### ISSUE TITLE
TF 2.4.0-rc3: Mismatched protobuf version in setup.py and workspace.bzl

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorflow#45300]
Protobuf version in `tensorflow/workspace.bzl` and `tensorflow/tools/pip_package/setup.py` aren't same in TF 2.4.0-rc3.
setup.py has protobuf 3.13 and workspace.bzl still fetches 3.9.2 during the build. Same is the case with master branch.
Is this intentional or to be done item?

**Comment by mihaimaruseac** [comment]
The one in workspace is used when compiling whereas the one in `setup.py` is needed at `pip install` time.

This is something that we should fix, but is there a bug that results from this? So we know how to prioritize?

**Comment by jayfurmanek** [comment]
According to: https://abi-laboratory.pro/?view=timeline&l=protobuf
protobuf 3.9 and 3.13 are not compatible (even the soname has changed). I'd think you'd want to ensure matching internal and external function, no?

**Comment by mihaimaruseac** [comment]
Hmm, you are right. Yes, this is something we need to fix. Thank you
