### ISSUE TITLE
I am trying to convert yolov3 to a full uint8 tflite model after, i got this error : Quantized not yet supported for op : 'EXP'

### ISSUE THREAD

**Issue by Tieckby** [tensorflow/tensorflow#45301]
**System information**
- I used Google Colab.
- TensorFlow installed from google colab :
- TensorFlow version 2.3.0, after I tried 2.3.1 and 2.4.0-rc2 (it gives the same error):

**I'm using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook
https://colab.research.google.com/drive/1i1gXJyVpiu9qngAiQEhMZoU1Q6LFKf0j#scrollTo=3CPc8AYBxa1U
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model("yolov3-416")
def representative_dataset_gen():
    for _ in range(250):
        yield [tf.random.uniform(shape=[1, 416, 416, 3], minval=0.0, maxval=1.0, dtype=tf.dtypes.float32)]

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]    
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.allow_custom_ops = True
converter.representative_dataset = representative_dataset_gen
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model_uint8_io = converter.convert()
# Save the model.
with open('tflite_quant_model_uint8_io.tflite', 'wb') as f:
  f.write(tflite_quant_model_uint8_io)

**The output from the converter invocation**
Traceback (most recent call last):
  File "convertToTflite_uint8_io.py", line 15, in <module>
    tflite_quant_model_uint8_io = converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 742, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py", line 461, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py", line 104, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'.
Quantization not yet supported for op: 'EXP'

**Comment by ravikyram** [comment]
@Tieckby 

Please, grant me the access for the colab link you have provided. Thanks!

**Comment by Tieckby** [comment]
https://colab.research.google.com/drive/10BCL6_F5RQz_mMsB7VIKU8dABFJswlBB

Share link

**Comment by ai1361720220000** [comment]
Have you solved the problem? I met the same problem while transform the pb file into tflite file.

**Comment by Tieckby** [comment]
Not yet

**Comment by sushreebarsa** [comment]
@Tieckby It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!
