### ISSUE TITLE
TFlite gets the incorrect value dividing by zero or computing tf.log(x)

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#45312]
**System information**
- OS Platform and Distribution: MacOS Catalina 10.15.6
- TensorFlow installed: from binary
- TensorFlow version: The issue could be reproduced by TF1.x (TF 1.15.2) and TF2.x (TF 2.3.1)
- Python version: 3.6.5

**Describe the current behavior**
I have the following code that simply creates a TF graph whose output tensor is an input placeholder divided by a float32 constant 0. I would expect the evaluation value of the output tensor to be always "Inf" no matter which value is fed into the input placeholder. However, what I got from the following example is, the result from Tensorflow is expected, while the one from TFlite is the max limit of float32.

```
import os
import re
import tempfile

import numpy as np
import tensorflow as tf

is_tf_2 = bool(re.match("2\.[0-9]+\.[0-9]+", tf.version.VERSION))
if is_tf_2:
    print("using TF2.x")
    import tensorflow.compat.v1 as tf

    tf.compat.v1.disable_eager_execution()


def run_tf_ops():
    input_tensor = tf.placeholder(dtype=tf.float32, shape=[None])
    b = tf.constant(0.0, dtype=tf.float32)
    output_tensor = tf.divide(input_tensor, b)

    tf_session = tf.Session()

    with tempfile.TemporaryDirectory("") as tempdir:
        converter = tf.lite.TFLiteConverter.from_session(
            sess=tf_session,
            input_tensors=[input_tensor],
            output_tensors=[output_tensor],
        )
        tflite_model = converter.convert()
        tflite_saved_model_path = os.path.join(tempdir, "saved_model.tflite")
        with open(tflite_saved_model_path, "wb") as f:
            f.write(tflite_model)

        # Test TFLite load
        # Load the TFLite model and allocate tensors.
        interpreter = tf.lite.Interpreter(model_path=tflite_saved_model_path)
        interpreter.allocate_tensors()
        # Get input and output tensors.
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()

        # Test the model on random input data.
        # get output from tflite model
        interpreter.set_tensor(input_details[0]["index"], [np.float32(1.0)])
        interpreter.invoke()
        output_data_from_tflite = interpreter.get_tensor(output_details[0]["index"])

    print(
        f"Tensorflow result: {tf_session.run(output_tensor, feed_dict={input_tensor: [np.float32(1.0)]})}"
    )
    print(f"TFLite result: {output_data_from_tflite}")


if __name__ == "__main__":
    run_tf_ops()
```
The interesting behavior is if I replace the input placeholder `input_tensor` with a constant float32 tensor like `input_tensor = tf.constant(value=[1.0], dtype=tf.float32)`(also remove the code on feeding data), both Tensorflow and TFlite get the correct result `Inf` in TF 1.15.2, but would have the same issue in TF 2.3.1.

**NOTE** The same behavior happens for other operations such as "tf.log(x)" when we feed x with run time data 0.

**Standalone code to reproduce the issue**
The issue could be 100% reproduced by running the above code with the system info.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version(`2.5.0-dev20201201`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/bf3062f1ab3fee71e5b3951ef70e5d4a/untitled557.ipynb).Thanks!

**Comment by jdduke** [comment]
@TJ can you take a look?

**Comment by thaink** [comment]
@RuofanKong @WindQAQ Is this inconsistency in behaviors blocking/affecting your model?
Dividing to zeros or inf values are not so common I guess.

We had a discussion on the PR internally, The PR itself looks OK but output inf results may affect subsequent ops. We need to investigate how all the ops are handing inf values first to ensure not to break the compatibility. That might be a long investigation.

**Comment by WindQAQ** [comment]
From my side, we have a check by using `isinf` to detect `inf` and reset them to zero. It's ok for me not to push the change. We have handled it by checking extreme large/small value instead. Thanks!

**Comment by WindQAQ** [comment]
FYI, we have also observed that XNNPACK delegate uses infinity as upper/lower bound, which results in different behavior across TFLite

**Comment by thaink** [comment]
Thanks for your update. It is still a good point to close the gap between TF and TFLite inf-handling behaviors. We'll put it as a longer-term goal.

**Comment by WindQAQ** [comment]
Thanks for the effort. Here are some other info about inf that you might be interested.

- init value of maxpool and reduce min/max.
- Some calls to other kernels that needs to set activation min/max, such as BroadcastPow4D and LstmCell.

**Comment by RuofanKong** [comment]
@thaink Thanks for helping it! On our end, this is indeed blocker issues for our model, when any invalid computation ops are involved, we have no way to tell the output is valid vs invalid values per clipping results, but TF is good. So it would be good to fix it.

**Comment by thaink** [comment]
@RuofanKong I think there should be some way to avoid inf value being produced, like checking if dividing to 0 or use isinf for input.

**Comment by RuofanKong** [comment]
@thaink The problem is lots of this particular checking on the invalid values (e.g. "tf.math.is_nan") are not supported in TFlite..

**Comment by thaink** [comment]
the tf.is_nan is supported in TFLite by lowering to equal op.
Could you try to convert with nightly?

**Comment by RuofanKong** [comment]
@thaink Okay as I was on the older TF 2.x version, and it's great to see more ops are supported in TFlite now!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/347ccd9fd9aa347676bf92caa810baeb/45312.ipynb). Thanks!

**Comment by chunduriv** [comment]
Was able to replicate issue in tf-nightly(2.8.0-dev20211009), please find the gist [here](https://colab.research.google.com/gist/chunduriv/26b98f3f5c4a39fc6761b0e523fc739c/45312.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
@RuofanKong  Please have the look at the [gist](https://colab.research.google.com/gist/sushreebarsa/24fa85d95ffee715f2d055b56869c699/gist45321.ipynb) on colab using TF v2.8.0 , and didn't face the reported issue. Could you please confirm the same?Thank you!
