### ISSUE TITLE
tf.shape is broken when drop_remainder=True on TPUs

### ISSUE THREAD

**Issue by idavidrein** [tensorflow/tensorflow#45317]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
tf.shape gives incorrect tensor shapes when used with `drop_remainder=False` while batching a Dataset on TPUs.

**Describe the expected behavior**
tf.shape should always return the correct tensor shape regardless of the value of `drop_remainder`.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1EcQMGADKDdVTo5yETzYr3IUfqHjDMzX0?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.3 and was able to reproduce the issue. However in TF nightly i am seeing the error (`NotFoundError: 'OptimizeDatasetV2' is neither a type of a primitive operation nor a name of a function registered in binary running on n-6e00c1af-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:__inference_run_576]`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1e772687b9d16778dfcdc51d2a9ff803/untitled556.ipynb). Thanks!

**Comment by gagika** [comment]
Please remove `with tpu_strategy.scope():` from your code, as you are already running through `strategy.run`.

This should run correctly:
```
@tf.function
def run(ds, strategy):
  def step(features):
    x = tf.concat([features['a'], features['b']], axis=0)
    return x, tf.shape(x)[0]
  return strategy.run(step, args=(next(ds),))

print(run(ds, tpu_strategy))
```

Also, running something on a TPU, please choose your batch size to be a multiple of the number of cores (8 in this case).

If you need to run tf-nightly in colab, besides installing Tensorflow `tf-nightly` version, you will also need to choose a corresponding Tensorflow version on TPU, please see [here](https://stackoverflow.com/questions/63180202/invalidargumenterror-while-initializing-ttpu/63271669#63271669) for the commands.

**Comment by idavidrein** [comment]
> Please remove `with tpu_strategy.scope():` from your code, as you are already running through `strategy.run`.
> 
> This should run correctly:
> 
> ```
> @tf.function
> def run(ds, strategy):
>   def step(features):
>     x = tf.concat([features['a'], features['b']], axis=0)
>     return x, tf.shape(x)[0]
>   return strategy.run(step, args=(next(ds),))
> 
> print(run(ds, tpu_strategy))
> ```
> 
> Also, when running on a TPU, please choose your batch size to be a multiple of the number of cores (8 in this case).
> 
> If you need to run tf-nightly in colab, besides installing Tensorflow `tf-nightly` version in colab, you will also need to choose a corresponding Tensorflow version on TPU, please see [here](https://stackoverflow.com/questions/63180202/invalidargumenterror-while-initializing-ttpu/63271669#63271669) for the commands.

Hi, thank you for the tips! However, removing the scope() and changing the batch size doesn't seem to work unfortunately, as you can see here: https://colab.research.google.com/drive/1EcQMGADKDdVTo5yETzYr3IUfqHjDMzX0?usp=sharing

**Comment by gagika** [comment]
> Hi, thank you for the tips! However, removing the scope() and changing the batch size doesn't seem to work unfortunately, as you can see here: https://colab.research.google.com/drive/1EcQMGADKDdVTo5yETzYr3IUfqHjDMzX0?usp=sharing

Looks like this issue was fixed in tf-nightly.

To test on tf-nightly, you can use the following code in colab:

```
!pip install tf-nightly
```

Restart the runtime and run:
```
!pip install cloud-tpu-client

import tensorflow as tf
from cloud_tpu_client import Client
print(tf.__version__)

Client().configure_tpu_version(tf.__version__, restart_type='ifNeeded')
```

After which the shape should work correctly.

Another thing that you can try for TF 2.3 is disabling dynamic batch size in strategy.run:
```
strategy.run(step, args=(next(ds),), options=tf.distribute.RunOptions(experimental_enable_dynamic_batch_size=False))
```

**Comment by idavidrein** [comment]
@gagika Yeah that works! Thanks for the help :+1:
