### ISSUE TITLE
Support for CUDA 11.1 and RTX 3090

### ISSUE THREAD

**Issue by jediyoda36** [tensorflow/tensorflow#45319]
**System information**
- TensorFlow version: tf-nightly-gpu-2.5.0.dev20201201
- System: Ubuntu 18.04
- CUDA: 11.1
- NVIDIA Driver: 455.23.05

I just installed `tf-nightly-gpu-2.5.0.dev20201201` on my machine, and trying to run a test script, and errors shows below:

![image](https://user-images.githubusercontent.com/13287220/100816986-3dabe380-3482-11eb-9ffc-e2691251940c.png)

**Comment by amahendrakar** [comment]
@jediyoda36,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/43947#issuecomment-715295153) from issue #43947 with a similar error and let us know if it helps. Thanks!

**Comment by jediyoda36** [comment]
@amahendrakar,
I'm not sure whether I can do this. I'm also using PyTorch in other project. If I change this soft link, will it affect PyTorch?

**Comment by jediyoda36** [comment]
I've resolved this problem with the method mentioned in [this issue]( https://github.com/tensorflow/tensorflow/issues/44682#issuecomment-732283634)
