### ISSUE TITLE
illegal hardware instruction  python while import tensorflow2.2.0

### ISSUE THREAD

**Issue by moseshu** [tensorflow/tensorflow#45323]
**My System information**
- OS Platform and Distribution (e.g.MacOS Bigsur 11.0 M1 Chip):
- TensorFlow installed from (pip3 install tensorflow==2.2.0):
- TensorFlow version (tf2.2.0):

I use pip3 install tensorflow==2.2.0,but when i import tensorflow as tf, it gave me an error "illegal hardware instruction  python3", my MacOS is BigSur 11.0,M1 chip. is this problem from BigSur or M1 chip? how to solve it ?

**Comment by amahendrakar** [comment]
@moseshu,
The Apple TF on M1 chips is a private fork of TF owned by Apple. We don't have access to fixing code issues there.

For more information, please go through issue [#44751](https://github.com/tensorflow/tensorflow/issues/44751#issuecomment-729896963). Thanks!

**Comment by kklingeman** [comment]
can this be re-opened, please?  this is still an issue.
