### ISSUE TITLE
variable_scope inherits attributes

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#45329]
```python
import tensorflow
def _custom_getter(getter, *args, **kwargs):
  return getter(*args, **kwargs) 
with tf.compat.v1.variable_scope('', custom_getter=_custom_getter):
  scope = tf.compat.v1.get_variable_scope()
  scope2 = tf.compat.v1.variable_scope(scope)
  print(scope2._custom_getter) # return None
```
New ```variable_scope``` doesn't inherit last ```variable_scope```'s attributes. Is it expected behavior?

**Comment by amahendrakar** [comment]
@fsx950223,
On running with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/021798093fbbf45e93770d191af2a52a/45329.ipynb), the code snippet prints `None` twice. Whereas, with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ee4b1f520eb8a7eb9723939f6a7f3595/45329-tf-nightly.ipynb) the code prints `None` only once. Please check the linked gist for reference. 

Could you please confirm, if you've got the same results. Thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/021798093fbbf45e93770d191af2a52a/45329.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ee4b1f520eb8a7eb9723939f6a7f3595/45329-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!
