### ISSUE TITLE
RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE', after QAT quantize_apply()

### ISSUE THREAD

**Issue by limbtio** [tensorflow/tensorflow#45328]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.5.0.dev20201130

I'm trying to apply quantization on a keras model for quantization aware training and then int8 quantize the model with tflite.
I successfully annotated only the supported layers and use tfmot.quantization.keras.quantize_apply. But, when I try to quantize the quant aware model I get this error multiple times:
RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE'.
Am I doing something wrong?

**Code**
(Just need to change ```directory``` to a folder with some calibration images from COCO)
```
import cv2
import numpy as np
import os
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow import keras


def apply_quantization_to_supported_layers(layer):
    if isinstance(layer, tf.keras.layers.ReLU):
        return tfmot.quantization.keras.quantize_annotate_layer(layer)
    elif isinstance(layer, tf.keras.layers.Activation):
        if not layer.activation.__name__ == 'sigmoid':
            return tfmot.quantization.keras.quantize_annotate_layer(layer)
    elif isinstance(layer, tf.keras.layers.DepthwiseConv2D):
        return tfmot.quantization.keras.quantize_annotate_layer(layer)
    elif isinstance(layer, tf.keras.layers.Conv2D) and not isinstance(layer, tf.keras.layers.Conv2DTranspose):
        # Conv2DTranspose inherits from Conv2D
        return tfmot.quantization.keras.quantize_annotate_layer(layer)
    return layer


def read_and_process_image(fname):
    img = cv2.imread(fname)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, dsize=(224, 224), interpolation=cv2.INTER_LANCZOS4)
    img = img / 127.5
    img = img - 1
    img = img.astype(np.float32)
    img = img.reshape(1, 224, 224, 3)
    return img


def representative_data_gen():
    directory = r'C:\user\calibrationsImages'
    for filename in os.listdir(directory):
        if filename.endswith(".jpg"):
            image_path = os.path.join(directory, filename)
            img = read_and_process_image(image_path)
            img_in = np.array(img)
            yield [img_in]
        else:
            continue


if __name__ == "__main__":

    print(tf.version.VERSION)
    orig_model_path = "model.hdf5"

    # load regularly trained model
    model = keras.models.load_model(orig_model_path)
    model.summary()  # print model layers

    # convert supported layers to quantization aware
    annotated_model = tf.keras.models.clone_model(
        model,
        clone_function=apply_quantization_to_supported_layers,
    )

    quant_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
    quant_aware_model.summary()

    adam = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, decay=0.0, amsgrad=False)
    quant_aware_model.compile(optimizer=adam,
                              loss="binary_crossentropy")

    quant_aware_model.summary()

    # quantize quantization aware model to int8
    converter = tf.lite.TFLiteConverter.from_keras_model(quant_aware_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_data_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

    tflite_quant_model = converter.convert()

    open('model.tflite', 'wb').write(tflite_quant_model)

```

**The error I'm getting**

```
Traceback (most recent call last):
  File "C:/REPOSITORIES/QuantizationAwareTraining/forTfIssue.py", line 78, in <module>
    tflite_quant_model = converter.convert()
  File "C:\Users\limorb\Anaconda3\envs\QuantizationAwareTraining\lib\site-packages\tensorflow\lite\python\lite.py", line 895, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "C:\Users\limorb\Anaconda3\envs\QuantizationAwareTraining\lib\site-packages\tensorflow\lite\python\lite.py", line 653, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "C:\Users\limorb\Anaconda3\envs\QuantizationAwareTraining\lib\site-packages\tensorflow\lite\python\lite.py", line 481, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "C:\Users\limorb\Anaconda3\envs\QuantizationAwareTraining\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 104, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE'.
Quantization not yet supported for op: 'DEQUANTIZE'.
Quantization not yet supported for op: 'DEQUANTIZE'.
Quantization not yet supported for op: 'DEQUANTIZE'.
Quantization not yet supported for op: 'DEQUANTIZE'.
. 
.
.
```

**Link to model**

[model.zip](https://drive.google.com/file/d/1eopi5IdNKPTJimK0Bb1q-8TYZc7IY5sp/view?usp=sharing)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/b4f2d8570c93f6612ecbb451c86df8a3/45328.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3354c2211a47b12df9348599cdb49589/45328-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by limbtio** [comment]
Hi, is there any update on this matter?

**Comment by limbtio** [comment]
Hi, I was able to quant-aware the model, but when I'm trying to convert it to tflite using this code:

    converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_quant_model = converter.convert()

I get the following error:
error: 'tfl.pad' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 0.16100097357058057:-128> vs. !quant.uniform<i8:f32, 0.023529411764705882:-128>

tf version: 2.5.0-dev20210204
Here is the quant-aware model
[qat_model.zip](https://drive.google.com/file/d/1CgLDjrq2lZfgtp0U9mkvN2ZSuicwXjHO/view?usp=sharing)

**Comment by limbtio** [comment]
Hi, I was able to quant-aware the model, but when I'm trying to convert it to tflite using this code:

    converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_quant_model = converter.convert()

I get the following error:
error: 'tfl.pad' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 0.16100097357058057:-128> vs. !quant.uniform<i8:f32, 0.023529411764705882:-128>

tf version: 2.5.0-dev20210204
Here is the quant-aware model
[qat_model.zip](https://drive.google.com/file/d/1CgLDjrq2lZfgtp0U9mkvN2ZSuicwXjHO/view?usp=sharing)

**Comment by ai1361720220000** [comment]
> Hi, I was able to quant-aware the model, but when I'm trying to convert it to tflite using this code:
> 
> ```
> converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> tflite_quant_model = converter.convert()
> ```
> 
> I get the following error:
> error: 'tfl.pad' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 0.16100097357058057:-128> vs. !quant.uniform<i8:f32, 0.023529411764705882:-128>
> 
> tf version: 2.5.0-dev20210204
> Here is the quant-aware model
> [qat_model.zip](https://drive.google.com/file/d/1CgLDjrq2lZfgtp0U9mkvN2ZSuicwXjHO/view?usp=sharing)

hello, i have the same error when quant my model to uint8 model. tf version 2.5.0.  Have you solved the problem?

**Comment by pjpratik** [comment]
@limbtio The quant aware model can be loaded using _tfmot.quantization.keras.quantize_scope_ as given in the [documentation](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization/keras/quantize_scope). Was able to run this on TF 2.11 using the given [quant-aware model](https://drive.google.com/file/d/1CgLDjrq2lZfgtp0U9mkvN2ZSuicwXjHO/view) .Please find the gist [here](https://colab.research.google.com/gist/pjpratik/7be378592cdc202dfb77ca8dc2a8b838/45328.ipynb) and let us know if this helps. Thank you.
