### ISSUE TITLE
tf.keras.preprocessing.image.random_shift consistently failing in graph mode

### ISSUE THREAD

**Issue by donglinz** [tensorflow/tensorflow#45325]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.6.5
- GPU model and memory: 32G V100, 4G GTX 1650 with Max-Q Design

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
tf.compat.v1.disable_eager_execution()
image = tf.random.uniform([3,32,32])
img = tf.keras.preprocessing.image.random_shift(image, hrg=0.3, wrg=0.3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dz/.conda/envs/py37cu101/lib/python3.7/site-packages/keras_preprocessing/image/affine_transformations.py", line 89, in random_shift
    order=interpolation_order)
  File "/home/dz/.conda/envs/py37cu101/lib/python3.7/site-packages/keras_preprocessing/image/affine_transformations.py", line 323, in apply_affine_transform
    x = np.rollaxis(x, channel_axis, 0)
  File "<__array_function__ internals>", line 6, in rollaxis
  File "/home/dz/.conda/envs/py37cu101/lib/python3.7/site-packages/numpy/core/numeric.py", line 1259, in rollaxis
    n = a.ndim
AttributeError: 'Tensor' object has no attribute 'ndim'
```
**Describe the expected behavior**
Random shift the image with no error
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
image = tf.random.uniform([3,32,32])
img = tf.keras.preprocessing.image.random_shift(image, hrg=0.3, wrg=0.3)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/1db118e00f20bed9fac0f4f380d61605/45325.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/1a15fd8ae4052b09952d5c616e6cda57/45325-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by donglinz** [comment]
Greetings! Any update on this?

**Comment by jvishnuvardhan** [comment]
@donglinz Sorry for the late response. In the graph mode, as the error shows 'Tensor' object has no attribute 'ndim'. However running it in eager mode will work without any issue.  [Here](https://colab.research.google.com/gist/jvishnuvardhan/9a7ec379c7ea3cacc3a77173eb35bdf9/45325-tf-nightly.ipynb) is a gist for our reference. 

Why do you want to disable eager execution? Is there any specific reason for your use-case? Thanks!

**Comment by donglinz** [comment]
Hi @jvishnuvardhan
Thanks for the response! I was using tf.data.Dataset.map for data augmentation which has to be running in the graph mode. I know I can use tf.py_function to wrap some python logic to do the same thing in graph mode as tf.keras.preprocessing.image.random_shift did in eager mode. But generally speaking, tf.py_function have much lower performance compared to built-in tensorflow operations. Does tensorflow have any alternatives that support shift image randomly in graph model?

**Comment by fchollet** [comment]
Hello,

`tf.keras.preprocessing.image.random_shift` explicity only works with NumPy arrays (or eager tensors), as specified in the documentation. It isn't meant to operate on graph tensors.

Also note that it is outdated functionality. If you need equivalent functionality that works on both arrays and tensors and in graph mode, you can use the preprocessing layer `RandomTranslation`: https://keras.io/api/layers/preprocessing_layers/image_preprocessing/random_translation/
