### ISSUE TITLE
Training in Colab always gives an error of "FailedPreconditionError"

### ISSUE THREAD

**Issue by androuino** [tensorflow/tensorflow#45327]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Google Colab

Started training in Colab but unfortunately, I am always having this error:
`
WARNING:tensorflow:Unresolved object in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_mean
W1202 07:14:44.360409 139666145298304 util.py:150] Unresolved object in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_mean
WARNING:tensorflow:Unresolved object in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_variance
W1202 07:14:44.360842 139666145298304 util.py:150] Unresolved object in checkpoint: (root).model._box_predictor._base_tower_layers_for_heads.class_predictions_with_background.4.10.moving_variance
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
W1202 07:14:44.361112 139666145298304 util.py:158] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/guide/checkpoint#loading_mechanics for details.
WARNING:tensorflow:FailedPreconditionError: models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint; Is a directory
W1202 07:14:44.364649 139666145298304 checkpoint_management.py:295] FailedPreconditionError: models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint; Is a directory
WARNING:tensorflow:models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint: Checkpoint ignored
W1202 07:14:44.364827 139666145298304 checkpoint_management.py:296] models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint: Checkpoint ignored
WARNING:tensorflow:FailedPreconditionError: models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint; Is a directory
W1202 07:14:44.365584 139666145298304 checkpoint_management.py:295] FailedPreconditionError: models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint; Is a directory
WARNING:tensorflow:models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint: Checkpoint ignored
W1202 07:14:44.365750 139666145298304 checkpoint_management.py:296] models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint: Checkpoint ignored
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib_v2.py", line 627, in train_loop
    manager.save()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_management.py", line 819, in save
    self._record_state()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_management.py", line 728, in _record_state
    save_relative_paths=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_management.py", line 248, in update_checkpoint_state_internal
    text_format.MessageToString(ckpt))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 570, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 529, in rename
    rename_v2(oldname, newname, overwrite)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 546, in rename_v2
    compat.as_bytes(src), compat.as_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.FailedPreconditionError: models/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8/checkpoint.tmp1e96a55bc7b14447b94ca71713ebdea9; Is a directory
`

I don't have any idea why it keeps saying the checkpoint.tmp is a directory?

Appreciate your help.

This is my [pipeline.config](https://gist.github.com/androuino/200aa56039b1cfeb02ed6bb301ffa51a)

**Comment by ravikyram** [comment]
@androuino 

Request you to flll [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by androuino** [comment]
Hi @ravikyram, thank you for your response. This is the colab [link](https://colab.research.google.com/drive/1rrXAduY_KqezWmfID7Q6c5h92W9nWxw5?usp=sharing).

Please use this [link](https://www.kaggle.com/jipingsun/object-detection-obama/download) for a simple set of data for training.

And this is the [link](https://medium.com/swlh/tensorflow-2-object-detection-api-with-google-colab-b2af171e81cc) I am following for the tutorial.

Thank you and have a nice day.

**Comment by ravikyram** [comment]
@androuino 

Please, grant me the access for the colab link. Thanks!

**Comment by androuino** [comment]
Hi @ravikyram, thanks for your fast reply. Please kindly check if you already have access to my colab notebook.

Thank you.

Have a great day.

**Comment by ravikyram** [comment]
@androuino 

This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thanks!

**Comment by androuino** [comment]
@ravikyram, oh ok. Thanks for routing me to models repo.

**Comment by ravikyram** [comment]
@androuino 

Please, close this thread here and we can track the issue in Tensorflow Models repo. Thanks!
