### ISSUE TITLE
tf.keras.preprocessing.image.random_shear raises TypeError when it is mapped to a tf dataset.

### ISSUE THREAD

**Issue by Crispy13** [tensorflow/tensorflow#45326]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-3819cfbfb025> in <module>()
----> 1 for i in tfd.map(test):
      2   print(i.shape)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):
--> 258           raise e.ag_error_metadata.to_exception(e)
    259         else:
    260           raise

TypeError: in user code:

    <ipython-input-4-bf71d3ba553f>:3 test  *
        image_5 = tf.keras.preprocessing.image.random_shear(image_4, intensity = shear_angle, row_axis=0, col_axis=1, channel_axis=2)
    /usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/affine_transformations.py:114 random_shear  *
        shear = np.random.uniform(-intensity, intensity)
    mtrand.pyx:1083 numpy.random.mtrand.RandomState.uniform  **
        

    TypeError: __array__() takes 1 positional argument but 2 were given
```

Please check **this Colab notebook:**
https://colab.research.google.com/drive/1SWl5cGiSTa_ML2zmQFpTvs6SIqOH7qNW?usp=sharing

When editing some part of code got it work, but it can't be used for map method of tfdataset.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/edc528ea775af52e7aa90afbad637d01/45326.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/5b55c740767fca2cb532c169306ac5c7/45326-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by bhack** [comment]
@Crispy13 the problem I think is that `random_shear` is implemented as numpy/scipy function:
https://github.com/keras-team/keras-preprocessing/blob/58df11e1145b2088092252c4dba02168c6da2b13/keras_preprocessing/image/affine_transformations.py#L99

With map you are passing a Tensor cause you are in graph mode. Probably you could to use map with `py_function` or explore shear augmentations from Tensorflow addons in @tanzhenyu https://github.com/tanzhenyu/image_augmentation/blob/master/image_augmentation/image/README.md

@tanzhenyu I think that probably we need to add an extra checks to this old scipy/PIL functions for the input type to give a better error message to developers.

**Comment by Crispy13** [comment]
@bhack
So is it intended to not use tensor with the `random_shear` function?

**Comment by bhack** [comment]
Check the input at:

https://github.com/keras-team/keras-preprocessing/blob/58df11e1145b2088092252c4dba02168c6da2b13/keras_preprocessing/image/affine_transformations.py#L281

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/0aa6d6de6bf542f23dc7c10df2c4cea4/45326-tf-nightly.ipynb#scrollTo=o0dEQAmaUikk)..Thanks !

**Comment by chunduriv** [comment]
@Crispy13, While trying to reproduce your issue in `tf-nightly(2.8.0-dev20211009)` facing different error, please find the gist [here](https://colab.research.google.com/gist/chunduriv/b94010827e1cd34414b39fd99432fe89/45326.ipynb),Thanks!

**Comment by sachinprasadhs** [comment]
Could you please try with any other pipeline and confirm of the same issue is occurring with `.map()` function. 
Also, please refer [this](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#map) document for `.map()` function for different type of input.

**Comment by bhack** [comment]
I suggest to use random shear from keras-cv

https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/random_shear_test.py
