### ISSUE TITLE
MLIR

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#45333]
**System information**
- Windows 10 Pro
- TensorFlow source, 2.3.1
- targeting Cortex-M4, Cortex-M7, Cortex-M33, ARM CortexM flavors

**Describe the problem**
I'd like to know if there any connection between TensorFlow-MLIR and TensorFlow Lite for Microcontrollers?
Can TensorFlow-MLIR support TensorFlow Lite for Microcontrollers for ARM Cortex M flavors?

Thank you for your insight.

**Comment by bhack** [comment]
This is already tracked at https://llvm.discourse.group/t/mlir-for-tf-mikro-arm-cortex-m/2331/3

**Comment by ymodak** [comment]
Since the issue is being addressed at LLVM Discussion Forum as tagged above we may continue the discussion on that thread. Closing this issue for now. Thanks!
