### ISSUE TITLE
Post-training quantization same model get different result for tf.concat

### ISSUE THREAD

**Issue by ZhouKai90** [tensorflow/tensorflow#45330]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04 in docker
- TensorFlow installed from (source or binary): binary pip install
- TensorFlow version (or github SHA if from source):2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
def representative_dataset_gen_img(imgCnt=20):
    imgDir = os.path.abspath(FLAGS.quan_images)
    imgNameList = glob.glob(os.path.join(imgDir, '*.jpg'))
    imgIndex = random.sample(range(len(imgNameList)), len(imgNameList) if imgCnt == 0 else imgCnt)
    for i in imgIndex:
        imgMat = cv2.imread(imgNameList[i])
        imgMat = utils.image_preporcess(np.copy(imgMat), [FLAGS.input_size[0], FLAGS.input_size[1]])
        imgMat = imgMat[np.newaxis,:,:,:]
        yield [imgMat.astype(np.float32)]

def convert_tflite_from_keras():
	#converter = tf.lite.TFLiteConverter.from_keras_model(model)
	converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(kerasH5File)
	converter.optimizations = [tf.lite.Optimize.DEFAULT]
	converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
	converter.inference_input_type = tf.uint8
	converter.inference_output_type = tf.uint8
	converter.representative_dataset = representative_dataset_gen_img
	TFLiteModel = converter.convert()
	open(TFLiteFile, "wb").write(TFLiteModel)

```
**Also, please include a link to the saved model or GraphDef**
[bad.h5](https://drive.google.com/file/d/11301633Tl5pUjq6DXC8p-VPPECVGYjM3/view?usp=sharing)
[good.h5](https://drive.google.com/file/d/1VsQZ-tfaxmouYo3fNdYFZT-mG_FSEqmx/view?usp=sharing)
[bad.tflite](https://drive.google.com/file/d/15ReLcnSGqz67j8KSZdHCMG-hTRj-KWPO/view?usp=sharing)
[good.tflite](https://drive.google.com/file/d/1910F-erSpyLUXIO6m6nvvxfXJCacn-2f/view?usp=sharing)

**Failure details**
I use the same tiny-yolov3 network to train two different target detection tasks, and use the same tflite Python API to quantify the model to get the tflite model.However, one result of the two models after quantization is correct and the other is wrong. After comparison, I found that the branch of "Quantize "node for concat OP quantization is different (as shown in the figure below).letf is ok, and right is bad.
![1](https://user-images.githubusercontent.com/20400418/100845353-0c4e0a80-34b8-11eb-836f-8ae8ad9411b7.png)
--Why does the same model have different quantization results?
--I've tried several versions of tensorflow, such as tf2.3, tf-nightly-2.5.0 and the problem remains

**Comment by ymodak** [comment]
It is not clear how you are getting different results on quantization perhaps you can explain more.
Are you observing incorrect results with `tf.compat.v1.lite.TFLiteConverter.from_keras_model_file` and correct results with `tf.lite.TFLiteConverter.from_keras_model` ?

**Comment by ZhouKai90** [comment]
> It is not clear how you are getting different results on quantization perhaps you can explain more.
> Are you observing incorrect results with `tf.compat.v1.lite.TFLiteConverter.from_keras_model_file` and correct results with `tf.lite.TFLiteConverter.from_keras_model` ?

No, I used the same Tiny-yolov3 network to train two different object detection tasks, and got two H5 models (good.h5 and bad.h5). also I used the same tflite python API `tf.compat.v1.lite.TFLiteConverter.from_keras_model_file` to convert the two H5 models, and got two tflite models(good.tflite and bad.tflite). The 'bad.tflite' is incorrect, After comparison, I found that the branch of "Quantize "node  is different for the two tflite models. I think that's what caused the incorrect results.

**Comment by pjpratik** [comment]
Hi @ZhouKai90 I was checking if this is still an issue.

Can you try the conversion process in latest TF 2.11 or TF nightly or by enabling `converter.experimental_new_converter = True`. It enables MLIR-based conversion which is true by default in the nightly and also `converter.experimental_new_quantizer = True` which enables MLIR-based quantization conversion instead of Flatbuffer-based conversion.

Thanks.

**Comment by mikel-brostrom** [comment]
Thank you for highlighting this @PINTO0309. Will try this later today for YOLOX.

**Comment by mikel-brostrom** [comment]
Tried to export with both Tensorflow 2.11.0 and  TF-nightly:

```bash
tensorflow     2.11.0
tf-nightly     2.13.0.dev20230317
protobuf       3.20.2
```

 The quanitzed models are still not working. Float32 & Float 16 works as usual

**Comment by pjpratik** [comment]
Hi @mikel-brostrom is the issue related to "Quantize" op after conversion?

**Comment by mikel-brostrom** [comment]
Yes, post-training quantization

**Comment by pkgoogle** [comment]
Hi @ZhouKai90 and @mikel-brostrom,

It seems the architecture of the original h5 files are not identical:

![screenshot_45330](https://user-images.githubusercontent.com/132095473/236055345-eaba855c-e63b-448e-8780-b00e6a4f14b6.png) (left side bad.h5), (right side good.h5)

The area which corresponds to the difference in the lite versions are actually different in the h5 files. Furthermore, the dimensionality of some elements have changed from the start to the red arrow and downwards. Can either of you try again when the model architecture is identical prior to conversion?
