### ISSUE TITLE
Feed batch of images in Java

### ISSUE THREAD

**Issue by iglaweb** [tensorflow/tensorflow#45347]
Seems like documentation is missing for providing multiple inputs for tensorflow model (.pb) in Java. Could you help how to provide multiple jpg byte[] images to model? Version of Tensorflow java is 2.3. Type of model input is type float32[?,100,100,1]

```
      private static final int SIZE = 100;
      private static final float MEAN = 256f;

        Graph graph = new Graph();
        GraphBuilder b = new GraphBuilder(graph);
        final Output<String> input = b.placeholder("input", DataType.STRING);      
  Output<Float> graphOutput =
                b.div(
                        b.resizeBilinear( // Resize using bilinear interpolation
                                b.expandDims(
                                        b.cast(b.decodeJpeg(input, 1), Float.class),
                                        b.constant("make_batch", 0)),
                                b.constant("size", new int[]{SIZE, SIZE})),
                        b.constant("scale", MEAN));
        byte[] image = ....;
        Tensor inputTensor = Tensor.create(image);
        List<Tensor<?>> tensorList = session.runner()
                .feed(inputOp, inputTensor)
                .fetch(graphOutput.op().name()).run();
       // get image tensor
        Tensor<Float> imageTensor = tensorList.get(0).expect(Float.class);
        for (int i = 1; i < tensorList.size(); i++) {
            tensorList.get(i).close();
        }
        inputTensor.close();
```

**Comment by rthadur** [comment]
@iglaweb Are you using [tensorflow/java](https://github.com/tensorflow/java/issues) here ? Can you please provide where exactly the documentation is missing ?

**Comment by iglaweb** [comment]
@rthadur Yeah, I use tensorflow/java v.2.3.0 that was recently deprecated. I cannot figure out how to provide multiple inputs for the model.

**Comment by rthadur** [comment]
@iglaweb please post this issue on [tensorflow/java ](https://github.com/tensorflow/java/issues) where it would be relevant.

**Comment by SmartMapple** [comment]
Had the question solevd? can tensorflow support multiple inputs?

**Comment by rthadur** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
