### ISSUE TITLE
Enhancement: Locally Connected layers 

### ISSUE THREAD

**Issue by jeandut** [tensorflow/tensorflow#4534]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

http://stackoverflow.com/questions/34858459/tensorflow-not-sharing-variables
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/S5_xohNLwgs

I need to implement a network with locally connected layers (convolution without weight sharing) with 2D inputs (images).

I was wondering if the implementation of this feature is on the roadmap or if there exists some clever hacks using existing TF functions to do it.

**EDIT:** It seems this kind of layer is often used for face classification for instance in [DeepFace](https://www.cs.toronto.edu/~ranzato/publications/taigman_cvpr14.pdf).

**Comment by jmchen-g** [comment]
@mrry Since you replied in SO. Do you know if anyone is working on this?

**Comment by mrry** [comment]
@jmchen-g I've no idea.

**Comment by jeandut** [comment]
I thought about trying to add the op in C++ myself but thinking about it it looks fairly difficult. Any update on this ?

**Comment by thtrieu** [comment]
Anyone with workaround / clever hacks for this instead of brute force? I came across this issue today. 6D kernel seems intimidating ...

**Comment by ronrest** [comment]
Even if this feature does not get included in the Tensorflow code, I would like to know if anyone has any working code (or link to working code) for implementing Locally Connected Layers in tensorflow.

**Comment by wugang33** [comment]
I found this for a time. Only find keras implements https://www.tensorflow.org/api_docs/python/tf/contrib/keras/layers/LocallyConnected2D
