### ISSUE TITLE
"bluepill" target build fails if repository pathname contains spaces

### ISSUE THREAD

**Issue by ddavis-2015** [tensorflow/tensorflow#45346]
@tensorflow/micro
@petewarden 

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  - Linux Ubuntu 18.04.5
- TensorFlow installed from (source or binary):
  - source
- Tensorflow version (commit SHA if source):
  - commit 753786571eb24b08f06506e2ff397358974a8c1d (HEAD -> master, origin/master, origin/HEAD)
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
  - bluepill (ARM emulator)

**Describe the problem**

Building a test for use with the emulator (TARGET=bluepill) fails in the shell script.  This is due to the repository pathname having a space character in it.  The following scripts do not have sufficient quote escapes:
- line 33 of tensorflow/lite/micro/testing/test_bluepill_binary.sh
- line 12 of tensorflow/lite/micro/tools/make/downloads/renode/test.sh

**Please provide the exact sequence of commands/steps when you ran into the problem**

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=bluepill test_kernel_mul_test
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:476: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:476: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/testing/test_bluepill_binary.sh tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3/bin/kernel_mul_test '~~~ALL TESTS PASSED~~~'
The following command failed: /media/ddavis/WETU Repo/git/tensorflow/tensorflow/lite/micro/testing/../tools/make/downloads/renode/test.sh. Please  make sure that you have correctly installed Renode for TFLM. See  tensorflow/lite/micro/docs/renode.md for more details.
tensorflow/lite/micro/tools/make/Makefile:532: recipe for target 'test_kernel_mul_test' failed
make: *** [test_kernel_mul_test] Error 1
```

**Comment by Saduf2019** [comment]
@ddavis-2015 Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!

**Comment by mohantym** [comment]
@ddavis-2015 ! Have you checked [this thread ](https://github.com/tensorflow/tensorflow/issues/45348#issuecomment-777661482)yet ?

**Comment by ddavis-2015** [comment]
I have not yet had a chance to test this with TF v2.6.0 as I am currently swamped with work in the tflite-micro and tflite-micro-arduino-examples repos.  But I do intend to re-test this in the coming weeks.

**Comment by mohantym** [comment]
Hi @ddavis-2015 !
I was able to compile with bluepill target with tflite-micro instructions.
!make -f /content/tflite-micro/tensorflow/lite/micro/tools/make/Makefile TARGET=bluepill test_kernel_mul_test
(provided full path and used tflite-micro repo)

Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/0889a8ce52ffda50597363028fc9bbbc/git_45346.ipynb#scrollTo=3ZJqtLv0gQcd)for reference.

Thank you!

**Comment by ddavis-2015** [comment]
@mohantym 

Thank you for reminding me about this issue.  I have just tested it, and it is still failing:

`tensorflow/lite/micro/testing/test_with_renode.sh gen/bluepill_x86_64_default/bin/kernel_mul_test '~~~ALL TESTS PASSED~~~' bluepill
The following command failed: /tmp/test tflm make/tflite-micro/tensorflow/lite/micro/testing/../tools/make/downloads/renode/test.sh. Please  make sure that you have correctly installed Renode for TFLM. See  tensorflow/lite/micro/docs/renode.md for more details.
tensorflow/lite/micro/kernels/Makefile.inc:119: recipe for target 'test_kernel_mul_test' failed
make: *** [test_kernel_mul_test] Error 1
`

Note the use of spaces in the directory name under /tmp: /tmp/**test tflm make**/tflite-micro

I also tested with a pathname that had no space characters, and that test had no failures.

**Comment by mohantym** [comment]
Ok @ddavis-2015 !
Thanks for the update. will try to come with a PR to address this issue .
Thank you!

**Comment by pjpratik** [comment]
Hi @ddavis-2015 

The issue seems to be resolved with the latest branch. I was able to build the target successfully without any error.

Please find the [gist](https://colab.research.google.com/gist/pjpratik/4292a0013cf5e07b2f68b43b1615747c/45346.ipynb) and can you confirm if it is resolved from your end?

Thanks.
