### ISSUE TITLE
.ckpt to .pb

### ISSUE THREAD

**Issue by gowthamvenkatsairam** [tensorflow/tensorflow#45341]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
No OpKernel was registered to support Op 'TPUReplicatedInput' used by {{node input0}} with these attrs: [N=16, is_packed=false, T=DT_INT32, index=0, is_mirrored_variable=false]
Registered devices: [CPU, GPU, XLA_CPU, XLA_GPU]
Registered kernels:
  <no registered kernels>

	 [[input0]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1333       # We add a more reasonable error message here to help users (b/110263146)
   1334       raise _wrap_restore_error_with_msg(
-> 1335           err, "a mismatch between the current graph and the graph")
   1336 
   1337   @staticmethod

**Describe the expected behavior**
the actual model contains .meta,.data,.index files
the model should be converted from .ckpt to .pb

**Standalone code to reproduce the issue**
import os
import tensorflow as tf

trained_checkpoint_prefix = 'models/model.ckpt-49491'
export_dir = os.path.join('export_dir', '0')

graph = tf.Graph()
with tf.compat.v1.Session(graph=graph) as sess:
    # Restore from checkpoint
    loader = tf.compat.v1.train.import_meta_graph(trained_checkpoint_prefix + '.meta')
    loader.restore(sess, trained_checkpoint_prefix)

    # Export checkpoint to SavedModel
    builder = tf.compat.v1.saved_model.builder.SavedModelBuilder(export_dir)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.TRAINING, tf.saved_model.SERVING],
                                         strip_default_attrs=True)
    builder.save()                
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@gowthamvenkatsairam,
On running the code, I am facing an error stating `OSError: File models/model.ckpt-49491.meta does not exist`. 

In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and all the required supporting files. Thanks!

**Comment by amahendrakar** [comment]
Also, please go through [this](https://stackoverflow.com/a/56793601) similar StackOverflow query and let us know if it helps. Thanks!

**Comment by gowthamvenkatsairam** [comment]
https://drive.google.com/file/d/0B3APw5BZJ67ETHNPaU9xUkVoV0U/view
model is available here

**Comment by gowthamvenkatsairam** [comment]
i also gone through the stackoverflow link that you have shared,but that does'nt solve the problem

**Comment by amahendrakar** [comment]
@gowthamvenkatsairam,
I was able to run the code with TF v2.3 without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6803c28df6e8ef8e1f8500948b5753ff/45341.ipynb). 

Could you please try running the code in a new virtual environment and check if you are facing the same issue. Thanks!
