### ISSUE TITLE
Contributing to TFlite Micro

### ISSUE THREAD

**Issue by puranjaymohan** [tensorflow/tensorflow#45350]
Hi,
I want to contribute to TFlite Micro. Please help me with getting started.
I have some hardware which might be useful for me to contribute, it includes: STM32 Nucleo-L476RG, Arduino Uno, Nano, Micro, Esp8266, and Esp32
I know Python and C programming.

P.S. - I am a hobbyist and want to contribute.
Thanks.

**Comment by ymodak** [comment]
Thanks for expressing your interest in contributing to TensorFlow.
We appreciate community reaching out and contributing to enhance TensorFlow's usage.
Please go through [contributor guidelines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/CONTRIBUTING.md) to start with.
Feel free to contribute in any way you can; improving the guides, documentation, tutorials, fixing bugs that you may encounter or encounter by other users.
We accept code/document changes in the form of Pull Request (PR).
So make sure to provide as much information as you can with your PR to help us better assess the case and review it.
I also encourage you to sign up for the [TensorFlow monthly newsletter](https://services.google.com/fb/forms/tensorflow/) for new updates.

**Comment by ymodak** [comment]
You can filter the GitHub issues on this repo with `good first issue` lablel. But I am afraid that we don't have any for `micro` at the moment. Never the less you can try taking a glance on `feature requests` or `bug` labelled micro issues.
Thank you.
