### ISSUE TITLE
how to understand handling val data with keras in tf2.1

### ISSUE THREAD

**Issue by jianku122** [tensorflow/tensorflow#45357]
I apply model.fit to handle val data.
model.fit(dataset,
                    epochs=4,
                    steps_per_epoch=32,  
                    validation_data=val_dataset, 
                    validation_steps=8,
                    callbacks=callbacks,
                    verbose=1
                    )
Steps respectively set are above, but logs only contain the training steps:
```
...
28/32 [=========================>....] - ETA: 4s - loss: 0.0045 - accuracy: 0.8959
29/32 [==========================>...] - ETA: 3s - loss: 0.0045 - accuracy: 0.8935
30/32 [===========================>..] - ETA: 2s - loss: 0.0045 - accuracy: 0.8940
31/32 [============================>.] - ETA: 1s - loss: 0.0045 - accuracy: 0.8926
2020-12-03 09:35:34.813262: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-12-03 09:35:34.818206: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled

Epoch 00002: saving model to .\log-output\saved_models\model_epoch02_val_acc0.89.ckpt

32/32 [==============================] - 181s 6s/step - loss: 0.0045 - accuracy: 0.8930 - val_loss: 0.0043 - val_accuracy: 0.8913

Epoch 3/4
...
```
It seems that only the first 31 steps are related to train data and the last step also includes the extra 8 validation steps. Is that right?
By th way, how to deal with the error "Cancelled: Operation was cancelled"?

tf 2.1
cuda 10.1
python 3.7
win10
GPU 2080Ti

**Comment by ravikyram** [comment]
@jianku122 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!
