### ISSUE TITLE
TFLite Converter for BiLSTM based architecture

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#45361]
**System information**: Default configuration of Google Colab. I ran this experiment on Colab and I am attaching the self-contained notebook.

I have been working on the conversion of [EasyOCR](https://github.com/JaidedAI/EasyOCR) to TFLite . I have been getting this error while converting to TFLite.
> ConverterError: input resource[0] expected type resource != float, the type of assignvariableop_resource_0[0]
	In {{node AssignVariableOp}}

I successfully converted the PyTorch Model to ONNX and ran the inference with sample data and the results are matching correctly. So I hope there are no issues in PyTorch --> ONNX conversion. Even there are no issues in converting to TensorFlow SavedModel. I am getting the error while converting the SavedModel to TFLite. 

**FYI:** Model consists of 2 layer Bi-Directional LSTM cells.

I have attached all the mentioned details in this [Notebook](https://colab.research.google.com/github/tulasiram58827/ocr_tflite/blob/main/colabs/easyocr_tflite_report.ipynb). To reproduce the above error you can use the same [Notebook](https://colab.research.google.com/github/tulasiram58827/ocr_tflite/blob/main/colabs/easyocr_tflite_report.ipynb).

The notebook provided itself is self-contained and will download and install all the necessary modules and files.

@amahendrakar

**Comment by ravikyram** [comment]
I have tried in TF nightly version(`2.5.0-dev20201202`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f3f533b14704175abbde6f5fbc1b480e/untitled561.ipynb). Thanks!

**Comment by tulasiram58827** [comment]
@ymodak

**Comment by abattery** [comment]
Sorry for encountering this issue. TFLite runtime is not able to handle mutable variable cases yet. We are working on improving this area.

**Comment by tulasiram58827** [comment]
Thanks @abattery for replying. Can I expect the support of mutable variables in further nightly releases of this month or is it planned for long term?

**Comment by abattery** [comment]
@tulasiram58827 we working on support for mutable variables. However, it will take some times. I will update this thread when the feature is available to use.

**Comment by tulasiram58827** [comment]
Thanks @abattery

**Comment by tulasiram58827** [comment]
Hi @abattery 

Can I expect the support for mutable variables in Q1

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/1fa9a6812f331ed23f2a0cc9f730acae/45361.ipynb). Thank you.

**Comment by pjpratik** [comment]
Hi @tulasiram58827 

You can try enabling resource variables by converting using saved model. I was able to successfully convert using the same and also by enabling select ops and tflite builtins.

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/f63b910b51910d62427a0a97c67332eb/45361.ipynb). 

Thanks.
