### ISSUE TITLE
 有关tensorflow estimator   About tensorflow estimator

### ISSUE THREAD

**Issue by anavanab99** [tensorflow/tensorflow#45364]
I am using the estimator model to process some financial data. The API is tf.estimator.DNNLinearCombinedRegressor However, the document does not provide a detailed description of the use of this API. I would like to ask: 1. If I set 960 lines of batch data for input and use ten batches for prediction. Do different batches affect the prediction results? For example, will batch 1 affect the calculation of batch 2? If you still can't understand my question, let me give another example. Suppose that the correct results can be obtained by inputting batch 1 and batch 2. But now, due to data error, all data of batch 1 become 0, while batch 2 has not changed. In this case, can you still get correct results by inputting batch 1 and batch 2? 2. If I set 960 rows of data for a batch, does the data in the first row affect the data calculation in the second row? This problem is similar to the first one, except that different batches are changed into different lines. Please answer my question, thank you!

**Comment by ravikyram** [comment]
@anavanab99 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by anavanab99** [comment]
## URL(s) with the issue:
https://tensorflow.google.cn/versions/r1.15/api_docs/python/tf/estimator/DNNLinearCombinedRegressor

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):

?

I don't think it is necessary to provide relevant code for this problem. It is just a supplement to the API description. If you need to provide relevant code, you can refer to your own API documentation https://tensorflow.google.cn/versions/r1.15/api_docs/python/tf/estimator/DNNLinearCombinedRegressor

Is the link to the source code correct?


Are all parameters defined and formatted correctly?


Are return values defined?


Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises



Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
