### ISSUE TITLE
Convolutional RNN/LSTM

### ISSUE THREAD

**Issue by loliverhennigh** [tensorflow/tensorflow#4536]
Hi all,

This is a feature request for Convolutional RNNs such as [Convolutional LSTMS](http://arxiv.org/pdf/1506.04214v2.pdf). Is there any plan to support them in tensorflow?

I have an implementation working in [here](https://github.com/loliverhennigh/Convolutional-LSTM-in-Tensorflow) and some basic results indicating how well they do. I went about implementing them by making a new class called `ConvRNNCell` and `BasicVONVLSTMCell` and following what is seen in the tensorflow `rnn_cell.py` file. It seems I could redo the whole `rnn_cell.py` file like this. 

If this is of interest I would be more then happy to implement it for all the rnn functions.

**Comment by concretevitamin** [comment]
@ebrevdo could you take a look?  Thanks.

**Comment by mschonwe** [comment]
I haven't tried it yet, but @iwyoo did share an implementation of a ConvLSTM variant of the BasicLSTMCell : https://github.com/iwyoo/ConvLSTMCell-tensorflow

**Comment by davek44** [comment]
What's the benefit of having a dedicated cell? I've been running a convolutional layer followed by a recurrent layer with the existing modules.

**Comment by anxingle** [comment]
@loliverhennigh   sounds good!  Thank you for your work.

**Comment by carlthome** [comment]
@davek44, it's mostly applicable to seq2seq where you only want the final RNN output from the encoder, but it's hard to say really, because a ConvLSTM also has convolutions for the hidden states, which you're missing by sequentially applying a conv3d and then a RNN.

**Comment by edgarriba** [comment]
@davek44 do you have any working example?

**Comment by ebrevdo** [comment]
This seems useful to add. We're still reworking rnns a little. May take until late January to get to this.

**Comment by mmuneebs** [comment]
So, is this feature somewhere in master already?

**Comment by loliverhennigh** [comment]
I just put a pull request here #8891.  Im a bit new to contributing to tensorflow so hopefully I did everything ok.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
