### ISSUE TITLE
tflite RuntimeError: Encountered unresolved custom op: StridedSlice failed to prepare. 

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#45377]
**System information**
- Ubuntu 18.04
- tensorflow 2.4-rc3 and tf-nightly-2.5.0.dev20201203

**Describe the current behavior**

I'm trying to get tflite to work with a model I trained with keras using the subclassed model api.

```python
loaded_model = tf.keras.models.load_model("foo.ckpt")
converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_quant_model = converter.convert()
model_quant_file = Path("bar.tflite")
model_quant_file.write_bytes(tflite_quant_model)

interpreter = tf.lite.Interpreter(model_path="bar.tflite")
interpreter.allocate_tensors()
```

Leads to:

```python
    257   def allocate_tensors(self):
    258     self._ensure_safe()
--> 259     return self._interpreter.AllocateTensors()
    260 
    261   def _safe_to_run(self):

RuntimeError: Encountered unresolved custom op: StridedSlice.Node number 0 (StridedSlice) failed to prepare.
```

So I guess StridedSlice ops aren't implemented yet for tflite?

**Comment by ravikyram** [comment]
@lminer 

Please, share simple standalone code with supporting files (foo.ckpt) to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by abattery** [comment]
I think there are unsupported StridedSlice operation inputs by TFLite StridedSlice op. You will be able to run your model with Select TF ops. https://www.tensorflow.org/lite/guide/ops_select
