### ISSUE TITLE
Converted TensorFlow Lite model is not a valid model in Android Studio

### ISSUE THREAD

**Issue by pnovapps** [tensorflow/tensorflow#45373]
**System information**

Issue encountered with own model but can also reproduced using the example code found here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb

Running in a Colaboratory notebook

TensorFlow v2.3.0-0-gb36436b087 2.3.0

Android Studio 4.1.1

**Describe the current behavior**

The notebook runs as expected and the TensorFlow Lite model produces the expected output in Colaboratory.

Importing the downloaded model into Android Studio 4.1.1 gives the error
'Not a valid TensorFlow Lite model'

**Describe the expected behavior**

A successfully converted TensorFlow Lite LSTM model should be valid and usable in Android Studio

**Standalone code to reproduce the issue**

The code used to reproduce is the example LSTM model
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb

**Other info / logs**

**Comment by ymodak** [comment]
The example scope is to demonstrate building a keras sequential model and its conversion into tflite.
For deploying a tf lite model into android platform you can try [examples](https://github.com/tensorflow/examples/tree/master/lite/examples) given here.

**Comment by pnovapps** [comment]
The problem is with Android Studio.

Copy pasting code from the examples given I can load and run the model even though Android Studio tells me it is an invalid model and refuses to import it. There is a ticket raised with  Android Studio.

**Comment by ymodak** [comment]
Thanks for your issue. Can you please tag the open ticket in this issue thread as well?

**Comment by pnovapps** [comment]
On Google IssueTracker:

Successfully converted TensorFlow Lite model is invalid model in Android Studio 4.1.1

https://issuetracker.google.com/issues/174736305

**Comment by n9hal** [comment]
I have the same problem while importing. alongside this  whilie converting  my model
tflite_model = converter.convert()  

I am getting below warning.

WARNING:absl:Found untraced functions such as lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 5 of 5). These functions will not be directly callable after loading.

**Comment by Parth220** [comment]
@n9hal Did you end up finding a solution? I have the same warning on conversion. It does not run in the TFLite C++ api on Android

**Comment by n9hal** [comment]
@Parth220 No, Didn't find anything

**Comment by Henry6789** [comment]
Any update on this one? I'm suffering from this problem too..

**Comment by mohantym** [comment]
Hi @pnovapps ! 
We are checking to see whether you still need help in this issue. Have you checked in latest version of Android Studio/Tensorflow (2.5/2.6)yet ? Attaching relevant threads for reference. [link1](https://stackoverflow.com/a/66734683/11530462),[link2](https://github.com/tensorflow/tensorflow/issues/47571#issuecomment-791598653). Thanks!
