### ISSUE TITLE
TensorFlow 1.15.4 artifacts on Maven Central?

### ISSUE THREAD

**Issue by Kislovskiy** [tensorflow/tensorflow#45370]
Hello TensorFlow team!

Are you planning to upload a patch for TensorFlow 1.15.4  ( https://github.com/tensorflow/tensorflow/releases/tag/v1.15.4 ) to Maven Central? The latest available version on Maven is 1.15.0 ( https://mvnrepository.com/artifact/org.tensorflow/tensorflow )

**Comment by mihaimaruseac** [comment]
We don't have anyone left working on Java at the moment. This is a task that should be picked up by SIG JVM.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by jvishnuvardhan** [comment]
@Kislovskiy [Here](https://github.com/tensorflow/community/tree/master/sigs) is the link to the SIG community. Thanks!
