### ISSUE TITLE
EfficientNet - Conversion to TFlite

### ISSUE THREAD

**Issue by tgpsantos** [tensorflow/tensorflow#45376]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung S9
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.0
- TensorFlow LITE version (use command below): 2.3.0
- Python version: 3.7.4

**Describe the current behavior**
I'm trying to convert the EfficientNet Model to a TFLite model. 

```python
efficientnet = tf.keras.applications.EfficientNetB0(
    include_top=True,
    weights="imagenet",
    input_tensor=None,
    input_shape=None,
    pooling=None,
    classes=1000,
    classifier_activation="softmax",
)

# Save h5 model to device
efficientnet.save('effnet_b0.h5', compile=False)
# Load h5 model from device
effNetLoaded = tf.keras.models.load_model('effnet_b0.h5')

# Convert model to .tflite format 
converter = tf.lite.TFLiteConverter.from_keras_model(efficientnet)
tflite_model = converter.convert()
open('effnet_b0.tflite', "wb").write(tflite_model)
```

When using `effnet_b0.tflite` in Android I'm getting the following error (GPU delegate):

`java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`

I couldn't find much information about this error. I noticed the input was `[None, 224, 224, 3]`, but after changing to `[1, 224, 224, 3]` problem persisted. 

Appreciate any help or info you could give. I'll be happy to provide additional info.

**Comment by ymodak** [comment]
If you compile the model after model instantiation that can solve the issue.
```python
efficientnet.compile()
# Save h5 model to device
efficientnet.save('effnet_b0.h5')#, compile=False)
...
```

**Comment by abattery** [comment]
To run TFLite model with GPU delegate or NNAPI, the model should have a static shape. When you convert your model, could you set a fixed input shape when you are creating a keras model?

**Comment by tgpsantos** [comment]
Setting the input size fixed it. I tried it previously but some asset must have been mixed up during tests. This time I was more careful 👓  Thanks guys, problem solved.

**Comment by tgpsantos** [comment]
hey @mhyeonsoo
It's been some months already but I believe I've set the shape in the model creation (before saving it as a .h5). But your snippet _should_ work, not sure why it is not working (tbh I think I had the same problem)
