### ISSUE TITLE
TextVectorization layer together with TensorBoard fails when trying to log the weights

### ISSUE THREAD

**Issue by HeroGamers** [tensorflow/tensorflow#45372]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Version 2004 & Windows 10 Pro Version 20H2
- TensorFlow installed from (source or binary): PyPi
- TensorFlow version (use command below):  v2.3.1 & v2.4.0-rc3 & 2.5.0-dev20201203
- Python version: 3.6.6
- CUDA/cuDNN version: 10.1.243
- GPU model and memory: GeForce GTX 1050 Ti (notebook) & GeForce GTX 980 Ti

**Describe the current behavior**
When trying to use TensorBoard with a model, which has a TextVectorization layer, the log_weights function in callbacks.py of tensorflow/python/keras runs into an exception when it tries to get the name of the layer where the weights reside - which I guess might be because the TextVectorization layer is still experimental, and as such this might be why.

**Describe the expected behavior**
Either the weights would have a name, or they would be skipped when TensorBoard tries to log them.

**Standalone code to reproduce the issue**
I've made an example showing the issue using Google Colab, and it can be accessed through this link: https://colab.research.google.com/drive/1wRbFp-O6txoUv01GA_thlwJu_VxkPeyX

**Other info / logs**
For now I've added a few lines of code to TensorFlow locally, to just skip the layer if it's a TextVectorization layer - I don't know much about the internals of the layer, so I'm pretty much just shooting blindly there.
![image](https://user-images.githubusercontent.com/15278940/101026115-c906a100-3576-11eb-9f76-e97e19db43cf.png)

Traceback at the exception:
```
Traceback (most recent call last):
  File "D:/Projekter/Git/HeroAI/hero_ai.py", line 334, in <module>
    model = run()
  File "D:/Projekter/Git/HeroAI/hero_ai.py", line 283, in run
    history = train(model, train_dataset, test_dataset, callbacks)
  File "D:/Projekter/Git/HeroAI/hero_ai.py", line 228, in train
    callbacks=callbacks)
  File "C:\Users\marcu\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\marcu\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\marcu\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\callbacks.py", line 2339, in on_epoch_end
    self._log_weights(epoch)
  File "C:\Users\marcu\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\callbacks.py", line 2397, in _log_weights
    weight_name = weight.name.replace(':', '_')
AttributeError: 'TrackableWeightHandler' object has no attribute 'name'

Process finished with exit code 1
```

**Comment by amahendrakar** [comment]
@HeroGamers,
Looking at [this comment](https://github.com/tensorflow/tensorflow/issues/41244#issuecomment-730210764) from a similar issue, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/bb9bafc3228d94eccd5d235e41a46e8d/45372.ipynb). Thanks!

**Comment by HeroGamers** [comment]
@amahendrakar
Yup, that seems to be related to the same problem!
Guessing this issue can be closed now then, since it has been referred in the other issue, thanks!
