### ISSUE TITLE
Enable use of generators in tf lite model maker

### ISSUE THREAD

**Issue by syeds-git** [tensorflow/tensorflow#45378]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Using Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): 2+
- Python version: Default Colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

The current api of tensorflow model maker accepts a dataset created using following:

```
from tflite_model_maker import ImageClassifierDataLoader
data = ImageClassifierDataLoader.from_folder('path')
train_data, rest_data = data.split(0.8)
validation_data, test_data = rest_data.split(0.5)

model = image_classifier.create(train_data, model_spec=model_spec.efficientnet_lite4_spec, validation_data=validation_data, epochs=75, learning_rate=0.01, dropout_rate=0.3)
```
However it does not accept a generator which can be used to provide customized augmentation code. Here is an example of generator from this [tutorial](https://www.tensorflow.org/hub/tutorials/tf2_image_retraining#looking_for_a_tool_instead):

```
datagen_kwargs = dict(rescale=1./255, validation_split=.20)
dataflow_kwargs = dict(target_size=IMAGE_SIZE, batch_size=BATCH_SIZE,
                   interpolation="bilinear")

valid_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    **datagen_kwargs)
valid_generator = valid_datagen.flow_from_directory(
    data_dir, subset="validation", shuffle=False, **dataflow_kwargs)

do_data_augmentation = False
if do_data_augmentation:
  train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
      rotation_range=40,
      horizontal_flip=True,
      width_shift_range=0.2, height_shift_range=0.2,
      shear_range=0.2, zoom_range=0.2,
      **datagen_kwargs)
else:
  train_datagen = valid_datagen
train_generator = train_datagen.flow_from_directory(
    data_dir, subset="training", shuffle=True, **dataflow_kwargs)

```
Passing train_generator and valid_generator to image_classifier.create throws an exception. 

**Describe the expected behavior**
image_classifier.create method should accept train_generator and valid_generator as created in the example above or some other method should be provided to customized augmentation code for both train and validation images.

**Standalone code to reproduce the issue**
Use https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_image_classification.ipynb
and use the code provided above to create train_generator and valid_generator then run following:

model = image_classifier.create(train_generator, model_spec=model_spec.mobilenet_v2_spec, validation_data=valid_generator, epochs=75, learning_rate=0.01, dropout_rate=0.3)

**Other info / logs** 

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-43-a03b2f96410f> in <module>()
      1 # Train using models available in model maker
----> 2 model = image_classifier.create(original_generator, model_spec=model_spec.mobilenet_v2_spec, validation_data=validation_data, epochs=50, learning_rate=0.01, dropout_rate=0.2)

/usr/local/lib/python3.6/dist-packages/tensorflow_examples/lite/model_maker/core/task/image_classifier.py in create(train_data, model_spec, validation_data, batch_size, epochs, train_whole_model, dropout_rate, learning_rate, momentum, shuffle, use_augmentation, use_hub_library, warmup_steps, model_dir, do_train)
    116   image_classifier = ImageClassifier(
    117       model_spec,
--> 118       train_data.index_to_label,
    119       train_data.num_classes,
    120       shuffle=shuffle,

AttributeError: 'DirectoryIterator' object has no attribute 'index_to_label'

**Comment by Saduf2019** [comment]
@syeds-git 
Please share a colab gist with the error reported.

**Comment by syeds-git** [comment]
@Saduf2019 please see this link: 

https://github.com/syeds-git/TensorflowIssue-45378/blob/main/Colab_for_Tensorflow_Issue_45378.ipynb

Thanks

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c6550efa16412758fd4329de083dedab/untitled477.ipynb),

**Comment by ymodak** [comment]
@syeds-git  For enabling augmentation you can set `use_augmentation` flag as True,
```python
model = image_classifier.create(train_data, use_augmentation=True)
```
It performs data augmentation with default values  as `rotation_range=40, horizontal_flip=True, width_shift_range=0.2, height_shift_range=0.2, shear_range=0.2, zoom_range=0.2`
See https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier#advanced-usage

**Comment by syeds-git** [comment]
@ymodak the documentation is for the command line tool. Is it possible to provide different values using image_classifier.create method?

**Comment by ymodak** [comment]
I am afraid not. It simply provides an option to perform data augmentation with default `hparams`.
https://github.com/tensorflow/hub/blob/a13500b5465b1ca168e6089104a6dbbd9725219f/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py#L69-L88

**Comment by syeds-git** [comment]
@ymodak possible to have this capability in future?

**Comment by ymodak** [comment]
I don't see any conclusive information on the [TF Lite roadmap](https://www.tensorflow.org/lite/guide/roadmap) regarding it.
However you may try posting a thread and tagging this issue on [TF Lite discussion group](https://groups.google.com/a/tensorflow.org/g/tflite). Thanks!
