### ISSUE TITLE
Tensorflow-Python Environment Assertion Error 

### ISSUE THREAD

**Issue by kamathhrishi** [tensorflow/tensorflow#45396]
I tried running some Tensorflow-python code inside Graphene-SGX on Ubuntu 18.04. While the specific does not matter much. I would like to better understand what this AssertionError is and what is it trying to check? I am using the latest Tensorflow 2.3.0. 

```
[2020-12-04 05:34:34,839] - INFO - Running development server on: http://0.0.0.0:1236/
[2020-12-04 05:34:34,840] - WARNING - NOTICE! Running development server on production environment is not recommended.
2020-12-04 05:35:01.759068: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-04 05:35:06.357236: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3696010000 Hz
2020-12-04 05:35:06.860466: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xe33f4980 initialized for platform Host (this does not guarantee that XLA will be used).
 Devices:2020-12-04 05:35:06.864362: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

2020-12-04 05:35:07.218360: F tensorflow/core/platform/env.cc:357] Check failed: -1 != cmd_length (-1 vs. -1)
```

From what I understand, it is caused by line 357 (https://fossies.org/linux/tensorflow/tensorflow/core/platform/env.cc)

**Comment by ravikyram** [comment]
@kamathhrishi 

Please provide the exact sequence of commands and code that you executed before running into the problem. Thanks!

**Comment by kamathhrishi** [comment]
Hello @ravikyram, this was what I tried to run. 

```
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

model = Sequential()
model.add(Dense(500, input_dim=8, activation="sigmoid"))
model.add(Dense(100, activation="sigmoid"))
model.add(Dense(2, activation="softmax"))
#model.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
#model.fit(x_train, y_train, epochs=100, batch_size=70, validation_data=(x_test, y_test))
#model.save("Diabetes_model.h5")

print(model.predict(np.zeros([1,8])))
```

Note that I ran this using Graphene-SGX (https://github.com/oscarlab/graphene). 

I would be concerned as to what the failing AssertionCheck would mean. 

Thank you

**Comment by ravikyram** [comment]
Was able to run the code on Ubuntu 18.04 without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/06212dc6359e088a0d64c97f1bf79d17/45396.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@kamathhrishi Looks like this is not an issue of Tensorflow as @ravikyram was able to run (but not using Graphene-SGX).
Can you please post the issue in Graphene-SGX repo?

If you think the error is related to Tensorflow, Can you please share error log? In the above posts, Assertion error was not shown (hope i didn't miss). Thanks!

**Comment by kamathhrishi** [comment]
Hey @jvishnuvardhan Sorry for the late reply. Yes, its an error from TF.

As you can see from the last line of error statement 

```2020-12-04 05:35:07.218360: F tensorflow/core/platform/env.cc:357] Check failed: -1 != cmd_length (-1 vs. -1)```

it clearly states that the error is from env.cc line 357. When I check the C file , I noticed it was a check. 
Further, Graphene exits with a return code 134.

**Comment by mihaimaruseac** [comment]
The [code that leads to the `CHECK` is](https://cs.opensource.google/tensorflow/tensorflow/+/r2.3:tensorflow/core/platform/env.cc;l=355-357;drc=7581d2a338c65086c6c7d0be1c65bd0621dd33c6):

```cc
    int fd = open("/proc/self/cmdline", O_RDONLY);
    int cmd_length = read(fd, buf, PATH_MAX - 1);
    CHECK_NE(-1, cmd_length);
```

Likely on your system `/proc/self/cmdline` for the Python interpreter cannot be read.

Please provide details about operating system and the way you are running the code.

**Comment by kamathhrishi** [comment]
@mihaimaruseac Thank you for your response. I will verify this and get back to you in about a week. This was inside a Library OS called Graphene. I will have to check if it has access to "/proc/self/cmdline". In Graphene-SGX I had to partition between what resources from OS could be accessible and cannot be accessible.

**Comment by mihaimaruseac** [comment]
Any updates?

**Comment by kamathhrishi** [comment]
Hey, @mihaimaruseac Thanks for following up. I have been using Tf 2.2 temporarily instead. I will use Tf 2.4 and post my update here. Sorry for the delay.

**Comment by jvishnuvardhan** [comment]
Any updates with recent TF versions? Thanks!

**Comment by kamathhrishi** [comment]
Hello @jvishnuvardhan, it worked fine. We can close this issue. 

Thank you.
