### ISSUE TITLE
Is there a tutorial and guide implement with c ？

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#45393]
Since c is covered in tensorflow version compatibility . Is there any document , book or anything else which is useful to learn tensorflow with c ( or c++ ) ?

**Comment by ravikyram** [comment]
@DachuanZhao 

Please, refer the below links and see if it helps you.

https://www.tensorflow.org/install/lang_c
https://www.tensorflow.org/api_docs/cc

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> 
> Please, refer the below links and see if it helps you.
> 
> https://www.tensorflow.org/install/lang_c
> https://www.tensorflow.org/api_docs/cc
> 
> This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

Hi , what I want is a guide like [https://www.tensorflow.org/guide](https://www.tensorflow.org/guide) or tutorial like  [https://www.tensorflow.org/tutorials](https://www.tensorflow.org/tutorials)

**Comment by ymodak** [comment]
Unfortunately we do not have such guides for c or c++ yet. I found a guide that talks about usage of c++ api for[ building custom ops](https://www.tensorflow.org/guide/create_op) in TF.
See https://github.com/tensorflow/custom-op

**Comment by DachuanZhao** [comment]
> Unfortunately we do not have such guides for c or c++ yet. I found a guide that talks about usage of c++ api for[ building custom ops](https://www.tensorflow.org/guide/create_op) in TF.
> See https://github.com/tensorflow/custom-op
