### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by UltraBlackLinux** [tensorflow/tensorflow#45405]
**System information**
- Manjaro 5.9
- TensorFlow installed from (source or binary): source
- TensorFlow version: 3.2.1
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7
- GCC/Compiler version (if compiling from source): 10.2
- CUDA/cuDNN version: 11.1.1
- GPU model and memory: asus radeon 560 4gb

**Describe the problem**
build fail
It's the same issue like  #41362 but it's back. I didn't comment on the other one since it's pretty old now and nobody would notice...

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
pkgname=llvm-amdgpu
pkgdesc='Radeon Open Compute - LLVM toolchain (llvm, clang, lld)'
pkgver=3.10.0
pkgrel=1
arch=('x86_64')
url='https://github.com/RadeonOpenCompute/llvm-project'
license=('custom:Apache 2.0 with LLVM Exception')
depends=(z3)
makedepends=(cmake python ninja)
source=("${pkgname}-${pkgver}.tar.gz::$url/archive/rocm-$pkgver.tar.gz")
sha256sums=('8262aff88c1ff6c4deb4da5a4f8cda1bf90668950e2b911f93f73edaee53b370')
_dirname="$(basename "$url")-$(basename "${source[0]}" .tar.gz)"

build() {
    cmake -GNinja -Wno-dev -S "$_dirname/llvm" \
          -DCMAKE_INSTALL_PREFIX='/opt/rocm/llvm' \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_HOST_TRIPLE=$CHOST \
          -DLLVM_BUILD_UTILS=ON \
          -DLLVM_ENABLE_BINDINGS=OFF \
          -DLLVM_ENABLE_OCAMLDOC=OFF \
          -DLLVM_ENABLE_PROJECTS='llvm;clang;compiler-rt;lld' \
          -DLLVM_TARGETS_TO_BUILD='AMDGPU;X86' \
          -DOCAMLFIND=NO
    ninja
}
```
Thanks!

**Comment by sanatmpa1** [comment]
@UltraBlackLinux,

Can you try installing the latest stable version of tensorflow i.e `2.6.0` and lets us know if the issue still persists? You can follow this [guide](https://www.tensorflow.org/install/source#tested_build_configurations) to build from source. Thanks!
