### ISSUE TITLE
[RNN] tensorflow/lite/kernels/fully_connected.cc:119 is_optional_bias_int != true error in quantized LSTM model

### ISSUE THREAD

**Issue by fragolka** [tensorflow/tensorflow#45402]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (or github SHA if from source): TF2.3, TF '2.5.0-dev20201203'
- Python version: 3.7.5

I am trying to convert and fully quantize a model containing LSTM layers. I use unroll = True flag as quantization of while function is not supported yet (see https://github.com/tensorflow/tensorflow/issues/39392). 

```
import tensorflow as tf
import numpy as np

# create a simple lstm model
input_data = np.random.random_sample([1,2,3]).astype(np.float32)
lstm_model = tf.keras.models.Sequential([tf.keras.layers.LSTM(units = 5, unroll = True)])
lstm_model.build(input_data.shape)

# create a representative dataset
repr_dataset = tf.data.Dataset.from_tensor_slices(np.tile(input_data, [10, 1, 1]))
repr_dataset = repr_dataset.batch(1)
def representative_data_gen():
    for input_value in repr_dataset.take(1):
        yield [input_value]
    
# convert and quantize the model
converter = tf.lite.TFLiteConverter.from_keras_model(lstm_model)
converter.optimizations =  [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_model = converter.convert()
open("lstm_model.tflite","wb").write(tflite_model)

# open interpreter
interpreter = tf.lite.Interpreter(model_path="lstm_model.tflite")
interpreter.allocate_tensors()
```

The interpreter fails when allocating tensors:

```
Traceback (most recent call last):

  File "test_lstm.py", line 455, in <module>
    interpreter.allocate_tensors()

  File "Anaconda3\envs\Automatic-Speech-Recognition\lib\site-packages\tensorflow\lite\python\interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()

RuntimeError: tensorflow/lite/kernels/fully_connected.cc:119 is_optional_bias_int != true (0 != 1)Node number 4 (FULLY_CONNECTED) failed to prepare.
```

I found out that following code is converted into a fully connected node with 8int bias  as h_tm1 is a tf.zeros() tensor during the first rnn step. (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/recurrent.py#L2461)
```
      z = K.dot(inputs, self.kernel)
      z += K.dot(h_tm1, self.recurrent_kernel)
      if self.use_bias:
        z = K.bias_add(z, self.bias)
```

Is this an expected behaviour or a bug? How to get around it?

Thank you

**Comment by fragolka** [comment]
Any updates on this? Thanks

**Comment by mohantym** [comment]
Was able to replicate the issue with TF 2.3 and TF v2.5 In Colab, Issue is not recurring in TF 2.5 ,please find the [gist](https://colab.research.google.com/gist/mohantym/9d620af346622de25aa3a807edc47388/github_45402.ipynb) here ..Thanks!
