### ISSUE TITLE
Convert float32 Image NdArray to uint8

### ISSUE THREAD

**Issue by cosmir17** [tensorflow/tensorflow#45418]
## URL(s) with the issue:
Couldn't find a documentation.

## Description of issue (what needs changing):
I use Tensorflow version 2.3.1 (or Nightly)

I could find tons of information on how to convert int image to float32. However, not being able to do so for the opposite case.

How do convert this normalised ndarray(0 to 1) to a 0-255 ndarray while maintaining the same shape?
![Screenshot 2020-12-04 at 21 48 11](https://user-images.githubusercontent.com/2845708/101218255-a9f13780-367a-11eb-9cb4-622dcc65a863.png)

Thank you,
Sean

**Comment by ymodak** [comment]
You can try,
```python
import numpy as np
image  = np.array([255,255,0,0])
image = my_array / 255
image = my_array * 255
image.astype(np.uint8)
``

**Comment by cosmir17** [comment]
Thank you, @ymodak. It's working.
![Screenshot 2020-12-05 at 10 49 53](https://user-images.githubusercontent.com/2845708/101240546-b19af580-36e7-11eb-9eb1-5901897a4228.png)

Nonetheless, numpy `dtype` is still float32. So, I used. 
img_resized_255.astype(np.uint8)

Issue solved. So, I close this page.
