### ISSUE TITLE
Model optimization using quantization on desktop PC?

### ISSUE THREAD

**Issue by yummychop** [tensorflow/tensorflow#45413]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

 We are running CNN using tensorflow on desktop PC's GPU, Win 10 64 bit. We would like to do quantization of the trained model to reduce the inference time. But it seems the quantization only works for tensorflow lite. Is there a way to quantitate the model which runs on desktop PC?

**Will this change the current api? How?**
Maybe. 

**Who will benefit with this feature?**
tensorflow desktop developers

**Any Other info.**

**Comment by amahendrakar** [comment]
@yummychop,
Please go through [this](https://www.tensorflow.org/model_optimization/guide) TensorFlow model optimization guide and let us know if it helps. Thanks!

**Comment by yummychop** [comment]
> @yummychop,
> Please go through [this](https://www.tensorflow.org/model_optimization/guide) TensorFlow model optimization guide and let us know if it helps. Thanks!
Thank you for the reply, we tried the weights-based pruning as suggested in the guide, the sparsity of the weights increased but the inference time didn't get improved. As someone raised here: https://github.com/tensorflow/model-optimization/issues/173. The pruning only reduced the model size.

And as I indicated above, it seems quantization only works for TF lite and TF lite in only for embedded platforms. We are trying tensorRT

We are also looking at tensor decomposition... but I do think the quantization should work for a desktop, GPU-based platform

**Comment by jvishnuvardhan** [comment]
@yummychop This issue is more related to Model-optimization. It is better if you post this issue in [`Model-optimization`](https://github.com/tensorflow/model-optimization/issues) repo. The issue you share will have more updates in the future as team is working supporting the feature. Thanks!

Please open an issue there and close the issue here. Thanks!

**Comment by yummychop** [comment]
I will raise this issue in the "model optimization" section, thank you for your help @jvishnuvardhan
