### ISSUE TITLE
Page is not visible in Desktops 

### ISSUE THREAD

**Issue by Vivek2509** [tensorflow/tensorflow#45429]
## URL(s) with the issue:
https://www.tensorflow.org/hub/tutorials/tf2_object_detection#utilities

## Description of the issue (what needs changing):
- The `Toggle-code` button is not working.
- Below page is cut from the left side
- Screenshot from crome
![Screenshot (96)](https://user-images.githubusercontent.com/43227010/101273854-36a50e00-37bf-11eb-8a9a-a5dd318612ea.png)
- Screenshot from firefox
![Screenshot (97)](https://user-images.githubusercontent.com/43227010/101273857-3b69c200-37bf-11eb-9e42-ef93c9d0bfeb.png)

**Comment by lamberta** [comment]
Thanks for the report and tracking internally b/175229423

**Comment by lamberta** [comment]
Should be fixed now: https://www.tensorflow.org/hub/tutorials/tf2_object_detection
