### ISSUE TITLE
I can build tensorflow.dll  successfully,but not  include SSE4.2,Why?

### ISSUE THREAD

**Issue by lrb352225** [tensorflow/tensorflow#45421]
python ./configure.py    set:
build TensorFlow with ROCm support? [y/N]: n
build TensorFlow with CUDA support? [y/N]: n
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:SSE4.2]:
Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
build command:  bazel build --config opt //tensorflow/tools/lib_package:libtensorflow
can you tell me
build successfully,but tensorflow.dll not include SSE4.2,Why?

**Comment by lrb352225** [comment]
tensorflow version is   tensorflow_r2.3

**Comment by ravikyram** [comment]
@lrb352225 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!
