### ISSUE TITLE
addv2

### ISSUE THREAD

**Issue by mihaibf** [tensorflow/tensorflow#45447]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by ravikyram** [comment]
@mihaibf 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Please, share the colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by mihaimaruseac** [comment]
No template filled, closing
