### ISSUE TITLE
Did not get operators or tensors in subgraph 1. when using tf.lite.Interpreter

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#45444]
**tf version: 2.3.1** 

I saved a model of simple RNN and after quantitation, this model can not be reloaded by `tf.lite.Interpreter`
I tried other types of model such as textCNN, it still does not work.

If I remove the `converter.optimizations = [tf.lite.Optimize.DEFAULT] `, it succeed.
However, I cannot remove this command as it can significantly reduce the size of my model.
Any hints ?
Thanks.
```
def get_model_rnn():
    inputs = layers.Input(shape=(maxlen,))
    embedding = layers.Embedding(vocab_size, 128,  trainable=True)
    title_embed = embedding(inputs)
    title_ids_mask = layers.Masking(mask_value=0, name='mask')(title_embed)
    title_gru = layers.Bidirectional(layers.GRU(128, return_sequences=False))(title_ids_mask)
    outputs = layers.Dense(1, activation='sigmoid', name='mlp2')(title_gru) 
    model = keras.Model(inputs=inputs, outputs=outputs)
    model.compile("Adam", "binary_crossentropy", metrics=["binary_accuracy"])
    return model 
model = get_model_rnn()
model.save('./model_rnn')

converter = tf.lite.TFLiteConverter.from_saved_model('./model_rnn')
#converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.optimizations = [tf.lite.Optimize.DEFAULT] # this caused the error
tflite_quant_model = converter.convert()
open("model_rnn.tflite", "wb").write(tflite_quant_model)

interpreter = tf.lite.Interpreter(model_path="./model_rnn.tflite")   
```

ERROR==>
```
In [27]: interpreter = tf.lite.Interpreter(model_path="./model_rnn.tflite")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-55e82bdec7e7> in <module>
----> 1 interpreter = tf.lite.Interpreter(model_path="./model_rnn.tflite")

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in __init__(self, model_path, model_content, experimental_delegates, num_threads)
    196       self._interpreter = (
    197           _interpreter_wrapper.CreateWrapperFromFile(
--> 198               model_path, self._custom_op_registerers))
    199       if not self._interpreter:
    200         raise ValueError('Failed to open {}'.format(model_path))

ValueError: Did not get operators or tensors in subgraph 1.
```

**Comment by yananchen1989** [comment]
`converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]` , which has the same effect of compression, can also cause the error. 
the size of the original model is **15M**
if not using 
```
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```
the quantization model size is 11M.
If use, the model will be 2.8M. A significant change.

**Comment by yananchen1989** [comment]
if not use `converter.optimizations = [tf.lite.Optimize.DEFAULT]`
`tflite_quant_model = converter.convert()` info:

> 2020-12-08 06:37:25.640712: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
> 2020-12-08 06:37:25.640753: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
> 2020-12-08 06:37:25.641019: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: ./model_rnn
> 2020-12-08 06:37:25.701719: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
> 2020-12-08 06:37:25.701761: I tensorflow/cc/saved_model/loader.cc:250] Reading SavedModel debug info (if present) from: ./model_rnn
> 2020-12-08 06:37:25.701954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-12-08 06:37:25.701962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
> 2020-12-08 06:37:25.924717: I tensorflow/cc/saved_model/loader.cc:215] Restoring SavedModel bundle.
> 2020-12-08 06:37:26.177707: I tensorflow/cc/saved_model/loader.cc:199] Running initialization op on SavedModel bundle at path: ./model_rnn
> 2020-12-08 06:37:26.395008: I tensorflow/cc/saved_model/loader.cc:319] SavedModel load for tags { serve }; Status: success: OK. Took 753990 microseconds.


if use `converter.optimizations = [tf.lite.Optimize.DEFAULT]`
There are more lines of info:

> 2020-12-08 06:38:08.069592: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
> 2020-12-08 06:38:08.069635: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
> 2020-12-08 06:38:08.069906: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: ./model_rnn
> 2020-12-08 06:38:08.134263: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
> 2020-12-08 06:38:08.134305: I tensorflow/cc/saved_model/loader.cc:250] Reading SavedModel debug info (if present) from: ./model_rnn
> 2020-12-08 06:38:08.134534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-12-08 06:38:08.134543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
> 2020-12-08 06:38:08.359398: I tensorflow/cc/saved_model/loader.cc:215] Restoring SavedModel bundle.
> 2020-12-08 06:38:08.610223: I tensorflow/cc/saved_model/loader.cc:199] Running initialization op on SavedModel bundle at path: ./model_rnn
> 2020-12-08 06:38:08.831016: I tensorflow/cc/saved_model/loader.cc:319] SavedModel load for tags { serve }; Status: success: OK. Took 761110 microseconds.
> **2020-12-08 06:38:09.941434: I tensorflow/lite/tools/optimize/quantize_weights.cc:211] Skipping quantization of tensor std.constant13 because it has fewer than 1024 elements (256).
> 2020-12-08 06:38:09.953622: I tensorflow/lite/tools/optimize/quantize_weights.cc:203] Skipping quantization of tensor arg6 that is not type float.
> 2020-12-08 06:38:09.953653: I tensorflow/lite/tools/optimize/quantize_weights.cc:220] Skipping quantization of tensor arg7 because it has no allocated buffer.
> 2020-12-08 06:38:09.954093: I tensorflow/lite/tools/optimize/quantize_weights.cc:203] Skipping quantization of tensor arg6 that is not type float.
> 2020-12-08 06:38:09.954100: I tensorflow/lite/tools/optimize/quantize_weights.cc:220] Skipping quantization of tensor arg7 because it has no allocated buffer.**

**Comment by yananchen1989** [comment]
`2.5.0-dev20201207` is OK for this problem.

**Comment by gromovnik1337** [comment]
I resolved this problem by running the optimization (quantization) script on the SavedModel format (according to https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) inside the TF docker container. My model was also inside the container (I've created a docker volume).

**Comment by DanBmh** [comment]
Update to my comment above: Seems it doesn't work with every model architecture ...
