### ISSUE TITLE
all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by menkeyi** [tensorflow/tensorflow#45450]
(tfv1) [root@bogon ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

tfv1) [root@bogon ~]# nvidia-smi
Mon Dec  7 22:21:25 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:0C.0 Off |                    0 |
| N/A   44C    P0    15W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

2020-12-07 22:03:48.390261: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.9.0
Traceback (most recent call last):
  File "cpu.py", line 91, in <module>
    with tf.Session() as sess:
  File "/root/anaconda3/envs/tfv1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1570, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/root/anaconda3/envs/tfv1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 693, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable

The CPU version of tensorflow can execute successfully, but GPU version of tensorflow fails. Why？
tensorflow version ：
           conda install tensorflow=1.14.0=gpu_py37hae64822_0

**Comment by ravikyram** [comment]
@menkeyi 

Please, try with the tested build configurations from [here](https://www.tensorflow.org/install/source#gpu). Thanks!
