### ISSUE TITLE
tflite quantized model unable to run on DSP

### ISSUE THREAD

**Issue by shlomi-amitai** [tensorflow/tensorflow#45452]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
Binary 
- Tensorflow version (commit SHA if source):
tf-nightly 
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
Android
**Describe the problem**
Model with full quantization. 
I get the following message:
INFO: Created TensorFlow Lite delegate for Hexagon.
INFO: Initialized TensorFlow Lite runtime.
INFO: Interpreter::UseNNAPI() is deprecated. Use tflite::NnApiDelegate() directly instead.
INFO: Hexagon delegate: 0 nodes delegated out of 51 nodes with 0 partitions.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Converter configuration:
converter.optimizations = [tf.lite.Optimize.DEFAULT] # dynamic range quantization
converter.representative_dataset = representative_data_gen  # + float fallback quantization
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]  # +integer only quantization
converter.inference_input_type = tf.int8 # +integer only quantization
converter.inference_output_type  = tf.int8    

tflite model is attatched
[myModel.zip](https://github.com/tensorflow/tensorflow/files/5653707/myModel.zip)

**Comment by karimnosseir** [comment]
Hello @shlomi-amitai is this same issue as
https://github.com/tensorflow/tensorflow/issues/45902 


Thanks
