### ISSUE TITLE
"keras predict" uses one more batch than specified by "steps" argument with generator x

### ISSUE THREAD

**Issue by shenriet** [tensorflow/tensorflow#45459]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1

**Describe the current behavior**
When providing a python generator to the keras.Model.predict function with a number of steps=N then, the generator is called N+1 times whereas the output of the predict function is the expected result (of size N x batch_size).

**Describe the expected behavior**
I expect the generator to be called only N times. It makes it impossible to resume the prediction just after the last called batch. Beside, the last batch is taken from the generator but not used for the prediction.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

# a model that simply take a float as input and return it Model(x) = x
inputs = tf.keras.Input(shape=(1,))
outputs = tf.keras.layers.Dense(
    1, 
    activation=None, 
    use_bias=False, 
    kernel_initializer=tf.keras.initializers.Ones()
)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

def get_generator(batch_size=32, max_value=100):
    for begin in np.arange(start=0, stop=max_value, step=batch_size):
        end = min(max_value, begin + batch_size)
        print("Call generator {} to {}".format(begin, end))
        yield np.arange(begin, end)[:,None]

batch_size = 32
max_value = 100
data_generator = get_generator(batch_size=batch_size, max_value=max_value)

N = 3
# 3 steps but generator called 4 times...
res = model.predict(x=data_generator, steps=N)
```
![image](https://user-images.githubusercontent.com/7781975/101401829-2da56100-38d3-11eb-8013-7ed0d1470226.png)

```python
expected_result = np.arange(0, N * batch_size)[:, None]
print(np.allclose(res, expected_result))
```
![image](https://user-images.githubusercontent.com/7781975/101401914-5168a700-38d3-11eb-8dc4-4d4eaf25e3dc.png)

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please fin the [gist for nightly](https://colab.research.google.com/gist/Saduf2019/552f6674aa5f547a6f2898c1a4edf9c2/untitled.ipynb), [tf 2.3](https://colab.research.google.com/gist/Saduf2019/05229ccff799bcd67db6d4cc3cbb3014/untitled480.ipynb)

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue using TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/1f755dc8ae5731f627e58c5608f1f997/untitled88.ipynb).Thanks!

**Comment by gowthamkpr** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by arthurflor23** [comment]
Hi,
This issue has been resolved? I got this problem in my project today and after debugging I came across this issue.
Finally, I ran the gist and apparently the issue persists.
