### ISSUE TITLE
TypeError: Expected int for argument 'num' not <tf.Tensor 'Squeeze:0' shape=() dtype=int32>.

### ISSUE THREAD

**Issue by qinghua2016** [tensorflow/tensorflow#4545]
I run the following code, but it has one error at    "tf.unpack(inputs,self.bathsize)",the error is as follows:
TypeError: Expected int for argument 'num' not <tf.Tensor 'Squeeze:0' shape=() dtype=int32>.
```
 def build(n_dict, word_dim):
       self.word_ids = tf.placeholder(tf.int32, shape=(None, None, 7), name='word_ids')
        self.bathsize = tf.shape(self.word_ids)[0]
        self.word_len=tf.shape(self.word_ids)[1]
        with tf.device("/cpu:0"):
            self.embedding = tf.Variable(tf.random_uniform([n_dict, word_dim], -1.0, 1.0), name='embedding', dtype='float32')
            self.embedded_input = tf.nn.embedding_lookup(self.embedding, self.word_ids)
        inputs = tf.reshape(self.embedded_input, [self.bathsize, self.word_len, -1])
        # inputs=tf.transpose(inputs,[1,0,2])
        inputs = tf.nn.dropout(inputs, self.dropout)
        self.inputs = inputs

        self.input_length = tf.fill([self.word_len], self.bathsize)
        self.input_length = tf.cast(self.input_length, dtype=tf.int64)
        with tf.variable_scope('forward'):
            self.lstm_fw_cell = rnn_cell.BasicLSTMCell(n_hidden)
        with tf.variable_scope('backward'):
            self.lstm_bw_cell = rnn_cell.BasicLSTMCell(n_hidden)
        lstm_state_fw = self.lstm_fw_cell.zero_state(self.word_len, tf.float32)
        lstm_state_bw = self.lstm_bw_cell.zero_state(self.word_len, tf.float32)
        # sequence_length=self.input_length

        outputs, output_state_fw, output_state_bw = rnn.bidirectional_rnn(
            self.lstm_fw_cell, self.lstm_bw_cell,
            tf.unpack(inputs,self.bathsize),
            initial_state_fw=lstm_state_fw,
            initial_state_bw=lstm_state_bw,
            sequence_length=self.input_length
        )
```
As I know, tf.unpack have one parameter num, when the code run to "tf.unpack(inputs,self.bathsize)", num=None.  When the bachsize if fixed, it succeed to run. But  I want the model inputs have variable bacthsize, do you have any idea to solve this?@Geoffrey Irving

**Comment by tatatodd** [comment]
Here is the documentation for `tf.unpack`:
https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#unpack

Note this line in particular:
If num is not specified (the default), it is inferred from value's shape

Try changing your code above to just the following:
```
  tf.unpack(inputs)
```

**Comment by aselle** [comment]
Automatically closing due to lack of recent response. Please reopen when additional information becomes available. Thanks!

**Comment by huangshenno1** [comment]
@tatatodd removing the parameter `num` will cause a `ValueError: Cannot infer num from shape` and cannot solve anything.
I'm now having the same problem when trying to use `tf.unpack`. Could anyone give an effective solution to  this?
