### ISSUE TITLE
Suspected memory leak - when loading multiple models with tf.saved_model.load

### ISSUE THREAD

**Issue by farotem** [tensorflow/tensorflow#45453]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
binary wheel via PyPI
- TensorFlow version (use command below):
v2.4.0-rc3-20-g97c3fef64ba 2.4.0-rc4
- Python version:
3.6
Bazel version (if compiling from source):
NA
GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
CUDA 11.1

- GPU model and memory:
V100 16GB

**Describe the current behavior**
I'm suspecting a CPU memory leak when loading multiple models.
When I'm running infinite loop that keeps loading the same model while using the same variable the memory (private bytes and working set) of the process keep increasing. At some points the working set seems to free some memory, but the trend is that the memory keeps on rising.
For example I used a simple model.
For our **current real** model the memory leak in tf 2.3 is 0.32MB per load model 
For our **current real** model the memory leak in tf 2.4 is 0.08MB per load model it is still an issue since the model can be changed and our server serve different models 24/7 

This trend happens even though I call gc.collect() on every iteration and tf.keras.backend.clear_session().

**Describe the expected behavior**
The memory shouldnt increase on each interation

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import gc


def build_and_save_own_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.save('my_model')
    tf.keras.backend.clear_session()
    del model
    gc.collect()


def profile_load_model(path):
    model = tf.saved_model.load(path)
    tf.keras.backend.clear_session()
    del model
    gc.collect()


def run_model():
    model_path = 'my_model'
    build_and_save_own_model()
    print("load model in loops:")
    c = 1
    while True:
        print("----------- iter", c)
        profile_load_model(model_path)
        c += 1


if __name__ == '__main__':
    print("*****************************************************")
    print("START LOADING MODEL")
    print(tf.version.GIT_VERSION, tf.version.VERSION)
    print("*****************************************************")
    run_model()
```

TF2_3 memory leak:
![memleak_tf2_3](https://user-images.githubusercontent.com/27951762/101373173-5585cc00-38b5-11eb-8405-124b885033ab.PNG)

TF2_4 memory leak:
![memleak_tf2_4](https://user-images.githubusercontent.com/27951762/101373017-2bcca500-38b5-11eb-9b22-cc652036b455.PNG)

thanks

**Comment by ravikyram** [comment]
@farotem 

Can you please share colab link or complete code to trace memory  allocations. Thanks!

**Comment by farotem** [comment]
https://colab.research.google.com/drive/1Vlc00zyfMEZ_8vXPN9v2_dp6eZ3K3NDz?usp=sharing

**Comment by ravikyram** [comment]
@farotem 

Please, grant me the access for the colab link. Thanks!

**Comment by farotem** [comment]
please try again

**Comment by ravikyram** [comment]
@farotem 

I tried in colab with TF 2.4, nightly version (`2.5.0-dev20201209`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/99ba4449987b586936b065b278d063ce/untitled572.ipynb).You are also seeing the same behavior?

Thanks!

**Comment by farotem** [comment]
yes thank you, as you can see you started at 380.1 MiB
finished at 388.3 MiB 
after 1024 iterations.

**Comment by jvishnuvardhan** [comment]
@farotem Similar behavior was noticed with `tf.keras.models.load_model` also.
```
# model = tf.saved_model.load(path)
    model = tf.keras.models.load_model(path)
```

[Here](https://colab.research.google.com/gist/jvishnuvardhan/6f7d9fc4034138037ef0945e00fbfad3/untitled572.ipynb) is a gist for our reference. Thanks!

**Comment by haimat** [comment]
Hi, I am not really sure based on my own experiments -
is this memory leak still an issue with TF 2.4?

**Comment by farotem** [comment]
@haimat I checked again with tf 2.4.1 and unfortunately still had the same memory leak.
You can look at the gist jvishnuvardhan  posted

**Comment by jvishnuvardhan** [comment]
@haimat @farotem I just checked with `tf-nightly`. I don't see much leak. Please check the [gist](https://colab.research.google.com/gist/jvishnuvardhan/103a8bd18e46f988cef12a1ec9af4346/untitled572.ipynb). 

Can you please run the gist and tell me if you see any memory leak.

I changed only one line as shown below

```
#model = tf.saved_model.load(path)
    model = tf.keras.models.load_model(path)
```

Please let me know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
@haimat @farotem Please take a look at [similar issue](https://github.com/tensorflow/tensorflow/issues/40171) that was resolved recently. Thanks.

Please verify once and close the issue. Thanks!

**Comment by haimat** [comment]
@jvishnuvardhan Looks good to me, thanks.
But I have not opened this issue, so it's not up to me to close it :)

**Comment by jvishnuvardhan** [comment]
@farotem I think this was resolved in `tf-nightly`. I am closing this issue. 
Please feel free to reopen if I am mistaken. Thanks!

**Comment by farotem** [comment]
Thanks @jvishnuvardhan looks good!

**Comment by OliverPfau** [comment]
I have memory leaks cloning a loaded model with
```
model_copy =  tf.keras.models.clone_model(model)
model_copy.build()
model_copy.set_weights(model.get_weights())
```
using Tensorflow 2.3.1. Does this fix affect the cloning as well?

**Comment by jvishnuvardhan** [comment]
@OliverPfau Can you please open a new issue with a simple standalone code to reproduce your issue? Thanks! In the new issue, you could reference this issue. Thanks!

**Comment by neozhao98** [comment]
Hi @jvishnuvardhan, so this issue has been fixed after tf2.5 version, is right?
