### ISSUE TITLE
Cannot ./configure Tensorflow on Ubuntu 18.04 LTS with CUDA 11.1

### ISSUE THREAD

**Issue by cement-head** [tensorflow/tensorflow#45463]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: latest
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7.1 
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.1/8
- GPU model and memory: RTX TITAN (DUAL) 24 GB

**Describe the problem**
Attempting to configure tensorflow for using the ./compile script.
CUDA is not found 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure 
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]: 

Found possible Python library paths:
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.6/dist-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: y
ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib/i386-linux-gnu'
        '/lib/x86_64-linux-gnu'
        '/lib32'
        '/opt/ont/guppy/lib'
        '/usr'
        '/usr/lib'
        '/usr/lib/i386-linux-gnu'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/lib32'
        '/usr/local/cuda'
        '/usr/local/cuda-11.1/targets/x86_64-linux/lib'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11.1

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8

Please specify the TensorRT version you want to use. [Leave empty to default to TensorRT 6]: 7

Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]: 

Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /usr/local/cuda-11.1/targets/x86_64-linux/lib,/usr/local/cuda-11.1/targets/x86_64-linux/include,/usr/lib/x86_64-linux-gnu,/usr/include,/usr/local/cuda-11.1/bin/,/usr/local/cuda-11.1/nvvm/libdevice/              

Could not find any libdevice*.10.bc in any subdirectory:
        'nvvm/libdevice'
        'share/cuda'
        'lib/nvidia-cuda-toolkit/libdevice'
        'local/cuda/nvvm/libdevice'
of:
        '/usr/include'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda-11.1/bin/'
        '/usr/local/cuda-11.1/nvvm/libdevice/'
        '/usr/local/cuda-11.1/targets/x86_64-linux/include'
        '/usr/local/cuda-11.1/targets/x86_64-linux/lib'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@cement-head 
Can you please try with CUDA 11.0? TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.
Please refer to this issue and let us know : #43629

**Comment by cement-head** [comment]
Okay - this will take some time.

**Comment by cement-head** [comment]
Okay - same error with CUDA 11.0 and TensorFlow 2.5 (pulled from GitHub):

Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /usr/local/cuda-11.0/targets/x86_64-linux/lib,/usr/local/cuda-11.0/targets/x86_64-linux/include,/usr/lib/x86_64-linux-gnu,/usr/include,/usr/local/cuda-11.0/bin/,/usr/local/cuda-11.0/nvvm/libdevice/


Could not find any libdevice*.10.bc in any subdirectory:
        'nvvm/libdevice'
        'share/cuda'
        'lib/nvidia-cuda-toolkit/libdevice'
        'local/cuda/nvvm/libdevice'
of:
        '/usr/include'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda-11.0/bin/'
        '/usr/local/cuda-11.0/nvvm/libdevice/'
        '/usr/local/cuda-11.0/targets/x86_64-linux/include'
        '/usr/local/cuda-11.0/targets/x86_64-linux/lib'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

**Comment by cement-head** [comment]
BTW; Tensorflow is not finding the install CUDA, nor the cuDNN install automagically, which is in the path on this machine - all other CUDA functions are okay (on Ubuntu 18.04).

This does not appear to be a CUDA 11.0 vs 11.1 error/issue.

**Comment by feranick** [comment]
I cannot reproduce this issue. Running Ubuntu 18.04 with CUDA 11.0 or 11.1, and they are detected just fine during `.configure`. It seems there is an issue with the submitter setup of CUDA.

Is CUDA recognized using TF 2.4?

**Comment by cement-head** [comment]
Okay, turns out that TensorRT is already pre-built in the repos; I just installed that!
