### ISSUE TITLE
Failed to build person_detection example test

### ISSUE THREAD

**Issue by gerbauz** [tensorflow/tensorflow#45469]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All (presumably)
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 4a11dfdd3bb
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): All (presumably), tested for ARC.

**Describe the problem**
As I can see, now there is no longer common person detection, and int8 version became the [main one](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/person_detection). 
So, actually I faced two issues, when I was trying to **build tests** for person detection.

1. [This command](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/README.md#run-the-tests-on-a-development-machine) doesn't work at all, it says `make: *** No rule to make target 'test_person_detection_test'.  Stop.` and the right target actually is `test_person_detection_test_int8` as it used to be when it was an experimental version. Similarly, test generation works with `make -f tensorflow/lite/micro/tools/make/Makefile generate_person_detection_test_int8_make_project`.
2. When test project is generated, it is stored in a following path: 
```
\gen\[platform]\prj\person_detection_test_int8\make
```
And build gives following error:
```
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8/person_detect_model_data.cc', needed by 'tensorflow/lite/micro/tools/make/downloads/person_model_int8/person_detect_model_data.o'.  Stop.
```
Thing is, it requires following project path (winthout _int8):
```
\gen\[platform]\prj\person_detection_test\make
```
If I change it manually, test can be built successfully. 

**Please provide the exact sequence of commands/steps when you ran into the problem**

1. `make -f tensorflow/lite/micro/tools/make/Makefile generate_person_detection_test_make_project`
2.  
```
make -f tensorflow/lite/micro/tools/make/Makefile generate_person_detection_test_int8_make_project
*go into project folder*
make
```

**Comment by henriwoodcock** [comment]
I've just run into this. Using `test_person_detection_test_int8` instead of `test_person_detection_test` works on macOS.

```
make -f tensorflow/lite/micro/tools/make/Makefile test_person_detection_test_int8
```

**Comment by njeffrie** [comment]
I'm working to update our documentation to always use person_detection_int8. At some point it may be worth renaming person_detection_int8 to person_detection since the original uint8 model is now gone, but in the meantime I'll make sure we use _int8 everywhere.

I'm unable to replicate the makefile project generation issue above after trying the steps listed. Perhaps this issue is already fixed? Let me know if it persists for you.
