### ISSUE TITLE
Cannot convert model: Exception has occurred: ValueError

### ISSUE THREAD

**Issue by Ecclesiast** [tensorflow/tensorflow#45460]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): built from source
- TensorFlow version (or github SHA if from source): 2.3.0

Here you can find a **tf-trt, tflite converter** issue with model train code and build model - [Collab Notebook](https://colab.research.google.com/drive/1-dRG9O2B_NfvjmQz9du5A0oRQJaIC6dH?usp=sharing) 
Here is the converter error
```
InvalidArgumentError: Input 1 of node functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall was passed float from Func/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/input/_1510:0 incompatible with expected resource.
```
**Also, please include a link to the saved model or GraphDef**
Here is the link to the saved_model also - [saved_model.zip](https://drive.google.com/file/d/10olY_D9HcSOjDS6Ufrrd2Ci6HA5kRW4D/view?usp=sharing)

**Failure details**
Trying to convert model to fp16 using tflite or with tf-trt. 
TensorRT - version 7.2.1.6
Cuda - 11.1
GPU - Nvidia GeForce 1060 6GB
Tensorflow as mentioned before - version 2.3.0 source build.
Also tried converting from saved_model directly but the problem is similar.

Can you help me with issues please? As I see, there is a problem somewhere in Input but I don't understand where.
Bigger priority here is to use TF-TRT, but TF-Lite is ok too.
Also could you please clarify which issues, bottleneck I can meet with this mix of tf, tf-text, tflite, tf-trt?

**Comment by abattery** [comment]
@Ecclesiast Could you try conversion with V2 converter API, from_saved_model?

**Comment by Ecclesiast** [comment]
If you mean 
```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/drive/MyDrive/test_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_model = converter.convert()
```
then yes. I mentioned above, that it doesn't work. The error is a bit different, but I consider the main idea is the same.
```
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    496         results = c_api.TF_GraphImportGraphDefWithResults(
--> 497             graph._c_graph, serialized, options)  # pylint: disable=protected-access
    498         results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: Input 1 of node StatefulPartitionedCall/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall was passed float from Func/StatefulPartitionedCall/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/input/_1009:0 incompatible with expected resource.

ValueError: Input 1 of node StatefulPartitionedCall/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall was passed float from Func/StatefulPartitionedCall/functional_1/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/input/_1009:0 incompatible with expected resource.
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/10da08af79ac01ee6d8b37460212db9c/45460.ipynb#scrollTo=AS3Lu3vY6fgz).

However with TF v2.2 and TF-nightly, importing `tensorflow_text` throws an error stating
```
NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```
Thanks!

**Comment by abattery** [comment]
@Ecclesiast

I tried to import the attached saved model through TensorFlow saved model loader. 

tensorflow/python/training/py_checkpoint_reader.py, in get_tensor
    self, compat.as_bytes(tensor_str))
IndexError: Requested 411640 bytes but only read 0.

The attached saved model may be not loadable because the checkpoint path is hard-coded somewhere in the saved model.

**Comment by Ecclesiast** [comment]
@amahendrakar tensorflow_text should be the same version as tf. Something with ABI, as I know. So if you are installing tf 2.2, then try install tensorflow_text==2.2.0.

**Comment by Ecclesiast** [comment]
@abattery I don't know actually what's the problem with this model, maybe something with compressing. 
Please, go to attached collab notebook. Last cells contains trainer class and training code for one iteration. 
You can execute them and save as a model.

**Comment by abattery** [comment]
@Ecclesiast

I was able to convert the trainer in the colab notebook to TFLite converter without any errors.

**Comment by abattery** [comment]
@Ecclesiast

I  would recommend training your model with the recent version of TF and TF text library and then convert your model with the same TF and TF text runtime.

**Comment by Ecclesiast** [comment]
@abattery thank you for your answer. Could you please specify which versions of these libraries I should use to convert models without errors?
Also is it a good solution to install tf-nightly side by side with tensorflow source build? As I remember, removing tf-nightly in future is a pain in the neck. And also tf-nightly as I understand is a developer builds of tf?
When can I count on unbuggy tf, tf_text, tf_lite versions?

**Comment by abattery** [comment]
@Ecclesiast I would say that there is a tf 2.4 released binaries. Could you use that version for your case?

**Comment by Ecclesiast** [comment]
@abattery There is no version I've tested on Collab that resolves this issue. I've tried different versions of tf-nightly(2.5.0.dev20201210, 2.4.0.dev20200902).
Also tried tensorflow==2.4.0rc1 and tensorflow_text==2.4.0rc1 - nothing works fine. 
Also this is important as the last stable release versions are 2.3.0 for both libraries and tensorflow-text is clarifying that versions of these libraries should be the same.
If you say, that everything is working fine for you - could you please share your tensorflow, tensorflow-text, tf-nightly versions?

**Comment by abattery** [comment]
What I succeeded is the following conversion procedure. However, the shared saved model are based on version 2.2 so I would recommend you to create a new saved model based on tf 2.4.0 rc version.

```
!pip install tensorflow==v2.4.0-rc4
!pip install tensorflow_text==2.4.0-rc1

cls_trainer = ClassificationTrainer()

train_dataset, valid_dataset = cls_trainer.convert2encoded()

cls_trainer.train(train_dataset, valid_dataset)
cls_trainer.save()

converter = tf.lite.TFLiteConverter.from_saved_model('PATH_TO_MODEL')
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS
]
model = converter.convert()
```
