### ISSUE TITLE
Strange Out Of Memory error when trying example Colab 

### ISSUE THREAD

**Issue by ando0689** [tensorflow/tensorflow#45468]
When I try to run the [officially provided Colab ](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer)
not changing any row, everything goes fine until the training `model = question_answer.create(train_data, model_spec=spec)` 
As soon as training process started, after a while it begins to consume memory with big chunks (e.g. memory consumption increases by 2GB per 2-3 seconds) and shortly it crashes the Colab environment as it throws Out of Memory error. I think this is some sort of a bug, because otherwise this will not be official example, or it would be documented somewhere in the example that the free Colab environment with 16GB ram is not enough to run this example. 
I also tried to run the example with much smaller dataset, but the same problem in the same way is being reproduced. So I am almost sure that this is a bug in the library.

**Comment by Saduf2019** [comment]
@ando0689 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Van you share your colab gist where the error is present.

**Comment by ando0689** [comment]
Hi. I am sorry for that, but actually I don't know what to fill there.
I opened this issue under the "Other" tag, as I guess it's not relevant what OS I use etc, because I just run the [**Official Tensorflow Lite Model Maker example Colab** ](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer) **without changing anything,** just running each cell one by one, and on the cell called "**Customize the TensorFlow Model**" I get out of memory error.

Is it relevant who runs the example or on what machine etc. if I just run it in Google Colab?

**Comment by ando0689** [comment]
I didn't provide enough information in this issue, so I close this and provided the full information here: https://github.com/tensorflow/tensorflow/issues/45541
