### ISSUE TITLE
How to unset changes made by tf.debugging.set_log_device_placement?

### ISSUE THREAD

**Issue by adityagupta679** [tensorflow/tensorflow#45465]
## Description of issue (what needs changing): 
It is not specified as to how to unset the changes made by this function.  Therefore it's becoming difficult to suppress the info level messages and a long trail of info messages gets printed leading to difficulty in analyzing actual results.

![image](https://user-images.githubusercontent.com/9129069/101432051-265f7100-392e-11eb-9987-f5b1de11e71f.png)

### Clear description

Maybe a feature needs to be developed to provide functionality within the function to disable its behaviour.

`tf.debugging.set_log_device_placement(False)`
`tf.get_logger().setLevel(3)`
`os.environ["KMP_WARNINGS"] = "FALSE" `
`tf.get_logger().setLevel('INFO')`

None of the above methods work.
### Correct links

Is the link to the source code correct? Yes

### Parameters defined

Are all parameters defined and formatted correctly? Yes
 
### Returns defined

Are return values defined? Yes

### Raises listed and defined

NA

### Usage example

Is there a usage example?

Yes

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?  NA

### Submit a pull request? 

Unclear how to slove the issue yet.

**Comment by amahendrakar** [comment]
@adityagupta679,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
> None of the above methods work.

Also, try setting the log level before importing TensorFlow as shown below and check if it works.

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"
import tensorflow as tf
...
```
Thanks!

**Comment by adityagupta679** [comment]
> @adityagupta679,
> In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!


> > None of the above methods work.
> 
> Also, try setting the log level before importing TensorFlow as shown below and check if it works.
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"
> import tensorflow as tf
> ...
> ```
> 
> Thanks!

Hey , This code can regenerate the issue. GPU environment is required for the messages to be shown at all. I ran on Google colab using Tensorflow version 2.3.0 . Notice that in the second run of the matmul operation, the messages should not be displayed but are still displayed. 
Trying the workaround you suggest also does not work.  Additionally, the issue is that I wish to be able to turn the messages on/off at the requirement. Maybe a feature needs to be added for that. Till then if possible a workaround can be displayed in the documentation. 
 
```
import tensorflow as tf
import os
tf.config.set_soft_device_placement(True)
tf.debugging.set_log_device_placement(True)
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)
tf.config.set_soft_device_placement(False)
tf.debugging.set_log_device_placement(False)
tf.get_logger().setLevel(3)
os.environ["KMP_WARNINGS"] = "FALSE" 
tf.get_logger().setLevel('WARNING')
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)
```

> O/P

> Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
> tf.Tensor(
> [[22. 28.]
>  [49. 64.]], shape=(2, 2), dtype=float32)
> Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
> tf.Tensor(
> [[22. 28.]
>  [49. 64.]], shape=(2, 2), dtype=float32)

**Comment by rohan100jain** [comment]
These configuration flags are for the entire program and cannot be changed after startup. I agree that we should document this aspect and throw even an error message if it is called post initialization.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
