### ISSUE TITLE
Pip install issue on windows 10 with error ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\jc_mr.TSE-DEV64-2\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\tensorflow\\include\\external\\aws\\aws-cpp-sdk-core\\include\\aws\\core\\client\\SpecifiedRetryableErrorsRetryStrategy.h'

### ISSUE THREAD

**Issue by TSE-jc** [tensorflow/tensorflow#45462]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Please fill issue template

**Comment by TSE-jc** [comment]
Issue closed. Was due to a windows file long path management not activated.

**Comment by nafi90** [comment]
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\mkays\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'


Got this error while installing torch

**Comment by gorkemgoknar** [comment]
See following post to enable Long path in Windows : https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing#:~:text=Hit%20the%20Windows%20key%2C%20type,paths%20option%20and%20enable%20it.
