### ISSUE TITLE
tf.nn larger support for RaggedTensor

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#45476]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I would like to be able to use `tf.nn`, and in turn `tf.keras.layers` such as `Conv2D` on `RaggedTensor`.

**Will this change the current api? How?**

I think it shouldn't in any way, just that keras layers and tf.nn operations should accept ragged tensors.

**Who will benefit with this feature?**

Anyone wanting to use keras layers on ragged tensors. 
I am giving a bit more explanation on my specific use case below.

**Any Other info.**

So in my use case, I want to perform distributed training using images that have widely different sizes (and it doesn't make sense to pad them). I would want for each of the elements of the ragged tensor to be distributed on different GPUs.
But if I use a ragged tensor as is, it is not supported by my models with an error like:

```
TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=tf.RaggedTensor(values=tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:4", shape=(None, 1), dtype=complex64), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:3", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:2", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.
```

Even if I use the setting advised [here](https://github.com/tensorflow/tensorflow/issues/27170#issuecomment-587571120), I still get this error.

**Comment by edloper** [comment]
Is this still an issue?  If so, can you provide a code snippet to reproduce it?

**Comment by jvishnuvardhan** [comment]
@zaccharieramzi Can you please share a simple standalone code as requested above? Thanks!

**Comment by zaccharieramzi** [comment]
Yes sorry about the delayed response, I am not really suffering from this issue anymore, but here is a simple standalone code:

```python
import tensorflow as tf
from tensorflow import keras
a = tf.ragged.stack([
  tf.random.normal(shape=[2, 2, 1]),
  tf.random.normal(shape=[3, 3, 1]),
], axis=0)
model = keras.models.Sequential(keras.layers.Conv2D(1, 3, padding='same'))
model(a)
```

You can find a colab [here](https://colab.research.google.com/drive/1SJKUp28Oe94DIoV-zVOLSwKdsycycAy9?usp=sharing).

**Comment by jvishnuvardhan** [comment]
@edloper Can you please take a look at this issue. I can reproduce the issue with `TF2.7`. Thanks!
