### ISSUE TITLE
Raspberry Pi 4 camera feed doesn't appear

### ISSUE THREAD

**Issue by Yosonix** [tensorflow/tensorflow#45470]
Hi everyone,

**System information**
- OS Platform and Distribution : Raspbian
- TensorFlow installed from : binary
- TensorFlow version : v2.3.0-0-gb36436b087 2.3.0
- Python version: Python 3.7.3
- Model : Raspberry Pi 4 4gb ram

**Describe the current behavior**
When I'm using [image_classification example](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/raspberry_pi) or [object_detection example](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi) I didn't get any error but the camera feed doesn't appear so I couldn't check if it's working.

**Other info / logs**
I checked picamera and I could get the stream from the pi camera so my camera is working great.
I build and install from setup.py in the main directory and downloaded the files in /tmp.
Everytime I use ctrl+c to stop the program I got different writing like it is looping into the code. 

Thanks for you help.

I attached a picture with the terminal.
<img width="1213" alt="Capture d’écran 2020-12-08 à 11 37 08" src="https://user-images.githubusercontent.com/45320002/101474746-d2638500-394b-11eb-9ad9-fcdbaa383bad.png">

**Comment by sushreebarsa** [comment]
@Yosonix It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version TF 2.5 and let us know if the issue still persists? Thanks!
