### ISSUE TITLE
Failed to load native tensorflow runtime

### ISSUE THREAD

**Issue by shreeraj04** [tensorflow/tensorflow#45471]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Windows Server 2012 R2 Standard
- TensorFlow installed from : Binary (pip)
- TensorFlow version: 2.2.0
- Python version: 3.7.2
- Installed using : pip
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Tensorflow is installed without any issues. But when running my program I am getting the below error.

> D:\Tetherfi\TRS\TFaceAuthServer>python tfacecompare.py
> Traceback (most recent call last):
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_hel
> per
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
> ion)
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\imp.py", li
> ne 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\imp.py", li
> ne 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tfacecompare.py", line 20, in <module>
>     import tensorflow.keras
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\__init__.py", line 50, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\site-packag
> es\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_hel
> per
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
> ion)
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\imp.py", li
> ne 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\kiolocal\AppData\Local\Programs\Python\Python37\lib\imp.py", li
> ne 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

I have tried installing visual c++ redistributable for 2015 (64 and 32 bit), but still the same. Reinstalling of python also didn't help.
Please guide and help to solve this.

**Comment by Saduf2019** [comment]
@shreeraj04 
Could you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/45435#issuecomment-739659395) and let us know if all the requirements are met as this is the common reason for the error.
