### ISSUE TITLE
When pre-built libtensorflow C API will be updated to 2.4?

### ISSUE THREAD

**Issue by VladislavAD** [tensorflow/tensorflow#45477]
I rely on pre-build C API libs that I download from https://www.tensorflow.org/install/lang_c, so I wonder when it is going to be updated with recent tensorflow 2.4 version with CUDA 11 support.

**Comment by mihaimaruseac** [comment]
When TF 2.4 pip package is released, later this week or the next.

**Comment by VladislavAD** [comment]
Thanks, hope prebuild C API will be updated with 2.4 release.

**Comment by rmothukuru** [comment]
@VladislavAD,
Now that pip package is released for Tensorflow Version 2.4, can you please confirm if your issue is resolved? Thanks!

**Comment by VladislavAD** [comment]
Precompiled C API is still 2.3.1 version to download https://www.tensorflow.org/install/lang_c so issue is not resolved yet.

**Comment by photex** [comment]
+1 We just got the unfortunate surprise of not being able to run our application on our new RTX 3090 hardware.

**Comment by VladislavAD** [comment]
Any estimated time when precompiled C API libs will be updated?

**Comment by photex** [comment]
If you copy the URL and change it to 2.4.0 it's there. I deployed my app successfully this past week on ubuntu 20.04 using an RTX 3090.

**Comment by VladislavAD** [comment]
Wow thanks, I downloaded them with your advice. Well this isn't obvious that libs exists and are avaliable.

**Comment by photex** [comment]
Yeah. I wish there was a listing of versions available to be honest. I took a guess and it worked out 🤣

**Comment by mihaimaruseac** [comment]
Apologies. This being the holiday season the website pipeline has been frozen and no update happened. In January we should get the URLs fixed.

**Comment by VladislavAD** [comment]
What CUDA version needed for precompiled lib? 11.0, 11.1 or 11.2?

**Comment by photex** [comment]
We are using 11.1 and the most recent cuDNN v8 (maybe 8.0.2?)

**Comment by mihaimaruseac** [comment]
The links are updated now, closing this one.
