### ISSUE TITLE
import tensorflow on apache2 cgi module

### ISSUE THREAD

**Issue by JYKim9628** [tensorflow/tensorflow#4547]
I try to run tensorflow on web server python cgi
I succeed in running python in apache2 web server

but I stoped by environment variables :LD_LIBRARY_PATH set in Python Code

I run os.environ:function and result print check
This result is correct value
I don't know what can i do

I need you help

**my code is** 
```

import cgi
import os
import cgitb
cgitb.enable()

import requests

print("Content-type: text/html;charset=utf-8\r\n")

print("<html>")
print("<head>")
print("\t<title>Python CGI Test</title>")
print("</head>")
print("<body>")
print("\t<h1>Hello, Python CGI!</h1>")
print("</body>")
print("</html>")


os.environ["LD_LIBRARY_PATH"] = '$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64'

print os.environ
print ("")


import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
```

**and result**

> Hello, Python CGI!
> 
> {'CONTEXT_DOCUMENT_ROOT': '/var/www/html', 'SERVER_SOFTWARE': 'Apache/2.4.18 (Ubuntu)', 'CONTEXT_PREFIX': '', 'SERVER_SIGNATURE': '
> Apache/2.4.18 (Ubuntu) Server at 192.168.0.115 Port 80
> \n', 'REQUEST_METHOD': 'GET', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LD_LIBRARY_PATH': '$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64', 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '192.168.0.115', 'REMOTE_PORT': '57930', 'SERVER_PORT': '80', 'SERVER_ADDR': '192.168.0.115', 'DOCUMENT_ROOT': '/var/www/html', 'SCRIPT_FILENAME': '/var/www/html/123.py', 'SERVER_ADMIN': 'webmaster@localhost', 'HTTP_HOST': '192.168.0.115', 'SCRIPT_NAME': '/123.py', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_CACHE_CONTROL': 'max-age=0', 'REQUEST_URI': '/123.py', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'GATEWAY_INTERFACE': 'CGI/1.1', 'REMOTE_ADDR': '192.168.0.115', 'HTTP_ACCEPT_LANGUAGE': 'ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4', 'REQUEST_SCHEME': 'http', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch'} --> -->
>  
>  
> <type 'exceptions.ImportError'>	Python 2.7.12: /home/mutation/anaconda2/bin/python2.7
> Fri Sep 23 15:28:53 2016
> A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.
> 
>  /var/www/html/123.py in ()
>      41 
>      42 
> =>   43 import tensorflow as tf
>      44 hello = tf.constant('Hello, TensorFlow!')
>      45 sess = tf.Session()
> tensorflow undefined, tf undefined
>  /home/mutation/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py in ()
>      19 from __future__ import absolute_import
>      20 from __future__ import division
>      21 from __future__ import print_function
>      22 
> =>   23 from tensorflow.python import *
> tensorflow undefined
>  /home/mutation/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py in ()
>      46 _default_dlopen_flags = sys.getdlopenflags()
>      47 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
> =>   48 from tensorflow.python import pywrap_tensorflow
>      49 sys.setdlopenflags(_default_dlopen_flags)
>      50 
> tensorflow undefined, pywrap_tensorflow undefined
>  /home/mutation/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in ()
>      26                 fp.close()
>      27             return _mod
> =>   28     _pywrap_tensorflow = swig_import_helper()
>      29     del swig_import_helper
>      30 else:
> _pywrap_tensorflow undefined, swig_import_helper = None
>  /home/mutation/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
>      22         if fp is not None:
>      23             try:
> =>   24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
>      25             finally:
>      26                 fp.close()
> _mod undefined, imp = <module 'imp' (built-in)>, imp.load_module = <built-in function load_module>, fp = <closed file '/home/mutation/anaconda2/lib/pytho...sorflow/python/_pywrap_tensorflow.so', mode 'rb'>, pathname = '/home/mutation/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so', description = ('.so', 'rb', 3)
> <type 'exceptions.ImportError'>: libcudart.so.8.0: cannot open shared object file: No such file or directory 
>       args = ('libcudart.so.8.0: cannot open shared object file: No such file or directory',) 
>       message = 'libcudart.so.8.0: cannot open shared object file: No such file or directory'

**Comment by rperdon** [comment]
Hi, were you able to find a solution to this?

**Comment by JYKim9628** [comment]
I'm sorry my answer too late

I found solution 

The solution is that set environment value in apache config

**Comment by MacroMayhem** [comment]
Can you elaborate on the solution @dotdotgod ?
