### ISSUE TITLE
TF-TRT Dynamic Shapes Feature Tracker

### ISSUE THREAD

**Issue by tfeher** [tensorflow/tensorflow#45481]
### Introduction
The dynamic shape mode in TF-TRT utilizes TensorRT’s [dynamic shape feature](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes) to improve the conversion rate of networks and handle networks with unknown input shapes efficiently. This issue tracks the ongoing development to enable TRT's dynamic shape mode trough TF-TRT.

**Who will benefit with this feature?**
The conversion rate and therefore the performance will improve for the following inference problems:
- Network with unknown input shapes (e.g. fully convolutional object detection networks)
- Networks where the first (batch) dimension of a tensor changes within the graph (e.g. BERT)
- Networks that have subgraphs where the tensors have non identical first dimension

Additionally the memory usage will improve: to handle input tensors with different shapes (eg image size, sequence length) currently requires separate TRT engine creation for each input. With dynamic shape mode a single engine can handle various input shapes.

**Will this change the current api? How?**

Some change in the [conversion parameters](https://github.com/tensorflow/tensorflow/blob/b34e7144ed6dd0ab51c03df783aa14009589e800/tensorflow/python/compiler/tensorrt/trt_convert.py#L118) will be necessary to enable/disable dynamic shape mode and provide a way to select optimization profiles.

### Phase 1
The first phase of this work is the basic scaffolding to enable the TF-TRT converter to use TRT's dynami shape API.

0. Add implicit batch experimental #34293
1. Enable explicit batch mode #36379
2. Improve binding index query #36434
3. Add binding size specification #36435
4. Define networks with dynamic shapes #36439
5. Add optimizaton profiles #36660
6. Execution context managment #36664
7. TensorRT profile generation mode #36729

### Phase 2
Enable dynamic shape mode for ops used in MobileNet, ResNet, Bert. This includes improvement in the converters plus increasing their unit test coverage. Note that at this stage dynamic shape mode is still experimental.

- Refactor ExecuteTrtEngine #38118 
- Use Unified Memory in TRT opconverter tests  #38124
- ConvertSqueeze #38146
- ConvertUnary, ConvertRsqrt #39153
- ConvertTranspose #39151 
- ConvertActivation, ConvertLeakyRelu #39155 
- BiasAdd - ConvertBiasAdd #39156
- Conv2D, DepthWiseConv2dNative #39204
- ConvertConv2dBackPropInput #47840
- ConvertPack #39859
- ConvertReshape #40545
- ConvertExpandDims  #39282
- ConvertSlice, ConvertStridedSlice #40736
- ConvertGather #39848
- ConvertMatMul and ConvertBatchMatMul #47215
- ConvertBinary #39785
- ConvertSquaredDifference #39758
- ConvertReduce #40201
- ConvertFusedBatchNorm #40179
- ConvertSoftMax  #47039
- ConvertShape #39990
- ConvertPool #40184
- Update related python integration tests: Unary_test.py, Batch_matmul_test.py, biasadd_matmul_test.py, Conv2d_test.py, reshape_traspose_test.py

### Phase 3
This is a direct continuation of Phase 2. Ensure that all op converter support dynamic shape mode and test it. We have almost 20 converters to update and test. The bulk of this work is improving the test coverage. 
- ConvertSquare #40483
- ConvertClipByValue #45589 
- ConvertPad #45597
- ConvertResize #46376
- ConvertArgMinMax #45862 
- ConvertQuantize #45599
- ConvertTopK #46299
- ConvertUnpack #48049
- ConvertAddN #46675 
- ConvertConcat #46382
- ConvertConv3D #46940
- ConvertDepthSpaceShuffle #47590
- ConvertSplit #48246
- ConvertCombinedNMS #40062
- Enable calibration if static input shapes are used #48244

### Phase 3+
Some converters in phase 3 were updated only for explicit batch support with static shape. Enable dynamic shape mode for them:
- ConvertCombinedNMS
- ConvertResize #51462
- ConvertStridedSlice #51475
- ConvertConv2DBackpropInput #51468

Additionally:
- Fix shape output bug https://github.com/tensorflow/tensorrt/issues/251 
  #52181 
  #52186
- Update python integration tests #51411 #51471

### Phase 4
 Implement calibration in dynamic shape mode. Using TRT 7.1 one can  run calibration in [dynamic shape mode](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#int8-calib-dynamic-shapes).
- TRTEngineOp: allow profile collection before calibration
- Refine APIs: build mode + calibration + lazy calibration

### Phase 5
Test performance of dynamic shape mode

### Phase 6
Define API to enable dynamic shape and specify optimization profiles.
- Finalize API - [implemeted here](https://github.com/tensorflow/tensorflow/blob/e52ccf29b87d7262078040b86a0fb4669149cb05/tensorflow/python/compiler/tensorrt/trt_convert.py#L944-L987)
- Implement additional optimization profiles
  - basic profiles for testing #45588 
  - Pass profile params to TrtShapeOptimizationProfiles class #48060
  - Implement Range, Range+Optimal profiles #48414

### Phase 7
- C++ conversion API #52012
Optional elements from Phase 6 are moved here.
- Implement UserDefined profile 
- Change default conversion param from implicit batch mode to dynamic shape mode

Tagging @DEKHTIARJonathan and @bixia1

**Comment by DrXuQian** [comment]
Hi tfeher, About 'Networks where the first (batch) dimension of a tensor changes within the graph (e.g. BERT)'.
Why would the first dimension change within the graph? I would assume that once the batch size is determined, the shape won't change throughout graph of BERT.

**Comment by tfeher** [comment]
> Why would the first dimension change within the graph?

Some networks do reshape operations that change the first dim. It is done internally to express some operations more conveniently, the output is usually reshaped again to have the expected batch size. An example is [BERT TF1 model](https://github.com/NVIDIA/DeepLearningExamples/blob/c481324031ecf0f70f8939516c02e16cac60446d/TensorFlow/LanguageModeling/BERT/modeling.py#L674). 

The dynamic shape feature of TF-TRT improves the TR conversion of such networks.

**Comment by jiweibo** [comment]
Hi, @tfeher can tf-trt dynamic_batch support the situation of being divided into multiple trt subgraphs now? 
And how should we set the shape information of the min, max, and opt of the internal subgraph?

![image](https://user-images.githubusercontent.com/26377421/127456355-b87ee9f3-2ccf-4bc9-a92f-c98aaf0fc4fe.png)

**Comment by tfeher** [comment]
> can tf-trt dynamic_batch support the situation of being divided into multiple trt subgraphs now?

Yes, dynamic shape mode supports graphs that have multiple TRT subgraphs. There is a known issue https://github.com/tensorflow/tensorrt/issues/251, which occurs if the trt_engine_op is trying to output shape tensors. Otherwise it should work.

> And how should we set the shape information of the min, max, and opt of the internal subgraph?

You only need to set the shape information for the inputs of the model. From these we calculate the size of any tensor in the graph, and set input shape information for the internal TRT subgraphs (`trt_engine_ops`).
