### ISSUE TITLE
r0.10: ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#4548]
My code runs well on r0.9, and after I upgrade to r0.10, and it runs failed. And my TF r0.10 is built from source also.

**Comment by AlvinChen13** [comment]
More information: since r0.10 needs setuptool > 1.7, and the installed setuptool is 0.98, then I update it to 27.3. And then I switch back to TF r0.9, encounter the same error. 

Anyone use r0.10, and what's the version of setuptool used?

**Comment by vigneshstack** [comment]
How did you tried to revert it back to previous build ?

**Comment by AlvinChen13** [comment]
I can't revert it back, it seems the python issue. Now, my yum can't work after I delete /usr/lib/python2.7/site-packages/. I am not sure whether such packages, like python, setuptools are OS related, and I use centos 7. I dowload the python 7.5.12 source code to rebuild it, and install. But it still can't work.

After I dowload setuptool27.3 and install it, even r0.9 can't work, and it can work well before...

root@hal-dev share]# yum
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   No module named yum

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq
  

[root@hal-dev share]# 

[alvin@hal-dev mnist]$ 
[alvin@hal-dev mnist]$ python convolutional.py 
Traceback (most recent call last):
  File "convolutional.py", line 31, in <module>
    import numpy
ImportError: No module named numpy
[alvin@hal-dev mnist]$

**Comment by vigneshstack** [comment]
Here we have multiple issues !!

Because it's conflicting with YUM package manager and python modules, if possible could you provide cat convolutional.py

**Comment by AlvinChen13** [comment]
Firstly, my original r0.9 works well, then I want to upgrade to r0.10, since r0.10 need setuptool > 1.7, and I updated setuptools to 27.3 manually, then both r0.10 and r0.9 can't work. Then I do a lot of OPs to python, then yum can't work after I delete /usr/lib/python2.7/site-packages since I try to update it by re-install pip.
'convolutional.py' is the example of mnist in repo, and I haven't change it.

**Comment by AlvinChen13** [comment]
@vigneshstack I copy the 'site-packages' from another machine, and now the yum can work. But my r0.9 still can't work for the example 'tensorflow-r0.9/tensorflow/models/image/mnist'.. I follow the steps:
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

mkdir _python_build
cd _python_build
ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
ln -s ../tensorflow/tools/pip_package/* .
python setup.py develop

**Comment by AlvinChen13** [comment]
BTW, the following works well:

$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

$ bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

**Comment by jmchen-g** [comment]
@jart Could you take a look at this? Thanks.

**Comment by AlvinChen13** [comment]
The python issues are solved. 

Hold on this issue, although I still can't run r0.10 due to my network connection while do configuring.

**Comment by AlvinChen13** [comment]
4 nodes get 4x performance improving, and the network is the bottleneck.
