### ISSUE TITLE
Selective builds to reduce tensorflow-lite binary size missing needed java package org.tensorflow.lite

### ISSUE THREAD

**Issue by duudat** [tensorflow/tensorflow#45488]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
Try to build a custom .aar file from https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/tools/build_aar_with_docker.sh

**Describe the problem**
The result aar.file missing all java-wrapper classes (Interpreter, etc) under package: org.tensorflow.lite. These classes are needed to perform inference from a model in Android.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Following the instruction building selective build for a given tflite model using docker: https://www.tensorflow.org/lite/guide/reduce_binary_size#selectively_build_tensorflow_lite_with_docker

```
curl -o build_aar_with_docker.sh \
  https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/tools/build_aar_with_docker.sh &&
chmod +x build_aar_with_docker.sh
```

and 
```
sh tensorflow/lite/tools/build_aar.sh \
  --input_models=/a/b/my_model.tflite \
  --target_archs=x86,x86_64,arm64-v8a,armeabi-v7a \
  --checkpoint=master \
```

**Any other info/ logs**
Rename resulted aar files to .zip and attached:

1. aar file built from Mobilenet_1.0_224(float) model: [tensorflow-lite-with-mobile-net-model.zip](https://github.com/tensorflow/tensorflow/files/5661364/tensorflow-lite-with-mobile-net-model.zip)
2. aar file built from my custom model: [tflite-with-my-custom-model.zip](https://github.com/tensorflow/tensorflow/files/5661324/tflite-with-my-custom-model.zip)

Both missing java classes

Note: did try to copy needed java classes into the resulted_aar but this approach seems not working. Might-be the generated .so files missing C++ files which support org.tensorflow.lite java classes as well.

**Comment by thaink** [comment]
Hi @duudat What it means by "in order for it to run locally: org.tensorflow.lite.Interpreter, etc."?
Are you using it in an Android project?

**Comment by thaink** [comment]
@wangtz I found it has been this way since day 1 of this feature.
However, It seems to work fine with Android since then.
Do you have any insights on this?

**Comment by duudat** [comment]
@thaink Yes, you are correct, I use the generated aar file in my Android project to cutting the size of 'org.tensorflow:tensorflow-lite:x.x.x'.
Specifically, my assumption by follow the instructions: https://www.tensorflow.org/lite/guide/reduce_binary_size#selectively_build_tensorflow_lite_with_docker is that:
The resulted `tensorflow-lite.aar` will replace 'org.tensorflow:tensorflow-lite:x.x.x' dependency in my Android project. 

In Android, to get on-device inference out of a model, it requires java Interpreters, and other java classes under package: org.apache.tensorflow-lite which is missing in the new generated`tensorflow-lite.aar`, so I got compile errors of `cannot find symbol class Interpreter.`

**Comment by duudat** [comment]
Minor thing I notices is that: the generated aar file seems to also exclude other files inside normal 'org.tensorflow:tensorflow-lite:x.x.x' aar file from Center: proguard.txt, headers.

<img width="799" alt="Screen Shot 2020-12-09 at 12 13 59 AM" src="https://user-images.githubusercontent.com/65645909/101602842-8f3cfc80-39b3-11eb-8b31-5c10d0287c06.png">

At least proguard.txt is, for sure, needed in most aar files if the Android app, which uses the aar, enabled size optimization, resource shrinking.

**Comment by duudat** [comment]
@thaink you have suggestion to get around with the errors: `cannot find symbol class Interpreter.` without adding 'org.tensorflow:tensorflow-lite:x.x.x'  dependency to my build.gradle file.

**Comment by thaink** [comment]
@duudat Your use is right. Let me check the cause of this.

**Comment by duudat** [comment]
@thaink any update on this issue?

**Comment by duudat** [comment]
I could locally include needed java classes by modyfing build_aar.sh as following.


[modified_build_aar.txt](https://github.com/tensorflow/tensorflow/files/5698153/modified_build_aar.txt)

**Comment by thaink** [comment]
thanks for the info @duudat. I was able to reproduce this issue.

**Comment by thaink** [comment]
The issue is fixed at master branch.
