### ISSUE TITLE
> It  work for me.Thank you

### ISSUE THREAD

**Issue by CodePythonFollow** [tensorflow/tensorflow#45497]
> It didn't work for me. Still getting that error.

try
`conda update wrapt`

_Originally posted by @congee524 in https://github.com/tensorflow/tensorflow/issues/30191#issuecomment-514249543_

**Comment by amahendrakar** [comment]
@CodePythonFollow,
Could you please describe in detail the issue you are facing and provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Thanks!

**Comment by mihaimaruseac** [comment]
Closing as spam
