### ISSUE TITLE
tensorboard can not work

### ISSUE THREAD

**Issue by cdmajie** [tensorflow/tensorflow#4549]
when i run tensorboard demo:
1. python mnist_with_summaries.py   OK
2. tensorboard --logdir=/tmp/mnist_logs/  
print like this 
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js
127.0.0.1 - - [23/Sep/2016 16:55:12] "GET /lib/css/global.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Sep/2016 16:55:12] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/dist/bazel-html-imports.html' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/dist/bazel-html-imports.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/external/dist/bazel-html-imports.html' on path /usr/local/lib/python2.7/dist-packages/external/dist/bazel-html-imports.html
127.0.0.1 - - [23/Sep/2016 16:55:12] code 404, message Not Found
127.0.0.1 - - [23/Sep/2016 16:55:12] "GET /dist/bazel-html-imports.html HTTP/1.1" 404 -
127.0.0.1 - - [23/Sep/2016 16:55:12] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/polymer/polymer.html' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/polymer/polymer.html
127.0.0.1 - - [23/Sep/2016 16:55:12] "GET /polymer/polymer.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/iron-icons/iron-icons.html' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/iron-icons/iron-icons.html
.......

No such file or directory error 

how can i install these file ?

**Comment by cdmajie** [comment]
change firefox to chrome can slove this problem.

**Comment by cbquillen** [comment]
I had this problem too with 0.11rc.  0.10 doesn't have any issues with firefox though.

**Comment by tripiana** [comment]
Please @cdmajie reopen this issue, firefox is important enough to take a closer look.

**Comment by MatthiasWinkelmann** [comment]
I ran into the same problem – using Chrome. It's not browser-specific.

I had installed tf using the instructions at [https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#using-pip](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#using-pip), specifically:

```
# Mac OS X, GPU enabled, Python 3.4 or 3.5:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0-py3-none-any.whl
```

The file ```dist/bazel-html-imports.html``` was not in ```/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/dist```. I copied a few files from github (```package.json```, ```bower.json```, etc.) and ran bower and npm install and somehow got it working – numericjs was also missing.

I can't make sense of the build system fast enough to contribute a useful pull request, but from browsing the changes, I'd guess @dsmilkov may be able to help.

**Comment by pannous** [comment]
see #5341 for workaround
