### ISSUE TITLE
TF2 GPUs on Kubernetes

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorflow#45494]
I made a helm chart for TF2 and it doesn't seem to be able to recognize the GPU, although cupy seems to work fine. 
Is there any avail guidance on this or working helm chart example to inspect?

**Comment by joehoeller** [comment]
@ymodak would you be able to assist please?

**Comment by ymodak** [comment]
What is your TF version and cuda version?
See https://www.tensorflow.org/install/source#gpu for TF and cuda version compatibility.

**Comment by joehoeller** [comment]
The AWS AMI is CUDA 11, the docker image it pulls from is CUDA 10.1.

**Comment by joehoeller** [comment]
Does TF2 distribute across VMs/ your whole K8s cluster?

**Comment by joehoeller** [comment]
@sanjoy ?

**Comment by sanjoy** [comment]
@joehoeller Can you share the logs from the TF run?  I'm not familiar with helm, but TF 2.4 depends on CUDA 11.0, if you have some other version of CUDA installed then GPU support will be disabled.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
