### ISSUE TITLE
Bus error when load the tflite model

### ISSUE THREAD

**Issue by SelvaMuruganChithiraipandi** [tensorflow/tensorflow#45504]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 4.14.119
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Installed tflite runtime from source code.
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 8.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I have enable the FlexDelegate and compiled the tflite runtime code by using the below command for ARM 32bit machine, the wheel file is created and I have installed it in my machine. But when I load the .tflite model, I am getting the Bus error. But, I didn't got this "Bus error" when I use the same wheel file in Raspberry Pi, it is working fine in the Raspberry Pi(ARM 32bit).

Before enable the FlexDelegate I didn't got this Bus error while load the tflite model, but that time I got the below RuntimeError.
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 16 (FlexMul) failed to prepare.

Note: Actually my machine is the aarm64 64bit machine, but due to some build restrictions I am using the 32bit applications in my machine.

**Command used for compilation:**
CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true -e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.7" tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf

**Other info / logs**
I ran the code by using gdb and got the below back trace.

INFO: Created TensorFlow Lite delegate for select TF ops.
[New Thread 0xebc59460 (LWP 1157)]
[New Thread 0xeb458460 (LWP 1158)]
[New Thread 0xeaa57460 (LWP 1159)]
[New Thread 0xea0ff460 (LWP 1160)]
[New Thread 0xe94ff460 (LWP 1161)]

Thread 2 "python3" received signal SIGBUS, Bus error.
[Switching to Thread 0xebc59460 (LWP 1157)]
0xf642d574 in std::condition_variable::condition_variable (this=0xea10075c)
    at /tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/obj/gcc3/arm-linux-gnueabihf/libstdc++-v3/include/condition_variable:65
65	/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/obj/gcc3/arm-linux-gnueabihf/libstdc++-v3/include/condition_variable: No such file or directory.
(gdb) bt
#0  0xf642d574 in std::condition_variable::condition_variable (this=0xea10075c)
    at /tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/obj/gcc3/arm-linux-gnueabihf/libstdc++-v3/include/condition_variable:65
#1  0xf4df5a24 in nsync::nsync_mu_semaphore_init(nsync::nsync_semaphore_s_*) ()
   from /usr/lib/python3.7/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by terryheo** [comment]
What's the target OS? Is it Raspberry Pi OS?
If it's your custom HW, I think there is an ABI compatibility issue. You can check flags of /proc/cpuinfo.
FYI, we only have tested ARM with Raspberry Pi OS, Ubuntu Server for ARM, Coral.

**Comment by SelvaMuruganChithiraipandi** [comment]
Target OS: Linux 4.14.119

root@as371:~$cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 50.00
Features	: fp asimd aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 50.00
Features	: fp asimd aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 50.00
Features	: fp asimd aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 50.00
Features	: fp asimd aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

root@as371:~$

**Comment by SelvaMuruganChithiraipandi** [comment]
Hi, how to check the flags of /proc/cpuinfo to find is it really ABI compatibility issue or not? If it is an ABI compatibility issue, how to fix this ?

**Comment by terryheo** [comment]
TF's armhf toolchain compiles ARMv7 binary with NEON and VFP supports which are missing from yours.

FYI, this is RPI3's.
```
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

Also you can check ABI of binary with readelf.
```
$ readelf -A benchmark_model
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```
You can compare it with yours.

You might want to add some GCC options to CUSTOM_BAZEL_FLAGS to make it compatible with your target hw.
https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by SelvaMuruganChithiraipandi** [comment]
Hi, I got the below information in my benchmark_model and tflite runtime .so file, this looks similar to yours. 

I saw the "--define=raspberry_pi_with_neon=true" in BAZEL_FLAGS, what is the use of this flag? Is this enabling something specific to Raspberry Pi? Are we also need to enable something like that?

We are using cortex-A53 ARM64 machine, but we are using 32bit applications because of some build restrictions. In our /proc/cpuinfo we have the "asimd", "asimd" is the "neon" equivalent in ARM Cortex A53.

$ readelf -A benchmark_model 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6


$ readelf -A _pywrap_tensorflow_interpreter_wrapper.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv4
  Tag_Advanced_SIMD_arch: NEONv1 with Fused-MAC
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
selva@selva-Lenovo-V130-15IKB:~/cogknit/runtime/flex_enabled_for_armv7/tflite_runtime$

**Comment by SelvaMuruganChithiraipandi** [comment]
Hi, initially I got the below RuntimeError when load the tflite model, so I have enabled the FlexDelegate. Is the below "FlexMul" feature requires VFP (or) NEON suppor? And Is it possible to compile the tflite runtime only with the below "FlexMul" Flex delegate feature?


RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 16 (FlexMul) failed to prepare

**Comment by terryheo** [comment]
https://www.tensorflow.org/lite/guide/reduce_binary_size may be helpful.

**Comment by SelvaMuruganChithiraipandi** [comment]
I am still getting the bus error. I am trying to run a .tflite model for ASR which I got from another company on Synaptics based Arm platform. It is Cortex A53 but we are using armv7a ISA and building 32-bit binaries. 

The ASR code requires tflite_runtime to be enabled with "flex delegate" which causes the crash on my embedded target but it works on Raspberry PI board. When the tflite_runtime is built with "flex delegate" option for PI, I saw the "--define=raspberry_pi_with_neon=true" in BAZEL_FLAGS. I tried enabling and disabling this flag while building for my target board, but it still crashes. I am wondering what else can be tried out. Could you please suggest?

**Comment by terryheo** [comment]
Using Flex op requires to build TF op kernels which is difficult to support various targets.
If the required Flex op is only FlexMul, I think you might be able to create Flex-free ASR model with some refactoring.
