### ISSUE TITLE
Feature request: add TensorFlow Serving to conda-forge as well

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#4551]
[TensorFlow made it into conda-forge](https://github.com/conda-forge/tensorflow-feedstock) which is awesome, but could TensorFlow Serving be provided as well for easier CI? Installing bazel just for building Serving during a CI run is a bit excessive.

**Comment by concretevitamin** [comment]
@nfiedel - could you take a look?  Thanks!

**Comment by nfiedel** [comment]
Thanks for the ping. Community contributions are welcome.

@kirilg can provide guidance or may be able to get to this eventually...

**Comment by drpngx** [comment]
Marking as "contributions welcome" as per @nfiedel .

**Comment by gunan** [comment]
We do not maintain the conda-forge repository for tensorflow.
Therefore I will close this issue.
