### ISSUE TITLE
When installed by pip, dependencies' versions are not fixed.

### ISSUE THREAD

**Issue by luciencho** [tensorflow/tensorflow#45510]
**System information**
- OS Platform and Distribution: window & linux
- TensorFlow installed from: binary
- TensorFlow version: 1.13, 1.14
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
grpcio>=1.8.6 has been installed, which is always the newest one: eg. 1.34.0; however grpcio~=1.32.0 is expected

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow-gpu

**Comment by Saduf2019** [comment]
@luciencho 
Please verify your pip version if it is the latest.
There is no support for 1.x, please upgrade to 2.x and share the complete error log in case you face issues with 2.x.
you may refer to [pip install tensorflow gpu](https://github.com/tensorflow/tensorflow/issues/42367) similar issue.

**Comment by luciencho** [comment]
It is a tf 1.x problem.
After updating pip, the problem remains unsolved. I was just wondering why grpcio>=1.8.6 has been installed. [code](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh) does not make sense to me.

**Comment by Saduf2019** [comment]
@luciencho
There is no support for 1.x, please upgrade to 2.x and share the complete error log in case you face issues with 2.x.
