### ISSUE TITLE
save/load pair do not preserve `trainable` attribute

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#45537]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Debian testing
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a model with some layers set as `trainable=False`. However, after saving this model and loading it back, all parameters are trainable again. 

**Describe the expected behavior**
I would expect that save/load pair would reconstruct the model precisely in its original state. 

**Standalone code to reproduce the issue**

```python
m1 = Sequential([
    Input((100,)),
    Dense(20),
    Dense(10),
])

m1.trainable = False

m2 = Sequential([
    Input((100,)),
    m1,
    Dense(5),
    Dense(3)
])

m2.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
sequential_6 (Sequential)    (None, 10)                2230      
_________________________________________________________________
dense_13 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_14 (Dense)             (None, 3)                 18        
=================================================================
Total params: 2,303
Trainable params: 73
Non-trainable params: 2,230
_________________________________________________________________
```

Note that only 73 parameters are trainable (as expected).
Now let's save and load back the model:

```python
tf.keras.models.save_model(m2, "/tmp/mymodel")
m2_reloaded = tf.keras.models.load_model("/tmp/mymodel")
m2_reloaded.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
sequential_6 (Sequential)    (None, 10)                2230      
_________________________________________________________________
dense_13 (Dense)             (None, 5)                 55        
_________________________________________________________________
dense_14 (Dense)             (None, 3)                 18        
=================================================================
Total params: 2,303
Trainable params: 2,303
Non-trainable params: 0
_________________________________________________________________
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by eli-osherovich** [comment]
tf-nightly behaves in the same way

**Comment by amahendrakar** [comment]
@eli-osherovich,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/37531#issuecomment-600439680) from similar issue #37531 and let us know if it helps. Thanks!

**Comment by eli-osherovich** [comment]
Thanks @amahendrakar, It seems that the ticket is indeed related to this problem, however, I do not see how that particular comment is relevant. If I understand correctly the comment, It suggests to compile the model after setting `trainable=False`. This is probably necessary to use the model properly. However, it has nothing to do with the fact that reloaded model has all its parameters set to trainable.

**Comment by eli-osherovich** [comment]
@amahendrakar , I have to correct myself, the issue you reference above (#37531) is completely unrelated to this bug. That thread is about the need to compile models after one changes `trainable` flag.

**Comment by eli-osherovich** [comment]
Any update on this issue?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/8e1acab2e9e11b0bd03e05d0cc58bb9e/45537-2-3.ipynb), [TF v2.4](https://colab.research.google.com/gist/amahendrakar/170ece581b87cd904bef0385579ff8bf/45537-2-4.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/4d70cdf1c47c618f7510ca5292300a1f/45537-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by rmothukuru** [comment]
@eli-osherovich,
The behavior that you are expecting can be achieved by Saving the Model in **`H5 format`**, instead of **`Tensorflow Saved Model Format`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/7aa9d3f874072c9995c0e5086b26539c/45537-2-4.ipynb) of working code. 

Thanks!

**Comment by eli-osherovich** [comment]
Thanks, @rmothukuru , saving in HDF5 files has its own limitations, as you surely know.

**Comment by eli-osherovich** [comment]
Any update on this one?

**Comment by jvishnuvardhan** [comment]
@eli-osherovich I think this was resolved in recent `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/6a2199d444d13e52f985cd3d9b67addf/45537-tf-nightly.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by eli-osherovich** [comment]
Fixed indeed.
Thanks!
