### ISSUE TITLE
I got a problem when I ran the flower demo of slim

### ISSUE THREAD

**Issue by geekvc** [tensorflow/tensorflow#4553]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Ubuntu 14.04
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
Cuda 7.5   cuDNN 5.0
If installed from binary pip package, provide:
No, we installed tensorflow with the source code
1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
754048a0453a04a761e112ae5d99c149eb9910dd
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
We ran the flower demo alone, everything is ok, however, with the slim I got the error like this:
![image](https://cloud.githubusercontent.com/assets/10766005/18788663/5d1d63ce-81da-11e6-91fa-0a34ae52e130.png)
 I think something wrong with this file /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/image_ops.py

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
think you!

**Comment by jmchen-g** [comment]
Please include more details and this is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
