### ISSUE TITLE
Bug in tensorflow.python.ops.parallel_for.gradients.batch_jacobian()

### ISSUE THREAD

**Issue by stengoes** [tensorflow/tensorflow#45539]
There is a bug on `line 113` of the `batch_jacobian` function:
https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/python/ops/parallel_for/gradients.py#L83-L113

## Explaining the bug
On `line 113` the `output_shape[0]` is not an instance of the class `tf.TensorShape()`.
It is either an `integer` or `None` and therefore has no `is_compatible_with()` method.

## Suggesting a fix
```python 
if not output_shape[0].is_compatible_with(inp.shape[0])
``` 
could be replaced with 
```python
if not output_shape[0:1].is_compatible_with(inp.shape[0])
```
because `output_shape[0:1]` is an instance of `tf.TensorShape()`

## Minimal Example - showing the bug and testing the fix

The example below has been evaluated in a docker container running the image: `tensorflow/tensorflow:2.3.0-gpu-jupyter`

```python
import tensorflow as tf
from tensorflow.python.ops.parallel_for.gradients import batch_jacobian

# Define function that computes f(x) = x^2 and its derivative df/dx = 2*x
@tf.function
def square(x):    
    y = x**2
    dydx = batch_jacobian(y, x)
    return y, dydx

# Create a model that uses the function
x = tf.keras.backend.placeholder(shape=(None, 2), dtype=tf.float32)
y, dydx = tf.keras.layers.Lambda(lambda c: square(c))(x)
model = tf.keras.Model(x, [y, dydx])

# Test case: evaluate model with dummy input
x_input = tf.constant([[1., 2.], [3., 4.], [5., 6.]])
y_output, dydx_output = model(x_input)
print(y_output)
print(dydx_output)
```

Results in the following error:
```
AttributeError: in user code:

    <ipython-input-1-5f56962453df>:8 square  *
        dydx = batch_jacobian(y, x)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/gradients.py:113 batch_jacobian  **
        if not output_shape[0].is_compatible_with(inp.shape[0]):

    AttributeError: 'NoneType' object has no attribute 'is_compatible_with'
```

After the suggested fix it outputs:
```
tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[ 2.  0.]
  [ 0.  4.]]

 [[ 6.  0.]
  [ 0.  8.]]

 [[10.  0.]
  [ 0. 12.]]], shape=(3, 2, 2), dtype=float32)
```

## Colab demonstrating the minimal example (mentioned above)
https://colab.research.google.com/drive/1UNCyHc6d7mrZv7p7VD3GekI3YqAntQ9q?usp=sharing

## Next steps
If you want I can make a pull request. But I first want to know whether this an intended way of using the batch_jacobian function.

**Comment by allenlavoie** [comment]
My guess is that this worked with 1.x TensorShape, but in 2.x slicing a shape returns a literal value instead of a Dimension object. So one simple fix would be to use `tensor.shape.dims[index]` instead of `tensor.shape[index]`. A PR for that sounds fine, and it'd be good to have a unit test if so.

This function isn't part of the public API. Could you switch to [`GradientTape.batch_jacobian`](https://www.tensorflow.org/api_docs/python/tf/GradientTape#batch_jacobian)? They should be equivalent, but the public one supports eager execution and will be better tested (I doubt it has this problem).

**Comment by saddamhijazi** [comment]
The problem is still there, I got this error 

AttributeError: 'int' object has no attribute 'is_compatible_with'
