### ISSUE TITLE
Windows Tensorflow load large than 4GB file will meet outOfRange error.

### ISSUE THREAD

**Issue by CathyCan0329** [tensorflow/tensorflow#45543]
**System information**
-OS Platform and Distribution: Windows
-TensorFlow installed from: binary
-TensorFlow version: 1.0.1, 1.15
-Python version: 3.6

**Describe the current behavior**
Tensorflow load large than 4GB file on Windows will meet **outOfRange** error.

**Other info / logs** 
Tensorflow Windows version's file stat function by default use **_wstat** which represents the file size as 32-bit integer, once load large than 4GB file on Windows will meet **outOfRange** error. So I change the default to use **_wstat64** which represents the file size as 64-bit integer to fix the issue.

Attach [PR](https://github.com/tensorflow/tensorflow/pull/45542) here.

**Comment by mihaimaruseac** [comment]
Does this manifest on master?

**Comment by CathyCan0329** [comment]
The bug can be reproduced on TF 1.15 and I've tested the fix it worked. The related code has not changed for 3 years, so the master branch should have the same issue.

**Comment by Saduf2019** [comment]
@CathyCan0329 

Can you please share a simple stand alone code with all dependencies, or if possible share a colab gist with the issue reported.

**Comment by mihaimaruseac** [comment]
This is fixed now, as the PR landed
