### ISSUE TITLE
Official Example For TensorFlow Lite Model Maker keeps crashing

### ISSUE THREAD

**Issue by ando0689** [tensorflow/tensorflow#45541]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
 **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**Mac Book Pro 2017(2.3 GHz Dual-Core Intel Core i5, 8 GB 2133 MHz LPDDR3), MacOS Big Sur 11.0.1,
Browser: Version 87.0.4280.88 (Official Build) (x86_64),
but I guess the above info does not matter as I run the example in Google Colab [here](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
**No**
- TensorFlow installed from (source or binary):
**TensorFlow is provided by Google Colab environment**
- TensorFlow version (use command below):
**2.4.0-dev20200902**
- Python version:
Python 3.6.9
- Bazel version (if compiling from source):
**N/A**
- GCC/Compiler version (if compiling from source):
**N/A**
- CUDA/cuDNN version:
**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243**
- GPU model and memory:
**I cannot check this as I run the Colab provided in official Tensorflow page on the provided Google Colab Environment, which you can see in the following url: https://www.tensorflow.org/lite/tutorials/model_maker_question_answer**

**Describe the current behavior**
When I try to run the officially provided Colab from TensorFlow Lite Model Maker Library for BERT Q&A
not changing anything, everything goes fine until the training model = `question_answer.create(train_data, model_spec=spec)`
As soon as training process started, after a while it begins to consume memory with big chunks (e.g. memory consumption increases by 2GB per 2-3 seconds) and shortly it crashes the **Colab** telling "Your session crashed after using all available RAM". I think this is some sort of a bug, because otherwise this will not be an official example, or it would be documented somewhere in the example that the free Colab environment provided by Google with 16GB RAM is not enough to run this example.
I also tried to run the example with much smaller dataset, but the same problem in the same way is being reproduced. So I am almost sure that this is a bug in the library.

**Describe the expected behavior**
The example project provided in Official website of TensorFlow should run without any problem on the officially provided Colab Environment.

**Standalone code to reproduce the issue**
Please just go node by node through the official example [in the following Colab](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer) with a basic free Colab plan, without changing anything in the example.
when you reach "Customize the TensorFlow Model" point, and run the following code `model = question_answer.create(train_data, model_spec=spec)` wait for 2-3 minutes, and you will get and error that Colab environment was crashed telling "Your session crashed after using all available RAM".

**Other info / logs** 
There is the logs that I get after running `!cat /var/log/colab-jupyter.log` in Colab just after the crash
https://gist.github.com/ando0689/c67406e124ce8180935f36fe5e95e835

**Comment by ymodak** [comment]
The colab crashes on trying with a different model_spec as well.
```python
spec = model_spec.get('bert_qa')
```

**Comment by ymodak** [comment]
@ando0689 Can you please try with model maker nightly package?
`python
!pip install tflite-model-maker-nightly
`
The colab does not crash with the nightly package. Thanks!

**Comment by ando0689** [comment]
Hi. Thank you very much.

This specific problem is resolved on nightly build, but overall the example is not working, I will post the issues here and if needed I will open a separate issue for this.

here are the issues:

1. When I do `!pip install tflite-model-maker-nightly` I see the following error in the log:
```ERROR: tensorflow 2.3.0 has requirement h5py<2.11.0,>=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tf-nightly 2.5.0.dev20201215 has requirement numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.
```
Though this does not stop the execution and I can continue.

2. When i try to use the created model with TensorFlow Lite Android v 2.3.0 I get the following error when I try to create interpreter with this model:
https://gist.github.com/ando0689/1874b6881dc7af3a31519e1bb2813386

3. And when I increase the version of TensorFlow Lite on Android to `0.0.0-nightly` I get the following error when I try to do inference:
https://gist.github.com/ando0689/b25f00443249da833af08cb8a6235a95

4. Just a note: The provided dataset with 8000 entities seems to be too much for this example, as running on the free Colab, it takes about 6 hours, and usually fails with some error.. I was only able to train it by reducing the dataset to be 1000 entities, I guess it's enough for example.

Thank you in advance,
Please tell me if I need to create separate issue for this.

**Comment by ymodak** [comment]
Thanks for your issue. Lets continue the discussion on your new thread. I will close this one.
