### ISSUE TITLE
TensorFlow Binary Segmentation

### ISSUE THREAD

**Issue by JulienBelanger** [tensorflow/tensorflow#4554]
I've written the following [segmentor](https://docs.google.com/document/d/1Mnfrcu5AU47rRoPwweQv8kRGzTPJaXwJf7zd3pksXK4/edit?usp=sharing) and I can't get the accuracy to work. In fact I'm always getting accuracy of 0.0 whatever the size of my sample.

I think the problem is at the sigmoid layer at the end of U() function where a tensor of continuous elements between 0 and 1 (conv10) is further compared to a binary tensor and therefore there's no chance of getting any equality between the two.

**Comment by concretevitamin** [comment]
Since this issue is not a bug or feature request, please ask this type of question on stackoverflow with the tag #tensorflow. Thank you.
