### ISSUE TITLE
using GraphDef in C API?

### ISSUE THREAD

**Issue by jmhodges** [tensorflow/tensorflow#4557]
I'm looking over the C API to turn a GraphDef into a TF_Graph for use with TF_NewSessionWithGraph, but I can't figure out how that's supposed to be done.

It kind of seems like you can't unless you use the deprecated TF_ExtendGraph API? But that's deprecated, so I'm not sure what to do.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h#L754 :)

It's currently being worked on though :)

**Comment by mrry** [comment]
The `TF_ImportGraphDef()` implementation is part of pending PR #4555, so should be available very soon: https://github.com/tensorflow/tensorflow/pull/4555/commits/22221698a3ecd43024f84cd6c468ddd00955f920 (commit)

**Comment by jmhodges** [comment]
Ah! I missed that! Thanks for the info.
