### ISSUE TITLE
Tutorials still mention boosted_trees_classifier_train_in_memory

### ISSUE THREAD

**Issue by gqqnbig** [tensorflow/tensorflow#45577]
## URL(s) with the issue:

https://github.com/tensorflow/docs/blob/master/site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb

## Description of issue (what needs changing):

The tutorials says 

> For performance reasons, when your data fits in memory, we recommend use the boosted_trees_classifier_train_in_memory function. 

However, function `boosted_trees_classifier_train_in_memory` doesn't exist. It's actually removed in ffc25308ce2be84240ec90502b38800bc5a4dd60.

### Submit a pull request?

I'm not sure whether it's fine to simply remove the sentense. You guys may want to add something else.

**Comment by bhack** [comment]
@gqqnbig I think that there is a new arg `train_in_memory`at  https://www.tensorflow.org/api_docs/python/tf/estimator/BoostedTreesClassifier.
Can you send a small PR to refactor that sentence?

**Comment by ymodak** [comment]
Closing this issue since the associated PR has merged and fixes it. Thanks!
