### ISSUE TITLE
failed to compile tensorflow (V2.4_RC4) in debug mode

### ISSUE THREAD

**Issue by NEWPLAN** [tensorflow/tensorflow#45570]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 4.19.117.bsk.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4_rc4
- Python version:Python 3.7.3
- Installed using virtualenv? pip? conda?: build from source 
- Bazel version (if compiling from source):bazel 3.1.0
- GCC/Compiler version (if compiling from source):gcc (Debian 8.3.0-6) 8.3.0
- CUDA/cuDNN version: Cuda compilation tools, release 11.1, V11.1.105
- GPU model and memory: V100(32G), host memory>120GB

**Describe the problem**
I want to compile Tensorflow from source code, using the debug model, when I pass args to the bazel, it ends up with failure as below:
ERROR: /home/chengyang/src/tf-src/tensorflow_2.4_rc4/tensorflow/BUILD:724:1: Linking of rule '//tensorflow:libtensorflow_framework.so.2.4.0' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/chengyang/.cache/bazel/_bazel_zhoudongyan.daniel/b440c4e0619e08e4030082228cc9dfe0/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-8 \
    LD_LIBRARY_PATH=/opt/XXX/jdk/jre/lib/amd64/server:/opt/XXX/lib/native:/opt/XXX/lib/native/ufs:/opt/XXX/lib/native:/opt/XXX/lib/native:/opt/XXX/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64: \
    PATH=/home/chengyang/.cache/bazelisk/downloads/bazelbuild/bazel-3.1.0-linux-x86_64/bin:/home/chengyang/software/bazelisk:/usr/local/cuda/bin:/home/chengyang/system_op/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tige
r/arnold/arnold_entrypoint/tools:/opt/XXX/bin:/opt/XXX/bin:/home/chengyang/.local/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow_framework.so.2.4.0-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld: bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/libcublas_plugin.pic.lo(cuda_blas.pic.o): relocation R_X86_64_PC32 against undefined symbol `_ZN15stream_executor3gpu12_GLOBAL__N_120CUDABlasLtMatmulPlan14kMaxBatchCountE' can n
ot be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
Target //tensorflow/compiler/xla/tools:run_hlo_module failed to build
INFO: Elapsed time: 111.012s, Critical Path: 93.19s
INFO: 2174 processes: 2174 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 ```bazel build //tensorflow/compiler/xla/tools:run_hlo_module  --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=cuda --compilation_mode=dbg --strip=never --copt="-g" --cxxopt="-g" --copt="-O0" --cxxopt="-O0"  --verbose_failures```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I have successfully compiled the source code with ```--compilation_mode=opt --strip=never --copt="-g" --cxxopt="-g"  --verbose_failures```,  however, it turns out to be that "-O2" is enabled, and I hope to pass "-O0" to track the execution with GDB.

**Comment by Saduf2019** [comment]
@NEWPLAN 
Can you please try with CUDA 11.0? TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.

**Comment by NEWPLAN** [comment]
> @NEWPLAN
> Can you please try with CUDA 11.0? TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.

Thanks for your reply, I would follow your suggestion to recompile it. Additionally, what are the expected arguments passing to the bazel?  That's how can I disable the "-O2" flag in debug mode?

**Comment by bhack** [comment]
@NEWPLAN  Have you tried with the `dbg` conf? See https://github.com/tensorflow/tensorflow/issues/27744

**Comment by NEWPLAN** [comment]
> @NEWPLAN Have you tried with the `dbg` conf? See #27744

did not try all the approaches mentioned in the link, but compiling the src codes with ```dbg``` has been practiced. Still, got the same errors as above.

**Comment by bhack** [comment]
As `--compilation_mode=opt --strip=never` Is already working for you have you tried the same with `dbg` instead of `opt`?

**Comment by NEWPLAN** [comment]
> As `--compilation_mode=opt --strip=never` Is already working for you have you tried the same with `dbg` instead of `opt`?

sure, when repalcing the ```opt``` with ```dbg```, the compiling is failed (as above), however, using the opt means the src code would be optimized by the compiler such as ```-O2```, which is conflicted with debugging the code step by step.

**Comment by bhack** [comment]
Ok Just to be sure about the reproducibilty can you try in the devel image (you have already the source there) https://www.tensorflow.org/install/docker?hl=en?

**Comment by NEWPLAN** [comment]
> Ok Just to be sure about the reproducibilty can you try in the devel image (you have already the source there) https://www.tensorflow.org/install/docker?hl=en?

sure, thanks for your help, I would like to try it soon.

**Comment by NEWPLAN** [comment]
Hi, I have tried the new command to compile the tensorflow in debug mode, the compile cmd is
" bazel build //tensorflow/tools/pip_package:build_pip_package  --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=cuda --compilation_mode=dbg --strip=never --copt="-fPIC" --cxxopt="-fPIC"  --copt="-O0" --cxxopt="-O0" --dynamic_mode=off --verbose_failures --linkopt=-L/usr/local/cuda/lib64 --linkopt=-lcudart" 

the log is shown as follows.
"tf-src/tensorflow_2.4_rc4/tensorflow/BUILD:724:1: Linking of rule '//tensorflow:libtensorflow_framework.so.2.4.0' failed (Exit 1): crosstool_wrapper_driver_is_no
t_gcc failed: error executing command
  (cd /home/tiger/.cache/bazel/_bazel_zhoudongyan.daniel/b440c4e0619e08e4030082228cc9dfe0/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-8 \
    LD_LIBRARY_PATH=/opt/tiger/yarn_deploy/jdk/jre/lib/amd64/server:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native/ufs:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lzo/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64: \
    PATH=/home/tiger/.cache/bazelisk/downloads/bazelbuild/bazel-3.1.0-linux-x86_64/bin:/home/tiger/chengyang/software/bazelisk:/usr/local/cuda/bin:/home/tiger/system_op/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tiger/arnold/arnold_entrypoint/tools:/opt/tiger/yarn_deploy/hadoop/bin:/opt/tiger/yarn_deploy/hive/bin:/home/tiger/.local/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-dbg/bin/tensorflow/libtensorflow_framework.so.2.4.0-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld: bazel-out/k8-dbg/bin/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.pic.o): relocation R_X86_64_PC32 against undefined symbol `_ZN15stream_executor3gpu12_GLOBAL__N_12
0CUDABlasLtMatmulPlan14kMaxBatchCountE' can not be used when making a shared object; recompile with -fPIC"

**Comment by NEWPLAN** [comment]
> Hi, I have tried the new command to compile the tensorflow in debug mode, the compile cmd is
> " bazel build //tensorflow/tools/pip_package:build_pip_package --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=cuda --compilation_mode=dbg --strip=never --copt="-fPIC" --cxxopt="-fPIC" --copt="-O0" --cxxopt="-O0" --dynamic_mode=off --verbose_failures --linkopt=-L/usr/local/cuda/lib64 --linkopt=-lcudart"
> 
> the log is shown as follows.
> "tf-src/tensorflow_2.4_rc4/tensorflow/BUILD:724:1: Linking of rule '//tensorflow:libtensorflow_framework.so.2.4.0' failed (Exit 1): crosstool_wrapper_driver_is_no
> t_gcc failed: error executing command
> (cd /home/tiger/.cache/bazel/_bazel_zhoudongyan.daniel/b440c4e0619e08e4030082228cc9dfe0/execroot/org_tensorflow &&
> exec env -
> CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1
> GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-8
> LD_LIBRARY_PATH=/opt/tiger/yarn_deploy/jdk/jre/lib/amd64/server:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native/ufs:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lzo/lib:/usr/local/cuda/compat:/usr/local/cuda/lib64:
> PATH=/home/tiger/.cache/bazelisk/downloads/bazelbuild/bazel-3.1.0-linux-x86_64/bin:/home/tiger/chengyang/software/bazelisk:/usr/local/cuda/bin:/home/tiger/system_op/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/tiger/arnold/arnold_entrypoint/tools:/opt/tiger/yarn_deploy/hadoop/bin:/opt/tiger/yarn_deploy/hive/bin:/home/tiger/.local/bin
> PWD=/proc/self/cwd
> PYTHON_BIN_PATH=/usr/bin/python3
> PYTHON_LIB_PATH=/usr/lib/python3/dist-packages
> TF2_BEHAVIOR=1
> TF_CONFIGURE_IOS=0
> TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0
> TF_NEED_CUDA=1
> external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-dbg/bin/tensorflow/libtensorflow_framework.so.2.4.0-2.params)
> Execution platform: @local_execution_config_platform//:platform
> /usr/bin/ld: bazel-out/k8-dbg/bin/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.pic.o): relocation R_X86_64_PC32 against undefined symbol `_ZN15stream_executor3gpu12_GLOBAL__N_12
> 0CUDABlasLtMatmulPlan14kMaxBatchCountE' can not be used when making a shared object; recompile with -fPIC"

Thanks for all of the help I have received. I just find a practical solution to my problem, i.e., compile the tensorflow with "--per_file_copt". I would like to share with the community and hope it works  as expected.
```
bazel build //tensorflow/compiler/xla/python:xla_client --per_file_copt="//tensorflow/compiler/.*\.cc,-//tensorflow/stream_executor/.*\.cc@-g,-O0"  --per_file_copt="//tensorflow/stream_executor/.*\.cc@-g,-O1" --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=cuda --compilation_mode=dbg --strip=never -c opt --copt="-m64" --cxxopt="-m64" --copt="-mcmodel=large" --cxxopt="-mcmodel=large" --config=avx2_linux --config=xla --verbose_failures
```
