### ISSUE TITLE
Autograph warning seems to lead to reduced performance

### ISSUE THREAD

**Issue by moonj94** [tensorflow/tensorflow#45584]
**System information**
- I am using a toolbox called EEGNet and using my own script
- OS Platform and distribution: macOS catalina version 10.15.7 (19H2)
- TensorFlow installed from (source or binary) - i don't know how to check this
- Tensorflow version 2.3.1
- Python version: 3.7.4

- GPU model and memory: Radeon Pro 560X 4GB Intel UHD graphics 630 1536MB, and memory = 16GB 2400MHz DDR4

**Describe the current behavior**
I am getting the warning:
`WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd0e8162b90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd0e8162b90> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause:`

I get this warning somewhat sporadically. When I reopen Spyder the issue is gone until the second iteration in which I need to call it. I am also noticing that the performance as seen through validation accuracy is very much lower when this warning appears.

I checked other posts and it looked like changing gast==0.2.2 fixed it. But not for me.

**Describe the expected behavior**
Ideally the warning shouldn't appear, as it does the very first time around when I reopen Spyder. And the validation accuracy should be higher

**Standalone code to reproduce the issue**
N/A
I am using a module/toolbox called EEGNet.  https://github.com/vlawhern/arl-eegmodels
but this seems to be the line that causes the warning:
`fittedModel = model.fit(X_train, Y_train, batch_size = 64, epochs = 300, 
                                    verbose = 2, validation_data=(X_validate, Y_validate),
                                    callbacks=[checkpointer], class_weight = class_weights)`

**Other info / logs**

This is when I set autograph to verbose, 3
`INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076e1bb90>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076e1bb90>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076e1bb90>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076e1bb90>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0a290>
    args: (<tf.Tensor 'args_0:0' shape=(150,) dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0a290>
    args: (<tf.Tensor 'args_0:0' shape=(150,) dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0a290>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0a290>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd076f0a680>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(150, 64, 128, 1) dtype=float64>, <tf.Tensor 'args_2:0' shape=(150, 3) dtype=float32>, <tf.Tensor 'args_3:0' shape=(150,) dtype=int64>))
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd076f0a680>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(150, 64, 128, 1) dtype=float64>, <tf.Tensor 'args_2:0' shape=(150, 3) dtype=float32>, <tf.Tensor 'args_3:0' shape=(150,) dtype=int64>))
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd076f0a680>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd076f0a680>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076f0a7a0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076f0a7a0>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076f0a7a0>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x7fd076f0a7a0>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0ab90>
    args: (<tf.Tensor 'args_0:0' shape=(75,) dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0ab90>
    args: (<tf.Tensor 'args_0:0' shape=(75,) dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0ab90>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fd076f0ab90>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd0778ff170>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(75, 64, 128, 1) dtype=float64>, <tf.Tensor 'args_2:0' shape=(75, 3) dtype=float32>, <tf.Tensor 'args_3:0' shape=(75,) dtype=int64>))
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd0778ff170>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, (<tf.Tensor 'args_1:0' shape=(75, 64, 128, 1) dtype=float64>, <tf.Tensor 'args_2:0' shape=(75, 3) dtype=float32>, <tf.Tensor 'args_3:0' shape=(75,) dtype=int64>))
    kwargs: {}

INFO:tensorflow:Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd0778ff170>: DoNotConvert rule for tensorflow
Whitelisted: <function TensorLikeDataAdapter.__init__.<locals>.grab_batch at 0x7fd0778ff170>: DoNotConvert rule for tensorflow
Train on 150 samples, validate on 75 samples
Epoch 1/300
INFO:tensorflow:Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00>
    args: ()
    kwargs: {}

Converted call: <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00>
    args: ()
    kwargs: {}

INFO:tensorflow:Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00> key <code object initialize_variables at 0x7fd17c1c40c0, file "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7fd077f74d90>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmpaqdi9bka)
Cache hit for entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00> key <code object initialize_variables at 0x7fd17c1c40c0, file "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 603> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x7fd077f74d90>, frozenset({'initializer_map'})): _ConvertedEntityFactoryInfo(tf__initialize_variables in tmpaqdi9bka)
INFO:tensorflow:Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00>
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
WARNING: Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x7fd077965b00> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py", line 506, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 324, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError`

Can you help me troubleshoot this?

**Comment by ravikyram** [comment]
@moonj94 

Can you please provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by moonj94** [comment]
I don't have a colab link but here is my code snippet:
`F1,D,F2,KL=8,2,16,9`
`model = EEGNet(nb_classes = 3, Chans = chans, Samples = samples, 
                        dropoutRate = 0.5, kernLength = KL, F1 = F1, D = D, F2 = F2, 
                        dropoutType = 'Dropout')`
`checkpointpath = '/tmp/checkpoint.h5`
`checkpointer = ModelCheckpoint(filepath=checkpointpath, verbose=1,
                                        save_best_only=True)
            
            ###############################################################################
            # if the classification task was imbalanced (significantly more trials in one
            # class versus the others) you can assign a weight to each class during 
            # optimization to balance it out. This data is approximately balanced so we 
            # don't need to do this, but is shown here for illustration/completeness. 
            ###############################################################################
            
            # the syntax is {class_1:weight_1, class_2:weight_2,...}. Here just setting
            # the weights all to be 1
            class_weights = {1:1, 2:1, 0:1}#, 3:1}
            
            ################################################################################
            # fit the model. Due to very small sample sizes this can get
            # pretty noisy run-to-run, but most runs should be comparable to xDAWN + 
            # Riemannian geometry classification (below)
            ################################################################################
#            tf.autograph.set_verbosity(3,True)
            fittedModel = model.fit(X_train, Y_train, batch_size = 64, epochs = 200, 
                                    verbose = 2, validation_data=(X_validate, Y_validate),
                                    callbacks=[checkpointer], class_weight = class_weights)
            
        #     load optimal weights
            model.load_weights(checkpointpath)`

You're going to need to download EEGnet: https://github.com/vlawhern/arl-eegmodels

And I'm afraid I can't share my data due to my workplace policy. But you can probably set X to a random array of 300 x 64 x 128.

**Comment by nikitamaia** [comment]
Hi @moonj94 you said that you see the warnings when you do control+c. What happens if you don't stop the code? Does it run?

Additionally, please provide your code with the proper indentation and as close to reproducible as possible. This helps us to troubleshoot and debug quicker. Thanks.

**Comment by moonj94** [comment]
Yeah so it runs properly if I don't do control+c.

**Comment by nikitamaia** [comment]
So to summarize, you do not see this warning every time you run the code? It only occurs sometimes. And when you don't see the warning, the code runs properly. Is that correct?

Additionally, please provide your code with the proper indentation and as close to reproducible as possible.
