### ISSUE TITLE
Cannot load saved model when using multiple tf.keras.layers.experimental.preprocessing.StringLookup layers

### ISSUE THREAD

**Issue by dlebech** [tensorflow/tensorflow#45580]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 and Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.5 (Ubuntu) and 3.6.9 (Colab)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

`v2.3.0-54-gfcc4b966f1 2.3.1`

**Describe the current behavior**

I am unable to load a saved model that has multiple `tf.keras.layers.experimental.preprocessing.StringLookup` layers.

When I load the model, I get the following error:
```
ValueError: The same saveable will be restored with two names: layer_with_weights-1/_table/.ATTRIBUTES/table
```

**Describe the expected behavior**

I expect to be able to load the model.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1BrlOjxYVyVM3lEJRmeK9lNvev8Z4MVwT?usp=sharing

The notebook does the following:
1. Create a model with two `tf.keras.layers.experimental.preprocessing.StringLookup` layers.
2. Save the model with `tf.saved_model.save` in the same Keras model
3. Reload the model with `tf.saved_model.load`
4. `ValueError` is thrown

**Other info / logs** Include any logs or source code that would be helpful to

- It works when using a single `StringLookup` layer.
- I have observed the same problem with `tf.keras.layers.experimental.preprocessing.TextVectorization`.

Full error stacktrace (from Colab): [error.txt](https://github.com/tensorflow/tensorflow/files/5674123/error.txt)

**Comment by huberemanuel** [comment]
I tried your code with the latest `tf-nightly`, and it works perfectly. I also tried with `tensorflow==2.4.0rc4` and also works. I would suggest upgrading your TensorFlow version.

**Comment by dlebech** [comment]
@huberemanuel thanks for the quick response! This is great news, and I am a bit embarrassed that I did not try the release candidate before posting. I will close the issue and upgrade to the bleeding edge :+1: Thank you for your time.

(I have verified now that it worked for my use case in 2.4.0 RC4)
