### ISSUE TITLE
Tensorflow float32 conversion bug from python to tensorflow constants

### ISSUE THREAD

**Issue by JohanMeppelinkDRA** [tensorflow/tensorflow#45596]
Tensorflow changes values well within tf.float32 range to nearby values.

Is this expected behaviour? Numpy doesn't have this issue and given the values are within float32 range I'm not sure why this is happening.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10, same issue on linux though**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **No**
- TensorFlow version (use command below): **version 2.1.0**
- Python version: 3.6.8
- Bazel version (if compiling from source): **Not build from source**
- GCC/Compiler version (if compiling from source): **Not build from source**
- CUDA/cuDNN version:  **running on cpu**
- GPU model and memory:  ****

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**
For example
`tf.constant(20200131, dtype=tf.float32)`
Becomes <tf.Tensor: shape=(), dtype=float32, numpy=20200132.0>

Why the extra 1?**

Expected behaviour:
**
`tf.constant(20200131, dtype=tf.float32)`
Becomes <tf.Tensor: shape=(), dtype=float32, numpy=20200131.0>
**

**Standalone code to reproduce the issue**
import tensorflow as tf
tf.constant(20200131, dtype=tf.float32)

**Comment by aaronmondal** [comment]
In fact, `numpy` **does** have the same behaviour:
```python
>>> import numpy as np
>>> np.full([], 20200131, dtype=np.float32)
array(20200132., dtype=float32)
```
It's just that `numpy` defaults to `float64`, which is why you do not notice it when invoking without specifying `dtype`:
```python
>>> a = np.full([], 20200131)
a = np.full([], 20200131)
>>> a
array(20200131)
>>> a.dtype
dtype('int64')
```
Float32 rounds to even numbers for large values. See also this interesting [Wikipedia page](https://en.wikipedia.org/wiki/Single-precision_floating-point_format):
> Integers between 224=16777216 and 225=33554432 round to a multiple of 2 (even number)
