### ISSUE TITLE
keras load_model Could not find matching function when compute_mask is used

### ISSUE THREAD

**Issue by pedro-r-marques** [tensorflow/tensorflow#45602]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
https://colab.research.google.com/drive/1Q9kiMw5k1uVtCpIbOEhui3h83_8IfN3t?usp=sharing

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
colab

- TensorFlow installed from (source or binary):
tf-nightly

- TensorFlow version (use command below):
- Python version:

**Describe the current behavior**
ValueError exception is raised when attempting to load a saved model that uses a ```compute_mask``` method.

In this example https://colab.research.google.com/drive/1Q9kiMw5k1uVtCpIbOEhui3h83_8IfN3t?usp=sharing
a custom layer copied from the documentation is added to a Sequential model. The model is compiled and saved. The function ```keras.models.load_model``` raises and exception when attempting to reconstruct the model.

It seems probable that the model is not taking computed masks into account when attempting to reconstruct the graph. The error message leads me to believe that it is unaware that a mask producer can pass a mask to a mask consumer.

**Describe the expected behavior**
Canonical examples described in the documentation should be able to be saved and loaded.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1Q9kiMw5k1uVtCpIbOEhui3h83_8IfN3t?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * Tensor("inputs:0", shape=(None, 16, 8), dtype=float32)
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 16, 8), dtype=tf.float32, name='inputs')
    * TensorSpec(shape=(None, 16), dtype=tf.bool, name='mask')
  Keyword arguments: {}
```

**Workaround:**
If the model is saved with the ```save_traces``` flag set to False  it can be successfully saved and loaded.
Example:
https://colab.research.google.com/drive/1WRPqSzu41waymZRr_9wqpojhVEi7EsCV?usp=sharing

**Comment by bhack** [comment]
You need to use custom object on load. Please see Docs at:
https://keras.io/api/utils/serialization_utils/

P.s. /cc @MarkDaoust I think this Is one of the edge cases where we could improve the error with a more user friendly message.

**Comment by pedro-r-marques** [comment]
@bhack I've confirmed that using custom_objects works. i.e. the "workaround" colab works even if save_traces is True.
