### ISSUE TITLE
Tensorflow_datsaet api fails to cache my training data.

### ISSUE THREAD

**Issue by Arman-IMRSV** [tensorflow/tensorflow#45609]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: V100 (16GB)

**Describe the current behavior**
Here is the error I get:
![Screenshot from 2020-12-11 16-39-07](https://user-images.githubusercontent.com/70702200/101952699-727d1080-3bcf-11eb-8aaf-cb55fe37bec4.png)

The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Standalone code to reproduce the issue**
I run a custom data loader:
```
start_time = time.clock()

data_loader = None

if translation_direction in [Translation_Direction.English_to_Farsi,Translation_Direction.Farsi_to_English]:
    data_loader = Data_loader_persian(translation_direction, fa_vocab_size=12000, en_vocab_size=24000)
    
else:
    raise Exception("Requested Translation Direction is not supported!")
    
train_examples, val_examples, test_examples, dataset_size_dict, tokenizer = data_loader.run()

end_time = time.clock()
print(f"Execution time: {end_time - start_time} seconds.")
```

Then I try to cache and prefetch the dataset:
```
train_dataset = train_examples.cache()
train_dataset = train_dataset.padded_batch(global_batch_size)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)
```

Then when I try to read the dataset:
```
for i,x in enumerate(train_examples):
    if i==5:
        break
```
Here is when the error comes up! No matter how many times I try to read, every times it reads from file (no caching happens!)

Note: Screenshot of the profiling window is attaches. As could be seen, the program is HIGHLY input-bound.
I would appreciate if you have any idea. Thanks :)

**Comment by aaronmondal** [comment]
It would be helpful if you could provide a standalone reproducible code example. Without being able to see custom components these things are hard to debug.

Also note that `cache` works at the **second** epoch of training. The data is read from disk (or cachefile, if specified), cached in your memory during the first epoch (provided your memory is large enough, otherwise the code will kill itself) and then read from memory from the second epoch onwards. This is at least the case for a "regular" dataset, where each datapoint is fed into the model once per epoch.

**Comment by Saduf2019** [comment]
@Arman-IMRSV 
I ran the code shared its incomplete , please share complete code or if possible share a  colab gist with the error reported.
