### ISSUE TITLE
TFLM: Adding ported and optimized operations for CEVA-BX1

### ISSUE THREAD

**Issue by yair-ehrenwald** [tensorflow/tensorflow#45607]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): nightly
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): CEVA-BX1

I will be adding optimized operations for the CEVA-BX1 platform (later on for other CEVA platforms as well).

Starting with fully connected but many others will follow: see PR: https://github.com/tensorflow/tensorflow/pull/45606

**Comment by pjpratik** [comment]
Hi @yair-ehrenwald 

 The optimized kernel for DEPTHWISE CONV for CEVA and Conv2D has been added with the commits https://github.com/tensorflow/tflite-micro/commit/58da40911848875428f3ac5b1e695cf58d535fe1 and https://github.com/tensorflow/tflite-micro/commit/380e5bdd46d686dff42338c4fb42f34dadbfee8b.

Thanks.
