### ISSUE TITLE
No documentation on how to access the ram:// filesystem of TPU's

### ISSUE THREAD

**Issue by Guthman** [tensorflow/tensorflow#45605]
According to this comment there is support to access the RAM filesystem of TPU's: https://github.com/tensorflow/tensorflow/issues/32651#issuecomment-534685146

However, the documentation seems to be lacking information on the subject (although it's a bit hard to search, as the search term 'ram' (special characters are stripped) returns a lot of irrelevant results.

Is the documentation indeed missing, or is the feature maybe not implemented yet?

**Comment by mihaimaruseac** [comment]
TF filesystems use a URI to refer to paths. The scheme of the URI specifies which filesystem to use. So

```
with open("ram://path/to/file") as f:
  print(f.read())
```

Will use `/path/to/file` from the RAM filesystem. Changing the path to be `s3://path/to/file` will use the S3 filesystem, etc.

**Comment by Guthman** [comment]
Thank you. And how would one move data to the ram filesystem (as opposed to reading)?

**Comment by mihaimaruseac** [comment]
All methods under [`tf.io.gfile`](https://www.tensorflow.org/api_docs/python/tf/io/gfile) can be used transparently across filesystems.

```
tf.io.gfile.copy("/tmp/local/file", "ram://ram_file")
```
