### ISSUE TITLE
The current TensorFlow lite version cannot be built with Visual Studio 2017.

### ISSUE THREAD

**Issue by OgreTransporter** [tensorflow/tensorflow#45629]
**System information**
- OS Platform and Distribution: Windows SDK version 10.0.17763.0 to target Windows 10.0.19042
- TensorFlow installed from (source): master, commit 67a9764695429fc5963aeeb905526bfe5af45739
- TensorFlow version: 2.4?
- CMake version: 3.18.5
- Compiler version: Visual Studio 2017 (MSVC 19.16.27045.0)
- CUDA/cuDNN version: 10.2, 11.1
- GPU model and memory: GeForce 1080 Ti

**Describe the problem**
The current TensorFlow lite version cannot be built with Visual Studio 2017.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
D:
mkdir TF
cd TF
git clone https://github.com/tensorflow/tensorflow.git src
mkdir build
cd build
cmake -G "Visual Studio 15" -A x64 -D CMAKE_DEBUG_POSTFIX:STRING=d -D CMAKE_INSTALL_PREFIX:PATH=D:\TF\install -D TFLITE_ENABLE_GPU:BOOL=OFF -D GIT:FILEPATH=D:\dev\Tools\GIT\bin\git.exe D:\TF\src\tensorflow\lite
msbuild INSTALL.vcxproj /maxcpucount /nodeReuse:false /nologo /p:Configuration=Debug
```

**Any other info / logs (translated from german)**
```
       "D:\TF\build\INSTALL.vcxproj" (default target) (1) ->.
       "D:\TF\build_BUILD.vcxproj" (default target) (3) ->.
       "D:\TF\build\tensorflow-lite.vcxproj" (default target) (4) ->
       (ClCompile target) ->
         D:\TF\src\tensorflow-lite\kernels\elementwise.cc(299): fatal error C1001: Internal compiler error. [D:\TF\build\tensorflow-lite.vcxproj]
```

Project file built with Visual Studio:
```
42>D:\TF\src\tensorflow\lite\kernels\elementwise.cc(299): fatal error C1001: Internal compiler error.
42>(Compiler file "msc1.cpp", line 1518)
42> Simplify or modify the program in the environment of the items listed above. Select
42>Use the "Technical Support" command in the "Help" menu of Visual C++,
42>or open the technical support help file for more information.
42>INTERNAL COMPILER ERROR in "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe".
42> From the Visual C++ Help menu, click Technical Support,
42> or open Technical Support Help for more information.
```

**Comment by bhack** [comment]
Can you check our Visual Studio compatibility matrix for each TF version at https://www.tensorflow.org/install/source_windows#tested_build_configurations ?

Thanks

**Comment by OgreTransporter** [comment]
Hi bhack,

the list gives an overview of TensorFlow, not TensorFlow lite. For lite a C++11 compiler is supposedly sufficient as it can be found e.g. in the Micro documentation (https://www.tensorflow.org/lite/microcontrollers#supported_platforms). Also, there is a CMake build instruction https://www.tensorflow.org/lite/guide/build_cmake without any restrictions.
