### ISSUE TITLE
Potential GPU Memory Leak

### ISSUE THREAD

**Issue by IlleQuiProgrammat** [tensorflow/tensorflow#45627]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Colab (couldn't find distro from this)**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.1**
- Python version: **Python 3.8.5 (64-bit)**
- CUDA/cuDNN version: **10.1**
- GPU model and memory: **Nvidia Tesla T4 16GB**

**Describe the current behavior**

Half way through an epoch the network appears to run out of memory despite no new memory requirements i.e. nothing extra is being created that isn't deleted (I think). See ipynb below for a detailed error message. Furthermore, when checking the memory free after the program has finished executing (using `nvidia-smi`) it gives `14599MiB / 15079MiB` used and `No running processes found`.

**Describe the expected behavior**
The network should continue to train as normal.

**Standalone code to reproduce the issue**
https://gist.github.com/IlleQuiProgrammat/cd37e1b0767e0c859fef922387284898

*Note: the full error is shown at the bottom*

**Comment by Saduf2019** [comment]
@IlleQuiProgrammat 

I ran the code shared an face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f5856ebfa522d94eb93cb30b2ff52624/untitled485.ipynb).
Please share all dependencies for us to replicate the issue faced.

**Comment by IlleQuiProgrammat** [comment]
Apologies for not explaining more clearly, on my drive I have copied the celeb a img_align data set to `/MLProj/img_align_celeba.zip` from https://drive.google.com/file/d/0B7EVK8r0v71pZjFTYXZWM3FlRnM/view?usp=drivesdk

And the other error regarding the latest checkpoint can be solved by not running that cell - I haven't trained a model yet it is there for using it in the future for inference.

In addition, you don't appear to be running this on a gpu or colab has missed copying the `pip install tensorflow-gpu` command from my gist. Running this on cpu would be far too slow and I believe this issue is related to managing the gpu memory but I'm not sure.

**Comment by IlleQuiProgrammat** [comment]
@Saduf2019 mentioning you as, from the previous issues I've seen, tensorflow butler normally removes the awaiting response tag but this hasn't seemed to happen so making sure you've seen my response.

**Comment by Saduf2019** [comment]
@IlleQuiProgrammat
Apologies for the delayed response.
Can you please share a colab gist, i am unable to download from the link shared.

**Comment by IlleQuiProgrammat** [comment]
I'm not quite sure how you would like me to attach the dataset to the colab gist as it is very large. If there is a way I don't know, please tell me. 

If it is just an issue of the Google drive link not working, you can download the dataset from any of the links on this page: http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Thank you in advance.

**Comment by ymodak** [comment]
Since you are hitting OOM error I would recommend [limiting gpu memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and also try reducing your batch size to a smaller value.
```python
# On top of your script 
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
# Rest of your code
...

**Comment by IlleQuiProgrammat** [comment]
Apologies, I missed your response, I shall try that now and update you to the results.

**Comment by IlleQuiProgrammat** [comment]
Thank you, this seems to be working @ymodak - is there a reason why this is not enabled by default?

**Comment by ymodak** [comment]
Glad it worked. As per the [Limiting GPU memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) docs,
> By default, TensorFlow maps nearly all of the GPU memory of all GPUs  visible to the process. This is done to more efficiently use the relatively precious GPU memory resources on the devices by reducing memory fragmentation.
