### ISSUE TITLE
tf.test.gpu_device_name() breaks tensorflow

### ISSUE THREAD

**Issue by taDachs** [tensorflow/tensorflow#45622]
**System information**
- I am working on a vae in tensorflow using probability layers
- Ubuntu 20.04
- tensorflow 2.5 compiled from source
- Python version: 3.8.5
- CUDA 11.1
- RTX 2070 Super with 8gb of ram

I want to reproduce this [example](https://www.tensorflow.org/probability/examples/Probabilistic_Layers_VAE). When running it I get the following exception:
```
Blas xGEMM launch failed : a.shape=[1,300,4096], b.shape=[1,4096,512], m=300, n=512, k=4096
	 [[node encoder/dense/MatMul (defined at <ipython-input-8-24f1e62ee75b>:15) ]] [Op:__inference_train_function_1790]
```
Jupyter also throws a ```CUBLAS_STATUS_NOT_INITIALIZED``` error. NVTOP also show that all of the VRAM is being used. I run ``` tf.config.experimental.set_memory_growth(gpu, True)``` right after tensorflow import.

Removing
```
if tf.test.gpu_device_name() != '/device:GPU:0':
  print('WARNING: GPU device not found.')
else:
  print('SUCCESS: Found GPU: {}'.format(tf.test.gpu_device_name()))
```
fixes the problem. When adding this snippet to any other tensorflow program it breaks as well.

My theory is that ```tf.test.gpu_device_name()``` somehow breaks or resets ```tf.config.experimental.set_memory_growth(gpu, True)```.

**Comment by bhack** [comment]
It Is probably a https://github.com/tensorflow/tensorflow/issues/26275 duplicate.
