### ISSUE TITLE
tf.enable_eager_execution() not working

### ISSUE THREAD

**Issue by MeteoRex11** [tensorflow/tensorflow#45636]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- CUDA/cuDNN version: cuDNN 7.6.5
- GPU model and memory: NVIDIA GTX 1050

**Describe the current behavior**
I am trying to use the function tensor.numpy(), which requires eager_excecution to be enabled. I checked online, and it said that Tensorflow 2.0 has eager_execution enabled by default. However, when I run `print(tf.executing_eagerly())` the output is `False`

I have tried the `tf.compat.v1.enable_eager_execution()` function, but it does not seem to change anything

**Standalone code to reproduce the issue**
```
import tensorflow as tf
tf.compat.v1.enable_eager_execution()
print(tf.executing_eagerly())

```

**Comment by Saduf2019** [comment]
MeteoRex11 
I ran the code shared and do not face issue reported, please refer  to the [gist here](https://colab.research.google.com/gist/Saduf2019/c323090d207a00edd540c4d7a4ff5b57/untitled485.ipynb). Could you try on colab and let us know.

**Comment by MeteoRex11** [comment]
> MeteoRex11
> I ran the code shared and do not face issue reported, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/c323090d207a00edd540c4d7a4ff5b57/untitled485.ipynb). Could you try on colab and let us know.

It is working on colab, but not on my system. Is it because of some installation issue?

**Comment by ymodak** [comment]
@MeteoRex11 Did you pass  [`--config=v2` flag](https://github.com/tensorflow/tensorflow/issues/29573) while building from source?
See https://www.tensorflow.org/install/source#expandable-1

**Comment by MeteoRex11** [comment]
> @MeteoRex11 Did you pass [`--config=v2`](https://github.com/tensorflow/tensorflow/issues/29573) flag while building from source?
> See https://www.tensorflow.org/install/source#expandable-1

No actually I had installed tensorflow via pip, in an anaconda environment.

**Comment by Saduf2019** [comment]
@MeteoRex11 
Is this still an issue.

**Comment by MeteoRex11** [comment]
Yes it still doesn't work. I tried reinstalling Tensorflow but the issue persists

**Comment by jvishnuvardhan** [comment]
@MeteoRex11 I just tried on my `windows-10` desktop and don't see any issue there. I have exactly same TF version as you. You don't need `tf.compat.v1.enable_eager_execution()`. It is difficult to test why it is working wrongly for you. I guess it is more related to windows-10 and not related to TF.

Can you please try 

```
import tensorflow as tf
#tf.compat.v1.enable_eager_execution()
print(tf.executing_eagerly())
tf.__version__()
```

**Comment by MeteoRex11** [comment]
> @MeteoRex11 I just tried on my `windows-10` desktop and don't see any issue there. I have exactly same TF version as you. You don't need `tf.compat.v1.enable_eager_execution()`. It is difficult to test why it is working wrongly for you. I guess it is more related to windows-10 and not related to TF.
> 
> Can you please try
> 
> ```
> import tensorflow as tf
> #tf.compat.v1.enable_eager_execution()
> print(tf.executing_eagerly())
> tf.__version__()
> ```

The issue was being replicated on Linux as well, but reinstalling Tensorflow, CuDNN & CudaToolKit's older versions fixed it.
