### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'com_google_protobuf'

### ISSUE THREAD

**Issue by rani-pinchuk** [tensorflow/tensorflow#45633]
- Windows 10 - fresh installation to reproduce this problem (after experiencing this issue on another Windows 10 machine).
- Following the instructions in https://www.tensorflow.org/install/source_windows (without installing MSYS2).
- TensorFlow version: r2.3 and latest (tried both)
- Python version: 3.8.6
- Bazel version: 3.1.0 and 3.7.1 (both were tried and give the same results)
- Compiler version: according to the instructions as mentioned above (Install Visual C++ Build Tools 2019)

**Describe the problem**
For r2.3, the compilation starts as usual and fail with:
```
...
Repository rule tf_http_archive defined at:
  C:/users/ranip/documents/tensorflow/third_party/repo.bzl:134:19: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Elapsed time: 180.653s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 12 targets configured)
    currently loading: tensorflow
```

For latest master, it fails with:
```
...
Repository rule third_party_http_archive defined at:
  C:/users/ranip/documents/tensorflow/third_party/repo.bzl:216:28: in <toplevel>
ERROR: An error occurred during the fetch of repository 'flatbuffers':
   Traceback (most recent call last):
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 73, in _apply_delete
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
ERROR: C:/users/ranip/documents/tensorflow/tensorflow/tools/pip_package/BUILD:281:1: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/lite/python:tflite_convert in repository @ which failed to fetch. no such package '@flatbuffers//': Traceback (most recent call last):
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 73, in _apply_delete
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@flatbuffers//': Traceback (most recent call last):
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 193
                _apply_delete(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 73, in _apply_delete
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/ranip/documents/tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Elapsed time: 174.239s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (50 packages loaded, 14 targets configured)
    currently loading: tensorflow/lite/python
```

I am aware of issues https://github.com/tensorflow/tensorflow/issues/37897 and https://github.com/tensorflow/tensorflow/issues/35414 - no "Windows Subsystem for Linux" was installed on this Windows - as said - it is a fresh Windows 10 install, just to reproduce this problem. Did not use gitbash, or any Unix like shell.  Only Powershell was used.

**Comment by Saduf2019** [comment]
@rani-pinchuk 
Please refer to this resolved [issue](https://github.com/tensorflow/tensorflow/issues/42587#issuecomment-678813034) with same error and let us know. [ also verify if your pip version is latest]

**Comment by rani-pinchuk** [comment]
> @rani-pinchuk
> Please refer to this resolved [issue](https://github.com/tensorflow/tensorflow/issues/42587#issuecomment-678813034) with same error and let us know. [ also verify if your pip version is latest]

I have tried it again, from a totally clean windows installation, following the instructions in https://www.tensorflow.org/install/source_windows to the letter, but WITHOUT installing MSYS2. Using r2.4. 

I still get "An error occurred during the fetch of repository 'flatbuffers'". Pip version is the latest. BAZEL_VC has no impact, and I don't see how the issue pointed to is resolved.

As I am trying doing this again and again from a fresh Windows 10 installation, the only conclusion I have is that something is missing in the documentation in https://www.tensorflow.org/install/source_windows

Any help will be appreciated.

**Comment by mihaimaruseac** [comment]
`BAZEL_SH environment variable is not set`

Seems like a Bazel bug to me.

Can you compile other projects that use Bazel?

**Comment by rani-pinchuk** [comment]
I am not very much familiar with Bazel, and have no other projects to compile with it. 

I wonder if you could, though, explain (or document) the Window setup that is used to create the nightly-builds (or the release builds - see  #46538). I thought that this setup is based on the documentation in https://www.tensorflow.org/install/source_windows and therefore, this documentation must be correct... 

In any case, if it helps, I will be happy to follow your instructions and try to build other project on the setup I have.

**Comment by mihaimaruseac** [comment]
https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/ci_build/rel/windows/ contains the scripts we are using for the release (nightly or final release). What is not shown there is just the VM setup and setting up credentials and build optimizations for internal hosts.

Most Google projects have a bazel build. You can also make a custom one.

**Comment by mihaimaruseac** [comment]
Did you manage to test on another project?

**Comment by mihaimaruseac** [comment]
Closing as no response has been received and it doesn't look like a TF issue.
