### ISSUE TITLE
Can't Install TF on Apple M1

### ISSUE THREAD

**Issue by mabidou** [tensorflow/tensorflow#45645]
**Issue Creation**
On trying to install TF 2.3 using `pip install tensorflow==2.3` from the terminal, I got a success message.
I could see tensorflow 2.3 in the list of installed packages by using either `conda list` or `pip list`

When I run python from the terminal and trying to import tensorflow, it returns this error message:

```
(tfenv) mgd@MGD-m1 ~ % conda list tensorflow
# packages in environment at /Users/mgd/opt/anaconda3/envs/tfenv:
#
# Name                    Version                   Build  Channel
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-datasets       4.1.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorflow-metadata       0.26.0                   pypi_0    pypi
(tfenv) mgd@MGD-m1 ~ % python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
zsh: illegal hardware instruction  python
(tfenv) mgd@MGD-m1 ~ % 
```

on uninstalling it and trying to installing again using:
`pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.3.0-cp38-cp38-macosx_10_14_x86_64.whl`
same issue

Same scenario on trying latest version. i.e. by using just `pip install tensorflow` to get 2.3.1

On trying to import it from Jupyter Lab, no error message is shown and also no interaction is happening. It's as if it's empty cell.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.0.1
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.3.1
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: pip

**Comment by mabidou** [comment]
Same issue reported before but no fix
https://github.com/tensorflow/tensorflow/issues/44999

**Comment by amahendrakar** [comment]
@mabidou,
Could you please try installing TensorFlow as per [this guide](https://github.com/apple/tensorflow_macos#installation) from Apple and let us know if it helps.

Also, please go through issue [#44751](https://github.com/tensorflow/tensorflow/issues/44751) for more information. Thanks!

**Comment by mabidou** [comment]
I have tried mentioned [link](https://github.com/apple/tensorflow_macos#installation) that has created a new env and also installed mac version that is not possible to import.

Here are more details. After installation, I got
```
TensorFlow and TensorFlow Addons with ML Compute for macOS 11.0 successfully installed.
To begin, activate the virtual environment:
   . "/Users/mgd/tensorflow_macos_venv/bin/activate" 
```
When activating the env using `source /Users/mgd/tensorflow_macos_venv/bin/activate`

I switched to it & I found the following packages, noting that I uninstalled previous version before starting this trial. Anyhow, here's what I found.

```
tensorflow-addons      0.11.2
tensorflow-estimator   2.3.0
tensorflow-macos       0.1a1 
```

After running Python inside the terminal and trying to import it, I failed & here's the full log

```
(base) mgd@MGD-m1 ~ % source /Users/mgd/tensorflow_macos_venv/bin/activate
(tensorflow_macos_venv) (base) mgd@MGD-m1 ~ % python --version
Python 3.8.5
(tensorflow_macos_venv) (base) mgd@MGD-m1 ~ % python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow-macos as tf
  File "<stdin>", line 1
    import tensorflow-macos as tf
                     ^
SyntaxError: invalid syntax
>>> import tensorflow_macos as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow_macos'
>>> 
```

**Comment by mabidou** [comment]
@amahendrakar Hope to consider the need of running TF 2.3 as it's required for TF certificate. 
Although I installed macOS version that didn't work, I still need to run TF 2.3 for above certificate.

**Comment by mabidou** [comment]
Seems no solution so far!
https://github.com/tensorflow/tensorflow/pull/45404

**Comment by mabidou** [comment]
Also TensorFlow Data Sets is not working and I reported it 
https://github.com/tensorflow/datasets/issues/2872

**Comment by mihaimaruseac** [comment]
As mentioned in #45631, this should be reported on the Apple fork.
