### ISSUE TITLE
Tensorflow 1.x binary not found with pip install (Python=3.7)

### ISSUE THREAD

**Issue by ad12** [tensorflow/tensorflow#45642]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
Tensorflow 1.x (specifically 1.15) binary cannot be found when installing via `pip` 

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4)
ERROR: No matching distribution found for tensorflow-gpu==1.15
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
conda create -n tf1 python=3.7
conda activate tf1
pip install tensorflow-gpu==1.15
```

**Comment by ravikyram** [comment]
@ad12 

Please, refer similar issue #39380 , #34302 and see if it helps you.Also, could you please check if you are using the 64 bit version of Python. Thanks!

**Comment by ad12** [comment]
@ravikyram thanks for these suggestions

#39380 mentions that Tensorflow 1.X is not compatible with Python 3.8. I am running with 3.7.9 so this may not be the issue. I also tried with python 3.6.12 and also getting the same `pip install` error

#34302 mentions upgrading `pip>=19.0` as the fix. I am running with `pip=20.3.1`

I am also using the 64-bit Python version.

**Comment by mihaimaruseac** [comment]
Please attach the output of `pip debug verbose` and `pip install -vv tensorflow-gpu==1.15.4` (preferably in a new clean virtualenv)

**Comment by ad12** [comment]
It appears to have resolved itself, thank you!
