### ISSUE TITLE
what are the .pb and .h5  model file?

### ISSUE THREAD

**Issue by pogevip** [tensorflow/tensorflow#45644]
```
model = create_model()
model.fit(train_images, train_labels, epochs=5)

!mkdir -p saved_model

model.save('saved_model/my_model') 

model.save('my_model.h5') 
```
what's the .pb  model?
What are the differences and similarities between it and TensorRT's engine file?

**Comment by bhack** [comment]
> There are two formats you can use to save an entire model to disk: the TensorFlow SavedModel format, and the older Keras H5 format. 

https://www.tensorflow.org/guide/keras/save_and_serialize

**Comment by Saduf2019** [comment]
These are to formats used when you want to deploy ypur model, example if you want to deploy on android the acceptable format is .pb(info such as graph definistion,checkpoits,weights are combined ot freezed into a single file .pb--protocol buffer wheras .h5 is keras model), which later needs to eb converted to .tflite. we use .pb and not .h5 for deployment or large scale use of model as a product.
For your question about Tensorrt a .pb model can be converted to TensorRT model.
