### ISSUE TITLE
 2.4.0 sess.run freezing in Windows 10 with RTX 3090

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#45648]
my DeepFaceLab software uses tf 2.3.1 with compat.v1, it works fine.
When I upgrade to 2.4.0rc4, tf sess.run is freezed without any errors.
Seems like it depends on model complexity.
Models with big graph freeze instantly.
Model with simpler graph may be freezed in 30 minutes.
I don't know how to write reproduction code.

OS: Windows 10

Windows 10 setting
Hardware-accelerated GPU scheduling to “ default graphics setting ”, solves the problem.

![fwy9iW8 1](https://user-images.githubusercontent.com/8076202/102058534-11408180-3e09-11eb-9bea-839dce2e9870.jpg)

**Comment by iperov** [comment]
Hardware-accelerated GPU scheduling to “ default graphics setting ”, solves the problem.

**Comment by ymodak** [comment]
TF 2.X packages come with gpu support however if the gpu environment setup is not compatible it silently falls back on cpu for computations.
TensorFlow 2.4 pip packages are built with CUDA11 and cuDNN 8.0.2.
See [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0).

**Comment by iperov** [comment]
I am using CUDA11 and cuDNN 8.0.2

**Comment by KichangKim** [comment]
@iperov You saved my life. I have exactly same issue on my large scale CNN network, and it solved by enabling Hardware accelerated GPU scheduling in Windows 10. (Python 3.8 + TensorFlow 2.4.0)

**Comment by iperov** [comment]
> @iperov I have exactly same issue on my large scale CNN network

do you also use compat.v1 ?

**Comment by KichangKim** [comment]
No, I used keras API. TF 2.4.0 makes application freezed (0% cpu/gpu usage) without errors.

**Comment by iperov** [comment]
@KichangKim
> I used keras API. 

so it is mean the problem not only with v1 graph system, but also with v2 eager execution?

**Comment by iperov** [comment]
2.4.0 release does not fix the issue.

**Comment by Zhaopudark** [comment]
The same with me. I have tried 2.4.0-rc0 rc1 rc2 rc3 rc4 and 2.4.0 but unexpected thread freezing usually but not always  appear.

**Comment by iperov** [comment]
@ymodak still no solution?
why users should do the fix in windows settings?

**Comment by sanjoy** [comment]
I don't know what the "Hardware accelerated GPU scheduling" feature does (perhaps it uses the new CUDA-graph HW support in Ampere?), so I don't understand why it is interacting poorly with TensorFlow.  Someone familiar with this new setting in Windows will have to chime in.

**Comment by iperov** [comment]
I am using RTX 2080, it is not ampere.

**Comment by psycho2012** [comment]
reference, https://github.com/tensorflow/tensorflow/issues/45716

**Comment by iperov** [comment]
@psycho2012  already referenced, you are blind flooder

**Comment by iperov** [comment]
also in Windows Server 2019 no solution at all. 
Stable freeze with tf 2.4.0 and rtx 3090

**Comment by Fannhhyy** [comment]
`https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.15.4%2Bnv20.12/py38/CPU%2BGPU/cuda111cudnn8avx2`
This repo build tf1.15 whl with cuda11 support，maybe you can try it

**Comment by iperov** [comment]
@Fannhhyy 
py3.8 - no
avx2 - no

**Comment by Fannhhyy** [comment]
> @Fannhhyy
> py3.8-没有
> avx2-没有

`https://github.com/fo40225/tensorflow-windows-wheel/issues/167#issuecomment-767277221`
The author fixed the nvidia-tensorflow build on windows. Maybe you can try to build it.

'https://drive.google.com/file/d/1Zeln6Buadpokml3wmTwyJipRo2JvRKP8/view?usp=sharing'
I tried to build it , but I don't have time to test the whl.

**Comment by sachinprasadhs** [comment]
Hi, could you please check if the issue still persists with latest Tensorflow version or tf-nightly version. 
Also, make sure you update the drivers and the tested build configurations from [here](https://www.tensorflow.org/install/source_windows#gpu). Thanks!
