### ISSUE TITLE
Mask RCNN tflite inference on android

### ISSUE THREAD

**Issue by MeghaGhosh** [tensorflow/tensorflow#45651]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): nightly

**Provide the text output from tflite_convert**

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /tmp/tmpjivs_7gq/assets
```

**Standalone code to reproduce the issue** 

int imageTensorIndex = 0;
        int[] imageShape = tflite.getInputTensor(imageTensorIndex).shape(); // {1, height, width, 3}
        imageSizeY = imageShape[1];
        imageSizeX = imageShape[2];
        DataType imageDataType = tflite.getInputTensor(imageTensorIndex).dataType();

TensorImage inputImageBuffer = new TensorImage(imageDataType);
 inputImageBuffer.load(bitmap);

int[] probabilityShape = tflite.getOutputTensor(probabilityTensorIndex).shape(); // {1, NUM_CLASSES}
DataType probabilityDataType = tflite.getOutputTensor(probabilityTensorIndex).dataType();
// Creates the output tensor and its processor.
outputProbabilityBuffer = TensorBuffer.createFixedSize(probabilityShape, probabilityDataType);
tflite.run(inputImageBuffer.getBuffer(), outputProbabilityBuffer.getBuffer().rewind());

Also, please include a link to a GraphDef or the model if possible.

[{'name': 'input_image', 'index': 0, 'shape': array([   1, 1024, 1024,    3], dtype=int32), 'shape_signature': array([  -1, 1024, 1024,    3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'input_image_meta', 'index': 1, 'shape': array([ 1, 18], dtype=int32), 'shape_signature': array([-1, 18], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'input_anchors', 'index': 2, 'shape': array([     1, 261888,      4], dtype=int32), 'shape_signature': array([    -1, 261888,      4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 662, 'shape': array([1, 1, 1], dtype=int32), 'shape_signature': array([ 1, -1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_1', 'index': 740, 'shape': array([   1, 1000,    6,    4], dtype=int32), 'shape_signature': array([   1, 1000,    6,    4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_2', 'index': 744, 'shape': array([   1, 1000,    6], dtype=int32), 'shape_signature': array([   1, 1000,    6], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_3', 'index': 864, 'shape': array([  1, 100,   6], dtype=int32), 'shape_signature': array([  1, 100,   6], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_4', 'index': 936, 'shape': array([  1, 100,  28,  28,   6], dtype=int32), 'shape_signature': array([  1, 100,  28,  28,   6], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_5', 'index': 578, 'shape': array([1, 1, 4], dtype=int32), 'shape_signature': array([-1, -1,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_6', 'index': 591, 'shape': array([1, 1, 2], dtype=int32), 'shape_signature': array([-1, -1,  2], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

These are the input and output tensors of the model.

--------- beginning of crash
2020-12-11 17:27:42.138 16752-16752/com.objdetector A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 16752 (com.objdetector), pid 16752 (com.objdetector)

This is the segmentation fault error

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

How exactly should I run inference on android for Mask RCNN tflite model? I have added these dependencies:

dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
}

There seem to be 3 inputs and 7 outputs to the model.. what do i need to pass as input, should I pass image, image_meta as well as input anchors? Which of the outputs will provide the result? Do I need to map all the outputs? How can I get the result?

**Comment by srjoglekar246** [comment]
@MeghaGhosh What is your use-case? If you need bounding boxes, you can check out the [SSD models on the TF2 detection zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) Mask-RCNN is not very well supported on TFLite, mainly because the models in the TF1 detection zoo are too large to perform well on-device.

**Comment by MeghaGhosh** [comment]
I need Mask RCNN itself.. I need the tflite model to match my h5 model in this use case.. and that cannot be changed from Mask RCNN. What do you mean "not very well" supported? Is it supported though? Even just the bounding box values are enough.. Is it possible to get the output using android interpreter?

**Comment by srjoglekar246** [comment]
@MeghaGhosh Support for the TF1 Mask RCNNmodels in TFlite is pretty limited. That said, feel free to follow the steps in [this Github issue](https://github.com/tensorflow/tensorflow/issues/34845#issuecomment-573156336) to get a TFLite model. Its latency is pretty large (~1-2s), and you will need to change some of the pipeline config params based on which model you are using. Feel free to give it a try :-)
We are also working on CenterNet & EfficientDet support in the TF2 detection zoo for mobile phones, so hopefully we will models with greater mAP soon.

**Comment by MeghaGhosh** [comment]
Okay sure I will check that out, thank you. In addition, I did actually get a tflite model from the matterport Mask RCNN model.. i used select tf ops for conversion, python inference did not work but android seems to support select ops from what I've been reading.. what I could use help with is the android inference. Currently facing a segmentation fault issue that I have outlined, would appreciate any direction you could point me in with reference to that.

**Comment by abattery** [comment]
@MeghaGhosh Could you share the more details on the unsuccessful behavior seen in Python inference? Which computer system, operating system, and TensorFlow version did you use for Python inference?

**Comment by terryheo** [comment]
If the crashing happens on x86 emulator, it's likely the same issue with https://github.com/tensorflow/tensorflow/issues/38025

As a workaround, you need to use download nightly manually.
https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/google3/ubuntu_16/lite/nightly/511/20201214-223707/tensorflow-lite-select-tf-ops.aar

And use it as
```
compile files('libs/tensorflow-lite-select-tf-ops.aar')
```
instead of
```
implementation('org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly') { changing = true }
```

**Comment by MeghaGhosh** [comment]
So the segmentation fault is actually happening when we create the tflite model with tf-nightly version. When we create the model with tensorflow 2.3.0 we are getting this error:


2020-12-18 16:03:35.209 12244-12244/com.objdetector W/System.err: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reduce.cc:534 reference_ops::ReduceGeneric<T>( GetTensorData<T>(op_context->input), op_context->input->dims->data, op_context->input->dims->size, GetTensorData<T>(op_context->output), op_context->output->dims->data, op_context->output->dims->size, GetTensorData<int>(op_context->axis), num_axis, op_context->params->keep_dims, GetTensorData<int>(temp_index), GetTensorData<int>(resolved_axis), init_value, reducer) was not true.2020-12-18 16:03:35.209 12244-12244/com.objdetector W/System.err: No2020-12-18 16:03:35.221 12244-12244/com.objdetector W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)2020-12-18 16:03:35.221 12244-12244/com.objdetector W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)2020-12-18 16:03:35.221 12244-12244/com.objdetector W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)2020-12-18 16:03:35.221 12244-12244/com.objdetector W/System.err:     at com.objdetector.deepmodel.MObjectDetector.detectObjects(MObjectDetector.java:198)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at com.objdetector.MainActivitynew$1.onClick(MainActivitynew.java:69)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.view.View.performClick(View.java:6733)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.view.View.performClickInternal(View.java:6691)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.view.View.access$3400(View.java:802)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.view.View$PerformClick.run(View.java:26499)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.os.Looper.loop(Looper.java:226)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7178)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at java.lang.reflect.Method.invoke(Native Method)2020-12-18 16:03:35.222 12244-12244/com.objdetector W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)2020-12-18 16:03:35.223 12244-12244/com.objdetector W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)2020-12-18 16:03:35.224 12244-12244/com.objdetector E/Edgar: []2020-12-18 16:03:35.245 12244-12244/com.objdetector E/ANR_LOG: >>> msg's executing time is too long2020-12-18 16:03:35.245 12244-12244/com.objdetector E/ANR_LOG: Blocked msg = { when=-44s561ms what=0 target=android.view.ViewRootImpl$ViewRootHandler callback=android.view.View$PerformClick } , cost  = 44558 ms2020-12-18 16:03:35.245 12244-12244/com.objdetector E/ANR_LOG: >>>Current msg List is:2020-12-18 16:03:35.246 12244-12244/com.objdetector E/ANR_LOG: Current msg <1>  = { when=-44s561ms what=0 target=android.view.ViewRootImpl$ViewRootHandler callback=android.view.View$UnsetPressedState }2020-12-18 16:03:35.246 12244-12244/com.objdetector E/ANR_LOG: >>>CURRENT MSG DUMP OVER<<<2020-12-18 16:03:35.282 12244-12244/com.objdetector I/Choreographer: Skipped 2675 frames!  The application may be doing too much work on its main thread.2020-12-18 16:03:35.355 12244-12244/com.objdetector I/Choreographer: Skipped 3 frames!  The application may be doing too much work on its main thread.2020-12-18 16:03:35.361 12244-12423/com.objdetector I/OpenGLRenderer: Davey! duration=44679ms; Flags=0, IntendedVsync=204496322680101, Vsync=204540920879301, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=204540928240420, AnimationStart=204540928558343, PerformTraversalsStart=204540930867420, DrawStart=204540931626113, SyncQueued=204540934693343, SyncStart=204540934836959, IssueDrawCommandsStart=204540987101266, SwapBuffers=204540994920651, FrameCompleted=204541002585651, DequeueBufferDuration=553000, QueueBufferDuration=6118000, ReplyForward |   | ReplyForward |   |  
-- | -- | -- | -- | --
  | ReplyForward

We have tried 2-3 different versions of code and they all result in the same error - I am sharing all the different versions here:

1. Generating an image of input tensor size and passing that as input (have tried passing a real image with the same result):

int imageTensorIndex = 0;
int[] imageShape = tfLite.getInputTensor(imageTensorIndex).shape(); // {1, height, width, 3}
int imageSizeY = imageShape[1];
int imageSizeX = imageShape[2];
DataType imageDataType = tfLite.getInputTensor(imageTensorIndex).dataType();

// input tensor

int[] inputshape;
DataType OinputputDataType = null;

HashMap inputProbabilityBuffers = new HashMap<>();
ByteBuffer xc;
for (int k = 0; k < tfLite.getInputTensorCount(); k++) {
    inputshape = tfLite.getInputTensor(k).shape();
    OinputputDataType = tfLite.getInputTensor(k).dataType();
    xc = TensorBuffer.createFixedSize(inputshape, OinputputDataType).getBuffer();
    inputProbabilityBuffers.put(k, xc);
}

TensorImage inputImageBuffer = new TensorImage(OinputputDataType);
inputImageBuffer.load(generateImage());

int[] OutputShape;
DataType OutputDataType;
HashMap outputProbabilityBuffers = new HashMap<>();
ByteBuffer x;
for (int i = 0; i < tfLite.getOutputTensorCount(); i++) {
    OutputShape = tfLite.getOutputTensor(i).shape();
    OutputDataType = tfLite.getOutputTensor(i).dataType();
    x = TensorBuffer.createFixedSize(OutputShape, OutputDataType).getBuffer();
    outputProbabilityBuffers.put(i, x);
    
}

Object[] Inputs = {inputImageBuffer.getBuffer()};

try {
    tfLite.runForMultipleInputsOutputs(Inputs, outputProbabilityBuffers);
} catch (Exception e){
    e.printStackTrace();
}


2. Passing random float values into all 3 input tensors and sending those to the model:

int imageTensorIndex = 0;
  int[] imageShape = tfLite.getInputTensor(imageTensorIndex).shape(); // {1, height, width, 3}
  int imageSizeY = imageShape[1];
  int imageSizeX = imageShape[2];
  DataType imageDataType = tfLite.getInputTensor(imageTensorIndex).dataType();

  // input tensor

  int[] inputshape;
  DataType OinputputDataType = null;

  HashMap inputProbabilityBuffers = new HashMap<>();
  ByteBuffer xc;
  Object[] input = new Object[3];

  for (int k = 0; k < tfLite.getInputTensorCount(); k++) {
      inputshape = tfLite.getInputTensor(k).shape();
      Log.e("Edgar",""+ inputshape.toString());

      OinputputDataType = tfLite.getInputTensor(k).dataType();
      xc = TensorBuffer.createFixedSize(inputshape, OinputputDataType).getBuffer();
      inputProbabilityBuffers.put(k, xc);

      ByteBuffer temp = ByteBuffer.allocateDirect(xc.limit()); // Allocate with size of float
      temp.putFloat(inputshape[k]); // May be an array containing actual values
      input[k] = temp;
  }
 
  TensorImage inputImageBuffer = new TensorImage(OinputputDataType);
  inputImageBuffer.load(generateImage());

  int[] OutputShape;
  DataType OutputDataType;
  HashMap outputProbabilityBuffers = new HashMap<>();
  ByteBuffer x;
  for (int i = 0; i < tfLite.getOutputTensorCount(); i++) {
      OutputShape = tfLite.getOutputTensor(i).shape();
      OutputDataType = tfLite.getOutputTensor(i).dataType();
      x = TensorBuffer.createFixedSize(OutputShape, OutputDataType).getBuffer();
      outputProbabilityBuffers.put(i, x);

  }
  try {
      tfLite.runForMultipleInputsOutputs(input, outputProbabilityBuffers);

      Log.e("Edgar", "" + outputProbabilityBuffers.toString());

  } catch (Exception e){
      e.printStackTrace();
  }

3. Creating empty buffers for inputs and passing those:

int[] inputshape;
DataType OinputputDataType;	
Object inputs[] = new Object[tfLite.getInputTensorCount()];
for (int i=0; i < tfLite.getInputTensorCount(); i++) {
	inputshape = tfLite.getInputTensor(k).shape();
    OinputputDataType = tfLite.getInputTensor(k).dataType();
    xc = TensorBuffer.createFixedSize(inputshape, OinputputDataType).getBuffer();
    inputProbabilityBuffers.put(k, xc);
	ByteBuffer i_bytes = ByteBuffer.allocate(xc);
	inputs[i] = i_bytes;
    }
int[] OutputShape;
DataType OutputDataType;
HashMap outputProbabilityBuffers = new HashMap<>();
ByteBuffer x;
for (int i = 0; i < tfLite.getOutputTensorCount(); i++) {
  OutputShape = tfLite.getOutputTensor(i).shape();
  OutputDataType = tfLite.getOutputTensor(i).dataType();
  x = TensorBuffer.createFixedSize(OutputShape, OutputDataType).getBuffer();
  outputProbabilityBuffers.put(i, x);
}
interpreter.runForMultipleInputsOutputs(inputs, outputProbabilityBuffers);

They all result in above error. This is my model file (it is the converted tflite model from mask rcnn coco weights file):

https://drive.google.com/file/d/1gGjMK_YyyHuOqyZytsoh5sJ9jSPSxn7J/view

This is the implementation while building gradle:

assert file(project.ext.ASSET_DIR + "/model.tflite").exists()
assert file(project.ext.ASSET_DIR + "/mod.txt").exists()
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.objdetector"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk{
            abiFilters  'armeabi-v7a',  'arm64-v8a'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dependencies {
        implementation 'org.tensorflow:tensorflow-android:1.6.0'
    }

    aaptOptions {
        noCompress "tflite"
    }

    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
//    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
   implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'

}

What are we missing? Is there some other way we need to pass the input values?

**Comment by abattery** [comment]
@MeghaGhosh I confirmed that your shared model, which is included in the above comment, was able to run with the benchmark_model_plus_flex tool. Looks like the model itself is runnable.

Could you follow the @terryheo 's comment with the shared model?

**Comment by MeghaGhosh** [comment]
Yes, we are using the nightly aar files. Still facing the same issue:

2020-12-22 17:10:08.127 16299-16299/com.objdetector W/System.err: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/reduce.cc:534 reference_ops::ReduceGeneric<T>( GetTensorData<T>(op_context->input), op_context->input->dims->data, op_context->input->dims->size, GetTensorData<T>(op_context->output), op_context->output->dims->data, op_context->output->dims->size, GetTensorData<int>(op_context->axis), num_axis, op_context->params->keep_dims, GetTensorData<int>(temp_index), GetTensorData<int>(resolved_axis), init_value, reducer) was not true.

**Comment by abattery** [comment]
@MeghaGhosh there are possibility that model won't work when the given input shape is not compatible with the model. Could you make sure that the input shapes being used meet input constraints?

**Comment by MeghaGhosh** [comment]
Hi @abattery yes we are taking the input shapes from the model itself and filling the object, the size of our object matches that expected by the model. This is our latest attempt, could you let us know if we're missing something?
int imageTensorIndex = 0;
        int[] imageShape = tfLite.getInputTensor(imageTensorIndex).shape(); // {1, height, width, 3}
        int imageSizeY = imageShape[1];
        int imageSizeX = imageShape[2];
        DataType imageDataType = tfLite.getInputTensor(imageTensorIndex).dataType();
// input tensor
        int[] inputshape;
        DataType OinputputDataType = null;
        HashMap inputProbabilityBuffers = new HashMap<>();
        ByteBuffer xc;
        Object[] input = new Object[3];
        for (int k = 0; k < tfLite.getInputTensorCount(); k++) {
            inputshape = tfLite.getInputTensor(k).shape();
            OinputputDataType = tfLite.getInputTensor(k).dataType();
            xc = TensorBuffer.createFixedSize(inputshape, OinputputDataType).getBuffer();
            inputProbabilityBuffers.put(k, xc);
            ByteBuffer temp = ByteBuffer.allocateDirect(xc.limit()); // Allocate with size of float
            int[] shape = tfLite.getInputTensor(k).shape();

            int na = xc.limit()/4;
            for (int a = 0; a <na; a++) {
               // temp.put(randomno);
                temp.putFloat(0);
               // temp.put(randomno);
            }
            input[k] = temp;
//            String stringShape = "";
//            for(int j = 0; j < shape.length; j++) {
//                stringShape = stringShape + ", " + shape[j];
//            }
            Log.e("Edgar", "Shape of input tensor " + ": " + Arrays.toString(input));
            tfLite.resizeInput(k, inputshape);
        }
        int[] OutputShape;
        DataType OutputDataType;
        HashMap outputProbabilityBuffers = new HashMap<>();
        ByteBuffer x;
        for (int i = 0; i < tfLite.getOutputTensorCount(); i++) {
            OutputShape = tfLite.getOutputTensor(i).shape();
            OutputDataType = tfLite.getOutputTensor(i).dataType();
            x = TensorBuffer.createFixedSize(OutputShape, OutputDataType).getBuffer();
            outputProbabilityBuffers.put(i, x);
        }
        try {
            tfLite.runForMultipleInputsOutputs(input, outputProbabilityBuffers);
            Log.e("Edgar", "" + outputProbabilityBuffers.toString());
        } catch (Exception e){
            e.printStackTrace();
        }


Shape of input tensor : [java.nio.DirectByteBuffer[pos=12582912 lim=12582912 cap=12582912], java.nio.DirectByteBuffer[pos=372 lim=372 cap=372], java.nio.DirectByteBuffer[pos=4190208 lim=4190208 cap=4190208]]
6:42

**Comment by abattery** [comment]
Could you share your input shape sizes? I would make sure that the benchmark tool can reproduce the problem with those sizes or not.

**Comment by MeghaGhosh** [comment]
Thanks! These are the input shape sizes:

[1, 1024, 1024, 3]
[1, 93]
[1, 261888, 4]

**Comment by abattery** [comment]
The benchmark tool on the desktop works well with the model and the above input shapes.

@MeghaGhosh Can you share which version of aar files you are using?
@thaink could you take a look at this issue?

**Comment by MeghaGhosh** [comment]
I'm using the aar file from the link shared in @terryheo 's comment.

https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/google3/ubuntu_16/lite/nightly/511/20201214-223707/tensorflow-lite-select-tf-ops.aar

**Comment by abattery** [comment]
@MeghaGhosh could you try the same version of tensorflow-lite.aar as well?

https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/google3/ubuntu_16/lite/nightly/511/20201214-223707/tensorflow-lite.aar

**Comment by MeghaGhosh** [comment]
Yes we've been trying this, however this is leading to us not being able to use tensorflow-lite-support.

These implementations are leading to this error:

implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'
compile files ('libs/tensorflow-lite-select-tf-ops.aar')
compile files ('libs/tensorflow-lite.aar')

Duplicate class org.tensorflow.lite.DataType found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.DataType$1 found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.Delegate found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.Interpreter found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.Interpreter$Options found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.NativeInterpreterWrapper found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.Tensor found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.Tensor$QuantizationParams found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.TensorFlowLite found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.annotations.UsedByReflection found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.nnapi.NnApiDelegate found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Duplicate class org.tensorflow.lite.nnapi.NnApiDelegate$Options found in modules jetified-tensorflow-lite-0.0.0-nightly-runtime.jar (org.tensorflow:tensorflow-lite:0.0.0-nightly) and jetified-tensorflow-lite-runtime.jar (tensorflow-lite.aar)
Go to the documentation to learn how to Fix dependency resolution errors.

This is solved as we remove implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly', however then we can't use the support functions such as TensorBuffer. 

How can we work around this?

**Comment by MeghaGhosh** [comment]
Hey thanks for all the support, we could run the model on android with the following code:

Object[] inputs = new Object[] {new float[1][1024][1024][3], new float[1][93], new float[1][261888][4]};
Map<Integer, Object> outputs = new HashMap<>();
outputs.put(0, new float[1][1000][4]);
outputs.put(1, new float[1][1000][6][4]);
outputs.put(2, new float[1][1000][6]);
outputs.put(3, new float[1][100][6]);
outputs.put(4, new float[1][100][28][28][6]);
outputs.put(5, new float[1][261888][4]);
outputs.put(6, new float[1][261888][2]);
try {
    tfLite.runForMultipleInputsOutputs(inputs, outputs);
} catch (Exception e){
    e.printStackTrace();
}

The output tensor shapes returned by "tflite.GetOutputTensor" did not match 3 of the output shapes given here..

**Comment by MeghaGhosh** [comment]
Also, it's taking about 52 seconds to run (without GPU), is it taking the same amount of time on the benchmark tool as well?

**Comment by xiaodi68tmc** [comment]
I read through the discussion. Thanks for the information and learned.
Could I know how the performance of running Mask RCNN tflite on android (such as inference time)? Is any successful examples and demo codes?
I successfully converted my trained Mask RCNN model to a tflite model, but still didn't get how to run it on Android by using Java codes.
Thanks

**Comment by manthanTECHNOZER** [comment]
I've the same issue.

1. I used same config for Mask_RCNN from samples --> [Balloon](https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon).
2. Trained model on custom dataset. 
3. Successfully converted model from .h5(255.9MB) to .tflite(65.8MB), using this [article](https://wathek.medium.com/convert-mask-r-cnn-model-to-tflite-with-tensorflow-2-3-57160d3be18d).
4. Simple pass .tflite file to [label_image.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/python/label_image.py) for inference check.

After running this file, I also checked activity monitor to look at resources, it's taking ~90% CPU usage, but after 2/3 minutes, I got an error like this,
**`zsh: segmentation fault  python label_image.py`**

Didn't know, what's the problem, because I didn't even modify any code. 

Config:
TF-2.4.0 on MacOs 10.15 using conda (CPU only)

**Comment by MeghaGhosh** [comment]
Hey @abattery @terryheo I am facing issues inferencing the code and getting the output in android. 
I have populated all the input values - image, image meta and anchors , however the outputs are not as expected at all. I have shared the codes here. 

https://github.com/tensorflow/tensorflow/issues/46951

Any help will be much appreciated!!

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
