### ISSUE TITLE
Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45659]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0rc4
- Python version: 3.7.4
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: V100

**Describe the current behavior**

The following tests fail with the error "Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string": //tensorflow/python/ops/ragged:ragged_dispatch_test, //tensorflow/python/ops/ragged:ragged_map_fn_op_test, //tensorflow/python/ops/ragged:ragged_print_op_test, //tensorflow/python/ops/ragged:ragged_tensor_test

**Standalone code to reproduce the issue**
Running `bazel test` on the above targets

**Other info / logs**

Example log:

```
ERROR: testRaggedToStringescape (__main__.RaggedToStringTest)
RaggedToStringTest.testRaggedToStringescape
testRaggedToStringescape([["a'b"], ['c\\d']], "[['a\\'b'], ['c\\\\d']]")
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/ops/ragged/ragged_print_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/ops/ragged/ragged_print_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/tmp/bazel-tf/20db8ac50b74c328e6dea9b20829b459/execroot/org_tensorflow/bazel-out/ppc-opt/bin/tensorflow/python/ops/ragged/ragged_print_op_test.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
  (1) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
0 successful operations.
0 derived errors ignored.
	 [[{{node AsString/map/TensorArrayUnstack/TensorListFromTensor}}]]
	 [[Func/AsString/map/while/body/_1/input/_41/_24]]
  (1) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
  (1) Invalid argument: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
0 successful operations.
0 derived errors ignored.
	 [[{{node AsString/map/TensorArrayUnstack/TensorListFromTensor}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by ravikyram** [comment]
@Flamefire 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by Flamefire** [comment]
This is simply running the mentioned test case via bazel. I could also reproduce this with `python git/tensorflow/tensorflow/python/ops/ragged/ragged_print_op_test.py RaggedToStringTest.testRaggedToStringescape` with TF installed.

Reducing that to a minimal code is cumbersome as the error happens in graph mode with a `test_session` created spanning over many functions. My attempt in doing that failed, i.e. I could not extract enough from the test to make it fail

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Flamefire** [comment]
`python git/tensorflow/tensorflow/python/ops/ragged/ragged_print_op_test.py RaggedToStringTest.testRaggedToStringescape ` no longer fails so it might have been fixed
