### ISSUE TITLE
Build tensorflow from source, issues about CUDA lib and header paths

### ISSUE THREAD

**Issue by yummychop** [tensorflow/tensorflow#45667]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.3
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 11.0/8.0.4
- GPU model and memory: GTX 1060 6GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed [this](https://www.tensorflow.org/install/source) tutorial to install tensorflow from source, I would like to link my tensorflow to tensorRT and CUDA/CUDNN, when I ran the configure.py it seems that it couldn't locate the CUDA lib and header files, so I listed all the possible paths for CUDA libs and header files with comma-separated as required in configure, as the following:

/home/myName/Downloads/TensorRT-7.2.1.6.Ubuntu-18.04.x86_64-gnu.cuda-11.0.cudnn8.0/TensorRT-7.2.1.6,
/usr/local/cuda-11.0/targets/x86_64-linux/include,
/usr/local/cuda-11.0/targets/x86_64-linux/lib,
/usr/local/cuda-11.0/bin,
/usr/local/cuda-11.0/nvvm/libdevice,
/usr/local/cuda/nvvm/libdevice

Then it complained that it couldn't find libdevice*.10.bc, but this really doesn't make sense since /usr/local/cuda-11.0/nvvm/libdevice &  /usr/local/cuda/nvvm/libdevice are the paths containing libdevice.10.bc

I have already verified TensorRT's installation by running its sample projects, did I do anything wrong? Thank you in advance!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@yummychop,
Every TensorFlow release is compatible with certain a CUDA and cuDNN version. You can check the compatibility from the [tested build configurations](https://www.tensorflow.org/install/source#gpu). 

Since TensorFlow 1.x is not actively supported. Could you please try building TensorFlow v2.4 with CUDA 11 and cuDNN 8 and check if it works. Thanks!

**Comment by yummychop** [comment]
thank you @amahendrakar , i installed tensorflow 2.4.0 and the problem got resolved, I followed [this](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) tutorial provided by NVIDIA, it requires tensorflow 1.15.3 which is misleading...
