### ISSUE TITLE
Test failures with "OpError not raised"

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45661]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0rc4
- Python version: 3.7.4
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): GCC 8.3.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: V100

**Describe the current behavior**

Some tests fail with "OpError not raised": 
- //tensorflow/python/feature_column:feature_column_test  & //tensorflow/python/feature_column:feature_column_v2_test : IdentityCategoricalColumnTest.test_get_sparse_tensors_with_inputs_too_big
- //tensorflow/python/kernel_tests:batch_scatter_ops_test : ScatterTest.testScatterOutOfRange

**Standalone code to reproduce the issue**
Run bazel test

**Comment by amahendrakar** [comment]
@Flamefire,
In order to expedite the trouble-shooting process, could you please provide the exact sequence of commands / steps that you executed before running into the error. Thanks!

**Comment by Flamefire** [comment]
Running `python git/tensorflow/tensorflow/python/feature_column/feature_column_test.py IdentityCategoricalColumnTest.test_get_sparse_tensors_with_inputs_too_big` or the `bazel test` seems to be enough to trigger this.

I was able to reproduce this with the custom build TF 2.4 and the pip installed TF 2.3 (can't use 2.4 as we still have CUDA 10.1 on our systems and the driver update is pending)

**Comment by Flamefire** [comment]
Note that this seems to only affect the CPU dispatched version, while when a GPU that is used (by default  when any is detected) the bug does not appear. Furthermore it seems that out-of-bounds indices are seemingly ignored which means there is a chance those cause actual OOB writes which are somehow not noticed otherwise

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate from `feature column` to `keras preprocessing`, `feature column` will be deprecated going forward.
For more details refer [Migrate tf.feature_columns to Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns)
Also, refer the list of API's fate under feature column here https://www.tensorflow.org/api_docs/python/tf/feature_column?version=nightly

**Comment by sachinprasadhs** [comment]
Since it will be deprecated from Tensorflow 2.12 onwards, there won't be any development happening with the existing feature column code. 
Please refer migration guide here [Migrate tf.feature_columns to Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns) for the alternatives and create a new issue, if you find failure with the migrated code. Thanks!
