### ISSUE TITLE
Multi-GPU selection in map_fn and vectorized_map

### ISSUE THREAD

**Issue by Susmit-A** [tensorflow/tensorflow#45668]
**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): No

**Current Behaviour**
Currently, both these functions run on a single GPU, even on a multi-GPU machine. This restricts the maximim number of parallel iterations (map_fn) and the amount of memory available for mapping (both).

**Will this change the current api? How?**
This will add another parameter to `tf.map_fn` and `tf.vectorized_map` that specifies the GPUs to use for parallelizing. By default, all visible GPUs will be used.

**Who will benefit with this feature?**
Anyone having a setup with two or more GPUs can benefit from this feature.

**Any Other info.**
For simple parallelism, this may even make it possible to call a model on multiple GPUs without GPU Strategy APIs.

**Comment by rmothukuru** [comment]
@Susmit-A,
Sorry for the delayed response.  Can you please refer to the documentation of [Distribute Strategy](https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy) and let us know if it helps? Thanks!

**Comment by tilakrayal** [comment]
@Susmit-A,
Stateful dataset transformations are currently not supported with **tf.distribute.experimental_distribute_dataset or tf.distribute.distribute_datasets_from_function**. Any stateful ops that the dataset may have are currently ignored. For example, if your dataset has a **map_fn** that uses [tf.random.uniform](https://www.tensorflow.org/api_docs/python/tf/random/uniform) to rotate an image, then you have a dataset graph that depends on state (i.e the random seed) on the local machine where the python process is being executed.
https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy
Thank you!
