### ISSUE TITLE
Allow user to control amount of GPU memory consumed

### ISSUE THREAD

**Issue by DC-Swind** [tensorflow/tensorflow#4566]
Environment:
~tensorflow 0.10 
~NVIDIA K80 GPU server. 
~ubuntu 14.04

I do not change the code which is download from this repository.
When I run ptb_word_lm.py, it takes up all my GPU memory (from device gpu:0 to device gpu:15). Is it a bug? How could I fix it?

Thanks a lot in advance!
Swind

**Comment by jmchen-g** [comment]
Do you have 16 GPUs in your machine? Once a GPU is used by TF, it will grab all its memory.

**Comment by DC-Swind** [comment]
Actually I have 8 K80 physical GPUs which can be used as 16 GPUs.  GPU:0 is used by TF, but it will grab all GPUs' memory.(from gpu:0 to gpu:15)

**Comment by yaroslavvb** [comment]
check out http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory and CUDA_VISIBLE_DEVICES

**Comment by DC-Swind** [comment]
Thank you for your response, CUDA_VISIBLE_DEVICES works.
But I think it is still a question (or a bug in a way) about TF 0.10, I hope it will be solved in the following versions of TF. For example, I hope that TF can provide an interface to set CUDA_VISIBLE_DEVICES and recovers the original value of CUDA_VISIBLE_DEVICES after running. Or the code
with tf.device('/gpu:13'):
can control the usage of gpu memory. It seems that this code just controls the usage of gpu calculation now. When I use this code, ptb_word_lm.py just use gpu:13 for calculation but takes up all my GPU memory from gpu:0 to gpu:15.

Thanks again

**Comment by aselle** [comment]
@jmchen-g, I've made this into a feature request, retitled and assigned to you based on the previous comment by  @DC-Swind.

**Comment by aselle** [comment]
@zheng-xq

**Comment by yaroslavvb** [comment]
What's wrong with using `CUDA_VISIBLE_DEVICES`? There may be performance implications if you wait to initialize GPU memory pool until device is declared

**Comment by zheng-xq** [comment]
To control which GPU you want to use, use CUDA_VISIBLE_DEVICES

To control how much GPU memory you want to use: per_process_gpu_memory_fraction

https://github.com/tensorflow/tensorflow/blob/d24e64227653ab3cab7405c79ca166063a42f0ff/tensorflow/python/kernel_tests/sparse_xent_op_test.py#L262

**Comment by aselle** [comment]
We should probably add this to the documentation... maybe here? https://www.tensorflow.org/versions/r0.11/how_tos/using_gpu/index.html
Or is it already in it, and I just can't find it.

**Comment by carlthome** [comment]
Can you require a specific amount of bytes instead of a fraction? I don't know what GPU will be used, and would like to reserve 100 MB when starting a session.

**Comment by allannk** [comment]
I'll second Carlthome's request here. Working with multiple machines with (very) differing amount of GPU memory is hard, since it seems I can only set it to a fraction of the available memory, causing it to fail on our GPU monster that also run other tasks.

Alternatively, is there a way to grab the total GPU memory? CUDA calls get blocked by StreamExecutor, and I cannot seem to find a way to achieve this using the latter.
