### ISSUE TITLE
tensorflow/contrib/makefile/download_dependencies.sh fails to parse workspace.bzl

### ISSUE THREAD

**Issue by tomasreimers** [tensorflow/tensorflow#4567]
Hi, 

In download_dependencies.sh we grep tensorflow/workspace.bzl in order to determine which Eigen to download. We do this using the command `grep -o 'http.*bitbucket.org/eigen/eigen/.*tar\.gz' tensorflow/workspace.bzl` which we then proceed to try and curl and untar (ln22).  

Due to the new format of workspace.bzl, that grep returns `http://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz` which will download a 404 from bitbucket. Can we please update the makefile to account for this?

Thanks,
Tomas

**Comment by Bleyddyn** [comment]
I see the same error on both Mac OS 10.11.16 and Raspbian. Clean git checkout of Tensorflow in both cases.

$ uname -a
Darwin XXXX.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

$ tensorflow/contrib/makefile/download_dependencies.sh
downloading http://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Ripley:tensorflow andrew



$ uname -a
Linux raspberrypi 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux

$ tensorflow/contrib/makefile/download_dependencies.sh
downloading http://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by concretevitamin** [comment]
It's fixed in master, commit 1d9ca7bbea8f41d38f5dc57fd3fe4ee15c4aab04.
