### ISSUE TITLE
tensorflow_text.BertTokenizer not giving correct offset values in strings that have special characters

### ISSUE THREAD

**Issue by Doyel** [tensorflow/tensorflow#45684]
Is there a bug in tensorflow_text.BertTokenizer()?
------------------------

Please let me know if I am mistaken. I will close the issue.

System information

-  Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow): Yes

-   OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (using a TPU worker through a hosted runtime)

-   Exact command to reproduce: Please see the below code.

Describe the problem:

I am using the SQUAD dataset for a BERT project. I needed offsets for each wordpiece token and thus decided to use the BertTokenizer class from tensorflow_text. A lot of the instances in the dataset have special characters like Greek letters, etc. In each sentence that contains such special characters, I noticed that the tokenizer is messing up the offsets of tokens that come after the special character.

Source code:

```
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

# Get the vocab file
tfhub_handle_encoder = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3"
test_encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name='encoder')
vocab_file = test_encoder.resolved_object.vocab_file.asset_path.numpy()

vocab_file = vocab_file.decode("utf-8")
lower_case = test_encoder.resolved_object.do_lower_case.numpy()

# String has a Greek alphabet
mystr = u"The difference in the above factors for the case of θ=0 is the reason that most broadcasting uses vertical polarization.".encode('UTF-8')
mystr = tf.constant(mystr)  # mystr is a unicode string tensor

print(mystr.numpy().decode("utf-8"))           # θ gets printed correct
print(mystr.numpy())                                     # Prints the utf-8 encoding of θ
print(tf.strings.substr(mystr, pos=80, len=12, unit='UTF8_CHAR').numpy())    # The token 'broadcasting' starts at offset 80
print(tf.strings.substr(mystr, pos=44, len=4, unit='UTF8_CHAR').numpy())      # The token 'case' starts at offset 44

bert_tokenizer = text.BertTokenizer(vocab_lookup_table=vocab_file, lower_case=lower_case)
(tokens, offset_starts, offset_limits) = bert_tokenizer.tokenize_with_offsets([mystr])
context_offsets = tf.stack([offset_starts.flat_values, offset_limits.flat_values], axis=-1)
context_offsets = context_offsets.numpy()

print(context_offsets)
```

Output:

The BertTokenizer correctly detects the starting offset for 'case' to be 44 but messes up the starting offset for 'broadcasting' (it thinks the starting offset is 81). Please see the below output:

```
The difference in the above factors for the case of θ=0 is the reason that most broadcasting uses vertical polarization.
b'The difference in the above factors for the case of \xce\xb8=0 is the reason that most broadcasting uses vertical polarization.'
b'broadcasting'
b'case'
[[  0   3]
 [  4  14]
 [ 15  17]
 [ 18  21]
 [ 22  27]
 [ 28  35]
 [ 36  39]
 [ 40  43]
 **[ 44  48]**    # 'case' starts at offset 44
 [ 49  51]
 [ 52  54]          # The tokenizer reads θ as two tokens. How do we change this behavior?
 [ 54  55]
 [ 55  56]
 [ 57  59]
 [ 60  63]
 [ 64  70]
 [ 71  75]
 [ 76  80]
 **[ 81  93]**   # 'broadcasting' starts at offset 80, not 81
 [ 94  98]
 [ 99 107]
 [108 113]
 [113 120]
 [120 121]]
```

**Comment by ravikyram** [comment]
@Doyel 

Please, help me with colab link or reproducible code with supporting files.It helps me in localizing the issue faster.I am not able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0efaf387d7d2d4e0ecded3048dbdfd52/untitled576.ipynb).Thanks!

**Comment by Doyel** [comment]
Thank you for taking up this bug. I have created an updated github gist [here](https://colab.research.google.com/gist/Doyel/002bca423a3083db48a8e447e24f32f5/untitled576.ipynb)

Please let me know if you need any additional information. Thank you again!

**Comment by jvishnuvardhan** [comment]
@Doyel Looks like this is more related to `tensorflow-text`. So, can you please post in their repo [here](https://github.com/tensorflow/text). Thanks!

**Comment by gcuder** [comment]
Has this issue been fixed?
