### ISSUE TITLE
ERROR on running frozen.pb at tf2.x (google.protobuf.message.DecodeError: Error parsing message )

### ISSUE THREAD

**Issue by seongkyun** [tensorflow/tensorflow#45685]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Ubuntu 18.04 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow2.3.1
- Python version: python3.6
- CUDA/cuDNN version: CUDA 10.1, cuDNN7.6
- GPU model and memory: 8 GiB

I have my pytorch model and converted it to onnx model.
Nextly, it is converted to tf2.3.1 saved_model.pb (including variables folder with data files) type model using onnx-tf and I checked it ran perfectly. :)

Now, I converted it to frozen.pb type model following here: https://stackoverflow.com/questions/59657166/convert-frozen-model-pb-to-savedmodel
and finally got the frozen_model.pb file.
the converting code is below:
<pre><code>
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
from tensorflow.lite.python.util import run_graph_optimizations, get_grappler_config
import numpy as np

OD_SAVED_DIR = "./od_tf_model"

OD_FROZEN_DIR = "./frozen_models/od"

def frozen_keras_graph(func_model):
    frozen_func, graph_def = convert_variables_to_constants_v2_as_graph(func_model)

    input_tensors = [
        tensor for tensor in frozen_func.inputs
        if tensor.dtype != tf.resource
    ]
    output_tensors = frozen_func.outputs
    graph_def = run_graph_optimizations(
        graph_def,
        input_tensors,
        output_tensors,
        config=get_grappler_config(["constfold", "function"]),
        graph=frozen_func.graph)

    return graph_def
    
def convert_saved_model_to_pb(path_to_saved_model, path_to_frozen_model):
    model_dir = path_to_saved_model
    model = tf.saved_model.load(model_dir)
    func_model = model.signatures["serving_default"]
    graph_def = frozen_keras_graph(func_model)
    tf.io.write_graph(graph_def, path_to_frozen_model, 'frozen_graph.pb')
    
convert_saved_model_to_pb(OD_SAVED_DIR, OD_FROZEN_DIR)

</code></pre>

Now, I am trying to run frozen_model.pb on my tensorflow 2.3.1 but got an error.

<pre><code>
...
graph_def = tf.compat.v1.GraphDef()
loaded = graph_def.ParseFromString(open('path/to/frozen/pb/file/frozen_model.pb','rb').read())
...
</code></pre>

and got following error

<pre><code>
Traceback (most recent call last):
  File "run_frozen.py", line 392, in <module>
    loaded = graph_def.ParseFromString(open(PB_MODEL_PATH,'rb').read())
google.protobuf.message.DecodeError: Error parsing message
</code></pre>

is anyone solved this problem?

i.e) running saved_model.pb file on tensorflow 2.3.1 code is below:
<pre><code>
model = tf.saved_model.load('path/to/saved/model/including/folder')
    infer = model.signatures["serving_default"]
    outputs = infer(images)
</code></pre>

**Comment by amahendrakar** [comment]
@seongkyun,
On running the given code snippet, I am facing an error stating `OSError: SavedModel file does not exist at: ./od_tf_model/{saved_model.pbtxt|saved_model.pb}`.

In order to reproduce the issue reported here, could you please provide the complete code along with all the files required to run the code. Thanks!

**Comment by seongkyun** [comment]
I think the tf2.x saved model to tf1.x frozen model process is done wrongly.
