### ISSUE TITLE
Problem with installing Tensorflow on Anaconda

### ISSUE THREAD

**Issue by Lysapala** [tensorflow/tensorflow#45688]
**System information**
- Mac OS 11.0.1 (Big Sur)
- TensorFlow installed from Anaconda
- TensorFlow version: 2.0
- Python version: 3.8.5 and 3.7.9
- Installed using Conda
- GPU model and memory: Intel 3 GHz 6-Core i5 Processor 

Hello I have a problem with anaconda and tensorflow. I tried to install tensorflow on Python 3.8.5 but then I get always an error. So I downgraded Python to 3.7.9 and then I was able to install tensorflow. But when I run a script by using tensorflow I get the warning, that my processor is not optimized for tensorflow (I'm using a intel i5 3GHz 6-core processor on my mac). I tried it with the steps in the following link, but it still don't work.
https://towardsdatascience.com/optimize-your-cpu-for-deep-learning-424a199d7a87
How can I run Tensorflow on my computer?

Thank you for your help.

**Comment by amahendrakar** [comment]
@Lysapala,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!

**Comment by Lysapala** [comment]
Okay, thanks. I thought it is a tensor flow-problem because of the processor-issue.

**Comment by amahendrakar** [comment]
Marking the issue as closed since the installation involves Anaconda. Thanks!
