### ISSUE TITLE
StringLookup on GPU and disable_eager_mode gives incosistent results

### ISSUE THREAD

**Issue by IsaacDayan** [tensorflow/tensorflow#45687]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Unknown
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: release 10.1, V10.1.243
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When using StringLookup and GPU and disable_eager_mode, on each run I get different results - accuracy, (minimal reproducible code).
On training, the trained model don't converge.
On CPU, or when eager mode in enabled, I get consistent results.

**Describe the expected behavior**

consistent accuracy - results among runs (on GPU)

**Standalone code to reproduce the issue**

updated link:
https://colab.research.google.com/gist/IsaacDayan/85c8c7492b6a2f80857ee1795f1d8e45/stringlookupdiscrepancyaccuracybetweeneagerandgraphminimal.ipynb

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@IsaacDayan 

Will it be possible to share the supporting files to reproduce the issue. It helps us in localizing the issue faster. Thanks!

**Comment by IsaacDayan** [comment]
@ravikyram 

Updated colab . Now it download files from github

https://colab.research.google.com/gist/IsaacDayan/85c8c7492b6a2f80857ee1795f1d8e45/stringlookupdiscrepancyaccuracybetweeneagerandgraphminimal.ipynb
