### ISSUE TITLE
Download dependencies to install tensorflow from source on Mac

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorflow#4568]
### Environment info
Operating System: OS X 10.11.6

Installed version of CUDA and cuDNN: 
No

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) :
6218ac2be3cc530da866ec32da4cb86c6ac5bb85

2. The output of `bazel version`
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:58:27 2016 (1470304707)
Build timestamp: 1470304707
Build timestamp as int: 1470304707

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
tensorflow/contrib/makefile/download_dependencies.sh

### What other attempted solutions have you tried?
I thought it was some problem that I havent install the tar in my Mac, but it didnt help

### Logs or other output that would be helpful
When i run the command line like above, I got some error which indicate it failed to download eigen.

downloading http://bitbucket.org/eigen/eigen/get/" + eigen_version + ".tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

Can you help me?  I am new to tensorflow

**Comment by tomasreimers** [comment]
Seems to be the same as: https://github.com/tensorflow/tensorflow/issues/4567

**Comment by anbai106** [comment]
Hi, thanks for your answer, actually, I just follow the tutorial for ios application:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile
and also, I install tensorflow with Docker container, So if I want to continue to the IOS application implement, what should I do, just follow the canonical way with bazel or with the source installation, or the docker version???
Thank you in advance:)
Hao
