### ISSUE TITLE
Failed to run Benchmark 

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#45698]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): Latest Master 203f9256a596170151e4ddc93aeda6ed2905e8e7
- Python version:
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source): 10.2
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
There is no output of benchmark
```
bazel --output_user_root=$build_dir run --copt=-O3 //tensorflow/core/kernels/image:non_max_suppression_op_benchmark_test -- --benchmarks=../
```

**Describe the expected behavior**
It should output the performance data of unit test.

Isolate to this Commit: https://github.com/tensorflow/tensorflow/commit/29bb0deb26db7179eefc87e750fd8755b2c9def3 which enables the new benchmark feature.

**Comment by Leslie-Fang** [comment]
Is there any document about this new benchmark? Looking into the source code, it confuse me. Since the https://github.com/tensorflow/tensorflow/blob/c70e89e48a87fb76698beefcd9d7588b6f53c97f/tensorflow/core/platform/default/test_benchmark.cc#L55-L62 will set no args. But the benchmark do needs args to trigger the testinghttps://github.com/tensorflow/tensorflow/blob/c70e89e48a87fb76698beefcd9d7588b6f53c97f/tensorflow/core/platform/default/test_benchmark.cc#L159-L228.
I think that's why there is no output of the benchmark results.

**Comment by rohan100jain** [comment]
https://github.com/tensorflow/tensorflow/commit/bba12d0401800fbf873ea35f34517a8c47a54272 should have fixed the issue
