### ISSUE TITLE
micro: Port TRANSPOSE from lite to micro

### ISSUE THREAD

**Issue by patriklaurell** [tensorflow/tensorflow#45695]
@tensorflow/micro

This issue tracks my work porting operator TRANSPOSE from lite to micro. @advaitjain 

It will be delivered in a series of PRs.

PR 1 (merged): Refactor flatbuffer_conversions #45439 
PR 2 (merged): Refactor transpose reference op #45438 
PR 3 (merged): Copy of the reference kernel from lite to micro without changes #45843 
PR 4: Modify the micro kernel, port the tests and add the kernel to the micro build (as three separate commits) #47446

**Comment by driedler** [comment]
@patriklaurell Thanks for spearheading this kernel!

Are you certain these constants are correct?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/transpose_conv.cc#L31

From what I can tell, the TF-Lite-2.4 converter generates the input tensors as:
```
constexpr int kOutputShape = 0;
constexpr int kFilterTensor = 1;
constexpr int kInputTensor = 2;
constexpr int kBiasTensor = 3;
constexpr int kOutputTensor = 0;
```
Also need to update:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/transpose_conv.cc#L68
to:
```
  bool has_bias = node->inputs->size == 4;
  // Check number of inputs/outputs
  TF_LITE_ENSURE(context, has_bias || node->inputs->size ==3);
```

**Comment by patriklaurell** [comment]
@driedler Sorry for a delayed response. I missed your comment. Actually this issue relates to porting the TRANSPOSE op, the files you liked are for the TRANSPOSE_CONV op. It was ported here https://github.com/tensorflow/tensorflow/commit/d9841dfd9689f9c4e0bc4e1229dbc354f01ebc1b

Is it the transpose or transpose_conv you are interested in? :)

**Comment by driedler** [comment]
@patriklaurell Yes. My apologies, TRANSPOSE_CONV has the issue. Please disregard.

**Comment by dmpiergiacomo** [comment]
Hi @patriklaurell,

Which is the status of your PR5? I would need to consume TRANSPOSE from TFLM as well and I would prefer not to duplicate the effort, if you are already working on it :)

Thank you.

**Comment by dmpiergiacomo** [comment]
I created a PR [48192](https://github.com/tensorflow/tensorflow/pull/48192) that should solve this issue.

**Comment by patriklaurell** [comment]
@dmpiergiacomo sorry for a late response. I have been on vacation over the easter week. I don't know if it is still relevant but I have the code for PR5 ready locally. I have not uploaded it since it depends on the changes in PR4 #47446.

**Comment by patriklaurell** [comment]
With the merge of #47446 this issue is fixed.
