### ISSUE TITLE
iOS Build TFlite as framework

### ISSUE THREAD

**Issue by MaTriXy** [tensorflow/tensorflow#45707]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: arm64 ios
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest from master - 2.4.0
- Python version: Python 3.7.6
- Installed using virtualenv? pip? conda?:  anaconda3
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source):  12 
- CUDA/cuDNN version: NA
- GPU model and memory: NA 

**Describe the problem**
Running  build with the following command : 
```
bazel build --config=ios_fat -c opt \
  //tensorflow/lite/ios:TensorFlowLiteC_framework

```
This outputs a framework file i would like to add to my pod and distribute later. 
I've done it with previous versions but since moving to Xcode 12 i keep getting various issues.
1. Running dev version works ok but in release build results from tensor running return faulty. 
2.  Building with 
```
bazel build --config=ios_fat --ios_multi_cpus=armv7,arm64,i386,x86_64 -c opt \
  //tensorflow/lite/ios:TensorFlowLiteC_framework
```
Cause build issues where multiple c code is missing for arm64. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by thaink** [comment]
The --config=ios_fat already configure the build for all armv7,arm64,i386,x86_64.
If you want to build for some archs, you should use --config=ios without "fat": --config=ios --ios_multi_cpus=...

**Comment by yyoon** [comment]
Can you share the exact errors you're getting? If this is related to CocoaPods lint step, you might be hitting https://github.com/CocoaPods/CocoaPods/issues/10104.

**Comment by MaTriXy** [comment]
@thaink thanks - I'll change the build config and retest
@yyoon checking the lint issue thread and test again.

**Comment by MaTriXy** [comment]
Both remarks helped.
