### ISSUE TITLE
Request for a tutorial on building C++ API not pure C

### ISSUE THREAD

**Issue by busFred** [tensorflow/tensorflow#45700]
**System information**
- TensorFlow version: 2.4
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**
The [current documentation](https://www.tensorflow.org/install/lang_c) only tells user how to install TensorFlow for C API. But none of them tells how to install TensorFlow for **C++**.

**Will this change the current api? How?**
This does not change the current api. It just enables user know how to make the existing functionality available on our computer.

**Who will benefit with this feature?**
People who hate python but still wants to do machine learning with tensorflow

**Any Other info.**

**Comment by OgreTransporter** [comment]
It is actually quite simple. I build the C++ library on Windows (VS2019) like this:
```
bazel build --config=opt --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings --announce_rc tensorflow:tensorflow_cc
```

A good tutorial is available here: https://medium.com/vitrox-publication/deep-learning-frameworks-tensorflow-build-from-source-on-windows-python-c-cpu-gpu-d3aa4d0772d8

**Comment by busFred** [comment]
> It is actually quite simple. I build the C++ library on Windows (VS2019) like this:
> 
> ```
> bazel build --config=opt --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings --announce_rc tensorflow:tensorflow_cc
> ```
> 
> A good tutorial is available here: https://medium.com/vitrox-publication/deep-learning-frameworks-tensorflow-build-from-source-on-windows-python-c-cpu-gpu-d3aa4d0772d8

I ended up using [this one](https://github.com/FloopCZ/tensorflow_cc/tree/tf-v2.4.0) to install tensorflow c++ API on my computer.
The only problem I ran into is bazel couldn't find python despite python location was previously configured with ./configure. By brute force, I symliink the location where bazel is looking for python to the directory where python is actually being installed and solved the problem.

**Comment by OgreTransporter** [comment]
> The only problem I ran into is bazel couldn't find python despite python location was previously configured with ./configure. By brute force, I symliink the location where bazel is looking for python to the directory where python is actually being installed and solved the problem.

Another option could be to set the environment variables `PYTHON_BIN_PATH` and `PYTHON_LIB_PATH` before ./cofigure as in the [CI script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/windows/bazel/common_env.sh).

**Comment by aselle** [comment]
C++ is the standard language of TensorFlow, so it is not under "bindings." So just follow the build instructions. The point however is that building C++ libraries on different versions of the compilers is generally not safe, so that is why we don't really have a c++ only archive.
