### ISSUE TITLE
Dot layer incomplete description

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#45706]
### Description of issue (what needs changing):
The dot layer accepts (0,0) as an argument for the axes, which produces the same result as (1,1). This behavior is not documented and more confusing than helpful since it suggests that the numbering of the axes starts at zero, but it actually starts at one. Since (0,0) as an argument seems to work, it suggests that also combination like (0,1) or (0,2) should work, but in this cases errors are produced. It might be better to not accept (0,0) as input for the axes, or to specify the motivation behind it in the documentation. 

Moreover, it would great to clarify the requirements for matching axes sizes in the documentation. Right now the documentation only states that the size of the selected axes must match, but e.g., also the first axes must mach otherwise an error is produced.

**Comment by rmothukuru** [comment]
@rschumi0,
[ Keras Dot Layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dot) doesn't accept **`(0,0)`** for **`axes`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/c47fafc91a069b557dffc9b020ea0169/dot_layer.ipynb) which gives Value Error. 

Can you please confirm if we can close this issue as the functionality is as expected? Thanks!

**Comment by rschumi0** [comment]
Yes, it seems it's not an issue any more with the latest version. I initially had an older version.
