### ISSUE TITLE
Tensorflow website stating CUDNN v5 required, but my version working only on v5.1

### ISSUE THREAD

**Issue by bibhashthakur** [tensorflow/tensorflow#4571]
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#requirements
states that cuDNN v5 is required. So I tried to compile the basic example. This error was shown.
_Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration._

It worked when I upgraded cuDNN to v5.1. Please update the said webpage if possible. 

Operating System: Ubuntu Linux 14.04 LTS

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Sep 24 20:03 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Sep 24 20:03 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.3
-rwxr-xr-x 1 root root 59909104 Sep 24 19:10 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rwxr-xr-x 1 root root 60696704 Jun 10 13:48 /usr/local/cuda/lib64/libcudnn.so.5.1.3
-rw-r--r-- 1 root root 59715990 Jun 10 13:48 /usr/local/cuda/lib64/libcudnn_static.a

**Tensorflow version:**
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0

**Comment by jmchen-g** [comment]
@zheng-xq Could you take a look at this? Thanks.

**Comment by gunan** [comment]
We should update the website with this information.
All our builds have been using cudnn 5.1 for a while now.

**Comment by gunan** [comment]
Documentation is now updated.
