### ISSUE TITLE
ambiguity risk of crop_size

### ISSUE THREAD

**Issue by qazsweet** [tensorflow/tensorflow#45731]
https://github.com/tensorflow/tensorflow/blob/14793703c9fde08b643892b1f9d2504488f2d5f4/tensorflow/python/ops/image_ops_impl.py#L4698

Based on the introduction of this operator, crop_height, crop_width are supposed to stand for the size of output, which literally the middle step size of this op

**Comment by aaronmondal** [comment]
I agree. This should probably be renamed to `output_size` or `out_size`, and the documentation updated accordingly. Would you mind filing a PR?

**Comment by amahendrakar** [comment]
@qazsweet,
As @aaronmondal suggested, could you please submit a PR for this change? Thanks!
