### ISSUE TITLE
No tensorflow lite 2.4.0 pre-built libraries

### ISSUE THREAD

**Issue by kafan1986** [tensorflow/tensorflow#45735]
**System information**
- OS Platform and Distribution: Android
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.4.0

**Describe the problem**
Can not find pre-built libraries for tensorflow lite 2.4.0 at the below location. Latest available version is older 2.3.0

https://bintray.com/google/tensorflow/tensorflow-lite

**Comment by mihaimaruseac** [comment]
They should exist now:

https://bintray.com/google/tensorflow/tensorflow-lite/2.4.0

**Comment by jdduke** [comment]
Note that, while the libraries have been uploaded, we're experiencing some issues syncing these libraries with JCenter. Hoping to resolve shortly.

**Comment by kafan1986** [comment]
Yes. Works now. Thanks!
