### ISSUE TITLE
Why is the object_C library empty

### ISSUE THREAD

**Issue by KeepSmileEveryDay** [tensorflow/tensorflow#45738]

**Comment by ravikyram** [comment]
@KeepSmileEveryDay 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Can you please elaborate about the issue & the context.Will it be possible to provide related code.Thanks!

**Comment by KeepSmileEveryDay** [comment]
@ravikyram 
This is my procedure, thank you!
<img width="558" alt="WechatIMG53" src="https://user-images.githubusercontent.com/14270188/102335634-22d18700-3fcb-11eb-90e7-f3904dd8e2f5.png">
![WechatIMG54](https://user-images.githubusercontent.com/14270188/102335646-26650e00-3fcb-11eb-85d4-ae2b98b66bf9.jpeg)

**Comment by KeepSmileEveryDay** [comment]
I saw that the Demo was written in SWIFT language. If I wanted to write in Object-C language, the above error would appear through normal Cocoapods mode

**Comment by ravikyram** [comment]
@KeepSmileEveryDay 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by KeepSmileEveryDay** [comment]
First, I searched TensorFlow through Pod Search and got the result of the first picture above. Later, I searched pod 'TensorFlow 'in podfile. Pod Install then gets the result of the second image above.

**Comment by ymodak** [comment]
TF 0.0.4 is obsolete, Please try to switch to recent TF version 2.3 or 2.4
