### ISSUE TITLE
How to specify `force_gpu_compatible` in TensorFlow 2.x?

### ISSUE THREAD

**Issue by Jianbing-D** [tensorflow/tensorflow#45730]
In TF 1.x, we can use these codes to force CPU tensor located on pinned CPU memory, whose bindwidth will be higher than pageable CPU memory.
```python
config = tf.ConfigProto()
config.gpu_options.force_gpu_compatible = True
...
with tf.Session(config = config) as sess:
    ...
```

But in TF 2.x, what is the mechanism to force CPU tensor located on pinned memory?

**Comment by amahendrakar** [comment]
@Jianbing-D,
Instead of `config = tf.ConfigProto()`, please try `tf.compat.v1.ConfigProto` and check if it works. 

Please check [this gist](https://colab.research.google.com/gist/amahendrakar/ca4186d881a51f9d09242dfabd322f4b/45730.ipynb) for reference. Thanks!

**Comment by Jianbing-D** [comment]
@amahendrakar Thanks for clearifying.
But what I want to ask is how to force tensor to located on CPU pinned memory with TF 2.x APIs(rather than via `tf.compat.v1` to use TF 1.x APIs in TF 2.x).

BTW, I want to accelerate the tensor transition from CPU->GPU, therefore CPU pinned memory is what I want for higher performance. 
For example, this [issue](https://github.com/tensorflow/tensorflow/issues/44836) is related to bad performance on CPU pageable memory.

**Comment by rmothukuru** [comment]
@Jianbing-D,
You can try using **`tf.config.experimental.set_visible_devices(gpus[0], 'GPU')`**. Please refer [documentation of GPU](https://www.tensorflow.org/guide/gpu) for more information. Thanks!

**Comment by Jianbing-D** [comment]
> @Jianbing-D,
> You can try using **`tf.config.experimental.set_visible_devices(gpus[0], 'GPU')`**. Please refer [documentation of GPU](https://www.tensorflow.org/guide/gpu) for more information. Thanks!

Thanks. But I think your reply is irrelevant to my issue. That method only set the `visible_devices`, while tensors still can be allocated on CPU pageable memory rather than CPU pinned memory, which is what I really wanted. 

You can try the following code snippet to verify it:
```python
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices("GPU")
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')

a = tf.constant(0)
print(a.device)
```

**Comment by tomerk** [comment]
To clarify: are you looking to use the tensors on gpu, or do you specifically want to place tensors on CPU (w/ cpu compute) while pinning them in memory so they never page out to disk?

---------------
If you're just looking to use gpus without dealing with manual device control, you can try distribution strategies:
https://www.tensorflow.org/guide/distributed_training
(There's a one device strategy that works even if you have just one GPU)

Or if you need to you can manually control the devices your tensors are placed on as described in the previously-linked gpu guide:
https://www.tensorflow.org/guide/gpu

---------------
If you're looking to place your tensors and computation on the CPU *and* pin them in memory so nothing pages out to disk even when your virtual memory is greater than your allocated program memory... off the top of my head I'm not sure if TF has ever had support for that. I would have to ask around.

**Comment by Jianbing-D** [comment]
Thanks @tomerk , 
> If you're looking to place your tensors and computation on the CPU and pin them in memory so nothing pages out to disk even when your virtual memory is greater than your allocated program memory... off the top of my head I'm not sure if TF has ever had support for that. I would have to ask around.

This is what I am looking.

**Comment by sanjoy** [comment]
@agarwal-ashish suggested a fix in our internal tracker: `tf.compat.v1.enable_eager_execution` currently allows passing in a `ConfigProto`, which could be a workaround for now.

**Comment by Jianbing-D** [comment]
> @agarwal-ashish suggested a fix in our internal tracker: `tf.compat.v1.enable_eager_execution` currently allows passing in a `ConfigProto`, which could be a workaround for now.

Thanks, I will try.
