### ISSUE TITLE
[Build] [ROCm] [Bazel] /opt/rocm/.info/version-dev file not found

### ISSUE THREAD

**Issue by acxz** [tensorflow/tensorflow#45733]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.9.1
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.7.1
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: N/A
- ROCm version: 3.10.0
- GPU model and memory:

**Describe the problem**

When building I am getting the following error:
```
INFO: Repository local_config_rocm instantiated at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/WORKSPACE:19:16: in <toplevel>
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/tensorflow/workspace.bzl:102:19: in tf_repositories
Repository rule rocm_configure defined at:
  /home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl:794:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 775, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 534, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 388, column 30, in _get_rocm_config
		config = find_rocm_config(repository_ctx, find_rocm_config_script)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 366, column 41, in find_rocm_config
		exec_result = _exec_find_rocm_config(repository_ctx, script_path)
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/gpus/rocm_configure.bzl", line 362, column 19, in _exec_find_rocm_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/home/acxz/vcs/git/github/rocm-arch/tensorflow-rocm/src/tensorflow-2.4.0-rocm/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_rocm//rocm': Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
ERROR: no such package '@local_config_rocm//rocm': Repository command failed
ERROR: ROCm version file "/opt/rocm/.info/version-dev" not found
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. git clone
2. `export TF_NEED_ROCM=1`
3. `./configure`
4. 
```
  bazel \
        build \
          //tensorflow:libtensorflow.so \
          //tensorflow:libtensorflow_cc.so \
          //tensorflow:install_headers \
          //tensorflow/tools/pip_package:build_pip_package
      bazel-bin/tensorflow/tools/pip_package/build_pip_package --gpu "${srcdir}"/tmpoptrocm
```

To be exactly precise I am using the following build script (PKGBUILD):
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tensorflow-rocm

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Downstream issue: https://github.com/rocm-arch/tensorflow-rocm/issues/17

It could be that rocm 3.10 doesn't ship with `/opt/rocm/.info/version-dev` or that the Arch Linux package doesn't not ship with `/opt/rocm/.info/version-dev` files.

Could someone check if `/opt/rocm/.info/version-dev` exists in a ubuntu installation of rocm-3.10 and if so which package it is installed under?
If not then we should remove this check in our bazel code and figure out someother way of obtaining the rocm version: https://github.com/tensorflow/tensorflow/blob/9e7a15398b6e16fdf9b684aaa1437d1d3c76a5ab/third_party/gpus/find_rocm_config.py#L72-L83

**Comment by amahendrakar** [comment]
@acxz,
TensorFlow v2.4 is compatible with Python 3.6 - 3.8. Please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#linux) for more information.

Could you please check if you are facing the same issue with Python 3.8 as well? Thanks!

**Comment by acxz** [comment]
Based on the error log, the issue does not have to do with the Python versions.
I checked on Python 3.8 and am still getting the same issue.

**Comment by darjankrijan** [comment]
The version-dev file seems to be from the rocm-dev package, checked in CentOS 8:
[version-dev.txt](https://github.com/tensorflow/tensorflow/files/5725044/version-dev.txt)

RPMs are here:
https://repo.radeon.com/rocm/centos8/4.0/

Seems to be just a file with the version number and package version e.g. "4.0.0-23".
Same with ```version-libs``` and ```version-utils``` in the same ```.info``` directory.
Guess it's a good idea to add them to rocm-arch as well (in the rocm-libs and rocm-utils metapackages).

**Comment by acxz** [comment]
ahh nice find!

**Comment by acxz** [comment]
resolved with above pr
