### ISSUE TITLE
Will tf.reshape() perform extra memcopy in tensorflow gpu backend?

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#45741]
```py
mediate_op = tf.some_op(inputs)
output_op = tf.reshape(mediate_op, [128, -1])
```
In terms of device memory occupation, is `tf.reshape` performed in place (reuse the data memory of `mediate_op`)?

**Comment by ravikyram** [comment]
@ghostplant 
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us i localizing the issue faster. Thanks!

**Comment by aaronmondal** [comment]
From the docs:
> The `tf.reshape` does not change the order of or the total number of elements in the tensor, and so it can **reuse the underlying data buffer**. This makes it a fast operation independent of how big of a tensor it is operating on.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if necessary. Thanks!

**Comment by ghostplant** [comment]
Thanks! I also verified that.
