### ISSUE TITLE
TF Lite for MCU porting, why not provide the generating the static library flow.

### ISSUE THREAD

**Issue by liumengbjut** [tensorflow/tensorflow#45745]
Why not provide the generating the static library flow and link with the MCU tools environment. In this way, we only need to focus on the model generation, instead of compiling the source code for examples again and again.

Could anybody tell me the reason? Thanks so much.

**Comment by pkgoogle** [comment]
Hi @liumengbjut, can you use this to build the .so files and use that? https://www.tensorflow.org/lite/guide/build_cmake
