### ISSUE TITLE
Passing tensorflow::ops::DecodeJpeg::Attrs to the tensorflow::ops::DecodeJpeg constructor causes std::logic_error

### ISSUE THREAD

**Issue by busFred** [tensorflow/tensorflow#45748]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): It's custom code. However, it's based on this [article](https://itnext.io/creating-a-tensorflow-dnn-in-c-part-1-54ce69bbd586).
- OS Platform and Distribution: Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4
- Python version: 3.8
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc-10
- CUDA/cuDNN version: CUDA 11.2 (installed but not used)
- GPU model and memory: NVIDIA GeForce MX150

**Describe the current behavior**
Passing tensorflow::ops::DecodeJpeg::Attrs to the tensorflow::ops::DecodeJpeg constructor causes std::logic_error

console output
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

**Describe the expected behavior**
Exit without error.

**Standalone code to reproduce the issue**
```
tensorflow::Status ReadTensorFromImageFile(
    const std::string& file_name, const int input_height, const int input_width,
    const float input_mean, const float input_std,
    std::vector<tensorflow::Tensor>* out_tensors, bool writeGraph) {
  // build the graph
  tensorflow::Scope root = tensorflow::Scope::NewRootScope();
  tensorflow::ops::Placeholder input_file_name{root.WithOpName("input"),
                                               tensorflow::DataType::DT_STRING};
  tensorflow::ops::ReadFile file_reader{root.WithOpName("file_reader"),
                                        input_file_name};
  constexpr int kNumOfChannels = 3;
  tensorflow::ops::DecodeJpeg decode_file{
      root.WithOpName("decode_file"), file_reader,
      tensorflow::ops::DecodeJpeg::Channels(kNumOfChannels)};
```
Exit without error iff tensorflow::ops::DecodeJpeg::Attrs is not used.
```
tensorflow::ops::DecodeJpeg decode_file{root.WithOpName("decode_file"), file_reader};
```

**Other info / logs**
gdb backtrace
```
[New Thread 0x7fffe8839700 (LWP 104836)]
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

Thread 1 "tutorial_01" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffe8a2b859 in __GI_abort () at abort.c:79
#2  0x00007fffe8cb1951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffe8cbd47c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffe8cbd4e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffe8cbd799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffe8cb425e in std::__throw_logic_error(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fffeb6b316c in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) ()
   from /usr/local/lib/libtensorflow_cc.so.2
#8  0x00007ffff5617b4c in tensorflow::SetAttrValue(absl::lts_2020_02_25::string_view, tensorflow::AttrValue*) () from /usr/local/lib/libtensorflow_cc.so.2
#9  0x00007ffff551fc13 in tensorflow::NodeDefBuilder::Attr(absl::lts_2020_02_25::string_view, absl::lts_2020_02_25::string_view) () from /usr/local/lib/libtensorflow_cc.so.2
#10 0x00007fffebceff2a in tensorflow::ops::DecodeJpeg::DecodeJpeg(tensorflow::Scope const&, tensorflow::Input, tensorflow::ops::DecodeJpeg::Attrs const&) ()
   from /usr/local/lib/libtensorflow_cc.so.2
#11 0x000055555555a095 in ReadTensorFromImageFile (file_name="../data/grace_hopper.jpg", input_height=299, input_width=299, input_mean=0, input_std=255, out_tensors=0x7fffffffd610, 
    writeGraph=true) at ../src/tutorial_01/tutorial_01.cpp:48
#12 0x0000555555559d11 in main (argc=2, argv=0x7fffffffd788) at ../src/tutorial_01/tutorial_01.cpp:22
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
