### ISSUE TITLE
Tensorflow compile failure on Power9/PPC64LE, how to pass compile flags to NVCC?

### ISSUE THREAD

**Issue by vlawhern** [tensorflow/tensorflow#45746]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RedHat 8, PPC64LE
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.3
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.7.1
- GCC/Compiler version (if compiling from source): gcc 8.3.1
- CUDA/cuDNN version: 10.2/7.6
- GPU model and memory: Tesla V100

**Describe the problem**

I get the following error when  compiling Tensorflow for IBM Power9 architectures (PPC64LE):

```/usr/include/bits/floatn.h(79): error: identifier "__ieee128" is undefined```
```/usr/include/bits/floatn.h(82): error: invalid argument to attribute "__mode__"```

Per this PyTorch github thread that had the same issue (https://github.com/pytorch/pytorch/issues/45073) you apparently need to pass in some compile flags, in particular "-mno-float128" to CC and "-Xcompiler -mno-float128" to NVCC. From the Bazel documentation you can use ``--copt/--cxxopt`` to pass in compile flags for CC but is there a way to pass in compile flags to NVCC? 

The related issue thread at https://github.com/tensorflow/tensorflow/issues/38912 unfortunately suggests this is still an open problem..

Any help would be appreciated!

**Comment by FindHao** [comment]
Facing the same problem.

According to some docs from tensorflow, we can pass ` --copt=-nvcc_options=disable-warnings ` to bazel to disable nvcc warnings. How about passing `--copt=-nvcc_options=Xcompiler --copt=-nvcc_options=mno-float128` to  bazel?

**Comment by vlawhern** [comment]
So I still run into compiling errors when trying to pass in ``-nvcc_options`` through ``--copt``, it seems like those options don't get fully propagated through bazel, specifically I ran into problems compiling nccl-related files

I was however able to successfully compile Tensorflow 2.3 with GPU support on PPC64LE by directly modifying the bazel build files for tensorflow and nccl. In particular:

1. Replace these lines of tensorflow.bzl (https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/tensorflow.bzl#L1380-L1383) with
```
        "@local_config_cuda//cuda:using_nvcc": ([
            "-nvcc_options=relaxed-constexpr",
            "-nvcc_options=ftz=true",
            "-nvcc_options=compiler-options=-mno-float128",
        ]),
```
2. Replace these lines of build_defs.bzl.tpl from nccl (https://github.com/tensorflow/tensorflow/blob/r2.3/third_party/nccl/build_defs.bzl.tpl#L46-L51) with

```
        "@local_config_cuda//cuda:using_nvcc": [
            "-nvcc_options",
            "relocatable-device-code=true",
            "-nvcc_options",
            "-nvcc_options=compiler-options=-mno-float128",
            "ptxas-options=" + maxrregcount,
        ],
```

3. Then compile Tensorflow with the following call:
```
 bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --cxxopt='--machine-no-float128' --host_cxxopt='--machine-no-float128' --copt='--machine-no-float128' --host_copt='--machine-no-float128' --verbose_failures
```

The key is passing in the compile flag ``-mno-float128`` since GCC 8.3.1 for RHEL 8 for PPC64LE architecture is configured with ``--with-long-double-128`` which is causing problems when compiling certain ops. I suspect this should also work for Tensorflow 2.4, but I haven't tried it yet. 

Perhaps there should be a way to automatically add these flags when compiling Tensorflow for PPC64LE...

**Comment by mihaimaruseac** [comment]
You can add configs into `.bazelrc`

**Comment by bhack** [comment]
@vlawhern If you want you can try prepare a PR for that specific GCC version on:

https://github.com/tensorflow/tensorflow/blob/aa92d1d7a9bd24e157326bd3dc18945ab5ca5b78/configure.py#L522-L524

**Comment by bhack** [comment]
Also probably it seems it is fixed with CUDA11 (and so with TF 2.4.0). Please check https://github.com/LLNL/blt/issues/341#issuecomment-620810990

If this is fixed with TF 2.4.0 we could close this as we will not do specific TF 2.3.x backports. @vlawhern Can you try with plain TF 2.4.0?

**Comment by vlawhern** [comment]
@bhack I tried compiling TF 2.4.0 but was unable to due to a separate issue with Eigen (see #44626), which appears to be unresolved at this point. So I'm not sure if this issue is fixed with TF 2.4 right now..

**Comment by bhack** [comment]
@vlawhern You can ping that ticket for an update.

**Comment by vlawhern** [comment]
Just circling back to this...

I successfully compiled a newer version of TF (TF 2.5.2, CUDA 11, cuDNN 8) without problems and without having to do the fixes I described above. So I believe this is no longer an issue (and the problems I had with Eigen were resolved in https://github.com/tensorflow/tensorflow/issues/44626).
