### ISSUE TITLE
int8 quantization with int16 activations support for TFMicro and Cortex-M

### ISSUE THREAD

**Issue by oleksii-abramenko** [tensorflow/tensorflow#45759]
Hello community,

There is a support of int16 activations in TFLite, which helps a lot in keeping precision of an int8-quantized network, but not in TFMicro.

It should be noted that the TFMicro users are ones who will benefit from this features the most, because the platforms where one can run standard TFLite interpreter are often powerful enough/have enough memory so that things can often be done without any quantization at all, so this may not bring as much added value for the deployment on TFLite-compatible systems in this case(but it definitely does for research).

For TFMicro int16 activations support is absolutely paramount.

Just wondering if there is a plan to put this feature into production soon?

**System information**
- TensorFlow version (you are using):
TF 2.4rc3

- Are you willing to contribute it (Yes/No):
No

**Describe the feature and the current behavior/state.**
When the model with int8 weights and int16 activations is run with TFMicro interpreter the following error is observed: "Node X failed to prepare"

**Will this change the current api? How?**
No, this shouldn't change APIs. It is already supported by TFLite but not by TFMicro.

**Who will benefit with this feature?**
TFMicro users will benefit from this feature.

**Any Other info.**

**Comment by tilakrayal** [comment]
@oleksii-abramenko,
TensorFlow Lite  supports converting **activations to 16-bit integer values and weights to 8-bit integer values** during model conversion from TensorFlow to TensorFlow Lite's flat buffer format. Kindly find the gist of it [here](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant_16x8.ipynb).

Have you got the chance to check that there was a pull request raised for the similar feature to be implemented for **tflite-micro** where int16 activation case into the MNIST LSTM example was added.
https://github.com/tensorflow/tflite-micro/pull/1755
https://github.com/tensorflow/tflite-micro/pull/1735

Support float, int8 activation int8 weight and int16 activation int8 weight quantized unidirectional LSTM models. Use template and function overloading to remove code duplications -- https://github.com/tensorflow/tflite-micro/pull/1682
Thank you!
