### ISSUE TITLE
SVD Function has (very) different GPU and CPU outputs 

### ISSUE THREAD

**Issue by eddymina** [tensorflow/tensorflow#45756]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab Notebook 
-   **TensorFlow installed from (source or binary)**: pip install v2.3.0
-   **Python version**: Colab Default 3.6.9
-   **CUDA/cuDNN version**: 10.1, V10.1.243
-   **GPU model and memory**: Colab Default GPU (Persistence-M) ~15GB
-   **Exact command to reproduce**:
```python
import tensorflow as tf 
import numpy as np
tf.debugging.set_log_device_placement(True)
print(tf.__version__)

A= tf.random.uniform((50,9))

with tf.device('cpu:0'):
    _ ,_, v = tf.linalg.svd(A, full_matrices=True, compute_uv=True)
    res_cpu= v[0]
    
with tf.device('gpu:0'):
    _ ,_, v = tf.linalg.svd(A, full_matrices=True, compute_uv=True)
    res_gpu= v[0]
    
np.array_equal(res_cpu,res_gpu) #this will return False but expected should be true- 
np.allclose(res_cpu,res_gpu) #this will also return False but expected should be true- 
```

### Describe the problem
Computing SVD (singular value decomp) operation on gpu matches numpy results more closely and more accurately. The cpu implementation is far off (sometimes gives nans.) I presume there maybe a different solver used but there doesn't seem to be much explanation on that in source. I would like to use the CPU method in my training pipeline because I cannot afford any more GPU cost.

**Comment by ravikyram** [comment]
@eddymina 

I have tried in TF nightly version (`2.5.0-dev20201216`) and i am not seeing any issue. Please, find the [gist here](https://colab.research.google.com/gist/ravikyram/6c7ae99c1520ede3d96bb8beaf5bd3bd/untitled580.ipynb).Please, verify once and close the issue.Thanks!

**Comment by foxik** [comment]
@ravikyram In your gist, the operations in TF nightly are executed always on CPU:
```
2.5.0-dev20201216
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Svd in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Svd in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
```
Therefore, the results are not conclusive.

**Comment by foxik** [comment]
Note that according to https://github.com/googlecolab/colabtools/issues/1574 , Colab does not offer CUDA 11, so TF 2.4 and TF nightly does not use GPUs on colab.

That can be verified by using
```python
print(tf.test.gpu_device_name())
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```
which indeed shows
```

Num GPUs Available:  0
```
on TF 2.4.

**Comment by eddymina** [comment]
@ravikyram I would prefer to use tf 2.3 if possible as I am unsure what differences and other potential bugs exist with bleeding edge tf and @foxik brings up a good point as to why.

**Comment by saikumarchalla** [comment]
Still an issue in TF 2.5 stable version on GPU. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/bc9b27b6f0a297bee1b59061169a1762/untitled89.ipynb).Thanks!

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220714. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/abbde46a1175c42cbce9a69c3be12db4/untitled432.ipynb). Thank you!

**Comment by jmhuttun** [comment]
I don't think that this should be necessarily considered as a bug. Remember that, as eigenvalue decomposition, singular value decompositions is not unique. If you inspect v's given by cpu and gpu version, you can see that those are same except some of columns are multiplied by -1. This can be expected as if u and v are singular vectors, then -u and -v are also.
