### ISSUE TITLE
[TensorFlow 2.x]'s model from OFFICAL DOC cannot freeze in any way( included [frozen_graph.py] in offical doc) [TenseorFlowSharp]. [C#] [Python][frozen model] CSharp Transfer Learning

### ISSUE THREAD

**Issue by Rick-712N** [tensorflow/tensorflow#45758]
Sorry to trouble you guys, but i cost days and problem dosen't gone :(

Description: As a outsider of mechine learning, i use ml.net before. And there's a project need ML on Raspberry Pi, so it won't work( Linux Arm is not sueported).
Instead of ML.net, i plan to use **TensorFlowShar****p**(TF#, 'cause i muna use C# to write GUI and other things), and it **need a FROZEN MODEL**. So as a idot of mechin-learning, i followed officical docs to built a image classifier.(Details: _Anaconda_, _TensorFlow 2.3_, docs here: [https://tensorflow.google.cn/tutorials/images/transfer_learning](url) )

Then just to use a code like this of the end of the codes to get the model file:
keras_model_path = './keras_save'
model.save(keras_model_path)
h5_save_path = 'model.h5'
model.save(h5_save_path)

The difficulity is to make the 'h5' or savedmodel to be a frozen model.
The official code "frozen_graph" dosent work, and I used many scripts but failed.
The last code in my latop looks like this( From Lei Mao, thank you).

Follow the code, i put the model firstly to create ConcreteFunction, and then get frozen ConcreteFunction, finally write it on the hard drive.

For this clip of code, question is : **tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.**
In this place
 `frozen_func = convert_variables_to_constants_v2(full_model) # Error`

Freeze code like this:
`import matplotlib.pyplot as plt`
`import numpy as np`
`import os`
`import tensorflow  as tf`
`from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2`
`from tensorflow import keras`

`model = keras.models.load_model('keras_save')`

`# 将 Keras 模型转换为 ConcreteFunction`
`full_model = tf.function(lambda x: model(x))`
`full_model = full_model.get_concrete_function(tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))`

`# 获取 冻结的 ConcreteFunction`
`frozen_func = convert_variables_to_constants_v2(full_model) # Error`
`frozen_func.graph.as_graph_def()`

`layers = [op.name for op in frozen_func.graph.get_operations()]`
`print("-" * 50)`
`print("Frozen model layers: ")`
`for layer in layers:`
  `  print(layer)`

`print("-" * 50)`
`print("Frozen model inputs: ")`
`print(frozen_func.inputs)`
`print("Frozen model outputs: ")`
`print(frozen_func.outputs)`

`# 将冻结的图从冻结的ConcreteFunction保存到硬盘`
`tf.io.write_graph(graph_or_graph_def=frozen_func.graph,logdir="./frozen_models",name="frozen_graph.pb",as_text=False)`

I'm doubt that is there any bugs? I hope you guys could pull me a hand ...

By the way, i also TIRED to use a TensorFlowSharp method called "FromSavedModel", it returns a TFSession type object, but icannot use this way to classify image. Only secess is to make image classification from google inception .... I hope you guys could give me a hand, and now the difficultiy is to <1 export a frozen model and then use it in TF# OR
<2 use a SavedModel in TF# .

In C# of TF#， error here：
TensorFlow.TFException:“Op type not registered 'StatefulPartitionedCall' in binary running on LAPTOP-8FU28J1C. Make sure the Op and Kernel are registered in the binary running in this process.”
code is：

`//load SavedModel`
`            TFGraph _tfGraph = new TFGraph();`
`            TFSession _tfSession;`
`           using (var tmpSess = new TFSession(_tfGraph))`
`            using (var tfSessionOptions = new TFSessionOptions())`
`           using (var metaGraphUnused = new TFBuffer())`
`            {`
`                //for some reason FromSavedModel is not static`
`                _tfSession = tmpSess.FromSavedModel(tfSessionOptions, null, "tmp/keras_save", new[] { "serve" }, _tfGraph, `metaGraphUnused);`
`            }`
code is from Github also, links here:
[https://github.com/migueldeicaza/TensorFlowSharp/issues/265](url)
migueldeicaza/TensorFlowSharp/issues/265

Last recorded 12.17( Dec,17,2020) Peking Time.

**Comment by Rick-712N** [comment]
Sorry, # in Python make words so huge ...

**Comment by amahendrakar** [comment]
@Rick-712N,
frozen_graph is a TF 1.x concept. In TF2.x, the primary export format is SavedModels.

Is there any specific reason you want to export a frozen graph? Thanks!

**Comment by Rick-712N** [comment]
> @Rick-712N,
> frozen_graph is a TF 1.x concept. In TF2.x, the primary export format is SavedModels.
> 
> Is there any specific reason you want to export a frozen graph? Thanks!

Yes, i wanna run the model in **TensorFlowSharp**(TF#) which is a C# version tensorflow, but it need Frozen model. (Saved model is available but i cannot load my tf2 SavedModel in it, it might be not support TF2.x)

**Comment by Rick-712N** [comment]
BTW, i ran the official freeze_graph.py tool to transform, but error:
Code like this:

import tensorflow as tf
from  tensorflow.python.tools import freeze_graph


`with tf.compat.v1.Session() as sess:`
`    freeze_graph.freeze_graph(`
`			input_graph="", `
 `           input_saver="", `
  `          input_binary=False, `
   `         input_checkpoint="", `
    `        output_node_names="dense/BiasAdd:0", `
     `       restore_op_name="", `
      `      filename_tensor_name="", `
       `     output_graph="frozen_graph.pb",`
        `    clear_devices="", `
         `   initializer_nodes="", `
          `  variable_names_whitelist="", `
           ` variable_names_blacklist="", `
            `input_meta_graph=None, `
`            input_saved_model_dir="keras_save" `
`			)`
 `   print('Over !')`

output node name is the real output node name in my model, which is the model of the TensorFlow offical transferlearning tutorial.

error: `AssertionError: dense/BiasAdd:0 is not in graph`

i donnot know what's wrong with it, cuz im a idot of mechine learning ...

**Comment by Rick-712N** [comment]
Finally, I muna use C# to make other things, and use python to do Mechine-Learning. I have no time to stuck in this terrible stuff... and I have a tech competition to prepare.
