### ISSUE TITLE
micro: port op SPACE_TO_BATCH_ND from lite

### ISSUE THREAD

**Issue by rkuester** [tensorflow/tensorflow#45765]
@tensorflow/micro

This issue tracks my work porting operator SPACE_TO_BATCH_ND from lite to micro.

The port will be submitted in a number of PRs. Here's a rough flight plan in the style of #45306:

PR 1: Extract the code for parsing the op from a flatbuffer out of ParseOpDataTfLite in tensorflow/lite/core/api/flatbuffer_conversions.cc into a standalone function that can be called from micro's op resolver
PR 2: Extract the reference implementation out of tensorflow/lite/kernels/internal/reference/reference_ops.h into its own header which can be included without dragging in reference_ops.h's dependences
PR 3: Copy operator from lite to micro without making any changes or including in the build
PR 4: Delete extra code from the micro copy of the operator
PR 5: Port micro copy of operator as necessary and add a corresponding test

**Comment by stephanboner** [comment]
There is already work in progress on this issue in #45693

**Comment by rkuester** [comment]
> There is already work in progress on this issue in #45693, maybe you can contribute there if you want?

Oops, thanks for pointing this out, @stephanboner. I'll leave this op to you. Please let me know if you want any help.

**Comment by stephanboner** [comment]
> > There is already work in progress on this issue in #45693, maybe you can contribute there if you want?
> 
> Oops, thanks for pointing this out, @stephanboner. I'll leave this op to you. Please let me know if you want any help.

I will, thank you!
