### ISSUE TITLE
python/ops/variable_scope.py, variable_scope() is not backward compatible

### ISSUE THREAD

**Issue by OscarDPan** [tensorflow/tensorflow#4576]
https://github.com/tensorflow/tensorflow/commit/3d1ee95e612b1987e664ca46a7c584872d36dde9#diff-57dece591b2185b1c01f712d53baef96L1089

It used to accept "" as name_of_scope, newer version TF will produce an error.
```
if default_name is None and not name_or_scope:
      raise TypeError("If default_name is None then name_or_scope is required")		
```

By reading the newer code, I believe disallowing "" as scope name wasn't your team's intension.
A simple fix could make this function completely backward compatible.

**Comment by lukaszkaiser** [comment]
Indeed, it looks like it was meant to be "... and not name_or_scope is None", right? Would you be willing to send a PR correcting this?

**Comment by OscarDPan** [comment]
I think it should be "... and ~~not~~ name_or_scope is None".
PR is up:
https://github.com/tensorflow/tensorflow/pull/4619
