### ISSUE TITLE
CUDA 10.0 support has been dropped in tf 2.4

### ISSUE THREAD

**Issue by janbernloehr** [tensorflow/tensorflow#45762]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.0/7.6.3
- GPU model and memory: 1080 Ti

**Describe the current behavior**

When building tf 2.4.0 from source on CUDA 10.0 the build fails with

```
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /tensorflow_src/third_party/gpus/cuda_configure.bzl:1430:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/tensorflow_src/third_party/gpus/cuda_configure.bzl", line 1400
		_create_local_cuda_repository(<1 more arguments>)
	File "/tensorflow_src/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/tensorflow_src/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/tensorflow_src/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/tensorflow_src/third_party/remote_config/common.bzl", line 217, in execute
		fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
```

The dependency on cublasLt was added in 592947d1a6c4123d8aec8362d74b020c8b4e2b1a but cublasLt was added only in CUDA 10.1 and later.

**Describe the expected behavior**

The dependency on cublasLt is modelled such that on CUDA 10.0 it is not required.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@janbernloehr,
Every TensorFlow release is compatible with a certain CUDA and cuDNN version. Please go through the [tested build configurations](https://www.tensorflow.org/install/source#gpu) for more information. 

Please try building TensorFlow 2.4 with CUDA 11 and cuDNN 8 and check if you are facing the same error. Thanks!

**Comment by janbernloehr** [comment]
Building with CUDA 11 works fine, also 10.2 works. I was not sure if dropping CUDA 10.0 was intentional but I get from your response that it is not supported anymore. Thanks!

**Comment by amahendrakar** [comment]
@janbernloehr,
Yes, CUDA 10.0 is not supported with TensorFlow v2.4. 

> Building with CUDA 11 works fine, also 10.2 works

Is this still an issue? Please feel free to close the issue if resolved. Thanks!
