### ISSUE TITLE
Hexagon Delegate of fully connected layer 

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#45764]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hello, with the attached example tflite model, it runs on our device cpu good, output matches with expected. However if we use hexagon delegate to run, the output do not match, every 0x200 blocks have the same data.
The model is generated with tf1.15
I see that there's a test code at lite/delegates/hexagon/builders/tests/matmul_test.cc, however it asks the weight to be const, while in our model we need both inputs to matmul to be dynamic (output from previous nodes).
The matmul inputs are both at 512x256.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tensorbuffer** [comment]
How do I attached the tflite model? it only allows for txt file for attachment.

**Comment by amahendrakar** [comment]
@tensorbuffer,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.4 and check if you are facing the same issue?

> How do I attached the tflite model? it only allows for txt file for attachment.

You can drag and drop the file in the comment box or upload the file on Google Drive and share the link with us. Thanks!

**Comment by tensorbuffer** [comment]
Ok I have found out the root cause, it's a mismatch between tflite and nnlib.
I will close this issue now.
