### ISSUE TITLE
Segmentation fault in tf.histogram_fixed_width

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#45770]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.histogram_fixed_width` crashes (segmentation fault) when `values` contain nan

**Describe the expected behavior**
Expect no crash 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.histogram_fixed_width(values=np.nan, value_range=[1,2])
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.3, nightly version(`2.5.0-dev20201216`) and was able to reproduce the issue.Please,find the gist [here](https://colab.research.google.com/gist/ravikyram/c73c149a0723b67cec2772459f542a73/untitled582.ipynb). Thanks!

**Comment by mihaimaruseac** [comment]
Does this also reproduce with TF 2.4?

**Comment by ravikyram** [comment]
@mihaimaruseac 

I have tried in colab with TF 2.4 and i was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e36fe89c33a3477c484b62248b30a02d/untitled584.ipynb). Thanks!

**Comment by rushabh-v** [comment]
Looks like `values` don't expect `nan` values. Should I open a PR that raises an error if there are `nan` in `values`?

**Comment by ymodak** [comment]
I see that the example crashes if executed on cpu with TF 2.4 where as on gpu execution it passes with following output.
```python
<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>
```

**Comment by saikumarchalla** [comment]
I tried in TF 2.5 and 2.6 Nightly versions on both GPU and CPU,the colab crashes still on CPU. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/42470608ab9e257fd25ec111cd04a7c8/untitled90.ipynb).Thanks!

**Comment by mohantym** [comment]
It is still replicating in CPU mode for [TF 2.8](https://colab.sandbox.google.com/gist/mohantym/0f41a7f797bf930813d8383dc1d955a3/github_45770.ipynb#scrollTo=F8ttmtF-X2zd).
