### ISSUE TITLE
[Doc bug] tf.sparse.concat doesn't have argument `expand_nonconcat_dim`

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#45778]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/sparse/concat

## Description of issue (what needs changing):
The signature of API  `tf.sparse.concat ` doesn't have argument `expand_nonconcat_dim`
![image](https://user-images.githubusercontent.com/24580222/102425051-90d17a80-3fda-11eb-88fb-8da8d44f381c.png)

But in the Argument section, it describes argument `expand_nonconcat_dim`
![image](https://user-images.githubusercontent.com/24580222/102425085-a34bb400-3fda-11eb-8d57-5834a8a9f9a7.png)

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.3.0
- **Python version**: 3.7.6

**Comment by yongtang** [comment]
Added a PR #46040 for the fix.
