### ISSUE TITLE
Keras docs wrongly advise not to pass tf.keras.layers activations to a layer creation

### ISSUE THREAD

**Issue by bibbygoodwin** [tensorflow/tensorflow#45786]
## URL(s) with the issue:

https://keras.io/api/layers/activations/

## Description of issue (what needs changing):

In tf.keras, there are 2** ways of adding activation functions to your models. In the first instance, objects from `tf.keras.activations` can be passed as the `activation` argument in the creation of a layer as in: 
```python
model.add(layers.Dense(64, activation=tf.nn.tanh))
```

The 2nd API for activations is to explicitly add them as a layer, as in:
```python
x = layers.Dense(10)(x)
x = layers.LeakyReLU()(x)
```

The problem with the docs is that they explicitly say (at https://keras.io/api/layers/activations/) that:
> you should not pass activation layers instances as the activation argument of a layer. They're meant to be used just like regular layers

This runs contrary to current usage in tf2, where can can do exactly this. See, for instance, [this stackoverflow answer](https://stackoverflow.com/a/56869141/7858285) which advises the following:
```python
model.add(Conv2D(..., activation=tf.keras.layers.LeakyReLU(alpha=0.1), ...)
```
in place of the `lambda` function that is otherwise needed if one is to follow the keras docs advice.

**you might say there are 3 ways, as in the '1st' method one can also request an activation by its string identifier. 

### Submit a pull request?
Unless I'm mistaken, the https://keras.io/ docs are not open source. The keras repo currently requests that all issues be opened here in the tf repo.

**Comment by rmothukuru** [comment]
@bibbygoodwin,
This is an issue related to `**Keras documentation**` and not **`TF Keras documentation`**.  The statement:

> you should not pass activation layers instances as the activation argument of a layer. They're meant to be used just like regular layers

is neither present in the TF Keras Documentation for [LeakyRelu](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LeakyReLU) nor in [PReLU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/PReLU).

So, request you to raise an issue in [Keras Github Repository](https://github.com/keras-team/keras/issues/new). Thanks!

**Comment by bibbygoodwin** [comment]
@rmothukuru Thank you for your reply. The README of the keras repo currently states: 

> In the near future, this repository will be used once again for developing the Keras codebase. For the time being, the Keras codebase is being developed at tensorflow/tensorflow, and any PR or issue should be directed there.

That was why I created this issue here and not in the keras repo.

Also, the docs I linked to which have the problem (https://keras.io/api/layers/activations/) are indeed the keras documentation, but are for `tf.keras`, as you can see on the linked page. Thus, I think there is ample scope for confusion here if things are not ammended.

Thanks again.

**Comment by fchollet** [comment]
It was always possible to do so (if you use the layer as such, it's used like a function), but it leads to potential issues (most importantly the issue that your activation layer *could* include trainable weights, which would be ignored by the model if you used it like this).

Layers are meant to be nodes in a graph of layers, and so should be used as such, like in the example:

```
x = layers.Dense(10)(x)
x = layers.LeakyReLU()(x)
```

> Unless I'm mistaken, the https://keras.io/ docs are not open source. The keras repo currently requests that all issues be opened here in the tf repo.

Keras docs are open-source and can be modified at https://github.com/keras-team/keras-io
