### ISSUE TITLE
GRPCIO v1.32.0 hard requirement results in clashes with other versions

### ISSUE THREAD

**Issue by axsaucedo** [tensorflow/tensorflow#45785]
Tensorflow currently has a hard dependency on `grpcio~=1.32.0`, which results in clashes with packages that depend in newer versions of GRPC. This issue encompasses the requirement to update the GRPCIO library to the latest 1.34.0 version (or later).

**Comment by ymodak** [comment]
Probably https://github.com/tensorflow/tensorflow/pull/46019 may fix this.

**Comment by mihaimaruseac** [comment]
#46019 landed

**Comment by dariobig** [comment]
We've just stumbled on this issue with TF 2.4.1. It seems that TF 2.4.1 still depends on 1.32.0: https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/tools/pip_package/setup.py#L121

**Comment by mihaimaruseac** [comment]
That is true. 2.5 branch cut is today.

**Comment by dariobig** [comment]
> That is true. 2.5 branch cut is today.

Thanks @mihaimaruseac , can you confirm this will be addressed in TF 2.5? Since this issue is closed, do you have another issue to track its progress?

**Comment by dariobig** [comment]
I've created a new issue just in case: https://github.com/tensorflow/tensorflow/issues/48109
