### ISSUE TITLE
Support for AMD Graphics Card

### ISSUE THREAD

**Issue by shvamabps** [tensorflow/tensorflow#45782]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.x
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**
If possible can the support for AMD graphics be provided as this is the issue either way if the system has good features/configuration just because it has an AMD graphics card the TensorFlow won't work as smooth as it works in Nvidia graphics card? 

**Will this change the current API? How?**
I don't know about this.

**Who will benefit from this feature?**
Everyone who uses AMD graphics card.

**Any Other info.**

**Comment by amahendrakar** [comment]
@shvamabps,
Please go through simliar issue [#32358](https://github.com/tensorflow/tensorflow/issues/32358) and take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/32358#issuecomment-530234081) from a member of the TensorFlow team and let us know if it helps. Thanks!

**Comment by shvamabps** [comment]
Thanks @amahendrakar 
It helped..

**Comment by neel04** [comment]
@shvamabps You can check out `PlaidML` by Intel which is great for using AMD GPU's and other non-Nvidia devices to be used in training and works very well with `Keras`.

**Comment by amahendrakar** [comment]
@shvamabps,
Thank you for the update. Marking this issue as closed, please feel free to reopen if necessary.
