### ISSUE TITLE
Default weights_initializer for tf.contrib.layers.convolution2d should be xavier_initializer_conv2d

### ISSUE THREAD

**Issue by yzgysjr** [tensorflow/tensorflow#4578]
Hi, 

I notice that in [tf.contrib.layers.convolution2d](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L354), [tf.contrib.layers.convolution2d_in_plane](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L469), [tf.contrib.layers.convolution2d_transpose](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L573), [tf.contrib.layers.separable_convolution2d](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L1097), the default weights_initializer is tf.contrib.layers.xavier_initializer, rather than tf.contrib.layers.xavier_initializer_conv2d. Is it better to use tf.contrib.layers.xavier_initializer_conv2d?

Thanks!

**Comment by haleuh** [comment]
xavier_initializer_conv2d = xavier_initializer

**Comment by yzgysjr** [comment]
Got it. Thanks!
