### ISSUE TITLE
A Convolutional Neural Network Model Could not be loaded

### ISSUE THREAD

**Issue by aykutcayir34** [tensorflow/tensorflow#4579]
I have saved the model using Keras' model.save('my_model.h5') it's working. However, when I try to load the model in a different project I get this error message: ValueError: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout_1/mul_1:0", shape=(?, 1, 256), dtype=float32).
Could this be a bug? Any idea?

**Comment by concretevitamin** [comment]
Looks like you should file it against Keras.  Feel free to reopen if you have a minimum repro program that shows this is a TF bug.
