### ISSUE TITLE
Keras add_loss()/kernel_regularizer incompatability

### ISSUE THREAD

**Issue by TheBeaNerd** [tensorflow/tensorflow#45795]
**System information**
- OS Platform and Distribution : Ubuntu 18.04.5 LTS (Dockerized)
- TensorFlow installed from : Docker tensorflow/tensorflow:latest-gpu-jupyter
- TensorFlow version : 2.3.1
- Python version: 3.6.9
- GPU model and memory: No GPU

**Describe the current behavior**

Given a Model with a Dense layer that includes a kernel_regularizer, using add_loss() and then compiling results in the following error during .fit():  ValueError: Shapes must be equal rank, but are 0 and 1.

Note: this issue does not manifest when the loss is passed directly to .compile().

**Describe the expected behavior**

The Keras framework should seamlessly combine various loss functions.

**Standalone code to reproduce the issue**

https://gist.github.com/TheBeaNerd/e123c0e4a6245c9069bf645da5501fd7

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/211375a272ab543fe8a2c7610a365560/45795.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@TheBeaNerd,
Can you try using the code mentioned in the [Documentation for Add_Loss](https://www.tensorflow.org/guide/keras/custom_layers_and_models#the_add_loss_method) and see if the **`Error`** Persists? Thanks!

**Comment by TheBeaNerd** [comment]
@rmothukuru
Can you clarify which of the following actions you are suggesting?

1. Perform add_loss() at a Layer level as with the ActivityRegularizationLayer in the referenced documentation

  - Note that in my current example, add_loss() is being performed at the Model level.
  - Because the loss is between the input and output of the network, it isn't local to a specific Layer.

2. Perform kernel regularization as with the OuterLayerWithKernelRegularizer in the referenced documentation

  - I can try that, but it doesn't seem substantially different from the current example.

**Comment by charlesincharge** [comment]
I ran into this issue, too, and would appreciate any help.

One issue might be that the regularizer loss (first row) show up as tf-scalars while the `model.add_loss` output (second row) shows up as `(None,)`-size/batch-size vectors? 
![Screenshot 2021-03-18 at 5 10 59 PM](https://user-images.githubusercontent.com/3221512/111713481-f49f5580-880c-11eb-89d4-d8ada4e9009f.png)

**Comment by gowthamkpr** [comment]
@TheBeaNerd The error occurs because the loss that has been calculated is not a scalar but an n dimensional tensor. Try reducing your loss to a scalar as mentioned in this [issue](https://stackoverflow.com/questions/69643143/raise-shapes-must-be-equal-rank-when-adding-regularizers-to-keras-layers) and it should work with regularizers.
