### ISSUE TITLE
[C++] Cannot Construct tensorflow::Status with std::string

### ISSUE THREAD

**Issue by busFred** [tensorflow/tensorflow#45793]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc-10
- CUDA/cuDNN version: 11.2 (installed but NOT used)
- GPU model and memory: MX150

**Describe the current behavior**
All the below cannot successfully construct a tensorflow::Status instance
1. ```
    tensorflow::StringPiece err_msg = "NOT jpg";
    tensorflow::Status{tensorflow::errors::Code::INVALID_ARGUMENT, err_msg};
    ```
2. `tensorflow::Status{tensorflow::errors::Code::INVALID_ARGUMENT, "string"};`

3. `tensorflow::errors::InvalidArgument("Image must be jpeg encoded");`
Only this work
`tensorflow::Status::OK();`

All of them causes the following error
```
[build] /usr/bin/ld: src/tutorial_02/CatDogCnn/libCatDogCnn.a(CatDogCnn.cpp.o): in function `tensorflow::Status::Status(tensorflow::error::Code, std::basic_string_view<char, std::char_traits<char> >)':
[build] /usr/local/include/tensorflow/bazel-bin/tensorflow/include/tensorflow/core/platform/status.h:54: undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, std::basic_string_view<char, std::char_traits<char> >, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'
```

**Describe the expected behavior**
Should compile without error

**Standalone code to reproduce the issue**
class definition 
```
#include <tensorflow/cc/client/client_session.h>
#include <tensorflow/cc/framework/gradients.h>
#include <tensorflow/cc/ops/image_ops.h>
#include <tensorflow/cc/ops/standard_ops.h>
#include <tensorflow/cc/tools/freeze_saved_model.h>
#include <tensorflow/core/framework/tensor.h>
#include <tensorflow/core/lib/io/path.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/summary/summary_file_writer.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
class CatDogCnn {
 public:
  /**
   * @brief Construct a new Cat Dog Cnn object. Assume images are square.
   *
   * @param image_size the size of image
   * @param num_of_channels number of channels
   */
  CatDogCnn(const int image_size, const int num_of_channels);
  /**
   * @brief Create a Graph for Input Image. If unstack is false, the
   * output_image_tensor_node_ will have shape of [batch, width, channel]. If
   * unstack is true, the ouput_image_tensor_node_ will have shape of [batch,
   * height, width, channel]. In addition, only the first element will be stored
   * to output_image_tensor_node_
   *
   * @param unstack ouput tensor or not
   * @return tensorflow::Status
   */
  tensorflow::Status CreateGraphForInputImage(bool unstack);

  /**
   * @brief Convert an image to a tensor
   *
   * @param path_to_image path to the jpeg file to be converted
   * @param out_tensor pointer to output tensor
   * @return tensorflow::Status
   */
  tensorflow::Status ConvertImageToTensor(
      const std::filesystem::path& path_to_image,
      tensorflow::Tensor* out_tensor);

 private:
  const int kImageSize;      // assume squre picture
  const int kNumOfChannels;  // RGB
  // load image
  tensorflow::Scope load_image_scope_;
  tensorflow::Output input_image_filename_node_;
  tensorflow::Output output_image_tensor_node_;
};
```

methods implementation
```
CatDogCnn::CatDogCnn(const int image_size, const int num_of_channels)
    : kImageSize{image_size},
      kNumOfChannels{num_of_channels},
      load_image_scope_{tensorflow::Scope::NewRootScope()} { /*empty*/
}

tensorflow::Status CatDogCnn::CreateGraphForInputImage(bool unstack) {
  input_image_filename_node_ = tensorflow::ops::Placeholder{
      load_image_scope_.NewSubScope("input_file_name"),
      tensorflow::DataType::DT_STRING};
  tensorflow::ops::ReadFile read_file_node{
      load_image_scope_.NewSubScope("read_file"), input_image_filename_node_};
  tensorflow::ops::DecodeJpeg decode_image_node{
      load_image_scope_.NewSubScope("decode_image"), read_file_node};
  // convert each pixel to float
  tensorflow::ops::Cast cast_float_node{
      load_image_scope_.NewSubScope("cast_float"), decode_image_node,
      tensorflow::DataType::DT_FLOAT};
  // [height, width channel] -> [batch, height, width, channel]
  tensorflow::ops::ExpandDims expand_batch_dim_node{
      load_image_scope_.NewSubScope("exapnd_batch_dim"), cast_float_node, 0};
  // resize image to square
  tensorflow::ops::ResizeBilinear resize_image_node(
      load_image_scope_.NewSubScope("resize"), expand_batch_dim_node,
      {kImageSize, kImageSize});
  // divide each pixel by 255 so that each pixel is [0, 1]
  tensorflow::ops::Div normalize_image_node{
      load_image_scope_.NewSubScope("normalize_image"),
      resize_image_node,
      {255.f}};
  if (unstack) {
    // unstack along height axis
    // array of [batch, width, channel]
    tensorflow::ops::Unstack unstack_image_node{
        load_image_scope_.NewSubScope("unstack_image"), normalize_image_node,
        1};
    output_image_tensor_node_ = unstack_image_node[0];
  } else {
    output_image_tensor_node_ = normalize_image_node;
  }
  return load_image_scope_.status();
}

tensorflow::Status CatDogCnn::ConvertImageToTensor(
    const std::filesystem::path& path_to_image,
    tensorflow::Tensor* out_tensor) {
  if (load_image_scope_.ok() == false) {
    return load_image_scope_.status();
  }
  if (path_to_image.extension().string() != ".jpg" ||
      path_to_image.extension().string() != ".jpeg") {
    tensorflow::StringPiece err_msg = "NOT jpg";
    return tensorflow::errors::InvalidArgument("Image must be jpeg encoded");
    // return tensorflow::Status{tensorflow::errors::Code::INVALID_ARGUMENT,
    //                           err_msg,};
    // return tensorflow::Status::OK();
  }
  std::vector<tensorflow::Tensor> out_tensors;
  tensorflow::ClientSession client_session{load_image_scope_};
  TF_CHECK_OK(
      client_session.Run({{input_image_filename_node_, path_to_image.string()}},
                         {output_image_tensor_node_}, &out_tensors));
  (*out_tensor) = std::move(out_tensors[0]);
  return load_image_scope_.status();
}
```
entry point
```
#include <iostream>
#include <tensorflow_tutorial/tutorial_02/CatDogCnn/CatDogCnn.hpp>
int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "./tutorial_02 /path/to/image" << std::endl;
    exit(EXIT_FAILURE);
  }
  CatDogCnn cat_dog_model{150, 3};
  tensorflow::Tensor image_tensor;
  cat_dog_model.CreateGraphForInputImage(false);
  cat_dog_model.ConvertImageToTensor(std::filesystem::path{argv[1]},
                                     &image_tensor);
  std::cout << image_tensor.DebugString() << std::endl;
  cat_dog_model.CreateGraphForInputImage(true);
  cat_dog_model.ConvertImageToTensor(std::filesystem::path{argv[1]},
                                     &image_tensor);
  std::cout << image_tensor.DebugString() << std::endl;
  return 0;
}
```
CMakeLists.txt for CatDogCnn
```
add_library(CatDogCnn STATIC CatDogCnn.cpp)

target_link_libraries(CatDogCnn PUBLIC TensorflowCC::TensorflowCC)

if(CUDA_FOUND)
  target_link_libraries(CatDogCnn PUBLIC ${CUDA_LIBRARIES})
endif(CUDA_FOUND)
```
CMakeLists.txt for entry point
```
add_subdirectory(CatDogCnn)

add_executable(tutorial_02 tutorial_02.cpp)

target_link_libraries(tutorial_02 PRIVATE CatDogCnn)

target_link_libraries(tutorial_02 PRIVATE TensorflowCC::TensorflowCC)

# if(CUDA_FOUND)
#   target_link_libraries(tutorial_02 ${CUDA_LIBRARIES})
# endif(CUDA_FOUND)

set_target_properties(tutorial_02 PROPERTIES
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/bin/tutorial_02"
)
```
library TensorflowCC::TensorflowCC is generated by [FloopCZ/tensorflow_cc](https://github.com/FloopCZ/tensorflow_cc/tree/tf-v2.4.0), which compiles and installs Tensorflow with CMake support.
I don't think TensorflowCC is the smoking gun here since tensorflow::Status{} is working. I think there is a missing pieces that needs to be added to create Status instance with std::string

**Other info / logs** Include any logs or source code that would be helpful to
[main] Building folder: tensorflow_cpp_tutorial 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/fred/Documents/research/tensorflow_cpp_tutorial/build --config Debug --target all -- -j 10
[build] [1/3  33% :: 11.613] Building CXX object src/tutorial_02/CatDogCnn/CMakeFiles/CatDogCnn.dir/CatDogCnn.cpp.o
[build] [2/3  66% :: 11.648] Linking CXX static library src/tutorial_02/CatDogCnn/libCatDogCnn.a
[build] [3/3 100% :: 14.248] Linking CXX executable ../bin/tutorial_02/tutorial_02
[build] FAILED: ../bin/tutorial_02/tutorial_02 
[build] : && /bin/g++-10  -g   src/tutorial_02/CMakeFiles/tutorial_02.dir/tutorial_02.cpp.o  -o ../bin/tutorial_02/tutorial_02  -Wl,-rpath,/usr/local/lib  src/tutorial_02/CatDogCnn/libCatDogCnn.a  /usr/local/lib/libtensorflow_cc.so.2  -lpthread  /usr/local/cuda/lib64/libcudart_static.a  -lpthread  -ldl  /usr/lib/x86_64-linux-gnu/librt.so && :
[build] /usr/bin/ld: src/tutorial_02/CatDogCnn/libCatDogCnn.a(CatDogCnn.cpp.o): in function `tensorflow::Status::Status(tensorflow::error::Code, std::basic_string_view<char, std::char_traits<char> >)':
[build] /usr/local/include/tensorflow/bazel-bin/tensorflow/include/tensorflow/core/platform/status.h:54: undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, std::basic_string_view<char, std::char_traits<char> >, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1

**Comment by busFred** [comment]
Based on my investigation, the macro ABSL_USES_STD_STRING_VIEW is somehow being defined during the compilation and the "absl/strings/string_view.h" has the following code:
```
#ifdef ABSL_USES_STD_STRING_VIEW

#include <string_view>  // IWYU pragma: export

namespace absl {
ABSL_NAMESPACE_BEGIN
using std::string_view;
ABSL_NAMESPACE_END
}  // namespace absl

#else  // ABSL_USES_STD_STRING_VIEW
```
This code snippet redirect the absl::string_view to use std::string_view.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
