### ISSUE TITLE
[C++] tensorflow::ops::Unstack Documentation and Implementation Mismatch

### ISSUE THREAD

**Issue by busFred** [tensorflow/tensorflow#45794]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc-10
- CUDA/cuDNN version: 11.2 (installed but not used)
- GPU model and memory: MX150

**Describe the current behavior**
the input tensor has shape [1,150,150,3]. According to the documentation in the array_ops.h, unstack the input along 0th axis should produce [150,150,3] tensor. However, putting 0 as input cause segmentation fault.
`Segmentation fault (core dumped)`
If unstack along 1st axis, the output tensor has shape of [150,150,3]

**Describe the expected behavior**
unstack along 0th axis of a tensor with shape [a,b,c,d] should output a tensor with shape [b,c,d].

**Standalone code to reproduce the issue**
```
tensorflow::ops::Unstack unstack_image_node{load_image_scope_.NewSubScope("unstack_image"), normalize_image_node, 0};
output_image_tensor_node_ = unstack_image_node[0]; // and then std::cout<<out_tensor.DebugString(); to examine the shape
```

**Other info / logs**
Start from line 6958 to line 6982 in arrays_ops.h describes the expected behavior of class Unstack, which is basically as same as the documentation of its [python counterpart](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/stack)
```
/// Unpacks a given dimension of a rank-`R` tensor into `num` rank-`(R-1)` tensors.
///
/// Unpacks `num` tensors from `value` by chipping it along the `axis` dimension.
/// For example, given a tensor of shape `(A, B, C, D)`;
///
/// If `axis == 0` then the i'th tensor in `output` is the slice `value[i, :, :, :]`
///   and each tensor in `output` will have shape `(B, C, D)`. (Note that the
///   dimension unpacked along is gone, unlike `split`).
///
/// If `axis == 1` then the i'th tensor in `output` is the slice `value[:, i, :, :]`
///   and each tensor in `output` will have shape `(A, C, D)`.
/// Etc.
///
/// This is the opposite of `pack`.
///
/// Arguments:
/// * scope: A Scope object
/// * value: 1-D or higher, with `axis` dimension size equal to `num`.
///
/// Optional attributes (see `Attrs`):
/// * axis: Dimension along which to unpack.  Negative values wrap around, so the
/// valid range is `[-R, R)`.
///
/// Returns:
/// * `OutputList`: The list of tensors unpacked from `value`.
class Unstack {
```
however, using the following code with axis = 1
```
tensorflow::ops::Unstack unstack_image_node{
  load_image_scope_.NewSubScope("unstack_image"), normalize_image_node, 1};
output_image_tensor_node_ = unstack_image_node[0];
```
produce the expected behavior when axis = 0, which is
```
2020-12-17 11:45:05.233760: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-17 11:45:05.252351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099940000 Hz
Tensor<type: float shape: [1,150,150,3] values: [[[0.0705882385 0.0941176564 0.298039228]]]...>
Tensor<type: float shape: [150,150,3] values: [[0.0705882385 0.0941176564 0.298039228]]...>
```
If axis = 0
```
tensorflow::ops::Unstack unstack_image_node{
  load_image_scope_.NewSubScope("unstack_image"), normalize_image_node, 0};
output_image_tensor_node_ = unstack_image_node[0];
```
segmentation fault occurs.
```
2020-12-17 11:38:37.604552: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-17 11:38:37.624902: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099940000 Hz
Tensor<type: float shape: [1,150,150,3] values: [[[0.0705882385 0.0941176564 0.298039228]]]...>
Segmentation fault (core dumped)
```

**Comment by vinhngx** [comment]
+1 I've noticed the same that the axis parameter doesn't seem to be effective and always points to dimension 0.

**Comment by vinhngx** [comment]
I figured it out how to specify the axis dimension (which default to 0):
```
 auto unstack_image_node = tensorflow::ops::Unstack(root.WithOpName("unstack_image"), resized, 3, tensorflow::ops::Unstack::Attrs().Axis(3));
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
