### ISSUE TITLE
Keras compile(loss=) missing gradient for captured tensors

### ISSUE THREAD

**Issue by TheBeaNerd** [tensorflow/tensorflow#45796]
**System information**
- OS Platform and Distribution : Ubuntu 18.04.5 LTS (Dockerized)
- TensorFlow installed from : Docker tensorflow/tensorflow:latest-gpu-jupyter
- TensorFlow version : 2.3.1
- Python version: 3.6.9
- GPU model and memory: No GPU

**Describe the current behavior**

A gradient is not being recorded for tensors captured by a loss function passed to .compile() 

This results in a ValueError: No gradients provided for any variable ...

**Describe the expected behavior**

.compile(loss=) should correctly integrate the gradients for all tensors used in the loss computation.

**Standalone code to reproduce the issue**

https://gist.github.com/TheBeaNerd/78844dacf2d236eb50188062036a1082

**Comment by amahendrakar** [comment]
@TheBeaNerd,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by TheBeaNerd** [comment]
@amahendrakar
The example still does not work, but I'm seeing a different error under both 2.4.0 and nightly:

  TypeError: Cannot convert a symbolic Keras input/output to a numpy array.

As I note in my example, however, using add_loss() rather than .compile(loss=) works under 2.3.1, 2.4.0 and nightly.

(I have updated my gist to reflect this experiment)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/4a4292b7148fc3e3b8effccebeea95d7/45796-2-3.ipynb#scrollTo=MEU-6CSjvLen), throws a `ValueError` stating `No gradients provided for any variable`.

Whereas with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/b66448a64c709065ec989dbc047b2add/45796.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/2a43ee3aab29e02270b395f82ffb4f6d/45796-tf-nightly.ipynb#scrollTo=MEU-6CSjvLen), the error is `TypeError: Cannot convert a symbolic Keras input/output to a numpy array`. Please check the linked gist for reference. Thanks!

**Comment by fchollet** [comment]
The code above is TF1 code. It relies on the existence of backgrounds static computation graph. 
If you want to run it, revert to TF 1.x. The gradient error is expected.

Here's the equivalent code in TF 2.x: https://keras.io/examples/generative/vae/

**Comment by TheBeaNerd** [comment]
> The gradient error is expected.

  As noted above, under TF 2.4/nightly, the gradient error has been replaced with:

  TypeError: Cannot convert a symbolic Keras input/output to a numpy array.

> Here's the equivalent code in TF 2.x: https://keras.io/examples/generative/vae/

  The linked example doesn't use .compile(loss=) to integrate loss with the model.

  Thus, it doesn't address the issue:

> **Describe the expected behavior**
>
> .compile(loss=) should correctly integrate the gradients for all tensors used in the loss computation.
