### ISSUE TITLE
Official Example For TensorFlow Lite Model Maker doesn't work

### ISSUE THREAD

**Issue by ando0689** [tensorflow/tensorflow#45791]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
**No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**Mac Book Pro 2017(2.3 GHz Dual-Core Intel Core i5, 8 GB 2133 MHz LPDDR3), MacOS Big Sur 11.0.1,
Browser: Version 87.0.4280.88 (Official Build) (x86_64),
but I guess the above info does not matter as I run the example in Google Colab [here](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_question_answer.ipynb)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
**OnePlus 6 OxygenOS 10.3.7, Android 10**
- TensorFlow installed from (source or binary):
**binary**
- TensorFlow version (use command below):
**In Colab 2.5.0-dev20201217, in Android 0.0.0-nightly**
- Python version:
**Python 3.6.9**
- Bazel version (if compiling from source):
**N/A**
- GCC/Compiler version (if compiling from source):
**N/A**
- CUDA/cuDNN version:
**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243**
- GPU model and memory:
I cannot check this as I run the Colab provided in official Tensorflow page on the provided Google Colab Environment, which you can see in the following url: [https://www.tensorflow.org/lite/tutorials/model_maker_question_answer](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer)

**Describe the current behavior**
In order to have the full context of the issue, please see [the following issue](https://github.com/tensorflow/tensorflow/issues/45541)

The specific problem described in #45541  is resolved on nightly build, but overall the official example is not working:

here are the issues:

1. When I do `!pip install tflite-model-maker-nightly` I see the following error in the log:
```
ERROR: tensorflow 2.3.0 has requirement h5py<2.11.0,>=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tf-nightly 2.5.0.dev20201215 has requirement numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.
```
Though this does not stop the execution and I can continue.

2. When i try to use the created model with TensorFlow Lite Android v 2.3.0 I get the following error when I try to create interpreter with this model:
https://gist.github.com/ando0689/1874b6881dc7af3a31519e1bb2813386

3. And when I increase the version of TensorFlow Lite on Android to `0.0.0-nightly` I get the following error when I try to do inference:
https://gist.github.com/ando0689/b25f00443249da833af08cb8a6235a95

4. Just a note: The provided dataset with 8000 entities seems to be too much for this example, as running on the free Colab, it takes about 6 hours, and usually fails with some error.. I was only able to train it by reducing the dataset to be 1000 entities, I guess it's enough for example.

**Describe the expected behavior**
The example project provided in Official website of TensorFlow should run without any problem on the officially provided Colab Environment and also the produced model should work on client side as well.

**Standalone code to reproduce the issue**
1. Please try to make TFLite model using Official Colab [here](https://www.tensorflow.org/lite/tutorials/model_maker_question_answer)
2. Following the resolution of #45541  issue described [here](https://github.com/tensorflow/tensorflow/issues/45541) install tflit_model_maker from nightly channel  using `!pip install tflite-model-maker-nightly`
3. On client side use the official TensorFlow Lite Android example app for BERT QA, find it [here](https://github.com/tensorflow/examples/tree/master/lite/examples/bert_qa/android)

**Other info / logs** 
Provided in issue description above

**Comment by lintian06** [comment]
Thank you for the report! We will take a look at it in details from our side.

```
java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'
    
Registration failed.
```

As you find the error message, can you check it what TensorFlow version do you use exactly? Is it latest TF tensorflow (like 2.3, 2.4) or tf-nightly (2.5.0.dev20201215)? Thank you!

**Comment by ando0689** [comment]
Hi @lintian06 ,

Thanks for reply.

As I mentioned in the report, this exact error is received with TFLite 2.3.0 on Android, changing the version of TFLite to tf-nightly (2.5.0.dev20201215) resolves this exact problem, and the Interpreter gets initialized, but during inference it throws another error, you can see the log here:
[https://gist.github.com/ando0689/b25f00443249da833af08cb8a6235a95](https://gist.github.com/ando0689/b25f00443249da833af08cb8a6235a95)

**Comment by lintian06** [comment]
Thank you for the log message! The crashed call stack doesn't show the information as detailed as I need.

Can you try changing [this line](https://github.com/tensorflow/examples/blob/22f86fd27e5688152772e06db80da03d552bfd10/lite/examples/bert_qa/android/app/src/main/java/org/tensorflow/lite/examples/bertqa/ml/QaClient.java#L151) to
```
Object[] inputs = {segmentIds, inputMask, inputIds};
```

I just suspect your model may has different tensors, compared with the existing one.

**Comment by ando0689** [comment]
Thanks. 
It's strange but now I started to receive the following exception:
https://gist.github.com/ando0689/23077fe85f7961b07ee0d2e550b42538

B.t.w, if it would be more convenient for you, here is the model itself, I use the official TFLite BertQA example app, the only change I do is the change of the model and the version of TF. so may be if you can reproduce the problem it would be easier to debug it?
https://drive.google.com/file/d/13tBmq6oTqPC3pyiElJuRVzks1z1xmEja/view?usp=sharing

**Comment by lintian06** [comment]
Hi @ando0689 , the file contains zero bytes, which doesn't seem correct.

**Comment by ando0689** [comment]
@lintian06 , sorry for that, last time I tried with a corrupted model, and the last error was because of that.
I retrained the model and tried how you suggested with changing 
this `Object[] inputs = {inputIds, inputMask, segmentIds};`
to this `Object[] inputs = {segmentIds, inputMask, inputIds};`

and seems it worked! Thank you very much!!

**Comment by lintian06** [comment]
Great! FYI, we are going to polish the code to adapt the tensor order in the near future.
