### ISSUE TITLE
saved_model does not support RaggedTensors

### ISSUE THREAD

**Issue by pedro-r-marques** [tensorflow/tensorflow#45797]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

inp = layers.Input(shape=(None, 4), ragged=True)
x = layers.Lambda(lambda x: x)(inp)
model = keras.Model(inp, x)
model.compile(loss="mse")

model.save("test", save_traces=True)
```

https://colab.research.google.com/drive/1hGrYVPrTy6vDbZPAHAPn2XGmpQMXQmQX?usp=sharing

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab

- TensorFlow version (use command below):
tf-nightly (~=2.5.0.a)

**Describe the current behavior**
```keras.Model.save()``` raises an exception when a layer returns a RaggedTensor.

The exception message states that the object returned from tracing a function must be a tf.Tensor. RaggedTensors are not instances of tf.Tensor.

**Describe the expected behavior**
It should be possible to save and load models that take RaggedTensors as inputs and return RaggedTensors as outputs.

**Workaround**
The model can be saved when the option ```save_traces=False``` is used.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1hGrYVPrTy6vDbZPAHAPn2XGmpQMXQmQX?usp=sharing

Issue #41034 Reports a similar issue with loading a model that uses a RaggedTensor as input. This issue is for the specific problem of a RaggedTensor not being accepted as the return value of a keras node / tf.function as far as the saved_model package is concerned.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/signature_serialization.py:158 signature_wrapper  *
        structured_outputs, signature_function.name, signature_key)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/signature_serialization.py:219 _normalize_outputs  **
        .format(value, key, compat.as_str_any(function_name), signature_key))

    ValueError: Got a non-Tensor value tf.RaggedTensor(values=Tensor("PartitionedCall:0", shape=(None, 4), dtype=float32), row_splits=Tensor("PartitionedCall:1", shape=(None,), dtype=int64)) for key 'lambda' in the output of the function __inference__wrapped_model_173 used to generate the SavedModel signature 'serving_default'. Outputs for functions used as signatures must be a single Tensor, a sequence of Tensors, or a dictionary from string to Tensor.
```

As far as I can tell this relates to the following function in python/saved_model/signature_serializatioon.py

 ```python
def _normalize_outputs(outputs, function_name, signature_key):
  """Construct an output dictionary from unnormalized function outputs."""
  # Convert `outputs` to a dictionary (if it's not one already).
  if not isinstance(outputs, collections_abc.Mapping):
    if not isinstance(outputs, collections_abc.Sequence):
      outputs = [outputs]
    outputs = {("output_{}".format(output_index)): output
               for output_index, output
               in enumerate(outputs)}

  # Check that the keys of `outputs` are strings and the values are Tensors.
  for key, value in outputs.items():
    if not isinstance(key, compat.bytes_or_text_types):
      raise ValueError(
          ("Got a dictionary with a non-string key {!r} in the output of the "
           "function {} used to generate the SavedModel signature {!r}.")
          .format(key, compat.as_str_any(function_name), signature_key))
    if not isinstance(value, ops.Tensor):
      raise ValueError(
          ("Got a non-Tensor value {!r} for key {!r} in the output of the "
           "function {} used to generate the SavedModel signature {!r}. "
           "Outputs for functions used as signatures must be a single Tensor, "
           "a sequence of Tensors, or a dictionary from string to Tensor.")
          .format(value, key, compat.as_str_any(function_name), signature_key))

  return outputs
```

The test that requires the return value to be an instance of tf.Tensor is too restrictive.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/36183e588ab823b46da963668fc8429c/45797-2-3.ipynb), [TF v2.4](https://colab.research.google.com/gist/amahendrakar/f7339fc475dd6101cd31898fa9dc6cbf/45797.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/328ae01930ae030a4edc2d21e1b0f2fe/45797-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by rmothukuru** [comment]
@pedro-r-marques,
The error can be resolved by replacing the line,  **`x = layers.Lambda(lambda x: x)(inp)`** with 
**`x = layers.Lambda(lambda x: x.to_tensor())(inp)`**.

Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/cd735dc7a4c5b1a09a4a206a9b336548/45797.ipynb) of the working code. Thanks!

**Comment by pedro-r-marques** [comment]
@rmothukuru The operation ```to_tensor``` converts a RaggedTensor to a dense tensor (i.e. tf.Tensor). If you apply that operation the node no longer returns a RaggedTensor and thus graph saving works. This issue is to track the fact that graph saving does not support graphs with nodes that return RaggedTensors, which I'm sure you agree, is undesirable.

**Comment by tanguycdls** [comment]
The issue seems to be on the keras side since using only the savedmodel api works in TF2.4:
````
class TestOutputRagged(tf.Module):
  @tf.function()
  def test(self, a):
    return a

a = TestOutputRagged()
a.test(tf.ragged.constant([[2], [6, 8]]))
tf.saved_model.save(a, '/tmp/test')
tf.saved_model.load('/tmp/test').test(tf.ragged.constant([[3], [6, 8]]))
````

**Comment by pedro-r-marques** [comment]
If you want to replicate the issue without Keras, the following would do the trick:
```
import tensorflow as tf

class TestOutputRagged(tf.Module):
  @tf.function()
  def test(self, a):
    return a

a = TestOutputRagged()
rt = tf.ragged.constant([[2], [6, 8]])
tf.saved_model.save(a, '/tmp/test', signatures=a.test.get_concrete_function(tf.type_spec_from_value(rt)))
```

By default, Keras model save attempts to save the signatures of the functions. As per the original description above, the problem doesn't occur when not saving signatures. But the stack trace above is in the saved model code which currently rejects as function signature is the returned value is not a tf.Tensor. AFAIK it should accept any CompositeTensor.

**Comment by pedro-r-marques** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/b68d87647ca12d585b4daaa597a450bf83bc3ea4
