### ISSUE TITLE
Tensorflow model as executable file

### ISSUE THREAD

**Issue by moh3th1** [tensorflow/tensorflow#4582]
I want to share my model as an executable file (without sharing my source code ) . I am using Tensorflow on Ubutun 16.04.1 LTS .I tried pyinstaller and cx_freeze but it give me alot of errors

**pyinstaller error** 
![jvssz](https://cloud.githubusercontent.com/assets/15180702/18830940/609bb61c-83e3-11e6-939d-3d7b8a7cf7a0.png)

**cx_freeze error** 
![ikzr5](https://cloud.githubusercontent.com/assets/15180702/18830975/8c4a345a-83e3-11e6-854e-649b1a269d94.png)

	
I installed pyqt4 and I got this error 
` ` `
Error loading Python lib '/root/build/test/libpython2.7.so.1.0': /root/build/test/libpython2.7.so.1.0: cannot open shared object file: No such file or directory 
` ` `

**Comment by datnamer** [comment]
Nuitka?

**Comment by moh3th1** [comment]
NO , I use pyinstaller to compile the code and convert it to executable

**Comment by yaroslavvb** [comment]
That sounds like a problem in Anaconda/pyfreeze -- the error in your stack
trace is in QT framework which is not part of tensorflow

**Comment by mrry** [comment]
Agreed, this doesn't seem like a TensorFlow-specific issue, so I'm going to close it.

**Comment by kyo055** [comment]
@moh3th1 Have you solved the problem about the pyinstaller with tensorflow
