### ISSUE TITLE
I need a complete overhaul software bug security external storage 

### ISSUE THREAD

**Issue by nicholascourtway** [tensorflow/tensorflow#45831]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by amahendrakar** [comment]
@nicholascourtway,
Closing the issue as no details are filled. If mistaken, please fill in the issue template and explain in detail the issue you are facing. Thanks!

**Comment by nicholascourtway** [comment]
Yes by itself everyone
