### ISSUE TITLE
Tensorflow 2.4 Throwing Errors 

### ISSUE THREAD

**Issue by milind-prajapat** [tensorflow/tensorflow#45834]
**System information**
- OS Platform and Distribution: Windows 10 v20H2 
- TensorFlow installed from (source or binary): Through pip command
- TensorFlow version (use command below): v2.4.0
- Python version: v3.8.5
- CUDA/cuDNN version: v11.0 (update 1)/v8.0.4
- GPU model and memory: Nvidia GTX 1650 4GB GDDR5

-tf.version.GIT_VERSION: library cudart64_110.dll
-tf.version.VERSION: v2.4.0-rc4-71-g582c8d236cb 2.4.0

**Describe the current behavior**
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node sequential/conv2d/Conv2D (defined at <ipython-input-4-f922f88cbe61>:19) ]] [Op:__inference_train_function_753]
Function call stack:
train_function

**Describe the expected behavior**
It should be training the network with no issues. The same code worked on tensorflow v2.3.0.

**Standalone code to reproduce the issue**
Notebook at:
https://colab.research.google.com/drive/14vdfsSkqGn375E54vd11--yXy0WKemWm?usp=sharing
It was working fine on v2.3.0 at my end but after upgrading to 2.4.0 its throwing error.  Also I tried one more CNN network with different architecture which is working fine with no errors. I have also renamed a dll file in order to make tensorflow open CUPTI library.

**Other info / logs** Logs are included.
[Expected_log.txt](https://github.com/tensorflow/tensorflow/files/5713830/Expected_log.txt)
[Current_log.txt](https://github.com/tensorflow/tensorflow/files/5713831/Current_log.txt)

**Comment by amahendrakar** [comment]
@milind-prajapat,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/45779#issuecomment-747403789) from a similar issue #45779 and check if it helps. Thanks!

**Comment by milind-prajapat** [comment]
Yes, It worked. Thank you. But its wired to add them each time. Any
permanent solution?

**Comment by amahendrakar** [comment]
> Yes, It worked.

@milind-prajapat,
Thank you for the update. You'll have to set the GPU memory limit every time.

**Comment by milind-prajapat** [comment]
Yes, it is working.
