### ISSUE TITLE
v1.15.4 NoneType' object has no attribute 'UnimplementedError

### ISSUE THREAD

**Issue by UrmsOne** [tensorflow/tensorflow#45835]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.4
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am working on distributed learning in tensorflow through estimators API using below simple code template:

```
# TrainSpec for training
    train_spec = tf.estimator.TrainSpec(
        input_fn=lambda: csv_input_fn(TRAIN_PATH, FLAGS.batch_size, True),
        max_steps=FLAGS.train_steps,
        hooks=[])
    # EvalSpec for test
    eval_spec = tf.estimator.EvalSpec(
        input_fn=lambda: csv_input_fn(TEST_PATH, FLAGS.batch_size, True))
    print("---training and testing---")
    tf.estimator.train_and_evaluate(classifier, train_spec, eval_spec)
    print("---training finished---")

    # All role are workers, pick the task_index with 0 to save model
    if FLAGS.task_index == 0:
        classifier.export_saved_model(export_dir, serving_input_receiver_fn)
        # classifier.export_savedmodel(export_dir, serving_input_receiver_fn, strip_default_attrs=True)
    print("finish...")
```

I encountered the following error during training.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/server_lib.py", line 158, in __del__
AttributeError: 'NoneType' object has no attribute 'UnimplementedError'
```

I analyzed the source code and found that the errors object may be garbage collected.

I will submit a PR later, please pass it. Because I will use v1.15.4(v1.15.4 version on our production environment) 

for distributed training on kubeflow, 

I don’t want to modify the code there every time.

Thanks!!!

**Comment by amahendrakar** [comment]
@UrmsOne,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.4 and check if you are facing the same issue? Thanks!

**Comment by power1628** [comment]
same issue here, any updates?

**Comment by UrmsOne** [comment]
Modify the source code to solve the problem by myself.  You could try it, too.

Reference: 

[https://github.com/tensorflow/tensorflow/pull/45836/commits/7bb1dbc3991854c92b1aa03fd7a7159e8bc4dfe5](https://github.com/tensorflow/tensorflow/pull/45836/)

**Comment by UrmsOne** [comment]
@power1628 

Modify the source code to solve the problem by myself. You could try it, too.

Reference:

[https://github.com/tensorflow/tensorflow/pull/45836/](https://github.com/tensorflow/tensorflow/pull/45836/commits/7bb1dbc3991854c92b1aa03fd7a7159e8bc4dfe5)
