### ISSUE TITLE
Op type not registered 'StatefulPartitionedCall' in binary running

### ISSUE THREAD

**Issue by chlyzzo** [tensorflow/tensorflow#45837]
使用spark-2.3，然后通过maven下载依赖包，libtensorflow-1.9.0.jar,libtensorflow_jni-1.9.0.jar；
在spark-submit提交，读取模型，报如下错：

org.tensorflow.TensorFlowException: Op type not registered 'StatefulPartitionedCall' in binary running on [机器名]. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by amahendrakar** [comment]
@chlyzzo,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, looks like you are using TensorFlow 1.x which is not actively supported. Please install TensorFlow v2.4 and check if you are facing the same issue. Thanks!
