### ISSUE TITLE
Bazel can't fetch numeric-1.2.6.min.js because numericjs.com has expired

### ISSUE THREAD

**Issue by sharkdtu** [tensorflow/tensorflow#4583]
INFO: Downloading from http://www.numericjs.com/lib/numeric-1.2.6.min.js: 0B

---

When i opened it on my broswer, it prompted that numericjs.com has expired

**Comment by natlachaman** [comment]
same problem here

**Comment by jart** [comment]
Hey @dsmilkov where can we download this from GitHub? I found https://github.com/sloisel/numeric/blob/master/src/numeric.js but it doesn't appear to be the same code that we have checked in internally, even though the versions are the same. 

Or better yet, is there another library we could use?

cc: @danmane

**Comment by dsmilkov** [comment]
https://github.com/sloisel/numeric/blob/master/src/numeric.js is just a portion of the library (uncompiled), and the author doesn't store the compiled/bundled one on github.

We can link to:
https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js

Cloudfare CDN should be pretty stable. Let me know your thoughts

**Comment by dsmilkov** [comment]
Thanks Submitted an internal change where numericjs gets pulled from cloudflare cdn. The internal change should show up in github within a day.

Thanks @sharkdtu and @natlachaman  for the bringing this issue to our attention!
