### ISSUE TITLE
Its like all my info and accounts just dissapear

### ISSUE THREAD

**Issue by nicholascourtway** [tensorflow/tensorflow#45832]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by amahendrakar** [comment]
@nicholascourtway,
Closing the issue as no details are filled. If mistaken, please fill in the issue template and explain in detail the issue you are facing. Thanks!
