### ISSUE TITLE
A strange problem about gfile

### ISSUE THREAD

**Issue by fuhuamosi** [tensorflow/tensorflow#4584]
<img width="848" alt="2016-09-26 20 46 30" src="https://cloud.githubusercontent.com/assets/11813885/18834822/9ee71bea-842a-11e6-95d3-2af68449343d.png">

I use Tensorflow of gpu's version and Python3 on Linux.As you can see, I read a file by Gfile with mode "r",but it seems to return a byte object rather than a string.Can anyone explain this issue?

**Comment by aselle** [comment]
gfile currently returns a byte stream. If you want to convert it into a unicode (native) python string you need to know its encoding. If it is utf-8 you can do `str(foo.read(), 'utf-8')`.

**Comment by fuhuamosi** [comment]
@aselle Thank you,I understand the issue now.
