### ISSUE TITLE
TF2.4 doc missing keras.backend methods

### ISSUE THREAD

**Issue by wuhy08** [tensorflow/tensorflow#45860]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/backend

## Description of issue (what needs changing):

Missing a lot of `keras.backend` method documentation

### Clear description

For example, why should someone use this method? How is it useful?

In TF2.4 doc, a lot of methods in keras.backend are missing. E.g., Fig1 is the screenshot of v2.4, while Fig2 is the screenshot of v2.3.

![image](https://user-images.githubusercontent.com/5104719/102656451-bec4d500-4128-11eb-913e-cc4a3e27e58e.png)
![image](https://user-images.githubusercontent.com/5104719/102656515-d8661c80-4128-11eb-95eb-d7ba74c5d1fc.png)

### Correct links

Is the link to the source code correct? N/A

### Parameters defined

Are all parameters defined and formatted correctly? N/A

### Returns defined

Are return values defined? N/A

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

N/A

### Usage example

Is there a usage example? N/A

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by rmothukuru** [comment]
In the [Source Code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L2272), it is set not to generate the Docs.

**Comment by wuhy08** [comment]
Just curious, is this intentional?

**Comment by MarkDaoust** [comment]
Yes. @rmothukuru's link makes it clear that this is intentional.

`Keras.backend` was important when there were multiple backends. But now that there's only TensorFlow backend is much less important/useful. They chose a limited set that they thought were worth documenting.
