### ISSUE TITLE
Illegal instruction on older CPUs under version 2.4.0 

### ISSUE THREAD

**Issue by paciorek** [tensorflow/tensorflow#45866]
**System information**
- Ubuntu 18.04 and 20.04, Scientific Linux 7
- binary installed via pip
- version 2.4.0
- Python 3.8
- installed via pip (either inside or not inside a Conda environment)
- various CPU-only and GPU-hosting machines

**Describe the problem**

`import tensorflow` produces "Illegal instruction (core dumped)" on older machines (seemingly those that do not support AVX2 instructions). There is no problem on new machines (seemingly those that support AVX2 instructions). 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
pip install tensorflow
python -c "import tensorflow"
```

**Any other info / logs**

The core dump occurs on various machines with various types of CPUs. The common thread seems to be that it occurs on machines that don't support AVX2 instructions. Most of the machines on which this occurs do support AVX instructions. 

The issue does not occur with Tensorflow 2.3.1 nor with Tensorflow 2.5.0 installed via tf-nightly. 

Any chance Tensorflow 2.4.0 was built in a way (perhaps unintentionally) that requires AVX2 instructions or some other requirement that causes it to fail on somewhat older (but not really old) machines? Based on what I am seeing, it seems that using 2.4.0 on many machines will fail.

The same issue occurs when running in the official Tensorflow Docker container.

This seems related to issue #44668.

**Comment by amahendrakar** [comment]
> Any chance Tensorflow 2.4.0 was built in a way (perhaps unintentionally) that requires AVX2 instructions

@paciorek,
Yes, that is one of the requirements for TensorFlow. Starting with TensorFlow 1.6, the TensorFlow binaries use AVX instructions which may not run on older CPUs. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).

As an alternative, you can either [build](https://www.tensorflow.org/install/source) TensorFlow from source or use [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb). 

Thanks!

**Comment by paciorek** [comment]
I don't think the AVX dependency explains the issue.

1) We have various machines that support AVX (and therefore are listed in your hardware requirements as being supported, namely Ivy Bridge and Sandy Bridge) but not AVX2, and the issue occurs on these machines.

2) If the requirement is for AVX2, it would be helpful if this were documented so that users can simply check /proc/cpuinfo. As far as I can see, only a dependency on AVX is indicated.

3) Given the AVX dependency has been in place since TF 1.6, the AVX dependency does not explain why the problem occurs with Tensorflow 2.4.0 but not 2.3.1 or 2.5.0 from tf-nightly.

**Comment by desmoteo** [comment]
Same issue here, 2.3.1 works on machine with AVX but lacking AVX2 (AMD A10-6700 ). 
Version 2.4.0 fails instead

**Comment by wyqsmith** [comment]
Same issue @ E5-2650 V2 (Supports AVX but not supports AVX2), CentOS7 Kernel 3.10.0-1127.10.1, Python 3.8.6.

Version 2.3.1 Works well.

**Comment by byronyi** [comment]
cc @mihaimaruseac seems AVX2 got accidentally built into the 2.4 release? Didn't see that in release notes

**Comment by mihaimaruseac** [comment]
This is interesting. Will raise the issue internally, but given the holiday season will probably not be able to do anything until January

**Comment by mihaimaruseac** [comment]
We can try bisecting nightlies to see which commit range introduced the AVX2 dependency

**Comment by byronyi** [comment]
> We can try bisecting nightlies to see which commit range introduced the AVX2 dependency

@paciorek would you mind to try bisecting yourself? Not sure if a pre-AVX2 box is necessary for testing this as I don't have one myself...

**Comment by paciorek** [comment]
I won't be able to try until Thursday.

**Comment by cserpell** [comment]
I think this is the same of #45744 .

**Comment by SaschaHeyer** [comment]
Any updates on that topic?

**Comment by mihaimaruseac** [comment]
Same reply as in #45744.

Also, it seems we all have AVX2 enabled CPUs, so we cannot really bisect.

**Comment by mihaimaruseac** [comment]
Deduplicating to #45744 (randomly chosen among multiple duplicates)
