### ISSUE TITLE
Tensorflow's hwloc build force-enables use of sys/sysctl.h, which breaks on recent Linux/glibc

### ISSUE THREAD

**Issue by HadrienG2** [tensorflow/tensorflow#45861]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, openSUSE Tumbleweed, tested on various snapshots up to 20201216 .
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested.
- TensorFlow installed from (source or binary): Source.
- TensorFlow version: 1.15.2
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 9.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Tensorflow vendors the hwloc library and heavily customizes the way in which this library is built. I am not familiar enough with Bazel to fully understand the details of what you are doing here and the reasons why you are doing it, but unfortunately, what I do know is that on my machine, the net result is a broken hwloc build...

The immediate symptom is that some hwloc source files do not compile because they are configured to include the `<sys/sysctl.h>` header, which [has been removed from glibc >=2.32](https://sourceware.org/pipermail/libc-announce/2020/000029.html) because the underlying system call has been removed from the Linux kernel since release 5.5.

This is not a hwloc bug/incompatibility however, as it would intuitively seem, because the hwloc build system is perfectly able to figure out that this header does not exist and the hwloc source code knows how to avoid using it when that happens.

The actual problem is this line of the tensorflow build system: https://github.com/tensorflow/tensorflow/blob/1cd185160a061a1213e8e8d05eb078e880ac9e46/third_party/hwloc/BUILD.bazel#L113

For some reason that I do not know, it is pretty clear that you force-set the `HAVE_SYS_SYSCTL_H` define, which would normally be unset by the hwloc build system after it correctly detects that there is no `sysctl.h` header...

Removing this line of the `BUILD.bazel` file fixes the build on my machine, but I can only assume that you added it for some reason (most likely to make the build work on an operating system that does use the `sysctl.h` header, but on which the hwloc build system does not correctly detect said header ?), which means that the actual tensorflow patch will need to be more nuanced and only perform this patch on the OS configurations where it is necessary.

I am not able to easily share the build instructions that I followed because they are inside a mildly complicated build system within a closed-source project. But from my understanding of the problem, detailed reproducer instructions should not be necessary here, you should be able to easily replicate this issue just by trying to build tensorflow from source, through any method of your choosing, on any Linux distribution that uses glibc >=2.32. Although I personally observed this problem on openSUSE Tumbleweed, I would also expect it to reproduce identically on Gentoo, Arch, or Fedora 34...

**Comment by angerson** [comment]
Does this also happen on `master`? We no longer support the builds for the 1.15 branch, unfortunately. 

I couldn't find any reason for the flag to be set this way in our file history, so if it's still a problem on `master`, we can probably unset it.

**Comment by HadrienG2** [comment]
I did not try the master build yet, what I have checked so far is that...

1. Removing this line of the BUILD.bazel file fixes the build of tensorflow 1.15 on my machines.
2. This line is still present on the master version of BUILD.bazel.

...which gave me a reasonable suspicion that the build should still fail on master, and thus that the bug is worth reporting.

**Comment by angerson** [comment]
I'd think so too, but it'll be good to have a confirmation. If it's easy to try the build at `master` for you, can you verify that it also fails?

**Comment by HadrienG2** [comment]
After a quick try, given the same build configuration flags that we use on 1.15, but on a different system with a very different set of installed packages (which happens to be the only one that I have at hand right now), the build succeeds. Which solves my immediate problem.

However, I suspect that hwloc might not get built anymoe. Which means that the build could still start failing again given a different system configuration or set of configuration flags that do lead the tensorflow build to use hwloc again.

What leads me to believe this is that in the previous build configuration, I was able to find files associated with hwloc in `~/.cache/bazel`, and now I don't. Though I don't remember if I did search for these after I got my former build to succeed, so if bazel auto-cleans up this directory to some extent when the build succeed, that factor could also come into play.

Would you, per chance, remember or be able to easily figure out what circumstances lead the tensorflow build to try to build hwloc, so that I don't have to reverse-engineer this information myself?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
