### ISSUE TITLE
tensorflow/examples/android

### ISSUE THREAD

**Issue by grayscaler** [tensorflow/tensorflow#4586]
hi all

This example seems like a new version and i got some errors when i want to build the APK on android studio.
Dose any have same issue?

thanks for your time

<img width="1280" alt="2016-09-27 1 16 48" src="https://cloud.githubusercontent.com/assets/12976847/18844583/6ab64f50-8450-11e6-8099-b7af5ca8ef20.png">

**Comment by andrewharp** [comment]
The Java interface with tensorflow was moved to `tensorflow/contrib/android/java`. If you add that as an additional srcs directory it should work for you.

[build.gradle](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/build.gradle) should probably be updated to include this automatically.

**Comment by grayscaler** [comment]
It works, thanks for your helping.

**Comment by andrewharp** [comment]
https://github.com/tensorflow/tensorflow/commit/7f648692df34679d299093391bac45ed789d09ba adds contrib/android/java to the src dir list, so this should now work automatically.
