### ISSUE TITLE
Documentation for tf.keras.backend.max is missing

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#45871]
## URL(s) with the issue:

Please provide a link to the documentation entry:
https://www.tensorflow.org/api_docs/python/tf/keras/backend/max?hl=FA

## Description of issue (what needs changing): 
Go to https://www.tensorflow.org/s/results?q=keras.backend.max and click on the first link (in fact, any link related to that API).

The link to the API, **`tf.keras.backend.max`** is not available. Is it intentional, because, in the [Source Code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L2272), it is set **not to generate the Docs**.

If it is intentional, can you please explain why? Is there a better alternative to this API, or you have plans to Deprecate it, etc..

### Correct links

Is the link to the source code correct? : No (Link for the API itself is missing)

### Parameters defined

Are all parameters defined and formatted correctly? : No

### Returns defined

Are return values defined? : No

### Usage example

Is there a usage example? : No

### Submit a pull request? : 
I'm ready to submit a PR to remove this [line of code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L2272) if it is fine with you.

**Comment by ymodak** [comment]
duplicate #45860
