### ISSUE TITLE
Illegal instruction  CPUs under version 2.4.0

### ISSUE THREAD

**Issue by momen** [tensorflow/tensorflow#45872]
System information

OS: Ubuntu 18.04
TensorFlow binary installed using pip
TensorFlow version 2.4.0rc0
Python version 3.8.6
CUDA/cuDNN version: 11.0/8.0.4
GPU model: GTX 1080 ti
Describe the current behavior

Attempting to import tensorflow produces an "Illegal instruction" error.

Describe the expected behavior

Import tensorflow without error. (Illegal instruction)

python -c "import tensorflow as tf"

**Comment by amahendrakar** [comment]
@momen,
Could you please provide the make and model of your CPU? Starting with v1.6, TensorFlow binaries use AVX instructions which may not run on older CPUs. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) for installing TensorFlow.

Also, please check similar issues [#33038](https://github.com/tensorflow/tensorflow/issues/33038#issuecomment-538470776), [#29788](https://github.com/tensorflow/tensorflow/issues/29788#issuecomment-505571104) and let us know if it helps. Thanks!
