### ISSUE TITLE
tf.compat.v1.get_variable does not reuse variables within a scope and same variable name

### ISSUE THREAD

**Issue by tyagi619** [tensorflow/tensorflow#45876]
1-  Tensorflow version = **2.4.0**

2- **Google Colab Notebook** 

The following code from the documentation of [tf.compat.v1.variable_scope](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) throws **assertionError**

```
def foo():
  with tf.compat.v1.variable_scope("foo", reuse=tf.compat.v1.AUTO_REUSE):
    v = tf.compat.v1.get_variable("v", [1])
  return v

v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.
assert v1 == v2
```

Here is a screenshot of the error:
![Screenshot from 2020-12-19 19-52-16](https://user-images.githubusercontent.com/35839837/102691633-e6549400-4233-11eb-86a7-58a860acb263.png)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/58f9b10bb2454d4f2832d251d59a4de5/45876.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@tyagi619,
Can you please respond to the [above comment](https://github.com/tensorflow/tensorflow/issues/45876#issuecomment-750749305)? Thanks!

**Comment by tyagi619** [comment]
Yes that solves the issue. But I think the documentation must mention that eager execution must be disabled before running the particular piece of code

**Comment by rmothukuru** [comment]
@tyagi619,
The generic comment is present in the documentation of [Disable Eager Execution](https://www.tensorflow.org/api_docs/python/tf/compat/v1/disable_eager_execution)  and in the Migration Guide from 
**`Tensorflow 1.x to 2.x`**. 

It will be difficult to specify that for every `API`, as there are [many APIs](https://www.tensorflow.org/api_docs/python/tf/compat/v1) using `tf.compat.v1`.

**Comment by rmothukuru** [comment]
@tyagi619,
Closing this issue as it has resolved your error. Adding the command to `disable eager execution` in the documentation will be tracked in #46133. Thanks!
