### ISSUE TITLE
SavedModel FROM OFFICAL DOCS always returns the same class( use OFFICAL DOCS' CODE TO PREDICT)

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#45877]
Hello every1!
I'm learning tensorflow to predict multi classes images. And I first use **OFFCIAL DOCS** to learn.
url's here( a transfer learning ex): 
tensorflow.google.cn/tutorials/images/transfer_learning

and I add only two lines of code to export my model, like this:
```
# keras_model_path = './keras_save'
# model.save(keras_model_path)
```
After that, i tried to use this model to make a simple prediction of dogs and cats, like this:
```
from keras.models import load_model
from keras.preprocessing import image
import tensorflow as tf
import numpy as np

model = load_model('keras_save')

img = image.load_img('imgs_to_predict/1.jpg', target_size=(160,160))
img_array = tf.expand_dims(image.img_to_array(img), 0)
predictions = model.predict(img_array)
score = tf.nn.softmax(predictions[0])

class_names = ['cats','dogs'] # right names, use a code to print when generated the model

print(
    "This image most likely belongs to {} with a {:.2f} percent confidence."
    .format(class_names[np.argmax(score)], 100 * np.max(score)))
```
and, it's basically from this **offical doc**, here:
tensorflow.google.cn/tutorials/images/classification

the last part of it, the only thing is the image which the doc used is from Internet.

When trying to make a classification, the output always :
`This image most likely belongs to cats with a 100 percent confidence.`
even it's a **cat,** a **dog** ,or a **sunflower** from the offical doc.

I'm wondering what's wrong with it, and thanks for all guys who answering my question. Appreciate! :)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/92ef3c316fb0d67bec1f985c83d299d1/45877.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@ghost,
Sorry for the delayed response. Can you please let us know if this issue still persists? Thanks!
