### ISSUE TITLE
Ubuntu18.04 running on WSL2: "libcuda.so.1" does not exist. How to create that?

### ISSUE THREAD

**Issue by dushyantkumr1** [tensorflow/tensorflow#45882]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:

```
def test_sum():
    assert sum([1, 2, 3]) == 6, "Should be 6"

if __name__ == "__main__":
    test_sum()
    print("Everything passed")

    # import tensorflow as tf
    import tensorflow.compat.v1 as tf       # To get TF 1.x like behaviour in TF 2.0 one can run
    tf.disable_v2_behavior()

    print(tf.__version__)
    print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 running on WSL2
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.4.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?:: installed using conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA11.0/ cuDNN8
- GPU model and memory: 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 running on WSL2
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.4.0
- Python version:
- Installed using virtualenv? pip? conda?:: installed using conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA11.0/ cuDNN8
- GPU model and memory: Quadro RTX 4000, 8GB

-   **Exact command to reproduce**:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

### Describe the problem
The number of GPU available is being shown to be zero. 

I am getting following output:
 
```
(base) dushyant@DESKTOP-U96RKFC:/mnt/c/Windows/System32$ python3 /home/$USER/test.py
Everything passed
2020-12-19 12:47:55.757762: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /home/dushyant/miniconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2.4.0
2020-12-19 12:47:56.642478: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-12-19 12:47:56.645707: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.0/lib64:
2020-12-19 12:47:56.645745: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2020-12-19 12:47:56.645767: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-U96RKFC): /proc/driver/nvidia/version does not exist
Num GPUs Available:  0
```
Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.0/lib64:

I searched for libcuda.so.1 in my directory: "LD_LIBRARY_PATH: /usr/local/cuda-11.0/lib64:" and elsewhere. It does not seem to exist.

I also search for 'libcuda.so*' and found the following:
```
(base) dushyant@DESKTOP-U96RKFC:/mnt/c/Windows/System32$ find /usr/ -name 'libcuda.so*'
/usr/local/cuda-11.0/doc/man/man7/libcuda.so.7
/usr/local/cuda-11.0/targets/x86_64-linux/lib/stubs/libcuda.so
```

I am under impression that I can create "libcuda.so.1". However, I have no idea how to create that. Any help would be appreciated.

**Comment by amahendrakar** [comment]
@dushyantkumr1,
Could you please let us know if you have installed CUDA/cuDNN on Windows or on WSL?

Also, please go through [this guide](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) from NVIDIA and let us know if it helps. Thanks!

**Comment by victoryang00** [comment]
Sounds like Nvidia does not provide the runtime support for WSL2.

I use the `CMakeList.txt` file to make my test program compilable
```cmake
cmake_minimum_required(VERSION 3.11)
project(test_llvmgpu)

set(CMAKE_CXX_FLAGS "-I/usr/local/cuda/include ")
set(CMAKE_CXX_STANDARD 20)

add_executable(test_llvmgpu main.cpp)
target_link_libraries(test_llvmgpu /usr/local/cuda-11.0/targets/x86_64-linux/lib/stubs/libcuda.so)
```

**Comment by dushyantkumr1** [comment]
Hi Abhilash,

Yes, I was able to install that.

Would it be okay if I respond in a couple of days as I am busy with some
important submission? It will also take me some time to remember what
exactly I did.

You can email me at ***@***.***

Regards,
Dushyant

==============================

Dushyant Kumar

Dept. of Radiology,

University of Pennsylvania,

Philadelphia, PA, 19104
==============================
