### ISSUE TITLE
dynamic_rnn broken on master?

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#4588]
The following code works on TF 0.10 but fails on `master`:

```
import tensorflow as tf
i = tf.placeholder(tf.float32, shape=[1, None, 20])
cell = tf.nn.rnn_cell.GRUCell(30)
o = tf.nn.dynamic_rnn(cell, i, dtype=tf.float32)
```

The autogenerated documentation for `master` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.nn.dynamic_rnn.md) does not mention anything which could explain this.

The failure is the following exception:
```
ValueError: Time steps is not the same for all the elements in the input in a batch.
```
raised on line `915` of `rnn.py`

I could not find any issues in the issue tracker that address this.

**Comment by gibiansky** [comment]
This bug was introduced in [this commit](https://github.com/tensorflow/tensorflow/commit/bdb6e00b08b5023825eb9acd0e4e4fd1cbc6d01e).

I think it can be patched by changing the lines:
```python
got_time_steps = shape[0]
got_batch_size = shape[1]
```
to 

```python
got_time_steps = shape[0].value
got_batch_size = shape[1].value
```

**Comment by gibiansky** [comment]
Also, usability note: `dynamic_rnn` should check in advance that the provided `initial_state` has a shape. If it does not then it crashes deep down inside `dynamic_rnn` and it's really hard to understand why. The error it gives ends up being something like `as_list() is undefined on unknown TensorShape`, which gives no indication as to _which_ TensorShape is unknown.

**Comment by ebrevdo** [comment]
I can't replicate your error.  Are you using the most recent version of master?  Have you tried downloading a nightly?

These exact lines do not replicate the error for me:

```
import tensorflow as tf
i = tf.placeholder(tf.float32, shape=[1, None, 20])
cell = tf.nn.rnn_cell.GRUCell(30)
o = tf.nn.dynamic_rnn(cell, i, dtype=tf.float32)
```

**Comment by gibiansky** [comment]
I was using the most recent version of master at the time. I am building the current `master` from a clean slate and will see if I can still reproduce the error.

**Comment by gibiansky** [comment]
I have tested with current `master` and have confirmed the issue still exists.

`tf.__version__` returns `0.10.0`; `tf.__git_version__` returns `v0.10.0rc0-2191-gf38886b`; running `git log` in the TF repo I just built and installed gives the the latest commit of `f38886ba307314cc0ae5b15279f5693f39c92f21` (which confirms that the `tf.__git_version__` is correct).

**Comment by gibiansky** [comment]
Please let me know what else I can do to be helpful. This does not seem like it should be related to the platform because `rnn.py` is platform-independent; in addition, looking at the code the way it is on `master` confirms that this issue *should* happen (see my first comment for the code responsible).

**Comment by DavidNemeskey** [comment]
I could reproduce the issue as well. However, this is a sneaky one, as the behaviour differs between Python versions.

Apparently, when `const_{time|batch}` is `None`(, and the `Dimension`-typed `got_{time|batch}` is not),
1. Python 3.4.2 calls `Dimension.__eq__`, and negates the result
1. Python 3.5.2 calls `Dimension.__ne__`

Both return `None`, but
1. in the first case, the `if` then becomes `if not None`, so `if True`
1. in the second, it becomes `if None`, i.e. `if False`

I propose fixing the issue either as @gibiansky suggested, or just call `as_list()` on shape so that we have an `int`--`int` comparison.

**Comment by ebrevdo** [comment]
@gunan this is a hole in our jenkins testing infrastructure.

**Comment by ebrevdo** [comment]
@DavidNemeskey thanks for getting to the core of the issue.  If either you or @gibiansky wants to submit a PR I'd happily review.  if you dont have bandwidth i can push a change within the day.

**Comment by ebrevdo** [comment]
@mrry is this a directionality bug the TensorShape comparison code?

**Comment by mrry** [comment]
@ebrevdo `TensorShape.__eq__()` and `TensorShape.__ne__()` probably don't have the behavior you'd expect when some of the dimensions are unknown. (In particular, `(None, x) == (None, x)` and `(None, x) != (None, x)` both return `None` because the value is unknown.)

So this library code probably shouldn't be using `==` or `!=` to compare shapes. Use `merge_with()`, `assert_compatible_with()` etc. instead.

**Comment by gunan** [comment]
Do we have unit tests for this?
I can investigate the reason why the tests did not catch this.

**Comment by ebrevdo** [comment]
I think we test with Python 3.5 only?

**Comment by gunan** [comment]
Which test would this be?

**Comment by gibiansky** [comment]
Any progress on this? It's marked as 'awaiting response' but I'm not sure who this is waiting on.

I see this issue on Python 3.4 I believe.

**Comment by gunan** [comment]
I think the we had multiple conversations going on here.
1- Looks like we are open for contributions here, if you would like to create a PR to fix the issue, @ebrevdo agreed to review the fix.

2- It looks like our testing does not catch this issue. I was trying to see what we have for rnns as unit tests. We obviously need to expand them to catch this problem, and fix the issue. The fix can be packaged with an extension to the unit test for RNN.

**Comment by ebrevdo** [comment]
I'll see if I can get a fix + unit test in.

**Comment by ikrambennasrbennasr** [comment]
hello, please i run this code : 

from sparkdl import DeepImagePredictor
# Read images using Spark
image_df = ImageSchema.readImages("flower_photos/sample/")

predictor = DeepImagePredictor(inputCol="image", outputCol="predicted_labels", modelName="InceptionV3", decodePredictions=True, topK=10)
predictions_df = predictor.transform(image_df)


and i get this error : 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-d7bde844670d> in <module>()
      4 
      5 predictor = DeepImagePredictor(inputCol="image", outputCol="predicted_labels", modelName="InceptionV3", decodePredictions=True, topK=10)
----> 6 predictions_df = predictor.transform(image_df)

~/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_spark-deep-learning-1.0.0-spark2.3-s_2.11.jar/sparkdl/transformers/named_image.py in _transform(self, dataset)
     94             modelName=self.getModelName(),
     95             featurize=False)
---> 96         transformed = transformer.transform(dataset)
     97         if self.getOrDefault(self.decodePredictions):
     98             return self._decodeOutputAsPredictions(transformed)

~/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_spark-deep-learning-1.0.0-spark2.3-s_2.11.jar/sparkdl/transformers/named_image.py in _transform(self, dataset)
    327             outputMode=modelGraphSpec["outputMode"])
    328         resizeUdf = createResizeImageUDF(modelGraphSpec["inputTensorSize"])
--> 329         result = tfTransformer.transform(dataset.withColumn(resizedCol, resizeUdf(inputCol)))
    330         return result.drop(resizedCol)
    331 

~/anaconda3/lib/python3.6/site-packages/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_spark-deep-learning-1.0.0-spark2.3-s_2.11.jar/sparkdl/transformers/tf_image.py in _transform(self, dataset)
    145                                  "width": "__sdl_image_width",
    146                                  "num_channels": "__sdl_image_nchannels",
--> 147                                  "image_buffer": "__sdl_image_data"})
    148                 .drop("__sdl_image_height", "__sdl_image_width", "__sdl_image_nchannels",
    149                       "__sdl_image_data")

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_tensorframes-0.3.0-s_2.11.jar/tensorframes/core.py in map_rows(fetches, dframe, feed_dict, initial_variables)
    262     if isinstance(dframe, pd.DataFrame):
    263         return _map_pd(fetches, dframe, feed_dict, block=False, trim=None, initial_variables=initial_variables)
--> 264     return _map(fetches, dframe, feed_dict, block=False, trim=None, initial_variables=initial_variables)
    265 
    266 def map_blocks(fetches, dframe, feed_dict=None, trim=False, initial_variables=_initial_variables_default):

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_tensorframes-0.3.0-s_2.11.jar/tensorframes/core.py in _map(fetches, dframe, feed_dict, block, trim, initial_variables)
    150         builder = _java_api().map_rows(dframe._jdf)
    151     _add_graph(graph, builder)
--> 152     ph_names = _add_shapes(graph, builder, fetches)
    153     _add_inputs(builder, feed_dict, ph_names)
    154     jdf = builder.buildDF()

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_tensorframes-0.3.0-s_2.11.jar/tensorframes/core.py in _add_shapes(graph, builder, fetches)
     83             t = graph.get_tensor_by_name(op_name + ":0")
     84             ph_names.append(t.name)
---> 85             ph_shapes.append(_get_shape(t))
     86     logger.info("fetches: %s %s", str(names), str(shapes))
     87     logger.info("inputs: %s %s", str(ph_names), str(ph_shapes))

/tmp/spark-ad4dff5c-2eda-49cc-b5a8-b81ede3fac4b/userFiles-d4fb97fa-84ed-4aaf-8036-d6d38363201e/databricks_tensorframes-0.3.0-s_2.11.jar/tensorframes/core.py in _get_shape(node)
     36 
     37 def _get_shape(node):
---> 38     l = node.get_shape().as_list()
     39     return [-1 if x is None else x for x in l]
     40 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py in as_list(self)
    898     """
    899     if self._dims is None:
--> 900       raise ValueError("as_list() is not defined on an unknown TensorShape.")
    901     return [dim.value for dim in self._dims]
    902 

ValueError: as_list() is not defined on an unknown TensorShape.


Any help please ! Thanks

**Comment by dimagoldin** [comment]
@ikrambennasrbennasr did you find a solution? im getting the same error :(

**Comment by ikrambennasrbennasr** [comment]
Hi @dimagoldin  in fact I did not understand the main origin of this error. But what I do is create another environment and isntaller tensorflow with python3.6. This error did not appear to me.
