### ISSUE TITLE
Colab session getting restarted during conversion of the Boundless model

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#45885]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.4.0

## Colab Notebook for reproducing the issue
https://colab.research.google.com/gist/sayakpaul/baf963933cbc3e627e66f6330d66c519/boundless_tflite.ipynb

## Issue

When trying to convert the [Boundless model](https://tfhub.dev/google/boundless/quarter/1) Colab Notebook session is getting restarted and the converter is unable to generate the TensorFlow Lite model. 

## Code

```python
model_handle = https://tfhub.dev/google/boundless/quarter/1
model = hub.load(model_handle)
concrete_function = model.signatures['default']

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_function])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

**Note** that I did try to run the conversion without `converter.optimizations = [tf.lite.Optimize.DEFAULT]` and it does not help. 

## Logs

```
WARNING:tensorflow:Issue encountered when serializing model_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing model_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
WARNING:tensorflow:Issue encountered when serializing trainable_variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
to_proto not supported in EAGER mode.
```

## Useful references

The pre-trained Boundless model on TensorFlow Hub comes with [this tutorial](https://www.tensorflow.org/hub/tutorials/boundless). 

Anything I am missing out on during the conversion process?

**Comment by sayakpaul** [comment]
Cc: @MeghnaNatraj

**Comment by abattery** [comment]
I can confirm that there is an issue with TF 2.4.0 version.

You can convert the above model with Flex with TF nightly version.

**Comment by sayakpaul** [comment]
Okay let me try that out, thank you!

**Comment by sayakpaul** [comment]
Works with the suggestions given in https://github.com/tensorflow/tensorflow/issues/45885#issuecomment-748736435.
