### ISSUE TITLE
Cannot quantize only part of a QAT model for running on both Android CPU/DSP

### ISSUE THREAD

**Issue by xumengwei** [tensorflow/tensorflow#45887]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0-dev20201208
- Python version: 3.7

**Standalone code to reproduce the issue**
What I'm trying to do is to quantize part of a model, running quantize-aware training, and then deploy it to run on both Android CPU/DSP for inference. The code is below:

```
def apply_quantization(layer):
    if isinstance(layer, keras.layers.Conv2D):
        return tfmot.quantization.keras.quantize_annotate_layer(layer)
    return layer

annotated_model = keras.models.clone_model(
    base_model, # base_model is a mobilenetv2 or resnet50
    clone_function=apply_quantization
)
q_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
```
Then I try to convert it to a quantized tflite model (with only weights)

```
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.convert()
```
The tflite model works, but can only run on CPU but no op is delegated to DSP because the activations are not quantized (am I right?)

So I tried to quantize both weights and activations:

```
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.allow_custom_ops = True
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
```
The tflite model is generated, but I cannot initialize an interpreter with this model with following error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-3d7cc3476638> in <module>
      1 interpreter = tf.lite.Interpreter(model_content=m7)
----> 2 interpreter.allocate_tensors()
      3 input_index = interpreter.get_input_details()[0]["index"]
      4 output_index = interpreter.get_output_details()[0]["index"]
      5 print (input_index, output_index)

~/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    333   def allocate_tensors(self):
    334     self._ensure_safe()
--> 335     return self._interpreter.AllocateTensors()
    336 
    337   def _safe_to_run(self):

RuntimeError: tensorflow/lite/kernels/dequantize.cc:61 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 5 (DEQUANTIZE) failed to prepare.
```
I've checked the generated tflite model, it seems there're two consecutive DEQUANTIZE op inserted. Any one knows how to fix it?

**Comment by daverim** [comment]
Hi xumengwei@,

The current setting is a little strange since you have chosen to fully quantize the model with post-training quantization but only quantized-aware training for convolution layers. The current tooling is a little confused and adds inappropriate dequantize/quantize ops expecting the input model to not be quantized. We are working on a fix for this.

For the meantime, I verified that our new quantizer tooling handles the input qat model appropriately.
```
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.allow_custom_ops = True
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# add this line before convert()
converter._experimental_new_quantizer = True

tflite_model = converter.convert()
```

**Comment by xumengwei** [comment]
@daverim Thanks for your reply. I understand what's doing might sound minority. I want to quantize only certain layers (e.g., the 1st, 3rd conv layers) and keep others (e.g., the 2nd, 4th conv) as float32.

I've tried your the way you suggested using `_experimental_new_quantizer`. However, what I got is a fully quantized model instead of only some of them. As a result, the whole model is delegated to DSP. Do you have any idea how can I achieve my goal?

**Comment by daverim** [comment]
@xumengwei, ah that makes more sense, in that case, you don't want to apply post-training quantization, just quantize-aware-training conversion. Try the following:

```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
```

**Comment by xumengwei** [comment]
@daverim I've tried the way you suggested. Here is the complete code:

```
MODEL_NAME = 'mobilenetv2'
base_model = keras.applications.MobileNetV2(
    input_shape=(224,224,3), alpha=1.0, include_top=True, weights='imagenet',
    input_tensor=None, pooling=None, classes=1000,
    classifier_activation='softmax'
)
def apply_quantization(layer):
    if type(layer) == keras.layers.Conv2D:
        return tfmot.quantization.keras.quantize_annotate_layer(layer)
    return layer

annotated_model = keras.models.clone_model(
    base_model,
    clone_function=apply_quantization
)

q_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
# converter._experimental_new_quantizer = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
pathlib.Path('/tmp/tmp.tflite').write_bytes(tflite_model)
```

Basically I tried to quantize only Conv2D layers of a mobilenetv2 model. However, the generated model is quite weird: the `quantize` and `dequantize` layers always come after Conv2D layer together... Isn't the `quantize` layer before the Conv2D layer?

![image](https://user-images.githubusercontent.com/23546158/102842444-f5a92c80-4441-11eb-80f6-ad3c3f868116.png)

**Comment by xumengwei** [comment]
@daverim I've also tried a simpler, manually constructed model with direct quantization annotation `tfmot.quantization.keras.quantize_annotate_layer`. The code is following.

```
inputs = keras.layers.Input(shape=(224, 224, 3))
x1 = keras.layers.Conv2D(32, (3, 3), activation='relu')(inputs)
x2 = keras.layers.Lambda(lambda x: tf.identity(x))(inputs)
x2 = tfmot.quantization.keras.quantize_annotate_layer(
    keras.layers.Conv2D(32, (3, 3), activation='relu')
)(x2)
x = keras.layers.concatenate(inputs = [x1,x2])
x = keras.layers.MaxPool2D([5,5], strides=5)(x)
x = keras.layers.Flatten()(x)
x = keras.layers.Dense(2)(x)
base_model = keras.models.Model(inputs=inputs, outputs=x)
q_aware_model = tfmot.quantization.keras.quantize_apply(base_model)

converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter._experimental_new_quantizer = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
pathlib.Path('/tmp/tmp.tflite').write_bytes(tflite_model)
```
In this model, two conv layers take the same input and then their outputs are combined. I only quantize one of them. However, in the generated tflite model, both two conv layers are quantized...
<img width="370" alt="Screen Shot 2020-12-23 at 10 47 00 AM" src="https://user-images.githubusercontent.com/23546158/102953409-32415a80-450c-11eb-980e-162f7a8ba921.png">

**Comment by xumengwei** [comment]
@daverim can you help or involve other people who may be familiar with this issue?

**Comment by daverim** [comment]
Hi sorry for the delay, realized there were two bugs with this issue: workaround is posted  in

https://github.com/tensorflow/model-optimization/issues/523
