### ISSUE TITLE
Problem getting python include path

### ISSUE THREAD

**Issue by 9607835** [tensorflow/tensorflow#45886]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 & Cygwin
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.4.0-rc2
- Python version: 3.6.10
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.2.0

**Describe the problem**

```
ERROR: An error occurred during the fetch of repository 'local_config_python':
   Traceback (most recent call last):
        File "C:/cygwin64/home/username/tensorflow/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl
                _create_local_python_repository(repository_ctx)
        File "C:/cygwin64/home/username/tensorflow/third_party/py/python_configure.bzl", line 212, column 41, in _create_local_python_repository
                python_include = _get_python_include(repository_ctx, python_bin)
        File "C:/cygwin64/home/username/tensorflow/third_party/py/python_configure.bzl", line 152, column 21, in _get_python_include
                result = execute(
        File "C:/cygwin64/home/username/tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Problem getting python include path.
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\cygwin64\home\username\_bazel_username\5ud3wb25\external\local_config_python\usr\bin\python3" -c "from __future__ import print_function;from distutils import sysconfig;print(sysconfig.get_python_inc())"): The system cannot find the file specified.
 (error: 2)
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
INFO: Repository llvm-project instantiated at:
  C:/cygwin64/home/username/tensorflow/WORKSPACE:19:16: in <toplevel>
  C:/cygwin64/home/username/tensorflow/tensorflow/workspace.bzl:690:20: in tf_repositories
Repository rule tf_http_archive defined at:
  C:/cygwin64/home/username/tensorflow/third_party/repo.bzl:131:34: in <toplevel>
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Problem getting python include path.
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\cygwin64\home\username\_bazel_username\5ud3wb25\external\local_config_python\usr\bin\python3" -c "from __future__ import print_function;from distutils import sysconfig;print(sysconfig.get_python_inc())"): The system cannot find the file specified.
 (error: 2)
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
INFO: Elapsed time: 2.198s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    Fetching @local_execution_config_python; fetching
```

`C:\cygwin64\home\username\_bazel_username\5ud3wb25\external\local_config_python\` is an empty directory...

**Provide the exact sequence of commands / steps that you executed before running into the problem**

any of the following
```
$ bazel build '//tensorflow/tools/pip_package:build_pip_package'
$ env PYTHON_BIN_PATH='/usr/bin' bazel build '//tensorflow/tools/pip_package:build_pip_package'
$ env PYTHON_BIN_PATH='C:/cygwin64/usr/bin' bazel build '//tensorflow/tools/pip_package:build_pip_package'
```

**Any other info / logs**

I would of assumed it has something to do with bazel getting confused by cygwin paths (e.g. it can not handle any paths that have a space character in their own build script), but that would not explain why it is using such a bizarre path in the first place.

bazel can not be compiled from source, so that is not an option.
tensorflow can not be installed via pip, so that is not an option.

**Comment by 9607835** [comment]
As a desperate measure I tried the windows version of python3.8 and, WOW, it worked, I could install tensorflow... unfortunately the python program I am using depends on version 1 of tensorflow and assumes unix/linux system behavior, and tensorflow 1.8-1.15 can not be installed under any version of python(cygwin or windows)... so compiling tensorflow from source is still a general requirement.  

This problem may extend back to tensorflow versions before version 2, which would render the software I am trying to use effectively dead without a fix, which is how I am now forced to regard it lest more time be wasted.

**Comment by amahendrakar** [comment]
@9607835,
Could you please explain in detail the issue you are facing and also provide the exact sequence of commands that you executed before running into the error, so that we can look into this. Thanks!
