### ISSUE TITLE
Training a keras model on TPU pods?

### ISSUE THREAD

**Issue by steindor** [tensorflow/tensorflow#45899]
Hi!

Are there any examples on how to run a Keras model on TPU pods? I have a model which runs fine on a V3-8. However, when trying to run the same code on V3-32, it fails with the following error:

`Failed copying input tensor from /job:worker/replica:0/task:0/device:CPU:0 to /job:worker/replica:0/task:1/device:CPU:0 in order to run DatasetFromGraph: FetchOutputs node : not found [Op:DatasetFromGraph]`

The model is created and compiled within the TPU scope as recommended:

```
with strategy.scope():
    keras_model = create_model()
    optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08)
    keras_model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

```
I am running Tensorflow 2.3.1 whith the same version on the TPU.

I have already asked on StackOverflow without getting any good pointers / answers, see link here:

https://stackoverflow.com/questions/65331321/training-a-keras-model-using-tpu-pods?noredirect=1#comment115577267_65331321

Thanks!

**Comment by amahendrakar** [comment]
@steindor,
Please take a look at this [TPU usage guide](https://www.tensorflow.org/guide/tpu) and let us know if it helps. 

Also, could you please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by steindor** [comment]
Yes, I have been through the TPU usage guide before I opened this issue. I will try to create a code snippet which reproduces this.

**Comment by amahendrakar** [comment]
> I will try to create a code snippet which reproduces this.

@steindor,
Any updates regarding this? Did you get a chance to work on it? Thanks!

**Comment by steindor** [comment]
Yes, I ran the code example you gave me with v3-32 but did not get the same error so there is something else going on here. I'll close this since this is probably not related to tensorflow.
