### ISSUE TITLE
Can't use contrib.slim in tf 1.14

### ISSUE THREAD

**Issue by andreixxi** [tensorflow/tensorflow#45892]
I am running on google colab. 
`import tensorflow
print(tensorflow.__version__)`
after running this cell the output is 1.14.0 so I assume the above command `!pip install tensorflow==1.14` worked
but i have the following error: 
`import tensorflow.contrib.slim as slim`
---> ImportError: No module named contrib.slim
I've tried changing the import to `import tf_slim as slim` but i get a similar error: ImportError: No module named tf_slim

**Comment by amahendrakar** [comment]
@andreixxi,
`tensorflow.contrib` exists only in TensorFlow 1.x, which is not actively supported anymore. We'd recommend you to update TensorFlow to the latest stable version v2.4. Thanks!

**Comment by andreixxi** [comment]
@amahendrakar `tensorflow.contrib` does not work in tensorflow 2.4 either, it is deprecated. should i just try another method and give up and whole slim ?

**Comment by amahendrakar** [comment]
@andreixxi,
Please take a look at [this comment](https://github.com/tensorflow/models/issues/8020#issuecomment-572743379) from a similar issue and let us know if it helps. Thanks!

**Comment by andreixxi** [comment]
@amahendrakar i've tried installing it by using `pip install --upgrade tf_slim` and then `import tf_slim as slim`. i use google.colab for this project. the import works well in the cell, but when i try to `import tf_slim as slim` in a .py script i get the following error: <br>import tf_slim as slim
ImportError: No module named tf_slim
