### ISSUE TITLE
tf.data.experimental.assert_cardinality incompatible with INFINITE_CARDINALITY

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#45894]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: v1.12.1-47912-gec43aacb56f 2.5.0-dev20201219
- Python version: 3.7.7

**Describe the current behavior**: `tf.data.experimental.assert_cardinality`  can be used to fix `Dataset.cardinality` in instances where it cannot be inferred. In situations where the cardinality is infinite, this raises an error where it shouldn't.

**Describe the expected behavior** if `ds = ds_base.apply(tf.data.experimental.assert_cardinality(tf.data.INFINITE_CARDINALITY)`, then an error should be raised if `ds_base` stops producing elements, as opposed to when the first element is produced.

**Standalone code to reproduce the issue**
[Notebook](https://colab.research.google.com/drive/13s9geZzR4xUtYJ6ImINl0kuisL-n8H_6?usp=sharing)

Code (same as notebook):
```python
import tensorflow as tf

ds = tf.data.Dataset.range(5).repeat().flat_map(lambda i: tf.data.Dataset.range(i))
print(ds.cardinality() == tf.data.INFINITE_CARDINALITY)  # False
ds = ds.apply(tf.data.experimental.assert_cardinality(tf.data.INFINITE_CARDINALITY))
print(ds.cardinality() == tf.data.INFINITE_CARDINALITY)  # True

for example in ds.take(1):
    pass
# tensorflow.python.framework.errors_impl.FailedPreconditionError:
# Input dataset was expected to contain -1 elements but contained at least 1 element.
```

**Comment by rmothukuru** [comment]
@jackd,
As per [the documentation](https://www.tensorflow.org/api_docs/python/tf/data#other-members), this behavior seems to be expected. What do you think?

**Comment by jackd** [comment]
I think `tf.data.INFINITE_CARDINALITY` should consistently be used to indicate infinite cardinality, regardless of how it is encoded. I can understand why this error occurs, but I would consider it a bugged edge-case.

At the very least I would expect an error when creating  `tf.data.experimental.assert_cardinality` with a negative `cardinality` value, though that would just make me change this from a bug report to a feature request.

**Comment by aaudiber** [comment]
Thanks for reporting this @jackd! I agree with your assessment that it's a bugged edge-case, and submitted a fix so that asserting infinite cardinality will work as you described.
