### ISSUE TITLE
Single scalar summary point not visible in the plot

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#459]
When only one event is available for a scalar summary, the plot remains empty, as shown below (here the value is 2.0):
![snapshot2](https://cloud.githubusercontent.com/assets/331795/11701319/b1919762-9e83-11e5-8f85-fa1740c52c57.png)
It would be great to see one point corresponding to the value instead. The value does appear in the JSON/CSV file.

**Comment by danmane** [comment]
Agreed, this isn't great behavior! It's not that hard to fix so I'll try to get it for you soon :)

**Comment by pronobis** [comment]
Great, thanks!

**Comment by girving** [comment]
Dan fixed this a while ago.  Thanks Dan!
