### ISSUE TITLE
Number of Delegated Nodes

### ISSUE THREAD

**Issue by shlomi-amitai** [tensorflow/tensorflow#45902]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Ubunto 18
- TensorFlow installed from (source or binary):
- source 
- Tensorflow version (commit SHA if source):
- 2.4 nigthly
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
When I run my NN tflite quantized model on mobile device's DSP. I get the following message:

INFO: Hexagon delegate: 44 nodes delegated out of 67 nodes with 7 partitions.

When visualizing the tflite model, I see that the whole model was successfully quantized (FFQ or IOQ - w/ or w/o inputs/outputs) 
So, why only part of the model was delegated?
Is there a way to control or optimize this? how to make all the NN to go through the DSP?

(Model Attached)
[myModel2.zip](https://github.com/tensorflow/tensorflow/files/5724126/myModel2.zip)

**Comment by freedomtan** [comment]
because not all valid TfLite ops are supported by Hexagon delegate. you may want to check its [supported ops and constraints](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md)

**Comment by shlomi-amitai** [comment]
Thanks,
I followed the supported ops in the link you sent and replaced all suspecios ops with supported ones.
Yet, nothing changed and I still get one third of my ops not delegated.
is there a way to know which ops specifically were not delegated? could you have a look in the model I've attached?
[myModel_ffq2.zip](https://github.com/tensorflow/tensorflow/files/5724934/myModel_ffq2.zip)

Thanks

**Comment by karimnosseir** [comment]
Unsupported nodes in the model:

Unsupported node 0 QUANTIZE
Unsupported node 1 QUANTIZE
Unsupported node 5 CONV_2D
Unsupported node 13 CONV_2D
Unsupported node 16 CONV_2D
Unsupported node 20 CONV_2D
Unsupported node 34 CONV_2D
Unsupported node 40 CONV_2D
Unsupported node 47 CONV_2D
Unsupported node 63 TRANSPOSE_CONV
Unsupported node 65 DEQUANTIZE

For Quantize/Dequantize they are from/to float which we don't run on the DSP. If you changed your model to have inputs and outputs as int8 they will be gone.

For Conv2D, we currently only supports 
dilation_height_factor/dilation_weight_factor  == 1 and stride_height/stride_width <= 3
In your case dilation is the reason it is not delegated.

For TransposeConv, we currently don't handle bias - it was added in TFLite recently.
If it is blocker for your case, we are happy to add support to the bias for you.

**Comment by shlomi-amitai** [comment]
Thank you!
I'm afraid dilation rate > 1 is much more crucial for me, since it enables you to enlarge your features space per conv operation.
Do you plan to support this any time soon?

**Comment by shlomi-amitai** [comment]
BTW, could replace conv dilation with AveragePooling(dilationFactor) -> conv2d(dilation =1)  -> Upsampling(dilationFactor) but unfortunately other 2 operations are not supported as well.

**Comment by shlomi-amitai** [comment]
I also tried to remove all unsupported ops (besides quantization of float inputs) and yet I get  
INFO: Hexagon delegate: 33 nodes delegated out of 39 nodes with 3 partitions.
Seems like some of the conv ops are still not delegated (dilation=1, stride<=3).
Attached is the model.
[myModelV3_fullDSP.zip](https://github.com/tensorflow/tensorflow/files/5729993/myModelV3_fullDSP.zip)

**Comment by karimnosseir** [comment]
For the last model shared, the unsupported ops are
- Quantize/Dequantize: Same comment as my previous comment to get rid of them.
- TransposeConv: In this model it is different than the previous one. I have a fix will send it shortly and will look in adding the bias later.
- -ResizeBilinear: We support size < 66 at the moment, the reason is because we noticed that in some cases Hexagon NN implementation loses a lot of accuracy, so we disabled it. If you're building from source, i can point you how to enable it for testing if it doesn't cause a lot of accuracy issue for you.

For dilated conv, sure we can look in adding support to dilated conv2d. If i recall correctly Hexagon NN limits to strides 1 for dilated version.

Will update the issue here when changes lands.

Thanks

**Comment by karimnosseir** [comment]
The TransposeConv issue in the last model should be fixed now. Wait for the latest nightly if you're relying on nightly or build from master again.
Will update when other changes land.

Thanks

**Comment by shlomi-amitai** [comment]
Thanks, I will check and update.

**Comment by karimnosseir** [comment]
Update:
TransposeConv with bias support was merged. Please try it and let us know if you're having issues.

Next, add support for the dilated conv support. Will update when it is also added.

Thanks

**Comment by twkx** [comment]
> Update:
> TransposeConv with bias support was merged. Please try it and let us know if you're having issues.
> 
> Next, add support for the dilated conv support. Will update when it is also added.
> 
> Thanks

Hi,

Thanks for supporting bias now!

I kindly report you that I have found an issue in TransponseConv with bias.

I've just filled a new issue: #51093 

Best,

**Comment by karimnosseir** [comment]
Thanks @twkx for reporting this. Will follow on the other issue.
Thank again.

**Comment by liyuming1978** [comment]
is there any tools and ways  to know which ops is support or not in dsp

**Comment by karimnosseir** [comment]
We have them listed here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md

**Comment by mohantym** [comment]
Hi @shlomi-amitai !
We are checking to see whether you still need help in this issue . 

All the operations are not supported in GPU delegates. That is why, Some operations will be delegated and some will be skipped.

You should devise a policy to fallback to CPU/NNAPI/XNNPack delegates (instantiate all the supported delegates from device , Switch to a different other delegate incase it finds an supported op for a delegate)

For best results, Please [benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#benchmark-multiple-performance-options-in-a-single-run) your Lite model against GPU/XNNPack/CPU/Multithreads prior using a fallback policy.

Thankyou

**Comment by FabianSchuetze** [comment]
Thanks for your explanation @karimnosseir . Your explanation below was very interesting:

> Unsupported nodes in the model:
> 
> Unsupported node 0 QUANTIZE
 Unsupported node 1 QUANTIZE 
Unsupported node 5 CONV_2D 
Unsupported node 13 CONV_2D 
Unsupported node 16 CONV_2D 
Unsupported node 20 CONV_2D 
Unsupported node 34 CONV_2D 
Unsupported node 40 CONV_2D 
Unsupported node 47 CONV_2D 
Unsupported node 63 TRANSPOSE_CONV
Unsupported node 65 DEQUANTIZE
> 
> For Quantize/Dequantize they are from/to float which we don't run on the DSP. If you changed your model to have inputs and outputs as int8 they will be gone.
> 
> For Conv2D, we currently only supports dilation_height_factor/dilation_weight_factor == 1 and stride_height/stride_width <= 3 In your case dilation is the reason it is not delegated.
> 
> For TransposeConv, we currently don't handle bias - it was added in TFLite recently. If it is blocker for your case, we are happy to add support to the bias for you.


How did you obtain the unuspported nodes programmatically? I don't see a good logging mechanism to highlight unsupported nodes. Did you just print nodes without a delegate?
