### ISSUE TITLE
Better shape inference for tf.slice and tf.strided_slice

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#4590]
Currently, if any of the values in the `size` argument is not a constant, the output shape is completely unknown (but the correct rank):

``` python
>>> z = tf.zeros((1, 2, 3))
>>> z.get_shape().as_list()
[1, 2, 3]
>>> m = tf.slice(z, [0, 0, 0], [-1, -1, -1])
>>> m.get_shape().as_list()
[1, 2, 3]
>>> m = tf.slice(z, [0, 0, 0], [tf.constant(1) + 0, -1, -1])
>>> m.get_shape().as_list()
[None, None, None]
```

The desired behaviour would instead treat the second and third dimensions correctly:

``` python
>>> m = tf.slice(z, [0, 0, 0], [tf.constant(1) + 0, -1, -1])
>>> m.get_shape().as_list()
[None, 2, 3]
```

Looking briefly at the code, this would requite being a bit more clever in terms of how constant values are computed; right now if anything in a `Pack`-ed array is unknown at graph construction time, the entire array is unknown (see `_ConstantValue`'s `Pack` case).

I guess this request ends up being just a request for a better constant propagation system which supports partially-known tensors. Perhaps you already have other use cases for such a feature, in which case view this as just another request that such a feature would enable.

**Comment by tatatodd** [comment]
Thanks for filing the issue @gibiansky!

Do you have a use-case where the current shape inference behavior is making it hard or impossible to do something?  That will make it easier for us to prioritize this general class of problems.

FYI there is a trade-off between full-blown shape inference including const-propagation, vs simpler code.  So it's not obvious that full-featured shape inference will always be worth it.  Of course this is a philosophical statement; that's why concrete examples are always helpful to determine priorities.

**Comment by gibiansky** [comment]
Sure. What motivated filing this was a confusing error message and non-obvious solution with regard to `dynamic_rnn`. I was slicing a part of my input sequence (for example I needed to train on times T_0 through T_end, where T_end is computed as part of the graph) using `tf.slice`. However `dynamic_rnn` requires that the input has the last dimension defined (since that dimension is the dimension of the network input). As a result of the bug above, the output of `tf.slice` is of completely unknown shape, and so `dynamic_rnn` fails. It's possible to fix this with a `tf.reshape` with a constant dimension, but this is definitely a suboptimal situation (and non-obvious). Does that make sense?

**Comment by tatatodd** [comment]
@gibiansky yes that makes sense, and thanks for the clear write-up!  :)

FYI the following commit added the current logic:
https://github.com/tensorflow/tensorflow/commit/5989d094ae15011c9a8a92d6fbcd829be71afa12

There's a technical detail that makes it hard for us to implement better shape inference when the size argument is only partially known.  I'll think about this a bit.

**Comment by tatatodd** [comment]
@gibiansky Indeed, I think it's possible to implement, but it's a bit involved.

I'm marking this as Contributions welcome for now, since using `tf.reshape` always works as a workaround.

**Comment by aselle** [comment]
This is also an issue for strided_slice.

**Comment by yongtang** [comment]
I created a PR #13561 to improve the shape inference so that as long as the size is not `-1`, the right shape value will be inferred:
```python
>>> import tensorflow as tf
>>> z = tf.zeros((1, 2, 3))
>>> z.get_shape().as_list()
[1, 2, 3]
>>> m = tf.slice(z, [0, 0, 0], [tf.constant(1) + 0, 2, -1])
>>> m.get_shape().as_list()
[None, 2, None]
```
*Note: The above example used to return `[None, None, None]`*.

The PR is not a completely fix for this issue. It is an improvement nevertheless.

**Comment by wt-huang** [comment]
@yongtang Thanks for the PR! Closing this for now, stay tuned for future improvement.
