### ISSUE TITLE
How to catch/expect the error: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#45900]
TF version 1.x and 2.x.

Is there a way to catch this error with try-expect in python?

`F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1`

**Comment by amahendrakar** [comment]
@kiflowb777,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by kiflowb777** [comment]
https://stackoverflow.com/questions/65405886/how-to-catch-expect-the-error-f-tensorflow-core-common-runtime-gpu-gpu-event-mg

**Comment by imad08** [comment]
hey ! I am a begginer in open source although I know tensorflow etc but I want to contribute can someone tell from where can I find issues for begginers like me

**Comment by kiflowb777** [comment]
https://stackoverflow.com/questions/32391561/how-to-catch-exception-caused-in-c-in-python

**Comment by amahendrakar** [comment]
> https://stackoverflow.com/questions/65405886/how-to-catch-expect-the-error-f-tensorflow-core-common-runtime-gpu-gpu-event-mg

@kiflowb777,
Can we please close this issue, as it is being tracked on StackOverflow? Thanks!
