### ISSUE TITLE
How to catch internal TensorFlow error: 'GPU sync failed' in python?

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#45901]
TF version 1.x and 2.x.

Is there a way to catch this error with try-expect in python?

`tensorflow.python.framework.errors_impl.InternalError: GPU sync failed`

**Comment by amahendrakar** [comment]
@kiflowb777,

Please take a look at the below code snippet and check if it works. 

```
try:
   # do something
   pass

except InternalError:
   # handle InternalError exception
   pass

```

Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is a larger community that reads questions there. Thanks!

**Comment by kiflowb777** [comment]
Thank you, can we assume that every InternalError is the 'GPU sync failed' error?

**Comment by kiflowb777** [comment]
https://stackoverflow.com/questions/65395940/how-to-catch-internal-tensorflow-error-gpu-sync-failed-in-python

**Comment by kiflowb777** [comment]
This InternalError can also be thrown in other cases:
```
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(63, 494), b.shape=(494, 2048), m=63, n=2048, k=494
	 [[{{node tower_0/MatMul}}]]
	 [[concat/concat/_99]]
  (1) Internal: Blas GEMM launch failed : a.shape=(63, 494), b.shape=(494, 2048), m=63, n=2048, k=494
	 [[{{node tower_0/MatMul}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by kiflowb777** [comment]
There is some way to check if an **InternalError** is the '**GPU sync failed**' error without comparing string?

**Comment by kiflowb777** [comment]
```
try:
   #do_something

except InternalError as e:
   if is_e_a_gpu_sync_failed(e):
      #do something

```

**Comment by amahendrakar** [comment]
@kiflowb777,
Could you please provide a minimal code snippet of the issue you are facing, so that we can reproduce the issue on our end and look into this. Thanks!

**Comment by kiflowb777** [comment]
This error is random. 
It depends mainly on the network size,  number of input images and dimensions. 
Often when there is no memory in the graphics card.

I will try to provide the code that often throws this error.
