### ISSUE TITLE
regression: dropped Support of CUDA® architecture 5.0?

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#45904]
I'm using trying to use tensorflow 2.4 with nvidia 960m (compute compatibility 5.0)

According to the following change: https://github.com/tensorflow/docs/commit/cb886cfdd16d66ff7f8d1430676ff395b02910e6

Support of my card and many others have been dropped (My card at least definitely worked fine with tensorflow 2.2)

This is a major regression for many who are trying to upgrade, and currently, it is not even clear to me if it's intended and what is the rational behind it. If it is intended, please document it prominently in the 2.4 release. (and please consider not dropping the support of this architecture)

**Comment by amitport** [comment]
Hi, @amahendrakarI are you sure this is not a regression? AFAIKT, a year ago tensorflow supported all cuda architectures greater than 3.5

**Comment by ymodak** [comment]
I think this was intentional change. See https://github.com/tensorflow/tensorflow/issues/41892#issuecomment-667452483

**Comment by amitport** [comment]
It's bad for tensorflow maintainers among others, I'm sure many issues could just be resolved when considering they are running an unsupported compute version, but even not all maintainers seem to be familier with this new limitation.

Also, got do admit I don't follow why/how `3.5`, `3.7`, `5.2`, `6.0`, and `6.1` are supported but specifically `5.0` is skipped (https://www.tensorflow.org/install/gpu) when in the 2.3 release notes we have: "PTX is not compiled before version `7.0`".

**Comment by MiWeiss** [comment]
Side note for docker users landing here - because they are not able to use their gpus anymore:

The problems you may have when trying to run with gpus from the docker image `tensorflow/tensorflow:gpu-latest` appear not to be related to this issue: Using `tensorflow/tensorflow:gpu-nightly` works.

**Comment by sanjoy** [comment]
TF 2.4 should support CC 5.0, please see announcement [here](https://groups.google.com/a/tensorflow.org/g/developers/c/uCKQeiTA3u8/m/xDBWKcrUAgAJ).

The list of compute capabilities on https://www.tensorflow.org/install/gpu is stale, we will fix it soon.

**Comment by ymodak** [comment]
The gpu docs have been updated commit [b5c78b0](https://github.com/tensorflow/docs/commit/430fe3be375a1f3f6267b86300e1c0f1d79b2b26#diff-db2f8c542d222b663b56e2614d6e42b9531606ded976427355d2c7442d6eee43).
See https://www.tensorflow.org/install/gpu#hardware_requirements
Thanks!
