### ISSUE TITLE
Error using custom activation function while mixed precision enable

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#45919]
Config
```
TensorFlow 2.3
```

I already posted in [SO](https://stackoverflow.com/questions/65403976/typeerror-using-custom-activation-function-while-mixed-precision-enabled), a few hours ago without any response until now. But I need a quick pointer. 

----

### Problem

I was trying to use a **custom activation** in **mixed-precision** enabled training pipelines but faced the following error:

```
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
```

### Reproduce 

Enabling Mixed precision...

```
import tensorflow as tf 

policy = tf.keras.mixed_precision.experimental.Policy('mixed_float16')
tf.keras.mixed_precision.experimental.set_policy(policy)
print('Mixed precision enabled')
```

Custom activation... 

```
def ARelu(x, alpha=0.90, beta=2.0):
    alpha = tf.clip_by_value(alpha, clip_value_min=0.01, clip_value_max=0.99)
    beta  = 1 + tf.math.sigmoid(beta)
    return tf.nn.relu(x) * beta - tf.nn.relu(-x) * alpha
```

Training...

```
import tensorflow as tf

(xtrain, ytrain), (xtest, ytest) = tf.keras.datasets.mnist.load_data()

def pre_process(inputs, targets):
    inputs  = tf.expand_dims(inputs, -1)
    targets = tf.one_hot(targets, depth=10)
    return tf.divide(inputs, 255), targets

train_data = tf.data.Dataset.from_tensor_slices((xtrain, ytrain)).\
    take(10_000).shuffle(10_000).batch(8).map(pre_process)
test_data = tf.data.Dataset.from_tensor_slices((xtest, ytest)).\
    take(1_000).shuffle(1_000).batch(8).map(pre_process)

model = tf.keras.Sequential([
                             
            tf.keras.layers.Conv2D(filters=16, kernel_size=(3, 3), strides=(1, 1),
                                   input_shape=(28, 28, 1), activation=ARelu),
            tf.keras.layers.MaxPool2D(pool_size=(2, 2)),

            tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), strides=(1, 1), 
                                   activation=ARelu),
            tf.keras.layers.MaxPool2D(pool_size=(2, 2)),

            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(64, activation=ARelu), 
            tf.keras.layers.Dense(10, activation='softmax', dtype=tf.float32)]) 

opt = tf.keras.optimizers.Adam()

model.compile(loss='categorical_crossentropy', optimizer=opt)
history = model.fit(train_data, validation_data=test_data, epochs=10)

# ------------------

TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
```

However, without mixed-precision, it works. I understand the problem simply types miss match but where I should look into it? 

Additionally, while trying to solve it, I've found that using `tf.keras.mixed_precision.LossScaleOptimizer` is safe to avoid numeric underflow. Is it something that we should use for mixed-precision training?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/641251e2fb3ab5eeb4d30fc646d43f21/45919-2-4.ipynb). Thanks!

**Comment by innat** [comment]
Are you telling me to get the gist or to the person whom you assigned? lolz

**Comment by rmothukuru** [comment]
@innat,
> Are you telling me to get the gist or to the person whom you assigned? lolz :octocat:

It is an instruction to next level Engineers, so is the status, **`Awaiting Tensorflower`**.

**Comment by innat** [comment]
## Solved 

I have to typecast the input 

```
def ARelu(x, alpha=0.90, beta=2.0):
    alpha = tf.clip_by_value(alpha, clip_value_min=0.01, clip_value_max=0.99)
    beta  = 1 + tf.math.sigmoid(beta)
	x = tf.cast(x, 'float32')
    return tf.nn.relu(x) * beta - tf.nn.relu(-x) * alpha
```

But I'm not sure by doing this, do we lose the benefit of mixed-precision as well.
