### ISSUE TITLE
TF-TRT conversion failing (maybe because of 2GB limit on GraphDef)

### ISSUE THREAD

**Issue by dshahrokhian** [tensorflow/tensorflow#45910]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Linux 16.04
- TensorFlow installed from (source or binary): No
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080

**Describe the current behavior**
While trying to convert a RoBERTa model to TRT, it throws an error: `KeyError: "The name 'input_word_ids:0' refers to a Tensor which does not exist. The operation, 'input_word_ids', does not exist in the graph."`

But after checking with `saved_model_cli`, it is indeed part of the graph. Investigating a bit further, this might happen because of another (previous) error:

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/message_lite.cc:406] tensorflow.GraphDef exceeded maximum protobuf size of 2GB: 2222908841
```

**Describe the expected behavior**

It should convert it to TRT, as it successfully happens when using a smaller model (e.g. `DistilRoBERTa`).

**Standalone code to reproduce the issue**
```
from tensorflow.python.compiler.tensorrt import trt_convert as trt

converter = trt.TrtGraphConverterV2(
    input_saved_model_dir=<saved model directory>, 
    conversion_params=trt.TrtConversionParams()
)

converter.convert()
converter.save(<output dir>)
```

Additional info:
Related to https://github.com/tensorflow/tensorrt/issues/229

**Comment by amahendrakar** [comment]
@dshahrokhian,
Could you please provide the saved model files you are using in the code, so that we can reproduce the issue on our end.

Also, please update TensorFlow to v2.4 and check if you are facing the same issue. Thanks!

**Comment by amahendrakar** [comment]
>     input_saved_model_dir=<saved model directory>,

@dshahrokhian,
In order to reproduce the issue, could you please share the contents of the `saved model directory` folder with us.

Alternatively, you can update TensorFlow on your machine using the below command and check if it works.

```
pip3 install --upgrade tensorflow
```

 Thanks!

**Comment by dshahrokhian** [comment]
This error does not happen with TF 2.4, thanks.
