### ISSUE TITLE
FullyConnected reference_integer_ops miscalculate output data due to endianness issue on s390x

### ISSUE THREAD

**Issue by skribm9** [tensorflow/tensorflow#45921]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): Ubuntu 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The Test case `//tensorflow/lite/micro/examples/hello_world:hello_world_test` failed on s390x with error:

```
Testing LoadModelAndPerformInference
0. (1.0*2^-127) near value (-1.1018541*2^0) failed at tensorflow/lite/micro/examples/hello_world/hello_world_test.cc:103
0.841 (1.6819992*2^-1) near value (-1.1018541*2^0) failed at tensorflow/lite/micro/examples/hello_world/hello_world_test.cc:111
0.141 (1.1279996*2^-3) near value (-1.1018541*2^0) failed at tensorflow/lite/micro/examples/hello_world/hello_world_test.cc:118
-0.959 (-1.9179993*2^-1) near value (-1.1018541*2^0) failed at tensorflow/lite/micro/examples/hello_world/hello_world_test.cc:125
0/1 tests passed
~~~SOME TESTS FAILED~~~
```

On debugging, I found that `GetTensorData<int32_t>(bias)` returns tensor data in LE format, where bias is an Optional Input Tensor being populated in `Eval` as ```const TfLiteTensor* bias = GetOptionalInputTensor(context, node, kBiasTensor);```

This tensor data of bias is used in reference_integer_ops FullyConnected in calculation of `acc`. 
I tried a solution of byte-swapping this data while populating `acc` which fixed the test case. The solution looked like this:
```
if (bias_data) {
#if FLATBUFFERS_LITTLEENDIAN
        acc += bias_data[out_c];
#else
        acc += __bswap_32(bias_data[out_c]);
#endif
``` 
in [fully_connected.h](https://github.com/tensorflow/tensorflow/blob/bba12d0401800fbf873ea35f34517a8c47a54272/tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h#L54)

Since, I do not have a view of the reach and use of this optional tensor, can you please suggest if there is another way that you would like me to try or if I should PR this solution?

**Describe the expected behavior**
The tensor data on BE systems must be in correct format and the test case should pass.

**Standalone code to reproduce the issue**
To reproduce the issue, please run this test case:
```
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial -k --test_timeout 300,450,1200,3600 --build_tests_only -c dbg --copt=-O -c opt --copt=-g --strip never --color=yes --curses=yes --test_output=errors --verbose_failures  -- //tensorflow/lite/micro/examples/hello_world:hello_world_test
```

**Other info / logs**

**Comment by skribm9** [comment]
I found that a similar fix is also required for `micro_speech_binary_mock_test` and `micro_speech_test` test cases to pass on s390x. The changes are required in [depthwise_conv.h](https://github.com/tensorflow/tensorflow/blob/60b9283c9e5308bae6fe19d2db531a6c230baffd/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h#L105). Here also, the bias data needs to be byte-swapped before populating `acc`.

**Comment by skribm9** [comment]
Hi @advaitjain , just posting an update here.. 
In tensorflow release 2.4.1, this solution causes regression to `//tensorflow/lite/micro/kernels:fully_connected_test` and similarly, fix in  `depthwise_conv.h` causes `//tensorflow/lite/micro/kernels:depthwise_conv_test` test case to fail. 
It seems that these tests require `bias_data` to be in Little Endian format and is handling data accordingly while for `hello_world_test` and micro_speech_tests, `bias_data` is being used in calculation assuming that it's in BE format and hence, it's messing up the calculation of `acc`.

**Comment by kun-lu20** [comment]
Any updates from the community for this issue? Thanks!

**Comment by kun-lu20** [comment]
Hi @advaitjain , hope all is well.

Wonder if you have any updates reg this issue? Thanks!

**Comment by kun-lu20** [comment]
This issue could be closed since test case `//tensorflow/lite/micro/examples/hello_world:hello_world_test` has been moved out of [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repository.

**Comment by pjpratik** [comment]
Hi @kun-lu20 @skribm9 

I was checking if this issue still persists.

The `hello_world_test` is now `evaluate_cc_test` as given [here](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/hello_world#run-the-tests-on-a-development-machine).

I've tried running 
`bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial -k --test_timeout 300,450,1200,3600 --build_tests_only -c dbg --copt=-O -c opt --copt=-g --strip never --color=yes --curses=yes --test_output=errors --verbose_failures  -- //tensorflow/lite/micro/examples/hello_world:evaluate_cc_test` and was able to build successfully without any error.

Please find the screenshot below.

<img width="565" alt="Screenshot 2023-04-11 at 10 46 13 PM" src="https://user-images.githubusercontent.com/118897289/231240618-7af9559b-1daf-4cbc-ae44-143283b8b684.png">

Please feel free to close the issue if it is resolved.

Thanks.

**Comment by kun-lu20** [comment]
Hi @pjpratik ,

Thanks for checking this! 

Since this test case has been moved out of [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repo, we are not tracking it on s390x any more. Could you please close this issue? Thanks again.

**Comment by pjpratik** [comment]
@kun-lu20 Thanks for the confirmation.
