### ISSUE TITLE
label_image build fails for stm32f1

### ISSUE THREAD

**Issue by vaibhavjadhav377** [tensorflow/tensorflow#45925]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution : ubuntu 18.04
- TensorFlow installed from : Source
- Tensorflow commit: bba12d0401800fbf873ea35f34517a8c47a54272 (Branch:Master)
- Target platform : Arm

I am trying to build target 'stm32f1' at location tensorflow/lite/tools/make/targets in file stm32f1_makefile.inc 
for this I am using toolchain provided at https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm for x86_64 which is Pre-built GNU bare-metal toolchain for 32-bit Arm processors.
while building label_image I am getting error saying that it was not able to find #include <dlfcn.h>

Following are the steps to produce this issue: (in tensorflow dir)
$./tensorflow/lite/tools/make/download_dependencies.sh
export the tools from toolchain downloaded from above link.
And modified the build_rpi_build.sh where I changed TARGET_ARCH to TARGET and passes TARGET=stm32f1.

**Comment by terryheo** [comment]
TFLite isn't buildable with the embedded tool chain.
It works with A-profile architecture toolchain.
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a

For stm32f1, you'd better play with TFLite micro.
https://www.tensorflow.org/lite/microcontrollers
