### ISSUE TITLE
No algorithm Worked

### ISSUE THREAD

**Issue by 876arham** [tensorflow/tensorflow#45926]
Getting this error when using the code in collab

Found 14400 images belonging to 2 classes.
Found 400 images belonging to 2 classes.
Epoch 1/50
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-28-86598d638a85> in <module>()
     15         epochs=50,
     16         validation_data=test_generator,
---> 17         validation_steps=800)

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    853       # In this case we have created variables on the first call, so we run the
    854       # defunned version which is guaranteed to never create variables.
--> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    856     elif self._stateful_fn is not None:
    857       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
-> 2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 
   2945   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

NotFoundError:  No algorithm worked!
	 [[node sequential_2/conv2d_6/Conv2D (defined at <ipython-input-26-b3f11172c6da>:17) ]] [Op:__inference_train_function_3219]

Function call stack:
train_function

My code on colab i was just testing a random CNN architecture on my dataset
https://colab.research.google.com/drive/1mb7c3Dg6CDwcjYitp85uNpa_A6il1J6f?usp=sharing

**Comment by ravikyram** [comment]
@876arham 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let me know which TF version you are using?.
Request you to share sample input files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by 876arham** [comment]
https://www.kaggle.com/lijiyu/bossbase?select=boss_256_0.4_test is the dataset i am using

version 2.4.0 tensorflow

**Comment by ravikyram** [comment]
@876arham 

I have tried in colab with TF nightly version(`2.5.0-dev20201223`) .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b5ca4794ebaad0ee7cf8d0c0744b2c17/untitled.ipynb).You are also seeing the same behavior?
Thanks!
