### ISSUE TITLE
Linking issue: undefined reference to `tflite::micro::GetTensorShape SparkfunEdge

### ISSUE THREAD

**Issue by fadelgaber** [tensorflow/tensorflow#45927]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2
- Python version: many versions including latest
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): gcc 7.5
- CUDA/cuDNN version: N/A
- GPU model and memory: intel onboard graphics

**Describe the current behavior**
Currently trying to run the magic wand examples from another project that is written in C (one of the FreeRTOS examples on SparkFun Edge).
I compiled the magic wand examples, moved all the .o files to the other project and tried compiling the other project together with linking the TFLite .o files. The linking step generated the following errors:

```
../gcc/edge/bin/fully_connected.o: In function `EvalFloat':
/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:192: undefined reference to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)'
/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:194: undefined reference to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)'
/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:196: undefined reference to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)'
/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:198: undefined reference to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)'
../gcc/edge/bin/fully_connected.o: In function `EvalQuantizedInt8':
/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:124: undefined reference to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)'
../gcc/edge/bin/fully_connected.o:/home/fadel/Desktop/Projects/ml/tensorflow/tensorflow/lite/micro/kernels/fully_connected.cc:126: more undefined references to `tflite::micro::GetTensorShape(TfLiteEvalTensor const*)' follow
collect2: error: ld returned 1 exit status
```
This is the exact same problem as this: https://github.com/tensorflow/tensorflow/issues/41821 except that I am not using the "CMSIS-NN" tag anywhere.

**Describe the expected behavior**
Successful linking of the code.

**Standalone code to reproduce the issue**
*Download any FreeRTOS example from SparkFun's repository, ex: https://github.com/sparkfun/SparkFun_Apollo3_AmbiqSuite_BSPs/tree/6398086a1a87ddea78274521683ba3ad817bee82/common/examples/ble_freertos_tag
*Compile the magic wand example
*Copy all the created .o files to the /src/gcc directory of the FreeRTOS
*Use an "extern C" to allow magic wand's main() function to be called from a C interface (FreeRTOS project is in C).
*Call the main() function in the FreeRTOS project.
*Edit the Makefile of the RTOS project to link all the .o files from the magic wand example
*Compile the FreeRTOS example, the error will show at the linking step.

I know that it's time-consuming to replicate this, I can provide my repositories that contains the ready made Makefiles, etc. However, perhaps you know what the issue is just from reading the above.

**Comment by fadelgaber** [comment]
Issue solved by linking the microlite library produced by the makefile together with the magic wand's .o files.

Will leave this issue open as perhaps this is indeed a bug and the compiled .o files should provided the whole runtime environment.

**Comment by wangtz** [comment]
Hi fadelgaber,

GetTensorShape is defined in tensorflow/lite/micro/kernels/kernel_util.cc 
Could you check if kernel_util.o is included in your project and if it contains the required symbol (you can use `nm` to list all symbols in .o files.

I have an old FreeRTOS + BLE + Magic Wand demo project. It is very old. Some of the scripts might no work anymore so I've kept it private for now. I've granted you the access permission in case you find anything useful.

Let me know how it goes.

Thanks,
Tiezhen

**Comment by sushreebarsa** [comment]
@fadelgaber Could you please try as per the above comment  and let us know if this issue still persists ?Thanks!
