### ISSUE TITLE
Feature clolumns  cannot be used in the keras model, it may be a bug

### ISSUE THREAD

**Issue by anavanab99** [tensorflow/tensorflow#45924]
## URL(s) with the issue:
https://tensorflow.google.cn/api_docs/python/tf/keras/layers/DenseFeatures

### Clear description

I have made a keras function API model, which uses' fit_generator 'for multiple input. If you don't use tensorflow feature columns, the model can work normally, but if you use feature columns to input to densefeatures layer, the model will not work. It looks like a bug, because the same code has been tried before, and the model works
For example, why should someone use this method? How is it useful?

### Usage example

my code:
set use_feature_columns=False can work but,set use_feature_columns=True,it can't work.

https://colab.research.google.com/drive/18e-T5UYi__uzsMmavXTj86pM9GPhqe7I?usp=sharing

**Comment by amahendrakar** [comment]
@anavanab99,
I do not have access to the Colab notebook you have linked. Could you please provide the required permissions to view the files. Thanks!
