### ISSUE TITLE
TensorFlow 1.5 API : Error : 'DatasetV1Adapter' object does not support indexing

### ISSUE THREAD

**Issue by ssnirgudkar** [tensorflow/tensorflow#45938]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from : Binary (from docker image)
- TensorFlow version : 1.15
- Python version: 2.7.17
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Error emitted by TensorFlow API:
TypeError: 'DatasetV1Adapter' object does not support indexing

**Describe the expected behavior**
No error

**Standalone code to reproduce the issue**
images, labels = read_list ( data_dir, data_list ) <= here data_dir is full path of dir. containing image & label files. data_list is a text file, 2 column containing names of image file and label file.
The output is an array consisting of full path of images & corresponding labels.

queue = tf.data.Dataset.from_tensor_slices([images, labels])
img_contents = tf.io.read_file(queue[0]) <= Error location
label_contents = tf.io.read_file(queue[1])

TypeError: 'DatasetV1Adapter' object does not support indexing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here is the traceback of the real code - 

Traceback (most recent call last):
  File "wasr_train_noimu.py", line 462, in <module>
    main()
  File "wasr_train_noimu.py", line 315, in main
    coord)
  File "/wasr/wasr_models/image_reader.py", line 249, in __init__
    self.image, self.label, self.imu = read_images_from_disk(self.queue, self.input_size, random_scale, random_mirror, ignore_label, img_mean)
  File "/wasr/wasr_models/image_reader.py", line 180, in read_images_from_disk
    img_contents = tf.io.read_file(input_queue[0])
TypeError: 'DatasetV1Adapter' object does not support indexing

The code in 'Standalone code' section is a gist of the actual code. 

I have looked at various posts including [this](https://github.com/tensorflow/tensorflow/issues/28995) one where it is mentioned that the issue is fixed in version 1.5 but I am still encountering it. I have also gone through the TensorFlow 1.5 documentation but could not understand why I am seeing this issue or what is the correct way to use the API if my code is not correct.
Any help will be highly appreciated.
Thanks,
-Shailesh

**Comment by ravikyram** [comment]
@ssnirgudkar 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by ssnirgudkar** [comment]
Here you go -
import tensorflow as tf
imageList=[]
imageList.append("a.png")
imageList.append("b.png")
imageT=tf.convert_to_tensor(imageList, dtype=tf.string)
queue = tf.data.Dataset.from_tensor_slices(imageT)
img_contents = tf.io.read_file(queue[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'DatasetV1Adapter' object does not support indexing

I may be making some silly mistake but I do not what!

**Comment by ravikyram** [comment]
@ssnirgudkar 

Can you please upgrade to latest stable TF version 2.4 , nightly version and see if the issue still persists. Thanks!

**Comment by ssnirgudkar** [comment]
I cannot easily upgrade to TF 2.4 because there are other dependencies which have to managed as well. It will take me number of days to do so with significant efforts.
I will appreciate if you can acknowledge that this is a bug & it exists in TF 1.5 & can be fixed in 1.5.

**Comment by ssnirgudkar** [comment]
Also with the steps which I have provided you should be able to verify if the code works in TF 2.4 or not.

**Comment by mihaimaruseac** [comment]
We only patch old releases for security issues. 1.15 is too old and we cannot build it effectively if we are to patch other issues (since then they can cause further damage, so we'd need to test 100% of the test suite but this is impossible at the moment)

**Comment by marchss** [comment]
@mihaimaruseac  Thank you for your response. Could you please kindly look at the conflicting doc string in the same issue here https://github.com/tensorflow/tensorflow/issues/28995
