### ISSUE TITLE
Name argument ignored in operations

### ISSUE THREAD

**Issue by servandoa** [tensorflow/tensorflow#45937]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version (use command below): v2.4.0-0-g582c8d236cb, 2.4.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to create a named operation is just ignored and the default value is generated. 
`
x = tf.keras.Input(shape=4, name="X", dtype="float32")
y = tf.keras.Input(shape=4, name="Y", dtype="float32")
ex = tf.math.exp(x, name="exponential_X")
lx = tf.math.log(x, name="log_X")
xy = tf.multiply(x, y, name="XY")
nx = tf.norm(x, name="norm_X")
rmx =  tf.reduce_mean(x, name="reduce_mean_X")
print(x.name)
print(ex.name)
print(lx.name)
print(xy.name)
print(nx.name)
print(rmx.name)

z = tf.Variable(1.0, name="Z")
ez = tf.math.exp(x, name="exponential_Z")
print(ez.name)
`
X
tf.math.exp_11/Exp:0
tf.math.log_6/Log:0
tf.math.multiply_5/Mul:0
tf.compat.v1.norm_3/norm/Squeeze:0
tf.math.reduce_mean_2/Mean:0
tf.math.exp_12/Exp:0

**Describe the expected behavior**
Output should be the names defined on the operation.

**Standalone code to reproduce the issue**
[Above example in Google Colab.](https://colab.research.google.com/drive/1Yc8pQoXK1MiGIPEGH-Ls9TKHpUMsrVqz)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@servandoa,
Looks like this is simliar to issue #45401, #43844 and #43840.

Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/45401#issuecomment-738957954) from a member of the TensorFlow team for more information. Thanks!

**Comment by servandoa** [comment]
Many thanks,
Apologies, I search for it as an open issue.
Regards,
