### ISSUE TITLE
saved_model.save write .pb with read only permissions that can't be removed even with admin permissions

### ISSUE THREAD

**Issue by MaxxTr** [tensorflow/tensorflow#45935]
### System information

* OS: Windows 10
* ONNX 1.8.0
* ONNX_TF 1.7.0
* TENSORFLOW 2.4.0
* Desktop
* Python 3.7.3
* CUDA 460.89
* running from anaconda3:
_anaconda_depends         2019.03                  py37_0
anaconda                          custom                   py37_1
anaconda-client                1.7.2                       py37_0
anaconda-navigator         1.9.7                        py37_0
anaconda-project              0.8.3                       py_0

I'm trying to convert onnx model to tensorflow and create pb file.
The conversion is successful, but the save .pb directory has "read only" attribute that can't be removed even when I'm running as admin (after removing it returns back)...

CODE:

`    onnx_model = onnx.load(onnx_model_path)
    
    tf_rep = prepare(onnx_model)
    
    tensorflow.saved_model.save(
        tf_rep.tf_module,
        tensorflow_model_path)
`

How it looks like:
![image](https://user-images.githubusercontent.com/2767433/102983532-e5ae4d00-4514-11eb-9ca7-6e2ed910772e.png)

NOTE: I also used a built in function " export_graph" - same issue

**Comment by amahendrakar** [comment]
@MaxxTr,
This seems like an issue with Windows rather than a TensorFlow issue. Could you please get in touch with Microsoft Windows regarding this. Thanks!

**Comment by MaxxTr** [comment]
@amahendrakar For me it looks like pure tensorflow issue, as simple python write file at this case works fine, so when tensorflow save your data tensorflow somehow changes the permissions

**Comment by amahendrakar** [comment]
@MaxxTr,
Could you please provide a minimal code snippet of the issue you are facing, so that we reproduce it on our end and look into it. Thanks!

**Comment by MaxxTr** [comment]
Hi @amahendrakar  please pay attention that the code snippet was provided:

`
 onnx_model = onnx.load(onnx_model_path)

tf_rep = prepare(onnx_model)

tensorflow.saved_model.save(
    tf_rep.tf_module,
    tensorflow_model_path)
`

**Comment by amahendrakar** [comment]
@MaxxTr,
The given code snippet is incomplete. On running the code, I am facing an error stating `NameError: name 'onnx_model_path' is not defined`.

In order to reproduce the issue reported here, please provide Python script/notebook you are running along with all the files required to run the code. Thanks!

**Comment by MaxxTr** [comment]
@amahendrakar  it's kind of obvious that this path is undefined... this is the path to the model. Do you have one ? ( I assume you should as you are support person and work with all that stuff day to day)

**Comment by amahendrakar** [comment]
@MaxxTr,
On running the code with a sample model, I see that `.pb` has both read and write permissions. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/37bb6f83164e685da27e1cb0452c594d/45935.ipynb#scrollTo=hXvXTn6CkdBf&line=1&uniqifier=1). Thanks!

**Comment by MaxxTr** [comment]
Good day @amahendrakar.
Looks like you tested that on linux, but not on windows. Am I right ?

**Comment by amahendrakar** [comment]
@MaxxTr,
Yes, that's right. I have tested the code on a Linux machine. Thanks!

**Comment by MaxxTr** [comment]
@amahendrakar , yes but the problem is reported on windows. So isn't it wrong to test it on linux and say that everything is ok ?

**Comment by mohantym** [comment]
Hi @MaxxTr ! 
I downloaded  the onnx file from Github and ran the above code in my local windows machine in the 2.8 version . It was not in read only mode by default. Attaching screenshots for proof. [dir_model](https://user-images.githubusercontent.com/86464649/157797772-e1f413f0-e8f8-4c41-a428-fabdcb5283f9.png), [saved_model](https://user-images.githubusercontent.com/86464649/157797723-042a7362-fb11-4d26-9c57-43f7dd58ace7.png). Can you let us know from your side too?
