### ISSUE TITLE
Float model size is lesser than dynamic-range model size

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#45932]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.5.0-dev20201222
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am converting the [Boundless model](https://arxiv.org/pdf/1908.07007.pdf) to TensorFlow Lite. While the model conversion is successful and the inference works as expected there's an inconsistency in the model sizes. Currently, the dynamic-range quantized model size is ~14 MB whereas the float16 quantized model size is ~7MB. 

**Describe the expected behavior**

Float16 model size should be higher, technically twice the size of the dynamic-range quantized model. 

**Standalone code to reproduce the issue**
Colab Notebook - https://colab.research.google.com/github/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/Boundless_TFLite.ipynb. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/017181b3d5102244f8d9abeaa4cf734e/45932-2-5.ipynb#scrollTo=MrtANUkQser-). Thanks!

**Comment by daverim** [comment]
Hi sayakpaul@

From looking at your model it appears that it is implemented as all tensorflow ops (`tf.lite.OpsSet.SELECT_TF_OP`). While float16 quantization is supported when using Tensorflow ops by dequantizing constant tensors at runtime, dynamic range quantization is not supported when using Tensorflow ops, so your dynamic range model is identical to the float model.

I am adding an internal bug for dynamic range to work similar to the float16 in the flex case. In the meantime, this is expected behavior when a model only uses Tensorflow ops.

**Comment by sayakpaul** [comment]
Useful to know this @daverim. I guess this point is worth reflecting on in the Flex ops documentation. WDYT @daverim?

**Comment by teijeong** [comment]
Hi @sayakpaul,

In the code, it seems you also have to provide `tf.lite.OpsSet.TFLITE_BUILTINS` to `supported_ops`. 

https://www.tensorflow.org/lite/guide/ops_select#convert_a_model

**Comment by sayakpaul** [comment]
@teijeong so it should be the following, right

```python
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_function])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS, 
    tf.lite.OpsSet.TFLITE_BUILTINS]
```

**Comment by teijeong** [comment]
Great! :)
