### ISSUE TITLE
Tensorflow operations : Invalid data type according to Tensorflow Profiler

### ISSUE THREAD

**Issue by RocaVincent** [tensorflow/tensorflow#45946]
Hi,

I use Tensorflow 2.5 installed from source with Cuda 11.1 and Cudnn 8 on Ubuntu 20.04. My GPU is a Nvidia Quadro RTX 6000. 

I have got Out of Memory problems with the GPU and the training of a CycleGAN model. In order to track memory leaks in my code, I have run it with [profiler trace](https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/Trace) and I can now see with Tensorboard strange results in the memory breakdown table (memory profile tab). Indeed, some Tensorflow operations have "INVALID" data type, no region type and no shape. This suggests there are bugs with some Tensorflow operations.

Above I put a minimal code sample which reproduces this kind of error.

```
import tensorflow as tf
import keras

IMAGE_SHAPE = [256,256,3]

def Discriminator():
    return keras.Sequential([
        keras.layers.Flatten(input_shape=IMAGE_SHAPE),
        keras.layers.Dense(1, activation="sigmoid")
    ])

def Generator():
    return keras.Sequential([
        keras.layers.Conv2D(filters=IMAGE_SHAPE[-1], kernel_size=3, strides=1, padding="same", use_bias=False,
                           input_shape=IMAGE_SHAPE)
    ])

generator_BtoA = Generator()
discriminator_A = Discriminator()

loss_obj = keras.losses.MeanSquaredError()

discriminator_A_optimizer = keras.optimizers.Adam(0.0002)

BATCH_SIZE = 32

@tf.function
def train_step():
    # training discriminator
    imagesA = tf.random.uniform([BATCH_SIZE]+IMAGE_SHAPE)
    imagesB = tf.random.uniform([BATCH_SIZE]+IMAGE_SHAPE)
    fakesA = generator_BtoA(imagesB, training=False)
    with tf.GradientTape(persistent=True) as tape:
        disc_fakesA = discriminator_A(fakesA, training=True)
        discA_loss = loss_obj(tf.zeros_like(disc_fakesA), disc_fakesA)
    gradients_discA = tape.gradient(discA_loss, discriminator_A.trainable_variables)
    discriminator_A_optimizer.apply_gradients(zip(gradients_discA, discriminator_A.trainable_variables))


from tensorflow.profiler.experimental import Trace as Trace_profiler, start as start_profiler, stop as stop_profiler

start_profiler("my_logdir/")
with Trace_profiler("train", step_num=1, _r=-1):
    train_step()
stop_profiler()
```

With this code, I get the following results in the memory profile tab :

Op Name | Allocation Size (GiBs) | Requested Size (GiBs) | Occurrences | Region type | Data type | Shape
-- | -- | -- | -- | -- | -- | --
sequential/conv2d/Conv2D | 0.227 | 0.227 | 1 |   | INVALID
sequential/conv2d/Conv2D | 0.039 | 0.039 | 1 |   | INVALID
sequential/conv2d/Conv2D | 0.023 | 0.023 | 1 | output | float | [32,3,256,256]
sequential/conv2d/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer | 0.023 | 0.023 | 1 | output | float | [32,3,256,256]

How do you interprete these results ?

**Comment by amahendrakar** [comment]
@RocaVincent,
> I have got Out of Memory problems with the GPU and the training of a CycleGAN model.

To resolve the out of memory error, please try any one of the methods to limit GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).


Also, please go through these guides for [tensorboard profiling tool](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) and [memory profile summary](https://www.tensorflow.org/guide/profiler#memory_profile_summary) for more information. Thanks!

**Comment by RocaVincent** [comment]
@amahendrakar 

> To resolve the out of memory error, please try any one of the methods to limit GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).

I have already tried to allow memory growthing but there is still the problems.
 
> Also, please go through these guides for [tensorboard profiling tool](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) and [memory profile summary](https://www.tensorflow.org/guide/profiler#memory_profile_summary) for more information.

That's what I've done and that's what I've explained in the first post with in addition a minimal code sample to reproduce the results with the profiler, you may have missed it.

I'm curious to know if people get the same results with this code (run the code and access the dir *my_logdir* with the profiler).

**Comment by amahendrakar** [comment]
I did not face any out of memory errors on running the code, however I did get similar results with the memory profiler on TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/efd7fe9f22efd676bf9e08dea1bbc573/45946.ipynb). 

![Screenshot 2020-12-24 at 11 18 40 PM](https://user-images.githubusercontent.com/57165142/103173584-f4349580-4881-11eb-8d57-1b5a63982fc1.png)

Thanks!

**Comment by rmothukuru** [comment]
@RocaVincent,
Can you please respond to the above comment? Thanks!

**Comment by RocaVincent** [comment]
@rmothukuru
My issue is about the strange results that the profiler gives with this convolutions with invalid data type, no shape and no region type. Of course, I haven't OOM errors with this simple code either, but it points out some problems which may cause OOM with bigger models.

**Comment by ckluk-github** [comment]
Hi, 
I think I replied you regarding this issue in https://github.com/tensorflow/profiler/issues/255
We are still investigating (delayed due to the holidays).
thanks

**Comment by parkournerd** [comment]
I have this issue with Conv1D also. My model should be using under 200MB, but I have INVALID shape when profiling and the heap usage spikes to 4GB.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5c8e82c1710e65a412c03ca82743b06b/untitled188.ipynb)..Thanks !

**Comment by bastienjalbert** [comment]
> I have this issue with Conv1D also. My model should be using under 200MB, but I have INVALID shape when profiling and the heap usage spikes to 4GB.

Got almost exactly the same. With Conv2D. It causes that 7go of memory are fried, even if the network need no more than 200Mo to run...

![image](https://user-images.githubusercontent.com/12199444/133930589-8ee0aeb7-7b7a-4587-98b8-ca8a82250ec8.png)
![image](https://user-images.githubusercontent.com/12199444/133930604-2f90851e-550e-40a6-8594-b35362595b81.png)

Does anybody have found a solution or an idea of that ?

**Comment by yichunkuo-pony** [comment]
Has similar issue, any update? @ckluk-github

**Comment by isabellahuang** [comment]
Running into the same issue as well.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
