### ISSUE TITLE
Tensorflow 1.14 is not recognizing custom operator: Posenet_Decoder_Op

### ISSUE THREAD

**Issue by lupitia1** [tensorflow/tensorflow#45944]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux 2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: --
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 3.7
- Installed using virtualenv? pip? conda?: using virtualenv and pip
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source):  gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-11)
- CUDA/cuDNN version: --
- GPU model and memory: --

**Describe the problem**
I have been trying to run this model: [posenet](https://github.com/google-coral/project-posenet/blob/master/models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder.tflite) but it retrieves an error in the decoder part indicating you need a custom operator called PosenetDecoderOp. I investigated what to do and I approached this problem installing Tensorflow from source adding the custom operators. After compilation and instalation of Tensorflow I tried to run my code again:

              _``import numpy as np
              import tensorflow as tf
              
              #Load the TFLite model and allocate tensors.
              interpreter = tf.lite.Interpreter(model_path="posenet_mobilenet_v1_075_481_641_quant_decoder.tflite")
              interpreter.allocate_tensors()
              
              #Get input and output tensors.
              input_details = interpreter.get_input_details()
              output_details = interpreter.get_output_details()
              
              #Test the model on random input data.
              input_shape = input_details[0]['shape']
              input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
              interpreter.set_tensor(input_details[0]['index'], input_data)
              
              interpreter.invoke()
              output_data = interpreter.get_tensor(output_details[0]['index'])
              print(output_data)``_

And I got the following error:
`  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ec2-user/decoder/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "tf_run_model.py", line 5, in <module>
    interpreter = tf.lite.Interpreter(model_path="posenet_mobilenet_v1_075_481_641_quant_decoder.tflite")
  File "/home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 76, in __init__
    _interpreter_wrapper.InterpreterWrapper_CreateWrapperCPPFromFile(
  File "/home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 28, in <module>
    _tensorflow_wrap_interpreter_wrapper = swig_import_helper()
  File "/home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_tensorflow_wrap_interpreter_wrapper', fp, pathname, description)
  File "/usr/local/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/ec2-user/decoder/lib/python3.7/site-packages/tensorflow/lite/python/interpreter_wrapper/_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite3ops6custom27Register_POSENET_DECODER_OPEv`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
Please follow the instruction at https://github.com/google-coral/project-posenet#the-poseengine-class

The above PosenetDecoderOp is not a part of the TFLite project but it is a part of the project posenet. You need to register the custom op before invoking the TFLite interpreter. Please refer the custom op guide document: https://www.tensorflow.org/lite/guide/ops_custom

https://github.com/google-coral/edgetpu/tree/master/src/cpp/posenet

**Comment by lupitia1** [comment]
> Please follow the instruction at https://github.com/google-coral/project-posenet#the-poseengine-class
> 
> The above PosenetDecoderOp is not a part of the TFLite project but it is a part of the project posenet. You need to register the custom op before invoking the TFLite interpreter. Please refer the custom op guide document: https://www.tensorflow.org/lite/guide/ops_custom
> 
> https://github.com/google-coral/edgetpu/tree/master/src/cpp/posenet

Thank you so much abattery, I'm trying this and I will update with the results.

**Comment by lupitia1** [comment]
Hello again @abattery 

> Please follow the instruction at https://github.com/google-coral/project-posenet#the-poseengine-class
> 
I tried this but it is no posible to run the model cause I'm using the cpu version: [cpu version](https://github.com/google-coral/project-posenet/blob/master/models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder.tflite)
nevertheless, it requires an operator that is from the edgetpu library. This is the operator I tried to put in my compilated from source Tensorflow.

> The above PosenetDecoderOp is not a part of the TFLite project but it is a part of the project posenet. You need to register the custom op before invoking the TFLite interpreter. Please refer the custom op guide document: https://www.tensorflow.org/lite/guide/ops_custom
> 
> https://github.com/google-coral/edgetpu/tree/master/src/cpp/posenet

I used this documentation you attached and also [this article](https://medium.com/@bsramasubramanian/running-a-tensorflow-lite-model-in-python-with-custom-ops-9b2b46efd355) to register the custom operator but I'm getting the same error I described in the origina post:

`[...]_tensorflow_wrap_interpreter_wrapper.so: undefined symbol: _ZN6tflite3ops6custom27Register_POSENET_DECODER_OPEv`

**Comment by abattery** [comment]
Regarding the 'pycoral' import issue, you need to have edgetpu project in your development environment. You can probably ask it to the edgetpu project.

For the undefined symbol problem, I think you need to expose tflite::ops::custom::Register_POSENET_DECODER_OP function in the header and the global symbol can be retrieved from the Python program.

**Comment by lupitia1** [comment]
Is the edgetpu alwyas required to run in cpu? Im doing this in a cloud instance so I cannot connect the edgetpu.

**Comment by terryheo** [comment]
No, it's not necessary.
You'd better just check how to create interpreter instance with posenet_lib since the pose_engine has dependency on edgetpu.

```
        posenet_decoder_delegate = load_delegate(POSENET_SHARED_LIB)
        self._interpreter = Interpreter(
            model_path, experimental_delegates=[posenet_decoder_delegate])
        self._interpreter.allocate_tensors()
```

**Comment by lupitia1** [comment]
> No, it's not necessary.
> You'd better just check how to create interpreter instance with posenet_lib since the pose_engine has dependency on edgetpu.
> 
> ```
>         posenet_decoder_delegate = load_delegate(POSENET_SHARED_LIB)
>         self._interpreter = Interpreter(
>             model_path, experimental_delegates=[posenet_decoder_delegate])
>         self._interpreter.allocate_tensors()
> ```

Hello terryheo! I appreciate your help, I came to this conclussion after dealing with many errors and I finally made it work :D (using the tflite_runtime and a compilated .so file).

I attach the Issue where I updated all the process: [project-posenet Issue #49](https://github.com/google-coral/project-posenet/issues/49)

**Comment by amahendrakar** [comment]
> I came to this conclussion after dealing with many errors and I finally made it work :D

@lupitia1,
Thank you for the update.

Is this still an issue? Please feel free to close the issue if resolved.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
