### ISSUE TITLE
Problem about distributed training with XLA compiling.

### ISSUE THREAD

**Issue by sseung0703** [tensorflow/tensorflow#45940]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  - custom layer and custom training step
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  - I have tested on Windows 10, Ubuntu 16.04, and Ubuntu 18.04.
- TensorFlow installed from (source or binary):
  - both
- TensorFlow version (use command below):
  - I have tried TF 2.4, 2.5 distributed version and source installed 2.4
- Python version:
  - 3.7
- Bazel version (if compiling from source):
  - 3.5.0
- GCC/Compiler version (if compiling from source):
  - 7.5
- CUDA/cuDNN version:
  - 10.1 and 11.0
- GPU model and memory:
  - 1080ti x4

**Describe the current behavior**
When I train my model on multi-gpu with XLA compiling below error is occurred.
```
Training starts
Traceback (most recent call last):
  File "FFP_/train_w_pruning.py", line 76, in <module>
    train_step(*data)
  File "/home/cvip/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 787, in __call__
    result = self._call(*args, **kwds)
  File "/home/cvip/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 854, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/home/cvip/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1920, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/cvip/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 561, in call
    ctx=ctx)
  File "/home/cvip/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trying to access resource ResNet/conv/kernel/replica_1_879 located in device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference_train_step_dist_88943]
```

**Describe the expected behavior**
I want to compile my multi-gpu code but it seems unavailable.

**Standalone code to reproduce the issue**
https://github.com/sseung0703/TF2-multi-gpu-training

**Comment by amahendrakar** [comment]
@sseung0703,
The code provided in the GitHub repo is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. Thanks!

**Comment by sseung0703** [comment]
@amahendrakar
Sorry for the complex example. I write a code as simple as possible as below.
It requires three codes in my repo, i.e., nets/ResNet.py, nets/tcl.py, and op_utils.py
It is still complex, but I think they should be checked because the problem may be in custom layers or a training step.

```
import os, argparse
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import tensorflow as tf
tf.debugging.set_log_device_placement(False)

import op_utils
from nets import ResNet

parser = argparse.ArgumentParser(description='')

parser.add_argument("--gpu_id", default= [0], type=int, nargs = '+')
parser.add_argument("--compile", default=True, action = 'store_true')
parser.add_argument("--learning_rate", default=1e-1, type=float)
parser.add_argument("--weight_decay", default=5e-4, type=float)
parser.add_argument("--batch_size", default=128, type=int)
args = parser.parse_args()

if __name__ == '__main__':
    gpus = tf.config.list_physical_devices('GPU')
    tf.config.set_visible_devices([tf.config.list_physical_devices('GPU')[i] for i in args.gpu_id], 'GPU')
    for gpu_id in args.gpu_id:
        tf.config.experimental.set_memory_growth(gpus[gpu_id], True)
    devices = ['/gpu:{}'.format(i) for i in args.gpu_id]
    strategy = tf.distribute.MirroredStrategy(devices, cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())

    with strategy.scope():
        options = tf.data.Options()
        options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA

        def inference(image, label):
            image = tf.cast(image, tf.float32)
            image = (image-np.array([113.9,123.0,125.3]))/np.array([66.7,62.1,63.0])
            return image, label

        from tensorflow.keras.datasets.cifar100 import load_data
        (train_images, train_labels), (test_images, test_labels) = load_data()

        test_ds = tf.data.Dataset.from_tensor_slices((test_images, test_labels))
        test_ds = test_ds.map(inference, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        test_ds = test_ds.batch(args.batch_size)
        test_ds = test_ds.with_options(options)
        test_ds = test_ds.prefetch(tf.data.experimental.AUTOTUNE)

        model = ResNet.Model(num_layers = 56, num_class = 100, name = 'ResNet', trainable = True)

        train_step, train_loss, train_accuracy, optimizer = op_utils.Optimizer(args, model, strategy)

        for step, data in enumerate(test_ds):
            train_step(*data)
            print('check')
```

**Comment by amahendrakar** [comment]
@sseung0703,
I was able to run the code without any issues on TF v2.4 and CUDA 11/cuDNN 8. Please check the below screenshot for reference. 
![image](https://user-images.githubusercontent.com/57165142/103370963-3fee7580-4af4-11eb-8f4e-677b138bd360.png)


Could you please create a new virtual environment and check if you are facing the same error in that as well? Thanks!

**Comment by sseung0703** [comment]
@amahendrakar 
Did you check the above code on multi-GPU?

**Comment by amahendrakar** [comment]
@sseung0703,
Yes, I ran the code on a machine with two Tesla V100s. Thanks!

**Comment by sseung0703** [comment]
@amahendrakar
In the above code did you set the argument to use multi-GPU like "--gpu_id 0 1" ?

**Comment by amahendrakar** [comment]
@sseung0703,
Thank you for the update. I had initially run the code without any arguments (i.e. with the default arguments). 

On running the code with `--gpu_id 0 1`. I was able to reproduce the issue.
![Screenshot 2021-01-06 at 7 28 37 PM](https://user-images.githubusercontent.com/57165142/103778391-30bd7980-5058-11eb-99d1-51bc804037b4.png)

**Comment by sseung0703** [comment]
@amahendrakar 
Yes, that is the same error as me.
I think when the graph is compiled by XLA, parameters are not shareable.
How can I solve this?

**Comment by nikitamaia** [comment]
Hi @sseung0703, to clarify, your code runs with `MirroredStrategy` if `experimental_compile` is false. Is that correct?

**Comment by sseung0703** [comment]
@nikitamaia yes, without compiling my code works well. You can handle that parameter by argument “—compile”.

**Comment by sseung0703** [comment]
Hi @ckkuang, then is there any other option to use XLA on multi-gpu?

**Comment by ckkuang** [comment]
You can try [auto-clustering](https://www.tensorflow.org/xla#auto-clustering) (although it seems to be an experimental feature). Don't forget to remove  the `experimental_compile` knob from your tf.function.

**Comment by sseung0703** [comment]
@ckkuang I have tried auto-clustering, but there is no performance improvement. Does it mean there is no compilable operation in my code due to sharable parameters?

**Comment by cheshire** [comment]
@sseung0703 Your example does not show the whole code, since the part actually applying `experimental_compile=True` is not in your example.

@nnigania is currently working on supporting collective ops under XLA:GPU compilation, so I think the best bet is to wait for this work to land.

Alternatively, you would have to compile the part of your model which is not using any collectives (as we did for MLPerf).

**Comment by nnigania** [comment]
'jit_compile' is the new alias for 'experimental_compile'

Current suggestion is to "jit_compile" only parts of training which are running independently on each replica(GPU). Any time any communication/synchronization is needed then jit_compile around that will fail. So a 'jit_compile' around entire strategy.run will fail, and a 'jit_compile' around the function containing 'optimizer.apply_gradients' will fail. Also any 'jit_compile' around functions which update metrics will fail. But 'jit_compile' around the function doing the main training should work.

We are looking to lower the all_reduce and resolved some of these issues. Soon folks can enable 'jit_compile' on the entire training step (ideally like the way the user has done in this case).

To fix their current code, user needs to change the train_step code in <their github>/main/op_utils.py from:

```
    @tf.function(experimental_compile = args.compile)
    def train_step(images, labels):
        with tf.GradientTape() as tape:
            pred = model(images, training = True)
            total_loss = loss_object(labels, pred)/args.batch_size
        gradients = tape.gradient(total_loss, model.trainable_variables)
        if args.weight_decay > 0.:
            gradients = [g+v*args.weight_decay for g,v in zip(gradients, model.trainable_variables)]
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        train_loss.update_state(total_loss)
        train_accuracy.update_state(labels, pred)
   
    @tf.function(experimental_compile = args.compile)
    def train_step_dist(image, labels):
        strategy.run(train_step, args= (image, labels))
```


Code needs to changed to:

```
    @tf.function(jit_compile = True)
    def compiled_step(images, labels):
        with tf.GradientTape() as tape:
            pred = model(images, training = True)
            total_loss = loss_object(labels, pred)/args.batch_size
        gradients = tape.gradient(total_loss, model.trainable_variables)
        return total_loss, pred, gradients

    def train_step(images, labels):
        total_loss, pred, gradients = compiled_step(images, labels)
        if args.weight_decay > 0.:
            gradients = [g+v*args.weight_decay for g,v in zip(gradients, model.trainable_variables)]

        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        train_loss.update_state(total_loss)
        train_accuracy.update_state(labels, pred)
   
    @tf.function()
    def train_step_dist(image, labels):
        strategy.run(train_step, args= (image, labels))
```
Please let me know if you still hit issues, and we will be happy to resolve them.

**Comment by sseung0703** [comment]
Thank you for your advice @nnigania. :) 
I upgraded my Tensorflow version to 2.5 due to jit_compile is not available on 2.4, and had to fix more codes to remove all the update operation in compiled_step.
And after this work, my code works well with jit_compiling on multi-GPU, which gives 3 times faster iteration operation!!

Thank you very much again, and this issue is resolved :).

**Comment by caandewiel** [comment]
@geetachavan1 @nnigania Which commit fixed this issue in TF 2.5?

**Comment by sseung0703** [comment]
@caandewiel 
As I said above, it is impossible to update mirrored variables in the jit compiled graph.
So I had to remove all the update operations in jit compiled code and then update each variable outside.
You can find my work [here.](https://github.com/sseung0703/EKG/blob/feb7c3ccb1244aea3f42663c2f426a692dd6e65a/op_utils.py#L41-L87)

**Comment by nnigania** [comment]
For runs on single-host (single or multi-GPU using mirrored-strategy) we now support XLA around optimizer.apply_gradients . So now for even better performance we can do:

```
    @tf.function(jit_compile=True)
    def train_step(*data):
        # no need for xla around compiled_step 
        total_loss, gradients, update_vars = compiled_step(*data)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
```
+@cheshire

**Comment by caandewiel** [comment]
@nnigania That’s great news! I was wondering what commit is responsible for achieving this behavior as I’m currently using an alternative backend and would like to replicate this behavior.

**Comment by nnigania** [comment]
TF2.7 we added this support to enable XLA around entire training step for models using mirrored strategy. Only gotchas were tf.summary statements and tf metrics which do reductions as XLA is still working to add support for them.

Also in the most recent TF2.8 release, support was added to enable XLA for model using the Keras compile/fit API as well which leads to significant performance benefits. See TF2.8 release notes for details.

**Comment by sseung0703** [comment]
@nnigania I was outdated so far. Now, I can remove a bunch of pseudo distributed things and make my code much clear!
Thank you for informing us 😚

**Comment by zanussbaum** [comment]
@nnigania can you elaborate on the gotchas for `tf.metrics`? We are using a MirroredStrategy for multi-GPU training and aggregate the metrics in our `train_step`. Will XLA/`jit_compile` not work for us yet? And does XLA work for multi-TPU training as well?

**Comment by nnigania** [comment]
sure, for metrics, you can make calls to update() inside XLA scope, but calls to metrics init() and result() need some support from TF team.

From TPU perspective, XLA is always on (and required) by default for TPU runs, and does not have the issues discussed in this thread.
