### ISSUE TITLE
Tf.contrib.layers.Bias_add fails to operate due to uninitialized value

### ISSUE THREAD

**Issue by dtlam26** [tensorflow/tensorflow#45955]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from source:
- TensorFlow version (use command below): 1.14/1.15
- Python version: 3.7
- CUDA/cuDNN version: 10

**Describe the current behavior**
I want to add bias layers to slicing parts of a reshape layer. I conduct it with `tf.contrib.layers.bias_add` and then concatenate them back. However, I can't do that and it keeps raising the bug of uninitialized for the `Bias_add op` even I have given it

The code I use is below:

   ```
 input = keras.Input(shape=[shape, shape, 256])

    kernel_init = tf.keras.initializers.RandomNormal(0.0, 0.01)

    # seg_layer = _seg_layer(output_filters,num, f_l,kernel_init,bias_init)
    head = keras.layers.Conv2D(256, 3, padding="same", kernel_initializer=kernel_init)(input)
    head = keras.layers.ReLU()(head)
    for _ in range(3):
        head = keras.layers.Conv2D(256, 3, padding="same", kernel_initializer=kernel_init)(head)
        head = keras.layers.ReLU()(head)
    head = keras.layers.Conv2D(
        output_filters,
        3,
        1,
        padding="same",
        kernel_initializer=kernel_init,
        use_bias=False,
    )(head)
    # head = tf.identity(head)
    head = keras.layers.Reshape([-1, int(output_filters/9) ])(head)
    slicing = int(f_l/num)
    segment = []
    for i in range(num):
        tempt = head[:,slicing*i:slicing*(i+1),:]
        tempt = tf.contrib.layers.bias_add(
            tempt,
            activation_fn=None,
            initializer=tf.zeros_initializer(),
            regularizer=None,
            reuse=None,
            variables_collections=None,
            outputs_collections=None,
            trainable=True,
            data_format='NHWC',
            scope=None
        )
        segment.append(tempt)
    output = keras.layers.Concatenate(axis=1)(segment)
    model = keras.models.Model(input,output)
```

Error:
```
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value BiasAdd/biases
         [[{{node BiasAdd/biases/read}}]]
         [[BiasAdd/biases/read/_687]]
  (1) Failed precondition: Attempting to use uninitialized value BiasAdd/biases
         [[{{node BiasAdd/biases/read}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by ravikyram** [comment]
@dtlam26 
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. 

In TF 2.4 you can try with `tf.nn.bias_add` as contrib functions will not be supported in TF 2.x
Thanks!

**Comment by dtlam26** [comment]
Does the `tf.nn.bias_add` give fixed bias value for the tensor? Because according to the description of both 1.15 and 2.4, I am not sure they can learn

**Comment by ravikyram** [comment]
@dtlam26 

Can you please refer the [link](https://www.tensorflow.org/agents/api_docs/python/tf_agents/keras_layers/bias_layer?hl=fr) and see if it help you. Thanks!
