### ISSUE TITLE
tf.read_file have different speed to read the same images

### ISSUE THREAD

**Issue by ShiquanYu** [tensorflow/tensorflow#45952]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):docker image: `docker pull tensorflow/tensorflow:1.13.1-gpu-py3`
- TensorFlow version (use command below):1.13.1
- Python version:3.5.2
- CUDA/cuDNN version:10.0
- GPU model and memory:1080TI/11G

**Describe the current behavior**
Hi,
I had pull tf1.13.1 docker image from dockerhub: 

```sh
$ docker pull tensorflow/tensorflow:1.13.1-gpu-py3
```
I use `tf.data.TextLineDataset` to load data from HHD, here is my code:

```python
def _parse_function(data):
    data_str_split = tf.string_split([data]).values
    filename = data_str_split[0]
    image_string = tf.read_file(filename)
    return image_string

def input_fn(is_training, filename, params):
    batch_size = params['batch_size']
    num_parallel_calls = params['num_parallel_calls']
    if num_parallel_calls is None:
        num_parallel_calls = tf.data.experimental.AUTOTUNE
    parse_fn = lambda data: _parse_function(data)    # anchor
    dataset = tf.data.TextLineDataset(filename)
    if is_training:
        dataset = dataset.apply(tf.data.experimental.map_and_batch(
            map_func=parse_fn, batch_size=batch_size, num_parallel_calls=num_parallel_calls))
        dataset = dataset.shuffle(300)
    else:
        dataset = dataset.apply(tf.data.experimental.map_and_batch(
            map_func=parse_fn, batch_size=batch_size, num_parallel_calls=num_parallel_calls))

    # create reinitializable iterator from dataset
    iterator = dataset.make_initializable_iterator()
    images = iterator.get_next()
    iterator_init_op = iterator.initializer
    inputs = {'images': images, 'iterator_init_op': iterator_init_op}
    return inputs
```
I tested the reading speed of the first file: `total.txt`(about 4,000,000 lines), the reading speed is about 2000～3000it/s(if i test it a second time, it will up to 8000~9000it/s):
```python
if __name__ == "__main__":
    os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
    params = {
        'batch_size': 32,
        'num_parallel_calls': 64
    }

    test_txt = '${ROOT}/total.txt'
    # test_txt = '${ROOT}/train.txt'
    # test_txt = '${ROOT}/valid.txt'
    test_inputs = input_fn(True, test_txt, params)

    import time
    ts = time.time()
    last_processed = 0
    num_processed = 0
    with tf.Session() as sess:
        sess.run(test_inputs['iterator_init_op'])
        while True:
            try:
                images = sess.run(test_inputs['images'])
            except tf.errors.OutOfRangeError:
                sess.run(test_inputs['iterator_init_op'])
                continue
            num_processed += images.shape[0]
            tn = time.time()
            if tn-ts > 1.0:
                print("\rnum_parallel_calls[{}]:{:5.2f}it/s".format(params['num_parallel_calls'],
                                                                    (num_processed-last_processed)/(tn-ts)), end='')
                last_processed = num_processed
                ts = tn
```
Then, I shuffled the file `total.txt` and splited to `train.txt/valid.txt`, and test the reading speed,
but the speed drops to **100it/s**!

The 2 txt file pointed to the same images, why is there such a big difference?

Can you tell me how to solve this problem, I have tried to split the `train.txt` to several small `.txt` file, but it's useless.

Thanks a lot!

**Comment by ravikyram** [comment]
@ShiquanYu 

You are seeing the same behavior with latest TF  2.4, Nightly versions?

If the issue still persists in latest versions please share simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by ShiquanYu** [comment]
Hi, @ravikyram 

I'm sorry but i need to run it in tf1.x, because I need to deploy the model to an embedded device which only support tf1.x's operators and model.

Is there any way to solve this problem in version tf1.x? Otherwise, I have to use tfrecord instead.

But this problem is too strange, the cpu is idle, the disk is idle, the memory is enough, but it's still can't load data from the disk.
Each picture has only 2kb~10kb size, the maximum loading speed is only 1Mb/s?

Thanks!

**Comment by ShiquanYu** [comment]
Hi, @ravikyram 

Thanks for your reply, I have found the reason, maybe because of the `shuffle` operation raise this problem.

I used cv2 to read image from HHD, it's same speed with tf.read_file. If I shuffle the data, the HHD need to cost more time on `seek time`.

Thanks a lot!
