### ISSUE TITLE
Nontrainable Custom Convolution at the start of model

### ISSUE THREAD

**Issue by 876arham** [tensorflow/tensorflow#45959]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**
I am creating a CNN model ,but at the start I want my image to be passed through high pass filter(based on a matrix convolution) how to do that,or How to add a custom non trainable Convolution layer with a constant matrix at the start of model
.Please refer GNCNN model , how to do the HIgh pass filter part in keras , using flow from directory method

**Comment by amahendrakar** [comment]
@876arham,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
