### ISSUE TITLE
Is it possible to build tf2.4 with cuda 10.0?

### ISSUE THREAD

**Issue by Cospel** [tensorflow/tensorflow#45957]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.0.130, cudnn 7.5
- GPU model and memory: K80

**Describe the problem**

I would like to know if is it possible to build newest tensorflow against cuda 10.0? Is there any workaround with cuda 10.0? It looks like libcublasLt.so.10.0 is missing in cuda10.0 ...

**Provide the exact sequence of commands / steps that you executed before running into the problem**

During the build I get following error:

    $: bazel build //tensorflow/tools/pip_package:build_pip_package
    ....
    Repository command failed
    No library found under: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublasLt.so.10.0
    INFO: Elapsed time: 1.836s
    INFO: 0 processes.
    FAILED: Build did NOT complete successfully (0 packages loaded)
        currently loading: tensorflow/tools/pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@Cospel,
Every TensorFlow release is compatible with a certain CUDA and cuDNN version. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu). 

TensorFlow v2.4 is compatible with CUDA 11.0 and cuDNN 8, hence you will face issues while building with CUDA 10.

Thanks!
