### ISSUE TITLE
Using Tensorflow 2.3 in r (conda environment) to reproduce the examples of Platypus R-package

### ISSUE THREAD

**Issue by konstanto21** [tensorflow/tensorflow#45956]
the example included in Platypus package: https://github.com/maju116/platypus/blob/yolo3_fix/examples/Blood%20Cell%20Detection/Blood-Cell-Detection.md

my session trying to reproduce the result:
> history <- blood_yolo %>%
+   yolo3_fit_generator(
+     generator = train_blood_yolo_generator,
+     epochs = 3,
+     steps_per_epoch = 3,
+     validation_generator = valid_blood_yolo_generator,
+     validation_steps_per_epoch = 9,
+     model_filepath = "development/BCCD/blood_w.hdf5",
+     save_best_only = TRUE,
+     monitor = "val_loss"
+   )
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x0000024526D8AB80> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x00000245244990D0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x00000245244E0EE0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x0000024561F4C280> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x0000024561F97D30> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function make_python_function.<locals>.python_function at 0x0000024562187C10> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Comment by amahendrakar** [comment]
@konstanto21,
You can safely ignore the warnings and suppress the messages by changing the log level at the start of the program  
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```

or you can set the [autograph verbosity](https://www.tensorflow.org/api_docs/python/tf/autograph/set_verbosity
) level using the below the below code 

```
import os
import tensorflow as tf
os.environ['AUTOGRAPH_VERBOSITY'] = 1
```

Thanks!
