### ISSUE TITLE
tflite android gpu delegate init error, what does it mean?  Init: MUL: 1x1088x1x1  cannot be reduced to linear.

### ISSUE THREAD

**Issue by uchihaltachi** [tensorflow/tensorflow#45967]
@tensorflow/micro

**Describe the problem**
error log:
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: 
TfLiteGpuDelegate Init: MUL: 1x1088x1x1  cannot be reduced to linear.
TfLiteGpuDelegate Prepare: delegate is not initialized
 Node number 23608 (TfLiteGpuDelegateV2) failed to prepare.

when i run my own model convert from pytorch to TFLite.

device: HUAWEI Mate20
dependence:
implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly')
implementation('org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly')
implementation('org.tensorflow:tensorflow-lite-support:0.0.0-nightly')

**Please provide the exact sequence of commands/steps when you ran into the problem**
When I run the model on the android GPU

**Comment by ravikyram** [comment]
@uchihaltachi 

Please, share simple standalone code to reproduce the issue in our environment. Thanks!

**Comment by ymodak** [comment]
Closing this issue since it's addressed in another [thread](https://github.com/tensorflow/tensorflow/issues/37102#issuecomment-754889708). Thanks!
