### ISSUE TITLE
A long period of GPU/CPU idle time in timeline

### ISSUE THREAD

**Issue by lonway** [tensorflow/tensorflow#45960]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux version 3.10.0
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-gpu==1.15
- Python version: 3.6.8
- CUDA/cuDNN version: 10.2
- GPU model and memory: Tesla-V100, 16G

**Describe the current behavior**
There is a long period of GPU and CPU idle time in timeline. The model is trained in one GPU and there is no problem of network transmission.

**Describe the expected behavior**
There should not be such a long period of idle time.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![屏幕快照 2020-12-24 下午8 17 36](https://user-images.githubusercontent.com/5723913/103089708-c2c18d00-4629-11eb-9059-43aeb8b20136.png)

**Comment by amahendrakar** [comment]
@lonway,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by unlimitednzt** [comment]
@lonway Did you manage to solve this?
