### ISSUE TITLE
Apollo3 project upload issue 

### ISSUE THREAD

**Issue by aloizo03** [tensorflow/tensorflow#45969]
@tensorflow/micro

**System information**
- Windows 10
- Arduino IDE
- TensorFlow Lite 2.1
- Sparkfun Apollo3 blue

I make all the steps correct from the sparkfun site to i can run the apollo3 from arduino ide.

When i upload the micro speech project into apollo3 from Arduino IDE i get this message #include "tensorflow/lite/c/c_api_internal.h"
How i can resolve this ?

**Comment by aloizo03** [comment]
sorry the full error message is 'tensorflow/lite/c/c_api_internal.h' file not found

**Comment by amahendrakar** [comment]
@aloizo03,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same error.

Also in order to expedite the trouble-shooting process, please provide the exact sequence of commands / steps that you executed before running into the error. Thanks!
