### ISSUE TITLE
grpc 1.32.0 doesn't support python 3.9 in windows 10, dependency should be updated to 1.34.0

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#45973]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.9.1
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source):  Visual Studio 2019
- CUDA/cuDNN version: 11.2 / 8.0.5
- GPU model and memory:
RTX 3070 GDDR6 8GB

**Describe the problem**
cannot build grpcio 1.32.0
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build and install

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

grpcio 1.32.0 does not support python 3.9.1 in Windows 10

tensorflow dependency should be updated as with grpcio 1.34.0

**Comment by mihaimaruseac** [comment]
We don't have yet an official build for 3.9 but we plan to have one next quarter. When we get this,we will also update the dependencies.

Currently, protobuf, grpc and gast are the dependencies that need to be updated to have 100% tests green.

**Comment by bhack** [comment]
I'am trying the grpcio upgrade with https://github.com/tensorflow/tensorflow/pull/46019

**Comment by bhack** [comment]
I think that we could close this as dup of https://github.com/tensorflow/tensorflow/issues/45973
