### ISSUE TITLE
TF 2.4: Metrics not recognized as stateful in ProgbarLogger callback

### ISSUE THREAD

**Issue by DrAA** [tensorflow/tensorflow#45978]
**System information**
- The vanilla example in https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Metric has the issue
- OS Platform and Distribution: Linux Ubuntu 21.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.9
- CUDA/cuDNN version: 11.0/8.0.5.39
- GPU model and memory: GeForce RTX 2080 Mobile

**Describe the current behavior**
Although the metric in the example, `CategoricalAccuracy`, is calculated correctly, it is not being recognized as a stateful metric by the `ProgbarLogger` callback. For more complicated metrics, that require proper handling by the `ProgbarLogger` callback, this causes errors such as `ValueError: operands could not be broadcast together with shapes (19,11) (38,11)` since they are concatenated instead of using the stateful metric value.

**Describe the expected behavior**
If the automatic addition of the `ProgbarLogger` callback did recognize the metrics added to the model, it would have been seen in the `ProgbarLogger.stateful_metrics` attribute, but it is currently always empty.

**Standalone code to reproduce the issue**
In the code example below, the `ProgbarLogger` is manually created and metrics are added to the constructor. Hence, the automatic creation of the `ProgbarLogger` is disabled and the `ProgbarLogger.stateful_metrics` will contain the `CategoricalAccuracy` metric and properly calculate the progress in a stateful manner.

```python
import types

import numpy as np
import tensorflow as tf
from tensorflow.python.keras.callbacks import ProgbarLogger

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

metrics = [tf.keras.metrics.CategoricalAccuracy()]
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=metrics)

np.random.seed(0)
tf.random.set_seed(0)
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

metric_names = [
    m.lower() if isinstance(m, str) else
    m.__name__ if isinstance(m, types.FunctionType) else
    m.name for m in metrics]
callbacks = [ProgbarLogger(
    count_mode='steps',
    stateful_metrics=metric_names)]

result = model.fit(dataset, callbacks=callbacks, epochs=10)

```

**Comment by amahendrakar** [comment]
@DrAA,
I did not face any errors while running the given code snippet and the linked TensorFlow documentation example. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7de9e1facb8ea70e68e06ca5edde4275/45978.ipynb).



> this causes errors such as `ValueError: operands could not be broadcast together`

In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by DrAA** [comment]
Sure, I added a metric from a codebase where I experience the problem, called `ReservoirHistogram`. I added a cell to you [colab notebook](https://colab.research.google.com/gist/amahendrakar/7de9e1facb8ea70e68e06ca5edde4275/45978.ipynb), and also pasted that below. Running the code should demonstrate the problem, and just switch the `if False` statement to `if True`  to see that the hotfix works.

```python
#!/usr/bin/env python
import types

import numpy as np
import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))


class ReservoirHistogram(tf.metrics.Metric):

    def __init__(self,
                 name='histogram',
                 reservoir_size=300,
                 reservoir_shape=(10,),
                 dtype=tf.float32,
                 **kwargs):
        super().__init__(name=name, dtype=dtype, **kwargs)
        self.reservoir: tf.Variable = self.add_weight(
            name='reservior',
            shape=(reservoir_size,) + reservoir_shape,
            initializer='zeros',
            dtype=self.dtype)

        self.current_index: tf.Variable = self.add_weight(
            name='current_index', shape=(), dtype=tf.int32,
            initializer=tf.constant_initializer(0))

    def update_state(self, y_true, y_pred, sample_weight=None):
        batch_size = tf.shape(y_pred)[0]
        reservoir_size = tf.cast(tf.shape(self.reservoir)[0], tf.int32)
        r_index = self.current_index % reservoir_size
        batch_part = tf.minimum(batch_size, reservoir_size - r_index)
        batch_random = tf.random.uniform(shape=(batch_part,), maxval=1.)
        self.current_index.assign_add(batch_part)
        reservoir_prob = (1. if self.current_index < reservoir_size
                          else tf.cast(reservoir_size / self.current_index,
                                       dtype=tf.float32))
        batch_mask = batch_random <= reservoir_prob
        batch_mask = tf.tile(
            input=tf.expand_dims(tf.cast(batch_mask, tf.float32), axis=1),
            multiples=tf.concat(((1,), tf.shape(self.reservoir)[1:]), axis=0))
        old_values = self.reservoir[r_index: r_index + batch_part]
        batch_values = y_pred[:batch_part]
        # transform values to have a zero-centered distribution
        batch_values = tf.clip_by_value(tf.where(
            batch_values > 0.5, batch_values - 1, batch_values),
            clip_value_min=-0.1, clip_value_max=0.1)
        new_values = old_values * (1 - batch_mask) + batch_values * batch_mask
        new_reservoir = tf.concat(
            (self.reservoir[:r_index],
             new_values,
             self.reservoir[r_index + batch_part:]),
            axis=0)
        self.reservoir.assign(new_reservoir)

    def result(self):
        used_size = tf.minimum(self.current_index, tf.shape(self.reservoir)[0])
        return self.reservoir[:used_size]

    def reset_states(self):
        self.reservoir.assign(tf.zeros(shape=tf.shape(self.reservoir)))
        self.current_index.assign(0)


metrics = [tf.keras.metrics.CategoricalAccuracy(), ReservoirHistogram()]
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.01),
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=metrics)

np.random.seed(0)
tf.random.set_seed(0)
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

if False:  # switch to True to demonstrate that the hotfix works
    metric_names = [
        m.lower() if isinstance(m, str) else
        m.__name__ if isinstance(m, types.FunctionType) else
        m.name for m in metrics]
    callbacks = [tf.keras.callbacks.ProgbarLogger(
        count_mode='steps',
        stateful_metrics=metric_names)]
    result = model.fit(dataset, callbacks=callbacks, epochs=10)
else:
    result = model.fit(dataset, epochs=10)
```

**Comment by amahendrakar** [comment]
Was able to run the code without any errors on [TF v2.3](https://colab.research.google.com/gist/amahendrakar/b01a2a3654163ea4edc2b9eafb282017/45978-2-3.ipynb).

However with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/5a14072b48aefa4288f95d0a7dca7599/45978.ipynb#scrollTo=0pauDHBLSFyP) and TF-nightly, I'm facing an error stating `ValueError: operands could not be broadcast together with shapes (32,10) (64,10) (32,10)`. Please check the linked gist for reference. Thanks!

**Comment by DrAA** [comment]
Yes, that sounds similar to my experience. Worked well for me in 2.3 but
not in 2.4. Any additional information or help that I could provide?

Best regards,

Anders Arpteg, Ph.D.

Head of Research, peltarion.com

Founder, Agent Central AB

Cell: +46 (0)709 389020
https://www.linkedin.com/in/andersarpteg/

**Comment by jvishnuvardhan** [comment]
@DrAA Is this still an issue for you? I ran your code with `tf-nightly` and I don't see any error. Can you please check and confirm whether the issue is still persisting with `tf-nightly`. Thanks!

**Comment by DrAA** [comment]
Yes, I can confirm that the issue has been resolved in the latest tf-nightly. Great!
