### ISSUE TITLE
tf.debugging.assert_type raising error for wrong reason

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#45975]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary (pip install)
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
```
>>> tf.debugging.assert_type(tf.constant(0.0), tf_type=(tf.float32,))
TypeError:  tensor must be of type (tf.float32,)
```
is incorrect.

**Describe the expected behavior**
Error should be raised because of incorrect argument type for `tf_type` (which needs to be a tf float type, not an iterable of them), not because tensor is not of type `(tf.float32,)`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e97a3e0f3be52cfb7dbb5b4051d9d0fd/45975.ipynb). Thanks!

**Comment by yongtang** [comment]
Added a PR #46013 for the fix.
