### ISSUE TITLE
MaskRCNN TensorFlow Lite Inference Issue. No output from TFLite Model.

### ISSUE THREAD

**Issue by dsJoe** [tensorflow/tensorflow#45977]
**System information**
- OS Platform and Distribution ( Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1034-azure x86_64)):
- TensorFlow installed from (source- Pip Install):
- TensorFlow version (2.3.0):

**Command used to run the converter**
```
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.allow_custom_ops = True
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

converter.optimizations = [ tf.lite.Optimize.DEFAULT ]

tflite_model = converter.convert()
```

**link to Jupyter notebook and tflite model**

https://drive.google.com/drive/folders/1pTB33fTSo5ENzevobTvuG7hN4YmiCPF_?usp=sharing

**Commands used for inference**
```
### Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model_2.3.tflite")
interpreter.allocate_tensors()

### Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

### Test the model on random input data.
input_data_1 = np.array(np.random.random_sample(input_details[0]['shape']), dtype=np.float32)
input_data_2 = np.array(np.random.random_sample(input_details[1]['shape']), dtype=np.float32)
input_data_3 = np.array(np.random.random_sample(input_details[2]['shape']), dtype=np.float32)

interpreter.set_tensor(input_details[0]['index'], input_data_1)
interpreter.set_tensor(input_details[1]['index'], input_data_2)
interpreter.set_tensor(input_details[2]['index'], input_data_3)

interpreter.invoke() ---> Kernel is getting stuck here. No output. I am executing the code from jupyter.

```

**The output from the converter invocation**

No output in Jupyter. 

Segmentation fault (core dumped) -- When executed in command line.

**Failure details**

Conversion is successful. But there is no output from model.

Could you guys please provide some ideas? I am stuck here and don't know how to proceed!

**Comment by abattery** [comment]
I ran the model with tf-nightly version through the shared notebook. It took a few minutes to complete the invoke() part but I could get the result.

```
Prediction results: [[[0.2833773  0.28597987 0.03956655 0.5136417 ]
  [0.38100398 0.45283458 0.66197014 0.6441412 ]
  [0.17763907 0.53368616 0.48083413 0.1984492 ]
  ...
  [0.55963373 0.806476   0.32869753 0.5672232 ]
  [0.7234199  0.45786685 0.3743322  0.25172007]
  [0.662722   0.8848254  0.75358796 0.9891881 ]]]
```

**Comment by dsJoe** [comment]
> I ran the model with tf-nightly version through the shared notebook. It took a few minutes to complete the invoke() part but I could get the result.
> 
> ```
> Prediction results: [[[0.2833773  0.28597987 0.03956655 0.5136417 ]
>   [0.38100398 0.45283458 0.66197014 0.6441412 ]
>   [0.17763907 0.53368616 0.48083413 0.1984492 ]
>   ...
>   [0.55963373 0.806476   0.32869753 0.5672232 ]
>   [0.7234199  0.45786685 0.3743322  0.25172007]
>   [0.662722   0.8848254  0.75358796 0.9891881 ]]]
> ```

Hi abattery, Thanks a ton for checking the code and responding.

Have you done any modifications in the code? Are you using the same model which I shared?

I tried tf-nightly(cpu), but the system freezed and jupyter kernel died after sometime.

Did you try the GPU version? I have to change my CUDA to 11 for trying tf-nightly in gpu.

Could you please share the system details where you tried this code?

**Comment by abattery** [comment]
I ran the shared model on the colab without any modifications after installing ```!pip install tf-nightly```.

**Comment by abattery** [comment]
I think the model is quite big and slow to run. However, the model itself is runnable.

**Comment by dsJoe** [comment]
Thanks again. I am able to execute the code in Colab and get the results. It took a long time though(~10 minutes). I will check how to improve the inference time. Please suggest if you have any ideas.

Once again, Thank you very much for helping 👍

**Comment by abattery** [comment]
If you need bounding boxes, you can check out the SSD models on the [TF2 detection zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). Mask-RCNN is not very well supported on TFLite, mainly because the models in the TF1 detection zoo are too large to perform well on-device.

**Comment by MeghaGhosh** [comment]
Hi @abattery @jiks-hue I have tried to run my tflite model with tf-nightly multiple times (with the above code). On colab the runtime gets disconnected and locally I get a segmentation fault. Is there any reason it is not working for me?
