### ISSUE TITLE
Attempting to use uninitialized value 

### ISSUE THREAD

**Issue by haniyeka** [tensorflow/tensorflow#45971]
Hello, 
I have a trained tensorflow model which is trained by tensorflow v1.14 and the model is saved as meta graph model. What I'm trying to do is to convert this model to Keras since I cannot work with the model with SHAP package. The Shap package doesn't support the meta graph tensorflow model. So I want to convert it to Keras. I have done this with another TF model with VGG architecture and this works perfectly fine.  For this purpose I create the architecture in Keras and then I set the weight and bias values to the new model. 
Now I have a trained model with Resnet-18 architecture. But the problem is when I want to get the weights I get this error: 

Attempting to use uninitialized value scale2/block1/A/weights
	 [[{{node _retval_scale2/block1/A/weights_0_0}}]]

This works fine when I want to get the non-nested layer's values. 

```
with tf.compat.v1.Session() as sess, tf.device('/device:gpu:0'):
    saver = tf.compat.v1.train.import_meta_graph('./snapshot-110.meta')
    saver.restore(sess,tf.train.latest_checkpoint('./'))
    graph = tf.compat.v1.get_default_graph()

    vars_global = tf.compat.v1.global_variables()
    sess.as_default()
    model_vars = {}
    for var in vars_global:
        model_vars[var.name] = var.eval()
```

**Comment by Saduf2019** [comment]
@haniyeka 
We see that you are using an old version of tf 1.x is not supported, can you please try on 2.x and let us know if you face any issues.
