### ISSUE TITLE
Android Benchmark tool Build Failed

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#45972]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: master branch
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory: GTX 1660 and 6GB RAM

**Describe the problem**

Build failed when building android benchmark tool for tflite models.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I just ran this command 

> bazel build -c opt --config=android_arm64 tensorflow/lite/tools/benchmark/android:benchmark_model

**Any other info / logs**
> INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/ram/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/ram/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/ram/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/ram/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:android_arm64 in file /home/ram/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /home/ram/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
ERROR: /home/ram/.cache/bazel/_bazel_ram/a1828cafbf783c13dba0538b4a59550c/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: Analysis of target '//tensorflow/lite/tools/benchmark/android:benchmark_model' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 0.180s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 1 target configured)

**Comment by multiverse-tf** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): Source
> * TensorFlow version: master branch
> * Python version: 3.8
> * Installed using virtualenv? pip? conda?:
> * Bazel version (if compiling from source): 3.1.0
> * GCC/Compiler version (if compiling from source): 7.5.0
> * CUDA/cuDNN version:
> * GPU model and memory: GTX 1660 and 6GB RAM
> 
> **Describe the problem**
> 
> Build failed when building android benchmark tool for tflite models.
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> I just ran this command
> 
> > bazel build -c opt --config=android_arm64 tensorflow/lite/tools/benchmark/android:benchmark_model
> 
> **Any other info / logs**
> 
> > INFO: Options provided by the client:
> > Inherited 'common' options: --isatty=1 --terminal_columns=204
> > INFO: Reading rc options for 'build' from /home/ram/tensorflow/.bazelrc:
> > Inherited 'common' options: --experimental_repo_remote_exec
> > INFO: Reading rc options for 'build' from /home/ram/tensorflow/.bazelrc:
> > 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
> > INFO: Found applicable config definition build:short_logs in file /home/ram/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
> > INFO: Found applicable config definition build:v2 in file /home/ram/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> > INFO: Found applicable config definition build:android_arm64 in file /home/ram/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
> > INFO: Found applicable config definition build:android in file /home/ram/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
> > ERROR: /home/ram/.cache/bazel/_bazel_ram/a1828cafbf783c13dba0538b4a59550c/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
> > ERROR: Analysis of target '//tensorflow/lite/tools/benchmark/android:benchmark_model' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed

It looks like your overall building environment isn't set properly. Please follow https://www.tensorflow.org/lite/guide/build_android for details. 

Or one could use pre-built binaries mentioned in https://www.tensorflow.org/lite/performance/measurement as you've discovered in https://github.com/tensorflow/tensorflow/issues/45986

> > INFO: Elapsed time: 0.180s
> > INFO: 0 processes.
> > FAILED: Build did NOT complete successfully (2 packages loaded, 1 target configured)

**Comment by tulasiram58827** [comment]
Yeah after raising this issue I got working binary from Tensorflow website.
