### ISSUE TITLE
Running custom tflite model, segfault only on CPU, tflite 2.4.0 built from sources

### ISSUE THREAD

**Issue by hfnvbh** [tensorflow/tensorflow#45981]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 8.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Meizu 16th
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0, also 5a8dc94c30a
- Python version: no 
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the current behavior**
trying to run custom [converted](https://github.com/pb-julian/liteface) tflite [model](https://www.dropbox.com/s/akxeqp99jvsd6z7/model-MobileFaceNet-arcface-ms1m-refine-v1.zip?dl=0) from insigthface on android. It works with standard tflite.aar from jcenter. Also works with built from sources libtensorflowlite_gpu_delegate.so. But when i tried to run on CPU with built from source libtensorflowlite.so, i got segfault.

**Describe the expected behavior**
Expected to work with manually built libtensorflowlite.so

**Standalone code to reproduce the issue**
- *.so files was built with docker from repo and [guide](https://www.tensorflow.org/lite/guide/build_android) in site.
- libtensorflowlite.so was built with commands: `bazel build tensorflow/lite:libtensorflowlite.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --config=android --cpu=arm64-v8a` and  `bazel build tensorflow/lite:libtensorflowlite.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --config=android --cpu=armeabi-v7a`
- code for running was adapted from [sample of usage](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c)

**Other info / logs** Include any logs or source code that would be helpful to
traceback:
<img width="1250" alt="Снимок экрана 2020-12-27 в 05 13 36" src="https://user-images.githubusercontent.com/32731602/103161348-56e64c80-4802-11eb-87de-e40365ea69e0.png">

**Comment by thaink** [comment]
Why are you building .so instead of .aar file? As you mentioned, it worked with the standard .aar file from jCenter so it might be easier for you to just build the .aar file.
Can you try following command:
bazel build -c opt --config=android_arm64 \
  --crosstool_top=//external:android/crosstool \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite

**Comment by hfnvbh** [comment]
Hi @thaink,

Other code in my project written on C++, so i need c API for tflite. Also, jCenter's aar is slow, *.so complied from sources runs faster.

Yes, java aar variant works, and that is proof that problem not in model.

But cpp *.so crashes. What is wrong?

**Comment by thaink** [comment]
Got it.
Instead of "--config=android --cpu=arm64-v8a", can you try --config=android_arm64?
Beside "-cpu", it also set "-fat_apk_cpu". "Bazel needs to have --cpu and --fat_apk_cpu both set to the target CPU to build transient dependencies correctly."

**Comment by hfnvbh** [comment]
@thaink 
Yes, i tried to use together "--cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a" and "--cpu=arm64-v8a --fat_apk_cpu=arm64-v8a". Also tried to add "--config=android_arm64" and "--config=android_arm" and tried to use only --config param.

results are same, still crashes.

**Comment by thaink** [comment]
@hfnvbh Can you provide a code to reproduce this.
I cannot find the model from your link.

**Comment by hfnvbh** [comment]
@thaink 
[model.tflite.zip](https://github.com/tensorflow/tensorflow/files/5780045/model.tflite.zip)

```cpp
// Load the model
std::unique_ptr<tflite::FlatBufferModel> model =
    tflite::FlatBufferModel::BuildFromFile("model.tflite");

// Build the interpreter
tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model, resolver)(&interpreter);

// Resize input tensors, if desired.
interpreter->AllocateTensors();

float* input_tensor = interpreter->typed_input_tensor<float>(0);
std::vector<float> input;
input.resize(112 * 112 * 3)
std::memcpy(input_tensor, input.data(), 112 * 112 * 3 * sizeof(float));

interpreter->Invoke();

float* output = interpreter->typed_output_tensor<float>(0);
```

**Comment by thaink** [comment]
I just tried your code on my android phone. It works just fine.

**Comment by hfnvbh** [comment]
@thaink 
that interesting. Could you please share your .so files, i will check it in my phone too.

**Comment by thaink** [comment]
The lib file is here https://github.com/thaink/upload_files/tree/main/TF_PR45981
By the way, the error log you show doesn't look like a linking issue.
If you face the error, could you upload the full log?

**Comment by hfnvbh** [comment]
Hi @thaink .

I made some experiments and want to clarify situation
Yes, you are correct, if just run that code in single function it's works with your and my *.so builds.

But when i separate code for two functions: init and run and call it in third function, i got crash even with your build.

Here is code for reproduce:
```cpp

void tfinit(std::unique_ptr<tflite::Interpreter> &interpreter) {
    // Load the model
    std::unique_ptr<tflite::FlatBufferModel> model =
            tflite::FlatBufferModel::BuildFromFile("/storage/emulated/0/recognition.tflite");

// Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

// Resize input tensors, if desired.
    interpreter->AllocateTensors();
}

void tfrun (std::unique_ptr<tflite::Interpreter> &interpreter) {
    float* input_tensor = interpreter->typed_input_tensor<float>(0);
    std::vector<float> input;
    input.resize(112 * 112 * 3);
    std::copy(input.data(), input.data() + 112 * 112 * 3 , input_tensor);

    interpreter->Invoke();

    float* output = interpreter->typed_output_tensor<float>(0);
}

//function runs others two
JNIEXPORT jboolean JNICALL JNI_FUNC(initTfModel)(JNIEnv* env, jobject thiz) {
    std::unique_ptr<tflite::Interpreter> interpreter;
    tfinit(interpreter);
    tfrun(interpreter);
    return true;
}
``` 

here is logs for crash:
[crash.log](https://github.com/tensorflow/tensorflow/files/5811702/crash.log)

But if i add GPU delegate to init and make at as written below, it will work without crashes
```cpp
void tfinit(std::unique_ptr<tflite::Interpreter> &interpreter) {
    // Load the model
    std::unique_ptr<tflite::FlatBufferModel> model =
            tflite::FlatBufferModel::BuildFromFile("/storage/emulated/0/recognition.tflite");

// Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

    auto delegateOptions = TfLiteGpuDelegateOptionsV2Default();
    delegateOptions.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;

    std::unique_ptr<TfLiteDelegate, std::function<void(TfLiteDelegate*)>> delegate(
            TfLiteGpuDelegateV2Create(&delegateOptions),
    [](TfLiteDelegate* d) { TfLiteGpuDelegateV2Delete(d); }
    );

    interpreter->ModifyGraphWithDelegate(std::move(delegate));

// Resize input tensors, if desired.
    interpreter->AllocateTensors();
}
```

**Comment by thaink** [comment]
Looks like `tflite::Interpreter` reuse tensors that are belong to tflite::Model.
So when your program exit the tfinit, the `tflite::FlatBufferModel` object is deallocated, causing those tensors in `tflite::Interpreter` become invalid.

You can fix it by moving the content of tfinit to JNI_FUNC. This way, you still can invoke the model multiple times. Or define the  `tflite::FlatBufferModel` object in JNI_FUNC and pass it to tfinit.

@jdduke do you think this is error-prone and should be fixed?

**Comment by hfnvbh** [comment]
@thaink 

Thank you, i also found notes from api reference about it. The fact that GPU version stable working even after `tflite::FlatBufferModel`  destruction confused me.

So, my problem solved, thank you very much.

**Comment by jdduke** [comment]
> @jdduke do you think this is error-prone and should be fixed?

It does require a bit more care on the client side, but it has been this way from the beginning and is fully documented. We could offer a convenience path which passes ownership of `FlatBufferModel` to the `Interpreter`. Relatively few clients shared a `FlatBufferModel` instance between `Interpreters` (which was a good motivation for the existing API that allows sharing).
