### ISSUE TITLE
cannot execute exe of tensorflow py compiled with pyinstaller

### ISSUE THREAD

**Issue by fafabone** [tensorflow/tensorflow#45988]
**System information**
- I used the basic example of tensorflow installing procedure:
`  import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))
`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
  I don't know
- TensorFlow installed from (source or binary):
  installed via pip. pip install tensorflow and pip install --upgrade tensorflow
- TensorFlow version (use command below):
  2.4.0
- Python version:
  Python 3.8.7rc1
- Bazel version (if compiling from source):
  Not compiled from source
- GCC/Compiler version (if compiling from source):
 Not compiled from source
- CUDA/cuDNN version:
  Tried:
  1- Without CUDA
  2- CUDA 11.1, no CUDNN
  3- CUDA 11.1,  CUDNN 8.1
  4- CUDA 11.1,  CUDNN 8.1, CUDA 10.1 over CUDA 11.1
Same result
- GPU model and memory:
   NVIDIA GeForce MX250

**Describe the current behavior**
I run python with the script:
```python
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
```
The right output is:
tf.Tensor(-29.82965, shape=(), dtype=float32)

I launch pyinstaller --onefile prova.py and this is the output:
 C:\Users\fabio\VSC>pyinstaller --onefile C:\Users\fabio\VSC\prova.py
103 INFO: PyInstaller: 4.1
103 INFO: Python: 3.8.7rc1
104 INFO: Platform: Windows-10-10.0.19041-SP0
106 INFO: wrote C:\Users\fabio\VSC\prova.spec
108 INFO: UPX is not available.
108 INFO: Extending PYTHONPATH with paths
['C:\\Users\\fabio\\VSC', 'C:\\Users\\fabio\\VSC']
131 INFO: checking Analysis
735 INFO: checking PYZ
1053 INFO: checking PKG
1061 INFO: Building because C:\Users\fabio\VSC\build\prova\prova.exe.manifest changed
1069 INFO: Building PKG (CArchive) PKG-00.pkg
22364 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
22370 INFO: Bootloader c:\windows\system32\venv\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
22373 INFO: checking EXE
22374 INFO: Rebuilding EXE-00.toc because pkg is more recent
22376 INFO: Building EXE from EXE-00.toc
22383 INFO: Appending archive to EXE C:\Users\fabio\VSC\dist\prova.exe
22465 INFO: Building EXE from EXE-00.toc completed successfully.

Then I run the exe and this is the output:
(venv) C:\Users\fabio\VSC>dist\prova.exe
Traceback (most recent call last):
  File "prova.py", line 1, in <module>
    import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))
  File "c:\windows\system32\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow\__init__.py", line 41, in <module>
  File "c:\windows\system32\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow\python\__init__.py", line 41, in <module>
  File "c:\windows\system32\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow\python\eager\context.py", line 35, in <module>
  File "c:\windows\system32\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow\python\pywrap_tfe.py", line 29, in <module>
ImportError: DLL load failed while importing _pywrap_tfe: Impossibile trovare il modulo specificato.
[20820] Failed to execute script prova

**Describe the expected behavior**
The exe file should return the tensor as the python script

**Standalone code to reproduce the issue**
Create a python script prova.py:
import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))

Run in the directory of the script
pyinstaller --onefile prova.py

Then run the exe resulting

How can I build a onefile exe from a script using tensorflow?
Thanks.

**Comment by ravikyram** [comment]
@fafabone 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
Please, check Your CPU/Python is on 32 bits?Please, refer #36167

Thanks!

**Comment by fafabone** [comment]
- My CPU is Intel® Core™ i7-10510U Processor and it supports AVX 2 instruction set:
https://ark.intel.com/content/www/us/en/ark/products/196449/intel-core-i7-10510u-processor-8m-cache-up-to-4-90-ghz.html#:~:text=Instruction%20Set%20Extensions,-Instruction%20Set%20Extensions&text=These%20can%20include%20SSE%20(Streaming,AVX%20(Advanced%20Vector%20Extensions).
- I have installed 2015-2019 C++ redistributable, 32bit and 64bit.
- I installed tensorflow via pip.
- Python is 64 bit as tensorflow ask in installation guide:
python -c "import platform;print(platform.architecture()[0])"
64bit
- My script py runs as expected, my exe created via pyinstaller doesn't.

**Comment by ravikyram** [comment]
@fafabone 

Just to verify are you able to import tensorflow. Thanks!

**Comment by fafabone** [comment]
Any solution for my problem?

**Comment by mihaimaruseac** [comment]
It seems it is a bug in pyinstaller not being able to properly load all needed DLLs. Not really a TF issue.

**Comment by fafabone** [comment]
Please, could you suggest a way to produce an exe running in windows starting from python script that imports tensorflow?
Thanks
