### ISSUE TITLE
Parallel execution of ops on tensors in unstacked list 

### ISSUE THREAD

**Issue by Susmit-A** [tensorflow/tensorflow#45984]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, mapping/vector operations execute only batches in parallel, implying that if an op has to be performed on multiple tensors in parallel, all of them should be stacked, and therefore have the same shape.
This feature will allow execution of all tensors in a python iterable in parallel, without requiring them to be stacked. It will be analogous to the `map` function in python.

**Will this change the current api? How?**
This will add a new function to the API, accepting two arguments: A callable and a python iterable of tensors, not necessarily of the same shape.
The callable takes a single argument, which can be a single or nested tensor.

**Who will benefit with this feature?**
This feature has a wide range of applications, and can benefit the entire community.

**Any Other info.**

**Comment by rmothukuru** [comment]
@Susmit-A,
You mentioned 

> This feature has a wide range of applications 

Can you specify some applications? Thanks!

**Comment by Susmit-A** [comment]
@rmothukuru Off the top, the main application would be parallel processing of temporal data with different number of timesteps, and parallel processing of images with different dimensions, both without padding.

Another classic application is the Parallel For, provided by matlab. Currently, parallelizing a loop using `tf.while_loop` adds unnecessary constraints and complexity.

**Comment by mdanatg** [comment]
I think the challenge here is that feeding a Python iterable/list into an efficient graph requires quite a few moving parts. It would be much more practical if that iterable was a TF structure that allowed uneven shapes, like RaggedTensor, TensorArray or Dataset.

Come to think of it, would `Dataset.from_generator(...).map(...)` work for this purpose? See [Dataset.from_generator](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator).

**Comment by Susmit-A** [comment]
@saxenasaurabh That is correct. The same can also be said for pythonic for loops - they take impractically long times for large lists.

@saxenasaurabh @mdanatg Please refer to `https://github.com/Susmit-A/addons/blob/master/tensorflow_addons/layers/adaptive_pooling.py`, specifically lines 76-83. This is a minimal example of an application, currently as a PR in tensorflow addons.

Here, I need to slice a tensor in multiple places *unevenly*, using a list of starting and ending indices.

**Comment by edloper** [comment]
`tf.map_fn` supports ragged tensors.  So you can do something like this:

```
x = tf.ragged.constant([[1, 2, 3], [4, 5], [6, 7, 8]])
def fn(row):
  return tf.math.cumsum(row)
tf.map_fn(fn, x)
```

(This is a trivial example, but you could do something more interesting in `fn`.)  

If your function returns a value with a different number of ragged dimensions than the input (or a different dtype than the input), then you'll need to specify `fn_output_signature` when calling `map_fn`.

If you want to use this with `tf.data`, you could do something along the lines of:

```
def fn():
  for i in range(1, 10):
    yield range(i)

dataset = tf.data.Dataset.from_generator(fn, output_types=tf.int32, output_shapes=[None])
batched = dataset.apply(tf.data.experimental.dense_to_ragged_batch(10))
print(next(iter(batched)))
```

For more details on ragged tensors, see: https://www.tensorflow.org/guide/ragged_tensor.

Also, see the "RaggedTensors" section on this page: https://www.tensorflow.org/api_docs/python/tf/map_fn.

**Comment by edloper** [comment]
> RaggedTensors cannot be used here since they can't be created by stacking a list of tensors - they require a list of python/numpy arrays.

See `tf.ragged.stack`.  https://www.tensorflow.org/api_docs/python/tf/ragged/stack

**Comment by Susmit-A** [comment]
@edloper Please read the previous comment - RaggedTensors cannot be created within a graph from a list of tensors - `tf.ragged.stack` requires a list of numpy/python values. Using tensors throws errors, and converting tensors to numpy objects breaks the graph.

**Comment by edloper** [comment]
I'm not sure what you mean by saying that RaggedTensors can't be created within a graph from a list of tensors.  E.g.:

```python
>>> # Stacking two dense tensors with different sizes.
>>> t3 = tf.constant([[1, 2, 3], [4, 5, 6]])
>>> t4 = tf.constant([[5], [6], [7]])
>>> assert isinstance(t3, tf.Tensor) and isinstance(t4, tf.Tensor)
>>> tf.ragged.stack([t3, t4], axis=0)
<tf.RaggedTensor [[[1, 2, 3], [4, 5, 6]], [[5], [6], [7]]]>
```

**Comment by Susmit-A** [comment]
@edloper Please refer to [this stackoverflow question](https://stackoverflow.com/questions/57346556/creating-a-ragged-tensor-from-a-list-of-tensors). This is the error thrown when creating RaggedTensors from a list of tensors. The solution provided in the link makes use of a for loop, rendering the use of RaggedTensors moot.

**Comment by edloper** [comment]
So you're getting an error from the following code?

```
a = tf.convert_to_tensor([1,2])
b = tf.convert_to_tensor([1,2,3])
tf.ragged.stack([a, b])
```

I find that surprising.  Can you give me a full stack trace?

**Comment by edloper** [comment]
Looking at lines 76-84 of the adaptive_pooling.py file you linked -- what exactly is it you want to happen here?  Do you want the `N=self.output_size[0]` different calls to `self.reduce_function` to be able to run in parallel?  If so, then that will already be the case -- `self.output_size[0]` is an int (not a tensor), so when the `call` method is wrapped in `tf.function`, the loop will be unrolled, and the resulting graph will contain different subgraphs for each iteration of the loop on line 76.  When the graph is run, the nodes in those subgraphs can run in parallel.

**Comment by Susmit-A** [comment]
The problem here is that the inputs to `call` may be of variable size, therefore requiring a graph retrace for every call.

**Comment by edloper** [comment]
If you need `call` to be able to take any number of input tensors, then I'd recommend combining them all into a single ragged tensor input.  I.e., rather than having `call` take a list of `N` float tensors with shape [A], have it take a single raggedTensor with shape [N, A].  Otherwise, `call` will need to be retraced for each different number of input tensors.

If the number of inputs doesn't vary too much, but the shape of each tensor varies, then you could try using the `experimental_relax_shapes` argument when calling the `tf.function` decorator to reduce the amount of retracing that's required.

**Comment by Susmit-A** [comment]
It is the shape that varies. However, `experimental_relax_shapes` still causes retracing.

**Comment by edloper** [comment]
With `experimental_relax_shapes`, it will retrace a couple times, but then should trace with a relaxed shape after that.  E.g., the following:

```python
@tf.function(experimental_relax_shapes=True)
def foo(x):
  print("Retrace", x.shape)
  return x

for i in range(10):
  foo(tf.range(i))
```

prints:

```
Retrace (0,)
Retrace (1,)
Retrace (None,)
```

So the graph gets retraced a total of 3 times (and won't get retraced again after that, unless the dtype or rank of the input changes).
