### ISSUE TITLE
TFLite Benchmark Binary Erroring with FastSpeech Model

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#45986]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

I used [nightly pre-built binary](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model_plus_flex) from [here](https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary)

FastSpeech Model used for benchmark can be downloaded from [here](https://github.com/tulasiram58827/TTS_TFLite/blob/main/models/fastspeech_quant.tflite)

Error : 

```
The input model file size (MB): 31.1646
 Initialized session in 13.661ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
ERROR: tensorflow/lite/kernels/expand_dims.cc:40 axis <= input_dims.size was not true.
ERROR: Node number 553 (EXPAND_DIMS) failed to prepare.

ERROR: tensorflow/lite/kernels/expand_dims.cc:40 axis <= input_dims.size was not true.
ERROR: Node number 553 (EXPAND_DIMS) failed to prepare.

ERROR: tensorflow/lite/kernels/expand_dims.cc:40 axis <= input_dims.size was not true.
ERROR: Node number 553 (EXPAND_DIMS) failed to prepare.

ERROR: tensorflow/lite/kernels/expand_dims.cc:40 axis <= input_dims.size was not true.
ERROR: Node number 553 (EXPAND_DIMS) failed to prepare.

ERROR: tensorflow/lite/kernels/expand_dims.cc:40 axis <= input_dims.size was not true.
```

After this error I converted the model with fixed size and I got this error.

```
The input model file size (MB): 31.1646
Initialized session in 13.661ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
ERROR: tensorflow/lite/kernels/range.cc:45 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 477 (RANGE) failed to invoke.

ERROR: tensorflow/lite/kernels/range.cc:45 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 477 (RANGE) failed to invoke.

ERROR: tensorflow/lite/kernels/range.cc:45 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 477 (RANGE) failed to invoke.

ERROR: tensorflow/lite/kernels/range.cc:45 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 477 (RANGE) failed to invoke.
```

**Comment by abattery** [comment]
The benchmark tool feeds random input data to the graph. The FastSpeech model may requires some valid set of data. If the model requires that, the random input data may break like the above case. Could you make sure that? @tulasiram58827 

+CCing @multiverse-tf

**Comment by tulasiram58827** [comment]
How to provide custom input to the model while performing benchmark?

Is there any argument? I can't see anything like that in the benchmark guide page of tensorflow docs

**Comment by abattery** [comment]
I don't have good knowledge on that part neither. @multiverse-tf can provide more information regarding the benchmark tool.

**Comment by multiverse-tf** [comment]
> How to provide custom input to the model while performing benchmark?
> 
> Is there any argument? I can't see anything like that in the benchmark guide page of tensorflow docs
> 

We do provide parameters (i.e. --input_layer, --input_layer_shape, --input_layer_value_range, --input_layer_value_files) to help set values of input layers. Pls refer to definitions [here]( https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L289-L307) in the [benchmark_tflite_model.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc)

For example, if the model has 2 inputs, one could add "--input_layer=in0,in1 --input_layer_shape=1,30:1 --input_layer_value_range=in0,0,4" when running the benchmark tool. Noting that:
1. one has to specify all inputs of the model for --input_layer and --input_layer_shape. However, the input name doesn't need to match that of the model. The tool simply assumes the same input tensor order that TFLite interpreter sees. Admittedly, this will be a bit inconvenient as one has to learn the exact order of input tensors but a TFLite model visualization tool (like [the one](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/visualize.py) TFLite provides or the [Netron](https://github.com/lutzroeder/netron)) will help.

2. In this case, the value of the 1st input tensor (i.e. in0) will be initialized randomly but limited between 0 and 4.


We will document these parameters in related docs asap.

> @abattery

**Comment by tulasiram58827** [comment]
Thanks @multiverse-tf your suggestions worked out. Hope they will be added to docs in future.

Also as mentioned by @abattery random inputs are feeded while benchmarking so I ran benchmarking iteratively 3 or 4 times. Atleast once I got the results. So I think this hack can also be used. But yeah this depends on luck :).

Thanks @abattery and @multiverse-tf  once again

**Comment by tensorbuffer** [comment]
@tulasiram58827 can you share the exact command line?

I am using the same tool and same model, I can run if I set the shape to 1,10 or 1,20, but not 1,30 or 1,50:
# android_aarch64_benchmark_model_plus_flex --graph=fastspeech_quant.tflite --input_layer=input_ids,speaker_ids,speed_ratios,f0_ratios,energy_ratios --input_layer_shape=1,50:1:1:1:1

INFO: STARTING!
INFO: Log parameter values verbosely: [0]
INFO: Num threads: [1]
INFO: Graph: [fastspeech_quant.tflite]
INFO: Signature to run: []
INFO: Input layers: [input_ids,speaker_ids,speed_ratios,f0_ratios,energy_ratios]
INFO: Input shapes: [1,50:1:1:1:1]
INFO: #threads used for CPU inference: [1]
INFO: Loaded model fastspeech_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 964 nodes with 1 partitions.

VERBOSE: Replacing 2 out of 964 node(s) with delegate (TfLiteFlexDelegate) node, yielding 3 partitions for the whole graph.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
VERBOSE: Replacing 535 out of 963 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 241 partitions for the whole graph.
INFO: The input model file size (MB): 31.016
INFO: Initialized session in 257.588ms.
INFO: Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
ERROR: tensorflow/lite/kernels/range.cc:50 (start >= limit && delta < 0) || (start <= limit && delta > 0) was not true.
ERROR: Node number 526 (RANGE) failed to invoke.
INFO: count=7 first=81437 curr=75866 min=75555 max=81437 avg=76472.1 std=2029 p5=75555 median=75584 p95=81437
