### ISSUE TITLE
Install Error "github.com/tensorflow/examples"

### ISSUE THREAD

**Issue by ToshihiroIwaki** [tensorflow/tensorflow#45985]
Would you tell me?
I want install "tensorflow example" from Anaconda for windows10.

However, no matter how many times I repeat it, I get an error.

Installed anaconda3

**Procedure so far
conda create -n insta1
conda activate insta1
conda install python=3.7.5
git clone https://github.com/tensorflow/examples
(insta1) C:\installation\insta2020-01\examples\tensorflow_examples\lite\model_maker\pip_package>pip install -e .

**Error contents
---------------------------------
(insta1) C:\installation\insta2020-01\examples\tensorflow_examples\lite\model_maker\pip_package>pip install -e .
Obtaining file:///C:/installation/insta2020-01/examples/tensorflow_examples/lite/model_maker/pip_package
    ERROR: Command errored out with exit status 1:
     command: 'C:\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\installation\\insta2020-01\\examples\\tensorflow_examples\\lite\\model_maker\\pip_package\\setup.py'"'"'; __file__='"'"'C:\\installation\\insta2020-01\\examples\\tensorflow_examples\\lite\\model_maker\\pip_package\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\toshi\AppData\Local\Temp\pip-pip-egg-info-su_59rf8'
         cwd: C:\installation\insta2020-01\examples\tensorflow_examples\lite\model_maker\pip_package\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\installation\insta2020-01\examples\tensorflow_examples\lite\model_maker\pip_package\setup.py", line 232, in <module>
        setup_extra = prepare_package_src()
      File "C:\installation\insta2020-01\examples\tensorflow_examples\lite\model_maker\pip_package\setup.py", line 188, in prepare_package_src
        namespace_packages = find_namespace_packages(where=BUILD_ROOT)
      File "C:\anaconda3\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\anaconda3\lib\distutils\util.py", line 121, in convert_path
        if pathname[0] == '/':
    TypeError: 'WindowsPath' object is not subscriptable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ymodak** [comment]
Can you try using `pip` to install `tflite-model-maker`?
` pip install  tflite-model-maker`

**Comment by walterdumba** [comment]
Hi there, I also reproducing the same issue
I'm running python 3.8.7 and also carefully double-checked the required dependencies versions for running this example
Here's my stacktrace:

C:\Users\Walter\Downloads\tensorflow-examples\tensorflow_examples\lite\model_maker\pip_package>pip install -e .
Obtaining file:///C:/Users/Walter/Downloads/tensorflow-examples/tensorflow_examples/lite/model_maker/pip_package
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Walter\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Walter\\Downloads\\tensorflow-examples\\tensorflow_examples\\lite\\model_maker\\pip_package\\setup.py'"'"'; __file__='"'"'C:\\Users\\Walter\\Downloads\\tensorflow-examples\\tensorflow_examples\\lite\\model_maker\\pip_package\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Walter\AppData\Local\Temp\pip-pip-egg-info-fcpvhhz7'
         cwd: C:\Users\Walter\Downloads\tensorflow-examples\tensorflow_examples\lite\model_maker\pip_package\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Walter\Downloads\tensorflow-examples\tensorflow_examples\lite\model_maker\pip_package\setup.py", line 240, in <module>
        setup_extra = prepare_package_src()
      File "C:\Users\Walter\Downloads\tensorflow-examples\tensorflow_examples\lite\model_maker\pip_package\setup.py", line 196, in prepare_package_src
        namespace_packages = find_namespace_packages(where=BUILD_ROOT)
      File "C:\Users\Walter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2032.0_x64__qbz5n2kfra8p0\lib\distutils\util.py", line 121, in convert_path
        if pathname[0] == '/':
    TypeError: 'WindowsPath' object is not subscriptable
    ----------------------------------------
WARNING: Discarding file:///C:/Users/Walter/Downloads/tensorflow-examples/tensorflow_examples/lite/model_maker/pip_package. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Thank you in advance
