### ISSUE TITLE
TF2.3; tensorflow.python.framework.errors_impl.UnknownError: Failed to rename; : Access is denied. ; Input/output error

### ISSUE THREAD

**Issue by gmatalongthewatchtower** [tensorflow/tensorflow#45980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Conda; TF 2.3; 
- TensorFlow version (use command below): 2.3
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Stackoverflow: https://stackoverflow.com/questions/65461750/tensorflow-python-framework-errors-impl-unknownerror-failed-to-rename-access
I am not able to download and load tensorflow dataset on my Windows 10 machine. It works okay on Google colab. 

**Describe the expected behavior**
I should be able to download the datasets. 

**Standalone code to reproduce the issue**

```
import tensorflow_datasets as tfds
datasets, info = tfds.load("imdb_reviews", as_supervised=True, with_info=True
```

**Error:**

```

Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]
Shuffling...:  90%|█████████ | 18/20 [00:01<00:00, 14.15 shard/s]
Reading...: 0 examples [00:00, ? examples/s]
                                            
Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]
                                                           
Reading...: 0 examples [00:00, ? examples/s]
                                            
Writing...:   0%|          | 0/2500 [00:00<?, ? examples/s]
Traceback (most recent call last):
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3b586bfe81d7>", line 3, in <module>
    datasets, info = tfds.load("imdb_reviews", as_supervised=True, with_info=True)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow_datasets\core\registered.py", line 300, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 307, in download_and_prepare
    self.info.write_to_directory(self._data_dir)
  File "C:\Anaconda3\envs\ml_tf\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow_datasets\core\file_format_adapter.py", line 200, in incomplete_dir
    tf.io.gfile.rename(tmp_dir, dirname)
  File "C:\Anaconda3\envs\ml_tf\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 546, in rename_v2
    compat.as_bytes(src), compat.as_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: C:\Users\User\tensorflow_datasets\imdb_reviews\plain_text\0.1.0.incomplete5JQVCL to: C:\Users\User\tensorflow_datasets\imdb_reviews\plain_text\0.1.0 : Access is denied.
; Input/output error
```

**Conda list**

```
tensorboard               2.3.0              pyh4dce500_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.3.0           mkl_py37h3bad0a6_0
tensorflow-base           2.3.0           eigen_py37h17acbac_0
tensorflow-datasets       1.2.0                    py37_0
tensorflow-estimator      2.3.0              pyheb71bc4_0
tensorflow-metadata       0.14.0             pyhe6710b0_1
tensorflow-mkl            2.3.0                h93d2e19_0
```

**Comment by Saduf2019** [comment]
@gmatalongthewatchtower 
I ran the code shared on tf nightly and did not face any issues, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d8d644ec98eee653cdd7186e9e2fd092/untitled488.ipynb).

**Comment by gmatalongthewatchtower** [comment]
@Saduf2019 : this is an issue on Windows 10. Google Colab uses Linux. I don't see this issue on Google Colab. If you Google this error, many people are facing the issue.

**Comment by gmatalongthewatchtower** [comment]
Here's a sample github issue thread: https://github.com/tensorflow/tensorflow/issues/41380. There are way too many issues on this topic.

**Comment by ymodak** [comment]
Are you able to load [tf keras datasets](https://www.tensorflow.org/api_docs/python/tf/keras/datasets/imdb/load_data)?
```python
tf.keras.datasets.imdb.load_data()
```

**Comment by gmatalongthewatchtower** [comment]
Yes, that works well without any issues. I got a bunch of deprecation warnings, but there was no issue with the code.

**Comment by ymodak** [comment]
Thanks for confirming. Can you please raise this issue on TensorFlow Datasets repository as well?
https://github.com/tensorflow/datasets/issues
cc @Conchylicultor

**Comment by mh-hassan18** [comment]
I am also getting this error on: Windows 10; TF 2.3; Python 3.7

tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: path\trial_5a095c02600a30dc086a9efe046b1272\checkpoints\epoch_0\checkpoint_temp/part-00000-of-00001.data-00000-of-00001 to: path\trial_5a095c02600a30dc086a9efe046b1272\checkpoints\epoch_0\checkpoint.data-00000-of-00001 : Access is denied. 
; Input/output error [Op:MergeV2Checkpoints]

**Comment by ymodak** [comment]
This works with TF 2.4.1 and TF Datasets 4.0.1
