### ISSUE TITLE
Simplify GPU usage model

### ISSUE THREAD

**Issue by marcusobrien** [tensorflow/tensorflow#45982]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0 - Python
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
IMO many new developers are using TF as it supports CUDA, and they have a single GPU they want to use. So one common use case is a single GPU. To utilize a GPU device script writers are using the following code 

```python
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

Can we have a simple API that enables the GPU first device ?

proposed API

experimental:
```python
configure_default_device(string physical_device_name, int device_number)
get_default_device()
```

example usage:
```python
tf.config.experimental.configure_default_device('GPU', 0)

get_default_device()
     example settings above would return
                  "GPU" device 0

```
**Will this change the current api? How?**
Yes
Simplify a common use case, and abstract away these settings so they can be changed in future without developers having to re-write their scripts ie when moving to later TF version

**Who will benefit with this feature?**
Many new developers with a single GPU

**Any Other info.**
It would be good to extend the API to handle specific GPU devices, or to set the engine to use all of them. Another API would show the current settings.

**Comment by rmothukuru** [comment]
@marcusobrien,
[Tensorflow GPU Documentation](https://www.tensorflow.org/guide/gpu?hl=en) states: 

> TensorFlow code, and tf.keras models will transparently run on a single GPU with no code changes required.
> 
> **Note: Use tf.config.experimental.list_physical_devices('GPU') to confirm that TensorFlow is using the GPU.**

Is your use case not the same as mentioned above?

**Comment by rmothukuru** [comment]
@marcusobrien,
Can you please respond to the above comment? Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
