### ISSUE TITLE
How to read .bin file using Tensorflow C++ api?

### ISSUE THREAD

**Issue by Suri12990** [tensorflow/tensorflow#45990]
Hey all,

I need to read lidar point cloud from .bin folder. But I could not able to find an API in c++ to achieve my task. could anyone help me with this? 

Tensorflow version 1.4.0

Thanks in advance.

**Comment by Saduf2019** [comment]
@Suri12990 
We see that you are using 1.x which is not supported, please upgrade to 2.x

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Suri12990** [comment]
Thank you so much, I got the answer.
