### ISSUE TITLE
from tensorflow.contrib.layers.python.layers.initializers import variance_scaling_initializer

### ISSUE THREAD

**Issue by andreixxi** [tensorflow/tensorflow#45992]
`from tensorflow.contrib.layers.python.layers.initializers import variance_scaling_initializer`<br>
ImportError: No module named slim.layers.python.layers.initializers<br>
is there a new way to do this ?

**Comment by jvishnuvardhan** [comment]
@andreixxi You can import `variance_scaling_initializer` as `from tensorflow.contrib.layers import variance_scaling_initializer`.
Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5ed76051d2a1f0623b88708a6f93ebb9/untitled69.ipynb). Thanks!

I am closing this issue as it was resolved. Feel free to reopen if the issue persists. thanks!
