### ISSUE TITLE
Tensorflow 2.4 requires BMI2 CPU extension (AVX is not enough)

### ISSUE THREAD

**Issue by ant-pls-dev** [tensorflow/tensorflow#45991]
**System information**
- OS Platform and Distribution : Debian GNU/Linux 10 (buster) (and Ubuntu)
- TensorFlow installed from (source or binary): binary

```
== check python ===================================================
python version: 3.6.9
python branch: 
python build version: ('default', 'Oct  8 2020 12:12:24')
python compiler version: GCC 8.4.0
python implementation: CPython

== check os platform ===============================================
os: Linux
os kernel version: #1 SMP Debian 4.19.160-2 (2020-11-28)
os release version: 4.19.0-13-amd64
os platform: Linux-4.19.0-13-amd64-x86_64-with-Ubuntu-18.04-bionic
linux distribution: ('Ubuntu', '18.04', 'bionic')
linux os distribution: ('Ubuntu', '18.04', 'bionic')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='90e48bf24072', release='4.19.0-13-amd64', version='#1 SMP Debian 4.19.160-2 (2020-11-28)', machine='x86_64', processor='x86_64')
architecture: ('64bit', 'ELF')
machine: x86_64

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                  1.19.4
protobuf               3.14.0
tensorflow             2.4.0
tensorflow-estimator   2.4.0rc0

== check for virtualenv =========================================
False

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.4.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 9, 'final', 0)
```

**Describe the current behavior**
import tensorflow fails with "Illegal Instruction" on a CPU with AVX

**Describe the expected behavior**
according to the documentation (https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements), all CPU with AVX are supported, so the import should not fail

**Standalone code to reproduce the issue**
python3
`>>> import tensorflow`

**Other info / logs**
The problem comes from an instruction from the "BMI2" extension. Output from GDB : 
```
Program received signal SIGILL, Illegal instruction.
0x00007fb5fe658c48 in tensorflow::UnaryVariantOpRegistry::RegisterDeviceCopyFn(tensorflow::VariantDeviceCopyDirection, tensorflow::TypeIndex const&, std::function<tensorflow::Status (tensorflow::Variant const&, tensorflow::Variant*, std::function<tensorflow::Status (tensorflow::Tensor const&, tensorflow::Tensor*)>)> const&) () from /usr/local/lib/python3.6/dist-packages/tensorflow/python/../libtensorflow_framework.so.2
```

Which points to instruction **SHLX**.

Some older CPUs do have AVX, but not BMI2 : 
- Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
- Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz

example output of lscpu : 
`Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d`

Best Regards

**Comment by mihaimaruseac** [comment]
Related #45744, #45866

**Comment by rmothukuru** [comment]
@ant-pls-dev,
Can you please confirm if we can close this issue as it is already being tracked in the issues [mentioned above](https://github.com/tensorflow/tensorflow/issues/45991#issuecomment-751809042) by @mihaimaruseac? Thanks!

**Comment by mihaimaruseac** [comment]
Duplicating to #45744

**Comment by ant-pls-dev** [comment]
Hello, other tickets only mention avx2 and I saw no mention of BMI2 instructions, so I was not sure it was the same issue. If you are confident the commit will also fix the requirement on BMI2, then I'm fine with closing this ticket.
Thank you,
Best regards
