### ISSUE TITLE
TF 2.4.0 crashes on startup with IndexError assuming that sys.argv[0] exists when it may be hosted by C++ (regression from 2.3.1)

### ISSUE THREAD

**Issue by chrisbutner** [tensorflow/tensorflow#45994]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Linux Debian 10
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.4.0
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.7.9
- CUDA/cuDNN version: 11.0, 8.0.4 for 11.0
- GPU model and memory: NVIDIA GTX 1080

**Describe the current behavior**

TF 2.4.0 crashes on startup with:
```
File "...\site-packages\tensorflow\python\distribute\combinations.py", line 159, in GPUCombination
GPU_TEST = re.search(r"(test_gpu|test_xla_gpu)$", sys.argv[0])
IndexError: list index out of range
```

**Describe the expected behavior**
sys.argv is checked to be non-empty before indexing (no bug on TF 2.3.1)

**Standalone code to reproduce the issue**

1. Ensure that PYTHONHOME is set
2. Py_Initialize()
3. Append our module's directory to the system path: (PyImport_ImportModule("sys"), PyObject_GetAttrString(sys, "path"), PyUnicode_FromString("..."), PyList_Append(sysPath, ...))
4. Import our module: PyImport_ImportModule("...")
5. Our module calls "import tensorflow as tf", which then crashes

**Python-only mock repro**
```
import sys
sys.argv.clear()
import tensorflow as tf
```

**Workaround**
```
# Work around https://github.com/tensorflow/tensorflow/issues/45994
import sys
if not sys.argv:
  sys.argv.append("(C++)")

import tensorflow as tf
```

**Notes**

It may help to write a unit test/build verification test that mocks this scenario by clearing sys.argv before importing tensorflow.

**Comment by chrisbutner** [comment]
Some clarifications:
- This also repros on Linux (e.g. the Debian 10 images on Google Cloud)
- This is a runtime crash bug when trying to make use of TensorFlow, not a build/install issue

**Comment by mihaimaruseac** [comment]
Able to reproduce:

```
>>> import sys
>>> print(sys.argv)
['']
>>> sys.argv.clear()
>>> print(sys.argv)
[]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 49, in <module>
    from ._api.v2 import __internal__
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 13, in <module>
    from . import distribute
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/_api/v2/__internal__/distribute/__init__.py", line 10, in <module>
    from . import combinations
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/_api/v2/__internal__/distribute/combinations/__init__.py", line 10, in <module>
    from tensorflow.python.distribute.combinations import generate
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/python/distribute/combinations.py", line 146, in <module>
    class GPUCombination(combinations_lib.TestCombination):
  File "/tmp/tfff/venv/lib/python3.8/site-packages/tensorflow/python/distribute/combinations.py", line 160, in GPUCombination
    GPU_TEST = re.search(r"(test_gpu|test_xla_gpu)$", sys.argv[0])
IndexError: list index out of range
```

Rick, since this is in DistStrat, can you take a look please?

**Comment by chrisbutner** [comment]
Very recently I actually hit an even stronger case of this - sys didn't actually even have an "argv" attribute at all, hosting via C++. I believe this was on "newer" TPUs, using Ubuntu 18.04 LTS, Python 3.7.

I updated my workaround to this to cover both cases:
```
import sys
if not hasattr(sys, "argv") or not sys.argv:
  sys.argv = [""]
```

**Comment by mooch443** [comment]
I can confirm that the steps in https://github.com/tensorflow/tensorflow/issues/45994#issuecomment-791823979 still reproduce the issue for me as well.

Python 3.7.9
Debian Linux 5.10.0-4-amd64
NVIDIA 1080 TI
cudnn 7.6.5 cudatoolkit 10.1.243
Tensorflow 2.4.1

The suggested workaround helps.

**Comment by scdub** [comment]
A fix on this issue would be appreciated -- in [embedded contexts](https://docs.python.org/3/extending/embedding.html), `sys.argv[0]` is not guaranteed to be set.

**Comment by jvishnuvardhan** [comment]
@chrisbutner Is this still an issue for you? Can you please check with recent TF (i tried `tf-nightly`) and let us know whether this is still an issue. Thanks!

**Comment by scdub** [comment]
This issue is still present, and can be identified by searching for `sys.argv[0]` instances in the codebase, and is still present in the nightly builds.

**Comment by chrisbutner** [comment]
This repro, importing tensorflow in embedded python, seems fixed (via https://github.com/tensorflow/tensorflow/commit/c8cb67f4c27ec312d228a344ed124bb34cbee74b, @scdub). Thanks!
