### ISSUE TITLE
How to access operations of the tf graph from a keras model? (for tf 2.4.0)

### ISSUE THREAD

**Issue by jiafatom** [tensorflow/tensorflow#45993]
**System information**
- TensorFlow installed from (source or binary): pypi
- TensorFlow version (use command below): 2.4.0

**Describe the current behavior**
Starting from tensorflow 2.4.0, it seems that the keras model cannot access the operations of the backend tf graph. I am looking at `keras.backend.get_session().graph`, is this the right way to access tf.graph? If I do `keras.backend.get_session().graph.get_operations()`, it returns an empty array.
Note that we can do this successfully for tf 1.x. And for tf 2.3, we can access tf graph by `model.outputs[0].graph`, however, `model.ouputs[0]` does not have `graph` for tf 2.4.
That is:
```python
# keras == 2.3.1, tensorflow == 2.3.0
from tensorflow.python import keras  
model = keras.models.Sequential()
model.add(keras.layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
tf_operations = model.outputs[0].graph.get_operations()
print(len(tf_operations))
# result: 8

# keras == 2.3.1, tensorflow == 1.15.0
from tensorflow.python import keras  
model = keras.models.Sequential()
model.add(keras.layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
tf_operations = keras.backend.get_session().graph.get_operations()
print(len(tf_operations))
# result: 25
```
but for tensorflow==2.4.0, if I use:
```python
tf_operations = model.outputs[0].graph.get_operations()
```
then it throws errors `AttributeError: 'KerasTensor' object has no attribute 'graph'`
and it returns 0 when I `print(len(tf_operations))` for `tf_operations = keras.backend.get_session().graph.get_operations()`

**Comment by Saduf2019** [comment]
@jiafatom 
I ran the code shared and find indentation errors, please provide with complete stand alone code such that we can replicate the issue faced, or if possible share a colab gist with error reported.

**Comment by jiafatom** [comment]
@Saduf2019 I just updated the code in the description. The code should be straightforward. Please let me know if you still have issues.

**Comment by Saduf2019** [comment]
@jiafatom 
I ran the code shared and face this error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a03b07436074537c30bd38cf066768f1/untitled489.ipynb).

**Comment by jiafatom** [comment]
@Saduf2019 Yes, you have repro the same error I am talking about in the description, and this is my question.
From description, I mentioned:

but for tensorflow==2.4.0, if I use:
tf_operations = model.outputs[0].graph.get_operations()
then it throws errors AttributeError: 'KerasTensor' object has no attribute 'graph'

This is because the `graph` attribute is no longer in `model.outputs[0]`. But in tf 2.3, it works successfully.
So the question is how to access the graph (the tf graph operations) in tf 2.4.

**Comment by Saduf2019** [comment]
@jvishnuvardhan 
The error is producible in nightly as well, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e9f93c926cd912b3a835fe36b01aed64/untitled488.ipynb).
