### ISSUE TITLE
Missing "pip install --upgrade pip" in instructions leads to bogus error "No such file or directory ... setup.py"

### ISSUE THREAD

**Issue by mrob27** [tensorflow/tensorflow#46]
I set up a virtualenv and ran ./bin/activate then tried the install command:

```
(tensorflow) $ ./bin/pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
  Downloading tensorflow-0.5.0-py2-none-any.whl (9.8Mb): 9.8Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build
Storing complete log in /Users/munafo/.pip/pip.log
(tensorflow) $ ls -l /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py 
-rw-r--r--  1 munafo  staff  2574 Nov  9 17:41 /var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py
(tensorflow) $
```

As shown in the session, there is no `/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/setup.py`, but there is a `/var/folders/gQ/gQ784XlzFBu-AAhgOvz4Ek+++TI/-Tmp-/pip-emt5Bl-build/tensorflow/tools/pip_package/setup.py`

So I suspect pip is failing to interpolate the subdirectory `tensorflow/tools/pip_package` into the path when trying to launch setup.py.

[Here](http://stackoverflow.com/questions/33623453/pip-installation-error-no-such-file-or-directory-setup-py) is another report of the same problem on Linux (the question asker is trying to install tensorflow-0.5.0-cp27-none-linux_x86_64.whl  , and a comment was added by a user who has Ubuntu 12.04)

**Comment by mrob27** [comment]
I fixed it by typing "pip install --upgrade pip" in the virtualenv (i.e. right after typing "source ./bin/activate"

This instruction needs to be added to the [instructions](http://tensorflow.org/get_started/os_setup.md#virtualenv_install)

**Comment by craigcitro** [comment]
Yes -- thanks @mrob27 for figuring out the right fix; we've updated the docs and these instructions will be in the next push.

(Closing, reopen if needed.)
