### ISSUE TITLE
ConverterError: <unknown>:0: error: loc("lstm_bias_lstm_17"): is not immutable (RNN)

### ISSUE THREAD

**Issue by nehasoni3** [tensorflow/tensorflow#46006]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): 2.4.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
`import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()`

**The output from the converter invocation**
`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    212                                                  debug_info_str,
--> 213                                                  enable_mlir_converter)
    214       return model_str

4 frames
Exception: <unknown>:0: error: loc("lstm_bias_lstm_17"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable

During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    214       return model_str
    215     except Exception as e:
--> 216       raise ConverterError(str(e))
    217 
    218   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("lstm_bias_lstm_17"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable`

**Comment by renjie-liu** [comment]
Hi, do you have more details, like what model you're building?

thanks

**Comment by nehasoni3** [comment]
> Hi, do you have more details, like what model you're building?
> 
> thanks

Hi @renjie-liu 
actually, model is trained on PyTorch and I have converted it on ONNX to Tensorflow.
Model is Tacotron2 for TTS.

**Comment by renjie-liu** [comment]
I see, unfortunately since we don't officially support PyTorch conversion, it might be somewhere broken either between pytorch -> onnx or onnx-> tensorflow.

Jae probably can point you about the tensorflow version of Tacotron2

**Comment by nehasoni3** [comment]
> I see, unfortunately since we don't officially support PyTorch conversion, it might be somewhere broken either between pytorch -> onnx or onnx-> tensorflow.
> 
> Jae probably can point you about the tensorflow version of Tacotron2

There are other models(even TTS)  also which converted into TFLite from PyTorch. I can share ONNX graph.

**Comment by jaeyoo** [comment]
Hi, here is (unofficial) TF version of Tacotron2.

https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/TensorFlowTTS_Tacotron2_with_TFLite.ipynb

You can also ask any questions on that repo issues. Thanks.

**Comment by nehasoni3** [comment]
> Hi, here is (unofficial) TF version of Tacotron2.
> 
> https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/TensorFlowTTS_Tacotron2_with_TFLite.ipynb
> 
> You can also ask any questions on that repo issues. Thanks.

I have tried this TTS also. It is working but I want to convert my own model into TFLite. Is this issue is something unsolvable?

**Comment by nehasoni3** [comment]
Hi
I have tried some things and now,error is changed.
**tensorflow.lite.python.convert.ConverterError: input resource[0] expected type resource != float, the type of assignvariableop_resource_0[0]**
@abattery @jaeyoo

**Comment by abattery** [comment]
According to the converter error message, the TensorFlow model you've created has the mutable resource variables or the stateful LSTM nodes, which are not currently not supported. We are working on supporting those features. However, it will take some times.

**Comment by abattery** [comment]
Please try out TensorFlow 2.6 or tf-nightly version with `converter.experimental_enable_resource_variables = True`>

**Comment by lzc16** [comment]
Hi @abattery !
I have try your method
> Please try out TensorFlow 2.6 or tf-nightly version with `converter.experimental_enable_resource_variables = True`.
And it can convert tensorflow to tflite. But when it put some warning and log error when start network forward.

Here is the warning.

```
2021-09-17 10:46:25.251638: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1844] Graph contains the following resource op(s), that use(s) resource type. Currently, the resource type is not natively supported in TFLite. Please consider not using the resource type if there are issues with either TFLite converter or TFLite runtime:
Resource ops: AssignVariableOp, ReadVariableOp, VarHandleOp
Details:
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> () : {device = ""}
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<1x1xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<768x1024xf32>) -> () : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>) -> (tensor<1024xf32>) : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>) -> (tensor<?x?xf32>) : {device = ""}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<1024xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_bias_lstm_18"}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<?x?xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_kernel_lstm_18"}
2021-09-17 10:46:25.252215: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1855] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexAssignVariableOp, FlexReadVariableOp, FlexVarHandleOp
Details:
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>, tensor<1024xf32>) -> () : {device = ""}
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<1x1xf32>) -> ()
        tf.AssignVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>, tensor<768x1024xf32>) -> () : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<1024xf32>>>) -> (tensor<1024xf32>) : {device = ""}
        tf.ReadVariableOp(tensor<!tf_type.resource<tensor<?x?xf32>>>) -> (tensor<?x?xf32>) : {device = ""}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<1024xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_bias_lstm_18"}
        tf.VarHandleOp() -> (tensor<!tf_type.resource<tensor<?x?xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_kernel_lstm_18"}

```

It there any suggestion to solve the problem?

Thanks.

**Comment by abattery** [comment]
Please do not upload a new issue at the closed one.
