### ISSUE TITLE
Weight Normalization layer doesn't work with mixed precision

### ISSUE THREAD

**Issue by stephen-systemfriend** [tensorflow/tensorflow#46001]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Minimal
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 'v2.4.0-rc4-71-g582c8d236cb'
- Python version: 3.8
- CUDA/cuDNN version: CUDA 11  cudnn 8
- GPU model and memory: RTX 2080 11gb

**Describe the current behavior**
when using mixed precision and the weight normalization layer from tensorflow_addons, it throws an error 
`    ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'sequential/weight_normalization/cond/data_dep_init/mul:0' shape=(10,) dtype=float16>`
from
```
assign_tensors = self._data_dep_init(inputs)
    \tensorflow_addons\layers\wrappers.py:204 _data_dep_init
        g_tensor = self.g.assign(self.g * scale_init)
    \tensorflow\python\keras\mixed_precision\autocast_variable.py:225 assign
```

**Describe the expected behavior**
layer to build and run normally as it does in float32 and float16 policies

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np

policy = tf.keras.mixed_precision.Policy("mixed_float16")
#runs fine with all the same type
#policy = tf.keras.mixed_precision.Policy("float16")

tf.keras.mixed_precision.set_global_policy(policy)

model = tf.keras.Sequential()

model.add(tfa.layers.WeightNormalization(tf.keras.layers.Dense(10, activation="relu")))

model.compile(loss=tf.keras.losses.MeanSquaredError())

X = np.random.randn(1,20)
Y = np.random.randn(1,10)

model.fit(X,Y)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

putting a tf.cast inside each call to assign in wrappers.py -> WeightNormalization stops the error, but I'm not certain if that is correct from a numerical stability perspective, and it seems like adding some functionality to the assign function in mixedPrecision/autocast_variable.py -> AutocastVariable would be better

**Comment by byronyi** [comment]
cc @reedwm

**Comment by Saduf2019** [comment]
I am able to replicate the issue on [tf 2.4 ](https://colab.research.google.com/gist/Saduf2019/9ef23bf617d4894247f5e05c7ea6366d/untitled489.ipynb)and [nightly](https://colab.research.google.com/gist/Saduf2019/16e724296666d25053cf6e19cc6e02a0/untitled488.ipynb)

**Comment by stephen-systemfriend** [comment]
as a side note, there are 2 separate implementations of Weight Normalization in the tensorflow ecosystem (one in tensorflow_addons and one in tensorflow_probability). I'm not sure what the right architectural decision should be about how to unify that, but in the least we should make sure that any bugs that are fixed in one also are fixed in the other.

**Comment by byronyi** [comment]
cc @seanpmorgan @smokrow

**Comment by saikumarchalla** [comment]
Was able to reproduce te issue in TF 2.6 Nightly version as well.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/27f72978f98493a33e5efc6207fd1ced/untitled90.ipynb).

**Comment by reedwm** [comment]
This should be filed in the [tensorflow/addons](https://github.com/tensorflow/addons) repository, so I'm closing the issue here.

I am not familiar with WeightNormalization, but skimming the layer implementation, I think most the math should be done in float32. The error comes from setting a float32 variable to a float16 value [at this line](https://github.com/tensorflow/addons/blob/b68af5c611dd06894ad282ec263a92e1681c83db/tensorflow_addons/layers/wrappers.py#L204). The layer previously calls `tf.nn.moments`, which should also be done in float32
