### ISSUE TITLE
keras.Model.fit error with 2.4 and TPUv3

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#46003]
My code is worked in 2.3 and 2.4 with GPU. And it is failed when doing "keras.Model.fit" in Cloud TPU with 2.4, but worked in 2.3.1 and nightly.

In the past, this error is only encountered when the TensorFlow version in TPU does not fully matched the version in VM.

**Comment by ravikyram** [comment]
@edwardyehuang 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
