### ISSUE TITLE
gpu out of mempry

### ISSUE THREAD

**Issue by daeing** [tensorflow/tensorflow#46027]
i difined a simple model use tensorflow2.0, but it run slowly. then i code gpustat in terminal, i found gpu out of memory. i run the same code use tensorflow tensorflow1.15, it runs normaly, and gpu memory cost correctly. the model defined as follow:

model = keras.Sequential([
    layers.Reshape(target_shape=(28 * 28,), input_shape=(28, 28)),
    layers.Dense(100, activation='relu'),
    layers.Dense(100, activation='relu'),
    layers.Dense(10)])

what should i do?

**Comment by ravikyram** [comment]
@daeing 

Can you try with latest TF stable version 2.4 or nightly version and see if the performance issue still persists.If the issue still present ,request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by daeing** [comment]
> @daeing
> 
> Can you try with latest TF stable version 2.4 or nightly version and see if the performance issue still persists.If the issue still present ,request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

Thank you for your replying. I trid tensorflow2.4 in windows, it runs normaly. 

During I deal with this question. I installed cuda 9, cuda 10.0, cuda 10.1, and cuda 11 my driver suggest me install. Then I created virtual environment in anaconda, such as tensorflow115, tensorflow20, tensorflow22, and use pip install tensorflow-gpu==1.15/ pip install tensorflow-gpu==2.0 / pip install tensorflow==2.2. After that, i enter the environment,  I code tf.test.is_gpu_available() it didn't work, no answer(True, False).  Can you give me some suggestion?

**Comment by ravikyram** [comment]
@daeing 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source_windows#gpu) and gpu installation guide for windows from [here](https://www.tensorflow.org/install/gpu#windows_setup) and see if it helps you.Thanks!
