### ISSUE TITLE
import_meta_graph: ValueError: At least two variables have the same name: Variable_1

### ISSUE THREAD

**Issue by snbuchholz** [tensorflow/tensorflow#4603]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: Ubuntu 16.04.1 LTS
Installed version of CUDA and cuDNN: none
pip package: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
$ python -c "import tensorflow; print(tensorflow.__version__)"
0.10.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Using commands from https://www.tensorflow.org/versions/r0.9/get_started/index.html to create a model:

```
import tensorflow as tf
import numpy as np
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))
y = W * x_data + b
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
sess.run(train)
```

Then this works:
```
saver = tf.train.Saver()
saver.save(sess, 'my-model')
sess = tf.Session()
new_saver = tf.train.import_meta_graph('my-model.meta')
```
But this doesn't:
```
tf.train.export_meta_graph(filename='my-model.meta')
new_saver = tf.train.import_meta_graph('my-model.meta')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1458, in import_meta_graph
    return _import_meta_graph_def(read_meta_graph_file(meta_graph_or_file))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1386, in _import_meta_graph_def
    return Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 861, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 502, in build
    vars_to_save = self._ValidateAndSliceInputs(names_to_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 399, in _ValidateAndSliceInputs
    names_to_variables = self._VarListToDict(names_to_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 377, in _VarListToDict
    name)
ValueError: At least two variables have the same name: Variable_1

What I actually want to use is this, which also does not work (same error):
```
meta_graph_def = tf.train.export_meta_graph()
saver = tf.train.import_meta_graph(meta_graph_def)
```
I need a solution that does not rely on the file system.
Am I doing something wrong?

### What other attempted solutions have you tried?
I tried to look at the files to see where these duplicated names occur but did not find any.

**Comment by concretevitamin** [comment]
You should call `tf.train.import_meta_graph()` with a cleared `Graph`.  Example:

```python

    # Create a clean graph and import the MetaGraphDef nodes.
    new_graph = tf.Graph()
    with tf.Session(graph=new_graph) as sess:
      # Import the previously export meta graph.
      saver = tf.train.import_meta_graph(meta_graph_def)
```

Please feel free to reopen if this doesn't solve the issue.

**Comment by snbuchholz** [comment]
Thanks! This information was missing from https://www.tensorflow.org/versions/r0.9/how_tos/meta_graph/index.html
