### ISSUE TITLE
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'is_fully_defined'

### ISSUE THREAD

**Issue by manakanemu** [tensorflow/tensorflow#46032]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.4.0
- Python version:3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.0
- GPU model and memory:24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Can not reshapes SparseTensor
**Describe the expected behavior**
Reshapes a SparseTensor
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import tensorflow as tf

sp = tf.SparseTensor([[1,1],[2,2]],[1.,2.],[4,4])
new_sp = tf.sparse.reshape(sp,[8,-1])
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\python\ops\sparse_ops.py", line 902, in sparse_reshape
    and sp_input.shape.is_fully_defined()):
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'is_fully_defined'

**Comment by ravikyram** [comment]
@manakanemu 

I have tried in colab with TF-GPU version 2.4 and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9262e45d524185a9efa89847f4aae52b/untitled586.ipynb).Thanks!

**Comment by manakanemu** [comment]
Sorry, I found this problem was caused by myself. I used "pickle" to load a SparseTensor, which caused the init function not be executed, so the correct SparseTensor._dense_shape_default was not obtained.

**Comment by ravikyram** [comment]
@manakanemu 

Is this still an issue? Please, close this thread if your issue was resolved. Thanks!
