### ISSUE TITLE
map_fn can't generate ragged tensor on arbitrary dimension

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#46035]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04 lts
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

map_fn can't generate ragged tensor on arbitrary dimension.

**Describe the expected behavior**

map_fn should generate ragged tensor on arbitrary dimension.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
#!/usr/bin/python3

import tensorflow as tf;

elems = tf.constant([3, 5, 0, 2]);
a=tf.map_fn(lambda x: tf.zeros((x)), elems, fn_output_signature = tf.RaggedTensorSpec(shape = (None), dtype = tf.float32, ragged_rank = 0));
print(a);
# error occurs below
b=tf.map_fn(lambda x: tf.zeros((4,x)), elems, fn_output_signature = tf.RaggedTensorSpec(shape = (4, None), dtype = tf.float32, ragged_rank = 1));
print(b);
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
i am able to reproduce this issue on[ tf 2.4 ](https://colab.research.google.com/gist/Saduf2019/b72d1339d4186a2387541c5680a8bc94/untitled489.ipynb)and nightly, please find the [gist here.](https://colab.research.google.com/gist/Saduf2019/c0a4fb375a6cc43ac46bb74f54da5fed/untitled488.ipynb)

**Comment by breadbread1984** [comment]
thx, this is the error i am talking about

**Comment by mdanatg** [comment]
This is not ovbious, but when the function returns a dense Tensor (`tf.zeros((4, x))`), the `fn_output_signature` must have `ragged_rank=0`, even in the second case.
See https://www.tensorflow.org/api_docs/python/tf/map_fn#raggedtensors_2

**Comment by breadbread1984** [comment]
I tried the following code with tensorflow 2.4.1. the shape of b is not (4,4,None) but (4,4,3). is your solution available on nightly version?

```python
#!/usr/bin/python3

import tensorflow as tf;

elems = tf.constant([3, 5, 0, 2]);
b=tf.map_fn(lambda x: tf.zeros((4,x)), elems, fn_output_signature = tf.RaggedTensorSpec(shape = (4, None), dtype = tf.float32, ragged_rank = 0));
print(b);
```

**Comment by mdanatg** [comment]
Yes, and it looks like the result contains some nonzero values so it's definitely a bug.

@edloper is there a workaround?

**Comment by edloper** [comment]
Yes, agreed that this looks like a bug.  A work-around for now is to have the function you pass to `map_fn` convert its output to a ragged tensor before returning it (and update the RaggedTensorSpec accordingly).  I.e., in your example, change the line that defines `b` to:

```
b=tf.map_fn(lambda x: tf.RaggedTensor.from_tensor(tf.zeros((4,x))), elems, fn_output_signature = tf.RaggedTensorSpec(shape = (4, None), dtype = tf.float32, ragged_rank = 1))
```

I suspect that the bug is in the RaggedTensorFromVariant op -- I will look into it after the weekend.

**Comment by mmilosav** [comment]
@edloper Should the workaround extend to higher rank outputs?  Consider rank=3 outputs:
```python
import tensorflow as tf

elems = tf.constant([3, 5, 0, 2])
b = tf.map_fn(fn=lambda x: tf.RaggedTensor.from_tensor(tf.zeros((6, 7, x))),
              elems=elems,
              fn_output_signature=tf.RaggedTensorSpec(shape=(6, 7, None), ragged_rank=1))
print('nested_row_splits:')
for split in b.nested_row_splits:
    print(split.numpy())
print('shape:', b.shape)
print('ragged_rank:', b.ragged_rank)
print('b:', b)
```
which prints out:
```
nested_row_splits:
[ 0  6 12 18 24]
[  0   7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119
 126 133 140 147 154 161 168]
shape: (4, 6, 7, 3)
ragged_rank: 2
```
The ragged last shape dimension shows 3, not None (the maximum last ragged dimension is 5).  Printing out the ragged tensor `b` (printout not pasted) has wrong shape - the last dimension is always 3 and does not vary according to `elems`.  Some elements of `b` are garbage floats.  Is the above attempt to extend to higher rank outputs incorrect, is this a bug? Cc. @jvishnuvardhan - Thanks

**Comment by edloper** [comment]
@mmilosav In this example, you'd need to use `ragged_rank=2` in the `RaggedTensorSpec` when you call `tf.map_fn` (and in the call to `RaggedTensor.from_tensor`):

```
b = tf.map_fn(fn=lambda x: tf.RaggedTensor.from_tensor(tf.zeros((6, 7, x)), ragged_rank=2),
              elems=elems,
              fn_output_signature=tf.RaggedTensorSpec(shape=(6, 7, None), ragged_rank=2))
``` 

In the general case, if a shape has ragged dimensions in axes `[a1, a2, ..., aN]`, then `ragged_rank` should be set to `max(a1, a2, ..., aN)`.  In this case, `axis=2` is the (only) ragged axis, so `ragged_rank` needs to be `2`.

**Comment by tilakrayal** [comment]
@breadbread1984,
I tried the alternative approach as [commented](https://github.com/tensorflow/tensorflow/issues/46035#issuecomment-766158574) by the developer, and was able to execute the code with the expected result. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/31b5659bb92b15dd931fd44baf7856e4/untitled451.ipynb) and let us know if the issue still persists. Thank you!
