### ISSUE TITLE
Error when build TF 1.13.2 from the source

### ISSUE THREAD

**Issue by Rivendile** [tensorflow/tensorflow#46034]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04/18.04
- TensorFlow installed from source
- TensorFlow version: 1.13.2
- Python version: 2.7
- Installed using: docker
- Bazel version: 0.19.2
- GCC/Compiler version: 4.9
- CUDA/cuDNN version: 10.0, 7
- GPU model and memory: T4, 32GB

**Describe the problem**
I tried to install TF from the source following instructions here, https://github.com/tensorflow/docs/blob/r1.13/site/en/install/source.md#build-from-source. 
However some error occurs: ERROR: /home/cluster/tensorflow/tensorflow/core/kernels/BUILD:593:1: C++ compilation of rule '//tensorflow/core/kernels:eigen_contraction_kernel' failed (Exit 1). 
Any help would be appreciated! Thanks!

**Comment by ravikyram** [comment]
@Rivendile 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source#gpu).Please, try to install in a fresh environment and see if the problem still persists.Still If you are facing  issue please share complete error log to investigate further. Thanks!

**Comment by mihaimaruseac** [comment]
Error message is incomplete.

We are not updating `v1.x` branches anymore as we no longer have environments where we can fully test them.

**Comment by bhack** [comment]
> Error message is incomplete.
> 
> We are not updating `v1.x` branches anymore as we no longer have environments where we can fully test them.

@mihaimaruseac We could add this info in the ISSUE Template and make a grooming with the bot cause we have 105 open issues only with TF 1.3 label (+ TF 1.2 TF 1.4 T F 1.5 labels) https://github.com/tensorflow/tensorflow/labels/TF%201.13.

**Comment by Rivendile** [comment]
Problem solved. I downgrade GCC to 4.8 and build it successfully. Thanks!
