### ISSUE TITLE
tensorflow 1.15.4 contrib.slim.python.slim.nets

### ISSUE THREAD

**Issue by andreixxi** [tensorflow/tensorflow#46037]
i use tensorflow 1.15.4<br>
`from tensorflow.contrib.slim.python.slim.nets import resnet_v2
ImportError: No module named contrib.slim.python.slim.nets`

**Comment by ravikyram** [comment]
@andreixxi 

I have tried in colab in TF 1.15.4 and I m not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/71b9822e56a3e621c31baedac8d190e3/untitled585.ipynb).Thanks!
