### ISSUE TITLE
Tensorflow related error when deploying shiny app on shinyapps.io

### ISSUE THREAD

**Issue by max-poltora** [tensorflow/tensorflow#46042]
I am trying to deploy shiny app, that uses reticulate and keras packages. I do not have any problem to run it locally, but real troubles appear, when I try to deploy it to shinyapps.io. My app.r file is as follows:
```
virtualenv_dir = Sys.getenv("VIRTUALENV_NAME")
python_path = Sys.getenv("PYTHON_PATH")
reticulate::virtualenv_create(envname = virtualenv_dir, python = python_path)
reticulate::virtualenv_install(virtualenv_dir, packages = c("numpy", "h5py", "scipy", "scikit-image", "pyyaml", "pillow"), ignore_installed = TRUE)
reticulate::use_virtualenv(virtualenv = virtualenv_dir)

library(shiny)
library(keras)
library(reticulate)
library(magick)
library(raster)
library(EBImage)
library(rdrop2)
library(plotly)

np <- import("numpy", convert=FALSE)
ndi <- import("scipy.ndimage", convert=FALSE)
segment <- import("skimage.segmentation", convert=FALSE)
feature <- import("skimage.feature", convert=FALSE)

model = load_model_hdf5("model_v02122020.h5")

ui <- 
tagList(
    fluidPage(
        sidebarLayout(sidebarPanel(
            fileInput("upload", "Choose a file", accept = c('image/png', 'image/jpeg')),
            actionButton('click', 'Start')
        ),
        mainPanel(
            tabsetPanel(type="tabs",
                tabPanel("Input image", plotOutput("InputImagePlot", height="100%")),
                tabPanel("Output image", plotOutput("OutputImagePlot", height="100%")),
            )
        )
        )
    )
)
server <- 
function(input, output, session) {

    observeEvent(input$click, {
## some code for image processing
})
}
shinyApp(ui = ui, server = server)
```
My .Rprofile file is as follows (credit to [this source](https://github.com/ranikay/shiny-reticulate-app/blob/master/.Rprofile)):
```
VIRTUALENV_NAME = "virt_tf"

if (Sys.info()[["user"]] == "shiny"){
  
  # Running on shinyapps.io
  Sys.setenv(PYTHON_PATH = 'python3')
  Sys.setenv(VIRTUALENV_NAME = VIRTUALENV_NAME) # Installs into default shiny virtualenvs dir
  Sys.setenv(RETICULATE_PYTHON = paste0('/home/shiny/.virtualenvs/', VIRTUALENV_NAME, '/bin/python'))
  
} else if (Sys.info()[["user"]] == "rstudio-connect"){
  
  # Running on remote server
  Sys.setenv(PYTHON_PATH = '/opt/python/3.7.6/bin/python')
  Sys.setenv(VIRTUALENV_NAME = paste0(VIRTUALENV_NAME, '/')) # include '/' => installs into rstudio-connect/apps/
  Sys.setenv(RETICULATE_PYTHON = paste0(VIRTUALENV_NAME, '/bin/python'))
  
} else {
  
  # Running locally
  options(shiny.port = 7450)
  Sys.setenv(PYTHON_PATH = 'python 3.6.12')
  Sys.setenv(VIRTUALENV_NAME = VIRTUALENV_NAME) # exclude '/' => installs into ~/.virtualenvs/
  # RETICULATE_PYTHON is not required locally, RStudio infers it based on the ~/.virtualenvs path
}
```
The deployment process seems to run completely according to R log:
```
rsconnect::deployApp()
Preparing to deploy application...Update application currently deployed at
https://name.shinyapps.io/appname/? [Y/n] y
DONE
Uploading bundle for application: 3428026...DONE
Deploying bundle: 4035381 for application: 3428026 ...
Waiting for task: 846214175
  building: Parsing manifest
  building: Building image: 4594673
  building: Installing system dependencies
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 4594673
  deploying: Starting instances
  terminating: Stopping old instances
Application successfully deployed to https://name.shinyapps.io/appname/
```
The error I get from the bottom of the log:

> Error in value[[3L]](cond) : Installation of TensorFlow not found.
> Python environments searched for 'tensorflow' package:
> You can install TensorFlow using the install_tensorflow() function.
> /home/shiny/.virtualenvs/virt_tf/bin/python3
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Execution halted

When I try to include `tensorflow` into the list of packages required to be installed into my virtualenvironment I get the following error message:

> Downloading tensorflow-2.3.1-cp35-cp35m-manylinux2010_x86_64.whl (320.4 MB)
> Collecting tensorflow
> Killed
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Error in value[[3L]](cond) : 
> Error installing package(s): 'numpy', 'h5py', 'scipy', 'scikit-image', 'pyyaml', 'pillow', 'tensorflow'
> Execution halted
> Out of memory!

As far as I understand, shinyapps.io pushes me to install tensorflow package into virtualenvironment. However, I guess, it should be in the list of available packages. But how to force using it?

**Comment by ravikyram** [comment]
@max-poltora 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose)

Can you refer this [link](https://stackoverflow.com/questions/62207717/cannot-find-tensorflow-in-r) and see if it helps you.Thanks!

**Comment by max-poltora** [comment]
@ravikyram 
I have filled issue template, when I created this issue. Or did I fill in the wrong template? Please let me know, which one shall I fill in then?
Thank you for the link. However, tensorflow, keras and my app run locally wiht no issues. I get problems, when I try to deploy my app. So it should be from the shinyapps server side, or do I misunderstend it?

**Comment by ravikyram** [comment]
@max-poltora 

Just to understand better , is this issue is related to Tensorflow?
I think issue is related to shinyapps. Please, clarify
Thanks!

**Comment by max-poltora** [comment]
@ravikyram 
The issue is related to tensorflow, when I deploy my app to shinyapps. I get the error message: 

> Error in value[3L] : Installation of TensorFlow not found

**Comment by max-poltora** [comment]
@ravikyram,
Basically, what I can observe, my app lacks tensorflow in that same environment on shinyapps.io. When I try to install it with, for instance `install_keras(method="virtualenv", envname=virtualenv_dir, tensorflow = "gpu")` or `reticulate::virtualenv_install(virtualenv_dir, packages = c("numpy", "h5py", "scipy", "scikit-image", "pyyaml", "pillow", "tensorflow"), ignore_installed = TRUE)`, it just kills the process, because tensorflow package is too heavy:

> 2020-12-30T09:34:23.855506+00:00 shinyapps[3428026]: Collecting tensorflow-gpu==2.2.0
> 2020-12-30T09:34:36.957986+00:00 shinyapps[3428026]:   Downloading tensorflow_gpu-2.2.0-cp35-cp35m-manylinux2010_x86_64.whl (516.2 MB)
> 2020-12-30T09:34:42.960610+00:00 shinyapps[system]: Out of memory!
> 2020-12-30T09:34:42.943096+00:00 shinyapps[3428026]: Error in value[[3L]](cond) : 
> 2020-12-30T09:34:42.933600+00:00 shinyapps[3428026]: Killed
> 2020-12-30T09:34:42.943098+00:00 shinyapps[3428026]:   Error installing package(s): 'tensorflow-gpu==2.2.0', 'keras', 'tensorflow-hub', 'h5py', 'pyyaml==3.12', 'requests', 'Pillow', 'scipy'
> 2020-12-30T09:34:42.943099+00:00 shinyapps[3428026]: Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> 2020-12-30T09:34:42.943123+00:00 shinyapps[3428026]: Execution halted

**Comment by ymodak** [comment]
RStudio community can be a right platform to raise this issue.
I see you have already raised this issue on [RStudio](https://community.rstudio.com/t/tensorflow-related-error-when-deploying-shiny-app-on-shinyapps-io/91966) (tagging for visibility)

**Comment by max-poltora** [comment]
@ymodak, thank you for the reply. I have indeed posted this issue on Rstudio and was able to make application run, when upgrading my plan to basic. However, now I see another error message in logs: 

> 2021-01-11T13:39:36.408265+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.408173: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/shiny/.virtualenvs/myenv/lib:/opt/R/3.6.1/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server
> 2021-01-11T13:39:36.408282+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.408229: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
> 2021-01-11T13:39:36.416118+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.416030: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1a6da190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2021-01-11T13:39:36.408540+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.408481: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> 2021-01-11T13:39:36.415464+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.415385: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2999995000 Hz
> 2021-01-11T13:39:36.408294+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.408269: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (614c4c4b9dd3): /proc/driver/nvidia/version does not exist
> 2021-01-11T13:39:36.416129+00:00 shinyapps[3428026]: 2021-01-11 13:39:36.416087: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2021-01-11T13:39:37.193196+00:00 shinyapps[3428026]: 
> 2021-01-11T13:39:37.193199+00:00 shinyapps[3428026]: Listening on http://127.0.0.1:36677
> 2021-01-11T13:40:26.655510+00:00 shinyapps[3428026]: Press Esc/Ctrl + C to abort
> 2021-01-11T13:40:26.657269+00:00 shinyapps[3428026]: https://www.dropbox.com/oauth2/authorize?client_id=mmhfsybffdom42w&redirect_uri=http%3A%2F%2Flocalhost%3A1410%2F&response_type=code&state=tPAJ0o83jt
> 2021-01-11T13:40:26.655193+00:00 shinyapps[3428026]: Waiting for authentication in browser...
> 2021-01-11T13:40:26.656945+00:00 shinyapps[3428026]: Please point your browser to the following url:

**Comment by max-poltora** [comment]
@ymodak, yes I have found the solution by upgrading my shinyapps plan up to basic. Thank you for your attention.

**Comment by ravikyram** [comment]
@max-poltora 

Please, close this thread if your issue was resolved. Thanks!

**Comment by andreazignoli** [comment]
I know I might be late for the party, but I have experienced the same issue when trying to deploy a Tf model on Shiny. As far as I understood after cross referencing is that using Tf inside a Python venv really requires a lot of memory that the Free program of Shiny does not handle. The Tf model in my case was running correctly without Python venv with Tf R package, but I understand a Python venv might be required anyway. If this is teh case, I tried Tf Lite instead of Tf and it worked out! Only thing is: R does not uses float32 (standard for Tf Lite models) so keep in mind that you need to numpy convert from float64 to float 32 and then set the tensor of the TF Lite interpreter with those values.
