### ISSUE TITLE
Using negative index slice on tf.scan accesses uninitialized memory

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#4604]
Accessing last element of array produced by scan by using array[-1] gives random results. IE
```
import tensorflow as tf
out = tf.scan(lambda p, c: p * c, tf.fill([2], 2), initializer=tf.constant(1)) 
sess = tf.Session()
print sess.run(out)
print sess.run(out[1])
print sess.run(out[-1])

```
This generates
```
[2 4]
4
181075993
```

The last number is different on reruns, `tf.__version__` is 0.10

**Comment by aselle** [comment]
I reproduced this on docker image tensorflow/tensorflow:0.10.0 
but it works fine for me on  tensorflow/tensorflow:nightly

**Comment by concretevitamin** [comment]
Closing this.  Feel free to re-open if it still is an issue at HEAD.
