### ISSUE TITLE
How to run tensorflow 2.4.0 on ARM Mac using Rosetta 2

### ISSUE THREAD

**Issue by danielplatt** [tensorflow/tensorflow#46044]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacBook Pro Apple M1 chip, macOS Big Sur version 11.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.4.0
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: I don't know what that means
- GPU model and memory: No GPU

**Describe the problem**

Python code `import tensorflow` leads to `zsh: illegal hardware instruction  python3` and the Python Console stops. I would like to enter additional commands after importing tensorflow rather than the Python Console stopping. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Install Python 3.8 using homebrew in a Rosetta 2 terminal
2. In Rosetta 2 terminal:
```
which python3
/usr/bin/python3
```
3. Create virtual environment:
`python3 -m venv /Users/daniel/TFTest/venv`

4. Activate virtual environment
`/Users/daniel/TFTest/venv/bin/activate`

5.
```
which python3
/Users/daniel/TFTest/venv/bin/python3
```

6. `pip install --upgrade pip`

7. `pip3 install --upgrade tensorflow`

8.
```
python3
import tensorflow
```

gives output:

`zsh: illegal hardware instruction  python3`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I am aware of this repository: https://github.com/apple/tensorflow_macos . But I would like to use tensorflow 2.4.0 rather than the experimental version from the Apple repository.

**Comment by isamilefchik** [comment]
Not sure if this is obvious to others but it wasn't completely obvious to me: if you install Bazel (the regular x86-64 version for mac) and use it through Rosetta 2 to compile Tensorflow from source, then it will compile without the (unsupported by Rosetta 2) AVX instruction set. I'm currently able to run both Tensorflow 1.15.0 and Tensorflow 2.5.0 using this method. Hope this is of any help :)

**Comment by danielplatt** [comment]
@isamilefchik  Thank you, your reply was very helpful and not obvious for me. Following the instruction at https://www.tensorflow.org/install/source#macos_1 together with the solution from the issue at https://github.com/tensorflow/tensorflow/issues/45434 allowed me to install tensorflow.

**Comment by isamilefchik** [comment]
@danielplatt Happy to hear it!

**Comment by mihaimaruseac** [comment]
We currently cannot support Mac ARM. There is less than one developer than can focus on build issues on all 3 operating systems.

Hence, support has to come from the the community. There is SIG Build that focuses on build related issues on several other platforms, leaving us to only focus on the pip packages we officially bless.

**Comment by easadler** [comment]
I want to confirm what @danielplatt  and @isamilefchik said about getting Tensorflow to work on rosetta. I did the following steps:

1. Build from source while running a terminal using rosetta
2. Updated the bash script that makes the `.whl` file [#45434](https://github.com/tensorflow/tensorflow/issues/45434)
3. I am pretty sure that I needed to rename the wheel to say `10_16` instead of `11_1`, but hard to say if that was necessary.

This let me run the entire local [keras tfx tutorial](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb), which was my goal. I also was able to use tensorflow probability.

**Comment by mihaimaruseac** [comment]
The sed issue is resolved by #46147. We will likely cherrypick this one on the 2.4 branch before doing a patch release.

**Comment by ben-xD** [comment]
Could someone say how long it takes to build TensorFlow from source for M1 mac? I tried it, and it took a significant time.
![Screenshot 2021-01-16 at 23 37 53](https://user-images.githubusercontent.com/24711048/104837897-96f39900-58af-11eb-802f-d6783b8b0f46.png)

As you can see, the screenshot (not even finished btw) was taking 1.8575 hours for just `argmax_op.cc`

**Comment by isamilefchik** [comment]
@ben-xD I think you're nearly finished

**Comment by danielplatt** [comment]
@ben-xD All I can say is that is was done when I came back to the computer after 5 hours.

**Comment by mihaimaruseac** [comment]
Unfortunately TF takes a long to compile on all operating systems. There are a lot of C++ templates to expand and a lot of code to optimize.

**Comment by paelikan** [comment]
@easadler How did you get tf-probability running, did you also install from source?
More generally, would installing from source allow Numpy, Panada, Scipy, etc. to be used on Rosetta 2?

**Comment by nguyenhoan1988** [comment]
@ben-xD : mine took almost 3 hours to finish, on a M1 Mac

```
INFO: Elapsed time: 9644.520s, Critical Path: 450.54s
INFO: 19332 processes: 1088 internal, 18244 local.
INFO: Build completed successfully, 19332 total actions
```

**Comment by nguyenhoan1988** [comment]
> I want to confirm what @danielplatt and @isamilefchik said about getting Tensorflow to work on rosetta. I did the following steps:
> 
> 1. Build from source while running a terminal using rosetta
> 2. Updated the bash script that makes the `.whl` file [#45434](https://github.com/tensorflow/tensorflow/issues/45434)
> 3. I am pretty sure that I needed to rename the wheel to say `10_16` instead of `11_1`, but hard to say if that was necessary.
> 
> This let me run the entire local [keras tfx tutorial](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/components_keras.ipynb), which was my goal. I also was able to use tensorflow probability.

I can also install tensorflow that runs on Rosetta successfully following your steps, @easadler.
Especially, I have to rename the `.whl` file from `11_0` to `10_16` to `pip` it.

Thank you for sharing the guide 👍

**Comment by Eieyron** [comment]
> Not sure if this is obvious to others but it wasn't completely obvious to me: if you install Bazel (the regular x86-64 version for mac) and use it through Rosetta 2 to compile Tensorflow from source, then it will compile without the (unsupported by Rosetta 2) AVX instruction set. I'm currently able to run both Tensorflow 1.15.0 and Tensorflow 2.5.0 using this method. Hope this is of any help :)

Hello, is there any way that you can give me a copy of your Tensorflow 1.15 whl? It crashes on me when I'm trying to build it from source.

**Comment by isamilefchik** [comment]
@Eieyron Sure. Here's a link to both the wheels I built for 1.15.0 and 2.5.0:

https://drive.google.com/drive/folders/11cACNiynhi45br1aW3ub5oQ6SrDEQx4p?usp=sharing

**Comment by Matt52** [comment]
These steps worked for me:

```
# 1.) I installed some brew packages before even installing python (notice that I am using Rosetta brew and not my default arm brew)
/usr/local/bin/brew install zlib
/usr/local/bin/brew install bzip2
/usr/local/bin/brew install sqlite
/usr/local/bin/brew install libiconv
/usr/local/bin/brew install libzip
/usr/local/bin/brew install xz

# 2.) install bazelisk and gsed
/usr/local/bin/brew install bazelisk
/usr/local/bin/brew install gnu-sed

# 3.) switch to your Rosetta python env (I use python 3.8.5 installed with rosetta-brew's pyenv)

# 4.) clone tf repo
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow

# 5.) change sed to gsed here in ./bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh (https://github.com/tensorflow/tensorflow/issues/45434#issuecomment-739635923)

# 6.) run configure and say No to gpu options
./configure

# 7.) build (this runs between 2 and 3 hours; 100% CPU all the time)
bazel build //tensorflow/tools/pip_package:build_pip_package

# 8.) create whl
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# 9.) install tf via pip
pip install /tmp/tensorflow_pkg/tensorflow-2.5.0-cp38-cp38-macosx_11_0_x86_64.whl

```

Voila!

**Comment by fonnesbeck** [comment]
After following the above, I get:

    ERROR: tensorflow-2.5.0-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

on install. I am installing into an Anaconda env, so it should be Intel, so this error confuses me.

**Comment by isamilefchik** [comment]
@fonnesbeck I couldn't figure out how to change the name of the wheel to make it work besides just renaming it to be version/machine agnostic. For example, I renamed my tensorflow 2.5.0 wheel to `tensorflow-2.5.0-py3-none-any.whl` and pip accepted it.

**Comment by d-dawg78** [comment]
You can find detailed instructions regarding TF installation on Mac M1 using Rosetta here:

https://drive.google.com/drive/folders/1-d6aZNrlsJLFciJuVpo1-dXWptEMo22h?usp=sharing

Note that there is also a .whl file generated for TF 2.4.1 and Python 3.8.5. Enjoy!

(and thanks to the others that commented above me for outlining the solution!).

**Comment by danielplatt** [comment]
@d-dawg78 I get an "Access Denied" error message when clicking that link. Have you selected the right sharing settings?

**Comment by d-dawg78** [comment]
@danielplatt Edited, does the link work now?

**Comment by ugoscaiella** [comment]
> @Eieyron Sure. Here's a link to both the wheels I built for 1.15.0, 2.4.1, and 2.5.0:
> 
> https://drive.google.com/drive/folders/11cACNiynhi45br1aW3ub5oQ6SrDEQx4p?usp=sharing

@isamilefchik which version of python did you use for these wheels?

**Comment by isamilefchik** [comment]
@ugoscaiella 3.7

**Comment by kode54** [comment]
Why is this even an issue any more, isn't there a native version available already? It simply requires Monterey to function.

**Comment by mathieuboudreau** [comment]
> Why is this even an issue any more, isn't there a native version available already? It simply requires Monterey to function.

Where is this native version for Monterey? Any links/documentation you can share, I've searched but can't find it?

**Comment by kode54** [comment]
This is available: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by mathieuboudreau** [comment]
Thanks, I knew about that hack, but it's not what I thought you meant by a native version being available.

**Comment by kode54** [comment]
Wait, so that thing Apple is describing there still requires Rosetta'd Intel TensorFlow?

**Comment by wookayin** [comment]
As of 2.7.0 TensorFlow prebuilt binary still does not run on M1 mac. The x86_64 binary under rosetta 2 will crash due to illegal instructions.

**Comment by kode54** [comment]
This is possibly because it assumes that since all recent Intel Macs have AVX or AVX2, it's safe to use that instruction set without actually asking the CPU if it supports it. Rosetta 2 does not, and indicates as such with its cpuid results.

**Comment by talhakabakus** [comment]
> @Eieyron Sure. Here's a link to both the wheels I built for 1.15.0, 2.4.1, and 2.5.0:
> 
> https://drive.google.com/drive/folders/11cACNiynhi45br1aW3ub5oQ6SrDEQx4p?usp=sharing

Many thanks for sharing the wheels. I got the following error when I try to install the `2.5.0` version on _macOS Monterey_ with an _M1 Pro_ SoC (sharing only the last part of error stack trace as it's too long to be pasted here):
```
ERROR: Could not find a version that satisfies the requirement h5py~=3.1.0 (from tensorflow) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.3.0, 3.4.0, 3.5.0, 3.6.0)
ERROR: No matching distribution found for h5py~=3.1.0
```

**Comment by justinjdickow** [comment]
Leaving this here as it's the official docs for compilation... https://www.tensorflow.org/install/source

**Comment by jyi4** [comment]
Is there a way to install Tensorflow 2.7.0 using Rosetta 2? On an M1 Mac and specifically need this version

**Comment by DelightRun** [comment]
> @Eieyron Sure. Here's a link to both the wheels I built for 1.15.0, 2.4.1, and 2.5.0:
> 
> https://drive.google.com/drive/folders/11cACNiynhi45br1aW3ub5oQ6SrDEQx4p?usp=sharing

Thanks a lots. 
BTW, I also tried to compile 1.15.5 on M1, and faced a lot of errors and deps problems,  i.e. bazel, numpy, etc.
So. I'd like to know how do you compile 1.15 on M1 and solve the related problems, could u please share some HOWTO instructions?

**Comment by thedataninja** [comment]
This is error i get
 
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 11 2022, 21:52:37) 

Does anyone have binaries for 3.8.15
