### ISSUE TITLE
No matching distribution found during installation suing dockerfile

### ISSUE THREAD

**Issue by abby-93** [tensorflow/tensorflow#46069]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Ubuntu 18.04 (Docker)
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.12
- Python version:2.7
- Installed using virtualenv? pip? conda?: virtualenv

**Describe the problem**
Hi, i am building this data analytics project in which i need to use tensorflow using dockerfile running on raspberry pi 4 python 2.7. I did not encounter this issue when i was running the dockerfile in amd64 architecture however in raspberry pi 4 python 2.7 it gives out error no matching distribution found for this platform. P
![tensorflow2](https://user-images.githubusercontent.com/76122954/103345254-d9556180-4acb-11eb-90d7-09a6229fe3be.png)
lease do help me figure this out. Thank you in advance. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

RUN pip install --no-cache-dir pandas sklearn keras tensorflow \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@abby-93 
We see that you are using 1.x and there is no support for it, please upgrade to 2.x and let us know, please refer to these [requirements](https://github.com/tensorflow/tensorflow/issues/42367#issuecomment-674531556) and let us know.

**Comment by abby-93** [comment]
HI, i am still new to this but I have tried the above mentioned instructions and i am still getting the error. Is it because i am trying to install it in raspberry pi?

**Comment by Saduf2019** [comment]
@abby-93 
Please confirm if you are using 2.x version.
