### ISSUE TITLE
Error during converting the OpenNMT-tf model to TensorFlow Lite

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#46061]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.4.0 (have tested on tf-nightly as well)

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
https://colab.research.google.com/gist/sayakpaul/b3a06119884e0b0bf9cb7f509e4b341e/scratchpad.ipynb
```

**The output from the converter invocation**

```
Exception: <unknown>:0: error: loc("transformer_base_1/while@__inference__run_14521"): 'tf.While' op body result type tensor<?x8x1x64xf32> is incompatible with result type tensor<?x8x0x64xf32> at index 6


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    214       return model_str
    215     except Exception as e:
--> 216       raise ConverterError(str(e))
    217 
    218   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("transformer_base_1/while@__inference__run_14521"): 'tf.While' op body result type tensor<?x8x1x64xf32> is incompatible with result type tensor<?x8x0x64xf32> at index 6
```

**Also, please include a link to the saved model or GraphDef**

```
https://s3.amazonaws.com/opennmt-models/averaged-ende-export500k-v2.tar.gz
```

[OpenNMT](https://opennmt.net/) is a pretty well-known open-source project in the area of Neural Machine Translation. It's used across industries and many academic institutions. 

I was trying to convert their latest SavedModel to TensorFlow Lite but currently, it's failing. From the initial error logs, it looks like it's because of the pesky `tf.While` op.  When I switched to `tf-nightly` it gets changed to the following - 

```
ConverterError: <unknown>:0: error: loc(callsite(callsite("transformer_base_1/TensorArrayV2@__inference__run_14521" at "StatefulPartitionedCall@__inference_signature_wrapper_15063") at "StatefulPartitionedCall_4")): requires element_shape to be 1D tensor during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall_4"): called from
<unknown>:0: error: loc(callsite(callsite("transformer_base_1/TensorArrayV2@__inference__run_14521" at "StatefulPartitionedCall@__inference_signature_wrapper_15063") at "StatefulPartitionedCall_4")): failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall_4"): called from
```

I have tried with the flex ops too but that does not help. I was wondering if the TensorFlow Lite team could look into this and share some suggestions to fix this much like https://github.com/TensorSpeech/TensorflowTTS/pull/84. 

Please note that OpenNMT folks have tried to convert TensorFlow Lite before but they have been unsuccessful so far as per  https://github.com/OpenNMT/OpenNMT-tf/issues/490. 

Cc: @abattery

**Comment by abattery** [comment]
The conversion failure from the nightly version happened at the TensorList transformation. @haozha111 could you take a look at this?

**Comment by haozha111** [comment]
> The conversion failure from the nightly version happened at the TensorList transformation. @haozha111 could you take a look at this?

yes, i can repro the same error with tf-nightly. Taking a look and will post anything i found here. Thanks!

**Comment by haozha111** [comment]
I took a look at your model, and I think the reason for tensorlist to fail to convert is that, it lacks an element_shape when the model construct the TensorArray. Could you check where in the code the model calls 'tf.TensorArray' and try to pass a element_shape there?

**Comment by sayakpaul** [comment]
Thanks for looking into it @haozha111. I don't think passing in an `element_shape` would be possible for this pre-trained model.

**Comment by mohantym** [comment]
Hi @sayakpaul !
We are checking to see whether you still need help in this issue . 
I was able to get lite model by using  below flags 2.11 ( before model conversion )
```
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
#converter.experimental_new_quantizer = False
#converter.experimental_enable_resource_variables = True
converter._experimental_lower_tensor_list_ops = False
```

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/58575444e929138ae368035295d43676/scratchpad.ipynb#scrollTo=XX3MCl_uRHAV) for reference.

Thank you!
