### ISSUE TITLE
Error when build plugin

### ISSUE THREAD

**Issue by Rivendile** [tensorflow/tensorflow#46068]
When I try to compile TF with a plugin, I run the following commands:
c++ -O3 -rdynamic -std=c++11 -I/usr/local/lib/python2.7/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -Wall -c plugin.cc -o plugin.o
c++ -shared -fPIC -Wl,-soname,libplugin.so.1 -L/usr/local/lib/python2.7/dist-packages/tensorflow -ltensorflow_framework -o libplugin.so plugin.o

However, when I try to tensorflow.load_library('libplugin.so'), error occurs: 
tensorflow.python.framework.errors_impl.NotFoundError: ./libplugin.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

I use the following command: ldd libconfig.so, but no libtensorflow_framework.so is included:
	linux-vdso.so.1 (0x00007ffceaa5e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd2cc4f2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd2cc2da000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd2cbee9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd2cbb4b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd2ccaa7000)
I find libtensorflow_framework.so in /usr/local/lib/python2.7/dist-packages/tensorflow.
So what's wrong with the compilation process?

Any help would be appreciated! Thanks

The system information: ubuntu18.04, cuda10.0, cudnn7, tf1.13.2, gcc 4.8.5

**Comment by ravikyram** [comment]
@Rivendile 

Can you refer the similar issues [link1](https://github.com/sadeepj/crfasrnn_keras/issues/53), [link2](https://stackoverflow.com/questions/48189818/undefined-symbol-ztin10tensorflow8opkernele) and see if it helps you.
If the problem still persists please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by Rivendile** [comment]
I added --no-as-needed in the compilation command and solved this problem. Thanks!
