### ISSUE TITLE
installing Keras package with tensorflow 2.3.1

### ISSUE THREAD

**Issue by Moaaz421** [tensorflow/tensorflow#46072]
I am a beginner in this, I want to make OpenCV and TensorFlow project and I have some issues

I downloaded python 3.7.6 with pip 19.2.3

after that, I used CMD to download Tensorflow 2.3.1 and I made the path in a python project  where I am coding 
_C:\Users\Desktop\PycharmProjects\SudokuSolver\venv\Lib\site-packages\tensorflow>_**pip install tensorflow==2.3.1**

now when I am importing the libraries:

import TensorFlow
from TensorFlow.Keras.models import load_model

That gives me an error
**"ModuleNotFoundError: No module named 'tensorflow.keras'"**

So what should I do and where is the wrong how to fix it?
Many thanks.

**Comment by alanpurple** [comment]
go to stackoverflow, tensorflow github issue is not for teaching

**Comment by Saduf2019** [comment]
@Moaaz421 
Please use this and let us know if you face any issues:

```import tensorflow as tf
from tensorflow.keras.models import load_model
```

**Comment by Moaaz421** [comment]
Thanks @Saduf2019

**Comment by mihaimaruseac** [comment]
Does this mean this is solved?

**Comment by Saduf2019** [comment]
@Moaaz421
Please move the issue to closed status as it is resolved.
