### ISSUE TITLE
Make `TextVectorization` support pickling

### ISSUE THREAD

**Issue by WeichenXu123** [tensorflow/tensorflow#46070]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version Tensorflow 2.2:
- Are you willing to contribute it No:

**Describe the feature and the current behavior/state.**

Make `TextVectorization` support pickling, currently it does not support pickling:
```
import cloudpickle
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
ptf = cloudpickle.dumps(TextVectorization())
```
Get error like `Cannot convert a Tensor of dtype resource to a NumPy array.`

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Support pickling will make it work with some distributed framework such as `Horovod`. Such framework usually require to pickle the user defined training function to remote and executing. So pickling is required.

**Any Other info.**

N/A

**Comment by gowthamkpr** [comment]
As mentioned [here](https://github.com/keras-team/keras/issues/16503#issuecomment-1135124533), pickling isn't natively supported in keras as it is generally [not secure](https://docs.python.org/3/library/pickle.html). Therefore I don't think this is actionable on Keras side, and overriding methods for tf.keras.layers.serialize is necessary. Thanks!
