### ISSUE TITLE
benchmark_model build failed

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#46079]
**System information**
- OS Platform and Distribution ubuntu 18.04
- TensorFlow installed from (source or binary): git hub master branch 
- TensorFlow version: master in github, tried also v2.3.0 v2.2.0 
- Python version: 2
- Installed using virtualenv? pip? conda?:NA 
- Bazel version (if compiling from source): Bazelisk version: v1.7.4 Build label: 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
Build benchmark tool according to README.md  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md failed :

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel  build -c opt   --config=android_arm64   tensorflow/lite/tools/benchmark:benchmark_model  --verbose_failures

**Any other info / logs**
Repository rule git_repository defined at:
  /home/keith/.cache/bazel/_bazel_keith/71ff04d0920d083c690fb304f211064a/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
ERROR: /home/keith/.cache/bazel/_bazel_keith/71ff04d0920d083c690fb304f211064a/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' **does not contain a toolchain for cpu 'arm64-v8a'**
ERROR: Analysis of target '//tensorflow/lite/tools/benchmark:benchmark_model' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 0.175s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by multiverse-tf** [comment]
> **System information**
> 
> * OS Platform and Distribution ubuntu 18.04
> * TensorFlow installed from (source or binary): git hub master branch
> * TensorFlow version: master in github, tried also v2.3.0 v2.2.0
> * Python version: 2
> * Installed using virtualenv? pip? conda?:NA
> * Bazel version (if compiling from source): Bazelisk version: v1.7.4 Build label: 3.1.0
> * GCC/Compiler version (if compiling from source): 7.5.0
> * CUDA/cuDNN version: NA
> * GPU model and memory: NA
> 
> **Describe the problem**
> Build benchmark tool according to README.md https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md failed :
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> bazel build -c opt --config=android_arm64 tensorflow/lite/tools/benchmark:benchmark_model --verbose_failures
> 
> **Any other info / logs**
> Repository rule git_repository defined at:
> /home/keith/.cache/bazel/_bazel_keith/71ff04d0920d083c690fb304f211064a/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in
> ERROR: /home/keith/.cache/bazel/_bazel_keith/71ff04d0920d083c690fb304f211064a/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' **does not contain a toolchain for cpu 'arm64-v8a'**

It looks like your overall building environment isn't set properly. Please follow https://www.tensorflow.org/lite/guide/build_android for details.

Or you could use pre-built binaries mentioned in https://www.tensorflow.org/lite/performance/measurement

> ERROR: Analysis of target '//tensorflow/lite/tools/benchmark:benchmark_model' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
> INFO: Elapsed time: 0.175s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by ek9852** [comment]
I was using the prebuilt benchmark binary. Thnaks.
But the problem of building the benchmark tool still exist.
And when I tried to build using android_arm instead of android_arm64,  the toolchain can be found and download.  Currently we have a problem in "does not contain a toolchain for cpu 'arm64-v8a'"   which might be related to broken url or link in the bazel config.

**Comment by multiverse-tf** [comment]
> I was using the prebuilt benchmark binary. Thnaks.
> But the problem of building the benchmark tool still exist.
> And when I tried to build using android_arm instead of android_arm64, the toolchain can be found and download. Currently we have a problem in "does not contain a toolchain for cpu 'arm64-v8a'" which might be related to broken url or link in the bazel config.

@ek9852, this issue looks quite stale now, and I'm closing this issue. If this issue still happens to you, feel free to re-open it. Thx!
