### ISSUE TITLE
Are there any excellent github projects on action recognition implemented by TF2?

### ISSUE THREAD

**Issue by August0424** [tensorflow/tensorflow#46074]
I have been searching for official or non-official awesome code projects of action recognition written by TF2 for a long time, but unfortunately fail. I'd like to integrate video classification with other TF2 elements more conviniently. The most majority of video-relevant resources are under the community of Pytorch, though only a few projects were done by TF1, which seem fairly passe and only attract very few stars. Since the TF 2.X version has been released for over 2 years, why does its current ecosystem yet appear to be frustrated? Does anybody else cope with similar questions?

**Comment by ymodak** [comment]
Did you see [action recognition with tf hub using i3d](https://www.tensorflow.org/hub/tutorials/action_recognition_with_tf_hub) tutorial?

**Comment by August0424** [comment]
> 
> 
> Did you see [action recognition with tf hub using i3d](https://www.tensorflow.org/hub/tutorials/action_recognition_with_tf_hub) tutorial?

Thanks. Looking forward to more elaborate official tutorials and demos by TF2
