### ISSUE TITLE
dtype argument for foldl/foldr

### ISSUE THREAD

**Issue by hhexiy** [tensorflow/tensorflow#4607]
Why doesn't foldl/foldr have a dtype argument as in map_fn, so that the output dtype can be different from the input dtype?

Use case: 
input is a list of indices (int32),  output is sum of embeddings of the indices (float32).

Thanks!

**Comment by tatatodd** [comment]
@hhexiy I'm not positive, but I believe that you can call `foldl` and `foldr` with an appropriate `initializer`, and the output type and shape can be anything that you want.

**Comment by aselle** [comment]
Automatically closing due to lack of recent response. Please reopen when additional information becomes available. Thanks!
