### ISSUE TITLE
Is there have API to automatically calculate #flops (e.g. like flop_counter in pytorch) in tensorflow2?

### ISSUE THREAD

**Issue by v3551G** [tensorflow/tensorflow#46081]
This template is for miscellaneous issues not covered by the other issue categories.
***
Environment: python3.6+tensorflow2.1, 
Question:  Is there have API to automatically calculate #flops (e.g.  flop_counter) in tensorflow2?
Note: in Pytorch, this could be easily realized by calling API, e.g. thop.profile(),  flop_counter， etc.
***

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by Saduf2019** [comment]
@v3551G 
Could you please explain the issue in brief.

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
