### ISSUE TITLE
ESP32-EYE person_detection example will not build

### ISSUE THREAD

**Issue by felixcollins** [tensorflow/tensorflow#46083]
@tensorflow/micro

Ubuntu 20.04.1 LTS
GNU Make 4.2.1
ESP IDF v4.2 checked out tag and ran install.sh and source export.sh
Cloned esp32-camera into idf components

I tried several different TF commits. I ran git clean -f -x -d between TF versions.

**TF master at 49524d68892d13265ec33b0e1cf7422fd71e316c**
Making the ESP project works but running "idf.py build" gives:
```
CMake Error at /home/felix/esp-idf/tools/cmake/component.cmake:468 (add_library):
  Cannot find source file:

    /home/felix/source/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/main/tensorflow/lite/micro/examples/person_detection_experimental/detection_responder.cc
```
I edited the file tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/main/CMakeLists.txt   and added  "../components/tfmicro/"  to the front of all the paths.

I can now run idf.py menuconfig to set (necessary) support for array rtc_gpio_desc.  
Now I run "idf.py build" and get:

```
 #error "No camera module configured, please configure in menuconfig"
```
The camera module selection is not showing in the menuconfig system when running tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/idf.py menuconfig. (should I run it from somewhere else?) 

I manually added "#define CONFIG_CAMERA_MODEL_ESP_EYE 1" in /tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/components/tfmicro/tensorflow/lite/micro/examples/person_detection/esp/app_camera_esp.h. 

I then run idf.py build again.  This time I get a link error:
```
/home/felix/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(main_functions.cc.obj): in function `loop':
/home/felix/source/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/build/../components/tfmicro/tensorflow/lite/micro/examples/person_detection/main_functions.cc:101: undefined reference to `GetImage(tflite::ErrorReporter*, int, int, int, signed char*)'
```

In "tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/components/tfmicro/tensorflow/lite/micro/examples/person_detection/esp/image_provider.cc"  Change the definitions of 
```
TfLiteStatus PerformCapture(tflite::ErrorReporter* error_reporter, int8_t* image_data) 
```
and 
```
TfLiteStatus GetImage(tflite::ErrorReporter* error_reporter, int image_width, int image_height, int channels, int8_t* image_data) 
```
The image_data pointer was wrongly typed as uint8_t*, changing to int8_t* fixes the undefined reference issue and the example now builds and runs! Hurray!  That was not easy.

**TF v2.4.0**
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_int8_esp_project
```
tensorflow/lite/micro/tools/make/Makefile:418: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:418: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:378: tensorflow/lite/micro/tools/make/targets/esp_makefile.inc: No such file or directory
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/targets/esp_makefile.inc'.  Stop.
```
I renamed esp32_makefile.inc to esp_makefile.inc and now generation works.

cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/

idf.py build fails with....
```
CMake Error at /home/felix/esp-idf/tools/cmake/component.cmake:468 (add_library):
  Cannot find source file:

    /home/felix/source/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/main/tensorflow/lite/micro/examples/person_detection_experimental/detection_responder.cc
```
Edit the file tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/main/CMakeLists.txt   add ../components/tfmicro/  to the front of all the paths
I can now run idf.py menuconfig to set (necessary) support for array rtc_gpio_desc.  
idf.py build now results in
```
fatal_exception  esp-idf/app_trace/libapp_trace.a  -lgcov  esp-idf/app_trace/libapp_trace.a  -lgcov  -lc  -lm && :
/home/felix/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/esp32/libesp32.a(cpu_start.c.obj):(.literal.main_task+0x18): undefined reference to `app_main'
```

**TF v2.3.0**
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_int8_esp_project
cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/
idf.py build fails with....
```
CMake Error at /home/felix/esp-idf/tools/cmake/component.cmake:468 (add_library):
  Cannot find source file:

    /home/felix/source/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection_int8/esp-idf/main/tensorflow/lite/micro/examples/person_detection_experimental/detection_responder.cc
``` 

Can anyone point to a combination of dependencies and TF that this example will actually build and run for esp32? I've managed to run the hello world but I'd like a more sophisticated example to work from.

**Comment by vikramdattu** [comment]
Hi @felixcollins this is fixed bug. tag v2.4.0 doesn't contain the fix, hence the error.

Please cherry pick following commit: https://github.com/tensorflow/tensorflow/commit/a4373953b95a298913318a9722b5d8347f8cf1e5 or switch to master.

**Comment by felixcollins** [comment]
@vikramdattu  Did you read my description?  For TF 2.4 I said _"I renamed esp32_makefile.inc to esp_makefile.inc and now generation works."_   After that it fails with a link error : "undefined reference to `app_main'".   I'll try again with Master and report back, but last time I tried it had similar issues. I changed to trying to get a tag to work so at least it was a stable point to work from.

**Comment by felixcollins** [comment]
@vikramdattu I updated the issue description with my experiences with master branch.

**Comment by felixcollins** [comment]
@vikramdattu  Yay! I got it working.  I just updated the description again. I managed to get it to build and run but as you can see there are a few issues with the project generation system and a couple of small mistakes in the image_provider.cc file for esp.

**Comment by vikramdattu** [comment]
@felixcollins can you please raise an PR for the fix so it can be merged?

**Comment by felixcollins** [comment]
@vikramdattu Sorry, I've been taken off this work now and do not have a fork set up to submit a PR from. The only changes I could submit would be the fix of the type the image data pointer for PerformCapture and GetImage in esp/image_provider.cc. This is simply removing the two 'u' characters from the front of the type. The rest of the build system issues I did not fix, I just hacked around them.

**Comment by SunBeenMoon** [comment]
Hello @felixcollins 
I wonder how you fix this problem. 

In #47063,

```
msb@msb-VirtualBox:/usr/my/tensorflow$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: *** No rule to make target 'generate_person_detection_esp_project'.  Stop.
```

Can you give me any advice or comments?

It's not working the beginning of the project.

**Comment by felixcollins** [comment]
Sorry @SunBeenMoon  I spent ages hacking around getting a build to work. I recommend you come back in a few years when they have things stabilised. The TFLite Micro seems to be very bleeding edge at the moment.

**Comment by Yifeng-Wang** [comment]
> Hello @felixcollins
> I wonder how you fix this problem.
> 
> In #47063,
> 
> ```
> msb@msb-VirtualBox:/usr/my/tensorflow$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project
> tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
> tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
> make: *** No rule to make target 'generate_person_detection_esp_project'.  Stop.
> ```
> 
> Can you give me any advice or comments?
> 
> It's not working the beginning of the project.

Instead of generating 'person detection’, I tried generate_person_detection_int8_esp_project and had the project folder generated in \tools\make\gen path, however the main folder was empty and i manually moved the files to the project folder and modified the CMakeLists.txt

**Comment by Yifeng-Wang** [comment]
I ran the person detection model in the example on my ESP-EYE but the performance wasn't as good as I expected, I wondered if it was because the camera needed some time to focus..., or it's just because of something else?

**Comment by vikramdattu** [comment]
Hi @yifeif what's the time it is taking per inference for you?

Last time I checked it is taking 700ms with greyscale model and about 1450ms (~1.5sec) for int8 model.

**Comment by Yifeng-Wang** [comment]
Hi@ vikramdattu, I simply used the stopwatch on my smartphone and I would like to say that's about 2secs/inference (that's longer than yours hh). In fact I am following an O'Relly's book called "TinyML" and this example belongs to Chap 9 & 10. The book mentioned that since the person detection model is much larger, it would take longer to run inference, so I think that 2sec delay is acceptable. Plus, I believe on the Sparkfun boards the time would take even longer:  _'When the program is running the blue LED will toggle on and off, once for each inference. Because the vision model we are using for person detection is relatively
large, it takes a long time to run inference—around 6 seconds in total.'_

**Comment by mohantym** [comment]
Hi @felixcollins !

Could you give it a try the documentation on person detection from [tflite-micro ](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection)repo with CMake 3.16 or higher.

Thank you!
