### ISSUE TITLE
dlerror: cusparse64_11.dll not found. Cannot detetct GPU.

### ISSUE THREAD

**Issue by ShrinidhiSS** [tensorflow/tensorflow#46086]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 64bit
- TensorFlow version: tensorflow-gpu=2.4.0
- Python version: 3.8.5
- Installed using pip 
- CUDA/cuDNN version: CUDA 11.1 | cuDNN v8.0.4 for CUDA 11.1
- GPU model and memory: NVIDIA GeForce GTX 1050

**I try to use NVIDIA GeForce GTX 1050 by installing all the ablove mnetioned specs. Cannot find the cusparse64_11.dll. The GPU is not being detected for running deep learning models. 

Could not load dynamic library 'cusparse64_11.dll'; **dlerror: cusparse64_11.dll not found**

Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices... **

![image](https://user-images.githubusercontent.com/48597846/103396793-2c2a2a00-4b5b-11eb-9499-8b66759fba37.png)

**Comment by ShrinidhiSS** [comment]
While running the following commands, i am unable to detect my GPU.
`import tensorflow as tf
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print("Num GPUs Available: ", len(physical_devices))
tf.config.experimental.set_memory_growth(physical_devices[0],True)`

Error

> Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found

> Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

**Comment by ravikyram** [comment]
@ShrinidhiSS 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source_windows#gpu).Please, create a fresh environment and check with this configuration and let us know if the issue still persists.Thanks!

**Comment by ShrinidhiSS** [comment]
But I am not able to download CUDA 11.0 from https://developer.nvidia.com/cuda-11.0-update1-download-archive
There is some problem downloading.
