### ISSUE TITLE
quant transpose convolution layer is not supported in nnapi acceleration

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#46098]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  Not related
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
  gtihub master branch, but this problem exist on v2.3.0 v2.2.0 etc.

**Describe the current behavior**
Quant transpose convolution layer not supported in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc#L2228
The layer version of INT8 transpose convolution layer had a version of 2 which failed the above version checking. See below:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/versioning/op_version.cc#L261

i.e. All deep learning model (esp. segmentation) using quant transpose convolution will not get nnapi acceleration on  all Android phone when they are using tensorflow lite to do the inferencing instead of Qualcomm SNPE DL engine to do the inference.

Related to https://github.com/tensorflow/tensorflow/issues/46084

**Comment by amahendrakar** [comment]
@ek9852,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here.

Also, please check if you are facing the same issue with TF v2.4 and TF-nightly as well? Thanks!

**Comment by ek9852** [comment]
I already mentioned  and point out the code related to the problem. And I already dig out the problem with gdb. Please read my text/log.
And the same problem  persist with master branch with github as I already mentioned.

**Comment by ek9852** [comment]
PR: https://github.com/tensorflow/tensorflow/pull/46183

**Comment by miaowang14** [comment]
The PR looks good to me. Thanks for the fix.

**Comment by ek9852** [comment]
Together with this patch https://github.com/tensorflow/tensorflow/commit/915c0b2bbc776cff475fac149f2e7ca9a350a715
fixes the problem.
