### ISSUE TITLE
cuda_driver.cc:175] Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: out of memory

### ISSUE THREAD

**Issue by omerbrandis** [tensorflow/tensorflow#46094]
hello,

I'm trying to run inference on a tensorrt converted graph (tf-trt) and received the error in the title.
I've followed instructions for "TF-TRT 2.0 Workflow With A SavedModel" at https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html.
but i'm afraid i have not been able to reach the part of the code the performs the inference, I get the OOM error a after loading the saved model , during preparation of the input data. 

I'm running tensorflow 2.0.0 (eager execution). on ubuntu 16.04, cuda 10.0, geforce gtx 1050 ( 4gb ram )

here is my conversion code 
from tensorflow.python.compiler.tensorrt import trt_convert as trt
ConvParams = trt.DEFAULT_TRT_CONVERSION_PARAMS
ConvParams = ConvParams._replace(max_workspace_size_bytes=1*1024*1024*1024)
ConvParams = ConvParams._replace(precision_mode="FP32")
ConvParams = ConvParams._replace(max_batch_size=1)
converter = trt.TrtGraphConverterV2(input_saved_model_dir=args.InputToConvert, conversion_params=ConvParams)

TensorRT_graph = converter.convert()

print('convert completed, building')
def my_input_fn():
  import numpy as np
  Inp1 = np.random.normal(size=(1,250, 250, 3)).astype(np.uint8)
  yield [Inp1]
converter.build(input_fn=my_input_fn)

print('build completed, saveing results to {}'.format(args.Output))
converter.save(args.Output)

the conversion process generates warnings but succeeds. 

**in another program/script/"execution session" I perform the following:**
load the saved model using the following code

saved_model_loaded = tf.saved_model.load('my saved model directory name',tags=[tf.compat.v1.saved_model.tag_constants.SERVING])
    graph_func = saved_model_loaded.signatures[tf.compat.v1.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
    frozen_func = convert_variables_to_constants_v2(graph_func)
    print('created concreate function')

try to load an image for inference 

ReadFile = tf.io.read_file('/home/omerbrandis/ffrobotics/AppleMask/mask_rcnn/test_images/img3095_RECT2_2.jpg')
print('after read file')
DecodedImg = tf.io.decode_jpeg(ReadFile)
print('after decode ')
image_expanded = tf.expand_dims(DecodedImg, axis=0)
print('read file')

**at runtime the code does not reach "read file" , only "after decode" is written.**

if i comment out the first section of the program that deals with reading the graph , the part that reads the file works without any problem.

as stated before, i have 4GB of ram on my gpu , and the conversion process should have limited the graphs usage to 1gb thus the OOM error is surprising. ( the image is only 210X210 pixels).

please advise
Omer.

**Comment by ravikyram** [comment]
@omerbrandis 

Can you please try in latest stable TF version 2.4 and see if you are facing the same issue?.There are lot of performance improvements in latest releases.

If you are facing issue still please share the colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
