### ISSUE TITLE
call() missing 1 required positional argument

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#46090]
Tensorflow Version 2.4 pip wheel
Python Version: 3.6
OS: official docker
As the title, when I try to export a multi-input model, it failed with an error message "call() missing 1 required positional argument: 'y'".Thanks for your help.
Here comes the code:
```python
import tensorflow as tf
import numpy as np
class CustomModel(keras.Model):
    def __init__(self, hidden_units):
        super(CustomModel, self).__init__()
        self.dense_layers = [keras.layers.Dense(u) for u in hidden_units]

    def call(self, x, y):
        x = tf.concat((x, y), axis=1)
        for layer in self.dense_layers:
            x = layer(x)
        return {'x': x}


model = CustomModel([16, 16, 10])
# Build the model by calling it
input_arr = tf.random.uniform((1, 5))
input_arr_2 = tf.random.uniform((1, 10))
outputs = model(input_arr, input_arr_2)
print(outputs)
model.save("my_model")
```

**Comment by ravikyram** [comment]
@lizhen2017 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, let us know which TF version you are using?.
Will it be possible to share complete error log?

Thanks!

**Comment by lizhen2017** [comment]
> @lizhen2017
> 
> Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> Please, let us know which TF version you are using?.
> Will it be possible to share complete error log?
> 
> Thanks!

Hi，I've update the tf version. Thanks for you help.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, 2.4, nightly version(`2.5.0-dev20210113`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cf638999d664bbaad2985e9be4c5fb15/untitled616.ipynb). Thanks!

**Comment by bguetarni** [comment]
When I remove `y` from the inputs of the call function, the model saving does not throw an error; see [gist](https://colab.research.google.com/gist/bguetarni/475044bfaea272db92f6fb3ee54cf7cb/untitled616.ipynb).
I suspect Tensorflow to run the model in order for him to recover the graph.
However the `tf.keras.Model.call()` function takes only 1 argument.
During the call they probably use this function with only 1 argument (as expected by the function prototype) and this is why it throws this error.

If you want to concatenate these arrays, do it before running the model so you just pass one array.

**Comment by jvishnuvardhan** [comment]
@lizhen2017 Sorry for the late response. I changed couple of lines and it works as expected. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3759195bb062465c63291175a5be1444/untitled616.ipynb) is a gist for reference. Currently model `call` expects single argument `inputs` other than self, traininig=`True` or `False`.

The following lines were added or changed

```
1.         self.hidden_units = hidden_units
2.        self.dense_layers = [keras.layers.Dense(u) for u in self.hidden_units]

3.   def call(self, inputs): # x, y):


4. outputs = model([input_arr, input_arr_2])
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by Aisharjaa** [comment]
# Fine tune all layers
# Passing layers="all" trains all layers. You can also 
# pass a regular expression to select which layers to
# train by name pattern.
model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE / 10,
            epochs=10, 
            layers="all")

Here shows,
TypeError                                 Traceback (most recent call last)
<ipython-input-36-f6fd060a95c0> in <module>()
      5 model.train(dataset_train, dataset_val, 
      6             learning_rate=config.LEARNING_RATE / 10,
----> 7             epochs=10 )

TypeError: train() missing 1 required positional argument: 'layers'

What should I do?
