### ISSUE TITLE
When can we expect Tensorflow builds with Cuda 11.1 or Cuda 11.2?

### ISSUE THREAD

**Issue by ion-elgreco** [tensorflow/tensorflow#46093]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Tensorflow 2.4 and 2.5 is only built with cuda 11.0.  Can there please be an updated build, which is built with Cuda 11.1 or Cuda 11.2. 

**Will this change the current api? How?**

Tensorflow will point at cuda 11.1/2 files instead of cuda 11.0.

**Who will benefit with this feature?**

At least everyone with RTX 3000 series graphics card, since only cuda 11.1+ officially supports compute capability 8.6.

**Any Other info.**

**Comment by ahtik** [comment]
CUDA 11.1 support has been merged, so I'd expect it to "drop" [:()] with the TF 2.5 release, https://github.com/tensorflow/addons/pull/2218

Today CUDA 11.2 does not have a corresponding cuDNN version, so I'd think this is a blocking prerequisite.

**Comment by ion-elgreco** [comment]
> CUDA 11.1 support has been merged, so I'd expect it to "drop" [ :) ] with the TF 2.5 release, [tensorflow/addons#2218](https://github.com/tensorflow/addons/pull/2218)
> 
> Today CUDA 11.2 does not have a corresponding cuDNN version, so I'd think this is a blocking prerequisite.
> 
> EDIT: Mistakenly linked the addons 11.1 support, but still TF 2.5 looks like the earliest point for getting the Ampere cards fully supported...

Ah indeed I thought cuda 11.2 already had a compatible cudnn version. Nice to see it will come in the next version.

**Comment by teusbenschop** [comment]
I am using the TF nightly build of today 31 December, but it gives a CUDA error on the RTX 3090 card.

Here are the steps taken:

```
$ docker run --gpus all -it --rm ${USER} -v $HOME:/home -w /home -p 8888:8888 -p 5000:5000 tensorflow/tensorflow:2.4.0-gpu bash 

# pip install tf-nightly-gpu==2.5.0.dev20201231

# python

>>> import tensorflow as tf
2020-12-31 19:40:19.756487: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> tf.config.list_physical_devices('GPU')
2020-12-31 19:40:46.403718: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-12-31 19:40:46.440280: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
2020-12-31 19:40:46.440329: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 5651e9c008a2
2020-12-31 19:40:46.440343: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 5651e9c008a2
2020-12-31 19:40:46.440474: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 455.23.4
2020-12-31 19:40:46.440530: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 455.23.4
2020-12-31 19:40:46.440550: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 455.23.4
[]
```

Results:

Notice the error ```failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error```

The RTX 3090 is not listed as a GPU in TensorFlow.

Question: How to get the RTX 3090 listed as a GPU in TensorFlow?

**Comment by ahtik** [comment]
@teusbenschop If you're ok with the master then it would help to just build from the master by yourself against CUDA 11.1 and corresponding CUDA 11.1 cudnn-8.0.5.39. AFAIK TF nightly is built against CUDA 11.0.

**Comment by teusbenschop** [comment]
Thank you @ahtik , yes I am comfortable with the master and comfortable with C / C++, so it should work out well.

**Comment by OgreTransporter** [comment]
Is it possible that cuDNN 8 for 11.1 also works with 11.2? On the download page of TensorRT (https://developer.nvidia.com/nvidia-tensorrt-7x-download) is the following info:
`TensorRT 7.2.2 for Windows10 and CUDA 11.1 & 11.2 ZIP package`
and
`TensorRT 7.2.2 for Linux and CUDA 11.1 & 11.2`

**Comment by ahtik** [comment]
@OgreTransporter A few days ago we built from source the latest TF master with CUDA 11.2 and the latest 8.x cuDNN. Build succeeded.

cuDNN was meant for CUDA 11.1. Although CUDA 11.2 was working fine, as soon as cuDNN was involved, basic LSTM model trainings crashed.

The conclusion was that CUDA 11.1 cuDNN can't be used for CUDA 11.2, and we must wait for the CUDA 11.2 cuDNN before trying again.

**Comment by ion-elgreco** [comment]
> @OgreTransporter A few days ago we built from source the latest TF master with CUDA 11.2 and the latest 8.x cuDNN meant for CUDA 11.1. Build succeeded.
> 
> Although CUDA 11.2 was working fine, as soon as cuDNN was involved, basic LSTM model trainings crashed.
> 
> The conclusion was that CUDA 11.1 cuDNN can't be used for CUDA 11.2, and we must wait for the CUDA 11.2 cuDNN before trying again.

Did you also try a build with CUDA 11.1? Or are you guys just aiming for CUDA 11.2 now?

**Comment by ahtik** [comment]
@ion-elgreco Yes, we built and actively use the latest TF with CUDA 11.1 and corresponding cuDNN 8.x.

So far no issues other than the risk of having it built from the master. TF 2.4 and CUDA 11.1 didn't get along.

**Comment by Alchete** [comment]
> @ion-elgreco Yes, we built and actively use the latest TF with CUDA 11.1 and corresponding cuDNN 8.x.
> 
> So far no issues other than the risk of having it built from the master. TF 2.4 and CUDA 11.1 didn't get along.

Hi guys, wondering if you guys have tried the latest?  nVidia claims cuDNN 8.1 is now compatible with CUDA 11.2.

cuDNN v8.1.0 (January 26th, 2021), for CUDA 11.0,11.1 and 11.2

**Comment by Lucasbravo1** [comment]
Hi all,

Has anyone installed TF for CUDA11.1 yet?

I just tried to install tf-nightly-2.5.0.dev20210202 from pip3 but got this error. It seems that tf-nightly still look for CUDA11.0 rather than 11.1. 

```
import tensorflow as tf
2021-02-03 01:04:35.803100: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/extras/CUPTI/lib64
2021-02-03 01:04:35.803125: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by rTiagoS** [comment]
Hi everybody,

I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but

TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried? 

Hope for replys! Thanks!!

**Comment by keremycdg** [comment]
@rTiagoS
Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.4.1

**Comment by stronquens** [comment]
> Hi everybody,
> 
> I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> 
> TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> 
> Hope for replys! Thanks!!
> 
> EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0

Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(

**Comment by ion-elgreco** [comment]
> > Hi everybody,
> > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > Hope for replys! Thanks!!
> > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> 
> Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(

Nvidia driver version?

**Comment by stronquens** [comment]
> > > Hi everybody,
> > > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > > Hope for replys! Thanks!!
> > > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> > 
> > 
> > Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> > I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(
> 
> Nvidia driver version?

461.40

**Comment by ion-elgreco** [comment]
> > > > Hi everybody,
> > > > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > > > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > > > Hope for replys! Thanks!!
> > > > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> > > 
> > > 
> > > Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> > > I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(
> > 
> > 
> > Nvidia driver version?
> 
> studio driver 461.40

Strange, could you try 416.09?

**Comment by stronquens** [comment]
> > > > > Hi everybody,
> > > > > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > > > > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > > > > Hope for replys! Thanks!!
> > > > > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> > > > 
> > > > 
> > > > Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> > > > I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(
> > > 
> > > 
> > > Nvidia driver version?
> > 
> > 
> > studio driver 461.40
> 
> Strange, could you try 416.09?

On the nvidia website the oldest driver compatible with my graphics is 451 (rtx 3070)

**Comment by ion-elgreco** [comment]
> > > > > > Hi everybody,
> > > > > > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > > > > > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > > > > > Hope for replys! Thanks!!
> > > > > > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> > > > > 
> > > > > 
> > > > > Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> > > > > I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(
> > > > 
> > > > 
> > > > Nvidia driver version?
> > > 
> > > 
> > > studio driver 461.40
> > 
> > 
> > Strange, could you try 416.09?
> 
> On the nvidia website the oldest driver compatible with my graphics is 451 (rtx 3070)

Sorry, typo! I meant 461.09

**Comment by BalzySte** [comment]
@keremycdg
Same specs as @rTiagoS and same issue, right now I'm downgrading to Cuda 11.0 as a temporary fix

**Comment by stronquens** [comment]
> > > > > > > Hi everybody,
> > > > > > > I have installed the latest CUDA 11.2 version from the official documentation and also CUDNN 8.1 successfully, but
> > > > > > > TENSORFLOW doesn't recognize my GPU... In order to do that, I need to built tensorflow from source? Have someone already tried?
> > > > > > > Hope for replys! Thanks!!
> > > > > > > EDIT: I ended up using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0
> > > > > > 
> > > > > > 
> > > > > > Same issue for me too. CUDA 11.2 , cudNN 8.1 , tensorflow==2.5
> > > > > > I ended up too using the required version of CUDA and CUDNN that tensorflows requires. CUDA version: 11.0 (update 1) and CUDNN version: 8.0 but with this LSTM and CONV layers crash :(
> > > > > 
> > > > > 
> > > > > Nvidia driver version?
> > > > 
> > > > 
> > > > studio driver 461.40
> > > 
> > > 
> > > Strange, could you try 416.09?
> > 
> > 
> > On the nvidia website the oldest driver compatible with my graphics is 451 (rtx 3070)
> 
> Sorry, typo! I meant 461.09

Tested and doesn't work

**Comment by ljburtz** [comment]
On my RTX 3090, I had ptax related errors when using the Tensorflow provided container (tensorflow/tensorflow:latest-gpu-jupyter -> tensorflow 2.4)

I fixed by using the NVIDIA provided container (nvcr.io/nvidia/tensorflow:21.02-tf2-py3 also tensorflow 2.4)
available at
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html#running

It's already built with CUDA 11.2!

**Comment by Sicily-F** [comment]
> @keremycdg
> Same specs as @rTiagoS and same issue, right now I'm downgrading to Cuda 11.0 as a temporary fix

Can I ask how you downgraded? I'm using Tensorflow-gpu on a Linux Tesla server at my university which comes with NVIDIA Driver Version: 460.27.04    CUDA Version: 11.2. I'm guessing I'm going to have to downgrade to CUDA 11.0 locally - any suggestions on how to do this? I'm more familiar with using Tensorflow on Windows so would appreciate any advice

**Comment by mihaimaruseac** [comment]
Nightly should now build with CUDA 11.2

2.5 branch cut is today so next week there will be an RC0 that you can use and test.

**Comment by Sicily-F** [comment]
> Nightly should now build with CUDA 11.2
> 
> 2.5 branch cut is today so next week there will be an RC0 that you can use and test.

How do I use the Nightly build? Can I use it without Bazel?

**Comment by Sicily-F** [comment]
I tried uninstalling tensorflow and tensorflow gpu and reinstalled both tf-nightly and tf-nightly gpu, same errors: 

pciBusID: 0000:87:00.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
2021-03-25 21:29:31.829916: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.831735: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.834609: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.840163: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-03-25 21:29:31.843093: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-03-25 21:29:31.848239: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.850681: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.853139: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
2021-03-25 21:29:31.853174: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-03-25 21:29:31.853217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-25 21:29:31.853238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1
2021-03-25 21:29:31.853253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N N
2021-03-25 21:29:31.853266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   N N

Any advice would be greatly appreciated this is driving me crazy!

**Comment by ljburtz** [comment]
I highly recommend using the tensorflow docker image built by NVIDIA ! 
see my [comment upthread](https://github.com/tensorflow/tensorflow/issues/46093#issuecomment-787044411)

**Comment by Sicily-F** [comment]
> I highly recommend using the tensorflow docker image built by NVIDIA !
> see my [comment upthread](https://github.com/tensorflow/tensorflow/issues/46093#issuecomment-787044411)

hi there, 

Ok, I'll give it a try!

Many thanks

**Comment by Sicily-F** [comment]
> On my RTX 3090, I had ptax related errors when using the Tensorflow provided container (tensorflow/tensorflow:latest-gpu-jupyter -> tensorflow 2.4)
> 
> Then I switched to the NVIDIA provided docker image (nvcr.io/nvidia/tensorflow:21.02-tf2-py3 also tensorflow 2.4)
> available at
> https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html#running
> 
> It's already pre-built from source with CUDA 11.2 and works like a charm! no more tensorflow installation hassle
> 
> highly recommend

Can I ask if this was on your own computer? I just tried on a server, pulling the docker image in with Singularity, and the NPC image doesn't support the NVIDIA Tesla K80 GPU, any other suggestions?

**Comment by ljburtz** [comment]
Sorry about that. It does [look like](https://forums.developer.nvidia.com/t/can-we-use-ngc-docker-containers-of-deep-learning-libraries-on-tesla-k80/62926) the older architecture of the NVIDIA K80 isn't supported by NGC containers. To answer your question, II was indeed on my own computer, and I don't have experience with the K80 or Singularity, best of luck on your use case and hopefully the tensorflow RC0 mentioned upthread is just around the corner

**Comment by povolann** [comment]
> On my RTX 3090, I had ptax related errors when using the Tensorflow provided container (tensorflow/tensorflow:latest-gpu-jupyter -> tensorflow 2.4)
> 
> Then I switched to the NVIDIA provided docker image (nvcr.io/nvidia/tensorflow:21.02-tf2-py3 also tensorflow 2.4)
> available at
> https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/running.html#running
> 
> It's already pre-built from source with CUDA 11.2 and works like a charm! no more tensorflow installation hassle
> 
> highly recommend

Hi, can I ask which command exactly did you use here?
_If you have Docker 19.03 or later, a typical command to launch the container is:
docker run --gpus all -it --rm -v local_dir:container_dir nvcr.io/nvidia/tensorflow:<xx.xx>-tf<x>-py<x>_

It gives me the error:
_bash: syntax error near unexpected token `newline'_

So, I have tried
_docker run --gpus all -it --rm -v local_dir:container_dir nvcr.io/nvidia/tensorflow:xx.xx-tfx-pyx_
And also (connect: permission denied)
_sudo docker run --gpus all -it --rm -v local_dir:container_dir nvcr.io/nvidia/tensorflow:xx.xx-tfx-pyx_

But now it gives me the error:
_Unable to find image 'nvcr.io/nvidia/tensorflow:xx.xx-tfx-pyx' locally
docker: Error response from daemon: manifest for nvcr.io/nvidia/tensorflow:xx.xx-tfx-pyx not found: manifest unknown: manifest unknown._
I guess I have to rewrite the image part but I am not sure which one I should choose.
Thank you for your answer!

**Comment by danijar** [comment]
@mihaimaruseac, do you have an idea when the prebuilt `tf-nightly` package will start using CUDA 11.2?

**Comment by ljburtz** [comment]
@povolann you can use the image name I put in my original message that you quoted. For example, try this command:
`docker run --gpus all -it --rm nvcr.io/nvidia/tensorflow:21.02-tf2-py3`

Next step: make sure you check the [docker documentation](https://docs.docker.com/storage/volumes/) to understand the `-v` flag, you'll see you just have to specify `local_dir` and `container_dir` paths that make sense on your system.

**Comment by songgc** [comment]
@Sicily-F Latest NGC dockers stopped supporting K80. Try [Tensorflow docker](https://www.tensorflow.org/install/docker)

**Comment by Sicily-F** [comment]
> @Sicily-F Latest NGC dockers stopped supporting K80. Try [Tensorflow docker](https://www.tensorflow.org/install/docker)

Hi, thanks for this! I've found a workaround with a custom-built nvidia image with the required libraries, but I'll try the Tensorflow docker as it's maybe more stable

**Comment by kamodulin** [comment]
I've been following this issue for a while and was finally was able to use the pre-release `tensorflow-gpu==2.5.0rc0` without any problems on my 3070! I thought I'd share my configuration in the event someone wants to try this method too (unfortunately, I never was able to get the methods above to work). I'll also note that the tf 2.4, cuDNN 8.0, and CUDA 11.0 build configuration didn't work for me either.

I did the following with miniconda:
- I installed the latest release candidate via `pip install tensorflow-gpu==2.5.0rc0`
- I installed CUDA 11.1 with `conda install cudatoolkit=11.1 -c conda-forge`
- I downloaded the missing [cuDNN 8.1.0](https://developer.nvidia.com/rdp/cudnn-archive#a-collapse810-102) and placed the .dll files into my environment's Library>bin folder as described [here](https://medium.com/analytics-vidhya/install-tensorflow-gpu-2-4-0-with-cuda-11-0-and-cudnn-8-using-anaconda-8c6472c9653f)

**Comment by EwoutH** [comment]
CUDA 11.3 is released!

- Blog: [Exploring the New Features of CUDA 11.3](https://developer.nvidia.com/blog/exploring-the-new-features-of-cuda-11-3/)
- Blog: [Programming Efficiently with the NVIDIA CUDA 11.3 Compiler Toolchain](https://developer.nvidia.com/blog/programming-efficiently-with-the-cuda-11-3-compiler-toolchain/)
- [Download CUDA 11.3](https://developer.nvidia.com/cuda-downloads)
- [CUDA Samples repo](https://github.com/NVIDIA/cuda-samples)

**Comment by Zethson** [comment]
> Nightly should now build with CUDA 11.2
> 
> 2.5 branch cut is today so next week there will be an RC0 that you can use and test.

I still have issues with Cuda 11.2 and RC1:

```
2021-04-23 19:13:13.420425: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-04-23 19:13:13.420452: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Num GPUs Available: 0
```

The same container has 0 issues with PyTorch.

**Comment by DachuanZhao** [comment]
+ 1 . Hope tensorflow2.5.0 can be built with cuda>=11.1

**Comment by mihaimaruseac** [comment]
It should.

You can test the RCs, they should work with CUDA 11.2

**Comment by bhack** [comment]
Can we close this?

**Comment by DachuanZhao** [comment]
> Can we close this?

Yes , you can close it since the outdated docs will be updated . [https://github.com/tensorflow/tensorflow/issues/49295](https://github.com/tensorflow/tensorflow/issues/49295)

**Comment by ymodak** [comment]
The docs are now updated with commit [69919bd](https://github.com/tensorflow/docs/commit/69919bd2c59a4902534f52f8de09eeead96e2ed6) Thanks!
