### ISSUE TITLE
broken links in word2vec tutorial docs

### ISSUE THREAD

**Issue by alexrudnick** [tensorflow/tensorflow#461]
Some of the links to word2vec_basic.py currently give a 404 -- they point to https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/word2vec/word2vec_basic.py . They should probably point to the version at  https://www.tensorflow.org/versions/master/tutorials/word2vec/word2vec_basic.py , right?

**Comment by vrv** [comment]
Yeah, we haven't pushed the new website that has these link fixes yet.  We'll probably do so soon.

**Comment by vrv** [comment]
Pushed website, fixed!
