### ISSUE TITLE
TFlite interpreter stuck after call to invoke()

### ISSUE THREAD

**Issue by N1ckx** [tensorflow/tensorflow#46107]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): example code + adaptations
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: tf-nightly 2.5.0.dev20210102
- Python version: 3.6.9
- GPU model and memory: no GPU

**Describe the current behavior**
TFlite interpreter invoke() method never returns

**Describe the expected behavior**
invoke() method returns with results

Hi,
i've successfully trained an object detection model using tensorflow 2.3.0 with SSD ResNet50 V1 FPN pretrained model.
By loading the model as a saved_model format i can run it as expected on my PC and on raspberry pi 4 as well.

Because performance on the rasperryPI was not good i looked into TFLite optimiziations and got some issues with the conversion from saved_model to .tflite format. The model was trained with the keep_aspect_ratio_resizer imge_resizer that required dynamic input size support from tflite. This is when i've moved to tf-nightly as suggested in a discussion found here on github. After the update the conversion was successfull, this is the code:
```
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("./1024PRE_v2/saved_model") # path to the SavedModel directory
converter.experimental_new_converter = True
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

# Save the model
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

In the object detection code i added a call to resize_tensor_input as suggested but the execution never gets past the invoke() method:

 ```
  interpreter = interpreter_wrapper.Interpreter(model_path=model_file)
  interpreter.resize_tensor_input(0, [1, 1024, 1024, 3])
  interpreter.allocate_tensors()

  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()

  category_index = label_map_util.create_category_index_from_labelmap(label_file, use_display_name=True)

  # Load a 1024x1024 image
  img = cv2.imread(file_name)

  # add N dim
  input_data = np.expand_dims(img, axis=0)

  interpreter.set_tensor(input_details[0]['index'], input_data)

  interpreter.invoke()
  
 # Code never reaches this point
 ```

Thanks in advance for the support

**Comment by N1ckx** [comment]
Forgot to mention that there's no output/log on the console coming from the invoke() method

**Comment by Emmanuel357** [comment]
try upgrading your python version to 3.8

**Comment by srjoglekar246** [comment]
You need to use [this method](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) of converting to TFLite, since SSD models (as-is from TF) don't work well on-device. We usually require an intermediate step to generate a TFLite-compatible SavedModel before using the converter API. For an end-to-end example, see [this](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb). Also, for TFLite we only support the [fixed size resizer](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_lib_tf2.py#L94), so you can do the pre-processing outside of TFLite & keep the model input size constant.

**Comment by N1ckx** [comment]
@Emmanuel357: tested on Ubuntu 20.4, using default python installation (2.8.5) i get the same result.

@srjoglekar246: ok, i will try that. Hopefully i can keep my checkpoint without having to train the model from the beginning.

Thanks,

**Comment by N1ckx** [comment]
I carried on my work on ubuntu 20.4, python 3.8.5 and last stable tensorflow release 2.4.0. I followed @srjoglekar246 suggestions and regenerated the tflite file from the new model but i got the same issue again.

I've however now found that everything works if from my tflite conversion code i remove this line:
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`

That line was expected to have no effect anyway, furthermore it looks like the use of tf.lite.Optimize is depracated now.

Thanks for your support.

**Comment by N1ckx** [comment]
It turns out that i can leave this line:
converter.optimizations = [tf.lite.Optimize.DEFAULT]

only if i also set "converter.target_spec.supported_ops". This is actually done in the first link @srjoglekar246, and that make it work. The reason i didn't set it in the first place was because in the example full integer quantiziation was enabled requiring me to set representative_dataset which i didn't understand and according to the documentation was optional.

Now i'm facing another issue where the tflite model is giving me completely wrong results compared to the saved_model. This looks like could be the same as what reported in issue #46142

**Comment by terryheo** [comment]
@N1ckx BTW, could you share how to get rasperryPI runtime?
FYI, if you can use 64bit OS (such as https://ubuntu.com/download/raspberry-pi), aarch64 binary gives better performance than armhf binary.

> Because performance on the rasperryPI was not good i looked into TFLite optimiziations and got some issues with the conversion from saved_model to .tflite format.

**Comment by N1ckx** [comment]
@terryheo I'm using a prebuilt arm 32bit wheel found here:
https://github.com/PINTO0309/Tensorflow-bin

I'm using raspbian 32bit, i will try ubuntu 64bit as you suggested.
 
Thanks,

**Comment by sushreebarsa** [comment]
@N1ckx Could you please let us know if you have tried as per [this comment](https://github.com/tensorflow/tensorflow/issues/46107#issuecomment-758466789) and  this issue still persists ? Thanks!
