### ISSUE TITLE
Hello guys , does any one know how to solve this issue ? Thanks in advance!

### ISSUE THREAD

**Issue by 13564545AWq** [tensorflow/tensorflow#46104]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by 13564545AWq** [comment]
My code is here :+1: #!sur/bin/python3
# -*-coding:utf-8 -*-
# Author: Wang Quan
# @Time:2021/1/2 7:46

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
# from tensorflow.keras.models import Sequential
import numpy as np
import math

(x_train,y_train),(x_test,y_test)=keras.datasets.mnist.load_data()
# print(len(x_train))
# print(len(x_test))
# print(x_train[0].shape)
# plt.matshow(x_train[0])
# plt.show()
# print(y_train[0])
# print(x_train.shape)
x_train=x_train/255.0
x_test=x_test/255.0

x_train_flattened= x_train.reshape(len(x_train),28*28)
x_test_flattened= x_test.reshape(len(x_test),28*28)
# print(x_train_flattened.shape)
# print(x_test_flattened.shape)
# print(x_train[2])
# print(x_train_flattened[2])

model=keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train_flattened,y_train,epochs=5)
model.evaluate(x_test_flattened,y_test)

# plt.matshow(x_test[2])
# plt.show()
y_predict=model.predict(x_test_flattened)
print(np.argmax(y_predict[2]))   #打印7

y_predicted_labels = [np.argmax(i) for i in y_predict]
# print(y_predicted_labels[:5])
# # y_test[:5]
cm=tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
print(cm)
import seaborn as sn
plt.figure(figsize=(10,7))
sn.heatmap(cm,annot=True,fmt='d')
plt.xlabel('predicted')
plt.ylabel('truth')
plt.show()

I got error :Tensor("confusion_matrix/SparseTensorDenseAdd:0", shape=(10, 10), dtype=int32)
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/光学系统/Keras Code/mnist read.py", line 53, in <module>
    sn.heatmap(cm,annot=True,fmt='d')
  File "C:\Users\Administrator\Anaconda3\envs\pythonProject\lib\site-packages\seaborn\_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "C:\Users\Administrator\Anaconda3\envs\pythonProject\lib\site-packages\seaborn\matrix.py", line 537, in heatmap
    yticklabels, mask)
  File "C:\Users\Administrator\Anaconda3\envs\pythonProject\lib\site-packages\seaborn\matrix.py", line 101, in __init__
    plot_data = np.asarray(data)
  File "C:\Users\Administrator\Anaconda3\envs\pythonProject\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\Administrator\Anaconda3\envs\pythonProject\lib\site-packages\tensorflow_core\python\framework\ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (confusion_matrix/SparseTensorDenseAdd:0) to a numpy array.

**Comment by mihaimaruseac** [comment]
Please:

1. Fill in issue template
2. Use proper markdown formatting so code and error are easy to read
3. Give a minimal reproducing example, not a large piece of code
4. Give the issue a relevant title.
