### ISSUE TITLE
ImageDataGenerator().batch_index starts from zero even though manually setting it

### ISSUE THREAD

**Issue by ion-elgreco** [tensorflow/tensorflow#46112]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: Cuda 11.0 update 1 + cudnn 8.0.5
- GPU model and memory: RTX 3080 10GB

**Describe the current behavior**
I define my datagenerator by `ImageDataGenerator(preprocessing_function=preprocess_input)` then I define the generator:        

```
 generator = datagen.flow_from_directory(
            directory=data_dir,
            target_size=(112, 112),
            color_mode="rgb",
            class_mode=None,
            batch_size=batch_size,
            shuffle=False,
        )
```
I want to **start at a particular batch_index**, so I set the `generator.batch_index = 500`. When I loop for the first time over the generator, it will ignore this set batch_index and start at zero:  
```
for batch, label in generator:
    pred = model.predict(batch, verbose=0)
    features.append(scipy.sparse.csr_matrix(pred))
```

But if just loop over it once with 
```
for batch, label in generator:
    break
```
 and then set the `generator.batch_index = 500`, and then loop over it again with the previous code it will start at the correct index.

I don't know if this is a feature or not. But if it is, it's not very practical to loop over it once before being able to adjust the batch_index.

**Describe the expected behavior**
I should be able to change the batch_index before looping over the generator. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Comment by amahendrakar** [comment]
@ion-elgreco,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by ion-elgreco** [comment]
> @ion-elgreco,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

You can run everything, I included comments and you can see the behaviour as I have previously described.

https://deepnote.com/project/018372c1-db6c-4f31-90a4-54d7a3500f33#%2Fnotebook.ipynb

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b11b4ac0a11295b05518adcdb25d6ad6/46112.ipynb). Thanks!

**Comment by fchollet** [comment]
`ImageDataGenerator` is not intended for subclassing. You could either reimplement your own version of it (by copying the code), or instead write a tf.data pipeline (recommended).

**Comment by ion-elgreco** [comment]
> `ImageDataGenerator` is not intended for subclassing. You could either reimplement your own version of it (by copying the code), or instead write a tf.data pipeline (recommended).

Alright, I'll just use this workaround by calling the generator first and then changing the batch_index.
