### ISSUE TITLE
Will TensorFlow update new optimizer?: Adabelief

### ISSUE THREAD

**Issue by IchiruTake** [tensorflow/tensorflow#46119]
**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): Yes

I have read this article and it is quite interesting? At this time, I use Adam optimizer in TensorFlow but the current accuracy is just 88%. The Adabelief gave me an idea about getting the model accuracy to be over 90% which inspires me. Thus I am wondering will TensorFlow will update this? Thank you

https://medium.com/the-dl/understanding-the-new-adabelief-optimizer-2db70ef6de1e
https://arxiv.org/pdf/1412.6980.pdf

**Comment by bhack** [comment]
Check:
https://github.com/tensorflow/addons/issues/2203
https://github.com/tensorflow/addons/pull/2234

/cc @tomerk

**Comment by jvishnuvardhan** [comment]
I think we can close this feature from here and track the progress in `addons` as that is the right repo for new optimizers. Thanks!
