### ISSUE TITLE
Documentation for Allocator

### ISSUE THREAD

**Issue by JC3** [tensorflow/tensorflow#4611]
Feature request: Documentation for Allocator on the web site (referenced by https://www.tensorflow.org/versions/r0.10/api_docs/cc/ClassTensor.html).

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

There is no documentation for Allocator or references to it except a few SO threads about interpreting PoolAllocator log messages. Information about it does not seem to exist outside of the source itself.

**Comment by concretevitamin** [comment]
I doubt we'll ever get to this -- Allocator is really an internal implementation detail, and subject to changes.  For now, sources -- and associated unit tests -- are your best bet.
