### ISSUE TITLE
what CUDA 11 and cuDNN i have to install to use TF 2.4?

### ISSUE THREAD

**Issue by TekpreXyz** [tensorflow/tensorflow#46110]
Hello i just want know what CUDA 11 and cuDNN i have to install to use TF 2.4
I'ts not clear in doc
![image](https://user-images.githubusercontent.com/73416709/103465568-4885bc80-4d3d-11eb-8438-4ccf6f940133.png)
Thanks

**Comment by kurmons** [comment]
Hi
CUDA Toolkit 11.0 (May 2020)

**Comment by ion-elgreco** [comment]
You can install Cuda toolkit 11.0 update 1 and cudnn 8.0.5.

**Comment by TekpreXyz** [comment]
thanks all!
