### ISSUE TITLE
This throws ERROR: features = tf.io.parse_example(..., features=make_parse_example_spec(columns))

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#46128]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): Latest from this week
- Python version: 3.8.x
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: 

**Describe the current behavior**
I was trying this code, but it throws exception

```https://www.tensorflow.org/api_docs/python/tf/keras/experimental/SequenceFeatures```

```return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (Ellipsis) with an unsupported type (<class 'ellipsis'>) to a Tensor.```


Here is the full code from that page,


```# Behavior of some cells or feature columns may depend on whether we are in
# training or inference mode, e.g. applying dropout.
training = True
rating = sequence_numeric_column('rating')
watches = sequence_categorical_column_with_identity(
    'watches', num_buckets=1000)
watches_embedding = embedding_column(watches, dimension=10)
columns = [rating, watches_embedding]

sequence_input_layer = SequenceFeatures(columns)
features = tf.io.parse_example(...,
                               features=make_parse_example_spec(columns))
sequence_input, sequence_length = sequence_input_layer(
   features, training=training)
sequence_length_mask = tf.sequence_mask(sequence_length)

rnn_cell = tf.keras.layers.SimpleRNNCell(hidden_size, training=training)
rnn_layer = tf.keras.layers.RNN(rnn_cell, training=training)
outputs, state = rnn_layer(sequence_input, mask=sequence_length_mask)
```

**Comment by ravikyram** [comment]
@summa-code 

Please share colab link or simple standalone code with supporting files to reproduce the issue. It helps us in localizing the issue faster.I am seeing the error message(`NameError: name 'sequence_numeric_column' is not defined`) while trying to reproduce the issue. Thanks!

**Comment by summa-code** [comment]
That is what i have given in the description, and also is in this link !!!!!!!

https://www.tensorflow.org/api_docs/python/tf/keras/experimental/SequenceFeatures

**Comment by ravikyram** [comment]
I have tried in colab with TF version [2.4 gist](https://colab.research.google.com/gist/ravikyram/445470fd54502d56b948ebc76743b505/untitled594.ipynb) and Nightly version(`2.5.0-dev20210104`) [gist](https://colab.research.google.com/gist/ravikyram/9b2cc481b9c9390d2abdd3e516f43a84/untitled593.ipynb) and was able to reproduce the issue. Thanks!

**Comment by MarkDaoust** [comment]
> `ValueError: Attempt to convert a value (Ellipsis) with an unsupported type (<class 'ellipsis'>) to a Tensor.`

Yeah, often people put `...` in examples to say "fill this in with the necessary code". it's too bad that `...` is also valid python.

 Anyway, this whole line: `tf.io.parse_example(..., features=feature_column.make_parse_example_spec(columns))` is a distraction from the function being documented here. This thing doesn't need `Examples` or parser specifications. It needs a dictionary of `SparseTensors`.
 
 If you actually do want to parse some tensors using that construct, `...` is where you's pass some `SerializeToString` serialized `tf.Examples`.
 
 Now, we encourage people to use doctest format `>>>` which we do test. But this doc is likely low enough traffic that we may never come back to fix this.

**Comment by summa-code** [comment]
I am little bit confused. So the example given looks like self contained. We are trying to extract the inputs. In the example given above what do you think goes in ... ? There is one numeric and and one categorical feature.

**Comment by MarkDaoust** [comment]
This line:

```
features = tf.io.parse_example(...,
                               features=feature_column.make_parse_example_spec(columns))
 ```
 
 Should be something like:
 
 ```
features = {
  'rating': tf.sparse.from_dense([[1.0,1.1, 0, 0, 0],[2.0,2.1,2.2, 2.3, 2.5]])
  'watches': tf.sparse.from_dense([[2, 85, 61, 0, 0, 0],[33,92, 2, 73, 1]])
}
```

**Comment by summa-code** [comment]
So this looks like feeding the actual sequence for building the model. And should there be a "," between ratings and watches ? There was a dimension issue in the watches array, Now it is throwing some other error.

features = {
 'rating': tf.sparse.from_dense([[1.0, 1.1, 0, 0, 0], [2.0, 2.1, 2.2, 2.3, 2.5]]),
 'watches': tf.sparse.from_dense([[2, 85, 61, 0, 0, 0], [33, 92, 2, 73, 1, 3]])
}
sequence_input, sequence_length = sequence_input_layer(features, training=training)




raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Condition x == y did not hold.
Indices of first 2 different values:
[[0]
 [1]]
Corresponding x values:
[2 5]
Corresponding y values:
[3 6]
First 2 elements of x:
[2 5]
First 2 elements of y:
[3 6]
python-BaseException

Process finished with exit code 1

**Comment by summa-code** [comment]
I am just looking for a simple usage example for SequenceFeatures with couple of different sequence columns.

**Comment by MarkDaoust** [comment]
All sets of sequences need the same shapes. In my earlier post they didn't match.

This works:

```
training = True
rating = feature_column.sequence_numeric_column('rating')
watches = feature_column.sequence_categorical_column_with_identity(
    'watches', num_buckets=1000)
watches_embedding = feature_column.embedding_column(watches, dimension=10)
columns = [rating, watches_embedding]

features = {
 'rating': tf.sparse.from_dense([[1.0,1.1, 0, 0, 0],[2.0,2.1,2.2, 2.3, 2.5]]),
 'watches': tf.sparse.from_dense([[2, 85, 0, 0, 0],[33,78, 2, 73, 1]])
}

sequence_input_layer = tf.keras.experimental.SequenceFeatures(columns)
sequence_input, sequence_length = sequence_input_layer(
   features, training=training)
   
sequence_length_mask = tf.sequence_mask(sequence_length)
```

**Comment by summa-code** [comment]
Oops i missed that one. Ok, can we create "features" variable without using the real inputs ? something like this ?

features['rating'] = tf.keras.Input(shape=(?,), name='rating', dtype=tf.float32)
features['watches'] = tf.keras.Input(shape=(?,), name='watches', dtype=tf.float32)

Is the shape here just one dimensional for the feature or should it have the windowed shape ?

**Comment by summa-code** [comment]
I came across this one,

https://github.com/tensorflow/tensorflow/issues/31240

**Comment by summa-code** [comment]
And how do i create an input to LSTMCell, because i want to use CuDNN with GPU,

I am using "tf.keras.preprocessing.timeseries_dataset_from_array" to create dataset that has the shape(batch, time sequence, features) format ?

**Comment by summa-code** [comment]
And then i came across this one,

https://github.com/tensorflow/community/blob/master/rfcs/20191212-keras-categorical-inputs.md

This all leads to One hot encoding, even the hashing Trick does not do the trick. I am just lost here.

**Comment by summa-code** [comment]
????

**Comment by MarkDaoust** [comment]
The linked commit updates that example:

 2cc955f
 
     ```python
    import tensorflow as tf
    # Behavior of some cells or feature columns may depend on whether we are in
    # training or inference mode, e.g. applying dropout.
    training = True
    rating = tf.feature_column.sequence_numeric_column('rating')
    watches = tf.feature_column.sequence_categorical_column_with_identity(
        'watches', num_buckets=1000)
    watches_embedding = tf.feature_column.embedding_column(watches,
                                                dimension=10)
    columns = [rating, watches_embedding]
    features = {
     'rating': tf.sparse.from_dense([[1.0,1.1, 0, 0, 0],
                                                 [2.0,2.1,2.2, 2.3, 2.5]]),
     'watches': tf.sparse.from_dense([[2, 85, 0, 0, 0],[33,78, 2, 73, 1]])
    }
    sequence_input_layer = tf.keras.experimental.SequenceFeatures(columns)
    sequence_input, sequence_length = sequence_input_layer(
       features, training=training)
    sequence_length_mask = tf.sequence_mask(sequence_length)
    hidden_size = 32
    rnn_cell = tf.keras.layers.SimpleRNNCell(hidden_size)
    rnn_layer = tf.keras.layers.RNN(rnn_cell)
    outputs, state = rnn_layer(sequence_input, mask=sequence_length_mask)
    ```
