### ISSUE TITLE
Unhandled Rejecting Error ~ Implicit Shape Can't Be a Fractional Number

### ISSUE THREAD

**Issue by riccrdo5** [tensorflow/tensorflow#46125]
Hello everyone, sos

I am following an online tutorial on how to run gesture recognition using react and tensor flow. However, I am always seeing this error whenever I play around with the webcam in chrome.

Here is my github for what I am working on btw. And here is the tutorial video I'm watching. I got stuck right around minute 10

https://github.com/riccrdo5/help

https://youtu.be/f7uBsb-0sGQ

Ty and happy holidays

![ErrorVSC](https://user-images.githubusercontent.com/67179440/103488631-02733c00-4dc3-11eb-81d1-70c75b9f9ffa.png)
![ErrorWeb](https://user-images.githubusercontent.com/67179440/103488632-043cff80-4dc3-11eb-8446-0a80b0258b26.jpg)

**Comment by ravikyram** [comment]
@riccrdo5 

Please, refer this SO [link](https://stackoverflow.com/questions/63421470/the-implicit-shape-cant-be-a-fractional-number) and see if it helps you.
If the issue still persists please share the exact sequence of commands / steps that you executed before running into the problem and complete error log. Thanks!

**Comment by riccrdo5** [comment]
I looked over that stackoverflow page before and it did not provide me with any insight.  All I really did was import react and tensorflow. Here is my js:

![image](https://user-images.githubusercontent.com/67179440/103801490-a4cd3280-5002-11eb-879b-da7dfbe77198.png)

Thanks

**Comment by ravikyram** [comment]
@riccrdo5 
This issue is more suitable for TFjs repo. Please post it on TFjs repo from [here.](https://github.com/tensorflow/tfjs/issues/new) Thanks!

**Comment by riccrdo5** [comment]
thanks for the advice. best wishes

**Comment by ravikyram** [comment]
@riccrdo5 

Can we close the issue here and track the issue in [TFjs repo](https://github.com/tensorflow/tfjs/issues/new).Thanks!

**Comment by riccrdo5** [comment]
Yess, thanks for the help

**Comment by ravikyram** [comment]
I am closing the issue here and the issue can be tracked in TFjs repo. Thanks!
