### ISSUE TITLE
always got the time out when try to download upb file. 

### ISSUE THREAD

**Issue by huangyhg** [tensorflow/tensorflow#46121]
Firstly try to build TP  2.3 branch in windows 10 using the following command, always got the time out when download upb file. 
can I manully download the file or disable the download operation? or modify the connect_time_out option?
bazel build //tensorflow/tools/pip_package:build_pip_package
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to C:/users/86178/_bazel_86178/26orbg4z/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: connect timed out
INFO: Elapsed time: 69.014s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by huangyhg** [comment]
ystem information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
    TensorFlow installed from (source or binary): source
    TensorFlow version: v2.3.0
    Python version: CPython 3.8
    Installed using virtualenv? pip? conda?: conda
    Bazel version (if compiling from source): download bazel-3.1.0-windows-x86_64.exe

**Comment by huangyhg** [comment]
I tried to download https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz directly using IE, got the file- upb-9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz. THen put to the filefolder - C:/users/86178/_bazel_86178/26orbg4z/external/upb.
but after type the command - bazel build //tensorflow/tools/pip_package:build_pip_package,
it will automatically delete the files in filefolder - C:/users/86178/_bazel_86178/26orbg4z/external/upb. 
questoin: How to disable the "delete" behaviour?

**Comment by Emmanuel357** [comment]
The tf supporters are probably all on Christmas or new years break because they are not responding to any of the latest issues being raised.

**Comment by huangyhg** [comment]
> 
> 
> The tf supporters are probably all on Christmas or new years break because they are not responding to any of the latest issues being raised.

Happy new year. I am not familar with bazel command options.......

**Comment by huangyhg** [comment]
INFO: Found applicable config definition build:windows in file d:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository upb instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/users/86178/_bazel_86178/26orbg4z/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
WARNING: Download from https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'upb':
   java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to C:/users/86178/_bazel_86178/26orbg4z/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: connect timed out
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to C:/users/86178/_bazel_86178/26orbg4z/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: connect timed out
INFO: Elapsed time: 56.606s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

(base) D:\tensorflow>

**Comment by ravikyram** [comment]
@huangyhg 

Please, refer similar issues #37811 , [link](https://github.com/bazelbuild/bazel/issues/3737) and see if it helps you. Thanks!

**Comment by huangyhg** [comment]
> 
> 
> @huangyhg
> 
> Please, refer similar issues #37811 , [link](https://github.com/bazelbuild/bazel/issues/3737) and see if it helps you. Thanks!

yw, what is " .netrc setup"?
 I need use IE with one proxy to download the file manully .

**Comment by huangyhg** [comment]
https://raw.githubusercontent.com/vokins/yhosts/master/hosts
solved

**Comment by rmothukuru** [comment]
@huangyhg,
Closing this issue as it is resolved. Thanks!

**Comment by huangyhg** [comment]
yw, please close it, thanks.
