### ISSUE TITLE
MetalDelegate.swift : Unexpected version number in 'available' attribute for non-specific platform '*'

### ISSUE THREAD

**Issue by KonradMokiejewski** [tensorflow/tensorflow#46137]
Warning in line
 @available(*, deprecated: 2.4, renamed: "isPrecisionLossAllowed")

**Comment by ravikyram** [comment]
@KonradMokiejewski 

Can you refer this [source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/swift/Sources/MetalDelegate.swift)  and see if it helps you.

If the problem still persists please share more information and exact sequence of commands / steps that you executed before running into the problem.It helps us in localiizng the issue faster.

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!
