### ISSUE TITLE
NotFoundError: No CPU devices are available in this process

### ISSUE THREAD

**Issue by ZYCCC927** [tensorflow/tensorflow#46134]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.2
- Python version: 2.7.17
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): gcc 4.8

Hello!
I have built TF-cpu 1.13.2 from source code and I'm trying to run a benchmark [tensorflow/benchmark](https://github.com/tensorflow/benchmarks/tree/cnn_tf_v1.13_compatible/scripts/tf_cnn_benchmarks)
An error (NotFoundError) occured after I run the following commands:
`python tf_cnn_benchmarks.py --data_format=NHWC --num_gpus=0 --batch_size=8 --model=vgg16 --data_name=imagenet --variable_update=parameter_server --local_parameter_device=cpu --device=cpu > ps.log &`

However tf can detect my CPU device correctly:
```
Python 2.7.17 (default, Sep 30 2020, 13:38:04)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.client import device_lib
>>> device_lib.list_local_devices()
2021-01-04 08:35:20.085746: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15041826958121108015
]
>>>
```

Any help would be appreciated. Thanks！

Here is my log:

```
root@ip-172-31-90-169:/home/cluster/benchmarks/scripts/tf_cnn_benchmarks# python tf_cnn_benchmarks.py --data_format=NHWC --num_gpus=0 --batch_size=8 --model=vgg16 --data_name=imagenet --variable_update=parameter_server --local_parameter_device=cpu --device=cpu > ps.log &
[1] 12899
root@ip-172-31-90-169:/home/cluster/benchmarks/scripts/tf_cnn_benchmarks# Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 74, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 63, in main
    params = benchmark_cnn.setup(params)
  File "/home/cluster/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 3503, in setup
    with tf.Session(config=create_config_proto(params)) as sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1551, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 676, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.NotFoundError: No CPU devices are available in this process
```

**Comment by ravikyram** [comment]
@ZYCCC927 

Please, see similar issue #45156 and see if it helps you.
If the issue still persists, can you please share more information or provide exact sequence of commands / steps that you executed before running into the problem. Thanks!
