### ISSUE TITLE
Android: Instantiating TFLite Interpreter with GPU delegate takes 2.5 seconds.

### ISSUE THREAD

**Issue by alexanderar** [tensorflow/tensorflow#46132]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **macOS Catalina v10.15.7**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Pixel 3a**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **v2.4.0**
- Python version: **3.8.0**
- Bazel version (if compiling from source): **-** 
- GCC/Compiler version (if compiling from source): **-**
- CUDA/cuDNN version:
- GPU model and memory: **Adreno 615**

**Describe the current behavior**
The instantiation time of tiflite interpreter with GPU delegate on Android is extremely high. For some models It takes about 2.5 seconds to instantiate it. This behavior was tested with various segmentation models of different sizes (500Kb - 12Mb) and on different  mobile devices. The instantiation time very slightly dependent on the model size and is faster on flagship devices (such as Samsung Galaxy S20) but overall it is very slow. Initializing an interpreter with the same model without GPU delegate is sub millisecond.

**Standalone code to reproduce the issue**
```
// interpreterBinary: ByteBuffer direct allocated byte buffer.
val options = Interpreter.Options().addDelegate(GpuDelegate())
val stopwatch = Stopwatch.createStarted() // start trace
val interpreter = Interpreter(interpreterBinary, options)
stopwatch.stop() // end trace
```

**Comment by ek9852** [comment]
@alexanderar  Can u download the Android prebuilt benchmark tools from https://www.tensorflow.org/lite/performance/measurement
And run it in the device to see if the gpu delegate is fallback to cpu.
I notice  tat in my case the transpose  convolution is never used using GPU and is using CPU fallback.
U might try 
./android_aarch64_benchmark_model  --graph=unet.tflite  --use_gpu=true --enable_op_profiling=true
or 
./android_aarch64_benchmark_model  --graph=unet.tflite  --use_nnapi=true --enable_op_profiling=true

Not sure u are using quantitated model or not. But try to use floating model and int8 model to see if there is any changes.
If u see :
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     TfLiteNnapiDelegate	        4	    19.800	    38.140%	    38.140%	     0.000	        4
	                 CONV_2D	        3	    17.773	    34.235%	    72.375%	     0.000	        3
	          TRANSPOSE_CONV	        2	    13.034	    25.107%	    97.482%	     0.000	        2
	                     ADD	        2	     1.307	     2.518%	   100.000%	     0.000	        2

Like above , TfLiteNnapiDelegate contains all layers using nnapi acceleration. 
Which for some reason the CONV_2D, TRANSPOSE_CONV and ADD layers areall fall back to CPU.

Related to https://github.com/tensorflow/tensorflow/issues/46098

**Comment by ek9852** [comment]
@alexanderar  If you are targeting for Android phone with qualcomm chipset only. 
I would recommend to use qualcomm snpe sdk directly to do the inference.
There are some many cases that the TFLite fall back to CPU implementation..
https://developer.qualcomm.com/docs/snpe/overview.html

**Comment by alexanderar** [comment]
@ek9852 Actually I am not even talking about running the model. Just the instantiation of the interpreter takes a very long time:
`val interpreter = Interpreter(interpreterBinary, options)` on Pixel3a takes 2.8 seconds for some networks. For other is the quite fast. I thought that it may somehow depend on the model size but in this specific case the model is just  400Kb.

**Comment by srjoglekar246** [comment]
Yup, that is expected, unfortunately :-(. the GPU delegate needs to generate shaders & constants during initialization, so that takes a bunch of time. It shouldn't be as high as 2.5s for a 400kb model; which is strange. Can you share the model (even if untrained)? We are working on ways to optimize this in the future.
For now, if your model is quantized, using the NNAPI delegate will probably do a better job for you. For float models, try XNNPack.

**Comment by terryheo** [comment]
@alexanderar could you share the tflite model you used? To me 2.5s on Pixel 3a looks too much even though the shader compilation time is considered. I want to see what's going on there.

**Comment by alexanderar** [comment]
@terryheo, here is the model. It is untrained but I think that it should be enough to reproduce the issue. 
I tested it multiple times and it took me about 3.3 sec on average on Pixel 3a device with this code (simplified):

```
val options = Interpreter.Options().setUseNNAPI(false)
   .setNumThreads(Runtime.getRuntime().availableProcessors())
   options.addDelegate(GpuDelegate())
        
interpreter = Interpreter(interpreterBinary, options)
```

[model.tflite.zip](https://github.com/tensorflow/tensorflow/files/5826041/model.tflite.zip)

**Comment by terryheo** [comment]
I don't think this is the case with the recent version since TFLite GPU has a cache for shader compilation.
Plz let me know if you still have the issue.

Thanks.

**Comment by alexanderar** [comment]
@terryheo Is there a way to pre-compile shaders?

**Comment by look1n** [comment]
@terryheo Is there a way to pre-compile shaders to reduce init time?

**Comment by terryheo** [comment]
Please take a look https://www.tensorflow.org/lite/performance/gpu#delegate_serialization
