### ISSUE TITLE
ValueError: Invalid checkpoint state loaded from

### ISSUE THREAD

**Issue by JohnG0024** [tensorflow/tensorflow#46130]
Running Tensorflow 1.13.0  through Anaconda on Ubuntu 16.04 (Full install on external SSD)
Python 3.6.11

```
import tensorflow as tf
result = tf.train.get_checkpoint_state('')
```
I booted to Ubuntu 16.04 installed on external SSD from my Windows PC. When I run the above commands in my PC Internal drive path in anaconda environment, I get a warning 
```
WARNING:tensorflow:FailedPreconditionError: checkpoint; Is a directory
WARNING:tensorflow:checkpoint: Checkpoint ignored
```

But when I run the exact commands in my external SSD drive path in the same anaconda environment, I get a `ValueError: Invalid checkpoint state loaded from`

What's the cause for this and how can I fix it?

**Comment by amahendrakar** [comment]
@JohnG0024,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by JohnG0024** [comment]
It's the same with latest tensorflow. I found the problem, something to do with the ` - ` in Ubuntu path, somehow tensorflow is able to recognize '-' in Windows path, but not in Ubuntu path. Not sure why.

**Comment by amahendrakar** [comment]
@JohnG0024 
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and also the files required to run the code. Thanks!

**Comment by JohnG0024** [comment]
> import tensorflow as tf
> result = tf.train.get_checkpoint_state('')

I've already quoted the code in the first comment.
