### ISSUE TITLE
It might be better to have one more return value in function `tf.unique()` showing the indexes in the original array

### ISSUE THREAD

**Issue by yzsatgithub** [tensorflow/tensorflow#4614]
The function `tf.unique(x, name=None)` finds the unique elements in a 1-D tensor. And it now returns two value: `y` and `idx`. `y` contains all of the unique elements of `x` sorted inthe same order that they occur in `x`. `idx` contains the index of each value of `x` in the unique output `y`.

```
# tensor 'x' is [1, 1, 2, 3, 3, 3, 7, 8, 8]
y, idx = tf.unique(x)
y ==> [1, 2, 3, 7, 8]
idx ==> [0, 0, 1, 2, 2, 2, 3, 4, 4]
```

BUT i think a third return value which contains the first index of each value of `y` in the original tensor `x` is also needed. It might work like this:

```
# tensor 'x' is [1, 1, 2, 3, 3, 3, 7, 8, 8]
y, idx, idx_ori  = tf.unique(x)
y ==> [1, 2, 3, 7, 8]
idx ==> [0, 0, 1, 2, 2, 2, 3, 4, 4]
idx_ori ==> [0, 2, 3, 6, 7]
```

Just like its equivalent in Numpy does:

```
array 'x' is [1, 1, 2, 3, 3, 3, 7, 8, 8]
y, idx_ori = np.unique(x, return_index=True)
y ==> [1, 2, 3, 7, 8]
idx_ori ==> [0, 2, 3, 6, 7]
```

**Comment by concretevitamin** [comment]
@aselle: is this an instance of NumPy API disparity that we should look into?

**Comment by aselle** [comment]
It is on my radar.  tf.unique_indexes does give the indices.

**Comment by aselle** [comment]
Sorry this is in my notes... here are all the differences between numpy that I notice:

_Not compatible. numpy accepts arbitrary shapes and tf accepts only shape=(1,). tf unconditionally returns the index array whereas numpy does this only if return_index is true. np can optionally also return inverse map or return counts of each elements usage. Workaround is tf.unqiue(tf.reshape(x, [-1])). Internally numpy may do similar since the inverse is not returned shaped_. The missing return_counts can be achieved using tf.unique_counts().

TF syntax: `tf.unique(x, name=None)`
NP syntax: `np.unique (ar, return_index=False, return_inverse=False, return_counts=False)`

**Comment by aselle** [comment]
Looking more closely, it appears unique_with_counts does support this already
https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#unique_with_counts
@yzsatgithub  let me know if that addresses your need.

**Comment by rksltnl** [comment]
I was looking for this functionality and somehow landed here from Google search.
@aselle `unique_with_counts` is different from what @yzsatgithub is asking.
In the NP syntax above, he's asking the indicies equivalent to `return_index=True` attribute in NP.
`unique_with_counts` in tensorflow is equivalent to `return_counts=True` attribute in NP.

**Comment by aselle** [comment]
You can definitely get the equivalent functionality using unique_with_counts()... in more detail...
```python
import tensorflow as tf
s=tf.Session()
x = np.array([1, 1, 2, 4, 4, 4, 7, 8, 8])
print(s.run(tf.cumsum(tf.pad(tf.unique_with_counts(x)[2],[[1,0]]))[:-1]))
print(np.unique(x, return_index=1)[1])
```
yields the output
```
[0 2 3 6 7]
[0 2 3 6 7]
```

**Comment by rksltnl** [comment]
This works only if x is pre-sorted. I know this is doable but it'd be nice if it works even though x isn't sorted like the numpy version.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nagash91** [comment]
This feature is still needed and not implemented in tensorflow

**Comment by haamoon** [comment]
This code gives the equivalent functionality:
```
def unique_with_inverse(x):
  y, idx = tf.unique(x)
  num_segments = tf.shape(y)[0]
  num_elems = tf.shape(x)[0]
  return (y, idx,  tf.unsorted_segment_max(tf.range(num_elems), idx, num_segments))
```
I slightly changed [this](https://stackoverflow.com/questions/38233821/merge-duplicate-indices-in-a-sparse-tensor).
