### ISSUE TITLE
Model loaded from a SavedModel format in a distribution strategy has weights whose names are not unique

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#46146]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): colab
- TensorFlow version (use command below): 2.2 and 2.4
- Python version: 3.6
- CUDA/cuDNN version: problem is on CPU and GPU
- GPU model and memory: colab

**Describe the current behavior**

I am using a distribution strategy to train my model on several GPUs, and using the `ModelCheckpointCallback` to save my model.
I train my model in 2 steps, in the first I use the SavedModel format and in the second, I want to save my model using the HDF5 format.
However, I encounter a problem when loading my saved model in a distribution strategy, where the names of the different weights of my model are stripped down the last part (i.e. for example `'kernel:0'`).
Therefore, my model has several weights with the same name and cannot be saved in the HDF5 format.

**Describe the expected behavior**

I would like my model to be loaded in the distribution strategy with the proper names.

**Standalone code to reproduce the issue**
You can find a colab to illustrate this issue [here](https://colab.research.google.com/drive/1VqhqimaF3zxkj1mBrjugITtRC5XYJrW9?usp=sharing).

**Other info / logs** 
For reference the typical error that you get is `RuntimeError: Unable to create link (name already exists)`, with the full traceback being:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-debcda389c22> in <module>()
      1 # and as a consequence, we cannot save the weights of our model
----> 2 new_model.save_weights('new_model_weights.hdf5')

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in save_weights(self, filepath, overwrite, save_format, options)
   2106     if save_format == 'h5':
   2107       with h5py.File(filepath, 'w') as f:
-> 2108         hdf5_format.save_weights_to_hdf5_group(f, self.layers)
   2109     else:
   2110       if context.executing_eagerly():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in save_weights_to_hdf5_group(f, layers)
    640     save_attributes_to_hdf5_group(g, 'weight_names', weight_names)
    641     for name, val in zip(weight_names, weight_values):
--> 642       param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
    643       if not val.shape:
    644         # scalar

/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)
    138             if name is not None:
--> 139                 self[name] = dset
    140             return dset
    141 

/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py in __setitem__(self, name, obj)
    371 
    372             if isinstance(obj, HLObject):
--> 373                 h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
    374 
    375             elif isinstance(obj, SoftLink):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.link()

RuntimeError: Unable to create link (name already exists)
```

However, this issue is different than [this one](https://github.com/tensorflow/tensorflow/issues/27688#issuecomment-595950270) because originally the weights do have different names (and even when saved, the weights have different names, it's just that loading them inside the distribution strategy erases that).

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d0911531f279ff81a99ad3005c71a38a/46146.ipynb). Thanks!

**Comment by SwathiAunooru** [comment]
You need to disable eager execution then it is able to create unique names i was able to run it 
tf.compat.v1.disable_eager_execution()

**Comment by SwathiAunooru** [comment]
> Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d0911531f279ff81a99ad3005c71a38a/46146.ipynb). Thanks!

In this colab we just need to disable eager execution and it works fine and i was able to run through it.

**Comment by zaccharieramzi** [comment]
@SwathiAunooru good catch!
It indeed works in eager mode.
However the names of the weights are still off. This time they are not identical, but they are still not what they were before, which might prove infefficient for debugging should it happen
I also don't know how easy it is to switch between eager mode and graph mode when loading/saving weights (is it possible?).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/660acf1315c19d2a99fc2d169f2b46a7/untitled160.ipynb?authuser=1)..Thanks !
