### ISSUE TITLE
GPU-delegate null EGLDisplay: lack of Wayland support?

### ISSUE THREAD

**Issue by jfinken** [tensorflow/tensorflow#46163]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Mendel Linux 5.0 Eagle** ([Mendel Linux Versions](https://coral.ai/software/#mendel-dev-board))
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Coral Dev Board 1GB** ([details](https://coral.ai/products/dev-board/))
- TensorFlow installed from (source or binary): **source, TensorFlow Lite only**
- TensorFlow version (use command below): **released version 2.3.1**
- Python version: **N/A**
- Bazel version (if compiling from source): **3.10** (installed via `sudo apt install bazel-3.10`)
- GCC/Compiler version (if compiling from source): **gcc 7.5.0**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **Vivante GC7000Lite, ~1GB**

**Describe the current behavior**

When attempting to run a C++ program linked against `libtensorflowlite_gpu_delegate.so`, an EGLDisplay is
not properly assigned nor initialized, thus the overall gpu-delegate fails to run.

This is the pertinent error message:
```
EGL: Warning: No default display support on wayland
ERROR: TfLiteGpuDelegate Init: eglGetDisplay returned nullptr
```
which I believe is generated via [line 35 of egl_environment.cc](https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/lite/delegates/gpu/gl/egl_environment.cc#L35)

**Describe the expected behavior**

The Coral Dev Board runs Mendel Linux, which as I understand it runs the Wayland compositor.  Thus _I believe_
`wl_display_connect()` (and possibly other functions) must be called to properly initialize EGL
within the TensorFlow Lite gpu-delegate.

**Standalone code to reproduce the issue**
The following code specifically shows the above error:
```
#include <stdio.h>
#include <assert.h>
#include <math.h>

#include <EGL/egl.h>
#include <EGL/eglext.h>

// gcc simple-egl.cpp -lEGL -lGLESv2 -o simple-egl-display
    
int main(int argc, char *argv[]) {

    EGLDisplay display;
    EGLSurface surface;
    EGLContext context;
    EGLConfig config;
    EGLBoolean result;

    display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    
    if (display == EGL_NO_DISPLAY) {
        fprintf(stderr, "EGL_NO_DISPLAY...\n");
        return 1;
    } 

    // initialize the EGL display connection
    result = eglInitialize(display, NULL, NULL);
    
    if (result == EGL_FALSE) {
        fprintf(stderr, "Cannot initialize EGL via the default display...\n");
        return 1;
    }        
    return 0;
}   
```
Versus this simple program with Wayland support:
```
#include <stdio.h>
#include <assert.h>
#include <math.h>

#include <EGL/egl.h>
#include <EGL/eglext.h>

#include <errno.h>
#include <cstring>
#include <wayland-egl.h>

// gcc simple-egl.cpp -lEGL -lGLESv2 -lwayland-egl -lwayland-client -o simple-egl-display

int main(int argc, char *argv[]) {

    EGLNativeDisplayType egl_native_display;
    EGLDisplay egl_display_wayland;
    EGLint major_version, minor_version;

    EGLDisplay display;
    EGLSurface surface;
    EGLContext context;
    EGLConfig config;
    EGLBoolean result;

    display = eglGetDisplay(EGL_DEFAULT_DISPLAY);

    if (display == EGL_NO_DISPLAY) {
        printf("EGL NO DISPLAY (Wayland support?)\n");
        //return 1;
    } else {

        // initialize the EGL display connection
        result = eglInitialize(display, NULL, NULL);

        if (result == EGL_FALSE) {
            fprintf(stderr, "Can't initialise EGL via the default display...\n");
            // return 1;
        }
    }

    // Requires wayland
    egl_native_display = EGLNativeDisplayType(wl_display_connect(NULL));
    if (egl_native_display == NULL) {
        printf("wl_display_connect failed: %s\n", strerror(errno));
        return 1;
    } else {

        // Now initialize EGL
        egl_display_wayland = eglGetDisplay(egl_native_display);

        if (egl_display_wayland == EGL_NO_DISPLAY){
            printf("Could not obtain EGL display (wayland)\n");
            return 1;
        }

        if (!eglInitialize(egl_display_wayland, &major_version, &minor_version))
        {
            printf("Could not initialize EGL (wayland)");
            egl_display_wayland = EGL_NO_DISPLAY;
            return 1;
        }
    }
    return 0;
}
```

**Comment by impjdi** [comment]
@jfinken Linux-based GPU support is still experimental, and we can't accommodate all Linux-based platforms due to limited resources and testing. However, if there are simple fixes to improve the support story, without requiring API changes, then pull requests are welcome.

**Comment by jfinken** [comment]
@impjdi Understood, _many_ thanks for the reply.  If I am able to make progress with simple fixes to potentially improve general GPU support under linux I'll definitely submit a PR.  Thanks again.

**Comment by Saduf2019** [comment]
@jfinken 
Is this still an issue, could you please verify on latest tf and let us know.

**Comment by jfinken** [comment]
I'll certainly take a look.  Do you have a TF commit or tag that I should target?  Thanks.

**Comment by sushreebarsa** [comment]
@jfinken 
It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable version of TF (2.4.1 or 2.5) and let us know if the issue still persists? Thanks!
