### ISSUE TITLE
Commit broke keras.

### ISSUE THREAD

**Issue by baregawi** [tensorflow/tensorflow#4616]
I'm running `Ubuntu 14.04.5 LTS` with `tensorflow==0.10.0` and `keras==1.1.0`.
```
ls -la /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug  3 10:55 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug  3 10:55 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug  3 10:55 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug  3 10:55 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug  3 10:55 /usr/local/cuda/lib64/libcudart_static.a
```

After installing tensorflow from source on an EC2 machine and attempting to import keras, I recieved an `AttributeError: module 'tensorflow.python' has no attribute 'control_flow_ops'` error. The same error mentioned in: https://github.com/fchollet/keras/issues/3857. I noticed that after this tensorflow commit: https://github.com/tensorflow/tensorflow/commit/5563229b5b45917cd8155bc47a8356af90fb20a2#diff-6ad579dc34adb7a581b8c0bcb1a4dd79

that `tensorflow.python.control_flow_ops` was no longer accessible and thus is what is breaking the code. I got around it by doing `from tensorflow.python.ops import control_flow_ops`.

Should I submit a pull request to keras or does tensorflow have a plan to fix this issue?

**Comment by concretevitamin** [comment]
@drpngx - Can you take a look at this?  Thanks.

**Comment by vrv** [comment]
We probably want to have them access our code via tf.cond, I've commented on that other bug.  importing the internal module is bypassing the public interface, sadly.
