### ISSUE TITLE
Missing header when building Android CMake TF Lite 2.4 

### ISSUE THREAD

**Issue by matthewn4444** [tensorflow/tensorflow#46164]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: git/source
- Bazel version (if compiling from source):3.1.0 (not used)
- GCC/Compiler version (if compiling from source): clang 12.0.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A, 32GB ram

I am not sure but I think the tensorflow 2.4 branch is missing the file `tensorflow/lite/delegates/gpu/cl/serialization_generated.h`?

Following steps from https://www.tensorflow.org/lite/guide/build_cmake I get the error messages

```
gmake[2]: *** [CMakeFiles/tensorflow-lite.dir/build.make:960: CMakeFiles/tensorflow-lite.dir/delegates/gpu/cl/kernels/softmax1x1.cc.o] Error 1
gmake[2]: *** [CMakeFiles/tensorflow-lite.dir/build.make:895: CMakeFiles/tensorflow-lite.dir/delegates/gpu/cl/kernels/relu.cc.o] Error 1
1 warning and 1 error generated.
In file included from /Users/mng/Repositories/tensorflow/tensorflow/lite/delegates/gpu/cl/kernels/softmax.cc:16:
In file included from /Users/mng/Repositories/tensorflow/tensorflow/lite/delegates/gpu/cl/kernels/softmax.h:20:
In file included from /Users/mng/Repositories/tensorflow/tensorflow/lite/delegates/gpu/cl/kernels/gpu_operation.h:22:
In file included from /Users/mng/Repositories/tensorflow/tensorflow/lite/delegates/gpu/cl/arguments.h:24:
/Users/mng/Repositories/tensorflow/tensorflow/lite/delegates/gpu/cl/gpu_object.h:26:10: fatal error:
      'tensorflow/lite/delegates/gpu/cl/serialization_generated.h' file not found
#include "tensorflow/lite/delegates/gpu/cl/serialization_generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

And many others. On master I can see the header exist, I assume the CMakeLists file isn't downloading or generating this file on compilation.

**Comment by terryheo** [comment]
OpenCL support is only enabled on master (r2.5)

https://www.tensorflow.org/lite/guide/build_cmake#opencl_gpu_delegate
