### ISSUE TITLE
train_on_batch is much slower than custom training loop on GPU

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#46165]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: Colab
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Colab
- GPU model and memory: Colab

**Describe the current behavior**

On Colab, `train_on_batch` is 3 times slower than custom training loop on GPU

**Describe the expected behavior**

Should be comparable.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1s6O4MyfqyCFI8uEM6JlTVNF18BLvYfka?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to

I think it's because `train_on_batch` uses `tf.data.Dataset`, which places tensor on CPU, on all kinds of input. The data transfer cost from host to device is not negligible resulting in slow down.

**Comment by amahendrakar** [comment]
Running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/a9a1a86c627a985d7bf219a2ae2289be/46165-2-3.ipynb#scrollTo=5dIEuEZDHA11) throws an error stating `TypeError: minimize() got an unexpected keyword argument 'tape'`.

Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/0fa486f44eb9aa0a385c2813ed3f2537/46165.ipynb).

Whereas with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/37e884a75bd1538610e9461f7f81e683/46165-2-5.ipynb), the code runs on CPU and takes almost the same time. Please check the linked gist for reference. Thanks!

**Comment by gadagashwini** [comment]
Hi @WindQAQ, I tested given code on Tensorflow v2.8.2 with CUDA 11. Looks like performance was improved. train_on_batch on GPU is much faster than CPU. Please take a look at gist [here](https://colab.research.google.com/drive/1Vzc1RCM9wk9mfM6OmBfmiWJnL8RPduam?usp=sharing). Thank you!
