### ISSUE TITLE
TFX ML Metadata storage to PostgreSQL

### ISSUE THREAD

**Issue by cah-aswini-jalla** [tensorflow/tensorflow#46176]
I wanted to store my metadata information of ML artifacts to PostgreSQL but I couldn't find any libraries that support MLMD for PostgreSQL. Is there any API's that could support to PostgreSQL other than MySQL/SQLite?

**Comment by rmothukuru** [comment]
@cah-aswini-jalla,
This issue is not related to Tensorflow but it is related to `ML Metadata` and `PostgreSQL`. Please raise the issue in the respective Repository so that it will be looked into by the appropriate Engineers. Thanks!
