### ISSUE TITLE
AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7fdb3138d5f8>>

### ISSUE THREAD

**Issue by zyberg2091** [tensorflow/tensorflow#46177]
**System information**
- TensorFlow installed from (source or binary): Hosted on colab server
- TensorFlow version (use command below): TF 4.0
- Python version: 3.6.9 (Latest version Hosted on google colab)  
- CUDA/cuDNN version:
- GPU model and memory:

Tue Jan  5 14:24:33 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    62W / 149W |   2206MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

### Current behavior

WARNING:tensorflow : AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7fdb3138d5f8>> and will run it as-is.

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.

Cause: <cyfunction Socket.send at 0x7fdb48bd4e58> is not a module, class, method, function, traceback, frame, or code object
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING: AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7fdb3138d5f8>> and will run it as-is.

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.

Cause: <cyfunction Socket.send at 0x7fdb48bd4e58> is not a module, class, method, function, traceback, frame, or code object
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
The parameters `output_attentions`, `output_hidden_states` and `use_cache` cannot be updated when calling a model.They have to be set to True/False in the config object (i.e.: `config=XConfig.from_pretrained('name', output_attentions=True)`).
WARNING:tensorflow:AutoGraph could not transform <function wrap at 0x7fdb465698c8> and will run it as-is.

Cause: while/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
The parameter `return_dict` cannot be set in graph mode and will always be set to `True`.
WARNING: AutoGraph could not transform <function wrap at 0x7fdb465698c8> and will run it as-is.

Cause: while/else statement not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Describe the expected behavior**

This warning is preventing to use AutoGraph but i think execution could be faster if it generates a tensorflow graph to run the code.

**Comment by zyberg2091** [comment]
well after exploring a little bit I have used tf-nightly but same response is generated. I tried to collect the log files by changing verbosity of the autograph but still no identification of this warning. If in past this issue has been explained/solved please mention it here because i couldn't find one.

**Comment by amahendrakar** [comment]
@zyberg2091,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here. Alternatively, you can share the Colab notebook you are running.

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/45354#issuecomment-740039243) from a similar issue and check if it helps. Thanks!

**Comment by zyberg2091** [comment]
Stand alone code to reproduce the warning : Tensorflow version (TF 4.0)

https://colab.research.google.com/drive/1N-rSuvqD8hoM3_wh7HLQQfdB52jvuv_E#scrollTo=GzRZfBxlPHvf

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5962f4656dfed02cfb0a8d4495c0ad01/46177.ipynb). Thanks!

**Comment by neel04** [comment]
@amahendrakar @ymodak I am having the same problem. Any idea on how I can solve it?

**Comment by mdanatg** [comment]
It appears that transformers is using some extensions that aren't compatible with autograph. At any rate, transformer itself should still be compatible with tracing, which still runs in graph mode. So I recommend writing something like this, which should be enough to clear the autograph warnings without other issues:

```
@tf.autograph.experimental.do_not_convert
def run_trace_only(bert_base_model, input_word_ids):
    return bert_base_model(input_word_ids)[0]

def custom_model(bert_base_model):
    input_word_ids = Input(shape=(200,), dtype=tf.int32)
    sequence_output = run_trace_only(bert_base_model, input_word_ids)
    ...
```

After running it that way, I see two other warnings remaining, which might be explained by the transformers documentation.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/7dd26433f06d99d2f027fdadf586c3cf/untitled162.ipynb?authuser=1)..Thanks !

**Comment by mohantym** [comment]
Hi @zyberg2091 ! This issue is not replicating in [2.8](https://colab.research.google.com/gist/mohantym/cc1bdfa18c81425a1894843a27986552/untitled162.ipynb?authuser=1#scrollTo=T2xB5gdWuOdp) version. Can we close this issue now?
