### ISSUE TITLE
 AttributeError: module 'tensorflow' has no attribute 'data'

### ISSUE THREAD

**Issue by mbhoshen** [tensorflow/tensorflow#46175]
Installing on a Windows 10 PC using CPU (no GPU)
Working in an Anaconda environment

Have previously used TF 1.5, but now for NLP work I needed to move to the new generation

I am using Python 3.6 installed tensorflow 2.2. Received the same issue with tensorflow 2.1

Running the line:
text_ds = tf.data.Dataset.from_tensor_slices(train_samples).batch(128)

I get:
**_**Traceback (most recent call last):

  File "<ipython-input-34-3c9c34f69f7e>", line 2, in <module>
    text_ds = tf.data.Dataset.from_tensor_slices(train_samples).batch(128)

AttributeError: module 'tensorflow' has no attribute 'data'**_**

AttributeError: module 'tensorflow' has no attribute 'data'

It looks like an installation program, so I reinstalled, using different versions. Any help much appreciated

(tensorflow2) C:\Users\mehes>conda list
# packages in environment at C:\Users\mehes\Anaconda3\envs\tensorflow2:
#
# Name                    Version                   Build  Channel
_tflow_select             2.2.0                     eigen
absl-py                   0.11.0           py36ha15d459_0    conda-forge
aiohttp                   3.7.3            py36h68aa20f_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astroid                   2.4.2            py36h9f0ad1d_1    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py36h779f372_1    conda-forge
black                     20.8b1                     py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py36hc753bc4_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
certifi                   2020.12.5        py36ha15d459_0    conda-forge
cffi                      1.14.4           py36he58ceb7_1    conda-forge
chardet                   3.0.4           py36hd36e781_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.3.1            py36he58ceb7_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py36ha15d459_2    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    3.8.4                      py_0    conda-forge
future                    0.18.2           py36ha15d459_2    conda-forge
gast                      0.2.2                      py_0    conda-forge
google-auth               1.24.0             pyhd3deb0d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.34.0           py36h4374274_0    conda-forge
h5py                      3.1.0           nompi_py36hf359dfe_100    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1113    conda-forge
helpdev                   0.7.1              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
idna_ssl                  1.1.0           py36h9f0ad1d_1001    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.3.0            py36ha15d459_2    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.4.2            py36h7b7c402_0    conda-forge
ipython                   7.16.1           py36h7b2dad6_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py36ha15d459_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.7.0            py36ha15d459_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
keyring                   21.8.0           py36ha15d459_0    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.4.3            py36h779f372_2    conda-forge
libblas                   3.9.0                     6_mkl    conda-forge
libcblas                  3.9.0                     6_mkl    conda-forge
libclang                  11.0.0          default_h5c34c98_2    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
liblapack                 3.9.0                     6_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libprotobuf               3.14.0               h7755175_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py36hc753bc4_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36h68aa20f_1002    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 5.1.0            py36h68aa20f_0    conda-forge
mypy_extensions           0.4.3            py36ha15d459_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py36ha15d459_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
numpy                     1.14.5                   pypi_0    pypi
numpydoc                  1.1.0                      py_1    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandoc                    2.11.3.2             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py36hd36e781_3    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
protobuf                  3.14.0           py36he2d232f_0    conda-forge
psutil                    5.8.0            py36h68aa20f_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pylint                    2.6.0            py36h9f0ad1d_1    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py36h3a74357_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py36ha15d459_6    conda-forge
pyqt-impl                 5.12.3           py36he2d232f_6    conda-forge
pyqt5-sip                 4.19.18          py36he2d232f_6    conda-forge
pyqtchart                 5.12             py36he2d232f_6    conda-forge
pyqtwebengine             5.12.1           py36he2d232f_6    conda-forge
pyreadline                2.1             py36h9f0ad1d_1002    conda-forge
pyrsistent                0.17.3           py36h68aa20f_1    conda-forge
pysocks                   1.7.1            py36hd36e781_2    conda-forge
python                    3.6.12          h39d44d4_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywin32                   228              py36h779f372_0    conda-forge
pywin32-ctypes            0.2.0           py36h9f0ad1d_1002    conda-forge
pyyaml                    5.3.1            py36hc753bc4_1    conda-forge
pyzmq                     20.0.0           py36hb0157bd_1    conda-forge
qdarkstyle                2.8.1              pyhd8ed1ab_2    conda-forge
qt                        5.12.9               h5909a2a_2    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2020.11.13       py36h68aa20f_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rsa                       4.6                pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py36h089df06_2    conda-forge
scipy                     1.5.3            py36h7ff6e69_0    conda-forge
setuptools                49.6.0           py36hd36e781_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.4.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.2.1            py36ha15d459_0    conda-forge
spyder-kernels            1.10.1           py36ha15d459_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
tensorboard               2.1.1                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0              pyh9f0ad1d_0    conda-forge
tensorflow                2.1.0           eigen_py36hdbbabfe_0
tensorflow-base           2.1.0           eigen_py36h49b2757_0
tensorflow-estimator      2.1.0                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
testpath                  0.4.4                      py_0    conda-forge
textdistance              4.2.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py36h68aa20f_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typed-ast                 1.4.2            py36h68aa20f_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.1            py36h003fed8_1    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
watchdog                  1.0.2            py36ha15d459_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py36h9f0ad1d_1    conda-forge
wincertstore              0.2             py36h9f0ad1d_1005    conda-forge
wrapt                     1.11.2           py36h779f372_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
yarl                      1.6.3            py36h68aa20f_0    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge

**Comment by ravikyram** [comment]
@mbhoshen 

Please, refer the [link](https://stackoverflow.com/questions/47143289/tensorflow-attributeerror-module-object-has-no-attribute-data),#34547 and see if it helps you.
If the issue still persists please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment]
@mbhoshen 

Did you try with Latest stable TF version 2.4 ot nightly version and see if you are facing the same issue?

It will be great if you share sample data to reproduce the issue in our environment. It helps us in debugging the issue faster.Thanks!

**Comment by mbhoshen** [comment]
Thanks
I now used the nightly and it seems to work fine. It seems the problem was
with versions 2.1 and 2.2. It is not data dependent, but rather with the
installation itself, as the problem arose before loading my data

בתאריך יום ד׳, 6 בינו׳ 2021, 08:17, מאת ravikyram ‏<notifications@github.com

**Comment by ravikyram** [comment]
@mbhoshen 

Please, close this thread as this issue was resolved in recent TF versions. Thanks!

**Comment by mbhoshen** [comment]
Will do, thanks!

בתאריך יום ד׳, 6 בינו׳ 2021, 10:27, מאת ravikyram ‏<notifications@github.com
