### ISSUE TITLE
Failed to build tensorflow 2.3.0 from source on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by minhduc66532** [tensorflow/tensorflow#46174]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetpack 4.4 (Ubuntu 18.04 LTS)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 2.7.17 and 3.6.9
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): Build label: 3.1.0- (@non-git)
- GCC/Compiler version (if compiling from source): (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: 10.2.89 / 8.0.0.180
- GPU model and memory: Nvidia Jetson Nano

**Describe the problem**

ERROR: /home/minhduc/src/tensorflow-2.3.0/tensorflow/core/kernels/BUILD:6109:1: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed (Exit 4)
aarch64-linux-gnu-gcc-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow:libtensorflow.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10499.940s, Critical Path: 654.48s
INFO: 5016 processes: 5016 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed this [tutorial](https://jkjung-avt.github.io/build-tensorflow-2.0.0/) ([github](https://github.com/jkjung-avt/jetson_nano)). I set up my virtual screen, start the build (NOT install) script (build_libtensorflow-2.3.0.sh). Go to school and come back home with the error log above

**Any other info / logs**
I also install both protobuf 3.8.0 and bazel using shell scripts from the above github repo

**Comment by amahendrakar** [comment]
@minhduc66532,
TensorFlow v2.3 is compatible with CUDA 10.1 and cuDNN 7.6. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).

Also, please follow the [official guide](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110) while building TensorFlow from source and check if you are facing the same issue. Thanks!

**Comment by minhduc66532** [comment]
I have downgraded Jetpack 4.4 to Jetpack 4.3

![image](https://user-images.githubusercontent.com/66398066/103753111-36599600-503d-11eb-9c2a-b1597d2118fc.png)

Still the getting error:
```
ERROR: /home/minhduc/src/tensorflow-2.3.0/tensorflow/core/kernels/BUILD:2828:1: C++ compilation of rule '//tensorflow/core/kernels:padding_fifo_queue' failed (Exit 4)
aarch64-linux-gnu-gcc-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/lib_package:libtensorflow failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9190.224s, Critical Path: 1217.73s
INFO: 5456 processes: 5456 local.
FAILED: Build did NOT complete successfully
```

**Comment by amahendrakar** [comment]
@minhduc66532,
Now you have CUDA 10.0 with cuDNN 7.6, which is not compatible with any of the TensorFlow 2.x versions. As shown in the table below, please try building either 

TF v2.4 with CUDA 11.0 and cuDNN 8 

or

TF v2.3 with CUDA 10.1 and cuDNN 7.6


 
Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0 | 7.6 | 10.1
tensorflow-2.1.0 | 2.7, 3.5-3.7 | GCC 7.3.1 | Bazel 0.27.1 | 7.6 | 10.1
tensorflow-2.0.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1 | 7.4 | 10.0

Thanks!

**Comment by minhduc66532** [comment]
Wow, so it has to be EXACTLY cudnn 7.6.0 and CUDA 10.1 ? Ok i'm gonna try again tomorrow and report the result

**Comment by minhduc66532** [comment]
Problem solved. This [guy ](https://qengineering.eu/install-tensorflow-2.3.1-on-jetson-nano.html) already built it on Jetpack 4.4 you can just download and use it.
And fun fact Jetpack 4.4 is using CUDA 10.2 and cuDnn 8.0. But anyway thank you for answering all of my question, really appreciated it. Have a great day
