### ISSUE TITLE
Though EXTERNAL delegate is explicitly applied, the model will not be executed by the delegate

### ISSUE THREAD

**Issue by keidav01** [tensorflow/tensorflow#46170]
Apologies if this is in the incorrect category, but is more clarification that I am looking for rather than an issue with the implemented code. 

**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.1 LTS**
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): **Source**
TensorFlow version (use command below): **v2.3.1**
Python version: N/A
Bazel version (if compiling from source): **3.1.0**
GCC/Compiler version (if compiling from source): **6.3.0**
CUDA/cuDNN version: N/A
GPU model and memory: N/A

**Describe the current behavior**

I'm currently looking into benchmarking a custom delegate against XNNPACK. I've done so through the second option specified in the tensorflow documentation (using the external delegate options within the benchmark tool). 

I downloaded the binary for the benchmarking tool itself here (linux aarch64) rather than building source: https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

When I run the benchmarking tool for the custom delegate, I get the info message specified in the title: 
_"Though EXTERNAL delegate is explicitly applied, the model will not be executed by the delegate"_

I'm not sure what this is telling me. I've looked through the the tensorflow codebase and, from where I've looked, these output messages are no where in **_tensorflow/tensorflow/lite_**. Going up a level or two, I still can't find anything of similar. 

When running with xnnpack set to true, I get the output message _**"Explicitly applied XNNPACK delegate, and the model graph will be partially executed by the delegate w/ 4 delegate kernels."**_. This is a little more self explanatory, and I can see that some of the code for this message was generated at tensorflow/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc:666.

I added some debug information within the custom delegate and I can see that, when running the benchmark_model tool, I am creating the optimized delegate graph I expect. I am also seeing the numbers that I expect to see for the benchmarking against XNNPACK.

However, the message seems to make it out as if the custom delegate has been created, but is not used during the benchmarking. Is this true? I would appreciate any clarity at your earliest convenience. Thank you!

**Comment by keidav01** [comment]
Bump on this. I could really do with some information today if at all possible

**Comment by multiverse-tf** [comment]
> Apologies if this is in the incorrect category, but is more clarification that I am looking for rather than an issue with the implemented code.
> 
> **System information**
> 
> Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
> OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.1 LTS**
> Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
> TensorFlow installed from (source or binary): **Source**
> TensorFlow version (use command below): **v2.3.1**
> Python version: N/A
> Bazel version (if compiling from source): **3.1.0**
> GCC/Compiler version (if compiling from source): **6.3.0**
> CUDA/cuDNN version: N/A
> GPU model and memory: N/A
> 
> **Describe the current behavior**
> 
> I'm currently looking into benchmarking a custom delegate against XNNPACK. I've done so through the second option specified in the tensorflow documentation (using the external delegate options within the benchmark tool).
> 
> I downloaded the binary for the benchmarking tool itself here (linux aarch64) rather than building source: https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary
> 
> When I run the benchmarking tool for the custom delegate, I get the info message specified in the title:
> _"Though EXTERNAL delegate is explicitly applied, the model will not be executed by the delegate"_

I believe this means the external delegate is applied successfully based on the return value of ModifyGraphWithDelegate invoke, however, no ops in the TFLite model graph are found that could be delegated by this EXTERNAL delegate.

> 
> I'm not sure what this is telling me. I've looked through the the tensorflow codebase and, from where I've looked, these output messages are no where in **_tensorflow/tensorflow/lite_**. Going up a level or two, I still can't find anything of similar.

The above error message is emitted from this part: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L626-L659

> 
> When running with xnnpack set to true, I get the output message _**"Explicitly applied XNNPACK delegate, and the model graph will be partially executed by the delegate w/ 4 delegate kernels."**_. This is a little more self explanatory, and I can see that some of the code for this message was generated at tensorflow/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc:666.
> 
> I added some debug information within the custom delegate and I can see that, when running the benchmark_model tool, I am creating the optimized delegate graph I expect. I am also seeing the numbers that I expect to see for the benchmarking against XNNPACK.
> 
> However, the message seems to make it out as if the custom delegate has been created, but is not used during the benchmarking. Is this true? I would appreciate any clarity at your earliest convenience. Thank you!

**Comment by keidav01** [comment]
Thank you very much for the response - I appreciate it.

Could you tell me is there somewhere I can download a specific version of the benchmark_model tool? I downloaded from here: 
https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

But I have a mismatch on tensorflow versioning, which may or may not be interfering with the logging that I am supposed to be getting. My tensorflow version is 2.3.1, whereas the benchmark_tool is nightly of course

**Comment by multiverse-tf** [comment]
> Thank you very much for the response - I appreciate it.
> 
> Could you tell me is there somewhere I can download a specific version of the benchmark_model tool? I downloaded from here:
> https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary
> 

Acked. Which version (like the date of the binary was built) do you want to download? Such pre-built binaries were only enabled  recently. So, I'm not sure whether we will have the version you'd like to use.

> But I have a mismatch on tensorflow versioning, which may or may not be interfering with the logging that I am supposed to be getting. My tensorflow version is 2.3.1, whereas the benchmark_tool is nightly of course

Acked. Could you build (or backport) the benchmark_tool with your repo? Or update the EXTERNAL delegate w/ latest TF repo?

**Comment by keidav01** [comment]
We are currently looking into building the benchmark_model tool with our repo, however building with bazel can be quite tedious with our codebase. So that's a process underway. 

Also, in relation to updating TF, we recently updated the external delegate and the rest of the code base to 2.3.1. It is a relatively lengthy process to align our code so unfortunately it is not possible under my time constraint.

No worries, ideally I could have the latest binary that aligned with the tensorflow 2.3.1 release, which appears to be this commit from the **21st September 2020 at 18:57pm** fcc4b966f1265f466e82617020af93670141b009 (HEAD, tag: v2.3.1).

Thank you

**Comment by multiverse-tf** [comment]
> We are currently looking into building the benchmark_model tool with our repo, however building with bazel can be quite tedious with our codebase. So that's a process underway.

Acked. An alternative to bazel might be backporting [TFLite's CMake support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/build_cmake.md#step-6-build-tensorflow-lite-benchmark-tool) to your repo?
> 
> Also, in relation to updating TF, we recently updated the external delegate and the rest of the code base to 2.3.1. It is a relatively lengthy process to align our code so unfortunately it is not possible under my time constraint.
> 
> No worries, ideally I could have the latest binary that aligned with the tensorflow 2.3.1 release, which appears to be this commit from the **21st September 2020 at 18:57pm** [fcc4b96](https://github.com/tensorflow/tensorflow/commit/fcc4b966f1265f466e82617020af93670141b009) (HEAD, tag: v2.3.1).

The closest one I could find is this [one](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_aarch64_benchmark_model).

> 
> Thank you

**Comment by keidav01** [comment]
Thank you for all the information. It was really helpful!

We have managed to build on x86 and can clarify that the peculiar message observed was due to the mismatch in tensorflow versions from the binary vs. our tensorflow source

**Comment by keidav01** [comment]
> Acked. An alternative to bazel might be backporting [TFLite's CMake support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/build_cmake.md#step-6-build-tensorflow-lite-benchmark-tool) to your repo?
> 
> The closest one I could find is this [one](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_aarch64_benchmark_model).

Could I please get the android arm 64 version of this as well please?

**Comment by multiverse-tf** [comment]
> > Acked. An alternative to bazel might be backporting [TFLite's CMake support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/build_cmake.md#step-6-build-tensorflow-lite-benchmark-tool) to your repo?
> > The closest one I could find is this [one](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_aarch64_benchmark_model).
> 
> Could I please get the android arm 64 version of this as well please?

The above one is built for android arm64. Did you mean 32bit? Then it's this [link](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_arm_benchmark_model). Based on the URL, I guess one could spot the pattern.

**Comment by keidav01** [comment]
Oh sorry apologies - I meant linux aarch64

**Comment by multiverse-tf** [comment]
> > > Acked. An alternative to bazel might be backporting [TFLite's CMake support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/build_cmake.md#step-6-build-tensorflow-lite-benchmark-tool) to your repo?
> > > The closest one I could find is this [one](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_aarch64_benchmark_model).
> > 
> > 
> > Could I please get the android arm 64 version of this as well please?
> 
> The above one is built for android arm64. Did you mean 32bit? Then it's this [link](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/android_arm_benchmark_model). Based on the URL, I guess one could spot the pattern.



> Oh sorry apologies - I meant linux aarch64

NP. [Here](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/lite/release/tools/nightly/41/20200921-215507/linux_aarch64_benchmark_model) you go.

**Comment by keidav01** [comment]
Thank you! Could you tell me which revision that is based on as well please?

**Comment by multiverse-tf** [comment]
> Thank you! Could you tell me which revision that is based on as well please?

It's based on https://github.com/tensorflow/tensorflow/commit/1a2b1d0ae199dd328bff8eb6c6dfb74ac8b79c61

**Comment by keidav01** [comment]
Great thanks

**Comment by FinnWilliamsArm** [comment]
Hi there,

We looked a bit more into this issue and it seems at this point:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L631

delegate.get() is returning the address of the ExternalDelegateWrapper rather than the external delegate itself,
where as node.delegate correctly contains the address of the external delegate.

This mismatch is then causing the benchmark_model to believe the delegate isn't doing anything.

**Comment by keidav01** [comment]
Reopening due to Finn's comment

**Comment by multiverse-tf** [comment]
> Hi there,
> 
> We looked a bit more into this issue and it seems at this point:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L631
> 
> delegate.get() is returning the address of the ExternalDelegateWrapper rather than the external delegate itself,
> where as node.delegate correctly contains the address of the external delegate.
> 
> This mismatch is then causing the benchmark_model to believe the delegate isn't doing anything.

Acked. Is it possible that your "external delegate" has a different implementation from the semantics of the external delegate that could be consumed by the benchmark model tool (including other TFLite tools and unit tests)? Could you share how is your external delegate is implemented? 

Note that we have a simple ["external delegate" example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/utils/dummy_delegate/external_delegate_adaptor.cc) that we believe could be successfully applied in the tooling as described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/utils/dummy_delegate/README.md#option-2-utilize-tensorflow-lite-external-delegate). Meanwhile, I'll look into this "mismatch" issue w.r.t. "external delegate" with a more sophisticated example.

**Comment by FinnWilliamsArm** [comment]
Thank you for the response, the header file we are using is here: https://review.mlplatform.org/c/ml/armnn/+/4728/6/delegate/src/armnn_external_delegate.cpp
It has the same function signature as the example you linked, from our own tests the delegate is working normally with the exception of this message.

**Comment by multiverse-tf** [comment]
> Thank you for the response, the header file we are using is here: https://review.mlplatform.org/c/ml/armnn/+/4728/6/delegate/src/armnn_external_delegate.cpp
> It has the same function signature as the example you linked, from our own tests the delegate is working normally with the exception of this message.

Thx for providing this info! After looking into the issue with a more sophisticated example, I did see there's a problem as you mentioned earlier. We will get this fixed asap.

**Comment by multiverse-tf** [comment]
> > Thank you for the response, the header file we are using is here: https://review.mlplatform.org/c/ml/armnn/+/4728/6/delegate/src/armnn_external_delegate.cpp
> > It has the same function signature as the example you linked, from our own tests the delegate is working normally with the exception of this message.
> 
> Thx for providing this info! After looking into the issue with a more sophisticated example, I did see there's a problem as you mentioned earlier. We will get this fixed asap.



> > Thank you for the response, the header file we are using is here: https://review.mlplatform.org/c/ml/armnn/+/4728/6/delegate/src/armnn_external_delegate.cpp
> > It has the same function signature as the example you linked, from our own tests the delegate is working normally with the exception of this message.
> 
> Thx for providing this info! After looking into the issue with a more sophisticated example, I did see there's a problem as you mentioned earlier. We will get this fixed asap.

After digging into the code, I think the output message "Though EXTERNAL delegate is explicitly applied, the model will not be executed by the delegate" is likely a false alarm here. Basically, when checking how many delegate kernels have been created by a delegate, the benchmark model tool compared the pointer of the external delegate wrapper with the pointer of the actual external delegate to tell whether there's a newly created delegate kernel ([code](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L631-L636)). Therefore, even when the actual external delegate is successfully applied, this comparison will return false and miss counting the actually to-be-delegated node.

I've made a fix (which will be checked in soon), and verifies it w/ the xnnpack delegate (but loading it as an external delegate) on the mobilenet-v2 float model. Here's the output I've got, and now you can see the "EXTERNAL" delegate is yielding 1 partition (i.e. one delegate kernel).
"
.....
Graph: [/tmp/m2.tflite]
External delegate path: [/tmp/xnnpack_as_external_delegate.so]
Loaded model /tmp/m2.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 66 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 1 partitions.
Explicitly applied EXTERNAL delegate, and the model graph will be completely executed by the delegate.
......
"

**Comment by FinnWilliamsArm** [comment]
Just tried your patch and it works! Thanks very much for the quick fix :)
