### ISSUE TITLE
sparse lookup tables for tf.nn.embedding_lookup_sparse

### ISSUE THREAD

**Issue by cherishlc** [tensorflow/tensorflow#4617]
Hope that “**params**” of **tf.nn.embedding_lookup_sparse** support **SparseTensor**!!!

[tf.nn.embedding_lookup_sparse(params, sp_ids, sp_weights, partition_strategy='mod', name=None, combiner='mean')](https://www.tensorflow.org/versions/r0.10/api_docs/python/nn.html#embedding_lookup_sparse)

The efficiency of sparse lookup tables is low,  but it is very useful for large-scale linear regression system, especially when designing a prototype. 
For example, the wide part of "wide and deep learning" use sparse features.
Although I don't know when the hashing function is applied, using sparse lookup table is more accurate than hashing.  The hashing function may merge two features into one bin (share the same weight), or discard new features when the lookup table is full.

**Comment by tatatodd** [comment]
@concretevitamin might have some thoughts on this.

**Comment by aselle** [comment]
Any update @ebrevdo? If this is not going to happen soon, I plan on closing this pending a more concrete plan here. It's not clear enough to move to contributions welcome.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
