### ISSUE TITLE
Publishing Tensorflow wheel package for s390x architecture

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#46181]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.3.1
- Python version: Python 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):

**Describe the problem**
Currently `pip install tensorflow` command on s390x architecture errors out with `No matching distribution found for tensorflow`.

This happens because there is no corresponding s390x arch wheel available on [PyPI](https://pypi.org/simple/tensorflow/).

I am investigating whether we could push s390x wheel on PyPI and, if so, what are the steps needed.

Nightly/release builds for s390x appear to produce corresponding wheel for s390x as seen [here](https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/lastSuccessfulBuild/artifact/tensorflow_whl/tensorflow-2.5.0-cp36-cp36m-linux_s390x.whl).  There also exists a `Release` Artifact which can contain s390x Tensorflow wheel which can be pushed to PyPI.

Please let me know if/how this can be achieved. I have tried installing the s390x wheel available from the [CI](https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/lastSuccessfulBuild/artifact/tensorflow_whl/tensorflow-2.5.0-cp36-cp36m-linux_s390x.whl) and it appears to have installed on s390x using following commands:
```
apt-get install sudo wget git unzip zip python3-dev python3-pip openjdk-11-jdk pkg-config libhdf5-dev libssl-dev libblas-dev liblapack-dev gfortran cython3 -y
ldconfig
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
pip3 install grpcio
pip3 install numpy wheel scipy portpicker protobuf==3.13.0
wget https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/lastStableBuild/artifact/tensorflow_whl/tensorflow-2.5.0-cp36-cp36m-linux_s390x.whl
pip3 install tensorflow-2.5.0-cp36-cp36m-linux_s390x.whl
```
Thanks.

**Comment by mihaimaruseac** [comment]
This cannot be done by Google team as we lack headcount for support. Instead, it can be done via SIG Build, as a different project.

**Comment by rposts** [comment]
Thanks @mihaimaruseac - I presume [this](https://github.com/tensorflow/build) is what we are referring to.

**Comment by mihaimaruseac** [comment]
Yep, that's correct.
