### ISSUE TITLE
Add `.bazelrc` to `.gitignore`

### ISSUE THREAD

**Issue by vnvo2409** [tensorflow/tensorflow#46196]
**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, we use `configure.py` for modifying `.bazelrc`, I think we should add `.bazelrc` to `.gitignore` and use `configure.py` for completely generating `bazelrc` from scratch. Afterward, we could add our own config to `.bazelrc` without any conflict with the upstream ( I usually add `build:asan ----copt=-fsanitize=address --linkopt=-fsanitize=address` ). Furthermore, we could generate a platform-specific `.bazelrc` using `python` ( which is good, I think ).

**Will this change the current api? How?** Nothing

**Who will benefit with this feature?** TensorFlow developers.

/cc: @mihaimaruseac

**Comment by vnvo2409** [comment]
I just read `.bazelrc` again and see that we could add custom config by `.bazelrc.user`. Close

**Comment by mihaimaruseac** [comment]
We are also moving away from running configure.py, especially in automated setups. This entails having `.bazelrc` and similar being synced with the repo.
