### ISSUE TITLE
Failed invoke tflite model in swift code(Provided data count 18181 must match the required count 4536.)

### ISSUE THREAD

**Issue by manosh7n** [tensorflow/tensorflow#46199]
**System information**
- OS Platform): macOS 11.1
- TensorFlow version: 2.4.0

Input shape of my tflite model - (18, 63) or 1134 float numbers.

I get the data itself in objective-c code, and then I send it to swift code and an error already occurs there. In detail I do the following

1. Receive the data in NSMutableArray. The length of the array is 1134 NSNumber
2. Converting NSMutableArray to NSData
```
NSData *d = [NSKeyedArchiver archivedDataWithRootObject:_data];
NSLog(@"output: %@", d);
// output: {length = 18181, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 000034fd }
```

3. I send data to the swift code.
```[_model predict:d];```
Swift code:
```
@objc public func predict(_ data: NSData) {
        guard
          let modelPath = Bundle.main.path(forResource: "model", ofType: "tflite")
        else {
            return
        }

        do {
          let interpreter = try Interpreter(modelPath: modelPath)
          try interpreter.allocateTensors()
          let inputData: Data = data as Data

          try interpreter.copy(inputData, toInputAt: 0) // <-- an error occurs in this line

          try interpreter.invoke()
          let outputTensor = try interpreter.output(at: 0)
        } catch {
          print(error)
        }
}
```
4. I get an error in the above line of code. Error:
```Provided data count 18181 must match the required count 4536.```

**Comment by manosh7n** [comment]
My model(here I did with the input size (1134,)):
```
model = Sequential()

model.add(keras.layers.InputLayer(input_shape=(1134,), name="input_1"))
model.add(Dense(1024, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(keras.layers.Dropout(0.35))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam', metrics=['accuracy'])
```
I save the model like this:
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```
the error is the same

**Comment by yyoon** [comment]
Not an ObjC expert myself, but I think you are converting the `NSMutableArray` of `NSNumber`s in an incorrect way.

1. `NSNumber` is an object, which doesn't necessarily have the same in-memory representation as a float number. You should get the float representation by retrieving the `floatValue` property on an `NSNumber` object.
2. `archivedDataWithRootObject` is an encoding method according to the [documentation](https://developer.apple.com/documentation/foundation/nskeyedarchiver/1413189-archiveddatawithrootobject), which complicates the issue even more.

Based on these, I think you should manually convert each element to float in a loop, something like the following (haven't tested this code myself).

```objective-c
int count = [_data count];
int num_bytes = sizeof(float) * count;
float *arr = (float*)malloc(num_bytes);
for (int i = 0; i < count; ++i) {
  arr[i] = [_data[i] floatValue];
}
NSData *d = [NSData dataWithBytesNoCopy:arr length:num_bytes freeWhenDone:YES];
// pass this NSData object to Swift side...
```

Again, I'm not an ObjC expert, so there might be a more efficient way to convert the data.

**Comment by manosh7n** [comment]
Thank you, so the error was really in the wrong conversion. I also wanted to ask you do know how to print prediction?
 I'm trying to ```print(outputTensor)``` But I get:
```
Tensor(name: "Identity", dataType: TensorFlowLite.Tensor.DataType.float32, shape: TensorFlowLite.Tensor.Shape(rank: 2, dimensions: [1, 3]), data: 12 bytes, quantizationParameters: nil)
```

**Comment by manosh7n** [comment]
Figured out the problem. Thank you again

**Comment by lifeMiik** [comment]
> Figured out the problem. Thank you again
Hello, I also encountered this problem. I want to change the width and height of the output image to 500. How can I solve it?
