### ISSUE TITLE
Error in example because of Incomplete API names for tf.keras.experimental.SequenceFeatures

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#46197]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/SequenceFeatures#example

## Description of issue (what needs changing): 
The APIs, **`sequence_numeric_column, sequence_categorical_column_with_identity, embedding_column`**, etc.. are incomplete. Consequently, it is resulting in the error, 

> NameError: name 'sequence_numeric_column' is not defined

It should be **`tf.feature_column.sequence_numeric_column, tf.feature_column.sequence_categorical_column_with_identity, tf.feature_column.embedding_column`**, instead.

Please find the [Github Gist](https://colab.research.google.com/gist/rmothukuru/90002755d1b45f6f94709a9623259d9f/sequencefeatures_error.ipynb).

There is an error in the above [Gist](https://colab.research.google.com/gist/rmothukuru/90002755d1b45f6f94709a9623259d9f/sequencefeatures_error.ipynb) because of **`Ellipsis`** and it is being tracked in #46128.

**Comment by summa-code** [comment]
What do you mean by incomplete API names ?

**Comment by rakeshmothukuru1** [comment]
@summa-code,
By incomplete API names, I mean, using **`sequence_numeric_column`** instead of **`tf.feature_column.sequence_numeric_column`**.

I didn't understand your point,

> You simply dont tag without knowing what is the real error.

I have provided a detailed [Colab Gist](https://colab.research.google.com/gist/rmothukuru/90002755d1b45f6f94709a9623259d9f/sequencefeatures_error.ipynb) demonstrating the errors.

**Comment by summa-code** [comment]
Oh my god, do you even know how python works ? Those are package names. They dont have to necessarily add if you import that. There is nothing wrong in API names. Don't waste our time unnecessarily while we are trying to solve actual bug.

**Comment by rakeshmothukuru1** [comment]
@summa-code,

> Oh my god, do you even know how python works ?

I know how python works but my point is that the Example code in the Documentation should be Executable without many changes from our side. Such a code will be helpful, especially to the Newbies.

For example, [this code](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column#example) uses the complete API name, **`tf.feature_column.numeric_column`**.

So, Please don't overreact. 

> Don't waste our time unnecessarily while we are trying to solve actual bug.

Fixing issues in the documentation is as important as fixing issues in the Code because clearer the documentation is, easier it will be for the Developer Community.

If you feel it's a waste of time, who is forcing you to respond?
