### ISSUE TITLE
 PB to Tflite

### ISSUE THREAD

**Issue by wangzhenyuhadoop** [tensorflow/tensorflow#46192]
import tensorflow as tf

path = 'E:\\Code\\PythonCode\\AliYunCode\\JS-CODE-20210104-1008-CNNX-GRU-H64-CTC-C1_0.pb'

inputs = ["input"]

outputs = ["dense_decoded"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(path, inputs, outputs)

converter.post_training_quantize = True

tflite_model = converter.convert()

open("tiny_160000.tflite", "wb").write(tflite_model)

-----
ERROR:Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, GATHER, LEAKY_RELU, LESS, LOGICAL_AND, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, NOT_EQUAL, RANGE, REDUCE_ANY, RESHAPE, SELECT, SHAPE, SPARSE_TO_DENSE, STRIDED_SLICE, SUB, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, Enter, Exit, LoopCond, Merge, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.

**Comment by abattery** [comment]
I think you need to train model with https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2 since your TF model file is based on the control flow v1 ops, which are not supported by TFLite. 

And there are some TF operators that are not covered by the TensorFlow Lite operator set. You can use the Select TF op option:
https://www.tensorflow.org/lite/guide/ops_select
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by devimonica** [comment]
have you tried using bazel ?

> 
> 
> import tensorflow as tf
> 
> path = 'E:\Code\PythonCode\AliYunCode\JS-CODE-20210104-1008-CNNX-GRU-H64-CTC-C1_0.pb'
> 
> inputs = ["input"]
> 
> outputs = ["dense_decoded"]
> 
> converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(path, inputs, outputs)
> 
> converter.post_training_quantize = True
> 
> tflite_model = converter.convert()
> 
> open("tiny_160000.tflite", "wb").write(tflite_model)
> 
> ERROR:Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, GATHER, LEAKY_RELU, LESS, LOGICAL_AND, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, NOT_EQUAL, RANGE, REDUCE_ANY, RESHAPE, SELECT, SHAPE, SPARSE_TO_DENSE, STRIDED_SLICE, SUB, TANH, TILE, TRANSPOSE, ZEROS_LIKE. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, Enter, Exit, LoopCond, Merge, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
