### ISSUE TITLE
compute gradient error:  'KerasTensor' object has no attribute '_id',   (tensorflow 2.4.0)

### ISSUE THREAD

**Issue by realbns2008** [tensorflow/tensorflow#46194]
Hi, i'm using tensorflow 2.4.0 ,  and want to compute gradients with keras tensor,  but failed.

I'm using python3.8

**Below are the log info:**

Traceback (most recent call last):
  File "demo-resnet-18-v4.py", line 119, in <module>
    cam, heatmap = grad_cam(model, preprocessed_input, predicted_class, "activation_16")
  File "demo-resnet-18-v4.py", line 65, in grad_cam
    grads = gtape.gradient(loss, var_list)
  File "/Users/baonansen/miniconda3/envs/tf2.4/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1080, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/Users/baonansen/miniconda3/envs/tf2.4/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 79, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
AttributeError: 'KerasTensor' object has no attribute '_id'

**below are the code:**

 53 def grad_cam(input_model, image, category_index, layer_name):
 54     with tf.GradientTape() as gtape:
 55         nb_classes = 53
 56         target_layer = lambda x: target_category_loss(x, category_index, nb_classes)
 57         x = Lambda(target_layer, output_shape = target_category_loss_output_shape)(input_model.output)
 58         model = Model(inputs=input_model.input, outputs=x)
 59         model.summary()
 60
 61         loss = K.sum(model.output)
 62         conv_output =  [l for l in model.layers if l.name == layer_name][0].output
 63
 64         var_list = [conv_output]
 65     grads = gtape.gradient(loss, var_list)

**Comment by realbns2008** [comment]
refine the code format:


def grad_cam(input_model, image, category_index, layer_name):
    
    with tf.GradientTape() as gtape:
        nb_classes = 53
        
        target_layer = lambda x: target_category_loss(x, category_index, nb_classes)
        x = Lambda(target_layer, output_shape = target_category_loss_output_shape)(input_model.output)
        
        model = Model(inputs=input_model.input, outputs=x)
        model.summary()

        loss = K.sum(model.output)
        conv_output =  [l for l in model.layers if l.name == layer_name][0].output

        var_list = [conv_output]
    grads = gtape.gradient(loss, var_list)

**Comment by realbns2008** [comment]
by the way: The input model is a resnet model , implemented by tf.keras

**Comment by ravikyram** [comment]
@realbns2008 

Please, share colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by realbns2008** [comment]
> @realbns2008
> 
> Please, share colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

Hi ravikyram, below is the main python code
https://colab.research.google.com/drive/1fZtcnOY7mRMnFHihGsve3jA6RXk05dv-?usp=sharing

**Comment by realbns2008** [comment]
@ravikyram 

here is the link of the model i use:
https://drive.google.com/file/d/1N013WMlgmDYOtblSxcmMGKB1cY3cRsaM/view?usp=sharing

**Comment by ravikyram** [comment]
@realbns2008 

I am not able to reproduce the issue. Please, help me with reproducing the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/86a53142054eec129f25dadd147401db/untitled547.ipynb).Thanks!

**Comment by realbns2008** [comment]
@ravikyram 
Hi, it looks like that the model path is wrong.
did you download the model to path "/content/industry_classifier_v4.h5" ?

**Comment by realbns2008** [comment]
the model link looks fine "https://drive.google.com/file/d/1N013WMlgmDYOtblSxcmMGKB1cY3cRsaM/view?usp=sharing"
I download the model from this link, and test it on my machine, and it reproduce the issue

**Comment by jwallbridge** [comment]
I am getting the same error in Tensorflow 2.4.1 when computing gradients.

Here is a reproducible example of the issue:
https://drive.google.com/file/d/1po6RoHQ_cok64EHXVrOIej1UXNnYsFIy/view?usp=sharing

Any help would greatly appreciated.

**Comment by motionlife** [comment]
Tensorflow 2.4.1 exact same problem

**Comment by Vocco** [comment]
Can confirm, running into the same problem in TF 2.4.1

**Comment by Milloyy** [comment]
I am getting the same error in Keras 2.4.3 and Tensorflow 2.4.1 when computing gradients too.

A line original code in example is: `grads = K.gradients(loss, model.input)[0]`, but it raise RuntimeError while running. And than I replaced it with the following codes:

```python
grads = None
with tf.GradientTape() as gtape:
    grads = gtape.gradient(loss, model.input)[0]
```

The same error appear. The complete code in here:

```python
from keras.applications import VGG16
from keras import backend as K
import tensorflow as tf

model = VGG16(weights='imagenet', include_top=False)

layer_name = 'block3_conv1'
filter_index = 0

layer_output = model.get_layer(layer_name).output
loss = K.mean(layer_output[:, :, :, filter_index])

grads = K.gradients(loss, model.input)[0]

# grads = None
# with tf.GradientTape() as gtape:
#     grads = gtape.gradient(loss, model.input)[0]

grads /= (K.sqrt(K.mean(K.square(grads))) + 1e-5)

iterate = K.function([model.input], [loss, grads])

import numpy as np


loss_value, grads_value = iterate([np.zeros((1, 150, 150, 3))])
input_img_data = np.random.random((1, 150, 150, 3)) * 20 + 128.0

step = 1.0
for i in range(40):
    loss_value, grads_value = iterate([input_img_data])

    input_img_data += grads_value * step


def deprocess_image(x):
    x -= x.mean()
    x /= (x.std() + 1e-5)
    x *= 0.1

    x += 0.5
    x = np.clip(x, 0, 255).astype('uint8')

    return x


def generate_pattern(layer_name, filter_index, size=150):
    layer_output = model.get_layer(layer_name).output
    loss = K.mean(layer_output[:, :, filter_index])

    grads = K.gradients(loss, model.input)[0]

    grads /= (K.sqrt(K.mean(K.square(grads))) + 1e-5)

    iterate = K.function([model.input], [loss, grads])

    input_img_data = np.random.random((1, size, size, 3)) * 20 + 128.0

    step = 1.0
    for i in range(40):
        loss_value, grads_value = iterate([input_img_data])
        input_img_data += grads_value * step

    img = input_img_data
    return deprocess_image(img)


layer_name = 'block1_conv1'
size = 64
margin = 5

results = np.zeros((8 * size + 7 * margin, 8 * size + 7 * margin, 3))

import matplotlib.pyplot as plt


for i in range(8):
    for j in range(8):
        filter_img = generate_pattern(layer_name, i + (j * 8), size=size)

        horizontal_start = i * size + i * margin
        horizontal_end = horizontal_start + size
        vertical_start = j * size + j * margin
        vertical_end = vertical_start + size
        results[horizontal_start: horizontal_end, vertical_start: vertical_end, :] = filter_img

    plt.figure(figsize=(20, 20))
    plt.imshow(results)

plt.show()
```

**Comment by 521125LYAlty** [comment]
I am getting the same error in tensorflow 2.4.1 when computing gradients.

**Comment by WingsOfPanda** [comment]
yes, I am having the same error with 2.4.1.

**Comment by xinluo2018** [comment]
i have the same error with 2.4.1

**Comment by hamedhpajouh** [comment]
same issue! with 2.4.1 any one have suggestion?!

**Comment by rshih32** [comment]
I ran into this problem when trying to run gradients using the functional keras API on 2.4.1
The main difference I see is that the layer outputs are the wrong type in 2.4.1
The solution for now is to downgrade to 2.3.0

See:
```
import tensorflow as tf
import numpy as np
print(tf.__version__)
def funtional_model():
    input_layer = tf.keras.layers.Input(shape=(10,10))
    dense = tf.keras.layers.Dense(5)(input_layer)
    model = tf.keras.Model(input_layer, dense)
    return model
    
functional_model = funtional_model()
print(type(functional_model.get_layer('dense').output))

with tf.GradientTape() as tape:
    outs = functional_model(np.random.rand(2,10))
gradients = tape.gradient(outs[0,0], functional_model.get_layer('input_1').output)
```

in 2.3.0:
```
2.3.0
<class 'tensorflow.python.framework.ops.Tensor'>
```

in 2.4.1/2.4.0:
```
2.4.1
<class 'tensorflow.python.keras.engine.keras_tensor.KerasTensor'>
.
.
.
AttributeError: 'KerasTensor' object has no attribute '_id'
```

**Comment by mechaot** [comment]
same issue here computing gradients on tf.keras.application.VGG16 with 2.4.1

**Comment by pointhex** [comment]
I have the same issue, is someone who has a workaround?

**Comment by qlzh727** [comment]
Adding Tomer who worked on keras_tensor.

**Comment by tomerk** [comment]
Using `tf.GradientTape` as a part of Keras functional model construction is unsupported, and we have no plans on the roadmap to add support for it at this point in time.

If you want your model to produce gradients as outputs (though that does not appear to be the case in the above examples):
Use a subclass model that uses `tf.GradientTape` to output the gradients from `call`.

If you are just trying to use GradientTape with already-built Keras models: Call the model on actual tensors with values inside the `tf.GradientTape` scope rather than using the symbolic Keras inputs/outputs.

For some of these use cases where you don't want to write a custom training loop from scratch, you may also want to consider using a custom training step if you need to use gradienttape in nontrivial ways:
https://keras.io/guides/customizing_what_happens_in_fit/
