### ISSUE TITLE
Building static-linked tensorflow

### ISSUE THREAD

**Issue by alantus** [tensorflow/tensorflow#462]
Have you considered distributing a static-built version of tensorflow so poor uses of old CentOS clusters  with an old glibc could use it? I understand static builds are dirty but it seems that there are many users that would benefit from this solution...
I tried to build tensorflow using an old glibc myself but did not succeed. I guess it could be done but some knowledge of bazel and the internal structure of tensorflow required (and a lot of time!)...

**Comment by girving** [comment]
Closing since I think this is covered by #527.  It would be better to fix compilation on Centos rather than ship static versions.
