### ISSUE TITLE
Many errors in the Example of tf.feature_column.categorical_column_with_hash_bucket

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#46201]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket

## Description of issue (what needs changing):
When running the **`Example Code`**, it is resulting in the errors mentioned below:

1. 

> File "<ipython-input-1-e0419158b389>", line 3
>     keywords = categorical_column_with_hash_bucket("keywords", 10K)
>                                                                  ^
> SyntaxError: invalid syntax

2. 

> NameError: name 'categorical_column_with_hash_bucket' is not defined

3. 

> NameError: name 'linear_model' is not defined

4. 

> NameError: name 'input_layer' is not defined

5. 

> ValueError: All feature_columns must be FeatureColumn instances. Given: Ellipsis

The code in the documentation should be modified to fix all the above errors. 

Please find the [Github Gist](https://colab.research.google.com/gist/rmothukuru/eba74b40ed40964c730e4e667ed0c8f1/categorical_column_with_hash_bucket_error.ipynb) demonstrating the errors.

**Comment by abhinavsp0730** [comment]
Hy, @rakeshmothukuru1  I found this as a duplicate issue of https://github.com/tensorflow/tensorflow/issues/46203 . Would you please close one of the issue.
Thanks.

**Comment by rakeshmothukuru1** [comment]
@abhinavsp0730,
No, the code present in this issue and #46203 are different corresponding to different APIs.
