### ISSUE TITLE
DepthwiseConv2D is slower than Conv2D

### ISSUE THREAD

**Issue by cookingbear** [tensorflow/tensorflow#46217]
I saw the similar issue in 
https://github.com/tensorflow/tensorflow/issues/42172
As in this post, when the batch size is larger, DepthwiseConv2D can be faster than Conv2D.
However, if I have to set the batch size to 1, is there any method to speed up DepthwiseConv2D?

**Comment by cookingbear** [comment]
> I saw the similar issue in
> #42172
> As in this post, when the batch size is larger, DepthwiseConv2D can be faster than Conv2D.
> However, if I have to set the batch size to 1, is there any method to speed up DepthwiseConv2D?

The version I used is tensorflow 2.3.1

**Comment by ek9852** [comment]
@cookingbear What platform are u running with that ?
Are u running using gpu/cuda, or pure CPU. ARM  or x86 platform ?

**Comment by cookingbear** [comment]
I tested it on x86 using cpu only

**Comment by jvishnuvardhan** [comment]
@cookingbear Is this still an issue for you? Can you please test with recent `TF2.6` and `tf-nightly` and let us know whether the issue persists. [Here](https://colab.research.google.com/gist/jvishnuvardhan/1844f21420de68d53ea92d8b0ebb4a17/untitled233.ipynb) is a gist for reference. Thanks!

**Comment by cookingbear** [comment]
> @cookingbear Is this still an issue for you? Can you please test with recent `TF2.6` and `tf-nightly` and let us know whether the issue persists. [Here](https://colab.research.google.com/gist/jvishnuvardhan/1844f21420de68d53ea92d8b0ebb4a17/untitled233.ipynb) is a gist for reference. Thanks!

thanks for your attention. I would test again with the newest version.
