### ISSUE TITLE
Control dependency doesn't work in distribute MirroredStrategy

### ISSUE THREAD

**Issue by whhu** [tensorflow/tensorflow#46210]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 20.04 LTS` with `nvcr.io/nvidia/tensorflow:19.12-tf1-py3`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): none
- TensorFlow version (use command below): `unknown 1.15.0`
- Python version: `3.6.9`
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: CUDA 10.2.89, cuDNN 7.6.5
- GPU model and memory: 2x GeForce GTX 1080 Ti with 11178 MiB fb memory
```
        GPU0    GPU1    CPU Affinity
GPU0     X      PHB     0-11
GPU1    PHB      X      0-11
```

**Describe the current behavior**
It seems that `tf.control_dependencies` is useless in the `load_fn`, which is called by a `MirroredStrategy`.
The wall times of `load` and `ret` differ greatly with each other.

**Describe the expected behavior**
The wall times of `load` and `ret` is comparable.

**Standalone code to reproduce the issue**
```python
import time
import tensorflow as tf

SHAPE = [2048, 2048]
STEP = 100
WARMUP = 100

_LOAD_OPS = list()


def load_fn():
    v = tf.get_variable('v', shape=SHAPE, initializer=tf.ones_initializer)
    m = tf.matmul(v, v)
    _LOAD_OPS.append(m.op)
    with tf.control_dependencies([m.op]):
        return tf.constant(1.0)


def bench(name, session, ops):
      stime = time.time()
      for _ in range(STEP):
          session.run(ops)
      etime = time.time() - stime
      print('{:6s} takes {:.3e} sec.'.format(name, etime))
    

def main():
    strategy = tf.distribute.MirroredStrategy()
    with strategy.scope():
        r = strategy.experimental_run_v2(load_fn)
        r = strategy.reduce(tf.distribute.ReduceOp.SUM, r)

    with tf.train.MonitoredSession() as mon_sess:
        for _ in range(WARMUP):
            mon_sess.run([_LOAD_OPS, r, []])

        bench('load', mon_sess, _LOAD_OPS)
        bench('ret',  mon_sess, r)
        bench('null', mon_sess, [])


if __name__ == '__main__':
    main()
```

**Other info / logs**
The non-trivial output is
```
load   takes 8.350e-01 sec.
ret    takes 3.153e-02 sec.
null   takes 4.847e-03 sec.
```

**Comment by amahendrakar** [comment]
@whhu,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by whhu** [comment]
> @whhu,
> TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

The problem remains. The output,
```bash
load   takes 7.845e-01 sec.
ret    takes 2.101e-02 sec.
null   takes 3.858e-03 sec.
```
is obtained in the latest `tensorflow/tensorflow:2.4.0-gpu` with `Python 3.6.9` and `v2.4.0-rc4-71-g582c8d236cb 2.4.0`.
The `import` part of the code is updated to
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
and the `strategy.experimental_run_v2` is updated to `strategy.experimental_run`.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. The output is as follows

- TF v2.3
```
load   takes 3.725e+00 sec.
ret    takes 2.209e-02 sec.
null   takes 3.345e-03 sec.
```
- TF v2.4
```
load   takes 1.684e-01 sec.
ret    takes 4.121e-02 sec.
null   takes 4.050e-03 sec.
```
- TF-nightly i.e. v2.5.0-dev20210111
```
load   takes 1.672e-01 sec.
ret    takes 4.292e-02 sec.
null   takes 4.081e-03 sec.
```

Thanks!

**Comment by nikitamaia** [comment]
Hi @whhu, in general you should not use distribution strategies with legacy TF1 graph mode, as this is not supported. You'll need to rewrite your code for TF2 such that you do not need `tf.disable_v2_behavior()` for the code to run.
