### ISSUE TITLE
Running multiple hexagon delegates sequentially. 

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#46223]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Snapdragon 855 running Android 9
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Right now, I have two instances of TfLite interpreter created using the same tflite model. Some of the network is delegated to DSP using hexagon delegate. Both interpreters are initialized one after other. Then, Invoke() is called many times, on either one or the other interpreter. This works fine. 

**Describe the expected behavior**

What happens if I create two instances of tfliteInterpreter from different models, both using hexagon delegate? Will this work as expected?

**Comment by karimnosseir** [comment]
Yes this should work without issues.

**Comment by yakovdan** [comment]
Can you briefly explain how sharing the same DSP between tflite interpreters work?

**Comment by karimnosseir** [comment]
Each delegate instance creates separate hexagon graph with separate rpc calls to the dsp.

**Comment by ymodak** [comment]
Closing this issue since it's addressed. Feel free to reopen if necessary. Thank you
