### ISSUE TITLE
Contributing to TF

### ISSUE THREAD

**Issue by OscarDPan** [tensorflow/tensorflow#4622]
My apology if I am posting this in a wrong place.
I was wondering if I have a valid bug fix or improvement to TF, and I want to test it before submitting a PR, what's the fastest way of doing it?
I usually use
```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
```
to re-set up TF but it always takes too much time.
Thanks

**Comment by concretevitamin** [comment]
Could you try to just build & test the relevant test targets?

For instance:

```
bazel test //tensorflow/python:saver_test  # Or other Python/C++ test targets.
```

I am not sure if this works in OSS world or not.  If not, when building `build_pip_package` feel free to drop the `-c opt` to improve build times.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
