### ISSUE TITLE
examples/image_retraining examples/android

### ISSUE THREAD

**Issue by grayscaler** [tensorflow/tensorflow#4623]
hi guys:
i want to use a retraining model on the android device, and i moved the model.pb(retraining Inception v3 model ) and label.txt(containing two labels) to the examples/android/assets, but i got some problem as the figure.

(09-28 18:37:11.572 21326-21351/org.tensorflow.demo E/native: tensorflow_inference_jni.cc:160 Output [output:0] not found, aborting!)

Is there any document which explains detail about how to predict with a model in .cc file and how should i rewrite tensorflow_inference_jni.cc file to load the model.
<img width="1143" alt="2016-09-28 6 38 03" src="https://cloud.githubusercontent.com/assets/12976847/18910659/975ef168-85ab-11e6-8fe0-4f6eaec3ba9a.png">

thanks for your time

**Comment by andrewharp** [comment]
See the comments in [TensorFlowImageListener.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java) for instructions on updating the model parameters.

You will also need to run strip_unused.py to remove some of the ops unsupported by Android TF that were for training (e.g. DecodeJpeg):
```
bazel build tensorflow/python/tools:strip_unused
bazel-bin/tensorflow/python/tools/strip_unused --input_graph=inception.pb --output_graph=/tmp/stripped_inception.pb --input_node_names="Mul" --output_node_names="final_result" --input_binary=true
```

**Comment by grayscaler** [comment]
it worked, thanks for your help and time.

**Comment by iamgroot42** [comment]
@andrewharp there's no strip_unused.py in the repo now. Has it been moved, or is running it no longer required?
