### ISSUE TITLE
Implement a simple way to load a TF dataset from a Spark dataset and a simple way to convert a TF dataset to a Spark dataset

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [tensorflow/tensorflow#46236]
**System information**
- TensorFlow version (you are using): 2.3.2
- Are you willing to contribute it (Yes/No): Hmm, yes though it may take a while for me to figure out how to do this. May be easier if an experienced contributor were to implement this (?)

**Describe the feature and the current behavior/state.**
Currently, from what I can tell, if you want to load data from Spark into a TF dataset, you have to first persist the data, as e.g. Parquet files or tfrecord files, then load data into a TF dataset from those files. This is inefficient as it requires intermediary processing and storage. Ideally, this new feature would allow a developer to load/transform data in Spark, then convert it to a TF dataset, build a model, etc.  Conversely, if you need an easy conversion from a TF dataset to Spark, the complementary converter would handle that. Perhaps a .toSparkDataset() method on TF dataset, or a separate static converter method somewhere.

**Will this change the current api? How?**
Yes. This will require new classes/methods -- up to the implementor.

**Who will benefit with this feature?**
I suspect many developers will benefit. Spark offers rich functionality for loading, transforming, joining data. Many systems may already have ETL type of code in Spark and want to leverage TensorFlow. Having an easy bridge from Spark to TF and back without the overhead of intermediary files (or a reduced such overhead) would be really useful.

LinkedIn's Spark-TFRecord library and the Spark Tensorflow Connector both require intermediary tfrecord files. Uber's Petastorm seems to offer a Spark-TF converter but if I understand correctly it uses intermediary local files for conversion; also I'm not seeing the reverse TF-to-Spark converter there (?).

**Any Other info.**
- I'm using Apache Spark 3.0.

**Comment by dgoldenberg-audiomack** [comment]
Generally, TF appears to drive implementors toward doing data prep and data post-processing in Spark, which means storing input data in intermediary storage, then loading it into TF datasets. That's rather inconvenient.

There is the [Big DL library](https://github.com/intel-analytics/BigDL) which presumably allows one to train TF models in a distributed fashion on Spark.

**Comment by Adamage** [comment]
@dgoldenberg-audiomack   I like how you used the word presumably. I have been struggling to make it work actually.

**Comment by dgoldenberg-audiomack** [comment]
@Adamage LOL I was exercising a bit of caution b/c I've not evaluated Big DL library yet :)
