### ISSUE TITLE
TypeError: '<' not supported between instances of 'function' and 'str'

### ISSUE THREAD

**Issue by abdallah1097** [tensorflow/tensorflow#46249]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Ubuntu)
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6.9

**Code**
I've save a model using callbacks:

```python
mc = tf.keras.callbacks.ModelCheckpoint( filepath=save_directory + '/trial10_model.h5',
                                        monitor="val_loss",
                                        save_freq="epoch",
                                        save_best_only=True,
                                        save_weights_only=False)
callback_list = [mc]

history = model.fit_generator(get_train_set_,validation_data = get_val_set_, validation_steps=validation_steps,
                              steps_per_epoch = steps_per_epoch,epochs=15, callbacks=callback_list)
```

While testing the model using evaluate or evaluate_generator:
```python
model = load_model("/content/gdrive/MyDrive/keras_tuner/good_trail/trial10_model.h5", custom_objects={ 'dice_coef': dice_coef })
res = model.evaluate(get_test_set_,steps=test_steps_per_epoch, verbose=1)
```
**Error Message**
I get this error message:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-56-3ae064222286> in <module>()
     12 callback_list = [mc]
     13 
---> 14 res = model.evaluate(get_test_set_,steps=test_steps_per_epoch, verbose=1, callbacks=callback_list)

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1233 test_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1224 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1219 run_step  **
        with ops.control_dependencies(_minimum_control_deps(outputs)):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:2793 _minimum_control_deps
        outputs = nest.flatten(outputs, expand_composites=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py:341 flatten
        return _pywrap_utils.Flatten(structure, expand_composites)

    TypeError: '<' not supported between instances of 'function' and 'str'
```

**Comment by ravikyram** [comment]
@abdallah1097 

Can you please share colab link or simple standalone code with supporting files(`model.h5`) to reproduce the issue in our environment.It helps us in debugging faster. Thanks!

**Comment by nikroyal** [comment]
try switching to tf 2.3... or try saving configurations and weights separately.... had exactly the same problem and these hacks worked for me.

**Comment by stanleyjzheng** [comment]
Downgrading to tf2.3 did not work for me, and isn't an acceptable solution due to the lack of support for CUDA 11 and CUDNN 8. However, saving the model as weights and then loading as weights worked (as opposed to loading the entire model). This behaviour can be found in Intel Unet. https://github.com/IntelAI/unet/tree/master/3D
Simply run `python train.py --data_path $DECATHLON_ROOT_DIRECTORY --epochs=1` with tf 2.4. I was unable to reproduce this with a minimal example. Thanks.

**Comment by ravikyram** [comment]
@abdallah1097 

Please go through below link

https://www.tensorflow.org/tutorials/keras/save_and_load

Try to save the model weights, rather than saving the whole model and then evaluated using the latest weights on a new model instance. See it works?

Thanks!

**Comment by zaccharieramzi** [comment]
@ravikyram is there a fix for someone who doesn't want to save the weights separately (because for example they want to also save the optimizer's state)?

**Comment by LaurinHerbsthofer** [comment]
I had the same issue, solved it by compiling the model again after loading:

`model = load_model(...)
model.compile(...)
model.evaluate(...)`

**Comment by zaccharieramzi** [comment]
@LaurinHerbsthofer your solution definitely works when only evaluating the model afterwards and not resuming training.

if you want to resume training however the problem still stands because you cannot compile the model again: it will get rid of the optimizer’s state.

**Comment by MatrixScenary** [comment]
See this: https://github.com/tensorflow/tensorflow/issues/45903#issuecomment-804973541
