### ISSUE TITLE
Add Sony Spresense target

### ISSUE THREAD

**Issue by takayoshi-k** [tensorflow/tensorflow#46240]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): any
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): master
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Sony Spresense board with Cortex-M4F

**Describe the problem**
To add support for sony spresense board.
Spresense has own development environment and it is bit conflict with Tensorflow Lite for Microcontrollers.
Tensorflow Lite for Microcontrollers can be used as a linkable library as libtensorflow-microlite.a.

A simple solution is to build the library as on Coretex-M4 platform with CMSIS-NN, and use it on the board development environment.
But the problem is how to use a examples.
Fortunately, the examples provide main_functions.cc with just 2 function as externd "C" like setup() and loop().
So I try to create a spresense target to build the library archive with example's sources without main.cc.

**Please provide the exact sequence of commands/steps when you ran into the problem**
I add a Makefile for downloading and build it on spresense sdk environment.
The draft work is in https://github.com/takayoshi-k/spresense/tree/add_tf_lm.
The makefile is https://github.com/takayoshi-k/spresense/blob/add_tf_lm/externals/tensorflow/Makefile.

**Comment by mohantym** [comment]
Hi @takayoshi-k ! Sony Spresense has been added in  tested micocontrollers list now. Attaching relevant[ thread ](https://www.tensorflow.org/lite/microcontrollers#supported_platforms)for reference. Thanks!
