### ISSUE TITLE
tf.keras Model predict slow in flask service

### ISSUE THREAD

**Issue by qiuming-93** [tensorflow/tensorflow#46245]
System info:
tensorflow: 1.12.0
flask: 1.1.2
os: centos7.6
use cpu

problem:
tf.keras Model predict slow in flask service
import the follow code in python console, and run predict method directly， only cost about 800ms time;
but in flask service， run predict methodin an interface, it need about 12s time.

code:
    def __init__(self):
        self.height = 960
        self.width = 960
        self.channels = 3
        self.model = ResNet50(include_top=False, input_shape=(self.height, self.width, self.channels))
        self.graph = tf.get_default_graph()

    def image_resize(self, image):
        raw_height = image.shape[0]
        raw_width = image.shape[1]
        if raw_height > self.height or raw_width > self.width:
            ratio1 = raw_height * 1.0 / self.height
            ratio2 = raw_width * 1.0 / self.width
            if ratio2 > ratio1:
                ratio1 = ratio2
            raw_height = int(raw_height / ratio1)
            raw_width = int(raw_width / ratio1)
            image = cv2.resize(image, (raw_width, raw_height))
        new_img = np.pad(image,
                         pad_width=((0, self.height - raw_height),
                                    (0, self.width - raw_width),
                                    (0, 0)
                                    ),
                         mode="constant", constant_values=(0, 0))

        return new_img

    def predict(self):
        image = cv2.imread('1.jpg')
        image = self.image_resize(image)
        time1 = int(round(time.time() * 1000))
        with self.graph.as_default():
            self.model.predict(np.array([image]))
        time2 = int(round(time.time() * 1000))
        cost = time2 - time1
        return str(cost) + " ms."

**Comment by qiuming-93** [comment]
I have find the reason, my flask service has an other model based on paddlepaddle, and it predict faster after i remove the other model

**Comment by abhinavsp0730** [comment]
Hy, @qiuming-93  if possible would you please send your whole code and instructions to replicate it. So, that I can test the bottle neck of your issue.
thanks.

**Comment by qiuming-93** [comment]
I have find the reason, you can add "from paddleocr import PaddleOCR" at the head of the code to replicate it.
thanks

**Comment by ravikyram** [comment]
@qiuming-93 

Is this still an issue?
If issue still persists please share complete code snippet with proper indentation and supporting files to reproduce the issue in our environment.It helps us in debugging faster. Thanks!

**Comment by qiuming-93** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2021/1/4 20:05
# @Author  : qiuming

import flask
from tensorflow.python.keras.applications import ResNet50
import tensorflow as tf
import cv2
import numpy as np
import os

os.environ["CUDA_VISIBLE_DEVICES"] = ""

host='0.0.0.0'
# 实例化 flask
app = flask.Flask(__name__)

height = 960
width = 960
channels = 3
model = ResNet50(include_top=False, input_shape=(height, width, channels))

def image_resize(image):
    height=960
    width=960
    raw_height = image.shape[0]
    raw_width = image.shape[1]
    if raw_height > height or raw_width > width:
        ratio1 = raw_height * 1.0 / height
        ratio2 = raw_width * 1.0 / width
        if ratio2 > ratio1:
            ratio1 = ratio2
        raw_height = int(raw_height / ratio1)
        raw_width = int(raw_width / ratio1)
        image = cv2.resize(image, (raw_width, raw_height))
    new_img = np.pad(image,
                     pad_width=((0, height - raw_height),
                                (0, width - raw_width),
                                (0, 0)
                                ),
                     mode="constant", constant_values=(0, 0))

    return new_img

def predict():
    image = cv2.imread('1.jpg')
    import time
    print(time.time())
    if not isinstance(image, np.ndarray):
        raise BaseException('image must be numpy array')
    shape = image.shape
    if len(shape) == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
    assert len(image.shape) == 3
    raw_height = 960
    raw_width = 960
    if image.shape[0] > 960:
        raw_height = image.shape[0]
    if image.shape[1] > 960:
        raw_width = image.shape[1]
    if raw_width / 960 > raw_height / 960:
        raw_height = int(raw_width / 960 * 960)
    else:
        raw_width = int(raw_height / 960 * 960)
    image_copy = image.copy()
    image_copy = image_resize(image_copy)
    print(time.time())
    pred = model.predict(np.array([image_copy]))
    print(time.time())

	
# 将预测函数定义为一个路由
@app.route("/predict", methods=["GET"])
def predict2():
    data = {"success": False}
    predict()
    return flask.jsonify(data)


# 启动Flask应用程序，允许远程连接
if __name__ == '__main__':
    app.run(debug=False, host=host,threaded=False,port=5000)

**Comment by ravikyram** [comment]
@qiuming-93 

TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by qiuming-93** [comment]
ok
