### ISSUE TITLE
TensorBoard callback with update_freq='batch' fails when fitting multiple times

### ISSUE THREAD

**Issue by aCampello** [tensorflow/tensorflow#46252]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes. The bug happens in the minimal example in the TensorFlow documentation, with a small tweak.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS Mojave 10.14.6
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: Python 3.8.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

If we add a callback for TensorBoard when fitting a Keras Model (say `model`) as in `callbacks = [tf.keras.callbacks.TensorBoard(log_dir='./logs', update_freq='batch')]`,

calling the function `model.fit` twice causes an error (see logs below)

**Describe the expected behavior**

Ideally we would be able to call `model.fit` a many times as we want. If we don't use the `update_freq` parameter, it does not give an error and behaves as expected.

**Standalone code to reproduce the issue**
Any model will do. The one in the tensorflow docs tutorial, for example:

```bash
import tensorflow as tf
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

callbacks = [tf.keras.callbacks.TensorBoard(log_dir='./logs', update_freq='batch')]

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

model.fit(x_train, y_train, callbacks=callbacks)
model.fit(x_train, y_train, callbacks=callbacks)
```

**Other info / logs** 

Log of the error:

```bash
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4814 - accuracy: 0.8604
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-24-6d870932cb3b> in <module>
     17 
     18 model.fit(x_train, y_train, callbacks=callbacks)
---> 19 model.fit(x_train, y_train, callbacks=callbacks)

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    853       # In this case we have created variables on the first call, so we run the
    854       # defunned version which is guaranteed to never create variables.
--> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    856     elif self._stateful_fn is not None:
    857       # Release the lock early so that multiple threads can perform the call

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2940       (graph_function,
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
-> 2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1916         and executing_eagerly):
   1917       # No tape is watching; skip to running the function.
-> 1918       return self._build_call_outputs(self._inference_function.call(
   1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    553       with _InterpolateFunctionError(self):
    554         if cancellation_manager is None:
--> 555           outputs = execute.execute(
    556               str(self.signature.name),
    557               num_outputs=self._num_outputs,

~/WellcomeML/build/virtualenv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

NotFoundError:  Resource localhost/_AnonymousVar1925/N10tensorflow22SummaryWriterInterfaceE does not exist.
	 [[{{node cond/then/_0/batch_loss}}]] [Op:__inference_train_function_108360]

Function call stack:
train_function
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1f9c5a3d464fa88f88f12d111499b5c4/46252.ipynb#scrollTo=nPStrYH4k6-R). Thanks!

**Comment by rmothukuru** [comment]
@aCampello,
It is resulting in `error` but can you please give some Real World Use Cases where and why we execute **`model.fit`** immediately after another **`model.fit`** command because, executing the entire cell, with a single **`model.fit`** command any number of times is not resulting in error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/653a49aba124e384db87cfa11c501111/46252.ipynb) of working code.

Thanks!

**Comment by aCampello** [comment]
Hi @rmothukuru. Thanks for helping with this!

This is a made up example, but there are a number of real cases where you would like to fit multiple times. For instance, if you are working on a Jupyter notebook, you might want to run `.fit` for a couple of epochs, do something else, then run `.fit` for a couple more, etc, especially when you are iterating your model/try to define your architecture.

Partial fits are quite useful in the real world, to be fair.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/46ea70c9ddbfd5e0298ae3d445d8bb6f/untitled163.ipynb?authuser=1)..Thanks !

**Comment by cmgreen210** [comment]
This still appears to be an issue at least in `2.7.0`.

Another use case to consider is for [distributed evaluation in the Parameter Server Strategy](https://www.tensorflow.org/tutorials/distribute/parameter_server_training#inline_evaluation). Basically if you model is too big to fit on a single machine you need to manually do an eval loop and if you want to do this multiple times during training you'll have to call `fit` multiple times.

**Comment by sushreebarsa** [comment]
@aCampello I was able to run your code successfully  on colab using TF v2.8.0  .Could you please have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/e1cdb14dfe451f245b979bf89ae3e9f0/46252.ipynb) and let us know if it helps? Thanks!
