### ISSUE TITLE
[XLA] dense_layer_test.py throws internal error in fallback path

### ISSUE THREAD

**Issue by AyanmoI** [tensorflow/tensorflow#46257]
The failure happens in Master as well as r2.4 (these are the 2 branches that I've tested).

Even with lazy_compilation turned on (via `TF_XLA_FLAGS=--tf_xla_enable_lazy_compilation=true`), the first execution always compiles as per the current implementation. If we tweak this behaviour such that the first execution doesn't compile (and uses the fallback path) or use `--tf_xla_always_defer_compilation=true` to force the fallback path, the test `tensorflow/compiler/tests/dense_layer_test.py` fails with the following signature
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node cluster_3}} {{function_node cluster_3}} Trying to assign variable with wrong dtype. Expected INVALID got float
     [[{{node dense/kernel/Assign}}]]
     [[cluster_3_1/partitioned_call]]
```

There are 3 test points in the test. Based on the descriptions, they test that the dense layer node is properly compiled in jit scope. I am not sure if this test is supposed to be used for the fallback path. However, the failure is not merely a test failure but an internal error (`Trying to assign variable with wrong dtype. Expected INVALID got float`) which leads me to think there might be a bug. 

The error comes from handling of resource variables https://github.com/tensorflow/tensorflow/blob/13d37279f137a96ca6fa5142f20c8747103bf79e/tensorflow/core/kernels/resource_variable_ops.cc#L397-L401

**Comment by sanjoy** [comment]
Hi @AyanmoI 

I was not able to reproduce this issue as:

```
# Git SHA1: 5534f5d320818aad52aac35af193b88b7222d46b

bazel test -c opt --nodistinct_host_configuration --config=cuda //tensorflow/compiler/tests:dense_layer_test_gpu --test_env=TF_XLA_FLAGS=--tf_xla_always_defer_compilation=true
```

Can you please share the exact run command and the commit at which you're running so that we're not talking past each other?

Thanks!

**Comment by AyanmoI** [comment]
Hey @sanjoy ... that is pretty much the repro I used. However, it seems that simply using  `--tf_xla_always_defer_compilation=true` doesn't reproduce this error. I believe there might still be an issue in the interaction of  resource variable and partioned_call but it cannot be exposed in this fashion. 
I'll see if there is a better repro and address this then. For now I am closing this issue.

**Comment by hercule24** [comment]
Hey @AyanmoI , I am also using TF 2.4 and having the same issue.

Our error is likely thrown from a `tf.keras.layers.Embedding` layer, I am wondering if you have any suggestions to work around this issue or will upgrading to TF 2.11 or higher help?
