### ISSUE TITLE
Cannot Convert SentencePieceTokenizer to TensorRT

### ISSUE THREAD

**Issue by dshahrokhian** [tensorflow/tensorflow#46254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/7.6
- GPU model and memory: RTX 2080

**Describe the current behavior**
Whenever I try to convert a model containing the tokenizer as subgraph, I get an error.

**Describe the expected behavior**
It should just convert it.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1_S37VihkTZ1B0HgjW8D7DMZcI8nwz2Bk

**Other info / logs**
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-e780e9ed6737> in <module>
      4 )
      5 
----> 6 converter.convert()

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/compiler/tensorrt/trt_convert.py in convert(self, calibration_input_fn)
   1094                                   self._input_saved_model_tags)
   1095     func = self._saved_model.signatures[self._input_saved_model_signature_key]
-> 1096     frozen_func = convert_to_constants.convert_variables_to_constants_v2(func)
   1097     grappler_meta_graph_def = saver.export_meta_graph(
   1098         graph_def=frozen_func.graph.as_graph_def(), graph=frozen_func.graph)

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2(func, lower_control_flow, aggressive_inlining)
   1069       func=func,
   1070       lower_control_flow=lower_control_flow,
-> 1071       aggressive_inlining=aggressive_inlining)
   1072 
   1073   output_graph_def, converted_input_indices = _replace_variables_by_constants(

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py in __init__(self, func, lower_control_flow, aggressive_inlining, variable_names_allowlist, variable_names_denylist)
    804         variable_names_allowlist=variable_names_allowlist,
    805         variable_names_denylist=variable_names_denylist)
--> 806     self._build_tensor_data()
    807 
    808   def _build_tensor_data(self):

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/convert_to_constants.py in _build_tensor_data(self)
    823         data = map_index_to_variable[idx].numpy()
    824       else:
--> 825         data = val_tensor.numpy()
    826       self._tensor_data[tensor_name] = _TensorData(
    827           numpy=data,

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in numpy(self)
   1069     """
   1070     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1071     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1072     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1073 

~/anaconda3/envs/ds/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1037       return self._numpy_internal()
   1038     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1039       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1040 
   1041   @property

~/anaconda3/envs/ds/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Comment by Saduf2019** [comment]
@dshahrokhian 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ca4dff5ddcc5b906fad0d2c75aee57d7/untitled.ipynb) and share all dependencies for us to replicate the issue faced and analyse it.

**Comment by dshahrokhian** [comment]
@Saduf2019 Was there an issue colab instance I have shared? It had all the dependencies already.
I have added the file to your gist.

Thanks.

**Comment by Saduf2019** [comment]
@dshahrokhian
what you add to your gist is local to you i cannot access it, please send it through attachment.

**Comment by dshahrokhian** [comment]
My apologies, here it is: https://drive.google.com/file/d/1l1kdHuM_oJf_sJwR1p8g1Pn4P_DRtCWc/view?usp=sharing

**Comment by Saduf2019** [comment]
@ymodak 
I ran the code shared on tf 2.4 and nightly, please find the gist for [tf 2.4](https://colab.research.google.com/gist/Saduf2019/65e9cb7c2b26eae2e5eb8a21fb7b02db/untitled492.ipynb) and cloab crashes on [nightly](https://colab.research.google.com/gist/Saduf2019/263fe39332add8ab3eebe9d0a030afdc/untitled.ipynb).

**Comment by ymodak** [comment]
Perhaps [tensorflow/text](https://github.com/tensorflow/text) repo can be a right place fo this issue. Can you please raise it on that repo?
Thanks!

**Comment by dshahrokhian** [comment]
@ymodak correct me if I am wrong, but this has more to do with core tensorflow not being able to handle lookup tables during TF-TRT conversion. 

I had already opened an issue on `tensorflow/text`, as well as `tensorflow/tensorrt`. In [this](https://github.com/tensorflow/tensorrt/issues/233) issue, one of your core contributors also thinks the same.

Thank you for the support.

**Comment by massibelloni-medium** [comment]
hi all! I am facing the very same issue, so did not open a new one. Any update on this? Thanks for the support @bixia1

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/41027e5a650bace7b265bede0db6e443/untitled492.ipynb#scrollTo=AKpLR7ODG89j)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
