### ISSUE TITLE
TensorFlow 0.10.0rc fails to detects CUDA device on my Macbook Pro (with nvidia 750M graphic card)

### ISSUE THREAD

**Issue by vinhqdang** [tensorflow/tensorflow#4626]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
- This one is related, but it is for Ubuntu
https://github.com/tensorflow/tensorflow/issues/2882
- This one is related also
https://github.com/tensorflow/tensorflow/issues/2940#issuecomment-238952433

### Environment info
Operating System: mac os 10.12

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
ls -l /usr/local/cuda/lib/libcud*
-rwxr-xr-x@ 1 root   admin   8.1K Sep 28 14:39 /usr/local/cuda/lib/libcuda.1.dylib*
-rwxr-xr-x@ 1 root   wheel   8.1K Apr 13 08:02 /usr/local/cuda/lib/libcuda.dylib*
lrwxr-xr-x@ 1 root   wheel    45B Apr 13 08:03 /usr/local/cuda/lib/libcudadevrt.a@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root   wheel    50B Apr 13 08:03 /usr/local/cuda/lib/libcudart.7.5.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib
lrwxr-xr-x@ 1 root   wheel    46B Apr 13 08:03 /usr/local/cuda/lib/libcudart.dylib@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib
lrwxr-xr-x@ 1 root   wheel    49B Apr 13 08:03 /usr/local/cuda/lib/libcudart_static.a@ -> /Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a
-rwxr-xr-x@ 1 qdang  staff    56M Apr 23 02:19 /usr/local/cuda/lib/libcudnn.5.dylib*
lrwxr-xr-x@ 1 qdang  staff    16B Apr 23 04:10 /usr/local/cuda/lib/libcudnn.dylib@ -> libcudnn.5.dylib
-rw-r--r--@ 1 qdang  staff    53M Apr 23 02:19 /usr/local/cuda/lib/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
``TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.10.0-py2-none-any.whl``
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.dylib locally
0.10.0
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I just run the ``iris_monitor.py`` example at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/monitors and got the error

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.dylib locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
```

### What other attempted solutions have you tried?

I ran torch on my GPU successfully before, so I could confirm that GPU computing is possible on my computer.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by tatatodd** [comment]
@vinhqdang is there any other information returned in the failure?

Based on #255, you might try running the device query binary from nvidia's samples, to see whether the GPU is properly detected.

**Comment by vinhqdang** [comment]
Here is the ``nvcc`` I have

```
nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26
```

**Comment by vinhqdang** [comment]
Oops, I think the problem is: I am running Mac OS 10.12 with Xcode 8, clang 8 and CUDA 8.0, but CUDA 8.0 does not support clang 8


```
/Developer/NVIDIA/CUDA-8.0/samples/1_Utilities/deviceQuery$ make

/Developer/NVIDIA/CUDA-8.0/bin/nvcc -ccbin clang++ -I../../common/inc  -m64  -Xcompiler -arch -Xcompiler x86_64  -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_60,code=compute_60 -o deviceQuery.o -c deviceQuery.cpp
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
**nvcc fatal   : The version ('80000') of the host compiler ('Apple clang') is not supported**
make: *** [deviceQuery.o] Error 1

```

**Comment by wwxFromTju** [comment]
so, How to solve? I also have this problem? now, I run the mac os and Xcode8, cuda 7.5

**Comment by tatatodd** [comment]
@wwxFromTju Have you followed the instructions here:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#prepare-environment-for-mac-os-x

Note the following section:

---

If you want to compile tensorflow and have the XCode 7.3 installed, note that Xcode 7.3 is not yet compatible with CUDA 7.5. You will need to download Xcode 7.2 and select it as your default:
```
$ sudo xcode-select -s /Application/Xcode-7.2/Xcode.app
```

---

I am not an expert on the mac environment, but perhaps you can try XCode 7.2?

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.
