### ISSUE TITLE
ESP32 example creation fails for person_detection example

### ISSUE THREAD

**Issue by vikramdattu** [tensorflow/tensorflow#46277]
**System information**
- OS Platform and Distribution: ESP32
- TensorFlow version: master, commit 78012e5d6c45ffd3673b8970b199a67980df1963

**Describe the problem**

Example creation fails with following error:

```
% make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: *** No rule to make target 'generate_person_detection_esp_project'.  Stop.
```

**Comment by Hazeline2018** [comment]
Still no solution yet? Please!

**Comment by vikramdattu** [comment]
MR is ongoing... https://github.com/tensorflow/tensorflow/pull/47063

Feel free to cherry-pick changes for now.

**Comment by vikramdattu** [comment]
Closing the issue, as it isn't relevant anymore.
