### ISSUE TITLE
use of interpreter-->SetNumThreads. Do we need to invoke setNumThreads always to improve performance

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#46272]
In the label_image.cc example from tfLite, we are passing setNumThreads manually under the code.
Does number of threads automatically picked by tfLite (or) Is it required by user to always force SetNumThreads ?

**Comment by teijeong** [comment]
Hi @pranathibl, it's determined automatically when not specified (equal to calling `setNumThreads(-1)`).

For simple questions in the future, please use stackoverflow :)
