### ISSUE TITLE
Don't raise an Error on unknown kwargs

### ISSUE THREAD

**Issue by bugerry87** [tensorflow/tensorflow#46276]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version 2.1 - 2.3:
- Are you willing to contribute it (No):

**Describe the feature and the current behavior/state.**

Almost all Keras objects support **kwargs but raising an TypeError if a 'Keyword argument (is) not understood'. i.e.

```
tf.keras.layers.Dense(8, foo='bar')
```

I wish a more Duck Typing behavior that either ignores unknown args or raises a warning according to the debug level.

**Who will benefit with this feature?**

Simplifies the parameter management for inheriting classes or adapter classes.

```
class MyLayer(tf.keras.layers.Layer):
   def __init__(self, units=8, dims=(0,2,1), **kwargs):
      super(MyLayer, self).__init__(**kwargs)
      self.layer = tf.keras.layers.Dense(units, **kwargs)
      self.permute = tf.keras.layers.Permute(dims, **kwargs)
      [...]
```

**Comment by fchollet** [comment]
> I wish a more Duck Typing behavior that either ignores unknown args or raises a warning according to the debug level.

This would be extremely dangerous, since it would any mistyped argument would be silently ignored instead of causing an error. For example:

```python
dense = Dense(32, activaton='relu')  # This silently creates a layer with *no* activation due to the typo.
```
