### ISSUE TITLE
How to convert TF1.12 checkpoints to saved/keras model format.

### ISSUE THREAD

**Issue by nehasoni3** [tensorflow/tensorflow#46289]
I have a TTS model checkpoints trained on TFv1.12. For inferencing, I have used 
`self.session = tf.Session(config=config)
self.session.run(tf.global_variables_initializer())
saver = tf.train.Saver()
saver.restore(self.session, checkpoint_path)
`
For its TFlite conversion, saved/keras model is required. How do I convert this model into TFLite.

**Comment by amahendrakar** [comment]
@nehasoni3,
For converting to `.tflite` format, please go through [this](https://www.tensorflow.org/lite/convert) official guide.

Also TensorFlow 1.x is not actively supported, hence I'd recommend updating TensorFlow to the latest stable version v2.4. Thanks!

**Comment by nehasoni3** [comment]
> @nehasoni3,
> For converting to `.tflite` format, please go through [this](https://www.tensorflow.org/lite/convert) official guide.
> 
> Also TensorFlow 1.x is not actively supported, hence I'd recommend updating TensorFlow to the latest stable version v2.4. Thanks!

Thanks for reply.
I have model in TFv1.12. I have tried [this.](https://gist.github.com/zhanwenchen/d628ef70e9f76525fd47d6213c30730d).
checkpoints are converted into saved model but can not converted into TFlite, its do not have signature_def

**Comment by amahendrakar** [comment]
> Also TensorFlow 1.x is not actively supported, hence I'd recommend updating TensorFlow to the latest stable version v2.4. Thanks!

@nehasoni3,
Could you please check if you are facing the same issue with TF v2.4 as well? Thanks!
