### ISSUE TITLE
tf.io.gfile.GFile does not raise an error when given a directory

### ISSUE THREAD

**Issue by MiladShahidi** [tensorflow/tensorflow#46282]
Python's `open` does not accept directories. The following results in an `IsADirectoryError`:

```
    with open('.', 'r') as f:
        print(f.readlines())
```

However, if you use `tf.io.gfile.GFile` instead, you will get an empty list and no error:

```
    with tf.io.gfile.GFile('.', 'r') as f:
        print(f.readlines())

```

Not sure if this is a feature or a bug, but it is not the behavior I would expect, given that the [documentation](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile) says that `tf.io.gfile` is meant to provide an API close to Python's file IO objects.

**Comment by ravikyram** [comment]
@MiladShahidi 

Thanks for filing the issue.
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple stndalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.

Are you interested in submitting PR for this?

Thanks!

**Comment by MiladShahidi** [comment]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version:  3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
The `tf.io.gfile.GFile` function does not raise an error when given a directory, whereas Python's `open` does. Given that the documentation says the role of the `gfile` module is to provide an API that's close to Python's file IO API, it would be reasonable to expect it to raise an error when the provided address points to a directory.

**Describe the expected behavior**
the `GFile` method should raise an error when given a directory.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1qR5b7M5SbpepOX9b9Jlru3fPOfCWqVxa?usp=sharing

**Comment by MiladShahidi** [comment]
Thank you for your response @ravikyram. I'd be more than happy to submit a PR for this.

**Comment by ravikyram** [comment]
@MiladShahidi 

Thanks for your interest in submitting PR.
I have tried in colab with TF version 2.3, 2.4 and nightly version(`2.5.0-dev20210110`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/70c1e8a714c17d4b288b246e04324bf0/untitled606.ipynb).

 Please, submit a PR .Thanks!

**Comment by mihaimaruseac** [comment]
Known issue, should be fixed in 2.5 with the switch to modular filesystems.

**Comment by MiladShahidi** [comment]
Thanks @mihaimaruseac. So, should I still submit a PR? Or is it already taken care of?

**Comment by mihaimaruseac** [comment]
I think this is handled already, thank you for offering to send a PR.

https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/experimental/filesystem/plugins/posix/posix_filesystem.cc;l=208-212;drc=f64e839687b6129dfe2a9e21ef965593c7f3a3c2

**Comment by saikumarchalla** [comment]
I executed the code in Nightly 2.6 and  not getting any error message when passing directory. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/df2a49e181a65c54af2033db56bf5084/nighly.ipynb).Thanks!

**Comment by mihaimaruseac** [comment]
In this case, closing as resolved. Thank you
