### ISSUE TITLE
TFLite: GPU delegate (OpenGL) outputs errors when different context is active.

### ISSUE THREAD

**Issue by Gohan1989** [tensorflow/tensorflow#46284]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3
- Python version: -
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
I have a problem running TFLite's GPU delegate on a mobile device without OpenCL support (which means the delegate falls back to the OpenGL implementation obviously).
```
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
E/tflite: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
E/tflite: Falling back to OpenGL
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
```
Got error:
```
E/tflite: TfLiteGpuDelegate Invoke: ToTensorConverter: input data size does not match expected size.
E/tflite: Node number 130 (TfLiteGpuDelegateV2) failed to invoke.
E/tflite: TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
E/tflite: Node number 87 (TfLiteGpuDelegateV2) failed to invoke.
```
Problem is that my app (which is using Unity3D engine) is creating its own OpenGL context (I don't have access to rendering context, so I can not change it back to TFLite one after rendering) which is active and TFLite can not copy data to GPU.
I think TFLite should activate its own context before making any operations on GPU when running OpenGL. 
**Describe the expected behavior**
TFLite works when app changes current OpenGL context to different than the one used by TFLite.

**Comment by Saduf2019** [comment]
@Gohan1989 
please share a simple stand alone code to replicate the issue faced.

**Comment by impjdi** [comment]
@Gohan1989 Instead of using TF 2.3, can you use master branch's latest snapshot and tell me how it goes?

**Comment by Gohan1989** [comment]
@impjdi 
On master branch I have the same behavior.

**Comment by impjdi** [comment]
@Gohan1989 can you attach your tflite model?  doesn't have to contain trained weights; i only need the architecture.
