### ISSUE TITLE
Compiled static library has different name than given in README.md

### ISSUE THREAD

**Issue by tusharsoni08** [tensorflow/tensorflow#4628]
At url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile in Building on Linux section of README.md file, when we run `tensorflow/contrib/makefile/build_all_linux.sh` command, then the build file name written as following :
"This should compile a static library in `tensorflow/contrib/makefile/gen/lib/tf_lib.a` "

But when I tried to run `tensorflow/contrib/makefile/build_all_linux.sh` command, then it's generated file have following name:
`/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a`

Could anyone confirm me that why they are different? does docs have not updated name or something else.

**Comment by concretevitamin** [comment]
I fixed at HEAD.  This will be pushed to Github within a day or two.  Thanks for noticing this!
