### ISSUE TITLE
C++ ShapeInference / ShapeRefiner use without PlaceHolder/ConstantOp support

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#4629]
The ShapeInference for C++ engine doesn't support the PlaceholderOp.  Is this because it isn't finished, or am I missing something?

It seems to be that you can't add a node to the shape inference engine without having added its dependencies.  Since ConsantOp and PlaceholderOp do not have a shape inference functions, I don't understand how the ShapeRefiner can have any nodes added to it.

**Comment by asimshankar** [comment]
Both the [Placeholder](https://github.com/tensorflow/tensorflow/blob/38adca7ebb40b8cd56b841af2f6b8a44c71f2a82/tensorflow/core/ops/array_ops.cc#L2359) and [Const](https://github.com/tensorflow/tensorflow/blob/38adca7ebb40b8cd56b841af2f6b8a44c71f2a82/tensorflow/core/ops/array_ops.cc#L335) ops do have shape inference functions registered. Thus, they can be added to the ShapeRefiner.

Closing this issue, feel free to re-open if I have misunderstood your question.

**Comment by DavidNorman** [comment]
Hi.  I was mistaken.  I am making a new device and I am interested in knowing about the shape of tensors flowing through the device when the device is handed the graph (perhaps a better name is the subgraph).

In this graph, constants and placeholders have been replaced by _Recv nodes, which do not have shape inference functions - this lead to my mistake.
