### ISSUE TITLE
No imagenet folder in the 0.6.0 wheel linked on tensorflow.org

### ISSUE THREAD

**Issue by daikazoku** [tensorflow/tensorflow#463]
Trying to follow the Inception-v3 tutorial, but there is  no imagenet folder in my installation.

```
(d)[nani@nande cat]$ pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.6.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.com/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/nani/Desktop/cat/d/lib/python2.7/site-packages
Requires: six, protobuf, wheel, numpy


(d)[nani@nande cat]$ ls d/lib/python2.7/site-packages/tensorflow/models/image/
cifar10  __init__.py  __init__.pyc  mnist
```

**Comment by vnkmr7620** [comment]
Try to run using bazel

**Comment by daikazoku** [comment]
you mean building from source? I am still building bazel.

**Comment by vnkmr7620** [comment]
yes. try to build it from source

**Comment by vrv** [comment]
Most of the example sources are no longer in the pip package install directory, instead, after installing the pip package, you can clone the git repository to get access to the source (at tag 0.6.0 to be safe), and then you can just do

cd tensorflow/models/image/imagenet
python classify_image.py

**Comment by daikazoku** [comment]
Oh, I see. Thanks.
