### ISSUE TITLE
Add TFLite metadata support to TensorFlowLiteSwift

### ISSUE THREAD

**Issue by willbattel** [tensorflow/tensorflow#46303]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
TFLite offers the ability to embed metadata into its models. For example, we can ship an image classifier with its labels included. https://www.tensorflow.org/lite/convert/metadata

Currently, the metadata is not accessible from the TensorFlowLiteSwift package. Available platforms can be found here: https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/metadata

I am using a custom TFLite image classifier in my Swift-based iOS app, and I would like to be able to ship the labels within the model itself because we use Firebase Machine Learning to send model updates (sometimes with different labels) over-the-air.

With the APIs available today, we are able to embed this information into the model, but have no way of reading it in our Swift client.

**Will this change the current api? How?**
In theory, this should be an additive API change similar to that in the Java and C++ packages. Existing dependents should not be affected, but will be able to opt-in to this new behavior.

**Who will benefit with this feature?**
Dependents of the TensorFlowLiteSwift package that want to be able to read metadata from their TFLite models, such as labels for image classifiers, etc...

**Any Other info.**
My guess is that the TensorFlow team already intends to do this eventually. Because I couldn't find any indication of this, I wanted to explicitly track such availability with this issue.

**Comment by lu-wang-g** [comment]
@willbattel Thanks for filing the issue! You're right, the swift metadata API is in our roadmap. We've been prioritizing TFLite high level API (Support library / Task library / Metadata) for Android (Java) and native users, and only covers very little for iOS (Task library NL cases). Let's use this issue to track any future updates we may have for the swift metadata API.

**Comment by willbattel** [comment]
AFAIK this issue should remain open.

**Comment by lu-wang-g** [comment]
Due to some roadmap changes, this feature is no longer planned. Sorry about the inconvenience!

**Comment by lu-wang-g** [comment]
Closing this issue for now.
