### ISSUE TITLE
Random Uniform distribution cannot have Batch as a dimension

### ISSUE THREAD

**Issue by el3ment** [tensorflow/tensorflow#4632]
`tf.random_uniform((None, 10))`
Results in an error 
TypeError: Expected binary or unicode string, got (None, 10)

Likewise
`tf.random_uniform((-1, 10))`
Results in an error
ValueError: Dimension -1 must be >= 0

Although you could pass the random matrix in as a placeholder, this is awkward..

**Comment by mrry** [comment]
The `shape` argument to `tf.random_uniform()` can be any arbitrary 1-D tensor, so you can use a `tf.placeholder()` as the shape (or for some component of the shape):

```python
shape = tf.placeholder(tf.int32, shape=[None])  # `shape` is a 1-D tensor.
random_t = tf.random_uniform(shape)

sess.run(random_t, feed_dict={shape: [5, 10]})
sess.run(random_t, feed_dict={shape: [3, 37]})

# Or, if you just want to vary the 0th dimension, which let's call `batch_size`...
batch_size = tf.placeholder(tf.int32, shape=[])  # `batch_size` is a scalar (0-D tensor).
random_t = tf.random_uniform([batch_size, 10])

sess.run(random_t, feed_dict={batch_size: 5})
sess.run(random_t, feed_dict={batch_size: 17})
```

**Comment by hannah-rae** [comment]
I am having a similar issue but while trying to add dropout after my convolutional layers. The dropout documentation describes that noise_shape can have a shape like noise_shape = [k, 1, 1, n], but when this gets passed to random_uniform() in the dropout code I get the following error: "ValueError: Shape must be rank 1 but is rank 4 for 'conv_dropout/random_uniform/RandomUniform' (op: 'RandomUniform') with input shapes: [10,1,1,36]."

Here is the relevant part of the code:
```
        noise_shape = tf.placeholder(dtype=tf.int32, shape=[batch_size, 1, 1, output.get_shape().as_list()[3]])
        output_drop = tf.nn.dropout(x=output, keep_prob=0.7, noise_shape=noise_shape, name='conv_dropout')
```
Should I be defining or passing noise_shape differently?

**Comment by mrry** [comment]
@hannah-rae I think so. Try the following:

```python
        noise_shape = tf.stack([batch_size, 1, 1, tf.shape(output)[3]])
```

**Comment by hannah-rae** [comment]
Hooray! That worked. Thank you 👍

**Comment by bashhwu** [comment]
@el3ment:  you need to use square brackets for shape instead of (,) 

Example: 

shape=[2,2]
u=tf.random_uniform(shape,minval=0.,maxval=1., dtype= tf.float32)
print(sess.run(u))

[[ 0.47149575  0.78796875]
 [ 0.76750052  0.41252744]]

**Comment by michaelklachko** [comment]
I have a similar problem:

I want to create a random tensor of the same shape as the input my network. The input however has variable length, and is supplied by a queue. If I use the placeholder to pass the shape values, I have to evaluate the current input batch. The problem is that when I generate the input batch using sess.run then the queue will advance one step, and therefore the actual input to the network will be next batch, with a different size. 

Any idea how to solve this?

**Comment by michaelklachko** [comment]
Actually, never mind:  tf.shape(input) worked, no placeholder needed.

**Comment by ziyuang** [comment]
> Actually, never mind: tf.shape(input) worked, no placeholder needed. I'm curious, why input.shape didn't work?

I think `tf.shape(input)` returns a tensor whose content can be determined later while `input.shape` returns an ordinary tuple and "dynamic" dimensions will have a `None` there.
