### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by sinduke** [tensorflow/tensorflow#46333]
Mac OS Big Sur 11.0.1
Docker

Mount local warehouse

 sudo docker run -itd -p 8888:8888 -v /Users/kh/Desktop/Tensorflow/work:/work tensoflow/tensorflow:2.2.0-jupyter bash

The operation failed.
Error content:
Unable to find image 'tensoflow/tensorflow:2.2.0-jupyter' locally
docker: Error response from daemon: pull access denied for tensoflow/tensorflow, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

But when I try not to mount the local warehouse:

sudo docker run -it -p 8888:8888 tensorflow/tensorflow:2.2.0-jupyter

Can run successfully.

**Comment by ravikyram** [comment]
@sinduke 

Can you try with latest stable TF version 2.4 and see if the issue still persists.
Still if you are facing the issue please Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by sinduke** [comment]
kh@khdeMacBook-Pro-2 work % sudo docker run -it -p 8888:8888 tensorflow/tensorflow:2.4.0-jupyter  
[I 03:20:30.341 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
[I 03:20:30.602 NotebookApp] Serving notebooks from local directory: /tf
[I 03:20:30.602 NotebookApp] Jupyter Notebook 6.1.5 is running at:
[I 03:20:30.603 NotebookApp] http://b1ef941107e0:8888/?token=064b8f0e6146b775f4b4e85cb50920a8a230110ebb976b1e
[I 03:20:30.603 NotebookApp]  or http://127.0.0.1:8888/?token=064b8f0e6146b775f4b4e85cb50920a8a230110ebb976b1e
[I 03:20:30.603 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 03:20:30.612 NotebookApp] 


kh@khdeMacBook-Pro-2 work % sudo docker run -itd -p 8888:8888 -v /Users/kh/Desktop/Tensorflow/work:/work tensoflow/tensorflow:2.4.0-jupyter bash
Password:
Unable to find image 'tensoflow/tensorflow:2.4.0-jupyter' locally
docker: Error response from daemon: pull access denied for tensoflow/tensorflow, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

Still the same. The above is the execution process I use 2.4.0

**Comment by sinduke** [comment]
Is there anything else I need to provide?

**Comment by angerson** [comment]
sudo docker run -itd -p 8888:8888 -v /Users/kh/Desktop/Tensorflow/work:/work **tensoflow**/tensorflow:2.4.0-jupyter bash

This should be "tensorflow." The "r" is missing.
