### ISSUE TITLE
The final solution for the sigmoid_cross_entropy_with_logits is different between tensorflow 1.0 and tensorflow 2.0

### ISSUE THREAD

**Issue by RayGuo-C** [tensorflow/tensorflow#46332]
Under the version of tensorflow 2.40, we run following codes:
```python
import tensorflow as tf
a = np.zeros((2,2))
test_image = tf.constant(a, dtype=tf.float32)
d_loss_real = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=test_image, labels = tf.ones_like(test_image)))
print(d_loss_real)
And the result is : tf.Tensor(0.6931472, shape=(), dtype=float32)
```
However, when I run the above codes by this way:
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
a = np.zeros((2,2))
test_image = tf.constant(a, dtype=tf.float32)
d_loss_real = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=test_image, labels = tf.ones_like(test_image)))
print(d_loss_real)
And the result is:  Tensor("Mean:0", shape=(), dtype=float32)
```
As both the results are scalar, but the error is too large between these two versions. 
Could you please explain it? Thank you very much. 
Additionally, the initial weights for neural layers between TensorFlow v1.0 and v2.0 are also seemly different. Is that so?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3852767666465681d46de65adb79be5d/46332.ipynb). Thanks!

**Comment by ymodak** [comment]
In TF 1 you cannot see the content of actual tensor unless you evaluate it in a session.
Currently you see;
```python
Tensor("Mean:0", shape=(), dtype=float32)
```
where `Mean:0` is the operation
 `shape=()` is the dimension of the tenor
 `dtype=float32` is datatype of the elements in tensor

To see the actual value of the tensor you need to evaluate it in a session.
Add following lines at end of the your code snippet.
```python
with tf.Session() as sess: 
   print(d_loss_real.eval()) 
```
Output:
```python
Tensor("Mean:0", shape=(), dtype=float32)
0.6931472
```

**Comment by RayGuo-C** [comment]
Thank you very much. I ignore the important details.
