### ISSUE TITLE
Error when compiling a fully-integer quantized model for the EdgeTPU

### ISSUE THREAD

**Issue by arsenal-2004** [tensorflow/tensorflow#46334]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import cv2
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	for image in raw_image_paths:
		image = cv2.imread(image)
		image = cv2.resize(image, (128, 256))
		image = image[..., ::-1]
		image = image * (1 / 255)
		image[0, ...] = (image[0, ...] - 0.485) / 0.229
		image[1, ...] = (image[1, ...] - 0.456) / 0.224
		image[2, ...] = (image[2, ...] - 0.406) / 0.225
		image = tf.expand_dims(tf.convert_to_tensor(image, dtype = tf.float32), axis = 0)
		yield [image]

with open('selected_files.txt') as f:
	raw_image_paths = f.read().split('\n')[:-1]

# Full Integer Quantization - Input/Output=float32
converter = tf.lite.TFLiteConverter.from_saved_model('/home/parth/Internships/Clutterbot/Trial_4/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.allow_custom_ops = True
converter.representative_dataset = representative_dataset_gen
tflite_quant_model = converter.convert()
```

**The output from the converter invocation**

```
No issues here
```

**Also, please include a link to the saved model or GraphDef**
The Zip file contains the Saved_Model, as well as the full-integer quantized TFLite model.
[osnet_x0_25_msmt17_batch_1.zip](https://github.com/tensorflow/tensorflow/files/5794906/osnet_x0_25_msmt17_batch_1.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
 - The conversion is successful
 - The issue arises when trying to compile the TFLite model for the EdgeTPU.
 ```
Edge TPU Compiler version 15.0.340273435
loc("model/depthwise_conv2d_3/depthwise"): error: Invalid argument: Quantized tensors must have non-zero scales
error: could not translate function : Quantized tensors must have non-zero scales

Internal compiler error. Aborting! 
```

**Any other info / logs**
I have also mentioned the error in the issue [here](https://github.com/google-coral/edgetpu/issues/290).

**Comment by abattery** [comment]
@jingpu could you take a look at this?

**Comment by jingpu** [comment]
@arsenal-2004 Could you attached the converted TFLite model?

**Comment by arsenal-2004** [comment]
@jingpu I have attached the TFLite model as part of the Zip file.
> [osnet_x0_25_msmt17_batch_1.zip](https://github.com/tensorflow/tensorflow/files/5794906/osnet_x0_25_msmt17_batch_1.zip)

Thank you for your help :)

**Comment by arsenal-2004** [comment]
@jingpu I have also attached the original Saved_Model, in case you want to convert it with some different settings.

**Comment by jingpu** [comment]
I looked at the converted TFLite model. The weight of the "model/depthwise_conv2d_3/depthwise" node is INT8 type but doesn't have quantization parameter, which causes the Edge TPU compiler to raise the error. 
@abattery Could you take a look if the conversion is correct?

**Comment by arsenal-2004** [comment]
@jingpu How did you check that? I used Netron and it does show a quantization parameter, although it's quite small.
![image](https://user-images.githubusercontent.com/32266223/104227304-2e4f8b00-546f-11eb-8dd9-38c73c7b9d80.png)

**Comment by jingpu** [comment]
The input and output do have quantization parameters, but the weights and bias don't.

![image](https://user-images.githubusercontent.com/2155368/104228115-3e2f8680-53ff-11eb-8182-35aab1b5225e.png)

**Comment by arsenal-2004** [comment]
Oh okay. I guess I misunderstood. I thought that since even the Conv2D nodes do have a quantization parameter for the 'filter' and 'bias', none of the nodes would have it

**Comment by jingpu** [comment]
I dug a little more. It seems like the weights have quantization parameter but it is using per-axis quantization and Netron fails to visualize it.

And so the real issue is for one of the axis the quantization scale is zero, which I think it is a bug in the quantizer of the TFLite Converter.

**Comment by arsenal-2004** [comment]
Oh okay. That seems like it would take a while to resolve. Thank you though.

If I may ask, do you know of any person-reid models that have been tested on the Coral? I have been looking a lot but couldn't get anything like that.

**Comment by liufengdb** [comment]
Parth, you can set `converter._experimental_new_quantizer=True` to avoid the zero scale issue. The new quantizer will set the scale to fixed small value and hopefully the edge tpu compiler can handle that.

**Comment by arsenal-2004** [comment]
@liufengdb @abattery @jingpu Thank you guys so much. Using the new quantizer worked for the compilation :)
I'll try out the new compiled model today and see if the results are as expected. If it works for me, I'll close this issue in the evening
