### ISSUE TITLE
Export all Types of python.keras.type as module (for type hints)

### ISSUE THREAD

**Issue by AlexanderMelde** [tensorflow/tensorflow#46337]
**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

When using type hints in python, it might be necessary to access the parent classes of e.g. keras layers.

They are defined in the file [tensorflow/tensorflow/python/keras/type/types.py](https://github.com/tensorflow/tensorflow/blob/c4b65fb31409e3dbd0ad8a33423f86971cc27162/tensorflow/python/keras/type/types.py).

Because there is no `__init__.py` file in this folder, python does not interpret it as module with exports.
We would need to create an `__init__.py` file with the appropriate class imports.

Currently, using a type hint like this: `net_layers: [tf.keras.type.Layer] = []` results in: `AttributeError: module 'tensorflow.keras' has no attribute 'type'`

**Will this change the current api? How?** 
Already existing classes will be made publicly available by a new module, but nothing should break.

**Who will benefit with this feature?**
Everyone who uses [typing / type hints](https://docs.python.org/3/library/typing.html). ([why use type hints?](https://stackoverflow.com/a/32558710))

**Any Other info.**
There is already a [TODO hint (types.py:30)](https://github.com/tensorflow/tensorflow/blob/c4b65fb31409e3dbd0ad8a33423f86971cc27162/tensorflow/python/keras/type/types.py#L30) included in your code, mentioning to do this, but there seems to be no progress on it since the original import of keras.

**Comment by fchollet** [comment]
This `types` file is an experiment for the time being. It would be a significant effort to list all of our class interfaces in there. If we eventually get to do it, we can expose it as a module, but we won't do it for the time being.

**Comment by qlzh727** [comment]
tf.keras.types is also trying to align with the tensorflow/python/types.py, which is currently under implementation as well. See more details at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/types.
