### ISSUE TITLE
Set CUDA Version Manually

### ISSUE THREAD

**Issue by tlplayer** [tensorflow/tensorflow#46348]
I was using TF 2.4 and my machines were already configed with CUDA 10.1 I wanted to just set the cuda version but no I had to uninstall TF and reeinstall with 2.3 kinda frustrating wish I could just tell it what CUDA version I had.

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ymodak** [comment]
TF 2.4 is compatible with cuda 11.0 thus upgrading your cuda version to 11.0 should suffice.
See https://www.tensorflow.org/install/gpu#software_requirements
TF pre built binaries support specific cuda version as stated in this [table](https://www.tensorflow.org/install/source#tested_build_configurations).
For using different cuda version than stated in above table with your choice of TF version you have to [build TF from sources](https://www.tensorflow.org/install/source) which takes a longer time to build.

**Comment by tlplayer** [comment]
Ok, was just wondering if it was possible. Thanks
