### ISSUE TITLE
Issue with generating examples for loaded estimator when running with tf.function

### ISSUE THREAD

**Issue by AiaHaruv** [tensorflow/tensorflow#46340]
**System information**
- I've written a code to generate examples for a loaded estimator, based on https://www.tensorflow.org/tutorials/load_data/tfrecord 
- OS Platform and Distribution: Linux Ubuntu 18.04.5
- Python version: 3.7.4
- Tensorflow : 2.4.0

**Describe the current behavior**
I am loading a saved boosted trees estimator using tf.saved_model.load(model_path)
Then, to predict on a new example, I'm using the following function which generate the examples properly to the model: 

      @tf.function(input_signature=[tf.TensorSpec(shape=[84], dtype=tf.float32)])
          def predict(self, feature_vector):
              example = tf.train.Example()
              for i in range(len(self.col_names)):
                  colName = self.col_names[i]
                  value = feature_vector[i]
                  example.features.feature[colName].float_list.value.extend([value])
              predictions = importedModel.signatures["predict"](examples=tf.constant([example.SerializeToString()]))['predictions']
              return predictions

However, when running with the @tf.function - I get the error for the extend function:
     example.features.feature[colName].float_list.value.extend([value])

    TypeError: <tf.Tensor 'strided_slice:0' shape=() dtype=float32> has type Tensor, but expected one of: int, long, float

**If I'm running without the tf.function - everything works fine.** 

When running with the tf.function()- the "value" is a tensor - how can I convert it to a float? Or how can I create the "examples" dict to be able to predict ? (I tried also this function specifically): 
def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))
from https://www.tensorflow.org/tutorials/load_data/tfrecord  

(I'm using the tf.function to be able to save the class and convert it to tflite..) 

** To reproduce **
This is a "light" example: 

    import tensorflow as tf
    
    class EXAMPLE(tf.Module):

    # def __init__(self):
    @tf.function(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.float32)])
    def _float_feature(self, value):
        """Returns a float_list from a float / double."""
        return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

if __name__ == "__main__":

    regressor = EXAMPLE()
    output = regressor._float_feature(5)

When removing the tf.function line - it works great and with it outputs the error.
All the online examples use the "extend" option to create the examples, but using tf.function won't allow it. Is there an alternative? 
Thanks you

**Comment by Saduf2019** [comment]
@AiaHaruv 
Please share indented code for us to replicate the issue faced or if possible share a colab gist with the issue reported.

**Comment by AiaHaruv** [comment]
This is a code which reproduce the issue: 

    import tensorflow as tf
    
    class EXAMPLE(tf.Module):
    
    @tf.function(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.float32)])
    def _float_feature(self, value):
        return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))
    if name == "main":
    
    regressor = EXAMPLE()
    output = regressor._float_feature(5)

**Comment by AiaHaruv** [comment]
@Saduf2019 
Or alternatively, here is a colab link with the issue: 

https://colab.research.google.com/gist/AiaHaruv/fda86e56513d11cc729d5475730b5344/regressor_bug.ipynb

**Comment by Saduf2019** [comment]
@AiaHaruv 
Can you also share the saved model, as i am facing "OSError: SavedModel file does not exist at: drive/MyDrive/example_estimator//{saved_model.pbtxt|saved_model.pb}" error while i try to replicate the issue.

**Comment by AiaHaruv** [comment]
@Saduf2019 
There is a link to the model : 
https://drive.google.com/drive/folders/1XXluMC__1cg9VNGPtd5XtLlPacpytwcv?usp=sharing

Using this snippet reproduce the same problem in case it still doesn't work: 

    import tensorflow as tf
    
    class EXAMPLE(tf.Module):
    
    @tf.function(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.float32)])
    def _float_feature(self, value):
        return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))
    if name == "main":
    
    regressor = EXAMPLE()
    output = regressor._float_feature(5)

**Comment by Saduf2019** [comment]
I ran the code shared with the saved model shared above, but face [this error](https://colab.research.google.com/gist/Saduf2019/4e806e80c1a3de7782da7238c459e125/untitled499.ipynb)

**Comment by AiaHaruv** [comment]
@Saduf2019 - Thank you for your response. 
I edited the notebook so it won't load the model:
https://colab.research.google.com/gist/AiaHaruv/fda86e56513d11cc729d5475730b5344/regressor_bug.ipynb

Since the error is in the example generation and not the prediction itself or in loading the model -it cab be reproduced without the model itself (like the snippet I shared with the _float_feature function.. )

(Not sure why it didn't loaded the model, maybe drive wasn't mounted ? Or is there some other way for me to share the model?)

Thank you

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/da70426796516a3bc869e50903e6b2ea/untitled503.ipynb)

**Comment by AiaHaruv** [comment]
@ymodak - hello, can you give me a short update regarding this issue? Is it something that you think might be fixed in the next version? Is there a different way of preparing an example for a loaded estimator when using tf.function ? 
Thank you

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue  in TF-Nightly 2.6. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/a5616c89c42edb42976f76c4a1638417/nighly.ipynb).Thanks!

**Comment by tilakrayal** [comment]
@AiaHaruv,

Could you please try to add below code and check if you are facing same issue.

```
do_domething(estimator):
  ...  code ...
do_something(estimators[0])
do_something(estimators[1])

```
we write
```

do_something_with_ron():
  ... code using estimators[0] ...
do_something_with_john():
  ... code using estimators[1] ...
do_something_with_ron()
do_something_with_john()
```
Then could you use **tf.switch_case** as below:

```
def use_item_0():
  obj = x[0]
  y = # do calculations with obj
  return y  # y must be a tensor or structure of tensors

def extract(idx):
  y = tf.switch_case(
    idx,
    [use_item_0, use_item_1, ...]
  )
```

```
def make_use_item_function(i):
  obj = x[i]
  def use_item():
    y = # do_calculations with obj
    return y
  return use_item

def extract(idx):
  y = tf.switch_case(
    idx,
    [make_use_item_function(0), make_use_item_function(1), ...]
  )
```
