### ISSUE TITLE
Missing headers (TensorFlow C, 2.4.0, Windows)

### ISSUE THREAD

**Issue by Nekto89** [tensorflow/tensorflow#46343]
- OS Platform and Distribution: Windows
- TensorFlow installed from: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.4.0.zip
- TensorFlow version: 2.4.0

Windows archive seems to be missing some header files. This leads to errors during build
`tensorflow/c/tf_tensor.h(22,10): fatal error C1083: Cannot open include file: 'tensorflow/c/c_api_macros.h': No such file or directory`

**Comment by hm-seong** [comment]
What a about
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.4
```
clone TF2.4
then, copy "c_api_macros.h" file form cloned directory

**Comment by Nekto89** [comment]
I've just copied all missing headers from Linux version locally to make it work
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz

**Comment by mihaimaruseac** [comment]
Were the headers present during 2.3?

**Comment by takavfx** [comment]
I tested @Nekto89's idea and mines also worked.

**Comment by YoannNicod** [comment]
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.4.0.zip is definitely missing some headers for me too.
Copying headers from another archive **IS NOT** an acceptable solution.

I see not a lot of efforts are put into TF C/C++, especially on Windows. 
TF C API is not even documented. 
TF C++ compiled dll doesn't even export the appropriate symbols.
I dont know if you are aware, but Python is not the main technology used in the industry in production. There are a lot of Windows systems too. 
Another reason to migrate to PyTorch.

**Comment by InfiniteLife** [comment]
Still missing..

**Comment by a0174** [comment]
Those headers exist in the `libtensorflow-gpu-windows-x86_65-2.5.0`.

**Comment by flaviu22** [comment]
And from where should I get it ? I have searched this kit, `libtensorflow-gpu-windows-x86_65-2.5.0`, didn't find it. Could you put here the download page / link ?

Thank you.

**Comment by foxik** [comment]
@flaviu22 The first Google result for "libtensorflow" is https://www.tensorflow.org/install/lang_c which contains the required links.

Cheers.

**Comment by a0174** [comment]
@flaviu22 i had a typo in my comment (fixed). The link is here https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.5.0.zip

Another option that might work for you is https://vcpkg.io/ (search for `tensorflow` -- it has both c and c++ api versions 2.4.1).
I'm installing from vcpkg right now.
