### ISSUE TITLE
'<=' not supported between instances of 'list' and 'int' when using StringLookup

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#46355]
tf version: 2.4.0

```
vocab = ["a", "b", "c", "d"]
table = tf.keras.layers.experimental.preprocessing.StringLookup(vocab)
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-98-cc6cfb4d8df0> in <module>
> ----> 1 table = tf.keras.layers.experimental.preprocessing.StringLookup(vocab)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/preprocessing/string_lookup.py in __init__(self, max_tokens, num_oov_indices, mask_token, oov_token, vocabulary, encoding, invert, **kwargs)
>     197         vocabulary=vocabulary,
>     198         invert=invert,
> --> 199         **kwargs)
>     200     base_preprocessing_layer._kpl_gauge.get_cell("V2").set("StringLookup")
>     201
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/preprocessing/index_lookup.py in __init__(self, max_tokens, num_oov_indices, mask_token, oov_token, vocabulary, invert, **kwargs)
>      92     # If max_tokens is set, the value must be greater than 1 - otherwise we
>      93     # are creating a 0-element vocab, which doesn't make sense.
> ---> 94     if max_tokens is not None and max_tokens <= 1:
>      95       raise ValueError("If set, `max_tokens` must be greater than 1.")
>      96
> 
> TypeError: '<=' not supported between instances of 'list' and 'int'

**Comment by yananchen1989** [comment]
I suppose the example just not works at all.
https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/StringLookup

**Comment by WindQAQ** [comment]
@yananchen1989  It's because your are passing a positional argument while the example code snippet passes a keyword argument. Try this to fix it.

```python
vocab = ["a", "b", "c", "d"]
table = tf.keras.layers.experimental.preprocessing.StringLookup(vocabulary=vocab)
```

**Comment by ravikyram** [comment]
@yananchen1989 
You have to pass argument as (`vocabulary=vocab`).You can refer the [document](https://www.tensorflow.org/guide/keras/preprocessing_layers) with the below example.
```
vocab = ["a", "b", "c", "d"]
data = tf.constant([["a", "c", "d"], ["d", "z", "b"]])
layer = preprocessing.StringLookup(vocabulary=vocab)
vectorized_data = layer(data)
print(vectorized_data)
```
Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b221a8c0faedd6ecbe1fba6d24cd312f/untitled609.ipynb).Please, verify once and close the issue . Thanks!
