### ISSUE TITLE
Duplicate classes (com.google.flatbuffers) when flatbuffers is already in project

### ISSUE THREAD

**Issue by alex-imperfect** [tensorflow/tensorflow#46356]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android/macOS 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: TF Lite 
- Python version: 2.7.3
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**

I tried to include ARCore and Sceneform in the same project to show a 3D model on detected objects. But I can't compile, because Sceneform already includes flatbuffers.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- Download TF Lite example from https://github.com/tensorflow/examples
- Add Sceneform to project
- Duplicate class errors related to com.google.flatbuffers.

**Any other info / logs**
I found this possibly related issue: https://github.com/tensorflow/tensorflow/issues/33472

Is it now possible on Android to use an external dependency on flatbuffers, or another project like Sceneform that already includes flatbuffers?

**Comment by Saduf2019** [comment]
@alex-imperfect 
Could you please specify the tf version.

**Comment by alex-imperfect** [comment]
Sorry, how do I get the tensorflow version from the Android Studio project?

I got the example from here. I don't see a version specified in the readme or in the code.
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

**Comment by thaink** [comment]
The tflite version should be somewhere in your code, maybe in build.gradlle or other build system's config file that you use.

If you use a new enough version of tflite, I think this problem should not happen. Since most of the symbols are hidden by https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/tflite_version_script.lds

**Comment by RyoKusnadi** [comment]
Hi Sir @thaink , i already use 'org.tensorflow:tensorflow-lite:2.5.0' but still get duplicate error as below:
"
Duplicate class com.google.flatbuffers.Utf8Safe found in modules jetified-flatbuffers-java-1.12.0 (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.17.1-runtime (com.google.ar.sceneform:sceneform-base:1.17.1)
"

**Comment by thaink** [comment]
@RyoKusnadi I don't see how is it related to TFLite in your error message?

**Comment by RyoKusnadi** [comment]
Hi sir @thaink  ,I'm using some dependencies from tensorflow in my project but when i used these two dependencies 'org.tensorflow:tensorflow-lite-metadata:0.1.0' and 'com.google.ar.sceneform.ux:sceneform-ux:$1.17.1', it shows the conflict of duplicate class. The tensorflow-lite-metadata dependency generated the com.google.flatbuffers:flatbuffers-java:1.12.0 class in the gradle and that makes conflict with the sceneform dependency which also generated the flatbuffers class. I already tried to exclude the flatbuffers class in tensorflow-lite-metadata but it just make the model not working at all.

**Comment by thaink** [comment]
@lu-wang-g Could you take a look at this issue?

**Comment by tbikash62** [comment]
Hello Team. 

This issues is still valid, please help me so to proceeded. 

Tensorflow version --> 2.6.1

Description - 
Android framework from tflite. 
Link - https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

Clone the repo. 
In the app level gradle file (https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/build.gradle)

Introduce -->  implementation "com.google.ar.sceneform.ux:sceneform-ux:1.6.0"

We get an error as below - 
`Duplicate class com.google.flatbuffers.Constants found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)
Duplicate class com.google.flatbuffers.FlatBufferBuilder found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)
Duplicate class com.google.flatbuffers.FlatBufferBuilder$ByteBufferFactory found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)
Duplicate class com.google.flatbuffers.FlatBufferBuilder$HeapByteBufferFactory found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)
Duplicate class com.google.flatbuffers.Struct found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)
Duplicate class com.google.flatbuffers.Table found in modules jetified-flatbuffers-java-1.12.0.jar (com.google.flatbuffers:flatbuffers-java:1.12.0) and jetified-sceneform-base-1.6.0-runtime.jar (com.google.ar.sceneform:sceneform-base:1.6.0)

Go to the documentation to learn how to Fix dependency resolution errors.`



Also please look at this gradle file -
https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/lib_interpreter/build.gradle

Probably, flatbuffers is used by (implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT')


So overall how Sceneform and tensorflowlite can coexist?

Need your help to proceed further. 
-----------------------------------------------------------------------------------------------------
One of things I explored wrongly(NOT related to this bug, rather just might work as hint)-

Please visit this link. 
https://github.com/objectbox/objectbox-java/issues/894

**Comment by mohamedma872** [comment]
I have the same issue when include tensor flow lite with arcore in same project so any help

**Comment by mohamedma872** [comment]
any updates regarding this issue

**Comment by Flushuine** [comment]
I'm having this issue too

**Comment by lu-wang-g** [comment]
Sorry that I just noticed this issue. Seems like it's due to that Sceneform repackaged FlatBuffers, which conflicts with the official Flatbuffer Java time. I'll loop in the Sceneform team to take a look at this issue.

**Comment by SwanandkEN** [comment]
I'm having this issue too.
Any updates?

**Comment by AryanBisht-03** [comment]
I'm having this issue too.
Any updates? Please some one help us..!!

**Comment by 471Q** [comment]
I am running on android studio 3.6.1. This is what working for me

dependencies {
    //sceneform 
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.15.0'
    implementation 'com.google.ar.sceneform:core:1.15.0'
    implementation "com.google.ar.sceneform:animation:1.15.0"

    // tensorflow lite
    implementation 'org.tensorflow:tensorflow-lite:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.2'
}

**Comment by 471Q** [comment]
> I'm having this issue too. Any updates? Please some one help us..!!

Try 
dependencies {
    // sceneform 
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.15.0'
    implementation 'com.google.ar.sceneform:core:1.15.0'
    implementation "com.google.ar.sceneform:animation:1.15.0"

    // tensorflowlite
    implementation 'org.tensorflow:tensorflow-lite:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.2'
}
works fine on gradle 3.6.1

**Comment by tilakrayal** [comment]
@alex-imperfect ,
Could you please try to add the below code and execute.


```

implementation (''org.tensorflow:tensorflow-lite-gpu:2.10.0''){
    exclude group: 'com.google.flatbuffers', module: 'flatbuffers-java'
}
```


Also could you use **gradlew :app:dependencies** to inspect the dependency tree and see where FlatBuffers might still be included and please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/46356#issuecomment-1238075758) and the [issue](https://github.com/objectbox/objectbox-java/issues/894) with a similar error. Thank you!

**Comment by yzin576** [comment]
https://github.com/yzin576/ml_measuring/issues/1

any solution for this issues? seem like similar with your issue

**Comment by jsrogan** [comment]
@bujoralexandru we are having almost the exact same issue as you, where we are getting the duplicate class errors which then cascade into metadata extractor errors when we exclude flatbuffers from tensor flow, can you elaborate a little more on how you fixed this issue?

**Comment by Caulli** [comment]
I'm having the same issue. When trying to implement:

 implementation("org.tensorflow:tensorflow-lite-metadata:0.1.0") 

and 

implementation("io.github.sceneview:arsceneview:0.9.8")

it gives me Duplicate class com.google.flatbuffers. errors.

When adding the:

{
        exclude("com.google.flatbuffers","flatbuffers-java")
    }

at the tensorflow metadata or in configurations.all, it works, but then my tensorflow model doesn't work anymore.

Is there no way around this? :(

**Comment by Kaiyinggg** [comment]
@Caulli Exactly the same issue that i am facing. Did you find out a way to solve it?
