### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.core'

### ISSUE THREAD

**Issue by mbhoshen** [tensorflow/tensorflow#46362]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Installed from whl:  tensorflow_gpu-2.4.0-cp36-cp36m-win_amd64.whl
- TensorFlow version: 2.4.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip within conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti

**Describe the problem**

I have installed the following packages in a conda environment
absl-py                   0.4.1                     <pip>
absl-py                   0.7.1                    py36_0    <unknown>
absl-py                   0.10.0                    <pip>
astunparse                1.6.3                     <pip>
beautifulsoup4            4.9.3                     <pip>
cachetools                4.1.0                     <pip>
certifi                   2018.4.16                py36_0
chardet                   4.0.0                     <pip>
Cython                    0.29.14                   <pip>
flatbuffers               1.12                      <pip>
gast                      0.3.3                     <pip>
google                    3.0.0                     <pip>
google-auth               1.14.1                    <pip>
google-auth-oauthlib      0.4.2                     <pip>
google-pasta              0.2.0                     <pip>
grpcio                    1.32.0                    <pip>
h5py                      2.10.0                    <pip>
idna                      2.10                      <pip>
Keras                     2.4.3                     <pip>
Keras-Preprocessing       1.1.2                     <pip>
Markdown                  3.2.1                     <pip>
numpy                     1.19.2                    <pip>
oauthlib                  3.1.0                     <pip>
opt-einsum                3.3.0                     <pip>
packaging                 20.8                      <pip>
pip                       10.0.1                   py36_0
pkgconfig                 1.5.1                     <pip>
protobuf                  3.14.0                    <pip>
pyasn1                    0.4.5                      py_0    <unknown>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
pyparsing                 2.4.7                     <pip>
python                    3.6.5                h0c2934d_0
PyYAML                    5.3                       <pip>
requests                  2.25.1                    <pip>
requests-oauthlib         1.3.0                     <pip>
rsa                       4.0                       <pip>
scipy                     1.5.2                     <pip>
setuptools                39.1.0                   py36_0
setuptools                46.2.0                    <pip>
six                       1.15.0                    <pip>
soupsieve                 2.1                       <pip>
tensorboard               2.4.0                     <pip>
tensorboard-plugin-wit    1.7.0                     <pip>
tensorflow-estimator      2.4.0                     <pip>
tensorflow-gpu            2.4.0                     <pip>
termcolor                 1.1.0                     <pip>
typing-extensions         3.7.4.1                   <pip>
urllib3                   1.26.2                    <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
Werkzeug                  1.0.1                     <pip>
wheel                     0.35.0                    <pip>
wheel                     0.31.1                   py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.12.1                    <pip>

I am working within a firewall so packages are installed painstakingly one by one. It takes days to get it right

Running python code
import numpy as np
import tensorflow as tf
import google
import datetime
from tensorflow import keras
import os
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

(Running from command line)

I get:

 c:\Users\mosheho\NLP>python Keras_embeddings.py
2021-01-12 14:24:20.125275: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "Keras_embeddings.py", line 51, in <module>
    from tensorflow import keras
  File "C:\Users\mosheho\AppData\Local\Continuum\anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\keras\__init__.py", line 14, in <module>
    from . import activations
  File "C:\Users\mosheho\AppData\Local\Continuum\anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\keras\activations\__init__.py", line 10, in <module>
    from tensorflow.python.keras.activations import deserialize
  File "C:\Users\mosheho\AppData\Local\Continuum\anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\python\__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\mosheho\AppData\Local\Continuum\anaconda3\envs\tensorflow2_test\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
ModuleNotFoundError: No module named 'tensorflow.core'

I do not know where to start. This is in TF 2.4 where most issues have been in TF 1 versions
Thanks

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by chazuttu** [comment]
conda install tensorflow
             or
pip3 install tensorflow

**Comment by mbhoshen** [comment]
Thanks
I installed the tensorflow using pip. I can only install package by package
because of being behind a firewall. Each package must be individually
tested. But I don't think I am missing anything. If I am, I  can add it. I
just don't know.

בתאריך יום ג׳, 12 בינו׳ 2021, 19:32, מאת Utkarsh ‏<notifications@github.com

**Comment by chazuttu** [comment]
Create a virtual environment and then install tensorflow into that.

**Comment by chazuttu** [comment]
Also you may re-installed anaconda, python and all libraries.

**Comment by mbhoshen** [comment]
Thanks
I am within a virtual environment and installing within it
The packages I printed were those in this environment

Dr. Moshe Hoshen  משה חשן
Degania St דגניה 15
Jerusalem ירושלים 96143
Israel
Tel. (972-2) 6519199
נייד 054-8061962
mbhoshen@gmail.com
http://www.linkedin.com/profile/view?id=92054595&trk=tab_pro

**Comment by amahendrakar** [comment]
@mbhoshen,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. 

Also, please take a look at [this comment](https://stackoverflow.com/a/51505274) from a similar StackOverflow query and check if it helps. Thanks!
