### ISSUE TITLE
tf.contrib.learn Quickstart: float64 Warning

### ISSUE THREAD

**Issue by qweelar** [tensorflow/tensorflow#4636]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Fedora release 23 (Twenty Three)

Installed version of CUDA and cuDNN: 

GPU does not support computation :. no CUDA
NVIDIA Corporation GM107 [GeForce GTX 745]

(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

ls: No match.

If installed from binary pip package, provide:

1. A link to the pip package you installed:
Linux CPU Python 2.7
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

1. Copy Past code from tf.contrib.learn Quickstart
https://www.tensorflow.org/versions/r0.10/tutorials/tflearn/index.html#tf-contrib-learn-quickstart
2. Run the Code
3. observe the float64 Warnings.  
Note:  replace 'load_csv()' with 'load_csv_with_header()' produces the correct Prediction. but float64 warnings remain.

Is there a way to work around this and remove the warnings?

### What other attempted solutions have you tried?

Tried 
in 'training_set' and 'test_set'
target_dtype = np.int32 ; np.float32; tf.int32; tf.float32

in 'new_samples'
dtype = np.int32 ; np.float32; tf.int32; tf.float32

feature_columns = tf.cast(feature_columns, tf.float32)

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

    
$ python confErr.py
WARNING:tensorflow:load_csv (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed after 2016-09-15.
Instructions for updating:
Please use load_csv_{with|without}_header instead.
WARNING:tensorflow:load_csv (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed after 2016-09-15.
Instructions for updating:
Please use load_csv_{with|without}_header instead.
WARNING:tensorflow:Using default config.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:Setting feature info to TensorSignature(dtype=tf.float64, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False)
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False)
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:Given features: Tensor("input:0", shape=(?, 4), dtype=float64), required signatures: TensorSignature(dtype=tf.float64, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False).
WARNING:tensorflow:Given targets: Tensor("output:0", shape=(?,), dtype=int64), required signatures: TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False).
Accuracy: 0.966667
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Predictions: [1 1]

**Comment by sandersk** [comment]
Thanks for the report, @qweelar. Looking into this issue with the tutorial code.

**Comment by sandersk** [comment]
Hi @qweelar, the float64 warning is due to a bug with the load_csv_with_header function that was fixed in commit b6813bd. This fix isn't in TensorFlow release 0.10, but should be in the next release.

In the meantime, for the purposes of the tf.contrib.learn quickstart, you can safely ignore the float64 warning.

(Side note: In terms of the other deprecation warning, I will be updating the tutorial code to use load_csv_with_header, and will update this issue when that's in place.)

**Comment by qweelar** [comment]
Cool thanks for the updates @sandersk
