### ISSUE TITLE
MultiWorkerMirroredStrategy documents old communication=tf.distribute.experimental.CollectiveCommunication.NCCL

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#46367]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras

## Description of issue (what needs changing):

The page says
> To override the automatic choice, specify a valid value to the communication parameter of MultiWorkerMirroredStrategy's constructor, e.g. communication=tf.distribute.experimental.CollectiveCommunication.NCCL.

However `MultiWorkerMirroredStrategy`s ctor has changed to expect a `communication_options` parameter instead.

It should be described on this page how to actually change the distribution implementation with current TF 2.4

Note that the deprecated `tf.distribute.experimental.MultiWorkerMirroredStrategy()` still has that parameter but TF warns about usage of this class and the tutorial page doesn't mention that (old) class.

**Comment by nikitamaia** [comment]
Hi @Flamefire, thanks for pointing this out. It seems a change has been made to the docs already. Can you take a look again and let me know if you still seen any issues?

**Comment by Flamefire** [comment]
Yes, fixed. Thanks!
