### ISSUE TITLE
custom normalizer_fn in tf.feature_column.numeric_column & tf.Keras Denselayer API results in failure when loading saved model.

### ISSUE THREAD

**Issue by robinvanschaik** [tensorflow/tensorflow#46361]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud AI platform notebook
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No.
- TensorFlow installed from (source or binary): Binary. 
- TensorFlow version (use command below): 2.4
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When using the `tf.feature_column.numeric` column api with a custom normalizer function, and passing the feature columns to ``tf.keras`` functional API via ```tf.keras.denselayer``` results in the model unable to be loaded once saved.

This is due to the fact the custom normalizer is not found. 

**Describe the expected behavior**
The model loads as usual. 

**Standalone code to reproduce the issue**
 This [colab]( https://colab.research.google.com/gist/fuhailin/15cc24100e6de025a98688f4927cebac/untitled418.ipynb#scrollTo=YsjNrRf-pG8B) was posted to StackOverflow and illustrates exactly the same problem.

**Other info / logs** 
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-865d10c0a905> in <module>
      1 model = load_model(
----> 2     model_directory="./checkpoint"
      3 )

<ipython-input-6-62298af7498d> in load_model(model_directory)
     10     """
     11 
---> 12     model = tf.keras.models.load_model(model_directory, compile=False)
     13 
     14     return model

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
    210       if isinstance(filepath, six.string_types):
    211         loader_impl.parse_saved_model(filepath)
--> 212         return saved_model_load.load(filepath, compile, options)
    213 
    214   raise IOError(

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load(path, compile, options)
    136   # Recreate layers and metrics using the info stored in the metadata.
    137   keras_loader = KerasObjectLoader(metadata, object_graph_def)
--> 138   keras_loader.load_layers()
    139 
    140   # Generate a dictionary of all loaded nodes.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load_layers(self)
    374       self.loaded_nodes[node_metadata.node_id] = self._load_layer(
    375           node_metadata.node_id, node_metadata.identifier,
--> 376           node_metadata.metadata)
    377 
    378     for node_metadata in metric_list:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _load_layer(self, node_id, identifier, metadata)
    403     # Detect whether this object can be revived from the config. If not, then
    404     # revive from the SavedModel instead.
--> 405     obj, setter = self._revive_from_config(identifier, metadata, node_id)
    406     if obj is None:
    407       obj, setter = revive_custom_object(identifier, metadata)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _revive_from_config(self, identifier, metadata, node_id)
    421       obj = (
    422           self._revive_graph_network(metadata, node_id) or
--> 423           self._revive_layer_from_config(metadata, node_id))
    424 
    425     if obj is None:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in _revive_layer_from_config(self, metadata, node_id)
    481     try:
    482       obj = layers_module.deserialize(
--> 483           generic_utils.serialize_keras_class_and_config(class_name, config))
    484     except ValueError:
    485       if must_restore_from_config:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    175       module_objects=LOCAL.ALL_OBJECTS,
    176       custom_objects=custom_objects,
--> 177       printable_module_name='layer')

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    356             custom_objects=dict(
    357                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 358                 list(custom_objects.items())))
    359       with CustomObjectScope(custom_objects):
    360         return cls.from_config(cls_config)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/feature_column/base_feature_layer.py in from_config(cls, config, custom_objects)
    139     config_cp = config.copy()
    140     config_cp['feature_columns'] = serialization.deserialize_feature_columns(
--> 141         config['feature_columns'], custom_objects=custom_objects)
    142     config_cp['partitioner'] = generic_utils.deserialize_keras_object(
    143         config['partitioner'], custom_objects)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column/serialization.py in deserialize_feature_columns(configs, custom_objects)
    184   return [
    185       deserialize_feature_column(c, custom_objects, columns_by_name)
--> 186       for c in configs
    187   ]
    188 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column/serialization.py in <listcomp>(.0)
    184   return [
    185       deserialize_feature_column(c, custom_objects, columns_by_name)
--> 186       for c in configs
    187   ]
    188 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column/serialization.py in deserialize_feature_column(config, custom_objects, columns_by_name)
    136       cls_config,
    137       custom_objects=custom_objects,
--> 138       columns_by_name=columns_by_name)
    139 
    140   # If the name already exists, re-use the column from columns_by_name,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column/feature_column_v2.py in from_config(cls, config, custom_objects, columns_by_name)
   2620     kwargs = _standardize_and_copy_config(config)
   2621     kwargs['normalizer_fn'] = serialization._deserialize_keras_object(  # pylint: disable=protected-access
-> 2622         config['normalizer_fn'], custom_objects=custom_objects)
   2623     kwargs['dtype'] = dtypes.as_dtype(config['dtype'])
   2624 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/feature_column/serialization.py in _deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    271       obj = custom_objects.get(object_name)
    272     else:
--> 273       obj = module_objects.get(object_name)
    274       if obj is None:
    275         raise ValueError(

AttributeError: 'NoneType' object has no attribute 'get'

```

Any pointers how to tackle this?

**Comment by Saduf2019** [comment]
@robinvanschaik 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f35e030f2ddd8f1984623bf52e8c42c7/untitled.ipynb).

**Comment by robinvanschaik** [comment]
@Saduf2019 My apologies. The original missed an import from sklearn. 

I re-uploaded the colab as [here](https://colab.research.google.com/gist/robinvanschaik/701ab926088a2b96d81b2a2aa546164c/untitled418.ipynb). 

Please let me know if you run into issues regarding this colab.

**Comment by geo-papadopoulos** [comment]
I am running on the same issue when loading my saved model too.
Do we have any fix on that?

**Comment by bguisard** [comment]
@robinvanschaik you need to pass your custom objects to `.load_model(...)` otherwise it can't recreate your rescaling function. This [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects) provides more information about it.

I was able to get your code working by changing your last row to:
```
loaded_model = tf.keras.models.load_model('./saved_models/1', custom_objects={"scale_fn": scale_fn})
```

You can check that both models have the same weights with the following snippet I copied from TF's guide:
```python
import numpy as np

sample_input, _ = next(iter(dataset))
np.testing.assert_allclose(
    model.predict(sample_input), loaded_model.predict(sample_input)
)

for mw, lmw in zip(model.weights, loaded_model.weights):
    np.testing.assert_allclose(mw.numpy(), lmw.numpy())
```

**Comment by puneetsl** [comment]
Thanks @bguisard  for your comment, how can we handle custom scaling functions which need to maintain states. For example, min-max where we need to maintain min and max values from training data?

**Comment by puneetsl** [comment]
After some digging, I found that although you can register the custom function using `@tf.keras.utils.register_keras_serializable()` decorator and would work for classes that have the `get_config` module implemented, however, it will not work for user-defined functions. The reason is when you register a function it would be added to the `custom_object` dictionary as `Custom>{func_name}`. 
https://github.com/tensorflow/tensorflow/blob/b08c055e8405e87e833c25d2f4a1cadd04b95941/tensorflow/python/feature_column/serialization.py#L270 does not check for such condition and thus fail to load the appropriate object required to deserialize the model properly.

one simple solution can be to add this condition to the code 
```
elif f'Custom>{object_name}' in custom_objects:
      obj = custom_objects.get(f'Custom>{object_name}')
```

I tested this on my local machine, but it still would have the problem of not persisting the state for certain normalization functions

**Comment by fonnesbeck** [comment]
Did anyone come up with a solution for this? `normalizer_fn` is practically useless if it does not use the values from the training dataset to scale/normalize new inputs to the loaded model. Is this not documented anywhere? It seems like a pretty common issue.

**Comment by robinvanschaik** [comment]
@fonnesbeck I think that applying [layer-normalization](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LayerNormalization) on the input layer w.r.t. the appropriate axis might achieve a similar result, no? 

Unfortunately, it would mean that these parameters have to be learned during training, and I believe that this may extend training time.  

Other than that, I do not have any other solutions for the current predicament.

**Comment by fonnesbeck** [comment]
@robinvanschaik this is an Estimator (`DNNClassifier`), so I'm not manually building the layers, otherwise that's what I would have tried. I've resorted to manually serializing numpy arrays of normalization parameters.

**Comment by mokundong** [comment]
> @robinvanschaik you need to pass your custom objects to `.load_model(...)` otherwise it can't recreate your rescaling function. This [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects) provides more information about it.
> 
> I was able to get your code working by changing your last row to:
> 
> ```
> loaded_model = tf.keras.models.load_model('./saved_models/1', custom_objects={"scale_fn": scale_fn})
> ```
> 
> You can check that both models have the same weights with the following snippet I copied from TF's guide:
> 
> ```python
> import numpy as np
> 
> sample_input, _ = next(iter(dataset))
> np.testing.assert_allclose(
>     model.predict(sample_input), loaded_model.predict(sample_input)
> )
> 
> for mw, lmw in zip(model.weights, loaded_model.weights):
>     np.testing.assert_allclose(mw.numpy(), lmw.numpy())
> ```

how to load if use "normalizer_fn=lambda x: (x - 3.0) / 4.2)"

**Comment by jvishnuvardhan** [comment]
@robinvanschaik Is this still an issue for you? 
You are trying to load a Tensorflow model as a keas model. When you load the model as a TF model, everything works as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/badf69e20d2a6a4f3f01d805efc83738/untitled418.ipynb).

```
# loaded_model = tf.keras.models.load_model('./saved_models/1')
loaded_model = tf.saved_model.load('./saved_models/1')
```

**Comment by robinvanschaik** [comment]
> @robinvanschaik Is this still an issue for you? 
> You are trying to load a Tensorflow model as a keas model. When you load the model as a TF model, everything works as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/badf69e20d2a6a4f3f01d805efc83738/untitled418.ipynb).
> 
> ```
> # loaded_model = tf.keras.models.load_model('./saved_models/1')
> loaded_model = tf.saved_model.load('./saved_models/1')
> ```

Hi @jvishnuvardhan, 

Thanks for coming back to me. Unfortunately, I cannot verify whether this would have solved my issue. 

I have switched companies and do not tackle my use case with TFX.
