### ISSUE TITLE
micro_speech example: FeatureProvider tries to read audio data that is in the future

### ISSUE THREAD

**Issue by hollance** [tensorflow/tensorflow#46365]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): -
- TensorFlow installed from (source or binary): source / Arduino library
- Tensorflow version (commit SHA if source): -
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33

**Describe the problem**

The audio capture subsystem keeps track of the latest audio capture time. This is the `time_in_ms` passed into `PopulateFeatureData()` from micro_speech/feature_provider.cc. `PopulateFeatureData` will then work backwards from this timestamp to fetch audio data for any slices that it hasn't cached yet.

I believe the code should be as follows: https://github.com/hollance/tensorflow/commit/9fe6428a70ebb78fb471c5ddf8ff3d6fb7f8b14d

Reason: `current_step` is the index of the last slice that will be read. Since each slice is 30ms in length, we must subtract that from the timestamp, otherwise the last slice will go (partially) out of bounds and we will read stale data from the audio capture ring buffer.

For example, if the `time_in_ms` is 2010 (this the point in time *up to* which audio has been captured), the current code will set `current_step` to 2010 / 20 = 100. In the loop that computes new slices, this step value is multiplied again by 20 to create `slice_start_ms`, which becomes 2000. Then we read 30ms worth of audio starting from `slice_start_ms`. But we don't have 30ms worth of audio left in the capture buffer, only 10. The current implementation will try to read 20ms into the future, which is really old data from roughly 0.5 seconds ago.

Apparently making this change will cause `feature_provider_mock_test` to fail. I haven't looked into this in detail yet but I'm a little suspicious at the provided duration of 970ms. The correct duration for a 49x40 spectrogram is 990ms (or really anything between 990 and 1009ms, but those extra ms aren't used because they don't fill up a full window). I suspect the reason 970 was used here is that the sample is actually 1000ms and 30ms was (mistakenly) subtracted to work around the bug in feature_provider.cc.

**Comment by pjpratik** [comment]
Hi @hollance 

The PR [#74](https://github.com/tensorflow/tflite-micro-arduino-examples/pull/74) addresses the issue in [micro speech](https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main/examples/micro_speech) example of tflite-micro-arduino-examples with the following lines.

```
  const int last_step = (last_time_in_ms / kFeatureSliceStrideMs);
  // Number of new 20ms slices from which we can take 30ms samples
  int slices_needed =
      ((((time_in_ms - last_time_in_ms) - kFeatureSliceDurationMs) *
        kFeatureSliceStrideMs) /
           kFeatureSliceStrideMs +
       kFeatureSliceStrideMs) /
      kFeatureSliceStrideMs;

```
https://github.com/tensorflow/tflite-micro-arduino-examples/blob/76052fc778fb3638667d69886503733653550bfc/examples/micro_speech/feature_provider.cpp#L46-L53

Can you please confirm if this addresses the issue?

Thanks.
