### ISSUE TITLE
Exporting a TF Estimator with a `hub.text_embedding_column_v2` does not include the pretrained model

### ISSUE THREAD

**Issue by edend10** [tensorflow/tensorflow#46371]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): AI Platform runtime 2.3 or Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

This issue has been observed with the estimator API only, not Keras. I'm not entirely sure if it's a problem with estimator, export, or a tf hub issue.

**Describe the current behavior**

When exporting a TF Estimator which uses a `hub.text_embedding_column_v2` (the new version of tf-hub's `text_embedding_column_v2` that supports pretrained models in TF 2 SavedModel format), the export directory does not include the pretrained model asset files. Instead, the model seems to reference the local path the model was trained with.
When `text_embedding_column_v2` is fed with a url (i.e. `tfhub.dev/../my-model`), the model references the cached local path.

When the local path doesn't exist anymore, or when using the exported model in a different machine altogether, calling `tf.saved_model.load` fails with a `FileNotFound` exception:

When defining the embedding column with a local path to the pretrained model:
```
 ...
 hub.text_embedding_column_v2('/home/.../my-local-model')
 ...
 estimator = ...
 ...
 tf.estimator.export_saved_model(...)

...
 # on another machine or when removing /home/.../my-local-model:
...
tf.saved_model.load(...)

NotFoundError:  /content/local_nnlm50_2/assets/tokens.txt; No such file or directory
	 [[{{node dnn/input_from_feature_columns/input_layer/text_feature0_hub_module_embedding/StatefulPartitionedCall_1/StatefulPartitionedCall/text_file_init/InitializeTableFromTextFileV2}}]] [Op:__inference_pruned_10883]
```

When defining the embedding column with a cached pretrained model from a `tfhub.dev` url (not reproducible in Colab since tf hub cache doesn't kick in there):
```
 ...
 hub.text_embedding_column_v2('https://tfhub.dev/google/nnlm-en-dim50/2')
 ...
 estimator = ...
 ...
 tf.estimator.export_saved_model(...)

...
 # on another machine or when removing cache dir /tmp/tfhub_modules:
...
tf.saved_model.load(...)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError:  /tmp/tfhub_modules/74a841d6eb84e8d93d913d716fb5440d020cc291/assets/tokens.txt; No such file or directory
         [[{{node dnn/input_from_feature_columns/input_layer/topClickQuery_1st_hub_module_embedding/StatefulPartitionedCall_1/StatefulPartitionedCall/text_file_init/InitializeTableFromTextFileV2}}]] [Op:__inference_pruned_1658]
```

**Describe the expected behavior**

The expected behavior is for the export directory to include the pretrained model's assets, like it does when using `hub.text_embedding_column` (v1) with TF 1 format modules. And more importantly: loading the exported estimators should not fail even when loaded in a different machine, as well as not when the original local path to the pretrained model doesn't exist anymore.
The entire exported estimator should be contained within the export directory. 

**Standalone code to reproduce the issue**
Here's a Colab replicating the issue:
https://colab.research.google.com/drive/1Tr5M0m_EVRd5sFdgDX-EbVsk47UokPxD?usp=sharing

Overview of Colab:
- Download both versions of nnlm50 to local (TF 1 module, TF 2 SavedModel)
- Define two estimators: one with `text_embedding_column` (v1) and the local TF 1 format pretrained model, and the other with `text_embedding_column_v2` and the local TF 2 format pretrained model
- Train and export the estimators to SavedModels
- Print contents of export dir: **TF 1 format has the nnlm50 assets, TF 2 format does not**
- Try to load both estimators from disk: **success**
- Delete both local nnlm50 directories used for training the estimators
- Try to load the v1 estimator from disk again: **success**
- Try to load the v2 estimator from disk again: **fails**

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@edend10,
TensorFlow Hub issues are tracked in tensorflow/hub repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/hub/issues/new) and fill in the template, so that we can track the issue there. Thanks!

**Comment by edend10** [comment]
@amahendrakar 
Thanks for looking into this. I'll gladly post on tf/hub, but just noting I'm not 100% sure this is a tf hub issue and not an estimator issue (I trust your intuition though). I posted here because the issue manifests when using the estimator API, but not when using the Keras API.

**Comment by amahendrakar** [comment]
@edend10,
I was able to reproduce the error with TF v2.3 and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/9b3027743ad936469e62f289f327c949/46371-2-4.ipynb). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/82de81ae4a654f9928c7d3136ba69fa8/46371-tf-nightly.ipynb). 

I was able to run the code without any errors. Please checked the linked gist for reference. Thanks!

**Comment by edend10** [comment]
Looks good to me @amahendrakar !

Pretty sure [https://github.com/tensorflow/tensorflow/commit/6d8366afc435eb0f78d5abff457db26b68f0183d#diff-85d1ba3be0fd0e98ce033a07237e1f76c61058ce93e0f1e12e58a3c61b9291d5](this is the commit) that fixed it.

`saved_model/load.py` is being called by `hub.KerasLayer`. So it was a tensorflow issue after all :)

Thanks for looking into it! Closing
