### ISSUE TITLE
Problem with pypi package installation in linux debian(parrot os)

### ISSUE THREAD

**Issue by MusheAbdulHakim** [tensorflow/tensorflow#46377]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Parrot Os 4.10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pypi
- TensorFlow version:
- Python version:3.9.1
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
When i run the following commands either with pip3 or just pip basically, i run into an issue like :
`ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
`
I even read the article from this website
[https://tutorialforlinux.com/2020/10/02/step-by-step-tensorflow-parrot-linux-installation-guide/](tutorialforlinux)
I have run the various commands yet to no avail
**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow
pip install tensorflow-cpu
pip install tf-nightly
pip install tf-nightly-gpu

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@MusheAbdulHakim 

Which version of TF you are using?

TF 2.4 supports python from `3.6-3.8` . Please, refer the [document](https://www.tensorflow.org/install/source#cpu).

Tensorflow only supports the 64-bit version of Python

Can you downgrade to python 3.8 version and see if the issue still persists. Thanks!

**Comment by MusheAbdulHakim** [comment]
i have created a new virtual environment with python 3.8 and used `pip install tensorflow` and is installing now.Thanks

**Comment by ravikyram** [comment]
@MusheAbdulHakim 

Please, close this thread if your issue was resolved. Thanks!
