### ISSUE TITLE
Model Subclassing 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by kutayk33** [tensorflow/tensorflow#46379]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
class MyVGG(tf.keras.Model):
   I don't understand why is the problem please help!
 
    def __init__(self, num_classes):
        super(MyVGG, self).__init__()
        
        #self.input_l = tf.keras.layers.Conv2D(filters=64,kernel_size=3, activation='relu', input_shape=(150,150,3))
        #create blocks of Vgg 
        self.block_a = Block(filters=64 ,  kernel_size=3, repetitions= 2) 
        self.block_b = Block(filters=128 , kernel_size=3 , repetitions= 2) 
        self.block_c = Block(filters=256 , kernel_size=3, repetitions= 3) 
        self.block_d = Block(filters=512 , kernel_size=3 , repetitions= 3) 
        self.block_e = Block(filters=512 , kernel_size=3 , repetitions= 3) 
        
        # Define a Flatten layer
        self.flatten = tf.keras.layers.Flatten()
        # Define a Dense Layer 
        self.dense = tf.keras.layers.Dense(256, activation='relu')
        # Add  the softmax classifier using a Dense layer
        self.classifier = tf.keras.layers.Dense(num_classes, activation='softmax')
    
    def call(self, inputs):
    
        #x = self.input_l(inputs)
        #Chain all the layers 
        x = self.block_a(inputs) 
        x = self.block_b(x) 
        x = self.block_c(x) 
        x = self.block_d(x) 
        x = self.block_e(x) 
        x = self.flatten(x) 
        x = self.dense(x) 
        x = self.classifier(x) 
        return x
model_vgg = MyVGG(num_classes=2)

model_vgg.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model_vgg.fit_generator(train_generator, 
                                  epochs=10, 
                                  verbose=1, 
                                  validation_data = validation_generator)

**Describe the expected behavior**

**Standalone code to reproduce the issue**
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2616     if not self.built:
   2617       input_spec.assert_input_compatibility(
-> 2618           self.input_spec, inputs, self.name)
   2619       input_list = nest.flatten(inputs)
   2620       if input_list and self._dtype_policy.compute_dtype is None:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    164         spec.min_ndim is not None or
    165         spec.max_ndim is not None):
--> 166       if x.shape.ndims is None:
    167         raise ValueError('Input ' + str(input_index) + ' of layer ' +
    168                          layer_name + ' is incompatible with the layer: '

AttributeError: 'NoneType' object has no attribute 'shape'

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@kutayk33,
On running the given code snippet, I am facing an error stating `NameError: name 'Block' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d31f86b2fbc0612652c09f6a40963a66/46379.ipynb).

In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
