### ISSUE TITLE
Add support for converting mixed_float16 models to TF_lite

### ISSUE THREAD

**Issue by CaptainDario** [tensorflow/tensorflow#46380]
**System information**
- Windows 10
- tensorflow==2.4.0 installed via pip

**Project details:**
* [notebook](https://captaindario.github.io/DaKanjiRecognizer-ML/DaKanjiRecognizer.html)
* [github repository](https://github.com/CaptainDario/DaKanjiRecognizer-ML)

**Command used to run the converter or code if you’re using the Python API**

```
# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(tf_models_dir) # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**The output from the converter invocation**

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
E:\projects\DaKanjiRecognizer\.venv_dev\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    209     try:
--> 210       model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
    211                                                  toco_flags_str, input_data_str,

E:\projects\DaKanjiRecognizer\.venv_dev\lib\site-packages\tensorflow\lite\python\wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     31   """Wraps TocoConvert with lazy loader."""
---> 32   return _pywrap_toco_api.TocoConvert(
     33       model_flags_str,

Exception: <unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_1_input/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x64x64x1xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_2/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x31x31x32xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_3/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x14x14x32xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_4/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x6x6x64xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
<ipython-input-15-758d3ba4bcca> in <module>
      7 # Convert the model
      8 converter = tf.lite.TFLiteConverter.from_saved_model(tf_models_dir)
----> 9 tflite_model = converter.convert()
     10 
     11 # Save the model.

E:\projects\DaKanjiRecognizer\.venv_dev\lib\site-packages\tensorflow\lite\python\lite.py in convert(self)
    737     converter_kwargs.update(quant_mode.converter_flags())
    738 
--> 739     result = _convert_saved_model(**converter_kwargs)
    740     calibrate_and_quantize, flags = quant_mode.quantizer_flags()
    741     if calibrate_and_quantize:

E:\projects\DaKanjiRecognizer\.venv_dev\lib\site-packages\tensorflow\lite\python\convert.py in convert_saved_model(saved_model_dir, saved_model_version, saved_model_tags, saved_model_exported_names, **kwargs)
    630     model_flags.saved_model_exported_names.extend(saved_model_exported_names)
    631   toco_flags = build_toco_flags(**kwargs)
--> 632   data = toco_convert_protos(
    633       model_flags.SerializeToString(),
    634       toco_flags.SerializeToString(),

E:\projects\DaKanjiRecognizer\.venv_dev\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    214       return model_str
    215     except Exception as e:
--> 216       raise ConverterError(str(e))
    217 
    218   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_1_input/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x64x64x1xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_2/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x31x31x32xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_3/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x14x14x32xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("DaKanjiRecognizer/conv2D_4/Conv2D@__inference__wrapped_model_1048891" at "StatefulPartitionedCall@__inference_signature_wrapper_1049439") at "StatefulPartitionedCall")): 'tfl.conv_2d' op operand #0 must be tensor of 32-bit float or QI8 type or QUI8 type or QI16 type values, but got 'tensor<?x6x6x64xf16>'
<unknown>:0: note: loc("StatefulPartitionedCall"): called from



```

**Also, please include a link to the saved model or GraphDef**
There is no TF lite mixed precision model but [here is a model trained with default precision](https://github.com/CaptainDario/DaKanjiRecognizer/tree/main/data).

**Any other info / logs**

When I train the model using ```mixed_float16``` set with:
```
physical_devices = tf.config.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(physical_devices[0], True)

from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('float32')
#policy = mixed_precision.Policy('mixed_float16')      # <-- uncomment this
mixed_precision.set_policy(policy)
```
the converter crashes. As stated [here](https://www.tensorflow.org/lite/guide/ops_compatibility) (if I understand correctly) there is currently no support for this scenario. <br/>
If this is not planned to be implemented, are there any workarounds to still use float16 on supported GPUs. So one can still speed up training and is able to train larger models.

**Comment by abattery** [comment]
Sorry for encountering this. Currently, TFLite do not support mixed float16 models in TF yet.

**Comment by CaptainDario** [comment]
Is there a way to convert tha savedModel to float32 and than convert it to a tf_lite model?

**Comment by lgeiger** [comment]
We are running into this issue as well since we've switched from the graph rewrite to the Keras mixed precision API.

@reedwm What is the recommended way to convert a model with `dtype_policy="mixed_float16` back to `float32` in order to  support conversion to TFLite? I cannot seem to find any official docs on what the recommended workflow is for this case.

**Comment by lgeiger** [comment]
Checkout the following minimal example which results in a segfault:
```python
import tensorflow as tf

tf.keras.mixed_precision.set_global_policy("mixed_float16")

img = tf.keras.layers.Input(shape=(224, 224, 3))
x = tf.keras.layers.Conv2D(16, 3)(img)
x = tf.keras.layers.BatchNormalization(momentum=0.7)(x)
model = tf.keras.Model(img, x)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

**Comment by CaptainDario** [comment]
I never found a solution and I am still interested in it.

**Comment by lgeiger** [comment]
> I never found a solution and I am still interested in it.

So one workaround that seems to work for us is to clone the model and overwrite the `dtype`:
```python
model = tf.keras.models.clone_model(
    model,
    clone_function=lambda layer: layer.__class__.from_config(
        {**layer.get_config(), "dtype": "float32"}
    ),
)
```
However this doesn't play nicely with custom objects and seems like a quite brittle solution.

**Comment by CaptainDario** [comment]
Thank you!
I will give this a try because using float16 on RTX GPU's is such a big improvement for me.

However I really hope that somebody from the TF team will look at this again.

**Comment by reedwm** [comment]
> Is there a way to convert tha savedModel to float32 and than convert it to a TF_lite model?

@lgeiger solution works, but as he said, it is brittle (doesn't work with subclassed models, there is no guarantee a layer's config has a `dtype` attribute, etc). It will work in many cases though.

Alternatively, the model can be rebuilt as a float32 model. This will work in any case as long as the model can be rebuilt and supports float32. In either case, the weights of the mixed precision model must then be copied to the weights of the float32 model. For example

```python
import tensorflow as tf
import numpy as np

# Build a toy model
def get_model():
  img = tf.keras.layers.Input(shape=(224, 224, 3))
  x = tf.keras.layers.Conv2D(16, 3)(img)
  x = tf.keras.layers.BatchNormalization(momentum=0.7)(x)
  model = tf.keras.Model(img, x)
  return model

# Create a mixed_float16 model
tf.keras.mixed_precision.set_global_policy("mixed_float16")
model = get_model()

# Compile and train model
model.compile('sgd', 'mse')
x = np.random.normal(size=(64, 224, 224, 3))
y = np.random.normal(size=(64, 222,222, 16))
model.fit(x, y)

# Create a float32 model with the same weights as the mixed_float16 model, so
# that it loads into TF Lite
tf.keras.mixed_precision.set_global_policy("float32")
f32_model = get_model()
f32_model.set_weights(model.get_weights())

# Load model into TF lite
converter = tf.lite.TFLiteConverter.from_keras_model(f32_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

This strategy works for any case where a model is trained in mixed precision but a float32 model is needed for inference.

> And is it planned to support mixed_float16 for TF_lite models?

@abattery can you answer this? Not supporting mixed_float16 for TF lite is a significant usability issue. I think this should be done in TF lite (and any other inference backend), but an alternative would be to have a tool to convert a Keras model or SavedModel to float32.

> Checkout the following minimal example which results in a segfault:

This raises an exception for me (probably was fixed recently). Better than a segfault, but we should still support this use case.

**Comment by abattery** [comment]
@reedwm Thanks for reminding us of the feature request for mixed_float16 for TFLite. 

CCing @talumbau

**Comment by CaptainDario** [comment]
@reedwm thank you very much for the code snippet!!
Now I am able to train with float 16 precision but still save a tflite model.

**Comment by lgeiger** [comment]
@talumbau @abattery Has there been any progress on this issue?

Since the deprecation of the grappler mixed precision training workflow people using the new recommended mixed precision training with Keras are not able to convert models to TFLite anymore without additional code. This is very problematic if the workflow relies on storing saved models which are expected to be reloadable without any code but unfortunately cannot be easily converted to float32 to workaround this issue.

**Comment by CaptainDario** [comment]
@abattery After a training a model with mixed precision why is not possible to save it with `float16` quantization flags enabled?

```
# Convert the model
converter = tf.lite.TFLiteConverter.from_keras_model(eff)

# set quantization, additional ops
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
```

What is the difference between a float16 quantized model and with mixed_precision trained model?

**Comment by pjpratik** [comment]
The issue still persists with TF 2.11 and TF Nightly 2.12.0-dev20230106 as well. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/26d72e9871e6460e50491a045a937a11/46380.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi All, @CaptainDario, this should now work (with fallback) using [mixed-precision quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only_16-bit_activations_with_8-bit_weights_experimental): [gist](https://colab.sandbox.google.com/gist/pkgoogle/36a426d4120a87747105e650e6b5a562/46380.ipynb)

**Comment by CaptainDario** [comment]
@pkgoogle thanks for the info. I have currently no setup to test that.

**Comment by pkgoogle** [comment]
Hi @CaptainDario, the [gist](https://colab.sandbox.google.com/gist/pkgoogle/36a426d4120a87747105e650e6b5a562/46380.ipynb) should be self-contained, let me know if you don't believe it is a resolution to your issue.

**Comment by CaptainDario** [comment]
Yes the gist looks like what I wanted. Thanks !

**Comment by pkgoogle** [comment]
@CaptainDario, great! Can you close as completed if you have no more open items :). Thanks!

**Comment by Mary-prh** [comment]
I tried all the above-mentioned solutions, but none of them is working properly. 
The attempt to convert the precision to float32 by changing the policy and setting weights did not work, and the weight remained in the same policy. 
`tf.keras.mixed_precision.set_global_policy("float32")
f32_model = ghost_model
f32_model.set_weights(ghost_model.get_weights())
for layer in f32_model.layers:
    print(layer.name, layer.trainable, layer.dtype, layer.dtype_policy) `
but did not work.
```
batch_normalization_75 True float32 <Policy "mixed_float16">
activation_43 True float32 <Policy "mixed_float16">
depthwise_conv2d_39 True float32 <Policy "mixed_float16">
batch_normalization_76 True float32 <Policy "mixed_float16">
activation_44 True float32 <Policy "mixed_float16">
concatenate_30 True float32 <Policy "mixed_float16">
global_average_pooling2d_6 True float32 <Policy "mixed_float16">
```
