### ISSUE TITLE
Tensorflow Lite Build issue on RK3399 Ubuntu 18.04 aarch64

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/tensorflow#46386]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04 aarch64
- TensorFlow installed from (source or binary):  source
- Tensorflow version (commit SHA if source):  098231f
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):  RK3399 Ubuntu 18.04 aarch64

**Describe the problem**
I was going to build the tensorflow lite with CMake on RK3399 Ubuntu 18.04 aarch64 device.

OS: Ubuntu 18.04 aarch64
CMake: 3.18.0
gcc(g++): 10.1.0
GPU: Mali T860
OpenCL: 1.2

I cloned the TensorFlow and was going to build tflite supporting ARM GPU (OpenCL) with CMake.

_git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
mkdir tflite_build
cd tflite_build
cmake ../tensorflow/lite -DTFLITE_ENABLE_GPU=ON_

The configuration was successful.
I started to build the command "cmake --build . -j" but I met the following error.

![image](https://user-images.githubusercontent.com/47862419/104396628-00109f00-5586-11eb-9fcb-0f57eee17347.png)

Could u please let me know how to fix it?
Thanks

**Comment by terryheo** [comment]
Did you disabled TFLITE_ENABLE_XNNPACK? I've confirmed the error without enabling TFLITE_ENABLE_XNNPACK.
I'll submit a patch soon.

**Comment by rose-jinyang** [comment]
Yes, in fact, I made TFLITE_ENABLE_XNNPACK disabled.
If TFLITE_ENABLE_XNNPACK is enabled, the other error appears.

**Comment by terryheo** [comment]
It should be fixed by the PR. Please reopen if the issue persists.
