### ISSUE TITLE
TF2.4 ParameterServerStrategy tf.range in step_fn is slower than np.arange

### ISSUE THREAD

**Issue by wuxianxingkong** [tensorflow/tensorflow#46387]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**TF on yarn**(running machine system is CentOS 7)
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.4.0
- Python version:3.6
- CUDA/cuDNN version: no gpu
- GPU model and memory: no gpu
- CPU info: please see it below
- Training config: chief:  8cpus,25G memory; worker: 30 instances, 8 cpus per instance, 25G memory per instance;ps: 8 instances, 12 cpus per instance, 25G memory per instance

**Describe the current behavior**

I built a model using ParameterServerStrategy, and I used tf.range(steps_per_invocation) in step_fn to execute more steps. But I found there was a about 0.4 second between one loop end and next loop start, but when I changed to np.arnage(steps_per_invocation), the gap can be ignored.This is very similar to https://github.com/tensorflow/tensorflow/issues/40708.

```python
@tf.function
def train_fn(iterator):
    print("Flag_A_retrace!!!", time.time())
    tf.print("Flag_A", tf.timestamp())
    losses = 0.0
    for inner_index in tf.range(FLAGS.steps_per_invocation):
        tf.print("Flag_G", tf.timestamp(), inner_index)
        parsed_feature_dict, label_dict, weight_dict = next(iterator)
        tf.print("Flag_H", tf.timestamp(), inner_index)
        replica_fn = train_step(model, metrics, optimizer)
        tf.print("Flag_I", tf.timestamp(), inner_index)
        losses = strategy.run(replica_fn, args=(parsed_feature_dict, label_dict, weight_dict)) # we just need last loss
        tf.print("Flag_J", tf.timestamp(), inner_index)
    tf.print("Flag_B", tf.timestamp())
    return strategy.reduce(tf.distribute.ReduceOp.SUM, losses, axis=None)
```

The time between Flag_J and next Flag_G is 0.4 second

```python
@tf.function
def train_fn(iterator):
    print("Flag_A_retrace!!!", time.time())
    tf.print("Flag_A", tf.timestamp())
    losses = 0.0
    for inner_index in np.arange(FLAGS.steps_per_invocation):
        tf.print("Flag_G", tf.timestamp(), inner_index)
        parsed_feature_dict, label_dict, weight_dict = next(iterator)
        tf.print("Flag_H", tf.timestamp(), inner_index)
        replica_fn = train_step(model, metrics, optimizer)
        tf.print("Flag_I", tf.timestamp(), inner_index)
        losses = strategy.run(replica_fn, args=(parsed_feature_dict, label_dict, weight_dict)) # we just need last loss
        tf.print("Flag_J", tf.timestamp(), inner_index)
    tf.print("Flag_B", tf.timestamp())
    return strategy.reduce(tf.distribute.ReduceOp.SUM, losses, axis=None)
```
The time between Flag_J and next Flag_G can be ignored.

**Describe the expected behavior**
1.  tf.range performance should be the same as np.arange
2. 0.4 second in just one step is very slow because it accouts for abount 94% of one step execute time.

**Comment by ravikyram** [comment]
@wuxianxingkong 

Looks like code is incomplete.

Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
