### ISSUE TITLE
tensorflow 2.4.0  the predict function outputs an error, when the same code works on another TF versions. 

### ISSUE THREAD

**Issue by rpsantosa** [tensorflow/tensorflow#46384]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform : Windows 10
- TensorFlow installed from ): 2.4.0, using instal_tensorflow(version = "2.4.0" )
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 / 8.0.2
- GPU model and memory: RTX 3070

**Describe the current behavior**
I can run this code https://blogs.rstudio.com/ai/posts/2019-08-23-unet/ on the kaggles notebook (which runs TF 2.3.0),
but on my PC, intel + nvidia 3070, TF 2.4, the code can run and train.  BUT the PREDICT function doesnt work. 
The exact same code the predict function works as expected on Kaggles

**Describe the expected behavior**
The predicitions functions results in predictions, not errors

**Standalone code to reproduce the issue**
https://www.kaggle.com/rpsantosakaggle/unet-carvana

**Other info / logs** 
 predictions <- predict(model, batch)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: in user code:

    C:\Users\rpsan\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\keras\engine\training.py:1478 predict_function  *
        return step_function(self, iterator)
    C:\Users\rpsan\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\keras\engine\training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\rpsan\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\rpsan\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\rpsan\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_re

*have run many other codes that worked seamlesly, but with this one, it bugs. 
 tf_config()
TensorFlow v2.4.0 ()
Python v3.6 (C:/Users/rpsan/AppData/Local/r-miniconda/envs/r-reticulate/python.exe)

**Comment by ymodak** [comment]
Please provide a minimum code snippet to reproduce the reported issue this helps us reduce time on trouble shooting significantly. On a side note: From the stack trace you may want to refer this [thread](https://github.com/rstudio/keras/issues/1063).

**Comment by rpsantosa** [comment]
I just manage to solve the issue.  Something changed in the behavior of prediction function from TF 2.3.0 to TF 2.4.0. 
What worked:
 Instead of predict(model, batch) ( what works fine on TF 2.3.0)
I wrote : predict(model, batch[[1]])  ( this owrks on TF 2.4.0) ( like, selecting only the train data, what makes sense)
Thankyou for the support and replay
