### ISSUE TITLE
YOLOv4 not completely quantized -> Edge TPU compilation fails

### ISSUE THREAD

**Issue by arsenal-2004** [tensorflow/tensorflow#46395]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	i = 1
	for image in range(100):
		image = np.random.random((1, 416, 416, 3)).astype('float32')
		print(i, image.shape)
		i += 1
		yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model('/content/drive/MyDrive/YOLO/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter._experimental_new_quantizer = True
converter.allow_custom_ops = True
converter.representative_dataset = representative_dataset_gen
tflite_quant_model = converter.convert()
with open('/content/drive/MyDrive/YOLO/saved_model/yolov4_full_integer_quant.tflite', 'wb') as w:
	w.write(tflite_quant_model)
print("Full Integer Quantization complete! - yolov4_full_integer_quant.tflite")
```

**The output from the converter invocation**

```
There is no issue here
```

**Also, please include a link to the saved model or GraphDef**

The link contains the Saved_Model and the quantized TFLite model.
https://drive.google.com/drive/folders/1m4KOjdWHmtBpHPau8Oxu7bC5efkdCRy_?usp=sharing

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Despite using the target spec BUILTINS_INT8, the model is not quantized completely (exp and log operations)
- This then causes an issue when using the EdgeTPU compiler, with an error
```
Edge TPU Compiler version 15.0.340273435
Invalid model: /content/drive/MyDrive/Clutterbot/YOLO/saved_model/yolov4_full_integer_quant.tflite
Model not quantized
```

@abattery @jingpu Can you please help me out here? I thought Exp and Log operations were common enough to have been quantized, or am I missing something here?

**Comment by arsenal-2004** [comment]
@liufengdb Can you please take a look at this issue?

**Comment by amahendrakar** [comment]
Running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/889d9720c511ac07a2358d56b759a7ee/46395-2-3.ipynb) throws an error stating `RuntimeError: Failed to quantize: <unknown>:0: error: loc("functional_1/lambda/Exp;StatefulPartitionedCall/functional_1/lambda/Exp"): 'tfl.exp' op requires the same type for all operands and results`.

Was able to reproduce the `Model not quantized` issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/c54d3783ad033b67f99d6a551cc96200/46395.ipynb#scrollTo=wcinmBwAiglX).  

Running the code with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3a06e155a169b62379ce80860f015ca4/46395.ipynb), throws an error stating `RuntimeError: Quantization not yet supported for op: 'EXP'. Quantization not yet supported for op: 'LOG'.`

Please check the linked gist for reference. Thanks!

**Comment by arsenal-2004** [comment]
@amahendrakar Do you need any more information from me?

**Comment by abattery** [comment]
@jingpu @liufengdb @daverim could you take a look at this?

**Comment by arsenal-2004** [comment]
Any updates on this?

**Comment by teijeong** [comment]
Hi @arsenal-2004 ,

[Log](https://github.com/tensorflow/tensorflow/blob/ffe67626083d356629326fec99ad032c51a7d904/tensorflow/lite/kernels/elementwise.cc#L53) and [Exp](https://github.com/tensorflow/tensorflow/blob/ffe67626083d356629326fec99ad032c51a7d904/tensorflow/lite/kernels/exp.cc#L65) are not currently supported for quantized inference, so you'd want to restructure the model or find alternatives without log/exp.

Will close this as the referenced one is also closed.

**Comment by abattery** [comment]
@arsenal-2004 If you still want `Log` and `Exp` quantized operators in TFLite, you can file a separate issue for the feature request.
