### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list).

### ISSUE THREAD

**Issue by neenaloysius** [tensorflow/tensorflow#46394]
Im getting this valueError in colab gpu env with keras tensorflow ver 2.
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list). on running the following code :

def ctc_lambda_func(args):
    y_pred, labels, input_length, label_length = args
    # the 2 is critical here since the first couple outputs of the RNN
    # tend to be garbage:
    # print "y_pred_shape: ", y_pred.shape
    y_pred = y_pred[:, 2:, :]
    # print "y_pred_shape: ", y_pred.shape
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)

# ---- CTC ----
    
labels = Input(name='the_labels', shape=[None], dtype=dtype)       # transcription data (batch_size * y_seq_size)
input_length = Input(name='input_length', shape=X_train_length.shape, dtype=dtype)  # unpadded len of all x_sequences in batch
label_length = Input(name='label_length', shape=label_length.shape, dtype=dtype)  # unpadded len of all y_sequences in batch

# Lambda layer with ctc_loss function due to Keras not supporting CTC layers
loss_out = Lambda(function=ctc_lambda_func, name='ctc', output_shape=(1,))([y_pred, np.float32, Y_train, np.float32, X_train_length, np.float32, label_length, np.float32])
network_model = Model(inputs=[input_data, labels, input_length, label_length], outputs=y_pred)

**Comment by amahendrakar** [comment]
@neenaloysius,
On running the given code snippet with TF v2.4, I am facing an error stating `NameError: name 'dtype' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/404e7bf1a78ec3e83af5735df794a840/46394.ipynb).

In order to reproduce the issue reported here, could you please provide the exact TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by neenaloysius** [comment]
PFA the colab file. The dataset folder I have shared with you. Please let me  know if you need more details
Thanks,
Neena Aloysius
Research Scholar
Dept. of CSE,
Amrita School of Engineering
Ph: +91-9061414992.
 

    On Wednesday, January 13, 2021, 09:30:59 PM GMT+5:30, Abhilash Mahendrakar <notifications@github.com> wrote:  
 
 


@neenaloysius,
On running the given code snippet with TF v2.4, I am facing an error stating NameError: name 'dtype' is not defined. Please find the gist of it here.

In order to reproduce the issue reported here, could you please provide the exact TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by neenaloysius** [comment]
Could you please update the progress. Also, please confirm if you were able to access the dataset folder.
Thanks,
Neena Aloysius
Research Scholar
Dept. of CSE,
Amrita School of Engineering
Ph: +91-9061414992.
 

    On Friday, January 15, 2021, 02:52:39 PM GMT+5:30, Neena Aloysius <neenaloysius@ymail.com> wrote:  
 
 PFA the colab file. The dataset folder I have shared with you. Please let me  know if you need more details
Thanks,
Neena Aloysius
Research Scholar
Dept. of CSE,
Amrita School of Engineering
Ph: +91-9061414992.
 

    On Wednesday, January 13, 2021, 09:30:59 PM GMT+5:30, Abhilash Mahendrakar <notifications@github.com> wrote:  
 
 


@neenaloysius,
On running the given code snippet with TF v2.4, I am facing an error stating NameError: name 'dtype' is not defined. Please find the gist of it here.

In order to reproduce the issue reported here, could you please provide the exact TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
> PFA the colab file. The dataset folder I have shared with you. Please let me  know if you need more details

@neenaloysius,
I do not see a Colab notebook or a dataset attached. Could you please share the links of it here? Thanks!

**Comment by neenaloysius** [comment]
The colab file in zipped format:
[CSLR (1).zip](https://github.com/tensorflow/tensorflow/files/5846749/CSLR.1.zip)
This is the link for dataset:
https://drive.google.com/drive/folders/1kus7GxIYTkHFb1HJBLd_ALQGIGlQUSw5?usp=sharing

**Comment by amahendrakar** [comment]
@neenaloysius,
I did not face the `ValueError: Failed to convert a NumPy array to a Tensor` on running the code with the TensorFlow v2.4.

However, I am facing a different error stating `ValueError: Can not squeeze dim[1], expected a dimension of 1, got 3 for '{{node ctc/Squeeze}} = Squeeze[T=DT_FLOAT, squeeze_dims=[-1]](Placeholder_1)' with input shapes: [?,3].`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/58f50b495e0e9eb67097c72fdd662d82/46394.ipynb). Thanks!

**Comment by neenaloysius** [comment]
Yeah, I slightly changed the code and this is the issue im facing now. Not sure which variable is causing the issue.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
