### ISSUE TITLE
tf.math.tanh makes silently crash Python

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#46408]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 Bits build 21286
- TensorFlow installed from (source or binary): binary from pip
- TensorFlow version (use command below): 2.5.0-dev20210113
- Python version: Python 3.8.5 with Miniconda 4.9.2
- CUDA/cuDNN version: CUDA 11.0 / CuDNN 8.0.6
- GPU model and memory: GeForce RTX 2080 Super with Max-Q Design with 8Go

**Describe the current behavior**
The Python interpreter crashes silently without any error when using the `tf.math.tanh()` function.

**Describe the expected behavior**
Works without crashing

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.constant([-float("inf"), -5, -0.5, 1, 1.2, 2, 3, float("inf")])
tf.math.tanh(x)
```
**Other info / logs** 
When running `python -u -m trace -t crash.py` the last lines are:
```
 --- modulename: gen_math_ops, funcname: tanh
gen_math_ops.py(10769):   _ctx = _context._context or _context.context()
gen_math_ops.py(10770):   tld = _ctx._thread_local_data
gen_math_ops.py(10771):   if tld.is_eager:
gen_math_ops.py(10772):     try:
gen_math_ops.py(10773):       _result = pywrap_tfe.TFE_Py_FastPathExecute(
gen_math_ops.py(10774):         _ctx, "Tanh", name, x)
gen_math_ops.py(10773):       _result = pywrap_tfe.TFE_Py_FastPathExecute(
```
You can also find in attachment a screenshot of the crash.
![crash](https://user-images.githubusercontent.com/959590/104497672-011feb80-55db-11eb-8b6b-a65b8f6aeb69.png)

**Comment by ravikyram** [comment]
@jplu 

I have tried in colab with TF nightly -GPU version(`2.5.0-dev20210113`) and I am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/90c043459bf2e5f16ea087772ab8114d/untitled618.ipynb).Colab uses cuda 10.1. 

Can you check with latest stable version 2.4 and see if the issue still persists.Thanks!

**Comment by jplu** [comment]
I'm on Windows, Colab in on Linux. Unfortunately, there is no point for me to test on a colab.

Anyway, TF 2.4 works on Windows but I want to use the nightly builds because it contains an important fix that the 2.4 doesn't have.

**Comment by RhynoTime** [comment]
I have a similar issue - fairly basic DCGAN from the Tensorflow Tutorial (https://www.tensorflow.org/tutorials/generative/dcgan) which worked just fine in TF 2.4 is crashing now in 2.5 (I need to use 2.5 to enable other models to function properly with all the version issues between Ampere and CUDA/CUDNN/TF)

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Mostly No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 Bit, Version 20H2 / 19042.746
TensorFlow installed from (source or binary): binary from pip
TensorFlow version (use command below): 2.5.0-dev20210122
Python version: Python 3.8.5 using Anaconda
CUDA/cuDNN version: CUDA 11.1.1_456.81_win10 / CuDNN 8.0.5.39
GPU model and memory: GeForce RTX 3080 

It's the same model as the DCGAN in the tutorial, just with a few tweaks to the kernels and image sizes for my dataset... worked just fine in TF 2.4. 

This line in the generator causes a Kernel Error (no error codes given / big red screen in the Spyder Ipython console)

_model.add(layers.Conv2DTranspose(3, (3, 3), strides=(2, 2), padding='same', use_bias=False, activation='**tanh**'))_

but if I change it to 

model.add(layers.Conv2DTranspose(3, (3, 3), strides=(2, 2), padding='same', use_bias=False, activation='**relu**'))

it seems to run ... although training results are quite bad, so I can't tell if its just the activation or other issues are happening at the same time but not driving errors.

**Comment by RhynoTime** [comment]
I should mention I get the exact same result when using the OP's code 

![image](https://user-images.githubusercontent.com/39113957/105802454-6fa86600-5f58-11eb-90b5-7f06622ab0a6.png)

**Comment by JakubBialy** [comment]
I confirm identical behavior as @RhynoTime described.
I checked various tf-nightly versions (installed via `pip`) against `tanh` crashes, results below.

```
tf-nightly==2.5.0.dev20201212 - OK
tf-nightly==2.5.0.dev20201213 - OK
tf-nightly==2.5.0.dev20201214 - OK
tf-nightly==2.5.0.dev20201215 - ERR
tf-nightly==2.5.0.dev20201216 - ERR

tf-nightly==2.5.0.dev20201225 - ERR

tf-nightly==2.5.0.dev20210101 - ERR
```

**Comment by catrinaisahuman** [comment]
this issue still persists on latest version
`2.5.0.dev20210210`

**Comment by sherhut** [comment]
Thank you for reporting this. I have verified that this is fixed in a recent build from source. The next nightly build should also contain the fix.
