### ISSUE TITLE
DataFrameIterator is not exported

### ISSUE THREAD

**Issue by svpino** [tensorflow/tensorflow#46401]
https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/preprocessing/image.py#L464

The `DataFrameIterator` class is not exported, so it can't be extended from outside the framework.

**Comment by sachinprasadhs** [comment]
It is used in [ImageDataGenerator's](https://github.com/keras-team/keras/blob/v2.7.0/keras/preprocessing/image.py#L597-L1137) [flow_from_directory](https://github.com/keras-team/keras/blob/v2.7.0/keras/preprocessing/image.py#L898) where it [returns](https://github.com/keras-team/keras/blob/v2.7.0/keras/preprocessing/image.py#L976) `DirectoryIterator`. 
It is not directly exposed with export but internally being used as mentioned above.

**Comment by svpino** [comment]
If the class was exported, we could extend it to change its default behavior. For example, `DirectoryIterator`, `NumpyArrayIterator`, `ImageDataGenerator`, etc. are all exported.

Can we also export `DataFrameIterator`?

**Comment by rthadur** [comment]
Please check latest comments here https://github.com/keras-team/keras/pull/16008#issuecomment-1030343173 , this has been deprecated and meant for internal use only. Thank you
