### ISSUE TITLE
Installation of OpenCL backend Tensorflow Lite runtime package

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/tensorflow#46400]
**System information**
- OS Platform and Distribution: Ubuntu 18.04 aarch64
- Mobile device:  RK3399 with Mali T860 GPU
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?:  virtualenv
- GCC/Compiler version (if compiling from source): gcc 7.5
- CUDA/cuDNN version: None
- GPU model and memory: Mali T860

**Describe the problem**

I am going to install OpenCL backend TensorFlow Lite runtime for Python on RK3399 Ubuntu 18.04 aarch64 platform.
I looked at the document and blogs but could NOT find any method to install OpenCL backend TensorFlow Lite runtime for Python.
I think that OpenCL backend TensorflowLite for Python should be installed from the source.
If so, how should it be built and installed?
Could u provide a proper method asap?
Thanks

**Comment by terryheo** [comment]
Dup of https://github.com/tensorflow/tensorflow/issues/46498
