### ISSUE TITLE
Support for directly importing Dense layer from keras API

### ISSUE THREAD

**Issue by zyberg2091** [tensorflow/tensorflow#46407]
**System information**
- TensorFlow version (you are using): TF 4.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Why Dense?

While i was writing code i noticed Dense layer is not supported in importing directly in keras but input layer is there. In that case anyhow we have to mention full path dependency because this layer is the most basic layer and frequently used while building the architecture even if not initially used then at least last few layers are dense layers only mostly. It can be used as feed forward neural network as well as in the output layer.so I think it will be good if this layer can be directly imported from keras without any path dependencies,

[ `from tensorflow.python.keras.engine.input_layer import Input`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/__init__.py) 

Just adding Dense here like this will do

**Will this change the current api? How?**

Nothing is going to change in api. This will be just an additional functionality for the users to serve their purpose easily.

**Comment by anilkumarKanasani** [comment]
@zyberg2091 , Can we work on this issue ?
Is it assigned to any one ?

**Comment by jvishnuvardhan** [comment]
@zyberg2091 Just want to understand your use case. 
Currently we import `Input` and `Dense` layers as follows

```
from tensorflow.keras import Input
from tensorflow.keras.layers import Dense
```
Considering a simple example model, 
```
  model = tf.keras.models.Sequential([
    Dense(512, activation='relu', input_shape=(784,)),
    Dense(10)
  ]) 
```
In the above model, we are using `Dense` layer as simply `Dense`.

If I understand correctly, you want to import Dense directly as 

`from tensorflow.keras import Dense`

Currently `Dense` layer is part of `layers` API. Whether `Dense` is part of `Layers` or part of `keras` (similar to `Input` layer), the model building part of the code is same. 

I want to understand what do we accomplish from this requested feature (by moving `Dense` layer ). Is there anything missing from the current implementation that cannot work with your use-case? If we simply move out `Dense`, it may confuse the large community of existing users. Please let us know your use case with little more details. Thanks!

**Comment by zyberg2091** [comment]
@jvishnuvardhan considering your simple sequential API model.
i can just import those layers in just one 1 line from keras engine.These is preventing me from just writing extra useless line.well all of us are aware that these two layers have to be imported in most use cases because these two layers are basic layers.for my project i just needed these two layers and if i have to use another layer other than input than i have to write like this-

`from tensorflow.keras.layers import Input,Dense`

Then i don't understand this approach-

`from tensorflow.keras import Input`
`from tensorflow.keras.layers Import Dense`

Users may have different use cases according to their needs and so importing layers become specific.Therefore i understand other layers might be imported from keras layers API but if we are able to import Input layer directly why can't we do this to dense layer which is equally basic as Input layer.

This also creates confusion and i am unable to think where can we use this 'From tensorflow.keras import Input' alone

Most simple use case can be -

`from tensorflow.keras import Input,Dense` for importing layers from keras engine

**Comment by tomerk** [comment]
To clarify, you want us to export tf.keras.layers.Dense with an alias tf.keras.Dense?

**Comment by zyberg2091** [comment]
yes @tomerk

**Comment by tomerk** [comment]
Notes from our internal discussion about this.
We don't want to blur layer/non-layer api boundaries in Keras like this.

`keras.Input` is not a layer, it is a symbolic input object that can be passed to layers.
`keras.layers.InputLayer` is the corresponding input layer, which is *not* aliased under `keras` directly.

(`from tensorflow.python.keras.engine.input_layer import Input` might refer to the internal file location of `keras.Input`, but it's not a layer itself and as such we don't expose it under `keras.layers`.)
