### ISSUE TITLE
LSTM crashing during training - Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure

### ISSUE THREAD

**Issue by Kalhama** [tensorflow/tensorflow#46405]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Win 10 Enterprice LTSC
- TensorFlow installed from: binary
- TensorFlow version: v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: Python 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Build cuda_11.0_bu.relgpu_drvr445TC445_37.28845127_0 / cuDNN v 8.0.5 for CUDA 11.0
- GPU model and memory: GTX 960 (Asus Strix Direct DCU2 OC 4GB)

**Describe the current behavior**
When training a network with LSTM layers it crashes randomly during epochs. 

**Standalone code to reproduce the issue**
https://github.com/Kalhama/tensorflow-lstm-crash

**Things I've checked and are ok / have no effect**
✅ Only occurs when training on GPU
✅ Only occurs when using LSTM layers
✅ Underclocking GPU, raising voltages etc.. (in case stock overclock would be unstable)
✅ CPU and GPU temps (either never exceeds 60 deg C)
✅ Different driver versions. I earlier had 460.89 but it's the same on 451.82
✅ There is enough VRAM / RAM. (I used `tf.config.experimental.set_memory_growth()` and then Win task manager to check VRAM utilization. Only used max 1GB of VRAM on large networks)

**Things I've checked and have some effect, but do not remove problem completely**
✅ Different network sizes. All networks seem to have this issue but larger networks feel to be more prone to crash fast
✅ Different batch sizes and different train data sizes. Overall larger batches and longer epochs are more stable. 

**Other info / logs**
```2021-01-12 21:38:15.476512: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2021-01-12 21:38:15.476581: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1859): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
2021-01-12 21:38:15.483573: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:220] Unexpected Event status: 1

2
```

Sometimes the error looks like this:
```
2021-01-12 21:41:41.096689: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_INTERNAL_ERROR
in tensorflow/stream_executor/cuda/cuda_dnn.cc(1972): 'cudnnRNNBackwardData( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, output_desc.handles(), output_data.opaque(), output_desc.handles(), output_backprop_data.opaque(), output_h_desc.handle(), output_h_backprop_data.opaque(), output_c_desc.handle(), output_c_backprop_data.opaque(), rnn_desc.params_handle(), params.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), input_desc.handles(), input_backprop_data->opaque(), input_h_desc.handle(), input_h_backprop_data->opaque(), input_c_desc.handle(), input_c_backprop_data->opaque(), workspace.opaque(), workspace.size(), reserve_space_data->opaque(), reserve_space_data->size())'
2021-01-12 21:41:41.127515: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1926 : Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 3, 200, 1, 200, 32, 200]
Traceback (most recent call last):
  File "c:/Users/User/Code/tensorflow/main.py", line 61, in <module>
    main()
  File "c:/Users/User/Code/tensorflow/main.py", line 40, in main
    model.train(
  File "c:\Users\User\Code\tensorflow\core\model.py", line 47, in train
    self.model.fit(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError:    Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 3, 200, 1, 200, 32, 200]
         [[{{node gradients/CudnnRNN_grad/CudnnRNNBackprop}}]]
         [[Adam/gradients/PartitionedCall_2]] [Op:__inference_train_function_7900]

Function call stack:
train_function -> train_function -> train_function
```

**Comment by Kalhama** [comment]
Updates:

1. I updated python to 3.8.7, no effect
2. I tried using tf-nightly (2.5.0-dev20210113) but still got same error
3. I was able to replicate the issue on another computer:

- OS Platform and Distribution: Win 10 Enterprice LTSC
- TensorFlow installed from: binary
- TensorFlow version: 
- Python version: Python 3.8.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 11.0  / cuDNN v8.0.4 (September 28th, 2020), for CUDA 11.0
- GPU model and memory: GTX 1060 6GB

**Comment by amahendrakar** [comment]
@Kalhama,
As per this comment from issue [#45987](https://github.com/tensorflow/tensorflow/issues/45987#issuecomment-751934074) with a similar error log, updating the NVIDIA drivers seems to work. Could you please take a look at it and let us know if it helps. Thanks!

**Comment by Kalhama** [comment]
Hello!

I updated the driver as you suggested and this hasnt occured since. Today I also ran the example repo I provided for quite good time +30min without errors.

**Comment by Kalhama** [comment]
Can be closed

**Comment by amahendrakar** [comment]
@Kalhama,
Thank you for the update. Closing the issue as it is resolved. Please feel free to re-open if necessary.
