### ISSUE TITLE
bazel build succeeds, but bazel-mobile install fails

### ISSUE THREAD

**Issue by kavasseri** [tensorflow/tensorflow#4641]
The build succeeds on OS 10.11.6, with bazel version 0.3.1-homebrew. However, the bazel mobile-install fails. This is not a TensorFlow capitalization problem or a camera permissions issue! 
Thanks || 

bazel mobile-install //tensorflow/examples/android:tensorflow_demo --verbose_failures
The main error is listed below:
---------------------
ERROR: /private/var/tmp/_bazel_kg/16cb3f28d531847b42ceb660896dbffa/external/bazel_tools/tools/android/BUILD:132:1: Converting to Python 3: external/bazel_tools/tools/android/incremental_install.py failed: 2to3 failed: error executing command 
  (cd /private/var/tmp/_bazel_kg/16cb3f28d531847b42ceb660896dbffa/execroot/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/host/genfiles/python3/external/bazel_tools/tools/android --write-unchanged-files external/bazel_tools/tools/android/incremental_install.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 0.396s, Critical Path: 0.15s
--------------------------------------

WARNING: Bazel Android NDK crosstools are based on Android NDK revision 11. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '12.1.2977051'.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/debug:debug_graph_utils.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/debug:debug_graph_utils.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:avgpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:bounds_check.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_activations.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_attention.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_cuboid_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_cuboid_convolution.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_patch_3d.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_pooling.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_softmax.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:maxpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_entry.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_scorer.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_search.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_decoder.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_loss_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/core/BUILD:667:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /Users/kg/tensorflow/tensorflow/examples/android/BUILD:56:12: in srcs attribute of android_binary rule //tensorflow/examples/android:tensorflow_demo: please do not import '//tensorflow/contrib/android:java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java' directly. You should either move the file to this package or depend on an appropriate rule there.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_kg/16cb3f28d531847b42ceb660896dbffa/external/bazel_tools/tools/android/BUILD:132:1: Converting to Python 3: external/bazel_tools/tools/android/incremental_install.py failed: 2to3 failed: error executing command 
  (cd /private/var/tmp/_bazel_kg/16cb3f28d531847b42ceb660896dbffa/execroot/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/host/genfiles/python3/external/bazel_tools/tools/android --write-unchanged-files external/bazel_tools/tools/android/incremental_install.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:tensorflow_demo failed to build
INFO: Elapsed time: 0.396s, Critical Path: 0.15s

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by andrewharp** [comment]
My guess is that incremental_install.py is a python2 script, but you are using python3, and the automatic conversion is failing. Does it work if you use python2 instead?

If you run:
`bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/host/genfiles/python3/external/bazel_tools/tools/android --write-unchanged-files external/bazel_tools/tools/android/incremental_install.py`
does it tell you anything else about the failure?

If you just want to go ahead and install/run the demo, here's the typical command sequence:
```
bazel build -c opt //tensorflow/examples/android:tensorflow_demo
adb install -r bazel-bin/tensorflow/examples/android/tensorflow_demo.apk
```

You can even auto-start the activity with:
`adb shell am start -n org.tensorflow.demo/.CameraActivity`

**Comment by kavasseri** [comment]
Andre - thanks much for the kind note. Running the command you suggested

"bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/host/genfiles/python3/external/bazel_tools/tools/android --write-unchanged-files external/bazel_tools/tools/android/incremental_install.py" 
does not return anything.

I also forgot to add that  the "adb install.."  goes through without errors - however, that is when the App crashes on start.

Probably python3 is the culprit - I will check it out and let you know.

**Comment by andrewharp** [comment]
What is the runtime error you're seeing? Have you added the model and label files to tensorflow/examples/android/assets/?

**Comment by kavasseri** [comment]
Yes, Andrew. I have the model and label (*.txt) files in the assets directory. I am starting over again and will let you know the outcome. Thanks so much! ||

**Comment by kavasseri** [comment]
Andrew, I started over and the adb install works fine now. Perhaps I was missing the labels (*.txt) file. I am sorry for the inconvenience and will close the issue. Also, thank you so much for your help in resolving this. ||
