### ISSUE TITLE
TF2.4/XLA assertion in Electra model when deferring compilation on GPU

### ISSUE THREAD

**Issue by bas-aarts** [tensorflow/tensorflow#46419]
Attached are gzip versions of
1) git.patch
2) dummy_p1.tfrecord
3) run_electra_bug.sh

Environment:
1) Google TF-2.4 container: tensorflow/tensorflow:2.4.0-gpu
2) single GV100 32GB

Reproduction steps:

1) git clone git@github.com:NVIDIA/DeepLearningExamples.git
2) cd DeepLearningExamples/TensorFlow2/LanguageModeling/ELECTRA/
3) copy the attached git.patch file to ./
4) cp the attached run_electra_bug file to ./scripts
5) cp the attached dummy_p1.tfrecord file to ./data
6) git apply git.patch
7) bash scripts/docker/build.sh
8) bash scripts/docker/launch.sh
9) TF_XLA_FLAGS=--tf_xla_always_defer_compilation=true bash scripts/run_electra_bug.sh 1 6e-3 amp 1  (run this within the docker container started in 8).

The resulting error:
```
0]<stderr>:Traceback (most recent call last):
[0]<stderr>:  File "/workspace/electra/run_pretraining.py", line 493, in <module>
[0]<stderr>:    args = main(start_time)
[0]<stderr>:  File "/workspace/electra/run_pretraining.py", line 427, in main
[0]<stderr>:    local_step==1, take_step=local_step % args.gradient_accumulation_steps == 0)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
[0]<stderr>:    result = self._call(*args, **kwds)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 888, in _call
[0]<stderr>:    return self._stateless_fn(*args, **kwds)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2943, in __call__
[0]<stderr>:    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
[0]<stderr>:    ctx, args, cancellation_manager=cancellation_manager))
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 560, in call
[0]<stderr>:    ctx=ctx)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
[0]<stderr>:    inputs, attrs, num_outputs)
[0]<stderr>:tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
[0]<stderr>:	 [[{{node cluster_11_1/merge_oidx_69/_148}}]] [Op:__inference_train_one_step_88467]
[0]<stderr>:
[0]<stderr>:Function call stack:
[0]<stderr>:train_one_step
[0]<stderr>:
Process 0 exit with status code 1.
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 731, in _launch_job
    args.verbose)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 704, in run_controller
    gloo_run()
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/launch.py", line 720, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/gloo_run.py", line 284, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/usr/local/lib/python3.6/dist-packages/horovod/runner/gloo_run.py", line 271, in launch_gloo
    .format(name=name, code=exit_code))
```

**Comment by bas-aarts** [comment]
[
[git.patch.gz](https://github.com/tensorflow/tensorflow/files/5812626/git.patch.gz)
[dummy_p1.tfrecord.gz](https://github.com/tensorflow/tensorflow/files/5812628/dummy_p1.tfrecord.gz)
[run_electra_bug.sh.gz](https://github.com/tensorflow/tensorflow/files/5812634/run_electra_bug.sh.gz)


](url)

**Comment by amahendrakar** [comment]
@bas-aarts,
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. Thanks!

**Comment by sanjoy** [comment]
I was able to reproduce this.

When I look at the [entire log](https://gist.github.com/sanjoy/cb32509002a089b0c5a4aad6a9f28627) though, I see an OOM.  Do you see that as well?  If yes, it is possible that the OOM is the root cause and the `_Recv` failed because it was waiting on a `_Send` that failed because of the OOM.  Can you try adjusting the batch size etc. to make the OOM disappear and check if the failed recv error also goes away?

**Comment by bas-aarts** [comment]
@sanjoy, shooting from the hip here, but can you try running on 1 GPU only?
I reproduced on 1 GPU only (tried again just now on GV100 32GB), and see no OOM.
Perhaps multiple GPUs results in more allocation per GPU

try running with:
TF_XLA_FLAGS=--tf_xla_always_defer_compilation=true bash scripts/run_electra_bug.sh 1 6e-3 amp 1

**Comment by bas-aarts** [comment]
> The

I actually tried, but was not able to reduce significantly. I therefore choose to use the model as a repro.

**Comment by sanjoy** [comment]
Bas, is there a way to reduce the batch size so that it fits in a 16G P100 or V100?  I don't have access to a 32G V100.

**Comment by bas-aarts** [comment]
With the last  command line, BS=1

**Comment by sanjoy** [comment]
Bas, [this](https://gist.github.com/sanjoy/a5eb963dbc567f98a3e0fa4d888cabe3) is the full log with 1GPU and the command line you mentioned in https://github.com/tensorflow/tensorflow/issues/46419#issuecomment-764001365. In the log I see many lines like:

```
[0]<stderr>:2021-01-26 05:17:39.245145: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at resource_variable_ops.cc:536 : Not found: Resource localhost/_AnonymousVar837/N10tensorflow3VarE does not exist.
```

preceding the `RecvAsync` failure.  So I suspect these errors are causing a previous Send to fail, resulting in the later failed Recv.  Does this sound plausible?

**Comment by bas-aarts** [comment]
I'm certain the warnings have something to do with the problem.  Since these are no errors, I do not know how serious the issue is.

**Comment by bas-aarts** [comment]
Any updates on this? perhaps even an ETA?

**Comment by sanjoy** [comment]
Bas,

Sorry for the delay, after https://github.com/tensorflow/tensorflow/issues/46419#issuecomment-767343956 I assumed that you're going to look into this further.  Looks like that was a mis-parsing on my part.

I strongly suspect that some Grappler-esque pass is running after auto-clustering and DCE'ing an XLA cluster.  The following change seems to fix the symptom at least ([log](https://gist.github.com/sanjoy/deb3a6c6a0a4821e93d3de4389ef074e)):

```
diff --git a/tensorflow/compiler/jit/build_xla_ops_pass.cc b/tensorflow/compiler/jit/build_xla_ops_pass.cc
index a340b9d3f45..e7c0c10a225 100644
--- a/tensorflow/compiler/jit/build_xla_ops_pass.cc
+++ b/tensorflow/compiler/jit/build_xla_ops_pass.cc
@@ -309,9 +309,9 @@ xla::StatusOr<Node*> ReplaceFunctionCallWithPartitionedCall(
     }
   }
 
-  ops::PartitionedCall call(
-      root.WithOpName("partitioned_call"), args, n->output_types(), func,
-      ops::PartitionedCall::Attrs{}.ConfigProto(config_string));
+  ops::StatefulPartitionedCall call(
+      root.WithOpName("stateful_partitioned_call"), args, n->output_types(),
+      func, ops::StatefulPartitionedCall::Attrs{}.ConfigProto(config_string));
 
   for (const Edge* e : n->in_edges()) {
     if (e->IsControlEdge()) {
```

So I think the correct solution is to use `StatefulPartitionedCall` when the XLA cluster has any resource variable operations.  But before we do that, I'd prefer confirm that this theory is correct -- would you be able to put some time into verifying this theory?  For this theory to be correct, there has to be a DCE-like pass that runs after build_xla_ops_pass that deletes non-stateful partitioned call ops.  This pass is likely being run from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/optimization_registry.cc).

@cheshire and @nnigania also ran into a variant of this issue IIRC.

**Comment by bas-aarts** [comment]
I'll take a look @sanjoy

**Comment by cheshire** [comment]
@bas-aarts As discussed, there is the patch I've used.

In file `def_function.py`, after inserting `_noinline=True`, add

> `attributes.update(_grappler_do_not_remove=True)` (line 658)

Inside `functional_ops.py`, at line 1223, add:

```
  if grappler_do_not_remove_attr in f.definition.attr:
    op_attrs[grappler_do_not_remove_attr] = f.definition.attr[
      grappler_do_not_remove_attr]
```

where `grappler_do_not_remove_attr = '_grappler_do_not_remove`

**Comment by sanjoy** [comment]
Undoing auto-close.

**Comment by bas-aarts** [comment]
@cheshire, would you mind attaching a git patch instead? want to make sure I do the right thing. thanks.

**Comment by cheshire** [comment]
hi Bas,

I don't have a git patch, as this change is internal. Do you think you
could try it and maybe show the patch you create to double check?

George

**Comment by bas-aarts** [comment]
Hi George,

with the following diff, the error is still there:

diff --git a/tensorflow/python/eager/def_function.py b/tensorflow/python/eager/def_function.py
index da19acad243..475fa810433 100644
--- a/tensorflow/python/eager/def_function.py
+++ b/tensorflow/python/eager/def_function.py
@@ -655,6 +655,7 @@ class Function(object):
       attributes.update(_XlaMustCompile=bool(self._jit_compile))
       if self._jit_compile:
         attributes.update(_noinline=True)
+        attributes.update(_grappler_do_not_remove=True)
     if not attributes:
       attributes = None
     return function_lib.defun_with_attributes(
diff --git a/tensorflow/python/ops/functional_ops.py b/tensorflow/python/ops/functional_ops.py
index bdd20cda991..2caae0dc24e 100644
--- a/tensorflow/python/ops/functional_ops.py
+++ b/tensorflow/python/ops/functional_ops.py
@@ -1218,6 +1218,9 @@ def partitioned_call(args,
   }
   if xla_compile_attr in f.definition.attr:
     op_attrs[xla_compile_attr] = f.definition.attr[xla_compile_attr]
+  grappler_do_not_remove_attr = "_grappler_do_not_remove"
+  if grappler_do_not_remove_attr in f.definition.attr:
+    op_attrs[grappler_do_not_remove_attr] = f.definition.attr[grappler_do_not_remove_attr]
   op = graph.create_op(op_name, args, tout, name=op_name, attrs=op_attrs)
   outputs = op.outputs
   if hasattr(f, "graph"):

**Comment by bas-aarts** [comment]
Hi George.

with the following diff the original error is still there
```
diff --git a/tensorflow/python/eager/def_function.py b/tensorflow/python/eager/def_function.py
index da19acad243..475fa810433 100644
--- a/tensorflow/python/eager/def_function.py
+++ b/tensorflow/python/eager/def_function.py
@@ -655,6 +655,7 @@ class Function(object):
       attributes.update(_XlaMustCompile=bool(self._jit_compile))
       if self._jit_compile:
         attributes.update(_noinline=True)
+        attributes.update(_grappler_do_not_remove=True)
     if not attributes:
       attributes = None
     return function_lib.defun_with_attributes(
diff --git a/tensorflow/python/ops/functional_ops.py b/tensorflow/python/ops/functional_ops.py
index bdd20cda991..2caae0dc24e 100644
--- a/tensorflow/python/ops/functional_ops.py
+++ b/tensorflow/python/ops/functional_ops.py
@@ -1218,6 +1218,9 @@ def partitioned_call(args,
   }
   if xla_compile_attr in f.definition.attr:
     op_attrs[xla_compile_attr] = f.definition.attr[xla_compile_attr]
+  grappler_do_not_remove_attr = "_grappler_do_not_remove"
+  if grappler_do_not_remove_attr in f.definition.attr:
+    op_attrs[grappler_do_not_remove_attr] = f.definition.attr[grappler_do_not_remove_attr]
   op = graph.create_op(op_name, args, tout, name=op_name, attrs=op_attrs)
   outputs = op.outputs
   if hasattr(f, "graph"):
```

**Comment by bas-aarts** [comment]
I have confirmed that @sanjoy's proposed change does not trigger the error.

**Comment by bas-aarts** [comment]
@cheshire , can you please let me know if the diff above is the one you expected to work? Thanks

**Comment by cheshire** [comment]
@bas-aarts yes. To clarify: I do not know whether it solves your problem or not. It solved one problem for me, I'm not sure whether you have the same one.
