### ISSUE TITLE
Timeseries example does not work with Preprocessing layers

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#46416]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tutorials/structured_data/time_series

## Description of issue (what needs changing):
The examples use methods such as 
```
data = np.array(data, dtype=np.float32)
ds = tf.keras.preprocessing.timeseries_dataset_from_array(
      data=data,
      targets=None,
      sequence_length=self.total_window_size,
      sequence_stride=1,
      shuffle=True,
      batch_size=32,)
```
But, this pretty much disables the usage of preprocessing layers to be built. And also, such an elaborate example does not use sequence features or input layer methods. The method ```timeseries_dataset_from_array``` pretty much did away any usage of preprocessing layers in the model. We can not effectively use feature layer engineering because we have to convert all the feature columns into float.

**Comment by ravikyram** [comment]
@summa-code 

Thank you for raising the issue.
Do you have any use case that supports the issue. Please feel free to submit a PR if you have use case supporting this.Thanks!

**Comment by summa-code** [comment]
It is example code. That is what i described.

**Comment by mohantym** [comment]
Hi @summa-code !
Is this issue still valid. Documentation on Time series has been updated and does not include tf.keras.preprocessing.timeseries_dataset_from_array now. 

Can we mark this issue .as resolved now.

Thank you!

**Comment by MarkDaoust** [comment]
> does not include tf.keras.preprocessing.timeseries_dataset_from_array now.

Yes it does.

> We can not effectively use feature layer engineering because we have to convert all the feature columns into float.

Valid criticism. 

This tutorial's already about 3x too long. 
A new tutorial under the "load_data" section could make sense.

I don't think I can get to it any time soon.

Any suggestions for a dataset?

It looks like `tf.keras.preprocessing.timeseries_dataset_from_array` doesn't currently support nested arrays, it may not be hard for it to, IDK.

**Comment by anishlukk123** [comment]
anyone working on this?
