### ISSUE TITLE
how to restore  part of the model,  then save the whole model after training?

### ISSUE THREAD

**Issue by Liujingxiu23** [tensorflow/tensorflow#46424]
I want to finetine a base model using a new dataset.
The model have two part: part1 + part2
I only want to restore the variables of part1.

1.restore the model using:
    saver = tf.train.Saver(variables_of_part1, max_to_keep=1000)
2.Training
3.Save the model
But the new model saved lost the variables of part2.

How can I realize "restore part of a model, trainning, then save the whole model"?

My tensorflow version is 1.10.

**Comment by ravikyram** [comment]
@Liujingxiu23 

TF 1.10 is very old.TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version TFv2.4 and the below tutorial helps you .

https://www.tensorflow.org/tutorials/keras/save_and_load

**Comment by Liujingxiu23** [comment]
@ravikyram  Thank you for you reply, I tried to solve the problem just by adding another saver before training and found it works.

**Comment by ravikyram** [comment]
@Liujingxiu23 

Glad to know its resolved.Please, close this thread as your issue was resolved. Thanks!
