### ISSUE TITLE
[tf-nightly] `keras.callbacks.EarlyStopping` stops training immediately after the first epoch even if monitored score has improved

### ISSUE THREAD

**Issue by harupy** [tensorflow/tensorflow#46429]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### Code to reproduce 

```python
import tensorflow as tf
import keras

from unittest import mock
from functools import reduce


def print_attr(obj, attr):
    print(attr.ljust(20), ":", reduce(lambda a, b: getattr(a, b), attr.split("."), obj))


def print_divider(title):
    print(f"\n========== {title} ==========")


def print_es_attrs(es):
    for attr in [
        "patience",
        "stopped_epoch",
        "wait",
        "best",
        "best_weights",
        "model.stop_training",
    ]:
        print_attr(es, attr)


es = keras.callbacks.EarlyStopping(
    monitor="loss", mode="min", patience=0, restore_best_weights=True, verbose=1
)
es.model = mock.MagicMock(stop_training=False)

print_divider("TF and Keras version")
print("tf:", tf.version.GIT_VERSION, tf.version.VERSION)
print("keras:", keras.__version__)


es.on_train_begin()
print_divider("After train_begin")
print_es_attrs(es)

print_divider("Call on_epoch_end")
es.on_epoch_end(epoch=0, logs={"loss": 1.0})

print_divider("After on_epoch_end")
print_es_attrs(es)
```

This prints out:

```diff
  ========== TF and Keras version ==========
+ tf: v1.12.1-48978-gad524691510 2.5.0-dev20210114 <- using tf-nightly
  keras: 2.4.3
  
  ========== After train_begin ==========
  patience             : 0
  stopped_epoch        : 0
  wait                 : 0
+ best                 : inf
  best_weights         : None
+ model.stop_training  : False
  
  ========== Call on_epoch_end ==========
  Restoring model weights from the end of the best epoch.
  
  ========== After on_epoch_end ==========
  patience             : 0
  stopped_epoch        : 0
  wait                 : 0
+ best                 : 1.0
  best_weights         : <MagicMock name='mock.get_weights()' id='140324772920720'>
+ model.stop_training  : True  <- should this be False because score has improved from inf to 1.0?
```

Sorry if I'm wrong but is this intended behavior?

**Comment by harupy** [comment]
Ran the same code with `tensorflow==2.4.0`

```
========== TF and Keras version ==========
tf: v2.4.0-rc4-71-g582c8d236cb 2.4.0
keras: 2.4.3

========== After train_begin ==========
monitor_op           : <ufunc 'less'>
patience             : 0
stopped_epoch        : 0
wait                 : 0
best                 : inf
best_weights         : None
model.stop_training  : False

========== Call on_epoch_end ==========

========== After on_epoch_end ==========
monitor_op           : <ufunc 'less'>
patience             : 0
stopped_epoch        : 0
wait                 : 0
best                 : 1.0
best_weights         : <MagicMock name='mock.get_weights()' id='140291636062288'>
model.stop_training  : False <-
```

**Comment by harupy** [comment]
https://github.com/tensorflow/tensorflow/blob/abcabe12666d064da4710d965c36a59c937eab12/tensorflow/python/keras/callbacks.py#L1766-L1790

It looks like `self.wait` is incremented regardless of score improvement.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/287a3a54ee2ab01da24f28b06a6e0ae1/46429-2-3.ipynb), [TF v2.4](https://colab.research.google.com/gist/amahendrakar/66188c31e71e58fb365e7556a2d6cbe7/46429.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8bfa154e314e3e5c8ccd76c9b76ff2b6/46429-2-5.ipynb). Please find the gist of it here. Thanks!

**Comment by harupy** [comment]
@amahendrakar Thanks!

**Comment by harupy** [comment]
I'm a bit confused about how `patience` works.

Let's say we have the following traning session where `score` never improves from `1.0`.

|epoch|score|
|:-|:-|
|1|1.0|
|2|1.0|
|3|1.0|

if `baseline` is unspecified and `patience` is 1, after which epoch should the training early stop?

**Comment by harupy** [comment]
@jvishnuvardhan Does tensorflow 2.5.0 contain a patch for this issue?

**Comment by jvishnuvardhan** [comment]
@harupy It looks like this is intended behavior. Please check the source code here https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/callbacks.py#L1801-L1803

During `on_train_begin`, self.wait is set as `0`. On `on_epoch_end`, self.wait += 1. 

So `on_epoch_end`, the above condition becomes True and `stop_training` (self.model.stop_training = True) flag is set as True. Please let us know what you think. Thanks!

**Comment by harupy** [comment]
Thanks@jvishnuvardhan  for the explanation! Looks like this is an intended behavior.
