### ISSUE TITLE
PIP Tensorflow-gpu

### ISSUE THREAD

**Issue by TekpreXyz** [tensorflow/tensorflow#46420]
I read in docs that for new version of tensorflow gpu support is integrated 
so if i run: pip install tensorflow, i have both cpu and gpu support.

Now the question is: why is still present 
pip install tensorflow-gpu 2.4.0 ???
https://pypi.org/project/tensorflow-gpu/

anyway
i installed  TS whit command "pip install tensorflow"

if i run 
```
C:\Users\Kit>nvcc -V 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:35_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28845127_0
```
so everithink seems fine
also for 
C:\Users\Kit>nvidia-smi
Thu Jan 14 08:02:30 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.89       Driver Version: 460.89       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0  On |                  N/A |
| 35%   14C    P8    N/A /  75W |    758MiB /  4096MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

but when i run 
```
from keras import backend as K
print(tf.config.list_physical_devices('GPU'))
or
import tensorflow as tf
print(tf.test.gpu_device_name())
```
i can see only cpu

but if i install whit
pip install tensorflow-gpu 2.4.0

i can see cpu AND gpu in python

I'M A BIT CONFUSED

**Comment by mihaimaruseac** [comment]
There are CI scripts that still use `tensorflow-gpu`. So we upload the same pip package (modulo renaming) twice.
