### ISSUE TITLE
[RNN] models cannot run in TFLite with delegates

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#46426]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Qualcomm Snapdragon 865
- TensorFlow installed from (source or binary): Source 
- TensorFlow version (or github SHA if from source): Nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
tf_model = tf.keras.models.load_model('./my_model.h5')

for i in range(4):
    tf_model.inputs[i].shape._dims[0] = tf_python.framework.tensor_shape.Dimension(1)

model_func = tf.function(lambda a: tf_model(a))
concrete_func = model_func.get_concrete_function([tf.TensorSpec(tf_model.inputs[0].shape, tf_model.inputs[0].dtype), tf.TensorSpec(tf_model.inputs[1].shape, tf_model.inputs[1].dtype), tf.TensorSpec(tf_model.inputs[2].shape, tf_model.inputs[2].dtype), tf.TensorSpec(tf_model.inputs[3].shape, tf_model.inputs[3].dtype)])

tf_out = concrete_func([input_1, gru0_1_h_in, gru1_1_h_in, out_quats_gru1_h_in])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
2021-01-14 11:16:28.325520: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:933] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 389 nodes (195), 590 edges (225), time = 6.75ms.
  function_optimizer: Graph size after: 389 nodes (0), 590 edges (0), time = 3.64ms.
Optimization results for grappler item: while_body_2339
  function_optimizer: function_optimizer did nothing. time = 0.004ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
Optimization results for grappler item: while_cond_2338
  function_optimizer: function_optimizer did nothing. time = 0.004ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
Optimization results for grappler item: while_cond_2708
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: while_body_2709
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
Optimization results for grappler item: while_body_1969
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
Optimization results for grappler item: while_cond_1968
  function_optimizer: function_optimizer did nothing. time = 0.003ms.
  function_optimizer: function_optimizer did nothing. time = 0.002ms.

2021-01-14 11:16:28.851727: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:332] Ignored output_format.
2021-01-14 11:16:28.851756: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:335] Ignored drop_control_dependency.
2021-01-14 11:16:28.895692: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.

```

**Also, please include a link to the saved model or GraphDef**

```
My Keras model contains a GRU layer, here is what the Keras layer converts to in TFLite:

![Screenshot from 2021-01-14 06-12-45](https://user-images.githubusercontent.com/67419721/104586228-348e6480-5633-11eb-9558-047cd559280b.png)


```

**Failure details**
Model conversion was successful. and runs on CPU. However, when I try to initialize an OpenCL delegate, I get the following run time error:

ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
interpreter->ModifyGraphWithDelegate failed

I suspect the problem is with those `While` ops generated by the converter. My GRU layer is stateless, where I manually manage the layer state (tf.keras.layers.GRU is defined with arguments: return_sequences=True, stateful=False, unroll=False. It is called with one of the model's inputs passed to the initial_state argument), and with the sequence dimension of 1. Is it possible to tell the TFLite converter to generate a graph that doesn't contain a while loop? Since in my situation I don't actually need to have a loop in my GRU.

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by impjdi** [comment]
Yeah, this is a question to the TFLiteConverter folks.  Un-assigning myself.

**Comment by renjie-liu** [comment]
Hi, I think our gpu delegate does not support control flow yet, you probably can try with unroll the GRU.

thanks

**Comment by teijeong** [comment]
Hi, have you tried GRU with unroll?

**Comment by DwayneDuane** [comment]
I ended up breaking up the GRU layer into its constituent matrix and elementwise ops. Closing this issue as I have found a workaround.
