### ISSUE TITLE
cudart64_101.dll not found

### ISSUE THREAD

**Issue by JasonKramer525** [tensorflow/tensorflow#46437]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.2 and 7.6.5
- GPU model and memory: RTX 2070 Super

**Describe the problem**
I am trying to install TensorFlow and be able to use it on my computer. I am only writing "import tensorflow" in my python file and getting several errors. I am using conda and created a new virtual environment and downloaded tensorflow and tensorboard. I also downloaded the 10.1 file and put it in my bin folder but still getting the same error.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python
import tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Here is the error that I am currently getting:
 tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-14 14:04:25.725481: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by chazuttu** [comment]
Find the directory of dlls  and update your PATH to include that directory.
If that doesnt work try miniconda:
conda create --name .conda_venv
conda activate .conda_venv
conda install tensorflow-gpu

**Comment by Saduf2019** [comment]
@JasonKramer525 
Have you set in PATH
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin;%PATH%

Please verify if you have refered to  https://www.tensorflow.org/install/source#gpu, also please check resolved issue with ame error: [link](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install), #43193, #36111

**Comment by remixer-dec** [comment]
I had the same issue, copying cudart64_102.dll and renaming it to cudart64_101.dll solved it for me. And now tf.test.is_gpu_available() returns True .
