### ISSUE TITLE
Blas SGEMM launch failed : m=25600, n=64, k=64 [Op:Conv2D] when building model and restoring weights

### ISSUE THREAD

**Issue by Echambouleyron** [tensorflow/tensorflow#46431]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: tf-nightly-gpu 2.4.0-dev20201016
-   **Python version**: 3.8.5
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:  Cuda = 11.2 
-   **GPU model and memory**: GeForce RTX 2060 6000MB
-   **Exact command to reproduce**: 

num_classes = 1
pipeline_config = 'object_detection/configs/tf2/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.config'
checkpoint_path = 'object_detection/test_data/checkpoint/ckpt-0'

configs = config_util.get_configs_from_pipeline_file(pipeline_config)
model_config = configs['model']
model_config.ssd.num_classes = num_classes
model_config.ssd.freeze_batchnorm = True
detection_model = model_builder.build(
      model_config=model_config, is_training=True)

fake_box_predictor = tf.compat.v2.train.Checkpoint(
    _base_tower_layers_for_heads=detection_model._box_predictor._base_tower_layers_for_heads,
    # _prediction_heads=detection_model._box_predictor._prediction_heads,
    #    (i.e., the classification head that we *will not* restore)
    _box_prediction_head=detection_model._box_predictor._box_prediction_head,
    )
fake_model = tf.compat.v2.train.Checkpoint(
          _feature_extractor=detection_model._feature_extractor,
          _box_predictor=fake_box_predictor)
ckpt = tf.compat.v2.train.Checkpoint(model=fake_model)
ckpt.restore(checkpoint_path).expect_partial()

image, shapes = detection_model.preprocess(tf.zeros([1, 640, 640, 3]))
prediction_dict = detection_model.predict(image, shapes)
_ = detection_model.postprocess(prediction_dict, shapes)

It fails ath the second last line

**Comment by zhangbei07** [comment]
I have the same problem.My error message
2021-01-15 10:37:37.265487: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_INTERN                                                 AL_ERROR
Internal: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(135, 1296), b.shape=(1296, 120), m=135, n=120, k=1296
         [[{{node layer_0_type_0/MatMul}}]]
         [[o_energy/_43]]
  (1) Internal: Blas GEMM launch failed : a.shape=(135, 1296), b.shape=(1296, 120), m=135, n=120, k=1296
         [[{{node layer_0_type_0/MatMul}}]]
0 successful operations.
0 derived errors ignored.

Have I written custom code (as opposed to using a stock example script
provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7.6
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
happens on a mobile device:
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): tf1.14
Python version: 3.7.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: Cuda = 10.1
GPU model and memory: V100 16130MB

**Comment by Saduf2019** [comment]
@Echambouleyron
Could you please try with cuda 11.0 and let us know.

zhangbei07 
we see that you are using a old version of tf, there is no support for 1.x please upgrade to 2.x, verify the cuda version compatibility [here](https://www.tensorflow.org/install/source) and let us know if you face any issues.

**Comment by Echambouleyron** [comment]
@Saduf2019 This worked. No need to downgrade Cuda version to 11.0. Many thanks.

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

**Comment by Saduf2019** [comment]
@Echambouleyron 
Thank you for your update, glad the issue is resolved, please move this to closed status.
