### ISSUE TITLE
Missing include files in libtensorflow-cpu-windows-x86_64-2.4.0.zip

### ISSUE THREAD

**Issue by rani-pinchuk** [tensorflow/tensorflow#46432]
In the page https://www.tensorflow.org/install/lang_c there are links to two zip files for the Windows installation of the TensorFlow C API. 

These Windows zips: libtensorflow-cpu-windows-x86_64-2.4.0.zip and libtensorflow-gpu-windows-x86_64-2.4.0.zip are missing some of the includes:
```
.\include\tensorflow\c\c_api_experimental.h
.\include\tensorflow\c\c_api_macros.h
.\include\tensorflow\c\tensor_interface.h
.\include\tensorflow\c\tf_file_statistics.h
.\include\tensorflow\c\tf_tstring.h
```

This means that using this zip files (and unlike with the zip files of 2.3.1) you cannot build.

Thanks!

**Comment by shoelzer** [comment]
I ran into this issue and figured out a workaround. I downloaded the source for TensorFlow 2.4.0 and copied missing header files to the C API folder.

I copied these files:

* tensorflow-2.4.0/tensorflow/c/c_api_macros.h
* tensorflow-2.4.0/tensorflow/c/tf_tstring.h
* tensorflow-2.4.0/tensorflow/core/platform/ctstring.h
* tensorflow-2.4.0/tensorflow/core/platform/ctstring_internal.h

And copied them here:

* libtensorflow-gpu-windows-x86_64-2.4.0/include/tensorflow/c/c_api_macros.h
* libtensorflow-gpu-windows-x86_64-2.4.0/include/tensorflow/c/tf_tstring.h
* libtensorflow-gpu-windows-x86_64-2.4.0/include/tensorflow/core/platform/ctstring.h
* libtensorflow-gpu-windows-x86_64-2.4.0/include/tensorflow/core/platform/ctstring_internal.h

The other header files listed in the original report don't seem to be necessary.

**Comment by rani-pinchuk** [comment]
@shoelzer - indeed. I have also created for myself a separate zip file as a workaround. However, obviously, it will be nice if it is fixed to include the correct files.

Another related issue, which I am not sure deserves a separate entry, is that in the page https://www.tensorflow.org/install/lang_c there is a reference to the nightly builts page. However, that page does not contain the nightly builts for Windows. This should also be fixed because in the README.md (https://github.com/tensorflow/tensorflow) there is a "promise" that the nightly builds are available also for Windows (last two rows in the table https://github.com/tensorflow/tensorflow#official-builds).

**Comment by shoelzer** [comment]
@rani-pinchuk Yes, I think the missing Windows nightlies are worth a separate issue so I made one: #46538.

**Comment by ymodak** [comment]
You may try  TF 2.4.1 package, I see those files are covered in the package https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.4.1.zip
Also TF 2.5 was recently released which includes it as well.
