### ISSUE TITLE
Spurious results from a full-integer TensorFlow Lite model

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#46444]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.5.0-dev20210114 (`tf-nightly`)
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have been able to convert the [Boundless model](https://tfhub.dev/s?q=google%2Fboundless) with full integer quantization. However, the results of the model are spurious. 

**Describe the expected behavior**

The result should be consistent with the results from other TFLite variants of the same model. 

Here's the expected result - 

![image](https://user-images.githubusercontent.com/22957388/104683094-3bdd6d00-571c-11eb-87fa-f927b3c5a713.png)

The masked and the generated images are from the model. 

Here's the result from the integer model - 

![image](https://user-images.githubusercontent.com/22957388/104683131-4f88d380-571c-11eb-9655-5ce8f2f49fc2.png)

Notice how the masked and the generated images are spurious. Is this because I am constructing the representative dataset to only have 50 examples? Is the converter not able to appropriately approximate the activation ranges? 

**Standalone code to reproduce the issue**

Colab Notebook https://colab.research.google.com/gist/sayakpaul/5f52b65c849e751e81e4073d6cf737bf/boundless_tflite.ipynb

Cc: @abattery

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate the issue reported, please fin the [gist here](https://colab.research.google.com/gist/Saduf2019/ef14c11086b41416877508ab7bc7df55/untitled496.ipynb)

**Comment by abattery** [comment]
CCing terryheo@

**Comment by sayakpaul** [comment]
@abattery you probably used the email alias of Terry.

**Comment by teijeong** [comment]
Hi @sayakpaul,

I tried your colab, and got this result.
![image](https://user-images.githubusercontent.com/4837376/107916096-07720080-6fa9-11eb-8b23-9915c28b55d7.png)

Although image is not as good as dynamic_range quantized one, the error seems to affect only masked region. Can you try again with latest TF nightly?

Also, as I commented on the other issue https://github.com/tensorflow/tensorflow/issues/45932, you need to provide `tf.lite.OpsSet.TFLITE_BUILTINS` to `supportedd_ops` for dynamic range quantization.

**Comment by sayakpaul** [comment]
> Although image is not as good as dynamic_range quantized one, the error seems to affect only masked region. Can you try again with latest TF nightly?

Yes, will try and let you know. 

> Although image is not as good as dynamic_range quantized one, the error seems to affect only masked region. Can you try again with latest TF nightly?

Yes, noted.

**Comment by sayakpaul** [comment]
@teijeong I followed your suggestion on trying out with latest `tf-nightly`. No luck.

Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/c645035b5d8fc529a7396711c9013463/boundless_tflite.ipynb).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210602,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/9f796a7fdb02ae030d236f36a9ac8623/untitled496.ipynb#scrollTo=HMiJeeuIpCN9)..Thanks !

**Comment by pjpratik** [comment]
@sayakpaul As @teijeong suggested, the integer output seems to be better after adding `tf.lite.OpsSet.TFLITE_BUILTINS` in TF nightly 2.12.0-dev20230106. Can you please check this [gist](https://colab.research.google.com/gist/pjpratik/dd64b8ed170692aea056c5b9aaa33dab/46444.ipynb). Thank you.
