### ISSUE TITLE
Make tf.image.resize compatible with XLA compilation

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#46447]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, XLA compilation does not work for `tf.image.resize` when method is `tf.image.ResizeMethod.BILINEAR` or `tf.image.ResizeMethod.NEAREST_NEIGHBOR.` Because `half_pixel_centers` is forced to true [here](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/python/ops/image_ops_impl.py#L1623-L1627), but the tf2xla kernel forces `half_pixel_centers` to false [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/kernels/image_resize_ops.cc#L592).

This makes users unable to do upsampling/downsampling for images on TPU.

**Will this change the current api? How?**

No, just change underlying behavior.

**Who will benefit with this feature?**

Everyone who needs to use down/up sampling method for XLA.

**Any Other info.**

Colab to reproduce errors.

https://colab.research.google.com/drive/1RKW1U3pqoc7w58ifq0qjb6WqBJQ3cD9V?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ab3cafb61d1f52249596f76f3b53e762/46447-2-5.ipynb). Thanks!
