### ISSUE TITLE
An issue on cross-building Tensorflow Lite for Python

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/tensorflow#46443]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 x86_64 amd64 PC
- TensorFlow installed from (source or binary): v2.4
- Tensorflow version (commit SHA if source): 582c8d2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): RK3399 Ubuntu 18.04 aarch64

**Describe the problem**
I am going to get tflite whl for Python3 on aarch64.
So I tried to cross-build tflite whl on Ubuntu 18.04 x86_64 host PC.
But while compiling the source I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/104678949-87494880-5727-11eb-9b5d-850b3e81bf9d.png)

Host PC environment:
OS: Ubuntu 18.04 x86_64 AMD64
native gcc(g++): 7.5.0
cross-compiler aarch64-linux-gnu-gcc(aarch64-linux-gnu-g++): 7.5.0
bazel: 3.1.0
python: virtual env python 3.7

**Please provide the exact sequence of commands/steps when you ran into the problem**

I followed the following steps on my host PC.

sudo apt update
sudo apt-get install software-properties-common
sudo apt update
sudo apt install git curl
sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-distutils
sudo apt install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev

cd ~
python3.7 -m venv py37
source ~/py37/bin/activate
pip install cython
pip install wheel
pip install numpy

git clone -b r2.4 https://github.com/tensorflow/tensorflow.git tensorflow_r2.4
cd tensorflow_r2.4
python configure.py
![image](https://user-images.githubusercontent.com/47862419/104679377-81079c00-5728-11eb-9f23-a9bd0a3f8ff9.png)

./tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64

**Comment by chazuttu** [comment]
Maybe your repository is corrupted

**Comment by rose-jinyang** [comment]
No
I tried to find the file 'pyconfig.h' but there is NOT the file.

![image](https://user-images.githubusercontent.com/47862419/104688998-bd44f780-573c-11eb-8df2-ed72a2327956.png)

**Comment by chazuttu** [comment]
Open the new terminal & enter the command sudo apt-get install python-dev to get the latest default python-dev.

**Comment by rose-jinyang** [comment]
No, it is NOT

**Comment by rose-jinyang** [comment]
The command "sudo apt-get install python-dev" will install the corresponding files in the folder "/usr/include/x86_64-linux-gnu" rather than "/usr/include/aarch64-linux-gnu".

**Comment by terryheo** [comment]
You need to use tensorflow/tools/ci_build/ci_build.sh to use pre-configured Python Docker container for Python.

You can find example commands from this page.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by rose-jinyang** [comment]
I meant the issue on the host PC rather than docker.

**Comment by teijeong** [comment]
Hi @rose-jinyang ,

As @terryheo mentioned, building TFLite with docker (but still on the host machine) will handle most of compatibility issues by making an isolated environment. Can you try that workflow, instead of building with host's cross-complie toolchain?

**Comment by terryheo** [comment]
https://www.tensorflow.org/lite/guide/build_cmake_pip might be helpful.
