### ISSUE TITLE
Two SavedModel roundtrips lose track of a Resource's initializer and its assets

### ISSUE THREAD

**Issue by arnoegw** [tensorflow/tensorflow#46456]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): any
- TensorFlow installed from (source or binary): either
- TensorFlow version (use command below): 2.4.0, nightly
- Python version: any

**Describe the current behavior**
 1) Creating `MyLookupModel` as below and doing tf.saved_model.save, load on it recreates the `._vocab_table._initializer` but does not track it as a trackable subobject of `._vocab_table`.
 2) Doing tf.saved_model.save, load once more initializes the `._vocab_table` from the vocab file asset of the first SavedModel, not the second SavedModel - or crashes, if the first SavedModel is no longer available.

Item 1 appears to be a general issue with restored resource objects (not peculiar to StaticHashTable), and item 2 appears to be a direct consequence of it.

The end-to-end effect of this was reported in issue https://github.com/tensorflow/hub/issues/719 for a first SavedModel stored on TF Hub and a second SavedModel built from it by the user (with more parts added, and using Keras, but that seems immaterial).

**Describe the expected behavior**
 1) Saving and restoring `MyLookupModel` recreates the `._vocab_table._initializer` and tracks it as a trackable subobject of `._vocab_table`.
 2) Saving and restoring the model once more initializes the `._vocab_table` from the vocab file asset of the second SavedModel - with no need for the first SavedModel to be available in that time and place.

**Standalone code to reproduce the issue**

See also b/177326279

```python
class MyLookupModel(tf.train.Checkpoint):
  def __init__(self, vocab_file):
    super().__init__()
    vocab_initializer = tf.lookup.TextFileInitializer(
        vocab_file,
        key_dtype=tf.string, key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
        value_dtype=tf.int64, value_index=tf.lookup.TextFileIndex.LINE_NUMBER)
    self._vocab_table = tf.lookup.StaticHashTable(vocab_initializer,
                                                  default_value=-1)

  @tf.function(input_signature=[tf.TensorSpec((None,), tf.string)])
  def __call__(self, inputs):
    return self._vocab_table.lookup(inputs)

ORIGINAL_VOCAB = "/tmp/original/vocab.txt"
tf.io.gfile.makedirs(os.path.dirname(ORIGINAL_VOCAB))
with tf.io.gfile.GFile(ORIGINAL_VOCAB, "w") as f:
  for x in ["a", "b", "c", "d"]:
    f.write(x + "\n")

model0 = MyLookupModel(ORIGINAL_VOCAB)
tf.saved_model.save(model0, "/tmp/model1")
model1 = tf.saved_model.load("/tmp/model1")
tf.saved_model.save(model1, "/tmp/model2")
# If "/tmp/model1/assets/vocab.txt" is deleted at this point, the next line crashes.
model2 = tf.saved_model.load("/tmp/model2") 
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d10a3b25b824b58b198a4b8cf892d372/46456-tf-nightly.ipynb). Thanks!

**Comment by lmxx1234567** [comment]
Is there any workaround?  I have try to copy assets to the specified directory, It works. But it is not suitable for distribution.

**Comment by arnoegw** [comment]
Yes, there is a simple but tedious workaround: make the Asset (here: `._vocab_table._initializer._filename`) reachable by some other path of Trackable objects (for example, here in `MyLookupModel.__init__()`, change the local variable `vocab_initializer` to an attribute `self._vocab_initializer`, so that the asset is tracked as `modelX._vocab_initializer._filename` even if the path via `._vocab_table` is lost in `model1`).

**Comment by arnoegw** [comment]
This has been fixed by https://github.com/tensorflow/tensorflow/commit/149691c4b1628ea67b06188503dc2fc4a6be3317, which has already been available from tf-nightly for a while and is expected to be released with TF2.5. Thank you, @k-w-w !
