### ISSUE TITLE
Import Issue of cross-built tflite package

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/tensorflow#46455]
System information

Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 x86_64 amd64 PC
TensorFlow installed from (source or binary): v2.4
Tensorflow version (commit SHA if source): 582c8d2
Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): RK3399 Ubuntu 18.04 aarch64

Describe the problem:

I built the tflite runtime whl on host PC and tried to import the whl package file in python 3.7.
But I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/104740652-264f5e00-5783-11eb-8add-5d517757adf2.png)

Host PC environment:
OS: Ubuntu 18.04 x86_64 AMD64
native gcc(g++): 7.5.0
ldd: 2.27 
cross-compiler aarch64-linux-gnu-gcc(aarch64-linux-gnu-g++): 8.3.0 (This is downloaded and used automatically when building )
bazel: 3.1.0
python: virtual env python 3.7

Target device environment:
OS: Ubuntu 18.04 LTS aarch64
native gcc(g++): 7.5.0
ldd: 2.27
python: 3.7

Please provide the exact sequence of commands/steps when you ran into the problem

I followed the following steps on my host PC.

sudo apt update
sudo apt-get install software-properties-common
sudo apt update
sudo apt install git curl
sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-distutils
sudo apt install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev

cd ~
python3.7 -m venv py37
source ~/py37/bin/activate
pip install cython
pip install wheel
pip install numpy

git clone -b r2.4 https://github.com/tensorflow/tensorflow.git tensorflow_r2.4
cd tensorflow_r2.4
python configure.py

![image](https://user-images.githubusercontent.com/47862419/104741092-b2fa1c00-5783-11eb-81a2-7315f1660250.png)

./tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64

The whl file "tflite_runtime-2.4.0-py3-none-linux_aarch64.whl" is outputted in the folder "tensorflow_r2.4/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist".

When importing the tflite run-time package on the target device platform, The issue occurs.

from tflite_runtime.interpreter import Interpreter

**Comment by teijeong** [comment]
Can you try building with docker, as mentioned in https://github.com/tensorflow/tensorflow/issues/46443?

Also you might want to check if the host's cross-compiler and target environments share the same glibc version.

**Comment by terryheo** [comment]
For GLIBC compatibility, please refer the following.
https://www.tensorflow.org/lite/guide/build_cmake_arm#checking_glibc_version

You might need to use custom toolchain with CMake.
https://www.tensorflow.org/lite/guide/build_cmake_pip
