### ISSUE TITLE
No estimated time using model.fit() with TFRecord Dataset.

### ISSUE THREAD

**Issue by BenjaminChoou** [tensorflow/tensorflow#46454]
There is no estimated time when I call model.fit() with TFRecord Dataset.

```
   2448/Unknown - 894s 364ms/step - loss: 0.0703
```

**Comment by ravikyram** [comment]
@BenjaminChoou 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please,share colab link or simple standalone cose to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by BenjaminChoou** [comment]
Sorry. I found the estimated time will appear after 1 epoch training.
