### ISSUE TITLE
unable to load weights from directories other than the working directory

### ISSUE THREAD

**Issue by ghylander** [tensorflow/tensorflow#46450]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): tf-nightly-gpu v2.5.0.dev20201214
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA v11.0
- GPU model and memory: Tesla T4 15109MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
If i use model.load_weights(dir) and specify a directory similarly to how it's done in the docs:

checkpoint_filepath = "./checkpoints/training_checkpoints_tests/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_filepath)

 if os.path.exists(checkpoint_dir):
            model.load_weights(checkpoint_filepath)
            print('Checkpoints loaded')
        else:
            !mkdir -p './checkpoints/training_checkpoints_tests'
            print('No checkpoints found')

however the script never actually reads into the directory i'm specifying. If i instead load checkpoints directly from the working directory:

checkpoint_filepath = "/training_checkpoints_tests/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_filepath)

 if os.path.exists(checkpoint_dir):
            model.load_weights(checkpoint_filepath)
            print('Checkpoints loaded')
        else:
            !mkdir -p '/training_checkpoints_tests'
            print('No checkpoints found')

it works no problem. This second approach is fine if you have few models or checkpoints, but the direcotry quickly fills with folders and folders of checkpoints of different models and runs and it'd be better to keep all checkpoint in a folder

**Describe the expected behavior**
load checkpoints from sub-directories

**Standalone code to reproduce the issue**
See above

**Comment by kashyapraval** [comment]
checkpoint_filepath = "./checkpoints/training_checkpoints_tests/cp.ckpt"

what is the pwd here? Please write the entire path.

**Comment by ghylander** [comment]
"$USER/(private github repository name)/MobilenetV3Large/checkpoints/training_checkpoints_tests/cp.ckpt"

**Comment by Saduf2019** [comment]
@ghylander 
There are too many indentation errors, can you please share your code on a colab gist with the error reported.

**Comment by ghylander** [comment]
While preparing the code to be linked here i think i found the issue

in the docs [https://www.tensorflow.org/guide/keras/save_and_serialize](url) checkpoint filepaths are specified with double quotes ""

i.e: `model.load_weights("pretrained_ckpt")`

this is not the correct way to specify filepaths/directories or files in linux, Single quotes '' are to be used

when specifying working directory paths, using double quotes works probably because python handles the paths as entities, while using os.path.exists may not correctly identify paths written inside double quotes.

**Comment by ghylander** [comment]
i ran a test and loading the checkpoints in a subdirectory, without using os.path.exists, will indeed load the checkpoints

**Comment by Saduf2019** [comment]
@ghylander 
Please move the issue to closed status if resolved.

**Comment by ghylander** [comment]
should i post it to the docs repository?

**Comment by Saduf2019** [comment]
@ghylander
please create a pr in docs repo and move this to closed status.
