### ISSUE TITLE
tensorflow/core/kernels/sparse_matmul_op_test segfaults due to wrong alignment

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#46460]
Using TensorFlow 2.4.0 on an x86 system with GCC 8.3.0

**Describe the current behavior**

The test code has an over-aligned class: https://github.com/tensorflow/tensorflow/blob/f18495306f26fa2e1d3351c03838cde265eb6690/tensorflow/core/kernels/sparse_matmul_op_test.cc#L265-L327

As this is used as a test fixture in https://github.com/tensorflow/tensorflow/blob/f18495306f26fa2e1d3351c03838cde265eb6690/tensorflow/core/kernels/sparse_matmul_op_test.cc#L329 this class is allocated via `new` by GoogleTest

In C++14 this is not supported, in C++17 it is. See the GCC manual for e.g.:
```
'-Waligned-new'
     Warn about a new-expression of a type that requires greater
     alignment than the 'alignof(std::max_align_t)' but uses an
     allocation function without an explicit alignment parameter.  This
     option is enabled by '-Wall'.
```

Also compare the results at https://gcc.godbolt.org/z/PnnceM

As the result the class may not be aligned correctly and create a segfault when running https://github.com/tensorflow/tensorflow/blob/f18495306f26fa2e1d3351c03838cde265eb6690/tensorflow/core/kernels/sparse_matmul_op_test.cc#L330 (which GCC vectorizes assuming the alignment)

I have found that the alignment of the class varies based on even the folder where the binary is run from. So reproducing requires a bit of experimenting but the above descriptions should make it clear that this is fragile.

**Other info / logs**

I suggest to enable the `-Waligned-new` as an error to catch such mistakes in the future.
A workaround here is to enable the GCC flag `-faligned-new` which provides the C++17 `new` functions. Alternatively moving those fields out of the class will also work.

**Comment by cantonios** [comment]
Nice catch!  We can fix this in the general case by using an Eigen macro to provide a custom aligned `new` operator.  Fix should propagate soon.
