### ISSUE TITLE
Query: Convert Tensorflow NMT with attention model to tfjs

### ISSUE THREAD

**Issue by kabyanil** [tensorflow/tensorflow#46464]
I'm following the TensorFlow NMT with attention (link) guide to build a character level transliteration model. I'm able to train the model and make inference calls in an .ipynb notebook. I'm able to save training checkpoints and load them later. However, my front end application is built on electron js. Therefore, I need to convert the encoder-decoder model to tfjs. Would anybody provide some guidance to convert my model to tfjs? I'd be happy to provide source code if needed.

**Comment by ravikyram** [comment]
@kabyanil 

Please, refer this [link](https://github.com/tensorflow/tfjs-converter/tree/master/tfjs-converter) and see if it helps you.
This issue is more suitable for TFjs repo. Please post it on TFjs repo from [here](https://github.com/tensorflow/tfjs/issues/new). Thanks!

**Comment by kabyanil** [comment]
@ravikyram 

Thank you for replying. the TensorFlow tutorial builds an Encoder and Decoder using subclassing. It doesn't have a single Model. My confusion is how to save this Encoder-Decoder model when it doesn't have a single Model? For instance, when we build a sequential Model, we can call methods such as model.fit(), model.predict(), model.save() etc. But what do we do when we don't have a model to call? or in other words, how do we construct a model when using subclassing for the Encoder and the Decoder separately, as shown in the tutorial?

The provided tutorial works perfectly. I'm confused about how to construct a single model from the architecture. If I'm able to construct a model, then I'll be able to save the model and call the tensorflowjs_converter script to port the model to tfjs.

will you be able to guide me on that?

**Comment by ravikyram** [comment]
@kabyanil 

Can you share colab link or simple standalone code to reproduce the issue. It helps in localizing the issue. Thanks!

**Comment by kabyanil** [comment]
@ravikyram 

it's the exact same code as the tensorflow official tutorial, [nmt with attention](https://www.tensorflow.org/tutorials/text/nmt_with_attention). i was only experimenting with a different dataset.

using my own dataset, i am already able to load checkpoints and make inference calls within the .ipynb script. just seeking some guidance for saving the model in SavedModel format (any format works) and then calling tensorflowjs_converter script to port the model to tfjs, as my requirement is to make inferences within an electronjs app. it's totally ok with you take the official tutorial itself as reference code.

**Comment by rthadur** [comment]
Related question has been resolved in tfjs repo https://github.com/tensorflow/tfjs/issues/4566 , thank you
