### ISSUE TITLE
Doc : keras.utils.plot_model prints the shape as (None, n) but outdated (?, n) is given in doc  

### ISSUE THREAD

**Issue by zyberg2091** [tensorflow/tensorflow#46461]
## URL(s) with the issue:

https://www.tensorflow.org/guide/keras/functional

## Description of issue (what needs changing):

keras.utils.plot_model prints the shape as (None, n) but given in doc as (?, n)

### Clear description

Watch the line `keras.utils.plot_model(model, "my_first_model_with_shape_info.png", show_shapes=True)` in the doc link provided above.The output shown there is outdated

### Correct links

[Gist](https://colab.research.google.com/drive/19dlb-Qcoo2EBDigpZ8E75cb63woYI_EI?usp=sharing) here to show the changes.
Tensorflow version: 2.4

### Submit a pull request?
 Yes

**Comment by zyberg2091** [comment]
A PR has to be merged with keras team but it was mentioned in the tensorflow documentation.so i opened it here.

**Comment by salonidabgar** [comment]
Hello! I am new to the open source community and would like to contribute to this issue.

**Comment by yashk2810** [comment]
This is now fixed: https://www.tensorflow.org/guide/keras/functional
