### ISSUE TITLE
tensorflow.io.gfile.GFile: utf-8 can't decode byte 0xe9 (with both 'r' and 'rb' arguments), while normal open can read the file

### ISSUE THREAD

**Issue by fabrien** [tensorflow/tensorflow#46474]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary via pip
- TensorFlow version: 2.4.0
- Tensorflow IO version: 0.17.0
- Tensorflow datasets: 4.2.0
- Python version: 3.7.7
- CUDA/cuDNN version: 11.2.67/8.0.5.39
- GPU model and memory: GTX 965M/8Gb

**Describe the current behavior**
I am trying to generate a tensorflow dataset using tfds, by following this tutorial: https://www.tensorflow.org/datasets/add_dataset. I do so using the dataset from https://achrafothman.net/site/asl-smt/ (Corpus sample data) which consists of 2 text files, one in English, and the other in American SIgn Language glossed (still text). The files are utf-8-sig encoded, but the same behaviour happens when I save the files as utf-8. Before doing the tfds dataset, I simply opened the file with open, and that worked just fine. However, I am now trying to open them while creating my own dataset, so I import tfds. However, this library raises an error when one uses os.open, saying that we should use its own function, GFile. I then replaced my open with gfile.GFile(filename, 'r'), but it produces the following error when I am running the test (`python -m asgl_dataset.asgl_dataset_test`) (It does pass some tests before raising an error, which I guess are not important to paste here):
```
======================================================================
ERROR: test_download_and_prepare_as_dataset (__main__.AslgDatasetTest)
AslgDatasetTest.test_download_and_prepare_as_dataset
Run the decorated test method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\testing\test_utils.py", line 276, in decorated
    f(self, *args, **kwargs)
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\testing\dataset_builder_testing.py", line 307, in test_download_and_prepare_as_dataset
    self._download_and_prepare_as_dataset(self.builder)
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\testing\dataset_builder_testing.py", line 372, in _download_and_prepare_as_dataset
    builder.download_and_prepare(download_config=download_config)
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 446, in download_and_prepare
    download_config=download_config,
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1181, in _download_and_prepare
    leave=False,
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1176, in <listcomp>
    for split_name, generator
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\core\split_builder.py", line 295, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\core\split_builder.py", line 359, in _build_from_generator
    leave=False,
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tqdm\std.py", line 1165, in __iter__
    for obj in iterable:
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow_datasets\testing\dataset_builder_testing.py", line 402, in _iter_examples
    for key, ex in generator:
  File "D:\Documents\Epitech\Gesture\gesturesoftware\src\backend\aslg pc12 dataset\aslg_dataset\aslg_dataset.py", line 79, in _generate_examples
    english = gfile.GFile('english_processed_utf8.txt', 'rb').read()
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 117, in read
    self._preread_check()
  File "D:\Anaconda\envs\deeplearning_37\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 80, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 85: invalid continuation byte
```
From my understanding, I think that GFile simply does not handle special characters, such as 'é'. After searching the web, I found that a common solution was to use GFile(filename, 'rb') (instead of 'r', so that the file is read as bytes), but this results in the exact same behavior. 

**Describe the expected behavior**
The files should open properly using GFile, or AT LEAST let the user use open, and let me move on to parse the text they contain so that I can produce my dataset. 

**Standalone code to reproduce the issue**
The files were downloaded from the previously mentioned link (https://achrafothman.net/site/asl-smt/), and then first processed using a small script. The files with '_utf8' in the name were opened with Windows' notepad, and then I used 'saved as', and selected the encoding to be 'utf-8' instead of 'utf-8 without bom'.

Small script:
```python
def delete_end_dots(input_file_name, output_file):
    with open(input_file_name, "r", encoding="utf-8") as input_f, open(output_file, "w+", encoding="utf-8") as out_f:
        for line in input_f:
            line = line.strip()
            splitted = line.split(" ")
            if splitted[-1] == '.':
                splitted = splitted[:-1]
            line = " ".join(splitted)
            print(line, file=out_f)


delete_end_dots("sample-corpus-asl-en.asl.txt", "asl_processed.txt")
delete_end_dots("sample-corpus-asl-en.en.txt", "english_processed.txt")
```

aslg_dataset.py:
```python

"""aslg_dataset dataset."""

import sys
print("started on kernel {}".format(print(sys.executable)))

import tensorflow_datasets as tfds
import re
import tensorflow.io.gfile as gfile

# TODO(aslg_dataset): Markdown description  that will appear on the catalog page.
_DESCRIPTION = """
## ASLG-SMT Dataset 
## by Achraf Othman and Mohamed Jemni
This dataset has 87706 sentences, in both english and American Sign Language, glossed.
We added some processing compared to the original dataset: punctuation is split from the words for english (some sentences did not apply this rule).
we also assert that each word is separated from anything else, for both (e.g. 123word becomes 123 word).
We finally delete any duplicate spaces. 
"""

# TODO(aslg_dataset): BibTeX citation
_CITATION = """@INPROCEEDINGS{8336054,
author={A. {Othman} and M. {Jemni}},
booktitle={2017 6th International Conference on Information and Communication Technology and Accessibility (ICTA)},
title={An XML-gloss annotation system for sign language processing},
year={2017},
volume={},
number={},
pages={1-7},
doi={10.1109/ICTA.2017.8336054}}
"""


class AslgDataset(tfds.core.GeneratorBasedBuilder):
  """DatasetBuilder for aslg_dataset dataset."""

  VERSION = tfds.core.Version('1.0.0')
  RELEASE_NOTES = {
      '1.0.0': 'Initial release.',
  }

  def _info(self) -> tfds.core.DatasetInfo:
    """Returns the dataset metadata."""
    # TODO(aslg_dataset): Specifies the tfds.core.DatasetInfo object
    return tfds.core.DatasetInfo(
        builder=self,
        description=_DESCRIPTION,
        features=tfds.features.FeaturesDict({
            # These are the features of your dataset like images, labels ...
            'input_text': tfds.features.Text(),
            'output_text': tfds.features.Text(),
        }),
        # If there's a common (input, target) tuple from the
        # features, specify them here. They'll be used if
        # `as_supervised=True` in `builder.as_dataset`.
        supervised_keys=None,  # Set to `None` to disable
        citation=_CITATION,
    )

  def _split_generators(self, _):
    """Returns SplitGenerators."""
    # TODO(aslg_dataset): Downloads the data and defines the splits
    # path = dl_manager.download_and_extract('https://todo-data-url')

    # TODO(aslg_dataset): Returns the Dict[split names, Iterator[Key, Example]]
    return {
        # 'train': self._generate_examples(path / 'train_imgs'),
        'train': self._generate_examples()
    }

  def _generate_examples(self):
    """Yields examples.
    File encoding is utf-8-sig"""
    english = gfile.GFile('english_processed_utf8.txt', 'rb').read() ## I tried to open the file, and then use readlines, but it produces the same error
    asl = gfile.GFile('asl_processed_utf8.txt', 'rb').read() ## '_utf8' in the file name describes the same file as without, except it was saved with an utf-8 encoding instead of utf-8-sig. The exact same behaviour occurs with both files (with and without '_utf8')
    # with open('english_processed.txt', encoding='utf-8-sig') as english_f, open('asl_processed.txt', encoding='utf-8-sig') as asl_f:
    english = [eng for eng in english.split('\n') if eng]
    asl = [a for a in asl.split('\n') if a]
    for i, sentences in enumerate(zip(english, asl)):
      eng_sen, asl_sen = self._clean_sentences(*sentences)
      yield i, {
        'input_text': eng_sen.strip(),
        'output_text': asl_sen.strip()
      }

  @staticmethod
  def _clean_sentences(eng_sen, asl_sen):
    eng = eng_sen.replace("!", " ! ").replace(".", " . ").replace(",", " , ")
    eng = re.sub(r'([\-\'a-zA-ZÀ-ÖØ-öø-ÿ]+)', r' \1 ', eng)
    eng = re.sub(r' +', ' ', eng)

    asl = re.sub(r'([0-9]+(?:[.][0-9]*)?)', r' \1 ', asl_sen)
    asl = re.sub(r' +', ' ', asl)

    return eng, asl

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The directory in which everything happens has been generated using `tfds new`. The only file I modified was the one pasted before, which is the main python file. We then use `tfds build` before running the test.

**Comment by ravikyram** [comment]
@fabrien 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by fabrien** [comment]
Hey, @ravikyram! It's not online, so I don't have a link for you, unfortunately. However, I do give everything necessary to reproduce:

`tfds new aslg_dataset` in a directory

copy paste the given code in the file aslg_dataset.py
You can download the corpus files at the given link as indicated, process them with the given small python script given, and name them accordingly. You can then run

`tfds build` and finally run the python file (from the superior directory) with `python -m aslg_dataset.aslg_dataset_test.py`

If you want to, I can upload my full directory here, but I guess you are not interested in a 87000x2 sentences corpus on that issue ^^, and the only modified file from what `tfds new` gives you, is aslg_dataset.py, for which you already have the code

**Comment by yongtang** [comment]
Wondering if this is related to #33590

**Comment by huangliang0828** [comment]
The local Python files( all of them were tensorflow training model files )，reported the following error in Chinese directory path, but they were used normally in English directory/path. Python=3.9.13 or 3.9.16 Spyder=5.3.3 tensorflow=2.9.1 or 2.10.
I don't know what the problem is.
error like this ：
File D:\ProgramData\miniconda3\envs\autokeras_1\lib\site-packages\tensorflow\python\eager\execute.py:54 in quick_execute tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 205: invalid continuation byte

**Comment by tilakrayal** [comment]
@fabrien,
Could it be that you are using invalid folder names or printing non-standard symbols? A UnicodeDecodeError may indicate that some string (e.g. a filename, foldername or print statement) you are using is not a valid UTF-8 string: https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte

Thank you!

**Comment by fabrien** [comment]
Hey, this issue is almost 3 years old now, I have to admit I completely stopped working on this and python since then. To answer your question though, I believe the issue indeed is that some characters are not handled in utf-8, even if it looks like they should (in this case, the failing byte represents the "é" character, which is included in utf-8 normally). Maybe it's just the file encoding which is done differently so it can't be read in utf-8. I won't be able to test it, but looking at it from 3 years in the future, I'm wondering if the solution isn't just to use the latin-1 encoding to open the file. I feel like the code shown should work and still don't know why it didn't though.

**Comment by tilakrayal** [comment]
@fabrien,
As from the [gist](https://colab.research.google.com/gist/tilakrayal/90ed4883fdc81893d76f4441157578f9/untitled1559.ipynb) the code which was mentioned executed without any issues/errors with the latest version of tensorflow and also I have tried on the various environments also the output is similar with the gist provided. Thank you!
