### ISSUE TITLE
bazel coverage only generates empty coverage report

### ISSUE THREAD

**Issue by roguedream** [tensorflow/tensorflow#46477]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 2.1.0
- Python version: 3.6.9
- Installed using : source
- Bazel version (if compiling from source): 0.29.0
- GCC/Compiler version (if compiling from source): gcc 7.5.0
- CUDA/cuDNN version: N
- GPU model and memory: RTX 2080 super

**Describe the problem**
The following command is used to test and get test coverage.
```
bazel coverage -s --instrument_test_targets --coverage_report_generator=@bazel_tools//tools/test:coverage_report_generator --coverage_support=@bazel_tools//tools/test:coverage_support --collect_code_coverage --jobs 5 //tensorflow
```

But I only get `~/tensorflow-2.1.0/bazel-testlogs/tensorflow/tensorflow/baseline_coverage.dat` and the data is only filenames and online `end_of_record`.

I am not sure if it is caused by the wrong command.

**Comment by amahendrakar** [comment]
@roguedream,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by roguedream** [comment]
> @roguedream,
> Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

I tried v2.4 with bazel 3.1.0 using command 
```
sudo bazel coverage -s --instrument_test_targets --experimental_cc_coverage --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main --combined_report=lcov --jobs 4 //tensorflow/core:all
```
I got `_coverage` folder in the `bazel-out` folder. But there is only a `lcov_files.tmp` this folder and it points to many coverage.dat files. But those coverage.dat files are still empty.
Is the command wrong?

**Comment by amahendrakar** [comment]
@roguedream,
Could you please provide the exact sequence of commands / steps that you executed before running into the issue. Thanks!

**Comment by StefanusAgus** [comment]
Hello, I have the same problem on the latest stable version of tensorflow. I wonder if there is any solution for this? Thank you.

**Comment by minhdang241** [comment]
I also have the same problem

**Comment by LiewenHuke** [comment]
I used "bazel coverage --combined_report=lcov  ..." in my testing root-dir. Same issue in lcov_files.tmp, every record point at an empty file.
