### ISSUE TITLE
Please Help Me To Sort This Out 

### ISSUE THREAD

**Issue by seviksindia** [tensorflow/tensorflow#46489]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:2
- Python version:3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:6.5
- GPU model and memory:geforce 210 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by chazuttu** [comment]
@seviksindia please describe the problem properly

**Comment by ymodak** [comment]
duplicate https://github.com/tensorflow/tensorflow/issues/46490#issuecomment-761871554
