### ISSUE TITLE
[TFLite] OpenCL strange performance compared to OpenGL

### ISSUE THREAD

**Issue by natario1** [tensorflow/tensorflow#46486]
I've run some tests and I keep seeing the behavior below, where CPU execution and OpenGL execution match all expectations (histogram shape, speed), but OpenCL performs unpredictably. The graph refers to tests run on Pixel 4 with an extremely simple model (400x400x1 input => 2D mean => 1x1 output), collecting about 3k samples for each plot.

![cl_plot](https://user-images.githubusercontent.com/15526561/104822300-c370cc00-5841-11eb-90f1-d4bdc14a8802.png)

- The first plot `cpu` is for CPU execution (no delegate). Execution takes 10ms on average. 
- The second `ssbo_mono_gl` is for GPU execution with OpenGL. Input is passed as SSBO with the correct dimensions (400x400x1). Shape is nice and it's faster than CPU, as one would expect.
- The third `ssbo_mono_cl` is for GPU execution with OpenCL. Input is passed as SSBO with the correct dimensions (400x400x1). I can see several issues:
  - On average, 2.5 times slower than OpenGL.
  - The results cluster around two speed levels. 
  
  I'm not concerned with OpenCL slower than OpenGL in theory (might be due to SSBO input) **but** histogram shows that it's averagely slower just because of the right cluster. The left cluster performs just fine, actually better than GL. This looks suspicious to me.

- Things get even weirder in the fourth plot `ssbo_dhwc4_cl` where I pass a dhwc4 (400x400x4) SSBO to the delegate. What I see:
  - OpenCL performance gets about 4 times slower, which seems to suggest that most time is spent on conversions? The model is always the same (single channel).
  - The majority of samples now belongs to the fast cluster! Why would this shift happen?
  
I'd like to ask two questions,
1. Is there a known explanation for this (especially the two clusters, and the DHWC4 shift)? Maybe the SSBO to OpenCL conversion should be investigated.
2. If it's not tensorflow's fault but rather weird behavior from the GPU driver, are we really sure that OpenCL should be the preferred implementation in the V2 delegate? With this data in hand I would choose OpenGL hands down, yet TF prefers OpenCL when available. I know I can use `TFLITE_GPU_EXPERIMENTAL_FLAGS_GL_ONLY`, I'm just questioning the default.

**Comment by teijeong** [comment]
Hi @impjdi , could you give some insights? Thanks!

**Comment by impjdi** [comment]
Without looking at the model, it's hard to tell why.  It's possible that it's taking all the time in conversions + gpu waits.  If you want to dig deeper, you can use `//tensorflow/lite/delegates/gpu/cl/testing/run_performance_profiling.sh` to help diagnose the issue.  It's not going to solve anything, but you could pinpoint what is taking so long / where.

**Comment by natario1** [comment]
I described the model above, it has a single node which is a 2D mean. [simple_model_400x400x1.tflite.zip](https://github.com/tensorflow/tensorflow/files/5995424/simple_model_400x400x1.tflite.zip)

I used this model so that the profiling above would benchmark mostly i/o conversions. I run the CL profiler but it's not telling me much. My issue is not poor CL performance per se but rather
- weird CL behavior, clustering around two performance points
- performance being sometimes much worse than GL, despite CL being the default

Also my tests were focused on SSBO input which I don't think that `run_performance_profiling.sh` is using. 
Here is the output on Pixel 4 @impjdi 

```
INFO: Initialized TensorFlow Lite runtime.
Precision: CalculationsPrecision::F16
Storage type: TensorStorageType::TEXTURE_ARRAY
Per kernel timing(1 kernels):
  mean 0 - 0.219904ms
--------------------
Accumulated time per operation type:
  mean - 0.219904ms
--------------------
Ideal total time: 0.219904
--------------------

Memory for intermediate tensors - 0.305178 MB
Total time - 0.228136ms
Total time - 0.228282ms
Total time - 0.227741ms
Total time - 0.228017ms
Total time - 0.226982ms
Total time - 0.228176ms
Total time - 0.226889ms
Total time - 0.227861ms
Total time - 0.228688ms
Total time - 0.228273ms

```

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
