### ISSUE TITLE
TypeError: '<' not supported between instances of 'function' and 'str'

### ISSUE THREAD

**Issue by divyanshjoshi** [tensorflow/tensorflow#46484]
<em>Please make sure that this is a bug. As per our[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),we only address code/doc bugs, performance issues, feature requests andbuild/installation issues on GitHub. tag:bug_template</em>

**System information**
- I'm training the model on google collaboratory

**Describe the current behavior**
I've trained and saved my model, on importing the model it gives this error on model evaluation, but model.predict() works perfectly

**Testing Code**
`model_path = "/content/drive/MyDrive/Train Data/Models/text_block_model_new_batch.h5"`
`model = tf.keras.models.load_model(model1_path,custom_objects={'dice_coef':dice_coef,'dice_coef_loss':dice_coef_loss})`
`results = model.evaluate(X_test,Y_test)`

![Screenshot (40)](https://user-images.githubusercontent.com/54077406/104814641-16448680-5836-11eb-8057-9bcd29159d9f.png)

**Comment by amahendrakar** [comment]
@divyanshjoshi,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Alternatively, you can share the link of the Colab notebook you are running. 

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/46249#issuecomment-756605409) from a similar issue and let us know if it helps. Thanks!

**Comment by divyanshjoshi** [comment]
Currently I'm working on tensorflow 2.4.0
I can't upload my colab notebook publicly, so is there any other way I can reach you? 
Although I can upload the training portion of my notebook, if that's possible, Thanks

**Comment by ymodak** [comment]
Check if you have any missing values in your data and remove them if any.

**Comment by chazuttu** [comment]
TypeError: '<' not supported between instances of 'function' and 'str' arises because of some issue in your data

**Comment by divyanshjoshi** [comment]
> TypeError: '<' not supported between instances of 'function' and 'str' arises because of some issue in your data

I don't think so ,cause the model is successful in making predictions and the test set is kinda from the same distribution from the train

**Comment by divyanshjoshi** [comment]
> Check if you have any missing values in your data and remove them if any.

The set set seems fine and even checked for any null values, still didn't solve the problem.

**Comment by divyanshjoshi** [comment]
@amahendrakar..... Hopefully the link you mentioned is gonna help me, I'll let update you soon

**Comment by amahendrakar** [comment]
> Although I can upload the training portion of my notebook, if that's possible, Thanks

Without a reproducible code it would be difficult for us to pinpoint the issue. Hence, could you please share a minimal code snippet with dummy dataset to reproduce the error? Thanks!

**Comment by divyanshjoshi** [comment]
Okay, Sure
**Here you go!**

I basically used a custom loss function
```
def dice_coef(y_true,y_pred,epsilon=0.001):
  y_true_sum  = K.sum(y_true)
  y_pred_sum  = K.sum(y_pred)
  intersection = K.sum(y_true * y_pred)
  return ((2 * intersection + epsilon)/(y_true_sum + y_pred_sum + epsilon))

def dice_coef_loss(y_true,y_pred):
    return  1 - dice_coef(y_true,y_pred)
```
This is the training portion
```
model_path = os.getcwd() + "/drive/MyDrive/Train Data/Models/text_block_model_morph_1024*1024.h5"

checkpoint = tf.keras.callbacks.ModelCheckpoint(model_path,
                             monitor="val_loss",
                             mode="min",
                             save_best_only = True,
                             verbose=1)

decay_rate = learning_rate / epochs
opt = tf.keras.optimizers.Adam(lr=learning_rate, beta_1=0.9, beta_2=0.999, epsilon=None, amsgrad=False)

model.compile(optimizer=opt,loss=dice_coef_loss,metrics=[dice_coef,'accuracy'])
results_2 = model.fit(X_train, Y_train, validation_split=0.1,batch_size=batch_size, epochs=epochs,callbacks=[checkpoint])
```
Hope that's sufficient information, Thank you for responding!!

**Comment by divyanshjoshi** [comment]
I used a **standard U-Net** for my model architecture 

_This is the link to my test set_ - [https://drive.google.com/drive/folders/1tsRtFiXTSDgbtQl6yabfkBmoZ_Yfo5gl?usp=sharing](https://drive.google.com/drive/folders/1tsRtFiXTSDgbtQl6yabfkBmoZ_Yfo5gl?usp=sharing)

**Comment by ymodak** [comment]
What happens if you use built it loss functions `(binary_crossentropy/categorical_crossentropy)` here? Are you able to execute code after losing custom objects?

**Comment by divyanshjoshi** [comment]
> What happens if you use built in loss functions `(binary_crossentropy/categorical_crossentropy)` here? Are you able to execute code after losing custom objects from your code and using built in functions?

Didn't try that yet, that's a great suggestion I'll try that out and let you know!

**Comment by divyanshjoshi** [comment]
@ymodak ..... The model was able to evaluate on binary_crossentropy, so I guess there's an issue with the custom loss function

**Comment by divyanshjoshi** [comment]
@amahendrakar .......It finally worked!!, I only saved the model weights, rather than saving the whole model and then evaluated on the latest weights on a new model instance, Thank you for your help!

**Comment by zaccharieramzi** [comment]
@ymodak  is there a fix for someone who doesn't want to save the weights separately (because for example they want to also save the optimizer's state)?

**Comment by MatrixScenary** [comment]
See this: https://github.com/tensorflow/tensorflow/issues/45903#issuecomment-804973541

**Comment by teedy8023mars** [comment]
> @amahendrakar .......It finally worked!!, I only saved the model weights, rather than saving the whole model and then evaluated using the latest weights on a new model instance, Thank you for your help!
> 
> **This helped me**
> https://www.tensorflow.org/tutorials/keras/save_and_load

hey man, this saved my ass, thank you ,  I had the same issue and cannot figure out until SAW your post
