### ISSUE TITLE
InvalidArgumentError: 5 nodes in a cycle 

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorflow#46483]
Hello,
I am trying to read image data from TFRecords,parse it , decode the images and the batch it. The moment I use @tf.function for decoding the images using a dataset.map() method, I get the following error. 
Here is the code and output:

Thank in advance! 

```
class DataParser(Hyperparameters):

   
    def __init__(self): 
        self.TFRECORDS_FORMAT=Hyperparameters.TFRECORDS_FORMAT
        self.BATCH_SIZE=Hyperparameters.BATCH_SIZE
        self.HEIGHT=Hyperparameters.HEIGHT
        self.WIDTH=Hyperparameters.WIDTH
        
    def readTFRecs(self,dir_name): 
        
        TFRecFiles=tf.constant(tf.io.gfile.listdir(dir_name))
        TFRecFiles=tf.map_fn(lambda name:dir_name+'/'+name,TFRecFiles)
        TFRecDataset=tf.data.TFRecordDataset(TFRecFiles)#.batch(self.BATCH_SIZE).prefetch(1)
        self.dataset_len=tf.data.experimental.cardinality(TFRecDataset).numpy()
        Dataset = TFRecDataset.map(lambda example:tf.io.parse_example(example,self.TFRECORDS_FORMAT))
        return Dataset
    
    @tf.function
    def decode_image(self,entry):
       return tf.image.decode_image(entry['image'],channels=3) #[batch_size,h,w,3]
    
    
    @tf.function
    def makeDataset(self,TFRecDataset):
        Dataset = TFRecDataset.map(lambda entry: self.decode_image(entry))
        return iter(Dataset)



dp=DataParser()  
TFRecDataset=dp.readTFRecs('../input/cassava-tfrecords-512x512')  
Iter=dp.makeDataset(TFRecDataset)  
next(Iter)  
```

Gives the error:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-29-f39735f1a1fd> in <module>
      1 dp=DataParser()
      2 TFRecDataset=dp.readTFRecs('../input/cassava-tfrecords-512x512')
----> 3 Iter=dp.makeDataset(TFRecDataset)
      4 next(Iter)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
--> 846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    847 
    848     def fn_with_cond(*inner_args, **inner_kwds):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 5 nodes in a cycle [Op:__inference_makeDataset_2557]
```

**Comment by Saduf2019** [comment]
@AdityaKane2001 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d75d080236815637596eef74ec99d383/untitled502.ipynb). [please share all dependencies for us to replicate the issue faced]

**Comment by AdityaKane2001** [comment]
Hey,

Hyperparameters is just a config class

```
#Import required libraries
import tensorflow as tf
import os
import numpy as np
import pandas as pd
import cv2

class Hyperparameters:
    TFRECORDS_FORMAT={'image': tf.io.FixedLenFeature([], tf.string),
                      'image_name': tf.io.FixedLenFeature([], tf.string),
                      'target': tf.io.FixedLenFeature([], tf.int64)}
    BATCH_SIZE=32
    AUTOTUNE=tf.data.experimental.AUTOTUNE
    HEIGHT=224
    WIDTH=224
    WIDTH_FACTOR=0.2
    HEIGHT_FACTOR=0.2
    FILL_MODE='reflect'
    TRAINING=True

```

**Comment by Saduf2019** [comment]
@AdityaKane2001 
I ran the code shared and face a different issue, please find [gist here](https://colab.research.google.com/gist/Saduf2019/211df62123c9ff4818baab3aa43378f4/untitled504.ipynb). Unless you share all dependencies we cannot replicate the issue to analyse it.

**Comment by AdityaKane2001** [comment]
Hi,
Actually this is the notebook that I am using for a kaggle competition.
Please check out the notebook at : kaggle notebook
<https://www.kaggle.com/adityakane/tfdata-efficientnet>. Before you run the
notebook, please uncomment the @tf.function decorator in DataParser class .
Following is the change you need to do:

    #@tf.function
    def makeDataset(self,TFRecDataset):
        Dataset = TFRecDataset.map(lambda entry: self.decode_image(entry))
        #Dataset = Dataset.map(lambda
entry:(entry['image'],tf.one_hot(entry['target'],5)))
        Dataset = Dataset.shuffle(4000)
        #Dataset=Dataset.zip(TFRecDataset.map(lambda entry:entry['target']))
        Dataset = Dataset.batch(self.BATCH_SIZE).prefetch(1)
        return Dataset


                                                   ||

                                                   ||

                                                   ||

                                                   ||

                                                  \\//


      @tf.function
    def makeDataset(self,TFRecDataset):
        Dataset = TFRecDataset.map(lambda entry: self.decode_image(entry))
        #Dataset = Dataset.map(lambda
entry:(entry['image'],tf.one_hot(entry['target'],5)))
        Dataset = Dataset.shuffle(4000)
        #Dataset=Dataset.zip(TFRecDataset.map(lambda entry:entry['target']))
        Dataset = Dataset.batch(self.BATCH_SIZE).prefetch(1)
        return Dataset




Thanks and Regards,
Aditya Kane

**Comment by AdityaKane2001** [comment]
After making the change in the last mail, please run the following code in
a new cell:


dp=DataParser()
TFRecDataset=dp.readTFRecs('../input/cassava-tfrecords-512x512')
Dataset=dp.makeDataset(TFRecDataset)
#Dataset = Dataset.shuffle(600)
valDataset=Dataset.take(50).prefetch(dp.AUTOTUNE)
trainDataset=Dataset.skip(50).prefetch(dp.AUTOTUNE)


Thanks and Regards,
Aditya Kane

**Comment by Saduf2019** [comment]
@AdityaKane2001 
I ran the code shared as directed and do not see any errors, please fond the [gist here](https://colab.research.google.com/gist/Saduf2019/cd9ab8cae10af1e3797098c26273d6c3/untitled508.ipynb).

**Comment by AdityaKane2001** [comment]
Hello,
Please view the notebook [gist](https://colab.research.google.com/gist/AdityaKane2001/2904c6a0864ad78f226eb6824a13ec62/issue_46483.ipynb) attached herewith. The issue is replicated there.

Thanks and Regards,
Aditya Kane

**Comment by ymodak** [comment]
Closing this issue since you have found workaround. Feel free to reopen if facing further problems with latest tf version.
Thanks!

**Comment by AdityaKane2001** [comment]
Ok
