### ISSUE TITLE
Issues when Cross-building TFLite GPU Delegate and loading the built so file in Python

### ISSUE THREAD

**Issue by rose-jinyang** [tensorflow/tensorflow#46498]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS x86_64 PC
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 582c8d2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): RK3399 Ubuntu 18.04 LTS aarch64

**Describe the problem**

Host PC environment:
OS: Ubuntu 18.04 x86_64 AMD64
native gcc(g++): 7.5.0
cross-compiler aarch64-linux-gnu-gcc(aarch64-linux-gnu-g++): 8.3.0, which is download automatically by bazel when building
bazel: 3.7.2
python: virtual env python 3.7

Target Device environment:
Device: RK3399
CPU: armv8
GPU: Mali T860
OS: Ubuntu 18.04 aarch64
native gcc(g++): 7.5.0
OpenCL: 1.2

I have two issues: the first is one **when cross-building OpenCL backend TFLite GPU delegate on the host PC**; the second is **when loading the TFLite GPU delegate so file** in Python on the target device platform.

First, I could NOT build **OpenCL(v1.2) backend TFLite GPU delegate** for OpenCL version 1.2.

![image](https://user-images.githubusercontent.com/47862419/104850767-fa231100-592b-11eb-94e1-82fba7d297bb.png)

So I built **OpenCL(v2.2) backend TFLite GPU delegate**.
I tried to use the built OpenCL(v2.2) TFLite GPU delegate in Python on RK3399 aarch64 but I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/104851345-69e6cb00-592f-11eb-984c-d4bc18def731.png)

**Please provide the exact sequence of commands/steps when you ran into the problem**
I followed the following steps on my host PC.

sudo apt update
sudo apt-get install software-properties-common
sudo apt update
sudo apt install git curl
sudo apt install python3.7 python3.7-dev python3.7-venv python3.7-distutils
sudo apt install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev

cd ~
python3.7 -m venv py37
source ~/py37/bin/activate
pip install cython
pip install wheel
pip install numpy

git clone -b r2.4 https://github.com/tensorflow/tensorflow.git tensorflow_r2.4
cd tensorflow_r2.4
./configure

![image](https://user-images.githubusercontent.com/47862419/104850283-2be6a880-5929-11eb-9b09-7572ddb59263.png)

For OpenCL 1.2:
bazel build -s -c opt --config=elinux_aarch64 --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" --copt="-DCL_DELEGATE_NO_GL" --copt="-DCL_TARGET_OPENCL_VERSION=120" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so

But this failed as the above figure.
So I built again for OpenCL 2.2
bazel build -s -c opt --config=elinux_aarch64 --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" --copt="-DCL_DELEGATE_NO_GL" --copt="-DCL_TARGET_OPENCL_VERSION=220" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
This building was successfull and I got a tflite gpu delegate so file.

I tried to load the built GPU delegate so file in Python as the following.

![image](https://user-images.githubusercontent.com/47862419/104851016-520e4780-592d-11eb-9457-b49bb752efca.png)

But I met an issue as the above figure.

What I want to know are:
1) how to build OpenCL(v1.2 rather than v2.2) backend TFLite GPU delegate so file on the host PC or the target platform
2) how to fix the issue when loading the built TFLite GPU delegate so file in Python.

**Comment by rose-jinyang** [comment]
For the second issue when loading TFLite GPU delegate, I added two functions **_tflite_plugin_create_delegate_** and  **_tflite_plugin_destroy_delegate_** so the issue disappeared.

**Comment by terryheo** [comment]
Verified the issue. I'll investigate.

**Comment by terryheo** [comment]
@rose-jinyang the OpenCL delegate code is written in 2.2 API. So you can't build it with "-DCL_TARGET_OPENCL_VERSION=120".
But the generated binary can run on OpenCL 1.2 devices. Have you tried it?

**Comment by rose-jinyang** [comment]
Yes, I checked that it can run on OpenCL 1.2 devices.
Did u add tflite_plugin_create_delegate and tflite_plugin_destroy_delegate in the delegate module?

**Comment by terryheo** [comment]
No I didn't. You can send a PR for that. I can review the change.

**Comment by suyash-narain** [comment]
> Yes, I checked that it can run on OpenCL 1.2 devices.
> Did u add tflite_plugin_create_delegate and tflite_plugin_destroy_delegate in the delegate module?

Hi, Even I am trying to do the same thing, but I get the error, 'undefined symbol: tflite_plugin_create_delegate'. How did you add it in the delegate module that it disappeared for you?

**Comment by terryheo** [comment]
@suyash-narain You can refer https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/external

@rose-jinyang I'm wondering if you're going to share your change with a PR.

**Comment by suyash-narain** [comment]
@terryheo Thanks. I was trying to build the GPU delegate with opencl backend, using 
bazel build -s -c opt --config=elinux_aarch64 --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" --copt="-DCL_DELEGATE_NO_GL" --copt="-DCL_TARGET_OPENCL_VERSION=220"
to which, I get a build error: 'BUILD FAILED, 'DCL_TARGET_OPENCL_VERSION=220' no such file or directory'
I have installed the 'mesa-common-dev, libegl1-mesa-dev, libgles2-mesa-dev, ocl-icd-opencl-dev' too on my host linux machine running ubuntu 18.04.

**Comment by BenjaminWegener** [comment]
https://github.com/tensorflow/tensorflow/issues/55522

**Comment by BenjaminWegener** [comment]
@terryheo https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/9721986c8289c3fce9642526ef7bb799ade5466e
that is the needed change to export the two needed functions

**Comment by tc-wolf** [comment]
@BenjaminWegener thank you very much for the pointer to the needed linking changes and to the external delegate creation API.  Unfortunately, I think that https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/9721986c8289c3fce9642526ef7bb799ade5466e is just a stub implementation - it won't create / use the GPU delegate with that, only create the test delegate.  I was however able to get this to work by using your changes to the linker flags and implementing functions that wrapped the GPU delegate constructor / destructor:

```cpp
// added to tensorflow/lite/delegates/gpu/delegate.cc
extern "C" {

TFL_CAPI_EXPORT TfLiteDelegate* tflite_plugin_create_delegate(
    char** options_keys, char** options_values, size_t num_options,
    void (*report_error)(const char*)) {
  // Ignore passed in options, sorry.
  if (num_options > 0){
    TFLITE_LOG_PROD(tflite::TFLITE_LOG_WARNING, "TODO: Implement option-handling, USING DEFAULTS.");
  }
  
  TfLiteGpuDelegateOptionsV2 options = TfLiteGpuDelegateOptionsV2Default();
  options.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;
  options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
  options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
  options.experimental_flags = TFLITE_GPU_EXPERIMENTAL_FLAGS_ENABLE_QUANT;
  options.max_delegated_partitions = 1;
  
  return TfLiteGpuDelegateV2Create(&options);
  
}

TFL_CAPI_EXPORT void tflite_plugin_destroy_delegate(TfLiteDelegate* delegate) {
  TfLiteGpuDelegateV2Delete(delegate);
}


}
```
(A better implementation would use the passed in options, but I used defaults suitable for me).

**Comment by BenjaminWegener** [comment]
@tc-wolf thanks, will look into it. Good work!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by Imperialpiggy** [comment]
> For the second issue when loading TFLite GPU delegate, I added two functions **_tflite_plugin_create_delegate_** and **_tflite_plugin_destroy_delegate_** in the delegate module so the issue disappeared and my Python inference using OpenCL backend TFLite GPU delegate works.

Dear Jinyang, could you offer me a little help about how you did this? I got the same error: function 'tflite_plugin_destroy_delegate' not found. Thank you very much for your help.
