### ISSUE TITLE
Converted models gives wrong outputs

### ISSUE THREAD

**Issue by Roberto7766** [tensorflow/tensorflow#46495]
**System information**
Run on Colab; tensorflow-gpu==2.3.1 for the first part, then tf-nightly-gpu (after runtime restart).

**Command used to run the converter or code if you’re using the Python API**
Colab link with the project:
https://colab.research.google.com/drive/1V7fo4TgfAvMxme9AOBbdYggW-I7-tXTr?usp=sharing

**The output from the converter invocation**
On Colab, no verbose output but model.tflite is created

**Also, please include a link to the saved model or GraphDef**
Here the link of the .pb model (which was obtained using onnx_to_tensorflow):
https://drive.google.com/drive/folders/1RiwVVbzTNymzdmy_sRZxIWWSOGE3EwOx?usp=sharing

**Failure details**
I obtained a converted model.tflite file but the outputs are wrong (see Colab notebook for comparison)

**Any other info / logs**
As explained in the notebook, the tflite coinversion works with tensorflow-gpu==2.3.1 but to run the model tf-nightly-gpu is required (after runtime restart). If I do differently, Colab crashes.

**Comment by abattery** [comment]
I tried to reproduce this on tf-nightly. When loading the attached saved model, the saved model loader does not stop forever. The loading problem will report this to the TensorFlow Core team.

**Comment by ymodak** [comment]
Is this still an issue with the latest version of TensorFlow? Thanks!
