### ISSUE TITLE
(Donkey Car: Epoch failure during train command) Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized.

### ISSUE THREAD

**Issue by kelvham** [tensorflow/tensorflow#46491]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, uses Donkey Car train function.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): I am not sure, using Anaconda Prompt
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.0 (have also tried 2.3.0 and 2.3.2)
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: GTX 1080 * GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When executing the Train command, it eventually fails with error: `W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated. [[{{node PyFunc}}]]`

**Describe the expected behavior**

100 Epochs should be ran through.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

`(donkey) C:\Users\Kelvin>python C:\Users\Kelvin\mycar\train.py --tub C:\Users\Kelvin\mycar\data\ --model C:\Users\Kelvin\mycar\models\mypilot.h5`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Sorry if anything is unclear, I am fairly new to this. This is in reference to autorope/donkeycar#742 . Basically, we are trying to train a neural network and go through 100 Epochs, but run into this error. I have tried with 2.3.2 and 2.4.0 and updated Cuda 10.2 and updated my graphics drivers and have had no luck.

Here is the full log when I run into the issue:

[console with 2.4.0.txt](https://github.com/tensorflow/tensorflow/files/5825583/console.with.2.4.0.txt)

**Comment by ravikyram** [comment]
@kelvham 

Will it be possible to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by kelvham** [comment]
@ravikyram I am not sure exactly what code you'll need, as I was following a step-by-step guide that clones another github repo, the important pages of the instructions are [http://docs.donkeycar.com/guide/host_pc/setup_windows/](url) and [http://docs.donkeycar.com/guide/train_autopilot/](url) .

**Comment by ravikyram** [comment]
@kelvham 

TensorFlow v2.4 is built and tested against CUDA 11.0 (not 11.1) and cuDNN 8

Could you please check if you are facing the same issue with TF v2.4, CUDA 11.0 and cuDNN 8.Thanks!

**Comment by kelvham** [comment]
@ravikyram it failed instantly with that setup you outlined

[TF 2.4, CUDA 11.0, cuDNN 8.txt](https://github.com/tensorflow/tensorflow/files/5836580/TF.2.4.CUDA.11.0.cuDNN.8.txt)

**Comment by mohantym** [comment]
Hi @kelvham ! I checked the log in above text file.  Your device does not seem to comply AVX instructions which might be causing OOM in first case.  Please refer these threads to  build Tensorflow in your device from source . You can also constrain [memory growth](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) using to avoid OOM issue. Attaching relevant threads for reference .Ref [1](https://stackoverflow.com/questions/59265920/this-tensorflow-binary-is-optimized-with-intelr-mkl-dnn-to-use-the-following-c), [2](https://technofob.com/2019/06/14/how-to-compile-tensorflow-2-0-with-avx2-fma-instructions-on-mac/), 3 Thanks!

**Comment by kelvham** [comment]
@mohantym Thank you for the reply, as you can see this thread is from over a year ago and I have since disassembled my bot. If I ever pursue the project again I will keep this in mind! 

Thanks again!!

**Comment by mohantym** [comment]
Ok @kelvham ! Closing this issue for now. Feel free to re-open if you need further assistance . Thank you!
