### ISSUE TITLE
TfLite converter crashes when quantization is enabled

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#46499]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A

I have TF model in saved_model format. When converting to TFlite without quantization, everything works and I'm able to run inference, no problem. When converting using full integer quantization with a representative dataset, I get the following exception:

Traceback (most recent call last):
  File "C:/REPOSITORIES/PoolNet2TFv2/tfliteInf.py", line 93, in <module>
    quantize("poolnet_640_tf")
  File "C:/REPOSITORIES/PoolNet2TFv2/tfliteInf.py", line 35, in quantize
    quant_model = converter.convert()
  File "C:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "C:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\lite.py", line 899, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "C:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "C:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\lite.py", line 450, in _calibrate_quantize_model
    return calibrate_quantize.calibrate_and_quantize(
  File "C:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 95, in calibrate_and_quantize
    return self._calibrator.QuantizeModel(
RuntimeError: Quantization not yet supported for op:

see [here](https://drive.google.com/file/d/19D3BuJSEXHsM0eH0L1Cad3gX-9JkkXYX/view?usp=sharing) a zip file containing the TF model (poolnet_640_tf), a folder with 3 images for the representative dataset (norm_images) and quantize.py, my conversion code. 

Thank you

**Comment by abattery** [comment]
@davrim @teijeong @liufengdb Could you take a look at this?

**Comment by amahendrakar** [comment]
@yakovdan,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/04fff092e402aab660fec5c2169c457e/46499-2-3.ipynb) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/a7e65574fb185f0b05dbcfa38e46e491/46499.ipynb). 

However, I did not face any errors and was able to convert the model to `.tflite` with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/2f27821ddb635d90702dadc3e5ab4b82/46499-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by yakovdan** [comment]
This works for me as well with the latest TF-nightly. However, inference is now broken. See [here](https://drive.google.com/file/d/17lLtNZyJOCD8UCy4Bf-nAXB2gyuCs0IZ/view?usp=sharing) for code, model and input image. 

I get the following exception:

Traceback (most recent call last):
  File "infere.py", line 56, in <module>
    result = run_tflite_model(img,sys.argv[1]+".tflite").astype(np.uint8)[0,0,:,:]
  File "infere.py", line 34, in run_tflite_model
    interpreter.allocate_tensors()
  File "c:\REPOSITORIES\PoolNet2TFv2\venv38local\lib\site-packages\tensorflow\lite\python\interpreter.py", line 335, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 6 (PADV2) failed to prepare.

**Comment by MeghnaNatraj** [comment]
In the folder [here](https://drive.google.com/file/d/17lLtNZyJOCD8UCy4Bf-nAXB2gyuCs0IZ/view?usp=sharing), I've downloaded the model 'poolnet_quant.tflite' and visualized it in [netron](https://lutzroeder.github.io/netron/). (refer to the image below)

@daverim any idea why the node "PadV2/constant_values;StatefulPartitionedCall/PadV2/constant_values" still remains `float32` even though we have applied full integer quantization? 

Here's a [gist for reference](https://colab.research.google.com/gist/MeghnaNatraj/6471fa4e322dfd546a321b3f62dcccc6/46499-tf-nightly.ipynb) for model conversion and inference. The model converts successfully but when running inference, the code fails when we allocate tensors `interpreter.allocate_tensors()` which fails at [this line](https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/lite/kernels/pad.cc#L116-L119) where you can see that if PADV2 op's "constant_values" attribute is defined (as it is in this model), it is expected to be `int8` but instead it is `float32`. (refer to the logs below)

```
interpreter.allocate_tensors()
...
...
Traceback (most recent call last):...
...
RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 6 (PADV2) failed to prepare.
```

![Screen Shot 2021-01-20 at 3 07 54 PM](https://user-images.githubusercontent.com/8790823/105156799-50fa3780-5b32-11eb-9360-3830c7f941fb.png)

**Comment by yakovdan** [comment]
Hi, are there any updates on this?

**Comment by yakovdan** [comment]
Are there any news on this? 
@MeghnaNatraj , @daverim

**Comment by MeghnaNatraj** [comment]
@yakovdan we're currently looking into this issue and we'll let you know once we have an update.

**Comment by yakovdan** [comment]
Hi,
@MeghnaNatraj , it has been three weeks. Are there any updates on this or some plan to work on this?

thank you,

**Comment by teijeong** [comment]
Hi @yakovdan,

Apologies for late update. With tf-nightly, you can specify `converter.experimental_new_quantizer = True` to enable new MLIR quantizer. That one quantized the constant padding correctly.

However, as the constant value is really large, it will make all values after PadV2 op around zero. This is because the padding and input of PadV2 op should share the same scale. Rather than setting it to -FLT_MAX, consider giving it some reasonable value. It depends but if the dimensions can vary a bit, MaxPool2D with same padding would give similar result, too.

**Comment by yakovdan** [comment]
Thank you for solving this. Can you explain why this large scale value is selected and how would I choose something more reasonable? 
I've noticed that most scale values are in the range [0,1.1] so I chose 0.5 as a test and I still got all zeros.

**Comment by teijeong** [comment]
> so I chose 0.5 as a test and I still got all zeros.

Can you elaborate what have you observed? Did you manually modified the scale for PadV2 op? you might also want to modify zero point, too.

From the [quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec), the scale is determined by `(max - min) / quant_range` where `quant_range = 255` for int8 quantization. So when the range gets large like (1, -1000000000), scale becomes near zero, and zero point would be at 127 or so. The minimum value will be quantized to -128, but any meaningful value will likely be quantized to 127, and in turn which becomes zero.

How do you define your pad op in the original graph? you can assign more reasonable lower bound to the padded value for the quantization to work.
