### ISSUE TITLE
Can I use cmdline option `--allow_nudging_weights_to_use_fast_gemm_kernel` via python API?

### ISSUE THREAD

**Issue by dayo09** [tensorflow/tensorflow#46503]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source from git
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**

```
// input, output and weight settings above..
converter = tf.lite.TFLiteConverter.from_session(sess, input_tensors, output_tensors)
...
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
2021-01-05 08:02:27.757106: F tensorflow/lite/toco/graph_transformations/ensure_uint8_weights_safe_for_fast_int8_kernels.cc:190] Bad value for Conv2D_4/filter at index 134, previous bad value at index 132, distance=2, kMinDistanceBetweenBadValues=16. Consider passing --allow_nudging_weights_to_use_fast_gemm_kernel if you don't care about accuracy.
Fatal Python error: Aborted
```

**Failure details**
- We randomly generate Fully Connected weights and convert the tf session to tflite using `toco` - python API. It seems that `toco` doesn't allow a certain type of weights with some zero values in the vicinity to other zero values.
- The console output says I need to pass `--allow_nudging_weights_to_use_fast_gemm_kernel`, which is only useful for the command line. I cannot find a way to pass it via Python API.

Is there any way that I can pass the `--allow_nudging_weights_to_use_fast_gemm_kernel` option via Python API?

**Comment by abattery** [comment]
The TOCO converter is deprecated. Please use MLIR converter instead. If you have any issues related to MLIR converter, please upload the problem in here.

**Comment by dayo09** [comment]
Thank you for the answer.
