### ISSUE TITLE
Could not create TensorFlow Graph: Not found: ~/graphs/inception/tensorflow_inception_graph.pb

### ISSUE THREAD

**Issue by tusharsoni08** [tensorflow/tensorflow#4650]
### Environment info
Operating System: Ubuntu 14.04

**URL:** https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#building-on-linux

I'm following the "Building on Linux", however all commands run fine, but when I've run this following command
`tensorflow/contrib/makefile/gen/bin/benchmark \
 --graph=~/graphs/inception/tensorflow_inception_graph.pb`

**Output** on terminal is as following:

`I tensorflow/tools/benchmark/benchmark_model.cc:202] Graph: [~/graphs/inception/tensorflow_inception_graph.pb]
 I tensorflow/tools/benchmark/benchmark_model.cc:203] Input layer: [input:0]
 I tensorflow/tools/benchmark/benchmark_model.cc:204] Input shape: [1,224,224,3]
 I tensorflow/tools/benchmark/benchmark_model.cc:205] Input type: [float]
 I tensorflow/tools/benchmark/benchmark_model.cc:206] Output layer: [output:0]
 I tensorflow/tools/benchmark/benchmark_model.cc:207] Num runs: [50]
 I tensorflow/tools/benchmark/benchmark_model.cc:208] Inter-run delay (seconds): [-1.0]
 I tensorflow/tools/benchmark/benchmark_model.cc:209] Num threads: [-1]
 I tensorflow/tools/benchmark/benchmark_model.cc:210] Benchmark name: []
 I tensorflow/tools/benchmark/benchmark_model.cc:211] Output prefix: []
 I tensorflow/tools/benchmark/benchmark_model.cc:212] Show sizes: [0]
 I tensorflow/tools/benchmark/benchmark_model.cc:51] Loading TensorFlow.
 I tensorflow/tools/benchmark/benchmark_model.cc:58] Got config, 0 devices
 E tensorflow/tools/benchmark/benchmark_model.cc:64] Could not create TensorFlow Graph: Not found: ~/graphs/inception/tensorflow_inception_graph.pb`

Why at last TensorFlow Graph is not created or found at ~/graphs/inception/tensorflow_inception_graph.pb even that file is there.

**Comment by arundasan91** [comment]
Hello, 

You have to download the graph and label files as a zip file from (here)[https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip] and extract the contents to `~/graphs/inception/` folder since you are using the `--graph` flag as `--graph=~/graphs/inception/tensorflow_inception_graph.pb`.

**Comment by concretevitamin** [comment]
Try to do an `ls -l  ~/graphs/inception/tensorflow_inception_graph.pb` to see if the file is indeed there.

If so and the error still persists, try to expand "~" to the absolute path when launching the program.

Feel free to reopen if there's still issues.

**Comment by tusharsoni08** [comment]
@concretevitamin I've tried `ls -l ~/graphs/inception/tensorflow_inception_graph.pb` and found it there 
`-rw-r----- 1 tushar tushar 53884595 Nov 18  2015 /home/tushar/graphs/inception/tensorflow_inception_graph.pb`

even I can see that file via clicking on that same folder path, but error is same.

**Comment by tusharsoni08** [comment]
@concretevitamin I've found it working when I've copy that graph folder to the same level at tensorflow's folder. But it was not working when my tensorflow folder on Desktop and graph folder on my home folder, idk why? but by the way now it's work!

**Comment by lizeyu4444** [comment]
@tusharsoni08 thanks! works for me.
