### ISSUE TITLE
python3 pip Install Error: No matching distribution found for tensorflow==2.2.0

### ISSUE THREAD

**Issue by hannesa2** [tensorflow/tensorflow#46506]
I have macOS Big Sur on a Apple Silicon M1 and I'm unable to install Tensorflow in python3.
I removed xcode python3 and installed brew arm64 python3 (x86 python3 doesn't work as well)

(This is  a follow up of closed https://github.com/tensorflow/tensorflow/issues/39130)

I checked successful 64 bis version 
`python3 -c "import sys; print(sys.version)" or python -c "import struct; print(struct.calcsize('P')*8)"`

> 3.8.7 (default, Dec 30 2020, 02:09:32) 
> [Clang 12.0.0 (clang-1200.0.32.28)]

<img width="606" alt="image" src="https://user-images.githubusercontent.com/3314607/104881650-f6aa7c80-5961-11eb-8cbb-6128190a0a3a.png">

Can this work anyhow, or who knows, how to make this work ?

**Comment by Saduf2019** [comment]
@hannesa2 
Please ensure you have 1) pip version >19.0 [as it is a tensorFlow 2 package requirement ]. Could you please upgrade pip using the below command and let us know if it works.

```pip install --upgrade pip.```
2) and  could you please check if you are using the 64 bit version of Python and you meet all the requirements in [this link](https://github.com/tensorflow/tensorflow/issues/42367#issuecomment-674531556)

3)also check similar issues at #45360, #46377

For more information please check this [TensorFlow guide.](https://www.tensorflow.org/install#download-a-package)

**Comment by hannesa2** [comment]
> Please ensure you have 1) pip version >19.0 [as it is a tensorFlow 2 package requirement ]. Could you please upgrade pip using the below command and let us know if it works.
> `pip install --upgrade pip.`

It's already fulfilled

```
pip install --upgrade pip
Requirement already satisfied: pip in /Users/hannes/.local/share/virtualenvs/ML-jdJEXb4p/lib/python3.8/site-packages (20.3.3)
```

> 2) and could you please check if you are using the 64 bit version of Python and you meet all the requirements in [this link](https://github.com/tensorflow/tensorflow/issues/42367#issuecomment-674531556)

It's already fulfilled

`python3 -c "import sys; print(sys.version)" or python -c "import struct; print(struct.calcsize('P')*8)"`
`3.8.7 (default, Dec 30 2020, 02:09:32) [Clang 12.0.0 (clang-1200.0.32.28)]`
 
> 3)also check similar issues at #45360, #46377

They are Linux related, I use macOS Big Sur Apple Silicon M1

> For more information please check this [TensorFlow guide.](https://www.tensorflow.org/install#download-a-package)

After stuck on this guide, I wrote this issue

**Comment by Saduf2019** [comment]
@hannesa2 
please upgrade to tf 2.4 as you are using python 3.8 as mentioned in the issues shared.

**Comment by daftano** [comment]
for M1 you might want to use the Apple at fork https://github.com/apple/tensorflow_macos
