### ISSUE TITLE
Instead of x2 variable name should be x0

### ISSUE THREAD

**Issue by raushan291** [tensorflow/tensorflow#46507]
https://www.tensorflow.org/guide/autodiff
Instead of x2 variable name should be x0 in last line

x0 = tf.Variable(3.0)
x1 = tf.Variable(0.0)

with tf.GradientTape() as tape:
  // Update x1 = x1 + x0.
  x1.assign_add(x0)
  // The tape starts recording from x1.
  y = x1**2   # y = (x1 + x0)**2

// This doesn't work.
print(tape.gradient(y, x0))   // dy/dx0 = 2*(x1 + x2)[](url)

**Comment by amahendrakar** [comment]
@raushan291,
Thank you for reporting the issue. Would you be interested in submitting a PR for this?

**Comment by amahendrakar** [comment]
@raushan291,
The issue was fixed by [PR #1794](https://github.com/tensorflow/docs/pull/1794) and the changes are reflected in the [guide](https://www.tensorflow.org/guide/autodiff#4_took_gradients_through_a_stateful_object) as well. 

Closing this issue as it is fixed. Thanks!
