### ISSUE TITLE
Sagemaker endpoint serving doesnt work for multiple timestep `and` multiple inputs (mulit input-output LSTM)

### ISSUE THREAD

**Issue by abdulbasitds** [tensorflow/tensorflow#46501]
Update: Minimum Reproducible code
https://colab.research.google.com/drive/1RJ2ou705xfrqjeFGImvMk02lTxfFPZek?usp=sharing

I have a LSTM network that has 3 inputs and 3 outputs(built with [functional api][1] in Tf.keras) , that I am trying to deploy as sagemaker endpoint. I have input shape of (None,10,1) for each input/feature, which means 10 timesteps.(I later concatenate the embeddings, but its irrelevant here) 

Everything works fine on training time on sagemaker training jobs as well and training completes and artifacts are made successfully. But at time of invocation, endpoint is not working to predict `1 example, having 10 timesteps with 3 inputs` , I have tried multiple things but cant provide three inputs for prediction(input_1,input_2,input_1).

As I said that each input has 10 timesteps, so have shape (10,1). Endpoint only returns the output if I format my payload as below, but by doing so, it treats each time-step as separate example/instance and return 10 predictions for each output

    {'inputs':{
               'input_1': [[0], [0], [0], [0], [2], [12], [11], [7], [7], [2]],
               'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
               'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]}
              } # gives len(pred['output_1"])) == 10

This is expected as it consider this request as 10 examples, but in my case it is one example with 10-timesteps for each feature (1,10,1). So I tried different things from the [documentation][2]. Like using instances.

    {'instances': [
                    {
                          'input_1': [[0],[0], [0],[0],[2],[12],[11], [7], [7], [2]],
                          'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
                          'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]
                    }
                  ]
    }

But it gives this error.

>  transpose expects a vector of size 4. But input(1) is a vector of
> size 3\\n\\t [[{{node transpose_1}}]]\\n\\t
> [[functional_1/lstm/PartitionedCall]]\\n\\t
> [[StatefulPartitionedCall/StatefulPartitionedCall]]\"\n}"}"

Document also gives example and says

> for models with multiple named inputs, just include all the keys in the input dict

but when I use this, I get error saying `Missing 'inputs' or 'instances' key\"\n}"`

    {'input_1': [[0], [0], [0], [0], [2], [12], [11], [7], [7], [2]],
     'input_2': [[0], [0], [0], [0], [30], [21], [2], [15], [27], [30]],
     'input_3': [[0], [0], [0], [0], [6], [2], [3], [13], [15], [6]]}

My invocation code is below.

    import boto3
    import json
    
    sm = boto3.client('sagemaker-runtime')    
    endpoint_name = "tensorflow--------------------4"
    response = sm.invoke_endpoint(EndpointName=endpoint_name, 
                                  Body=json.dumps(payload),
                                  ContentType='application/json')

I am not sure how to solve this issue, looking forward for help

  [1]: https://keras.io/guides/functional_api/
  [2]: https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/deploying_tensorflow_serving.html

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Sagemaker and Ubuntu 20
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7

**Standalone code to reproduce the issue**

I am not sure about the standalone code as sagemaker endpoint is confidential, and what should I share for this, i would be thankful for the suggestion on this too.

**Comment by ravikyram** [comment]
@abdulbasitds 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by abdulbasitds** [comment]
@ravikyram  I am not sure how to provide TF serving code, but I have tried to reproduce the problem with minimum code possible here:

https://colab.research.google.com/drive/1RJ2ou705xfrqjeFGImvMk02lTxfFPZek?usp=sharing

**Comment by ravikyram** [comment]
@abdulbasitds 

This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here](https://github.com/tensorflow/serving/issues/new). Thanks!

**Comment by abdulbasitds** [comment]
Have made this issue on this repo, thanks for letting me know
