### ISSUE TITLE
Tensorflow 2.4 about 10% slower than 2.3 for training RNN

### ISSUE THREAD

**Issue by hunse** [tensorflow/tensorflow#46515]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): difference between 2.3 and 2.4
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

In TensorFlow 2.4, a basic RNN model runs about 10% slower than the same model in TensorFlow 2.3. This appears on both the CPU and GPU. I've created Colab notebooks to demonstrate the issue.

The step time reported by the progress bar also appears longer (and when I did some of my own timing, I also saw the step as longer), so I don't think it has to do with callbacks or any sort of overhead outside the step function.

**Describe the expected behavior**

I would expect them to be the same, if not better in 2.4 (since it has newer CUDA, etc.).

I know that TensorFlow 2.4 no longer has XLA enabled by default. I tried enabling it on my local machine, and found that it didn't help (in fact it made things slower in TF 2.4). Furthermore, if I enable it on Colab with `os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=2"` I see slower speeds on GPU for both 2.3 and 2.4. So I don't think that's the problem. (Also, the fact that there's a slowdown on CPU suggests it's not an XLA thing.)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

TF 2.3: https://colab.research.google.com/drive/1xnfP17Bzan7-ICI_JtMfiEdTvgwrLoEz?usp=sharing
TF 2.4: https://colab.research.google.com/drive/17rccQnDvLr4mAiGmAoJyK7t0hlrEpBoV?usp=sharing

**Comment by hunse** [comment]
I also did some similar experiments on a CNN, and found that there is also a slowdown there, though it seems less significant (only about 5% instead of 10%):

TF 2.3: https://colab.research.google.com/drive/10WcsVCkyxRrrclpmPWSaWAI8UslZAR_Q?usp=sharing
TF 2.4: https://colab.research.google.com/drive/1dolfWxeq_PV3UGvTFMo6E9sC1doeZENv?usp=sharing

**Comment by hunse** [comment]
Doing some profiling on a related model (one which also showed a slowdown in TF 2.3), I noticed that while the "Device compute time" has stayed about the same from 2.2 to 2.3 to 2.4 (if not decreased slightly), the "Kernel launch time" has increased (for that model, from 0.6 to 1.7 to 2.8 ms per step). Is there some reason the kernel launch time would be so much higher in 2.3 vs 2.2, and then higher again in 2.4?

I should also note that with the original SimpleRNN model I posted above, if I scale things up (using `input_d=256` and `units=1024`), then I see similar performance between 2.3 and 2.4. So it seems to be related to the amount of work each kernel is performing (could be a longer kernel launch time, could be something else).

On the one hand, if there was a conscious decision made to trade off faster computation for longer kernel launch times (and thus improve performance on models that have fewer kernels doing more work, but degrade performance on models with many smaller kernels), I understand why this trade-off would make sense. On the other hand, there are definitely still many cases (even large models) that for one reason or another use smaller kernels.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Code runs a bit slower on TF v2.4 when compared with TF v2.3. 

Whereas with TF-nightly, Colab doesn't detect the GPU. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9e761711f1354daca7af3647f5a89e7b/46515.ipynb). Thanks!

**Comment by MathiasDL** [comment]
I am also experiencing slowdown when upgrading from TF **2.3.1** to **2.4.1**. Almost all compiled GPU ops are between 5 and 15% slower. A notable outlier is `clip_by_value`, which is more than 6x slower in my case.

**Comment by qlzh727** [comment]
Adding @yhliang2018 and @tomerk since this is more a like overall performance issue rather than just RNN issue.

**Comment by tomerk** [comment]
Hi @hunse do you have a link to your profiling? Especially where it notes the change in kernel launch time)

**Comment by tomerk** [comment]
(And ideally traces of before & after as well)

**Comment by hunse** [comment]
Here's [the profiling where I saw an increase in kernel launch time](https://drive.google.com/file/d/1XJ_TOnqUXNhbqHmWVC3Qy7cdFKFReQ6x/view?usp=sharing) (one folder is TF 2.3, the other is TF 2.4). The profiling overview reports that TF 2.4 has more ops on the host, though I wouldn't think that that would increase kernel launch time, unless it's having to wait for other ops on the host to finish before it launches the next one.

Unfortunately, that profiling is from a network in our NengoDL package, so it's not an isolated TensorFlow example (I could pass along code for it, but it wouldn't be pure TensorFlow code, so I'm not sure if that's useful). I had been trying to isolate the slowdown in the Colab notebooks above, but it appears that that's not perfect: When I run that code on my local machine, I don't see a slowdown. So I don't think that that's fully captured the problem.

**Comment by tomerk** [comment]
Hi @hunse, I've finally had a chance to dig in to your profiles. Checking the traces, t looks like your tf 2.4 runs are using 8 compute threads on the host (+ 3 tf data threads). On the other hand, your tf 2.3 runs are only using 4 or 5 compute threads on the host + 3 tf.data threads. The GPU compute itself looks like it has basically the same time breakdown across both so it *seems* like placement of ops hasn't changed at least at a quick glance, but both the host in 2.4 spends much more of its time on send/receives.

Perhaps context switching among the extra threads is slowing down your tensor data transfers? (e.g. via reducing cache coherency)
Could you try reducing the thread count in 2.4 to match what 2.3 used by default? https://www.tensorflow.org/api_docs/python/tf/config/threading

(Though off the top of my head I'm not sure what if any changes we made to the default threadpool size selection)

**Comment by hunse** [comment]
Thanks for the suggestion, @tomerk. I standardized the number of threads, which seems to have reduced the discrepancy between TF 2.3 and 2.4 in that case.

However, for that same network, when I compare between 2.2 and 2.4, I still see a significant difference. The difference is still there whether I use 4, 2, or 1 thread.

I've [attached some profiling for 1 thread](https://drive.google.com/file/d/1woH_2s8ElLuoT1qEPQ4ebPVC1PIL4HJv/view?usp=sharing) showing results from 2.2, 2.3, and 2.4. The big difference between 2.2 and 2.3 is that there's a lot more host-chip communication at the end of each step, which seems to increase the amount of time between steps.

In another model, I see more of a difference between 2.3 and 2.4 than 2.2 and 2.3 ([profiling here](https://drive.google.com/file/d/1c1R9cbBLF50w7oh2UZ3UBNoC-zX7dHf0/view?usp=sharing)). Even when accounting for the fact that TF 2.3 and 2.4 seem to take a bit longer to start up, when I measure just the time to run the core loop on the device it takes about 650 ms in 2.2, 665 ms in 2.3, and 697 ms in 2.4. Both 2.3 and 2.4 appear to have more host-device communication, but in 2.3 it's more spread-out and doesn't result in as much time between steps, whereas in 2.4 it all happens between steps. I'm not sure if this is the entire reason (or any of the reason) for the slowdown, but it is the most salient difference to me.

**Comment by tomerk** [comment]
Hmm I don't seem to be able to view these profiles. Not sure if it's an issue on my side or not. Let me try getting someone else since I'm not sure I'll have the bandwidth to dig in to this.

**Comment by annezhangxue** [comment]
I have observed the same phenomenon, with tensorflow2.0 GPU, I can run the same RNN program 300 seconds, but with tensorflow 2.4 GPU, the same code takes 30 minutes to run, such a huge difference. Therefore unfortunately I have to downgrade 2.4 to 2.0 again

**Comment by mabahgat** [comment]
another example: on Quadro RTX 6000 .. TF 2.4 ETA 7 hours for single iteration, TF 2.3 40 minutes. Same everything except for downgrading to 2.3 between the two runs.

**Comment by RuralHunter** [comment]
I have also seen the performance degradation with CPU only too. Too me the performance decreases about 15%. There is another issue with multi-thread predicating. With 2.4 and 2.5 release, I got error like this occasionally(I do pre-warm predication for the model before launching threads):
```
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1915, in predict_on_batch
    self.predict_function = self.make_predict_function()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1545, in make_predict_function
    if self.predict_function is not None:
AttributeError: 'Sequential' object has no attribute 'predict_function'
```
This doesn't happen at all with same code on release 2.3.

**Comment by sachinprasadhs** [comment]
@hunse , Could you try with the latest Tensorflow stable version 2.9.1 and let us know the outcome, Thanks!
