### ISSUE TITLE
Unable to import tensorflow in python3 after wheels install / Python3.7 / RPi 3B+ Raspbian aarch64

### ISSUE THREAD

**Issue by dev-fr** [tensorflow/tensorflow#46512]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: NO
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux raspberrypi 5.10.5-v8+ #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021 aarch64 GNU/Linux
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: Raspberry Pi 3 B+
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 2.4.0
-   **Python version**: 3.7
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**: GCC 8.3.0
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**: 
        sudo -H pip3 install tensorflow-2.4.0-cp37-cp37m-linux_aarch64.whl
        python3 -c "import tensorflow as tf"

### Describe the problem
unable to import tensorflow module from python3 (3.7) :
pi@raspberrypi:~ $ python3 -c "import tensorflow as tf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

### Source code / logs

Here is the output tf_env.txt generated by tf_env_collect.sh :

== check python ===================================================
python version: 3.7.3
python branch: 
python build version: ('default', 'Jul 25 2020 13:03:44')
python compiler version: GCC 8.3.0
python implementation: CPython

== check os platform ===============================================
os: Linux
os kernel version: #1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021
os release version: 5.10.5-v8+
os platform: Linux-5.10.5-v8+-aarch64-with-debian-10.7
linux distribution: ('debian', '10.7', '')
linux os distribution: ('debian', '10.7', '')
mac version: ('', ('', '', ''), '')
uname: uname_result(system='Linux', node='raspberrypi', release='5.10.5-v8+', version='#1392 SMP PREEMPT Sat Jan 9 18:56:30 GMT 2021', machine='aarch64', processor='')
architecture: ('64bit', 'ELF')
machine: aarch64

== are we in docker =============================================
No

== compiler =====================================================
c++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                  1.19.5
protobuf               3.0.0
tensorflow             2.4.0
tensorflow-estimator   2.4.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
      7074:	find library=libcrypt.so.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libcrypt.so.1
      7074:	
      7074:	find library=libpthread.so.0 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libpthread.so.0
      7074:	
      7074:	find library=libdl.so.2 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libdl.so.2
      7074:	
      7074:	find library=libutil.so.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libutil.so.1
      7074:	
      7074:	find library=libexpat.so.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libexpat.so.1
      7074:	
      7074:	find library=libz.so.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libz.so.1
      7074:	
      7074:	find library=libm.so.6 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libm.so.6
      7074:	
      7074:	find library=libc.so.6 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libc.so.6
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libpthread.so.0
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libc.so.6
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libm.so.6
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libz.so.1
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libexpat.so.1
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libutil.so.1
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libdl.so.2
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libcrypt.so.1
      7074:	
      7074:	
      7074:	initialize program: python3
      7074:	
      7074:	
      7074:	transferring control: python3
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_opcode.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=libffi.so.6 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libffi.so.6
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libffi.so.6
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=libstdc++.so.6 [0]; searching
      7074:	 search path=/usr/local/lib/python3.7/dist-packages/tensorflow/python/tls/aarch64:/usr/local/lib/python3.7/dist-packages/tensorflow/python/tls:/usr/local/lib/python3.7/dist-packages/tensorflow/python/aarch64:/usr/local/lib/python3.7/dist-packages/tensorflow/python:/usr/local/lib/python3.7/dist-packages/tensorflow/python/../tls/aarch64:/usr/local/lib/python3.7/dist-packages/tensorflow/python/../tls:/usr/local/lib/python3.7/dist-packages/tensorflow/python/../aarch64:/usr/local/lib/python3.7/dist-packages/tensorflow/python/..		(RUNPATH from file /usr/local/lib/python3.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/tls/aarch64/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/tls/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/aarch64/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../tls/aarch64/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../tls/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../aarch64/libstdc++.so.6
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../libstdc++.so.6
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libstdc++.so.6
      7074:	
      7074:	find library=librt.so.1 [0]; searching
      7074:	 search path=/usr/local/lib/python3.7/dist-packages/tensorflow/python:/usr/local/lib/python3.7/dist-packages/tensorflow/python/..		(RUNPATH from file /usr/local/lib/python3.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/librt.so.1
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../librt.so.1
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/librt.so.1
      7074:	
      7074:	find library=libgcc_s.so.1 [0]; searching
      7074:	 search path=/usr/local/lib/python3.7/dist-packages/tensorflow/python:/usr/local/lib/python3.7/dist-packages/tensorflow/python/..		(RUNPATH from file /usr/local/lib/python3.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/libgcc_s.so.1
      7074:	  trying file=/usr/local/lib/python3.7/dist-packages/tensorflow/python/../libgcc_s.so.1
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libgcc_s.so.1
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libgcc_s.so.1
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/librt.so.1
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libstdc++.so.6
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
      7074:	
      7074:	find library=libssl.so.1.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libssl.so.1.1
      7074:	
      7074:	find library=libcrypto.so.1.1 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libssl.so.1.1
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_hashlib.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/termios.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_csv.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=libopenblas.so.0 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libopenblas.so.0
      7074:	
      7074:	find library=libgfortran.so.5 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libgfortran.so.5
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libgfortran.so.5
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libopenblas.so.0
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_tests.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/linalg/lapack_lite.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/linalg/_umath_linalg.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=libbz2.so.1.0 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/libbz2.so.1.0
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/libbz2.so.1.0
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_bz2.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=liblzma.so.5 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/lib/aarch64-linux-gnu/liblzma.so.5
      7074:	
      7074:	
      7074:	calling init: /lib/aarch64-linux-gnu/liblzma.so.5
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_lzma.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	find library=libmpdec.so.2 [0]; searching
      7074:	 search cache=/etc/ld.so.cache
      7074:	  trying file=/usr/lib/aarch64-linux-gnu/libmpdec.so.2
      7074:	
      7074:	
      7074:	calling init: /usr/lib/aarch64-linux-gnu/libmpdec.so.2
      7074:	
      7074:	
      7074:	calling init: /usr/lib/python3.7/lib-dynload/_decimal.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/fft/_pocketfft_internal.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/mtrand.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/bit_generator.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_common.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_bounded_integers.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_mt19937.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_philox.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_pcg64.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_sfc64.cpython-37m-aarch64-linux-gnu.so
      7074:	
      7074:	
      7074:	calling init: /usr/local/lib/python3.7/dist-packages/numpy/random/_generator.cpython-37m-aarch64-linux-gnu.so
      7074:	
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 23, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB\x87\x01\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01ZSgithub.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
      7074:	
      7074:	calling fini: python3 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libcrypt.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libutil.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libexpat.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_opcode.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libffi.so.6 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libstdc++.so.6 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/librt.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_hashlib.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libssl.so.1.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libdl.so.2 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/termios.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_csv.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_tests.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/linalg/lapack_lite.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/linalg/_umath_linalg.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libopenblas.so.0 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libgfortran.so.5 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libgcc_s.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libz.so.1 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_bz2.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libbz2.so.1.0 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_lzma.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/liblzma.so.5 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/python3.7/lib-dynload/_decimal.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/lib/aarch64-linux-gnu/libmpdec.so.2 [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/fft/_pocketfft_internal.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/mtrand.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/bit_generator.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_common.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_bounded_integers.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_mt19937.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_philox.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_pcg64.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_sfc64.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /usr/local/lib/python3.7/dist-packages/numpy/random/_generator.cpython-37m-aarch64-linux-gnu.so [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libm.so.6 [0]
      7074:	
      7074:	
      7074:	calling fini: /lib/aarch64-linux-gnu/libpthread.so.0 [0]
      7074:	

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 146: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.4.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(2, 7, 16, 'final', 0)

== bazel version  ===============================================

**Comment by amahendrakar** [comment]
@dev-fr,
Could you please download the TensorFlow Python package from [this link](https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.3.0rc2-cp35-none-linux_armv6l.whl) and check if you are able to install it?

Also, please go through [this guide](https://github.com/tensorflow/build/tree/master/raspberry_pi_builds#raspberry-pi-builds) for building TensorFlow for Raspberry Pi and check if it helps. Thanks!

**Comment by dev-fr** [comment]
The wheels package link provided is for ARM 32bits v6. https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.3.0rc2-cp35-none-linux_armv6l.whl

I use aarch64, 64 Bit Raspbian OS, as mentioned in the title, and Rpi 3B+ is Armv7.

**Comment by dev-fr** [comment]
Any idea ?

**Comment by ymodak** [comment]
Can you try upgrading protobuf version and check?
See https://github.com/tensorflow/models/issues/3995#issuecomment-400183986
