### ISSUE TITLE
Apple M1 `MLC` ops not supported (e.g., tf.MLCConv2D)

### ISSUE THREAD

**Issue by mtamburro** [tensorflow/tensorflow#46513]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

macOS 11.1 (Big Sur) running on a MacBook Pro (13-inch, M1, 2020)

- TensorFlow installed from (source or binary):

Binary, from https://github.com/apple/tensorflow_macos

- TensorFlow version (or github SHA if from source):

'2.4.0-rc0'

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
```

**The output from the converter invocation**

```
/python/framework/func_graph.py:590:0: error: 'tf.MLCConv2D' op is neither a custom op nor a flex op
```

**Also, please include a link to the saved model or GraphDef**

```
There's a similar issue here:
https://github.com/apple/tensorflow_macos/issues/133
```

**Failure details**
Conversion fails, since tf.MLCConv2D is not the same as tf.Conv2D.  The same is true for other operations like tf.MLCMatMul.

**Any other info / logs**
What's the right path forward here for using Lite, and then Lite Micro on an M1 Mac?  Should conversion from MLC be supported?  I attempted to work around this using `TF_DISABLE_MLC_EAGER` as mentioned at the very bottom of https://github.com/apple/tensorflow_macos but did not understand what syntax I should be using.

**Comment by ravikyram** [comment]
@mtamburro 

Can you try with below code and see if it helps you.

```
converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite_quant_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_quant_model)
```

If you are still facing the issue please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by mtamburro** [comment]
> @mtamburro
> 
> Can you try with below code and see if it helps you.
> 
> ```
> converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)
> converter.experimental_new_converter=True
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
>                                        tf.lite.OpsSet.SELECT_TF_OPS]
> tflite_quant_model = converter.convert()
> open("converted_model.tflite", "wb").write(tflite_quant_model)
> ```
> 
> If you are still facing the issue please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

Hi @ravikyram--

No, this did not help--but would we expect lite to already have converter support for these `MLC` ops?

To reproduce the issue, you can even use the magic wand notebook found in the Tensorflow repository here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/magic_wand/train/train_magic_wand_model.ipynb

Worth noting: I have steps similar to these later in my code, where I'm quantizing the model to run on microcontrollers that support only INT-8.  All of that works fine on my identically configured Intel MacBook Pro, but fails at this earlier step on the M1 MacBook Pro.

**Comment by abattery** [comment]
The `MLC` operators are not a part of the official TensorFlow project. You need to enable them through user-defined TF Select option in the TFLite. @thaink could you help this?

**Comment by thaink** [comment]
@mtamburro Where is the definition of MLC ops?

**Comment by mtamburro** [comment]
Great question. Perhaps the authors of this blog post would know?

https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html?m=1

**Comment by mihaimaruseac** [comment]
If the TF version you use comes from the fork, the issue should be opened against the fork

**Comment by mtamburro** [comment]
Thank you, Mihai.  I'l continue following up on that fork here: https://github.com/apple/tensorflow_macos/issues/133
