### ISSUE TITLE
TensorFlow 2.4.0 core dumped issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by wyqian1027** [tensorflow/tensorflow#46516]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS
- TensorFlow installed from (source or binary): installed from pip, with this version: tensorflow-2.4.0-cp36-cp36m-manylinux2010_x86_64.whl (394.7 MB)
- TensorFlow version: 2.4.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- CUDA/cuDNN version:
- GPU model and memory: No GPU

**Describe the problem**
After installation exactly following the official guideline at: https://www.tensorflow.org/install/pip

(venv) $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Illegal instruction (core dumped)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Exactly the same as the guideline listed above, namely
$ python3 -m venv --system-site-packages ./venv
$ source ./venv/bin/activate  # sh, bash, or zsh
(venv) $ pip install --upgrade pip
(venv) $ pip install --upgrade tensorflow

**Any other info / logs**
I also did the installations with tensorflow==1.15 and tf-nightly. Both are working fine without the "core dumped" issue, however, I would really like to use the stable TensorFlow version 2.4.0.

Thank you very much for your time!

**Comment by ravikyram** [comment]
@wyqian1027 

could you please let us know the make and model of the CPU. 
Can you try installing in a fresh environment and install from scratch and see whether you are able to import Tensorflow to avoid and conflicts in dependencies. Thanks!

**Comment by lillux** [comment]
I found the same error today:
`illegal hardware instruction (core dumped)  python`

System information
- OS Platform and Distribution: `Ubuntu 20.04 LTS`
- TensorFlow installed from: `pip`, in a clean conda env
- TensorFlow version: `tensorflow-2.4.0-cp36-cp36m-manylinux2010_x86_64.whl` (394.7 MB)
- Python version: `Python 3.6.12`
- CUDA version: `cudatoolkit 10.2.89  build: hfd86e86_1`
- cuDNN version: `7.6.5`
- CPU: `Intel Xeon E5 v2680v2`
- GPU model and memory: `Nvidia GTX 1080`

I tried with Python `3.8.5`, both with `cudatoolkit=11.0` and without cudatoolkit installed, but the same error appears.

**Comment by mihaimaruseac** [comment]
It could be an issue on the conda build.

**Comment by mihaimaruseac** [comment]
Can you also try with the 2.4.1 patch?

**Comment by lillux** [comment]
Upgrade to `Tensorflow 2.4.1` solved my issue. Thank you!

**Comment by mihaimaruseac** [comment]
Awesome, thanks for confirming. Looks like the issue was #45744
