### ISSUE TITLE
Distributed tensorflow hangs 

### ISSUE THREAD

**Issue by passerbydj** [tensorflow/tensorflow#4651]
I set up a distributed tensorflow according to the inception example(https://github.com/tensorflow/models/tree/master/inception/inception), with a very deep network.
During training(minutes or hours), it must run into hanging. No error occurs in ps or workers, but the cpu/gpu usage falls to zero and no any further steps are made.
If I replace the network with a much simpler one(much less variables), all things work fine.
Is there any limit on the amount of vars placed on ps? or any suggestions to deal with the problem?

Setup: tensorflow r0.10 build on cuda 7.5 and cudnn v5

**Comment by concretevitamin** [comment]
We'll need much more details to diagnose this:

1. How large is large?  What's the # of vars?
2. What's your cluster configuration?  Spec of each machine's hardware?
3. We will need info/error logs and stack traces.

**Comment by passerbydj** [comment]
[network.py.txt](https://github.com/tensorflow/tensorflow/files/502540/network.py.txt)

1. please see the python file.
2. the cluster is set on 2 servers. each one has a ps and a worker. And each worker works on 4 gpu cards.
3. nothing unusual appears in logs, all logs were print as I coded until it hangs. I do not have stack details right now, but both ps and workers are on locks, and workers still send messages periodically.

**Comment by jart** [comment]
In order for us to help, we need simple specific steps to reproduce the problem. We're not able to troubleshoot nontrivial scripts. Here's an [example](https://github.com/tensorflow/tensorflow/issues/3978) of an issue that demonstrated a hanging issue which was able to be reproduced and solved. Please feel free to file another issue if necessary.

**Comment by xuzhuoran0106** [comment]
Have you found the reason? @passerbydj

**Comment by suiyuan2009** [comment]
@passerbydj, still meet hang problem using the latest tf version?
