### ISSUE TITLE
dso_loader.cc Could not load dynamic library 'cupti64_110.dll'; dlerror: cupti64_110.dll not found

### ISSUE THREAD

**Issue by marcusobrien** [tensorflow/tensorflow#46520]
**System information**
- Windows 10 - 20H2 Build 19042.746
- TensorFlow installed from (source or binary): Nightly
- TensorFlow version: 
- tensorboard==2.4.1
tensorboard-plugin-wit==1.7.0
tensorflow-estimator==2.4.0
tensorflow-gpu==2.4.0
tensorflow-hub==0.11.0
tf-estimator-nightly==2.5.0.dev2021011401
tf-nightly-gpu==2.5.0.dev20210114

- Python version: 3.8.5
- Installed using virtualenv? conda - with pip installs on top
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.1/8.0.5.39 for CUDA 11.1
- GPU model and memory: RTX 3090 - 24GB

**Describe the problem**
Running through a search for the best hyper params. This means I am looping through these actions in the same process - creating ANN(LSTM), compiling , training, validating an ANN, then changing the hypers and running again etc. This used to work on TF2.1 with my Super 2080, now I have changed to TF 2.5 as it supports the 3090. The system crashes on this line with no traceback, and no exception thrown.

training_history = self.model.fit (ann_training_input_batched_scaled_3d, training_output,
                                               epochs = regressor_number_epochs, batch_size = regressor_batch_size,
                                               callbacks = callbks,
                                               verbose=1,
                                               validation_data = (ann_validation_input_batched_scaled_3d, valoutput))

This is the second iteration, so the second time this gets executed (but its with a new ANN so its the the first time with a new ANN, second time in the process). Note that if I use a CPU instead of a GPU I get the same errors about CUPTI, but it doesnt crash so quickly, it dos a few more iterations then crashes with no exception/logging etc.

Before it dies, I see these warnings and finally errors

ensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti64_110.dll'; dlerror: cupti64_110.dll not found
2021-01-18 17:40:51.410137: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti.dll'; dlerror: cupti.dll not found
2021-01-18 17:40:51.410283: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1644] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2021-01-18 17:40:51.410657: I tensorflow/core/profiler/lib/profiler_session.cc:158] Profiler session tear down.
2021-01-18 17:40:51.410812: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1735] function cupti_interface_->Finalize()failed with error CUPTI could not be loaded or symbol could not be found.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
I dont understand how the process is dying, and I have the offending code wrapped in a try block, but no exception is being thrown. 

Also how do I resolve this dll CUPTI warning ? It should be using cupti64_2020.2.1.dll. It works for the first iteration.

Marcus

**Comment by amahendrakar** [comment]
@marcusobrien,
Please take a look at issue [#43030](https://github.com/tensorflow/tensorflow/issues/43030#issuecomment-736206189) with a similar error and let us know if it helps. Thanks!
