### ISSUE TITLE
RecvAsync is cancelled error on Ryzen High Performance mode

### ISSUE THREAD

**Issue by chiranshu14** [tensorflow/tensorflow#46527]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
>No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> Windows 10

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
>No

- TensorFlow installed from (source or binary):
>binary

- TensorFlow version (use command below):
>2.4.0

- Python version:
>3.8.7

- Bazel version (if compiling from source):
N/A

- GCC/Compiler version (if compiling from source):
N/A

- CUDA/cuDNN version:
>V11.0.221

- GPU model and memory:
>RTX 3070 FE (VRAM - 8GB, system memory- 32GB)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
>v2.4.0-rc4-71-g582c8d236cb 2.4.0

**Describe the current behavior**

>I am trying to run the sample code [here](https://www.tensorflow.org/tutorials/text/text_classification_rnn). 
1. If the computer is on Ryzen High Performance mode, while executing the statement "model.fit()", the code breaks with an error "RecvAsync is cancelled" after 2 epochs.  (attached is the screenshot of the error)
error- 
CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node gradient_tape/sequential/embedding/embedding_lookup/Reshape/_54}}]] [Op:__inference_train_function_22374]

Function call stack:
train_function

2. If the computer is on Power saving mode, the model trains successfully without an error. 
In both, the above cases the CPU, RAM and GPU utilization was below 20%
 
System specifications - 
Ryzen 3700X | 32GB 3000MHz CL15 DDR4 ram | RTX 3070 | Windows 10

**Describe the expected behavior**
The code should run successfully regardless of the Power option selected. Especially in Ryzen High Performance mode, the code should run faster and without any issues. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I am trying to run the code from the tensorflow website - 
https://www.tensorflow.org/tutorials/text/text_classification_rnn

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

![system_sw_info](https://user-images.githubusercontent.com/25884862/104998987-20db6780-5a52-11eb-835e-5f25b8a97cdc.png)
![tensorflow_error](https://user-images.githubusercontent.com/25884862/105003986-5a63a100-5a59-11eb-93b6-fc6203bdc681.png)

**Comment by amahendrakar** [comment]
@chiranshu14,
Could you please try limiting the total GPU memory using any one of the methods listed in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and check if you are facing the same error.

Also, please take a look at [this comment](https://stackoverflow.com/a/58517209) from a similar StackOverflow query and let us know if it helps. Thanks!

**Comment by chiranshu14** [comment]
Hi @amahendrakar ,

I tried the following solutions that you mentioned - 
1.  Enable memory growth
2. Restricting GPU memory limit to 1024 and 4096 MB
3. setting the OS environment variable TF_FORCE_GPU_ALLOW_GROWTH to true

But none of these worked. Note that, the PC was on Ryzen High Performance mode. ( I also tried High Performance and Balanced modes) and it still didn't work.

When I switched to "Power Saving" mode, the code ran without having to do any of the above steps. 
Also, I was continuously monitoring the hardware info of the GPU in the course of training and it never crossed 50% of the GPU memory and 95% of utilization. So it seems like it is not that tf isn't getting enough memory. There is something with Battery Saving option that makes it run without any issues.
![image](https://user-images.githubusercontent.com/25884862/105109358-68a9cf80-5ae2-11eb-84e5-add42eeb9701.png)

**Comment by chiranshu14** [comment]
@amahendrakar ,

Here is the complete error description for your reference (Battery option - Ryzen High Performance)


Epoch 1/10
391/391 [==============================] - 38s 80ms/step - loss: 0.6847 - accuracy: 0.5111 - val_loss: 0.5003 - val_accuracy: 0.7255
Epoch 2/10
373/391 [===========================>..] - ETA: 1s - loss: 0.4305 - accuracy: 0.8031
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-19-7944b517869f> in <module>
----> 1 history = model.fit(train_dataset, epochs=10,
      2                     validation_data=test_dataset,
      3                     validation_steps=30)

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    853       # In this case we have created variables on the first call, so we run the
    854       # defunned version which is guaranteed to never create variables.
--> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    856     elif self._stateful_fn is not None:
    857       # Release the lock early so that multiple threads can perform the call

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in __call__(self, *args, **kwargs)
   2940       (graph_function,
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
-> 2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1916         and executing_eagerly):
   1917       # No tape is watching; skip to running the function.
-> 1918       return self._build_call_outputs(self._inference_function.call(
   1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    553       with _InterpolateFunctionError(self):
    554         if cancellation_manager is None:
--> 555           outputs = execute.execute(
    556               str(self.signature.name),
    557               num_outputs=self._num_outputs,

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_57}}]]
	 [[gradient_tape/sequential/embedding/embedding_lookup/Reshape/_54]] [Op:__inference_train_function_22374]

Function call stack:
train_function

**Comment by chiranshu14** [comment]
@amahendrakar Some more insights - 
I was able to run the [Neural style transfer code ](https://www.tensorflow.org/tutorials/generative/style_transfer)
and the [Image classifier code ](https://www.tensorflow.org/tutorials/images/classification) without any issues in the high-performance mode. 
So my guess is there is an issue specifically with the RNN implementation.

**Comment by amahendrakar** [comment]
@chiranshu14,
Could you please try running the code in a new virtual environment and check if it works.

Also, check if you are facing the same issue with the latest TF-nightly as well. Thanks!
