### ISSUE TITLE
tensorflow running principle 

### ISSUE THREAD

**Issue by KingAndQueen** [tensorflow/tensorflow#4652]
1. In tensorflow/python/ops/seq2seq_model.py  line 236 , we see the output_feed cosists of  self.updates and self.gradient_norms.
And the self.updates is not used in anywhere, I wonder if I can delete this from output_feed ?
2. How does the tensorflow run:  If a variable is not in its output_feed list, does tensorflow count this variable ?

**Comment by tatatodd** [comment]
@KingAndQueen please say which version of tensorflow you're using:

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

For basic usage of tensorflow, see the documentation:
https://www.tensorflow.org/versions/r0.11/get_started/basic_usage.html#basic-usage

Hope this helps!

**Comment by aselle** [comment]
Closing for now, because there does not seem to be any bug or enhancement request. Please read the documentation, and if you need specific usage help, you can post on StackOverFlow. Thank you!
