### ISSUE TITLE
CrossShardOptimizer must be used for model training on TPUs

### ISSUE THREAD

**Issue by StrangeTcy** [tensorflow/tensorflow#46526]
Running [the example](https://github.com/EleutherAI/gpt-neo) on a Colab TPU results in the following error:
```
File "main.py", line 256, in <module>
    main(args)
  File "main.py", line 230, in main
    estimator.train(input_fn=partial(input_fn, global_step=current_step, eval=False), max_steps=next_checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3130, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3125, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2962, in _call_model_fn
    config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3386, in _model_fn
    _validate_tpu_training_graph(ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3817, in _validate_tpu_training_graph
    'CrossShardOptimizer must be used for model training on TPUs.')
ValueError: CrossShardOptimizer must be used for model training on TPUs.
```

**Comment by Saduf2019** [comment]
@StrangeTcy 
Please share minimum code to replicate the issue faced or share a colab gist with the issue.

**Comment by StrangeTcy** [comment]
[try following this notebook](https://colab.research.google.com/github/EleutherAI/GPTNeo/blob/master/GPTNeo_example_notebook.ipynb#scrollTo=R918l14UhrBR)

**Comment by Saduf2019** [comment]
@StrangeTcy
please attach the data set used for us to replicate the issue.

**Comment by StrangeTcy** [comment]
Any way to move on resolving this issue?

**Comment by StrangeTcy** [comment]
@Saduf2019 
Ok, sorry, disregard the aforementioned notebook, use this one instead:
https://colab.research.google.com/drive/1MaamQYdVsGvpWnUZ_5tDtT-OsLYcZOHI?usp=sharing
It uses the data set on my Google Drive, which I'll modify the code to `gdown`

**Comment by Saduf2019** [comment]
@StrangeTcy
We see that you are using tf 1.x version, can you please use 2.x and let us know as there is no support for 1.x.

**Comment by StrangeTcy** [comment]
@Saduf2019 , 
I've thought of that already, and if I leave the 2.x tf, I run into [the wrong `mesh_shape` error](https://github.com/EleutherAI/gpt-neo/issues/119)

**Comment by Saduf2019** [comment]
I ran the code shared but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f2ce91b1d11a44cac830af5806819fa4/untitled514.ipynb).

**Comment by StrangeTcy** [comment]
@jvishnuvardhan 
Ok, I'm running the gist and running into the wrong `mesh_shape` error as mentioned above.
Kindly quote the error you were facing with your gist if you deem it helpful.

**Comment by StrangeTcy** [comment]
@jvishnuvardhan 
any way to speed up the resolution of this issue?

**Comment by StrangeTcy** [comment]
@jvishnuvardhan 
Oh, no-one cares any more. Okay

**Comment by jvishnuvardhan** [comment]
@StrangeTcy Sorry for the delay. Thanks!

**Comment by nikitamaia** [comment]
Hi @StrangeTcy, if I understand correctly, you're trying to run the code in this repo on TPUs. That repo indicates that it provides TPU support so my suggestion would be to post an issue in that repo since this seems like a support request. I do not have much familiarity with TF1.x but as I recall you need to wrap the optimizer in a [ CrossShardOptimizer](https://www.tensorflow.org/api_docs/python/tf/compat/v1/tpu/CrossShardOptimizer) if you want to use TPUs

**Comment by hthu** [comment]
Looks like you probably want to wrap your optimizer with `CrossShardOptimizer` when using TPU?

https://github.com/EleutherAI/gpt-neo/blob/c0961f0177b3d8bd8aa0552df24a7da2fa5c2537/model_fns.py#L187

You might want to condition on `if params["use_tpu"]:` there.

**Comment by hthu** [comment]
In the meantime I created a PR:
https://github.com/EleutherAI/gpt-neo/pull/131

Haven't really tested it though..

**Comment by StrangeTcy** [comment]
@hthu
Well, it definitely looks like a thing that'd help, but I'd say that it's not that I want to wrap my optimizer into a `CrossShardOptimizer`, I want for the tensorflow/mesh-tensorflow code to do it for me.

**Comment by hthu** [comment]
@StrangeTcy 
I understood, but this is the one of the most important pieces when using TPU and this is the correctness guarantee for your computation.

Otherwise your gradients over 8 TPU cores will not be fully aggregated.

If it is the framework that you're using, the framework should probably follow the rule as well.

There is also a reference on cloud tpu mentioning using the `CrossShardOptimizer`, here:
https://cloud.google.com/tpu/docs/using-estimator-api

**Comment by StrangeTcy** [comment]
@hthu 
https://stackoverflow.com/questions/66193962/best-way-to-wrap-an-optimizer-in-crossshardoptimizer -- perhaps you might recommend the best course of action?

**Comment by hthu** [comment]
Looks like you are using `mesh tensorflow` here.

I believe you probably shouldn't try to wrap things inside `CrossShardOptimizer` anymore as `MTF` already does cross replica sums automatically based on your mesh and layouts.

Can you try to run a `2x4` or `all:8` mesh on MTF and see if those would work without wrapping `CrossShardOptimizer`?

**Comment by StrangeTcy** [comment]
@hthu 
As I see it, this is what lead me here to begin with: if I use some unwrapped `mtf` optimizer, I get an error that `CrossShard optimizer must be used for training on TPUs`, and I don't know the correct way to wrap v2 optimizers in `CrossShardOptimizer`

**Comment by hthu** [comment]
The idea is that you shouldn't try to wrap those, at all.
Mesh Tensorflow and the framework you're using should already handle the `CrossReplicaSum` needed (see my comments on the other thread as well).

If you run into errors, this is likely how the framework or `MTF` handles TPU computation.

Let's move the discussion to the [thread](https://github.com/EleutherAI/gpt-neo/issues/120) inside the framework you're using.

**Comment by sanatmpa1** [comment]
@StrangeTcy,

Can you take a look at the comment from @hthu? Thanks!
