### ISSUE TITLE
Should pb file match CUDA version?

### ISSUE THREAD

**Issue by Ellie1013** [tensorflow/tensorflow#46529]
I used tensorflow.git and bazel to build a model. The detail process is

1. git clone tensorflow.git
2. ./configure << tensorflow configure
3. I answered N in every question of configure process including 'Use CUDA'.
4. bazel-build my model to pb file

Then, can I use my model in any device that set CPU or GPU(any CUDA, Cudnn version)?

When I run my pb file, it occurs to fail to make cuFFT batched plan.

As I searched, it was because CUDA version doesn't match, is it right?

**Comment by Saduf2019** [comment]
@Ellie1013 
Please find cuda version compatibility [here](https://www.tensorflow.org/install/source). cuda 11.0 is compatible with latest version of tensorflow and stable version 2.4.
Please share logs of any failure faced in case it is still an issue.

**Comment by Ellie1013** [comment]
What does mean 'Do you wish to build TensorFlow with CUDA support?' for tensorflow configure process? to build pb file? or to run pb file?

Last week pb file worked correctly, so it returned the result. But, now it doesn't work. I don't know what happen.

The detail setting is...

Linux 
Tensorflow v.1.15 (It must use tensorflow version 1) 
CUDA 10.2.89 
Cudnn 7.6.5.32

Error log is... 2021-01-19 17:00:45.138402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1 2021-01-19 17:00:45.138469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0 2021-01-19 17:00:45.140340: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix: 2021-01-19 17:00:45.140359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165] 0 1 2021-01-19 17:00:45.140368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0: N N 2021-01-19 17:00:45.140392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1: N N 2021-01-19 17:00:45.142855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10024 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:65:00.0, compute capability: 7.5) 2021-01-19 17:00:45.144418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 5035 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:b3:00.0, compute capability: 7.5) 2021-01-19 17:00:45.146850: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564476c72980 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices: 2021-01-19 17:00:45.146877: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5 2021-01-19 17:00:45.146889: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5 2021-01-19 17:00:55.558024: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0 2021-01-19 17:00:55.757115: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7 2021-01-19 17:00:57.329001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0 2021-01-19 17:00:57.469277: E tensorflow/stream_executor/cuda/cuda_fft.cc:223] failed to make cuFFT batched plan:5 2021-01-19 17:00:57.469333: E tensorflow/stream_executor/cuda/cuda_fft.cc:426] Initialize Params: rank: 1 elem_count: 2048 input_embed: 1025 input_stride: 1 input_distance: 1025 output_embed: 2048 output_stride: 1 output_distance: 2048 batch_count: 46 2021-01-19 17:00:57.469343: F tensorflow/stream_executor/cuda/cuda_fft.cc:435] **failed to initialize batched cufft plan with customized allocator: Failed to make cuFFT batched plan.**

**Comment by Saduf2019** [comment]
@Ellie1013
There is no support for tensorflow 1.x now, please upgrade to 2.x.
TensorFlow 2.4 is built and tested against CUDA 11.0 and cuDNN 8. Fore more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).

Could you please install CUDA 11.0 with cuDNN 8 and check if you are facing the same issue. Thanks!
