### ISSUE TITLE
tf.keras.applications.densenet.preprocess_input does not work for data_format="channels_first" for symbolic tensors

### ISSUE THREAD

**Issue by PaulKlinger** [tensorflow/tensorflow#46539]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): colab
- TensorFlow version (use command below): 2.4.0, v2.4.0-0-g582c8d236cb
- Python version: 3.6.9

**Describe the current behavior**
Running `tf.keras.applications.densenet.preprocess_input` on a `data_format="channels_first"` symbolic tensor raises an Exception. This is caused by the input transposition not being applied if the `mode` parameter to [_preprocess_symbolic_input](https://github.com/tensorflow/tensorflow/blob/7a49c87f9f56a7fc169669cfe97728859798967c/tensorflow/python/keras/applications/imagenet_utils.py#L242) is set to "torch" (as is the case for densenet preprocessing).

See the relevant lines here:
https://github.com/tensorflow/tensorflow/blob/7a49c87f9f56a7fc169669cfe97728859798967c/tensorflow/python/keras/applications/imagenet_utils.py#L262-L281

This is not caught by the unit tests as only the default `mode="caffe"` is tested.

The equivalent numpy function `_preprocess_numpy_input` handles this correctly (treating the input differently depending on `data_format` for all modes

**Describe the expected behavior**
Preprocessing should work for `data_format="channels_first"`

**Standalone code to reproduce the issue**
Colab notebook with minimum example:
https://colab.research.google.com/drive/1THrNYTAAzPxw9135h-sFt-LxMz_7SEeQ?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/88605d7199898f076e057b8ed35457c9/46539.ipynb#scrollTo=NRQ2tF_zk5qY). Thanks!
