### ISSUE TITLE
Example code bug in documentation related to tf.data.Dataset.interleave

### ISSUE THREAD

**Issue by padoremu** [tensorflow/tensorflow#46536]
## URL with the issue:
https://www.tensorflow.org/guide/data_performance

## Description of issue:
The following has been tested with TF version v2.4.0-0-g582c8d236cb.

On the above-mentioned documentation page, it is defined:

`def __new__(cls, num_samples=3):`

which is ok up to some point, but results in a bug for the variant using `interleave`, since then internally a tensor is provided as second argument, so that `num_samples` won't be 3. In fact, it alternates between 0 and 1 in `_generator`. One can easily check this out by using the `print` function - both in `__new__` and in `_generator`.

Assuming the person writing this part of the documentation wasn't aware of this and this problem is not version specific, it is very likely that the timing results are wrong accordingly when using `interleave`.

It is also worth mentioning that when using `tf.data.Dataset.range(2).interleave`, the generated data in total is doubled in size (**if fixing the above-mentioned bug**), so that the timing results cannot be compared 1:1. When using `tf.data.Dataset.range(2).interleave`, the timing results should be divided by two to allow for a fair comparison, which isn't mentioned in the documentation.

See my gist [here](https://gist.github.com/padoremu/de948c6133c365bb3249c77b172aa4fd).

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/e73270cc9aa9431b7f95ea69ca5bfb20/46536-2-3.ipynb), [TF v2.4](https://colab.research.google.com/gist/amahendrakar/3a515cd6ca720be96268009d941a5f37/46536.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/aa7f3ae07a3ce055139691c4a3a94b72/46536-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!
