### ISSUE TITLE
libtensorflow-gpu-windows-x86_64-2.3.1 does not support GPUs with compute capability 5.0

### ISSUE THREAD

**Issue by shoelzer** [tensorflow/tensorflow#46537]
TensorFlow 2.3.1 crashes on my GPU with compute capability (CC) 5.0 with the error "no kernel image is available for execution on the device". I used [cuobjdump](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#cuobjdump) to inspect tensorflow.dll to see what binary and PTX code was included. I found binary code for CC 3.5, 3.7, 5.2, 6.0, 6.1, and 7.0 as well as PTX code for CC 7.0.

PTX code is forward-compatible, but 7.0 PTX cannot run on a 5.0 GPU. Binary code is forward-compatible but only for minor version updates. This means that neither the 3.7 nor the 5.2 binary can run on a 5.0 GPU. In fact, the current configuration means that TensorFlow 2.3.1 can run on any GPU with CC 3.5 and up *except* for CC 5.0.

I suggest building for CC 5.0 instead of CC 5.2 so that TensorFlow 2.3.X can run on any GPU with CC 3.5 and up.

**Comment by ymodak** [comment]
What version of TF are you using? TF 2.4 supports cc 5.0
https://github.com/tensorflow/tensorflow/issues/45904#issuecomment-750485891

**Comment by shoelzer** [comment]
This is with 2.3.1 and I updated the description above to make that clear. I also confirmed that 2.4.0 does support CC 5.0.

Will there be any more 2.3.X releases? If so, this is worth fixing.

**Comment by mihaimaruseac** [comment]
Was this a regression from 2.3.0?

We don't have a plan for more 2.3.x releases at the moment but if there are security vulnerabilities in a year since the release we will have to do a patch.

**Comment by shoelzer** [comment]
@mihaimaruseac  I just checked and this is not a regression from 2.3.0. Both 2.3.0 and 2.3.1 support the same set of of GPU compute capabilities. (They both exclude 5.0.)

**Comment by mihaimaruseac** [comment]
In this case, we won't be able to release a patch release changing the compute capabilities. We try to limit the delta between normal release and patches.
