### ISSUE TITLE
save custom training loop with keras API (train_step)

### ISSUE THREAD

**Issue by quetil** [tensorflow/tensorflow#46530]
Hi, based on the #38103 issue, I'd like to reopen the discussion:

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Windows/Linux as well)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): last one, 2.4.0
- Python version: 3.8

**Describe the current behavior**
I'm using the feature: custom training logic with `model.fit` by overriding `model.train_step` (and `model.test_step`). It's working well, except for saving/loading cases, I have the following issue:
When I save my model (`model.save`) with the custom training logic and then I want to load it, the custom training loop is not saved and when I apply a `model.fit` for my loaded model, it comes back to the default one.

**Describe the expected behavior**
I'd expect to save as well the model.train_step (and also `test_step`). Especially with the new 2.4 feature `model.save(save_traces=True)`. Is it possible (and if yes, how) ? If no, is a such feature planned or should I write a feature request ?

**Standalone code to reproduce the issue**
[Gist](https://colab.research.google.com/gist/quetil/51c1b89bddd5e25d896678b87b62712f/save-custom-train_step-in-subclassing-model.ipynb)

Thank you in advance,

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/1b04d27710a0136b72ff546df22f5760/46530.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/5e5a3ad01ed5d2c6a1c853d4a2bb4619/46530-tf-nightly.ipynb). 

Whereas running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/2deed26ac2f6239ca51f08d1bfa65865/46530-2-3.ipynb#scrollTo=OkFh162Qzj-M) throws an error stating `TypeError: save() got an unexpected keyword argument 'save_traces'`. Please check the linked gist for reference. Thanks!

**Comment by jvishnuvardhan** [comment]
@quetil There are some differences while saving and loading of Sequential/Functional models when compared to Subclass models. The approach you followed is correct for Sequential/Functional models but need slight modification as shown in the following [gist](https://colab.research.google.com/gist/jvishnuvardhan/9e531f99119f1f13d6a0f7916aa23c95/46530-tf-nightly.ipynb).

In simple you need to implement `get_config` and `from_config` methods. There is an extensive [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects). 

Please verify once and close the issue if this was resolved for you. Thanks!
