### ISSUE TITLE
Build failure when using non-system gcc with later glibc

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#46549]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: HEAD
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Build using gcc 10.2.0 compiled on system with a later version of glibc than installed on system.
The tool flatc which is compiled during the build links with the glibc from gcc 10.2.0.
When flatc is executed later in the build, the environment is cleared out and it is not possible to set LD_LIBRARY_PATH so that it would load the correct version of glibc.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

System installed libstdc++.so.6 is 3.4.25
gcc 10.2.0 built with glibc 2.28 and libstdc++.so.6 3.4.28 installed to /usr/local
Build command line:
$ TF_MKL_ROOT=~builder/1/built_tarballs/onednn/ bazel build --config=noaws --config=nogcp --config=nonccl --config=mkl_aarch64 --action_env=TF_MKL_ROOT=/home/builder/1/built_tarballs/onednn/ --action_env=LD_LIBRARY_PATH=/usr/local/lib64 --host_action_env=LD_LIBRARY_PATH=/usr/local/lib64 //tensorflow/tools/pip_package:build_pip_package --verbose_failures

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Build fails with the below messages:
ERROR: /home/debian/src/tensorflow_1dnn-git/tensorflow/lite/python/BUILD:11:22: Generating flatbuffer files for <source file tensorflow/lite/schema/schema.fbs>: failed (Exit 1): flatc failed: error executing command 
  (cd /home/debian/.cache/bazel/_bazel_debian/0988af24c3a1bb0051e8f606aa777b9e/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/flatbuffers/flatc --python -o bazel-out/aarch64-opt/bin/tensorflow/lite/python/schema_py_srcs_no_include_all -I ./ -I bazel-out/aarch64-opt/bin -I bazel-out/aarch64-opt/bin --no-includes --no-union-value-namespacing --gen-object-api tensorflow/lite/schema/schema.fbs)
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/external/flatbuffers/flatc: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by bazel-out/host/bin/external/flatbuffers/flatc)
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by ssrokyz** [comment]
From the following page, the issue could be solved in my case.
[https://github.com/tensorflow/tensorflow/pull/46550](https://github.com/tensorflow/tensorflow/pull/46550)
