### ISSUE TITLE
TensorFlow Lite  support multi scale input?

### ISSUE THREAD

**Issue by hufangjian** [tensorflow/tensorflow#46546]
Did TensorFlow Lite  support multi scale input?
In same case,i need dynamic input shapes;

for examples:
the tensorflow lite mode input shape is  1x3x360x640

but I can not input 1x3x720x1080 .
(without fixed size, FC,all ops are conv).
caffe ,ncnn,TNN model, i can change the protext  to support multi scale input.

**Comment by abattery** [comment]
TensorFlowLite support dynamic dimension features like TensorFlow. However, the orginal model should be trained with dynamic dimensions to fit your needs.
