### ISSUE TITLE
 An error occurs when inferring by loaded pretrained model

### ISSUE THREAD

**Issue by karrdy89** [tensorflow/tensorflow#46547]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Google colab

**Describe the current behavior**
- Error occurs when inferring from loaded model (before saving, it is successfully inferred from the same input)
- same happens even if the input signature is redefined when saving the model 

**Describe the expected behavior**
- Must be inferable from the loaded model

**Standalone code to reproduce the issue**
- here is code : https://colab.research.google.com/drive/1CJyLvind12Df-WFst4UTPMk0e5C996Tq?usp=sharing
- Links to the data are also in colab 

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
- here  is error message
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-13d7f1beda6b> in <module>()
      1 loaded_bert_model = tf.saved_model.load(DATA_OUT_PATH+'/bert/saved')
      2 loaded_electra_model = tf.saved_model.load(DATA_OUT_PATH+"/electra/saved")
----> 3 logits = loaded_bert_model(input_encodings_bert)['logits']
      4 print("bert_saved",logits)
      5 logits = loaded_electra_model(input_encodings_electra)['logits']

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/function_deserialization.py in restored_function_body(*args, **kwargs)
    271         .format(_pretty_format_positional(args), kwargs,
    272                 len(saved_function.concrete_functions),
--> 273                 "\n\n".join(signature_descriptions)))
    274 
    275   concrete_function_objects = []

ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (9 total):
    * {'input_ids': <tf.Tensor 'input_ids_1:0' shape=(1, 14) dtype=int32>, 'attention_mask': <tf.Tensor 'input_ids:0' shape=(1, 14) dtype=int32>}
    * None
    * None
    * None
    * None
    * None
    * None
    * None
    * False
  Keyword arguments: {}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (9 total):
    * {'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}
    * None
    * None
    * None
    * None
    * None
    * None
    * None
    * True
  Keyword arguments: {}

Option 2:
  Positional arguments (9 total):
    * {'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}
    * None
    * None
    * None
    * None
    * None
    * None
    * None
    * False
  Keyword arguments: {}
```

**Comment by amahendrakar** [comment]
@karrdy89,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/37973#issuecomment-605448707) from issue #37973 with a similar error and let us know if it helps. Thanks!

**Comment by karrdy89** [comment]
In my case redefine the input signature can solve the problem.
If you just save transformers distilbert model, the form of the _default_save_signature function will look like this.
```
 input_signature: ({'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids')})
```
Therefore, if you want to pass a total of three inputs(input_ids, attention_mask, token_type_ids), it is necessary to design the model layer according to the input and redefine the input signature through the __call__ method with @tf.function decorator.

However, it seems there is a problem that an error occurs in the loaded model when the same value as the input before saving.

**Comment by sanatmpa1** [comment]
@karrdy89,

Can you try updating TF to latest stable version i.e 2.7.0 and let us know if the issue still persists? Thanks!
