### ISSUE TITLE
tf.nn.convolution crashes Floating-point exception when filters has 0 in shape

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46540]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.6.9
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.nn.convolution` crashes (Floating-point exception) when `filters` has 0 in shape

error message:
~~~
[1]    10129 floating point exception (core dumped)  python
~~~
**Describe the expected behavior**
expect no crash
**Standalone code to reproduce the issue**
~~~
import numpy as np
import tensorflow as tf
tf.nn.convolution(input=np.ones((1,1,1,1)), filters=np.ones((1,0,1,1)))
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1, 2.4 and nightly version(`2.5.0-dev20210119`) and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/86610191c4b189c94d36a872672d034a/untitled624.ipynb). Thanks!

**Comment by ymodak** [comment]
I tested with TF 2.3.1, 2.4.0 on macOS, Python 3.7 with PyCharm IDE, I didn't see the crash. The code executed successfully.

**Comment by bhack** [comment]
It is not only the case when the filter has a 0 shape value cause this works fine:

```
tf.nn.convolution(input=tf.ones((1,0,1,1)), filters=tf.ones((1,0,1,1)))
```

**Comment by DNXie** [comment]
@ymodak 
I tested on the nightly version (`2.5.0-dev20210114`) and it still crashes.

**Comment by ymodak** [comment]
I wonder if this issue only fails on colab.
On macOS pycharm it gives:
```python
tf.Tensor(
[[[[0.]
   [0.]]]], shape=(1, 1, 2, 1), dtype=float64)
```
