### ISSUE TITLE
Compared to TF1.15, do TF2 have some speedup  in CPU inference?

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensorflow#46548]
I find this is not a good Stackoverflow question.

So I post it here. Thank you for your time.

**Comment by ravikyram** [comment]
@guotong1988 

Can you please share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
