### ISSUE TITLE
Source code for tf.signal.rfft

### ISSUE THREAD

**Issue by yugeshav** [tensorflow/tensorflow#46552]
Hi,

I am trying to convert tf.signal.fft into c code for my project. I have gone through the below link to understand the functionality

https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/python/ops/signal/fft_ops.py#L115-L141

I could not find the complete source to understand the  tf.signal.fft  API.

The source code found is returning  fft_fn(input_tensor, fft_length, Tcomplex=complex_dtype, name=name) but no complete steps.

Can someone please help to find the definition of the above function  fft_fn(..)

or

if there is any c code for this function, please provide the link or attachment.

Regards,
Yugesh.

**Comment by cutun** [comment]
I think code is based on [Eigen and Cublas]
[](https://github.com/tensorflow/tensorflow/blob/7b4c01794fbc2e6dc46e93a42416dd80929ce1e5/tensorflow/core/kernels/fft_ops.cc#L124)
