### ISSUE TITLE
 A function to get number of TFLite model parameters

### ISSUE THREAD

**Issue by vadim-belov** [tensorflow/tensorflow#46569]
**System information**
- TensorFlow version (you are using): 2.3 
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.** A function to get number of TFLite model parameters

**Will this change the current api? How?** It will add a new function to Interpreter

**Who will benefit with this feature?** People who need to optimize the model. They will be able to see the change in parameter number and estimate benefits 

**Any Other info.** If there is a way to do it in a current version, please, let me know.

**Comment by abattery** [comment]
We do not have such API yet since the parameters are frozen into the constant tensors. However, the number of TFLite tensors will be approximately the same with the original TF model but they are not the same.

**Comment by vadim-belov** [comment]
Thank you for your answer! But as I understand, It is only avaylable in C++ API. Is there a way to get this value through python API?

**Comment by abattery** [comment]
Flatbuffer object can be obtained to retrieve the information of the model directly.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/flatbuffer_utils.py#L40
