### ISSUE TITLE
LSTM layer not Using cuDNN even with default arguments

### ISSUE THREAD

**Issue by kevin1zc** [tensorflow/tensorflow#46567]
**Problem description**
I am using a TF model in RLlib in my project. The model contains a ConvLSTM2D layer and a LSTM layer. However, even with default arguments, there is a warning:
`WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU`
Note that there is no complaint about my ConvLSTM2D layer.
I also tried to manually filled in all relevant arguments with values required in TF document, but the warning still persists. Can anyone help me figure out where the problem is?
Full code for constructing the model and the system information are provided below.

**Code for model construction**
Note that obs_space.shape=46800, activation=tanh, and normc_initializer is a built-in kernel initializer in RLlib.
```
        inputs = tf.keras.layers.Input(obs_space.shape, name="observations")

        input_depth = inputs[..., :45000]
        input_sensor = inputs[..., 45000:]

        input_depth = tf.keras.layers.Reshape(target_shape=(50, 30, 30, 1))(input_depth)
        input_sensor = tf.keras.layers.Reshape(target_shape=(50, 36))(input_sensor)

        conv_lstm = tf.keras.layers.ConvLSTM2D(filters=10, kernel_size=(3, 3))(input_depth)
        pool = tf.keras.layers.MaxPool2D()(conv_lstm)
        flat = tf.keras.layers.Flatten()(pool)

        fc1 = tf.keras.layers.Dense(512, activation=activation)(flat)
        fc2 = tf.keras.layers.Dense(128, activation=activation)(fc1)
        conv_out = tf.keras.layers.Dense(16, activation=activation)(fc2)

        sensor_lstm = tf.keras.layers.LSTM(units=64)(input_sensor)

        action_out = tf.keras.layers.Concatenate()([sensor_lstm, conv_out])
        action_out = tf.keras.layers.Dense(128, activation=activation,
                                           kernel_initializer=normc_initializer(1.0))(action_out)
        action_out = tf.keras.layers.Dense(64, activation=activation,
                                           kernel_initializer=normc_initializer(1.0))(action_out)
        final_action_out = tf.keras.layers.Dense(num_outputs,
                                                 activation=activation,
                                                 kernel_initializer=normc_initializer(1.0))(action_out)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.01))(action_out)

        self.base_model = tf.keras.Model(
            inputs, [final_action_out, value_out])
        self.register_variables(self.base_model.variables)
```

**System information**
- OS Platform and Distribution: Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA version: 11.2
- cuDNN version: 8.0.5
- GPU model and memory: GeForce RTX 3080, 10009MiB

**Comment by amahendrakar** [comment]
@kevin1zc,
On running the given code snippet, I am facing an error stating `NameError: name 'num_outputs' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b82c1d230238dbf7311209faabfbd9bb/46567.ipynb). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using.

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40944#issuecomment-655665293) from issue #40944 with a similar error log and check if it helps. Thanks!

**Comment by kevin1zc** [comment]
@amahendrakar 
Thank you for your response. I double checked my code and LSTM documentation, and this seems to be a problem of RLlib. It disabled eager execution by default, which violates the LSTM requirement for using cuDNN. Enabling eager mode manually should fix the problem.
