### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tensorflow#4656]
Hi,

The documentation for tf.contrib.learn.LinearRegressor.weights_ is missing. Can you update what the values returned by the above param means?

Thank,
Sumit

**Comment by concretevitamin** [comment]
It's probably obvious, but I imagine you're looking for a more rigorous spec such as a formula?  Assigning to @martinwicke to take a look or re-assign if appropriate.

**Comment by martinwicke** [comment]
weights_ may actually go away soon, so I wouldn't rely on it. Please use get_tensor_value instead. 

Out of interest, what would you be using it for? We're removing it because we didn't feel it was worth it.

**Comment by sumitbinnani** [comment]
Not anything in particular. Was exploring the parameters to understand what model is learning, and had difficulty understanding what the parameters returned by ``weights_`` meant.

**Comment by sumitbinnani** [comment]
Any idea about how to proceed, @martinwicke @concretevitamin?
```
AttributeError: 'LinearRegressor' object has no attribute 'get_tensor_value'
```

**Comment by martinwicke** [comment]
Sorry -- I should have said `get_variable_names` and `get_variable_value`.
