### ISSUE TITLE
tf.config.run_functions_eagerly(run_eagerly=True) cashes on model load

### ISSUE THREAD

**Issue by ChWick** [tensorflow/tensorflow#46579]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3 and 2.4 verified
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Not required
- GPU model and memory: Not required

**Describe the current behavior**
Exception when loading saved model when a custom layer having `training=None` as argument is implemented.
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * Tensor("Placeholder:0", shape=(None, 28, 28), dtype=float32)
  Keyword arguments: {'training': False}

Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='inputs')
    * False
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name='inputs')
    * True
  Keyword arguments: {}
```

**Describe the expected behavior**
No exception

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
[minimal example](https://colab.research.google.com/drive/1NBb6neAWOLhtBfORWviZB-Cy2BRrScz3?usp=sharing)

**Other info / logs**
See Colab error.
Removing the `tf.config.run_functions_eagerly` does not result in an exception and training the model works flawlessly.

**Comment by amahendrakar** [comment]
@ChWick,
Please check these comments from issue [#45602](https://github.com/tensorflow/tensorflow/issues/45602#issuecomment-744065797), [#43605](https://github.com/tensorflow/tensorflow/issues/43605#issuecomment-739076002) and [#38620](https://github.com/tensorflow/tensorflow/issues/38620#issuecomment-651338446) with similar error log and let us know if it helps. Thanks!

**Comment by ChWick** [comment]
@amahendrakar Thank you so much! I obviously I was unable to perform a solid search...
