### ISSUE TITLE
arg_scope overwrite fails for positional arguments

### ISSUE THREAD

**Issue by NoahDStein** [tensorflow/tensorflow#4657]
The code

```
x = tf.placeholder(tf.float32, [None, 10])
with slim.arg_scope([slim.fully_connected], num_outputs=20):
    y = slim.fully_connected(x, 30)
```

raises

```
TypeError: fully_connected() got multiple values for argument 'num_outputs'
```

There is an easy workaround, namely changing `30` to `num_outputs=30` seems to work fine.  I'm not sure if this is easy to fix or was even intended to work.

**Comment by jmchen-g** [comment]
I believe the arg_scope will add those to the function calls below. Also:
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.

**Comment by NoahDStein** [comment]
I don't see how this addresses the bug of arg_scope not working with positional arguments.  I also don't see how StackOverflow would be appropriate because this is not a question, it's a bug report.

**Comment by jmchen-g** [comment]
@sguada Please clarify what is your intended behavior. Thanks.

**Comment by sguada** [comment]
Arg_scope only affect key-word arguments, which have a default value.

**Comment by NoahDStein** [comment]
The current behavior is somewhere in the middle: arg_scope affects positional arguments, but they cannot be overridden positionally, only by specifying them by name as keyword arguments.  It makes perfect sense to me that a relatively straightforward implementation would lead to this behavior and that it might be much more complicated to either remove the ability of arg_scope to affect positional arguments entirely or to add the ability to override them positionally.  So I think leaving the behavior as is would be reasonable, I just wanted to make sure the developers were aware of it, because the error message is a little confusing if you don't think about how arg_scope could be implemented.

**Comment by nathansilberman** [comment]
Your assessment is correct. We'll try to clarify behavior via documentation. Thanks for pointing this out!
