### ISSUE TITLE
I got this error while trying to run the webcam_demo.py example in Posenet library from tensorflow. how to resolve this?

### ISSUE THREAD

**Issue by ArimaValanImmanuel** [tensorflow/tensorflow#46575]
I got this error/warning while trying to run the webcam_demo.py example in Posenet library from Tensorflow. how to resolve this?

This is the **Git Repo** from where I forked this code : [posenet-python](https://github.com/rwightman/posenet-python)

and This is my **Output Screen** :
```
>>> 
 RESTART: A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py 
Cannot find model file ./_models\model-mobilenet_v1_101.pb, converting from tfjs...
WARNING:tensorflow:From A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py", line 66, in <module>
    main()
  File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py", line 20, in main
    model_cfg, model_outputs = posenet.load_model(args.model, sess)
  File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\posenet\model.py", line 42, in load_model
    convert(model_ord, model_dir, check=False)
  File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\posenet\converter\tfjs2python.py", line 198, in convert
    initializer_nodes="")
  File "A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 361, in freeze_graph
    checkpoint_version=checkpoint_version)
  File "A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 190, in freeze_graph_with_def_protos
    var_list=var_list, write_version=checkpoint_version)
  File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 835, in __init__
    self.build()
  File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 847, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 885, in _build
    build_restore=build_restore)
  File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 489, in _build_internal
    names_to_saveables)
  File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 362, in validate_and_slice_inputs
    for converted_saveable_object in saveable_objects_for_op(op, name):
  File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 223, in saveable_objects_for_op
    yield ResourceVariableSaveable(variable, "", name)
  File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 95, in __init__
    self.handle_op = var.op.inputs[0]
IndexError: tuple index out of range
>>> 
```

**Comment by amahendrakar** [comment]
@ArimaValanImmanuel,
The linked tutorial uses TensorFlow 1.12, which is not actively supported. 

Could you please migrate the code to the latest stable version TensorFlow 2.4 and check if you are facing the same issue. Thanks!

**Comment by ArimaValanImmanuel** [comment]
I migrated after reading the code fully, now I got this error:

How to resolve this?

 `google.protobuf.message.DecodeError: Error parsing message

`
Code snippet is:

```
graph_def.ParseFromString(f.read())
```

**Comment by amahendrakar** [comment]
@ArimaValanImmanuel,
In order to expedite the trouble-shooting process, could you please remove all the external dependencies and provide a minimal code snippet so that we can reproduce the issue on our end. That will also allow us to determine the source of the issue easily. Thanks!

**Comment by haiderasad** [comment]
> I got this error/warning while trying to run the webcam_demo.py example in Posenet library from Tensorflow. how to resolve this?
> 
> This is the **Git Repo** from where I forked this code : [posenet-python](https://github.com/rwightman/posenet-python)
> 
> and This is my **Output Screen** :
> 
> ```
> >>> 
>  RESTART: A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py 
> Cannot find model file ./_models\model-mobilenet_v1_101.pb, converting from tfjs...
> WARNING:tensorflow:From A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> Traceback (most recent call last):
>   File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py", line 66, in <module>
>     main()
>   File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\webcam_demo.py", line 20, in main
>     model_cfg, model_outputs = posenet.load_model(args.model, sess)
>   File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\posenet\model.py", line 42, in load_model
>     convert(model_ord, model_dir, check=False)
>   File "A:\Python\Scripts\Posenet-Forked -- OGCode\posenet-python-master\posenet\converter\tfjs2python.py", line 198, in convert
>     initializer_nodes="")
>   File "A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 361, in freeze_graph
>     checkpoint_version=checkpoint_version)
>   File "A:\Python\lib\site-packages\tensorflow\python\tools\freeze_graph.py", line 190, in freeze_graph_with_def_protos
>     var_list=var_list, write_version=checkpoint_version)
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 835, in __init__
>     self.build()
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 847, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 885, in _build
>     build_restore=build_restore)
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 489, in _build_internal
>     names_to_saveables)
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 362, in validate_and_slice_inputs
>     for converted_saveable_object in saveable_objects_for_op(op, name):
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 223, in saveable_objects_for_op
>     yield ResourceVariableSaveable(variable, "", name)
>   File "A:\Python\lib\site-packages\tensorflow\python\training\saving\saveable_object_util.py", line 95, in __init__
>     self.handle_op = var.op.inputs[0]
> IndexError: tuple index out of range
> >>> 
> ```

getting the same error even after migrating to tf 2 , did anyone find any solution?

**Comment by abhi9rocks** [comment]
Still getting the same error even after migrating to tf 2 , did anyone find any solution? Please help! Tensorflow==2.4.1 tensorflow-gpu==2.4.1
![2021-05-21](https://user-images.githubusercontent.com/48823353/119087249-789bd680-ba24-11eb-8f42-443f25927e63.png)

**Comment by abhi9rocks** [comment]
Still getting the same error even after migrating to tf 2 , did anyone find any solution? Please help !!!!
tensorflow==2.4.1
tensorflow-gpu==2.4.1
![2021-05-21 (1)](https://user-images.githubusercontent.com/48823353/119087558-f19b2e00-ba24-11eb-9f8e-179bc25508d9.png)
