### ISSUE TITLE
tflite model can not inference when use tensorflow op

### ISSUE THREAD

**Issue by zhaohb** [tensorflow/tensorflow#46580]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ubuntu 18.04
- TensorFlow installed from (source or binary):
- source
- TensorFlow version (use command below):
- 2.4.0
- Python version:
- 3.6.0
- Bazel version (if compiling from source):
- 3.1.-

when I convert a tf model to tflite and use tensorflow op with
```python
     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                          tf.lite.OpsSet.SELECT_TF_OPS]
     converter.allow_custom_ops = True
```
and I managed to get the tflite file, now I want to use the TFlite model for inference.
I add "//tensorflow/lite/delegates/flex:delegate" in tflite_cc_shared_object deps, and rebuild tenosrflowlite lib:
```shell
bazel build --config=monolithic --define=with_select_tf_ops=true -c opt //tensorflow/lite:libtensorflowlite.so
```
and I copy libtensorflowlite.so to /usr/lib.

then, Inference program was compiled using g++, the compilation was successful, an executable program TFlite was generated,I use the ldd command to view the libraries used by tflite:
```shell
	linux-vdso.so.1 (0x00007ffe09fb1000)
	libtensorflowlite.so => /usr/lib/libtensorflowlite.so (0x00007f4017d84000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f40179fb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f40177e3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f40173f2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4017054000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4016e4e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4016c46000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4016a27000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b71a930000)
```
I executed the tflite executable：
```shell
./tflite
```
but I get error:
```shell
ERROR: Op builtin_code out of range: 129. Are you using old TFLite binary with newer model?
ERROR: Registration failed.

Segmentation fault (core dumped)
```

Which step went wrong?

**Comment by zhaohb** [comment]
@thaink @ravikyram @abattery  who can help me？Am I doing the right thing？

**Comment by abattery** [comment]
You need to build your binary with TFLite build with the same or newer version of the TensorFlow that were used for the converter. I doubt that your TFLite model is converted by the tf-nightly but your inference program is based on the 2.4.0 verison.

**Comment by mohantym** [comment]
Hi @zhaohb ! Have you checked with above [comment](https://github.com/tensorflow/tensorflow/issues/46580#issuecomment-766452524) ? Thanks!

**Comment by zhaohb** [comment]
@mohantym reply was late，I did not verify it. I changed to other way to inference.
