### ISSUE TITLE
Tensorboard not loading scalars with reload arrow button

### ISSUE THREAD

**Issue by DJJD17** [tensorflow/tensorflow#46581]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): N/A
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1.106
- GPU model and memory: NVIDIA GeFroce RTX 2070, 32GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Using Jupyter Notebook, Tensorboard will not load scalars from logs.  Will not work at all.  I click the reload button on the orange header of Tensorboard and nothing happens.  Nothing... just updates the last reload date and time.  I have confirmed that the temporary files are created and that there are event files within the test folder within the temporary files.  I do not have tensorflow installed.  I have python 3.7.9, numpy, pandas, matplotlib, tb-nightly, pillow, torch.

**Describe the expected behavior**
I expected to see graphs of scalars and data that is saved in the loggers.  It does not anything.

**Standalone code to reproduce the issue**
%pylab inline
import torch
%load_ext tensorboard
import torch.utils.tensorboard as tb
import tempfile
log_dir = tempfile.mkdtemp()
%tensorboard --logdir {log_dir} --reload_interval 1
logger = tb.SummaryWriter(log_dir+'/test', flush_secs=1)
logger.add_scalar('first/number', 0, global_step=0)
logger.add_scalar('first/number', 1, global_step=1)

![Capture](https://user-images.githubusercontent.com/72282737/105374384-45a81a00-5bcd-11eb-99dc-359d80ea0b4b.PNG)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@DJJD17 I ran your code in a colab and can see the graph. Can you please check this [gist](https://colab.research.google.com/gist/jvishnuvardhan/7abe95afbce80f947380a8cdff4a45a1/untitled78.ipynb) and let us know if I am missing anything here. Thanks!

**Comment by DJJD17** [comment]
Thank you

I was able to get it to work in colab. But I simply cannot get it to run on my laptop. It’s a Windows 10 Alienware R15. I have tried it with tb-nightly  by itself and tensorflow by itself. i can’t get it to work and I am highly confused. The laptop is brand new. 

Your thoughts?
Jeff

**Comment by jvishnuvardhan** [comment]
@DJJD17 Sorry for the late response. This is more related to TensorBoard, so can you please open this issue in [`TB repo`](https://github.com/tensorflow/tensorboard/issues). That repository has TB experts who can resolve your issue faster. In this repo, we deal `TensorBoard` callback under `tf.keras`. Thanks!

Please close the issue here and open a new issue (with the same content) in TB repo. Thanks!
