### ISSUE TITLE
Jupyter kernel restarts/crashes when importing Tensorflow, 'ModuleNotFoundError: No module named 'tensorflow' in Python CLI

### ISSUE THREAD

**Issue by oresttokovenko** [tensorflow/tensorflow#46583]
**System information**
Using an M1 MacBook

I cannot use environment capture because the package is not being detected. I have tried the following: restarting computer, reinstalling Conda, reinstalling individual packages, installing using different package managers, setting up new environments, using different versions of python in different environments. It was working before and then suddenly stopped. I have seen reports of it being a memory issue, but it never occurred before, and I have 16GB of RAM, it should be more than enough. 

**Describe the current behavior**

Jupyter kernel restarts/crashes when importing Tensorflow, 'ModuleNotFoundError: No module named 'tensorflow' in Python CLI

**Describe the expected behavior**

For it to import normally

Below is a video of the behaviour. 

https://drive.google.com/file/d/11hCwbneKVdx0srZN9YxCyyIwDE8BKKQN/view?usp=sharing

<img width="724" alt="Screen Shot 2021-01-21 at 10 02 34 AM" src="https://user-images.githubusercontent.com/51058259/105384701-c9630600-5bcf-11eb-9f2c-53cb693ddf88.png">
<img width="723" alt="Screen Shot 2021-01-21 at 10 02 57 AM" src="https://user-images.githubusercontent.com/51058259/105384741-d7b12200-5bcf-11eb-850a-9a47cfb3c8ea.png">

**Comment by ravikyram** [comment]
@oresttokovenko 

Did you install Tensorflow before importing by (`pip install tensorflow`). Also refer this [SO link](https://stackoverflow.com/questions/46568913/tensorflow-import-error-no-module-named-tensorflow) and see if it helps you.
Also, check whether your cpu supports AVX instructions.Please, see hardware requirements from [here](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).Thanks!

**Comment by oresttokovenko** [comment]
@ravikyram I solved the problem by going at it through a different route. I installed miniforge3 instead of Miniconda and used the native apple silicon Tensorflow. I'm still not sure what caused regular Tensorflow to break but my new one works now.
