### ISSUE TITLE
What is mac osx tensorflow=2.0.0 equivalent to in windows 64bit?

### ISSUE THREAD

**Issue by moonj94** [tensorflow/tensorflow#46586]
I have a mac book pro and I've been using tensorflow 2.0.0, but my lab computer is a windows (likely 64bit). I want to make sure that this lab computer has the equivalent package as my mac. Can anyone tell me which tensorflow version for windows is equivalent to mac osx 2.0.0?

**Comment by steventrouble** [comment]
If I understand correctly, the versions should be the same regardless of which operating system you use.

**Comment by ymodak** [comment]
TF is tested and supports various major 64-bit operating systems.
See https://www.tensorflow.org/install
So you can install TF on windows in the same manner as you did for macOS using `pip`.
`pip install tensorflow==2.0.0`
On a side note you can also setup gpu support on your windows if have following [system configuration](https://www.tensorflow.org/install/gpu#hardware_requirements).
