### ISSUE TITLE
TFLite from file descriptor on Android 11

### ISSUE THREAD

**Issue by danielzgtg** [tensorflow/tensorflow#46593]
**System information**
- TensorFlow version (you are using): Likely https://github.com/mozilla/tensorflow/tree/23ad988fcde60fb01f9533e95004bbc4877a9143
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

This issue is a continuation of mozilla/DeepSpeech#3507. TFLite is used in the app, but the model is provided by the user and usually in `/sdcard/Download`.

Currently, TFLite accepts arrays or file paths. With Android's scoped storage and SAF, it's hard to use file paths to the external storage without either compatibility edge cases or overly invasive permissions. On Android 10, I could use the workaround of converting the file descriptor I received from Android to a path like `"/proc/self/fd/" + fd`. On Android 11, that stopped working. It seems to be no longer possible to open a file under `/proc/self/fd/` that points to external storage without requesting the read permission I was hoping to avoid.

I would like TFLite to be compatible with Android 11's external storage. The following solutions come to mind:

- Duplicate `tflite::FlatBufferModel::BuildFromFile` into `tflite::FlatBufferModel::BuildFromFileDescriptor`
- Add https://stackoverflow.com/a/59004193/10477326
- On Android builds, manually add a conditional to detect the `/proc/self/fd/` prefix and use a `dup` instead of a `fopen`

**Will this change the current api? How?**

Not unless we choose the `BuildFromFileDescriptor` solution.

**Who will benefit with this feature?**

Developers and users of apps that:

- Explore, educate, or demonstrate machine learning, and
- Run on up-to-date Android versions, and
- Load user-supplied models, and
- Usually take large (~1 GiB) models that reside on external storage, which we cannot afford to read into memory or duplicate on disk, and
- Would like to respect privacy by obeying scoped storage and SAF by not requesting file permissions to everything but rather allow the user to pick only the files necessary

**Comment by thaink** [comment]
@jdduke is better to just if the benefit is big enough to support this feature.

But if it is blocking you, there are definitely some workaround:
- If the path can be fix, you can try to put the model to /data/local/tmp
- If you select the model using UI, you can copy the model to the app's internal storage and get it path

**Comment by danielzgtg** [comment]
> justify if the benefit is big enough to support this feature

If you don't want to increase the API surface, we can just go with the solution with the tiny check to make `/proc/self/fd` use `dup`.

> if it is blocking you

It was never blocking me. It was just that whatever workaround I applied would be inconvenient to the end-user.

> /data/local/tmp

That path requires ADB to access. However, I am trying to remove the requirement for ADB.

> If you select the model using UI

Yes, that I what I was doing on Android 10, and plan to continue doing

> can copy the model to the app's internal storage

Duplicating a gigabyte of data isn't nice to users whose 16 GB phones are already running out of storage

**Comment by thaink** [comment]
As I see, this will be mainly used for experimental and users are mostly engineers. Above concerns might not really problematic in those cases.

**Comment by jdduke** [comment]
An API addition seems like a reasonable request, though I'd also be OK with the temporary workaround in the provided StackOverflow link (though that might be somewhat annoying to test?). Do you have a strong preference? If folks had already been using the /proc/self/fd/ workaround, I could see some value in avoiding the breakage, though I suspect that approach will always be somewhat brittle, and better to just make FD usage a first-class part of the API.

**Comment by danielzgtg** [comment]
> As I see [...]

Alright. I think I'm going to go for the approach where I copy to internal storage. A fix in TFLite will take a month or two to propagate through my dependencies and reach me anyway.

I can't think of any myself, but other users might have different use cases for this. A lot of stuff on Linux is moving towards file descriptors, and file descriptors are more general than files. Adding this feature would let users enjoy the generality.

> though that might be somewhat annoying to test?

Getting a file descriptor is the easy part. In `bash`, we can just `exec 3<>/path/to/file`. In C, we can similarly open the file without passing `O_CLOEXEC`.

The hard part is reproducing what Android does with `/proc/self/fd`. I have no clue how Android does that (especially since it wasn't the case on Android 10), and I couldn't simulate something on my desktop Linux box. I would like to find out.

>  /proc/self/fd/ workaround, I could see some value in avoiding the breakage

This would indeed avoid having to request changes in the libraries that wrap TFLite. However, ...

> suspect that approach will always be somewhat brittle

This is a problem. It feels a bit too magic. I only suggested the `/proc/self/fd` approach in case we didn't want to increase the API surface, but it seems like this is no longer the case.

**Comment by jdduke** [comment]
Thanks for the reply. I'm happy to review a pull request for the proposed API addition (we might need to also include an optional offset/length for completeness?), otherwise I can try to get something in within the next week or so.

**Comment by jdduke** [comment]
Another question @danielzgtg, if we added some helper Java APIs for feeding in the model via a `FileDescriptor`  (e.g., from a `ContentResolver`, which allows mmap'ing), would that also be useful? I noticed your example is using the Java API, and I think we can find a cleaner way of doing this from Java as well.

**Comment by danielzgtg** [comment]
> happy to review

I am quite busy and I work more in Java than C++, so you might get to this sooner.

> would that also be useful

That would be helpful if the implementation would work. However, I see `FileDescriptor` (as opposed to `ParcelFileDescriptor`) doesn't have a public method to get the integer. Neither is the particular native API said to be stable. This would increase the coupling with either Android or Oracle's implementation. I'm not sure having this increased coupling and specific dependency is worth it.

> noticed your example is using the Java API

No, I myself am not using the Java bindings, even though my code is in Java/Kotlin. I am indirectly using TFLite through the DeepSpeech project, whose Android app I'm working on. https://github.com/mozilla/DeepSpeech/blob/f27908e7e3781b4ebed228a27439d9988b13a5c7/native_client/java/libdeepspeech/src/main/java/org/deepspeech/libdeepspeech/DeepSpeechModel.java#L33 https://github.com/mozilla/DeepSpeech/blob/f27908e7e3781b4ebed228a27439d9988b13a5c7/native_client/deepspeech.cc#L266

However, I think the majority of people are going to use the Java API. It would indeed be nice if there was a vendor-independent improvement to TFLite's Java API.
