### ISSUE TITLE
Loading model from GCS takes longer than copying it to local and then loading the model

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tensorflow#46597]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): x86_64 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7

**Describe the current behavior**
```
new_model = tf.keras.models.load_model(
 'gs://benchmarking_test/bert_en_uncased_L-12_H-768_A-12_2' 
)
```
takes about 30min or so.
whereas, following works in less than a minute
```
!gsutil cp -r gs://benchmarking_test/bert_en_uncased_L-12_H-768_A-12_2 local_path
new_model = tf.keras.models.load_model(
 'local_path' 
)
```

**Describe the expected behavior**
Both should take a similar time.

**Comment by ravikyram** [comment]
@sumitbinnani 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.
Also, can you try with latest stable version TF 2.4 otr Nightly version and see if you are facing the same issue. There are lot of performance improvement in latest versions of TF.

Thanks!
