### ISSUE TITLE
tf.keras.preprocessing.image_dataset_from_directory includes hidden dirs as classes

### ISSUE THREAD

**Issue by jhihn** [tensorflow/tensorflow#46595]
I am using google colab, and filed this as an issue there but they told me to file it here instead. https://github.com/googlecolab/colabtools/issues/1824

 It seems that google colab uses . prefixed hidden directories `.ipynb_checkpoints`, which image_dataset_from_directory thinks is a class.

Describe the current behavior:
When passing class names it produces the error:
ValueError: The class_names passed did not match the names of the subdirectories of the target directory. Expected: ['.ipynb_checkpoints', 'no_skip', 'skip'], but received: ['no_skip', 'skip']
When not passing class names it picks up 3 classes, not two.

Describe the expected behavior:
tf.keras.preprocessing.image_dataset_from_directory(...) should not include hidden .directories.

The web browser you are using (Chrome, Firefox, Safari, etc.):
Not relevant

Link (not screenshot!) to a minimal, public, self-contained notebook that
reproduces this issue (click the Share button, then Get Shareable Link):
https://colab.research.google.com/drive/1sI2Zk7-YjIOg3nRDyHtUtczwjevQfdPF?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d5813effbc7af9ea285b1933d908b8a7/46595.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@jhihn It looks for a directory structure (as shown [here](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory?version=nightly)) to infer data and labels. I think `.ipynb_checkpoints` should not be saved in the data directory. Thanks!

**Comment by jhihn** [comment]
I didn't save .ipynb_checkpoints there. The Google Colab did. I don't have control over that. And I think it should NOT include hidden (.) directories anyway. .ipynb_checkpoints would not appear in a normal unix directory listing unless you used the "-a" option.

**Comment by jvishnuvardhan** [comment]
@jhihn Colab save notebooks under `MyDrive/Colab Notebooks`. In this [gist](https://colab.research.google.com/gist/jvishnuvardhan/3f616896ffa3696c9bd1d834a05eec18/46595.ipynb), we cannot reproduce the issue. If we manually create `ipynb_checkpoints` under the `data` where you have training files, then it will throw an error. 

I am not sure about inner details about the `tf.keras.preprocessing.image_dataset_from_directory` and how to implement the same to exclude hidden files without affecting other modules. If you think you can implement it without breaking other modules, then please feel free to contribute through Pull Request. Thanks!

**Comment by jhihn** [comment]
So it's using Python's os.walk() function which according to https://www.tutorialspoint.com/python/os_walk.htm
includes the . files (hidden)

This us undesired and is covered in this stackoverflow:

https://stackoverflow.com/questions/13454164/os-walk-without-hidden-folders

**Comment by sscast** [comment]
Hi, I'm having the same problem on Jupiter lab. Is there any workaround for this?

**Comment by tilakrayal** [comment]
@jhihn ,
`tf.keras.preprocessing.image_dataset_from_directory` is deprecated from `Tensorflow 2.9` version.Could you prefer loading data with [tf.keras.utils.image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory), and transform the output [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) with pre-processing layers.
If you still feel this feature needs to be added, feel free to open a new feature request. Thank you!

**Comment by volkfox** [comment]
The problem still exist after renaming to tf.keras.utils.image_dataset_from_directory

$ python train.py 
Traceback (most recent call last):
  File "/Users/dkh/Downloads/Data-Centric-AI-Competition/internal-competition/train.py", line 25, in <module>
    train = tf.keras.utils.image_dataset_from_directory(
  File "/Users/dkh/miniforge3/lib/python3.9/site-packages/keras/utils/image_dataset.py", line 192, in image_dataset_from_directory
    image_paths, labels, class_names = dataset_utils.index_directory(
  File "/Users/dkh/miniforge3/lib/python3.9/site-packages/keras/utils/dataset_utils.py", line 75, in index_directory
    raise ValueError(
ValueError: The `class_names` passed did not match the names of the subdirectories of the target directory. Expected: ['.gitignore', 'cat', 'croissant', 'dog', 'muffin'], but received: ['cat', 'dog', 'muffin', 'croissant']

**Comment by volkfox** [comment]
@jhihn  can you please reopen?

**Comment by tilakrayal** [comment]
@volkfox,
Could you please feel free please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thank you!
