### ISSUE TITLE
ISSUES.md link broken

### ISSUE THREAD

**Issue by danielzgtg** [tensorflow/tensorflow#46592]
## URL(s) with the issue:

Most files under https://github.com/tensorflow/tensorflow/tree/f2d8cfe09234329e14c98798540f146bd94558e0/.github/ISSUE_TEMPLATE

## Description of issue (what needs changing):

The links to the [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md) are broken.

### Clear description

For example, why should someone use this method? How is it useful?

I don't know why there is a separate GitHub policy aside from the CONTRIBUTING.md, but it seems important and people are supposed to read it

### Correct links

Is the link to the source code correct? No

### Parameters defined

Are all parameters defined and formatted correctly? N/A

### Returns defined

Are return values defined? N/A

### Raises listed and defined

Are the errors defined? N/A

### Usage example

Is there a usage example? N/A

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? N/A

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? No

**Comment by amahendrakar** [comment]
@danielzgtg,
Thank you for reporting the issue. The change has been requested in [#46601](https://github.com/tensorflow/tensorflow/pull/46601) and the links will be updated upon merging.

**Comment by danielzgtg** [comment]
This bug is still in the repo. #46601 was closed without merging. It mentioned something about moving the files instead, but there is no newly linked PR or commit

**Comment by amahendrakar** [comment]
@danielzgtg,
As mentioned in PR #46601, the directory where the GitHub policy page currently exists is being removed internally.

Once it is reverted, the broken links should work as intended. Thanks!

**Comment by mihaimaruseac** [comment]
This should be done, afaik. If not, please list the broken link and the URL of the page where the link is broken.
