### ISSUE TITLE
Deleting a model and clearing the session if other models are still loaded and in use

### ISSUE THREAD

**Issue by haimat** [tensorflow/tensorflow#46608]
In my Python application I load several TF 2.4 / Keras models in parallel and use their `predict()` functions in separate threads. The single GPU in the machine is locked by a Python `Lock`, so that these threads cannot run "their" TF models at the same time. Now at some point a thread can decide to delete its currently loaded TF model (via Python's `del` command) and load another one (via `tensorflow.keras.models.load_model()`). However, in that case the other threads with their loaded TF models must not be affected.

Now I want to free all memory when I delete a model in a thread and load another model. So I thought about calling `tf.keras.backend.clear_session()` after deleting a model. But it seems that is not an option in my case, since other models are still loaded and in use, as described above.

I might put all these models into their own processes (instead of using threads), but then I might run into the problem that I cannot lock and make use of that single GPU from multiple processes in parallel. So is there another, "official" method to properly free all memory after deleting a TF/Keras model in such a multi-model setup?

**Comment by Saduf2019** [comment]
@haimat 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Please move this to closed status if ticket is created in Stackoverflow.

**Comment by haimat** [comment]
@Saduf2019
I have [asked this question on StackOverflow](https://stackoverflow.com/questions/65723891/how-to-free-tf-keras-memory-in-python-after-a-model-has-been-deleted-while-othe) as well, however, I have not received a solution or even valid answer so far. Even though I have added a bounty to my question. Is this really such an unusual request that nobody knows the answer to this?

**Comment by jvishnuvardhan** [comment]
@haimat Is this related to [this issue](https://github.com/tensorflow/tensorflow/issues/46628).
Can you try running against `tf-nightly` and let us know whether it is still an issue for you. Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by haimat** [comment]
@jvishnuvardhan Hi, are you sure you linked the correct issue here?

**Comment by jvishnuvardhan** [comment]
@haimat Sorry. I was working on the other issue and pasted by mistake. [Here](https://github.com/tensorflow/tensorflow/issues/45453) is the correct issue. Please let me know if you tried running your code with `tf-nightly`. 

Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by haimat** [comment]
Ok thanks, looks fine now.
