### ISSUE TITLE
Broken link in doc

### ISSUE THREAD

**Issue by fawazahmed0** [tensorflow/tensorflow#46603]
**Link to Doc:**

https://www.tensorflow.org/tutorials/audio/simple_audio

![-2021-jan-22-008](https://user-images.githubusercontent.com/20347013/105484563-87ba8400-5cd1-11eb-8daf-370b3601ff0f.jpg)

**Dead Link(Name of Link: contributing five minutes of your own voice):**

https://aiyprojects.withgoogle.com/open_speech_recording

![-2021-jan-22-010](https://user-images.githubusercontent.com/20347013/105484575-8b4e0b00-5cd1-11eb-91aa-283abea5e457.jpg)

**Comment by Harsh188** [comment]
AYI Projects is no longer accepting contributions.
