### ISSUE TITLE
Subclassed tf.keras.Model can't access intermediate layer's output

### ISSUE THREAD

**Issue by cecabert** [tensorflow/tensorflow#46605]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
*Yes*
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
*Google Colab*
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
*No*
- TensorFlow installed from (source or binary):
*Binary, pip install*
- TensorFlow version (use command below):
*2.4*
- Python version:
*Colab's version: 3.6.9"
- Bazel version (if compiling from source):
*N/A - Colab*
- GCC/Compiler version (if compiling from source):
*N/A - Colab*
- CUDA/cuDNN version:
*N/A - Colab without GPU*
- GPU model and memory:
*N/A - Colab without GPU*

**Describe the current behavior**

Accessing internal layer's output of a sublcassed `Model` leads to `AttributeError: Layer XXX has no inbound nodes` exception. The code to reproduce the issue given below or avaiable [here](https://colab.research.google.com/drive/1w5p68LvzwPnYKzpDm6HzsRsRXlBp35hq?usp=sharing) 

```python
import tensorflow as tf

class MyModel(tf.keras.Model):

  def __init__(self, name='MyModel', **kwargs):
    super(MyModel, self).__init__(name=name, **kwargs)
    self.dense1 = tf.keras.layers.Dense(4, name='layer1')
    self.dense2 = tf.keras.layers.Dense(2, name='layer2')

  def call(self, inputs, training=None, mask=None):
    x = self.dense1(inputs)
    return self.dense2(x)

x_in = tf.keras.layers.Input(shape=(2,), dtype=tf.float32)
my_model = MyModel()
y = my_model(x_in, training=False)
mid_feat = my_model.get_layer('layer1').output
```

This happens when using tensorflow `2.4`, however it does work with `2.3`. Something must have changed between the two versions. 

**Describe the expected behavior**

The old behaviour, where we can access internal layer's outputs from a model whether it has been build with `functional` API or sublclassed `Model`.

**Comment by Saduf2019** [comment]
I ran the issue on tf 2.3,24 and nightly, am able to replicate the issue please find the [gist here](https://colab.research.google.com/gist/Saduf2019/1c88c7d7eba5a379de97c01a5b13154c/untitled507.ipynb).

**Comment by cecabert** [comment]
Any updates on this ?

**Comment by tomerk** [comment]
This is intended behavior. (It only happened to work in certain situations in the past, but came at the cost of other bugs).

When you use a subclassed model in a functional model it will not inline the layers of the subclassed model into the outer functional model.  So, it it doesn't make sense to access sub-layer inputs/outputs in the functional style.

In the past it would sort-of inline it in a way that could actually cause bugs by e.g. not always correctly capturing variables/layers/call arguments of the subclassed model. (This could become especially problematic if you tried to use the inner layer's outputs to construct a new functional model)

**Comment by cecabert** [comment]
@tomerk thanks for the feedback.

> When you use a subclassed model in a functional model it will not inline the layers of the subclassed model into the outer functional model. So, it it doesn't make sense to access sub-layer inputs/outputs in the functional style.

Does it means there is no way to access intermediate layes with subclassed model or reuse part of the model in the functional style ?

**Comment by tomerk** [comment]
If by intermediate layer access you mean via the functional model layer intermediate inputs/outputs accessing for an already-made model, that is correct. We may come up with a solution at some point in the future for slicing into nested functional models, but it's less clear we'll be able to do so for subclass models in the general case. (Subclass models can support things that the functional api can't represent).

Another option to try though (if this would suit your needs), is:
- You can make your nested functional/subclass model output *all* of its intermediate outputs that you will need, then only use some of them in your outer functional model. I'm not 100% sure off the top off my head, but I think you may then be able to get access to these unused intermediate outputs & use them for something else.

**Comment by lidamsoukaina** [comment]
@cecabert I was able to reproduce the error. I added double underscores to the method **call**, and the problem was resolved.
Here is the updated code:
```
  import tensorflow as tf

  class MyModel(tf.keras.Model):

      def __init__(self, name='MyModel', **kwargs):
          super(MyModel, self).__init__(name=name, **kwargs)
          self.dense1 = tf.keras.layers.Dense(4, name='layer1')
          self.dense2 = tf.keras.layers.Dense(2, name='layer2')

      def __call__(self, inputs, training=None, mask=None):
          x = self.dense1(inputs)
          return self.dense2(x)

  x_in = tf.keras.layers.Input(shape=(2,), dtype=tf.float32)
  my_model = MyModel()
  y = my_model(x_in, training=False)
  mid_feat = my_model.get_layer('layer1').output
```
