### ISSUE TITLE
custom hardware support for tensorflow

### ISSUE THREAD

**Issue by benjamin7007** [tensorflow/tensorflow#46618]
Tensorflow currently has support for CPU and GPU devices, adding a new device seems possible but the documentation is out of date. The most recent activity on this seems to be from git hub issue: https://github.com/tensorflow/tensorflow/issues/4359

Is there more current documentation or is there a best practice for adding a device? Has anyone been through the process of adding custom ML hardware under tensorflow?

**Comment by mihaimaruseac** [comment]
See https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md and https://github.com/tensorflow/community/blob/master/rfcs/20200612-stream-executor-c-api.md and https://github.com/tensorflow/community/blob/master/rfcs/20190305-modular-tensorflow.md

**Comment by bhack** [comment]
Check also https://github.com/tensorflow/tensorflow/pull/45784
https://github.com/tensorflow/tensorflow/pull/43611

**Comment by mohantym** [comment]
Hi @benjamin7007 !
Has the[ pluggable device documentation](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md) addressed your need for custom hardware support.

Manufacturers are developing the custom plugin for their community.  Attached[ relevant documentation](https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html) on creating Plugins for any hardware.
For e.g [Mac M1 plugin](https://developer.apple.com/metal/tensorflow-plugin/) from Apple. 

Please post on [TF forum](https://discuss.tensorflow.org/) for further assistance.

Thank you!
