### ISSUE TITLE
Object Detection API to Tensorflow Lite

### ISSUE THREAD

**Issue by leo513** [tensorflow/tensorflow#46610]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.4.0
- CUDA 11.0

I have successfully trained my own model using the Object Detection API. 
As a pre-trained model I used ssd_resnet50v1_fpn_640x60.
The detection works fine.

Now I want to convert the trained model to Tensorflow Lite.
I used export_tflite_graph_tf2.py and after that the TensorFlow Lite-Konverter-API:

```
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory from export_tflite_graph_tf2.py
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

The model.tflite was succesfully created but unfortunately when I run the detection, nothing is detected.
tflite-runtime: 2.5.0
I used this guide https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/Raspberry_Pi_Guide.md and with the coco_ssd_mobilenet_v1_1.0_quant_2018_06_29 everything works.

I got no errors, just no detection with my own model at all.
does anyone have an idea what this can be due to?

**Comment by lintian06** [comment]
Can you check error messages in `adb logcat`? I guess randomly picking one model in Object Detection API to convert to TFLite won't work directly. As different models are likely to have different model input and output shapes, you have to change the related inference code in general.

**Comment by leo513** [comment]
You're right.
I tried it again with the mobilnet_v2_FPNLite an the conversion worked just fine.
Thank you :)

**Comment by amahendrakar** [comment]
> I tried it again with the mobilnet_v2_FPNLite an the conversion worked just fine.

@leo513,
Thank you for the update. Please feel free to close the issue if resolved.
