### ISSUE TITLE
ExponentialMovingAverage Does Not Work Under tf.function (TF 2.4)

### ISSUE THREAD

**Issue by ChanZou** [tensorflow/tensorflow#46615]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The average variable becomes None and seems like the Tensor is not tracked.
**Describe the expected behavior**
Tensor being properly tracked and valid average value being returned.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Colab: https://colab.research.google.com/drive/17W7CVfDqx-HTbcRMphhQYg6WCq-ELg_K?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Autograph logs show that the function is traced twice. While the first pass shows everything alright, including the tensor being properly tracked, the second pass seems not to be the case although the generated graph has been reused.

**Comment by amahendrakar** [comment]
@ChanZou,
I do not have access to the Colab Notebook you have linked. Could you please provide the required permissions to view the files? Thanks!

**Comment by ChanZou** [comment]
> @ChanZou,
> I do not have access to the Colab Notebook you have linked. Could you please provide the required permissions to view the files? Thanks!

Terribly sorry, this link should be open to everyone: 
[colab](https://colab.research.google.com/drive/17W7CVfDqx-HTbcRMphhQYg6WCq-ELg_K?usp=sharing)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1becf068751c41e85591907fcf07fa99/46615.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.6 and let us know if you are facing the same error. Thanks!
