### ISSUE TITLE
ERRORS 

### ISSUE THREAD

**Issue by CaptnJake** [tensorflow/tensorflow#46613]
- Windows 10 64-bit 
- python 3.8.3 and pip 20.3.3

every time I try to install I get the same error messages:
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow

im kind of at a loss for what to do, any help would be appreciated

**Comment by mihaimaruseac** [comment]
Can you please post the full error message? Does it list some TF versions that it tries?

**Comment by CaptnJake** [comment]
> Can you please post the full error message? Does it list some TF versions that it tries?

that is the whole error message. I key in pip3 install tensorflow like many tutorials suggest and all I get is that.

**Comment by mihaimaruseac** [comment]
Can you fill in the issue template and also post a full output of `pip install` command?

**Comment by Saduf2019** [comment]
@CaptnJake 
Could you please update pip using the below commands and check if you are still facing the same issue?

```pip install --upgrade pip```
```pip install tensorflow```
Please ensure your tensorflow version is compatible with the python version used, TF 2.4 supports python from 3.6-3.8 . Please, refer the [document](https://www.tensorflow.org/install/source#cpu),Also, could you check if you are using the 64 bit version of Python. TensorFlow is tested and supported only on 64-bit systems. 

Please refer to similar issues, #44615, #45147, #44775
