### ISSUE TITLE
Operator Softsign and Softplus are not supported by the standard TensorFlow Lite runtime

### ISSUE THREAD

**Issue by bugreporter450** [tensorflow/tensorflow#46626]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:a GNU/Linux system with Linux kernel 4.15.0 on 1 6-core 3.60GHz Intel Core CPU i7-6850K with 64 GB RAM equipped with a NVIDIA Corporation GP102 GPUs
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):tensorflow2-GPU
- Python version:3.6

**Describe the current behavior**
When I converted the trained hdf5 model to tflite, the following operator non-support occurred ：Softsign

**Describe the expected behavior**
The hdf5 model should be successfully converted to the format of tflite.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
batch_size = 80
epochs = 171
num_classes = 10
import os
save_dir = 'model'
model_name = 'model.h5'
import keras as keras
(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()
img_rows, img_cols = x_train.shape[1], x_train.shape[2]

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

import keras as keras
model = keras.models.Sequential()
model.add(keras.layers.ThresholdedReLU(theta=0.3514439122821289))
model.add(keras.layers.LeakyReLU(alpha=0.4855740853866919))
model.add(keras.layers.AveragePooling2D(pool_size = (1, 2), padding='same'))

model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(num_classes, activation='softsign'))
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=keras.optimizers.Adadelta(), metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))

model_path = os.path.join(save_dir, model_name)
model.save(model_path)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: AVERAGE_POOL_2D, CAST, FULLY_CONNECTED, GREATER, MAXIMUM, MUL. Here is a list of operators for which you will need custom implementations: Softsign.
```

**Comment by abattery** [comment]
Please consider enabling Softsign operator with TF select option. https://www.tensorflow.org/lite/guide/ops_select

**Comment by Saduf2019** [comment]
@bugreporter450 
I ran the code on [colab](https://colab.research.google.com/gist/Saduf2019/df1b5da9008a5c9dbd3a3033bf869644/untitled507.ipynb) and do not face any errors, could you please refer to above comment [by abattery] and let us know.

**Comment by hampengit** [comment]
Hi all, 

We have the same problem converting our model to tensorflow lite during quantisation stage. Is Softplus being supported now? if not, what would be the solution to convert models with Softplus ops? 
Thanks
