### ISSUE TITLE
TFLite outputs different inference results for the same input

### ISSUE THREAD

**Issue by BernardoGO** [tensorflow/tensorflow#46620]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.3.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

**Notebook Link: https://github.com/BernardoGO/tflite_convert_bug/blob/main/BiLSTM%20Conversion%20Test.ipynb**

```
converter = tf.lite.TFLiteConverter.from_keras_model(new_model)
#converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
#converter.allow_custom_ops=True
tflite_model = converter.convert()

open("tf_test.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
INFO:tensorflow:Assets written to: /tmp/tmp4xjrqwpb/assets
Out[9]: 476052
```

**Graph Definition**

```
new_model = Sequential()
new_model.add(Input(name='input', batch_size=1, shape=(925, 3)) )
new_model.add(Dense(8))
new_model.add(LSTM(64, return_sequences=True))
new_model.add(LSTM(64, return_sequences=True))
new_model.add(LSTM(64, return_sequences=True))
new_model.add(LSTM(64, return_sequences=True))
new_model.add(Activation('softmax', name='softmax'))

new_model.summary()
```

**Failure details**

- Producing wrong results and/or decrease in accuracy

The model was converted successfully, but the output differs for each execution. The same does not happen for the non-converted TensorFlow model, which always yields the same results.
I've attached a notebook that shows how to reproduce the problem and how to detect it. After a few runs, the output gets more consistent.
It only happens when using LSTMs and seems to get even worse when using return_sequences=True.

**Any other info / logs**

- I've used this function to check if the output is the same after each execution:
```
def equal(tensor1, tensor2):
    for i, j in zip(tensor1.reshape(-1), tensor2.reshape(-1)):
        if abs(i - j) > 0.001:
            return False
    return True
```

![image](https://user-images.githubusercontent.com/1606650/105568097-9fb3f700-5d15-11eb-96c7-762667033f89.png)

**Comment by renjie-liu** [comment]
Hi, This is because for tflite, the fused lstm kernel is "stateful", so you will need to reset the variable tensors, with python you can do 

```
interpreter.reset_all_variables()
```

**Comment by BernardoGO** [comment]
Thanks for your answer.
Do are you saying that in TFLite the LSTM is always stateful while in TensorFlow it should be explicitly declared?

**Comment by renjie-liu** [comment]
The fused unidirectional_sequence_lstm kernel is always stateful (if you visualize your graph).

**Comment by mohantym** [comment]
@BernardoGO ! Did you mean to write the **equal(tensor1,tensor2)**  function as below?
```
def equal(tensor1, tensor2):
    for i, j in zip(tensor1.reshape(-1), tensor2.reshape(-1)):
        if abs(i - j) > 0.001:
            return False
        else: 
            return True
```

I was getting True value even I reset the environment multiple times. Attaching gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/61d6d6eff57bc92aa5c78e9c92e99a2c/bilstm-conversion-test.ipynb#scrollTo=9_goVvjY3-pk)  and [2.7](https://colab.sandbox.google.com/gist/mohantym/bc45fc6124b3f54a21e22c6d34f41e51/bilstm-conversion-test.ipynb#scrollTo=9_goVvjY3-pk) for reference. Thank you!
