### ISSUE TITLE
Linux C library for TensorFlow 2.4.1 contains macOS dylib files

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#46629]
**Describe the problem**

I'm looking for the prebuilt TensorFlow C library for Linux (no GPU support).

I see from the [documentation](https://www.tensorflow.org/install/lang_c) that the C library is available for version 2.4.0 although there is already TensorFlow 2.4.1 out.

If I download the 2.4.0 library - the contact is correct:

```
wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz
tar xvf libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz
[ ... ]
./lib/
./lib/libtensorflow.so.2.4.0
./lib/libtensorflow_framework.so.2.4.0
./lib/libtensorflow_framework.so
./lib/libtensorflow_framework.so.2
./lib/libtensorflow.so
./lib/libtensorflow.so.2
```

Instead, if I download version 2.4.1 (I just change the URL), the content is for macOS (dylib instead of so):

```
wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.1.tar.gz
tar xvf libtensorflow-cpu-linux-x86_64-2.4.1.tar.gz
[ ... ]
./lib/
./lib/libtensorflow.2.4.1.dylib
./lib/libtensorflow_framework.2.4.1.dylib
./lib/libtensorflow_framework.dylib
./lib/libtensorflow_framework.2.dylib
./lib/libtensorflow.dylib
./lib/libtensorflow.2.dylib
```

**Comment by av8ramit** [comment]
I'm not sure how this happened but I'll take a look. I'm looking into overhauling the entire libtensorflow release so this should be resolved soon. Thanks for the issue and your patience.

**Comment by mihaimaruseac** [comment]
This should be fixed, I think.

Please reopen if that is not the case
