### ISSUE TITLE
tf.reduce_max returns wrong answers on large tensors e.g., (2048,2048,1024)

### ISSUE THREAD

**Issue by varung** [tensorflow/tensorflow#46621]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): docker run nvcr.io/nvidia/tensorflow:20.12-tf2-py3
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11
- GPU model and memory: RTX 3090, 24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Computing the max of a large 3d matrix returns the incorrect answer

**Describe the expected behavior**
I would expect the value of the function to correct!

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
for i in range(12):
    n = 2**i
    x = np.arange(n*n*1024, dtype=np.float32).reshape((n,n,1024))
    print(x.shape, np.max(x), tf.reduce_max(x).numpy())
```
```

(1, 1, 1024) 1023.0 1023.0
(2, 2, 1024) 4095.0 4095.0
(4, 4, 1024) 16383.0 16383.0
(8, 8, 1024) 65535.0 65535.0
(16, 16, 1024) 262143.0 262143.0
(32, 32, 1024) 1048575.0 1048575.0
(64, 64, 1024) 4194303.0 4194303.0
(128, 128, 1024) 16777215.0 16777215.0
(256, 256, 1024) 67108864.0 67108864.0
(512, 512, 1024) 268435460.0 268435460.0
(1024, 1024, 1024) 1073741800.0 1073741800.0

(2048, 2048, 1024) 4294967300.0 -3.4028235e+38

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by varung** [comment]
It seems there is a maximum size tensor after which tensorflow will give silently give incorrect results?
How can I avoid exceeding this limit or detect when this occurs?

**Comment by varung** [comment]
This seems to happen when the tensor input to reduce_max is greater than 4gb in size (in the case of tf.float32). 
```
In [54]: tf_sector.device
Out[54]: '/job:localhost/replica:0/task:0/device:GPU:0'

In [55]: tf.reduce_max(tf_sector[:2**31])
Out[55]: <tf.Tensor: shape=(), dtype=float32, numpy=-3.4028235e+38>

In [56]: tf.reduce_max(tf_sector[:2**30])
Out[56]: <tf.Tensor: shape=(), dtype=float32, numpy=448851.8>

In [57]: np.max(sector_rct[:2**31])
Out[57]: 655147.94

In [58]: np.max(sector_rct[:2**30])
Out[58]: 448851.8
```

**Comment by varung** [comment]
I tried the same thing in pytorch and it works correctly.
So I do not think this is a problem with my drivers, or the basic formulation of my setup.

```
In [14]: torch_sector = torch_sector.cuda()
In [15]: torch_sector.dtype
Out[15]: torch.float32
In [16]: torch_sector.device
Out[16]: device(type='cuda', index=0)
In [17]: torch_sector.max()                                                                                                                                                                 
Out[17]: tensor(856689.3750, device='cuda:0')
In [18]: sector_rct.max()
Out[18]: 856689.4
```

**Comment by amahendrakar** [comment]
@varung,
Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by varung** [comment]
I tested on tf_nightly_version:
2.5.0-dev20210122
tf.reduce_max seems to only process the first 2**30 entries of the tensor, ignoring the remainder.

**Comment by varung** [comment]
```
import numpy as np
import numpy as np

flat = np.zeros((2,2**30), dtype=np.float32)
flat[1] = 1
flat = flat.reshape(-1)
print("numpy_cpu", flat.shape, np.max(flat), np.max(flat[:2**30]))
if True:
    import tensorflow as tf
    print(tf.version.VERSION)
    tf_flat = tf.identity(flat)
    print(tf_flat.device, tf_flat.shape, tf.reduce_max(tf_flat), tf.reduce_max(tf_flat[:2**30]))
else:
    import torch
    torch_flat = torch.from_numpy(flat).cuda()
    print(torch_flat.device, torch_flat.shape, torch.max(torch_flat), torch.max(torch_flat[:2**30]))

```

`python tf_error_case.py >> output.txt
`

If I run with Tensorflow:
```
2.5.0-dev20210122
numpy_cpu (2147483648,) 1.0 0.0
/job:localhost/replica:0/task:0/device:GPU:0 (2147483648,) tf.Tensor(-3.4028235e+38, shape=(), dtype=float32) tf.Tensor(0.0, shape=(), dtype=float32)

```
If I flip the True to False to run with Torch:
```
numpy_cpu (2147483648,) 1.0 0.0
cuda:0 torch.Size([2147483648]) tensor(1., device='cuda:0') tensor(0., device='cuda:0')
```

**Comment by varung** [comment]
Sorry, I don't have time to try this on 2.4, but, since an extremely recent nightly version has the bug, there is still something to fix here.

**Comment by varung** [comment]
Ok! It turns out this minimal version was easy enough to test on colab.
https://colab.research.google.com/drive/1-A0fWC9U2Dlt8FvzVVeFb8l1TY360EiU?usp=sharing

**Comment by WindQAQ** [comment]
Related to https://github.com/NVIDIA/cub/issues/212.  TensorFlow invokes NVIDIA's cub library for scalar reduction. However, it so far only supports 32 bits indexing. In your case, `2 ** 31 > std::numeric_limits<int>::max()` and overflow to -2147483648, which means `num_items` to be reduced becomes negative or 0. Therefore, there is no reduction happending, and returns minimum float32 (-3.4028235E+38).
https://github.com/tensorflow/tensorflow/blob/79715317b315feb1687e83cccc76fe78f199ed0e/tensorflow/core/kernels/reduction_gpu_kernels.cu.h#L697-L698
https://github.com/NVIDIA/cub/blob/8128ac8489e0f2d3dd82425bac24020367f72fe8/cub/device/device_reduce.cuh#L153

**Comment by varung** [comment]
ah. How does pytorch do it? Since it seems to work correctly there.

**Comment by WindQAQ** [comment]
Pytorch instead uses its own CUDA kernel.

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Reduce.cuh

**Comment by kiancross** [comment]
Is there a workaround for this?

**Comment by varung** [comment]
renamed it back to "wrong answers", because it seems to depend on the precise roll over of the integer type. For instance, numbers > 2**32 would roll over again, may result in arbitrary undetectable answers.

**Comment by varung** [comment]
@amahendrakar this is not just v2.3, it is also v2.4 and v2.5

**Comment by amahendrakar** [comment]
Colab session crashes on running the code with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0d30b9f7acafb0f4f37d6f849e7536c2/46621.ipynb#scrollTo=ZrVlDG5bsjSA). Thanks!

**Comment by sushreebarsa** [comment]
Colab session crashes on running the code with TF v2.5,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/3c557f01da17d2c3e7e869c50c1ce857/untitled195.ipynb)..Thanks !

**Comment by sanjoy** [comment]
@sushreebarsa That crash is probably not the issue that's reported here.  The colab is crashing because it is running out of memory on an older GPU.  The bug reported here manifests when reducing large tensors, which will only fit in newer GPUs that have more than 16G of memory.

My initial hunch is that address arithmetic is going wrong somewhere; TF uses 32bit indices in many places which will overflow with large tensors.

@varung Are you running into this issue in realistic situations, or is this more of a theoretical concern at the moment?

**Comment by varung** [comment]
Yes I am running into it on a real situation on a RTX 3090. I'm switched to pytorch instead which does not have the error.

**Comment by south-ocean** [comment]
i also meet the error in tf2.11, do you have any   @sanjoy @WindQAQ @tensorflowbutler 
![image](https://user-images.githubusercontent.com/30514703/224951381-b88bcc4a-ca70-4dce-b0e2-be9bfe85e6ba.png)
