### ISSUE TITLE
./configure should fail if the bazel commands fail

### ISSUE THREAD

**Issue by llchan** [tensorflow/tensorflow#4662]
The configure script now calls bazel clean and bazel fetch (as of ~Aug 2016).  If they fail, the script should exit with a nonzero exit status rather than continuing onwards.  This is important for automated build systems to detect failed configure calls.

**Comment by gunan** [comment]
@davidzchen added these to configure script.
David, is this the case at the moment?

**Comment by davidzchen** [comment]
The reason why the script continues even when commands fail is because the script does not `set -e`. Perhaps we should set `set -e` and some other shell settings in the `configure` script as described by [Writing Safe Shell Scripts](https://sipb.mit.edu/doc/safe-shell/).

**Comment by gunan** [comment]
@martinwicke, is there a reason we do not have `set -e` in the configure script?

**Comment by llchan** [comment]
If you use `set -e`, I'd put it at the end after all the configuration is done, or put it in the `bazel_clean_and_fetch()` function and unset it when it exits that function. Otherwise stuff like `default_python_bin_path=$(which python)` will fail the script if there is no python on the path.

**Comment by llchan** [comment]
Philosophically speaking, I'd prefer for the configure script not to run any bazel commands (esp fetch, since that does a lot of work). It would be more "normal" to write some config files and have the build step clean/fetch if it detects a config change.

But.. if this is really complicated, I dont feel very strongly, just figured I'd voice my opinion.

**Comment by davidzchen** [comment]
+cc @damienmg 

@llchan That is a good point. For those lines where we have command substitution, would it be idiomatic to do the following to prevent the non-zero exit code:

```sh
default_python_bin_path=$(which python || true)
```

It is not ideal to have to run those bazel commands in the `configure` script. We are working on improving the cache invalidation for external repositories and have plans to let repository rules declare which environment variables they consume and would invalidate the repository if they change.

At the same time, ideally, a shell script as non-trivial as `configure` should try to be as strict as possible and exit immediately if any of the commands fail.

**Comment by martinwicke** [comment]
set -e is generally a good idea, unless we can include error messages
better than the ones generated by the failing commands.
