### ISSUE TITLE
Process finished with exit code 132 (interrupted by signal 4: SIGILL)

### ISSUE THREAD

**Issue by tomuGo** [tensorflow/tensorflow#46628]
![image](https://user-images.githubusercontent.com/24789356/105575143-48a93300-5da4-11eb-9260-4846a809e2ea.png)
i use tensorflow 2.4.1  in mac

**Comment by gallogiulia** [comment]
Hello! 
I followed the PyCharm installation guide from the official Tensorflow Certification page. https://www.tensorflow.org/extras/cert/Setting_Up_TF_Developer_Certificate_Exam.pdf 

After installing all necessary packages, with the specified versions, I get the same problem as @tomuGo. 
My version of tensorflow is 2.3.0 and I am running the script on my Apple Silicon.
<img width="1187" alt="Screen Shot 2021-01-23 at 7 48 26 PM" src="https://user-images.githubusercontent.com/21693360/105620652-0a1b7480-5db4-11eb-85fb-59ffeb8a8b9e.png">

**Comment by jvishnuvardhan** [comment]
@gallogiulia @tomuGo I had same problem. After following the suggestion mentioned in a [stackoverflow](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org) to install certificates,  everything worked as expected.

Before you take exam, install the certificate and run the your `mnist` code. Please let me know how it progresses.
Best wishes for your certification. Thanks!

**Comment by tomuGo** [comment]
@gallogiulia https://github.com/apple/tensorflow_macos      look this,it worked

**Comment by kangdongju-peng** [comment]
@jvishnuvardhan 
Very thank you!, I decide to install certificates but I wonder what the certificates is. Is it AI TensorFlow Developer Professional Certificate?

**Comment by jvishnuvardhan** [comment]
@kangdongju-peng This (`install certificates`) is not related to `TensorFlow Developer Professional Certificate`. You need `install certificates` to download some data from some website (GitHub, webpages, etc). In the above case, the code need to download `mnist` data. Thanks!

**Comment by kangdongju-peng** [comment]
@jvishnuvardhan Really thank you! but I wonder about how to install certificates on ubuntu. If you give me answers about it, I will really thank you!

**Comment by rainbow9981** [comment]
> stackoverflow

 I follow the 

> @gallogiulia @tomuGo I had same problem. After following the suggestion mentioned in a [stackoverflow](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org) to install certificates, everything worked as expected.
> 
> Before you take exam, install the certificate and run the your `mnist` code. Please let me know how it progresses.
> Best wishes for your certification. Thanks!
> 
> Please close the issue if this was resolved for you. Thanks!

I follow the suggestion to install the certificate but still can't solve the problem. I wonder why. Thanks

**Comment by mehmet0zen** [comment]
> > stackoverflow
> 
> I follow the
> 
> > @gallogiulia @tomuGo I had same problem. After following the suggestion mentioned in a [stackoverflow](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org) to install certificates, everything worked as expected.
> > Before you take exam, install the certificate and run the your `mnist` code. Please let me know how it progresses.
> > Best wishes for your certification. Thanks!
> > Please close the issue if this was resolved for you. Thanks!
> 
> I follow the suggestion to install the certificate but still can't solve the problem. I wonder why. Thanks

Same here I'm guessing it's because of the package we use.

**Comment by intexcor** [comment]
Проблема встречается и на линукс устройствах
