### ISSUE TITLE
Remove py_proto_library Macro from tensorflow/core/platform/default/build_config.bzl

### ISSUE THREAD

**Issue by ssiano** [tensorflow/tensorflow#46636]
tensorflow/core/platform/default/build_config.bzl contains a py_proto_library macro (Re-defined protocol buffer rule) with a comment that it should be removed once the protobuf dependency version is updated to include the commit shown in the comment.

The referenced protobuf commit (294b5758c373cbab4b72f35f4cb62dc1d8332b68) has been in protobuf since v3.6.0 from 2018-06-13.

Also, TensorFlow has the following protobuf version references:
```
master      tensorflow/workspace.bzl: protobuf 3.9.2, tensorflow/tools/pip_package/setup.py: protobuf >=3.9.2
2.0 branch  tensorflow/workspace.bzl: protobuf 3.8.0, tensorflow/tools/pip_package/setup.py: protobuf >=3.6.1
```

**Comment by SuryanarayanaY** [comment]
Hi @ssiano ,

Could you please confirm whether this is still an issue with latest versions ?

I am unable to find which Macro you are referring to in this file `tensorflow/core/platform/default/build_config.bzl .

But I can find the comment still persists here. 
https://github.com/tensorflow/tensorflow/blob/f058c3591a30810e5fb99344d73d4778fd0a0b2f/tensorflow/tsl/platform/default/build_config.bzl#L356-L358

Could you please check whether the mentioned Macro still exists in master branch?

Thanks!

**Comment by ssiano** [comment]
@SuryanarayanaY, the macro is on Line 358 of the code snippet you show.

And the commit of the code snippet is on master.
