### ISSUE TITLE
tensorflow.greater returns a wrong bool

### ISSUE THREAD

**Issue by Celtaidd** [tensorflow/tensorflow#46634]
### System information
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5861094/tf_env.txt)

-   I used the custom script shown below
-   Windows 10 Family version 19041.746
-   TensorFlow is installed from source
-   v2.4.0-49-g85c8b2a817f 2.4.1
-   Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
-   CUDA v11.1
-   CPU Intel Core i7-3770 @ 3.40GHz
-   GPU: GeForce GTX 1060 6GB

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
when I use the greater function from the package it gives me **True** when 1 > 1000** and **False when 1 > 10000**. I think the error is obvious enough

EDIT: Issue Fixed, it was obviously the fact that I was using Int8. I guess Python made me unused to check for overflows. Sorry for that dumb issue ^-^

### Source code / logs
>>> import tensorflow as tf
initialization is successful
>>>tf.greater(tf.convert_to_tensor(1, dtype=tf.int8), tf.convert_to_tensor(1000, dtype=tf.int8))
<tf.Tensor: shape=(), dtype=bool, numpy=True>

>>>tf.greater(tf.convert_to_tensor(1, dtype=tf.int8), tf.convert_to_tensor(10000, dtype=tf.int8))
<tf.Tensor: shape=(), dtype=bool, numpy=False>

**Comment by WindQAQ** [comment]
Because 1000 is overflow given dtype=int8, and it's converted to -24 in int8 representation. Therefore, 1 > -24.
Similarly, 10000 is overflow, and is 16 in int8 representation. Therefore, 1 < 16.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/30fcf688a66ad8dbb36c44f922e5d25f/untitled515.ipynb)
