### ISSUE TITLE
object detection identifying even there is no image

### ISSUE THREAD

**Issue by sidharth1805** [tensorflow/tensorflow#46632]
hello guys i have been working in tensor flow object detection I have choose mobile ssd net model and trained the model but i am  getting a very false model it is detecting even when there is no image in the video stream.
![image](https://user-images.githubusercontent.com/53184702/105580005-ca528e00-5daf-11eb-95ed-097ceeded753.png)
Even it detects the same thing while a white blank wall is before it my accuracy is good.

**Comment by Saduf2019** [comment]
@sidharth1805 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
