### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by YangHan-Morningstar** [tensorflow/tensorflow#46640]
Hi, guys, recently I'm trying to built my own metrics class using the sklearn.metrics, but when I running the update_state funcation inherit from the tensorflow.keras.metrics.Metric, I find the argument in update_state function which are y_true and y_pred is Tensor object but I need numpy array, I have tried the method given in the documentation which says using y_true.numpy but I got an error: AttributeError: 'Tensor' object has no attribute 'numpy'. I have tried many methods following the Internet but it still doesn't work. Could you help me solve this? Here are my code, thanks!

class SelfF1(Metric):
    def __init__(self, average, name="self_f1", **kwargs):
        super(SelfF1, self).__init__(name=name, **kwargs)
        self.f1_value = self.add_weight(name="sf", initializer="zeros", dtype="float64")
        self.average = average

    def update_state(self, y_true, y_pred, sample_weight=None):

        y_pred = tf.reshape(tf.argmax(y_pred, axis=1), shape=(-1,))
        if len(y_true.shape) == 2 and y_true.shape[1] != 1:
            y_true = tf.reshape(tf.argmax(y_true, axis=1), shape=(-1,))

        f1_value = f1_score(y_true=y_true.numpy(), y_pred=y_pred.numpy(), average=self.average)

        self.f1_value.assign(f1_value)

    def result(self):
        return self.f1_value

    def reset_states(self):
        self.f1_value.assign(0.0)

**Comment by amahendrakar** [comment]
@YangHan-Morningstar,
On trying to implement the custom metrics in a sample code I am facing an error stating `TypeError: __init__() missing 1 required positional argument: 'average'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/eb9bde2645ed403f4a337dab576c832d/46640.ipynb).

In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using.

Also, please take a look at [this guide](https://www.tensorflow.org/guide/keras/train_and_evaluate#custom_metrics) to implement custom metrics and check if helps. Thanks!

**Comment by YangHan-Morningstar** [comment]
My tensorflow version is 2.0.0 and I have followed this guide. I found the
y_true and y_predict is Tensor object but I need numpy array.

**Comment by amahendrakar** [comment]
@YangHan-Morningstar,
Could you please share the Python sciprt/notebook you are running, so that we can reproduce the issue on our end. Thanks!

**Comment by YangHan-Morningstar** [comment]
Sure, here it is.

from sklearn.metrics import recall_score

class Self_Recall(tf.keras.metrics.Metric):
    def __init__(self, average="macro", name="self_recall", **kwargs):
        super(Self_Recall, self).__init__(name=name, **kwargs)
        self.recall_value = self.add_weight(name="recall_value",
initializer="zeros")
        self.average = average

    def update_state(self, y_true, y_pred):
        y_true_numpy = y_true.numpy()
        y_pred_numpy = y_pred.numpy()

        value = recall_score(y_true_numpy, y_pred_numpy, average=self.average)
        self.recall_value.assign(value)

    def result(self):
        return self.recall_value

    def reset_states(self):
        self.recall_value.assign(0.0)

**Comment by amahendrakar** [comment]
@YangHan-Morningstar,
By adding the `run_eagerly=True` argument to `model.compile`, I was able to run the code without any issues. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ce9f58bb1b51fe2cd124c56c4b52877e/46640.ipynb). Thanks!

**Comment by YangHan-Morningstar** [comment]
I have tried your gist of it and it do work but when I copy the code in the gist to my PyCharm and run it, it still tell me the error, I do not change any code, just copy and run! My tensorflow version is 2.0.0 and here is my picture, I'm very confused...
![image](https://user-images.githubusercontent.com/67748964/106389738-eabdc080-641f-11eb-8f59-bc5fa2a72eab.png)

**Comment by amahendrakar** [comment]
> My tensorflow version is 2.0.0

@YangHan-Morningstar,
Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue? Thanks!

**Comment by YangHan-Morningstar** [comment]
Nice! It works in the version v2.4.1, thanks a lot!
