### ISSUE TITLE
Unable to tf.saved_model.load() from a trained Keras model

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#46644]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8

**Describe the current behavior**
I have a Saved Model.  When I attempt to load it in the JVM, it crashes the JVM - see https://github.com/tensorflow/java/issues/194 .  When I use `tf.saved_model.load()`, it fails complaining about, `The same saveable will be restored with two names: layer_with_weights-0/layer_with_weights-1/layer_with_weights-0/_table/.ATTRIBUTES/table`.

The model does work in TF-Serving and when using `keras.models.load_model()`

**Describe the expected behavior**
The model should load everywhere and should not cause a core dump in the JVM.

**Standalone code to reproduce the issue**
The model is proprietary.  I am struggling with how to triage the issue into something that I can share.  If you have thoughts, please let me know!

**Other info / logs**
The SavedModel is created from a Keras model.

See https://github.com/tensorflow/java/issues/194 for some JVM dump logs.

**Comment by jeisinge** [comment]
I have been attempting to triage a bit more.  I can reproduce 100% of the time on my model, I haven't been able to simplify to a test case that I can reproduce.  I wanted to share what I have done and learned to hopefully prompt some ideas on where to investigate next.

First, this issue not only segfaults Java, it also segfaults Python.

Second, I attempted to save each of the layers of my model to see which of my layers is the issue.  I have limited it down to about 30 lines of code for the Keras Functional models that fail:
```python
def categorical_embedding(vocabulary, embedding_dimensions, max_norm_embedding, name, num_biases): 
  categorical_input = keras.Input(shape=1, dtype="int64", name=name)
  
  lookup_layer = keras.layers.experimental.preprocessing.IntegerLookup(
    num_oov_indices=1, vocabulary=vocabulary, mask_value=None
  )
  lookup_layer.weights[0].name = "lookup_weights" # fix for serialization - see https://github.com/tensorflow/tensorflow/issues/41244
  lookup = lookup_layer(categorical_input)
  
  embedding = keras.layers.Embedding(
    len(vocabulary) + 1, embedding_dimensions, input_length=1, name="embedding"
  )(lookup)
  bias = keras.layers.Embedding(
    len(vocabulary) + 1, num_biases, input_length=1,
    embeddings_initializer=keras.initializers.Zeros(),
    name="bias"
  )(lookup)
  
  squeeze = keras.layers.Lambda(lambda net: K.squeeze(net, -2), name="squeeze_to_one_embedding")
  
#   max_norm = keras.constraints.MaxNorm(max_norm_embedding, axis=-1)
#   embeddings_constraint = keras.layers.Lambda(lambda net: max_norm(net), name="embeddings_constraint")

  return categorical_input, keras.Model(
    inputs=categorical_input, outputs=[squeeze(embedding), squeeze(bias)], name=f"{name}_categorical_embedding"
  )
```
Unfortunately, I cannot reproduce the issue this simplified test case.

Further, our model train is a two-phase train --- the first model with this functional model does not show this issue; the second model does.  This two-phased train involves training once and then transferring some of the input, trunk, and heads to another train.  The model that is failing is part of this transfer.

I have tested with TF 2.3.1 and 2.4.0.  Both cannot load/save this model.

Other warnings/errors that I have seen are:
```python
InvalidArgumentError: Shape [140185022619568,-4294967096] has dimensions with values below -1 (where -1 means unknown)
InvalidArgumentError: Shape [140185009137680,140185009137680] is too large (more than 2**63 - 1 entries)
2021-01-25 22:20:16,729 - absl - WARNING - Found untraced functions such as dense_9_layer_call_and_return_conditional_losses, dense_9_layer_call_fn, concatenate_3_layer_call_and_return_conditional_losses, concatenate_3_layer_call_fn, dense_11_layer_call_and_return_conditional_losses while saving (showing 5 of 195). These functions will not be directly callable after loading.
2021-01-25 22:23:18,762 - tensorflow - WARNING - 11 out of the last 11 calls to <function recreate_function.<locals>.restored_function_body at 0x7f8890406440> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
```

Any thoughts on where to investigate next are much appreciated!

**Comment by ymodak** [comment]
Any luck in putting together a reproducible example?

**Comment by jeisinge** [comment]
Unfortunately, no.  The issue still exists, however, I still cannot reproduce with code/data that I can share.

If you have any recommendations on how best to reproduce, let me know.  If not, I reckon, this should be closed.

**Comment by ymodak** [comment]
Closing this issue for now. Thanks!
