### ISSUE TITLE
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lxj0276** [tensorflow/tensorflow#4664]
I'm a new user of tensorflow.I install tensorflow like this.
1.export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
2.sudo pip install --upgrade $TF_BINARY_URL

and I succeed install tensorflow ,when I import tensorflow ,It happens that "ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory".It's crazy,I find some solution ,that my shell environment variables should do like this:
1.export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
2.export CUDA_HOME=/usr/local/cuda
but it not works.
I find there is not libcudart.so.7.5 in "/usr/local/cuda/lib64",it's only "libcudart so.8.0"

os:ubuntu 16.04 LTS,cuda:8.0

**Comment by yaroslavvb** [comment]
You need to install CUDA 7.5 rather than CUDA 8.0 which is not yet
supported by pre-built binaries

**Comment by concretevitamin** [comment]
What @yaroslavvb said.  Feel free to re-open if CUDA 7.5 did not work for you.

**Comment by lxj0276** [comment]
If I install cuda7.5 and cuda8.0 at the same time ,they  will not clash?
