### ISSUE TITLE
tf.repeat fails

### ISSUE THREAD

**Issue by dh-g** [tensorflow/tensorflow#46648]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.*
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: no GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
n = 50000
many_ones = tf.cast(tf.concat([tf.ones(n), [n,]], axis = 0), 'int32')
array = tf.concat([tf.range(n), [n, ]], axis = 0)
tf.repeat(array, many_ones)
```
returns

> InvalidArgumentError: Size 0 must be non-negative, not -1794917296 [Op:Reshape]

**Describe the expected behavior**
`np.repeat` returns
> array([    0,     1,     2, ..., 50000, 50000, 50000], dtype=int32)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

the following code would work for small ns, but fail/be very slow for big ns
```
n = 50000
many_ones = tf.cast(tf.concat([tf.ones(n), [n,]], axis = 0), 'int32')
array = tf.concat([tf.range(n), [n, ]], axis = 0)
tf.repeat(array, many_ones)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
@dh-g I was able  to execute the code  up to value n = 45000 but  after that the colab is crashing by utilizing the entire available  RAM. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/50427c688799dbcfbb20505b82e1efd1/untitled.ipynb).

Is there any specific reason why do you want a tensor of such huge dimensions?

**Comment by dh-g** [comment]
`utilizing the entire available RAM.`

yeah this is most likely a memory problem, but this shouldn't be, as numpy can do it without missing a beat, and so does pytorch, and will be done in less than a second.

`Is there any specific reason why do you want a tensor of such huge dimensions?`

the reason is that i need to vectorize an operation 

[item1, ..., item1, ..., itemN, ..., itemN] - [item1_1, ..., item1_m, ..., itemN_1, ..., itemN_l]

which if i used for loop with (the biggest repeat is actually way bigger than 45000 ≈2^15 btw), it would take forever to calculate.

**Comment by dh-g** [comment]
any updates? this is not a small issue by any means.

**Comment by rmothukuru** [comment]
@dh-g,
Instead of using all the APIs in one go, below code works without any issue, even for `n=100000`:

```python
import tensorflow as tf
print(tf.__version__)

n = 100000
#many_ones = tf.cast(tf.concat([tf.ones(n), [n,]], axis = 0), 'int32')
many_ones = tf.ones(n)
print(many_ones.numpy())
many_ones = tf.concat([many_ones, [n,]], axis = 0)
print(many_ones.numpy())
many_ones = tf.cast(many_ones, 'int32')
print(many_ones.numpy())
``` 
Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/0b3d68db66a7e76fd2b9de7b01211735/gh_tf_46648.ipynb) of working code.

**Comment by dh-g** [comment]
hey @rmothukuru please note the problem is about `tf.repeat` **not** on tf.ones

**Comment by dh-g** [comment]
and I totally disagree with the change of tag from bug to performance, this IS a bug.

**Comment by dh-g** [comment]
hey any updates?

**Comment by dh-g** [comment]
hey again, any updates????

**Comment by dh-g** [comment]
@saikumarchalla @rmothukuru Hey guys, I just tried in the colab notebook again [here](https://colab.research.google.com/gist/saikumarchalla/50427c688799dbcfbb20505b82e1efd1/untitled.ipynb#scrollTo=pDt8nA5z_GQS). The code still fails for both 2.4 and the nightly version 2.6

**Comment by ttang235** [comment]
For not-very-large tensors(e.g. 5M elements), tf.repeat can also have some problems. 
`
a = tf.range(5000000)
b = tf.concat([tf.zeros(5000000-1, dtype=tf.int32),tf.constant([5000000], dtype=tf.int32)], axis=0)
c = tf.repeat(a,b)
`

The above code results in an OOM error:

> 2021-07-08 14:22:05.656061: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 25000000000000 exceeds 10% of system memory.
2021-07-08 14:22:05.656150: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[5000000,5000000] and type bool on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tangfangshuang/.pyenv/versions/py3_venv/lib/python3.5/site-packages/tensorflow_core/python/ops/array_ops.py", line 4927, in repeat
    return repeat_with_axis(input, repeats, axis, name)
  File "/home/tangfangshuang/.pyenv/versions/py3_venv/lib/python3.5/site-packages/tensorflow_core/python/ops/array_ops.py", line 4839, in repeat_with_axis
    mask = sequence_mask(repeats, max_repeat)
  File "/home/tangfangshuang/.pyenv/versions/py3_venv/lib/python3.5/site-packages/tensorflow_core/python/ops/array_ops.py", line 3591, in sequence_mask
    result = row_vector < matrix
  File "/home/tangfangshuang/.pyenv/versions/py3_venv/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 5376, in less
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[5000000,5000000] and type bool on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Less]

**Comment by dh-g** [comment]
@rmothukuru @saikumarchalla hey guys any updates? there has been no update for 5 months now. And as you can see from @ttang235 's comment this is not a lone incidence.

**Comment by tilakrayal** [comment]
@dh-g,
If you pass a scalar repeat value instead of a vector, tf.repeat will use a fast path that requires less memory: b = tf.repeat(a, 1000, axis=0). Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a4ac94a00ccf4c64c8a5f193773fac1f/reproducin.ipynb).

Also find the comment from the developer for the [similar](https://github.com/tensorflow/tensorflow/issues/50712) error/issue and the merged [PR](https://github.com/tensorflow/tensorflow/pull/52545) for the reference. Thank you!
