### ISSUE TITLE
MGB track

### ISSUE THREAD

**Issue by MGBtrust** [tensorflow/tensorflow#46649]
https://github.com/tensorflow/tensorflow/blob/590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b/tensorflow/python/training/tracking/base.py#L498-L990

**Comment by Saduf2019** [comment]
@MGBtrust 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
