### ISSUE TITLE
tf.transpose returns incorrect shape or throws concatenation error when part of keras model

### ISSUE THREAD

**Issue by jasonhillary** [tensorflow/tensorflow#46641]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda 11.0/ 8.0.4
- GPU model and memory: NVIDIA GeForce GTX 1050 / 4.0GB Memory

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

- When run as part of a keras model, tf.tranpose of a rank 2 tensor gives unexpected shape . 
- When run  eagerly tf.transpose gives expected shape. 
- If the first dimension is greater than 32 then tf.transpose either returns an incorrect shape or throws a concatenation error
- This issue also affects tf.matmul(a, b, transpose_b=True)

**Describe the expected behavior**
Given a tensor of shape(i, j) tf.transpose returns a tensor of  shape (j, i) . As it does in eager mode
Used for calculating similarities, similar in this example https://keras.io/examples/vision/metric_learning/

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1MIXzVp1Jqsu-eypWFeNavW1bk3-B0UTG?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ea31d1156401c60c60c416f66052dd97/46641.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@jasonhillary When I provided `batch_size` parameter to `model.predict`, both shapes are same as shown in this [gist](https://colab.research.google.com/gist/jvishnuvardhan/6c68afcc72034c530a2eb6dd48d7a84f/46641.ipynb). 

The following line I changed from

`transpose_model = m.predict(v)`
to
`transpose_model = m.predict(v,batch_size=64)`

Output is as shown below.
```
eager shape:  (128, 64) model shape : (128, 64)
eager shape:  (128, 64) model shape : (128, 64)
```

Please close the issue if this was resolved for you. Thanks!

**Comment by jasonhillary** [comment]
@jvishnuvardhan thank you very much, that did indeed resolve it.
