### ISSUE TITLE
Error in prediction:Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU for TensorFlow C++ API Reference

### ISSUE THREAD

**Issue by clemente0420** [tensorflow/tensorflow#46658]
<em>Please make sure that this is a bug. As per our

**System information**
- OS Platform ：Ubuntu 16.04
- TensorFlow installed from source :
- TensorFlow version (use command below): TensorFlow Core v2.4.1  TensorFlow C++ API Reference
- Python version: 3.5
- Bazel version : release: release 1.2.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

LOG OUTPUT

2021-01-25 10:39:38.260369: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:661] Executor failed to create kernel. Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node v_}}]]
2021-01-25 10:39:38.261762: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:661] Executor failed to create kernel. Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node v_}}]]
Error in prediction:Invalid argument: Default MaxPoolingOp only supports NHWC on device type CPU
         [[{{node v_}}]]

**Comment by clemente0420** [comment]
PLEASE WE NEED NCHW dataformat for c++ API

**Comment by amahendrakar** [comment]
@clemente0420,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by clemente0420** [comment]
![image](https://user-images.githubusercontent.com/32806348/105708612-aaf26700-5f4f-11eb-8e72-7d961245c71a.png)

if not support on cpu , why you guys write the doc for that?

With the default format "NHWC", the data is stored in the order of: [batch, in_height, in_width, in_channels]. Alternatively, the format could be "NCHW", the data storage order of: [batch, in_channels, in_height, in_width].

**Comment by rmothukuru** [comment]
@clemente0420,
Thank you for sharing the documentation for reference. Can you please share your code so that we can reproduce the error and see what's going on? Thanks!
