### ISSUE TITLE
Guide for porting reference ops to TFLite micro

### ISSUE THREAD

**Issue by stephanboner** [tensorflow/tensorflow#46657]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/CONTRIBUTING.md

## Description of issue (what needs changing):

> TODO(b/165627437): Create and link to a guide to porting reference ops.

This TODO is still open. It feels like TFLite micro is getting more and more attention and recently many ops are in the process to be ported. I'm also working on two ops (#45693) and I would highly appreciate such a guide since I'm struggling to port the tests from TFLite to micro.
How are the TODOs handled in tensorflow? Is someone working on that or is it just open until somebody picks it up?

**Comment by sanatmpa1** [comment]
@stephanboner,

Can you take a look at this [guide](https://github.com/tensorflow/tflite-micro/blob/080db2db55e82863d1a9adcf5c045d48e3e73941/tensorflow/lite/micro/docs/porting_reference_ops.md) and let me know if that is what you're looking for? Thanks!
