### ISSUE TITLE
How can I build this for Intel GPU (to use OpenCL)

### ISSUE THREAD

**Issue by kjkaranj** [tensorflow/tensorflow#46650]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source 
- TensorFlow version: Release 2.5.1
- Python version: Python 2.7.15+
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: NA
- GPU model and memory: Intel GPU 

**Describe the problem**
Compiled with -DCL_DELEGATE_NO_GL flags in Makefile however I get the following error : 
./tensorflow/lite/delegates/gpu/api.h:262:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetInputShape(index,const Dimensions& dimensions) = 0;

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1> Add -DCL_DELEGATE_NO_GL in Makefile 
2> Added tensorflow/lite/delegates/gpu/*.cc to the list of sources in Makefile 
3> Included /usr/include to add cl.h 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
COMPLETE ERROR LOGS: 
In file included from /usr/include/EGL/eglplatform.h:130:0,
                 from /usr/include/EGL/egl.h:39,
                 from ./tensorflow/lite/delegates/gpu/gl/portable_gl31.h:21,
                 from ./tensorflow/lite/delegates/gpu/api.h:50,
                 from tensorflow/lite/delegates/gpu/api.cc:16:
./tensorflow/lite/delegates/gpu/api.h:262:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetInputShape(index,const Dimensions& dimensions) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:271:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetInputObjectDef(int index, ObjectDef def) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:272:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetOutputObjectDef(int index, ObjectDef def) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:273:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetAllInputObjectDefsTo(ObjectDef def) {
                 ^
./tensorflow/lite/delegates/gpu/api.h:280:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetAllOutputObjectDefsTo(ObjectDef def) {
                 ^
./tensorflow/lite/delegates/gpu/api.h:293:17: error: expected unqualified-id before ‘int’
   virtual absl::Status Build(std::unique_ptr<InferenceRunner>* runner) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:310:17: error: expected unqualified-id before ‘int’
   virtual absl::Status GetInputObject(int index, TensorObject* object) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:311:17: error: expected unqualified-id before ‘int’
   virtual absl::Status GetOutputObject(int index, TensorObject* object) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:312:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetInputObject(int index, TensorObject object) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:313:17: error: expected unqualified-id before ‘int’
   virtual absl::Status SetOutputObject(int index, TensorObject object) = 0;
                 ^
./tensorflow/lite/delegates/gpu/api.h:315:17: error: expected unqualified-id before ‘int’
   virtual absl::Status Run() = 0;

**Comment by terryheo** [comment]
You should use CMake to build it.
https://www.tensorflow.org/lite/guide/build_cmake#opencl_gpu_delegate

**Comment by IrishBAM** [comment]
EGL_NO_X11 seems to do the trick

**Comment by kjkaranj** [comment]
Thank you for the comments will try this out and update here .
