### ISSUE TITLE
Third-party Tensorflow 2.4.0

### ISSUE THREAD

**Issue by fsinn1995** [tensorflow/tensorflow#46660]
Hello TensorFlow team,
I'm looking for version 2.4.0 of Tensorflow for all used third-party with the version status. Is there a document that refers to all third-party versions and versions?
Best regards,
Fabian

**Comment by Saduf2019** [comment]
@fsinn1995 
Please refer to this [link]( https://github.com/tensorflow/tensorflow#community-supported-builds) and let us know if i helps.
