### ISSUE TITLE
Old Lookup Bug still active?

### ISSUE THREAD

**Issue by DHOFM** [tensorflow/tensorflow#46666]
I am using Tensorflow 1.x 
OS: Mac OS or Linux can be testet e.g in Cola

The following demo code works with GPU but not with CPU. It looks like this from 2018 - I think it should work on both:
```
`
vocab = [{'this':1},
         {'is':2},
         {'just':3},
         {'the':4},
         {'a':5},
         {'demo':6},
         {'code':7},
         {'tensorflow':8},
         {'test':9}]

features = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

EMBEDDING_SIZE = 1
with tf.Session() as sess:
    features_embedded = tf.contrib.layers.embed_sequence(
        ids=features,
        vocab_size=len(vocab),
        embed_dim=EMBEDDING_SIZE,
        scope='words',
        reuse=tf.AUTO_REUSE
        )
    word_list = tf.unstack(features_embedded, axis=1)
    sess.run(tf.global_variables_initializer())`
```

Leads to InvalidArgumentError: indices[1,4] = 9 is not in [0, 9)
	 [[{{node words/embedding_lookup}}]]

Or GPU:
[[[-0.03936231]
  [-0.62959105]
  [ 0.05874097]
  [-0.39156422]
  [-0.50708985]]

 [[-0.50708985]
  [-0.2946922 ]
  [-0.32304823]
  [ 0.514025  ]
  [ 0.        ]]]

It is something like this bug: https://github.com/tensorflow/tensorflow/issues/17417

**Comment by DHOFM** [comment]
Think I got it, len(vocab) is 9 should be 10 or more. But why does it work with GPU???

**Comment by mihaimaruseac** [comment]
We no longer fix TF 1.x. Can you try with the latest version?

**Comment by DHOFM** [comment]
@mihaimaruseac Thanks. What does latest Version mean? TF 2.x or latest TF 1.x?

**Comment by Saduf2019** [comment]
@DHOFM 
As informed "We no longer fix TF 1.x. " please use 2.x i.e 2.4 and let us know if you face any issues.

**Comment by DHOFM** [comment]
OK, but as yo can see, this is tf.contrib.layers.embed_sequence - so there is no more tf.contrib.layers.embed_sequence in TF 2.0, right?

**Comment by mihaimaruseac** [comment]
You should convert to use the replacements APIs for `tf.contrib`.

**Comment by ymodak** [comment]
> OK, but as yo can see, this is tf.contrib.layers.embed_sequence - so there is no more tf.contrib.layers.embed_sequence in TF 2.x, right?

That's correct. Also check out [`TF Addons`](https://github.com/tensorflow/addons) repository where a subset of `tf.contrib` functions are revived.
