### ISSUE TITLE
Breaking change of TFLite model definition in TensorFlow 2.4.0: OperatorCode.BuiltinCode

### ISSUE THREAD

**Issue by jackwish** [tensorflow/tensorflow#46663]
(source issue: https://github.com/jackwish/tflite/issues/9)

**This change breaks software stacks that depend on the built TFLite model parser, e.g. [tvm](https://github.com/apache/tvm), [tflite2onnx](https://github.com/jackwish/tflite2onnx), and etc.**

Starting from [TensorFlow 2.4.0](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/lite/schema/schema.fbs#L220), the `BuiltinOperator` switches to `int32` from `byte`. As a result, the `OperatorCode.builtin_code` is now an `int32` too, and code like `op_code.BuiltinCode()` is broken. 

```
// An OperatorCode can be an enum value (BuiltinOperator) if the operator is a
// builtin, or a string if the operator is custom.
table OperatorCode {
  // This field is for backward compatibility. This field will be used when
  // the value of the extended builtin_code field has less than
  // BulitinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES.
  deprecated_builtin_code:byte;
  custom_code:string;

  // The version of the operator. The version need to be bumped whenever new
  // parameters are introduced into an op.
  version:int = 1;

  // This field is introduced for resolving op builtin code shortage problem
  // (the original BuiltinOperator enum field was represented as a byte).
  // This field will be used when the value of the extended builtin_code field
  // has greater than BulitinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES.
  builtin_code:BuiltinOperator;
}
``` 

For any code that uses `op_code.BuiltinCode()`, a workaround like the below (or [this PR](https://github.com/jackwish/tflite/pull/10/files)) is needed.

```py

if op_code.BuiltinCode() < BuiltinOperator.PLACEHOLDER_FOR_GREATER_OP_CODES:
    opc = op_code.DeprecatedBuiltinCode()
else:
    opc = op_code.BuiltinCode()
```

**Comment by abattery** [comment]
Sorry for encountering this issue in your side. Since TFLite builtin operator set is getting bigger, we need to roll this change. We provide helpers to adopt this change:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_conversion_utils.cc
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_utils.cc

Please take a look at them.

**Comment by jackwish** [comment]
@abattery Thank you for the details! I understand that is something that can hardly avoid when the system involves... So by design, for any systems that rely on a TFLite model (or the model representation), they should wrap up the calling to `BuiltinCode` like [this](https://github.com/tensorflow/tensorflow/blob/747ca958fa6c51ffd81616867e7f043216cbe4ad/tensorflow/lite/python/util.py#L651) with the example handlers you listed? If that's the case, maybe we can do something (maybe [this](https://github.com/jackwish/tflite/pull/10)) in [`tflite`](https://github.com/jackwish/tflite) (a python parser package) to avoid such change in the software system stack.

**Comment by abattery** [comment]
@jackwish we would do that but we are depending the flatbuffer library to generate the interfaces which are done by the codegen to approach so it is a very tricky to do that.

**Comment by jackwish** [comment]
@abattery Thanks for your reply. Refactoring for such a case seems can be avoided. I can work around it in [the python parsing package](https://github.com/jackwish/tflite).

Now closing as I have got the answer. Thanks!
