### ISSUE TITLE
Updates to the TFLM Makfile that are not backwards compatible

### ISSUE THREAD

**Issue by Lucy20211** [tensorflow/tensorflow#46667]
**System information**

-   OS Platform and Distribution: Linux Ubuntu 20.10 
-   TensorFlow version: 2.4.1
-   Python version: 3.8
-   CPU Intel Core i7
-   GPU: NVIDIA GeForce GTX
-   STM32CubeIDE-Lnx: 1.3.0
-   STM32 Nucleo-64 development board with STM32F401RE MCU

**Describe the problem**

I would like to run the Makefile in the Tensorflow Lite for Microcontrollers directory in order to run inference on ST microcontroller above. My problem is that I cannot use the 
TAGS =”portable_optimized” command line option /cc @advaitjain

**Source code / logs**

tensorflow/lite/micro/tools/make/Makefile:61: *** The TAGS command line option is no longer supported in the TFLM Makefile..

Thanks in advance.

**Comment by advaitjain** [comment]
The portable_optimized kernels have been removed for some time now. You can remove `TAGS=portable_optimized` from your command line and things should work as before.

**Comment by advaitjain** [comment]
Also, since you're using an stm32f4 board, you might also want to try `OPTIMIZED_KERNEL_DIR=cmsis_nn` to get optimized implementations for some of the kernels.

**Comment by junior-azeh** [comment]
> **System information**
> 
> * OS Platform and Distribution: Linux Ubuntu 20.10
> * TensorFlow version: 2.4.1
> * Python version: 3.8
> * CPU Intel Core i7
> * GPU: NVIDIA GeForce GTX
> * STM32CubeIDE-Lnx: 1.3.0
> * STM32 Nucleo-64 development board
> 
> **Describe the problem**
> 
> I would like to run the Makefile in the Tensorflow Lite for Microcontrollers directory in order to run inference on ST microcontroller above. My problem is that I cannot use the TAGS =”portable_optimized” command line option /cc @advaitjain
> 
> **Source code / logs**
> 
> tensorflow/lite/micro/tools/make/Makefile:61: *** The TAGS command line option is no longer supported in the TFLM Makefile..
> 
> Thanks in advance.

Did you generate sample project to test with the stm32, if so what was the make command you used

> **System information**
> 
> * OS Platform and Distribution: Linux Ubuntu 20.10
> * TensorFlow version: 2.4.1
> * Python version: 3.8
> * CPU Intel Core i7
> * GPU: NVIDIA GeForce GTX
> * STM32CubeIDE-Lnx: 1.3.0
> * STM32 Nucleo-64 development board
> 
> **Describe the problem**
> 
> I would like to run the Makefile in the Tensorflow Lite for Microcontrollers directory in order to run inference on ST microcontroller above. My problem is that I cannot use the TAGS =”portable_optimized” command line option /cc @advaitjain
> 
> **Source code / logs**
> 
> tensorflow/lite/micro/tools/make/Makefile:61: *** The TAGS command line option is no longer supported in the TFLM Makefile..
> 
> Thanks in advance.

Did you generate sample projects for the stm32 board, what was the make command used

**Comment by Lucy20211** [comment]
Hi, I used this command: `make -f tensorflow/lite/micro/tools/make/Makefile` (from https://www.digikey.com/en/maker/projects/tinyml-getting-started-with-tensorflow-lite-for-microcontrollers/c0cdd850f5004b098d263400aa294023)
