### ISSUE TITLE
Time issue in micro_speec

### ISSUE THREAD

**Issue by nixmeer** [tensorflow/tensorflow#46684]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

When the _micro_speech_ loop is executed for the first time, `current_time` is 0. In this case, the Feature Provider requests `kFeatureSliceCount` audio data packages of `kFeatureSliceDurationMs` length. However, since `previous_time` is set equal to  `current_time` after calling `feature_provider->PopulateFeatureData()`. So running the next time, current time has increased by the number of ms that the audio provider has been recording but also have 990 ms of data already been used. The Feature Provider just sees the difference in the recorded time since the last call and asks for more data that should be available. But since audio provider has no data, it waits till the data has been recorded which takes exactly the time that is missing which are 990 ms.

Am I the only one with this issue? Is it my mistake or common?

There are multiple ways to fix this: 
1) start the time of the audio provider at -990 ms
2) don't let the feature provider request data if there is none recorded (needs audio provider init to be called separately I guess)
3) don't set `previous_time` to `current_time` but to `how_many_new_slices * kFeatureSliceStrideMs`

**Comment by jvishnuvardhan** [comment]
@nixmeer Is this still an issue for you? Can you please test with recent `TF2.7` and `tf-nightly` and let us know whether the issue persists with recent TF version. Also, share a complete standalone code to reproduce the issue. Thanks!

**Comment by vikramdattu** [comment]
@nixmeer @jvishnuvardhan BTW, the examples repo for Espressif solutions is now maintained at: https://github.com/espressif/tflite-micro-esp-examples 

If issue still persists for you, I would request you to try out the above repo.
