### ISSUE TITLE
get "Tensor("args_0:0", shape=(), dtype=string)" when using tf.data.TextLineDataset.map()

### ISSUE THREAD

**Issue by tabVersion** [tensorflow/tensorflow#46685]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux version 3.16.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) ) #1 SMP Debian 3.16.59-1 (2018-10-03)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): unknown 1.15.3
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no gpu used
- GPU model and memory: no gpu used

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am reading data from a hdfs path using TextLineDataset. I use `for` to iter over the dataset everything goes well but when it comes to `map`, all I get is `Tensor("args_0:0", shape=(), dtype=string)` (I don'y know there it comes from). The issue can be reproduced with tf ver 2.4.1.

Here is the code:

```python
path = 'hdfs://path-to-file'
dataset = tf.data.Dataset.list_files(path)
dataset = tf.data.TextLineDataset(dataset)
for line in dataset:
    print(line)
```

output using `for`:

```
...
tf.Tensor(b'1\t[1, 15, 1907, 190706, 19070605, 161, "nan", "nan", "nan", 2, 7, 37, "nan", "nan", 1, 0, "nan", "nan", 1819, 181903, 18190301, "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", 0, 1, 1, 1, 0, 0, "201", "2.486379972076975", "1", "0", "0.0", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]', shape=(), dtype=string)
tf.Tensor(b'0\t[1, 13, 1909, 190911, 19091101, 195, "nan", "nan", "nan", 2, "nan", "nan", "nan", "nan", 1, 0, "nan", "nan", 1909, 190901, 19090101, "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", "nan", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', shape=(), dtype=string)
...
```

---

```python
def parse_line(line):
    print(line)
    return line

path = 'hdfs://path-to-file'
dataset = tf.data.Dataset.list_files(path)
dataset = tf.data.TextLineDataset(dataset).map(lambda x: parse_line(x))
```

output using `map`: (this is all I get)

```
Tensor("args_0:0", shape=(), dtype=string)
```

**Describe the expected behavior**

map func should get element in the dataset rather than `Tensor("args_0:0", shape=(), dtype=string)`

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

provided above

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

no log

**Comment by ameyparanjape** [comment]
@tabVersion What's the solution? Facing the same issue! Did you get past this?

**Comment by tabVersion** [comment]
@ameyparanjape Hi, I first init a dataset and iter over it. Using `for` should reach the data and I process data every batch instead of using `map`.

**Comment by valentin-fngr** [comment]
> @ameyparanjape Hi, I first init a dataset and iter over it. Using `for` should reach the data and I process data every batch instead of using `map`.

This is sadly the only way to achieve it

**Comment by tabVersion** [comment]
> > @ameyparanjape Hi, I first init a dataset and iter over it. Using `for` should reach the data and I process data every batch instead of using `map`.
> 
> 
> 
> This is sadly the only way to achieve it 
> 
> 

I've read related source code and I couldn't figure out why.

**Comment by shelllet** [comment]
The same question

**Comment by 2er0** [comment]
Reproducible in version 2.5.0 as well

**Comment by 2er0** [comment]
Workaround: https://stackoverflow.com/questions/58969880/how-to-use-map-with-tuples-in-a-tensorflow-2-dataset

**Comment by Qucy** [comment]
I'm also facing the same issue, code is from Tensorflow offical guideline (https://www.tensorflow.org/tutorials/generative/pix2pix#build_an_input_pipeline_with_tfdata). 
I'm using tf-gpu 2.6 and below code will pop up an error in map function due to it will get a Tensor 'Tensor("args_0:0", shape=(), dtype=string)' instead of a Tensor contains a file path.

`train_dataset = tf.data.Dataset.list_files(str(path / 'train/*.jpg'))
 train_dataset = train_dataset.map(load_image_train, num_parallel_calls=tf.data.AUTOTUNE)
`

**Comment by dragos99** [comment]
Same here!

**Comment by ashok49473** [comment]
same here

**Comment by javadan** [comment]
What version number is this fixed for?

**Comment by javadan** [comment]
still broken in 2.7.

**Comment by wei-yuma** [comment]
Same here!

**Comment by krahnikblis** [comment]
+1up

**Comment by jurevreca12** [comment]
this is still a problem for me

**Comment by Willy8m** [comment]
still the same here

**Comment by JIMhackKING** [comment]
I get the same problem, why close the issue? Is that soluted? Or the problem still here but you use the different way to solute? @tabVersion
