### ISSUE TITLE
[TF2] Converted quantized TFLite model suffers severe precision/recall drop

### ISSUE THREAD

**Issue by sseeds-reply** [tensorflow/tensorflow#46687]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS High Sierra
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.5.0-dev20201209
- Trained on custom dataset using  https://github.com/tensorflow/models/blob/master/research/object_detection/configs/tf2/ssd_mobilenet_v2_320x320_coco17_tpu-8.config 
- tflite_runtime version: 2.5.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_saved_model('/Path/To/Tensorflow/Model/saved_model')
def representative_data_gen():
  image_urls = glob.glob(os.path.join("/Path/To/Imageset",'*'))[:250]

  for image in image_urls:
    try:
      img = cv2.imread(image)
      img = cv2.resize(img, (300, 300))
      img = cv2.cvtColor(img.copy(), cv2.COLOR_BGR2RGB)
      img = img/255.0 
      img = img.astype(np.float32)
      image_list.append(img)
    except Exception as e:
        print(f'{str(e)} : {image}')
        continue

  image_list = np.array(image_list)
  img = tf.data.Dataset.from_tensor_slices(image_list).batch(1)
  for i in img.take(250):
    yield [i]

converter.representative_dataset = representative_data_gen
converter.optimizations = [tf.lite.Optimize.DEFAULT] # size and latency
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
converter.target_spec.supported_types = [tf.int8]
tflite_quant_model = converter.convert()

#Save
tflite_models_dir = pathlib.Path("/filepath/quantized_export_tflite_uint8")
tflite_models_dir.mkdir(exist_ok=True, parents=True)
tflite_model_quant_file = tflite_models_dir/"quantized_model.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)
```

**The output from the converter invocation**

```
# Compiles tflite model successfully.
```

**Failure details**

The Tensorflow model used is a custom trained version of the MobileNet SSD V2 model using the Tensorflow Object Detection API (TF V2). This model is to be deployed on the Google Coral Dev board, and as such requires full integer quantisation (falling back to float32 for the final custom op) when converting to TFLite format. To export the model after training, export_tflite_graph_tf2.py is used (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) , before the quantization step is carried out. Once the post training quantization is complete, the resulting converted .tflite model runs successfully, however upon evaluation (using coco metrics), suffers a severe drop (>50% decrease) in performance compared to the original model, which achieves very high precision/recall when evaluated in the same manner. 

The code used to generate inference is below:

```
# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="quantized_model.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
width = input_details[0]['shape'][2]
height = input_details[0]['shape'][1]

# Load image
img = cv2.imread(image)
(H, W) = img.shape[:2] # Used to multiply normalized output bounding box co-ords to return to image coords
img = cv2.cvtColor(img.copy(), cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (width, height))

if input_details[0]["dtype"] == np.uint8:
        input_scale, input_zero_point = input_details[0]["quantization"]
        img = img / input_scale + input_zero_point

img = np.expand_dims(img, axis=0)
img = np.uint8(img)

# Generate inference
interpreter.set_tensor(input_details[0]['index'], img)
interpreter.invoke()

# Output
boxes = interpreter.get_tensor(output_details[0]['index'])[0]
classes = interpreter.get_tensor(output_details[1]['index'])[0]
scores = interpreter.get_tensor(output_details[2]['index'])[0]

```

**Comment by daverim** [comment]
Is it possible to share the saved model?

**Comment by sseeds-reply** [comment]
Please find attached the quantized .tflite model, as well as the saved .pb model that has been run through the tflite converision compatibility script.


[model.zip](https://github.com/tensorflow/tensorflow/files/5879096/model.zip)

**Comment by teijeong** [comment]
Hi @sseeds-reply , it might be a known problem in the quantizer. At the end of the model, values are requantized before fed into CONCAT op, and this makes precision/recall fall. 
We're working on a fix in the new quantizer which will be ready in few days. When it's ready, you can try nightly release with following flag to test it again. Will get back to this thread when it's done. :)

```python
# while converting
converter.experimental_new_quantizer = True
```

![image](https://user-images.githubusercontent.com/4837376/107171354-ea1bc000-6a05-11eb-84df-b6e1005f86bb.png)

**Comment by daverim** [comment]
Hi, also wanted to add, I tried to convert the saved model and the results do not seem to be good. I also ran the saved model and the results seem to be bad as well. I think maybe I am missing some pre-processing or post-processing functions.

I made a gist for it, please let me know if I have anything wrong: I used an existing mobilenet_ssd quantized model and the model seems to work ok.

https://gist.github.com/daverim/f22e75b67264c2ae7dfa4a45bbc284b4

Perhaps the saved model is out of date, or untrained?
Thanks,
David

**Comment by sseeds-reply** [comment]
Hi,

Thank you for the suggestion, I shall try using the new converter.
In the mean time, we have found a workaround in the application logic instead.

Many thanks for the help

**Comment by nfbalbontin** [comment]
Hi! I'm trying to evaluate my tflite model. @sseeds-reply Could you share how are you evaluating your model using coco metrics please? it would really be a great help. Thanks!
