### ISSUE TITLE
micro_speech: ESP32 Audio Codec Chip not initialized

### ISSUE THREAD

**Issue by nixmeer** [tensorflow/tensorflow#46683]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): not sure
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32 LyraT v4.3

The example _micro_speech_ does configure an I2S bus to receive audio data. This seems to me as if there is an audio codec chip required as provided on the LyraT eval board. However, the audio codec chip is not being initialized so it does not know that it is supposed to send audio data with 16k sampling rate, 16 bit resolution, one channel and act as a replica.

[Here](https://github.com/tensorflow/tensorflow/tree/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/lite/micro/examples/micro_speech#deploy-to-esp32) it says that two boards have been tested. The DevKit has no microphone and the ESP-EYE has a "digital mic". May the EYE'S mic just sends data with this spec by default; I could not find any information about it. So the code might deploy to both and run on both but I doubt it works.

For me, it fixed it to add the initialization of the ES8388. While doing so, I removed the "manual" I2S-handling and replaced it with an audio pipeline.

Maybe it would not harm the example to run on the ESP-EYE, if the audio codec chip was being initialized by default or the board information from menu_config of the IDF would help.

**Comment by sushreebarsa** [comment]
@nixmeer This is a micro related issue,Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues)  ..Thanks!
