### ISSUE TITLE
tf.sequence_mask abortion when lengths contains large value

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46698]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.sequence_mask` abortion when lengths contains large value

**Describe the expected behavior**
expect an exception message if the input is not expected, instead of crash.
**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.sequence_mask(lengths=np.array([3.05524638e+307], dtype=np.float64))
~~~

Output:
~~~python
2021-01-26 16:02:42.088240: F tensorflow/core/framework/tensor_shape.cc:187] Non-OK-status: InitDims(dim_sizes) status: Internal: Expected shape dimensions to be non-negative, got -9223372036854775808
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment]
I ran the code on tf 2.4 and tf-nightly colab crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/37011b0996cc4cebc25af92ee4fa1839/untitled509.ipynb)

**Comment by yongtang** [comment]
Added a PR #46742 for the fix.

**Comment by mihaimaruseac** [comment]
Reopening as #46742 was rolled back

**Comment by saikumarchalla** [comment]
Was able to reproduce in Nightly version TF 2.6 and the colab crashes. Pease find the gist [here](https://colab.research.google.com/gist/saikumarchalla/5df7d4f625bc4be94b76698dd78a1517/untitled92.ipynb#scrollTo=UnuuCWdFJcbp). Thanks1

**Comment by mohantym** [comment]
Hi @DNXie ! I think this bug has been addressed now. I getting value error instead of [Colab ](https://colab.sandbox.google.com/gist/mohantym/69e5e1575579a85cc94199ca9f03da35/github_46698.ipynb)getting crashed. Thanks!

**Comment by DNXie** [comment]
@mohantym It seems to be fixed in the nightly version also. Thanks!
