### ISSUE TITLE
tf.keras.backend.reshape abortion when shape contain large values

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46693]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.backend.reshape` abortion when `shape` contain large values

**Describe the expected behavior**
expect an exception message if the input is not expected, instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.backend.reshape(x=[1], shape=np.array([21943, 45817, 30516, 61760, 38987], dtype=np.uint16))
~~~

Output:
~~~python
2021-01-26 15:32:50.289333: F tensorflow/core/framework/tensor_shape.cc:405] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1, nightly version(2.5.0-dev20210126) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a63148028cea8674427b82f612d8adeb/untitled636.ipynb). Thanks!

**Comment by yongtang** [comment]
Added a PR #46717 for the fix.

**Comment by DNXie** [comment]
@yongtang Thanks for th PR!

BTW I just found similar abortion in `tf.reshape` and `tf.contant`.

Here are the reproduce code:
~~~python
tf.reshape(tensor=[1], shape=np.array([21943, 45817, 30516, 61760, 38987], dtype=np.uint16))
tf.constant(value=np.ones((0,1,1)), shape=[36,23,53,24,117,82,47,124,112,69,53,0])
~~~

Could you please make sure that the PR also fixes these two APIs? Thanks!

**Comment by yongtang** [comment]
@DNXie Yes tf.reshape and tf.keras.backend.reshape are through the same kernel so both will be fixed.
