### ISSUE TITLE
Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 4] and a Java object with shape [1, 10,4]

### ISSUE THREAD

**Issue by MeysamSMH7** [tensorflow/tensorflow#46692]
Im useing tensorflow - object detection my questions is like this but!

https://stackoverflow.com/questions/57393407/java-lang-illegalargumentexception-cannot-copy-between-a-tensorflowlite-tensor

**java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 4] and a Java object with shape [1, 10,4].**

a guy answerd to this questions and sayed your should change in python side! but he didnt talk about which lines or which .py codes Im useing mobile_ssd_v2_float and too many people cant solve it! Is there any answers for this question?

this is pic of my .tflite file form Netron
![yez6b](https://user-images.githubusercontent.com/42836468/105861333-d9317e80-6003-11eb-91a4-452a60b7e632.png)

**Comment by abattery** [comment]
@lintian06 could you take a look at this?

**Comment by MeysamSMH7** [comment]
@abattery @lintian06 can you help?

**Comment by amahendrakar** [comment]
@MeysamSMH7,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by thaink** [comment]
@MeysamSMH7 The model you use and the model in that example have different outputs.
As you might see here https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java, the model we use have 4 outputs, while your model has one.

**Comment by MeysamSMH7** [comment]
@amahendrakar 
Version of TensorFlow is 1.2
And I'm using this one
Ssd_mobilenet_v2_coco_2018
Payton version is 2

**Comment by MeysamSMH7** [comment]
@thaink, hi
It's not possible!
I've changed input to [1,1917,4]
But I've got this error:
Invalid index 1

**Comment by thaink** [comment]
@MeysamSMH7 The problem here is the outputs not input.
Please compare you model with https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2?lite-format=tflite to see the differences.

**Comment by MeysamSMH7** [comment]
@thaink 
I know differences, but I can't use my own .tflite
Can I limitations for output model? Default is 1917 but maybe can change it into 10?

**Comment by thaink** [comment]
@MeysamSMH7 The difference is the TFLite_Detection_PostProcess op is added at the output of our models.
You can also try to add that following: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md
Please note the --add_postprocessing flag.
