### ISSUE TITLE
0.6.0 whl package named incorrectly as of 12/10 9am PST

### ISSUE THREAD

**Issue by ryneeverett** [tensorflow/tensorflow#467]
From #1:

> Closing since it seems to work. Python 3 support will ship with version 0.6.0, which is coming very soon. Future Python 3 bugs should be filed as separate issues!

In a python 2 virtualenv:

```sh
$ python --version
Python 2.7.10
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
...
Successfully installed protobuf-3.0.0a3 setuptools-18.7.1 tensorflow-0.6.0 wheel-0.26.0
```

In a python 3 virtualenv:

```sh
$ python --version
Python 3.4.3
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-cp34m-linux_x86_64.whl
tensorflow-0.6.0-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by vrv** [comment]
Yeah, we're still testing everything out today before announcing that it's ready.

Just curious, what happens if you download the wheel package and rename it tensorflow-0.6.0-cp34-none-linux_x86_64.whl ?

**Comment by ryneeverett** [comment]
@vrv Thanks, that worked! The python 3 installation instructions are already published in the docs so I assumed it was official.

```sh
$ python --version
Python 3.4.3
$ wget https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-cp34m-linux_x86_64.whl
...
$ mv tensorflow-0.6.0-cp34-cp34m-linux_x86_64.whl tensorflow-0.6.0-cp34-none-linux_x86_64.whl
$ pip install -U tensorflow-0.6.0-cp34-none-linux_x86_64.whl
...
Successfully installed numpy-1.10.1 protobuf-3.0.0a3 setuptools-18.7.1 six-1.10.0 tensorflow-0.6.0 wheel-0.26.0
```

**Comment by vrv** [comment]
Yeah, they shouldn't have been pushed to the docs until they were tested fully.  We'll probably just rename the wheel files.

**Comment by craigcitro** [comment]
new wheels with the updated filename are up.

i'll let @martinwicke close this once the website is updated.

**Comment by vrv** [comment]
Fixed!
