### ISSUE TITLE
Tesnorflow Sparse operations are slow - Comparison between Dense, SparseTensor and raw_ops sparse 

### ISSUE THREAD

**Issue by shanakap** [tensorflow/tensorflow#46706]
**System information**
- Tensorflow 2.4.0
- colab - basic settings

**Description**

I am trying to convert my code to run with `Sparse Matrices` on Tensorflow but looks like the performance is quite bad. I tried using `SparseTensor` and `tf.raw_ops.Sparse...` functions. Below is a comparsion for some of the functions. Pleaese refer the [colab code](https://colab.research.google.com/drive/1urRVOW4hR3i_7koNtXOnUTa5bhl7WXPC?usp=sharing) to generate the results.  

Following results are for a matrix with 75% zeros and time in seconds.  

|Method | Dense | SparseTensor | Raw_ops|
| --- | --- | --- | --- |
|Element-wise Multiplication	     | 0.0511	   |  0.5765	      |    0.5677|
|Exponential	                             |0.0438   	   |   0.0121	      |   0.0149 |
|Devision	                                     | 0.0625	   |   0.5718	      |   0.5614 |
|Reduce Sum                                |0.0194	   |    1.1918	      |   1.1648 |
|Matrix Multiplication	              |0.0576	   |   0.1589	      |  0.1553  |

Functions used:
|Method | Dense | SparseTensor | Raw_ops|
| --- | --- | --- | --- |
|Element-wise Multiplication	     | `tf.multiply()`	   | ` *`	      |   `tf.raw_ops.SparseDenseCwiseMul()`|
|Exponential	                             |`tf.exp()` 	   |  ` tf.sparse.map_values(tf.exp,x)`	      |` tf.exp(`)    |
|Devision	                                     | `tf.divide()`	   |  `/`      |  ` tf.raw_ops.SparseDenseCwiseDiv()` |
|Reduce Sum                                |`tf.reduce_sum()`   |    `tf.sparse.reduce_sum()`	      |   `tf.raw_ops.SparseReduceSum()` |
|Matrix Multiplication	              |`tf.matmul()`	   |  `tf.sparse.sparse_dense_matmul()`	      |  `tf.raw_ops.SparseTensorDenseMatMul()`  |

As per the results on sparse tensors, elementvise operations take 10x while Reduce_sum has taken 100x time to run.  

Is Tensorflow Sparse operations are written focusing on optimising the memory and not run time? Is there a fix for this?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/3298af6d440d21e42c7afc576290e040/46706.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d4d9aaf0d4cb9215c11c9a2c15254dd6/46706-tf-nightly.ipynb). 

Whereas with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/a9026321cd14b9c59445ae9c18f6e837/46706-2-3.ipynb#scrollTo=H1GhEvwu2fzC), I am facing an error stating `AttributeError: module 'tensorflow._api.v2.sparse' has no attribute 'map_values'`. Please check the linked gist for reference. Thanks!

**Comment by shanakap** [comment]
I believe 'map_values' was introduced in the latest `Tensorflow 2.4.0`.

**Comment by sjtusmartboy** [comment]
@rmothukuru hi,is there any update on this issue, because it has been half an year

**Comment by gowthamkpr** [comment]
@shanakap Please go through the following [solution](https://stackoverflow.com/questions/63127620/sparse-matrix-vs-dense-matrix-multiplication-c-tensorflow). Also please take a look at this [issue](https://wujigu.com/qa/?qa=1084328/tensorflow-how-to-perform-efficient-sparse-matrix-multiplication-by-using-tf-matmul) where its explained why sparse multiplication in slower than dense multiplication. Thanks!
