### ISSUE TITLE
tf.data.Dataset.list_files is increadibly slow on Tensorflow 2.3.1

### ISSUE THREAD

**Issue by orf** [tensorflow/tensorflow#46702]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Running the following snippet on Tensorflow 2.3.1 takes several minutes:

```python
import tensorflow as tf
tf.data.Dataset.list_files("s3://commoncrawl/*.txt")
```

The same snippet on Tensorflow 2.4.1 takes under a second. There is a single file in this path that matches. This makes this API unusable on 2.3.1.

If I run the command with `AWS_LOG_LEVEL=0` then I see there are a huge number of these messages:

```
2021-01-26 17:17:35.606039: I tensorflow/core/platform/s3/aws_logging.cc:71] Connection has been released. Continuing.
2021-01-26 17:17:35.607345: I tensorflow/core/platform/s3/aws_logging.cc:71] Connection has been released. Continuing.
2021-01-26 17:17:35.610330: I tensorflow/core/platform/s3/aws_logging.cc:71] Connection has been released. Continuing.
```

**Describe the expected behavior**

The snippet should execute instantly

**Standalone code to reproduce the issue**

Export your environment variables:

```
export AWS_REGION=us-east-1
export AWS_LOG_LEVEL=0
```

then run the following code:

```
import tensorflow as tf
tf.data.Dataset.list_files("s3://commoncrawl/*.txt")
```

**Other info / logs**

I've attached a complete log from running the above snippet. It's very large.

[out.log](https://github.com/tensorflow/tensorflow/files/5874958/out.log)

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3.1 and its taking some minutes please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b97889aee2275a606f5acf6ec53f5098/untitled632.ipynb).However the code runs instantly with TF version 2.4.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/17243a783a997f1130184e0a17a7c0b9/untitled633.ipynb).Thanks!

**Comment by rmothukuru** [comment]
@orf,
Since **`Tensorflow 2.4`** is the latest stable version, and it is working fine in this version, we suggest you to upgrade your Tensorflow Version to **`2.4`**. Thanks!

**Comment by orf** [comment]
I'm not sure if this is a good approach. Tensorflow 2.3 is still supported and receives updates.

**Comment by rmothukuru** [comment]
@orf,
Using the latest stable version is always the recommended approach. Do you have any problem in upgrading your TF Version?

**Comment by orf** [comment]
I guess not, but we are looking at using this more widely across many projects which may or may not have issues upgrading and would prefer to not have to foster that on them.

On top of that it's not really a backport or a minor incompatibility: the globbing mechanism just doesn't function on s3 at all on 2.3, which received a bugfix release only 22 days ago.

But it's your prerogative - if you wish to close this issue then that's up to you.

**Comment by krenerd** [comment]
This issue happened to me in TF 2.4.1. The following line took 10+ minutes to complete, while there were only 1,500 images in the directory. Although the images were 4K and the size of the data was around 50GB, it doesn't seem reasonable to take a such long time. 
```
tf.data.Dataset.list_files(div8k_save_path+'*.png')
```

**Comment by krenerd** [comment]
The code using `os.listdir` is extremely fast(~3secs) while `tf.data.Dataset.list_files` takes around 15 minutes. This issue still seems to happen in tf `2.4.1`.
```
div8k_list=[os.path.join(div8k_save_path, x) for x in os.listdir(div8k_save_path)]
train_path = tf.data.Dataset.from_tensor_slices(div8k_list)
```

**Comment by aaudiber** [comment]
@krenerd Does the slow listing happen only when the files are large, or does it happen with small/empty files as well? Also, does it still happen with the current `tensorflow==2.5.0rc3` release candidate?
