### ISSUE TITLE
floating point exception in tf.signal.stft 

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46701]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
floating point exception in `tf.signal.stft`

**Describe the expected behavior**
expect no crash

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.signal.stft(signals=np.array([3.2031196e+38], dtype=np.float32), frame_step=1, frame_length=1, fft_length=False, pad_end=True)
~~~

Output:
~~~python
Floating point exception (core dumped)
~~~

**Comment by Saduf2019** [comment]
@ymodak 
I ran the code on tf 2.4 and nightly the session crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5a87792308d2539e92c2e8abe772f182/untitled509.ipynb)

**Comment by ymodak** [comment]
Tested with TF 2.5, now the error is raised and session no longer crashes.
```python
InvalidArgumentError: Obtained a FFT shape of 0 elements: [1,0] [Op:RFFT]
```
