### ISSUE TITLE
tf.math.reduce_prod aborts when keepdims contain large values

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46700]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.math.reduce_prod` aborts when `keepdims` contain large values

**Describe the expected behavior**
expect an exception message if the input is not expected, instead of crash.

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.math.reduce_prod(input_tensor=1, keepdims=np.array([63600, 1], dtype=np.float16))
~~~

Output:
~~~python
2021-01-26 17:02:24.497049: F ./tensorflow/python/eager/pywrap_tensor_conversion.h:58] Check failed: !PyErr_Occurred()
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment]
@ymodak 
I ran the code on tf 2.4 and nightly but colab crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/0f6ab8c1a411eac72ae6e4502faed92b/untitled509.ipynb).

**Comment by yongtang** [comment]
Added a PR #46741 for the fix.
