### ISSUE TITLE
Typo Recognize Flowers with TensorFlow Lite on Android

### ISSUE THREAD

**Issue by georgezoto** [tensorflow/tensorflow#46718]
## URL(s) with the issue:
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android#4

## Description of issue (what needs changing):
Copy the TensorFlow Lite model model.tflite and label.txt that you trained earlier to assets folder at `lite/codelabs/flower_classification/start/app/src/main/assets/.`

The path used above is incorrect and needs to be updated to `lite/codelabs/flower_classification/android/start/app/src/main/assets/`

Thanks,
George

**Comment by abattery** [comment]
@lintian06  could you take a look?

**Comment by lintian06** [comment]
Thank you for the suggestion! It is going to be fixed soon. :-)

**Comment by ymodak** [comment]
I see the [codelab](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android#0) has been revamped and the issue no longer persists. Please let us know if you have any difficulties. Thanks!
