### ISSUE TITLE
different result on dict of tensors by getting `_enable_dict_to_input_mapping` in tf.python.keras.engine.functional.py

### ISSUE THREAD

**Issue by ericxsun** [tensorflow/tensorflow#46726]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Linux Ubuntu 18.04 
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1, 2.3.2, 2.3.0, cpu, gpu both
- Python version: 3.7

**Describe the current behavior**

`_enable_dict_to_input_mapping` of same dict of tensors `{'text': (a, b)}` is `False` in tf 2.4.1, but `True` in tf 2.3.2

**Describe the expected behavior**

expect same False or True

**Standalone code to reproduce the issue**

Tensorflow 2.3.2
```python
>>> import tensorflow as tf
>>> tf.__version__
'2.3.2'
>>> # copy from https://github.com/tensorflow/tensorflow/blob/9edbe5075f79a4a95ed14a2be831f9b59e61f49d/tensorflow/python/keras/engine/functional.py#L136
>>> from tensorflow.python.util import nest
>>> def get_enable_dict_to_input_mapping_232(_nested_inputs):
...     _enable_dict_to_input_mapping = (not nest.is_sequence(_nested_inputs) or (isinstance(_nested_inputs, (list, tuple, dict)) and not any(nest.is_sequence(t) for t in _nested_inputs)))
...     return _enable_dict_to_input_mapping

>>> a = tf.keras.Input(shape=(None,), dtype=tf.int32, name='a')
>>> b = tf.keras.Input(shape=(None,), dtype=tf.int32, name='b')
>>> c = {'text': (a, b) }

>>> get_enable_dict_to_input_mapping_232(c)
True
```

Tensorflow 2.4.1
```python
>>> import tensorflow as tf
>>> tf.__version__
'2.4.1'
>>> # copy from https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/functional.py#L142
>>> from tensorflow.python.util import nest
>>> def get_enable_dict_to_input_mapping_241(_nested_inputs):
...     if not nest.is_nested(_nested_inputs):
...         _enable_dict_to_input_mapping = True
...     elif (isinstance(_nested_inputs, (list, tuple)) and not any(nest.is_nested(t) for t in _nested_inputs)):
...         _enable_dict_to_input_mapping = True
...     elif (isinstance(_nested_inputs, dict) and not any(nest.is_nested(t) for t in _nested_inputs.values())):
...         _enable_dict_to_input_mapping = True
...     else:
...         _enable_dict_to_input_mapping = False
...     return _enable_dict_to_input_mapping

>>> a = tf.keras.Input(shape=(None,), dtype=tf.int32, name='a')
>>> b = tf.keras.Input(shape=(None,), dtype=tf.int32, name='b')
>>> c = {'text': (a, b) }

>>> get_enable_dict_to_input_mapping(c)
False
```

`_enable_dict_to_input_mapping` of same dict of tensors `{'text': (a, b)}` is `False` in tf 2.4.1 and `True` in tf 2.3.2

This leads to different result in `_flatten_to_reference_inputs` defined in [Functional._flatten_to_reference_inputs](https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/functional.py#L574)

- in tf 2.3.2, for `inputs = {'text': (a, b)}`, returns `[(a, b)]`, and then raise Exception  `AttributeError: 'tuple' object has no attribute '_keras_mask'` in [Functional._run_internal_graph](https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/functional.py#L536) while assigning `input_t._keras_mask = mask`
- in tf 2.4.1, for `inputs = {'text': (a, b)}`, returns `[a, b]`, and then all is okay while assigning `input_t._keras_mask = mask`

**Refs**

difference impl of getting `_enable_dict_to_input_mapping` in `tf.python.keras.engine.functional.py` between tf 2.4.1-[_enable_dict_to_input_mapping](https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/functional.py#L142) and tf 2.3.2 - [_enable_dict_to_input_mapping](https://github.com/tensorflow/tensorflow/blob/9edbe5075f79a4a95ed14a2be831f9b59e61f49d/tensorflow/python/keras/engine/functional.py#L136)

tf 2.4.1
```python
    if not nest.is_nested(self._nested_inputs):
      self._enable_dict_to_input_mapping = True
    elif (isinstance(self._nested_inputs, (list, tuple)) and
          not any(nest.is_nested(t) for t in self._nested_inputs)):
      self._enable_dict_to_input_mapping = True
    elif (isinstance(self._nested_inputs, dict) and
          not any(nest.is_nested(t) for t in self._nested_inputs.values())):
      self._enable_dict_to_input_mapping = True
    else:
      self._enable_dict_to_input_mapping = False

    if not keras_tensor.keras_tensors_enabled():
      if any(not hasattr(tensor, '_keras_history') for tensor in self.outputs):
        base_layer_utils.create_keras_history(self._nested_outputs)
```

tf 2.3.2
```
  self._enable_dict_to_input_mapping = (
        not nest.is_sequence(self._nested_inputs) or
        (isinstance(self._nested_inputs, (list, tuple, dict)) and
         not any(nest.is_sequence(t) for t in self._nested_inputs)))
```

**Additional**
I cannot upgrade tensorflow to 2.4.1 on the production env, since the cuda version is 10.1, does not supported by tensorflow 2.4.1 (it requires cuda 11.0), If I install tensorflow-gpu 2.4.1, I  cannot get the GPUs using `tf.config.list_physical_devices('GPU')` (empty list will be returned)

**Comment by amahendrakar** [comment]
@ericxsun,
Correct me if I am wrong but running the same code snippet on TF v2.3 and TF v2.4 produces identical results.

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/62b7e3e1a5f188500114b3f167713066/46726.ipynb). Thanks!

**Comment by ericxsun** [comment]
@amahendrakar available for checking ?

**Comment by ericxsun** [comment]
Any Tensorflower could be available checking?
