### ISSUE TITLE
FR for keras.preprocessing.image_dataset_from_directory label_mode parameter to accept enum as input

### ISSUE THREAD

**Issue by BlueskyFR** [tensorflow/tensorflow#46727]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When calling the `tf.keras.preprocessing.image_dataset_from_directory()` function, the parameter `label_mode=` accepts 3 values: `int`, `categorical` and `binary`. However, the string object is not deterministic: for that, I propose to add another option, which would be to specify the value using an enumeration which IS deterministic.

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Users who want more structured code.

**Any Other info.**

This behavior is, as far as I know, already available for some features in Keras.

**Comment by fchollet** [comment]
> However, the string object is not deterministic: for that, I propose to add another option, which would be to specify the value using an enumeration which IS deterministic.

What does that mean?

**Comment by BlueskyFR** [comment]
> > However, the string object is not deterministic: for that, I propose to add another option, which would be to specify the value using an enumeration which IS deterministic.
> 
> What does that mean?

By accepting a string as input, typos can be made and no autocompletion can be offered by the IDE, which is the case when using an enum.

**Comment by sachinprasadhs** [comment]
tf.keras.preprocessing.image_dataset_from_directory will be deprecated in future Tensorflow version, prefer loading data with [tf.keras.utils.image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory), and then transforming the output [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) with preprocessing layers.
Let us know if you still face an issue. Thanks!
