### ISSUE TITLE
Can't visualize plots from multiple log directories in Tensorboard after refreshing browser. Must close reopen tab.

### ISSUE THREAD

**Issue by eli7** [tensorflow/tensorflow#4672]
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
1. Run tensorboard for one log directory such as:
   tensorboard --logdir=some/directory1
2. View it on a browser
3. Run tensorboard for two log directories such as:
   tensorboard --logdir=somelabel1:some/directory1,somelabel2:some/directory2
4. Refresh the browser tab

Expected: two plots
Actual: only one plot
1. If you close the browser tab and then navigate to tensorboard again the two plots will be visible.
### What other attempted solutions have you tried?

Close reopen browser tab.
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

**Comment by concretevitamin** [comment]
@danmane: could you take a look?

**Comment by wchargin** [comment]
I'm not sure that I can reproduce this. When I write `tensorboard --logdir x:/tmp/data,y:/tmp/moredata`, I can view data from both logdirs, and this still holds on refresh.

If you can provide a consistent repro case, please feel free to reopen this issue in our new repository at https://github.com/tensorflow/tensorboard/issues. Thanks!
