### ISSUE TITLE
InvalidArgument error for space_to_batch function using half-float (fp16)

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#4673]
I am trying to execute atrous_conv2d operation using half-float (fp16) as input data type (float32 dataType works fine) but I get the following InvalidArgumentError:

**tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'Tower_0/conv2/atrous_conv2d/SpaceToBatch': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available**

Here is the software configuration:
OS: SLES 12
Tensor Flow: 0.10 (compiled from sources using Cuda 8.0.27 and cuDNN 5.1.5)
Python: 3.5.2
Bazel : 0.3.1

Is this a known issue? If so, in which Tensor Flow version will it be fixed?

**Comment by concretevitamin** [comment]
@benoitsteiner: the SpaceToBatch GPU kernel lacks half support.  Is this something already on your radar?  If not, we can just mark this as contributions welcome, of course.
