### ISSUE TITLE
bqml kmeans -> tflite: Call_once op doesn't support multiple subgraphs with inputs

### ISSUE THREAD

**Issue by loweew** [tensorflow/tensorflow#46737]
Filing on request of tflite group

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 & macOS 11.0.1
- TensorFlow installed from (source or binary): pip tf-nightly 
- TensorFlow version (use command below): 2.5.0-dev20210123 (git: v1.12.1-49539-g18d8bcbe72b)
- Python version: 3.7

**Describe the current behavior**
Export saved model from bqml to GCS. Load saved model and test:
![Screen Shot 2021-01-26 at 12 21 34 PM](https://user-images.githubusercontent.com/5230786/106028324-ccf80080-6099-11eb-9e45-a24188eee451.png)

create tflite model using from_saved_model:
![Screen Shot 2021-01-26 at 12 26 28 PM](https://user-images.githubusercontent.com/5230786/106028363-da14ef80-6099-11eb-8aa4-d7a2c13c848b.png)

load tflite model with interpreter to test:
![Screen Shot 2021-01-26 at 12 29 29 PM](https://user-images.githubusercontent.com/5230786/106028401-e39e5780-6099-11eb-93a4-3c229194501a.png)

**Describe the expected behavior**
Load tflite model and make predictions using interpreter to validate successful conversion

**Standalone code to reproduce the issue**
toy saved model from bqml k-means, notebook to repro, and tflite model can be found here: https://drive.google.com/drive/folders/1HfAU7ZK6CHvRFl_hSfw42RzlAfvXS-PJ?usp=sharing

**Comment by abattery** [comment]
Hi @loweew 

I can reproduce your issue on my side. Will take a look. Thanks

**Comment by abattery** [comment]
I have a working fix for this problem. However, it will take a while to submit the fix. I can share the converted model to you for verification.

https://drive.google.com/file/d/103ph9bHBYhR_NpLfHY4E-_k5HokmTAvm/view?usp=sharing

**Comment by loweew** [comment]
Great, I was able to load and allocate tensors successfully. But invoke failed:

![Screen Shot 2021-01-28 at 10 45 35 AM](https://user-images.githubusercontent.com/5230786/106164124-a8625e00-6157-11eb-9992-629042d62507.png)

I suspect this is a different issue, but I'm unable to verify that this is working for inference at this point. Are hash tables not supported using the tf builtin? Our end goal is the deploy a k-means model trained in bqml on iOS. So, if this is just a python issue, it's not the end of the world. But it would be nice to confirm this is working correctly in python before trying to implement it in iOS.

**Comment by abattery** [comment]
Actually, we provide hash table custom ops separately. We are working on adding them in the builtin op set. I verified the model working well with hash table custom ops.

Please take a look: https://www.tensorflow.org/lite/guide/ops_custom
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/kernels/hashtable
