### ISSUE TITLE
Support request for tanh activation function during quantization aware training (TensorFlow Model Optimization)

### ISSUE THREAD

**Issue by Nikolai10** [tensorflow/tensorflow#46733]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes 

**Describe the feature and the current behavior/state.**

When using `tfmot.quantization.keras.quantize_model()` to convert a `tf.keras.model` that uses a `tanh` activation function to a `tf.keras.model prepared for quantization,` the following error message appears:

**Case I:** ValueError: Only some Keras activations under `tf.keras.activations` are supported. For other activations, use `Quantizer` directly, and update layer config using `QuantizeConfig`.

Minimal example to reproduce:

```
import tensorflow as tf
import tensorflow_model_optimization as tfmot

i = tf.keras.layers.Input(shape=(24, 24, 3))
x = tf.keras.layers.Conv2D(10, kernel_size=1, activation='tanh')(i)
model = tf.keras.Model(inputs=i, outputs=x)

quant_aware_model = tfmot.quantization.keras.quantize_model(model)
```

**Case II:** Even worse - when specifying the activation function explicitly as `tf.nn.tanh(x)`, one receives the following misleading error message:

TypeError: in user code: TypeError: tf__call() got an unexpected keyword argument 'name'

Minimal example to reproduce:

```
import tensorflow as tf
import tensorflow_model_optimization as tfmot

i = tf.keras.layers.Input(shape=(24, 24, 3))
x = tf.keras.layers.Conv2D(10, kernel_size=1)(i)
x = tf.nn.tanh(x)
model = tf.keras.Model(inputs=i, outputs=x)

quant_aware_model = tfmot.quantization.keras.quantize_model(model)
```

**Will this change the current api? How?**

No, I'd expect minor changes. Please have a look at the class [QuantizeAwareActivation](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize_aware_activation.py): in line 76-77 the author states:

" TODO(pulkitb): Other activations such as elu, tanh etc., should just work on inclusion. Verify in TFLite before enabling."

**Who will benefit with this feature?**

All users that are interested in building tiny applications beyond classification/ recognition, which mainly uses softmax/ sigmoid activations.

**Any Other info.**

alternatively: please provide me with some more information, on how "to use the `Quantizer` directly", to replace the tanh activation function. Thank you very much.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/fb7ff601eff3309556e56711d28cf264/46733.ipynb). Thanks!

**Comment by Nikolai10** [comment]
any updates @daverim ?

**Comment by raminmohammadi** [comment]
any suggestion on this issue? I am encountering the same error.

**Comment by Nikolai10** [comment]
Hi @raminmohammadi, 

As a workaround, I manually insert fake quantization nodes into the computation graph:

#### 1. Define regular tf.keras model
```
tiny_model = ...
```

#### 2. Build model without tail (=tanh activation function)
```
idx = -3 # adjust idx to your use case (probably -2, check it by yourself)
model_no_tail = tf.keras.Model(inputs=tiny_model.input, outputs=tiny_model.layers[idx].output)
```

#### 3. Make model_no_tail quantization aware

```
quant_aware_model = tfmot.quantization.keras.quantize_model(model_no_tail)
```

#### 4. Add tail manually, by inserting a fake quantization node into the computation graph (simulates exact same behavior)
```
def add_tail(quant_aware_model):
    base_model=quant_aware_model
    x = tf.nn.tanh(base_model.output)
    x = tf.quantization.fake_quant_with_min_max_args(x, min=-1, max=1, num_bits=8, narrow_range=False, name=None)
    model=tf.keras.Model(inputs=base_model.input, outputs=x)
    return model

quant_aware_model = add_tail(quant_aware_model)
quant_aware_model.summary()
```

#### 5. Convert to fully-integer model (MCUs) after training:

```
tflite_models_dir = pathlib.Path(model_path)
tflite_models_dir.mkdir(exist_ok=True, parents=True)
quantized_tflite_encoder = tflite_models_dir/"tiny_model.tflite"

if not os.path.exists(model_path + "tiny_model.tflite"):
    converter = tf.lite.TFLiteConverter.from_keras_model(quant_aware_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model_quant = converter.convert()
    
    # Write it out to a tflite file:
    quantized_tflite_encoder.write_bytes(tflite_model_quant)
```

Hope that helps, good luck with your work! In case you find a better solution, feel free to share it here :)
