### ISSUE TITLE
RaggedTensor processing float type  causes memory leak

### ISSUE THREAD

**Issue by skywalker1990** [tensorflow/tensorflow#46735]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- TF 1.15.3
- Linux
- python 3.7

**Describe the current behavior**
text_input_flatten is a 3D tensor, [batch_size, seq_length, embedding_size], dtype=tf.float32
text_mask is a 2D tensor, [batch_size, seq_length], dtype=tf.bool

text_input_ragged = tf.RaggedTensor.from_tensor(text_input_flatten)
text_input_ragged = tf.ragged.boolean_mask(text_input_ragged, text_mask, name="ragged_text_input")
new_text_input = text_input_ragged.to_tensor(default_value=0)
new_length = tf.shape(new_text_input)[1]
new_text_input = tf.pad(new_text_input, [[0, 0], [0, seq_length * emb_size - new_length], [0, 0]], constant_values=0)

the memory usage is increasing rapidly, finally, the program will crash.
When I changed the text_input_flatten dtype to tf.int32, it works normally.

![memory](https://user-images.githubusercontent.com/8108725/106013911-e7f95d80-60f7-11eb-97e5-b4fe31c38bfc.png)
**Describe the expected behavior**

**Comment by ravikyram** [comment]
@skywalker1990 
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. 
If the issue persists in 2.4 version,can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by skywalker1990** [comment]
Sorry, the version of our production environment is 1.15.x. We have no plan to upgrade the version to 2.x yet.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
