### ISSUE TITLE
Some **function** symbols are exported as DATA from prebuilt Windows CPU tensorflow.dll

### ISSUE THREAD

**Issue by awson** [tensorflow/tensorflow#46730]
**System information**
- Windows 10 x64
- Used `libtensorflow-cpu-windows-x86_64-2.3.1.zip` binaries.

**Describe the current behavior**
When I build Haskell `tensorflow` package with my own MSVC toolset-based GHC, I get `undefined symbol` link errors for  `TF_GetCode`, `TF_Message`, `TF_DeleteStatus`, `TF_NewStatus`, `TF_SetStatus` symbols.

And indeed, inspecting `tensorflow.lib` import library I see that these symbols are exported as `DATA` symbols, and linker doesn't generate thunks for them. But they all are functions.

I suspect the tests don't catch this because if we testing a C/С++ code, the, e.g., Visual C++ complier  sees that these functions are declared as `__declspec(dllimport)` and correctly generates indirect calls for them, thus using `__imp_`-decorated names for these functions.

Also we shouldn't, perhaps, have the problems (I haven't tried this tho) when compiling this code with stock mingw-based GHC. This is because mingw tools (GNU ld + GCC startup code) implement runtime pseudo-relocs, which allows the client object code to link against `__imp_foo` anywhere the code expects `foo`.

I've glanced into the code and have understood that export of the symbols is implemented in a python script which uses heuristics to guess if it shall export the symbol as `DATA` or not.

Apparently these heuristics are broken.

Apart from this: if tensorflow API already have `TF_CAPI_EXPORT` annotations everywhere, why doesn't it use the standard  `dllexport` definition for `TF_CAPI_EXPORT` **when building** the library to export all relevant symbols, why does it implement some broken hard-to-maintain custom mechanism?

Sorry if this is a dumb question, there should exist compelling reasons to do so, I believe.

**Comment by mihaimaruseac** [comment]
It might be a mistake that showed up during code evolution. Sadly we didn't treat Windows with the same care as Linux.

**Comment by awson** [comment]
I haven't tested 2.6.0, but looked quickly into `tensorflow.lib` from 2.6.0 distro, and I see these particular symbols are now exported correctly.

**Comment by Saduf2019** [comment]
@awson 
lease move this to closed status as it is resolved now.
