### ISSUE TITLE
How to create representative_dataset with multiple inputs on TensorFlow Lite Converter?

### ISSUE THREAD

**Issue by henriwoodcock** [tensorflow/tensorflow#46732]
I cannot find any examples online, if I was to simulate data would it look like this?

```
def representative_dataset():
    for _ in range(100):
      data1, data2 = np.random.rand(1, 256), np.random.rand(1, 50)
      yield [data1.astype(np.float32), data2.astype(np.float32)]
```

**Comment by DaviesX** [comment]
The inputs seem to be fed in arbitrary order. Not sure why. tf lite doesn't seem to pay attention to the ordering of the input signatures.

**Comment by DaviesX** [comment]
> The inputs seem to be fed in arbitrary order. Not sure why. tf lite doesn't seem to pay attention to the ordering of the input signatures.

Sorry, I made a wrong observation. It appears that the ordering goes in consistent with the order of the input signatures.

**Comment by henriwoodcock** [comment]
Yes, got it working. If you need representative dataset use the method like above in my original post
