### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal:

### ISSUE THREAD

**Issue by paulemoe** [tensorflow/tensorflow#46738]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.4.1
- Python version:3.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am not able to install tensorflow using pip on anaconda (& sypder)
It has worked on my other Computer but not on the Windows10, i have uninstalled and reinstalled everything several times, but it just wont work. I can install other libraries, but not tensorflow - i do not understand why.

I know this post is a duplicate, but the answers in previous posts didnt help me since i am new to coding and everything....Sorry for bothering though
And no i do not want to use google collab, but install & use tensorflow on my computer

I would be very happy if someone could help me!!

**Provide the exact sequence of commands / steps that you executed before running into the problem**
ImportError: Traceback (most recent call last):
  File "C:\Users\go-pa\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Das angegebene Modul wurde nicht gefunden.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@paulemoe,
You might be facing this issue because of the following reasons

- You are running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions. 

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check this similar duplicate issue: [#46124](https://github.com/tensorflow/tensorflow/issues/46124#issuecomment-753665428)

Thanks!

**Comment by paulemoe** [comment]
Thank you for your answer!

- I am runnning 64-bit Python.
- I installed Microsoft Visual C++ Redistributable from the link and reinstallet python & tensorflow, didnt solved the issue
- I have an intel i5, very standart CPU, nothing fancy

tensorflow still refuses to run, any more advice?

**Comment by amahendrakar** [comment]
@paulemoe,
Thank you for the update. 

> * I have an intel i5, very standart CPU, nothing fancy

Could you please let us know the exact make and model of the CPU on your machine?

**Comment by Priyam2323** [comment]
This simply means that your anaconda version and tensorflow version are not compatible. So, in this case I uninstalled anaconda and then installed the latest version.
It worked.

**Comment by PooyanRezaeipour** [comment]
> Reference in new is



> This simply means that your anaconda version and tensorflow version are not compatible. So, in this case I uninstalled anaconda and then installed the latest version. It worked.

I uninstalled tensorflow by "pip uninstall tensorflow" and then reinstalled it by "pip install tensorflow". 
It works.
Thank you so much!

**Comment by Rakhilukky** [comment]
for many people does.nt work on 2024 or later because tnsorflow is stable on old version try uninstall them and use this
pip install pip==20.0.2 && pip install tensorflow==2.4.0

**Comment by mihaimaruseac** [comment]
Duplicate of #19584
