### ISSUE TITLE
GPU pip wheel cannot be used on a system without the GPU libraries installed

### ISSUE THREAD

**Issue by bc-lee** [tensorflow/tensorflow#4674]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I found some issues like #2653 but it wasn't really helpful.
### Environment info

Operating System: Ubuntu 16.04.1

Installed version of CUDA and cuDNN: CUDA 8.0 / cuDNN 5.1.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   558720 Sep 30 15:48 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep 30 15:48 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep 30 15:48 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Sep 30 15:48 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Sep 30 15:48 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Sep 30 15:50 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Sep 30 15:50 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Sep 30 15:50 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Sep 30 15:50 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:
1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

I've built TF from the source (latest r0.10 branch 931ff427f with cherry-picked 6d57860e3 (for avx2 issue)) with CUDA enabled.

```
$ bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

`python3 -c "import tensorflow; print(tensorflow.__version__)"` would normally work with GPU.

```
$ python3 -c "import tensorflow as tf; print(tf.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.8.0 locally
0.10.0
$ env | grep cuda
CUDA_HOME=/usr/local/cuda
LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
```

However, if I unset CUDA-related variables and SET `CUDA_VISIBLE_DEVICES=-1`(for using CPU Only), TF won't work.

```
$ unset LD_LIBRARY_PATH             
$ unset CUDA_HOME           
$ CUDA_VISIBLE_DEVICES=-1 python3 -c "import tensorflow as tf; print(tf.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leebc/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/leebc/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/leebc/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/leebc/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
```
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

**Comment by concretevitamin** [comment]
Can you try `CUDA_VISIBLE_DEVICES=none` or `CUDA_VISIBLE_DEVICES=''`?

**Comment by bc-lee** [comment]
Unfortunately, either `CUDA_VISIBLE_DEVICES=none` or `CUDA_VISIBLE_DEVICES=''` won't work. Do I need to build and test other branches?

**Comment by concretevitamin** [comment]
I think the in-preparation 0.11 release will fix this, but not at the 0.10 branch you're using.  Can you try it [here](https://github.com/tensorflow/tensorflow/tree/r0.11)?

**Comment by alquraishi** [comment]
Does the latest build at MASTER have this fix or no?

**Comment by bc-lee** [comment]
Well, neither [r0.11](https://github.com/tensorflow/tensorflow/tree/r0.11) and [master](https://github.com/tensorflow/tensorflow/tree/master) branches won't work. IIRC, this `CUDA_VISIBLE_DEVICES` variable works in r0.8 with some old CUDA and cuDNN. Do I need to bisect commits?

**Comment by zszhong** [comment]
in r0.10, using `export CUDA_VISIBLE_DEVICES="2"`, it works ok.

**Comment by vrv** [comment]
@zszhong I think the complaint is that the gpu pip wheel does not work if you don't have the GPU libraries installed.  CUDA_VISIBLE_DEVICES is not interpreted at all by TensorFlow code, it only affects how the driver makes the devices available to the process.

I don't remember it ever being the case that you could run the GPU pip build on a system without the GPU libraries installed.  It must be something related to the way our swig wrapper has a static linkage to the cuda libraries, even though the C++ code dynamically loads the library. @keveman or @zheng-xq, let me know if you have any ideas.

**Comment by zszhong** [comment]
@vrv, sorry that I'm not familiar with the internal tensorflow code, so I can't find the reasons from the in-depth viewpoint. I didn't use the official wheel files, and I always build and install tensorflow from source. In the branch of `r0.10`,  it works OK. The environment is `RedHat 64bit, GCC 4.8.4, Python 2.7, CUDA 7.0 with CuDNN 4.0`. Yes, It is probably related to the `CUDA 8.0`, I didn't use the `CUDA 8.0`.

I suggest @bc-lee to build tensorflow from source, because the official wheel may have any other dependencies that your machine doesn't have (although it might be built with static linkage). There are many experiences on how to build from source and it doesn't cost much time.  In addition, if the system didn't have GPU driver, why do you use the GPU wheel? I think you should use the CPU version. And if you have installed the driver, why do you use the CPU version?

**Comment by vrv** [comment]
Indeed, our current answer is: only install the GPU wheel on a machine that has the GPU libraries installed, otherwise install the CPU wheel.

However, it might be nice sometimes for people to be able to install one wheel that worked everywhere (even if it was more bloated) -- this issue is just tracking that feature request.  It's not something we're highly likely to work on any time soon given the hundreds of other issues we currently have, but if someone from the community is interested in digging in to figure it out, it would be appreciated :).

**Comment by bc-lee** [comment]
@zszhong I use TF by building it from source, not from official wheel(which is linked against CUDA 7.5 / cuDNN 5).

@vrv Understood. Sometimes I'd like to run TF without any GPU use along with GPU-using TF running. Installing two versions of TF (using virtualenv) might help, but I was curious if I can disable GPU feature completely using `CUDA_VISIBLE_DEVICES`. This issue isn't crutial issues than other Tons of issues, but It would be awesome if single wheel file works both GPU and CPU version. I'll remain this issue be open.

**Comment by gunan** [comment]
@bc-lee If you have a system that has a GPU, you can install the GPU tensorflow version, but only run your code on CPU. GPU pip wheel file will still allow you to run your graph on CPU.
You can then run another process, start another process, which runs your code on GPU. But to be able to do that, you have to have a machine with GPU, with CUDA and CuDNN installed.
I do not see the direct relation of the use case you described to being able to install a TF GPU pip package on a machine with no GPU. 
If you were asking a TF package that came with all GPU drivers, CUDA and CuDNN, that is not possible due to different constraints in the licenses of all these software.

**Comment by yaroslavvb** [comment]
@bc-lee you can disable GPU completely by using `CUDA_VISIBLE_DEVICES`

At Google the preference was to use "fat binary" approach -- single binary that bundles GPU drivers and works on both GPU and non-GPU machines. The annoyance of open-source world is that GPU drivers have to be installed separately and can be missing on machines without a physical GPU. A way to simplify things is to install GPU drivers on all machines, whether or not physical GPU is present, and use a GPU-binary.

**Comment by gunan** [comment]
As a workaround, You can install nvidia drivers and cuda on your system even if you do not have a NVIDIA GPU and install the GPU version. Or if you have a GPU and install the GPU version, you can use `CUDA_VISIBLE_DEVICES` environment variable to run TensorFlow only on CPU.

I will close this issue as there has not been any updates for a long time, but we have a few initiatives which can help with this issue in the long term.

**Comment by rosbo** [comment]
@gunan, sorry to revive this thread (I am happy to create a separate issue if you prefer), but you mentioned:

> You can install nvidia drivers and cuda on your system even if you do not have a NVIDIA GPU and install the GPU version

I did just that (on a machine without a GPU but with nvidia drivers installed and `CUDA_VERSION` and `NVIDIA_VISIBLE_DEVICES` to ``) and it works but I still get these annoying log messages the first time I create a session:

```
> python -c 'import tensorflow as tf; tf.Session()'
2018-09-12 00:56:38.003223: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUresult(-1)
2018-09-12 00:56:38.003303: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on 
this host (8c18459333df): /proc/driver/nvidia/version does not exist
```

Is there another environment variable I can set to prevent the GPU build from trying to initialize cuda when running without a physical GPU?

Thank you

**Comment by gunan** [comment]
You may be able to set TF_CPP_MIN_LOG_LEVEL, but that may also block any errors you may have during graph creation and execution.

**Comment by rosbo** [comment]
Thank you @gunan but like you mentioned, hiding errors isn't ideal for our users.

You mentioned above that "we have a few initiatives which can help with this issue in the long term", do you have any issues tracking these?

**Comment by gunan** [comment]
None on public side, but we are hoping we can merge some of these soon.
