### ISSUE TITLE
Loading and stitching TF graphs has tf.Variable conflict even if using the name scope in loading

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#46745]
**System information**
- OS Platform and Distribution: MacOS Catalina 10.15.6
- TensorFlow installed: from binary
- TensorFlow version: The issue could be reproduced by TF1.x (TF 1.15.2) and TF2.x (TF 2.4.1)
- Python version: 3.6.5

**Describe the current behavior**
I have the following code `tf_stitch_keras_model_build_save.py` that simply creates a TF Keras model and saves it into a checkpoint. I ran the Python script twice and generated two checkpoints `./foo/model` with input shape 4 and output shape 3 (by running `$ python tf_stitch_keras_save.py -i 4 -o 3 -p ./foo/model`) and `./bar/model` with input shape 3 and output shape 2 (by running `$ python tf_stitch_keras_save.py -i 3 -o 2 -p ./bar/model`). Then I ran another Python script `python tf_stitch_keras_restore.py -p1 ./foo/model -p2 ./bar/model` that is supposed to load these two checkpoints into a new TF graph with model foo's output stitching to model bar's input.

- tf_stitch_keras_model_build_save.py:
```
import argparse
from typing import Tuple

import numpy as np
import tensorflow.compat.v1 as tf
from tensorflow.keras import models
from tensorflow.keras import layers

tf.disable_v2_behavior()


def build_model(input_shape: int, output_shape: int) -> Tuple[tf.Tensor, tf.Tensor]:
    graph = tf.get_default_graph()
    with graph.as_default():
        model = models.Sequential()
        model.add(layers.Dense(16, activation='relu', input_shape=(input_shape,), name="layer_0"))
        model.add(layers.Dense(16, activation='relu', name="layer_1"))
        model.add(layers.Dense(output_shape, activation='sigmoid', name="layer_2"))

        input_tensor = tf.placeholder(dtype=tf.float32, shape=[None, input_shape])
        output_tensor = model(input_tensor)
        graph.add_to_collection("INPUT", input_tensor)
        graph.add_to_collection("OUTPUT", output_tensor)
    return input_tensor, output_tensor


def save_model(sess: tf.Session, path: str) -> None:
    saver = tf.train.Saver()
    sess.run(tf.global_variables_initializer())
    save_path = saver.save(sess, path)
    print(f"Saved the model in {save_path}")


def parse_arguments() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input_shape", type=int)
    parser.add_argument("-o", "--output_shape", type=int)
    parser.add_argument("-p", "--path", type=str)
    return parser


def main():
    parser = parse_arguments()
    args = parser.parse_args()
    input_tensor, output_tensor = build_model(args.input_shape, args.output_shape)
    print(f"Finished building the model: Input tensor {input_tensor} and output tensor {output_tensor}.")
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    res = sess.run(output_tensor, feed_dict={input_tensor: np.random.rand(1, args.input_shape)})
    print(f"The random output is {res}.")
    save_model(sess, args.path)


main()
```
-  tf_stitch_keras_restore.py:
```
import argparse
from typing import Dict, List

import tensorflow.compat.v1 as tf


def load_and_stitch_graph(
    path: str,
    sess: tf.Session,
    input_map: Dict[str, tf.Tensor],
    return_values: List[str],
    scope: str = "",
) -> List[tf.Tensor]:
    """
    :param path: The path of the model to be loaded from.
    :param sess: The tensorflow session for loading a model.
    :param input_map: dict key is the tag name of the tensor for another Tensor as
           dict value stitches to.
    :param return_values: The tag name for the returned tensors.
    :param scope: The name used for loading a model.
    :return:
    """
    # Load the checkpoint in the tmp graph.
    tmp_graph = tf.Graph()
    with tmp_graph.as_default():
        saver = tf.train.import_meta_graph(path + ".meta", import_scope=scope)

    # Structure the input map for stitching the graph when loading.
    input_map_for_import_graph_def = {
        tmp_graph.get_collection(key)[0].name: val
        for key, val in input_map.items()
    }
    return_values_for_import_graph_def: List[tf.Tensor] = [
        tmp_graph.get_collection(val)[0].name
        for val in return_values
    ]

    # Load and stitch.
    with sess.graph.as_default():
        return_tensors = tf.import_graph_def(
            tmp_graph.as_graph_def(),
            input_map=input_map_for_import_graph_def,
            name="",
            return_elements=return_values_for_import_graph_def
        )
        # only restore if there's something to restore
        if saver is not None:
            saver.restore(sess, path)

    return return_tensors


def parse_arguments() -> argparse.ArgumentParser:
    """
    Stitch the model loaded from path1 to the model loaded from path2.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("-p1", "--path1", type=str)
    parser.add_argument("-p2", "--path2", type=str)
    return parser


def main():
    parser = parse_arguments()
    args = parser.parse_args()
    graph = tf.get_default_graph()
    sess = tf.Session(graph=graph)

    with graph.as_default():
        input1, output1 = load_and_stitch_graph(
            path=args.path1,
            sess=sess,
            scope="foo",
            input_map={},
            return_values=["INPUT", "OUTPUT"]
        )

        out2 = load_and_stitch_graph(
            path=args.path2,
            sess=sess,
            scope="bar",
            input_map={"INPUT": output1},
            return_values=["OUTPUT"]
        )
    sess.run(out2[0], feed_dict={input1: [[1, 2, 3, 4]]})


main()

```

However, when it tries to load model `bar` and stitches the graph with model `foo`, `tf.import_graph_def` crashes with the following error:
```
Traceback (most recent call last):
  File "/Users/rukon/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/Users/rukon/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/Users/rukon/tf2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible: In[0]: [1,4], In[1]: [3,16]
	 [[{{node foo/sequential/layer_0/Relu}}]]
```
After digging into the error, looks there is a tf.Variable conflict even though we added the name scope during loading model, and it tries to hook up the model "bar" first hidden layer to the model "foo" input, my best guess is internally somehow tf.Variables are messed up on reference. I understand Tensorflow would deprecate the usage of tf graph as well as its utilities, but currently wrt the backward compatibility with TF 1.x, I'd expect it should still work.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
The issue could be 100% reproduced by running the above code with the system info.

**Comment by ravikyram** [comment]
@RuofanKong 

I tried to run your code in colab and i am seeing the error as mentioned in the [gist](https://colab.research.google.com/gist/ravikyram/1a641d259acedfbfb5b2d9be8f4cfdab/untitled638.ipynb).
Can you please share colab notebook or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by RuofanKong** [comment]
@ravikyram I ran it locally with provided sys info and command and that script `tf_stitch_keras_save.py` all consistently works. Are you sure you are using the exactly same Tensorflow and Python version? Also, I'm new to colab notebook, could you share more details?

**Comment by RuofanKong** [comment]
@ravikyram I see why yours don't work. When you run `tf_stitch_keras_save.py` and `tf_stitch_keras_restore.py` scripts, you need to pass the inline arguments as I shared in the reproduce steps above. Let me share it here again so you're clear on it:
1. Run command: `$ python tf_stitch_keras_save.py -i 4 -o 3 -p ./foo/model` to build and save the model "foo".
2. Run command: `$ python tf_stitch_keras_save.py -i 3 -o 2 -p ./bar/model` to build and save the model "bar".
3. Run command: `$ python tf_stitch_keras_restore.py -p1 ./foo/model -p2 ./bar/model` to load models "foo" and "bar" and stitch them together, then you will hit the error that I showed above.

**Comment by ymodak** [comment]
Thanks for the issue. I was able to repro the reported behavior with [gist](https://colab.research.google.com/gist/ymodak/72f524cdeb176eddee1fccc1059680f4/untitled638.ipynb).

**Comment by RuofanKong** [comment]
Any updates on this?
