### ISSUE TITLE
Distributed training for transformer model.

### ISSUE THREAD

**Issue by Zotec-exe** [tensorflow/tensorflow#46744]
Hello,

I am attempting to adapt TensorFlow's transformer tutorial to work on multiple GPUs using there distributed training tutorial,

Transformer: https://www.tensorflow.org/tutorials/text/transformer
Distributed training: https://www.tensorflow.org/tutorials/distribute/custom_training

However, when I execute the program I get the error: "TypeError: train_step() argument after ** must be a mapping, not Tensor" in `per_replica_losses = strategy.run(train_step, args=(inp, tar),)`.

The code that is causing the issue is as follows:
`train_step_signature = [
    tf.TensorSpec(shape=(None, None), dtype=tf.int64),
    tf.TensorSpec(shape=(None, None), dtype=tf.int64),
]

@tf.function(input_signature=train_step_signature)
def train_step(inp, tar):
  #inp, tar = dataset_inputs
  tar_inp = tar[:, :-1]
  tar_real = tar[:, 1:]

  enc_padding_mask, combined_mask, dec_padding_mask = create_masks(inp, tar_inp)

  with tf.GradientTape() as tape:
    predictions, _ = transformer(inp, tar_inp,
                                 True,
                                 enc_padding_mask,
                                 combined_mask,
                                 dec_padding_mask)
    loss = loss_function(tar_real, predictions)

  gradients = tape.gradient(loss, transformer.trainable_variables)
  optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))

  train_loss(loss)
  train_accuracy(accuracy_function(tar_real, predictions))`

@tf.function(input_signature=train_step_signature)
def distributed_train_step(inp, tar):
  per_replica_losses = strategy.run(train_step, args=(inp, tar),)

  return strategy.reduce(tf.distribute.ReduceOp.SUM, per_replica_losses,
                         axis=None)

for epoch in range(EPOCHS):
  start = time.time()
  BatchTime = time.time()

  train_loss.reset_states()
  train_accuracy.reset_states()

  for (batch, (dataset_inputs)) in enumerate(train_dataset):

      distributed_train_step(dataset_inputs)

      if batch % 50 == 0:

           print ('Epoch {} Batch {} Loss {:.4f} Accuracy {:.4f}'.format(epoch + 1, batch, train_loss.result(), train_accuracy.result()))

      if batch % 100 == 0:
          ckpt_save_path = ckpt_manager.save()
          print ('Saving checkpoint for batch {} at {}'.format(batch,
                                                                 ckpt_save_path))
          print("Time taken: {}".format(time.time() - BatchTime))
          BatchTime = time.time()

  print ('Epoch {} Loss {:.4f} Accuracy {:.4f}'.format(epoch + 1,
                                               train_loss.result(),
                                              train_accuracy.result()))
print ('Time taken for 1 epoch: {} secs\n'.format(time.time() - start))`

Thanks

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1c8330f8697cc271fe92d1865ce9a574/46744.ipynb#scrollTo=bJlf26srz1ur). Thanks!

**Comment by nikitamaia** [comment]
Hi @Zotec-exe, are you distributing the dataset? Please see[ this section of the docs](https://www.tensorflow.org/tutorials/distribute/custom_training#setup_input_pipeline) that explains the use of ` strategy.experimental_distribute_dataset` to wrap your dataset for `MirroredStrategy` with custom training loops.

**Comment by Zotec-exe** [comment]
Yes i am, i should of mentioned.

This is my version to prepare the dataset:

```train_dataset = train_examples.map(tf_encode)
train_dataset = train_dataset.filter(filter_max_length)


train_dataset = train_dataset.shuffle(BUFFER_SIZE).padded_batch(BATCH_SIZE)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)
train_dataset = strategy.experimental_distribute_dataset(train_dataset)

val_dataset = val_examples.map(tf_encode)
val_dataset = val_dataset.filter(filter_max_length).padded_batch(BATCH_SIZE)
val_dataset = strategy.experimental_distribute_dataset(val_dataset)

**Comment by nikitamaia** [comment]
Ah okay. Please provide a fully reproducible colab with your training code so that nothing gets lost.

**Comment by Zotec-exe** [comment]
Here's a link:

https://colab.research.google.com/drive/1CWmHaonRfKno2cjUMyl__SGUG1mA1c-A?usp=sharing

**Comment by nikitamaia** [comment]
just a thought, but I wonder if the problem is that `train_step` function does not return the loss. See example of 1train_step1 in the tutorial [here](https://www.tensorflow.org/tutorials/distribute/custom_training#training_loop).
