### ISSUE TITLE
error: 'tfl.max_pool_2d' op quantization parameters violate the same scale constraint

### ISSUE THREAD

**Issue by suakim** [tensorflow/tensorflow#46754]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): tf-nightly 2.5.0.dev20210112

### 2. Code

https://colab.research.google.com/drive/18SeujsYiwNr3bwpamGBnQ09EG8ord7I2#scrollTo=BOs2yEVkHRmx

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    216                                                  debug_info_str,
--> 217                                                  enable_mlir_converter)
    218       return model_str

5 frames
Exception: /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:206:0: error: 'tfl.max_pool_2d' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 0.04703366522695504:-1> vs. !quant.uniform<i8:f32, 0.047032601225609871:-1>
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/pooling.py:300:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize_wrapper.py:167:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:625:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1032:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:563:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:428:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1032:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/tflite_keras_util.py:184:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:612:0: note: called from

During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    218       return model_str
    219     except Exception as e:
--> 220       raise ConverterError(str(e))
    221 
    222   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:206:0: error: 'tfl.max_pool_2d' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 0.04703366522695504:-1> vs. !quant.uniform<i8:f32, 0.047032601225609871:-1>
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/pooling.py:300:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize_wrapper.py:167:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:625:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1032:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:563:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:428:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1032:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/tflite_keras_util.py:184:0: note: called from
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py:612:0: note: called from

**Comment by suakim** [comment]
Is there any updates?

**Comment by teijeong** [comment]
Hello, sorry for late response.

will take a look - I think recently added `DownCastScale` method might have caused discrepancy between scales, but need to check.

https://github.com/tensorflow/tensorflow/search?q=downcastscale

**Comment by suakim** [comment]
Hello, thanks for the reponse. I just tried it with tf 2.4.1 (not tf-nightly), but had the same error. Please find the attached [code](https://colab.research.google.com/drive/1iVxnf1hfDt3R5XOJ3-4yiOzRjQ9d3UMb?usp=sharing)

**Comment by teijeong** [comment]
Thanks for testing :) in that case the problem lies in somewhere else, will take a look.

**Comment by Xhark** [comment]
The main problem is current QAT toolkit doesn't support concat op yet. 
(concat op inputs should have the same scale, so this scale guessing algorithm may have some problem.)

if you are okay to use add op instead of concat op, then it seems works fine.

**Comment by suakim** [comment]
@Xhark, thank you for the answer. Yes it works now after changing 'concat' to 'add'.
