### ISSUE TITLE
An error when loading quantized model 

### ISSUE THREAD

**Issue by suakim** [tensorflow/tensorflow#46755]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): tf-nightly 2.5.0.dev20210112

**Provide the text output from tflite_convert**

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-774313fb0438> in <module>()
    156     else:
    157         with quantize_scope:
--> 158             loaded_model = tf.keras.models.load_model('q_aware_model_fine_tuned.h5')
    159         inputs = [tf.keras.layers.Input(shape=(height, width, 1), name="input_{}".format(i)) for i in range(4)]
    160         q_aware_model = tf.keras.models.Model(inputs, loaded_model(inputs))

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    706     symbolic_weights = _legacy_weights(layer)
    707     weight_values = preprocess_weights_for_loading(
--> 708         layer, weight_values, original_keras_version, original_backend)
    709     if len(weight_values) != len(symbolic_weights):
    710       raise ValueError('Layer #' + str(k) + ' (named "' + layer.name +

ValueError: Layer #9 (named "quant_activation" in the current model) was found to correspond to layer quant_activation in the save file. However the new layer quant_activation expects 3 weights, but the saved weights have 1 elements.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/181562QquolAr3Yz5eKflZMH0zLKrzpSF?usp=sharing

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by Saduf2019** [comment]
@suakim 
I ran the code shared an face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/430e7c03d0a9b53a5f378e8aea44f3f7/untitled513.ipynb), please share all dependencies to replicate and analyse issue faced.

**Comment by suakim** [comment]
Please check this file in google drive and let me know if you can't download: https://drive.google.com/file/d/1AViTqRry0K-P1ELZJ5_Y2yU_9ZIiohm6/view?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/32f98f3970d3d5fc89852434fb523845/untitled516.ipynb)

**Comment by ymodak** [comment]
Can you try using `tf` format to save and load model instead of `h5` and check if that works? Thanks!

**Comment by suakim** [comment]
Hello, I tried to save the model by using q_aware_model.save('q_aware_model_fine_tuned'), but failed to load this model. Is it the same way with what you suggested? The error is as below: 
AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program: [<tf.Variable 'output_min:0' shape=() dtype=float32, numpy=-6.0>, <tf.Variable 'output_min:0' shape=() dtype=float32, numpy=-6.0>, <tf.Variable 'output_max:0' shape=() dtype=float32, numpy=6.0>, <tf.Variable 'output_max:0' shape=() dtype=float32, numpy=6.0>, <tf.Variable 'output_max:0' shape=() dtype=float32, numpy=6.0>, <tf.Variable 'output_min:0' shape=() dtype=float32, numpy=-6.0>]

I attached the code [here](https://colab.research.google.com/drive/1q9fuKSz-XZSM2mCm9P6DknJ9wx_NAYOJ?usp=sharing)

**Comment by j-o-d-o** [comment]
@suakim whats the reason for closing the issue? Did you solve the problem? I am still facing the exact same thing.
