### ISSUE TITLE
Recommend replacement list for some incompatible ops in TFLite

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#46753]
Hi TensorFlow Lite Authors,  

It's glad to hear that there are some workaround for incompatible ops, such as ResizeOp, in TFLite. Would you mind share something like recommend replacement list for some of these bad ops? It will take us away from some troubles on early stage, the design stage, not the model deployment stage that things all are embarrassed to developers.

Looking for your reply,
Sun Aries.

**Comment by SunAriesCN** [comment]
@liyunlu0618

**Comment by liyunlu0618** [comment]
Some context. During the cn-sig group discussion about MOT, user asked about incompatible ops like ResizeNearestNeighbor and Renjie mentioned it could be replaced with other TFLite compatible ops. This request is for us to provide a list with such examples as guidance.

**Comment by mohantym** [comment]
Hi @SunAriesCN !
Attached list of  [built in ops ](https://www.tensorflow.org/mlir/tfl_ops)and[ select ops](https://www.tensorflow.org/lite/guide/op_select_allowlist) .  You can also [register a custom operator ](https://www.tensorflow.org/lite/guide/ops_custom)in cpu and gpu kernel now. 

Can the above pointers be considered as  answer to your query?

Thank you!


To disable quantization and debug your lite model, You can use [tfl.quantization_debugger](https://www.tensorflow.org/lite/performance/quantization_debugger)
