### ISSUE TITLE
numpy() is not working on Tensor object in TF2.x

### ISSUE THREAD

**Issue by Alok-Ranjan23** [tensorflow/tensorflow#46765]
**Please consider the following code snippet**

from tensorflow.keras.layers import Layer

class SimpleDense(Layer):
    
    def __init__(self, units=32):
        '''Initializes the instance attributes'''
        super(SimpleDense, self).__init__()
        self.units = units

    def build(self, input_shape):
        '''Create the state of the layer (weights)'''
        # initialize the weights
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(name="kernel",
            initial_value=w_init(shape=(input_shape[-1], self.units),
                                 dtype='float32'),
            trainable=True)

        # initialize the biases
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(name="bias",
            initial_value=b_init(shape=(self.units,), dtype='float32'),
            trainable=True)

    def call(self, inputs):
        '''Defines the computation from inputs to outputs'''
        print(inputs.numpy().shape)
        print(self.w.numpy().shape)
        print(tf.matmul(inputs,self.w).numpy().shape)
        print(self.b.numpy().shape)
        print((tf.matmul(inputs,self.w)+self.b).numpy().shape)
        return tf.matmul(inputs, self.w) + self.b

my_dense = SimpleDense(units=1)
x = tf.ones((3, 2))
y = my_dense(x)   # I am able to execute all the print of the call method.

xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

my_layer = SimpleDense(units=1)
model = tf.keras.Sequential([my_layer])
model.compile(optimizer='sgd', loss='mean_squared_error')
model.fit(xs, ys, epochs=500,verbose=0)  # I am not able to execute any of the print of the call method.

- There error is following.
AttributeError: in converted code:
        print(inputs.numpy().shape)

    AttributeError: 'Tensor' object has no attribute 'numpy'

_**I am not able to understand the above error as per my knowledge Tensor object has numpy() attribute available in tf2.x version and I am using TF2.0**_

Please Explain why i am getting the above error. It will be very helpful.

**Comment by Alok-Ranjan23** [comment]
Hi @WindQAQ , As per my knowledge eager_execution is **by-default** in TF2.x. Then why you are telling me to set  **run_eagerly=True** in model.compile(...) whereas i think that it is already set True in TF2.x. Please explain.

**Comment by WindQAQ** [comment]
> As per my knowledge eager_execution is **by-default** in TF2.x.
Correct.

> Then why you are telling me to set **run_eagerly=True** in model.compile(...) whereas i think that it is already set True in TF2.x. 

For keras model compilation, it is set to False for performance issue.

![image](https://user-images.githubusercontent.com/11615393/106235408-77157c80-61af-11eb-9dbe-28b5b52a3d30.png)

**Comment by Alok-Ranjan23** [comment]
Thanks @WindQAQ ,

As per my understanding, there are two eager environment, One (i.e. TF2.x eager mode) is set as True and Other (i.e. tf.keras eager_mode) is set as False so that it will run inside tf.function for performance issue. Am i correct?

Does setting **eager_mode as True in TF2.x** not affect TF2.x performance with respect to TF1.x? 

Can you please provide a link for tf.function documentation?

**Comment by WindQAQ** [comment]
> As per my understanding, there are two eager environment, One (i.e. TF2.x eager mode) is set as True and Other (i.e. tf.keras eager_mode) is set as False so that it will run inside tf.function for performance issue. Am i correct?
> Does setting **eager_mode as True in TF2.x** not affect TF2.x performance with respect to TF1.x?

Here is a more detailed explanation of `tf.function`. For performance, in most cases, eager context will introduce some overhead, but `tf.function` makes the certain piece of your program (typically the training/inference pipeline) run in graph mode, so that the overhead is removed.

https://www.tensorflow.org/guide/function

> Can you please provide a link for tf.function documentation?

https://www.tensorflow.org/api_docs/python/tf/function?version=nightly

**Comment by Alok-Ranjan23** [comment]
Thanks @WindQAQ ,

**If** I will create my model without using tf.keras, then **tf.function** will be in picture or not?

**Comment by WindQAQ** [comment]
> **If** I will create my model without using tf.keras, then **tf.function** will be in picture or not?

Nope, you should decorate it in your own.

**Comment by Alok-Ranjan23** [comment]
Hi @WindQAQ ,

How did TF2.x handle **eager_mode=True(default)** performance overhead if it will not use tf.function

**Comment by WindQAQ** [comment]
Unfortunately, most optimizations occurs in graph mode so it's recommended to use `tf.function`. Is there any reason that you don't or you can't use it?

**Comment by Alok-Ranjan23** [comment]
Hi @WindQAQ ,
As you have said that in reply of that(If I will create my model without using tf.keras, then tf.function will be in picture or not?),
It will not use tf.function, So the performance will degrade in TF2.x if i will not use my own written tf.function. Am i correct?

Can i run TF2.x code(without tf.keras) without using tf.function?

**Comment by WindQAQ** [comment]
> As you have said that in reply of that(If I will create my model without using tf.keras, then tf.function will be in picture or not?),
> It will not use tf.function, So the performance will degrade in TF2.x if i will not use my own written tf.function. Am i correct?

Correct.

> Can i run TF2.x code(without tf.keras) without using tf.function?

Yes you can, just not to decorate your function with `tf.function`. When you want, just do

```python
@tf.function
def func():
    # Your function
```

**Comment by Alok-Ranjan23** [comment]
Thank you @WindQAQ , closing this issue now, Thank you for the clarification.
