### ISSUE TITLE
Multiheadattention layer dimensions

### ISSUE THREAD

**Issue by je-santos** [tensorflow/tensorflow#46760]
## This works ok
inputs = Input(shape=[1800])
y = MultiHeadAttention(num_heads=10,
key_dim=10,
use_bias=False,
attention_axes = 0,
)(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary())

## This is not working properly:

inputs = Input(shape=[1800,1]). # added channel dim here
y = MultiHeadAttention(num_heads=10,
key_dim=10,
use_bias=False,
attention_axes = 0,
)(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary())

**Comment by amahendrakar** [comment]
@je-santos,
I was able to run the code without any issues with TensorFlow v2.4. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/771a3515014438784017faacdb81816f/46760.ipynb). Thanks!

**Comment by je-santos** [comment]
Hi, the code runs all right. But the dimensions are not correct. In the second case the dense layers do not have the right number of parameters.
