### ISSUE TITLE
MHA not attending the specified dimension

### ISSUE THREAD

**Issue by je-santos** [tensorflow/tensorflow#46762]
Hi, it looks like if I add a channel dimension, the number of parameters in the Dense layer is no longer correct:
This is ok:

inputs = Input(shape=[1800])
y = MultiHeadAttention(num_heads=10,
key_dim=10,
use_bias=False,
attention_axes = 0,
)(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary())  # This shows that we have 720,000  parameters
This is not:

inputs = Input(shape=[1800,1]). # added channel dim here
y = MultiHeadAttention(num_heads=10,
key_dim=10,
use_bias=False,
attention_axes = 0,  #if this is set to None the same error persists
)(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary()) # this is not correct, it shows 400 parameters, although I specify to attend the first axis

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4, nightly version (`2.5.0-dev20210129`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cecbb03c0bfd90335a36bd0ebac44708/untitled645.ipynb). Thanks!

**Comment by saberkun** [comment]
inputs = Input(shape=[1800]) is not a valid input to MHA.
inputs = Input(shape=[1800,1]). is valid. [batch size, 1800, 1]
The expected number of params is indeed 400 = 10 * 10 * 4, where 10 * 10 is for q, k, v and output projection matrices. The attention axis should be the sequence dimension, which is 1800.
