### ISSUE TITLE
PoseNet model readme points to the wrong paper reference

### ISSUE THREAD

**Issue by trgardos** [tensorflow/tensorflow#46769]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/pose_estimation/overview.md
or
https://www.tensorflow.org/lite/models/pose_estimation/overview

## Description of issue (what needs changing):
In Further Reading the reference is pointing to the wrong PoseNet paper. It points to
https://www.cv-foundation.org/openaccess/content_iccv_2015/papers/Kendall_PoseNet_A_Convolutional_ICCV_2015_paper.pdf
which is also called PoseNet but it is about camera relocalization, not body pose detection.

### Correct links

According to this blog post
https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5
I think the correct papers are here:
https://arxiv.org/abs/1701.01779
and
https://arxiv.org/abs/1803.08225

**Comment by teijeong** [comment]
Thanks for the report! Will be fixed shortly with https://arxiv.org/abs/1803.08225
