### ISSUE TITLE
Using MaxPooling1D with 4D and higher Tensors

### ISSUE THREAD

**Issue by dmitra79** [tensorflow/tensorflow#46772]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): Not sure?

**Describe the feature and the current behavior/state.**

Currently, MaxPooling1D layer only takes 3D tensor as input, and data_format argument specifies if features are first or last.
If tensor is 4D, an error gets thrown. However, the same API can be used to handle higher-dimensional data, e. 4D tensors, and there are use-cases for that. For example, when trying to implement multiple instance learning, data is organized in bags of instances, and for time series would become 4D.

```
n = 6
sample_size = 300
code_size = 50
learning_rate = 0.001
n_bags= None

# autoencoder: n_bags X n_instances_in_bag X n_samples (timesteps) X n_measurements
input_window = Input(shape=(n_bags,sample_size, n)) 
x = Conv1D(filters=40, kernel_size=21, activation='relu', padding='valid')(input_window)
x = MaxPooling1D(pool_size=2)(x)
```

Currently, this throws an error:
```
ValueError: Input 0 of layer max_pooling1d_4 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, None, 280, 40]
```

but there is no reason why this can't work. Note that Conv1D layer works just fine with this.

**Will this change the current api? How?**
I believe the API can remain the same

**Comment by around-star** [comment]
@dmitra79 @jvishnuvardhan PoolingND layers only take inputs of (N+2) dimensions. I would like to add the feature of accepting inputs of >=N dimensions.

**Comment by dmitra79** [comment]
It was [suggested](https://stackoverflow.com/questions/65945784/using-maxpool1d-on-inputs-with-4-dimensions-4d-tensor) to me that one can use a 2D filter with length 1 in some dimensions, ex: MaxPooling2D with (1,2) would work here. So there is a workaround. But it'd be nice to have the API support this

**Comment by rchao** [comment]
@dmitra79 thanks for reporting this suggestion. Would you be interested in making a contribution toward this?

**Comment by fchollet** [comment]
It sounds like you want to do 1D pooling over one dimension of a multi-dimensional tensor. I'd recommend implementing your own layer to do that. It would simply implement a `call` method that would use `tf.nn.pool`. Ref: https://www.tensorflow.org/api_docs/python/tf/nn/pool
