### ISSUE TITLE
Deprecation warnings Model.state_updates when calling keras model `predict` after `get_weights`, in static execution

### ISSUE THREAD

**Issue by de-code** [tensorflow/tensorflow#46777]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): No
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.12
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

Similar to #44178 I am seeing the following deprecation warning:

```
/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
```

That is happening only in static execution (not eager mode). And it seems only when calling `get_weights` before calling `predict`.

**Describe the expected behavior**

No warning.

**Standalone code to reproduce the issue**

```python
import numpy as np
import tensorflow as tf
from tensorflow.python.framework.ops import disable_eager_execution


def build_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(1, input_shape=(1,)),
        tf.keras.layers.Dense(10),
        tf.keras.layers.Dense(1)
    ])
    model.compile(optimizer='sgd', loss='mse')
    return model


def do_test():
    x = np.asarray([[0], [1]])
    y = x
    model = build_model()
    model.fit(x=x, y=y, epochs=1000, verbose=0)
    model.get_weights()
    result = model.predict(x=x)
    print('result:', result)
    print('result close?:', np.allclose(result, y, atol=0.01))


def test_with_graph_static_execution():
    with tf.Graph().as_default():  # pylint: disable=not-context-manager
        do_test()


def test_without_explicit_graph_using_static_execution():
    disable_eager_execution()
    do_test()


def test_without_graph_eager_execution():
    do_test()


test_with_graph_static_execution()
# test_without_explicit_graph_using_static_execution()
# test_without_graph_eager_execution()
```

In the above example code, you may comment / uncomment to call the desired test function. Out of the three, `test_without_graph_eager_execution` is not showing the warning, `test_with_graph_static_execution` and `test_without_explicit_graph_using_static_execution` are.

The specific model doesn't seem to be relevant, neither whether it was first fit.

Removing the call to `get_weights` will also avoid the warning (but the warning only appears when then calling `predict`).
(Of course, in the real use case the weights will be used)

The main motivation for using the static execution is to improve performance.

**Other info / logs**

<details>
<summary>traceback</summary>

```
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 991, in predict
    use_multiprocessing=use_multiprocessing)
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 712, in predict
    callbacks=callbacks)
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 185, in model_iteration
    f = _make_execution_function(model, mode)
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays_v1.py", line 555, in _make_execution_function
    return model._make_execution_function(mode)
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2084, in _make_execution_function
    self._make_predict_function()
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 2072, in _make_predict_function
    updates=self.state_updates,
  File "/path/to/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2325, in state_updates
    warnings.warn('`Model.state_updates` will be removed in a future version. '
```
</details>

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7064020ac8077570aad3b03b7b6c8805/46777.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@de-code,
In Tensorflow 2.x, if you want to run your Code in Graph Mode, it is recommended to use **`tf.function`** instead of **`Disabling the Eager Execution`**.

By adding **`tf.function`**, the function, `test_without_explicit_graph_using_static_execution` runs without any warning. 

The function, `test_with_graph_static_execution` results in warning because **`tf.Graph().as_default():`** is deprecated and is not thread safe as per the [documentation](https://www.tensorflow.org/api_docs/python/tf/Graph#using_graphs_directly_deprecated).

Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/b26381c61f757979da269af6559f9548/46777.ipynb#scrollTo=UMdiyrzT5T9c) of the working code.

**Comment by de-code** [comment]
> @de-code,
> In Tensorflow 2.x, if you want to run your Code in Graph Mode, it is recommended to use **`tf.function`** instead of **`Disabling the Eager Execution`**.

Thank you, I didn't realise that disabling eager execution was deprecated as well. Can you please confirm that using `disable_eager_execution` is indeed deprecated?

> By adding **`tf.function`**, the function, `test_without_explicit_graph_using_static_execution` runs without any warning.
> 
> Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/b26381c61f757979da269af6559f9548/46777.ipynb#scrollTo=UMdiyrzT5T9c) of the working code.

Thank you for updating gist.
Is the `tf.function(do_test())` correct? Isn't that running `do_test()` first and then passing the return value (`None`) to `tf.function`?

I've updated the gist to add print output relating to the eager mode and keep original version as `test_without_explicit_graph_using_disable_eager_execution`:

```python
def test_without_explicit_graph_using_disable_eager_execution():
    disable_eager_execution()
    do_test()
```

and your updated version as `test_without_explicit_graph_using_tf_function`:

```python
def test_without_explicit_graph_using_tf_function():
    tf.function(do_test())
```

I've also tried to update it to something like `tf.function(do_test)()` but that didn't like calling `model.fit` as part of that (neither did it like wrapping `model.predict`.

Is there actually a way to make the Keras model to use the eager mode less?

The output shows that `model.run_eagerly` is actually `False` in all cases (unlike `tf.executing_eagerly()`). Yet I am experiencing significant performance difference (~10x), depending on whether I call `disable_eager_execution` (or use the deprecated `tf.Graph().as_default()`).

If understand you correctly, then disabling eager mode globally in any way is deprecated.
In that case I guess we could close this issue and I could create another performance related issue (if that isn't already covered).
It would probably be good to mark `disable_eager_execution` as deprecated.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/affe462d0c1be1ab07d12a601202682c/untitled51.ipynb#scrollTo=MqcdqCUM9qEk)..Thanks !

**Comment by chunduriv** [comment]
Since the disable_eager_execution is deprecated in Tf 2.x. This function is not necessary if you are using TF2. Eager execution is enabled by default. If you want to use Graph mode please consider tf.function. If you are facing performance issue, with all the required information raise new issue. Thanks!

**Comment by de-code** [comment]
Thank you for your response.

> Since the disable_eager_execution is deprecated in Tf 2.x. This function is not necessary if you are using TF2. Eager execution is enabled by default.

Isn't that why `disable_eager_execution` is necessary with TF2. Because the default is enabled by default, that is an approach to disable it. (`enable_eager_execution` wouldn't be necessary in TF2)

Can you confirm that `disable_eager_execution` is indeed deprecated? (I asked that in my previous [comment](https://github.com/tensorflow/tensorflow/issues/46777#issuecomment-774341175) as well).

> If you want to use Graph mode please consider tf.function.

`tf.function` wasn't mentioned before. It is unclear how to use it in combination with Keras.
The examples above don't work.

> If you are facing performance issue, with all the required information raise new issue.

Fair enough. I am not sure what the would be the ideal tickets is, there seem to be a few:

- What is the supported method of training and running Keras models in graph mode in TF2?
- Performance issue with training Keras model in eager mode, compared to graph mode, in TF2

The latter will be more difficult to measure and validate.

**Comment by chunduriv** [comment]
@de-code,

tf.compat.v1.disable_eager_execution, This API was designed for TensorFlow v1. For more information refer [here](https://www.tensorflow.org/api_docs/python/tf/compat/v1/disable_eager_execution).

Since you are using builtin Keras functions, classes and layers so there is no need to use a @tf.function decorator, they are already treated as a graph by the TF compiler. @tf.function is basically used to convert a normal function into a TensorFlow Graph as mentioned [here](https://www.tensorflow.org/api_docs/python/tf/function). 

When you are using custom model 
```
@tf.function
def custom_model(model, ...):
  ...
  outputs = model(...)
  ...
```

```
# Create the model
model = define model layers(...)
# It's a good idea to initialize it too
model(<dummy input>)  # or model.build(...)

custom_model(model, ...)
```

**Comment by de-code** [comment]
Okay, thank you.

Based on your response I understand that disabling eager mode globally (except for using `tf.function`) is indeed deprecated,
and that Keras models should already be using the graph mode.

In that case the Keras model shouldn't have become faster when disabling eager mode.

I will test it again and raise a performance issue instead, if that is still an issue.
