### ISSUE TITLE
Inconsistency of computations with different batch size

### ISSUE THREAD

**Issue by artem-s-shevchenko** [tensorflow/tensorflow#46770]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla K80 11441MiB

**Describe the current behavior**

Computations with batch size 2 or two consecutive computations with batch size 1 lead to different results if the number of units is bigger than 64 (for tf.keras.layers.Dense) or the last dimension is equal to 1 (tf.matmul).

**Describe the expected behavior**
Results supposed to be same. 

**Standalone code to reproduce the issue**
```python
linear = tf.keras.layers.Dense(units=65)
data = 50*tf.ones(shape=[2, 93, 3286])
r = linear(data)
r_0 = linear(data[:1])
r_1 = linear(data[1:])
print(tf.reduce_max(tf.abs(r[:1]-r_0)/tf.abs(r[:1])), tf.reduce_max(tf.abs(r[:1]-r_0)))
print(tf.reduce_max(tf.abs(r[1:]-r_1)/tf.abs(r[1:])), tf.reduce_max(tf.abs(r[1:]-r_1)))
```

```python
data_1 = 1.22222*tf.random.normal(shape=(2, 20, 10, 1))
data_2 = 0.37*tf.random.normal(shape=(2, 20, 10, 52))
r = tf.matmul(data_1, data_2, transpose_a=True)
r_0 = tf.matmul(data_1[:1], data_2[:1], transpose_a=True)
r_1 = tf.matmul(data_1[1:], data_2[1:], transpose_a=True)
print(tf.reduce_max(tf.abs(r[:1]-r_0)/tf.abs(r[:1])), tf.reduce_max(tf.abs(r[:1]-r_0)))
print(tf.reduce_max(tf.abs(r[1:]-r_1)/tf.abs(r[1:])), tf.reduce_max(tf.abs(r[1:]-r_1)))
```

**Comment by ravikyram** [comment]
@artem-s-shevchenko 

I have tried in colab with TF version 2.2, nightly version. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/65f8ac5564cc2c33470eaf77772cb47d/untitled644.ipynb).You are also seeing the same behavior?
Thanks!

**Comment by artem-s-shevchenko** [comment]
@ravikyram 
Not exactly same.

For tf.keras.layers.Dense:
tf.Tensor(1.754481e-05, shape=(), dtype=float32) tf.Tensor(0.00024414062, shape=(), dtype=float32)
tf.Tensor(1.754481e-05, shape=(), dtype=float32) tf.Tensor(0.00024414062, shape=(), dtype=float32)

For tf.matmul:
tf.Tensor(0.00043521042, shape=(), dtype=float32) tf.Tensor(4.7683716e-07, shape=(), dtype=float32)
tf.Tensor(0.00037936267, shape=(), dtype=float32) tf.Tensor(4.7683716e-07, shape=(), dtype=float32)

**Comment by WindQAQ** [comment]
Hi @artem-s-shevchenko, it's not related to Dense layer or matmul, but the reduction in TensorFlow backend is non-deterministic. If you change to test with `np.testing.assert_allclose(r_0.numpy(), r_1.numpy())`, you can find they are the same. There is an RFC in community https://github.com/tensorflow/community/pull/346.

https://colab.research.google.com/drive/1GlMBO3Ldek1QybLw01B-izVslBBZAVOy?usp=sharing

**Comment by artem-s-shevchenko** [comment]
Hi, @WindQAQ ,
If I try ```np.testing.assert_allclose(r[:1].numpy(), r_0.numpy()) ``` or ```np.testing.assert_allclose(r[1:].numpy(), r_1.numpy())```, problem is still present.

**Comment by ymodak** [comment]
@artem-s-shevchenko Can you please share a gist showing AssertionError? I tried WindQAQ's attached gist and find that AssertionError is not raised.

**Comment by artem-s-shevchenko** [comment]
https://gist.github.com/artem-s-shevchenko/17be8e0b03c3f76e2eefc7e1f19a3d80
https://gist.github.com/artem-s-shevchenko/daa582568968e0cc6423500e7f7b6b34

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b3cf81415e542275bf098fcb4689df30/untitled52.ipynb)..Thanks !

**Comment by cantonios** [comment]
We make no guarantees of consistency if order of operations change, or if data layout changes.  Different code paths may be exercised, and they may use different intrinsics (e.g. in one case may use fused multiply-adds, but not in another).  The results *should* be consistent within some appropriate tolerance.

**Comment by chunduriv** [comment]
@artem-s-shevchenko, 

Can you take a look at [this](https://github.com/tensorflow/tensorflow/issues/46770#issuecomment-921153932) comment and let us know if it helps?
