### ISSUE TITLE
Add Torch (Flash light) "Android"

### ISSUE THREAD

**Issue by MeysamSMH7** [tensorflow/tensorflow#46787]
Hi,
I wanna add Torch to this app. sometime light is not good  in area so I have to use flash light in app
But I can't use this code in app 
mCameraManager.setTorchMode(mCameraId, true);
The error is: camera "0" is in use
Or flash light just blink for a second
How can I use this feature in app?

**Comment by Saduf2019** [comment]
@MeysamSMH7
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps 
followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by MeysamSMH7** [comment]
@Saduf2019
hi, that is not an error, its just a feature. i`ve found it, its just add these lines to CameraConnectionFragment.java

`                              if (new sharedPref(getContext()).getTorch())
                                    previewRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_TORCH);
                                else
                                    previewRequestBuilder.set(CaptureRequest.FLASH_MODE, CaptureRequest.FLASH_MODE_OFF);
                                previewRequestBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON);
`

**Comment by AleksandarTokarev** [comment]
@MeysamSMH7 where to add this? I am not seeing any class sharedPref in the project. For me it turns on for a second and it stops after that

**Comment by AleksandarTokarev** [comment]
Ok seems removing the auto flash in configuration allows the flash to be controlled.
```
// Flash is automatically enabled when necessary.
                previewRequestBuilder.set(
                    CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH);
```
But this cannot be achieved with `CameraManager manager;` and `manager.setTorchMode(cameraId, true);`, but has to be controlled through the FLASH MODES.

Basically in CameraActivity - create a variable `  protected CameraConnectionFragment camera2Fragment;` and assign the result of 
```
camera2Fragment =
          CameraConnectionFragment.newInstance(
``` to that new variable;

After that in camera connection fragment i have added
```
public void turnFlash(boolean flag) {
    previewRequestBuilder.set(CaptureRequest.FLASH_MODE, flag ? CaptureRequest.FLASH_MODE_TORCH : CaptureRequest.FLASH_MODE_OFF);
    previewRequest = previewRequestBuilder.build();
    try {
      captureSession.setRepeatingRequest(
              previewRequest, captureCallback, backgroundHandler);
    } catch (CameraAccessException e) {
      e.printStackTrace();
    }
  }
```
which turns the torch mode on or off based on the flag.
This method is called from `DetectorActivity` - from the onclick button
