### ISSUE TITLE
Enabling GPU support for Tensorflow in virtualenv

### ISSUE THREAD

**Issue by Godofnothing** [tensorflow/tensorflow#46784]
I am attempting to setup `Tensorflow` with GPU support on virtualenv. 
I have a native version with system interpreter - `Tensorflow 2.4.1`, which works fine and does see the `GPU`. 
And  in virtualenv I use `Tensorflow 2.0.0` with Python 3.7.9. 

When running in the interpreter on the system with `Tensorflow 2.4.1` I receive following greeting message : 

`I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0`

And the command `tf.config.experimental.list_physical_devices("GPU")` shows my GPU. 
However perforing the same actions in virtualenv I do not receive this greeting message, and the output of the command above is an empty list. 

**System information**
- OS Platform and Distribution : (Linux Ubuntu 20.04):
- TensorFlow version: 2.0.0
- Python version: 3.7.9
- Installed using pip in virtualenv
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2080Ti

I've installed the `Tensorflow 2.0.0` via pip inside virtualenv. And the `CUDA` setup was performed as described here 
https://www.tensorflow.org/install/gpu?hl=ur with some changes for `Ubuntu 20.04`.

My question is : what needs to be done in order to enable GPU support inside virtualenv?

**Comment by Saduf2019** [comment]
@Godofnothing 
Can you please upgrade your tensorflow version on virtual env same as on your system where gpu is detected also verify [here](https://www.tensorflow.org/install/source#gpu).

**Comment by Godofnothing** [comment]
The problem is that the project I am working on and for which I have created this `virtualenv` requires `TF 2.0`, its scripts use some core functionality of `TF` like from `tensorflow.python`, `tensorflow.framework`, which were removed in later versions.

**Comment by Saduf2019** [comment]
@Godofnothing
The cuda version you are using is 11.0 which is compatible with tf 2.4 and onward, please refer to the gpu compatibility link shared above, where tf 2.0 uses cuda 10 and cudnn 7.4

**Comment by Godofnothing** [comment]
Ok, thanks a lot for help!

**Comment by Saduf2019** [comment]
@Godofnothing
Could you please move this issue to closed status.
