### ISSUE TITLE
Micro: port op FAKE_QUANT from Lite

### ISSUE THREAD

**Issue by rsun-bdti** [tensorflow/tensorflow#46783]
@tensorflow/micro

**System information**
Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): source
Tensorflow version (commit SHA if source): master
Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Sparkfun Edge

**Describe the problem**
I am about to port The TF Lite kernel op FAKE_QUANT to TFLite Micro.

**Please provide the exact sequence of commands/steps when you ran into the problem**
PR 1: refactor flatbuffer_conversions parsing function
PR 2: refactor reference implementation from lite/kernels/internal/reference/reference_ops.h into its own header with only the changes to pass internal CI build checks.
PR 3: copy the kernel from lite to micro any make the micro op and its testing code to work.

**Comment by njeffrie** [comment]
As far as I know, this op is only used to calibrate models for quantization within TFLite. Since the TFLM runtime expects quantized models, I cannot think of a use case for this operator within TFLM.

Let me know if I'm missing something here.

**Comment by rsun-bdti** [comment]
Closing this issue per Nat's comment.

**Comment by SevHub** [comment]
Hallo, I used quantisation-aware training according to [this](https://www.tensorflow.org/model_optimization/guide/quantization/training_example) official example. After converting the model to a tflite model it still has this "fake_quant" layers. Is there a way to get rid of this layers in the tflite model or convert them into somthing else like "Quantize"? Or is this quantization-aware training just not possible with Tflite Micro?
