### ISSUE TITLE
ValueError: Input 0 of layer encoder1_ is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 64, 4, 850)

### ISSUE THREAD

**Issue by poojitharamachandra** [tensorflow/tensorflow#46794]
inputs_p = Input(shape=(5,4,850)) #4 time steps, 5 features , num_sds
          decoder_inputs = Input(shape=(5,4,850)) #1time step, 5 features , num_sds
          neighbhourhood = Input(shape=(4,850,850)) #1time step, 5 features , num_sds

          encoder_inputs = MyModel_conv_accross_time()(inputs_p , neighbhourhood)

          enc = LSTM(cfg['units'],activation='tanh',return_state=True,return_sequences=True,name='encoder1_') 
          decoder_outputs, state_h, state_c  = enc(encoder_inputs)

ValueError: Input 0 of layer encoder1_ is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 64, 4, 850)

MyModel_conv_accross_time  returns results with shape (batch,64,4,850)

**Comment by mch463** [comment]
This is very good

**Comment by poojitharamachandra** [comment]
I believe this is because lstm expects 3d input , not 4d . let me check and get back!

**Comment by poojitharamachandra** [comment]
reshaping the output from MyModel_conv_accross_time to (batch*850,64,4) solved the issue
