### ISSUE TITLE
Trying to train a custom object detection model

### ISSUE THREAD

**Issue by aayushnair1126** [tensorflow/tensorflow#46797]
Hey guys!
I have been trying to train a model of Object detection using the the Tensorflow models that you guys provide and while i have been trying to do this for the last 3 weeks there are some issues which are coming again and again like there is nor attribute input to convolution box predictor as those issues are resolved now there is a new issue of checkpoint which i am not able to solve or find a way to solve it i would request to update me on this one 
![Problem1](https://user-images.githubusercontent.com/51516774/106319221-1e211380-6297-11eb-8395-bf5d3a09478a.jpg)

**Comment by Saduf2019** [comment]
@aayushnair1126 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced].
Could you please paste the error log, not the image it makes it easier to search the issue.
