### ISSUE TITLE
tf-nightly ResNet50V2 building error

### ISSUE THREAD

**Issue by whiteRa2bit** [tensorflow/tensorflow#46790]
**System information**
Colab

**Describe the current behavior**
Tf-nightly notebook:
https://colab.research.google.com/drive/1-A_C9bQL0cRdJ5F2ETlJl9GaZmukYVaq?usp=sharing

**Describe the expected behavior**
Tf 2.4.1 notebook:
https://colab.research.google.com/drive/1lRlGfQljmqAwOsP_npItl_aElCI9KPMD?usp=sharing

**Comment by whiteRa2bit** [comment]
@ravikyram could you take a look, please?

**Comment by WindQAQ** [comment]
The break is introduced in https://github.com/tensorflow/tensorflow/commit/9700d00258607d5a81980a6fe602280dd0f4d2e1. What you do is to override attributes related to output shape inference (somehow risky). So it breaks the static shape inference when you try to build again. Any reason that you have to do that? Note that overriding some of those attributes are meaningless (like initializers). When you call `ResNet50V2`, the model has already been built, so initializers overriding does not have any effect.

**Comment by whiteRa2bit** [comment]
Thank you very much, I was using a pre-trained model, therefore I wanted to leave it as is
