### ISSUE TITLE
Generated wheel files are named incorrectly (python wheel experts, please help!)

### ISSUE THREAD

**Issue by craigcitro** [tensorflow/tensorflow#468]
**Note:** If you know lots about python wheels, and can answer some of the questions here, please jump in!

Python wheel files encode metadata about supported architectures into their names, cf [the wheel PEP](https://www.python.org/dev/peps/pep-0427/) and [the suffix PEP](https://www.python.org/dev/peps/pep-0425/).

Currently, when we generate wheel files, we end up with either too-broad names (eg all Mac wheels are `py2-none-any`, which is wrong) or too-specific (some linux wheels are tagged `cp34-cp34m-linux-x86_64`, but we think the abi component should be `none`). This leads to issues like #467.

A part of the issue here is that we're not sure what some of these tags mean -- for instance, the only explanation I've found of the `m` suffix is in [an issue on the wheel bug tracker](https://bitbucket.org/pypa/wheel/issues/61/abi-version-is-not-found) and even that doesn't clear things up.

There are really three parts to fixing this:
 * we should know what the "right" filename is for these wheel files.
 * we should fix our build process to generate the right output on all architectures.
 * we should consider serving our wheel files via a custom PyPA.

More details on the last one: we're making our lives harder by asking people to point to the "right" wheel file. `pip` knows how to take a package name (eg `tensorflow`) and a list of wheel files, and then install the right one. We can and should serve our own PyPA, so that installation instructions on **all** platforms we support would be something like

    pip install --extra_index_url=https://tensorflow.org/pypa tensorflow

/cc @vrv @martinwicke @keveman on the TF side.

**Comment by furaoing** [comment]
Solution for all who wants to install from wheels on python3.5, rename "tensorflow-0.6.0-cp34-none-linux_x86_64.whl" to "tensorflow-0.6.0-cp35-none-linux_x86_64.whl".

**Comment by vrv** [comment]
Closing since we're not getting any traction from the community on this.  Sigh.
