### ISSUE TITLE
ImageDataGenerator - Caching not effective when using tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by BlueskyFR** [tensorflow/tensorflow#46807]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Manjaro Linux 20.2.1
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- CUDA/cuDNN version: 11.0

**Describe the current behavior**

When creating a dataset generator using ImageDataGenerator, as the documentation specifies it:
```
The data will be looped over (in batches).
```
The dataset generator is then used in `tf.data.Dataset.from_generator`, on which is then called `.cache()`: we have a problem here, since the `cache()` function caches the data, as the documentation specifies it:
```
The first time the dataset is iterated over, its elements will be cached either in the specified file or in memory.
Subsequent iterations will use the cached data.
```
The problem is that the dataset never ends since this is the way ImageDataGenerator works.

**Describe the expected behavior**

There should be a callback or something telling `tf.data.Dataset` that the dataset is OVER when getting the last batch each time, so that data can be cached properly.

**Comment by amahendrakar** [comment]
@BlueskyFR,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
