### ISSUE TITLE
edgetpu_compiler: "Model not Quantized" despite being quantized

### ISSUE THREAD

**Issue by pandalion98** [tensorflow/tensorflow#46806]
### 1. System information

- OS Platform and Distribution: Google Colab; Ubuntu 20.04.1
- TensorFlow installation (pip package or built from source): `pip`
- TensorFlow library (version, if pip package or github SHA, if built from source): Tested on `1.15.5`, `2.3.0`, and `2.4.1`

### 2. Code

I have followed these guides to the letter:

- Creating a YOLOv3-tiny model, Converting it to Keras, then finally exporting as a tflite
    - https://github.com/goruck/edge-tpu-train
 - Training YOLO models
    - https://github.com/AlexeyAB/darknet#how-to-train-tiny-yolo-to-detect-your-custom-objects

It is as dead-stock a model as possible. I am trying to eliminate causes. I have also encountered the error while trying to convert EfficientDet-d0, YOLOv3, and YOLOv4-tiny.

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/drive/1p5TpbSZZgDVTTlrJPxfw-waAGH-HKFSy?usp=sharing): Download [this attached model](https://github.com/tensorflow/tensorflow/files/5898304/heehoo.zip). Simply drag and drop to `/content`, then run the notebook.

### 3. Failure after conversion
```
Edge TPU Compiler version 15.0.340273435
Invalid model: heehoo.tflite
Model not quantized
```

### 5. (optional) Any other info / logs
I encounter no errors during conversion from Keras to Tflite. I even verified the models using Netron, and there seems to be nothing wrong. All the layers seem to use `uint8`.

This is the worst warning I have seen, along with CUDA-related warnings:
`2021-01-31 00:15:49.647787: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.`

**Comment by abattery** [comment]
@jingpu @daverim could you take a look?

**Comment by jingpu** [comment]
@pandalion98 The error is because tensor "functional_1/up_sampling2d/strided_slice2" has INT32 type. BTW, coral edge tpu doesn't support shape computation like "Shape" operator. I would suggest to try to avoid them.

**Comment by mohantym** [comment]
Hi @pandalion98 !
I am not getting any warning in [Colab](https://colab.sandbox.google.com/gist/mohantym/00d75ef611a47e9d9e35f565efae31cd/tflite-compile-error.ipynb#scrollTo=HeboX6cQ2D3q) with above gist. Regarding quantization, I can see the model is quantized through interpeter. 

But I am getting errors on usage of dynamic sized tensors which can be fixed by using static shapes in model training.
[Reference](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization).

Thank you!
