### ISSUE TITLE
tf.cond within vectorized_map results in unknown output shape

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#46818]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab version
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Colab version
- TensorFlow version (use command below): v2.4.1-0-g85c8b2a817f 2.4.1
- Python version: Colab version
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
When using tf.cond from within tf.vectorized_map, the output shape is lost and the result has a None batch shape. This results in memory exploding at backpropagation time.

**Describe the expected behavior**
The output shape should be retained when the shapes of the two possible cond outputs are the same. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1ydXdSe0_jJqtJLYGXgkCxywjC9gFANwv?usp=sharing

**Comment by ravikyram** [comment]
@AdrienCorenflos 

If you comment `@tf.function` then the code works as expected. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d0c7e641c6530bbb3ffa9050d9cec977/untitled647.ipynb).Is there any particular reason that you want to use @tf.function.
Thanks!

**Comment by AdrienCorenflos** [comment]
Hi,
I probably should have mentioned that this only happened within a tf.function indeed.

This code is actually a (very) simplified version of my original code (akin to this [one](https://github.com/EEA-sensors/sequential-parallelization-examples/blob/main/python/temporal-parallelization-bayes-smoothers/parallel_kalman_tf.ipynb)), it needs to be compiled for speed reasons.

Adrien

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/cfb521a18bea983985fc8de91eca1fdc/untitled50.ipynb)..Thanks !

**Comment by sachinprasadhs** [comment]
To perform the `tf.cond` operation inside graph mode you need to follow excecution of OPS in a Tensorflow graph flow. Refer [this](https://stackoverflow.com/questions/37063952/) answer for more details.
