### ISSUE TITLE
StyleGAN2 is not converging in 4x RTX 3090

### ISSUE THREAD

**Issue by Thunder003** [tensorflow/tensorflow#46810]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): 2.4rc02
- TensorFlow version (use command below): 2.x
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1
- GPU model and memory: 4x RTX 3090(24 GB)

**Describe the current behavior**
I have converted StyleGAN 2 official code(Written in Tensorflow 1.x) to TensorFlow 2.x. It is converging properly till some point, but then it started to decrease the quality. 

First I observed a mode collapsing then Eventually, the resulting images were a completely distorted type, kind of noise only. 
I'm using data having many categories.

Anyone knows why it is happing and the solution. Thanks in advance.

**Comment by amahendrakar** [comment]
@Thunder003,
Instead of **TensorFlow 2.4rc02**, could you please install **TensorFlow v2.4.1** using the below command and check if it works.

`pip install tensorflow==2.4.1`

Thanks!

**Comment by amahendrakar** [comment]
Also in order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. Thanks!
