### ISSUE TITLE
RaggedTensor not supported as model input in generator and sequence

### ISSUE THREAD

**Issue by pedro-r-marques** [tensorflow/tensorflow#46825]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- tf-nightly 2.5.0 (2021020101)
- colab

**Describe the current behavior**
generators and sequences (objects that implement the keras.utils.Sequence interface) that return a RaggedTensor as model input trigger an exception

**Describe the expected behavior**
generators and sequences should support any CompositeTensor

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1Qxov6zoWEnVcGwAH67cWiqaIjGcUTwbk?usp=sharing

This notebook creates a model that uses ragged tensors and verifies that when a tensor is passed to ```model.fit``` the behaviour is as expected. It then attempts to return the save value from a generator. The generator works if the tensor is converted from ragged to dense (although that changes the computed value). Passing a ragged tensor directly to the tf.data.Dataset API also seems to work. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
InvalidArgumentError:  TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int32, but the yielded element was <tf.RaggedTensor [[[1, 2], [3, 4]], [[5, 6]]]>.
TypeError: int() argument must be a string, a bytes-like object or a number, not 'RaggedTensor'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 912, in generator_py_func
    dtype=dtype.as_numpy_dtype))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in _convert
    result = np.asarray(value, dtype=dtype, order="C")

  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)

ValueError: setting an array element with a sequence.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 625, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 921, in generator_py_func
    sys.exc_info()[2])

  File "/usr/local/lib/python3.6/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 912, in generator_py_func
    dtype=dtype.as_numpy_dtype))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in _convert
    result = np.asarray(value, dtype=dtype, order="C")

  File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)

TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was int32, but the yielded element was <tf.RaggedTensor [[[1, 2], [3, 4]], [[5, 6]]]>.


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_1924]

Function call stack:
train_function
```

**Comment by Saduf2019** [comment]
@pedro-r-marques 
please refer these links and let us know if it helps : [link](https://github.com/tensorflow/tensorflow/issues/27598), [link1](https://github.com/tensorflow/tensorflow/issues/35342), [link2](https://stackoverflow.com/questions/63247003/tensorflow-from-generator-giving-error-generator-yielded-an-element-that-co)

**Comment by pedro-r-marques** [comment]
@Saduf2019 From your links it appears that the intent is that fit must be called with a Dataset which is created with ```from_generator``` such that the ```output_signature``` parameter is set; if that is the case, at least the error message should be improved imho. And most likely the documentation for ```model.fit``` should specify that using a sequence or a generator is only supported if the returned values are dense tensors.

**Comment by Saduf2019** [comment]
@pedro-r-marques 
Could you please try and let us know if the issue persist.

**Comment by axiom5** [comment]
This was a bug before tensorflow v2.4.0. Release notes say tf.data supports Ragged tensors in generators

https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0
