### ISSUE TITLE
Running tensorboard with vz-projector demo in development mode

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#4682]
Is it possible to actually test the `vz-projector` element in the tensorboard components ? 
I know it's a bleeding edge feature but I'd like to give it a try to see how it works but I get the following error while running `gulp`

~~~
TypeScript error: components/vz-projector/data.ts(170,24): Error TS2345: Argument of type '{ metadata: { [key: string]: number | string; }; index: number; vector: number[]; projectedPoint:...' is not assignable to parameter of type 'DataPoint[]'.
  Type '{ metadata: { [key: string]: number | string; }; index: number; vector: number[]; projectedPoint:...' is not assignable to type 'DataPoint'.
    Types of property 'projections' are incompatible.
      Type '{}' is not assignable to type '{ [key: string]: number; }'.
        Index signature is missing in type '{}'.
TypeScript error: components/vz-projector/vz-projector-bookmark-panel.ts(74,5): Error TS2346: Supplied parameters do not match any signature of call target.
TypeScript error: components/vz-projector/vz-projector-bookmark-panel.ts(88,7): Error TS2339: Property 'download' does not exist on type 'HTMLAnchorElement'.
~~~

**Comment by concretevitamin** [comment]
@dsmilkov: Daniel, could you take a look?  Thanks.

**Comment by jrabary** [comment]
I manage to make the tsne demo working with the following correction in the `data.ts` file

~~~
getSubset(subset?: number[]): DataSet {
    let pointsSubset = subset ? subset.map(i => this.points[i]) : this.points;
    let points = pointsSubset.map(dp => {
      return {
        metadata: dp.metadata,
        index: dp.index,
        vector: dp.vector.slice(),
        projectedPoint: [0, 0, 0] as [number, number, number],
        projections: {} as {[key: string]: number;}
      };
    });
~~~

The next problem is that I get `numeric is not defined` when running PCA.

**Comment by dsmilkov** [comment]
Hi,

I appreciate your interest, however the `vz-projector` is not yet released, so it is not possible to test it yet. We plan to release it soon (no promises as to exactly when). When we release it, we will add a documentation in the "How to" section next to the other TensorBoard pages.

As for the broken compile, we are fixing it internally today - the update should show up in 1-2 days on GitHub.

**Comment by jrabary** [comment]
Hi @dsmilkov. I'm testing the latest verison of the embedding project which looks nice. I'm wondering how can I create a demo tensors in .bytes format ?
