### ISSUE TITLE
Running TensorFlow Profiler on CPU only machine but training on GPU machine?

### ISSUE THREAD

**Issue by jieheroli** [tensorflow/tensorflow#46823]
Can I trainng a model on GPU machine and generating the profile files, but use a CPU only machine to load the files and render the profile webpage correctly?

**Comment by amahendrakar** [comment]
@jieheroli,
I was able run [this guide](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras), i.e. train and generate the model on GPU, save the `logdir` file, load it back on CPU and run the profiler without any issues. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/980bc108d9178a48f3078f6d8fb8836c/tensorboard_profiling_keras.ipynb#scrollTo=75oykBMhFh4e). Thanks!
