### ISSUE TITLE
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr. when convert and quantize tf model

### ISSUE THREAD

**Issue by JiashuGuo** [tensorflow/tensorflow#46821]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: `import tensorflow.compat.v1 as tf tf.__version__  2.4.1`
-   **Python version**: Python 3.6.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
I am trying to covert a Feature Extraction model that used in deepSort tracking to a int8 quantized tflite model, I am following the post-training quantization but failed with an error.  Actually, no matter what content in representative_data_gen() function, the error is same as in Traceback below:
### Source code / logs
Here is the code that converting the frozen-graph to tflite:
    
        import tensorflow.compat.v1 as tf
        mnist = tf.keras.datasets.mnist
        (train_images, train_labels), (test_images, test_labels) = mnist.load_data()
        train_images = train_images.astype(np.float32) / 255.0

        def representative_data_gen():
            for input_value in tf.data.Dataset.from_tensor_slices(train_images).batch(1).take(100):
                yield [input_value]
        
        converter = tf.lite.TFLiteConverter.from_frozen_graph("mars-small128.pb",input_arrays=["Cast"],output_arrays=["features"],input_shapes={"Cast":[1, 128, 64, 3]})
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8
        converter.representative_dataset = representative_data_gen
        tflite_model = converter.convert()
        open("converted_model.tflite", "wb").write(tflite_model)
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 58, in __init__
    _calibration_wrapper.CalibrationWrapper(model_content))
TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 219, in <module>
    main()
  File "detect.py", line 109, in main
    encoder = generate_detections.create_box_encoder("mars-small128.pb", batch_size = 32)
  File "/home/dev/projects/coral/examples-camera/opencv/generate_detections.py", line 191, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/home/dev/projects/coral/examples-camera/opencv/generate_detections.py", line 150, in __init__
    tflite_model = converter.convert()
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1947, in convert
    return super(TFLiteConverter, self).convert()
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1313, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 449, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 60, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.

**Comment by ravikyram** [comment]
@JiashuGuo 

Please, share `mars-small128.pb` file to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by JiashuGuo** [comment]
[mars-small128.pb.tar.gz](https://github.com/tensorflow/tensorflow/files/5902770/mars-small128.pb.tar.gz)

**Comment by ravikyram** [comment]
@JiashuGuo 

I have tried in colab with TF version 2.4 and i am seeing the below error message.
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 52: invalid start byte`. 
Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/be04157fa70cbdc11f0af50f252b9f09/untitled646.ipynb).
Please, help me in reproducing the issue. It helps me in localizing the issue faster. Thanks!

**Comment by JiashuGuo** [comment]
> @JiashuGuo
> 
> I have tried in colab with TF version 2.4 and i am seeing the below error message.
> `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 52: invalid start byte`.
> Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/be04157fa70cbdc11f0af50f252b9f09/untitled646.ipynb).
> Please, help me in reproducing the issue. It helps me in localizing the issue faster. Thanks!

I uploaded mars-small128.pb file and ran the cells in order, and got this:
`ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.`
PLease see gist [here](https://colab.research.google.com/gist/ravikyram/be04157fa70cbdc11f0af50f252b9f09/untitled646.ipynb#scrollTo=TouSYPZyuxPP)

**Comment by JiashuGuo** [comment]
> @JiashuGuo
> 
> I have tried in colab with TF version 2.4 and i am seeing the below error message.
> `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 52: invalid start byte`.
> Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/be04157fa70cbdc11f0af50f252b9f09/untitled646.ipynb).
> Please, help me in reproducing the issue. It helps me in localizing the issue faster. Thanks!

Hi @ravikyram , I just ran cells again in order and error become this:
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr. See it [here](https://colab.research.google.com/gist/ravikyram/be04157fa70cbdc11f0af50f252b9f09/untitled646.ipynb#scrollTo=TouSYPZyuxPP)
Can you please check it again?

**Comment by JiashuGuo** [comment]
@jvishnuvardhan Have you get any ideas on this?

**Comment by jvishnuvardhan** [comment]
@JiashuGuo As far i know `TypeError: pybind11::init(): factory function returned nullptr` is related to GPU. Thanks!

I tried simple float model conversion, which works without any issues. We will check the root-cause of this error. Thanks!

**Comment by JiashuGuo** [comment]
Thanks for the updates! FYI I didn't use GPU to run this script.

**Comment by karimnosseir** [comment]
@jianlijianli The model converts to float the call for calibration fails to load the model. Can you please take a look

Thanks

**Comment by teijeong** [comment]
Building `LoggingInterpreter` failed with following error.

> ERROR: Only models with a single subgraph are supported, model had 3 subgraphs

A fix would be desired to correctly pass the error message to Python world.

**Comment by JiashuGuo** [comment]
@teijeong Will you going to make the converter to be able to convert the model that has more than one subgraph?

**Comment by jianlijianli** [comment]
Hi Jiashu, apologies for the delay. This is a known limitation and TFLite's quantization framework currently lacks proper support of multi-graph models (and your model has 3 subgraphs). We are looking into the issue and will update this thread soon. Thanks.

**Comment by dogacbasaran** [comment]
@jianlijianli, @JiashuGuo, I recently tried TFLite's quantization methods, I was able to follow Post-training float16 quantization and Post-training dynamic range quantization methods, convert my model and able to infer. However when I tried Post-training integer quantization, it gives:
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr. 

How do I confirm that my model has more than 1 subgraphs? Also is it normal that only Post-training integer quantization fails and gives this error even if my model has more than 1 subgraphs? Thanks.

**Comment by JiashuGuo** [comment]
> @jianlijianli, @JiashuGuo, I recently tried TFLite's quantization methods, I was able to follow Post-training float16 quantization and Post-training dynamic range quantization methods, convert my model and able to infer. However when I tried Post-training integer quantization, it gives:
> ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
> 
> How do I confirm that my model has more than 1 subgraphs? Also is it normal that only Post-training integer quantization fails and gives this error even if my model has more than 1 subgraphs? Thanks.

Hi @dogacbasaran, you can view the structure and subgraphs of your model in Netron https://netron.app/. I also got this error during integer quantization but seems there is no fix for now.

**Comment by teijeong** [comment]
Hi @dogacbasaran, besides visualizing graph, if you try again with tf-nightly the error message should be visible. Please le me know if you still get nullptr error.

**Comment by hoangmt** [comment]
I had the same issue. It dues to a version conflict between cuda and tensorRT, especially for my case, I use docker, it becomes more complicated to know the problem and to fix. I use latest tensorRT docker and update gpu driver of my pc to be the same as the one inside docker, the problem is solved.

**Comment by xhae** [comment]
Now multiple subgraph calibration is supported with https://github.com/tensorflow/tensorflow/commit/cd5a9ad1338b01f5fd8ce64ed86ad09bf26468ee

**Comment by JiashuGuo** [comment]
> Now multiple subgraph calibration is supported with [cd5a9ad](https://github.com/tensorflow/tensorflow/commit/cd5a9ad1338b01f5fd8ce64ed86ad09bf26468ee)

I have installed tf-nightly and now get the following error:
TF Select ops: TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3
Please see the [https://colab.research.google.com/drive/10CadH871KSf5Twklf0fI1rp3UGI0VhEB](gist) in Colab.

**Comment by xhae** [comment]
As the error message says, some ops are not supported by native. I think you can try using flex delegate for those ops.

**Comment by mohantym** [comment]
@JiashuGuo ! I was getting Runtime error in [2.8](https://colab.sandbox.google.com/gist/mohantym/e60689239e39ee210952b90eaa401b3c/untitled646.ipynb#scrollTo=TouSYPZyuxPP). Thanks!

**Comment by pjpratik** [comment]
Hi @JiashuGuo I was checking if this is still an issue.

On 2.11 and TF Nightly, the error received is `RuntimeError: tensorflow/lite/kernels/reshape.cc:92 num_input_elements != num_output_elements (784 != 24576)Node number 10 (RESHAPE) failed to prepare.Node number 0 (WHILE) failed to invoke.`

which is more related to representative dataset provided. I was able to successfully convert the model using post training integer quantization by providing the representative dataset that match with the cast shape.

Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/d478801578c95f738cf3673cf20410cb/46821.ipynb).

Thanks.

**Comment by Fabiran** [comment]
> Hi @JiashuGuo I was checking if this is still an issue.
> 
> On 2.11 and TF Nightly, the error received is `RuntimeError: tensorflow/lite/kernels/reshape.cc:92 num_input_elements != num_output_elements (784 != 24576)Node number 10 (RESHAPE) failed to prepare.Node number 0 (WHILE) failed to invoke.`
> 
> which is more related to representative dataset provided. I was able to successfully convert the model using post training integer quantization by providing the representative dataset that match with the cast shape.
> 
> Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/d478801578c95f738cf3673cf20410cb/46821.ipynb).
> 
> Thanks.

I have the same issue.
