### ISSUE TITLE
To save subclassed Keras model from_config method is mandatory

### ISSUE THREAD

**Issue by giulatona** [tensorflow/tensorflow#46828]
## URL(s) with the issue:
https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects

## Description of issue (what needs changing):
The guide states that to save/load custom layer or a subclassed model, the get_config and optionally from_config methods should be overwritten. However, in the case of subclassed model the definition of from_config is needed and not optional.

### Clear description
Overwriting from_config is needed because the method of the base class Model calls Functional.from_config, which looks for the key 'layers' in the config and therefore raises an exception in case of a subclassed model. 

### Submit a pull request?
Submitted PR to update the guide.
https://github.com/keras-team/keras-io/pull/363

**Comment by ymodak** [comment]
Closing this issue as per the discussion in the associated PR thread tagged above. Thanks!
