### ISSUE TITLE
Estimator: how to write asset files into the assets directory hermetically when save model

### ISSUE THREAD

**Issue by lonway** [tensorflow/tensorflow#46826]
System information

- python 3.6.8
- tensorflow-gpu 1.15.0

**Describe the problem**
I have an asset file which needs to be saved within the exported model. I use estimator to export model as follows:
```
predictor = tf.estimator.Estimator()
assets_extra = {'index.idx': '/local/path/to/index.idx'}
servable_model_path = predictor.export_savedmodel(
    model_path,
    export_input_fn,
    assets_extra,
    as_text=True)
```

The parameter `assets_extra` will copy the asset file `index.idx` to the export directory. And the expected result is that the tensor in the graph which contain the directory of `index.idx` should be binded to the path of `index.idx` within the export directory. Actually,  the directory of `index.idx` in the graph dosen't change, but still `/local/path/to/index.idx`. If I move the exported model to another machine which don't contain `/local/path/to/index.idx`, the model can't find the `index.idx`.

So how can I bind the tensor value to the path of `index.idx` within the export directory?

**Comment by lonway** [comment]
I found a method `tf.saved_model.Asset` which may fix this problem, but I don't know how to use it within tf.estimator

**Comment by amahendrakar** [comment]
@lonway,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!
