### ISSUE TITLE
tensorflow 2.4 ParameterServerStrategy + Estimator will be stuck

### ISSUE THREAD

**Issue by 1148569762** [tensorflow/tensorflow#46827]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
tf version: 2.4
cluster spec:
ParameterServerStrategyV2 is now connecting to cluster with cluster_spec: ClusterSpec({'chief': ['tensorflow-tess-search-rk2-mlp-339212-chief-0.mlp.svc:2222'], 'evaluator': ['tensorflow-tess-search-rk2-mlp-339212-evaluator-0.mlp.svc:2222'], 'ps': ['tensorflow-tess-search-rk2-mlp-339212-ps-0.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-1.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-2.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-3.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-4.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-5.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-6.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-7.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-8.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-9.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-10.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-11.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-12.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-13.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-14.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-ps-15.mlp.svc:2222'], 'worker': ['tensorflow-tess-search-rk2-mlp-339212-worker-0.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-1.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-2.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-3.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-4.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-5.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-6.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-7.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-8.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-9.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-10.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-11.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-12.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-13.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-14.mlp.svc:2222', 'tensorflow-tess-search-rk2-mlp-339212-worker-15.mlp.svc:2222']})
1、tf.compat.v1.distribute.experimental.ParameterServerStrategy + Estimator :  Error reported to Coordinator: 'NoneType' object has no attribute 'extended'
example code:
strategy = tf.compat.v1.distribute.experimental.ParameterServerStrategy()
model_config = tf.estimator.RunConfig(
        train_distribute=strategy,
        eval_distribute=None,
        log_step_count_steps=config["parameters"]["log_steps"],
        save_summary_steps=config["parameters"]["save_summary_steps"],
        save_checkpoints_steps=config["parameters"]["save_checkpoints_steps"],
        save_checkpoints_secs=None,
        keep_checkpoint_max=config["parameters"]["keep_checkpoint_max"],
 )
estimator = tf.estimator.Estimator(
        model_fn=model_fn, model_dir=model_dir, params=config, config=model_config
)
![image](https://user-images.githubusercontent.com/13100437/106465747-5ada4e00-64d5-11eb-8ddc-11fb45695a88.png)

2、tf.distribute.experimental.ParameterServerStrategy + Estimator: the training job will be stuck
example code:
os.environ["GRPC_FAIL_FAST"] = "use_caller"
cluster_resolver = tf.distribute.cluster_resolver.TFConfigClusterResolver()
 variable_partitioner = (
    tf.distribute.experimental.partitioners.FixedShardsPartitioner(
    num_shards=ps_number))
strategy = tf.distribute.experimental.ParameterServerStrategy(cluster_resolver=cluster_resolver,
    variable_partitioner=variable_partitioner)
model_config = tf.estimator.RunConfig(
        train_distribute=strategy,
        eval_distribute=None,
        log_step_count_steps=config["parameters"]["log_steps"],
        save_summary_steps=config["parameters"]["save_summary_steps"],
        save_checkpoints_steps=config["parameters"]["save_checkpoints_steps"],
        save_checkpoints_secs=None,
        keep_checkpoint_max=config["parameters"]["keep_checkpoint_max"],
    )
estimator = tf.estimator.Estimator(
        model_fn=model_fn, model_dir=model_dir, params=config, config=model_config
)

**Comment by ravikyram** [comment]
@1148569762 

Can you please share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
