### ISSUE TITLE
On Windows, full-integer TFLite conversion is broken; `schema_py_generated.py` is empty

### ISSUE THREAD

**Issue by AdamHillier** [tensorflow/tensorflow#46824]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (20H2, build 19042)
- TensorFlow installation (pip package or built from source): `tensorflow_cpu` PyPI pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

```python
import tensorflow as tf
import tensorflow_model_optimization as tfmot


def make_qat_keras_model():
    model = tf.keras.models.Sequential(
        [
            tf.keras.layers.Input((224, 224, 3)),
            tf.keras.layers.Conv2D(32, (3, 3), padding="same", strides=2),
        ]
    )
    return tfmot.quantization.keras.quantize_model(model)


keras_model = make_qat_keras_model()
keras_model.summary()

with open("converted_keras_model.tflite", "wb") as f:
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    # This code works if the following two lines are commented out
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    f.write(converter.convert())
```

### 3. Failure after conversion

The above code yields the error:

```
Traceback (most recent call last):
  File ".\test_scipt.py", line 23, in <module>
    f.write(converter.convert())
  File "C:\Users\Adam\src\tmp-env\lib\site-packages\tensorflow\lite\python\lite.py", line 873, in convert
    return super(TFLiteKerasModelConverterV2,
  File "C:\Users\Adam\src\tmp-env\lib\site-packages\tensorflow\lite\python\lite.py", line 637, in convert
    result = _modify_model_io_type(result, **flags_modify_model_io_type)
  File "C:\Users\Adam\src\tmp-env\lib\site-packages\tensorflow\lite\python\util.py", line 835, in modify_model_io_type
    model_object = _convert_model_from_bytearray_to_object(model)
  File "C:\Users\Adam\src\tmp-env\lib\site-packages\tensorflow\lite\python\util.py", line 572, in _convert_model_from_bytearray_to_object
    model_object = schema_fb.Model.GetRootAsModel(model_bytearray, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
```

### Cause

The Python schema file generated as this Bazel output is just an empty file when built on Windows: https://github.com/tensorflow/tensorflow/blob/822ec5c902a7fbbb630a7ee76437abe4d8bfe13a/tensorflow/lite/python/BUILD#L11-L14

This can be verified by running `bazel build -c opt //tensorflow/lite/python:schema_py` and checking the output: `bazel-bin/external/org_tensorflow/tensorflow/lite/python/schema_py_generated.py` is empty.

Running the same build command on Linux/MacOS yields a thousands-of-LOC Python file.

The empty file issue can be further verified by unzipping the published [TensorFlow wheel](https://files.pythonhosted.org/packages/9c/3b/fb50a6d5bdaf189c6131d8db84acba2fc35d6e7d9bfd7991dd71eb304d92/tensorflow_cpu-2.4.1-cp38-cp38-win_amd64.whl) and noting that `tensorflow/lite/python/schema_py_generated.py` is an empty file.

Hence the Python attribute error.

### Related issues

* #38285

**Comment by AdamHillier** [comment]
cc @MeghnaNatraj do you know what could be causing this problem on Windows?

**Comment by MeghnaNatraj** [comment]
This issue is resolved in the following versions:
`pip install tensorflow==2.4.0`
`pip install tf-nightly` (from today: Feb 1, 2021)

There were certain tests excluded from being run on Windows/MacOS, as a result of which this error went undetected in 2.4.1. As these tests have been enabled recently, the last few 2.5-nightly-versions (2.5 hasn't been officially released yet) contain the schema_.. file.

As you want to use full integer quantization with QAT, you now have two options:
1. Use 2.4.1, and replace the file from 2.4.0 into 2.4.1
2. Use tf-nightly, starting today (Feb 1, 2021) as I have verified that this file exists in this version.

Let us know if this works for you.

**Comment by lgeiger** [comment]
@MeghnaNatraj Thanks for the fast response. I just checked the [2.4.0 Python 3.8 Windows wheel](https://files.pythonhosted.org/packages/84/f3/4aa5da782d3ad2ed33026a6e42280ce5a146b6fe71191b52e2bd0be7903e/tensorflow-2.4.0-cp38-cp38-win_amd64.whl) and the included `tensorflow/lite/python/schema_py_generated.py` file is empty, so downgrading to `2.4.0` is not an option (Mac and Linux versions are fine though).

I will check the nightly wheels from today once they are available.

**Comment by AdamHillier** [comment]
Hi @MeghnaNatraj, thanks for looking into this. To echo Lukas' point, I tested TF 2.4.0 (both `tensorflow` and `tensorflow-cpu` packages) and got the same AttributeError as before. Is it possible that this is an issue specific to the Python 3.8 wheel (seems unlikely)?

**Comment by MeghnaNatraj** [comment]
@AdamHillier It might be due to the OS you're on (Windows seem to have this issue). And probably Python 3.8. I am currently testing this on a MacOS with Python 3.6 and I was able to verify that the file is present. 

Is it possible to try running this with the latest pip package (`tf-nightly`) and let me know if you still face this issue. I will re-open and investigate the further, if the issue persists on WindowsOS with tf-nightly.

**Comment by AdamHillier** [comment]
Thanks for your help; yes, I believe this is a Windows only issue. As for `tf-nightly`, today/yesterday's published PyPI releases do not include Windows wheels.

The most recent release with a Windows wheel is `2.5.0.dev20210131` - however, when I install this in a clean environment and try and install it, I get an unrelated error `RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd` (trying to upgrade to a more recent Numpy version does not fix this, because the older Numpy version is pinned in the TF requirements).

However, `2.5.0.dev20210130` from the day before does install and work on Windows. Unfortunately, the problem this issue describes is still present.

Can we please re-open the issue, because I don't think it is currently resolved in TF-nightly?

**Comment by xunkai55** [comment]
@MeghnaNatraj Possibly it's related with the similar issue we found in TFLite Support. https://github.com/tensorflow/tflite-support/commit/1e6a6e832d5afb45877a3a974bde986000ac18dc

I guess our TF windows wheels are built in the same environment with TFLite Support wheels, so the same problem might be there. Probably you can verify if the schema_py_generated.py is empty in the current nightly. If it is, you can give my fix a try.

Thanks!

**Comment by MeghnaNatraj** [comment]
@xunkai55 Thank you for this suggestion. It looks like the past few Windows builds seem to have this issue - so I'm working on patching in your solution. 

I'll update this issue once the fix is merged and a new tf-nightly is published.

**Comment by MeghnaNatraj** [comment]
I've patched the change in and the latest `tf-nightly` package has the schema_py_generated file. Thank you for the fix @xunkai55
