### ISSUE TITLE
backing_device changes depending on the tensor's dtype

### ISSUE THREAD

**Issue by miguelusque** [tensorflow/tensorflow#46833]
Hi!

I have noticed that `backing_device` changes depending on the Tensor's `dtype`:

```python
import tensorflow as tf
tensor_1 = tf.math.add(tf.zeros([2, 2]), [[1, 2], [3, 4]])
tensor_2 = tf.math.add(tf.zeros([2, 2], dtype=tf.dtypes.int32), [[1, 2], [3, 4]])
 
print(tensor_1.backing_device)
print(tensor_2.backing_device)
```
 

```
/job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0
```

The behaviour above has some impact when interacting with other libraries. For instance, when exporting the Tensor via DLPack, some libraries (i.e. CUDA or JAX), do not support DLPack object hosted in CPU memory.

Hope it helps!
Miguel

**System information**
- TensorFlow version: 2.4.1
- Ubuntu 20.04
- Cuda 11.0
- Python 3.8
- Installed via pip.

**Describe the current behavior**
One tensor backing device is CPU, while the other is GPU.

**Describe the expected behavior**
Having GPU as backing device for both tensors.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/a63bda22f935bffd7c9715b07c3a93c5/46833-2-3.ipynb) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/442ebb80b1a53c219e6d34f622c00859/46833.ipynb#scrollTo=i2A5oY8bQUq-).

Whereas Colab doesn't detect the GPU with latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/abba546e65072cb19f02f16ae77d7c22/46833-tf-nightly.ipynb). Please check the linked gist for reference. Thanks!

**Comment by VoVAllen** [comment]
This is the expected behavior, that all the int32 tensors are on cpu by default, no matter which context device is specified.

**Comment by VoVAllen** [comment]
You can force it on gpu by using `tf.identity` operator

**Comment by miguelusque** [comment]
Hi @VoVAllen ,

I understand that is the current behaviour. Nevertheless, it looks it has some impact on some scenarios, as the one described in this issue.

Therefore, could it be reconsidered the current behaviour? Nowadays, GPUs can efficiently deal with int32 tensors.

Regards,
Miguel

**Comment by VoVAllen** [comment]
@miguelusque I'm not tf developer, but met the same issue before. Generally speaking this is a legacy issue from tensorflow 1. int32 tensors are usually used to represent the shape information, thus many operators assume it's a cpu operator. If changed to gpu by default, many codes and op implementations will break.

**Comment by VoVAllen** [comment]
Some issues related to this https://github.com/tensorflow/tensorflow/issues/34071, https://github.com/tensorflow/tensorflow/issues/41307

**Comment by miguelusque** [comment]
Hi @VoVAllen ,

Thank you for your detailed reply.

it looks like we are in a front of a great use case to challenge CI/CD system used in TensorFlow. 😀

I hope the TF dev team may consider this issue.

Regards,
Miguel

**Comment by pandrey-fr** [comment]
Hello,

Many thanks to VoVAllen for clarifying where this behavior comes from.

I am currently facing a practical issue due to this (as other have before): when I convert int Tensors to dlpack in order to use pre-compiled custom cuda kernels (using TVM), they end up on the CPU, which causes my custom code to fail.

I am therefore wondering : **how can you force a given int Tensor to have a GPU as 'backing_device' (in addition to having it as 'device')?** Some GitHub Issues suggest using 'tf.identity', but I cannot seem to make it work.

Thanks in advance,
Paul

**Comment by pandrey-fr** [comment]
My bad, you mentioned a trick [here](https://github.com/tensorflow/tensorflow/issues/41307#issuecomment-657385914) by casting to and then from unsigned int. This is not optimal, but it works.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/cbcca6a474a1a37a3f09fc52cbabf24a/untitled49.ipynb#scrollTo=hr6nP5jy59AQ) ..Thanks !

**Comment by wangpengmit** [comment]
Hi @miguelusque, you've hit a long-running issue internally known as "the int32 problem". Basically TF carves out int32 as "the shape dtype", to workaround some design problems of the device-placement system. We're designing potential alternatives but it's hard to fix. At the moment just don't use int32 for your normal computation.

**Comment by tilakrayal** [comment]
@miguelusque,
I was able to get the expected result with int64 or uint32 as commented by the developer. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/072f762abdb8e1d28f31407c68ec5a0a/untitled49-latest.ipynb) and let us know if the issue still persists. Thank you!

**Comment by miguelusque** [comment]
Hi @tilakrayal , I would say that the issue still persists because it was raised on int32, and not uint32 or other datatypes.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220721. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/154bd6ccaddf9480320cc7e9609513e8/untitled49-latest.ipynb). Thank you!
