### ISSUE TITLE
FATAL ERROR: tensorflow/core/framework/types.pb.h: No such file or directory

### ISSUE THREAD

**Issue by shashank2710** [tensorflow/tensorflow#46837]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. Standard C++ program used to previously compile and run with TF 1.1 (CUDA - 9.2 and CUDNN 7.2 )
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: CUDA - 10.2/ CUDNN - 7.6
- GPU model and memory: Quadro P5200, 32 Gb RAM

**Describe the current behavior**
TF 2.3.0 successfully installs with bazel. However, while compiling a C++ program using gcc, I get the following error
_**/usr/local/include/tensorflow/tensorflow/core/framework/tensor_shape.h:22:10: fatal error: tensorflow/core/framework/types.pb.h: No such file or directory**_
I tried to locate the types.pb.h file and found the file in _/home/%username%/.cache/bazel/_bazel_%username%/3fa00a5b455754a3e6fd353fefb67596/execroot/org_tensorflow/bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/core/framework/types.pb.h_
Copying or including this folder/file did not help as additional dependencies were missing. 

**Standalone code to reproduce the issue**
Clone tensorflow from github and checkout v2.3.0. Run ./configure with following options (refer attachment)
Bazel build with the following options:
_bazel build -c opt \
            --copt=-mavx \
            --copt=-mavx2 \
            --copt=-mfma \
            --copt=-mfpmath=both \
            --copt=-msse4.2 \
            --config=cuda //tensorflow:libtensorflow_cc.so_
[TF_Config.txt](https://github.com/tensorflow/tensorflow/files/5906638/TF_Config.txt)

**Comment by amahendrakar** [comment]
@shashank2710,
Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by shashank2710** [comment]
@amahendrakar, 
**Issue still persists in v2.4.1.** 

Error 1:
**_/usr/local/include/tensorflow/tensorflow/core/framework/tensor_shape.h:22:10: fatal error: tensorflow/core/framework/types.pb.h: No such file or directory_**

Resolution:
Resolved by adding  /usr/local/include/tensorflow/bazel-bin to the c++ include path. 
/usr/local/include/tensorflow/bazel-bin has a symlink to /home/%username%/.cache/bazel/_bazel_%username%/3fa00a5b455754a3e6fd353fefb67596/execroot/org_tensorflow/bazel-out/k8-opt/bin

Error 2
After resolving Error 1 I encounter the following error. This is similar to 
**_/usr/local/include/tensorflow/bazel-bin/tensorflow/core/framework/types.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory_**
Resolution: 
I had to include the following in my c++ program
/home/%username%/.cache/bazel/_bazel_%username%/3fa00a5b455754a3e6fd353fefb67596/external/com_google_protobuf/src

Note: 
I have installed Bazel 3.1.0 from source, not the standard apt-repository

**Comment by amahendrakar** [comment]
@shashank2710,
TensorFlow v2.4 is built and tested against **CUDA 11.0** and **cuDNN 8**. Could you please update the CUDA and cuDNN packages on your machine and check if it helps.

Also, please run the `bazel clean --expunge` command before building and let us know if you are facing the same error. Thanks!

**Comment by shashank2710** [comment]
@amahendrakar 
I re-installed TF v2.4.0 with CUDA 11.0 and cuDNN 8.0. All 3 errors mentioned above still exist. 

After resolving the errors manually, I tried to compile the project using g++ and received the following errors

> TensorFlowUtils.cpp:(.text+0x753): undefined reference to `tensorflow::Env::GetFileSize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long long*)'
makefile:50: recipe for target failed
TensorFlowUtils.cpp:(.text+0x7b4): undefined reference to `tensorflow::Env::NewRandomAccessFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<tensorflow::RandomAccessFile, std::default_delete<tensorflow::RandomAccessFile> >*)'
./src/TensorFlowUtils.o: In function `TensorFlowUtils::getTopLabels(std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*)':
TensorFlowUtils.cpp:(.text+0x3367): undefined reference to `tensorflow::Scope::WithOpNameImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
./src/TensorFlowUtils.o: In function `TensorFlowUtils::loadGraph(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<tensorflow::Session, std::default_delete<tensorflow::Session> >*)':
TensorFlowUtils.cpp:(.text+0x3d6f): undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::MessageLite*)'
./src/TensorFlowUtils.o: In function `TensorFlowUtils::readTensorFromImageFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, float, float, std::vector<tensorflow::Tensor, std::allocator<tensorflow::Tensor> >*)':
TensorFlowUtils.cpp:(.text+0x54fd): undefined reference to `tensorflow::Scope::WithOpNameImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
./src/TensorFlowUtils.o: In function `TensorFlowUtils::convertOpenCvImageToTfImageFileIo(cv::Mat, int, int, float, float)':
TensorFlowUtils.cpp:(.text+0x67fb): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/TensorFlowUtils.o: In function `tensorflow::Scope tensorflow::Scope::WithOpName<char const*>(char const*) const':
TensorFlowUtils.cpp:(.text._ZNK10tensorflow5Scope10WithOpNameIJPKcEEES0_DpT_[_ZNK10tensorflow5Scope10WithOpNameIJPKcEEES0_DpT_]+0x57): undefined reference to `tensorflow::Scope::WithOpNameImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
./src/TensorFlowUtils.o: In function `tensorflow::Status tensorflow::errors::NotFound<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*)':
TensorFlowUtils.cpp:(.text._ZN10tensorflow6errors8NotFoundIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EEENS_6StatusEDpT_[_ZN10tensorflow6errors8NotFoundIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EEENS_6StatusEDpT_]+0x97): undefined reference to `tensorflow::strings::StrCat[abi:cxx11](tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&, tensorflow::strings::AlphaNum const&)'
./src/TensorFlowUtils.o: In function `tensorflow::Status tensorflow::errors::DataLoss<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, unsigned long long, char const*, unsigned long>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, unsigned long long, char const*, unsigned long)':
TensorFlowUtils.cpp:(.text._ZN10tensorflow6errors8DataLossIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_yS3_mEEENS_6StatusEDpT_[_ZN10tensorflow6errors8DataLossIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_yS3_mEEENS_6StatusEDpT_]+0x196): undefined reference to `tensorflow::strings::internal::CatPieces[abi:cxx11](std::initializer_list<absl::lts_2020_02_25::string_view>)'
./src/DetectChars.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
DetectChars.cpp:(.text._ZN10tensorflow8internal17MakeCheckOpStringImmEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringImmEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x51): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
./src/DetectChars.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
DetectChars.cpp:(.text._ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIliEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x50): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
./src/DetectChars.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long long, long long>(long long const&, long long const&, char const*)':
DetectChars.cpp:(.text._ZN10tensorflow8internal17MakeCheckOpStringIxxEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN10tensorflow8internal17MakeCheckOpStringIxxEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x51): undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()'
./src/Classification.o: In function `Classification::init()':
Classification.cpp:(.text+0x461): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
Classification.cpp:(.text+0x517): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/Classification.o: In function `Classification::classify(cv::Mat const&)':
Classification.cpp:(.text+0x11ca): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/SubClass.o: In function `SubClass::init()':
SubClass.cpp:(.text+0xa81): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
SubClass.cpp:(.text+0xaa3): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/SubClass.o:SubClass.cpp:(.text+0xb5b): more undefined references to `tensorflow::Status::empty_string[abi:cxx11]()' follow

I am currently referring #43307 and #40538
I compiled with 

> bazel build  --config=v2 --config=opt --copt=-O3 --copt=-m64 --copt=-march=native --verbose_failures //tensorflow:install_headers //tensorflow:tensorflow //tensorflow:tensorflow_cc //tensorflow:tensorflow_framework //tensorflow/tools/lib_package:libtensorflow

This was able to resolve 12 of 18 g++ tensorflow linker errors. 
I still have the have the following errors during c++ compilation. 
> Classification.cpp:(.text+0x461): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
Classification.cpp:(.text+0x517): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/Classification.o: In function `Classification::classify(cv::Mat const&)':
Classification.cpp:(.text+0x11ca): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/SubClass.o: In function `SubClass::init()':
SubClass.cpp:(.text+0xa81): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
SubClass.cpp:(.text+0xaa3): undefined reference to `tensorflow::Status::empty_string[abi:cxx11]()'
./src/SubClass.o:SubClass.cpp:(.text+0xb5b): more undefined references to `tensorflow::Status::empty_string[abi:cxx11]()' follow
collect2: error: ld returned 1 exit status

**Comment by shashank2710** [comment]
@amahendrakar 
Weekend update. Referred #43307 and #40538. 
I compiled TF v2.4 with CUDA 11 and CuDNN 8.0 with the following bazel command options

>bazel build -c opt --copt=-O3 --copt=-m64 --copt=-march=native --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --verbose_failures //tensorflow:install_headers //tensorflow:tensorflow //tensorflow:tensorflow_cc //tensorflow:tensorflow_framework //tensorflow/tools/lib_package:libtensorflow

This resolved Error 2 and all g++ compiler/linker errors. **Errors 1 and 2 still exist.**

**Comment by mihaimaruseac** [comment]
You should not need to manually download other repos and symlink.

Most likely your bazel cache is corrupted.

**Comment by shashank2710** [comment]
@amahendrakar , 
A fresh ubuntu install and updated bazel flags helped resolve this issue.

**Comment by ArthurShen8118** [comment]
May I ask what do you means about ubuntu fresh install and update bazel?

Can you break them into the detail, thanks
