### ISSUE TITLE
TF 2.4.1: Mirrored Strategy not providing performance boost RTX 3090 

### ISSUE THREAD

**Issue by LastHorizon** [tensorflow/tensorflow#46831]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8.0.4.30
- GPU model and memory: 2x RTX 3090/24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have a dataset created from an image directory (tf.keras.preprocessing.image_dataset_from_directory()). I then use a mirrored strategy (tf.distribute.MirroredStrategy) to create and compile my model then I try training the model using model.fit(). The call to model.fit causes an error message to inform me that the dataset is unshardable. I am therefore not receiving a performance increase from the second RTX 3090 GPU that I have just installed in the machine. 

**Describe the expected behavior**

When I used this approach using Tensorflow 2.3.1 and 2 x RTX 2060s, I did not generate any error messages about sharding the dataset, the log printed that it was running with a mirrored strategy, and listed the GPUs being used, and there was a significant performance boost

**Standalone code snippet to reproduce the issue**

```

def get_compiled_model(num_classes, dim_x, dim_y, dim_z):

        data_augmentation = keras.Sequential(
          [
                layers.experimental.preprocessing.RandomFlip("horizontal", input_shape=(dim_x, dim_y, dim_z)),
                layers.experimental.preprocessing.RandomRotation(0.1),
                layers.experimental.preprocessing.RandomZoom(0.1),
          ]
        )


        model = Sequential([
          data_augmentation,
          layers.experimental.preprocessing.Rescaling(1./255),
          layers.Conv2D(2, 3, padding='same', activation='relu'),
          layers.MaxPooling2D(),
          #layers.Conv2D(32, 3, padding='same', activation='relu'),
          #layers.MaxPooling2D(),
          #layers.Conv2D(64, 3, padding='same', activation='relu'),
          #layers.MaxPooling2D(),
          layers.Dropout(0.2),
          layers.Flatten(),
          layers.Dense(6, activation='relu'),
          layers.Dropout(0.2),
          layers.Dense(num_classes)
        ])
        model.compile(
                #optimizer=tf.keras.optimizers.Adam(),
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'],
        )

        return model


## create data set 

        train_ds = tf.keras.preprocessing.image_dataset_from_directory(
          data_dir,
          validation_split=0.2,
          subset="training",
          seed=123,
          image_size=(50, 50),
          batch_size=2048,
          color_mode='grayscale'
        )
        val_ds = tf.keras.preprocessing.image_dataset_from_directory(
          data_dir,
          validation_split=0.2,
          subset="validation",
          seed=123,
          image_size=(50, 50),
          batch_size=2048,
          color_mode='grayscale'
        )


## create model with mirrored strategy 
        mirrored_strategy = tf.distribute.MirroredStrategy()

        with mirrored_strategy.scope():

                model = get_compiled_model(2, 50, 50, 1):


## train model 

        history = model.fit(
          train_ds,
          validation_data=val_ds,
          epochs=5000,
          initial_epoch=0,
        )

```

**Comment by nikitamaia** [comment]
Hi @LastHorizon, can you provide screenshots showing the training logs between 2.3 and 2.4? I would like to know what the difference in training time per epoch is. 

As for the error message about the dataset being unshardable, there is no autosharding when you're doing single worker training. Autosharding is only necessary with multi worker training. So with `MirroredStrategy` the autosharding options register as no-op. However, in 2.4 the code is shared with `MultiWorkerMirroredStrategy` so you see the warnings regardless. If you want to get rid of the that warning, [you can set the autoshard policy to data](https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy), but in the single worker case it should not actually impact performance.

```
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
train_ds = train_ds.with_options(options)
```

**Comment by LastHorizon** [comment]
Hi @nikitamaia 

Unfortunately I can't provide screenshots because I am accessing the machine remotely and the 2060s have been taken out. (They are about to installed in a new machine.) However I can remember what the stats are that you are interested in: 

`MirroredStrategy` with two RTX 2060s - Epoch takes **85s**
`MirroredStrategy` with two RTX 3090s - Epoch takes **90s**

As you can see, the two 2060 graphics cards are out performing the much more powerful 3090 cards!

**Comment by nikitamaia** [comment]
Can you provide fully reproducible code? It's difficult to debug much further without reproducible code or logs.

Also, did setting the autoshardpolicy make the sharding error go away?
