### ISSUE TITLE
Hi everyone, I want to look at the person_detect.tflite model you mentioned in Arduino IDE ESP32 person detection code, I want to look at the input layer of it, my beetle classifier has 96 by 96 and is grayscale so it is 1 x 96 x96 x1, but I am not sure if I can modify the person detection code to detect beetle or cat and dog TFlite converted to c model. Would you please provide the person_detect.tflite model available online? 

### ISSUE THREAD

**Issue by Paryavi** [tensorflow/tensorflow#46847]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by Paryavi** [comment]
Also Would you please create a tutorial document, showing steps from TFLite to ESP 32 Tensorflow with a Colab example for image classification? like cat-dog classification or flower classification steps after TFLite.

**Comment by yair-ehrenwald** [comment]
Hi, I haven't tried this myself, but with the tool added here: https://github.com/tensorflow/tensorflow/pull/42837
You should be able to get the tflite file from the c array model.

**Comment by vikramdattu** [comment]
@Paryavi I have a cats_and_dogs example here with Jupyter notebook here: https://github.com/vikramdattu/tensorflow/tree/master/tensorflow/lite/micro/examples/cats_and_dogs

**Comment by sanatmpa1** [comment]
@Paryavi,

Can you confirm if the above link provided by @vikramdattu helps in resolving this issue? Thanks!

**Comment by Paryavi** [comment]
Thanks, Sanat and @vikramdattu <https://github.com/vikramdattu>, I got busy
with other camera board detection projects like OpenMV, also college class
works.

Before that, I tried training the ESP32 classification models with edge
impulse framework;
https://www.edgeimpulse.com/blog/add-sight-to-your-esp32
It was not very accurate, so I will check Vikram's design eventually, it is
great to have a framework like it.

Thanks,
Mohsen

**Comment by sanatmpa1** [comment]
Thanks for the update @Paryavi, In this case, Can you close this issue and create a new one in future if you face any problems? Thanks!
