### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#46840]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOs Big Sur
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.7

**Describe the current behavior**

I'm trying to assign the return value of `get_value()` to a numpy array within a method decorated using `tf.function`. It works only if I call the method directly. However, if I use the result of `tf.numpy_function()` (in `case3`), I get an error. 

**Describe the expected behavior**

I don't know, but the error is not doing any good explaining why this is happening

**Standalone code to reproduce the issue**
Please find the notebook [here](https://colab.research.google.com/drive/1npV2ZmDE-So0IlA63MpoKhIs7sL-N6Xu?usp=sharing) which contains the following:

    import numpy as np
    import tensorflow as tf
    
    
    class Foo:
        def __init__(self):
            self.storage = np.zeros((10, 3, 1))
    
        @staticmethod
        def get_value(): 
            return np.array([[1], [2], [3]])
    
        @tf.function
        def case1(self):  # works
            self.storage[0] = self.get_value()
    
        def case2(self):  # works
            self.storage[0] = tf.numpy_function(self.get_value, inp=[], Tout=tf.float32)
    
        @tf.function  # fails
        def case3(self):
            self.storage[0] = tf.numpy_function(self.get_value, inp=[], Tout=tf.float32)
    
    
    if __name__ == '__main__':
        foo = Foo()
        foo.case1()
        foo.case2()
        foo.case3()

Error:

    2021-02-01 23:11:35.422101: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
    2021-02-01 23:11:35.422548: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    2021-02-01 23:11:35.439501: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
    Traceback (most recent call last):
      File "/Users/emadboctor/Library/Application Support/JetBrains/PyCharm2020.3/scratches/scratch.py", line 29, in <module>
        foo.case3()
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
        result = self._call(*args, **kwds)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
        self._initialize(args, kwds, add_initializers_to=initializers)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
        self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
        graph_function, _ = self._maybe_define_function(args, kwargs)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
        graph_function = self._create_graph_function(args, kwargs)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
        func_graph_module.func_graph_from_py_func(
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
        out = weak_wrapped_fn().__wrapped__(*args, **kwds)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
        return wrapped_fn(*args, **kwargs)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    TypeError: in user code:
    
        /Users/emadboctor/Library/Application Support/JetBrains/PyCharm2020.3/scratches/scratch.py:22 case3  *
            self.storage[0] = tf.numpy_function(self.get_value, inp=[], Tout=tf.float32)
    
        TypeError: __array__() takes 1 positional argument but 2 were given

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4, nightly version(`2.5.0-dev20210201`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/85e69a98c5573d6ff6ac367be6b8a3a7/untitled649.ipynb).Thanks!

**Comment by nfelt** [comment]
See also #46563 for a little more detail about what causes this error in general.

**Comment by emadboctorx** [comment]
@nfelt Any particular suggestions for fixing the issue?

**Comment by nfelt** [comment]
@emadboctorx Unfortunately not really. My best guess is that something in the wrapper logic around `numpy_function` is attempting to convert some sort of TF tensor object into a numpy ndarray to feed as an argument into your `numpy_function` and at that point is hitting the same conversion error that I hit in the other issue.  However, the actual original stacktrace seems to be obscured because the error message is being re-propagated up through some intermediate layers.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5c3c061fc9a60c88b64b71612c7280e0/untitled47.ipynb#scrollTo=COohR0nH3Jta)..Thanks !

**Comment by exeptionerror** [comment]
All Possible solution added [[Solved] TypeError: method() takes 1 positional argument but 2 were given](https://flutterq.com/typeerror-method-takes-1-positional-argument-but-2-were-given/)

**Comment by sat219** [comment]
Able to reproduce the error for a similar case as shown below:

from PIL import Image
img_data = np.random.random(size=(100, 100, 3))
img = tf.keras.preprocessing.image.array_to_img(img_data)
array = tf.keras.preprocessing.image.img_to_array(img)

TypeError                                 Traceback (most recent call last)
<ipython-input-115-e13b4c9f83c3> in <module>
      2 img_data = np.random.random(size=(100, 100, 3))
      3 img = tf.keras.preprocessing.image.array_to_img(img_data)
----> 4 array = tf.keras.preprocessing.image.img_to_array(img)

~\anaconda3\envs\tf-latest-gpu\lib\site-packages\tensorflow\python\keras\preprocessing\image.py in img_to_array(img, data_format, dtype)
    226       dtype = backend.floatx()
    227     kwargs['dtype'] = dtype
--> 228   return image.img_to_array(img, data_format=data_format, **kwargs)
    229 
    230 

~\anaconda3\envs\tf-latest-gpu\lib\site-packages\keras_preprocessing\image\utils.py in img_to_array(img, data_format, dtype)
    307     # or (channel, height, width)
    308     # but original PIL image has format (width, height, channel)
--> 309     x = np.asarray(img, dtype=dtype)
    310     if len(x.shape) == 3:
    311         if data_format == 'channels_first':

TypeError: __array__() takes 1 positional argument but 2 were given

**Comment by ABNER-1** [comment]
I found that was caused by PIL lib.
I found the numpy array function description here
```
 An array, any object exposing the array interface, an object whose
            __array__ method returns an array, or any (nested) sequence.
```

so, it will invoke the `__array__` of PIL object.
I solved this problems by downgrade PIL from 8.3.0 to 8.2.0.
Maybe this will help you.

**Comment by bersbersbers** [comment]
> I solved this problems by downgrade PIL from 8.3.0 to 8.2.0.

Thanks! I had suspected something like this, so I had done a `pip install --upgrade --force-reinstall tensorflow` already. Interestingly, the `pillow` package was unaffected by this change, as it is not even listed in the `tensorflow` dependency tree.

`pip install "pillow<8.3"` does indeed fix this for now, and the root issue is tracked in https://github.com/python-pillow/Pillow/issues/5571.

**Comment by TMPhoenix** [comment]
Just came by to say that we too were seeing issues with this and a downgrade of pillow to 8.2.0 has worked around the issue for now.

**Comment by Bhisham-Sharma** [comment]
> I found that was caused by PIL lib.
> I found the numpy array function description here
> 
> ```
>  An array, any object exposing the array interface, an object whose
>             __array__ method returns an array, or any (nested) sequence.
> ```
> 
> so, it will invoke the `__array__` of PIL object.
> I solved this problems by downgrade PIL from 8.3.0 to 8.2.0.
> Maybe this will help you.

Thanks alooooot !!

**Comment by makcimbx** [comment]
Upgrade to 8.3.1 is work too.

**Comment by flutterq2** [comment]
[[already solved] TypeError: __array__() takes 1 positional argument but 2 were given](https://exerror.com/typeerror-array-takes-1-positional-argument-but-2-were-given/)

**Comment by sjtusmartboy** [comment]
I have the same problem, downgrading pillow to 8.2.0 doesn't solve my problem.
Ubuntu18.10
python3.7
tensorflow2.6

**Comment by sjtusmartboy** [comment]
＠schissmantics, Hi, have you solved this problem now, I've tried your code on tensorflow 2.5 and python 3.7 and Pillow 8.2.0(8.3.1), not solving the problem and same error.

**Comment by collinzrj** [comment]
In some newer version of numpy, an extra parameter `dtype` may be passed to the the `__array__` attribute of an object, but in previous implementation of `Tensor` and some other structures, `__array__` is defined like
```
  def __array__(self):
    raise NotImplementedError(
        "Cannot convert a symbolic Tensor ({}) to a numpy array."
        " This error may indicate that you're trying to pass a Tensor to"
        " a NumPy call, which is not supported".format(self.name))
```
In that case, an error is thrown before the function is executed
#51595 and fc0f0e61ca9fe3ca3b9b58f51bcf00e0643ed9e3 can solve this

**Comment by caio-davi** [comment]
The issue is **NOT** related to Pillow. It is clear by the description and the [notebook](https://colab.research.google.com/drive/1npV2ZmDE-So0IlA63MpoKhIs7sL-N6Xu?usp=sharing). 
It seems to be related to [this issue](https://github.com/tensorflow/tensorflow/issues/32927), though. 
I thought [this commit](https://github.com/tensorflow/tensorflow/commit/c8c6683f33bf93495dcd2bc2cb103e0adaa01718#diff-3bac640d4fd7baf52009c2ed77c693723025a266052799f44c16cf53c3bdfc53) would solve the issue, but it seems not to be the case.

**Comment by caio-davi** [comment]
The changes mentioned by @collinzrj does fix the problem, but it raises another error:
```
NotImplementedError: Cannot convert a symbolic Tensor (PyFunc:0) to a numpy array. 
This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.
```

Although, I think this one is indeed expected.

**Comment by collinzrj** [comment]
@caio-davi yes, it is expected
