### ISSUE TITLE
LU solve output shape incorrect for wildcard batched inputs

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#46857]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab version
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): colab version
- Python version: colab version
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: colab version
- GPU model and memory: NA

**Describe the current behavior**
tf.linalg.lu_solve does not trace shapes properly:
if M is a tensor of shape (None, a, a) and RHS a tensor of shape (None, a, b), computing M^{-1}RHS returns a tensor of shape (None, a, None).
This is in contradiction with using tf.linalg.solve directly which is better behaved.

**Describe the expected behavior**
The shape tracing should happen properly.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1qkZfPVaLIjKyLwg-N-n4DBkvwZUrBCkW?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/88c9436b2446ea66c34436fa40e0a4a0/46857.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/441ca7be27bcef72f84bb789e6c4f971/untitled45.ipynb)..Thanks !

**Comment by tilakrayal** [comment]
Could you please find the gist [here](https://colab.research.google.com/gist/tilakrayal/ef046ca27effb84a9718c4aeaf580dfc/untitled45.ipynb) and let us know if the issue still persists. Thank you!
