### ISSUE TITLE
TF 2.5 nightly CUDA driver check failed 

### ISSUE THREAD

**Issue by LastHorizon** [tensorflow/tensorflow#46851]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.5.0-dev20210202
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: Pip 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8.0.4
- GPU model and memory: 2 x RTX 3090 w/ 24GB

**Describe the problem**
I have installed the tensorflow 2.5 nightly builds: 
```
pip install tf-nightly-gpu
pip install tf-nightly
```
into a virtual environment to try and address performance issues with using a dual RTX 3090 setup. When I try and execute the python script I get the following error from the CUDA driver: 
```
2021-02-02 09:48:40.071972: F tensorflow/stream_executor/cuda/cuda_driver.cc:1289] Check failed: context != nullptr success should entail non-null context
```

I assume this might be linked to the CUDA/cuDNN revision being used but I can't find any instructions as to the versions being of CUDA/cuDNN being expected. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
pip install tf-nightly-gpu
pip install tf-nightly

**run python script** 

```

N.B. the script is working as it executes under other versions of TF.

**Comment by ravikyram** [comment]
@LastHorizon 

Can you try with CUDA 11.1 and see if the issue still persists?
Thanks!

**Comment by LastHorizon** [comment]
@ravikyram 

The following have been installed and the problem still persists 

libnvinfer7_7.2.2-1+cuda11.1_amd64.deb 
cuda-11-1
libcudnn8=8.0.4.30-1+cuda11.1
libcudnn8=8.0.4.30-1+cuda11.1
libnvinfer7=7.2.2-1+cuda11.1 
libnvinfer-dev=7.2.2-1+cuda11.1 
libnvinfer-plugin7=7.2.2-1+cuda11.1

**Comment by Saptr** [comment]
try cuda 11.0 and cudnn8.0.2 if rtx3090
I worked successful.
and cuda 11.1 and cudnn 8.0.4 worked on  rtx3080 but cannot work on rtx3090

**Comment by rmothukuru** [comment]
@Saptr,
Can you please let us know if the above comment helped you. Thanks!

**Comment by RaenonX** [comment]
> @Saptr,
> Can you please let us know if the above comment helped you. Thanks!

@rmothukuru I think you pinged the wrong guy

**Comment by rmothukuru** [comment]
Yeah, sorry.
@LastHorizon,
Can you please let us know if the [above comment](https://github.com/tensorflow/tensorflow/issues/46851#issuecomment-773078880) helped you. Thanks!

**Comment by LastHorizon** [comment]
@rmothukuru 
After downgrading to libcudnn 8.0.02.39-1+cuda11.0 and upgrading tf-nightly-gpu through pip, I can report the tf-nightly build is now running. 

I am not getting the expected performance boosts from the GPUs though when compared to the old 2060s

**Comment by rmothukuru** [comment]
@LastHorizon,
As the issue regarding Installation is resolved, Can you please close this issue and raise a new issue related to the performance of your GPUs. Thanks!
