### ISSUE TITLE
Requesting MatrixDeterminant op in tflite

### ISSUE THREAD

**Issue by dpmcgonigle** [tensorflow/tensorflow#46859]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3+
- Are you willing to contribute it (Yes/No): I would need guidance / access to someone who knows the tflite codebase

**Describe the feature and the current behavior/state.**
I request that the operator MatrixDeterminant be added to the tensorflow-lite operators.  Currently, tensorflow/core/kernels/determinant_op.[cc/h] defines the standard tensorflow MatrixDeterminant operation, but there appears to be no such operation for tflite.

I am trying to convert the Glow model (https://github.com/openai/glow) to tflite, but I am running into the issue where I can't convert the trained pb file and invoke it because there is no MatrixDeterminant operation.

**Will this change the current api? How?**
It would add an operation for MatrixDeterminant to tflite's operators.

**Who will benefit with this feature?**
Anyone trying to convert a model containing the MatrixDeterminant operation to tflite.

**Any Other info.**

**Comment by abattery** [comment]
Will add MatrixDeterminant op to the Select TF option soon. https://www.tensorflow.org/lite/guide/ops_select

**Comment by dpmcgonigle** [comment]
Thank you very much for the quick response!!

**Comment by abattery** [comment]
The operator is now included at the head. You can try tomorrow's tf-nightly version if you are using `pip` command.
