### ISSUE TITLE
Cannot use load_model when using a layer with dynamic = True and saving to hdf5 format

### ISSUE THREAD

**Issue by kimartin** [tensorflow/tensorflow#46853]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA Quadro RXT 6000, 24 GB NVRAM

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When building a model (using the Function API), I need to use a layer in dynamic mode as far as I can tell, since the task is going to involve operations along an axis of variable size.
While the training works perfectly fine, and the saving of the model also does as far as I can tell (no error, at least), when loading the model back up using load_model fails with the error:
ValueError: You are trying to load a weight file containing [n] layers into a model with [n-1] layers.

Upon inspection of the load_weights_from_hdf5_group function, it appears that layers build with dynamic=True return an empty list with trying to get the weights, which results in such layers not being included in the following operations, ultimately resulting in the function failing. However, the layer itself is found and otherwise normal (e.g. its name gets found properly by the same function).

This affects both new models and ones saved before the update.

**Describe the expected behavior**
The model should load properly, as it did in previous versions (I have tested up to 2.3.1). 

**Standalone code to reproduce the issue**
I write two versions of the same little script, the only difference is the `dynamic` flag in the first Conv2D layer.
I originally discovered this when using a custom layer (where the need for the dynamic=True flag came in), but this also happens when using the Conv2D layer.
```
from tensorflow.keras.models import load_model, Model
from tensorflow.keras.layers import Conv2D, Input

# this works
inp = Input(shape=(64, None, 3))
conv = Conv2D(4, (3, 3), dynamic=False)
# dynamic = True apparently requires manual building, which might or might not be a separate issue
conv.build(inp.shape)
x = conv(inp)
x = Conv2D(4, (3, 3))(x)

mod1 = Model(inputs=inp, outputs=x)

mod1.save("test.hdf5")
load_model("test.hdf5")
print("Succesfully loaded this model")

# this fails:
inp = Input(shape=(64, None, 3))
conv = Conv2D(4, (3, 3), dynamic=True)
# dynamic = True apparently requires manual building, which might or might not be a separate issue
conv.build(inp.shape)
x = conv(inp)
x = Conv2D(4, (3, 3))(x)

mod1 = Model(inputs=inp, outputs=x)

mod1.save("test.hdf5")
load_model("test.hdf5")
print("Succesfully loaded this model")`

**Other info / logs** 
`Traceback (most recent call last):
  File "C:/Users/killian/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/scratch_7.py", line 29, in <module>
    load_model("test.hdf5")
  File "C:\Users\killian\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\save.py", line 207, in load_model
    compile)
  File "C:\Users\killian\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 187, in load_model_from_hdf5
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "C:\Users\killian\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 691, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 2 layers into a model with 1 layers.
`

**Comment by amahendrakar** [comment]
@kimartin,
Looking at issues [#44533](https://github.com/tensorflow/tensorflow/issues/44533#issuecomment-749246090) and [#43498](https://github.com/tensorflow/tensorflow/issues/43498#issuecomment-709533001) with a similar error log, I was able to save and load the model in `tf` format. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6b76cf7cae52a1de37049395ab682641/46853.ipynb). Thanks!

**Comment by kimartin** [comment]
@amahendrakar Switching to the tf format as in the gist does provide a workaround for saving new models, thank you. 
Unlike the issues mentioned however I had no problem with custom objects (in particular at least), just with the dynamic flag, so this definitely seems like a bug.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/85077ec6810f624599b3c2d1643f816f/untitled46.ipynb#scrollTo=HZuVem9A10lx)..Thanks !

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
