### ISSUE TITLE
A mistake code on Model Maker Guide

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#46866]
The image classification code on [official Model Maker Guide](https://tensorflow.google.cn/lite/guide/model_maker) may get a mistake on training data name.

![516441612286382_ pic_hd](https://user-images.githubusercontent.com/17171866/106685499-76437700-6603-11eb-83c3-6e4098e44183.jpg)

Mistake code in above red rectangle, I think should be replace with following code snippet.
```
model = image_classifier.create(train_data)
```

**Comment by lintian06** [comment]
Thank you for the suggestion! Will fix it soon.
