### ISSUE TITLE
RuntimeError: Unable to create link (name already exists)

### ISSUE THREAD

**Issue by shanmukh05** [tensorflow/tensorflow#46871]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): kaggle kernel
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

This is my  Notebook:
[Kaggle Notebook](https://www.kaggle.com/shanmukh05/cassave-leaf-diseases-tpu-final/edit/run/53396178)
This is the main model I am using:
![error](https://user-images.githubusercontent.com/65073329/106710547-1e653a00-661c-11eb-856a-b8619f0d5a80.png)

**I am getting following error as mentioned in below link**
[Github Issue](https://github.com/tensorflow/tensorflow/issues/41021)
![error_1](https://user-images.githubusercontent.com/65073329/106710888-ab0ff800-661c-11eb-97cf-6102280e8009.png)

**Comment by Saduf2019** [comment]
@shanmukh05 
Please share error log and info shared as screenshots in text format for us and any other user who faces problem it would be helpful.

**Comment by shanmukh05** [comment]
**Code (This is the main model. Details of dataset are in notebook I mentioned earlier)**

> I am using TPU

``` 
    IMAGE_SIZE = [300,300]
    import tensorflow as tf
    efficient_net = {
        0 : tf.keras.applications.EfficientNetB0(weights="imagenet",include_top=False ,input_shape=[*IMAGE_SIZE, 3]),
        1 : tf.keras.applications..EfficientNetB1(weights="imagenet",include_top=False ,input_shape=[*IMAGE_SIZE, 3]),
    }

    output = {}
    inputs = tf.keras.Input(shape=(*IMAGE_SIZE, 3))
    
    ls =   [0,1]      #[3,5,7]  

    for i in ls:
        pretrained_model = efficient_net[i]
        x = pretrained_model(inputs)
        x = tf.keras.layers.GlobalAveragePooling2D()(x)
        output[i] = tf.keras.layers.Dense(CLASSES,activation="sigmoid", dtype='float32')(x)
        
    outputs = tf.keras.layers.average(list(output.values()))
    model = tf.keras.Model(inputs, outputs)
    optimizer = tf.keras.optimizers.Adam(lr=lr)
    
    loss = tf.keras.losses.CategoricalCrossentropy()
        
    metrics = [
       tf.keras.metrics.CategoricalAccuracy(name='categorical_accuracy')
    ]

    model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
    cpk_path = './best_model.h5'
    
    checkpoint = tf.keras.callbacks.ModelCheckpoint(
        filepath=cpk_path,
        monitor='val_categorical_accuracy',
        mode='max',
        save_best_only=True,
        verbose=1,
    )

    reducelr = tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_categorical_accuracy',
        mode='max',
        factor=0.1,
        patience=3,
        verbose=0
    )

    earlystop = tf.keras.callbacks.EarlyStopping(
        monitor='val_categorical_accuracy',
        mode='max',
        patience=15, 
        verbose=1
    )
    
   callbacks = [checkpoint, reducelr, earlystop] 
   EPOCHS= 3
   VERBOSE =1

  STEPS_PER_EPOCH = NUM_TRAINING_IMAGES//(BATCH_SIZE)

  tf.keras.backend.clear_session()
  with strategy.scope():
    
  model = create_model()
  model = compile_model(model, lr=0.0001)
   
  callbacks = create_callbacks()
    
  history = model.fit(train_ds, 
                        epochs=EPOCHS,
                        callbacks=callbacks,
                        validation_data = valid_ds,
                        steps_per_epoch = STEPS_PER_EPOCH,
                        verbose=VERBOSE)
 ```


**Error Log**

  ```Downloading data from https://github.com/Callidior/keras-applications/releases/download/efficientnet/efficientnet-b0_weights_tf_dim_ordering_tf_kernels_autoaugment_notop.h5
16809984/16804768 [==============================] - 0s 0us/step
Downloading data from https://github.com/Callidior/keras-applications/releases/download/efficientnet/efficientnet-b1_weights_tf_dim_ordering_tf_kernels_autoaugment_notop.h5
27164672/27164032 [==============================] - 0s 0us/step
Epoch 1/3
146/146 [==============================] - 165s 387ms/step - loss: 1.1287 - categorical_accuracy: 0.6490 - val_loss: 0.5770 - val_categorical_accuracy: 0.8000

Epoch 00001: val_categorical_accuracy improved from -inf to 0.80000, saving model to ./best_model.h5
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-c8fdc0a8823e> in <module>
     17                         validation_data = valid_ds,
     18                         steps_per_epoch = STEPS_PER_EPOCH,
---> 19                         verbose=VERBOSE)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1143           epoch_logs.update(val_logs)
   1144 
-> 1145         callbacks.on_epoch_end(epoch, epoch_logs)
   1146         training_logs = epoch_logs
   1147         if self.stop_training:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    426     for callback in self.callbacks:
    427       if getattr(callback, '_supports_tf_logs', False):
--> 428         callback.on_epoch_end(epoch, logs)
    429       else:
    430         if numpy_logs is None:  # Only convert once.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
   1342     # pylint: disable=protected-access
   1343     if self.save_freq == 'epoch':
-> 1344       self._save_model(epoch=epoch, logs=logs)
   1345 
   1346   def _should_save_on_batch(self, batch):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in _save_model(self, epoch, logs)
   1394                     filepath, overwrite=True, options=self._options)
   1395               else:
-> 1396                 self.model.save(filepath, overwrite=True, options=self._options)
   1397             else:
   1398               if self.verbose > 0:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
   2000     # pylint: enable=line-too-long
   2001     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
-> 2002                     signatures, options, save_traces)
   2003 
   2004   def save_weights(self,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
    152           'or using `save_weights`.')
    153     hdf5_format.save_model_to_hdf5(
--> 154         model, filepath, overwrite, include_optimizer)
    155   else:
    156     saved_model_save.save(model, filepath, overwrite, include_optimizer,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
    129     if (include_optimizer and model.optimizer and
    130         not isinstance(model.optimizer, optimizer_v1.TFOptimizer)):
--> 131       save_optimizer_weights_to_hdf5_group(f, model.optimizer)
    132 
    133     f.flush()

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_optimizer_weights_to_hdf5_group(hdf5_group, optimizer)
    594     for name, val in zip(weight_names, weight_values):
    595       param_dset = weights_group.create_dataset(
--> 596           name, val.shape, dtype=val.dtype)
    597       if not val.shape:
    598         # scalar

/opt/conda/lib/python3.7/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)
    138             if name is not None:
--> 139                 self[name] = dset
    140             return dset
    141 

/opt/conda/lib/python3.7/site-packages/h5py/_hl/group.py in __setitem__(self, name, obj)
    371 
    372             if isinstance(obj, HLObject):
--> 373                 h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
    374 
    375             elif isinstance(obj, SoftLink):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.link()

RuntimeError: Unable to create link (name already exists)```

**Comment by AdityaKane2001** [comment]
@shanmukh05  This issue is mentioned on [StackOverflow](https://stackoverflow.com/questions/62169315/runtimeerror-unable-to-create-link-name-already-exists-keras).  This is occuring because you have 2 sets of layers of the same name, thus the model's weights cannot be saved:
Error is in the folowing line:

```
for i in ls:
        pretrained_model = efficient_net[i]
        x = pretrained_model(inputs)
        x = tf.keras.layers.GlobalAveragePooling2D()(x)
        output[i] = tf.keras.layers.Dense(CLASSES,activation="sigmoid", dtype='float32')(x)


#You can use the name parameter in layer function. It is best if you do them seperately and not in a for loop.
```

Hope this helps.

**Comment by shanmukh05** [comment]
> @shanmukh05 This issue is mentioned on [StackOverflow](https://stackoverflow.com/questions/62169315/runtimeerror-unable-to-create-link-name-already-exists-keras). This is occuring because you have 2 sets of layers of the same name, thus the model's weights cannot be saved:
> Error is in the folowing line:
> 
> ```
> for i in ls:
>         pretrained_model = efficient_net[i]
>         x = pretrained_model(inputs)
>         x = tf.keras.layers.GlobalAveragePooling2D()(x)
>         output[i] = tf.keras.layers.Dense(CLASSES,activation="sigmoid", dtype='float32')(x)
> 
> 
> #You can use the name parameter in layer function. It is best if you do them seperately and not in a for loop.
> ```
> 
> Hope this helps.

**I tried this, but getting the same error**
````for i in ls:
        j=0
        for layer in efficient_net[i].layers:
            layer._name = layer.name + "_"+str(i)
        j+=1``

**Comment by Saduf2019** [comment]
@shanmukh05 

When I tried reproducing your error, I face a different error, as shown below.

```NameError: name 'CLASSES' is not defined.```

Please find the [Gist](https://colab.research.google.com/gist/Saduf2019/4a6845af0b4cc53766af7d55cbdfe75e/untitled520.ipynb).

Also refer to these resolved issues with same error: #43011, #26835, [link](https://github.com/keras-team/keras/issues/6844), [link1](https://fantashit.com/runtimeerror-unable-to-create-link-name-already-exists-during-model-saving-with-modelcheckpoint/)

**Comment by shanmukh05** [comment]
> @shanmukh05
> 
> When I tried reproducing your error, I face a different error, as shown below.
> 
> `NameError: name 'CLASSES' is not defined.`
> 
> Please find the [Gist](https://colab.research.google.com/gist/Saduf2019/4a6845af0b4cc53766af7d55cbdfe75e/untitled520.ipynb).
> 
> Also refer to these resolved issues with same error: #43011, #26835, [link](https://github.com/keras-team/keras/issues/6844), [link1](https://fantashit.com/runtimeerror-unable-to-create-link-name-already-exists-during-model-saving-with-modelcheckpoint/)

The problem is that, both `Efficientnet0,EfficientNet1` have same layer names. I tried changing names as given [here](https://github.com/tensorflow/tensorflow/issues/46871#issuecomment-772425509), but I am getting same error. The error was not there in previous versions of tensorflow. I tried `tf-nightly` but no use. Can you suggest any alternative for changing names of  `layers`

**Comment by AdityaKane2001** [comment]
@shanmukh05 
Please take a look at [this](https://www.kaggle.com/adityakane/issue-46871-solution) notebook. I believe it is the solution.

**Comment by shanmukh05** [comment]
> @shanmukh05
> Please take a look at [this](https://www.kaggle.com/adityakane/issue-46871-solution) notebook. I believe it is the solution.

Nope, still facing the issue. I don't know why just renaming layers is not working.

**Comment by shanmukh05** [comment]
> @shanmukh05
> 
> When I tried reproducing your error, I face a different error, as shown below.
> 
> `NameError: name 'CLASSES' is not defined.`
> 
> Please find the [Gist](https://colab.research.google.com/gist/Saduf2019/4a6845af0b4cc53766af7d55cbdfe75e/untitled520.ipynb).
> 
> Also refer to these resolved issues with same error: #43011, #26835, [link](https://github.com/keras-team/keras/issues/6844), [link1](https://fantashit.com/runtimeerror-unable-to-create-link-name-already-exists-during-model-saving-with-modelcheckpoint/)

Try running this notebook: [Kaggle Notebook](https://www.kaggle.com/adityakane/issue-46871-solution)

**Comment by AdityaKane2001** [comment]
@shanmukh05 Using sav_weights_only is a workaround, and it works correctly, as demonstrated in [this](https://www.kaggle.com/adityakane/issue-46871-solution) notebook.

**Comment by AIGR-sw** [comment]
> **I tried this, but getting the same error**
> 
> ```
>         j=0
>         for layer in efficient_net[i].layers:
>             layer._name = layer.name + "_"+str(i)
>         j+=1``
> ```
@shanmukh05 
Try to rename the weights as follows:

 ```
for w in efficient_net[i].weights:
    w._handle_name = 'EP_' + str(i) + '_' + w.name
```

I know you shouldn't mess with underscore variables but it seems to work.

**Comment by shanmukh05** [comment]
> > **I tried this, but getting the same error**
> > ```
> >         j=0
> >         for layer in efficient_net[i].layers:
> >             layer._name = layer.name + "_"+str(i)
> >         j+=1``
> > ```
> 
> @shanmukh05
> Try to rename the weights as follows:
> 
> ```
> for w in efficient_net[i].weights:
>    w._handle_name = 'EP_' + str(i) + '_' + w.name
> ```
> 
> I know you shouldn't mess with underscore variables but it seems to work.

Thanks, that is working

**Comment by Saduf2019** [comment]
@shanmukh05

Please move this issue to closed status if resolved
