### ISSUE TITLE
Keras UpSampling2D layer is converted with a `shape` op that should be constant-folded away

### ISSUE THREAD

**Issue by AdamHillier** [tensorflow/tensorflow#46879]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.6
- TensorFlow installation (pip package or built from source): PyPI pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

```
import tensorflow as tf

m = tf.keras.models.Sequential(
    [
        tf.keras.layers.Input((32, 32, 3)),
        tf.keras.layers.Conv2D(32, (3, 3)),
        tf.keras.layers.UpSampling2D((2, 2), interpolation="nearest"),
    ]
)

converter = tf.lite.TFLiteConverter.from_keras_model(m)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
with open("tmp-model.tflite", "wb") as f:
    f.write(converter.convert())
```

### 3. Failure after conversion

The converted TFLite model looks like this:

![image](https://user-images.githubusercontent.com/7688302/106741589-cde9de80-6613-11eb-96c0-60dfd88c3d61.png)

Since the shape is statically known, I would expect the right-hand branch to be constant folded.

Possibly related to #25086.

**Comment by abattery** [comment]
Thanks for the suggestion! In the above case, it can be constant-foled away. We will take this as a feature request and update this thread when there is a progress regarding this optimization effort. We would welcome contributions for this performance improvement's opportunity from the community as well.

**Comment by karimnosseir** [comment]
The model has dynamic batch which disables constant folding.
Keras by default has dynamic batch size. 
See this [answer](https://github.com/tensorflow/tensorflow/issues/43882#issuecomment-731636562)

**Comment by karimnosseir** [comment]
For example changing this line in your model will make it constant and the ops will go away
```
tf.keras.layers.Input((32, 32, 3), batch_size=1),
```

**Comment by AdamHillier** [comment]
Fair enough, that does indeed work to enable constant folding. Thanks for your help :)

For this specific case, whether or not the batch size is static vs dynamic doesn't make any difference to whether or not the right-hand-side `shape`/`strided-slice` can be constant folded, because the shape is only being taken to get the spatial h/w info, which is static.

**Comment by karimnosseir** [comment]
@AdamHillier That's true. I think my reply confused multiple people, sorry about this.
 
What i meant here is that you don't need to wait for any changes/features to land. Once you fix the batch size this should go away as expected.

Thanks
