### ISSUE TITLE
Crash when Dense 2D without Bias on Android GPU Delegate

### ISSUE THREAD

**Issue by Robird** [tensorflow/tensorflow#46870]
**System information**
- Have I written custom code:Yes
- OS Platform and Distribution:Ubuntu 20.04 and Win10
- Mobile device: Huawei Honor V30 Pro (OXF-AN10)
- TensorFlow installed from: Pip
- TensorFlow version:2.4.1
- Python version:3.8
- CUDA/cuDNN version:11.0/8.0.5
- GPU model and memory:GTX 1080 ti

You can collect some of this information using our environment capture
v2.4.0-49-g85c8b2a817f 2.4.1

**Describe the current behavior**
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0

**Describe the expected behavior**
Work fine as run the model on mobile CPU

**Standalone code to reproduce the issue**

```
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf

x = layers.Input(shape=(256,64,3))
y = layers.Dense(1,use_bias=False)(x) #here use_bias=False is the key point
y = layers.GlobalMaxPool2D()(y)

model = keras.Model(inputs=[x],outputs=[y])
model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_input = model.inputs[0]
input_shape = model_input.shape
model_input.set_shape((1,*input_shape[1:]))

lite_model = converter.convert()
with open('issue_dense_2dMustBias_android_gpu.tflite', "wb") as fp:
    fp.write(lite_model)
```

[issue_dense_2dMustBias_android_gpu.zip](https://github.com/tensorflow/tensorflow/files/5916325/issue_dense_2dMustBias_android_gpu.zip)

**Comment by Robird** [comment]
TF Lite Android GPU Delegate problem

**Comment by srjoglekar246** [comment]
Hey @Robird to help resolve this quicker, could you provide some details on how you are using the delegate? Is it from the Java API? Also, could you try adb logcat & see if you see specific errors from TFLite?

**Comment by teijeong** [comment]
Used [benchmark tool](https://www.tensorflow.org/lite/performance/measurement) to run some inferences. Tested with Galaxy S10e (Exynos 9820) and Pixel 2 XL (SD 835). Works fine on both phones with GPU delegate.

It seems the problem is specific to the device you're testing, so it would great if you can provide more detailed logs. Thanks!

**Comment by sushreebarsa** [comment]
I tried to run the code in colab with  TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/dc15c71937ec21fc2f801095e6985071/untitled156.ipynb?authuser=1)..Thanks !

**Comment by impjdi** [comment]
TFLite CPU is able to reinterpret any tensor shape to any tensor shape as long as the number of elements match, TFLite GPU isn't; tensor shapes must be well formed.  If I look at your network, I see a couple of incompatibilities with the GPU backend:
* batch dimension must be preserved across the network, i.e. the input to the FC layer must be 1x16384x3.
* IIRC FC's weight tensor should have the form OHWI (1, 1, 16384, 3) and that's not the case, i.e. you're feeding (1, 1, 1, 3).
