### ISSUE TITLE
Tensorflow lite return zero in the third running time.

### ISSUE THREAD

**Issue by huyutao3550346** [tensorflow/tensorflow#46885]
hello everyone, I build a tensorflow lite 1.15.0(1.15.5) c++ lib for android.
In the first and second time, the  interpreter output is normal. but after it, interpreter return all zero.
I'm accept the camera video. 
![image](https://user-images.githubusercontent.com/29395068/106755884-9efe5780-6669-11eb-9274-25554774c53a.png)
![image](https://user-images.githubusercontent.com/29395068/106755895-a160b180-6669-11eb-8386-947e606e723f.png)
![image](https://user-images.githubusercontent.com/29395068/106755907-a45ba200-6669-11eb-8bd7-e3cf3667c5d6.png)

there is my code:
int init()
{
    std::unique_ptr<tflite::FlatBufferModel> model;
    model = tflite::FlatBufferModel::BuildFromBuffer(model_buffer,model_size);
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter_);
    if (interpreter_->AllocateTensors() != kTfLiteOk) {
        return -1;
    }
    else
    {
        input_ = interpreter_->inputs()[0];
        return 0;
    }
}

int detect(android_camera_frame)
{
               /*
                  process image
             */
             memcpy(interpreter_->typed_tensor<float>(input_),detect_mat.data,256 * 256 * 3 * sizeof(float));
            TfLiteTensor *predict_tensor = interpreter_->tensor(interpreter_->outputs()[0]);
            float *detect_out_data = predict_tensor->data.f;

            for(int i = 0; i<20;i++)
            {
                printf("detect_out_data(%d):%f\n",i,detect_out_data[i]);
            }
}

**init** is a initialization function,only run once. and the frame of android camera is process by **detect** always.
In the result only first and second return is true;after that, result is all zero or nan....

there is my compile option:
bazel build //tensorflow/lite:libtensorflowlite.so --crosstool_top=//external:android/crosstool --cpu=arm64-v8a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"

tensorflow vision is 1.15.0 and 1.15.5

**Comment by abattery** [comment]
TF 1.15 is too old TF version to get supported. We encourage you to use TensorFlow Lite 2.4 or the tf-nightly version for this.  Could you try your code with the recent TensorFlow version?

**Comment by huyutao3550346** [comment]
@abattery 
thank you. I have compiled lite in tensorflow2.4 and tensorflow2-master today.
but get another issue;
when I link lite lib in my project. but get:
CMakeFiles/xinyan_homework.dir/src/xinyan_homework_detect.cpp.o: In function `xinyan_homework::CXinYanHomeworkDetect::init(char const*, int)':
/Users/admin/Desktop/work/AliveFaceDetc/xinyan_homework/native/src/xinyan_homework_detect.cpp:48: undefined reference to `tflite::InterpreterBuilder::operator()(std::unique_ptr<tflite::Interpreter, std::default_delete<tflite::Interpreter> >*)'

this is my code:
    std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromBuffer(model_buffer,model_size);
    
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder builder(*model, resolver);
    
    **builder(&interpreter_);** //this code is wrong
    if (interpreter_->AllocateTensors() != kTfLiteOk) {
        return XINYAN_HOMEWORK_ERROR_NULL;
    }
    else
    {
        input_ = interpreter_->inputs()[0];
        return XINYAN_HOMEWORK_SUCCESS;
    }

when I delete error code. complie is success.

my NDK version is 18.1.5063045 NDK_API_LEVEL is 21. 
and my build command is bazel build --config=android --cpu=arm64-v8a //tensorflow/lite:libtensorflowlite.so --crosstool_top=//external:android/crosstool  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11"

**Comment by teijeong** [comment]
Hi @abattery, can you comment?

**Comment by abattery** [comment]
Adding @terryheo for building issues.

**Comment by terryheo** [comment]
You'd better build it with "--config=android_arm64"

Also if you're using CMake for your project, you can integrate it with TFLite directly.
https://www.tensorflow.org/lite/guide/build_cmake
