### ISSUE TITLE
Unable to evaluate dense tensor obtained from sparse complex tensor

### ISSUE THREAD

**Issue by amrit-poudel** [tensorflow/tensorflow#4688]
I am unable to evaluate/print/run  a dense tensor which is obtained from a complex sparse tensor.

a = tf.SparseTensor(indices=[[0, 0, 0], [1, 2, 1]], values=[1.0+2j, 2.0], shape=[3, 4, 2])

b = tf.sparse_tensor_to_dense(a, default_value=0.0)

sess  = tf.Session()

sess.run(b)

returns the following error:

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'SparseToDense' with these attrs.  Registered kernels:
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT64]

```
 [[Node: SparseToDense_3 = SparseToDense[T=DT_COMPLEX128, Tindices=DT_INT64, validate_indices=true](SparseTensor_2/indices, SparseTensor_2/shape, SparseTensor_2/values, SparseToDense_3/default_value)]]
```

I also tried 

br = tf.real(b)

sess.run(br)

However, this gives the same error as above.

Note, however, that following works fine:

x = tf.ones((3,3), dtype=tf.complex128)

sess.run(x)

I am currently using tensorflow v 0.10.0 on macosx (cpu only).

I am not sure why I am unable to evaluate complex tensor obtained from sparse_tensor_to_dense operator operation.

**Comment by tatatodd** [comment]
@amrit-poudel Thanks for the clear description of the problem!

The error message indicates that `sparse_tensor_to_dense` doesn't support complex values yet; we simply haven't implemented it.  Calling sess.run on a complex dense tensor works, since it doesn't involve `sparse_tensor_to_dense`.

@concretevitamin might know whether we have any plans to add support for complex values to `sparse_tensor_to_dense`.

**Comment by concretevitamin** [comment]
I am not aware of any plan at the moment.  CC-ing @ebrevdo.  Contributions welcome though!

**Comment by ebrevdo** [comment]
We'll soon have a scatter_nd op which should subsume this behavior and work with the data type. At that point we'll probably point sparse to dense to use that kernel.

**Comment by amrit-poudel** [comment]
Many thanks!

**Comment by tatatodd** [comment]
Cool, I'll assign myself and update this issue when `scatter_nd` is in.

**Comment by amrit-poudel** [comment]
Has there been any progress on this yet? How long do you think this might take? Thanks for the effort.

**Comment by tatatodd** [comment]
I don't see a `ScatterNd` op yet.  Re-assigning to @ebrevdo to update this when available.

**Comment by amrit-poudel** [comment]
Is there a quick fix to this without using ScatterNd? For instance, if the sparse tensor is complex, one could split into real and imaginary parts (not sure if this is available for a sparse tensor) and then call sparse_tensor_to_dense?

**Comment by ebrevdo** [comment]
Yes; that will work.  You will have to create two SparseTensors: one taking
the real values and one taking the imaginary values (the indices and shape
tensors can be the same).

**Comment by amrit-poudel** [comment]
Actually, I meant taking a real and imaginary parts of a complex sparse tensor and then performing sparse_tensor_to_dense operation on real and imaginary part separately.  It appears to me that taking real and imaginary parts of a complex sparse tensor is not possible.

**Comment by Timeroot** [comment]
Are there any plans to add this op?
