### ISSUE TITLE
No UInt8 support for logistic operator in TFLu

### ISSUE THREAD

**Issue by alisonwh** [tensorflow/tensorflow#46882]
@tensorflow/micro

**Describe the problem**
I am working on running object detection demo with TFLu + ssd mobilenet v1 quantized model on i.mx8mp's Cortex-M7 core. The input tensor and output tensor's type for logistic operator is UInt8. But there is no UInt8 support in current code.

I create the following patch to fix the problem. Please give me some advice.
https://github.com/tensorflow/tensorflow/pull/46873

**Comment by furknclk** [comment]
Hi man. I am working on the same project. Can you share your experience with me ? I dont know where should i start.

**Comment by alisonwh** [comment]
@furknclk There are some examples for TFLu in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples. You can try them first.

**Comment by alisonwh** [comment]
@furknclk I have solved the problem. This is my patch https://github.com/tensorflow/tensorflow/pull/46873/commits. It has not been merged yet. Anyway, you can try it.

**Comment by sanatmpa1** [comment]
@alisonwh,

I can see from this [PR](https://github.com/tensorflow/tensorflow/pull/46873/commits) that it is not merged and was awaiting your response, As you mentioned in previous comment that its solved, Can you confirm if we are good to close the issue? Thanks!
