### ISSUE TITLE
Custom "Best" Metric Not Tracking Best Accuracy

### ISSUE THREAD

**Issue by ghwatson** [tensorflow/tensorflow#46896]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
-- custom code in which the bug manifests, but test code is slightly edited stock example code from Tensorflow docs.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
-- MacOS and Linux
- TensorFlow installed from (source or binary):
-- via pip
- TensorFlow version (use command below):
-- 2.4.0
- Python version:
-- 3.8.2

**Describe the current behavior**

I've created a custom metric which tracks the max achieved result of a metric during a training run (so for example it should reflect the best model's accuracy seen so far at any given point in time). When I apply this to the simple MNIST code from the docs where the accuracy continuously moves up at the epoch level, this custom metric does not exactly match the raw accuracy (though it roughly tracks with it).

**Describe the expected behavior**

The expected behaviour in this case would be for the custom metric to exactly match the accuracy since the accuracy improves monotonically at the epoch level. It seems like it's a bug that it does not. However, I admit that it could be a hole in my understanding of Tensorflow! Perhaps there's some kind of off-by-one error here in how I'm interpreting the metric's state maybe?

Another comment which may or may not be related: In working with multiple class instances of tensorflow metric objects in jupyter notebooks, I noticed that sometimes I had to be very liberal with my usage of reset_state even though I had separate class instances of the same metric. This makes me expect that at the root of both this and the bug I outline in this issue, that there's some kind of unintentionally shared state between multiple instances of the same metric class. If I can reproduce this someday again, I'll post in separate issue. I just wanted to include full context in case this provides clues that tie to other posted issues in tf's github repo.

**Standalone code to reproduce the issue**

reproducible in this collab notebook: https://colab.research.google.com/drive/1hBcLce9VWynZgTAbzhWzEfdO3VZq4-0W?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4,nightly version(`2.5.0-dev20210203`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/938d0fd01de962220cd1f48710b26b72/untitled654.ipynb). Thanks!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by ghwatson** [comment]
@ymodak it appears to be a bug to me. I could definitely be misunderstanding something which might make it not a bug, However, TF2 has had many corner case bugs so I wouldn't be surprised if it is a bug.
