### ISSUE TITLE
`tf.random.fixed_unigram_candidate_sampler` crashes(abort) when `vocab_file` is invalid

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46898]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.random.fixed_unigram_candidate_sampler` crashes(abort) when `vocab_file` is invalid

**Describe the expected behavior**
expect an exception message if the file format is incorrect instead of crash

**Standalone code to reproduce the issue**
~~~python
tf.random.fixed_unigram_candidate_sampler(true_classes=np.ones((1,1)), num_true=1, num_sampled=1, unique=True, range_max=1, vocab_file='abc')
~~~
Output:
~~~python
2021-02-03 22:08:02.817419: F tensorflow/core/kernels/range_sampler.cc:246] Non-OK-status: LoadFromFile(env, vocab_file, distortion) status: Not found: abc; No such file or directory
Aborted (core dumped)
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b506631d184ce832dc87a808c71841d5/46898.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210528 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/6607926a89e0d69ab2a5223df6dd18cf/untitled39.ipynb#scrollTo=8D_c_j0gqQ0U)...Thanks !

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220719. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0c0d9a98f3652d8d31652430f5501d4e/untitled39.ipynb). Thank you!
