### ISSUE TITLE
Cannot Compile TF-Nightly with CUDA 11.2 and CUDNN 8.1

### ISSUE THREAD

**Issue by ayakashi-ml** [tensorflow/tensorflow#46902]
**System information**
- Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: tf-nightly
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: Built using instructions [here](https://www.tensorflow.org/install/source_windows)
- Bazel version (if compiling from source): Bazel 3.7.2
- GCC/Compiler version (if compiling from source): MSVC 14.28.29333
- CUDA/cuDNN version: 11.2 / 8.1
- GPU model and memory: Geforce RTX 3090 24GB

When trying to build TF-nightly with CUDA 11.2 and CUDNN 8.1, this error occurs:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C2039: 'copysign': is not a member of ''global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\complex(354): error C3861: 'copysign': identifier not found
`

This causes the build to fail.

Steps to reproduce:
1) Uninstall all global CUDA instances.
2) Install CUDA 11.2
3) Install CUDNN 8.1 by dragging the files into the install directory of CUDA
4) Git clone tensorflow
5) Checkout tf-nightly branch
6) Set up Bazel, following [this](https://docs.bazel.build/versions/master/windows.html#build-c) guide (suggested by documentation)
7) Follow the rest of the guide [here](https://www.tensorflow.org/install/source_windows).
8) Execute bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
9) Receive the error.

Traceback is attached.
[log.txt](https://github.com/tensorflow/tensorflow/files/5922256/log.txt)

**Comment by amahendrakar** [comment]
@ayakashi-ml,
Could you please try building TensorFlow with **CUDA 11.0** and **cuDNN 8** and let us know if you are facing the same error. 

Also, please take a look at similar issues [#44682](https://github.com/tensorflow/tensorflow/issues/44682#issuecomment-732283634) and [#43588](https://github.com/tensorflow/tensorflow/issues/43588#issuecomment-699592351) and check if it helps. Thanks!

**Comment by mwilkinsonjr** [comment]
For what it's worth I ran into this exact same error on Windows with CUDA 11.2 and "cuDNN v8.1.0 (January 26th, 2021), for CUDA 11.0,11.1 and 11.2" and found that switching from branch "master" to "r2.4" lead to a working build and setup (also using the numpy 1.20.x branch) for CUDA 11.2.  

I suspect the problem here is maybe with MSVC - the VisualStudio\2019\Community\VC\Tools\MSVC\14.28.29333\include\complex header file appears to have a Ctraits double sized tensor copysign definition in it that is missing (more likely a typo) from the associated library.

**Comment by mihaimaruseac** [comment]
The issue is MSVC. https://www.gitmemory.com/issue/OpenImageIO/oiio/2799/752372181

**Comment by bhack** [comment]
https://github.com/microsoft/vcpkg/issues/15369
