### ISSUE TITLE
tf.summary.create_file_writer aborts 

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46909]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.summary.create_file_writer` crash (abort)

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.summary.create_file_writer(logdir='', flush_millis=np.ones((1,2)))
~~~

Output:
~~~python
2021-02-04 03:59:32.339427: F tensorflow/core/framework/tensor.cc:669] Check failed: 1 == NumElements() (1 vs. 2)Must have a one element tensor
Aborted (core dumped)
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.1,2.4,nightly versions(`2.5.0-dev20210203`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9329366f22f1d5559d31065583e6f21e/untitled656.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Colab is still crashing in TF 2.6 when I executed the code. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/4d07531868b085424317d42652909927/untitled92.ipynb#scrollTo=RvUKM453ViFa).Thanks!
