### ISSUE TITLE
tf.strings.substr crashes(aborts) 

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46900]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.strings.substr` crashes(aborts)  when `len(pos)` > `len(input)`

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
tf.strings.substr(input='abc', len=1, pos=[1,-1])
~~~

~~~python
import tensorflow as tf
tf.strings.substr(input='abc', len=1, pos=[1,2])
~~~

Output:
~~~python
2021-02-03 22:46:41.234297: F ./tensorflow/core/framework/tensor.h:806] Check failed: new_num_elements == NumElements() (2 vs. 1)
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment]
@rmothukuru 
I ran the code shared on tf 2.4 and nightly, colab crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e258b6a130140d89c1fd3325317982bc/untitled520.ipynb).

**Comment by yongtang** [comment]
According to documentation https://www.tensorflow.org/api_docs/python/tf/strings/substr an error should be thrown out gracefully (instead of a crash). Added a PR #46974 for the fix.
