### ISSUE TITLE
libtensorflowlite_flex_jni.so not found when using tensorflow-lite.aar

### ISSUE THREAD

**Issue by dpmcgonigle** [tensorflow/tensorflow#46905]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Yes, I have overwritten the tensorflow lite Transpose method to accept tensors larger than 4D

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- macOS Catalina 10.15.7

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- Running an emulator in AndroidStudio 4.1.2, Pixel_3a_API_30_x86

- TensorFlow installed from (source or binary):
- Source

- TensorFlow version (use command below):  2.5.0 master branch HEAD (2/3/2021, commit 54bcf2919f7824995835726630064c383eb47149)
- with modified tensorflow/lite/kernels/transpose.cc, and registering function in tensorflow/lite/kernels/register.cc and builtin_op_kernels.h)
- Python version:3.7.5
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.3 (clang-1103.0.32.29)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I used that tensorflow code (with my custom transpose operation) to convert a pb file of the Glow model into a tflite file using the Python API.  I tested the model out in Python, and was able to load/invoke it just fine.

I built the tensorflow-lite.aar and tensorflow-lite-select-tf-ops.aar files with the current version of tensorflow (commands used to build below).  I try loading the model in Android using Java, and the Interpreter() constructor throws the following error:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tflite_java, PID: 4451
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libtensorflowlite_flex_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.tensorflow.lite.flex.FlexDelegate.<clinit>(FlexDelegate.java:61)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at org.tensorflow.lite.NativeInterpreterWrapper.maybeCreateFlexDelegate(NativeInterpreterWrapper.java:511)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:476)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:88)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:287)
        at com.example.tflite_java.MainActivity.loadModel(MainActivity.java:79)
        at com.example.tflite_java.MainActivity.onCreate(MainActivity.java:115)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 4451 SIG: 9

**Describe the expected behavior**
I expected to be able to load and utilize the model, not this error: java.lang.UnsatisfiedLinkError: dlopen failed: library "libtensorflowlite_flex_jni.so" not found

**Standalone code to reproduce the issue**
===========MainActivity.java=============
package com.example.tflite_java;

import android.content.res.AssetFileDescriptor;
import android.content.res.AssetManager;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import org.tensorflow.lite.Interpreter;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;

public class MainActivity extends AppCompatActivity {
    // Load tflite model from assets.
    public MappedByteBuffer loadModelFile(String modelPath) throws IOException, IOException {
        try (AssetFileDescriptor fileDescriptor = getAssets().openFd(modelPath);
            FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor())) {
            FileChannel fileChannel = inputStream.getChannel();
            long startOffset = fileDescriptor.getStartOffset();
            long declaredLength = fileDescriptor.getDeclaredLength();
            return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
        }
    }

    // Load the tflite model
    public Interpreter loadModel(String modelFile) {
        Interpreter tflite;
        try {
            System.out.println("Loading model from file " + modelFile);
            ByteBuffer buffer = loadModelFile(modelFile);
            Interpreter.Options opt = new Interpreter.Options();
            opt.setNumThreads(1);
            tflite = new Interpreter(buffer, opt);
        } catch (IOException ex) {
            tflite = null;
            System.out.println(ex.getMessage());
        }
        return tflite;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Interpreter interpreter = loadModel("waterfall_glow_20210203_tfnightly.tflite");
    }
}

**Other info / logs** 
Android ndk version android-ndk-r18b-darwin-x86_64.zip
Android sdk version 30.0.3
Build commands for tensorflow-lite and tensorflow-lite-select-tf-ops
bazel build --cxxopt='--std=c++14' -c opt --config=android_arm --config=monolithic //tensorflow/lite/java:tensorflow-lite-select-tf-ops
bazel build --cxxopt='--std=c++11' -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a //tensorflow/lite/java:tensorflow-lite

**Comment by abattery** [comment]
You need to depend on tensorflow-lite-select-tf-ops.aar for importing libtensorflowlite_flex_jni.so.

**Comment by dpmcgonigle** [comment]
Thank you for the quick response!

I have the following in my app/build.gradle:
    implementation project(':tensorflow-lite')
    implementation project(':tensorflow-lite-support-0.1.0')
    implementation project(':tensorflow-lite-select-tf-ops')

Additionally, I added all three modules to AndroidStudio via "New" -> "New Module" -> "JAR/AAR".

**Comment by teijeong** [comment]
Hi @dpmcgonigle, is your issue resolved? If so, please close this :)

**Comment by dpmcgonigle** [comment]
Hello @teijeong, my issue is not resolved.  @abattery suggested I need to "depend on tensorflow-lite-select-tf-ops.aar for importing libtensorflowlite_flex_jni.so".  I pointed out in my last post that I am including this as a dependency.  Thank you!

Sincerely,
Dan McGonigle

**Comment by abattery** [comment]
@thaink could you take a look at this?

**Comment by thaink** [comment]
@dpmcgonigle  I think the problem here is you only build tensorflow-lite-select-tf-ops.aar for arm:
`bazel build --cxxopt='--std=c++14' -c opt --config=android_arm --config=monolithic //tensorflow/lite/java:tensorflow-lite-select-tf-ops`
but might be you are trying to run it on emulator, which is x86.

**Comment by dpmcgonigle** [comment]
Thank you very much for getting back to me!  That looks to be the problem.  Thank you very much for helping me out!

**Comment by sanyakuznezov** [comment]
Hello everyone, I need help. When trying to run the sound classification model on android 4.4.2, there is a problem:
E/dalvikvm: dlopen("/data/app-lib/com.ashomok.sleepbaby-2/libtensorflowlite_flex_jni.so") failed: dlopen failed: cannot locate symbol "fegetround" referenced by "libtensorflowlite_flex_jni.so"...

on android 10, this problem does not arise, the application starts

**Comment by abattery** [comment]
@sanyakuznezov could you upload new issue? This issue has been closed and we would keep each issue to be focused.

**Comment by sanyakuznezov** [comment]
ok
