### ISSUE TITLE
Tokenizer doesn't work with string tensors (AttributeError)

### ISSUE THREAD

**Issue by princyok** [tensorflow/tensorflow#46907]
**System information**
- OS Platform: Windows 10
- TensorFlow version: 2.3.2
- Python version: 3.8.5
- CUDA version: 10.1.243

**Issue**
Tokenizer doesn't work with tensors (at least string tensors).

**Standalone code to reproduce**

Fails with a string tensor:

````
a = ['hello world', 'what is your name', 'start with a scene']

t = tf.constant(a, dtype=tf.string)
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(t)
````
Throws this error:

````
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'lower'
````

Works fine with a regular python list:

````
a = ['hello world', 'what is your name', 'start with a scene']

tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(a)
````

**Comment by Saduf2019** [comment]
@princyok 
Sorry for the delayed response, can you please refer to this [link](https://keras.io/) which has it explained in detail.
Also similar resolved issues: [link](https://github.com/tensorflow/tensorflow/issues/26922),[link1](https://github.com/tensorflow/tensorflow/issues/29972)

**Comment by princyok** [comment]
@Saduf2019 
Thanks. I've gone through the links, although I'm not sure if the first link to keras.io was a mistake. 

None of those links seem to address the key issue here: Why the `Tokenizer` class has no support for tensors or even numpy arrays. It's strictly list of strings (even the documentation clearly spells this out), but why should this be the case? The TextVectorization layer (also keras API) supports tensors, so does the various classes in text_tensorflow.

But I guess it is simply what it is.

**Comment by Saduf2019** [comment]
i am able to replicate the issue reported on f 2.3 and 2.4, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5304494b257b2262257522966d779a7d/untitled524.ipynb)

**Comment by jvishnuvardhan** [comment]
@princyok Input Argument text sequence can be `can be a list of strings, a generator of strings (for memory-efficiency), or a list of list of strings.`  So, after changing one line in your code (`# t = tf.constant(a, dtype=tf.string)`), everything worked as expected.

 [Here](https://colab.research.google.com/gist/jvishnuvardhan/8e6459701bedb03e56a02a6f919453ba/untitled524.ipynb) is a gist for reference. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by around-star** [comment]
@jvishnuvardhan , thats what @princyok tried to point out in the issue. The code works well with strings as you mentioned but throws in the error when using a tensor. I think this needs to be fixed. Please revert back if you would like a fix for this issue.

**Comment by princyok** [comment]
@jvishnuvardhan I already addressed your in my other comment above. What you are pointing out is the problem itself.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/4d65eacbe55981f7ceaa1df965c35fe0/untitled36.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
@princyok tf.keras.preprocessing.text.Tokenizer will be deprecated in future version since it does not operate on Tensors, and is most unlikely to get any update.
We recommend you to use tf.keras.layers.TextVectorization which has similar functionality which operate on Tensors.
For details see [here](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer?version=nightly). Thanks!

**Comment by sachinprasadhs** [comment]
I'm able to Tokenize string data by using TextVectorization.
Below is the code reference.
```
import tensorflow as tf
from tensorflow.keras import layers
data = ['hello world', 'what is your name', 'start with a scene']

layer = layers.TextVectorization()
layer.adapt(data)
vectorized_text = layer(data)
print(vectorized_text)
```

```
tf.Tensor(
[[10  3  0  0]
 [ 5  9  2  8]
 [ 6  4 11  7]], shape=(3, 4), dtype=int64)
```
