### ISSUE TITLE
In tf.keras, can i use model(x).numpy() with disable_eager_execution()?

### ISSUE THREAD

**Issue by stevenheleah** [tensorflow/tensorflow#46919]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

- Python version: 3.7
- TensorFlow version (use command below):2.2

**Describe the current behavior**
As is known to us, for predicting, there are two options to use the model. I can call `model.predict(x)` or I can call `model(x).numpy()`. `model(x)` is faster than `model.predict(x)`  for small amount of inputs in eager mode. Since i want to  deploy the model in production environment，i should disable the eager mode with `tf.compat.v1.disable_eager_execution()`.For better performance，i want to use `model(x).numpy()` to predict instead of  `model.predict(x)` for small amount of inputs ,but i found that i can't convert tensor to numpy with  `tf.compat.v1.disable_eager_execution()`
**Describe the expected behavior**
is there any solutions to use `model(x).numpy()` with `tf.compat.v1.disable_eager_execution()` for faster prediction

**Comment by qlzh727** [comment]
You shouldn't use disable_eager_execution() in the first place.

1. model(x) is faster for single example inference, whereas model.predict(x) is better for bulk/batch example inference.
2. model(x).numpy() is only working in eager mode. numpy() is a method for eager tensor, which is not available when eager execution is disabled.
3. the performance between eager mode and graph mode should be similar, and please report performance issue if you see any.
