### ISSUE TITLE
tf.keras.layers.RepeatVector crashes(aborts) when n is large

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46913]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.layers.RepeatVector` crashes(aborts) when `n` is large

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.layers.RepeatVector(n=9223372036854775807)(np.ones((3, 1)))
~~~

Output:
~~~python
2021-02-04 04:42:07.262027: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment]
@rmothukuru 
I ran the code shared on tf 2.4 and nightly, colab crashes. Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a19ece73799cb1d602387e840fe98574/untitled520.ipynb).

**Comment by DNXie** [comment]
BTW it also throws segfault
~~~python
tf.keras.layers.RepeatVector(n=9223372036854775807)(np.ones((3, 1)))

**Comment by DNXie** [comment]
BTW, tf.keras.layers.RepeatVector thorws segmentation fault when data is empty:
~~~python
import tensorflow as tf
import numpy as np
tf.keras.layers.RepeatVector(n=9223372036854775807)(np.ones((0,0)))
~~~

Output:
~~~python
Segmentation fault (core dumped)
~~~

**Comment by saikumarchalla** [comment]
Colab crashes in TF 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/4ef0fe758f11af629a9485dbfaa17e17/untitled93.ipynb).

**Comment by yongtang** [comment]
Added a PR #51359 for the fix.
