### ISSUE TITLE
window10 make file error

### ISSUE THREAD

**Issue by SunBeenMoon** [tensorflow/tensorflow#46916]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): window10
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.4.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): heimax we1

**Describe the problem**
Hello, I have problem build makefile in window10
I've download the migw to use "make".

in Powershell

```
PS C:\tensorflow> make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
process_begin: CreateProcess(NULL, uname -m, ...) failed.
-m은(는) 예상되지 않았습니다.
'tr'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
FIND: 매개 변수 형식이 틀립니다.
FIND: 매개 변수 형식이 틀립니다.
명령 구문이 올바르지 않습니다.
process_begin: CreateProcess(NULL, bash C:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:521: *** Something went wrong with the flatbuffers download: .  멈춤.

```

```
PS C:\tensorflow> make -f tensorflow/lite/micro/tools/make/Makefile TARGET=himax_we1_evb third_party_downloads
process_begin: CreateProcess(NULL, uname -m, ...) failed.
-m은(는) 예상되지 않았습니다.
'tr'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
FIND: 매개 변수 형식이 틀립니다.
FIND: 매개 변수 형식이 틀립니다.
명령 구문이 올바르지 않습니다.
process_begin: CreateProcess(NULL, bash C:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:521: *** Something went wrong with the flatbuffers download: .  멈춤.
```

I can't find the reason of this problem. I guess I have to change environment setting

**Comment by Saduf2019** [comment]
@SunBeenMoon 
Can you please refer to similar issues and let us know, #45033, #42765, #42476

**Comment by SunBeenMoon** [comment]
Thank you for response my issue.

I've checked all three of issues, but none of them was fit my error. 

I've check my gcc and make version
```
PS C:\tensorflow> gcc -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registrThread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
PS C:\tensorflow> make -v
GNU Make 3.82
Built for i386-pc-mingw32
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

Still I can't find the reason of this make file problem ..

**Comment by SunBeenMoon** [comment]
So, I've have question 2 of it. 

1. Is this a problem because the Makefile version is lower than 4.1?
2. Another micro issue says that the latest tensorflow has a build problem. Is that the cause? The haimax-we1 I want to use is only in the latest tensorflow.

**Comment by SunBeenMoon** [comment]
Actually I solved some of the problem.
but not sure this solution is perfect

first of all, can't download or build in window system(cmd or powershell) you have to build in linux environment.

It is not perfect but i've solved it(I can't find a way to build in window environment). 

so I'll close this issue.
