### ISSUE TITLE
Model is working fine in CPU but in GPU it consumes all RAM. 

### ISSUE THREAD

**Issue by Engineer1999** [tensorflow/tensorflow#46918]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code:- Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.0
- GPU model and memory: Tesla K4, RAM=15GB

**Current behavior**
I am trying to run face identification using the face_identification library based on dlib and object detection using the mobilenet_ssd model. Both of them combined working fine in CPU on local machine and on AWS CPU but when we use GPU, RAM is used completely. The issue is with the object detection model. Before loading the model it uses 300MB RAM, but when it loads the pre-trained model, RAM is suddenly jumped to 15GB. Both models are working fine in the CPU. 

**Expected behavior**
It should run on GPU without RAM overflow.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info/logs** 
Traceback (most recent call last):
  File "StreamingService.py", line 252, in <module>
    streamingService.start()
  File "StreamingService.py", line 104, in start
    verification_service.verify(studentExamId, studentId, verificationCode)
  File "/home/ubuntu/screening-service-test/screening-service/computerVision/VerificationService.py", line 84, in verify
    studentFaceEncoding  = self.getFaceEncoding(studentPicDict[key])
  File "/home/ubuntu/screening-service-test/screening-service/computerVision/VerificationService.py", line 20, in getFaceEncoding
    face_locations = face_recognition.face_locations(rgb_small_frame, model = "cnn")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/face_recognition/api.py", line 119, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/face_recognition/api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudnnFindConvolutionForwardAlgorithm( context(), descriptor(data), (const cudnnFilterDescriptor_t)filter_handle, (const cudnnConvolutionDescriptor_t)conv_handle, descriptor(dest_desc), num_possible_algorithms, &num_algorithms, perf_results.data()) in file /home/ubuntu/dlib/dlib/cuda/cudnn_dlibapi.cpp:820. code: 2, reason: CUDA Resources could not be allocated.

**Comment by ravikyram** [comment]
@Engineer1999 
 
Can you please share complete code and error log.It helps us in debugging further.
Try to limit GPU memory using this [link](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and see if it helps you.Thanks!
