### ISSUE TITLE
tf.keras.backend.tile crash(aborts) when n is large

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46911]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.backend.tile` crash(aborts) when `n` is large

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.backend.tile(x=np.ones((1,1,1)), n=[100000000,100000000, 100000000])
~~~
Output
~~~python
2021-02-04 04:10:34.072054: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c767ecbb5d79e0cfdda8bebb6fa4582e/46911.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Colab crashes in TF 2.6 as well.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/b6bdaeacb30114dcac93f2325c54dfd2/copy-of-untitled92.ipynb).Thanks!

**Comment by yongtang** [comment]
Added PR #51138 for the fix.
