### ISSUE TITLE
`tf.sparse.eye` crashes(aborts) when num_rows contains large number

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46912]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.sparse.eye` crashes(aborts) when `num_rows` contains large number

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.sparse.eye(num_rows=9223372036854775807, num_columns=None)
~~~

Output
~~~python
2021-02-04 04:36:57.184236: F tensorflow/core/framework/tensor_shape.cc:345] Check failed: size >= 0 (-9223372036854775808 vs. 0)
Aborted (core dumped)
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.1, 2.4, nightly versions (`2.5.0-dev20210203`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d19e64c4c9dc491d53fa38368e84eea6/untitled657.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue using TF 2.6 Nightly version and the colab crashes. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/ac52112902392e4498f05c15cefbe074/untitled92.ipynb).

**Comment by yongtang** [comment]
With PR #51359 merged, this is issue is fixed now. I will close this issue but feel free to reopen if the issue persist.
