### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: TensorArrayV3.Node number 3 (TensorArrayV3) failed to prepare.

### ISSUE THREAD

**Issue by najme22** [tensorflow/tensorflow#46924]
I'm not so professional in python! I'm trying to convert frozen graph to tflite file in colab to start inference it using jetson nano. I get this error! 

converter.allow_custom_ops = True
converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
open('tflite_file', 'wb').write(tflite_model)

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

**Comment by ravikyram** [comment]
@najme22 

Can you please fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by teijeong** [comment]
Hi,

Seems you need to convert your model with select TF ops https://www.tensorflow.org/lite/guide/ops_select
