### ISSUE TITLE
PPO implementation does not converge

### ISSUE THREAD

**Issue by emadboctorx** [tensorflow/tensorflow#46927]
I'm not sure whether the problem is implementation / tensorflow specific. Following this [repo](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail) as a reference, I re-implemented the same thing over and over for like 5 times in different ways. Every single time, I end up with the same results, despite the code is almost identical to the pytorch implementation. Here's a colab [notebook](https://colab.research.google.com/drive/1rvCYd9xJDQNAutpAHUBYc42ElHCXWNNd?usp=sharing) containing the full code. If anyone can help me fix the issue, I'd really be very grateful.

**Comment by emadboctorx** [comment]
I fixed the issue by lowering lr

**Comment by ravikyram** [comment]
@emadboctorx 

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by emadboctorx** [comment]
I know, thanks anyway and I did ask on SO already.
