### ISSUE TITLE
tf.abs() crashes when dtype=float32

### ISSUE THREAD

**Issue by jessyprociv** [tensorflow/tensorflow#46920]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 20H2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): using pip inside conda
- TensorFlow version (use command below): 2.5.0-dev20210203
- Python version: 3.8.5
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 11.0 / 8
- GPU model and memory: RTX 1070 8GB

**Describe the current behavior**
tf.abs() works fine when provided with integer values but crashes when dtype=float32.
If run in Jupyter the cell will hang and never execute. If run in Anaconda prompt python will crash and kick you back out to conda.

**Describe the expected behavior**
Return absolute value

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.constant([-2.25, 3.25])
tf.abs(x)
```

**Comment by amahendrakar** [comment]
@jessyprociv,
I was able to run the code without any issues on [TF v2.4](https://colab.research.google.com/gist/amahendrakar/6814282816d3d7430ba9bb6714c8b49b/46920.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/a1e2e3ec2fc182e9e1af317e1a628d3f/46920-tf-nightly.ipynb). Please check the linked gist for reference. 

Could you please run the code in new virtual environment and check if you are facing the same issue? Thanks!

**Comment by jessyprociv** [comment]
Hi @amahendrakar 

I created a new environment and am unfortunately still having the same issue. Of course it might still just be an issue with my computer so am happy for this issue to be closed if it doesn't seem like a legitimate bug.

New environment created using the following commands in conda:
```
conda create -n new-tf python=3.8
conda activate new-tf
pip install tf-nightly-gpu==2.5.0.dev20210203
conda install cudatoolkit=11.0
```

Then inside python once again running:
```
import tensorflow as tf
tf.__version__ #returns '2.5.0-dev20210203'
x = tf.constant([-2.25, 3.25])
tf.abs(x)
```

Attached screenshot shows a big spike in cuda and GPU memory usage while running tf.abs(x) before python crashes.
![Capture3](https://user-images.githubusercontent.com/53418753/106899490-882f3200-6749-11eb-9fbf-36ec285ea768.PNG)

Appreciate any further advice if you have it, but perfectly happy to accept that this may be my own problem!

**Comment by jessyprociv** [comment]
After running into some other issues today I've been able to identify and solve my problem by downgrading to tensorflow 2.4 as per:

https://medium.com/analytics-vidhya/using-tensorflow-on-windows-10-with-nvidia-rtx-3000-series-gpus-637ab2a4b163

https://medium.com/@JeansPantRushi/fix-for-tensorflow-v2-failed-to-get-convolution-algorithm-b367a088b56e

Thank you again for your help and sorry to have raised a false bug report!
