### ISSUE TITLE
[quantization] Post-training quantization using TFLiteConverter isn't working in TF 2.3

### ISSUE THREAD

**Issue by frgfm** [tensorflow/tensorflow#46922]
Hello there :wave: 

**System information**
- Have I written custom code: not one bit
- OS Platform and Distribution: Linux, Ubuntu 20.04
- TensorFlow installed from: pip
- TensorFlow version: 2.3.1
- Python version: 3.8.5
- CUDA/cuDNN version: CUDA 11.0, cuDNN 8.0.5
- GPU model and memory: GeForce RTX 2070 Max Q, 8Gb RAM

**Describe the current behavior**
There seems to be an issue in TF 2.3, where post-training quantization does not seem to actually work: quantized version are no smaller than fp16 counterpart using the conversion tutorial from the documentation (post-training). This seems to have been fixed in tf2.4 but I din't see any related issue or mention of a fix (I may have missed a few things :sweat_smile: ).

**Describe the expected behavior**
Using the same TFLite converter, the bare TFLite model should be strictly bigger than its FP16 counterpart, which in turn should be strictly bigger than its int8 counterpart.

**Standalone code to reproduce the issue**
The following code raises an error in TF2.3.1 but no longer in TF 2.4.* :
```
import sys
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, Sequential

_layers = [
    layers.Conv2D(8, 3, activation='relu', padding='same', input_shape=(224, 224, 3)),
    layers.GlobalAveragePooling2D(),
    layers.Flatten(),
    layers.Dense(10),
]
mock_model = Sequential(_layers)

def convert_to_fp16(tf_model):
    converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)

    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    return converter.convert()


def quantize_model(tf_model, input_shape):
    converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)

    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    # Float fallback for operators that do not have an integer implementation
    def representative_dataset():
        for _ in range(100):
            data = np.random.rand(1, *input_shape)
            yield [data.astype(np.float32)]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    return converter.convert()


assert sys.getsizeof(convert_to_fp16(mock_model)) > sys.getsizeof(quantize_model(mock_model, (224, 224, 3)))
```

**Other info / logs** No error is actually thrown during the execution, but the behaviour is not as expected. The same test is passing between a bare tflite conversion (in fp32), and fp16 conversion, but fails between fp16 and int8.

**Comment by teijeong** [comment]
Hi @frgfm, it's possbile that the changelog missed misc. bug fixes. Also, afaik it's not likely for bug fixes to be applied to previous releases. Are you looking for bug fixes without upgrading TF version?

**Comment by frgfm** [comment]
Well, I understand the release process so: no, not really. But since I didn't see it mentioned anywhere, I was afraid it was not on purpose, or worse: that it's still not working.

Anyway, the issue here is that for projects having flexible dependencies on the TF side would experience silent issues here. I think this should be highlighted in the documentation or as a warning somewhere :man_shrugging:

**Comment by fg-mindee** [comment]
@teijeong so what do you suggest? Opening a PR to edit the documentation?
Since this isn't assigned to anyone anymore, either you decide that this should not be worked on and we close the issue, or we do something about it. I just wouldn't like to grow the pile of unhandled issues on the project :pray:

**Comment by frgfm** [comment]
Any update @teijeong ? :pray:

**Comment by charlesmindee** [comment]
Hi, I have the same issue, this is my system information:

  OS Platform and Distribution: Linux, Ubuntu 18.04
  TensorFlow installed from: pip
  TensorFlow version: 2.3.1
  Python version: 3.7
  CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
  GPU model and memory: GeForce RTX 2080 Ti

**Comment by sushreebarsa** [comment]
I tried to run the code in colab with TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c4591ed6d13af508ced2d17f5ea856ed/untitled157.ipynb?authuser=1#scrollTo=L51E5SZFhQug)..Thanks !

**Comment by frgfm** [comment]
Hi @sushreebarsa,

What do you mean? Did you have issues with TF nightly? Because, as mentioned earlier, this issue is about TF < 2.4. Starting from TF 2.4, I didn't experience any issue.

**Comment by sushreebarsa** [comment]
I also didn't experience any issue in TF-nightly,provided gist is only for reference..Thanks !

**Comment by jvishnuvardhan** [comment]
@frgfm Generally we don't patch it back to an old version unless there is any security related patches. I am closing this issue as this was resolved in recent TF versions.

Feel free to reopen if I am mistaken. Thanks!
