### ISSUE TITLE
http://commondatastorage.googleapis.com/books1000/ no longer available

### ISSUE THREAD

**Issue by msaroufim** [tensorflow/tensorflow#4693]
This is not tensorflow issue but an issue with the first tutorial in the udacity program https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb

The url is not found and is not accessible via a browser, tried Chrome 53 on Mac OS X 10.11

**Comment by msaroufim** [comment]
Found the right url after googling it http://yaroslavvb.com/upload/notMNIST/

Tutorial just needs an update

**Comment by yaroslavvb** [comment]
That's the URL hosted on my personal server I changed it to GCS-hosted version under /books1000/ because my ISP blocked yaroslavvb.com due to too many accesses.  Someone should rehost it in a place that can take load or fix the commondatastorage address (I'm guessing it's a internal billing issue) @vincentvanhoucke

**Comment by vincentvanhoucke** [comment]
I can access both:
http://commondatastorage.googleapis.com/books1000/notMNIST_large.tar.gz
http://commondatastorage.googleapis.com/books1000/notMNIST_small.tar.gz
What's not working for you? Were you trying to get to:
http://commondatastorage.googleapis.com/books1000/ ? That won't work.

**Comment by jowagner** [comment]
FYI: (1) The last post on https://discussions.udacity.com/t/assignment-1-code-cell-2-error/197910 now  points to @yaroslavvb 's personal server. (2) notMNIST_large.tar.gz on books1000 is now about 30 MB smaller than the original. Did you remove broken images?

**Comment by yaroslavvb** [comment]
I haven't touched the version on my server

**Comment by vincentvanhoucke** [comment]
Nothing has changed in a while, I certainly haven't touched the dataset since Yaroslav put it up.

**Comment by jlcarval** [comment]
Hi,
I just downloaded from http://commondatastorage.googleapis.com/books1000/notMNIST_large.tar.gz
and check the file size. It is 52723712. 
Change that number on train_filename = maybe_download('notMNIST_large.tar.gz', 52723712) and worked.

Thanks

**Comment by Shivanshmundra** [comment]
Hi,
This is issue is because in assignment its **https** while this should be **http**.
Hope you got that right.
Thanks

**Comment by jowagner** [comment]
(1) Both http and https work right now. 
(2) I don't remember but if an https connection had been refused, I sure would have tried http as well. 
(3) File sizes changed again. Creating issue #12208
