### ISSUE TITLE
Ubuntu 20.10 and 3090 with CUDA 11.0 and cuDNN 8.0: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'

### ISSUE THREAD

**Issue by othrif** [tensorflow/tensorflow#46933]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.4.1
- Python version: 3.8.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 11.0.3/8.0.5.39
- GPU model and memory: GeForce RTX 3090 24GB

**Describe the problem**

I just set up a new deep learning station with Ubuntu 20.10 and a GeForce RTX 3090. I am receiving a very large number of warnings in the form of:

```
2021-02-04 08:52:12.943009: W tensorflow/stream_executor/gpu/asm_compiler.cc:235] Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'
```

I followed the instructions in:
* https://www.tensorflow.org/install/gpu
* https://www.tensorflow.org/install/source#gpu
(though the instructions are not updated since Ubuntu 18.04)

To build a setup with
* Tensorflow 2.4.1
* NVIDIA GPU driver: 460.32.03
* CUDA toolkit: 11.0.3
* cuDNN: 8.0.5.39

**Provide the exact sequence of commands / steps that you executed before running into the problem**
``` bash 
sudo apt -y install build-essential
sudo apt -y install gcc-8 g++-8 gcc-9 g++-9

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8 --slave /usr/bin/g++ g++ /usr/bin/g++-8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9 --slave /usr/bin/g++ g++ /usr/bin/g++-9

sudo update-alternatives --config gcc # select gcc-8 option (1)
gcc --version # to check it is gcc 8

# Get CUDA Toolkit
# TF 2.4.0 compatibel with cuDNN 8.0 and CUDA 11.0
wget https://developer.download.nvidia.com/compute/cuda/11.0.3/local_installers/cuda_11.0.3_450.51.06_linux.run
sudo bash cuda_11.0.3_450.51.06_linux.run # Deslect CUDA driver and install
# Add the following to the bashrc file
export PATH=$PATH:/usr/local/cuda-11.0/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.0/lib64

# Get cuDNN package
tar -xvf cudnn-11.0-linux-x64-v8.0.5.39.tgz
sudo cp cuda/include/cudnn.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
nvcc --version
nvidia-smi
python -c "import tensorflow as tf; tf.config.list_physical_devices('GPU')"
```

**Comment by amahendrakar** [comment]
@othrif,
Please check if TensorFlow is able to detect the GPU on your machine by running the below code
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

Also, you can suppress the warnings by changing the log level at the start of the program as shown below.  
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```

Thanks!

**Comment by othrif** [comment]
Thanks @amahendrakar! I am able to run with the GPU, and changing the log level suppressed these warnings.

**Comment by ramram1987** [comment]
Hi @othrif I Have a different but as we have similar specs I thought you might help me.

    Linux Ubuntu 20.10
    TensorFlow version: 2.4.1
    Python version: 3.8.7
    CUDA: 11.0.221
    GPU model and memory: GeForce RTX 3090 24GB

I am not able to install cuda. I tried to follow Nvidia documentation for ubuntu 20.04 but it failed. Can you tell me how did you do?

**Comment by othrif** [comment]
Hi @ramram1987, the Nvidia documentation is difficult to follow and a the tensorflow GPU documentation did not work for me. Have you tried the instructions i included above on how i installed tensorflow?
