### ISSUE TITLE
Initialization of global pointer variable seems suspect with our current use of Renode.

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#46937]
@tensorflow/micro

I hit this issue while working on https://github.com/tensorflow/tensorflow/pull/46904:

 * If I create a global pointer variable (explicitly initialized to nullptr) and check for the variable == nullptr in my factory function, the check always returns false.

AFAICT, this behavior is specific to our use of Renode. I have not been able to reproduce on Linux or with the Xtensa simulator.

I have a workaround that should allow #46904 to be merged and I will then update this issue with a cleaner way to reproduce this error.

**Comment by PiotrZierhoffer** [comment]
The reason is in `_zero_initialize_bss_data` (tensorflow/lite/micro/tools/make/downloads/stm32_bare_lib/source/startup.c). It initializes the BSS data with DEADBEEF.

To verify that:

Build with debug info
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=bluepill BUILD_TYPE=debug test_renode -j`nproc`
```

Run in Renode:
```
include @tensorflow/lite/micro/testing/bluepill_nontest.resc; sysbus LoadELF @tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3_debug/bin/test_renode; machine StartGdbServer 3333
```

Start GDB:
```
tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-gdb tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3_debug/bin/test_renode
```

In GDB:
```
tar rem :3333
watch *0x20000008
mon s
c
```

It will break in the code that actually writes this data.

Now why do they go to bss instead of data? I don't know.

Here's an excerpt from the objdump:

```
Disassembly of section .data:

20000000 <a>:                        <- OK
20000000:   0000002d    andeq   r0, r0, sp, lsr #32

20000004 <init_to_true>:                        <- OK
20000004:   00000001    andeq   r0, r0, r1

Disassembly of section .bss: 

20000008 <init_to_false>:                        <- NOT OK
20000008:   00000000    andeq   r0, r0, r0

2000000c <init_to_nullptr>:                        <- NOT OK
2000000c:   00000000    andeq   r0, r0, r0

20000010 <g_tick_count>:                        <- NOT OK
20000010:   00000000    andeq   r0, r0, r0

Disassembly of section ._user_heap_stack:

20000014 <._user_heap_stack>:
    ...   
```

For the record, this is HAL specific, so it should behave the same way on HW, not only in Renode.

**Comment by PiotrZierhoffer** [comment]
Changing 0xDEADBEEF to 0 of course fixes the problem

**Comment by ajelinski** [comment]
Your example @advaitjain has similar results on `stm32f4` also built with `stm32_bare_lib` that causes the problem.

The `-559038737` number that is printed as `init_to_nullptr` is exactly a signed int value for `0xDEADBEEF`. The `239` in `init_to_false` is the ending `0xEF` byte.

I remember stumbling upon an issue with this BSS initialization when code from such an `if` was never executed:
```
static TYPE* some_pointer = nullptr;
if (!some_pointer){
    // Code never called
}
```
The compiler simply assumed a static pointer is always `nullptr` (`0x0`) right after declaration and skipped the "additional" `nullptr` initialization while it was `0xDEADBEEF` instead.

Now I can see there's no such problem anymore so perhaps the compiler has been fixed.

Nevertheless, this issue made me wonder again about what the purpose of that `0xDEADBEEF` initialization is. The binaries work well without it. Perhaps it could be simply disabled @aselle @petewarden? https://github.com/google/stm32_bare_lib/blob/55bf49816f1a9dc7d9e35951c135e852ce7a98df/source/startup.c#L114

**Comment by advaitjain** [comment]
Thanks for the debugging @PiotrZierhoffer.

@ajelinski, I'm not sure about the thinking behind the decision to go with not zero initializing the .bss -- it does seem non-standard.

I have made https://github.com/tensorflow/tensorflow/pull/47382 that fixes this issue independent of upstream changes to STM32 Bare Lib and also answers @PiotrZierhoffer's comment about why the variables are ending up in .bss instead of .data

This link has some useful info as well: https://stackoverflow.com/q/8721475

**Comment by advaitjain** [comment]
Talked to @petewarden and we decided that changine STM32 Bare Lib is the way to go.

> 
> I have made #47382 that fixes this issue independent of upstream changes to STM32 Bare Lib and also answers @PiotrZierhoffer's comment about why the variables are ending up in .bss instead of .data
> 
> This link has some useful info as well: [stackoverflow.com/q/8721475](https://stackoverflow.com/q/8721475)

#47382 originally added `-fno-zero-initialized-in-bss` and verified that the globals were in the .data section instead of .bss using the tips from https://stackoverflow.com/q/8721475

It has since been updated to simply pull in an updated version of STM32 Bare Lib (with the zero initialization of .bss)
