### ISSUE TITLE
Subgraph search & replace (graph surgery)

### ISSUE THREAD

**Issue by nscotto** [tensorflow/tensorflow#46930]
TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I would like to be able to do subgraph search & replace of models, basically to replace some block of operators by others automatically.
Currently there is no way to iterate over the graph with a standard graph traversal, making it hard/impossible to perform automatic subgraph search & replace.

**Will this change the current api? How?**
Not necessarily, Pytorch is developping torch.fx for doing something similar (in 1.8 alpha)

**Who will benefit with this feature?**
Businesses wanting to write custom framework on top of tensorflow for automatic model modifications taylored to their needs.

**Any Other info.**

**Comment by mihaimaruseac** [comment]
I think Grappler already does this.

**Comment by nscotto** [comment]
It does replace blocks, but I can't use it to replace what blocks I want.
By blocks, I mean a block ranges from a single operator to a full feature extractor.
Grappler seems to be a tool to do optimization for you, not exactly what I am looking for.

**Comment by mihaimaruseac** [comment]
I think it is better to make a RFC at https://github.com/tensorflow/community/

**Comment by ematejska** [comment]
The API owners are moving to a rotation based system and assigning several owners to follow along and comment.

**Comment by manivaradarajan** [comment]
Closing in light of request for RFC: https://github.com/tensorflow/tensorflow/issues/46930#issuecomment-776104414
