### ISSUE TITLE
Cannot create mbed folder

### ISSUE THREAD

**Issue by mdinoulis** [tensorflow/tensorflow#46936]
**System information**
- OS Platform and Distribution Windows 10
- Mobile device STM32F746

When I run the command:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_hello_world_mbed_project

I get the following error message:
/Makefile:61: *** The TAGS command line option is no longer supported in the TFLM Makefile..

**Comment by amahendrakar** [comment]
@mdinoulis,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/46667#issuecomment-766923481) from issue [#46667](https://github.com/tensorflow/tensorflow/issues/46667) with a similar error and let us know if it helps. Thanks!

**Comment by mdinoulis** [comment]
Thanks for the quick response, however I already tried removing the TAG descriptor but I get the following error:

make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed  generate_hello_world_mbed_project
process_begin: CreateProcess(NULL, uname -m, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:47: pipe: No error
-m was unexpected at this time.
'tr' is not recognized as an internal or external command,
operable program or batch file.
FIND: Parameter format not correct
FIND: Parameter format not correct
The syntax of the command is incorrect.
process_begin: CreateProcess(NULL, bash D:\Projects\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:519: pipe: Bad file descriptor
tensorflow/lite/micro/tools/make/Makefile:521: *** Something went wrong with the flatbuffers download: .  Stop.

**Comment by mdinoulis** [comment]
Note this is using the latest version of the tensorflow repository, cloned yesterday.

**Comment by mdinoulis** [comment]
Ok, I've made some progress with this problem but it's still not working.
I have installed bash for windows. I then got an error saying wget was not found and so have installed wget too.

Now when I try and run make it partially compiles but I get the following error message:
(Note that I have managed to get it to compile on my Mac using gmake - however I would like to get this running on my PC too)


$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed generate_hello_world_mbed_project
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2021-02-06 15:18:49--  http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip
Resolving mirror.tensorflow.org... 142.250.178.16, 2a00:1450:4009:815::2010
Connecting to mirror.tensorflow.org|142.250.178.16|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1760478 (1.7M) [application/zip]
Saving to: `C:/Users/mdino/AppData/Local/Temp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip'

     0K .......... .......... .......... .......... ..........  2% 2.13M 1s
    50K .......... .......... .......... .......... ..........  5% 4.13M 1s
   100K .......... .......... .......... .......... ..........  8% 4.62M 0s
   150K .......... .......... .......... .......... .......... 11% 2.83M 0s
   200K .......... .......... .......... .......... .......... 14% 6.34M 0s
   250K .......... .......... .......... .......... .......... 17% 1.76M 0s
   300K .......... .......... .......... .......... .......... 20% 96.9M 0s
   350K .......... .......... .......... .......... .......... 23% 2.47M 0s
   400K .......... .......... .......... .......... .......... 26% 3.98M 0s
   450K .......... .......... .......... .......... .......... 29% 1.26M 0s
   500K .......... .......... .......... .......... .......... 31% 12.4M 0s
   550K .......... .......... .......... .......... .......... 34% 8.67M 0s
   600K .......... .......... .......... .......... .......... 37% 3.93M 0s
   650K .......... .......... .......... .......... .......... 40%  156M 0s
   700K .......... .......... .......... .......... .......... 43% 7.60M 0s
   750K .......... .......... .......... .......... .......... 46% 4.49M 0s
   800K .......... .......... .......... .......... .......... 49% 4.25M 0s
   850K .......... .......... .......... .......... .......... 52% 5.23M 0s
   900K .......... .......... .......... .......... .......... 55% 4.00M 0s
   950K .......... .......... .......... .......... .......... 58% 4.21M 0s
  1000K .......... .......... .......... .......... .......... 61% 3.13M 0s
  1050K .......... .......... .......... .......... .......... 63% 5.83M 0s
  1100K .......... .......... .......... .......... .......... 66% 6.03M 0s
  1150K .......... .......... .......... .......... .......... 69% 3.86M 0s
  1200K .......... .......... .......... .......... .......... 72% 5.50M 0s
  1250K .......... .......... .......... .......... .......... 75% 5.55M 0s
  1300K .......... .......... .......... .......... .......... 78% 4.17M 0s
  1350K .......... .......... .......... .......... .......... 81% 3.74M 0s
  1400K .......... .......... .......... .......... .......... 84% 5.93M 0s
  1450K .......... .......... .......... .......... .......... 87% 3.14M 0s
  1500K .......... .......... .......... .......... .......... 90% 4.46M 0s
  1550K .......... .......... .......... .......... .......... 93% 5.87M 0s
  1600K .......... .......... .......... .......... .......... 95% 3.44M 0s
  1650K .......... .......... .......... .......... .......... 98% 6.73M 0s
  1700K .......... .........                                  100% 7.64M=0.4s

2021-02-06 15:18:49 (4.12 MB/s) - `C:/Users/mdino/AppData/Local/Temp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip' saved [1760478/1760478]

/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 1: $'PK\003\004': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 2: nL8Q5: command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 3: nL8Q?: command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 4: $'\bnL8Qw\030B\005\352\002\304\005V': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 4: $'\367\257XY': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'\002T': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'v힍\265M4\036w]\027\262\036p\250t5\256\367\245f': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'\225L\347\313l\036\020\350\341е\254\3218\002~\264B\323\302\371\016XC\2408\313': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'@\244͏\v\2105': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'\301\2173H2\037.\342,\311N\223\233d}\231^\257\341': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'^\255\342\345:\231g\220\256': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: $'m\237\220Q7\037Ԣ\304R\234R\372T\235\317k\347T\347\316ܝ\353F\352\217g\317q': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 5: 6▒m@0▒cs/d▒▒ ▒j▒4▒E)8▒&▒▒▒z@-i#hPo▒q▒X▒6▒▒
▒l▒▒{▒▒A
        y+▒▒▒▒▒▒Ff▒%▒▒32▒܇▒5▒s▒▒D%k<▒ȂJ▒▒▒W▒9▒▒0▒ubOO▒▒▒_▒ɕ▒@▒▒Y▒0▒!▒▒m▒▒b▒Ѫh▒R▒(K▒H▒2@L▒90j▒▒63J▒^%,▒G▒▒j-\▒▒liW▒▒▒A
                                                                                                                     ▒27/▒1▒▒▒U▒e'▒j
   Yk▒u9▒▒▒#▒3▒(lඤ▒d7▒▒Z4K▒Ez▒▒y}▒]O▒▒,▒m'>!▒(▒}▒▒▒▒▒W▒t▒▒|^▒▒8▒▒Zu▒▒v{▒▒Jt+{ߐ%^▒▒k<~.▒ـ▒Z46▒▒v9▒▒      ▒▒v▒▒Z▒Ԋ▒ݏܲ{7▒oȽ▒)
                                                                                                                         H\▒/   ▒e▒C▒w▒▒@▒▒▒▒▒▒▒B2▒#-{▒▒0▒▒▒▒▒l>9▒▒t)▒▒s_▒▒P2▒   PK
nL8Q>   flatbuffers-dca12522a9f9e37f126ab925fd385c807ab4f84e/.bazelci/UT▒▒l_PK
nL8Q=▒!X▒K      flatbuffers-dca12522a9f9e37f126ab925fd385c807ab4f84e/.bazelci/presubmit.ymlUT▒▒l_▒▒▒▒J*▒▒I▒L▒L-▒R▒I,I-.▒*▒i▒E▒▒V
▒I▒y%▒▒f& ▒▒X}|IbQzjI1DHWAIOOO  ▒▒Kj▒▒▒ML▒/▒▒PK
nL8Q▒4%_▒0B     flatbuffers-dca12522a9f9e37f126ab925fd385c807ab4f84e/.clang-formatUT▒▒l_m▒Mn▒@
                                                                                              ▒▒>)[v▒▒*RP▒\p+▒y▒n▒Q▒E▒: No such file or directory
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 11: $'OO\337\367ʲ\204\0365\3341P]\034\327\025ZL4\237t\364]r\363\024c\020\202\216\214?h\210\254N\326\b\a\275\221z]P\022\301c\177\346\2608\274\350\234\3230tl4y\006\244\272h.y\371\214i\201,': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 11: $'\034ZÉ枓\377\b\277\211\215l\270\247\326\b\257ot[\005\235:\232\004\235\243\246\277\231\304m\242\3711\277\356\361\235$\235\264\031Y\363\351\2365\363\334\356\004\343\232-_\346_\332+\355[\264\371\021\324J\234\256\377B\252\252\002\370\004PK\003\004': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 12: $'\bnL8Q\33088Ҟ\337B': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 13: $'\302@\020D\373': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 16: $'\021\301\336\316\322?\020': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 16: r▒▒▒▒T▒bLl▒XN▒▒▒QtK*4: No such file or directory
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 16: $'\202\v%Q\256\253\333\341^\211ulh': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 17: $'f\345eey\206\310?SޫwZ\270pF\223Ă6\306\3236\375{\351\003PK\003\004': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 18: $'\bnL8QԠP3\211\375A': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: command substitution: line 19: syntax error near unexpected token `)'
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: command substitution: line 19: `1
                                                                                    D▒▒▒▒▒▒▒▒▒d▒mJ▒▒.▒[▒^ĝ3o=&▒9bxB ▒0j▒<▒▒▒▒k$▒x)(b"1 ▒▒P▒x▒l'
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 16: $'ł\205\270\312\0261ͼ\304RT\373t\363\206\036t\371\261\204d\340Vׯv\230\036\236\332\300U0\330_\246\345\f\343L\336\027\027mg\252ۮ\230\235g\376\201I\275\317\037PK\003\004': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 17: $'\bnL8Q\026\345\365\275OUC': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 18: $'\200': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 18: $'\365\370\243\371PK\003\004': command not found
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 19: flatbuffers-dca12522a9f9e37f126ab925fd385c807ab4f84e/.github/UT▒▒l_PK: No such file or directory
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 20: syntax error near unexpected token `('
/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: line 20: nL8Q}▒▒▒N   flatbuffers-dca12522a9f9e37f126ab925fd385c807ab4f84e/.github/ISSUE_TEMPLATE.mdUT▒▒l_U▒AO▒0
                                 ▒▒▒o▒▒(▒▒v@ABp H▒^▒▒Ҥ▒]`▒▒C▒I▒!▒▒▒=▒▒▒▒▒!▒hr▒▒▒>▒▒Ԃ▒▒▒
                                                                                       ▒^#▒0zڳU▒▒C▒q▒▒1▒,▒▒|▒▒a▒\#RjGj▒B.+▒▒!r▒'9͏y▒B▒▒D▒?KR▒▒I▒GkX▒$g▒B9B▒F^9▒▒A▒q▒▒▒u▒▒▒1▒▒▒bj▒1▒=HO▒▒▒▒▒,▒▒▒!-▒9▒G     ▒s▒▒▒▒W▒        ▒=▒L▒▒▒▒<\]Uh▒▒zu[▒▒▒▒▒▒▒▒▒S▒7▒dvT@JּeY▒ ▒q)Z▒▒r▒▒▒▒;▒▒򑱡▒,▒٠nV▒sϿ▒▒6▒▒▒▒{4=;▒I%▒▒f▒▒▒▒PK'
tensorflow/lite/micro/tools/make/Makefile:521: *** Something went wrong with the flatbuffers download: Bad checksum. Expected: aa9adc93eb9b33fa1a2a90969e48baee, Got: .  Stop.

**Comment by amahendrakar** [comment]
@mdinoulis,
Could you please check if you are facing the same issue in a Linux environment as well.

Alos, go through these comments from similar issues [#45033](https://github.com/tensorflow/tensorflow/issues/45033#issuecomment-732299726) and [#46916](https://github.com/tensorflow/tensorflow/issues/46916#issuecomment-774973928) as well. Thanks!

**Comment by mdinoulis** [comment]
This appears to work on my OSX environment but not on Windows
