### ISSUE TITLE
`tf.random.learned_unigram_candidate_sampler` crashes(abort) when `range_max` is large

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46938]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.random.learned_unigram_candidate_sampler` crashes(abort) when `range_max` is large

**Describe the expected behavior**
expect an exception message if the file format is incorrect instead of crash

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.random.learned_unigram_candidate_sampler(true_classes=np.ones((1,1)), num_true=1, num_sampled=1, unique=True, range_max=3118649543)
~~~

Output:
~~~python
2021-02-04 23:02:12.013481: F tensorflow/core/lib/random/weighted_picker.cc:27] Check failed: N >= 0 (-1176317753 vs. 0)
Aborted (core dumped)
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b8e2017e50e2d6bb9ff385b256dec117/46938.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Colab crashes in TF 2.6 Nightly as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c0ee174eaa10bbcd578f3f6652fe9a57/untitled92.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
PR has been submitted internally, Thanks for reporting the bug.
