### ISSUE TITLE
tf.nn.depth_to_space crash(aborts) with block_size is large

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46939]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.nn.depth_to_space` crash(aborts) with `block_size` is large

**Describe the expected behavior**
expect an exception message if the file format is incorrect instead of crash

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.nn.depth_to_space(input=np.ones((4, 1, 1, 1)), block_size=2147483647)
~~~

Output:
~~~python
2021-02-05 00:28:12.102761: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-02-05 00:28:12.108864: F tensorflow/core/framework/tensor_shape.cc:353] Check failed: 0 <= new_num_elements (0 vs. -17179869180)
Aborted (core dumped)
~~~

**Comment by ravikyram** [comment]
@DNXie 

I have tried in colab with TF versions 2.1, 2.4, nightly versions(`2.5.0-dev20210204`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/177654fc4b30edb5ed05136747b83ee6/untitled660.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
@DNXie I tried to reproduce the issue in TF 2.6 and the colab doesnt crashes instead it gives an error message. Please check the gist [here](https://colab.research.google.com/gist/saikumarchalla/c0ee174eaa10bbcd578f3f6652fe9a57/untitled92.ipynb#scrollTo=aVDdvD6FlZyv).Thanks!

**Comment by DNXie** [comment]
@saikumarchalla I think the gist you referred to is a wrong API. The bug still exists, see [gist](https://colab.research.google.com/drive/15PAAdaxZXoJvtuZ0joDwOBpTTc2crDQG?usp=sharing).
