### ISSUE TITLE
Cannot Install Tensorflow on any version of Python 3.8

### ISSUE THREAD

**Issue by kunaldas1997** [tensorflow/tensorflow#46934]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- TensorFlow installed from (source or binary): Cannot Install
- TensorFlow version: NaN
- Python version: 3.8, 3.8.7, 3.9, 3.9.1 (All 64-bit)
- Installed using virtualenv? pip? conda?: pip via venv

**Describe the problem**
Cannot install tensorflow. tried on all the above mentioned python version. Yes it is a 64-bit installation. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Tried:
pip install tensorflow
pip install --upgrade tensorflow
pip install --upgrade ALL_URLS_FOR_WINDOWS
py -m ALL_ABOVE_COMMANDS

**Comment by alecStewart1** [comment]
Same issue here.

I was using [poetry](https://python-poetry.org/) and luckily it gives an error of sorts.
On WIndows 10 x64, whether you're trying to use the release or nightly version, I recieve this error using Python 3.8.2 and poetry:

```
  EnvCommandError

 

  Command C:\Users\my_user\AppData\Local\pypoetry\Cache\virtualenvs\recommendation-engine-GCPmYScX-py3.8\Scripts\pip.exe install --no-deps file:///C:/Users/my_user/AppData/Local/pypoetry/Cache/artifacts/2f/3c/d9/0fd02d4091668a37d58877876469a9d8989635f2891a38541592711257/tensorflow-2.4.1-cp38-cp38-win_amd64.whl errored with the following return code 1, and output:

  Processing c:\users\my_user\appdata\local\pypoetry\cache\artifacts\2f\3c\d9\0fd02d4091668a37d58877876469a9d8989635f2891a38541592711257\tensorflow-2.4.1-cp38-cp38-win_amd64.whl

  Installing collected packages: tensorflow

  ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\users\\my_user\\appdata\\local\\pypoetry\\cache\\virtualenvs\\recommendation-engine-gcpmyscx-py3.8\\Lib\\site-packages\\tensorflow\\include\\external\\llvm-project\\mlir\\_virtual_includes\\AffineMemoryOpInterfacesIncGen\\mlir\\Dialect\\Affine\\IR\\AffineMemoryOpInterfaces.cpp.inc'

```

**Comment by kunaldas1997** [comment]
I gave Python 3.8.4 a shot, and tensorflow was installed! I don't know what is going with tensorflow's development. Newb like me can literally leave the field because there is no proper doc to tell as of what to do when such error occurs.

**Comment by ravikyram** [comment]
@kunaldas1997 

Which version of Tensorflow you are installing. Please ,see tested build configurations from [here](https://www.tensorflow.org/install/source_windows#tested_build_configurations).Thanks!

**Comment by kunaldas1997** [comment]
> Same issue here.
> 
> I was using [poetry](https://python-poetry.org/) and luckily it gives an error of sorts.
> On WIndows 10 x64, whether you're trying to use the release or nightly version, I recieve this error using Python 3.8.2 and poetry:
> 
> ```
>   EnvCommandError
> 
>  
> 
>   Command C:\Users\my_user\AppData\Local\pypoetry\Cache\virtualenvs\recommendation-engine-GCPmYScX-py3.8\Scripts\pip.exe install --no-deps file:///C:/Users/my_user/AppData/Local/pypoetry/Cache/artifacts/2f/3c/d9/0fd02d4091668a37d58877876469a9d8989635f2891a38541592711257/tensorflow-2.4.1-cp38-cp38-win_amd64.whl errored with the following return code 1, and output:
> 
>   Processing c:\users\my_user\appdata\local\pypoetry\cache\artifacts\2f\3c\d9\0fd02d4091668a37d58877876469a9d8989635f2891a38541592711257\tensorflow-2.4.1-cp38-cp38-win_amd64.whl
> 
>   Installing collected packages: tensorflow
> 
>   ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\users\\my_user\\appdata\\local\\pypoetry\\cache\\virtualenvs\\recommendation-engine-gcpmyscx-py3.8\\Lib\\site-packages\\tensorflow\\include\\external\\llvm-project\\mlir\\_virtual_includes\\AffineMemoryOpInterfacesIncGen\\mlir\\Dialect\\Affine\\IR\\AffineMemoryOpInterfaces.cpp.inc'
> 
> ```

    Latest. 2.4.1

**Comment by kunaldas1997** [comment]
> @kunaldas1997 
> 
> Which version of Tensorflow you are installing. Please ,see tested build configurations from [here](https://www.tensorflow.org/install/source_windows#tested_build_configurations).Thanks!

Latest 2.4.1

**Comment by ravikyram** [comment]
@kunaldas1997 

Glad to know it was resolved.Please, close this thread as the issue was resolved.Thanks!

**Comment by kunaldas1997** [comment]
> @kunaldas1997 
> 
> Glad to know it was resolved.Please, close this thread as the issue was resolved.Thanks!

Atleast a clear mention on docs will be valuable, so that new people dont have to strugggle.

**Comment by Taimor80** [comment]
I faced the same problem with Python  3.8.5
This works for me:
enable "long path" policy using "gpedit.msc",  then execute "pip install --upgrade  tensorflow"

**Comment by stevenjoezhang** [comment]
See also https://stackoverflow.com/questions/66672519/could-not-install-packages-due-to-an-oserror-errno2-no-such-file-or-directory

**Comment by qiantanjingtao** [comment]
> I faced the same problem with Python 3.8.5 This works for me: enable "long path" policy using "gpedit.msc", then execute "pip install --upgrade tensorflow"



> See also https://stackoverflow.com/questions/66672519/could-not-install-packages-due-to-an-oserror-errno2-no-such-file-or-directory

https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
