### ISSUE TITLE
tf.keras.backend.random_normal segfault 

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46941]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.backend.random_normal` crashes(segfault) when `dtype` is integer

**Describe the expected behavior**
expect an exception message if the file format is incorrect instead of crash

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.keras.backend.random_normal(shape=np.ones((1)), mean=np.ones((1)), dtype=20)
~~~
Output:
~~~
Segmentation fault (core dumped)
~~~

**Comment by Saduf2019** [comment]
I am able to reproduce the issue on TF v2.4 and TF-nightly. Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8c1d5438aa272e9137543a1bf72c57bd/untitled520.ipynb). 
Thanks!

**Comment by saikumarchalla** [comment]
@DNXie I tried to reproduce the issue in TF 2.6 and the colab doesnt crashes instead it gives an error message. Please check the gist [here](https://colab.research.google.com/gist/saikumarchalla/72c03f6c9bf56ec41f2701d8f2d33fd6/untitled92.ipynb).Thanks!
