### ISSUE TITLE
How to use tflite on bert

### ISSUE THREAD

**Issue by TLCFYBJJHYYSND** [tensorflow/tensorflow#46949]
I have convert a trained bert model from .pb to .tflite。
I have two tasks : 1) sentence pair classification 2) QA on squad2.0 format dataset which need to have more than one outputs.
I have find text classification demo code on normal text classification task, but what should i do to hire tflite on bert.
Wonder that whether tflite BERT needs input_ids, input_mask, input_type_ids, if they are needed, how to make that kind of input to tflite interpreter.
Thanks

**Comment by teijeong** [comment]
Hi,

You would be able to get better answers from broader folks if you ask this kind of question on Stackoverflow.
It seems not so clear what you're question targets to. If it's about BERT's inputs, [TFLite Task Library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/bert_question_answerer) or [Text classification example](https://github.com/tensorflow/examples/blob/master/lite/examples/text_classification/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/textclassification/client/TextClassificationClient.java) would be good places to start.

**Comment by lintian06** [comment]
+1 for what is mentioned above by @teijeong.

(2) For QA task, we already provided demo code for [BERT QA](https://github.com/tensorflow/examples/blob/master/lite/examples/bert_qa/android/app/src/main/java/org/tensorflow/lite/examples/bertqa/ml/QaClient.java). 

If you use a similar BERT model for (1) sentence pair classification but multiple inputs, you can adapt from either [Text classification](https://github.com/tensorflow/examples/blob/master/lite/examples/text_classification/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/textclassification/client/TextClassificationClient.java) or the BERT QA app. The key is to use the right tensor inputs and shapes in java for your model, and run [`tflite.runForMultipleInputsOutputs(inputs, output)`](https://github.com/tensorflow/examples/blob/6bb09d63a8cc9813431257bfac486ebaba1da66c/lite/examples/bert_qa/android/app/src/main/java/org/tensorflow/lite/examples/bertqa/ml/QaClient.java#L230).

**Comment by mohantym** [comment]
Hi @TLCFYBJJHYYSND! 
We are checking to see whether you still need help in this issue . Have you checked with above comment yet?
