### ISSUE TITLE
TensorFlow with DLPack invokes unexpected data transfers

### ISSUE THREAD

**Issue by jeng1220** [tensorflow/tensorflow#46950]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu-18.04
- TensorFlow installed from (source or binary): binary, TensorFlow official docker image 
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA 11.0
- GPU model and memory: Tesla V100

**Describe the current behavior**
TensorFlow with DLPack invokes unexpected data transfers. For instance, before prediction, TensorFlow transfers the data, allocated by CuPy and wrapped with DLPack to CPU, then transfers data back to GPU, and then starts prediction. This behavior makes DLPack meaningless.

**Describe the expected behavior**
TensorFlow shouldn't transfer the data, allocated by CuPy and wrapped with DLPack to CPU. Instead, it should take the data on GPU directly.

**Standalone code to reproduce the issue**
1. sample code (foo.py):
```python
import cupy as cp
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model

n = 10000000

a = Input(shape=(n))
output = Lambda(lambda x: x ** 2)(a)
model = Model(a, output)

x = cp.arange(n, dtype=cp.float32).reshape(1, n)
dltensor = x.toDlpack()
x2 = tf.experimental.dlpack.from_dlpack(dltensor)

cp.cuda.nvtx.RangePush('model.predict')
y = model.predict(x2)
cp.cuda.nvtx.RangePop()
print('done')
```

2. pull TensorFlow image
```bash
$ docker pull tensorflow/tensorflow:latest-gpu
```

3. install CuPy
```bash
# after login the container
$ pip install cupy-cuda110
```

4. run:
```
$ nvprof -o output.nvprof python ./foo.py
# or use Nsight-Systems to record behavior
$ nsys profile -t cuda,nvtx python ./foo.py
```
**Other info / logs**
![tf2_with_dlpack](https://user-images.githubusercontent.com/5894445/107031704-96368e80-67ed-11eb-9092-11e669b3853b.png)

**Comment by EvenOldridge** [comment]
++ @VoVAllen @jermainewang for awareness.
Any thoughts about what could be going on here?

**Comment by VoVAllen** [comment]
It's weird, did you see D2H copy without the forward process? 
Also by setting ` tf.config.experimental.set_device_policy("explicit")`, got error 
```
InvalidArgumentError: Tensors on conflicting devices: cannot compute LogicalNot as input #0 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0) Tensors can be copied explicitly using: `with tf.device(device_name): x = tf.identity(x)` or transparently copied by using tf.config.experimental.set_device_policy('silent'). Copying tensors between devices may slow down your model [Op:LogicalNot]
```
Seems the there's problem on the real device. Also why would it be D2H instead of cudamemcpy?

**Comment by jeng1220** [comment]
@VoVAllen ,

> It's weird, did you see D2H copy without the forward process?

I saw it did D2H copy, H2D copy, forward process and then D2H copy. Obviously, "D2H copy, H2D copy" was redundant.

> Also by setting tf.config.experimental.set_device_policy("explicit"), got error...
> Seems the there's problem on the real device. Also why would it be D2H instead of cudamemcpy?

I saw the error message after setting "explicit" too. 
My machine is fine. I am not familiar with TensorFlow implementation.
I suppose that it is a bug from `tf.experimental.dlpack`, because `x2` should be set as `device:GPU:0` instead of `device:CPU:0`, isn't?

**Comment by VoVAllen** [comment]
I found the error with `tf.config.experimental.set_device_policy("explicit")` is not the error we are looking for. It's some Keras internal issues.

Actually I cannot reproduce the error with 
```python
import cupy as cp
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model
n = 10000000

u = tf.ones(1)

tf.config.experimental.set_device_policy("explicit")
x = cp.arange(n, dtype=cp.float32).reshape(1, n)
dltensor = x.toDlpack()
x2 = tf.experimental.dlpack.from_dlpack(dltensor)

x3 = x2 + u
print('done')
```
It seems there's no copy issue for x3 and x2. Therefore I guess this might related to Keras instead of problem with dlpack

**Comment by VoVAllen** [comment]
```python
import cupy as cp
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model

n = 10000000

a = Input(shape=(n))
output = Lambda(lambda x: x ** 2)(a)
model = Model(a, output)
x = cp.arange(n, dtype=cp.float32).reshape(1, n)
dltensor = x.toDlpack()
x2 = tf.experimental.dlpack.from_dlpack(dltensor)

tf.config.experimental.set_device_policy("warn")
cp.cuda.nvtx.RangePush('model.predict')
y = model.predict(x2)
cp.cuda.nvtx.RangePop()
print('done')
```

You can get 
```
2021-02-08 16:20:19.669326: W tensorflow/core/common_runtime/eager/execute.cc:140] before computing TensorDataset input #0 was expected to be on /job:localhost/replica:0/task:0/device:CPU:0 but is actually on /job:localhost/replica:0/task:0/device:GPU:0 (operation running on /job:localhost/replica:0/task:0/device:CPU:0). This triggers a copy which can be a performance bottleneck.
2021-02-08 16:20:19.704433: W tensorflow/core/common_runtime/eager/execute.cc:140] before computing AssignVariableOp input #1 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0). This triggers a copy which can be a performance bottleneck.
```

The copy is probably due to the `TensorDataset` op.

**Comment by VoVAllen** [comment]
If I use `x2 = tf.reshape(tf.range(n, dtype=tf.float32), (1, n))` as input, the copy still happens. It seems not dlpack problems. Could you check this with nvprof?

**Comment by VoVAllen** [comment]
Also the copy behavior won't be considered as bug, because all tensors inside tensorflow are immutable. Therefore the copy will only happen once for each tensor.

**Comment by jeng1220** [comment]
> Could you check this with nvprof?

Yes, even if `x2` is created by `tf.range`, TensorFlow Keras still do the redundant data transfers:

![image](https://user-images.githubusercontent.com/5894445/107303798-b9e22900-6aba-11eb-890a-fa1f9634a65e.png)

**Comment by jeng1220** [comment]
@VoVAllen ,

>  the copy behavior won't be considered as bug, because all tensors inside tensorflow are immutable. 

Do you mean that due to the design of TensorFlow and the `x2` is not inside TensorFlow, so it must be copied to the tensor which is inside TensorFlow?

If so, the copy of `x2` should be a D2D but it is "D2H, H2D". To address it, we need Keras people's help or authors  of TensorDataset's help.

@EvenOldridge ,
Could you help to loop the right persons?

**Comment by VoVAllen** [comment]
@jeng1220 No. The copy is merely due to `TensorDataset` op inside Keras. It's a cpu op and requires all tensors to be on cpu, thus D2H happens. And the latter operation needs gpu tensor, thus H2D happens. However this should only happen at the first iteration, since tensor already had both cpu and gpu memory.

This is nothing related with dlpack.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
