### ISSUE TITLE
Makefile fails when setting CO_PROCESSOR=ethos-u

### ISSUE THREAD

**Issue by henriwoodcock** [tensorflow/tensorflow#46954]
@tensorflow/micro

make: *** No rule to make target 'tensorflow/lite/micro/tools/make/ext_libs/ethos-u.inc'.  Stop.

**System information**

- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 
- Tensorflow from most recent commit

**Describe the problem**

```
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/ext_libs/ethos-u.inc'.  Stop.
```

**Please provide the exact sequence of commands/steps when you ran into the problem**

 ```
make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 OPTIMIZED_KERNEL_DIR=cmsis-nn CO_PROCESSOR=ethos-u microlite
```

**Comment by jenselofsson** [comment]
Hi!

Try using ethos_u and cmsis_nn instead of ethos-u/cmsis-nn:

`make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 OPTIMIZED_KERNEL_DIR=cmsis_nn CO_PROCESSOR=ethos_u microlite`

**Comment by henriwoodcock** [comment]
> Hi!
> 
> Try using ethos_u and cmsis_nn instead of ethos-u/cmsis-nn:
> 
> `make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 OPTIMIZED_KERNEL_DIR=cmsis_nn CO_PROCESSOR=ethos_u microlite`

That's fixed it thank-you

**Comment by jenselofsson** [comment]
> > Hi!
> > Try using ethos_u and cmsis_nn instead of ethos-u/cmsis-nn:
> > `make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 OPTIMIZED_KERNEL_DIR=cmsis_nn CO_PROCESSOR=ethos_u microlite`
> 
> That's fixed it thank-you

No problem!
