### ISSUE TITLE
Help understand outputs of Mask RCNN tflite model

### ISSUE THREAD

**Issue by MeghaGhosh** [tensorflow/tensorflow#46951]
Hi, I could really do with some help in understanding the outputs of the tflite model of Mask RCNN.

I have converted the model to tflite using Tensorflow 2.3.

The model takes 3 inputs - the resized image, image meta and anchors

I have written the android equivalent code for the resized image - included padding and subtracted pixel means, as well as the image meta and anchors. The model is running but I can't seem to understand which output stands for what.

There are 7 outputs of the tflite model which have dimensions as follows:

[1][1][1]
[1][1000][81][4]
[1][1000][81]
[1][100][6]
[1][100][28][28][81]
[1][1][4]
[1][1][2]

I assume [1][100][28][28][81] is for the masks and I thought [1][100][6] would be the class ID, probability score and bounding boxes. However that doesn't seem to be consistent with the results. I can share the tflite model and the first few results of the outputs if that helps. Any help would be very much appreciated!

**Comment by MeghaGhosh** [comment]
We've run the model many times but we keep getting the same values repeated for the 3rd output. For example:

2021-02-08 15:08:16.206 23908-23908/com.objdetector E/Edg = output3: 0.0011121973 _ I 
2021-02-08 15:08:16.207 23908-23908/com.objdetector E/Edg = output3: 0.24362154 _ I 
2021-02-08 15:08:16.207 23908-23908/com.objdetector E/Edg = output3: 0.0011121973 _ I 
2021-02-08 15:08:16.207 23908-23908/com.objdetector E/Edg = output3: 0.27135313 _ I 
2021-02-08 15:08:16.207 23908-23908/com.objdetector E/Edg = output3: 3.0 _ I 
2021-02-08 15:08:16.207 23908-23908/com.objdetector E/Edg = output3: 0.8469641 

This is repeated each time for each detection. The second and third outputs don't seem to have any pattern and for the fifth output the values keep getting repeated again. Would really appreciate any help here.

**Comment by amahendrakar** [comment]
@MeghaGhosh,
In order to expedite the trouble-shooting process, could you please provide a minimal codes snippet to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by MeghaGhosh** [comment]
Sure, this is the code:


getAnchor( 800, 1024, 0);

private void getAnchor(double min_dim, double max_dim, double min_scale) {    

int[][] backbone_shapes = new int[5][2];    
int stride[] = new int[5];    
double init_scales[] = {8, 16, 32, 64, 128};    
double ratios[] = {0.5, 1, 2};    
int feature_strides[] = {4, 8, 16, 32, 64};    
double scales[] = new double[3];    
double heights[] = new double[3];    
double widths[] = new double[3];    
double anchors[][] = new double[261888][4];    
for (int i = 0; i < 5; i++) {        
stride[i] = 2 * (int) (Math.pow(2, i + 1));        
for (int k = 0; k < 2; k++) {            
backbone_shapes[i][k] = (int) (Math.ceil(1024 / stride[i]));        }        
int shape_0 = backbone_shapes[i][0];        
double shift_x[] = new double[shape_0];        
double shift_y[] = new double[shape_0];        
for (int k = 0; k < 3; k++) {            
scales[k] = init_scales[i];            
heights[k] = scales[k] / Math.sqrt(ratios[k]);            
widths[k] = scales[k] * Math.sqrt(ratios[k]);        }        
for (int a = 0; a < shape_0; a++) {            
shift_x[a] = a * feature_strides[i];        }        
double box_widths[][] = new double[shape_0 * shape_0][3];        
double box_centers_x[][] = new double[shape_0 * shape_0][3];        
double box_heights[][] = new double[shape_0 * shape_0][3];        
double box_centers_y[][] = new double[shape_0 * shape_0][3];        
for (int x = 0; x < shape_0 * shape_0; x++) {            
for (int y = 0; y < 3; y++) {                
box_widths[x][y] = widths[y];                
box_centers_x[x][y] = shift_x[x % shift_x.length];                
box_heights[x][y] = heights[y];                
box_centers_y[x][y] = shift_x[x / shift_x.length];            }        }        
double flattened_widths[] = new double[shape_0 * shape_0 * 3];        
double flattened_centers_x[] = new double[shape_0 * shape_0 * 3];        
double flattened_heights[] = new double[shape_0 * shape_0 * 3];        
double flattened_centers_y[] = new double[shape_0 * shape_0 * 3];        
int s = 0;        
for (int k = 0; k < shape_0 * shape_0; k++)            
for (int j = 0; j < 3; j++) {                
flattened_widths[s] = box_widths[k][j];                
s++;            }        
s = 0;        
for (int k = 0; k < shape_0 * shape_0; k++)            
for (int j = 0; j < 3; j++) {                
flattened_centers_x[s] = box_centers_x[k][j];                
s++;            }        
s = 0;        
for (int k = 0; k < shape_0 * shape_0; k++)            
for (int j = 0; j < 3; j++) {                
flattened_heights[s] = box_heights[k][j];                
s++;            }        
s = 0;        
for (int k = 0; k < shape_0 * shape_0; k++)            
for (int j = 0; j < 3; j++) {                
flattened_centers_y[s] = box_centers_y[k][j];                
s++;            }        
double box_sizes[][] = new double[shape_0 * shape_0 * 3][2];        
double box_centers[][] = new double[shape_0 * shape_0 * 3][2];        
for (int m = 0; m < shape_0 * shape_0 * 3; m++) {            
box_sizes[m][0] = flattened_heights[m];            
box_sizes[m][1] = flattened_widths[m];            
box_centers[m][0] = flattened_centers_y[m];            
box_centers[m][1] = flattened_centers_x[m];        }        
double boxes[][] = new double[shape_0 * shape_0 * 3][4];        
for (int n = 0; n < shape_0 * shape_0 * 3; n++) {            
boxes[n][0] = box_centers[n][0] - 0.5 * box_sizes[n][0];            
boxes[n][1] = box_centers[n][1] - 0.5 * box_sizes[n][1];            
boxes[n][2] = box_centers[n][0] + 0.5 * box_sizes[n][0];            
boxes[n][3] = box_centers[n][1] + 0.5 * box_sizes[n][1];        }        
if (i == 0) {            
for (int y = 0; y < shape_0 * shape_0 * 3; y++) {                
for (int z = 0; z < 4; z++) {                    
anchors[y][z] = boxes[y][z];                }            }        } 
else if (i == 1) {            
for (int y = 0; y < shape_0 * shape_0 * 3; y++) {                
for (int z = 0; z < 4; z++) {                    
anchors[y + 196608][z] = boxes[y][z];                }            }        } 
else if (i == 2) {            
for (int y = 0; y < shape_0 * shape_0 * 3; y++) {                
for (int z = 0; z < 4; z++) {                    
anchors[y + 196608 + 49152][z] = boxes[y][z];                }            }        } 
else if (i == 3) {            
for (int y = 0; y < shape_0 * shape_0 * 3; y++) {                
for (int z = 0; z < 4; z++) {                    
anchors[y + 196608 + 49152 + 12288][z] = boxes[y][z];                }            }        } 
else {            for (int y = 0; y < shape_0 * shape_0 * 3; y++) {                
for (int z = 0; z < 4; z++) {                    
anchors[y + 196608 + 49152 + 12288 + 3072][z] = boxes[y][z];                }            }        }    }    
for (int z = 0; z < 261888; z++) {        
anchors[z][0] = anchors[z][0] - 0;        
anchors[z][1] = anchors[z][1] - 0;        
anchors[z][2] = anchors[z][2] - 1;        
anchors[z][3] = anchors[z][3] - 1;    }    
for (int z = 0; z < 261888; z++) {        
for (int c = 0; c < 4; c++) {            
anchors[z][c] = anchors[z][c] / 1023;        }    }    
float final_anchors[][][] = new float[1][261888][4];    
for (int z = 0; z < 261888; z++) {        
for (int c = 0; c < 4; c++) {           
// final_anchors[0][z][c] = anchors[z][c];            
final_anchors[0][z][c] = (float)anchors[z][c];        }    }    

BitmapFactory.Options options = new BitmapFactory.Options();    
options.inJustDecodeBounds = true;    
BitmapFactory.decodeResource(getResources(), R.drawable.b1, options);    

double w = options.outWidth;    
double h = options.outHeight;    
double height = h;    
double width =w;    
double scale = 1;    
double[] window ={0,0,w,h};    
scale = Math.max(1, min_dim / Math.min(h, w));    
if(scale < min_scale){        
scale = min_scale;    }    
double image_max = Math.max(h, w);    
if (round(image_max * scale) > max_dim) {        
Double ab = max_dim;        
double ac = image_max;        
scale = ab / ac;    }    
if(scale != 1){        
h= round(h*scale);        
w = round(w*scale);    }    
double  top_pad = (max_dim - h) / 2;    
double  left_pad = (max_dim - w) / 2;    
window[0] = top_pad;    window[1] = left_pad;    
window[2] = h + top_pad;    
window[3] = w + left_pad;    
float [][] meta_value = new float[1][18];    
meta_value[0][0]=0;    
meta_value[0][1] =(float)height;    
meta_value[0][2] =(float)width;    
meta_value[0][3] =3;    
meta_value[0][4] =1024;    
meta_value[0][5] =1024;    
meta_value[0][6] =3;    
meta_value[0][7] =(float)scale;    
meta_value[0][8] =(float)window[0];    
meta_value[0][9] =(float)window[1];    
meta_value[0][10] =(float)window[2];    
meta_value[0][11] =(float)window[3];    
meta_value[0][12] =0;    
meta_value[0][13] = 0;    
meta_value[0][14] =0;    
meta_value[0][15] = 0;    
meta_value[0][16] =0;    
meta_value[0][17] = 0;   
 
int h_h = (int)h;    
int w_w = (int)w;    

sendvalue(meta_value, final_anchors,h_h,w_w);}

private void sendvalue(float[][] meta_value, float[][][] final_anchors, int h, int w) {    
imageBitmapForModel= BitmapFactory.decodeResource(getResources(), R.drawable.b1);
int[] pix = new int[1024*1024];
imageBitmapForModel.getPixels(pix, 0, 1024, 0, 0, 1024, 1024);
float input[][][][] = new float[1][1024][1024][3];
for (int y = 0; y < 1024; y++){    
for (int x = 0; x < 1024; x++)    {        
int index = y * 1024 + x;        
input[0][x][y][0]  = (((pix[index]  >> 16) & 0xff) -123.7f);     
input[0][x][y][1]= (((pix[index] >> 8) & 0xff) -116.8f);        
input[0][x][y][2] = ((pix[index] & 0xff)-103.9f);             
//   pix[index] = 0xff000000 \| (red << 16) \| (green << 8) \| blue;    }} 
final List<DetectionResult> results = newObjectDector.detectObjects(imageBitmapForModel,meta_value,final_anchors,input);}

public List<DetectionResult> detectObjects(Bitmap bitmap, float[][] meta_value, float [][][] final_anchors, float input[][][][]) {

    Object[] inputs = new Object[] {input, meta_value, final_anchors};

   Map<Integer, Object> outputs = new HashMap<>();
    outputs.put(0, new float[1][1][1]);
    outputs.put(1, new float[1][1000][6][4]);
    outputs.put(2, new float[1][1000][6]);
    outputs.put(3, new float[1][100][6]);
    outputs.put(4, new float[1][100][28][28][6]);
    outputs.put(5, new float[1][1][4]);
    outputs.put(6, new float[1][1][2]);
try {
    Date date = Calendar.getInstance().getTime();
    DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy-mm-ss");
    String today = formatter.format(date);
    tfLite.runForMultipleInputsOutputs(inputs, outputs);
        float[][][] output0 = (float[][][])outputs.get(0);

                float[][][][] output1 = (float[][][][])outputs.get(1)
float[][][] output2 = (float[][][])outputs.get(2);
float[][][] output3 = (float[][][])outputs.get(3);
for (int i = 0; i < 20;i++)
{for (int k =0; k<6;k++)
{

    Log.e("output3 ",""+output3[0][i][k] + " _ I - " + i);

}}
float[][][][][] output4 = (float[][][][][])outputs.get(4);
float[][][] output5 = (float[][][])outputs.get(5);
float[][][] output6 = (float[][][])outputs.get(6);
Date dates = Calendar.getInstance().getTime();
DateFormat formatterdd = new SimpleDateFormat("dd/MM/yyyy-mm-ss");
String todays = formatterdd.format(dates);
} catch (Exception e){
    e.printStackTrace();
}


This is the google drive link to our tflite model:

https://drive.google.com/file/d/1S6T5GUHa9WrcK2WZa0DrHpD68w9jHnTX/view?usp=sharing

This is the image we are passing to the model:

![b1](https://user-images.githubusercontent.com/29752250/107219126-a42b2000-6a36-11eb-8fe2-6d294779db77.png)

**Comment by MeghaGhosh** [comment]
Update: 

Converted the model with 2.4.0 and updated gradle build as follows:

implementation 'org.tensorflow:tensorflow-lite-gpu:2.4.0'
compile files ('libs/tensorflow-lite-select-tf-ops.aar')
compile files ('libs/tensorflow-lite.aar')

This is the link to the model:

https://drive.google.com/file/d/1uA05SPwJCzVq1Si2_LnitP7w-qUjLEm6/view?usp=sharing

This is the link to the colab notebook to convert the model:

https://colab.research.google.com/drive/1Ei4-KTdyf0C6ifnxtnuDm8pwCEwxipY8?usp=sharing

Getting zeros in output3 now

. I suspect it has something to do with the anchor scales. Please check the models and let me know. Any help would be appreciated.

**Comment by MeghaGhosh** [comment]
Hi @amahendrakar any update? A bit tight on time, and we have tried passing the input image in various ways and we keep getting the same values repeated in the output. I'm pretty sure the third output tensor [1][100][6] should return the bounding boxes, class ID and score, but the values aren't right and keep getting repeated. We have compared the inputs with python and they match.

**Comment by MeghaGhosh** [comment]
Hey I got the outputs correctly.. the image meta values had gotten reversed, also I used the tflite support library for image processing. Getting correct values now. Thank you!
