### ISSUE TITLE
Move Tensorflow Lite packages off of Bintray / JCenter due to deprecation of Bintray

### ISSUE THREAD

**Issue by inthewaves** [tensorflow/tensorflow#46964]
Some Tensorflow packages are on Bintray at https://bintray.com/google/tensorflow, but according to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/, Bintray (and JCenter) will be unavailable on May 1, 2021. Does this affect Tensorflow's usage of Bintray?

Looking at older issues, I saw a comment https://github.com/tensorflow/tensorflow/issues/30348#issuecomment-533239346 that says that Tensorflow is "no longer releasing TensorFlow Mobile Android artifacts on Maven". If the deprecation of Bintray affects Tensorflow, then it would be great if the packages were made available on Maven Central

**Comment by yyoon** [comment]
Thanks for the notice. We are aware of the issue, and planning to host the TFLite Android binaries on a different maven repository somewhere other than JCenter before the actual shutdown.

**Comment by xunkai55** [comment]
Thanks for the remainder. Yes we're investigating this issue and will action later.

**Comment by xunkai55** [comment]
We've already pushed artifacts to Maven Central. Closing it now. For any issues related, Feel free to reopen.
