### ISSUE TITLE
why tensorflow has so much ugly designed api?  be pythonic please...

### ISSUE THREAD

**Issue by pengyuan** [tensorflow/tensorflow#46979]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by AdityaKane2001** [comment]
It is optimized for performance, not for ease of usage. Don't worry, you'll get the hang of it! 😄

**Comment by shatatoy** [comment]
optimized for performance???? Ohhhh ... be pythonic please.

**Comment by Saduf2019** [comment]
@pengyuan 
Please elaborate the issue faced.
