### ISSUE TITLE
Is there a error "DCHECK((ref_.store(0), true));"  of RefCounted::Unref() function.

### ISSUE THREAD

**Issue by wu-yy** [tensorflow/tensorflow#46977]
https://github.com/tensorflow/tensorflow/blob/3db52be7be81a87c623cdeb7f03d3767521c5246/tensorflow/core/lib/core/refcount.h#L103

`DCHECK((ref_.store(0), true));`  shoud convert the ref_'value  to 0. but after run `DCHECK((ref_.store(0), true));`, the ref_'value is still 1.

then, there is a test code：
`#include<iostream>

#include "tensorflow/core/lib/core/refcount.h"

#include "tensorflow/core/platform/test.h"

namespace tensorflow {
namespace core {
namespace {
TEST(RefCountTest, UnRefTest) {
  std::atomic_int_fast32_t ref_(1);
  DCHECK((ref_.store(0), true));
  // CHECK(ref_.load() == 0);   //here's check could not passed.
  std::cout << "ref_value: " <<  ref_.load(std::memory_order_acquire);
}
}
}
}`

Result:
`Running main() from test_main.cc
   [==========] Running 1 test from 1 test suite.
  [----------] Global test environment set-up.
  [----------] 1 test from RefCountTest
  [ RUN      ] RefCountTest.UnRefTest
  ref_value: 1[       OK ] RefCountTest.UnRefTest (0 ms)
  [----------] 1 test from RefCountTest (0 ms total)
 
  [----------] Global test environment tear-down
  [==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.`

**Comment by rthadur** [comment]
cc @jvishnuvardhan

**Comment by rainwoodman** [comment]
The tuple in DCHECK is only evaluated under debug mode. (`#undef NDEBUG`). Could this be the cause of this anomaly?
