### ISSUE TITLE
Can't import reader.py correctly for rnn/ptb/

### ISSUE THREAD

**Issue by fanyangxyz** [tensorflow/tensorflow#4697]
I cloned the code and downloaded the dataset. However when I run 
`python ptb_word_lm.py --data_path=simple-examples/data/ --model small`

it gives the following error message:

Traceback (most recent call last):
  File "ptb_word_lm.py", line 369, in <module>
    tf.app.run()
  File "/Users/fanyang1/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 329, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 93, in __init__
    self.input_data, self.targets = reader.ptb_producer(
**AttributeError: 'module' object has no attribute 'ptb_producer'**

It seems that for some unknown reason, the reader.py file is not imported correctly. 

Is this a python problem or more TensorFlow related problem? 

Thanks!

**Comment by kinni** [comment]
Hi, I bet you have installed the Tensor with the version 0.10.0rc0 (with this url $ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py2-none-any.whl); however you are running the latest version of source code 0.11.0rc0 which has conflict with the compiled tensorflow library version 0.10.0rc0.

Solution, checkout the 0.10.0rc0 version of the source code; or compile the tensorflow package again with the latest source code.

Hope this help.

**Comment by tatatodd** [comment]
@fanyangxyz did the comment from @kinni help?  I suspect the same problem.

**Comment by fanyangxyz** [comment]
@kinni thanks for the comment. However, changing the source code did not help with the import problem.

**Comment by kinni** [comment]
@fanyangxyz, open ptb_word_lm.py and modify the header changing `from tensorflow.models.rnn.ptb import reader` to just `import reader`, there maybe some issue in your environment settings.

I got the same problem, but fix it using the trick above. Hope this help.

**Comment by fanyangxyz** [comment]
@kinni This change solved the import problem. Thanks! 
Could you talk more about the environment settings? I've encountered quite a few import problems before. It would be great if I could pinpoint the cause.

**Comment by javidcf** [comment]
There seems to be some recent changes in the PTB model which are not part of 0.11.0rc0. This include, among other things, interface changes in `tensorflow.models.rnn.ptb.reader`, in particular the `ptb_producer` function, that is not present in 0.11.0rc0. When you do `import tensorflow.models.rnn.ptb.reader` you are importing the PTB `reader` module from your installation, which is not compatible with the current PTB model in `master`; so changing the line to the relative import `import reader` works. Another option would be to checkout the tag 0.11.0rc0 in your cloned git repo.

**Comment by YannanLiu** [comment]
@kinni, I import reader, but it says no module named reader

**Comment by sharod** [comment]
Same problem here YananLiu. Someone pls help !!

**Comment by monkeyMozart** [comment]
change ptb_producer to pt_iterator
