### ISSUE TITLE
How to build tensorflow when making small changes?

### ISSUE THREAD

**Issue by dimitraka** [tensorflow/tensorflow#46972]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory:

I know that I can build tensorflow using the following command:

`bazel build --config=opt -c opt -j 8 //tensorflow/tools/pip_package:build_pip_package`

But this command takes a lot of time and I need to make small changes in the code of tensorflow and check them immediately. How do you build tensorflow while contributing? There must be a faster way.

**Comment by mihaimaruseac** [comment]
Bazel keeps a cache of compilation results. Each incremental change will reuse most of the cache.

You can also compile more granular targets while developing and only at the end build a full pip package and run integration tests.

You don't need to always compile with optimizations on. That takes time.

**Comment by dimitraka** [comment]
How could I find and use those granular targets? Do you have any suggestions? 

Regarding the optimizations, you suggest removing the flags `--config=opt -c opt`, right?

**Comment by mihaimaruseac** [comment]
The `BUILD` file specify all possible BUILD targets. `bazel query 'deps(....)'` can also list what Bazel needs to build before the target inside `deps` can be built.

**Comment by dimitraka** [comment]
Thanks for your response!

After building with the specified targets, in order to run TensorFlow with the new code, do I also have to run the following commands:
`
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-2.3.0-cp38-cp38m-linux_x86_64.whl
`
like when installing from source? Or is it that by just building, the changes should be applied when using TensorFlow?

**Comment by mihaimaruseac** [comment]
You have to fully build the pip package and install it if you want to manually test the code / test the pip package.

But during development you usually only want to run a small unit test.

**Comment by dimitraka** [comment]
I am using the following commands (same to those I used when installing for the first time from source):

```
bazel build -j 16 //tensorflow/tools/pip_package:build_pip_package
`
`
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
`
`
pip install /tmp/tensorflow_pkg/tensorflow-2.3.0-cp38-cp38m-linux_x86_64.whl
`

But when using TensorFlow, I do not see any differences. Do I use the correct commands for building and installing?

**Comment by mihaimaruseac** [comment]
Yes, these are the correct commands. Make sure you are using the right environment, the right python/pip combination.

**Comment by bhack** [comment]
@dimitraka This is a well know issue. You can subscribe or comment about your experience at https://github.com/tensorflow/build/issues/5

**Comment by mohantym** [comment]
Hi @dimitraka !
Although, We can not check integrity of changed repository without "bazel build" , But we can do few unit tests ahead  using "bazel test " command with respective to unit tests (integrate in each component)  for files which were changed in the forked repo.

Please look at the unit tests raised by [elfringham ](https://github.com/tensorflow/tensorflow/issues?q=is%3Aissue+bazel+test+elfringham+author%3Aelfringham+is%3Aopen)for reference to get more context on "bazel test". It does not guarantee though whether build will pass if tests passed  in bazel test.

Feel free to share your thoughts on TF Forum.

Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
