### ISSUE TITLE
ValueError: ssd_mobilenet_v2 is not supported. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [tensorflow/tensorflow#46970]
Hi Folks

From last few days I'm working on generating model file for Object Detection using Tensorflow 2.x. I have gone through so many blogs and github repos etc. etc.

With help of them I am able to generate xml -> csv file then test.record / train.record files.

Links which I had gone through are mentioned below
https://teyou21.medium.com/training-your-object-detection-model-on-tensorflow-part-2-e9e12714bdf
https://www.dlology.com/blog/how-to-train-an-object-detection-model-easy-for-free/
https://medium.com/@marklabinski/installing-tensorflow-object-detection-api-on-windows-10-7a4eb83e1e7b

Now I am at that step where I have to run command to train the record files using label text file.
python train.py --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v2_quantized_300x300_coco.config

But after running this command in PyCharm I am getting error

![ssd_mobilenet_v2](https://user-images.githubusercontent.com/34931349/107122123-d3695200-68bb-11eb-9ea4-80356801a16f.jpeg)

I searched a lot to solve this issue but not able to find any solution

Operating System: Windows 10 64 bit
Python version: 3.7
Tensorflow version : 2.4.1

Please help me if anyone has any solution for this.

**Comment by AdityaKane2001** [comment]
I don't know how to resolve this error, but just one side note. I highly recommend using [TF Hub](https://tfhub.dev/s?module-type=image-object-detection) for pretrained / pre-made model architectures. It makes the process way easier, and ypu can run it locally, on Colab or on Kaggle.

**Comment by ravikyram** [comment]
@Neeraj1108Yadav 

Just to verify did you download the model from this [link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md).Also, refer similar issue #4056 and see if it helps you. Thanks!

**Comment by Neeraj1108Yadav** [comment]
@ravikyram 

I didn't download from your mentioned link

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

But after opening it, I'm confused now which one to download.

**Comment by ravikyram** [comment]
@Neeraj1108Yadav 

You can use your desired model from the list.Eg:(`SSD MobileNet v2 320x320`).Thanks!

**Comment by Neeraj1108Yadav** [comment]
@ravikyram 

I need help here and am so close to generate model file, but I don't know what wrong I am doing.

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

So I am referring above link to train my model and able to generate all files **.pbtxt, test.record, train.record**.  I am at the step where I have to generate a **config file**. As per your suggestions I downloaded the model but the files and folders inside folder  is not matching as per required in mentioned below images

Structure of folder
>  +--ssd_mobilenet_v2_320x320_coco17_tpu-8
   |   pipeline.config
   |   
   +---checkpoint
   |       checkpoint
   |       ckpt-0.data-00000-of-00001
   |       ckpt-0.index
   |       
   \---saved_model
       |   saved_model.pb
       |   
       \---variables
               variables.data-00000-of-00001
               variables.index

Please refer images from the above links

![train_config_one](https://user-images.githubusercontent.com/34931349/107186560-821ba880-6a0a-11eb-8814-75355aefc228.JPG)

![train_config_two](https://user-images.githubusercontent.com/34931349/107186579-8942b680-6a0a-11eb-99ec-ad5d835ebbcf.JPG)

![train_config_three](https://user-images.githubusercontent.com/34931349/107186591-8f389780-6a0a-11eb-8203-e07eba38f725.JPG)

Please help me on this

**Comment by ravikyram** [comment]
@Neeraj1108Yadav 

This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thanks!

**Comment by abhishekbalu** [comment]
@Neeraj1108Yadav 

One of the issues can be you are to train the model using train.py which is a legacy file. Try using model_main_tf2.py if you are using tf2. I had a similar issue when using the train.py file.

**Comment by saidRaiss** [comment]
Hi, @Neeraj1108Yadav can you share your pipeline config file, I think that you set "ssd_mobilenet_v2" as type of your features_extractor. It happened with me, set "ssd_mobilenet_v2_keras" and try again.
model {
```
    ssd {
          ...
          feature_extractor {
                type: 'ssd_mobilenet_v2_keras'
                 ...
           }
          ...
    }
...
}
```

**Comment by HridoyHazard** [comment]
having the same issue even after using tf2 models

**Comment by abdelkarim86** [comment]
même chose
ValueError:  is not supported for tf version 2. See `model_builder.py` for features extractors compatible with different versions of Tensorflow

**Comment by danbbbbb** [comment]
> @ravikyram
> 
> I didn't download from your mentioned link
> 
> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
> 
> But after opening it, I'm confused now which one to download.
Can you tell me which one you pick at last? I have the same problem, and i have tried 'ssd_mobilenet_v2_320x320_coco17_tpu-8',it can't work
