### ISSUE TITLE
Unexpected TFDS Shuffling behavior

### ISSUE THREAD

**Issue by Muennighoff** [tensorflow/tensorflow#46982]
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.shuffle(buffer_size=256)
dataset = dataset.take(1)
print(list(dataset.as_numpy_iterator()))
dataset = dataset.repeat(5)
print(list(dataset.as_numpy_iterator()))

>>> [2]
>>> [1, 2, 3, 3, 2]

Is this on purpose? I was expecting [2, 2, 2, 2, 2], as I would expect the dataset in memory to be replaced with the subset that I took in take(1), rather than now having (I assume) two datasets in memory, the subset dataset + the original dataset.

Thanks =)

**Comment by zhuzilin** [comment]
@Muennighoff 
This is because `repeat` will repeat the processing pipeline before it instead of repeat the output. Therefore each `repeat` will still do the shuffling. You could set the `reshuffle_each_iteration=False` in the shuffle or use `cache` to cache the result.

**Comment by Muennighoff** [comment]
> @Muennighoff
> This is because `repeat` will repeat the processing pipeline before it instead of repeat the output. Therefore each `repeat` will still do the shuffling. You could set the `reshuffle_each_iteration=False` in the shuffle or use `cache` to cache the result.

Oh I see, so the dataset doesn't execute the processing until I actually call it, but just stores the processing operations to be applied?

**Comment by zhuzilin** [comment]
> Oh I see, so the dataset doesn't execute the processing until I actually call it, but just stores the processing operations to be applied?

Exactly. If you have experience with tf1, the dataset functions are just building the graph and the iterators are the ones to run the ops.

**Comment by Muennighoff** [comment]
> > Oh I see, so the dataset doesn't execute the processing until I actually call it, but just stores the processing operations to be applied?
> 
> Exactly. If you have experience with tf1, the dataset functions are just building the graph and the iterators are the ones to run the ops.

That makes sense. Thanks a lot for helping my understanding. Closing this now.
