### ISSUE TITLE
STM32F746NG Hello World LCD Display not working correctly

### ISSUE THREAD

**Issue by mdinoulis** [tensorflow/tensorflow#46984]
@tensorflow/micro

**System information**
- Host OSX10.15.7
- TensorFlow installed with homebrew
- Tensorflow version 2.4.1
- Target platform Arm Mbed OS

**Describe the problem**
After the hello world project has compiled, when I copy the mbed.bin file (177Kb) to the STM32F746NG  the LCD screen just goes white. The program is clearly running because if I run screen /dev/tty.usbmodem403 9600 is can see all the correct values scrolling down my terminal window. Also, the hardware is working correctly as if I install the MBED LCD demo https://ide.mbed.com/compiler/#nav:/DISCO-F746NG_LCDTS_demo it runs fine and both the screen display and the capacitative touch work correctly.

**Comment by ymodak** [comment]
Apologies for the delay in response. Is this still an issue?

**Comment by mdinoulis** [comment]
Hi Yasir,

Yes, this is still an issue. I’ve not been able to resolve the problem.

Best Regards,
Dino



On 4 Mar 2021, at 20:21, Yasir Modak <notifications@github.com> wrote:

﻿

Apologies for the delay in response. Is this still an issue?

**Comment by ymodak** [comment]
Since it appears to be hardware issue, Have you tried posting this question on [ST community](https://community.st.com/s/)?
I found a similar [thread](https://community.st.com/s/question/0D50X00009XkXSgSAN/stm32f429-white-screen-flashing-com-led)

**Comment by mdinoulis** [comment]
Hi Yasir,

The problem doesn’t seem to be hardware related, the display works fine and examples from the ST website (which use a different display library) work fine.

Best Regards,
Dino


On 4 Mar 2021, at 20:27, Yasir Modak <notifications@github.com> wrote:

﻿

Since it appears to be hardware issue, Have you tried posting this question on ST community<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.st.com%2Fs%2F&data=04%7C01%7C%7C4c4f7a0ed3224577c14508d8df4be250%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637504864311693216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PD%2FMnQiXauWNHdZaiCO0YVC2NTGJGltsfvBQ%2Bgg2ceQ%3D&reserved=0>?
I found a similar thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.st.com%2Fs%2Fquestion%2F0D50X00009XkXSgSAN%2Fstm32f429-white-screen-flashing-com-led&data=04%7C01%7C%7C4c4f7a0ed3224577c14508d8df4be250%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637504864311693216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4CRyMuXgB5UnQt51lIAEJOXsnPTkbKKRGyUJaoanYRk%3D&reserved=0>

**Comment by patriklaurell** [comment]
@mdinoulis there have been some recent updates to mbed generation for the hello world example. Is this still an issue with these recently merged changes?
