### ISSUE TITLE
how to find what tensorflow/keras release contains a specific bug fix

### ISSUE THREAD

**Issue by jmm5491** [tensorflow/tensorflow#46987]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

This is related to a known bug (see below in italics), but I'm trying to figure out how to install a version of tf/keras which has the fix.
**System information**
- OS Platform and Distribution -> Ubuntu 20.0.4
- TensorFlow installed from -> docker tensorflow-gpu 
- TensorFlow version: 2.5.0-dev20210204 from docker tensorflow/tensorflow:nightly-gpu
- Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) \n[GCC 8.4.0]
- Installed usinga  Dockerfile to add some required Python libraries to tensorflow-gpu image
- CUDA/cuDNN version:Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
- GPU model and memory: Nvidia RTX 2080 Ti

I'm training a large (millions of parameters) NN to analyze audio files (speech vs. music).  After 28/50 epochs I hit a known bug which is (to my knowledge) fixed already.  I'm not sure how to find out what tf/keras release the fix is in or if my docker image has the fix.  I'm using a docker image since it was recommended as the easiest way to get version compatibility between tf/keras and CUDA. 

This is the bug description and reference to the fix:

_Tensorflow 2.1 Error “when finalizing GeneratorDataset iterator” - a memory leak? #37515

URL: https://github.com/tensorflow/tensorflow/commit/e918c6e6fab5d0005fcde83d57e92b70343d3553
Fixing a memory leak in Keras.
Fixes: #37515
PiperOrigin-RevId: 302568217
Change-Id: I28d0eaf3602fea0461901680df24899f135ce649_

**Comment by amahendrakar** [comment]
@jmm5491,
The error mentioned in [#37515](https://github.com/tensorflow/tensorflow/issues/37515) seems to have been fixed in TensorFlow v2.2, so TensorFlow v2.5 should also work in this case.

In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and the dataset you are using. Thanks!

**Comment by jmm5491** [comment]
I hit this problem when running someone else's github project, so I'm not very familiar with the code.  I'll look into it some more and see what I can do.  It uses a large dataset. FYI, it is this project: https://github.com/qlemaire22/speech-music-detection.

**Comment by jmm5491** [comment]
I can provide a tgz file including the project code and one dataset with which what I run to reproduce the problem.  It's 4Gb compressed.  With slightly more steps (using sox app to convert mp3 files to a series of .wav files, plus .npy files), I can reduce the file size quite a bit.  I'm not sure the best way to get it to you.  I  could upload it to my Google Drive and make it available that way, for example.

**Comment by amahendrakar** [comment]
> I could upload it to my Google Drive and make it available that way, for example.

@jmm5491,
Yes please, you can share the code and the dataset from your Google Drive.

Alternatively, you can also run your code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by jmm5491** [comment]
I tried to reproduce this on Colab using the complete 4Gb dataset, but rather than seeing the symptom described in my original post, the python process hung.  Because of this and the fact that other users don't seem to have this problem, I'm going to assume the problem is in the code I'm using.  This issue can be closed now.  Thanks.
