### ISSUE TITLE
tf.nn.avg_pool/1d/2d/3d outputs NaN if `ksize=0`

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46994]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A:

**Describe the current behavior**
The following APIs output NaN if `ksize=0`
- `tf.nn.avg_pool1d`
- `tf.nn.avg_pool2d`
- `tf.nn.avg_pool3d`
- `tf.nn.avg_pool`

**Describe the expected behavior**
Expect a grace exception message if the input is unexpected(e.g. `ksize=0`) other than a NaN as output

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.nn.avg_pool1d(input=np.ones((1, 1, 1)), ksize=0, strides=1, padding='SAME')
tf.nn.avg_pool2d(input=np.ones((1, 1, 1, 1)), ksize=0, strides=1, padding='SAME')
tf.nn.avg_pool3d(input=np.ones((1, 1, 1, 1, 1)), ksize=0, strides=1, padding='SAME')
tf.nn.avg_pool(input=np.ones((1, 1, 1)), ksize=0, strides=1, padding='SAME')
~~~

The output of `tf.nn.avg_pool1d`
~~~python
<tf.Tensor: shape=(1, 1, 1), dtype=float64, numpy=array([[[nan]]])>
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the error with TF v2.3, TF v2.4 and TF-nightly for `tf.nn.avg_pool1d`, `tf.nn.avg_pool2d` and `tf.nn.avg_pool`. Whereas, `tf.nn.avg_pool3d` throws an error stating `NotFoundError: Could not find device for node: {{node AvgPool3D}}`

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3440b1b620422cd182cbe75a70e75cc1/46994.ipynb). Thanks!

**Comment by ymodak** [comment]
The associated PR is merged and this should be now fixed with tomorrows tf-nightly version. Thanks!
