### ISSUE TITLE
`tf.keras.layers.ELU` and  `tf.keras.layers.LeakyReLU` outputs nan if `alpha=None`

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46993]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.keras.layers.ELU` and  `tf.keras.layers.LeakyReLU` outputs nan if `alpha=None`

**Describe the expected behavior**
expect no nan as output

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
layer = tf.keras.layers.ELU(alpha=None)
out=layer(np.array([-2, 6.]))
print(out)
~~~

Output:
~~~
tf.Tensor([nan  6.], shape=(2,), dtype=float32)
~~~

~~~python
import tensorflow as tf
import numpy as np
layer = tf.keras.layers.LeakyReLU(alpha=None)
out=layer(np.array([-2, 6]))
~~~
Output:
~~~
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([nan,  6.], dtype=float32)>
~~~

Related: #13787

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and tf-nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/cdb1c001d0fc15d73735806bba9a2cbd/untitled522.ipynb).
Thanks!

**Comment by yongtang** [comment]
I think when `alpha=None` is passed a ValueError could be thrown. Added a PR #47017 for the fix.
