### ISSUE TITLE
Integration with blaze ecosystem numba python to llvm compiler?

### ISSUE THREAD

**Issue by datnamer** [tensorflow/tensorflow#47]
Hi Tensorflow team,

Thanks for the open source work! 

I'm always on the lookout to replace lower level work with python code.   I'm therefore really excited about [Numba](https://github.com/numba/numba) a JIT compiler that can turn a subset of pure python syntax into really fast multithreaded compiled code across multiple backends.  There are also other cool projects that provide different abstractions and graph symbolic representations to different data backends.

http://blaze.pydata.org/
https://github.com/libdynd/dynd-python
https://github.com/blaze/blaze

 I don't have any specific use cases in mind (maybe to efface c++ use?), but just wanted to make the team aware.  As a pydata user, I would love to see any  cooperation and synergy between all these amazing projects in the ecosystem.

**Comment by datnamer** [comment]
So I did some digging in the documentation. It would be convenient to be able to write a new op with Numba.

**Comment by MInner** [comment]
letting you guys know that `numba` has recently opensourced their `numbapro` paid library, so everyone can use 'gpu' and 'parallel' targets now! I'd be really excited to see if anyone would use any of those in tensorflow

**Comment by MarkDaoust** [comment]
I think that 'close' belongs over in [tensorflow/skflow #47](https://github.com/tensorflow/skflow/issues/47)

**Comment by martinwicke** [comment]
Oops, sorry.

**Comment by matthew-pickett** [comment]
Our team has recently released a library for python-native TensorFlow operator definition and optimization: [opveclib](https://github.com/opveclib/opveclib). It is not part of the numba ecosystem, but I believe could be an alternative solution to  @datnamer 's desired functionality.

**Comment by aselle** [comment]
Since we have py_func() you can utilize any python numpy based library, so this feature seems addressed. If you have a more targeted feature request, we'd be happy to talk about it. Thanks!
