### ISSUE TITLE
Error in keras.tokenizer.texts_to_sequences

### ISSUE THREAD

**Issue by JafarMansouri** [tensorflow/tensorflow#47004]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When few texts are given to the keras.tokenizer.texts_to_sequences, it can produce the right sequences but when we have loarge number of texts, it produces wrong sequences.

**Describe the expected behavior**
Expect the same "number of non zero values" for few texts and large texts.

In example below, for "few texts", rows 0 and 5 have 2 and 4 non-zero values respectively, but for "texts" that we have many rows (as shown below) for these rows we have 1 and 3 non-zero values (the first 8 rows in "texts" are the same as in "few texts"). These are just two rows. There are many rows like this.

**Standalone code to reproduce the issue**
[samples.txt](https://github.com/tensorflow/tensorflow/files/5942989/samples.txt)

```from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import pickle

few_texts=['product market',
           'business marketing',
           'entrepreneur business',
           'invest money',
           'money invest .',
           'business money investment investing',
           'strategies market .',
           'marketing investment . .']


tokenizer = Tokenizer(num_words=25)
tokenizer.fit_on_texts(few_texts)
sequences = tokenizer.texts_to_sequences(few_texts)
print('sequences:',sequences)
word_index = tokenizer.word_index
data = pad_sequences(sequences, maxlen=25, padding='post')
print('Shape of data tensor:', data.shape)
data
```
sequences: [[7, 3], [1, 4], [8, 1], [5, 2], [2, 5], [1, 2, 6, 9], [10, 3], [4, 6]]
Shape of data tensor: (8, 25)
array([[ 7,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 8,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  6,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

```
with open("samples.txt", "rb") as fp:   
    seed = pickle.load(fp)
texts=seed
len(texts)
```
1000
```
texts[0],texts[1],texts[2],texts[3],texts[4],texts[5],texts[6],texts[7]
```
('product market',
 'business marketing',
 'entrepreneur business',
 'invest money',
 'money invest .',
 'business money investment investing',
 'strategies market .',
 'marketing investment . .')
```
tokenizer = Tokenizer(num_words=25)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
#print('sequences:',sequences)
word_index = tokenizer.word_index
#print('Found %s unique tokens.' % len(word_index))

data = pad_sequences(sequences, maxlen=25, padding='post')
#print(data)
print('Shape of data tensor:', data.shape)

data[0],data[5]
```
Shape of data tensor: (1000, 25)
(array([5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]),
 array([ 1,  3, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]))

**Comment by Saduf2019** [comment]
@JafarMansouri 
The stand alone code seems incomplete to replicate the issue reported, with syntax errors as well.
Please share stand alone code such that we can replicate the issue reported, or a colab gist with code and the error to analyse.

**Comment by JafarMansouri** [comment]
@Saduf2019 I edited

**Comment by Saduf2019** [comment]
I ran the code shared on tf 2.4 and nightly please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e7042dfc76ce20efc2273eadfcd93f38/untitled523.ipynb)

**Comment by around-star** [comment]
@JafarMansouri @Saduf2019 Since you used num_words=25, it would truncate the number of unique words to 25 or keep atmost 25 words (if no. of unique words > 25) from the input dataset based on the word frequencies.
In the 1st dataset, the number of unique words being less than 25 caused no issue.
In the 2nd dataset (samples.txt), the number of unique words are greater than 25. So it filtered out 25 words based on their frequencies and tokenized them. Hence, upon encountering any new word in "text_to_sequence" function, it would return 0 as its tokenized value .

**Comment by JafarMansouri** [comment]
Yes, that was the reason of the error. Thanks.
