### ISSUE TITLE
Import tensorflow -> Illegal instruction

### ISSUE THREAD

**Issue by RarDay** [tensorflow/tensorflow#47002]
System information |  Version
|----------------|---------|
OS Platform | Ubuntu 18.04 LTS
Device | Orange Pi 4
Python version | 3.6
Installed using | pip

Hi everyone!
Find only one work solution for me:
```
pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.8.0-py3-none-any.whl
<...>
Installing collected packages: tensorflow
Successfully installed tensorflow-1.8.0
```
And:
```
orangepi@orangepi4:~$ python3.6.9
>>> import tensorflow
Illegal instruction (core dumped)
```
I am installing version 1.5.0 and the problem persists

**Comment by ravikyram** [comment]
@RarDay 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source#cpu).
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by RarDay** [comment]
@ravikyram Sorry, I don't understand a little how to download "tensorflow-2.4.0" build and run it
I must use doker? CPU or GPU?

**Comment by ravikyram** [comment]
@RarDay 

Please refer this [link](https://hub.docker.com/r/tensorflow/tensorflow/) and see if it helps you. Thanks!

**Comment by RarDay** [comment]
@ravikyram  Can I install tensorflow without docker in python 3.6? I'm using an orange pi and I don't have that much memory and time to constantly install docker

**Comment by ravikyram** [comment]
@RarDay 

You can install Tensorflow from source and using pip.Please, refer this [document.](https://www.tensorflow.org/install).

Building TF on orangepi refer this [document](https://github.com/snowsquizy/tensorflow-on-orange-pi/blob/master/GUIDE.md) and [link](https://poddingue.medium.com/installing-tensorflow-on-the-orange-pi-4b-63428377499cBuilding). Thanks!

**Comment by amahendrakar** [comment]
@RarDay,
Any updates regarding this issue?

Please feel free to close the issue if resolved. Thanks!
