### ISSUE TITLE
`tf.nn.log_poisson_loss` outputs NaN

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#47019]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.nn.log_poisson_loss` outputs NaN if `log_input` and `targets` contain large values

**Describe the expected behavior**
Expect a grace exception message if the input is invalid instead of Nan as output

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.nn.log_poisson_loss(log_input=np.array([1e+38], dtype=np.float32), targets=np.array([1e+38], dtype=np.float32))
~~~
Output:
~~~python
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>
~~~

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/98c7843a6a19d3d28efaff943f99c892/untitled524.ipynb)

**Comment by rjpower** [comment]
This is an expected result from floating point approximation. Checking for NaNs on every operation would result in unacceptable performance degradation and isn't consistent with other floating point libraries.

You can use tf.math.is_nan to check if a result is nan.

**Comment by kkimdev** [comment]
Ideally this should return infinity.  Currently
```
tf.nn.log_poisson_loss(log_input=np.array([100], dtype=np.float32), targets=np.array([100], dtype=np.float32))
tf.Tensor([inf], shape=(1,), dtype=float32)
```
But doesn't seem like a high priority and contributions welcome!

**Comment by AdityaKane2001** [comment]
@kkimdev 
What is the expected output that we are looking for here?

**Comment by mohantym** [comment]
Hi @DNXie  @kkimdev !checked this issue is give "inf" output when compiled with float64  (used tensor instead of numpy array ) providing [gist ](https://colab.research.google.com/gist/mohantym/cc05b28af3fee349917513a55ccc2908/untitled524.ipynb#scrollTo=HRA_hmkgVC4J)for reference
