### ISSUE TITLE
TPU, model.fit : 2GB of RAM limit. tf.version 2.4

### ISSUE THREAD

**Issue by agsci2017** [tensorflow/tensorflow#47026]
**Describe the current behavior**

There is an error (""Session crashed for unknown reason""), when trying to use a dataset with the size more than 2GB of RAM.
Error is reproducible for different step size (256,1024,8192).

**Describe the expected behavior**

No error when feeding a dataset which is more than 2GB of RAM.

**Code to reproduce the issue**

To reproduce, just copy the following code to Colab with TPU enabled.

The bug can happen due to 2GB limit in protobuf (since tensorflow relies on it).
https://stackoverflow.com/questions/34128872/google-protobuf-maximum-size

```
import tensorflow as tf
import numpy as np

import distutils
if distutils.version.LooseVersion(tf.__version__) < '1.14':
    raise Exception('This notebook is compatible with TensorFlow 1.14 or higher, for TensorFlow 1.13 or lower please use the previous version at https://github.com/tensorflow/tpu/blob/r1.13/tools/colab/fashion_mnist.ipynb')

import os

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
# This is the TPU initialization code that has to be at the beginning.
tf.tpu.experimental.initialize_tpu_system(resolver)
print("All devices: ", tf.config.list_logical_devices('TPU'))

# optimizer = tf.tpu.CrossShardOptimizer(tf.train.GradientDescentOptimizer(0.01))

strategy = tf.distribute.TPUStrategy(resolver)

with strategy.scope():
  model = tf.keras.applications.VGG16(input_shape=(32,32,3),classes=10, weights=None)#  create_model()
  optimizer = tf.keras.optimizers.Adam()
  model.compile(
      optimizer=optimizer,
      loss='mse',
      metrics=['mse'])
  
  training_loss = tf.keras.metrics.Mean('training_loss', dtype=tf.float32)
  training_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      'training_accuracy', dtype=tf.float32)


# 1024*192 * 32*32*3 * 4bytes = 2 415 919 104 bytes
# ~ 2GB. "Session crashed for unknown reason"
X = np.zeros((1024*192, 32,32,3),dtype=np.float32)
y = np.ones((1024*192, 10),dtype=np.float32)

# ~ 1GB. Works
# X = np.zeros((1024*192//2, 32,32,3),dtype=np.float32)
# y = np.ones((1024*192//2, 10),dtype=np.float32)

model.fit(
    X,y,
    epochs=10,
    steps_per_epoch=1024, #batch size is 192 per TPU
)
```
```
print(tf.version.VERSION)
print(tf.version.GIT_VERSION)
2.4.1
v2.4.1-0-g85c8b2a817f
```

**Logs**
![106828116-a4958500-66dd-11eb-9ae6-06606e561bc4](https://user-images.githubusercontent.com/27484172/107322586-d735e800-6af8-11eb-9be7-5035a2bda197.png)

**Comment by hthu** [comment]
This looks like pretty much the same one you filed a while back:

https://github.com/tensorflow/tpu/issues/533

Nothing in particular has changed yet -- the large numpy tenosr is pushing the rpc to 2GB boundary.

You could try wrap it up with tf.dataset.from_tensors or from_tensor_slices to feed data in a smaller batch fashion.
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_tensors
