### ISSUE TITLE
tf.strings.split cannot handle some characters

### ISSUE THREAD

**Issue by princyok** [tensorflow/tensorflow#47022]
**System information**
- OS Platform: Windows 10
- TensorFlow version: 2.3.2
- Python version: 3.8.5

**Issue**
This code:
````
print(tf.strings.split(tf.constant(["abc à cc"])))
````
produces this:
````
<tf.RaggedTensor [[b'abc', b'\xc3']]>
````
Python split works just fine:
````
print("abc à cc".split(" "))
````
and prints:
````
['abc', 'à', 'cc']
````
This is what I suspect is the problem: this code `"à".encode() ` prints `b'\xc3\xa0'`. This byte literal `\xa0` is the nonbreaking space character (codepoint 160 in UTF-16 and UTF-32).

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3c84e607809e252bd2553092599c11e8/untitled524.ipynb).

**Comment by princyok** [comment]
@Saduf2019 
The gist you linked above shows that it's working fine on colab in 2.4 and nightly. I think you got confused by the byte literals (string tensors hold strings as bytes instead of unicode strings), but that's not a bug to the best of my knowledge. This is likely a problem that occurs with tensorflow only on Windows, because this issue is related to [this other issue](https://github.com/tensorflow/tensorflow/issues/43559). 

In fact, I was running into that issue again (the issue linked above), so I tried to get to the root cause and discovered that this orphan byte literal `b'\xc3'` (sometimes `b'\xc2'` too) is created during splitting (you can find [my comment](https://github.com/tensorflow/tensorflow/issues/43559#issuecomment-762510624) on that issue as well). I thought it's better to report the isolated root problem.

But note that this can't be simply dismissed as a Windows or python problem since the regular python split works without any issues.

**Comment by princyok** [comment]
@ @ #43559

**Comment by saikumarchalla** [comment]
@princyok  Yeah the code is working fine on colab and  will let you know the update once we fix it. Thanks!

**Comment by duvallj** [comment]
I can reproduce this issue on Windows 10, Python 3.8.7, Tensorflow 2.6.0:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.strings.split("verità truth").numpy()
array([b'verit\xc3'], dtype=object)
>>> tf.strings.split("verita truth").numpy()
array([b'verita', b'truth'], dtype=object)
>>> tf.__version__
'2.6.0'
>>>
```

**Comment by duvallj** [comment]
Tracing back how `tf.strings.split` is actually implemented, it would seem the error is in https://github.com/abseil/abseil-cpp/blob/master/absl/strings/str_split.h possibly? At least that's what I can make out from reading https://github.com/tensorflow/tensorflow/blob/556c3a9c41ce0590c12390a0d2fb90af7e035f0a/tensorflow/core/ops/BUILD#L122-L132 and https://github.com/tensorflow/tensorflow/blob/556c3a9c41ce0590c12390a0d2fb90af7e035f0a/tensorflow/core/ops/string_ops.cc#L19

**Comment by duvallj** [comment]
Nevermind, I am new to tensorflow and didn't know where the kernels are actually implemented. This op is implemented at https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/string_split_op.cc#L102-L158, and notably it's just the implicit delimiter version that's broken:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.strings.split(["verità truth"], ' ')
<tf.RaggedTensor [[b'verit\xc3\xa0', b'truth']]>
>>> tf.strings.split(["verità truth"])
<tf.RaggedTensor [[b'verit\xc3']]>
>>>
```
The correctness of that algorithm seems to depend on https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/platform/str_util.cc#L88-L105, which in turn depends on a valid `isspace` function. Both absl and std have ones that work (I checked by compiling a small example), so it really is confusing why this is an issue in the first place.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220719. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8d7a7e75568d4d5e517b55441669bff4/untitled524.ipynb). Thank you!

**Comment by tilakrayal** [comment]
@princyok,
I tried to execute the code multiple times on both colab and the VM with different examples and it was executed as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/29ae1afb882ac8270ce15774f9cbedde/untitled524.ipynb). 
Also please have a look at the below comment for the reference.
https://github.com/tensorflow/tensorflow/issues/43559#issuecomment-886728179


![image](https://user-images.githubusercontent.com/81610181/235133228-00f711c4-d7c0-4347-a6a9-b07aad904efc.png)
![Screenshot 2023-04-28 4 44 10 PM](https://user-images.githubusercontent.com/81610181/235133459-88763f03-5ee1-4577-bb21-cbd97721f5ea.png)

**Comment by mihaimaruseac** [comment]
The issue seems solved then
