### ISSUE TITLE
INFO:tensorflow:Saver not created because there are no variables in the graph to restore

### ISSUE THREAD

**Issue by knightperfectionist** [tensorflow/tensorflow#47029]
I am using
bert-tensorflow==1.0.1
tensorflow version = 2.4.1
keras - 2.4.3

Code
BERT_MODEL_HUB = "https://tfhub.dev/google/bert_cased_L-12_H-768_A-12/1"

def create_tokenizer_from_hub_module():
"""Get the vocab file and casing info from the Hub module."""
with tf.Graph().as_default():
bert_module = hub.Module(BERT_MODEL_HUB)
tokenization_info = bert_module(signature="tokenization_info", as_dict=True)
with tf.Session() as sess:
vocab_file, do_lower_case = sess.run([tokenization_info["vocab_file"],
tokenization_info["do_lower_case"]])

return bert.tokenization.FullTokenizer(
vocab_file=vocab_file, do_lower_case=do_lower_case)

tokenizer = create_tokenizer_from_hub_module()

After running above cell in Colab I'm getting the following msg

INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Saver not created because there are no variables in the graph to restore

**Comment by Saduf2019** [comment]
@knightperfectionist 
Can you check this link and let us know: [link](https://stackoverflow.com/questions/46104525/how-to-restore-a-partial-graph-in-tensorflow)
