### ISSUE TITLE
post_training_integer_quantization issue

### ISSUE THREAD

**Issue by Paryavi** [tensorflow/tensorflow#47027]
I used a simple transfer learning code on my windows computer, downloading the cat-dog dataset.
The transfer learning and conversion to TFLite sections are OK, but I can't convert the input to int8 from float 32 following TF guidline.

**My Code;**
https://colab.research.google.com/drive/1hlTykr4-rUYqI-n10icVEywxUhyar364

**The Guide to do the conversion;**
https://www.tensorflow.org/lite/performance/post_training_integer_quant

**Issue**; ValueError: Unbatching a dataset is only supported for rank >= 1

Thanks in advance for your help,
MoZen

**Comment by amahendrakar** [comment]
@Paryavi,
I do not have access to the Colab notebook you have linked. Could you please provide the required permissions to view the files. Thanks!

**Comment by Paryavi** [comment]
@amahendrakar  and @abattery 
Thank you, here is the link; https://colab.research.google.com/drive/1hlTykr4-rUYqI-n10icVEywxUhyar364?usp=sharing

**Comment by abattery** [comment]
Hi Paryavi,

train_dataset is already a dataset in TF. You don't need to re-insert into the tf.dataset API

```
def representative_data_gen():
  for input_value in train_dataset.batch(1).take(100):
    # Model has only one input so each data point has one element.
```

However, you need to preprocess the data from dataset correctly to feed the correct input value.

If you can rely on the conversion without the representative dataset like the below one and I verified that it is working with your colab:
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
#converter.representative_dataset = representative_data_gen

tflite_model_quant = converter.convert()
```

**Comment by abattery** [comment]
For int8 input and output type overriding in the target model, you can use the following code snippet but you need a representative_data_gen method.

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8

tflite_model_quant = converter.convert()
```

**Comment by Paryavi** [comment]
Hi, @abattery and @amahendrakar,
Thanks for your time,
I modified the code to get the images from the URL and added the code snippet. Still, it has the error. It's quantized but not with int8 input.
Colab link again; https://colab.research.google.com/drive/1hlTykr4-rUYqI-n10icVEywxUhyar364?usp=sharing

**Comment by amahendrakar** [comment]
@Paryavi,
On running the Colab notebook, I see that the input and output are `int8`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/60de6ba4bb568f813987d23f46c295a8/47027.ipynb#scrollTo=zMByxhf97oVQ&line=4&uniqifier=1). Thanks!

**Comment by Paryavi** [comment]
Thanks, @amahendrakar, Yes I was able to fix it using @abattery help. Thank you both!
