### ISSUE TITLE
text_dataset_from_directory doesn't work if there isn't at least one subdirectory

### ISSUE THREAD

**Issue by princyok** [tensorflow/tensorflow#47021]
**System information**
- OS Platform: Windows 10
- TensorFlow version: 2.3.2
- Python version: 3.8.5

**Issue**
`tf.keras.preprocessing.text_dataset_from_directory` doesn't work if you have a directory structure like this:

data_dir/
--text_1.txt
--text_2.txt
--text_3.txt
````
ds = tf.keras.preprocessing.text_dataset_from_directory(
    data_dir, labels=[0,0,1], label_mode="int", 
    batch_size=NUM_FILES_PER_TENSOR, validation_split=None, 
    subset=None, shuffle=False, seed=seed
)
````
According to the documentation, the above should work since "inferred" is not passed to the `labels` argument. But instead you get this error:

````
ValueError: Expected the lengths of `labels` to match the number of files in the target directory. len(labels) is 3 while we found 0 files
````

But if you change the structure to this and run the exact same code, it works:

data_dir/
--dummy/
----text_1.txt
----text_2.txt
----text_3.txt

Even worse is that the labels you passed are simply ignored. It prints this message: `Found 3 files belonging to 1 classes`. It feels like the "inferred" option (which is the default) was properly implemented and the rest are broken.

**Comment by ravikyram** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly(`2.5.0-dev20210208`). Please find the gist of it [here](https://colab.research.google.com/gist/ravikyram/e15a8f99bee2ca0b1103c675e526ea66/untitled666.ipynb). Thanks!

**Comment by amahendrakar** [comment]
@princyok,
I was able to run the code without any issues by passing the the parent directory as the `directory` argument, instead of `data_dir`.

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2a5feff0651cd748e9129eab69d68069/47021.ipynb). Thanks!

**Comment by princyok** [comment]
@amahendrakar 

That's exactly the problem, just as the title says. It leads to other issues as explained in the main post above.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5 ,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/a9d04923f81d685319797d29f504e794/untitled159.ipynb?authuser=1)..Thanks !

**Comment by ymodak** [comment]
Thanks for your issue. I think this is working as intended. 
The directory structure is expected to like - 
```python
main_directory/
...class_a/
......a_text_1.txt
......a_text_2.txt
...class_b/
......b_text_1.txt
......b_text_2.txt
```
See https://www.tensorflow.org/api_docs/python/tf/keras/utils/text_dataset_from_directory#used-in-the-notebooks
Thanks!
