### ISSUE TITLE
tf.nn.embedding_lookup outputs NaN

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#47020]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.nn.embedding_lookup` outputs NaN if `params` is large value

**Describe the expected behavior**
Expect a grace exception message if the input is invalid instead of Nan as output

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.nn.embedding_lookup(params=np.array([1e+38, 1e+38],dtype=np.float32), ids=1, max_norm=10)
~~~

Output:
~~~python
<tf.Tensor: shape=(), dtype=float32, numpy=nan>
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5274acb10c36e926ce950dde22f4e5fc/47020.ipynb). Thanks!

**Comment by rjpower** [comment]
This is expected floating point behavior. TensorFlow does not guarantee that floating point approximations will not result in NaN values, in line with other numerical toolkits. You can use `tf.math.is_nan` to check for NaN values.
