### ISSUE TITLE
gradient computation fails in graph mode with numpy_function

### ISSUE THREAD

**Issue by akkiss** [tensorflow/tensorflow#47033]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (conda-forge)
- TensorFlow version (use command below): 'v2.3.0-rc2-23-gb36436b087', 'v2.4.0-49-g85c8b2a817f'
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Titan RTX 24GB

**Describe the current behavior**

I'm trying to use a function implemented in cython in a loss function. The (int64) output of this function is used as index for tf.gather. When computing the loss in eager execution mode gradients are computed fine, but when run in graph mode, an exception is raised.

**Describe the expected behavior**

I would expect the same result in graph execution mode.

**Standalone code to reproduce the issue**

A tiny sample where the cython function simply implements argmin:

```
import tensorflow as tf
import numpy as np
import assign

model = tf.keras.applications.ResNet50(False, weights=None, input_shape=(224, 224, 3))
data = tf.random.normal((8,224,224,3), 128, 64)

def f(x):
	y = model(x)
	idx = tf.numpy_function(assign.assign_objects_to_cells, (-y,), np.int64)
	#idx = tf.argmin(-y, -1)
	#idx = tf.numpy_function(np.argmin, (-y, -1), np.int64)
	values = tf.gather(y, idx, batch_dims=3)
	return tf.reduce_sum(values)


def grad(x):
	with tf.GradientTape() as tape:
		y = f(x)
	return tape.gradient(y, model.trainable_variables)
tf_grad = tf.function(grad)

print('eager execution')
g = grad(data)
print('graph execution')
g = tf_grad(data)
```

And the **assign.pyx**:

```
import numpy as np
cimport numpy as np
cimport cython

@cython.boundscheck(False) # turn off bounds-checking for entire function
@cython.wraparound(False)  # turn off negative index wrapping for entire function
cdef void _assign_objects_to_cells(float[:,:,:,:] error, np.int64_t[:,:,:] argmax) nogil:
	cdef int N = error.shape[0], H = error.shape[1], W = error.shape[2], C = error.shape[3]
	cdef int y, x, c, best_id
	cdef float best, e
	
	for n in range(N):
		for y in range(H):
			for x in range(W):
				best_id = 0
				best = error[n,y,x,0]
				for c in range(1, C):
					e = error[n,y,x,c]
					if e<best:
						best = e
						best_id = c
				argmax[n,y,x] = best_id

def assign_objects_to_cells(np.ndarray[np.float32_t, ndim=4] error not None):
	cdef int N = error.shape[0], H = error.shape[1], W = error.shape[2], C = error.shape[3]
	out = np.empty((N,H,W), np.int64)
	_assign_objects_to_cells(error, out)
	
	return out
```

**Other info / logs** 

Eager execution runs fine, but graph execution fails:

```
eager execution
graph execution
Traceback (most recent call last):

  File "<ipython-input-1-eafa53e19dc9>", line 25, in <module>
    g = tf_grad(data)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)

  File "d:\conda\envs\tf2\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)

TypeError: in user code:

    <ipython-input-1-eafa53e19dc9>:19 grad  *
        return tape.gradient(y, model.trainable_variables)
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\backprop.py:1073 gradient  **
        unconnected_gradients=unconnected_gradients)
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\eager\backprop.py:162 _gradient_function
        return grad_fn(mock_op, *out_grads)
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\ops\array_grad.py:678 _GatherV2Grad
        batch_dims, params_shape[axis])
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\ops\array_grad.py:603 _BatchGatherGrad
        indices = _GetBatchIndices(params_shape, indices, batch_dims)
    d:\conda\envs\tf2\lib\site-packages\tensorflow\python\ops\array_grad.py:582 _GetBatchIndices
        [1] * (dim - 1) + [dim_value] + [1] * (indices_ndims - dim), axis=0)

    TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Note, that both eager and graph modes work if I replace tf.numpy_function with tf.argmin and the results are the same (up to rounding errors). Graph execution also fails when using np.argmin.

**Comment by ravikyram** [comment]
@akkiss 

I have tried in colab with TF -GPU version 2.4 and i am seeing the below error message.(`AttributeError: module 'assign' has no attribute 'assign_objects_to_cells'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/13dd352805733aebbebab17bae61c4c8/untitled668.ipynb).
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by akkiss** [comment]
Assign is not a library but a cython function (the "And the assign.pyx:" part). This is not required anyway, the problem appears with np.argmin as well. Unfortunately I cannot make my colab public, but this code reproduced the problem:

```
!pip install tensorflow-gpu==2.4.0

import tensorflow as tf
import numpy as np
#import assign

model = tf.keras.applications.ResNet50(False, weights=None, input_shape=(224, 224, 3))
data = tf.random.normal((8,224,224,3), 128, 64)

def f(x):
	y = model(x)
	#idx = tf.numpy_function(assign.assign_objects_to_cells, (-y,), np.int64)
	#idx = tf.argmin(-y, -1)
	idx = tf.numpy_function(np.argmin, (-y, -1), np.int64)
	values = tf.gather(y, idx, batch_dims=3)
	return tf.reduce_sum(values)


def grad(x):
	with tf.GradientTape() as tape:
		y = f(x)
	return tape.gradient(y, model.trainable_variables)
tf_grad = tf.function(grad)

print('eager execution')
g = grad(data)
print('graph execution')
g = tf_grad(data)
```

**Comment by foxik** [comment]
The problem is that `tf.numpy_functions` returns completely undefined static shape; i.e.,
```python
  print(idx.shape)
```
returns `(8, 7, 7)` in Eager mode, but `<unknown>' in Graph mode (i.e., not even the rank of the result is known). This behaviour is expected (it would be difficult to perform some static analysis of the resulting shape).

What you can do is to provide the information about the output shape (and then check at runtime that it holds). You can do so quite easily by using the following just after `idx = tf.numpy_function(np.argmin, (-y, -1), np.int64)`:
```python
  idx = tf.ensure_shape(idx, y.shape[:-1])
```
The `idx` has the same value, but it has the same static shape as `y`, apart from the last dimension (which is eradicated by the `np.argmin`); the `tf.ensure_shape` even checks at runtime that the dynamic shape matches.

**Comment by foxik** [comment]
BTW, the gist with the added line: https://colab.research.google.com/drive/1iOwlwiETazXwkHt0SvNgZP29KOXKDjQg?usp=sharing

**Comment by akkiss** [comment]
OMG, so obvious, how did I not think of this... Thanks @foxik for the solution.

If someone ever reads this might be happy to hear this works also with variable tensor shapes:
```
idx = tf.ensure_shape(idx, 3*[None])
```
