### ISSUE TITLE
SIGSEGV - error when using large convolution - GPU

### ISSUE THREAD

**Issue by Emilon1928** [tensorflow/tensorflow#47036]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04, Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): anaconda
- TensorFlow version (use command below): 2.2.0-rc3 and Colab Version
- Python version: 3.7 Colab
- CUDA/cuDNN version: 11.2, Colab
- GPU model and memory: 2080Ti, Colab

**Describe the expected behavior**

The script should generate a map of random values, smoothed with a Gauss filter. For the value sigma = 60 everything works fine, above this value the error "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)" is returned. I got the same error on different workstations and also on colab. 

The problem only occurs when using the GPU.
**Standalone code to reproduce the issue**
```
import tensorflow as tf
from matplotlib import pyplot as plt

random_mask = tf.random.uniform((1, 400, 400, 1),
                                        minval=-1,
                                        maxval=1,
                                        dtype=tf.float32)

sigma = 61
sigmas_per_radius = 3
radius = tf.cast(sigma * sigmas_per_radius, tf.int32)

x = tf.cast(tf.range(-radius, radius + 1),dtype=tf.float32)

gauss_1d = tf.exp(-0.5 * tf.square(x / sigma))
gauss_1d = gauss_1d / tf.reduce_sum(gauss_1d)

kernel = tf.expand_dims(gauss_1d, 1) * gauss_1d
kernel = kernel[..., tf.newaxis, tf.newaxis]

point_wise_filter = tf.eye(1, batch_shape=[1, 1])

def_map = tf.nn.separable_conv2d(
    random_mask,
    kernel,
    point_wise_filter,
    strides=[1, 1, 1, 1],
    padding='SAME'
)

def_map = tf.squeeze(def_map)

plt.imshow(def_map.numpy())
plt.show()

```

**Comment by ravikyram** [comment]
I have tried in colab with TF-GPU version 2.4 and i am not seeing any issue. Please. find the gist [here](https://colab.research.google.com/gist/ravikyram/fd8d3bb4c9fc82f592c951273ea7e9aa/untitled667.ipynb). Thanks!

**Comment by Emilon1928** [comment]
I am using the default tensorflow library from Colab, this is 2.4.1. Can you check it ? 
(https://colab.research.google.com/drive/1YqnLaeWm_1EXw9PAnOf90tlcDy6PoF6H?usp=sharing)

**Comment by ravikyram** [comment]
I am not seeing any  issue in colab with TF-GPU version 2.4.1. Please,find the gist [here](https://colab.research.google.com/gist/ravikyram/4980c9d435449e7b27ed8552c659685c/untitled669.ipynb).
Please,verify once and close this issue.Thanks!

**Comment by Emilon1928** [comment]
Can you check it again without installing another version of tensorflow than the one on the colab? I asked some of my friends about verification and they all confirm the error. Please try to do the same as on the notebook I provided. Without installing the new library :)

**Comment by amahendrakar** [comment]
> I am using the default tensorflow library from Colab, this is 2.4.1. Can you check it ?
> (https://colab.research.google.com/drive/1YqnLaeWm_1EXw9PAnOf90tlcDy6PoF6H?usp=sharing)

@Emilon1928,
On running the Colab notebook you have provided, I did not face issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6007f14d3e178781a1cc48eb90002d08/untitled2.ipynb). Thanks!
