### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib' -->> alterative

### ISSUE THREAD

**Issue by knightperfectionist** [tensorflow/tensorflow#47038]
**I want alternative for the following code in TF2**

tf.contrib.cloud.configure_gcs(session, credentials=auth_info)

**Comment by amahendrakar** [comment]
@knightperfectionist,
Could you please provide a minimal code snippet of the use-case you're trying to implement, so that we can look into this. Thanks!

**Comment by knightperfectionist** [comment]
> @knightperfectionist,
> Could you please provide a minimal code snippet of the use-case you're trying to implement, so that we can look into this. Thanks!

import datetime
import json
import os
import pprint
import random
import string
import sys
import tensorflow as tf

assert 'COLAB_TPU_ADDR' in os.environ, 'ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!'
TPU_ADDRESS = 'grpc://' + os.environ['COLAB_TPU_ADDR']
print('TPU address is', TPU_ADDRESS)

from google.colab import auth
auth.authenticate_user()
with tf.Session(TPU_ADDRESS) as session:
  print('TPU devices:')
  pprint.pprint(session.list_devices())

  # Upload credentials to TPU.
  with open('/content/adc.json', 'r') as f:
    auth_info = json.load(f)
  tf.contrib.cloud.configure_gcs(session, credentials=auth_info)
  # Now credentials are set for all future sessions on this TPU.


It's a compatibility issue of v1 and v2. The notebook needs to be updated it seems.
