### ISSUE TITLE
TF 2.4.1 with python 3.8.7 (apple silicon with rosetta) terminated by SIGILL on import

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#47041]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.2
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.7 (x86_64 through Rosetta)

**Describe the current behavior**
I am using a fish shell via Rosetta (`uname -m` gives me x86_64) and I could import TF without any problems.
After the 11.1 -> 11.2 Big Sur update, I can no longer import TensorFlow. I have no idea why.

**Describe the expected behavior**
no crash

**Standalone code to reproduce the issue**
just import tensorflow:

```bash
Python 3.8.7 (default, Feb  3 2021, 07:09:08)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
fish: 'python' terminated by signal SIGILL (Illegal instruction)
```

**Comment by faroit** [comment]
> @ziofil,
> 
> Can you try to install the latest stable version of tensorflow i.e `2.6.0` and lets us know if the issue still persists. You can follow this [guide](https://www.tensorflow.org/install/source) to build from source. Thanks!

the issue is still relevant

**Comment by faroit** [comment]
@ziofil please reopen

**Comment by mohantym** [comment]
Hi @ziofil ! Could you uninstall previous Tensorflow versions and try with instructions in this links [1](https://developer.apple.com/metal/tensorflow-plugin/),[ 2](https://github.com/tensorflow/tensorflow/issues/51506#issuecomment-901460541) . Attaching relevant [thread](https://github.com/tensorflow/tensorflow/issues/8976#issuecomment-299663626) for reference. Thank you!

**Comment by mihaimaruseac** [comment]
Please try TF 2.10.
