### ISSUE TITLE
Error when Building Tensorflow 2.4/2.4.1 for C++ with cuda support

### ISSUE THREAD

**Issue by daschuchmann** [tensorflow/tensorflow#47042]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0 / 2.4.1
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.0 /8.0.5.39
- GPU model and memory: Nvidia GTX 1070

**Describe the problem**

When building tenmsorflow for C++ with gpu support the build failed with the following error:
![grafik](https://user-images.githubusercontent.com/78606066/107390473-0730bb80-6af8-11eb-8454-3b651682eb16.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I first cloned the repository and switched to branch r2.4

after that i configured with configure.py.

![grafik](https://user-images.githubusercontent.com/78606066/107390779-537bfb80-6af8-11eb-8f62-bc4ca3d7b297.png)

then I started the build with bazel:

`bazel build --config=opt --config=cuda tensorflow:tensorflow.dll`

It ended up with the error above.

**Any other info / logs**

Building without cuda support works just fine

I dont know where the error is maybe its me maybe Tensorflow. I hope i can get some Help here. It would be great if the Tensorflow Site would have a proper instruction. I had to make a long journey to get to the point of where i am here with building.

**Comment by Saduf2019** [comment]
@daschuchmann 
please share error logs as text, it would be easy for us and any user to search for the error.
Also you may refer to : [link](https://github.com/tensorflow/tensorflow/issues/24549#issuecomment-454464310), [link1](https://github.com/tensorflow/tensorflow/issues/11859#issuecomment-475044408), [link2](https://stackoverflow.com/questions/57503584/cannot-build-the-tensorflow-c-api-in-windows)

**Comment by daschuchmann** [comment]
@Saduf2019 thank you solved it. I havent set the environment to mysys. After setting the environment to mysys it started building successfully. In future issues I will share the logs as text.

**Comment by Saduf2019** [comment]
@daschuchmann
Tahnk you for your update, glad we could help.
