### ISSUE TITLE
Allow cloning of tf.keras.Model subclass

### ISSUE THREAD

**Issue by Lucianod28** [tensorflow/tensorflow#47048]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
As far as I know, there is no way to clone a class-based model currently. For functional models, we have `tf.keras.models.clone_model`, but this doesn't work for subclasses of `tf.keras.Model`. For example, if I define some model like so:
```python
class MySequentialModel(tf.keras.Model):
    def __init__(self, name=None, **kwargs):
        super().__init__(**kwargs)
        self.dense_1 = FlexibleDense(out_features=3)
        self.dense_2 = FlexibleDense(out_features=2)

    def call(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)
```
Then train, save and load the model, when I try to clone it like this:
```model = tf.keras.models.clone_model(loaded_model)```
I get:
```ValueError: Expected `model` argument to be a functional `Model` instance, but got a subclass model instead.```
Is there another way to do this or am I missing something?
**Will this change the current api? How?**
Not really, you'd just be allowing an additional input type in the `tf.keras.models.clone_model` function.
**Who will benefit with this feature?**
People who want to clone class-based models.

**Comment by emadboctorx** [comment]
Why is this issue closed? I'm facing the same problem, is there some solution?

**Comment by rmothukuru** [comment]
@emadboctorx,
This is not the issue that is closed.

**Comment by emadboctorx** [comment]
@rmothukuru yeah, I just noticed. Both issues are addressing the same topic anyway.

**Comment by gcunhase** [comment]
Any updates on this? Also facing the same issue.

**Comment by mychina75** [comment]
tried 2.6 version but not solved...
waiting for a solution...

**Comment by galenseilis** [comment]
Indeed, I am also facing this issue, even after ensuring that I build the model.

**Comment by git-elliot** [comment]
issue is still there, any updates?

**Comment by mohantym** [comment]
@Lucianod28 ! It is still replicating in [2.8](https://colab.sandbox.google.com/gist/mohantym/313d5ffc85b215b1d23d927bb23f92d0/github_47048.ipynb#scrollTo=5Ds8QUcrZ56q) version. Could you please post this on Keras repo and close the feature request here?

**Comment by jamesbraza** [comment]
> Could you please post this on [Keras](https://github.com/keras-team/keras/issues) repo and close the feature request here?

I am hitting this issue today, and saw it's pending the request to be cloned to the Keras repo.  As requested, @mohantym @Lucianod28 I have completed the cloning of the issue to https://github.com/keras-team/keras/issues/17261.  Hopefully someone addresses it in Keras repo, as I think this is a great feature request.

**Comment by mohantym** [comment]
@jamesbraza !
Thanks for putting the respective Keras Tracker here . We have already let the concerned team know about it.
Thank you!
