### ISSUE TITLE
"no checkpoint found" tensorboard projector

### ISSUE THREAD

**Issue by AnnBkrv** [tensorflow/tensorflow#47049]
I want to load a custom embedding file and a metadata file into tensorboard's projector plugin. I've been following this tutorial mostly: https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin. I get the "no checkpoint found" error in spite of the checkpoint files being present in the folder. I also have used tensorboard's inspect function on the log directory and tensorboard can't find any event files. Here's my code:

`import os
from tensorboard.plugins import projector
import pandas as pd
import tensorflow as tf

weights = pd.read_csv ("test/vectors_test.tsv", sep = '\t')

log_dir = "test/logs/"
weights = tf.Variable(weights)
checkpoint = tf.train.Checkpoint(embedding=weights)
checkpoint.save(os.path.join(log_dir, "embedding.ckpt"))

# Set up config
config = projector.ProjectorConfig()
config.model_checkpoint_path = os.path.join(log_dir, "embedding.ckpt")
embedding = config.embeddings.add()
embedding.tensor_name = "embedding/.ATTRIBUTES/VARIABLE_VALUE"
embedding.metadata_path = "test/metadata_test.tsv"
projector.visualize_embeddings(log_dir, config)

%load_ext tensorboard

%tensorboard --logdir test/logs/ --host localhost --port=1003
%tensorboard --inspect --logdir test/logs
`

**Comment by ravikyram** [comment]
@AnnBkrv 

This issue is more suitable for Tensorboard repo. Please post it on Tensorboard repo from [here](https://github.com/tensorflow/tensorboard/issues/new/choose). Thanks!
