### ISSUE TITLE
Steps to build dynamic libraries of tflite for raspberry pi and aarch 64(armv8) boards

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#47059]
I have downloaded tensorflow source github and try to create tensorflow lite library from tools/ make makefiles.
I have not found steps to build and generate dynamic tfLite library for these hardware devices. Could You provide me the steps to build dynamic .so for tfLite library

**Comment by amahendrakar** [comment]
@pranathibl,
Please take a look at these links to build TensorFlow Lite for [Raspberry Pi](https://www.tensorflow.org/lite/guide/build_rpi) and [ARM64 boards](https://www.tensorflow.org/lite/guide/build_arm64) and let us know if it helps. Thanks!
