### ISSUE TITLE
Why is snappy compression output buffer size so small?

### ISSUE THREAD

**Issue by burgerkingeater** [tensorflow/tensorflow#47056]
Hi @frankchn,
The snappy compression buffer size is hard coded to 262144 bytes:
https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/core/lib/io/snappy/snappy_compression_options.h#L30. This is a quite small number leading to high chance of hitting the error:
https://github.com/tensorflow/tensorflow/blob/516ae286f6cc796e646d14671d94959b129130a4/tensorflow/core/lib/io/snappy/snappy_inputstream.cc#L113

I wonder why it is set to thus small. 

Furthermore, `output_buffer_` is a fixed sized array https://github.com/tensorflow/tensorflow/blob/516ae286f6cc796e646d14671d94959b129130a4/tensorflow/core/lib/io/snappy/snappy_inputstream.h#L73

Why can't it be a vector so that we don't need the `output_buffer_size` at all? I'm happy to submit a PR to make the according change if needed.

Thanks.

**Comment by frankchn** [comment]
1) The maximum block size in the current snappy implementation is 64KB, so in practice users are never going to hit that error. See https://github.com/google/snappy/blob/master/snappy.h#L190-L198

2) We are using a raw pointer into the `char[]` array in the `next_out_` variable (snappy_inputstream.cc:121 and snappy_inputstream.cc:136). If we were using `std::vector` and extracting the raw pointer using `std::vector::data()`, then we need to account for `std::vector` performing reallocations, and thus invalidating the existing `next_out_` pointer. A raw memory allocation avoids this issue altogether.

**Comment by burgerkingeater** [comment]
@frankchn thanks for the detailed explanation.
1. It means SnappyInputStream relies on an external lib's internal implementation to determine its behavior and it's tempting to think it's an anti-pattern.

2. the 64KB seems not taking effect as we are hitting the error https://github.com/tensorflow/tensorflow/blob/516ae286f6cc796e646d14671d94959b129130a4/tensorflow/core/lib/io/snappy/snappy_inputstream.cc#L113

**Comment by frankchn** [comment]
Do you have a test case / reproduction of the error you are encountering?

The implementation of the snappy library is also controlled by Google, so I don't think it is a problem in practice.
