### ISSUE TITLE
0.11.rc0 version, using all gpu's memory while running on only one

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#4706]
With 0.11.rc0 tf, cudnn 7.5
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 0000:03:00.0     Off |                    0 |
| N/A   47C    P0   127W / 235W |  10995MiB / 11519MiB |     87%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 0000:04:00.0     Off |                    0 |
| N/A   39C    P0    63W / 235W |  10953MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          On   | 0000:83:00.0     Off |                    0 |
| N/A   40C    P0    62W / 235W |  10954MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          On   | 0000:84:00.0     Off |                    0 |
| N/A   39C    P0    62W / 235W |  10953MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      8828    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 10964MiB |
|    1      8828    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 10923MiB |
|    2      8828    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 10923MiB |
|    3      8828    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 10923MiB

With 0.10.0 tf, same code running with gpu status below
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 0000:03:00.0     Off |                    0 |
| N/A   46C    P0   129W / 235W |  10993MiB / 11519MiB |     89%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 0000:04:00.0     Off |                    0 |
| N/A   38C    P0    63W / 235W |    108MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K40m          On   | 0000:83:00.0     Off |                    0 |
| N/A   39C    P0    62W / 235W |    107MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K40m          On   | 0000:84:00.0     Off |                    0 |
| N/A   38C    P0    62W / 235W |    107MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     20051    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2 10959MiB |
|    1     20051    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2    74MiB |
|    2     20051    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2    74MiB |
|    3     20051    C   ...mpiler/gcc-4.8.2/lib/ld-linux-x86-64.so.2    74MiB

**Comment by chenghuige** [comment]
@yaroslavvb I see thanks, but I don't think it need to grab all gpu memories if only running on one.
Just grap one gpu memory as version 0.10.0 did is fine.
Anyway can force to grab one gpu memory by using CUDA_VISIBLE_DEVICES.

**Comment by concretevitamin** [comment]
@chenghuige: what do you mean by "only running on one"?  To me, this means setting `CUDA_VISIBLE_DEVICES`.  If you instead mean that you use `with tf.device("/gpu:0")` exclusively in your code, then when initializing the TensorFlow runtime, it would have no way to _know_ just one GPU is going to be used.

**Comment by chenghuige** [comment]
@concretevitamin  well I think as in version 0.10, it will launch only one GPU, unless your code is like models/image/cifa10/
to explicitly set using more then 1
  for i in xrange(FLAGS.num_gpus):
      with tf.device('/gpu:%d' % i):

**Comment by aselle** [comment]
You will get best performance by partitioning your variables manually across GPUs in a way that makes sense.

**Comment by vrv** [comment]
I think the problem is that there's an Eigen scratch allocator in the GPUDevice constructor that allocates memory on the GPU.  Before r0.11, the call was directly calling cuMalloc instead of going through our allocator, and so although some memory was used on the GPU, it wasn't going through our allocator so the whole thing wasn't being taken.  But to properly track memory usage, we make all of our calls now go through the allocator, so GPUDevice construction now unfortunately allocates all the memory.

Two solutions: 

1) We lazily allocate the scratch allocator space instead of eagerly doing it in the constructor (not sure where / when we would do this though).

2) You can set the 'allow_growth' option in ConfigProto.GPUOptions so that the initial allocation doesn't cause all of the GPU memory to be allocated.

**Comment by gunan** [comment]
No response for 10 days.
Also looks like this is working as intended.
Therefore closing the issue.
