### ISSUE TITLE
tensorflow/cc/saved_model/README.md is broken

### ISSUE THREAD

**Issue by atn832** [tensorflow/tensorflow#47062]
## URL(s) with the issue:

- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/saved_model/README.md
- https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/cc/saved_model/README.md

## Description of issue (what needs changing):
I would expect to see some documentation regarding the package. Instead, it says `<!--#include file="../../python/saved_model/README.md"-->`.

**Comment by jvishnuvardhan** [comment]
@atn832 Looks like there is no information in that `README.md` but general information about the package is given in the `README.md` in `python` folder [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md). Thanks!
