### ISSUE TITLE
TF 2.4 tf.data cached shuffle 35% slower compared to TF 2.3

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#47067]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4, 2.5.0a20210210
- Python version: 3.8.5

**Describe the current behavior**
When running the code example below, TF 2.4 is 35% slower in the first epoch compared to TF 2.3 when shuffling is enabled. The epoch times for the second epoch are only slightly slower, so this issue only seems to occur when the shuffle buffer is not fully filled yet.

This issue doesn't seem to happen without shuffling, so I don't think this issue is related to a problem in GCS read performance. TF nightly partially fixed this issue, but is still ~10% slower compared to TF 2.3. 

version | 1st epoch | 1st epoch no shuffling
---|---|---
`v2.2.2` | 256.2 s |
`v2.3.2` | **249.0 s** | 234.7 s
`v2.4.1` | **334.7 s** | 230.6 s
`v2.5.0a20210210` | 276.0 s | 

**Describe the expected behavior**
The time of the first epoch should not be slower compared to TF 2.3.

**Standalone code to reproduce the issue**
```python
import time
import tensorflow_datasets as tfds

dataset = tfds.load(
    "imagenet2012",
    decoders={"image": tfds.decode.SkipDecoding()},
    split="train",
    data_dir="gs://my_data_bucket",
)

samples = dataset.cardinality()  # 1281167
dataset = dataset.cache().shuffle(samples).batch(256).prefetch(1)

for epoch in range(2):
    start = time.time()
    for data in dataset:
        pass
    end = time.time()
    print(f"Epoch {epoch + 1}: {(end - start):.1f} s")
```

**Comment by amahendrakar** [comment]
@lgeiger,
On running the given code snippet, I am facing a `ValueError`, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/aa1ff8e66576d954087402557b8ac382/47067.ipynb).

In order to expedite the trouble-shooting process, could you please provide a minimal reproducible code. 

Also, check if you are facing the same issue with `tfds-nightly` version as well? Thanks!

**Comment by lgeiger** [comment]
> On running the given code snippet, I am facing a ValueError, please find the gist of it here.

I updated the code example above. Looks like Colab uses a different version TFDS.

Please note that since this is a performance issue it will be difficult to reproduce on Colab since a large dataset like ImageNet or similar is required to be able to see a difference.

> Also, check if you are facing the same issue with tfds-nightly version as well?

I did. Please see the table above.

**Comment by ShubhamShaswat** [comment]
I did some tests on Google Colab but on the `imagenet_resized` dataset instead. The code is almost similar. I used `pip` to install required tensorflow version and restart the runtime. Below are my observations for 3 different versions of the Tensorflow.

#### Code :

```python
import time
import tensorflow_datasets as tfds 

dataset = tfds.load("imagenet_resized",split="train")

samples = dataset.cardinality()  # 1281167
dataset = dataset.cache().shuffle(samples).batch(256).prefetch(1)

for epoch in range(2):
    start = time.time()
    for data in dataset:
        pass
    end = time.time()
    print(f"Epoch {epoch + 1}: {(end - start):.1f} s")
```
| Version  | 1st epoch |
| ------------- | ------------- |
| TF 2.3.0  | 109.5 s  |
| TF 2.3.2  | 110.8 s  |
| TF 2.4.1  | 91.0 s  |

for me on CPU, TF 2.4.1 seems faster, don't know if this for this case only

**Comment by lgeiger** [comment]
@ShubhamShaswat I can reproduce your results with the `imagenet_resized` dataset as well on my machine both when reading the dataset from the local disk as well as from GCS. So it looks like this issue only comes up with larger datasets.

**Comment by ShubhamShaswat** [comment]
@lgeiger larger dataset could be the reason here, as per the samples size both have the same `cardinality` of `1281167` so this might not be the reason. If the datasize is the culprit I would like to test it with smaller samples size but with different datasizes just like `imagenet` and `imagenet_resized` and see if that's the real reason.

**Comment by amahendrakar** [comment]
On running the code with `imagenet2012`, facing an error stating `OSError: Not enough disk space. Needed: 155.84 GiB (download: Unknown size, generated: 155.84 GiB)`. 

Whereas with `imagenet_resized` dataset, the execution times are 

TF Version | 1st epoch | 2nd epoch
---|---|---
[2.3.2](https://colab.research.google.com/gist/amahendrakar/bd93339692ddb713b5b1e2ed43792384/47067-2-3-2.ipynb) | 118.3 s | 5.5 s
[2.4.1](https://colab.research.google.com/gist/amahendrakar/0e007f9e2a136aad27a7998bc95e1db2/47067.ipynb) | 95.0 s | 3.7 s
[2.5.0-dev20210223](https://colab.research.google.com/gist/amahendrakar/8319878707e674a103b85d82a4c219a2/47067-tf-nightly.ipynb) | 141.9 s | 4.1 s

Please check the linked gist for reference. Thanks!

**Comment by lgeiger** [comment]
@amahendrakar great that you were able to reproduce the slowdown in `tf-nightly` with `imagenet_resized`.

> On running the code with imagenet2012, facing an error stating OSError: Not enough disk space. Needed: 155.84 GiB (download: Unknown size, generated: 155.84 GiB).

This is expected as Colab doesn't have enough disk available to download ImageNet. You can reproduce it on colab by using a GCS bucket and streaming the data from there.

**Comment by sachinprasadhs** [comment]
Could you please try to download imagenet dataset manually here https://www.tensorflow.org/datasets/catalog/imagenet2012 and test it in the latest version again and let us know if you find satisfying results. Thanks!
