### ISSUE TITLE
model.predict infer batch size from x if x is an array/tensor

### ISSUE THREAD

**Issue by CharlesSS07** [tensorflow/tensorflow#47079]
If you use a subclassed tf keras model, and write the call method, you may want to access the shape of the `inputs` argument. While training, this is possible. The shape would be [batch_size, width, height, channels] for a batch of images using a tf data dataset. However, when calling `model.predict(images)`, where images is an array [batch_size, width, height, channels], the shape would be [None, width, height, channels]. This is confusing, though can be fixed by setting the batch_size argument of predict.

I propose that when calling model.predict on tensors/arrays (not datasets), batch_size is inferred from the shape of the inputted array. I have implemented the code myself by overriding the predict function in a class extending tf.keras.Model like shown:

```
...
def predict(self,
                x,
                batch_size=None,
                verbose=0,
                steps=None,
                callbacks=None,
                max_queue_size=10,
                workers=1,
                use_multiprocessing=False
               ):
         return super(Autoencoder, self).predict(x, (batch_size or x.shape[0]), verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
...
```

I see no reason why the shape of `inputs` is not always known, so this seems like a reasonable request to me. I have not really checked, however, if `inputs.shape` is not set when not using a dataset to fit or evaluate, it would make sense that `inputs.shape` is populated there as well. It just doesn't make sense that the shape of `inputs` should ever have a None value in it when it is known.

**Comment by omalleyt12** [comment]
Thanks for the issue! For backwards compatibility reasons, `batch_size` will default to `32` if not supplied. `tf.data.Dataset`s don't use this argument bc they are assumed to be batched already. What's happening here is prob that your data is not evenly divisible by `32` and so there is a last partial batch, and so the overall batch_size comes through as None

**Comment by CharlesSS07** [comment]
Hi,

Thanks for the response. It looks like we're talking about two different things.

When using datasets, the shape of `input` is [**batch_size**, width, height, channels], as it should be. My issue has to do with passing arrays, and not datasets.

Currently, passing a numpy array to `model.predict` will call `call`, and the `input` argument of `call` will have the shape [**None**, width, height, channels]. My issue is not in the batch size used by a dataset, but that I cannot determine the batch size of `input` when an array is passed to `model.predict`.

**Comment by omalleyt12** [comment]
Sure, what I meant was if your data is of shape `(48, 10)`, it will be split into batches of `32` and `16`, and so when the `tf.function` is traced, it will show a `None` `batch_size`. To confirm that this is the case, you can try passing a `batch_size` that evenly divides your data. Then the shape of `input` in `call` should be `[batch_size, ...]`

**Comment by CharlesSS07** [comment]
I see. Thank you for the clarification! Could I ask why it shows a None batch_size when there is a remainder batch?
