### ISSUE TITLE
Create API for creating slot variables

### ISSUE THREAD

**Issue by xksteven** [tensorflow/tensorflow#4707]
To create or modify Adadelta, or Adam requires editing the Eigen tensor implementations of each.  However if it were possible to create a slot variable from tensorflow then one could perform tests without needing to recompile the whole tensorflow library.

**Comment by hholst80** [comment]
Have you looked into miyosudas implementation of Shared RMSProp?

**Comment by xksteven** [comment]
@hholst80 can you provide a link to it?  I don't know from which repo his implementation is in.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, we will reopen when further information becomes available.
