### ISSUE TITLE
Micro benchmarks is excluded for cortex_m_corstone_300_makefile.inc

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#47071]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
I hit this issue when working with: https://github.com/tensorflow/tensorflow/pull/46830
Micro benchmarks had to be excluded.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Try to run Micro benchmark for cortex_m_corstone_300_makefile.inc

**Comment by advaitjain** [comment]
As part of enabling benchmarks for the Ethos-U, we will want to support the Vela converted person detection model from the benchamark code. [Here](https://github.com/tensorflow/tensorflow/pull/48669#discussion_r622620181) an initial discussion on that topic.
