### ISSUE TITLE
KerasClassifier, GridSearchCV ignore with tf.device('cpu:0')

### ISSUE THREAD

**Issue by dvelaren** [tensorflow/tensorflow#47085]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- CUDA/cuDNN version: CUDA v11.0.2/cuDNN v8.0.4.30
- GPU model and memory: Quadro M1200

**Describe the current behavior**
Using KerasClassifier in combination with GridSearchCV ignores if I force to use CPU computing instead of GPU using `with tf.device('cpu:0')`

**Describe the expected behavior**
TF and Keras libraries should use specified hardware (CPU or GPU) if it is inside the `with tf.device(DEVICE_NAME)`.

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

tf.debugging.set_log_device_placement(True)
X_train = np.random.rand(1000,7)
input_dim = X_train.shape[1]
epochs = [5, 10, 15]
batch_size = [10, 20, 30, 40]
param_grid = dict(epochs=epochs, batch_size=batch_size)

def create_sequential_model(activation='relu', dropout_rate=0.2, optimizer='SGD'):
    model = Sequential()
    model.add(Dense(4, input_dim=input_dim, activation=activation))
    model.add(Dropout(dropout_rate))
    model.add(Dense(2, activation=activation))
    model.add(Dense(4, activation=activation))
    model.add(Dense(7, activation='sigmoid'))
    model.compile(loss='mse', optimizer=optimizer, metrics=['accuracy'])
    return model

with tf.device('cpu:0'): # This works and runs on CPU
    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b) # This works and runs on GPU
print(c)

with tf.device('cpu:0'): # This doesn't work
    model = KerasClassifier(build_fn=create_sequential_model, verbose=1) 
    grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=5)
    grid_result = grid.fit(X_train, X_train) 
```

**Other info / logs**
Proof it is using GPU instead of CPU
![ErrorTFCPUGPU](https://user-images.githubusercontent.com/2531157/107632092-4da42880-6c66-11eb-91a0-d10e6bf514a6.png)

Please find the error displayed below (I know this error is because the parameter `n_jobs=-1` of GridSearchCV is not supported on tensorflow if using GPU)
`TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.`

**Comment by dvelaren** [comment]
Also, I would like to add that I tried using the "trick" of setting `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` and it works. However I intend to use GPU after I obtained best hyperparameters with other created model and using the `fit` and `predict` function. So if I set CUDA_VISIBLE_DEVICES to -1 and then I try to set it back again to '0' or '1', GPU won't work anymore and I would have to reinitize my whole program in order for GPU to work.

**Comment by ravikyram** [comment]
I have tried in colab with TF-GPU version 2.4.1 . Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0beae0906a79e8f19f9e01071d642e30/untitled671.ipynb).You are also seeing the same behavior?
Thanks!

**Comment by dvelaren** [comment]
> @dvelaren
> I have tried in colab with TF-GPU version 2.4.1 . Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0beae0906a79e8f19f9e01071d642e30/untitled671.ipynb).You are also seeing the same behavior?
> Thanks!

Hello @ravikyram your colab works even in the GridSearchCV. However error persist when trying outside of Colab.

**Comment by mohantym** [comment]
Hi @dvelaren ! Is this issue still valid in 2.8 version?
