### ISSUE TITLE
Multiple GPU tests run redundantly

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#47081]
Using TensorFlow 2.4.1

**Describe the problem**

I noticed that some GPU tests are run multiple times redundantly with apparently no need or benefit causing test times to increase.
Example: //tensorflow/core/kernels/mlir_generated:gpu_tanh_test, //tensorflow/core/kernels/mlir_generated:gpu_tanh_test_gpu

As you can see there is a gpu_* test and a gpu_*_gpu test

This happens because `tf_cuda_cc_test` rule is used which creates a CPU and a GPU test already. However as the test is meant for GPU already and has `tags = tf_cuda_tests_tags()` set, it will create 2 tests that are both run (only) on GPU

As current master has changed considerably I just did a quick check and found e.g.:
https://github.com/tensorflow/tensorflow/blob/c820e5278288773ef2298b1796164a9826d847cf/tensorflow/core/kernels/mlir_generated/BUILD#L332-L345

This follows the same pattern and should likely be revised. I quick fix would likely be: If the passed tags already contain `gpu` then the CPU test will not be added.

**Comment by mohantym** [comment]
Hi @Flamefire !
We are checking to see whether you still need help in this issue .  I think the unit test related to tanh moved to gpu_unary_ops_test in 2.8.2 later versions.

I tested with above test in 2.9.2 version and build passed .
Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/0ccc54941f7f0c784cc0da5389e540b8/tensorflow-ranking.ipynb#scrollTo=ndJ5VcZnBB3U)for reference.

Thank you!

**Comment by Flamefire** [comment]
Yes the issue still persists: https://github.com/tensorflow/tensorflow/blob/73e20279c60fc77aa377ce42d36644b832d8a5d6/tensorflow/core/kernels/mlir_generated/BUILD#L450-L470

**Comment by mohantym** [comment]
Ok @Flamefire !
Thanks for the update. But , Did you check my gist too.
Thank you!

**Comment by Flamefire** [comment]
Thanks @mohantym for the reply.
Seems you have missed that the issue is not a failing test but rather a redundant test due to a "CPU" test copy created for a GPU test, see the current master: https://github.com/tensorflow/tensorflow/blob/1b32744e65e8fdfb4fd694326fd1fa2fc9613acc/tensorflow/tensorflow.bzl#L1409

I.e. for the above quoted example it will create a test `gpu_unary_ops_test_cpu` and `gpu_unary_ops_test_gpu` both with `tags = tf_cuda_tests_tags()`

See my initial description
