### ISSUE TITLE
TF Lite Micro person detection example won't make?

### ISSUE THREAD

**Issue by Hazeline2018** [tensorflow/tensorflow#47080]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Python pip and git clone
- TensorFlow version: 2.4.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I installed the whole Tensorflow package using both pip and git clone on Ubuntu 20.04. When I tried to make the person detection project as follows:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project

It errored out with no make rule. The whole log is:

_terryl@DESKTOP-55BFST5:/mnt/c/Projects/tensorflow$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project
--2021-02-10 22:34:31--  http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip
Resolving mirror.tensorflow.org (mirror.tensorflow.org)... 216.58.195.80
Connecting to mirror.tensorflow.org (mirror.tensorflow.org)|216.58.195.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1760478 (1.7M) [application/zip]
Saving to: ‘/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip’

/tmp/dca12522a9f9e37f126ab925 100%[=================================================>]   1.68M  8.23MB/s    in 0.2s

2021-02-10 22:34:32 (8.23 MB/s) - ‘/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip’ saved [1760478/1760478]

Cloning into 'tensorflow/lite/micro/tools/make/downloads/pigweed'...
remote: Sending approximately 12.05 MiB ...
remote: Counting objects: 6, done
remote: Finding sources: 100% (6/6)
remote: Total 18665 (delta 8537), reused 18663 (delta 8537)
Receiving objects: 100% (18665/18665), 11.99 MiB | 5.09 MiB/s, done.
Resolving deltas: 100% (8537/8537), done.
Updating files: 100% (1456/1456), done.
Updating files: 100% (647/647), done.
Note: switching to '47268dff45019863e20438ca3746c6c62df6ef09'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 47268dff pw_hdlc_lite: Client I/O improvements
warning: pw_presubmit/py/pw_presubmit/format_code.py has type 100644, expected 100755
warning: pw_presubmit/py/pw_presubmit/pigweed_presubmit.py has type 100644, expected 100755
make: *** No rule to make target 'generate_person_detection_esp_project'.  Stop._

I tried multiple times clean installing tensorflow but always the same problem. Am I missing something or the example project got broken somehow? I tried making hello_world project for ESP32, it worked fine.
Please help, thanks!
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Hazeline2018** [comment]
Any advice or even a clue to look at would be highly appreciated! The project got stuck here! Thanks!

**Comment by ymodak** [comment]
duplicate #46277 
Also a [PR](https://github.com/tensorflow/tensorflow/pull/47063) is in progress to address this issue.
Thanks!
