### ISSUE TITLE
tf.keras.metric.Metric.reset_states() fails if state contains variables with rank greater than zero

### ISSUE THREAD

**Issue by artiumd** [tensorflow/tensorflow#47089]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory
- TensorFlow installed from (source or binary): Google Colaboratory
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9

**Describe the current behavior**
When I implement my own custom keras metric that has an internal weight of rank greater than zero (meaning, its shape has length greater than zero), calling the ``reset_states()`` method on an instance of this metric fails.

See example below. This is reproducible in colab. 

**Describe the expected behavior**
I would expect ``reset_metrics()`` not to fail.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


class MyMetric(tf.keras.metrics.Metric):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.w = self.add_weight(name='w', shape=(1,))

    def update_state(self, w):
        self.w.assign(w)

    def result(self):
        return self.w

m = MyMetric()
m.reset_states()
```

**Other info / logs** 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-86-2dd397d265f4> in <module>()
     14 
     15 m = MyMetric()
---> 16 m.reset_states()

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/metrics.py in reset_states(self)
    251     when a metric is evaluated during training.
    252     """
--> 253     K.batch_set_value([(v, 0) for v in self.variables])
    254 
    255   @abc.abstractmethod

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py in batch_set_value(tuples)
   3704   if ops.executing_eagerly_outside_functions():
   3705     for x, value in tuples:
-> 3706       x.assign(np.asarray(value, dtype=dtype(x)))
   3707   else:
   3708     with get_graph().as_default():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
    889             ("Cannot assign to variable%s due to variable shape %s and value "
    890              "shape %s are incompatible") %
--> 891             (tensor_name, self._shape, value_tensor.shape))
    892       assign_op = gen_resource_variable_ops.assign_variable_op(
    893           self.handle, value_tensor, name=name)

ValueError: Cannot assign to variable w:0 due to variable shape (1,) and value shape () are incompatible
```

**Comment by ravikyram** [comment]
Was able to reproduce the issue with  TF v2.4 and TF-nightly(`2.5.0-dev20210211`). Please find the gist of it [here](https://colab.research.google.com/gist/ravikyram/3f9f178cb17c4890bcaf1b6ecae9dc40/untitled670.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue using TF Nightly 2.6 version.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/bc5f710e75b6d271cd09396ea147b24d/untitled96.ipynb).Thanks!

**Comment by chibi03** [comment]
Is there any workaround for this issue?

**Comment by lucasbanunes** [comment]
Running TF 2.11 and having the same issue, any workaround?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Could you please try to update to latest tensorflow v2.17 which contains Keras3.0.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
