### ISSUE TITLE
Calling tf.linalg.expm causes SIGSEGV. 

### ISSUE THREAD

**Issue by relgukxilef** [tensorflow/tensorflow#47091]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home (19041.789)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0-dev20201216
- Python version: 3.7.7
- CUDA/cuDNN version: 11.0.3/8.0.4.30
- GPU model and memory: RTX 3070, 8GB

Calling `tf.linalg.expm` causes the interpreter to exit. Attaching GDB reveals a SIGSEGV in thread 1. I have attached a demangled stack trace.
Calling `tf.linalg.expm` should return a tensor with the result.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
tf.linalg.expm(tf.constant([[1.0]]))
```
Passing larger matrices or the result of `tf.random.normal` doesn't change the behavior. 

[tf_stacktrace.txt](https://github.com/tensorflow/tensorflow/files/5967082/tf_stacktrace.txt)

**Comment by amahendrakar** [comment]
@relgukxilef,
I was able to run the code without any issues on [TF v2.4](https://colab.research.google.com/gist/amahendrakar/59040e0ba2e0095d54ec56a923380bd9/47091.ipynb#scrollTo=eAcOTxDwx2UZ) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/05d9f648aff82758c4cebb382168d574/47091-tf-nightly.ipynb). Please check the linked gist for reference.

Could you please try running the code in a new virtual environment and check if you are facing the same error. Thanks!

**Comment by relgukxilef** [comment]
The error occurs in both this environment and a second environment running Python 3.8.5 and TF 2.5.0-dev20210204 (the newest nightly at the time of installation). Both were created through Anaconda (which is not the recommended way of installing TF anymore)
When creating a new environment with `virtualenv` and installing TF through pip (either `tensorflow` or `tf-nightly`) this problem does not occur. As far as I am concerned this is a solution for my case. Thanks for the suggestion.
