### ISSUE TITLE
Build issue with bazel "python_bin_path.sh: No such file or directory"

### ISSUE THREAD

**Issue by alexatknit** [tensorflow/tensorflow#471]
I've updated my code, and following what is currently listed under https://www.tensorflow.org/versions/master/get_started/os_setup.html#source arrived at this output:

```bash
alex@ml1:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 0.793s, Critical Path: 0.00s
alex@ml1:~/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Thu Dec 10 12:13:53 PST 2015 : === Using tmpdir: /tmp/tmp.NqHERREKmr
/tmp/tmp.NqHERREKmr ~/tensorflow
Thu Dec 10 12:13:53 PST 2015 : === Building wheel
bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 45: tensorflow/tools/python_bin_path.sh: No such file or directory
```

Any idea why the python_bin_path.sh file hasn't been generated?

**Comment by vrv** [comment]
Did you run ./configure  first?

**Comment by alexatknit** [comment]
Sure did. Right now I'm trying updating to bazel 0.1.2 or rebooting.

**Comment by vrv** [comment]
Hmm, @wicke, this might be related to your change earlier today?

**Comment by martinwicke** [comment]
Probably. As a workaround while I look into this, you can edit tensorflow/tools/pip_package/build_pip_package to remove the offending line. Replace 

```bash
  source tensorflow/tools/python_bin_path.sh
  ${PYTHON_BIN_PATH} setup.py bdist_wheel >/dev/null
```

with

```bash
  python setup.py bdist_wheel >/dev/null
```

Then rebuild.

**Comment by craigcitro** [comment]
worst-case, we could also just do ${PYTHON_BIN_PATH:-python}

**Comment by alexatknit** [comment]
Thanks @martinwicke, that did the trick.

**Comment by chihaytong** [comment]
It looks like the ./configure script puts python_bin_path.sh into the root tensorflow/tools directory, not tensorflow/tensorflow/tools.

Either util/python/python_config.sh or tensorflow/tools/pip-package/build_pip_package.sh needs to change.

**Comment by pronobis** [comment]
This problem still appears for me for master and bazel 0.1.2
```
Fri Dec 11 09:27:04 PST 2015 : === Building wheel
bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 45: tools/python_bin_path.sh: No such file or directory
```

The abovementioned commits are in.

**Comment by noisychannel** [comment]
Confirmed. This issue still exists.

**Comment by vrv** [comment]
Does the change in 7c5c20b2b73c40bb4fd113f26bcda73a5e5bec6d help?

**Comment by noisychannel** [comment]
It does. The script was in the wrong directing when trying to source python_bin_path.sh

**Comment by panmari** [comment]
Also fixed it for me @vrv

**Comment by pronobis** [comment]
Works indeed. Thanks.
