### ISSUE TITLE
Make Tensorflow 2.3 available through conda on macOS

### ISSUE THREAD

**Issue by kmalfroid** [tensorflow/tensorflow#47109]
### System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): conda
- Python version: 3.7.9

### Describe the problem

`conda install tensorflow` installs version 2.0

Please, make tensorflow 2.3 available through conda.

Other platforms support 2.3, however macOS is still stuck at 2.0:
https://anaconda.org/anaconda/tensorflow
<img width="202" alt="Screen Shot 2021-02-12 at 10 15 22" src="https://user-images.githubusercontent.com/73581880/107749654-396e3300-6d1b-11eb-85be-02a0472dc40a.png">

**Comment by ymodak** [comment]
TF provides pre built pip packages whereas conda packages are community supported.
I think anaconda repo can be a right platform to raise this issue since they provide TF conda packages across various platforms.
https://github.com/ContinuumIO/anaconda-issues/issues
