### ISSUE TITLE
ValueError: Data cardinality is ambiguous:   x sizes: 60000   y sizes: 10000 Please provide data which shares the same first dimension.

### ISSUE THREAD

**Issue by saikrishna14343** [tensorflow/tensorflow#47106]
![Screenshot (58)](https://user-images.githubusercontent.com/60438445/107751007-d0021a80-6d42-11eb-9326-ed9af5c643e3.png)
![Screenshot (59)](https://user-images.githubusercontent.com/60438445/107751014-d395a180-6d42-11eb-802f-6c3313bf0999.png)
![Screenshot (60)](https://user-images.githubusercontent.com/60438445/107750981-c37dc200-6d42-11eb-80a6-b4fffe5e445d.png)

**Comment by saikrishna14343** [comment]
i am working on jupypter notebook . please let me know how can i share my entire code here

**Comment by Saduf2019** [comment]
@saikrishna14343 
Please run your code on colab gist and add the gist here. [contrl+k will let u paste the gist executed on colab]

**Comment by saikrishna14343** [comment]
i do not have colab .

**Comment by Saduf2019** [comment]
@saikrishna14343
Please use [google colab](https://colab.research.google.com/notebooks/) [[link](https://www.tutorialspoint.com/google_colab/index.htm) for reference],Labels used do not match the first dimension as feature as per your screen shots.

**Comment by ShubhamShaswat** [comment]
what is your `x_test` and `y_test`, seems like there is shape mismatching, the first dimension should be same for both
