### ISSUE TITLE
Snapshot Op Reader::MakeNestedDataset didn't handle the empty shard case properly (divide by 0 error)

### ISSUE THREAD

**Issue by arde171** [tensorflow/tensorflow#47103]
Hi @frankchn, I'm using snapshot op for distributed training with parameter server strategy in which one of the workers didn't get data and produces snapshot folder with empty shard. However, for the next run I got an exception _Reader::MakeNestedDataset()_ as the shard was empty. I think the existing code was written with the assumption that shard won't be empty  (start_index % shard_dirs.size()) and caused divide by 0 error. Could you please confirm.

https://github.com/tensorflow/tensorflow/blob/582c8d236cb079023657287c318ff26adb239002/tensorflow/core/kernels/data/experimental/snapshot_util.cc#L590

**Comment by frankchn** [comment]
Hello! Can you provide more details, like what is the error you encountered, what are the parameters of the `snapshot` call, and the internal directory structure of the snapshot directory?

It would be ideal if you can provide a test-case for this.

**Comment by arde171** [comment]
Error:
```
Child process exited with exit code 134

# Problematic frame:
# C  [_pywrap_tensorflow_internal.so+0x8d2d59e]  tensorflow::data::snapshot_util::Reader::MakeNestedDataset(tensorflow::Env*, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, int, absl::lts_2020_02_25::InlinedVector<tensorflow::DataType, 4ul, std::allocator<tensorflow::DataType> > const&, std::vector<tensorflow::PartialTensorShape, std::allocator<tensorflow::PartialTensorShape> > const&, long long, tensorflow::data::DatasetBase**)+0x41e
```

snapshot call :
`dataset = dataset.apply(tf.data.experimental.snapshot("snapshot/path"))`

The snapshot directory structure:
```
<>/hash_id
       /run_id
       snapshot.metadata
```
 I observed that there was no shard folders inside run_id due to no input data for that particular worker. 
 I won't be able to give you this distributed PS test. However, you can call the  _Reader::MakeNestedDataset()_ with empty shard data (shard_dirs.size()=0) and then you can reproduce the same error.

**Comment by frankchn** [comment]
@arde171 Thanks! Managed to reproduce this on our side and a fix is going through internal code review now and should be pushed out next week and included with the next release.
