### ISSUE TITLE
tf.All support as TFlite buildin op

### ISSUE THREAD

**Issue by neso613** [tensorflow/tensorflow#47101]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (or github SHA if from source): 2.4.1

**Provide the text output from tflite_convert**
```
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: All, RandomUniform
Details:
tf.All {device = "", keep_dims = false}
tf.RandomUniform {device = "", seed = 0 : i64, seed2 = 0 : i64}
```

**Standalone code to reproduce the issue** 
I have a model in [Tensorflow.](https://github.com/TensorSpeech/TensorFlowTTS/blob/master/notebooks/TensorFlowTTS_Tacotron2_with_TFLite.ipynb)
If I use this 
converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS,
tf.lite.OpsSet.SELECT_TF_OPS]
model is converted into TFLite but have Flex Delegate.

Flex delegate do not worked on edge board. 
Requesting to please provide tf.All and tf.RandomUniform support as buildin op.
Please suggest some solution for now. I know, Custom op is one way, but how to do ?
Can I expect the support for Ops soon or in tf-nightly versions?

**Comment by thaink** [comment]
TFLite supports Reduce_any. It makes sense to support Reduce_All as well.

**Comment by neso613** [comment]
> TFLite supports Reduce_any. It makes sense to support Reduce_All as well.

I don't get the point. Your mean, I will replace tf.reduce_all with tf.redice_any. How?
In the code, there is about 20 TF op like tf.reduce_all,tf.reduce_sum,tf.tile with their equivalent numpy functions. But issue is still persist.

**Comment by thaink** [comment]
@neso613 I didn't mean that. It is just a statement to support adding Reduce_All as a builtin op.

**Comment by neso613** [comment]
> @neso613 I didn't mean that. It is just a statement to support adding Reduce_All as a builtin op.

ok. Do you know, where this tf.All() and tf.RandomUniform() used in the model. Can we replace these op with np equivalents.

**Comment by neso613** [comment]
Any ETA for op support?

**Comment by neso613** [comment]
ETA

**Comment by neso613** [comment]
looking forward for op support

**Comment by thaink** [comment]
It is in out to-do-list.

**Comment by thaink** [comment]
The op is now supported in the master branch.
