### ISSUE TITLE
What is the best architecture that we can converted to coreml and run on ios?

### ISSUE THREAD

**Issue by rafallukasik123** [tensorflow/tensorflow#47114]
I would like to know which architecture achieve the best resaults?
For example efficientdet or mobilenetv3.
Also, the model from this architecture must be able to convert to coreml and run on iOS.

**Comment by Saduf2019** [comment]
@rafallukasik123 
Can you share more details,In general EfficientDet is used for detection and Mobilenet for classification, Can you try Tflite delegate.
If this is not a bug or feature request please open this issue on [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) and move this to closed status.
