### ISSUE TITLE
tf.keras.experimental.CosineDecay() get wrong step after tf.keras.Model.load_weight()

### ISSUE THREAD

**Issue by HLSS-Hen** [tensorflow/tensorflow#47115]
**System information**
-- NVIDIA RTX 2080ti 11G x2 ( with NVLink )
-- Ubuntu 20.04 LTS
-- Python 3.8.5 ( gcc / g++ 9.3.0 )
-- CUDA Toolkit 11.1, cuDNN 8.0.4, TensorRT 7.2.2, NCCL 2.8.3
-- tensorflow 2.4.1 ( build form release )

**Describe the current behavior**
Keras Model load weights saved with `tf.keras.callback.ModelCheckpoint()` makes `tf.keras.experimental.CosineDecay()` get wrong step in `Model.fit()`.
Usually, this make `CosineDecay.__call__(step)` return 0 because step>decay_steps.
**Describe the expected behavior**
The step should compute by inital_batch when call Model.fit(), but not the step in ckpt.

**Comment by HLSS-Hen** [comment]
I find that `tf.keras.Optimizer` has attribute `iterations`, which saves in ckpt and compute the `step`when call `CosineDecay.__call__(step)`.
It's works right when I call `model.optimizer.iterations.assign(0)` after 'Model.load_weights()' and 'Model.compile()'.

**Comment by amahendrakar** [comment]
@HLSS-Hen,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by HLSS-Hen** [comment]
First run:

```
import tensorflow as tf
import tensorflow_datasets as tfds

EPOCHS = 120
INITIAL_EPOCH = 0
TRAIN_BATCH_SIZE = 256

def _parser(record):
    image = record['image']
    label = record['label']
    image = tf.image.resize(image, (224, 224), tf.image.ResizeMethod.BICUBIC)
    image = image / 255.
    return image, label

ds = tfds.load('cifar10', split=['train'])[0]
ds = ds.map(lambda x: _parser(x),num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(TRAIN_BATCH_SIZE)

model = tf.keras.applications.EfficientNetB0(classes=10,weights=None)
model.compile(tf.keras.optimizers.SGD(tf.keras.experimental.CosineDecay(.1, 50000//TRAIN_BATCH_SIZE*EPOCHS), .9),
              tf.keras.losses.SparseCategoricalCrossentropy(),
              [tf.keras.metrics.SparseTopKCategoricalAccuracy(1, name='top1')])

model.fit(ds_train,
          epochs=EPOCHS,
          initial_epoch=INITIAL_EPOCH,
          callbacks=[tf.keras.callbacks.TensorBoard('logs', histogram_freq=1, profile_batch=0),
                     tf.keras.callbacks.ModelCheckpoint('logs/ckpt', 'val_top1', 0, True, True, 'max')])
```

Then change(load weights):

```

model.compile(tf.keras.optimizers.SGD(tf.keras.experimental.CosineDecay(.1, 50000//TRAIN_BATCH_SIZE*EPOCHS), .9),
              tf.keras.losses.SparseCategoricalCrossentropy(),
              [tf.keras.metrics.SparseTopKCategoricalAccuracy(1, name='top1')])
model.load_weights('logs/ckpt')  // <= Load weights
model.fit(ds_train,
          epochs=EPOCHS,
          initial_epoch=INITIAL_EPOCH,
          callbacks=[tf.keras.callbacks.TensorBoard('logs', histogram_freq=1, profile_batch=0),
                     tf.keras.callbacks.ModelCheckpoint('logs/ckpt', 'val_top1', 0, True, True, 'max')])
```

LR get from CosineDecay is 0, becauese Optimizer have a param of run steps, which is also save in ckpt.
We need to use `model.optimizer.iterations.assign(0)` between `Model.load_weights()` and `Model.Fit()`
@amahendrakar

**Comment by amahendrakar** [comment]
@HLSS-Hen,
On running the given code snippet I am facing an error stating `NameError: name 'ds_train' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7a30f5975b5f971e79dd4c41a73dc6ea/47115.ipynb).

Could you please provide the complete code snippet, so that we can reproduce the issue on our end. Alternatively, you can also run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by HLSS-Hen** [comment]
@amahendrakar [here](https://colab.research.google.com/drive/1sFaEse3NxATiyI9hTVNxYX1PNPD23ueU?usp=sharing)

**Comment by amahendrakar** [comment]
@HLSS-Hen,
On running the code, I am facing an error stating `NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for logs/0/ckpt`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6fadd34d835958cdc4b62794a15c76c6/47115.ipynb#scrollTo=3PjN7uxli9Rs).

Could you please confirm if this is the same error you are facing. Thanks!

**Comment by HLSS-Hen** [comment]
@amahendrakar this just my input error, [here](https://colab.research.google.com/drive/1sFaEse3NxATiyI9hTVNxYX1PNPD23ueU?usp=sharing). 
I have said before:
> I find that `tf.keras.Optimizer` has attribute `iterations`. which saves in ckpt, compute the `step`when call `CosineDecay.__call__(step)`.
> It's works right when I call `model.optimizer.iterations.assign(0)` after 'Model.load_weights()' and 'Model.compile()'.

**Comment by innat** [comment]
We're also facing the same issue. Is there any update on this?

**Comment by amahendrakar** [comment]
@ymodak,
Colab notebook crashes on running the code with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c87343c44e0c5459c887fdf78d663838/47115.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Colab crashes on TF 2.6 Nightly due to OOM error.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/68779064d7fae015281478dd4ed900a8/47115.ipynb).Thanks!

**Comment by laplacericky** [comment]
@HLSS-Hen Sometimes, people wants to not only save the model parameters but also the optimizer's state, the 'iteration' you are referring to is one of the important optimizer's state that some people wants to recover. Other important optimizer's states include momentums, etc..

If you do not want to keep any optimizer's state, you can use model.save_weights and load_weights with HDF5 format. Then you need to compile the model again.

Or

you can compile the model again with new optimizer instance after load_weights, i.e. model.compile(loss=loss,optimizer=new_instance_optimizer)

Or 

If you just wants to have other optimizer's states recovered except the iteration(which may not be reasonable), your way of directly resetting the hidden iteration attribute of the optimizer is acceptable.

**Comment by sachinprasadhs** [comment]
Could you please check with the stable API [tf.keras.optimizers.schedules.CosineDecay](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/CosineDecay) and let us know if the issue still persists. Thanks!
