### ISSUE TITLE
installation issue in intel core2 cpu 

### ISSUE THREAD

**Issue by mortalx2** [tensorflow/tensorflow#47119]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu 20.0.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version:version 2.5.0
- Python version:3.7.9
- Installed using virtualenv? pip? conda? usig pip
- Bazel version (if compiling from source):Bazel version 3 .7.2
- GCC/Compiler version (if compiling from source):gcc version 9.3.0
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the problem**
while installing tensorflow  2. 5.0 using source  in my old cpu (intel core 2 duo) i am getting error as :- attributeError: module 'tensorflow' has no attribute '__version__'  

how to solve this error ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
/python3.7 
/import tensorflow as tf
/print(tf.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute '__version__'

**Any other info / logs**
![error](https://user-images.githubusercontent.com/77532074/107810626-023b6880-6d93-11eb-887b-ead8f971e787.jpg)

to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@mortalx2,
Could you please share the following details with us, so that we can look into the issue

- output of `pip list` command
- output of `conda list` command
- the make and model of the CPU on your machine

Thanks!

**Comment by mortalx2** [comment]
(base) mortal-x2@mortalx2-desktop:~$ pip list
Package                            Version
---------------------------------- -----------------
absl-py                            0.10.0
aiofiles                           0.6.0
aiohttp                            3.6.3
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
appdirs                            1.4.4
APScheduler                        3.6.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      3.0.1
atomicwrites                       1.4.0
attrs                              20.2.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.9.3
bitarray                           1.6.1
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         4.2.0
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.4.1
clyent                             1.2.2
colorama                           0.4.4
conda                              4.9.2
conda-build                        3.20.5
conda-package-handling             1.7.2
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.1.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distlib                            0.3.1
distributed                        2.30.1
dm-tree                            0.1.5
docopt                             0.6.2
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
fbmessenger                        6.0.0
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
flatbuffers                        1.12
fsspec                             0.8.3
future                             0.18.2
gast                               0.4.0
gevent                             20.9.0
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.24.0
google-auth-oauthlib               0.4.2
google-pasta                       0.2.0
greenlet                           0.4.17
grpcio                             1.34.1
h11                                0.9.0
h5py                               3.1.0
HeapDict                           1.0.1
html5lib                           1.1
httpcore                           0.11.1
httptools                          0.1.1
httpx                              0.15.4
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.0.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
jeepney                            0.5.0
Jinja2                             2.11.2
joblib                             0.17.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
kafka-python                       2.0.2
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.2
keyring                            21.4.0
kiwisolver                         1.3.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.1
Markdown                           3.3.3
MarkupSafe                         1.1.1
matplotlib                         3.3.2
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.0
multidict                          4.7.6
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.5
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.5
opt-einsum                         3.3.0
packaging                          20.4
pandas                             1.1.3
pandocfilters                      1.4.3
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                21.0.1
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.8
protobuf                           3.14.0
psutil                             5.7.2
psycopg2-binary                    2.8.6
ptyprocess                         0.6.0
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.2
PyJWT                              1.7.1
pykwalify                          1.7.0
pylint                             2.6.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-crfsuite                    0.9.7
python-dateutil                    2.8.1
python-engineio                    3.13.2
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
python-socketio                    4.6.1
python-telegram-bot                12.8
pytz                               2020.1
PyWavelets                         1.1.1
pyxdg                              0.27
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
regex                              2020.9.27
requests                           2.24.0
requests-oauthlib                  1.3.0
requests-toolbelt                  0.9.1
rfc3986                            1.4.0
rocketchat-API                     1.9.1
rope                               0.18.0
rsa                                4.7
Rtree                              0.9.4
ruamel-yaml                        0.15.87
ruamel.yaml.clib                   0.2.2
sanic                              20.12.1
Sanic-Cors                         0.10.0.post3
Sanic-Plugins-Framework            0.9.5
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.2
seaborn                            0.11.0
SecretStorage                      3.1.2
Send2Trash                         1.5.0
sentry-sdk                         0.19.5
setuptools                         53.0.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
sklearn-crfsuite                   0.3.6
slackclient                        2.9.3
sniffio                            1.2.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tabulate                           0.8.7
tblib                              1.7.0
tensorboard                        2.4.1
tensorboard-plugin-wit             1.8.0
tensorflow                         2.5.0
tensorflow-estimator               2.4.0
tensorflow-probability             0.11.1
termcolor                          1.1.0
terminado                          0.9.1
terminaltables                     3.1.0
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
twilio                             6.45.4
typing-extensions                  3.7.4.3
tzlocal                            2.1
ujson                              3.2.0
unicodecsv                         0.14.1
urllib3                            1.25.11
uvloop                             0.14.0
virtualenv                         20.4.0
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
webexteamssdk                      1.6
websockets                         8.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.1
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
yarl                               1.6.3
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.1.2

**Comment by mortalx2** [comment]
(base) mortal-x2@mortalx2-desktop:~$ conda list
# packages in environment at /home/mortal-x2/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
_libgcc_mutex             0.1                        main  
absl-py                   0.10.0                   pypi_0    pypi
aiofiles                  0.6.0                    pypi_0    pypi
aiohttp                   3.6.3                    pypi_0    pypi
alabaster                 0.7.12                     py_0  
anaconda                  2020.11                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.10.0                   py38_0  
anaconda-project          0.8.4                      py_0  
apscheduler               3.6.3                    pypi_0    pypi
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38h7b6447c_1  
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.2            py38h7b6447c_0  
astunparse                1.6.3                    pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10                       py_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.2.0                   pypi_0    pypi
autopep8                  1.5.4                      py_0  
babel                     2.8.1              pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.6.1                      py_0  
backports.shutil_get_terminal_size 1.0.0                    py38_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
bitarray                  1.6.1            py38h27cfd23_0  
bkcharts                  0.2                      py38_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blosc                     1.20.1               hd408876_0  
bokeh                     2.2.3                    py38_0  
boto                      2.49.0                   py38_0  
bottleneck                1.3.2            py38heb32a55_1  
brotlipy                  0.7.0           py38h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.10.14                    0  
cachetools                4.2.0                    pypi_0    pypi
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.3           py38he30daa8_0  
chardet                   3.0.4                 py38_1003  
click                     7.1.2                      py_0  
cloudpickle               1.4.1                    pypi_0    pypi
clyent                    1.2.2                    py38_1  
colorama                  0.4.4                      py_0  
conda                     4.9.2            py38h06a4308_0  
conda-build               3.20.5                   py38_1  
conda-env                 2.6.0                         1  
conda-package-handling    1.7.2            py38h03888b9_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
cryptography              3.1.1            py38h1ba5d50_0  
curl                      7.71.1               hbc83047_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.21          py38he6710b0_0  
cytoolz                   0.11.0           py38h7b6447c_0  
dask                      2.30.0                     py_0  
dask-core                 2.30.0                     py_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
distributed               2.30.1           py38h06a4308_0  
dm-tree                   0.1.5                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.16                     py38_1  
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.10               he6710b0_2  
fastcache                 1.1.0            py38h7b6447c_0  
fbmessenger               6.0.0                    pypi_0    pypi
filelock                  3.0.12                     py_0  
flake8                    3.8.4                      py_0  
flask                     1.1.2                      py_0  
flatbuffers               1.12                     pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
fsspec                    0.8.3                      py_0  
future                    0.18.2                   py38_1  
gast                      0.4.0                    pypi_0    pypi
get_terminal_size         1.0.0                haa9412d_0  
gevent                    20.9.0           py38h7b6447c_0  
glib                      2.66.1               h92f7085_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py38hd5f6e3b_3  
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
graphite2                 1.3.14               h23475e2_0  
greenlet                  0.4.17           py38h7b6447c_0  
grpcio                    1.34.1                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h11                       0.9.0                    pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
harfbuzz                  2.4.0                hca77d97_1  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
httpcore                  0.11.1                   pypi_0    pypi
httptools                 0.1.1                    pypi_0    pypi
httpx                     0.15.4                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
iniconfig                 1.1.1                      py_0  
intel-openmp              2020.2                      254  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38hb070fc8_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_1  
isort                     5.6.4                      py_0  
itsdangerous              1.1.0                      py_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py38_0  
jeepney                   0.5.0              pyhd3eb1b0_0  
jinja2                    2.11.2                     py_0  
joblib                    0.17.0                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
kafka-python              2.0.2                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   21.4.0                   py38_1  
kiwisolver                1.3.0            py38h2531618_0  
krb5                      1.18.2               h173b8e3_0  
lazy-object-proxy         1.4.3            py38h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.4.2                h62408e4_0  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblief                   0.10.1               he6710b0_0  
libllvm10                 10.0.1               hbcb73fb_5  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libtool                   2.4.6             h7b6447c_1005  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
libxslt                   1.1.34               hc22bd24_0  
llvmlite                  0.34.0           py38h269e1b5_4  
locket                    0.2.0                    py38_1  
lxml                      4.6.1            py38hefd8a0e_0  
lz4-c                     1.9.2                heb0550a_3  
lzo                       2.10                 h7b6447c_2  
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py38h817c723_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
mock                      4.0.2                      py_0  
more-itertools            8.6.0              pyhd3eb1b0_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.1.0                    py38_0  
msgpack-python            1.0.0            py38hfd86e86_1  
multidict                 4.7.6                    pypi_0    pypi
multipledispatch          0.6.0                    py38_0  
navigator-updater         0.2.1                    py38_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
nltk                      3.5                        py_0  
nose                      1.3.7                    py38_2  
notebook                  6.1.4                    py38_0  
numba                     0.51.2           py38h0573a6f_1  
numexpr                   2.7.1            py38h423224d_0  
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.19.2           py38hfa32c7d_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1h               h7b6447c_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0  
pandas                    1.1.3            py38he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py38h06a4308_1  
pango                     1.45.3               hd140c19_0  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
patchelf                  0.12                 he6710b0_0  
path                      15.0.0                   py38_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py38_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py38_0  
pcre                      8.44                 he6710b0_0  
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    8.0.1            py38he98fc37_0  
pip                       20.2.4           py38h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
pkginfo                   1.6.1            py38h06a4308_0  
pluggy                    0.13.1                   py38_0  
ply                       3.11                     py38_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.7.2            py38h7b6447c_0  
psycopg2-binary           2.8.6                    pypi_0    pypi
ptyprocess                0.6.0                    py38_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py38h403a769_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38h1ba5d50_0  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pyjwt                     1.7.1                    pypi_0    pypi
pykwalify                 1.7.0                    pypi_0    pypi
pylint                    2.6.0                    py38_0  
pyodbc                    4.0.30           py38he6710b0_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysocks                   1.7.1                    py38_0  
pytables                  3.6.1            py38h9fd0a39_0  
pytest                    6.1.1                    py38_0  
python                    3.8.5                h7579374_1  
python-crfsuite           0.9.7                    pypi_0    pypi
python-dateutil           2.8.1                      py_0  
python-engineio           3.13.2                   pypi_0    pypi
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.35.1                     py_0  
python-libarchive-c       2.9                        py_0  
python-socketio           4.6.1                    pypi_0    pypi
python-telegram-bot       12.8                     pypi_0    pypi
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py38h7b6447c_2  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.3.1            py38h7b6447c_1  
pyzmq                     19.0.2           py38he6710b0_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.9.27                pypi_0    pypi
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                    pypi_0    pypi
requests-toolbelt         0.9.1                    pypi_0    pypi
rfc3986                   1.4.0                    pypi_0    pypi
ripgrep                   12.1.1                        0  
rocketchat-api            1.9.1                    pypi_0    pypi
rope                      0.18.0                     py_0  
rsa                       4.7                      pypi_0    pypi
rtree                     0.9.4                    py38_1  
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
ruamel_yaml               0.15.87          py38h7b6447c_1  
sanic                     20.12.1                  pypi_0    pypi
sanic-cors                0.10.0.post3             pypi_0    pypi
sanic-plugins-framework   0.9.5                    pypi_0    pypi
scikit-image              0.17.2           py38hdf5156a_0  
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.5.2            py38h0b6359f_0  
seaborn                   0.11.0                     py_0  
secretstorage             3.1.2                    py38_0  
send2trash                1.5.0                    py38_0  
sentry-sdk                0.19.5                   pypi_0    pypi
setuptools                50.3.1           py38h06a4308_1  
simplegeneric             0.8.1                    py38_2  
singledispatch            3.4.0.3                 py_1001  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
sklearn-crfsuite          0.3.6                    pypi_0    pypi
slackclient               2.9.3                    pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.1                      py_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.1.5                    py38_0  
spyder-kernels            1.9.4                    py38_0  
sqlalchemy                1.3.20           py38h7b6447c_0  
sqlite                    3.33.0               h62c20be_0  
statsmodels               0.12.0           py38h7b6447c_0  
sympy                     1.6.2            py38h06a4308_1  
tabulate                  0.8.7                    pypi_0    pypi
tbb                       2020.3               hfd86e86_0  
tblib                     1.7.0                      py_0  
tensorboard               2.4.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-probability    0.11.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0  
terminaltables            3.1.0                    pypi_0    pypi
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2020.10.1        py38hdd07704_2  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
toolz                     0.11.1                     py_0  
tornado                   6.0.4            py38h7b6447c_1  
tqdm                      4.50.2                     py_0  
traitlets                 5.0.5                      py_0  
twilio                    6.45.4                   pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
tzlocal                   2.1                      pypi_0    pypi
ujson                     3.2.0                    pypi_0    pypi
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                h7b6447c_0  
urllib3                   1.25.11                    py_0  
uvloop                    0.14.0                   pypi_0    pypi
watchdog                  0.10.3                   py38_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
webexteamssdk             1.6                      pypi_0    pypi
websockets                8.1                      pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.12.1                   pypi_0    pypi
wurlitzer                 2.0.1                    py38_0  
xlrd                      1.2.0                      py_0  
xlsxwriter                1.3.7                      py_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.3                he6710b0_3  
zict                      2.0.0                      py_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.1.2            py38h7b6447c_0  
zstd                      1.4.5                h9ceee32_0

**Comment by mortalx2** [comment]
model no of the cpu is core 2 duo

**Comment by amahendrakar** [comment]
@mortalx2,
Could you please try installing TensorFlow in a new virtual environment and check if you are facing the same issue? Thanks!

**Comment by mortalx2** [comment]
kk let me try

**Comment by mortalx2** [comment]
same issue is coming

**Comment by amahendrakar** [comment]
@mortalx2,
Could you please share the output of the `cat /proc/cpuinfo` command with us? Thanks!
