### ISSUE TITLE
TF Lite benchmark NOT_EQUAL node takes up a lot of time.

### ISSUE THREAD

**Issue by Jkeezuz** [tensorflow/tensorflow#47111]
Hi,

Tensorflow used for both model and benchmark: 2.3.1
Platform: Android

I've got an internal company model (therefore can't share it, sorry). 
I've run tflite benchmark model on it and got weird results. Namely the NOT_EQUAL op apparently takes 73 ms to run, which is big part of computation time, the problem is that it does not block running other nodes (they run between the 1st ms and 38th ms of computation) therefore I'm not sure why benchmark reports that this node runs for 73ms if it doesn't actually block other nodes. 

Screen of the report:
![perf_not_equal](https://user-images.githubusercontent.com/32575801/107762540-780ce900-6d2d-11eb-8c08-b30c3812f4cb.png)

As you can see the cast, expand_dims etc. nodes don't start after 73ms but rather instantaneously which is confusing because when it comes to the total running time of model these 73ms are counted and added to the X ms of rest of the model, therefore it reports the whole model running time to be 73+x ms. 

When it comes to the node it only takes one of the inputs to the model as the input to the node, nothing else, therefore in theory it shouldn't wait for anything (I assume it waits for something if it starts but doesn't block computation).

Could you please give me some help about what's going on here? Thanks.

**Comment by amahendrakar** [comment]
> I've got an internal company model (therefore can't share it, sorry).

@Jkeezuz,
In this case, could you please provide a dummy model and code so that we can reproduce the issue on our end.

Also, please check if you are facing the same issue with TF v2.4.1 and TF-nightly as well. Thanks!
