### ISSUE TITLE
Extend tensorflow/examples for raspberry_pi

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#47113]
Is there any plan to extend the TensorFlow/examples for raspberry_pi? Those which are shown at https://www.tensorflow.org/lite/examples are not all for raspberry_pi though ...

**Comment by mohantym** [comment]
Hi @peter197321!
We are checking to see whether you still need help in this issue . Have you checked this [thread ](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/raspberry_pi)yet? Thanks!
