### ISSUE TITLE
TF Lite Benchmark randomly throws errors.

### ISSUE THREAD

**Issue by Keezuu** [tensorflow/tensorflow#47110]
Hi,

I'm using TF Lite benchmark to benchmark a model we use internally in company (therefore I can't share it, sorry). Unfortunately when trying to run the model with given command:

`
./benchmark_model --graph=models/fp-full.v3.tflite --input_layer="in1,in2,in3,in4" --input_layer_shape="1,50:1:1:1,10" —input_layer_value_range=“in1,30,30:in2,0,0:in3,0,0:in4,0,0"        
`

The benchmark randomly either runs correctly or throws the given error:

`ERROR: tensorflow/lite/kernels/range.cc:45 (start > limit && delta < 0) || (start < limit && delta > 0) was not true.
ERROR: Node number 198 (RANGE) failed to invoke.`

As you see in the command I've specified the range of values to single value (I've also tried other values and it always ended the same, with randomly throwing the error) therefore there should be nothing random when running the model, but still it randomly fails. 

Could you please give me some tips what might be causing this behaviour? 

The inputs to the model are as follows (checked in Netron):
**in1**: int32[1,1]
**in2**: int32[1]
**in3**: float32[1]
**in4**: float32[1,1]

I use Tensorflow 2.3.1 for both model and benchmark.

**Comment by Saduf2019** [comment]
@Jkeezuz 
please refer to similar resolved issues and let us know, #35661, #40504

**Comment by miaout17** [comment]
Hi @Jkeezuz 

The TensorFlow Lite benchmark tools feeds random input data to the model. It has a constraint that it only works if the model can handle arbitrary data. It seems your model contains a number of integer ID inputs, which are only valid in a specific range. In this case, you may need to implement your own benchmark instead of using the existing tool. 

Let us know if you have any further questions.

**Comment by Jkeezuz** [comment]
Thanks @Saduf2019, I will take a look at this.
@miaout17 but as far as I'm aware I can specify the input ranges with --input_layer_value_range, right? And I even do this in the command in the post and I specify the range to be single value range.

I've also tried to run the benchmark with --input_layer_value_files argument providing fixed input as files, but the benchmark fails with segmentation fault. 

As far as I understand with given input to the model: 
input_ids = [1, 48, 51, 84, 2, 61, 54, 2, 56, 41, 2, 18, 63, 74, 41, 10]
I should be able to run the model if I encode those values as binary as in attached file, right?

[input_ids_4b_new.bin.zip](https://github.com/tensorflow/tensorflow/files/5995835/input_ids_4b_new.bin.zip)
