### ISSUE TITLE
Model still getting updated even set the trainable flag to be False 

### ISSUE THREAD

**Issue by TIANHAO-WANG** [tensorflow/tensorflow#47125]
I have a trained DNN `model`, and I hope to find the input `x` that maximize `model.predict(x)` through gradient descent. Here's what I did:

```python
def minimize_output(model, input_dim):
  N = input_dim
  model.trainable = False
  model.compile(optimizer='adam', loss='mean_squared_error')
  
  x = tf.Variable( np.random.uniform(-1, 1, (1, N, 1)) , name='subset', dtype=tf.float32)

  x_sigmoid = tf.sigmoid(x)
  x_target = -model(x_sigmoid)

  optimizer = tf.train.AdamOptimizer()
  train = optimizer.minimize(x_target, var_list=[subset])

  init = tf.initialize_all_variables()

  with tf.Session() as session:
      session.run(init)
      for step in range(2000):
        session.run(train)
        print("step", step, "target", x_target.eval())
      subset_pred = session.run(x_sigmoid)
  return subset_pred.reshape(-1)

min_input = minimize_output(model, input_dim=N)
```

However, it seems that value of `model.predict(min_input)` is much smaller than `-x_target.eval()`, therefore I think model is still updating during the Session. I have no idea why that happen, I already set model to be `model.trainable = False` and `var_lst=[subset]` for the optimizer.

Anyone have any idea how can I freeze the model during the training session? Thanks a lot!!!

**Comment by TIANHAO-WANG** [comment]
Here's output of `min_input = minimize_output(model, input_dim=N)`:

step 1990 target [[-0.9065793]]
step 1991 target [[-0.90662825]]
step 1992 target [[-0.9066771]]
step 1993 target [[-0.90672606]]
step 1994 target [[-0.906775]]
step 1995 target [[-0.90682375]]
step 1996 target [[-0.9068723]]
step 1997 target [[-0.906921]]
step 1998 target [[-0.90696967]]
step 1999 target [[-0.9070183]]

However, the output of `model.predict(min_input)` is `[[0.7591585]]`, which is supposed to be `[[-0.9070183]]`.

**Comment by amahendrakar** [comment]
@TIANHAO-WANG,
On running the given code snippet, I am facing an error stating `NameError: name 'model' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/582b6268fc47d068e86247cc4e4bfa08/47125.ipynb).

In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
