### ISSUE TITLE
Flex Delegate bazel build for C api

### ISSUE THREAD

**Issue by henry8th** [tensorflow/tensorflow#47120]
Hi, A bit unsure as to what category this would fall under so Iv chosen miscellaneous.
There is no documentation regarding the usage of flex delegates for the C api
I have tried the command 

bazel build --config=android_arm64 --config=monolithic --cxxopt=--std=c++11 --define=with_select_tf_ops=true -c opt //tensorflow/lite/c:libtensorflowlite_c.so //tensorflow/lite/delegates/flex:delegate

however it fails, i can provide the logs if required.

What are the ways to go about building a libtensorflowlite_c.so file that support flex delegates for android?
Thank you

**Comment by Saduf2019** [comment]
@henry8th 
Can you please refer to this [link](https://www.tensorflow.org/lite/guide/ops_select) and let us know.

**Comment by henry8th** [comment]
Hi thanks for getting back to me It includes details for all supported
languages bar C,
The c++ option doesn't work for me.
I have opted to use other languages as opposed to forcing it with C
Many thanks

**Comment by terryheo** [comment]
@thaink don't we have a way to build flex via C api ? (at least via selective build?)

**Comment by thaink** [comment]
@terryheo @henry8th The //tensorflow/lite/delegates/flex:delegate rule is not intended to build standalone .so file for flex delegate. 
Can you try adding following line to //tensorflow/lite/delegates/flex/BUILD:
```
load("//tensorflow/lite:build_def.bzl", "tflite_cc_shared_object")

tflite_cc_shared_object(
    name = "tensorflowlite-select-tf-ops",
    features = ["windows_export_all_symbols"],
    linkopts = select({
        "//tensorflow:macos": [
            "-Wl,-exported_symbols_list,$(location //tensorflow/lite:tflite_exported_symbols.lds)",
        ],
        "//tensorflow:windows": [],
        "//conditions:default": [
            "-Wl,-z,defs",
            "-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)",
        ],
    }),
    per_os_targets = True,
    deps = [
        ":delegate",
        "//tensorflow/lite:tflite_exported_symbols.lds",
        "//tensorflow/lite:tflite_version_script.lds",
    ],
)

```
The build it with --nocheck_visibility and try it.

**Comment by FengMu1995** [comment]
How to use the libtensorflowlite_flex.so in my project built with cmake
