### ISSUE TITLE
Memory leak loading keras model in loop

### ISSUE THREAD

**Issue by danzafar** [tensorflow/tensorflow#47122]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.2
- Python version:3.7

**Problem Statement**
Running the following code:
```
import tensorflow as tf
def process_start():
  model = tf.keras.models.load_model(r"/large/model/file")
while True:
  process_start()
```
Crashes my VM after some time due to OOM. Takes about 40m with a 4gb VM.
![image](https://user-images.githubusercontent.com/57200935/107836994-45c6b000-6d5c-11eb-96f3-54b4278e815b.png)

I also get these messages:
```
Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x7f24557770d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x7f2455771750>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.
```

**Describe the expected behavior**
Should be able to run this in loops as needed.

**More info**
I saw from https://github.com/tensorflow/tensorflow/issues/24695 that _Keras Layers are numbered globally within the Python process_. My guess is that every time the model is loaded it's assigning some variables that don't get properly cleaned up.

I believe this is a bug. Is there a suggested workaround or advice here?

**Comment by Saduf2019** [comment]
@danzafar 
Please share all dependencies for us to replicate the issue faced, I ran the code shared and face [this error](https://colab.research.google.com/gist/Saduf2019/159e5dc4670056f801c2ff2dac7b0181/untitled533.ipynb).
