### ISSUE TITLE
How to use tensor on the tensorflow lite  like tensorflow tensor operation? For example, tensor ascend dimension ,reduction dimension and tensor  slice. Thanks.

### ISSUE THREAD

**Issue by 158703127** [tensorflow/tensorflow#47138]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by 158703127** [comment]
Please help me!Thanks!

**Comment by teijeong** [comment]
Hi, if it's a question, please use stackoverflow for faster answer. I not sure if I get it correctly, but if you want to try if how those ops work in TFLite model, you can make a TF model and convert it to TFLite model. dimensionality manipulation and slice ops can be supported partially with RESHAPE and STRIDED_SLICE ops in TFLite.

**Comment by 158703127** [comment]
> Hi, if it's a question, please use stackoverflow for faster answer. I not sure if I get it correctly, but if you want to try if how those ops work in TFLite model, you can make a TF model and convert it to TFLite model. dimensionality manipulation and slice ops can be supported partially with RESHAPE and STRIDED_SLICE ops in TFLite.

Hi, I integrated TFLite on android by using TFLite .a static lib.  TFLite support TfLiteTensor class, not support Tensor class, can't find RESHAPE and STRIDED_SLICE API in  TfLiteTensor. Thanks!

**Comment by teijeong** [comment]
Operations on the tensor is actually another op in the computation graph. That being said, the graph would be like

TfLiteTensor -> RESHAPE op -> new TfLiteTensor with new shape.

I still don't get what you're actually trying to achieve. What part of the graph you're trying to modify?

**Comment by jvishnuvardhan** [comment]
@158703127 If you are looking for RESHAPE op, may be the example provided in [this issue](https://github.com/tensorflow/tensorflow/issues/45150) might help. 

Please provide any standalone code to reproduce the issue. If you have a general question, please post them in Stackoverflow as GitHub is mainly for bugs and performance related issue. There is a large community on Stackoverflow that support general questions. Thanks!
