### ISSUE TITLE
Can't set empty layer name

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#47131]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):2.4
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Get variable name like 'dense/kernel:0'
**Describe the expected behavior**
Get variable name like 'kernel:0'

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
dense = tf.keras.layers.Dense(16, name='')
dense(tf.ones([16, 16]))
dense.weights[0].name
```
https://colab.research.google.com/drive/1KBzEMwJtMsgSoIfUieLBV9_5iLKmik46?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
> **Describe the expected behavior**
> Get variable name like 'dense/kernel:0'

@fsx950223,
On running the given Colab notebook with TensorFlow v2.4.1, I got the 'expected behavior'. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ff7e9c9c2ae7181edb87a28a1b177022/47131.ipynb#scrollTo=QoCm0cbfN50k). Thanks!

**Comment by fsx950223** [comment]
Sorry, I swap the current behavior and the expected behavior by mistake.
I have updated the comment.

**Comment by pao0318** [comment]
Hyy, I have descibed the issue.
The explaination is that tensorflow by default gives the info about the layer which is created by the user. If you want to give the custom name of the layer you should pass it to the **name**=" some_name" or if you want it to be empty it cant be possible but an alternate solution is by passing space in the **name**=" "

Here is the link to your notebook:
[https://colab.research.google.com/drive/1KBzEMwJtMsgSoIfUieLBV9_5iLKmik46?usp=sharing](url)

**Comment by fsx950223** [comment]
> Hyy, I have descibed the issue.
> The explaination is that tensorflow by default gives the info about the layer which is created by the user. If you want to give the custom name of the layer you should pass it to the **name**=" some_name" or if you want it to be empty it cant be possible but an alternate solution is by passing space in the **name**=" "
> 
> Here is the link to your notebook:
> [https://colab.research.google.com/drive/1KBzEMwJtMsgSoIfUieLBV9_5iLKmik46?usp=sharing](url)

It's impossible
``` python
input = tf.keras.layers.Input((6 ,6))
output = tf.keras.layers.Dense(128)(input)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 856, in _infer_output_signature
    with backend.name_scope(self._name_scope()):
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6650, in __enter__
    scope_name = scope.__enter__()
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/fangsixie/.conda/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4246, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: ' /' is not a valid scope name
```

**Comment by fsx950223** [comment]
BTW, I met this issue when I try to transfer JAX's weights to Tensorflow's weights. Since sometimes JAX weights don't have layer name, e.g: VIT.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/05756d04a1196ad097c9009027218c7b/47131.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@fsx950223 I can reproduce this with recent TF2.6 and `tf-nightly`. May be this is a intended behavior. As the layer is of dense, default name includes `dense`.

As Keras moved to separate repo (i can't move the issue), can you please close here and open in keras repo https://github.com/keras-team/keras/issues

Keras team is focussed on the new repo mentioned above.

Thanks!
