### ISSUE TITLE
InaccessibleTensorError for tensor defined in same scope

### ISSUE THREAD

**Issue by nicolasshu** [tensorflow/tensorflow#47139]
Hello
I am for some reason getting an error in Tensorflow 2.2 stating that I am not being able to access a tensor when created within the same scope, but using `tf.function`

```python
import tensorflow as tf
cosine_loss = tf.keras.losses.CosineSimilarity(axis=0,reduction=tf.keras.losses.Reduction.NONE)
@tf.function
def func():
    A = tf.convert_to_tensor([[1,1.,1],[1,3,1]])
    B = tf.convert_to_tensor([[1,1.,1]])

    S = []
    for b in B:
        S_n = []
        for a in A:
            S.append(-cosine_loss(a,b))
        S.append(S_n)
    
    return S
print(func())
```

```
InaccessibleTensorError: The tensor 'Tensor("while/while/Neg:0", shape=(), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=while_while_body_55, id=140111838031568); accessed from: FuncGraph(name=func, id=140111839241488).
```

Why is this not being able to access it?
Thank you

**Comment by Saduf2019** [comment]
@nicolasshu 
The code shared seems incomplete, I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/44c2eed897f05554b7e516b7982fecdf/untitled530.ipynb)

**Comment by nicolasshu** [comment]
Sorry. That was my bad. I just updated it

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/1ac6960e24bfd171dc59167629851572/untitled535.ipynb).

**Comment by rmothukuru** [comment]
@nicolasshu,
Documentation of [TF.Function](https://www.tensorflow.org/api_docs/python/tf/function#example_usage_2) states:

> Key Point: Any Python side-effects (appending to a list, printing with print, etc) will only happen once, when func is traced. To have side-effects executed into your tf.function they need to be written as TF ops:

Instead, use TensorFlow collections like tf.TensorArray:

```python
@tf.function
def f(x):
  ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
  for i in range(len(x)):
    ta = ta.write(i, x[i] + 1)
  return ta.stack()
f(tf.constant([1, 2, 3]))
```
So, replacing `Lists` and `List Operations` with `TensorArray` should resolve your issue.
