### ISSUE TITLE
Data provided by a keras.utils.sequence DataGenerator has None dimensions when used to fit Model subclass

### ISSUE THREAD

**Issue by 05hazza06** [tensorflow/tensorflow#47133]
Code is written using Google Colab on Tensorflow Version 2.4.1

A DataGenerator subclassing keras.utils.sequence is providing data of correct shape when used to fit a sequential model. However, when used to fit a custom model subclassing keras.Model the input dimensions become (None, None, None, None) in the call method during the first training epoch.

When the custom model is fit using the DataGenerator the input dimensions to the call method should be (16, 256, 128, 3).

A simplified recreation of the issue is provided on Google Colab in the following notebook:
[Colab Notebook](https://colab.research.google.com/drive/1VqPc6Wn2tIND6myoZyFWXhGiMispiDxJ#scrollTo=KMRPZrfQE3KA)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3117d9916427e0ddd9e12beaa96f2329/47133.ipynb). Thanks!

**Comment by rthadur** [comment]
cc @amahendrakar @rmothukuru

**Comment by tomerk** [comment]
Can you try switching your input pipeline to be `tf.data` based instead? That should make it generally more performant anyways.

**Comment by rmothukuru** [comment]
@05hazza06,
Can you please respond to the above comment? Thanks!

**Comment by 05hazza06** [comment]
The tf.data dataset implementation worked as expected. Thanks.
Still unsure about why Keras sequence didn't work but the issue is sorted.
