### ISSUE TITLE
com_github_apple_swift_swift_protobuf sha256 mismatch in tensorflow/workspace.bzl

### ISSUE THREAD

**Issue by eichin** [tensorflow/tensorflow#47137]
**System information**

In reference to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl on master, as-written.

**Describe the current behavior**

While digging in to an unrelated buildsystem problem, I noticed that
```
    # https://github.com/apple/swift-protobuf/releases
    tf_http_archive(
        name = "com_github_apple_swift_swift_protobuf",
        strip_prefix = "swift-protobuf-1.6.0/",
        sha256 = "4ccf6e5ea558e8287bf6331f9f6e52b3c321fca5f1d181d03680f415c32a6bba",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/apple/swift-protobuf/archive/1.6.0.zip",
            "https://github.com/apple/swift-protobuf/archive/1.6.0.zip",
        ],
    )
```

has a `sha256` value that doesn't match what I get from either source.  Note that I'm looking at this from a "prepare for offline builds" perspective, I don't know if the normal build system will actually fetch this, or if "everyone" already has the matching version cached, or if something else is going on (like the `intel/mkl-dnn` archive-rename problem.)

**Describe the expected behavior**

The particular values in `workspace.bzl` have been unchanged for a while.  I don't know if the upstream has changed or not, intentionally, but specific releases aren't supposed to; that's one reason for the hash checks...

**Standalone code to reproduce the issue**

```
workbench$ wget https://storage.googleapis.com/mirror.tensorflow.org/github.com/apple/swift-protobuf/archive/1.6.0.zip
2021-02-13 18:49:23 (9.31 MB/s) - ‘1.6.0.zip’ saved [1918999/1918999]
workbench$ sha256sum 1.6.0.zip 
4d6d2543da84474fe50a543f70ba145d99c4d14a4aac10d7b3c7dc9f0f7ecec3  1.6.0.zip
workbench$ rm 1.6.0.zip 
workbench$ wget https://github.com/apple/swift-protobuf/archive/1.6.0.zip
2021-02-13 18:49:43 (8.42 MB/s) - ‘1.6.0.zip’ saved [1918999/1918999]
workbench$ sha256sum 1.6.0.zip 
4d6d2543da84474fe50a543f70ba145d99c4d14a4aac10d7b3c7dc9f0f7ecec3  1.6.0.zip
```
(and note that 4d6.*ec3 does not match the 4cc.*bba in the `.bzl` file.)

**Other info / logs**

Vaguely related: https://github.com/tensorflow/tensorflow/issues/12979 and https://github.com/libgit2/libgit2/issues/4343 that suggest that "it is known" that github archive hashes change when github itself updates; usually the `storage.googleapis.com/mirror.tensorflow.org` links are enough to cover for that but it looks like they match now.

**Comment by mihaimaruseac** [comment]
I think this should be fixed now as we bumped this dep several times.
