### ISSUE TITLE
Incorrect console print output while printing tensor generated from tf.image.grayscale_to_rgb api in Tensorflow 1.2

### ISSUE THREAD

**Issue by ssnirgudkar** [tensorflow/tensorflow#47136]
I am trying to convert a grayscale png image into rgb. I am using Tensor version 1.2. When I print the output of the converted tensor on console, it shows me zero in all 3 channels. If I visualize the output on tensor board, it shows the image just fine. 

I tried doing the same in Tensor 2.4 and it works fine there. Is there a bug in printing on 1.2 version? 

import tensorflow as tf
import os
import numpy as np
from datetime import datetime

logdir = "logs/" + datetime.now().strftime("%Y%m%d-%H%M%S")
image_list = ['<full path of IR image.png>']
            
sess = tf.InteractiveSession()
imageHandle = tf.read_file(image_list[0])

image_tensor = tf.image.decode_png(imageHandle, dtype=tf.uint8) 
image_tensor = tf.reshape(image_tensor, [1, 512, 640, 1])
image_tensor = tf.Print(image_tensor, [image_tensor], "*** read_images_from_decode_png", summarize=900) # **This print is correct**

image_tensor1 = tf.image.grayscale_to_rgb(image_tensor)
image_tensor1 = tf.Print(image_tensor1, [image_tensor1], "*** read_images_from_disk_grayscale2rgb", summarize=900) # **This print is wrong**

summary_op3 = tf.summary.image('config/config', image_tensor1)
summary_writer = tf.summary.FileWriter(logdir, sess.graph)
text = sess.run(summary_op3)
summary_writer.flush()
summary_writer.close()

**Comment by Saduf2019** [comment]
@ssnirgudkar 
I ran the code shared and face a [different error](https://colab.research.google.com/gist/Saduf2019/a283a1c09743316b1cb00511248c1150/untitled530.ipynb), please share all dependencies , if possible share a colab gist with the error reported.

**Comment by ssnirgudkar** [comment]
[
![1603392383 356605_color](https://user-images.githubusercontent.com/37679575/107960318-797b2300-6f72-11eb-976a-17e23d85c25a.png)
](url)

image_list = ['1603392383 356605_color.png']

I have attached a png file (1603392383 356605_color.png). From my original script, please adjust the variable 'image_list' to point to the path of this image and you should be able to reproduce the problem.

Also I noticed that you are using TensorFlow 1.15, my environment is TensorFlow 1.2. It is important to keep the environment same to reproduce the issue.

**Comment by Saduf2019** [comment]
@ssnirgudkar
There is no support for 1.x, there is support only for 2.x only, in case it is working fine on 2.x please move this issue to closed status.

**Comment by ssnirgudkar** [comment]
Can you confirm if you can reproduce the issue which I am seeing (TF 1.2) at your end? I am not necessarily asking to fix the problem. The code which I am using is a legacy code and it will take some time/effort to port this code on TF 2.X.
But it is important for me to know that this issue exists (or not) so that I can focus on other parts of the system.

**Comment by Saduf2019** [comment]
@ssnirgudkar 
I ran the code with the image shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d5380a6e71ab5999064c2a0ae1807f4e/untitled543.ipynb) and confirm if this is the error faced.

**Comment by ssnirgudkar** [comment]
Sorry, one typo in the script. Can you please change 'reshape' line to following ?

image_tensor = tf.reshape(image_tensor, [1, 512, 640, **3**])

Also, again to reiterate the TF version is **1.2** not 1.12.

**Comment by Saduf2019** [comment]
@ssnirgudkar 
We will not be able to replicate this on tf 1.2, please upgrade to 2.x as informed earlier and move this issue to closed status if there is no error or create a new issue in case you face any errors.
