### ISSUE TITLE
[tflite] Problem reading multi-input tflite model with Java

### ISSUE THREAD

**Issue by AlxndrMlk** [tensorflow/tensorflow#47134]
Hi,

with a colleague of mine, we've build a two-input model using TF2's Functional API. We want to deploy this model in Android, using `tflite` and Java.

## Model

The model has the following architecture

```{python}
# Inputs
in1 = keras.Input(shape = (24, 7), name = 'in_1')
in2 = keras.Input(shape = (2,), name = 'in_2')

# Model
x1 = keras.layers.LSTM(48, return_sequences = True)(in1)
x1 = keras.layers.LSTM(48)(x1)

x2 = keras.layers.Dense(16, activation = 'relu')(in2)
x2 = keras.layers.Dense(8, activation = 'relu')(x2)

x = keras.layers.concatenate([x1, x2], name = 'concat_00')

x = keras.layers.Dense(128, activation = 'relu', name = 'concat_dense_00')(x)
x = keras.layers.Dropout(.2)(x)
x = keras.layers.Dense(64, activation = 'relu', name = 'concat_dense_02')(x)
x = keras.layers.Dropout(.2)(x)
output = keras.layers.Dense(12)(x)

model_lstm_3 = keras.Model(inputs = [in1, in2], outputs = output)
```

## `tflite` conversion

The model had been converted to `tflite` format, using TF 2.3 and the following code:

```{python}
converter = tf.lite.TFLiteConverter.from_keras_model(model_lstm_3)
tflite_model = converter.convert()
````

## Reading the model in Java

We're trying to read in the model in Java using the following code:

```{java}
tflite = Interpreter(loadModelFile(activity, "model_simple.tflite"))

var output = arrayOf(0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f)
val geoData = arrayOf(arrayOf(arrayOf(52.26240269140683f, 20.971026685407484f)))
val historicData = arrayOf(arrayOf(
    // arrayListOf(....),
    arrayOf(1f, 1f, 0.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 1.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 2.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 3.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 4.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 5.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 6.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 7.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 8.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 9.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 10.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 11.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 12.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 13.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 14.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 15.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 16.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 17.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 18.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 19.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 20.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 21.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 22.0f, 1f, 1f, 1f, 2020f),
    arrayOf(1f, 1f, 23.0f, 1f, 1f, 1f, 2020f),
))
var floatInput = arrayOf<Array<Array<Array<Float>>>>(geoData, historicData)

Timber.d("Input model $floatInput")
tflite!!.run(floatInput, output)
Timber.d("Output model $output")
```

## Exception

The line `tflite!!.run(floatInput, output)` generates the following exception:

```{java}
java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of [[[[Ljava.lang.Float;
        at org.tensorflow.lite.Tensor.dataTypeOf(Tensor.java:352)
        at org.tensorflow.lite.Tensor.throwIfTypeIsIncompatible(Tensor.java:418)
        at org.tensorflow.lite.Tensor.getInputShapeIfDifferent(Tensor.java:287)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:146)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:319)
```

## Java libs

```
implementation('org.tensorflow:tensorflow-lite:2.4.0')
implementation('org.tensorflow:tensorflow-lite-gpu:2.4.0')
implementation('org.tensorflow:tensorflow-lite-support:0.0.0-nightly')
```

We're not sure how to solve this and we'll be grateful for any hints.

Thank you!

**Comment by teijeong** [comment]
You might want to use `runForMultipleInputsOutputs` instead of `run`.

**Comment by AlxndrMlk** [comment]
@teijeong - thank you, we'll check this option.

**Comment by tajchert** [comment]
Sadly there is still an issue:
java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of [[[Ljava.lang.Float;

![image](https://user-images.githubusercontent.com/2962633/108109758-a161a800-7092-11eb-9194-7ee8ebc8013a.png)

**Comment by AlxndrMlk** [comment]
@teijeong, unfortunately `runForMultipleInputsOutputs` did not solve the problem.

I also exported the model once again, usinf TF 2.4.1, but the outcome is the same.

Any other suggestions?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
