### ISSUE TITLE
Hi I am trying to compile on windows and get errors

### ISSUE THREAD

**Issue by divastar** [tensorflow/tensorflow#47144]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): trying to install from source
- TensorFlow version:2.2
- Python version:3.9
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):3.73
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.2/8.1.0.77
- GPU model and memory:RTX 2080/ 15.9GB

**Describe the problem** I followed everything explained in this tutorial https://towardsdatascience.com/how-to-compile-tensorflow-2-3-with-cuda-11-1-8cbecffcb8d3
until the command :
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

where I got :
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/418c218efa950245ba075b9bb3a53505b807c5df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (419 packages loaded, 27891 targets configured).
INFO: Found 1 target...
ERROR: C:/users/korin/tensorflow/tensorflow/core/profiler/internal/gpu/BUILD:108:16: undeclared inclusion(s) in rule '//tensorflow/core/profiler/internal/gpu:cupti_wrapper':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/profiler/internal/gpu/cupti_wrapper.cc':
  'tensorflow/stream_executor/cuda/cuda_activation.h'
  'tensorflow/stream_executor/gpu/gpu_activation.h'
cl : Command line warning D9035 : option 'experimental:preprocessor' has been deprecated and will be removed in a future release
cl : Command line warning D9036 : use 'Zc:preprocessor' instead of 'experimental:preprocessor'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1356.616s, Critical Path: 249.97s
INFO: 7667 processes: 3916 internal, 3751 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by divastar** [comment]
python 3.8

**Comment by amahendrakar** [comment]
@divastar,
Every TensorFlow release is compatible with a certain CUDA/cuDNN version. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu). 

Could you please run the `bazel clean --expunge` command and then try building the latest version of **TensorFlow v2.4** with **CUDA 11.0** and **cuDNN 8** and check if you are facing the same issue.

 Also, follow the [official guide](https://www.tensorflow.org/install/source_windows) while building TensorFlow from source. Thanks!

**Comment by divastar** [comment]
I am working on it. Thank you

**Comment by divastar** [comment]
Hi .
So I uinstalled cuda 11.0 cudnn 8.0.1.13
made a new environment with conda python 3.6
bazel 3.7
when I configure I get :

(newtensor) C:\Users\korin\tensorflow>python ./configure.py
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is C:\Users\korin\anaconda3\envs\newtensor\python.exe]:


Found possible Python library paths:
  C:\Users\korin\anaconda3\envs\newtensor\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\korin\anaconda3\envs\newtensor\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\include


Traceback (most recent call last):
  File "third_party\gpus\find_cuda_config.py", line 653, in <module>
    main()
  File "third_party\gpus\find_cuda_config.py", line 645, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party\gpus\find_cuda_config.py", line 583, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party\gpus\find_cuda_config.py", line 257, in _find_cuda_config
    get_header_version)
  File "third_party\gpus\find_cuda_config.py", line 244, in _find_header
    required_version, get_version)
  File "third_party\gpus\find_cuda_config.py", line 233, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party\gpus\find_cuda_config.py", line 250, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8

after I copied cuda.h from C:\Users\korin\tensorflow\tensorflow\core\platform to 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\include
and specified this folder for cuda during confi - same errors 
then i tried to edit cuda_configure.bzl with:
       ),
        "cupti": _check_cuda_lib_params(
            "cupti",
            cpu_value,
            cuda_config.config["cupti_library_dir"],
            #cuda_config.cuda_version,
			"11",
            static = False,
        ),
        "cusparse": _check_cuda_lib_params(
            "cusparse",

stil same errors during config

Thank you..

**Comment by divastar** [comment]
of course I did bazel clean --expunge before and downloaded latest tensorflow as you suggested ..

**Comment by amahendrakar** [comment]
@divastar,
Could you please confirm if you've added the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environmental variable as mentioned in [this guide](https://www.tensorflow.org/install/gpu#windows_setup). Thanks!
