### ISSUE TITLE
Tensorflow C API Prebuilt Library for Ubuntu 20

### ISSUE THREAD

**Issue by fatihkiralioglu** [tensorflow/tensorflow#47141]
Hi,

Currently, published Tensorflow C API Ubuntu libraries are  built for Ubuntu 16. Is there any plan to built it for Ubuntu 20? 

When I try to link it against my Ubuntu 20 projects, I got linker errors such as:

```
.dynsym local symbol at index 857
...
/usr/bin/ld: Model.cpp:(.text+0x101): undefined reference to `TF_NewGraph'
/usr/bin/ld: Model.cpp:(.text+0x10a): undefined reference to `TF_NewSessionOptions'
/usr/bin/ld: Model.cpp:(.text+0x128): undefined reference to `TF_SetConfig'
/usr/bin/ld: Model.cpp:(.text+0x160): undefined reference to `TF_LoadSessionFromSavedModel'
```

Thanks.

**Comment by Saduf2019** [comment]
@fatihkiralioglu 
We see that the issue template has not been filled, we ask for the template as it helps us analyse the issue [ ex: tf version]
Can you please refer to these resolved issues and let us know if it helps: [link](https://github.com/tensorflow/tensorflow/issues/23649), [link1](https://github.com/tensorflow/tensorflow/issues/8033), #41506, #21301.

**Comment by fatihkiralioglu** [comment]
@Saduf2019 Hi,

The version is 2.4.0. I have downloaded prebuilt library from : https://www.tensorflow.org/install/lang_c

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz

The issues you have shared does not resolve my issue. I can successully monitor .so objects with nm but cant link against my Ubuntu 20 project

**Comment by fatihkiralioglu** [comment]
@Saduf2019 There is a similar issue: 

https://github.com/tensorflow/tensorflow/issues/41382

**Comment by fatihkiralioglu** [comment]
Thanks @Saduf2019, issue is resolved, I just fixed the linkage order in my make file. Best Regards
