### ISSUE TITLE
Installing tensorflow 2 on raspberry pi 3 model B

### ISSUE THREAD

**Issue by COfek** [tensorflow/tensorflow#47142]
- Raspbian GNU/Linux 10 (buster)
- firstly trying to install via pip then second attempt trying to install from source
- TensorFlow version: 2.3.0
- Python version: 3.7.3
- gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 

Hello, I've been trying to get tensorflow (specifically Keras) to work on a raspberry pi 3 model B, using a Raspbian GNU/Linux 10 (buster), default python version is 3.7.3 and pip version is updated to 21.0.1.
the official tensorflow site says that the installation via pip should be all the same when it comes to raspberry pi with the following details but for some reasons pip installs tensorflow 1.12.0 when I run the command line `pip3 install tensorflow`, I've also tried following a guide to install tensorflow 2.3.0 via a wheel but that failed too when pip failed to find a version of tesnorflow-estimator/tensorboard that satisfies the requirements.
I would really appreciate any help.

the exact guide I am following is this guide: https://itnext.io/installing-tensorflow-2-3-0-for-raspberry-pi3-4-debian-buster-11447cb31fc4 and when I get to the last phase of actually installing tensorflow 2.3.0 I get the following error:

` Could not find a version that satisfies the requirement tensorflow-estimator<2.4.0,>=2.3.0 (from tensorflow==2.3.0) (from versions: 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12)
No matching distribution found for tensorflow-estimator<2.4.0,>=2.3.0 (from tensorflow==2.3.0)`

**Comment by Saduf2019** [comment]
@COfek 
Could you please refer to [this link](https://www.tensorflow.org/install/pip#raspberry-pi) and let us know

**Comment by COfek** [comment]
@Saduf2019 Hello and Thanks for responding, I've had a readthrough that guide and I've done everything except creating a venv because I want everything to be on the root.
