### ISSUE TITLE
EdgeTPU compilation fails for multi-head networks

### ISSUE THREAD

**Issue by niciBume** [tensorflow/tensorflow#47143]
### 1. System information

- OS Platform and Distribution  Linux Ubuntu 20.04:
- TensorFlow installation pip installation 2.3.1:

### 2. Code

Model Architecture:
```
TARGET_SIZE = 224
inputs = tf.keras.layers.Input(shape=(TARGET_SIZE, TARGET_SIZE, 3))
base_model = tf.keras.applications.MobileNetV2(input_shape=(TARGET_SIZE, TARGET_SIZE, 3), alpha=1.0, include_top=False, weights='imagenet', input_tensor=inputs)
base_out = base_model.output
base_out = tf.keras.layers.Conv2D(filters=512, kernel_size=3, activation='relu')(base_out)
base_out = tf.keras.layers.Dropout(0.2)(base_out)
base_out = tf.keras.layers.GlobalAveragePooling2D()(base_out)
#base_out = tf.keras.layers.Flatten()(base_out)

# construct a fully-connected layer header to output the predicted
# bounding box coordinates
bboxHead = tf.keras.layers.Dense(256, activation="relu")(base_out)
bboxHead = tf.keras.layers.Dense(128, activation="relu")(bboxHead)
bboxHead = tf.keras.layers.Dense(64, activation="relu")(bboxHead)
bboxHead = tf.keras.layers.Dense(32, activation="relu")(bboxHead)
bboxHead = tf.keras.layers.Dense(4, activation="sigmoid", name="bounding_box")(bboxHead)

# construct a second fully-connected layer head, this one to predict
# the class label
softmaxHead = tf.keras.layers.Dense(256, activation="relu")(base_out)
softmaxHead = tf.keras.layers.Dense(128, activation="relu")(softmaxHead)
softmaxHead = tf.keras.layers.Dense(64, activation="relu")(softmaxHead)
softmaxHead = tf.keras.layers.Dense(8, activation="relu")(softmaxHead)
softmaxHead = tf.keras.layers.Dense(1, activation="sigmoid", name="class_label")(softmaxHead)

# put together our model which accept an input image and then output
# bounding box coordinates and a class label
model = tf.keras.models.Model(inputs=base_model.input, outputs=(bboxHead, softmaxHead))
```

Visualisation of the architecture : [model_plot](https://user-images.githubusercontent.com/17791005/107879987-5dc53d80-6edc-11eb-98b9-46ec369b8c89.png)

TFLite Conversion:
```
def convert_tflite(pl_model):
    converter = tf.lite.TFLiteConverter.from_keras_model(pl_model)
    # Set quantize to true
    converter.post_training_quantize = True
    converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]  # For EdgeTPU, no float ops allowed
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8

    tflite_model = converter.convert()
    open("pl_od_model_edgetpu.tflite", "wb").write(tflite_model)

def representative_dataset_gen():
    data_dir = os.path.join(os.path.join(ma_uav_dir, 'Vision/Detector/CNN_Classifier'), 'Data/test')
    pl_dir = os.path.join(data_dir, 'PayLoad')
    pl_imgs = [cv2.imread(os.path.join(pl_dir, image)) for image in os.listdir(pl_dir) if '.png' in image]
    not_pl_dir = os.path.join(data_dir, 'Not_PayLoad')
    not_pl_imgs = [cv2.imread(os.path.join(not_pl_dir, image)) for image in os.listdir(not_pl_dir) if '.png' in image]
    all_imgs = pl_imgs + not_pl_imgs
    random.shuffle(all_imgs)

    for i in range(len(all_imgs) - 1):
        img = all_imgs[i]
        image = resize_img(img_org=img).astype(np.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

def resize_img(img_org):
    return cv2.resize(img_org, (TARGET_SIZE, TARGET_SIZE)) * (1. / 255)
```
Resulting in following Netron output: [image](https://user-images.githubusercontent.com/17791005/107880057-bac0f380-6edc-11eb-9bf9-7cfb7fff8f55.png)

### 3. Failure after conversion
The TFLite conversion is successful but the compilation to Coral EdgeTPU fails. Following command `edgetpu_compiler pl_od_model_edgetpu.tflite ` results in the error below:

EdgeTPU Compiler Output:
```
Edge TPU Compiler version 15.0.340273435
ERROR: :309 scale_diff / output_scale <= 0.02 was not true.
ERROR: Node number 79 (FULLY_CONNECTED) failed to prepare.

ERROR: :309 scale_diff / output_scale <= 0.02 was not true.
ERROR: Node number 79 (FULLY_CONNECTED) failed to prepare.

Compilation failed: Internal error

Internal compiler error. Aborting!
```

I suppose the issue is related to https://github.com/tensorflow/tensorflow/issues/41069. As I am also dealing with a model with two outputs. If the model has a single output, the compilation is successful. Could you clarify the `ERROR :309`? Is the coral able to handle a known issue regarding multi-head network quantisation? Is the coral able to handle multi-head networks?

I have to clarify that I trained the network for only 1 epoch and just wanted to use this "dummy network" to test if it is compatible with the Coral. 

Thanks!

**Comment by abattery** [comment]
FYI @jingpu

**Comment by amahendrakar** [comment]
@niciBume,
On running the code, I am facing an error stating `NameError: name 'ma_uav_dir' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7b8f8e39966cc150708d0907d88b1ab2/47143.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by niciBume** [comment]
@amahendrakar 
Thanks for the response! Not sure why, but when trying to recreate with dummy data [here](https://colab.research.google.com/gist/niciBume/5e1f8a6243525513e726bab6173cff58/47143.ipynb) it works! But on my machine it's still failing. I'll try to dig deeper into this, give me a few days and I'll try to come up with an explanation.
Thanks!

**Comment by jingpu** [comment]
> ERROR: :309 scale_diff / output_scale <= 0.02 was not true.
> ERROR: Node number 79 (FULLY_CONNECTED) failed to prepare.

The error in the initial post seems to come from 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/kernel_util.cc#L310

which indicates an quantization issue during TFLite conversion

**Comment by niciBume** [comment]
I used dummy images i.e np.ones(img_shape) to try to reproduce the error.
I think the reason is because the represantative_dataset() originally used resize(cv2.imread(os.path.join(pl_dir, image))) whereas the network has been trained with img_to_array(load_img(os.path.join(pl_dir, img_p) which is why the scaling error could occur.

- img_to_array(load_img(os.path.join(pl_dir, img_p) returns an image matrix between 0 and 255
- resize(cv2.imread(os.path.join(pl_dir, image))) returns image matrix between 0 and 1

**Comment by amahendrakar** [comment]
@niciBume,
Thank you for the update. Is this still an issue?

**Comment by niciBume** [comment]
@amahendrakar sorry forgot to close the issue. It's working consistently now! Thanks a lot!
