### ISSUE TITLE
std::partial_sort in detection_postprocess kernel is not stable

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#47158]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): 5eac5b75b48232e93f2a96ed856131201cd2ae3c
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
std::partial_sort in detection_postprocess kernel is not stable, i.e. the order of equal elements is not guaranteed to be preserved. The problem with this is that it is hard to be bit-exact between TFL and TFLM. At least when compiling TFLM with Arm clang.

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by sushreebarsa** [comment]
@mansnils We see that the PR  is merged ,Could you please let us know if we can close this issue ? Thanks!

**Comment by mansnils** [comment]
@sushreebarsa What is left is to update it on TFLM as well. But TFLM now has its own repo so maybe we should close this and create a new issue for TFLM.

**Comment by sushreebarsa** [comment]
@mansnils Thank you for the update ! Please move this issue to closed status .Thanks!
