### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow ERROR: No matching distribution found for tensorflow

### ISSUE THREAD

**Issue by EmadElDinH** [tensorflow/tensorflow#47151]
I'm trying to install the TensorFlow lib for 3 days now & tried everything, I'm using win10 64 bit and python 3.9.1 64 bit with up to date pip

**Comment by EmadElDinH** [comment]
![image](https://user-images.githubusercontent.com/79036528/107900745-9d2a7300-6f4a-11eb-9316-cade5c093845.png)

and that what happened!!!
Can you please help!

**Comment by WindQAQ** [comment]
@EmadElDinH TensorFlow has not supported Python3.9 yet.  See https://github.com/tensorflow/tensorflow/issues/44485. As a workaround, can you try to install Python3.8 or lower version?

**Comment by EmadElDinH** [comment]
actually this is what I'm doing right now ....
I'll check it & come back to you!
thanks!

**Comment by amahendrakar** [comment]
@EmadElDinH,
TensorFlow v2.4 is compatible with Python 3.6 - 3.8. For, more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#cpu).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1


As mentioned by @WindQAQ, support for Python 3.9 is already being tracked in issue [#44485](https://github.com/tensorflow/tensorflow/issues/44485). 

Thanks!

**Comment by evalsocket** [comment]
Same issue on python 3.8
```
ster ↑35  pip install tensorflow                              1 ↵  3430  14:09:46
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
```

**Comment by mihaimaruseac** [comment]
@evalsocket Please post output of `python --version`, `python -m pip --version` and `python -m pip install -vvv tensorflow`

**Comment by MystiqueCida** [comment]
These steps gave me a solution to the error.

# In[3]: pip install --user virtualenv


# In[3]: pip install wheel


# In[1]: pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl


# In[ ]: pip install tf-nightly

**Comment by Jcelestine** [comment]
This:
 pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl gave me the response as well

**Comment by mihaimaruseac** [comment]
These are not TF errors. You pip install is old and needs to be updated. Please file a bug on Pip repo if that is not the case as most likely the issue comes from there
