### ISSUE TITLE
shapes incompatible after upgrade

### ISSUE THREAD

**Issue by jharting** [tensorflow/tensorflow#4715]
After upgrade from 0.10.0 to 0.11.0rc0 my code no longer runs:

```
(802, 277)
(802, 1)
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Traceback (most recent call last):
  File "brain.py", line 47, in <module>
    classifier.fit(x=trainX, y=trainY, steps=2000)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 435, in fit
    max_steps=max_steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 333, in fit
    max_steps=max_steps)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 662, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 963, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 944, in _call_model_fn
    return self._model_fn(features, targets, mode=mode, params=self.params)
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 258, in _dnn_classifier_model_fn
    weight=_get_weight_tensor(features, weight_column_name))
  File "/usr/lib/python2.7/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py", line 329, in sigmoid_cross_entropy
    logits.get_shape().assert_is_compatible_with(multi_class_labels.get_shape())
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 750, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (?, 1) and (?,) are incompatible
```

My code:

```
...
print shape(trainX) # (802, 277)
print shape(trainY) # (802, 1)
classifier.fit(x=trainX, y=trainY, steps=2000)
...
```

This worked fine on 0.10.0. Notice the shapes in the beginning of output (looks like a valid combination to me).

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

none

### Environment info
Operating System: Fedora 23, TF 0.11.0rc0

**Comment by hholst80** [comment]
I would say no (I like hard typing). Easily fixed as you can always reshape an (?,1) rank 2 tensor into (?,) with a reshape op.

**Comment by jharting** [comment]
Can you please elaborate on what the problem is? In the numpy world at least the matrices of shapes (802, 277) and (802, 1) or alternatively (802, 277) and (802, ) vector seem reasonable to work with without reshaping. None of these works for me here. Also please provide the reshape fix so that I can verify. Thanks.

**Comment by jharting** [comment]
Minimalistic reproducer:

```
import tensorflow as tf
from numpy import *

trainX = mat([[1,1], [0,0]])
trainY = array([1,0])

feature_columns = [tf.contrib.layers.real_valued_column("", dimension=2)]
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10])

classifier.fit(x=trainX, y=trainY, steps=2000)

```

**Comment by concretevitamin** [comment]
I don't know what changes in tf.learn between 0.10 and 0.11rc0 that could cause this.  @martinwicke: can you take a look?

**Comment by klpickrell** [comment]
I've run into this as well.  It appears to be related to changes made specifically for n_classes=2.  Setting n_classes to 3 in jharting's example will enable it to run.

**Comment by martinwicke** [comment]
This should have been fixed by a recent commit. Sorry for the trouble. Please let me know if the problem persists at head.

**Comment by Zoomink** [comment]
Found this issue via this [StackOverflow issue](https://stackoverflow.com/questions/40257607/tf-contrib-learn-quickstart-changing-n-classes-to-2-does-not-work).

The issue still persists in https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc1-cp35-cp35m-linux_x86_64.whl 

Also, the nightly builds return 404 (https://github.com/tensorflow/tensorflow#installation). The last successful nightly build seems to work though (https://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/lastStableBuild/artifact/pip_test/whl/tensorflow-0.11.0rc0-cp35-cp35m-linux_x86_64.whl), but it is rc0?

Confused of what to use.

**Comment by martinwicke** [comment]
We're updating the version, so nightlies `__version__` may be confusing now. `__git_commit__` should be more informative. The fix is very recent, so it won't be in any of the 0.11 versions. It will be 0.12.
