### ISSUE TITLE
Add the ability load specific weights with the tf.keras.Model.load_weights method

### ISSUE THREAD

**Issue by rickstaa** [tensorflow/tensorflow#47157]
**System information**
- **TensorFlow version (you are using):** 2.4.1
**Are you willing to contribute it (~Yes~/No):** At the moment I'm a bit short on time, I might have time to do this in the future. This feature request is a way to check if there is enough support to implement it.

**Describe the feature and the current behaviour/state.**

Currently the [tf.keras.Model.load_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) method loads all the weights that are in a checkpoint. In my project, I want the user to have the ability to load only certain layers (weights) that are in a checkpoint. The user should be able to do this by supplying CLI arguments.

Currently, I achieve this behaviour by overloading the [tf.keras.Model.load_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) method. I first store the old model state in this overloaded method before I call the `super().load_weights` method. After the weights are restored, I then overwrite the weights the user didn't want to load based on the old mode state. 

Giving Tensorflow users the ability to supply an `ignore_list`, for example, in the [CheckpointOptions](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointOptions) object would ease this process.

**Will this change the current api? How?**

It would add a extra parameter to the [CheckpointOptions](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointOptions) object and some additional code to the [tf.keras.Model.load_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) method in order to filter based on parameter names.

**Who will benefit with this feature?**

I think it will ease the loading process for people that are using transfer learning. It would stop them from relying on workarounds as the one explained above. I am not sure how much work it is to implement such an addition, and if the work outweighs the benefits. I, therefore, opened this issue to see if other people also think this is helpful.

**Comment by mattdangerw** [comment]
Thanks for the report! Team talked today, and we don't plan on adding functionality like that right now.

The main tool for transfer learning would be to nest models and/or layers and set `trainable=True/False` as desired. See https://keras.io/guides/transfer_learning.

Beyond that, if you need more custom loading of weights, using `layer.set_weights` on the layers you want is the way to go. We want to move away from any whitelists/blacklists based on names, which can be brittle.
