### ISSUE TITLE
Compiled metrics cannot deal with dictionaries in update_state

### ISSUE THREAD

**Issue by mh-synth** [tensorflow/tensorflow#47162]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8.1.0
- GPU model and memory: RTX2080Ti 11GB

**Describe the current behavior**
I have written a custom metric, subclassing from tf.keras.metrics.Metric. I also have a custom model,
subclassing from tf.keras.Model. I compile the model, passing this custom metric. When doing a single train step,
I update the state of the custom metric with prediction and target as **dictionaries**.

However, the autograph operation turns these dictionaries into lists, making it impossible for me to access the right item in the dictionary within the metric.

An error is thrown:

```
File "bug.py", line 41, in <module>
    model.train_step([])
  File "bug.py", line 17, in train_step
    self.compiled_metrics.update_state(y_true, y_pred)
  File "/home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py", line 408, in update_state
    metric_obj.update_state(y_t, y_p, sample_weight=mask)
  File "/home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/keras/utils/metrics_utils.py", line 90, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "/home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 177, in update_state_fn
    return ag_update_state(*args, **kwargs)
  File "/home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    bug.py:27 update_state  *
        self.value.assign_add((y_true["a"] - y_pred["a"]) ** 2)
    /home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1009 _slice_helper
        _check_index(s)
    /home/mhueting/.pyenv/versions/tts_env/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:886 _check_index
        raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))

    TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 'a'
```

**Describe the expected behavior**
I expect the dictionaries passed to the compiled metric container's `update_state` function to be preserved as dictionaries instead of converted into keyless lists.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1DCYM2W3C5H2StxrdPeqqsvVGBtbVfNfJ?usp=sharing

```
import numpy as np
import tensorflow as tf

class Model(tf.keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, x, training=True):
        # this model returns a dictionary of values
        return {
            "a": tf.constant([5]),
            "b": tf.constant([5]),
        }

    def train_step(self, data):
        # each sample also consists of a dictionary of values
        y_true = {"a": tf.constant([3]),
                  "b": tf.constant([4])}
        y_pred = self(4)

        # the metrics on this compiled metric container each care about
        # only one of the values in the dictionaries y_true/y_pred
        self.compiled_metrics.update_state(y_true, y_pred)

        return {m.name: m.result() for m in self.metrics}

class MetricForA(tf.keras.metrics.Metric):
    def __init__(self, name="metricForA", **kwargs):
        super(MetricForA, self).__init__(name=name, **kwargs)
        self.value = self.add_weight(name='value', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        self.value.assign_add((y_true["a"] - y_pred["a"]) ** 2)

    def result(self):
        return self.value

    def reset_states(self):
        self.value.assign(0)

class MetricForB(tf.keras.metrics.Metric):
    def __init__(self, name="metricForB", **kwargs):
        super(MetricForB, self).__init__(name=name, **kwargs)
        self.value = self.add_weight(name='value', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        self.value.assign_add((y_true["b"] - y_pred["b"]) ** 2)

    def result(self):
        return self.value

    def reset_states(self):
        self.value.assign(0)

if __name__ == "__main__":
    model = Model()
    metrics = [MetricForA(), MetricForB()]

    model.compile(metrics=metrics)

    # this results in an error, showing us that the dictionaries passed to update_state
    # are no longer dictionaries
    model.train_step([])
```

**Comment by Saduf2019** [comment]
@mh-synth 
I ran the code and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5a398d5d487ecccbbb5a12b857e5955a/untitled537.ipynb)

**Comment by mh-synth** [comment]
Apologies - updated the colab and the standalone code. Running the Colab in its entirety now gives the error.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/fbfb06b8cd1b0837bded70f7b86de31f/untitled544.ipynb).

**Comment by sushreebarsa** [comment]
I am able to replicate the issue reported on [TF nightly 
](https://colab.research.google.com/gist/sushreebarsa/f115121b5bf99be036d376841c401d8f/untitled120.ipynb?authuser=1#scrollTo=xa4YZlORuhmf)and [TF v2.5 ](https://colab.research.google.com/gist/sushreebarsa/868ec754d9ca3a8ef4b7ec444602e223/untitled121.ipynb?authuser=1)..Thanks !

**Comment by tiruk007** [comment]
This issue still persists on the latest TF V2.11 and Tf-nightly. Please find the gist of [2.11](https://colab.research.google.com/gist/tiruk007/f6996981e7e540bbad37229625c71915/untitled43.ipynb) and [tf-nightly](https://colab.research.google.com/gist/tiruk007/94980e4a5b65fd9df4e8db926fb9fb40/untitled44.ipynb) for reference .
Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
