### ISSUE TITLE
Error while training a model using spark and elephas estimator- Please suggest

### ISSUE THREAD

**Issue by snigdhasen** [tensorflow/tensorflow#47163]
I am still getting the same error while executing on spark cluster 

estimator = ElephasEstimator()
estimator.set_keras_model_config(model.to_yaml())
estimator.set_optimizer_config(sgd_conf)
estimator.set_mode("synchronous")
estimator.set_loss("mae")
estimator.set_metrics(['mse'])
estimator.set_epochs(epochs)
estimator.set_batch_size(batch_size)
estimator.set_validation_split(0.1)
estimator.set_categorical_labels(False)
pipeline = Pipeline(stages=[estimator])
fitted_pipeline = pipeline.fit(df)

<img width="633" alt="Capture1" src="https://user-images.githubusercontent.com/53963317/107957497-b3761480-6fc6-11eb-8247-e0ba551f10da.PNG">
<img width="751" alt="Capture2" src="https://user-images.githubusercontent.com/53963317/107957501-b53fd800-6fc6-11eb-9c2c-ce335eadfd9e.PNG">

**Comment by amahendrakar** [comment]
@snigdhasen,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by snigdhasen** [comment]
@amahendrakar TF Version 2.2.0. dataset size is more than 150MB. Not able to attach here
Code is below: 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import optimizers

from elephas.ml_model import ElephasEstimator
from elephas.ml.adapter import to_data_frame

from pyspark import SparkContext, SparkConf
from pyspark.mllib.evaluation import RegressionMetrics
from pyspark.ml import Pipeline
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
data= pd.read_csv("/home/newbiggatcdh1/phd/LALR.csv")
data[data["modelMag_u"]==-9999]=np.nan
data[data["modelMag_g"]==-9999]=np.nan
data[data["modelMag_r"]==-9999]=np.nan
data[data["modelMag_i"]==-9999]=np.nan
data[data["modelMag_z"]==-9999]=np.nan
data[data["fiberMag_u"]==-9999]=np.nan
data[data["fiberMag_g"]==-9999]=np.nan
data[data["fiberMag_r"]==-9999]=np.nan
data[data["fiberMag_i"]==-9999]=np.nan
data[data["fiberMag_z"]==-9999]=np.nan
data[data["dered_u"]==-9999]=np.nan
data[data["dered_g"]==-9999]=np.nan
data[data["dered_r"]==-9999]=np.nan
data[data["dered_i"]==-9999]=np.nan
data[data["dered_z"]==-9999]=np.nan
data=data.dropna()
print(data.shape)
print(data.shape)
print(type(data))
data1=data.to_numpy()
X=data1[:,0:32]
y=data1[:,-1]
print(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.33)
X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
X_train /= 255
X_test /= 255
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')
print(type(X_train))
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.keras.layers import Dropout

model = Sequential()
model.add(Dense(512, input_shape=(X_train.shape[1],))) # shape[1] will be number of columns
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('linear'))
conf = SparkConf().setAppName('Regression_Spark_MLP').setMaster('local[*]')
sc = SparkContext(conf=conf)
df = to_data_frame(sc, X_train, y_train)
test_df = to_data_frame(sc, X_test, y_test)
print(type(df))
opt = optimizers.Adam(learning_rate=0.05)
sgd_conf = optimizers.serialize(opt)
batch_size = 256
epochs = 10
estimator = ElephasEstimator()
estimator.set_keras_model_config(model.to_yaml())
estimator.set_optimizer_config(sgd_conf)
estimator.set_mode("synchronous")
estimator.set_loss("mae")
estimator.set_metrics(['mse'])
estimator.set_epochs(epochs)
estimator.set_batch_size(batch_size)
estimator.set_validation_split(0.1)
estimator.set_categorical_labels(False)
import timeit
pipeline = Pipeline(stages=[estimator])
start = timeit.default_timer()
fitted_pipeline = pipeline.fit(df)
stop = timeit.default_timer()
execution_time = (stop - start)/60
print("Program Executed in minutes "+str(execution_time)) # It returns time in minutes

**Comment by snigdhasen** [comment]
@amahendrakar Please let me know if any update on this

**Comment by nitbix** [comment]
For reference, this appears to be the same as https://github.com/tensorflow/tensozflow/issues/37885
BatchNormalization layers appear to not deserialise properly with pyyaml>5.1.
I just tried in tensorflow 2.4.1 and the problem is still there. There should be instructions to reproduce this easily in the previous issue, but let me know if you would like me to test anything specific.

**Comment by amahendrakar** [comment]
@snigdhasen,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory:'/home/newbiggatcdh1/phd/LALR.csv'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/506c3a9910d69a32be4216c0dd234a40/47163.ipynb#scrollTo=hmUnOeaAIRVX).



> dataset size is more than 150MB. Not able to attach here

In this case, could you please upload the dataset to Google Drive and share it with us. Thanks!

**Comment by snigdhasen** [comment]
@amahendrakar 
Please find attached dataset 
https://drive.google.com/file/d/1x94BgnF6gfabFqpHgKmfgT9gIsnNboGp/view?usp=sharing

**Comment by amahendrakar** [comment]
@snigdhasen,
I did not face any errors while running the code with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/a3c7645acf43e03b36662a8c0bbe5455/47163-2-2.ipynb) and TF v2.3. 

Whereas with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/73a845a7506035da518bbca8d46c687d/47163-2-4.ipynb#scrollTo=hmUnOeaAIRVX) and TF-nightly, the `pyspark` module throws an error stating `PicklingError: Could not serialize object: ValueError: Cell is empty`. Please check the linked gist for reference. 

Could you please run the code in a new virtual environment and check if you're facing the same issue. Thanks!

**Comment by snigdhasen** [comment]
@amahendrakar
Yes thanks.That issue got resolved now. But everytime the output is coming like this. For all object same value

![image](https://user-images.githubusercontent.com/53963317/110797041-a9ca8e80-829e-11eb-9c9e-1d11d8f13dcd.png)

**Comment by amahendrakar** [comment]
> Yes thanks.That issue got resolved now. But everytime the output is coming like this. For all object same value

@snigdhasen,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. 

Please feel free to close the issue if the original error is resolved. Thanks!

**Comment by snigdhasen** [comment]
Thanks for help.
