### ISSUE TITLE
Slow as_numpy_iterator() and StringLookup.adapt() with make_csv_dataset()

### ISSUE THREAD

**Issue by jhzab** [tensorflow/tensorflow#47171]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, attached below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 under WSL 2 and Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Doesn't apply.
- TensorFlow installed from (source or binary): Binary.
- TensorFlow version (use command below): v1.12.1-50923-g01fe322bbb5 2.5.0-dev20210215 (also tried 2.4.1 via pip and colab)
- Python version: 3.8.6
- Bazel version (if compiling from source): Doesn't apply.
- GCC/Compiler version (if compiling from source): Doesn't apply.
- CUDA/cuDNN version: Doesn't apply.
- GPU model and memory: Doesn't apply. CPU only.

**Describe the current behavior**
Using the dataset API to read CSV data (via `list(data.as_numpy_iterator())`) takes around 4-5x longer compared to regular pandas' `read_csv()`.
Running a `StringLookup.adapt(...)` is also slow. (Made even worse when multiple adapt()s need to run?) But can't be easily compared to pandas' unique() since the data is in memory by then.
Setting `num_parallel_reads` didn't really make a difference.

The used dataset has 678014 lines with 30MB worth of data.

**Describe the expected behavior**
Being near pandas read performance would be nice or faster via num_parallel_reads. ;-) This should make `adapt()` fast as well, hopefully.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1wySl43lLZ5P3ntjpD3TmYn0ZcYrTYve-?usp=sharing

```python
import tensorflow as tf
import pandas as pd
import logging
from pathlib import Path

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT, level = logging.INFO)

path = "https://www.openml.org/data/get_csv/20649148/freMTPL2freq.arff"
if not Path("freMTPL2freq.csv").exists():
  logging.info("Loading data file")
  df = pd.read_csv(path)
  df.to_csv("freMTPL2freq.csv")
else:
  logging.info("Data file already exists")
  df = pd.read_csv(path)

logging.info("Opening data")
data = tf.data.experimental.make_csv_dataset("freMTPL2freq.csv",
                                             num_rows_for_inference=100,
                                             batch_size=256,
                                             shuffle=False,
                                             sloppy=False,
                                             #num_parallel_reads=4,
                                             num_epochs=1,)
# this is even slower?
#data = tf.data.Dataset.from_tensor_slices(df.to_dict('list'))

logging.info("Reading data")
# This part is slower than expected
tmp = list(data.as_numpy_iterator())
logging.info("Done reading data")
lookup = tf.keras.layers.experimental.preprocessing.StringLookup()
feature_ds = data.map(lambda x: x['Area'])
logging.info("Starting adapt")
# This part is also slower than expected
lookup.adapt(feature_ds)
logging.info("Finished adapt")

# Commented out IPython magic to ensure Python compatibility.
# %timeit tmp = list(data.as_numpy_iterator())

# Commented out IPython magic to ensure Python compatibility.
# %timeit lookup.adapt(feature_ds)

# Commented out IPython magic to ensure Python compatibility.
# %timeit df["Area"].unique()

# Commented out IPython magic to ensure Python compatibility.
# %timeit pd.read_csv(path)
```

**Comment by ravikyram** [comment]
Was able to reproduce the issue with  TF v2.4 and TF-nightly(`2.5.0-dev20210217`). Please find the gist of it [here](https://colab.research.google.com/gist/ravikyram/356c38f0d6431d6c38ffcd18abef29ae/untitled672.ipynb). Thanks!

**Comment by stefanobranco** [comment]
I'm not sure this is directly connected, but Stringlookup.adapt() performance gotten significantly worse for me ever since `tf-nightly-2.5.0.dev20210114` tot he point where it's looking it's just stuck there.

**Comment by lingster** [comment]
I have similar issues when I try to load a parquet file using:

```
ds = tfio.IODataset.from_parquet(...)
iter = ds.as_numpy_iterator()
```
In this case, is it better to use spark to manipulate the data before conversion to a tf dataset for training?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
