### ISSUE TITLE
Can't compile Tensorarray with XLA.

### ISSUE THREAD

**Issue by MSusik** [tensorflow/tensorflow#47170]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CPU
- GPU model and memory: N/A

**Describe the current behavior**

I have some code that is expensive to compile in XLA (~10 minutes). I am looking for a way to speed up this compilation. I noticed that my codebase produces a lot of computational graph nodes in one of the for loops. Therefore I plan to replace this for-loop with a `tf.while_loop`. In order to do that, I need to use TensorArrays. When I do that the compilation fails.

If I understand correctly, I have to build the Tensorarray inside the XLA context due to XLA limitations. I believe the issue might be caused by the fact that on compile time the shape of the tensors have to be known and the compiler assumes all the shapes within the tensoarray will be shared.

When I change the shapes of the tensors in such a way that all of them have the same size, the code compiles fine.

Then a question arises: Is there a way to construct a `tf.while_loop` (or a similiar construct) with some kind of a data structure so that I don't compile most of the iterations?

**Describe the expected behavior**

The XLA compilation runs smoothly and my compilation time goes down.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1gpzRRggNNcuYDnCWy-VLXNvLi3O81tAN?usp=sharing

```
import tensorflow as tf

array = [
    tf.random.uniform((19,1,3,2)),
    tf.random.uniform((19,1,2,2)),
    tf.random.uniform((3,1,3,2)),
    tf.random.uniform((18,1,2,2)),
]

size = len(array)

@tf.function(experimental_compile=True) # The same happens with autograph=False
def add(array):
    
    tensor_array = tf.TensorArray(
        dtype=tf.float32,
        size=size,
        infer_shape=False,
        element_shape=tf.TensorShape([None, 1, None, 2]),
    )
    for i in range(size):
        tensor_array = tensor_array.write(i, array[i])
    # There would be a while_loop here

r = add(array)
```

**Other info / logs**

```
---------------------------------------------------------------------------

InternalError                             Traceback (most recent call last)

<ipython-input-1-c5dfc3274b00> in <module>()
     23     # There would be a while_loop here
     24 
---> 25 r = add(array)

4 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    893       # If we did not create any variables the trace we have is good enough.
    894       return self._concrete_stateful_fn._call_flat(
--> 895           filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
    896 
    897     def fn_with_cond(inner_args, inner_kwds, inner_filtered_flat_args):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InternalError: Invalid TensorList shape: element_type: TUPLE
tuple_shapes {
  element_type: F32
  dimensions: 4
  dimensions: 19
  dimensions: 1
  dimensions: 3
  dimensions: 2
  layout {
    minor_to_major: 4
    minor_to_major: 3
    minor_to_major: 2
    minor_to_major: 1
    minor_to_major: 0
    format: DENSE
  }
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
}
tuple_shapes {
  element_type: S32
  layout {
    format: DENSE
  }
}
, expected: element_type: TUPLE
tuple_shapes {
  element_type: F32
  dimensions: 4
  dimensions: 19
  dimensions: 1
  dimensions: 2
  dimensions: 2
  layout {
    minor_to_major: 4
    minor_to_major: 3
    minor_to_major: 2
    minor_to_major: 1
    minor_to_major: 0
    format: DENSE
  }
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
  is_dynamic_dimension: false
}
tuple_shapes {
  element_type: S32
  layout {
    format: DENSE
  }
}

	 [[{{node TensorArrayV2Write_1/TensorListSetItem}}]] [Op:__inference_add_26]
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4103de4b0de4fa7c1f3b56a709132fc4/47170.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210603, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/4f8e6a971e70d8b5b65cc9363d8c7f96/47170.ipynb). Thanks!

**Comment by bhack** [comment]
Can we close this?

**Comment by sachinprasadhs** [comment]
> Can we close this?

Could you please provide more context on this and why do you feel this issue needs to be closed. Thanks!

**Comment by bhack** [comment]
If it is not planned for the "old" bridge with the new bridge `tf.config.experimental.enable_mlir_bridge()` is probably https://github.com/tensorflow/tensorflow/issues/52030

As I see

```python
error: 'tf.TensorListReserve' op unknown tensor list element shape
```

**Comment by sachinprasadhs** [comment]
Understood, thanks for providing insight on the issue.
Do you feel this issue could be related to the issue which you have created https://github.com/tensorflow/tensorflow/issues/58051 as well. 
In that case, we can close this and track the progress in the above 2 linked issues.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
