### ISSUE TITLE
tensorflow_model_server  taking a lot of time in deploying model

### ISSUE THREAD

**Issue by akanksha4116** [tensorflow/tensorflow#47177]
Command is running from hours 
nohup tensorflow_model_server \
  --rest_api_port=9090 \
  --model_name=seman_model \
  --model_base_path="${Model_Directory}" >server1.log 2>&1

**Comment by Saduf2019** [comment]
@akanksha4116 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
