### ISSUE TITLE
Need to get the version info from the model

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#47176]
I have downloaded / created tfLite Model.

How do i know the version of the tfLite Model from just the flatbuffer model(*.tflite ) file..
Can i fetch the version information from this model.

Another query - we have schema_generated.h file in every tfLite release. (tensorflow/lite/schema)
I could not see any version information in this file. 

Can i fetch the version of tfLite from this file .

**Comment by ymodak** [comment]
I am afraid that `.tflite` file by itself won't be sufficient to extract the TF version. Perhaps you may want to try asking the version on the repository where you downloaded the model.
TensorFlow Lite Runtime version value is shared with that of TensorFlow.
https://github.com/tensorflow/tensorflow/blob/e2cd9cda8001d6c9aaeb454ecc6f14dcc7a1a2d7/tensorflow/lite/version.h#L25
