### ISSUE TITLE
Crash when creating Dataset from RaggedTensor, parallel function calls

### ISSUE THREAD

**Issue by azertyken** [tensorflow/tensorflow#47183]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, see in colab below

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Docker image tensorflow/tensorflow:2.4.1-gpu-jupyter

- TensorFlow installed from (source or binary):
binary

- TensorFlow version (use command below):
2.4.1

- Python version:
3.6.9

- GPU model and memory:
Tesla V100 with 16GB

**Describe the current behavior**

Running the script in the colab below crashes:
- at random times (but typically soon after launching the script)
- **most often with a segfault without further info**, sometimes with a variety of error such as
  - tensorflow.python.framework.errors_impl.InvalidArgumentError: PartialTensorShape: Incompatible ranks during merge: 1 vs. 0
         [[{{node TensorListConcatV2}}]] [Op:IteratorGetNext]
  - F tensorflow/core/framework/tensor_shape.cc:466] Check failed: end <= dims() (1 vs. 0)
  - invalid fastbin entry (free)
  - InvalidArgumentError: Trying to concat list with only uninitialized tensors but element_shape_except_first_dim_ is not fully defined: []
	 [[{{node TensorListConcatV2}}]]

**Describe the expected behavior**

No crashes, the expected output is 
2
0
2
0
...

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1TA2kXxM5mQXDKI5-mcY28IuTl4zO4Syv?usp=sharing

**Other info**
The problem does not occur if
- **the num_parallel_calls is set to 1**
and/or
- the ragged tensor is changed to an ordinary tensor
and/or
- the tf.fill is changed to a constant tensor

**Comment by Saduf2019** [comment]
@azertyken 
Can you please refer to this resolved issue and let us know if it helps: [link](https://stackoverflow.com/questions/62712483/tensorflow-partialtensorshape-incompatible-ranks-during-merge-2-vs-1)

**Comment by azertyken** [comment]
@Saduf2019 I don't think the issue you refer to is similar to the one that I'm experiencing. Please note that most of the time, the script just segfaults and there is no error indication whatsoever.

**Comment by Saduf2019** [comment]
@azertyken 
I ran the code on tf 2.4 and nightly and do not see any errors on tf-nightly , nor does the colab crash, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/36a97496f09e72d44e6ca025ec205a9e/untitled540.ipynb).

**Comment by ddeweerdt** [comment]
@Saduf2019 You're right, the errors are gone, thanks!

**Comment by Saduf2019** [comment]
@ddeweerdt 
Thank you for your update, please move the issue to closed status.
