### ISSUE TITLE
i can't import tf.python.ops

### ISSUE THREAD

**Issue by NightKight** [tensorflow/tensorflow#4718]
Python 3.5.2 (default, Oct  2 2016, 13:49:15)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
/>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
/>>> tf.__version__
'0.11.0rc0'
/>>> tf.python.ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.python' has no attribute 'ops'
/>>> tf.python.platform
<module 'tensorflow.python.platform' from '/home/zhusf/lib/python3.5/site-packages/tensorflow/python/platform/__init__.py'>
/>>> tf.python.framework
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.python' has no attribute 'framework'
/>>> tf.python.summary
<module 'tensorflow.python.summary.summary' from '/home/zhusf/lib/python3.5/site-packages/tensorflow/python/summary/summary.py'>
/>>> tf.python.training
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.python' has no attribute 'training'

**Comment by concretevitamin** [comment]
This is not typical usage pattern from a python shell.  To use an op, directly use `tf.<op name>(...)`.  To, say, use something from the `training` package, you can do `tf.train.Saver`.

If you are adding/modifying TensorFlow source code -- instead of operating from within a shell -- there's plenty of examples on how to properly import.
