### ISSUE TITLE
Bug related to Martin Görnes Attend Tutorial

### ISSUE THREAD

**Issue by DHOFM** [tensorflow/tensorflow#47194]
I know that TF 1 is no longer supported but if I test this notebook related to Martin Görner Attention Based Classification Tutorial: https://github.com/conversationai/conversationai-models/blob/master/attention-tutorial/Attention_Model_Tutorial.ipynb

And add the following lines to the bi_rnn_model Function after the encoding was calculated:

Original Code
```
encoding, alphas = attend(outputs, 
                            hparams['attention_size'], 
                            hparams['attention_depth'])
```
To add code.

```
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    
    xev = encoding.eval()

```
The eval Method will hang forever. This happens in session.py:

```
def _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list,
                          run_metadata):
    return tf_session.TF_SessionRun_wrapper(
        self._session, options, feed_dict, fetch_list, target_list,
        run_metadata)

```

Am I doing it completely wrong or is it an old TF1 Bug???

Kind regards,

Dirk

**Comment by Saduf2019** [comment]
@DHOFM 
1.x is not suuported,please upgrade to 2.x and let us know in case you face any issues.

**Comment by DHOFM** [comment]
@Saduf2019 Yes, I know, but my question was / is: Is it an old TF Bug or am I doing it completely wrong?

**Comment by jvishnuvardhan** [comment]
@DHOFM This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
