### ISSUE TITLE
CUDA devices are not recognized

### ISSUE THREAD

**Issue by sdonatti** [tensorflow/tensorflow#47191]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: Anaconda 4.8.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1.243/7.6.5
- GPU model and memory: NVIDIA Quadro P2000 4GB

**Describe the problem**
- The list of available GPU is empty!
- TensorFlow runs only on CPU

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`conda env create -f tf-gpu-test.yaml`
`conda activate tf-gpu-test`
`python tf-gpu-test.py`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Files: [tf-gpu-test.zip](https://github.com/tensorflow/tensorflow/files/5989857/tf-gpu-test.zip)
CUDA: []
CPU: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

**Comment by Saduf2019** [comment]
@sdonatti 
Can you please confirm if you have followed installation as mentioned in the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu).

**Comment by sdonatti** [comment]
The virtual environment uses the [tensorflow-gpu](https://anaconda.org/anaconda/tensorflow-gpu) package from Anaconda. I confirm that the platform has installed CUDA 10.1.243 and cuDNN 7.6.5 in-line with the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu) for TensorFlow 2.3.0.

**Comment by jvishnuvardhan** [comment]
@sdonatti We don't support Anaconda related issues. Did you check whether `tf-gpu` working in local (instead of virtual env). Did you try with other python versions (such as Python 3.6 or 3.7)? Thanks!

**Comment by sdonatti** [comment]
No, I have not tried other Python versions. It seems the issue is with the tensorflow-gpu package from Anaconda because I can detect the CUDA devices properly when using PIP virtual environments with the same major versions. It is a pity and a disappointment that TensorFlow does not support its Anaconda packages, as this package manager shines in providing the versatility to handle CUDA/cuDNN dependencies automatically and binds them to a virtual environment. You can close this issue.

**Comment by jvishnuvardhan** [comment]
@sdonatti I understand your feelings about Anaconda package but we don't have any control on those builds and I am sure their repo might provide faster resolution to your problem.

cc @mihaimaruseac 

I am closing this issue as we cannot do much with Anaconda based TF Package. Thanks!

**Comment by sdonatti** [comment]
The issue can be mitigated using earlier TensorFlow versions (e.g., 1.15.0) or other package managers (e.g., PIP). It would be good if TensorFlow starts to support its Anaconda packages in the future. Cheers!
