### ISSUE TITLE
Multi-thread support for TF2 ParameterServerStrategy

### ISSUE THREAD

**Issue by shaowei-su** [tensorflow/tensorflow#47197]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After building a sample model based on tutorial(https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy), the performance is way less compare to TF 1 PS strategy(multi client version) and checking the coordinator resource utilization, it turns out that only single core is heavily utilized in a multi-core machine for coordinator. It seems that even though in workers are maintained in separate thread(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/coordinator/cluster_coordinator.py#L742), the actual executions are still sequential. 

Is this caused by GIL? what's the recommended approach to improve the performance?

**Describe the expected behavior**
Multi-thread / multi-core support for ParameterServerStrategy coordinator.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
N/A
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by yuefengz** [comment]
The function execution will release GIL therefore so far it has not been a big issue for our internal users. Have you tried multi-step packing: https://www.tensorflow.org/tutorials/distribute/parameter_server_training#performance_improvement?

**Comment by shaowei-su** [comment]
Thanks Yuefeng, I tried but performance wise it's still not on par with TF 1 API. Do you mind sharing some details regrading how to set up the benchmark you and Haoyu used in this video(https://www.youtube.com/watch?v=B2Tpv_N7wkg&list=PLv-somlsqZU6VDnVcOof75RgT0I6v1Vg4&index=1&ab_channel=TensorFlow)?

**Comment by yuefengz** [comment]
cc @haoyuz as well.

After we enabled multi-step packing (like ~10 steps per schedule), we tried to see whether there is any imbalance between PS in terms of CPU usage. We saw some PS has much higher CPU load and identified issues with variable sharding and optimizer variables being used by all other PS in a single step. Therefore, we added the tip 1 and 2 in the tutorial.

**Comment by yuefengz** [comment]
We created a synthetic model which resemble a wide-n-deep for benchmarking.

**Comment by shaowei-su** [comment]
> we tried to see whether there is any imbalance between PS in terms of CPU usage
For our particular case, PS CPU usage is low and the bottleneck is on coordinator throughput.

**Comment by yuefengz** [comment]
Could you try packing more steps into a single function?

**Comment by yuefengz** [comment]
If you have a profiling with python call stacks enabled, that would be wonderful.
