### ISSUE TITLE
"No matching distribution found for tensorflow" when installing with pip on macOS 11

### ISSUE THREAD

**Issue by jameshfisher** [tensorflow/tensorflow#47205]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.1, x86-64
- TensorFlow installed from (source or binary): `pip3 install tensorflow`
- TensorFlow version: latest
- Python version: 3.8
- Installed using: pip3

**Describe the problem**

Installation with `pip` fails with:

```shell
$ pip3 install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
# TensorFlow apparently does not yet support 3.9, so fall back to 3.8
brew install python@3.8
brew link --overwrite python@3.8

pip3 install tensorflow
```

**Any other info / logs**

Here is verbose output:

```shell
$ pip3 install --upgrade -v tensorflow
Using pip 20.2.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-ephem-wheel-cache-v942l1u1
Created temporary directory: /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-req-tracker-vv4x81gu
Initialized build tracking at /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-req-tracker-vv4x81gu
Created build tracker: /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-req-tracker-vv4x81gu
Entered build tracker: /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-req-tracker-vv4x81gu
Created temporary directory: /private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-install-wju8g2vw
1 location(s) to search for versions of tensorflow:
* https://pypi.org/simple/tensorflow/
Fetching project page and analyzing links: https://pypi.org/simple/tensorflow/
Getting page https://pypi.org/simple/tensorflow/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/tensorflow/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/tensorflow/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: cp27-cp27m-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/90/cf/1d1e12f9f39b6a0ed1c49792ef5ce7615dddc2ce7287fc83ede0dddb9b3c/tensorflow-0.12.0rc0-cp27-cp27m-macosx_10_11_x86_64.whl#sha256=feaf06c7df5c0a480654bf1f38dd4d3b809c7315502a7d9f295033f9d2bd9b13 (from https://pypi.org/simple/tensorflow/)
... OMITTING EXTREMELY LONG LIST OF WHEELS ...
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://files.pythonhosted.org/packages/ad/fc/fccaa149d7ccc165de01d62d19e5e9492e87ad23a7106f6dfe132800ca6f/tensorflow-2.4.1-cp38-cp38-win_amd64.whl#sha256=eedcf578afde5e6e69c75d796bed41093451cd1ab54afb438760e40fb74a09de (from https://pypi.org/simple/tensorflow/)
Given no hashes to check 0 links for project 'tensorflow': discarding no candidates
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for tensorflow
Removed build tracker: '/private/var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/pip-req-tracker-vv4x81gu'
```

The cause seems to be that it expects at least one wheel whose tags match my machine, but none do. My guess is that this is due to using macOS 11. All lines look like `macosx_10_*_x86_64`, but I guess it's looking for a line matching `macosx_11_*_x86_64`. (Apologies: I know nothing about the python ecosystem; this is just my educated guess.)

**Comment by jameshfisher** [comment]
I just found this, which looks closely related to my theory that this is due to macOS 11: https://github.com/tensorflow/tensorflow/issues/45120

**Comment by jameshfisher** [comment]
[PEP 425](https://www.python.org/dev/peps/pep-0425/) seems to confirm that it is checking against the filename e.g. `tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl` to check compatibility.

**Comment by jameshfisher** [comment]
To test, I changed the filename, and it starts installing:

```bash
wget https://files.pythonhosted.org/packages/2f/33/4b330de553d80ae6fa123ec9aee90ee7d679d297b1595c9c6ce2b3c7a967/tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl
mv tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl tensorflow-2.4.1-cp38-cp38-macosx_11_2_x86_64.whl
pip3 install tensorflow-2.4.1-cp38-cp38-macosx_11_2_x86_64.whl
```

However, it runs long and hot, apparently compiling many dependencies from source, e.g. `grpcio`, some of which fail. But this seems to confirm that it's the lack of a `macosx_11_2` wheel that causes the issue.

**Comment by jameshfisher** [comment]
I get the feeling that macOS 11 is actually not supported, and [the requirements on the install page](https://www.tensorflow.org/install) are out-of-date.

**Comment by Saduf2019** [comment]
@jameshfisher 
Can you please verify, if your system satisfies these [requirement](https://github.com/tensorflow/tensorflow/issues/42367#issuecomment-674531556) once.

**Comment by jameshfisher** [comment]
Hi @Saduf2019, my CPU does support AVX instructions:

```shell
$ sysctl -a | grep 'cpu.*features'
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET SGX BMI1 AVX2 SMEP BMI2 ERMS INVPCID FPU_CSDS MPX RDSEED ADX SMAP CLFSOPT IPT MDCLEAR TSXFA IBRS STIBP L1DF SSBD
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI
```

It's an unmodified Macbook Air from early 2020; here's my hardware overview from System Information:

```
Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir8,2
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	1.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1554.80.3.0.0 (iBridge: 18.16.14346.0.0,0)
  Serial Number (system):	FVFC50AVLYWT
  Hardware UUID:	6550BBA2-DE9D-5DBE-8839-F8BF5BD445BC
  Provisioning UDID:	6550BBA2-DE9D-5DBE-8839-F8BF5BD445BC
  Activation Lock Status:	Enabled
```

**Comment by jameshfisher** [comment]
Here is the entire output from `pip3 install --upgrade -v tensorflow`, which includes the long list of wheels that it checks: [pip_output.txt](https://github.com/tensorflow/tensorflow/files/6001868/pip_output.txt)

(It's frustrating that pip is not more explicit about why it is skipping a wheel. It would be very helpful to see which tags don't match. I'll see if there's any way to get that info.)

**Comment by jameshfisher** [comment]
So based on @8bitmp3's suggestion, I tried installing via virtualenv, and it does find and install a wheel! The wheel `tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl`, with standard `pip3` from Homebrew, is rejected with "none of the wheel's tags match", but with virtualenv, I get the output:

```
Found link https://files.pythonhosted.org/packages/2f/33/4b330de553d80ae6fa123ec9aee90ee7d679d297b1595c9c6ce2b3c7a967/tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl#sha256=4a04081647b89a8fb602895b29ffc559e3c20aac8bde1d4c5ecd2a65adce5d35 (from https://pypi.org/simple/tensorflow/), version: 2.4.1
```

It then goes on to install this wheel.

So now there are two mysteries:

* Why does pip3 under virtualenv install `tensorflow-2.4.1-cp38-cp38-macosx_10_11_x86_64.whl`, despite my OS being version 11.2 rather than 10.11? Shouldn't these be incompatible?
* Why does pip3 from Homebrew fail to match this wheel, if not due to the OS? And why won't it give me more specific information about what failed to match, so that I can debug it? I've asked about this at https://github.com/pypa/pip/issues/9621

**Comment by jameshfisher** [comment]
So with some help from @8bitmp3 (https://github.com/tensorflow/docs/pull/1820) and @pfmoore (https://github.com/pypa/pip/issues/9621), I found the root cause.

pip from `brew install python@3.8` is version 20.2.4, which on macOS 11 only accepts `macosx_11` wheels. But pip 20.3+  includes [a change to accept `macosx_10` when running on macOS 11](https://github.com/pypa/pip/issues/9138).

The fact remains that the TensorFlow installation instructions on macOS are broken. To fix it, at least one of these solutions needs to happen:

* TensorFlow installation instructions should demand pip 20.3+.
* TensorFlow should support Python 3.9. Then we wouldn't have to `brew install python@3.8`, dragging in an old version of pip.
* TensorFlow should publish wheels explicitly supporting `macos_11`, as per https://github.com/tensorflow/tensorflow/issues/45120.
* Homebrew should update the pip in `python@3.8` to 20.3+.

**Comment by jameshfisher** [comment]
I've proposed documentation change here: https://github.com/tensorflow/docs/pull/1826

This leaves it up to the user how to get pip 20.3+. It's not easy, because TF demands Python <3.9 but pip 20.3+, which can't be satisfied with Homebrew packages (AFAICS). My workaround is to use virtualenv for now.

**Comment by mihaimaruseac** [comment]
TF cannot yet support Py3.9 (#44485)

MacOS support is hard to obtain as we depend on a different team which provides us with VMs but they are older macs

**Comment by jameshfisher** [comment]
Note: Homebrew now seems to have updated `python@3.8` to include `pip3` version `21.0.1`. So the following now seems to work:

```
brew install python@3.8
pip3 install tensorflow
```

**Comment by mihaimaruseac** [comment]
Awesome. What else is needed for this issue?

**Comment by jameshfisher** [comment]
I think nothing, so I'll close it!

**Comment by torgeir** [comment]
Hit this coming from homebrew python@3.9. For anyone else ending up here;

`brew install python@3.8` installs alongside 3.9 without linking. Manually pointing to the needed installation worked for us `/usr/local/opt/python@3.8/bin/python3 -m venv venv; ...`

**Comment by agouliel** [comment]
Doesn't work on Macbook Air M1, with macOS Big Sur 11.6, Python 3.8.12 and pip 21.3

**Comment by jeff-hykin** [comment]
`pip install tensorflow-macos`

Note: only works for tensorflow 2 versions
