### ISSUE TITLE
How can I get min/max information from TFlite Intepreter?

### ISSUE THREAD

**Issue by jwj04ok** [tensorflow/tensorflow#47200]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.4.1
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I can see the min/max information by using netron open .tflite file. I need those two information to calculate radix. However, I cannot get min/max from any API provided in TFLite Intepreter. I guess to use get_tensor_details(). However I can only get the scale and zero point. Is there any way I can access min/max?

**Will this change the current api? How?**
Yes, adding one or two items in get_tensor_details()
**Who will benefit with this feature?**
Anyone that wants to calculate radix from quantized models in TFLite
**Any Other info.**

**Comment by teijeong** [comment]
Can you describe your use case? (As you might be aware) you can calculate min/max from scale and zero points, like `((DTYPE_MIN - zero_point) * scale, (DTYPE_MAX - zero_point) * scale)`

**Comment by jwj04ok** [comment]
> Can you describe your use case? (As you might be aware) you can calculate min/max from scale and zero points, like `((DTYPE_MIN - zero_point) * scale, (DTYPE_MAX - zero_point) * scale)`

Oh, thanks for your explanation.Now I know how to calculate scale and zero points.
