### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by rutvi1462** [tensorflow/tensorflow#47204]
I am learning object-detection from [this link](https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/).

But I **got an error** while run command in **anaconda prompt**:

(base) R:\SEMESTER 8\SC\eye-detection\models\research\object_detection\legacy>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
2021-02-17 15:30:15.419573: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-02-17 15:30:15.419775: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
  File "R:\Anaconda\anaconda\lib\site-packages\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "R:\Anaconda\anaconda\lib\site-packages\object_detection\data_decoders\tf_example_decoder.py", line 27, in <module>
    slim_example_decoder = tf.contrib.slim.tfexample_decoder
AttributeError: module 'tensorflow' has no attribute 'contrib'

### What I have tried:

- I tried to automatically upgrade script to tensorflow2 using [single python file command](https://www.tensorflow.org/guide/upgrade#single_file). But didn't work for me.
(base) R:\Anaconda\anaconda\Lib\site-packages\object_detection\data_decoders>**tf_upgrade_v2 --infile tf_example_decoder.py --outfile tf_example_decoder.py**
2021-02-17 15:14:35.610773: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-02-17 15:14:35.611176: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
ERROR line 27:23: Using member tf.contrib.slim.tfexample_decoder in deprecated module tf.contrib. tf.contrib.slim.tfexample_decoder cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
ERROR line 62:23: Using member tf.contrib.lookup.HashTable in deprecated module tf.contrib. tf.contrib.lookup.HashTable cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
ERROR line 63:20: Using member tf.contrib.lookup.KeyValueTensorInitializer in deprecated module tf.contrib. tf.contrib.lookup.KeyValueTensorInitializer cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
ERROR line 71:31: Using member tf.contrib.lookup.HashTable in deprecated module tf.contrib. tf.contrib.lookup.HashTable cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
ERROR line 72:20: Using member tf.contrib.lookup.KeyValueTensorInitializer in deprecated module tf.contrib. tf.contrib.lookup.KeyValueTensorInitializer cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
TensorFlow 2.0 Upgrade Script
**Converted 1 files
Detected 5 issues that require attention
File: tf_example_decoder.py**
tf_example_decoder.py:27:23: ERROR: Using member tf.contrib.slim.tfexample_decoder in deprecated module tf.contrib. tf.contrib.slim.tfexample_decoder cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
tf_example_decoder.py:62:23: ERROR: Using member tf.contrib.lookup.HashTable in deprecated module tf.contrib. tf.contrib.lookup.HashTable cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
tf_example_decoder.py:63:20: ERROR: Using member tf.contrib.lookup.KeyValueTensorInitializer in deprecated module tf.contrib. tf.contrib.lookup.KeyValueTensorInitializer cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
tf_example_decoder.py:71:31: ERROR: Using member tf.contrib.lookup.HashTable in deprecated module tf.contrib. tf.contrib.lookup.HashTable cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
tf_example_decoder.py:72:20: ERROR: Using member tf.contrib.lookup.KeyValueTensorInitializer in deprecated module tf.contrib. tf.contrib.lookup.KeyValueTensorInitializer cannot be converted automatically. tf.contrib will not be distributed with TensorFlow 2.0, please consider an alternative in non-contrib TensorFlow, a community-maintained repository such as tensorflow/addons, or fork the required code.
Make sure to read the detailed log 'report.txt'

- tried to install downgrade tesorflow version but not supported in python 3.9.1
- tried to run this code in cmd also but got same error.

**_Tensorflow Version: 2.4.1
python version: 3.9.1
windows: 10
conda 4.9.2_**

Can anyone know proper solution for this?

**Comment by fsx950223** [comment]
Use [tf_slim](https://github.com/google-research/tf-slim) instead

**Comment by rutvi1462** [comment]
@fsx950223 instead of which I have to use tf_slim?

**Comment by fsx950223** [comment]
You should pull tensorflow models' latest codebase since they have updated the code.

**Comment by rutvi1462** [comment]
Hey @fsx950223 thanks for your help. But I need your help one more time. To install updated model directory I follow [this link](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) and its work properly. but I am not moving forward because of following error.

R:\SEMESTER 8\SC\models\research\object_detection\legacy>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    tf.app.run()
  File "R:\minianaconda\minianaconda\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "R:\minianaconda\minianaconda\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "R:\minianaconda\minianaconda\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "R:\minianaconda\minianaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 340, in new_func
    return func(*args, **kwargs)
  File "train.py", line 169, in main
    trainer.train(
  File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\legacy\trainer.py", line 302, in train
    training_optimizer, optimizer_summary_vars = optimizer_builder.build(
  File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\builders\optimizer_builder.py", line 153, in build
    return build_optimizers_tf_v1(config, global_step)
  File "R:\minianaconda\minianaconda\lib\site-packages\object_detection\builders\optimizer_builder.py", line 86, in build_optimizers_tf_v1
    optimizer = tf_opt.MovingAverageOptimizer(
NameError: name 'tf_opt' is not defined

**This error come from** [optimizer_builder.py](https://github.com/tensorflow/models/blob/master/research/object_detection/builders/optimizer_builder.py).

Please help me to solve this.

**Comment by ravikyram** [comment]
@rutvi1462 

This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thanks!

**Comment by rutvi1462** [comment]
@ravikyram Thanks I will post there.
