### ISSUE TITLE
Replacing activation in a pretrained network

### ISSUE THREAD

**Issue by mrtpk123** [tensorflow/tensorflow#47208]
I'm trying to replace swish activation with relu activation in pretrained TF model EfficientNetB0. EfficientNetB0 uses swish activation in Conv2D and Activation layers. I could not find any relevant resources on how to do this. Is there any TF API to do this? Below is the code that I'm working on to replace swish activations with relu activations. Any pointers/help on replacing the activation is much appreciated.

```
import tensorflow as tf
from tensorflow.keras.layers import ReLU

def replace_swish_with_relu(model):
    '''
    Modify passed model by replacing swish activation with relu
    '''
    for layer in tuple(model.layers):
        layer_type = type(layer).__name__
        if hasattr(layer, 'activation') and layer.activation.__name__ == 'swish':
            print(layer_type, layer.activation.__name__)
            if layer_type == "Conv2D":
                # conv layer with swish activation.
                # Do something
                layer.activation = ReLU() # This didn't work
            else:
                # activation layer
                # Do something
                layer = tf.keras.layers.Activation('relu', name=layer.name + "_relu") # This didn't work
    return model

# load pretrained efficientNet
model = tf.keras.applications.EfficientNetB0(
    include_top=True, weights='imagenet', input_tensor=None,
    input_shape=(224, 224, 3), pooling=None, classes=1000,
    classifier_activation='softmax')

# convert swish activation to relu activation
model = replace_swish_with_relu(model)
model.save("efficientNet-relu")
```

**Comment by rmothukuru** [comment]
@mrtpk123,
Can you please let us know why are you trying to do so? Also, if you change the Activation Function, will the purpose of Transfer Learning be fulfilled, i.e..I don't think we will be able to Freeze the Layers or reuse the Weights. Thanks!

**Comment by mrtpk123** [comment]
Hi @rmothukuru, Thank you for the reply. 

Actually, I'm in search of an EfficientNet pretrained model with ReLU activations. My plan is to retrain the existing model after replacing the swish activations. Thank you.
