### ISSUE TITLE
Tensorflow Lite QAT: Double QUANT/DEQUANT in half-quantized and failure in full-quantized model conversion

### ISSUE THREAD

**Issue by gfilippi** [tensorflow/tensorflow#47213]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04.1-Ubuntu
- TensorFlow installation (pip package or built from source): pip install tensorflow==2.3.0-gpu
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

import tensorflow as tf

import tensorflow_model_optimization as tfmot

from constants import *
from dataset_loader import DatasetLoader

import cv2
from constants import *
import numpy as np

import numpy as np
import pathlib
from imutils import paths
import argparse

if __name__ == '__main__':

    ap = argparse.ArgumentParser()
    ap.add_argument("-m", "--model", type=str, default="none", help="name of pre-trained network to use")
    ap.add_argument("-q", "--qat", type=int, default=1, help="use qat")
    args = vars(ap.parse_args())

    #
    # LOAD MODEL
    #
    print("[INFO] load model from file... {}".format(args["model"]))
    model = tf.keras.models.load_model(args["model"])

    # LOAD DATASET
    dl = DatasetLoader()
    dl.load()
    trainX = dl.images
    valX   = dl.images_test
    trainY = dl.labels
    valY   = dl.labels_test

    # .npy data are UINT8_T, SIZE_FACExSIZE_FACE, convert to float
    trainX = trainX.astype("float")
    valX = valX.astype("float")

    #
    # QAT
    #
    if(args["qat"]):
        print("[INFO] build QAT model")

        quantize_model = tfmot.quantization.keras.quantize_model

        q_aware_model = quantize_model(model)

        q_aware_model.compile(optimizer='adam',
                  loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])

        q_aware_model.fit( trainX,
                           trainY,
                           validation_data=(valX, valY),
                           shuffle=True,                       
                           batch_size=256, 
                           epochs=1, 
                           validation_split=0.1)

        baseline_model_accuracy = model.evaluate( valX, valY, verbose=0)
        q_aware_model_accuracy = q_aware_model.evaluate(valX,valY, verbose=0)

        _, baseline_model_accuracy = model.evaluate(
            valX, valY, verbose=0)

        _, q_aware_model_accuracy = q_aware_model.evaluate(
            valX, valY, verbose=0)

        print(baseline_model_accuracy )
        print(q_aware_model_accuracy)

    if(args["qat"]):
        print("\n[INFO] set converter...")
        my_model=q_aware_model
    else:
        print("\n[INFO] set converter...")
        my_model = model

    converter = tf.lite.TFLiteConverter.from_keras_model( my_model ) 

    print("\n[INFO] convert to TFLITE/FLOAT32")
    tflite_model = converter.convert()

    #
    # STORE: tflite model where all the parameters are FLOAT32
    #
    tflite_models_dir = pathlib.Path("./output")
    tflite_models_dir.mkdir(exist_ok=True, parents=True)

    tflite_model_file = tflite_models_dir/"fer_model_float.tflite"
    print("[INFO] writing TFLITE/FLOAT32    : {}".format(tflite_model_file))
    tflite_model_file.write_bytes(tflite_model)

    #
    # STORE: tflite model where all the parameters are UINT8
    #
    converter2 = tf.lite.TFLiteConverter.from_keras_model(my_model ) 
    
    representative_ds = tf.data.Dataset.from_tensor_slices((trainX)).batch(32)

    def representative_data_float_gen():
      for input_value in representative_ds.take(100):
        yield [input_value]

    # convert again, in/out & parameters are now UINT8
    converter2.optimizations = [tf.lite.Optimize.DEFAULT]
    converter2.representative_dataset = representative_data_float_gen

    print("\n[INFO] convert to TFLITE/HALF-QUANT")
    tflite_model_quant      = converter2.convert()
    tflite_model_quant_file = tflite_models_dir/"fer_model_half-quant.tflite"
    print("[INFO] writing TFLITE/HALF-QUANT : {}".format(tflite_model_quant_file))
    tflite_model_quant_file.write_bytes(tflite_model_quant)

    #
    # STORE: tflite model where all the parameters are still using float32
    #
    converter3 = tf.lite.TFLiteConverter.from_keras_model(my_model ) 
    converter3.representative_dataset      = representative_data_float_gen
    converter3.optimizations               = [tf.lite.Optimize.DEFAULT]
    converter3.target_spec.supported_ops   = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter3.target_spec.supported_types = [tf.int8]    
    converter3.inference_input_type        = tf.uint8
    converter3.inference_output_type       = tf.uint8

    print("\n[INFO] convert to TFLITE/FULL-QUANT")
    tflite_model_quant_io = converter3.convert()
    tflite_model_quant_io_file = tflite_models_dir/"fer_model_full-quant.tflite"
    print("[INFO] writing TFLITE/FULL-QUANT : {}".format(tflite_model_quant_io_file))
    tflite_model_quant_io_file.write_bytes(tflite_model_quant_io)

    # END
    print("\nbye.\n\n")

The keras model is very simple:

class SimpleNet:
    @staticmethod
    def build(width, height, depth, classes, stages, filters, reg=0.0001, bnEps=2e-5, bnMom=0.9):

        inputShape = (height, width, depth)
        chanDim = -1

        if K.image_data_format() == "channels_first":
            inputShape = (depth, height, width)
            chanDim = 1

        model = tf.keras.Sequential()

        model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu', input_shape=inputShape ))
        model.add(MaxPooling2D((3, 3), strides=(2, 2)))
        model.add(Conv2D(filters=64, kernel_size=(5, 5), activation='relu'))
        model.add(MaxPooling2D((3, 3), strides=(2, 2)))
        model.add(Conv2D(filters=128, kernel_size=(3, 3), activation='relu'))
    
        model.add(Flatten())
        model.add(Dropout(0.3))
        model.add(Dense(512, kernel_regularizer=l2(reg)))
        model.add(Dropout(0.3))
        model.add(Dense(256, kernel_regularizer=l2(reg)))
        model.add(Dropout(0.3))
        model.add(Dense(classes, activation="softmax"))        

        return model

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:
I'm training the keras model and the converting to tflite using QAT as per official documentation.

Conversion to half-quantization is successful but the .tflite model has n.2 QUANTIZE at the input and n.2 DEQUANTIZE at the output.

Conversion to full-quantized model fails to convert but I cannot detect what op is not supported, here is my console log

[INFO] load model from file... ./output/fer_model_float.hdf5
[INFO] build QAT model
69/69 [==============================] - 3s 43ms/step - loss: 1.8564 - accuracy: 0.6415 - val_loss: 1.7545 - val_accuracy: 0.6627
0.6648070812225342
0.6155276894569397

[INFO] set converter...

[INFO] convert to TFLITE/FLOAT32
[INFO] writing TFLITE/FLOAT32    : output/fer_model_float.tflite

[INFO] convert to TFLITE/HALF-QUANT
[INFO] writing TFLITE/HALF-QUANT : output/fer_model_half-quant.tflite

[INFO] convert to TFLITE/FULL-QUANT
Traceback (most recent call last):
  File "./tflite.py", line 217, in <module>
    tflite_model_quant_io_file.write_bytes(tflite_model_quant_io)
  File "/home/gfilippi/.virtualenvs/tf23/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 831, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/gfilippi/.virtualenvs/tf23/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/gfilippi/.virtualenvs/tf23/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 452, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/home/gfilippi/.virtualenvs/tf23/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 98, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Quantization not yet supported for op:

### 5. (optional) Any other info / logs
this seems similar to the problem documented here:

https://github.com/tensorflow/tensorflow/issues/41308

![double_q-deq](https://user-images.githubusercontent.com/1153348/108218102-99f2db00-7134-11eb-827a-26a09017a89f.png)

**Comment by gfilippi** [comment]
adding one more info: if I use TF2.4 for conversion I still have the same problem (double quant/dequant on the half-quantized model) and the full-quantized seems to have a different failure related to the output type ... but I don't know how to set this properly other than the code I wrote as per official documentation on QAT

[INFO] convert to TFLITE/FULL-QUANT
Traceback (most recent call last):
  File "./tflite.py", line 214, in <module>
    tflite_model_quant_io = converter3.convert()
  File "/home/gfilippi/.virtualenvs/tf24/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 874, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/gfilippi/.virtualenvs/tf24/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 637, in convert
    result = _modify_model_io_type(result, **flags_modify_model_io_type)
  File "/home/gfilippi/.virtualenvs/tf24/lib/python3.6/site-packages/tensorflow/lite/python/util.py", line 843, in modify_model_io_type
    _modify_model_output_type(model_object, inference_output_type)
  File "/home/gfilippi/.virtualenvs/tf24/lib/python3.6/site-packages/tensorflow/lite/python/util.py", line 753, in _modify_model_output_type
    _get_tf_type_name(quant_type)))
ValueError: Initial model output is not dequantized. Expected type for tensor with name 'b'sequential/quant_dense_2/Softmax_float'' should be in ('tf.int8', 'tf.int16'), instead type is tf.float32

**Comment by teijeong** [comment]
Hi, with tf-nightly, would you try setting `experimental_new_quantizer` and see if there's difference?

```python
converter.experimental_new_quantizer = True
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
