### ISSUE TITLE
TypeError if set the weights to the current weights via `set_weights`

### ISSUE THREAD

**Issue by noppelmax** [tensorflow/tensorflow#47216]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04 `Linux XXX 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): `v2.4.0-49-g85c8b2a817f 2.4.1`
- Python version: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`

**Describe the current behavior**
I get the error `TypeError: __array__() takes 1 positional argument but 2 were given`. Hence it might be related to bug #46840. 

**Describe the expected behavior**
Should just set the weight to what they are right now.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

denseLayer = tf.keras.layers.Dense(1,activation="relu")
denseLayer.build(input_shape=(4))

denseLayer.set_weights(denseLayer.weights)
```
Link: [Colab](https://colab.research.google.com/drive/1bwHmMvktEsLzOK-x8fsmIJBiNJGfsM9F?usp=sharing)

**Other info / logs** 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-99e968378f7a> in <module>
      4 denseLayer.build(input_shape=(4))
      5 
----> 6 denseLayer.set_weights(denseLayer.weights)

~/Projects/NotebooksEnvs/py38Env/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in set_weights(self, weights)
   1875         weight_index += 1
   1876 
-> 1877     backend.batch_set_value(weight_value_tuples)
   1878 
   1879   def get_weights(self):

~/Projects/NotebooksEnvs/py38Env/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/Projects/NotebooksEnvs/py38Env/lib/python3.8/site-packages/tensorflow/python/keras/backend.py in batch_set_value(tuples)
   3704   if ops.executing_eagerly_outside_functions():
   3705     for x, value in tuples:
-> 3706       x.assign(np.asarray(value, dtype=dtype(x)))
   3707   else:
   3708     with get_graph().as_default():

~/Projects/NotebooksEnvs/py38Env/lib/python3.8/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     81 
     82     """
---> 83     return array(a, dtype, copy=False, order=order)
     84 
     85 

TypeError: __array__() takes 1 positional argument but 2 were given
```

**Comment by noppelmax** [comment]
It turns out, that it works with `get_weights()` but still, this should yield a reasonable error message.

**Comment by ravikyram** [comment]
Was able to reproduce the issue with  TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/ravikyram/be8bceb82372692740dc74da02749466/untitled674.ipynb). Thanks!

**Comment by shivaditya-meduri** [comment]
Hi, I want to work on creating a more suitable error message for this scenario. I was thinking something like
TypeError: set_weights() expects a list of  expected_num_weights weights in the form of arrays, but instead received  list of tf.variable
