### ISSUE TITLE
I have problem with python code in google colab

### ISSUE THREAD

**Issue by walaamm** [tensorflow/tensorflow#47218]
I write this code:
basemodel.fit(X_train,y_train,epochs=20,validation_split=.1,callbacks=call_back)
but don't work this error:
Epoch 1/20
ValueError Traceback (most recent call last)
in ()
----> 1 basemodel.fit(X_train,y_train,epochs=20,validation_split=0.1,callbacks=call_back)

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
975 except Exception as e: # pylint:disable=broad-except
976 if hasattr(e, "ag_error_metadata"):
--> 977 raise e.ag_error_metadata.to_exception(e)
978 else:
979 raise

**Comment by amahendrakar** [comment]
@walaamm,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. 

Alternatively, you can also share the Colab notebook you are running, with us. Thanks!
