### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by dmidge8** [tensorflow/tensorflow#47212]
I encounter a bug that occurs when I try to import tensorflow in a conda environment (python 3.8). All my attempts so far, to even revert to a previous version or recreate the environment from scratch with different version of tensorflow, failed so far.
The issue is similar to https://github.com/tensorflow/tensorflow/issues/42084 but I didn't manage to get a fix out of it, even some others have the same issue (and the end was "It's better to open a new issue and post the full details."), so here I am!

# About the system
A Kubuntu (Linux) computer, version 20.04. The installation step are close to https://www.tensorflow.org/install/pip#ubuntu-macos, adapted to the current version of Kubuntu for the nvidia dependencies.
Pilots Nvidia Updated
CUDA/cuDNN version: 11.00
TF installed from conda (Binary)
TF version 2.2.0 or 2.3.0

# Step to reproduce
Launch python 3.8
```
>>> import tensorflow
2021-02-17 10:35:57.687845: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/home/me/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /home/me/.conda/envs/CasComplexe/lib/python3.8/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb
```

**Comment by ravikyram** [comment]
@dmidge8 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).Can you try with CUDA 10.1 and see if the issue still persists. Thanks!

**Comment by dmidge8** [comment]
Hi @ravikyram ,
Thank you for your answer. I had CUDA 10.1 and it was not working. It was complaining that it couldn't find libcudart.so.11.0 (which is normal since it CUDA 10.1 was installed, but I have no idea why it was looking for CUDA 11.0). Anyway, fast forward, I installed the correct version of CUDA and the drivers following the Tensorflow tutorial. And the warning on libcudart disappeared.

Prior to that (around one month ago), my environment was working, but for some reason, it broke. I remember that I played to have tensorboard working in the environment, but I can't remember what I did that could have broke tensorflow, thus I started over with a clean environment and can't get it to work since then, with various version of tensorflow. I tried to clean the conda cache, but it is not helping. I guess that it is my upper environment that has some mismatched *.so that for some reason, the tensorflow in conda is looking for.

Anyway, the crash happen even when I don't want to use CUDA (I am just importing TF), thus I don't even have the CPU environment working.

**Comment by jvishnuvardhan** [comment]
@dmidge8 Generally we don't support Anaconda built TF packages. TF built 2.2 and 2.3 requires CUDA10.1. However, we don't have any idea about Conda 2.3 package. 

Is it possible to install `TF2.4` or `tf-nightly` using `pip`? As you already have `CUDA11`, installing TF using `pip` should work. Also, can you please try different python version such as `3.6` or `3.7`? I asking this because I notice others also facing similar issue where they have `TF2.3` and `python3.8`. Thanks!

**Comment by dmidge8** [comment]
Hi @jvishnuvardhan ,
Thanks for your interest in the issue!
I tried to install it with pip in the conda environment, and it didn't solve anything. Even with various versions. The odd part though is that installing it through pip *outside* of the conda environment did solve the problem *inside* the conda environment (I had to go through another loop of installation though in the conda environment, with the conda pip installation). It is odd... It is kink of if the conda package tries to reach for a package that is outside of the environment and can't see it if it is only present inside the environment....
However, I didn't try with `tf-nightly`...

**Comment by jvishnuvardhan** [comment]
@dmidge8 Please try with `tf-nighly` also and close the issue if it was resolved for you. Generally we don't support Anaconda based issues. If you can post them in their repo, you might get faster resolutions related those issue. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this is more related Anaconda repository than TensorFlow. Please feel free to reopen if I am mistaken. Thanks!
