### ISSUE TITLE
DSP HiFi4 support (delegate) for TF-Lite

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#47217]
I wonder if there is any support (experimental) for HiFi4 DSP of Cadance ([Xtensa HiFi4 Audio DSP](https://ip.cadence.com/uploads/928/TIP_PB_HiFi_DSP_FINAL-pdf)), and possibly check there is an execution mechanism, probably delegate executor for this DSP.  
So question or request is: Is there any support available or would be possible to add HiFi4 delegate or another mechanism to leverage from HiF4 DSP?

**Comment by jdduke** [comment]
Hi @peter197321, can you say a little more about what platform/OS you're using for deployment? And what the size/type of your model is? Thanks.

**Comment by peter197321** [comment]
Hello Jared,

My platform/OS is Linux.
I'd deploy the models for audio recognition, and to have the sound
classification models.

Thank you.

**Comment by jdduke** [comment]
Is there a reason you cannot use TFLM?

On the TFLite side, there are no plans to build such a delegate, though you could potentially leverage some of the optimized kernels that have already been written for TFLM. It really depends on whether you expect graph execution to run entirely on the DSP, or if you want the host CPU in the loop.
