### ISSUE TITLE
Long prediction time when using tensorflow lite optimize

### ISSUE THREAD

**Issue by ark1375** [tensorflow/tensorflow#47223]
I wrote a model based on the VGG16 using mostly TensorFlow documentation. After training, I saved the model into a .h5 file.
When I run the prediction, it takes about a second and a half to return the results. As I try to optimize the prediction time using `tensorflow.lite.Optimize.DEFAULT` (code available below) the prediction time increases drastically. I'm talking about almost 600 times slower than the normal code (when I don't use the Optimize). Why is that? Shouldn't optimize suppose to decrease the prediction time instead of increasing it? I used the *default* optimizer, *latency* optimizer, and *size* optimizer without any change in the result.
I used both CPU and GPU versions of TensorFlow without any significant change in the result.

**My system is:**
-  Intel Core i7 9700H
-  16 Gb DDR4 2300Mhz
-  GTX 1660ti (mobile version)
-  Windows 10 (latest build)

The code:
```
import tensorflow as tf
import os
import time
import numpy as np
from tensorflow import keras
import pathlib

saved_model_dir= 'model/'
saved_modelh5 = 'model.h5'
dataset_path = 'bound box dataset/img'
out_path = 'converted_model.tflite'
num_calibration_steps = 1

print("Im doing something")

converter = tf.lite.TFLiteConverter.from_keras_model(keras.models.load_model(saved_modelh5))  
converter.optimizations = [tf.lite.Optimize.DEFAULT  ]
tflite_model = converter.convert()


#------------------------------------------------------------
#with open(out_path, "wb")as f:
print('converted')
tflite_model_file = pathlib.Path(out_path)
tflite_model_file.write_bytes(tflite_model)
print('Saved')


input_data = np.random.rand(1,512,512,3).astype(np.float32)

interpreter = tf.lite.Interpreter( model_content = tflite_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
t = time.time()
input_shape = input_details[0]['shape']
#input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
print('start invoke')
interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])

t = time.time() - t
print('predict time:',t)
```

**Comment by amahendrakar** [comment]
@ark1375,
On running the code I'm facing an error stating `OSError: SavedModel file does not exist at: model.h5/{saved_model.pbtxt|saved_model.pb}`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/02ac68a2cc96b459305597c3727bd87f/47223.ipynb).

In order to expedite the trouble-shooting process, could you please provide all the files required to run the code. Thanks!

**Comment by ark1375** [comment]
I uploaded the required file [here](https://drive.google.com/file/d/12EmRy4zf3Bpz5rQKLKortPnKYn0KcAlj/view?usp=sharing). Because the model data was too large, I had to upload it to Google Drive. 
I ran the model using Python 3.7 and the latest version of TensorFlow that I could install from pip (2.4).

**Comment by ark1375** [comment]
@amahendrakar
Did it work? Could you run the code with the file that I linked to?

**Comment by teijeong** [comment]
Hi @ark1375,

The quantized op kernels are usually optimized for ARM architecture, but not so for x86. TensorFlow Lite model doesn't work with desktop GPUs and even if it's supported, GPUs don't support integer calculations.

You can try build your custom tflite runtime with `ruy` enabled, but the inference speed is still not going to be as fast as the float one.

**Comment by ark1375** [comment]
@teijeong First of all thanks for the answer. Second, you think if I ran the model on a Raspberry pi, then I could see the difference in speed?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/4947b00a5b3eb902506eebdf37d4b575/47223.ipynb) and TF-nightly, where prediction time is ~ 260 seconds.

Whereas with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/34520b50b6ff3f535ce33ecba8876896/47223-2-3.ipynb), the predict time is ~6 seconds. Please check the linked gist for reference. Thanks!

**Comment by teijeong** [comment]
@ark1375 sorry for late reply. Yes, I think you might observe some sppedup when running on rpi, depending on its hardware capability.

@terryheo It seems weird to see latency getting higher from ~6s to ~260s. Can you take a look? We need to verify first if they had run on the same machine though.

**Comment by terryheo** [comment]
Regarding the performance, you'd better specify num_threads since TF 2.4.

```
interpreter = tf.lite.Interpreter( model_content = tflite_model, num_threads=16)
```

It looks like a regression, anyway it solves your issue.

**Comment by talumbau** [comment]
Hi,

Thanks for reporting this issue. With recent versions of TensorFlow, the conversion to TF Lite format with the optimization options you mention will use the new "dynamic range per-channel" quantization method, whereas previous versions (e.g. v2.3) use the older "dynamic range per-tensor" quantization method. For this new method, when running the converted model on x86 you need to build with a more recent version of GCC (9 or higher) or a more recent version of MS Visual C++ `__MSC_VER` 1920 or higher to get optimized code.

We are going to land a workaround that will permit running the old path for for models converted in v2.3 (dynamic range per-tensor). Upgrading your compiler version is another way to fix this issue. I will close once we land the workaround. Cheers!

**Comment by sachinprasadhs** [comment]
Hi, Could you please convert and test your model in the latest version, since the code which you are using is the legacy version.
Also, could you please update the compiler and let us know if you observe the same behavior. Thanks!
