### ISSUE TITLE
Keras cannot restore custom functions for subclassed Model, but for subclassed Layer custom functions can be restored

### ISSUE THREAD

**Issue by blackyang** [tensorflow/tensorflow#47224]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Keras cannot restore custom functions for subclassed Model, even with custom_object arguments; but for subclassed Layer, custom functions can be restored. See two code snippet attached.

**Describe the expected behavior**
I expect the consistent behavior between subclassed Model and subclassed Layer

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
 import tensorflow as tf
 import numpy as np

 class MyModel(tf.keras.models.Model):

   def __init__(self, **kargs):
     super(MyModel, self).__init__(**kargs)
     self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
     self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)

   def call(self, inputs):
     x = self.dense1(inputs)
     return self.dense2(x)

   def about(self):
       print("123")

 model = MyModel()

 x = np.random.random((2, 3))
 model(x)

 model_file = "model_file"
 model.save(model_file)

 loaded_model = tf.keras.models.load_model(model_file, custom_objects={"MyModel": MyModel})
 loaded_model.about()
```

```
 import tensorflow as tf
 import numpy as np


 class MyDense(tf.keras.layers.Dense):
     def __init__(self, units, **kargs):
         super(MyDense, self).__init__(units=units, **kargs)
     def call(self, inputs):
         return super(MyDense, self).call(inputs)
     def my_units(self):
         return self.units
     @classmethod
     def convert_to_p(cls, p_inputs):
         print("now converting to p")

 x = tf.keras.Input(shape=(10,))
 dense1 = MyDense(units=20)(x)
 y = MyDense(units=30)(dense1)
 model = tf.keras.models.Model(inputs=[x], outputs=[y])
 # tf.keras.utils.plot_model(model)
 outputs = model(np.random.random((2, 10)))
 model_path = "./foo"
 model.save(model_path)
 loaded_model = tf.keras.models.load_model(model_path, custom_objects={"MyDense": MyDense})
 for layer in loaded_model.layers:
     if hasattr(layer, "my_units"):
         print(layer.name, layer.my_units())
         layer.convert_to_pynchpin([1])
         print()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@blackyang 

I tried in colab with TF 2.4 .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3393146ba2def5305e8b0aa9b8451a8d/untitled675.ipynb).You are also seeing the same behavior?
Thanks!

**Comment by blackyang** [comment]
@ravikyram the colab exactly showed the issue, calling `loaded_model.about()` will result an error, but calling `layer.my_units()` is fine

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
