### ISSUE TITLE
LSTM - Issue with model fitting using ragged tensor

### ISSUE THREAD

**Issue by sebgra** [tensorflow/tensorflow#47222]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Linux Ubuntu 16.04 / Google Colab
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9
- CUDA/cuDNN version: Not used
- GPU model and memory: None

** Problem Description**

I'm working on classification of ECG signals into 4 classes. Each sequence to be classified has potentially different lengths. Sequences are stored into a ragged tensor. 

The model is based on LSTM layers. Unfortunatly when I try to fit the model using the function "fit" there is a problem about matrix size incompatibility:

```
InvalidArgumentError:  Matrix size-incompatible: In[0]: [32,18000], In[1]: [18286,256]
	 [[node sequential/LSTM_1/lstm_cell/MatMul (defined at <ipython-input-7-36997f53d4b2>:19) ]] [Op:__inference_train_function_6985]
```
Nevertheless, when I use a subset of this exact dataframe (25 sequence of 8500+), the training is going well to the end. 

I have verified, there are no Nan of None in my sequences. 

**Describe the current behavior**

The training of the model returns an error concerning matrix size incompatibility. The training can be performed when using a subset of the dataset.

**Describe the expected behavior**

Model can be trained well with the entire dataset

**Standalone code to reproduce the issue**

_Notebook link :_  https://colab.research.google.com/drive/1RdtafxvD_5nqh9-xuG6o8WL4GOd9IZnN?authuser=1#scrollTo=Dzq3tRK9cwbe

_Data link :_ https://drive.google.com/file/d/1V9nNxMehtiwAjNVS-8usTP6Jol9jC6et/view?usp=sharing

**Other info / logs** 

```
Epoch 1/10
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-36997f53d4b2> in <module>()
     17 model.summary()
     18 
---> 19 model.fit(xx,yy, epochs=10) # --> Doesn t working with the full dataset, matrix size error

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  Matrix size-incompatible: In[0]: [32,18000], In[1]: [18286,256]
	 [[node sequential/LSTM_1/lstm_cell/MatMul (defined at <ipython-input-7-36997f53d4b2>:19) ]] [Op:__inference_train_function_6985]

Function call stack:
train_function
```
Thanks in advance

**Comment by Saduf2019** [comment]
@sebgra 
I am unable to access the notebook shared, please refer to [this link](https://stackoverflow.com/questions/50158475/invalidargumenterror-matrix-size-incompatible-in0-256-2048-in1-256-1) meanwhile and let us know if it helps.

**Comment by sebgra** [comment]
@Saduf2019 
[cardiology_challenge_2017.zip](https://github.com/tensorflow/tensorflow/files/6001993/cardiology_challenge_2017.zip)
 Here's the .py code

Original file is located at
    https://colab.research.google.com/drive/1RdtafxvD_5nqh9-xuG6o8WL4GOd9IZnN
"""

from google.colab import drive
drive.mount("/content/drive")

"""# Importing Libraries"""

import numpy as np
import tensorflow as tf
import keras
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

```
"""# Reading Database"""

df = pd.read_pickle('/content/drive/MyDrive/Cardiology/Data_Set/Cardiology_Dataset') # Full dataset : Cardiology_Dataset file 
#--> https://drive.google.com/file/d/1V9nNxMehtiwAjNVS-8usTP6Jol9jC6et/view?usp=sharing
df

"""# Implementing Model"""

xx = tf.ragged.constant(df['Sequence'])

yy = tf.one_hot(df['Label'],4)
xx.bounding_shape()[-1]

#max_seq = X_train.bounding_shape()[-1]
max_seq = xx.bounding_shape()[-1]
print(f'Maximum length sequence : {max_seq}')

model = keras.Sequential([
                          tf.keras.layers.Input(shape=[None, max_seq], dtype=tf.float32, ragged=True),
                          keras.layers.LSTM(units=64, activation='tanh', dropout=0.2, name = 'LSTM_1', return_sequences=True),
                          keras.layers.LSTM(units=256, activation='tanh', dropout=0.2, name = 'LSTM_2',return_sequences=True),
                          keras.layers.LSTM(units=100, activation='tanh', dropout=0.2, name = 'LSTM_3', return_sequences=False),
                          tf.keras.layers.Dense(units=4, activation='sigmoid', name = 'Dense_1')
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

model.summary()

model.fit(xx,yy, epochs=10) # --> Doesn t working with the full dataset, matrix size error

"""# Subset of the original dataset --> Working"""

sub_df = df.head(25)

xx_sub = tf.ragged.constant(sub_df['Sequence'])

yy_sub = tf.one_hot(sub_df['Label'],4)


max_seq = xx_sub.bounding_shape()[-1]

model = keras.Sequential([
                          tf.keras.layers.Input(shape=[None, max_seq], dtype=tf.float32, ragged=True),
                          keras.layers.LSTM(units=64, activation='tanh', dropout=0.2, name = 'LSTM_1', return_sequences=True),
                          keras.layers.LSTM(units=256, activation='tanh', dropout=0.2, name = 'LSTM_2',return_sequences=True),
                          keras.layers.LSTM(units=100, activation='tanh', dropout=0.2, name = 'LSTM_3', return_sequences=False),
                          # tf.keras.layers.LSTM(4),
                          #tf.keras.layers.Flatten(name = 'Flatten'),
                          tf.keras.layers.Dense(units=4, activation='sigmoid', name = 'Dense_1')
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

model.summary()

model.fit(xx_sub,yy_sub, epochs=10, shuffle=False) # --> No problem with a subset of the original dataset, why ?
```

**Comment by around-star** [comment]
@Saduf2019 , @sebgra , Even though I didn't run your code, I think that your **Input Layer's** `shape` declaration is causing the error. You declared the shape to **[None, max_seq]** , but it would only be compatible for tensors having that exact shape. Since you used **ragged tensors** and since the shape of all the sequences are not same i.e. not equal to [None, max_seq] , the code is running into the error. Try changing the **Input Layer's** shape to `[None, None]` and check if it works.

**Comment by sebgra** [comment]
@around-star This modification returns an error concerning the dense layer : 

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by around-star** [comment]
@sebgra i see . Thats one contraint with `Dense` layers. The feature of the data along the axis which they perform the dot product , needs to be of constant len/size. I would suggest to try padding along the last axis or make some changes in the network so as not to include any `Dense` layer.

**Comment by sebgra** [comment]
@around-star I have made a version of this network with padding. But I am still confused about the performance of the network with zero padding which seems to descrease the performances.

**Comment by Saduf2019** [comment]
@sebgra 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b880db2093b941f34036930007bcf804/untitled549.ipynb).
Please refer to above comment and let us know.

**Comment by sebgra** [comment]
@Saduf2019 That is because you're trying to read a .py file, which is a script and not the data. 
Try to replace  :

`df = pd.read_pickle('/content/cardiology_challenge_2017.py') `

By : 

`df = pd.read_pickle('/content/drive/MyDrive/Cardiology/Data_Set/Cardiology_Dataset')`

Which should correspond to the path of the data available at : 

[https://drive.google.com/file/d/1V9nNxMehtiwAjNVS-8usTP6Jol9jC6et/view?usp=sharing](url)

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210603, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/4695fd45e14c353b84515c11bf87840b/47222.ipynb). Thanks!

**Comment by mathshangw** [comment]
> **System information**
> 
>     * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> 
>     * OS Platform and Distribution : Linux Ubuntu 16.04 / Google Colab
> 
>     * TensorFlow installed from (source or binary): Google Colab
> 
>     * TensorFlow version (use command below): 2.4.1
> 
>     * Python version: 3.6.9
> 
>     * CUDA/cuDNN version: Not used
> 
>     * GPU model and memory: None
> 
> 
> ** Problem Description**
> 
> I'm working on classification of ECG signals into 4 classes. Each sequence to be classified has potentially different lengths. Sequences are stored into a ragged tensor.
> 
> The model is based on LSTM layers. Unfortunatly when I try to fit the model using the function "fit" there is a problem about matrix size incompatibility:
> 
> ```
> InvalidArgumentError:  Matrix size-incompatible: In[0]: [32,18000], In[1]: [18286,256]
> 	 [[node sequential/LSTM_1/lstm_cell/MatMul (defined at <ipython-input-7-36997f53d4b2>:19) ]] [Op:__inference_train_function_6985]
> ```
> 
> Nevertheless, when I use a subset of this exact dataframe (25 sequence of 8500+), the training is going well to the end.
> 
> I have verified, there are no Nan of None in my sequences.
> 
> **Describe the current behavior**
> 
> The training of the model returns an error concerning matrix size incompatibility. The training can be performed when using a subset of the dataset.
> 
> **Describe the expected behavior**
> 
> Model can be trained well with the entire dataset
> 
> **Standalone code to reproduce the issue**
> 
> _Notebook link :_ https://colab.research.google.com/drive/1RdtafxvD_5nqh9-xuG6o8WL4GOd9IZnN?authuser=1#scrollTo=Dzq3tRK9cwbe
> 
> _Data link :_ https://drive.google.com/file/d/1V9nNxMehtiwAjNVS-8usTP6Jol9jC6et/view?usp=sharing
> 
> **Other info / logs**
> 
> ```
> Epoch 1/10
> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-7-36997f53d4b2> in <module>()
>      17 model.summary()
>      18 
> ---> 19 model.fit(xx,yy, epochs=10) # --> Doesn t working with the full dataset, matrix size error
> 
> 6 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      58     ctx.ensure_initialized()
>      59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> ---> 60                                         inputs, attrs, num_outputs)
>      61   except core._NotOkStatusException as e:
>      62     if name is not None:
> 
> InvalidArgumentError:  Matrix size-incompatible: In[0]: [32,18000], In[1]: [18286,256]
> 	 [[node sequential/LSTM_1/lstm_cell/MatMul (defined at <ipython-input-7-36997f53d4b2>:19) ]] [Op:__inference_train_function_6985]
> 
> Function call stack:
> train_function
> ```
> 
> Thanks in advance

did you solve it ?

**Comment by sebgra** [comment]
This hasn't be solved yet. The only solution that I've found is to pad sequence with zeros to get series of the same time. Indeed, the power of the model is unfortunatly decreasing.

**Comment by mathshangw** [comment]
sorry for my late reply . yes, this is my problem too .. can i use reshape ?

**Comment by sebgra** [comment]
Only zero padding help me to make it works but not as efficient as it could. I'm still searching for a slolution

**Comment by GlaIZier** [comment]
@around-star 
> i see . Thats one contraint with `Dense` layers. The feature of the data along the axis which they perform the dot product , needs to be of constant len/size. I would suggest to try padding along the last axis or make some changes in the network so as not to include any `Dense` layer.
Could you elaborate on this please? I don't get it why the Dense layer can't infer the shape in that network. As I understand even if input was [None, None], shape before Dense would be [None, 100] (None for batch) as we don't return sequences in the last LSTM, but only a final state.

@sebgra Tried to reproduce the code and had the same problem. However, Embedding layer helps and I think it might be crucial there:

```
x1 = tf.ragged.constant([[1, 2, 3, 4, 5], [8, 9], [10, 11, 12, 13], [1, 2, 3]])
y1 = tf.constant([[0, 1, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0],])
model1 = tf.keras.Sequential([
                          tf.keras.layers.Input(shape=[None], dtype=tf.int32, ragged=True),
                          tf.keras.layers.Embedding(15, 4),
                          tf.keras.layers.LSTM(units=64, activation='tanh', dropout=0.2, name = 'LSTM_1', return_sequences=True),
                          tf.keras.layers.LSTM(units=256, activation='tanh', dropout=0.2, name = 'LSTM_2',return_sequences=True),
                          tf.keras.layers.LSTM(units=100, activation='tanh', dropout=0.2, name = 'LSTM_3', return_sequences=False),
                          tf.keras.layers.Dense(units=4, activation='sigmoid', name = 'Dense_1')
])


model1.compile(optimizer=tf.keras.optimizers.Nadam(learning_rate=1e-3),
          loss='categorical_crossentropy',
          metrics=['accuracy'])
model1.summary()
model1.fit(x1, y1, batch_size=2)
```

Doc: https://www.tensorflow.org/guide/ragged_tensor#keras

**Comment by vitaly-d** [comment]
@mathshangw , [I played a bit with a notebook you have shared](https://colab.research.google.com/drive/1VbTFVBWacHJ0zTNqXCGUvOgfhP3rRH25?usp=sharing) and found, 

1. **Dimensions are mixed up **:  in`tf.keras.layers.Input(shape=[None,max_seq],` we want `max_seq` to be a sequence len, but instead it defines the features vector size of a timestep, see the `tf.print` output from `call`:  `[32 1 18000]`
 
 2. **Keras somehow failed in getting the bounding shape of the ragged tensor**, it used `18000` instead of `18170`. However, **it doesn't seem like a Keras bug to me, because no one wants to train LSTM with a variable size feature vector**.. 

3. The solution is mentioned in @GlaIZier [comment](https://github.com/tensorflow/tensorflow/issues/47222#issuecomment-1033766102) "Embedding layer helps" to add feature dimension, it's size it just a constant.

It sounds like this issue can be closed.

**Comment by sebgra** [comment]
@vitaly-d I'm still trying to make @GlaIZier 's answer to work, but I'm facing a new error which is :

`InvalidArgumentError:  indices[32] = -9 is not in [0, 18287)
	 [[node sequential_18/embedding_15/embedding_lookup_ragged/embedding_lookup
 (defined at /usr/local/lib/python3.7/dist-packages/keras/layers/embeddings.py:191)
]] [Op:__inference_train_function_219565]
`

The corrected code is : 

`model = keras.Sequential([
                          tf.keras.layers.Input(shape=[None], dtype=tf.float32, ragged=True),
                          tf.keras.layers.Embedding(18286, 4),
                          keras.layers.LSTM(units=64, activation='tanh', dropout=0.2, name = 'LSTM_1', return_sequences=True),
                          keras.layers.LSTM(units=256, activation='tanh', dropout=0.2, name = 'LSTM_2',return_sequences=True),
                          keras.layers.LSTM(units=100, activation='tanh', dropout=0.2, name = 'LSTM_3', return_sequences=False),
                          # tf.keras.layers.LSTM(4),
                          #tf.keras.layers.Flatten(name = 'Flatten'),
                          tf.keras.layers.Dense(units=4, activation='sigmoid', name = 'Dense_1')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

model.summary()

model.fit(tf_X_train, y, epochs=20, batch_size=2)
`

Where y is the one hot encoded on 4 classes of my corresponding sequences, and 18286 the result of my tf_Xtrain.bounding_shape()[1]

What would be a good reproducible solution ?

Thanks in advance

**Comment by GlaIZier** [comment]
As @vitaly-d mentioned you have problems with your data.  You need to preprocess it properly.
LSTM expects data with [batch, time_step, features] shape. Your shape is [batch_size, 1, time_steps]. 
Embedding expects data in [batch, time_step] (taking into account that your feature length is 1 like for strings/words) and makes it [batch, time_step, feature/embedded vector], which is fully compatible with LSTM. Furthermore, my guess is that Embedding layer doesn't support negative numbers, which can be found in your sequences

So, 
without Embedding you input should be smth like: [[[128], [157], [189], [226]], [[123], [232]]]. It might not work though as I mentioned in my previous post, thus padding to the same length might be necessary.
with Embedding: [[128, 157, 189], [123, 232]] without negative numbers

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
