### ISSUE TITLE
Failed to convert QAT model to tflite when I use tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8

### ISSUE THREAD

**Issue by eliver8801** [tensorflow/tensorflow#47235]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installation (pip package or built from source):pip package
- TensorFlow library (version, if pip package or github SHA, if built from source):2.3.1

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
When I use tf.lite.TFLiteConverter to convert keras ACTIVATIONS_INT16_WEIGHTS_INT8 QAT model to tflite file。There are some bugs and the conversion is failed.
This is my convert code and Bugs.
**quant_converter1 = tf.lite.TFLiteConverter.from_keras_model(model1_quant)
quant_converter1.optimizations = [tf.lite.Optimize.DEFAULT]
quant_converter1.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
quant_tflite_model1 = quant_converter1.convert()
with open(model1_tflite_quant, 'wb') as f:
  f.write(quant_tflite_model1)**

![as](https://user-images.githubusercontent.com/12438262/108315281-17f5c700-71b3-11eb-9ec9-f0e0d1114f9f.png)
**I updated the TensorFlow to the latest stable version v2.4.1 and also  face the same error**  @amahendrakar

**Comment by amahendrakar** [comment]
@eliver8801,
In order to reproduce the issue reported here, could you please provide a minimal code snippet and all the files required to run the code.

Also, please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error?

**Comment by eliver8801** [comment]
**I updated the TensorFlow to the latest stable version v2.4.1 and also face the same error** @amahendrakar

**Comment by amahendrakar** [comment]
@eliver8801,
Could you please provide a minimal code snippet along with all the supporting files, so that we can reproduce the issue on our end. Thanks!
