### ISSUE TITLE
Using TensorArray for storing large dataset of interactions

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#47230]
**Reading from TensorArray:**
 
```python
def __init__(self, size):
        self.obs_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.obs2_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.act_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.rew_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.done_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)

 def get_sample(self, batch_size):
            idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
            tf.print(idxs)
            return self.obs_buf.gather(indices=idxs),     \     # HERE IS THE ISSUE
                   self.act_buf.gather(indices=idxs),     \
                   self.rew_buf.gather(indices=idxs),     \
                   self.obs2_buf.gather(indices=idxs),    \
                   self.done_buf.gather(indices=idxs)
```

**Usage:**

```python
@tf.function
def train(self, rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(1, gradient_steps + 1):
        obs, act, rew, next_obs, done = rpm.get_sample(batch_size)

        with tf.GradientTape() as tape:
            ...
```
**Issue:**

> Traceback (most recent call last):
>   File ".\main.py", line 130, in <module>
>     rl_training.train()
>   File "C:\Users\user\Documents\Projects\rl-toolkit\rl_training.py", line 129, in train
>     self._rpm, self.batch_size, self.gradient_steps, logging_wandb=self.logging_wandb
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
>     result = self._call(*args, **kwds)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 871, in _call
>     self._initialize(args, kwds, add_initializers_to=initializers)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 726, in _initialize
>     *args, **kwds))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
>     graph_function, _ = self._maybe_define_function(args, kwargs)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 3206, in _create_graph_function
>     capture_by_value=self._capture_by_value),
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 3887, in bound_method_wrapper
>     return wrapped_fn(*args, **kwargs)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:
> 
>     C:\Users\user\Documents\Projects\rl-toolkit\policy\sac\sac.py:183 update  *
>         obs, act, rew, next_obs, done = rpm.get_sample(batch_size)
>     C:\Users\user\Documents\Projects\rl-toolkit\utils\replay_buffer.py:39 __call__  *
>         return self.obs_buf.gather(indices=idxs),                    self.act_buf.gather(indices=idxs),                    self.rew_buf.gather(indices=idxs),                    self.obs2_buf.gather(indices=idxs),                   self.done_buf.gather(indices=idxs)
>     C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py:1190 gather  **
>         return self._implementation.gather(indices, name=name)
>     C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py:861 gather
>         return array_ops.stack([self._maybe_zero(i) for i in indices])
>     C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py:505 __iter__
>         self._disallow_iteration()
>     C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py:498 _disallow_iteration
>         self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
>     C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py:476 _disallow_when_autograph_enabled
>         " indicate you are trying to use an unsupported feature.".format(task))
> 
>     OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

Why I cannot using TensorArray in this context? And what alternatives I have?

TF version: 2.4.1
Python version:  3.6.8

**Comment by amahendrakar** [comment]
@markub3327,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by markub3327** [comment]
```python
import tensorflow as tf
import numpy as np

class ReplayBuffer(tf.Module):
    def __init__(self, size, name="replay_buffer"):
        super(ReplayBuffer, self).__init__(name=name)

        self.obs_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.obs2_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.act_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.rew_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.done_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False)
        self.ptr, self.size, self.max_size = 0, 0, size

    def store(self, obs, act, rew, next_obs, done):
        self.obs_buf = self.obs_buf.write(self.ptr, obs)
        self.obs2_buf = self.obs2_buf.write(self.ptr, next_obs)
        self.act_buf = self.act_buf.write(self.ptr, act)
        self.rew_buf = self.rew_buf.write(self.ptr, rew)
        self.done_buf = self.done_buf.write(self.ptr, done)
        self.ptr = (self.ptr + 1) % self.max_size
        self.size = min(self.size + 1, self.max_size)

    def __len__(self):
        return self.size

    # Get batch
    def __call__(self, batch_size):
        idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
        tf.print(idxs)
        return self.obs_buf.gather(indices=idxs),     \
               self.act_buf.gather(indices=idxs),     \
               self.rew_buf.gather(indices=idxs),     \
               self.obs2_buf.gather(indices=idxs),    \
               self.done_buf.gather(indices=idxs)

rpm = ReplayBuffer(size=10)  

# store 
for i in range(10):
    rpm.store(np.array([0, 1, 2, 3, 4, 5]), np.array([0, 1, 2, 3, 4, 5]), np.array([0, 1, 2, 3, 4, 5]), np.array([0, 1, 2, 3, 4, 5]), np.array([0, 1, 2, 3, 4, 5]))


@tf.function
def train(rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(1, gradient_steps + 1):
        obs, act, rew, next_obs, done = rpm(batch_size)
      
       # HERE I RUN tf.GradientTape BUT IT IS NOT IMPORTANT FOR NOW ....
     
train(rpm, 64, 100)
```

Here is the reproduciable code. Thanks.

**Comment by amahendrakar** [comment]
@markub3327,
I was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/92fbae9d2dd5af0f67b8ec853d627537/47230.ipynb#scrollTo=0lQejRoawvGo).

Could you please take a look at [this guide](https://www.tensorflow.org/guide/function#loops) for using loops with tf.function and check if it helps. Thanks!

**Comment by markub3327** [comment]
```python
import tensorflow as tf
import numpy as np
tf.__version__


class ReplayBuffer(tf.Module):
    def __init__(self, size, name="replay_buffer"):
        super(ReplayBuffer, self).__init__(name=name)

        self.obs_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.obs2_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.act_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.rew_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.done_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.ptr, self.size, self.max_size = 0, 0, size

    def store(self, obs, act, rew, next_obs, done):
        self.obs_buf = self.obs_buf.write(self.ptr, obs)
        self.obs2_buf = self.obs2_buf.write(self.ptr, next_obs)
        self.act_buf = self.act_buf.write(self.ptr, act)
        self.rew_buf = self.rew_buf.write(self.ptr, rew)
        self.done_buf = self.done_buf.write(self.ptr, done)
        self.ptr = (self.ptr + 1) % self.max_size
        self.size = min(self.size + 1, self.max_size)

    def __len__(self):
        return self.size

    # Get batch
    def __call__(self, batch_size):
        idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
        tf.print(idxs)

        obs_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        obs2_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        act_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        rew_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        done_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)

        for i in tf.range(batch_size):
            obs_batch = obs_batch.write(i, self.obs_buf.stack()[i])
            obs2_batch = obs2_batch.write(i, self.obs2_buf.stack()[i])
            act_batch = act_batch.write(i, self.act_buf.stack()[i])
            rew_batch = rew_batch.write(i, self.rew_buf.stack()[i])
            done_batch = done_batch.write(i, self.done_buf.stack()[i])
 
        return obs_batch, act_batch, rew_batch, obs2_batch, done_batch


rpm = ReplayBuffer(size=1000000)  

# store 1M of experiences from the game
for i in range(10):
    rpm.store(
        tf.random.uniform([28]),
        tf.random.uniform([4]),
        tf.random.uniform([1]),
        tf.random.uniform([28]),
        tf.random.uniform([1])
    )


@tf.function
def train(rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(gradient_steps):
        obs, act, rew, next_obs, done = rpm(batch_size)
      
       # HERE I RUN tf.GradientTape BUT IT IS NOT IMPORTANT FOR NOW ....

train(rpm, 8, 10)
```

Is this a naive solution for a large memory that will contains about 1M experiences from the game? I try it with `.read(index)`, but I get an error too:

> <ipython-input-1-6c7dad339eed>:66 train  *
>     obs, act, rew, next_obs, done = rpm(batch_size)
>     <ipython-input-7-fb7b628dd210>:41 __call__  *
>     obs_batch = obs_batch.write(i, self.obs_buf.read(i))
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/tensor_array_ops.py:1141 read  **
>    return self._implementation.read(index, name=name)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/tensor_array_ops.py:755 read
>         if index < 0:
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:885 __bool__
>         self._disallow_bool_casting()
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:489 _disallow_bool_casting
>         "using a `tf.Tensor` as a Python `bool`")
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:476 _disallow_when_autograph_enabled
>         " indicate you are trying to use an unsupported feature.".format(task))
> 
>OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

**Should I figure it out with using the tf.Dataset?**

**Comment by amahendrakar** [comment]
@rmothukuru,
Colab session crashes on running the code with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/11780cdea6435d5c0b2bb2569e5d9356/47230.ipynb). Thanks!

**Comment by markub3327** [comment]
The issue here is a lot of data that I would store in ReplayBuffer. When you try it with 
```python
rpm = ReplayBuffer(size=1000)  
```
instead of 
```python
rpm = ReplayBuffer(size=1000000)  
```
it runs correctly. But I need to store a lot of data (min. 1000000 interactions). Thanks

**Comment by rmothukuru** [comment]
@markub3327,
Some points from my side:

1. As @amahendrakar mentioned, Session is crashing when trying to reproduce your issue in Google Colab
2. As per [your comment](https://github.com/tensorflow/tensorflow/issues/47230#issuecomment-792772133), I've replaced `size=1000000` with `size=1000` but couldn't observe the Error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/bbe262ada06cb610ee6dae4a6eacc718/47230.ipynb).
3. The documentation of [write function](https://www.tensorflow.org/api_docs/python/tf/TensorArray#write) states 
> Note: The output of this function should be used. If it is not, a warning will be logged or an error may be raised. To mark the output as used, call its `.mark_used()` method.

Can you please add `mark_used` and see if the issue still persists? Thanks!

**Comment by markub3327** [comment]
I try paste `.mark_used()` after every write function ...

Here is code:
```python
import tensorflow as tf
import numpy as np
print(tf.__version__)


class ReplayBuffer(tf.Module):
    def __init__(self, size, name="replay_buffer"):
        super(ReplayBuffer, self).__init__(name=name)

        self.obs_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.obs2_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.act_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.rew_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.done_buf = tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
        self.ptr, self.size, self.max_size = 0, 0, size

    def store(self, obs, act, rew, next_obs, done):
        self.obs_buf = self.obs_buf.write(self.ptr, obs)
        self.obs2_buf = self.obs2_buf.write(self.ptr, next_obs)
        self.act_buf = self.act_buf.write(self.ptr, act)
        self.rew_buf = self.rew_buf.write(self.ptr, rew)
        self.done_buf = self.done_buf.write(self.ptr, done)

        self.obs_buf.mark_used()
        self.obs2_buf.mark_used()
        self.act_buf.mark_used()
        self.rew_buf.mark_used()
        self.done_buf.mark_used()

        self.ptr = (self.ptr + 1) % self.max_size
        self.size = min(self.size + 1, self.max_size)

    def __len__(self):
        return self.size

    # Get batch
    def __call__(self, batch_size):
        idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
        tf.print(idxs)

        obs_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        obs2_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        act_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        rew_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)
        done_batch = tf.TensorArray(tf.float32, size=batch_size, clear_after_read=False, dynamic_size=False)

        for i in idxs:
            obs_batch = obs_batch.write(i, self.obs_buf.stack()[i])
            obs2_batch = obs2_batch.write(i, self.obs2_buf.stack()[i])
            act_batch = act_batch.write(i, self.act_buf.stack()[i])
            rew_batch = rew_batch.write(i, self.rew_buf.stack()[i])
            done_batch = done_batch.write(i, self.done_buf.stack()[i])
 
            #obs_batch.mark_used()
            #obs2_batch.mark_used()
            #act_batch.mark_used()
            #rew_batch.mark_used()
            #done_batch.mark_used()

        return obs_batch, act_batch, rew_batch, obs2_batch, done_batch


rpm = ReplayBuffer(size=1000000)

# store 1M of experiences from the game
for i in range(10):
    rpm.store(
        tf.random.uniform([28]),
        tf.random.uniform([4]),
        tf.random.uniform([1]),
        tf.random.uniform([28]),
        tf.random.uniform([1])
    )


@tf.function
def train(rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(gradient_steps):
        obs, act, rew, next_obs, done = rpm(batch_size)
      
       # HERE I RUN tf.GradientTape BUT IT IS NOT IMPORTANT FOR NOW ....      
       # Q = rew + (1-done) * nextQ

train(rpm, 8, 10)
```

Still, it's not working with size=1000000, but it's necessary. I think that this is not a good solution. Can `tf.Dataset` dynamically expanding until the size of the dataset will be equal to maximal size like 1000000 or can I sampling uniformly a part of it (mini-batch like 32) that can be used in tf.GradientTape during updating parameters of DNN? Thanks.

**Comment by nikitamaia** [comment]
Hi @markub3327, if I understand correctly from this thread, you're only seeing that `OperatorNotAllowedInGraphError` when `rpm = ReplayBuffer(size=1000000)` but there does not seem to be an issue if the size is smaller (say 10)?

Is that correct?

**Comment by markub3327** [comment]
Yes, when I created too large `tf.TensorArray` for storing interactions of my agent, it's crashed. I do the same thing with NumPy arrays and it's working.

With Numpy:
```python
np.zeros((size,) + obs_dim, dtype=np.float32)
```

With TF:
```python
tf.TensorArray(tf.float32, size=size, clear_after_read=False, dynamic_size=False)
```

Exist an effective way of implementing this? [Tensorflow Replay Buffers](https://www.tensorflow.org/agents/tutorials/5_replay_buffers_tutorial) is no the solution for me. Thanks.

**Comment by rohan100jain** [comment]
TensorArrays are a bit problematic here (its a known issue) [Details: We have 2 kinds of TensorArrays - eager mode and graph mode; capture eager mode tensor arrays in graph/tf.function mode isn't well supported and thats why you run into problems doing a .read() on self.obs_buf etc.]

I'd recommend the approach you're gravitating towards in your last update i.e. using Tensors instead. The only nuance here is that Tensorflow Tensors are immutable and so you can't manipulate them like numpy arrays. As a result you need to use scatter/gather ops instead.

```python
class ReplayBuffer:
    """
    A simple FIFO experience replay buffer for DDPG agents.
    Based on https://github.com/openai/spinningup/blob/master/spinup/algos/pytorch/ddpg/ddpg.py.
    """

    def __init__(self, obs_dim, act_dim, size):
        self.obs_buf = tf.zeros((size,) + obs_dim, dtype=tf.float32)
        self.obs2_buf = tf.zeros((size,) + obs_dim, dtype=tf.float32)
        self.act_buf = tf.zeros((size,) + act_dim, dtype=tf.float32)
        self.rew_buf = tf.zeros((size, 1), dtype=tf.float32)
        self.done_buf = tf.zeros((size, 1), dtype=tf.float32)
        self.ptr, self.size, self.max_size = 0, 0, size

    def store(self, obs, act, rew, next_obs, done):
        self.obs_buf = tf.tensor_scatter_nd_update(self.obs_buf, [[self.ptr]], [obs])
        self.obs2_buf = tf.tensor_scatter_nd_update(self.obs2_buf, [[self.ptr]], [next_obs])
        self.act_buf = tf.tensor_scatter_nd_update(self.act_buf, [[self.ptr]], [act])
        self.rew_buf = tf.tensor_scatter_nd_update(self.rew_buf, [[self.ptr]], [rew])
        self.done_buf = tf.tensor_scatter_nd_update(self.done_buf, [[self.ptr]], [done])
        self.ptr = (self.ptr + 1) % self.max_size
        self.size = min(self.size + 1, self.max_size)

    def __len__(self):
        return self.size

    def sample(self, batch_size):
        idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
        tf.print(idxs)

        return dict(
            obs=tf.gather(self.obs_buf, idxs),
            obs2=tf.gather(self.obs2_buf, idxs),
            act=tf.gather(self.act_buf, idxs),
            rew=tf.gather(self.rew_buf, idxs),
            done=tf.gather(self.done_buf, idxs),
        )

rpm = ReplayBuffer((28,), (4,), int(1e6))

# store 1M of experiences from the game
for i in range(10000):
    rpm.store(
        tf.random.uniform([28]),
        tf.random.uniform([4]),
        tf.random.uniform([1]),
        tf.random.uniform([28]),
        tf.random.uniform([1])
    )


@tf.function
def train(rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(gradient_steps):
        obs, act, rew, next_obs, done = rpm.sample(batch_size)

       # HERE I RUN tf.GradientTape BUT IT IS NOT IMPORTANT FOR NOW ....

train(rpm, 8, 10)
```

I've verified that this works. Please let me know what you think!

**Comment by markub3327** [comment]
Yeah, It looks well, but I tested it in Colab and the run cell takes about 11 min 14 s.

With fewer elements than 10000 was the run shorter.

**Comment by rohan100jain** [comment]
The program that I provided in the last comment - I ran that on colab and it took around 35 seconds (I was using a GPU runtime). I tried with CPU runtime and that was really slow (didn't even get to finish).

Another option is to use tf.Variable here - the biggest slowdown is because of the tf.tensor_scatter_nd_update since that allocates and creates a new tensor each time. With tf.Variable, we just re-use the same underlying buffer and the CPU runtime comes down to 15 seconds.

```python
import tensorflow as tf
import time

class ReplayBuffer:
    """
    A simple FIFO experience replay buffer for DDPG agents.
    Based on https://github.com/openai/spinningup/blob/master/spinup/algos/pytorch/ddpg/ddpg.py.
    """

    def __init__(self, obs_dim, act_dim, size):
        self.obs_buf = tf.Variable(tf.zeros((size,) + obs_dim, dtype=tf.float32))
        self.obs2_buf = tf.Variable(tf.zeros((size,) + obs_dim, dtype=tf.float32))
        self.act_buf = tf.Variable(tf.zeros((size,) + act_dim, dtype=tf.float32))
        self.rew_buf = tf.Variable(tf.zeros((size, 1), dtype=tf.float32))
        self.done_buf = tf.Variable(tf.zeros((size, 1), dtype=tf.float32))
        self.ptr, self.size, self.max_size = 0, 0, size

    def store(self, obs, act, rew, next_obs, done):
        self.obs_buf.scatter_nd_update([[self.ptr]], [obs])
        self.obs2_buf.scatter_nd_update([[self.ptr]], [next_obs])
        self.act_buf.scatter_nd_update([[self.ptr]], [act])
        self.rew_buf.scatter_nd_update([[self.ptr]], [rew])
        self.done_buf.scatter_nd_update([[self.ptr]], [done])
        self.ptr = (self.ptr + 1) % self.max_size
        self.size = min(self.size + 1, self.max_size)

    def __len__(self):
        return self.size

    def sample(self, batch_size):
        idxs = tf.random.uniform(shape=[batch_size], maxval=self.size, dtype=tf.int32)
        # tf.print(idxs)

        return dict(
            obs=tf.gather(self.obs_buf, idxs),
            obs2=tf.gather(self.obs2_buf, idxs),
            act=tf.gather(self.act_buf, idxs),
            rew=tf.gather(self.rew_buf, idxs),
            done=tf.gather(self.done_buf, idxs),
        )

rpm = ReplayBuffer((28,), (4,), int(1e6))

@tf.function
def train(rpm, batch_size, gradient_steps):
    for gradient_step in tf.range(gradient_steps):
        obs, act, rew, next_obs, done = rpm.sample(batch_size)

       # HERE I RUN tf.GradientTape BUT IT IS NOT IMPORTANT FOR NOW ....

start_time = time.time()
# store 1M of experiences from the game
for i in range(10000):
    rpm.store(
        tf.random.uniform([28]),
        tf.random.uniform([4]),
        tf.random.uniform([1]),
        tf.random.uniform([28]),
        tf.random.uniform([1])
    )



train(rpm, 8, 10)
end_time = time.time()

print(end_time - start_time)
```

**Comment by markub3327** [comment]
Thanks @rohan100jain ! It's a solution for me. I test it on CPU with time ~15 s, on GPU ~35 s and Numpy version has 10 s.
