### ISSUE TITLE
How to convert a csv file to TFrecord tensorFlow format?

### ISSUE THREAD

**Issue by EdwinGerman** [tensorflow/tensorflow#4723]
Hello everybody i need to convert a csv file to TFrecord for TensorFlow. I really appreciate your help.
An example of csv file that  i need to convert is:
Col1 Col2 Col3 Col4 Target
2.56 0.98 0.45  7.8    0.189
3.10 5.78  4.78 9.0    0.78
....
Thank you very much!!!

**Comment by concretevitamin** [comment]
This is suitable for StackOverflow.
