### ISSUE TITLE
How do I profile layers in tensorflow instead of ops? Is there a way to profile only layers in tensorflow?

### ISSUE THREAD

**Issue by saisriker** [tensorflow/tensorflow#47236]

**Comment by ravikyram** [comment]
@saisriker 
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ymodak** [comment]
Take a look at TensorFlow Profiler https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras
