### ISSUE TITLE
It's not worth the effort. Use PyTorch instead.

### ISSUE THREAD

**Issue by IanSMoyes** [tensorflow/tensorflow#47232]
I spent 11 hours trying to install tensorflow on 2 machines. My Starlite 2 Ubuntu laptop & my 8Gb Raspberry Pi 4.

I have RARELY been treated with such disrespect and contempt as I have been by tensorflow's support team. I have rarely interacted with people who seem so bitter and disillusioned as this team. I have come to the opinion the Google assign people to this team as a punishment. No other theory fits my World model.

Eventually, I gave up and install PyTorch instead (in less than 30 minutes & no problems).

GOOGLE, the wealthiest Corporation in history can't support the installation of their software on the 3 main operating systems NEARLY as well as Zuckerberg. WOW!!!!

**Comment by lvenugopalan** [comment]
Please read [code of conduct ](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md) before posting any queries and be respectful as advised in the earlier issues authored by you. The issue tracker is for Tensorflow feature requests or bug reports. Please refrain from posting inappropriate comments. If any functionality or feature does not work to your satisfaction, please let us know, as each feedback is valuable to us. Tensorflow team will be happy to address them. Again, we can only help if you restrict your posts to product issues and not personal rants.
