### ISSUE TITLE
add tflite_micro with cmake files and zephyr modules

### ISSUE THREAD

**Issue by hakehuang** [tensorflow/tensorflow#47241]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (Linux Ubuntu 16.04):
- TensorFlow installed from (source):
- Tensorflow version (e85120faff5febebc6ac527b8cf977333a8dd6f4):
- Target platform (Arm Mbed OS):

**Describe the problem**

tflite only have makefile support, so add cmake support will make tf easy to be integarted.

**Please provide the exact sequence of commands/steps when you ran into the problem**
I use Zephyr RTOS as example, 
https://github.com/hakehuang/zephyr/commits/tf_int

cd samples/hello_world/
west build -b mimxrt1060_evk

**Comment by hakehuang** [comment]
PR is created
#47240

**Comment by advaitjain** [comment]
https://github.com/tensorflow/tensorflow/pull/47240#issuecomment-791160760 describes why will not be able to add cmake support at this time, and also gives some direction for how you might be able to integrate TFLM as part of a larger project.

**Comment by hakehuang** [comment]
> [#47240 (comment)](https://github.com/tensorflow/tensorflow/pull/47240#issuecomment-791160760) describes why will not be able to add cmake support at this time, and also gives some direction for how you might be able to integrate TFLM as part of a larger project.
@advaitjain 
it is strange why TFLM does not want to have CMAKE support, as I see in the TFLite there is ready CMAKE solution, can you explain the reason?

**Comment by advaitjain** [comment]
@hakehuang, very valid question.

We do see a lot of potential benefits to having cmake support. However, (at this time) we do not want to support more than two separate build systems simultaneously. So any additional build system support would have to be accompanied by a solid plan and justification to remove one of the existing ones (Make and Bazel).

For the time-being, we would like to make it easier to perform such integrations without needing to merge code in upstream Tensorflow.

We would also welcome further discussion on this topic at the [SIG-micro mailing list](https://groups.google.com/a/tensorflow.org/g/micro).

Somewhat separate from the topic of cmake or not, we would also like to have any Zephyr or any other framework/IDE/OS integration to be outside of the TFLM repository.
