### ISSUE TITLE
ValueError: Expected `model` argument to be a functional `Model` instance, but got a subclass model instead.

### ISSUE THREAD

**Issue by emadboctorx** [tensorflow/tensorflow#47248]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Maybe, unless there's some way to achieve the same thing already

**Describe the feature and the current behavior/state.**

I need to copy a keras model and there is no way that I know of which can be done unless the model **is not** a `tf.keras.models.Model()` subclass. 

**Note:** The use `copy.deepcopy()` will work without giving any errors however it will result in another error whenever the copy is used:

Results in:

    /usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:569 _run_internal_graph  **
        assert x_id in tensor_dict, 'Could not compute output ' + str(x)
    
    AssertionError: Could not compute output KerasTensor(type_spec=TensorSpec(shape=(None,), dtype=tf.int64, name=None), name='tf.math.argmax/ArgMax:0', description="created by layer 'tf.math.argmax'")

Example:

    import tensorflow as tf
    
    class MyModel(tf.keras.Model):
    
      def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
        self.dropout = tf.keras.layers.Dropout(0.5)
    
      def call(self, inputs, training=False):
        x = self.dense1(inputs)
        if training:
          x = self.dropout(x, training=training)
        return self.dense2(x)
    
    
    if __name__ == '__main__':
        model1 = MyModel()
        model2 = tf.keras.models.clone_model(model1)

Results in:

    Traceback (most recent call last):
      File "/Users/emadboctor/Library/Application Support/JetBrains/PyCharm2020.3/scratches/scratch.py", line 600, in <module>
        model2 = tf.keras.models.clone_model(model1)
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 430, in clone_model
        return _clone_functional_model(
      File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 171, in _clone_functional_model
        raise ValueError('Expected `model` argument '
    ValueError: Expected `model` argument to be a functional `Model` instance, but got a subclass model instead.

**Will this change the current api? How?** I don't know

**Who will benefit with this feature?** Whoever wants to create n copies of a custom model without writing n lines for achieving the same thing.

**Any Other info.**

**Comment by amahendrakar** [comment]
@emadboctorx,
Looks like this is a duplicate of [#47048](https://github.com/tensorflow/tensorflow/issues/47048).

Can we close this issue since it is already being tracked there. Thanks!

**Comment by emadboctorx** [comment]
@amahendrakar sure, thanks

**Comment by Suesoso** [comment]
Is this issue addressed? I meet the same problem

**Comment by emadboctorx** [comment]
@Suesoso Looks like it was brought up previously in other issues but still I don't see solutions anywhere

**Comment by gcunhase** [comment]
Any updates on this? Having the same issue on TF2.5.0.
