### ISSUE TITLE
[Grappler] Optimise branches with constant predicates. 

### ISSUE THREAD

**Issue by bhatuzdaname** [tensorflow/tensorflow#47256]
I am using tf 1.15. When I try to optimize a graph using grappler and get an optimized graph_def, I see that branches on constant predicates are not folded. Is this something that is not supported?

**Comment by Saduf2019** [comment]
@bhatuzdaname 
Yes there is no support for 1.x as well now, please upgrade to 2.x and let us know in case you face any issues.

**Comment by bhatuzdaname** [comment]
Hi, I tried it with 2.4 and face the same issue.

**Comment by jvishnuvardhan** [comment]
@bhatuzdaname Can you please share a simple standalone code (with `TF2.x`) to reproduce the issue? Thanks!
