### ISSUE TITLE
tflite building is taking hours

### ISSUE THREAD

**Issue by justeph** [tensorflow/tensorflow#47259]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): yocto
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.4 
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.7
- GCC/Compiler version (if compiling from source): 10.2
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am trying to compile tensorflow-lite and benchmark_model from source using yocto. I already managed to do it using a yocto recipe based on the Makefile. But the Makefile support is limited, so I need to compile tensorflow-lite and benchmark_model using bazel. But bazel build takes several hours!  

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I started from http://git.yoctoproject.org/cgit/cgit.cgi/meta-tensorflow/ and slightly modified http://git.yoctoproject.org/cgit/cgit.cgi/meta-tensorflow/tree/recipes-framework/tensorflow/tensorflow_2.4.0.bb to compile tensorflow-lite instead of tensorflow. Basically I just modified the do_compile so now it is:
```
do_compile () {
    export CT_NAME=$(echo ${HOST_PREFIX} | rev | cut -c 2- | rev)
    unset CC
    ${BAZEL} build \
        --jobs=40 \
        ${TF_ARGS_EXTRA} \
        -c opt \
        --cpu=${BAZEL_TARGET_CPU} \
        --crosstool_top=@local_config_yocto_compiler//:toolchain \
        --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
        --copt -DTF_LITE_DISABLE_X86_NEON --copt -DCL_DELEGATE_NO_GL \
        //tensorflow/lite:libtensorflowlite.so \
        //tensorflow/lite/tools/benchmark:benchmark_model \
        //tensorflow/tools/pip_package:build_pip_package \
        ${TF_TARGET_EXTRA}
}
```
I also updated the do_install function with the correct path (tensorflow --> tensorflow-lite)

And the recipe works. I was able to install `benchmark_model` on the target and run it. 
The issue here is that, the build takes literally 3 hours to complete while with the Makefile it tooks only few minutes. 
I am building on a very powerfull machine with 40 cores and 189G of RAM. When using `htop` to monitor cpu load, I see only a few processes although I added `--jobs=40` on the bazel build command. 

Am I missing something here? 
Thank you for your help

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Did you also try using [instructions on TF Lite](https://www.tensorflow.org/lite/guide/build_arm64) webpage?
https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

**Comment by terryheo** [comment]
The following lines are used to build TF not TFLite. You can remove them.
```
        //tensorflow/tools/pip_package:build_pip_package \
        ${TF_TARGET_EXTRA}
```

**Comment by justeph** [comment]
thank you @terryheo  this is much faster!!
