### ISSUE TITLE
tutorials_example_trainer failed to build

### ISSUE THREAD

**Issue by lonny1992** [tensorflow/tensorflow#4725]
when I build the tensorflow with the command:
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
error happens :
./tensorflow/core/framework/allocator.h(154): warning: missing return statement at end of non-void function "tensorflow::Allocator::RequestedSize"

./tensorflow/core/framework/allocator.h(154): warning: missing return statement at end of non-void function "tensorflow::Allocator::RequestedSize"

gcc: error trying to exec 'as': execvp: No such file or directory
ERROR: /home/lonny/tensorflow/tensorflow/core/kernels/BUILD:1673:1: output 'tensorflow/core/kernels/_objs/batch_space_ops_gpu/tensorflow/core/kernels/spacetobatch_functor_gpu.cu.o' was not created.
ERROR: /home/lonny/tensorflow/tensorflow/core/kernels/BUILD:1673:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1092.740s, Critical Path: 902.88s

Operating System:Ubuntu 16.04

Installed version of CUDA and cuDNN: 
CUDA toolkit 8.0rc

how can I solve the error?

**Comment by concretevitamin** [comment]
@lonny1992: we don't yet officially support CUDA 8.0, I think.  Can you try to compile with 7.5?

**Comment by aselle** [comment]
It looks like you don't have a working assembler. Can you compile a simple C program successfully? i.e.
```c
cat > test.c <<EOF 
int main(){return 0;}
EOF
gcc test.c
./a.out
```

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.
