### ISSUE TITLE
HDF5 locking issues when using concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by asokraju** [tensorflow/tensorflow#47275]
I was working in TensorFlow and concurrent futures on **Windows 10** using anaconda.  Below is the MWE:

    import tensorflow as tf
    from tensorflow import keras
    
    import numpy as np
    import concurrent.futures 
    import time

    def simple_model():
        model = keras.models.Sequential([
            keras.layers.Dense(units = 10, input_shape = [1]),
            keras.layers.Dense(units = 1, activation = 'sigmoid')
        ])
        model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
        return model
    
    def clone_model(model):
        model_clone = tf.keras.models.clone_model(model)
        model_clone.set_weights(model.get_weights())
        return model_clone
    
    def work(model_path, seq):
        # model = clone_model(model)# model_list[model_id]
        # print(model)
        # import tensorflow as tf
        model = tf.keras.models.load_model(model_path)
        return model.predict(seq)
    
    def workers(model, num_of_seq = 4):
        seqences = np.arange(0,num_of_seq*10).reshape(num_of_seq, -1)
        model_savepath = './simple_model.h5'
        model.save(model_savepath)
        path_list = [model_savepath for _ in range(num_of_seq)]
    
        with concurrent.futures.ProcessPoolExecutor(max_workers=None) as executor:        
            t0 = time.perf_counter()
            # model_list = [clone_model(model) for _ in range(num_of_seq)]
            index_list = np.arange(1, num_of_seq)
            # [clone_model(model) for _ in range(num_of_seq)]
            # print(model_list)
            future_to_samples = {executor.submit(work, path, seq): seq for path, seq in zip(path_list,seqences)}
        Seq_out = []
        for future in concurrent.futures.as_completed(future_to_samples):
            out = future.result()
            Seq_out.append(out)
        t1 = time.perf_counter()
        print(t1-t0)
        return np.reshape(Seq_out, (-1, )), t1-t0
    
    
    
    if __name__ == '__main__':
        model = simple_model()
        num_of_seq = 400
        # model_list = [clone_model(model) for _ in range(4)]
        out = workers(model, num_of_seq=num_of_seq)
        print(out)

returns:

    2021-02-19 16:31:13.665341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]
    15.456169300000003
    (array([1., 1., 1., ..., 1., 1., 1.], dtype=float32), 15.456169300000003)

When I try to run the script in Ubuntu it keeps running with no output and until I force quit the process. And some time it gives the following error:

    OSError: Unable to open file (unable to lock file, errno = 37, error message = 'No locks available')

What I have tried:

 1. I used `conda tf-gpu export > environment.yml` to get all the installed files to a different Windows 10 and saw the same behavior.
2. Made a new environment in Windows 10 (where the code is working) with various different TensorFlow versions. All TF-2.x versions worked out.
3. Tried the same code on Docker by pulling TensorFlow images. Same issues
4. The issue is with locking the HDF5 file, so tried: https://stackoverflow.com/questions/57310333/can-we-disable-h5py-file-locking-for-python-file-like-object. It did not work

Similar issues have been reported in:

 - https://stackoverflow.com/questions/49438814/opening-already-opened-hdf5-file-in-write-mode-using-h5py
 -  https://github.com/h5py/h5py/issues/1066
 -  https://github.com/h5py/h5py/issues/1101
 -  https://github.com/keras-team/keras/issues/11796
 - https://github.com/keras-team/keras/issues/11101

**Comment by Saduf2019** [comment]
@asokraju 
I ran the code shared on tf 2.4 and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e714682cd4a968a2df453d30c950cbb3/untitled546.ipynb)

**Comment by asokraju** [comment]
For some reason MpI codes ldoesnot eork on collab please try on a local
computer

**Comment by asokraju** [comment]
Above MWE, the aim is to predict the output of a saved model in parallel. 

WORKER: 
1. Saves the model to the disk and saves the path in `model_savepath `
2. It then calls four workers by sending the model path and the `work `function (data that needs to be predicted).
3. Each one then clones a model from the path (using `clone_model`) and then uses it to predict.

PS: 
1. It might not work in COLAB. So try running it on a local computer.
2. You can not parse the model directly in `future_to_samples `. For more information see #46917.
3. The issue might be from read and write permissions of HDF5 file format resulting from:
     - `model.save(model_savepath)`
     - `tf.keras.models.clone_model(model_savepath)`
     - also `tf.keras.models.load_model(model_savepath)`

**Comment by ymodak** [comment]
Have you tried saving your model to `tf` format? Does that work?

**Comment by asokraju** [comment]
As per your suggestion, I modified the code as follows:
```
import tensorflow as tf
from tensorflow import keras

import numpy as np
import concurrent.futures 
import time
import os
# gpus = tf.config.experimental.list_physical_devices('GPU')
# if len(gpus) > 0:
#     print(f'GPUs {gpus}')
#     try: tf.config.experimental.set_memory_growth(gpus[0], True)
#     except RuntimeError: pass
def simple_model():
    model = keras.models.Sequential([
        keras.layers.Dense(units = 10, input_shape = [1]),
        keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])
    model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model

def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    return model_clone

def work(model_path, seq):
    t0 = time.perf_counter()
    model = tf.keras.models.load_model(model_path)
    # model = tf.saved_model.load(model_path)
    t1 = time.perf_counter()
    print("Time taken to load the model", t1-t0)
    return model.predict(seq)

def workers(model, num_of_seq = 4):
    seqences = np.arange(0,num_of_seq*10).reshape(num_of_seq, -1)
    # model_savepath = './testing/simple_model.h5'
    model_savepath = './testing'
    try:
        os.mkdir(model_savepath)
    except:
        pass
    model.save(model_savepath)
    path_list = [model_savepath for _ in range(num_of_seq)]

    with concurrent.futures.ProcessPoolExecutor(max_workers=None) as executor:        
        t0 = time.perf_counter()
        # model_list = [clone_model(model) for _ in range(num_of_seq)]
        index_list = np.arange(1, num_of_seq)
        # [clone_model(model) for _ in range(num_of_seq)]
        # print(model_list)
        future_to_samples = {executor.submit(work, path, seq): seq for path, seq in zip(path_list,seqences)}
    Seq_out = []
    for future in concurrent.futures.as_completed(future_to_samples):
        out = future.result()
        Seq_out.append(out)
    t1 = time.perf_counter()
    print(t1-t0)
    return np.reshape(Seq_out, (-1, )), t1-t0



if __name__ == '__main__':
    model = simple_model()
    num_of_seq = 400
    # model_list = [clone_model(model) for _ in range(4)]
    out = workers(model, num_of_seq=num_of_seq)
    print(out)
```

And the output is 

```
......
Time taken to load the model 1.0405409000000034
57.1098902
(array([1., 1., 1., ..., 1., 1., 1.], dtype=float32), 57.1098902)
```
This still has the same issue. 
PS: The above out is generated on my windows computer, and the time taken to load the model in the earlier method is quite fast, (~0.05) compared to 1 second. I also noted that as the model complexity increases, the time increases ( a model with 4 hidden layers of 200 parmas each and a custom cost function took around 25 seconds to load).

**Comment by asokraju** [comment]
Hey, are you waiting for my comments?

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210527 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9cbb3f165d0f628edd9adafa1f0999d6/untitled31.ipynb#scrollTo=sCzU_uAv_oox)..Thanks !

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
