### ISSUE TITLE
Export tensorflow-lite target in CMake build

### ISSUE THREAD

**Issue by KarlKulator** [tensorflow/tensorflow#47271]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently it is only possible to integrate the tensorflow-lite CMake build as a source build into an external project.
See [https://www.tensorflow.org/lite/guide/build_cmake](https://www.tensorflow.org/lite/guide/build_cmake): "Create a CMake project which uses TensorFlow Lite".
Additionally the compiled libtensorflow-lite.a does not include all dependencies (ruy, absl):
See _"Note: This generates a static library libtensorflow-lite.a in the current directory but the library isn't self-contained since all the transitive dependencies are not included."_. This makes it hard to manually import the prebuilt libary into new projects.

The suggestion would be to export the tensorflow-lite target using CMakes importing and exporting feature ([https://cmake.org/cmake/help/git-stage/guide/importing-exporting/index.html](https://cmake.org/cmake/help/git-stage/guide/importing-exporting/index.html)). All dependencies, like ruy and absl, should be either bundled into the tensorflow-lite library or also be exported.

**Will this change the current api? How?**
This will add the possibility to import the tensorflow-lite CMake build into a separate external project using find_package() and without an additional source build. No modification, only an addition.

**Who will benefit with this feature?**
- Users of the Tensorflow Lite C/C++ API
- Teams can build tensorflow-lite once and distribute the library in a package to all members
- Allows to deliver a prebuilt tensorflow-lite and be easily integrated into projects

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by terryheo** [comment]
One question, do you prefer to use it as shared library or static library?

**Comment by KarlKulator** [comment]
Using BUILD_SHARED_LIBS as an option so the user can decide would of course be ideal.

Otherwise I would default to a static lib like in the make build.

**Comment by terryheo** [comment]
Using C++ requires lots of header files, so you'd better use C API for now.
https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library

And I'll check the feasibility of providing C++ library later.

**Comment by KarlKulator** [comment]
The C Library also does not use CMake Exporting and Importing features as far as I can see.

**Comment by KarlKulator** [comment]
@terryheo Can I use the libtensorflowlite_c.so without the ruy and absl libraries? 

For the Cpp interface it says "This generates a static library libtensorflow-lite.a in the current directory but the library isn't self-contained since all the transitive dependencies are not included. "

I guess this is also the case for the C API?

**Comment by KarlKulator** [comment]
@terryheo Hi, is there any news on improving the export of the C++ tensorflow-lite target in CMake?

**Comment by mcmchammer** [comment]
Would love to see this happen as well!

**Comment by terryheo** [comment]
> @terryheo Can I use the libtensorflowlite_c.so without the ruy and absl libraries?
> 
> For the Cpp interface it says "This generates a static library libtensorflow-lite.a in the current directory but the library isn't self-contained since all the transitive dependencies are not included. "
> 
> I guess this is also the case for the C API?

No. The generated libtensorflowlite_c.so is self-contained so you don't need any additional libraries. So please use C API if you're not using CMake or Bazel.

**Comment by pkgoogle** [comment]
Hi @KarlKulator, are you still having trouble integrating the libtensorflowlite_c.so file in your project? What current issue are you running into?
