### ISSUE TITLE
"classes" not working on flow_from_dataframe

### ISSUE THREAD

**Issue by andy6804tw** [tensorflow/tensorflow#47281]
The classes parameter works on flow_from_directory but not flow_from_dataframe in TF 2.4.

```py
train_generator = train_datagen.flow_from_dataframe(dataframe=df,
                                                    x_col="img_path",
                                                    y_col="class",
                                                    classes=["rika", "risa","yui", "akane","neru"],
                                                    target_size=(200, 200),
                                                    batch_size=32,
                                                    class_mode='categorical', shuffle=False)
```

![](https://i.imgur.com/TyrbHcW.png)

The `train_generator.class_indices` output are not correspond my  classes lists.

Please correct me if I am wrong. Thanks!

**Comment by ymodak** [comment]
The classes correspond to the directory names in alphabetical order. Therefore you see that order.

**Comment by andy6804tw** [comment]
@ymodak Thanks for your reply. I know it will alphabetical order by default. Is there any way to specify the order?

**Comment by amahendrakar** [comment]
@andy6804tw,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by andy6804tw** [comment]
@amahendrakar  Sure! 
I take the `cnn-who-is-she` dataset for [example](https://www.kaggle.com/scott1205/cnn-who-is-she) from Kaggel.  
Here is my kernel I shared. https://www.kaggle.com/andy6804tw/47281-issue.

Thank you!

**Comment by amahendrakar** [comment]
@rmothukuru,
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3954ada50bc6bfd98ffbc4257688a84c/47281.ipynb). Thanks!

**Comment by ymodak** [comment]
This was fixed earlier in `keras-team/keras` with https://github.com/keras-team/keras/issues/13637.

**Comment by ymodak** [comment]
I will update this thread when the fix is in hopefully by end of this week. Thanks!

**Comment by YawWashout** [comment]
@ymodak was wondering if you happened to implement this fix? or a workaround? Was just scratching my head for a few hours not realizing it was ignoring the `classes` variable I was specifying.

Thanks!

**Comment by sachinprasadhs** [comment]
It is working as per the alphabetical order of classes and the mapping of classes is working as expected, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/fee73604a73e58247cf244fb43fb8ae1/47281.ipynb). Thanks!

**Comment by andy6804tw** [comment]
Hi! @sachinprasadhs It's great hearing from you. After my test, I still found the problem.
please find the gist [here](https://colab.research.google.com/drive/1Fay5Pmzi1DgBz3gK8PEH5UNt1ExEXESf). Thanks!

**Comment by sachinprasadhs** [comment]
It is ordering the classes based on alphabetical order, however if you still think it is not the way it is supposed to work please post this issue on keras-team/keras repo.
Development of keras moved to separate repository https://github.com/keras-team/keras/issues

To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by andy6804tw** [comment]
@sachinprasadhs Thank you very much! I'll open new issue on keras-team/keras repo.

**Comment by sachinprasadhs** [comment]
@andy6804tw, I already see the issue has been moved to keras repo by us, please track the issue here https://github.com/keras-team/keras/issues/15206
