### ISSUE TITLE
The Example Code in tf.feature_column.numeric_column is not Executable/Complete/Self-Sufficient

### ISSUE THREAD

**Issue by worldpeaceaspirer** [tensorflow/tensorflow#47286]
Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column#example

Description of issue (what needs changing):
The example code cannot be Executed as it is. We have to add the namespaces by searching in the **`tensorflow.org`** site.

Complete/Self-Sufficient/Stand-Alone example code will be very helpful, especially for the New Developers.

**Comment by PratsBhatt** [comment]
I have created a pull request. Suggestions inputs are welcome @worldpeaceaspirer  and @rmothukuru . Thank you.

**Comment by ymodak** [comment]
Thanks for the PR. This is now fixed with tf-nightly docs.
https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column?version=nightly#example
