### ISSUE TITLE
tf-mlir-translate can not handle the value of tf.const node with float_value

### ISSUE THREAD

**Issue by MoFHeKa** [tensorflow/tensorflow#47280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): libtensorflow_framework.so.2.5.0
- Python version: Python 3.7.0
- Bazel version (if compiling from source): bazel-3.7.2-linux-x86_64
- GCC/Compiler version (if compiling from source):  10.1.0
- CUDA/cuDNN version: 11.0
- GPU model and memory: TITAN V 12066MiB

**Describe the current behavior**
***Build command***
In $LLVM_SRC_DIR:
`git reset --hard 2bfe27da171e8a6dddac6c444c4bca003103941a`
Then:
`bazel build --distdir=$build_dir --override_repository=llvm-project=$LLVM_SRC_DIR   -c opt tensorflow/compiler/mlir:tf-mlir-translate`
***Run command***
`./tf-mlir-translate --graphdef-to-mlir ~/tem_new_graph_def.graphdef -o ~/model.mlir`
or
`./tf-mlir-translate --savedmodel-signaturedefs-to-mlir ~/model.savedmodel/ -o ~/model.mlir`

When the mlir translator meet a float_val tensor, It just generated some messy hex. For example:
**raw graphdef:**
`node {
  name: "model/addf0/BiasAdd/ReadVariableOp"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 256
          }
        }
        float_val: 0.0051481337286531925
        float_val: -0.004853762686252594
        float_val: -0.0063857887871563435
        float_val: -0.005939189810305834
        float_val: -0.007605542428791523
        float_val: -0.014029058627784252
        float_val: 6.364182627294213e-05
        float_val: 0.0026220008730888367
        float_val: -0.006861857604235411
        float_val: 0.011504308320581913
        float_val: 0.00323308352380991
        float_val: 0.004311520606279373
        float_val: -0.00712333619594574
        float_val: 0.0016613556072115898
        float_val: -0.001945714931935072
        float_val: -5.2431416406761855e-05
        float_val: -0.0072508323937654495
        float_val: 0.007718958426266909
        float_val: -0.005794827360659838
        float_val: -0.00043485683272592723
        float_val: -0.011029565706849098
        float_val: 0.00399430375546217
        float_val: 0.009735933504998684
        float_val: -0.005351892672479153
        float_val: 0.0004388465313240886
        float_val: 0.006414614152163267
        float_val: -0.0023052822798490524
        float_val: 0.0028045496437698603
        float_val: 0.0013200563844293356
        float_val: -0.008794997818768024
        float_val: -0.0009779843967407942
        float_val: -0.010262236930429935
        float_val: 0.0024026455357670784
        float_val: 0.008377766236662865
        float_val: 0.0016489957924932241
        float_val: 0.008051405660808086
        float_val: -0.0026613050140440464
        float_val: 0.000884789798874408
        float_val: -0.00757144670933485
        float_val: -0.00411588978022337
        float_val: -0.006682147271931171
        float_val: -0.0025500720366835594
        float_val: 0.003163927234709263
        float_val: -0.0024716767948120832
        float_val: -0.011840238235890865
        float_val: 0.002221206435933709
        float_val: 0.010188544169068336
        float_val: -0.0005134445964358747
        float_val: 0.014506646431982517
        float_val: 0.008010786958038807
        float_val: 0.00045173970283940434
        float_val: -0.006965363398194313
        float_val: -0.0003679479705169797
        float_val: -0.008194392547011375
        float_val: -0.01170737948268652
        float_val: -0.0030496888794004917
        float_val: -0.005231104791164398
        float_val: -0.006195568945258856
        float_val: -0.010564603842794895
        float_val: -0.007049794774502516
        float_val: -0.0033882728312164545
        float_val: -0.0076379235833883286
        float_val: -0.0052634309977293015
        float_val: 0.0020512063056230545
        float_val: -0.010911918245255947
        float_val: -0.0014321575872600079
        float_val: -0.004976712167263031
        float_val: -0.005636582151055336
        float_val: 0.0057461741380393505
        float_val: -0.0050669782795012
        float_val: -0.005440800916403532
        float_val: 0.016398049890995026
        float_val: 0.005827216897159815
        float_val: -0.0025648120790719986
        float_val: -0.00967519823461771
        float_val: -0.004590281751006842
        float_val: 0.0002168136416003108
        float_val: -0.009099945425987244
        float_val: -0.007822085171937943
        float_val: -0.004594044294208288
        float_val: -0.00698000006377697
        float_val: 0.002748528029769659
        float_val: -0.006815034430474043
        float_val: 0.008094011805951595
        float_val: -0.005640577524900436
        float_val: -0.005020929034799337
        float_val: -0.009470895864069462
        float_val: -0.002705982653424144
        float_val: 0.004372714087367058
        float_val: -0.002115572802722454
        float_val: -0.008014006540179253
        float_val: -0.00045102433068677783
        float_val: 0.005882886704057455
        float_val: -0.0012644800590351224
        float_val: 0.005815275013446808
        float_val: -0.009082064032554626
        float_val: -0.004126546438783407
        float_val: 0.015735354274511337
        float_val: -0.00870969332754612
        float_val: -0.011116635985672474
        float_val: -0.0030493661761283875
        float_val: -0.003578674979507923
        float_val: 0.006664385553449392
        float_val: 0.005230343900620937
        float_val: -0.00039703131187707186
        float_val: -0.0038723910693079233
        float_val: -0.0011821255320683122
        float_val: 0.006628826260566711
        float_val: -0.0008820746443234384
        float_val: -0.01215388160198927
        float_val: -0.005438085645437241
        float_val: -0.0014401013031601906
        float_val: -0.0031687782611697912
        float_val: 0.004439719021320343
        float_val: -0.0010851756669580936
        float_val: 0.00455262279137969
        float_val: 0.01028736773878336
        float_val: -0.01316842157393694
        float_val: -0.007040669210255146
        float_val: 0.005985334049910307
        float_val: 0.001018555136397481
        float_val: -0.006859580520540476
        float_val: -0.0012270506704226136
        float_val: 0.00039293334702961147
        float_val: 0.00015758314111735672
        float_val: -0.007701294496655464
        float_val: -0.005402510054409504
        float_val: 0.0027941293083131313
        float_val: -0.00476961862295866
        float_val: 0.013895658776164055
        float_val: 0.0048489863984286785
        float_val: -0.01240287534892559
        float_val: 0.00227100751362741
        float_val: 0.0004433704598341137
        float_val: -0.00233777379617095
        float_val: -0.004992697387933731
        float_val: 0.0029940051026642323
        float_val: -0.0024685945827513933
        float_val: -0.004253252409398556
        float_val: -0.010474653914570808
        float_val: 0.016132526099681854
        float_val: 0.007510742638260126
        float_val: 0.011006304062902927
        float_val: 0.020926298573613167
        float_val: -0.0018459537532180548
        float_val: -0.00524304062128067
        float_val: -0.006811123341321945
        float_val: -0.004207645542919636
        float_val: -0.0026161535643041134
        float_val: -0.00533562945201993
        float_val: -0.003053524997085333
        float_val: 0.012821650132536888
        float_val: -0.00304988631978631
        float_val: -0.004115841817110777
        float_val: -0.0026411768049001694
        float_val: 0.004588124807924032
        float_val: -0.006611636374145746
        float_val: -0.007796596735715866
        float_val: -0.0005695070140063763
        float_val: -0.005537876393646002
        float_val: -0.0021315556950867176
        float_val: 0.00860658660531044
        float_val: 0.008062107488512993
        float_val: -0.007444465532898903
        float_val: 0.0004948594723828137
        float_val: 0.013905920088291168
        float_val: 0.01084441039711237
        float_val: -0.006462818011641502
        float_val: -0.007946974597871304
        float_val: -0.00013547498383559287
        float_val: 0.0029342391062527895
        float_val: 0.0032939868979156017
        float_val: -0.006928297225385904
        float_val: 0.004277899395674467
        float_val: -0.004152035806328058
        float_val: 0.0007484358502551913
        float_val: -0.006124483421444893
        float_val: -0.0001521199446870014
        float_val: -0.006839861627668142
        float_val: 0.004457100760191679
        float_val: -0.009015962481498718
        float_val: 0.0029336384031921625
        float_val: 0.0015798307722434402
        float_val: 0.0014634429244324565
        float_val: -0.007801746483892202
        float_val: 0.0010955692268908024
        float_val: -0.007367278914898634
        float_val: -0.00868617556989193
        float_val: -0.00434133131057024
        float_val: -0.002788239624351263
        float_val: -0.004975281655788422
        float_val: -0.004753256682306528
        float_val: -0.0012826395686715841
        float_val: -0.0036673436406999826
        float_val: -0.0059289475902915
        float_val: 0.016369104385375977
        float_val: -0.00635050144046545
        float_val: 0.004774186760187149
        float_val: 0.0037566213868558407
        float_val: -0.008517655543982983
        float_val: -0.004843609873205423
        float_val: -0.007144990377128124
        float_val: 0.016293589025735855
        float_val: -0.007814271375536919
        float_val: 0.011035293340682983
        float_val: -0.007298213895410299
        float_val: -0.009457477368414402
        float_val: 0.004397874232381582
        float_val: 0.017384257167577744
        float_val: 0.007743040099740028
        float_val: -0.00099231640342623
        float_val: -0.005199010483920574
        float_val: 0.003438242245465517
        float_val: 0.008518864400684834
        float_val: 0.0025021492037922144
        float_val: -0.006360295228660107
        float_val: 0.004405853804200888
        float_val: 0.0017105545848608017
        float_val: 0.001984659116715193
        float_val: -0.006431774701923132
        float_val: -0.006175287999212742
        float_val: -0.007920660078525543
        float_val: 0.010450722649693489
        float_val: -0.005794399883598089
        float_val: -0.007095997221767902
        float_val: -0.005131132435053587
        float_val: 0.001255601178854704
        float_val: -0.003194880671799183
        float_val: -0.008282691240310669
        float_val: 0.02166000008583069
        float_val: 0.007440856657922268
        float_val: -0.0023202376905828714
        float_val: 0.012448390014469624
        float_val: 0.0006656379555352032
        float_val: -0.0024139166343957186
        float_val: -0.003526628715917468
        float_val: -0.0010204833233729005
        float_val: -0.007021935656666756
        float_val: 0.010514422319829464
        float_val: 0.005775094032287598
        float_val: -0.010260146111249924
        float_val: 0.004442145116627216
        float_val: 0.002659732010215521
        float_val: -0.0016509274719282985
        float_val: -0.001772205694578588
        float_val: 0.0015684027457609773
        float_val: 0.001310656196437776
        float_val: 0.0006843036971986294
        float_val: -0.00796379055827856
        float_val: -0.0076110996305942535
        float_val: 0.0022425760980695486
        float_val: -0.0026748101226985455
        float_val: 0.004271205514669418
        float_val: -0.0023577818647027016
        float_val: -0.010191367007791996
        float_val: -0.00014487635053228587
      }
    }
  }
}`

**TF milr generated by tf-mlir-translate:**
`%outputs_408, %control_409 = tf_executor.island wraps "tf.Const"() {device = "", value = dense<"0xADB1A83B500C9FBBE13FD1BB899DC2BBEA37F9BB23DA65BC72778538E0D52B3B6FD9E0BB917C3C3C24E2533BA8478D3BE06AE9BBD8C1D93A5C07FFBACEE95BB86498EDBB51EFFC3B89E2BDBB7FFDE3B95AB534BCA6E2823B77831F3CEE5EAFBBFC14E639AF31D23B381417BB89CC373BBE05AD3AE51810BCB62F80BAF12228BCB4751D3BE642093C1E23D83A0BEA033C4A692EBB3DF1673AE619F8BB96DE86BBEAF5DABB1C1F27BBE4594F3BDBFB21BB8FFD41BCA991113BDAED263CAF9806BA49AD6D3CAD3F033C7AD7EC39B43DE4BB24E9C0B9C64106BC4FD03FBC4ADD47BBB069ABBB3304CBBB29172DBCF701E7BBC90D5EBB8C47FABBDC78ACBB886D063BE7C732BC3CB7BBBAB013A3BB14B3B8BB674ABC3BE508A6BBBF48B2BB3455863C3DF2BE3B681628BBB9841EBC136A96BB78586339F01715BC342800BCA38996BB7CB8E4BBA620343BA750DFBBBF9C043C98D4B8BB9B86A4BBD12B1BBCDB5631BBFC488F3B6CA50ABB2E4D03BC7677ECB93BC5C03BE9BCA5BA108EBE3BF0CC14BCFB3787BB6EE7803C1AB30EBC8D2236BCE0D747BB34886ABBEB60DA3B4E63AB3BA428D0B9F1C77DBB8DF19ABAA036D93B073B67BA132147BCF831B2BBC8C1BCBA47AB4FBB107B913B743C8EBA2B2E953B598C283C5DC057BC6AB5E6BB9F20C43B0A81853A55C6E0BBFDD4A0BA9F02CE39E73C2539245BFCBB8A07B1BBB61D373B764A9CBB9EAA633C3FE49E3B6E354BBC2FD5143B2D74E839563519BBC899A3BB1237443B25C821BBDE5E8BBBE29D2BBC5C28843CAD1CF63BC953343CA16DAB3CEEF3F1BAD0CDABBBD82FDFBB4AE089BBC6732BBB81D6AEBBA61D48BBE611523C9AE047BB2FDE86BB98172DBBFB57963B6DA6D8BB987AFFBBF84A15BA1377B5BB92B10BBBA4020D3CEE16043CB4F0F3BB75B9013AA8D5633CC1AC313C0CC6D3BB073402BC4A0E0EB95D4C403BEEDF573BC506E3BB9F2D8C3BCD0D88BBAE32443AE4AFC8BB63821FB9EB20E0BBDF0C923BB0B713BC4942403B5312CF3AFFD0BF3ACBA5FFBB34998F3A3769F1BB76500EBCBA418EBBE6BA36BBB007A3BB35C19BBB3E1EA8BAD15770BB9E47C2BB8018863CDE17D0BBC8709C3BA631763BA38D0BBC25B79EBB8620EABB227A853C6E0700BC60CD343CDB25EFBB89F31ABC0B1C903B6E698E3C54B9FD3B9D1082BA765CAABB2254613BB5920B3C19FB233B066AD0BBFB5E903BB034E03A0E11023BA3C1D2BB125ACABBA8C501BC82392B3CF3DEBDBB8A85E8BB0F23A8BBFC92A43A346151BB20B407BC5070B13C6ED2F33B210F18BB55F44B3C357E2E3ACD321EBB031F67BBBDC185BA4418E6BBAF442C3C003DBD3B2C1A28BC6A8F913BE64E2E3BEF63D8BA5B49E8BADD92CD3A53CAAB3AD862333A8F7A02BC8866F9BB2FF8123BDE4B2FBB78F58B3B04851ABBB1F926BCF3E917B9"> : tensor<256xf32>} : () -> tensor<256xf32>`

**when change all float_val to one, the result shown like this:**
` %outputs_408, %control_409 = tf_executor.island wraps "tf.Const"() {device = "", value = dense<1.000000e+00> :tensor<256xf32>} : () -> tensor<256xf32>`

**Describe the expected behavior**
It should be outputted like this:
`%outputs_408, %control_409 = tf_executor.island wraps "tf.Const"() {device = "", value = dense<"0.0051481337286531925,-0.004853762686252594,……,-0.00014487635053228587"> : tensor<256xf32>} : () -> tensor<256xf32>`

**Comment by Saduf2019** [comment]
@MoFHeKa 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by MoFHeKa** [comment]
> @MoFHeKa
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Sorry about that. I have re-edit my issue.

**Comment by MoFHeKa** [comment]
well, I didn't notice that this is tensor_content binary.
