### ISSUE TITLE
whether tensorflow2.0 suppert bert pretraining?

### ISSUE THREAD

**Issue by ZYG151541155** [tensorflow/tensorflow#47282]
Question: Where tensorflow2.0 suppert bert pretraining?
    Version:  tensorflow2.4
   Base on my data, I want to train new pretrain-model with bert. However, When I run run_pretraining.py file, ad error occurred.

Traceback (most recent call last):
  File "run_pretraining.py", line 493, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/python3/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/python3/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/python3/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 429, in main
    is_per_host = tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2
AttributeError: module 'tensorflow' has no attribute 'contrib'_**

So, I don't know how to deal with this problem and whether tensorflow2.0+ support bert pretraining again with my data.
Finally, hope someone can give me answer and I will appreciate you, thanks!

**Comment by ravikyram** [comment]
@ZYG151541155 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
Can you please share complete code snippet to reproduce the issue.

contrib module is no longer available in TensorFlow 2.0, but you can use with this;
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Thanks!

**Comment by ZYG151541155** [comment]
> @ZYG151541155
> 
> Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
> Can you please share complete code snippet to reproduce the issue.
> 
> contrib module is no longer available in TensorFlow 2.0, but you can use with this;
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> 
> Thanks!

Thanks your replied! However, I want to uset bert pre-trained model to train a new pretrain model with my domain data and fine-tuning with my train data! The bugs show like that:   

[@localhost bert]$ python3 run_pretraining.py 
2021-02-20 14:36:40.090529: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/usr/local/python3/lib/python3.8/site-packages/absl/flags/_validators.py:353: UserWarning: Flag --input_file has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/usr/local/python3/lib/python3.8/site-packages/absl/flags/_validators.py:353: UserWarning: Flag --bert_config_file has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/usr/local/python3/lib/python3.8/site-packages/absl/flags/_validators.py:353: UserWarning: Flag --output_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
INFO:tensorflow:*** Input Files ***
I0220 14:36:40.888833 140508959438656 run_pretraining.py:420] *** Input Files ***
INFO:tensorflow:  /mnt/data/bert_2.0/water/outdir_pretrain/tf_examples.tfrecord *
I0220 14:36:40.889002 140508959438656 run_pretraining.py:422]   /mnt/data/bert_2.0/water/outdir_pretrain/tf_examples.tfrecord *
Traceback (most recent call last):
  File "run_pretraining.py", line 493, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/python3/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/python3/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/python3/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_pretraining.py", line 429, in main
    is_per_host = tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by Saduf2019** [comment]
@ZYG151541155 

Please refer to this [issue](https://stackoverflow.com/questions/55870127/module-tensorflow-has-no-attribute-contrib) and let us know if it helps.
