### ISSUE TITLE
Can the GradCAM being integrate to savedModel format?

### ISSUE THREAD

**Issue by luvwinnie** [tensorflow/tensorflow#47292]
**System information**
Colaboratory
Tensorflow 2.4
Tested on below version
v2.4.0-49-g85c8b2a817f 2.4.1
v2.3.0-54-gfcc4b966f1 2.3.1

**Describe the current behavior**
I'm trying to make a savedModel that can generate GradCAM heatmap, however it shows errors that the tape.gradient or tf.gradients is None can't be compute, Does anyone can help with this?

**Describe the expected behavior**
Expected that can save to savedModel .

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
This is the colaboratory notebook.

https://colab.research.google.com/drive/1uX4T_DZWaptZ4pF2akawB5FYYMgRtX7y?authuser=1#scrollTo=QBsBrZ5JEk-N

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@luvwinnie 

Please, grant me the access for the colab link. Thanks!

**Comment by luvwinnie** [comment]
@ravikyram I have added the permission!

**Comment by luvwinnie** [comment]
It seems like i need to do this by disable the eager mode and save with tensorflow V1 savedModel Format.... I think this should be fixed for any model that need to compute the gradient during inference time.
https://colab.research.google.com/drive/1HXAhebh9liIhWjgO3UAqnj_m1CTYOf9W?authuser=1#scrollTo=Osob4efBAPuF

**Comment by luvwinnie** [comment]
Any progress on this?

**Comment by tilakrayal** [comment]
@luvwinnie ,

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.

**Comment by luvwinnie** [comment]
@tilakrayal It is not able to integrate the GradCAM inside the model, Instead I Implement the gradient calculation and GradCAM  with only numpy.
