### ISSUE TITLE
TFLM / example: micro_speech / mbed compile -m DISCO_F746NG -t GCC_ARM collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by marconi1964** [tensorflow/tensorflow#47299]
@tensorflow/micro

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.1
- TensorFlow installed from (source or binary): source
- TensorFlow version: TensorFlow/Lite/Micro
- Python version: Python 2.7.17 and Python3 3.6.9
- Installed using virtualenv? pip? conda?: pip, and no virtualenv, no conda
- GCC/Compiler version (if compiling from source): gcc 7.5.0
- mbed version: 1.10.5
- Target platform: DISCO_F746NG

**Describe the problem**
TensorFlow Lite Micro cross compile for micro speech example at DISCO_F746NG platform. It was 100% completed in compile, but report link error.
I follow the advice from [issue 46721](https://github.com/tensorflow/tensorflow/issues/46721) and modify the tensorflow/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc as the following, see also [link](https://github.com/marconi1964/tensorflow/blob/example/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc)

`# Settings for the Discovery STM32F746NG board.`
`ifeq ($(TARGET),$(filter $(TARGET),mbed))`

`  micro_speech_MBED_PROJECT_FILES += \`
`    AUDIO_DISCO_F746NG.lib \`
`    BSP_DISCO_F746NG.lib \`
`    SDRAM_DISCO_F746NG.lib \`
`    LCD_DISCO_F746NG.lib`
`  MICRO_SPEECH_SRCS += \`
`	tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.cc \`
`	tensorflow/lite/micro/examples/micro_speech/disco_f746ng/command_responder.cc`

`endif`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The procedures are
`$ cd tensorflow`
`$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed generate_micro_speech_mbed_project`
`$ mbed config root .`
`$ mbed deploy`
`$ mbed compile -m DISCO_F746NG -t GCC_ARM`
collect2: error: ld returned 1 exit status

[mbed] ERROR: "/usr/bin/python" returned error.
       Code: 1
       Path: "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed"
       Command: "/usr/bin/python -u /home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/make.py -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output

Below is the complete log of last command with -v flag.

**Any other info / logs**
`ubuntu@ubuntu:~/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed$ /usr/bin/python -u /home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/make.py -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM -v`

[Warning] @,: Compiler version mismatch: Have 7.3.1; expected version >= 9.0.0 and < 10.0.0
Building project mbed (DISCO_F746NG, GCC_ARM)
Scan: mbed
Macros: -DDEVICE_CRC=1 -DTARGET_STM32F746xG -DDEVICE_I2C_ASYNCH=1 -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DDEVICE_PORTOUT=1 -DDEVICE_PORTINOUT=1 -D__MBED_CMSIS_RTOS_CM -DTARGET_DISCO_F746NG -DCOMPONENT_FLASHIAP=1 -DTARGET_STM32F7 -DDEVICE_MPU=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DTARGET_N25Q128A -DTOOLCHAIN_GCC -DDEVICE_CAN=1 -DARM_MATH_CM7 -DTARGET_CORTEX_M -DTARGET_LIKE_CORTEX_M7 -DDEVICE_RTC=1 -DDEVICE_ANALOGOUT=1 -DDEVICE_QSPI=1 -DTARGET_M7 -DCOMPONENT_PSA_SRV_IMPL=1 -DEXTRA_IDLE_STACK_REQUIRED -DDEVICE_LPTICKER=1 -DDEVICE_PWMOUT=1 -DDEVICE_SPI_ASYNCH=1 -DMBED_TICKLESS -DUSE_FULL_LL_DRIVER -DCOMPONENT_QSPIF=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DTRANSACTION_QUEUE_SIZE_SPI=2 -DDEVICE_USBDEVICE=1 -DDEVICE_STDIO_MESSAGES=1 -D__CORTEX_M7 -DTARGET_FAMILY_STM32 -DUSE_HAL_DRIVER -DTARGET_FF_ARDUINO -DHSE_VALUE=25000000 -DTARGET_RELEASE -DTARGET_STM -DTARGET_NAME=DISCO_F746NG -DDEVICE_SERIAL_FC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_USTICKER=1 -DDEVICE_WATCHDOG=1 -DDEVICE_TRNG=1 -DTARGET_LIKE_MBED -DTARGET_RTOS_M4_M7 -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DMBED_BUILD_TIMESTAMP=1613922146.79 -DDEVICE_RESET_REASON=1 -DDEVICE_SPI=1 -DCOMPONENT_NSPE=1 -DDEVICE_INTERRUPTIN=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DSTM32F746xx
Link: mbed
Preproc: arm-none-eabi-cpp -E -P ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_GCC_ARM/STM32F746xG.ld -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -Wl,--wrap,printf -Wl,--wrap,sprintf -Wl,--wrap,snprintf -Wl,--wrap,vprintf -Wl,--wrap,vsprintf -Wl,--wrap,vsnprintf -Wl,--wrap,fprintf -Wl,--wrap,vfprintf -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_BOOT_STACK_SIZE=4096 -DXIP_ENABLE=0 -o ./BUILD/DISCO_F746NG/GCC_ARM/.link_script.ld -DDEVICE_CRC=1 -DTARGET_STM32F746xG -DDEVICE_I2C_ASYNCH=1 -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DDEVICE_PORTOUT=1 -DDEVICE_PORTINOUT=1 -D__MBED_CMSIS_RTOS_CM -DTARGET_DISCO_F746NG -DCOMPONENT_FLASHIAP=1 -DTARGET_STM32F7 -DDEVICE_MPU=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DTARGET_N25Q128A -DTOOLCHAIN_GCC -DDEVICE_CAN=1 -DARM_MATH_CM7 -DTARGET_CORTEX_M -DTARGET_LIKE_CORTEX_M7 -DDEVICE_RTC=1 -DDEVICE_ANALOGOUT=1 -DDEVICE_QSPI=1 -DTARGET_M7 -DCOMPONENT_PSA_SRV_IMPL=1 -DEXTRA_IDLE_STACK_REQUIRED -DDEVICE_LPTICKER=1 -DDEVICE_PWMOUT=1 -DDEVICE_SPI_ASYNCH=1 -DMBED_TICKLESS -DUSE_FULL_LL_DRIVER -DCOMPONENT_QSPIF=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DTRANSACTION_QUEUE_SIZE_SPI=2 -DDEVICE_USBDEVICE=1 -DDEVICE_STDIO_MESSAGES=1 -D__CORTEX_M7 -DTARGET_FAMILY_STM32 -DUSE_HAL_DRIVER -DTARGET_FF_ARDUINO -DHSE_VALUE=25000000 -DTARGET_RELEASE -DTARGET_STM -DTARGET_NAME=DISCO_F746NG -DDEVICE_SERIAL_FC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_USTICKER=1 -DDEVICE_WATCHDOG=1 -DDEVICE_TRNG=1 -DTARGET_LIKE_MBED -DTARGET_RTOS_M4_M7 -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DMBED_BUILD_TIMESTAMP=1613922146.79 -DDEVICE_RESET_REASON=1 -DDEVICE_SPI=1 -DCOMPONENT_NSPE=1 -DDEVICE_INTERRUPTIN=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DSTM32F746xx @./BUILD/DISCO_F746NG/GCC_ARM/.includes_d41d8cd98f00b204e9800998ecf8427e.txt -include ./BUILD/DISCO_F746NG/GCC_ARM/mbed_config.h
[DEBUG] Return: 0
Link: arm-none-eabi-gcc @./BUILD/DISCO_F746NG/GCC_ARM/.link_options.txt
[DEBUG] Return: 1
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.o: In function `GetAudioSamples(tflite::ErrorReporter*, int, int, int*, short**)':
[DEBUG] Errors: /home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.cc:154: multiple definition of `GetAudioSamples(tflite::ErrorReporter*, int, int, int*, short**)'
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/audio_provider.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/audio_provider.cc:28: first defined here
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.o: In function `LatestAudioTimestamp()':
[DEBUG] Errors: /home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.cc:181: multiple definition of `LatestAudioTimestamp()'
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/audio_provider.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/audio_provider.cc:37: first defined here
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/command_responder.o: In function `RespondToCommand(tflite::ErrorReporter*, long, char const*, unsigned char, bool)':
[DEBUG] Errors: /home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/command_responder.cc:26: multiple definition of `RespondToCommand(tflite::ErrorReporter*, long, char const*, unsigned char, bool)'
[DEBUG] Errors: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/command_responder.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/command_responder.cc:23: first defined here
[DEBUG] Errors: collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/make.py", line 78, in wrapped_build_project
    *args, **kwargs
  File "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/build_api.py", line 610, in build_project
    res = toolchain.link_program(resources, build_path, name)
  File "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 778, in link_program
    self.link(elf, objects, libraries, lib_dirs, linker_script)
  File "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/toolchains/gcc.py", line 357, in link
    self.default_cmd(cmd)
  File "/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 830, in default_cmd
    raise ToolException(stderr)
ToolException: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.o: In function `GetAudioSamples(tflite::ErrorReporter*, int, int, int*, short**)':
/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.cc:154: multiple definition of `GetAudioSamples(tflite::ErrorReporter*, int, int, int*, short**)'
BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/audio_provider.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/audio_provider.cc:28: first defined here
BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.o: In function `LatestAudioTimestamp()':
/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/audio_provider.cc:181: multiple definition of `LatestAudioTimestamp()'
BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/audio_provider.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/audio_provider.cc:37: first defined here
BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/command_responder.o: In function `RespondToCommand(tflite::ErrorReporter*, long, char const*, unsigned char, bool)':
/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/disco_f746ng/command_responder.cc:26: multiple definition of `RespondToCommand(tflite::ErrorReporter*, long, char const*, unsigned char, bool)'
BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/examples/micro_speech/command_responder.o:/home/ubuntu/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/micro_speech/mbed/./tensorflow/lite/micro/examples/micro_speech/command_responder.cc:23: first defined here
collect2: error: ld returned 1 exit status

**Comment by marconi1964** [comment]
Issue solved by modifying the line of tensorflow/tensorflow/lite/micro/examples/micro_speech/disco_f746ng/Makefile.inc

from
`ifeq ($(TARGET),$(filter $(TARGET),mbed))`
to
`ifeq ($(TARGET),$(filter $(TARGET),disco_f746ng))`

**Comment by napoleonwar** [comment]
Hi, May I ask what is the code size after compilation? fx the size of .hex (binary file) and .elf (execution file)

**Comment by marconi1964** [comment]
Compile result shows 
Total static RAM memory (data + bss) : 36,408 bytes
Total Flash memory (text + data): 94,736 bytes

The bin file 'mbed.bin' size shows 135,308 bytes, under linux system.

it is not required to build .elf file to run mbed on embedded CPU, so no information available about .elf file size.
