### ISSUE TITLE
Add compatability for h5py 3

### ISSUE THREAD

**Issue by SamTov** [tensorflow/tensorflow#47303]
**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
We are developing some software that relies heavily on both H5Py and TensorFlow and require the latest release of each. In terms of functionality the code will run however if the user installs both separately but the setup.py will throw errors reading conflicts in dependencies.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Those who wish to have a python module that relies on H5Py 3 and TensorFlow

**Any Other info.**

**Comment by mihaimaruseac** [comment]
Can you detail the errors?

**Comment by SamTov** [comment]
Sorry I should have been a little more clear. It isn't an issue with any tensor flow functionality it is simply when I run pip install on my package. In the setup.py I have both h5py>3 and tensorflow>2 and so pip fails to run because these requirements conflict with one another. I have no issues with actual tf operations failing.

**Comment by mihaimaruseac** [comment]
Ok, so this then needs to wait until we are confident that there are no big bugs if we bump our `h5py` dependency.

**Comment by SamTov** [comment]
Okay no problem. Is there anything I can do to help this? Or is there a timeline on that process?

**Comment by mihaimaruseac** [comment]
Let's try sending a PR with the bound updated and see what breaks.

**Comment by SamTov** [comment]
Is there any update on this?

**Comment by wagnerpeer** [comment]
Can this ticket be closed?
Multiple sources indicate, that `tensorflow` is compatible to and built with support for `h5py~=3.1` since December 2020:
* tensorflow/tools/ci_build/release/requirements_common.txt
* tensorflow/tools/pip_package/setup.py ([c0dbdfb7](https://github.com/tensorflow/tensorflow/commit/c0dbdfb718de6481b00d7ff17a0ff763cf7a7544#diff-f526feeafa1000c4773410bdc5417c4022cb2c7b686ae658b629beb541ae9112))

**Comment by SamTov** [comment]
yes it appears to be working.
