### ISSUE TITLE
TopKV2 InvalidArgumentError: k must be scalar

### ISSUE THREAD

**Issue by robinderat** [tensorflow/tensorflow#47306]
Running on Google Colab
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- TensorFlow version: 2.4.1
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1

### Current behaviour

I am trying to use tf.raw_ops.TopKV2 to get the top k values of my output, with k varying per row.

As stated in the documentation k expects "A Tensor of type int32. 0-D.  Number of top elements to look for along the last dimension (along each row for matrices)." 

However, it gives me InvalidArgumentError: k must be scalar, got shape [2] [Op:TopKV2]

### Code

```
import numpy as np
import tensorflow as tf

input = np.array([[0,1,2], [5,4,3]])
k = np.array([1,2])

tf.raw_ops.TopKV2(input=input, k=k)
```
Trace:
```
InvalidArgumentError                      Traceback (most recent call last)

<ipython-input-11-245902c47f71> in <module>()
      5 k = np.array([1,2])
      6 
----> 7 tf.raw_ops.TopKV2(input=input, k=k)

3 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_export.py in wrapper(*args, **kwargs)
    402           'Please pass these args as kwargs instead.'
    403           .format(f=f.__name__, kwargs=f_argspec.args))
--> 404     return f(**kwargs)
    405 
    406   return tf_decorator.make_decorator(f, wrapper, decorator_argspec=f_argspec)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py in top_kv2(input, k, sorted, name)
  11426       return _result
  11427     except _core._NotOkStatusException as e:
> 11428       _ops.raise_from_not_ok_status(e, name)
  11429     except _core._FallbackException:
  11430       pass

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6860   message = e.message + (" name: " + name if name is not None else "")
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access
   6864 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: k must be scalar, got shape [2] [Op:TopKV2]
```
### Expected behaviour

I expect topKV2 to accept a list/array/tensor for the k parameter. Returning value 2, index 2 for the first row and values 5 4, indices 0 1 for the second row.

### Extra

Additionally, the documentation example use of TopKV2 is
```
tf.raw_ops.TopKV2(
    input, k, sorted=True, name=None
)
```

However, providing the input and k arguments directly gives the following error:
top_kv2 only takes keyword args (possible keys: ['input', 'k', 'sorted', 'name']). Please pass these args as kwargs instead.

**Comment by Saduf2019** [comment]
@robinderat 
K is a scalar ex: k=3 but you are using a vector. 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by robinderat** [comment]
@Saduf2019 
I know I am using a vector. That is what I want. Please note I am using TopKV2 not TopK. 
For TopK documentation says:
k: An int that is >= 0. Number of top elements to look for along the last dimension (along each row for matrices). 

For TopKV2 documentation says:
k: A Tensor of type int32. 0-D. Number of top elements to look for along the last dimension (along each row for matrices). 

Therefore, I should be able to use a vector/tensor.

**Comment by ymodak** [comment]
Value of `k` can be 0-D tensor as per the docs. With `k=np.ndim(np.array([1,2]))` we get 1-D tensor.
```python
import numpy as np
np.ndim(2)
==> 0
np.ndim(np.array([1,2]))
==> 1
```
Perhaps we can update docs to state that k expects a scalar tensor (0-D).

**Comment by robinderat** [comment]
Ah yes, of course. My bad.
