### ISSUE TITLE
Need a easy way to let different weights have different LR in Keras.

### ISSUE THREAD

**Issue by HLSS-Hen** [tensorflow/tensorflow#47308]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes, may be

**Describe the feature and the current behavior/state.**
At nowtimes, if I want to train model and use defferent LR for weights, I need to give up `Model.Fit()`.

**Will this change the current api? How?**
Yes, probably:
- Layer.add_weight() may have extra param "Init_LR"
- Weights may add attribute “Init_LR”
- Some others.

**Who will benefit with this feature?**
Anyone who want to use this.
Developer who also use PyTorch.

**Comment by fsx950223** [comment]
It's easy to implement it with custom training loop.

**Comment by HLSS-Hen** [comment]
```
import numpy
from tensorflow import keras
from tensorflow.python.eager import backprop
from tensorflow.python.keras.engine import data_adapter
class DoubleBiasLRModel(keras.Model):
    def __init__(self, *args, **kwargs):
        super(DoubleBiasLRModel, self).__init__(**kwargs)
        self.LR_list=[]
        for weights in self.trainable_variables:
            if "bias" in weights.name or "beta" in weights.name:
                self.LR_list.append(2.)
            else:
                self.LR_list.append(1.)
        self.LR_list=np.array(self.LR_list)

    def train_step(self, data):
        data = data_adapter.expand_1d(data)
        x, y, sample_weight = data_adapter.unpack_x_y_sample_weight(data)
        with backprop.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(y, y_pred, sample_weight, regularization_losses=self.losses)

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars) * self.LR_list
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
        return {m.name: m.result() for m in self.metrics}
```
Then def model with `DoubleBiasLRModel(xxx)` instead of ` keras.Model(xxx)`
I use this code to solve my need. I wish we can have more elegant and simple

**Comment by chenmoneygithub** [comment]
The responses above look good. In Keras we provide basic components and leave room for customization, and the different lr scenario is an example of customization.
