### ISSUE TITLE
Building v2.3.1 from sources with avx512 support on a system without avx512

### ISSUE THREAD

**Issue by smuzaffar** [tensorflow/tensorflow#47307]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version: 2.7.15
- Installed using virtualenv? pip? conda?: build from sources
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: without cuda
- GPU model and memory: without GPU

**Describe the problem**
I am able to build and run TF 2.3.1 using `-msse3`. I am now trying to build it for `-march=skylake-avx512` on a system which is not `skylake-avx512`. As the build system does not support avx512 instruction sets so during the build phase it crashes with error like

```
ERROR: tensorflow-2.3.1/tensorflow/compiler/mlir/tensorflow/BUILD:171:7: Generating code from table: transforms/canonicalize.td //tensorflow
/compiler/mlir/tensorflow:tensorflow_canonicalize_inc_gen__gen_rewriters_genrule failed (Illegal instruction): bash failed: error executing command
```

I think this is because many internal tools e.g.  `bazel-out/k8-opt/bin/tensorflow/compiler/mlir/xla/operator_writer_gen` were build with `-march=skylake-avx512` flags.  I was wondering if there is a way to build these internal mlir tools with `-march=native` only

**Comment by jpienaar** [comment]
For these the tools are built with host compiler options, I'm not sure where/how you are setting the march file. Normally the tools are build with different options than the general bazel run so that this isn't needed. Try passing different arch via --host_copt/--host-cxxopt for the tools

**Comment by smuzaffar** [comment]
@jpienaar , I set the following env before calling bazel
```
export CC_OPT_FLAGS="-march=skylake-avx512"
```
and looks like these options are then passed to all tools. How can I pass --host_copt/--host-cxxopt for individual tools?

**Comment by smuzaffar** [comment]
looks like `--host_*opt` is not properly used for building mlir-tblgen 

```
bazel --batch --output_user_root ../build build -s --verbose_failures --host_copt=-msse3 --host_cxxopt=-msse3 --copt=-march=skylake-avx512 --config=opt --cxxopt=-std=c++17 -j 16 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --distinct_host_configuration=false @llvm-project//mlir:mlir-tblgen
....
...
/build/muz/avx/w/slc7_amd64_gcc900/external/gcc/9.3.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/MlirTableGenMain/mlir-tblgen.d '-frandom-seed=bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/MlirTableGenMain/mlir-tblgen.o' -DLLVM_ENABLE_STATS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DLLVM_BUILD_GLOBAL_ISEL -iquote external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -isystem external/llvm-project/mlir/include -isystem bazel-out/k8-opt/bin/external/llvm-project/mlir/include -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include -isystem external/zlib/include -isystem bazel-out/k8-opt/bin/external/zlib/include -w -DAUTOLOAD_DYNAMIC_KERNELS '-march=skylake-avx512' -Wno-sign-compare '-std=c++14' '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/llvm-project/mlir/tools/mlir-tblgen/mlir-tblgen.cpp -o bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/MlirTableGenMain/mlir-tblgen.o
```

this causes the build to fail due to ` Illegal instruction`
```
/bin/bash: line 1: 16797 Illegal instruction     bazel-out/k8-opt/bin/external/llvm-project/mlir/mlir-tblgen -gen-struct-attr-decls tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_gpu_ops_structs.td -Ibazel-out/k8-opt/bin -I external/llvm-project/mlir/include -I external/org_tensorflow -I bazel-out/k8-opt/bin/external/llvm-project/mlir/include -I bazel-out/k8-opt/bin/external/org_tensorflow -Itensorflow/compiler/mlir/hlo/include -Iexternal/org_tensorflow/tensorflow/compiler/mlir/hlo/include -Ibazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/include -I $(dirname tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_gpu_ops_structs.td) -o bazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/include/mlir-hlo/Dialect/mhlo/IR/lhlo_gpu_ops_structs.h.inc
Target //tensorflow/tools/pip_package:build_pip_package failed to build

```

**Comment by jpienaar** [comment]
That is different: you are building the tool with that option, then you are basically hitting a LLVM bug where avx512 isn't supported, but you are explicitly requesting to build the binary. The host flags come to play where you are building a target that uses mlir-tblgen as a tool (e.g., by way of gentbl rule). Also try passing in option via --cxopt="-march=skylake-avx512 flag to bazel vs environment variable.

**Comment by smuzaffar** [comment]
ah my bad, `--distinct_host_configuration=false ` was the issue, sorry for the noise.
