### ISSUE TITLE
tutorial URL outdated, should probably be "www.tensorflow.org/tutorials/audio/simple_audio"

### ISSUE THREAD

**Issue by OlafEichstaedt** [tensorflow/tensorflow#47305]
The url 
`https://www.tensorflow.org/tutorials/audio_recognition`
in line 21 of `tensorflow/tensorflow/examples/speech_commands/train.py` is outdated and produces an 404 error. 

It should probably be:
`https://www.tensorflow.org/tutorials/audio/simple_audio`

**Comment by amahendrakar** [comment]
@OlafEichstaedt,
Thank you for reporting the issue.

The requested change is being tracked in PR [#47310](https://github.com/tensorflow/tensorflow/pull/47310). The link will be updated once the PR is merged. Thanks!
