### ISSUE TITLE
TPU with bfloat16 does not support tf.image.resize with nearest

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#47319]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.9
- GPU model and memory: TPUv3

![图片](https://user-images.githubusercontent.com/3354448/108751857-b4d2ae80-757d-11eb-8d7f-467085464eca.png)

**Comment by ravikyram** [comment]
@edwardyehuang 

Please, fill issue template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
