### ISSUE TITLE
BUG: gfile.rmtree is raises a NotFound error for ram:// filesystems

### ISSUE THREAD

**Issue by adriangb** [tensorflow/tensorflow#47316]
Tested via tf-nightly on 2020-02-22 (YYYY-MM-DD).

Code to reproduce:

```python
from tensorflow.io import gfile

gfile.mkdir("ram://deletethisdir")
gfile.rmtree("ram://deletethisdir")  # raises a NotFoundError
```

Colab notebook: https://colab.research.google.com/drive/13bWmaJ40aeQKd2pUfNtnfwaaUP1M_IVL?authuser=1#

**Comment by adriangb** [comment]
ccing @mihaimaruseac

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.4 and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/31f6ff9f7152b2cd2ea8321d9e736a30/47316.ipynb#scrollTo=MMP-3L1yxwgF). 

However, I did not face any errors while running the code with [TF v2.3.2](https://colab.research.google.com/gist/amahendrakar/897a5c4b12bdea9fd44233a0792c748f/47316-2-3.ipynb). Please check the linked gist for reference. Thanks!
