### ISSUE TITLE
Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string

### ISSUE THREAD

**Issue by hosford42** [tensorflow/tensorflow#47325]
Opening a new bug per @nikitamaia's suggestion. See discussion in #28007, in which she confirmed the bug. Bug only presents when using GPU, not CPU.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 2.4.1/8
- GPU model and memory: GeForce GTX 1050 Ti computeCapability: 6.1, 3.95GiB

**Describe the current behavior**
Error during function call for compiled function:
`Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string`

**Describe the expected behavior**
Compiled function call should succeed like uncompiled function call.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


def _get_char_flags(char_tensor):
    char = char_tensor.numpy().decode()
    return char.isalpha(), char.isspace()


@tf.function  # <--------------- Runs fine with this line commented out.
def tf_split_text(text):
    tf.assert_rank(text, 0)
    tf.debugging.assert_type(text, tf.string)

    chars = tf.strings.unicode_split(text, input_encoding='UTF-8')
    is_alpha, is_space = tf.map_fn(lambda char: tf.py_function(_get_char_flags, char, Tout=[tf.bool, tf.bool]),
                                   (chars,), dtype=tf.bool, parallel_iterations=True,
                                   fn_output_signature=[tf.bool, tf.bool])

    is_alpha = tf.concat([is_alpha, [False]], axis=0)
    is_space = tf.concat([is_space, [True]], axis=0)

    is_special = ~(is_alpha | is_space)
    is_non_alpha = ~is_alpha
    is_non_space = ~is_space

    was_special = tf.concat([[False], is_special[:-1]], axis=0)
    was_non_alpha = tf.concat([[True], is_non_alpha[:-1]], axis=0)
    was_non_space = tf.concat([[False], is_non_space[:-1]], axis=0)

    any_to_special = is_special
    non_alpha_to_non_space = was_non_alpha & is_non_space
    token_start_flags = any_to_special | non_alpha_to_non_space
    token_start_indices = tf.where(token_start_flags)[:, 0]

    special_to_any = was_special
    non_space_to_non_alpha = was_non_space & is_non_alpha
    token_end_flags = special_to_any | non_space_to_non_alpha
    token_end_indices = tf.where(token_end_flags)[:, 0]

    tf.debugging.assert_equal(tf.size(token_start_indices), tf.size(token_end_indices))

    preceding_space = tf.concat([[False], is_space[:-1]], axis=0)

    tokens = tf.strings.substr(text, token_start_indices, token_end_indices - token_start_indices, unit='UTF8_CHAR')
    has_preceding_space = tf.gather(preceding_space, token_start_indices)

    tf.assert_rank(has_preceding_space, 1)
    tf.assert_rank(tokens, 1)
    tf.assert_equal(tf.reduce_sum(tf.map_fn(tf.strings.length, tokens, fn_output_signature=tf.int32)) +
                    tf.reduce_sum(tf.cast(has_preceding_space, tf.int32)),
                    tf.strings.length(text))
    return has_preceding_space, tokens


text = tf.constant('hi there', tf.string)
preceding_spaces, words = tf_split_text(text)
print(words)
```

**Other info / logs**

Traceback:
```python
Traceback (most recent call last):
  File "/home/hosford42/PycharmProjects/ImageParser/error.py", line 56, in <module>
    preceding_spaces, words = tf_split_text(text)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 894, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
	 [[{{node map_1/TensorArrayUnstack/TensorListFromTensor/_96}}]]
	 [[map_1/while/loop_body_control/_61/_107]]
  (1) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
	 [[{{node map_1/TensorArrayUnstack/TensorListFromTensor/_96}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_tf_split_text_265]

Function call stack:
tf_split_text -> tf_split_text
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/c035c29422e11b84b99577232d3c160a/47325-2-3.ipynb) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/d6c26cc365d808a42006dfaab1f7a673/47325.ipynb). Whereas with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/345b439ec9d5c7971140885ac9e163ba/47325-tf-nightly.ipynb), Colab doesn't detect GPU. 

Please check the linked gist for reference. Thanks!

**Comment by sanjoy** [comment]
This prints `tf.Tensor([b'hi' b'there'], shape=(2,), dtype=string)` on tf-nightly, so I'm assuming this is already fixed.

@hosford42 I'm closing the issue for now, but please reopen if you find that it is not fixed.

**Comment by hosford42** [comment]
@sanjoy, was that when using the GPU? It doesn't occur with CPU. See @amahendrakar's earlier comment:

> Whereas with TF-nightly, Colab doesn't detect GPU.

**Comment by sanjoy** [comment]
> @sanjoy, was that when using the GPU? It doesn't occur with CPU. See @amahendrakar's earlier comment:

This was on my local machine and TF was able to use the GPU.  Can you confirm that you're able to reproduce the problem with tf-nightly?

**Comment by hosford42** [comment]
I can't install tf-nightly right now. I may be able to get back to you on this in a few days, though. Thanks, all, for looking at this.

**Comment by Jasonsey** [comment]
hi @geetachavan1, 

I saw you mark this issue Done in TF2.5.0. 
But I can reproduce it in [TF2.5.0 Colab](https://colab.research.google.com/drive/1p-mEPrW24R7WvcvFa6IZxdA-wqke96RX?usp=sharing).  This issue will be reproduced in TF2.5.0-GPU, But not in TF2.5.0-CPU.
Please Help.

**Comment by MarkDaoust** [comment]
I just tried this in colab with TF2.7 and I do not get the error. I believe this is fixed.
