### ISSUE TITLE
Using GridSearchCV in a regression with Keras:  TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by anoldmaninthesea** [tensorflow/tensorflow#47324]
I'm trying to use GridSearchCV in a regression with a Keras neural network.
The data I'm using is the Boston Housing Price dataset, which was loaded directly from keras `boston_housing.load_data()`. The following is a code snippet of I'm trying to do.

    def build_model():
        model=models.Sequential()
        model.add(layers.Dense(64,activation="relu",
                              input_shape=(train_data_norm.shape[1],)))
        model.add(layers.Dense(64,activation="relu"))
        model.add(layers.Dense(1))
        model.compile(optimizer='rmsprop',loss="mse",metrics=["mae"])
        return model 
    
    from sklearn.model_selection import GridSearchCV
    
    from keras.wrappers.scikit_learn import KerasRegressor
    
    model=KerasRegressor(build_fn=build_model(),epochs=30)
    
    param_grid = {"epochs":list(range(1,51))}
    
    grid_model=GridSearchCV(model,param_grid,cv=4)
    
    grid_model.fit(train_data_norm, train_targets)

And I get the following error message: 

    TypeError Traceback (most recent call last)
    <ipython-input-185-3fa5fc34b6b0> in <module>
          9 grid_model=GridSearchCV(model,param_grid,cv=4)
         10 
    ---> 11 grid_model.fit(train_data_norm, train_targets)
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
         70                           FutureWarning)
         71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
    ---> 72         return f(**kwargs)
         73     return inner_f
         74 
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
        679         n_splits = cv.get_n_splits(X, y, groups)
        680 
    --> 681         base_estimator = clone(self.estimator)
        682 
        683         parallel = Parallel(n_jobs=self.n_jobs, verbose=self.verbose,
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
         70                           FutureWarning)
         71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
    ---> 72         return f(**kwargs)
         73     return inner_f
         74 
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\base.py in clone(estimator, safe)
         85     new_object_params = estimator.get_params(deep=False)
         86     for name, param in new_object_params.items():
    ---> 87         new_object_params[name] = clone(param, safe=False)
         88     new_object = klass(**new_object_params)
         89     params_set = new_object.get_params(deep=False)
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
         70                           FutureWarning)
         71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
    ---> 72         return f(**kwargs)
         73     return inner_f
         74 
    
    ~\anaconda3\envs\PythonCPU\lib\site-packages\sklearn\base.py in clone(estimator, safe)
         69     elif not hasattr(estimator, 'get_params') or isinstance(estimator, type):
         70         if not safe:
    ---> 71             return copy.deepcopy(estimator)
         72         else:
         73             if isinstance(estimator, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_list(x, memo, deepcopy)
        203     append = y.append
        204     for a in x:
    --> 205         append(deepcopy(a, memo))
        206     return y
        207 d[list] = _deepcopy_list
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_list(x, memo, deepcopy)
        203     append = y.append
        204     for a in x:
    --> 205         append(deepcopy(a, memo))
        206     return y
        207 d[list] = _deepcopy_list
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        170                     y = x
        171                 else:
    --> 172                     y = _reconstruct(x, memo, *rv)
        173 
        174     # If is its own copy, don't memoize.
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268     if state is not None:
        269         if deep:
    --> 270             state = deepcopy(state, memo)
        271         if hasattr(y, '__setstate__'):
        272             y.__setstate__(state)
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        144     copier = _deepcopy_dispatch.get(cls)
        145     if copier is not None:
    --> 146         y = copier(x, memo)
        147     else:
        148         if issubclass(cls, type):
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
        228     memo[id(x)] = y
        229     for key, value in x.items():
    --> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
        231     return y
        232 d[dict] = _deepcopy_dict
    
    ~\anaconda3\envs\PythonCPU\lib\copy.py in deepcopy(x, memo, _nil)
        159                     reductor = getattr(x, "__reduce_ex__", None)
        160                     if reductor is not None:
    --> 161                         rv = reductor(4)
        162                     else:
        163                         reductor = getattr(x, "__reduce__", None)
    
    TypeError: cannot pickle '_thread.RLock' object

**Comment by Saduf2019** [comment]
@ anoldmaninthesea 

I ran the code shared but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a29602b436740e214e5416bac43023d6/untitled549.ipynb).
You may also refer to similar issues: #33204, [link](https://github.com/tensorflow/tensorflow/issues/21485), [link1](https://stackoverflow.com/questions/44144584/typeerror-cant-pickle-thread-lock-objects)

**Comment by anoldmaninthesea** [comment]
@Saduf2019  your error comes from not importing keras models and layers.  I solved my problem by removing the `( )` in the `KerasRegressor(build_fn=build_model(),epochs=30)`, by rewriting it into `KerasRegressor(build_fn=build_model,epochs=30)`.
