### ISSUE TITLE
ImportError: cannot import name 'keras_modules_injection'

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#47329]
**System information**
- Have I written custom code and  used `from tensorflow.python.keras.applications import keras_modules_injection` in Tensorflow 2.0, it worked, now I changed to Tensorflow 2.4, and facing error `ImportError: cannot import name 'keras_modules_injection'`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 2.4.1
- Python version: Python 3.6.9
- CUDA/cuDNN version: CUDA 11
- GPU model and memory: Titan XP

Checking TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

`2021-02-22 20:44:00.220774: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
v2.4.0-49-g85c8b2a817f 2.4.1`

**Describe the current behavior**
python test_tf_imports.py 
2021-02-22 20:24:25.627138: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "test_tf_imports.py", line 2, in <module>
    from tensorflow.python.keras.applications import keras_modules_injection
ImportError: cannot import name 'keras_modules_injection'

**Describe the expected behavior**
With the line of code `from tensorflow.python.keras.applications import keras_modules_injection` which was running in TF2.0, should run in TF2.4.x

**Standalone code to reproduce the issue**
from tensorflow.python.keras.applications import keras_modules_injection
from tensorflow.python.util.tf_export import keras_export

@keras_export('keras.applications.resnet50.ResNet50',
              'keras.applications.ResNet50')
@keras_modules_injection
def ResNet50(*args, **kwargs):
  return resnet50.ResNet50(*args, **kwargs)

**Comment by amahendrakar** [comment]
Was able to run the code without any issues with [TF v2.0](https://colab.research.google.com/gist/amahendrakar/6ddd992c27768a534e5826cf4cf4f910/47329-2-0.ipynb) and TF v2.1. 

Whereas with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/fd545805499bcedb3a419e936951e206/47329.ipynb#scrollTo=pBdW4kdaERMT) and above, I'm facing an error stating `ImportError: cannot import name 'keras_modules_injection'`. Please check the linked gist for reference. Thanks!

**Comment by jvishnuvardhan** [comment]
@rrklearn2020 `keras_modules_injection`  is just a `Decorator injecting tf.keras replacements for Keras modules.`. I think `keras_modules_injection` is not required for more recent versions starting from `v2.2`.

Please check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/__init__.py from `master` branch and compare it with `2.0` branch https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/applications/__init__.py

Are you noticing any error without this decorator when used with recent TF versions? Thanks!

Please close the issue if this was resolved for you. Thanks!
