### ISSUE TITLE
tf.nn.depth_to_space with NCHW argument works in TF 2.3 but fails in TF 2.4

### ISSUE THREAD

**Issue by acuskev** [tensorflow/tensorflow#47328]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Intel CPU, Macbook Pro 2019

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
In TF 2.4, the tf.nn.depth_to_space command fails with any data_format parameter of "NCHW". 

```
python test_d2l.py
2021-02-22 15:37:05.145218: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-22 15:37:05.145510: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "test_d2l.py", line 4, in <module>
    tf.nn.depth_to_space(x, block_size=2, data_format="NCHW")
  File "/usr/local/anaconda3/envs/keras2onnx/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/anaconda3/envs/keras2onnx/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 3922, in depth_to_space_v2
    return gen_array_ops.depth_to_space(input, block_size, data_format, name=name)
  File "/usr/local/anaconda3/envs/keras2onnx/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1625, in depth_to_space
    return depth_to_space_eager_fallback(
  File "/usr/local/anaconda3/envs/keras2onnx/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1661, in depth_to_space_eager_fallback
    _result = _execute.execute(b"DepthToSpace", 1, inputs=_inputs_flat,
  File "/usr/local/anaconda3/envs/keras2onnx/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node DepthToSpace}} = DepthToSpace[T=DT_FLOAT, block_size=2, data_format="NCHW"]
All kernels registered for op DepthToSpace:
  device='CPU'; T in [DT_UINT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_UINT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT8]; data_format in ["NHWC"]
  device='CPU'; T in [DT_INT32]; data_format in ["NHWC"]
  device='CPU'; T in [DT_HALF]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BFLOAT16]; data_format in ["NHWC"]
  device='CPU'; T in [DT_FLOAT]; data_format in ["NHWC"]
  device='CPU'; T in [DT_DOUBLE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX64]; data_format in ["NHWC"]
  device='CPU'; T in [DT_COMPLEX128]; data_format in ["NHWC"]
  device='CPU'; T in [DT_BOOL]; data_format in ["NHWC"]
  device='CPU'; T in [DT_STRING]; data_format in ["NHWC"]
  device='CPU'; T in [DT_RESOURCE]; data_format in ["NHWC"]
  device='CPU'; T in [DT_VARIANT]; data_format in ["NHWC"]
 [Op:DepthToSpace]
```

**Describe the expected behavior**
Code block below runs without error in TF 2.3 (compiles cluster with XLA). 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import numpy as np
x =  np.random.rand(3, 4, 6, 8).astype(np.float32)
tf.nn.depth_to_space(x, block_size=2, data_format="NCHW")
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by WindQAQ** [comment]
@acuskev It's because XLA:{CPU_GPU} device is not registered in 2.4.* by default.

As you can see in [here](https://colab.research.google.com/drive/1fnS3PvK_ralzf2jlMG73JMRXDKPApRvt?usp=sharing), with NCHW format, depth to space is running on XLA:CPU. To fix it, you can decorate the function with `tf.function(experimental_compile=True)` in 2.4.* and onwards.

```python
@tf.function(experimental_compile=True)
def func(x):
  return tf.nn.depth_to_space(x, block_size=2, data_format="NCHW")
```

**Comment by acuskev** [comment]
Hi, 

Thanks for the response but we are installing 2.4 through pip and cannot access the TF source code to change the function. Is there any approach to resolve just through changes in the model code?

**Comment by jvishnuvardhan** [comment]
@acuskev You don't need to build TF from source. You can use TF through `pip` and decorate the function as suggested by @WindQAQ .

Based on @WindQAQ suggestion, you code work well with `func` as shown in this [gist](https://colab.research.google.com/gist/jvishnuvardhan/f0b499c954afbeeace1466b32d7e98ca/untitled90.ipynb). Thanks!
