### ISSUE TITLE
How to extend self attention in transformer with local attention

### ISSUE THREAD

**Issue by arwinder24** [tensorflow/tensorflow#47336]
Hello everyone.. I'm trying (Vaswani et al, 2017) for machine translation task. Some of the recent findings ("https://www.aclweb.org/anthology/P19-1295/" and "https://www.aclweb.org/anthology/D19-5622/" ) show that number of heads can extract redundant features as original work by Vaswani et al, 2017 used global attention. These papers suggested to use local attention along with global attention. So, I'm trying to extent Vaswani et al, 2017 with local attention as suggested by "https://www.aclweb.org/anthology/D19-5622/". 
In the paper, suggested global mask as follows:
![global mask](https://user-images.githubusercontent.com/60576100/108811216-df9b2200-75d2-11eb-9ca4-55c3e4a398c2.png)

and local mask as: 
![local mask](https://user-images.githubusercontent.com/60576100/108811141-b67a9180-75d2-11eb-89af-2aed43ace7a1.png)

I have created global and local mask as follows: 
        seq_len = tf.shape(seq)[1]
        global_mask = tf.zeros((tf.shape(seq)[0], tf.shape(seq)[1]))
                
        local_mask = global_mask
        local_mask=tf.Variable(local_mask)
        for i in range(0, tf.shape(seq)[0]):
          for j in range(0,tf.shape(seq)[1]):
            if not (i-w<=j and j<=i+w):
              local_mask[i,j].assign(-1e9) 
        local_mask = tf.convert_to_tensor(local_mask)

       global_mask=global_mask[:,tf.newaxis,tf.newaxis,:]
       local_mask=local_mask[:,tf.newaxis,tf.newaxis,:]

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
