### ISSUE TITLE
Custom objects in tf.keras have conflicting interface

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#47347]
Custom tf.keras layers (tf.2.4.)  use `call` for invocation.  However, custom constraints use `__call__`.  This seems confusing.  Furthermore, if you implement a constraint using `call` instead of `__ call __` no warning or error given. I wonder if its reasonable to expect a Not Implemented error to occur in this case of `__call__` missing.

Ref: 
1. Custom layer documentation: https://keras.io/guides/making_new_layers_and_models_via_subclassing/
2. Custom constraint documentation: https://keras.io/api/layers/constraints/

EDIT 1. Fixed link.
EDIT 2. Added tensorflow version. Updated ticket title to reflect tf.keras.

**Comment by amogh7joshi** [comment]
You might want to update your links, you've provided two of the same links (directing to the constraint documentation) rather than two separate ones. 

The link to the custom layer documentation: https://keras.io/guides/making_new_layers_and_models_via_subclassing/

**Comment by isaacgerg** [comment]
Thanks for the pointing out my error.  I have fixed this.

It seems to me that throwing Not Implemented would be the most appropirate.  I can't imagine a usecase where someone would make a constraint and want the parent class behavior of simply passing the vector through.

**Comment by ravikyram** [comment]
@isaacgerg 

Please, close this thread if your issue was resolved.Thanks!

**Comment by isaacgerg** [comment]
@ravikyram The issue has not been resolved.

**Comment by dz1135508698** [comment]
Hello! Which version of keras does tensorflow-2.4.0 correspond to?

**Comment by amogh7joshi** [comment]
You can see Keras v2.4.0; at the current stage Keras is simply being developed as part of TensorFlow so there's no exact version which it corresponds to.

**Comment by isaacgerg** [comment]
@dz1135508698  This affects tf.keras 2.4.  I have updated the issue so that it is more specific.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210603, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/1af17b567364bcf350c53dfbc6370d12/47347.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Hi, Could you please refer to the updated documentation from the Tensorflow documents on `tf.keras.constraints` [here](https://www.tensorflow.org/api_docs/python/tf/keras/constraints?version=nightly) and for Making new Layers and Models via subclassing [here](https://www.tensorflow.org/guide/keras/custom_layers_and_models) and let us know if you still feel the details are conflicting. Thanks!
