### ISSUE TITLE
Proposal to use newer oneDNN version in the core

### ISSUE THREAD

**Issue by alenik01** [tensorflow/tensorflow#47346]
**System information**
- TensorFlow version (you are using): v2.4.1/r2.4
- Are you willing to contribute it: It depends on TF Community plans

**Describe the feature and the current behavior/state.**
At the moment TensorFlow employs [oneDNN v1.6.4](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/workspace.bzl#L172-L181) for core computationally intensive routines. Meanwhile oneDNN is approaching [to v2.2](https://github.com/oneapi-src/oneDNN/milestones) release. May you please clarify if there are any plans for the upcoming TF releases to move to a newer oneDNN version?

**Will this change the current api? How?**
It should not change the current API, I built TensorFlow with oneDNN master and it worked fine.

**Who will benefit with this feature?**
Newer versions of oneDNN have better support for and performance on AArch64, the main benefits will be for the users running TensorFlow on AArch64-based machines.

**Any Other info.**
This issue is mainly a question to understand TensorFlow Community plans for this topic.

**Comment by alenik01** [comment]
This question may be relevant for @agramesh1

**Comment by nSircombe** [comment]
It looks like the hope is to move to 2.2 with the TensorFlow 2.5 release: https://github.com/oneapi-src/oneDNN/issues/994#issuecomment-785426665
?

**Comment by agramesh1** [comment]
Yes, that is the plan.

**Comment by alenik01** [comment]
@agramesh1, many thanks for clarifying this.
