### ISSUE TITLE
ImportError traceback in VScode

### ISSUE THREAD

**Issue by tarangmehta1195** [tensorflow/tensorflow#47354]
ImportError                               Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     17         try:
---> 18             fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
     19         except ImportError:

C:\Program Files\Python39\lib\imp.py in find_module(name, path)
    295     else:
--> 296         raise ImportError(_ERR_MSG.format(name), name=name)
    297 

ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\__init__.py in <module>
     53     # use `dlopen()` for dynamic loading.
---> 54     from tensorflow.python import pywrap_tensorflow
     55 except ImportError:

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     19         except ImportError:
---> 20             import _pywrap_tensorflow
     21             return _pywrap_tensorflow

ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
c:\Users\tarang mehta\Desktop\introtodeeplearning-master\Deep_lizard\First_ANN.py in 
----> 2 import tensorflow as tf
      3 from tensorflow import keras
      4 from tensorflow.keras.models import Sequential
      5 from tensorflow.keras.layers import Activation, Dense
      6 from tensorflow.keras.optimizers import Adam

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

~\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\__init__.py in <module>
     58 please exit the tensorflow source tree, and relaunch your python interpreter
     59 from there.""" % traceback.format_exc()
---> 60   raise ImportError(msg)
     61 
     62 # Protocol buffers

ImportError: Traceback (most recent call last):
  File "C:\Users\tarang mehta\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Program Files\Python39\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tarang mehta\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\tarang mehta\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\tarang mehta\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
2 cells were canceled due to an error in the previous cell.

**Comment by tarangmehta1195** [comment]
currently i have this version: 
Requirement already satisfied: tensorflow in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (0.12.0)
Requirement already satisfied: numpy>=1.11.0 in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (from tensorflow) (1.20.1)
Requirement already satisfied: six>=1.10.0 in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: protobuf==3.1.0 in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: wheel>=0.26 in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: setuptools in c:\users\tarang mehta\appdata\roaming\python\python39\site-packages (from protobuf==3.1.0->tensorflow) (53.0.0)

**Comment by Saduf2019** [comment]
@tarangmehta1195 

Could you please check if you are using 64-bit Python on your machine. TensorFlow is tested and supported on the following 64-bit systems. For more information, please check [this document](https://www.tensorflow.org/install#install-tensorflow-2).

Can you please refer to these links and let us know if it helps: [link](https://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso), [link1](https://github.com/tensorflow/tensorflow/issues/7529),[link2](https://github.com/tensorflow/tensorflow/issues/8385), #40668

**Comment by tarangmehta1195** [comment]
i am using 64-bit Python

**Comment by Saduf2019** [comment]
@tarangmehta1195
Can you also verify other requirement:


You might be facing this issue because of the following reasons

You are running 32-bit Python or 32-bit OS
You have not installed the Microsoft [Visual C++ Redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) package
Your CPU does not support AVX instructions.
Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check this similar duplicate issue: #46124

Thanks!
