### ISSUE TITLE
Im trying to list my gpus, but only show gpu0  and do not show gpu1 that is my nvidia

### ISSUE THREAD

**Issue by jpmrs1313** [tensorflow/tensorflow#47359]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by Saduf2019** [comment]
@jpmrs1313 
Can you please provide with more details, how many gpus do you have, what is the purpose[ what function are you calling],  are you planning to use  a stratergy?

**Comment by jpmrs1313** [comment]
I have two gpus, Intel HD Graphics 630 (in my CPU) and GeForce GTX 1050TI and when i list the gpus with this command line:

from tensorflow.python.client import device_lib
device_lib.list_local_devices()

Thats my outpout
[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 16820838733360620967]

I have CUDA v11.2 installed and cudnn too. 
My tensorflow version is 2.4.1 and python 3.8.7

**Comment by jpmrs1313** [comment]
> @ jpmrs1313
> Você pode fornecer mais detalhes, quantos gpus você tem, qual é o propósito [qual função você está chamando], você está planejando usar uma estratégia?

Eu tenho dois gpus, Intel HD Graphics 630 (em minha CPU) e GeForce GTX 1050TI e quando listo o gpus com esta linha de comando:

de tensorflow.python.client import device_lib
device_lib.list_local_devices ()

Esse é meu outpout
[nome: "/ dispositivo: CPU: 0"
device_type: "CPU"
memory_limit: 268435456
localidade {
}
encarnação: 16820838733360620967]

Tenho o CUDA v11.2 instalado e o cudnn também.
Minha versão de tensorflow é 2.4.1 e python 3.8.7

**Comment by jpmrs1313** [comment]
@Saduf2019 

I have 2  gpus, Intel HD Graphics 630 (in CPU) e GeForce GTX 1050TI and when i list gpus with this command line:

de tensorflow.python.client import device_lib
device_lib.list_local_devices ()

Output:

name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 16820838733360620967

I have CUDA v11.2 installed and  cudnn too.
My tensorflow  version is 2.4.1 and python 3.8.7

**Comment by Saduf2019** [comment]
@jpmrs1313 
Can you please try with CUDA 11.0 and let us know if you still face issue.

**Comment by jpmrs1313** [comment]
> @jpmrs1313
> Can you please try with CUDA 11.0 and let us know if you still face issue.

Thanks a lot. It works

**Comment by Saduf2019** [comment]
@jpmrs1313
Thank you for your update, glad your issue is resolved, please move this to closed status.

**Comment by jpmrs1313** [comment]
Thanks
