### ISSUE TITLE
When will tensorflow be compatible with CUDA 11.2?

### ISSUE THREAD

**Issue by AbeG13** [tensorflow/tensorflow#47352]
- TensorFlow version: 2.5 (nightly)
- GPU: RTX 3070
- CUDA version: 11.2
- cuDNN version: 8

Right now, tensorflow is unable to recognize my GPU, so I'm not able to take advantage of the hardware. I read that others have been having the same issue with the newer RTX cards and it's due to tensorflow not supporting the latest CUDA versions. Please make this update, so we can leverage these newer cards. They're pretty hard to get right now, so it was disappointing to find out I couldn't use it.

**Comment by amahendrakar** [comment]
@AbeG13,
Support for CUDA 11.2 has already been requested in issue [#46093](https://github.com/tensorflow/tensorflow/issues/46093).

Can we please close this issue since it is being tracked there? Thanks!

**Comment by AbeG13** [comment]
Okay, closed. I hope the update comes out soon.
