### ISSUE TITLE
TensorFlow 2.4 Contains References to nocopts, which is No Longer Compatible with Bazel

### ISSUE THREAD

**Issue by ssiano** [tensorflow/tensorflow#47353]
In e5f8043742f927ed0e1711bb48f3e1a153b7a997 and ddde447e792231cdf83b435b0eeb59dd59bf4044, among other commits, support for `nocopts` was removed to enable the upgrade of Bazel to 1.0 and above.

However, there are still a few references to `nocopts` in the r2.4 branch:
```
$ git grep nocopts
tensorflow/lite/micro/testing/micro_test.bzl:        nocopts = "",
tensorflow/lite/micro/testing/micro_test.bzl:        nocopts: list of gcc compilation flags to remove for this rule
tensorflow/lite/micro/testing/micro_test.bzl:        nocopts = nocopts,
tensorflow/tensorflow.bzl:    # -fno-exceptions in nocopts breaks compilation if header modules are enabled.
tensorflow/tensorflow.bzl:    # -fno-exceptions in nocopts breaks compilation if header modules are enabled.
```

These should probably be removed for consistency and to avoid confusion.

**Comment by advaitjain** [comment]
https://github.com/tensorflow/tensorflow/pull/47055 removed `tensorflow/lite/micro/testing/micro_test.bzl`.
