### ISSUE TITLE
Getting ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.1

### ISSUE THREAD

**Issue by arpans2112** [tensorflow/tensorflow#47365]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- MacBook pro
- processor: 2GHz Quad-Core Intel Core i5,  
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I'm successfully able to install 1.8.0, 
getting below error with all available wheel from mac os, supported wheel for my mac is cp39, which is not avilable. 
tensorflow-2.4.1-cp36-cp36m-macosx_10_11_x86_64.whl is not a supported wheel on this platform.

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@arpans2112 

Could you please update pip using the below commands and check if you are still facing the same issue?

pip install --upgrade pip
pip install tensorflow
Please ensure your tensorflow version is compatible with the python version used, TF 2.4 supports python from 3.6-3.8 . Please, refer the [document](https://www.tensorflow.org/install/source#cpu),Also, could you check if you are using the 64 bit version of Python. TensorFlow is tested and supported only on 64-bit systems.

Please refer to similar issues, #44615, #45147, #44775, #39130, [link](https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow),
