### ISSUE TITLE
Tensorflow is ignoring `tf.config.set_soft_device_placement(True)`

### ISSUE THREAD

**Issue by shengy90** [tensorflow/tensorflow#47368]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (GPU)
- TensorFlow installed from (source or binary): Google Colab (GPU)
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.10
- CUDA/cuDNN version: Google Colab (GPU)
- GPU model and memory: Google Colab (GPU)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:

**Describe the current behaviour**

I'm training a neural network with embedding layer using GPU-distributed strategy (TF's MirroredStrategy), and I'm getting the following error:

```
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=2 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
GatherV2: GPU CPU 
Cast: GPU CPU 
Const: GPU CPU 
ResourceSparseApplyAdagradV2: CPU 
_Arg: GPU CPU 
ReadVariableOp: GPU CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  model_6_user_embedding_embedding_lookup_readvariableop_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  adagrad_adagrad_update_1_update_0_resourcesparseapplyadagradv2_accum (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  model_6/User-Embedding/embedding_lookup/ReadVariableOp (ReadVariableOp) 
  model_6/User-Embedding/embedding_lookup/axis (Const) 
  model_6/User-Embedding/embedding_lookup (GatherV2) 
  gradient_tape/model_6/User-Embedding/embedding_lookup/Shape (Const) 
  gradient_tape/model_6/User-Embedding/embedding_lookup/Cast (Cast) 
  Adagrad/Adagrad/update_1/update_0/ResourceSparseApplyAdagradV2 (ResourceSparseApplyAdagradV2) /job:localhost/replica:0/task:0/device:GPU:0

     [[{{node model_6/User-Embedding/embedding_lookup/ReadVariableOp}}]] [Op:__inference_train_function_2997]
```

From the error log, it looks like the embedding_lookup/ReadVariableOp is not GPU compatible - which I can understand why. 

But I've set `tf.config.set_soft_device_placement(True)` so I'm expecting TF to use CPU for CPU only operations, and that doesn't seemed to have worked. Is TF ignoring that config setting? Or does that setting doesn't yet support some other conditions? 

**Describe the expected behaviour**

I'd expect MirroredStrategy to default to CPU for CPU only computations by setting `tf.config.set_soft_device_placement(True)` but that doesn't seem to be happening.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Link to Google Colab notebook:
https://colab.research.google.com/drive/1ZN1HzSTTfvA_zstuI-EsKjw7Max1f73v?usp=sharing

Dataset can be found on Kaggle:
https://www.kaggle.com/zygmunt/goodbooks-10k

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Full log can be seen on Google Colab by downloading the dataset from kaggle, uploading to google colab, and running the code on GPU. The neural network is really small -takes less than 5 seconds to execute the whole notebook.

**Comment by shengy90** [comment]
I found this similar issue for TF1.14:
https://github.com/tensorflow/tensorflow/issues/31318

Looks like we can't do MirroredStrategy cannot support training Embedding layers using momentum-based optimisers. There seems to be a fix for TF1.14, but this became a bug again in TF2.0?

Will try to see if using non-momentum-based optimisers work for now to unblock. Still something that should be fixed IMO!

**Comment by shengy90** [comment]
Also, the error message certainly hasn't helped!!

**Comment by shengy90** [comment]
https://colab.research.google.com/drive/13MXa8Q96M6uzlkK3K_M7vmQfclL59eRj?usp=sharing

Confirmed working when training with RMSProp with no momentum, similar to issue #31318 for TF1.14.

**Comment by nikitamaia** [comment]
Hi @shengy90, I ran the colab notebook you provided[ (link)](https://colab.research.google.com/drive/1ZN1HzSTTfvA_zstuI-EsKjw7Max1f73v?usp=sharing) on the GPU runtime, but I'm not seeing any errors. Please take a look and let me know if I'm missing something.

**Comment by shengy90** [comment]
<img width="1818" alt="Screenshot 2021-03-15 at 11 53 10" src="https://user-images.githubusercontent.com/12820124/111149654-0bcc1200-8585-11eb-991e-3e58215b02fb.png">

I just ran it (and got this error - see screenshot). Are you connected to GPU run time? This error only happens when I'm trying to do GPU distributed training using AdaGrad, or RMSprop (with momentum parameter > 0).

@nikitamaia

**Comment by nikitamaia** [comment]
I was able to reproduce the error in colab (not sure what I was doing wrong the first time). I'm not quite sure how `set_soft_device_placement` works with MirroredStrategy, so doing some more investigation.

**Comment by pliu19** [comment]
hello, do we have some expectation of when this will be fixed?

**Comment by mohantym** [comment]
Was able to resolve the issue with TF v2.5 ,please find the gist [here.](https://colab.research.google.com/gist/mohantym/4f8b14d77515e0f5a1a89217d954bddd/mirroredstrategywithrmsprop.ipynb#scrollTo=0neHYIlVAaBl)Thanks!
