### ISSUE TITLE
Any suggestion to use tensorflow feasibly?

### ISSUE THREAD

**Issue by DabiaoMa** [tensorflow/tensorflow#47363]
I am currently doing a research while it is based on a project written with Tensorflow. While I could not implement the dynamic time wrapping easily since it is a dynamic method. With pytorch I could implement it very quickly (since pytorch supports dynamic graph). 

Could anyone help me choose the correct version and documents of Tensorflow that supports dynamic graph? I checked on Tensorflow official website while the document is kind of messy.

**Comment by ariG23498** [comment]
Hey @DabiaoMa 
I think this [thread](https://github.com/tensorflow/tensorflow/issues/12321) might help you.

**Comment by amahendrakar** [comment]
@DabiaoMa,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
