### ISSUE TITLE
ssd mobilenet model size is not correct using tflite converter python api

### ISSUE THREAD

**Issue by uranusx86** [tensorflow/tensorflow#47364]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

My script [SSD mobilenet convert to TF lite colab script](https://colab.research.google.com/drive/1qaGW7ViN0fW2z4bqRKL4sd8X-HIq5Vm2?usp=sharing)

### 3. Failure after conversion

convert offical SSD MobileNet v2 320x320 model using python api from [tf2_detection_zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md), conversion is successful, but tflite file size is too small (only 6.4 MB) and run on mobile extremely slow (900 ms).

And I found following result:

* if **convert to saved model and tflite both using tf 2.4**
   * using tflite converter python api is 6.4M
   * using command line tool (tflite_converter) is 324 bytes
   * **both file is NOT correct**
* if **convert to saved model using TF 2.3 and convert to tflite using tf 2.4**
   * using tflite converter python api is 6.4M
   * using command line tool (tflite_converter) is 24M
   * **the command line tool transform result is correct** which run on mobile very fast (100 ms)!

saved model convert script

```bash=
python object_detection/export_tflite_graph_tf2.py --pipeline_config_path ./ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config --trained_checkpoint_dir ./ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint/ --output_directory ./output/
```

tflite converter python api convert code

```python=
converter = tf.lite.TFLiteConverter.from_saved_model('output/saved_model/',signature_keys=["serving_default"])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with tf.io.gfile.GFile('output/detect_using_api.tflite', 'wb') as f:
  f.write(tflite_model)
```

command line tool convert script

```bash=
tflite_convert --output_file output/detect_using_command.tflite --saved_model_dir output/saved_model/ --experimental_new_converter True
```

My question is

Why output result is different between using tflite converter python api and command line tool?

### 5. (optional) Any other info / logs
N/A

**Comment by abattery** [comment]
We recommend using the python API conversion over the command line. Could you verify this behavior with tf-nightl

**Comment by uranusx86** [comment]
I have tried, but it keep same size (6.4 MB) by using python API conversion.

It doesn't make sense because the weight file of SSD MobileNet v2 320x320 is about 24 MB, tflite file size is too small.

**Comment by abattery** [comment]
Did you verify the converted models their correctness other than file sizes? The file size can be reduced due to pruning unused parts in the model when the some weight data aren't related with the inference run.

**Comment by uranusx86** [comment]
install converted tflite file on mobile which convert by tf-nightly, it can detect object (but I don't test whether the accuracy is same as saved model file) but extremely slow (900 ms).

but if I install converted tflite file which convert by command line tool, it run fast (100 ms).

**Comment by abattery** [comment]
Could you share the above models to us?

**Comment by uranusx86** [comment]
Sure.
[detect_using_api.zip](https://github.com/tensorflow/tensorflow/files/6040054/detect_using_api.zip)
[detect_using_command.zip](https://github.com/tensorflow/tensorflow/files/6040055/detect_using_command.zip)

**Comment by abattery** [comment]
Interestingly, they have the identical same graph structure when I looked at the netron. Will look at the details.

**Comment by abattery** [comment]
@talumbau Could you take a look?

The graph structures are identical but the user reported that there is a 9x performance difference on mobile.

I tried on the x86 machine only. Their latency data look similar.

- detect_using_api.tflite
```
Inference timings in us: Init: 3932, First inference: 112837, Warmup (avg): 88766.2, Inference (avg): 81024.4
```

- detect_using_command.tflite
```
Inference timings in us: Init: 3028, First inference: 108867, Warmup (avg): 85563.7, Inference (avg): 79799.9
```

**Comment by uranusx86** [comment]
Hi, I test tflite file on Colab today.

It show same performance issue, detect_using_command.tflite **is better than** detect_using_api.tflite.

test code:

```python=
import os, time
import numpy as np

def prepare(model_name):
    interpreter = tf.lite.Interpreter(model_path=model_name)
    input_index = interpreter.get_input_details()[0]["index"]
    output_index = interpreter.get_output_details()[0]["index"]
    interpreter.allocate_tensors()
    return interpreter, input_index, output_index

def infer(image, interpreter, input_index, output_index):
    interpreter.set_tensor(input_index, image)
    interpreter.invoke()
    outputs = interpreter.get_tensor(output_index)
    return outputs

api_interpreter = prepare(os.path.join("output", "detect_using_api.tflite"))
command_interpreter = prepare(os.path.join("output", "detect_using_command.tflite"))

api_time = []
command_time = []

for _ in range(100):
  img = (np.random.random(size=(1, 300, 300, 3))).astype(np.float32)

  start = time.time()
  out = infer(img, *api_interpreter)
  api_time.append(time.time() - start)

  start = time.time()
  out = infer(img, *command_interpreter)
  command_time.append(time.time() - start)

print("api version avg time", sum(api_time)/len(api_time))
print("cmd version avg time", sum(command_time)/len(command_time))
```

and result

```
api version avg time 2.333226749897003
cmd version avg time 0.08322675704956055
```

**Comment by WindQAQ** [comment]
@uranusx86 @abattery The model is very different. The API converted model uses `tf.lite.Optimize.DEFAULT`, which enables quantization as per https://www.tensorflow.org/api_docs/python/tf/lite/Optimize?version=nightly (I would say this argument is bogus because it's not default at all... ). For example, you can see that `ssd_mobile_net_v2keras_feature_extractor/model/block_1_project/Conv2D` has int8 weights while command line converted model has float32 weights. Therefore, the API converted model has smaller size. 

For the performance, on my Pixel3a, 

API converted model
```
Timings (microseconds): count=50 first=138922 curr=138345 min=136733 max=29662368 avg=2.51898e+06 std=6203433
```
Commandline converted model
```
Timings (microseconds): count=38 first=187153 curr=39225742 min=172200 max=39250433 avg=4.93929e+06 std=10202402
```

On x86 arch, it's less optimization on int kernel, so the performance is expected to be slower when trying to use integer kernel.

**Comment by abattery** [comment]
Thanks @WindQAQ a lot for the through investigations! :-) Your explanations make sense.

**Comment by abattery** [comment]
@uranusx86 You can remove the `converter.optimizations = [tf.lite.Optimize.DEFAULT]` line. Then, you will have the almost same model with the one generated by the command line.

**Comment by uranusx86** [comment]
WOW, thank you guys.

After remove `converter.optimizations = [tf.lite.Optimize.DEFAULT]`, the files are same.

I never knew tf.lite.Optimize.DEFAULT option enables quantization ...

And it make sense why API converted model is slow than Commandline converted model because I use very old mobile (snapdragon 801) to test, the CPU performance may degrade when compute quantization operation.
