### ISSUE TITLE
AttributeError: Can't set the attribute "name" when building bidirectional layer with stackedrnncell

### ISSUE THREAD

**Issue by kongyansan** [tensorflow/tensorflow#47373]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
On Jupyter Notebook, Python 3.6, Tensorflow Version 2.4

**Describe the current behavior**
I am currently trying to build a bidirectional layer using stackedrnncell. However, I am running to an attribute error but the error message is not helping me in debugging this error. 

**Describe the expected behavior**
Would expect the model to be build. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

lstm_1 = tf.keras.layers.LSTMCell(128)
lstm_2 = tf.keras.layers.LSTMCell(128)
lstm_fw_cell = tf.keras.layers.StackedRNNCells([lstm_1, lstm_2])
lstm_fw = tf.keras.layers.RNN(lstm_fw_cell,unroll=True)

lstm_3 = tf.keras.layers.LSTMCell(128)
lstm_4 = tf.keras.layers.LSTMCell(128)
lstm_bw_cell= tf.keras.layers.StackedRNNCells([lstm_3, lstm_4])
lstm_bw = tf.keras.layers.LSTM(lstm_bw_cell,go_backwards=True,unroll=True)

model = Sequential()
model.add(Bidirectional(lstm_fw, backward_layer=lstm_bw))
model.add(Dense(4, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

![image](https://user-images.githubusercontent.com/41911024/109015802-7a3d5300-76f0-11eb-9ed7-b6a7b3f34f04.png)

**Comment by kongyansan** [comment]
`lstm_cell_1 = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(rnn_size, forget_bias=1.0, state_is_tuple=True)
lstm_cell_2 = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(rnn_size, forget_bias=1.0, state_is_tuple=True)
lstm_fw_cell = tf.compat.v1.nn.rnn_cell.MultiRNNCell([lstm_cell_1, lstm_cell_2], state_is_tuple=True)
fw = RNN(lstm_fw_cell, unroll=True)

lstm_cell_3 = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(rnn_size, forget_bias=1.0, state_is_tuple=True)
lstm_cell_4 = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(rnn_size, forget_bias=1.0, state_is_tuple=True)
lstm_bw_cell = tf.compat.v1.nn.rnn_cell.MultiRNNCell([lstm_cell_3, lstm_cell_4], state_is_tuple=True)

model = Sequential()
model.add(Bidirectional(fw))
model.add(Dense(4, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()`

I have also tried another method using tf.compat rather than tf.keras but I got the following error instead. And is there a difference between StackedRNNCell and MultiRNN?

![image](https://user-images.githubusercontent.com/41911024/109018999-8d9ded80-76f3-11eb-827d-ff86782a3151.png)

**Comment by Saduf2019** [comment]
@kongyansan 
Code provided is not sufficient to replicate issue reported, can you please share a colab gist with the error.

**Comment by kongyansan** [comment]
Hi, i think there was some issues with my environment because I managed to run model.summary() after initialising the new one. Thank you and I will be closing this issue
