### ISSUE TITLE
No version of tensorflow will install on python 3.7.9 x64 / pip 20.1

### ISSUE THREAD

**Issue by abolotnov** [tensorflow/tensorflow#47376]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `OS X 11.1 (PC)`
- TensorFlow installed from (source or binary): `pip`
- TensorFlow version: `1.15 or any other`
- Python version: `3.7.9`
- Installed using virtualenv? pip? conda?: `pip`

**Describe the problem**

installed python 3.7.9 as compatible platform with TF 1.15 via `pyenv`
no version of tf will install at all:

```
:~$ python3 -VV
Python 3.7.9 (default, Feb 24 2021, 13:04:10)
[Clang 12.0.0 (clang-1200.0.32.29)]
:~$ python3 -c 'import sys;print("%x" % sys.maxsize, sys.maxsize > 2**32)'
7fffffffffffffff True
:~$ python3 -m pip install tensorflow==1.15
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15
```
same output with just `pip3 install tensorflow`

Is there something else I am overlooking as far the python/pip version/build type?

**Comment by amahendrakar** [comment]
@abolotnov,
TensorFlow 1.x is not actively supported. Please try installing the latest stable version of TensorFlow v2.4.1 using the below command.

`pip install --upgrade tensorflow`

Thanks!

**Comment by abolotnov** [comment]
Not sure how exactly I fixed it, but I got it fixed somehow.
