### ISSUE TITLE
Generating the descriptors of constant shape

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#47381]
The local features generated by tensorflowv1 is different from tensorflowv2.5

```
def generate_vectors(paths):
    
    ops.reset_default_graph()
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.FATAL)

    model = hub.Module('https://tfhub.dev/google/delf/1')

    image_placeholder = tf.compat.v1.placeholder(tf.float32, shape=(None, None, 3), name='input_image')

    module_inputs = {
        'image': image_placeholder,
        'score_threshold': 100.0,
        'image_scales': [0.25, 0.3536, 0.5, 0.7071, 1.0, 1.4142, 2.0],
        'max_feature_num': 1000,
    }

    module_outputs = model(module_inputs, as_dict=True)
    image_tf = paths_to_image_loader(list(paths))
    img_paths = []
    with tf.compat.v1.train.MonitoredSession() as sess:
        features = []

        for i in tqdm(range(len(paths))):
            image = sess.run(image_tf)
            local_feature = sess.run([module_outputs['locations'], module_outputs['descriptors']],
                                     feed_dict={image_placeholder: image})

```

The local_feature[1] and local_feature[0] has got a constant shape of 1000 with the above code that has the legacy cide,.

I used the latest code to generate vectors as follow,

```
def run_delf(image):
    np_image = np.array(image)
    float_image = tf.image.convert_image_dtype(np_image, tf.float32)

    return delf(
        image=float_image,
        score_threshold=tf.constant(100.0),
        image_scales=tf.constant([0.25, 0.3536, 0.5, 0.7071, 1.0, 1.4142, 2.0]),
        max_feature_num=tf.constant(1000))
```

Unfortunately `result["locations"].numpy()` and `result["descriptors"].numpy()` always has got a different shapes for every image inputs while it is intended to have 1000 features. How can I fix it?

**Comment by ravikyram** [comment]
@Zumbalamambo 

This issue is more suitable for TensorFlow Hub repo. Please post it on hub repo from [here](https://github.com/tensorflow/hub/issues/new). Thanks!

**Comment by Zumbalamambo** [comment]
@ravikyram The error is due to the mismatch in the tensorflow version and not because tf-hub!!

**Comment by ravikyram** [comment]
@Zumbalamambo 

Can you please help us with the colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by Saduf2019** [comment]
@Zumbalamambo
Please update as per above comment
