### ISSUE TITLE
[XLA:GPU] Build failure

### ISSUE THREAD

**Issue by nouiz** [tensorflow/tensorflow#47386]
This commit:

```
commit 9f8d5d0ef4e990ab2398d573a14aaa8ed02a10e2
Author: Rahul Joshi <jurahul@google.com>
Date:   Mon Feb 22 08:41:59 2021 -0800

    [MLIR:LHLO] Add optional call target arg mapping to LMHLO CustomCall operations.

    - XLA:HLO -> LMHLO conversion drops all token arguments and return values, however
      custom calls that users write still expect to get buffer pointers for these token types.
    - To be able to support this, add an optional call target argument mapping attribute to
      LMHLO custom calls. When this attribute is present, it indicates the number of
      arguments and returns that the custom call expects and also indicates which LMHLO
      arg() or output() maps to which arg or result number of the custom call.

    PiperOrigin-RevId: 358826664
    Change-Id: I36e839e9ff5b73890715b71717a4c13631955fba
```

Introduced a compilation regression. Before that commit, this command line works:

```
bazel test -c opt --config=cuda //tensorflow/compiler/xla/tests:conv_depthwise_test_gpu //tensorflow/compiler/xla/tests:grouped_convolution_test_gpu
```

Starting at this commit, it gives this error:
```
ERROR: /home/fbastien/github/tensorflow-tf2-upstream2/tensorflow/compiler/mlir/hlo/BUILD:485:11: undeclared inclusion(s) in rule '//tensorflow/compiler/mlir/hlo:lhlo':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/lhlo_ops_structs.cc':
  'bazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen/mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.h.inc'
  'bazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen/mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc'
cc1plus: warning: command line option ‘-Wno-pointer-sign’ is valid for C/ObjC but not for C++
```

@jurahul that authored it.

**Comment by jurahul** [comment]
Thanks for the bug. It was reported internally as well, and I have a fix in flight.

**Comment by jurahul** [comment]
Should be fixed now with https://github.com/tensorflow/tensorflow/commit/d439d8c6d4137e0bc468a2de06e41b375029ee92. Would be great if you can confirm.

**Comment by nouiz** [comment]
I still have this error:
```
ERROR: /home/fbastien/github/tensorflow-tf2-upstream2/tensorflow/compiler/xla/service/gpu/BUILD:1635:11: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/service/gpu:buffer_comparator':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/service/gpu/buffer_comparator.cc':
  'bazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen/mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.h.inc'
```

with your commit and with e5bf7893fefb12b796c075d6d4cd3a608d84c2f2.

**Comment by jurahul** [comment]
Thanks for checking. Looking again, I guess I need to attempt to build TF from OSS and try to reproduce the issue first.

**Comment by michaelbanfield** [comment]
I was able to resolve this by wiping out my bazel cache.


```
rm -rf ~/.cache/bazel 
```

**Comment by jurahul** [comment]
Thanks Michael. I also was able to build OSS TF after this change. Back to @nouiz to check if deleting the bazel cache fixes the issue.

**Comment by benbarsdell** [comment]
I hit this error too. Doing a `bazel clean --expunge` fixed it. Does this indicate a bug in Bazel?

**Comment by nouiz** [comment]
I have the same behavior as @benbarsdell. the clean shouldn't be needed.

**Comment by jurahul** [comment]
I guess there is nothing to fix now on the tensorflow side. @mihaimaruseac should this issue be reported to bazel?

**Comment by mihaimaruseac** [comment]
Yes please, that's a better approach.

**Comment by jurahul** [comment]
I have filed a new issue with bazel: https://github.com/bazelbuild/bazel/issues/13135. @nouiz, would it be possible for you to provide build configuration information on the bazel issue? After that, I think we can close this issue.

**Comment by jurahul** [comment]
Closing this as this is a bazel issue.

**Comment by nouiz** [comment]
We didn't got any update on the bazel bug in ~2.5 mounts. I poked them yesterday, but still no news.

This is very troublesome for us. Mostly, we can't use git bisect or reuse the same directory when moving between branch. This normally help save TF compilation time that is very slow without a build cluster as you have.

Any idea how to make sure this get fixed?

Also, are you sure it isn't a bug in TF bazel rules and not inside bazel itself?
