### ISSUE TITLE
Feature Request: Include function argument defaults in the documentation

### ISSUE THREAD

**Issue by markpwoodward** [tensorflow/tensorflow#4738]
I have recently started using functions from tf.contrib. They speed things up a lot. Thank you. 

I did notice that some of the prototypes in the documents have their arguments replaced with `(*args, **kwargs)`. See tf.contrib.layers: https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.layers.html#layers-contrib. Perhaps this is automatically done if the number of arguments exceeds some number. Unfortunately the prototype is the only place where the argument defaults are shown. I have been looking at the source file, layers.py, to see the full prototype for the defaults which is fine, but probably not idea. 

My request is to include the argument defaults somewhere in the documentation. I wouldn't mind long prototypes, i.e. getting rid of the `(*args, **kwargs)`. Or if people want the shorter prototypes, maybe the argument defaults could be automatically included somewhere in the description.

**Comment by tatatodd** [comment]
Thanks for filing the issue @markpwoodward!  Indeed the documentation is suboptimal.

@martinwicke might have some ideas on who to involve to get this fixed.

**Comment by martinwicke** [comment]
This is a problem with the `@arg_scope` decorator, which being a decorator, changes the function signature to `**kwargs` and `*args`. @sguada can we fix this by making our doc generator inspect through arg_scope and use the function args form the inside?

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
