### ISSUE TITLE
Unable to build TFLite for Microcontrollers on Mac OS 

### ISSUE THREAD

**Issue by Sehaba95** [tensorflow/tensorflow#47399]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac OS Mojave (version: 10.14.6)
- TensorFlow installed from (source or binary): from source 
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): zephyr_vexriscv (from [this tutorial](https://blog.tensorflow.org/2020/06/running-and-testing-tf-lite-on-microcontrollers.html)

**Describe the problem**
I have created my own test project base on [this tutorial](https://blog.tensorflow.org/2020/06/running-and-testing-tf-lite-on-microcontrollers.html), but when I build it using the following command: 
**make -f tensorflow/lite/micro/tools/make/Makefile TARGET="zephyr_vexriscv" ruby1_bin**
 
I have got this error message:
tensorflow/lite/micro/tools/make/Makefile:417: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:417: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
g++ -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter  -I. -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/kissfft -o tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/bin/ruby1 tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/obj/tensorflow/lite/micro/examples/ruby1/main.o tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/obj/tensorflow/lite/micro/examples/ruby1/model_28.o tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/lib/libtensorflow-microlite.a  -lm
Undefined symbols for architecture x86_64:
  "_stbi_load", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tensorflow/lite/micro/examples//ruby1/Makefile.inc:13: tensorflow/lite/micro/tools/make/gen/zephyr_vexriscv_x86_64/bin/ruby1] Error 1

**Comment by mohantym** [comment]
Hi @Sehaba95! 
We are checking to see whether you still need help in this issue .Supported Micro controllers for Tensorflow can be found [here](https://www.tensorflow.org/lite/microcontrollers). You can refer this[ link](https://github.com/milinddeore/TfLite-Standalone-build-Linux-MacOS) for building TFLite in macos .Thanks!
