### ISSUE TITLE
Did not open image after detecting object using tensorflow2

### ISSUE THREAD

**Issue by rutvi1462** [tensorflow/tensorflow#47392]
I am learning object [detetction with tensorflow2](https://gilberttanner.com/blog/tensorflow-object-detection-with-tensorflow-2-creating-a-custom-model) and my model trained successfully.

But whenever I trying to [Test trained model on test images](https://colab.research.google.com/github/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model/blob/master/Tensorflow_2_Object_Detection_Train_model.ipynb#scrollTo=5tGVwzpLxvSv) in my _VScode_, image doesn't open.

### Here is my code:

```
import io
import os
import cv2
import scipy.misc
import numpy as np
import six
import time
import glob
from IPython.display import display

from six import BytesIO

import matplotlib
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont

import tensorflow as tf
from object_detection.utils import ops as utils_ops
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util

def load_image_into_numpy_array(path):
  """Load an image from file into a numpy array.

  Puts image into numpy array to feed into tensorflow graph.
  Note that by convention we put it into a numpy array with shape
  (height, width, channels), where channels=3 for RGB.

  Args:
    path: a file path (this can be local or on colossus)

  Returns:
    uint8 numpy array with shape (img_height, img_width, 3)
  """
  img_data = tf.io.gfile.GFile(path, 'rb').read()
  image = Image.open(BytesIO(img_data))
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

category_index = label_map_util.create_category_index_from_labelmap('training/label_map.pbtxt', use_display_name=True)

tf.keras.backend.clear_session()
model = tf.saved_model.load(f'inference_graph/saved_model')

def run_inference_for_single_image(model, image):
  image = np.asarray(image)
  # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
  input_tensor = tf.convert_to_tensor(image)
  # The model expects a batch of images, so add an axis with `tf.newaxis`.
  input_tensor = input_tensor[tf.newaxis,...]

  # Run inference
  model_fn = model.signatures['serving_default']
  output_dict = model_fn(input_tensor)

  # All outputs are batches tensors.
  # Convert to numpy arrays, and take index [0] to remove the batch dimension.
  # We're only interested in the first num_detections.
  num_detections = int(output_dict.pop('num_detections'))
  output_dict = {key:value[0, :num_detections].numpy() 
                 for key,value in output_dict.items()}
  output_dict['num_detections'] = num_detections

  # detection_classes should be ints.
  output_dict['detection_classes'] = output_dict['detection_classes'].astype(np.int64)
   
  # Handle models with masks:
  if 'detection_masks' in output_dict:
    # Reframe the the bbox mask to the image size.
    detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
              output_dict['detection_masks'], output_dict['detection_boxes'],
               image.shape[0], image.shape[1])      
    detection_masks_reframed = tf.cast(detection_masks_reframed > 0.5,
                                       tf.uint8)
    output_dict['detection_masks_reframed'] = detection_masks_reframed.numpy()
    
  return output_dict
  
for image_path in glob.glob('images/test/*.jpg'):
  image_np = load_image_into_numpy_array(image_path)
  output_dict = run_inference_for_single_image(model, image_np)
  vis_util.visualize_boxes_and_labels_on_image_array(
      image_np,
      output_dict['detection_boxes'],
      output_dict['detection_classes'],
      output_dict['detection_scores'],
      category_index,
      instance_masks=output_dict.get('detection_masks_reframed', None),
      use_normalized_coordinates=True,
      line_thickness=8)
  display(Image.fromarray(image_np))
```

### After run the python file I got below output in cmd:

> <PIL.Image.Image image mode=RGB size=500x625 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=242x239 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=238x238 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=489x368 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=433x358 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=486x486 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=492x487 at 0x2090689B040>
> <PIL.Image.Image image mode=RGB size=155x357 at 0x2090689B040>

**_I didn't get expected output which is shown [here](https://colab.research.google.com/github/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model/blob/master/Tensorflow_2_Object_Detection_Train_model.ipynb#scrollTo=EEX-m3P1yp4y&line=5&uniqifier=1)._** Please help me to solve this.

**Comment by AdityaKane2001** [comment]
@rutvi1462 
If you run this code with a normal Python interpreter, this output is expected. To resolve this, you have two options. One, you can save these images to disk and view them as normal images. Secondly, you can try with `cv2.imshow()` method. This works when calling through interpreter and shell. 
Sometimes Jupyter or Colab notebooks face similar issues, so it's best to avoid them for this case.

**Comment by rutvi1462** [comment]
@AdityaKane2001 
Thanks for your answer. Images are already saved in my drive. But its give me same output. And I tried `cv2.imshow()`. I wrote this above `display(Image.fromarray(image_np))`. But it would show me only image. This is not detect at least wrong object. Do you have any solution?

**Comment by AdityaKane2001** [comment]
So, if you are accessing from a script, IPython module will not help you. Please try with `cv2.in=imshow()` . Secondly, when using cv2, don't forget to manually draw the boxes using `cv2.rectangle()`  . I think using this method, you will get your results.

In case the issue gets resolved, don.t forget to close this issue.

**Comment by rabion1234** [comment]
had you completed this issue because i am getting this issue too?
