### ISSUE TITLE
Feature request: Implement QR decomposition

### ISSUE THREAD

**Issue by kstant0725** [tensorflow/tensorflow#4739]
Feature request:  A tensorflow op that performs numerically stable (works on non full rank matrices) QR decomposition along with gradients so that it can be used in layers and cost functions.

**Comment by tatatodd** [comment]
Contributions are welcome!

**Comment by LaurenLuoYun** [comment]
@kstant0725 I want to try adding this implement.

**Comment by dougalsutherland** [comment]
This seems to have been added in https://github.com/tensorflow/tensorflow/commit/715f951eb9ca20fdcef20bb544b74dbe576734da.

**Comment by kstant0725** [comment]
I seem to get the following error when I try to use the QR in a network.  Was the gradient implemented?

LookupError: No gradient defined for operation 'Qr_1' (op type: Qr)

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
