### ISSUE TITLE
BestExporter exports worse model when training tasks restart.

### ISSUE THREAD

**Issue by wuxianxingkong** [tensorflow/tensorflow#47396]
BestExporter is widely used in my company to avoid model degradation with time. But BestExporter exports worse model when training task restart.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Distributed training.
- TensorFlow installed from (source or binary):binary.
- TensorFlow version (use command below): All versions(TF1.14, TF1.15, TF2.x).

**Describe the current behavior**

There are scenes for example we need to restart training tasks: 

1. continuous training(not online streaming training): Training with new data and check if its satisfies the best exporter condition.
2. Failure restart: In local or distributed training, worker failure is common, thanks to the checkpoint, we can restart failed task.

For example, old best AUC is 0.85, but when we restart training task,  [self._has_exported](https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/exporter.py#L295) in BestExporter is False, and TF will export new saved model ignoring whether current eval_result(for example AUC=0.79) is better than best_result(AUC=0.80)  loaded from event files created by last running task or not. And next all eval_results(for example AUC=0.80, AUC=0.81) are worse than old AUC=0.85 unfortunately which means all newer saved_models are worse than old one and may cause worse online business metrics.

This bug was imported in [issue](https://github.com/tensorflow/estimator/pull/41)  and  [this commit](https://github.com/tensorflow/estimator/commit/43921b4552d1c30acc31d3b5989112cb397383e0#diff-5e0426432b8f40323ca256ef0d11b27ec3a7b4cc9d4042d228b17d0b13d73cfb).

**Describe the expected behavior**

Export REAL best model.

**Standalone code to reproduce the issue**

Has been proved in production environment.

**Comment by Saduf2019** [comment]
@wuxianxingkong 
Please share simple stand alone code to replicate the issue reported or a colab gist with the error and code.
