### ISSUE TITLE
EagerTensor implements `__len__` but not `len()`.

### ISSUE THREAD

**Issue by noppelmax** [tensorflow/tensorflow#47393]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux merry 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- TensorFlow installed from (source or binary): `pip install tensorflow`
- TensorFlow version (use command below): `v2.4.0-49-g85c8b2a817f 2.4.1`
- Python version: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`

**Describe the current behavior**
The EagerTensor implements `__len__` but does not provide the `len(.)` function.

**Describe the expected behavior**
If `__len__` is a attribute, the `len(.)` function should work.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
import sys

print(tf.version.GIT_VERSION, tf.version.VERSION) # v2.4.0-49-g85c8b2a817f 2.4.1
print(sys.version) # 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
x = np.dtype('float32').type(3.0)

sigmoid = tf.keras.layers.Activation(activation="sigmoid")
actX = sigmoid(x)

print(type(x)) # <class 'numpy.float32'>
print(type(actX)) # <class 'tensorflow.python.framework.ops.EagerTensor'>

if hasattr(actX, "__len__"):
    print(len(actX))
else:
    print("Has no length")
```
yield the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a34ef039f8c4> in <module>
      9 
     10 if hasattr(actX, "__len__"):
---> 11     print(len(actX))
     12 else:
     13     print("Has no length")

~/Projects/NotebooksEnvs/py38Env/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in __len__(self)
   1020     """Returns the length of the first dimension in the Tensor."""
   1021     if not self.shape.ndims:
-> 1022       raise TypeError("Scalar tensor has no `len()`")
   1023     # pylint: disable=protected-access
   1024     try:

TypeError: Scalar tensor has no `len()`
```

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a61b1be61641de145afc27ff46e02b7d/untitled552.ipynb)

**Comment by jvishnuvardhan** [comment]
@noppelmax Looks like this throws an error when the object has single element. When I have list object as shown below, then there is no issue.  Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/be4093be730a116a6a1046fe7dbad607/untitled552.ipynb)

`x = np.dtype('float32').type([3.0, 4.0, 5.0])`

I am not sure whether it is intended or not. We will look into it. Thanks!

**Comment by JW1992** [comment]
This is an expected behavior. As the trace shows, the tensor is a scalar. As a result len() does not really apply here.

**Comment by noppelmax** [comment]
So the only possibility to check whether a tensor is a scalar or not is a `try-except`?

**Comment by JW1992** [comment]
Hi @noppelmax, can you please specify what is your usage scenario? What about attribute 'shape'?

`x = tf.constant(1)
y = tf.constant([1,2,3])

print(x.shape)
print(y.shape)`
