### ISSUE TITLE
How to change the type of placeholder

### ISSUE THREAD

**Issue by lglhuada** [tensorflow/tensorflow#474]
I declared a placeholder with labels=tf.placeholder(tf.float32,shape=(5)), 
while when I checked the shape of 'labels' with tf.shape(labels), it returned 
Tensor("Shape_2:0", shape=TensorShape([Dimension(1)]), dtype=int32, device=/gpu:1) TensorShape([Dimension(5)]). 

Obviously I set labels as tf.float32, it is actually int32. How can I resolve it. Thanks in advance.

**Comment by girving** [comment]
The shape of a tensor is always integers, regardless of the dtype of the tensors.  For example, a 1-D tensor can't have 2.7 elements.

**Comment by girving** [comment]
If you want to see the dtype of labels, do `labels.dtype`.

**Comment by lglhuada** [comment]
OK, thanks for your very quick feedback.
