### ISSUE TITLE
Tensorflow and flask has an error loading model.

### ISSUE THREAD

**Issue by liming-developer-python** [tensorflow/tensorflow#47403]
Hello 
According to this closed issue, https://github.com/tensorflow/tensorflow/issues/44467
I tried to install h5py == 2.10.0 version on my venv
But still got same error

![image](https://user-images.githubusercontent.com/75870530/109180833-46346180-77c6-11eb-9988-8925782f5bc8.png)
![image](https://user-images.githubusercontent.com/75870530/109180849-4cc2d900-77c6-11eb-83a7-0c35caad603b.png)
![image](https://user-images.githubusercontent.com/75870530/109180894-54827d80-77c6-11eb-9629-c21b75c8b590.png)

Please help me
Thanks All!

**Comment by liming-developer-python** [comment]
According to https://github.com/tensorflow/tensorflow/issues/44467 , they used tensorflow 2.1 but I am using 1.4, is that a problem?

**Comment by liming-developer-python** [comment]
But I couldn't get that version.
![image](https://user-images.githubusercontent.com/75870530/109181253-ad521600-77c6-11eb-8d15-39da91f59497.png)
Please look, and let me get correct version.
Thanks

**Comment by Abduttayyeb** [comment]
@liming-developer-python I think you should look once here #39130, check the py ver. you are using, maybe that's creating an issue.

**Comment by liming-developer-python** [comment]
@Abduttayyeb Thanks for your advise
I installed python tensorflow 2.1.0 successfully But have same error continuosly.
Please can you tell me another solution to solve that loading model error?
![image](https://user-images.githubusercontent.com/75870530/109241139-caf99c80-7813-11eb-99fa-809dff940087.png)

**Comment by Saduf2019** [comment]
@liming-developer-python 
Please verify if you have 64 bit python version and OS.
Please refer to similar issues : #47365, #47151, #42163, 

Could you please update pip using the below commands and check if you are still facing the same issue?
pip install --upgrade pip
pip install tensorflow.
