### ISSUE TITLE
Layer .input_shape and .output_shape wrongly claim "The layer has never been called"

### ISSUE THREAD

**Issue by jameshfisher** [tensorflow/tensorflow#47404]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2
- TensorFlow installed from (source or binary): https://github.com/apple/tensorflow_macos
- TensorFlow version (use command below): v1.12.1-44680-gc3fea33a21 2.4.0-rc0
- Python version: 3.8.6

**Describe the current behavior**
For a layer `l`, `l.input_shape` and `l.output_shape` raise the error "AttributeError: The layer has never been called and thus has no defined input shape", even though the layer has definitely been called.

**Describe the expected behavior**
After a layer `l` has been called, `l.input_shape` and `l.output_shape` return shapes.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
l = tf.keras.layers.Dense(units=2)
l(tf.ones((5,3)))  # Call the layer, defining the input shape
print(l.input_shape)  # Expected: (None, 3)
print(l.output_shape)  # Expected: (None, 2)
```

**Other info / logs**
* It's possible I'm using the API wrongly. But I'm pretty sure the claim "The layer has never been called" is false.
* This works as expected if I wrap the layer in a `tf.keras.Sequential`. Is there an assumption that the layer is inside a `tf.keras.Model`?

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/55e1f6adb00a794bd52d780958a9df23/untitled552.ipynb)

**Comment by ymodak** [comment]
Your assumption is correct, you need to instantiate the `tf.keras.model` before inspecting the shapes of the layers. `dense layer` by itself has not attribute `output_shape`.
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense#example

**Comment by jameshfisher** [comment]
Thanks @ymodak - makes sense. `.output_shape` seems like a private API so I can't really complain - as you say, I should be calling a model, not a layer.
