### ISSUE TITLE
How to run a model training command in redhat linux slurm file?

### ISSUE THREAD

**Issue by Homayra22** [tensorflow/tensorflow#47406]
<em>Hello , I am trying to run a model training command  for object detection in cluster server. For this reason, I need to run a final command in a particular directory . As I am working on a cluster server, I am creating a slurm file. After the basic instructions, I  wrote the directory where the training command will be executed and now I am unable to connect the training command with the slurm file.</em>

![Slurrm _ssd](https://user-images.githubusercontent.com/68661510/109196179-ff605080-7760-11eb-963d-8e46fbb6fcd7.png)

**Comment by Saduf2019** [comment]
@Homayra22 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please paste error logs its easy to search the issue.

**Comment by Homayra22** [comment]
Thanks, my problem is solved. I just used the full forms of all the slurm commands and delete " -l" from the first line. Also, I run the model training code without " srun python 3" command.

**Comment by Saduf2019** [comment]
@Homayra22
Please move this issue to closed status as its resolved.
