### ISSUE TITLE
Install gpu Ubuntu16.04 misses crucial steps: "unable to locate package nvidia-driver-450"

### ISSUE THREAD

**Issue by GrigoriiTarasov** [tensorflow/tensorflow#47402]
## URL(s) with the issue:
https://www.tensorflow.org/install/gpu?hl=ur#ubuntu_1604_cuda_110
## Description of issue (what needs changing):

19th line:
`sudo apt-get install --no-install-recommends nvidia-driver-450`
leads to error: 
`E: Unable to locate package nvidia-driver-450`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please take a look at the below screenshot for reference

![Screenshot 2021-02-26 3 05 53 PM](https://user-images.githubusercontent.com/57165142/109282900-28a5dd00-7844-11eb-9d29-83ec21948a20.png)

Thanks!

**Comment by amahendrakar** [comment]
@GrigoriiTarasov,
With reference to issue [#44301](https://github.com/tensorflow/tensorflow/issues/44301#issuecomment-716250923), ignoring the `sudo apt-get install --no-install-recommends nvidia-driver-450` command seems to work in this case.

Could you please skip that particular step and check if you are able to install TensorFlow. Thanks!

**Comment by GrigoriiTarasov** [comment]
@amahendrakar
Thanks a lot!
I confirm that skipping 19th line works.
