### ISSUE TITLE
Login loop caused by unmet packages in gpu Ubuntu16.04 installation guide

### ISSUE THREAD

**Issue by GrigoriiTarasov** [tensorflow/tensorflow#47405]
**System information**
- OS Platform and Distribution Linux Ubuntu 16.04:
- GeForce GTX TITAN 2070
Other inapplicable cause I following a guide: 
https://www.tensorflow.org/install/gpu?hl=ur#ubuntu_1604_cuda_110

**Describe the problem**
23th line 
`sudo apt-get install --no-install-recommends     cuda-11-0     libcudnn8=8.0.4.30-1+cuda11.0      libcudnn8-dev=8.0.4.30-1+cuda11.0`

leads to
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcudnn8-dev is already the newest version (8.0.4.30-1+cuda11.0).
libcudnn8 is already the newest version (8.0.4.30-1+cuda11.0).
The following additional packages will be installed:
  cuda-demo-suite-11-0 cuda-drivers cuda-drivers-460 cuda-runtime-11-0
  nvidia-460 nvidia-460-dev
Recommended packages:
  nvidia-prime | bumblebee
The following packages will be REMOVED:
  nvidia-450
The following NEW packages will be installed:
  cuda-11-0 cuda-demo-suite-11-0 cuda-drivers cuda-drivers-460
  cuda-runtime-11-0 nvidia-460 nvidia-460-dev
0 upgraded, 7 newly installed, 1 to remove and 66 not upgraded.
Need to get 0 B/168 MB of archives.
After this operation, 93,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] `

If 'yes' is choosen next reboot leads to login loop because of
"NVIDIA NVML Driver/library version mismatch"
nvidia 450 was installed at 19th line and nvidia 460 after 23th line

Deleting nvidia 460 allowing to login normally,with nvidia smi giving 450 version,
but 
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices()
```
Still don't show accessible GPU.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
https://www.tensorflow.org/install/gpu?hl=ur#ubuntu_1604_cuda_110
except 19th line
`sudo apt-get install --no-install-recommends nvidia-driver-450`
due to
https://github.com/tensorflow/tensorflow/issues/47402
instead of it 
`sudo apt-get install --no-install-recommends nvidia-450`
And
`sudo apt-get update --allow-unauthenticated` before 2nd line
due to
`W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/InRelease  Could not resolve host: developer.download.nvidia.com`

**Comment by amahendrakar** [comment]
@GrigoriiTarasov,
As mentioned in [#47402](https://github.com/tensorflow/tensorflow/issues/47402#issuecomment-786553342), except for the `sudo apt-get install --no-install-recommends nvidia-driver-450` command, I was able to install CUDA without any issues. 

Could you please skip that particular command and let us know if you are still facing the same issue. Thanks!

**Comment by GrigoriiTarasov** [comment]
@amahendrakar 
I really appreciate your help. 
Yes  if purge, remove and rm all nvidia and cuda and follow guide without nvidia-driver-450 and without reboot those time no login stuck,
