### ISSUE TITLE
Different outputs from GradientTape and CropAndResizeGradImage 

### ISSUE THREAD

**Issue by Verma-Rajat** [tensorflow/tensorflow#47407]
**System information**
== tensorflow installed from info ==================
Name: tensorflow
Version: 2.4.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/user/.venv/lib/python3.6/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 8, 'final', 0)

**Describe the current behavior**
I am calculating gradients using GradientTape.gradient() and comparing those against CropAndResizeGradImage().

**Describe the expected behavior**
This check passes for some configurations (like one given on https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize#example) not always.

**Standalone code to reproduce the issue**
```
import numpy as np
import tensorflow as tf

def test_crop_and_resize(BATCH_SIZE=1, NUM_BOXES=41, IMAGE_DIM=15, CHANNELS=6, CROP_SIZE=8):

    image = tf.random.normal(shape=(BATCH_SIZE, IMAGE_DIM, IMAGE_DIM, CHANNELS) )
    boxes = tf.random.uniform(shape=(NUM_BOXES, 4))

    box_indices = tf.random.uniform(shape=(NUM_BOXES,), minval=0, maxval=BATCH_SIZE, dtype=tf.int32)

    with tf.GradientTape() as g:
        g.watch(image)
        output = tf.image.crop_and_resize(image, boxes, box_indices, (CROP_SIZE, CROP_SIZE))

    grad_in = tf.random.normal(output.shape)
    grad_out = g.gradient(output, image, grad_in)
    grad_out_raw = tf.raw_ops.CropAndResizeGradImage(grads=grad_in, boxes=boxes, box_ind=box_indices, image_size=image.shape, T=tf.float32, method='bilinear')
    np.testing.assert_array_equal(grad_out.numpy(), grad_out_raw.numpy())

test_crop_and_resize()
```

```
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 962 / 1350 (71.3%)
E       Max absolute difference: 3.6710215
E       Max relative difference: 320.43555
E        x: array([[[[ 4.556600e-01,  3.979062e-01,  1.036789e-01,  4.944029e-01,
E                  2.423330e-01,  1.300183e-01],
E                [ 5.906850e-01,  3.972412e-01,  2.205431e-01,  1.333644e+00,...
E        y: array([[[[ 4.556600e-01,  3.979062e-01,  1.036789e-01,  4.944029e-01,
E                  2.423330e-01,  1.300183e-01],
E                [ 5.906850e-01,  3.972412e-01,  2.205431e-01,  1.333644e+00,...
```

**Comment by Saduf2019** [comment]
@Verma-Rajat 
I ran the code and do not face any error as reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/50fab505fc9ba2bdbb07a48ec0edf3a1/untitled552.ipynb#scrollTo=cPgBtJFj-1MP)

**Comment by Verma-Rajat** [comment]
Hmm, in your gist, I don't see test_crop_and_resize() getting invoked.

**Comment by Verma-Rajat** [comment]
One interesting thing is on my local system with 'tf-nightly' I see mismatches of larger magnitude.
```
E       Mismatched elements: 947 / 1350 (70.1%)
E       Max absolute difference: 3.3557742
E       Max relative difference: 114.614235
```

While on jupyter notebook, they are of very small magnitude.
```
Mismatched elements: 501 / 1350 (37.1%)
Max absolute difference: 2.3841858e-06
Max relative difference: 5.073249e-05
```

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and tf-nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/66fa2cb4ec7f25013f81c209b3c887a3/untitled554.ipynb).

**Comment by sushreebarsa** [comment]
I tried this issue in TF 2.5 version ,please check this [gist](https://colab.sandbox.google.com/gist/googly789/b214b35979d30a09ff7e6ecdd3b60ddc/untitled93.ipynb#scrollTo=NKg1RPvq955B)...Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/1ff870a1087c225a03f5ca4b7a396e31/untitled167.ipynb?authuser=1)..Thanks!

**Comment by sachinprasadhs** [comment]
I see `Max absolute difference: 2.861023e-06` and `Max relative difference: 0.00034471` in Tensorflow 2.8, which is very small fraction. Could you please confirm if you find this difference good enough. Thanks!
