### ISSUE TITLE
fully_connected_preloaded_var.py unexpectedly slow

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#4740]
From http://stackoverflow.com/questions/39840323/benchmark-of-howto-reading-data -- `examples/tutorials/mnist/fully_connected_feed.py` runs roughly 10x faster per step (`feed_dict`) than `examples/tutorials/mnist/fully_connected_preloaded_var.py` (TF variable with `slice_input_producer`). Looking at Timeline (attached), it seems the training is bottlenecked on QueueDequeueMany which takes 13ms
which is about 100x slower than corresponding segment on `feed_dict` example [timeline]((https://github.com/tensorflow/tensorflow/files/507483/timeline.feed.json.zip)
). Also, the timing taken by `QueueDequeueMany` scales linearly with batch-size. IE, increasing batch-size to 200 makes it take 22ms.

[timeline.var.json.zip](https://github.com/tensorflow/tensorflow/files/507476/timeline.var.json.zip)

**Comment by tatatodd** [comment]
Let's consolidate this to #4732, and follow-up on that issue.  Thanks!
