### ISSUE TITLE
Changes to MklConvFwdPrimitiveFactory to support Arm Compute Library backend

### ISSUE THREAD

**Issue by alenik01** [tensorflow/tensorflow#47415]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
At the moment MklConvFwdPrimitiveFactory reuses already created oneDNN primitives, stored in the vector `fwd_primitives`, with the help of [GetConvFwd](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.cc#L401-L404) function which creates a key from convolution parameters stored in MklConvFwdParams and compares this key with the keys of existing primitives. However, when oneDNN is built with [Arm Compute Library](https://github.com/ARM-software/ComputeLibrary) (ACL, see also oneDNN [build options](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html)) there is specific requirement to create a separate primitive per constant weights tensor, this is a restriction implied by ACL code design which does not allow to use primitive caching mechanism in MklConvFwdPrimitiveFactory as it is. The solution may be to add a new entry, `void* filter_address`, to [MklConvFwdParams](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.cc#L58-L93) struct and to include the address of weights to the key in [CreateKey](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.cc#L361-L399) function:

    ...
    key_creator.AddAsKey(convFwdDims.filter_dims);
    #ifdef DNNL_AARCH64_USE_ACL
    key_creator.AddAsKey(convFwdDims.filter_address);
    #endif
    key_creator.AddAsKey(convFwdDims.bias_dims);
    ...

**Will this change the current api? How?**
The only API change is the addition of a new field to [CreateKey](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.cc#L361-L399) and [MklConvFwdParams](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.cc#L58-L93) in `mkl_conv_ops.cc`, this is related to the limitations of ACL which is designed to create a separate primitive per weights tensor.

**Who will benefit with this feature?**
The users who run inference regime with TensorFlow on AArch64-based machines.

**Any Other info.**
This Issue is raised mainly to get feedback from maintainers of the oneDNN to TensorFlow integration.

**Comment by alenik01** [comment]
Please have a look, @agramesh1

**Comment by agramesh1** [comment]
> Please have a look, @agramesh1

 Adding @gzmkl from Intel-TF team who can help.

**Comment by alenik01** [comment]
Closed due to the raised PR.
