### ISSUE TITLE
Pass for Dialect conversion from Tflite to TF  

### ISSUE THREAD

**Issue by dinkdeep** [tensorflow/tensorflow#47427]
Does there exists a Pass that can take back for Dialect conversion from Tflite to TF, TFlite->TF
We need something which preserves the quantization info generated during Tflite and detours back to TF where we can lower it down to HLO and Linalg thereon.
We don't need a new Dialect but just a Pass that can visit the Tflite IR and reconvert it back to TF getting back the Quantization info.
                CustomPass
TF->TFlite->TF->HLO->Linalg
What would be the other available ways to achieve this.

**Comment by abattery** [comment]
Thanks for filing a feature request. We do not have such feature yet.

**Comment by dinkdeep** [comment]
Thanks @abattery so as of now what are the alternatives we can have for this I mean to say how do we go about if we need to get it to happen.

**Comment by abattery** [comment]
See also https://google.github.io/iree/design-roadmap#quantization I don't know good answers on this. CCing @liufengdb
