### ISSUE TITLE
conflict numpy version between tensorflow and tf-nighty

### ISSUE THREAD

**Issue by hoaquocphan** [tensorflow/tensorflow#47422]
When I install tf-nighty as below command:
`pip3 install tf-nightly`

the error appear as below:

```
Requirement already satisfied: zipp>=0.5 in /home/hoaphan/.local/lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tb-nightly~=2.4.0.a->tf-nightly) (3.4.0)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.5
    Uninstalling numpy-1.18.5:
      Successfully uninstalled numpy-1.18.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5
```
this mean:
the tensorflow requires numpy <1.19.0
but the tf-nighty requires numpy 1.19.5

so I cannot install tensorflow and tf-nighty at same time,
so please help me solve this issue.

**Comment by amahendrakar** [comment]
@hoaquocphan,
TF v2.3.2 requires `numpy >= 1.16.0, < 1.19.0`, whereas for TF v2.4 and the latest TF-nightly the required version is `numpy~=1.19.2`.

In this case, I'd suggest you to install **`numpy v1.19.2`**, as it is compatible with the latest stable version of TensorFlow i.e. v2.4.1.



> so I cannot install tensorflow and tf-nighty at same time,

Also, you can only import any one release of TensorFlow in the script. So, I'd recommend using separate virtual environments for each version. 

Thanks!

**Comment by mihaimaruseac** [comment]
Since tf-nightly and tensorflow use the same code, you should **never** install both in the same environment. Usually, the latest one overrides most of the other. This is the way pip works and TF can do nothing in this case. That's why you should use `venv`/`virtualenv`.
