### ISSUE TITLE
NotFoundError: It shows libcudart.so.8.0, but I am using CUDA 10.0.

### ISSUE THREAD

**Issue by hitobito2009** [tensorflow/tensorflow#47421]
Hello everyone.
I wanted to use TensorFlow 1.13.1, so I installed it in the following environment.
-----system information-----
OS:Ubuntu18.04.5 64bit
CPU:Intel Core  i7-10700 @2.90Ghz x 16
RAM:16GB
GPU:Gefoce RTX2060
CUDA:10.0.130
cuDNN:7.4
GPU driver:460.32.03
python2.7
-----------------------------------

-----The following error message will be displayed-----
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory
-------------------------------------------------
The TensorFlow website describes it as compatible with Python 2.7, 3.3 to 3.7 GCC 4.8 Bazel 0.19.2 cuDNN7.4 CUDA10.0. Why am I being suggested a CUDA 8.0 environment?
I have tried to install other versions of TensorFlow, but they all give me the same error.
Can someone please help me?
Thank you

**Comment by Saduf2019** [comment]
@hitobito2009 
Is there any particular reason for using tf 1.x, as there is no support for 1.x please upgrade to 2.x and let us know if you face any issues.

You may also refer to similar error issues: [link](https://github.com/tensorflow/tensorflow/issues/5343), [link](https://stackoverflow.com/questions/43162667/importerror-libcudart-so-8-0-cannot-open-shared-object-file-no-such-file-or-d), [link2](https://github.com/tensorflow/tensorflow/issues/8900)
