### ISSUE TITLE
Failed to run models with libtensorflow_jni and tensorflow text together

### ISSUE THREAD

**Issue by liyinhgqw** [tensorflow/tensorflow#47431]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version:  n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc7
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When using [libtensorflow_jni.so](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/BUILD#L437) with [tensorflow text](https://github.com/tensorflow/text), it crashes.

Same issue: https://github.com/tensorflow/java/issues/82

**Any other info / logs**
```
2021-02-17 19:20:45.283001: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at wordpiece_kernel.cc:204 : Invalid argument: Trying to access resource using the wrong type. Expected N10tensorflow6lookup15LookupInterfaceE got N10tensorflow6lookup15LookupInterfaceE
```

**Comment by amahendrakar** [comment]
@liyinhgqw,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!
