### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session' with tensorflow 2.4.1

### ISSUE THREAD

**Issue by slim-hmidi** [tensorflow/tensorflow#47442]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **windows 10**
- TensorFlow installed from (source or binary): installed from source
- TensorFlow version (use command below): **2.4.1**
- Python version: **3.8.5**
- CUDA/cuDNN version: Cuda 11.2/11.1
- GPU model and memory: **Intel(R) UHD Graphics 630
NVIDIA GeForce GTX 1050**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.4.0-49-g85c8b2a817f 2.4.1

**Describe the current behavior**

I installed the tensorflow-gpu:
```
conda create -n tensorflow-gpu
activate tensorflow-gpu
pip install tensorflow-gpu

activate tensorflow-gpu

python
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

I got this error: AttributeError: module 'tensorflow' has no attribute 'Session'
```

**Describe the expected behavior**

The Session() should be executed correctly.

**Comment by amahendrakar** [comment]
@slim-hmidi,
`tf.Session` is used in TensorFlow 1.x and has been deprecated in TensorFlow 2.x. In Tensorflow 2.x, eager execution is enabled by default, thus eliminating the need for Sessions.

For more information, please take a look at similar issues [#34658](https://github.com/tensorflow/tensorflow/issues/34658#issuecomment-559511245) and [#18538](https://github.com/tensorflow/tensorflow/issues/18538
). Thanks!
