### ISSUE TITLE
Quantize for pooling op

### ISSUE THREAD

**Issue by yisongsong** [tensorflow/tensorflow#47447]
The int8 pooling(avg and max) does not have rescale because operators have the same scale and zero point for
input and output tensors. 
I'm wondering how to keep same scale, since distributions for different for intput and output tensors after max or avg operation.
![image](https://user-images.githubusercontent.com/19774920/109381833-97a03600-7917-11eb-8d9d-c87d2d6be964.png)

**Comment by Saduf2019** [comment]
@yisongsong 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced], also please share  data in text format its easier to search.
