### ISSUE TITLE
how to set C++ standard version for tensenflow as another bazel project dependency

### ISSUE THREAD

**Issue by xiedeacc** [tensorflow/tensorflow#47456]
**System information**
- ubuntu20.04
- TensorFlow version:2.4.0
- Python version:3.8
- Bazel version (if compiling from source):3.7.2
- GCC/Compiler version (if compiling from source):9.3

**Describe the problem**
my project depend on tensorflow, compile tensorflow need std=c++14 and above, I set --cxxopt="-std=c++14" in bazel build command for my project, but this option doesn't work for tensorflow repository, I notice -std=c++14 effective for my own project and some other external repository

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
external/org_tensorflow/tensorflow/core/platform/default/port.cc:360:46: error: could not convert '{9223372036854775807, 9223372036854775807}' from '<brace-enclosed initializer list>' to 'tensorflow::port::MemoryInfo'
  360 |   MemoryInfo mem_info = {INT64_MAX, INT64_MAX};
      |                                              ^
      |                                              |
      |                                              <brace-enclosed initializer list>

**Comment by amahendrakar** [comment]
@xiedeacc,
In order to expedite the trouble-shooting process, could you please provide the the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by xiedeacc** [comment]
> @xiedeacc,
> In order to expedite the trouble-shooting process, could you please provide the the exact sequence of commands / steps that you executed before running into the problem. Thanks!
@amahendrakar, I will provide a small project to reproduce this problem, need a few days(sorry for my busy work)

**Comment by xiedeacc** [comment]
copy .tf_configure.bazelrc and .bazelrc from  tensorflow root directory to my own project resolved this problem
