### ISSUE TITLE
Error "failed to connect to all addresses" when iterating dataset on TPU with Colab or Kaggle

### ISSUE THREAD

**Issue by StephKua** [tensorflow/tensorflow#47459]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I'm currently testing out this example [EfficientDet_TPU](https://www.kaggle.com/davidtong/efficientdet-tpu-train-1-epoch-in-4-min)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle and Google Colab
- TensorFlow version (use command below): 2.4
- Python version: 3.7

**Describe the current behavior**
Unable to iterate dataset
![Screenshot from 2021-02-28 16-35-06](https://user-images.githubusercontent.com/19550237/109412442-f8e10b80-79e2-11eb-9822-c07aa298818a.png)

**Describe the expected behavior**
Able to iterate dataset

**Standalone code to reproduce the issue**
 You can directly try this example, the tfrecords is provided as well. [EfficientDet_TPU](https://www.kaggle.com/davidtong/efficientdet-tpu-train-1-epoch-in-4-min)

**Other info / logs** 
`UnavailableError                          Traceback (most recent call last)
<ipython-input-33-15ac5583c702> in <module>
----> 1 for batch_x, (batch_regression, batch_classification) in train_dataset_encode:
      2     print(batch_x)
      3     break

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in __next__(self)
    745   def __next__(self):
    746     try:
--> 747       return self._next_internal()
    748     except errors.OutOfRangeError:
    749       raise StopIteration

/opt/conda/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py in _next_internal(self)
    737         return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
    738       except AttributeError:
--> 739         return structure.from_compatible_tensor_list(self._element_spec, ret)
    740 
    741   @property

/opt/conda/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    117         if type is None:
    118             try:
--> 119                 next(self.gen)
    120             except StopIteration:
    121                 return False

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2114     finally:
   2115       ctx.executor = executor_old
-> 2116       executor_new.wait()
   2117 
   2118 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/executor.py in wait(self)
     67   def wait(self):
     68     """Waits for ops dispatched in this executor to finish."""
---> 69     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     70 
     71   def clear_error(self):

UnavailableError: failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1614500451.196304845","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1614500451.108464009","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
`

**Comment by sayakpaul** [comment]
Related issues:
* https://github.com/tensorflow/tensorflow/issues/39122
* https://github.com/tensorflow/tensorflow/issues/39719
* https://github.com/tensorflow/tensorflow/issues/38762

**Comment by StephKua** [comment]
> Related issues:
> 
> * #39122
> * #39719
> * #38762

@sayakpaul  I'm currently using GCS Bucket and still facing the same error. Based on the related issues, I couldn't really get a proper solution for this problem.

**Comment by sayakpaul** [comment]
So, if you are using `tf.py_function` inside your data loader chances are likely that it is causing the issue. So, in that case, you might want to apply your `tf.py_function` related functionalities to your data, serialize it as shards of TFRecords inside your GCS Bucket and then load them during training time.

**Comment by amahendrakar** [comment]
@StephKua,
Please take a look at @sayakpaul's comment above and let us know if this is still an issue. Thanks!
