### ISSUE TITLE
Tensorflow Addons connected components not working properly

### ISSUE THREAD

**Issue by jeball** [tensorflow/tensorflow#47451]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda compilation tools, release 10.1, V10.1.243
- GPU model and memory: GEForce GTX 1080 Ti, 11264 MB Dedicated Video Memory (I'm using CPU)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TFA connected components should produce 2 components with the attached script. It is not.

**Describe the expected behavior**
TFA result should show same number of components as Scipy.ndimage.measurements.label, as claimed in the documentation

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

"""
    TFA Addons Connected Components check

    Using:
    TensorFlow 2.4.0
    Python 3.8.5
    TFA 0.12.1
    Scipy 1.6.1
"""

import tensorflow
import numpy as np
import tensorflow_addons as tfa
import matplotlib.pyplot as plt
import scipy.ndimage.measurements as meas

with tensorflow.device('/CPU:0'):

    M = 500
    img = np.zeros((M, M))

    # One square
    top = 50
    bottom = 270
    left = 300
    right = 450
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1

    # Second one
    top = 100
    bottom = 150
    left = 200
    right = 250
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1

    # Convert image to tensor
    img = tensorflow.convert_to_tensor(img)
    imgtf = tensorflow.expand_dims(img, -1)

    # Connected components with TFA
    d_img_tfa = tfa.image.connected_components(imgtf).numpy()

    # Plot it
    plt.figure()
    plt.title('TFA Connected Components Image')
    _ = plt.imshow(d_img_tfa)
    plt.show(block=False)

    # Connected components with scipy
    d_img_scipy, _ = meas.label(imgtf)

    # Count number of non-background components (subtract 1 for background)
    num_comp_tfa = np.unique(d_img_tfa.flatten()).size - 1
    num_comp_scipy = np.unique(d_img_scipy.flatten()).size - 1

    # These images should be the same
    print("\nTFA connected components has %d components." % num_comp_tfa)
    print("Scipy connected components has %d components.\n" % num_comp_scipy)

    # Plot
    plt.figure()
    plt.title('Scipy Connected Components Image')
    _ = plt.imshow(d_img_scipy)
    plt.show(block=True)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@jeball 
I ran the code shared and face a different error, please refer to this [gist here](https://colab.sandbox.google.com/gist/Saduf2019/d5326e86b8bd3905ab35163d41e20189/untitled554.ipynb).

**Comment by jeball** [comment]
Remove the plot commands – the print statements will show different numbers. Alternately just squeeze the last dimension out.

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image002.png@01D70E6E.5D537160]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by jeball** [comment]
I have made the changes in the notebook. Code runs now.

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image002.png@01D70E6F.8BE86160]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by jeball** [comment]
Not sure changes get saved?

Add these lines in

d_img_tfa = np.squeeze(d_img_tfa)

and

d_img_scipy = np.squeeze(d_img_scipy)

just before the plots.

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image002.png@01D70E6F.C6A1A500]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by Saduf2019** [comment]
@jeball 
I have added the two lines as suggested but face the same [error](https://colab.research.google.com/gist/Saduf2019/f038f646736a2ddf5bba2d995f97e193/untitled554.ipynb), please share a colab gist with the error reported.

**Comment by jeball** [comment]
Hello support,

The lines were not there?

Please install TF 2.4, not a nightly build. TFA does not seem compatible to this version.
Please use the commands below.

pip install tensorflow==2.4
pip install tensorflow-addons[tensorflow]

The script is shown below.


""
    TFA Addons Connected Components not working properly

    Using:
    TensorFlow 2.4.0
    Python 3.8.5
    TFA 0.12.1
    Scipy 1.6.1

    To install:
    pip install tensorflow==2.4
    pip install tensorflow-addons[tensorflow]

"""


import tensorflow as tf
import numpy as np
import tensorflow_addons as tfa
import matplotlib.pyplot as plt
import scipy.ndimage.measurements as meas


with tf.device('/CPU:0'):

    M = 500
    img = np.zeros((M, M))

    # One square
    top = 50
    bottom = 270
    left = 300
    right = 450
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1

    # Second one
    top = 100
    bottom = 150
    left = 200
    right = 250
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1

    # Convert image to tensor
    img = tf.convert_to_tensor(img)
    imgtf = tf.expand_dims(img, -1)

    # Connected components with TFA
    d_img_tfa = tfa.image.connected_components(imgtf).numpy()

    # Remove last dimension and convert to numpy matrix
    d_img_tfa = tf.squeeze(d_img_tfa, axis=-1).numpy()

    # Plot it
    plt.figure()
    plt.title('TFA Connected Components Image')
    _ = plt.imshow(d_img_tfa)
    plt.show(block=False)

    # Connected components with scipy
    d_img_scipy, _ = meas.label(imgtf)
    d_img_scipy = tf.squeeze(d_img_scipy, axis=-1).numpy()

    # Count number of non-background components (subtract 1 for background)
    num_comp_tfa = np.unique(d_img_tfa.flatten()).size - 1
    num_comp_scipy = np.unique(d_img_scipy.flatten()).size – 1



John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image003.png@01D70F38.96F12410]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by jvishnuvardhan** [comment]
@jeball Looks like this is more related to `tf-addons` repo. Can you please open this issue in [tf-addons](https://github.com/tensorflow/addons) repo and close the issue here. Thanks!

**Comment by jeball** [comment]
Will close this one. Thanks.

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image002.png@01D711D8.89671000]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>
