### ISSUE TITLE
how to Training .TextGrid file by tensorflow

### ISSUE THREAD

**Issue by UEBoy2019** [tensorflow/tensorflow#47468]
now, i have get some audio label file , that  read .wav file and use Annotate -TextGrid(sentence) button operator by Praat tool;
open file  :

`File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0 
xmax = 17.275351473922903 
tiers? <exists> 
size = 1 
item []: 
    item [1]:
        class = "IntervalTier" 
        name = "silences" 
        xmin = 0 
        xmax = 17.275351473922903 
        intervals: size = 19 
        intervals [1]:
            xmin = 0 
            xmax = 1.9536757369614515 
            text = "silent" 
        intervals [2]:
            xmin = 1.9536757369614515 
            xmax = 3.4176757369614514 
            text = "sounding" 
        intervals [3]:
            xmin = 3.4176757369614514 
            xmax = 4.281675736961452 
            text = "silent" 
        intervals [4]:
            xmin = 4.281675736961452 
            xmax = 5.081675736961452 
            text = "sounding" `

---------
but  i do not how to use the file with tensorflow , 
give me a dir,   3Q;

**Comment by Saduf2019** [comment]
@UEBoy2019 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
