### ISSUE TITLE
RuntimeError: Mixing different tf.distribute.Strategy objects while using tf.distribute.MirroredStrategy()

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#47466]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04)
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): 1.15
- Python version:3.6.9
- CUDA/cuDNN version: 10
- GPU model and memory: TitanXP

TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`: v1.15.4-39-g3db52be 1.15.

**Describe the current behavior**
Referring to : https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py, I was trying to create a code and also converting it to multi-GPU with tf.distribute.MirroredStrategy(). The code works with out tf.distribute.MirroredStrategy() in single Titan XP, but once I use the below code its shows error as shown below. 
**Describe the expected behavior**
Using the tf.distribute.MirroredStrategy()

`strategy=tf.distribute.MirroredStrategy()
    with strategy.scope():
           model....
           model.compile`

The above structure should run with multi-gpu

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Referring to https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L107, replaced with the above code. 

But error `RuntimeError: Mixing different tf.distribute.Strategy objects: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7f36a44f72e8> is not <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7f36247d0128>`

**Comment by amahendrakar** [comment]
@rrklearn2020,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by rrklearn2020** [comment]
Code was written in TF1.13 and currently works with TF1.15 (Stable version). We tried to convert to TF2.x, starting with the 'Automatic conversion script' and trying make changes for each errors. But not successful. Request for hints to solve the issue in TF1.15 version for using distribute.MirroredStrategy().

**Comment by amahendrakar** [comment]
@rrklearn2020,
Could you please share the Python script / notebook you are running, so that we can reproduce the issue on our end. Thanks!
