### ISSUE TITLE
unable to train model by using TPU(free TPU)

### ISSUE THREAD

**Issue by halhwadi** [tensorflow/tensorflow#47460]
I have prepared pipe line to train x-rays image classification model, train dataset is not balanced so did balance it by using resampling methods see the below link for more information:
https://www.tensorflow.org/guide/data#resampling

please see the error msg I got when fit the model:
_""UnavailableError: 2 root error(s) found.
  (0) Unavailable: Socket closed
  (1) Unavailable: Unable to find a context_id matching the specified one (12465293436922014039). Perhaps the worker was restarted, or the context was GC'd?
0 successful operations.
0 derived errors ignored._

Please advise?

**Comment by amahendrakar** [comment]
@halhwadi,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
