### ISSUE TITLE
Suspected duplicate code in resize_bilinear_op.cc

### ISSUE THREAD

**Issue by CyangXu** [tensorflow/tensorflow#47464]
I suspect these two code blocks are doing very similar tasks and can potentially be merged: 

- [Code block 1](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/image/resize_bilinear_op.cc;l=254;drc=9e274c0b2ff75f64a97c9aec57aa59b030c5a01b;bpv=1;bpt=0)
- [Code block 2](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/image/resize_bilinear_op.cc;l=265-283;drc=9e274c0b2ff75f64a97c9aec57aa59b030c5a01b;bpv=1;bpt=0)

The only difference which I can notice is that the code block 1 **might** benefit from sequential cache read. But I think the compiler should assist to achieve the same efficiency for the code block 2. If so, we should merge these two blocks to eliminate duplicate code.

**Comment by CyangXu** [comment]
I can help to fix if my judgement is correct. That would be my first code contribution to TF :)

**Comment by around-star** [comment]
@ymodak I sent in a pull request which must solve this.

**Comment by CyangXu** [comment]
I expected that I could become the assignee and fixed it. Why not give a newbie an opportunity? So sad.

**Comment by ymodak** [comment]
@CyangXu Thanks for your issue. Assignee's generally facilitate the PR merging process, you may want to raise PR as an author to fix issue/add new feature. I am sorry you missed this opportunity however feel free to raise PR to address any other issue of your choice and we can help merge it. Contributions from the community are highly encouraged and welcomed. Thanks!

**Comment by CyangXu** [comment]
@ymodak Thank you for explanation!

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
