### ISSUE TITLE
Large overhead when py_function returns tuple of lists

### ISSUE THREAD

**Issue by kretes** [tensorflow/tensorflow#47470]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.8 (verified in 3.6.9 as well)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Given the code in the gist https://gist.github.com/kretes/02dc479ab7a63a8b5a559c5e7df89598 - I see that the version of the `py_function` that return a tuple of lists with data is introducing some large overhead on top of the actual operation. It takes ~10 seconds to finish the iteration in this code, while the other two versions (returning just tuple, or returning tuple of ndarrays) is done within ~2 secs.

**Describe the expected behavior**
There should be no difference between returning a tuple with data, or wrapping them up with one more nesting level.

**Standalone code to reproduce the issue**
https://gist.github.com/kretes/02dc479ab7a63a8b5a559c5e7df89598 - code and logs from run on my side. I verified this in multiple installations, the recent one in jupyter/tensorflow docker image

**Comment by kretes** [comment]
This might be a duplicate of https://github.com/tensorflow/tensorflow/issues/44555

**Comment by AdityaKane2001** [comment]
Hi,
I'm not sure if this is correct, but hear me out. As stated [here](https://www.tensorflow.org/guide/function#tracing), and [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map)

> Note that irrespective of the context in which map_func is defined (eager vs. graph), tf.data traces the function and executes it as a graph. To use Python code inside of the function you have a few options: ...

Thus, the map function traces the graphs if the input/output has a python object. numpy arrays work similar to Tensors and result in similar performance when a graph is traced.
 But, as mentioned in your last call,

> In [10]: %%time
    ...: for _ in make_ds(return_list):
    ...:     pass
    ...: 
CPU times: user 11.4 s, sys: 345 ms, total: 11.7 s
Wall time: 11.7 s

Returning the list causes the function to retrace the graph every time and thus the time drastically increases.
I think the solution to issue 44555 is on similar lines.  Prefer to continue discussion there.
Hope this helps.
