### ISSUE TITLE
Building tensorflow_cc target (cpu-only) from scratch with xla failing (TF1.15.5)

### ISSUE THREAD

**Issue by ksangeet9ap** [tensorflow/tensorflow#47486]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 1.15
-   **Python version**: 3.6
-   **Bazel version (if compiling from source)**: 0.26.1
-   **GCC/Compiler version (if compiling from source)**: 7.5.0 (set using --action env GCC_HOST_COMPILER_PATH)

### Source code / logs
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/compiler/xla/service/generic_transfer_manager.cc: In member function 'virtual tensorflow::Status xla::GenericTransferManager::WriteSingleTupleIndexTable(stream_executor::Stream*, absl::Span<const stream_executor::DeviceMemoryBase>, const xla::Shape&, stream_executor::DeviceMemoryBase*)':
tensorflow/compiler/xla/service/generic_transfer_manager.cc:56:47: error: expected ',' before '{' token
   stream->ThenDoHostCallback([element_pointers{std::move(element_pointers)}]() {
                                               ^
tensorflow/compiler/xla/service/generic_transfer_manager.cc:56:47: error: expected identifier before '{' token
Target //tensorflow:tensorflow_cc failed to build
INFO: Elapsed time: 1827.953s, Critical Path: 236.32s
INFO: 5317 processes: 5317 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by Saduf2019** [comment]
@ksangeet9ap 
We see that you are using a old version of tenor flow and there is no support for tf 1.x, can you please upgrade to 2,x and verify you meet the [requirements](https://www.tensorflow.org/install/source).
