### ISSUE TITLE
Configure fail when install from source code

### ISSUE THREAD

**Issue by Lustralisk** [tensorflow/tensorflow#4748]
I Installed with following settings: centOS 7, CUDA 7.5, cudnn v4, python 2.7

After I filling in the configurations using

`./configure`
and I got this error
```
ERROR: /home/[...]/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /home/[...]/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished
```

When I tried with v0.9 there is no such problem. And I don't need those android features.

Anybody encountered the same problem? How can I fix this issue?

**Comment by hlzz** [comment]
+1 got the same problem when build it on centos

**Comment by Lustralisk** [comment]
I don't know whether something wrong with the java environment

**Comment by Lustralisk** [comment]
Guess what, using bazel with version 3.1.0 can solve the problem. Bazel team should really think of their downward compatibility
