### ISSUE TITLE
flatbuffers download:

### ISSUE THREAD

**Issue by mushtaqsyed** [tensorflow/tensorflow#47485]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10:
- TensorFlow installed from (source or binary):Binary
- TensorFlow version: 3 (Lite)
- Python version: 3.9
- Installed using virtualenv? pip? conda?: cloned it. from github

**Describe the problem**
 flatbuffers download is failing.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

$ make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2021-03-01 22:41:11--  http://mirror.tensorflow.org/github.com/google/flatbuffers/archive/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip
Resolving mirror.tensorflow.org... 172.217.6.48
Connecting to mirror.tensorflow.org|172.217.6.48|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1760478 (1.7M) [application/zip]
Saving to: `/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip'

     0K .......... .......... .......... .......... ..........  2%  526K 3s
    50K .......... .......... .......... .......... ..........  5%  855K 2s
   100K .......... .......... .......... .......... ..........  8% 1.33M 2s
   150K .......... .......... .......... .......... .......... 11% 2.38M 2s
   200K .......... .......... .......... .......... .......... 14%  612K 2s
   250K .......... .......... .......... .......... .......... 17% 63.8M 1s
   300K .......... .......... .......... .......... .......... 20%  444K 2s
   350K .......... .......... .......... .......... .......... 23% 16.7M 1s
   400K .......... .......... .......... .......... .......... 26% 1.03M 1s
   450K .......... .......... .......... .......... .......... 29% 1.62M 1s
   500K .......... .......... .......... .......... .......... 31%  340K 1s
   550K .......... .......... .......... .......... .......... 34% 89.0M 1s
   600K .......... .......... .......... .......... .......... 37%  106M 1s
   650K .......... .......... .......... .......... .......... 40% 1.37M 1s
   700K .......... .......... .......... .......... .......... 43% 4.26M 1s
   750K .......... .......... .......... .......... .......... 46%  697K 1s
   800K .......... .......... .......... .......... .......... 49% 1.48M 1s
   850K .......... .......... .......... .......... .......... 52% 1.04M 1s
   900K .......... .......... .......... .......... .......... 55% 1.81M 1s
   950K .......... .......... .......... .......... .......... 58% 1.79M 1s
  1000K .......... .......... .......... .......... .......... 61% 1.73M 1s
  1050K .......... .......... .......... .......... .......... 63% 1.44M 1s
  1100K .......... .......... .......... .......... .......... 66% 1.31M 0s
  1150K .......... .......... .......... .......... .......... 69% 1.58M 0s
  1200K .......... .......... .......... .......... .......... 72% 1.40M 0s
  1250K .......... .......... .......... .......... .......... 75% 1.70M 0s
  1300K .......... .......... .......... .......... .......... 78%  525K 0s
  1350K .......... .......... .......... .......... .......... 81% 71.7M 0s
  1400K .......... .......... .......... .......... .......... 84% 2.75M 0s
  1450K .......... .......... .......... .......... .......... 87% 1.14M 0s
  1500K .......... .......... .......... .......... .......... 90%  888K 0s
  1550K .......... .......... .......... .......... .......... 93% 6.11M 0s
  1600K .......... .......... .......... .......... .......... 95% 1.66M 0s
  1650K .......... .......... .......... .......... .......... 98%  892K 0s
  1700K .......... .........                                  100% 2.13M=1.4s

2021-03-01 22:41:13 (1.20 MB/s) - `/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip' saved [1760478/1760478]

tensorflow/lite/micro/tools/make/bash_helpers.sh: line 29: /tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip: No such file or directory
tensorflow/lite/micro/tools/make/Makefile:525: *** Something went wrong with the flatbuffers download: Bad checksum. Expected: aa9adc93eb9b33fa1a2a90969e48baee, Got: .  Stop.

The file dca12522a9f9e37f126ab925fd385c807ab4f84e.zip does exist under c:/tmp/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip

**Comment by amahendrakar** [comment]
@mushtaqsyed,
Please go through these comments from similar issues [#46916](https://github.com/tensorflow/tensorflow/issues/46916#issuecomment-774973928) and [#46936](https://github.com/tensorflow/tensorflow/issues/46936#issuecomment-776585339) and check if it helps. Thanks!

**Comment by mushtaqsyed** [comment]
Hi Abhilash:
These links,  #46916
<https://github.com/tensorflow/tensorflow/issues/46916#issuecomment-774973928>
 and #46936
<https://github.com/tensorflow/tensorflow/issues/46936#issuecomment-776585339>,
did not help. The impression that I get from these is that TFLite is not
supported under Windows 10. Is this correct?
I am following the book TiniML, and that does not say so. Could you please
elaborate
Thanks a lot!
Cheers,
Mushtaq

**Comment by mushtaqsyed** [comment]
Hi Abhilash:
Any feedback?
I forgot to mention in my first post that I was running the make command in
a cygwin terminal as an administrator. I have also tried the same in a
MINGW64 as administrator and got the same error message.
Thanks a lot!
Cheers,
Mushtaq

**Comment by sanatmpa1** [comment]
@mushtaqsyed,

Can you refer the issue #45033 and this [link](https://forums.tinyml.org/t/make-doesnt-work-on-hello-world-test-from-tinyml-book/344/5) and let us know if it helps to resolve your issue? Thanks!
