### ISSUE TITLE
rtx3090 tf2.4.1 error with single machine multi-card

### ISSUE THREAD

**Issue by jiangjing1989** [tensorflow/tensorflow#47497]
strategy is tf.distribute.MirroredStrategy, I train the model on two cards, it reports that
F tensorflow/stream_executor/cuda/cuda_driver.cc:1289] Check failed: context != nullptr success should entail non-null context.
how can I solve it?

**Comment by amahendrakar** [comment]
@jiangjing1989,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at issue [#46851](https://github.com/tensorflow/tensorflow/issues/46851) with a similar error log and check if it helps. Thanks!

**Comment by jiangjing1989** [comment]
> @jiangjing1989,
> In order to expedite the trouble-shooting process, could you please provide the following information
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary):
> * TensorFlow version (use command below):
> * Python version:
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version:
> * GPU model and memory:
> 
> along with the complete code and the dataset you are using. Thanks!

**my environment is :**
Ubuntu 18.04.5 LTS
python3.8
rtx3090
conda install cudatoolkit=11.0 
conda install cudnn=8.0.5 
pip3 install tensorflow_gpu-2.4.1-cp38-cp38-manylinux2010_x86_64.whl
pip install tfa-nightly

code address is https://github.com/jiangjing1989/asr_test/tree/master/my, the start script if train_sublm.py.

I run the code with RTX2080 successfully.

**Comment by jiangjing1989** [comment]
> Also, please take a look at issue [#46851](https://github.com/tensorflow/tensorflow/issues/46851) with a similar error log and check if it helps. Thanks!

sorr, tensorflow version is tf_nightly_gpu-2.5.0.dev20210130-cp38-cp38-manylinux2010_x86_64.whl

**Comment by jiangjing1989** [comment]
> Also, please take a look at issue [#46851](https://github.com/tensorflow/tensorflow/issues/46851) with a similar error log and check if it helps. Thanks!

sorry again, cudnn version is 11.2

**Comment by amahendrakar** [comment]
@jiangjing1989,
Currently TensorFlow is not compatible with **CUDA 11.2**. 

TF v2.4 and TF-nightly are built and tested against **CUDA 11.0**. Could you please check if you are facing the same error with **CUDA 11.0** and **cuDNN 8**. Thanks!

**Comment by jiangjing1989** [comment]
> @jiangjing1989,
> Currently TensorFlow is not compatible with **CUDA 11.2**.
> 
> TF v2.4 and TF-nightly are built and tested against **CUDA 11.0**. Could you please check if you are facing the same error with **CUDA 11.0** and **cuDNN 8**. Thanks!

Thanks. With CUDA 11.0 and cuDNN8.0.2, it run successfully.

**Comment by amahendrakar** [comment]
> Thanks. With CUDA 11.0 and cuDNN8.0.2, it run successfully.

@jiangjing1989 
Thank you for the update. Closing the issue as it is resolved.
