### ISSUE TITLE
GPUOptions C++ free(): invalid pointer

### ISSUE THREAD

**Issue by qurugou** [tensorflow/tensorflow#47492]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below):1.14
- Python version:3.6
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.0/7.4.2
- GPU model and memory: 2070 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
c++
int main()
{   
    tensorflow::Session* session;
    tensorflow::Status status;
    ConfigProto configProto;
    GPUOptions gpuOptions;

    gpuOptions.set_per_process_gpu_memory_fraction(0.5);
    configProto.set_allocated_gpu_options(&gpuOptions);
}

it will report free(): invalid pointer after the code is finished.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@qurugou 
We see that you are using an old version of tensorflow for which there is no support, please upgrade to tf 2.x and let us know in case you face any issues.
