### ISSUE TITLE
https://www.tensorflow.org/guide/estimators - HTTP Error 404: Page not Found

### ISSUE THREAD

**Issue by xcodz-dot** [tensorflow/tensorflow#47494]
Looks like this shows a 404 to me at the time of writing
https://www.tensorflow.org/guide/estimators

**Comment by amahendrakar** [comment]
@xcodz-dot,
Could you please let us know the source from where you got the link, so that we can correct it. The working link is
 
https://www.tensorflow.org/guide/estimator

Thanks!

**Comment by xcodz-dot** [comment]
It's all over this page:
https://github.com/tensorflow/estimator

**Comment by amahendrakar** [comment]
@xcodz-dot,
Thank you for reporting the issue. I've submitted a fix for the broken link in PR [#63](https://github.com/tensorflow/estimator/pull/63).

This issue will be closed once the PR is merged.

**Comment by amahendrakar** [comment]
> It's all over this page:
> https://github.com/tensorflow/estimator

@xcodz-dot,
PR [#63](https://github.com/tensorflow/estimator/pull/63) has been merged. Now the guide points to the working link.

Closing this issue as it is resolved. Please feel free to re-open if mistaken. Thanks!
