### ISSUE TITLE
-1073741795

### ISSUE THREAD

**Issue by Junaidkhan1809** [tensorflow/tensorflow#47498]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

ImportError: Traceback (most recent call last):
  File "C:\Users\Junaid\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Junaid\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Junaid\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Junaid\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Junaid\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

- first I run the command line pip install tensorflow==2.2.0
- then while importing the tensorflow it throws the above error

![image](https://user-images.githubusercontent.com/72540582/109615543-079dfe80-7b5a-11eb-82d9-9e33fd4b8909.png)

**Comment by Saduf2019** [comment]
@Junaidkhan1809 
Please verify your system meets the requirements mentioned above mentioned for you to use tensorflow.

**Comment by Junaidkhan1809** [comment]
> @Junaidkhan1809
> Please verify your system meets the requirements mentioned above mentioned for you to use tensorflow.

My machine has windows 7 64bit i3

**Comment by Junaidkhan1809** [comment]
What specification are required to run tensorflow @Saduf2019

**Comment by Saduf2019** [comment]
@Junaidkhan1809
Please click on the links given by bot above and verify [ex python 64 bit, AVX support, os 64 bit etc].

**Comment by Junaidkhan1809** [comment]
My machine is not compatible !
one last query What type of machine is required in terms of specification @Saduf2019

**Comment by Junaidkhan1809** [comment]
Thank You !
