### ISSUE TITLE
`tf.distribute.MirroredStrategy(),` but getting unbalance GPU usage

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#47503]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes, with reference.  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.6.9
- CUDA/cuDNN version: CUDA 11 and cuDNN 8
- GPU model and memory: 3 GPU's 32GB each (same GPU model)

**Describe the current behavior**
Trying to use `tf.distribute.MirroredStrategy(),` but getting unbalance GPU usage. The 1st GPU is used most of the time and other 2 GPU's are seldom used for the same code, same training instance. 

**Describe the expected behavior**
get almost uniform usage of all 3 GPU (for better performance).

**Standalone code to reproduce the issue**
https://github.com/rrklearn2020/keras-retinanet 

Running directly from the repository with tf.distribute.MirroredStrategy():
`keras_retinanet/bin/train_v2.py coco /path/to/MS/COCO`

I also tried the "tf.data.Dataset.from_generator" by adding below lines (currently not added to train_v2.py due to error)
```
train_generator=tf.data.Dataset.from_generator(train_generator)
validation_generator=tf.data.Dataset.from_generator(validation_generator)
```
But getting an error as shown below.
```
raise TypeError("`generator` must be callable.")
TypeError: `generator` must be callable.
```

 Please guide me to get almost uniform usage of all 3 GPU (for better performance).

**Comment by Saduf2019** [comment]
@rrklearn2020 
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily, or if possible share a colab gist with the issue reported.
Thanks!

**Comment by rrklearn2020** [comment]
@Saduf2019 

**Point 1:** The performance concern while using tf.distribute.MirroredStrategy(). Screenshot attached. Question: The 1st GPU is used most of the time and other 2 GPU's are seldom used for the same code, same training instance. **_How to improve the performance by having all GPU running with similar load?_**

![GPU_Use_MirroredStrategy](https://user-images.githubusercontent.com/70491128/109673025-9bb09b80-7b43-11eb-89a6-08f5fa447f3f.png)

**Point 2:** While trying to improve the performance using the "tf.data.Dataset.from_generator", its creating error (code and the error are shared before. Please inform the points to be considered while using "tf.data.Dataset.from_generator". I had checked the [https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator](url), but not very clear.

**Comment by nikitamaia** [comment]
Hi @rrklearn2020, [have you seen the GPU performance guide](https://www.tensorflow.org/guide/gpu_performance_analysis)? It might be worth trying to profile your training job to try and see what's happening on each GPU at each step.

Additionally, are you also seeing this imbalance if you remove the validation data or callbacks?

As @Saduf2019 mentioned earlier, if you can provide a simpler example I can try to reproduce this on my end.
