### ISSUE TITLE
install_pip_packages.sh specifies incompatible version combo for pylint and astroid

### ISSUE THREAD

**Issue by deven-amd** [tensorflow/tensorflow#47505]
This PR https://github.com/tensorflow/tensorflow/pull/46046 introduces what seems to be an incompatible version combination for pylint and astroid.

see this line : https://github.com/tensorflow/tensorflow/pull/46046/files#diff-c8d38bb153d3e8107f198a493594dba5a8725176bbc6069304aec7fcec2fabc6R89

The nightly TF ROCm build (which uses the `install_pip_packages.sh` script when creating the docker container), ran into the following error
```
ERROR: Cannot install astroid==2.5 and pylint==2.6.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested astroid==2.5
    pylint 2.6.2 depends on astroid<2.5 and >=2.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

The complete build log can be seen here : http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/630/console

/cc @bhack

**Comment by bhack** [comment]
I will check this constrain today

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/pull/47506

**Comment by deven-amd** [comment]
TF ROCm nightly build passed with this PR merged. Thanks @bhack for the quick response.

http://ml-ci.amd.com:21096/job/tensorflow-rocm-nightly/632/
