### ISSUE TITLE
Error when using quantization aware training with custom activation function

### ISSUE THREAD

**Issue by LucasStromberg** [tensorflow/tensorflow#47502]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Custom code

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10

- TensorFlow installed from (source or binary):
Anaconda Navigator

- TensorFlow version (use command below):
tensorflow-gpu 2.3.0

- Python version:
3.7.9

- CUDA/cuDNN version:
cudatoolkit 10.1.243
cudnn 7.6.5

- GPU model and memory:
GTX 1070 8GB

**Describe the current behavior**
I have a model with a custom activation function, ReLU6, as defined below. When using tfmot.quantization.keras.quantize_model I get the following error output:

> ValueError: Unable to clone model. This generally happens if you used custom Keras layers or objects in your model. Please specify them via `quantize_scope` for your calls to `quantize_model` and `quantize_apply`.

When simply using 'relu' I don't get this error.

Activation function:
`def _relu6(x):
    return activations.relu(x, max_value=6.0)`

Usage:
`x = Activation(_relu6)(x)`

**Describe the expected behavior**
I need to be able to quantize a model with the relu6 activation function. I am not sure how to approach this problem.

**Standalone code to reproduce the issue**
Creating any model with the custom activation function as above seems to yields this error.

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by abattery** [comment]
@ethkim could you triage this issue?

**Comment by amahendrakar** [comment]
@LucasStromberg,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by LucasStromberg** [comment]
Hi again, I was able to get around this problem by replacing my custom activation function with the tensorflow.keras.layers.ReLU(max_value=6.0) layer.

**Comment by amahendrakar** [comment]
@LucasStromberg,
Thank you for the update. Closing this issue as it is resolved. 

Please feel free to re-open if necessary. Thanks!

**Comment by debjyoti003** [comment]
How to solve this issue if one is using custom layer?
