### ISSUE TITLE
Missing documentation for bucket_by_sequence_length api

### ISSUE THREAD

**Issue by PratsBhatt** [tensorflow/tensorflow#47513]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/data/experimental/ops/grouping.py
Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):
I think `bucket_by_sequence_length` is a very important api, but it's lack of documentation example makes it usage quiet restricted to some users.
### Clear description
This API is very useful in NLP where we can batch the data efficiently keeping in mind the memory constraints that is involved. 
This API can pad the data based on the longest sequence in that particular batch in place of padding the complete dataset with a constant number.
For example, why should someone use this method? How is it useful?
As I said above it can be used for large dataset as well as small as it will reduce the padding of the dataset.
### Correct links

Is the link to the source code correct?
https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/data/experimental/ops/grouping.py
### Parameters defined
Yes
Are all parameters defined and formatted correctly?
Yes
### Returns defined
Yes
Are return values defined?
Yes
### Raises listed and defined
Yes
Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises
Yes
### Usage example
There is only one example in the nightly build that doesn't involve all the parameter such as `padded_shapes , padding_values, pad_to_bucket_boundary, no_padding, drop_remainder`. Basically it doesn't involve a close to real scenario.
Is there a usage example?
Yes, there is one example.

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?
I will be willing to contribute and I can have the PR ready within a day, as I use this API, if the other contributors agree to it. If you accept this issue, you can assign it to me.

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by PratsBhatt** [comment]
Can I work on it and provide a PR @ymodak ?

**Comment by PratsBhatt** [comment]
I have completed working on the PR and it is ready for the review @ymodak . The pull request is named "Update grouping.py".

**Comment by ymodak** [comment]
Thanks for the PR.

**Comment by PratsBhatt** [comment]
The pull request has been merged. This issue can be closed?

**Comment by ymodak** [comment]
@PratsBhatt Yes, your [PR](https://www.tensorflow.org/api_docs/python/tf/data/experimental/bucket_by_sequence_length?version=nightly) is up with tf-nightly docs. Thanks for the fix.
