### ISSUE TITLE
Estimator#export_saved_model section links to irrelevant guide or guide missing relevant section

### ISSUE THREAD

**Issue by C-Compton** [tensorflow/tensorflow#47529]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#export_saved_model
https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators

**Comment by jvishnuvardhan** [comment]
@C-Compton I agree with you. The link is misleading but the link is a more detailed guide on [Using the SavedModel format](https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators). May be we need to change from "For a detailed guide, see [SavedModel from Estimators](https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators)."  to "For a detailed guide on SavedModel, see [Using the SavedModel format](https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators)"

Please let us know if you want to contribute and update any docs through a PR. Thanks!

**Comment by PratsBhatt** [comment]
I can work on the PR. Shall I go ahead with your suggestion @jvishnuvardhan ?

**Comment by PratsBhatt** [comment]
This issue can be closed the PR has been merged. @jvishnuvardhan . Thank you.
