### ISSUE TITLE
Increase GPU memory usage in tensorflow 2.4.1 versus tensorflow 2.3.2

### ISSUE THREAD

**Issue by maunzzz** [tensorflow/tensorflow#47524]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.5
- TensorFlow installed from: tensorflow dockers _tensorflow:2.3.2-gpu_ and _tensorflow:2.4.1-gpu_
- TensorFlow version (use command below): 2.3.2 and 2.4.1
- Python version: 3.6.9
- CUDA/cuDNN version: for **2.3.2**: CUDA 10.1.243 CUDNN 7.6.4.38-1 for **2.4.1**: CUDA 11.0.3 CUDNN 8.0.4.30-1
- GPU model and memory: GeForce RTX 2070 SUPER, 7979MiB

**Describe the current behavior**
After upgrading to tensorflow 2.4.1 GPU memory consumption is increased. Training with the same batch size as for tensorflow 2.3.2 results in GPU running out of memory. 

The script below works fine when run with
`sudo docker run --rm -v ${PWD}:/data --gpus all tensorflow/tensorflow:2.3.2-gpu python3 /data/script.py`

but crashes when run with
`sudo docker run --rm -v ${PWD}:/data --gpus all tensorflow/tensorflow:2.4.1-gpu python3 /data/script.py`

When using tensorflow 2.4.1 the batch size must be lower to 3 for the script to run without crashing.

**Describe the expected behavior**
The script below should be possible to run with tensorflow 2.4.1 without crashing due to GPU running out of memory.

**Standalone code to reproduce the issue**
script.py: 
```
import numpy as np
import tensorflow as tf
from tensorflow.python.keras import Input
from tensorflow.python.keras.layers import Conv3D, Activation
from tensorflow.python.keras.models import Model


for gpu in tf.config.experimental.list_physical_devices('GPU'):
    tf.config.experimental.set_memory_growth(gpu, True)


def get_model():
    inputs = Input((100, 100, 100, 1), name='image3d')
    x = Conv3D(80, kernel_size=(3, 3, 3), padding='valid', activation='relu')(inputs)

    class_scores = Conv3D(1, kernel_size=(1, 1, 1))(x)
    out = Activation('softmax', name='out')(class_scores)

    return Model(inputs=inputs, outputs=out, name='net')


batch_size = 8

model = get_model()
x = np.empty((batch_size, 100, 100, 100, 1), dtype=np.float32)
y = np.empty((batch_size, 98, 98, 98, 1), dtype=np.float32)

model.compile('sgd', 'mse')
model.fit(x, y, batch_size=batch_size)
```

works fine when run with
`sudo docker run --rm -v ${PWD}:/data --gpus all tensorflow/tensorflow:2.3.2-gpu python3 /data/script.py`

but crashes when run with
`sudo docker run --rm -v ${PWD}:/data --gpus all tensorflow/tensorflow:2.4.1-gpu python3 /data/script.py`

When using tensorflow 2.4.1 the batch size must be lower to 3 for the script to run without crashing.

**Other info / logs** 
output when executing 
`sudo docker run --rm -v ${PWD}:/data --gpus all tensorflow/tensorflow:2.4.1-gpu python3 /data/script.py`
[trace-2.4.1.log](https://github.com/tensorflow/tensorflow/files/6075341/trace-2.4.1.log)

**Comment by amahendrakar** [comment]
@maunzzz,
I was able to run the code without any issues on both [TF v2.3](https://colab.research.google.com/gist/amahendrakar/12660c3c92cbf4f10728b05c450f116d/47524-2-3.ipynb) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/0b4fc66059bc127e630904cd1a764bc3/47524.ipynb). Please check the linked gist for reference.

To prevent the out of memory error please try setting a hard limit on the total GPU memory as shown in [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). Thanks!

**Comment by maunzzz** [comment]
Alright, thank you. What hardware did you run it on?
Setting a hard limit on the GPU helped for 2.4.1
