### ISSUE TITLE
Error while Compile to the model into TFLite model

### ISSUE THREAD

**Issue by samyon7** [tensorflow/tensorflow#47528]
I use it in google Colab

[Here is notebook link 1](https://colab.research.google.com/drive/1voMaXutl7pOcybTZKwtjSjU_5aqncBdp?usp=sharing)
[Here is notebook link 2](https://nbviewer.jupyter.org/github/samyon7/Convert_TFLite_Problem/blob/master/Untitled243.ipynb)

Was that because I used the branching model?

**Comment by abattery** [comment]
There is an uncovered op by TFLite builtin op set, tf.Selu. In such case, we recommend using the Select TF op. Please refer to https://www.tensorflow.org/lite/guide/ops_select.

You can convert your model with the following snippet:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
```

**Comment by samyon7** [comment]
> There is an uncovered op by TFLite builtin op set, tf.Selu, in your model. In such case, we recommend using the Select TF option. Please refer to https://www.tensorflow.org/lite/guide/ops_select.
> 
> You can convert your model with the following snippet:
> 
> ```
> converter = tf.lite.TFLiteConverter.from_keras_model(model)
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> tflite_model = converter.convert()
> ```

So can't we use selu?
Even though this activation is actually pretty good compared to others, except relu.
But thanks for the solution, cheers!

**Comment by abattery** [comment]
If you really want to support selu op in TFLite builtin op set, please file a new issue for the feature request. Thanks

**Comment by abattery** [comment]
Closing for now. Please re-open this if there is any other concern or file a new issue for the other request.
