### ISSUE TITLE
Model Accuracy Goes Static When Arbitrary Lines Are Added

### ISSUE THREAD

**Issue by Cnotey** [tensorflow/tensorflow#47522]
**System information**
- I have written custom code, repo link below.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 Home, build 19041.804**
- TensorFlow installed from (source or binary): source, **Anaconda3**
- TensorFlow version (use command below): **2.1.0**
- Python version: **3.7.7**
- CUDA/cuDNN version: 10.1
- GPU model and memory: EVGA Geforce GTX 1080 SC, 8GB

**Describe the current behavior**
Adding arbitrary comment and print lines above the model training function causes accuracy to become static and not improve past 0.5024.  Removing the lines allows it to train correctly.  

Please see these screenshots for a better explanation:
https://imgur.com/a/weV5mgL

**Describe the expected behavior**
Model should train correctly regardless of arbitrary lines.

**Standalone code to reproduce the issue**
repo: https://github.com/Cnotey/TF_Issue_003

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I have a hard time believing this is a TF issue, or an issue with my code.  It seems like this is a compatibility issue somehow.

**Comment by Saduf2019** [comment]
@Cnotey 
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. 
Or share a colab gist with the error reported.Thanks!

**Comment by Cnotey** [comment]
Hi Saduf. I already spent about 30 hours cutting out 1 000 lines of intellectual property to even be able to share the repo. This is the simplest form that will function.

I have not used Google Colab before but could try it. I would have ignored the issue, but it's just so weird and has persisted for nearly a year and is preventing further progress on the project.

**Comment by Cnotey** [comment]
@ymodak   Thanks for keeping this one going.  Still seems like a bug to me rather than a support request.  I'm here to answer any further questions about the issue.

**Comment by Cnotey** [comment]
@ymodak I have done some further investigation into the matter.  I am also able to mitigate the issue by changing the random seed in TF.  Is it possible that the random seed is somehow related to the number of lines in the program?

**Comment by sanatmpa1** [comment]
@Cnotey,

Can you update your tensorflow to latest stable version i.e `2.6.0` and let us know if the issue still persists? Thanks!
