### ISSUE TITLE
getting error while adding metadata to object detection tflite model

### ISSUE THREAD

**Issue by codePerfectPlus** [tensorflow/tensorflow#47523]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or GitHub SHA, if built from source): tf-nightly

### 2. Code

Reference Link- https://www.tensorflow.org/lite/convert/metadata

I am trying to add metadata into my tflite model as metadata is required for the android app. I am trying the following method but getting error.

```bash
python ./metadata_writer_for_image_classifier.py \
    --model_file=./model_without_metadata/mobilenet_v1_0.75_160_quantized.tflite \
    --label_file=./model_without_metadata/labels.txt \
    --export_directory=model_with_metadata
```

Google-Colab Link for refernce-
https://colab.research.google.com/drive/1MkPxvYWVWdygFYxDk8U-jXDBhEjsSnMa#scrollTo=q3AtK7ErmrVl

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

```bash
File "metadata_writer_for_image_classifier.py", line 176, in main
    "The model info for, {0}, is not defined yet.".format(model_basename))
ValueError: The model info for, , is not defined yet.
```

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
@lu-wang-g could you take a look at this issue?

**Comment by lu-wang-g** [comment]
Seems like model_file was not passed in successfully, i.e. it became an empty string. Please try using the full path for model_file.

You can also try the new MetadataWriter Library. Here is an example to write metadata for an ImageClassifier model:

1. Install the TFLite Support nightly Pypi package:
```
pip install tflite_support_nightly
```
2. Write metadata to the model using the following script:
```
from tflite_support.metadata_writers import image_classifier
from tflite_support.metadata_writers import writer_utils
from tflite_support import metadata

ImageClassifierWriter = image_classifier.MetadataWriter
_MODEL_PATH = <Path to the model>
_LABEL_FILE = <Path to the label file>
_SAVE_TO_PATH = "model_with_metadata.tflite"

writer = ImageClassifierWriter.create_for_inference(
    writer_utils.load_file(_MODEL_PATH), [127.5], [127.5], [_LABEL_FILE])
writer_utils.save_file(writer.populate(), _SAVE_TO_PATH)
````
3. Verify the populated metadata and associated files.
```
displayer = metadata.MetadataDisplayer.with_model_file(_SAVE_TO_PATH)
print("Metadata populated:")
print(displayer.get_metadata_json())
print("Associated file(s) populated:")
print(displayer.get_packed_associated_file_list())
```

**Comment by codePerfectPlus** [comment]
I Think It will not work in my case.  I am creating tflite model for the object detection problem and I am getting the error while writing the metadata with the above script.

```bash
ValueError: The number of output tensors (4) should match the number of output tensor metadata (1)
```

Colab:- https://colab.research.google.com/drive/1MkPxvYWVWdygFYxDk8U-jXDBhEjsSnMa#scrollTo=wrKT_tf2dYKX

**Comment by lu-wang-g** [comment]
I thought you were interested at the ImageClassification API. I've correct my previous answer for ObjectDetection. Please try it again and see if it works.

**Comment by codePerfectPlus** [comment]
@lu-wang-g yup it's working, I think it's missing in Tensorflow documentation.
Thanks for sharing the script.

**Comment by lu-wang-g** [comment]
We'll add the documentation once the full MetadataWriter Library is done. Please stay tuned.

**Comment by Saduf2019** [comment]
@codePerfectPlus 
As the request for object detection problem is resolved please move this to closed status.
