### ISSUE TITLE
working with sparse input

### ISSUE THREAD

**Issue by hoondy** [tensorflow/tensorflow#47532]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) colab
- TensorFlow installed from (source or binary): colab
- TensorFlow version (use command below): 2.4.1
- Python version: 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Sparse input works with dense and dropout layers as of v2.4.1. However, when you stack dense with dropout, it throws an error. If you try to reshape sparse input, you also get an error.

**Describe the expected behavior**
Sparse input works just like dense input.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

see [gist](https://colab.research.google.com/gist/hoondy/74b5c6cca796d0229941868b43c66592/git210303.ipynb)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

spawn from #25980

**Comment by Saduf2019** [comment]
I am able to reproduce this on tf 2.3,tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/29a944c75db2fbc56f02f682b300736c/untitled557.ipynb).

**Comment by H-Ribeiro** [comment]
I can confirm that I have the same issue when using an Con1D after input layer.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210530,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/86dad8df4e4a046afb443670bce03e48/untitled142.ipynb#scrollTo=HkzVWKaTuJiI)..Thanks !

**Comment by PeterShmukler** [comment]
simple reproduction
https://colab.research.google.com/gist/ymodak/36c744a25affa7c74147d5cccbf94140/git44970.ipynb

**Comment by chunduriv** [comment]
Here issue is with converting `Sparse_tensor` to `Dense_tensor`. Since `tf.constant` is Dense tensor, first we need to convert `Sparse_tensor` to `Dense_tensor` as given in the below code

```
import tensorflow as tf
from platform import python_version
print(python_version(), tf.version)

st = tf.SparseTensor(indices=[[4, 2], [4, 3]],
values=[10, 20],
dense_shape=[10, 5])
#tf.constant(tf.sparse.reorder(st))
dt = tf.sparse.reorder(st)
dt_numpy = tf.sparse.to_dense(dt).numpy()
tf.constant(dt_numpy)
```
