### ISSUE TITLE
Failed to get convolution algorithm [CUDA 11.0 - cuDNN 8.0.4 - Python 3.8]

### ISSUE THREAD

**Issue by Chaosdrachin** [tensorflow/tensorflow#47530]
**System information**
- Windows 10
- PC
- TensorFlow installed from (source or binary): via pip
- TensorFlow version: 2.4.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: Cuda 11.0 | cuDNN 8.0.4
- GPU model and memory:
RTX 2060 
6GB

**Describe the problem**
I Coded a CNN in Tensorflow on CPU it works without any problems, then i wanted more performance so i try´d the GPU version , after 2 days of figuring out wich cuda bla bla

now i have no idea to fix this , this is my first Neuronal Network and i only wanted to Check is a Cat or a Dog on the Picture.

i hope someone can help me

i got everytime the following error :
> 2021-03-03 15:23:58.929966: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:58.930097: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:58.930188: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 2021-03-03 15:23:59.186498: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:59.186672: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:59.186834: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:59.189687: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:59.190360: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
> 2021-03-03 15:23:59.190471: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops_fused_impl.h:697 : Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

**Any other info / logs**
the traindata paths and labes are in a SQL database and the sql manger build the full path
i testet it on CPU -> works without Problems

my Programcode itself (Pastebin):
https://pastebin.com/cNeGByBm
The Full Log :
https://pastebin.com/fe3D9Ubk

**Comment by ymodak** [comment]
You may try gpu memory resources management by allowing gpu memory growth.  
To know more see https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
Make sure your exit all python processes and create a new python session and try by limiting gpu memory growth on the top of your script.
```python
import tensorflow as tf
gpu = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu[0], True)
#Rest of your code
```

**Comment by Chaosdrachin** [comment]
> 
> 
> You may try gpu memory resources management by limiting gpu memory growth.
> To know more see https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
> Make sure your exit all python processes and create a new python session and try by limiting gpu memory growth on the top of your script.
> 
> ```python
> import tensorflow as tf
> gpu = tf.config.experimental.list_physical_devices('GPU')
> tf.config.experimental.set_memory_growth(gpu[0], True)
> #Rest of your code
> ```

it works thanks :3
