### ISSUE TITLE
tf.keras.backend.in_train_phase / tf.keras.backend.in_test_phase not documented

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#47537]
Tensorflow 2.4.1

tf.keras.backend.in_train_phase / tf.keras.backend.in_test_phase not documented. 

Reference tf 2.4.1 docs here on the tf.keras.backend lib.  You will see neither function appears.

https://www.tensorflow.org/api_docs/python/tf/keras/backend

**Comment by ymodak** [comment]
Docs are not generated intentionally for some of the `tf.keras.backend` functions.
See commit [a37bf6c](https://github.com/tensorflow/tensorflow/commit/91e5ad0fad9bbf8462a797ddd7183df1c15f6832#diff-3bac640d4fd7baf52009c2ed77c693723025a266052799f44c16cf53c3bdfc53) 
[tf.keras.backend.in_train_phase](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L4693-L4694)
[tf.keras.backend.in_test_phase](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L4739-L4740)

**Comment by isaacgerg** [comment]
@ymodak There is not documentation for differing behavior between test/train time despite the flag learning_phase() being provided and documented.

**Comment by sachinprasadhs** [comment]
Tensorflow has [documented](https://www.tensorflow.org/api_docs/python/tf/keras/backend) only those backend functions listed at https://keras.io/api/utils/backend_utils/, rest all are undocumented.
However, you see see all the hidden functionalities with the code in the github [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py).
Closing this issue, feel free to reopen if you need further clarification. Thanks!
