### ISSUE TITLE
tf.device breaks when using tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by OmriSteiner** [tensorflow/tensorflow#47533]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 / 8.0.4
- GPU model and memory: GeForce RTX 3090 24GB RAM

**Describe the current behavior**
When using `tf.device` inside a generator which is used for dataset creation (using `tf.data.Dataset.from_generator`), the device passed to `tf.device` is not guaranteed to be used.

**Describe the expected behavior**
Tensors created from operations within the scope of `tf.device` should be placed on the given device, unless the operations don't support that device. Anyhow, tensor placement should be deterministic.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

def gen():
    with tf.device("CPU"):
        i = 0
        for i in tf.range(5000):
            i = tf.add(i, 1)
            print(i.device)
            yield i

d = tf.data.Dataset.from_generator(gen, output_types=(tf.int32))

for i in d:
    print(i)
```
Sample output of the above code:
```
...
/job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(4993, shape=(), dtype=int32)
/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(4994, shape=(), dtype=int32)
/job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(4995, shape=(), dtype=int32)
/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(4996, shape=(), dtype=int32)
/job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(4997, shape=(), dtype=int32
...
```
In some cases, the above code will also throw a RuntimeError: "Exiting device scope without proper scope nesting". I'll discuss why this happens later.

The following sample code **does not** reproduce the bug (which is expected, as discussed below):
(I moved the `tf.device` call inside the loop).
```
import tensorflow as tf

def gen():
    i = 0
    for i in tf.range(5000):
        with tf.device("CPU"):
            i = tf.add(i, 1)
            print(i.device)
            yield i

d = tf.data.Dataset.from_generator(gen, output_types=(tf.int32))

for i in d:
    print(i)
```

**Detailed explanation of cause**
The issue is caused by the interaction of the implementations of `tf.device` and `tf.data`.
`tf.device` is a context manager. On entrance, it sets the `device_name` to the given device, and on exit - it restores it to its previous value. However, the `device_name` is a thread-local variable, stored in the context's thread_local_data. You can see the implementation [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/eager/context.py#L1749).
The problem is that, due to the multi-threaded nature of `tf.data`, the python generator used by our dataset might run from different threads. I think it is only guaranteed to run on the same thread until the next `yield` statement (I didn't make sure, but it seems like it).
Thus, if we call `tf.device`, then call `yield`, and then resume execution on a different thread - our context's thread local data would contain a different `device_name`.

In the second code snippet I provided the issue does not reproduce, because each time we return from a `yield` statement, we set the device scope again.

The RuntimeError I mentioned above, stems from [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/eager/context.py#L1797), and it happens when the context manager exits with a different thread, rather than the one it entered with.

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate this issue on tf 2.3, tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/dcad70fe2cccd8fc8c4aa82f2ed6f09a/untitled557.ipynb).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7034fbb6b3210c44a2a8bbc8738473dd/untitled143.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5ac1e412b0cf81a29b59a3e62423d618/untitled169.ipynb?authuser=1) ..Thanks!
