### ISSUE TITLE
tf.data.zip and tf.data.cache throws cachefile AlreadyExistsError and/or deletes valid cachefiles

### ISSUE THREAD

**Issue by kdonbekci** [tensorflow/tensorflow#47545]
**System information**
Running on Ubuntu 20.04 using the docker container 2.4.1-gpu-jupyter.
Also occurs on Google Colab environment running TF 2.4.1

**Describe the current behavior**
`tf.data.Dataset.cache` and `tf.data.Dataset.zip` do not operate well together in certain situations, where there is a hierarchy between datasets but nevertheless they are both desired and cached. Imagine the scenario of an audio data pipeline where client extracts spectrograms and uses those spectrograms to extract MFCCs. Furthermore, the user wants to retain the spectrogram dataset at the end of the pipeline and includes in the final `zip` operation. Now, if the spectrogram dataset is cached to disk to allow for faster feature extraction later (say with different hyperparameters), user will be faced the exception: 
```
AlreadyExistsError: There appears to be a concurrent caching iterator running - cache lockfile already exists 
```
Currently the user can sort of get behind this behavior by simply moving the `.cache` operation on the intermediary dataset to after the `.map` operation that creates the conflicting dataset. This will introduce a performance hit, however, unless all the datasets  upstream of the intermediary dataset are cached. Which brings us to the second issue.
Even if the upstream datasets are cached, there is a bug/behavior that is causing the cache files to be deleted after an iteration over the entire zipped dataset is completed. This second bug essentially renders the workaround useless when the user wants to cache both the downstream and upstream datasets.

**Describe the expected behavior**
The expected or ideal behavior would be the ability of caching&retaining intermediary dataset without a problem. This would make intuitive sense for users building multi-step pipelines with the `tf.data` API.

**Standalone code to reproduce the issue**
The notebook below contains the problematic case as well as the workaround described (and its demise). 
[Link to Google Colab Notebook](https://colab.research.google.com/drive/1MOOfB5eJKAEyNTSxHY1vci6Unc5J2mi0?usp=sharing)

**Other info / logs** 
```
---------------------------------------------------------------------------
AlreadyExistsError                        Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py in execution_mode(mode)
   2112       ctx.executor = executor_new
-> 2113       yield
   2114     finally:

9 frames
AlreadyExistsError: There appears to be a concurrent caching iterator running - cache lockfile already exists ('spectrogram_0.lockfile'). If you are sure no other running TF computations are using this cache prefix, delete the lockfile and re-initialize the iterator. Lockfile contents: Created at: 1614817563 [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

AlreadyExistsError                        Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/executor.py in wait(self)
     67   def wait(self):
     68     """Waits for ops dispatched in this executor to finish."""
---> 69     pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
     70 
     71   def clear_error(self):
```

**Comment by Saduf2019** [comment]
@kdonbekci 
I ran the code shared but do not see the error reported on tf 2.4, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/0392fdc2e633c9207b98abf329f64cf1/untitled557.ipynb).

**Comment by kdonbekci** [comment]
I am sorry if I can't see but running the gist you've sent, I still see that the `AlreadyExistsError` is being caught by the code block demonstrating the issue. I've pasted the mentioned block here.
```
try:
  ds1 = ds.map(hard_problem, num_parallel_calls=1, deterministic=True).cache('spectrogram')
  ds2 = ds1.map(hard_problem, num_parallel_calls=tf.data.AUTOTUNE, deterministic=True).cache('mfcc')
  zipped = tf.data.Dataset.zip((ds1,ds2))
  for x in zipped:
      pass
except tf.errors.AlreadyExistsError as e:
    print(e)
```

**Comment by kdonbekci** [comment]
And here is the entire self-sufficient code block + output demonstrating the issue again,
```
import tensorflow as tf
import numpy as np
print('TF Version: ',tf.__version__)
hard_problem = lambda x: x+1
ds = tf.data.Dataset.from_tensor_slices(np.random.rand(100, 50, 50))
ds1 = ds.map(hard_problem, num_parallel_calls=1, deterministic=True).cache('spectrogram')
ds2 = ds1.map(hard_problem, num_parallel_calls=1, deterministic=True).cache('mfcc')
ds3 = ds2.map(hard_problem, num_parallel_calls=1, deterministic=True)
zipped = tf.data.Dataset.zip((ds1,ds2))
try:
  for x in zipped:
      break
except tf.errors.AlreadyExistsError as e:
  print('ERROR')
  print(e)
```
OUTPUT
```
>>> TF Version:  2.4.1
>>> ERROR
>>> There appears to be a concurrent caching iterator running - cache lockfile already exists ('spectrogram_0.lockfile'). If you are sure no other running TF computations are using this cache prefix, delete the lockfile and re-initialize the iterator. Lockfile contents: Created at: 1614907806
```

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate the issue reported on tf 2.3, 2.4 and nightly, please fin the [gist here](https://colab.research.google.com/gist/Saduf2019/311a685d3e3cffe63736427ceb4720d5/untitled558.ipynb).

**Comment by kdonbekci** [comment]
Yes, can confirm the gist contains the error. 

What's missing in the gist is the second failure of `.cache` and `.zip` where if multiple cached datasets are zipped together, Tensorflow will fail to cache all of the datasets. In fact, it will only cache a single dataset in the zip and emit warnings for the rest as such:
```
2021-03-04 23:36:18.516294: W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2021-03-04 23:36:19.080730: W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2021-03-04 23:36:19.317442: W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

**Comment by kdonbekci** [comment]
The snippet below illustrates the second issue of incomplete iterators. 
```
import tensorflow as tf
import numpy as np
from pathlib import Path
print('TF Version: ',tf.__version__)
Path('cache').mkdir(exist_ok=True)
hard_problem = lambda x: x+1
ds = tf.data.Dataset.from_tensor_slices(np.random.rand(100, 50, 50))
ds1 = ds.map(hard_problem, num_parallel_calls=1).cache('cache/spectrogram')
ds2 = ds.map(hard_problem, num_parallel_calls=1).cache('cache/mfcc')
zipped = tf.data.Dataset.zip((ds1,ds2))
for x in zipped:
    pass
print(list(Path('cache').iterdir()))
```

**Comment by kdonbekci** [comment]
Right now, the only way to avoid this not-fully-consumed iterator issue is to a dummy iteration over all of the to-be-zipped dataset before the `.zip` in a redundant/wasteful way.

**Comment by aaudiber** [comment]
Hi @kdonbekci,

Regarding the AlreadyExistsError, can you try replacing `.cache(filename)` with `.apply(tf.data.experimental.snapshot(filename))`? `snapshot` is similar to cache, but supports concurrent access.

The second issue is an unfortunate interaction between `cache` and `zip`. The contract for `cache` (and `snapshot` for that matter) is that they will only finalize the cached data (making it available for future iterations) if the first pass through the data runs to completion. But `zip` will stop reading from all of its inputs as soon as any of the inputs run out of data. As a result, only one of the inputs to zip will run to completion and finalize its cache.

**Comment by kdonbekci** [comment]
I will try the `snapshot` experimental feature today and let you know how it goes @aaudiber. 

On the second issue, I understand the contracts for these ops require complete iteration. Although I am not familiar with the design limitations of either `zip` or `cache|snapshot` ops, it would be great if this unfortunate interaction was removed going forward.

Either caching without full iteration, like this [torchdata](https://github.com/szymonmaszke/torchdata) package or improving `zip` to accommodate this use case seem like possible alternatives.
Especially in the case (which is my case) the zipped datasets have valid `.cardinality()` results which are all equal.

**Comment by kdonbekci** [comment]
I've tried the new `snapshot` feature. By the way, reading the documentation, it's a great addition to the `tf.data` API! 

Unfortunately `snapshot` is not a fix to my issue. It removes the AlreadyExistsError, however, it does not work as expected and the incomplete iteration causes buildup on disk storage. Here is the [colab](https://colab.research.google.com/drive/1s5zNq1xYkvOtxeR7dY9s1iWSm7jqRz79?usp=sharing) that uses the `snapshot` feature and demonstrates the growing cache directory.

**Comment by RobertBiehl** [comment]
I have the same issue.
It seems like you circumvent the issue by force caching by iterating over it (in this example through tfds benchmark).
After that is done you can zip without causing an error.

This is not really a practical solution, so I hope the bug gets fixed soon.

Example:
```
import tensorflow as tf
import numpy as np
import tensorflow_datasets as tfds
print('TF Version: ', tf.__version__)
hard_problem = lambda x: x + 1
ds = tf.data.Dataset.from_tensor_slices(np.random.rand(100, 50, 50))
ds1 = ds.map(hard_problem, num_parallel_calls=1).cache('spectrogram')
ds2 = ds1.map(hard_problem, num_parallel_calls=1).cache('mfcc')

# force full cache write
tfds.core.benchmark(ds1)
tfds.core.benchmark(ds2)

zipped = tf.data.Dataset.zip((ds1, ds2))
try:
    for x in zipped:
        break
except tf.errors.AlreadyExistsError as e:
    print('ERROR')
    print(e)
    
```

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7d6217b7373a876032e870a86e5e8625/untitled147.ipynb)..Thanks !
