### ISSUE TITLE
TRT：converted tensorRT model pb too large

### ISSUE THREAD

**Issue by ericxsun** [tensorflow/tensorflow#47547]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu-18.04.x86_64
- TensorFlow installed from (source or binary): build from source 
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: cuda=10.1, cuDnn=7.6.4
- GPU model and memory:
- TensorRT version: 6.0.1

**Describe the current behavior**
the converted tensorRT model (pb file) is too large (**9.5M --> 1.1G**, see below)

**Describe the expected behavior**
I guess the converted model could be larger than the original (9.5M), but should not be **too large**

**Standalone code to reproduce the issue**
```
from tensorflow.python.compiler.tensorrt import trt_convert as trt

conversion_params = trt.TrtConversionParams(precision_mode=trt.TrtPrecisionMode.FP32)

input_saved_model_dir = 'bert_finetune_20210303'
output_saved_model_dir = 'bert_finetune_20210303_fp32'

converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_saved_model_dir, conversion_params=conversion_params)
converter.convert()
converter.save(output_saved_model_dir)
```

the size bewteen converted and the original:

```sh
# the original
4.0K	./bert_finetune_20210303/assets
9.5M	./bert_finetune_20210303/saved_model.pb
387M	./bert_finetune_20210303/variables
397M	./bert_finetune_20210303

# precision_mode=trt.TrtPrecisionMode.FP16
4.0K	./bert_finetune_20210303_fp16/assets
1.1G	./bert_finetune_20210303/saved_model.pb
387M	./bert_finetune_20210303_fp16/variables
1.5G   	./bert_finetune_20210303_fp16

# precision_mode=trt.TrtPrecisionMode.FP32
4.0K	./bert_finetune_20210303_fp32/assets
1.1G	./bert_finetune_20210303_fp32/saved_model.pb
387M	./bert_finetune_20210303_fp32/variables
1.5G 	./bert_finetune_20210303_fp32
```

anyone could help me, thanks a lot.

**NOTE**: the model used here: https://drive.google.com/file/d/1sSu08U4-c-iopi5SGLfPUWP68MTpC5wg/view?usp=sharing

**Comment by amahendrakar** [comment]
Colab session crashes on running the code with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4ca6a70325eac68fe87033d8dd8702a6/47547.ipynb). Thanks!

**Comment by ericxsun** [comment]
> here

see the log `INFO:tensorflow:Linked TensorRT version: (0, 0, 0)`, it means tensorflow-gpu with tensorRT does not be installed

**Comment by ericxsun** [comment]
> Colab session crashes on running the code with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4ca6a70325eac68fe87033d8dd8702a6/47547.ipynb). Thanks!

see the log INFO:tensorflow:Linked TensorRT version: (0, 0, 0), it means tensorflow-gpu with tensorRT does not be installed

**Comment by ericxsun** [comment]
@bixia1 available for checking this? Thanks a lot

**Comment by kscp123** [comment]
i also face this problem, anyone can solve it?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
