### ISSUE TITLE
How can i secure my .tflite model on edge device?

### ISSUE THREAD

**Issue by anilnishad19799** [tensorflow/tensorflow#47549]
I have built the TensorFlow model and converted it into a .tflite model, I want to deploy my .tflite model into an edge device(android or IoT).
Final goal: I want to protect my model from being a copy or reverse engineered and also the user is only able to use this model in my android app or IoT device.
how can I do that?

**Comment by abattery** [comment]
There are some options for encrypting your model, for example, applying [AES method](https://stackoverflow.com/questions/6788018/android-encryption-decryption-with-aes).

Encryption requires a key and a key should be stored in somewhere safely. For example, you can look at the [security key attestation](https://developer.android.com/training/articles/security-key-attestation)

**Comment by anilnishad19799** [comment]
how can i secure model in raspberry pi ?

Thanks in advance

**Comment by amahendrakar** [comment]
@anilnishad19799,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
