### ISSUE TITLE
About reshape op on TF Lite nnapi delegate

### ISSUE THREAD

**Issue by antkillerfarm** [tensorflow/tensorflow#47546]
Android NN API only supported tensor rank: up to 4. So maybe need to add rank restriction on TF Lite nnapi delegate. If not, some models which have reshape op(rank > 4) will be failed on Android platform.

For example:
tensorflow/lite/delegates/nnapi/nnapi_delegate.cc:

```c++
bool NNAPIDelegateKernel::Validate(
    const TfLiteContext* context, int builtin_code, int version,
    int android_sdk_version, const TfLiteNode* node,
    bool is_accelerator_specified,
    std::vector<NNAPIValidationFailure>* map_failures) {
...
case kTfLiteBuiltinReshape: {
...
      // add these lines for rank restriction
      const auto& input = context->tensors[node->inputs->data[0]];
      Expect(input.dims->size <= 4,
             NNAPIValidationFailureType::kUnsupportedOperandRank,
             "Input rank should be <= 4", &val_ctx);
...
}
...
}
```

**Comment by abattery** [comment]
@miaowang14 could you review this suggestion regarding shape op validation in NNAPI?

**Comment by miaowang14** [comment]
@antkillerfarm good idea, would you like to create a PR implementing this? I am happy to review and approve it.

**Comment by pjpratik** [comment]
@antkillerfarm The restriction for input and output shape has been now [updated](https://github.com/tensorflow/tensorflow/blob/6a0cfcc56d09643a0cf8292c1b6d0eb0aec92a5d/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc#L2546) for nnapi delegate. Could you please check [this](https://github.com/tensorflow/tensorflow/blob/6a0cfcc56d09643a0cf8292c1b6d0eb0aec92a5d/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc#L2546) and confirm? Thanks.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks.
