### ISSUE TITLE
What's the correct matcher of 'tf.nn.conv2d_transpose' in quantization aware training ?

### ISSUE THREAD

**Issue by Zhuxinpei** [tensorflow/tensorflow#47557]
To some reason, I have to use TF1.X (actually TF1.14.0) to quantize a custom model.
As general,
```
g = tf.get_default_graph()
tf.contrib.quantize.create_training_graph(input_graph=g,quant_delay=0)
```
was used to create fakequant min/max variable and I could find the min/max value of 'tf.nn.conv2d_transpose' in checkpoint. But when
```
tf.contrib.quantize.create_eval_graph()
```
created the Fakequant Evaluation Graph, 'tf.nn.conv2d_transpose' was not added fake quantization nodes. I tried transpose only, transpose --> relu6, transpose --> bias --> relu6, transpose --> bacthnorm --> relu6, but all of them did not work.

### **Thus the direct question: What's the correct matcher of 'tf.nn.conv2d_transpose' in quantization aware training ? Is there any resources documented the correct matchers of every op ?**

**Comment by abattery** [comment]
@ethkim could you triage this issue?
