### ISSUE TITLE
Fails to run the model in an Android app

### ISSUE THREAD

**Issue by neta111111** [tensorflow/tensorflow#47559]
Hi, I've created a model using keras. The model works fine in google-colab but when I attach it to my app in Android Studio I get the following comment:

`java.lang.AssertionError: Error occurred when initializing ImageClassifier: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.`

My app works fine with a different model so I believe the problem is in the model (in the metadata to my understanding).

This is the metadata code:
# Creates model info.
model_meta = _metadata_fb.ModelMetadataT()
model_meta.name = "Pedastrian Lights classifier"
model_meta.description = ("checks what color is the light if exists in frame")
model_meta.version = "v1"
model_meta.author = "Neta Kletshevsky"
# Creates input info.
input_meta = _metadata_fb.TensorMetadataT()

# Creates output info.
output_meta = _metadata_fb.TensorMetadataT()
input_meta.name = "image"
input_meta.description = (
    "Input image to be classified.".format(160, 160))
input_meta.content = _metadata_fb.ContentT()
input_meta.content.contentProperties = _metadata_fb.ImagePropertiesT()
input_meta.content.contentProperties.colorSpace = (
    _metadata_fb.ColorSpaceType.RGB)
input_meta.content.contentPropertiesType = (
    _metadata_fb.ContentProperties.ImageProperties)
input_normalization = _metadata_fb.ProcessUnitT()
input_normalization.optionsType = (
    _metadata_fb.ProcessUnitOptions.NormalizationOptions)
input_normalization.options = _metadata_fb.NormalizationOptionsT()
input_normalization.options.mean = [127.5]
input_normalization.options.std = [127.5]
input_meta.processUnits = [input_normalization]
input_stats = _metadata_fb.StatsT()
input_stats.max = [255]
input_stats.min = [0]
input_meta.stats = input_stats

# Creates output info.
output_meta = _metadata_fb.TensorMetadataT()
output_meta.name = "probability"
output_meta.description = "Probabilities of the 1001 labels respectively."
output_meta.content = _metadata_fb.ContentT()
output_meta.content.content_properties = _metadata_fb.FeaturePropertiesT()
output_meta.content.contentPropertiesType = (
    _metadata_fb.ContentProperties.FeatureProperties)
output_stats = _metadata_fb.StatsT()
output_stats.max = [1.0]
output_stats.min = [0.0]
output_meta.stats = output_stats
#label_file = _metadata_fb.AssociatedFileT()
#label_file.name = "labels"#label_file.description = "Labels for objects that the model can recognize."
#label_file.type = _metadata_fb.AssociatedFileType.TENSOR_AXIS_LABELS
#output_meta.associatedFiles = [label_file]

# Creates subgraph info.
subgraph = _metadata_fb.SubGraphMetadataT()
subgraph.inputTensorMetadata = [input_meta]
subgraph.outputTensorMetadata = [output_meta]
model_meta.subgraphMetadata = [subgraph]

b = flatbuffers.Builder(0)
b.Finish(
    model_meta.Pack(b),
    _metadata.MetadataPopulator.METADATA_FILE_IDENTIFIER)
metadata_buf = b.Output()

populator = _metadata.MetadataPopulator.with_model_file("converted_model.tflite")
populator.load_metadata_buffer(metadata_buf)
#populator.load_associated_files('/content/drive/MyDrive/android/assets')
populator.populate()

**What NormalizationOptions do I need to add and how?**

**Comment by abattery** [comment]
@lu-wang-g could you take a look at this? Thanks

**Comment by neta111111** [comment]
I would highly appreciate if someone can help!

**Comment by lu-wang-g** [comment]
You should be able to pack the normalization params with the following lines of code:
```
input_normalization.options = _metadata_fb.NormalizationOptionsT()
input_normalization.options.mean = [127.5]
input_normalization.options.std = [127.5]
```
Not sure why it doesn't work for you.

Please try the MetadataWriter Library to populate the metadata:
1. Install the TFLite Support nightly Pypi package:
```
pip install tflite_support_nightly
```
2. Write metadata to the model using the following script:
```
from tflite_support.metadata_writers import image_classifier
from tflite_support.metadata_writers import writer_utils
from tflite_support import metadata

ImageClassifierWriter = image_classifier.MetadataWriter
_MODEL_PATH = "mobilenet_v1_1_default_1.tflite"
_LABEL_FILE = "labelmap.txt"
_SAVE_TO_PATH = "mobilenet_v1_1_default_1_metadata.tflite"
_MEAN = 127.5
_STD = 127.5

writer = ObjectDetectorWriter.create_for_inference(
    writer_utils.load_file(_MODEL_PATH), [_MEAN], [_STD], [_LABEL_FILE])
writer_utils.save_file(writer.populate(), _SAVE_TO_PATH)

# Verify the populated metadata and associated files.
displayer = metadata.MetadataDisplayer.with_model_file(_SAVE_TO_PATH)
print("Metadata populated:")
print(displayer.get_metadata_json())
print("Associated file(s) populated:")
print(displayer.get_packed_associated_file_list())
```

Using mean=127.5 and std=127.5 will normalize your image from [0, 255] to [-1, 1]. Some models may normalize it to [0, 1], so mean=0, std=255. Make sure the values are set properly for your case.

**Comment by neta111111** [comment]
Thank you very much, it's working now. Very appreciate your help!

**Comment by Regenhardt** [comment]
How to find out what normalization values I need? I just used 127.5/127.5 because it's the default and I just...threw images into training with a mostly default pipeline.config, yet I'm getting this error.
