### ISSUE TITLE
tf.train.Checkpoint.read breaking inside a @tf.function

### ISSUE THREAD

**Issue by maurodlt** [tensorflow/tensorflow#47561]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 11.2.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8

**Describe the current behavior**
"Tensor is unhashable. Instead, use tensor.ref() as the key." error when running tf.train.Checkpoint.read() inside a @tf.function.
I am running this on jupyter notebook and I am getting the error whenever I run the following function.
word2vec.load_variables.get_concrete_function((tf.TensorSpec([], tf.string, name="file")))

**Describe the expected behavior**
It was expected to work without errors as the tf.train.Checkpoint.write() does and nothing in the documentation indicates that the tf.train.Checkpoint().read() should be different.

**Standalone code to reproduce the issue**

    import tensorflow as tf    
    from tensorflow.keras import Model
    from tensorflow.keras.layers import Dot, Embedding, Flatten

    class Word2Vec(Model):
        def __init__(self, vocab_size, embedding_dim):
            super(Word2Vec, self).__init__()
            self.target_embedding = Embedding(vocab_size, 
                                          embedding_dim,
                                          input_length=1,
                                          name="w2v_embedding", )

            self.context_embedding = Embedding(vocab_size, 
                                           embedding_dim, 
                                           input_length=5)
            self.dots = Dot(axes=(3,2))
            self.flatten = Flatten()

        @tf.function
        def call(self, pair):
            target, context = pair
            we = self.target_embedding(target)
            ce = self.context_embedding(context)
            dots = self.dots([ce, we])
            return self.flatten(dots)
    
        @tf.function
        def save_variables(self, file):
            tf.train.Checkpoint(step=self.variables).write("variables")
            return 0
    
         @tf.function
        def load_variables(self, file):
            tf.train.Checkpoint(step=self.variables).read("variables")
            return 0
    
    #Word2Vec
    embedding_dim = 300
    vocab_size = 50000
    word2vec = Word2Vec(vocab_size, embedding_dim)
    opt = tf.keras.optimizers.SGD(learning_rate=1.0)
    word2vec.compile(optimizer=opt,
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

    target = tf.constant([[1]])
    context = tf.constant([[[2],[3],[4],[5],[6]]])
    predict_example = (target,context)
    word2vec(predict_example)

    call_output = word2vec.call.get_concrete_function((tf.TensorSpec([None,1], tf.int32, name='target'), tf.TensorSpec([None,5,1], tf.int32, name='context')))
    save_variables = word2vec.save_variables.get_concrete_function((tf.TensorSpec([], tf.string, name="file")))
    load_variables = word2vec.load_variables.get_concrete_function((tf.TensorSpec([], tf.string, name="file")))

    word2vec.save("w2v_shakespeare.tf", save_format="tf", signatures={'predict': call_output, 'save': save_variables, 'load': load_variables})
`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

TypeError: in user code:

    <ipython-input-2-f49e7051c166>:31 load_variables  *
        tf.train.Checkpoint(step=self.variables).read("variables")
    /Users/maurodlt/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py:2148 read  **
        return self._saver.restore(save_path=save_path, options=options)
    /Users/maurodlt/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tensorflow/python/training/tracking/util.py:1322 restore
        file_prefix_feed_dict = {self._file_prefix_placeholder: save_path}
    /Users/maurodlt/.pyenv/versions/3.8.0/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:830 __hash__
        raise TypeError("Tensor is unhashable. "

    TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.

[traceback_error.txt](https://github.com/tensorflow/tensorflow/files/6084255/traceback_error.txt)
**Background** 
I am creating a TF model in Python which I am training using the C API. After training in the C API, I want to save and load the trained model. Considering the limitations in the C API, I need to run @tf.functions defined in python to save and load my model. However, the only function that I found that saves variables and can be used inside a @tf.function is the tf.train.Checkpoint.write() which can only be read using the tf.train.Checkpoint.read(), which is returning the reported error.

Thanks : )

**Comment by amahendrakar** [comment]
@maurodlt,
I am facing a different error stating `NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for variables` on running the code. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2575450e985220c21ea919d2f2691436/47561.ipynb). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by maurodlt** [comment]
Hi @amahendrakar,

The code was trying to access a folder that was not created at that point. Please find the corrected notebook [here](https://colab.research.google.com/gist/maurodlt/68cda6c01348981f08e31dc75831b82f/47561.ipynb) (same code below). 

Thanks! : )


    import tensorflow as tf    
    from tensorflow.keras import Model
    from tensorflow.keras.layers import Dot, Embedding, Flatten

    class Word2Vec(Model):
        def __init__(self, vocab_size, embedding_dim):
            super(Word2Vec, self).__init__()
            self.target_embedding = Embedding(vocab_size, 
                                      embedding_dim,
                                      input_length=1,
                                      name="w2v_embedding", )

            self.context_embedding = Embedding(vocab_size, 
                                       embedding_dim, 
                                       input_length=5)
            self.dots = Dot(axes=(3,2))
            self.flatten = Flatten()

        @tf.function
        def call(self, pair):
            target, context = pair
            we = self.target_embedding(target)
            ce = self.context_embedding(context)
            dots = self.dots([ce, we])
            return self.flatten(dots)

        @tf.function
        def save_variables(self, file):
            tf.train.Checkpoint(step=self.variables).write("variables")
            return 0

         @tf.function
        def load_variables(self, file):
            tf.train.Checkpoint(step=self.variables).read("variables")
            return 0

    #Word2Vec
    embedding_dim = 300
    vocab_size = 50000
    word2vec = Word2Vec(vocab_size, embedding_dim)
    opt = tf.keras.optimizers.SGD(learning_rate=1.0)
    word2vec.compile(optimizer=opt,
          loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
          metrics=['accuracy'])

    target = tf.constant([[1]])
    context = tf.constant([[[2],[3],[4],[5],[6]]])
    predict_example = (target,context)
    word2vec(predict_example)

    call_output = word2vec.call.get_concrete_function((tf.TensorSpec([None,1], tf.int32, name='target'), 
    tf.TensorSpec([None,5,1], tf.int32, name='context')))
    save_variables = word2vec.save_variables.get_concrete_function((tf.TensorSpec([], tf.string, name="file")))
    load_variables = word2vec.load_variables.get_concrete_function((tf.TensorSpec([], tf.string, name="file")))

    word2vec.save("w2v_shakespeare.tf", save_format="tf", signatures={'predict': call_output, 'save': save_variables, 'load': load_variables})

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6a32ac9fcb448df77c53f4d38413b3a6/47561.ipynb#scrollTo=-FwYKenh34En). Thanks!

**Comment by rmothukuru** [comment]
@maurodlt,
As the error suggests, can you please use `tensor.ref()` as shown in the [Example Code of tensor.ref()](https://www.tensorflow.org/api_docs/python/tf/Tensor#ref) and see if the error still persists? Thanks!

**Comment by maurodlt** [comment]
> @maurodlt,
> As the error suggests, can you please use `tensor.ref()` as shown in the [Example Code of tensor.ref()](https://www.tensorflow.org/api_docs/python/tf/Tensor#ref) and see if the error still persists? Thanks!

Hi @rmothukuru,
I cannot because this error occurs inside the tf.train.Checkpoint.read function and I do not have control of the tensor that should be used with 'tensor.ref()'. The only parameter that is passed to this function is the name of the file that it should read. 

My Checkpoint object is defined as tf.train.Checkpoint(step=self.variables), the same construction used on the tf.train.Checkpoint(step=self.variables).write(), which works well on the example provided. I tried another two approaches as well: to define the checkpoint using a list of 'tensor.ref()' as suggested, and to define it without any arguments _tf.train.Checkpoint()_. None worked, indicating that the problem is indeed inside the tf.train.Checkpoint.read method. 

Thanks!

**Comment by Saduf2019** [comment]
@maurodlt 
Can you check on the latest tf version and let us know if this is still an issue.

**Comment by maurodlt** [comment]
@Saduf2019 
The error still persists on TF 2.6.0. We can see this by running the code example on [this](https://colab.research.google.com/gist/amahendrakar/6a32ac9fcb448df77c53f4d38413b3a6/47561.ipynb#scrollTo=-FwYKenh34En) gist. 
Thanks!

**Comment by MarkDaoust** [comment]
Yes, this is still a problem.

There is a workaround, use a TF1 name-based checkpoint from `raw_ops`.

There's a complete example here:

https://www.tensorflow.org/lite/examples/on_device_training/overview

Caution: Name-based checkpoints can be tricky.

**Comment by sanatmpa1** [comment]
@maurodlt,

Can you take a look at this above comment from @MarkDaoust and let us know if it helps in resolving your issue? Thanks!

**Comment by maurodlt** [comment]
Thanks @MarkDaoust, now I can load the weights back in the model!

@sanatmpa1, his response did help me as a workaround to the issue.
