### ISSUE TITLE
pip3 install tensorflow-cpu fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [tensorflow/tensorflow#47564]
I guess it is because there is no 'wheel' defined yet. 'pip3 install tensorflow' is available, works. Is there a difference, if you have no (dedicated) GPU?

**Comment by amahendrakar** [comment]
@LutzWeischerFujitsu,
Please try installing the Linux aarch64 release under the Community Supported Builds from [this page](https://github.com/tensorflow/tensorflow#community-supported-builds) and check if it helps. Thanks!

**Comment by LutzWeischerFujitsu** [comment]
I tried pip3 install tf-nightly instead, but it fails, too. However, pip3 install tensorflow works.

**Comment by rmothukuru** [comment]
@LutzWeischerFujitsu,
With respect to your question, 
> Is there a difference, if you have no (dedicated) GPU? 

There is no difference with respect to `Installation` of `Tensorflow` if we have `GPU` or don't have a `GPU`. 

So, you can proceed with `pip3 install tensorflow`.
