### ISSUE TITLE
Didnt find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3' when trying to run on Android

### ISSUE THREAD

**Issue by sailor239** [tensorflow/tensorflow#47562]
### 1. System information

- OS Platform and Distribution (Windows 10):
- TensorFlow installation (pip package):
- TensorFlow library (2.3.1, pip package):

### 2. Code

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

### 3. Failure after conversion
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()  #### Returns error here

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 151 (FlexSize) failed to prepare.

**Comment by abattery** [comment]
Since you are using the Select TF option, please refer to the following documents to enable Flex delegate for FlexSize op:
https://www.tensorflow.org/lite/guide/ops_select

You need to link the additional aar for the Select TF option. There is two options, one for prebuilt aar and one for custom built aar to reduce the unused parts.

**Comment by sailor239** [comment]
> Since you are using the Select TF option, please refer to the following documents to enable Flex delegate for FlexSize op:
> https://www.tensorflow.org/lite/guide/ops_select
> 
> You need to link the additional aar for the Select TF option. There are two ways, one using the prebuilt aar and one using a custom built aar to reduce the unused parts for a small footprint.

Hi, thanks very much for your reply. I will try it.
For the solutions you mentioned, does it also apply for the issue of 'RESIZE_NEAREST_NEIGHBOR' version '3' when deploying on Android?

**Comment by abattery** [comment]
For the RESIZE_NEAREST_NEIGHBOR issue, could you file a separate issue with the reproducible steps?

**Comment by sailor239** [comment]
> For the RESIZE_NEAREST_NEIGHBOR issue, could you file a separate issue with the reproducible steps?

Thank you for your reply. It is actually the same issue. After I converted the model to .tflite, when I try to deploy the model on Android. I encounter the issue of RESIZE_NEAREST_NEIGHBOR. Any ideas? :)

**Comment by abattery** [comment]
Can you share the model creation script or the TFLite model?

**Comment by sailor239** [comment]
> Can you share the model creation script or the TFLite model?

I may not be able to share the model creation script or the model. It is a custom-trained model based on YOLO V3. After training, I get the checkpoint (3 files: checkpoint, .index & .data). Then a script (convert_to_pb.py from https://github.com/pythonlessons/TensorFlow-2.x-YOLOv3/tree/master/tools) is used to convert it to .pb, and then another script (shown in original post as 2. Code) to convert it to .tflite. Is this information enough?

**Comment by abattery** [comment]
I am not sure that it can be reproducible on my side. If possible, could you provide a minimal reproducible step for reducing the graph structure and carrying dumb weights?

I saw that you are using TF 2.3.1. I would highly recommend using TF 2.4.1 and tf-nightly both for the TFLite conversion since there are a lot of improvements in the conversion.

**Comment by sailor239** [comment]
Thank you for the suggestions. But the code currently is not compatible with TF 2.4.1 yet. I'll try to share the model in some way.

**Comment by sailor239** [comment]
Will close this issue for now, as I couldn't share the code or model. Thanks for all the inputs.
