### ISSUE TITLE
 Undefined symbol micro_test::did_test_fail in tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common

### ISSUE THREAD

**Issue by swapnilsayansaha** [tensorflow/tensorflow#47574]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 2.4.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm Mbed OS

The error happens when I try to compile the project in Mbed Studio with tflite micro files generated using make. Steps include:
1. Generate files for Mbed:
```
 make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed OPTIMIZED_KERNEL_DIR=cmsis_nn generate_hello_world_mbed_project
```
2. Copy the tensorflow and third part folders from the gen folder into Mbed project folder in a folder named tensorflow_lite  (the two folders are in tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/hello_world/mbed). the project directory looks something likes this after copying: 
![Screenshot from 2021-03-04 13-01-10](https://user-images.githubusercontent.com/20337475/110029831-cfc5c100-7ce9-11eb-8f5e-e2dfd03c62cd.png)
The project is configured to run on Nucleo-L476RG.

3. Delete examples folder in tensorflow_lite/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/hello_world/mbed/tensorflow/lite/micro/

4. Hit 'clean build' button: 
![Screenshot from 2021-03-04 13-02-38](https://user-images.githubusercontent.com/20337475/110029932-eec45300-7ce9-11eb-9445-ee450d3ca050.png)

5. I faced an error with inline TfLiteRegistration Register_FULLY_CONNECTED_INT8()  being redefined. Solution: Comment out the following line in tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.h:
```
inline TfLiteRegistration Register_FULLY_CONNECTED_INT8() {
return Register_FULLY_CONNECTED();
}
```
6. Hit clean build again. The error this time:
```
Error: L6218E: Undefined symbol micro_test::did_test_fail (referred from BUILD/NUCLEO_L476RG/ARMC6/tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.o).

```
I checked conv_test_common.cc in tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.cc and it doesnt have any micro_test::did_test_fail function, it does reference "tensorflow/lite/micro/kernels/conv_test.h", which references "tensorflow/lite/micro/testing/micro_test.h", which does seem to have the following namespace:
```
  namespace micro_test {            \
  int tests_passed;                 \
  int tests_failed;                 \
  bool is_test_complete;            \
  bool did_test_fail;               \
  } 
```
I am not sure why the error is occuring.

**Comment by swapnilsayansaha** [comment]
Further information, my hunch says the problem is happening here in conv_test_common.cc, as it invokes a function from "tensorflow/lite/micro/testing/micro_test.h", where its calling micro_test::did_test_fail boolean variable but not finding it for some reason despite having the variable in the namespace in micro_test.h file.

![Screenshot from 2021-03-04 14-27-36](https://user-images.githubusercontent.com/20337475/110039253-cf332780-7cf5-11eb-886c-780208f73fa4.png)

**Comment by swapnilsayansaha** [comment]
Update: Solved the issue by changing the following function in micro_test.h:
```
#define TF_LITE_MICRO_EXPECT_NEAR(x, y, epsilon)                              \
  do {                                                                        \
    auto vx = (x);                                                            \
    auto vy = (y);                                                            \
    auto delta = ((vx) > (vy)) ? ((vx) - (vy)) : ((vy) - (vx));               \
    if (vx != vy && delta > epsilon) {                                        \
      MicroPrintf(#x " (%f) near " #y " (%f) failed at %s:%d",                \
                  static_cast<double>(vx), static_cast<double>(vy), __FILE__, \
                  __LINE__);                                                  \
      micro_test::did_test_fail = true;                                       \
    }                                                                         \
  } while (false)
```
to
```
#define TF_LITE_MICRO_EXPECT_NEAR(x, y, epsilon)                              \
  do {                                                                        \
    auto vx = (x);                                                            \
    auto vy = (y);                                                            \
    auto delta = ((vx) > (vy)) ? ((vx) - (vy)) : ((vy) - (vx));               \
    if (vx != vy && delta > epsilon) {                                        \
      MicroPrintf(#x " (%f) near " #y " (%f) failed at %s:%d",                \
                  static_cast<double>(vx), static_cast<double>(vy), __FILE__, \
                  __LINE__);                                                  \
    }                                                                         \
  } while (false)
```
I am not sure if this is recommended or it will break something, so waiting for a tensorflower to comment.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
