### ISSUE TITLE
tensorflow.keras and tensorflow.python.keras

### ISSUE THREAD

**Issue by XXZhou25** [tensorflow/tensorflow#47570]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux centos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.4.1
- Python version: 3.6.2
- Installed using virtualenv? pip? conda?: virtualenv conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):7.2.0
- CUDA/cuDNN version:cudnn-6.0.21-cuda8.0_0
- GPU model and memory:Tesla K20Xm 4G

**Describe the problem**
I was wondering why keras is under /path/tensorflow/python instead of /path/tensorflow/ anymore?
Is it because of new version?

I asked this question is because one package I am trying to use call tensorflow.keras when I import it, while my keras is actually under tensorflow.python.keras, and I want to find the reason before I reinstall everything.

Thanks.  
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by XXZhou25** [comment]
I remember like last year, my keras was under tensorflow/python/keras, but I reinstalled my environment, after that my keras was under tensorflow/keras. I don't remember their versions. Is it caused by tensorflow version? I will appreciate if you have any idea of importing tensorflow.keras directly. Thanks!

**Comment by Saduf2019** [comment]
@XXZhou25 
We see that you are using an old version of tensorflow, we do not have support for 1.x, could you please upgrade to 2.x and let us know if you face any issues.
Yes you would see changes due to the new version and because there is no support for 1.x.

**Comment by XXZhou25** [comment]
Hi @Saduf2019 ,
I see. I just updated tf to 2.x and it works perfect. Thank you so much!

**Comment by Saduf2019** [comment]
@XXZhou25 
Can you please move this to closed status as the issue is resolved.
