### ISSUE TITLE
Failed to build TF on Ubuntu 18.04 due to C++ compilation of rule '//tensorflow/stream_executor/cuda:cusparse_stub' failed (Exit 1)

### ISSUE THREAD

**Issue by div3125** [tensorflow/tensorflow#47587]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.1
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: conda (conda version 4.8.2)
- Bazel version (if compiling from source): 3.1.0 (Bazelisk v1.7.5)
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA Version 10.1.105, cuDNN version 7.6.5
- GPU model and memory: 2 x NVIDIA Quadro RTX 8000 (48 GB per card, 96 GB total)

**Describe the problem**
Bazel build step fails when building from source
**ERROR: /home/user/Downloads/tensorflow-2.4.1/tensorflow/tools/pip_package/BUILD:69:1 C++ compilation of rule '//tensorflow/stream_executor/cuda:cusparse_stub' failed (Exit 1)**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Installing Bazelisk
sudo curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64
2. Downloaded TF v2.4.1 source
curl -LO https://github.com/tensorflow/tensorflow/archive/v2.4.1.tar.gz
3. tar -xvzf v2.4.1.tar.gz && cd tensorflow-2.4.1
4. Install bazel
bazel version (This command automatically installed bazel version 3.1.0)
5. ./configure.py
Output of configure.py attached in file configure_output.txt
6. bazel build //tensorflow/tools/pip_package:build_pip_package
Output of build attached in file bazel_build_output.txt

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[bazel_build_output.txt](https://github.com/tensorflow/tensorflow/files/6089929/bazel_build_output.txt)
[configure_output.txt](https://github.com/tensorflow/tensorflow/files/6089930/configure_output.txt)

**Comment by amahendrakar** [comment]
@div3125,
TensorFlow **v2.4** was built and tested against **CUDA 11.0** and **cuDNN 8**. Every TensorFlow release is compatible with a certain CUDA/cuDNN version, for more information please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu). 


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0 | 7.6 | 10.1



Could you please try building **TensorFlow v2.4** with **CUDA 11.0** and **cuDNN 8** and check if you are facing the same error. Thanks!

**Comment by div3125** [comment]
On my system, I have other versions (<=2.3) of Tensorflow running which are built against CUDA 10, which is currently installed. I can install CUDA 11.2 side by side but my NVIDIA driver version is 418 which is not compatible with cuDNN 8. Is it not possible to build v2.4 against CUDA 10?

**Comment by amahendrakar** [comment]
> Is it not possible to build v2.4 against CUDA 10?

@div3125,
You will most likely face errors while building the package since TF v2.4 was intended to be built with CUDA 11.0.

In this case, is it possible for you to update the NVIDIA driver on your machine?

Also, CUDA 11.2 support is already being tracked in issue [#47568](https://github.com/tensorflow/tensorflow/issues/47568).

Thanks!

**Comment by div3125** [comment]
My bad, I typed CUDA 11.2 by mistake, I actually meant 11.0. I can't update the NVIDIA driver because it will break compatibility with other TensorFlow installations on the system. If there is no other solution then I will close the issue.

**Comment by amahendrakar** [comment]
@div3125,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/45205#issuecomment-747440700) from issue #45205 with a similar error log and check if it helps. Thanks!

**Comment by div3125** [comment]
I deleted Bazel cache directory, reinstalled Bazel and created new source directory for TensorFlow v2.4.1 and ran the compilation process again but encountered this same error again. So, Bazel caching doesn't seem like the root cause. 

Also, in issue [#45205](https://github.com/tensorflow/tensorflow/issues/45205), the author is trying to compile TensorFlow version 2.3.0 against CUDA version 10.1 which is a tested build configuration. I am trying to build v2.4.1 against CUDA 10.1 which is not an officially tested configuration according (the link)[https://www.tensorflow.org/install/source#gpu]  you mentioned in a comment above.

At the moment, I am unable to upgrade NVIDIA driver on my system from its current version r418.39 because it will break compatibility with Tensorflow installations < v2.4 in different Anaconda environments on my system which use CUDA v10.0 and v10.1 which in turn need this version of NVIDIA driver.

I am currently trying Docker build process mentioned in [this comment](https://github.com/tensorflow/tensorflow/issues/45205#issuecomment-735217803) of the same issue  [#45205](https://github.com/tensorflow/tensorflow/issues/45205) and I will share the results in a few days.

**Comment by div3125** [comment]
@amahendrakar I found a solution, Anaconda has added tensorflow-gpu v2.4.1 package. I was able to install and run it with the following command in my Anaconda environment (Python 3.8.8)

`conda install -c anaconda tensorflow-gpu==2.4.1`
