### ISSUE TITLE
Given an input and get two outputs

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/tensorflow#47593]
I am using Tensorflow 2.4.0 and Ubuntu 16.04

Given this model

    base_model = tf.keras.applications.EfficientNetB0(weights="imagenet", include_top=False)
    base_model.trainable = base_model_trainable
    inputs = tf.keras.Input(shape=(IMG_SIZE,IMG_SIZE,3), name="input")
    x = tf.keras.applications.efficientnet.preprocess_input(inputs)
    # more details - https://www.tensorflow.org/tutorials/images/transfer_learning#important_note_about_batchnormalization_layers

    x = base_model(x,
                   training=False)  # training=training is needed only if there are layers with different behavior during training versus inference (e.g. Dropout)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    outputs = tf.keras.layers.Dense(len(class_names), name="output")(x)
    model = tf.keras.Model(inputs, outputs)

My objective is given the input to get the value  of `model.get_layer("efficientnetb0").output`, 
and `model.output`

if I do (a) (it does not give `model.get_layer("efficientnetb0").output`)

    layer_name="efficientnetb0"

    grad_model = tf.keras.models.Model([model.inputs], [model.output])

or (b) (it requires an additional input after preprocessing)

    grad_model = tf.keras.models.Model([model.inputs, model.get_layer(layer_name).input], [model.get_layer(layer_name).output, model.output])

both works

but if I do

    grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output])

It gives exception:

    ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'") at layer "rescaling". The following previous layers were accessed without issue: []

It does not make sense to me - is this a bug or is there a way for me to pass in just an input and get two outputs?

**Comment by amahendrakar** [comment]
@tianhuat,
On running the code, I am facing an error stating `NameError: name 'base_model_trainable' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f29e5b2b3bace2df45cf9653a89f5679/47593.ipynb).

In order to reproduce the issue reported, could you please provide the complete code and the dataset you are using. Thanks!
