### ISSUE TITLE
Tensorflow Lite Android Object Detection — Mobile SSD models are expected to have exactly 4 outputs, found 8

### ISSUE THREAD

**Issue by fonghyalex** [tensorflow/tensorflow#47595]
**Problem Encountered:**

> E/AndroidRuntime:` FATAL EXCEPTION: main Process: org.tensorflow.lite.examples.detection, PID: 14719 java.lang.AssertionError: Error occurred when initializing ObjectDetector: Mobile SSD models are expected to have exactly 4 outputs, found 8

**Problem Description**
- Android Application Source: TensorFlow Lite Object Detection Example from Google
- Error shown when starting the Example Application

**Model Description**
- Custom Model Used? **YES**
- Pre-trained Model Used: ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8
- Inference type: FLOAT
- Number of classes: 4

**System Information**
- OS Platform and Distribution: ( Linux Ubuntu 20.14)
- TensorFlow Version: 2.4.1
- TensorFlow installed from: Pip

**Saved Model conversion commands used**

1. Saved_Model.pb export command:

> python ./exporter_main_v2.py
--input_type image_tensor
--pipeline_config_path ./models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/pipeline.config
--trained_checkpoint_dir ./models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8
--output_directory exported_models/tflite

2. Convert saved model (.pb) to tflite command:
> toco
--saved_model_dir ./exported-models/tflite/saved_model
--emit-select-tf-ops true
--allow_custom_ops
--graph_def_file ./exported-models/tflite/saved_model/saved_model.pb
--output_file ./exported-models/tflite/tflite/detect.tflite
--input_shapes 1,300,300,3
--input_arrays normalized_input_image_tensor
--output_arrays 'TFLite_Detection_PostProcess’,’TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'
--inference_type=FLOAT
--allow_custom_ops

**Remarks**
I am trying to use a trained custom model on the Google TensorFlow lite provided example. Just that every time I open the application, it returns such an error, Mobile SSD models are expected to have exactly 4 outputs, found 8. The model is trained to identify 4 classes, all stated in the labelmap.txt and pipeline config.

Does anybody have any clue about this error?

**Comment by abattery** [comment]
@lintian06 could you take a look at this issue?

**Comment by fonghyalex** [comment]
@lintian06 
Hello,
May I ask if I want to prevent this from happening, shall I change to other models? 
Or it is not model-related issue?

**Comment by lintian06** [comment]
Hi @fonghyalex,

As you've customized the model other than our built-in model, the model is different from the previous one because it doesn't contain model [metadata](https://www.tensorflow.org/lite/inference_with_metadata/overview). Therefore, it fails the previous assertion. (The inputs and outputs may be different too, which I cannot infer from your report.)

First, please change the related code to run with the interpreter directly. In [build.gradle](
https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/build.gradle#L40),
```
interpreter {
    getIsDefault().set(true)
    dimension "tfliteInference"
}
taskApi {
    // getIsDefault().set(true)  <- default
    dimension "tfliteInference"
}
```
After using interpreter, you can customize inputs and outputs for [TFLiteObjectDetectionAPIModel](https://github.com/tensorflow/examples/blob/cbe96424b6b930fd74dbd4ef2b1e826a031a3554/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L56) if it is needed.

Second, please double confirm whether `--emit-select-tf-ops true` and `--allow_custom_ops` are do needed. It is because `select-tf-ops` and `custom ops`, as names indicate, require more than ordinary TFLite runtime and built-in TFLite ops. Please try removing to see if it still produces correct a model.

*Notes for your information.*
- For [select TF Ops](https://www.tensorflow.org/lite/guide/ops_select#android_aar), you need to add `org.tensorflow:tensorflow-lite-select-tf-ops` in aar. It means including selected TF ops in the TFLite runtime.

- For [custom ops](https://www.tensorflow.org/lite/guide/ops_custom), it requires you to include your own implementation of custom ops into TFLite.

------------------------------
Hope it helps!

**Comment by lintian06** [comment]
@lu-wang-g for the visibility of metadata.

**Comment by fonghyalex** [comment]
@lintian06 
Thank you so much for your prompt reply! =)

After carefully following your instruction and the tutorial of [Tensorflow Example](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md), I have exported the .tflite to the application once again.

Just that, I have encountered another problem:
> java.lang.AssertionError: Error occurred when initializing ObjectDetector: Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images.

From the error message, I learnt that the metadata is not being set up properly. Yet, I can hardly find any tutorial on setting the metadata from the Tensorflow Example instructions. 

**As the custom model is actually downloaded from the TensorFlow 2 Model zoo, may I ask how should I modify the metadata?**

**Comment by lu-wang-g** [comment]
Please check my answer [here](https://stackoverflow.com/a/64493506/11031225) about how to use the MetadataWriter Library. We'll publish the formal documentation soon. Please stay tuned. Thanks.

**Comment by fonghyalex** [comment]
@lu-wang-g
Huge thanks!
I have tried using this script yesterday and the script returned a message similar to "not a valid tflite file". I believe there may be something wrong when I am converting the model.
In order to fully achieve the expected website from the [example](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md)  instruction. I have decided to train another model with TensorFlow v1 and perform the conversion.

As I do not have any furthers questions up to now, I'll close the issue for now and open it again once there is any update.
@abattery @lintian06 @lu-wang-g Thank you so much for helping me out! =)

**Comment by fonghyalex** [comment]
After further study, I believe the aforementioned issue was raised since the model has 8 tensors output but the Android application written in Java can only support 4 tensors output (at least the example provided by Google only supports 4 tensors output)

I am not very certain about the number of tensors output on different models. So far as I understood and messed around with different models, models with fixed_shape_resizer of 640 x 640 are likely to require more than 4 tensors output ( 8 tensors output usually), which is not compatible with the Android application written in Java.

For any amateur users like me, please find the following prerequisites to use your custom model in the [Android application](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)
Suggested Setup ( Assume you are using TensorFlow version >= 2.3):

- TensorFlow Model: *SSD model with fixed_shape_resizer of 320 x 320*
(In my case, SSD MobileNet v2 320x320 works perfectly fine)
(The tensors output has to be 4)

- *Colab* ( Perfect for model training and conversion)
( I've tried to perform the training and conversion on both Linux and Windows platform on my local machine, the incompatibility of different tools and package gives me a headache. I turned out using Colab to perform the training and conversion. It is much more powerful and has great compatibility with those training tools and script.)

- The [metadata writer library](https://stackoverflow.com/questions/64097085/issue-in-creating-tflite-model-populated-with-metadata-for-object-detection/64493506#64493506) that was written by @lu-wang-g
(In my case, after converting the trained model to .tflite, if you directly migrate the .tflite model to the Android application, the application will report tons of problem regarding the config of the .tflite model. Assume if you trained and converted the model correctly, all you need is the metadata writer library above. It will automatically configure the metadata for you according to the .tflite model. Then you can directly migrate the model to the application.)

**Comment by lu-wang-g** [comment]
Using TFLite_Detection_PostProcess should only create a model with 4 output tensors instead of 8. I guess something was wrong during the conversion from TF to TFLite. Can you please share the script and the model?

Loop in @srjoglekar246 to verify the conversion step.

**Comment by fonghyalex** [comment]
@lu-wang-g 
This is the [Colab scripts](https://colab.research.google.com/drive/1bhf36Pk-YnFTPj7O_d3H0q9DYzLXfa45?usp=sharing) I have used.

Please note that I have git cloned the [TensorFlow Model Garden](https://github.com/tensorflow/models) and the [Metadata writer library](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/metadata/python/metadata_writers) to the drive beforehand.

Model used:
SSD MobileNet v2 320x320

**Comment by srjoglekar246** [comment]
@fonghyalex 

1. Your checkpoint path to `export_tflite_graph_tf2` seems wrong. It should be `Model/ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint` ?

2. Not sure if you can convert TF2 with quantization like that. Can you try `tflite_convert` without all the quantization parameters, and see things work on float? If yes, then the quantization params might not work. I usually use the [Python API](https://www.tensorflow.org/lite/performance/post_training_quantization) for quantization.

**Comment by fonghyalex** [comment]
@srjoglekar246 

Thank you for your message. I am sorry that I forgot to mention that I have successfully converted the TensorFlow model to tflite and it is working fine on the Java application.

For the post quantization part, may I ask if the correct flow is that the model has to be first quantized, then convert to the tflite format? After post-quantization, I can then add all the quantization parameter to perform tflite conversion?

I will do a test on the above question tomorrow. Thanks!
Shall I close the issue?

**Comment by srjoglekar246** [comment]
you need to quantize while converting. See the documentation for Python API I linked.

**Comment by fonghyalex** [comment]
@srjoglekar246 

Thank you for your prompt reply. 

I will follow the documentation to perform the quantization. Huge thanks!

As the issue in the title is solved now, I am going to close this issue. Thanks everyone!

**Comment by iamdanniemirz** [comment]
@fonghyalex 
Hi Dear, I'm still stuck on this problem. can you share your solution with me so I run my quantized model on android? Thanks a Lot.

**Comment by PadalaKavya** [comment]
> Hi @fonghyalex,
> 
> As you've customized the model other than our built-in model, the model is different from the previous one because it doesn't contain model [metadata](https://www.tensorflow.org/lite/inference_with_metadata/overview). Therefore, it fails the previous assertion. (The inputs and outputs may be different too, which I cannot infer from your report.)
> 
> First, please change the related code to run with the interpreter directly. In [build.gradle](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/build.gradle#L40),
> 
> ```
> interpreter {
>     getIsDefault().set(true)
>     dimension "tfliteInference"
> }
> taskApi {
>     // getIsDefault().set(true)  <- default
>     dimension "tfliteInference"
> }
> ```
> 
> After using interpreter, you can customize inputs and outputs for [TFLiteObjectDetectionAPIModel](https://github.com/tensorflow/examples/blob/cbe96424b6b930fd74dbd4ef2b1e826a031a3554/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L56) if it is needed.
> 
> Second, please double confirm whether `--emit-select-tf-ops true` and `--allow_custom_ops` are do needed. It is because `select-tf-ops` and `custom ops`, as names indicate, require more than ordinary TFLite runtime and built-in TFLite ops. Please try removing to see if it still produces correct a model.
> 
> _Notes for your information._
> 
> * For [select TF Ops](https://www.tensorflow.org/lite/guide/ops_select#android_aar), you need to add `org.tensorflow:tensorflow-lite-select-tf-ops` in aar. It means including selected TF ops in the TFLite runtime.
> * For [custom ops](https://www.tensorflow.org/lite/guide/ops_custom), it requires you to include your own implementation of custom ops into TFLite.
> 
> Hope it helps!

Where can I find this code to change?
