### ISSUE TITLE
Make Sure Full Functionality is Available in C/C++

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#476]
Please make sure all the functionality is defined in the C++ core.

**Comment by bhack** [comment]
:+1:

**Comment by josh11b** [comment]
I am currently working on expanding the C API to add support for graph definition.  Not sure when it will be done, but it is one of our goals before 1.0.

**Comment by saudet** [comment]
@josh11b Great! Though what about automatic differentiation?

**Comment by josh11b** [comment]
Automatic differentiation will eventually be in, though closer to 1.0.  Are you looking for C API support for use in another language or are you using C++ directly?  We consider those separate APIs, but both should have something reasonable for defining graphs (though no shape inference or automatic differentiation, yet) in the next TensorFlow release (0.10.0) -- they are both checked in at head.

C++ graph-definition API update: 
https://github.com/tensorflow/tensorflow/commit/25ac3dabfa3af7a313eb46b03690117c85030cc2

C graph-definition API was a few commits, I'm having trouble tracking them all down.

**Comment by saudet** [comment]
Good to hear that! JavaCPP has no problems interacting with TensorFlow's C++ API directly, so using either API is fine in that case.

**Comment by josh11b** [comment]
Andy will know more about the status of automatic differentiation.

**Comment by aselle** [comment]
Shape inference is now in C++ as is partial gradients. Work continues, but closing due to lack of recent activity. Please open a new issue referencing this one if it is still an issue. Thanks!

**Comment by jdolson** [comment]
@aselle Do you mean to say that the C++ interface can now compute gradients and add them to the graph as in python? I don't see anything in the C interface to access this functionality. Is there a separate ticket to track that? Is there any rough timeline on when this functionality is expected?

**Comment by aselle** [comment]
@saudet, this issue is overly broad and not clear what it is asking for. Many of the things raised in this issue have been addressed. I closed this to create a more focused issue #7044.
