### ISSUE TITLE
TLFM Problem Compiling micro_allocator.cc In Visual Studio With MSVC

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tensorflow#47609]
@tensorflow/micro

**System information**
- Windows 10
- TensorFlow installed from source
- Tensorflow version 2.4.1:
- Target platform: Windows Visual Studio 2019 MSVC. Building with C++ Language Standard Default (ISO C++14 Standard) and C Language Standard Default (Legacy MSVC)

**Describe the problem**
I am working to port TFLM to Visual Studio and almost have it working. I am currently stuck at one issue. In micro_allocator.cc, there is a declaration of a constant TFLiteIntArray:

//tensorflow/lite/micro/micro_allocator.cc line 63:
`const TfLiteIntArray kZeroLengthIntArray = {};`

TFLiteIntArray uses a variable length array at the end.

//tensorflow/lite/c/common.h line 81:
```
typedef struct TfLiteIntArray {
  int size;
// gcc 6.1+ have a bug where flexible members aren't properly handled
// https://github.com/google/re2/commit/b94b7cd42e9f02673cd748c1ac1d16db4052514c
#if (!defined(__clang__) && defined(__GNUC__) && __GNUC__ == 6 && \
     __GNUC_MINOR__ >= 1) ||                                      \
    defined(HEXAGON) || (__clang_major__ == 7 && __clang_minor__ == 1)
  int data[0];
#else
  int data[];
#endif
} TfLiteIntArray;
```

The micro_allocator.cc will not compile in MSVC, as it generates an error [C466](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2466?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2466)%26rd%3Dtrue&view=msvc-160), cannot allocate an array of constant size 0:

The C466 error can supposedly be disabled with the "Disable Language Extensions" compiler setting (/Za). This setting is incompatible with compiler C17, thus I'm using C14. However when I set /Za with C14, the error is still generated for micro_allocator.cc, and creates a lot of problems elsewhere in the project.

There are two places in micro_allocator where the kZeroLengthIntArray object is referenced, in both cases the address of kZeroLengthIntArray is being used when a tensor's shape is found to be null:

```
if (flatbuffer_tensor.shape() == nullptr) {
    // flatbuffer_tensor.shape() can return a nullptr in the case of a scalar
    // tensor.
    result->dims = const_cast<TfLiteIntArray*>(&kZeroLengthIntArray);
  }
```

I have resolved the compiler issue by creating a pointer to an empty zero length int array object, and a function that initializes the object at runtime and returns a pointer to that object:

```
TfLiteIntArray* pZeroLengthIntArray = 0;
TfLiteIntArray* GetZeroLengthIntArray()
{
    if (pZeroLengthIntArray == 0)
    {
        pZeroLengthIntArray = (TfLiteIntArray *)malloc(sizeof(TfLiteIntArray));
        pZeroLengthIntArray->size = 0;
    }
    return pZeroLengthIntArray;
}
```

If a tensor's shape is found to be null, I set its dims pointer to this dynamically allocated object by calling the function:

```
  if (flatbuffer_tensor.shape() == nullptr) {
    // flatbuffer_tensor.shape() can return a nullptr in the case of a scalar
    // tensor.
    result->dims = const_cast<TfLiteIntArray*>(GetZeroLengthIntArray());
  }
```

Question:
Is there some other way to get MSVC to compile micro_allocator.cc? If not, should I submit the above work-around as a general pull-request that will be compatible with MVSC as well as gnu/other compilers?

**Comment by embeddetech** [comment]
Update: 
I would probably propose the code below as an improvement from the code above, as it avoids a potential memory leak.

```
unsigned char ZeroLengthIntArrayBuffer[sizeof(TfLiteIntArray)];
TfLiteIntArray* GetZeroLengthIntArray()
{
    TfLiteIntArray* pZeroLengthIntArray = (TfLiteIntArray*)ZeroLengthIntArrayBuffer;
    pZeroLengthIntArray->size = 0;
    return pZeroLengthIntArray;
}
```

```
 if (flatbuffer_tensor.shape() == nullptr) {
    // flatbuffer_tensor.shape() can return a nullptr in the case of a scalar
    // tensor.
    result->dims = const_cast<TfLiteIntArray*>(GetZeroLengthIntArray());
  }
```

**Comment by lindyrock** [comment]
@embeddetech @advaitjain I have been running into the same C2466 error on micro_allocator.cc Line 63. I was just able to get this to compile on MSVC (Windows 10; VS2019; ISO C++14/C11) by altering line 63 from:

`const TfLiteIntArray kZeroLengthIntArray = {};
`

to 

`const TfLiteIntArray kZeroLengthIntArray{0};
`

@embeddetech I don't know yet if this is a good solution, but there seems to be no harm in explicitly setting `int size = 0` in this way.

**Comment by advaitjain** [comment]
The flexible member in TfLiteIntArray as well as zero length array have been tricky across multiple compiler versions.

I would recommend the following:

 * (Preferred) add an ifdef for your platform here: https://github.com/tensorflow/tensorflow/blob/425b7e924b180b9979457ab7f36c78f306a5eef8/tensorflow/lite/c/common.h#L81-L93

 * If that does not work, then go with the suggestion from @lindyrock and add an ifdef to micro_allocator.cc https://github.com/tensorflow/tensorflow/blob/425b7e924b180b9979457ab7f36c78f306a5eef8/tensorflow/lite/micro/micro_allocator.cc#L63

**Comment by embeddetech** [comment]
@advaitjain Thank you! Is there any chance an #ifdef _WINDOWS switch could be pulled into the TFLM release so that it is compatible with MSVC out of the box?

@lindyrock I want to say that doing it your way seemed to cause issues for me, but it may be that I had multiple concurrent issues and was confused about what was causing me problems. I have TFLM up and running in an MSVC C/C++ project. I currently have problems loading models if certain layers are too large, but I'm close. How is your port of TFLM into MSVC going?

**Comment by SuryanarayanaY** [comment]
Hi @embeddetech ,

Could you confirm whether this is still an issue for you ? Did you get a chance to work on latest TF versions?

**Comment by SuryanarayanaY** [comment]
Hi @embeddetech ,

Glad that your issue got resolved.Please feel free to close the issue.Thanks!
