### ISSUE TITLE
Error to load a file related with cuda

### ISSUE THREAD

**Issue by LucasColas** [tensorflow/tensorflow#47602]
**System information**
- OS Platform and Distribution : Windows 10 Familly 1909
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install 
- TensorFlow version: 2.3.0
- Python version: 3.7
- Installed using pip
- CUDA/cuDNN version: 11.2
- GPU model and memory: 1660Ti

**Describe the problem**

I installed tensorflow with PIP.  Then I wanted to use use keras. I tried to execute a py file with this code : 
`from tensorflow.keras import layers
`

But I got : 

> 2021-03-06 06:24:10.791991: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-06 06:24:10.804340: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

And I have already done : 

> pip install tf-nightly-gpu

**Comment by amahendrakar** [comment]
@LucasColas,
Every TensorFlow release is compatible with a certain CUDA/cuDNN version, for more information please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu). 

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1

In this case, can you please try building **TensorFlow v2.4** with **CUDA 11.0** and **cuDNN 8** and check if you are facing the same error. Thanks!

**Comment by LucasColas** [comment]
My CUDA version is 11.2

**Comment by LucasColas** [comment]
Hi, I'm still waiting an answer.

**Comment by amahendrakar** [comment]
> My CUDA version is 11.2

@LucasColas,
Support for CUDA 11.2 is being tracked in issue [#47568](https://github.com/tensorflow/tensorflow/issues/47568).

As mentioned in the previous comment, could you please try running the code either with 

**TensorFlow v2.3**, **CUDA 10.1** and **cuDNN 7.6**

or 

**TensorFlow v2.4**, **CUDA 11.0** and **cuDNN 8.0**

Thanks!

**Comment by LucasColas** [comment]
How can I change my Cuda version and cuDNN version ? 
Thanks.

**Comment by amahendrakar** [comment]
@LucasColas,
Please uninstall the existing CUDA and cuDNN packages and follow [this guide](https://www.tensorflow.org/install/gpu#windows_setup) to install TensorFlow with GPU support. Thanks!
