### ISSUE TITLE
Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)

### ISSUE THREAD

**Issue by ritchieng** [tensorflow/tensorflow#4760]
I've the following error. I'm using a conda installation of tensorflow. I'm struggling to try to use it with my GPU.

```
Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:526] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
Aborted (core dumped)
```

which nvcc returns
`/usr/local/cuda-7.5/bin/nvcc`

nvcc version returns
`Cuda compilation tools, release 7.5, V7.5.17`

I tried downloading CuDNN v5.1 and did the following but it didn't work either
```
sudo cp lib* /usr/local/cuda-7.5/lib64/
sudo cp include/cudnn.h /usr/local/cuda-7.5/include/
sudo ldconfig

```

I tried on the other folder too
```
sudo cp lib* /usr/local/cuda/lib64/
sudo cp include/cudnn.h /usr/local/cuda/include/
sudo ldconfig
```

**Comment by tatatodd** [comment]
@ritchieng Please provide info on your environment.  I.e. fill out the template that's provided when you click on the green "New issue" button.  Thanks!

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by xinqiu** [comment]
> E tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:526] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Abort trap: 6

Mac: 10.11.6

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep_18_22:16:08_CDT_2016
Cuda compilation tools, release 8.0, V8.0.46
GPU Driver Version: 10.10.14 310.42.25f02

GPU: GTX 750M

Python 2.7.10

tf.__version__ ='0.11.0rc1'
