### ISSUE TITLE
Hexagon 685/690 wrong SoC examples for QCS610/QCS410 on TensorFlow Lite Hexagon delegate 

### ISSUE THREAD

**Issue by tomchen1000** [tensorflow/tensorflow#47607]
On this page:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/hexagon_delegate.md

It states that QCS610, QCS410 are SoC examples for Hexagon 690. However, according to Qualcomm's product info:
https://www.qualcomm.com/products/qcs610

Both SoC QCS610 and QCS410 contain Hexagon 685 rather than Hexagon 690.

**Comment by abattery** [comment]
@karimnosseir could you review this suggestion?

**Comment by karimnosseir** [comment]
@tomchen1000  Thanks for the feedback. I've reached to QC to confirm and didn't hear back from them yet.

Thanks
