### ISSUE TITLE
Can we add a check in Model.fit on dataset element_spec?

### ISSUE THREAD

**Issue by gqqnbig** [tensorflow/tensorflow#47618]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I have this code
```python
import tensorflow as tf

length = 500
features = list(range(length))
labels = tf.random.uniform([length], minval=0, maxval=2, dtype=tf.int32)
data = tf.transpose([range(length),
					 tf.random.uniform([length], minval=0, maxval=2, dtype=tf.int32)])

dataset = tf.data.Dataset.from_tensor_slices(data)

dataset.shuffle(length)

train_length = int(length / 5 * 4)
train_data = dataset.take(train_length)
test_data = dataset.skip(train_length)


assert isinstance(train_data.element_spec, tuple) and len(train_data.element_spec) > 0, \
	'When x is dataset, its members must be a tuple of either (inputs, targets) or (inputs, targets, sample_weights). Currently your tuple size is 0.'

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'], run_eagerly=True)
model.fit(train_data.batch(10), validation_data=test_data.batch(10), epochs=10)
```

If we ignore the assert, running the code throws error 

> ValueError: No gradients provided for any variable: ['dense/kernel:0', 'dense/bias:0', 'dense_1/kernel:0', 'dense_1/bias:0'].

The error reason may not be obvious that train_data doesn't return required examples, ie. "either (inputs, targets) or (inputs, targets, sample_weights)."

I hope the error message can be improved. Is it ok if we detect `len(train_data.element_spec)` in places like `tensorflow.python.keras.engine.data_adapter.DatasetAdapter._validate_args`? 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
People writting buggy code, learning dataset, not give correct shape

**Comment by rmothukuru** [comment]
@gqqnbig, 
Could reproduce the error with `Tensorflow Version 2.4`. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/bd1cd5555c30273efbe93f4f1b373db1/gh_47618.ipynb). 

Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce  the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d01da7f43a1b9e18f84e1dc753aea012/untitled150.ipynb)..Thanks !
