### ISSUE TITLE
Build TFLite Micro for RISC-V

### ISSUE THREAD

**Issue by ioannesKX** [tensorflow/tensorflow#47622]
@tensorflow/micro

How do I build TFLite Micro for RISC-V MCU's? I use:
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mcu_riscv TARGET_ARCH=riscv32_mcu hello_world_bin`
but the binary produced at **_/micro/tools/make/gen/mcu_riscv_riscv32_mcu_default/bin/_** seems to not have used the riscv-gcc toolchain as specified by _**mcu_riscv_makefile.inc**_. An x86-64 executable was built.

**Comment by Saduf2019** [comment]
@ioannesKX 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by ioannesKX** [comment]
> @ioannesKX
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.1 LTS x86_64**
- TensorFlow installed from (source or binary):  **Source**
- Tensorflow version (commit SHA if source): **commit 2780b863ca82403b4c080042e9ac3e5772189881 (HEAD -> master, origin/master, origin/HEAD)**
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):  **some RISC-V**

**Describe the problem**
Cannot compile TFLite Micro for RISC-V target. IDK if bug or if I'm following the wrong steps.

**Please provide the exact sequence of commands/steps when you ran into the problem**
After cloning, from the tensorflow directory:
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mcu_riscv TARGET_ARCH=riscv32_mcu hello_world_bin`

I'd expect this command to compile TFLite Micro using the riscv64-unknown-elf toolchain (as specified in flags in **_/micro/tools/make/targets/mcu_riscv_makefile.inc_**) and produce a RISC-V executable under _**/micro/tools/make/gen/mcu_riscv_riscv32_mcu_default/bin**_ , but it actually produces a normal x86 one (executes normally on my host machine), meaning the flags were not passed properly or something similar.

**Comment by ymodak** [comment]
Can you try with `TARGET=risc32_mcu` and check?
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world`
Also see https://github.com/tensorflow/tensorflow/issues/32041

**Comment by ioannesKX** [comment]
> Can you try with `TARGET=risc32_mcu` and check?
> `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world`
> Also see #32041

```
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:565: tensorflow/lite/micro/tools/make/targets/riscv32_mcu_makefile.inc: No such file or directory
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/targets/riscv32_mcu_makefile.inc'.  Stop.
```
On previous issues indeed `TARGET=riscv32_mcu` is used, but as this error implies, there should be a file `riscv32_mcu_makefile.inc` under **/targets** rather than the`mcu_riscv_makefile.inc` that exists now. If you search https://github.com/tensorflow/tensorflow/search?q=riscv32_mcu you can see that this is the TARGET expected from the rest of the code base.

I suspected there was a mistake in the filename and renamed `mcu_riscv_makefile.inc` to `riscv32_mcu_makefile.inc`, now the `make` command you gave me seems to start working as intended: it downloads the SiFive gcc-riscv toolchain and starts using it to compile, but I reach another error:
```
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_micro/obj/tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/start.S', needed by 'tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_micro/bin/hello_world'.  Stop.
```

[This seems to be the related PR.](https://github.com/tensorflow/tensorflow/commit/84b639d8582a0375db1b39edd6a50d39e21240ff)

**Comment by ioannesKX** [comment]
Another thing, if `hello_world` is not included in the `make` flags, compilation is stuck in another stage:
```
In file included from tensorflow/lite/micro/kernels/elu.cc:16:
./tensorflow/lite/kernels/internal/reference/elu.h: In function 'void tflite::reference_ops::Elu(const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*)':
./tensorflow/lite/kernels/internal/reference/elu.h:31:40: error: 'expm1' is not a member of 'std'; did you mean 'exp'?
   31 |     output_data[i] = val < 0.0f ? std::expm1(val) : val;
      |                                        ^~~~~
      |                                        exp
tensorflow/lite/micro/kernels/elu.cc: In function 'void tflite::{anonymous}::PopulateLookupTable(const TfLiteTensor*, const TfLiteTensor*, tflite::{anonymous}::TransformFunc, tflite::{anonymous}::OpData*)':
tensorflow/lite/micro/kernels/elu.cc:57:33: error: 'round' is not a member of 'std'; did you mean 'round'?
   57 |     const float rescaled = std::round(transformed * inverse_scale);
      |                                 ^~~~~
In file included from /opt/riscv/riscv64-unknown-elf/include/c++/10.2.0/cmath:45,
                 from ./tensorflow/lite/kernels/internal/reference/elu.h:18,
                 from tensorflow/lite/micro/kernels/elu.cc:16:
/opt/riscv/riscv64-unknown-elf/include/math.h:308:15: note: 'round' declared here
  308 | extern double round (double);
      |               ^~~~~
make: *** [tensorflow/lite/micro/tools/make/Makefile:633: tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_mcu_micro/obj/tensorflow/lite/micro/kernels/elu.o] Error 1
```

IDK if this is related or helps, but [in this (old) fork that ported TFLMicro to RISC-V](https://github.com/mars20/tensorflow/tree/riscv-mcu/tensorflow/lite/experimental/micro), the `round` function had some changes: https://github.com/mars20/tensorflow/commit/4fe29849f35cb1637f3a2dc8ea8162b1fef2ac7b#diff-d6578d7c90da9299018be4513de5fb5fcb7bdc8848df35222adb866e47eb82cb.

**Comment by ioannesKX** [comment]
I have pulled the above changes. They have fixed the issue with the round/expm functions, but a couple more have a similar problem. Result of same `make` command as above:

```
In file included from ./tensorflow/lite/kernels/internal/reference/reduce.h:21,
                 from tensorflow/lite/micro/kernels/reduce.cc:16:
./tensorflow/lite/kernels/internal/max.h: In function 'T tflite::TfLiteMax(const T&, const T&)':
./tensorflow/lite/kernels/internal/max.h:29:15: error: 'fmax' is not a member of 'std'; did you mean 'max'?
   29 |   return std::fmax(x, y);
      |               ^~~~
      |               max
In file included from ./tensorflow/lite/kernels/internal/reference/reduce.h:22,
                 from tensorflow/lite/micro/kernels/reduce.cc:16:
./tensorflow/lite/kernels/internal/min.h: In function 'T tflite::TfLiteMin(const T&, const T&)':
./tensorflow/lite/kernels/internal/min.h:29:15: error: 'fmin' is not a member of 'std'; did you mean 'min'?
   29 |   return std::fmin(x, y);
      |               ^~~~
      |               min
make: *** [tensorflow/lite/micro/tools/make/Makefile:672: tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_mcu_micro/obj/tensorflow/lite/micro/kernels/reduce.o] Error 1```

**Comment by marconi1964** [comment]
Similiar try on TFLM for RISC-V, but different progress and error.

I tried TFLM on MaixPy Amigo, which is also RISC V base MCU, but failed. I reported at [MaixPy repo issue](https://github.com/sipeed/MaixPy/issues/414), but no reply yet. See if I can get some input here.

I did the same with @ioannesKX by  renaming mcu_riscv_makefile.inc to riscv32_mcu_makefile.inc, but different make command, and it 'works', though not sure if that is the 'right' approach.

```
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ mv tensorflow/lite/micro/tools/make/targets/mcu_riscv_makefile.inc tensorflow/lite/micro/tools/make/targets/riscv32_mcu_makefile.inc 
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu generate_hello_world_make_project
```

I manually move the source files from tensorflow directory to MaixPy tool chain directory (clone from MaixPy hello_world example), and update the CMakeLists.txt. It seems working to some extent, but error happens with namespace, even though I modified the CXX flags to -std=c++11.
It seems opposite to [this PR - mars20@4fe2984# - the round function](https://github.com/mars20/tensorflow/commit/4fe29849f35cb1637f3a2dc8ea8162b1fef2ac7b#diff-d6578d7c90da9299018be4513de5fb5fcb7bdc8848df35222adb866e47eb82cb)

```
$ cd ~/maixpy/projects/TFLM_hello_world
$ python3 project.py build
.....
In file included from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.h:23,
                 from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.cc:16:
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h: In function 'T tflite::TfLiteRound(T)':
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:36:41: error: 'round' is not a member of 'std'
 DECLARE_STD_GLOBAL_SWITCH1(TfLiteRound, round);
                                         ^~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:33:39: note: in definition of macro 'DECLARE_STD_GLOBAL_SWITCH1'
     return TF_LITE_GLOBAL_STD_PREFIX::std_name(x);    \
                                       ^~~~~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:36:41: note: suggested alternative:
 DECLARE_STD_GLOBAL_SWITCH1(TfLiteRound, round);
                                         ^~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:33:39: note: in definition of macro 'DECLARE_STD_GLOBAL_SWITCH1'
     return TF_LITE_GLOBAL_STD_PREFIX::std_name(x);    \
                                       ^~~~~~~~
In file included from /opt/kendryte-toolchain/riscv64-unknown-elf/include/c++/8.2.0/cmath:45,
                 from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.h:18,
                 from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.cc:16:
/opt/kendryte-toolchain/riscv64-unknown-elf/include/math.h:308:15: note:   'round'
 extern double round (double);
               ^~~~~
In file included from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.h:23,
                 from /home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/quantization_util.cc:16:
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h: In function 'T tflite::TfLiteExpm1(T)':
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:37:41: error: 'expm1' is not a member of 'std'
 DECLARE_STD_GLOBAL_SWITCH1(TfLiteExpm1, expm1);
                                         ^~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:33:39: note: in definition of macro 'DECLARE_STD_GLOBAL_SWITCH1'
     return TF_LITE_GLOBAL_STD_PREFIX::std_name(x);    \
                                       ^~~~~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:37:41: note: suggested alternative: 'exp'
 DECLARE_STD_GLOBAL_SWITCH1(TfLiteExpm1, expm1);
                                         ^~~~~
/home/ubuntu/maixpy/projects/amigo_tflm/main/tensorflow/lite/kernels/internal/cppmath.h:33:39: note: in definition of macro 'DECLARE_STD_GLOBAL_SWITCH1'
     return TF_LITE_GLOBAL_STD_PREFIX::std_name(x);    \
                                       ^~~~~~~~
```

**Comment by chuantunglin** [comment]
> > Can you try with `TARGET=risc32_mcu` and check?
> > `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world`
> > Also see #32041
> 
> ```
> $ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world
> tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
> tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
> tensorflow/lite/micro/tools/make/Makefile:565: tensorflow/lite/micro/tools/make/targets/riscv32_mcu_makefile.inc: No such file or directory
> make: *** No rule to make target 'tensorflow/lite/micro/tools/make/targets/riscv32_mcu_makefile.inc'.  Stop.
> ```
> 
> On previous issues indeed `TARGET=riscv32_mcu` is used, but as this error implies, there should be a file `riscv32_mcu_makefile.inc` under **/targets** rather than the`mcu_riscv_makefile.inc` that exists now. If you search https://github.com/tensorflow/tensorflow/search?q=riscv32_mcu you can see that this is the TARGET expected from the rest of the code base.
> 
> I suspected there was a mistake in the filename and renamed `mcu_riscv_makefile.inc` to `riscv32_mcu_makefile.inc`, now the `make` command you gave me seems to start working as intended: it downloads the SiFive gcc-riscv toolchain and starts using it to compile, but I reach another error:
> 
> ```
> make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_micro/obj/tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/start.S', needed by 'tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_micro/bin/hello_world'.  Stop.
> ```
> 
> [This seems to be the related PR.](https://github.com/tensorflow/tensorflow/commit/84b639d8582a0375db1b39edd6a50d39e21240ff)

I have the same issue with this. Has it been resolved yet?

**Comment by ioannesKX** [comment]
Managed to compile and run the examples on Spike so I think it's resolved now: https://github.com/tensorflow/tflite-micro/issues/311 @chuantunglin
