### ISSUE TITLE
AttributeError when concatenating window datasets

### ISSUE THREAD

**Issue by m4ff** [tensorflow/tensorflow#47629]
**System information**
- Windows 10
- TensorFlow installed from pip
- TensorFlow version 2.4.1 (git v2.4.0-49-g85c8b2a817f)

**Current behavior**
Concatenating two window datasets throws the following error: `AttributeError: 'DatasetSpec' object has no attribute 'most_specific_compatible_shape'`

**Expected behavior**
The code below returns a new dataset that is the concatenation of the two

**Standalone code to reproduce the issue**
```
import tensorflow as tf

tf.data.Dataset.range(3).window(1).concatenate(tf.data.Dataset.range(3, 6).window(1))
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b591a02e5118c4ec4a0a35266a16c43d/47629.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210531,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/ef4acf846badc579a02f60defcd0806d/untitled151.ipynb)..Thanks !
