### ISSUE TITLE
Ability to Save Checkpoints Every N Steps using Estimator

### ISSUE THREAD

**Issue by craymichael** [tensorflow/tensorflow#4763]
TensorFlow Version: r0.10.0rc0

For TensorFlow/SKFlow/tf,learn Estimators, there is no option for specifying when an Estimator saves checkpoints other than `save_checkpoints_secs` in a `RunConfig`, which isn't usable for a monitor such as `ValidationMonitor`. For example, if I want to do early stopping and check every 10 steps, it is definitely not guaranteed that new checkpoints were saved for the model, even if I specify `save_checkpoints_secs` to be 1 second.

### Tried:
It is currently not possible to use a `CheckpointMonitor` with an `Estimator` (e.g. `LinearClassifier`) as far as I can tell. There is no saver nor Scaffold I can specify that captures the same variables it does normally.

When can we expect this capability, and are there workarounds currently?

**Comment by tatatodd** [comment]
@ispirmustafa might have some thoughts on this.

**Comment by craymichael** [comment]
Any thoughts on this?

**Comment by ispirmustafa** [comment]
You can use `supervisor_save_model_steps` in a RunConfig.

**Comment by craymichael** [comment]
Ok I see that a RunConfig has the `save_checkpoints_steps` parameter in master but not 0.10 nor 0.11. I'll evaluate if it's worth cloning and building master. Thanks

**Comment by tatatodd** [comment]
Thanks for the info @ispirmustafa!

@craymichael I'm closing this out, but feel free to comment or open a new issue if you have further problems.

**Comment by jinghuangzhu** [comment]
Is save_checkpoints_steps now in version r1.0? I find it really useful. Thanks.
