### ISSUE TITLE
Why not use multiple streams for model calculations?

### ISSUE THREAD

**Issue by Richie-yan** [tensorflow/tensorflow#47637]
I see that Tensorflow uses one stream for model calculation by default, why not use multiple streams? Will there be any impact on using multiple streams?
I think that for some OPs that are not dependent on models, using multiple streams will increase the parallelism of calculations, then increasing the end-to-end training speed of the model.
Any advices can help me.

**Comment by Saduf2019** [comment]
@Richie-yan 
Can you please share some stand alone code in support of this request.
