### ISSUE TITLE
Cannot compile tensorflow lite application when -Werror=undef is actived

### ISSUE THREAD

**Issue by Nabil-tf** [tensorflow/tensorflow#47638]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Na
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): Tensorflow lite r2.4
- Python version: Na
- Bazel version (if compiling from source): Na
- GCC/Compiler version (if compiling from source): gcc version 9.2.0 
- CUDA/cuDNN version: Na
- GPU model and memory: Na

**Describe the current behavior**
When I try to compile the minimal.cc code example with the compilation flag -Werror=undef activated I have the following error :

g++ -std=c++17 -pthread -Werror=undef  minimal.cc -o minimal -I./tensorflow/include -L./tensorflow/lib -ltensorflow-lite -ldl
In file included from ./tensorflow/include/tensorflow/lite/allocation.h:27,
                 from ./tensorflow/include/tensorflow/lite/interpreter.h:34,
                 from minimal.cc:16:
./tensorflow/include/tensorflow/lite/c/common.h:87:26: error: "\__clang_major__" is not defined, evaluates to 0 [-Werror=undef]
  87 |     defined(HEXAGON) || (\__clang_major__ == 7 && \__clang_minor__ == 1) 
       |                                         ^~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors

**Describe the expected behavior**

Should compile without error

**Standalone code to reproduce the issue**

To reproduce just compile the code example minimal.cc with the follow command :
`g++ -std=c++17 -pthread -Werror=undef  minimal.cc -o minimal -I<Path to tf-lite include> -L<Path to tf-lite lib> -ltensorflow-lite -ldl`

**Other info / logs** 

It looks that the variable \__clang_major__ was not yet defined, so we found a way to solve this issue by adding (defined(\_clang_)   in the file [common.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/common.h) :

Here is the diff

diff \--git a/tensorflow/include/tensorflow/lite/c/common.h b/tensorflow/include/tensorflow/lite/c/common.h
index 5c2f408..bdcd636 100644
--- a/tensorflow/include/tensorflow/lite/c/common.h
+++ b/tensorflow/include/tensorflow/lite/c/common.h
@@ -84,7 +84,7 @@ typedef struct TfLiteIntArray {
 // https://github.com/google/re2/commit/b94b7cd42e9f02673cd748c1ac1d16db4052514c
 #if (!defined(\__clang__) && defined(\__GNUC__) && \__GNUC__ == 6 && \
      \__GNUC_MINOR__ >= 1) ||                                      \
\-    defined(HEXAGON) || (\__clang_major__ == 7 && \__clang_minor__ == 1)
\+    defined(HEXAGON) || (defined(\_clang_) && \__clang_major__ == 7 && \__clang_minor__ == 1) 
   int data[0];
 #else

With this modification the compilation finish without error

**Comment by abattery** [comment]
@terryheo could you review this suggestion?

**Comment by terryheo** [comment]
The change makes sense to me. Will you send a PR?

**Comment by terryheo** [comment]
Nevermind, I'm making a PR.
