### ISSUE TITLE
ssd_mobilenet_v2 to 8-bit quantized tflite model conversion error

### ISSUE THREAD

**Issue by sandeep22-v** [tensorflow/tensorflow#47631]
Tensorflow version : 2.4.1

I have been trying to convert tensorflow model 'ssd_mobilenet_v2' to 8 bit quantized tflite model.
I was successful in converting from tf to just tfllite model ,BUT I was unable to convert to 8 bit quantized tflite model as it shows some errors.
My code is : 

import tensorflow as tf
import numpy as np
import cv2
import os

saved_model_dir = '/home/ssd_mobilenet_v2_2'

folder = '/mscoco_dataset_images'
 
def representative_data_gen() :
 i = 1
 for filename in os.listdir(folder): 
  k = (i/number_of_images)*100
  print(' PROCESSING :  ',k,' %')
  testimage = cv2.imread(os.path.join(folder,filename))
  testimage = np.expand_dims(testimage,0)      
  yield[testimage.astype(np.uint8)]   # doubt,why it is uint8 and not float32
  i = i+1   

onverter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir,signature_keys = ["serving_default"]) 

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_data_gen

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8 ,tf.lite.OpsSet.SELECT_TF_OPS] # part after coma is important for preventing tf.size() error

converter.inference_input_type = tf.uint8

converter.inference_output_type = tf.uint8

converter.allow_custom_ops = True #is it required?

tflite_model = converter.convert()

with open('batch_q_model.tflite', 'wb') as f:
  f.write(tflite_model)

**_I'm getting the error as :_**  
**RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor tfl.cast
Empty min/max for tensor tfl.cast**

Why is this error coming?I know it is an issue with related to calibration,i.e,representative dataset,but I've inputted the official mscoco dataset images.
Can someone please tell how to rectify this error

**Comment by sandeep22-v** [comment]
@jvishnuvardhan sir I've posted the issue..Please help me with this

**Comment by Saduf2019** [comment]
@sandeep22-v 
The code provided has errors can you please share standalone code such that we can replicate the issue reported, or share a colab gist with the error reported.

**Comment by sandeep22-v** [comment]
> @sandeep22-v
> The code provided has errors can you please share standalone code such that we can replicate the issue reported, or share a colab gist with the error reported.

Sure sir... I think the issue you mentioned was about the represenative_data_gen() function which need external folder to work,.
I've simulated it  in the below code,so this code will run as a standalone one.
Also ssd_mobilenet_v2 is attached as zip file


import tensorflow as tf
import numpy as np
import cv2
import os

saved_model_dir = '/home/ssd_mobilenet_v2_2'
def representative_data_gen():
    for _ in range(100):
      print('    PROCESSING    ')
      data = np.random.rand(1, 244, 244, 3)
      yield [data.astype(np.uint8)]

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir,signature_keys = ["serving_default"])

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_data_gen

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8 ,tf.lite.OpsSet.SELECT_TF_OPS] # part after coma is important for preventing tf.size() error

converter.inference_input_type = tf.uint8

converter.inference_output_type = tf.uint8

converter.allow_custom_ops = True #is it required?

tflite_model = converter.convert()

with open('batch_q_model.tflite', 'wb') as f:
  f.write(tflite_model)

[ssd_mobilenet_v2_2.zip](https://github.com/tensorflow/tensorflow/files/6099523/ssd_mobilenet_v2_2.zip)

**Comment by abattery** [comment]
@ethkim could you triage this issue?

**Comment by sandeep22-v** [comment]
> @ethkim could you triage this issue?

Thank you sir for the response

**Comment by sandeep22-v** [comment]
UPDATE : I downgraded tensorflow from 2.4.1 to 2.2.0 and ran the same code..

Got a new kind of error 
**ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[1, None, None, 3]'.**

Can you please tell me how version change surprisingly changes the type of error

**Comment by sandeep22-v** [comment]
### 1. System information

- OS Platform and Distribution :  Linux Ubuntu 20.04
- TensorFlow installation -pip package 
-  TensorFlow version : 2.4.1

Was trying to convert ssd_mobilenet_v2_2 to tflite version.

### 2. Code

The code was : 

import tensorflow as tf
saved_model_directory = '/ssd_mobilenet_v2_2'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_directory)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

**'tf.Size' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Size {device = ""}**

How can this error be rectified

**Comment by ameyparanjape** [comment]
@sandeep22-v I am getting a similar error. What did you do to fix the issue? Does downgrading tensorflow work?
Brief log of my error:
```
ConverterError: <unknown>:0: error: loc("strided_slice_10"): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: error: loc("strided_slice_11"): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: error: loc("strided_slice_12"): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: error: loc("strided_slice_13"): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

**Comment by sandeep22-v** [comment]
> @sandeep22-v I am getting a similar error. What did you do to fix the issue? Does downgrading tensorflow work?
> Brief log of my error:
> 
> ```
> ConverterError: <unknown>:0: error: loc("strided_slice_10"): 'tf.StridedSlice' op is neither a custom op nor a flex op
> <unknown>:0: error: loc("strided_slice_11"): 'tf.StridedSlice' op is neither a custom op nor a flex op
> <unknown>:0: error: loc("strided_slice_12"): 'tf.StridedSlice' op is neither a custom op nor a flex op
> <unknown>:0: error: loc("strided_slice_13"): 'tf.StridedSlice' op is neither a custom op nor a flex op
> <unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
> 	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
> ```

Sir are you trying to convert ssd_mobilenet_v2 to tflite?

**Comment by ameyparanjape** [comment]
No, I was converting efficientdet model to efficientdet-lite and having trouble with that. But [this](https://github.com/google/automl/issues/966#issuecomment-804352674) worked

**Comment by pjpratik** [comment]
Hi @sandeep22-v I was checking if this is still an issue. 

Tensorflow hub provides the pretrained lite models for object detection tasks. The sd_mobilenet_v2_100 for int8 can be found [here](https://tfhub.dev/iree/lite-model/ssd_mobilenet_v2_100/int8/default/1) which is trained on coco dataset.

Feel free to close the issue if it is already resolved.

Thanks.
