### ISSUE TITLE
arm_nn_mat_mult_nt_t_s8.c:111: undefined reference to `__SXTB16_RORn

### ISSUE THREAD

**Issue by mushtaqsyed** [tensorflow/tensorflow#47630]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) NA
- TensorFlow installed from (source or binary):source
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Could you please help with the following?
Thanks a lot!

Compiling the hello_world example code on the Arduino Nano BLE 33 gives the following error: 
Error compiling for Arduino Nano BLE 33. 
I think it is related to the error below. Please see the partial dump pasted below. 
arm_nn_mat_mult_nt_t_s8.c:137: more undefined references to `__SXTB16_RORn' 

C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\kissfft\kiss_fft.c:378:9: warning: incompatible implicit declaration of built-in function 'memcpy'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\kissfft\kiss_fft.c:378:9: note: include '<string.h>' or provide a declaration of 'memcpy'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\kissfft\kiss_fft.c:378:9: warning: argument 2 null where non-null expected [-Wnonnull]
         memcpy(fout,tmpbuf,sizeof(kiss_fft_cpx)*st->nfft);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\kissfft\kiss_fft.c:378:9: note: in a call to built-in function 'memcpy'
libraries\Arduino_TensorFlowLite\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions\arm_nn_mat_mult_nt_t_s8.c.o: In function `arm_nn_mat_mult_nt_t_s8':
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:111: undefined reference to `__SXTB16_RORn'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:112: undefined reference to `__SXTB16_RORn'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:118: undefined reference to `__SXTB16_RORn'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:125: undefined reference to `__SXTB16_RORn'
C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:136: undefined reference to `__SXTB16_RORn'
libraries\Arduino_TensorFlowLite\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions\arm_nn_mat_mult_nt_t_s8.c.o:C:\Users\mushtaqsyed\Documents\Arduino\libraries\Arduino_TensorFlowLite\src\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:137: more undefined references to `__SXTB16_RORn' follow
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Nano 33 BLE.

**Comment by Saduf2019** [comment]
@mushtaqsyed 
This is not a tensorflow related issue, please refer to this [link](https://forum.arduino.cc/index.php?topic=676185.0), and open this issue in relevant repo.
