### ISSUE TITLE
Plotting a TensorFlow Graph with dot/graphviz

### ISSUE THREAD

**Issue by jameshfisher** [tensorflow/tensorflow#47647]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**

There is [`tf.keras.utils.plot_model`](https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model), which draws a Keras model using dot/graphviz. It's used in many tutorials/notebooks, and I've found it very useful. However, it only works for Keras models. I could not find a way to plot arbitrary TensorFlow graphs.

I wanted to understand my TensorFlow graph, so [I ended up making `plot_graph`](https://gist.github.com/jameshfisher/f99ad86fc23d2ae7c856ee2f2ec89cd8). It lets you do:

```python
def py_func(x):
  if tf.random.uniform(()) < 0.5:
    x = x*x
  x = tf.cast(x, 'float32')
  return 2*x + 5

tf_func = tf.function(py_func)
tf_concrete_func = tf_func.get_concrete_function(tf.constant(3))
my_graph = tf_concrete_func.graph
plot_graph(my_graph)
```

This generates this image:

![graph](https://user-images.githubusercontent.com/166966/110341720-901d1300-8022-11eb-9397-c583a60cca70.png)

If there's interest, I could polish this and contribute it as a TensorFlow feature.

**Will this change the current api? How?**

No, it would be a standalone additional function, e.g. `tf.graph_util.plot_graph`.

**Who will benefit with this feature?**

* Those wanting to understand their TensorFlow graph visually
* Those wanting to understand the TensorFlow graph language through experimentation
* Tutorial/notebook writers
* Those not using TensorBoard

**Any Other info.**

* I'm aware of TensorBoard, but I haven't really used it. Is everyone using that to visualize their graphs?

**Comment by ymodak** [comment]
Using TensorBoard’s Graphs [dashboard](https://www.tensorflow.org/tensorboard) is recommended for examining your TensorFlow model.
Perhaps we may want to identify if there are any limitations of using TensorBoard's Graphs for your use case which can make a point to add/update the feature?

**Comment by jameshfisher** [comment]
@ymodak okay, thanks. My main issue with TensorBoard is fairly fundamental - it only works interactively as a separate black box. Saving an image programmatically is more flexible - I can put images in a blog post, I can keep a history of images, I can generate images in CI, etc. That said, the TensorBoard graph dashboard seems to work for understanding my graph structure, which was my immediate use case, so I'll close this issue.
