### ISSUE TITLE
Typo issue in tf.keras.losses docs

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#47642]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy
https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy

### Clear description

https://github.com/tensorflow/tensorflow/blob/5b5527d81085db5dadf3886a37fef7c4943ad704/tensorflow/python/keras/losses.py#L587
(BinaryCrossentropy)
https://github.com/tensorflow/tensorflow/blob/5b5527d81085db5dadf3886a37fef7c4943ad704/tensorflow/python/keras/losses.py#L748
(SparseCategoricalCrossentropy)

Above lines should be

```
          **Note - Using from_logits=True may be more numerically stable.**
```

like

https://github.com/tensorflow/tensorflow/blob/5b5527d81085db5dadf3886a37fef7c4943ad704/tensorflow/python/keras/losses.py#L667

(CategoricalCrossentropy)

**Comment by zenogantner** [comment]
Thank you for reporting this. I am currently preparing a PR for this, but I will go through that file in detail to spot more typos, because the [contributing guidelines](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) say we should avoid fixing single typos because every PR causes several hours of GPU/CPU times for testing.

**Comment by Saduf2019** [comment]
@zenogantner 
Thank you for submitting the pr,the issue will closed once the pr is merged.

**Comment by Saduf2019** [comment]
Thank you for the pr, this issue will be moved to closed status once the pr is merged.

**Comment by jeongukjae** [comment]
@Saduf2019 

I checked the changed lines in the linked PR (#47645). I think this issue can be closed.

But is it right to remove those lines instead of fixing highlightings? In my experiences, those notes were useful in numerically unstable situations like the mixed-precision training.

**Comment by zenogantner** [comment]
Not sure. @fchollet, the main author of Keras, decided to remove the lines, I assume he knows what he is doing there.

**Comment by rmothukuru** [comment]
@jeongukjae,
Closing the issue as [the PR](https://github.com/tensorflow/tensorflow/pull/47645) has been merged. Thanks!
