### ISSUE TITLE
GPU execution not deallocating memory in iOS swift

### ISSUE THREAD

**Issue by jestingeorgejacob1** [tensorflow/tensorflow#47640]
**System information**
- OS Platform - iOS, swift
- Mobile device : iPhone, iPad
- TensorFlow installed from (source or binary): Pod.
- TensorFlow version (use command below): 2.3.0

**Issue**
Initialised interpreter once with below code
var delegate = MetalDelegate()
self.interpreter = try Interpreter(modelPath: modelPath, options: nil, delegates: [delegate])
self.interpreter?.allocateTensors()

Then executed the below code each time on running the inference
var inputTensor = try interpreter?.copy(input, toInputAt:0)
try interpreter?.invoke()
var outputTensor = try interpreter?.output(at: 0)

On running the .invoke() in GPU (using MetalDelegate) the memory consumption is increasing and not decreasing. How do i deallocate the unused memory? This is working fine in CPU.

**Comment by multiverse-tf** [comment]
@teijeong, could you help with this as you are more experienced w/ iOS?

**Comment by yyoon** [comment]
Also cc: @impjdi

**Comment by teijeong** [comment]
Hi @jestingeorgejacob1 , can you give more details about your problem? When I tested TFLite runtime the memory usage goes up, but it goes back to normal level once the Interpreter is recycled. You can expect the memory consumption to go up at least by model file size, so if you can provide your model, model size, and amount of memory increased (best to use Instruments) it would be great.

Does it increase for every inference, or increase once and stays at the same level?

**Comment by jestingeorgejacob1** [comment]
Hi @teijeong,  yes, it increases for every inferences. For my use case I am initialising the interpreter once and running the inference with same interpreter multiple times say about 200+ times. The memory keeps increasing by 5MB on every inference. I tried with the tflite model in style transfer iOS app by running it in a forloop and it seems to be increasing memory.
Is there a way to release the memory in GPU after an inference is completed? How can i make sure Interpreter is recycled after every inference.?
Thanks for the reply

**Comment by impjdi** [comment]
We're using this on production (ObjC) and memory doesn't seem to increase.  Could it be that there is something leaking in Swift integration?  Unfortunately, I have never used Swift myself, and can't tell.

As @teijong said, providing the model file & the actual code snippet on how you use should help diagnosing the issue.

**Comment by jestingeorgejacob1** [comment]
@impjdi, @teijeong  - Thanks for the reply. 
Please find the attached sample xcode project. This project is downloaded from https://github.com/tensorflow/examples/tree/master/lite/examples/style_transfer/ios. Can you please install the pods and check? I have  made an update in line 226 of ViewController.swift to run the invoke function inside a loop. After running the project, once an image is selected the memory can be seen increasing.

[ios.zip](https://github.com/tensorflow/tensorflow/files/6154211/ios.zip)
