### ISSUE TITLE
 import tensorflow as tf gives an error

### ISSUE THREAD

**Issue by Saagarika99** [tensorflow/tensorflow#47654]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version:
- Python version:Python 3.5.6
- Installed using virtualenv? pip? conda?:pip 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

In [1]: import tensorflow as tf
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

C:\Users\Saagarika\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py in <module>()
     22
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26

C:\Users\Saagarika\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py in <module>()
     52
     53 # Protocol buffers
---> 54 from tensorflow.core.framework.graph_pb2 import *
     55 from tensorflow.core.framework.node_def_pb2 import *
     56 from tensorflow.core.framework.summary_pb2 import *

C:\Users\Saagarika\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\core\framework\graph_pb2.py in <module>()
      8 from google.protobuf import reflection as _reflection
      9 from google.protobuf import symbol_database as _symbol_database
---> 10 from google.protobuf import descriptor_pb2
     11 # @@protoc_insertion_point(imports)
     12

C:\Users\Saagarika\Anaconda3\envs\tensorflow\lib\site-packages\google\protobuf\descriptor_pb2.py in <module>()
   1837 FileDescriptorSet = _reflection.GeneratedProtocolMessageType('FileDescriptorSet', (_message.Message,), dict(
   1838   DESCRIPTOR = _FILEDESCRIPTORSET,
-> 1839   __module__ = 'google.protobuf.descriptor_pb2'
   1840   # @@protoc_insertion_point(class_scope:google.protobuf.FileDescriptorSet)
   1841   ))

TypeError: Expected a message Descriptor, got Descriptor

**Comment by Saduf2019** [comment]
@Saagarika99 
Please refer to this issue and verify the requirements : #42367, #47517
