### ISSUE TITLE
tensorflow-gpu==1.14.0 does not support python 3.6.12-debug

### ISSUE THREAD

**Issue by tywofxd** [tensorflow/tensorflow#47660]
**System information**
- I haven't written custom code.
- OS Platform and Distribution :Linux Ubuntu 18.04.
- Python version: python 3.6.12-debug

**Describe the current behavior**
I used python 3.6.12-debug built by pyenv:
$ pip -V
pip 18.1 from /home/yawen/.pyenv/versions/3.6.12-debug/lib/python3.6/site-packages/pip (python 3.6)

I wanted to install tensorflow 1.14.0, but I got the following error:
$python -m pip install tensorflow-gpu==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0
ERROR: No matching distribution found for tensorflow-gpu==1.14.0

I checked my whether my python was 32bits or 64bits:
>>> import platform
>>> platform.architecture()
('64bit', '')

It is 64bits, which satisfies the requirement of tensorflow. I don't know why tensorflow does not support python 3.6.12-debug.

**Describe the expected behavior**
I hope I can successfully install tensorflow on python 3.6.12-debug, or any other version of python-debug.

**Comment by Saduf2019** [comment]
@tywofxd 
There is no support for tf 1.x , so please update  tf 2.x and let us know.

**Comment by tywofxd** [comment]
Following your instruction, I tried to install tensorflow 2.0.0, but it still did not work. Here is what I have done:
$ pyver=3.6.12
$ eval "$(pyenv init -)"
$ pyenv shell "$pyver"-debug
$ python -V
Python 3.6.12
$ pip -V
pip 21.0.1 from /home/yawen/.pyenv/versions/3.6.12-debug/lib/python3.6/site-packages/pip (python 3.6)
$ python -m pip install tensorflow==2.0.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0
ERROR: No matching distribution found for tensorflow==2.0.0
$ python -m pip install tensorflow==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0
ERROR: No matching distribution found for tensorflow==2.0.0

I met the same error as installing tensorflow 1.14.0. Can you give me more suggestions? I appreciate it very much if you can help me.

**Comment by tywofxd** [comment]
Hello!
Following your instruction, I tried to install tensorflow 2.0.0, but it still did not work. Here is what I have done:
$ pyver=3.6.12
$ eval "$(pyenv init -)"
$ pyenv shell "$pyver"-debug
$ python -V
Python 3.6.12
$ pip -V
pip 21.0.1 from /home/yawen/.pyenv/versions/3.6.12-debug/lib/python3.6/site-packages/pip (python 3.6)
$ python -m pip install tensorflow==2.0.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0
ERROR: No matching distribution found for tensorflow==2.0.0
$ python -m pip install tensorflow==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0
ERROR: No matching distribution found for tensorflow==2.0.0
I met the same error as installing tensorflow 1.14.0. Can you give me more suggestions? I appreciate it very much if you can help me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 中午1:07
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"ywtan"<yawentan_xd@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] tensorflow-gpu==1.14.0 does not support python 3.6.12-debug (#47660)





 
@tywofxd
 There is no support for tf 1.x , so please update  tf 2.x and let us know.

**Comment by Saduf2019** [comment]
@tywofxd 
TensorFlow v2.0 is compatible with Python 3.5 - 3.7. For more information, please take a look at the [tested build configurations.
](https://www.tensorflow.org/install/source_windows#cpu).

Please verify with this [comment](Please post output of python --version, python -m pip --version and python -m pip install -vvv tensorflow) for compatibility, is your python version 64 bit.


Also please refer to similar issues: #47517, #39130, #31939 , [link](https://github.com/tensorflow/tensorflow/issues/35646#issuecomment-571876409)

**Comment by Volker-Weissmann** [comment]
I can confirm this bug. `pip install tensorflow` works with 3.8.5-debug and 3.6.12 but not with 3.6.12-debug. pip version is 21.0.1.

[Here](https://www.tensorflow.org/install/pip), you just say that `Python 3.5–3.8` is supported, which is not true because 3.6.12-debug is a Python version 3.5-3.8 .

All python versions were installed using pyenv.

**Comment by Saduf2019** [comment]
@@tywofxd

You might be facing this issue because of the following reasons

You are running 32-bit Python or 32-bit OS
You have not installed the Microsoft Visual C++ Redistributable package
Your CPU does not support AVX instructions.
Please take a look at the system requirements and check if you have the correct dependencies installed.

Also, check this similar duplicate issue: #46124, #46738, #46788, #46490, #45398

Thanks!

**Comment by Volker-Weissmann** [comment]
The point is that (on Arch Linux)
`pyenv install 3.6.12 `          and
`pyenv install 3.8.5 --debug`
gives you a python version that supports tensorflow, but
`pyenv install 3.6.12 --debug`
gives you a python version that does not support tensorflow.

 3.8.5-debug and 3.6.12 but not with 3.6.12-debug

> @@tywofxd
> 
> You might be facing this issue because of the following reasons
> 
> You are running 32-bit Python or 32-bit OS

Nope, everything is 64-bit
> You have not installed the Microsoft Visual C++ Redistributable package

N/A, I'm on Arch Linux.

> Your CPU does not support AVX instructions.

/proc/cpuinfo includes the line "flags : ... avx ... avx2 ..."

> Please take a look at the system requirements and check if you have the correct dependencies installed.
> 
> Also, check this similar duplicate issue: 
> #46124

N/A, I'm on Arch Linux
> #46738

Includes no new info

> #46788

1. different error message
2. The cpu supports avx
3. If the cpu would not support avx, the other python version would probably also not work.
4. It is reproducible on different devices
 
>#46490


1. different error message
2. The gpu supports cuda
3. If the gpu would not support cudo, the other python version would probably also not work.
4. It is reproducible on different devices

> #45398

Different error message
> 
> Thanks!

**Comment by mihaimaruseac** [comment]
TF 1.x is no longer supported.

**Comment by Volker-Weissmann** [comment]
> TF 1.x is no longer supported.

Yes, but this Problem affects also newer versions.

With python 3.6.12-debug, pip install tensorflow does not work.

**Comment by Saduf2019** [comment]
@Volker-Weissmann 
As this issue was opened with refernce to 1.x, can you please create anew issue with 2.x and the code/steps and error faced [errorlogs]

**Comment by Volker-Weissmann** [comment]
> @Volker-Weissmann
> As this issue was opened with reference to 1.x, can you please create anew issue with 2.x and the code/steps and error faced [errorlogs]

Done: https://github.com/tensorflow/tensorflow/issues/47991

**Comment by ReetKaur15** [comment]
I am facing the same issue with python 3.11.4
