### ISSUE TITLE
Tensorflow 2.3.1 training does not use GPU but CPU with  CUDA 11.2 

### ISSUE THREAD

**Issue by awaisbajwaml** [tensorflow/tensorflow#47669]
I am trying to train a custom dataset with the following backbone 

ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8

I have the following information about the system 

### System information
 Ubuntu 18.04)**:
TensorFlow 2.3.1
TensorFlow version
Python version 3.6
CUDNN 11.2 cuDNN 8.5
GPU K80

I get the following error when I try to train the model 

When I try to train my model it showed the following log when starting training and I see that it does not use GPU at all..

![image](https://user-images.githubusercontent.com/47017344/110425796-f5005980-8072-11eb-99ca-281c03cdeed0.png)

Here is the output of the NVIDA GPU - that is nothing is used

![image](https://user-images.githubusercontent.com/47017344/110425826-00538500-8073-11eb-8035-532a14ab0e27.png)

**Comment by awaisbajwaml** [comment]
The training has started but it is using CPU

![image](https://user-images.githubusercontent.com/47017344/110427640-0f880200-8076-11eb-9f26-e92723b9bcd7.png)

**Comment by Saduf2019** [comment]
@awaisbajwaml 
Please upgrade to tf 2.4 and let us know, as 11.0 is tested for tf 2.4 onwards.
Cuda 11.2 is work in progress, you may refer to [this issue](47568), for future updates on it.

**Comment by awaisbajwaml** [comment]
@Saduf2019 

I am able to solve the issue, here are the steps:

First I upgraded to 2.4.0 but it gave me multiple errors.

After that, I used symlinks to start the training again, and now it is working fine. 

I have summarized a blog post [here](https://awaisbajwa.medium.com/tensorflow-2-4-with-cuda-11-2-gpu-training-fix-87f205215419) and hence closing the issue. 

Thanks for your help
