### ISSUE TITLE
Update aliasing in tf.linalg.band_part docs

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#47662]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/linalg/band_part

### Clear description

https://github.com/tensorflow/tensorflow/blob/56903ed0419882e004d4467dec452684b106e46f/tensorflow/core/api_def/base_api/api_def_MatrixBandPart.pbtxt#L50-L66

`tf.matrix_band_part` in above lines should be `tf.linalg.band_part`. (`tf.matrix_band_part` is moved to `tf.compat.v1.matrix_band_part`)

The below links should also be fixed

* https://github.com/tensorflow/tensorflow/blob/011228639301a8ed60d39c94ab096b074091bb4a/tensorflow/go/op/wrappers.go
* https://github.com/tensorflow/tensorflow/blob/0748d9a3ab284f7c9461985db478d09e2873cf1a/tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td

**Comment by ymodak** [comment]
@jeongukjae Are you still interested to raise a PR for this?
Note that `wrappers.go` and `tf_generated_ops.td` are machine generated files therefore we should not edit manually.

**Comment by jeongukjae** [comment]
@ymodak I tried to fix this issue, but I don't use Golang, so I don't know how exactly auto-generate that files. I think it would be better that other people fix this.

**Comment by ymodak** [comment]
This is fixed with tf-nightly docs. Thanks!
https://www.tensorflow.org/api_docs/python/tf/linalg/band_part?version=nightly
