### ISSUE TITLE
Possible memory leak cloning a model in memory with TF 2.3.1

### ISSUE THREAD

**Issue by OliverPfau** [tensorflow/tensorflow#47673]
Hi,

I created a flask application which loads tensorflow models on startup. When an inference request is coming, the model is cloned in memory for the request like this:

```
model_copy =  tf.keras.models.clone_model(model)
model_copy.build()
model_copy.set_weights(model.get_weights())
```

The flask app runs in docker. After several requests the docker container crashed. With each request the RAM is increasing. After disabling the model cloning and doing the requests with one model in memory with locking, the memory does no more increasing.

**System information**
- OS Platform and Distribution: debian 10
- TensorFlow installed from: binary
- TensorFlow version: v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.6.9

**Comment by amahendrakar** [comment]
@OliverPfau,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by OliverPfau** [comment]
The model is a tf.keras.Sequential model learning image classification problem:

```
model = tf.keras.Sequential([
...
])
```
save it like this:
`model.save(model_save_path)`

load it:
`model = tf.keras.models.load_model(model_path)`

each time I make a in memory copy the RAM is increasing.
Cloning:
```
model_copy =  tf.keras.models.clone_model(model)
model_copy.build()
model_copy.set_weights(model.get_weights())
```

**Comment by amahendrakar** [comment]
@OliverPfau,
Similiar issue [#45453](https://github.com/tensorflow/tensorflow/issues/45453#issuecomment-768554610) was fixed in the tf-nightly version.

Could you please update TensorFlow and check if you are facing the same issue with TF v2.4.1 and TF-nightly as well? Thanks!

**Comment by OliverPfau** [comment]
I did some test inside docker container. I hav 3 tensorflow image classification models. Each model is invoked with the same image data 100 times. So I have 300 model invokations in summary for my test.

No model cloning -> use one instance for each model (3 in summary) and locking
With model cloning -> for each model invokation the model is cloned

No model cloning TF 2.3.1: used RAM on start: 0,982 Gb; used RAM after test: 1,121 Gb
With model cloning TF 2.3.1: used RAM on start: 0,977 Gb; used RAM after test: 9,667 Gb

No model cloning TF 2.4.1: used RAM on start: 1,278 Gb; used RAM after test: 1,365 Gb
With model cloning TF 2.4.1: used RAM on start: 1,134 Gb; used RAM after test: 3,039 Gb

So with TF 2.4.1 the used RAM is 3 times smaller, but it seems like there a memory leak with increasing RAM consumption. With both TF versions the RAM is increasing and gc.collect() does not free any RAM.

**Comment by jvishnuvardhan** [comment]
@OliverPfau Sorry for the late response.

Just a quick question. Why do you want to clone a model when you can use original model? Cloning creates new layers and new weights which will increase memory requirements. Thanks!

**Comment by OliverPfau** [comment]
Every request making a prediction runs inside docker. So the idea was to preload the models, clone the appropriate model for the request, do the request in docker and dispose the copied model.

**Comment by jvishnuvardhan** [comment]
@OliverPfau Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues). Thanks!
