### ISSUE TITLE
How to use a fractionally strided deconvolution layer? Please mention its initialization and also corresponding upsampling of its input

### ISSUE THREAD

**Issue by VenuGopalVasarla** [tensorflow/tensorflow#47672]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by VenuGopalVasarla** [comment]
Hi,
  I was trying to implement and integrate refinedet object detection module into the tensorflow/models repo as a experimental model. The feature extractor contains an transfer connection block which need fractionally strided deconv in it. How to implement that particular deconv using tensorflow?
Thanks in advance

**Comment by Saduf2019** [comment]
@VenuGopalVasarla 

As this is not a bug or a feature request, can you please create an issue on [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) for this and move this to closed status.
