### ISSUE TITLE
SavedModel file does not exist error when running Image classification with TensorFlow Lite Model Maker tutorial

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tensorflow#47686]
**System information**
I am just following instructions found on the tutorial page: https://www.tensorflow.org/lite/tutorials/model_maker_image_classification

OS:  windows 10 home

tensorflow lite model maker installed via pip install tflite-model-maker
print(tf.version.GIT_VERSION, tf.version.VERSION):  v2.4.0-49-g85c8b2a817f 2.4.1

Python 3.8.6

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:48_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28540450_0

**Describe the current behavior**
when executing 

model = image_classifier.create(train_data)

error ending with the following occur:

....

 File "c:\Users\raywl\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: C:\Users\raywl\AppData\Local\Temp\tfhub_modules\87f7b0d2504a48175f521bcaed174acabc93672c/{saved_model.pbtxt|saved_model.pb}

**Describe the expected behavior**

INFO:tensorflow:Retraining the models...
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
hub_keras_layer_v1v2 (HubKer (None, 1280)              3413024   
......

**Standalone code to reproduce the issue**

import os

import numpy as np

import tensorflow as tf
assert tf.__version__.startswith('2')

from tflite_model_maker import configs
from tflite_model_maker import ExportFormat
from tflite_model_maker import image_classifier
from tflite_model_maker import ImageClassifierDataLoader
from tflite_model_maker import model_spec

import matplotlib.pyplot as plt

image_path = tf.keras.utils.get_file(
      'flower_photos.tgz',
      'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
      extract=True)
image_path = os.path.join(os.path.dirname(image_path), 'flower_photos')

data = ImageClassifierDataLoader.from_folder(image_path)
train_data, test_data = data.split(0.9)
model = image_classifier.create(train_data)

*error hit*

attached is the full screen dump of the repeatable step until the error. 

I check the path 

C:\Users\raywl\AppData\Local\Temp\tfhub_modules\87f7b0d2504a48175f521bcaed174acabc93672c

and found it to only contain 2 empty folders assets and variables (see screen capture sc_tfhub.png)

I am also able to complete this colab tutorial on chrome without issue (https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_image_classification.ipynb#scrollTo=6cv3K3oaksJv)

Please advise how I can troubleshoot this issue.

<img width="576" alt="sc_tfhub" src="https://user-images.githubusercontent.com/10432466/110570140-6f72cb80-8190-11eb-9bcd-a2548c5032f2.PNG">

[fullScreenDumpMM.txt](https://github.com/tensorflow/tensorflow/files/6112868/fullScreenDumpMM.txt)

Thanks
Raymond

**Comment by abattery** [comment]
@ziyeqinghan could you take a look at this?

**Comment by lintian06** [comment]
From the error message, it seems that your hub module doesn't download correctly. Can you try downloading it from https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2 and put the unzipped files in that path?

**Comment by FlyWong** [comment]
Hi

May I know which path?

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FlyWong** [comment]
Hi all,

Thanks it worked after copying in the files extracted from the .gz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
