### ISSUE TITLE
SentencePieceTokenizer.detokenize fails on TPU with "No registered 'SentencepieceDetokenizeOp' OpKernel for XLA_TPU_JIT devices"

### ISSUE THREAD

**Issue by chrisbutner** [tensorflow/tensorflow#47683]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, included below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Collab with TPU
- TensorFlow installed from (source or binary): (pre-installed)
- TensorFlow version (use command below): v2.4.1-0-g85c8b2a817f 2.4.1
- Python version: Python 3.7.10

**Describe the current behavior**

Running tensorflow_text.SentencepieceTokenizer.detokenize on a TPU gives "No registered 'SentencepieceDetokenizeOp' OpKernel for XLA_TPU_JIT devices"

**Describe the expected behavior**

Running tensorflow_text.SentencepieceTokenizer.detokenize on a TPU succeeds, just like on a CPU or GPU device

**Standalone code to reproduce the issue**

```
!pip install tensorflow-text
!pip install sentencepiece

!python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
!python --version

import tensorflow as tf
import tensorflow_text as tf_text
import sentencepiece

resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)

tokenizer_prefix = "/tmp/tokenizer"
corpus_path = tokenizer_prefix + ".txt"
model_path = tokenizer_prefix + ".model"

with open(corpus_path, "w") as f: 
  content = f.write("a b c d e")

sentencepiece.SentencePieceTrainer.Train(input=corpus_path, model_prefix=tokenizer_prefix, vocab_size=9, character_coverage=1.0)

with tf.device("/TPU:0"):
  tokenizer = tf_text.SentencepieceTokenizer(model=tf.io.gfile.GFile(model_path, "rb").read(), add_eos=True)
  @tf.function
  def tf_detokenize(input):
    return tokenizer.detokenize(input)
  print(tf_detokenize(tf.constant([1, 2, 3, 4, 5], dtype=tf.int32)))
```

**Other info / logs**

```
InvalidArgumentError: Function invoked by the following node is not compilable: {{node __inference_tf_detokenize_280}} = __inference_tf_detokenize_280[_XlaMustCompile=true, config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000", executor_type=""](dummy_input, dummy_input).
Uncompilable nodes:
SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentencepieceDetokenizeOp: unsupported op: No registered 'SentencepieceDetokenizeOp' OpKernel for XLA_TPU_JIT devices compatible with node {{node SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentencepieceDetokenizeOp}}
	Stacktrace:
		Node: __inference_tf_detokenize_280, function: 
		Node: SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentencepieceDetokenizeOp, function: __inference_tf_detokenize_280

SentenceTokenizer/Reshape: unsupported op: No registered 'Reshape' OpKernel for XLA_TPU_JIT devices compatible with node {{node SentenceTokenizer/Reshape}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, Tshape=DT_INT32
	Stacktrace:
		Node: __inference_tf_detokenize_280, function: 
		Node: SentenceTokenizer/Reshape, function: __inference_tf_detokenize_280

Identity: unsupported op: No registered 'Identity' OpKernel for XLA_TPU_JIT devices compatible with node {{node Identity}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING
	Stacktrace:
		Node: __inference_tf_detokenize_280, function: 
		Node: Identity, function: __inference_tf_detokenize_280

identity_RetVal: unsupported op: No registered '_Retval' OpKernel for XLA_TPU_JIT devices compatible with node {{node identity_RetVal}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, index=0
	Stacktrace:
		Node: __inference_tf_detokenize_280, function: 
		Node: identity_RetVal, function: __inference_tf_detokenize_280
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/165f56b8059db42420dca8b11dd3e836/47683-2-3.ipynb), [TF v2.4](https://colab.research.google.com/gist/amahendrakar/914acf4640879a1f7e6a87644a6f14be/47683.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/1ff4b0ff2ff79ef9321be404591290fb/47683-2-5.ipynb). Please check the linked gist for reference. Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF  2.6.0-dev20210531 ,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/35532c4057083f2bed50b12cd3296c80/untitled157.ipynb)..Thanks !

**Comment by tilakrayal** [comment]
@chrisbutner,
I tried to execute the given code on tf-nightly and was not able to find the mentioned initial error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d78483df084a35f8e03f7066135baef1/untitled725.ipynb) and let us know if anything is missing here. Thank you!

**Comment by chrisbutner** [comment]
Hi @tilakrayal - in the gist you linked I see the following error, so I don't think the gist indicates that the bug can be closed.

```InvalidArgumentError: Trying to access resource _0_SentencepieceOp located in device /job:worker/replica:0/task:0/device:CPU:0 from device /job:worker/replica:0/task:0/device:TPU:0```

Also, the gist installs `tensorflow-text-nightly` then `tensorflow-text` - only one of these should happen. And I'm not sure on the compatibility story of stable `sentencepiece` with nightly TF builds - this may be contributing to the error.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
