### ISSUE TITLE
LLVM MLIR Tensorflow Compatibility

### ISSUE THREAD

**Issue by dwincort** [tensorflow/tensorflow#47680]
You have a great [table of tested build configurations for tensorflow in general](https://www.tensorflow.org/install/source#tested_build_configurations) — do you have something similar for getting TF's MLIR integration to work.  That is, can you suggest commits from llvm-project to use with commits from this repository that will guarantee a successful build of `mlir:tf-opt` as described in [the tensorflow MLIR readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/README.md)?  In that readme, there is a line suggesting that manual BUILD file changes may be required, for example if "you are using a different version of LLVM than set in tensorflow/workspace.bzl's LLVM_COMMIT", but I don't see a reference to `LLVM_COMMIT` in any of the 4 workspace*.bzl files in the tensorflow directory.

Alternatively/Additionally, is there any further guidance toward building `tf-opt` from source than that given in the aforementioned readme?

Any help would be appreciated.

**Comment by joker-eph** [comment]
At the moment, TensorFlow is revision-locked with LLVM, there is no guarantee that you can build TensorFlow with any other revision that the one specified in the workspace.bzl. We upgrade to the top of the main LLVM branch almost every day, sometimes multiple times per day.

The LLVM_COMMIT mentioned in the doc has been refactored an is now in third_party/llvm/workspace.bzl ; the instructions are only useful for testing purpose.

**Comment by dwincort** [comment]
Thanks for the info!
