### ISSUE TITLE
tf.Variable shape is restricted with copy.deepcopy

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#47684]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- CUDA/cuDNN version: ???
- GPU model and memory: GTX 1070

**Describe the current behavior**
`tf.Variable` shape is restricted when using `copy.deepcopy`
```python
>>> x = tf.Variable([[1.2, 3.4]], shape=[None, 2])
>>> x.shape
TensorShape([None, 2])
>>> import copy
>>> copy.deepcopy(x).shape
TensorShape([5, 2])
```

**Describe the expected behavior**
copy has the same shape as original.

**Comment by Saduf2019** [comment]
@joelberkeley 
Please refer to this [gist](https://colab.research.google.com/drive/1zhKXHpmEdrdWaagNMqTsReKFmdvfwcWH?usp=sharing) and let us know.

**Comment by joelberkeley** [comment]
@Saduf2019 I'm not sure that gist is quite correct. The following code shows how it's not possible to assign to a deepcopy of a `tf.Variable`
```python
>>> x = tf.Variable(tf.zeros([5, 2]), shape=[None, 2])
>>> x.assign(tf.zeros([10, 2]))
<tf.Variable 'UnreadVariable' shape=(None, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>
>>> y = tf.Variable(tf.zeros([5, 2]), shape=[None, 2])
>>> import copy
>>> copy.deepcopy(y).assign(tf.zeros([10, 2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 888, in assign
    raise ValueError(
ValueError: Cannot assign to variable Variable:0 due to variable shape (5, 2) and value shape (10, 2) are incompatible
```

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220714. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d581a718b1ea433d9794f049be421911/untitled437.ipynb). Thank you!

**Comment by tilakrayal** [comment]
@joelberkeley,
I tried to execute the mentioned code on the latest version with the alternative approach and the code was executed without any issues.

Here instead of using copy, you can try to use **tf.identity** which returns a Tensor with the same shape and contents as input. 
https://www.tensorflow.org/api_docs/python/tf/identity
Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/34cf034e998a0aa12586e9a588601837/untitled2110.ipynb). 

Thank you!

**Comment by joelberkeley** [comment]
@tilakrayal I've forgotten the details of this and no longer need it. Do with the ticket what you wish

**Comment by tilakrayal** [comment]
@joelberkeley,
Could you please feel free to move this issue to the closed status? Thank you!

**Comment by joelberkeley** [comment]
Closed as no longer interested
