### ISSUE TITLE
multi-threading on tensorflow models

### ISSUE THREAD

**Issue by dihiaselma** [tensorflow/tensorflow#47692]
Hello;

I have a TensorFlow model in .h5. I call it from a Flask App via /predict

my project consist on predicting the sentiment of each entering comment from tweeter in streaming. 
I want to load the model one time (at the beginning) , then many threads or processes use this model (share it)

I get a Lock error.

How can I fix this bug, how to allow many threads to share the same model at the same time without locking.?

Thanks

**Comment by karenlorris** [comment]
Same problem here
