### ISSUE TITLE
Transpose of a Bi-LSTM CRF working fine on TFLite interpreter of Python but throwing error on Android

### ISSUE THREAD

**Issue by PatroxGaurab** [tensorflow/tensorflow#47695]
System.Exception: 'Java.Lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/transpose.cc:56 op_context->perm->dims->data[0] != dims (3 != 2)
Node number 6 (TRANSPOSE) failed to prepare.
Please help me, how we can debug this error.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Layer (type)                 Output Shape              Param #   
=================================================================
sequence_input (InputLayer)  [(None, 75)]              0         
_________________________________________________________________
embedding_37 (Embedding)     (None, 75, 20)            703000    
_________________________________________________________________
bidirectional_37 (Bidirectio (None, 75, 100)           28400     
_________________________________________________________________
time_distributed_37 (TimeDis (None, 75, 50)            5050      
_________________________________________________________________
crf_64 (CRF)                 (None, 75, 21)            1554      
=================================================================
Total params: 738,004
Trainable params: 738,004
Non-trainable params: 0

**Comment by abattery** [comment]
Please make sure your android aar files have the same or higher TF version used for the TFLite conversion.

**Comment by PatroxGaurab** [comment]
Thanks for your prompt response ->
```
# Model definition
sequence_input = Input(shape=(MAX_LEN,), name='sequence_input')
model = Embedding(input_dim=n_words+2, output_dim=EMBEDDING, # n_words + 2 (PAD & UNK)
                  input_length=MAX_LEN)(sequence_input)  # default: 20-dim embedding
model = Bidirectional(LSTM(units=50, return_sequences=True,
                           recurrent_dropout=0.1))(model)  # variational biLSTM

model = TimeDistributed(Dense(50, activation="relu"))(model)  # a dense layer as suggested by neuralNer


crf = CRF(n_tags+1)  # CRF layer, n_tags+1(PAD)


sequence_mask = tf.keras.layers.Lambda(lambda x: tf.greater(x, 0))(sequence_input)

outputs = crf(model)

model = Model(sequence_input, outputs)

model.compile(
    loss=crf.neg_log_likelihood,
    metrics=[crf.accuracy],
    optimizer=tf.keras.optimizers.Adam(5e-5)
    )
```

Prediction on TFLite interface of Python working fine ->

```
interpreter = tf.lite.Interpreter(model_path="model1.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(output_details)
print(input_details)
# Test model on random input data.
input_shape = input_details[0]['shape']
test_sentence = nltk.word_tokenize("A series of explosions shook the Iraqi capital")
# Preprocessing
x_test_sent = pad_sequences(sequences=[[word2idx.get(w, 0) for w in test_sentence]],
                        padding="post", value=word2idx["PAD"], maxlen=MAX_LEN)
    
input_data = np.array([x_test_sent[0]], dtype=np.float32)
# input_data = input_data.astype(np.float) 
print(input_data)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
np.set_printoptions(threshold=sys.maxsize)

print(output_data)
```

But prediction on Android giving error ->
          
```
            // Tokenize sentence
            // sentence = sentence.ToLower();
            SimpleTokenizer tokenizer = SimpleTokenizer.Instance;
            String[] tokens = tokenizer.Tokenize(sentence);

            int i = 0;
            var word2idx = new Dictionary<string, int>();
            ner_words.ForEach(w =>
           {
               if (!word2idx.ContainsKey(w))
                   word2idx.Add(w, i+2);
               else
                   word2idx[w] = i+2;
               i++;
           });
            if (!word2idx.ContainsKey("UNK"))
                word2idx.Add("UNK", 1); // Unknown words
            else
                word2idx["UNK"] = 1;
            if (!word2idx.ContainsKey("PAD"))
                word2idx.Add("PAD", 0); // Padding
            else
                word2idx["PAD"] = 0;

            // Preprocessing
            List<int> x_test_sent = new List<int>();
            for (int j = 0; j < MAX_LEN; j++)
            {
                if (j >= tokens.Length)
                {
                    x_test_sent.Add(word2idx["PAD"]);
                }
                else if (!word2idx.ContainsKey(tokens[j]))
                {
                    x_test_sent.Add(word2idx["UNK"]);
                }
                else
                {
                    x_test_sent.Add(word2idx[tokens[j]]);
                }
            }

            // Start loading tflite model
            var assets = Application.Context.Assets;
            System.Console.WriteLine("Assets", assets);
            Android.Content.Res.AssetFileDescriptor fileDescriptor = assets.OpenFd("model1.tflite");
            FileInputStream inputStream = new FileInputStream(fileDescriptor.FileDescriptor);
            FileChannel fileChannel = inputStream.Channel;
            long startOffset = fileDescriptor.StartOffset;
            long declaredLength = fileDescriptor.DeclaredLength;
            var asd = fileChannel.Map(FileChannel.MapMode.ReadOnly, startOffset, declaredLength);
            var model = new Xamarin.TensorFlow.Lite.Interpreter(asd);


            try
            {
                List<List<float>> record = new List<List<float>>();
                record.Add(new List<float>());
                int x = 0;
                x_test_sent.ForEach(j =>
                {
                    record[0].Add( j );
                    x++;
                });
                var Input_tensor = record.SelectMany(x => x).ToArray();

                x = 0;

                // var Input_tensor = record.SelectMany(x => x).ToArray();
                FloatBuffer ith_output = FloatBuffer.Allocate(1 * MAX_LEN * 21);  // Float tensor
                ith_output.Order();

                model.Run(Input_tensor, ith_output);
```

**Comment by PatroxGaurab** [comment]
BTW I'm using Xamarin TFLite interface

**Comment by abattery** [comment]
Could you make sure that your Xamarin TFLite library has built with the same or higher than TF version used for conversion?

**Comment by PatroxGaurab** [comment]
Can you please help me how to find that? my python side version is 2.4.0, and I'm using the latest TFLite library

**Comment by abattery** [comment]
The latest version of Xamarin TFLite library is 2.1.0 and the TF version for TFLite model conversion is 2.3. The old runtime may not be able to run the models generated newer version. My recommendation is upgrading TF version of your client. Maybe there is a way to link android library in the Xamarin to use the latest TFLite library.

**Comment by PatroxGaurab** [comment]
As the latest TFLite is not available as the Nuget package, how can we upgrade this in xamarin?

**Comment by PatroxGaurab** [comment]
Issue is fixed after a downgrade of TF version where it's built.
Thanks
