### ISSUE TITLE
Numpy v1.20+ compatibility

### ISSUE THREAD

**Issue by ghylander** [tensorflow/tensorflow#47691]
**System information**
- TensorFlow version (you are using): tf-nightly-gpu v2.5.0-dev20201214
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Tensorflow is incompatible with numpy v1.20+ (recently released). This version introduces new functions and changes behaviours.

**Will this change the current api? How?**
There seems to be an issue with the way tensorflow or numpy  handles symbolic tensors

**Who will benefit with this feature?**
Anyone wishing to use the new features or packages where numpy is a dependency. Virtual environments can circumvent this, but sometimes having numpy v1.20 in the same environment as tf can be neecssary or preferable

**Any Other info.**

**Comment by mihaimaruseac** [comment]
Given that numpy is backwards incompatible, TF needs a lot of work to support both pre 1.20 and after 1.20 numpy.

**Comment by bhack** [comment]
Also we are not strictly aligned with numpy versioning everywhere in the repository:

```
tensorflow/lite/tools/pip_package/setup.py:        'numpy >= 1.16.0',
tensorflow/lite/tools/pip_package/setup_with_binary.py:        'numpy ~= 1.19.2',  # Higher versions have a compatibility issue.
tensorflow/lite/micro/examples/magic_wand/train/requirements.txt:numpy==1.16.2
tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb:            "Requirement already satisfied: numpy~=1.19.2 in /usr/local/lib/python3.6/dist-packages (from tensorflow==2.4.0rc0) (1.19.4)\n",
tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/devel-cpu-jupyter.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le-jupyter.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-cpu-ppc64le.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/ppc64le/devel-gpu-ppc64le-jupyter.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/arm64v8/devel-cpu-arm64v8-jupyter.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/arm64v8/devel-cpu-arm64v8.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/dockerfiles/devel-cpu.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/partials/ubuntu/bazel.partial.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/partials/ubuntu/bazelbuild-arm64v8.partial.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/dockerfiles/partials/ubuntu/bazelbuild.partial.Dockerfile:    'numpy<1.19.0' \
tensorflow/tools/pip_package/setup.py:    'numpy ~= 1.19.2',
tensorflow/tools/ci_build/install/install_centos_pip_packages.sh:pip2 install --upgrade numpy==1.14.5
tensorflow/tools/ci_build/install/install_centos_pip_packages.sh:pip3 install --upgrade numpy==1.14.5
tensorflow/tools/ci_build/install/install_python3.6_pip_packages.sh:pip3 install --no-binary=:all: --upgrade numpy==1.14.5
tensorflow/tools/ci_build/install/install_pip_packages.sh:  pip3 install --no-binary=:all: --upgrade numpy==1.14.5
tensorflow/tools/ci_build/install/install_pip_packages.sh:  pip3 install --upgrade numpy==1.14.5
tensorflow/tools/ci_build/install/install_pip_packages_by_version.sh:  "numpy ~= 1.19.2"
tensorflow/tools/ci_build/release/common.sh:  "${PIP_CMD}" install --user 'numpy ~= 1.19.2'
tensorflow/tools/ci_build/release/common.sh:  ${PIP_CMD} install --user 'numpy ~= 1.19.2'
tensorflow/tools/ci_build/release/common.sh:  ${PIP_CMD} install 'numpy ~= 1.19.2'
tensorflow/tools/ci_build/release/common.sh:  ${PIP_CMD} install 'numpy ~= 1.19.2' --user
tensorflow/tools/ci_build/release/common_win.bat:%PY_EXE% -m pip install "numpy ~= 1.19.2"
```

**Comment by bnavigator** [comment]
This answer on StackOverflow has a solution for the often reported "Cannot convert a symbolic Tensor (gru/strided_slice:0) to a numpy array." Exception thrown by array_ops.py: https://stackoverflow.com/a/66486051

Perhaps you wnat take it into account when updating the compatibility with numpy 1.20

**Comment by NeilGirdhar** [comment]
@mihaimaruseac Which "backwards incompatibilities" ([changelog](https://numpy.org/doc/1.20/release/1.20.0-notes.html)) are preventing TensorFlow from supporting numpy 1.20?

**Comment by tomashek** [comment]
Is there any estimation when Tensorflow will work with numpy 1.20.x?

**Comment by Titaniumtown** [comment]
Yea, I really need it to be updated, I've been unable to use tensorflow for over a month now 😕

**Comment by bhack** [comment]
Here the PR to explore CI fails https://github.com/tensorflow/tensorflow/pull/48918

**Comment by bnavigator** [comment]
CI fails because the installer cannot install Numpy 1.20 for a Python 3.6 ecosystem don't help you at all.

**Comment by bnavigator** [comment]
> Given that numpy is backwards incompatible, TF needs a lot of work to support both pre 1.20 and after 1.20 numpy.

I don't think that is true. There should be nothing in NumPy 1.20 which has not been deprecated before a long time ago.
https://numpy.org/doc/stable/release/1.20.0-notes.html#expired-deprecations.
Any fixes of failures because old TF code does not work with NumPy 1.20 anymore will also happily work with NumPy 1.19.

**Comment by bhack** [comment]
@bnavigator Before you downvoting if you are talking about:
```
 AMD ROCm -- Community CI Build — rocm CI build failed
Intel® oneDNN -- Community CI Build — oneDNN Threadpool native format unit tests failed
```
These are external builds, on external "community" build servers/VM so they are not under TF control.
Then we have our [TF Macos fails](https://source.cloud.google.com/results/invocations/7ba94070-327a-4429-b736-0903f9c4f06f/targets/%2F%2Ftensorflow%2Flite%2Fpython:lite_v2_test/tests). That CI VM probably is still under python 3.7.3.

Then, as you can see, we still release the next TF version (2.5.0) for python 3.6: https://pypi.org/project/tensorflow/2.5.0rc3/#files

**Comment by bnavigator** [comment]
So why are you *requiring* 1.20 for all of your containers? That's not how you check compatibility with 1.20. As I said, you don't have to drop support for older NumPy versions and thus python 3.6. The failures with NumPy 1.20 are already partially reported. Just fix those.

**Comment by bhack** [comment]
> So why are you requiring 1.20 for all of your containers?
This is not the problem as it is already mentioned in the PRs the there is another one to upgrade some base images as requested in another ticket (Docker images, wheels and CI VM are not strictly aligned). 

As you have commented also on the PR I will reply on the PR.

**Comment by shoyer** [comment]
I see there is a work-around identified, but is there also an underlying NumPy bug in the 1.20 release? If so, it would be good to identify that and report it upstream.

**Comment by bnavigator** [comment]
I thinkt that it is an incompatibility how Tensorflow calls NumPy functions like np.prod(). NumPy cannot automatically know what to do with a Tensorflow symbolic Tensor passed to it. NumPy's API says it must be array_like.

**Comment by NeilGirdhar** [comment]
@bnavigator Would you happen to know why it works in numpy 1.19?

**Comment by shoyer** [comment]
NumPy tries very hard to preserve backwards compatibility. So it's a little surprising that there is a change in behavior here from NumPy 1.19 to 1.20.

My guess is that TensorFlow is doing something relatively "unusual" here that isn't well tested inside NumPy. But it would be great to know exactly what that it.

**Comment by bnavigator** [comment]
Yeah, but even the error is thrown by TF not by np:

https://github.com/tensorflow/tensorflow/blob/368c14ecb296e87c67e8d77aba175e02d5b93741/tensorflow/python/framework/ops.py#L857-L870

Tensorflow itself says, that there is no support for passing a Tensor to `np.prod()`.

I can't find the release note for it, but I think 1.20 internally moved some function implementations to ufuncs. See the tracebacks in #47242, #47263.

Note that np 1.21 expects nothing else than `AttributeError`. https://github.com/numpy/numpy/pull/19001

**Comment by joshua-cogliati-inl** [comment]
FYI: On https://github.com/tensorflow/models/issues/9706  @Amir22010 provides this fix for numpy 1.20's NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array error:
```patch
--- tensorflow/python/ops/array_ops.py.orig	2021-07-06 16:14:00.000000000 -0600
+++ tensorflow/python/ops/array_ops.py	2021-07-06 16:15:07.000000000 -0600
@@ -39,6 +39,7 @@
 # pylint: disable=wildcard-import
 from tensorflow.python.ops.gen_array_ops import *
 from tensorflow.python.ops.gen_array_ops import reverse_v2 as reverse  # pylint: disable=unused-import
+from tensorflow.python.ops.math_ops import reduce_prod
 from tensorflow.python.types import core
 from tensorflow.python.util import deprecation
 from tensorflow.python.util import dispatch
@@ -2801,7 +2802,7 @@
 
 def _constant_if_small(value, shape, dtype, name):
   try:
-    if np.prod(shape) < 1000:
+    if reduce_prod(shape) < 1000:
       return constant(value, shape=shape, dtype=dtype, name=name)
   except TypeError:
     # Happens when shape is a Tensor, list with Tensor elements, etc.
```

**Comment by bnavigator** [comment]
@joshua-cogliati-inl, it's the same fix as in #48935 (0f8fde42d09b199d02cf5d9d79fe76ebf1d260ef)

**Comment by jbroot** [comment]
> Given that numpy is backwards incompatible, TF needs a lot of work to support both pre 1.20 and after 1.20 numpy.

I'd argue that current compatibility is more important than assuring backwards compatibility. However, backwards compatibility could be placed on the TF backlog.

**Comment by bnavigator** [comment]
As I said 2 months ago, I haven't seen anything that breaks compatibility with a reasonable recent numpy. They do not change the API between years long deprecations in between.

**Comment by mihaimaruseac** [comment]
> > Given that numpy is backwards incompatible, TF needs a lot of work to support both pre 1.20 and after 1.20 numpy.
> 
> I'd argue that current compatibility is more important than assuring backwards compatibility. However, backwards compatibility could be placed on the TF backlog.

TF is Google first. If Google code uses a certain version of a TF dependency we have to use/support that in OSS too

**Comment by joshua-cogliati-inl** [comment]
> Given that numpy is backwards incompatible, TF needs a lot of work to support both pre 1.20 and after 1.20 numpy.

Um, I am not sure what you are talking about.  The pull request https://github.com/tensorflow/tensorflow/pull/48935 makes 3 changes:
 1.  Switches from calling numpy.prod to tensorflow..python.ops.math_ops.reduce_prod 
 2. Changes some shape constants from floats to integers (things like 1.0 -> 1)
 3. Updates which numpy versions are supported

None of those should cause any backwards compatibility problems.

**Comment by steveSchneider2** [comment]
Is there a 'best guess' on far out the fix is? a month? 6 months?

**Comment by bnavigator** [comment]
They cannot approve the fix because they have no CI to properly check it. There might be more problems with NumPy 1.20 and 1.21 compatibility.

**Comment by joshua-cogliati-inl** [comment]
An alternate fix (which also works for me) for numpy 1.20's NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array error was in https://github.com/tensorflow/tensorflow/pull/49008 which was merged and then reverted:
```patch

diff --git a/tensorflow/python/ops/array_ops.py b/tensorflow/python/ops/array_ops.py
index f7fc323971461..a8d7bb04cc759 100644
--- a/tensorflow/python/ops/array_ops.py
+++ b/tensorflow/python/ops/array_ops.py
@@ -2893,6 +2893,7 @@ def matrix_set_diag(
 
 def _constant_if_small(value, shape, dtype, name):
   try:
+    shape = nest.map_structure(tensor_util.constant_value, shape)
     if np.prod(shape) < 1000:
       return constant(value, shape=shape, dtype=dtype, name=name)
   except TypeError:
@@ -3204,6 +3205,7 @@ def ones(shape, dtype=dtypes.float32, name=None):
       one = np.ones([]).astype(dtype.as_numpy_dtype)
     else:
       one = 1
+
     if not isinstance(shape, ops.Tensor):
       try:
         if not context.executing_eagerly():
 ```

**Comment by joshua-cogliati-inl** [comment]
Also, here is a short piece of code that fails with numpy 1.21.0 and tensorflow 2.4.1:
```python
import tensorflow as tf
from tensorflow import keras

model = keras.models.Sequential([
    keras.layers.LSTM(20, return_sequences=True, input_shape=[None, 2]),
    keras.layers.TimeDistributed(keras.layers.Dense(20))
])
```

**Comment by ghylander** [comment]
What's the status on this? i see that #48935 has been approved

**Comment by bnavigator** [comment]
> What's the status on this? i see that #48935 has been approved

If I understand correctly, the "approval" is just a trigger to run the tests.

**Comment by mihaimaruseac** [comment]
We now have wide ranges of dependencies

**Comment by ghylander** [comment]
i'm unsure about what that means

**Comment by bnavigator** [comment]
months :(

**Comment by mohantym** [comment]
I think latest version 2.6 and nightly support Numpy 1.21.2 now. Attaching [issue](https://github.com/tensorflow/tensorflow/issues/52380#issuecomment-943971924) for reference.

**Comment by mihaimaruseac** [comment]
I think this is now resolved

**Comment by michelkok** [comment]
For me, I could not upgrade to numpy>1.20 with TF 2.6.2 (i.e. the latest). However, after upgrading to TF 2.7.0 it does.
