### ISSUE TITLE
An error occurred while installing

### ISSUE THREAD

**Issue by linweijun** [tensorflow/tensorflow#477]
OS：ubuntu 15
python：2.7.9

error Log：
/usr/bin/pip run on Fri Dec 11 12:02:09 2015
tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by vrv** [comment]
What do you get from: `uname -a` ?

**Comment by cnsgcu** [comment]
Is python 3.5 supported? Having the same problem in python 3.5.1

> $ pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl
tensorflow-0.6.0-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.

> $ python --version
Python 3.5.1

> $ uname -a
... 3.19.0-43-generic ... x86_64 GNU/Linux

**Comment by martinwicke** [comment]
The Python version is encoded in the wheel filename. You can try to rename
the wheel (cp35), but you may have to install from source.

**Comment by nunoachenriques** [comment]
Thanks Martin, installed using the rename trick to ...cp35... after wget ... on a Debian stretch with Python 3.5.

**Comment by mxrguspxrt** [comment]
On ubuntu 14.04 getting the same error.

```
/usr/bin/pip3 run on Tue Feb  2 10:02:00 2016
tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
pip.exceptions.UnsupportedWheel: tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by martinwicke** [comment]
You seem to be using the 0.5.0 wheel, which has no support for Python 3.
Try the 0.6.0 Python 3 version.

**Comment by wspeirs** [comment]
The key/solution is the version number in the URL. I was trying to install with pip3 using python 3.4, so I had to change the URL to: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl

This took waaay too long to figure out :-\

**Comment by vrv** [comment]
De-duping with #468, which is the more general issue.
