### ISSUE TITLE
Could not load libcusolver.so.10 with tf-nightly-gpu

### ISSUE THREAD

**Issue by TPrivat** [tensorflow/tensorflow#47705]
**System information**
- OS Platform and Distribution: Arch Linux
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0 (tf-nightly-gpu)
- Python version: 3.9
- CUDA/cuDNN version: 11.2
- GPU model and memory: 1070 TI 8GB

Problem:
Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/usr/local/lib

I have tried to edit the LD_LIBRARY_PATH like other issues have suggested but that does not work. I do not know which version of CUDA tf-nightly requires. 

CUDA Info:
[taylor@taylor-desktop ~]$ pacman -Qi cuda
Name            : cuda
Version         : 11.2.1-4
Description     : NVIDIA's GPU programming toolkit
Architecture    : x86_64
URL             : https://developer.nvidia.com/cuda-zone
Licenses        : custom:NVIDIA
Groups          : None
Provides        : cuda-toolkit  cuda-sdk  libcudart.so=11.0-64  libcublas.so=11-64  libcublas.so=11-64
                      libcusolver.so=11-64  libcusolver.so=11-64  libcusparse.so=11-64  libcusparse.so=11-64
Depends On      : gcc  gcc-libs  opencl-nvidia  nvidia-utils  python
Optional Deps   : gdb: for cuda-gdb [installed]
                          glu: required for some profiling tools in CUPTI [installed]
Required By     : cudnn
Optional For    : None
Conflicts With  : None
Replaces        : cuda-toolkit  cuda-sdk  cuda-static
Installed Size  : 3.32 GiB
Packager        : Konstantin Gizdov <arch@kge.pw>
Build Date      : Mon Mar 1 05:21:57 2021
Install Date    : Tue Mar 9 16:35:57 2021
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

libcusolver.so=11-64 is installed but tensorflow seems to be looking for libcusolver.so=10. Is that due to tf-nighlty requiring Cuda 11.0? Then it would be the same cuda version as required by tensorflow 2.4. Let me know if you need any more info or I need to format things differently. Thanks.

**Comment by amahendrakar** [comment]
@TPrivat,
Every TensorFlow release is compatible with a certain CUDA and cuDNN version. For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0 | 7.6 | 10.1


In this case, could you please try installing TensorFlow on **Python 3.8** with **CUDA 11.0** and **cuDNN 8** and check if you are facing the same issue. 

Thanks!

**Comment by TPrivat** [comment]
I can only use what is the arch repository. That is python 3.9, cuda 11.2 and cudnn 8.1 which is why I am using tf-nightly. What cuda cudnn version are compatible with tf-nightly/tf-nightly-gpu (2.5.0.dev20210309). 
Thanks.

**Comment by amahendrakar** [comment]
@TPrivat,
TF-nightly packages are compatible with **Python 3.9**, **CUDA 11.2** and **cuDNN 8.1**. I was able to install TensorFlow without any issues with the above configuration. Please check the attached screenshot for reference. 

![Screenshot 2021-03-18 7 59 49 PM](https://user-images.githubusercontent.com/57165142/111643330-e5c49d00-8824-11eb-8768-05c43f368f13.png)

Thanks!

**Comment by TPrivat** [comment]
Yes it seems with the newer version of tf-nightly-gpu (2.5.0.dev20210318) the correct version of libcusolver is loaded. However I now have the errors "failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error" and "None of the MLIR Optimization Passes are enabled (registered 2)". I do not get the line "Adding visible gpu devices:" and instead get "CPU Frequency: 3600000000 Hz", which I assume means it is still using my CPU rather than my GPU.

Below is the full read-out:
`2021-03-18 17:55:57.237003: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-03-18 17:55:57.872950: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-18 17:55:57.907640: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2021-03-18 17:55:57.907666: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: taylor-desktop
2021-03-18 17:55:57.907673: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: taylor-desktop
2021-03-18 17:55:57.907723: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.56.0
2021-03-18 17:55:57.907744: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.56.0
2021-03-18 17:55:57.907748: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.56.0
Dataset created, creating and adapting vector layer now...
2021-03-18 17:55:57.948387: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-03-18 17:55:57.948691: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3600000000 Hz`

I appreciate you taking time to help!

**Comment by TPrivat** [comment]
![tensorflow_errors](https://user-images.githubusercontent.com/33856930/111708613-2bc53500-8814-11eb-9272-2a211d952ed4.png)
