### ISSUE TITLE
Unable to load tflite file in android, It provides =" Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/transpose.cc:55 op_context->perm->dims->data[0] != dims (3 != 2) 03-10 16:42:09.948  8010  8010 D check here: Node number 6 (TRANSPOSE) failed to prepare."

### ISSUE THREAD

**Issue by Adeesh2411** [tensorflow/tensorflow#47700]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes** 
 colab link to tensorflow model = [https://colab.research.google.com/drive/1BI0661FaM6L4oqjNX1MYfHpJCKwKQhjt?usp=sharing](url)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Samsung Galaxy M30 s**
- TensorFlow installed from (source or binary):  **pip3 install tensorflow**
- TensorFlow version (use command below): **2.4.1**
- Python version: **3.7**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Unable to load tflite model file , It provides Internal error. PLease find Log data that raised for this issue : 
**03-10 16:42:09.948  8010  8010 D check here: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/transpose.cc:55 op_context->perm->dims->data[0] != dims (3 != 2)
03-10 16:42:09.948  8010  8010 D check here: Node number 6 (TRANSPOSE) failed to prepare.
03-10 16:42:09.948  8010  8010 D check here: 
03-10 16:42:09.948  8010  8010 D check here: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
03-10 16:42:09.948  8010  8010 D check here: 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:163)
03-10 16:42:09.948  8010  8010 D check here: 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
03-10 16:42:09.948  8010  8010 D check here: 	at org.tensorflow.lite.Interpreter.run(Interpreter.java:319)
03-10 16:42:09.948  8010  8010 D check here: 	at com.example.testforlite.MainActivity$1.onClick(MainActivity.java:89)
03-10 16:42:09.948  8010  8010 D check here: 	at android.view.View.performClick(View.java:5794)
03-10 16:42:09.948  8010  8010 D check here: 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
03-10 16:42:09.948  8010  8010 D check here: 	at android.view.View$PerformClick.run(View.java:22729)
03-10 16:42:09.948  8010  8010 D check here: 	at android.os.Handler.handleCallback(Handler.java:751)
03-10 16:42:09.948  8010  8010 D check here: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-10 16:42:09.948  8010  8010 D check here: 	at android.os.Looper.loop(Looper.java:154)
03-10 16:42:09.948  8010  8010 D check here: 	at android.app.ActivityThread.main(ActivityThread.java:6138)
03-10 16:42:09.948  8010  8010 D check here: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 16:42:09.948  8010  8010 D check here: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
03-10 16:42:09.948  8010  8010 D check here: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)**

I have passed input with correct dimension, still There is some error when I run tflite using Interpreter

**Describe the expected behavior**

Expected behaviour should load tflite model and provide output values for the provided input
 
**Standalone code to reproduce the issue**
colab tensorflow model : [https://colab.research.google.com/drive/1BI0661FaM6L4oqjNX1MYfHpJCKwKQhjt?usp=sharing](url) 
android Code link : [https://github.com/Adeesh2411/TensorflowAndroidAPP](url)
tflite file can be found in asset folder

**Comment by abattery** [comment]
@Adeesh2411 could you make sure that your android client has a TFLite dependency, which has the same or higher version of the TF version used for TFLite model conversion?

**Comment by abattery** [comment]
The old runtime may not be able to run the models generated with a newer version. My recommendation is upgrading TF version of your android client if the client has a lower version than 2.4.

**Comment by Adeesh2411** [comment]
@abattery I converted my tensorflow vesion = 2.4.0 and tflite = 2.4.0. 
Still it provides same issue

**Comment by abattery** [comment]
@Adeesh2411 could you confirm which TF version you are using for android?

**Comment by Adeesh2411** [comment]
My dependency : 
dependencies {

    implementation 'org.tensorflow:tensorflow-lite:2.4.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

In MainActivity file I'm importing : import org.tensorflow.lite.Interpreter;
then I initialize ` ByteBuffer My_byte = loadModelFile(MainActivity.this, Model);
            tflite = new Interpreter(My_byte);` 

I didn't get what you meant by saying TF version in android . Is there anything I need to add in dependency?

**Comment by Adeesh2411** [comment]
@abattery  Thank you for looking into my issue. 
I got working with model now. 
Isuue was with tflite dependency :
I converted my tensorflow verion in python : 
```
tensorboard==2.2.2
tensorflow==2.2.0
tensorflow-estimator==2.2.0
```
and in android my dependency version to :
`implementation 'org.tensorflow:tensorflow-lite:2.2.0'`
