### ISSUE TITLE
"Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED" only when running old TF code

### ISSUE THREAD

**Issue by kuonb** [tensorflow/tensorflow#47701]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==2.1.0
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.5.2
- CUDA/cuDNN version: Driver Version: 418.39       CUDA Version: 10.1
- GPU model and memory: GeForce GTX 1080Ti (11GB)

I've downloaded tensorflow-gpu 2.1.0 because it's compatible with the drivers currently installed. Indeed, TFv2 code works, but  I run into this problem when trying to run old TFv1 code. It seems that this error happens after the first convolution, so I guess there is a problem using convolutions, but it's funny that I have no such problem using TFv2 code. I've searched about it, and I've read that downgrading TF and even the drivers could solve it, but if TFv2 can use convolutions, why old TFv1 code could not? This might be a bug. Any workaround?

TFv2 code that works: https://pastebin.com/D4YMMUPT
Old TFv1 code that does not work: https://pastebin.com/AXAaYbKs

Error log:

> 2021-03-10 17:45:34.210128: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
> 2021-03-10 17:45:34.210184: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
> 2021-03-10 17:45:34.210191: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> WARNING: Logging before flag parsing goes to stderr.
> W0310 17:45:34.787791 139979412670208 deprecation.py:323] From /home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/compat/v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> W0310 17:45:34.792874 139979412670208 deprecation.py:506] From /home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> 2021-03-10 17:45:34.911558: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2021-03-10 17:45:34.930318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:17:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
> coreClock: 1.62GHz coreCount: 28 deviceMemorySize: 10.90GiB deviceMemoryBandwidth: 451.17GiB/s
> 2021-03-10 17:45:34.930522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2021-03-10 17:45:34.931581: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2021-03-10 17:45:34.932423: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2021-03-10 17:45:34.932628: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2021-03-10 17:45:34.933731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2021-03-10 17:45:34.934569: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2021-03-10 17:45:34.937042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2021-03-10 17:45:34.938760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2021-03-10 17:45:34.939051: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
> 2021-03-10 17:45:34.961585: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3999980000 Hz
> 2021-03-10 17:45:34.962354: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x59b5640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2021-03-10 17:45:34.962397: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2021-03-10 17:45:35.060702: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a3bb90 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2021-03-10 17:45:35.060757: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
> 2021-03-10 17:45:35.062292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
> pciBusID: 0000:17:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
> coreClock: 1.62GHz coreCount: 28 deviceMemorySize: 10.90GiB deviceMemoryBandwidth: 451.17GiB/s
> 2021-03-10 17:45:35.062384: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2021-03-10 17:45:35.062432: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2021-03-10 17:45:35.062480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2021-03-10 17:45:35.062526: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2021-03-10 17:45:35.062573: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2021-03-10 17:45:35.062617: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2021-03-10 17:45:35.062665: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2021-03-10 17:45:35.065186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
> 2021-03-10 17:45:35.065292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2021-03-10 17:45:35.067678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2021-03-10 17:45:35.067707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
> 2021-03-10 17:45:35.067721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
> 2021-03-10 17:45:35.070991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10308 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
> W0310 17:45:35.072554 139979412670208 deprecation.py:323] From /home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/util/tf_should_use.py:235: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
> Instructions for updating:
> Use `tf.global_variables_initializer` instead.
> 2021-03-10 17:45:35.750980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2021-03-10 17:45:35.904388: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2021-03-10 17:45:35.905558: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
> 2021-03-10 17:45:35.905655: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 418.39.0
> 2021-03-10 17:45:35.905682: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
> 2021-03-10 17:45:35.905727: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 418.39.0
> Traceback (most recent call last):
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
>     return fn(*args)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
>     target_list, run_metadata)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
>   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[{{node Conv2D}}]]
> 	 [[Mean_1/_7]]
>   (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[{{node Conv2D}}]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "old_tf_script.py", line 62, in <module>
>     x:xx, y_: yy, keep_prob: 1.0})
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 790, in eval
>     return _eval_using_default_session(self, feed_dict, self.graph, session)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 5312, in _eval_using_default_session
>     return session.run(tensors, feed_dict)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 960, in run
>     run_metadata_ptr)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
>     run_metadata)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
>   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[node Conv2D (defined at old_tf_script.py:18) ]]
> 	 [[Mean_1/_7]]
>   (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 	 [[node Conv2D (defined at old_tf_script.py:18) ]]
> 0 successful operations.
> 0 derived errors ignored.
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node Conv2D:
>  Reshape (defined at old_tf_script.py:30)
> 
> Input Source operations connected to node Conv2D:
>  Reshape (defined at old_tf_script.py:30)
> 
> Original stack trace for 'Conv2D':
>   File "old_tf_script.py", line 31, in <module>
>     h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
>   File "old_tf_script.py", line 18, in conv2d
>     return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1914, in conv2d_v2
>     name=name)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2011, in conv2d
>     name=name)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 969, in conv2d
>     data_format=data_format, dilations=dilations, name=name)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
>     attrs=attr_protos, op_def=op_def)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
>     op_def=op_def)
>   File "/home/user/virtualenv1/lib/python3.5/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
>     self._traceback = tf_stack.extract_stack()
>

**Comment by Saduf2019** [comment]
@kuonb 
please refer to these issues and let us know: [link](https://stackoverflow.com/questions/60368298/could-not-load-dynamic-library-libnvinfer-so-6), #36201, #35968, [link1](https://www.gitmemory.com/issue/tensorflow/tensorflow/36201/578413833)
