### ISSUE TITLE
Training stalls after saving checkpoint 0

### ISSUE THREAD

**Issue by albertonavas99** [tensorflow/tensorflow#47706]
Hello,

First of all, I have read and tried all solutions from #32017, unless it isn't the same error exactly.

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow version: 2.4.1
- Python version: 3.8.2
- CUDA/cuDNN version: 11.2

I have tried to train a model with this command:
melody_rnn_train --config=attention_rnn --run_dir=tmp\\run1 --sequence_example_file=tmp\\sequence_examples\\training_melodies.tfrecord --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --num_training_steps=1

The behaviour should be the same than in a normal t2t-trainer output.

There are a lot of warnings about deprecated stuff but, I am pretty sure they are not impoortant so the last output lines are:

```
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
I0310 18:09:11.618963  5924 basic_session_run_hooks.py:613] Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into tmp\\run1\train\model.ckpt.
I0310 18:09:11.622482  5924 basic_session_run_hooks.py:618] Saving checkpoints for 0 into tmp\\run1\train\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
I0310 18:09:16.462026  5924 basic_session_run_hooks.py:625] Calling checkpoint listeners after saving checkpoint 0...
```

And nothing more happens after that, it stalls and IDK why.
Thanks in advance.

**Comment by Saduf2019** [comment]
@albertonavas99 
Please share simple stand alone code to reproduce the issue or a colab gist with the error.

**Comment by albertonavas99** [comment]
@Saduf2019 
I have only executed the command below which belongs to a library called "Magenta" developed by Google. It has a repository: https://github.com/magenta/magenta/tree/master/magenta/models/melody_rnn. Also, it can be downloaded with:

`pip install magenta`

The only file needed to execute this command is compressed and 
[training_melodies.zip](https://github.com/tensorflow/tensorflow/files/6131575/training_melodies.zip)
attached (--sequence_example_file).

Thanks.

**Comment by jvishnuvardhan** [comment]
@albertonavas99 This issue is more related to `magenta` repo and I see you already opened an issue there. This `tensorflow` repo is more related to bugs and performance related issues in Tensorflow Core.   

duplicate https://github.com/magenta/magenta/issues/1899

I am closing this issue as it is more related to `magenta` repo. Please feel free to reopen If I am mistaken. thanks!
