### ISSUE TITLE
Feeding a batch of different image shapes for a model with dynamic input shape

### ISSUE THREAD

**Issue by m-parchami** [tensorflow/tensorflow#47717]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Linux Ubuntu 18
- TensorFlow installed from binary
- TensorFlow version: 1.15
- Python version: 3.7
- Running on CPU.

**Describe the current behavior**
I am working on a model with a flexible input shape (None, None,3). That is, the images can be of any size but the number of channels should be 3. The model is compatible with handling dynamic shapes. As you can see in the following:
```Python

arr1 = np.random.random((100, 100, 3))
arr2 = np.random.random((104, 100, 3))
arr3 = np.random.random((200, 240, 3))

out = model.predict(np.expand_dims(arr1, 0))
print(out.shape)

out = model.predict(np.expand_dims(arr2, 0))
print(out.shape)

out = model.predict(np.expand_dims(arr3, 0))
print(out.shape)
```
And the output of this section is:
```Python
(1, 100, 100, 3)
(1, 104, 100, 3)
(1, 200, 240, 3)
```
However, this is a single image inference. When we have batches (e.g. when training with batch_size > 1), the batch will have a shape of (1, ) since NumPy cannot handle an array of arrays with different shapes. And as a result, I cannot feed the model batches of images. Shouldn't there be a way to feed a batch of images with different shapes to model?

This is my result on feeding a batch:
```Python

batch = [arr1, arr1, arr1]
out = model.predict(batch)
print(out.shape)

batch = [arr2, arr2, arr2]
out = model.predict(batch)
print(out.shape)


batch = [arr1, arr2] #this one generates the error
out = model.predict(batch)
print(out.shape)
```
And the result is:
```Python
(3, 100, 100, 3)
(3, 104, 100, 3)
Traceback (most recent call last):
  File "flexnet.py", line 57, in <module>
    out = model.predict(batch)
  File "/home/amin/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/amin/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 716, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "/home/amin/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2471, in _standardize_user_data
    exception_prefix='input')
  File "/home/amin/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 563, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (2, 1)
```

**Comment by ASCcool** [comment]
Every array (image) in a batch should be of the same size by definition. You can evaluate the arrays individually if you wish to.

**Comment by m-parchami** [comment]
You are absolutely right! But as I have shown in my issue, there can be a model which is flexible to dynamic shapes. Therefore, I wonder whether there is a way to feed batches to these models as well.

**Comment by Saduf2019** [comment]
@m-parchami 
We see that you are using tf version 1.15, there is no support for 1.x, please update to 2.x and let us know.
