### ISSUE TITLE
std symbols undefined while compiling libtensorflowlite.so for android

### ISSUE THREAD

**Issue by Krisonrik** [tensorflow/tensorflow#47711]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  macOS Big Sur version 11.2.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
  source
- TensorFlow version:
  2.4.0
- Python version:
 3.9
- Installed using virtualenv? pip? conda?:
  trying to build from source
- Bazel version (if compiling from source):
 3.1.0
- GCC/Compiler version (if compiling from source):
 clang-1200.0.32.29
- CUDA/cuDNN version:
- GPU model and memory:
  AMD Radeon Pro 5300M 4 GB

**Describe the problem**
When trying to compile libtensorflowlite.so for android with added "//tensorflow/lite/delegates/flex:delegate" dependency (as is stated in the https://www.tensorflow.org/lite/guide/ops_select), compilation would fail due to std::make_unique being undefined.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build \
-s //tensorflow/lite:libtensorflowlite.so \
--config=android_arm64 \
--cxxopt='--std=c++11' \
-c opt \
--config=v2 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

SUBCOMMAND: # //tensorflow/core/kernels:portable_tensorflow_kernels [action 'Compiling tensorflow/core/kernels/control_flow_ops.cc', configuration: 17edd87150895742afa8f50ebcaef1b3cd2bf6b4d6974c05ffc14bdd6966f454, execution platform: @local_execution_config_platform//:platform]
(cd /private/var/tmp/_bazel_richardyao/1258fb4559d515393cc4dfc8787a5562/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=30.0.3 \
    ANDROID_NDK_API_LEVEL=21 \
    ANDROID_NDK_HOME=/usr/local/Caskroom/android-ndk/21/android-ndk-r21 \
    ANDROID_SDK_API_LEVEL=30 \
    ANDROID_SDK_HOME=/Users/richardyao/library/Android/Sdk \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/local/opt/python@3.9/bin/python3.9 \
    PYTHON_LIB_PATH=/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android '-D__ANDROID_API__=21' -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig '-Werror=return-type' '-Werror=int-to-pointer-cast' '-Werror=pointer-to-int-cast' '-Werror=implicit-function-declaration' -O2 -g -DNDEBUG -MD -MF bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/control_flow_ops.pic.d '-frandom-seed=bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/control_flow_ops.pic.o' -fPIC '-DS_IREAD=S_IRUSR' '-DS_IWRITE=S_IWUSR' '-DS_IEXEC=S_IXUSR' -DSUPPORT_SELECTIVE_REGISTRATION -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/arm64-v8a-opt/bin -iquote external/gif -iquote bazel-out/arm64-v8a-opt/bin/external/gif -iquote external/eigen_archive -iquote bazel-out/arm64-v8a-opt/bin/external/eigen_archive -iquote external/com_google_absl -iquote bazel-out/arm64-v8a-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/arm64-v8a-opt/bin/external/nsync -iquote external/libjpeg_turbo -iquote bazel-out/arm64-v8a-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf -iquote external/double_conversion -iquote bazel-out/arm64-v8a-opt/bin/external/double_conversion -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm64-v8a-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm64-v8a-opt/bin/external/farmhash_archive -iquote external/png -iquote bazel-out/arm64-v8a-opt/bin/external/png -iquote external/zlib -iquote bazel-out/arm64-v8a-opt/bin/external/zlib -iquote external/highwayhash -iquote bazel-out/arm64-v8a-opt/bin/external/highwayhash -iquote external/icu -iquote bazel-out/arm64-v8a-opt/bin/external/icu -iquote external/fft2d -iquote bazel-out/arm64-v8a-opt/bin/external/fft2d -iquote external/gemmlowp -iquote bazel-out/arm64-v8a-opt/bin/external/gemmlowp -isystem external/gif -isystem bazel-out/arm64-v8a-opt/bin/external/gif -isystem external/eigen_archive -isystem bazel-out/arm64-v8a-opt/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/arm64-v8a-opt/bin/external/nsync/public -isystem external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf/src -isystem external/double_conversion -isystem bazel-out/arm64-v8a-opt/bin/external/double_conversion -isystem external/farmhash_archive/src -isystem bazel-out/arm64-v8a-opt/bin/external/farmhash_archive/src -isystem external/png -isystem bazel-out/arm64-v8a-opt/bin/external/png -isystem external/zlib -isystem bazel-out/arm64-v8a-opt/bin/external/zlib -isystem external/icu/icu4c/source/common -isystem bazel-out/arm64-v8a-opt/bin/external/icu/icu4c/source/common -w '-std=c++14' '--std=c++11' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DTENSORFLOW_USE_XLA=1' -DTF_LEAN_BINARY -Wno-narrowing -fomit-frame-pointer -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/core/kernels/control_flow_ops.cc -o bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/control_flow_ops.pic.o)
ERROR: /Users/richardyao/Code/tensorflow/tensorflow/core/kernels/BUILD:6467:11: C++ compilation of rule '//tensorflow/core/kernels:portable_tensorflow_kernels' failed (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target ... (remaining 154 argument(s) skipped)
tensorflow/core/kernels/data/dataset_utils.cc:883:17: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
      counter = std::make_unique<BlockingCounter>(num_batch_elements);
                ^~~~~~~~~~~~~~~~
                absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(
                                                      ^
tensorflow/core/kernels/data/dataset_utils.cc:883:17: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
      counter = std::make_unique<BlockingCounter>(num_batch_elements);
                ^~~~~~~~~~~~~~~~
                absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(
                                                      ^
tensorflow/core/kernels/data/dataset_utils.cc:884:19: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
      status_mu = std::make_unique<mutex>();
                  ^~~~~~~~~~~~~~~~
                  absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(
                                                      ^
tensorflow/core/kernels/data/dataset_utils.cc:884:19: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
      status_mu = std::make_unique<mutex>();
                  ^~~~~~~~~~~~~~~~
                  absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(
                                                      ^
4 errors generated.
Target //tensorflow/lite:libtensorflowlite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 690.094s, Critical Path: 483.34s
INFO: 757 processes: 13 internal, 744 local.
FAILED: Build did NOT complete successfully

**Comment by abattery** [comment]
@thaink could you take a look at this?

**Comment by Krisonrik** [comment]
btw, I also tested on master branch, same thing. Although 2.4.0 seems to have other fails besides the make_unique not being defined.

**Comment by thaink** [comment]
std::make_unique is introduced in C++14.
You should build with --cxxopt='--std=c++14'.
And if you add "//tensorflow/lite/delegates/flex:delegate" as dependency, --config=monolithic may also be required.

**Comment by abattery** [comment]
@thaink could you make sure that the necessary build flags are mentioned in the our guide page?

**Comment by thaink** [comment]
By default, we always build with c++14: https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L300
We don't add it in sample commands in https://www.tensorflow.org/lite/guide/build_android but I think it is good since adding config with default value with have no effect but make the command more complicated.

**Comment by abattery** [comment]
IMO, it would be nice to have the sample command at least for  `--config=monolithic`.

**Comment by mohantym** [comment]
Hi @Krisonrik !
This issue seems be resolved with C++14 flag from above [comment](https://github.com/tensorflow/tensorflow/issues/47711#issuecomment-796378549). You can also refer [Cmake ](https://www.tensorflow.org/lite/guide/build_cmake)documentation to build for android and other architecture. 

Thank you!
