### ISSUE TITLE
keras.io List of topics on the right cannot be navigated

### ISSUE THREAD

**Issue by eduardosuela** [tensorflow/tensorflow#47729]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: 
https://keras.io/guides/training_with_built_in_methods/
It is an example. 
This issue applies to the whole site

## Description of issue (what needs changing): 
List of topics on the right cannot be navigated at keras.io

### Clear description
When navigating docs at keras.io when the list of topics on the right (LOTOR) is longer than the browser height you cannot touch topics in the bottom. There is no scroll on the page, so the topics are un reachable.

### Suggested solution
LOTOR is fixed in position now 
LOTOR should have a scroll bar or move with all the page 

Many thanks

**Comment by ymodak** [comment]
<img width="1348" alt="Screen Shot 2021-03-22 at 3 03 50 PM" src="https://user-images.githubusercontent.com/42785357/112064315-00965a80-8b20-11eb-8084-9d60247af9a7.png">

I see that the last topic on the right hand side index table fits exactly on the bottom of the screen and there is no more content to scroll down.
