### ISSUE TITLE
Still unable to install in python 3.9(64 BIT) in windows 10 

### ISSUE THREAD

**Issue by ShyamSundhar1411** [tensorflow/tensorflow#47723]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@ShyamSundhar1411 
There is a detailed thread about Tensorflow's support for Python 3.9 in #44485. Can you please confirm if we can close this issue as it is being already tracked? Thanks!

**Comment by jvishnuvardhan** [comment]
This is marked as feature request. duplicate #44485
Thanks!
