### ISSUE TITLE
fit_generator is calling __getitem__ with id=0 twice in the first epoch

### ISSUE THREAD

**Issue by nicochidt** [tensorflow/tensorflow#47728]
**System information**
- Have I written custom code : Yes
- OS Platform and Distribution: MacOS 11.2.2
- TensorFlow installed from (source or binary): Installed with pip
- TensorFlow version: v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.7.4

**Describe the current behavior**
When using a generator and `fit_generator` (or `fit` for the case) method, the first time `__getitem__` is called, repeats the idx = 0, which produces that the generator either sends the same batch twice or have errors since `on_epoch_end` is not called on time.

**Describe the expected behavior**
__getitem__ should always be called with incremental indexes as argument. 

**Standalone code to reproduce the issue**

```
from tensorflow.keras.utils import Sequence
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import numpy as np

class DataGenerator(Sequence):
    def __init__(self, batch_size = 512, shape = (10,)):
        self.shape = shape
        self.batch_size = batch_size

    def on_epoch_end(self):
        # do nothing
        pass

    def __getitem__(self, idx):
        print("[+] Idx: %d" % idx)
        y = np.ones((10,2))
        y[:,0] = 0
        return np.random.random((10,10)), y

    def __len__(self):
        return 7

inp = Input(shape = (10,), dtype = np.float)
x = Dense(10, activation = 'relu')(inp)
out = Dense(2, activation='softmax')(x)
model = Model(inputs=inp, outputs= out)

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

generator = DataGenerator()

model.fit_generator(generator, epochs = 2, shuffle = False, workers = 0)
```
The output of the above code is: 
```
[+] Idx: 0
Epoch 1/10
[+] Idx: 0
1/7 [===>..........................] - ETA: 1s - loss: 0.7483 - accuracy: 0.3000[+] Idx: 1
[+] Idx: 2
[+] Idx: 3
[+] Idx: 4
[+] Idx: 5
[+] Idx: 6
7/7 [==============================] - 0s 1ms/step - loss: 0.7374 - accuracy: 0.4012
Epoch 2/10
[+] Idx: 0
1/7 [===>..........................] - ETA: 0s - loss: 0.6861 - accuracy: 0.6000[+] Idx: 1
[+] Idx: 2
[+] Idx: 3
[+] Idx: 4
[+] Idx: 5
[+] Idx: 6
```
When it shouldn't  call` __getitem__` twice with `Idx: 0`

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate this on tf 2.3,2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/222be34238eb7807514249bb47a50c14/untitled561.ipynb)

**Comment by nicochidt** [comment]
@Saduf2019, thanks for taking a look. In case it helps, this is not present in tf 2.0. The problem appeared when updating from 2.0 to 2.4.

**Comment by nicochidt** [comment]
I don't see this moving forward soon, so in case anyone has the same problem, this is an ugly trick to make the generator work: 

```
from tensorflow.keras.utils import Sequence
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import numpy as np

class DataGenerator(Sequence):
    def __init__(self, batch_size = 512, shape = (10,)):
        self.shape = shape
        self.batch_size = batch_size
        self.first_epoch = True

    def on_epoch_end(self):
        # do nothing
        pass

    def __getitem__(self, idx):
        print("[+] Idx: %d" % idx)
        y = np.ones((10,2))
        y[:,0] = 0
        if self.first_epoch:
               self.first_epoch = False
               self.on_epoch_end()
        return np.random.random((10,10)), y

    def __len__(self):
        return 7

inp = Input(shape = (10,), dtype = np.float)
x = Dense(10, activation = 'relu')(inp)
out = Dense(2, activation='softmax')(x)
model = Model(inputs=inp, outputs= out)

model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

generator = DataGenerator()

model.fit_generator(generator, epochs = 2, shuffle = False, workers = 0)
```

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210531,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/20eef508d78beaaa4306dd4ead0c3ccd/untitled160.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
