### ISSUE TITLE
tensorflow/models/compression does not work

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#4772]
To run the compression model:

`python encoder.py --input_image=/your/image/here.png \ --output_codes=output_codes.pkl --iteration=15 --model=residual_gru.pb`

However, this error shows up:
> [libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.

I see from v0.8.0 RC0 that it has been fixed:
> Added instructions and binaries for ProtoBuf library with fast serialization and without 64MB limit

Could this error have been reintroduced? I'm using 0.10.0.

**Comment by tatatodd** [comment]
@jkschin Can you provide the full error log?  Also the following environment information:

-----

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

**Comment by jkschin** [comment]
-rw-r--r-- 1 root root   322936 Aug 16  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 16  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 59909104 Sep 20 20:51 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 Jul  3 16:54 /usr/local/cuda/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Jul  3 16:54 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 59909104 Sep 20 20:51 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 59909104 Sep 20 20:51 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 root root 58775484 Sep 20 20:51 /usr/local/cuda/lib64/libcudnn_static.a

Installed from source:
51238b1b5219a37ba145915efa764cca870e0d9f
0.3.0

**Comment by tatatodd** [comment]
@jkschin The commit hash 51238b1b5219a37ba145915efa764cca870e0d9f corresponds to the `models` repository:
https://github.com/tensorflow/models/commit/51238b1b5219a37ba145915efa764cca870e0d9f

How about your `tensorflow` repository?  If you installed from source, please provide the commit hash of that repo (i.e. run `git rev-parse HEAD` under the tensorflow repo directory).  Otherwise provide a link to the pip package you installed, and the output from `python -c "import tensorflow; print(tensorflow.__version__)"`.  Thanks!

**Comment by DaveyTao** [comment]
Please refer to: https://github.com/tensorflow/models/pull/510
and https://github.com/tensorflow/models/pull/510/commits/608f46debea6b1e4ffb6c3ccea5771004693bd4c

**Comment by jkschin** [comment]
@tatatodd I recompiled and ran it already. I think I should just close this.
