### ISSUE TITLE
ValueError: Shape (?, 4096) must have rank 1

### ISSUE THREAD

**Issue by egorlitvinenko** [tensorflow/tensorflow#4773]
Operating System: _CentOS 6 - box for vagrant_

Installed version of CUDA and cuDNN: 
ls -l /path/to/cuda/lib/libcud*: "No such file or directory"
_No CUDA installed._

Installation:
1.  Installed with Anaconda 4.0.9;
2. `python -c "import tensorflow; print(tensorflow.__version__)"`: _0.10.0rc0_;
3. Python 3.5, numpy 1.11.2, scipy 0.18.1;

### Reproduce

It is standard VGG model with 16 layers. I tried extract vgg.fc2 layer:
http://pastebin.com/A1qd7g2e

I also get this error after `session.run` was called.

### What other attempted solutions have you tried?
I'm a new user of tenserflow and don't know any attempted solutions. I found this issue - https://github.com/tensorflow/tensorflow/issues/3815, but it is closed.

### Logs or other output that would be helpful
Stacktrace - http://pastebin.com/eaQi1T0R

**Comment by tatatodd** [comment]
@egorlitvinenko Please provide the full error log, including the stack trace.

**Comment by egorlitvinenko** [comment]
I provided all log with stacktrace, which I see in Jupyter notebook. Is there another place, from which I should take log?

**Comment by tatatodd** [comment]
My apologies @egorlitvinenko I missed the stacktrace you provided.

But I'm still confused.  What implementation of vgg are you using?  Can you provide a link?

I don't think it's implementation we've provided below, since there is no vgg16 (but there is vgg_16).
https://github.com/tensorflow/models/blob/master/slim/nets/vgg.py

**Comment by egorlitvinenko** [comment]
@tatatodd Yes, it is another implementation - http://pastebin.com/tkmXvw4H

**Comment by tatatodd** [comment]
@egorlitvinenko I recommend you first read about the basic concepts of TensorFlow, in particular the difference between "Building the graph" and "Launching the graph in a session":
https://www.tensorflow.org/versions/r0.11/get_started/basic_usage.html#basic-usage

Here are lines 7 and 8 of your example:
```
print(vgg.fc2[:20]) # this is error line
return vgg, sess.run(vgg.fc2, feed_dict={vgg.imgs: [img1]})
```

Note that the `sess.run` call in line 8 is where you actually run the graph.  The `vgg.fc2` in line 7 is referring to a graph node, *before* you've run the graph.  If you want to inspect the output, you should inspect the result returned by `sess.run`.

Note that we primarily use github issues to track bugs and feature requests.  This type of question is better suited for StackOverflow, which we also monitor.  In the future please ask these types of questions there and tag it with the `tensorflow` tag.  Thanks!
