### ISSUE TITLE
Building TFLite Python wheel consumes excessive memory

### ISSUE THREAD

**Issue by Shamino0** [tensorflow/tensorflow#47737]
I am building the TFLite runtime using the instructions described at https://www.tensorflow.org/lite/guide/build_cmake_pip

When I run this (in a Linux VM with 8GB RAM and 8GB swap), the build process consumes all memory and crashes.  There are hundreds of instances of the C compiler running at once, which is causing the problem.

It appears that there are two places where a raw `-j` (without any number of jobs) is passed to Make, causing it to spawn parallel builds without limit.

I made the following changes locally to fix it:

~~~~
$ git diff
diff --git a/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh b/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh
index 832106ec7a8..75adb911078 100755
--- a/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh
+++ b/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh
@@ -113,7 +113,7 @@ case "${TENSORFLOW_TARGET}" in
     ;;
 esac
 
-cmake --build . --verbose -j -t _pywrap_tensorflow_interpreter_wrapper
+cmake --build . --verbose -t _pywrap_tensorflow_interpreter_wrapper
 cd "${BUILD_DIR}"
 
 case "${TENSORFLOW_TARGET}" in
diff --git a/tensorflow/lite/tools/pip_package/setup.py b/tensorflow/lite/tools/pip_package/setup.py
index a85053b1602..e0ab72cd82a 100644
--- a/tensorflow/lite/tools/pip_package/setup.py
+++ b/tensorflow/lite/tools/pip_package/setup.py
@@ -82,7 +82,7 @@ def make_args(target='', quiet=True):
   args = ([
       'make', 'SHELL=/bin/bash', 'BUILD_WITH_NNAPI=false', '-C', TENSORFLOW_DIR
   ] + MAKE_CROSS_OPTIONS +
-          ['-f', RELATIVE_MAKEFILE_PATH, '-j',
+          ['-f', RELATIVE_MAKEFILE_PATH, # '-j',
            str(get_build_cpus())])
   if quiet:
     args.append('--quiet')
diff --git a/tensorflow/tools/ci_build/devtoolset/build_devtoolset.sh b/tensorflow/tools/ci_build/devtoolset/build_devtoolset.sh
index f56f834743c..b79076f52a9 100755
--- a/tensorflow/tools/ci_build/devtoolset/build_devtoolset.sh
+++ b/tensorflow/tools/ci_build/devtoolset/build_devtoolset.sh
@@ -114,7 +114,7 @@ cd "${TARGET}-build"
       --with-linker-hash-style="gnu" \
       --with-tune="generic" \
       && \
-    make -j 42 && \
+    make -j 16 && \
     make install
 
 # Create the devtoolset libstdc++ linkerscript that links dynamically against
diff --git a/tensorflow/tools/ci_build/linux/cmake/run.sh b/tensorflow/tools/ci_build/linux/cmake/run.sh
index d9bf4f01b5d..52c6bd5daa6 100755
--- a/tensorflow/tools/ci_build/linux/cmake/run.sh
+++ b/tensorflow/tools/ci_build/linux/cmake/run.sh
@@ -29,7 +29,7 @@ pushd build
 cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
 # When building do not use all CPUs due to jobs running out of memory.
 # TODO(gunan): Figure out why we run out of memory in large GCE instances.
-make --jobs 20 tf_python_build_pip_package
+make tf_python_build_pip_package
 
 virtualenv cmake_test --system-site-packages
 source cmake_test/bin/activate
@@ -44,7 +44,7 @@ mv $WHEEL_FILE_PATH $FIXED_WHEEL_PATH
 pip install --upgrade $FIXED_WHEEL_PATH
 
 # Run all tests.
-ctest -C Release --output-on-failure -j
+ctest -C Release --output-on-failure
 
 # Finalize and go back to the initial directory.
 deactivate
~~~~

Please consider incorporating these changes.  Especially the changes to `build_pip_package_with_cmake.sh` and `pip_package/setup.py`, which I believe are the files directly responsible for the problem.  With these changes, the Python wheel compiles fine and the system's memory usage remains within normal sizes.

**Comment by abattery** [comment]
@terryheo could you review this suggestion?

**Comment by terryheo** [comment]
Could you confirm if only "build_pip_package_with_cmake.sh" changes fix your issue?
BTW, what's the number of available cores in your VM?

**Comment by Shamino0** [comment]
Yes, that change alone is sufficient.  It prevented multiple instances of the compiler and memory usage for the entire VM never exceeded 1GB.

The VM is configured for only one core, so the scripts (which is most of them) that check the number of cores are passing `-j 1` as they should.

**Comment by terryheo** [comment]
Thanks for the confirmation. I'll work on it.

**Comment by terryheo** [comment]
Now you can configure it as following.
```
$ BUILD_NUM_JOBS=1 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh
```

**Comment by Shamino0** [comment]
This doesn't solve the problem.  The default number of jobs is still unlimited, which means anybody following the instructions on the web page (https://www.tensorflow.org/lite/guide/build_cmake_pip) will hit the same problem.

Allowing the user to specify the number of jobs on the command line is a workaround, not a solution.  The script needs to do what most of the other build scripts do and set the default number of jobs to equal the number of CPUs.

**Comment by Shamino0** [comment]
May I suggest this change as a more proper fix.

Near the top of the file:

    NUM_CPUS=$(grep -c ^processor /proc/cpuinfo)

In the cmake line:

    cmake --build . --verbose -j ${BUILD_NUM_JOBS:-$NUM_CPUS} -t _pywrap_tensorflow_interpreter_wrapper
