### ISSUE TITLE
What is the supported sequence length of bert-tiny and bert-small?

### ISSUE THREAD

**Issue by John-8704** [tensorflow/tensorflow#47741]
Here are few bert models I came across recently but couldn't figure out the maximum supported sequence length, Is it 512 tokens per sentence?

Does these models have the same 512 token limit as the original bert-base model

```
L=2 | 2/128 (BERT-Tiny) | 2/256 | 2/512 | 2/768
L=4 | 4/128 | 4/256 (BERT-Mini) | 4/512 (BERT-Small) | 4/768

```

**Comment by Saduf2019** [comment]
@John-8704 
The input dimension is dependent on the dimension of positional embedding [table created](https://github.com/google-research/bert/blob/master/README.md), the model should be able to handle 256 sequence length.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by John-8704** [comment]
@Saduf2019 Just have a doubt, You are saying it should handle 256 sequence length but according to papers isn't BERT suppose to handle texts upto 512 sequence length? Does these versions of Bert can't handle 512 sequence length?

**Sure, will post such questions at Stackoverflow going forward. Thank you.**

**Comment by Saduf2019** [comment]
@John-8704
As per your request on Bert tiny, it should be able to handle 256[ you can download a model, inspect its input layers], yes Bert base can handle 512. Please move this to closed status and create a issue on stackOverflow as it is a large community to answer.
