### ISSUE TITLE
Error while using tensorflow==2.4.1  #tensorflow-probability==0.12.1, for the code that works with TF1.15 and TFP 0.8.0

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#47742]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, referring to https://github.com/zhulingchen/tfp-tutorial
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- TensorFlow version (use command below):v1.15.4-39-g3db52be 1.15.5 (code works fine with TF15)
- Python version:3.6
- CUDA/cuDNN version:11
- GPU model and memory:12GB

**Describe the current behavior**
Learning TFP. the Code works fine with TF15 and TFP0.8, but error while using with TF2.4 and TFP0.9

Note: same code works in TF2.4 by adding below lines
`import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()`
But would not like to use this, since I would like to use the improvements made in TF2.4, including tf.distribute.MirroredStrategy

**Describe the expected behavior**
The TFP code should work with TF2.4, please guide me to make changes 

**Standalone code to reproduce the issue**
https://github.com/rrklearn2020/learn_tfp.git

**Other info / logs** Include any logs or source code that would be helpful to
-```
-------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-24-3cf063f5b2a9> in <module>
    103                               validation_data=(x_test, y_test),
    104                               shuffle=True,
--> 105                               callbacks=callbacks)
    106                 else:
    107                     print('Using real-time data augmentation.')

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1097                 batch_size=batch_size,
   1098                 _r=1):
-> 1099               callbacks.on_train_batch_begin(step)
   1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in on_train_batch_begin(self, batch, logs)
    442     """
    443     if self._should_call_train_batch_hooks:
--> 444       self._call_batch_hook(ModeKeys.TRAIN, 'begin', batch, logs=logs)
    445 
    446   def on_train_batch_end(self, batch, logs=None):

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
    292 
    293     if hook == 'begin':
--> 294       self._call_batch_begin_hook(mode, batch, logs)
    295     elif hook == 'end':
    296       self._call_batch_end_hook(mode, batch, logs)

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_begin_hook(self, mode, batch, logs)
    301     """Helper function for `on_*_batch_begin` methods."""
    302     hook_name = 'on_{mode}_batch_begin'.format(mode=mode)
--> 303     self._call_batch_hook_helper(hook_name, batch, logs)
    304 
    305     if self._check_timing:

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook_helper(self, hook_name, batch, logs)
    358         if numpy_logs is None:  # Only convert once.
    359           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
--> 360         hook(batch, numpy_logs)
    361 
    362     if self._check_timing:

............/tf2x_tfp_venv/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in on_train_batch_begin(self, batch, logs)
    690     """
    691     # For backwards compatibility.
--> 692     self.on_batch_begin(batch, logs=logs)
    693 
    694   @doc_controls.for_subclass_implementers

<ipython-input-8-f80d1df575fd> in on_batch_begin(self, batch, logs)
      8     def on_batch_begin(self, batch, logs=None):
      9         if self.update_per_batch:
---> 10             n_batch_per_epoch = int(np.ceil(self.params['samples'] / self.params['batch_size']))
     11             idx_total_batch = (self.epoch - self.n_silent_epoch) * n_batch_per_epoch + batch + 1
     12             kl_weight = (idx_total_batch / n_batch_per_epoch) / self.n_annealing_epoch

KeyError: 'samples'

​

```

**Comment by amahendrakar** [comment]
@rrklearn2020,
Please take a look at [this guide](https://www.tensorflow.org/guide/migrate) to migrate your code from TensorFlow 1.x to 2.x and check if it helps. Thanks!

**Comment by rrklearn2020** [comment]
@amahendrakar, I did check this link (before raising the support request), some changes are made, but still, there are errors. I have attached the ipynb file. Please support.

**Comment by amahendrakar** [comment]
@rrklearn2020,
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the error easily. Thanks!

**Comment by rrklearn2020** [comment]
I tried to debug little more and found that the error is caused by the class as shown below.
`class KLLossScheduler(tf.keras.callbacks.Callback):
    def __init__(self, update_per_batch=False, n_silent_epoch=5, n_annealing_epoch=50, verbose=0):
        self.update_per_batch = update_per_batch
        self.n_silent_epoch = n_silent_epoch
        self.n_annealing_epoch = n_annealing_epoch
        self.verbose = verbose
        super(KLLossScheduler, self).__init__()
    def on_batch_begin(self, batch, logs=None):
        if self.update_per_batch:
            n_batch_per_epoch = int(np.ceil(self.params['samples'] / self.params['batch_size']))
            idx_total_batch = (self.epoch - self.n_silent_epoch) * n_batch_per_epoch + batch + 1
            kl_weight = (idx_total_batch / n_batch_per_epoch) / self.n_annealing_epoch
            kl_weight = np.maximum(0.0, np.minimum(kl_weight, 1.0))
            self.kl_weight = kl_weight
            if self.verbose > 0:
                print('\nBatch: {}, KL Divergence Loss Weight = {:.6f}'.format(batch+1, kl_weight))
            for l in self.model.layers:
                for id_w, w in enumerate(l.weights):
                    if 'kl_loss_weight' in w.name:
                        l_weights = l.get_weights()
                        l.set_weights([*l_weights[:id_w], kl_weight, *l_weights[id_w+1:]])
    def on_epoch_begin(self, epoch, logs=None):
        self.epoch = epoch
        if not self.update_per_batch:
            kl_weight = (epoch - self.n_silent_epoch + 1) / self.n_annealing_epoch
            kl_weight = np.maximum(0.0, np.minimum(kl_weight, 1.0))
            self.kl_weight = kl_weight
            if self.verbose > 0:
                print('\nEpoch: {}, KL Divergence Loss Weight = {:.6f}'.format(epoch+1, kl_weight))
            for l in self.model.layers:
                for id_w, w in enumerate(l.weights):
                    if 'kl_loss_weight' in w.name:
                        l_weights = l.get_weights()
                        l.set_weights([*l_weights[:id_w], kl_weight, *l_weights[id_w+1:]])
    def on_epoch_end(self, epoch, logs={}):
        print('KL Divergence Weight = {:.6f}, KL Divergence Loss = {:.4f}'.format(self.kl_weight,
                                                                                  sum(self.model.losses).numpy()))`

It would be a great help if you can share some hints to update this area with TF2.x
(Note: This class is from https://github.com/zhulingchen/tfp-tutorial. and works good with TF1.15 and TFP <0.9)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, [TF v2.4](https://colab.research.google.com/gist/amahendrakar/d03d72ef716567aec789a049c38ea555/47742.ipynb) and TF-nightly.

Whereas with [TF v1.15.4](https://colab.research.google.com/gist/amahendrakar/3e0c27e5b990767cba1d137f0fc44d9b/47742-1-15.ipynb), I was able to run the code without any issues. Please check the linked gist for reference. Thanks!

**Comment by rrklearn2020** [comment]
It would be a great help if you can share some hints to update this area with TF2.x

**Comment by rrklearn2020** [comment]
@rmothukuru  @amahendrakar @tensorflowbutler 

Please support. Waiting for your feedback..
