### ISSUE TITLE
undeclared includion error when building libtensorflowlite.so

### ISSUE THREAD

**Issue by Krisonrik** [tensorflow/tensorflow#47744]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS Big Sur Version 11.2.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
master branch af4b0dfbb251cae9f6407c851cfd5bc11a172b3b
- Python version:
3.8
- Installed using virtualenv? pip? conda?:
conda
- Bazel version (if compiling from source):
3.7.2
- GCC/Compiler version (if compiling from source):
Apple clang version 12.0.0 (clang-1200.0.32.29) 
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
When compiling libtensorflowlite.so with //tensorflow/lite/delegates/flex::delegate as dependency, build fail with undeclared includions in error.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build \
//tensorflow/lite:libtensorflowlite.so \
--config=monolithic \
--cxxopt='--std=c++14' \
-c opt \

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=112
INFO: Reading rc options for 'build' from /Users/richardyao/Code/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/richardyao/Code/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --java_toolchain=@org_tensorflow//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=@org_tensorflow//third_party/toolchains/java:tf_java_toolchain --//tensorflow/core/kernels/mlir_generated:enable_gpu=false --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /Users/richardyao/Code/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/richardyao/opt/miniconda3/bin/python3 --action_env PYTHON_LIB_PATH=/Users/richardyao/opt/miniconda3/lib/python3.8/site-packages --python_path=/Users/richardyao/opt/miniconda3/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /Users/richardyao/Code/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/richardyao/Code/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/richardyao/Code/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:monolithic in file /Users/richardyao/Code/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:macos in file /Users/richardyao/Code/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (3 packages loaded, 158 targets configured).
INFO: Found 1 target...
ERROR: /Users/richardyao/Code/tensorflow/tensorflow/compiler/mlir/xla/BUILD:262:11: undeclared inclusion(s) in rule '//tensorflow/compiler/mlir/xla:hlo_utils':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/mlir/xla/hlo_utils.cc':
  'bazel-out/darwin-opt/bin/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen/mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.h.inc'
Target //tensorflow/lite:libtensorflowlite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1429.033s, Critical Path: 828.11s
INFO: 1071 processes: 13 internal, 1058 local.
FAILED: Build did NOT complete successfully

**Comment by abattery** [comment]
@thiank could you take a look at this?

**Comment by thaink** [comment]
I am able to build with that command using linux.
Can you try to build //tensorflow/lite:ltensorflowlite, it will have different file format based on the target operating system.

**Comment by Krisonrik** [comment]
Is it possible to build for linux with macOS? I was also able to complete build with 2.4.0, but the resulting .so somehow have issue during linking. 
ld.lld: error: /root/project/ext/tensorflow/lib/linux/cpu/libtensorflowlite.so: unknown file type

**Comment by thaink** [comment]
you could try --config=linux or some other in this file https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L351

**Comment by mohantym** [comment]
Hi @Krisonrik !
I got a successful build in my Mac M1 with below command (with 2.9 and Bazel 5.0.0) . used .dylib instead of .so .
```
bazel build --config=monolithic -c opt //tensorflow/lite:libtensorflowlite_c.dylib
 
```

<img width="1506" alt="Screen Shot 2022-10-07 at 10 45 51 AM" src="https://user-images.githubusercontent.com/86464649/194509071-960bba6d-dec5-45a8-ad9a-a3bbee5c5823.png">


Thank you!
