### ISSUE TITLE
Failed to convert QAT model to tflite when I use tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8

### ISSUE THREAD

**Issue by eliver8801** [tensorflow/tensorflow#47746]
1. System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
TensorFlow installation (pip package or built from source):pip package
TensorFlow library (version, if pip package or github SHA, if built from source):2.3.1
2. Code

Provide code to help us reproduce your issues using one of the following options:
When I use tf.lite.TFLiteConverter to convert keras ACTIVATIONS_INT16_WEIGHTS_INT8 QAT model to tflite file。There are some bugs and the conversion is failed.
This is my convert code and Bugs.
quant_converter1 = tf.lite.TFLiteConverter.from_keras_model(model1_quant)
quant_converter1.optimizations = [tf.lite.Optimize.DEFAULT]
quant_converter1.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
quant_tflite_model1 = quant_converter1.convert()
with open(model1_tflite_quant, 'wb') as f:
f.write(quant_tflite_model1)
as
**I updated the TensorFlow to the latest stable version v2.4.1 and also face the same error** @amahendrakar
![image](https://user-images.githubusercontent.com/12438262/110884962-e10c6000-82dd-11eb-9659-af72df2f8edd.png)

**Comment by abattery** [comment]
@ethkim could you triage this issue?

**Comment by pjpratik** [comment]
@eliver8801 I was checking if the issue still exists.

You can try [Experiment with Quantization](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide#experiment_with_quantization) and try with quantization configurations to check for your use case.

Could you provide a standalone reproducible code in order better understand the issue. Also, please try `experimental_new_converter = TRUE` to enable MLIR based conversion. 

Thanks!
