### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, MUL, PACK, RESHAPE, SHAPE, STRIDED_SLICE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: Conv3D, Conv3DBackpropInputV2, MaxPool3D.

### ISSUE THREAD

**Issue by aliceruget** [tensorflow/tensorflow#47756]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, MUL, PACK, RESHAPE, SHAPE, STRIDED_SLICE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: Conv3D, Conv3DBackpropInputV2, MaxPool3D.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by amahendrakar** [comment]
@aliceruget,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by abattery** [comment]
I recommend enabling the Select TF option to use TF ops for your model? https://www.tensorflow.org/lite/guide/ops_select

**Comment by aliceruget** [comment]
Thank you very much for the quick response @amahendrakar and @abattery!

My TensorFlow version is 2.2.0. 
I can't unfortunately share the main code or the dataset @amahendrakar because of its confidentiality ... I can try to find another code that would give the same error ? 

I indeed enabled the TF option @abattery which erased the error on Conv3D and MaxPool3D in this way :
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
This however kept the error on Conv3DBackpropInputV2. 

I can avoid this error on Conv3DBackpropInputV2 by adding converter.allow_custom_ops=True. 
However, when I run afterwards
interpreter = tf.lite.Interpreter(model_path=model_path_lite)
interpreter.allocate_tensors(), 
then get the  error    
File "keras_code_lite.py", line 11, in <module>
    interpreter.allocate_tensors()
  File "/home/ar432/venv/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/ar432/venv/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Encountered unresolved custom op: Conv3DBackpropInputV2.Node number 2 (Conv3DBackpropInputV2) failed to prepare.

**Comment by abattery** [comment]
Conv3DBackpropInputV2 op is now supported at the tf-nightly version. Please consider upgrading TF version.

**Comment by aliceruget** [comment]
Thanks, using tf-nightly solved my issue!
