### ISSUE TITLE
Getting issues while evaluting the object detection model on tensorflow 2.O

### ISSUE THREAD

**Issue by codePerfectPlus** [tensorflow/tensorflow#47757]
Greetings,

I am trying TF-OD API for object detection. I am getting issues while evaluating the model by given methods in the documentation. It always showing out of memory. Even I tried on the colab. How should I evaluate the model.

Tensorflow Version- 2.4.1
CUDA:- True with 2 GB graphics
Python Version- 3.8 Ananconda
Platform- Windows 10

## URL(s) with the issue:
https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#evaluating-the-model-optional

Thanks for helping out.

**Comment by Saduf2019** [comment]
@codePerfectPlus 
Please share the colab gist for us to analyse.

You may also refer to : [link](https://stackoverflow.com/questions/36927607/how-can-i-solve-ran-out-of-gpu-memory-in-tensorflow), #32707, [link1](https://github.com/tensorflow/tensorflow/issues/40646#issuecomment-647224203)

**Comment by codePerfectPlus** [comment]
@Saduf2019  Thanks for helping out. Issue is fixed now.

**Comment by Saduf2019** [comment]
@codePerfectPlus 
Thank you for your update, glad the issue is resolved.
