### ISSUE TITLE
I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

### ISSUE THREAD

**Issue by 6368696a6961** [tensorflow/tensorflow#47753]
I run my code on pycharm
include :  import tensorflow as tf

In the run window show me the red line: 
I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

tf version: tensorflow-2.4.0rc4-cp37-cp37m-win_amd64.whl

How can I fix it

**Comment by amahendrakar** [comment]
@6368696a6961,
The messages are just information logs stating that TensorFlow has successfully detected the GPU on your machine. You can safely ignore them.

You can also disable them by changing the log level using the below code snippet

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```

Please find the gist of the same [here](https://colab.research.google.com/gist/amahendrakar/2d37b3975927274613d098cb1f6428cc/47753.ipynb). 

Thanks!

**Comment by 6368696a6961** [comment]
> @6368696a6961,
> The messages are just information logs stating that TensorFlow has successfully detected the GPU on your machine. You can safely ignore them.
> 
> You can also disable them by changing the log level using the below code snippet
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
> import tensorflow as tf
> ```
> 
> Please find the gist of the same [here](https://colab.research.google.com/gist/amahendrakar/2d37b3975927274613d098cb1f6428cc/47753.ipynb).
> 
> Thanks!
