### ISSUE TITLE
Tensorflow Random segmentation faults

### ISSUE THREAD

**Issue by ajinkyaambatwar** [tensorflow/tensorflow#47752]
I am trying to run the demo code from official tensorflow [website][1]
I am attaching the full code (copied and arranged) here for ease
```
import tensorflow as tf

# print("1")
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import time
import os

# print("2")
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"


# @tf.function
def train_step(x, y):
    with tf.GradientTape() as tape:
        logits = model(x, training=True)
        loss_value = loss_fn(y, logits)
    grads = tape.gradient(loss_value, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))
    train_acc_metric.update_state(y, logits)
    return loss_value


# @tf.function
def test_step(x, y):
    val_logits = model(x, training=False)
    val_acc_metric.update_state(y, val_logits)


inputs = keras.Input(shape=(784,), name="digits")
x1 = layers.Dense(64, activation="relu")(inputs)
x2 = layers.Dense(64, activation="relu")(x1)
outputs = layers.Dense(10, name="predictions")(x2)
model = keras.Model(inputs=inputs, outputs=outputs)

# Instantiate an optimizer.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
train_acc_metric = keras.metrics.SparseCategoricalAccuracy()
val_acc_metric = keras.metrics.SparseCategoricalAccuracy()
# Prepare the training dataset.
batch_size = 64
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = np.reshape(x_train, (-1, 784))
x_test = np.reshape(x_test, (-1, 784))

# Reserve 10,000 samples for validation.
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

# Prepare the training dataset.
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Prepare the validation dataset.
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(batch_size)

epochs = 2
for epoch in range(epochs):
    print("\nStart of epoch %d" % (epoch,))
    start_time = time.time()

    # Iterate over the batches of the dataset.
    for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
        loss_value = train_step(x_batch_train, y_batch_train)

        # Log every 200 batches.
        if step % 200 == 0:
            print(
                "Training loss (for one batch) at step %d: %.4f"
                % (step, float(loss_value))
            )
            print("Seen so far: %d samples" % ((step + 1) * 64))

    # Display metrics at the end of each epoch.
    train_acc = train_acc_metric.result()
    print("Training acc over epoch: %.4f" % (float(train_acc),))

    # Reset training metrics at the end of each epoch
    train_acc_metric.reset_states()

    # Run a validation loop at the end of each epoch.
    for x_batch_val, y_batch_val in val_dataset:
        test_step(x_batch_val, y_batch_val)

    val_acc = val_acc_metric.result()
    val_acc_metric.reset_states()
    print("Validation acc: %.4f" % (float(val_acc),))
    print("Time taken: %.2fs" % (time.time() - start_time))
    print("end")
```
Without any reason, this code enters Segmentation Fault in Tensorflow 2.3.1 right at the beginning
```
>python dummy.py 
2021-03-11 17:45:52.231509: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Segmentation fault (core dumped)
```
Interestingly if I put some random print statements at the very start(those ```print("1")``` etc statements, the code will execute till the end and suffer segmentation fault at the end(redundant output not shown)
```
Start of epoch 1
Training loss (for one batch) at step 0: 1.0215
Seen so far: 64 samples
Training loss (for one batch) at step 200: 0.9116
Seen so far: 12864 samples
Training loss (for one batch) at step 400: 0.4894
Seen so far: 25664 samples
Training loss (for one batch) at step 600: 0.5636
Seen so far: 38464 samples
Training acc over epoch: 0.8416
Validation acc: 0.8296
Time taken: 3.16s
end
Segmentation fault (core dumped)
```
Another observation is, if I uncomment the `@tf.function` on top of my `trainStep` and `testStep` functions, the code enters into segfault again but after it prints
```Start of epoch 0```

System Specs - 
OS - Ubuntu 14.04
CPU - Intel Core I7
RAM - 64GB
CUDA version - 10.1
CUDNN - 7.6
TF version - 2.3.1(installed via ```pip```)
VRAM - 12GB
GPU - NVIDIA GTX1080TI

Using conda environment with python3.6/python3.7(tried both separately)
Even tried python virtualenv and still got the issue

I thought it might be some issue with my TF2.3 version. Hence I tried everything from TF2.0.0 till TF2.3.2 (CUDA 11 is not supported on Ubuntu 14 and hence can't work with TF2.4.1). I either enter ```Segmentation Fault``` at some place or the other. If not that I get this error.

```*** Error in `python': double free or corruption (!prev): 0x000000000167c080 ***```
I even got libtcmalloc-minimal4 which was suggested for double free error on another thread.

### The code only worked for TF2.0.x without any issue. But I can't use this, as 2.0.x does not support RaggedTensor backprop as mentioned in [this](https://github.com/tensorflow/tensorflow/issues/35802) thread.
`
Can someone explain what is going wrong with my Tensorflow package?

  [1]: https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

**Comment by amahendrakar** [comment]
@ajinkyaambatwar,
TensorFlow pip packages require Ubuntu 16.04 or later (64-bit). For more information, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and [tested build configurations](https://www.tensorflow.org/install/source#gpu).

Could you please update Ubuntu and let us know if you are still facing the same issue. Thanks!

**Comment by ajinkyaambatwar** [comment]
Sure @amahendrakar , I will try and update you regarding the issue!

**Comment by ajinkyaambatwar** [comment]
Hi @amahendrakar , sorry for delayed response. After upgrading to Ubuntu 18, the issue didn't appear!
Thank you!
