### ISSUE TITLE
Converting models with mutable resource variable with v2 TFLiteConveter

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#47765]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installation (pip package or built from source):
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

This is how the original model is built:

```python
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import *

def get_student_model():
    base_model = MobileNetV2(weights=None, include_top=False,
                input_shape=(224, 224, 3))
    base_model.trainable = True
    inputs = Input(shape=(224, 224, 3)) 
    x = experimental.preprocessing.Rescaling(1./127.5, offset=-1)(inputs)
    y = base_model(x, training=True)
    y = GlobalAveragePooling2D()(y)
    y = Dense(512, activation="relu")(y)
    y = Dropout(0.5)(y)
    outputs = Dense(30, activation='softmax')(y)
    model = tf.keras.Model(inputs, outputs)
    return model
```

This is how the TensorFlow Lite model is generated:

```python
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("mobilenetv2_student_no_true_labels_e_125_t_2")
converter.experimental_new_converter = False
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
open("student_mobilenetv2.tflite", 'wb').write(tflite_model)
print('Model size is %f MBs.' % (len(tflite_model) / 1024 / 1024.0))
```

### 3. Failure after conversion

When trying to convert with `converter.experimental_new_converter = True` the conversion runs into - 

```
ConverterError: <unknown>:0: error: loc("Conv_1_bn/moving_mean"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable
```

With tf-nightly (2.5.0-dev20210312) this issue seems to be persisting as well. 

As per https://github.com/tensorflow/tensorflow/issues/43833#issuecomment-744087884, I understand with the MLIR converter this is probably still unsupported. 

_What is more surprising are the outputs of the TFLite models converted with the TOCO converter. I have tried with just the float model i.e. when the conversion is done without any optimization flag set. The results remain fixed._ 

Here's the Colab Notebook that reproduces this issue: https://colab.research.google.com/gist/sayakpaul/2326ccd94e3d33e1c1ced7dfd7f09519/inference_tflite.ipynb. 

Cc: @MeghnaNatraj @abattery

**Comment by sayakpaul** [comment]
I further looked into the issue and it seems to be stemming from this line, in particular `training=True` - 

```
y = base_model(x, training=True)
```

I instantiated a blank model with the utility function provided above and removed the `training` argument. Doing so allowed me to do the conversion seamlessly. I will try the model again with this change and report back. 

Hope this helps someone facing a similar issue.

**Comment by abattery** [comment]
Hi @sayakpaul 

We are working on the mutable variable support. I will notify this thread once the on-going work is done. Thanks for the filing this feature request!

**Comment by sayakpaul** [comment]
@abattery sure. 

But currently, with the TOCO converter, I am able to run the conversion successfully but that indeed results in spurious outputs. Is this expected or a known behavior?

**Comment by abattery** [comment]
@sayakpaul I am not sure the converted model with TOCO will work correctly for mutable variables.

**Comment by sayakpaul** [comment]
I see. So, the best bet, for now, would be to implement a similar architecture and train using the same loop, and then run the conversions. Am I correct?

**Comment by abattery** [comment]
Could you try using the following code snippet with the tf-nightly version and linking the `tensorflow/lite/kernels:variable_op_kernels`?

```
converter._enable_tflite_resource_variables = True
```

The above experimental items are subject to change since it is under development.

**Comment by sayakpaul** [comment]
@abattery yes, it works now, thanks. Here's the [Colab](https://colab.research.google.com/gist/sayakpaul/76640f20ac8937ddd15a813342c8899a/scratchpad.ipynb). We need to convert it with the flex ops: 

```python
converter = tf.lite.TFLiteConverter.from_saved_model("mobilenetv2_student_no_true_labels_e_125_t_2")
converter._enable_tflite_resource_variables = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("student_mobilenetv2.tflite", 'wb').write(tflite_model)
print('Model size is %f MBs.' % (len(tflite_model) / 1024 / 1024.0))
```

**Comment by karimnosseir** [comment]
Mutable variable support is available in the nightly when converting from SavedModel only (Other types are coming soon).
Builtin ops are available now for VarHandleOp, ReadVariable, AssignVariable in the nightly also

Only thing needed is to set this flag during conversion:
converter.experimental_enable_resource_variables = True

Please let us know if you're having any issues.

Thanks
