### ISSUE TITLE
validate_indices is deprecated and will be removed in a future version. Instructions for updating: The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.?

### ISSUE THREAD

**Issue by John-8704** [tensorflow/tensorflow#47764]
I was trying to train a classification model, this is my model

```
text_inputs = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
tokenize = hub.KerasLayer(preprocessor.tokenize)
tokenized_inputs = [tokenize(text_inputs)]
seq_length = 512
bert_pack_inputs = hub.KerasLayer(
    preprocessor.bert_pack_inputs,
    arguments=dict(seq_length=seq_length))
encoder_inputs = bert_pack_inputs(tokenized_inputs)
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-512_A-8/1", trainable=True)
encoder_outputs = encoder(encoder_inputs)['pooled_output']
output_layer = tf.keras.layers.Dense(1, activation='sigmoid')(encoder_outputs)
```

```
model = tf.keras.Model(inputs=[text_inputs], outputs=[output_layer])
model.summary()


# class weights
target_labels = y_train.tolist()
class_weights = compute_class_weight(
    "balanced", classes=np.unique(target_labels), y=target_labels
)
class_weights = dict(zip(np.unique(target_labels), class_weights))

model.compile(tf.keras.optimizers.Adam(3e-05, epsilon=1e-08, clipnorm=1.0), loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), metrics=["acc"])

model.fit(x_train, y_train, batch_size=64, validation_data=(x_valid, y_valid), epochs=10, callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, verbose=1)], class_weight=class_weights)
```

```
WARNING:tensorflow:From /home/intellectfaces/Desktop/Work/apps/env/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5043: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
WARNING:tensorflow:From /home/intellectfaces/Desktop/Work/apps/env/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:5043: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
Epoch 1/10
 740/7930 [=>............................] - ETA: 32:56 - loss: 0.6752 - acc: 0.5807

```

What does these warnings mean? It only appears when I use class_weights option in model.fit, if i remove that argument no warnings. Does this warning cause any issue with what my model is learning, am I not suppose to use class_weights anymore?

Please provide some assistance.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5 nightly gpu
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1
- GPU model and memory: 24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@John-8704,
On running the given code snippet, I am facing an error stating `KeyError: 'CaseFoldUTF8'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f5086cbfc1fa33f014fb61053c69bbb5/47764.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here?

Also, if you are not facing any errors you can suppress the warning logs by adding the below code snippet before importing TensorFlow
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
.....
```
 Thanks!

**Comment by John-8704** [comment]
> @John-8704,
> On running the given code snippet, I am facing an error stating `KeyError: 'CaseFoldUTF8'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f5086cbfc1fa33f014fb61053c69bbb5/47764.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here?
> 
> Also, if you are not facing any errors you can suppress the warning logs by adding the below code snippet before importing TensorFlow
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
> import tensorflow as tf
> .....
> ```
> 
> Thanks!

To solve the KeyError: 'CaseFoldUTF8', please install and import tensorflow_text library because it is required to use preprocess layer. Make sure to import tensorflow_text before tensorflow.

**Comment by amahendrakar** [comment]
@John-8704,
Thank you for the update. After importing `tensorflow-text`, I am facing an error stating `NameError: name 'y_train' is not defined`. 

Could you please provide the dataset you are using, so that we can reproduce the issue on our end. Thanks!
