### ISSUE TITLE
enh: allow stateless numpy function

### ISSUE THREAD

**Issue by jonas-eschle** [tensorflow/tensorflow#47777]
**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`tf.numpy_function` is assumed to be stateful. However, many pure Python functions (as the example with `np.*` in the docs) are actually stateless. `numpy_function` calls `py_func_common` that actually has a 'stateful' argument. Can't we just pass this through?

**Will this change the current api? How?**
Add an argument `stateful` to `numpy_function`. Defaults to `True`, keeps backwards compatibility

**Who will benefit with this feature?**

This allows optimizations in the graph

**Any Other info.**
Is there any reason why this is not passed through currently?

**Comment by mdanatg** [comment]
cc @allenlavoie @saxenasaurabh 
Marking it stateless might cause trouble if the Python function calls into other TF ops, like variable reads or updates. But if the user is made aware of the pitfalls, it might be ok to allow.

**Comment by mayou36** [comment]
This is then the responsibility of the user I would say, it's a guarantee that the user gives. AFAIK there is currently no way of creating an eager, stateless function from the public API, right? The main motivation is to wrap efficiently np, scipy etc functionality

**Comment by saxenasaurabh** [comment]
Could you provide more detail on what problems you are running into with this? Performance perhaps?

I am not sure why we removed the `stateful` arg in TF2 (compared to `py_func`). Adding it back sounds reasonable to me but it would be nice to understand the impact.

**Comment by mayou36** [comment]
I agree, this discrepancy was my motivation for the issue as (to me) the de-facto difference between the two is the `use_gradient_tape` in `py_function` which leads [to a memory leak](https://github.com/tensorflow/tensorflow/issues/35010#issuecomment-798198842) in eager and is meant for TF eager, not pure Python eager (AFAI understand).

I didn`t run explicitly in performance issues (an artificial example would be easy but also not reality), rather when looking through the code and I didn't understand why it was off. I can't really see a reason for the (potential) loss in performance by not being able to communicate this guarantee.

If that seems risky but we don't know why, we can maybe introduce it as an experimental knob? Or directly expose the `py_func_common` publicly?

**Comment by saxenasaurabh** [comment]
I think adding `stateful=True` arg to the API sounds reasonable. Would you like to send a PR? 
One way to test this change might be to create a tf.function with two calls to `tf.numpy_function` and test that there is no control edge between them. Right now there should be, which is a possibly performance concern I believe.

**Comment by mayou36** [comment]
Sure, gladly doing that!
