### ISSUE TITLE
InvalidArgumentError:  indices[112,8] = -1 is not in [0, 32)

### ISSUE THREAD

**Issue by JoseConi** [tensorflow/tensorflow#47786]
Hi!

Im trying to create an RNN to predict if a stock price will go up or down tomorrow (its just for practice, im not expecting that it works).

But i can not run the model. I let you the code and the error message:

CODE ////////////////////////////////////////////////////////////////////////////////////////////////
`import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras import initializers

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

inTrain, inTest, outTrain, outTest = train_test_split(pd.read_csv("CocaColaImput.csv"), pd.read_csv("CocaColaOutput.csv"), test_size=0.33, random_state=14)
inTrain=inTrain.reset_index(drop=True)
inTest=inTest.reset_index(drop=True)
outTrain=outTrain.reset_index(drop=True)
outTest=outTest.reset_index(drop=True)

model_rnn = Sequential()
model_rnn.add(Embedding(32, 24))
model_rnn.add(Dense(5, activation='relu'))
model_rnn.add(Dense(1, activation='sigmoid'))

model_rnn.compile(loss='mse', optimizer='adam',metrics=['accuracy'])

model_rnn.fit(inTrain, outTrain, batch_size=128, epochs=15, validation_data=(inTest,outTest))`

ERROR MESSAGE ////////////////////////////////////////////////////////////////////////////////////
**The error message:**

_"InvalidArgumentError:  indices[112,8] = -1 is not in [0, 32)
	 [[node sequential_43/embedding_20/embedding_lookup (defined at <ipython-input-208-c4c0034817e8>:1) ]] [Op:__inference_train_function_14324]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_43/embedding_20/embedding_lookup:
 sequential_43/embedding_20/embedding_lookup/14045 (defined at /usr/lib/python3.7/contextlib.py:112)

Function call stack:
train_function"_

/////////////////////////////////////////////////////////////////////////////////////////////////////////

CocaColaImput.csv has a shape of 14868 rows × 32 columns; CocaColaOutput.csv has 14868 rows × 1 columns.
Im working in the google colaboratory platform, using its standard libraries.

Do you know what i am doing wrong or how can i fix it?

**Comment by Saduf2019** [comment]
@JoseConi 
I ran the code shared and find missing dependencies, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a35feed050951e7a7d7ca4d0428340b1/untitled561.ipynb) , if possible share a colab gist with the error reported.

Meanwhile you may refer to similar issues :[link](https://stackoverflow.com/questions/51223936/tensorflow-invalidargumenterror-indices-while-training-with-keras),[link1](https://github.com/tensorflow/tensorflow/issues/23698).
