### ISSUE TITLE
M1 arm64 release binaries

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#47782]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.3 (20D91)
- TensorFlow installed from (source or binary): tf-nighly
- TensorFlow version: 
- Python version: 3.9.2

**Describe the problem**

`tf-nightly` fails to install on M1 arm64. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
~: where pip
/opt/homebrew/bin/pip
~: where python
/opt/homebrew/bin/python
~: pip --version
pip 21.0.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)
~: python --version
Python 3.9.2
~: file /opt/homebrew/bin/python
/opt/homebrew/bin/python: Mach-O 64-bit executable arm64
~: pip install tf-nightly
ERROR: Could not find a version that satisfies the requirement tf-nightly
ERROR: No matching distribution found for tf-nightly
```

**Comment by takipsizad** [comment]
proably trying to build from source will help

**Comment by mihaimaruseac** [comment]
The official pip packages that we build are for x86_64. For ARM, you have to build from source.

**Comment by mihaimaruseac** [comment]
We are not able to provide ARM binaries at the moment. The earliest would be next year after we get all the needed infrastructure and head count.

**Comment by calebmadrigal** [comment]
Is there any plans to officially release binary distributions for TensorFlow for ARM (Apple M1) on linux?
