### ISSUE TITLE
Inconsistency in tf.keras.models.Model.fit() doc

### ISSUE THREAD

**Issue by francescoalongi** [tensorflow/tensorflow#47780]
### URL(s) with the issue
https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit

### Description of the issue (what needs changing):
Related to the `validation_data` parameter, the doc clearly states the following:

> Note that validation_data does not support all the data types that are supported in x, eg, dict, generator or keras.utils.Sequence.

I don't get whether this was just an oversight or it was intended, since this method is working fine even when `validation_data` is a generator.

**Comment by ymodak** [comment]
The documentation for `model.fit` arguments are now updated with latest [tf-nightly api docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit). Thanks!
