### ISSUE TITLE
Accessing data for post-processing on the GPU without transfer to host

### ISSUE THREAD

**Issue by masaladose** [tensorflow/tensorflow#4779]
In TensorFlow's C++ API, after the session Run has been completed, is it possible to access the data while it's still on the GPU?
I would like to do post-processing on the GPU with the output of TensorFlow. 

Currently the output is sent back to the host and I will have to move it back to the GPU for post-processing. This data transfer is something that I am looking to avoid.

**Comment by tatatodd** [comment]
@zheng-xq probably has advice here (thanks XQ!)

**Comment by zheng-xq** [comment]
In general, all TensorFlow intermediate tensors disappear after a run, except: 

1. If you put it in a Variable, and mark it "trainable=False". I would recommend this for now. 
2. Push into a queue. However, the current queue implementation doesn't work with GPU yet. There are design discussion to change that. 
3. A semi-experimental feature called partial_run. Only touch this if you feel very brave. :) https://github.com/tensorflow/tensorflow/blob/2098b9abcf20d2c9694055bbfd6997bc00b73578/tensorflow/python/client/session_test.py#L1285

**Comment by yaroslavvb** [comment]
Also
  4. Persistent Tensors. If you execute `GetSessionHandle` op on a tensor, this data will persist after the session run call has terminated, until session is reset, or someone calls `DeleteSessionTensor`

**Comment by masaladose** [comment]
Thank you @zheng-xq  and @yaroslavvb for your suggestions.
I wanted to break it down a bit more to understand the steps better.
1. Create new tensors input and output (on host)
2. Load Graph 
3. Run session (on GPU)
4. Output tensor with the output is now on the host. This is presumably after it was copied from the GPU and has now been deleted on the GPU

If I chose to do either a "trainable=False" approach or use GetSessionHandle, is there a way I can get a pointer to the tensor or data that's still on the GPU? 
My objective is to pass the output tensor, which has a segmented image, to a CUDA kernel directly for post-processing.

**Comment by vincentvanhoucke** [comment]
Was there any resolution on this issue?

**Comment by yaroslavvb** [comment]
Every couple of months someone asks how to get a hold of GPU data initialized by TensorFlow, or give TensorFlow GPU data initialized by someone else, and I haven't seen any solution (latest q was https://github.com/tensorflow/tensorflow/issues/6955#issuecomment-273828989)

**Comment by yaroslavvb** [comment]
Latest official word is that it's not supported: https://github.com/tensorflow/tensorflow/issues/2210#event-706768999

**Comment by vincentvanhoucke** [comment]
Assigning to @aselle for visibility. Feel free to close if indeed that's the official word.

**Comment by byronyi** [comment]
Not sure if it's related, but how does the Unified Memory Access feature of CUDA play a role in this? It would be nice if we just return a memory slice to user, with a tag specifying it on device or main memory.

**Comment by yaroslavvb** [comment]
There's no UVM integration into TensorFlow, see https://github.com/tensorflow/tensorflow/issues/3678#issuecomment-238064949 for rationale

**Comment by VladislavAD** [comment]
Any update on this issue? I'm looking for a way to speed up inference moving pre and post processing of input and output of U-Net into GPU memory using OpenCV with CUDA build + Tensorflow C API. DtoH and HtoD memory operations eat all performance advantage of OpenCV CUDA image processing.
