### ISSUE TITLE
Inconsistent Embedding Layer functionality when initialized under MirroredStrategy()

### ISSUE THREAD

**Issue by UCRajkumar** [tensorflow/tensorflow#47791]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:  GeForce GTC 1080 Ti - 12 Gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
 
I'm passing in a tensor to an embedding layer. The tensor contains a value greater than the vocab size specified when initializing the embedding layer. This throws an error, as expected, when the layer is initialized outside the `tf.distribute.MirroredStrategy()`. In other words, if I create a model on a CPU machine or a single GPU machine, passing an invalid tensor throws an error. This is the correct behavior. 

However, if I pass in this tensor under the MirroredStrategy() then the error is no longer thrown and the model continues to train

**Describe the expected behavior**

The expected behavior is that an error should be thrown if an invalid tensor (i.e. a tensor with vocab size greater than the specified value to an embedding layer) is passed to an embedding layer regardless of the strategy used for data parallelism. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential, load_model, Model 

embed_dim = 64; maxlen = 152; vocab_size = 8
K.clear_session()
X_tk = np.random.randint(1, vocab_size, (10, 152))
X_mask_tk = np.random.randint(1, vocab_size + 1, (10, 152)) #The +1 is for the mask token
l = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
# print(l(X_tk)) #this works
# print(l(X_mask_tk)) #this doesn't work

model = keras.Sequential([layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)])
# print(model(X_tk)) #this works
# print(model(X_mask_tk)) #this doesn't works

model2 = keras.Sequential([layers.Input(shape=(maxlen,)), layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)])
model2.compile(optimizer='Adam', loss='sparse_categorical_crossentropy')
# model2.fit(X_mask_tk, X_tk) #This doesn't work

strategy = tf.distribute.MirroredStrategy()
with strategy.scope(): #im using 2 gpus but I reckon this issue would occur even with 1 gpu

    model3 = keras.Sequential([layers.Input(shape=(maxlen,)), layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)])
    model3.compile(optimizer='Adam', loss='sparse_categorical_crossentropy')
model3.fit(X_mask_tk, X_tk) #This works
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This should be the expected error when running `model3.fit(...)`:
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[3,21] = 8 is not in [0, 8)
	 [[node sequential_1/embedding_2/embedding_lookup (defined at <ipython-input-8-1c81a1dbdc4a>:25) ]]
	 [[sequential_1/embedding_2/embedding_lookup/_24]]
  (1) Invalid argument:  indices[3,21] = 8 is not in [0, 8)
	 [[node sequential_1/embedding_2/embedding_lookup (defined at <ipython-input-8-1c81a1dbdc4a>:25) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_25411]
```

**Comment by UCRajkumar** [comment]
@nikitamaia  any update here?

**Comment by nikitamaia** [comment]
Hi @UCRajkumar, I was able to reproduce the issue on a colab GPU runtime, so thank you for providing the reproducible code. No update for now, but will keep this thread updated if something changes.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/42f037e4b64cca0e9ad3fccec01a657c/untitled199.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi @UCRajkumar ,
I believe this issue has been resolved in recent versions. I tried running your code on Colab using TensorFlow v2.17.0, and I did not encounter any issues. Please find the [gist](https://colab.research.google.com/gist/Venkat6871/ff3c9346f5fb3af109d86715df449f4d/47791_tf-2-17-0-v.ipynb) here for your reference.
Thank you!
