### ISSUE TITLE
Length for attr 'output_shapes' of 0 must be at least minimum 1

### ISSUE THREAD

**Issue by redmlr** [tensorflow/tensorflow#47797]
I am trying to convert a list of lists of strings into a tf.data.Dataset object, but it throws this error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Length for attr 'output_shapes' of 0 must be at least minimum 1
	; NodeDef: {{node ParallelMapDatasetV2}}; Op<name=ParallelMapDatasetV2; signature=input_dataset:variant, other_arguments:, num_parallel_calls:int64 -> handle:variant; attr=f:func; attr=Targuments:list(type),min=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=use_inter_op_parallelism:bool,default=true; attr=deterministic:string,default="default"; attr=preserve_cardinality:bool,default=false> [Op:ParallelMapDatasetV2]
```
As you can see, I specified output_shapes and output_types, I even tried converting the list into a ragged tensor first but that also changed nothing. 
Here is my code:
```
    tf_train_ds = tf.data.Dataset.from_generator(
        lambda: train_list,
        output_types=(tf.string),
        output_shapes=(178728,)
        #output_shapes=(tf.TensorSpec(shape=(2,), dtype=tf.string), tf.TensorSpec(shape=(2,), dtype=tf.string))
        # output_signature=(
        #     tf.TensorSpec(shape=(2,), dtype=tf.string),
        #     tf.TensorSpec(shape=(2,), dtype=tf.string)
        # )
    )
```

I am stuck with this error for so so long...

**Comment by amahendrakar** [comment]
@redmlr,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by redmlr** [comment]
@amahendrakar 
TF Version: 2.4.0-rc0
Dataset:
I have a dataset from common voice (mozilla) containing filenames and corresponding labels. I've loaded the filenames into a python list, structured like this: `['common_voice_de_22136164.wav', common_voice_de_129376192.wav, ...]`

Code:
```
def get_waveform_and_label(file_path):

    # get label
    #label_ = get_label(file_path)
    # get the loaded lists
    train_list, _, _ = load_json_into_lists(TRAIN_DS_PATH, TEST_DS_PATH)

    for filename in train_list:
        if filename == str(file_path):
            return filename

    # get waveform
    #waveform_ = get_waveform(file_path)
    for filename in train_list:
        if filename == str(file_path):
            file_to_read = str("/de/cv_valid_data/" + filename)
            audio_binary = tf.io.read_file(file_to_read)
            waveform = decode_audio(audio_binary)

            return waveform


@tf.autograph.experimental.do_not_convert
def lists_to_tf_ds():
    
    train_list, validation_list, test_list = load_json_into_lists(TRAIN_DS_PATH, TEST_DS_PATH)

    filenames_train_list = tf.ragged.constant([sample[0] for sample in train_list])

    print("Example file tensor: ", filenames_train_list[0])

    AUTOTUNE = tf.data.AUTOTUNE

    files_ds = tf.data.Dataset.from_tensor_slices(filenames_train_list)

    waveform_ds = files_ds.map(get_waveform_and_label, num_parallel_calls=AUTOTUNE) 

    return waveform_ds

tf_waveform_ds = lists_to_tf_ds()
```

I tried to do something similar to this: 
https://www.tensorflow.org/tutorials/audio/simple_audio

**Comment by amahendrakar** [comment]
@redmlr,
On running the given code snippet, I am facing an error stating `NameError: name 'load_json_into_lists' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/73105eb918071d531804c2b0275d1f0b/47797.ipynb).

Could you please share a minimal code snippet so that we can reproduce the issue on our end? Alternatively, you can also run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by redmlr** [comment]
@amahendrakar,
So, just for testing reasons, I'd recommend to grab some (2-4) .wav audio clips and labels (can be just one sentence). You don't need the function the code is missing in your comment, try out my notebook: https://colab.research.google.com/drive/1hVm4fyty92G9YFfQ0TMjIKs0QOouZ8lb?usp=sharing
I never worked in colab before, but you have to do 3 things: 
1. Do what was in my first sentence; 
2. Upload your .wav files to colab; 
3. Read my comments; 
This should work:)

**Comment by amahendrakar** [comment]
@jvishnuvardhan,
I was able to reproduce the issue with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/fa9ed4f606a4ad1f6e0f454df4f0df8d/47797.ipynb#scrollTo=xGopHeBEuWLk) and TF-nightly. Whereas with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/761ea542250be22f05e03b3f95f59f1d/47797-2-3.ipynb), I am facing an error stating `AttributeError: module 'tensorflow._api.v2.data' has no attribute 'AUTOTUNE'`. 

Please check the linked gist for reference. Thanks!

**Comment by aaudiber** [comment]
@redmlr Sorry, this is a confusing error message that is trying to complain that the `Dataset.map` function `get_waveform_and_label` doesn't always return something. It should fix the issue if you put a `return ""` at the end

**Comment by redmlr** [comment]
@aaudiber Thank you for trying! In fact, I could fixed the error 1 day ago. It's so strange but the solution is the following:
`waveform_ds = files_ds.map(lambda file_path: tf.py_function(get_waveform_and_label, [file_path], [tf.float32, tf.string]), num_parallel_calls=AUTOTUNE) `

**Comment by aaudiber** [comment]
Ah, that should also fix the issue by avoiding tracing altogether. Thanks for sharing the fix! If dataset performance ever becomes an issue down the line, you may want to revisit the use of `py_function`, which could add overhead compared to executing a traced map function.
