### ISSUE TITLE
  programs that use this library are impossible to understand

### ISSUE THREAD

**Issue by TZubiri** [tensorflow/tensorflow#47793]
My cpu has a frequency of 3GHz, that is, electric current runs through it's circuitry 3 thousand million times per second, in something more than 2 seconds it cycle once for every person in the world, this of course is an ordinary modern computer, the small computers in our pockets have the same power. 25 years ago a computer with a thirtyedth of the power beat the strongest chess player in the world taking no more than a couple of minutes per move. With one second of that 1996 cpu I can find the first thousand prime numbers, I can figure out how much sleep I get on average, I can find out the geometry of an ozone atom.  

Now why in the world does a program take 10 hours to build? 3 million million cycles to compile a program? And this is just the beggining, tensorflow models will then be trained, so they will continue to squeeze out a cpu like it's a slave until something useful comes out of the other end. We are spending a small eternity to compile a compiler, which then will spend as many small eternities as money can buy to obtain a result, without care for the way it is accomplished.

Can we still consider this open source? Will someone be able to understand this code, and if they can, will they be able to understand the binaries, and if they manage to do that, will they ever understand the trained models.
The open source movement tries to understand the software that we build and use, but by turning the assembly line up to 11, this approach is effectively creating logic/code faster than we can analyze it. There's definitely applications for such code and human systems will cope, mainly by treating these programs as a black box and studying the systems they interface with instead, but I just wanted to expose that, altough open source, these machine learning libraries are blueprints to build a machine that generates opaque systems, which is kind of a paradox.

**Comment by AdityaKane2001** [comment]
@TZubiri 
Firstly, that's a lot of philosophy in one post. 😂 
What I think, is that seeing and understanding what's under the hood is  matter of experience. When one has complex systems like this library itself, one cannot expect to see and understand the code at the first glance. But if you give the time and energy, you will find yourself completely understanding the code and logic behind TensorFlow and ML in general. 
Not all people have the luxury to do what I just mentioned. They need results and they need them fast. We may be generating "opaque systems", as you preferred to put it, without knowing what the weights represent, but we do understand the logic they are created by. I think that's a good start for a field like ML, which has been mainstream for around for two or three decades, as opposed to something like mathematics and physics, which are around for centuries or millenniums.  
Finally, I'd like to say that the libraries that make and run ML are changing the world as we speak. And unfortunately, finding the geometry of ozone doesn't change the world, after all.

**Comment by TZubiri** [comment]
Thanks for the response Aditya. I'm afraid I was too cynical and critical yesterday without devoting enough effort to first understand the system. The truth is that I was simply frustrated by the 10 hour build time, but that problem is also present in the building of several mainstream technologies like android and linux as well, and it's mostly a byproduct of the C toolchain.

I find myself delving into this library because I have been contracted to build a prototype for a videovigilance startup, and a previous contractor tried to use tensorflow to solve some of the challenges. I'm facing the decision between following the path of the previous contractor, or lowering the expectations and using simpler technology. I apologize if this seems off topic, or not in line with what you expect at a github repo, but I do not expect or demand anything from the maintainers, at best I'm providing insight to maintainers into the preconceptions and the first experiences of a skeptical new developer might have with the library.

Feel free to ignore everything here.

That said,

@AdityaKane2001 Specific question, you mention that we may not understand the weighs, but that we may understand the logic by which they are created by. I agree that we may understand the code, and I'll try to do so. But regarding the weighs, do you think we have a chance to understand them? Are there any features built into tensorflow for analyzing the models or minimizing their size (thus making them easier to understand?). Something that I would like to do is to draw a correspondence between my own understanding of the subject at hand and that of my model. Taking a specifc case of my videovigilance prototype, can I inspect the model to find out if it's classifying people by skin colour? Adding another case to clarify, if I'm building a chess model, can I inspect the models to figure out whether the model knows what a [fork](https://en.wikipedia.org/wiki/Fork_(chess)) is? If the question depends on the specific models, let me know and I can post a repo with a working example.
Thank you Aditya.

Closing the issue to highlight that no response is really needed, but I appreciate having an open space to post my thoughts about my experience with the tech.

**Comment by TZubiri** [comment]
Actually scratch that, I don't think I'm going to be able to build this thing, let alone build something with it. (#4680)
