### ISSUE TITLE
Retracing happens when using eager execution for custom code

### ISSUE THREAD

**Issue by tsc2017** [tensorflow/tensorflow#47792]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab default
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  Colab default
- TensorFlow version (use command below): 2.4.1
- Python version: Colab default
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Colab default
- GPU model and memory: Tesla T4

**Describe the current behavior**
I use a `get_param()` function to wrap the `tf.Variable()`  function.  It returns the `Variable` on non-first call or creates it otherwise. There is a `network()` function that gets the network output and a `train_network()` function that runs a training step. Following [this example](https://www.tensorflow.org/guide/function#using_with_multiple_keras_optimizers) I created a Keras Adam optimizer for training  a network.

I found that tracing happens twice for `train_network()` and once for `network()`. I wonder whether it is a bug and whether this will negatively affect the efficiency of the code.

**Describe the expected behavior**
Tracing should happens only once for both `network()`  and `train_network()`

**Standalone code to reproduce the issue**
```
w=get_param('w0', np.random.normal(0,1,[10000,10000]))
@tf.function
def network(): # Define a network 
  print('Tracing network')
  w=get_param('w0')
  return tf.reduce_sum(w**2)

opt = tf.keras.optimizers.Adam(1)

@tf.function
def train_network():
 print('Tracing train_network')
 with tf.GradientTape() as tape:
    loss = network()
    w=get_param('w0')
 grad=tape.gradient(loss, [w])
 grad_and_var=zip(grad,[w])
 opt.apply_gradients(grad_and_var)
 return loss
```
```
for i in range(10):
  t0 = time.time()
  loss = train_network()
  iter_time = time.time() - t0
  print('iter %i:'%i, ' loss=%.2f,' % loss, 'iter_itme=%.4f s' % iter_time) 
```

For the complete program please refer to [this Colab Notebook](https://colab.research.google.com/drive/1RomHVK3fHPCJw8tSst4DERTBSEm9sf0t?usp=sharing)

**Comment by AdityaKane2001** [comment]
@tsc2017 
[This](https://stackoverflow.com/questions/57675242/how-does-tf-function-works-when-two-functions-call-each-other) may be helpful.
