### ISSUE TITLE
Extend tf.unsorted_segment_sum to allow 'rejecting' entries

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#478]
As already discussed in #466, it would be useful to be able to mark entries which are not to be summed anywhere by assigning negative indexes (or just -1) there. @girving suggested, that this behavior should only be enabled when setting a flag (e. g. `drop_negatives`) to preserve the existing error detection behavior, which I support.

**Comment by yongtang** [comment]
Added a PR #13055 for the fix.
