### ISSUE TITLE
Hello World Example not supported in Himax WE-1 board. 

### ISSUE THREAD

**Issue by SunBeenMoon** [tensorflow/tensorflow#47805]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Himax WE-1

Hi,

I'm curious why TFLM doesn't support the Hello World example of the Himax WE-1 board. Until January of this year, we have confirmed that TFLM supports the Hello World example of the Himax WE-1 board. I am curious about the reason for not applying at this time. (The Arduino IDE still supports the Hello World example.)

Thanks

**Comment by sushreebarsa** [comment]
@SunBeenMoon   This is a micro related issue , Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues) & move this issue to closed status.. Thanks!
