### ISSUE TITLE
Does anymore know how to install for tensorflow version 1.01 in google colabs 

### ISSUE THREAD

**Issue by jackson119** [tensorflow/tensorflow#47812]
I am currently doing one project  related to the CNN but my professor has told me to use tensorflow 1.01 version. However right now google Collab seems to be  not  support version 1.01 anymore.  Hence I would like to ask  is it  still possible to install tensorflow version 1.01 in google collabs. Thank you  I will really really appreciate your helps

**Comment by Saduf2019** [comment]
@jackson119 All you have to do in colab is ```'!pip install tensorflow==2.4```
You may refer to [link](https://colab.research.google.com/notebooks/tensorflow_version.ipynb), [link1](https://medium.com/@tuxnani/install-tensorflow-2-0-in-colab-36f778945a48),.
Please note tf 1.x version is not supported, please use 2.x, 2.4 is the stable version.

If this answers your query, move this issue to closed status.

**Comment by jackson119** [comment]
so no more tensorflow 1 in google colabs ? okay really appreciate your  helps

**Comment by Saduf2019** [comment]
@jackson119 
You can pip install tf 1.x, but there is no support fot it, you can use 2.x.
Is there any particular reason to use 1.x.
Please move this to closed status as you have reopened it.
