### ISSUE TITLE
UnboundLocalError: local variable 'kwargs' referenced before assignment

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#47819]
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.1
- CUDA/cuDNN version: 11.1
- GPU model and memory: RTX 3070

When I try load model from json with ``` model_from_json()``` from model with loss added by ```add_loss()``` and ```tf.add_n()```  method I get:

```
UnboundLocalError                         Traceback (most recent call last)

<ipython-input-1-ebe792783517> in <module>()
     36 json_file.close()
     37 
---> 38 loaded_model = model_from_json(loaded_model_json)  # UnboundLocalError: local variable 'kwargs' referenced before assignment
     39 print("model_from_json ok")

5 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/model_config.py in model_from_json(json_string, custom_objects)
    129   config = json.loads(json_string)
    130   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
--> 131   return deserialize(config, custom_objects=custom_objects)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    175       module_objects=LOCAL.ALL_OBJECTS,
    176       custom_objects=custom_objects,
--> 177       printable_module_name='layer')

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    356             custom_objects=dict(
    357                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 358                 list(custom_objects.items())))
    359       with CustomObjectScope(custom_objects):
    360         return cls.from_config(cls_config)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py in from_config(cls, config, custom_objects)
    667     """
    668     input_tensors, output_tensors, created_layers = reconstruct_from_config(
--> 669         config, custom_objects)
    670     model = cls(inputs=input_tensors, outputs=output_tensors,
    671                 name=config.get('name'))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py in reconstruct_from_config(config, custom_objects, created_layers)
   1283       if layer in unprocessed_nodes:
   1284         for node_data in unprocessed_nodes.pop(layer):
-> 1285           process_node(layer, node_data)
   1286 
   1287   input_tensors = []

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py in process_node(layer, node_data)
   1231         input_tensors = (
   1232             base_layer_utils.unnest_if_single_tensor(input_tensors))
-> 1233       output_tensors = layer(input_tensors, **kwargs)
   1234 
   1235       # Update node index map.

UnboundLocalError: local variable 'kwargs' referenced before assignment
```

**Comment by kiflowb777** [comment]
Code to replicate issue:
```python
import tensorflow as tf
import numpy as np

from tensorflow.keras.models import model_from_json
from tensorflow.keras import Input, Model, regularizers, layers

tf.compat.v1.disable_eager_execution()


inputs = Input(shape=(10,))
d = layers.Dense(10, kernel_initializer='ones')
x = d(inputs)
outputs = layers.Dense(1)(x)
model = Model(inputs, outputs)
  
model.add_loss(tf.reduce_mean(outputs))

reg_losses = [
    tf.cast(tf.size(input=w), tf.float32) for w in model.trainable_weights
    ]
model.add_loss(tf.add_n(reg_losses))

model.summary()

model.compile(optimizer="adam", loss=[None] * len(model.outputs))
model.fit(np.random.random((2, 10)))

model_json = model.to_json()
json_filename = "model.json"
with open(json_filename, "w") as json_file:
    json_file.write(model_json)
model.save_weights("model.h5")

json_file = open(json_filename, 'r')
loaded_model_json = json_file.read()
json_file.close()

loaded_model = model_from_json(loaded_model_json)  # UnboundLocalError: local variable 'kwargs' referenced before assignment
print("model_from_json ok")
```

**Comment by Saduf2019** [comment]
I am able to reproduce this issue on tf 2.3, 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8c0a1907110db7311a310579b73f4b78/untitled563.ipynb).
Thanks!

**Comment by rmothukuru** [comment]
@kiflowb777,
Can you please confirm if you are trying to Migrate the Code from `Tensorflow 1.x` to `2.x`? If not, can you try `decorating` your `Code` with `tf.function` instead of `tf.compat.v1.disable_eager_execution()` and check if the issue persists? Thanks!

**Comment by kiflowb777** [comment]
@rmothukuru 
Yes, I used a script for migration, training and solution work well, but the problem appears when loading the model from json.
My project is based on a **MaskRCNN** that requires the use of a ```tf.compat.v1.disable_eager_execution()```,  without it a training does not work. 
With ```tf.function``` MaskRCNN doesn't work.
https://github.com/matterport/Mask_RCNN

**Comment by kiflowb777** [comment]
I am still able to reproduce the error on TensorFlow 2.5.0

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210531,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5c1ea1cbc834a7329cc27f325eee2c51/untitled162.ipynb)..Thanks !

**Comment by ambarion** [comment]
Same problem on tf 2.8. Exactly from deserialize part. What is really Frustrating is that the tf.compat.v1.disable_eager_execution() have to be required when you want to get some gradient information on **Keras model.** Because **you do not** give the GradientTape support on keras. 

> @kiflowb777, Can you please confirm if you are trying to Migrate the Code from `Tensorflow 1.x` to `2.x`? If not, can you try `decorating` your `Code` with `tf.function` instead of `tf.compat.v1.disable_eager_execution()` and check if the issue persists? Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
