### ISSUE TITLE
Add Resnet-18 and Resnet-34 in tf.keras.applications.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/tensorflow#47818]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes, but would probably need help.

**Describe the feature and the current behavior/state.**
Currently there are multiple resnet variants available (50, 101, 152 + V2 options). 

Those model's are rather big and thus limiting the research and use of computer vision solutions on edge devices.

Adding requested models would make it easier to research and prototype new solutions in Tensorflow.

**Will this change the current api? How?**
It could be possible to use requested models in the same way as the `ResNet50` is called. An example could look like the following:
```python
resnet18 = tf.keras.applications.ResNet18(
    include_top=True, weights='imagenet', input_tensor=None,
    input_shape=None, pooling=None, classes=1000, **kwargs
)

resnet34 = tf.keras.applications.ResNet34(
    include_top=True, weights='imagenet', input_tensor=None,
    input_shape=None, pooling=None, classes=1000, **kwargs
)
```

**Who will benefit with this feature?**
Any user's who are working with smaller versions of computer vision models.

**Any Other info.**
This issue expands already existing request for Resnet-34:
https://github.com/tensorflow/tensorflow/issues/44099

**Comment by rmothukuru** [comment]
Raised a CL to fix this issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Sorry for the late response.

This is a duplicate. we can track the progress in keras-team/keras repo https://github.com/keras-team/keras/issues/15269

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!

I will close this issue here and please track this feature development in keras-team/keras repo. Thanks!
