### ISSUE TITLE
ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'   

### ISSUE THREAD

**Issue by Zakria96** [tensorflow/tensorflow#47827]
I am using faster_rcnn_inception_v2_coco model and want to convert it into tflite...   
import tensorflow as tf  

tflite_model_name="TF.lite"

saved_model_dir="exported_output_graph/saved_model/saved_model.pb"  
#Convert the model 
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir) # path to the SavedModel directory 
tflite_model = converter.convert()  
with open(tflite_model_name, 'wb') as f:   
f.write(tflite_model)   
I don't what I am missing here

### 1. System information

- OS Platform and Distribution =Linux 
- TensorFlow library =1.14

**Comment by abattery** [comment]
Could you try the conversion with the recent TF version? TF 1.14 is too old to be supported.

**Comment by Zakria96** [comment]
> Could you try the conversion with the recent TF version? TF 1.14 is too old to be supported.

I tried the newer version then got this error
KeyError: "The name 'prefix/FirstStageFeatureExtractor/Assert/Assert:0' refers to a Tensor which does not exist. The operation, 'prefix/FirstStageFeatureExtractor/Assert/Assert', exists but only has 0 outputs."

**Comment by abattery** [comment]
@Zakria96 It is really impossible to reproduce without having enough information. Could you create a gist or share your minimal steps to reproduce your problem at our side?

**Comment by Zakria96** [comment]
> @Zakria96 It is really impossible to debug your issue without having enough information. Could you create a gist or share your minimal steps to reproduce your problem at our side?

I am training my own object detection(rgb) model by using predefined faster_rcnn_inception_v2_coco... and I have successfully completed my training and created my frozen_inference_graph from the checkpoints..now I want to convert my model into TFlite.

To find the input , output array name and tensor shape  required  to convert .pb file into .tflite file using python script below.

import tensorflow as tf

def load_graph(frozen_graph_filename):
    with tf.io.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())

    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name="prefix")
    return graph


if __name__ == '__main__':
    graph = load_graph("frozen_inference_graph.pb")
    for op in graph.get_operations():
        abc = graph.get_tensor_by_name(op.name + ":0")
        print(abc)

KeyError: "The name 'prefix/FirstStageFeatureExtractor/Assert/Assert:0' refers to a Tensor which does not exist. The operation, 'prefix/FirstStageFeatureExtractor/Assert/Assert', exists but only has 0 outputs."

**Comment by abattery** [comment]
Is it possible to share your frozen graph file to us? Or can you create a colab to reproduce the issue easily?

**Comment by Zakria96** [comment]
> Is it possible to share your frozen graph file to us? Or can you create a colab to reproduce the issue easily?

yeah I can....How should I send it...

**Comment by abattery** [comment]
You can share the file through a google drive link or something else.

**Comment by Zakria96** [comment]
> You can share the file through a google drive link or something else.
You can find my frozen graph  here: 
https://drive.google.com/file/d/1jKYaZCnqqkfTR4JDZUSFFe8x485c8kz1/view?usp=sharing

**Comment by abattery** [comment]
Could you clarify the names of the input and output tensors of the given frozen graph?

Then you can convert your model with the following code snippet.

```
  converter = tf.compat.v1.lite.TFLiteConverter.frrom_frozen_graph(".../frozen_inference_graph.pb", ["input_tensor_name"], ["output_tensor_name"])
  converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
  ]
  model = converter.convert()
```

**Comment by Zakria96** [comment]
> Could you clarify the names of the input and output tensors of the given frozen graph?
> 
> Then you can convert your model with the following code snippet.
> 
> ```
>   converter = tf.compat.v1.lite.TFLiteConverter.frrom_frozen_graph(".../frozen_inference_graph.pb", ["input_tensor_name"], ["output_tensor_name"])
>   converter.target_spec.supported_ops = [
>     tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
>   ]
>   model = converter.convert()
> ```

I am not able to find the input and output tensors of my frozen_inference_graph.... Can you tell me how to find the input and output tensors of my model... and also show me an example of input and output tensor.... I tried a lot... I would be thankful..

**Comment by abattery** [comment]
They have input and output tensor names under https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/faster_rcnn_inception_v2_coco/faster_rcnn_inception_v2_coco.md.

I could successfully convert the above frozen graph def by using the following code snippet.

```
  converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("/tmp/fg.pb", ["image_tensor"], ["detection_classes", "detection_scores", "detection_boxes", "num_detections"])
  converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS
  ]
  model = converter.convert()
```
