### ISSUE TITLE
tf.decode_raw should support tf.float16

### ISSUE THREAD

**Issue by Shmuma** [tensorflow/tensorflow#4782]
Hi!

It should be trivial to add, I guess.

**Comment by WeiweiVivianWang** [comment]
Test2

**Comment by haosdent** [comment]
It looks add `Eigen::half` in `decode_raw_op.cc` should be enough?

```
diff --git a/tensorflow/core/kernels/decode_raw_op.cc b/tensorflow/core/kernels/decode_raw_op.cc
index d3bd991..280c2dc 100644
--- a/tensorflow/core/kernels/decode_raw_op.cc
+++ b/tensorflow/core/kernels/decode_raw_op.cc
@@ -93,6 +93,7 @@ class DecodeRawOp : public OpKernel {
       Name("DecodeRaw").Device(DEVICE_CPU).TypeConstraint<type>("out_type"), \
       DecodeRawOp<type>)

+REGISTER(Eigen::half);
 REGISTER(float);
 REGISTER(double);
 REGISTER(int32);
```

**Comment by benoitsteiner** [comment]
You also need to update the op registration code in tensorflow/core/ops/parsing_ops.cc to declare that is now supports outputing half floats.

**Comment by benoitsteiner** [comment]
Last but not least, I strongly encourage you to add a regression test to cover the float16 case in tensorflow/python/kernel_tests/decode_raw_op_test.py

**Comment by haosdent** [comment]
@benoitsteiner Many thanks! Let me try to fix it.
