### ISSUE TITLE
issue with multi objects detection (using ssd_resnet50_v1_fpn_640x640_coco17_tpu-8)

### ISSUE THREAD

**Issue by halhwadi** [tensorflow/tensorflow#47836]
**System information**

- Colab (GPU runtime)

**Describe the current behavior**
I'm trying to modified  this [notebook ](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb)to detect multi objects(2 objects) instead of one object, I have modified  the "gt_boxes_list" and "gt_classes_list" so both have (2,4) and (2,2) shapes respectively, however when I train the model I get the below error: 
*******
ValueError: in user code:

    <ipython-input-17-9f168971fcaf>:55 train_step_fn  *
        losses_dict = model.loss(prediction_dict, shapes)
    /usr/local/lib/python3.7/dist-packages/object_detection/meta_architectures/ssd_meta_arch.py:842 loss  *
        (batch_cls_targets, batch_cls_weights, batch_reg_targets,
    /usr/local/lib/python3.7/dist-packages/object_detection/meta_architectures/ssd_meta_arch.py:1083 _assign_targets  *
        groundtruth_weights_list)
    /usr/local/lib/python3.7/dist-packages/object_detection/core/target_assigner.py:512 batch_assign  *
        (cls_targets, cls_weights,
    /usr/local/lib/python3.7/dist-packages/object_detection/core/target_assigner.py:177 assign  *
        unmatched_shape_assert = shape_utils.assert_shape_equal(
    /usr/local/lib/python3.7/dist-packages/object_detection/utils/shape_utils.py:321 assert_shape_equal  *
        raise ValueError('Unequal shapes {}, {}'.format(shape_a, shape_b))

    ValueError: Unequal shapes [3], [2]
*****
[hint] I have checked "prediction_dict['class_predictions_with_background'] and its shape is (1, 51150, 2) instead of (1, 51150, **3**) as num_classes is 2 so prediction_dict['class_predictions_with_background'].shape[2] should be (num_classes + 1) as per the below quoted comment from "ssd_meta_arch.py" file:
"3) class_predictions_with_background: 3-D float tensor of shape
          [batch_size, num_anchors, num_classes+1] containing class predictions
          (logits) for each of the anchors.  Note that this tensor *includes*"

**Describe the expected behavior**
model should train and predict the 2 classes with their corresponding boxes

**Standalone code to reproduce the issue**
please find the link to the modified colab [notebook:](https://colab.research.google.com/drive/1l8e2LcPmnDAlf8r54ltC7kkTb70WbpyP?usp=sharing)

for training images, I used only 5 images (they are uploaded under this path:
'/content/models/research/object_detection/test_images/bike'
![bike_1](https://user-images.githubusercontent.com/72650269/111270399-3da6ac80-8649-11eb-9d7b-79b741159dc4.jpg)
![bike_2](https://user-images.githubusercontent.com/72650269/111270415-426b6080-8649-11eb-846a-fcf8af843220.jpg)
![bike_3](https://user-images.githubusercontent.com/72650269/111270436-49926e80-8649-11eb-839b-1425b7cb7fab.jpg)
![bike_4](https://user-images.githubusercontent.com/72650269/111270450-4e572280-8649-11eb-8bcd-60eb20be28be.jpg)
![bike_5](https://user-images.githubusercontent.com/72650269/111270468-54e59a00-8649-11eb-9c04-a62bd04a2291.jpg)

you need to change the pictures extension to "jpg" in image_path
```
train_image_dir = 'models/research/object_detection/test_images/bike/'
train_images_np = []
for i in range(1, 6):
  image_path = os.path.join(train_image_dir, 'bike_' + str(i) + '.jfif')
```

Best Regards

**Comment by Saduf2019** [comment]
@halhwadi 
Please provide access to the colab note book shared.

**Comment by halhwadi** [comment]
Sorry find the link to the`[ shared notebook](https://colab.research.google.com/drive/1l8e2LcPmnDAlf8r54ltC7kkTb70WbpyP?usp=sharing)`

**Comment by halhwadi** [comment]
> @halhwadi
> Please provide access to the colab note book shared.
