### ISSUE TITLE
error about Kernel8bitNeonDotprodOutOfOrder  occurs  when running int8 CPU inference by tflite

### ISSUE THREAD

**Issue by DanielMao2015** [tensorflow/tensorflow#47834]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: on mobile
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:  under-release yet, the platform is Qualcom SM4350
-   **TensorFlow installed from (source or binary)**: on mobile
-   **TensorFlow version (use command below)**: v2.0.0
-   **Python version**: on mobile
-   **Bazel version (if compiling from source)**: on mobile
-   **GCC/Compiler version (if compiling from source)**:  on mobile
-   **CUDA/cuDNN version**: on mobile
-   **GPU model and memory**: on mobile
-   **Exact command to reproduce**:tflite->Invoke

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
The problem  occurs when doing stress testing for camera of mobile phone. In detail, we do cpu inference for a int8 quantilized model and the problem occurs occasionally, causing the camera crash.

### Source code / logs
03-16 04:58:16.798467 28412 28412 F DEBUG   : backtrace:
03-16 04:58:16.798525 28412 28412 F DEBUG   :       #00 pc 00000000002247dc  /vendor/lib64/libtensorflowLite.so (ruy::Kernel8bitNeonDotprodOutOfOrder(ruy::KernelParams8bit<8, 8> const&)+1364)
03-16 04:58:16.798548 28412 28412 F DEBUG   :       #01 pc 0000000000114774  /vendor/lib64/libtensorflowLite.so (void ruy::RunKernelTyped<(ruy::Path)8, signed char, signed char, signed char, ruy::BasicSpec<int, signed char> >(ruy::Tuning, ruy::PackedMatrix<signed char> const&, ruy::PackedMatrix<signed char> const&, ruy::BasicSpec<int, signed char> const&, int, int, int, int, ruy::Matrix<signed char>*)+508)
03-16 04:58:16.798564 28412 28412 F DEBUG   :       #02 pc 0000000000113c74  /vendor/lib64/libtensorflowLite.so (void ruy::RunKernel<(ruy::Path)8, signed char, signed char, signed char, ruy::BasicSpec<int, signed char> >(ruy::Tuning, ruy::SidePair<ruy::PMatrix> const&, void*, ruy::SidePair<int> const&, ruy::SidePair<int> const&, ruy::DMatrix*)+160)
03-16 04:58:16.798573 28412 28412 F DEBUG   :       #03 pc 00000000002297b4  /vendor/lib64/libtensorflowLite.so
03-16 04:58:16.798583 28412 28412 F DEBUG   :       #04 pc 0000000000228dc4  /vendor/lib64/libtensorflowLite.so (ruy::TrMul(ruy::TrMulParams*, ruy::Context*)+2292)
03-16 04:58:16.798596 28412 28412 F DEBUG   :       #05 pc 00000000001131d0  /vendor/lib64/libtensorflowLite.so (void ruy::DispatchMul<(ruy::Path)15, signed char, signed char, signed char, ruy::BasicSpec<int, signed char> >(ruy::Matrix<signed char> const&, ruy::Matrix<signed char> const&, ruy::BasicSpec<int, signed char> const&, ruy::Context*, ruy::Matrix<signed char>*)+384)
03-16 04:58:16.798610 28412 28412 F DEBUG   :       #06 pc 0000000000112410  /vendor/lib64/libtensorflowLite.so (tflite::optimized_integer_ops::ConvPerChannel(tflite::ConvParams const&, int const*, int const*, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, int const*, tflite::RuntimeShape const&, signed char*, tflite::RuntimeShape const&, signed char*, tflite::CpuBackendContext*)+1164)
03-16 04:58:16.798622 28412 28412 F DEBUG   :       #07 pc 000000000011109c  /vendor/lib64/libtensorflowLite.so (void tflite::ops::builtin::conv::EvalQuantizedPerChannel<(tflite::ops::builtin::conv::KernelType)1>(TfLiteContext*, TfLiteNode*, TfLiteConvParams*, tflite::ops::builtin::conv::OpData*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*)+648)
03-16 04:58:16.798636 28412 28412 F DEBUG   :       #08 pc 0000000000105ed8  /vendor/lib64/libtensorflowLite.so (TfLiteStatus tflite::ops::builtin::conv::Eval<(tflite::ops::builtin::conv::KernelType)1>(TfLiteContext*, TfLiteNode*)+280)
03-16 04:58:16.798647 28412 28412 F DEBUG   :       #09 pc 000000000023079c  /vendor/lib64/libtensorflowLite.so (tflite::Subgraph::Invoke()+740)
03-16 04:58:16.798657 28412 28412 F DEBUG   :       #10 pc 00000000002342dc  /vendor/lib64/libtensorflowLite.so (tflite::Interpreter::Invoke()+32)

**Comment by abattery** [comment]
@DanielMao2015  Could you try your code with the recent TF version? TF 2.0.0 is too old to be supported.

**Comment by DanielMao2015** [comment]
@abattery As you said, I will test with the recent version, and will close the issue if no bug occurs
