### ISSUE TITLE
constants.SAVED_MODEL_FILENAME_PB)) OSError: SavedModel file does not exist at: /home/pi/Downloads/tf_lite_model.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by Tshi90** [tensorflow/tensorflow#47837]
I faced this problem when I wanted to import the pre-trained model to my rpi 3b+. I saw there are some similar issues but neither of them works for my case. Pls help me out!!

constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /home/pi/Downloads/tf_lite_model.h5/{saved_model.pbtxt|saved_model.pb}  

^ this is the error.

**Comment by Saduf2019** [comment]
@Tshi90 
please share simple stand alone code to replicate the issue reported or a colab gist.
