### ISSUE TITLE
Keras tuner - Missing validation split for model training

### ISSUE THREAD

**Issue by yiannisEfth** [tensorflow/tensorflow#47848]
URL with the issue:
https://www.tensorflow.org/tutorials/keras/keras_tuner#instantiate_the_tuner_and_perform_hypertuning

Description of issue (what needs changing):

On the second to last code cell where the hypermodel is re-instantiated and trained with the optimal number of epochs, a validation split parameter on the training set is not defined,as per best practises when fitting a model.

Is the link to the source code correct?

Yes

Are all parameters defined and formatted correctly?

Yes

Are return values defined?

Yes

Are you planning to also submit a pull request to fix the issue?

Yes, here: https://github.com/tensorflow/docs/pull/1844

**Comment by Saduf2019** [comment]
Thank you for the pr, the issue will be closed once the pr is merged.

**Comment by yiannisEfth** [comment]
Resolved through https://github.com/tensorflow/docs/pull/1844
