### ISSUE TITLE
Cannot compile with "-mavx"

### ISSUE THREAD

**Issue by larry-fuy** [tensorflow/tensorflow#4784]
I tried to compile tensorflow 0.10 with avx support. The command I used is 
```bazel build -c opt --copt=-mavx //tensorflow/tools/pip_package:build_pip_package```. 
However bazel output errors

```
...
ERROR: /home/oci/yfu/tensorflow_xeonphi/tensorflow/core/kernels/BUILD:1210:1: C++ compilation of rule '//tensorflow/core/kernels:batch_matmul_op' failed: gcc failed: error executing command /opt/rh/devtoolset-4/
root/usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/opt/rh/devtoolset-4/root/usr/bin -B/usr/bin -Wunused-but-set-parameter ... (remaining 105 argument(s) skip
ped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
...
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/GenericPacketMath.h:222:1: note:   template argument deduction/substitution failed:
In file included from external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:442:0,
                 from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/kernels/batch_matmul_op_impl.h:21,
                 from tensorflow/core/kernels/batch_matmul_op_real.cc:16:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/ProductEvaluators.h:648:24: note:   cannot convert '0' (type 'int') to type 'const type& {aka const Eigen::half&}'
     res = pset1<Packet>(0);
                        ^
```

The latest Eigen library seems to have explicit type conversion [here](https://github.com/RLovelett/eigen/blob/master/Eigen/src/Core/ProductEvaluators.h#L660)
I compiled tensorflow with gcc 5.2.1 on CentOS 7.
There is a related Stackoverflow [question](http://stackoverflow.com/questions/38493835/tensorflow-avx-support) but no response on why the compilation is failed.

**Comment by larry-fuy** [comment]
If this is related to #4775 please close it.

**Comment by sjlee7748** [comment]
@larry-fuy I think that your question isn's same with me.

Have you ever built tensorflow r0.11rc0.0 version with avx support?
When I built many tensorflow version(r0.9, r0.10rc0, r0.10, r0.11rc0.0), only tensorflow r0.10 had avx error. So, I suggest that you try to build other version.

In addition, If your machine is Intel Haswell, try to type '--copt=-mavx2' instead of '-copt=mavx'(before you build, please type 'bazel clean').

**Comment by larry-fuy** [comment]
@sjlee7748 Thanks for suggestions. Actually I compiled the source code from master branch and assume it should be the latest version of 0.11. Sorry forget mention this in my post. I'll try other versions on your suggestions. 
Currently I worked on a KNL machine and will try avx512 finally.
I'll close this issue and switch to see #4775.
