### ISSUE TITLE
Having trouble with merge conflicts? Use Merge Mamba for free, forever

### ISSUE THREAD

**Issue by henryjcee** [tensorflow/tensorflow#47843]
Shameless plug warning: I'm responsible for developing [Merge Mamba](https://mergemamba.com).

I've seen a few cases of people having to juggle their pull requests around each other and I really think for a big project like Tensorflow, Merge Mamba could be helpful for letting people know when they're working on code that conflicts with changes in other branches.

Merge Mamba is free forever for open source projects and right now I'm just trying to get as much feedback as possible, whether you love it or hate it. We're on [Github Marketplace](https://github.com/marketplace/merge-mamba) and if you are interested it's just a few clicks to get up and running.

Thanks and apologies for hijacking your issue pages,
H

**Comment by mihaimaruseac** [comment]
Please don't file spam issues
