### ISSUE TITLE
@amahendrakar, I did check this link (before raising the support request), some changes are made, but still, there are errors. I have attached the ipynb file. Please support.

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#47845]
@amahendrakar, I did check https://www.tensorflow.org/guide/migrate  (before raising the support request), some changes are made, but still, there are errors. I have attached the ipynb file. Please support.

_Originally posted by @rrklearn2020 in https://github.com/tensorflow/tensorflow/issues/47742#issuecomment-797540614_

**Comment by abattery** [comment]
Pleaae do not create a duplicated issue. It just makes an extra burden who triages the github issue.
