### ISSUE TITLE
After training the model , how I can save it? or from which folder I can download my trained model?

### ISSUE THREAD

**Issue by halhwadi** [tensorflow/tensorflow#47856]
hello

after training the model , how i can save it? or from which folder I can download my trained model?

I just have trained "ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz" and use object detections API's

my folder structure shown in below image:

![2021-03-17](https://user-images.githubusercontent.com/72650269/111440953-461de680-8720-11eb-87d7-940f27d963fc.png)

**Comment by Saduf2019** [comment]
@halhwadi 
You may use ```export_frozen_inference_graph.py```, ypu may refer to: [link](https://stackoverflow.com/questions/63524108/how-to-export-frozen-inference-graph-pb-from-a-checkpoint-in-tensorflow-objectde), [link1](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/save_and_load.ipynb).

Please confirm if you are using TF2 release of object detection API

**Comment by Saduf2019** [comment]
For tf2: models/research/object_detection/export_tflite_graph_tf2.py
example to refer to: [example](https://colab.research.google.com/gist/Saduf2019/db8b5cb091b59c5f45221c33de509863/example.ipynb)

Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!
