### ISSUE TITLE
training_a_model.md problem

### ISSUE THREAD

**Issue by goldkwang** [tensorflow/tensorflow#47854]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud Platform
- TensorFlow installed from (source or binary): 
- Tensorflow version (commit SHA if source): tensorflow-1.15
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32-CAM

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

I am working on custom object detection for use in Arduino board (ESP32-CAM) 
ESP32-CAM working stand alone (no wifi mode)
I am practicing github page.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/training_a_model.md

1.  PYTHONPATH problem
    ---------------------------------------------------------------------------------
    echo 'export PYTHONPATH=$PYTHONPATH:models/research/slim' >> ~/.bashrc
    source ~/.bashrc
    --- result ---------------------------------------------------------------------------------
      File "<ipython-input-30-ddee1c530575>", line 1
        export PYTHONPATH=$PYTHONPATH:models/research/slim >> ~/.bashrc
                        ^
    SyntaxError: invalid syntax

2. python: can't open file 'models/research/slim/datasets/build_visualwakewords_data.py': [Errno 2] No such file or directory
"build_visualwakewords_data.py" not exist in the datasets folder
-------------------------------------------------------------------------------------------
  ! python models/research/slim/datasets/build_visualwakewords_data.py
  --logtostderr \
  --train_image_dir=coco/raw-data/train2014 \
  --val_image_dir=coco/raw-data/val2014 \
  --train_annotations_file=coco/raw-data/annotations/instances_train2014.json \
  --val_annotations_file=coco/raw-data/annotations/instances_val2014.json \
  --output_dir=coco/processed \
  --small_object_area_threshold=0.005 \
  --foreground_class_of_interest='person'

3. build_visualwakewords_data.py file not exist in the datasets folder
 ! python models/research/slim/datasets/build_visualwakewords_data.py

**Comment by johanforslund** [comment]
You can use
```
!python models/research/slim/download_and_convert_data.py \
    --dataset_name=visualwakewords \
    --dataset_dir="${DATA_DIR}"
```
to both download and build the dataset.

**Comment by goldkwang** [comment]
thanks johanforslund

**Comment by rthadur** [comment]
The file has been and tflite micro is now moved to a new repo here https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/person_detection/training_a_model.md , I see the commands are updated too. Closing this issue. Thank you
