### ISSUE TITLE
tf.train.Server session_config parameter cannot be configured by Estimator

### ISSUE THREAD

**Issue by candyzone** [tensorflow/tensorflow#47852]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**

session_config=tf.ConfigProto(...)
run_config=tf.estimator.RunConfig(session_config=session_config)
estimator = tf.estimator.Estimator(model_fn=..., config=run_config)
tf.estimator.train_and_evaluator(estimator, train_spec, eval_spec)

ps/worker tf.Server is not configured by session_config

**Describe the expected behavior**

ps/worker tf.Server can be configured by Estimator

PR: https://github.com/tensorflow/estimator/pull/66

**Comment by Saduf2019** [comment]
@candyzone 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by candyzone** [comment]
> @candyzone
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

update

**Comment by Saduf2019** [comment]
@candyzone 
We see that you are using a very old version of tensor flow for which there is no support [for tf 1.x] any more, kindly upgrade to 2.x and let us know if you face any issues.

**Comment by candyzone** [comment]
@Saduf2019 
TF 2.0 move Estimator to tensorflow_estimator  as an addon. It also has this problew in TF 2.0
I make a PR in https://github.com/tensorflow/estimator/pull/66

**Comment by tilakrayal** [comment]
@candyzone ,
Respective PR was closed due to lack of activity.Can you please provide the required information to debug the issue and also please  update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!
