### ISSUE TITLE
Are you using old TFLite binary with newer model?Registration failed.

### ISSUE THREAD

**Issue by aliceruget** [tensorflow/tensorflow#47857]
### 1. System information

- OS Platform and Distribution 
NAME="Raspbian GNU/Linux"
VERSION_ID="10"

- TensorFlow installation with this code : 
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install python3-tflite-runtime

### 2. Code to reproduce
- Code

import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path_lite) # path to lite model

- Error raised
Traceback (most recent call last):
    interpreter = tflite.Interpreter(model_path=model_path_lite)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 207, in __init__
    custom_op_registerers_by_func))
ValueError: Op builtin_code out of range: 132. Are you using old TFLite binary with newer model?Registration failed.

### 5. Other infos
- Conversion of keras model to .tflite model
I converted the model from a keras model with this code :
converter = tf.lite.TFLiteConverter.from_saved_model(model_path_h5) # model to keras model
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
with open(model_path_lite, 'wb') as f:
   f.write(tflite_model)
   
To be able to convert, I had to use tf-nighlty  because the keras model contained Conv3DBackpropInputV2 operations. 

- Related issue
I don't manage to install tf-nighlty on the raspberry pi.

**Comment by abattery** [comment]
This is an intended behavior. The model should be executed with the same TF version or higher TF version. Please consider building your TensorFlow image through CMake or Bazel.
