### ISSUE TITLE
Android: TFLite GPU delegate has very little gain of performance over CPU

### ISSUE THREAD

**Issue by francku** [tensorflow/tensorflow#47859]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 33 Silverblue
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Xiaomi redmi note 5 pro (android 10)
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below): 2.4
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:qualcom 509

**Describe the current behavior**
I'm trying to use TFLite on a yolo v5 neural network exported using [this repo](https://github.com/zldrobit/yolov5/tree/tf-android-tfl-detect). 
What I do is export the pretrained coco model from .pt file to .tflite in FP16 using the tf.py from repo. Then I make 50 inferences on an image in the android app and I get the avarage of the times. I take single inference time using `getLastNativeInferenceDurationNanoseconds()` function.
I've made some test with CPU (4 thread and xnnpack) and GPU delegate both on FP16.  On GPU I set in `GpuDelegate.Options()`  the following two options
```
gpu_options.setPrecisionLossAllowed(true);
gpu_options.setInferencePreference(GpuDelegate.Options.INFERENCE_PREFERENCE_SUSTAINED_SPEED); 
```
What i've seen is that there's no much time gain using GPU over CPU.
On an immage 256x256 I've got
248.499 ms on CPU and 218.727 ms on GPU

With a bigger immage 800x640 the gain is a bit more but stil not a lot:
1671.821 ms on CPU and 1445.127 ms on GPU

(all times are the avarage time of 50 inferences)

**Describe the expected behavior**
What I expected was a greater improvement in time using GPU delegate. 

Is it normal or there's something I can do to improve GPU performance?

**Comment by abattery** [comment]
@srjoglekar246 could you take a look at this issue?

**Comment by srjoglekar246** [comment]
@francku How large are your inputs & outputs? For GPU, copying inputs to/from the GPU takes time if the output is large as well. And note that XNNPack + 4 Threads is already a pretty fast setup :-).

It might also be the case that your full model isn't running on GPU, do you see any INFO/ERROR logs in logcat?

Using GPU also helps power efficiency if you perform inference frequently, something that isn't easily captured in existing benchmarks.

**Comment by francku** [comment]
> How large are your inputs & outputs? For GPU, copying inputs to/from the GPU takes time if the output is large as well. And note that XNNPack + 4 Threads is already a pretty fast setup :-).

Hi! thanks for answering. 
Input and output depends on the image passed as input and they can be big. The input is a buffer of dimension `1 * INPUT_SIZE_W * INPUT_SIZE_H * 3 * numBytesPerChannel` where numBytesPerChannel is 4 in FP model. Output is even bigger, is a buffer of dimension `output_box * (numClass + 5) * numBytesPerChannel` with output_box equals to 
`((((inputSize_w / 32) * (inputSize_h / 32)) + ((inputSize_w / 16)* (inputSize_h/16)) + ((inputSize_w / 8)* (inputSize_h / 8))) * 3)`
So this could be what is slowing me down?
I've manged to try on a powerful phone a Huaweii P20 pro and CPU results are simililar to the old one but on GPU the results are better: on a 800x640 model I've got 256.892145 ms. Is there a way to know how much of this difference depends on copying data to/from GPU and how much depends on the computation power of the two GPUs? I take times using `getLastNativeInferenceDurationNanoseconds()` does this include both copying and computation?

> It might also be the case that your full model isn't running on GPU, do you see any INFO/ERROR logs in logcat?

I don't have any error on logcat but I tried the banchmark app on TFLite website to check if everything work on GPU and I've got these results
`Explicitly applied GPU delegate, and the model graph will be completely executed by the delegate.`
and then

```
Profiling Info for Benchmark Initialization:
============================== Run Order ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	 ModifyGraphWithDelegate	            0.000	 4635.158	 4635.158	 99.996%	 99.996%	242484.000	        1	ModifyGraphWithDelegate/0
	         AllocateTensors	         4635.093	    0.179	    0.091	  0.004%	100.000%	     0.000	        2	AllocateTensors/0

============================== Top by Computation Time ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	 ModifyGraphWithDelegate	            0.000	 4635.158	 4635.158	 99.996%	 99.996%	242484.000	        1	ModifyGraphWithDelegate/0
	         AllocateTensors	         4635.093	    0.179	    0.091	  0.004%	100.000%	     0.000	        2	AllocateTensors/0

Number of nodes executed: 2
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	 ModifyGraphWithDelegate	        1	  4635.158	    99.996%	    99.996%	242484.000	        1
	         AllocateTensors	        1	     0.183	     0.004%	   100.000%	     0.000	        2

Timings (microseconds): count=1 curr=4635341
Memory (bytes): count=0
2 nodes observed



Operator-wise Profiling Info for Regular Benchmark Runs:
============================== Run Order ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	     TfLiteGpuDelegateV2	            0.038	  367.988	  367.645	100.000%	100.000%	     0.000	        1	[Identity]:347

============================== Top by Computation Time ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	     TfLiteGpuDelegateV2	            0.038	  367.988	  367.645	100.000%	100.000%	     0.000	        1	[Identity]:347

Number of nodes executed: 1
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     TfLiteGpuDelegateV2	        1	   367.644	   100.000%	   100.000%	     0.000	        1
```
So I guess this mean that everything work on GPU, am I right?

> Using GPU also helps power efficiency if you perform inference frequently, something that isn't easily captured in existing benchmarks.

Thanks this is something I'll keep in mind on my future considerations, I thought that GPU and CPU had the same power efficiency since they need the same time of computation. 
A drawback that I've noticed on GPU is that It took a bit more to allocate the delegate. In particular when I use
`gpu_options.setInferencePreference(GpuDelegate.Options.INFERENCE_PREFERENCE_SUSTAINED_SPEED); `
on big images (800x640 for instance) it could take a couple of minutes to initialize and in the meantime the phone is really laggy and even unlocking the screen becomes a nightmare. Is a normal behaviuor for this option?

And just a last question is it normal that the same model is usable for a GPU delegate but when I try to use NNAPI I've got this error `java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: ModifyGraphWithDelegate is disallowed when graph is immutable.` ?  On benchamrk results seems that GPU use ModifyGraphWithDelegate but on NNAPI it says that graph is immutable.

Thanks

**Comment by srjoglekar246** [comment]
@francku Your latency benchmarking method seems right to me. From the output, it looks like everything works on GPU. It will certainly be faster on newer phones, since the GPUs are better.

There is no way currently to measure how much time is spent copying data to/from the delegate, we can look into it. Thoughts, @multiverse-tf ?

> A drawback that I've noticed on GPU is that It took a bit more to allocate the delegate. Is a normal behaviuor for this option?

Currently, yes. We are planning improvements in this area, for delegates to reduce initialization time.
