### ISSUE TITLE
Cannot limit GPU memory with MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by gatagat** [tensorflow/tensorflow#47861]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: pypi
- TensorFlow version: v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: Python 3.8.5
- CUDA/cuDNN version: 11.1/8.0.5
- GPU model and memory: RTX2080Ti

**Describe the current behavior**

When running trainings with `OneDeviceStrategy` or `MirroredStrategy` on a single machine, it is possible to set a limit on the used GPU memory:
```python
limit_mb = ...
gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_virtual_device_configuration(
            gpu,
            [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=limit_mb)])
strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.NcclAllReduce())
...
with strategy.scope():
   ...
   model.fit(...)
```
However running a distributed training with `MultiWorkerMirroredStrategy` on multiple machines does not work as both the `set_virtual_device_configuration` and `MultiWorkerMirroredStrategy` must run before anything else.

The code is the same with the strategy created as follows:

```python
    cluster_resolver = tf.distribute.cluster_resolver.SlurmClusterResolver(
        jobs=None, port_base=8888, gpus_per_node=None, gpus_per_task=None,
        tasks_per_node=None, auto_set_gpu=True, rpc_layer='grpc'
    )
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy(
        communication=tf.distribute.experimental.CollectiveCommunication.NCCL,
        cluster_resolver=cluster_resolver
    )
```

Calling `set_virtual_device_configuration` before creating the `MultiWorkerMirroredStrategy` (as for the other strategies) leads to:
```
File "venv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 340, in new_func
  return func(*args, **kwargs)
File "venv/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 253, in __init__
  super(_CollectiveAllReduceStrategyExperimental,
File "venv/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 185, in __init__
  CollectiveAllReduceExtended(
File "venv/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 327, in __init__
  self._initialize_strategy(self._cluster_resolver)
File "venv/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 335, in _initialize_strategy
  self._initialize_multi_worker(cluster_resolver)
File "venv/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 434, in _initialize_multi_worker
  context.context().configure_collective_ops(
File "venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 729, in configure_collective_ops
  raise RuntimeError("Collective ops must be configured at program startup")
```

Calling `MultiWorkerMirroredStrategy` before `set_virtual_device_configuration` leads to:
```
File "venv/lib/python3.8/site-packages/tensorflow/python/framework/config.py", line 748, in set_logical_device_configuration
  context.context().set_logical_device_configuration(device, logical_devices)
File "venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 1490, in set_logical_device_configuration
  raise RuntimeError(
RuntimeError: Virtual devices cannot be modified after being initialized
```

**Describe the expected behavior**

It is possible to limit the GPU memory for `MultiWorkerMirroredStrategy` as for the other strategies.

If this is expected to not work by design, it would be useful to have it clearly stated in the docs.

**Comment by amahendrakar** [comment]
@gatagat,

> ```
> gpus = tf.config.list_physical_devices('GPU')
> if gpus:
>   try:
>     # Currently, memory growth needs to be the same across GPUs
>     for gpu in gpus:
>       tf.config.experimental.set_memory_growth(gpu, True)
>     logical_gpus = tf.config.experimental.list_logical_devices('GPU')
>     print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
>   except RuntimeError as e:
>     # Memory growth must be set before GPUs have been initialized
>     print(e)
> ```
> 

Could you please take a look at [this](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) alternate method to limit GPU memory and check if it helps. Thanks!

**Comment by gatagat** [comment]
Thanks for the proposition, I am aware of that option and also that one can set it using the envvar TF_FORCE_GPU_ALLOW_GROWTH=yes, however, that does not limit the memory.

**Comment by crccw** [comment]
Logical devices configuration should go before creating the strategy. Is there any other code before creating the strategy?
