### ISSUE TITLE
OOM errors running multiprocessing inference

### ISSUE THREAD

**Issue by mdable2** [tensorflow/tensorflow#47863]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.65
- GPU model and memory: NVIDIA GTX 1070 8 GB

**Describe the current behavior**
I have a set of images that I need to run an inference on. What I am trying to do is spawn 4 workers and each worker has 1/4 access to GPU's memory. I am getting OOM even if I restrict the memory to 1/8 per worker. Below is some of the code:

```
def process_image(doc_paths):
    model = models.Model(my_model)
    for path in doc_paths:
        ...do some work...
        model.do_predict()
        return 0 or 1


if __name__ == "__main__":
    num_processes = 4
    process_pool_executer = concurrent.futures.ProcessPoolExecutor(num_processes)

    # Split documents into `num_processes` equal parts, so in our case -> 4 equal parts
    for i, paths in enumerate(sub_file_paths):
        print(f'==== Processing path {i} ====')
        f = process_pool_executer.submit(process_image, paths)
        futures.append(f)

        for future in concurrent.futures.as_completed(futures):
            r = future.result()
            results.append(r)
```

Within the `do_predict()` function, I import tensorflow and have tried both these memory allocation options:

```
# OPTION 1
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_virtual_device_configuration(gpus[0], [
            tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
    except RuntimeError as e:
        print(e)


# OPTION 2
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
```

Both give me OOM errors. According to nvidia-smi my GPU has 8081 MiB free so allocating 1024 MB for each process should be fine. So I must be doing something or thinking of something in the wrong way. Any thoughts?

**Describe the expected behavior**
Expected behavior would be that I could run the above without OOM errors.

**EDIT:**
When running this script with one worker it works fine. And looking in task manager, my GPU usage does not get above 10%.

**EDIT2:**
I am actually using TF version 2.2 - not 2.3.

**Comment by Saduf2019** [comment]
@mdable2 
Would you want to [limit your gpu](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and try, also try on upgraded tf as in 2.4 the stable version and see if it helps.

**Comment by Saduf2019** [comment]
@mdable2 
Can you please check if the other two methods work and let us know.
