### ISSUE TITLE
Confine Tensorflow v2.3.2 C API to use only one thread.

### ISSUE THREAD

**Issue by suraj-maniyar** [tensorflow/tensorflow#47870]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Linux CentOS 8.3.2011
- TensorFlow installed from: source (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md)
- TensorFlow version: Tensorflow C API v2.3.2 (v2.3.2-0-g9edbe5075f7)
- Python version: 3.6.8
- Bazel version (if compiling from source): 3.7.1
- GCC/Compiler version (if compiling from source): 8.3.1
- CUDA/cuDNN version: N/A
- GPU model and memory: No GPU, 16 GB RAM

**Describe the current behavior**
Tensorflow C API generates multiple threads during inference, with at least one thread on each available CPU.

**Describe the expected behavior**
There should be one and only one thread created regardless of hardware setup (E.g. number of CPUs, number of cores etc.)

**Standalone code to reproduce the issue**
N/A

I am interested in what source code would change in order to make TensorFlow C API use only 1 thread.

Some related issues : 
- https://github.com/tensorflow/tensorflow/issues/43671
- https://github.com/tensorflow/tensorflow/issues/42510
- https://github.com/usnistgov/frvt/issues/12

Other issues on Github deal with TensorFlow 1.x API, but I am specifically interested in TensorFlow v2.3.2 C API.

**Comment by bplevin36** [comment]
I'm not an expert, but it looks like environment variables are the easiest way https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/core/common_runtime/process_util.cc#L99

**Comment by suraj-maniyar** [comment]
@bplevin36 Can you elaborate on what exactly will change in that file before building TensorFlow?

**Comment by bplevin36** [comment]
You don't even have to rebuild Tensorflow.  It reads the environment variables at run time.  Just set `TF_NUM_INTEROP_THREADS=1` and `TF_NUM_INTRAOP_THREADS=1` before running your program.
