### ISSUE TITLE
Unnecessary Device to Host copies

### ISSUE THREAD

**Issue by kushanam** [tensorflow/tensorflow#47871]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- Bazel version (if compiling from source):3.0.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1
- GPU model and memory:8.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

There are issues regarding unnecessary DtoH copies. When The tensor is originated on the device using any (GPU-friendly) dataset subclass or any other type of pipeline (one particular example is CuPy and DLPack), there are unnecessary DtoH copies happening. As a more explicit example when CuPy and keras are used DLPack invokes unexpected DtoH copies, which makes DLPack meaningless

**Describe the expected behavior**

Should eliminate the unnecessary DtoH and HtoD copies.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

`
!pip install cupy-cuda111
import os
print(os.getpid())
import cupy as cp
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model

n = 10000000

a = Input(shape=(n))
output = Lambda(lambda x: x ** 2)(a)
model = Model(a, output)

x = cp.arange(n, dtype=cp.float32).reshape(1, n)
dltensor = x.toDlpack()
x2 = tf.experimental.dlpack.from_dlpack(dltensor)

cp.cuda.nvtx.RangePush('model.predict')
y = model.predict(x2)
cp.cuda.nvtx.RangePop()
print('done')
`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@kushanam 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3c469caabcf199cf34cd9e79db4a62c7/untitled563.ipynb).

**Comment by kushanam** [comment]
> @kushanam
> I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3c469caabcf199cf34cd9e79db4a62c7/untitled563.ipynb).

I can't see the gist unfortunately due to API rate limit. I will try again, but wonder if you could share the error?

**Comment by kushanam** [comment]
> @kushanam
> I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3c469caabcf199cf34cd9e79db4a62c7/untitled563.ipynb).

Sorry, was able to run and fixed the example.

**Comment by Saduf2019** [comment]
Glad to hear that, please move the issue to closed status as resolved.

**Comment by kushanam** [comment]
@Saduf2019 , The issue is not resolved, What I fixed is not the issue, but the given example witch used threw an error.

**Comment by Saduf2019** [comment]
@kushanam 
I ran the updated code and face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/71784a638349f3e8c2eb5f427f9393a8/untitled566.ipynb), can you please share a colab gist with the error reported.

**Comment by kushanam** [comment]
> @kushanam
> I ran the updated code and face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/71784a638349f3e8c2eb5f427f9393a8/untitled566.ipynb), can you please share a colab gist with the error reported.

Seems like the Cuda version of the colab you are running on is 11.0:
!cat /usr/local/cuda/version.txt
CUDA Version 11.0.228

for that, please install cupy 11 rather:
`!pip install cupy-cuda110`

**Comment by ymodak** [comment]
@VoVAllen  Can you please take a look at this issue/ tag its owner? Thanks!

**Comment by VoVAllen** [comment]
@ymodak I'm not tensorflow people. I believe it should be someone who owns Keras data processing part.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
