### ISSUE TITLE
tensorflow 2.4.1 incompatibility with numpy 1.20.1

### ISSUE THREAD

**Issue by ststeinberg** [tensorflow/tensorflow#47878]
Hi, 

pip install reports that tensorflow 2.4.1 is incompatible with numpy 1.20.1 as it requires numpy 1.19.x

Is there any workaround for this right now or are there plans to upgrade requirements to numpy 1.20.x?

Thanks in advance!

**Comment by bhack** [comment]
Not for 2.4.x. For nightly or future releases please subscribe to https://github.com/tensorflow/tensorflow/issues/47691

**Comment by Saduf2019** [comment]
@ststeinberg 

 As mentioned [here](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/tools/pip_package/setup.py#L84), there is a bound on numpy versions supported by TF2.4 ( ~=1.19.2). Currently numpy version should be >=1.19.2 and < 1.20.

As you mentioned in the other issue, downgrading numpy 2.x to the versions mentioned above will work without any issues. 
Please move this to closed status as resolved.
Thanks!

**Comment by ststeinberg** [comment]
Closing this ticket and waiting for a solution of #47691.
