### ISSUE TITLE
Nvidia RTX 3090 is slower than Nvidia GTX 1080Ti for single image prediction

### ISSUE THREAD

**Issue by r06922090** [tensorflow/tensorflow#47875]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1 (2.2.5 for Keras version)
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2/8.1.0
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I tried five CNN models (ResNet50, ResNet101, ResNet152, DenseNet121, and MobileNet) to measure their inference time with  batch size one. The CNN models running on 3090 GPU is slower than running on 1080Ti GPU, and both of the devices are slow in eager execution.
| | 3090 GPU (enable eager model) | 3090 GPU (disable eager model) | 1080Ti GPU (enable eager model) | 1080Ti GPU (disable eager model) |
| :---: | :---: | :---: | :---: | :---: |
| ResNet50 | 39.643 ms | 23.588 ms | 25.103 ms | 11.846 ms |
| ResNet101  | 51.097 ms | 36.063 ms | 29.640 ms | 17.598 ms |
| ResNet152  | 50.035 ms | 48.3 ms | 34.169 ms | 22.586 ms |
| DenseNet121  | 52.822 ms | 43.287 ms | 29.565 ms | 18.306 ms | 
| MobileNet  | 28.205 ms | 10.332 ms | 21.362 ms | 4.294 ms | 

**Describe the expected behavior**
3090 GPU is faster than 1080Ti GPU.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

import tensorflow
import numpy
import time
import cv2
 
tensorflow.compat.v1.disable_eager_execution()
keras_resnet50 = tensorflow.keras.applications.resnet50.ResNet50()
image = numpy.asarray(cv2.resize(cv2.imread('cat.png'), (224, 224)))
data = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
keras_resnet50.predict(data)
t = time.time()
keras_resnet50.predict(data)
print((time.time() - t) * 1e6)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Test image: https://raw.githubusercontent.com/dmlc/mxnet.js/main/data/cat.png

**Comment by DolanDack** [comment]
I have the exact same problem. Just replaced my 1080ti with a 3090 and TF 2.4 is very slow (CUDA 11.0)

**Comment by Saptr** [comment]
Same problem. 
I had tested all gpu that i had ,and a lot of combinations.
CUDA : 11.0,11.1,11.2
tensorflow == 2.4.1,tf-nightly-gpu==2.5.0.dev20210320 or 2.5.0.dev20210320
GPU device : rtx3080,3090 ,2080s,2080ti,1080ti

Best performane always on rtx2080ti, and 3080/3090 worst, but the rtx20 series have stopped production.
Rtx30 series extremely slow (training or prediction,1.3~2times)
Big trouble on my product.

Now i see tf-nightly-gpu==2.6.0.dev released, i hope it can be better.

**Comment by woonkij** [comment]
> Same problem.
> I had tested all gpu that i had ,and a lot of combinations.
> CUDA : 11.0,11.1,11.2
> tensorflow == 2.4.1,tf-nightly-gpu==2.5.0.dev20210320 or 2.5.0.dev20210320
> GPU device : rtx3080,3090 ,2080s,2080ti,1080ti
> 
> Best performane always on rtx2080ti, and 3080/3090 worst, but the rtx20 series have stopped production.
> Rtx30 series extremely slow (training or prediction,1.3~2times)
> Big trouble on my product.
> 
> Now i see tf-nightly-gpu==2.6.0.dev released, i hope it can be better.

did it resolve your issue? I am going through similar problems now.

**Comment by memr5** [comment]
> Same problem.
> I had tested all gpu that i had ,and a lot of combinations.
> CUDA : 11.0,11.1,11.2
> tensorflow == 2.4.1,tf-nightly-gpu==2.5.0.dev20210320 or 2.5.0.dev20210320
> GPU device : rtx3080,3090 ,2080s,2080ti,1080ti
> 
> Best performane always on rtx2080ti, and 3080/3090 worst, but the rtx20 series have stopped production.
> Rtx30 series extremely slow (training or prediction,1.3~2times)
> Big trouble on my product.
> 
> Now i see tf-nightly-gpu==2.6.0.dev released, i hope it can be better.

Hey @woonkij,
I have similar issue when using Nvidia RTX 3080. I am seeing high inference time & high GPU Memory usage as compared to 2080Ti.

A single low size model is occupying more gpu memory in 3080 than it is occupying in 2080ti.

Did you had any memory issues like this?

_PS_: I tried using [NGC Containers](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) but still having the similar issue.
