### ISSUE TITLE
Multi input/output model works correctly in TF 1.15; produces error in TF 2.4.1

### ISSUE THREAD

**Issue by evancollins1** [tensorflow/tensorflow#47872]
- TensorFlow version: 2.4.1
- Python version: 3.8.3

**Describe the current behavior** 
Coded a multi input/output model
model.fit fails with the following error:

ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {"<class 'numpy.ndarray'>"}), (<class 'list'> containing values of types {'(<class \'list\'> containing values of types {"<class \'float\'>"})'})

**Describe the expected behavior**
Code runs properly as expected in TF 1.15 (with Python 3.6). 

**Standalone code to reproduce the issue**
% Runs properly in TF 1.15
model.fit([x1, x2], y.T.tolist(), 
                  batch_size=8,
                  epochs=50, verbose=1, shuffle=True,
                  callbacks=[earlystop])

% where type(x1) is numpy.ndarray
% where x1.shape is (7869, 1, 68)
% where type(x2) is numpy.ndarray
% where x2.shape is (7869, 500)
% where type(y.T.tolist()) is list
% where len(y) is 3
% where type(y) is numpy.ndarray
% where y.shape is (7869, 3)

**Addendum**

Note: I referred to [#42175](https://github.com/tensorflow/tensorflow/issues/42175) and ensured x1, x2, and y are np.array. 

model.fit([np.asarray(x1), np.asarray(x2)], y, 
                  batch_size=8,
                  epochs=50, verbose=1, shuffle=True,
                  callbacks=[earlystop])

This produced this error:
TypeError: 'NoneType' object is not callable

**Comment by amahendrakar** [comment]
@evancollins1,
In order to expedite the trouble-shooting process, could you please provide the complete code you'd run on TensorFlow v1.15 and v2.4? Thanks!

**Comment by evancollins1** [comment]
# Here is full code to reproduce problem:

import numpy as np
import pickle
import pandas as pd

import tensorflow.keras as keras

import tensorflow.keras.backend as K
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Dense, Masking, LSTM, TimeDistributed, \
                         Bidirectional, Flatten, \
                         Embedding, Dropout, Flatten, BatchNormalization, \
                         RNN, concatenate, Activation
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.preprocessing import sequence
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
import random as rn
import tensorflow as tf
from tensorflow.keras.optimizers import RMSprop



# where type(vad) is numpy.ndarray
# where vad.shape is (10039, 3)
# where type(x1) is numpy.ndarray
# where x1.shape is (7869, 1, 68)
# where type(x2) is numpy.ndarray
# where x2.shape is (7869, 500)
# where type(y.T.tolist()) is list
# where len(y) is 3
# where type(y) is numpy.ndarray
# where y.shape is (7869, 3)

vad = np.random.rand(10039, 3)
x1 = np.random.rand(7869, 1, 68)
x2 = np.random.rand(7869, 500)
y = np.random.rand(7869, 3)



# CCC-based loss function
def ccc(gold, pred):
    gold       = K.squeeze(gold, axis=-1)
    pred       = K.squeeze(pred, axis=-1)
    gold_mean  = K.mean(gold, axis=-1, keepdims=True)
    pred_mean  = K.mean(pred, axis=-1, keepdims=True)
    covariance = (gold-gold_mean)*(pred-pred_mean)
    gold_var   = K.mean(K.square(gold-gold_mean), axis=-1, keepdims=True)
    pred_var   = K.mean(K.square(pred-pred_mean), axis=-1, keepdims=True)
    ccc        = K.constant(2.) * covariance / (gold_var + pred_var + K.square(gold_mean - pred_mean) + K.common.epsilon())
    return ccc



def ccc_loss(gold, pred):  
    # input (num_batches, seq_len, 1)
    ccc_loss   = K.constant(1.) - ccc(gold, pred)
    return ccc_loss


# API model
def model(alpha, beta, gamma):
    # speech network
    speech_input = Input(shape=(x1.shape[1], x1.shape[2]), name='speech_input')
    speech_net = BatchNormalization()(speech_input)
    speech_net = LSTM(256, return_sequences=True)(speech_net)
    speech_net = LSTM(256, return_sequences=True)(speech_net)
    speech_net = LSTM(256, return_sequences=True)(speech_net)
    speech_net = Flatten()(speech_net)
    speech_model = Dropout(0.3)(speech_net)
    #text network
    text_input = Input(shape=(500, ))
    text_input = Embedding(3438,
                    300,
                    weights = [np.random.rand(3438, 300)],
                    trainable = True)(text_input)
    text_input = LSTM(256, return_sequences=True)(text_input)
    text_input = LSTM(256, return_sequences=True)(text_input)
    text_input = LSTM(256, return_sequences=False)(text_input)
    text_input = Dense(64)(text_input)
    text_model = Dropout(0.3)(text_input)
    # combined model
    combined_model = concatenate([speech_model, text_model])
    combined_model = Dense(64, activation='relu')(combined_model)
    combined_model = Dense(32, activation='relu')(combined_model)
    combined_model = Dropout(0.4)(combined_model)
    target_names = ('v', 'a', 'd')
    combined_model = [Dense(1, name=name)(combined_model) for name in target_names]

    model = Model([speech_input, text_input], combined_model) 
    model.compile(loss=ccc_loss,
                  loss_weights={'v': alpha, 'a': beta, 'd': gamma},
                  optimizer='RMSprop', metrics=[ccc])
    return model
    
model = model(1, 1, 1)
model.summary



earlystop = EarlyStopping(monitor='val_loss', mode='min', patience=10,
                          restore_best_weights=True)

# Error produced in the code below
model.fit([x1, x2], 
                  y.T.tolist(), batch_size=8, validation_split=0.2,
                  epochs=50, verbose=1, shuffle=True,
                  callbacks=[earlystop])

**Comment by amahendrakar** [comment]
@evancollins1,
On running the code with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/e01a745291ced3ef687d60341655aa42/47872.ipynb#scrollTo=NdYdsfw8mIJe) and [TF v1.15](https://colab.research.google.com/gist/amahendrakar/3e768eaa20fca8c13c2aa7e1991ef5f2/47872-1-15.ipynb), I am facing the same error stating 
```
ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 500), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'") at layer "embedding_1". The following previous layers were accessed without issue: []
```

Please check the linked gist for reference. Thanks!

**Comment by evancollins1** [comment]
Hi @amahendrakar, attached below is a link to the functional code to reproduce the issue. Thanks!

https://colab.research.google.com/drive/1PP9UM4KAiN4K6pKxNyOjYlHf0m49Z9Mx?usp=sharing

**Comment by amahendrakar** [comment]
@evancollins1,
Looking at similar issue [#35651](https://github.com/tensorflow/tensorflow/issues/35651#issuecomment-582434097), I was able to resolve the `ValueError: Failed to find data adapter that can handle input`. But now, the code throws a different error. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/bdf382f9913c55a8a8ce75ba0fa2f648/47872.ipynb). Thanks!

**Comment by evancollins1** [comment]
@amahendrakar Thank you. Making the y input for model.fit an array seemed to solve for the model.fit issue. However, now this is introducing an issue with the loss function. Any tips to resolve the dimensions? I defined the axis=-1 for the Squeeze function, but it produces the error referenced in the gist.
