### ISSUE TITLE
 module 'tensorflow.keras.layers' has no attribute 'MulitiHeadAttention'

### ISSUE THREAD

**Issue by lpc806835212** [tensorflow/tensorflow#47877]
When i use the newest version2.4.1 when i use 

head_attention1 = tf.keras.layers.MulitiHeadAttention(num_heads = 1,key_dim=1)(conv1)

it will has a AttributeError : module 'tensorflow.keras.layers' has no attribute 'MulitiHeadAttention'

**Comment by lintian06** [comment]
I think you had a typo for [tf.keras.layers.MultiHeadAttention](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MultiHeadAttention).

It shouldn't be an issue.

**Comment by lintian06** [comment]
I'll close this bug. Please reopen it if you still cannot find it in 2.4.1.
