### ISSUE TITLE
Unable to install Tensorflow due to one of the file named "getObjectTorrentRequest.h" file , Torrent named file are blocked in various system across organisations.

### ISSUE THREAD

**Issue by vishalyadav93** [tensorflow/tensorflow#47883]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform: Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:latest
- Python version:3.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Unable to install Tensorflow due to one of the file named "getObjectTorrentRequest.h" file , "Torrent" named file are blocked in systems across various organisations.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/42913143/111647376-6f299e80-8828-11eb-9426-e5c7f8fca466.png)

**Comment by amahendrakar** [comment]
@vishalyadav93,
In this case, could you please download the `.whl` file compatible with your machine form [this link](https://pypi.org/project/tensorflow/2.4.1/#files) and then install it.

Thanks!

**Comment by vishalyadav93** [comment]
didn't help, even if we try from wheel file, it will somehow put the "getTorrentRequest.h" file in my system which is getting blocked due to its name.

**Comment by amahendrakar** [comment]
@vishalyadav93,
I did not find any matches for the keyword `torrent` in the TensorFlow source code. Looks like the `getObjectTorrentRequest.h` file is part of the AWS SDK.

In this case, could you please get in touch with the administrator of your machine to get the url / file whitelisted. Thanks!
