### ISSUE TITLE
I hope that the tfjs-models project will increase the configuration resource link method

### ISSUE THREAD

**Issue by yulong88888** [tensorflow/tensorflow#47885]
Hi guys, I used tfjs-models project on my vue project for the first time today, and I also successfully launched posenet and handpose. Thank you for your contribution, but due to some special reasons, I cannot open tfhub.dev Just like google.com, I found that tfhub.dev will redirect to storage.googleapis.com, I can access storage.googleapis.com normally, and there is no problem running posenet, but handpose will fail to load mode, so I hope it can Provide a url method to configure the model, easy to replace https://github.com/tensorflow/tfjs-models/blob/master/handpose/src/index.ts 28 lines 38 lines 48 lines links.

My English is not very good, this is machine translation, thank you again for your contribution

**Comment by Saduf2019** [comment]
@yulong88888 
This i not the Tfjs repo,please move this issue to closed status and open it in the correct repo.

**Comment by yulong88888** [comment]
@Saduf2019 Sorry, I can't find the issue option in https://github.com/tensorflow/tfjs-models, can you help me

**Comment by yulong88888** [comment]
I completed the requirement by code overwriting
