### ISSUE TITLE
Rename tf.keras.optimizers to tf.keras.optims for more aesthetic import statements

### ISSUE THREAD

**Issue by Ryan-Rudes** [tensorflow/tensorflow#47889]
TensorFlow imports are often tedious, and i think it would be nice if some of the most common imports from `tensorflow.keras` aligned better with one another. For this reason, I propose that `tf.keras.optimizers` be renamed to `tf.keras.optims`.

```python
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.losses import *
from tensorflow.keras.optims import *
```

rather than

```python
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.losses import *
from tensorflow.keras.optimizers import *
```

**Comment by rmothukuru** [comment]
@Ryan-Rudes,
Using **`Optimizers`**  in the `Import` statements make code readable than **`optims`**. Can you please elaborate your request and also specify some potential disadvantages of the current notation? Thanks!

**Comment by Ryan-Rudes** [comment]
It is disadvantageous to write out “optimizers” because it is tedious, and considering 3 other highly substantial `tensorflow.keras` modules (`models`, `layers`, and `losses`) are all comprised of 6 letters, it would provide better alignment to abbreviate optimizers to optims (also 6 characters). PyTorch uses `torch.optim` presumably for it is shorter and honestly does not impact readability very much at all. `tf.compat` (compatibility) and `tf.config` (configuration) are similar in that they are modules that are written as 6-character abbreviations written in a similar manner, so the argument that `tf.keras.optims` would impact readability contradicts the fact that TensorFlow already uses `tf.compat` to denote the compatibility module.

**Comment by tomerk** [comment]
Hi @Ryan-Rudes, changing top-level api naming tends to be a very involved, risky, general super controversial topic in any widely-used library and can cause serious backwards compatibility issues. We definitely can't rename `optimizers` to `optims` without undertaking serious risk and causing a backwards compatibility headache for existing users. At most we could add an alias of `keras.optims` in addition to `keras.optimizers`.

But, given how past discussions around potential aliases went (e.g. aliasing tf.keras.optimizers/tf.keras.layers under tf.optimizers/tf.layers), I'm inclined to say these 4 characters (`izer`) aren't worth the complexity, potential risk, or organizational work that would be required to get consensus on something like this.

Good development tooling should be able to autocomplete the rest of `optimizers` for you regardless, so it would purely be a minor aesthetic change at best.
