### ISSUE TITLE
Return gradient 0 in mixed_precison setting

### ISSUE THREAD

**Issue by WingsOfPanda** [tensorflow/tensorflow#47884]
**System information**

OS Platform and Distribution: linux
TensorFlow version (use command below): tf2.4.1

**Reproducing code**

```

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
import numpy as np
from tqdm import tqdm

gpus = tf.config.experimental.list_physical_devices('GPU')

for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)


mixed_precision.set_global_policy('mixed_float16')


def forward_conv(x, filters, kernels, name='forward', padding='same'):
    i = 0
    for flt, kernel in zip(filters, kernels):
        x = layers.Conv3D(flt, kernel, activation='relu', padding=padding, dilation_rate=(1, 1, 1),
                          use_bias=False, name=str(i) + '_' + name)(x)
        x = layers.BatchNormalization(name=str(i) + '_bn_' + name)(x)
        i += 1
    return x


def part_one(ipt):
    l1 = forward_conv(ipt, (4, 4), (3, 3), name='enc1')
    d2 = layers.MaxPool3D(pool_size=(2, 2, 2))(l1)
    l2 = forward_conv(d2, (4, 4), (3, 3), name='enc2')
    return l1, l2


def part_inner(ipt1, ipt2):
    l1 = forward_conv(ipt1, (4, 4), (3, 3), name='enc1')
    l2 = forward_conv(ipt2, (4, 4), (3, 3), name='enc2')
    return l1, l2


def part_two(ipt1, ipt2):
    l2 = forward_conv(ipt2, (4, 4), (3, 3), name='dec2')
    u1 = layers.UpSampling3D(size=(2, 2, 2))(l2)
    r1 = forward_conv(ipt1 + u1, (4, 4), (3, 3), name='dec1')
    return r1


initial = tf.ones([1, 256, 368, 368, 1], dtype=tf.float16)

tf.random.set_seed(1)

with tf.GradientTape() as g:
    g.watch(initial)
    l1_, l2_ = part_one(initial)
    for _ in range(2):
        l1_, l2_ = part_inner(l1_, l2_)
    opt_ = part_two(l1_, l2_)
    loss = tf.reduce_mean(l1_) + tf.reduce_mean(opt_)
    gd = g.gradient(loss, initial)
    print('-' * 100)
    print(f'loss is {loss} and grad is {np.sum(gd)} with ckpt= {ckpt}')
```

**Behavior description**

When using tf.float32 setting, the result of gradient is reasonable with value around 0.6, however, when shift to tf.float16 with mixed_precision, the gradient is constantly 0. Should we expect that the computed gradient is so different between normal float32 mode and mixed_precision float16 mode? Thank you!

**Comment by 004307ec** [comment]
I have met the same issue with TF 2.4.1.  It prevents the use of newer features of new hardware.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF nightly-2.6.0.dev20210603 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/72eb0f52a364ea5b3d8dfe33bf64323f/untitled214.ipynb)..Thanks !

**Comment by jvishnuvardhan** [comment]
@WingsOfPanda I ran your code and face OOM error. Can you please check and reduce size to run the code successfully? Thanks!

**Comment by WingsOfPanda** [comment]
@jvishnuvardhan oh sure, u may reduce the initial size

`initial = tf.ones([1, 256, 368, 368, 1], dtype=tf.float16)`

to 

`initial = tf.ones([1, 64, 128, 128, 1], dtype=tf.float16)`

in my code. or even smaller if you need

**Comment by WingsOfPanda** [comment]
btw, I checked with the latest build tf2.5, the result is the same

**Comment by WingsOfPanda** [comment]
@jvishnuvardhan Hi. Any update? Have you able to run my code after reduce the input size? Thank you!

**Comment by jvishnuvardhan** [comment]
@WingsOfPanda Now it is throwing the following error. Can you try installing the version mentioned in the error trace below and then verify whether the issue was resolved or not.

`NotFoundError: No algorithm worked! Please try upgrading to cuDNN 8.0.5. You are using cuDNN 8.0.4, which has a bug causing this error. [Op:Conv3DBackpropFilterV2]
`

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/aa7d422653ad4b3580c0c5911c33ea13/untitled214.ipynb). Thanks!

**Comment by WingsOfPanda** [comment]
@jvishnuvardhan hmm, I think I have the correct cuDNN version. on my side I didn't see this error. One more thing, I tried tf2.6 but still facing this problem. Any further suggestions?
