### ISSUE TITLE
Tensorflow lite micro 2.4 Alpha version missing tflite::ops::micro::Register_FULLY_CONNECTED()

### ISSUE THREAD

**Issue by Nhiem** [tensorflow/tensorflow#47888]
**System information**
- Arduino Nano BLE 33 SENSE 
- Arudino Pro IDE Alpha 0.1.4 macos 

**Provide the text output from tflite_convert**

```
#tensorflow lite micro missing Register_FULLY_CONNECTED() layer in version 2.4 alpha when upload the Arduino IDE recommend with "Register_UNPACK();" but somehow it still fixing the issue during upload the problem is solved when i return back to TFlite micro version 2.1 !!!
is there any replacement layer here ????? '

please helps thank you so much for who answer this question 
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by ymodak** [comment]
Apologies for the delay in response? 
I don't see TF 2.4 alpha distribution available, Can you please test with latest version of TF 2.4.1 or TF 2.5.0rc1? Thanks

**Comment by Nhiem** [comment]
Yes Thank you for your response The problem is solved!!
