### ISSUE TITLE
Extracting tf.Variable() in numpy or tensor format for further processing from a ListWrapper()

### ISSUE THREAD

**Issue by kreouzisv** [tensorflow/tensorflow#47881]
Hello there,

I have a simple question, that I don't seem to find any documentation on regarding it. I am using costume code, and during one of my training loops a ListWrapper Object is created containing some tensor variable.

Initially when using tf.print() I was able to see the numerical contents of the tensor but not assign to a variable for further processing. 

After using tf.compat.v1.flags.tf_decorator.unwrap(x), where x is the initial ListWrapper, I am indeed able to see the tensor in tf.Variable format like that : 

<bound method ListWrapper.append of ListWrapper([<tf.Variable 'Variable:0' shape=(10, 10) dtype=float32, numpy=                                                                                                                array([[ 0.05768297,  0.        ,  0.        ,  0.        ,  0.        ,                                                                                                                                                                0.        ,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.00587903,  0.01599882,  0.        ,  0.        ,  0.        ,                                                                                                                                                                0.        ,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.0069333 ,  0.00599516,  0.05650787,  0.        ,  0.        ,                                                                                                                                                                0.        ,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.00601203,  0.0059952 , -0.0027298 ,  0.05753344,  0.        ,                                                                                                                                                                0.        ,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [ 0.00507043, -0.00599517, -0.00196748,  0.00593348,  0.03158937,                                                                                                                                                                0.        ,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.00458831,  0.00599515,  0.00015493, -0.00596476, -0.00691961,                                                                                                                                                                0.03968148,  0.        ,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.00672386,  0.00599529,  0.00553486, -0.00642598,  0.00682343,                                                                                                                                                               -0.00884094,  0.05674272,  0.        ,  0.        ,  0.        ],                                                                                                                                                             [-0.00481304,  0.00599513,  0.00011724, -0.00551202, -0.0070322 ,                                                                                                                                                                0.00368161, -0.00388715,  0.05674548,  0.        ,  0.        ],                                                                                                                                                             [-0.00566915,  0.00599517, -0.00349799, -0.00581874, -0.00713581,                                                                                                                                                               -0.0043654 , -0.00537512, -0.00558803,  0.05750472,  0.        ],                                                                                                                                                             [-0.00441868,  0.00599512,  0.00767725, -0.00547412, -0.00668069,                                                                                                                                                                0.00388396, -0.00506157, -0.00536125, -0.00621854,  0.05662818]],                                                                                                                                                           dtype=float32)>])>   

I am not able to subscript or use attributes to recover the variable and store it in numpy format, which would be the easier way for me to recover it in my training loop. 

Any suggesting are highly appreciated.

**Comment by Saduf2019** [comment]
@kreouzisv 
Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!

**Comment by kreouzisv** [comment]
I asked in the documentation tab, wasn't a bug or feature request. I figured that you should document how to manipulate the tensorflow object : ListWrapper(). 

Anyways, I was able to extract the numerical values of the list wrapper and store it using:

with tf.init_scope():
       store_array = x

where x is the Listwrapper object.

Thanks anyway

**Comment by Saduf2019** [comment]
@kreouzisv 
Please move this issue to closed status if resolved.
