### ISSUE TITLE
Segmentation Fault when Benchmarking TFLite EfficientNetB0 

### ISSUE THREAD

**Issue by yann-pourcenoux** [tensorflow/tensorflow#47886]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.02/Android 10
- Mobile devices: Xiaomi Redmi Note 7 & Huawei P30
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8

**Describe the current behavior**
When running the TFLite benchmark of a converted `EfficientNetB0` model on a mobile phone, I get a `Segmentation fault` error. I would be interested in any ideas of what could be causing this, if it is coming from the `.tflite` file or when running the benchmark. I am quite lost and have no idea where to look. Thanks in advance!

**Describe the expected behavior**
Get the profiling of the model.

**Standalone code to reproduce the issue**
I am generating the `tflite` file with the following script:
```
import tensorflow as tf
import tensorflow_datasets as tfds

# Create model
model = tf.keras.applications.EfficientNetB0(include_top=False)


# Create MNIST dataset
ds = tfds.load(
    name="coco/2017",
    split="train",
    data_dir="/data/datasets/tensorflow_datasets/",
)
ds = ds.map(lambda obj: tf.image.resize(obj["image"], (224, 224)))

# Transform the dataset into a representative dataset as in the TF guide
def representative_data_gen():
    for input_value in ds.batch(1).take(100):
        # Model has only one input so each data point has one element.
        yield [input_value]


# Converter
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Set the representative dataset in order to quantize the activations
converter.representative_dataset = representative_data_gen

# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]

# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# Additional tricks
converter.experimental_new_converter = True
converter.experimental_new_quantizer = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
]

tf_lite_quant_model = converter.convert()

# saving converted model in TFLite file
with open("EfficientNetB0.tflite", "wb") as tf_file:
    tf_file.write(tf_lite_quant_model)

print("Converted")
```
I use the TFLite benchmarking tool that can be downloaded [here](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_arm_benchmark_model)

I am running the benchmark with the successive commands : 
```
adb push android_arm_benchmark_model /data/local/tmp/benchmark
adb shell chmod +x /data/local/tmp/benchmark
adb push EfficientNetB0.tflite /data/local/tmp/model.tflite
adb shell /data/local/tmp/benchmark --graph=/data/local/tmp/model.tflite --use_gpu=false
adb shell rm -f /data/local/tmp/benchmark
adb shell rm -f /data/local/tmp/model.tflite
```

**Comment by abattery** [comment]
@yann-pourcenoux could you provide the converted model if the model is sharable? And could you also provide what kind of error message you see from the execution of the benchmark tool?

**Comment by yann-pourcenoux** [comment]
Yes, of course, the model is the following [EfficientNetB0.zip](https://github.com/tensorflow/tensorflow/files/6167299/EfficientNetB0.zip) and has been generated with the script above.
The full log when running the benchmark above is :
```
STARTING!
Log parameter values verbosely: [0]
Graph: [/data/local/tmp/model.tflite]
Use gpu: [0]
Loaded model /data/local/tmp/model.tflite
INFO: Initialized TensorFlow Lite runtime.
The input model file size (MB): 5.1575
Initialized session in 3.188ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
Segmentation fault 
```

**Comment by freedomtan** [comment]
@yann-pourcenoux if you inspect your model with tools such as [`netron`](https://github.com/lutzroeder/netron), you can see that your model have 1x1x1x3 input, which looks weird. Forutunately, the model you converted has dynamic-size tensors, so you can try something like

```
benchmark_model --graph=EfficientNetB0.tflite --input_layer=input  --input_layer_shape=1,224,224,3
```

**Comment by yann-pourcenoux** [comment]
By specifying `--input_layer_shape` or by creating the model with a fixed input shape I could fix the `segmentation fault` problem. But now I added a custom layer and I get a 
``` 
ERROR: tensorflow/lite/kernels/strided_slice.cc:156 op_context.input->type != op_context.output->type (3 != 1)
ERROR: Node number 476 (STRIDED_SLICE) failed to prepare.
```
The node where the error happens can be seen on this [image](https://user-images.githubusercontent.com/43449205/111805496-5d500600-88d1-11eb-840b-e393e7542e3f.png).
Do you have any idea what could be causing this problem?  I didn't find a relevant answer online. 
The full model is attached [here](https://github.com/tensorflow/tensorflow/files/6172459/model-EB0-full-fixed.zip).

**Comment by yann-pourcenoux** [comment]
To avoid that problem I changed the slicing operations with `tf.unstack()` and got rid of that error.
