### ISSUE TITLE
Latest Windows 10 update - Import tensorflow - Kernel dies

### ISSUE THREAD

**Issue by MaudDestree** [tensorflow/tensorflow#47890]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 19042.867
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): binary (conda)
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.1 (anaconda / spyder 4.1.4)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.2 / cuDNN 8.1.0.77
- GPU model and memory: Nvidia Quadro M620

**Describe the current behavior**
Since the last Windows 10 upgrade, it is impossible to import tensorflow. The kernel dies and restarts.
Non TF python code runs fine

**Describe the expected behavior**
Import tensorflow as usual :)

**Standalone code to reproduce the issue**
`import tensorflow as tf`

2021-03-18 17:10:01.890125: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

Kernel died, restarting

 
2021-03-18 17:10:01.890125: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
[SpyderKernelApp] WARNING | No such comm: 12ee0da4880411ebac01b6d88ae4f6b5

**Comment by amahendrakar** [comment]
@MaudDestree,
Could you please install TensorFlow outside the conda environment and check if you are facing the same issue. Thanks!

**Comment by MaudDestree** [comment]
Hello,
Do you mean I need to re-install a complete env including python etc ?
Do you have any hint to do that while keeping my Anaconda env ?
Btw, using another Anaconda env working with TF 1.14, I don't face the same issue (still I need TF2)
Thank you

**Comment by amahendrakar** [comment]
@MaudDestree,
Please follow [this guide](https://www.tensorflow.org/install/pip#1.-install-the-python-development-environment-on-your-system) to create a new virtual environment and install TensorFlow in it. Thanks!

**Comment by MaudDestree** [comment]
@amahendrakar 
I have re-installed everything (without Anaconda) and now it is running fine. 
Thank you
