### ISSUE TITLE
using ragged tensors with custom loss and metric 

### ISSUE THREAD

**Issue by inespancorbo** [tensorflow/tensorflow#47895]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): TF 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11/10
- GPU model and memory: NVIDIA Quadro P2000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

TF 2.4.1

**Describe the current behavior**

Please see below link to my code. I am working with ragged tensors. My data is (N, length, features) where length is variable. I do not understand how each epoch takes around 6000 seconds to complete. Is it because of the @tf.autograph.experimental.do_not_convert decorator? Is it because of ragged tensors? Is it because of something else. I have implemented the same but padding each data observation to maximum length (therefore, did not need the custom loss and metric I implemented) and an epoch runs for 200 seconds.

**Describe the expected behavior**

Understand why using ragged tensors takes so long vs padding to max length.

Understand 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

My issue is not reproducible because I am working with ragged tensors and had to manually change some of the .py files that come with tensorflow. See issue https://github.com/tensorflow/tensorflow/pull/45015 from @pedro-r-marques and many others referencing ragged tensors. If whoever reviews this can manually make the changes then my code should work. 

Anyways here is my code so it helps -- also the data is fictitious. I am dealing with roughly 10 GB of data but the format is the same. A list of 2d lists with unequal sequence length (same feature length).

https://colab.research.google.com/drive/1bXmCKuABlGwjoeTxwk-mBfKA_z7BXWYA?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I had to add the decorator @tf.autograph.experimental.do_not_convert on essentially all functions as otherwise I would get an WARNING as such:

```
WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x000001A3835F4040> and will run it as-is.
Cause: could not parse the source code of <function <lambda> at 0x000001A3835F4040>: no matching AST found
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

**Comment by funmathgt** [comment]
Hopefully, someone can confirm this but looking into recurrent_v2.py in the call method of the LSTM class it is unfortunately running everything by default on CPU .... Can someone please confirm if one cannot use ragged tensors with GPU when using LSTM layers?

**Comment by amahendrakar** [comment]
@funmathgt,
On opening the linked Colab notebook, I am facing the below error
![image](https://user-images.githubusercontent.com/57165142/112520444-6ead7c80-8dc1-11eb-82bf-c33d13ba5210.png)

Could you please provide the required permissions to view the notebook? Thanks!
