### ISSUE TITLE
WARNING:tensorflow:AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7f817468a4c0>> and will run it as-is

### ISSUE THREAD

**Issue by coert** [tensorflow/tensorflow#47898]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker image nvidia/cuda:10.2-devel-ubuntu18.04 (running Kebernetes on GCP)
- TensorFlow installed from (source or binary): 2.4.0
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: Python 3.8.0
- CUDA/cuDNN version: cuda:10.2
- GPU model and memory:  NVIDIA Tesla T4 16 GB GDDR6

Came across this message while debugging a problem in our processing pipeline, with the request to file a bug report with export AUTOGRAPH_VERBOSITY=10
...
TypeError: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
Error transforming entity <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7f817468a4c0>>
WARNING:tensorflow:AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7f817468a4c0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method Socket.send of <zmq.sugar.socket.Socket object at 0x7f817468a4c0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module, class, method, function, traceback, frame, or code object was expected, got cython_function_or_method
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
...

Full output is rather large:
https://pastebin.com/raw/G9jA8fXm

**Comment by Saduf2019** [comment]
@coert 
Please share simple stand aloe code such that we can replicate the issue reported or if possible share a colab gist.
 Mean while please refer to existing issues with same error: [link](https://github.com/tensorflow/tensorflow/issues/46177#issuecomment-799619015), #37144, [link1](https://stackoverflow.com/questions/61551592/tensorflow-fails-to-create-autograph-out-a-working-piece-of-code)
