### ISSUE TITLE
ASL Gesture Recognition SSD Model not showing labels upon running

### ISSUE THREAD

**Issue by saw999** [tensorflow/tensorflow#47904]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): version 2, ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

The image below shows how the label map was created for the ssd model.
![ssd_model_label_code](https://user-images.githubusercontent.com/80737339/111729623-d86bda80-8845-11eb-8799-b2595f4be735.jpeg)

### 3. Failure after conversion
The code is for ASL gesture recognition and translates ASL to text. The conversion is successful, however, when running on android studio, the labels of the ASL signs do not show but the accuracy does. What shows up on the android app is a '}' followed by the accuracy. We are assuming it is because of how the labels are defined in the label map file. We used the same object detection Android Studio project as the one in the link below. We just used our ssd tflite model instead of theirs. The labels show for their example and tflite model, but it does not show the labels for our model. 

Example Android Studio project used: https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

Any suggestions on how to get the labels to show when running on Android Studio will be appreciated.

**Comment by abattery** [comment]
@srjoglekar246 could you take a look?

**Comment by srjoglekar246** [comment]
@saw999 To confirm, how big is your converted model? I assume you converted with the instructions [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)?

@lu-wang-g for help with setting up the Android app.

**Comment by jvishnuvardhan** [comment]
@saw999 did you use `TF2.0` or recent stable version. It is recommended to use recent TF version. Thanks!

**Comment by saw999** [comment]
> @saw999 To confirm, how big is your converted model? I assume you converted with the instructions [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)?
> 
> @lu-wang-g for help with setting up the Android app.

The ssd model is 11MB and we followed the same instructions to convert the model.

**Comment by saw999** [comment]
> @saw999 did you use `TF2.0` or recent stable version. It is recommended to use recent TF version. Thanks!

Yes, we used TF2.0.

**Comment by lu-wang-g** [comment]
The label file format is not compatible with what the Android example expects. See there for [an example](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/assets/labelmap.txt) of the label file.

**Comment by saw999** [comment]
> The label file format is not compatible with what the Android example expects. See there for [an example](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/assets/labelmap.txt) of the label file.

We imported the label file into Android Studio in the format shown below:
![labeltext](https://user-images.githubusercontent.com/80737339/111830138-f24c0280-88c3-11eb-917b-559c96469340.png)

**Comment by lu-wang-g** [comment]
The above file looks good. Did you pack the associated file into the model? If not, you can do so by following the answer [here](https://stackoverflow.com/a/64493506/11031225).

**Comment by sanatmpa1** [comment]
@saw999,

Can you take a look at the above comment by @lu-wang-g and let us know if it helps in resolving your issue? Thanks!
