### ISSUE TITLE
Unable to link c++ project due to missing header files

### ISSUE THREAD

**Issue by jjoachim** [tensorflow/tensorflow#47902]
**System information**
- Linux Ubuntu 18.04
- Tensorflow 2.4.1 (from source)
- Bazel 4.0.0
- g++ 7.5.0

**Describe the problem**
I am trying to run some c++ source examples that I've found around, but they require the following header files:
```
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"
```
I ran into a compile issue:
```
/home/cargospectre/tensor/package/tensorflow-2.4.1/tensorflow/core/public/session.h:22:10: fatal error: tensorflow/core/framework/device_attributes.pb.h: No such file or directory
```
I found this file `/tensorflow-2.4.1/bazel-out/host/bin/tensorflow/core/framework/device_attributes.pb.h` and moved it to `tensorflow/core/framework/`, same with `graph.pb.h`. That seemed to work. However, now I'm running into this issue:

```
/home/cargospectre/tensor/package/tensorflow-2.4.1/tensorflow/core/framework/device_attributes.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
```
I think I found the protobuf that was downloaded for tensorflow at `tensorflow-2.4.1/bazel-bin/external/com_google_protobuf`, but it doesn't contain this file. I think the version is different? I tried independently downloading protobuf but this file still didn't exist. Here's my protobuf version:
```
protoc --version
libprotoc 3.0.0
```

So I'm kind of stuck at this point. Am I doing this right? Is there an easier way to access the c++ api? Is there a different example I need to be following?

EDIT: I tried cloning protobuf and building from source, which seems to be version 3.15.6, but now I'm missing yet another file
```
protoc --version
libprotoc 3.15.6

/home/cargospectre/tensor/package/tensorflow-2.4.1/tensorflow/core/framework/device_attributes.pb.h:28:10: fatal error: google/protobuf/inlined_string_field.h: No such file or directory
 #include <google/protobuf/inlined_string_field.h>
```

**Comment by kkimdev** [comment]
Hi, since this is a usage question / trouble shooting, I think it better belongs to StackOverflow, etc,...

(Though this could help: https://www.tensorflow.org/guide/create_op , see `tf.sysconfig.get_compile_flags()` and `tf.sysconfig.get_link_flags()`)
