### ISSUE TITLE
TF.keras in TF2.4

### ISSUE THREAD

**Issue by Alok-Ranjan23** [tensorflow/tensorflow#47909]
What are the differences in tf.keras in TF2.4 with respect to TF1.15 version?

**Comment by Saduf2019** [comment]
@Alok-Ranjan23 
There is no support for tf 1.x and there is support for tf 2.x, tf 2.4 is the latest stable version.
For more differences refer to this [link](https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/) and [this](https://stackoverflow.com/questions/59112527/primer-on-tensorflow-and-keras-the-past-tf1-the-present-tf2).

Also please move this to closed status as it is not a bug or a feature request, for any more clarity kindly open a [stackoverflow](Kindly open a stackoverflow issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!
