### ISSUE TITLE
libtensorflow.so target not public

### ISSUE THREAD

**Issue by LordPython** [tensorflow/tensorflow#4791]
Is there a particular reason that the libtensorflow.so target isn't public? I working on a tensorflow application in C++ and it would be nice to not have to link against tensorflow statically since that's taking ~6min for me.

**Comment by tatatodd** [comment]
@asimshankar might have details here.

**Comment by asimshankar** [comment]
I don't think there is a good reason for the target to be private, can be made public.
If you'd like to send in a pull request, we'd be happy to merge it.

(Out of curiosity: From your notes above, I gather that your project is also using bazel and you're using tensorflow as an external dependency?)

**Comment by LordPython** [comment]
Yes, I've got my project building with bazel and tensorflow is set up as a local_repository. 

It seems the linking was taking a long time due to something about using the clang from Xcode 7.3 (which I need to use because of CUDA), and seems to have been fixed by passing compiler flag -fvisibility-inlines-hidden.

**Comment by asimshankar** [comment]
Good to know, thanks.

I'm going to close this issue out. If you, or anyone else, needs the visibility change for the .so file in the future, we can add it then. Feel free to re-open if you disagree :)

Thanks!
