### ISSUE TITLE
Tensorflow ROCM getting wrong version

### ISSUE THREAD

**Issue by staticdev** [tensorflow/tensorflow#47917]
Didn't find this error on errors list: https://www.tensorflow.org/install/errors

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.10 with kernel 5.10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.2 with tensorflow-rocm2.3.4
- Python version: 3.8.6
- GPU model and memory: AMD Radeon RX580

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

```
Traceback (most recent call last):
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamdhip64.so.4: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/static/pyenv/versions/3.8.6/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: libamdhip64.so.4: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Describe the current behavior** I have rocm 3.9.1 (I downgraded from 4), but it is still trying to get libamdhip64.so.4 instead of libamdhip64.so.3.

**Describe the expected behavior** look for correct version.

**Standalone code to reproduce the issue**
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

**Comment by bhack** [comment]
Have you checked TF and ROCM versions compatibility at https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md ?

@lamberta As this is quite hidden probably we could expose this somewhere in https://www.tensorflow.org/install/gpu#hardware_requirements

**Comment by lamberta** [comment]
We say "CUDA®-enabled cards" in the install section and [gpu](https://www.tensorflow.org/install/gpu) page (it's highlighted at the top of that page).
What did you you want to add? ROCm is not officially supported so we won't add that—but might fit into [SIG Build](https://github.com/tensorflow/build).

**Comment by staticdev** [comment]
@bhack sorry I didn't answer but you were precise in your answer, I didn't knew about this compatibility table. Thanks.

**Comment by bhack** [comment]
@lamberta I meant as we list [Community builds](https://github.com/tensorflow/tensorflow#community-supported-builds) in the landing Readme  here we could find a place just to tell that there are community builds available and to ask support in their relative repositories (or SIG Build if they will support these kind of builds).

**Comment by lamberta** [comment]
Yeah, I think that might be ok.
We currently link out to "SIG Build" in the leftnav of the /install section, and really the extent of what we want to support on tensorflow.org. But if there's a good place to link out, I'm ok with that.
I'm not sure who owns that community build table in the readme. cc: @angerson

**Comment by bhack** [comment]
I don't know who is the owner but this is the last PR that we merged in that section https://github.com/tensorflow/tensorflow/pull/41928

**Comment by lamberta** [comment]
Thanks, bhack. cc: @mihaimaruseac 
It does seem like a useful table and buried, though I'd argue it should be more prominent in [SIG Build](https://github.com/tensorflow/build). Ideally that would be the one URL we could give folks for community supported builds.

**Comment by bhack** [comment]
Yes especially to clearly route support requests/tickets if they are not supported here.
