### ISSUE TITLE
Shared svdf OpData should be renamed to OpDataSvdf

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#47923]
@tensorflow/micro

Noticed this while reviewing #47911

Similar to 
https://github.com/tensorflow/tensorflow/blob/d73ba75a4c1b26b91cc20cb86866d775c02dc479/tensorflow/lite/micro/kernels/conv.h#L27-L28

the svdf struct should be OpDataSvdf instead of
https://github.com/tensorflow/tensorflow/blob/d73ba75a4c1b26b91cc20cb86866d775c02dc479/tensorflow/lite/micro/kernels/svdf.h#L23-L24

This renaming will likely happen after the CEVA optimized kernel is merged so we should include reference, cmsis_nn, xtensa and ceva in the renaming.

**Comment by tilakrayal** [comment]
@advaitjain,
As mentioned the **svdf.h** file which is available on the tflite-micro repo contains the changes which are mentioned **svdf struct should be OpDataSvdf**  . Kindly find the file details below.

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/svdf.h#L23

Thank you!
