### ISSUE TITLE
tfcompile for arm

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#47929]
I'm looking for a step-by-step procedure or example of how to use a compile (XLA/AOT) for the arm64 device. 
Is it possible to cross-compile the TensorFlow graph into executable code? (e.g. Linux/windows as a host machine for Linux-based arm64 device)
Please, if you can link me, I would very much appreciate it.

Thank you.

**Comment by pjpratik** [comment]
Hi @peter197321 

Is it for TF or TFLite?

For TFLite you can cross compile for arm64 devices using CMAKE. Please refer to this [documentation](https://www.tensorflow.org/lite/guide/build_cmake_arm) for building binary which is compatible with [Coral Mendel Linux 4.0](https://coral.ai/), Raspberry Pi (with [Ubuntu Server 20.04.01 LTS 64-bit](https://ubuntu.com/download/raspberry-pi) installed).

Thanks.
