### ISSUE TITLE
Gpu memory issue

### ISSUE THREAD

**Issue by kbrajwani** [tensorflow/tensorflow#47924]
**System information**
- I am using keras finetuned vgg model with 2 dense layers
-  Linux Ubuntu 18.04 (Colab)
- TensorFlow version (use command below): 2.4.3
- Python version: 3.7
- CUDA Version: 11.2   
- GPU model and memory: Tesla P100 with 16 gb

**Describe the current behavior**

here is the log after loading model
Fri Mar 19 17:02:34 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    33W / 250W |   **5703MiB / 16280MiB** |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

it's using 5gb gpu memory.

After making one prediction.

`Fri Mar 19 17:02:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.56       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    38W / 250W |   **9969MiB / 16280MiB** |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
Gpu usage is increased almost duoble.

Can you tell me it's a normal usage or there is something wrong with my code.

**Comment by kbrajwani** [comment]
For reproduce the issue please see this colab notebook : https://colab.research.google.com/drive/1QwfH6aXK8vTLuNslP4qcSMh50fT2K1Gt?usp=sharing

**Comment by Saduf2019** [comment]
@kbrajwani 
I ran this code on tf 2.3,2.4 and nightly, please refer to [the gist](https://colab.research.google.com/gist/Saduf2019/ac73d579cad60bf40eb00fbc76483055/untitled567.ipynb) and would you want to upgrade to nightly and let us know if it helps.

**Comment by kbrajwani** [comment]
Hey @Saduf2019 tf-nightly works like charm . Can you advise me one thing? what is the best process to deploy model on gpu configure machine to take full benefits of gpu.
Thanks

**Comment by kbrajwani** [comment]
Hey @Saduf2019 i am again in same problem this time i am running the program with tensorflow nightly in aws dl ami instance and its eating all gpu memory. In google colab it's working fine. So can you tell me it's tensorflow who makes a difference or cuda versions.

**Comment by kbrajwani** [comment]
Hey @Saduf2019 can you please check following gist where we can reproduce the memory issue. It's working fine if I run a cell in notebook as your gist. But when i run as python file in background it's not releasing memory. Why is taking too much memory to predict and load the model? I don't think it's a correct thing.
https://colab.research.google.com/drive/1QwfH6aXK8vTLuNslP4qcSMh50fT2K1Gt?usp=sharing

**Comment by jvishnuvardhan** [comment]
@kbrajwani Can you please run the code by enabling `tf.config.experimental.set_memory_growth` as shown below. Please check the [TF page](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) for more information.

```
physical_devices = tf.config.list_physical_devices('GPU')
try:
  tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
  # Invalid device or cannot modify virtual devices once initialized.
  pass
```

Also, can you try Keras under TF. Instead of importing keras as `import keras`, can you try importing as `from tensorflow import keras`.

Please let us know how it progresses. Thanks!

**Comment by kbrajwani** [comment]
@jvishnuvardhan I have tried both things you can check [gist ](https://colab.research.google.com/drive/1QwfH6aXK8vTLuNslP4qcSMh50fT2K1Gt?usp=sharing) but it doesn't work.

**Comment by kbrajwani** [comment]
@sanjoy Have you find any solution?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/87bdfd06c474e9c06cabb9f82b6b9a52/untitled168.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/ba4b1a12082231b36608c352f826a045/untitled250.ipynb) ..Thanks!

**Comment by sachinprasadhs** [comment]
Could you please try in the latest Tensorflow version with compatible CUDA and CuDNN version and let us know if you still face an error. Thanks!
