### ISSUE TITLE
TFLiteSavedModelConverterV2 breaks ordering of multi output models

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#47927]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- TensorFlow installation (pip package or built from source): binary and source 
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0-dev20210319, 5abe2b515db51d3aa35f6acf5869c1ce51a6b09c

**Describe the current behavior**

`tf.lite.TFLiteConverter.from_saved_model` doesn't support multi output models and outputs non-deterministic ordering which breaks users of the generated flatbuffers.

This is due to the fact that TFLite converter relies on the output ordering, but the saved model import function purposefully breaks this assumption by scrambling the inputs and outputs:
https://github.com/tensorflow/tensorflow/blob/c36991b0367a12bc81bf37dfdc5cf4793c7a8bde/tensorflow/compiler/mlir/tensorflow/translate/import_model.cc#L3708-L3721

**Describe the expected behavior**

`tf.lite.TFLiteConverter.from_saved_model` should behave the same way as `tf.lite.TFLiteConverter.from_keras_model` and preserve the output ordering. This issue is especially problematic when relying on models using `@tf.function(experimental_implements=True)` which are only supported by the saved model converter.

**Standalone code to reproduce the issue**
I opened PR #47928 which includes a failing test case (093f927aa9c217bfbecf7350c3c3f651964587af) that reproduces this issue when running the unittests with `bazelisk test tensorflow/lite/python:lite_v2_test --test_output=all`.

**Comment by abattery** [comment]
For the multiple input/output naming/ordering issue, we recommend using TFLite signature def API.

SignatureDef provides meaningful/generic names for inputs/outputs which doesn't rely on specific model details. More on SignatureDefs here.
If your saved model has a defined signatureDef then it will be exported during conversion to TFLite and then you can use the Signature inputs/outputs for inference and not relying on inputs/outputs order or tensor names.

SignatureDef support is new thing available in nightly and will be available in 2.5

Then use the nightly for converting to tflite. The generated tflite file will have the SignatureDef details.
Using Python API (as an example) you can do something like

```
my_signature = interpreter.get_signature_runner("my_method")
results = my_signature(input_1=input_tensor_1, input_2=input_tensor_2)
print(results["my_output"])
```

**Comment by lgeiger** [comment]
@abattery Thanks for the fast response.

I should've elaborated a bit more about the use case in my description. I am aware that users of saved model should not rely on the ordering of the output. However, this issue came up when using `tf.lite.TFLiteConverter.from_keras_model` together with models that use `@tf.function(experimental_implements=...)`.

This means `TFLiteKerasModelConverterV2` will use `TFLiteSavedModelConverterV2` under the hood
https://github.com/tensorflow/tensorflow/blob/52a6477e956d5be2c90e9e799ed3e0ad4512f77e/tensorflow/lite/python/lite.py#L951
in cases where the model uses `@tf.function(experimental_implements=...)`:
https://github.com/tensorflow/tensorflow/blob/52a6477e956d5be2c90e9e799ed3e0ad4512f77e/tensorflow/lite/python/lite.py#L570-L573

Therefore,  depending on the kind of model passed to `TFLiteKerasModelConverterV2`,  the output would either be orderer or not depending on an implementation detail. This would e.g. break [this existing unittest](https://github.com/tensorflow/tensorflow/blob/52a6477e956d5be2c90e9e799ed3e0ad4512f77e/tensorflow/lite/python/lite_v2_test.py#L1331-L1371) if the saved model code path is used internally.
I think this behaviour is quite confusing for users since I don't think it is documented anywhere in the Keras to TFLite conversion docs and breaks with the assumption that Keras model outputs are ordered which as far as I know holds true anywhere else in the code. So intuitively I would also expect the TFLite model directly converted from a Keras model to have the same ordering.

I agree that for saved models itself the story is a bit different since as far as I know one always had to refer to tensors directly by their names or via a signature def. So the behaviour here is consistent, but for the Keras model conversion I do think this could lead to serious bugs in user space, or am I missing something obvious here?

In any case I will take a closer look at `SignatureDef` and how we can use it for our need. We are mainly targeting TFLite Micro and I haven't looked into how we can use the `SignatureDef` in that context.

**Comment by abattery** [comment]
I would recommend exporting your keras model to the corresponding saved model before putting it to the TensorFlow Lite converter API for now.

Thank you for providing the valuable feedback. At least, there should be improvements in the document side.

**Comment by abattery** [comment]
Reopened for looking for another workaround.

**Comment by lgeiger** [comment]
@abattery Thanks for re-opening the issue. I tried out using `SignatureDefs` with Keras models and discovered a few bugs and usability issues which can be reproduced in [this colab notebook](https://colab.research.google.com/drive/12GWxCkECNYNDMx0EaI379lIQEvZgsW4i?usp=sharing).

The first problem is related to using full int8 quantization (/cc @MeghnaNatraj) by setting
```python
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
```
This breaks the signature runner since the signature still refers to tensors that [have been removed when converting to full int8 quantization](https://github.com/tensorflow/tensorflow/blob/305926798c36e2babfd31395317db33c55490d5b/tensorflow/lite/python/lite.py#L745).

The second problem is more a usability issue. Since the signature input and output names are set via Keras layer names, the signature of a Keras model depends on whether layers with the same name have already been instantiated prior to model saving which would lead to a change in leayer names. I think this is especially important when using the signature runner since users will need to rely on fixed names in their TFLite code as far as I can tell. Otherwise this means during training great care needs to be taken that the model is saved in a fresh environment to not mess up the names (this can be very tricky during fine tuning where multiple instances of the same model might exist in the training code).

Let's construct a model using dictionaries as inputs and outputs which provide a unique mapping in multi-output models
```python
model = tf.keras.Model({"input": input_tensor}, {"boxes": boxes, "scores": scores})

print(model.input)
# {'input': <KerasTensor: shape=(None, 32, 32, 128) dtype=float32 (created by layer 'input_4')>}

print(model.output)
# {'boxes': <KerasTensor: shape=(None, 4) dtype=float32 (created by layer 'tf.reshape_6')>,
# 'scores': <KerasTensor: shape=(None,) dtype=float32 (created by layer 'tf.reshape_7')>}
```

Unfortunately the signature def would include layer names that might not be uniquely identifiable across model training runs.
```python
print(interpreter.get_signature_list()["serving_default"])
# {'inputs': ['input_4'], 'outputs': ['tf.reshape_6', 'tf.reshape_7']}
```

Please take a look at [this colab notebook](https://colab.research.google.com/drive/12GWxCkECNYNDMx0EaI379lIQEvZgsW4i?usp=sharing) for a fully reproducible code example.

For me, all of these issues would be solved by maintaining the input/output order of the Keras model during serialization and conversion to TFLite so that the order of `model.inputs` and `model.outputs` (returns a list of tensors) are preserved during conversion.
Alternatively, relying on `SignatureDefs` would work very well too, if it supports full int8 conversion and if there exists an easy to use way to repeatedly name inputs and outputs during Keras model saving that does not depend on the automatic layer naming of Keras.

**Comment by lgeiger** [comment]
@abattery @MeghnaNatraj Do you have any recommendation on how to workaround this bug until there is a proper fix for it implemented?

**Comment by abattery** [comment]
Actually, you can override the output signature names by wrapping the keras model.

For example,

```
@tf.function(input_signatures=[tf.TensorSpec([None, 32, 32, 128], dtype=tf.float32, name="input_tensor")])
def override_output_signatures(input_tensor):
   outputs = keras_model(input_tensor)
   return {"boxes": prediction.boxes, "scores": prediction.scores}

signatures = override_output_signatures.get_concrete_function()
tf.saved_model.save(model, export_dir=export_path, signatures=signatures)
```

**Comment by lgeiger** [comment]
Cool, thanks. Would be great if this could be automatically done when constructing the Keras model in the future.

But that still will break with `converter.inference_output_type = tf.int8` since it modifies the flatbuffer after the fact.

**Comment by abattery** [comment]
@lgeiger Could you help us create a separate issue for the int8 overriding case with the signature definitions? This thread has a number of the discussion points and it is not easy to focus on when we invite more folks to look at the issue. It would be great if you can provide a minimal example as a form of the gist regarding the above issue.

**Comment by abattery** [comment]
Thanks @lgeiger for finding a bug! I took the above colab. It looks like the signature API can be broken after the model optimization is applied. Could you copy and paste the comment (https://github.com/tensorflow/tensorflow/issues/47927#issuecomment-804240854) to create a separate issue? I will take a look at this issue with the team.

**Comment by abattery** [comment]
fyi @karimnosseir

**Comment by lgeiger** [comment]
Thanks for taking a look. I opened #48148 which only includes the description of the bug that breaks the signature API with full integer models.

Sorry for mixing the two problems, this issue can now focus purely on the API usability.

**Comment by abattery** [comment]
The signature def API is designed intentionally without having an intuitive order. It would be better to rely on the names instead of the order.

**Comment by lgeiger** [comment]
> The signature def API is designed intentionally without having an intuitive order. It would be better to rely on the names instead of the order.

I agree that using the signature def API makes a lot of sense when working with `tf.functions` and saved models directly.

However, I think users only working with Keras models tend to expect that output ordering is preserved similar to how Python functions returning tuples work. So when converting models with `tf.lite.TFLiteConverter.from_keras_model` the fact that output ordering is not preserved is surprising since the fact that models get serialized as saved models during conversion is only an implementation detail that changed in TF 2.4.
Is there a concrete reason for why preserving output ordering is not possible for Keras models? When saving and loading Keras models using `model.save` and `tf.keras.models.load_model` the ordering is preserved as well, which is why I am confused that this is not possible when converting to TFLite.

**Comment by sachinprasadhs** [comment]
Hi, We are investigating on this issue.
Could you please close this issue and track the progress https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182 in the similar issue.
Along with the linked comment workaround, the suggested way to use is make use of signatures in your model https://www.tensorflow.org/lite/guide/signatures

**Comment by MeghnaNatraj** [comment]
I'm currently using TFLite as an external user, and I am currently facing the same issue as lgeiger@

As shows in [this comment above](https://github.com/tensorflow/tensorflow/issues/47927#issuecomment-804240854), once I train a keras model and specifiy input and output names, the input name stays as is but the output name is not preserved. To overcome this, I have added a `tf.keras.layer.Layer` to each of my outputs. 

eg: In the above scenario, that would translate to:

```
scores = tf.keras.layer.Layer(scores, name="scores)
