### ISSUE TITLE
Optimize unique_op by repetition rate

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#47947]
My test about unique op:

> Input: size:20\*1000k, uniqued size:5\*1000k.

> cmp test:

>> Origin: The initial size of the hash table in unique_op is 2*input_size

>> My test: The initial size of the hash table in unique_op is 1*input_size(change source code"tensorflow/core/kernels/unique_op.cc").

> cmp result:
>> Origin: spend: 2.517s
>> My test: spend: 1.709s(↑32.1%)

**As the size of the hash table increases, memory bind will increase.**
I think unique_op should be added a default params of repetition rate, default value is non-repeating(hash table size is 2*N)。Repetition rate will help us do some prediction, like: Adjust the initial size of the hash table to improve performance。
If the user does not know the repetition rate of his data, he should use default value.
If the user knows the repetition rate of his data, he will adjust this args to get a better performance.
Do you think this view makes sense? If it makes sense, I would be happy to discuss & implement this part of the code. ^v^

My test code:
```
from __future__ import print_function
import random
import tensorflow as tf
import time

size = 20 * 1000000
sum=0
keys, idx = tf.unique(tf.random_uniform(shape=[int(size)], dtype=tf.int64, maxval=int(size/5)), version='v2')

sess = tf.Session()
with tf.Session() as sess:
    for i in range(0,10):
       start = time.time()
       _ = sess.run(keys)
       sum+=(time.time() - start)
    print("avg time:", sum / 10);
```

**Comment by zhaozheng09** [comment]
I suggest repetition rate is a range of [0, 1), 0 is non-repeating, 1 is completely repetitive.
hash_table_size = 2 - repetition_rate.
If user use default value(non-repeating), hash_table_size is origin(2 * input_size).
If user use default value(my test, 0.75), hash_table_size is (1.25(ps:2-0.75) * N).

In order to solve the problem, we need to find a way to know whether the hash table has been expanded. If there is an expansion, a warning will be issued to notify the user that the wrong usage method may cause performance degradation.

**Comment by zhaozheng09** [comment]
Heuristic hash table size maybe a good idea ~

**Comment by zhaozheng09** [comment]
copy that. @kkimdev

**Comment by kkimdev** [comment]
Q: Is this request from a real world use case? If so, do you mind sharing with us?  I'm trying to gauge the importance of this and if it'll be useful more broadly.  Thanks!

**Comment by zhaozheng09** [comment]
Scene: Ps save embedding hash table, and workers get embedding by features.
We need unique_op to filter repeated features(hash key) for decreasing net pressure and decreasing lookup embedding hash table times.
Now we search 2,000,000 features in hash table once(like my test code).
We will search more keys in the future.

Data:The data cannot be given to you due to its sensitivity, but the characteristics of the data are the same as in the example.
