### ISSUE TITLE
WARNING:tensorflow:multiprocessing can interact badly with TensorFlow

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#47955]
I've a custom custom `tf.keras` data generator using `tf.keras.utils.Sequence`. Whenever I set `use_multiprocessing` as True, it gives a warning message at the very beginning. The custom data generator (in my case) read the image data, do some augmentation and return batch-wise samples. Nothing special, just a conventional approach. The full warning statement is 

> WARNING:tensorflow: multiprocessing can interact badly with TensorFlow, causing non-deterministic deadlocks. For high-performance data pipelines tf. data is recommended.

Just about to start training but freeze everything anyway after showing this message. The issue is, **Is it BAD to use multiprocessing, or Is it NOT POSSIBLE to use?**

**Comment by Saduf2019** [comment]
@innat 
Please refer to this comment from the member of the keras community [here](https://github.com/tensorflow/tensorflow/issues/46316#issuecomment-760339753).

Also please provide with code for us to replicate the issue.

**Comment by innat** [comment]
I wanted to reproduce this issue on some public data set on the kaggle kernel. But surprisingly I couldn't reproduce this issue.

In my local machine (Windows), my CPU: Intel Core `i5 6600` (`3.3`GHz), `4` logical Core, and with `TF 2.4.1`, Cuda `11.0`, cuDNN `8.0.4` - GPU: RTIX 2070. 

In kaggle, the kernel it's using `TF 2.4.1`. And `use_multiprocessing` froze my training at the beginning but in the kaggle kernel, it runs anyway. 

Here is a kernel I've used. https://www.kaggle.com/ipythonx/tf-keras-issue-47955?scriptVersionId=57548428

In the notebook, there is a class name `TrainConfig` where multiprocessing is set `True` or `False` in the `MULTIPROCESS` variable.

**Comment by innat** [comment]
Additionally, this is the kaggle CPU spec: `Xeon Processors @2.3Ghz, 46MB Cache. The same code runs on here but not on windows pc with `Intel Core i5, @3.3GHz, 6MB Cache`. What do I need to look at here?

**Comment by Wazaki-Ou** [comment]
I am facing the same issue. I used tf.keras.utils.Sequence to create my custom data generator, and I tried all solutions I could find to make it work, but whenever I try with multiprocessing, I get that same warning and the training does not start.
