### ISSUE TITLE
" ValueError: assignment destination is read-only" when using Pandas DataFrame

### ISSUE THREAD

**Issue by JulianWgs** [tensorflow/tensorflow#47958]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code I suppose (see below)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source): Not applicable
- GCC/Compiler version (if compiling from source): Not applicable
- CUDA/cuDNN version: Using CPU
- GPU model and memory: Using CPU

**Describe the current behavior**
This code
```python
import pandas as pd
import tensorflow as tf

df = pd.DataFrame()
df["x"] = tf.linspace(0, 100, 20)
df["x"] /= 2
```
produces the following error
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-796d4d4e000c> in <module>
      4 df = pd.DataFrame()
      5 df["x"] = tf.linspace(0, 100, 20)
----> 6 df["x"] /= 2

~/.local/lib/python3.8/site-packages/pandas/core/generic.py in __itruediv__(self, other)
  11338 
  11339     def __itruediv__(self, other):
> 11340         return self._inplace_method(
  11341             other, type(self).__truediv__  # type: ignore[operator]
  11342         )

~/.local/lib/python3.8/site-packages/pandas/core/generic.py in _inplace_method(self, other, op)
  11315         ):
  11316             # GH#36498 this inplace op can _actually_ be inplace.
> 11317             self._values[:] = result._values
  11318             return self
  11319 

ValueError: assignment destination is read-only
```

**Describe the expected behavior**
Normal assignment of the operation, like with Numpy.
```python
import pandas as pd
import numpy as np

df = pd.DataFrame()
df["x"] = np.linspace(0, 100, 20)
df["x"] /= 2
```

**Workaround**
```python
import pandas as pd
import tensorflow as tf

df = pd.DataFrame()
df["x"] = pd.Series(tf.linspace(0, 100, 20))
df["x"] /= 2
```

**Comment by amahendrakar** [comment]
> ~/.local/lib/python3.8/site-packages/pandas/core/generic.py in _inplace_method(self, other, op)

@JulianWgs,
From the error log, it looks like the error is thrown from the pandas module. 

In this case, could you please get in touch with pandas support regarding the error. Thanks!

**Comment by JulianWgs** [comment]
Thanks for the fast reply :)

This is true. However something in the Tensorflow code sets the array to be non writeable. The error does not happen when the exception is thrown, but when the tensor is assigned to the column of Pandas. The Numpy implementation handles it „correctly“.

Do you understand what I mean?

Sorry, for not clarifying this earlier.

Greetings
Julian

**Comment by pawanfaujdar** [comment]
import pandas as pd
import tensorflow as tf

df = pd.DataFrame()

df["y"] = tf.linspace(0, 100, 20)

def f(t):
    return t/2

df["x"]=df["y"].apply(f)
df.drop("y",axis=1,inplace=True)

**Comment by rmothukuru** [comment]
@JulianWgs,
The behavior is expected as the `Tensors` are **`immutable`**.  The problem can be resolved by replacing
`df["x"] = tf.linspace(0.0, 100.0, 20)` with `df["x"] = tf.linspace(0.0, 100.0, 20).numpy()`.

Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/b73d93b7ae4cf4477224570184d08530/gh_v.ipynb) of working code. Thanks!

**Comment by JulianWgs** [comment]
Thank you for your response :)

I know that Tensors are immutable, but Pandas Series are not. Tensorflow wrongly casts the Tensor as an immutable Series. As you can see in the workaround when using `pd.Series` the Tensor gets cast correctly as mutable. This is the correct behavior and should **also** happen, when directly assigning the Tensor.

Let me give you another example:
Tuples are also immutable, yet they correctly cast as mutable to a Pandas Series.

```python
import pandas as pd

immutable_tuple = tuple(range(5))
print(immutable_tuple)

# Tuples are not mutable (this does not work, because tuples are immutable)
immutable_tuple[2] = 5 

# Assign tuple to Pandas Series
df = pd.DataFrame()
df["tuple"] = immutable_tuple
df

# Pandas Series, based on a tuple, is now mutable
df["tuple"][2] = 5
df
```

To get closer to the origin of the bug, I would look at the difference of the call stacks between assignment to a Pandas Series and `pd.Series`.

Best regards
Julian

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in [TF v2.5](https://colab.research.google.com/gist/sushreebarsa/19763db786e1aecd738bb6bf75c157de/untitled171.ipynb#scrollTo=Lel12_wU092S) &[ TF 2.6.0-dev20210531](https://colab.research.google.com/gist/sushreebarsa/875d8818661966c886b932799d014010/untitled170.ipynb),Please find the gists ..Thanks !

**Comment by Venkat6871** [comment]
Hi **@JulianWgs** ,
Can you please try with recent TF version? I tried with TF2.16.1 and I cannot reproduce the error. Please check the [gist](https://colab.sandbox.google.com/gist/Venkat6871/b158c375ba3a514477293cc1d9501125/untitled122.ipynb) here.
Thank you!
