### ISSUE TITLE
Cant install tflite_runtime while deploying on web application online

### ISSUE THREAD

**Issue by nikhilnaregal** [tensorflow/tensorflow#47951]
**System information**
- OS Platform and Distribution (windows 10)

- TensorFlow installed from (source or binary):
- TensorFlow version: Uninstalled(As I cannot use such a huge library)
- Python version:  3.8
- Installed using virtualenv and pip3 on local
[requirements.txt](https://github.com/tensorflow/tensorflow/files/6177015/requirements.txt)

- GPU 8Gb memory:

I am new to this but I will try to explain my situation.
So I am using tflite.interpreter to load the saved model(converted to tflite) using tflite. interpreter.
Everything works fine on the local system but when I deploy my Django app to Heroku or azure. I cant install tflite_runtime from Requirements.py during git push to remote.
I used this to install it on my local
pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime

How do I include tflite_runtime in requirements.txt so that it automatically installs using pip while pushing to GIT?

`remote: Collecting scipy==1.6.1 remote: Downloading scipy-1.6.1-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB) remote: Collecting six==1.15.0 remote: Downloading six-1.15.0-py2.py3-none-any.whl (10 kB) remote: Collecting sqlparse==0.4.1 remote: Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB) remote: ERROR: Could not find a version that satisfies the requirement tflite-runtime==2.5.0 (from -r /tmp/build_1599e83a/requirements.txt (line 22)) (from versions: none) remote: ERROR: No matching distribution found for tflite-runtime==2.5.0 (from -r /tmp/build_1599e83a/requirements.txt (line 22)) remote: ! Push rejected, failed to compile Python app. remote: remote: ! Push failed remote: Verifying deploy... remote: remote: ! Push rejected to predictivemaintenance2021. remote: To https://git.heroku.com/pred2021.git ! [remote rejected] master -> master (pre-receive hook declined)
`

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by abattery** [comment]
https://stackoverflow.com/a/2477610/11843861 maybe you resolve the problem by adding an extra index in the requirements.txt.

**Comment by nikhilnaregal** [comment]
Thank you for your time,
I tried using extra index (-i) in requirements.txt but it gave me an error As I have other libraries in my requirements.txt file and it is looking for these libraries as well in the URL provided.
Is there anything else i should try? Please suggest

**Comment by abattery** [comment]
@nikhilnaregal This issue looks irrelevant with the TensorFlow project. This issue is related to how to use the custom repo in the requirements.txt. I would close this because this is the TensorFlow forum and another post from stackoverflow looks like a better place to handle this issue.
