### ISSUE TITLE
Make //tensorflow/cc:cc_ops compile for Android

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#4795]
It seems that the bazel target //tensorflow/cc:cc_ops is currently not compilable for Android. From what I saw, this is at least because of the missing platform specific headers (e.g. in tensorflow/core/platform/gif.h).

Making the cc_ops compilable for Android would allow to fully use tensorflow on Android. In particular, I'm trying to build tensorflow for Android with the operations to be able to provide [javacpp-presets](https://github.com/bytedeco/javacpp-presets) which allow an automated generation of complete Java bindings. Therefore they can be used to completely omit the jni/C++ code in Android applications that want to use tensorflow.

**Comment by andrewharp** [comment]
The Android version of TF uses a different build tree so that we can concentrate on binary size, etc. You'll find that most of cc_ops is provided by //tensorflow/core:android_tensorflow_lib
