### ISSUE TITLE
TextVectorization inconsistency depending on output_sequence_length

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#47954]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.1
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`TextVectorization`'s behavior changes if `output_sequence_length` is set.

**Describe the expected behavior**
I would expend the behavior to remain the same (up to the effect of `output_sequence_length`, of course). However, same that runs perfectly in one case, causes a runtime error in the other. The reason is that the former accepts scalar inputs, whereas the latter requires input rank > 0.

P. S.
I can fix it, the question is whether we want to accept scalar inputs or not.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_datasets as tfds

ds_train, ds_test = tfds.load("imdb_reviews", split=["train", "test"], as_supervised=True)


encoder1 = tf.keras.layers.experimental.preprocessing.TextVectorization(max_tokens=10000)
encoder2 = tf.keras.layers.experimental.preprocessing.TextVectorization(max_tokens=10000, output_sequence_length=200)

encoder1.adapt(ds_train.map(lambda x, y: x))
encoder2.adapt(ds_train.map(lambda x, y: x))

for x, y in ds_train:
  print(x)
  print(encoder1(x)) # This one works
  print(encoder2(x)) # This one fails



tf.Tensor(b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.", shape=(), dtype=string)
tf.Tensor(
[  11   14   34  412  384   18   90   28    1    8   33 1322 3560   42
  487    1  191   24   85  152   19   11  217  316   28   65  240  214
    8  489   54   65   85  112   96   22 5596   11   93  642  743   11
   18    7   34  394 9522  170 2464  408    2   88 1216  137   66  144
   51    2    1 7558   66  245   65 2870   16    1 2860    1    1 1426
 5050    3   40    1 1579   17 3560   14  158   19    4 1216  891 8040
    8    4   18   12   14 4059    5   99  146 1241   10  237  704   12
   48   24   93   39   11 7339  152   39 1322    1   50  398   10   96
 1155  851  141    9], shape=(116,), dtype=int64)

---------------------------------------------------------------------------

InvalidArgumentError                      Traceback (most recent call last)

<ipython-input-3-fe1d367865bf> in <module>()
      2   print(x)
      3   print(encoder1(x))
----> 4   print(encoder2(x))

8 frames

/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: text_vectorization_1/strided_slice/

```

**Comment by eli-osherovich** [comment]
[colab link](https://colab.research.google.com/gist/eli-osherovich/591f0e7a44b9b912fd9fcf52711a09dd/untitled1.ipynb)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/acad508bce039cd9db9209532dd88d83/47954.ipynb). Thanks!

**Comment by eli-osherovich** [comment]
Any response?
