### ISSUE TITLE
Multiple inputs api does NOT work correctly, concatenates first input and null to second

### ISSUE THREAD

**Issue by RichardKershner-v1** [tensorflow/tensorflow#47965]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by RichardKershner-v1** [comment]
Full code, system settings and errors below.  Tried this in many different formats and setups under Anaconda Jupyter.

By feeding the different inputs x, and x2, as the output, it can be seen that the inputs feed in cacatenated into the first input and not split between the two.

model = keras.Model(inputs=[x, x2], outputs=x)
model.predict([data,data1])
WARNING:tensorflow:Model was constructed with shape (None, 2) for input Tensor("input_3:0", shape=(None, 2), dtype=float32), but it was called on an input with incompatible shape (None, 4, 2).
[[[ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]
  [ 8.  9.]]

 [[10. 11.]
  [12. 13.]
  [14. 15.]
  [16. 17.]]]

model = keras.Model(inputs=[x, x2], outputs=x2) 
model.predict([data,data1])
  AssertionError: Could not compute output Tensor("input_2:0", shape=(None, 2), dtype=float32)
  puts out empty data sets. Full error at bottom.

============ complete code ==========
import numpy as np
import pandas as pd
import os

from datetime import date

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

data = [[2,3],[4,5],[6,7],[8,9]]
data1 = [[10,11],[12,13],[14,15],[16,17]]

train = (np.array(data) * 2).tolist()

print('data', data)
print('train',train)
print()

x = layers.Input(shape=(2,),dtype=tf.float32)
x2 = layers.Input(shape=(2,),dtype=tf.float32)
# DOESN'T SEE X2 !!!!!!!!!! BOTH GO INTO X !!!!!!!!!!!!!!!!!!!!!!

model = keras.Model(inputs=[x, x2], outputs=x)
# switched to outputs = x2 for second testing
model.compile() #loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

pred = model.predict([data,data1])
print(pred)

============ system configuration =======
print('keras version:', keras.__version__)
import tensorpack.tfutils as u
print(u.collect_env_info())
keras version: 2.4.0
python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
tensorflow version: 2.3.0
keras version: 2.4.0

-------------------  ----------------------------------------------------------------------------------------
sys.platform         win32
Python               3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Tensorpack           v0.11-2-g88530083-dirty @C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorpack
Numpy                1.20.1
TensorFlow           2.3.0/unknown @C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow
TF Compiler Version  MSVC 192729111
TF CUDA support      False
TF MKL support       False
TF XLA support       False
Free RAM             21.47/32.00 GB
CPU Count            16
cv2                  4.0.1
msgpack              1.0.2
python-prctl         False

========== FULL ERROR for using x2 as output ========
WARNING:tensorflow:Model was constructed with shape (None, 2) for input Tensor("input_1:0", shape=(None, 2), dtype=float32), but it was called on an input with incompatible shape (None, 4, 2).
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-eaa004bedc40> in <module>
     30 print(model.summary())
     31 
---> 32 pred = model.predict([data,data1])
     33 print(pred)

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
    128       raise ValueError('{} is not supported in multi-worker mode.'.format(
    129           method.__name__))
--> 130     return method(self, *args, **kwargs)
    131 
    132   return tf_decorator.make_decorator(

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1597           for step in data_handler.steps():
   1598             callbacks.on_predict_batch_begin(step)
-> 1599             tmp_batch_outputs = predict_function(iterator)
   1600             if data_handler.should_sync:
   1601               context.async_wait()

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\def_function.py in _initialize(self, args, kwds, add_initializers_to)
    694     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    695     self._concrete_stateful_fn = (
--> 696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    697             *args, **kwds))
    698 

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3063     arg_names = base_arg_names + missing_arg_names
   3064     graph_function = ConcreteFunction(
-> 3065         func_graph_module.func_graph_from_py_func(
   3066             self._name,
   3067             self._python_function,

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

~\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\framework\func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

AssertionError: in user code:

    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\functional.py:385 call
        return self._run_internal_graph(
    C:\Users\rkers\Anaconda3\envs\py38\lib\site-packages\tensorflow\python\keras\engine\functional.py:517 _run_internal_graph
        assert x_id in tensor_dict, 'Could not compute output ' + str(x)

    AssertionError: Could not compute output Tensor("input_2:0", shape=(None, 2), dtype=float32)

**Comment by Saduf2019** [comment]
@RichardKershner-v1 

Can you share simple stand alone code such that we could replicate the error reported or share a colab gist with the code and error, also share tf version we see that the template has not been filled.

You may also refer to below issues and let us know:
#34912 [link](https://stackoverflow.com/questions/61444983/keras-cnn-with-several-input-filters)

**Comment by RichardKershner-v1** [comment]
Thought I had the code above.  It also might be a Keras and not a tensor flow issue.
I did figure the fix for it, which doesn't seem like it should be the one that works.

First, I had to name the inputs and build a dataset.  The weird key is that I had to reshape the data, as below.  Not intuitive.  I have the below code with an output for concatenate and with an output for average.

def input_gen():
    a = np.array(data1).reshape(-1,1,2).tolist()
    b = np.array(data2).reshape(-1,1,2).tolist()
    return {'x1': a, 'x2': b}
dataset = tf.data.Dataset.from_tensor_slices(input_gen ())

import numpy as np
import pandas as pd
import os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

#data1 = [[[2,3]],[[4,5]],[[6,7]],[[8,9]]]  this is what new shape looks like that works
#data2 = [[[10,11]],[[12,13]],[[14,15]],[[16,17]]]
data1 = [[2,3],[4,5],[6,7],[8,9]]
data2 = [[10,11],[12,13],[14,15],[16,17]]

train = (np.array(data) * 2).tolist()

x1 = layers.Input(shape=(2),dtype=tf.float32, name="x1")
x2 = layers.Input(shape=(2),dtype=tf.float32, name="x2")

y1 = layers.Concatenate()([x1, x2]) 
y2 = layers.Average()([x1, x2])

model = keras.Model(inputs=[x1, x2], outputs=[y1,y2])
model.compile()#loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# print(model.summary())

def input_gen():
    a = np.array(data1).reshape(-1,1,2).tolist()
    b = np.array(data2).reshape(-1,1,2).tolist()
    return {'x1': a, 'x2': b}
dataset = tf.data.Dataset.from_tensor_slices(input_gen ())

pred = model.predict(dataset)

print('pred')
print(pred)

-- output as expected--
-- a 4(batchsize) by 4 array concatenated of the 2 (4x4) inputs --
-- and the average by axis = 1 , shape 4(batch size) by 2
y1 is for concatenate, y2 is for average as below.
[array([[ 2.,  3., 10., 11.],
       [ 4.,  5., 12., 13.],
       [ 6.,  7., 14., 15.],
       [ 8.,  9., 16., 17.]], dtype=float32), array([[ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.]], dtype=float32)]
