### ISSUE TITLE
[TFLM] Person detection benchmark build broken when generating Makefile projects

### ISSUE THREAD

**Issue by yair-ehrenwald** [tensorflow/tensorflow#47961]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): Nightly, source
- Tensorflow version (commit SHA if source): commit id 9711a668d8538ac2a3ebe93a90226b89683d0206
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**
When generating a Makefiles project for the person detection benchmark build fails due to some missing headers.
Command used: make -f tensorflow/lite/micro/tools/make/Makefile  generate_person_detection_benchmark_make_project

I will open a PR shortly with a fix.

**Comment by Saduf2019** [comment]
@yair-ehrenwald 
We see that you have raised a pr, this issue will close once the pr is merged.
please update the tf version in the template.
