### ISSUE TITLE
how to build  tensorflow-lite-gpu-x.x.x.aar

### ISSUE THREAD

**Issue by HuaMuLanChina** [tensorflow/tensorflow#47966]
**System information**
-  Linux Ubuntu 20.04:
- Mobile device : android
- TensorFlow installed from:source
- TensorFlow version:2.4.1
- Python version:3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):Bazel 3.1.0

**Describe the problem**
Build success with https://www.tensorflow.org/lite/guide/build_android but no gpu support
Any information on 'how to build tensorflow-lite-gpu-x.x.x.aar'

**Comment by abattery** [comment]
@terryheo @thaink could you take a look?

**Comment by thaink** [comment]
You can build it the same way you build tensorflow-lite.aar.
Just replace `//tensorflow/lite/java:tensorflow-lite`with `//tensorflow/lite/java:tensorflow-lite-gpu`.
Ex:
```
bazel build -c opt --cxxopt=--std=c++14 \
    --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    //tensorflow/lite/java:tensorflow-lite-gpu
```

**Comment by HuaMuLanChina** [comment]
cool , Thanks.
