### ISSUE TITLE
No visible @interface for 'TFLInterpreter' declares the selector 'copyData:toInputTensorAtIndex:error:'

### ISSUE THREAD

**Issue by Fedour** [tensorflow/tensorflow#47975]
Hello, I have a little problem with the tensorflow documentation.

I would like to use tensorflow lite with Objective C by following this [documentation](https://www.tensorflow.org/lite/guide/inference)

## URL(s) with the issue:

https://www.tensorflow.org/lite/guide/inference

## Description of issue (what needs changing):

Apparently this function is not declared:

`[interpreter copyData:inputData toInputTensorAtIndex:0 error:&error];`

I got this following error:

`No visible @interface for 'TFLInterpreter' declares the selector 'copyData:toInputTensorAtIndex:error:'`

Am I missing something, how can I fill a tensor with objective C ?

**Comment by abattery** [comment]
@yyoon could you take a look?

**Comment by Fedour** [comment]
I think I have it.

We need to apply copyData on a TFLTensor object, not the TFLInterpreter like this:

```
NSMutableData *inputData;  // Should be initialized
TFLTensor *inputTensor = [interpreter inputTensorAtIndex:0 error:&error];

//Feed data
[inputTensor copyData:inputData error:&error]
```

Am I correct ?

**Comment by yyoon** [comment]
@Fedour Thanks for reporting! You are correct on that.
Will update the inference guide doc.
