### ISSUE TITLE
WARNING: AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x000002051844F0D0> and will run it as-is. Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'arguments' object has no attribute 'posonlyargs' To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

### ISSUE THREAD

**Issue by shuchitajain** [tensorflow/tensorflow#47976]
I am trying to train my model and then get the Mean Attribute Error between predicted and true values.
But the predicted value column is empty due to this error.

**Comment by amahendrakar** [comment]
@shuchitajain,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, you can suppress the warning messages by changing the log level at the start of the program 
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```

or you can set the [autograph verbosity](https://www.tensorflow.org/api_docs/python/tf/autograph/set_verbosity
) level using

```
import os
import tensorflow as tf
os.environ['AUTOGRAPH_VERBOSITY'] = 1
```
Thanks!

**Comment by shuchitajain** [comment]
> or you can set the [autograph verbosity](https://www.tensorflow.org/api_docs/python/tf/autograph/set_verbosity) level using
> 
> ```
> import os
> import tensorflow as tf
> os.environ['AUTOGRAPH_VERBOSITY'] = 1
> ```
> 
> Thanks!
  


Hey, why do we need to import tensorflow here?
I am using tensorflow as backend and i am not importing it anywhere.

**Comment by shuchitajain** [comment]
Also, I am using Tensorflow 2.4.1.
The repository that I am working on:
https://github.com/Neerajj9/CSRNet-keras/issues

The dataset is given in the README

**Comment by amahendrakar** [comment]
@shuchitajain,
The GitHub repository you've linked contains multiple `.ipynb` files. 

In order to expedite the trouble-shooting process, could you please provide a minimal code snippet? Thanks!
