### ISSUE TITLE
Will Lamba.compute_output_shape change "inbound_nodes" of Lambda layer?

### ISSUE THREAD

**Issue by mjdxyr** [tensorflow/tensorflow#47977]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.4.1
- Python version:3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1
- GPU model and memory:Titan V  12G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I run x.compute_output_shape((5, 5, 5)),the inbound_nodes will become two.(x is a keras.layers.lambda)

**Describe the expected behavior**
compute_output_shape  should not change  inbound_layers

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1p1YhDb3TDXXVuf6tRFQsTIwyNLeCW8rB?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
I see that this worked correctly in TF 2.3 version. See [gist](https://colab.research.google.com/gist/ymodak/ad3f00e9109c80586c85eda364de8783/untitled580.ipynb) for more information.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210601,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/1d863266c57f1b495d7c47cab9dec21a/untitled175.ipynb)..Thanks !

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
