### ISSUE TITLE
Error building on Windows

### ISSUE THREAD

**Issue by mrry** [tensorflow/tensorflow#4798]
(Copied from @laudney's comment on #17)

> I've tried to follow your instructions. All seem to work flawlessly (for about 45min) until it failed with:
> 
> ```
> The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
> Done Building Project "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targets) -- FAILED.
> 
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj" (default target) (3) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj" (default target) (4) ->
> "H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default target) (5) ->
> (CustomBuild target) ->
>   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [H:\PycharmProjects\t
> ensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj]
> 
>     30 Warning(s)
>     1 Error(s)
> ```

**Comment by mrry** [comment]
@laudney It looks like the error (namely `"cmd.exe" exited with code 1`), happened early in the build - can you post the entire log (e.g., by adding the `/filelogger` flag to `MSBuild` and uploading the resulting `msbuild.log` as a gist)?

**Comment by laudney** [comment]
@mrry Yes. I've just done that and I've noticed it was due to "git.exe" not in my PATH. I'm trying it again and will report back.

**Comment by laudney** [comment]
@mrry New error below after 1h of compilation. Please let me know if you need the log.

"C:\src\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"H:\PycharmProjects\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj" (default target) (3) ->
(ClCompile target) ->
  H:\PycharmProjects\tensorflow\tensorflow\python\lib\core\py_func.cc(165): error C2466: cannot allocate an array of constant size 0 [H:\PycharmProjects\tensor
flow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj]

**Comment by elcombato** [comment]
exactly the same error in #4799

**Comment by mrry** [comment]
Thanks for this report! I've found the problem (a recent change to `py_func.cc`) and am working on a fix.
