### ISSUE TITLE
Invalid format in tf.math.log doc page

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#47985]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/math/log

### Clear description

<img width="1039" alt="Screen Shot 2021-03-23 at 5 12 34 AM" src="https://user-images.githubusercontent.com/8815362/112052367-6291a700-8b96-11eb-8535-c874920d66b4.png">

The example section is broken.

https://github.com/tensorflow/tensorflow/blob/e13f434909c7007b14f7930370472f26fba06f4e/tensorflow/core/api_def/python_api/api_def_Log.pbtxt#L13-L22

Maybe the above lines are invalid and markdown-style codeblock lines(```) should be removed like [tensorflow/core/api_def/python_api/api_def_Log1p.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/python_api/api_def_Log1p.pbtxt).

**Comment by amahendrakar** [comment]
@jeongukjae,
Looks like the issue is fixed in the nightly version of the documentation. 

Please check [this link](https://www.tensorflow.org/api_docs/python/tf/math/log?version=nightly) for reference. Thanks!

**Comment by jeongukjae** [comment]
@amahendrakar Thanks! I can see this issue is fixed in that link.
