### ISSUE TITLE
DOC: CONTRIBUTING.md Sanity Check guide not working

### ISSUE THREAD

**Issue by adriangb** [tensorflow/tensorflow#47989]
If I try running the [instructions in CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#running-sanity-check):

```bash
tensorflow/tools/ci_build/ci_build.sh CPU tensorflow/tools/ci_build/ci_sanity.sh
```

I get:

```
#10 1.118 /install/install_pip_packages.sh: line 21: python3.6: command not found
```

However, if I instead use the `cpu-py3.6` image, I get a bit further:

```bash
addgroup: Please enter a username matching the regular expression configured via the NAME_REGEX[_SYSTEM] configuration variable.
 Use the `--force-badname' option to relax this check or reconfigure NAME_REGEX.
```

I don't see any way for users to fix this without diving into the plethora of different Dockerfiles and scripts-calling scripts that exist in the repo.

**Comment by bhack** [comment]
We are trying to simplify/unify Dockerfiles at https://github.com/tensorflow/build/pull/21
We are also trying to improve linting integration. See https://github.com/tensorflow/tensorflow/issues/41396

I the meantime I see:
> /install/install_pip_packages.sh: line 21: python3.6: 

which branch/commit are you on? Cause on master we are on `python 3.8` as https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh#L126

**Comment by adriangb** [comment]
Just in case, I tested on the master (as of today at f1497fc92) and got the same thing. In fact, here is the call to `python3.6`:
https://github.com/tensorflow/tensorflow/blob/f1497fc92ed09a2c2bd03c586c72019d4c97dca6/tensorflow/tools/ci_build/install/install_pip_packages.sh#L21

**Comment by bhack** [comment]
Ok so it is in the image building phase. Yes this need to be fixed cause the image was still on python 3.5.

As an additional note `tensorflow/tools/ci_build/ci_sanity.sh` currently couldn't run also in our official devel image `tensorflow/tensorflow:devel`

**Comment by adriangb** [comment]
Until this is resolved, is there any way for contributors to run tests?

**Comment by angerson** [comment]
Maybe not directly at the moment, but "Ubuntu Sanity" on the PR status runs the same tests.

**Comment by adriangb** [comment]
Yes but someone working at Google has to manually trigger that AFAIK, which introduces several days of lag every time tests need to be run. Testing, especially "sanity"/linting but arguably unit tests as well, should be easy and fast to run so that developers can get feedback on their changes ASAP and iterate.

**Comment by bhack** [comment]
@angerson Just a reminder. If we are working in a Docker container these scripts require Docker in Docker and I it is not the best experience.

**Comment by bhack** [comment]
@adriangb In the meantime I will discuss this with @angerson you can look at https://github.com/tensorflow/tensorflow/pull/48291

**Comment by sachinprasadhs** [comment]
Hi, Could you please try with the latest version, since the above mentioned PR which serves your purpose is merged [here](https://github.com/tensorflow/build/pull/21). Thanks!

**Comment by dmvieira** [comment]
Same issue here... Still crashing with the same error message on main branch

**Comment by sachinprasadhs** [comment]
Could you please follow the conversation here  https://github.com/tensorflow/build/pull/21 and check if you find anything interesting for you.

**Comment by dmvieira** [comment]
Every path and file in this PR doesn't exists. I think they moved these files to some other place, but CONTRIBUTING documentation is still not working, so this BUG still open

**Comment by bhack** [comment]
Current OSS CI is:
https://github.com/tensorflow/tensorflow/blob/b9f3ad5cdd276fb5107508d027671014b3943266/.github/workflows/pylint-presubmit.yml#L43-L47

But the linting need to be aligned/fixed. See https://github.com/tensorflow/tensorflow/issues/55442

**Comment by dmvieira** [comment]
But my issue here @bhack  is not just running lint, but unit tests too...

**Comment by bhack** [comment]
> But my issue here @bhack is not just running lint, but unit tests too...

Can you just run `bazel test` for unit tests?

**Comment by dmvieira** [comment]
I got a lot of errors with this too

```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz failed: class javax.net.ssl.SSLException Tag mismatch!
ERROR: An error occurred during the fetch of repository 'tf_runtime':
   Traceback (most recent call last):
        File "/mnt/c/Users/Diogo/workspace/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz, https://github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz] to /home/diogo/.cache/bazel/_bazel_diogo/068659a64be06f79953e5b9650827913/external/tf_runtime/temp5964258185019624432/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz: Tag mismatch!
ERROR: /mnt/c/Users/Diogo/workspace/tensorflow/WORKSPACE:11:14: fetching _tf_http_archive rule //external:tf_runtime: Traceback (most recent call last):
        File "/mnt/c/Users/Diogo/workspace/tensorflow/third_party/repo.bzl", line 73, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz, https://github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz] to /home/diogo/.cache/bazel/_bazel_diogo/068659a64be06f79953e5b9650827913/external/tf_runtime/temp5964258185019624432/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz: Tag mismatch!
ERROR: no such package '@tf_runtime//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz, https://github.com/tensorflow/runtime/archive/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz] to /home/diogo/.cache/bazel/_bazel_diogo/068659a64be06f79953e5b9650827913/external/tf_runtime/temp5964258185019624432/2dcb2f2fcd53280da03fba8ce9eba9d9529a970b.tar.gz: Tag mismatch!
INFO: Elapsed time: 3.670s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by bhack** [comment]
I don't know your env status but I have a PR that it is trying to monitor the user experience of building nightly (or prepare a PR starting from the nightly branch):

https://github.com/tensorflow/tensorflow/pull/57630

Can you try to build, as in the PR, in that docker image so that we have a reproducible env to check the build?

**Comment by dmvieira** [comment]
Now it's working... I was using WSL
