### ISSUE TITLE
ERROR: cannot compute CombinedNonMaxSuppression as input #0(zero-based) was expected to be a float tensor but is a uint8 tensor 	 (while executing 'CombinedNonMaxSuppression' via Eager) ERROR: Node number 644 (TfLiteFlexDelegate) failed to invoke.

### ISSUE THREAD

**Issue by yann-pourcenoux** [tensorflow/tensorflow#47983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04/Android 10
- Mobile device if the issue happens on a mobile device: Xiaomi Redmi Note 7
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tf-nightly-gpu==2.5.0.dev20210322
- Python version: 3.8

**Describe the current behavior**
I am currently running a benchmark on android and the following error is raised:
```
ERROR: cannot compute CombinedNonMaxSuppression as input #0(zero-based) was expected to be a float tensor but is a uint8 tensor (while executing 'CombinedNonMaxSuppression' via Eager)
ERROR: Node number 644 (TfLiteFlexDelegate) failed to invoke.
```

The thing is I do not have control over the inner operations in the TFLite model. Moreover, I am already casting it into `tf.float32` when building the `tf.keras.Model`:

```
boxes_to_nms = tf.expand_dims(bboxes, axis=2)
boxes = tf.cast(boxes_to_nms, tf.float32)
scores = tf.cast(scores_to_nms, tf.float32)

nms_output = tf.image.combined_non_max_suppression(
    boxes=boxes,
    scores=scores,
    ...
    )
```

Does someone know how to deal with this ERROR, because I do not find any relevant information online and I feel quite powerless here. Thanks in advance!

**Standalone code to reproduce the issue**
I am running the benchmark using the native tool which includes TFOps and Flex Delegate that can be downloaded [here](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_arm_benchmark_model_plus_flex).

My model can be downloaded [here](https://github.com/tensorflow/tensorflow/files/6184291/model.zip)

I run the benchmark on an android divide using the following lines:
```
adb push android_arm_benchmark_model_plus_flex /data/local/tmp/benchmark
adb shell chmod +x /data/local/tmp/benchmark
adb push model.tflite /data/local/tmp/model.tflite
adb shell "/data/local/tmp/benchmark"  --graph="/data/local/tmp/model.tflite" --input_layer=input --input_layer_shape=1,800,1024,3
```

**Other informations**
The node number in the error is 644 but when I visualize the model using [netron](https://netron.app/), the CombinedNonMaxSuppression has the number 643 which is unexpected.

**Comment by yann-pourcenoux** [comment]
I don't know if you meant TF 2.4.1 or TF 2.5.0.

**In TF2.4.1**
The conversion fails and throws `IndexError: _Map_base::at. I read that this would be fixed in TF 2.5. This is why I did the conversion in TF 2.5

**In TF 2.5.0**
When I convert using TF 2.5, the conversion works even though I get the following warning `WARNING:absl:For model outputs containing unsupported operations which cannot be quantized, the 'inference_output_type' attribute will default to the original type.`

**Conversion**
```
model = load_model() # I would rather not share this

# Create Coco dataset
ds = tfds.load(name="coco/2017", split="train", data_dir="/data/datasets/tensorflow_datasets/",)
ds = ds.map(lambda obj: tf.image.resize(obj["image"], (800, 1024)))

# Transform the dataset into a representative dataset as in the TF guide
def representative_data_gen():
    for input_value in ds.batch(1).take(10):
        # Model has only one input so each data point has one element.
        yield [input_value]


# Converter
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Set the representative dataset in order to quantize the activations
converter.representative_dataset = representative_data_gen

# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]

# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# Additional tricks
converter.experimental_new_converter = True
converter.experimental_new_quantizer = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.
]

tf_lite_quant_model = converter.convert()

# saving converted model in TFLite file
with open("model.tflite", "wb") as tf_file:
    tf_file.write(tf_lite_quant_model)
```

**Comment by abattery** [comment]
converter.experimental_new_quantizer = False 

Could you try the conversion with the old quantizer?

**Comment by abattery** [comment]
@fredrec could you take a look?

**Comment by yann-pourcenoux** [comment]
Using `converter.experimental_new_quantizer = False` fixed it. Thanks!

**Comment by abattery** [comment]
@teijeong @liufengdb this issue is another example of the new quantizer's regression.

**Comment by teijeong** [comment]
can you provide difference between outputs of models regarding `converter.experimental_new_quantizer` flag? If it's only warning and the converted model works fine, then it would be fine.

Adding @MeghnaNatraj for more context

**Comment by teijeong** [comment]
If you can also provide float version of the tflite model, it would help me looking into the issue.

**Comment by liufengdb** [comment]
I couldn't find the corresponding ops in the tflite file for the two "tf.cast" operations. Could you find them in when you were reproducing that?
