### ISSUE TITLE
tf.data.experimental.snapshot should allow providing custom hash

### ISSUE THREAD

**Issue by ashahab** [tensorflow/tensorflow#47994]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Ues

**Describe the feature and the current behavior/state.**
Users may want to specify a custom hash_code to control the behavior of when snapshot enters read vs. write mode.
As an example: If snapshot is generated outside of training, and the dataset call-chain/graph is guaranteed to be unchanged,
then a simple hash function can checksum all the input files and generate a hash_code.

As long as the input dataset remains the same during training, the hash function can generate the same hash_code, and the
generated snapshots would be read. If the input dataset is different, the hash function would generate a new hash_code,
and therefore the SnapshotDataset op would generate new snapshots.
**Will this change the current api? How?**
It will expose a new optional parameter `hash_code` in the current `tf.data.experimental.snapshot` api.
**Who will benefit with this feature?**
All users of `tf.data.experimental.snapshot` who
**Any Other info.**
This extends the capability exposed in the C++ API: https://github.com/tensorflow/tensorflow/commit/cbc7f31b7d6aac81158be084201d3b3e8e346907

**Comment by tilakrayal** [comment]
@ashahab,
**tf.data.experimental.snapshot**  API  was deprecated and promoted to **tf.data.Dataset.shapshot** for the experimental endpoint. Could you please take a look at this official doc [link](https://www.tensorflow.org/api_docs/python/tf/data/experimental/snapshot) and the related `.md` [file](https://github.com/tensorflow/community/blob/master/rfcs/20200107-tf-data-snapshot.md) for the reference.
