### ISSUE TITLE
attr.s decorated keras Layers broken in keras.Sequential

### ISSUE THREAD

**Issue by moodoki** [tensorflow/tensorflow#47998]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1  (installed with miniconda)
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX1660, 6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

If a custom layer implementation uses the `@attr.s` decorated (e.g. for parameter validation), it will break its use in `Sequential`. It otherwise seems to function correctly in other usages.

Within `Sequential`, the decorated custom layer is flattened into its attributes used for creation instead of a Layer object.

**Describe the expected behavior**

Using the `@attr.s` should not break its use in `Sequential`.
`nest.flatten` in utils should keep the custom layer as a `Layer` object.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import attr

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import Model, Sequential

@attr.s(eq=False)
class TestLayer(layers.Layer):
    _n_out: int = attr.ib(validator=lambda i, a, x: x>=8)
    
    def __attrs_post_init__(self):
        super().__init__()
        self.fn = layers.Conv2D(self._n_out, 3, activation='relu')
    
    def call(self, x, **kwargs):
        return self.fn(x, **kwargs)
    

m = Sequential([TestLayer(8), layers.Dense(1)])

m.build([None, 128, 128, 3])
```

Possible cause of issue from within `Sequential` implementation:
```
from tensorflow.python.util import nest

nest.flatten(TestLayer(8)) # returns [8], should be [ TestLayer at <0x???????>]
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9c0118781b91> in <module>
     13 m = Sequential([TestLayer(8), layers.GlobalMaxPooling2D(), layers.Dense(1)])
     14 
---> 15 m.build([None, 128, 128, 3])

~/miniconda3/envs/genesis_dev/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in build(self, input_shape)
    345       if input_shape is None:
    346         raise ValueError('You must provide an `input_shape` argument.')
--> 347       self._build_graph_network_for_inferred_shape(input_shape)
    348       if not self.built:
    349         input_shape = tuple(input_shape)

~/miniconda3/envs/genesis_dev/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    515     self._self_setattr_tracking = False  # pylint: disable=protected-access
    516     try:
--> 517       result = method(self, *args, **kwargs)
    518     finally:
    519       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/miniconda3/envs/genesis_dev/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in _build_graph_network_for_inferred_shape(self, input_shape, input_dtype)
    320               raise ValueError(SINGLE_LAYER_OUTPUT_ERROR_MSG)
    321             # Keep track of nodes just created above
--> 322             track_nodes_created_by_last_call(layer, created_nodes)
    323             layer_input = layer_output
    324             outputs = layer_output

~/miniconda3/envs/genesis_dev/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in track_nodes_created_by_last_call(layer, created_nodes)
    566   prev_layers = layer._inbound_nodes[-1].inbound_layers
    567   for prev_layer in nest.flatten(prev_layers):
--> 568     if prev_layer._outbound_nodes:
    569       created_nodes.add(prev_layer._outbound_nodes[-1])

AttributeError: 'int' object has no attribute '_outbound_nodes'
```

**Comment by Saduf2019** [comment]
@moodoki 
Can you please refer to similar issues and let us know: [link](https://stackoverflow.com/questions/51181754/keras-tensorflow-convlstm2d-object-has-no-attribute-outbound-nodes)

**Comment by moodoki** [comment]
@Saduf2019 Linked issue seems unrelated, it's referring to a problem with Keras layer implementation differences but this is not the case here. I'm only using `tf.keras`. 

Furthermore, the problem is due to a different `flatten`. 
The issue with `tensorflow.python.util.nest.flatten` here is not the similarly named `tf.keras.layers.Flatten()`

`nest.flatten` is something that's internal to TensorFlow and used internally by `Sequential` to unpack dictionaries and nested lists to flat lists. From its name and implementation, it appears to be purely a python wrapper utility function. 

`layers.Flatten()` is a Keras layer that reshapes tensors.

**Comment by Saduf2019** [comment]
I am able to replicate the issue on [tf 2.4 and nightly](https://colab.research.google.com/gist/Saduf2019/4cb28eafacf7cd460672aafc490cdfc5/untitled574.ipynb) but the issue is not reproducible on tf 2.3, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/61c2cdd0a4792dd073d68ce7f802a0ea/untitled572.ipynb).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210601,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/8db11e7912a9e3084e22ff13d9b0cd0b/untitled178.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
