### ISSUE TITLE
TensorFlow Lite file Conversion 

### ISSUE THREAD

**Issue by kishorekethineni** [tensorflow/tensorflow#47999]
I have trained a Tfrecord file and converted into tflite file. I have used roboflow instructions as I don't have any knowledge on this domain. As per instructions https://gist.github.com/kishorekethineni/7b170822f27019d2f142be117f9855af I had run all the mentioned scripts exactly and generted tflite file successfully also checked tfilte file for input and output arrays worked fine there. required files: https://drive.google.com/drive/folders/1JnOp1ZXQCKR4RyNbg3BMuogJMOd9YmHg?usp=sharing

### 2. Code

https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing (GoogleColab)
(can check code here..)

!tflite_convert \
  --input_shape=1,300,300,3 \
  --input_arrays=normalized_input_image_tensor \
--output_arrays=TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3 \
  --allow_custom_ops \
  --graph_def_file=/content/models/research/fine_tuned_model/tflite/tflite_graph.pb \
  --output_file="/content/models/research/fine_tuned_model/final_model.tflite"

https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing (GoogleColab)

https://drive.google.com/drive/folders/1JnOp1ZXQCKR4RyNbg3BMuogJMOd9YmHg?usp=sharing (TensorFlow Lite file)

```

### 3. Failure after conversion
Model was not producing any detection

**Comment by kishorekethineni** [comment]
@MeghnaNatraj

**Comment by abattery** [comment]
@kishorekethineni Are you owning the original roboflow document? Is there any modification you made in the roboflow document? I would know that that the above roboflow document is used to work or not.

**Comment by kishorekethineni** [comment]
@abattery  Used the roboflow document as it is just changed file paths and num_steps to 1000 for quick train.

**Comment by kishorekethineni** [comment]
@abattery  reducing num_steps from 100000 to 1000 will affect the detection accuracy?

**Comment by abattery** [comment]
I don't know the details of the roboflow document. I would recommend discussing this with the roboflow colab author. For the accuracy problem, I think you can try some more experiments with the original parameter set.

Closing this issue for now since this looks like not an issue of the TensorFlow project.

Please reopen if you find a TensorFlow specific issue after discussing with the roboflow colab author.
