### ISSUE TITLE
2 bugs in training/input.py

### ISSUE THREAD

**Issue by oliverfunk** [tensorflow/tensorflow#480]
In the `_dtype()` method in the training/input.py file, the following code for TypeError:

      raise TypeError("Expected types to be consistent: %s vs. %s." %
                      ", ".join(x.name for x in types),
                      ", ".join(x.name for x in other_types))

should be:

      raise TypeError("Expected types to be consistent: %s vs. %s." %
                      (", ".join(x.name for x in types),
                      ", ".join(x.name for x in other_types)))

Also, when using the `tf.train.shuffle_batch_join()` method, you are suppose to pass a list of tuples of tensors, but if you pass a list of tuple and each tuple _only contains one item_, python will ignore the tuples and simply make it into a list. Thus, when the _flatten method in training/inputs.py is called, a `TypeError: 'Tensor' object is not iterable` is thrown. I suppose it's not necessarily a bug as one should know if you want to pass a tuple containing just one item, you must put a comma at the end of the tuple, but it may still may cause confusion.

Instead, _flatten could be:
```
def _flatten(tensor_list_list):
        for elm in tensor_list_list:
            if not isinstance(elm, tuple):
                raise TypeError("tensor_list_list must contain tuples.")
        return [tensor for tensor_list in tensor_list_list for tensor in tensor_list]
```

**Comment by vrv** [comment]
I have a fix out for the first issue: feel free to send us a PR for the second one!

**Comment by girving** [comment]
@vrv: If the actual bug is fixed, should we close this?  I don't think it's a TensorFlow bug that `(1)` isn't a `tuple` in Python.

**Comment by vrv** [comment]
I think it's fixed.

**Comment by chayitw** [comment]
I just met the same issue **(2)** but about using **tf.train.batch_join()** of the TF' version(0.11.0rc1).  As _**oliverfunk**_ said, i put a comma at the end of the tuple and seems work. 

Thanks!

My code is like as below:     

example_list  = [ \
        **(** img_preprocess.read_my_file_format(                  \
        filename_queue,                                                              \
        reader = tf.WholeFileReader(),                                        \
        decoder= img_preprocess.my_file_decoder_png,         \
        shape  = shape,                                                               \
        isWithLabel= False  **), )** for _ in range(read_threads) ];
