### ISSUE TITLE
gradient wrt input not working after applying tfmot.quantization.keras.quantize_model

### ISSUE THREAD

**Issue by WeiHao97** [tensorflow/tensorflow#48005]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): google colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After applying tfmot.quantization.keras.quantize_model to VGG16 model imported from keras:
1. If I do tf.gradient(loss, input_tensor) directly, it will give me None which implies no relationship between input and the loss which is not expected.
2. After I do  tf.gradient(loss, q_model.get_layer('quant_block1_conv1').input), things seem working fine. But after I pass an input with valid shape and dtype. it will give me an error complaining about the input.

**Describe the expected behavior**

All of these mentioned above did not happen to the original model.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1_UAEoZDamfmtnyiMEkMVlbdzwf9qCbwm?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

: ---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-11-dac3dfc084ae> in <module>
----> 1 _,l,grads_value = my_func2(img)

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   3822       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   3823 
-> 3824     fetched = self._callable_fn(*array_vals,
   3825                                 run_metadata=self.run_metadata)
   3826     self._call_fetch_callbacks(fetched[-len(self._fetches):])

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1468       try:
   1469         run_metadata_ptr = tf_session.TF_NewBuffer() if run_metadata else None
-> 1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
   1472                                                run_metadata_ptr)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: You must feed a value for placeholder tensor 'input_1_5' with dtype float and shape [?,224,224,3]
	 [[{{node input_1_5}}]]
	 [[Func/gradients/quant_block2_conv1/cond_1_grad/StatelessIf/then/_1388/input/_3903/_1395]]
  (1) Invalid argument: You must feed a value for placeholder tensor 'input_1_5' with dtype float and shape [?,224,224,3]
	 [[{{node input_1_5}}]]

**Comment by Saduf2019** [comment]
i am able to replicate this error on tf 2.3,2.4 and nightly, please find the [gist here.](https://colab.research.google.com/gist/Saduf2019/22e6ba2b809da57124a2ccf1286e4ea1/untitled572.ipynb)

**Comment by WeiHao97** [comment]
Any updates on this? Thanks! @jvishnuvardhan @Saduf2019

**Comment by WeiHao97** [comment]
Any updates on this? Thanks! @jvishnuvardhan @Saduf2019

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/bfca66f6c76b63367db818a314008654/untitled177.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/88d533c6bd4d49433cecf26be10214d7/untitled249.ipynb) ..Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
