### ISSUE TITLE
Multiple inputs with diffrent shapes

### ISSUE THREAD

**Issue by Mouradost** [tensorflow/tensorflow#48003]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When working with a graph we usually provide as inputs to the model a feature matrix (Batch, nb_nodes, nb_features) or (Batch, time, nb_nodes, nb_features) and adjacency matrix (batch, nb_nodes, nb_nodes) or (nb_nodes, nb_nodes)

1. differences of input shapes are different something that isn't allowed in model.fit(), model.predict() or model.evaluate() (for this we can use a custom training and evaluation step that allow us to handle the difference in shape, however, is it possible to still use model.fit() in this kind of situation?)
2. if using tf.data.Dataset.from_tensor_slices it returns `tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match:` (is it possible to create tf.data.Dataset with x as multiple inputs with diffrent shapes?)

**Will this change the current API? How?**

Flexibility in input shapes

**Who will benefit from this feature?**

Creating support for GNN

**Any Other info.**

**Comment by rmothukuru** [comment]
@Mouradost,
Inputs with different shapes can be passed to `model.fit` and `model.predict` of `Keras Models` using **`Ragged Tensors`**. Please refer [documentation of Ragged Tensor](https://www.tensorflow.org/guide/ragged_tensor?hl=en#keras) for more details. Thanks!
