### ISSUE TITLE
Allow Server-Side Encryption KMS option when uploading objects to S3 with Tensorflow

### ISSUE THREAD

**Issue by pranavpsv** [tensorflow/tensorflow#48009]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Productive systems frequently impose a requirement to use server-side encryption (SSE) to protect all data stored on S3, e.g. via [AWS KMS](https://docs.aws.amazon.com/kms/latest/developerguide/services-s3.html).

Tensorflow (and tensorboard) has an integration with S3, but it does not seem to support specifying SSE options for write operations. 

Is there a way in the current tensorflow code to specify SSE options for file uploads to S3?

If not, I'd suggest to add such a feature, e.g. by exposing an environment variable for extra arguments to S3 file upload operations (S3_UPLOAD_EXTRA_ARGS).

Current behaviour in this scenario is to issue an  error:
`tensorflow.python.framework.errors_impl.FailedPreconditionError: AWS Credentials have not been set properly. Unable to access the specified S3 location [Op:CreateSummaryFileWriter]`

when following this stock example but using an S3 bucket with SSE enabled: [link](https://www.tensorflow.org/tensorboard/get_started#using_tensorboard_with_keras_modelfit)

**Will this change the current api? How?**

This would not change the current api if the function that uploads data to S3 reads an environment variable and passes relevant information on to AWS SDK.

**Who will benefit with this feature?**

Any users of Tensorflow in production systems as they will typically use server-side encryption (e.g. kms) with S3.

**Comment by mihaimaruseac** [comment]
S3 filesystem is moving to SIG IO, as a plugin.

**Comment by pranavpsv** [comment]
> S3 filesystem is moving to SIG IO, as a plugin.

@mihaimaruseac Crossposted this issue on tensorflow/io repository

**Comment by ymodak** [comment]
Thanks for tagging the newly created thread. It's better to maintain one issue for discussion,Therefore closing this issue for now.

**Comment by pranavpsv** [comment]
Hi @ymodak @mihaimaruseac,

To get TensorFlow S3 writing to work with KMS on our productive system, I patched the TensorFlow C++ source code and built TensorFlow from source.
The GetTransferManager method in the s3_file_system.cc of the TensorFlow Release 2.4 branch was modified as follows:

```C++
std::shared_ptr<Aws::Transfer::TransferManager>
S3FileSystem::GetTransferManager(
    const Aws::Transfer::TransferDirection& direction) {
  std::shared_ptr<Aws::S3::S3Client> s3_client = this->GetS3Client();
  std::lock_guard<mutex> lock(this->initialization_lock_);
  if (this->transfer_managers_[direction].get() == nullptr) {
    Aws::Transfer::TransferManagerConfiguration config(
        this->GetExecutor().get());
    config.s3Client = s3_client;

    // Adding the following code: Allowing to enable KMS option
    const char* kmsFlag = getenv("S3_ENABLE_KMS");
    Aws::String enableKms = "0";
    if (kmsFlag) {
      enableKms = Aws::String(kmsFlag);
    }
    if (enableKms == "1") {
      config.createMultipartUploadTemplate.SetServerSideEncryption(Aws::S3::Model::ServerSideEncryption::aws_kms);
      config.uploadPartTemplate.SetSSECustomerAlgorithm("aws_kms");
      config.putObjectTemplate.SetServerSideEncryption(Aws::S3::Model::ServerSideEncryption::aws_kms);
    }     

```
The crossposted tensorflow/io issue's conclusion is that S3 support for Server Side Encryption is only likely to release after Release 2.6.

Is there interest in broadening the scope of this modification to support S3 writing with Server Side Encryption before TensorFlow 2.6?
