### ISSUE TITLE
MLIR binaries build fails due to missing dependency declaration

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#48004]
With the TF git version HEAD at 

commit b725e835c68bb50bea582cac0aceeb828d3d6ea9 (HEAD -> master, origin/master, origin/HEAD)
Author: A. Unique TensorFlower <gardener@tensorflow.org>
Date:   Mon Mar 22 22:00:12 2021 -0700

$ bazel build --copt=-UNDEBUG --linkopt='-fuse-ld=lld'  tensorflow/compiler/mlir:all

yields:

```
INFO: Analyzed 15 targets (0 packages loaded, 0 targets configured).
INFO: Found 15 targets...
ERROR: /home/uday/tensorflow-upstream/tensorflow/compiler/xla/service/gpu/BUILD:437:16: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/service/gpu:nccl_collective_thunks':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/service/gpu/nccl_all_gather_thunk.cc':
  'bazel-out/k8-opt/bin/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen/mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.h.inc'
INFO: Elapsed time: 39.406s, Critical Path: 36.14s
INFO: 329 processes: 67 internal, 262 local.
```

System information
Ubuntu Linux 20.04.02 LTS
bazel 3.7.2
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
TF configured with GPU/CUDA support

CC: @jpienaar @joker-eph

**Comment by jurahul** [comment]
This looks like a duplicate of https://github.com/tensorflow/tensorflow/issues/47386.

@bondhugula, can you try doing "bazel clean --expunge" and then rebuilding? We are tracking this issue on the bazel side in https://github.com/bazelbuild/bazel/issues/13135.

**Comment by bondhugula** [comment]
> This looks like a duplicate of #47386.
> 
> @bondhugula, can you try doing "bazel clean --expunge" and then rebuilding? We are tracking this issue on the bazel side in [bazelbuild/bazel#13135](https://github.com/bazelbuild/bazel/issues/13135).

Thanks @jurahul - clean with expunging works.
