### ISSUE TITLE
Converted Object Detection model trained with q-aware training still has fake quantization layers

### ISSUE THREAD

**Issue by FSet89** [tensorflow/tensorflow#48007]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 1.15

### 2. Code

I Trained a MobileNetV2SSD using the Object Detection API including this block:
```
graph_rewriter {
  quantization {
    delay: 0
    weight_bits: 8
    activation_bits: 8
  }
}
```

Then I exported the model for tflite using the command `python object_detection/export_tflite_ssd_graph.py 
`.
Finally, I converted to tflite using this code:
```
import tensorflow as tf 
from PIL import Image
import numpy as np 
import os
import sys

def _representative_dataset_gen(): 
    images_path = "/work/data/repr_dataset"
    if images_path is None: 
        raise Exception( 
             "Image directory is None, full integer quantization requires images directory!" 
        ) 
    imagePaths = os.listdir((images_path)) 
    for p in imagePaths: 
        image = Image.open(os.path.join(images_path, p))
        image = image.resize((300, 300)) 
        image = np.asarray(image)
        image = np.expand_dims(image, axis=1) 
        image = image.reshape(1, 300, 300, 3)
        yield [image.astype("float32")]

saved_model_path = sys.argv[1] 
input_arrays = ["normalized_input_image_tensor"] 
output_arrays = ['TFLite_Detection_PostProcess', 
    'TFLite_Detection_PostProcess:1', 
    'TFLite_Detection_PostProcess:2', 
    'TFLite_Detection_PostProcess:3']
input_shapes = {"normalized_input_image_tensor" : [1, 300, 300, 3]} 
converter = tf.lite.TFLiteConverter.from_frozen_graph(saved_model_path,input_arrays, 
     output_arrays, input_shapes) 
converter.allow_custom_ops = True 
converter.optimizations = [tf.lite.Optimize.DEFAULT] 
converter.representative_dataset = _representative_dataset_gen 


tflite_model_quant = converter.convert() 
with open('quantized.tflite', "wb") as tflite_file: 
     tflite_file.write(tflite_model_quant)
```

### 3. Failure after conversion
The converted model includes quantization/dequantization/fake quantization layers:
![quantized tflite](https://user-images.githubusercontent.com/8984671/112117585-cbd7e100-8bbb-11eb-8b20-325fb7f98365.png)
As a result, the inference time on an embedded system equipped with a NPU+NNAPI delegate is very high. I don't think this is normal. Is there a way to fix it?

**Comment by abattery** [comment]
@ethkim could you triage this issue?

**Comment by amahendrakar** [comment]
@FSet89,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by FSet89** [comment]
Is the quantization-aware training supported in the Object Detection API in TF2 (I mean the graph-rewrite block in the config file)

**Comment by FSet89** [comment]
> @FSet89,
> TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

I just tried but the graph_rewrite option seems not to work on TF2, so I cannot test quantization-aware training on TF2

**Comment by sanatmpa1** [comment]
@FSet89,

We are checking to see if this is still an issue, Can you check if this problem still persists with latest stable version of TF i.e `2.6.0`? Thanks!

**Comment by ivlydp** [comment]
> @FSet89,
> 
> We are checking to see if this is still an issue, Can you check if this problem still persists with latest stable version of TF i.e `2.7.0`? You can also take a look at this [function](https://www.tensorflow.org/api_docs/python/tf/compat/v1/mixed_precision/enable_mixed_precision_graph_rewrite) from TF for graph_rewrite and let us know if that's what you're looking for.Thanks!

Please help check. It still persists in 2.7.0. (My Result is as blow) 
![image](https://user-images.githubusercontent.com/8097474/147539479-fc99422d-4eed-49d8-829f-cb2aa2c68529.png)
