### ISSUE TITLE
No OpenCL for GPU delegate on Android 12

### ISSUE THREAD

**Issue by arturdryomov** [tensorflow/tensorflow#48001]
* Device: Google Pixel 4
* OS: Android 12 developer preview 2
* TensorFlow Lite: 2.4.0
* TensorFlow Lite GPU delegate: 2.4.0
* TensorFlow Lite support: 0.1.0

Calling `Interpreter.runForMultipleInputsOutputs` with pre-configured GPU delegate results in the following message:

```
CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
DEQUANTIZE: 
310 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
Falling back to OpenGL
```

There is no such message on Android 11 (and the same device). As a result, the executing time is higher than it was before (with OpenCL available).

**Comment by abattery** [comment]
@impjdi could you take a look at this report?

**Comment by freedomtan** [comment]
@arturdryomov FYR. On my Pixel 4 running Android 12 DP 2, I could find /vendor/lib64/libOpenCL.so and I can use `benchmark_model --use_gpu=1 ...` without problems.

**Comment by arturdryomov** [comment]
True, for some reason the native benchmark binary with `--use_gpu=true` is fine. Investigating further what happens during regular APK execution.

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
DEQUANTIZE: 
310 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Explicitly applied GPU delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
```

**Comment by impjdi** [comment]
I just flashed my Pixel 4 with Android 12 and I get:

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
64 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
```

so it looks like it's able to find the OpenCL libraries.

**Comment by arturdryomov** [comment]
Seems like we’ve found the issue. The target SDK changes the behavior.

```kotlin
targetSdkVersion(30)
```
```
I/tflite: Created TensorFlow Lite delegate for GPU.
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Initialized OpenCL-based API.
I/tflite: Created 1 GPU delegate kernels.
```
vs.
```kotlin
targetSdkVersion("S")
```
```
I/tflite: Created TensorFlow Lite delegate for GPU.
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Initialized OpenGL-based API.
I/tflite: Created 1 GPU delegate kernels.
```

**Comment by arturdryomov** [comment]
FYI — I’ve created [an Android 12 issue](https://issuetracker.google.com/issues/183419289) for this, not sure if it will produce useful results though. Can I ask some internal Google folks to reach out to the internal platform team? Might be more productive.

**Comment by arturdryomov** [comment]
YAFYI — attached a sample project and described steps to reproduce in the Android issue mentioned above.

**Comment by truboxl** [comment]
Can I ask where you set targetsdkversion 30?
There's nothing in https://github.com/tensorflow/tensorflow/search?q=targetsdkversion&type=code

I suspect something got to do with targetsdkversion > 24 behaviour in https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk

**Comment by arturdryomov** [comment]
It’s not about the TensorFlow target SDK. TensorFlow dependencies are used as-is but the client application declares the `S` target SDK. PTAL at the Google issue linked above — it has a sample project.

**Comment by arturdryomov** [comment]
@impjdi, hey, do you have ideas what might go wrong with the target SDK version? Maybe there are some internal Google folks who can elaborate on this. The Android issue is pretty much silent.

**Comment by impjdi** [comment]
We have an internal bug system and this is being investigated, but personally, I'm clueless as I don't go through any code path that does something like setting the SDK version (i.e. I have no idea when you talk about `targetSdkVersion()`).  I'll report back when I find something =/

**Comment by arturdryomov** [comment]
My current guess is that using Android 12 as a target SDK prevents applications (which are TF consumers) from linking to system binaries. As a result, OpenCL exists but cannot be linked to. When Android detects lower target SDK, rules are relaxed and the linking is allowed.

**Comment by impjdi** [comment]
Quoting some internal thread (sorry, I don't understand what these mean):
```
For Android 12 target sdk the developer must use <uses-native-library> with libOpenCL-pixel.so and libOpenCL.so.

See ENFORCE_NATIVE_SHARED_LIBRARY_DEPENDENCIES section in https://developer.android.com/about/versions/12/reference/compat-framework-changes
```

**Comment by arturdryomov** [comment]
Yep, got the same thing on the public tracker. Thanks! Gonna check if it helps.

**Comment by kumariko** [comment]
@arturdryomov Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!

**Comment by arturdryomov** [comment]
@kumariko, according [to the Google issue](https://issuetracker.google.com/issues/183419289) conversation — a manifest declaration is required to use OpenCL. It would be great if the TF AAR included such declarations so the manifest merger could propagate them to consumer applications.

**Comment by matthewn4444** [comment]
Since August API 31 is needed, so all new apps (and updates) submitted into the Play Store cannot use OpenCL anymore and have to use OpenGL instead?

**Comment by meysam-farmani** [comment]
In Android 12 and above, you must add the following code in the manifest inside the application file to add the required GPU libraries.

<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
