### ISSUE TITLE
How to pass -add_postprocessing_op=true while using tflite_convert in tensorflow2.x

### ISSUE THREAD

**Issue by vmishra2019** [tensorflow/tensorflow#48012]
How we can pass -add_postprocessing_op=true while creating PB file for tflite_convert 

python object_detection/export_tflite_ssd_graph.py --pipeline_config_path=pipeline.config --trained_checkpoint_prefix=model.ckpt-4000 --output_directory=saved_model --add_postprocessing_op=true

Above scripts should output two files In saved_model directory: tflite_graph.pb and tflite_graph.pbtxt

Above script i used in tensorflow1.13 if it need to be changed or modify please share the solution, thanks in advance

Regards
Vivek

**Comment by abattery** [comment]
Could you leave your question at the tensorflow/models repository, which owns the objection_detector scripts?
This repo is mainly for the TensorFlow project not the TF model garden.
https://github.com/tensorflow/models
