### ISSUE TITLE
Couldn't build android C++ .so libs with bazel and tensorflow as a remote dependency.

### ISSUE THREAD

**Issue by flamxi** [tensorflow/tensorflow#48014]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Source, current master branch (23.03.2021)
- TensorFlow version: Current master branch(23.03.2021), latest tag v2.4.1
- Python version: 3.8
- Bazel version (if compiling from source): 4.0.0
- GCC/Compiler version (if compiling from source):  7.5.0
- CUDA/cuDNN version: Not Used
- GPU model and memory: Not Used

**Describe the problem**
I am trying to build on C++ .so on top of tensorflow with bazel. I am trying to add tensorflow as a remote repository just like tensorflow_serving ( https://github.com/tensorflow/serving ).
I can build for native targets(linux x86_64) all fine, when I tried to build for **--config android** I got errors that android is not defined, so I copy/pasted the .bazelrc file from tensorflow, and updated .tf_configure.bazelrc. Than the build started but it is failing 
for this target: 

``` 
ERROR: /home/flamur/.cache/bazel/_bazel_flamur/8aff49c09e177f51e03fa24b3bf8aaa8/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/BUILD:486:22: Generating flatbuffer files for serialization_cc_fbs_srcs: @org_tensorflow//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs failed: (Exit 1): bash failed: error executing command 
  (cd /home/flamur/.cache/bazel/_bazel_flamur/8aff49c09e177f51e03fa24b3bf8aaa8/execroot/this_repo && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=30.0.0-rc4 \
    ANDROID_NDK_API_LEVEL=24 \
    ANDROID_NDK_HOME=/home/flamur/Android/Sdk/ndk-bundle \
    ANDROID_SDK_API_LEVEL=30 \
    ANDROID_SDK_HOME=/home/flamur/Android/Sdk \
    PATH=/home/flamur/anaconda3/envs/flamxi/bin:/home/flamur/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/flamur/bin:/home/flamur/.cargo/bin:/snap/bin:/home/flamur/anaconda3/envs/flamxi/bin:/home/flamur/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/flamur/bin:/snap/bin:/home/flamur/Documents/CLion-2020.2.4/clion-2020.2.4/bin:/home/flamur/Documents/CLion-2020.2.4/clion-2020.2.4/bin \
    PYTHON_BIN_PATH=/home/flamur/anaconda3/envs/flamxi/bin/python3 \
    PYTHON_LIB_PATH=/home/flamur/anaconda3/envs/flamxi/lib/python3.7/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; for f in external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/serialization.fbs; do bazel-out/host/bin/external/flatbuffers/flatc --scoped-enums -I ./  -c -o bazel-out/armeabi-v7a-opt/bin/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl $f; done')
Execution platform: @local_execution_config_platform//:platform
error: /home/flamur/.cache/bazel/_bazel_flamur/8aff49c09e177f51e03fa24b3bf8aaa8/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/serialization.fbs:15: 75: error: unable to load include file: tensorflow/lite/delegates/gpu/common/task/serialization_base.fbs
Target //skeleton:centernet failed to build
INFO: Elapsed time: 0.131s, Critical Path: 0.01s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

```
I checked that file **serialization.fbs** and it seems like having a relative path for this include:
```
include "tensorflow/lite/delegates/gpu/common/task/serialization_base.fbs";
```
I am guessing this could be the problem! As the error says that cannot find this file.

If you want more files like WORKSPACE or .bazelrc please mention that, I don't know if they are required at this state! 

For the target that I get this error I tested it with tensorflow as local dependency it works all fine, also with the remote dependency the non android targets are builded succesfully!

**Comment by wangtz** [comment]
Hi Flamur,

It would be great if you can provide more information on how the BUILD file was written and how your .tf_configure.bazelrc looks like.

Reading the error message above, it seems that bazel can find `tensorflow/lite/delegates/gpu/cl/serialization.fbs` but not `tensorflow/lite/delegates/gpu/common/task/serialization_base.fbs` ? 


Hi Juhyun,

Any thoughts on this or could you help re-assign to someone with more context?

Thanks,
Tiezhen

**Comment by flamxi** [comment]
Hi @wangtz 
Thanks for your reply.
This is my BUILD file content:
``` bazel
package(default_visibility = ["//visibility:public"])
#load("@org_tensorflow//tensorflow:tensorflow.bzl", "tflite_cc_shared_object", "tflite_copts", "tflite_linkopts")

cc_library(
    name = "centernet",
    srcs = glob([
        "foo.cpp",
    ]),
    hdrs = glob([
        "foo.hpp",
    ]),
    copts = [
        "-std=c++14",
    ] + select({
        "@org_tensorflow//tensorflow:android": [
            "-D__ANDROID__",
        ],
        "@org_tensorflow//tensorflow:android_arm64": [
            "-D__ANDROID__",
        ],
        "//conditions:default": [
        ]
    }),
    linkopts = [

    ] + select({
        "@org_tensorflow//tensorflow:android": [
            "-lEGL",
            "-lGLESv3",
            "-pie",
            "-lm",
        ],
        "//conditions:default": [],
    }),
    deps = [
        "@org_tensorflow//tensorflow/lite/delegates/nnapi:nnapi_delegate",
        "@org_tensorflow//tensorflow/lite:framework",
        "@org_tensorflow//tensorflow/lite:string_util",
        "@org_tensorflow//tensorflow/lite/kernels:builtin_ops",
        "@org_tensorflow//tensorflow/lite/tools/evaluation:utils",
        "@com_google_absl//absl/memory",
    ] + select({
        "@org_tensorflow//tensorflow:android_arm": [
            "@org_tensorflow//tensorflow/lite/delegates/gpu:gl_delegate",
             "@opencv//:opencv_arm",
        ],
        "@org_tensorflow//tensorflow:android_arm64": [
            "@org_tensorflow//tensorflow/lite/delegates/gpu:gl_delegate",
             "@opencv//:opencv_arm64",
        ],
        "//conditions:default": [
            "@native_opencv//:opencv",
        ],
    }),
)

```

And my tf_configure.bazelrc is:
``` bazel
build --action_env PYTHON_BIN_PATH="/home/$USER/anaconda3/envs/$USER/bin/python3"
build --action_env PYTHON_LIB_PATH="/home/$USER/anaconda3/envs/$USER/lib/python3.7/site-packages"
build --python_path="/home/$USER/anaconda3/envs/$USER/bin/python3"
build --config=xla
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --action_env ANDROID_NDK_HOME="/home/$USER/Android/Sdk/ndk-bundle"
build --action_env ANDROID_NDK_API_LEVEL="24"
build --action_env ANDROID_BUILD_TOOLS_VERSION="30.0.0-rc4"
build --action_env ANDROID_SDK_API_LEVEL="30"
build --action_env ANDROID_SDK_HOME="/home/$USER/Android/Sdk"
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by cuongvng** [comment]
For my case, I have to configure the Bazel build process to specify Android SDK and NDK path before running the `bazel build ...` commands. 
More detailed https://github.com/cuongvng/TF-Lite-Cpp-API-for-Android

**Comment by terryheo** [comment]
I guess the problem can be fixed by modifying the following file.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/cl/BUILD
```
flatbuffer_cc_library(
    name = "serialization_cc_fbs",
    srcs = ["serialization.fbs"],
    flatc_args = [
        "--scoped-enums",
        "-I ./",
    ],
    includes = [
        "//tensorflow/lite/delegates/gpu/common/task:serialization_base_cc_fbs_includes",
    ],
)
```
flatc_args need to have additional "-I" option to find `serialization_base.fbs` file. Could you try?

**Comment by flamxi** [comment]
I tried a lot of combination to pass that flag as you mentioned @terryheo but since I am not familiar with flatbuffer bazel macros, I can not find a proper way that should work, what I tried is to update the -I with just the first directory of the repository meaning ```-I //tensorflow, -I //``` but that seems like a syntax error, also tried to find and check this content: ``` "//tensorflow/lite/delegates/gpu/common/task:serialization_base_cc_fbs_includes"``` but could not find it, in current master I cannot find a lib name of that package, only ```serialization_base_cc_fbs``` at this point I don't know if  flatbuffers bazel defs, have this "feature" to include only by adding ```_includes``` at the end of package or not! Can I expect more guides from you in this area? Thanks

**Comment by flamxi** [comment]
@cuongvng thanks for your suggestions, but I already mentioned that when it comes to clone the repo locally I managed to add as a local_repository and than build against it, I am trying to build with tensorflow repo directly cloned from bazel! Thanks

**Comment by terryheo** [comment]
It worth to provide absolute path to the serialization_base.fbs with "-I" option. (later we could find proper relative path)
FYI, "//" path only works Bazel and flatc_args is directly used by flatbuffer compiler.

**Comment by flamxi** [comment]
exactly, // works only for bazel, and thats why I don't know how to begin writing the absolute path, since the repository comes from remote !

**Comment by terryheo** [comment]
Did you search $HOME/.cache/bazel ?

https://docs.bazel.build/versions/master/output_directories.html

**Comment by flamxi** [comment]
uh nice, so there will be the repository, I'll try it asap! thanks ;)

**Comment by flamxi** [comment]
It works all flawlessly now! @terryheo  thanks!
Even though I got to type hard-coded absolute paths, since $HOME and $USER were not recognized there :S.
May I ask if you have any idea how would the proper solution would be, I would gladly contribute that!

**Comment by terryheo** [comment]
That's good to hear.
Could you try if the following also works for you?

```
flatbuffer_cc_library(
    name = "serialization_cc_fbs",
    srcs = ["serialization.fbs"],
    flatc_args = [
        "--scoped-enums",
        "-I $(location //tensorflow/lite/delegates/gpu/common/task:serialization_base_cc_fbs_includes)",
    ],
    includes = [
        "//tensorflow/lite/delegates/gpu/common/task:serialization_base_cc_fbs_includes",
    ],
)
```
Please let me know if it works.

BTW, you can check the actual build command with "-s" option to Bazel. It will help to debug build issues.
```
$ bazel build -s //target
```

**Comment by flamxi** [comment]
I tried, and no it doesn't work, still the error message for the missing include!
Also wanted to ask, I couldn't find this package declaration ``` serialization_base_cc_fbs_includes ``` anywhere inside the repository, it is only used in this file we are changing!

**Comment by terryheo** [comment]
I see. I also thought it's strange.

It looks bit dirty... but could you try the following?
```
flatbuffer_cc_library(
    name = "serialization_cc_fbs",
    srcs = ["serialization.fbs"],
    flatc_args = [
        "--scoped-enums",
        "-I $$(dirname $(location //tensorflow/lite/delegates/gpu/common/task:serialization_base.fbs))/../../../../../..",
    ],
    includes = [
        "//tensorflow/lite/delegates/gpu/common/task:serialization_base.fbs",
    ],
)

```

**Comment by flamxi** [comment]
@terryheo 
I tried, I got this error:
```
ERROR: /home/flamxi/.cache/bazel/_bazel_flamur/8aff49c09e177f51e03fa24b3bf8aaa8/external/org_tensorflow/tensorflow/lite/delegates/gpu/cl/BUILD:490:22: 
in cmd attribute of genrule rule @org_tensorflow//tensorflow/lite/delegates/gpu/cl:serialization_cc_fbs_srcs: label '@org_tensorflow//tensorflow/lite/delegates/gpu/common/task:serialization_base.fbs' 
in $(location) expression is not a declared prerequisite of this rule. 
Since this rule was created by the macro 'flatbuffer_cc_library', the error might have been caused by the macro implementation.
```

**Comment by flamxi** [comment]
@terryheo Do you have any other idea we can try here!

**Comment by heeh** [comment]
@flamxi I believe this issue has been fixed in r2.6 by using `workspace_root`.
Here is the patch.
https://github.com/heeh/tensorflow/commit/bbdafc9f7e2a2564d8412dd1df7c1f0e5c3c0c05

**Comment by pkgoogle** [comment]
Hi @flamxi, did the above solution https://github.com/tensorflow/tensorflow/issues/48014#issuecomment-1027399549 worked for you?
