### ISSUE TITLE
Tensorflow C++ get_visible_devices

### ISSUE THREAD

**Issue by Shadowman82** [tensorflow/tensorflow#48015]
### System information

-   I wrote custom code
-   Windows 10 64-bit
-   Tensorflow compiled from source
-   Tensorflow v2.4
-   Python v3.8
-   Bazel v3.1
-   Visual Studio Build Tools 2019
-   CUDA 11.0

### Describe the problem
Hello, I am trying to get the visible GPU devices in my C++ program that integrates Tensorflow compiled from source. I can't find the C++ equivalent function of the Python tf.config.get_visible_devices() documented here https://www.tensorflow.org/api_docs/python/tf/config/get_visible_devices .
Is this function or a similar one implemented in C++?
I found a similar function in the GPUOptions but I got a linking error when try to building the program and I am not sure that the function is meant to read the available GPU devices.

### Source code / logs
ConfigProto* config = &options.config;
auto gpu_options = config->gpu_options();
string pi = gpu_options.visible_device_list();

Thank you,
Mauro

**Comment by Shadowman82** [comment]
A little update. I was able to read the devices once the Session is established through this code:

```
vector<DeviceAttributes> devices;
session->ListDevices(&devices);
```
But I need a similar function to read the devices before the Session is established. 
Directly with CUDA library is possible through this function:

```
cudaGetDeviceCount(&deviceCount);
for (device = 0; device < deviceCount; ++device) {
        cudaDeviceProp deviceProp;
        cudaGetDeviceProperties(&deviceProp, device);
}
```

But I want to do this using Tensorflow Library in C++ in order to not depend directly from CUDA.
Is it possible someway?
Thank you,
Regards

Mauro

**Comment by sanjoy** [comment]
Can you use `DeviceFactory::AddDevices`?

**Comment by Shadowman82** [comment]
Thank you @sanjoy for the suggestion. I saw the implementation of that function and it may be the one which I need.
More precisely, I am using this piece of code
```
vector<unique_ptr<Device>> devices;
auto gpu_factory = tensorflow::DeviceFactory::GetFactory("GPU");
if (gpu_factory) {
 gpu_factory->CreateDevices(options, "GPU", &devices);
}
```

I got this compilation error in the final application that integrates Tensorflow:

```
1>D:\Progetti\_UNSTABLE\workspace_library\sb_lib\source\sb_tensorflow.cpp(1116): message : vedere il riferimento all'istanza 'std::unique_ptr<tensorflow::Device,std::default_delete<tensorflow::Device>>' di modello classe di cui è in corso la compilazione
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(3283,25): error C2338: can't delete an incomplete type
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\memory(3284,1): warning C4150: eliminazione del puntatore al tipo incompleto 'tensorflow::Device'. Non è stato chiamato nessun distruttore
```

It may refer to the fact that the compiler cannot find the destructor of the base class of Device. I tried to export the destructor of DeviceBase through TF_EXPORT macro like I did previously for other compilation errors, but this didn't solve the issue.
Any ideas?
Thank you

**Comment by Shadowman82** [comment]
I managed to solve this issue by using another function:

    vector<string> devs_gpu;
   
    auto gpu_factory = DeviceFactory::GetFactory("GPU");
    CHECK_TF_FN_RETURN(gpu_factory->ListPhysicalDevices(&devs_gpu));

    for(int i=0; i<devs_gpu.size(); i++)
    {
        unordered_map<string, string> details;
        CHECK_TF_FN_GOTO(gpu_factory->GetDeviceDetails(i, &details));
    }
