### ISSUE TITLE
Getting error in each second step in model training in gcloud tensorflow2.3 python 3.7, error - model_lib_v2.py:651

### ISSUE THREAD

**Issue by vmishra2019** [tensorflow/tensorflow#48010]
Hi while running a training job in gcloud, continuously getting following error in each step, why this is occurring and how to resolve it

I 2021-03-23T10:34:36.455145835Z master-replica-0 Step 20900 per-step time 11.124s loss=1.705 master-replica-0 
E 2021-03-23T10:34:36.455868005Z master-replica-0 I0323 10:34:36.455145 140138105964352 model_lib_v2.py:651] Step 20900 per-step time 11.124s loss=1.705 master-replica-0 
{
 insertId: "1m02xqjg250xpg0"  
 jsonPayload: {
  created: 1616495676.455868   
  levelname: "**ERROR**"   
  lineno: 328   
  message: "I0323 10:34:36.455145 140138105964352 model_lib_v2.py:651] Step 20900 per-step time 11.124s loss=1.705"   
  pathname: "/runcloudml.py"   
 }
 labels: {…}  
 logName: "projects/tuberculosis-240217/logs/master-replica-0"  
 receiveTimestamp: "2021-03-23T10:34:39.125659068Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2021-03-23T10:34:36.455868005Z"  
}

**Comment by Saduf2019** [comment]
@vmishra2019 
Please provide minimal code such that we can reproduce the issues, can you first try to upgrade to stable version 2.4 and let us know if you face the issue.
