### ISSUE TITLE
steps_per_epoch documentation not in accordance with the tutorials on the tf website

### ISSUE THREAD

**Issue by BlueskyFR** [tensorflow/tensorflow#48019]
The documentation for the `steps_per_epoch` argument to the `tf.keras.Model.fit()` function, located [here](https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/keras/engine/training.py#L942), specifies that:

> If x is a `tf.data` dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted.

Also, the default value of `steps_per_epoch` is **None**.

In the [Load images tutorial](https://www.tensorflow.org/tutorials/load_data/images#train_a_model), the `train_ds` variable is passed to `Model.fit()` for training, and is a `tf.data.Dataset` on which several `.map()`s have been applied before:

![image](https://user-images.githubusercontent.com/25421460/112180016-74f1fc00-8bfb-11eb-8549-1dd9f00937bd.png)

Following the documentation, how can the steps (underlined in red in the picture) be displayed?

Please feel free to ask if you need any more detail!

**Comment by jvishnuvardhan** [comment]
@BlueskyFR Steps in the above example are estimated as (number of samples in your dataset / the batch size). In this example `number of samples` are 2936 and `batch_size` is 32. so ceil(2936/32) = 92. 

> When training with input tensors such as
>             TensorFlow data tensors, the default `None` is equal to
>             the number of samples in your dataset divided by
>             the batch size, or 1 if that cannot be determined.

`tf.keras.preprocessing.image_dataset_from_directory` returns a dataset object

> A tf.data.Dataset object.
> If label_mode is None, it yields float32 tensors of shape (batch_size, image_size[0], image_size[1], num_channels), encoding images (see below for rules regarding num_channels).

As it is not a `dataset` iterator that was set to be repeated indefinitely, the number of steps can be estimated.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by BlueskyFR** [comment]
@jvishnuvardhan thanks for your answer: I might have missunderstood the documentation on some points but it is not very clear in my opinion: with a `tf.data.Dataset`, should the total number of steps be displayed by `.fit()`.

In my code, `model.fit()` displays `X/Unknown` (with X being the current step), and I am trying to know why.
When I call `len(ds)` on my Dataset object, it only works if `ds.map()` was never called. The first time I call **map** on my dataset, `len(ds)` becomes unavailable so I though this was the problem.

Reading the documentation, I found no explanation to my problem: I think this part is not very clear about that behavior.

**Comment by jvishnuvardhan** [comment]
@BlueskyFR The code in the tutorial was not printing `X/unknown`. Are you talking about your code? Can you please share a standalone code to reproduce the issue?

In some other cases where data generator is used, that code will output `X/unknown` as dataset generator doesn't know how many batches are there in the data until it completes one full epoch. 

[This response](https://github.com/tensorflow/tensorflow/issues/39277) to a similar issue might help you. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@BlueskyFR [This](https://github.com/tensorflow/tensorflow/issues/36321) might help you. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Please feel free to raise any PR If you want to update any tutorial or guide. Thanks!

**Comment by BlueskyFR** [comment]
> I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Please feel free to raise any PR If you want to update any tutorial or guide. Thanks!

Sorry for the late response, I will provide a code sample to reproduce the problem.

**Comment by jvishnuvardhan** [comment]
Sure. You could also raise any PR to update the docs. Thanks!
