### ISSUE TITLE
Can't install Tensorflow for Golang

### ISSUE THREAD

**Issue by gg187on** [tensorflow/tensorflow#48017]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): go get
- TensorFlow version: 2.4.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip, conda
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version:-
- GPU model and memory: virtgl

**Describe the problem**

Can't install Tensorflow for Golang

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
~$ sudo go get github.com/tensorflow/tensorflow/tensorflow/go
[sudo] heslo pre používateľa gg187on: 
go: downloading github.com/tensorflow/tensorflow v1.15.5
go: downloading github.com/tensorflow/tensorflow v2.4.1+incompatible
go: downloading github.com/golang/protobuf v1.5.1
go: downloading google.golang.org/protobuf v1.26.0
github.com/tensorflow/tensorflow/tensorflow/go imports
    github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find module providing package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@gg187on,
Please take a look at this [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) file with the installation instructions for TensorFlow in Go.

Also, please go through issues [#39744](https://github.com/tensorflow/tensorflow/issues/39744) and [#41808](https://github.com/tensorflow/tensorflow/issues/41808) with a similar error log and check if it helps. Thanks!

**Comment by gg187on** [comment]
Tried steps from README.md and got error:

```
github.com/tensorflow/tensorflow/tensorflow/go imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find module providing package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```

**Comment by gg187on** [comment]
I tried literally everything, but it still don't want install. Always same error, I did exactly all commands as written in README.md even with optional steps, and always same...

**Comment by wiktoria-n** [comment]
I'm having exact same issue, followed the README.md as suggested above

**Comment by gg187on** [comment]
I read whole https://github.com/tensorflow/tensorflow/issues/35133#issuecomment-779766005 and it seems like Tensorflow dev can't fix their library for some time. It has always some problems.

**Comment by gg187on** [comment]
https://github.com/tensorflow/tensorflow/issues/35133#issuecomment-807404740

seems to work,...

**Comment by wiktoria-n** [comment]
> [#35133 (comment)](https://github.com/tensorflow/tensorflow/issues/35133#issuecomment-807404740)
> 
> seems to work,...

thank you, it worked perfectly for me

**Comment by allurefx** [comment]
I had the same problem, seems like the release doesn't handle the new module changes correctly. Anyway, I've put together a small script to generate the proto code, see below. Run this after you've done a go get in your module to get the tf module (basically till the point when you get the proto missing error).

# Edit these as necessary
go=~/go
ver=tensorflow@v2.4.1+incompatible

# Looks like go:generate actions expect the protos to be here
mkdir -p $go/src/github.com/tensorflow
ln -s $go/pkg/mod/github.com/tensorflow/$ver $go/src/github.com/tensorflow/tensorflow

# To trigger go:generate actions
cd $go/pkg/mod/github.com/tensorflow/$ver
chmod -R +w .
ln -s vendor/github.com/tensorflow/tensorflow/tensorflow/go/core tensorflow/go
ln -s vendor/github.com/tensorflow/tensorflow/tensorflow/go/stream_executor tensorflow/go
go mod init github.com/tensorflow/tensorflow
go generate github.com/tensorflow/tensorflow/tensorflow/go/op

**Comment by gg187on** [comment]
Ok, it seems I hit another problém, I'm not sure if it's error of documentation, but some APIs from docs seems like are not implemented. What I learned for last week is that, Golang is not machine learning ready. So if anyone want to do machine learning, I would rather recommend Python or C or even JS.

**Comment by gg187on** [comment]
Ok, it seems I hit another problem, and also it seems it's hard to do parallelism with TensorFlow lib. What I learned for last week is that, Golang is not machine learning ready. So if anyone want to do machine learning, I would rather recommend Python or C or even JS.

**Comment by giautm** [comment]
Hey @gg187on I have really setup DevContainer with TensorFlow for Go 1.16.1. You can use it right now without any issue with compiler.

https://github.com/giautm/tensorflow-go-example

FYI: DevContainer is feature of VSCode (https://code.visualstudio.com/docs/remote/containers). So, It requirements you have VSCode, Docker on your machine.

**Comment by amahendrakar** [comment]
> Ok, it seems I hit another problem

@gg187on,
Any updates regarding this issue? Could you please share the error log so that we can look into it. Thanks!

**Comment by wiktoria-n** [comment]
I am having the issue:

No such file or directory
   20 | // #include "tensorflow/c/c_api.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by amahendrakar** [comment]
> I am having the issue:

@wiktoria-n,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
