### ISSUE TITLE
RuntimeError: Input pipelines based on Queues are not supported when eager execution is enabled. Please use tf.data to ingest data into your model instead.

### ISSUE THREAD

**Issue by 438-gm-24** [tensorflow/tensorflow#48013]
OS Platform and Distribution (e.g., Linux Ubuntu 20.04): RHEL 7.7
TensorFlow version: 2.4.1
Python version: 3.8.5
CPU
NVIDIA Corporation GP102
I try to run this code
python -m CycleGAN_TensorFlow.create_cyclegan_dataset --image_path_a=folder_a --image_path_b=folder_b --dataset_name="horse2zebra_train" --do_shuffle=0

I have this error
RuntimeError: Input pipelines based on Queues are not supported when eager execution is enabled. Please use tf.data to ingest data into your model instead.

**Comment by Saduf2019** [comment]
@438-gm-24 
Can you share more details for us to analyse, simple stand alone code to replicate the issue faced or a colab gist with the code and error.

**Comment by 438-gm-24** [comment]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From project4/data_loader.py:9: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/pdiene/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From /home/pdiene/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From /home/pdiene/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:199: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/pdiene/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From project4/data_loader.py:11: __init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
WARNING:tensorflow:From project4/data_loader.py:55: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

WARNING:tensorflow:From project4/data_loader.py:66: The name tf.random_crop is deprecated. Please use tf.image.random_crop instead.

**Comment by 438-gm-24** [comment]
I update the code like this 
import tensorflow as tf

from . import cyclegan_datasets
from . import model


def _load_samples(csv_name, image_type):
    filename_queue =  tf.compat.v1.train.string_input_producer(
        [csv_name])

    reader = tf.compat.v1.TextLineReader()
    _, csv_filename = reader.read(filename_queue)

    record_defaults = [tf.constant([], dtype=tf.string),
                       tf.constant([], dtype=tf.string)]

    filename_i, filename_j = tf.io.decode_csv(
        records=csv_filename, record_defaults=record_defaults)

    file_contents_i = tf.io.read_file(filename_i)
    file_contents_j = tf.io.read_file(filename_j)
    if image_type == '.jpg':
        image_decoded_A = tf.image.decode_jpeg(
            file_contents_i, channels=model.IMG_CHANNELS)
        image_decoded_B = tf.image.decode_jpeg(
            file_contents_j, channels=model.IMG_CHANNELS)
    elif image_type == '.png':
        image_decoded_A = tf.image.decode_png(
            file_contents_i, channels=model.IMG_CHANNELS, dtype=tf.uint8)
        image_decoded_B = tf.image.decode_png(
            file_contents_j, channels=model.IMG_CHANNELS, dtype=tf.uint8)

    return image_decoded_A, image_decoded_B
def load_data(dataset_name, image_size_before_crop,
              do_shuffle=True, do_flipping=False):
     
    """
    :param dataset_name: The name of the dataset.
    :param image_size_before_crop: Resize to this size before random cropping.
    :param do_shuffle: Shuffle switch.
    :param do_flipping: Flip switch.
    :return:
    """
    if dataset_name not in cyclegan_datasets.DATASET_TO_SIZES:
        raise ValueError('split name %s was not recognized.'
                         % dataset_name)

    csv_name = cyclegan_datasets.PATH_TO_CSV[dataset_name]

    image_i, image_j = _load_samples(
        csv_name, cyclegan_datasets.DATASET_TO_IMAGETYPE[dataset_name])

    # Preprocessing:
    image_i = tf.image.resize(
        image_i, [image_size_before_crop, image_size_before_crop])
    image_j = tf.image.resize(
        image_j, [image_size_before_crop, image_size_before_crop])

    if do_flipping is True:
        image_i = tf.image.random_flip_left_right(image_i)
        image_j = tf.image.random_flip_left_right(image_j)

    image_i = tf.image.random_crop(
        image_i, [model.IMG_HEIGHT, model.IMG_WIDTH, 3])
    image_j = tf.image.random_crop(
        image_j, [model.IMG_HEIGHT, model.IMG_WIDTH, 3])

    image_i = tf.subtract(tf.compat.v1.div(image_i, 127.5), 1)
    image_j = tf.subtract(tf.compat.v1.div(image_j, 127.5), 1)

    # Batch
    if do_shuffle is True:
        images_i, images_j = tf.compat.v1.train.shuffle_batch(
            [image_i, image_j], 1, 5000, 100)
    else:
        images_i, images_j = tf.compat.v1.train.batch(
            [image_i, image_j], 1)

    inputs = {
        'images_i': images_i,
        'images_j': images_j
    }

    return inputs
but i have the same error

**Comment by Saduf2019** [comment]
@tensorflowbutler 
Cod shared is full of [indentation errors](https://colab.research.google.com/gist/Saduf2019/c94b6dd0903441e6e1e834ab1299aa93/untitled575.ipynb), please share a colab gist with issue reported or simple stand alone indented code with all dependencies such that we can replicate the issue reported.
