### ISSUE TITLE
How to convert conv3d layer ?

### ISSUE THREAD

**Issue by ahmedhajyahmed** [tensorflow/tensorflow#48023]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10  + anaconda
- TensorFlow installation (pip package or built from source): 2.4.1
- TensorFlow library (version, if pip package or github SHA, if built from source): pip package

### 2. Describe the problem
I'm using a model containing conv3d layers. I've got an error when converting the model to 
tflite saying that conv3d op is neither a custom op nor a flex op. 

**Question 1 : how to quantize a conv3d layers ?**

I tried to add "f.lite.OpsSet.SELECT_TF_OPS" to the converter supported ops. The code worked
without errors but I don't know if the conv3d layers were correctly quantized or not (to int8).

**Question2 : does adding "Select TensorFlow operators" affect  quantization ? if yes how ?**

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
model_path = os.path.join(os.getcwd(), "models", "best-model.hdf5")
    # load best weights
loaded_model = tf.keras.models.load_model(model_path)


no_quant_converter = tf.lite.TFLiteConverter.from_keras_model(loaded_model)

no_quant_tflite_model = no_quant_converter.convert()

# write the model to a tflite file as binary file
tflite_no_quant_file = os.path.join(os.getcwd(), "models", "tflite_models", "best-model_no_quant.tflite") 
with open(tflite_no_quant_file, "wb") as f:
    f.write(no_quant_tflite_model)
```

### 4. Failure after conversion
error : 
![image](https://user-images.githubusercontent.com/33780694/112195173-ef297d00-8c09-11eb-823d-49ab2942a97d.png)

**Comment by abattery** [comment]
There is a new builtin op support for conv3d in the tf-nightly. Could you try your conversion script under the tf-nightly version?

**Comment by ahmedhajyahmed** [comment]
@abattery  Thank you for your reply, when running under the tf-nightly version, I get "error: 'tf.BiasAdd' op is neither a custom op nor a flex op".
 I wonder if there is a possible method or implementation that allows me to properly quantify this layer (conv3d) because it is an essential layer in my architecture. Also, I would like to know what effect "Select TensorFlow operators" will produce in the quantize architecture, especially since conv3d is at the start of the network. In other words, if using the conv3d Select TensorFlow operator doesn't fall back to float32 operation, I can tolerate an increase in the interpreter binary size.

**Comment by abattery** [comment]
For the BiasAdd op, you can rely on the solution https://www.tensorflow.org/lite/guide/ops_select.

Select TF operators won't be quantized and the only a subset of TFLite builtin operators only quantizable. That means that conv3d operator will be only executed with float32 tensors.

**Comment by ahmedhajyahmed** [comment]
Thank you very much. Just one more thing, are there any methods that can be used to find out from a quantized (.tflite) file which operators are quantized and which operators are not? Also, is there any works in the community to quantize certain Select TF operators(specially conv3d)?

**Comment by abattery** [comment]
As far as I know, there are no on-going works for conv3d quantization for now from the community. If you can open your model in the netron, you can see there are some float ops that are always placed in between quantize and dequantize ops.

**Comment by ahmedhajyahmed** [comment]
Thanks, my goal is to test the quantization of a model that contains conv3d layers on google coral usb edge tpu (knowing that this hardware only run int8 ops). Is this possible?

**Comment by abattery** [comment]
@thaink could you share the status of hardware acceleration support for conv3d op?

**Comment by abattery** [comment]
The answer is no since TFLite quantizer won't place 8bit conv3d op. There is no 8bit tensor support from the builtin op.
Thanks for the feature request. We will consider this as a feature request for 8bit tensor support for conv3d op.

**Comment by ahmedhajyahmed** [comment]
Thank you @abattery

**Comment by thaink** [comment]
@ahmedhajyahmed Current Conv3d implementation only support float type, no quantization supported yet.
About hardware acceleration, I think it does support ege tpu.

**Comment by abattery** [comment]
Even though edge tpu supports conv3d op quantization, the TFLite quantizer won't replace float conv3d op with quantized conv3d op since there is no quantized CPU kernel for conv3d op.

**Comment by ahmedhajyahmed** [comment]
@abattery  so the 8 bit quantization is impossible and the only possible one is float 16 for GPU ?
And what do you advice me to do in my situation ?

**Comment by abattery** [comment]
@impjdi do we support float16 conv3d op in GPU delegate?

**Comment by abattery** [comment]
IMO, using float32 model with GPU delegate is an option.

**Comment by impjdi** [comment]
If you `grep` `Convolution3DAttributes` inside `//tensorflow/lite/delegates/gpu`, you will see that there is some support.  However, I don't see a legit code path how you could trigger that in a "normal" way, because I don't see the reference to any 3D op in the `gpu/common/model_builder.cc` which is the entry point for GPU IR.

**Comment by ahmedhajyahmed** [comment]
thanks guys for your help @abattery @impjdi @thaink I will close the incident now
