### ISSUE TITLE
Converted TensorFlow Lite MaskRCNN model, conversion was successful but outputs were wrong

### ISSUE THREAD

**Issue by Yu-Hang** [tensorflow/tensorflow#48025]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): '2.5.0-dev20210318'

### 2. Code

This [folder](https://drive.google.com/drive/folders/1Ot7GzI69t0ywdAhwvwaOj1VQFQfloqT4?usp=sharing) has the converted model, and also the code used to convert the model.

### 3. Failure after conversion
The conversion is successful, but the output tensors don't look right. I expect the MaskRCNN model to have four output tensors, however, this model seems to have 7 as shown in the image below. Beside, I tried inference with one image on Android, but the output tensors are either all zeros, or some meaningless numbers.
 
![Capture](https://user-images.githubusercontent.com/5137261/112209456-d90ec300-8bef-11eb-8239-27d55e6360aa.PNG)

**Comment by abattery** [comment]
For the multiple input/output naming/ordering issue, we recommend using TFLite signature def API.

SignatureDef provides meaningful/generic names for inputs/outputs which doesn't rely on specific model details. More on [SignatureDefs](https://www.tensorflow.org/tfx/serving/signature_defs#signaturedef_structure) here.
If your saved model has a defined signatureDef then it will be exported during conversion to TFLite and then you can use the Signature inputs/outputs for inference and not relying on inputs/outputs order or tensor names.

SignatureDef support is new thing available in nightly and will be available in 2.5

Then use the nightly for converting to tflite. The generated tflite file will have the SignatureDef details.
Using Python API (as an example) you can do something like

my_signature = interpreter.get_signature_runner("my_method")
results = my_signature(input_1=input_tensor_1, input_2=input_tensor_2)
print(results["my_output"])

**Comment by Yu-Hang** [comment]
So I will need to explicitly define SignatureDefs for the model first? How do I do that?

```
my_signature = interpreter.get_signature_runner("my_method")  <- where should I look for "my_method"?
results = my_signature(input_1=input_tensor_1, input_2=input_tensor_2) <- what does this line do?
print(results["my_output"])
```
You mean I can use this code to get the signature that was pre-defined in the model? Sorry I'm really confused.

@abattery @amahendrakar

**Comment by abattery** [comment]
To utilize signature def concept, the model should be exported as a TF saved model and the signature def information can be defined while exporting.

Please refer to https://www.tensorflow.org/guide/saved_model.

**Comment by amahendrakar** [comment]
@Yu-Hang,
Any updates regarding this? Could you please let us know if this is still an issue. Thanks!
