### ISSUE TITLE
Unexpected rank of mask computed by tf.keras.layers.Masking

### ISSUE THREAD

**Issue by SebastianThomas1** [tensorflow/tensorflow#48026]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.8

**Describe the current behavior**
I have batch tensors of the shape `(batch_size, n_time_steps, n_features, n_channels)`. They arise from tensors of the shape `(n_time_steps, n_features, n_channels)`, where `n_time_steps` is *not constant*. When constructing the batches, the tensors are padded to the maximum value of `n_time_steps`.

These tensors should be fed into a neural network of the following architecture:
- The inputs are masked due to the padding.
- The tensors for each timestep are fed to a time distributed convolutional block. The mask is propagated.
- The extracted features are fed to an RNN layer.

In the last layer, I run into an error due to the fact that the mask has the shape `(batch_size, n_time_steps, n_features)`, but the RNN layer expects it to have shape `(batch_size, n_time_steps)`.

**Describe the expected behavior**
According to the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Masking):
> For each timestep in the input tensor (dimension #1 in the tensor), if all values in the input tensor at that timestep are equal to mask_value, then the timestep will be masked (skipped) in all downstream layers (as long as they support masking).

So I expect the mask to have shape `(batch_size, n_time_steps)` and, in particular, tensor rank 2, regardless of the tensor rank of the input tensor.

**Standalone code to reproduce the issue**

Here is a minimal example:
```python
import tensorflow as tf

class TimeDistributedMaskPropagating(tf.keras.layers.TimeDistributed):
    """TimeDistributed layer that propagates mask."""
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.supports_masking = True
        
    def compute_mask(self, inputs, mask=None):
        return mask

n_features = 3
n_channels = 1

cnn_block = tf.keras.layers.Flatten()
estimator = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(None, n_features, n_channels)),
    tf.keras.layers.Masking(),
    TimeDistributedMaskPropagating(cnn_block),
    # tf.keras.layers.LSTM(10)
    # yields ValueError: Dimensions must be equal, but are 3 and 10
])

x1 = tf.random.uniform((4, 3, 1))       # shape: 4, 3, 1
x2 = tf.random.uniform((3, 3, 1))       # shape: 3, 3, 1

paddings = tf.constant([[0, 1], [0, 0], [0, 0]])
padded_x2 = tf.pad(x2, paddings)        # shape: 4, 3, 1
mini_batch = tf.stack((x1, padded_x2))  # shape: 2, 4, 3, 1

logits = estimator(mini_batch)          # shape: 2, 4, 3
print(logits._keras_mask)               # shape: 2, 4, 3
# mask has shape 2, 4, 3 with values
# [[[ True  True  True]
#   [ True  True  True]
#   [ True  True  True]
#   [ True  True  True]]
# 
#  [[ True  True  True]
#   [ True  True  True]
#   [ True  True  True]
#   [False False False]]]

# mask should have shape 2, 4 with values
# [[ True  True  True  True]
#  [ True  True  True False]]
```

**Other info / logs**
I have solved the problem for my use case by defining a custom masking layer, where `axis=-1` from the [original code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/core.py) in the methods `compute_mask` and `call` is replaced by `axis=[2, 3]` (in my case) or, more generally, by `axis=list(range(2, len(inputs.shape)))` ([full code](https://stackoverflow.com/a/66769283/10816965)).

If the TensorFlow team agrees with me that the current behavior of the `Masking` layer is unexpected and unintended, I would love to contribute with a pull request.

**Comment by SebastianThomas1** [comment]
Just a quick note: I provided a pull request (#48168), but I do not know how to link this issue to the pull request.

**Comment by saikumarchalla** [comment]
@SebastianThomas1   The PR which you have submitted was closed already. Please go ahead and close the issue if you don't have any concern. Thanks!

**Comment by SebastianThomas1** [comment]
Sorry for the late reply.

The issue still persists.

Yes, the PR was closed, but the only explanation given was that the data I provided is not the data the masked layer was expecting (at least to the opinion of the reviewer of the PR). However, the documentation still has no reference to this restriction.

If I understand the documentation correctly, the behavior of the implementation still is not what the documentation describes… The [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Masking#used-in-the-notebooks) says that "[...] if all values in the input tensor at that timestep are equal to `mask_value`, then the timestep will be masked […]". Moreover, the [tutorial](https://www.tensorflow.org/guide/keras/masking_and_padding?hl=en#mask-generating_layers_embedding_and_masking]) says: "Under the hood, these layers will create a mask tensor (2D tensor with shape (batch, sequence_length))". This is only true for input tensors of rank 3.

My proposed solution should work for every tensor (of rank at least 3). I do not know whether there is another reason why the PR was rejected, but I suggest that at least the documentation should be changed in order to inform the user that a mask layer expects input tensors of rank 3.

**Comment by sushreebarsa** [comment]
@SebastianThomas1 Could you please refer to this [doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Masking) and if the issue still persists then please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
