### ISSUE TITLE
NotImplementedError: Conversion for TF op 'Bucketize' not implemented.

### ISSUE THREAD

**Issue by CaptainDP** [tensorflow/tensorflow#48032]
Error encountered while converting the TensorFlow model to CoreML model:
NotImplementedError: Conversion for TF op 'Bucketize' not implemented.

TensorFlow uses the following code for training:

numeric_column = tf. Feature_column. Numeric_column (col)
buket_col = tf. Feature_column. Bucketized_column (numeric_column, boundary_dict [col])
embedding_column = tf.feature_column. Embedding_column (buket_col, K + 1)

How do I skip support for bucketized_column?

**Comment by abattery** [comment]
Could you ask a feature request for the CoreML converter instead? The missing support should be completed in the Core ML conversion side not in the TensorFlow project.
