### ISSUE TITLE
Failed to create cuSolverDN instance on GPU with 4GB

### ISSUE THREAD

**Issue by scarrazza** [tensorflow/tensorflow#48041]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- CUDA/cuDNN version: 11.0 / 8.0.4.30-1+cuda11.0
- GPU model and memory: RTX 1650 / T2000 with 4GB

**Describe the current behavior**

The following linear algebra operations:
- tf.linalg.eigh
- tf.linalg.eigvalsh
- tf.linalg.expm

when applied to a tensor with tf.complex* type in a RTX1650/T2000 GPUs with 4GB produce:
```bash
F tensorflow/core/util/cuda_solvers.cc:115] Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.
Aborted (core dumped)
```
This issue is not visible when setting a GPU memory limit or `set_memory_growth`.

**Describe the expected behavior**

No crash.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
rho = tf.constant([[ 9.14909492+1.14491749e-16j,  0.27933987-1.27970271e-01j, 
    0.25616772+1.12442776e-01j, -0.05876706-3.76165554e-01j],
    [ 0.27933987+1.27970271e-01j,  9.62506895+2.77555756e-17j,
    -0.19640032-1.72149754e-01j,  0.28515435+2.58716412e-01j],
    [ 0.25616772-1.12442776e-01j, -0.19640032+1.72149754e-01j,
    9.13383471-1.38777878e-17j,  0.18600413-2.68212068e-01j],
    [-0.05876706+3.76165554e-01j,  0.28515435-2.58716412e-01j,
    0.18600413+2.68212068e-01j,  9.58168325-5.20417043e-17j]])
tf.linalg.eigvalsh(rho)
```

**Comment by amahendrakar** [comment]
@scarrazza,
I was able to run the code on Google Colab without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3c77d7241788a2ad7753b3015386abc7/48041.ipynb).

> This issue is not visible when setting a GPU memory limit or `set_memory_growth`.

By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. You can read more about it [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). 

In this case, looks like the error was caused due to the GPU running out of memory. And as you've already mentioned the workaround would be to set a limit on the GPU memory growth. Also check similar issue [#22105](https://github.com/tensorflow/tensorflow/issues/22105) for reference.

Thanks!

**Comment by scarrazza** [comment]
@amahendrakar thanks for testing. 

However the GPUs on colab have 15gb of memory (they are usually T4). The issue I report is reproducible with low specs cards such as RTX 1650 and T2000 with 4GB of ram. I can confirm that this issue happens even if the GPU memory has 3.5GB of free memory.

**Comment by sanjoy** [comment]
@nluehr Does this mean `MinSystemMemory` needs some more adjustment, like in https://github.com/tensorflow/tensorflow/pull/44810?

**Comment by nluehr** [comment]
The required MinSystemMemory (GPU memory not claimed by TF allocator) can be controlled at runtime using the environment variable TF_DEVICE_MIN_SYS_MEMORY_IN_MB. @scarrazza can you check what minimum value of TF_DEVICE_MIN_SYS_MEMORY_IN_MB is needed to allow your model to run? As a starting point, I believe the default value TF selects for your GPU is 1050.

**Comment by scarrazza** [comment]
@nluehr thanks for the feedback. I will try to reproduce this issue, however so far with the latest 2.5.0 with CUDA 11.2, I am not able to reproduce the crash anymore.

**Comment by Qrox** [comment]
I encountered a similar error when calling `tf.linalg.solve` after loading and executing a model. However, if I call `tf.linalg.solve` before loading and executing the model, the error does not occur when I call `tf.linalg.solve` again after loading and executing the model. `set_memory_growth` does not appear to fix the problem.

If I were to guess, it's probably that model inference used up all graphic memory but does not release the memory when inference is finished, as it did not happen when I tried to reproduce it with a small model.

**Comment by sanatmpa1** [comment]
@scarrazza,

As per this [comment](https://github.com/tensorflow/tensorflow/issues/48041#issuecomment-845419240), you have mentioned that its not reproducible with `2.5.0`.  We recommend that you can try with latest stable version i.e `2.6.0` along with CUDA 11.2 and other configurations as per this [link](https://www.tensorflow.org/install/source#gpu) and let us know if the issue persists. Thanks!
