### ISSUE TITLE
incorrect number of nodes in graph - TFLite C++

### ISSUE THREAD

**Issue by mofanv** [tensorflow/tensorflow#48059]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.5
- TensorFlow installed from (source or binary): Source. Using Bazel and with [libcoral C++](https://github.com/google-coral/libcoral)
- Tensorflow version (commit SHA if source): installed from Bazel
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Coral edge TPU (USB accelerator)

**Describe the problem**
I'm using TF lite C++ working with coral edge TPU. I want to output intermediate results of the graph, so I use `lldb` debugger to examine the `interpreter.cc` and `subgraph.cc` file during `Invoke()`.

Although I'm running a model `mobilenet_v1_1.0_224_quant_edgetpu.tflite`, the command `primary_subgraph().nodes_size()` only gives a value of 2, meaning that there are only two nodes in the graph. Also, input and output sizes (and `tensors_size`) show the same. From my understanding, the number of nodes should be similar to the number of operations in the model (i.e. the mobilenet). Is there anything I missed or misunderstood? Could you please help to point it to me?

**Please provide the exact sequence of commands/steps when you ran into the problem**
1- set `COMPILATION_MODE ?= dbg`, and compile [libcoral C++](https://github.com/google-coral/libcoral) with bazel. `make CPU=k8 examples`
2- debug classify_image example with `lldb .out/k8-debug/classify_image`
3- set breakpoint `b interpreter.cc:180`
4- run `p primary_subgraph().nodes_size()` which then gives a `2`

**Comment by abattery** [comment]
It might be an intended behavior since operators, that are delegated to Coral Edge TPU, will be replaced into few partitions. Each partition consumes only one node.

**Comment by mofanv** [comment]
Thanks. Seems you're right. 

I see the coral team mentioned it on their [compiling page](https://coral.ai/docs/edgetpu/models-intro/#compiling). 
`The compiler creates a single custom op for all Edge TPU compatible ops`
