### ISSUE TITLE
Build failure: Undefined symbol error. 

### ISSUE THREAD

**Issue by dogacbasaran** [tensorflow/tensorflow#48064]
**System information**
- Linux Ubuntu 18.04:
- TensorFlow installed from source from the main
- TensorFlow version: 2.3, 2.4, 2.5
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version: 3.7.2 (installed using bazelisk release)
- GCC/Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Describe the problem**
I'm trying to build a CPU optimized Tensorflow version. I've been trying different flags in the building process to test performance for weeks. I was able to build yesterday, but today it started to give an undefined symbol error and failed in build. I tried tensorflow with branches r2.3, r2.4 and the main branch, they all failed. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure
bazel build --config=mkl --config=noaws --config=nogcp --config=nohdfs //tensorflow/tools/lib_package:libtensorflow --verbose_failures

Note that I also tried removing the options from the last bazel command such as, 
bazel build //tensorflow/tools/lib_package:libtensorflow --verbose_failures
and
bazel build --config=opt //tensorflow/tools/lib_package:libtensorflow --verbose_failures
They all failed. 

**configure output**
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /home/dogac/anaconda3/envs/MnM/bin/python3]: 

Found possible Python library paths:
  /home/dogac/anaconda3/envs/MnM/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/dogac/anaconda3/envs/MnM/lib/python3.6/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: 
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: 
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN support for Aarch64.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.

**bazel output and error**
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=179
INFO: Reading rc options for 'build' from /home/dogac/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/dogac/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/dogac/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/dogac/anaconda3/envs/MnM/bin/python3 --action_env PYTHON_LIB_PATH=/home/dogac/anaconda3/envs/MnM/lib/python3.6/site-packages --python_path=/home/dogac/anaconda3/envs/MnM/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/dogac/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/dogac/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:mkl in file /home/dogac/tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 --define=build_with_openmp=true -c opt
INFO: Found applicable config definition build:noaws in file /home/dogac/tensorflow/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /home/dogac/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nohdfs in file /home/dogac/tensorflow/.bazelrc: --define=no_hdfs_support=true
INFO: Found applicable config definition build:linux in file /home/dogac/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/dogac/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/lib_package:libtensorflow (218 packages loaded, 20353 targets configured).
INFO: Found 1 target...
ERROR: /home/dogac/tensorflow/tensorflow/compiler/tf2xla/cc/BUILD:31:21: Executing genrule //tensorflow/compiler/tf2xla/cc:xla_jit_op_gen_genrule failed (Exit 127): bash failed: error executing command 
  (cd /home/dogac/.cache/bazel/_bazel_dogac/e57be43ab57df3f949d2ecc82ad15737/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=:/usr/local/lib \
    PATH=/home/dogac/.cache/bazelisk/downloads/bazelbuild/bazel-3.7.2-linux-x86_64/bin:/home/dogac/bin:/home/dogac/.local/bin:/home/dogac/anaconda3/envs/MnM/bin:/home/dogac/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/home/dogac/.go/bin \
    PYTHON_BIN_PATH=/home/dogac/anaconda3/envs/MnM/bin/python3 \
    PYTHON_LIB_PATH=/home/dogac/anaconda3/envs/MnM/lib/python3.6/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops_gen_cc bazel-out/k8-opt/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops.h bazel-out/k8-opt/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops.cc 1 ,')
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops_gen_cc: symbol lookup error: bazel-out/host/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops_gen_cc: undefined symbol: _ZN4absl14lts_2020_09_239ByAnyCharC1ENS0_11string_viewE
Target //tensorflow/tools/lib_package:libtensorflow failed to build
INFO: Elapsed time: 688.756s, Critical Path: 228.18s
INFO: 5362 processes: 180 internal, 5182 local.
FAILED: Build did NOT complete successfully

**Comment by amahendrakar** [comment]
@dogacbasaran,
As per the [tested build configurations](https://www.tensorflow.org/install/source#cpu), could you please check if you are facing the same issue with **GCC 7.3.1** as well?

Version | Python version | Compiler | Build tools
-- | -- | -- | --
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0
tensorflow-2.2.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 2.0.0

Also, please follow the official [build from source](https://www.tensorflow.org/install/source#linux) guide while building TensorFlow. Thanks!

**Comment by dogacbasaran** [comment]
@amahendrakar I'm having trouble installing GCC 7.3.1 specifically. I downgraded my Bazel to 3.1.0, tried with GCC 7.5.0 it still failed the same way. Could you please direct me on how to install that specific version please? Thanks.

**Comment by dogacbasaran** [comment]
@amahendrakar I was able to build TF from the source. I copied my previous built /lib and /include directories into /usr/local before I failed in building. When I deleted them from the /usr/local, I was able to build again. I don't know why it works like that but that is ok for my case anyway. Thanks for your help. Cheers.
