### ISSUE TITLE
how to reduce libtensorflowlite.so size

### ISSUE THREAD

**Issue by herbiezhao** [tensorflow/tensorflow#48068]
**System information**
- OS Platform and Distribution (Linux Ubuntu 18.04):
- TensorFlow (source)
- TensorFlow version (master)
- Bazel version (3.7.2):
- ndk (r21)
- android sdk(android-30)

**Describe the problem**
when I use bazel to build libtensorflowlite.so, I got library size about 3.0M
when I use bazel to build tensorflow-lite.aar, I got aar size about 1.1M
question: How to reduce libtensorflowltie.so size, it's too big for me when i use c++ to inference model

so build command:
bazel build -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --fat_apk_cpu=arm64-v8a --config=android_arm64 //tensorflow/lite/java:tensorflow-lite

aar build command:
bazel build -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --fat_apk_cpu=arm64-v8a --config=android_arm64 //tensorflow/lite/java:tensorflow-lite

**Comment by abattery** [comment]
Please refer to https://www.tensorflow.org/lite/guide/reduce_binary_size. You can reduce your TFLite binary based on selective building. Basically, selective building will include the necessary operators for your models.

**Comment by herbiezhao** [comment]
> Please refer to https://www.tensorflow.org/lite/guide/reduce_binary_size. You can reduce your TFLite binary based on selective building. Basically, selective building will include the necessary operators for your models.

I don’t need the aar package. I need a library that can be inferred in C++. Is this method suitable for generating C++ library? And how to make selective building， are there executable scripts or input parameters that can be set?

**Comment by abattery** [comment]
You can build your own selective built C++ TensorFlow Lite library only under the bazel development environment.

For example,

```
load(
    "//third_party/tensorflow/lite:build_def.bzl",
    "tflite_custom_cc_library",
)

# A selective built tflite for testing.
tflite_custom_cc_library(
    name = "custom_tflite_lib",
    models = [
        "first_model_tflite_path_under_bazel",
        "second_model_tflite_path_under_bazel",
    ],
)
```

**Comment by herbiezhao** [comment]
I imitated the build_aar.sh file and created a bash file. In bash, I added a function that can compile the C++ library correctly. The library is very small, only 162k, but when I use this library to inference, there are many API functions that can’t be found. 

**Added function:**
function generate_tflite_cc {
  pushd ${TMP_DIR} > /dev/null
  # Generate the BUILD file.
  message=(
    'load("//tensorflow/lite:build_def.bzl", "tflite_custom_cc_library")'
    ''
    'tflite_custom_cc_library('
    '    name = "custom_tflite_lib",'
  )
  message+=('    '$(generate_list_field "models" $MODEL_NAMES))
  message+=(
    ')'
    ''
  )
  printf '%s\n' "${message[@]}" >> BUILD

  # Build the aar package.
  popd > /dev/null
  bazel  build -c opt --cxxopt='--std=c++11' \
    --config=${CONFIGS}\
    --fat_apk_cpu=${TARGET_ARCHS} \
    --crosstool_top=//external:android/crosstool \
    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
    //tmp:custom_tflite_lib
}

**NDK build error:**
*.cpp:537: undefined reference to `tflite::Interpreter::SetNumThreads(int)'
*.cpp:543: undefined reference to `tflite::Interpreter::Invoke()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_PAD()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_DEQUANTIZE()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_AVERAGE_POOL_2D()'
libcustom_tflite_lib.so: undefined reference to `tflite::MutableOpResolver::AddBuiltin(tflite::BuiltinOperator, TfLiteRegistration const*, int)'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_PACK()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_TRANSPOSE_CONV()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_DEPTHWISE_CONV_2D()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_ADD()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_RELU6()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_CONCATENATION()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_RESIZE_BILINEAR()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_RELU()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_SPACE_TO_BATCH_ND()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_CONV_2D()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_SHAPE()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_BATCH_TO_SPACE_ND()'
libcustom_tflite_lib.so: undefined reference to `tflite::ops::builtin::Register_STRIDED_SLICE()'

**Comment by abattery** [comment]
Looks like the above custom built script strips out all the operators from the generated library file. I would recommend using the bazel based solution for this case, which is verified working.

**Comment by herbiezhao** [comment]
I put
"tflite_custom_cc_library(
    name = "custom_tflite_lib",
    models = [
        "model1.tflite",
        "model2.tflite",
    ],
)" into tensorflow/lite/BUILD, and build again, I got the same library, and inference with same error.

I am not familiar with bazel build, could you provide a script that can be directly executed? TKS

**Comment by abattery** [comment]
Please refer to the following document for the bazel build environment:

https://www.tensorflow.org/lite/guide/build_android#set_up_build_environment_without_docker

And then run the following command and you can find the generated artifact file paths in the screen:

```
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite:custom_tflite_lib
```

**Comment by herbiezhao** [comment]
I can generate so, but this so cannot be used normally (missing operators).
How can i fix this problem?

**Comment by Zakria96** [comment]
Use the code below ...This will convert frozen graph into tflite and reduce the size of your tflite model... just provide the path of the frozen graph and run the following code:

import logging
logging.getLogger("tensorflow").setLevel(logging.DEBUG)

import tensorflow as tf
from tensorflow import keras
import numpy as np
import pathlib

#conversion of faster_rcnn_inception_v2_coco_model frozen_inference_graph.pbin to tflite model

import tensorflow as tf
import os 

os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'


#In place of frozen_inference_graph.pb you provide the path of your frozen graph... don't change anything else and run the code.
#you will get reduced size tflite model which will be equal to 1/4 size of your model.

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("frozen_inference_graph.pb", ["image_tensor"], ["detection_classes", "detection_scores", "detection_boxes", "num_detections"])
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
model = converter.convert()

tflite_models_dir = pathlib.Path("model/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)
tflite_model_file = tflite_models_dir/"mnist_model.tflite"
tflite_model_file.write_bytes(model)


#To Quantize the model on Export, Set the optimizations flag to optimize for size

converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
tflite_model_quant_file = tflite_models_dir/"mnist_model_quant.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)

**Comment by abattery** [comment]
Did you correctly put the models arguments in your BUILD rule? Could you share how to declare your custom library in the BUILD file?

@thaink

**Comment by thaink** [comment]
+1 We need more explanation about how you build it. Where did you put your models? If you modified the  tensorflow/lite/BUILD, the models should better be copied there.

**Comment by herbiezhao** [comment]
Modified in the tensorflow/lite/BUILD:
```
load("//tensorflow/lite:build_def.bzl", "tflite_cc_shared_object", "tflite_copts", "tflite_copts_warnings", "tflite_custom_cc_library")
tflite_custom_cc_library(
    name = "custom_tflite_lib",
    models = [
        "model1.tflite",
        "model2.tflite",
    ],
)
```
I put model1.tflite and model2.tflite into the path "tensorflow/lite".
Execution: 
`bazel build -c opt --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --fat_apk_cpu=arm64-v8a --config=android_arm64 //tensorflow/lite:custom_tflite_lib`

I got:
`-r-xr-xr-x 1 xxxx  xxxx  162K 3月  29 09:17 bazel-bin/tensorflow/lite/libcustom_tflite_lib.so`

**Comment by abattery** [comment]
@thaink any thoughts on this?

**Comment by thaink** [comment]
Seems like tflite_custom_cc_library does not meant to generate a standalone .so library but to generate a dependency for using in bazel build only.

@herbiezhao At the end of tensorflow/lite/BUILD file, in the "deps" file for the rule "tensorflowlite", could you:
- remove ":framework",
- replace "//tensorflow/lite/kernels:builtin_ops_all_linked", with ": custom_tflite_lib",
and build the //tensorflow/lite:tensorflowlite instead?

**Comment by herbiezhao** [comment]
@thaink  I can use your method to compile the library, but the size of the library has not decreased. The size is the same as the normal compilation
`-r-xr-xr-x 1 xxxx xxxx 3.0M  3.29 13:51 bazel-bin/tensorflow/lite/libtensorflowlite.so`

**Comment by thaink** [comment]
The problem turn to be the list in -exported_symbols_list is too inclusive. It include all builtin and custom ops definition.
@herbiezhao will the C api work for you?

**Comment by herbiezhao** [comment]
I will consider using the C api, but is C++ compilation still possible? Because building the aar package can greatly reduce the size of the library.

**Comment by thaink** [comment]
Do you mean the size of the aar file or the so file inside it? the aar file might have been compressed so it should be smaller.

**Comment by herbiezhao** [comment]
The size of the aar file is 635KB, and the size of so file in aar is 1384KB. So I think there should be a way to achieve compression.

**Comment by avroshk** [comment]
Hi, I am trying out the custom C Lib using `tflite_custom_c_library`. Is there an example that might guide me to troubleshoot the custom c_api lib? Here's what I am trying on 2.5.0-rc0:

1.  Added the following to `tensorflow/lite/c/BUILD`
```
tflite_custom_c_library(
    name = "custom_tensorflowlite_c",
    models = [
        "model.tflite"
    ]
)
``` 
2. Ran `bazel build -c opt //tensorflow/lite/c:custom_tensorflowlite_c `
```logs
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=178
INFO: Reading rc options for 'build' from /tensorflow_src/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /tensorflow_src/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /tensorflow_src/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /tensorflow_src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /tensorflow_src/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /tensorflow_src/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //tensorflow/lite/c:custom_tensorflowlite_c (1 packages loaded, 86 targets configured).
INFO: Found 1 target...
Target //tensorflow/lite/c:custom_tensorflowlite_c up-to-date:
  bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.a
  bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.pic.a
  bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so
INFO: Elapsed time: 0.316s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```  
3. However, when I try to link `libcustom_tensorflowlite_c.so` I get the following error: 
``` 
cc main.c -I/tensorflow_src/tensorflow/lite/c -I/tensorflow_src \
-Wl,-rpath=/tensorflow_src/bazel-bin/tensorflow/lite/c \
-L/tensorflow_src/bazel-bin/tensorflow/lite/c -lcustom_tensorflowlite_c -o test-custom-model

/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::DefaultErrorReporter()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::AllocateTensors()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `vtable for tflite::MutableOpResolver'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::InterpreterBuilder::operator()(std::unique_ptr<tflite::Interpreter, std::default_delete<tflite::Interpreter> >*)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::InterpreterBuilder::~InterpreterBuilder()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::MutableOpResolver::AddAll(tflite::MutableOpResolver const&)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::FlatBufferModel::VerifyAndBuildFromBuffer(char const*, unsigned long, tflite::TfLiteVerifier*, tflite::ErrorReporter*)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::Invoke()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::~Interpreter()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::FlatBufferModel::VerifyAndBuildFromFile(char const*, tflite::TfLiteVerifier*, tflite::ErrorReporter*)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::SetNumThreads(int)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::NnApiDelegate()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::InterpreterBuilder::InterpreterBuilder(tflite::Model const*, tflite::OpResolver const&, tflite::ErrorReporter*)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::FlatBufferModel::~FlatBufferModel()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::CreateOpResolver()'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::ResizeInputTensor(int, std::vector<int, std::allocator<int> > const&)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::delegates::InterpreterUtils::InvokeWithCPUFallback(tflite::Interpreter*)'
/tensorflow_src/bazel-bin/tensorflow/lite/c/libcustom_tensorflowlite_c.so: undefined reference to `tflite::Interpreter::ModifyGraphWithDelegate(TfLiteDelegate*)'
collect2: error: ld returned 1 exit status 
```  

I'll really appreciate some direction! Thanks!

**Comment by thaink** [comment]
@avroshk Can you try in `deps` field of `tensorflowlite_c` in tensorflow/lite/c/BUILD:
replace:
":c_api",
":c_api_experimental",
with 
`: custom_tensorflowlite_c` , 
and build the tensorflowlite_c instead. Please remember to add build config for android if you are doing so.

**Comment by avroshk** [comment]
Thank you! That did it. I am currently testing on linux. When built using my test model, libtensorflowlite_c.so file size dropped from 2.9M to to 351K

**Comment by avroshk** [comment]
@thaink One of my models uses one of select TF ops (FlexSelu). Is there a way to build the c_api lib with flex delegate but only include the required ops? I found a C++ example: https://www.tensorflow.org/lite/guide/ops_select#c

**Comment by thaink** [comment]
You can follow https://www.tensorflow.org/lite/guide/reduce_binary_size and extract the so file for flex delegate in tensorflow-lite-select-tf-ops.aar

**Comment by jinfagang** [comment]
Hi, does there a way in CMake? I am using the minal example to build my app, I don't want change any code in tensorflow_src, is there a way to do it to shinrk down the tensorflowlite.so size? BTW, I using staticlib for tflite.a, it was 780M huge!!
