### ISSUE TITLE
Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow

### ISSUE THREAD

**Issue by Adhithya-tech** [tensorflow/tensorflow#48072]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.2
- Are you willing to contribute it (Yes/No):Wish I was smart enough

**Describe the feature and the current behavior/state.**
Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Easy switch and tf wll become as competant as pytorch
**Any Other info.**
Nope, just that

**Comment by ymodak** [comment]
You may want to post this issue now [tf-onnx](https://github.com/onnx/onnx-tensorflow/issues) repo as a feature request since the `runtime error` hits from tf-onnx codebase.
