### ISSUE TITLE
Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow

### ISSUE THREAD

**Issue by Adhithya-tech** [tensorflow/tensorflow#48071]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):conda
- TensorFlow version (use command below):2.2
- Python version:3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Adhithya-tech** [comment]
@tensorflowbutler Nice

**Comment by amahendrakar** [comment]
@Adhithya-tech,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by Adhithya-tech** [comment]
@amahendrakar I think 

> This is a known limitation, as seen in notes section of https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status_v1_7_0.md.

This should solve it

**Comment by Adhithya-tech** [comment]
Anyways, it's basically converting a faster RCNN model to tensorfow using onnx in between

**Comment by amahendrakar** [comment]
> Anyways, it's basically converting a faster RCNN model to tensorfow using onnx in between

Without a sample code it would be difficult for us to debug the issue. Hence, could you please provide a minimal code snippet to reproduce the issue or share the Python script/notebook you are running. Thanks!

**Comment by mohammedayub44** [comment]
@amahendrakar  

Here is one text boundary detection model I'm using. Let me know if this helps - 

Install ONNX-Tensorflow

`git clone git@github.com:onnx/onnx-tensorflow.git && cd onnx-tensorflow`
`pip install -e .`

Code snippet: 
Model - [Link](https://1drv.ms/u/s!Astr8XJs2VCYge02Is9jjtWzpec3aA?e=88EZTP)

```python
import cv2
import torch
import numpy as np
from skimage import io
import sys
sys.path.append("path/to/cloned/folder/onnx-tensorflow")
import onnx
from onnx_tf.backend import prepare


# Load the ONNX file
model = onnx.load('onnx_export/detect2.onnx')  #Model File is provided in this above link

# Prepare the Image Input

img = io.imread(img_path)      # Any google image with text on it will do.
img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
img = np.array(img)
img = img.copy().astype(np.float32)
img -= np.array([0.485 * 255.0, 0.456 * 255.0, 0.406 * 255.0], dtype=np.float32)
img /= np.array([ 0.229 * 255.0, 0.224 * 255.0, 0.225 * 255.0], dtype=np.float32)

x = torch.from_numpy(img).permute(2, 0, 1)  # Converts [h, w, c] to [c, h, w]
x = Variable(x.unsqueeze(0))                           # Converts [c, h, w] to [b, c, h, w]

# Import the ONNX model to Tensorflow
tf_rep = prepare(model)

# Run the forward pass
detections, features = tf_rep.run(x)   # This function give error as stated in title

```

Thanks !

**Comment by alexispascual** [comment]
@Adhithya-tech, have you resolved this issue with converting a Torch FasterRCNN model to TF through ONNX? Through some digging, the error is caused by the Resize op that the FasterRCNN model does regardless of the backbone. Buried within the `GeneralizedRCNNTransform` class is this `interpolate` method call:

```
image = torch.nn.functional.interpolate(image[None], size=size, scale_factor=scale_factor, mode='bilinear',
                                            recompute_scale_factor=recompute_scale_factor, align_corners=False)[0]
```

The key is to set `align_corners` to `True` and retrain the model.

**Comment by mmeendez8** [comment]
I am also experiencing the same error. I am using [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) pytorch framework. And as @alexispascual pointed interpolate function is also the problem:

https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/ops/wrappers.py#L26

I fixed the operation to use those values:
```python
mode='bilinear'
align_corners=True
return F.interpolate(input, size=size, scale_factor=scale_factor, mode=mode, align_corners=align_corners)
```

but I am still getting the same error:

RuntimeError: in user code:

```
    /opt/miniconda3/envs/tf_exporter/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /opt/miniconda3/envs/tf_exporter/lib/python3.8/site-packages/onnx_tf/backend.py:328 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /opt/miniconda3/envs/tf_exporter/lib/python3.8/site-packages/onnx_tf/handlers/handler.py:58 handle  *
        cls.args_check(node, **kwargs)
    /opt/miniconda3/envs/tf_exporter/lib/python3.8/site-packages/onnx_tf/handlers/backend/resize.py:125 args_check  *
        exception.OP_UNSUPPORTED_EXCEPT(
    /opt/miniconda3/envs/tf_exporter/lib/python3.8/site-packages/onnx_tf/common/exception.py:50 __call__  *
        raise self._func(self.get_message(op, framework))

    RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.

```

**Comment by putizi-super** [comment]
I spent a lot on this issue,too.
