### ISSUE TITLE
No code size difference between MicroInterpreter and AllOpsResolver 

### ISSUE THREAD

**Issue by ocaff1** [tensorflow/tensorflow#48073]
@tensorflow/micro
Hi,

I do not see any code size reduction while using microInterpreter with a selection of usefull operators versus the full ops list.
For a quite simple network the code size for TFlite runtime is 160KBytes. Which is quite huge compared to what it claims (16KB for CM3!).
Can you explain this behavior?
Thank you,
OC

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Unbuntu 1804
- TensorFlow installed from (source or binary): Anaconda
- Tensorflow version (commit SHA if source): 2.4.1
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): tflite micro

**Description of the problem**

My TFLITE model is a 12 layers network of 52000 bytes obtained with full integer (int8) quantization.
All application code, except TFLite stuff is around 8KBytes. TFLite code is around 160KB.

- "Full" operators version is done with:
_static tflite::AllOpsResolver resolver;
static tflite::MicroInterpreter static_interpreter( model, resolver, tensor_arena, kTensorArenaSize, error_reporter);_

=> Code size:
.text                **164818**   
.rodata              124764    

- "Reduced" version
_static tflite::MicroMutableOpResolver<5> micro_op_resolver;
  micro_op_resolver.AddConv2D();
  micro_op_resolver.AddDepthwiseConv2D();
  micro_op_resolver.AddAveragePool2D();
  micro_op_resolver.AddReshape();
  micro_op_resolver.AddFullyConnected();
  static tflite::MicroInterpreter static_interpreter(model, micro_op_resolver, tensor_arena, kTensorArenaSize, error_reporter);_

=> Code size:
.text                **165442**     (Even bigger!)
.rodata              124816    

** Compilation **
Compilation of code is done with linux gcc
Flags: 
-Os 
-DTF_LITE_STATIC_MEMORY 
-DNDEBUG 
-DTF_LITE_DISABLE_X86_NEON

**Comment by napoleonwar** [comment]
I have a smiliar problem. I want to implement it to arm, so I am using ARM compiler. When I tried to compile the helloworld example from tflite micro, it gives me a hex file for over 300KB...

**Comment by Saduf2019** [comment]
@ocaff1 
Please share simple stand alone code or a colab gist with the issue reported.

**Comment by ocaff1** [comment]
Hi, 

The issue is solved when using a **static lib.** 
All unused objects are then removed at link for the code with MicroMutableOpResolver.
=> Code size
.text                 **51874**      
.rodata             61320     

My mistake was to compile all the tensorflow sources with application ones. I though compiler/linker was able to remove the unused part automatically. It seems not.

OC.

**Comment by Saduf2019** [comment]
@ocaff1 
Please move this issue to closed status as its resolved.
