### ISSUE TITLE
Pow layer is not available when fallback quantized conversion to tflite

### ISSUE THREAD

**Issue by janoslim** [tensorflow/tensorflow#48074]
I used tfliteConverter to convert DPED network to tflite and it has the Pow layer inside.
When I tried tflite quantization conversion with default optimization with fallback,
pow layer is not available to run because the input of Pow layer is dequantized but the parameter of pow layer is not dequantized and tflite return error about the two of them have different data type (float != uint).
Thank you.

**Comment by abattery** [comment]
@fredrec could you take a look?

**Comment by amahendrakar** [comment]
@janoslim,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, a minimal code snippet and the dataset you are using. Thanks!

**Comment by janoslim** [comment]
I am using tensorflow 2.4.0 in google colab.
My source codes are,
```
import cv2
import os
import numpy as np
import tensorflow.compat.v1 as tf

EXPORT_DIR = "./DPED_quant_fallback.tflite"

img_path = './0.jpg'

def representative_data_gen():
    image = tf.io.read_file(img_path)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [1, 9437184])
    image = tf.image.convert_image_dtype(image, tf.float32)
    yield [image]

converter = tf.lite.TFLiteConverter.from_frozen_graph(input_arrays=["Placeholder"],
                                                    graph_def_file="./frozen_DPED-r1.13.pb",
                                                    output_arrays=["generator/add_32"],
                                                    input_shapes={"Placeholder":[1,9437184]})

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
# converter.inference_input_type = tf.uint8
# converter.inference_output_type = tf.uint8
```

**Comment by daverim** [comment]
Hi, could you please try using `converter.experimental_new_quantizer = True` before `convert()`, as I believe that error is fixed in the new quantizer.

`!pip install tf-nightly` to use the new flag.

**Comment by amahendrakar** [comment]
@janoslim,
Any updates regarding this?

I was able to run the code without any issues on the latest TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7611451e11d1630196065645cd1c733d/48074.ipynb). Thanks!

**Comment by janoslim** [comment]
Hello @amahendrakar ,
I'm sorry for the late reply. 
I think it works well. 
Thanks a lot!!.
