### ISSUE TITLE
Tensorflow / TensorFlow Lite issue when compiling

### ISSUE THREAD

**Issue by Sunkian** [tensorflow/tensorflow#48076]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS, Big Sur, version 11.2.2
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 2.4.1
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: pip under venv
- GPU model and memory: AMD Radeon Pro 5300M 4 Go ; Intel UHD Graphics 630 1536 Mo

**Describe the problem**
I am trying to run a code provided by a user on Github, that deals with .tflite models. I asked to other people to try it (same os, same version of python / tensorflow) and have been able to compile it and to get the output, while I endlessly get an error. I also tested the code on another Mac (Catalina + python 3.8) and that works. I did not find any source of relevant information on the internet to solve the issue. I'm pretty sure it has something to do with tensorflow.
Here's the error : 
  File "/Users/username/Desktop/Face_mask_detector/my3.8/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 423, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Got value of type STRING but expected type FLOAT32 for input 0, name: serving_default_input:0 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```git clone https://github.com/tanhouren/Face_mask_detector```
```cd Face_mask_detector``` 
```python3.8  --version```
```python3.8 -m venv my3.8```
```source my3.8/bin/activate```
``` pip install tensorflow opencv-python``` 
```python --version```
```python main.py```

**Any other info / logs**

**Comment by jvishnuvardhan** [comment]
@Sunkian I exactly followed all the commands you listed and I didn't face that error. The code was running well initially and during inference I faced `Segmentation fault` and the code crashed.

```
python main.py 
Importing library. This might take a while...
Make sure your surrounding is bright
INFO: Start inference
Segmentation fault: 11
```

I don't think this is an error from TF. As i am not sure about their model, i think it is better if you raise an issue with that repository. May be the model was expecting huge memory or something wrong in the inference part of the code. I saw the inference was taking longer (like 10-15 sec) before crashing.

I am closing this issue as this was not related to any TF example from TensorFlow website. Thanks!
