### ISSUE TITLE
How to enable Multiple Object Tracking in tflite?

### ISSUE THREAD

**Issue by cristiandapp** [tensorflow/tensorflow#48085]
Hello everyone, I'm new here. I would like to know how can I enable realtime object tracking in tflite example for android(object detection). I need to count objects in real time with a moving camera. I've read older versions tflite allowed tracking on android, but now I'm confused about that. Can you help me? please

**Comment by abattery** [comment]
Please refer to the following document. This document explains how to enable object detection through TFLite.
https://www.tensorflow.org/lite/examples/object_detection/overview
