### ISSUE TITLE
Issue related to goldeneye DOS attack

### ISSUE THREAD

**Issue by Yakshith-Ramesh** [tensorflow/tensorflow#48098]
I have been seeing this below error when I run the final command, can anyone help me fix it.

Exception AttributeError: "'NoneType' object has no attribute 'terminate'" in <bound method Striker.__del__ of <Striker(Striker-2, initial)>> ignored

Shutting down GoldenEye
![image](https://user-images.githubusercontent.com/64961683/112573985-7c0a4b80-8e41-11eb-9432-477ae4a81714.png)
@jan Seidl @jseidl @giancluciano @samueloph

**Comment by Saduf2019** [comment]
@Yakshith-Ramesh 
Can you please paste the error logs for us to look into the issue.

**Comment by Yakshith-Ramesh** [comment]
> @Yakshith-Ramesh 
> Can you please paste the error logs for us to look into the issue.

Hi, thanks for responding. The error is shown at the bottom of screen as shown in the picture. There's no logs associated with the errors.

**Comment by Saduf2019** [comment]
@Yakshith-Ramesh 
Please paste the error in text format, it would be difficult for users with similar error to search and us to look it up.

**Comment by Yakshith-Ramesh** [comment]
> @Yakshith-Ramesh
> Please paste the error in text format, it would be difficult for users with similar error to search and us to look it up.

I am sorry about that. The error is as below 
Exception AttributeError: "'NoneType' object has no attribute 'terminate'" in <bound method Striker.__del__ of <Striker(Striker-2, initial)>> ignored

Shutting down GoldenEye

[GoldenEYE error.txt](https://github.com/tensorflow/tensorflow/files/6209586/GoldenEYE.error.txt)

**Comment by Saduf2019** [comment]
@Yakshith-Ramesh 
This is not a tensorflow related issue.

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
