### ISSUE TITLE
GPU device not found (Google colab)

### ISSUE THREAD

**Issue by alex-sokolov2011** [tensorflow/tensorflow#48096]
I still got the same error after

```
pip install tf-nightly-gpu

%tensorflow_version 2.x  
import tensorflow as tf  
device_name = tf.test.gpu_device_name()  
if device_name != '/device:GPU:0':
   raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```
in output:
_**SystemError Traceback (most recent call last)

in ()
3 device_name = tf.test.gpu_device_name()
4 if device_name != '/device:GPU:0':
----> 5 raise SystemError('GPU device not found')
6 print('Found GPU at: {}'.format(device_name))

SystemError: GPU device not found**_

but comand
`!nvidia-smi`
get me:
**_NVIDIA-SMI 460.56 Driver Version: 460.32.03 CUDA Version: 11.2_**

**Comment by ymodak** [comment]
This is because colab hosts cuda 11.0 currently. Generally colab uses latest stable TF compatible cuda version (currently TF 2.4 and cuda 11.0)
We can expect colab using cuda 11.2 once TF 2.5 is released.
```python
!nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by alex-sokolov2011** [comment]
@ymodak thank you so much. You are damn right, i have got the same output. But, but how does this information solve my problem?
I have already seen this cause in other threads, but have not found working solutions to downgrade to CUDA = 10.0.0 for Colab.

**Comment by amahendrakar** [comment]
@alex-sokolov2011,
I was able to run the given code snippet without any issues using TF v2.4.1, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/76e1162458ebc4e287af31ab765cbdc1/48096.ipynb). Thanks!

**Comment by ymodak** [comment]
@alex-sokolov2011  Google colab hosts latest stable TF version by default (TF 2.4.1 with gpu support). Thus you don't need to install tf explicitly neither use tf 2.x magic function. You can simply try ;
```python
import tensorflow as tf
device_name = tf.test.gpu_device_name()  
if device_name != '/device:GPU:0':
   raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```

**Comment by alex-sokolov2011** [comment]
@amahendrakar and @ymodak thank you so much

 That was real mystery, but now GPU ON. [here my test ](https://colab.research.google.com/drive/1uUdcdcuCUCpVE9Pkz16Hr9KgAXGIwMzA?usp=sharing).
 Sorry that I bothered you with that discussion.
