### ISSUE TITLE
Error Running cifar10_train.py in Ver 0.6.0 

### ISSUE THREAD

**Issue by rob-rowe** [tensorflow/tensorflow#481]
The cifar-10 demo ran fine under 0.5.0 but gives errors under 0.6.0 (I rolled back to 0.5.0 and confirmed this). Also cifar10_multi_gpu_train.py works under 0.6.0 as well as 0.5.0.  The output I'm getting when running cifar10_train.py in 0.6.0 is attached. I'm running under Ubuntu 14.04.
[error.txt](https://github.com/tensorflow/tensorflow/files/59525/error.txt)

**Comment by girving** [comment]
Apologies: we've noticed this internally and fixing it.

**Comment by sherrym** [comment]
Fixed today. Will be available in next release.
