### ISSUE TITLE
How do you convert mobilenet v3 checkpoints to .h5 file?

### ISSUE THREAD

**Issue by Kewenjing1020** [tensorflow/tensorflow#48100]
Hi, as pointed in https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/applications/mobilenet_v3.py#L390-L429 :
```
The weights for all 6 models are obtained and translated from the Tensorflow
  checkpoints from TensorFlow checkpoints found [here]
  (https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet/README.md).
```

How do you convert the checkpoints to .h5 file? Is there any documentation about this?

**Comment by Saduf2019** [comment]
@Kewenjing1020 

Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.

You may refer to these to links for an isea and move this issue to closed status after you reate one on stackoverflow: [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet_weight_update_util.py), [link1](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb)

**Comment by Kewenjing1020** [comment]
Thanks! The related links help!

**Comment by Saduf2019** [comment]
@Kewenjing1020 
Please move this issue to closed status as issue is resolved.
