### ISSUE TITLE
Add a  tf.keras.layers.WeightedAverage

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#48101]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow 2.4.1
- Are you willing to contribute it (Yes/No): I will give example code

**Describe the feature and the current behavior/state.**
I notice there is a ```tf.keras.layers.Average``` , But it does't have a parameter like ```weights``` . 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
All users who use ```tf.keras```

**Any Other info.**
I find the source code at [https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/layers/merge.py#L327-L360](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/layers/merge.py#L327-L360) . 
And I give an example code here : 
```
@keras_export('keras.layers.WeightedAverage')
class WeightedAverage(_Merge):
  """Layer that averages a list of inputs element-wise with weights.
  It takes as input a list of value tensors and a list of weight .  All of the value tensors are the same shape .  It returns
  a single tensor (also of the same shape as the value tensors ).
  Example:
  >>> x1 = np.ones((2, 2))
  >>> x2 = np.zeros((2, 2))
  >>> y = tf.keras.layers.WeightedAverage()([x1, x2],[2,3])
  >>> y.numpy().tolist()
  [[0.4, 0.4], [0.6, 0.6]]
  Usage in a functional model:
  >>> input1 = tf.keras.layers.Input(shape=(16,))
  >>> x1 = tf.keras.layers.Dense(8, activation='relu')(input1)
  >>> input2 = tf.keras.layers.Input(shape=(32,))
  >>> x2 = tf.keras.layers.Dense(8, activation='relu')(input2)
  >>> avg = tf.keras.layers.Average()([x1, x2],[1 for _ in range(16)])
  >>> out = tf.keras.layers.Dense(4)(avg)
  >>> model = tf.keras.models.Model(inputs=[input1, input2], outputs=out)
  Raises:
    ValueError: If there is a shape mismatch between the inputs and the shapes
      cannot be broadcasted to match.
  """

  def _merge_function(self, inputs , weights):
    output = inputs[0] * weights[0]
    weight_sum = weights[0]
    for i in range(1, len(inputs)):
      output += inputs[i] * weights[i]
      if weights[i] < 0:
        raise
      weight_sum += weights[i]
    if weight_sum == 0:
        raise
    return output / weight_sum 

```

**Comment by rmothukuru** [comment]
@DachuanZhao,
Thank you for the details and for the code. Can you please specify the use cases for this feature. Thanks!

**Comment by DachuanZhao** [comment]
> Thank you for the details and for the code. Can you please specify the use cases for this feature. Thanks!

You can use it when you want to calculate  a weighted average number 
I find that ```tf.keras.layers.Lambda``` can also make it . I will close this issue .
