### ISSUE TITLE
TF 2.4 still depends on GRPCIO v1.32.0

### ISSUE THREAD

**Issue by dariobig** [tensorflow/tensorflow#48109]
GRPCIO was meant to be updated in TF 2.4 but TF 2.4.0 and 2.4.1 still depend on it: 
- https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/tools/pip_package/setup.py#L121
- https://github.com/tensorflow/tensorflow/issues/45785#issuecomment-806233485

**Comment by ymodak** [comment]
The requirements are updated with TF 2.5 branch. See https://github.com/tensorflow/tensorflow/blob/96dfa5c37c8844d0fa7347c7a43c383ed9813022/tensorflow/tools/pip_package/setup.py#L130

**Comment by dariobig** [comment]
Thanks @ymodak

**Comment by mihaimaruseac** [comment]
If we need to update in 2.4, please open a PR on the branch and it will be picked up on an eventual cherrypick.

**Comment by ymodak** [comment]
Closing this issue now, Feel free to reopen if necessary. Thanks!
