### ISSUE TITLE
TransformedDistribution Documentation is not readable

### ISSUE THREAD

**Issue by ramakrse** [tensorflow/tensorflow#48116]
### Describe the problem
The documentation of tfp.TransformedDistribution is not readable in between, seen the attachement

### Source code / logs
Please see attachment
![Capture](https://user-images.githubusercontent.com/19791881/112711538-30ae7680-8eef-11eb-86e5-008263c64d6b.PNG)

**Comment by ramakrse** [comment]
Ok. Thanks. Done.

**Comment by saikumarchalla** [comment]
@ramakrse  Could you please go ahead and close the issue.
