### ISSUE TITLE
Please help Conda package tensorflow for OSX

### ISSUE THREAD

**Issue by pgunn** [tensorflow/tensorflow#48113]
(I get that this is a weird thing to put in an issue)

Right now it's hard for the Anaconda people to make conda packages of Tensorflow for OSX because of gcc-versus-clang issues: 
https://github.com/ContinuumIO/anaconda-issues/issues/11697

This is impacting downstream packages that want to use tensorflow, as we can't specify conda environments that come with tensorflow included; installing it with pip afterwards severely limits our ability to sanely package it.

If you can spare the time to work this out with them, a lot of us who maintain downstream packages would really appreciate it.

**Comment by xhochy** [comment]
Probably the necessary information needed here is how to build the correct Bazel compiler toolchain. You can have a look at https://github.com/conda-forge/tensorflow-feedstock/blob/40db5f43756877bea9e0dd2685cd5683b6527904/recipe/gen-bazel-toolchain.sh#L1 how we did this for conda-forge.

**Comment by gadagashwini** [comment]
@pgunn,
TensorFlow provided pip package is recommended, But, You can use a community-supported [Anaconda package](https://anaconda.org/anaconda/tensorflow). To install, read the [Anaconda TensorFlow guide](https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/). Thank you!

**Comment by pgunn** [comment]
It looks like there are conda-forge provided tensorflow packages now, so there's no need to keep this ticket open.

(I suggest a change in perspective to stop considering the pip package the recommended install route - a lot of the scientific community and several other communities use conda as their sole tool to manage their python environments and using pip for one package is a non-starter, but that's neither here nor there)
