### ISSUE TITLE
tensorflowlite.dll is huge (compared to other platforms)

### ISSUE THREAD

**Issue by sztomi** [tensorflow/tensorflow#48118]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 5d6cc7bf97a226c1e6a73ad4fc391c154dd622ac
- Python version: n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): MSVC 2019 (cl: 19.28.29334)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
bazel build -c opt //tensorflow/lite/tensorflowlite.dll
```

This yields a 15MB statically linked binary when compiled for 32-bit windows (i.e. the 64-bit version will be even larger). Compared to other platforms, this is a 5x increase that is difficult to explain, especially in lieu of tools like bloaty on Windows. Unfortunately I don't know where to start poking this at all - but I do believe that even accounting for platform differences, a 5x size difference is unexpected. The same issue was noted here: https://github.com/tensorflow/tensorflow/issues/33634#issuecomment-620645664 (with a suggestion to use the C API *instead*, but the C API is a binding that cannot be used independent from the C++ binary).

**Any other info / logs**
Let me know if I can include any more info.

**Comment by sztomi** [comment]
Interestingly, it compresses down to just 1.3MB with lzma. That tells me it's probably not all code taking up that much size.

**Comment by sztomi** [comment]
After some poking, it appears the size is due to the export table being 12MB. This is due to the `windows_export_all_symbols` feature added here: https://github.com/tensorflow/tensorflow/commit/fa32891c6f30add2338b4833ad32f593ec6610a6 

There is a def file filtering script, but that is only used for the non-lite version. I think that could be a reasonable solution to this. https://github.com/tensorflow/tensorflow/issues/43367

**Comment by sztomi** [comment]
After further investigation I found that the CMake build produces a 1.4MB DLL that is missing lots of symbols. However, with the CMake build, I'm able to build a static library that solves this problem for our use-case because ultimately it allows the linker to sort out which symbols to use (we are using the C++ API directly). The bazel build hardcodes the shared library, maybe it would be useful to make that optional. I don't have any bazel expertise unfortunately to do that (not that I would prefer bazel).

**Comment by pkgoogle** [comment]
Hi @sztomi, as this issue is quite old, can you let us know if you are still running into this issue?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by pkgoogle** [comment]
Hi @sztomi, to help us better focus on up to date issues, can you create a new github issue for this with your latest findings and close this one as not planned? Thanks for your help!

**Comment by pkgoogle** [comment]
Please follow progress on https://github.com/tensorflow/tensorflow/issues/61705
