### ISSUE TITLE
tflite model is not running on webcam feed

### ISSUE THREAD

**Issue by Zakria96** [tensorflow/tensorflow#48126]
**System information**
- OS Platform and Distribution (Linux)
- TensorFlow version (2.4.1):

I used TensorFlow pre-trained faster rcnn inception v2 coco model and used my own images and trained them on that model. I exported the frozen inference graph successfully and check it on my webcam , I was working fine and using the code below , I converted the frozen inference graph into tflite model....

import logging
logging.getLogger("tensorflow").setLevel(logging.DEBUG)

import tensorflow as tf
from tensorflow import keras
import numpy as np
import pathlib

#conversion of faster_rcnn_inception_v2_coco_model frozen_inference_graph.pbin to tflite model

import tensorflow as tf
import os 

os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("frozen_inference_graph.pb", ["image_tensor"], ["detection_classes", "detection_scores", "detection_boxes", "num_detections"])
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
model = converter.convert()

tflite_models_dir = pathlib.Path("model/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)
tflite_model_file = tflite_models_dir/"mnist_model.tflite"
tflite_model_file.write_bytes(model)

#To Quantize the model on Export, Set the optimizations flag to optimize for size

converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
tflite_model_quant_file = tflite_models_dir/"mnist_model_quant.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)

 But I am not able to load my .tflite model in python for checking if my tflite model is working and using my webcam as input to the model ...For loading the tflite model ,I am using the code below : 

######## Webcam Object Detection Using Tensorflow-trained Classifier #########
#
# Author: Evan Juras
# Date: 10/27/19
# Description: 
# This program uses a TensorFlow Lite model to perform object detection on a live webcam
# feed. It draws boxes and scores around the objects of interest in each frame from the
# webcam. To improve FPS, the webcam object runs in a separate thread from the main program.
# This script will work with either a Picamera or regular USB webcam.
#
# This code is based off the TensorFlow Lite image classification example at:
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/python/label_image.py
#
# I added my own method of drawing boxes and labels using OpenCV.

# Import packages
import os
import argparse
import cv2
import numpy as np
import sys
import time
from threading import Thread
import importlib.util

# Define VideoStream class to handle streaming of video from webcam in separate processing thread
# Source - Adrian Rosebrock, PyImageSearch: https://www.pyimagesearch.com/2015/12/28/increasing-raspberry-pi-fps-with-python-and-opencv/
class VideoStream:
    """Camera object that controls video streaming from the Picamera"""
    def __init__(self,resolution=(640,480),framerate=30):
        # Initialize the PiCamera and the camera image stream
        self.stream = cv2.VideoCapture(0)
        ret = self.stream.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*'MJPG'))
        ret = self.stream.set(3,resolution[0])
        ret = self.stream.set(4,resolution[1])
            
        # Read first frame from the stream
        (self.grabbed, self.frame) = self.stream.read()

	# Variable to control when the camera is stopped
        self.stopped = False

    def start(self):
	# Start the thread that reads frames from the video stream
        Thread(target=self.update,args=()).start()
        return self

    def update(self):
        # Keep looping indefinitely until the thread is stopped
        while True:
            # If the camera is stopped, stop the thread
            if self.stopped:
                # Close camera resources
                self.stream.release()
                return

            # Otherwise, grab the next frame from the stream
            (self.grabbed, self.frame) = self.stream.read()

    def read(self):
	# Return the most recent frame
        return self.frame

    def stop(self):
	# Indicate that the camera and thread should be stopped
        self.stopped = True

# Define and parse input arguments
parser = argparse.ArgumentParser()
parser.add_argument('--modeldir', help='Folder the .tflite file is located in',
                    required=True)
parser.add_argument('--graph', help='Name of the .tflite file, if different than detect.tflite',
                    default='mnist_model_quant.tflite')
parser.add_argument('--labels', help='Name of the labelmap file, if different than labelmap.txt',
                    default='labelmap.txt')
parser.add_argument('--threshold', help='Minimum confidence threshold for displaying detected objects',
                    default=0.5)
parser.add_argument('--resolution', help='Desired webcam resolution in WxH. If the webcam does not support the resolution entered, errors may occur.',
                    default='1280x720')
parser.add_argument('--edgetpu', help='Use Coral Edge TPU Accelerator to speed up detection',
                    action='store_true')

args = parser.parse_args()

MODEL_NAME = args.modeldir
GRAPH_NAME = args.graph
LABELMAP_NAME = args.labels
min_conf_threshold = float(args.threshold)
resW, resH = args.resolution.split('x')
imW, imH = int(resW), int(resH)
use_TPU = args.edgetpu

# Import TensorFlow libraries
# If tensorflow is not installed, import interpreter from tflite_runtime, else import from regular tensorflow
# If using Coral Edge TPU, import the load_delegate library
pkg = importlib.util.find_spec('tensorflow')
if pkg is None:
    from tflite_runtime.interpreter import Interpreter
    if use_TPU:
        from tflite_runtime.interpreter import load_delegate
else:
    from tensorflow.lite.python.interpreter import Interpreter
    if use_TPU:
        from tensorflow.lite.python.interpreter import load_delegate

# If using Edge TPU, assign filename for Edge TPU model
if use_TPU:
    # If user has specified the name of the .tflite file, use that name, otherwise use default 'edgetpu.tflite'
    if (GRAPH_NAME == 'mnist_model_quant.tflite'):
        GRAPH_NAME = 'mnist_model_quant.tflite'       

# Get path to current working directory
CWD_PATH = os.getcwd()

# Path to .tflite file, which contains the model that is used for object detection
PATH_TO_CKPT = os.path.join(CWD_PATH,MODEL_NAME,GRAPH_NAME)

# Path to label map file
PATH_TO_LABELS = os.path.join(CWD_PATH,MODEL_NAME,LABELMAP_NAME)

# Load the label map
with open(PATH_TO_LABELS, 'r') as f:
    labels = [line.strip() for line in f.readlines()]

# Have to do a weird fix for label map if using the COCO "starter model" from
# https://www.tensorflow.org/lite/models/object_detection/overview
# First label is '???', which has to be removed.
if labels[0] == '???':
    del(labels[0])

# Load the Tensorflow Lite model.
# If using Edge TPU, use special load_delegate argument
if use_TPU:
    interpreter = Interpreter(model_path=PATH_TO_CKPT,
                              experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
    print(PATH_TO_CKPT)
else:
    interpreter = Interpreter(model_path=PATH_TO_CKPT)

interpreter.allocate_tensors()

# Get model details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
height = input_details[0]['shape'][1]
width = input_details[0]['shape'][2]

floating_model = (input_details[0]['dtype'] == np.float32)

input_mean = 127.5
input_std = 127.5

# Initialize frame rate calculation
frame_rate_calc = 1
freq = cv2.getTickFrequency()

# Initialize video stream
videostream = VideoStream(resolution=(imW,imH),framerate=30).start()
time.sleep(1)

#for frame1 in camera.capture_continuous(rawCapture, format="bgr",use_video_port=True):
while True:

    # Start timer (for calculating frame rate)
    t1 = cv2.getTickCount()

    # Grab frame from video stream
    frame1 = videostream.read()

    # Acquire frame and resize to expected shape [1xHxWx3]
    frame = frame1.copy()
    print(frame.shape)
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    print(frame_rgb.shape)
    frame_resized = cv2.resize(frame_rgb, (width, height))
    print(frame_resized.shape)
    input_data = np.expand_dims(frame_resized, axis=0)
    print(input_data.dtype)

    # Normalize pixel values if using a floating model (i.e. if model is non-quantized)
    if floating_model:
        input_data = (np.float32(input_data) - input_mean) / input_std

    # Perform the actual detection by running the model with the image as input
    interpreter.set_tensor(input_details[0]['index'],input_data)
    interpreter.invoke()

    # Retrieve detection results
    boxes = interpreter.get_tensor(output_details[0]['index'])[0] # Bounding box coordinates of detected objects
    classes = interpreter.get_tensor(output_details[1]['index'])[0] # Class index of detected objects
    scores = interpreter.get_tensor(output_details[2]['index'])[0] # Confidence of detected objects
    #num = interpreter.get_tensor(output_details[3]['index'])[0]  # Total number of detected objects (inaccurate and not needed)

    # Loop over all detections and draw detection box if confidence is above minimum threshold
    for i in range(len(scores)):
        if ((scores[i] > min_conf_threshold) and (scores[i] <= 1.0)):

            # Get bounding box coordinates and draw box
            # Interpreter can return coordinates that are outside of image dimensions, need to force them to be within image using max() and min()
            ymin = int(max(1,(boxes[i][0] * imH)))
            xmin = int(max(1,(boxes[i][1] * imW)))
            ymax = int(min(imH,(boxes[i][2] * imH)))
            xmax = int(min(imW,(boxes[i][3] * imW)))
            
            cv2.rectangle(frame, (xmin,ymin), (xmax,ymax), (10, 255, 0), 2)

            # Draw label
            object_name = labels[int(classes[i])] # Look up object name from "labels" array using class index
            label = '%s: %d%%' % (object_name, int(scores[i]*100)) # Example: 'person: 72%'
            labelSize, baseLine = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2) # Get font size
            label_ymin = max(ymin, labelSize[1] + 10) # Make sure not to draw label too close to top of window
            cv2.rectangle(frame, (xmin, label_ymin-labelSize[1]-10), (xmin+labelSize[0], label_ymin+baseLine-10), (255, 255, 255), cv2.FILLED) # Draw white box to put label text in
            cv2.putText(frame, label, (xmin, label_ymin-7), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 0), 2) # Draw label text

    # Draw framerate in corner of frame
    cv2.putText(frame,'FPS: {0:.2f}'.format(frame_rate_calc),(30,50),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,0),2,cv2.LINE_AA)

    # All the results have been drawn on the frame, so it's time to display it.
    cv2.imshow('Object detector', frame)

    # Calculate framerate
    t2 = cv2.getTickCount()
    time1 = (t2-t1)/freq
    frame_rate_calc= 1/time1

    # Press 'q' to quit
    if cv2.waitKey(1) == ord('q'):
        break

# Clean up
cv2.destroyAllWindows()
videostream.stop()

the Error I am getting After running the code : 

Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 186, in <module>
    interpreter.invoke()
  File "/root/anaconda3/envs/tf_env/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 540, in invoke
    self._interpreter.Invoke()
RuntimeError: Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysTensorArrayV3_0)
	 (while executing 'TensorArrayScatterV3' via Eager)Node number 416 (TfLiteFlexDelegate) failed to invoke.

^CException ignored in: <module 'threading' from '/root/anaconda3/envs/tf_env/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/root/anaconda3/envs/tf_env/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
FATAL: exception not rethrown
Aborted

the error is in the screenshot attached 

![Screenshot at 2021-03-27 18-47-57](https://user-images.githubusercontent.com/65131911/112736937-8403e180-8f4e-11eb-9d6a-86f55af0de47.png)

**Comment by abattery** [comment]
To use TensorArray ops in your model, please consider using tf-nightly or TF 2.5. TensorArray is supported only in TFLite after TF 2.5

**Comment by Zakria96** [comment]
> To use TensorArray ops in your model, please consider using tf-nightly or TF 2.5. TensorArray is supported only in TFLite after TF 2.5

Can You send me a snippet how to use my tflite in TF 2.5 .... and finding my tflite's tensorArray

**Comment by abattery** [comment]
You can install a newer tf version by using the pip command:
```pip install tf-nightly```

To use the TensorArray support, the TFLite model should be regenerated with the new TF version.

**Comment by Zakria96** [comment]
> You can install a newer tf version by using the pip command:
> 
> ```pip install tf-nightly```
> 
> 
> 
> To use the TensorArray support, the TFLite model should be regenerated with the new TF version.

I regenerated my Tflite model with tf-nightly and then using TFLite_detection_webcam.py and
 Webcam is not showing the output results.
got the following error: screenshoot attached
![image](https://user-images.githubusercontent.com/65131911/112750493-6cf9d980-8fb8-11eb-9849-e39711e550c0.jpeg)

**Comment by Zakria96** [comment]
> > You can install a newer tf version by using the pip command:
> > `pip install tf-nightly`
> > To use the TensorArray support, the TFLite model should be regenerated with the new TF version.
> 
> I regenerated my Tflite model with tf-nightly and then using TFLite_detection_webcam.py and
> Webcam is not showing the output results.
> got the following error: screenshoot attached
> ![image](https://user-images.githubusercontent.com/65131911/112750493-6cf9d980-8fb8-11eb-9849-e39711e550c0.jpeg)

And when I am loading my mnist_model_quant.tflite model in the code below ,

import numpy as np
import tensorflow as tf

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model/mnist_model_quant.tflite")
interpreter.allocate_tensors()

print(interpreter.get_input_details())

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.uint8)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

I am getting the following ... This may help finding my solution

2021-03-28 09:32:30.482772: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (parrot): /proc/driver/nvidia/version does not exist
INFO: TfLiteFlexDelegate delegate: 58 nodes delegated out of 410 nodes with 15 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 17 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 17 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 3 nodes delegated out of 11 nodes with 2 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 6 nodes delegated out of 108 nodes with 2 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 3 nodes delegated out of 17 nodes with 2 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 10 nodes with 2 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 10 nodes delegated out of 261 nodes with 2 partitions.

[{'name': 'image_tensor', 'index': 0, 'shape': array([1, 1, 1, 3], dtype=int32), 'shape_signature': array([-1, -1, -1,  3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

[[1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 4. 3. 1. 1. 1. 1. 2. 1. 1. 4. 1. 1.
  3. 1. 1. 1. 1. 1. 4. 1. 2. 2. 2. 2. 2. 4. 4. 4. 4. 4. 1. 4. 4. 3. 4. 1.
  4. 1. 4. 4. 3. 1. 4. 4. 3. 2. 3. 4. 4. 3. 2. 2. 2. 2. 3. 1. 1. 1. 3. 1.
  1. 2. 1. 1. 2. 4. 4. 4. 3. 3. 4. 3. 1. 4. 2. 3. 4. 4. 1. 4. 1. 1. 4. 1.
  1. 1. 1. 1. 4. 1. 3. 1. 2. 1. 1. 2. 4. 2. 4. 4. 4. 4. 3. 3. 1. 1. 4. 3.
  4. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 1. 4.
  4. 4. 4. 3. 1. 1. 1. 2. 1. 2. 2. 4. 1. 4. 4. 1. 1. 2. 2. 1. 1. 1. 4. 3.
  1. 3. 2. 2. 4. 3. 1. 2. 4. 4. 4. 1. 1. 1. 4. 2. 2. 1. 2. 2. 3. 1. 4. 2.
  2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 2.
  3. 3. 2. 3. 1. 3. 3. 1. 3. 1. 1. 3. 1. 4. 2. 4. 3. 3. 2. 1. 1. 3. 3. 4.
  3. 2. 1. 1. 4. 1. 1. 2. 4. 1. 2. 4. 1. 2. 4. 4. 4. 1. 3. 4. 4. 4. 1. 4.
  4. 4. 1. 1. 4. 1. 1. 2. 4. 4. 3. 4. 4. 4. 2. 4. 2. 3. 4. 1. 1. 3. 1. 1.
  4. 2. 2. 4. 3. 3. 3. 4. 4. 2. 2. 2.]]

**Comment by Zakria96** [comment]
@abattery Jae sung Chung

**Comment by abattery** [comment]
Looks like the converted tflite is working. For the TFLite_detection_webcam.py's behavior, please ask questions at the script owner at https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi.

**Comment by Zakria96** [comment]
> Looks like the converted tflite is working. For the TFLite_detection_webcam.py's behavior, please ask questions at the script owner at https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi.


https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi#step-1a-download-and-extract-quantized-ssd-mobilenet-model

The link you sent that says that TensorFlow Lite does NOT support RCNN models such as Faster-RCNN! It only supports SSD models.

**Comment by sanatmpa1** [comment]
@Zakria96,

Can you take a look at this [similar issue](https://github.com/tensorflow/tensorflow/issues/37401) for tflite conversion of `FasterRCNN` and also take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/34845#issuecomment-573156336) to modify `pipeline.config`. Let us know if it helps. Thanks!
