### ISSUE TITLE
equations are terribly formatted

### ISSUE THREAD

**Issue by FeU-aKlos** [tensorflow/tensorflow#48136]
hello, 
if I change the language (e.g. German) in the documentation, the equations are terribly formatted. This problem appears e.g. [here](https://www.tensorflow.org/agents/tutorials/intro_bandit). In English language, every looks fine. Nevertheless, as soon as I change the language, there seems to be a formatting issue.
Best Regards

**Comment by Saduf2019** [comment]
@FeU-aKlos 
Can you please check the same on different browsers and confirm as we do not face the same issue.

**Comment by mohantym** [comment]
Hi @FeU-aKlos ! I think this issue has been addressed now. Please let us know if we can move this issue to closed status or not? Thanks!

**Comment by FeU-aKlos** [comment]
@mohantym the formatting is now correct, for the selectable languages. Nevertheless, German is now **not** anymore selectable. Not sure if this is the right way of adressing the issue, by just dropping the languages in which the problem was present. But yeah, I guess so far the issue can be closed.

**Comment by mohantym** [comment]
Ok @FeU-aKlos ! Closing this issue as it has been resolved in latest versions(2.8). Thanks!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
