### ISSUE TITLE
Removing dependency on full TF

### ISSUE THREAD

**Issue by john-** [tensorflow/tensorflow#48135]
### 1. System information

- OS Platform and Distribution: aarch64 /Ubuntu 18.04
- TensorFlow installation:  Package
- TensorFlow library: 2.4.1

### 2. Code

I have taken first step to using TF Lite by using interpreter from full Tensorflow.   This code does the inferencing and there is separate code to do the modelling:

[https://gitlab.com/john---/xmit_processor/-/blob/tflite/xmit_processor/xmit_processor.py](url)

This code take around 2% less RAM (out of 4GB) than the full Tensorflow version.   However, I think tot get the full benefit I need to use the Tensorflow Lite runtime.   However, for inference I am using many tf.* functions.   A couple of them:

tf.audio.decode_wav
tf.signal.stft

From what I can see in the documentation these are not available in TF Lite.   Let me know:

-  To get the minimized memory footprint of TF Lite do I need to use TF Lite runtime?
- Do I need to find TF Lite (tfl.\*) alternates for all the tf.\* functions?
- Any other paths I can take to decrease memory footprint?

Note: the training currently works with full Tensorflow but I can make changes to that part as needed to improve memory consumption on the inferencing side.

**Comment by abattery** [comment]
TFLite is optimized for the mainly ARM devices and inference use cases. It can reduce overall memory footprint by using only carrying inference features only.

- If possible, you might find an alternative option in programming language for tf.audio.decode_wav function out of graph, which is usually needed at the beginning of the graph.
- You can find alternatives in tfl dialect or you can implement your own stft op by creating a custom op. https://www.tensorflow.org/lite/guide/ops_custom
- If you can quantize your model, you can easily decrease your tensor memory by half. https://www.tensorflow.org/lite/performance/model_optimization

**Comment by john-** [comment]
Thanks for the detailed response.

Based on the the first two items it seems like the biggest gain would be to not import Tensorflow but to remove the dependency on it by reimplementing those functions I am currently using from  the tensorflow import.

Is it fair to say the the model itself is not really what what is bringing in the overhead but the functions needed to prepare the data for inference?  Or is that not really relevant because data preparation can be moved to the model itself?

**Comment by abattery** [comment]
Sorry, I don't have a good answer of your question related to the overhead expectations.

In my best guess, the overhead should be analyzed per model since each model has different characters.

For the details of the overhead analysis, please consider using the TFLite benchmark tool set to analyze overall memory overhead: https://www.tensorflow.org/lite/performance/measurement

**Comment by john-** [comment]
Thanks.   I guess I distinguished the model from the data preparation.   Sounds like the benchmark tool will give be a complete picture.

**Comment by john-** [comment]
I did some tests which indicate to me that the main contributor to memory  utilisation is the TensorFlow framework and not the model.

Without any model loaded:

`
/usr/bin/time -f '%M' python -c "import tensorflow as tf"
`
349296
`
/usr/bin/time -f '%M' python -c "import tflite_runtime.interpreter as tflite"
`
28644

With the model:

`
/usr/bin/time -f '%M' python -c "import tensorflow as tf; model = tf.keras.models.load_model('./1')"
`
440056
`
/usr/bin/time -f '%M' python -c "import tflite_runtime.interpreter as tflite; interpreter = tflite.Interpreter('./model_1.tflite')"
`
30728

Based on this the full framework (no nodel loaded) takes 12 times the memory as the runtime framework.   If I don't replace the tf.\* functions with python or tfl.\* equivalents any changes to the model will have much smaller gains in comparison.
