### ISSUE TITLE
"CancelledError:  [_Derived_]RecvAsync is cancelled.  Function call stack: train_function" persists for some code

### ISSUE THREAD

**Issue by nanhyang9** [tensorflow/tensorflow#48147]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.0
- CUDA/cuDNN version: 11.0 (TF was installed by following the procedure in https://www.tensorflow.org/install/gpu)
- GPU model and memory:  3080 RTX 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

After setting up a new rig, I ran two different LSTM models. Initially both models failed to initiate training by giving the error below:
     

     CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_41}}]]
	 [[gradient_tape/sequential_1/embedding/embedding_lookup/Reshape/_38]] [Op:__inference_train_function_3172]
    Function call stack:
    train_function

I was able to fix one model by adding `import os ; os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"`, but another model still fails to run. Here is the whole error message from the model:

    Epoch 1/15
    ---------------------------------------------------------------------------
    CancelledError                            Traceback (most recent call last)
    <ipython-input-96-9b266da78330> in <module>
          1 es = EarlyStopping(monitor = 'val_loss', mode = 'min', patience = 4, verbose =1)
          2 mc = ModelCheckpoint('best_model_naver.h5', monitor = 'val_acc', mode = 'max', save_best_only = True)
    ----> 3 history = model.fit(X_train, y_train, batch_size = 128, callbacks = [es, mc], epochs = 15, validation_split = .2)
    
    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
       1098                 _r=1):
       1099               callbacks.on_train_batch_begin(step)
    -> 1100               tmp_logs = self.train_function(iterator)
       1101               if data_handler.should_sync:
       1102                 context.async_wait()

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
        826     tracing_count = self.experimental_get_tracing_count()
        827     with trace.Trace(self._name) as tm:
    --> 828       result = self._call(*args, **kwds)
        829       compiler = "xla" if self._experimental_compile else "nonXla"
        830       new_tracing_count = self.experimental_get_tracing_count()

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
        886         # Lifting succeeded, so variables are initialized and we can run the
        887         # stateless function.
    --> 888         return self._stateless_fn(*args, **kwds)
        889     else:
        890       _, _, _, filtered_flat_args = \

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
       2940       (graph_function,
       2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
    -> 2942     return graph_function._call_flat(
       2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
       2944 

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
       1916         and executing_eagerly):
       1917       # No tape is watching; skip to running the function.
    -> 1918       return self._build_call_outputs(self._inference_function.call(
       1919           ctx, args, cancellation_manager=cancellation_manager))
       1920     forward_backward = self._select_forward_and_backward_functions(

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
        553       with _InterpolateFunctionError(self):
        554         if cancellation_manager is None:
    --> 555           outputs = execute.execute(
        556               str(self.signature.name),
    557               num_outputs=self._num_outputs,

    ~/anaconda3/envs/dl_learn/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
         57   try:
         58     ctx.ensure_initialized()
    ---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
             60                                         inputs, attrs, num_outputs)
             61   except core._NotOkStatusException as e:

    CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_41}}]]
	 [[gradient_tape/sequential_1/embedding/embedding_lookup/Reshape/_38]] [Op:__inference_train_function_3172]

    Function call stack:
    train_function'

Error message on console:

    2021-03-29 05:37:44.895392: E tensorflow/stream_executor/dnn.cc:616] CUDNN_STATUS_EXECUTION_FAILED in tensorflow/stream_executor/cuda/cuda_dnn.cc(1859): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'

    2021-03-29 05:37:44.895639: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at cudnn_rnn_ops.cc:1521 : Internal: Failed to call ThenRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 3, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 30, 128, 1, 30, 128, 0] 

**Describe the expected behavior**

I expected the issue to be resolved by adding `import os ; os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"`

**Standalone code to reproduce the issue**

Below is the code that produces the error messages:

    %config Completer.use_jedi = False
    import pandas as pd
    import numpy as np
    import urllib.request 
    from tensorflow.keras.preprocessing.text import Tokenizer
    from tensorflow.keras.preprocessing.sequence import pad_sequences
    from konlpy.tag import Okt
    import re
    import matplotlib.pyplot as plt
    import os
    os.environ["TF_FORCE_ALLOW_GPU_GROWTH"] = 'true'
    from tensorflow.keras.models import Sequential, load_model
    from tensorflow.keras.layers import Embedding, LSTM, Dense, GRU
    from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

    urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt", filename = 'ratings_train.txt')
    urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt", filename = 'ratings_test.txt')

    train = pd.read_table('ratings_train.txt')
    train.drop_duplicates(subset = 'document', inplace = True)
    train.dropna(inplace = True)   
    train['document'] = train['document'].str.replace(r"[^ㄱ-ㅎㅏ-ㅣ가-힣 ]", "")
    train[train['document'] == ''] = np.nan
    train.dropna(inplace = True)
    stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다']
    okt = Okt()
    X_train = [[word for word in okt.morphs(sentence, stem = True) if word not in stopwords] for sentence in train['document']]
    vocab_size = 19417
    t = Tokenizer(vocab_size, oov_token = "OOV")
    t.fit_on_texts(X_train)
    X_train_sequences = t.texts_to_sequences(X_train)
    y_train = np.array(train['label'])
    empty_sample_idx = [index for index, sequence in enumerate(X_train_sequences) if len(sequence) < 1]
    X_train = np.delete(X_train_sequences, empty_sample_idx, axis = 0)
    y_train = np.delete(y_train, empty_sample_idx, axis = 0)
    maxlen = 30
    X_train = pad_sequences(X_train, maxlen = maxlen, padding = 'pre')

    model = Sequential()
    model.add(Embedding(vocab_size, 30))
    model.add(LSTM(128))
    model.add(Dense(1, activation = 'sigmoid'))
    model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['acc'])
    es = EarlyStopping(monitor = 'val_loss', mode = 'min', patience = 4, verbose =1)
    mc = ModelCheckpoint('best_model_naver.h5', monitor = 'val_acc', mode = 'max', save_best_only = True)
    history = model.fit(X_train, y_train, batch_size = 128, callbacks = [es, mc], epochs = 15, validation_split = .2)

Below is the code I was able to run successfully after adding `import os ; os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"` :

    import os
    os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"
    import numpy as np
    import matplotlib.pyplot as plt
    from tensorflow.keras.datasets import imdb
    import re
    from tensorflow.keras.preprocessing.sequence import pad_sequences
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Embedding, GRU, Dense, LSTM
    from tensorflow.keras.utils import to_categorical
    from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

    vocab_size = 10000
    (X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

    maxlen = 500
    X_train = pad_sequences(X_train, maxlen = maxlen)
    X_test = pad_sequences(X_test, maxlen = maxlen)

    model = Sequential()
    model.add(Embedding(vocab_size, 100))
    model.add(LSTM(128))
    model.add(Dense(1, activation = 'sigmoid'))
    es = EarlyStopping(monitor = 'val_loss', mode = 'min', patience = 4, verbose = 1)
    mc = ModelCheckpoint('best_model_imdb.h5', monitor = 'val_acc', mode = 'max', save_best_only = True)
    model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['acc'])

    history = model.fit(X_train, y_train, callbacks = [es, mc], epochs = 15, batch_size = 128, validation_split = .2)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by nanhyang9** [comment]
I was able to got both codes working by downgrading TF from 2.4.1 to 2.3.0. But the performance dropped dramatically. When the 2nd code was run with TF 2.4.1 , it took about 5 seconds to run an epoch. But the same code run with TF 2.3.0 took about 65 seconds for an epoch. Watching `nvidia-smi` suggests that TF didn't seem to utilize GPU (Fan: 0%) even though `tf.test.is_built_with_cuda()` returns `True`

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on the version mentioned, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ca0005488f81dc618a5dc8b9137c59e1/untitled577.ipynb)

**Comment by nanhyang9** [comment]
I just learned that the exactly same results occur on Win10 with NVIDIA Driver 461.33, CUDA 11.2.109, Python 3.8.3.

**Comment by nanhyang9** [comment]
I got the same error message when I ran the code from Tensorflow container, which I built with the "tensorflow/tensorflow:latest-gpu-jupyter" image.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF nightly-2.6.0.dev20210603,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/c7d0721ec452f9f8cc306dcd796aa893/untitled208.ipynb)..Thanks !

**Comment by sanjoy** [comment]
@kaixih On the surface this looks like an error reported by cuDNN from a `cudnnRNNForwardTraining` call.  Can you PTAL to see if this rings a bell?

**Comment by kaixih** [comment]
Can we have the cudnn logs: https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging.

Also if possible, can we have a repro with synthetic data? I have some trouble resolving the dependencies of these data processing tools when running the script on my machine.

**Comment by summa-code** [comment]
Any solution to this Multi GPU?

```W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at cudnn_rnn_ops.cc:1562 : UNKNOWN: CUDNN_STATUS_BAD_PARAM in tensorflow/stream_executor/cuda/cuda_dnn.cc(1588): 'cudnnSetTensorNdDescriptor( tensor_desc.get(), data_type, sizeof(dims) / sizeof(dims[0]), dims, strides)' Traceback (most recent call last):

 tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node div_no_nan_1/ReadVariableOp_3/_40}}]] [Op:__inference_test_function_29082]```

**Comment by sushreebarsa** [comment]
@nanhyang9 Could you kindly ensure the proper configuration for distributed training or multi-GPU usage here with the latest TF version 2.16.1?
Thank you!
