### ISSUE TITLE
tensforflow stucks at the installation

### ISSUE THREAD

**Issue by LucasColas** [tensorflow/tensorflow#48142]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Family
- TensorFlow version:  2.4.1
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): No 
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: CUDA 11.2
- GPU model and memory: GTX 1660 Ti

I wanted to install tensorflow but the installation stucks.

I did a pip install. tensorflow had started downloading. And then this installation got stuck...

**Comment by Saduf2019** [comment]
@LucasColas 
Could you please down grade your Cuda to 11.0 and let us know if you face the same issue as Cuda 11.2 is compatible from tf-nightly [2.5].
Also please verify if you meet the system requirements:
#47720,#43030,#47517

**Comment by LucasColas** [comment]
I'm not a big to down grade Cuda.
