### ISSUE TITLE
Missing Add* function for Builtin operator FILL

### ISSUE THREAD

**Issue by dmpiergiacomo** [tensorflow/tensorflow#48145]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 771c870a81c1025c4886a4fb60ca33971e98c577
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): nRF52840 DK

**Describe the problem**
I successfully converted my model to TF Lite for Microcontrollers and I am now trying to consume it from an nRF52840 DK target, but I get a failure when allocating the tensors:
```
[ERR] ./model/debug_log.cc:12: Didn't find op for builtin opcode 'FILL' version '1'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
[ERR] ./model/debug_log.cc:12: 
[ERR] ./model/debug_log.cc:12: Failed to get registration from op code FILL
[ERR] ./model/debug_log.cc:12: 
[ERR] ./model/debug_log.cc:12: Failed starting model allocation.
[ERR] ./model/debug_log.cc:12: 
[ERR] ./model/debug_log.cc:12: AllocateTensors() failed
```

Being proprietary software, unfortunately, I cannot share more details about the model used.

I already have a proposed resolution of the issue and I'm opening this Issue ticket in order to open a PR.

**Please provide the exact sequence of commands/steps when you ran into the problem**
The code fails within this function call:
```
void model_init(){
	// Set up logging
	static tflite::MicroErrorReporter micro_error_reporter;
	error_reporter = &micro_error_reporter;

	// Map the model into a usable data structure
	model = ::tflite::GetModel(g_model);
	if (model->version() != TFLITE_SCHEMA_VERSION) {
		TF_LITE_REPORT_ERROR(error_reporter,
				"Model provided is schema version %d not equal "
				"to supported version %d.\n",
				model->version(), TFLITE_SCHEMA_VERSION);
	}

	// This pulls in all the operation implementations we need
	static tflite::AllOpsResolver resolver;
	resolver.AddExpandDims();

	// Build an interpreter to run the model with.
	static tflite::MicroInterpreter static_interpreter(
			model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
	interpreter = &static_interpreter;

	// Allocate memory from the tensor_arena for the model's tensors.
	TfLiteStatus allocate_status = interpreter->AllocateTensors();
	if (allocate_status != kTfLiteOk){
		TF_LITE_REPORT_ERROR(error_reporter, "AllocateTensors() failed");
		return;
	}

	// Obtain pointers to the model's input and output tensors.
	input = interpreter->input(0);
	output = interpreter->output(0);
}
```

**Comment by dmpiergiacomo** [comment]
Hi,

I created a PR with a fix [(48144)](https://github.com/tensorflow/tensorflow/pull/48144).

Apologies if did not respecting your contributing guidelines this time.

Cheers

**Comment by napoleonwar** [comment]
Hi, could you please tell me how big is your libtensorflow-microlite.a?

**Comment by dmpiergiacomo** [comment]
> Hi, could you please tell me how big is your libtensorflow-microlite.a?

Hi @napoleonwar, my `libtensorflow-microlite.a` seems to be 1.0 MB on my host. I currently don't know the size on the target though.

**Comment by napoleonwar** [comment]
> Hi @napoleonwar, my `libtensorflow-microlite.a` seems to be 1.0 MB on my host. I currently don't know the size on the target though.

Ok Thanks! I am wondering how big is it after you compiling the hello world example if you did before. Because in my case, the binary file is 350KB for this simplest example, it will become bigger for more complex cases. Did you get some result whose size is under 100KB by using TFLM?
