### ISSUE TITLE
GPU Profiling: MemoryProfile do not contain memory events.

### ISSUE THREAD

**Issue by ibreschi** [tensorflow/tensorflow#48146]
**System information**
- Have I written custom code in: C++
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 2.3.2
- Python version: 3.6
- Bazel version: 3.1.0
- GCC/Compiler version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: 10.2 /8
- GPU model and memory: GeForce GTX 1060 6GB 

**Describe the current behavior**

I'm trying to use the Tensorflow C++ profiling lib to extract the memory footprint of one network on my GPU.
Here is the code I use to trace my inference and extract the memory profile:
```
auto tracer = CreateGpuTracer();
tracer->Start(); 

// Inference
tensorflow::RunOptions run_options;
run_options.set_trace_level(tensorflow::RunOptions::FULL_TRACE);
tensorflow::RunMetadata run_metadata;
run_status = session->Run(run_options, input_tf_tensors, output_names, {}, &tf_outputs, &run_metadata);
tracer->Stop();

XSpace xspace;
status = tracer->CollectData(&xspace);

std::vector<const XPlane*> device_planes_gpu = FindPlanesWithPrefix(xspace, "/device:GPU:");
const XPlane* plane_gpu = device_planes_gpu[0];
MemoryProfile memory_profile = ConvertXPlaneToMemoryProfile(*plane_gpu);

std::string json_output;
google::protobuf::util::MessageToJsonString(memory_profile, &json_output);
LOG(INFO) << json_output;
```

Here the TF logs that shows how the GPU is found, Cuda libs are found and that some events are collected:
```
    2021-03-26 15:28:19.841126: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 1 GPUs
    2021-03-26 15:28:19.841822: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcupti.so.10.2
    2021-03-26 15:28:20.823429: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
    2021-03-26 15:24:34.402625: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1513] CUPTI activity buffer flushed
    2021-03-26 15:24:34.402648: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 562 callback api events and 562 activity events. 
```
 
Unfortunately no event either HostEventType::kMemoryDeallocation or HostEventType::kMemoryAllocation is collected in the XSpace and consequently the MemoryProfile is empty. The resulting memory summary is:
```
    {"memoryProfilePerAllocator":{},"numHosts":1,"memoryIds":[]}
```

**Describe the expected behavior**

I expect that the MemoryProfile contains at least one memoryProfilePerAllocator containing one MemoryProfileSummary.

From this object I should be able to get the information to print the Memory profile summary shown in the profiler guide:
https://www.tensorflow.org/guide/profiler#memory_profile_tool

**Other info / logs** Include any logs or source code that would be helpful to

My inference works as expected.

**Comment by ibreschi** [comment]
Hello do you have any update about this issue?

**Comment by sanjoy** [comment]
@jbaiocchi knows this better.

**Comment by jbaiocchi** [comment]
Please note that there's no official C++ API for programmatic profiling in TF2.

Your code is enabling TF1 profiling capabilities in session->Run() by setting a trace level in RunOptions passed. Don't do that to avoid conflicts with the TF2 profiler.

Do not use CreateGpuTracer() as it is not a public API. It is a factory function for instantiating the GPU tracer, which is a plugin to ProfilerSession. Using the factory function directly leads to undefined / untested behavior. Furthermore, that's not the part of the profiler that creates a memory profile. Likewise, the functions for processing xplane are meant for internal use of the profiler.

You might try something like the following instead:

**auto tracer = tensorflow::ProfilerSession::Create(ProfilerSession::DefaultOptions());**

tensorflow::RunOptions run_options;
tensorflow::RunMetadata run_metadata;
run_status = session->Run(run_options, input_tf_tensors, output_names, {}, &tf_outputs, &run_metadata);

XSpace xspace;
status = tracer->CollectData(&xspace);

std::vector<const XPlane*> device_planes_gpu = FindPlanesWithPrefix(xspace, "/device:GPU:");
const XPlane* plane_gpu = device_planes_gpu[0];
MemoryProfile memory_profile = ConvertXPlaneToMemoryProfile(*plane_gpu);

std::string json_output;
google::protobuf::util::MessageToJsonString(memory_profile, &json_output);
LOG(INFO) << json_output;

The code above will only work if profiling a local GPU. It will not work if session is dispatching to a remote worker.
I re-iterate that none of these are officially supported C++ APIs and we are likely to break them in the future.

**Comment by ibreschi** [comment]
@jbaiocchi  
Many thanks for your reply! 

I had the feeling that I was not using something meant to be used officially, but I looked for a C++ profiling API everywhere and I did not found any. I'm open to any suggestion on how to profile my GPU programmatically in C++ with something more suitable. 

Thanks for the suggestion of using the ProfilerSession, it cleaned my code a bit, but  the issue is still there. `memory_profile.memory_profile_per_allocator()` is empty and I don't have any 
event_type == HostEventType::kMemoryDeallocation or event_type == HostEventType::kMemoryAllocation in the plane_gpu.

Here few logs: 
```
2021-04-21 09:24:17.576700: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2021-04-21 09:24:17.576747: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 1 GPUs
2021-04-21 09:24:17.577510: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcupti.so.10.2
2021-04-21 09:24:18.651453: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2021-04-21 09:24:19.245044: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-04-21 09:24:20.036518: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:794] Collecting 4909 kernel records, 427 memcpy records.
2021-04-21 09:24:20.051242: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:223]  GpuTracer has collected 5336 callback api events and 5336 activity events. 
```
 
Could it be an issue of TF 2.3.2 ?

Thanks again

**Comment by jbaiocchi** [comment]
The memory allocation events are not generated by CUPTI but by BFCAllocator::AddTraceMe. Is that code executed?
https://github.com/tensorflow/tensorflow/blob/ccee426384468b152aba22e1a9f9a3fd2f92bf00/tensorflow/core/common_runtime/bfc_allocator.cc

**Comment by ibreschi** [comment]
Yes it's executed.

**Comment by jbaiocchi** [comment]
I think the other bug in your code is that you are looking for the events in the GPU side instead of the host side, try:
```
const XPlane* host_plane = FindPlaneWithName(xspace, "/host:CPU:");
MemoryProfile memory_profile = ConvertXPlaneToMemoryProfile(*host_plane);
```
It would be better to directly call ConvertXSpaceToMemoryProfileJson:
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/profiler/convert/xplane_to_memory_profile.cc

**Comment by ibreschi** [comment]
> ```
> const XPlane* host_plane = FindPlaneWithName(xspace, "/host:CPU");
> MemoryProfile memory_profile = ConvertXPlaneToMemoryProfile(*host_plane);
> ```
Tried this, unfortunately it does not work, I have the same result.

> It would be better to directly call ConvertXSpaceToMemoryProfileJson:
> https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/profiler/convert/xplane_to_memory_profile.cc
I dont think I can because it was introduced in a later version of TF, I use 2.3.2.

**Comment by jbaiocchi** [comment]
The memory profiler was added in 2.3 so you should have the necessary pieces.
More debugging tips:
- Make sure you are not disabling TraceMe (host_tracer_level in ProfilerOptions should be at least 2)
- Make sure the TraceMe's in BFCAllocator::AddTraceMe are actually executed while ProfilerSession is active.
- Debug ConvertXPlaneToMemoryProfile to see why it doesn't find the events (are the events missing or skipped)?
- Take a look at the commit history and see if any bug fixes might apply:   https://github.com/tensorflow/tensorflow/commits/a0f8ebc1cbe599b32461c77b6a538985f00315a2/tensorflow/core/profiler/convert/xplane_to_memory_profile.cc
  In particular:
https://github.com/tensorflow/tensorflow/commit/36d55f1c562e89d0e1eddc0a7d4d79049cabb466#diff-7b16b05d8b0b859750fec0ff5a9aeaa2fba390bfa858421152202ed15eadafd9

**Comment by sushreebarsa** [comment]
@ibreschi Could you please try as per the above comment  and let us know if this issue still persists ? Thanks!

**Comment by ibreschi** [comment]
@sushreebarsa  I did not managed to fix the issue using TF2.3.
I'm trying to compile using 2.4 witch has the commit mentioned above, I'll let you know as soon as I managed to do it.

**Comment by sushreebarsa** [comment]
@ibreschi Could you please let us know if you have tried as per the [comment](https://github.com/tensorflow/tensorflow/issues/48146#issuecomment-824224482) using latest stable version of TF 2.6.0?Please let us know if the issue still persists ?Thanks!

**Comment by MoFHeka** [comment]
RPC profile client is still unable to collect MemoryProfile event from remote worker in latest Tensorflow version.
