### ISSUE TITLE
Filename clashes in /tmp during flatbuffer download

### ISSUE THREAD

**Issue by andrewstevens-infineon** [tensorflow/tensorflow#48155]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 1e8f4666f2fbc1bdd4ce2797b218de0453cffc63
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): all

**Describe the problem**

The script `tensorflow/lite/micro/tools/make/flatbuffers_download.sh` creates a temporary files/dirs in `/tmp`
whose names are not uniqified and not all of which are subsequently removed.  This means builds by different users on a shared server host fail and junk is left lying around in `/tmp`.

A small patch correcting these issues by using `mktemp`  is attached.  This approach is the same
as that used in the  `tensorflow/lite/micro/tools/make/download_and_extract.sh` script.

[tmp_filename_clash_fix.patch.txt](https://github.com/tensorflow/tensorflow/files/6221742/tmp_filename_clash_fix.patch.txt)

**Please provide the exact sequence of commands/steps when you ran into the problem**

make -f tensorflow/lite/micro/tools/make/Makefile

**Comment by advaitjain** [comment]
Thanks for the fix. Created https://github.com/tensorflow/tensorflow/pull/48241 with the path.

Feel free to send a PR as well.
