### ISSUE TITLE
tf. feature_column.input_layer(dataVale, feature_embedding) sometimes gets out of order when processing feature_embedding lists

### ISSUE THREAD

**Issue by CaptainDP** [tensorflow/tensorflow#48151]
When bucketized_column is used to divide buckets and generate one-hot code, the running result is inconsistent with the actual input feature list.

windows10,tensorflow==1.13.1,python==3.7.7

-----------------------------------------python-----------------------------------------------------------
import tensorflow as tf
import json
import pandas as pd

def get_feature_columns(tain_file):
    data = pd.read_csv(tain_file, nrows=5).round(5)
    feature_size = data.columns.shape[0] - 1
    feature_columns = data.columns[:-1].tolist()
    return feature_columns, feature_size

def read_row(csv_row):
    record_defaults = [[0.]] * FEATURE_SIZE + [[0]]
    row = tf.decode_csv(csv_row, record_defaults=record_defaults)
    return dict(zip(FEATURE_COLUMNS, row[:-1])), row[-1]

def _feature_column(COLUMNS):
    with open('./feature_fm_bucket.json', 'r') as f:
        boundary_dict = json.load(f)
    boundary_dict = {k: sorted(x for x in v if abs(x) != float("inf")) for k, v in boundary_dict.items()}
    length = 0
    for kk in boundary_dict:
        length += len(kk)

    feature_embedding = []
    for col in COLUMNS:
        buket_col = tf.feature_column.bucketized_column(
            tf.feature_column.numeric_column(col), boundary_dict[col])
        feature_embedding.append(buket_col)

    return feature_embedding, boundary_dict

feature_name = 'user_click_num_7d'
# FEATURE_COLUMNS = [feature_name]

tain_file = './demo.csv'

FEATURE_COLUMNS, FEATURE_SIZE = get_feature_columns(tain_file)

feature_embedding, boundary_dict = _feature_column(FEATURE_COLUMNS)

TRAIN_FILENAMES = [tain_file]

batch_size = 1
filenames = TRAIN_FILENAMES
dataset = tf.data.Dataset.from_tensor_slices(filenames)
dataset = dataset.flat_map(lambda filename: tf.data.TextLineDataset(TRAIN_FILENAMES).skip(1))
dataset = dataset.map(lambda line: read_row(line), num_parallel_calls=15,
                      ).batch(batch_size).repeat(1)

iterator = dataset.make_one_shot_iterator()
ds = iterator.get_next()
dataVale = ds[0]

order = tf.feature_column.input_layer(dataVale, feature_embedding)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

value = sess.run(order)
first_line_value = value[0]

count = 0
for i, v1 in enumerate(FEATURE_COLUMNS):
    print("line=" + str(i + 1) + ", ", v1, end=', one_hot=[')
    jj = 0
    for j in range(len(boundary_dict[v1]) + 1):
        vv = first_line_value[count]
        count += 1
        print(vv, end=',')
        if vv == 1:
            jj = j

    print(end='], index=')
    print(jj, end='')
    print()
-----------------------------------------------------python-------------------------------------------

-----------------------------------------feature_fm_bucket.json----------------------------------------------------

{"mt_ses_pv_maxmin_30d":[0.01,0.03,0.06,0.1,0.16,0.24,0.37,0.58],"it_uv_15d":[2,5,6,7,8,9,10,11,12],"it_ck_pv_ws_3_30d":[0.04,0.07,0.09,0.11,0.13,0.15,0.18,0.22,0.26,0.31,0.38,0.49,0.64,0.8,0.92,0.96,0.98],"it_ck_pv_ws_3_15d":[0.06,0.1,0.13,0.16,0.19,0.22,0.25,0.28,0.32,0.37,0.43,0.53,0.65,0.8,0.92,0.96,0.98],"rt_it_uv_3h":[1,2,3,4,5,6,7],"it_lk_uv_7":[0.001,0.002,0.003,0.005,0.008,0.01],"it_lk_uv_30d":[0.0005,0.001,0.003],"it_collect_uv_15d":[0.001,0.002,0.003,0.006],"rt_it_fp_ws_st_ro_1_3h":[0.01,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.17,0.19],"it_st_pv_ws_1_3d":[0.27,0.34,0.38,0.41,0.44,0.46,0.48,0.5,0.52,0.54,0.55,0.58,0.6,0.64,0.68,0.75,0.83,0.93],"mt_ses_dur_weight_30d":[0.01,0.02,0.04,0.06,0.1,0.2],"rt_ur_tr":[0.01,0.02,0.03,0.04,0.05,0.07],"it_ck_pv_ws_1_15d":[0.02,0.04,0.06,0.07,0.09,0.1,0.11,0.13,0.15,0.17,0.2,0.24,0.3,0.37,0.47,0.6,0.75,0.88,0.96],"mt_nlp_tag_max":[0.02,0.04,0.05,0.07,0.08,0.1,0.12,0.15,0.17,0.19,0.21,0.24,0.28,0.33,0.41],"it_fp_ck_pv_15d":[5,6,7,8,9,10,11,12],"ur_ck_num_7":[0.7,1,2,2.5,3,3.5,4,4.7],"it_prop_ar_favorites_num":[2,3,4],"rt_it_fp_ws_st_ro_3h":[0.06,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.19,0.2,0.23,0.25,0.29,0.32,0.38],"it_prop_ar_articlenum":[2,3,4],"it_lk_uv_15d":[0.001,0.003,0.005,0.007,0.1,0.2],"rt_mt_it_dgc":[0.57,0.7,0.78,0.83,0.87,0.9,0.92,0.96,0.98],"it_fp_st_pv_7":[7,8,9,10,11,12,13],"it_fp_ck_pv_3d":[4,5,6,7,8,9,10,11],"it_lk_uv_1":[0.0001,0.0002,0.0003,0.0005,0.001,0.003,0.01],"rt_ur_st_show_num":[1,2,3,4,5],"rt_it_pv":[3,4,5,6,7,8],"it_ck_pv_ws_1_30d":[0.01,0.03,0.04,0.05,0.06,0.07,0.08,0.1,0.12,0.14,0.17,0.21,0.27,0.35,0.46,0.6,0.75,0.88,0.96],"mt_ses_pv_weight_7":[0.01,0.02,0.04,0.07,0.13,0.26],"it_fp_st_pv_30d":[7,8,9,10,11,12,13,14],"it_prop_ar_articlenum_4":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1],"it_prop_ar_articlenum_5":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],"it_prop_ar_articlenum_2":[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1],"it_prop_ar_articlenum_3":[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1],"it_fp_ck_pv_30d":[5,6,7,8,9,10,11,12],"rt_it_fp_ck_pv":[3,4,5,6,7,8],"it_rp_uv_3d":[0.001,0.002,0.003,0.004,0.01],"rt_it_fp_ws_ck_ro_3h":[0.01,0.03,0.04,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.15,0.16,0.18,0.21,0.25,0.3],"rt_it_uv":[3,4,5,6,7,8],"rt_mt_ses_wsim_top5":[0.001,0.002,0.003,0.005,0.006,0.008,0.01,0.015,0.02],"it_quality_effect_score":[0.8,0.88,0.93,0.96,0.97,0.98,0.99],"rt_mt_ses_wsim_top1":[0.001,0.002,0.003,0.005,0.006,0.008,0.01,0.015,0.02],"rt_mt_ses_wsim_top2":[0.001,0.002,0.003,0.005,0.006,0.008,0.01,0.015,0.02],"ur_dr_30d":[5,6,7,8],"it_fp_ag_pv_tr_3d":[0.05,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.2],"it_ck_pv_ws_1_3d":[0.19,0.26,0.3,0.34,0.37,0.39,0.42,0.44,0.46,0.48,0.51,0.53,0.56,0.59,0.64,0.7,0.79,0.89,0.97],"mt_ses_dur_weight_15d":[0.01,0.03,0.04,0.07,0.11,0.22],"mt_ses_lst":[1,2],"it_fp_ws_pv_tr_30d":[0.04,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.18],"it_uv_30d":[1,5,6,7,8,9,10,11,12],"it_fp_ag_pv_tr_15d":[0.05,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.2],"mt_ses_ss_7":[1,2,3,5,8],"it_cb_ro_7":[1.12,1.2,1.23,1.27,1.3,1.32,1.34,1.36,1.39,1.41,1.44,1.48,1.51,1.57,1.65,1.82],"rt_it_fp_ws_tr":[0.02,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15],"rt_it_fp_ws_st_ro_1h":[0.01,0.02,0.03,0.04,0.06],"it_quality_rare_score":[0.24,0.38,0.48,0.57,0.63,0.73,0.76,0.79,0.81,0.83,0.86,0.88,0.89,0.91,0.95,0.98,0.99],"it_collect_uv_7":[0.001,0.002,0.004],"mt_ses_dur_15d":[2,3,4,5,6,7],"it_st_pv_ws_3_7":[0.25,0.33,0.37,0.41,0.44,0.46,0.49,0.52,0.55,0.59,0.63,0.7,0.79,0.89,0.97],"it_rp_uv_30d":[0.001,0.002,0.003,0.005,0.011],"mt_ses_dur_30d":[1,2,3,4,5,6,7],"rt_it_fp_ws_ck_ro_1_3h":[0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.12,0.14],"it_fp_ck_pv_1":[3,4,5,6,7,8,9,10],"it_fp_ck_pv_7":[4,5,6,7,8,9,10,11],"rt_it_fp_ck_pv_1h":[1,2,3,4,5],"rt_it_fp_ws_tr_1h":[0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.11],"rt_it_pv_1h":[1,2,3,4,5],"ur_ck_num_30d":[1,2,3,4,5,6],"mt_ses_ss_90d":[1,2,3,4,5,9,12],"it_quality_cover_score":[0.42,0.52,0.53,0.54,0.55,0.56,0.6,0.65],"it_fp_ag_pv_tr_30d":[0.05,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.19],"context_event_hour":[8,12,14,18,21],"it_uv_1":[3,4,5,6,7,8,9,10],"rt_mt_ses_maxmin":[0],"it_uv_7":[1,5,6,7,8,9,10,11,12],"it_rp_uv_15d":[0.001,0.002,0.003,0.005,0.009],"it_rp_uv_1":[0.0005,0.001,0.003],"mt_it_lst_type":[1,2,4,6],"it_st_pv_ws_1_7":[0.09,0.14,0.16,0.19,0.21,0.22,0.24,0.26,0.28,0.3,0.33,0.37,0.41,0.46,0.56,0.67,0.8,0.91],"it_fp_ws_pv_tr_1":[0.03,0.04,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17],"it_fp_ag_pv_tr_1":[0.05,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.2],"rt_mt_ses_sim_lst4":[0.025,0.03,0.04,0.05,0.07,0.09,0.2],"rt_mt_ses_sim_lst5":[0.025,0.03,0.04,0.05,0.07,0.09,0.2],"it_collect_uv_1":[0.001,0.002],"rt_it_pv_3h":[1,2,3,4,5,6,7],"rt_mt_ses_sim_lst1":[0.025,0.03,0.04,0.05,0.07,0.09,0.2],"rt_mt_ses_sim_lst2":[0.025,0.03,0.04,0.05,0.07,0.09,0.2],"rt_mt_ses_sim_lst3":[0.025,0.03,0.04,0.05,0.07,0.09,0.2],"it_prop_ar_comment_num":[2,3,4],"it_lk_uv_3d":[0.0002,0.0003,0.0006,0.002],"ur_dr_7":[5,6,7,8],"rt_mt_ses_wsim_top4":[0.001,0.002,0.003,0.005,0.006,0.008,0.01,0.015,0.02],"it_st_pv_ws_1_15d":[0.04,0.06,0.08,0.09,0.11,0.12,0.14,0.15,0.17,0.2,0.23,0.27,0.33,0.41,0.52,0.66,0.79,0.91],"it_cb_ro_1":[1.11,1.19,1.23,1.26,1.29,1.31,1.34,1.36,1.39,1.41,1.45,1.48,1.52,1.58,1.67,1.86],"it_ck_pv_ws_3_7":[0.19,0.26,0.31,0.35,0.39,0.42,0.44,0.47,0.5,0.54,0.58,0.65,0.73,0.83,0.92,0.96,0.98],"mt_ses_ss_60d":[1,2,3,4,5,9,17],"mt_nlp_sec_tag_avg":[0.03,0.05,0.07,0.09,0.11,0.12,0.14,0.18,0.23,0.33],"rt_ur_ck_num":[1,1.4,1.9,2,2.4,2.7,3],"ur_dr_15d":[5,6,7,8],"rt_it_uv_1h":[1,2,3,4,5],"it_st_pv_ws_3_30d":[0.05,0.08,0.11,0.13,0.15,0.18,0.21,0.25,0.29,0.35,0.43,0.54,0.69,0.88,0.97],"mt_ses_dur_maxmin_15d":[0.02,0.04,0.08,0.13,0.21,0.34,0.55],"it_fp_ws_pv_tr_15d":[0.04,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.18],"it_fp_ag_pv_tr_7":[0.05,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.2],"rt_it_fp_ws_tr_3h":[0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.14],"it_fp_st_pv_3d":[6,7,8,9,10,11,12,13],"rt_it_fp_ck_pv_3h":[1,2,3,4,5,6,7],"rt_mt_ses_wsim_top3":[0.001,0.002,0.003,0.005,0.006,0.008,0.01,0.015,0.02],"ur_ck_num_15d":[1,2,3,4,5],"it_prop_time_decay":[0.12,0.15,0.2,0.24,0.27,0.31,0.36,0.41,0.46,0.5,0.57,0.61,0.65,0.69,0.74,0.77,0.81,0.84],"it_prop_ar_fellowsnum":[2,3,4,5],"it_prop_ar_lk_num":[2,3,4],"mt_ses_pref":[0.01,0.03,0.05,0.07,0.11,0.17,0.29],"it_uv_3d":[1,4,5,6,7,8,9,10,11],"rt_mt_it_weights":[0.06,0.16,0.25,0.33,0.37,0.47,0.5,0.6,0.7],"it_fp_ws_pv_tr_7":[0.04,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.18],"mt_ses_pv_maxmin_7":[0.02,0.05,0.09,0.18,0.32,0.56],"it_ck_pv_ws_1_7":[0.06,0.1,0.12,0.15,0.17,0.19,0.2,0.22,0.24,0.27,0.3,0.33,0.37,0.42,0.51,0.62,0.76,0.88,0.96],"it_rp_uv_7":[0.001,0.002,0.003,0.007],"it_cb_ro_15d":[1.13,1.2,1.23,1.27,1.3,1.32,1.34,1.36,1.39,1.41,1.44,1.47,1.5,1.55,1.62,1.81],"it_fp_ws_pv_tr_3d":[0.03,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.18],"mt_ses_pv_15d":[1,2,3,4,5],"it_cb_ro_30d":[1.13,1.2,1.24,1.27,1.3,1.32,1.33,1.35,1.38,1.4,1.43,1.46,1.5,1.55,1.61,1.78],"mt_ses_pv_weight_30d":[0.01,0.02,0.04,0.06,0.09,0.18],"mt_nlp_tag_num":[1,2,3,6],"mt_ses_ss_15d":[1],"rt_it_fp_ws_ck_ro_1h":[0.0003,0.0008,0.01,0.02,0.03,0.04],"mt_ses_dur_7":[1,3,4,5,6],"mt_ses_pv_maxmin_15d":[0.02,0.04,0.08,0.13,0.22,0.35,0.57],"it_cb_ro_3d":[1.12,1.2,1.23,1.27,1.3,1.32,1.35,1.37,1.4,1.42,1.45,1.49,1.53,1.58,1.65,1.87],"it_quality_time_score":[0.12,0.27,0.39,0.45,0.49,0.54,0.58,0.61,0.65,0.68,0.71,0.74,0.76,0.77,0.78,0.9,0.96],"it_collect_uv_3d":[0.001,0.002,0.003],"it_st_pv_ws_1_30d":[0.02,0.04,0.05,0.06,0.08,0.09,0.1,0.12,0.14,0.17,0.2,0.24,0.31,0.4,0.51,0.66,0.79,0.91],"mt_nlp_tag_avg":[0.02,0.04,0.05,0.06,0.07,0.09,0.1,0.12,0.14,0.16,0.19,0.22,0.26,0.31,0.39],"it_collect_uv_30d":[0.001,0.002,0.003,0.004,0.007],"it_prop_publishtime":[347,422,504,604,722,844,976,1104,1376,1563,1769,2035,2340,2606,2808,3158,3751,4188,16536],"mt_ses_dur_maxmin_30d":[0.01,0.03,0.05,0.09,0.14,0.22,0.34,0.54],"mt_nlp_tag_sum":[0.03,0.05,0.06,0.08,0.11,0.13,0.16,0.18,0.21,0.24,0.28,0.33,0.39,0.49,0.72],"mt_ses_pv_30d":[1,2,3,4,5],"it_prop_ar_share_cnt":[2,3,4],"it_fp_st_pv_1":[6,7,8,9,10,11,12],"mt_ses_ss_30d":[1,2,3,4,5,7,14],"mt_nlp_sec_tag_sum":[0.03,0.06,0.09,0.11,0.14,0.18,0.22,0.28,0.36,0.49],"rt_mt_ses_sim_top4":[0.025,0.029,0.034,0.041,0.049,0.058,0.07,0.086,0.115],"rt_mt_ses_sim_top5":[0.025,0.029,0.034,0.041,0.049,0.058,0.07,0.086,0.115],"mt_ses_pv_7":[1,2,3,4],"mt_ses_pv_weight_15d":[0.01,0.02,0.04,0.06,0.11,0.21],"rt_mt_ses_sim_top1":[0.025,0.029,0.034,0.041,0.049,0.058,0.07,0.086,0.115],"rt_mt_ses_sim_top2":[0.025,0.029,0.034,0.041,0.049,0.058,0.07,0.086,0.115],"rt_mt_ses_sim_top3":[0.025,0.029,0.034,0.041,0.049,0.058,0.07,0.086,0.115],"mt_nlp_sec_tag_max":[0.03,0.06,0.08,0.1,0.12,0.14,0.17,0.21,0.25,0.34],"it_st_pv_ws_3_15d":[0.09,0.13,0.16,0.19,0.22,0.25,0.28,0.31,0.36,0.41,0.47,0.58,0.71,0.88,0.97],"it_fp_st_pv_15d":[7,8,9,10,11,12,13,14],"rt_mt_it_rank":[0.5,0.72,0.85],"mt_ses_dur_weight_7":[0.01,0.02,0.04,0.08,0.13,0.28],"mt_ses_dur_maxmin_7":[0.02,0.05,0.1,0.18,0.32,0.55]}

-----------------------------------------feature_fm_bucket.json----------------------------------------------------

-----------------------------------------demo.csv----------------------------------------------------

context_event_hour,it_cb_ro_15d,it_cb_ro_1,it_cb_ro_30d,it_cb_ro_3d,it_cb_ro_7,it_ck_pv_ws_1_15d,it_ck_pv_ws_1_30d,it_ck_pv_ws_1_3d,it_ck_pv_ws_1_7,it_ck_pv_ws_3_15d,it_ck_pv_ws_3_30d,it_ck_pv_ws_3_7,it_collect_uv_15d,it_collect_uv_1,it_collect_uv_30d,it_collect_uv_3d,it_collect_uv_7,it_fp_ag_pv_tr_15d,it_fp_ag_pv_tr_1,it_fp_ag_pv_tr_30d,it_fp_ag_pv_tr_3d,it_fp_ag_pv_tr_7,it_fp_ck_pv_15d,it_fp_ck_pv_1,it_fp_ck_pv_30d,it_fp_ck_pv_3d,it_fp_ck_pv_7,it_fp_st_pv_15d,it_fp_st_pv_1,it_fp_st_pv_30d,it_fp_st_pv_3d,it_fp_st_pv_7,it_fp_ws_pv_tr_15d,it_fp_ws_pv_tr_1,it_fp_ws_pv_tr_30d,it_fp_ws_pv_tr_3d,it_fp_ws_pv_tr_7,it_lk_uv_15d,it_lk_uv_1,it_lk_uv_30d,it_lk_uv_3d,it_lk_uv_7,it_prop_ar_articlenum,it_prop_ar_comment_num,it_prop_ar_favorites_num,it_prop_ar_fellowsnum,it_prop_ar_lk_num,it_prop_ar_share_cnt,it_prop_publishtime,it_prop_time_decay,it_quality_cover_score,it_quality_effect_score,it_quality_rare_score,it_quality_time_score,it_rp_uv_15d,it_rp_uv_1,it_rp_uv_30d,it_rp_uv_3d,it_rp_uv_7,it_st_pv_ws_1_15d,it_st_pv_ws_1_30d,it_st_pv_ws_1_3d,it_st_pv_ws_1_7,it_st_pv_ws_3_15d,it_st_pv_ws_3_30d,it_st_pv_ws_3_7,it_uv_15d,it_uv_1,it_uv_30d,it_uv_3d,it_uv_7,mt_nlp_sec_tag_avg,mt_nlp_sec_tag_max,mt_nlp_sec_tag_sum,mt_nlp_tag_avg,mt_nlp_tag_max,mt_nlp_tag_num,mt_nlp_tag_sum,mt_ses_ss_15d,mt_ses_ss_30d,mt_ses_ss_60d,mt_ses_ss_7,mt_ses_ss_90d,mt_it_lst_type,mt_ses_dur_15d,mt_ses_dur_30d,mt_ses_dur_7,mt_ses_dur_maxmin_15d,mt_ses_dur_maxmin_30d,mt_ses_dur_maxmin_7,mt_ses_dur_weight_15d,mt_ses_dur_weight_30d,mt_ses_dur_weight_7,mt_ses_lst,mt_ses_pref,mt_ses_pv_15d,mt_ses_pv_30d,mt_ses_pv_7,mt_ses_pv_maxmin_15d,mt_ses_pv_maxmin_30d,mt_ses_pv_maxmin_7,mt_ses_pv_weight_15d,mt_ses_pv_weight_30d,mt_ses_pv_weight_7,ur_ck_num_15d,ur_ck_num_30d,ur_ck_num_7,ur_dr_15d,ur_dr_30d,ur_dr_7,rt_it_fp_ck_pv,rt_it_fp_ck_pv_1h,rt_it_fp_ck_pv_3h,rt_it_fp_ws_ck_ro_1_3h,rt_it_fp_ws_ck_ro_1h,rt_it_fp_ws_ck_ro_3h,rt_it_fp_ws_tr,rt_it_fp_ws_tr_1h,rt_it_fp_ws_tr_3h,rt_it_fp_ws_st_ro_1_3h,rt_it_fp_ws_st_ro_1h,rt_it_fp_ws_st_ro_3h,rt_it_pv,rt_it_pv_1h,rt_it_pv_3h,rt_it_uv,rt_it_uv_1h,rt_it_uv_3h,rt_mt_it_dgc,rt_mt_it_rank,rt_mt_it_weights,rt_mt_ses_maxmin,rt_mt_ses_sim_lst1,rt_mt_ses_sim_lst2,rt_mt_ses_sim_lst3,rt_mt_ses_sim_lst4,rt_mt_ses_sim_lst5,rt_mt_ses_sim_top1,rt_mt_ses_sim_top2,rt_mt_ses_sim_top3,rt_mt_ses_sim_top4,rt_mt_ses_sim_top5,rt_mt_ses_wsim_top1,rt_mt_ses_wsim_top2,rt_mt_ses_wsim_top3,rt_mt_ses_wsim_top4,rt_mt_ses_wsim_top5,rt_ur_ck_num,rt_ur_tr,rt_ur_st_show_num,label
11,1.398,1.374,1.398,1.406,1.404,0.08342,0.08342,0.45096,0.17688,0.17996,0.17996,0.38242,0.0038,0.00282,0.0038,0.00282,0.00322,0.16433,0.15416,0.16416,0.15696,0.16032,11.03429,8.61505,11.03429,9.36134,10.28606,12.83994,10.48414,12.83994,11.21267,12.11637,0.16137,0.14493,0.16137,0.15045,0.15611,0.00209,0.00019,0.00209,0.00015,0.00036,2.0,4.0,4.0,3.0,3.0,4.0,1666,0.435,0.564,0.99997,0.917776,0.63613,0.00308,0.00172,0.00308,0.00168,0.00241,0.09246,0.09246,0.47343,0.19089,0.19325,0.19325,0.39934,11.189,8.722,11.189,9.429,10.335,0.16,0.16,0.16,0.186,0.186,1,0.186,0.0,0.0,0.0,0.0,0.0,1.0,5.784,5.784,3.401,0.313,0.239,0.049,0.031,0.02,0.007,0.0,0.047,4.159,4.159,0.693,0.13,0.1,0.004,0.014,0.011,0.001,4.92,5.308,4.234,7.257,7.105,6.953,6.863,4.174,5.943,0.09343,0.03659,0.32193,0.11717,0.06461,0.10553,0.15844,0.06329,0.37468,6.828,4.111,5.916,6.783,4.007,5.858,0.889,1.0,0.667,0.0,0.024,0.024,0.024,0.024,0.024,0.024,0.024,0.024,0.024,0.024,0.0,0.0,0.0,0.0,0.0,1.946,0.02483,3.714,1

-----------------------------------------demo.csv----------------------------------------------------

The running results are as follows:
In column 108, ur_ck_num_7sub bucket value:
[0.7,1,2,2.5,3,3.5,4,4.7]

The ur_ck_num_7value value in column 108 is initial 4.4.
line=108,  ur_ck_num_7, one_hot=[0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,], index=5;
line=149,  rt_ur_ck_num, one_hot=[0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,], index=4

The ur_ck_num_7 value in column 108 is changed to 114.234.
line=108,  ur_ck_num_7, one_hot=[0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,], index=5：The data has not changed.;
line=149,  rt_ur_ck_num, one_hot=[0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,], index=5：The data changes.

We expected line 108 to change, but it was line 149 where the data changed.

**Comment by Saduf2019** [comment]
@CaptainDP 
We see that you are using 1.13 version of tensorflow, as 1.x is no more supported please upgrade to 2.x [2.4 is the stable version] and let us know if you face any issues.
