### ISSUE TITLE
Using GridSearchCV in BoostedTreesClassifier

### ISSUE THREAD

**Issue by samanemami** [tensorflow/tensorflow#48153]
I'm trying to Implement [GridsearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) on [BoostedTreesClassifier](https://github.com/tensorflow/estimator/blob/781c0d30c6bf100aa174591dd97cb70fc39d294d/tensorflow_estimator/python/estimator/canned/boosted_trees.py#L1933). Since [BoostedTreesClassifier](https://github.com/tensorflow/estimator/blob/781c0d30c6bf100aa174591dd97cb70fc39d294d/tensorflow_estimator/python/estimator/canned/boosted_trees.py#L1933) has not the fit method, is there any alternative to implement the GridsearchCV?

**Comment by rmothukuru** [comment]
@samanemami,
**`Estimators BoostedTreesClassifier`** are not extensively used in **`Tensorflow 2.x Version`**. 

So, . Please check this [Stack Exchange Answer](https://stats.stackexchange.com/a/433880). [This article](https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/) might also help you. Thanks!

**Comment by samanemami** [comment]
@rmothukuru 
`Estimators BoostedTreesClassifier`, instead of `fit `,  has `train`, which is indicated in the [tutorial](https://www.tensorflow.org/api_docs/python/tf/estimator/BoostedTreesClassifier) also. So, it is not possible to implement Sklearn gridsearch as indicated in the [page](https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/), or this [link](https://medium.com/ml-book/neural-networks-hyperparameter-tuning-in-tensorflow-2-0-a7b4e2b574a1) you have sent.
So is there any other solution to add `fit` in order to use the above solutions, or any updates in `Estimators BoostedTreesClassifier`?

**Comment by samanemami** [comment]
I solved the issue by defining a new [estimator](https://github.com/samanemami/TFBoostedTree/blob/main/TFBT.py) which contains the `fit` and `score` method based on the Sklearn standard.
The [proposed](https://github.com/samanemami/TFBoostedTree/blob/main/TFBT.py) script is available on the following repository.
[TFBoostedTree](https://github.com/samanemami/TFBoostedTree/tree/main)
