### ISSUE TITLE
ImportError on Raspberry Pi 4 Model B: cannot import name 'symbol_database' from 'google.protobuf' 

### ISSUE THREAD

**Issue by VasyaSmolyar** [tensorflow/tensorflow#48159]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution: Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
- Raspberry Pi 4 Model B
- TensorFlow installed from binary
- TensorFlow version: 2.4.0
- Python version: 3.7
- Google Protobuf version: 3.15.6

**Comment by amahendrakar** [comment]
@VasyaSmolyar,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem?

Also, take a look at [this comment](https://stackoverflow.com/a/40981878) from a similar StackOverflow query and check if it helps. Thanks!

**Comment by VasyaSmolyar** [comment]
Reinstalling protobuf is not helps at all. I install binary TF from here https://github.com/Qengineering/Tensorflow-Raspberry-Pi/

**Comment by amahendrakar** [comment]
@VasyaSmolyar,
Please follow the [official guide](https://www.tensorflow.org/install/pip#raspberry-pi) while installing TensorFlow and make sure you have all the required dependencies listed in the [system requirements](https://www.tensorflow.org/install/pip#system-requirements). Thanks!
