### ISSUE TITLE
`SignatureDef` of saved Keras models should match the Keras input and output `dict`

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#48157]
**System information**
- TensorFlow version (you are using): 2.6.0-dev20210329
- Are you willing to contribute it (Yes/No): Yes (although I'd need some pointers to where to look for this particular issue)

**Describe the feature and the current behavior/state.**

Currently when saving Keras models using the saved model format, the input and output names in the `SignatureDef` refer to the names of the tensors of the model. Unfortunately these names are not fixes since they depend on implementation details like the number of times the model has been built (this might be problematic during fine tuning). This makes it hard to construct multi input and output models that are intended to be used with saved models during serving or with TFLite.
In contrast to Keras the saved model format and therefore also the TFLite converter do not preserve the output ordering, which makes using a list as output of the Keras model not a valid use. For more information why this leads to problems please see #47927.

It would be great if the `SignatureDef` of the saved model would match the dictionary keys of the input and output of the Keras model or if saved models would preserve the order of inputs and outputs matching Python and Keras:

```python
import tensorflow as tf

def build_model():
    input_tensor = tf.keras.layers.Input((32, 32, 128))
    x = input_tensor

    boxes = tf.keras.layers.Conv2D(4, (3, 3))(x)
    boxes = tf.reshape(boxes, (-1, 4))

    scores = tf.keras.layers.Conv2D(1, (3, 3))(x)
    scores = tf.reshape(scores, (-1,))

    return  tf.keras.Model({"inputs": input_tensor}, {"boxes": boxes, "scores": scores})

model = build_model()
model = build_model()

model.save("/tmp/model")

restored_fn = tf.saved_model.load("/tmp/model")
concrete_fn = restored_fn.signatures["serving_default"]

# Would be great if these would match the Keras model:
# signature_wrapper(*, input_6)
# Args:
#   input: float32 Tensor, shape=(None, 32, 32, 128)
# Returns:
#   {'boxes': <1>, 'scores': <2>}
#     <1>: float32 Tensor, shape=(None, 4)
#     <2>: float32 Tensor, shape=(None,)

# Instead the keys are layer names which depends on implementation details and on how often the model
# was instantiated: (e.g input_6, tf.reshape_8, tf.reshape_9)
print(concrete_fn.pretty_printed_signature())
```

To make this work currently one needs to use the following workaround which requires users to learn about the low-level `tf.function` API despite that all the information was already present in the Keras model:
```python
@tf.function(input_signature=[tf.TensorSpec([None, 32, 32, 128], dtype=tf.float32, name="input")])
def override_output_signatures(input_tensor):
   outputs = model(input_tensor)
   return {"boxes": outputs["boxes"], "scores": outputs["scores"]}

signatures = override_output_signatures.get_concrete_function()
tf.saved_model.save(model, export_dir="/tmp/saved_model", signatures=signatures)
```

For a complete reproducible example please see [this notebook](https://colab.research.google.com/drive/1CtZ0O7vNN6ODCQfSlon92JDNzfN9FQPe?usp=sharing).

**Will this change the current api? How?**
This proposal wouldn't require any the API changes on the Python side since this usage is already supported in Keras, however it might change the names of serialized multi input/output models. However, I don't think this is a problem in general since currently Keras saved models do not have deterministic output naming either.

**Who will benefit with this feature?**

People working with multi input and output models that require serialization to saved models would greatly benefit from a way to easily set function signatures when saving Keras models. For more motivation for TFLite users, please see #47927.

**Comment by abattery** [comment]
The signature def API is designed intentionally without having an intuitive order. It would be better to stick with the naming instead of the order.

**Comment by abattery** [comment]
I think this is a problem of exporting the given keras model to the corresponding saved model, which means that this is not related to TFLite.

**Comment by Mr-Grieves** [comment]
I am trying to use this to solve an issue we are experiencing with TF rearranging the output order of our Keras models (it seems to always want them to be in alphabetical order), but unfortunately your workaround still re-orders the outputs...

If I reproduce your example, but swap the output order so that "scores" is first, the original signature is in the correct order, but does not contain the names:
```python
from collections import OrderedDict
import tensorflow as tf

def build_model():
    input_tensor = tf.keras.layers.Input((32, 32, 128))
    x = input_tensor

    scores = tf.keras.layers.Conv2D(1, (3, 3))(x)
    scores = tf.reshape(scores, (-1,))

    boxes = tf.keras.layers.Conv2D(4, (3, 3))(x)
    boxes = tf.reshape(boxes, (-1, 4))

    return tf.keras.Model({"inputs": input_tensor}, {"scores": scores, "boxes": boxes})

model = build_model()
model.save("/tmp/model")
restored_fn = tf.saved_model.load("/tmp/model")
concrete_fn = restored_fn.signatures["serving_default"]
print(concrete_fn.pretty_printed_signature())
```
Prints:
```
  Args:
    input_1: float32 Tensor, shape=(None, 32, 32, 128)
  Returns:
    {'tf.reshape': <1>, 'tf.reshape_1': <2>}
      <1>: float32 Tensor, shape=(None,)
      <2>: float32 Tensor, shape=(None, 4)
```

Whereas, with your workaround, the signature contains the names, but is out-of-order (I'm trying to force `scores` to appear first): 

```python
@tf.function(input_signature=[tf.TensorSpec([None, 32, 32, 128], dtype=tf.float32, name="input")])
def override_output_signatures(input_tensor):
   outputs = model(input_tensor)
   return OrderedDict([("scores", outputs["scores"]), ("boxes", outputs["boxes"])])

signatures = override_output_signatures.get_concrete_function()
tf.saved_model.save(model, export_dir="/tmp/saved_model", signatures=signatures)
print(tf.saved_model.load("/tmp/saved_model").signatures["serving_default"].pretty_printed_signature())
```
Prints:
```
  Args:
    input: float32 Tensor, shape=(None, 32, 32, 128)
  Returns:
    {'boxes': <1>, 'scores': <2>}
      <1>: float32 Tensor, shape=(None, 4)
      <2>: float32 Tensor, shape=(None,)
```

Any suggestions on how to alter your workaround to force consistent output order?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
