### ISSUE TITLE
Python tensorflow and tensorflow-cpu dependencies

### ISSUE THREAD

**Issue by adriangb** [tensorflow/tensorflow#48165]
Although undocumented, it seems that the [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/) package is meant to be a CPU-only version of tensorflow to enable smaller package sizes.

Given that there is no dependency relationship between `tensorflow-cpu` and `tensorflow`, ecosystem libraries have no way of specifying that they need either package (see for example [this issue](https://discuss.python.org/t/conditional-package-install-depending-on-other-packages-in-environment/4140)).

In hindsight, the most obvious solution would have been to make a `tensorflow-core` package or something, but idk if that's possible without a lot of work or breaking things.

I'm not sure what the solution is here, but I just wanted to raise the issue.

**Comment by bhack** [comment]
There was an old  similar thread at https://github.com/tensorflow/tensorflow/issues/7166

**Comment by adriangb** [comment]
I see, thank you for linking me! Indeed it does seem like the same issue. It's unfortunate that no resolution was reached.

**Comment by adriangb** [comment]
I'll close this since it really is a dupe of #7166, resolution or not
