### ISSUE TITLE
tensroflow 0.11rc conflict with boost.python generated so

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#4816]
My application will use both tensorflow and some so generated by boost.python(1.53) running on centos 6.3 with cuda 7.5 and cudnn 4 .
The problem is everything is fine with tensorflow 0.10, but changing to tensorflow 0.11rc, then 
I will always face segmentation fault (double free) before the program stop running, especially if using numpy also, and if changing import library sequence  might decrease the chance of facing double free, but still not fully solve the problem.

**Comment by tatatodd** [comment]
@chenghuige As we have limited resources, we can only provide support for specific bugs in TensorFlow.

Feel free to reply with a specific reproducible scenario if you feel there is a bug in TensorFlow that we can fix.  Thanks!
