### ISSUE TITLE
Time Series Prediction Bug

### ISSUE THREAD

**Issue by mgmanzanillo** [tensorflow/tensorflow#48177]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Anaconda Distribution
- TensorFlow version (use command below): unknown 2.3.0
- Python version: 2.8.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` 

**Describe the current behavior**
****
WARNING:tensorflow:AutoGraph could not transform <bound method split_window of Total window size: 22
Input indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label indices: [21]
Label column name(s): ['Temperature_mean']> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method split_window of Total window size: 22
Input indices: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label indices: [21]
Label column name(s): ['Temperature_mean']> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(TensorSpec(shape=(None, 21, 6), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 1, 1), dtype=tf.float32, name=None))

**Describe the expected behavior**
****
According to the tutorial this should be the output:
(TensorSpec(shape=(None, 6, 19), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 1, 1), dtype=tf.float32, name=None))

**Standalone code to reproduce the issue**
****
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Following this TF tutorial: https://www.tensorflow.org/tutorials/structured_data/time_series#2_split
The error happens in "w1.train.element_spec" part

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@mgmanzanillo,
I did not face any errors while running the code with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/e7f299f46e51b6f0b9eb645b307a4369/time_series.ipynb#scrollTo=daJ0-U383YVs&line=2&uniqifier=1) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/d4ce2e1745ce9bd39745f21469f4d4c2/48177-2-4.ipynb#scrollTo=daJ0-U383YVs&line=1&uniqifier=1). Please check the linked gist for reference.

Regarding the warning messages, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/47802#issuecomment-799555152) from issue #47802 and check if it helps. Thanks!
