### ISSUE TITLE
tf.cast zeroes out input tensor

### ISSUE THREAD

**Issue by specke** [tensorflow/tensorflow#48171]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but a stock example would fail too, e.g. "style_transfer.ipynb" fails on my setup when trying to convert image into a floating point tensor.
- OS Platform and Distribution: Windows 7, 64 bit
- TensorFlow installed from: binary, installed using command "pip install tensorflow==2.3.2"
- TensorFlow version: v2.3.1-38-g9edbe5075f7 2.3.2
- Python version: WinPython64 ver.3.8.7.0cod (Python version 3.8.7)
- CUDA/cuDNN version: CUDA Version 10.1.243, i.e. 10.1 update 2 / cuDNN ver.7.6.5.32
- GPU model and memory:  Nvidia Geforce GTX 750 TI, memory: 2GB

**Describe the current behavior**
CUDA is successfully recognized by the TensorFlow - I get the following message when the TensorFlow is started:
`(2021-03-29 22:59:14.061267: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll)`
CUDA also runs its own basic self-tests without apparent issues.

Unfortunately, when I am trying to run more complex code, error messages are generated (e.g. when trying to run TensorFlow's style transfer tutorial "style_transfer.ipynb". I traced the issue to the casting of integer numbers to floating point numbers, which generates the floating point zeros. There was an earlier bug described here: https://github.com/tensorflow/tensorflow/issues/14147 which sounds similar.

However, I do not seem to need to use a lot of GPU memory to trigger the issue. Even the following very basic test:
```
import tensorflow as tf
ivalue = tf.constant(10)
print(ivalue)
fvalue = tf.cast(ivalue, tf.float32)
print(fvalue)
```
produces output

```
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(0.0, shape=(), dtype=float32)
```
However, if I disable the CUDA acceleration by issuing the following commands at the start of my script:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```
the script works correctly, as expected.

**Describe the expected behavior**

I expect the script above to output
```
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(10.0, shape=(), dtype=float32)
```
without having to disable CUDA.

**Standalone code to reproduce the issue**
Please see above. Please let me know if I need to run a more complex code to help identify what is wrong more precisely.

**Other info / logs**
I actually attempted to install several combinations of versions of TensorFlow and CUDA, trying to see if it will make any difference. Specifically, I tried installing TensorFlow 2.2.0, 2.3.0 and 2.3.2 with various minor versions of CUDA 10.1 and cuDNN 7.6. It made no difference at all.

**Comment by saikumarchalla** [comment]
@specke  I tried to reproduce the issue with  TF version 2.3 and 2.4 as well  but I am not experiencing any issues and it is working as expected. 
```
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(10.0, shape=(), dtype=float32)
```
Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/882dda21d65b19c1c2c33fd9442d045a/-48171.ipynb).Thanks!

**Comment by specke** [comment]
I understand that this must be specific to my setup - otherwise you will have thousands more people complaining!

So it has something to do with how TF connects to GPU on my machine. Can you at least recommend the debugging process in this situation? As in: since I already happen to have the setup where things do not work as expected, I would like to at least try to identify what the actual issue is.

**Comment by saikumarchalla** [comment]
@specke  Could you please  create a virtual environment and test your code again. May be that works. Thanks!

**Comment by specke** [comment]
@saikumarchalla, my apologies for the delay. This is the record of what happens when I create a new virtual environment, install TensorFlow ver.2.3.1 onto it and try to run the commands above:
[tf_cuda_bug.log](https://github.com/tensorflow/tensorflow/files/6267680/tf_cuda_bug.log).

I did not try using TensorFlow ver,2.4 because it requires CUDA 11.0, which does not support Windows 7. I can try installing it and running it, of course, but I thought that using a supported combination of versions of TensorFlow, CUDA and cuDNN is important.

**Comment by saikumarchalla** [comment]
@specke Is it still an issue at your end  and please let us know.

**Comment by specke** [comment]
Yes, it is still an issue, I am awaiting for a tensorflower since 12th of April. CUDA-enabled Tensorflow is unusable on my setup.

**Comment by jvishnuvardhan** [comment]
@specke Is this still an issue for you? Can you please check with recent TF versions and let us know whether it was resolved for you. 

If you are still facing the issue, it is better to uninstall all cuda related files, restart, and reinstall cuda libraries. Another option is to install conda package and then install related cuda tools. Thanks!
