### ISSUE TITLE
Difference between android and iOS inference result

### ISSUE THREAD

**Issue by Fedour** [tensorflow/tensorflow#48170]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, no example code found
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 11.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 6 & iPhone8
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): TensorflowLite Objective C

**Context**

I'm currently working on an object detection on mobile project.
I have good result with tensorflowlite on android but we are facing a problem on ios.

I am using the objective-c version of tensorflow lite because I get the images from[ react-natice-camera](https://github.com/react-native-camera/react-native-camera) which is also coded in objective-c.

**Expected behavior**

I expect to have same inference result on iOS and android detection (classname, confidence and bbox location) but the results are very different on iOS. 
In fact 50% of the detections are the same but the other 50% are different. The locations of the bbox reaches very high values (> 1.56^31 e.g.) while the value must be between 0 and 1.

Some example of result:

| Android bbox (x1,y1,x2,y2) |  iOS bbox (x1,y1,x2,y2)| Notes|  
|---|---|---|
| 0.291 - 0.328 - 0.325 - 0.445  |  0.29 - 0.331 - 0.3257- 0.445 | same |  
| 0.295 - 0.509 - 0.327 - 0.600  |  0.292 - 0.511 - 0.327- 0.600 | same |  
| 0.295 - 0.493 - 0.550 - 0.582   |  0.0- 0.0 - 0.0- 0.0 |  different, but almost same classe & confidence | 
| 0.311 - 0.423 - 0.511 - 0.542   |  0.0- 5.56e^10 - 0.0- 0.0 |  overflow ?, but almost same classe & confidence | 

## Some part of the objective C code

Same images are used in android and objective c
Images are in rgb converted in grayscaled

Images are ing RGBA format

I don't use quantisized model so pixel are stored in float32 array

**Pre processing the image**

```
    float* array = malloc((320*320*3) * sizeof(float));
    int count = 0;
    for (int i = 0 ; i < height*width ; ++i)
    {
       
        int r   = ((int) rawData[byteIndex] );
        int g = ((int) rawData[byteIndex + 1] );
        int b  = ((int) rawData[byteIndex + 2] );

        byteIndex += 4; //passing to next rgba tuple
        
        float gray = r * 0.3f + g *0.59f + b*0.11f;
        gray = (gray - 127.5)/127.5;

        array[count++]=gray;
        array[count++]=gray;
        array[count++]=gray;
    }
```

This code is ok, I've done a lot of test with custom image.

I've already check this [issue](https://github.com/tensorflow/tensorflow/issues/40442) but nothing change

**Get inference result**

I use a SSDMobileNetV2 with [mnasFPN ](https://arxiv.org/pdf/1912.01106.pdf)network so I have 4 tensors output (classe, confidence, bbox locations, nb detections)

I retrieve the inference data with this code:

```
    //Getting input tensor
    TFLTensor *inputTensor = [interpreter inputTensorAtIndex:0 error:&error];

    //Copying input data into input tensor
    [inputTensor copyData:dataIm error:&error];

    //Executing model
    [interpreter invokeWithError:&error];
    
    //Getting the 4 output tensors
    TFLTensor *outputLocations = [interpreter outputTensorAtIndex:0 error:&error];
    TFLTensor *outputClasses = [interpreter outputTensorAtIndex:1 error:&error];
    TFLTensor *outputScore = [interpreter outputTensorAtIndex:2 error:&error];
    TFLTensor *outputNumDetections = [interpreter outputTensorAtIndex:3 error:&error];
    
    //Converting to NSData
    NSData* dataOutputLocations = [outputLocations dataWithError:&error];
    NSData* dataOutputClasses = [outputClasses dataWithError:&error];
    NSData* dataOutputScore = [outputScore dataWithError:&error];
    NSData* dataOutputNumDetections = [outputNumDetections dataWithError:&error];

    //Converting NSData to float array

    float numDetections;
    [dataOutputNumDetections getBytes:&numDetections length:(sizeof(float))];
    
    float outputLocArray[(int)numDetections * 4];
    float outputClassArray[(int)numDetections];
    float outputScoreArray[(int)numDetections];
    
    [dataOutputLocations getBytes:&outputLocArray length:(sizeof(float))*numDetections];
    [dataOutputClasses getBytes:&outputClassArray length:(sizeof(float))*numDetections];
    [dataOutputScore getBytes:&outputScoreArray length:(sizeof(float))*numDetections];

    //store final result into Dictionnary
    NSMutableArray* results = [NSMutableArray array];
    for(int i = 0; i < (int) numDetections; i++)
    {
        
        int detected_class = (int) outputClassArray[i];
        float score = outputScoreArray[i];
        float ymin = fmax(0,outputLocArray[i*4]);
        float xmin = fmax(0,outputLocArray[i*4+1]);
        float ymax = outputLocArray[i*4+2];
        float xmax = outputLocArray[i*4+3];
        
        if(score > 0.0f)
        {
            NSMutableDictionary* res = [NSMutableDictionary dictionary];
            NSString* classname = [@(detected_class) stringValue];
            
            [res setObject:classname forKey:@"classname"];
            [res setObject:@(score) forKey:@"confidence"];
            [res setObject:@(xmin) forKey:@"xmin"];
            [res setObject:@(xmax) forKey:@"xmax"];
            [res setObject:@(ymin) forKey:@"ymin"];
            [res setObject:@(ymax) forKey:@"ymax"];
  
            

            [results addObject:res];
        }
    }
```

By doing this I have the strange result above, with float value which seems to overflow.

I couldn't find an example code in objective-c so I'm not sure what is wrong.
Maybe a conversion error?

**Comment by abattery** [comment]
@yyoon could you take a look?

**Comment by tilakrayal** [comment]
@Fedour,
When converting your trained model into tflite format, did you use quantization, or just the float model? If you were using a float model, https://github.com/tensorflow/tensorflow/issues/40442 might have been the cause. If you were using a quantized model, we may need to investigate further to find the root cause.

Another possibility is that this is caused by the difference in the way image is pre-processed before fed into the model. IIUC, the image is cropped and then resized in the Android app, whereas the iOS app does not properly crop the image.
Also please take a look at this comment from the contributor for the [reference](https://github.com/tensorflow/tensorflow/issues/40518#issuecomment-650582285). Thank you!
