### ISSUE TITLE
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard contains broken links

### ISSUE THREAD

**Issue by atn832** [tensorflow/tensorflow#48174]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard

## Description of issue (what needs changing):

The doc for the `embeddings_metadata` argument contains a broken link. It says "See the details about metadata files format.", and the link redirects to https://www.tensorflow.org/how_tos/embedding_viz/#metadata_optional, which is broken.

**Comment by rmothukuru** [comment]
@atn832 ,
Can you please share us the exact link where **`embeddings_metadata`** was located, so that we can fix it? Thanks!

**Comment by alphaX86** [comment]
@rmothukuru maybe I'll look on this. Actually what @atn832 is trying to say that the in the TensorBoard docs, the `embeddings_metadata` has an link for reference but seems it's broken. So it must be either replaced or removed

**Comment by alphaX86** [comment]
![image](https://user-images.githubusercontent.com/59508546/114260761-7fcad000-99f4-11eb-859d-bb261a9a93bd.png)

**Comment by alphaX86** [comment]
So, I'd like to take this... may I know what it needs to be done? Look at the site and suggest me

**Comment by alphaX86** [comment]
Hmm, I'll make a PR on this so that it'll be clear
