### ISSUE TITLE
#Question on efficient data input pipeline.

### ISSUE THREAD

**Issue by Zardoua-Yassir** [tensorflow/tensorflow#48185]
Hello,
I trained a small ML model, where I created and extracted training data in a Pythonic way. According to TF docs, it seems there is an efficient alternative using the module tf.data. I'm learning about tf.data from a Stanford Gitbub code written in TF Version 1. Thus, it is necessary o use tf.compat.v1 to use these commands on TF version 2. Since my goal is to build efficient solutions, is it still a good idea to learn these tf.compat.v1 commands or their purpose is solely to migrate codes written in TF v1 to TFv2?

**Comment by Saduf2019** [comment]
@Zardoua-Yassir 
We have V2 version for all V1 functions, you should look out at the V2 implementation in the API docs to modify current model,
request you to refer to this [link](https://www.tensorflow.org/guide/upgrade) and move this issue to closed status and open an issue in [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) in case of any further queries as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.

Thanks!

**Comment by Zardoua-Yassir** [comment]
Thank you for the kind answer. I'm closing this issue
