### ISSUE TITLE
Minor updates to documentation 

### ISSUE THREAD

**Issue by freddan80** [tensorflow/tensorflow#48183]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): N/A
- Tensorflow version (commit SHA if source): 899fdb415dc970d5bca7d98a7dddf95968ef07c2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): N/A

**Describe the problem**
Some documentation is outdated and needs an update.
The memory mgmt markdown needs an update regarding offline planned tensor allocations.

**Please provide the exact sequence of commands/steps when you ran into the problem**
N/A

**Comment by amahendrakar** [comment]
@freddan80,
Looks like PR [#48184](https://github.com/tensorflow/tensorflow/pull/48184) has been merged successfully. 

Is this still an issue? Please feel free to close the issue if resolved. Thanks!
