### ISSUE TITLE
Broken Link in MLIR docs

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#48189]
## URL(s) with the issue:

https://www.tensorflow.org/mlir

<img width="1406" alt="Screen Shot 2021-03-30 at 10 25 10 PM" src="https://user-images.githubusercontent.com/8815362/112996050-cc1d4100-91a6-11eb-8b25-54934afe1d09.png">

`MLIR on GitHub` box link is broken. That link is pointing `https://github.com/llvm/llvm-project/tree/master/mlir` that returns 404. I think `https://github.com/llvm/llvm-project/tree/main/mlir` is valid link.

**Comment by Saduf2019** [comment]
@jeongukjae 
Created a PR to fix this issue, this issue will be closed once the [PR](https://github.com/tensorflow/tensorflow/pull/48215) is merged.
