### ISSUE TITLE
@tf.function in TF2.x

### ISSUE THREAD

**Issue by Alok-Ranjan23** [tensorflow/tensorflow#48197]
Where is tf.function defined? 
Where can I see its implementation?
How can it be invoked (as a decorator) when we compile the model using TF.Keras?

**Comment by Saduf2019** [comment]
@Alok-Ranjan23 
1) & 2) Please refer to [this link](https://www.tensorflow.org/api_docs/python/tf/function) for the function details.
3) When you compile a keras model it is invoked internally until and unless you specify the run_eagerly argument to be true.

For any further queries on this kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!
