### ISSUE TITLE
Getting sub-layer output of a custom layer breaks in a Tensorflow 2.4.1

### ISSUE THREAD

**Issue by DSamuylov** [tensorflow/tensorflow#48196]
**System information**
- Custom code:

```
class MyCustomLayer(keras.layers.Layer):
    def __init__(self, num_filters=64, kernel_size=3):
        keras.layers.Layer.__init__(self)
        self.conv_1 = keras.layers.Conv2D(filters=num_filters, kernel_size=kernel_size)
        
    def call(self, inputs):
        return self.conv_1(inputs)

x = keras.Input(shape=(None, None, 3))
my_custom_layer = MyCustomLayer()
y = my_custom_layer(x)
```

- OS Platform and Distribution: Mac OS Big Sur v 11.2.2, Linux Ubuntu 20.04
- TensorFlow installed from binary
- TensorFlow version: code fails using TF 2.4.1, but it works using TF  2.3.1
- Python version: 3.8

**Describe the current behavior**

The following line works:

```
my_custom_layer.output
# Out: <KerasTensor: shape=(None, None, None, 64) dtype=float32 (created by layer 'my_custom_layer')>
```

The following line breaks in Tensorflow 2.4.1:
```
my_custom_layer.conv_1.output
```

However, it works in Tensorflow 2.3.1 without any problem.

**Describe the expected behavior**

`my_custom_layer.conv_1.output` should return the output tensor of the convolutional layer.

**Standalone code to reproduce the issue**

Link to Colab: https://colab.research.google.com/drive/16a2IZfzrv4V0oOdxWp3ctt0VOj3wkyaI?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-74d9fc3b4fbb> in <module>
----> 1 my_custom_layer.conv_1.output

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in output(self)
   2152     """
   2153     if not self._inbound_nodes:
-> 2154       raise AttributeError('Layer ' + self.name + ' has no inbound nodes.')
   2155     return self._get_node_attribute_at_index(0, 'output_tensors', 'output')
   2156 

AttributeError: Layer conv2d has no inbound nodes.
```

Here there is the question that I initially raised on stackoverflow: https://stackoverflow.com/questions/66872434

**Comment by amahendrakar** [comment]
@rmothukuru,
I was able to run the code without any errors with [TF v2.3.2](https://colab.research.google.com/gist/amahendrakar/fd243f4375b1d4082dedbc19d6e2ae62/48196-2-3.ipynb). 

However with [TF v2.4.1](https://colab.research.google.com/gist/amahendrakar/b67fd59f860e8513b0f9286c058370ab/48196.ipynb#scrollTo=uZScYo7BRcNM) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/66c6be46befdc6e73073c1ab6c50199f/48196-tf-nightly.ipynb), I am facing an error stating `AttributeError: Layer conv2d has no inbound nodes.`. Please check the linked gist for reference. Thanks!

**Comment by cecabert** [comment]
Run into the exact same issue in #46605. Apparently it is consider as a *feature* and not a bug. However it makes impossible to access any layer's output once the model has been created.

**Comment by cecabert** [comment]
Any update on this issue, or we just have to live with it?

**Comment by sachinprasadhs** [comment]
There has been many changes have been made in the keras Layers behavior and so the error which you are facing. 
You can follow [this](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer?version=nightly) document which explains the methods and the arguments which can be used in subclassed layer. Thanks!
