### ISSUE TITLE
High Inference time on warmup state in android  

### ISSUE THREAD

**Issue by Humza1996** [tensorflow/tensorflow#48190]
**System information**
- OS Platform and Distribution (Windows 10 Pro/Andriod 10,11):
- Mobile device (Redmi note 8)
- TensorFlow installed from (source or binary): tflite .so built from source
- TensorFlow version: 2.4
- Python version: 3.8

**Problem:** I am working on Real time Audio processing application in android studio. I made a model using LSTMs and converted the model to the TFLITE format. After that when I tested model by giving some data it gives inconsistent inference time every time. Model inference time is 3-4ms. If I run inference in a loop, 3-4ms is the average inference time. If I shift towards the real-time scenario, I have to perform inference every 10ms. My inference time increases in this scenario. This is probably because the inference is not running back to back but actually waits till we get audio data again (10ms callback -3ms inference time = 7ms wait in thread for more audio data). I read on tensorflow site (https://www.tensorflow.org/lite/performance/measurement) that this is due to the warmup state and steady state. For warmup state it gives 9ms inference time and on steady state it gives almost 3ms inference time. But in my case, since audio is coming continuously and I want the model to run in steady state. Is there any way to run the TFLITE model in steady state once its loaded in the application ? 
   

**Describe the current behavior**
Android tflite model warmup everytime when inference function is called
**Describe the expected behavior**
Android tflite model should warmup once at start and stay in steady state after that.

I run the model on tensorflow benchmark tool with and without delay. When I run model without any delay it gives avg 2ms time for inference. When I put 5ms delay between each inference then model inference time inreased to 6ms. Please refer to screenshots below:

**Without any delay**
![without delay](https://user-images.githubusercontent.com/63999516/113251302-80b87f00-92db-11eb-9a7f-1f160c506476.png)

**With 5ms delay between each inference**
![with 5m delay](https://user-images.githubusercontent.com/63999516/113251321-87df8d00-92db-11eb-9a71-56d535b7558a.png)

Any help is greatly appreciated, thank you!

**Comment by abattery** [comment]
@srjoglekar246 could you take a look?

**Comment by Humza1996** [comment]
@impjdi @ymodak Please reveiw

**Comment by amahendrakar** [comment]
@Humza1996,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet so that we can reproduce the issue on our end. Thanks!

**Comment by Humza1996** [comment]
@amahendrakar Please find below
**loadModelFile** is loading function
If I use **tflite.runForMultipleInputsOutputs(inputs, outputs);** it gives high inference time i.e 13-14 ms
But when I run this line in for loop it gives me around 3-4ms inference time. Althou I have declared tflite outside the while loop. 


`private MappedByteBuffer loadModelFile() throws IOException {
        AssetFileDescriptor fileDescriptor = this.getAssets().openFd("lstm.tflite");
        FileInputStream fileInputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = fileInputStream.getChannel();
        long startOffSets = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffSets, declaredLength);
    }
    
Interpreter tflite;
float[][][] model_output;
float[][][][] model_st;
private void foo() {
        Thread bar = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    tflite = new Interpreter(loadModelFile());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                while (true) {
                    float[] data = network.getData(); // blocking call // Audiorecord is being used in the audioHandler Object // Data is returned every 10ms
                    
                    Object[] inputs = {data, states};
                    outputs.put(0, model_output);
                    outputs.put(1, model_st);
                    
                    /////////// Inference ////////////////
                    tfLiteLock.lock();
                    try {
                        tflite.runForMultipleInputsOutputs(inputs, outputs);
                    } finally {
                        tfLiteLock.unlock();
                    }
                    System.out.println("inference_time",""+tflite.getLastNativeInferenceDurationNanoseconds())
                    
                    //Computing 
                    //for(int i=0;i<500;i++){
                    
                    //try {
                    //  tflite.runForMultipleInputsOutputs(inputs, outputs);
                    //} finally {
                    //  tfLiteLock.unlock();
                    //}
                    
                    //System.out.println("inference_time",""+tflite.getLastNativeInferenceDurationNanoseconds())
                    //}
                    
                    foo.bar(model_output); 
                }
            }
        });
        bar.setPriority(Thread.MAX_PRIORITY);
        bar.start();`

**Comment by Humza1996** [comment]
@amahendrakar any update ?

**Comment by abattery** [comment]
I replied at the same question posted at https://stackoverflow.com/questions/66882466/high-inference-time-on-warmup-state-in-android-studio

**Comment by Humza1996** [comment]
@abattery Thankyou for your feedback but I am not able to solve the issue. Model is working fine when its run in a continuous loop (without any delay). Pipeline is, app gets voice data  and take its FFT. Then pass it to the model. Model outputs some data and I take IFFT of that data. Issue is , when there is a delay of getting microphone data, model takes long time for prediction as well. I guess model terminate itself or go on sleep. I want , model should take same time for everytime irrespective of input delay.

**Comment by abattery** [comment]
Model does not terminates and goes on sleep unless the inference object is destroyed. Instead, the related memory space can be evicted from the cache menory, which can impact the latency.

TFLite model is just another program so it also is under controlled by CPU scheduling and its performance is related to the memory usage patterns. So, in my view point, it is kind of complicated problems and hard to analyze the overall behaviors with the limited information. To get the consistent result, I suggest doing some more experiments on the runtime environments, model's characteristics, and threading strategy.

Also you can relay on the other performance techniques, model optimizations and hardware acceleration paths in order to reduce overall latency.

**Comment by Humza1996** [comment]
@abattery I have tested all optimizations technique to the model. Now my model is fully optimized and in [Quantized form](https://www.tensorflow.org/lite/performance/post_training_quantization#:~:text=Post%2Dtraining%20quantization%20is%20a,little%20degradation%20in%20model%20accuracy.).

**Comment by abattery** [comment]
@multiverse-tf any thoughts on https://github.com/tensorflow/tensorflow/issues/48190#issuecomment-812831324 ?

**Comment by Humza1996** [comment]
@rjpower @gbaned Please check this [comment](https://github.com/tensorflow/tensorflow/issues/48190#issuecomment-812831324)

**Comment by rjpower** [comment]
I'm not sure, this looks TF-Lite specific, so perhaps someone from that team can chime in.

My guess for why the performance is different: by sleeping between inferences, you are letting the CPU state drop back to idle. When the inference request starts, the task then has to wake up before it can run the inference. So this is giving you an idea of how much time the model takes if it is starting "cold".

**Comment by srjoglekar246** [comment]
CC'ing @multiverse-tf who might know more.

**Comment by Humza1996** [comment]
@multiverse-tf Please see the [comment](https://github.com/tensorflow/tensorflow/issues/48190#issuecomment-812831324)

**Comment by multiverse-tf** [comment]
> @multiverse-tf Please see the [comment](https://github.com/tensorflow/tensorflow/issues/48190#issuecomment-812831324)

Acked. I agree w/ @rjpower's [comment](https://github.com/tensorflow/tensorflow/issues/48190#issuecomment-813453287) above that "sleeping between inferences, you are letting the CPU state drop back to idle" and then the "CPU" starts "cold" in terms of CPU frequency or execution being gradually migrated from little core to big core etc. Note CPUs on mobile phones are prone to being throttled to save power consumption.

To validate this idea, if possible, could you lock the CPU frequency and set the cpu affinity (see [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#reducing-variance-between-runs-on-android) for reference) and check the perf. again?

Btw, I noticed "tfLiteLock.lock()" and "tfLiteLock.unlock();" in the code you pasted above. Just wondering whether the locking here will introduce additional overhead here or not.
