### ISSUE TITLE
Regenerate Keras Python code based on model.summary() 

### ISSUE THREAD

**Issue by notsinkingtitanic** [tensorflow/tensorflow#48191]
Is it possible to generate python code based on model.summary() information, the generated code (maybe write it to `filename.py` file) is the regular Keras model Sequential like the following:

```
model = Sequential()
model.add(Conv1D(filters=256, kernel_size=5, padding='same', activation='relu',
                 input_shape=(time_window_size, 1)))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(64))
model.add(Dense(units=time_window_size, activation='linear'))
model.compile(optimizer='adam', loss='mean_squared_error', metrics=[metric])
model.compile(optimizer='adam', loss='mean_squared_error', metrics=[metric])
model.compile(optimizer="sgd", loss="mse", metrics=[metric])
```

I am sure someone somewhere did it but I searched GitHub and Google and could not find it, you may have already came across such function. Please share your thoughts.

**Comment by jvishnuvardhan** [comment]
@notsinkingtitanic AFAIK, there is no API that currently supports conversion of `model.summary()` to a model. I think it will be possible but as of now there is no effort to create it. 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
