### ISSUE TITLE
error in running sequence to sequence model demo using bazel

### ISSUE THREAD

**Issue by vnkmr7620** [tensorflow/tensorflow#482]
![1](https://cloud.githubusercontent.com/assets/10511526/11749467/edc39e5c-a053-11e5-90f7-739ef703e47c.png)
![2](https://cloud.githubusercontent.com/assets/10511526/11749468/edc7d7ba-a053-11e5-8d04-0532412c76d2.png)

  I am using bazel for compiling and run in tensor flow. when i try to run the sequence to sequence example i got the following error. If anyone knows help us. I also tried to execute
 using python translate.py --data_dir <path for data>. it is also showing an error. The image 1 shows the error when i try with bazel and image 2 shows the error when i try with python translate.py method.

for bazel

bazel run -c opt <...>/models/rnn/translate/translate.py
  --data_dir [your_data_directory]

showing error

ERROR: Cannot run target //tensorflow/models/rnn/translate:translate.py: Not executable.
INFO: Elapsed time: 0.089s
ERROR: Build failed. Not running target.

python translate.py showing error

Traceback (most recent call last):
  File "translate.py", line 46, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named translate

**Comment by vrv** [comment]
If using bazel:

bazel run -c opt //tensorflow/models/rnn/translate:translate -- --data_dir [...]

You need a "--" before "--data_dir"

If running from python, what version of tensorflow do you have installed?  You need 0.6.0 for running translate.py directly to work.

**Comment by vnkmr7620** [comment]
thanks. it works, i checked bazel with tensorflow 0.5.0 and python with tensorflow 0.6.0

But anpther problem is in both I am getting the following error after some time. please have a look in the attached image
![13](https://cloud.githubusercontent.com/assets/10511526/11760997/b20cd746-a0d7-11e5-960e-58e681af16b4.png)

**Comment by martinwicke** [comment]
That's a network error when downloading what looks like dependencies. It's
most likely due to a bad internet connection.

**Comment by vnkmr7620** [comment]
i solved this error. But after downloading it started showing tokenizing and after some time again got error. please have a look on the attached image. (you can find downloaded files as well as the error
![wmtbazelerror](https://cloud.githubusercontent.com/assets/10511526/11765697/768b05e2-a188-11e5-958b-31b4edf30860.png)
)

**Comment by vnkmr7620** [comment]
I am running programs on 2GB RAM machine. os type 64 bit, disk space 160 GB processor intel core 2 dueo. Is that becoz of memory prob

**Comment by vnkmr7620** [comment]
hi all,
           i tried with  bazel run -c opt tensorflow/models/rnn/translate:translate --local_resources 2042,.5,1.0 -- --data_dir /home/cencluster/wmtbazel/
 But it is also issuing the error. Please have a look for the error.
![local res language modeling](https://cloud.githubusercontent.com/assets/10511526/11766651/e103d1ae-a1b7-11e5-910c-b89a76e0687d.png)

**Comment by martinwicke** [comment]
Bazel is already done by the time you get the error. You can try running without bazel altogether (after building):

```
bazel-bin/tensorflow/models/rnn/translate/translate --data_dir /home/cencluster/wmtbazel/
```

But probably, the model is probably too big to run in 2G RAM.

**Comment by vnkmr7620** [comment]
not solved. But this time getting different error.Please have a look on the attached image
![error in language](https://cloud.githubusercontent.com/assets/10511526/11775069/afedea00-a261-11e5-8dd8-36f4ced1dcee.png)

**Comment by martinwicke** [comment]
Unfortunately, I cannot see the actual error in that screenshot. It's quite likely that bazel wasn't using all that much memory, and that you're still out of memory. You should paste the actual program output here, the screenshot doesn't contain much information.

**Comment by vnkmr7620** [comment]
python translate.py --decode --data_dir /home/cencluster/wmt15/ --train_dir /home/cencluster/wmt15/train

> who is the president of the United States?

Getting the following output. But is is not correct what you have mentioned.
![output of language modelling](https://cloud.githubusercontent.com/assets/10511526/11800855/6db52b1c-a306-11e5-9fac-f794270edac9.png)

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/600, which has more information.
