### ISSUE TITLE
TF2 equivalent of tf.contrib.graph_editor 

### ISSUE THREAD

**Issue by StarWang** [tensorflow/tensorflow#48204]
Hi Team,

In TF1 we have tf.contrib.graph_editor to conveniently edit a trained model. I couldn't find the equivalent in TF2. Editing a trained model is obviously a better design since in many cases separating models into different components (e.g., embedding generation) is a post-training request. It does not make sense to use tf.function to generate different signatures and train the model again.

For TF model devs that provide training libraries for users, this is especially painful since different users have different request for model separation. Separating models on users' custom needs in post training stage is a more scalable solution than the current tf.function solution.

Can you add an equivalent graph editor in TF2?

**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The feature should allow users to separate the model graph and change the input and output of each subgraphs.

**Will this change the current api? How?**
Add a new api support for graph editting

**Who will benefit with this feature?**
All TF users bothered with changing model signature with a trained model

**Any Other info.**

**Comment by StarWang** [comment]
Hi @rmlarsen , can you help answer the question?

**Comment by StarWang** [comment]
@Saduf2019 @ymodak Can you help look at this request? Thanks

**Comment by ice-tong** [comment]
Hello, is there any update about this issue.

**Comment by mohantym** [comment]
Hi @StarWang !
We are checking to see whether you still need help in this issue . 
tf.contrib has been depreciated in 2.x versions . [Ref ](https://www.tensorflow.org/guide/migrate?_gl=1*scqnfy*_ga*MTY2ODE2Mjk4MC4xNjY0ODgxMDA0*_ga_W0YLR4190T*MTY3MzYzNDUzMC4zMzMuMS4xNjczNjM1MDIwLjAuMC4w)

Have you checked this [document](https://www.tensorflow.org/guide/intro_to_graphs) which suggests to use tf.function decorator to use the operations for graph mode in 2.x version.

Thank you!
