### ISSUE TITLE
Thread created by SummaryWriter not killed

### ISSUE THREAD

**Issue by wyx-cornell** [tensorflow/tensorflow#4820]
Hi,

I noticed that the _EventLoggerThread created by summary writer does not get killed by the close method, which will make the number of threads keep increasing until it exceeds the system capacity. Is there any particular reason to not kill these threads?

Best

**Comment by tatatodd** [comment]
@wyx-cornell Thanks for filing this issue!

Looking at the code, I believe you're right, and this is a bug.  Have you run into a real-world problem because of this, or did you just notice via code inspection as well?

Would you like to file a pull request to fix this?  Contributions are welcome!

**Comment by devanshdalal** [comment]
Hi, I am working on this, since haosdent is not working on it anymore.

**Comment by suiyuan2009** [comment]
I'll try to reproduce this, and I'll work on this if I can reproduce this.

**Comment by suiyuan2009** [comment]
@wyx-cornell , according to the latest code and I have tested, number of threads will increase only when you create a new writer every time you want to add_summary. Also, if you kill the thread when close the writer, there will be no thread serving you when you reopen this writer.

how about kill the thread when close the writer and create a new thread when reopen the writer?

**Comment by GrandathePanda** [comment]
I was directed to this particular issue from #2788. I had been using tf.trainLoggingTensorHook which I am assuming uses the lower level summary writers under the hood. I am on tensorflow version 1.2 and upon seeing this I removed the logging and I went from intermittent hanging on start of run to now consistent successful training runs upon every start. I was seeing similar gdb traces on all my threads to the above linked issue and it seems all my threads were in lock. If this isn't the same issue I'm more than willing to open a new one, but it at least seemed related.

**Comment by suiyuan2009** [comment]
@GrandathePanda , can you provide a minimal test case so we can reproduce?

**Comment by whjiang** [comment]
@suiyuan2009 
Below is a test that can reproduce:
We want to make a call from C++ to python and TF. Thus, an embedded python interpreter is used. 
However, the Py_EndInterpreter call fails with error message: 

> Fatal Python error: Py_EndInterpreter: not the last thread 

This is because there is a daemon thread _EventLoggerThread is still running after the python script finishes. 

The output of this test is:
`[33, 67.0]
[<_MainThread(MainThread, started 140735723737984)>, <_EventLoggerThread(Thread-1, started daemon 123145450090496)>]
Fatal Python error: Py_EndInterpreter: not the last thread
`

test.py file:
`# import logging as logger
import sys
import time
import tensorflow as tf
from tensorflow.python.platform import tf_logging as logging
from tensorflow.python.client import timeline
import threading

class Train(object):

    def run(self):
        v = tf.Variable(dtype=tf.float32, initial_value=tf.constant(1.0))
        a = tf.placeholder(tf.float32, shape=None, name="a")
        b = tf.reduce_mean(a, name="b")
        c = tf.add(b, v, name="c")
        add = tf.assign(v, c, name="assign")
        global_step = tf.contrib.framework.get_or_create_global_step()
        sum = tf.summary.scalar(name="sum", tensor=c)
        global_step_inc = tf.assign_add(global_step, 1)
        hooks = [tf.train.StopAtStepHook(last_step=20)]
        ckpt_dir = './tmp/s1/'
        logging.info('begin run')
        with tf.train.MonitoredTrainingSession(checkpoint_dir=ckpt_dir, hooks=hooks) as mon_sess:
            while not mon_sess.should_stop():
                print (mon_sess.run([global_step_inc, add], feed_dict={a: [1.0, 2.0, 3.0]}))
        logging.info('[finish run]')


if __name__ == "__main__":
    print(sys.version)
    Train().run()
    print threading.enumerate()
`

And the test cpp code:
`
#include "Python.h"
#include<iostream>

int main(int argc, char* argv[]) {
    // initialize Python
    Py_Initialize() ;
    PyEval_InitThreads() ; // nb: creates and locks the GIL
    PyThreadState* state = PyThreadState_Get();
    PyEval_ReleaseThread(state);

    PyEval_AcquireThread(state);

    const char* pythonFileName = argv[1];
    FILE* to_run_script= fopen(pythonFileName, "r");
    std::cout << "Run file " << pythonFileName << std::endl;
    PyObject * main_module = PyImport_ImportModule("__main__");
    PyObject* global_symbol_table = PyModule_GetDict(main_module);;
    if (to_run_script != NULL) {
        PyRun_File(to_run_script, pythonFileName, Py_file_input, global_symbol_table, global_symbol_table);

        // if python side has daemon thread. Py_EndInterpreter will throw 'not the last thread' exception.
        Py_EndInterpreter(state);

        if (!PyErr_Occurred()) {
            return 0;
        }else {
            PyErr_PrintEx(1);
        }
    }
    PyEval_ReleaseThread(state);
    Py_Finalize() ;
}
`

**Comment by albertz** [comment]
I think this is still up-to-date.
See [here](https://github.com/rwth-i6/returnn/blob/a923504d7265214efb74ef67509db9ac72b84d1c/tests/test_TFUtil.py#L678) and [here](https://github.com/rwth-i6/returnn/blob/3f1e9a235e28f41e695686a345410f32e929a663/TFUtil.py#L4466). This test case still runs with latest TF, e.g. [here](https://travis-ci.org/rwth-i6/returnn/jobs/501581634).

**Comment by suiyuan2009** [comment]
@whjiang it's a long time, I'll take a look in this week.
