### ISSUE TITLE
There is no Digital Object Identifiers (DOI) to make the code citable for academic references

### ISSUE THREAD

**Issue by georgeslabreche** [tensorflow/tensorflow#48200]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/README.md

## Description of issue (what needs changing):

The source code should be made citable for academic references: https://guides.github.com/activities/citable-code/

### Clear description

_"A DOI, or Digital Object Identifier, is a string of numbers, letters and symbols used to permanently identify an article or document and link to it on the web. A DOI will help your reader easily locate a document from your citation."_  - [source](https://library.uic.edu/help/article/1966/what-is-a-doi-and-how-do-i-use-them-in-citations).

### Usage example

See GitHub instructions on "making your code citable":  https://guides.github.com/activities/citable-code/

**Comment by mihaimaruseac** [comment]
https://www.tensorflow.org/about/bib could help

**Comment by georgeslabreche** [comment]
@mihaimaruseac it's good but it doesn't allow us to cite specific versions of the framework so that the published paper ages well in terms of reproducibility.

**Comment by ewilderj** [comment]
Looking for an owner from the product team for this.

**Comment by bhack** [comment]
We can use another specific entry for the library: https://ctan.org/tex-archive/macros/latex/contrib/biblatex-contrib/biblatex-software

**Comment by georgeslabreche** [comment]
@bhack that wouldn't produce a DOI, though.

**Comment by bhack** [comment]
If you want an automated DOI we could explore https://guides.github.com/activities/citable-code/

/cc @MarkDaoust @lamberta

**Comment by georgeslabreche** [comment]
@bhack, yes. That's what's in the description of this issue.

**Comment by lamberta** [comment]
FWIW, the Google quantum projects have started doing this with Zenodo: https://quantumai.google/cirq/citation
But, yes, currently we point to the [TensorFlow white paper](https://www.tensorflow.org/about/bib) for the citation.
cc: @theadactyl @joanafilipa

**Comment by ewilderj** [comment]
cc / @iamtimdavis from product

**Comment by mihaimaruseac** [comment]
@angerson implemented a solution for this and we should have a DOI with the 2.5 release.

**Comment by georgeslabreche** [comment]
@mihaimaruseac that's great to hear! Looking forward to it.

**Comment by angerson** [comment]
TensorFlow now has a DOI page set up with Zenodo: https://doi.org/10.5281/zenodo.4724125

I added a badge on the README and made a change that should appear on tensorflow.org/about/bib in the next few days.

**Comment by georgeslabreche** [comment]
@angerson Great! Thank you to everyone who made it happen. I look forward to referencing the TensorFlow DOI on my next publication.
