### ISSUE TITLE
Exception when saving custom RNN model with a constant in the call function when using SavedModel format

### ISSUE THREAD

**Issue by ingolfured** [tensorflow/tensorflow#48213]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Redhat 7.8.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1 and 2.3.1 (tested)
- Python version: 3.6.8
- Bazel version (if compiling from source):  No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

**Current Behavior**
When saving (SavedModel format) an RNN model with a constant in the call function (like shown below), we get an exception.

**Desired behaviour** 
We should be able to save `model` defined below, in a SavedModel format, just like we can save it in an h5 format.

**Code to reproduce the issue:**
```
import tensorflow as tf
import tensorflow.keras as tfk
import tensorflow.keras.backend as K
import numpy as np

class MinimalRNNCell(tfk.layers.Layer):

    def __init__(self, units, **kwargs):
        self.units = units
        self.state_size = units
        super(MinimalRNNCell, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(shape=(input_shape[-1], self.units),
                                      initializer='uniform',
                                      name='kernel')
        self.recurrent_kernel = self.add_weight(
            shape=(self.units, self.units),
            initializer='uniform',
            name='recurrent_kernel')
        self.built = True

    def call(self, inputs, states=None, constants=None, training=False, *args, **kwargs):
        prev_output = states[0]
        print("constants: ", constants)
        h = K.dot(inputs, self.kernel) + constants[0]
        output = h + K.dot(prev_output, self.recurrent_kernel)
        return output, [output]

    def get_config(self):
        return dict(super().get_config(), **{'units': self.units})

cell = MinimalRNNCell(32)
x = tfk.Input((None, 5), name='x')
z = tfk.Input((1), name='z')
layer = tfk.layers.RNN(cell, name='rnn')
y = layer(x, constants=[z])

model = tfk.Model(inputs=[x, z], outputs=[y])
model.compile(optimizer='adam', loss='mse')
model.save('tmp.h5') # This works ok
model_loaded = tfk.models.load_model('tmp.h5', custom_objects={'MinimalRNNCell': MinimalRNNCell})
print(model_loaded.predict([np.array([[[0,0,0,0,0]]]), np.array([[0]])])) # This works ok
model.save('tmp2') # This throws an exception
```

**Other info**
The stdout from the above is
```
constants:  (<tf.Tensor 'Placeholder_1:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'Placeholder_1:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'Placeholder_1:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'Placeholder_1:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'model_1/Cast_1:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'model_1/Cast_1:0' shape=(None, 1) dtype=float32>,)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]]
constants:  (<tf.Tensor 'z:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'z:0' shape=(None, 1) dtype=float32>,)
constants:  (<tf.Tensor 'constants:0' shape=(None, None, 5) dtype=float32>,)
```

I'll attach the full exception [here](https://github.com/tensorflow/tensorflow/files/6235635/tensorflow_rnn_exception.txt). Anyone should be able to reproduce. However, the main error is
```
ValueError: Dimensions must be equal, but are 32 and 5 for '{{node add}} = AddV2[T=DT_FLOAT](MatMul, constants)' with input shapes: [?,32], [?,?,5].
```
For some reason, the name of `z` changes to `constants` and the shape changes from the expected `(None, 1)` to `(None, None, 5)`. 

Any ideas appreciated. 

Thanks in advance.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/70335ea8349dae6d8a98840b0cb3f78a/48213-2-3.ipynb) and [TF v2.4](https://colab.research.google.com/gist/amahendrakar/6ded3f5bd216f6b6bce44aa0a3367f82/48213.ipynb).

Whereas with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/afa52880fc8f09635e60c6b5141eecbe/48213-tf-nightly.ipynb#scrollTo=K_zbK2SwaPyv), I am facing an error stating `TypeError: call() got multiple values for argument 'training'`. Please check the linked gist for reference. Thanks!

**Comment by ingolfured** [comment]
Any news on this one? Anything else I can help with?

**Comment by itamarst** [comment]
On 2.4, changing to saving in the new model format (e.g. `model.save('tmp.model')`) instead of HDF5 results in the error occurring at save time.

**Comment by ingolfured** [comment]
On TF 2.5 we get a different issue. 
```
TypeError: call() got multiple values for argument 'training'
```
This is probably where we should focus our efforts.

**Comment by ingolfured** [comment]
When I simply remove the `training=False` inside `call` we get the same issue as before (version 2.4 and lower) so no progress made.

**Comment by itamarst** [comment]
@k-w-w might you have any ideas? Or know who might? It seems like this is something in the serialization layer. Thank you!

**Comment by itamarst** [comment]
Updated example, with newer APIs and focusing on saving as the issue:

```python
import tensorflow as tf
from tensorflow.linalg import matmul
import tensorflow.keras as tfk
import tensorflow.keras.backend as K
import numpy as np

class MinimalRNNCell(tfk.layers.Layer):

    def __init__(self, units, **kwargs):
        self.units = units
        self.state_size = units
        super(MinimalRNNCell, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(shape=(input_shape[-1], self.units),
                                      initializer='uniform',
                                      name='kernel')
        self.recurrent_kernel = self.add_weight(
            shape=(self.units, self.units),
            initializer='uniform',
            name='recurrent_kernel')
        self.built = True

    def call(self, inputs, states=None, constants=None, *args, **kwargs):
        prev_output = states[0]
        print("constants: ", constants[0].name)
        h = matmul(inputs, self.kernel) + constants[0]
        output = h + matmul(prev_output, self.recurrent_kernel)
        return output, [output]

    def get_config(self):
        return dict(super().get_config(), **{'units': self.units})

cell = MinimalRNNCell(32)
x = tfk.Input((None, 5), name='x')
z = tfk.Input((1,), name='z')
layer = tfk.layers.RNN(cell, name='rnn')
y = layer(x, constants=[z])

model = tfk.Model(inputs=[x, z], outputs=[y])
model.compile(optimizer='adam', loss='mse')
model.predict([np.array([[[0,0,0,0,0]]]), np.array([[0]])])
model.save('tmp.model')
```

**Comment by k-w-w** [comment]
Thanks for reporting this! Looks like there is a bug with the RNN shape inference when using custom cells. For now, please the following workaround: (The model should use a subclass of RNN)

```python
class MinimalRNNCell(tfk.layers.Layer):
  ... # same as above

#  Create an RNN subclass to bypass the shape inference logic
class RNN(tfk.layers.RNN):
  pass

cell = MinimalRNNCell(32)
x = tfk.Input((None, 5), name='x')
z = tfk.Input((1,), name='z')
layer = RNN(cell, name='rnn')  #  This now uses RNN instead of tfk.layers.RNN
y = layer(x, constants=[z])

model = tfk.Model(inputs=[x, z], outputs=[y])
model.compile(optimizer='adam', loss='mse')
model.predict([np.array([[[0,0,0,0,0]]]), np.array([[0]])])
model.save('tmp_model')

# To load the model, the custom cell must be passed into `custom_objects`
loaded = tfk.models.load_model('tmp_model',custom_objects={'MinimalRNNCell': MinimalRNNCell})
```

**Comment by mohantym** [comment]
Hi @ingolfured ! Inline with @k-w-w comment.  I tried to resolve  the issue by adding

>  .h5 extension

 for model file in last line. Attaching [GIST](https://colab.research.google.com/gist/mohantym/6c0653d7b7b41db348ad76ddcc8c0926/github_48213.ipynb#scrollTo=uoja--mNHoA6) in TF 2.6  for reference

**Comment by itamarst** [comment]
Still waiting for resolution, it's not stale.

**Comment by itamarst** [comment]
@mohantym you will notice that the original filed issue (at the top) was actually saving as `.h5`. So changing extension to `.h5` is not sufficient.

Specifically, with Tensorflow 2.6:

```
... lots and lots and lots of callstack ...
  File "/home/itamarst/Devel/sandbox/venv/lib64/python3.9/site-packages/tensorflow/python/framework/smart_cond.py", line 58, in smart_cond
    return false_fn()
  File "/home/itamarst/Devel/sandbox/venv/lib64/python3.9/site-packages/keras/saving/saved_model/utils.py", line 166, in <lambda>
    lambda: replace_training_and_call(False))
  File "/home/itamarst/Devel/sandbox/venv/lib64/python3.9/site-packages/keras/saving/saved_model/utils.py", line 162, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/home/itamarst/Devel/sandbox/venv/lib64/python3.9/site-packages/keras/saving/saved_model/save_impl.py", line 633, in call_and_return_conditional_losses
    call_output = layer_call(*args, **kwargs)
TypeError: call() got multiple values for argument 'training'
```

So first, that doesn't always fix the bug.

Second, even if it is "resolved in some cases" that does not mean resolved in all cases, so this bug should stay open, otherwise other people will have random breakage and have to go through their own whole debugging, ticket filing, etc..

**Comment by mohantym** [comment]
Hi @ingolfured !  It is still valid in [2.8](https://colab.sandbox.google.com/gist/mohantym/6361c4182be018b9ba02b9b8fc1bb799/github_48213.ipynb#scrollTo=IWCFNeDscLIz) version . Could you please post this on [Keras](https://github.com/keras-team/keras) repo and close this one here?

**Comment by itamarst** [comment]
As far as I know this bug is still real.

**Comment by mohantym** [comment]
Yeah. It is replicating when saved without h5 extension.

**Comment by SuryanarayanaY** [comment]
The issue is replicating is TF2.10 and nightly versions.Please find the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/c408439e8cc7933a97a21de1bd3d8b60/48213.ipynb) here.
Thankyou!
