### ISSUE TITLE
Multiple retracing when shapes changes 

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#48229]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: na
- TensorFlow installed from (source or binary): binay pypy
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

```
import tensorflow as tf
@tf.function()  # Setting experimental relax shapes does not change the result
def unique_numpy(arr):
    unique_val, unique_inverse = tf.unique(arr)
    return unique_val
# We trace two functions.
unique_numpy.get_concrete_function(tf.TensorSpec(shape=(None,), dtype=tf.int32))
unique_numpy.get_concrete_function(tf.TensorSpec(shape=(None,), dtype=tf.int64))
print(unique_numpy.pretty_printed_concrete_signatures()) # 2 signatures available 
unique_numpy(tf.constant([0, 2], dtype=tf.int32)) 
print(' New')
print(unique_numpy.pretty_printed_concrete_signatures()) # 3 signatures while it should have re used the tf.TensorSpec(shape=(None,), dtype=tf.int32) trace
```

**Describe the expected behavior**
Since `tf.constant([0, 2], dtype=tf.int32)`respects the signature `tf.TensorSpec(shape=(None,), dtype=tf.int32)`I would have thought that TF would reuse that trace and not trace again the function.

I would like to do that to create a function with the same name that could support the same shape but multiple dtypes.
 
**Standalone code to reproduce the issue**
Done above

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c8bf4652ba79f99a8e8d34497e815ce7/untitled581.ipynb)

**Comment by mdanatg** [comment]
This is a bug, indeed. Here's a temporary workaround in case you're blocked by it:

```
cf = unique_numpy.get_concrete_function(tf.TensorSpec(shape=(None,), dtype=tf.int64))
cf(tf.constant([0, 2], dtype=tf.int32))  # guaranteed not to retrace
```

**Comment by sachinprasadhs** [comment]
Now it is using 2 signatures instead of 3 at the end, here is the [gist](https://colab.research.google.com/gist/sachinprasadhs/871fcd3cdf05c903952cffcc9e493fe7/untitled581.ipynb) for reference. Thanks!

**Comment by mdanatg** [comment]
This should now be fixed at head, and should land in the next version.
