### ISSUE TITLE
How can I find the type of quantization?

### ISSUE THREAD

**Issue by qkqk772** [tensorflow/tensorflow#48224]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

How can I find out the quantization type (e.g. float16 or int8) of the tflite file after loading the .tflite file in a Python environment and creating an Interpreter through tf.lite.Interpreter?

**Comment by abattery** [comment]
@xhae could you triage this issue?

**Comment by ymodak** [comment]
You may use [netron app](https://github.com/lutzroeder/netron) to load your tflite file and inspect the node properties.

**Comment by qkqk772** [comment]
> You may use [netron app](https://github.com/lutzroeder/netron) to load your tflite file and inspect the node properties.

Thank you, but I have to find out through code execution in Python..

**Comment by xhae** [comment]
AFAIK there's no such metadata that you can read and get the quantization type directly, instead you can navigate the weights and observe the data types. Does this make sense to you?

**Comment by qkqk772** [comment]
> AFAIK there's no such metadata that you can read and get the quantization type directly, instead you can navigate the weights and observe the data types. Does this make sense to you?

Yes, I was wondering if there was any other way than the way you told me. Thank you!

**Comment by xhae** [comment]
👍  sorry for the inconvenience.
