### ISSUE TITLE
Tensorflow-lite: unresolved dependencies during linking

### ISSUE THREAD

**Issue by WannesBouwen** [tensorflow/tensorflow#48227]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): arm 64 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 85c8b2a817f95a3e979ecd1ed95bff1dc1335cff
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Unresolved dependencies during linking.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I'm creating a very easy model via following python code:

```
import tensorflow as tf
import numpy as np
from tensorflow import keras

model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])
model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([ -1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([ -3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model.fit(xs, ys, epochs=500)

print(model.predict([10.0]))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open('linear.tflite', 'wb').write(tflite_model)
```

Afterwards I'm trying to create a simple C++ program to load and evaluate the model. But with following code which just creates the model. I'm already getting linker errors:

```
#include <tensorflow/lite/interpreter.h>
#include <tensorflow/lite/kernels/register.h>
#include <tensorflow/lite/model.h>
#include <tensorflow/lite/tools/gen_op_registration.h>

std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("linear.tflite");

if(!model){
    printf("Failed to mmap model\n");
    exit(0);
}
```

I observe following linker problems:

libtensorflow-lite.so: undefined reference to 'TfLiteXNNPackDelegateOptionsDefault'
libtensorflow-lite.so: undefined reference to 'TfLiteXNNPackDelegateDelete'
libtensorflow-lite.so: undefined reference to 'tflite::tools::ToolParams::Merge(tflite::tools::ToolParams const&, bool)'
libtensorflow-lite.so: undefined reference to 'TfLiteXNNPackDelegateCreate'
libtensorflow-lite.so: undefined reference to 'tflite::Flags::Parse(int*, char const**, std::vector<tflite::Flag, std::allocator<tflite::Flag> > const&)'

Note that I'm building with TFLITE_ENABLE_XNNPACK=OFF. I'm using CMake for the compilation.

Could anybody suggest on what's going wrong?

Kind regards,

Wannes

**Comment by abattery** [comment]
@multiverse-tf could you take a look?

**Comment by multiverse-tf** [comment]
@WannesBouwen could you share the CMakeLists.txt you created for your simple C++ program?

Also, does this issue happen w/ the HEAD? We have had multiple CMake-related changes since the commit [85c8b2a](https://github.com/tensorflow/tensorflow/commit/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff).

**Comment by WannesBouwen** [comment]
Hello,

Sorry for the late response. I've updated to the latest available changeset and the problem is not seen anymore. Thank you for the help.

Kind regards,

Wannes
