### ISSUE TITLE
Model to estimator docs use deprecated code

### ISSUE THREAD

**Issue by Nate711** [tensorflow/tensorflow#48220]
The example code for converting a keras model to a tf estimator cause a user warning that set_learning_phase is deprecated and will be removed after 2020-10-11, which has since past. 

## URL(s) with the issue:
https://www.tensorflow.org/guide/migrate#using_a_keras_model_definition

## Description of issue (what needs changing):
User warning in the console log:

```
/tmpfs/src/tf_docs_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:434: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
```

**Comment by amahendrakar** [comment]
@rmothukuru,
I was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/55b13a19457068e5b0163f7613f4d12d/48220.ipynb). Thanks!

**Comment by ymodak** [comment]
Tested the tutorial with TF 2.5 version, the observed warning is no longer triggered. Thanks!
