### ISSUE TITLE
tf.linalg.eigh and tf.linalg.eigvalsh errors

### ISSUE THREAD

**Issue by Mastiff37** [tensorflow/tensorflow#48221]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS 6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  Source
- TensorFlow version (use command below):  2.0.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I apologize in advance, I'm working on a machine that is isolated from the internet so have to type everything in by hand.  My issue is that I'm attempting to use tf.linalg.eigh within a loss function and get errors on a fraction of the test data I'm using.  For most data it works, but about 1% fails.  The matrices it fails on work fine with numpy.linalg.eig and they are symmetric matrices.

The error looks like this:

```
InvalidArgumentError: Got info = 5251 for batch index 49, expected info = 0.  Debug_info = heevd
  [[node SelfAdjointEigV2 (defined at .../lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_dirtributed_function_1774378]

Function call stack:
distributed_function
```

**Comment by ymodak** [comment]
Please provide a concise reproducible code example to investigate the issue. Thanks!

**Comment by amahendrakar** [comment]
Also, please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by Mastiff37** [comment]
I'm working on getting updated.  I'll report back after I do.  Thanks.
