### ISSUE TITLE
tf.meshgrid throws exception when input tensors have different dtypes

### ISSUE THREAD

**Issue by DCtheTall** [tensorflow/tensorflow#48238]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Reproducible on several OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: See above
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Reproducible with or without GPU

**Describe the current behavior**

Currently, the way TensorFlow tests its own `meshgrid` implementation is by comparing the output to the result of NumPy's implementation ([code](https://github.com/tensorflow/tensorflow/blob/32f8688c1c108ab2df794fe4ceb9e058641359b0/tensorflow/python/kernel_tests/array_ops_test.py#L552)).

In NumPy's implementation, when you call the function with arrays of different types, the types of the input arrays are mapped to the output arrays:

```python
np.meshgrid([1, 2, 3], [4.0, 5.0, 6.0])
[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])]
```

NumPy's code even works with tensors:

```python
a = tf.constant([1,2,3])
b = tf.constant([4,5,6], dtype='float32')
np.meshgrid(a, b)
[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32), array([[4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]], dtype=float32)]
```

However, the TensorFlow Python implementation throws an exception:

```python
tf.meshgrid(tf.constant([0, 1]), tf.constant([2., 3.]))
InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Mul]
```

It seems like this is being thrown by an internal matrix multiplication operation.

**Describe the expected behavior**

TensorFlow's Python function to match how NumPy handles inputs with different data types.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
tf.meshgrid(tf.constant([0, 1]), tf.constant([2., 3.]))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This was discovered during [code review](https://github.com/tensorflow/tfjs/pull/4855#pullrequestreview-624437214) for implementing `tf.meshgrid` for TensorFlow.js

I'd also be willing to submit a PR with a patch and an additional unit test to cover this case.

**Comment by amahendrakar** [comment]
@ymodak,
I was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3643d3263bf159df41177abd2ac1aff3/48238.ipynb). Thanks!

**Comment by kkimdev** [comment]
Thanks for reporting this! Tensorflow has different type promotion rules, and we have an experimental flag to control it.

```
import tensorflow.experimental.numpy as tnp
import tensorflow.compat.v2 as tf
tf.compat.v2.enable_v2_behavior()

tnp.experimental_enable_numpy_behavior(prefer_float32=True)
tnp.meshgrid(tf.constant([0, 1]), tf.constant([2., 3.]))
```

**Comment by DCtheTall** [comment]
@kkimdev thanks for the pointer. Is there is a compelling reason to keep the default behavior of throwing an exception?

**Comment by kkimdev** [comment]
Each type promotion rule has a trade-off.  historically, TensorFlow has been conservative and arguably it can reduce unexpected type promotion bugs.  Though this decision is not necessarily final and can be revisited (and there have been some discussions).

**Comment by DCtheTall** [comment]
> Each type promotion rule has a trade-off. historically, TensorFlow has been conservative and arguably it can reduce unexpected type promotion bugs.

@kkimdev that's definitely understandable, in an extreme example users might even call `tf.meshgrid` to verify that tensors have the same type (but that sounds like an anti-pattern to me...)
