### ISSUE TITLE
Tensorflow not using GPU (according to TensorBoard)

### ISSUE THREAD

**Issue by seeb0h** [tensorflow/tensorflow#4823]
GTX 1070, ubuntu 16.04.

I am retraining [inception](https://github.com/tensorflow/models/tree/master/inception) model on my own data. Everything is fine until the final command :

    bazel-bin/inception/flowers_train \
      --config=cuda \
      --train_dir="${TRAIN_DIR}" \
      --data_dir="${OUTPUT_DIRECTORY}" \
      --pretrained_model_checkpoint_path="${MODEL_PATH}" \
      --fine_tune=True \
      --initial_learning_rate=0.001 \
      --input_queue_memory_factor=1

According to the logs, **Tensorflow seems to be using the GPU** :

    I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties:
    name: GeForce GTX 1070
    major: 6 minor: 1 memoryClockRate (GHz) 1.7715
    pciBusID 0000:03:00.0
    Total memory: 7.92GiB
    Free memory: 7.77GiB
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y
    I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0)

But when I am checking the learning in TensorBoard, **the net is using mainly the CPU** (blue /device:CPU:0, green /device:GPU:0):

TensorBoard graph:

![graph](https://cloud.githubusercontent.com/assets/4989990/19196523/33a2e6c2-8cb6-11e6-85b1-1f35950657e3.png)

I have tried this two TensorFlow setups :

 1. Install from the source (3b75eb34ea2c4982fb80843be089f02d430faade) with nvidia-367 drivers, CUDA8 8.0, cuDNN
    v5,    source from the master (16/10/06 - r11?). compiled for GPU
    use:

        bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
        bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu    
        bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

 1. docker GPU image of Tensorflow on a PC with a GTX
    1070 8Go

        nvidia-docker run -it -p 8888:8888 -p 6006:6006 gcr.io/tensorflow/tensorflow:latest-gpu /bin/bash

According to the doc Cuda >=7.0 can be used when installed from sources. 

> The GPU version works best with Cuda Toolkit 7.5 and cuDNN v5. Other versions are supported (Cuda toolkit >= 7.0 and cuDNN >= v3) only when installing from sources

And the dockerfile begins with `FROM nvidia/cuda:7.5-cudnn5-devel`. So it is not using cuda and cudnn of the host system

**Comment by tatatodd** [comment]
@seeb0h is there a specific problem that you're running into as a result?  Or are you just wondering why the picture seems to show more blue (cpu) than green (gpu)?

I'm not an expert on tensorboard visualization, or the inception model.  But isn't the inception 'tower' where the bulk of the work is being performed?  So even though it's only a small portion of the total picture, it might account for the majority of the actual work.

@dsmilkov probably knows more about this.

**Comment by seeb0h** [comment]
Yes, exactly. I was wondering why the picture seems to show more blue (cpu) than green (gpu).

I haven't study that much the inception model and didn't know 'tower' was the main deal. So everything could be perfectly fine. 
If it is, sorry for your wasted time...

**Comment by seeb0h** [comment]
Ok. Still something weird. 
Running `watch nvidia-smi` gives :
```
Mon Oct 10 10:31:04 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.48                 Driver Version: 367.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:03:00.0      On |                  N/A |
| 29%   57C    P2    41W / 230W |   7806MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1082    G   /usr/lib/xorg/Xorg                              69MiB |
|    0      3082    C   /usr/bin/python                               7729MiB |
+-----------------------------------------------------------------------------+

```

While top gives : 
```
  PID UTIL.     PR  NI    VIRT    RES    SHR S  %CPU %MEM    TEMPS+ COM.
 3082 root      20   0 26,739g 3,469g 1,657g S 101,3 59,7   7254:50 python
```

GPU seems ignored...

**Comment by dsmilkov** [comment]
@seeb0h tower_0 is the namespace that holds the GPU ops. If you expand it, you will probably see that tower_0 contains conv_0,1,2... nodes as well which correspond to the actual convolution operations, whereas the external conv_0,1,2... nodes correspond to variables holding the weights of that convolution and variables are always allocated to the CPU.

I will close this bug for now, but feel free to reopen if you have any other concerns.

Thanks!

**Comment by seeb0h** [comment]
Ok. And I was running tensorflow from a docker image. It seems `watch nvidia-smi` is not reliable in this case.

So everything works flawlessly

**Comment by blvck-mvgic** [comment]
I tried running training with GAN128 and after installing `keras_vggface` from repo (which explicitly says it will check for either `tensorflow-gpu` or `tensorflow`) I got some error at some point, this is the last call:
```
File "C:\env\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2, in <module>
    from tensorflow.python.training import moving_averages
ModuleNotFoundError: No module named 'tensorflow.python.training'
```
Then I tried installing `tensorflow` and training only happens on CPU, which is quite not ideal.
