### ISSUE TITLE
Ubuntu Debbian to MacOS Terminal Prompt and TF

### ISSUE THREAD

**Issue by o0stsou0o** [tensorflow/tensorflow#48242]
Hi,

I have traditionally used TF 2.3.1 on an linux ubuntu debbian where I ran this project through a jupyter notebook.  No GPU was needed to run anything.  

I am now working locally on my Mac OS Terminal where I believe I can only conda install TF 2.0.  When I try pip installing an upgrade, I can no longer even import tensorflow.  I get this error importing tensorflow:

File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib"

Anyways, when I run the identical code with just tensorflow 2.0 in jupyter I am getting an error in my pipeline: 

26     return (0.5 / float(tf.shape(x_true)[0])) * tf.square(tf.linalg.norm(x_true - x_prime))    #original
     27 
     28 

TypeError: float() argument must be a string or a number, not 'Tensor'

Unfortunately, I am not as well versed in the differences between TFs and installing various versions.  I would prefer not to go through the entire pipeline to change TF syntax but am willing to do so if that is the only work around.  Would anybody have an idea what may be wrong?  Thanks.

**Comment by Saduf2019** [comment]
@o0stsou0o 
Can you please refer to this isue with same error and let us know if it helps: #36945, [link](https://github.com/tensorflow/tensorflow/issues/5141), [link](https://stackoverflow.com/questions/35989572/importerror-dlopen-symbol-not-found-pycodecinfo-getincrementaldecoder)

**Comment by o0stsou0o** [comment]
Hi Saduf2019,

I don't think any of the links are helpful though I did post to the first link.  I will add that the version of OSX I am using is 10.11.6 El Capitan.  Thanks.  


> @o0stsou0o
> Can you please refer to this isue with same error and let us know if it helps: #36945, [link](https://github.com/tensorflow/tensorflow/issues/5141), [link](https://stackoverflow.com/questions/35989572/importerror-dlopen-symbol-not-found-pycodecinfo-getincrementaldecoder)

**Comment by jvishnuvardhan** [comment]
@o0stsou0o I am not sure what is the root-cause but the best way to resolve this kind of issue is by removing `conda` and `Tensorflow` completely and re-install TF through `pip`. Unfortunately we don't support conda builds as we don't have any control on those builds. If your error is specific to Anaconda's TF, then post it in Anaconda repo so that some conda experts will resolve your issue faster. Thanks!

**Comment by o0stsou0o** [comment]
Thank you so much.  I am hoping to install tensorflow 2.3.1 or above.  I've tried with pip.  Unfortunately, if you run pip install --upgrade tensorflow or pip install tensorflow, it installs tensorflow 1.8.0.  If you conda install tensorflow, it gives you tensorflow 2.0.0.  In both cases if you try installing tensorflow==2.3.2 it gives an error upon import tensorflow.  Would you know of what may be the problem?  

> @o0stsou0o I am not sure what is the root-cause but the best way to resolve this kind of issue is by removing `conda` and `Tensorflow` completely and re-install TF through `pip`. Unfortunately we don't support conda builds as we don't have any control on those builds. If your error is specific to Anaconda's TF, then post it in Anaconda repo so that some conda experts will resolve your issue faster. Thanks!

**Comment by jvishnuvardhan** [comment]
@o0stsou0o I just tried `pip3 install tensorflow==2.4.1` on Mac OS and it correctly installed `TF2.4.1`.  If you still face it, search `tensorflow` related folders and delete all of them and restart Mac and try the above command. 

It could be that when you tried `pip install tensorflow`, that `pip` might be connected to `python2.x` and tried to install `TF1.x`. We no longer support `python2.x` and `TF1.x`.

Please let me know how it progresses. Thanks!

**Comment by o0stsou0o** [comment]
Thank you so much.  So I looked at the installation.  Indeed, when I do pip show tensorflow both inside and outside the conda environment, it shows version 2.4.1 in the site-packages in python 3.8.  Unfortunately, when I print the version of tensorflow in python3, I'm getting 1.8.0 (below).  Would you know why?  

<img width="1092" alt="Screen Shot 2021-04-07 at 9 26 28 PM" src="https://user-images.githubusercontent.com/23566009/113954833-9a305e00-97e8-11eb-9444-8311b10955ba.png">



> @o0stsou0o I just tried `pip3 install tensorflow==2.4.1` on Mac OS and it correctly installed `TF2.4.1`. If you still face it, search `tensorflow` related folders and delete all of them and restart Mac and try the above command.
> 
> It could be that when you tried `pip install tensorflow`, that `pip` might be connected to `python2.x` and tried to install `TF1.x`. We no longer support `python2.x` and `TF1.x`.
> 
> Please let me know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment]
@o0stsou0o Can you create a virtual Environment and install TF through `pip. Instructions are [here](https://www.tensorflow.org/install/pip). Thanks!

**Comment by o0stsou0o** [comment]
Thank you for your continued correspondence.  So in the virtual environment (not conda), I pip installed --upgrade tensorflow.  I then went into python3 and got the following error importing tensorflow:

<img width="1091" alt="Screen Shot 2021-04-09 at 10 43 05 AM" src="https://user-images.githubusercontent.com/23566009/114197629-8a1b9a00-9920-11eb-8dd2-c47090f04da2.png">

There was a long list of things not uninstalling while pip installing tensorflow though (below):

<img width="848" alt="Screen Shot 2021-04-09 at 10 35 40 AM" src="https://user-images.githubusercontent.com/23566009/114197830-bcc59280-9920-11eb-99ec-00e16cf3c042.png">

Do you have an idea what may be the issue?  


> @o0stsou0o Can you create a virtual Environment and install TF through `pip. Instructions are [here](https://www.tensorflow.org/install/pip). Thanks!
