### ISSUE TITLE
Data cardinality

### ISSUE THREAD

**Issue by KaterinaBao** [tensorflow/tensorflow#48256]
Hi, I am training a neural network use two inputs with different numbers of images, like this:

input1 = Input((500,500,3), name='input1')
input2 = Input((700, 500, 3,), name='input2')

l1 = Dense(64, activation='relu')(input1)
l1 = Dense(1, activation='sigmoid', name='output1')(l1)

l2 = Dense(64, activation='relu')(input2)
l2 = Dense(1, activation='sigmoid', name='output2')(l2)

model = keras.Model(inputs=[input1, input2], outputs=[l1, l2])
keras.utils.plot_model(model, 'multi_input_and_output_model.png', show_shapes=True)
model.compile(optimizer='adam', loss={'output1':keras.losses.MeanSquaredError(),'output2':keras.losses.MeanSquaredError()})
model.summary()

and you can check it by som dummy x1 and x2 but with different first dimension, for example:
x1.shape = (50, 500, 500, 3)
y1.shape = (50,)
x2.shape = (100,700,500,3)
y2.shape = (100,)
model.fit({'input1':x1, 'input2':x2}, {'output1':y1, 'output2':y2}, epochs=10)

I got the ValueError: Data cardinality is ambiguous: x sizes: 50, 100 y sizes: 50, 100 Please provide data which shares the same first dimension.

Can anyone help me to solve the problem?
Any help will be appreciated!

**Comment by AdityaKane2001** [comment]
@KaterinaBao 
You can have the model train on same number of samples. Thus, as per your example, you will be able to train on 50 examples only. The reason being, that on each step, your model requires a batch of data for *all* the inputs, and not only one of them. Thus, it is not possible to train on different sized datasets that go into a single model.
Hope this helps.

**Comment by amahendrakar** [comment]
@KaterinaBao,
Please take a look at @AdityaKane2001's comment and check if it helps. 

Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is a larger community that reads questions there. Thanks!

**Comment by KaterinaBao** [comment]
> @KaterinaBao
> You can have the model train on same number of samples. Thus, as per your example, you will be able to train on 50 examples only. The reason being, that on each step, your model requires a batch of data for _all_ the inputs, and not only one of them. Thus, it is not possible to train on different sized datasets that go into a single model.
> Hope this helps.

Thank, that information really useful

**Comment by KaterinaBao** [comment]
> @KaterinaBao,
> Please take a look at @AdityaKane2001's comment and check if it helps.
> 
> Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is a larger community that reads questions there. Thanks!

Yes, that's helpful. Thanks

**Comment by AdityaKane2001** [comment]
Requesting to close the issue if the query is resolved.
