### ISSUE TITLE
Trying To Resolve Eigen Library For TFLM Visual Studio Build

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tensorflow#48255]
**System information**
- Host OS Platform and Distribution: Windows 10
- TensorFlow installed from Source
- Tensorflow version 2.4.1
- Target platform Visual Studio

**Describe the problem**
I am attempting to build TFLM in Visual Studio, thus am unable to rely on the Bazel, CMake, or Make build tools (which seemed to have issue for TFLM example projects). I have a build that works without some kernels, like LSTM.

I am needing to resolve my Eigen library dependency to be able to load my models properly in C++. This dependency first presents when I add the tensorflow/lite/kernels/add.cc file. This C++ includes the header file tensorflow/lite/kernels/internal/optimized/optimized_ops.h, which in turn includes two header file folders from the Eigen library:

#include "third_party/eigen3/Eigen/Core"
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"

I manually attempted to download the Eigen library from here and add it into my project without any guidance from a build process, which seems to be the only way to troubleshoot with TFLM:

https://gitlab.com/libeigen/eigen

There is an eigen/src/Core folder here (doesn't exactly match "Eigen/Core"):

https://gitlab.com/libeigen/eigen/-/tree/master/Eigen/src/Core

However, there is nothing matching the unsupported/Eigen/CXX11/Tensor pattern at all.

Can someone please help me understand where/how to pull the Eigen library to satisfy the tensorflow/lite/kernels/add.cc dependency as a next step to resolving the rest of my dependency issues? 

I am fairly new to Bazel, CMake, and Make, but have been attempting to use them to build TFLM example projects from the tensorflow/lite/micro/examples folder, for example magic_wand, but there always seems to be issues with the build (for example, problems with checksums like this: https://github.com/tensorflow/tensorflow/issues/47467)

Thanks!

**Comment by mohantym** [comment]
Hi @embeddetech !
You can  pass Eigen , flatbuffer and other dependency through installable package.
[Reference](https://www.tensorflow.org/lite/guide/build_cmake#build_installable_package) .
Thank you!
