### ISSUE TITLE
tf.signal.rFFT in TFLITE is not working in JAVA

### ISSUE THREAD

**Issue by Humza1996** [tensorflow/tensorflow#48269]
**System information**
- OS Platform and Distribution (Android 10,11):
- TensorFlow installed from : source
- TensorFlow version: 2.4.1

I am simply trying to make a model which takes time series data as input and compute rFFT/irFFT and return time series data.
I used tf.signal.rfft and tf.signal.irfft for computations. I have converted it to TFLITE and its working perfectly fine in python. But when I load it into android studio it gave me Null in interpreter. Following is code for python:

```
from tensorflow.keras.layers import  Lambda, Input
import tensorflow as tf

inp = keras.Input(shape=((197429)))
O = Lambda(stftLayer)(inp)
Z = Lambda(istftLayer)(O)
model = keras.Model(inputs=inp, outputs=Z, name="fft_model")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS ]
tflite_model = converter.convert()
with open('FFT.tflite', 'wb') as f:
    f.write(tflite_model)
```

When I give voice signal to this TFLITE model on python it returns same signal perfectly. But When I Load it into Android studio and run following code, it do not load TFLITE model properly and show NULL in Interpreter :

    private MappedByteBuffer loadModelFile() throws IOException {
    AssetFileDescriptor fileDescriptor = this.getAssets().openFd("FFT.tflite");
    FileInputStream fileInputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
    FileChannel fileChannel = fileInputStream.getChannel();
    long startOffSets = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffSets, declaredLength);
    
    }
    import org.tensorflow.lite.Interpreter;
    Interpreter tflite;
    
    try {
    tflite = new Interpreter(loadModelFile());
    
        } catch (Exception e) {
            e.printStackTrace();
        }

When I run model it gives 
**Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.run(java.lang.Object, java.lang.Object)' on a null object reference**

Following is gradle setting:

    android {
        compileSdkVersion 30
        buildToolsVersion "30.0.3"
    
        defaultConfig {
            applicationId "com.example.dtln_test"
            minSdkVersion 27
            targetSdkVersion 30
            versionCode 1
            versionName "1.0"
    
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
    
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
        }
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
        aaptOptions{
            noCompress = "tflite"
    
        }
        buildFeatures {
            mlModelBinding true
        }
    }
    
    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
    
        //implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
        implementation 'androidx.appcompat:appcompat:1.1.0'
        implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
        implementation 'org.tensorflow:tensorflow-lite:+'
        implementation 'org.tensorflow:tensorflow-lite-support:+'
        ///////////////////////////////////////////////////////////
       // implementation 'org.tensorflow:tensorflow-lite-support:0.1.0-rc1'
      //  implementation 'org.tensorflow:tensorflow-lite-metadata:0.1.0-rc1'
    //    implementation 'org.tensorflow:tensorflow-lite-gpu:2.2.0'
        testImplementation 'junit:junit:4.12'
        implementation 'com.google.android.material:material:1.2.0-alpha03'
        androidTestImplementation 'androidx.test.ext:junit:1.1.1'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    }

Any help will be greatly appreciated !!
Thanks

**Comment by Humza1996** [comment]
@gargn @ravikyram Please review this.

**Comment by abattery** [comment]
FYI, I added my answer at the same post at https://stackoverflow.com/questions/66915970

**Comment by Humza1996** [comment]
Thankyou @abattery 
Issue Resolved. While Making TFLITE with custom functions/Lambda Layers, do these steps while making tflite.

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS ]
tflite_model = converter.convert()
and in android studio add these in dependicies:

implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'

implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'

**Comment by abattery** [comment]
Glad to see it resolved. Have a nice day!
