### ISSUE TITLE
Compatibility with numpy 1.20

### ISSUE THREAD

**Issue by mahmoodn** [tensorflow/tensorflow#48271]
Hi
May I know if there is any note about the numpy version and tensorflow? It seems that the master branch doesn't work with numpy==1.20.0.

Is that right? If yes, is there any workaround for that?

**Comment by Saduf2019** [comment]
@mahmoodn 
Not for 2.4.x. For nightly or future releases please subscribe to #47691 which is WIP.
Could you please refer to these issues #47691, #47878.

Kindly move this to closed status if it answers your question, as this is already tracked.
