### ISSUE TITLE
Autograph produces code with invalid syntax when transforming expressions containing tensor slicing with a colon in tf 2.6.0

### ISSUE THREAD

**Issue by lshug** [tensorflow/tensorflow#48289]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 11
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-54030-g23c3e3c4ad1 2.6.0-dev20210331
- Python version: 3.9.2
- CUDA/cuDNN version: using a CPU
- GPU model and memory: using a CPU

**Describe the current behavior**
When transforming expressions containing tensor slicing, autograph puts the contents of the brackets in parentheses (wraps them in a tuple). This produces invalid syntax if one of the characters in the brackets is a colon.

**Describe the expected behavior**
Autograph should transform expressions involving tensor slicing with colons without producing code that contains invalid syntax. 

**Standalone code to reproduce the issue**
```
import tensorflow as tf

@tf.function
def test_function(x):
    return x[:,0]

test_function(tf.ones((1, 1)))
```

**Other info / logs**

The above code produces the following warning:
```
WARNING:tensorflow:AutoGraph could not transform <function test_function at 0x7fd9511f7040> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpna4wrl96.py, line 12)
```
Full output is attached as [output.log](https://github.com/tensorflow/tensorflow/files/6252266/output.log).

The contents of the temporary file produced by autograph are:
```
# coding=utf-8
def outer_factory():

    def inner_factory(ag__):

        def tf__test_function(x):
            with ag__.FunctionScope('test_function', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
                do_return = False
                retval_ = ag__.UndefinedReturnValue()
                try:
                    do_return = True
                    retval_ = ag__.ld(x)[(:, 0)]
                except:
                    do_return = False
                    raise
                return fscope.ret(retval_, do_return)
        return tf__test_function
    return inner_factory
```

The syntax error is in the expression ```retval_ = ag__.ld(x)[(:, 0)]```. Removing the parentheses around ```:, 0``` fixes the error.

This problem does not appear when using tf 2.2.0. I haven't tested with other versions.

**Comment by amahendrakar** [comment]
@lshug,
I did not face any warnings while running the code with [TF v2.4](https://colab.research.google.com/gist/amahendrakar/36dc1a339008e4ec6d8b60d4d252d2be/48289.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/a5c77d368133c0c9a1570c9a2f361c47/48289-tf-nightly.ipynb). Please check the linked gist for reference. 

Please try running the code in a new virtual environment and let us know if you are facing the same issue. Also, take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/47802#issuecomment-799555152) from a similar issue and check it it helps.

Thanks!

**Comment by lshug** [comment]
@amahendrakar I think the issue is not being reproduced on your TF-nightly colab because it's using python 3.7. I encountered this issue on python 3.9. [Here's a colab reproducing the issue](https://colab.research.google.com/drive/1h4AoNcJz7uVHgUQrppl7bL1r5l1AXdy8?usp=sharing).  

As for suppressing the warning, I'm already avoiding it altogether by selectively not converting functions that contain tensor slicing with a colon by using the @tf.autograph.experimental.do_not_convert. The problem is the behavior, not the warning. Since autograph fails on such functions, the resultant graphs are not compiled JIT and are run as is, which can cause tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError when using things that are allowed in tf.functions but not in graph. I've included an example of this at the end of the linked colab.

**Comment by amahendrakar** [comment]
@lshug,
Thank you for the gist. 

@ymodak,
I was able to reproduce the issue with TensorFlow v2.5.0-rc1 and TF-nightly on Python 3.9. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/975ceaf88aff83ac5e0b44af1cd1b5c5/48289-tf-nightly-3-9.ipynb#scrollTo=C2V7xk9PiDE5&line=1&uniqifier=1). Thanks!

**Comment by mdanatg** [comment]
This should be fixed by https://github.com/tensorflow/tensorflow/commit/885861a9cada78487cd868f5acdbd7f2938d7a87, and should be visible in the next nightly. We'll try to patch it into the next 3.5 RC.
