### ISSUE TITLE
The new Apple M1 MLcompute Tensorflow2.4 not compatible with Numpy 1.20.1, after attempting installing ~>1.19.2, got error

### ISSUE THREAD

**Issue by xxl4tomxu98** [tensorflow/tensorflow#48280]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Air M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Github Apple MLcompute repo
- TensorFlow version: 2.4
- Python version: 3.9
- Installed using virtualenv? pip? conda?: conda, miniforge3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
After #48237, I uninstalled 1.20.1 and 1.18.5 and tried to install 1.19.2 or ~>1.19.2. error 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I uninstalled numpy 1.20.1 and 1.18.5 and tried to install numpy~=1.19.2 and got this error:
```
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@xxl4tomxu98 
Can you please refer to this link and move this to closed status as this is more apt to pen this issue on the mentioned repo.
