### ISSUE TITLE
Update/Refactor Community Page

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#48285]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/community/contribute/community

## Description of issue (what needs changing):
There some outdated and missing info in this page. See the thread at
https://github.com/tensorflow/docs/pull/1868#issuecomment-812568979

/cc @theadactyl

**Comment by Saduf2019** [comment]
@bhack  @theadactyl 
Checking if this is still an issue. Thanks!

**Comment by bhack** [comment]
Palese keep this alive /cc @theadactyl 

See the original thead at https://github.com/tensorflow/docs/pull/1868#issuecomment-812568979
