### ISSUE TITLE
UnboundLocalError 'strategy' referenced before assignment during SSD mobilenet FPN evaulation 

### ISSUE THREAD

**Issue by Ethylbenzol** [tensorflow/tensorflow#48288]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no custom code. Using stock example in tensorflow
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087
- Python version: 3.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1 
- GPU model and memory: RTX 2080, 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I used this `python model_main_tf2.py --model_dir=models\my_mobilenet640v2 --pipeline_config_path=models\my_mobilenet640v2\pipeline.config --checkpoint_dir=models\my_mobilenet640v2 --wait_interval=60 --eval_timeout=60` in stock model_main_tf2.py to evaluate a new trained object detection model using my own custom set of image data while training on top of a pre-trained model.

It throw a error 'UnboundLocalerror: local variable 'strategy' referenced before assignment.
pastebin of error: https://pastebin.com/rjfY6dhp
**Describe the expected behavior**
strategy scope should not have have error
Will ignoring this error cause any potential problems when exporting to tflite using export_tflite_ssd_graph.py ?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
>no custom code. Using stock example in tensorflow

@Ethylbenzol,
Could you please provide a minimal code snippet to reproduce the issue reported here or share the link of the example.

Also, please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. Thanks!

**Comment by Ethylbenzol** [comment]
Hey man thanks for the follow up.

> Could you please provide a minimal code snippet to reproduce the issue reported here or share the link of the example.
I used the exact code here at
` https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py `

I did however modified it a bit using tensorflow GPU ram control default code, and reduce the wait time from 300 to 120. You can read my code at https://pastebin.com/c3X3dvGY

>  please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same error. 

I dont think using default code would affect anything. I will make an upgrade to to TF 2.4.1 and make a follow up on your recommendation to see if anything fixes it.

**Comment by Ethylbenzol** [comment]
I'm actually using tensorflow object detection and that officially says it is still in TF2.2/ 2,3? Will there be issues when upgrading the tensorflow package to 2.4.1?

**Comment by Ethylbenzol** [comment]
Updated to 2.4.1. Error is resolved

**Comment by amahendrakar** [comment]
@Ethylbenzol,
Thank you for the update. Closing the issue as it is resolved. Please feel free to re-open if necessary.
