### ISSUE TITLE
Custom Layer Using Packages Other Than Tensorflow

### ISSUE THREAD

**Issue by JKhodadadi** [tensorflow/tensorflow#48292]
**System information**
- TensorFlow version (2.4.1):
- Are you willing to contribute it (If you pay yes):

**Describe the feature and the current behavior/state.**
Currently you can't use packages other than tensorflow to build a layer 

**Will this change the current api? How?**
I don't know

**Who will benefit with this feature?**
Everyone who wants to use packages like graph analysis or topological data analysis to build a custom layer for specific works .

**Comment by AdityaKane2001** [comment]
@Javadcs 
This is a great idea with the perspective that TensorFlow can incorporate things without any constraints. Unfortunately, this is not the case, actually far from it. Reason is (sort of) simple - Graph mode and associated things. Models and Layers in TensorFlow usually work with Graph mode on, which means that they need to be traced before execution. Now, we cannot trace non-TensorFlow constructs in the graph, it's just the way it works. The primary reason being compatibility and performance. Compatibility- TF's core is made of predefined ops and kernels, which can be extended by the user if need arises, but are in my opinion difficult to manipulate. Performance- by making such a graph and using TF constructs, TF is very fast, even for very complex operations like training a model. Thus, adding a feature allowing custom packages is not currently possible in TensorFlow, unless there are some **MAJOR** changes. 
And by the way, nobody's getting paid here (atleast most of them). All of them are here for the love of it :) .

**Comment by qlzh727** [comment]
Thanks @AdityaKane2001 for the reply.

@Javadcs, could you give a more specific example about what exact issue you are facing? A small reproducible example might help us better understand you issue.

**Comment by Javadcs** [comment]
> @Javadcs
> This is a great idea with the perspective that TensorFlow can incorporate things without any constraints. Unfortunately, this is not the case, actually far from it. Reason is (sort of) simple - Graph mode and associated things. Models and Layers in TensorFlow usually work with Graph mode on, which means that they need to be traced before execution. Now, we cannot trace non-TensorFlow constructs in the graph, it's just the way it works. The primary reason being compatibility and performance. Compatibility- TF's core is made of predefined ops and kernels, which can be extended by the user if need arises, but are in my opinion difficult to manipulate. Performance- by making such a graph and using TF constructs, TF is very fast, even for very complex operations like training a model. Thus, adding a feature allowing custom packages is not currently possible in TensorFlow, unless there are some **MAJOR** changes.
> And by the way, nobody's getting paid here (atleast most of them). All of them are here for the love of it :) .

Hi, thanks for answering me I appreciated it, that was a great idea to improve performance in this area which had two winters that both of them were related to it.
Can you guide me to know what is the structure of TensorFlow again I would appreciate it.

That was a joke for my friend I didn't intend to write it seriously I hope you and other researchers didn't take any offense
Good luck and good wishes.

**Comment by Javadcs** [comment]
> Thanks @AdityaKane2001 for the reply.
> 
> @Javadcs, could you give a more specific example about what exact issue you are facing? A small reproducible example might help us better understand you issue.

Hi thanks for your concern, I wanted to have a custom topological layer in a CNN but as @AdityaKane2001 said for improving performance which is notable it is impossible right now.

**Comment by AdityaKane2001** [comment]
@Javadcs 
What do you want to know about TensorFlow's structure? Any specific parts?
I'm also new to this, but I'll try my best.

**Comment by jvishnuvardhan** [comment]
@JKhodadadi Is there any actionable item like raising PR? 

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues). Thanks!
