### ISSUE TITLE
Core ML delegate for TensorFlow Lite does not run examples/lite/examples/image_classification/ios on Neural Engine.

### ISSUE THREAD

**Issue by y-ich** [tensorflow/tensorflow#48296]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, according to https://www.tensorflow.org/lite/performance/coreml_delegate.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPad Air(Gen.4)
- TensorFlow installed from (source or binary): I have no idea since I used pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
- TensorFlow version (use command below): I have no idea since I used pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Using Core ML delegate does not have any performance boost compared with the original code on A14 processor.

**Describe the expected behavior**
Using Core ML delegate should have performance boost compared with the original code by A14 Neural Engine.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

examples/lite/examples/image_classification/ios/ in https://github.com/y-ich/examples/tree/coreml_delegate

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
Could you take a look at this @lintian06 @yyoon

**Comment by sachinprasadhs** [comment]
The example which you have mentioned is outdated and is moved to a different location, please find the latest Image classification example from below links and let us know if you still face an error. Thanks!
1. https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_classifier
2. https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios
