### ISSUE TITLE
Add option to reset a tf.data.Iterator / tf.distribute.DistributedIterator

### ISSUE THREAD

**Issue by Yannik1337** [tensorflow/tensorflow#48297]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
We can iterate over a `tf.data.dataset` using `for element in datasetA:`. This automatically "restarts" if we run this for multiple epochs, as seen in this code:
```
datasetA = tf.data.Dataset.from_tensor_slices([1,  2,  3,  4,  5, 6])

for epoch in range(10):
  print(f"Epoch {epoch}")
  for element in datasetA:
    print(element)
``` 
When using an iterator `iterB = iter(datasetB)` we can exhaust the iteration, as seen in this code:

```
datasetA = tf.data.Dataset.from_tensor_slices([1,  2,  3,  4,  5, 6])
datasetB = tf.data.Dataset.from_tensor_slices([11, 22, 33, 44])

iterB = iter(datasetB)
epochs = 5

for epoch in range(epochs):
  print(f"Epoch {epoch}")
  for element in datasetA:
    print(element)
    elementB = iterB.get_next()
    print(elementB)
```

We can handle this by catching the error or using `get_next_as_optional()`, and **manually** restart the iteration:
```
for epoch in range(epochs):
  print(f"Epoch {epoch}")
  for element in datasetA:
    print(element)
    elementB = iterB.get_next_as_optional()
    if not elementB.has_value():
      iterB = iter(datasetB) #<--- restarts the iterator manually
      elementB = iterB.get_next_as_optional()

    print(elementB.get_value())
```
I propose a method like `.reset_iterator()` or `restart_iterator()` that handles this case conveniently. The same holds for distributed iterators.

**Will this change the current api? How?**
This won't have any effect

**Who will benefit with this feature?**
- Users that iterate over a dataset element by element, without using `for elem in dataset:` loops
- Users iterating multiple datasets **pairwise** simultaneously (see this [question](https://stackoverflow.com/questions/66929798/how-to-do-a-pairwise-iteration-over-two-unequal-length-tf-datasets/66931999#66931999))

**Any Other info.**
As an alternative, make the `.take(count)` operation advance the internal state, so that repeatedly taking `count` elements yields the next element, rather than the same.

**Comment by AdityaKane2001** [comment]
@Yannik1337 
Please take a look at [this](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#zip).

**Comment by Yannik1337** [comment]
@AdityaKane2001 Thanks for this link, I used the `.zip()` method to zip the two datasets like this:
```
datasetA = tf.data.Dataset.from_tensor_slices([1,  2,  3,  4,  5, 6])
datasetB = tf.data.Dataset.from_tensor_slices([11, 22, 33, 44])

zipped_ds = tf.data.Dataset.zip((datasetA, datasetB))

for elem in zipped_ds:
  print(elem)
```

However, as is stated in the documentation, this will only contain as many pairs as there are elements in the shorter dataset

I am looking for a way to restart the iteration over the shorter dataset, e.g. when we have element `5` from `datasetA`, we take `11` from `datasetB` (which is its first element). This is the intent of my feature request, so that one can restart the iterator once it's fully consumed.

**Comment by AdityaKane2001** [comment]
@Yannik1337 
Please see [repeat](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#repeat) in `tf.data.dataset`

**Comment by Yannik1337** [comment]
This solved my request, thanks @AdityaKane2001 for helping me out!
