### ISSUE TITLE
How to use Conv1D on microcontrollers?

### ISSUE THREAD

**Issue by Lucy20211** [tensorflow/tensorflow#48290]
@tensorflow/micro

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow version: 2.4.1
- Python version : 3.8
- STM32CubeIDE-Lnx: 1.3.0
- STM32 Nucleo-64 development board with STM32F401RE MCU

**Describe the problem**

I would like to run inference on ST microcontroller above by using a model characterized by Conv1D layers. For this reason, I should create a file .tflite, from which to generate a file .h, and a main program, main.cpp. In particular, in main.cpp I thought I would use something like this:

`// Pull in only needed operations (should match NN layers).`
`// Template parameter <n> is number of ops to be added. Available ops:`
`// tensorflow/lite/micro/kernels/micro_ops.h`

`static tflite::MicroMutableOpResolver <1> micro_op_resolver;`
`tflite_status = micro_op_resolver.Conv1D();`
 
 `if (tflite_status != kTfLiteOk) {`
   `error_reporter->Report("Could not add Conv1D op");`
`while(1);`
`}`

However, the Conv1D operation shouldn't be supported by TensorFlow Lite: how can I solve this problem? Have I create a custom operator, in order to implement the Conv1D op (https://www.tensorflow.org/lite/guide/ops_custom), or there is another way to fix it? 

By following the link above, in order to create and register Conv1D op, I wrote this simple code:

`import tensorflow as tf`
`tf.config.run_functions_eagerly(True)`

`input_shape = (1, 7, 1)`
`x = tf.random.normal(input_shape)`

`@tf.function`
`def convol1d():`
   `y=tf.keras.layers.Conv1D(1, 3, input_shape=input_shape[1:], name="Conv1D")(x)`
`return y`

`data = convol1d()`
`print("\n\n data is:", data)`

`tflite_model_name = 'convol1d' `
`converter = tf.lite.TFLiteConverter.from_concrete_functions([convol1d.get_concrete_function()])`
`converter.allow_custom_ops = True`
`tflite_model = converter.convert()`
`open(tflite_model_name + '.tflite', 'wb').write(tflite_model)`

If I run it, it appears the following error:

`ValueError: tf.function-decorated function tried to create variables on non-first call.`

Instead, I would expect it:

`Error:
Didn't find custom operator for name 'Conv1D'`
`Registration failed.`

If this latter error appeared, I would try to define the functions Prepare and Eval and construct a TfLiteRegistration in a file .cpp (in tensorflow/tensorflow/lite/kernels), then I would add an AddCustom call to register.cpp, always in tensorflow/tensorflow/lite/kernels, am I right? At this point, if all went well, I think I could finally use the op. I'm new to TensorFlow.

Thanks in advance.

**Comment by iteachmachines** [comment]
Try to reinstall tensorflow and see if it works fine with previous version.It seems like it couldn't find the 'Conv1D' file in keras.

**Comment by Lucy20211** [comment]
Hi @iteachmachines, thanks for your response, but unfortunately I had problems even by using a previous version.

**Comment by ymodak** [comment]
Did you try converting your model with Conv1D layer into TF Lite format?
See [example](https://github.com/tensorflow/tensorflow/issues/39823) where user could successfully convert it into tflite.

**Comment by Lucy20211** [comment]
Thanks @ymodak for your reply. If I don't use @tf.function decorator, I can convert my model into TF Lite format; if I do, it apperas the ValueError error. Maybe should I try to download the TF-nightly version to solve this error?

**Comment by jensmeder** [comment]
Conv1D will be converted to a combination of layers supported on TF Lite Micro including ExpandDims and Conv2D. Unfortunately, the ExpandDims layer is currently unsupported in TF Lite Micro so you have to use a workaround. See [my comment ](https://github.com/tensorflow/tensorflow/issues/43141#issuecomment-813046876)in #43141 for more details.

**Comment by Lucy20211** [comment]
Hi @jensmeder, thanks for your reply. Your solution can be very useful; however, I need to use dilated convolutions 1D which are causal (I had not specified this requirement). For this reason, I should use a type of padding which is causal; for layers conv1D I can specify a value for padding equal to "causal", while for conv2D not (one can choose only between "valid" and "same" if I'm right). How can I use conv2D which is both dilated and causal?

**Comment by ymodak** [comment]
@Lucy20211 I would suggest to open a new github issue thread for discussing topic other than the original query. This way it helps future users to access the appropriate information easily. Can you please post a new issue if your original question has been answered? Thanks!
