### ISSUE TITLE
boringssl error : invalid use of incomplete type 'BIO'

### ISSUE THREAD

**Issue by jaytoone** [tensorflow/tensorflow#48299]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: raspberrypi 3
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.3, 2.4.1, 2.0.0 (these versions are tried)
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: by bazel
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): local : 7.5.0
- CUDA/cuDNN version: 10
- GPU model and memory:

**Describe the problem**

using openssl version 1.0.2g, 1.1.1h, 1.1.1k ..., all trial has been failed.
I couldn't complete tensorflow lite lib building using below command, any suggestion would be really helpful regard to this issue.
(I tried boringssl version downgrade / upgrade, but it didn't worked)
![tried_version_boringssl](https://user-images.githubusercontent.com/50652715/113537568-06a63400-9614-11eb-8a31-fcaf4467a3aa.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

sudo bazel build \
--config=elinux_armhf \
--config=monolithic \
--config=noaws \
--config=nohdfs \
--config=nonccl \
--config=nogcp \
--config=v1 \
--copt=-O \
-c opt \
--verbose_failures \
--define=tensorflow_mkldnn_contraction_kernel=0 \
--define=with_xla_support=false \
--define=with_gcp_support=false \
--define=tflite_convert_with_select_tf_ops=true \
--define=with_select_tf_ops=true \
//tensorflow/lite:libtensorflowlite.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

/home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/boringssl/BUILD:137:1: C++ compilation of rule '@boringssl//:ssl' failed (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/ubuntu/.cache/bazelisk/downloads/bazelbuild/bazel-3.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.6/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
  /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/lib/gcc/arm-linux-gnueabihf/8.3.0/include -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/lib/gcc/arm-linux-gnueabihf/8.3.0/include-fixed -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/arm-linux-gnueabihf/include/c++/8.3.0/ -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/arm-linux-gnueabihf/libc/usr/include/ -isystem /usr/include/python3.5 -isystem /usr/include/ -MD -MF bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.d '-frandom-seed=bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.o' -fPIC -iquote external/boringssl -iquote bazel-out/armhf-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/armhf-opt/bin/external/boringssl/src/include -w -DAUTOLOAD_DYNAMIC_KERNELS -O '-std=c++14' -DOPENSSL_NO_ASM -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c external/boringssl/src/ssl/bio_ssl.cc -o bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.o)
Execution platform: @local_execution_config_platform//:platform
external/boringssl/src/ssl/bio_ssl.cc: In function 'SSL* get_ssl(BIO*)':
external/boringssl/src/ssl/bio_ssl.cc:16:37: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
   return reinterpret_cast<SSL *>(bio->ptr);
                                     ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc: In function 'int ssl_read(BIO*, char*, int)':
external/boringssl/src/ssl/bio_ssl.cc:40:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->retry_reason = BIO_RR_ACCEPT;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc:45:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->retry_reason = BIO_RR_CONNECT;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc: In function 'int ssl_write(BIO*, const char*, int)':
external/boringssl/src/ssl/bio_ssl.cc:80:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->retry_reason = BIO_RR_CONNECT;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc: In function 'long int ssl_ctrl(BIO*, int, long int, void*)':
external/boringssl/src/ssl/bio_ssl.cc:101:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->shutdown = num;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc:102:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->ptr = ptr;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc:103:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->init = 1;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc:107:17: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       return bio->shutdown;
                 ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc:110:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
       bio->shutdown = num;
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc: In function 'int ssl_free(BIO*)':
external/boringssl/src/ssl/bio_ssl.cc:148:10: error: invalid use of incomplete type 'BIO' {aka 'struct bio_st'}
   if (bio->shutdown) {
          ^~
In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/comp.h:16,
                 from /usr/include/openssl/ssl.h:17,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
/usr/include/openssl/ossl_typ.h:79:16: note: forward declaration of 'BIO' {aka 'struct bio_st'}
 typedef struct bio_st BIO;
                ^~~~~~
external/boringssl/src/ssl/bio_ssl.cc: At global scope:
external/boringssl/src/ssl/bio_ssl.cc:170:25: error: variable 'const BIO_METHOD ssl_method' has initializer but incomplete type
 static const BIO_METHOD ssl_method = {
                         ^~~~~~~~~~
In file included from /usr/include/openssl/ssl.h:18,
                 from external/boringssl/src/ssl/bio_ssl.cc:10:
external/boringssl/src/ssl/bio_ssl.cc:177:6: error: expected identifier before numeric constant
 long BIO_set_ssl(BIO *bio, SSL *ssl, int take_owership) {
      ^~~~~~~~~~~
external/boringssl/src/ssl/bio_ssl.cc:177:6: error: expected ',' or '...' before numeric constant
external/boringssl/src/ssl/bio_ssl.cc: In function 'long int BIO_ctrl(BIO*, int)':
external/boringssl/src/ssl/bio_ssl.cc:178:39: error: 'take_owership' was not declared in this scope
   return BIO_ctrl(bio, BIO_C_SET_SSL, take_owership, ssl);
                                       ^~~~~~~~~~~~~
external/boringssl/src/ssl/bio_ssl.cc:178:54: error: 'ssl' was not declared in this scope
   return BIO_ctrl(bio, BIO_C_SET_SSL, take_owership, ssl);
                                                      ^~~
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 8014.552s, Critical Path: 118.45s
INFO: 6038 processes: 6038 local.
FAILED: Build did NOT complete successfully

**Comment by Saduf2019** [comment]
@jaytoone 
Can you please try on virtual env and let us know.

**Comment by jaytoone** [comment]
with virtual env, I got below error
![virtualenv](https://user-images.githubusercontent.com/50652715/113793652-c6fe5a00-9783-11eb-896e-b232cf5169a3.png)


error log changed, but occurs in borringssl too
--------------- error head --------------------
/home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/boringssl/BUILD:137:1: C++ compilation of rule '@boringssl//:ssl' failed (Exit 1): arm-linux-gnueabihf-gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/ubuntu/.cache/bazelisk/downloads/bazelbuild/bazel-3.1.0-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/ubuntu/.local/bin/.virtualenvs/tf_bazel/bin/python3 \
    PYTHON_LIB_PATH=/home/ubuntu/.local/bin/.virtualenvs/tf_bazel/lib/python3.6/site-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
    TF_ENABLE_XLA=1 \
  /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/lib/gcc/arm-linux-gnueabihf/8.3.0/include -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/lib/gcc/arm-linux-gnueabihf/8.3.0/include-fixed -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/arm-linux-gnueabihf/include/c++/8.3.0/ -isystem /home/ubuntu/.cache/bazel/_bazel_root/d207b6c8dd83044074c0d1d7461cfde0/external/armhf_linux_toolchain/arm-linux-gnueabihf/libc/usr/include/ -isystem /usr/include/python3.5 -isystem /usr/include/ -MD -MF bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/dtls_method.pic.d '-frandom-seed=bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/dtls_method.pic.o' -fPIC -iquote external/boringssl -iquote bazel-out/armhf-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/armhf-opt/bin/external/boringssl/src/include -w -DAUTOLOAD_DYNAMIC_KERNELS -O '-std=c++14' -DOPENSSL_NO_ASM -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c external/boringssl/src/ssl/dtls_method.cc -o bazel-out/armhf-opt/bin/external/boringssl/_objs/ssl/dtls_method.pic.o)
Execution platform: @local_execution_config_platform//:platform
In file included from external/boringssl/src/ssl/../crypto/internal.h:112,
                 from external/boringssl/src/ssl/dtls_method.cc:65:
external/boringssl/src/include/openssl/ex_data.h:181:52: error: macro "CRYPTO_cleanup_all_ex_data" passed 1 arguments, but takes just 0
 OPENSSL_EXPORT void CRYPTO_cleanup_all_ex_data(void);
                                                    ^
In file included from external/boringssl/src/ssl/../crypto/internal.h:114,
                 from external/boringssl/src/ssl/dtls_method.cc:65:
external/boringssl/src/include/openssl/thread.h:120:41: error: macro "CRYPTO_num_locks" passed 1 arguments, but takes just 0
 OPENSSL_EXPORT int CRYPTO_num_locks(void);
                                         ^
external/boringssl/src/include/openssl/thread.h:131:55: error: macro "CRYPTO_get_locking_callback" passed 1 arguments, but takes just 0
 OPENSSL_EXPORT void (*CRYPTO_get_locking_callback(void))(int mode, int lock_num,
                                                       ^
external/boringssl/src/include/openssl/thread.h:176:45: error: macro "CRYPTO_get_dynlock_create_callback" passed 1 arguments, but takes just 0
     *CRYPTO_get_dynlock_create_callback(void))(const char *file, int line);
                                             ^
external/boringssl/src/include/openssl/thread.h:179:60: error: macro "CRYPTO_get_dynlock_lock_callback" passed 1 arguments, but takes just 0
 OPENSSL_EXPORT void (*CRYPTO_get_dynlock_lock_callback(void))(
                                                            ^
external/boringssl/src/include/openssl/thread.h:183:63: error: macro "CRYPTO_get_dynlock_destroy_callback" passed 1 arguments, but takes just 0
 OPENSSL_EXPORT void (*CRYPTO_get_dynlock_destroy_callback(void))(
