### ISSUE TITLE
Request for angle

### ISSUE THREAD

**Issue by fxsuper** [tensorflow/tensorflow#483]
Getting the angle of a complex number is another mathematical operation that would be useful / basic to have, along the lines of [np.angle](http://docs.scipy.org/doc/numpy/reference/generated/numpy.angle.html).

**Comment by girving** [comment]
That's a good feature request.  For complex numbers, it should be called `tf.arg` or `tf.argument`.

**Comment by RyanYoung25** [comment]
I'm a part of a group of 4 students from Drexel University who are currently working on this. Because we are not very familiar with tensorflow we are going to start by implementing tf.argument() directly as a kernel without a GPU kernel. After we get that we are going to try to implement atan, as implemented by eigen, and then making the tf.argument function a composition. Let us know if you have any tips, advice, or feedback.

**Comment by martinwicke** [comment]
If you write the op in all Eigen (which seems entirely achievable), you
should be able to write it once for both CPU and GPU. AdjustContrast is an
example of that, and how the final op is registered.

**Comment by RyanYoung25** [comment]
Thanks! We will take a look at that.

**Comment by girving** [comment]
Let's call it `tf.arg` rather than `tf.argument` for symmetry with `tf.abs`.

**Comment by RyanYoung25** [comment]
Will do. We found an implementation of argument in eigen called scalar_arg_op. Should we use that implementation or proceed with registering atan and defining arg as a tf function composition?

**Comment by vrv** [comment]
Since Eigen already has scalar_arg_op defined, we might as well use that for better performance on both CPU and GPU :)

**Comment by RyanYoung25** [comment]
Ok, we can do that.

**Comment by RyanYoung25** [comment]
We were able to get arctan implemented and working great with complex64 numbers. We're running into an issue with registering the scalar_arg_op with the complex64 data type. We can get arg to compile when we register it only with floats and double without errors, but when we call it in python it fails when passed a complex64 as expected. We think the error we are getting stems from: 

``` 
no known conversion for argument 1 from 
'Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 16>, 
Eigen::ThreadPoolDevice>::Scalar* {aka std::complex<float>*}' to 'Eigen::TensorEvaluator<const 
Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_arg_op<std::complex<float> >, const 
Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 1, 1, long int>, 16> >, 
Eigen::ThreadPoolDevice>::Scalar* {aka float*}
```

does this look familiar to anyone that could point us in the right direction? If not we will use arctan to implement arg.

**Comment by sesse** [comment]
If you present a compile error, you'll also need to present the code that doesn't comiple. It seems like you are trying to assign a complex<float> array to a float.

**Comment by asp78** [comment]
I'm working with Ryan on this. We have it working utilizing the Eigen implementation of arg and are currently in the process of writing tests for it. We haven't been able to test it on a GPU enabled device but will likely be able to do that soon as well, should we wait until we do that to submit a pull request? Also, we were curious if we should include the code we created for implementing arctan through Eigen before we knew that Eigen had a method for computing the argument directly.

**Comment by girving** [comment]
Yep, let's wait for the GPU enabled device test.  As for the custom arg code, don't include it unless it is used in the final version.

**Comment by carlthome** [comment]
Status?

**Comment by RyanYoung25** [comment]
Hi, sorry for the delay in updates. We finished implementing the feature but still have not been able to access a machine with a GPU to test if it is fully functional. If anyone would like to help us finish testing and get the code base up to a state where we can submit a pull request I'd be more than happy to add them as a collaborator or they can fork my fork.

**Comment by ibab** [comment]
@RyanYoung25: I have a machine with a GPU and can help you with this.
You could start by creating a PR that adds `tf.arg` for the CPU, ideally with a few tests to make sure that it works correctly.

**Comment by fxsuper** [comment]
Any updates on this?

**Comment by beniroquai** [comment]
One up. Any updates on that?

**Comment by fbcotter** [comment]
(This is obviously only a temporary fix for those that find themselves at this thread before the official tf.arg is added). You can do it with existing tensorflow operations, like:

    def angle(z):
        """
        Returns the elementwise arctan of z, choosing the quadrant correctly.

        Quadrant I: arctan(y/x)
        Qaudrant II: π + arctan(y/x) (phase of x<0, y=0 is π)
        Quadrant III: -π + arctan(y/x)
        Quadrant IV: arctan(y/x)

        Inputs:
            z: tf.complex64 or tf.complex128 tensor
        Retunrs:
            Angle of z
        """
        if z.dtype == tf.complex128:
            dtype = tf.float64
        else:
            dtype = tf.float32
        x = tf.real(z)
        y = tf.imag(z)
        xneg = tf.cast(x < 0.0, dtype)
        yneg = tf.cast(y < 0.0, dtype)
        ypos = tf.cast(y >= 0.0, dtype)

        offset = xneg * (ypos - yneg) * np.pi

        return tf.atan(y / x) + offset

**Comment by fbcotter** [comment]
Also, I would have thought calling it `tf.angle` would be nicer than `tf.arg`, as it then mimics numpy's `np.angle`

**Comment by carlthome** [comment]
> Also, I would have thought calling it tf.angle would be nicer than tf.arg, as it then mimics numpy's 
np.angle

Conformity is great, but then for API symmetry, `tf.abs` should also have an alias `tf.magnitude` that only takes complex numbers, no? It's rather NumPy that goofed by having abs(z) but not arg(z), IMO. Also, angle could refer to a lot of things not related to complex numbers, in my mind.

**Comment by beniroquai** [comment]
Short question - is the GPU version already working? I was wondering why my model is so slow, a device_placement log gave me this:
`Back_Propagate/Back_Propagate_Step/Propagate/Angle: (Angle): /job:localhost/replica:0/task:0/device:CPU:0
`
All other Nodes are on GPU though. Right now I'm using TF v1.13 on Windows

**Comment by martinwicke** [comment]
No, the original patch 227fc9f had build failures for GPU (see also #10643). Potentially those are gone, so it's worth enabling again. 

See the patch for the `#if 0`s, maybe try removing those and see whether that works.
