### ISSUE TITLE
OperatorNotAllowedInGraphError

### ISSUE THREAD

**Issue by 1165628028** [tensorflow/tensorflow#48305]
- TensorFlow version :2.4.0(gpu)

I am a beginner to tensorflow, when I run the following code,it report error:     OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

def create_placeholders(n_x):
    x = tf.placeholder(tf.float32,  [None, n_x], name = "x")    
    return x

def get(x):
    [r, c] = tf.shape(x)
    mat = tf.zeros([r, c])
    return np.array(mat, dtype='float32')

@tf.function
def model(h):
    (m, n_x) = h.shape
    x = create_placeholders(n_x) 
    with tf.name_scope("x_layer"):
        z = get(x)

    with tf.Session() as sess:
        v = tf.Variable(tf.ones([2,3]), name="v") 
        z = sess.run([z], feed_dict={x: v})           

h = tf.Variable(tf.ones([3,3]), name="h")
model(h)
```

I don't know what's wrong in code， how can i solve it?

**Comment by 1165628028** [comment]
Error track：
```
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:

    /media/D/ly/code/IEEE_TGRS_GCN-master/IEEE_TGRS_GCN-master/practice.py:19 model  *
        z = get(x)
    /media/D/ly/code/IEEE_TGRS_GCN-master/IEEE_TGRS_GCN-master/practice.py:10 get  *
        [r, c] = tf.shape(x)
    /home/ly/anaconda3/envs/tensorflow-gpu2.4.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:505 __iter__
        self._disallow_iteration()
    /home/ly/anaconda3/envs/tensorflow-gpu2.4.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:498 _disallow_iteration
        self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
    /home/ly/anaconda3/envs/tensorflow-gpu2.4.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:476 _disallow_when_autograph_enabled
        " indicate you are trying to use an unsupported feature.".format(task))
```

**Comment by Saduf2019** [comment]
@1165628028 

Can you please upgrade to tf 2.5 and let us know if you face the error, you may also refer to below similar issues:

#45079, [link](https://stackoverflow.com/questions/62068323/iterating-over-tf-tensor-is-not-allowed-autograph-is-disabled-in-this-function)

**Comment by 1165628028** [comment]
> @1165628028
> 
> Can you please upgrade to tf 2.5 and let us know if you face the error, you may also refer to below similar issues:
> 
> #45079, [link](https://stackoverflow.com/questions/62068323/iterating-over-tf-tensor-is-not-allowed-autograph-is-disabled-in-this-function)

Ok, i will try it. Thanks

**Comment by 1165628028** [comment]
I try it in tf2.5, but it also report same error: 
`    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

**Comment by 1165628028** [comment]
I try it in tf2.5, but it also report same error :
`  OperatorNotAllowedInGraphError: iterating over  `tf.Tensor`  is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

**Comment by 1165628028** [comment]
The error lie in : def get(x)
`    [r, c] = tf.shape(x) `, i don't know why this  sentence is wrong

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4,tf 2.5 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/0e09ff8f6996796a9863ec2039e24bdb/untitled585.ipynb).

**Comment by 1165628028** [comment]
> I am able to replicate the issue reported on tf 2.4,tf 2.5 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/0e09ff8f6996796a9863ec2039e24bdb/untitled585.ipynb).

Thank you very much for your help, maybe it's a syntax problem, not a version problem

**Comment by Saduf2019** [comment]
@1165628028 
Please confirm if the issue is resolved, if yes move this issue to closed status.

**Comment by ymodak** [comment]
> The error lie in : def get(x)
> ` [r, c] = tf.shape(x)`, i don't know why this sentence is wrong

`tf.shape` method gives dynamic shape of tensor which fails when tuple unpacking is triggered.
`.shape` method provides static shape of tensor in the form of tuples.
