### ISSUE TITLE
MHLO to LMHLO function signature conversion: missing output argument and stale comments

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#48302]
With the tensorflow git HEAD at the current master tip a83625aff5add82a150b41922ff99ad0f27fbb35 (Apr 5, 2021), I see the following issues: most of them appear are be due to stale code and an incomplete update post migration to new utilities.

INPUT
```
func @main(%arg0: tensor<1024x1024xf64>, %arg1: tensor<1024x1024xf64>) -> tensor<1024x1024xf64> {
    %0 = "mhlo.dot"(%arg0, %arg1) : (tensor<1024x1024xf64>, tensor<1024x1024xf64>) -> tensor<1024x1024xf64>
    "mhlo.return"(%0) : (tensor<1024x1024xf64>) -> ()
  }
```

OUTPUT
```
$ tf-opt -hlo-legalize-to-lhlo  dot.mlir 
module  {
  func @main(%arg0: memref<1024x1024xf64>, %arg1: memref<1024x1024xf64>) -> memref<1024x1024xf64> {
    %0 = memref.alloc() : memref<1024x1024xf64>
    "lmhlo.dot"(%arg0, %arg1, %0) {dot_dimension_numbers = {lhs_batching_dimensions = dense<> : tensor<0xi64>, lhs_contracting_dimensions = dense<1> : tensor<1xi64>, rhs_batching_dimensions = dense<> : tensor<0xi64>, rhs_contracting_dimensions = dense<0> : tensor<1xi64>}} : (memref<1024x1024xf64>, memref<1024x1024xf64>, memref<1024x1024xf64>) -> ()
    "lmhlo.copy"(%0, %arg1) : (memref<1024x1024xf64>, memref<1024x1024xf64>) -> ()
    "lmhlo.terminator"() : () -> ()
  }
}
```
The tensor being returned has been copied into the wrong memref, and the signature hasn't been converted. Looks like there are assumptions on what it would convert correctly. If the `mhlo.return` is replaced with a standard return, the output is semantically correct:
```
func @main(%arg0: memref<1024x1024xf64>, %arg1: memref<1024x1024xf64>) -> memref<1024x1024xf64> {
    %0 = memref.alloc() : memref<1024x1024xf64>
    "lmhlo.dot"(%arg0, %arg1, %0) {dot_dimension_numbers = {lhs_batching_dimensions = dense<> : tensor<0xi64>, lhs_contracting_dimensions = dense<1> : tensor<1xi64>, rhs_batching_dimensions = dense<> : tensor<0xi64>, rhs_contracting_dimensions = dense<0> : tensor<1xi64>}} : (memref<1024x1024xf64>, memref<1024x1024xf64>, memref<1024x1024xf64>) -> ()
    return %0 : memref<1024x1024xf64>
  }
```
But this is inconsistent with the large doct comment at `hlo_legalize_to_lhlo.cc` which says the return value would be converted to an output argument. The comment is probably stale and makes no mention of `-buffer-results-to-out-params` which I think is necessary to get such a conversion. 

```
  // FuncOp signature conversion example:
  //
  // func @func_op(%arg0: tensor<4xf32>, %arg1: tensor<4xf32>) -> tensor<4xf32> {
  //   %0 = "mhlo.maximum"(%arg0, %arg1) : (tensor<4xf32>, tensor<4xf32>) ->
  //   tensor<4xf32> %1 = "mhlo.add"(%arg0, %0)  : (tensor<4xf32>,
  //   tensor<4xf32>) -> tensor<4xf32> return %1 : tensor<4xf32>
  // }
  //
  // Transformed function with an extra argument for the result. The types have
  // been converted from tensor to memref.
  //
  // func @func_op(%arg0: memref<4xf32>,
  //               %arg1: memref<4xf32>,
  //               %arg2: memref<4xf32>) {
  //   %0 = alloc() : memref<4xf32>
  
  //   "lmhlo.maximum"(%arg0, %arg1, %0) :
  //         (memref<4xf32>, memref<4xf32>, memref<4xf32>) -> ()
  //   %1 = alloc() : memref<4xf32>
  //   "lmhlo.add"(%arg0, %0, %1) :
  //         (memref<4xf32>, memref<4xf32>, memref<4xf32>) -> ()
  //   "lmhlo.copy"(%1, %arg2) : (memref<4xf32>, memref<4xf32>) -> ()
  //   "lmhlo.terminator"() : () -> ()
  // }
```
Even with a `-buffer-results-to-out-params`, a `linalg.copy` is generated instead of an `lmhlo.copy` and so this comment should be updated to reflect changes in MLIR transform utilities.

CC: @silvasean @stellaraccident

**Comment by silvasean** [comment]
@sherhut who is more in touch with the mhlo->lmhlo legalization path.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
