### ISSUE TITLE
Documentation for loading `Estimator` and using it to `predict`

### ISSUE THREAD

**Issue by avivajpeyi** [tensorflow/tensorflow#48309]
Documentation and examples describing how to use a trained estimator to make predictions exist ([ref:boosted_trees_model_understanding](https://www.tensorflow.org/tutorials/estimator/boosted_trees_model_understanding)). 

Similarly, there are examples on how to save a trained estimator ([ref](https://www.tensorflow.org/guide/estimator))

However, there is a dearth of examples/documentation on how to load a saved estimator, and then use it for predictions. Currently, I am using this [stack-overflow issue](https://stackoverflow.com/questions/58959582/saving-loading-and-predicting-from-a-tensorflow-estimator-model-2-0/60230173#comment118347400_60230173) to help figure out how to do this.

**Comment by jvishnuvardhan** [comment]
@avivajpeyi The [guide](https://www.tensorflow.org/guide/estimator#savedmodels_from_estimators) you referenced above also shows how to load an estimator and run predictions. 


```
You can also load and run that model, from python:

imported = tf.saved_model.load(estimator_path)

def predict(x):
  example = tf.train.Example()
  example.features.feature["x"].float_list.value.extend([x])
  return imported.signatures["predict"](
    examples=tf.constant([example.SerializeToString()]))

print(predict(1.5))
print(predict(3.5))
```

If you think you want to update the guides, please feel free to raise a PR to update those guides. Thanks!

**Comment by avivajpeyi** [comment]
Hey @jvishnuvardhan, thanks: this works to predict 1 sample. However, it is unclear from the example/documentation if this is how one is expected to get predictions for N samples. 

Eg. in the [boosted_trees_model_understanding guide](https://www.tensorflow.org/tutorials/estimator/boosted_trees_model_understanding#visualizing_model_fitting), there is a predict function that takes an `Estimator` (`est`), and use's its `.predict` function to make predictions from N samples:

```python
def predict(est):
  """Predictions from a given estimator."""
  predict_input_fn = lambda: tf.data.Dataset.from_tensors(dict(df_predict))
  preds = np.array([p['predictions'][0] for p in est.predict(predict_input_fn)])
  return preds.reshape(predict_shape)
  ```
This is perfect! However, it doesn't work the same when I load the estimator. 


Based on the example, I tried to write a function to create a `tf.train.Example()` to pass to my loaded-estimator (in `predict_in_fn_autotrackable`). However, the time to make predictions with the loaded-estimator versus the original estimator is significantly different. 


  
```python
 
def predict_in_fn_autotrackable(input_df):
    examples = []
    for index, row in input_df.iterrows():
        feature = {}
        for col, value in row.iteritems():
            feature[col] = tf.train.Feature(
                float_list=tf.train.FloatList(value=[value]))
        example = tf.train.Example(
            features=tf.train.Features(
                feature=feature
            )
        )
        examples.append(example.SerializeToString())
    return tf.constant(examples)


def predict(model, data: pd.DataFrame):
    if isinstance(model, AutoTrackable):
        pred_fn = model.signatures['serving_default']
        preds = pred_fn(predict_in_fn_autotrackable(data))
        preds = preds['outputs'].numpy().flatten()
    else:
        predict_in_fn = lambda: tf.data.Dataset.from_tensors(dict(data))
        pred_fn = model.predict
        preds = np.array([p['predictions'][0] for p in pred_fn(predict_in_fn)])
    return preds
```

Below is a runtime-datasize plot of the original estimator's `.predict` in purple, and the loaded estimator's `.signatures['serving_default']` in red.
![Screen Shot 2021-04-06 at 12 24 04 pm](https://user-images.githubusercontent.com/15642823/113650139-13d62800-96d3-11eb-8ca7-96502407ccc1.png)

I think the issue lies in my `predict_in_fn_autotrackable` function. 

**I would love to help raise a PR to update the guides with an example of how to use a loaded estimator to make N predictions, however, I think currently I am unsure how to format my data to do so!**
