### ISSUE TITLE
tensorboard produces a lot of IOError

### ISSUE THREAD

**Issue by flyfj** [tensorflow/tensorflow#4830]
Hi, I'm using the tensorboard comes with 0.11rc.0 and it outputs a lot of warning on IOError for not able to find file or directory, e.g. /path/to/tensorflow/tensorboard/paper-item/all-imports.html. I checked the directory and there are indeed no such files. The board still runs but wonder if we can get rid of the warnings. My python env is anaconda 2.7.

**Comment by tatatodd** [comment]
@flyfj is this causing an actual problem, or is it just a matter of cleanliness?

@danmane might have some thoughts on this.

**Comment by flyfj** [comment]
the board itself seems to work (not sure if it's showing the correct thing), but looking at all the warning is just weird. Do other people encounter this issue?

**Comment by danmane** [comment]
@flyfj Can you copy+paste in the exact IOErrors you're getting?

**Comment by flyfj** [comment]
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js
127.0.0.1 - - [12/Oct/2016 16:05:01] "GET /lodash/lodash.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/all-imports.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/all-imports.html
127.0.0.1 - - [12/Oct/2016 16:05:01] "GET /paper-item/all-imports.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/iron-list/iron-list.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/iron-list/iron-list.html
127.0.0.1 - - [12/Oct/2016 16:05:01] "GET /iron-list/iron-list.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-icon-item.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-icon-item.html
127.0.0.1 - - [12/Oct/2016 16:05:01] "GET /paper-item/paper-icon-item.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-item-body.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-item-body.html
127.0.0.1 - - [12/Oct/2016 16:05:01] "GET /paper-item/paper-item-body.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /graphlib/dist/graphlib.core.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-group/paper-radio-group.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-group/paper-radio-group.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-radio-group/paper-radio-group.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tooltip/paper-tooltip.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tooltip/paper-tooltip.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-tooltip/paper-tooltip.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/iron-list/iron-list.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/iron-list/iron-list.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /iron-list/iron-list.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/all-imports.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/all-imports.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-item/all-imports.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-button/paper-radio-button.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-button/paper-radio-button.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-radio-button/paper-radio-button.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-item-body.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-item-body.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-item/paper-item-body.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-icon-item.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-item/paper-icon-item.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-item/paper-icon-item.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tooltip/paper-tooltip.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tooltip/paper-tooltip.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-tooltip/paper-tooltip.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-group/paper-radio-group.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-group/paper-radio-group.html
127.0.0.1 - - [12/Oct/2016 16:05:02] "GET /paper-radio-group/paper-radio-group.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-button/paper-radio-button.html' on path /home/jiefeng/anaconda2/lib/python2.7/site-packages/tensorflow/tensorboard/paper-radio-button/paper-radio-button.html

Here is part of the outputs @danmane 
the tensorboard page initially shows nothing, after a while if i reload, it starts to show the data.

**Comment by jart** [comment]
How are you running TensorBoard?

**Comment by bc-lee** [comment]
Same here. I built TF r0.11 from source to make wheel file, and installed by (user level) PIP. (so, `$ whereis tensorboard` returns `/home/leebc/.local/bin/tensorboard`)
When I run tensorboard by `$ tensorboard --logdir=/tmp/tensorboard`, I get these logs:
```
127.0.0.1 - - [13/Oct/2016 09:17:07] "GET / HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js' on path /home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html' on path /home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/external/dist/bazel-html-imports.html' on path /home/leebc/.local/lib/python3.5/site-packages/external/dist/bazel-html-imports.html
127.0.0.1 - - [13/Oct/2016 09:17:07] code 404, message Not Found
127.0.0.1 - - [13/Oct/2016 09:17:07] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2016 09:17:07] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2016 09:17:07] "GET /lib/css/global.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2016 09:17:07] "GET /dist/bazel-html-imports.html HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-checkbox/paper-checkbox.html' on path /home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-checkbox/paper-checkbox.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html' on path /home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-dialog/paper-dialog.html' on path /home/leebc/.local/lib/python3.5/site-packages/tensorflow/tensorboard/paper-dialog/paper-dialog.html
```

**Comment by flyfj** [comment]
@jart just like what @bc-lee did: tensorboard --logdir=/path/to/log

**Comment by asanakoy** [comment]
Same here. A lot of IOErrors and tinsted of graph I see a black rectangle in the browser. 
A lot of html and js files are missing in the tensorboard folder.
Ubuntu 14.04.5 LTS, python 2.7.11
Tensorflow v. 0.11.0rc0 installed from pip.

```
127.0.0.1 - - [13/Oct/2016 15:35:10] "GET / HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js
127.0.0.1 - - [13/Oct/2016 15:35:10] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2016 15:35:10] "GET /lib/css/global.css HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/external/dist/bazel-html-imports.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/external/dist/bazel-html-imports.html
127.0.0.1 - - [13/Oct/2016 15:35:10] code 404, message Not Found
127.0.0.1 - - [13/Oct/2016 15:35:10] "GET /dist/bazel-html-imports.html HTTP/1.1" 404 -
127.0.0.1 - - [13/Oct/2016 15:35:10] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/polymer/polymer.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/polymer/polymer.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-icons/iron-icons.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-icons/iron-icons.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-tabs/paper-tabs.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-dialog/paper-dialog.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-dialog/paper-dialog.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-checkbox/paper-checkbox.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-checkbox/paper-checkbox.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-toolbar/paper-toolbar.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/paper-toolbar/paper-toolbar.html
```

```
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /neon-animation/web-animations.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/neon-animation/animations/opaque-animation.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/neon-animation/animations/opaque-animation.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-fit-behavior/iron-fit-behavior.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-fit-behavior/iron-fit-behavior.html
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /neon-animation/animations/opaque-animation.html HTTP/1.1" 200 -
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /iron-fit-behavior/iron-fit-behavior.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-overlay-behavior/iron-overlay-manager.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-overlay-behavior/iron-overlay-manager.html
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /iron-overlay-behavior/iron-overlay-manager.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-dropdown/iron-dropdown-scroll-manager.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-dropdown/iron-dropdown-scroll-manager.html
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /iron-dropdown/iron-dropdown-scroll-manager.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-overlay-behavior/iron-overlay-backdrop.html' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/iron-overlay-behavior/iron-overlay-backdrop.html
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /iron-overlay-behavior/iron-overlay-backdrop.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/web-animations-js/web-animations-next-lite.min.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/web-animations-js/web-animations-next-lite.min.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /web-animations-js/web-animations-next-lite.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /lodash/lodash.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/d3/d3.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/d3/d3.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /d3/d3.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/plottable/plottable.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/plottable/plottable.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /plottable/plottable.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /lodash/lodash.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js
127.0.0.1 - - [13/Oct/2016 15:35:11] "GET /graphlib/dist/graphlib.core.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/dagre/dist/dagre.core.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/dagre/dist/dagre.core.js
127.0.0.1 - - [13/Oct/2016 15:35:12] "GET /dagre/dist/dagre.core.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/lodash/lodash.min.js
127.0.0.1 - - [13/Oct/2016 15:35:12] "GET /lodash/lodash.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js' on path /export/home/asanakoy/.venvs/tf/local/lib/python2.7/site-packages/tensorflow/tensorboard/graphlib/dist/graphlib.core.js

```

**Comment by dsmilkov** [comment]
Hi,

We just resolved this internally. Should see the fix at master within 1-2 days.

Thanks for letting us know!

**Comment by flyfj** [comment]
@dsmilkov awesome, thanks! will the official binary be updated?

**Comment by dsmilkov** [comment]
Not the current binary, but 0.11 RC1 will have the patch!

**Comment by jkschin** [comment]
@dsmilkov I just installed 0.11 RC1 but the error is still there. When I try to load an 'events.out.tfevents' file, nothing appears on localhost:6006. Tried on Chrome and Firefox, both don't work.

**Comment by flyfj** [comment]
＠jkschin my experience is if you reload the page multiple times, the data will show up regardless of all the warning/error it produces in the command line. Hopefully it can be fixed in the next patch.

**Comment by jkschin** [comment]
@flyfj refreshing the page does not work for me.

**Comment by asanakoy** [comment]
@jkschin Try to use Chromium browser. Didn't work for me in firefox, but works in Chromium.

**Comment by dsmilkov** [comment]
jkschin@ Do you get the same IOErrors just like the other users (logs pasted above)? What browser are you using?

If the issue you are seeing looks unrelated to the issue of TensorBoard producing a lot of IOErrors, feel free to file another issue regarding your problem.

Thanks!

**Comment by jkschin** [comment]
It's not an IOError. Filed new issue here #5341
