### ISSUE TITLE
 TypeError: '>' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by AndrewTheReese** [tensorflow/tensorflow#48300]
System Information

- Running in Google Collab
- Python 3.7
- TensorFlow Version: 2.1.0
- Keras Version: 2.3.0
- Notebook is set to run on GPU
![P1](https://user-images.githubusercontent.com/71000110/113538851-85aa5680-9599-11eb-8dfd-e8075f1d0612.PNG)

When I attempted to run the code above I got this error message:

![P2](https://user-images.githubusercontent.com/71000110/113538936-bee2c680-9599-11eb-8012-a6b2a647d471.PNG)

Any thoughts on how to solve this?

**Comment by Saduf2019** [comment]
@AndrewTheReese 
Please share simple stand alone code such that we can replicate the issue reported or a colab gist with the error, the snapshots shared do not help is searching the issue.
