### ISSUE TITLE
MultiWorkerMirroredStrategy how to use GPU and something about datashard

### ISSUE THREAD

**Issue by Mullich123** [tensorflow/tensorflow#48317]
1.When I used MultiWorkerMirroredStrategy to train my model,it works normally but didn't use GPUs,so I supposed if I omit something about the config of GPUs of the Strategy.
2.I wonder if the Strategy would do datashard automatically for me if I do nothing but just send dataset to 'model.fit' without 
using tf.dataset?

**Comment by amahendrakar** [comment]
@Mullich123,
Please take a look at the 'Multi-worker training with Keras' tutorial which has information regarding both [MultiWorkerMirroredStrategy](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#overview) and [dataset sharding](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#dataset_sharding), and let us know if it helps. Thanks!

**Comment by Mullich123** [comment]
Thanks for your reply.It did a great help.

**Comment by amahendrakar** [comment]
@Mullich123,
Thank you for the update.

Closing this issue as it is resolved. Please feel free to re-open if necessary.
