### ISSUE TITLE
Custom layer failed import message is not clear

### ISSUE THREAD

**Issue by ebursztein** [tensorflow/tensorflow#48312]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 / Linux etc...
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.7
- CUDA/cuDNN version: 11
- GPU model and memory:  RTX 3090

**Describe the current behavior**

Currently when using custom layers, when the import is missing during the reloading the raised `ValueError` says:
```
ValueError: Input tensors to a Similarity>SimilarityModel must come from `tf.keras.Input`. Received: None (missing previous layer metadata).
``

Trace:
```
~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    515     self._self_setattr_tracking = False  # pylint: disable=protected-access
    516     try:
--> 517       result = method(self, *args, **kwargs)
    518     finally:
    519       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\functional.py in __init__(self, inputs, outputs, name, trainable, **kwargs)
    118     generic_utils.validate_kwargs(kwargs, {})
    119     super(Functional, self).__init__(name=name, trainable=trainable)
--> 120     self._init_graph_network(inputs, outputs)
    121 
    122   @trackable.no_automatic_dependency_tracking

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    515     self._self_setattr_tracking = False  # pylint: disable=protected-access
    516     try:
--> 517       result = method(self, *args, **kwargs)
    518     finally:
    519       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\functional.py in _init_graph_network(self, inputs, outputs)
    155         base_layer_utils.create_keras_history(self._nested_outputs)
    156 
--> 157     self._validate_graph_inputs_and_outputs()
    158 
    159     # A Network does not create weights of its own, thus it is already

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\keras\engine\functional.py in _validate_graph_inputs_and_outputs(self)
    689                          'must come from `tf.keras.Input`. '
    690                          'Received: ' + str(x) +
--> 691                          ' (missing previous layer metadata).')
    692       # Check that x is an input tensor.
```

**Describe the expected behavior**

The RaiseError should be more explicit about which layer was not properly imported so it's easier to debug.

**Comment by sachinprasadhs** [comment]
@ebursztein , The error message has been improved in the recent version. Below is the code reference of the improved error message.
https://github.com/keras-team/keras/blob/af88a50a0936b25972aa3959aaee7b2d5da3042a/keras/engine/functional.py#L705-L710
