### ISSUE TITLE
Error validating data cardinality when fitting the model

### ISSUE THREAD

**Issue by andregarcia** [tensorflow/tensorflow#48316]
**System information**
- I am writing code to create models using tensorflow
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version 2.4.1
- Python version: 3.7.4
- CUDA/cuDNN version: not installed
- GPU model and memory: GeForce 940MX (256MB)

System information extracted from tf_env_collect.sh
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/6260387/tf_env.txt)

**Current behavior**
When fitting the model, inputs and outputs are joined in single tuple before calling the function _check_data_cardinality in tensorflow/python/keras/engine/data_adapter.py. Then, inside the _check_data_cardinality function, a flatten method is called for joined x and y. Since input and output are of different dimension, this results in error still inside _check_data_cardinality function. I have tried input and output manipulation to prevent the error, since this could be caused by invalid input and/or output format, but had no success.

**Expected behavior**
Do not throw an error, do not mix dimension validation of input and output together.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1qZG82zYoir92D0cIVZYwihvQJtC_L66O?usp=sharing

**Other info / logs**
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-1-1810d9a9a642> in <module>()
     31 
     32 
---> 33 test_concatenated_neural_network()

4 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _check_data_cardinality(data)
   1527           label, ", ".join(str(i.shape[0]) for i in nest.flatten(single_data)))
   1528     msg += "Make sure all arrays contain the same number of samples."
-> 1529     raise ValueError(msg)
   1530 
   1531 

ValueError: Data cardinality is ambiguous:
  x sizes: 3, 3, 3, 3, 3, 3, 3, 3
  y sizes: 4
Make sure all arrays contain the same number of samples.
```

**Comment by Saduf2019** [comment]
@andregarcia 
After making few changes to the code it works fine, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/ac1f4db217da2280595e54cce9284dc2/untitled583.ipynb) and let us know.

**Comment by andregarcia** [comment]
Thank you very much @Saduf2019, it works.
