### ISSUE TITLE
"A simple graph image" in "Introduction to graphs and tf.function" at TF guides not loading in Safari Browser.

### ISSUE THREAD

**Issue by Suraj1199** [tensorflow/tensorflow#48311]
## URL(s) with the issue:
https://www.tensorflow.org/guide/intro_to_graphs

Link to the documentation entry:
https://github.com/tensorflow/docs/blob/master/site/en/guide/intro_to_graphs.ipynb

## Description of issue (what needs changing):

"A simple graph image" in ["Introduction to graphs and tf.function"](https://www.tensorflow.org/guide/intro_to_graphs) not loading in Safari Browser.

![screenshot](https://github.com/Suraj1199/test/blob/master/File_000.jpeg)

Are you planning to also submit a pull request to fix the issue? 
Yes

**Comment by Suraj1199** [comment]
Here's my PR (https://github.com/tensorflow/docs/pull/1871)

**Comment by Saduf2019** [comment]
This issue will be closed once the pr is merged.

**Comment by lamberta** [comment]
Thanks. The fix is merged and should be reflected on tf.org after the next publishing run

**Comment by Suraj1199** [comment]
Thanks @lamberta for improving my PR. I was going to fix the lints and formatting later today but anyways you did it. @Saduf2019, the [PR](https://github.com/tensorflow/docs/pull/1872) for this issue has been merged, So it can be closed now.

**Comment by Suraj1199** [comment]
yet the problem #48311 is still there.

**Comment by lamberta** [comment]
Looks like the file wasn't imported last night—though the job looks like it ran. cc @yashk2810

**Comment by yashk2810** [comment]
Thanks for flagging. I am looking into it. Looks like there is a 48 hour lag which shouldn't happen.
