### ISSUE TITLE
tensorflow illegal instruction error

### ISSUE THREAD

**Issue by greeshmapremaraj** [tensorflow/tensorflow#48319]
hello,
when importing tensorflow i am getting an illegal instruction error.
mine is new model CPU ,but AVX instruction are missing?What should i do?plz help

**Comment by Saduf2019** [comment]
@greeshmapremaraj 
Could you please create a new virtual environment and check if you are facing the same issue in that as well? [to check your AVx refer to [link](https://stackoverflow.com/questions/37480071/how-to-tell-if-a-linux-machine-supports-avx-avx2-instructions), [link1](https://www.quora.com/How-can-I-determine-if-my-CPU-supports-AVX-instructions#:~:text=If%20it%20doesn't%20trigger,to%20use%20the%20AVX%20version.&text=If%20you're%20using%20Windows,in%20the%20'Instructions'%20box.)

You may refer to these issues as well and let us know: #45744,#46496, [link](https://github.com/tensorflow/tensorflow/issues/47720#issuecomment-797249831)
