### ISSUE TITLE
Output shapes of then and else branches do not match  (s64[1,64]) vs. (s64[64])

### ISSUE THREAD

**Issue by prudhvirajboddu** [tensorflow/tensorflow#48332]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below):2.4
- Python version:3.7.9
- accelerator : TPU
**Describe the current behavior**
Model is not training on TPU but it is on GPU with same code 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
[](https://www.kaggle.com/prudhvi9999/oversampled?scriptVersionId=58909509)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Code that throwing error when running on TPU
`InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-19-c05fea4c2943> in <module>
      1 model.fit(train_ds,epochs=EPOCHS,validation_data=val_ds,
----> 2           steps_per_epoch=TS,validation_steps=VS,callbacks=[lr_scheduler])

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1103               logs = tmp_logs  # No error, now safe to assign to logs.
   1104               end_step = step + data_handler.step_increment
-> 1105               callbacks.on_train_batch_end(end_step, logs)
   1106               if self.stop_training:
   1107                 break

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_train_batch_end(self, batch, logs)
    452     """
    453     if self._should_call_train_batch_hooks:
--> 454       self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
    455 
    456   def on_test_batch_begin(self, batch, logs=None):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
    294       self._call_batch_begin_hook(mode, batch, logs)
    295     elif hook == 'end':
--> 296       self._call_batch_end_hook(mode, batch, logs)
    297     else:
    298       raise ValueError('Unrecognized hook: {}'.format(hook))

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_end_hook(self, mode, batch, logs)
    314       self._batch_times.append(batch_time)
    315 
--> 316     self._call_batch_hook_helper(hook_name, batch, logs)
    317 
    318     if len(self._batch_times) >= self._num_batches_for_timing_check:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook_helper(self, hook_name, batch, logs)
    354       hook = getattr(callback, hook_name)
    355       if getattr(callback, '_supports_tf_logs', False):
--> 356         hook(batch, logs)
    357       else:
    358         if numpy_logs is None:  # Only convert once.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_train_batch_end(self, batch, logs)
   1018 
   1019   def on_train_batch_end(self, batch, logs=None):
-> 1020     self._batch_update_progbar(batch, logs)
   1021 
   1022   def on_test_batch_end(self, batch, logs=None):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in _batch_update_progbar(self, batch, logs)
   1082     if self.verbose == 1:
   1083       # Only block async when verbose = 1.
-> 1084       logs = tf_utils.to_numpy_or_python_type(logs)
   1085       self.progbar.update(self.seen, list(logs.items()), finalize=False)
   1086 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py in to_numpy_or_python_type(tensors)
    512     return t  # Don't turn ragged or sparse tensors to NumPy.
    513 
--> 514   return nest.map_structure(_to_single_numpy_or_python_type, tensors)
    515 
    516 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    657 
    658   return pack_sequence_as(
--> 659       structure[0], [func(*x) for x in entries],
    660       expand_composites=expand_composites)
    661 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    657 
    658   return pack_sequence_as(
--> 659       structure[0], [func(*x) for x in entries],
    660       expand_composites=expand_composites)
    661 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py in _to_single_numpy_or_python_type(t)
    508   def _to_single_numpy_or_python_type(t):
    509     if isinstance(t, ops.Tensor):
--> 510       x = t.numpy()
    511       return x.item() if np.ndim(x) == 0 else x
    512     return t  # Don't turn ragged or sparse tensors to NumPy.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in numpy(self)
   1069     """
   1070     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1071     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1072     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1073 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1037       return self._numpy_internal()
   1038     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1039       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1040 
   1041   @property

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
  (1) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_35]]
  (2) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_11]]
  (3) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_5]]
  (4) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_29]]
  (5) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_47]]
  (6) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_41]]
  (7) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_17]]
  (8) Invalid argument: {{function_node __inference_train_function_103841}} Compilation failure: Output shapes of then and else branches do not match: (s64[1,64]) vs. (s64[64])
	 [[{{node cond}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3]]
	 [[tpu_compile_succeeded_assert/_7380513076206390246/_3/_23]]
0 successful operations.
0 ... [truncated]`

**Comment by amahendrakar** [comment]
@prudhvirajboddu,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and also the dataset you are using. Thanks!
