### ISSUE TITLE
some confuse about tf.shape(x) and x.shape

### ISSUE THREAD

**Issue by Dragon-GCS** [tensorflow/tensorflow#48334]
When I learning the [document](https://tensorflow.google.cn/tutorials/text/transformer) about transformer, I meet some different about tf.shape(x) and x.shape
`tf.version == 2.3.0`
code:

```
class Encoder(tf.keras.layers.Layer): 
    def call(self, x, training, mask):
    ##########  it will raise a error when using x.shape[1]  ##########
        seq_len = tf.shape(x)[1]         
        x = self.embedding(x)
        x *= tf.sqrt(tf.cast(self.d_model, tf.float32))
        x += self.pos_encoding[:, :seq_len, :]
        
        x = self.dropout(x)
        
        for i in range(self.num_layers):
            x = self.enc_layers[i](x, training, mask)

        return x
```
the error when using `x.shape[1]` to replace `tf.shape(x)[1]`:
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [64,38,128] vs. [1,8216,128]
	 [[node transformer_14/encoder_19/add (defined at <ipython-input-104-62f8963562be>:19) ]]
  (1) Invalid argument:  Incompatible shapes: [64,38,128] vs. [1,8216,128]
	 [[node transformer_14/encoder_19/add (defined at <ipython-input-104-62f8963562be>:19) ]]
	 [[gradient_tape/transformer_14/decoder_14/embedding_34/embedding_lookup/Reshape/_466]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_step_1459223]

Errors may have originated from an input operation.
Input Source operations connected to node transformer_14/encoder_19/add:
 transformer_14/encoder_19/mul (defined at <ipython-input-104-62f8963562be>:18)

Input Source operations connected to node transformer_14/encoder_19/add:
 transformer_14/encoder_19/mul (defined at <ipython-input-104-62f8963562be>:18)
```
**it waste a lot of time to find it, who can explain the different betweent them, thanks**

**Comment by Saduf2019** [comment]
@Dragon-GCS 
I ran the code shared on tf nightly and do not see any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b9570f37557f93fb1d4f9b9fb6f73252/untitled583.ipynb).

**Comment by Dragon-GCS** [comment]
> @Dragon-GCS
> I ran the code shared on tf nightly and do not see any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b9570f37557f93fb1d4f9b9fb6f73252/untitled583.ipynb).

The code in my question is not complete，you can see the whole code in this [notebook](https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/text/transformer.ipynb)。It‘s from this [document](https://tensorflow.google.cn/tutorials/text/transformer?hl=zh_cn). You can run all the cell in colab,and you wil find the error in the last cell output. This error occur in the `class Encoder`, when you change `x.shape[1]` to `tf.shape(x)[1]`, this program can run well.

**Comment by Saduf2019** [comment]
@Dragon-GCS 
Please provide me with a colab gist with code that replicated the error.

**Comment by Dragon-GCS** [comment]
Here is the simplified code:
```
import tensorflow as tf

def scaled_dot_product_attention(q, k, v):
  matmul_qk = tf.matmul(q, k, transpose_b=True)
  dk = tf.cast(tf.shape(k)[-1], tf.float32)
  scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)
  attention_weights = tf.nn.softmax(scaled_attention_logits, axis=-1)
  output = tf.matmul(attention_weights, v)
  return output, attention_weights


class TestModel(tf.keras.Model):
  def __init__(self, d_model=128, num_heads=8,input_vocab_size=233,target_vocab_size=666, pe_input=233, pe_target=666):
    super(TestModel, self).__init__()
    self.embedding_inp = tf.keras.layers.Embedding(input_vocab_size, d_model)
    self.embedding_tar = tf.keras.layers.Embedding(target_vocab_size, d_model)
    self.pos_encoding_inp = tf.random.uniform([1,input_vocab_size,d_model])
    self.final_layer = tf.keras.layers.Dense(target_vocab_size)
  
  def call(self, inp, tar):
    ##########      it will raise a error when using inp.shape[1]      ##########
    #####  When use tf.shape or ignore adding self.pos_encoding_inp, it run well  #####
    seq_len = inp.shape[1] # tf.shape(inp)[1]
    inp = self.embedding_inp(inp)
    inp += self.pos_encoding_inp[:, :seq_len, :]

    tar = self.embedding_tar(tar)
    tar, _ = scaled_dot_product_attention(v=inp, k=inp, q=tar)   ## raise error
    out = self.final_layer(tar)
    return out

testmodel = TestModel()

train_step_signature = [tf.TensorSpec(shape=(None, None), dtype=tf.int64),
             tf.TensorSpec(shape=(None, None), dtype=tf.int64)]

optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True, reduction='none')   

@tf.function(input_signature=train_step_signature)
def train_step(inp, tar):
  tar_inp = tar[:, :-1]
  tar_real = tar[:, 1:]
  with tf.GradientTape() as tape:
    predictions = testmodel(inp, tar_inp)
    loss = loss_object(tar_real, predictions)
  gradients = tape.gradient(loss, testmodel.trainable_variables)    
  optimizer.apply_gradients(zip(gradients, testmodel.trainable_variables))
  print('step over')


input = tf.constant(np.random.randint(0, 100,[64,40]),dtype=tf.int64)
target = tf.constant(np.random.randint(0, 100,[64,39]),dtype=tf.int64)
train_step(input, target)
```

**Comment by Saduf2019** [comment]
I m able to replicate this issue on tf 2.3,2.5 and nightly, please find the gist [here](https://colab.research.google.com/gist/Saduf2019/04874623524313e08da482f0764acdcb/untitled589.ipynb) can you please refer to this comment based on [the error](https://github.com/keras-team/keras/issues/11749#issuecomment-804620973) reported.

**Comment by Dragon-GCS** [comment]
I read the link you mentioned, and I think my issue is not same as it. When I debug this error, x.shape and tf.shape(x) will rasie different value. So I think it will be a hidden danger and I mainly want to know why they are different.
BTW, thanks for your patients and replys.

**Comment by jvishnuvardhan** [comment]
@Dragon-GCS I didn't look at your code in detail but the main difference between x.shape (which results in static shape) and tf.shape (which results in dynamic shape) are described [here](https://github.com/tensorflow/tensorflow/issues/35798#issuecomment-574017006). Thanks!
