### ISSUE TITLE
Slow IDCT used in JPEG decode

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#4833]
This issue is related to #4807, yet a bit distinct. Regardless of whether libjpeg or libjpeg-turbo is used, I was wondering if there was a reason to choose the slow but more accurate variant of IDCT in libjpeg ([code link](https://github.com/tensorflow/tensorflow/blob/6b1d4fd8090d44d20fdadabf06f1a9b178c3d80c/tensorflow/core/lib/jpeg/jpeg_mem.cc#L143)). For human image viewing pleasure, accuracy may matter, but I was wondering if for model training, the decision was made to use the slower IDCT because that improved model convergence? In case the training is immune to using the faster but less accurate IDCT, it may be worth changing the default. Has anyone done any studies as to the trained model impact of the faster IDCT? From a performance point of view, I'm getting a significant performance gain (2x GTX 1080, 6-core high-clock Core i7, 500 MB/s SSD), around 20% for AlexNet against precomputed ImageNet AlexNet may be more CPU bound for decode since the network passes themselves are relatively cheap, so maybe the gains for Inception v3 or ResNet would be less, but they would still likely be significant.

**Comment by tatatodd** [comment]
@mkolod Thanks for another interesting point.  These are good areas to investigate wrt runtime performance!

I don't know of any studies of setting JDCT_IFAST, either wrt runtime performance or model accuracy.

As before, @prb12 and @poxvoculi might be interested.

**Comment by prb12** [comment]
Interesting ... when training models for real (i.e. where time-to-accuracy is often more important than step-time), people often deliberately introduce noise and random distortions after decoding the image, so I can't imagine this would hurt!

**Comment by TimZaman** [comment]
Choosing for JPEG is already a choice for lossy compression, so flipping the toggle makes sense.

**Comment by mkolod** [comment]
@TimZaman Indeed.

**Comment by vrv** [comment]
I made the fast IDCT the default in febdc1d13576a28382122e718bc8ab22ba9e6a45
