### ISSUE TITLE
Support for VersionId in s3 file system

### ISSUE THREAD

**Issue by sebastianschramm** [tensorflow/tensorflow#48331]
- TensorFlow version 2.4.1

Support **VersionId** argument in `s3_file_system` operations like reading (currently this is not supported by tensorflow even though it is supported by the underlying aws sdk).

I want to be able to load a model with a specific **VersionId** from a versioned AWS S3-bucket in **tf-serving**.

**Comment by ymodak** [comment]
In the light of https://github.com/tensorflow/tensorflow/issues/48009#issuecomment-805965233 can you please post your issue on [tensorflow/io](https://github.com/tensorflow/io/issues) repo. Thanks!

**Comment by sebastianschramm** [comment]
ok, I opened https://github.com/tensorflow/io/issues/1354#issue-852733649

**Comment by yongtang** [comment]
@sebastianschramm Let's close this issue and keep the conversation on https://github.com/tensorflow/io/issues/1354#issue-852733649
