### ISSUE TITLE
Conv2d gives an error

### ISSUE THREAD

**Issue by rghelichi** [tensorflow/tensorflow#48352]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):  9.3.0
- CUDA/cuDNN version: 11.0 / 11.0.207
- GPU model and memory: GeForce RTX 2060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to run any model with Conv it raises an unexpected error. When I run the same code within an environment without gpu (cpu only) it works properly. 
tf.test.is_gpu_avialable returns True and it seems the gpu is installed properly. Other applications (ray rllib) can run on the gpu with no problem. 

**Describe the expected behavior**
NotFoundError                             Traceback (most recent call last)
<ipython-input-13-4c2161bc3738> in <module>
----> 1 model(pp)

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
   1010         with autocast_variable.enable_auto_cast_variables(
   1011             self._compute_dtype_object):
-> 1012           outputs = call_fn(inputs, *args, **kwargs)
   1013 
   1014         if self._activity_regularizer:

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py in call(self, inputs, training, mask)
    422         a list of tensors if there are more than one outputs.
    423     """
--> 424     return self._run_internal_graph(
    425         inputs, training=training, mask=mask)
    426 

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py in _run_internal_graph(self, inputs, training, mask)
    558 
    559         args, kwargs = node.map_arguments(tensor_dict)
--> 560         outputs = node.layer(*args, **kwargs)
    561 
    562         # Update tensor_dict.

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
   1010         with autocast_variable.enable_auto_cast_variables(
   1011             self._compute_dtype_object):
-> 1012           outputs = call_fn(inputs, *args, **kwargs)
   1013 
   1014         if self._activity_regularizer:

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py in call(self, inputs)
    246       inputs = array_ops.pad(inputs, self._compute_causal_padding(inputs))
    247 
--> 248     outputs = self._convolution_op(inputs, self.kernel)
    249 
    250     if self.use_bias:

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py in convolution_v2(input, filters, strides, padding, data_format, dilations, name)
   1011     dilations=None,
   1012     name=None):
-> 1013   return convolution_internal(
   1014       input,  # pylint: disable=redefined-builtin
   1015       filters,

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py in convolution_internal(input, filters, strides, padding, data_format, dilations, name, call_from_convolution, num_spatial_dims)
   1141         op = conv1d
   1142 
-> 1143       return op(
   1144           input,
   1145           filters,

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py in _conv2d_expanded_batch(input, filters, strides, padding, data_format, dilations, name)
   2595     # We avoid calling squeeze_batch_dims to reduce extra python function
   2596     # call slowdown in eager mode.  This branch doesn't require reshapes.
-> 2597     return gen_nn_ops.conv2d(
   2598         input,
   2599         filter=filters,

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, explicit_paddings, data_format, dilations, name)
    930       return _result
    931     except _core._NotOkStatusException as e:
--> 932       _ops.raise_from_not_ok_status(e, name)
    933     except _core._FallbackException:
    934       pass

~/.virtualenvs/trader/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6860   message = e.message + (" name: " + name if name is not None else "")
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access
   6864 

~/.virtualenvs/trader/lib/python3.8/site-packages/six.py in raise_from(value, from_value)

**Standalone code to reproduce the issue**
# Create the base model from the pre-trained model ResNet50 V2
IMG_SHAPE = (32, 32, 3)
base_model = tf.keras.applications.ResNet50(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')
base_model(sample)

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@rghelichi 

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Thanks!

**Comment by rghelichi** [comment]
here is the sample code:
import tensorflow as tf
 
 sample = tf.random.normal(shape=(32, 32, 3)) 
 model = tf.keras.applications.ResNet50(input_shape=(32, 32, 3), include_top=False)
 print(model(sample[tf.newaxis, ...]))

this runs without gpu but with gpu gives me the error!

**Comment by rghelichi** [comment]
So the problem insisted I found on other issues 
https://github.com/tensorflow/tensorflow/issues/42738
a related error and when I tried one of the other users suggestions it worked

`gpu_devices = tf.config.experimental.list_physical_devices('GPU')
for device in gpu_devices:
    tf.config.experimental.set_memory_growth(device, True)`

what does this code do? is there sth I can do to avoid running these lines each time with my codes?

**Comment by Saduf2019** [comment]
@rghelichi 
Glad the suggestion worked for you,  memory growth enables dynamic allotment of GPU memory, You only need to add these lines if your GPU memory size is falling short, It is not needed otherwise.

Please move this issue to closed status as it answers your question and for any further queries please open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue.
