### ISSUE TITLE
3D NMS

### ISSUE THREAD

**Issue by Luoxiaoyu828** [tensorflow/tensorflow#48359]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tensorflow2.3.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
Does tensorflow currently provide NMS for 3D boxes?
**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**
Can you add an algorithm to non_max_suppression of the 3D frame

**Comment by Saduf2019** [comment]
@Luoxiaoyu828 
Can you please refer to similar issue here and let us know if it helps.
#48070

**Comment by bhack** [comment]
Check NMS in out Tensorflow 3d repository https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/box_ops.py

**Comment by etasnadi** [comment]
> Check NMS in our Tensorflow 3d repository https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/box_ops.py

Hi,

Thanks, it seems that it does the job, however it has a bit different interface that of the 2D version in tf.image as it does not return indices. Is there a proper implementation for the task?

Thanks.
