### ISSUE TITLE
predict_on_batch score from tensorflow 1.15 to tensorflow 2.3

### ISSUE THREAD

**Issue by mdatres** [tensorflow/tensorflow#48358]
Dear all,

I'm facing a strange behavior in keras-retinanet 1.0. I have recently updated retinanet from version 0.5 to version 1.0. I have two classes, one with a validation mAP of 0.87 and the other with a validation mAP of 0.3 both in version 0.5 and 1.0. I have trained retinanet 0.5 on the training set, and, after doing that, I have converted the trained model to an inference model. I have used predict_on_batch (as in examples) to get the predictions on the test set and I have saved them in a csv file. The predictions obtained with version 0.5 contain both classes with a score that goes from 0.2 to 1, as expected. But the predictions obtained using version 1.0 provide the predictions of one class (the one with 0.87 mAP) with a score between 0 and 1, while for the prediction of the other class the score is always below 0.5. I set up the score threshold to 0.5 during training in both cases (version 0.5 and 1.0). I don't understand why in version 1.0 the model seems not to find any object of the second class with a score greater than 0.5. The first version is in Tensorflow 1.15 with Keras 2.2.4 while the second is in Tensorflow 2.3 with Keras 2.4. Can someone help me? Does he function predict_on_batch change from tensorflow 1.15 to Tensorflow 2.3?

Best regards,
mdatres

**Comment by amahendrakar** [comment]
@mdatres,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by mdatres** [comment]
Unfortunately, I can't share the dataset since it is private. I can share to you the link of the model's implementation: `https://github.com/fizyr/keras-retinanet `
I have used the code contained in the Jupiter notebook example/ResNet50RetinaNet.ipynb to obtain the predictions (I have ran predict_on_batch on the test_set using a for loop). Let me know if I can share something else with you. 

Best regards, 
mdatres

**Comment by mdatres** [comment]
In the following .txt file, the code that I used for the prediction is reported. 
[code.txt](https://github.com/tensorflow/tensorflow/files/6276600/code.txt) 

Hope this help. 
Best regards, 

mdatres

**Comment by amahendrakar** [comment]
@mdatres,
On running the code, I am facing an error stating `ModuleNotFoundError: No module named 'read_test_data'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5e81b077e0203cbbbdc7527b244e5120/48358.ipynb). 

Without a reproducible code snippet it would be difficult for us to debug the issue.



> Unfortunately, I can't share the dataset since it is private

In this case, you can provide a dummy dataset and code to reproduce the issue reported here. Alternatively, you can also run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!
