### ISSUE TITLE
tensorflow-lite C++ example label_image failed for oemconfig.so and libhexagon_nn_skel.so

### ISSUE THREAD

**Issue by limdlh** [tensorflow/tensorflow#48357]
I compile tensorflow-lite and the example label_image in tensorflow-lite source code success,
I could run success with delegates of NNAPI, XNNPACK, GPU and also CPU with ADB, but always fail with Hexagon.
The running comand for Hexagon is: ./label_image -m tflite_model_int8.tflite -i grace_hopper.bmp -l labels.txt -j 1
The CMD window only show following message and paused for long time:
INFO: Loaded model tflite_model_int8.tflite
INFO: resolved reporter
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so_

The log of "adb logcat" shows:
04-07 14:52:43.607  3114  3114 I tflite  : Initialized TensorFlow Lite runtime.
04-07 14:52:43.688  3114  3114 V ./label_image: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1732: Successfully opened fastrpc_shell_3
04-07 14:52:43.723  3114  3114 V ./label_image: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1878: Successfully created user PD on domain 3 (attrs 0x0)
04-07 14:52:43.724  3114  3117 V ./label_image: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:277: FastRPC latency thread started for QoS
04-07 14:52:43.728  3114  3115 E ./label_image: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:745:Error 0x2: fopen failed for oemconfig.so. (No such file or directory)
04-07 14:52:43.729  3114  3115 E ./label_image: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:745:Error 0x2: fopen failed for libhexagon_nn_skel.so. (No such file or directory)
04-07 14:52:44.363   887  1096 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
04-07 14:52:46.371  1431  1431 E         : [eebbk_backup_restore]  get host by name error retry times: 245s!
04-07 14:52:47.503  1433  1635 D BES     : AEEIOCTL_RT_MON_Kick IOCTL,cmd= 2147774474, lParam=300. 

I did copy an empty file "oemconfig.so" to the path of my executeable file label_image.
And also I did download 3 different shared libraries “libhexagon_nn_skel.so”, “libhexagon_nn_skel_v65.so”, “libhexagon_nn_skel_v66.so” by hexagon_nn_skel.run and copy to the path of my executeable file label_image.
Should I copy "oemconfig.so" and “libhexagon_nn_skel.so” to other path?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: BBK S5d (Chinese made pad for kid learning)
- TensorFlow installed from (source or binary): build by myself
- TensorFlow version (use command below): tensorflow-2.4.1
- Python version: Python 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CUDA/cuDNN version:
- GPU model and memory:

Could anyone help? Or give a advice?
Thank you so much~

**Comment by karimnosseir** [comment]
You don't need to copy oemconfig.so.

The error is here 
```
intf/adsprpc/src/apps_std_imp.c:745:Error 0x2: fopen failed for libhexagon_nn_skel.so. (No such file or directory)
```

This means you're not pushing the files to the correct location.
To run label_image example, you need to push the files to "/data/local/tmp"

**Comment by karimnosseir** [comment]
Closing. Please reopen or create new issue if you still have questions.

Thanks
