### ISSUE TITLE
Convert a model trained with TensorFlow1, and convert the model to TFLite with TensorFlow 2 

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#48355]
Hi,

If the model is trained in TensorFlow1, is it possible to convert it to TensorFlow Lite model with the tool version 2.3.1 and be parsed with TFLite delegate parser?

**Comment by amahendrakar** [comment]
@Rahn80643,
It is generally preferred to use the same TensorFlow version while building a model and converting it to `.tflite` format. Using different TensorFlow version for converting the model may result in unexpected behavior.

Hope this answers your query. Thanks!

**Comment by Rahn80643** [comment]
@amahendrakar 
Thanks for your reply, I'm planning to modify my TensorFlow1 project to TensorFlow2.
