### ISSUE TITLE
Gradients are all None in GradientTape

### ISSUE THREAD

**Issue by Maximevdm** [tensorflow/tensorflow#48369]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 10.15.4

- TensorFlow installed from (source or binary): 2.4.1 from binary
- TensorFlow version (use command below):pip install tf 
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 1.6ghz i5, 8gb ddr3

**Describe the current behavior**
We get the error that no gradients have been found for the variable in our model. When printing the intermittent results, we see that all the gradients are none.
**Describe the expected behavior**
We expected gradients to be not none

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
`import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import time
from Retrieve_data import retrieve_data
from sklearn.model_selection import train_test_split
from Model import model_P
import keras as K
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Embedding
from keras.layers import Bidirectional
from keras.layers import Attention
from keras.layers import Concatenate
from keras.layers import TimeDistributed
from keras.layers import Reshape
from keras_self_attention import SeqSelfAttention
from tensorflow import keras

# Prepare the training dataset.
base_directory = '/Users/Desktop/Companies/'
X_pricing, Y_pricing, X_reports = retrieve_data(base_directory, 'ADP')
X_reports_train, X_reports_test, X_pricing_train, X_pricing_test, Y_train, Y_test = train_test_split(X_reports, X_pricing, Y_pricing, test_size=0.50, shuffle=False)

param_grid = {
    'batch_size': 64,
    'epochs': 50,
    'embedding_dimensions': 64,
    'units_LSTM_1': 128,
    'units_LSTM_2': 128,
    'units_BiLSTM_1': 128,
    'units_BiLSTM_2': 128,
    'units_Dense': 128,
    'optimizer': ['ADAM'],
    'loss': 'MeanSquaredError',
    'activation_LSTM_1': 'softsign',
    'activation_LSTM_2': 'softsign',
    'activation_BiLSTM_1': 'softsign',
    'activation_BiLSTM_2': 'softsign',
    'dropout_LSTM_1': 0.5,
    'dropout_LSTM_2': 0.5,
    'dropout_BiLSTM_1': 0.5,
    'dropout_BiLSTM_2': 0.5,
    'metrics': 'mse',
    'learning_rate': 0.000001
}

input_layer = K.Input(shape=(X_pricing.shape[1], X_pricing.shape[2]), batch_size=param_grid['batch_size'])

# Defining the Bidirectional LSTM Layer for Pricing
BiLSTM_pricing = Bidirectional(LSTM(units=param_grid['units_LSTM_1'], return_sequences=True, activation='softsign', dropout=param_grid['dropout_BiLSTM_1']))(input_layer)

    # Defining the Attention Layer for the Pricing
attention_pricing = SeqSelfAttention(attention_activation='softsign')(BiLSTM_pricing)

    # Adding Output Layer
output_layer = Dense(units=param_grid['units_Dense'], activation='relu')(attention_pricing)

    # Building Model

PricingModel = K.Model(inputs=input_layer, outputs=output_layer, name="PricingModel")

# Instantiate an optimizer to train the model.
optimizer = keras.optimizers.SGD(learning_rate=1e-3)
# Instantiate a loss function.
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Prepare the metrics.
train_acc_metric = keras.metrics.SparseCategoricalAccuracy()
val_acc_metric = keras.metrics.SparseCategoricalAccuracy()

x_train = X_pricing_train
x_test = X_pricing_test
y_train = Y_train
y_test = Y_test

print(x_train.shape)
print(y_train.shape)

print(len(x_train))
# Prepare the training dataset.
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(param_grid['batch_size'])

epochs = 1
for epoch in range(epochs):
    print("\nStart of epoch %d" % (epoch,))
    start_time = time.time()

    # Iterate over the batches of the dataset.
    for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
        with tf.GradientTape() as tape:

            logits = PricingModel(x_batch_train, training=True)
            logits = np.reshape(logits, (-1, (logits.shape[2]*logits.shape[1])))
            print(logits)
            print(logits.shape)
            loss_value = loss_fn(y_batch_train, logits)
            print(loss_value)
        tape.watch(loss_value)
        grads = tape.gradient(loss_value, PricingModel.trainable_weights)
        #print(PricingModel.trainable_weights)
        #print(len(PricingModel.trainable_weights))
        print(grads)
        optimizer.apply_gradients(zip(grads, PricingModel.trainable_weights))

        # Update training metric.
        train_acc_metric.update_state(y_batch_train, logits)

        # Log every 200 batches.
        if step % 200 == 0:
            print(
                "Training loss (for one batch) at step %d: %.4f"
                % (step, float(loss_value))
            )
            print("Seen so far: %d samples" % ((step + 1) * param_grid['batch_size']))

    # Display metrics at the end of each epoch.
    train_acc = train_acc_metric.result()
    print("Training acc over epoch: %.4f" % (float(train_acc),))

    # Reset training metrics at the end of each epoch
    train_acc_metric.reset_states()

`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The code produces the following error:
ValueError: No gradients provided for any variable: ['bidirectional/forward_lstm/lstm_cell_1/kernel:0', 'bidirectional/forward_lstm/lstm_cell_1/recurrent_kernel:0', 'bidirectional/forward_lstm/lstm_cell_1/bias:0', 'bidirectional/backward_lstm/lstm_cell_2/kernel:0', 'bidirectional/backward_lstm/lstm_cell_2/recurrent_kernel:0', 'bidirectional/backward_lstm/lstm_cell_2/bias:0', 'seq_self_attention/seq_self_attention_Add_Wt:0', 'seq_self_attention/seq_self_attention_Add_Wx:0', 'seq_self_attention/seq_self_attention_Add_bh:0', 'seq_self_attention/seq_self_attention_Add_Wa:0', 'seq_self_attention/seq_self_attention_Add_ba:0', 'dense/kernel:0', 'dense/bias:0'].

**Comment by tilakrayal** [comment]
@Maximevdm ,

On running the given code, I am facing an error stating **ModuleNotFoundError: No module named 'Retrieve_data'**. Please find the [gist](https://colab.research.google.com/gist/tilakrayal/6d776a58b332d314f79ca77b49f058e0/48369-2-4.ipynb) of it here and share all dependencies to replicate the issue or share a colab gist with the reported error.

Thanks!
