### ISSUE TITLE
ZeroMQ Operator

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#4836]
Currently (it seems like) the encouraged way to read data is either through the provided reader/producer ops which are not quite flexible, or through python feed_dict which is slower.

Is there a plan to support something like a ZeroMQReaderOp, which keeps reading and deserializing tensors from a zmq socket and produce them? This way we can use any comfortable way to process data perhaps in an independent process, and send them through zmq for training.

**Comment by tatatodd** [comment]
@ppwwyyxx Are you referring to http://zeromq.org/ or something else?

Can you provide more details on the deficiencies of the reader/producer ops?  Thanks!

**Comment by ppwwyyxx** [comment]
Yes, it is one of the most widely used messaging library.
I think the existing reader ops basically all assume that data eventually comes from file system - please correct me if I'm wrong about this. 
If data is actually generated on the fly in training, we cannot use reader ops and have to use feed_dict.

**Comment by tatatodd** [comment]
@ppwwyyxx I see.

It is true that most of the provided subclasses of [tf.ReaderBase](https://www.tensorflow.org/versions/r0.11/api_docs/python/io_ops.html#ReaderBase) deal with reading data from the filesystem.  However note that the trivial [tf.IdentityReader](https://www.tensorflow.org/versions/r0.11/api_docs/python/io_ops.html#IdentityReader) is an example of a non-filesystem implementation.

A natural way to add support for other data sources is to implement a subclass of `tf.ReaderBase` for that data source.  This is a simple way extend TensorFlow to support arbitrary messaging / pubsub / raw socket layers.

We welcome contributions!

**Comment by suiyuan2009** [comment]
I'd like to give a help.

**Comment by girving** [comment]
@mrry Is this done?

**Comment by mrry** [comment]
We decided not to add the 0MQ dependency in the discussion thread on #8728. @vrv made the great suggestion that extensions like this should be developed as `tf.load_op_library()` dynamic dependencies first, in which case there's no need to add it to the mainline repository.

**Comment by PatWie** [comment]
FYI:
https://github.com/PatWie/tf_zmq
