### ISSUE TITLE
LSTM layer not possible with channels_first

### ISSUE THREAD

**Issue by JeffreyWardman** [tensorflow/tensorflow#48364]
The following:
```
tf.keras.backend.set_image_data_format("channels_first")
tf.keras.layers.LSTM(units=256)(x)
```
Returns:
```ValueError: Shape must be at least rank 3 but is rank 2 for '{{node lstm/lstm_cell_1/BiasAdd}} = BiasAdd[T=DT_HALF, data_format="NCHW"](lstm/lstm_cell_1/MatMul, lstm/lstm_cell_1/split_1)' with input shapes: [?,256], [256].```

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- CUDA/cuDNN version: 11.1
- GPU model and memory: NVIDIA V100

**Comment by JeffreyWardman** [comment]
#38942

**Comment by Saduf2019** [comment]
@JeffreyWardman 
I ran the code shared but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/bafddf15f69ea5591a6d5a5b1d9e87f1/untitled583.ipynb) and share all dependencies such that we can replicate the issue reported .

**Comment by JeffreyWardman** [comment]
@Saduf2019 `x` can be anything

**Comment by Saduf2019** [comment]
@JeffreyWardman
please share a colab gist with the issue reported.

**Comment by JeffreyWardman** [comment]
@Saduf2019 see this [gist](https://colab.research.google.com/gist/JeffreyWardman/b61f01c52c433b7dbfc60babcb82ea31/untitled583.ipynb#scrollTo=npnrkMQiPkLzl)

**Comment by Saduf2019** [comment]
@JeffreyWardman 

The error in the gist is self explanatory, Your input layer is incorrect, please refer tot his [link](https://machinelearningmastery.com/reshape-input-data-long-short-term-memory-networks-keras/#:~:text=Tips%20for%20LSTM%20Input,-This%20section%20lists&text=The%20LSTM%20input%20layer%20must,on%20the%20first%20hidden%20layer.) for the correct input shape.


You may refer to this working example to [fix your code](https://keras.io/api/layers/recurrent_layers/lstm/)

For any further queries please create a [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue as this is not a bug or a performance issue and there is a big community to support and learn from your questions.

**Comment by JeffreyWardman** [comment]
@Saduf2019 could you please provide a working gist that works with channels first? That way there is evidence of it working.

**Comment by Saduf2019** [comment]
@JeffreyWardman 
Please find your code modified [here](https://colab.research.google.com/gist/Saduf2019/fb9b8e9c34562dc63e0746ae2b1ca3ea/untitled589.ipynb) for any further queries kindly open a stackoverflow issue.

**Comment by Hemanthkumar2112** [comment]
> @JeffreyWardman
> I ran the code shared but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/bafddf15f69ea5591a6d5a5b1d9e87f1/untitled583.ipynb) and share all dependencies such that we can replicate the issue reported .

i have done some changes with the gist

**Comment by d0m3nik** [comment]
Please reopen this issue. This problem remains with tensorflow version 2.4 and 2.5.

The following works:

```python
import tensorflow as tf

tf.keras.backend.set_image_data_format("channels_last")
x = tf.zeros((15, 256))
print(x.shape)
x = tf.keras.layers.Input(shape=x.shape)
x = tf.keras.layers.LSTM(units=32)(x)
```

this **does not** work:

```python
import tensorflow as tf

tf.keras.backend.set_image_data_format("channels_first")
x = tf.zeros((15, 256))
print(x.shape)
x = tf.keras.layers.Input(shape=x.shape)
x = tf.keras.layers.LSTM(units=32)(x)
```

According to documentation for keras.layers.LSTM:

https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM

the default input has to have shape (batch_dim, timesteps, features).

This is the case in both examples, with timesteps = 15 and features = 256.

It is unclear why the LSTM layer should be affected by the "channels_first" or "channels_last" setting.

**Comment by d0m3nik** [comment]
This seems to be related to how biases are implemented within the LSTM layer as the following example works as well:

```python
import tensorflow as tf

tf.keras.backend.set_image_data_format("channels_first")
x = tf.zeros((15, 256))
print(x.shape)
x = tf.keras.layers.Input(shape=x.shape)
x = tf.keras.layers.LSTM(units=32, use_bias=False)(x)
```
