### ISSUE TITLE
While converting from HLO to linalg the conversion of mhlo.convolution(contains padding ) -> linalg.conv fails  with error "non-zero padding unsupported yet" 

### ISSUE THREAD

**Issue by dinkdeep** [tensorflow/tensorflow#48362]
While converting from HLO to linalg the conversion of mhlo.convolution(contains padding ) -> linalg.conv fails 
with error "non-zero padding unsupported yet"  
 
 "mhlo.convolution"(%510, %532) {batch_group_count =  1 : i64, dimension_numbers =  {input_batch_dimension =  0 : i64, input_feature_dimension =  3 : i64, input_spatial_dimensions =  dense<[1, 2]> : tensor<2xi64>, kernel_input_feature_dimension =  2 : i64, kernel_output_feature_dimension =  3 : i64, kernel_spatial_dimensions =  dense<[0, 1]> : tensor<2xi64>, output_batch_dimension =  0 : i64, output_feature_dimension =  3 : i64, output_spatial_dimensions =  dense<[1, 2]> : tensor<2xi64>}, feature_group_count =  1 : i64, padding =  dense<1> : tensor<2x2xi64>, rhs_dilation =  dense<1> : tensor<2xi64>, window_strides =  dense<1> : tensor<2xi64>} : (tensor<4x56x56x64xf32>, tensor<3x3x64x64xf32>) -> tensor<4x56x56x64xf32>

The documentation @ https://mlir.llvm.org/docs/Dialects/Linalg/#linalgpad_tensor-mlirlinalgpadtensorop
for linalg.conv (::mlir::linalg::ConvOp) seems to contain attribute 
padding | ::mlir::DenseIntElementsAttr | 64-bit signless integer elements attribute
 
Is the padding support missing in linalg.conv as of now and is due for implementation if so when could it be added.

**Comment by amahendrakar** [comment]
@dinkdeep,
Could you please provide the 
- TensorFlow version
- minimal code snippet to reproduce the error
- and the exact sequence of commands / steps that you executed before running into the error

Thanks!
