### ISSUE TITLE
MultiWorkerMirroredStrategy looks a lot slower than non-distributed

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [tensorflow/tensorflow#48374]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I'm using code from here: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras (MNIST example) with small alterations, see below for the code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Amazon linux - 4.14.225-168.357.amzn2.x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Not applicable
- TensorFlow installed from (source or binary):
Version 2.4.1 installed using `pip3 install --user tensorflow==2.4.1`
- TensorFlow version (use command below):
```
$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2021-04-07 15:52:47.046112: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
v2.4.0-49-g85c8b2a817f 2.4.1
```
- Python version:
3.7.9
- Bazel version (if compiling from source):
Not applicable
- GCC/Compiler version (if compiling from source):
Not applicable
- CUDA/cuDNN version:
Looks like CUDA 11
- GPU model and memory:
Not applicable

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
On a single m5.large node in AWS training with the MNIST model takes 1m 48s. With 3 machines of that type and MultiWorkerMirroredStrategy in place, it takes 4 mins 30 seconds.

**Describe the expected behavior**
The expected behavior would be that the multi-worker execution is much faster than the single-node. The point of using a multi-worker distributed capability is to allow for a much faster, scalable processing (model training).

**Standalone code to reproduce the issue**
**Non-distributed**
```
import json
import os
import sys
import time
import numpy as np
import tensorflow as tf

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
if "." not in sys.path:
    sys.path.insert(0, ".")

def mnist_dataset(batch_size):
    (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
    # The `x` arrays are in uint8 and have values in the range [0, 255].
    # You need to convert them to float32 with values in the range [0, 1]
    x_train = x_train / np.float32(255)
    y_train = y_train.astype(np.int64)
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
    return train_dataset

def build_and_compile_cnn_model():
    model = tf.keras.Sequential(
        [
            tf.keras.Input(shape=(28, 28)),
            tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
            tf.keras.layers.Conv2D(32, 3, activation="relu"),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(128, activation="relu"),
            tf.keras.layers.Dense(10),
        ]
    )
    model.compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
        metrics=["accuracy"],
    )
    return model

start_time = time.time()
global_batch_size = 64
multi_worker_dataset = mnist_dataset(global_batch_size)
multi_worker_model = build_and_compile_cnn_model()
multi_worker_model.fit(multi_worker_dataset, epochs=50, steps_per_epoch=70)
elapsed_time = time.time() - start_time
str_elapsed_time = time.strftime("%H : %M : %S", time.gmtime(elapsed_time))
print(">> Finished. Time elapsed: {}.".format(str_elapsed_time))
```
**Distributed:**
```
import json
import os
import sys
import time
import numpy as np
import tensorflow as tf

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
if "." not in sys.path:
    sys.path.insert(0, ".")

def mnist_dataset(batch_size):
    (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
    # The `x` arrays are in uint8 and have values in the range [0, 255].
    # You need to convert them to float32 with values in the range [0, 1]
    x_train = x_train / np.float32(255)
    y_train = y_train.astype(np.int64)
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
    return train_dataset

def build_and_compile_cnn_model():
    model = tf.keras.Sequential(
        [
            tf.keras.Input(shape=(28, 28)),
            tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
            tf.keras.layers.Conv2D(32, 3, activation="relu"),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(128, activation="relu"),
            tf.keras.layers.Dense(10),
        ]
    )
    model.compile(
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
        metrics=["accuracy"],
    )
    return model

start_time = time.time()

per_worker_batch_size = 64
tf_config = json.loads(os.environ["TF_CONFIG"])
num_workers = len(tf_config["cluster"]["worker"])

strategy = tf.distribute.MultiWorkerMirroredStrategy()
global_batch_size = 64
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
multi_worker_dataset = mnist_dataset(global_batch_size)
multi_worker_dataset_with_shrd = multi_worker_dataset.with_options(options)

with strategy.scope():
    # Model building/compiling need to be within `strategy.scope()`.
    multi_worker_model = build_and_compile_cnn_model()
multi_worker_model.fit(multi_worker_dataset_with_shrd, epochs=50, steps_per_epoch=70)
elapsed_time = time.time() - start_time
str_elapsed_time = time.strftime("%H : %M : %S", time.gmtime(elapsed_time))
print(">> Finished. Time elapsed: {}.".format(str_elapsed_time))
```

**Other info / logs** Include any logs or source code that would be helpful to
**Non-distributed run log:**
```
2021-04-07 15:29:39.627372: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-07 15:29:41.291031: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-07 15:29:41.292029: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-07 15:29:41.371907: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-07 15:29:41.371985: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-10-2-249-213.awsinternal.audiomack.com): /proc/driver/nvidia/version does not exist
2021-04-07 15:29:41.372562: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-07 15:29:41.372737: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Epoch 1/50
2021-04-07 15:29:42.005401: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-04-07 15:29:42.006824: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2500000000 Hz
70/70 [==============================] - 3s 32ms/step - loss: 2.2895 - accuracy: 0.1377
Epoch 2/50
70/70 [==============================] - 2s 30ms/step - loss: 2.2368 - accuracy: 0.3166
Epoch 3/50
70/70 [==============================] - 2s 29ms/step - loss: 2.1805 - accuracy: 0.4483
Epoch 4/50
70/70 [==============================] - 2s 31ms/step - loss: 2.1005 - accuracy: 0.5943
Epoch 5/50
70/70 [==============================] - 2s 30ms/step - loss: 2.0082 - accuracy: 0.6545
Epoch 6/50
70/70 [==============================] - 2s 31ms/step - loss: 1.8875 - accuracy: 0.6937
Epoch 7/50
70/70 [==============================] - 2s 30ms/step - loss: 1.7216 - accuracy: 0.7262
Epoch 8/50
70/70 [==============================] - 2s 30ms/step - loss: 1.5662 - accuracy: 0.7549
Epoch 9/50
70/70 [==============================] - 2s 31ms/step - loss: 1.3967 - accuracy: 0.7727
Epoch 10/50
70/70 [==============================] - 2s 31ms/step - loss: 1.2423 - accuracy: 0.7823
Epoch 11/50
70/70 [==============================] - 2s 31ms/step - loss: 1.0856 - accuracy: 0.8145
Epoch 12/50
70/70 [==============================] - 2s 31ms/step - loss: 0.9729 - accuracy: 0.8060
Epoch 13/50
70/70 [==============================] - 2s 30ms/step - loss: 0.8768 - accuracy: 0.8278
Epoch 14/50
70/70 [==============================] - 2s 30ms/step - loss: 0.7688 - accuracy: 0.8481
Epoch 15/50
70/70 [==============================] - 2s 31ms/step - loss: 0.7315 - accuracy: 0.8442
Epoch 16/50
70/70 [==============================] - 2s 29ms/step - loss: 0.6648 - accuracy: 0.8584
Epoch 17/50
70/70 [==============================] - 2s 30ms/step - loss: 0.6287 - accuracy: 0.8635
Epoch 18/50
70/70 [==============================] - 2s 30ms/step - loss: 0.6144 - accuracy: 0.8416
Epoch 19/50
70/70 [==============================] - 2s 31ms/step - loss: 0.5623 - accuracy: 0.8624
Epoch 20/50
70/70 [==============================] - 2s 31ms/step - loss: 0.5672 - accuracy: 0.8665
Epoch 21/50
70/70 [==============================] - 2s 31ms/step - loss: 0.5544 - accuracy: 0.8607
Epoch 22/50
70/70 [==============================] - 2s 31ms/step - loss: 0.5045 - accuracy: 0.8795
Epoch 23/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4929 - accuracy: 0.8729
Epoch 24/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4719 - accuracy: 0.8756
Epoch 25/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4753 - accuracy: 0.8746
Epoch 26/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4741 - accuracy: 0.8728
Epoch 27/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4696 - accuracy: 0.8760
Epoch 28/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4531 - accuracy: 0.8835
Epoch 29/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4407 - accuracy: 0.8855
Epoch 30/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4087 - accuracy: 0.8910
Epoch 31/50
70/70 [==============================] - 2s 30ms/step - loss: 0.4413 - accuracy: 0.8808
Epoch 32/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4110 - accuracy: 0.8839
Epoch 33/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4152 - accuracy: 0.8959
Epoch 34/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4159 - accuracy: 0.8870
Epoch 35/50
70/70 [==============================] - 2s 30ms/step - loss: 0.4061 - accuracy: 0.8767
Epoch 36/50
70/70 [==============================] - 2s 31ms/step - loss: 0.4077 - accuracy: 0.8890
Epoch 37/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3841 - accuracy: 0.8951
Epoch 38/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3976 - accuracy: 0.8895
Epoch 39/50
70/70 [==============================] - 2s 30ms/step - loss: 0.3873 - accuracy: 0.8968
Epoch 40/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3711 - accuracy: 0.8943
Epoch 41/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3778 - accuracy: 0.8906
Epoch 42/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3692 - accuracy: 0.9022
Epoch 43/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3809 - accuracy: 0.8925
Epoch 44/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3921 - accuracy: 0.8910
Epoch 45/50
70/70 [==============================] - 2s 30ms/step - loss: 0.3620 - accuracy: 0.9006
Epoch 46/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3519 - accuracy: 0.9026
Epoch 47/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3732 - accuracy: 0.9030
Epoch 48/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3670 - accuracy: 0.8874
Epoch 49/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3756 - accuracy: 0.8920
Epoch 50/50
70/70 [==============================] - 2s 31ms/step - loss: 0.3572 - accuracy: 0.8954
>> Finished. Time elapsed: 00 : 01 : 48.
```
**Logs from the distributed run:**
```
2021-04-07 15:33:57.473623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-07 15:33:58.819768: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-07 15:33:58.820710: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-07 15:33:58.893993: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-07 15:33:58.894042: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-10-2-249-213.awsinternal.audiomack.com): /proc/driver/nvidia/version does not exist
2021-04-07 15:33:58.895043: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-07 15:33:58.895208: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-07 15:33:58.895622: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-07 15:33:58.899579: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.2.249.213:2121, 1 -> 10.2.252.56:2121, 2 -> 10.2.252.97:2121}
2021-04-07 15:33:58.899839: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://10.2.249.213:2121
2021-04-07 15:34:04.181014: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-04-07 15:34:04.200033: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2500000000 Hz
Epoch 1/50
70/70 [==============================] - 9s 85ms/step - loss: 2.2927 - accuracy: 0.1324
Epoch 2/50
70/70 [==============================] - 5s 77ms/step - loss: 2.2476 - accuracy: 0.2718
Epoch 3/50
70/70 [==============================] - 5s 74ms/step - loss: 2.1945 - accuracy: 0.4580
Epoch 4/50
70/70 [==============================] - 5s 74ms/step - loss: 2.1318 - accuracy: 0.5667
Epoch 5/50
70/70 [==============================] - 5s 74ms/step - loss: 2.0503 - accuracy: 0.6541
Epoch 6/50
70/70 [==============================] - 5s 75ms/step - loss: 1.9535 - accuracy: 0.6747
Epoch 7/50
70/70 [==============================] - 5s 77ms/step - loss: 1.8103 - accuracy: 0.7182
Epoch 8/50
70/70 [==============================] - 5s 77ms/step - loss: 1.6723 - accuracy: 0.7167
Epoch 9/50
70/70 [==============================] - 6s 79ms/step - loss: 1.5215 - accuracy: 0.7448
Epoch 10/50
70/70 [==============================] - 6s 79ms/step - loss: 1.3525 - accuracy: 0.7807
Epoch 11/50
70/70 [==============================] - 5s 78ms/step - loss: 1.2328 - accuracy: 0.7737
Epoch 12/50
70/70 [==============================] - 5s 76ms/step - loss: 1.1053 - accuracy: 0.7949
Epoch 13/50
70/70 [==============================] - 5s 74ms/step - loss: 0.9806 - accuracy: 0.8146
Epoch 14/50
70/70 [==============================] - 5s 75ms/step - loss: 0.8712 - accuracy: 0.8216
Epoch 15/50
70/70 [==============================] - 5s 75ms/step - loss: 0.8108 - accuracy: 0.8377
Epoch 16/50
70/70 [==============================] - 5s 75ms/step - loss: 0.7336 - accuracy: 0.8502
Epoch 17/50
70/70 [==============================] - 5s 75ms/step - loss: 0.6911 - accuracy: 0.8486
Epoch 18/50
70/70 [==============================] - 5s 74ms/step - loss: 0.6502 - accuracy: 0.8593
Epoch 19/50
70/70 [==============================] - 5s 75ms/step - loss: 0.6725 - accuracy: 0.8402
Epoch 20/50
70/70 [==============================] - 5s 74ms/step - loss: 0.5815 - accuracy: 0.8741
Epoch 21/50
70/70 [==============================] - 5s 75ms/step - loss: 0.5819 - accuracy: 0.8524
Epoch 22/50
70/70 [==============================] - 5s 75ms/step - loss: 0.5522 - accuracy: 0.8588
Epoch 23/50
70/70 [==============================] - 5s 75ms/step - loss: 0.4860 - accuracy: 0.8780
Epoch 24/50
70/70 [==============================] - 5s 75ms/step - loss: 0.5223 - accuracy: 0.8645
Epoch 25/50
70/70 [==============================] - 5s 74ms/step - loss: 0.5226 - accuracy: 0.8651
Epoch 26/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4903 - accuracy: 0.8724
Epoch 27/50
70/70 [==============================] - 5s 75ms/step - loss: 0.5156 - accuracy: 0.8642
Epoch 28/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4501 - accuracy: 0.8855
Epoch 29/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4403 - accuracy: 0.8916
Epoch 30/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4491 - accuracy: 0.8890
Epoch 31/50
70/70 [==============================] - 5s 77ms/step - loss: 0.4170 - accuracy: 0.8920
Epoch 32/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4621 - accuracy: 0.8793
Epoch 33/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4379 - accuracy: 0.8799
Epoch 34/50
70/70 [==============================] - 5s 75ms/step - loss: 0.4217 - accuracy: 0.8864
Epoch 35/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4094 - accuracy: 0.8932
Epoch 36/50
70/70 [==============================] - 5s 75ms/step - loss: 0.4042 - accuracy: 0.8941
Epoch 37/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4123 - accuracy: 0.8895
Epoch 38/50
70/70 [==============================] - 5s 76ms/step - loss: 0.3895 - accuracy: 0.9001
Epoch 39/50
70/70 [==============================] - 5s 77ms/step - loss: 0.4069 - accuracy: 0.8939
Epoch 40/50
70/70 [==============================] - 5s 75ms/step - loss: 0.3772 - accuracy: 0.8923
Epoch 41/50
70/70 [==============================] - 5s 77ms/step - loss: 0.4016 - accuracy: 0.8863
Epoch 42/50
70/70 [==============================] - 5s 76ms/step - loss: 0.3842 - accuracy: 0.9015
Epoch 43/50
70/70 [==============================] - 5s 75ms/step - loss: 0.4055 - accuracy: 0.8925
Epoch 44/50
70/70 [==============================] - 5s 76ms/step - loss: 0.3969 - accuracy: 0.8927
Epoch 45/50
70/70 [==============================] - 5s 76ms/step - loss: 0.3609 - accuracy: 0.8984
Epoch 46/50
70/70 [==============================] - 5s 76ms/step - loss: 0.4033 - accuracy: 0.8918
Epoch 47/50
70/70 [==============================] - 5s 76ms/step - loss: 0.3661 - accuracy: 0.8934
Epoch 48/50
70/70 [==============================] - 5s 75ms/step - loss: 0.3691 - accuracy: 0.8995
Epoch 49/50
70/70 [==============================] - 5s 77ms/step - loss: 0.3702 - accuracy: 0.8982
Epoch 50/50
70/70 [==============================] - 5s 78ms/step - loss: 0.3697 - accuracy: 0.8991
>> Finished. Time elapsed: 00 : 04 : 34.
```
**Other info**
`TF_CONFIG` is set in the environment of all 3 machines, as follows:
```
{"cluster": {"worker": ["xxx:2121", "yyy:2121", "zzz:2121"]}, "task": {"type": "worker", "index": 0}}
{"cluster": {"worker": ["xxx:2121", "yyy:2121", "zzz:2121"]}, "task": {"type": "worker", "index": 1}}
{"cluster": {"worker": ["xxx:2121", "yyy:2121", "zzz:2121"]}, "task": {"type": "worker", "index": 2}}
```

**Comment by nikitamaia** [comment]
Hi @dgoldenberg-audiomack, I don't think this finding is too surprising. There is always some amount of overhead associated with distributed training. If you're using `MirroredStrategy` then there is overhead at the end of each step to synchronize the gradients across replicas. That overhead is larger in the case of `MultiWorkerMirroredStrategy` as the gradients have to be synchronized across the replicas on a machine and then across all machines in a cluster.  The key is to make sure that the host successfully keeps the worker devices occupied by offloading enough work. For a small MNIST model and dataset, the overhead of `MultiWorkerMirroredStrategy` might not be worth it.

Something else to keep in mind is that as you add more replicas, you need to scale your batch size,  as this allows for higher device utilization and amortize the costs of communication across multiple GPUs. The benefit of synchronous distributed training strategies is that you're able to process more data on a single step, and thus each epoch takes less time (Also, personally I would recommend not explicitly `setting steps_per_epoch` unless it's really necessary for your use case as you will also have to keep track of scaling the step number as you scale the batch size, and that's just added complication) 

Scaling the batch size is simple:
```
per_replica_batch_size = 64
global_batch_size = per_replica_batch_size * strategy.num_replicas_in_sync

...

train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).shuffle(60000).batch(global_batch_size)
```

For more details on performance debugging, please see the [GPU performance guide](https://www.tensorflow.org/guide/gpu_performance_analysis). We have not added in details to this guide yet on how to debug multiworker setups, but I think most of the findings/tips for the single and multi GPU case are still useful to understand.

Hope this helps!

**Comment by dgoldenberg-audiomack** [comment]
Hi @nikitamaia, thanks for your response.  I think you may be the perfect person to talk to because so much of this is doc-related esp. for folks new-ish to the framework.

> I don't think this finding is too surprising.

Well, it is in fact very much surprising for a "noob". So much so that I'd venture to wonder why the doc about distributed processing doesn't utilize a larger dataset which would unequivocally show the benefits of something like `MultiWorkerMirroredStrategy`, when used in a multi-node scenario, right off the bat.  This would save developers quite a bit of trouble; I've seen similar questions in places like stackoverflow.  I've wondered if MNIST was too small a dataset but it would have saved me (and probably quite a few others) the time wondering and typing posts.

> For more details on performance debugging, please see the GPU performance guide. 

And that is another big point of user confusion, right there.  Where does the multi-worker begin or end and where does the GPU support begin or end?  If you look at the guides discussing `MultiWorkerMirroredStrategy`, [the very first thing the code there does](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) is turn the GPU support **off**.  Quote:

> Disable all GPUs. This prevents errors caused by the workers all trying to use the same GPU. For a real application each worker would be on a different machine.
> os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In all, the confusion is this: I have 2 GB of data. I want to distribute model training. I'm using AWS; maybe I need a cluster of m machines, maybe I need a cluster of p3 machines?  Do I want one machine with N gpu devices?  Do I want to use X number of m machines which are cheaper?

[The doc](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) says to disable GPU support for multi-worker.  Why?  Can I possibly combine the benefits of multi-worker with those of GPU support?

Basically, what's lacking, IMO, is a fully functional set of samples of large-ish datasets that walk the user through the steps of setting up a machine or a cluster and how to do the sizing and resource allocation properly.  Not only that, but how to do this with the specifics of AWS and GCP in mind.

For example, as things stand, it's not clear to me at all how one would go about getting TF to work in AWS EMR. Tensorflow can be installed there, but how do you configure it?  TF multi-worker requires the `TF_CONFIG` env var to be set on specific boxes using specific IP addresses; that's not very friendly to environments such as EMR because it requires each box to be aware of all the other cluster boxes.

Beyond that (separate topic), I can't seem to use Spark to fully handle all the data processing.  It appears I'd have to pre-generate my datasets, drop them into S3, and have Tensorflow's own loaders load the data into its own datasets.  There is a [Spark TF distributor](https://github.com/tensorflow/ecosystem/tree/master/spark/spark-tensorflow-distributor) but it's entirely unclear how to use and configure it.

All of this is a huge jigsaw puzzle one has to deal with. Some of this is usability and some of this is doc. The framework screams for a full how-to, otherwise it's weeks of effort for each individual developer trying to piece all this together.

**Comment by nikitamaia** [comment]
Hi @dgoldenberg-audiomack, thanks for all the feedback!
The tutorial you're referencing is intended to demonstrate just the mechanics of using `MultiWorkerMirroredStrategy`, so the use of MNIST is to reduce any added complication from modeling/data requirements. But in general, `MultiWorkerMirroredStrategy` works for both machines with GPUs and machines without GPUs. All of the guides on tensorflow.org are [runnable as colab notebooks,](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/distribute/multi_worker_with_keras.ipynb) so the disabling of the GPU in that line you're referencing is so that you can simulate a multi machine environment within colab.

As for end to end tutorials, [I published one for MirroredStrategy](https://blog.tensorflow.org/2020/12/getting-started-with-distributed-tensorflow-on-gcp.html) a few months ago. A large portion of the tutorial is GCP specific, but the explanations of how MirroredStrategy works and how to use it are applicable more generally. And there should be a follow up for MultiWorkerMirroredStrategy coming soon. Unfortunately, we don't have the bandwidth (or expertise) to provide tutorials for every cloud service, so community help here is greatly appreciated! AWS' solution architects also publish lots of blueprints for running TensorFlow on their services, so my suggestion would be to check out their examples.

Similarly, it's difficult for us to provide generic guidelines on what cluster configuration is best since we don't have control over cloud VM prices or know details about the networking, or user's data and model requirements. We have to rely on the cloud platforms to fill in the gaps here! But my personal opinion on this is to try the simpler configurations first (ie `MirroredStrategy`) and then add more resources if you think the time per epoch is still too large. Moving from single host to multi-host results in more overhead, so start with the simpler configuration first to determine if you need more scaling.

[The GPU performance guide](https://www.tensorflow.org/guide/gpu_performance_analysis) also provides a formula to get a sense for what the overhead of distribution will be. This might help you to determine the resources needed.
```(number of parameters * 4bytes)/ (communication bandwidth)```

**Comment by dgoldenberg-audiomack** [comment]
Whether MirroredStrategy or MultiWorkerMirroredStrategy, I get errors such as the following:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Requires start <= limit when delta > 0: 2147483000/-2147483296
```

Any ideas as to what might be causing this? This is now blocking me from making any progress on this issue also.

I've filed a ticket with tf-recommenders [here](https://github.com/tensorflow/recommenders/issues/274).

**Comment by nikitamaia** [comment]
Unfortunately, I don't have much context on tf-recommenders so your best bet is to wait until someone in that repo gets a chance to take a look. But one thing to check that can help determine if the issue is with the `tf.distribute.Strategy` API is to see what happens when you use `tf.distribute.get_strategy()`, instead of `MirroredStrategy` or `MultiWorkerMirroredStrategy`, which implements the tf.distribute.Strategy interface but is a pass-through and provides no actual distribution.

**Comment by certainly-cyber** [comment]
@nikitamaia 
Hello I have some confusion about the overhead. Based on the content of the blog, The time to AllReduce should be:
(number of parameters * 4bytes)/ (communication bandwidth)
But as far as I know, TensorFlow uses ring allreduce, which seems to mean that the number of synchronized data should be [2 * (N -1)/N ]* number of parameters * 4bytes(Reduce Scatter + All Gather), N represents the number of workers.If we do some simplification, this should be like:
(2 * number of parameters * 4bytes)
May I ask if my understanding is correct? Thank you~
