### ISSUE TITLE
Broken/outdated Links in Docs 

### ISSUE THREAD

**Issue by uzair-ali10** [tensorflow/tensorflow#48370]
While going through the documentation I encountered a few broken/outdated links, and I've found the correct link for the same 
Kindly assign this issue to me so that I can make the required changes.

**Comment by uzair-ali10** [comment]
@UsharaniPagadala Kindly assign the issue to me

**Comment by uzair-ali10** [comment]
Fixed all the broken link  
here is the PR
[https://github.com/tensorflow/examples/pull/303](https://github.com/tensorflow/examples/pull/303)

**Comment by UsharaniPagadala** [comment]
@uzair-ali10 

This issue will be closed once the PR is merged.Thanks

**Comment by uzair-ali10** [comment]
@UsharaniPagadala 

Alright, Thanks for merging!!!
