### ISSUE TITLE
tensorflow.experimental.numpy operations return tf.Tensor instead of ndarray<tf.Tensor>

### ISSUE THREAD

**Issue by SebastianJL** [tensorflow/tensorflow#48376]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): debian 10.9
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0rc0
- Python version: Python 3.7.5

**Describe the current behavior**
In tensorflow 2.5.0rc0 these operations
```python
import tensorflow as tf
import tensorflow.experimental.numpy as tnp

print(tnp.real(tf.constant(1)))
print(tnp.real(tf.constant(1+1j)))
print(tnp.imag(tf.constant(1+1j)))
print(tnp.array(tf.constant(1)))
```
return the following results
```python
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1, shape=(), dtype=int32)
```

**Describe the expected behavior**
In tensorflow 2.4.1 they used to return ndarrays
```python
ndarray<tf.Tensor(1, shape=(), dtype=int32)>
ndarray<tf.Tensor(1.0, shape=(), dtype=float64)>
ndarray<tf.Tensor(1.0, shape=(), dtype=float64)>
ndarray<tf.Tensor(1, shape=(), dtype=int32)>
```

**Other info / logs**
I didn't test any other methods.

**Edit**
I don't know if this actually is a bug or if it was one in tensorflow 2.4.1. But I couldn't find out which one is the intended behaviour. I for my part would expect these functions to return an ndarray but the introduction [article](https://www.tensorflow.org/guide/tf_numpy#tftensor_and_nd_array) seems to have a different opinion.

**Comment by tilakrayal** [comment]
@SebastianJL 

I was able to reproduce the issue. Please find the [gist](https://colab.research.google.com/gist/tilakrayal/44d02613d4cc21e5161da3f495ad8050/48376-2-4.ipynb) of it here. Thanks!

**Comment by ymodak** [comment]
`ndarray` wrapper is removed intentionally with TF 2.5.0-rc1
See commit [0b9ff2e](https://github.com/tensorflow/tensorflow/commit/0b9ff2eb1a097602206c6b29823543768bfb34fe#diff-ff9428d2d7e920852bc429bd4ffd46ae182d27730a55d16d31d34a5d21d38ac6)
