### ISSUE TITLE
INFO log get printed in tf2.5-rc0

### ISSUE THREAD

**Issue by henrysky** [tensorflow/tensorflow#48377]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 20H2 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0rc0
- Python version: 3.9.2
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): msvc 19.28.29913
- CUDA/cuDNN version: 11.2/8.1.1
- GPU model and memory: GTX1650 4GB

**Describe the current behavior**

simply doing ``import tensorflow as tf`` will print out all log at INFO level to Jupyter notebook

![image](https://user-images.githubusercontent.com/28623434/113896873-56156d00-9798-11eb-834a-d5a232222cb7.png)

**Describe the expected behavior**

Logs at INFO level will not get print to Jupyter notebook

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1-rOtR-xYJYymNIv4aksle_ZI9W90WLBh?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@henrysky 
I didn't face any info errors while running the code.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/b2faec222ca8d58ca3d2acacf8a708f2/-48377.ipynb#scrollTo=1kQicu7NMWf9) here

**Comment by henrysky** [comment]
I just ran your colab notebook those INFO get printed

![image](https://user-images.githubusercontent.com/28623434/113908499-9d095f80-97a4-11eb-8b02-ce51a82980bf.png)

**Comment by UsharaniPagadala** [comment]
@henrysky 
Can you please  [try](https://colab.research.google.com/gist/UsharaniPagadala/9cf5e09b254a630b09625f6697b8902a/-48377.ipynb) this. 
The logs are printed only for the first time on importing tensorflow.
Thanks

**Comment by mihaimaruseac** [comment]
Can you bisect with nightly versions to see at what nightly this got introduced?

**Comment by henrysky** [comment]
The behavior is introduced in this commit https://github.com/tensorflow/tensorflow/commit/373883e4cc074c5ad0efa8c3d3875ae102c4005a

**Comment by ymodak** [comment]
This is fixed with latest release of  TF 2.5-rc3 and should be in TF 2.5 final version as well.
Please check this [gist](https://colab.research.google.com/gist/ymodak/15e0203253582cc830f110ac8206fea7/-48377.ipynb) for reference.

**Comment by henrysky** [comment]
indeed fixed in rc3, thanks!
