### ISSUE TITLE
Tensorflow support for advance models like VAE-GAN, GAN 

### ISSUE THREAD

**Issue by gomrinal** [tensorflow/tensorflow#48389]
Hello,
I was wondering if you guys are planning to make functional APIs for advanced research-based models like VAE, VAEGAN, GANS, etc.
If so then it will be very easier for the TensorFlow community to explore applications of these models in an array of real-world problems. Since currently the generative model uses multiple losses therefore training them is not intuitive and often ends up in unstable training. 
GradientTape alleviates the problem a little but still, it's a major bottleneck in the widespread adoption of advance deep learning models in business problems.
Link: https://arxiv.org/pdf/1512.09300.pdf
Regards,
Mrinal

**Comment by tilakrayal** [comment]
@gomrinal,
**Variational Autoencoders (VAEs)**:

TensorFlow provides the tools to implement VAEs and also can define the custom layers and losses, perform sampling using TensorFlow ops, and also we can optimize the model using TensorFlow optimizers. 

`VAEs` are used for generative tasks and latent space representations. We have the **TensorFlow Probability (TFP)** which is an extension of TensorFlow that makes it simpler to work with probabilistic models like VAEs. TFP provides a wide range of probabilistic layers and distributions for building VAEs.

**Generative Adversarial Networks (GANs)**:

We can build both the generator and discriminator networks using TensorFlow & Keras API or lower-level TensorFlow ops. 
TensorFlow automatic differentiation capabilities are essential for training `GANs` and also provides libraries like TensorFlow Hub, which include pre-trained GAN models and components for GAN-based image generation tasks.

https://www.tensorflow.org/tutorials/generative/cvae
https://www.tensorflow.org/tutorials/generative/dcgan
https://www.tensorflow.org/tutorials/generative/cyclegan

Thank you!
