### ISSUE TITLE
TensorBoard can't support read data from Kerberos cluster hdfs.

### ISSUE THREAD

**Issue by bd050705** [tensorflow/tensorflow#48392]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.8
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 
      tensorboard            2.4.1    
      tensorboard-plugin-wit 1.8.0    
      tensorflow             2.3.1    
      tensorflow-estimator   2.3.0  
- Python version: 3.6.8

**Describe the current behavior**
sudo su hdfs
export KERB_TICKET_CACHE_PATH=/tmp/krb5cc_996
echo 'hdfs' | kinit hdfs@TEST-KDC

bash-4.2$ hdfs dfs -ls /tmp/tensorflow/mnist/
Found 4 items
drwxr-xr-x   - hdfs supergroup          0 2021-03-31 18:03 /tmp/tensorflow/mnist/input_data
drwxr-xr-x   - hdfs supergroup          0 2021-04-07 19:49 /tmp/tensorflow/mnist/working_dir
drwxr-xr-x   - hdfs supergroup          0 2021-03-31 19:25 /tmp/tensorflow/mnist/working_dir_1131
drwxr-xr-x   - hdfs supergroup          0 2021-03-31 19:39 /tmp/tensorflow/mnist/working_dir_231

bash-4.2$ hdfs dfs -ls /tmp/tensorflow/mnist/working_dir
Found 17 items
-rw-r--r--   1 hdfs supergroup        222 2021-04-07 19:49 /tmp/tensorflow/mnist/working_dir/checkpoint
-rw-r--r--   1 hdfs supergroup     656044 2021-03-31 20:09 /tmp/tensorflow/mnist/working_dir/events.out.tfevents.1617217664.cdhhakerberos-cdh-core-kudu-0.novalocal
-rw-r--r--   1 hdfs supergroup     657680 2021-04-01 02:10 /tmp/tensorflow/mnist/working_dir/events.out.tfevents.1617239301.cdhhakerberos-cdh-core-kudu-0.novalocal
-rw-r--r--   1 hdfs supergroup     657796 2021-04-07 20:49 /tmp/tensorflow/mnist/working_dir/events.out.tfevents.1617824847.cdhhakerberos-cdh-core-kudu-0.novalocal
-rw-r--r--   1 hdfs supergroup     328014 2021-04-07 19:47 /tmp/tensorflow/mnist/working_dir/graph.pbtxt
-rw-r--r--   1 hdfs supergroup   39295624 2021-03-31 19:07 /tmp/tensorflow/mnist/working_dir/model.ckpt-0.data-00000-of-00001
-rw-r--r--   1 hdfs supergroup        994 2021-03-31 19:07 /tmp/tensorflow/mnist/working_dir/model.ckpt-0.index
-rw-r--r--   1 hdfs supergroup     138970 2021-03-31 19:07 /tmp/tensorflow/mnist/working_dir/model.ckpt-0.meta

CLASSPATH=`hadoop classpath --glob` tensorboard --logdir hdfs://default/tmp/tensorflow/mnist/ --host `hostname` --verbosity 0 --logger_levels other.logger:DEBUG --stderrthreshold debug

**Describe the expected behavior**
I expect show data in Tensorboard. But TensorBoard show "No dashboards are active for the current data set."

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

2021-04-07 22:22:10.690895: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
I0407 22:22:13.750683 139694758954816 plugin_event_multiplexer.py:106] Event Multiplexer initializing.
I0407 22:22:13.750985 139694758954816 plugin_event_multiplexer.py:125] Event Multiplexer done initializing
I0407 22:22:13.751172 139694758954816 data_ingester.py:124] Launching reload in a daemon thread
I0407 22:22:13.752043 139693371959040 data_ingester.py:98] TensorBoard reload process beginning
I0407 22:22:13.752586 139693371959040 plugin_event_multiplexer.py:201] Starting AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/
I0407 22:22:13.756613 139693371959040 plugin_event_multiplexer.py:207] Done with AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/
I0407 22:22:13.756979 139693371959040 data_ingester.py:102] TensorBoard reload process: Reload the whole Multiplexer
I0407 22:22:13.757233 139693371959040 plugin_event_multiplexer.py:212] Beginning EventMultiplexer.Reload()
I0407 22:22:13.757594 139693371959040 plugin_event_multiplexer.py:256] Reloading runs serially (one after another) on the main thread.
I0407 22:22:13.757895 139693371959040 plugin_event_multiplexer.py:265] Finished with EventMultiplexer.Reload()
I0407 22:22:13.758112 139693371959040 data_ingester.py:107] TensorBoard done reloading. Load took 0.006 secs
TensorBoard 2.4.1 at http://cdhhakerberos-cdh-master1-0.novalocal:6006/ (Press CTRL+C to quit)
I0407 22:22:14.644470 139693380351744 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:14] "GET / HTTP/1.1" 200 -
I0407 22:22:14.728922 139693380351744 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:14] "GET /index.js HTTP/1.1" 200 -
I0407 22:22:14.752892 139693388744448 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:14] "GET /font-roboto/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 HTTP/1.1" 200 -
I0407 22:22:15.515960 139693380351744 application.py:439] Plugin listing: is_active() for scalars took 0.000 seconds
I0407 22:22:15.516464 139693380351744 application.py:439] Plugin listing: is_active() for custom_scalars took 0.000 seconds
I0407 22:22:15.516749 139693380351744 application.py:439] Plugin listing: is_active() for images took 0.000 seconds
I0407 22:22:15.516995 139693380351744 application.py:439] Plugin listing: is_active() for audio took 0.000 seconds
I0407 22:22:15.517701 139693380351744 application.py:439] Plugin listing: is_active() for debugger-v2 took 0.000 seconds
I0407 22:22:15.518152 139693380351744 application.py:439] Plugin listing: is_active() for graphs took 0.000 seconds
I0407 22:22:15.518453 139693380351744 application.py:439] Plugin listing: is_active() for distributions took 0.000 seconds
I0407 22:22:15.518700 139693380351744 application.py:439] Plugin listing: is_active() for histograms took 0.000 seconds
I0407 22:22:15.518924 139693380351744 application.py:439] Plugin listing: is_active() for text took 0.000 seconds
I0407 22:22:15.519140 139693380351744 application.py:439] Plugin listing: is_active() for pr_curves took 0.000 seconds
I0407 22:22:15.519388 139693380351744 application.py:439] Plugin listing: is_active() for profile_redirect took 0.000 seconds
I0407 22:22:15.519608 139693380351744 application.py:439] Plugin listing: is_active() for hparams took 0.000 seconds
I0407 22:22:15.519902 139693380351744 application.py:439] Plugin listing: is_active() for mesh took 0.000 seconds
I0407 22:22:15.520128 139693380351744 application.py:439] Plugin listing: is_active() for timeseries took 0.000 seconds
I0407 22:22:15.525379 139693397137152 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /icon_bundle.svg HTTP/1.1" 200 -
I0407 22:22:15.526228 139693380351744 application.py:439] Plugin listing: is_active() for projector took 0.006 seconds
I0407 22:22:15.526491 139693380351744 application.py:439] Plugin listing: is_active() for whatif took 0.000 seconds
I0407 22:22:15.529370 139693388744448 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /data/environment HTTP/1.1" 200 -
I0407 22:22:15.530524 139693380351744 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /data/plugins_listing HTTP/1.1" 200 -
I0407 22:22:15.541091 139693380351744 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /data/runs HTTP/1.1" 200 -
I0407 22:22:15.542141 139693397137152 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /data/environment HTTP/1.1" 200 -
I0407 22:22:15.544588 139693388744448 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /font-roboto/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2 HTTP/1.1" 200 -
I0407 22:22:15.587946 139693388744448 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /data/runs HTTP/1.1" 200 -
I0407 22:22:15.699429 139693388744448 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /font-roboto/d-6IYplOFocCacKzxwXSOJBw1xU1rKptJj_0jans920.woff2 HTTP/1.1" 200 -
I0407 22:22:15.701413 139693397137152 _internal.py:113] 192.168.140.253 - - [07/Apr/2021 22:22:15] "GET /font-roboto/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2 HTTP/1.1" 200 -
I0407 22:22:18.765110 139693371959040 data_ingester.py:98] TensorBoard reload process beginning
I0407 22:22:18.765607 139693371959040 plugin_event_multiplexer.py:201] Starting AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/
I0407 22:22:18.765993 139693371959040 plugin_event_multiplexer.py:207] Done with AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/
I0407 22:22:18.766208 139693371959040 data_ingester.py:102] TensorBoard reload process: Reload the whole Multiplexer
I0407 22:22:18.766429 139693371959040 plugin_event_multiplexer.py:212] Beginning EventMultiplexer.Reload()
I0407 22:22:18.766694 139693371959040 plugin_event_multiplexer.py:256] Reloading runs serially (one after another) on the main thread.
I0407 22:22:18.766852 139693371959040 plugin_event_multiplexer.py:265] Finished with EventMultiplexer.Reload()
I0407 22:22:18.766979 139693371959040 data_ingester.py:107] TensorBoard done reloading. Load took 0.002 secs

**Comment by kvignesh1420** [comment]
@bd050705 as per the [documentation](https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md) you need to set `KRB5CCNAME` as the path of Kerberos ticket cache file. For example:
```bash
export KRB5CCNAME=/tmp/krb5cc_10002
```

Can you give it a try?

**Comment by bd050705** [comment]
yes, I have try export KRB5CCNAME="/tmp/krb5cc_996", but it also not working on TensorBoard load data from hdfs.
My Tensorflow can write file to hdfs on kerberos mode. I download it to local system, It can be show on TensorBoard. But TensorBoard can't show the data from hdfs. I wonder is TensorBoard not support file I/O from kerberos cluster HDFS?

**Comment by kvignesh1420** [comment]
@bd050705 tensorboard uses tensorflow's file system modules for io from hdfs. If writes are supported then reads should ideally be working as well.

**Comment by bd050705** [comment]
Thank you for your reply. I also can't find any error log from tensorboard debug log. Only Tensorboard UI show "No dashboards are active for the current data set". But log had print "plugin_event_multiplexer.py:201] Starting AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/" and "Done with AddRunsFromDirectory: hdfs://default/tmp/tensorflow/mnist/", it seem to io_wrapper.GetLogdirSubdirectories(path) is empty, so bellow code "logger.info("Adding run from directory %s", subdir)" didn't be print out? but if I download this directory to local, events.out data can be display on tensorboard normally.

https://github.com/tensorflow/tensorboard/blob/2.4.1/tensorboard/backend/event_processing/plugin_event_multiplexer.py
        logger.info("Starting AddRunsFromDirectory: %s", path)
        for subdir in io_wrapper.GetLogdirSubdirectories(path):
            logger.info("Adding run from directory %s", subdir)
            rpath = os.path.relpath(subdir, path)
            subname = os.path.join(name, rpath) if name else rpath
            self.AddRun(subdir, name=subname)
        logger.info("Done with AddRunsFromDirectory: %s", path)

**Comment by bd050705** [comment]
I found that in tensorflow 1.13.1 it had add kerberos support for HDFS, but tensorflow 2.3.1 is not, and my tensorboard use 2.4.1. I also test use tensorflow 2.3.1 read and write kerberos hdfs and result is fail. I wonder is tensorflow not support kerberos for HDFS?

Add Kerberos support for HDFS file system #5398

Error log for tensorflow 2.3.1 listdir for kerberos HDFS

> NotFoundError                             Traceback (most recent call last)
> <ipython-input-20-00718e3957b5> in <module>
>       4 #with gfile.Open("hdfs://192.168.140.140:8020/tmp",'rb') as f:
>       5 #    f.readline()
> ----> 6 tf.io.gfile.listdir('hdfs://default/tmp/')
>       7 #tf.io.gfile.mkdir('hdfs://default/tmp/gfile')
>       8 #pathexist = gfile.Exists('hdfs://default/tmp')
> 
> /usr/local/lib64/python3.6/site-packages/tensorflow/python/lib/io/file_io.py in list_directory_v2(path)
>     692         node_def=None,
>     693         op=None,
> --> 694         message="Could not find directory {}".format(path))
>     695 
>     696   # Convert each element to string, since the return values of the
> 
> NotFoundError: Could not find directory hdfs://default/tmp/
> 

Tensorflow 1.13.1
https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/core/platform/hadoop/hadoop_file_system.cc
line 58-77

>   std::function<hdfsFS(hdfsBuilder*)> hdfsBuilderConnect;
>   std::function<hdfsBuilder*()> hdfsNewBuilder;
>   std::function<void(hdfsBuilder*, const char*)> hdfsBuilderSetNameNode;
>   std::function<int(const char*, char**)> hdfsConfGetStr;
>   std::function<void(hdfsBuilder*, const char*kerbTicketCachePath)>
>       hdfsBuilderSetKerbTicketCachePath;
>   std::function<int(hdfsFS, hdfsFile)> hdfsCloseFile;
>   std::function<tSize(hdfsFS, hdfsFile, tOffset, void*, tSize)> hdfsPread;
>   std::function<tSize(hdfsFS, hdfsFile, const void*, tSize)> hdfsWrite;
>   std::function<int(hdfsFS, hdfsFile)> hdfsHFlush;
>   std::function<int(hdfsFS, hdfsFile)> hdfsHSync;
>   std::function<hdfsFile(hdfsFS, const char*, int, int, short, tSize)>
>       hdfsOpenFile;
>   std::function<int(hdfsFS, const char*)> hdfsExists;
>   std::function<hdfsFileInfo*(hdfsFS, const char*, int*)> hdfsListDirectory;
>   std::function<void(hdfsFileInfo*, int)> hdfsFreeFileInfo;
>   std::function<int(hdfsFS, const char*, int recursive)> hdfsDelete;
>   std::function<int(hdfsFS, const char*)> hdfsCreateDirectory;
>   std::function<hdfsFileInfo*(hdfsFS, const char*)> hdfsGetPathInfo;
>   std::function<int(hdfsFS, const char*, const char*)> hdfsRename;
> 

Tensorflow 2.3.1
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/core/platform/hadoop/hadoop_file_system.cc
line 50-68

>  std::function<hdfsFS(hdfsBuilder*)> hdfsBuilderConnect;
>   std::function<hdfsBuilder*()> hdfsNewBuilder;
>   std::function<void(hdfsBuilder*, const char*)> hdfsBuilderSetNameNode;
>   std::function<int(const char*, char**)> hdfsConfGetStr;
>   std::function<int(hdfsFS, hdfsFile)> hdfsCloseFile;
>   std::function<tSize(hdfsFS, hdfsFile, tOffset, void*, tSize)> hdfsPread;
>   std::function<tSize(hdfsFS, hdfsFile, const void*, tSize)> hdfsWrite;
>   std::function<int(hdfsFS, hdfsFile)> hdfsHFlush;
>   std::function<int(hdfsFS, hdfsFile)> hdfsHSync;
>   std::function<tOffset(hdfsFS, hdfsFile)> hdfsTell;
>   std::function<hdfsFile(hdfsFS, const char*, int, int, short, tSize)>
>       hdfsOpenFile;
>   std::function<int(hdfsFS, const char*)> hdfsExists;
>   std::function<hdfsFileInfo*(hdfsFS, const char*, int*)> hdfsListDirectory;
>   std::function<void(hdfsFileInfo*, int)> hdfsFreeFileInfo;
>   std::function<int(hdfsFS, const char*, int recursive)> hdfsDelete;
>   std::function<int(hdfsFS, const char*)> hdfsCreateDirectory;
>   std::function<hdfsFileInfo*(hdfsFS, const char*)> hdfsGetPathInfo;
>   std::function<int(hdfsFS, const char*, const char*)> hdfsRename;

**Comment by kvignesh1420** [comment]
@bd050705 yes, seems like the support was removed in https://github.com/tensorflow/tensorflow/commit/2cad3742600f3e903bc5a2d1a60ef4b571e7c8f9#diff-b6e19034b00093723ad953a6ffb8528b9d311a86a650be0bb7ad58900bfb03f9 due to:
```cc
// KERB_TICKET_CACHE_PATH will be deleted in the future, Because KRB5CCNAME is
// the build in environment variable of Kerberos, so KERB_TICKET_CACHE_PATH
// and related code are unnecessary.
```

**Comment by kvignesh1420** [comment]
@bd050705 just to test the writes as well, can you please try this and let me know the output:

```python
import tensorflow as tf

body = b"1234567"
tf.io.write_file("hdfs://default/testfile.txt")

content = tf.io.read_file("hdfs://default/testfile.txt")
print("CONTENT: {}".format(content))
assert content == body

**Comment by bd050705** [comment]
import tensorflow as tf

body = b"1234567"
tf.io.write_file("hdfs://default/testfile.txt", b"1234567")

content = tf.io.read_file("hdfs://default/testfile.txt")
print("CONTENT: {}".format(content))
assert content == body


CONTENT: Tensor("ReadFile_6:0", shape=(), dtype=string)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-35-7d2943abc0e0> in <module>
      6 content = tf.io.read_file("hdfs://default/testfile.txt")
      7 print("CONTENT: {}".format(content))
----> 8 assert content == body

AssertionError:

**Comment by kvignesh1420** [comment]
I hope you set the necessary environment variables before running this. As per [docs](https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/hadoop.md).

**Comment by bd050705** [comment]
Thank you for your remind and reply. After I add "export LD_LIBRARY_PATH=/usr/java/jdk1.8.0_181-cloudera/jre/lib/amd64/server/" it work successfully. But on disable Kerberos cluster didn't need add this environment variables it can work normally.

**Comment by kvignesh1420** [comment]
Welcome. So is the tensorboard issue solved as well?

**Comment by bd050705** [comment]
Yes! Thank you very much.
