### ISSUE TITLE
Add link and more info in tf/examples/README

### ISSUE THREAD

**Issue by alphaX86** [tensorflow/tensorflow#48394]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by alphaX86** [comment]
Here's a brief about the issue...
In this repo (tensorflow/tensorflow/examples) the README is enough with examples and all other things, but still it has a statement "This directory is not actively maintained" which is fine, but I feel a statement must be included along with it... "Refer this repo for more examples as this folder is not actively maintained" so that newcomers will know and refer to that link

**Comment by alphaX86** [comment]
And TF community, please assign me this issue, I want to work on it! :)

**Comment by Saduf2019** [comment]
@alphaX86 
 Please feel free to submit a PR.Thanks!
