### ISSUE TITLE
/micro_speech/recognize_commands_test.cc bug

### ISSUE THREAD

**Issue by lucy0828** [tensorflow/tensorflow#48396]
Hi, I tried to follow the book TinyML chapter 07 and ran `recognize_command_test` and got an error shown in the img below..
I think in `recognize_commands_test.cc` line 158
`const int bad_dims[] = {2, 1, 3};`  
has to be changed to 
`const int bad_dims[] = {2, 1, 4};` 

![Screenshot from 2021-04-08 16-43-54](https://user-images.githubusercontent.com/46836844/113991238-3875ff80-988d-11eb-9e81-c853ec79b31c.png)

**Comment by lucy0828** [comment]
> Hi, I tried to follow the book TinyML chapter 07 and ran `recognize_command_test` and got an error shown in the img below..
> I think in `recognize_commands_test.cc` line 158
> `const int bad_dims[] = {2, 1, 3};`
> has to be changed to
> `const int bad_dims[] = {2, 1, 4};`
> 
> ![Screenshot from 2021-04-08 16-43-54](https://user-images.githubusercontent.com/46836844/113991238-3875ff80-988d-11eb-9e81-c853ec79b31c.png)

oh,, nevermind I figured it out!! There's no problem

**Comment by legitishan** [comment]
Hey, can someone close this issue :) (sorry if this sounds mean)
