### ISSUE TITLE
TopK GPU slower than TopK CPU

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#48397]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: MX150 4GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TopK GPU slower than TopK CPU
**Describe the expected behavior**
TopK GPU faster than TopK CPU
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
``` python
import tensorflow as tf

cls_outputs_reshape = tf.random.uniform((1, 4419360), -30 ,30)
def top_k_func(*args, **kwargs):
    return tf.math.top_k(*args, **kwargs)
top_k = tf.function(top_k_func)
with tf.device('/CPU:0'):
    _, cls_topk_indices = top_k(cls_outputs_reshape, k=5000, sorted=False)
with tf.device('/GPU:0'):
    _, cls_topk_indices = top_k(cls_outputs_reshape, k=5000, sorted=False)
tf.profiler.experimental.start('./profile_dir')
with tf.device('/CPU:0'):
    _, cls_topk_indices = top_k(cls_outputs_reshape, k=5000, sorted=False)
with tf.device('/GPU:0'):
    _, cls_topk_indices = top_k(cls_outputs_reshape, k=5000, sorted=False)
tf.profiler.experimental.stop()
```
``` bash
tensorboard --logdir=./profile_dir
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![Screenshot from 2021-04-08 16-21-30](https://user-images.githubusercontent.com/17592563/113993013-9226fb80-9886-11eb-912f-c25bc2927295.png)

**Comment by Saduf2019** [comment]
@fsx950223 
I ran the code on gpu and do not face any delay, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ae8068949605e40337134b5178116f7c/untitled.ipynb).

**Comment by fsx950223** [comment]
I modified the [gist](https://colab.research.google.com/drive/1Mmp6qTEWkpAhKq6XjRvMMWpaae4jVdV3?usp=sharing)

**Comment by fsx950223** [comment]
Any update, @Saduf2019

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8d0fff98cbcb5ff6e91242597db5dcae/untitled592.ipynb).

**Comment by sanjoy** [comment]
@ebrevdo (since you wrote the TopK GPU implementation originally) Is this unexpected?  I don't really know if the GPU implementation is expected to work well with k = 5000.

**Comment by ebrevdo** [comment]
Some comments here:

* I'm seeing `Avg. Time` for GPU-based TopKV2 is 11k us, and for CPU-based is 13k us - so it looks like GPU is actually faster?
* For a measurement of total runtime (excludiing profiler) I'm not sure (from that code) whether a copy from/to CPU is happening.  May want to verify this by ensuring the `uniform` call is happening on GPU and remove the `tf.function` AND use %%timeit instead of the profiler.
* We do an extra copy in the GPU codepath this is using [here](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/kernels/topk_op_gpu.h#L450) and it's likely that gpuprim now has support for iterators for ValueT, which would allow us to get rid of an extra device allocation and copy - probably speeding up the sort kernel.  I haven't checked since I wrote this code.

**Comment by fsx950223** [comment]
> * here

It's a sort algorithm instead of a topk algorithm and its time complexity is O(n)log(n) instead of O(n)log(k). Implement [gpu-topk](https://anilshanbhag.in/static/papers/gputopk_sigmod18.pdf) should enhance the performance and the algorithm has been implemented in onnx-runtime.

**Comment by ebrevdo** [comment]
While I'm not sure the implementation is actually O(nlog(n)) given it's a radix sort (iirc), the fact that it's not a pure top-k algorithm is clearly limiting its performance when `n >> k`.  So it would be great to implement `gpu-topk` or some variant.  I'll mark this as contributions welcome for now.

**Comment by ebrevdo** [comment]
Keep in mind we would need a segmented top-k algorithm since we perform multiple parallel top-k operations in general.

**Comment by dumbinacan** [comment]
Hey, I am interested in contributing to this project.  Could someone point me to where in the codebase I can find the the current topk function?  Am I correct in assuming that the gpu-topk function is only different from top_k in that its the hash map implementation vs radix Sort?
