### ISSUE TITLE
Toy model crashes on multiple GPUs with "No unary variant device copy function"

### ISSUE THREAD

**Issue by MinasTyuru** [tensorflow/tensorflow#48391]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 14.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0
- Python version: 3
- Bazel version (if compiling from source): 0.29.1-1.8
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10.1
- GPU model and memory: Various, including TITAN Xp 12 GB

**Describe the current behavior**
A toy model consisting of several Conv2D and SyncBatchNorm layers, when training on 4 GPUs, fails with the following error:
```
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2021-04-08 03:24:12.084199: W external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:560] dependency_optimizer failed: Deadline exceeded: dependency_optimizer exceeded deadline., time = 11444.1797ms.
2021-04-08 03:24:18.334984: W external/org_tensorflow/tensorflow/core/common_runtime/process_function_library_runtime.cc:733] Ignoring multi-device function optimization failure: Deadline exceeded: meta_optimizer exceeded deadline.
Traceback (most recent call last):
  File "/.../train_keras_model.py", line 109, in <module>
    main()
  File "/.../train_keras_model.py", line 103, in main
    verbose=2,
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/def_function.py", line 708, in _call
    return function_lib.defun(fn_with_cond)(*canon_args, **canon_kwds)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/tmp/local_changes/train_keras_model.runfiles/org_tensorflow/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::ResourceDeleter
	 [[{{node cond/inner_args_0_7/_2117/_10568}}]]
	 [[cond/else/_1/StatefulPartitionedCall/Adam/Adam/update_69/update_2/ResourceApplyAdam/_51423]]
  (1) Internal:  No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::ResourceDeleter
	 [[{{node cond/inner_args_0_7/_2117/_10568}}]]
0 successful operations.
3 derived errors ignored. [Op:__inference_fn_with_cond_527347]

Function call stack:
fn_with_cond -> fn_with_cond
```

**Describe the expected behavior**
Model should train without crashing.

**Standalone code to reproduce the issue**
This standalone code reproduces the problem for us.
```
import logging

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.metrics import AUC
from tensorflow.keras.layers import Dense, Conv2D
from tensorflow.keras.layers.experimental import SyncBatchNormalization

def train_dataset_input():
    batch_size = 4
    x_value = tuple(tf.random.uniform((1, batch_size, 10, 10, 3)) for _ in range(5))
    y_value = tf.random.uniform((1, batch_size, 5))
    dataset = tf.data.Dataset.from_tensor_slices((x_value, y_value))
    dataset = dataset.repeat()
    return dataset

class ConvBN(tf.keras.layers.Layer):
    def __init__(self,):
        super(ConvBN, self).__init__()
        self.conv = Conv2D(filters=32, kernel_size=1)
        self.bn1 = SyncBatchNormalization()
        self.bn2 = SyncBatchNormalization()
        self.bn3 = SyncBatchNormalization()

    def call(self, inputs, training=None, **kwargs):
        x = self.conv(inputs)
        x = self.bn1(x)
        x = self.bn2(x)
        x = self.bn3(x)
        return x

class MultiFrameModel(keras.Model):
    def __init__(self, **kwargs):
        super(MultiFrameModel, self).__init__(name="multi_frame_model", **kwargs)
        self.backbone = keras.Sequential([ConvBN() for _ in range(17)])
        self.dense = Dense(5)

    def call(self, samples, training=False):
        backbone_outputs = []
        assert len(samples) == 5
        for img in samples:
            backbone_outputs.append(self.backbone(img))

        concat_sample = tf.concat(values=backbone_outputs, axis=3)
        x = tf.reduce_sum(concat_sample, [2, 3])
        x = self.dense(x)
        return x

class AucFromLogits(AUC):
    def update_state(self, y_true, logits, sample_weight=None):
        y_pred = tf.math.sigmoid(logits)
        super(AucFromLogits, self).update_state(y_true, y_pred, sample_weight)

def main():
    strategy = tf.distribute.MirroredStrategy()
    assert strategy.num_replicas_in_sync == 4

    train_dataset = train_dataset_input()
    with strategy.scope():
        metrics = [
            AucFromLogits(
                name="auc_from_logits",
                num_thresholds=100,
                curve="PR",
                multi_label=True,
                label_weights=[1.0, 0.0, 0.0, 0.0, 0.0],
            )
        ]

        model = MultiFrameModel()
        model.compile(
            optimizer=keras.optimizers.Adam(),
            loss=keras.losses.MeanSquaredError(),
            metrics=metrics,
        )

    model.fit(
        x=train_dataset,
        validation_data=train_dataset,
        steps_per_epoch=100,  # number of training steps between eval epochs
        epochs=120,  # epochs = total number of training steps / steps_per_epoch
        validation_steps=100,
        validation_freq=1,
        verbose=2,
    )

if __name__ == "__main__":
    logging.getLogger().setLevel(logging.INFO)
    main()
```

Please note that this code is sufficient to reproduce the crash in our environment. However, because the crash only occurs when training with multiple GPUs, and Colab only allows training on one GPU, this will run but not reproduce the crash on Colab. I tried splitting the GPU into 4 virtual GPUs, but it did not reproduce the problem.

**Other info / logs**
The following features of the model appear to be important; removing any of them "fixes" the problem.
- The model consists of SyncBatchNorm and Conv2D layers, and is fairly deep (it consists of a block repeated 17 times; repeating it, say, 10 times does not trigger the issue).
- The input is a tuple of 5 tensors, and the model backbone is applied to each of the tensors.
- There is a slightly modified AUC metric.
- The model runs on 4 GPUs with the Keras MirroredStrategy.

I'm quite confused as to how these four features should interact to cause a crash, especially the metric; it's quite surprising that adding a metric should somehow cause training to fail.

**Comment by amahendrakar** [comment]
@MinasTyuru,
I was able to run the code without any errors on a machine with TensorFlow v2.4.1 and 2 GPUs. Please check the below screenshot for reference.

![image](https://user-images.githubusercontent.com/57165142/114044461-e3de7e80-98a4-11eb-80f7-287353717fd5.png)


Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue? Thanks!

**Comment by amahendrakar** [comment]
Also, try limiting the GPU memory growth using any of the methods listed [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if it helps. Thanks!

**Comment by MinasTyuru** [comment]
@amahendrakar Thanks, Abhilash! To clarify, the failure only occurs on 4 GPUs, not 2; when I try 2 GPUs locally it also trains without any problems. Are you able to access a machine with 4 physical GPUs for testing?

The way our production build system integrates TensorFlow is a little delicate, and as a result, it is quite nontrivial for us to upgrade TensorFlow versions. When I run in a virtualenv with a fresh pip install of TF2.4.1, that trains correctly, whereas if I try a fresh pip install of TF2.2.0rc4, that fails. Would you be able to see if you can reproduce the problem on TF2.2.0rc4 with 4 GPUs? And given that it seems to happen only on TF2.2.0rc4 (at least for this case; it's possible it's a symptom of some problem that could occur for some other model on TF2.4.1), would we be able to get support on resolving the problem there, or would we have to just upgrade to TF2.4.1?

I also tried both of the memory growth limits in that link and it didn't seem to make a difference.

Thanks again!

**Comment by amahendrakar** [comment]
> Would you be able to see if you can reproduce the problem on TF2.2.0rc4 with 4 GPUs?

@MinasTyuru,
On running the code with TensorFlow v2.2.0rc4 and 4 GPUs, I did not face any errors. Please check the below screenshot for reference. 
![Screenshot 2021-04-19 7 37 44 PM](https://user-images.githubusercontent.com/57165142/115249969-c16f1f80-a146-11eb-809e-dbf6c6530315.png)

> When I run in a virtualenv with a fresh pip install of TF2.4.1, that trains correctly, whereas if I try a fresh pip install of TF2.2.0rc4, that fails.

In this case, I'd suggest you to update TensorFlow to v2.4.1 or v2.5.0rc1. Thanks!
