### ISSUE TITLE
Testcode runs on multiple gpus instead of one

### ISSUE THREAD

**Issue by staehlmich** [tensorflow/tensorflow#48406]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.9
- Python version: 3.6.13
- Installed using virtualenv? pip? conda?: conda 4.6.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: GeForce GTX TITAN X - 12G

**Describe the problem**
I'm running a simple test script from the tensorflow documentation, to see if my setup is working correctly. I'm using conda to run tensorflow 1.9. When I'm running my test script, even though I'm specifying the device, it is running on all gpus, instead of the specified one. I can't figure out what the issue is. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import tensorflow as tf

with tf.device('/device:GPU:3'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
  c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@staehlmich ,

TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by tilakrayal** [comment]
@staehlmich ,

TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!
