### ISSUE TITLE
tflite qat model inference data_type

### ISSUE THREAD

**Issue by fwz-fpga** [tensorflow/tensorflow#48402]
I am confused with tflite QAT model. Is it running with uint8 data_type or int8 data_type? 
With this link https://www.tensorflow.org/lite/guide/hosted_models , I download the quant models and find it with uint8 weights.
With this link https://www.tensorflow.org/lite/performance/quantization_spec#int8_quantized_operator_specifications, I found tflite quantization use int8 data_type.

Which is correct?

**Comment by freedomtan** [comment]
I'll say both :-) As far as I can remember, quant models at TFLite hosted models are mostly old QAT ones using UINT8. Nowadays, int8 is the default type.

**Comment by fwz-fpga** [comment]
@freedomtan thanks for your replay :-). 
I am confused what's the reason tflite choose to use int8 rather than uint8, performance or convinent? And where can I download a example int8 qat model to test.
Another question, if qat use int8 for default data_type, then post-training-quantize models and qat models can running the same operation kernels(realize with int8)?

**Comment by Xhark** [comment]
There's a note on the link: https://www.tensorflow.org/lite/performance/quantization_spec#int8_quantized_operator_specifications

`Note: In the past our quantization tooling used per-tensor, asymmetric, uint8 quantization. New tooling, reference kernels, and optimized kernels for 8-bit quantization will use this spec.`

As far as I know, old TFLite converter (TF 1.x) dtype was uint8, new TFLite converter (TF 2.x) dtype is int8.
TFLite kernel ops usually supports both dtypes. (int8 and uint8)
But new converter only supports TFLITE_BUILTINS_INT8 OpsSet: https://www.tensorflow.org/api_docs/python/tf/lite/OpsSet

> I am confused what's the reason tflite choose to use int8 rather than uint8, performance or convinent? And where can I download a example int8 qat model to test.

I think it's more easy to represent symmetric quantization which we usually used for dynamic-range quantization. (weight quantization) See more details here : https://www.tensorflow.org/lite/performance/quantization_spec#symmetric_vs_asymmetric

**Comment by fwz-fpga** [comment]
@Xhark Thanks! 
I am confused about tensorflow quantization. As far as I know, tf quantizetion methods divided into two categories , post-training-quantization and quantize-aware-training.
In  post-training-quantization there are: 
method 1、dynamic-range quantization
method 2、integer-only quantization（need some datasets）
method 3、Float16 quantization
In quantize-aware-training there is just one method(quantize during training, here I call it method 4).

Then,
I convert two tflite models through method 4 and method 2 from the same fp32 model. When  running this two quantized model with tflite, will they use the same operations in framework ? will they have the same performance?

I know the model generated by method 1 is slower because it activations produced by immediate layer may convert to fp32, it take some times. 
But the models generated by method 2 and method 4, I wonder that their attributes(model size, data_type, running kernels) should be same except the model accuracy.

**Comment by Xhark** [comment]
AFAIK, method2 and method4 should generate same model structure for the full-integer quantization case. (weight values and quantization parameter values might be different.) : So it should have the same performance.

But method4 (QAT) supports selective quantization which quantize only specific layers:
https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide#quantize_some_layers
