### ISSUE TITLE
GPU delegate run tensorflow-lite C++ example label_image more slowly than CPU

### ISSUE THREAD

**Issue by limdlh** [tensorflow/tensorflow#48407]
I compile tensorflow-lite and the example label_image in tensorflow-lite source code success,
I did run with delegates of GPU and also CPU with ADB with running comands:
     CPU:  ./label_image -m tflite_model_int8.tflite -i grace_hopper.bmp -l labels.txt -j 1
     GPU:  ./label_image -m tflite_model_int8.tflite -i grace_hopper.bmp -l labels.txt -g 1
Both seems runs success, but average time or GPU : 60.00 ms, average time or CPU : 40.00 ms
Is it right? GPU is more slow than CPU for 50% ?
If Not, what should I do to make GPU runs at good performance?

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9.0
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: BBK S5d (SOC: Qualcomm Snapdragon 660)
TensorFlow installed from (source or binary): build by myself
TensorFlow version (use command below): tensorflow-2.4.1
Python version: Python 3.8.5
Bazel version (if compiling from source): 3.1.0
GCC/Compiler version (if compiling from source): g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CUDA/cuDNN version:
GPU model and memory:
SOC: Qualcomm Snapdragon 660

Could anyone help? Or give a advice?
Thank you so much~

**Comment by Saduf2019** [comment]
@limdlh 
Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.

**Comment by abattery** [comment]
@impjdi @lintian06 could you take a look at this?

**Comment by freedomtan** [comment]
@limdlh Assuming all the nodes in you quantized models could be delegated to GPU, then you are comparing CPU int speed and GPU fp16 speed (because GPU delegate has to dequantized your model to floating point).

**Comment by limdlh** [comment]
@freedomtan I did compare CPU, GPU and also DSP for both int and fp16, both GPU and DSP is not obviously faster than CPU no matter int or fp16.

**Comment by impjdi** [comment]
It's hard to tell without taking a look at the model.

**Comment by limdlh** [comment]
@impjdi Hello, both model is here: https://github.com/limdlh/share

**Comment by limdlh** [comment]
@impjdi I also tested in DSP(Hexagon), it's still roghly same slowly as GPU

**Comment by impjdi** [comment]
Hm, you have a pretty large `FULLY_CONNECTED` at the end which may not be too efficient when run on the GPU.  Try to cut the network right after the final `CONV_2D` and see whether it's indeed the culprit.

**Comment by limdlh** [comment]
@impjdi I did cut the FULLY_CONNECTED, but DSP(Hexagon) and GPU are still slow as CPU.

**Comment by impjdi** [comment]
Sorry for the late turnaround.  Have a lot of things on my plate.

That's a quite disappointing news; I suspected things to be slow on those end, but maybe there is more to it.  Do you have the adb log?

**Comment by impjdi** [comment]
I ran your full network (`tflite_model_not_quant.tflite`) on a Pixel 4:

CPU: 38.018285ms
GPU: 5.6015285ms

AFAIK Pixel 4 has Qualcomm Snapdragon 855 & Adreno 640.  So I don't think it's the delegate or the model.

I'm not familiar with the `label_image` thing.  How is the inference engine used?  It should look like:

```
  // done once.
  auto model = FlatBufferModel::BuildFromFile(model_path);
  unique_ptr<Interpreter> gpu_inference;
  InterpreterBuilder(*model, op_resolver)(&gpu_inference);
  TfLiteGpuDelegateOptionsV2 o = TfLiteGpuDelegateOptionsV2Default();
  o.inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_SUSTAINED_SPEED;
  o.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
  o.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
  o.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
  auto* gpu_delegate = TfLiteGpuDelegateV2Create(&o);
  gpu_inference->ModifyGraphWithDelegate(gpu_delegate);  // check whether it fails!  i'm just being lazy

  // now for each input tensor...
  gpu_inference->Invoke();  // check whether it fails!  i'm just being lazy
```

**Comment by limdlh** [comment]
@impjdi Thanks for your reply, but I find in the [TFLite docment ](https://tensorflow.google.cn/lite/performance/gpu#c-until-2.3.0), it use TfLiteInterpreterOptions, not TfLiteGpuDelegateOptionsV2, is it the reason why my code fail to accelerate?
And how about Hexagon(DSP), could you still give me a sample code to use Hexagon to accelerate?
Thank you so much~

**Comment by limdlh** [comment]
@Saduf2019 Hello, why remove assignment? should I add a new issue for Hexagon(DSP) accelerate?

**Comment by limdlh** [comment]
@Saduf2019 Hello, why remove assignment? should I add a new issue for Hexagon(DSP) accelerate?

**Comment by Saduf2019** [comment]
@limdlh 
This issue will be handled by @impjdi  and @lintian06, hence removed my assignment.

**Comment by impjdi** [comment]
I'm not familiar with `TfLiteInterpreterOptions`.  I suggest using the code snippet I pasted above.

**Comment by limdlh** [comment]
@impjdi Does your code pasted above also could used for Hexagon(DSP) ?
If not, could you give me a sample code ?
Now I still want a sample code for Hexagon, not for GPU.

**Comment by impjdi** [comment]
No, I don't use how to use Hexagon the hexagon delegate.  Doesn't it work as documented in https://www.tensorflow.org/lite/performance/hexagon_delegate ?

**Comment by limdlh** [comment]
@impjdi The code sample in https://www.tensorflow.org/lite/performance/hexagon_delegate runs roghly same slowly as CPU.
Should I new another issue in github for hexagon delegate?

**Comment by impjdi** [comment]
yeah, it's a different owner
