### ISSUE TITLE
Old version of CUDA support ?

### ISSUE THREAD

**Issue by gitlabspy** [tensorflow/tensorflow#48405]
Hi, I wonder if possible to release newest/nightly tensorflow-gpu compatible for old version CUDA ( 9.0 10.0). I want to use tf2.4 (or higher) on a CUDA 10.0 machine since the driver version are not compatible with newer version CUDA. Upgrading driver is impossible for some reason and and it's very inconvenient to build from source. 

It's very important to `pip install tensorflow-gpu # maybe with something like +cuda101` to install tensorflow gpu with certain cuda version. Especially when projects are moved to another machine when older version tensorflow can handle newer version tensorflow codes....

Thanks for you guys open source such a great library, I think this feature might be very useful to all users.

**Comment by amahendrakar** [comment]
@gitlabspy,
A similar query was answered in issue [#42895](https://github.com/tensorflow/tensorflow/issues/42895).

Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/42895#issuecomment-685874736) from a member of the TensorFlow team and check if it helps. Thanks!

**Comment by gitlabspy** [comment]
@amahendrakar Thanks for your response. He mentioned new cuda can not be compatible with older version of TF, so there is no way to build new TF (>2.4) for older cuda ?

**Comment by mihaimaruseac** [comment]
To reach the maximum performance available, each version of TF is tied to a specific CUDA version.

You can try compiling from source to get access to other versions of CUDA (newer/older) but you will have to fix compile errors/bugs that result from the mismatch yourself, as we don't have developers to handle every possible combination.
