### ISSUE TITLE
Is SavedModel in tf 1.15 same as SavedModel in tf 2.x from the API prospective?

### ISSUE THREAD

**Issue by pmixer** [tensorflow/tensorflow#48403]
Hi Team,

As it is noted in https://www.tensorflow.org/hub/tf2_saved_model:

**Users of TensorFlow 1 can update to TF 1.15 and then use the same APIs. Older versions of TF1 do not work.**

Does that means there's no difference between SavedModel format of tf 1.15(not tf.1.14 or other versions behind it) and tf 2.x?

Regards,
Zan

**Comment by Saduf2019** [comment]
@pmixer 
There is no significant difference, please let us know if you are facing any issues, else please open this issue in [stackover flow](https://stackoverflow.com/questions/tagged/tensorflow) and move this to closed status as its not a bug or feature request.

**Comment by pmixer** [comment]
@Saduf2019 
Thank you Saduf! That's cool, I'm just trying to verify my assumption before diving into the details for working on the related project. Thx for your support!
