### ISSUE TITLE
Deadlock when setting interop thread thread to 1 with a tf Dataset and tf function

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#48418]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux / colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 2.4.1
- TensorFlow version (use command below):
- Python version: Colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
For test purposes we usually set the nbr of threads to 1 for the interop and intra op threadings. When using the following code (to reduce batch size from an already batched dataset) we get a deadlock.

We only get the deadlock if:
- inter nbr thread set to 1
- and  
-  _slicer is wrapped in tf function.

**Describe the expected behavior**
No deadlocks
**Standalone code to reproduce the issue**
````
import tensorflow as tf
import numpy as np
tf.config.threading.set_inter_op_parallelism_threads(1)
@tf.function
def _slicer(dd, slice_):
    return tf.nest.map_structure(lambda val: val[slice_[0]:slice_[1]], dd)
def get_small_batch_gen(ds: tf.data.Dataset, batch_size):
    def gen_small_batch():
        for batch in ds:
            big_batch_size = tf.nest.flatten(tf.nest.map_structure(lambda x: x.shape[0], batch))
            for i in range(big_batch_size[0] // batch_size):
                yield _slicer(batch, tf.constant([i * batch_size, (i + 1) * batch_size]))
    return tf.data.Dataset.from_generator(gen_small_batch, output_signature=ds.element_spec)
size = 102
ds = tf.data.Dataset.from_tensor_slices(({i: tf.RaggedTensor.from_row_splits(np.random.choice(10, size=size),
                                                                                  tf.range(size + 1))
                                              for i in ['a', 'b', 'c']}, tf.range(size))).batch(10)
next(iter(get_small_batch_gen(ds, 5)))
`````

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jsimsa** [comment]
`tf.data.Dataset.from_generator` uses `PyFunc` op in its implementation, which uses an interop threadpool for its execution. if the Python method that it executes invokes any TF ops, these will need additional interop threadpool. This is unlikely to be changed.

If you would like to run your tests with a singleton interop threadpool, you should avoid using `tf.data.Dataset.from_generator` (or any other source of `PyFunc` such as `tf.py_function` or `tf.numpy_function`).

**Comment by tanguycdls** [comment]
ok thank you for the clarification ! so i'll need to use at least nbr interop thread i have nbr of python generator. 

Would there be any way to make that error more user friendly and explicitely raise instead of the deadlock ?
