### ISSUE TITLE
Having trouble building tf wheel from r2.5 branch

### ISSUE THREAD

**Issue by justkw** [tensorflow/tensorflow#48411]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.5
- Python version: py36
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I'm building  from tf source r2.5 branch, getting the following error while trying to build the wheel:
[91mERROR: Could not find a version that satisfies the requirement tf-estimator<2.6.0,>=2.5.0rc0 (from tf-nightly==2.5.0rc0) (from versions: none)
ERROR: No matching distribution found for tf-estimator<2.6.0,>=2.5.0rc0 (from tf-nightly==2.5.0rc0)

From what I can see in this commit : https://github.com/tensorflow/tensorflow/commit/ecf0809b8f292636b07bcf10db71861709fd2802
has changed the dependency 
from:
 'tf-estimator-nightly == 2.5.0.dev2021032501',
to:
 'tf-estimator >= 2.5.0rc0 , < 2.6.0',

but tf-estimator 2.5.0rc0 doesn't seem to be available.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by alanpurple** [comment]
It looks like a mistypo of tensorflow_estimator, which has 2.5.0rc0

**Comment by geetachavan1** [comment]
https://github.com/tensorflow/tensorflow/pull/48488 has fixed the issue.
