### ISSUE TITLE
Problem on building target with GPU support

### ISSUE THREAD

**Issue by AFAgarap** [tensorflow/tensorflow#4841]
Result of `bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer`:

```
ERROR: /home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/darth/.cache/bazel/_bazel_darth/08554d152596e5a7df399506682a63f3/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 0.097s
```

And yes, I have GPU enabled when I did `sudo ./configure`

**Comment by AFAgarap** [comment]
I installed `oracle-java8-installer`, and did a `sudo apt-get upgrade bazel`. But it said that my GPU was disabled, so I repeated the `./configure`. But it had an error: `ERROR: /home/darth/tensorflow/tensorflow/contrib/tfprof/tools/tfprof/BUILD:22:1: no such package '@linenoise//': Error cloning repository: Unexpected end of file from server caused by Unexpected end of file from server caused by Unexpected end of file from server and referenced by '//tensorflow/contrib/tfprof/tools/tfprof:tfprof'.`

**Comment by AFAgarap** [comment]
@tatatodd Hello?

**Comment by tatatodd** [comment]
@AFAgarap This looks similar to #4105 

Based on that issue, you might try the following:
```
$ bazel clean
$ ./configure # make sure to choose gpu support
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
```

If that doesn't work, please cut-and-paste the result of the above commands, including the exact values you entered for the `./configure` call.  Also include the below information:

---

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

**Comment by jinhou** [comment]
@tatatodd I met the same issue. And I do configure with CUDA enabled. Do you have any solutions for this issue?

$git rev-parse HEAD
8e48ec6ea0492e2cb9fd19c0a2ccf41afc7b4dc6

$bazel version
INFO: $TEST_TMPDIR defined: output root default is '/gruntdata/houge/tmp'.
Found stale PID file (pid=18305). Server probably died abruptly, continuing...
.
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

Thanks

**Comment by jinhou** [comment]
@AFAgarap @tatatodd I found a work around method to fixed this issue in my machine. 
In ./third_party/gpus/cuda_configure.bzl file, there is a function to check whether cuda is enabled, 
`def _enable_cuda(repository_ctx):
  if "TF_NEED_CUDA" in repository_ctx.os.environ:
    enable_cuda = repository_ctx.os.environ["TF_NEED_CUDA"].strip()
    print (enable_cuda)
    return enable_cuda == "1"
  return False
`
In my case, even I run the configure with CUDA enabled. The environment variable "TF_NEED_CUDA" was still no in the list of repository_ctx.os.environ. So It would said CUDA was not enabled when compiled from source. Then I export "TF_NEED_CUDA=1" in my ~/.bashrc. And it compiled successfully. 

So I am not sure whether it works for your case? @AFAgarap

**Comment by AFAgarap** [comment]
I was suspecting that there was some problem with the code or something, but wasn't sure where or which module would it be. Thanks for this, @jihunchoi I'll try it later.

**Comment by AFAgarap** [comment]
``
$ git rev-parse HEAD
``
``
$ 36ebbf1ddc3ed820b7a5572ff4ed8e9bc707b8e5
``

```
$ bazel version
Killed non-responsive server process (pid=12228)
.
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392
```

```
$ /usr/bin/bazel version
Killed non-responsive server process (pid=25627)
.
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```

I have two `bazel` installed because I've read somewhere that `bazel-0.3.1` is the one that works for TF. @tatatodd

**Comment by jihunchoi** [comment]
Hello @AFAgarap, I think you had intended to tag @jinhou but tagged me by mistake :)

**Comment by ChaunceyL** [comment]
@tatatodd 
I have met the same issue.
$ git rev-parse HEAD
73b01567d68d4639d2329deb335ddfcd9c04f87c

$ bazel version
.
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

**Comment by AFAgarap** [comment]
@jihunchoi Sorry, my bad. :grinning:

**Comment by AFAgarap** [comment]
@jinhou Nope, it didn't solve my problem. :disappointed:

**Comment by AFAgarap** [comment]
@jinhou When it is building, it crashes at some point. :disappointed:

**Comment by AFAgarap** [comment]
I have `tensorflow` installed using binary, with CUDA 8.0, and cuDNN 5.0.
Does the binary-installed tensorflow has anything to do with this failure to build from source? @tatatodd @jinhou

**Comment by tatatodd** [comment]
@AFAgarap See related issue #4910

We don't support CUDA 8.0 yet. It will be supported soon. Right now we only officially support 7.0 - 7.5. Please see #2559 which is tracking this. There's also #4895 which encountered this issue on the same version of Ubuntu.

I'm closing this out, but feel free to comment on this issue or file a new issue if you have a different problem.

**Comment by AFAgarap** [comment]
@tatatodd You do not support CUDA 8 yet for building from sources? Because the one I installed using binary pip is working out fine.

**Comment by tatatodd** [comment]
@AFAgarap We plan on CUDA 8 support to come officially in TensorFlow version 0.11rc1.

In general there is no difference in features between our binary and source releases at a particular version.  I.e. our binaries are built out of our sources at a particular version.

In the meantime if you're building from sources, and want to use CUDA 8, you'll need to ensure you have a fresh enough version of the sources, that hasn't introduced some other silly bug.  Once 0.11rc1 has been released you can just use that as a stable point in the codebase.

**Comment by AFAgarap** [comment]
@tatatodd Thank you. Though with the binary installation TensorFlow, I've been able to do `inception`. Is that okay? I mean, is it required to build TensorFlow from sources to use `inception`? I mean, perhaps there are just some "underground" bugs happening to my install that I'm not aware.

**Comment by tatatodd** [comment]
@AFAgarap If the binary TensorFlow that you're using seems to work for Inception, I wouldn't worry about it too much in the short-term.  But I would recommend you upgrade to version 0.11rc1 when it is available.

**Comment by AFAgarap** [comment]
@tatatodd Thank you. Though with the binary installation TensorFlow, I've been able to do `inception`. Is that okay? I mean, is it required to build TensorFlow from sources to use `inception`? I mean, perhaps there are just some "underground" bugs happening to my install that I'm not aware.

**Comment by AFAgarap** [comment]
In the short-term? Why? Will it have a problem? And yes, I'll upgrade to version `0.11rc` as soon as you deploy it.

**Comment by wcardoen** [comment]
I performed a ./configure with GPU enabled, the build did not work.
GPU support will be enabled for TensorFlow
bazel build  -c opt --verbose_failures --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: $TEST_TMPDIR defined: output root default is '/scratch/local/hpcapps/bazel'.
..............
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /scratch/local/hpcapps/bazel/_bazel_hpcapps/9854aab478a0076ff75539c378bcd3e3/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "/scratch/local/hpcapps/bazel/_bazel_hpcapps/9854aab478a0076ff75539c378bcd3e3/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "/scratch/local/hpcapps/bazel/_bazel_hpcapps/9854aab478a0076ff75539c378bcd3e3/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /scratch/local/hpcapps/bazel/_bazel_hpcapps/9854aab478a0076ff75539c378bcd3e3/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 2.299s

I did a bazel clean and a new configure, and:
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer   (see above)
I now got:
INFO: $TEST_TMPDIR defined: output root default is '/scratch/local/hpcapps/bazel'.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /scratch/local/hpcapps/tensorflow/tensorflow/core/kernels/BUILD:271:1: null failed: protoc failed: error executing command bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/local_linux-opt/genfiles/' -I. -Iexternal/protobuf/src -Ibazel-out/local_linux-opt/genfiles/external/protobuf/src ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/external/protobuf/protoc)
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 517.714s, Critical Path: 507.68s

PS: My OS is centos6
Linux kp298 2.6.32-642.6.2.el6.x86_64

Thanks,

Wim

**Comment by abrahamrhoffman** [comment]
@jinhou you are the man! Exporting the environment variable worked for me!

`
export TF_NEED_CUDA="1"

bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --copt=-msse4.1 --copt=-msse3 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package

bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
`

**Comment by hnkulkarni** [comment]
Thanks @jinhou, exporting TF_NEED_CUDA = "1" did the trick for me. Just curious, how did you find this out?

**Comment by mooneyj** [comment]
export TF_NEED_CUDA="1" solved the issue for me also, thanks @jinhou 
My system: Ubuntu 16.10, Cuda 8.0.61, Cudnn8.0, NVIDIA linux 378.13 (.run).

**Comment by MClarkTurner** [comment]
I'll also confirm this works when building from source. I assume this error somehow made it back into the master branch.

**Comment by proximacent** [comment]
This still seems to be an issue. I have Ubuntu 14.04 and **export TF_NEED_CUDA="1"** solved the issue.

**Comment by goldsborough** [comment]
Had to also export `CUDNN_INSTALL_PATH` for Bazel to recognize CuDNN.

**Comment by archenroot** [comment]
Is there any way to enabling the GPU support programatically, but not via some terminal input (Y vs N)?

@goldsborough what is the value of the variable? I suggest it is simply /usr/lib64 (I am on gentoo system):
```
andromeda /var/lib/layman/archenroot/sci-libs/tensorflow # equery f nvidia-cuda-cudnn
 * Searching for nvidia-cuda-cudnn ...
 * Contents of dev-libs/nvidia-cuda-cudnn-7.0:
/usr
/usr/include
/usr/include/cudnn.h
/usr/lib64
/usr/lib64/libcudnn.so -> libcudnn.so.7
/usr/lib64/libcudnn.so.7 -> libcudnn.so.7.0.4
/usr/lib64/libcudnn.so.7.0.4
/usr/lib64/libcudnn_static.a

```

**Comment by archenroot** [comment]
Ok, small update, I had to export some other variable, here is whole content from Ebuild, important is phase configure where I export related variables:
```
# Copyright 2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=5
PYTHON_COMPAT=( python{2_7,3_4} pypy )

inherit eutils multiprocessing distutils-r1 git-r3

DESCRIPTION="Library for Machine Intelligence"

HOMEPAGE="https://www.tensorflow.org/"
SRC_URI=""
EGIT_REPO_URI="https://github.com/tensorflow/tensorflow"
EGIT_COMMIT="c9568f1ee51a265db4c5f017baf722b9ea5ecfbb"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~arm ~hppa ~ppc ~ppc64 ~sparc ~x86 ~x86-fbsd ~amd64-linux ~x86-linux ~x86-macos"
IUSE="-cuda -opencl"
RESTRICT="primaryuri"

RDEPEND="
	>=dev-python/numpy-1.11.2-r1
	>=dev-python/six-1.10.0
	cuda? (
          >=dev-libs/nvidia-cuda-cudnn-7.0
	  >=dev-util/nvidia-cuda-toolkit-8.0.61
          >=x11-drivers/nvidia-drivers-3.78.13
        )
"

DEPEND="
	dev-python/setuptools
	>=dev-util/bazel-0.7.0[tools]
	>=dev-java/oracle-jdk-bin-1.8.0.152-r1
	>=dev-python/markdown-2.6.9
	>=dev-python/werkzeug-0.12.2
	>=dev-python/bleach-1.5.0
	>=dev-python/protobuf-python-3.4.1
	>=dev-python/pip-9.0.1-r1
	>=dev-python/wheel-0.29.0
	>=dev-lang/swig-3.0.12
	${RDEPEND}
"

#src_prepare() {
	#sed -i -e 's/protobuf == 3.0.0a3/protobuf >= 2.6.0/g' \
	#tensorflow/tools/pip_package/setup.py
#}

src_configure() {
	
	export CUDNN_INSTALL_PATH="/usr/lib64"
	export TF_NEED_CUDA="1"
	export TF_CUDA_VERSION="9.0"
	export TF_CUDNN_VERSION="7"
	yes "" | ./configure

	cat > CROSSTOOL << EOF
tool_path {
	name: "gcc"
	path: "${CC}"
}
tool_path {
	name: "g++"
	path: "${CXX}"
EOF

	echo "Will build with $(makeopts_jobs) jobs"

}

src_compile() {
	addwrite /proc/self
	# Added from bazel ebuild.. I am blind here as I don't understand deeply bazel itself :-)
	addpredict /proc
	elog "Compile Phase - Starting"

	local JAVA_HOME_DECL="$(java-config --print oracle-jdk-bin-1.8 | grep JAVA_HOME)"
	eval "export $JAVA_HOME_DECL"

	# Add /proc/self to avoid a sandbox breakage
	local -x SANDBOX_WRITE="${SANDBOX_WRITE}"
	echo "SANDBOX_WRITE=$SANDBOX_WRITE"

	elog "Compile Phase - SANDBOX_WRITE"

	cat > bazelrc << EOF
startup --batch
build --spawn_strategy=standalone --genrule_strategy=standalone
build --jobs $(makeopts_jobs)
EOF
	export BAZELRC="$PWD/bazelrc"
	elog "Compile Phase - Bazel configured"
	bazel build \
	 --spawn_strategy=standalone --genrule_strategy=standalone \
	 --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
	 elog "Compile Phase - Bazel build finished"
}

src_install() {
	elog "Install Phase - Starting"
	bazel-bin/tensorflow/tools/pip_package/build_pip_package "$PWD/tensorflow_pkg"
	elog "Install Phase - PIP package finished"
	local ALFA="$(find /tmp/empty* -type f -exec sh -c 'echo $(basename {})' \;)"
	local TENSORFLOW_WHEEL_FILE="$(find $PWD/tensorflow_pkg/tensorflow* -type f -exec sh -c 'echo $(basename {})' \;)"
	pip install --root "${ED}" "$PWD/tensorflow_pkg/$TENSORFLOW_WHEEL_FILE"
	elog "Install Phase - PIP install finished"
	rm -rf "${ED}"/usr/lib*/python*/site-packages/google/protobuf
	elog "Install Phase - removal of some files"
}
```

And this works, or in minimum I was able to finish compilation and installation process with CUDA 9 and CUDNN 7, now I will do some hello world test....
