### ISSUE TITLE
tf.data.experimental.enable_debug_mode() doesn't enable breakpoint

### ISSUE THREAD

**Issue by cgebbe** [tensorflow/tensorflow#48429]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Desktop
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v1.12.1-53831-ga8b6d5ff93a 2.5.0-rc0
- Python version: Python 3.6.8 
- CUDA/cuDNN version: CPU
- GPU model and memory: CPU

**Describe the current behavior**

```
import tensorflow as tf

tf.data.experimental.enable_debug_mode()
tf.config.run_functions_eagerly(True)


def func(x):
    x = x + 1  # BREAKPOINT HERE
    return x


dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.map(func)
# dataset = dataset.map(lambda x: tf.py_function(func, [x], tf.int32))  # doesn't work either
for item in dataset:
    print(item)

```

The breakpoint is not hit. (using pycharm professional 2020.3 )

**Describe the expected behavior**

I expect that the breakpoint is hit

**Comment by Saduf2019** [comment]
@cgebbe 
I ran your code on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/de6e076dfbc72fcc7862620fc634908e/untitled583.ipynb), i face a different error on 2.4.

**Comment by jsimsa** [comment]
@jayxiaojieshi could you please help investigate this issue? thank you

**Comment by jayxiaojieshi** [comment]
I have tested it with installing tf-nightly and adding break point to the source code in post-mortem debug mode with pdb.
And the behavior can be re-produced. If we add break point within the function, it is not enabled, while if we add break point in other places (like add a simple print "hello, world" line), it is enabled.

**Comment by jayxiaojieshi** [comment]
Also I have tried with deleting both lines "tf.data.experimental.enable_debug_mode()
tf.config.run_functions_eagerly(True)" or only deleting the line "tf.data.experimental.enable_debug_mode()", the break point within the function is not enabled. 
Does that suggest the behavior has nothing to do with tf.data debug mode?

**Comment by jsimsa** [comment]
@jayxiaojieshi are you saying that the [following example](https://www.tensorflow.org/guide/effective_tf2#use_tfconfigexperimental_run_functions_eagerly_when_debugging) works when for a tf.function but does not work for tf.data user-defined function (even when `tf.data.experimental.enable_debug_mode()`  is called)?

**Comment by jayxiaojieshi** [comment]
Yeah, for tf.function, during the process of execution the break point within the function will be enabled only once, while without "@tf.function" it will not be enabled.

**Comment by jayxiaojieshi** [comment]
> Yeah, for tf.function, during the process of execution the break point within the function will be enabled only once, while without "@tf.function" it will not be enabled.

For above comments I am testing with post-mortem debug mode with pdb, with "python -m pdb script.py" and setting break points with "break script.py:XXX". 
Actually for the [example](https://www.tensorflow.org/guide/effective_tf2#use_tfconfigexperimental_run_functions_eagerly_when_debugging) you mentioned, both tf.function or user-defined function work well. The break point will be enabled every time the function is called.

**Comment by jsimsa** [comment]
@jayxiaojieshi could you please provide a code snippet that updates the example provided by the user to illustrate how can pdb be used together with `tf.data.experimental.enable_debug_mode()` to insert breakpoints into tf.data user-defined functions and also update the `tf.data.experimental.enable_debug_mode()` documentation with this example? thanks

**Comment by jayxiaojieshi** [comment]
Sure, think the code below will work. 
cmd to run: python script.py

```
import tensorflow as tf
import pdb

tf.data.experimental.enable_debug_mode()
tf.config.run_functions_eagerly(True)

def func(x):
    pdb.set_trace()
    x = x + 1
    return x


dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.map(func)

for item in dataset:
    print(item)
```

**Comment by jsimsa** [comment]
It does not work for me. While first invocation of `func` (which occurs during tracing) triggers the breakpoint as expected, the subsequent invocation of `func` (which occurs during input pipeline execution) fails with `ValueError: signal only works in main thread`. Can you please confirm that you have verified that all four invocations of `func` that your example would exercise trigger the breakpoint?

**Comment by jayxiaojieshi** [comment]
Interesting. It works well on my side. With first stop shows:
```
->  x = (ag__.ld(x)+1)
```

Other three shows:
```
-> x = x+1
```

**Comment by jayxiaojieshi** [comment]
Just tested different version of Python. Python 3.8 is required to see the desired behavior, while for Python 3.6, 3.7 there will be errors.

**Comment by jsimsa** [comment]
Thank you Jay. I was running the repro with an internal build of TensorFlow that uses Python 3.6, which explains the error.

I was able to find a solution to the problem I was encountering. For the example to work with Python 3.6 or Python 3.7, one has to do `pdb.Pdb(nosigint=True).set_trace()` instead of `pdb.set_trace()`.

So to summarize, the following program illustrates how to add breakpoints to tf.data user-defined functions:

```
import pdb
import tensorflow as tf

tf.data.experimental.enable_debug_mode()

def func(x):
    pdb.Pdb(nosigint=True).set_trace()
    x = x + 1
    return x


dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
dataset = dataset.map(func)

for item in dataset:
    print(item)
```

@cgebbe please let us know if this addresses your question and if it does, feel free to close the issue. Thanks.

**Comment by cgebbe** [comment]
@jsimsa and @jayxiaojieshi : Thank you a lot for the support! he last example below is working for me (haven't tested the other ones).

One big question: Is it somehow possible to trigger the Pycharm Debugger instead of PDB? The former one is arguably more convenient...

**Comment by jsimsa** [comment]
If PDB works but PyCharm does not, please contact the PyCharm team for help with this.

**Comment by cgebbe** [comment]
One last question: Can you explain why the parameter nosigint=True is necessary? 

Based on the explanation from https://docs.python.org/3/library/pdb.html#pdb.Pdb, it seems to have something to do with Pressing Ctrl+C, so nothing necessary for the task at hand.

However, without it, I get the following error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: signal only works in main thread
....
ValueError: signal only works in main thread
	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
```

**Comment by jsimsa** [comment]
1) When running in debug mode, for technical reasons, tf.data executes user-defined functions using a background thread.
2) The implementation of `pdb.set_trace()` uses `signal`, which as per the error message is not supported in the main thread. Either Python 3.8 removed the use of `signal` in `pdb` or added support for `signal` in background threads.

**Comment by dniku** [comment]
In PyCharm, one can trigger a breakpoint in a function called by `Dataset.map()` by adding the following line within that function:

```
import pydevd; pydevd.settrace()
```

Also note that you will **not** need to install `pydevd` separately, as it is bundled with PyCharm. Simply add that line and run debugging.

(found in [this](https://stackoverflow.com/a/59346218/1214547) StackOverflow answer)
