### ISSUE TITLE
some qunstions of nnapi delegate

### ISSUE THREAD

**Issue by ToBigboss** [tensorflow/tensorflow#48426]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I don't quite understand the relationship between libtensorflowlite.so and libnnapi_delegate.so，if I only nnapi delegate, is it OK to just use libnnapi_delegate.so?

**Comment by Saduf2019** [comment]
@ToBigboss 
Your question is not clear, are you facing any error, please share error logs in case you are facing any such issues, also please fill the template for us to analyse the issue faced.

**Comment by ToBigboss** [comment]
> @ToBigboss
> Your question is not clear, are you facing any error, please share error logs in case you are facing any such issues, also please fill the template for us to analyse the issue faced.

I want to build tflite-nnapi delegate lib with c/c++ api，I compiled it using the following command line：
bazel build -c opt --config=android_arm64 //tensorflow/lite/delegates/nnapi:nnapi_delegate
and libnnapi_delegate.so is compiled in bazal-bin，but I don't see libtensorflowlite.so, so I compile  libtensorflowlite.so with the following command line: 
bazel build --cxxopt='--std=c++11' //tensorflow/lite:lib tensorflowlite.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a --verbose_ failures
There's only libtensorflowlite.so in the bazel-bin.

my qunstion is:
1. if i want to use nnapi delegate, Is it OK to just use libnnapi_delegate.so? do I need library libtensorflowlite.so?
2. can you provide sample code for using nnapi delegate with c/c++ api?

**Comment by karimnosseir** [comment]
Jared, can you please help with this issue.

Thanks

**Comment by jdduke** [comment]
Hi @ToBigboss . Can you add more details about your deployment environment? In particular:
- What build system are you using for your Android app/deployment?
- Are you already using TFLite via C++ in your app? If so, were you building from source? Or using prebuilt binaries?

A few notes to your equestions:

> if i want to use nnapi delegate, Is it OK to just use libnnapi_delegate.so? do I need library libtensorflowlite.so?

The NNAPI delegate is only useful with the core TFLite library, so you would need both. However, we haven't historically distributed the NNAPI delegate as a separate library on Android (for the prebuilt libraries), so we don't have the necessary build rule to produce a *standalone* NNAPI delegate `.so` that is fully self-contained (the libnnapi_delegate.so artifact you see isn't self-contained).

> can you provide sample code for using nnapi delegate with c/c++ api?

I'll file an internal feature request for this. We recently [published a sample](https://github.com/tensorflow/examples/tree/master/lite/examples/super_resolution/android) showing how to use the C API for the prebuilt libraries we publish for Android. If we extended that to show how to use the NNAPI delegate, would that be useful?

**Comment by ToBigboss** [comment]
> Hi @ToBigboss . Can you add more details about your deployment environment? In particular:
> 
> * What build system are you using for your Android app/deployment?
> * Are you already using TFLite via C++ in your app? If so, were you building from source? Or using prebuilt binaries?
> 
> A few notes to your equestions:
> 
> > if i want to use nnapi delegate, Is it OK to just use libnnapi_delegate.so? do I need library libtensorflowlite.so?
> 
> The NNAPI delegate is only useful with the core TFLite library, so you would need both. However, we haven't historically distributed the NNAPI delegate as a separate library on Android (for the prebuilt libraries), so we don't have the necessary build rule to produce a _standalone_ NNAPI delegate `.so` that is fully self-contained (the libnnapi_delegate.so artifact you see isn't self-contained).
> 
> > can you provide sample code for using nnapi delegate with c/c++ api?
> 
> I'll file an internal feature request for this. We recently [published a sample](https://github.com/tensorflow/examples/tree/master/lite/examples/super_resolution/android) showing how to use the C API for the prebuilt libraries we publish for Android. If we extended that to show how to use the NNAPI delegate, would that be useful?

_1.What build system are you using for your Android app/deployment?_
phone：xiaomi 11
CPU：snapdragon 888
android 11
MIUI 12.0.16

_2.Are you already using TFLite via C++ in your app? If so, were you building from source? Or using prebuilt binaries?_
yes，i want to use TFLite via c++ api，and i build libtensorflow.so and libnnapi_delegate.so from source with bazel. I'm trying to use cmake to compile libtensorflow.so and libnnapi_delegate.so into libtflite_nnapi.so，but the generated library is too large.

**Comment by alexanderfrey** [comment]
Have you already been able to make use of the hexagon dsp ? I'm not quite sure if nnapi or the hexagon delegate is the way to go. For what I learned the hexagon 1.21 version does not yet support the snapdragon 888.
