### ISSUE TITLE
new soc_id support for hexagon delegate

### ISSUE THREAD

**Issue by jklloyd23** [tensorflow/tensorflow#48435]
We are developing products based on the Qualcomm Snapdragon 865 and have been using the hexagon delegate to use the dsp on the SXR2130 variant with soc_id 356. Recently Qualcomm has migrated us to the QCS8250 variant of the 865, exact same processor, just differentiated by longer term support in the IOT group. This part has soc_id 481 which appears to not be recognized by the hexagon delegate. It looks like there needs to be an entry for 481 in the SocSkelTable that matches 356.

How does that happen? Does Qualcomm notify Google of new soc_id's and how does a new release happen? We are also working this through our Qualcomm contacts. If this is already known and a release is going to happen please provide any timetable information for a new release.

Thank you.

Jay

**Comment by abattery** [comment]
@karimnosseir could you take a look at this question?

**Comment by karimnosseir** [comment]
@jklloyd23 Happy to add it np.
Will update you when new version is released.

**Comment by karimnosseir** [comment]
libhexagon_interface.so is updated with the soc 481 now enabled.
Can you please try again by fetching from master branch.

**Comment by karimnosseir** [comment]
Closing please reopen if there are issues.

Thanks
