### ISSUE TITLE
MultiWorkerMirroredStrategy:tensorflow.python.framework.errors_impl.InternalError: x root error(s) found.

### ISSUE THREAD

**Issue by Mullich123** [tensorflow/tensorflow#48439]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:source
-   **TensorFlow version (use command below)**:2.3.3
-   **Python version**:3.6
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:7.3.1
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
tensorflow.python.framework.errors_impl.InternalError: 5 root error(s) found.
  (0) Internal:  Missing 1-th output from node replica_3/sequential/dropout/dropout/Dropout (defined at /threading.py:916) 
	 [[GroupCrossDeviceControlEdges_1/Identity_7/_203]]
  (1) Internal:  Missing 1-th output from node replica_3/sequential/dropout/dropout/Dropout (defined at /threading.py:916) 
  (2) Internal:  Missing 1-th output from node replica_3/sequential/dropout/dropout/Dropout (defined at /threading.py:916) 
	 [[GroupCrossDeviceControlEdges_0/SGD/SGD/update_1_1/Const/_147]]
  (3) Internal:  Missing 1-th output from node replica_3/sequential/dropout/dropout/Dropout (defined at /threading.py:916) 
	 [[GroupCrossDeviceControlEdges_2/SGD/SGD/update_0/Const/_163]]
  (4) Internal:  Missing 1-th output from node replica_3/sequential/dropout/dropout/Dropout (defined at /threading.py:916) 
	 [[div_no_nan_1/_119]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_7311]

Function call stack:
train_function -> train_function -> train_function -> train_function -> train_function

The above is the error message.I don't know the cause of it.

### Source code / logs
import json
import math
import os
import sys
import numpy as np
import unet

os.environ["CUDA_VISIBLE_DEVICES"] = "0, 1, 2, 3"
os.environ.pop('TF_CONFIG', None)
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

def build_and_compile_cnn_model():
    model = unet.build()
    model.compile(
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-9))
    return model

def _is_chief(task_type, task_id):
    # Note: there are two possible TF_CONFIG configuration.
    # 1) In addition to worker tasks, a chief task type is use;
    # in this case, this function should be modified to
    # return task_type == 'chief'.
    # 2) Only worker task type is used; in this case, worker 0 is
    # regarded as the chief. The implementation demonstrated here
    # is for this case.
    # For the purpose of this colab section, we also add task_type is None
    # case because it is effectively run with only single worker.
    return (task_type == 'worker' and task_id == 0) or task_type is None

def get_temp_dir(dirpath, task_id):
    base_dirpath = 'workertemp' + str(task_id)
    temp_dir = os.path.join(dirpath, base_dirpath)
    tf.io.gfile.makedirs(temp_dir)
    return temp_dir

def write_filepath(filepath, task_type, task_id):
    dirpath = os.path.dirname(filepath)
    base = os.path.basename(filepath)
    if not _is_chief(task_type, task_id):
        dirpath = get_temp_dir(dirpath, task_id)
    return os.path.join(dirpath, base)

if __name__ == '__main__':
    # I use default TFConfigClusterResolver,and set the environment variable below
    # In total two processes are opened and 'index' of the other one is '1'
    # like this
    tf_config = {
        'cluster': {'worker': ['10.1.11.60:15536', '10.1.11.59:19203']},
        'task': {'type': 'worker', 'index': 0}
    }
    os.environ['TF_CONFIG'] = json.dumps(tf_config)

    batch_size = 4

    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with strategy.scope():
        test_model = build_and_compile_cnn_model()
    # I use handwriting dataset
    train_data = np.load('train_data.npy')
    train_label = np.load('train_label.npy')
    # train_data shape is (60000, 28, 28, 1)
    # Only use the first 1000 pictures to train the model
    train_data = train_data[0:1000]
    train_label = train_label[0:1000]
    len_data = len(train_data)
    len_label = len(train_label)
    
    # Abandon partial batch
    steps_per_epoch = math.floor(len_data / batch_size)
    
    # Set save path just like tutorial
    checkpoint_dir = "./ckpt"
    checkpoint_name = "./ckpt/chief_ckpt"
    if not os.path.exists(checkpoint_dir):
        os.makedirs(checkpoint_dir)
    
    tf_config = json.loads(os.environ['TF_CONFIG'])
    task_type = tf_config['task']['type']
    task_rank = tf_config['task']['index']
    write_model_path = write_filepath(checkpoint_name, task_type, task_rank)
    
    callbacks = [tf.keras.callbacks.ModelCheckpoint(filepath=write_model_path + '_{epoch:04d}.h5',
                                                    save_best_only=False,
                                                    save_weights_only=True,
                                                    save_freq='epoch')]
    
    # Model loads latest weights
    checkpoints = [checkpoint_dir + '/' + name for name in os.listdir(checkpoint_dir) if name.endswith('.h5')]
    if checkpoints:
        latest_checkpoint = max(checkpoints, key=os.path.getctime)
        test_model.load_weights(latest_checkpoint)
    
    test_model.fit(x=train_data,
                   y=train_label,
                   batch_size=batch_size,
                   epochs=3,
                   steps_per_epoch=steps_per_epoch,
                   callbacks=callbacks,
                   verbose=1 if task_rank == 0 else 0)
    
unet.py:
from tensorflow.keras import layers
from tensorflow.keras.layers import Reshape
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras import *
import tensorflow as tf

def build():
    model = Sequential()
    model.add(layers.Conv2D(14, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv1", input_shape=(28, 28, 1)))
    model.add(layers.MaxPool2D(pool_size=(2, 2), name="pool1"))
    model.add(layers.Conv2D(28, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv2_1"))
    model.add(layers.Conv2D(28, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv2_2"))
    model.add(layers.MaxPool2D(pool_size=(2, 2), name="pool2"))
    model.add(layers.Conv2D(56, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv3_1"))
    model.add(layers.Conv2D(56, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv3_2"))
    model.add(layers.MaxPool2D(pool_size=(2, 2), name="pool3"))
    model.add(layers.Conv2D(112, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv4_1"))
    model.add(layers.Conv2D(112, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv4_2"))
    model.add(layers.Dropout(0.5))
    model.add(layers.MaxPool2D(pool_size=(2, 2), name="pool4"))
    model.add(layers.Conv2D(224, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv5_1"))
    model.add(layers.Conv2D(224, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv5_2"))
    model.add(layers.Dropout(0.5))
    model.add(layers.Conv2DTranspose(112, 2, padding='same',activation='relu',kernel_initializer='he_normal',name='up6'))
    model.add(layers.Conv2D(112, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv6_1"))
    model.add(layers.Conv2D(112, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv6_2"))
    model.add(layers.Conv2DTranspose(256,2 , padding='same',activation='relu',kernel_initializer='he_normal',name='up7'))
    model.add(layers.Conv2D(56, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv7_1"))
    model.add(layers.Conv2D(56, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv7_2"))
    model.add(layers.Conv2DTranspose(28, 2, padding='same',activation='relu',kernel_initializer='he_normal', name='up8'))
    model.add(layers.Conv2D(28, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv8_1"))
    model.add(layers.Conv2D(28, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv8_2"))
    model.add(layers.Conv2DTranspose(64,2 , padding='same',activation='relu',kernel_initializer='he_normal',name='up9'))
    model.add(layers.Conv2D(14, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv9_1"))
    model.add(layers.Conv2D(14, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv9_2"))
    model.add(layers.Conv2D(2, 3, activation='relu', padding='same', kernel_initializer='he_normal',
    name="conv9_3"))
    model.add(layers.Conv2D(2, 1, activation='sigmoid', padding='same', kernel_initializer='he_normal',
    name="conv10"))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.add(Reshape((10,)))
    return model

**Comment by Mullich123** [comment]
Is someone there?I badly need your help!!!!

**Comment by amahendrakar** [comment]
@Mullich123,
On running the given code snippet, I am facing an error stating `AttributeError: module 'unet' has no attribute 'build'`. 

In order to reproduce the issue reported here, could you please provide a minimal code snippet and the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please update TensorFlow to the latest stable version **TF v2.4.1** with **CUDA 11.0**, **cuDNN 8.0** and check if you are facing the same error. Thanks!

**Comment by Mullich123** [comment]
Thanks for your debugging!Well,I just can't understand the meaning of this error,could you tell me how the error happens?

**Comment by amahendrakar** [comment]
@Mullich123,
Without a reproducible code it would be difficult for us to determine the source of the error. 

Could you please provide a minimal code snippet, which we can run at our end and debug the issue. Thanks!

**Comment by Mullich123** [comment]
I've been updated my issues and file below is trainset I use which has been preprocessed.
[hand_trainset.zip](https://github.com/tensorflow/tensorflow/files/6316862/hand_trainset.zip)

**Comment by nikitamaia** [comment]
Hi @Mullich123, can you please make sure that your code is fully formatted? Copy and pasting unformatted code can lead to lots of errors and makes it more difficult for us to reproduce and debug the issue. Thanks!

Also, please try running your code with `tf.distribute.get_strategy()` instead of `MultiWorkerMirroredStrategy` and let me know what happens.

**Comment by Mullich123** [comment]
Wonderful, it runs normally with tf.distribute.get_strategy()!!!!!!So why it is?
My code is completely from the official tutorial:Multi-worker training with Keras.
I make it just by change 'strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()'
to 'strategy = tf.distribute.get_strategy()'.

**Comment by nikitamaia** [comment]
`get_strategy()` is the default strategy. It implements the `tf.distribute.Strategy` interface but is a pass-through and provides no actual distribution. I was curious to see the results with this strategy because it helps to isolate where the issue is. If you can reformat your code so that it's properly indented, etc, I can try to reproduce the error on my end to help you debug.

**Comment by Mullich123** [comment]
Well, I swear I do reformat my code and it looks normal with indentations in edit window.But it comes out like above.

**Comment by nikitamaia** [comment]
Can you put it in a colab notebook?

**Comment by Mullich123** [comment]
Sorry,I ...... don’t know how to use colab notebook.Here is my code:
[unet_code.zip](https://github.com/tensorflow/tensorflow/files/6348057/unet_code.zip)

**Comment by nikitamaia** [comment]
I don't see any obvious issues with your code. Can you provide a small dataset so I can try to reproduce the issue?

I would also suggest trying to upgrade to 2.4 as MultiWorkerMirroedStrategy moved out of experimental in 2.4 so you can use `tf.distribute.MultiWorkerMirroredStrategy` and you don't need to worry about setting the steps per epoch either.

Can you also try running without the callbacks and let me know what happens?

**Comment by Mullich123** [comment]
I've given you my dataset above,don't you see it?

**Comment by nikitamaia** [comment]
Yes, I see the dataset now. Thanks, I will try to reproduce this when I get a chance. In the meantime did you try the two suggestions in my previous comment?
