### ISSUE TITLE
Converting training loop to compilable Keras model

### ISSUE THREAD

**Issue by arunraja-hub** [tensorflow/tensorflow#48436]
I was recently going through this TF tutorial: https://www.tensorflow.org/tutorials/text/nmt_with_attention
 How do I convert the [training loop](https://www.tensorflow.org/tutorials/text/nmt_with_attention#training) in this tutorial to a Keras model which I can then compile using model.compile?

It is especially the variable input lengths and for loop that it is making this challenging

**Comment by Saduf2019** [comment]
@arunraja-hub 
Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!

**Comment by arunraja-hub** [comment]
@Saduf2019 I have asked this question on Stackoverflow (https://stackoverflow.com/questions/66629176/convert-training-loop-to-compilable-tf-model) a few weeks ago but there is no reply
So I posted here
If you can help that would be great
