### ISSUE TITLE
Tensorboard - Alphabetic ordering of Runs in Graph tab

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#4844]
In all the tabs in tensorboard, the different runs are neatly ordered. However, this is not the case for the Graph tab. See screenshot.
I'm going crosseyed looking for the correct model each time.
![image](https://cloud.githubusercontent.com/assets/7721540/19213241/c1de13a4-8d6e-11e6-9fcb-68c98f743a9f.png)

**Comment by jart** [comment]
Thanks for reporting this. I just wrote up a change internally fixing it. It should get released in the near future.
