### ISSUE TITLE
Broken link at tf.keras.callbacks.TensorBoard in docs page

### ISSUE THREAD

**Issue by alphaX86** [tensorflow/tensorflow#48458]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

URL(s) with the issue: 
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard

## Description of issue (what needs changing): 
The link needs to be changed or removed

### Submit a pull request?
Yes, here it is #48457 

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by alphaX86** [comment]
This issue is a remake of #48714 (I can't tag it as it became stale) but I've made a PR regarding this too. Please refer it

**Comment by mihaimaruseac** [comment]
#48714 does not exist. Was that a typo?

**Comment by alphaX86** [comment]
It was marked stale and closed abruptly. But the error is the link under `embeddings.metaData` doesn't exist and throws a 404 error

**Comment by alphaX86** [comment]
Oh ok wait... I'll edit the comment and tag the issue

**Comment by alphaX86** [comment]
It's #48174 sorry ma bad... Thanks @mihaimaruseac for pointing out

**Comment by rmothukuru** [comment]
@alphaX86,
Thank you for providing the [reference link](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard).

#48174 is not a Pull Request but is an issue. I will submit a fix to correct the broken link. Can you please let me know if I can close this issue as it is already being tracked in #48174? Thanks!

**Comment by alphaX86** [comment]
Alright! You can close this and I'll reference this in my PR. Thanks @rmothukuru

**Comment by rmothukuru** [comment]
@alphaX86,
You mean to say you have already created a PR for this change? If so, can you please share the PR number? Thanks!

**Comment by rmothukuru** [comment]
@alphaX86,
Thank you for the confirmation. Closing this issue. Thanks!
