### ISSUE TITLE
Manipulate Input/Output of TF model 

### ISSUE THREAD

**Issue by mrjoelc** [tensorflow/tensorflow#48452]
### 1. System information

- Mac OS 11.2.3
- TensorFlow 2.4.1 from COLAB
- Android 10
- MLKit by Google object-detection-custom:16.3.1

### 2. The problem 

I need to manipulate TensorFlow models to make them compatible with MLKit by Google for my Android Application.
A TFlite model is compatible with MLKit if the Tensors are like that:
INPUT
- The model must have only one input tensor with the following constraints:
- The data is in RGB pixel format.
- The data is UINT8 or FLOAT32 type. If the input tensor type is FLOAT32, it must specify the NormalizationOptions by attaching Metadata.
- The tensor has 4 dimensions : BxHxWxC, where: B is the batch size. It must be 1 (inference on larger batches is not supported). W and H are the input width and height. C is the number of expected channels. It must be 3.

OUTPUT
- The model must have at least one output tensor with N classes and either 2 or 4 dimensions: (1xN) , (1x1x1xN)

With this TFlite model [ssd_mobilenet_v1](https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/metadata/2)
Currently when I use a model with different predicted output (The problem is mainly in the output), I have the this error:
` com.google.android.gms.tasks.RuntimeExecutionException: com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
` 

I'm new to TensorFlow but I know that TF models can be converted using the TFlite converter but I don't know how to use for manipulating the Input/Ouput. Can someone explain me how to interpret the commands to give to the converter?

#### Other Infos

TF model to convert: [SSD MobileNetV2](https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2). From all the outputs I need only this: "detection_scores: a tf.float32 tensor of shape [N] containing detection scores."

**Comment by abattery** [comment]
@mrjoelc  Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.

**Comment by mrjoelc** [comment]
Well currently I'm working with Android and MLKit so for me is difficult to give you something to replicare the issue.
The only thing I can provide you is this [colab](https://colab.research.google.com/drive/125ifeqPU4hHo9On7mDiZkkC48Zi_h3PR?usp=sharing)
Here I try to convert the model from format TF2 to TFlite.

How can I set the output tensor to be like 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1)?
And how can I see the output tensor of the .tflite after successfully conversion?
I know this is possible but I don't know who to do it.

**Comment by abattery** [comment]
You can set the batch size by wrapping the model with the concrete function, e.g.,

```
tf.function(input_signature=(tf.TensorSpec(shape=[1, None,None,3]))
def batch_size_one_model_func(input):
  return original_model(input)

converter = tf.lite.TFLiteConverter.from_concrete_functions([batch_size_one_model_func.get_concrete_function()])
...
```

For the output tensor, you can add additional TF operators to expand dims, e.g., tf.ExpandDims.

**Comment by mrjoelc** [comment]
I'm sorry, I may not have been able to express myself.

What I need is to take an SSD type model and convert it into an image classifier. To do that I need to change the output tensor. In general the output tensor of a SSD consist [bounding boxes][scores of bounding boxes][the categories of the detected boxes][#detections] I only need the [scores of bounding boxes] (in my case will be only 1 score for the single image). So I need to save the model in TFlite format with an output [1xN] or [1x1x1xN]

it is possible?

**Comment by pjpratik** [comment]
Hi @mrjoelc I was checking if this is still an issue.

One way is to get the output tensor that contains the detection scores and create a new model that takes the same input as the SSD model but only outputs the detection scores and the convert the same into TFLite.

Also, the TFLite provides a way to use custom models. Please check the [Model Customization](https://www.tensorflow.org/lite/examples/object_detection/overview#model_customization) and also a way of TF2 object detection models to convert into TF Lite [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md#running-tf2-detection-api-models-on-mobile) and let us know if it helps.

Thanks.
