### ISSUE TITLE
Integrating Metal API on iOS?

### ISSUE THREAD

**Issue by tachim** [tensorflow/tensorflow#4846]
Any plans to use the Metal API on iOS? E.g. https://developer.apple.com/reference/metalperformanceshaders/mpscnnconvolution.

**Comment by jart** [comment]
We don't officially support iOS. We have community supported examples that allow TensorFlow to be used on iOS in CPU mode. Our GPU support is achieved on both Linux and OS X using CUDA. So it seems unlikely that we would integrate with the Metal API. @wicke might have thoughts on this.

See also: #491

**Comment by bryant1410** [comment]
There's [bender](https://github.com/xmartlabs/Bender), that provides an API on top of Metal to build and run neural nets. It also supports running TensorFlow models.
