### ISSUE TITLE
Error: Invalid argument: Quantized tensors must have non-zero scales

### ISSUE THREAD

**Issue by DemolationPeter** [tensorflow/tensorflow#48463]
Hi, 

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): Nvidia docker image (TF1.15)

### 2. Code

[model.zip](https://github.com/tensorflow/tensorflow/files/6292072/model.zip)

**Transformation from Checkpoints (used scripts from the Object detection API, see model.zip)**

```
python export_tflite_ssd_graph.py --pipeline_config_path=/Studienarbeit/tensorflow_od/models/Variation79/mobilnetv2_variation79.config --trained_checkpoint_prefix=/Studienarbeit/tensorflow_od/models/Variation79/model_checkpoints/model.ckpt-176720 --output_directory=exported-models/Variation79    --add_postprocessing_op=true
```

```
tflite_convert --graph_def_file=/Studienarbeit/tensorflow_od/exported-models/Variation79/tflite_graph.pb  --output_file=/Studienarbeit/tensorflow_od/exported-models/Variation79/detect.tflite --input_shapes=1,360,640,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  --inference_type=QUANTIZED_UINT8  --mean_values=128 --std_dev_values=127 --allow_custom_ops
```

### 3. Failure after conversion
I'm trying to convert a QAT trained Model from the TF1 Object Detection API (MobileNetV2-SSDLite) into a working model for the USB Edge TPU. It is working on some models fine but on others I get the following error when I try to convert the .tflite model into a .tflite model for the TPU.  I used the Command Line tool.

```
Edge TPU Compiler version 15.0.340273435
loc("BoxPredictor_4/BoxEncodingPredictor/Conv2D_bias"): error: Invalid argument: Quantized tensors must have non-zero scales
error: could not translate function : Quantized tensors must have non-zero scales
```
I can see in Netron that the Graph contains for the Bias no quantization term. 
In this issue #https://github.com/tensorflow/tensorflow/issues/46334  they found a solution or a work around with the option _(converter._experimental_new_quantizer=True)_. 
Unfortunatly it is just working with newer tf2 versions but i use tf1.15. 

**Question:**

- Is there a other solution to solve the error?
- Can I use models trained with tf1.15 and convert them in e.g. tf2.5.0 with the option _(converter._experimental_new_quantizer=True)_?

### 5. Extra Information

Here you can see that the quantization conversion term is missing for the Bias. For alle the other Conv2D there are quantization terms for the BIAS values.
![error_netron](https://user-images.githubusercontent.com/74291692/114309180-a6693380-9ae6-11eb-937f-3a3a62287b14.png)

Here how it should look like.
![correct_bias](https://user-images.githubusercontent.com/74291692/114309669-43789c00-9ae8-11eb-885d-66e1e7389d70.png)

**Comment by abattery** [comment]
@Xhark could you triage this issue?

**Comment by abattery** [comment]
> Can I use models trained with tf1.15 and convert them in e.g. tf2.5.0 with the option _(converter.experimental_new_quantizer=True)?

Yes, you can decouple the training jobs and conversion jobs.

**Comment by Xhark** [comment]
- To use TF 2.x converter, you may have to load your model with TF 2.x Object Detection API and export it to saved model format using [export_tflite_graph_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py)

- You still have to do a lot of steps to get actual quantized model for EdgeTPU. more context is [here](https://github.com/tensorflow/models/issues/9371).

**Comment by DemolationPeter** [comment]
Thank's for the fast reply. 
I worked on it last evening and this is my result.
You can convert (mostly) with TF 1.15 QAT trained models with TF 2.4.0. I use a docker image from nvidia [nvidia](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) because of the GPU support.
At first I converte in my docker image for the model training (nvidia container with TF1.15 and Object Detection API installed) the model checkpoint with the _export_tflite_ssd_graph.py_ in a TFLite suitable frozen_graph format (tflite_graph.pb). The file is located inside the Object Detection API.
After this step I use the image with TF2.4.0 for the conversion to a fully quantized model. For the conversion I this python script which I created based on this [information ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r1/convert/python_api.md#checkpoints).

```
import tensorflow as tf

# Convert the model
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph('/Studienarbeit/tensorflow_od/exported-models/Variation74/tflite_graph.pb',
input_arrays=['normalized_input_image_tensor'],
input_shapes={'normalized_input_image_tensor' : [1,300,300,3]},		#[1,360,640,3]
output_arrays=['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'],
) # 

converter.quantized_input_stats = {'normalized_input_image_tensor' : (128, 127)}  # mean, std_dev (input range is [, ])
#converter.inference_type = tf.int8 # conversion possible, also to an edgetpu.tflite model, but error at inference
converter.inference_input_type=tf.uint8 
converter.inference_output_type=tf.uint8 # optional
converter._experimental_new_quantizer = True
converter.allow_custom_ops = True
tflite_quant_model = converter.convert()
with open('/Studienarbeit/tensorflow_od/exported-models/Variation74/test.tflite', 'wb') as w:
	w.write(tflite_quant_model)
print("Full Integer Quantization complete! - test.tflite")
```

The test.tflite file isn't completly identicly to the models converted with the TFLite Command Line Tool in TF1.15 (at least the Netron Graph looks a liitle bit different). But the modell is fully quantized (only the NMS part is not but this is espected and ok).

After that it is possible to use the Edge TPU Compiler to convert the test.tflite into a working Graph for the EDGE TPU (tested with different Models and different Image resolution). The inference speed is the same. The only difference is that know the model contains two extra Dequantize Operations a the end (see images down below.)

As prove I add some Images down below and the model files as [zip](https://github.com/tensorflow/tensorflow/files/6294854/model_new.zip).


**Old .tflite graph in Netron** (TensorFlow Lite v3, TOCO Converted, runtime:1.5.0)

![detect tflite](https://user-images.githubusercontent.com/74291692/114359611-710b2700-9b74-11eb-9d10-153d15515b21.png)

**New .tflite graph in Netron** (TensorFlow Lite v3, MLIR Converted., runtime:1.14.0)

![test tflite](https://user-images.githubusercontent.com/74291692/114359743-926c1300-9b74-11eb-88da-d686db3dfae8.png)

**Final graph Edge TPU (it is working)**
![test_edgetpu tflite](https://user-images.githubusercontent.com/74291692/114359791-9bf57b00-9b74-11eb-8750-1d490ffe12dd.png)

----------------------------------------------------------------------------------------------------------

Unfortunatly I get still an error for one QAT trained model (InceptionV2-SSD with 640x360 resolution). The conversion with TFlite is working but the Conversione with the TPU Compiler ist just aborting without a clear error code than before. Right now I'm not sure if the problem is the Compiler or the .tflite model.

**Comment by teijeong** [comment]
Hi @DemolationPeter, the new quantizer was indeed experimental in the TF 2.4.0, but enabled by default on TF 2.5.0 and works well by default. Can you try once again with TF 2.5.0 or nightly? Thanks!

**Comment by DemolationPeter** [comment]
Hi @teijeong, now I tried it with the TF2.5.0 and used the offical docker image (tensorflow/tensorflow:2.5.0rc0-gpu). The conversion is working fine for all previous working models with the difference that I can delete _converter.experimental_new_quantizer = True_. (as expected).
The conversion for my InceptionV2-SSD model is working (I get again a .tflite file) and the Graph looks fine in _netron_ to me. ([model.zip](https://github.com/tensorflow/tensorflow/files/6303555/model.zip)
Unfortunatly the Edge TPU Compiler is still aborting the conversion for this specific model..
Maybe there is a problem with the Edge TPU Compiler?
Right know I'm retraining the model maybe this will solve the issue (you never know).
