### ISSUE TITLE
The `.adapt()` method should be called `.fit()` for TextVectorization

### ISSUE THREAD

**Issue by louis925** [tensorflow/tensorflow#48465]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, to train or fit a text vectorizer in `tf.keras.layers.experimental.preprocessing.TextVectorization`, we have to call a weird `.adapt()` method which no one use this name in standard machine learning. It is more commonly to use the name `.fit()` like in [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer.fit). I suggest to name the method as `.fit()` so it will be more familiar to people who just came to tensorflow.

**Will this change the current api? How?** Yes, there will be a new `.fit()` method which is exactly the `.adapt()` method.

**Who will benefit with this feature?**
New beginner to tensorflow who are familiar with other ML framework but just came to tensorflow to use this awesome framework.

**Any Other info.**

**Comment by fchollet** [comment]
Thanks for reaching out. `fit()` is already used for model training (via backprop), and the usage of `adapt()` in preprocessing layers is quite different. During the design phase of the preprocessing layers API, we discussed with exact question, and we decided that using a different name for `adapt()` would be clearer than using `fit()`, which would lead to confusion.
