### ISSUE TITLE
keras.layers.Dense should not have float units

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#48466]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.keras.layers.Dense accepts a floating `units` and successfully inits.

**Describe the expected behavior**
Expect 'ValueError' because 'units' should be a positive integer.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
layer = tf.keras.layers.Dense(units=3.3)
layer(tf.ones([1, 3]))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by AdityaKane2001** [comment]
@lugalUrim 
Don't worry,  it floors to an integer.
```python
layer.get_config()

 #{'activation': 'linear',
 #'activity_regularizer': None,
 # 'bias_constraint': None,
 #'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 #'bias_regularizer': None,
 #'dtype': 'float32',
 #'kernel_constraint': None,
 #'kernel_initializer': {'class_name': 'GlorotUniform',
 #'config': {'seed': None}},
 #'kernel_regularizer': None,
 #'name': 'dense_1',
 #'trainable': True,
 #'units': 3,
 #'use_bias': True}
```

**Comment by lugalUrim** [comment]
Thanks for pointing this out! @AdityaKane2001 
I suppose that it would be better if the document (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) can be changed to make this clear for everyone, because now it says that the `units` should be a positive integer.

**Comment by AdityaKane2001** [comment]
It needs to be a positive integer, the developers may have just made the provision in case of an typo or something.

**Comment by UsharaniPagadala** [comment]
@lugalUrim 

Could you please confirm if the issue is resolved? if yes, please feel free to move this issue to closed status.

**Comment by lugalUrim** [comment]
Thanks. I will close the issue.
