### ISSUE TITLE
Keras models latency grows too fast after converting to TFLite

### ISSUE THREAD

**Issue by bratyslav** [tensorflow/tensorflow#48460]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: custom code.
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: IOS 14.4.2, Android 11.
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: iPad 5, Pixel 5.
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.4.1
-   **Python version**: 3.7.10
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**: 

### Describe the problem
In my code, I use the default keras.applications.MobileNetV2 model and then add some layers on top. The latency of MobileNetV2 in Google Colab (GPU) is about 0.046 s, with my layers it increases to 0.048 s (about 4%). Then I convert both models to TFLite and check on my smartphone's GPU. The latency of MobileNetV2 is about 0.065 s, but when layers are added, it increases to 0.11 s (about 40% !!!). What could be the reason for this behavior?

### Source code / logs
Colab Notebook to reproduce: https://colab.research.google.com/drive/18qryA4hPu-uCEyFggoyWRkW_ouT8024A?usp=sharing

**Comment by abattery** [comment]
What kind of layers are newly introduced? I suspect that there might be not unsupported ops in the newly attached layer from GPU delegate.

**Comment by bratyslav** [comment]
> What kind of layers were newly introduced? I suspect that there might be not unsupported ops in the newly attached layer from GPU delegate.

i applied keras.layers.experimental.preprocessing.Resizing and keras.layers.Conv2D, But I get the same results with keras.layers.Conv2D only.
Here is the simple code snippet to reproduce: https://colab.research.google.com/drive/18qryA4hPu-uCEyFggoyWRkW_ouT8024A?usp=sharing

**Comment by bratyslav** [comment]
I read the keras.applications.MobileNetV2 source code and it uses:
    - VersionAwareLayers from tensorflow.python.keras.layers instead of keras.layers;
    - training.Model from tensorflow.python.keras.engine instead of keras.models.Model;
Using this I get the expected latency.

**Comment by abattery** [comment]
Did you resolve the problem?
