### ISSUE TITLE
Conv2DTranspose crashes with filters=0

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#48470]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
Sample code:
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

input = np.random.rand(2, 8, 8, 8)
x = tf.keras.Input([None, None, 8])
y = tf.keras.layers.Conv2DTranspose(filters=0,kernel_size=3, padding='same', dilation_rate=(1,1))(x)
model = tf.keras.Model(x, y)
z = model(input).numpy()
print(z.mean())
```

**Describe the current behavior**
The process dies after calling `model(input)`.

**Describe the expected behavior**
Expect a `ValueError` raised if `filters`=`0` is not supported. It seems that conv2d supports this, for example:

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

input = np.random.rand(2, 8, 8, 8)
x = tf.keras.Input([None, None, 8])

y = tf.keras.layers.Conv2D(0, kernel_size=3)(x)
model = tf.keras.Model(x, y)
z = model(input).numpy()
print(z.shape)
```

outputs `(2, 6, 6, 0)`.

**Comment by tilakrayal** [comment]
I have tried in colab with TF v2.4,TF v2.5.0rc0, TF-nightly and noticed that session is being crashed.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/0320e88d57e19455caae287cb8e0a208/48470.ipynb) here

**Comment by fchollet** [comment]
Thanks for the report. I would suggest raising `ValueError` for all conv layers in case `filters` is `0`. Would you be able to open a PR implementing this change (including tests)?

**Comment by lugalUrim** [comment]
Thanks @fchollet . I agree that `ValueError` should be raised whenever `filters` is `0`. 
I noticed that the following functions also crash when `filters`=`0`.
Conv1DTranspose
Conv3DTranspose
ConvLSTM2D

while these does not.
Conv1D
Conv3D

**Comment by around-star** [comment]
@fchollet I'll open a PR for this issue implementing the change.

**Comment by around-star** [comment]
@nikitamaia , @fchollet , @bhack I have sent in a [PR](https://github.com/tensorflow/tensorflow/pull/48566) for this issue. Can you please review it ?
