### ISSUE TITLE
Conv2D for GPU is not currently supported without cudnn

### ISSUE THREAD

**Issue by namursag** [tensorflow/tensorflow#48476]
**System information**

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
    TensorFlow installed from (source or binary): binary
    TensorFlow version (use command below): 2.4.1
    Python version: 3.7
    Bazel version (if compiling from source): N/A
    GCC/Compiler version (if compiling from source): N/A
    CUDA/cuDNN version: N/A
    GPU model and memory: N/A

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

a = np.random.rand(1, 4, 4, 1)
b = np.random.rand(4, 4, 1, 1)

tf.raw_ops.Conv2D(input=a, filter=b, strides=[1, 1, 1, 1], padding='SAME', use_cudnn_on_gpu=False)
```

**Describe the current behavior**
Raises UnimplementedError: Conv2D for GPU is not currently supported without cudnn [Op:Conv2D].

**Describe the expected behavior**
Expect Conv2D to run on GPU without cudnn, like pytorch.

**Comment by tilakrayal** [comment]
@namursag ,

I ran the code shared on tf v2.5.0rc0, tf nightly and do not see any error, please find the [gist here](https://colab.research.google.com/gist/tilakrayal/3ae2f7513d110e9584fc3f7741ccc23f/48476.ipynb)

**Comment by namursag** [comment]
Thanks @tilakrayal . Updating to tf-nightly solves my problem indeed.
