### ISSUE TITLE
Failed to designate device placement on GPU with tf.device and executed without warning

### ISSUE THREAD

**Issue by namursag** [tensorflow/tensorflow#48477]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA Version: 11.2   
- GPU model and memory: N/A

**Describe the current behavior**
The operation within a `with tf.device('/GPU:0'):` context runs on CPU, with no warnings received.

**Describe the expected behavior**

The operations within a `with tf.device` context should run in that device. 

If the device is not available or the operations are not supported on the particular device, warnings or exceptions are expected.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
tf.debugging.set_log_device_placement(True)

a = np.random.rand(2,2)
b = np.random.rand(2,2)

with tf.device('/GPU:0'):

  x = tf.Variable(a, dtype=tf.bfloat16)
  y = tf.Variable(b, dtype=tf.bfloat16)
  c_GPU = tf.matmul(x, y)
  
```

Outputs:
```
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
```

If I change the datatype from `bfloat16` to `float32`, the output is expected:
```
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
```

**Comment by Saduf2019** [comment]
@namursag 
Please refer to below link, which says about GPUs support for float16 and float32, you may also refer to [[link](https://github.com/tensorflow/tensorflow/issues/21317#issuecomment-413365605) and [link1](https://stackoverflow.com/questions/51602313/bfloat16-training-in-gpus)]
(NVIDIA GPUs support using a mix of float16 and float32, while TPUs support a mix of bfloat16 and float32.):

https://www.tensorflow.org/guide/mixed_precision#supported_hardware

**Comment by lugalUrim** [comment]
@Saduf2019 After I downgrade to 11.0, the output is still the same.

**Comment by Saduf2019** [comment]
@lugalUrim 
Can you please open a new issue with the details of your issue as this issue is for the GPU usage for bfloat16 which is not supported.
