### ISSUE TITLE
Functions attributes error "'Functional' object has no attribute '_make_train_function'" and eager mode and non-eager returns different logits

### ISSUE THREAD

**Issue by axelning** [tensorflow/tensorflow#48478]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N/a
- TensorFlow installed from (source or binary):pip3
- TensorFlow version (use command below):2.4.1
- Python version:3.7.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:N/a
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`
def adversarial_training(model, embedding_name, epsilon=1):
	
	if model.train_function is None:  # 如果还没有训练函数
		model._make_train_function()  # 手动make
	old_train_function = model.train_function  # 备份旧的训练函数

	# 查找Embedding层
	for output in model.outputs:
		embedding_layer = search_layer(output, embedding_name)
		if embedding_layer is not None:
			break
	if embedding_layer is None:
		raise Exception('Embedding layer not found')

	# 求Embedding梯度
	embeddings = embedding_layer.embeddings  # Embedding矩阵
	gradients = K.gradients(model.total_loss, [embeddings])  # Embedding梯度
	gradients = K.zeros_like(embeddings) + gradients[0]  # 转为dense tensor

	# 封装为函数
	inputs = (
		model._feed_inputs + model._feed_targets + model._feed_sample_weights
	)  # 所有输入层
	embedding_gradients = K.function(
		inputs=inputs,
		outputs=[gradients],
		name='embedding_gradients',
	)  # 封装为函数

	def train_function(inputs):  # 重新定义训练函数
		grads = embedding_gradients(inputs)[0]  # Embedding梯度
		delta = epsilon * grads / (np.sqrt((grads**2).sum()) + 1e-8)  # 计算扰动
		K.set_value(embeddings, K.eval(embeddings) + delta)  # 注入扰动
		outputs = old_train_function(inputs)  # 梯度下降
		K.set_value(embeddings, K.eval(embeddings) - delta)  # 删除扰动
		return outputs

	model.train_function = train_function  # 覆盖原训练函数
pops
'Functional' object has no attribute '_make_train_function'
and when I turned on disable_eager_execution(), no errors pops.

When in prediction, eager call  model(inputs) returns wrong logits when I finished training and save the model to h5 format then reloaded it through tf.kears.models.load_model. This process is done in non-eager execution mode

But in the meanwhile I transform the h5 model to tf saved model(*.pb) file and run it in non-eager mode. the correct logits appears.

**Describe the expected behavior**
shouldn't these two calls return the same logits?

**Standalone code to reproduce the issue**
https://github.com/bojone/bert4keras/blob/master/examples/task_sentiment_virtual_adversarial_training.py

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
`Traceback` (most recent call last):
  File "/home/pycharmProjs/bert4keras/examples/task_proxy_recognization.py", line 217, in <module>
    adversarial_training(test_model,'Embedding-Token', 0.5)
  File "/home/pycharmProjs/bert4keras/examples/task_proxy_recognization.py", line 174, in adversarial_training
    model._make_train_function()  # 手动make
AttributeError: 'Functional' object has no attribute '_make_train_function'

**Comment by Saduf2019** [comment]
@axelning 
I ran the code shared on tf 2.4 and see error due to third party dependencies, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e3d84ef25821c21f31342f11c8cace5d/untitled588.ipynb).
Please share code such that there are no third party dependencies and if the error reported is due to these, please open the issue in the respective repository.
If possible share a simple code with the error reported due to tensorflow.

**Comment by axelning** [comment]
It is because it just called tf.keras actually, and this functions runs well in tf 2.2 , so I wonder there's some change in tf.keras

**Comment by axelning** [comment]
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(512, activation=tf.nn.relu, input_shape=(784,)))
model.add(tf.keras.layers.Dense(5, activation=tf.nn.softmax))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model._make_train_function()



runs well , when without tf.compat.v1.disable_eager_execution() the same error pops

**Comment by Saduf2019** [comment]
@axelning 
I ran with out "tf.compat.v1.disable_eager_execution() " and no error popped up, please find [gist here](https://colab.research.google.com/gist/Saduf2019/0497ab113346b00090f50ae5dbeeaa02/untitled589.ipynb)

**Comment by axelning** [comment]
I ran the gist and got
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8d086c4bccef> in <module>()
      8 optimizer='rmsprop',
      9 metrics=['accuracy'])
---> 10 model._make_train_function()

AttributeError: 'Sequential' object has no attribute '_make_train_function'

**Comment by axelning** [comment]
ummm, any progress?

**Comment by jvishnuvardhan** [comment]
@axelning I changed last line of your code from 
`model._make_train_function()` to `model.make_train_function()` and with that change it doesn't throw any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d45923375c3cc9988a4e93d83feaddba/untitled589.ipynb).

Looks like `model._make_train_function()` is only available under `tensorflow/python/keras/engine/training_v1.py` hence it was working only when eager mode is disabled. Thanks!

**Comment by axelning** [comment]
> @axelning I changed last line of your code from
> `model._make_train_function()` to `model.make_train_function()` and with that change it doesn't throw any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d45923375c3cc9988a4e93d83feaddba/untitled589.ipynb).
> 
> Looks like `model._make_train_function()` is only available under `tensorflow/python/keras/engine/training_v1.py` hence it was working only when eager mode is disabled. Thanks!

is this the reason leading to prediction difference when in eager mode and non-eager mode?  I trained one model with non-eager mode, by self defined function through model._make_train_function() and use the model in eager mode, the logits the model output is absolutely wrong, but in non-eager mode, the logits returned normal

**Comment by jvishnuvardhan** [comment]
@axelning Not sure about it. Please share a simple and complete standalone code to reproduce the issue. Thanks!
