### ISSUE TITLE
"bazel clean" will undo "./configure" when source configured to build for GPU.

### ISSUE THREAD

**Issue by gunan** [tensorflow/tensorflow#4848]
### Environment info

Operating System:
ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda 8.0.44, cudnn 5.5

If installed from binary pip package, provide:
No

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
   c8d4896e3231c3ac32f174fd0af051867645fbb5
2. The output of `bazel version`
   Build label: 0.3.1
   Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
   Build time: Fri Jul 29 09:09:52 2016 (1469783392)
   Build timestamp: 1469783392
   Build timestamp as int: 1469783392
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

./configure   # configure with GPU support)
bazel test -c opt --config=cuda tensorflow/core:common_runtime_direct_session_test # this one should pass
bazel clean
bazel test -c opt --config=cuda tensorflow/core:common_runtime_direct_session_test  # this one fails, complaining no GPU support configured.
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@ae
3629bd' (requested by nodes 'CONFIGURATION_COLLECTION:com.google.devtools.build.lib.skyframe.ConfigurationCollectionValue$ConfigurationCollectionKey@1374ec1e', 'CONFIGURATION_FRAGMENT:com
.google.devtools.build.lib.skyframe.ConfigurationFragmentValue$ConfigurationFragmentKey@3686b55', 'CONFIGURATION_FRAGMENT:com.google.devtools.build.lib.skyframe.ConfigurationFragmentValue
$ConfigurationFragmentKey@a93d9174')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1070)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:474)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

David, Damien, looks like bazel clean undid some output of "./configure" at head.
Any idea where things went wrong?

**Comment by damienmg** [comment]
I don't have the code of cuda_configure in my HEAD but it sounds like the repository itself is invalidated by bazel clean which should not happens, @kchodorow might have an idea on why a simple clean would invalidate a remote repository (maybe a bug in the skylark remote repositories).

Side-note: we should fix the failure message that fail at the wrong step (i.e. not have that stack trace, why do even have that lever?)

**Comment by gunan** [comment]
Ping, any updates, comments on this?

**Comment by damienmg** [comment]
Is this still happening? I have some in progress change to fix invalidation of skylark remote repository (to avoid the clean --expunge in the configure step) but it shold not affect this one (or maybe it will).

**Comment by gunan** [comment]
Yes, I am still running into this if I do bazel clean:
```
...
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /usr/local/google/home/gunan/.cache/bazel/_bazel_gunan/f65fe95058266630d298f8662514e702/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 0.318s
```

**Comment by davidzchen** [comment]
The reason why this is happening is that it looks like `bazel clean` is, as Damien described, invalidating the repository created by `cuda_configure`, and because the environment variables used by `cuda_configure` are no longer set (since they were only set in the subshell when `./configure` ran), we end up re-fetching with all default values and thus configuring the repository to not build with GPU.

Seems this behavior we are observing where running `bazel clean` without `--expunge` invalidates the repository might be a bug.

**Comment by damienmg** [comment]
Ok I found out the issue.

`local = True` from [cuda_configure.bzl#L818](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L818) basically invalidate the repository for a lot of little things, I suggest removing that local = True.

**Comment by gunan** [comment]
Will try the suggestion out locally.

**Comment by gunan** [comment]
After removing local=True, I still see the same problem.
@damienmg do you think I missed something, or is this not the full fix?

**Comment by damienmg** [comment]
I need to investigate a bit more. removing local = True should do the trick... I'll try to reproduce tomorrow, all I need is docker right?

**Comment by gunan** [comment]
You actually need a machine with a NVIDIA gpu, docker or not.
When I try on my machine, I can confirm that local = True does not fix the
problem for me.

**Comment by pkit** [comment]
No `bazel clean` in history:

    $ history | grep ' bazel'
    ........
    241 bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
    242 bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

But then:

    $ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
	......
	ERROR: /home/kit/.cache/bazel/_bazel_kit/5f23834381991ebb87bab85ad8b737c5/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
		File "/home/kit/.cache/bazel/_bazel_kit/5f23834381991ebb87bab85ad8b737c5/external/local_config_cuda/crosstool/BUILD", line 4
			error_gpu_disabled()
		File "/home/kit/.cache/bazel/_bazel_kit/5f23834381991ebb87bab85ad8b737c5/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
			fail("ERROR: Building with --config=c...")
	ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
	ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/kit/.cache/bazel/_bazel_kit/5f23834381991ebb87bab85ad8b737c5/external/local_config_cuda/crosstool/BUILD.
	INFO: Elapsed time: 0.571s

Seems like cache invalidation issue to me. AFAIR it's time dependent, i.e. will fail only if looong time passed between builds.
