### ISSUE TITLE
GPU is not working even after fine installation

### ISSUE THREAD

**Issue by Barleysack** [tensorflow/tensorflow#48483]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version:2.4.1
- Python version:3.8.8
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11
- GPU model and memory:GTX1660TI

![Problem](https://user-images.githubusercontent.com/56079922/114399450-e4944f00-9bdb-11eb-9d28-c0c2829b2d3f.PNG)

Good Morning- Or Night- My friends.
I'm an student learning TF and ML stuffs with plenty of interests.
I installed the CUDA, CDNN, Tensorflow-gpu properly, and python console also answered me that I have proper graphic card for 
the tensorflow. However, whenever I try to run my tf codes, only cpu usage makes tons of works, while my GPU is chillin' like a summer vacation. I think the reason might be the fact that I'm using laptop right now, FX705-DU, which made several issues about gpu while gaming. 

Does anyone suffering from same problem like me? 
TF Device check answers me that I got right GPU and even TF does not claim about absence of GPU while running the code,
smiling happily with lines of 'successfully loaded .....' 
How can I make this GPU work? I'll happily wait for the answer:)

**Comment by swight-prc** [comment]
I had the same issue. I think perhaps 2.4 updated its cuDNN requirements. I have cuDNN4_7, and it's looking for cuDNN4_8.

I suspect this was a quiet update, and it was a bit of a surprise to see that error. I'm looking into how to get cuDNN4_8 now.

**Comment by Barleysack** [comment]
> I had the same issue. I think perhaps 2.4 updated its cuDNN requirements. I have cuDNN64_7, and it's looking for cuDNN64_8.
> 
> I suspect this was a quiet update, and it was a bit of a surprise to see that error. I'm looking into how to get cuDNN64_8 now.

well I'm totally noob here, so I always look for the stable or latest version for both cuda and cuDNN... 
mine is 8.1.1, and I don't think it's some kind of package problem, but maybe it's the problem for laptop computers which got both internal graphic cards and additional GPUs...

**Comment by swight-prc** [comment]
Did you follow the instructions here:
https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

?

They're a little outdated, but they got me there with Cuda 10 and cuDNN64_7 about 6 months ago.

**Comment by Barleysack** [comment]
> Did you follow the instructions here:
> https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781
> 
> ?
> 
> They're a little outdated, but they got me there with Cuda 10 and cuDNN64_7 about 6 months ago.

Again thanks for the help, 
I got both true response from both of the test-utility functions...
yet my gpu is sleeping...

**Comment by phone-burner** [comment]
Can you get the logs ?
Maybe the logs will point out the problem .
The most possible reason is that the program cannot find the required libraries or wrong version .

**Comment by Barleysack** [comment]
> Can you get the logs ?
> Maybe the logs will point out the problem .
> The most possible reason is that the program cannot find the required libraries or wrong version .

Luckily, I could make my GPU work by using link up there. 
Now, I have to use it for my pycharm. 
When I run my code in anaconda prompt, there's no problem for now. GPU cores are successfully utilized :)
I think pycharm will not gonna be a problem if I make right environment variables settings:) I'll try first...
Since I'm rly noob here, I think I have to ask sth......do I have to close this issue now then make another issue if I get stuck with pycharm? or keep it until I get through this also?

**Comment by tilakrayal** [comment]
@Barleysack ,

Could you please close the request, if  issue  got resolved and for  issues with Pycharm, please submit a new issue in Pycharm repo.

Thanks!

**Comment by Barleysack** [comment]
> @Barleysack ,
> 
> Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.
> For issues with Pycharm, please submit a new issue in Pycharm repo.
> 
> Thanks!

Problem solved by using vscode :) thanks!
