### ISSUE TITLE
Tensorflow Lite - Flatbuffers.h error [cmake]

### ISSUE THREAD

**Issue by ardtrkc** [tensorflow/tensorflow#48485]
Hello !

Our aim is to install TensorFlow Lite in our embedded board (iMX6). To reach this aim, firstly we made a recipe to build TFLite in our Yocto framework. After this step our static tensorflow-lite library was generated.

Then, we wanted to try the functionality of the library with a basic helloworld program. For this step, we chose to start with minimal.cpp which is from official github repo of tensorflow.

For this helloworld (minimal.cpp) program we created a recipe which includes our static tensorflow-lite library inside DEPENDS part. When we bitbake with cmake recipe we get this error about flatbuffers.h ;

`/home/student/fsl-release-bsp/build-analytics-tflite/tmp/sysroots/analytics/usr/include/tensorflow/contrib/lite/schema/schema_generated.h:21:37: fatal error: flatbuffers/flatbuffers.h: No such file or directory
|  #include "flatbuffers/flatbuffers.h"`

**-Please check below for files-**

- #include part of minimal.cpp :

`#include <cstdio>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/optional_debug_tools.h"`

- Our recipe (helloworld.bb) is as follows:

`# Recipe for the Hello World program

SUMMARY = "Recipe for the Hello World program"
LICENSE = "CLOSED"
LIC_FILES_CHKSUM = ""
DEPENDS += "opencv"
DEPENDS += "libconfig"
DEPENDS += "tensorflow-lite"
SRC_URI = "git://github.com/aniladar/patch.git;protocol=https;branch=main"
SRCREV = "${AUTOREV}"
S = "${WORKDIR}/git"
B = "${S}"
inherit cmake`

- The CMakeLists.txt file is as follows:

`cmake_minimum_required(VERSION 3.14)
project(patch)
add_executable(minimal minimal.cc)`

Maybe we need some additional things inside CMakeLists.txt file or maybe we have missing DEPENDS inside our recipe. If you brighten up our path it would be perfect. Your guidance and clarifications are important for us.

Thank you in advance !

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by Jakub-Bielawski** [comment]
Hello, I have exactly the same problem.
I've downloaded the Tensorflow repo, to lib directory in my project, and everywhere with #include "flatbuffers/flatbuffers.h" is an error. Can not open source file.

**Comment by ardtrkc** [comment]
> @terryheo could you take a look?

It would be appreciated if you can guide us

**Comment by DnPlas** [comment]
I believe flatbuffers is a dependency that would normally be pulled by bazel in a "traditional" build. I see you are using CMake, so you may reference [1] or try cross-compilation with bazel [2].

[1] https://www.tensorflow.org/lite/guide/build_cmake_arm 
[2] https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel
