### ISSUE TITLE
Matmul with int32 datatype is not supported on GPU

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#48481]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 2.4
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

tf.debugging.set_log_device_placement(True)

a = np.random.rand(8,8)
b = np.random.rand(8,8)

with tf.device('/GPU:0'):
  x = tf.Variable(a, dtype="int32")
  y = tf.Variable(b, dtype="int32")
  c_GPU = tf.matmul(x, y)
```

Output:
```
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0
```

See the [gist](https://colab.research.google.com/gist/lugalUrim/07e68fbce476c25bdd41daea6a5b24d1/matmul-for-int32.ipynb#scrollTo=EguARwuQxuIH) here.

**Describe the current behavior**

The op `MatMul` (with datatype `int32`) is actually executed on CPU (as a fallback, I suppose), instead of GPU as is specified by the user.

**Describe the expected behavior**

Currently `MatMul` for `float32` is well-supported on GPU. It would be great if the kernel of `MatMul` for `int32` on GPU can also be implemented.
There should be significant speedup on GPU compared with CPU implementation. Pytorch invokes `CuBLAS` to benefit from the special hardware instructions like `Tensor Core`.

**Comment by lugalUrim** [comment]
I guess the problem doesn't have much to do with `tf.device`, because the op `MatMul` does not have int-32 support itself.

Run
```
import tensorflow
from tensorflow.python.framework import kernels
matmul_kernel = kernels.get_registered_kernels_for_op('MatMul')
print(matmul_kernel)
```
and it turns out that `MatMul` is not registered with device_type=GPU and type=DT_INT32.

**Comment by Saduf2019** [comment]
@lugalUrim 
Please share your GPU model, Cuda, cudnn version.
