### ISSUE TITLE
Invalid (404) link in the the tf.data guide

### ISSUE THREAD

**Issue by ebursztein** [tensorflow/tensorflow#48494]
## URL(s) with the issue:

https://www.tensorflow.org/guide/data

## Description of issue (what needs changing):

In the sentence "See Loading TFRecords for an end-to-end example." the link points to 
https://www.tensorflow.org/tutorials/load_data/tf_records which returns a 404

It needs to point to the correct url https://www.tensorflow.org/tutorials/load_data/tfrecord

**Comment by ymodak** [comment]
This is fixed now with the tagged PR. Thanks!
