### ISSUE TITLE
Method docs contain unclosed verbatim, which causes exceeding verbatim block in HTML docs

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#4849]
The HTML docs for `tf.constant_initializer` at  https://www.tensorflow.org/versions/master/api_docs/python/state_ops.html#constant_initializer contain unclosed verbatim block, which continues past the method and contains several following methods -- see for example the `tf.random_normal_initializer`.

I am not much familiar with the process of documentation generation, but my guess is that the verbatim ending block at https://github.com/tensorflow/tensorflow/blob/2c4af2e65a2018540d949cfdba1fcb15d0121f80/tensorflow/python/ops/init_ops.py#L142 has wrong indentation (it is indented by two more spaces than the start of the block).

**Comment by jart** [comment]
Thank you for reporting this. I've contacted just the right person who will be able to help out with this shortly.

**Comment by xmbrst** [comment]
@martinwicke, it looks like the generated markdown is rendering fine on g3doc, so the website generator is doing something strange here.

**Comment by jart** [comment]
What are we using to generate the website? There are subtle differences between various Markdown implementations. Particularly when it comes to indentation. The solution could be as simple as decreasing the indent of that closing \`\`\` by two spaces, as @foxik suggests.

**Comment by xmbrst** [comment]
The website generator uses the same markdown renderer that we use to view the doc internally, so the problem must be some extra pre- or post-processing the website generator is doing.

**Comment by jart** [comment]
This was fixed by https://github.com/tensorflow/tensorflow/commit/8e63535abb29af6f62e65dab624f4a4d3f5581cc. Push to web server is still pending.
