### ISSUE TITLE
Activation layer fails to be merged in TFLite conversion after quantization-aware training

### ISSUE THREAD

**Issue by Mjonir** [tensorflow/tensorflow#48497]
### 1. System information

- OS Platform and Distribution: Windows 10.0.19042 Build 19042
- TensorFlow installation: pip package 
- TensorFlow library: 2.6.0-dev20210412

### 2. Code

**Model training (with QA training)**: https://colab.research.google.com/gist/Mjonir/c2f281c417b3846887a242c19caa2c06/tensorflow-datasets.ipynb
**Trained model (with QA training)**: https://1drv.ms/u/s!AiIykeHl1htbwsMqPggjpHJ4azvwgg?e=l4II0F
**Model training (no QA training)**: https://colab.research.google.com/gist/Mjonir/f83a50157a722e7b93d99ef6c5a3de9e/tensorflow-datasets.ipynb
**Trained model (no QA training)**: https://1drv.ms/u/s!AiIykeHl1htbwsMtDEYyVWq-dGOGsA?e=HUU30i
**TFLite conversion**: https://colab.research.google.com/gist/Mjonir/956546ac2c73277ab71d7b6a4f536646/tensorflow-lite-debugger-colab.ipynb
**Converted model (with QA training)**: https://1drv.ms/u/s!AiIykeHl1htbwsMpmYF1Y17JNt2Wlw?e=cHk0YD
**Converted model (no QA training)**: https://1drv.ms/u/s!AiIykeHl1htbwsMsaOLa1RKE03beQQ?e=zRHFvN

### 3. Failure after conversion

When converting a QA-trained model, the Relu activation fails to be merged with the preceding Conv2D/Dense layer. When porting to target hardware, in my case to microcontroller, this results in the activation layers being processed separately on the target instead of during the evaluation of the Conv2D kernel, inducing a 10% performance loss in my overall network.

For reference, an identical non-QA trained model has its activation indeed merged with the preceding Conv2D/Dense layer.

### 5. (optional) Any other info / logs

Netron visualisations:
**With QA training:**
![with_qa](https://user-images.githubusercontent.com/5678238/114494711-1b3e8980-9c1d-11eb-88ec-a0248d9fc6ef.png)
**No QA training:**
![no_qa](https://user-images.githubusercontent.com/5678238/114494704-18dc2f80-9c1d-11eb-8f54-c0ef7a30c35e.png)

**Comment by abattery** [comment]
@teijeong could you triage this issue?

**Comment by liufengdb** [comment]
David, there are fake quant ops are inserted between the conv and relu. looks like this is a bug of the QAT api.

**Comment by pjpratik** [comment]
@Mjonir I was checking if this issue still persists with TF 2.11 and TF MOT 0.7.3. 

I have converted the model which is trained using quantization aware training with  int 8 quantization.  

I have observed that Conv2D has been merged with RELU when visualized with [netron](https://netron.app/).

![tflite_int8_only_model tflite](https://user-images.githubusercontent.com/118897289/213136419-5ce4dcca-3001-4ba4-8718-0b38b0cdc1e3.png)

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/0d8bbca7942152cf0fe1c6fc59c83398/48497.ipynb) and let us know if it helps. Thank you.
