### ISSUE TITLE
Backport for moved models.rnn.linear doesn't work

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/tensorflow#485]
In v0.6 linear got moved into `ops.rnn_cell.linear`, but backport here `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/linear.py` points to `tf.nn.linear`.

This break code with v0.5.

**Comment by vrv** [comment]
Thanks, @ebrevdo can fix this.

Btw, that code was never part of the public API :(

**Comment by vrv** [comment]
Well, since it wasn't part of the official API, this isn't really a bug. And I believe it still isn't documented, so it's still not "ready".  Closing for now!
