### ISSUE TITLE
Documentation on hosted models

### ISSUE THREAD

**Issue by rola93** [tensorflow/tensorflow#48509]
## URL(s) with the issue:

https://www.tensorflow.org/lite/guide/hosted_models#image_classification

## Description of issue (what needs changing):
Additional information is required for the available models

### Clear description

Models available for image classification: only models are provided, there is no information with respect to preprocessing required, dataset where it was trained or labels file. This should be given, or at least, said somewhere in the docs.

**Comment by saikumarchalla** [comment]
@rola93  Please go through the TF HUB [link](https://tfhub.dev/s?deployment-format=lite&module-type=image-classification&q=quantized) and you will find more information related to the models provided in the documentation. Thanks!

**Comment by rola93** [comment]
Thanks for your answer! Now need to learn [hot to extract label's file from metadata](https://stackoverflow.com/questions/67082697/how-to-extract-metadata-from-tflite-model) for some of them, but this is another problem.

Thank you!
