### ISSUE TITLE
error when using XLA with multiple GPUs

### ISSUE THREAD

**Issue by cswhjiang** [tensorflow/tensorflow#48502]
The TF version is 2.4.1. When I enable XLA with mulit-gpu training by using MirroredStrategy, I got the following errors. 

```
...
while/NcclAllReduce_271: unsupported op: No registered 'NcclAllReduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node while/NcclAllReduce_271}}
        Stacktrace:
                Node: __inference_train_multiple_steps_260276, function: 
                Node: while, function: __inference_train_multiple_steps_260276
                Node: while/NcclAllReduce_271, function: while_body_135159

while/NcclAllReduce_272: unsupported op: No registered 'NcclAllReduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node while/NcclAllReduce_272}}
        Stacktrace:
                Node: __inference_train_multiple_steps_260276, function: 
                Node: while, function: __inference_train_multiple_steps_260276
                Node: while/NcclAllReduce_272, function: while_body_135159

while/NcclAllReduce_273: unsupported op: No registered 'NcclAllReduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node while/NcclAllReduce_273}}
        Stacktrace:
                Node: __inference_train_multiple_steps_260276, function: 
                Node: while, function: __inference_train_multiple_steps_260276
                Node: while/NcclAllReduce_273, function: while_body_135159

while/NcclAllReduce_274: unsupported op: No registered 'NcclAllReduce' OpKernel for XLA_GPU_JIT devices compatible with node {{node while/NcclAllReduce_274}}
        Stacktrace:
                Node: __inference_train_multiple_steps_260276, function: 
                Node: while, function: __inference_train_multiple_steps_260276
                Node: while/NcclAllReduce_274, function: while_body_135159
....

```

How to fix it?

**Comment by ymodak** [comment]
Looks like `nccl` drivers are missing from your system config. By default TF uses `NcclAllReduce()` you may switch to Hierarchical Copy and try.
```python
tf.distribute.mirrorstrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
```
https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy?version=nightly#args

**Comment by cswhjiang** [comment]
> Looks like `nccl` drivers are missing from your system config. By default TF uses `NcclAllReduce()` you may switch to Hierarchical Copy and try.
> 
> ```python
> tf.distribute.mirrorstrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
> ```
> 
> https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy?version=nightly#args

The task can run without XLA enabled. It seems that nccl drivers are installed correctly.

**Comment by nikitamaia** [comment]
Hi @cswhjiang, #45940 has some more info on using XLA with a distribution strategy. Please take a look at that thread. If that does not answer your question, please provide more information (are you using a custom training loop?) or reproducible code. Thanks!
