### ISSUE TITLE
Mapping an OpDef into a TF op (Python API)

### ISSUE THREAD

**Issue by 18jeffreyma** [tensorflow/tensorflow#48514]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF2
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

I'm currently for a way to map an OpDef into a TF op. Currently, there is no way to retrieve the Python bindings for a certain TF op given the OpDef (there isn't a way to access the op registry from the Python API). It's possible to export the OpList proto and load that into Python easily, but looking a way to access the actual python bindings for any registered TF op.

**Will this change the current api? How?**

Unclear, also made this post asking if such a feature was already available.

**Who will benefit with this feature?**

Any end users who wish to work at the TF op level and want to access more detailed information about each op (number of arguments attributes, etc.)

**Any Other info.**

**Comment by allenlavoie** [comment]
You can get some information about ops (their names and argument names) via `tf.raw_ops.*` (e.g. `tf.raw_ops.Add`). I don't know if we want to put protos in that API directly, but potentially those objects could include more information about the op.

If something were attached to the `tf.raw_ops` endpoints, what specifically would you want? Type constraints? Attributes vs. inputs?
