### ISSUE TITLE
The repository 'file:/var/nccl-repo-2.2.13-ga-cuda9.2  Release' no longer has a Release file. Ubuntu-18.04

### ISSUE THREAD

**Issue by Rahul2203** [tensorflow/tensorflow#48518]
I am getting this error while enabling the GPU support. 
I am following the steps as mentioned here.
https://www.tensorflow.org/install/gpu
![err](https://user-images.githubusercontent.com/79437844/114683080-3e416a00-9cff-11eb-9994-035dd9f21d57.png)

**Comment by saikumarchalla** [comment]
@Rahul2203  Could you please provide the following information.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Also, Please provide the exact sequence of commands that you have executed before running into the error. Thanks!
