### ISSUE TITLE
Shard data across TFRecords

### ISSUE THREAD

**Issue by NA-Dev** [tensorflow/tensorflow#48526]
**System information**
- Code straight from the documentation at https://www.tensorflow.org/api_docs/python/tf/data/experimental/TFRecordWriter 
- Google Colab with TPU
- TensorFlow version 2.4

**Describe the current behavior**

This code works and writes a file to Google Cloud Storage

```
dataset = tf.data.Dataset.range(3)
dataset = dataset.map(tf.io.serialize_tensor)
writer = tf.data.experimental.TFRecordWriter("/path/to/file.tfrecord")
writer.write(dataset)
```

But this code does not write any file. It also does not throw any error. Also, I can't for the life of me figure out how to print filename to debug that part.

```
dataset = tf.data.Dataset.range(3)
dataset = dataset.map(tf.io.serialize_tensor)

def reduce_func(key, dataset):
  filename = tf.strings.join(['/path/to/', tf.strings.as_string(key)])
  writer = tf.data.experimental.TFRecordWriter(filename)
  writer.write(dataset.map(lambda _, x: x))
  return tf.data.Dataset.from_tensors(filename)

dataset = dataset.enumerate()
dataset = dataset.apply(tf.data.experimental.group_by_window(
  lambda i, _: i % 2, reduce_func, tf.int64.max
))
```

**Describe the expected behavior**
I would expect the second bit of code to write a TFRecord file.

**Comment by amahendrakar** [comment]
@ymodak,
I was able to reproduce the issue with TF v2.4.1, TF v2.5.0rc1 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5f0aadb91702f31f21a8d412cd3f85da/48526.ipynb). Thanks!

**Comment by aaudiber** [comment]
@NA-Dev Datasets produce data on-demand, so to trigger the writing you need to iterate through the dataset, e.g. with
```
for _ in dataset: pass
```
or
```
_ = list(dataset)
```

Sorry for the confusion, I'm sending a PR to add the execution step to the doc.
