### ISSUE TITLE
Customize continuous string tensor type for feature hashing on GPU.

### ISSUE THREAD

**Issue by Lifann** [tensorflow/tensorflow#48520]
**System information**
- TensorFlow version (you are using): 1.15 & 2.4
- Are you willing to contribute it (Yes/No): Yes

**Background**
In a recommender system, there are large number of features are expressed in the form of text, like the name of a product, or behavior of user, in advertisement.

**Describe the feature and the current behavior/state.**
Currently, Tensorflow use discontinuous host memory to store the text. When hashing the text features, it will lead to lack of performance, by some reasons:
1. Extract string tensor from TFRecord will introduce lots of memcpy for moving string elements one by one.
2. When using GPU to hash the text features, is hard to do memcpy from discontinuous memory to continuous memory, both [H2D] or [H2H + single H2D], since we cannot use discontinuous data on GPU.

**Who will benefit with this feature?**
I implemented a Murmur hashing with CUDA, wrapped by Tensorflow OP. I found that string copying one by one consumes 90% of the time. So it will make a huge improvement if a continuous string Tensor is enabled.

I'm new to Tensorflow framework type system. How could I create a new tensor type? And what kinds of problems should I consider?

**Comment by sanjoy** [comment]
I'm not a TFRecord expert, but I can't easily see how this will work reading the TFRecord [spec](https://www.tensorflow.org/tutorials/load_data/tfrecord#tfrecords_format_details).

Can you more explicitly state what you're proposing?  Are you suggesting to create a new format that is like TFRecord, but is formatted differently?

**Comment by sanjoy** [comment]
> I'm wondering would it be possible for TensorFlow to accept a GPU implementation instead of tf.as_string + tf.strings. to_hash_bucket ? or just a GPU impl for the AsString OP?

@Lifann I think this is already done, see https://github.com/tensorflow/tensorflow/pull/47936.

**Comment by tilakrayal** [comment]
@Lifann,
Have you got the chance to have a look at this PR where it was raised for adding the GPU support for patterns of
 **AsString + StringToHashBucket** ops  and the PR was merged.
https://github.com/tensorflow/tensorflow/pull/47936

```python
struct TensorToHashBucket {
  TensorToHashBucket() = default;
  explicit TensorToHashBucket(int op1, int op2, int op3)
      : pre_as_string(op1), as_string(op2), string_to_hash_bucket(op3) {}

  int pre_as_string = kMissingIndex;
  int as_string = kMissingIndex;
  int string_to_hash_bucket = kMissingIndex
```
The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
