### ISSUE TITLE
micro: Port RESIZE_BILINEAR from lite to micro

### ISSUE THREAD

**Issue by patriklaurell** [tensorflow/tensorflow#48537]
@tensorflow/micro

@advaitjain This issue tracks my work on porting the RESIZE_BILINEAR kernel for int8 and float to TFL micro. It will be delivered in four PRs.
* PR1 (merged): Extract the code for parsing the op from a flatbuffer out of ParseOpDataTfLite in tensorflow/lite/core/api/flatbuffer_conversions.cc into a standalone function. #43427
* PR2 (merged): Extract the reference implementation out of tensorflow/lite/kernels/internal/reference/reference_ops.h into its own header. #48616
* PR3 (merged): Port the RESIZE_BILINEAR kernel, port the tests and add it to the micro build as three separate commits. #48617

**Comment by advaitjain** [comment]
Thanks @patriklaurell!

Note that we have realized that it's better to combine PR3 and 4 into a single pull request with separate commits for those steps.

**Comment by patriklaurell** [comment]
This issue was resolved by the merge of #48617
