### ISSUE TITLE
build_all_linux.sh failed: threadpool.cc:94:29: error: no matching function for call to ‘Eigen::NonBlockingThreadPoolTempl

### ISSUE THREAD

**Issue by atptour2017** [tensorflow/tensorflow#48538]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary):  https://github.com/tensorflow/tensorflow.git
- TensorFlow version: 1.13
- Python version: 3.6.13
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.19.2
- GCC/Compiler version (if compiling from source): gcc version 7.5.0
- CUDA/cuDNN version: No CUDA
- GPU model and memory: No GPU

**Describe the problem**
When I checkout tensorflow source code r1.13 and run the build_all_linux.sh, the downloading of eigen is failed as the eigen resource URL https://bitbucket.org/eigen/eigen/get/9f48e814419e.tar.gz writen in download_dependencies.sh did not exist. It seems that the version is eigen 3.3.7. Then I downloaded this eigen version from github.
Then I run build_all_linux.sh again. There were some errors during compiling: Please find the compiling log below. 
It seems that the eigen version 3.3.7 did not match the tensorflow r1.13 source code: the tensorflow/core/lib/core/threadpool.cc requires a different input parameter of NonBlockingThreadPoolTempl format that Eigen::NonBlockingThreadPoolTempl provided. However after I downloaded all the eigen 3.3.x and checked their NonBlockingThreadPoolTempl definition there were none of them match the tensorflow's requirements. What's the matter?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
tensorflow/tensorflow/contrib/makefile/build_all_linux.sh

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
tensorflow/core/lib/core/threadpool.cc: In constructor ‘tensorflow::thread::ThreadPool::Impl::Impl(tensorflow::Env*, const tensorflow::ThreadOptions&, const string&, int, bool, Eigen::Allocator*)’:
tensorflow/core/lib/core/threadpool.cc:94:29: error: no matching function for call to ‘Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::NonBlockingThreadPoolTempl(int&, bool&, tensorflow::thread::EigenEnvironment)’
         allocator_(allocator) {}
                             ^
In file included from /home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/ThreadPool:58:0,
                 from /home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/Tensor:74,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from tensorflow/core/lib/core/threadpool.cc:19:
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/ThreadPool/NonBlockingThreadPool.h:22:3: note: candidate: Eigen::NonBlockingThreadPoolTempl<Environment>::NonBlockingThreadPoolTempl(int, Environment) [with Environment = tensorflow::thread::EigenEnvironment]
   NonBlockingThreadPoolTempl(int num_threads, Environment env = Environment())
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/ThreadPool/NonBlockingThreadPool.h:22:3: note:   candidate expects 2 arguments, 3 provided
tensorflow/core/lib/core/threadpool.cc: In member function ‘void tensorflow::thread::ThreadPool::Impl::ParallelFor(tensorflow::int64, tensorflow::int64, std::function<void(long long int, long long int)>)’:
tensorflow/core/lib/core/threadpool.cc:100:72: error: no matching function for call to ‘Eigen::ThreadPoolDevice::ThreadPoolDevice(tensorflow::thread::ThreadPool::Impl*, int, Eigen::Allocator*&)’
     Eigen::ThreadPoolDevice device(this, this->NumThreads(), allocator_);
                                                                        ^
In file included from /home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/Tensor:92:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from tensorflow/core/lib/core/threadpool.cc:19:
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:109:3: note: candidate: Eigen::ThreadPoolDevice::ThreadPoolDevice(Eigen::ThreadPoolInterface*, int)
   ThreadPoolDevice(ThreadPoolInterface* pool, int num_cores) : pool_(pool), num_threads_(num_cores) { }
   ^~~~~~~~~~~~~~~~
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:109:3: note:   candidate expects 2 arguments, 3 provided
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:107:8: note: candidate: constexpr Eigen::ThreadPoolDevice::ThreadPoolDevice(const Eigen::ThreadPoolDevice&)
 struct ThreadPoolDevice {
        ^~~~~~~~~~~~~~~~
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:107:8: note:   candidate expects 1 argument, 3 provided
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:107:8: note: candidate: constexpr Eigen::ThreadPoolDevice::ThreadPoolDevice(Eigen::ThreadPoolDevice&&)
/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceThreadPool.h:107:8: note:   candidate expects 1 argument, 3 provided
tensorflow/core/lib/core/threadpool.cc: In member function ‘void tensorflow::thread::ThreadPool::ScheduleWithHint(std::function<void()>, int, int)’:
tensorflow/core/lib/core/threadpool.cc:204:10: error: ‘struct tensorflow::thread::ThreadPool::Impl’ has no member named ‘ScheduleWithHint’; did you mean ‘Schedule’?
   impl_->ScheduleWithHint(std::move(fn), start, limit);
          ^~~~~~~~~~~~~~~~
          Schedule
tensorflow/core/lib/core/threadpool.cc: In member function ‘void tensorflow::thread::ThreadPool::SetStealPartitions(const std::vector<std::pair<unsigned int, unsigned int> >&)’:
tensorflow/core/lib/core/threadpool.cc:209:10: error: ‘struct tensorflow::thread::ThreadPool::Impl’ has no member named ‘SetStealPartitions’
   impl_->SetStealPartitions(partitions);
          ^~~~~~~~~~~~~~~~~~
gcc --std=c++11 -march=native -I. -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/../../../ -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/ -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/eigen -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/fft2d -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/double_conversion -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/downloads/absl -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/gen/host_obj/ -I/home/chendan/code/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/include -I/usr/local/include -c tensorflow/core/lib/io/inputstream_interface.cc -o /home/chendan/code/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/io/inputstream_interface.o
tensorflow/contrib/makefile/Makefile:885: recipe for target '/home/chendan/code/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/core/threadpool.o' failed
make: *** [/home/chendan/code/tensorflow/tensorflow/contrib/makefile/gen/host_obj/tensorflow/core/lib/core/threadpool.o] Error 1

**Comment by tilakrayal** [comment]
@atptour2017 ,

TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

**Comment by atptour2017** [comment]
Thanks!
So I checkout r2.4 but could not find build_all_linux.sh in this branch. The similar folder is tensorflow/tensorflow/lite/tools/make. This folder has download_dependencies.sh inside. But I do not know how to build the code. I need to build out protobuf header files and c++ source files and others as I want to use tensorflow in C++.
When I checkout r2.0 the tensorflow\tensorflow\contrib\makefile\build_all_linux.sh exists. It's the same structure as version1.x. 
How to build the v2.4 source code?

**Comment by atptour2017** [comment]
> 
> 
> @atptour2017 ,
> 
> TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4.1 and check if you are facing the same issue. Thanks!

Thanks!
So I checkout r2.4 but could not find build_all_linux.sh in this branch. The similar folder is tensorflow/tensorflow/lite/tools/make. This folder has download_dependencies.sh inside. But I do not know how to build the code. I need to build out protobuf header files and c++ source files and others as I want to use tensorflow in C++.
When I checkout r2.0 the tensorflow\tensorflow\contrib\makefile\build_all_linux.sh exists. It's the same structure as version1.x.
How to build the v2.4 source code?

**Comment by Saduf2019** [comment]
@atptour2017 
Please share the error logs faced on  tf 2.4.
