### ISSUE TITLE
ValueError: `updates` argument is not supported during eager execution. You passed: [<tf.Variable 'UnreadVariable' 

### ISSUE THREAD

**Issue by SixtyTrees** [tensorflow/tensorflow#48541]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I am using Python 3.6 with Tensorflow 2.3.0 and Keras 2.3.0 on Windows 10.  NVIDIA-SMI 452.56       Driver Version: 452.56       CUDA Version: 11.0

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I run training of a Color-CNN model (https://github.com/beerboaa/Color-Classification-CNN/blob/master/color_net_training.py) I get 

Found 1260 images belonging to 3 classes.
Found 420 images belonging to 3 classes.
Traceback (most recent call last):
  File "C:/workspace/color_model/color_classification_cnn.py", line 162, in <module>
    model.fit_generator(
  File "C:\Python3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\keras\engine\training.py", line 1718, in fit_generator
    return training_generator.fit_generator(
  File "C:\Python3\lib\site-packages\keras\engine\training_generator.py", line 42, in fit_generator
    model._make_train_function()
  File "C:\Python3\lib\site-packages\keras\engine\training.py", line 328, in _make_train_function
    self.train_function = K.function(
  File "C:\Python3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3007, in function
    return tf_keras_backend.function(inputs, outputs,
  File "C:\Python3\lib\site-packages\tensorflow\python\keras\backend.py", line 3932, in function
    raise ValueError('`updates` argument is not supported during '
ValueError: `updates` argument is not supported during eager execution. You passed: [<tf.Variable 'UnreadVariable' shape=(48,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'UnreadVariable' shape=(48,) dtype=float32, numpy=

**Describe the expected behavior**

This script should train the color-CNN model

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://github.com/beerboaa/Color-Classification-CNN/blob/master/color_net_training.py

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
That code is 4 years old. I suggest you to open an issue there if the maintainer is still active. It will need for sure some changes to run in modern TF versions.
@saikumarchalla I think that we can close this.

**Comment by saikumarchalla** [comment]
@SixtyTrees   The code which you have provided using keras  instead of tf.keras and it is very old. Please check the suggestion mentioned above by @bhack .
