### ISSUE TITLE
Can we ignore 'tensorflow.python.framework.errors.DataLossError: corrupted record at 0'

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#4854]
I will face this problem when reading tf records on hdfs, may be running one hour or two hours, then my program will crash down due to this assertion fail from tensorflow c++ code.
Can we just ignore this, ie. ignore the batch with DataLossErro, so can continue training next batch without having to stop the program.

**Comment by chenghuige** [comment]
The problem is due to writting tfrecords without finally call close(). Close this.

**Comment by bobopit** [comment]
I meet the common problem,do you know how to ignore it

**Comment by RHTNT** [comment]
I get this error despite calling close(). It occurs randomly after successfully training for a few epochs. I think there is no fix to this.
