### ISSUE TITLE
WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.

### ISSUE THREAD

**Issue by emadboctorx** [tensorflow/tensorflow#48547]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.2.3 and Ubuntu 18 (google colab)
- TensorFlow installed from (source or binary): pip (binary)
- TensorFlow versions (use command below):

  - colab    --> v2.4.1-0-g85c8b2a817f 2.4.1
  - macOS --> v2.4.0-49-g85c8b2a817f 2.4.1

- Python version: 3.8.8 (macOS) and 3.7 (colab)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm using the following actor critic model:

    def create_a2c(input_shape, actor_units):
        initializer = Orthogonal(tf.math.sqrt(2.0))
        x0 = Input(input_shape)
        x = Dense(64, activation='tanh', kernel_initializer=initializer)(x0)
        x = Dense(64, activation='tanh', kernel_initializer=initializer)(x)
        actor_out = Dense(actor_units, kernel_initializer=Orthogonal(0.01))(x)
        critic_out = Dense(1, kernel_initializer=Orthogonal(1.0))(x)
        return Model(x0, [actor_out, critic_out])

I keep getting:

    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['dense_2/kernel:0', 'dense_2/bias:0'] when minimizing the loss.

**Describe the expected behavior**
I expect the gradients to exist.

**Standalone code to reproduce the issue**

Here's a colab [notebook](https://colab.research.google.com/drive/1gqkXUBiulwZ4XSiWg4eVmfcKFQ3Ce1G_?usp=sharing) 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.4 and nightly versions. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/ec58aa8fffe616dc5546be7f20550b69/a2c-cont-issue.ipynb).Thanks!

**Comment by emadboctorx** [comment]
I fixed the problem by changing the implementation. This doesn't necessarily mean that the current implementation is wrong. It works only for discrete environments, otherwise I get this ghost gradient warning. Based on this, I'm closing this issue and if anyone encounters the similar issue, feel free to re-open it.
