### ISSUE TITLE
TF Squeezing dimension off of sequential model inputs

### ISSUE THREAD

**Issue by tetelestia** [tensorflow/tensorflow#48549]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab notebook provided below
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): v2.4.1-0-g85c8b2a817f

**Describe the current behavior**

Creating a simple model where the final axis dimension is 1 causes data called by the model to fail with the following error: `ValueError: Input 0 of layer dense is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape (5, 160)`
For the output above, the input was defined as `(160, 1)`, but running an array with the shape `(5, 160, 1)` caused the error. Running in TF 2.2 everything works as expected.

**Describe the expected behavior**

The model should successfully be called on data where the final axis is 1.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1owEhfGDRt3lrRfpu5PzRE9v1I6SWVzxc

**Other info / logs**

The problem seems to be due to [this statement](https://github.com/tensorflow/tensorflow/blob/5f808811084219533fd58238b6e97577218808e6/tensorflow/python/keras/engine/functional.py#L615). There's a function, `_conform_to_reference_input` which will squeeze the final axis "if tensor is (BATCH, ..., 1) and reference is (BATCH, ...)."

This behaviour seems quite counter intuitive to me. The data I'm working with is a time series that can have variable numbers of input channels. Removing the axis with a single input channel breaks many of my models when I have a single input channel. Even a basic model, such as a 2D CNN on MNIST, this would seem to make the inputs incompatible unless that axis is added again in the model before the CNN layer.

Is there a different way we're supposed to handle inputs with a single channel?

**Comment by bhack** [comment]
It was introduced by @omalleyt12 with https://github.com/tensorflow/tensorflow/commit/2b58bb4025df1afe47cd9b523a988d4b75f3f89f. Let see what was the origin of this change.

**Comment by tetelestia** [comment]
This works either using the Functional API, or setting the input shape of the layer with Sequential API. It seems to only be a problem using `model.build(...)`

**Comment by UsharaniPagadala** [comment]
@tetelestia 
Please confirm if the issue still persist

**Comment by tetelestia** [comment]
There is a simple workaround to use Functional API, but my example still fails in `tf-nightly-2.6.0.dev20210428`

**Comment by bhack** [comment]
```
        # Should squeeze last dimension.
        # True if tensor is (BATCH, ..., 1) and reference is (BATCH, ...).
```
It was introduce by @omalleyt12 I don't know if he could comment on this.

**Comment by chunduriv** [comment]
I was able to reproduce the issue on colab using `TF2.6` and `TF-nightly(2.8.0-dev20211003)`.Please find the gist [here](https://colab.research.google.com/gist/chunduriv/ecb18bfa8cad4c955dd3107774674759/48549.ipynb) for reference.Thanks!

**Comment by bhack** [comment]
@qlzh727 Can you help to route this? Why it was introduced?

**Comment by qlzh727** [comment]
I think this is expected.

The core issue here is that the invocation of `model.build(input_length, input_channels)`.

Note that the input_shape is expected to contain batch dimension. The passed param here doesn't contain the batch dim, which make the model record the input shape to be a 2D tensor (rather than 3D). When the model sees the real input, the will try to compare the expected shape against the real input. In the case that the last dim is 1 and the expected rank is 1 less, it will try to squeeze the last dim of the put, and pass it to the layer.

To fix this issue on client side, you need to update the param for the build method to include batch dim as well. If you don't know the batch dim at the moment, you can use None instead.

**Comment by bhack** [comment]
Can we close this?
