### ISSUE TITLE
How to create a representative dataset using TFrecords for tensorflow lite post training quantize conversion?

### ISSUE THREAD

**Issue by Ethylbenzol** [tensorflow/tensorflow#48552]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): tf-nightly 2.6 dev

I am trying to create a representative data set for conversion to tflite and perform a int8 quantize operations. I was wondering, is it possible to use TFrecords as a input data to be used to create a `representative_dataset` instead of looping through each images to generate a `representative_dataset`? This is due to no examples of using TFrecords in the API but the API just says you can load TFrecord and create a dataset for manipulation.

**Comment by abattery** [comment]
@teijeong could you triage this issue?

**Comment by liufengdb** [comment]
Can you try the following code?
```
def representative_dataset_generator():
    """Dataset generator that generates random tensor with the same shape as the input"""
    filenames = [filename]
    raw_dataset = tf.data.TFRecordDataset(filenames) 
    for raw_record in raw_dataset.take(10):
       # manipulate the raw_record to get the right shape.
      yield raw_record    # raw_record is just a tensor
```

**Comment by Ethylbenzol** [comment]
> Can you try the following code?

Just tried it. Threw a error `TypeError: 'generator' object is not callable` in tensorflow/tensorflow/lite/python/optimize/calibrator.py at:
``` 
    for sample in dataset_gen():
      if not initialized:
        initialized = True
        self._calibrator.Prepare([list(s.shape) for s in sample])
      self._calibrator.FeedTensor(sample)
    return self._calibrator.Calibrate()
```

I will try debug and see what went wrong with the conversion process.

**Comment by tilakrayal** [comment]
@Ethylbenzol,

Could you please try to include the below code and execute.

```python
representative_dataset = dataset.take(10).map(preprocess_fn) 

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops   = [tf.lite.OpsSet.TFLITE_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.quantization_mode = tf.lite.QuantizationMode.INT8
tflite_model = converter.convert()
```

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
