### ISSUE TITLE
InvalidArgumentError when using class_weight in Model.fit with labels having extra dimension for time step

### ISSUE THREAD

**Issue by oO0oO0oO0o0o00** [tensorflow/tensorflow#48555]
We used the `class_weight` parameter to assign different weights for samples of different classes in `keras.Model.fit()`.
Our data (input) and labels (output) have an extra time-step dimension besides the batch dimension.
The labels are indices of classes (i.e. not one-hot encoded), used along with the **sparse** CE loss function.
We've written a minimal reproduction script (as presented below) to simplify the situation.

It looks like that `class_weight` is only designed for outputs of shape (batch_dim, n_classes).

Possible workarounds:
 1. convert `class_weight` to `sample_weight`
 2. collapse time-step axis into batch axis using `tf.reshape()` in a `Lambda` layer, which would mess the code up

I've noticed there are relevant issues but they are left there and closed as the authors did not reply in time.

**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Anaconda, binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.5
- CUDA/cuDNN version: cudnn 7.6.5 cuda10.1_0.conda (irrelevant)
- GPU model and memory: Tesla K40c, 11441MiB (irrelevant)

**Describe the current behavior**
Crashed on `model.fit` with the following exception (traceback appended at the end as it is too long):

> InvalidArgumentError: indices[0] = 3 is not in [0, 2)
>	 [[{{node GatherV2}}]] [Op:IteratorGetNext]

The training progress bar did not appear.

**Describe the expected behavior**
Complete the training, though the minimal reproduction script has no actual trainable parameter.

**Standalone code to reproduce the issue**
```python
import numpy
import tensorflow as tf
from tensorflow import keras

def test_class_weight_error():
    # the model simply return the input time_step*n_class=20x2 data as-is
    model = keras.Sequential([keras.layers.Reshape((20, 2), input_shape=(20, 2))])
    # run_eagerly improves the readability of the traceback a bit
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', run_eagerly=True)
    model.summary()
    # X (inputs, as well as y_pred): samples*time_step*n_classes=15x20x2
    xs = tf.reshape(tf.one_hot(tf.ones(300, dtype=tf.int32), 2), [-1, 20, 2]).numpy()
    # Y (labels i.e. y_true): samples*time_step=15x20, class labels of 0 or 1
    ys = np.ones([15, 20], dtype=np.int32)
    # without the line below (a.k.a. all labels being 1) there's no exception
    ys[:,:3] = 0
    # here's the crash
    model.fit(xs, ys, batch_size=3, class_weight={0:1.,1:1.})
    
test_class_weight_error()
```

**Other info / logs** 

Traceback:
[traceback.txt](https://github.com/tensorflow/tensorflow/files/6323917/traceback.txt)

Model Structure (in minimal repro script):
 > Model: "sequential_64"
 > Layer \(type\)                 Output Shape              Param
 > reshape_64 \(Reshape\)         \(None, 20, 2\)             0         
 > Total params: 0
 > Trainable params: 0
 > Non-trainable params: 0
 > _________________________________________________________________

**Comment by Saduf2019** [comment]
I am able to replicate this issue on tf 2.2, tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/aa6c13002327ac0f5b19bef00f93fee8/untitled593.ipynb)

**Comment by nealchau** [comment]
I was also able to reproduce this on TF 2.4. From the reference page for fit it also seems that the class_weight is argument is specifically created to allow the user to weight by class: 

class_weight | Optional named list mapping indices (integers) to a weight (float) value, used for weighting the loss function (during training only). This can be useful to tell the model to "pay more attention" to samples from an under-represented class.
-- | --

**Comment by chunduriv** [comment]
I was able to reproduce the issue on colab using `TF2.6` and `TF-nightly(2.8.0-dev20211003)`.Please find the gist [here](https://colab.research.google.com/gist/chunduriv/12e65022d084187b3384893f60a49ef0/48555.ipynb) for reference.Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
