### ISSUE TITLE
DeepDream tutorial Unsupervised

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#4855]
Is it possibile to have a unsupervised version of the DeepDream tutorial?
And what kind of solution could be adopted? VAE? DCGAN? 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/deepdream

**Comment by bhack** [comment]
What do you think to switch the notebook to MetaGraph? I see that fine tuning it is more oriented on tfslim this days and slim models use the new meta+check point.

**Comment by bhack** [comment]
The last comment it is another topic so I have opened a new issue https://github.com/tensorflow/tensorflow/issues/4907

**Comment by jart** [comment]
Thanks for reaching out. I've passed word along.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity.
