### ISSUE TITLE
RuntimeError: MetaGraphDef associated with tags {''serve'} could not be found in SavedModel.

### ISSUE THREAD

**Issue by dexsr415** [tensorflow/tensorflow#48554]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source):anaconda installation
- TensorFlow library (version, if pip package or github SHA, if built from source):2.3.0

### 2. Code
 I am using, the official code from the tensorflow website:
REFERENCE : https://www.tensorflow.org/lite/convert

`import tensorflow as tf `                                                                            
                                                                                                                 
`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)`
`tflite_model = converter.convert()                                                            `
`open("converted_model.tflite", "wb").write(tflite_model)                         `

### 3. ERROR  

According above code,here is an error.

**RuntimeError :  MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. 
To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [{'train', 'serve'}]**
 

### 4. modify code
I modeify my code:

`import tensorflow as tf `                                                                            
                                                                                                                
`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir,tags=[{'serve', 'train'}])`
`tflite_model = converter.convert()                                                            `
`open("converted_model.tflite", "wb").write(tflite_model)                         `

Have an other error:

 **if set(meta_graph_def.meta_info_def.tags) == set(tags):
TypeError: unhashable type: 'set'**

### Any other info / logs

I don't know this modify is true.

When I try to convert this is the error I get, so I cannot successfully convert to Lite.

**Comment by abattery** [comment]
Could you use the `saved_model_cli` tool to inspect the available tags in the given saved model?

If the available tags are "serve" and "train", you need to provide them as a set, e.g.,

tf.lite.TFLiteConverter.from_saved_model(
    saved_model_dir, tags=set())  # if the tags are empty.

tf.lite.TFLiteConverter.from_saved_model(
    saved_model_dir, tags=set(["serve", "train"]))  # if the tags are "serve" and "train".

**Comment by dexsr415** [comment]
> Could you use the `saved_model_cli` tool to inspect the available tags in the given saved model?
> 
> If the available tags are "serve" and "train", you need to provide them as a set, e.g.,
> 
> tf.lite.TFLiteConverter.from_saved_model(
> saved_model_dir, tags=set()) # if the tags are empty.
> 
> tf.lite.TFLiteConverter.from_saved_model(
> saved_model_dir, tags=set(["serve", "train"])) # if the tags are "serve" and "train".


Thanks for your reply!

I use  `saved_model_cli`

It report: `MetaGraphDef with tag-set: 'train, serve' contains the following SignatureDefs:`

And I modify my code

`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(["serve", "train"]))`

It report : **ValueError: Only support a single signature key.**

,I modify my code

`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(["train"]))`

It report :  **RuntimeError: MetaGraphDef associated with tags {'train'} could not be found in SavedModel. 
                 To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`**

,then I modify my code

`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(['train, serve']))`

It report :  **RuntimeError: MetaGraphDef associated with tags {'train, serve'} could not be found in SavedModel. 
                 To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`**



**I'm not sure what I should write in the 'set'**

**Comment by abattery** [comment]
Looks like your model has tags, {'train, serve'}. So, you need to specify tags with ['train', 'serve'].

The signatures are different. A signature represents an entry point of the given saved model. You can also get the list of the signatures by the following Python code:

```
loaded = tf.saved_model.load("/tmp/mobilenet/1/")
print(list(loaded.signatures.keys()))
```

Among the signature keys, you need to pick up the one signature key and provide it through the saved model converter API like the following example:

```
tf.lite.TFLiteConverter.from_saved_model(
saved_model_dir, tags=set(["serve", "train"]), signature_keys=["serve_default"]) 
```

**Comment by dexsr415** [comment]
> Looks like your model has tags, {'train, serve'}. So, you need to specify tags with ['train', 'serve'].
> 
> The signatures are different. A signature represents an entry point of the given saved model. You can also get the list of the signatures by the following Python code:
> 
> ```
> loaded = tf.saved_model.load("/tmp/mobilenet/1/")
> print(list(loaded.signatures.keys()))
> ```
> 
> Among the signature keys, you need to pick up the one signature key and provide it through the saved model converter API like the following example:
> 
> ```
> tf.lite.TFLiteConverter.from_saved_model(
> saved_model_dir, tags=set(["serve", "train"]), signature_keys=["serve_default"]) 
> ```

Thanks again for your reply!

I try the python you gave
It shows this:
`[]`

`[]`  Is this None?

So I modify my code
 ### 1
`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(["serve", "train"]), signature_keys=[""])`
Show this error:
**ValueError: Invalid signature key '' found. Valid keys are ''.**

### 2   
`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(["serve", "train"]), signature_keys=None)`
Show this error:
**ValueError: Only support a single signature key.**  (None is default)

**Comment by abattery** [comment]
Is it possible to share your saved model?

I think your saved model does not any signatures. TFLite converter API needs at least one sigature availabe. In such cases, you can re export your TF graph with explicitly defining a signature. Or, the saved model object will be a callable so you can create a simple concrete function to wrap the callable saved model and then, you can convert it through the concrete function converter API.

I recommend re-exporting a new saved model with a signature information.

**Comment by dexsr415** [comment]
> I think your saved model does not any signatures. TFLite converter API needs at least one sigature availabe. In such cases, you can re export your TF graph with explicitly defining a signature. Or, the saved model object will be a callable so you can create a simple concrete function to wrap the callable saved model and then, you can convert it through the concrete function converter API.
> 
> I recommend re-exporting a new saved model with the signaturee information.


Thank for you replay!
 
I re-exporting a new saved model.

It has singnaturee ['serving_default']


Then,i modify code

`converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, tags=set(["train", "serve"]), signature_keys=['serving_default'])`

`tflite_model = converter.convert()`

It reported (when it executes to that "`tflite_model = converter.convert()`"):

**WARNING:tensorflow:Issue encountered when serializing variables.
Type is unsupported, or the types of the items don't match field type in CollectionDef. 
Note this is a warning and probably safe to ignore.**

**error: 'tf_executor.graph' op is not any of a builtin TFLite op, a flex TensorFlow op or a custom TensorFlow op
error: failed while converting: 'main':**

**Comment by abattery** [comment]
Please share simple stand alone code such that we can replicate the issue faced or if possible share a colab gist.

**Comment by dexsr415** [comment]
Thank for you replay!


This is my saved model:

https://drive.google.com/drive/folders/1zbQ_tR2QlsZP-doHnfA_BXkgGczYwLBD?usp=sharing

And this is from : https://github.com/tegg89/SRCNN-Tensorflow  (I upgrade it to tf 2.3)

Change the checkpoint in the file and save it as a saved model. 


**Below is the code I used to convert**


    import os   
    import tensorflow as tf

    trained_checkpoint_prefix = ' ' # ckeckpoint dir
    export_dir = os.path.join('export_dir', '1')

    graph = tf.Graph()
    with tf.compat.v1.Session(graph=graph) as sess:
   
        loader = tf.compat.v1.train.import_meta_graph(trained_checkpoint_prefix + '.meta')
        loader.restore(sess, trained_checkpoint_prefix)

        signature = tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
            method_name=tf.compat.v1.saved_model.signature_constants.PREDICT_METHOD_NAME)
        signature_map = {tf.compat.v1.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:signature}

        builder = tf.compat.v1.saved_model.builder.SavedModelBuilder(export_dir)
        builder.add_meta_graph_and_variables(sess,
                                         [tf.compat.v1.saved_model.SERVING],
                                         signature_def_map=signature_map,
                                         strip_default_attrs=True)
        builder.save()


**I want to practice the process of converting saved model to tflite.**

**Comment by abattery** [comment]
Looks like the signature in the attached saved model does not have any outputs. Could you create a saved model with the signature, which has valid output signature information as well and try again?

**Comment by dexsr415** [comment]
> Looks like the signature in the attached saved model does not have any outputs. Could you create a saved model with the signature, which has valid output signature information as well and try again?



Thank  for you replay!

Sorry, it will take me a long time.

I am figuring out the archive type of tensorflow.

And i tried successfully.

I haven't understood the meaning of the tag and signature of saved_model before, but now I understand it roughly.

**My modify code:**
`      builder = tf.compat.v1.saved_model.builder.SavedModelBuilder("./saved_model/1")`
`     signature = tf.compat.v1.saved_model.predict_signature_def(inputs={'Input_images': self.images},
                                                                  outputs={'myOutput': self.pred})`
`      builder.add_meta_graph_and_variables(sess=sess,
                                           tags=[tf.compat.v1.saved_model.tag_constants.SERVING],
                                           signature_def_map={'predict': signature})`
`      builder.save() `



**This is my saved_model(by use saved_model_cli):**
![image](https://user-images.githubusercontent.com/82639664/115984187-53a87500-a5d8-11eb-89d0-7492a4e94adf.png)




Then I have a question to ask

If I have a saved checkpoint and GraphDef.Can I use these two to convert to saved_model?
I wanted to go through these two before.But the signature has not been specified.
This time I directly changed the source code.

**Comment by abattery** [comment]
> If I have a saved checkpoint and GraphDef.Can I use these two to convert to saved_model?

For the above question, it would be better to ask a separate issue and invite the TF saved model experts.

**Comment by dexsr415** [comment]
> > If I have a saved checkpoint and GraphDef.Can I use these two to convert to saved_model?
> 
> For the above question, it would be better to ask the new question as a separate issue and invite the TF saved model experts.

OK

After sorting it out, I am asking this question.

Thank you for your reply these few days.
