### ISSUE TITLE
tf.strings.lower() does not lower-case non-ASCII characters

### ISSUE THREAD

**Issue by DavidPal** [tensorflow/tensorflow#48551]
**System information**
This bug happens in Colab notebook. It happens on other platforms as well, but that's beside the point.

**Describe the current behavior**

tf.strings.lower() lower cases A-Z to a-z but it does not lower case other unicode characters, e.g. LATIN CAPITAL LETTER E WITH ACUTE, LATIN CAPITAL LETTER Z WITH CARON, and many others, etc. See the code below. 

It seems that tf.strings.lower() keeps all upper-case non-ASCII characters as is. I was unable to find an example of any character outside ASCII that is lower cased correctly. But I did only spot checks.

**Describe the expected behavior**

tf.strings.lower() should lower case all accented characters. E.g. É should become é, Ž should become ž, same as in Python. My understanding of Unicode standard is that there is a language-independent mapping from upper case to lower case for every unicode character. This Unicode web page explains the details: https://unicode.org/faq/casemap_charprop.html 
Tensorflow's tf.strings.lower() should implement this mapping.

**Standalone code to reproduce the issue**

Here is a link to a Colab notebook: https://colab.research.google.com/drive/1LyF0FZp9uMsqsyUGaWEdalhLql5B69k5

Here is the copy of the code from the Colab botebook:

```
# This piece of code demonstrates a bug in tf.strings.lower().

import tensorflow as tf

# Text in Slovak language. (It is first half of a panagram.)
# The text is in 3 different casings: Upper case, lower case, and
# mixed case. In the mixed case, all letters with diacritics 
# are upper case and standard English ASCII letters are lower case.
UPPER_CASE = u"STARÝ KÔŇ NA HŔBE KNÍH ŽUJE TÍŠKO POVÄDNUTÉ RUŽE"
LOWER_CASE = u"starý kôň na hŕbe kníh žuje tíško povädnuté ruže"
MIXED_CASE = u"starÝ kÔŇ na hŔbe knÍh Žuje tÍŠko povÄdnutÉ ruŽe"


class TestLowerCase(tf.test.TestCase):

    # This test case passes.
    # It verifies that, in Python, all three texts
    # are the same after lower casing.
    def test_python(self):
        self.assertEqual(UPPER_CASE.lower(), LOWER_CASE)
        self.assertEqual(MIXED_CASE.lower(), LOWER_CASE)
        self.assertEqual(LOWER_CASE.lower(), LOWER_CASE)

    # This test case passes.
    # It demonstrates the current tensorflow behaviour,
    # which is arguably incorrect.
    def test_tensorflow_current(self):
        tf_upper_case = tf.constant(UPPER_CASE, dtype=tf.string)
        tf_mixed_case = tf.constant(MIXED_CASE, dtype=tf.string)
        self.assertAllEqual(tf.strings.lower(tf_upper_case), tf_mixed_case)

    # This test case fails!
    # It demonstrates the desired/expected behavior.
    def test_tensorflow_desired(self):
        tf_upper_case = tf.constant(UPPER_CASE, dtype=tf.string)
        tf_lower_case = tf.constant(LOWER_CASE, dtype=tf.string)
        self.assertAllEqual(tf.strings.lower(tf_upper_case), tf_lower_case)


# Run all three test cases. The first two pass. The third one fails.
TestLowerCase().test_python()
TestLowerCase().test_tensorflow_current()
TestLowerCase().test_tensorflow_desired()
```

**Comment by tilakrayal** [comment]
@DavidPal ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

Thanks!

**Comment by DavidPal** [comment]
tf.strings.upper() has a similar bug. It does not correctly handle non-ASCII characters.

**Comment by rohan100jain** [comment]
Thanks for the minimal reproduction! If you pass in encoding='utf-8' as an argument to tf.strings.lower, the test seems to pass. It looks like by default if no encoding is provided then we default to ASCII. We'll look into maybe making that the default but there might be some backwards compatibility considerations we need to think through.

**Comment by DavidPal** [comment]
Thanks a lot for the explanation. This makes sense. In retrospect, I feel stupid and I should have guessed it. However, it would nice to update both the online documentation on the web and the functions' docstrings, and list at all these places explicitly the set of allowed encodings, so that people don't trip on this like I did.

As for backward compatibility/default behavior, I don't have any strict opinion. Status quo is fine for now. Long term, defaulting to "utf-8" encoding would be probably more user-friendly.

I am not sure what is the process for submitting a PR against TensorFlow. Once I figure it out, I will try to send to a PR with the documentation and/or docstring update.

**Comment by DavidPal** [comment]
The reason why tf.strings.lower() and its default behavior matters (to me at least) is because of tf.keras.layers.experimental.preprocessing.TextVectorization layer, which is responsible for creating words from a piece of text. The layer, by default, lower cases the text. It calls tf.strings.lower() internally without any encoding parameter and does not handle non-ASCII characters as one would naively expect. Fortunately, the "standardization" logic in TextVectorization layer can specified by the user by passing a custom standardize argument.

**Comment by rohan100jain** [comment]
Thanks David for confirming! I agree we should document this clearly so that users don't trip on it. Please send us a PR with the documentation updates - it'll be super useful! https://www.tensorflow.org/community/contribute/code#contribution_workflow has some instructions that might be helpful. It might be helpful to even add documentation to Keras Preprocessing Layers to indicate this as well.

**Comment by DavidPal** [comment]
Here is the PR with the documentation fix: https://github.com/tensorflow/tensorflow/pull/48911

I am guessing that the online documentation is automatically generated from the files I modify in the PR.

**Comment by DavidPal** [comment]
My PR https://github.com/tensorflow/tensorflow/pull/48911 was merged.
We can close this issue.
