### ISSUE TITLE
Create image_classifier in colab have an error. "unknown image file format. one of jpeg png gif bmp required"

### ISSUE THREAD

**Issue by Duynguyen0897** [tensorflow/tensorflow#48556]
![image](https://user-images.githubusercontent.com/44739285/115004251-d04c9c80-9ed0-11eb-924c-7dcf0060dae8.png)
The images datasets [here](https://babycuatoi.vn/tree.zip)
Help me please!

**Comment by AdityaKane2001** [comment]
@Duynguyen0897 
Can you please share the colab notebook or a minimal standalone reproducible gist?

**Comment by Duynguyen0897** [comment]
> 
> 
> @Duynguyen0897
> Can you please share the colab notebook or a minimal standalone reproducible gist?

The colab notebook [here](https://colab.research.google.com/drive/1hl7WPnzNOEH_MvchRqMGw6omRmy-5Z3y?usp=sharing)
Thank you!

**Comment by AdityaKane2001** [comment]
@Duynguyen0897 
The images in /tree/cam folder are of RGBA type, thus they are not being read properly by the model. Please convert these images to RGB. [This](https://stackoverflow.com/questions/9166400/convert-rgba-png-to-rgb-with-pil) may be helpful.
Hope this helps.

**Comment by Duynguyen0897** [comment]
> 
> 
> @Duynguyen0897
> The images in /tree/cam folder are of RGBA type, thus they are not being read properly by the model. Please convert these images to RGB. [This](https://stackoverflow.com/questions/9166400/convert-rgba-png-to-rgb-with-pil) may be helpful.
> Hope this helps.
Thank for your help!
I converted to .jpeg format and everything was fine

**Comment by AdityaKane2001** [comment]
Please close the issue if the query is resolved.
Thanks
