### ISSUE TITLE
Dilated and causal convolutions on microcontrollers

### ISSUE THREAD

**Issue by Lucy20211** [tensorflow/tensorflow#48567]
@tensorflow/micro

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow version: 2.4.1
- Python version : 3.8

**Describe the problem**

I would like to run inference on a microcontroller above by using a model characterized by Conv1D layers which implement causal convolutions 1D. In particular, in main.cpp I thought I would use something like this:

`// Pull in only needed operations (should match NN layers).`
`// Template parameter <n> is number of ops to be added. Available ops:`
`//` `tensorflow/lite/micro/kernels/micro_ops.h`

`static tflite::MicroMutableOpResolver <1> micro_op_resolver;`
`tflite_status = micro_op_resolver.Conv1D(); `

`if (tflite_status != kTfLiteOk) {`
`error_reporter->Report("Could not add Conv1D op");`
`while(1);`
`}`

However, the Conv1D operation shouldn't be supported by TensorFlow Lite: how can I solve this problem? Have I create a custom operator, in order to implement the op, or there is another way to fix it?
In order to create the op, I wrote this simple code:

`import tensorflow as tf`
`tf.config.run_functions_eagerly(True)`

`input_shape = (1, 7, 1)`
`x = tf.random.normal(input_shape)`

`@tf.function`
`def convol1d():`
`y=tf.keras.layers.Conv1D(1, 3, input_shape=input_shape[1:], name="Conv1D")(x)`
`return y`

`data = convol1d()`
`print("\n\n data is:", data)`

`tflite_model_name = 'convol1d'`
`converter= tf.lite.TFLiteConverter.from_concrete_functions([convol1d.get_concrete_function()])`
`converter.allow_custom_ops = True`
`tflite_model = converter.convert()`
`open(tflite_model_name + '.tflite', 'wb').write(tflite_model)`

If I run it, it appears the following error:

`ValueError: tf.function-decorated function tried to create variables on non-first call.`

Instead, I would expect it:

`Error: Didn't find custom operator for name 'Conv1D'`
`Registration failed.`

If this latter error appeared, I would try to define the functions Prepare and Eval and construct a TfLiteRegistration in a file .cpp, then I would add an AddCustom call to register.cpp, am I right? At this point, if all went well, I would try to use the op. 

Thanks in advance.

**Comment by abattery** [comment]
Unassigning myself from the micro issue.

**Comment by jdduke** [comment]
@njeffrie can you take a look?

**Comment by njeffrie** [comment]
I've seen similar issues, and previously our suggested workaround was to create a model using the conv2d operator instead of conv1d. I don't think conv2d in TFLite or TFLM supports causal padding for convolutions, but somebody more familiar with TFLite would know better than I do.

As you suggested, it seems like your custom op approach is likely best. As you stated, you will have to create a python version for use in training, along with a TFLite or TFLM implementation registered with the same custom op name.

I don't fully understand the custom op implementation you showed above (probably due to my own ignorance of the subject), but it seems odd to use the global "x" within your custom op declaration, rather than passing in an input tensor.

**Comment by Lucy20211** [comment]
Hi @njeffrie, thanks for you reply: I used a global "x" only as a test input for the custom operator (I've never used custom operators before). Regarding the following error:

`ValueError: tf.function-decorated function tried to create variables on non-first call.`

what could it depend on in this case?

**Comment by njeffrie** [comment]
I'm not very familiar with this area, but it seems like [this thread](https://github.com/tensorflow/tensorflow/issues/27120) may be relevant.

Have you tried changing
def convol1d(): to def convol1d(x): and renaming the global x to test_input or something? It looks like other examples pass the input into the tf-function rather than referencing it from within.

**Comment by Lucy20211** [comment]
I had tried with what you suggested; unfortunately it does not work.

**Comment by Lucy20211** [comment]
Could I try to implement a custom operator without using @tf.function?

**Comment by njeffrie** [comment]
I have very little experience with tf functions - perhaps @jdduke can assign this to somebody more familiar.

**Comment by Lucy20211** [comment]
It should be that I get ValueError because I can't create a Keras layer in tf.function (the layer should create variables inside it), but I'm not sure how I could define the layer inside tf.function at this point.

**Comment by Lucy20211** [comment]
I tried with this code:

`import tensorflow as tf`

`input_shape = (1, 7, 1)`

`test_input = tf.random.normal(input_shape)`
`y = None`

`@tf.function`
`def convol1d():`
`global y    `
    `if y is None:`
     `y=tf.keras.layers.Conv1D(1, 3, input_shape=input_shape[1:],name="Conv1D")(test_input)`
    `return y`

`tflite_model_name = 'convol1d'`
`converter=tf.lite.TFLiteConverter.from_concrete_functions([convol1d.get_concrete_function()])`
`converter.allow_custom_ops = True`
`tflite_model = converter.convert()`
`open(tflite_model_name + '.tflite', 'wb').write(tflite_model)`

Howerer, now I get this error:

`AttributeError: 'Tensor' object has no attribute 'numpy'`

I thought I should convert test_input (a tensor) to a numpy array, but I'm not sure on it.

**Comment by Lucy20211** [comment]
I've added `tf.config.run_functions_eagerly(True)` again and used 

`data = convol1d()`
`print("\n\n data is:", data)`

before using TF converter.  I haven't got errors now, but I would expect it:

`Error: Didn't find custom operator for name 'Conv1D'.
Registration failed.`

Instead, it doesn't happen. What could it depend on in this case?
Is it correct to use this snippet of code to implement a custom operator?

**Comment by Lucy20211** [comment]
@jdduke is it worth waiting for implementation of Conv1D? I know that I can use Conv2D instead of Conv1D, but I have to measure performance of my MCU which uses the same Conv1D and make a comparison with Conv2D for different models (if I implemented Conv1D with Conv2D, it should use the same resources and complexity of a Conv2D, so I wouldn't do anything).

**Comment by Lucy20211** [comment]
Ok, I'd still like to try to implement this custom op :) 

By following https://www.tensorflow.org/lite/guide/ops_custom, to access input of sine operator, I should use this line of code from SinEval:

`const TfLiteTensor* input = GetInput(context, node, 0);`

How can I access the inputs of Conv1D op, in particular dilation_rate and test_input? I use this:

`tf.keras.layers.Conv1D(1, 3, dilation_rate = 2, input_shape=input_shape[1:], name="Conv1D")(test_input)`

Moreover, always in c++, how can I access the kernel weights of each layer?

**Comment by Lucy20211** [comment]
To obtain dilation_rate and test_input, can I use 
`const TfLiteTensor* dilation = GetInput(context, node, 6)` and `const TfLiteTensor* input = GetInput(context, node, 0)`?

**Comment by jdduke** [comment]
Actually, now I'm a bit puzzled as to why you're seeing a Conv1D during conversion at all. TF lowers Conv1D to Conv2D automatically [see implementation here](https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/ops/nn_ops.py#L1867). 

As for what a custom op would look like, you have to distinguish between tensors and attributes. Attributes will be embedded in the flexbuffer data for that op, and you would reference it as we do in [this custom MFCC op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/mfcc.cc#L58). It might help if you could share the `.tflite` model that you successfully converted, which includes the Conv1D op?

**Comment by Lucy20211** [comment]
I had not thought that Conv1D is replaced by TFLite Conv2D op. In fact, I've recently found that Conv1D operator is replaced with a TFLite Conv2D op + a Reshape op, during TF to TFLite conversion. It is probably for this reason that the line

`Error: Didn't find custom operator for name 'Conv1D'. Registration failed.`

doesn't appear.

Then, even though there is a custom Conv1D op, the TF to TFLite conversion always favors the TFLite Conv2D op, since it is a builtin op, is it right?

However, if I understand, is there also a chance to prepare a custom op, by following as an example MFCC op? Sorry if I'm insisting, but it's all new to me and I was explicitly asked to implement a Conv1D through a custom op. If there isn't a possibility to do this, I would report it :)

**Comment by Lucy20211** [comment]
At the moment I'd try with this model: https://www.programmersought.com/article/13674618779/, for which I'd add the snippet of code concerning the converter.

I also wanted to ask another thing: in case I had to convert to TFLite a model that uses an op different to conv1D (an op for which it is really necessary to create a custom op), how can I use the converter to convert the model and to force it to allow custom ops at the same time?

**Comment by jdduke** [comment]
Over to @advaitjain for follow-up.

**Comment by advaitjain** [comment]
Similar to https://github.com/tensorflow/tflite-micro/issues/149#issuecomment-886855952, we do not have a direct path to fixing the issue described. Using Conv2D is likely the path of least resistance at the moment (https://github.com/tensorflow/tflite-micro/issues/149#issuecomment-858111382).
