### ISSUE TITLE
Model datatype

### ISSUE THREAD

**Issue by prabhakarlad** [tensorflow/tensorflow#48568]
Hi,

I am trying print the summary of give model. I am more specifically interested in the datatype of the model.

I have tried the print_model_analysis() but this doesn't print the datatype. I have also tried summarize_graph utility but had no luck.

Is there something I am missing ? Are there any apis to do so ?

Cheers,
Prabhakar

**Comment by bhack** [comment]
You can use something like
```
import tensorflow as tf
input = tf.keras.Input(shape=(100,), dtype='int32', name='input')
x = tf.keras.layers.Embedding(
    output_dim=512, input_dim=10000, input_length=100)(input)
x = tf.keras.layers.LSTM(32)(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
output = tf.keras.layers.Dense(1, activation='sigmoid', name='output')(x)
model = tf.keras.Model(inputs=[input], outputs=[output])
dot_img_file = '/tmp/model_1.png'
tf.keras.utils.plot_model(model, to_file=dot_img_file, show_shapes=True, show_dtype=True)
```

![image](https://user-images.githubusercontent.com/1710528/115073556-c8085780-9ef8-11eb-94d5-b35c97a0c62c.png)

**Comment by prabhakarlad** [comment]
Hi @bhack,

Thank you for the response, your suggestion prints the data type of each tensor.

I have come with below snip code which prints the dtype of model.

interpreter = tf.lite.Interpreter(model_path=args.input_path)
input_type = interpreter.get_input_details()[0]['dtype']
print('input: ', input_type)
output_type = interpreter.get_output_details()[0]['dtype']
print('output: ', output_type)

Cheers,
Prabhakar

**Comment by tilakrayal** [comment]
@prabhakarlad ,

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.

Thanks!

**Comment by prabhakarlad** [comment]
Hi @tilakrayal,

Similar to above for tflite is there something similar to get dType for onnx and pb models ?

Cheers,
Prabhakar

**Comment by bhack** [comment]
When you a Keras model you can print model input/output dtype. For onnx you need to ask in an onnx repository.

e.g from https://stackoverflow.com/questions/60792775/keras-how-to-check-what-is-the-data-type-expected-in-the-input-layer
```python
import tensorflow as tf 
x = tf.keras.layers.Input((2,), dtype=tf.float64)
res = tf.keras.layers.Dense(2, dtype=tf.float64)(x)
model = tf.keras.models.Model(x, res)

print(model.inputs[0].dtype, model.outputs[0].dtype)
```

**Comment by tilakrayal** [comment]
@prabhakarlad ,

**Comment by tilakrayal** [comment]
@prabhakarlad ,

 Please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status and for new issues please submit new issue from [this link ](https://github.com/tensorflow/models/issues/new/choose)and fill in the template, so that we can track the issue there. 

Thanks!

**Comment by prabhakarlad** [comment]
Thank you for the pointers @bhack
