### ISSUE TITLE
RTX 3070 gpu usage is low in CNN model training using tensorflow.

### ISSUE THREAD

**Issue by hogbal** [tensorflow/tensorflow#48560]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): tensorflow 2.5.0rc1
- Python version: python 3.6.9
- CUDA/cuDNN version: 11.2/8.1
- GPU model and memory: RTX 3070

**Describe the current behavior**

I trained the CNN model below using Docker.
It took 10 minutes per epoch on the GTX 1060, but over 20 minutes per epoch on the RTX 3070. When I checked the gpu usage through the nvidia-smi command, it was mostly 0%.
Why does the RTX 3070 have a slower training time than the GTX 1060? How do I fix it?

tensorflow recognizes RTX 3070 and uses vram as well.
docker used tensorflow/tensorflow:2.5.0rc1-gpu-jupyter
The cpu is using the intel i7-10700k

**Standalone code to reproduce the issue**
```
effnet = EfficientNetB0(weights='imagenet', include_top=False, input_shape=input_shape)`
def create_model():
    model = keras.Sequential()
    model.add(effnet)
    model.add(GlobalAveragePooling2D())
    
    model.add(Dense(512))
    model.add(BatchNormalization())
    model.add(ReLU())
    
    model.add(Dense(128))
    model.add(BatchNormalization())
    model.add(ReLU())
    
    model.add(Dense(32))
    model.add(BatchNormalization())
    model.add(ReLU())
    model.add(Dense(num_classes, activation="sigmoid"))
    return model
```
```
def scheduler(epoch, lr):
    if epoch == 0:
        lr = init_learning_rate
    else:
        lr = lr * 0.9
    
    print('learning rate: {:.10f}'.format(lr))
    tf.summary.scalar('learning_rate', data=lr, step=epoch)
    return lr

learning_rate_scheduler = tf.keras.callbacks.LearningRateScheduler(scheduler)
```
```
model = create_model()

f1_score = tfa.metrics.F1Score(
    num_classes=num_classes,
    average='macro')

optimizer = tf.keras.optimizers.Adam(learning_rate=init_learning_rate)
model.compile(loss='binary_crossentropy', optimizer=optimizer,
              metrics=['accuracy',f1_score])
```
```
logdir = "/tf/notebooks/compete/Plant_Pathology_2021/logs/scalars/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
file_writer = tf.summary.create_file_writer(logdir + "/metrics")
file_writer.set_as_default()
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)

history = model.fit(
        train_generator,
        steps_per_epoch=len(train_generator),
        epochs=num_epochs,
        validation_data=validation_generator,
        validation_steps=len(validation_generator),
        callbacks=[tensorboard_callback,learning_rate_scheduler],
        verbose=1)
```

**Comment by amahendrakar** [comment]
@hogbal,
Could you please run the below code snippet and share the results with us
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```

Also, take a look at the TensorFlow profiling tool [link #1](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras), [link #2](https://www.tensorflow.org/guide/profiler#gpu_kernel_stats) and let us know if it helps. Thanks!

**Comment by hogbal** [comment]
@amahendrakar
The result of that code is shown below.
<pre>
INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2
Num GPUs Available:  1
</pre>

After using the TensorFlow profiling tool, I will share the results :)

**Comment by hogbal** [comment]
Thank! As a result of using the TensorFlow profiling tool, it was a problem of input time.
I put an image using a data generator, but it was solved when I changed it to TFRecord.
