### ISSUE TITLE
tensortflow-lite installation and packaging

### ISSUE THREAD

**Issue by w3sip** [tensorflow/tensorflow#48575]
Hello,

I'm trying to create a standalone artifact of TFLite SDK. Running

`cmake -DCMAKE_INSTALL_PREFIX=~/tmp/foo ../tensorflow/tensorflow/lite
make
make install
`

The build completes, but the result of the build isn't installed. How can I assemble a standalone package?

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by terryheo** [comment]
For C++ API, you should use C++ CMake project to use the libraries.
For C API, you can use the output directly.
https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library
