### ISSUE TITLE
tf.nn.compute_average_loss documentation/code misaligned

### ISSUE THREAD

**Issue by AdamByerly** [tensorflow/tensorflow#48572]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/nn/compute_average_loss

## Description of issue (what needs changing):
The name of the method itself and the documentation at the URL above implies that the calculation will be an average (mean) reduction.
But in the source code (https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/ops/nn_impl.py#L391-L446), line 446 calculates a sum reduction.
Either this is a mistake, and the code should be changed to do a mean reduction, or the documentation should be made more clear as to what the method actually does and why.

**Comment by bhack** [comment]
Is the average not over the `global_batch_size`?

**Comment by AdamByerly** [comment]
It does indeed divide the sum by the global batch size.  I will close as user error.  I was passing in the global batch size since I had it available, but the error was that by not naming the parameter, the scalar global batch size was being broadcast as a weight to add to each example, thus producing the summing behavior I was seeing, despite the tensorflow code being correct.
