### ISSUE TITLE
 ai-explanations-image.ipynb - Saved model error 

### ISSUE THREAD

**Issue by jocelynbaduria** [tensorflow/tensorflow#48579]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
https://colab.research.google.com/github/GoogleCloudPlatform/ml-on-gcp/blob/master/tutorials/explanations/ai-explanations-image.ipynb#scrollTo=Yn8hEAHiXaE7

Performance issues
Error encountered during saved model of iris Dataset Flower - using sample colab tutorial - ai-explanations-image.ipynb

![Screen Shot 2021-04-16 at 4 47 57 PM](https://user-images.githubusercontent.com/62075076/115094774-97fa8d80-9ed3-11eb-8f60-cc93d26dad98.png)

**Comment by amahendrakar** [comment]
@jocelynbaduria,
Although, I do not have access to a GCP project, I was able to export the model to the local storage without any issues. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c69ed74c7b2906ca0436478cddbf4023/48579.ipynb#scrollTo=Yn8hEAHiXaE7&line=1&uniqifier=1). Thanks!

**Comment by jocelynbaduria** [comment]
Hi @amahendrakar 
I'll check if it works with my setup in GCP AI Platform. 
If I found any issues again, will provide feedback to you. 
Thanks..

**Comment by Saduf2019** [comment]
@jocelynbaduria 
Could you please update if this is still an issue.

**Comment by jocelynbaduria** [comment]
@Saduf2019 , I will update you, just crunching with projects and hw. Thanks!

**Comment by Saduf2019** [comment]
@jocelynbaduria
Can you please confirm.
