### ISSUE TITLE
how use session in function for TF1.14?

### ISSUE THREAD

**Issue by TomatoBoy90** [tensorflow/tensorflow#48585]
I build a seesion,but I use it in functoin,it will call me that No default TensorFlow session found.
how I reslove the issue?

**Comment by AdityaKane2001** [comment]
@TomatoBoy90 
It is recommended that you use TensorFlow 2.4.1, which is the latest stable release. Installation guide [here](https://www.tensorflow.org/install?hl=en).

**Comment by UsharaniPagadala** [comment]
@TomatoBoy90  
Could you please fill the issue template

Can you share more details for us to analyse, simple stand alone code to replicate the issue faced or a colab gist with the code and error. Thanks

**Comment by UsharaniPagadala** [comment]
@TomatoBoy90 
Could you please provide the above requested details.Thanks

**Comment by UsharaniPagadala** [comment]
@TomatoBoy90 

Please confirm if the issue is still persist
