### ISSUE TITLE
TFlite Converter - EfficientDet conversion fails on int quantization (IndexError: _Map_base::at)

### ISSUE THREAD

**Issue by Fapannen** [tensorflow/tensorflow#48587]
Hello, 

I am trying to convert EfficientDet-D4 model to tflite, with integer quantization with CPU fallback for unsupported operations. I am encountering error same as [this issue](https://github.com/tensorflow/tensorflow/issues/43239). I have tried using different converter settings but none of them work. Interestingly, though, EfficientDet-D0 converts with this type of quantization without any issue. What I've noticed is that all EfficientDet versions from D1-D7 have this error, only D0 converts successfully.

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

I am using slightly modified code from [EfficientDet repo](https://github.com/google/automl/tree/master/efficientdet), file "inference.py". I had to enable TF Select Ops in order to convert the model to tflite.

I am converting the model using guidelines on EfficientDet github repo (model_inspect.py)

def representative_dataset():
        files = [f for f in os.listdir('./representative_dataset') if os.path.isfile(os.path.join("representative_dataset", f))]
        for file in files:
           file = "representative_dataset/" + file
           img = cv2.imread(file, cv2.IMREAD_COLOR)
           resized = cv2.resize(img, (1024, 1024), interpolation = cv2.INTER_CUBIC)
           rgb_resized = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)
           np_resized = np.array([rgb_resized])
           yield [np_resized.astype(np.uint8)]

if tflite_path:
      height, width = utils.parse_image_size(self.params['image_size'])
      input_name = signitures['image_arrays'].op.name
      input_shapes = {input_name: [None, height, width, 3]}
      converter = tf.lite.TFLiteConverter.from_saved_model(
          output_dir,
          input_arrays=[input_name],
          input_shapes=input_shapes,
          output_arrays=[signitures['prediction'].op.name])
      converter.optimizations = [tf.lite.Optimize.DEFAULT]
      converter.representative_dataset = representative_dataset
      converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
      tflite_model = converter.convert()

This code results in the following error

Traceback (most recent call last):
  File "../automl/efficientdet/model_inspect.py", line 520, in <module>
    app.run(main)
  File "/home/fapannen/.local/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/fapannen/.local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "../automl/efficientdet/model_inspect.py", line 513, in main
    trace_filename=FLAGS.trace_filename)
  File "../automl/efficientdet/model_inspect.py", line 462, in run_model
    self.export_saved_model(**config_dict)
  File "../automl/efficientdet/model_inspect.py", line 151, in export_saved_model
    driver.export(self.saved_model_dir, self.tflite_path, self.tensorrt)
  File "/mnt/c/Users/Owner/Desktop/git/Thesis-EfficientDet/automl/efficientdet/inference.py", line 621, in export
    tflite_model = converter.convert()
  File "/home/fapannen/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1947, in convert
    return super(TFLiteConverter, self).convert()
  File "/home/fapannen/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1313, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/fapannen/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 461, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/home/fapannen/.local/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 100, in calibrate_and_quantize
    self._calibrator.FeedTensor(sample)
[tflitelog.txt](https://github.com/tensorflow/tensorflow/files/6328939/tflitelog.txt)

### 5. (optional) Any other info / logs
Attached full traceback log.

Any help is highly appreciated.
Cheers,
Tomas

**Comment by abattery** [comment]
@teijeong could you triage this issue?

**Comment by tilakrayal** [comment]
@Fapannen ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset  or colab link to reproduce the issue reported here.

Thanks!

**Comment by Fapannen** [comment]
Hello, sure.

1) Clone [EfficientDet repo](https://github.com/google/automl/tree/master/efficientdet)

2) mkdir <CUSTOM_DIR>
    cd <CUSTOM_DIR>

3) Download and unpack the model
    Concrete model doesnt matter, d1-d7 all have the issue
    wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-d4.tar.gz

    tar xf efficientdet-d4.tar.gz   

4) in <path_to_efficientdet_repo>/automl/efficientdet/inference.py, line 626, enable SELECT_TF_OPS 
    (https://www.tensorflow.org/lite/guide/ops_select)

4.1) Dataset does not matter, [dummy dataset](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization) yields the same error.
      
      def representative_dataset():
          for _ in range(100):
            data = np.random.rand(1, 1024, 1024, 3)
            yield [data.astype(np.uint8)]

4.2) Add to the conversion code

      converter.optimizations = [tf.lite.Optimize.DEFAULT] 
      converter.representative_dataset = representative_dataset

5) try to convert the model 
`python3 <path_to_efficientdet_repo>/automl/efficientdet/model_inspect.py --runmode=saved_model --model_name=efficientdet-d4 \
--ckpt_path=<CUSTOM_DIR>/efficientdet-d4 --saved_model_dir=<CUSTOM_DIR>/efficientdet-d4/saved_model \
--tflite_path=<CUSTOM_DIR>/efficientdet-d4.tflite`

**Comment by Fapannen** [comment]
I have tried converting this with tf-nightly ('2.6.0-dev20210418'), which seems to produce an tflite output. Closing the issue for now.
