### ISSUE TITLE
string_input_producer has no analogue for other dtypes

### ISSUE THREAD

**Issue by bschreck** [tensorflow/tensorflow#486]
It would be nice to a corresponding int_input_producer for producing a queue cycles through labels, for instance. This is a super easy fix by just adding another wrapper around _input_producer.

**Comment by girving** [comment]
@josh11b: Why isn't this just `input_producer`?  It doesn't seem to be at all string specific.

**Comment by bschreck** [comment]
It seems like they wanted to make it convenient to loop through filenames for internal reasons, but for some reason didn't need it for any other file type. But it's just as easy to use _input_producer with another data type.

**Comment by girving** [comment]
@bschreck: `_input_producer` is a fine solution for now, but it isn't part of the public API and will go away once we implement `__all__`.  However, unless there's a reason we should probably remove the underscore and make it part of the public API.

**Comment by martinwicke** [comment]
+1
