### ISSUE TITLE
Support for OV7675 camera module

### ISSUE THREAD

**Issue by narvekarnm** [tensorflow/tensorflow#48604]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): not applicable (using the Arduino_TensorFlowLite installed from the Arduino IDE)
- Tensorflow version (commit SHA if source): Arduino_TensorFlowLite. 2.4.0-ALPHA
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33 BLE Sense

The image provider source file for the person detection example under TFLite Micro, extends support only for the ArduCam camera module OV2640. 

Can the support be extended to camera module OV7675, since the TinyML starter kit contains this camera module?

Meanwhile, I made the following updates to hopefully get it up and running, but without any success:

File: Arduino\libraries\ArduCAM\memorysaver.h
Updates: 
1. Uncomment #define ARDUCAM_SHIELD_V2
2. Uncomment #define OV7675_CAM

File: Arduino\libraries\Arduino_TensorFlowLite\examples\person_detection\arduino_image_provider.cpp
Updates:
1. LOC 54: Replace OV2640_MINI_2MP_PLUS with OV7675_CAM
2. LOC 65: Replace OV2640 with OV7675

Upon uploading the compiled software to the microcontroller, the camera initialization fails with the following error:
Can't communicate with Arducam

I assume the registers are different for the OV7675 as compared to OV2640 and the arduino_image_provider.cpp needs to be updated with the correct register information.

Could you please provide me a solution to this issue?

Thank you.

**Comment by ai2ys** [comment]
I am facing the same issue.
Are there any updates regarding the support of the TinyML starter kit with the OV7675?

**Comment by mohantym** [comment]
Hi @narvekarnm !
We are checking to see whether you still need help in this issue . Have you checked this [document ](https://tinyml.seas.harvard.edu/assets/other/4D/22.03.11_Marcelo_Rovai_Handout.pdf)  which includes instructions for OV7675 too.
Please check the examples from [tflite-micro-arduino ](https://github.com/tensorflow/tflite-micro-arduino-examples)repo and let us know.

Thank you!
