### ISSUE TITLE
Old makefile target in person dection example README

### ISSUE THREAD

**Issue by alanvgreen** [tensorflow/tensorflow#48607]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Debian Linux
- TensorFlow installed from source
- Tensorflow version  7e55a20
- Target platform: host

**Describe the problem**

The README documentation for the "Run the tests on a development machine" of the [person_detection example README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/README.md#run-the-tests-on-a-development-machine) specifies a wrong make target. This PR shows the incorrect target and what it ought to be corrected to: #48594

**Please provide the exact sequence of commands/steps when you ran into the problem**

I was attempting to follow the instructions at [tensorflow/lite/micro/examples/person_detection/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/README.md#run-the-tests-on-a-development-machine) for running person detection test on a development machine.

The second step is:

```
make -f tensorflow/lite/micro/tools/make/Makefile test_person_detection_test
```

This fails with the message

```
make: *** No rule to make target 'test_person_detection_test'.  Stop.
```

**Comment by rmothukuru** [comment]
@alanvgreen,
Can you please confirm if we can close this issue as [the respective PR](https://github.com/tensorflow/tensorflow/pull/48594) has been merged? Thanks!
