### ISSUE TITLE
Make GreedyMemoryPlanner::PrintMemoryPlan accessible 

### ISSUE THREAD

**Issue by alanvgreen** [tensorflow/tensorflow#48605]
@tensorflow/micro

**System information**
- All distributions
- Source
- All version to date
- Any platform with UART output

**Describe the problem**

[GreedyMemoryPlanner::PrintMemoryPlan()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/memory_planner/greedy_memory_planner.h#L84) prints information about head memory allocation to the console. It has proven quite useful for comparing memory usage by different model archtectures and understanding how to reduce memory use.

While asking questions about memory use, I was advised to add a call to GreedyMemoryPlanner() to [MicroAllocator::CommitPlan()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/micro_allocator.cc#L345) this worked, but required casting the `MemoryPlanner *` to a `GreedyMemoryPlanner *`. We can avoid this cast by moving the call to PrintMemoryPlanner() up the call stack to [MicroAllocator::CommitStaticPlan](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/micro_allocator.cc#L1080). 

Since not all users will benefit from seeing the memory plan, and since it is reasonable to use the user to make this choice at compile time, I suggest adding a new preprocessor define that will, when present, cause the memory plan to be printed.

There is a sample PR at #48596 

My immediate motivation for this issue is to be allow the memory plan to be printed (when requested) for users of the https://github.com/google/CFU-Playground, and I am working on a non-open source project that would also benefit.

**Please provide the exact sequence of commands/steps when you ran into the problem**

nil.

**Comment by Venkat6871** [comment]
Hi **@alanvgreen** ,

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved .

Thank you!

**Comment by alanvgreen** [comment]
Yup, fixed for me, at least it was when I last looked, post-merge.
