### ISSUE TITLE
Bug in ragged version of tf.losses.SparseCategoricalCrossentropy

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#48609]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Debian Buster**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v1.12.1-55105-ga7116dd3913 2.6.0-dev20210418**
- Python version: **3.7.10**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

The ragged version of `tf.losses.SparseCategoricalCrossentropy()` fails when the inner shape (the number of classes in the prediction) is not ragged (which is the default if the predictions are generated by a Dense layer).

In other words, while the following works,
```python
y_true = tf.ragged.constant([[0, 1], [2]])
y_pred = tf.ragged.constant([[[.9, .05, .05], [.5, .89, .6]], [[.05, .01, .94]]], dtype=tf.float32)
print(y_true.shape, y_pred.shape)
>>> (2, None) (2, None, None)
print(tf.losses.SparseCategoricalCrossentropy()(y_true, y_pred))
```
the following code fails:
```python
y_true = tf.ragged.constant([[0, 1], [2]])
y_pred = tf.ragged.constant([[[.9, .05, .05], [.5, .89, .6]], [[.05, .01, .94]]], ragged_rank=1, dtype=tf.float32)
print(y_true.shape, y_pred.shape)
>>> (2, None) (2, None, 3)
print(tf.losses.SparseCategoricalCrossentropy()(y_true, y_pred))
```

**Describe the expected behavior**

The computation should not crash.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1k8POHBqlHn4Q5_7GUuaINdmX4F-u3Ktb?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to

Adding @pedro-r-marques who wrote the code.

**Comment by foxik** [comment]
Adding @pedro-r-marques who wrote the code.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.4.1 and nightly versions. Please find the gist here. Thanks!
