### ISSUE TITLE
TF/XLA ignores tf.config set_visible_devices API and initializes all GPUs in the system

### ISSUE THREAD

**Issue by bas-aarts** [tensorflow/tensorflow#48615]
This leads to many superfluous memory allocations, possibly leading to OOM.

Reproduction instructions for the duplicate memory allocations when running with XLA on a multiGPU host.
Use https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py as test.py
this test uses the “set_visible_devices” TF API

when running with
TF_XLA_FLAGS="--tf_xla_auto_jit=1 --tf_xla_enable_xla_devices=true"  python3 test.py
memory is allocated on the visible GPU only. This is the expected behavior, observed with TF 2.3

when running with
TF_XLA_FLAGS="--tf_xla_auto_jit=1 --tf_xla_enable_xla_devices=false"  python3 test.py
memory is allocated on all GPUs in the system. This behavior does not honor the tf.config set_visible_devices API, observed with > TF2.4
 
This issues is similar to the closed horovod issue https://github.com/horovod/horovod/issues/2548.
That issue was closed prematurely, as the presumed fix was not compatible with distributed strategy.

**Comment by cheshire** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/eaa0c588cf44e0c436560738ec361cbc4861cb2d

**Comment by trentlo** [comment]
> Fixed in [eaa0c58](https://github.com/tensorflow/tensorflow/commit/eaa0c588cf44e0c436560738ec361cbc4861cb2d)

I confirm it fixes the issue. Thanks!
