### ISSUE TITLE
@tf.function triggers "AttributeError: 'Tensor' object has no attribute 'ndim'"

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#48612]
TensorFlow version: `v2.4.0-49-g85c8b2a817f 2.4.1`

**Minimal Example**
```python
import tensorflow as tf

@tf.function
def f(a):
    return a.ndim

x = tf.zeros((3, 4))
f(x)
```

**Describe the current behavior**
```python
AttributeError: 'Tensor' object has no attribute 'ndim'
```

**Describe the expected behavior**
```python
<tf.Tensor: shape=(), dtype=int32, numpy=2>
```

**This actually works**
```python
import tensorflow as tf

@tf.function
def f(a):
    return len(a.shape)

x = tf.zeros((3, 4))
f(x)
```

This problem occured in https://github.com/jonasrauber/eagerpy/issues/36

**Comment by bhack** [comment]
You are in graph mode I think you need something like:
```python
import tensorflow as tf

@tf.function
def f(a):
    tf.print(tf.rank(a))
    return tf.rank(a)

x = tf.zeros((3, 4))
f(x)
```

**Comment by jonasrauber** [comment]
@bhack I am not sure I follow. Of course I can use other ways to achieve the same (see also my shape example), but the issue that I report is that the `ndim` attribute doesn't work in functions decorated with `@tf.function` and it should. Are you saying this is intended behavior? If so, I don't see why.

**Comment by bhack** [comment]
Cause `ndim` is in the EagerTensor base class non in the Tensor class:

https://github.com/tensorflow/tensorflow/blob/8ce4ae914b6d2e2b7a324ebca3e9a1e5dfba074a/tensorflow/python/framework/ops.py#L1217

**Comment by jonasrauber** [comment]
Yes, that's what I think should be changed ;-)

**Comment by bhack** [comment]
It was introduce 3 years ago https://github.com/tensorflow/tensorflow/commit/7da6a83b74f467929032dce95794ef0197d46b20. Probably just for numpy compatibility cause rank it is not implemented for `EagerTensor`:

https://github.com/tensorflow/tensorflow/blob/b7121255625688775e5d582d5bcead68b5650629/tensorflow/python/framework/ops.py#L1131-L1141

**Comment by jonasrauber** [comment]
In the end it boils down to this: the API should be consistent, so that the same code works with and without `@tf.function`.

**Comment by bhack** [comment]
But in Graph execution _rank could be `None`. Do you want to handle ndim `None` in the graph case?
https://github.com/tensorflow/tensorflow/blob/906c8d5c5b9dbd930b0c2d41c0fe8650b746b1cf/tensorflow/python/framework/ops.py#L548-L554

https://github.com/tensorflow/tensorflow/blob/906c8d5c5b9dbd930b0c2d41c0fe8650b746b1cf/tensorflow/python/framework/ops.py#L308-L316

**Comment by jonasrauber** [comment]
Yes. If you want, you could still raise an `AttributeError`, but only selectively if `ndim` is actually unknown.

It doesn't make sense to delegate this to downstream code / libraries. Imho, they should have to care as little as possible about whether the code is eventually wrapped by `@tf.function` or not.

**Comment by bhack** [comment]
@tensorflow/api-owners What do you think about this request?

**Comment by UsharaniPagadala** [comment]
@jonasrauber 

Could you Please move this issue to closed status if is is resolved.Thank you

**Comment by jonasrauber** [comment]
@UsharaniPagadala Has there been an update that fixes this?

**Comment by mdanatg** [comment]
This is an inconsistency in the Tensor class. I see `ndim` was added to `EagerTensor` (forwarding to `.shape.ndims`), but not to the base `Tensor` class). That should be a straightforward fix.

The recommended method right now is `.shape.rank` and that should work consistently, but all these do need to be cleaned up.

**Comment by Conchylicultor** [comment]
Any update on this ? Our users at google are also affected by this (using `.ndim` inside `@tf.function` even when the shape is statically known)

**Comment by faizan-m** [comment]
@Conchylicultor For a short term fix, have you considered using `.shape.rank` instead?

**Comment by MegaCreater** [comment]
Same here (with me) -> #59712

**Comment by JW1992** [comment]
Hi folks we recently submitted a fix for this. Please check the corresponding test [here](https://github.com/tensorflow/tensorflow/blob/8a216d2c29881745c9851dd3e22b11eca56b96c3/tensorflow/python/framework/ops_test.py#L108).
