### ISSUE TITLE
Why XLA leads to much more cuMemcpyHtoDAsync calls?

### ISSUE THREAD

**Issue by VertexC** [tensorflow/tensorflow#48613]
I did some profiling shows that, for a resnet50 inference task, (V100 batch=64), xla jit will have 5000 more cuMemcpyHtoDAsync calls in average. For some research purpose, I would like to decrease the number of cuMemcpyHtoDAsync calls.

I notice that there is hlo memory scheduler in XLA that might do the same thing as described in Grapper's page: "Memory optimizer - Analyzes the graph to inspect the peak memory usage for each operation and inserts CPU-GPU memory copy operations for swapping GPU memory to CPU to reduce the peak memory usage." 

Does hlo memory scheduler minize the peak memory in the same way which leads to more  cuMemcpyHtoDAsync calls? If true, how to disable such optimization?

Would really appreciate any ideas on this.

**Comment by kevint324** [comment]
I assume those extra memory transfers are related to JIT optimization and they would only run once during the first warmup run.
After the first batch there should be less memory transfers.

**Comment by VertexC** [comment]
@kevint324 Greate thanks for the hint. I just tried and result did show that most memory transfers happends at first warmup run. 

Just out of curiousity, do you have any idea why XLA Jit optimization need so many memory transfers?

**Comment by kevint324** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/xla/service

There are quite some hlo and llo optimization passes during the XLA setup stage.

**Comment by VertexC** [comment]
@kevint324 Thanks! I'll take a look into it.
