### ISSUE TITLE
Example mnist_rnn Not Working with Docker Image

### ISSUE THREAD

**Issue by claytantor** [tensorflow/tensorflow#4861]
# Issue: Example mnist_rnn does run on docker image.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-3bb5b939d552> in <module>()
      3 from __future__ import print_function
      4 
----> 5 from sklearn import metrics, preprocessing
      6 
      7 import tensorflow as tf

ImportError: No module named sklearn

```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

An example in the code base does not work with the docker image. It is the opinion of the filer that all examples should run without any need for configuration on the docker image because the project has control over what is installed on the docker image.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/mnist_rnn.py

### Environment info
Operating System:

docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow

>Installed version of CUDA and cuDNN: 

**NONE, CPU based container**

If installed from binary pip package, provide:

>The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
# python -c "import tensorflow; print(tensorflow.__version__)"
0.11.0rc0
```

> If installed from source, provide 

Not installed from source

>If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Example given at beginning of ticket.

>What other attempted solutions have you tried?

Removed all references to sklearn. Application works.

```
# It's useful to scale to ensure Stochastic Gradient Descent will do the right thing
#scaler = preprocessing.StandardScaler()
#X_train = scaler.fit_transform(X_train)
#X_test = scaler.fit_transform(X_test)
```

> Logs or other output that would be helpful

No logs produced.

**Comment by jart** [comment]
Try running `sudo apt-get install python-sklearn` inside the Docker container.

Thank you for reporting this issue. I'm writing up a change to the Dockerfile now so others don't run into this same problem. It'll be exported to GitHub in a matter of days. This bug will be closed when that happens.
