### ISSUE TITLE
Tesla V100 is slower than GTX 1660 super!?

### ISSUE THREAD

**Issue by Puppeteer-HML** [tensorflow/tensorflow#48629]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- CUDA/cuDNN version: CUDA 11.0, cuDNN 8.0.4
- GPU model and memory: Tesla V100S-16Q / GTX 1660 super 8G

Recently I'm working on a detection project. The network I'm using is efficientdet-d0. When I'm training my network on company's server, it is slower than training it on my desktop, by 40%~50%. 

For example, with same code (same model, same data, same batch-size, same everything), my desktop (GTX 1660 super 8G) spends average 250ms each step, while on server (virtual machine, Tesla V100S-16Q), it needs average 360ms per step. And eventually, training time becomes hours more after many epochs.

Both task manage and nvidia-smi show that CUDA is working so I'm using GPU training. And my colleagues who use Darknet and Pytorch don't have such issue and they all speed up the training when using Tesla GPU.

Does the tf code need adjustment when using Tesla GPU?

**Standalone code to reproduce the issue**
The efficientdet code is from [bubbliiiing](https://github.com/bubbliiiing/efficientdet-tf2), except that I'm using tf.keras.applications.EfficientNetB0 as backbone.

**Comment by sanjoy** [comment]
This is unusual.  Can you grab a profile using the [TensorBoard profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) to see if anything jumps out?

**Comment by Venkat6871** [comment]
Hi **@Puppeteer-HML** ,
- TensorFlow can be configured to use specific GPUs or a subset of available GPUs. Ensure that your code is utilizing the Tesla V100S-16Q on the server and not defaulting to another GPU or using CPU only.
- Check if TensorFlow is using GPU resources effectively by monitoring GPU utilization during training. You can use tools like nvidia-smi to check GPU usage and ensure that the GPU is being fully utilized during training.

Thank you!
