### ISSUE TITLE
Change "Simple Audio Recognition" to right link

### ISSUE THREAD

**Issue by wenwu-glagle** [tensorflow/tensorflow#48627]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

The link of "Simple Audio Recognition" in  tensorflow/lite/micro/examples/micro_speech/train/README.md is not right anymore, it jumps to https://www.tensorflow.org/tutorials/sequences/audio_recognition before, but now is https://www.tensorflow.org/tutorials/audio/simple_audio .

So need to update.

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by rthadur** [comment]
related PR has been approve and will be merged soon. Thank you
