### ISSUE TITLE
tf.ragged.stack doesn't work for multidimensional tensors

### ISSUE THREAD

**Issue by michaelyhuang23** [tensorflow/tensorflow#48624]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS BigSur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): installed by pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
a =tf.constant([[[3,4,5],[3,4,5]],[[3,4,5],[3,4,5]],[[3,4,5],[3,4,5]],[[3,4,5],[3,4,5]]])
b = tf.constant([[[3,3,4,5],[3,3,4,5],[3,3,4,5]],[[3,3,4,5],[3,3,4,5],[3,3,4,5]],[[3,3,4,5],[3,3,4,5],[3,3,4,5]]])
print(a.shape,b.shape)
c = tf.ragged.stack([a,b],axis=0)
```
When I attempt to stack two tensors of same rank. If the rank is $$\ge 2$$, it produces an error saying:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [8,3] vs. shape[1] = [9,4] [Op:ConcatV2] name: concat`

I can workaround this by making a, b both ragged tensors

**Describe the expected behavior**

It should stack them without problem

I traced it into the definition of the tf.ragged.stack function; It appears that the code runs line 180. It seems to assume that I am trying to use normal tf.stack when I have all elements as tensors.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_concat_ops.py", line 120, in stack
    return _ragged_stack_concat_helper(values, axis, stack_values=True)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_concat_ops.py", line 197, in _ragged_stack_concat_helper
    return _ragged_stack_concat_axis_0(rt_inputs, stack_values)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_concat_ops.py", line 222, in _ragged_stack_concat_axis_0
    concatenated_flat_values = array_ops.concat(flat_values, axis=0)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 1677, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1193, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/michaelhyh/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [8,3] vs. shape[1] = [9,4] [Op:ConcatV2] name: concat
```

**Comment by saikumarchalla** [comment]
@michaelyhuang23  I tried to reproduce the issue with 2 dimensional matrix and it is working fine  but  when i tried with 3  dimensional matrix, getting the same error as mentioned.  

Was able to reproduce the issue with TF 2.4.1 and tf-nightly version as well. Thanks!

**Comment by chunduriv** [comment]
I was able to reproduce the issue on colab using `TF2.6` and `TF-nightly(2.8.0-dev20211003)`. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/da6e69298bb7e6f277e3636a0d7c4c0d/48624.ipynb) for reference.Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
