### ISSUE TITLE
TPU ops are compiled by default despite of if_libtpu or if_with_tpu_support configurations

### ISSUE THREAD

**Issue by kevint324** [tensorflow/tensorflow#48630]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): UBUNTU18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): SOURCE
- TensorFlow version: TF2.4.1
- Python version:  PY3.6
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):  3.1
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
TPU ops are compiled by default on any platform other than ``chromiumos`` despite of if_libtpu or if_with_tpu_support configurations

**Provide the exact sequence of commands / steps that you executed before running into the problem**
follow standard build from source procedure
https://www.tensorflow.org/install/source 

**Any other info / logs**

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD#L575

‘’‘
cc_library(
    name = "ops",
    visibility = ["//visibility:public"],
    deps = [
        ":user_ops_op_lib",
        "//tensorflow/c/kernels:bitcast_op_lib",
        "//tensorflow/c/kernels:histogram_summary_op_lib",
        "//tensorflow/c/kernels:merge_summary_op_lib",
        "//tensorflow/c/kernels:summary_op_lib",
        "//tensorflow/core/ops:ops",
    ] + if_chromiumos(
        [],
        # Non-tpu platforms don't need tpu dependency.
        [
            "//tensorflow/core/tpu/ops",
        ],
    ) + if_tensorrt([
        "//tensorflow/compiler/tf2tensorrt:trt_engine_resource_ops_op_lib",
        "//tensorflow/compiler/tf2tensorrt:trt_op_libs",
    ]) + if_libtpu(
        if_false = ["//tensorflow/compiler/mlir/tensorflow:mlir_passthrough_op"],
        if_true = [],
    ),
)
’‘’

**Comment by frankchn** [comment]
@kevint324 Thanks for the report! This is working as intended, because TPU ops are also used in the current Cloud TPU product and we want to support this out of the box in TensorFlow. `//tensorflow/core/tpu/ops` also only contains the op definitions and not any kernel implementations, so should be very lightweight.

The `with_tpu_support` and `if_libtpu` are there to disable the building of the actual kernels by default, since they won't be used by the vast majority of TF users.

**Comment by kevint324** [comment]
Got it. Thanks for the reply.
