### ISSUE TITLE
delete the eager execution check for shared_embedding_columns_v2

### ISSUE THREAD

**Issue by AIspeakeryhl** [tensorflow/tensorflow#48638]
at the line 901 of tensorflow/tensorflow/python/feature_column/feature_column_v2.py:
we have a eager execution  check:
if context.executing_eagerly():
    raise RuntimeError('shared_embedding_columns are not supported when eager '
                       'execution is enabled.')
but it shouldn't check because it's a tf2.X code and it use eager execution at default

**Comment by AdityaKane2001** [comment]
@Alspeakeryhl
Yes, it is true that TF has eager execution on by default. But many models in production or production testing environments do not use eager mode, they use graph mode. Thus, to tell the user that the aforementioned function cannot be used under such conditions, we raise the `RuntimeError`.

**Comment by ymodak** [comment]
Adding to AdityaKane's answer-
Even though eager execution is enabled by default there are certain cases (executing inside of `tf.function`) when it is disabled and in such cases the eager execution check can come in handy.
See https://www.tensorflow.org/api_docs/python/tf/executing_eagerly to know more.
