### ISSUE TITLE
Is there any offical way of freezing graph to pb in Tensorflow2

### ISSUE THREAD

**Issue by Zhuxinpei** [tensorflow/tensorflow#48639]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

To some reason I have to get a pb model. In TF1 I used following code to build a pd file.
```
from tensorflow.python.framework import graph_util
constant_graph = graph_util.convert_variables_to_constants(sess,sess.graph_def,FLAG.output_op)
with tf.gfile.GFile(FLAG.save_path + '\\PBModel.pb',mode='wb') as f:
    f.write(constant_graph.SerializeToString())
```
I tried every thing of savedModel to pb or .h5 to pb but failed. So is there any offical way of freezing graph to pb in Tensorflow2 ?

**Comment by tilakrayal** [comment]
@Zhuxinpei ,

Can you please refer to this [link](https://stackoverflow.com/questions/58119155/freezing-graph-to-pb-in-tensorflow2) for similiar issue.

Thanks!

**Comment by Zhuxinpei** [comment]
I have tried all ways from that link but the pb from .h5 was not simillar to the pb in TF1 especially when I built custom model.

**Comment by tilakrayal** [comment]
@Zhuxinpei ,

In order to reproduce the issue reported here, could you please provide Tensorflow version,the complete code and the dataset you are using. Thanks!

**Comment by Zhuxinpei** [comment]
Tensorflow-2.3.0. Sorry for no code and data cause the issue was asked for the code of freezing graph to pb.

**Comment by jvishnuvardhan** [comment]
@Zhuxinpei Can you please check whether [this resource](https://www.tensorflow.org/guide/migrate#a_graphpb_or_graphpbtxt) is helpful to you or not. 

Some of the `TF1` functionality you can access through `tf.compat.v1.graph_util.convert_variables_to_constants`. Thanks!

**Comment by Zhuxinpei** [comment]
Thanks for your reply but the resource may not helpful. What I need is converting a saved_model from TF2 to a raw .pb file in TF1. The resource documents as 

> "TensorFlow 2.x saved_models work in TensorFlow 1.x if all the ops are supported"

 Thus I thought there should be a way of using `tf.compat.v1.graph_util.convert_variables_to_constants` to convert a saved_model. Actually I tried many ideas in stackoverflow but no one works. Such as the [link](https://stackoverflow.com/questions/58119155/freezing-graph-to-pb-in-tensorflow2) and code:
```
import logging
import tensorflow as tf
from tensorflow.compat.v1 import graph_util
from tensorflow.python.keras import backend as K
from tensorflow import keras

tf.compat.v1.disable_eager_execution()

saved_model_path = 'XXX'
model = keras.models.load_model(saved_model_path)
with K.get_session() as sess:
    output_names = [out.op.name for out in model.outputs]
    input_graph_def = sess.graph.as_graph_def()
    for node in input_graph_def.node:
        node.device = ""
    graph = graph_util.remove_training_nodes(input_graph_def)
    graph_frozen = graph_util.convert_variables_to_constants(sess, graph, output_names)
    tf.io.write_graph(graph_frozen, '/path/to/pb/model.pb', as_text=False)
logging.info("save pb successfully！")
```
If you have any idea please help.

**Comment by allenlavoie** [comment]
Freezing is not an operation the TF team has plans to support going forward.

It is used as an implementation detail of a few transformations, or was at some point (e.g. TF-Lite, XLA compilation to some extent). But not as a standalone operation.

If there's something you could do in TF1 that still requires a frozen graph and it's maintained by the TF team, please do file a bug about that. Endpoints should generally consume SavedModels, and we'd really rather not have a separate format for frozen models floating around that are supported spottily.
