### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow for MAC m1 

### ISSUE THREAD

**Issue by pitocms** [tensorflow/tensorflow#48636]
**System information**
-MacBook Air (M1, 2020)
-version 11.2
-python version 3.8.2 
-pip version 21.0.1 

**Describe the problem**

I am trying to install tensorflow by below command 
`pip install tensorflow 
`
and getting below 

error 

**ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow**

This is my all attempts log:

```
(venv) alimonkarim@Alimons-MacBook-Air ml % python -V
Python 3.8.2
(venv) alimonkarim@Alimons-MacBook-Air ml % pip -V
pip 21.0.1 from /Users/webnation/ml/venv/lib/python3.8/site-packages/pip (python 3.8)
(venv) alimonkarim@Alimons-MacBook-Air ml % pip install --upgrade pip

Requirement already satisfied: pip in ./venv/lib/python3.8/site-packages (21.0.1)
(venv) alimonkarim@Alimons-MacBook-Air ml % pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
```

**Comment by tilakrayal** [comment]
@pitocms ,

Please refer to similar issues #44615, #47365, #47205, #46817,  #46506 and [link](https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow). It helps.

Thanks!

**Comment by malikasinger1** [comment]
having same issue on macbook pro M1 

```
malik@Apples-MBP arabianconsult % pip3 install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos
malik@Apples-MBP arabianconsult %                           
```

**Comment by tobiolusa** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

Facing same issue in my Macbook Pro M1
