### ISSUE TITLE
tf.data.experimental.save

### ISSUE THREAD

**Issue by arunraja-hub** [tensorflow/tensorflow#48649]
My GIT version and tf.version: unknown, 2.2.0

**Describe the current behavior**
I am trying to use [tf.data.experimental.save ](https://www.tensorflow.org/api_docs/python/tf/data/experimental/save)to save a tf Dataset
**Describe the expected behavior**
Expected behaviour is that the dataset should be saved
**Standalone code to reproduce the issue**
The code is very simple:
```
import tensorflow as tf
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
```
The error I got was:
`AttributeError: module 'tensorflow._api.v2.data.experimental' has no attribute '                                                                                                             save'
`

**Comment by AdityaKane2001** [comment]
@arunraja-hub 
Can you please share a reproducible sample code? Thanks

**Comment by arunraja-hub** [comment]
@AdityaKane2001 I have updated the code above

**Comment by AdityaKane2001** [comment]
@arunraja-hub 
Thanks

**Comment by UsharaniPagadala** [comment]
@arunraja-hub 


I ran the code shared on tf 2.4, tf nightly and did not get any error, please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/7e6cfa94cb1b955a8c2f1e8fc9808b73/-48649.ipynb) here

**Comment by UsharaniPagadala** [comment]
@arunraja-hub 

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.
