### ISSUE TITLE
Tensorflow after 1.15 - No need to install tensorflow-gpu package

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#48640]
This is basically an info question that was asked by [mon](https://stackoverflow.com/users/4281353/mon) in SO and we answered as far as we know, [here](https://stackoverflow.com/a/67088947/9215780).

In the official `tf` installation guide in documentation, it says, 

> For releases 1.15 and older, CPU and GPU packages are separate:

pip install tensorflow==1.15      # CPU
pip install tensorflow-gpu==1.15  # GPU

And for later version, e.g `tf : > = 2.0`, we simply need to do 

```
pip install tensorflow     # CPU or GPU 
```

But still, we have 

```
!pip install tensorflow-gpu 
....
Installing collected packages: tensorflow-gpu
Successfully installed tensorflow-gpu-2.4.1

# -------------------------------------------------------------

!pip install tensorflow-cpu
....
Installing collected packages: tensorflow-cpu
Successfully installed tensorflow-cpu-2.4.1
```

why `tf-gpu/cpu` for `2.4.1` still exits? what is the main reason here? is there any difference for `tf > = 2` installing them separately or the standalone way?

**Comment by amahendrakar** [comment]
@innat,
1. As you've already mentioned, starting with TF v2.0, the TensorFlow packages by default support both CPU and GPU.


2. > why `tf-gpu/cpu` for `2.4.1` still exits? what is the main reason here?

If you explicitly require support for either CPU or GPU **only**, you can opt for the tf-cpu/gpu package.



3. > is there any difference for `tf > = 2` installing them separately or the standalone way?

Apart from the above mentioned point and the package size itself there isn't much difference.

Hope this answers your query. Thanks!

**Comment by mihaimaruseac** [comment]
`tensorflow` and `tensorflow-gpu` after 2.1 are exactly the same package, just with a different name.
