### ISSUE TITLE
AveragePooling3D does not support float64 and produces confusing error message

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#48644]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Description**
AveragePooling3D and MaxPool3D layer don't seem to support float64, i.e. they don't work with `tf.keras.backend.set_floatx('float64')`. The MaxPool3D layer shows a nice helpful error message, when it is used with float64, but AveragePooling3D only shows a strange error message that is not helpful: tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'AvgPool3D'

It would be great, if AveragePooling3D layer would also produce a similar helpful error message. 
Even better would be if both these layers would also support float64. It is quite strange that this is not supported since all other pool layers seem to support float64.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
import numpy as np
tf.keras.backend.set_floatx('float64')
model = keras.Sequential([
keras.layers.AveragePooling3D(pool_size=(3, 1, 3), input_shape=(3, 3, 3, 4))])
x = tf.constant([[[[[2, 2, 2, 1], [1, 1, 2, 2], [1, 1, 1, 1]], [[1, 1, 1, 2], [2, 1, 2, 2], [1, 2, 2, 2]], [[1, 1, 1, 2], [1, 1, 1, 1], [2, 1, 1, 1]]], [[[1, 2, 2, 1], [2, 2, 1, 1], [1, 2, 1, 1]], [[2, 2, 2, 1], [1, 1, 1, 1], [2, 2, 1, 2]], [[1, 2, 2, 1], [2, 2, 2, 1], [1, 1, 2, 1]]], [[[1, 1, 1, 1], [2, 2, 1, 2], [1, 1, 1, 2]], [[1, 1, 2, 1], [1, 1, 1, 1], [2, 2, 1, 2]], [[2, 2, 2, 1], [2, 1, 1, 2], [1, 1, 2, 2]]]]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

The same example with a MaxPool3D layer shows a much more helpful error message (TypeError: Value passed to parameter 'input' has DataType float64 not in list of allowed values: float16, bfloat16, float32) as illustrated in the following code
```
import tensorflow as tf
from tensorflow import keras
import numpy as np
tf.keras.backend.set_floatx('float64')
model = keras.Sequential([
keras.layers.MaxPool3D(pool_size=(1, 2, 2), input_shape=(4, 4, 3, 3))])
x = tf.constant([[[[[1, 2, 2], [1, 2, 2], [2, 2, 1]], [[1, 2, 1], [1, 2, 2], [1, 1, 2]], [[2, 2, 1], [2, 1, 1], [1, 2, 1]], [[2, 1, 2], [1, 1, 2], [1, 1, 1]]], [[[2, 1, 2], [2, 2, 1], [1, 2, 2]], [[1, 2, 2], [2, 1, 1], [2, 2, 2]], [[2, 1, 1], [2, 1, 2], [2, 1, 2]], [[2, 1, 2], [2, 2, 1], [1, 1, 2]]], [[[1, 1, 1], [2, 1, 2], [1, 2, 2]], [[2, 2, 1], [1, 2, 1], [1, 1, 1]], [[1, 1, 2], [2, 2, 2], [2, 2, 1]], [[1, 2, 1], [1, 1, 2], [1, 1, 2]]], [[[2, 1, 1], [1, 1, 1], [2, 1, 2]], [[1, 2, 1], [2, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 1, 2], [2, 2, 2]], [[2, 1, 1], [2, 1, 1], [1, 2, 1]]]]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

**Comment by szutenberg** [comment]
Hi @rschumi0 ,

I don't think we have an issue here. Both messages are informative. On TF 2.4.0 I'm getting:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'AvgPool3D' used by {{node sequential/average_pooling3d/AvgPool3D}} with these attrs: [strides=[1, 3, 1, 3, 1], data_format="NDHWC", ksize=[1, 3, 1, 3, 1], padding="VALID", T=DT_DOUBLE]
Registered devices: [CPU]
Registered kernels:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

	 [[sequential/average_pooling3d/AvgPool3D]] [Op:__inference_predict_function_70]
```

Let's have a look at the code:
- [AvgPool3D](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/nn_ops.cc#L716-L724) is registered also for `T=double` (which is float64)
- [MaxPool3D](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/nn_ops.cc#L739-L747) is not registered for `T=double`

These are op registrations. Kernels for CPU are registered in [core/kernels/pooling_ops_3d.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/pooling_ops_3d.cc#L712-L735). We see that there is no kernel registration for double, that's why TF complains. You can use XLA_CPU_JIT.

**Comment by UsharaniPagadala** [comment]
@rschumi0 
 
Please take a look at the above mentioned  comment and let us know if you are still facing the same issue. Otherwise move this to closed status Thanks!

**Comment by rschumi0** [comment]
@szutenberg Thank you for your answer.

I am not that familiar with the different kernels which made the error message confusing to me. How can I change to XLA_CPU_JIT?

So the reason for the different error message is that there is a kernel that supports double for AvgPool3D, but none for MaxPool3D. Is there a particular reason why there is none for MaxPool3D?

**Comment by UsharaniPagadala** [comment]
@rschumi0 
The following are the supported [devices](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/g3doc/cpu_supported_ops.md) for XLA_CPU_JIT. Could you please check and let us know if it helps.Thanks
