### ISSUE TITLE
How to Modify and Debug the TFLiteConverter

### ISSUE THREAD

**Issue by RobertChenKFC** [tensorflow/tensorflow#48657]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installation (pip package or built from source): built from source
- TensorFlow library (version, if pip package or github SHA, if built from source): 0d1805aede03d25aa9d49adcef6903535fa5ad14

### 2. Code

Modify `tensorflow/compiler/mlir/lite/tests/end2end/add.pbtxt` to [this](https://drive.google.com/file/d/1UxTnG9kQ_SJSDQ7_1mZAttUTlGAY5Gxo/view?usp=sharing) (basically just change the data type from `DT_INT32` to `DT_FLOAT`), then try to convert `add.pbtxt` to a fully quantized `.tflite` model using the following command:
```
./tf_tfl_translate \
  --tf-input-arrays=input0,input1 \
  --tf-input-shapes=4:4 \
  --tf-input-data-types=DT_FLOAT,DT_FLOAT \
  --tf-output-arrays=Add \
  --tf-inference-type=DT_QINT8 \
  --tf-input-min-values='-1,-1' \
  --tf-input-max-values='1,1' \
  add.pbtxt \
  -o output.tflite
```

### 3. Failure after conversion
The [output model](https://drive.google.com/file/d/1P-6V_wKkdcH4nAdM6Gl2Tft9FMNUE0Id/view?usp=sharing) `output.tflite` is not fully quantized even though `--tf-inference-type=DT_QINT8` is specified. Here is `output.tflite` when inspected with Netron:

![add-netron](https://user-images.githubusercontent.com/19867281/115502332-5a1cb100-a2a7-11eb-89a2-2db9e3ee380d.png)

FYI, [here](https://drive.google.com/file/d/1Ojz3v2mZ4O_nA2iHVpQ0us_0JAcgErL0/view?usp=sharing) is a log of the MLIR after each pass.

### 4. Any other info / logs
To be honest, I'm not sure if I am using `tf_tfl_translate` correctly, so I would like to know if this is an issue with `tf_tfl_translate` or if there is another correct way to perform full-integer quantization on a TensorFlow model using `tf_tfl_translate`.

Currently, I'm trying to add an MLIR pass to the `TFLiteConverter` (more specifically, in the function `AddTFToTFLConversionPasses` in `tensorflow/compiler/mlir/lite/tf_tfl_passes.cc`), and I want to use `TFLiteConverter` to convert and perform full-integer quantization on a TensorFlow model while running the MLIR pass I added in the process. I want to avoid rebuilding the pip package every time I modify my pass, so I decided to use the internal tool `tf_tfl_translate`, which lead to this problem.

If there are any tips and tricks on how to modify the `TFLiteConverter` to add an MLIR pass and be able to debug it without having to rebuild the pip package every time, please let me know. Thanks for your time!

**Comment by abattery** [comment]
We don't recommend using `tf_tfl_translate` and that is not an official TensorFlow API.  Please use the TFLiteConverter API instead. Please refer to https://www.tensorflow.org/lite/performance/post_training_quantization for the quantization.

**Comment by abattery** [comment]
For the pbtxt conversion, please use this path for your case. https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter#from_frozen_graph

**Comment by RobertChenKFC** [comment]
Thanks for the help. I do know how to convert to `.tflite` models using the `TFLiteConverter`, but my problem was how I could add an MLIR pass to the converter such that I can modify and test the pass without rebuilding TensorFlow entirely just to use the python API. My attempt was to use `tf_tfl_translate`, but unfortunately it failed at performing full-integer quantization. I was wondering if it was a problem with `tf_tfl_translate`, or if I used `tf_tfl_translate` incorrectly, or if I can achieve my goal without using `tf_tfl_translate`. Thanks.

**Comment by abattery** [comment]
Quantizer is a part of TF Python API. It looks hard to achieve that.

**Comment by RobertChenKFC** [comment]
Okay, so does this mean that if I want to add an MLIR pass to the `TFLiteConverter` and test it, I must rebuild the TensorFlow pip package entirely?

**Comment by abattery** [comment]
The Bazel build environment supports only required build targets and also builds the necessary stuffs for the TFLite converter.

**Comment by RobertChenKFC** [comment]
Just to make sure, do I run `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package` and let bazel figure out what should be rebuilt every time I modify my MLIR pass, or is there another target that just builds the `TFLiteConverter`?

**Comment by abattery** [comment]
It is possible to create a Python program under the bazel development env., by depending on the //tensorflow/lite/python:lite build target.

**Comment by UsharaniPagadala** [comment]
@RobertChenKFC 

please confirm if the issue still persist

**Comment by RobertChenKFC** [comment]
Sorry for the late reply, I'm still figuring out how to make this work with my existing code (I'm not really familiar with bazel), but I think this method should work. I'll close this issue first, and reopen it if other issues occur. Thanks for the help.
