### ISSUE TITLE
GraphDef duplication in event log

### ISSUE THREAD

**Issue by eric-czech** [tensorflow/tensorflow#4865]
This is a little difficult to explain, and I'm guessing someone has to have run into it before, but it would be nice to at least get an explanation for what's going on here.

The issue I'm finding is that when you specify a `model_dir` argument for any tflearn model, the first time you fit that model, the tensorboard warning like the following will always appear:

`WARNING:tensorflow:Found more than one graph event per run. Overwriting the graph with the newest event.`

If you clear the contents of that directory and rerun the same model, the warning no longer appears.

For example, here is a piece of code to reproduce:

```
import tensorflow as tf
import random

from tensorflow.contrib.learn.python import learn
from tensorflow.contrib.learn.python.learn import datasets
from tensorflow.contrib.learn.python.learn.estimators._sklearn import accuracy_score
from tensorflow.contrib.learn.python.learn.estimators._sklearn import train_test_split
random.seed(42)

iris = datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    random_state=42)

def custom_optimizer(learning_rate):
    return tf.train.MomentumOptimizer(learning_rate, 0.9)

classifier = learn.TensorFlowDNNClassifier(
    hidden_units=[10, 20, 10],
    n_classes=3,
    steps=400,
    learning_rate=0.01,
    optimizer=custom_optimizer,
    model_dir='/tmp/tf/bug_test_1')
classifier.fit(x_train, y_train)
```

If you run this in a jupyter notebook, wait until it is done, cd into `/tmp/tf/bug_test_1`, and run `tensorboard --logdir=.`, the warning will appear.  If you clear the contents and run again, it will no longer appear.  If you, in the same notebook within the same kernel, change the directory to something else (e.g. `/tmp/tf/bug_test_2`) and run again, the warning will again appear.  And the warning will again go away if you clear the contents and run again with the same directory.

I also tried pre-creating the directory but that appears to make no difference.

I wouldn't imagine this indicates a major problem but I try to take those warnings seriously since they have indicated more problematic issues in the past with running multiple models in the same kernel, so it would be great to know what this means.
### Environment info

Operating System: OS X Yosemite (10.10.5)
Tensorflow Version: 0.10.0

**Comment by jart** [comment]
Thank you for reporting this issue. You're correct that warnings like these should be taken seriously. To help me prioritize things, I just want to confirm whether or not this is causing TensorBoard to display incorrect data.

**Comment by eric-czech** [comment]
I don't believe the data shown is incorrect because of this, I think it's just a false warning.  Although I can't say that with 100% confidence since I'm really sure if there may be subtle differences when events already exist from previous runs (but there are no obvious differences as far as I can tell).

**Comment by jart** [comment]
Thanks for clarifying. I'm going to mark this 'contributions welcome' because we've got a bit of a backlog at the moment.

**Comment by haosdent** [comment]
I test with RNN, the case looks different. I think we should compare the content of the graph_def and only warn if their are different. Make sense? @jart

**Comment by jart** [comment]
Conditionally warning based equality sounds like a band-aid rather than a fix. Ideally I would like to address the root cause.

**Comment by outlace** [comment]
@jart 
I get these warnings as well, and additionally, on the second run, if I go to TensorBoard's graph section, my graph get's duplicated. Like it shows 2 separate identical copies of the graph. If I delete all the logs and just run once then my graph is displayed correctly.

**Comment by nbro** [comment]
@itsmeolivia Why did you close this issue?

**Comment by nischnei** [comment]
It seems like this issue still persists at least I have the same warning with version 1.11
