### ISSUE TITLE
bug while running bazel build

### ISSUE THREAD

**Issue by Gaasmann** [tensorflow/tensorflow#48652]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Sid
- TensorFlow installed from (source or binary): source r2.5
- TensorFlow version: r2.5
- Python version: 3.9
- Installed using virtualenv? pip? conda?: pip from the system (python3-pip) no venv
- Bazel version (if compiling from source): 3.7.2  (using bazelisk)
- GCC/Compiler version (if compiling from source): gcc (Debian 10.2.1-6) 10.2.1 20210110
- CUDA/cuDNN version: 11 / 8.1.1
- GPU model and memory: NVIDIA GeForce GTX 1070

**Describe the problem**
When building tensorflow, bazel fails with the following message:
```
ERROR: /home/nicolas/.cache/bazel/_bazel_nicolas/13cce9ab7cc322a6b7e908ff0026fedd/external/nccl_archive/BUILD.bazel:54:17: in _prune_relocatable_code rule @nccl_archive//:device_pruned:
Traceback (most recent call last):
        File "/home/nicolas/.cache/bazel/_bazel_nicolas/13cce9ab7cc322a6b7e908ff0026fedd/external/local_config_nccl/build_defs.bzl", line 207, column 15, in _prune_relocatable_code_impl
                output.append(outputs)
Error: 'File' value has no field or method 'append'
```
After looking at the file build_defs.bzl and at this [page](https://chromium.googlesource.com/external/github.com/tensorflow/tensorflow/+/e07069218c39cbfc4bbad79fc50c83d64b0546af%5E%21/third_party/nccl/build_defs.bzl.tpl),
I think that famous line 207 has a confusion between output and outputs. I tried swapping one for the other and it seems ok now. Bazel has started compiling at least. :-)

I'm not sure if it is really a Tensorflow issue or where is this build_defs.bzl file hosted so I'm not sure where to ask or do a PR. Sorry if Iḿ the wrong place.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Comment by Gaasmann** [comment]
Adding @chsigg as that [page](https://chromium.googlesource.com/external/github.com/tensorflow/tensorflow/+/e07069218c39cbfc4bbad79fc50c83d64b0546af%5E%21/third_party/nccl/build_defs.bzl.tpl) seems to declare him as the author of that piece of code.

**Comment by Saduf2019** [comment]
@Gaasmann 
Sorry for the delayed response, can you please let us know if you still face the issue.

**Comment by Gaasmann** [comment]
@Saduf2019 This seems to be a bug on the line I mentioned. I don't see new commits so I doubt the problem has resolved. I'll try to recompile nonetheless and let you know.

**Comment by Saduf2019** [comment]
@Gaasmann 
Please update, if we may move this to closed status if resolved.

**Comment by bermeitinger-b** [comment]
I have the same error message while building release 2.5.0.
