### ISSUE TITLE
[0.11]Can't bind GPU with tf.device()

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#4867]
I installed the latest TF v0.11  and found that it can't bind specific GPU with `tf.device("gpu:1")`.  It always applies all GPU resource when I run `tf.Session()`, which is unreasonable.
For example:
```python
import tensorflow as tf
with tf.device("gpu:1"):
  sess = tf.Session()
```
GPU resource:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      7895    C   python                                       10963MiB |
|    1      7895    C   python                                       10922MiB |
|    2      7895    C   python                                       10923MiB |
|    3      7895    C   python                                       10922MiB |
+-----------------------------------------------------------------------------+
```

But when I switch to TF v0.9, everything is fine.
GPU resource:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      5161    C   python                                          65MiB |
|    1      5161    C   python                                          65MiB |
|    2      5161    C   python                                          65MiB |
|    3      5161    C   python                                          65MiB |
+-----------------------------------------------------------------------------+
```

I think it's a bug and caused by the update of `tf.Session()`.
I hope I can fix it ASAP

**Comment by yaroslavvb** [comment]
There was a change a while back to new memory allocator that grabs all GPU memory on start for  performance reasons. There are some flags to limit how much memory it grabs -- http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

**Comment by HW-ZZ** [comment]
@yaroslavvb 
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```
But I think this way can't to set on a per-GPU basis.
If we need train two different models  on two different GPUs at same time,how can we 
allocate GPU memory.

**Comment by yaroslavvb** [comment]
If they run in difference processes use `CUDA_VISIBLE_DEVICES` to limit GPUs visible to each process

**Comment by vrv** [comment]
Or try the allow_growth option instead.

**Comment by asimshankar** [comment]
Seems like the question of how to limit a process to a subset of GPUs has been resolved (use `CUDA_VISIBLE_DEVICES`). I'm going to go ahead and close this issue, feel free to reopen if the concerns were not addressed. Thanks!
