### ISSUE TITLE
Efficient upsampling 3D Volume with linear interpolation options

### ISSUE THREAD

**Issue by XXZhou25** [tensorflow/tensorflow#48672]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow2.0
- Are you willing to contribute it (Yes/No): No. I was trying to vectorize it, but I failed with out of GPU memory error. My GPU is tesla V100, memory 32G. Volume size = [128, 256, 256, 3] / want to upsampling it to [256, 256, 512, 3] by interpolation. 

**Describe the feature and the current behavior/state.**
Upsample image by trilinear / cubic-spline interpolation

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Most of people who are working with 3D data.  

**Any Other info.**
I will appreciate any efficient implementation advices for implementing it in a vectorized way.

**Comment by amahendrakar** [comment]
>No. I was trying to vectorize it, but I failed with out of GPU memory error.

@XXZhou25,
Could you please provide a minimal code snippet of the use-case you are trying to implement, so that we can look into it. Thanks!
