### ISSUE TITLE
 Input and output tensor of .pb file

### ISSUE THREAD

**Issue by prabhakarlad** [tensorflow/tensorflow#48677]
Hi,

I have been trying to get the input and output tensor dtype for a pb model.
```

def printTensors(pb_file):

graph = tf.Graph()
with tf.io.gfile.GFile(pb_file, "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())
input_tensor = graph_def.node[0]
output_tensor = graph_def.node[-1]
print(input_tensor.name)
print(output_tensor.name)
```

when I use the above code and compare against the output of summarize_graph utility there seems to be a mismatch. So my query is graph_def.node[0] is always input and graph_def.node[-1] is output ?

Cheers,
Prabhakar

**Comment by tilakrayal** [comment]
@prabhakarlad ,

In order to reproduce the issue reported here, could you please provide the Tensorflow version,complete code and the dataset you are using. Thanks!
