### ISSUE TITLE
TFLite bug: RuntimeError: tensorflow/lite/kernels/conv.cc:329 input->dims->size != 4 (3 != 4)Node number 0 (CONV_2D) failed to prepare.

### ISSUE THREAD

**Issue by YannPourcenoux** [tensorflow/tensorflow#48675]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: Python 3.6.9 :: Anaconda, Inc.

**Describe the current behavior**
I am trying to convert some model to TFLite but the error `RuntimeError: tensorflow/lite/kernels/conv.cc:329 input->dims->size != 4 (3 != 4)Node number 0 (CONV_2D) failed to prepare.` is raised when I try to convert MobileNetV3Large.

**Describe the expected behavior**
I expect to be able to convert any basic model from `TensorFlow.Keras` to `TFLite`.

**Standalone code to reproduce the issue**
```
"""
File to show the runtime error when trying to convert MobileNetV3 to TFLite.
"""

import tensorflow as tf


mobile_net = tf.keras.applications.MobileNetV3Large(
    input_tensor=tf.keras.Input(shape=(224, 224, 3), batch_size=1, name="input", dtype=tf.float32)
)
model = tf.keras.Model(inputs=mobile_net.inputs, outputs=mobile_net(mobile_net.inputs))
model.compile()
model.summary(line_length=200)


def representative_dataset_generator():
    """Dataset generator that generates random tensor with the same shape as the input"""
    for _ in range(100):
        yield tf.random.uniform(shape=(1, 224, 224, 3), dtype=tf.float32)


converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Set the representative dataset in order to quantize the activations
converter.representative_dataset = representative_dataset_generator

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]

# Set the input and output tensors to uint8
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

# Experimental environment
converter.experimental_new_converter = True
converter.experimental_new_quantizer = True

tflite_model = converter.convert()

```
**Other infos**
The problem since to be coming from `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`. If I comment the `converter.inference_*_type = tf.uint8`, `converter.target_spec.supported_types = [tf.int8]` and also the `converter.optimizations`line, the error is still raised but go away if I change to `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]`.
It comes back if I uncomment the line related to the converter.optimizations.
Anyway, I need to do an integer only quantization like in the [TF tutorial here](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only). I am quite lost. Would you have any idea?

**Comment by liufengdb** [comment]
Hi Yann, can you help me and upload the converted model when only `[tf.lite.OpsSet.TFLITE_BUILTINS]` is used?

**Comment by YannPourcenoux** [comment]
Of course, [here](https://github.com/tensorflow/tensorflow/files/6353281/model.zip) it is!

**Comment by abattery** [comment]
Could you also share your inference code? I think the input dimension for the image tensor should have four dimensions.

**Comment by YannPourcenoux** [comment]
Hi, there is no inference code. I am just running the conversion code I put in the original issue message above. The input_shape of the model is `(1, 224, 224, 3)` (you can verify with [netron](https://netron.app/)) and the representative dataset is yielding tensors of shape `(1, 224, 224, 3)` ie the exact same.

**Comment by nfrumkin** [comment]
I have an identical error with a model I am currently running

**Comment by nfrumkin** [comment]
@mohantym The issue still persists. It seems you cannot use dtype=tf.int8 (only tf.float32, tfbloat16, etc. supported). So I did the following:
``` 
data = tf.random.uniform(shape=(1, 244, 244, 3), dtype=tf.float32)
data = tf.cast(data, dtype=tf.int8)
 yield [data]

**Comment by mohantym** [comment]
@nfrumkin !
Please attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/8c3c14e672b7e0cfe915670458453f8e/git_48675.ipynb#scrollTo=pP23RFf8TJA4) for reference  and open a new issue if you are looking assistance on similar issue.
Thank you!

**Comment by MECHAAMER** [comment]
the issue solved here [link](https://github.com/tensorflow/tensorflow/issues/61760)

for me I use:

np.transpose(image, (2, 0, 1))  # (H, W, C) -> (C, H, W)
