### ISSUE TITLE
ValueError: Shapes (8, 100) and (8, 1) are incompatible

### ISSUE THREAD

**Issue by shbkukuk** [tensorflow/tensorflow#48680]
![image](https://user-images.githubusercontent.com/53318795/115602332-7dffe700-a2e7-11eb-9f46-16b76d8bfdd5.png)
My model params is above. when i tried to get score metrics (Recall and Precision)  this error show up 
![image](https://user-images.githubusercontent.com/53318795/115603793-4134ef80-a2e9-11eb-92b4-ecd3323b8bd6.png)
model.fit code is :
![image](https://user-images.githubusercontent.com/53318795/115603861-56118300-a2e9-11eb-90d2-94e5c2b20b7b.png)

How can i solved this problem ?

**Comment by saikumarchalla** [comment]
@shbkukuk Could you please provide the code snippet/colab link so that it helps to figure out the error a bit faster.

Also, Please check the input size of  first layer whether you have defined properly or not and helps to resolve the error. Thanks!

**Comment by shbkukuk** [comment]
`IMG_SIZE = 100

new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
plt.imshow(new_array, cmap='gray')
#plt.show()
# üstte datalarımızı array ve gray uygun hale getirdik.şimdi data eğitimi yapcağız.

training_data = []
def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATA,category)
        class_num = CATEGORIES.index(category) #sınıflandırma yapıyoruz. 0=yangın,1=orman(yangınsız)
        for img in os.listdir(path):  # her img array haline çevirme
            try:
                img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)  # grileştirme de yapıldı.
                new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass

create_training_data()

#print(len(training_data))

random.shuffle(training_data)
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)


X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=426)


for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for multi_layer in multi_layers:
            NAME = "{}-Multilayer-{}-LayerSize-{}-dense-{}test-metrics".format(multi_layer, layer_size, dense_layer, datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
            print(NAME)

            model = Sequential()
            #ysa ilk katmanı(giriş)
            model.add(Dense(layer_size,input_shape=(X_train.shape[1:]),activation='relu')) #256 tane yapay sinir hücresi
            #ysa ara katman
        for l in dense_layers:
            model.add(Dense(layer_size,activation='relu'))
            #ysa gizli katman
        for l in range(multi_layer-1):
            model.add(Dense(layer_size,activation='relu'))
            #ysa çıkış katmanı
            model.add(Dense(1,activation='sigmoid'))
            tensorboard = TensorBoard(log_dir="4820logs/21-04-21/{}".format(NAME))

            model.summary()

            
            model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
                          optimizer='adam',
                          metrics=['accuracy',
                                   tf.keras.metrics.Recall(),
                                   tf.keras.metrics.Precision()
                                ])

            model.fit(X_train,y_train,batch_size=8,
                      epochs=50,verbose=2,
                      validation_data=(X_test,y_test),
                      callbacks=[tensorboard])
            #print("{},{},{}".format(str(pre),str(auc),str(rcll)))
            sınıf = X_test[2].reshape(IMG_SIZE, IMG_SIZE)
            plt.imshow(sınıf, cmap='gray')
            plt.show()
`
@saikumarchalla  I can share with you part of code. i think its enough for help. Thank you for replies.

**Comment by Saduf2019** [comment]
@shbkukuk 
I ran the code shared and face a different error please find the [gist here [syntax issues]](https://colab.research.google.com/gist/Saduf2019/070d315489e20c3fe7f5b6260db062a0/untitled597.ipynb)
Please share code or colab gist such that we could see the error reported.

**Comment by shbkukuk** [comment]
@saikumarchalla  thank you for replies.I solved the problem.

**Comment by Saduf2019** [comment]
@shbkukuk 
thank you for your update, glad the issue is resolved.
