### ISSUE TITLE
Issues loading saved model  - TypeError: __init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by GrayWasTaken** [tensorflow/tensorflow#48683]
solved can be closed

**Comment by bhack** [comment]
Can you share a minimal standalone example that we could just `copy and run` to reproduce this (or a Colab)?
Thanks

**Comment by GrayWasTaken** [comment]
> Can you share a minimal standalone example that we could just `copy and run` to reproduce this (or a Colab)?
> Thanks

Yeah sure thing:
[https://colab.research.google.com/drive/1fXn9w8_30kX1ATq6MS4UIWj4yealcCXo?usp=sharing](https://colab.research.google.com/drive/1fXn9w8_30kX1ATq6MS4UIWj4yealcCXo?usp=sharing)
