### ISSUE TITLE
Import graph operation in C or C++

### ISSUE THREAD

**Issue by FGMphys** [tensorflow/tensorflow#48694]
Hi all,
I'm dealing with the following operations. I would like to export a graph from tensorflow python API to TF C API.  Based on TF 2, I'm using graph execution and @tf.function to build the graph with custom operation. Then I'm saving the graph using save_model. Next I would like to load this graph on C or C++ and run the graph to obtain the outputs. Which is the best procedure to do that at the moment?

**Comment by tilakrayal** [comment]
@FGMphys ,

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
