### ISSUE TITLE
Function used in many augmentations (convert_image_dtype) has an issue

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#48701]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab default
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Colab default
- TensorFlow version (use command below): v2.4.1-0-g85c8b2a817f 2.4.1
- Python version: 3
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the current behavior**
There is a function convert_image_dtype that used in many augmentation ops like tf.image.stateless_random_brightness and etc.
That function has a rounding issue here https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/ops/image_ops_impl.py#L2290
Maybe other cases also have this bug (not checked).

When we casting float to int, we should use rounding. In convert_image_dtype rounding implemented as shift by 0.5 which is correct for max value, but is not correct for 0.
See example by link below.

**Describe the expected behavior**
Every time convert_image_dtype changes value scale following casting to int, it should use rounding before casting.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1xZqyuAlZu_xkDZZHNsr7K8g6MyapcNPi?usp=sharing

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.4 and Nightly version as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/5bbf7fed3fe931f4cc07306c91276f88/convert_image_dtype.ipynb).

**Comment by kkimdev** [comment]
Thanks for reporting the issue!

**Comment by pointhex** [comment]
Hi, Can I take this issue?

**Comment by kkimdev** [comment]
Yes, please feel free to do so.

**Comment by pointhex** [comment]
@kkimdev thank you. I did changes and try to check it by unit test, but have one small problem. Could you please tell me or send the link where I can find how to start the exact unit test? e.g ConvertImageTest.testNoConvert.

**Comment by kkimdev** [comment]
@pointhex I think you can put unit test here https://github.com/tensorflow/tensorflow/blob/85c8b2a817f95a3e979ecd1ed95bff1dc1335cff/tensorflow/python/ops/image_ops_test.py and once you open a Github PR, it will kick off pre-submit testings.  Thanks!

**Comment by shkarupa-alex** [comment]
The issue is still not resolved in TF master branch. It seems that PR https://github.com/tensorflow/tensorflow/pull/49868 was not merged.

**Comment by shkarupa-alex** [comment]
Here is a commit where this issue fix was removed https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py#L2290
