### ISSUE TITLE
Issue: Invalid argument:  assertion failed: [len requires non-zero rank, got 0]

### ISSUE THREAD

**Issue by nectario** [tensorflow/tensorflow#48712]
I am experiencing the below issue on random occurrences.

I checked my data and it looks good. Please advise, as this is a production issue.

Thank you.

Nektarios

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Custom**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows and Linux**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.1 and 2.4.1** 
- Python version: **3.8**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **11.0/8.05**
- GPU model and memory: **NVIDIA Titan Volta**
- 
```
Traceback (most recent call last):
  File "C:\Development\Python\Python386\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2825, in variable_creator_scope
    yield
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Development\Python\Python386\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [len requires non-zero rank, got 0]
	 [[{{node cond/else/_1157/cond/Assert/Assert}}]]
	 [[cond_1/pivot_f/_1168/_61]]
  (1) Invalid argument:  assertion failed: [len requires non-zero rank, got 0]
	 [[{{node cond/else/_1157/cond/Assert/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_110455]
Function call stack:
train_function -> train_function
 

```

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@nectario ,

In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!
