### ISSUE TITLE
IOS version of TensorFlowLiteC expose symbol(s) not found error

### ISSUE THREAD

**Issue by Mrlyk423** [tensorflow/tensorflow#48718]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

When attempting to use TensorFlow Lite on iOS  as the documentation, the linker raises an error that it found:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NSProcessInfo", referenced from:
      objc-class-ref in TensorFlowLiteC
  "_CFBundleGetVersionNumber", referenced from:
      l5794 in TensorFlowLiteC
  "___CFConstantStringClassReference", referenced from:
      CFString in TensorFlowLiteC
  "_objc_release", referenced from:
      l4515 in TensorFlowLiteC
  "_objc_msgSend", referenced from:
      l4506 in TensorFlowLiteC
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I build my app with cmake with cmakelist.txt and include "tensorflow/lite/c/c_api.h" in model.h as:
```
cmake_minimum_required(VERSION 3.5)
project(myapp)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -fPIC")
include_directories(${CMAKE_SOURCE_DIR}/tflib/include)
link_directories(${CMAKE_SOURCE_DIR}/tflib/lib)
add_library(mylib_ios SHAREDsrc/model.cc src/model.h)
find_library(TFLiteC NAMES TensorFlowLiteC HINTS ${CMAKE_SOURCE_DIR}/tflib/lib)
target_link_libraries(mylib_ios ${TFLiteC})
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@Mrlyk423 

Could you please fill the issue template
In order to expedite the trouble-shooting process, could you please provide the following details

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory

and the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by Mrlyk423** [comment]
@UsharaniPagadala  Thanks! Below is my system env.

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7 (19H2)
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): source
TensorFlow version: both r2.5 and commit 1d4451e42c6ce44bd9ebb89d117636e4960df7c3 of the master branch have the problem
Python version: 3.7.6
Installed using virtualenv? pip? conda?: conda
Bazel version (if compiling from source): 3.7.2
GCC/Compiler version (if compiling from source):
      Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
      Apple clang version 12.0.0 (clang-1200.0.32.29)
      Target: x86_64-apple-darwin19.6.0
      Thread model: posi
CUDA/cuDNN version: N/A
GPU model and memory： Intel UHD Graphics 630 1536 MB (No compile with Cuda support)

**Comment by abattery** [comment]
FYI, @yyoon @thaink

**Comment by yyoon** [comment]
@UsharaniPagadala Can you share the exact command used for building the iOS?

**Comment by Mrlyk423** [comment]
> @UsharaniPagadala Can you share the exact command used for building the iOS?

@yyoon The command for build tflite is 
`bazel build --config=ios_fat -c opt \  //tensorflow/lite/ios:TensorFlowLiteC_framework` 
And the command for build my own lib is: 
```
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake -DPLATFORM=SIMULATOR64
cmake --build . --config Release
```

**Comment by yyoon** [comment]
Can you try building it for `-DPLATFORM=OS64` in the same way and see if it works?
The `TensorFlowLiteC.framework` is a multi-arch framework, but it does not contain the recent arm64 simulator platform.

**Comment by Mrlyk423** [comment]
@yyoon I have also tried to build it for `-DPLATFORM=OS64` but the problem still exists. 

Meanwhile, I also tried the command `bazel build --config=ios_x86_64 -c opt //tensorflow/lite/c:tensorflowlite_c` to directly build it similar to the darwin/Linux/Android, and got a libtensorflowlite_c.dylib file. My app can build with this file in the arm64 simulator platform. But it fails in the TensorFlowLiteC.framework.

**Comment by Mrlyk423** [comment]
@yyoon I finally add Foundation.framework and CoreFoundation.framework when compiling my own app, and it seems work. The usage way is different from the dynamic lib libtensorflowlite_c.dylib.

**Comment by yyoon** [comment]
I see. Usually those frameworks are included by default when you create an Xcode project, but maybe they need to be manually added when using CMake. Good to know.

Is there anything else we can help you with? Otherwise, could you close the issue?
