### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by Zhang-Mengfan** [tensorflow/tensorflow#48711]
### System information

-   **OS Platform and Distribution (macOS 10.15.7)**:
-   **TensorFlow installed from (pip3 install tensorflow)**:
-   **TensorFlow version (2.4.1)**:
-   **Python version(3.8)**:

### Describe the problem
I tried install and re-install tensorflow many times. Including manually remove all the package folders. But I still could not import tensorflow in my terminal.

### Source code / logs
import tensorflow as tf
Traceback (most recent call last):
  File "/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _PyThread_tss_alloc
  Referenced from: /Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _PyThread_tss_alloc
  Referenced from: /Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /Users/zmengfan/Library/Python/3.8/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by moflo** [comment]
> Symbol not found: _PyThread_tss_alloc

That message looks suspicious, like there's problem with pip pulling wrong versions. I have been running TF 2.4.1 on macOS using the [conda](https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/) virtual environment. Is that a possibility for you to try instead?

**Comment by Zhang-Mengfan** [comment]
I installed [miniconda](https://docs.conda.io/en/latest/miniconda.html), and it works.

**Comment by saikumarchalla** [comment]
@Zhang-Mengfan  Glad to hear that issue is resolved for you. Thanks!
