### ISSUE TITLE
`Adadelta` optimizer throws error on GPU in apply_gradients

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#48713]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 
- GPU model and memory:

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
import random


def test_optimizer(optimizer):
  class Layer1(tf.keras.layers.Layer):

      def __init__(self, shape):
          super(Layer1, self).__init__()
          self.weight1 = self.add_weight(shape=shape)
          
      def call(self, inputs):
          return tf.gather(self.weight1, axis=0, indices=inputs)


  x = tf.keras.Input(shape=[1,])
  ind = tf.cast(x, "int64")
  y = Layer1(shape=(10, 2))(ind)
  model = tf.keras.Model(x, y)
  model.compile(optimizer=optimizer, loss='mse')

  x_data = np.array([[random.randint(0, 9),],])

  out = model(x_data)
  y_data = np.zeros(out.shape)
  with tf.GradientTape() as tape:
    y_pred = model(x_data)
    loss = tf.keras.losses.MeanSquaredError()(y_data, y_pred)

    gradients = tape.gradient(loss, model.trainable_weights)

  optimizer.apply_gradients(zip(gradients, model.trainable_weights))

test_optimizer(tf.optimizers.Adam())
print('Adam Passed')
test_optimizer(tf.optimizers.Adadelta())

```

**Outputs / logs** 
```
Adam Passed
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-16-69f396904fc3> in <module>()
      1 test_optimizer(tf.optimizers.Adam())
      2 print('Adam Passed')
----> 3 test_optimizer(tf.optimizers.Adadelta())
      4 print('Adadelta Passed')

16 frames
<ipython-input-13-fbaf6e8a2eb4> in test_optimizer(optimizer)
     31     gradients = tape.gradient(loss, model.trainable_weights)
     32 
---> 33   optimizer.apply_gradients(zip(gradients, model.trainable_weights))


NotFoundError: No registered 'ResourceSparseApplyAdadelta' OpKernel for 'GPU' devices compatible with node {{node ResourceSparseApplyAdadelta}}
	.  Registered:  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
 [Op:ResourceSparseApplyAdadelta]
```

**Describe the current behavior**

I am using `Adadelta` optimizer for training on GPU. During backpropagation `optimizer.apply_gradients()` I encounter this `NotFoundError`: No registered 'ResourceSparseApplyAdadelta' OpKernel for 'GPU' devices compatible with node {{node ResourceSparseApplyAdadelta}}.

However, if `Adam` optimizer is used, no error occurs.

**Describe the expected behavior**
The `Adadelta` optimizer works on CPU. I expect `Adamdelta` optimizer to work also on GPU.

**Comment by lugalUrim** [comment]
There are some relevant issues, e.g. https://github.com/tensorflow/tensorflow/issues/38779, but I didn't find any solution to this problem.

**Comment by UsharaniPagadala** [comment]
@lugalUrim 

I reproduced the issue in tf-nightly did not face any error.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/b7b992805d254cc67d9cc69fb4bfb279/-48713.ipynb) here.Thanks

**Comment by lugalUrim** [comment]
@UsharaniPagadala Yes, the error is in tensorflow 2.4.1, and it seems to be fixed in tf 2.5 and tf-nightly.

There is a small bug in the code (should be `random.randint(0, 9)` instead of `random.randint(0, 10)`), I have edited the issue description to fix it.

**Comment by UsharaniPagadala** [comment]
@lugalUrim 

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.

**Comment by ymodak** [comment]
Currently Google colab hosts cuda 11.0 where as TF 2.5 and nightlies support cuda 11.2 so I suspect that in those cases the computation is falling back on cpu. We may want to test it with cuda 11.2 to be sure.
