### ISSUE TITLE
Unclear if Debug build on Windows is supported

### ISSUE THREAD

**Issue by libbooze** [tensorflow/tensorflow#48719]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/install/source_windows

## Description of issue (what needs changing):
Specify if building Debug verion of TF on Windows is possible. 
From looking at bugs here people are having problems, but it is unclear if it is officially not supported, or it is supported, clarifying that in docs would help.

**Comment by chunduriv** [comment]
@libbooze, 

As per [Debug Builds](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#debug-builds)

`--config=dbg `option is not officially supported. Thank you
