### ISSUE TITLE
tf.RaggedTensor.bounding_shape: out_type argument is ignored

### ISSUE THREAD

**Issue by Andreas5739738** [tensorflow/tensorflow#48721]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.5.0-rc0-36-g0d1805aede0 2.5.0-rc1
- Python version: 3.9.2
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
`RaggedTensor.bounding_shape` has an argument out_type which is supposed to control the type of the output tensor. But it does not seem to have any effect:
```
>>> tf.RaggedTensor.from_tensor([[1,2,3]]).bounding_shape(1, out_type=tf.int32)  # output is not int32
<tf.Tensor: shape=(), dtype=int64, numpy=3>
```

**Describe the expected behavior**
```
>>> tf.RaggedTensor.from_tensor([[1,2,3]]).bounding_shape(1, out_type=tf.int32)
<tf.Tensor: shape=(), dtype=int32, numpy=3>
```

**Standalone code to reproduce the issue**
```
>>> tf.RaggedTensor.from_tensor([[1,2,3]]).bounding_shape(1, out_type=tf.int32)
<tf.Tensor: shape=(), dtype=int64, numpy=3>
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.4.1, TF v2.5.0-rc1 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9640e7286e9edde8f7a32339625dc7cb/48721.ipynb#scrollTo=VGMsyaf7P_J4). Thanks!

**Comment by chunduriv** [comment]
@Andreas5739738, I tried to run your code on `Colab` using `TF v2.6` and `tf-nightly` and this issue was resolved. Please find the [gist](https://colab.research.google.com/gist/chunduriv/91da87b9e05efcb3eba7d0c6456ebefa/48721.ipynb) here for reference. Please feel free to close the issue if it is resolved ? Thanks!

**Comment by Andreas5739738** [comment]
Thank you! Confirming that this is resolved.
