### ISSUE TITLE
INSTALL ERROR: No matching distribution found for tensorflow on RASPERRY PI 4 ARM64 UBUNTU 18.04 

### ISSUE THREAD

**Issue by hassan-shehawy** [tensorflow/tensorflow#48733]
**System information**
- Hardware: Raspberry Pi 4 Model B Rev 1.4
- Architecture: aarch64
- OS Platform and Distribution: Ubuntu 18.04.1
- Python version: 3.7.5 [64-bit]
- Pip version: 21.0.1
- Installed using: virtualenv and pip

**Describe the problem**
I get the following error when I try to install: (I tried other versions of python including 3.5, 3.6, 3.7 and 3.8)
`ERROR: Could not find a version that satisfies the requirement tensorflow`
`ERROR: No matching distribution found for tensorflow`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Created virtual environment, activated it and then:
`pip3 install tensorflow`

**Comment by GodsNightmare** [comment]
$ git clone https://github.com/user/repo.git
# Clone a repo
> Cloning into 'repo'...
> remote: Counting objects: 66179, done.
> remote: Compressing objects: 100% (15587/15587), done.
> remote: Total 66179 (delta 46985), reused 65596 (delta 46402)
> Receiving objects: 100% (66179/66179), 51.66 MiB | 667 KiB/s, done.
> Resolving deltas: 100% (46985/46985), done.
> warning: remote HEAD refers to nonexistent

**Comment by DnPlas** [comment]
It seems that the pip package for TF2.* is not available for ARM64 yet, that is why you are getting an error message. You could try installing TF 2.3 using the wheel directly.
For example: `pip install https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.3.0rc2-cp35-none-linux_armv6l.whl` . Please check this [link](https://www.tensorflow.org/install/pip#package-location) for more info.
NOTE: That wheel was build for Pi3, if that doesn't work, you can try building TF from [source]( https://github.com/tensorflow/build/tree/master/raspberry_pi_builds).

**Comment by tilakrayal** [comment]
@hassan-shehawy ,

Please take a look at [DnPlas](https://github.com/tensorflow/tensorflow/issues/48733#issuecomment-827267559)   comment and let us know if you are still facing the same issue? Thanks!

**Comment by hassan-shehawy** [comment]
Thank you, but that wheel is for ARM32 and when I tried it, I got the error:
`ERROR: tensorflow-2.3.0rc2-cp35-none-linux_armv6l.whl is not a supported wheel on this platform`
I also tried another wheel made for ARM64 from [here](https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-64-os.html) and could install successfully but got an error when tried to import (described in #48761 )
I will try building from source and update here.

**Comment by hassan-shehawy** [comment]
I'm adding this comment to help anyone reading this and having same problems. I tried different things recommended by many persons trying to help, but I always got stuck with something. I think this is because it's usually very easy to overlook some details when I ask for help for my specific setup (RPI4+ARM64+Ubuntu18) and I found out that it's very common to receive help with the assumption that I'm using Raspbian or that my OS is 32-bit or I'm asking for TF lite or even thinking that Ubuntu 18 would be the same as 20. 

So what ended up working for me is building it from source following the official documentation tutorial [here](https://www.tensorflow.org/install/source) and it took 22 hours to compile. Don't be intimidated by the process; I know having a wheel file and just pip install looks way easier, but really building from source is quite straightforward. I also have the wheel file if you want (I will probably upload it on google drive or dropbox)

Because of the so many problems popping up, I don't remember them or their source. However, there were 4 errors that happened because I didn't give proper attention to some details:
1. Double check the .bazelversion file in the TF folder and make sure that this version really exists for ARM64 (at one point this created a problem for me because for a reason I don't know it was 1.3 and this version doesn't exist for aarch64)
If you are using a virtual environment:
2 You *must* do the configuration (via the configure.py file) before building, don't forget to do this :-)
3. If you didn't create it with --system-site-packages, make sure you have got everything you need (numpy, keras-preprocessing ...)
4. I got an error when I tried to import TF complaining about the version of numpy (I don't remember it). I solved it by `pip install --upgrade numpy`

**Comment by cemicel** [comment]
@hassan-shehawy Hi !
I've been straggling with the exact same issues for days..
Could you please share you wheels ?

**Comment by hassan-shehawy** [comment]
Hi, here's the wheel: (sorry to repeat it, but it's for TF 2.4 on ARM64, Ubuntu 18.04 and python 3.7 just to be 100% sure :-)

 https://drive.google.com/file/d/12hy4RdKPQgCImvr8pGt4nZyz2qmg3pd8/view?usp=sharing

**Comment by hassan-shehawy** [comment]
Hi, here's the wheel: (sorry to repeat it, but it's for TF 2.4 on ARM64, Ubuntu 18.04 and python 3.7 just to be 100% sure :-)

 https://drive.google.com/file/d/12hy4RdKPQgCImvr8pGt4nZyz2qmg3pd8/view?usp=sharing
