### ISSUE TITLE
tfa.seq2seq.AttentionWrapperState : TypeError: __new__() missing 3 required positional arguments: 'alignments', 'alignment_history', and 'attention_state'

### ISSUE THREAD

**Issue by Jeet1994** [tensorflow/tensorflow#48738]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**The following is my code block which uses AttentionWrapper:**

```
def decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, text_length, summary_length, 
                   max_summary_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers):
    '''Create the decoding cell and attention for the training and inference decoding layers'''
    
    for layer in range(num_layers):
        with tf.variable_scope('decoder_{}'.format(layer)):
            lstm = tf.compat.v1.nn.rnn_cell.LSTMCell(rnn_size,
                                           initializer=tf.random_uniform_initializer(-0.1, 0.1, seed=2))
            dec_cell = tf.compat.v1.nn.rnn_cell.DropoutWrapper(lstm, 
                                                     input_keep_prob = keep_prob)
    
    output_layer = Dense(vocab_size,
                         kernel_initializer = tf.truncated_normal_initializer(mean = 0.0, stddev=0.1))
    
    attn_mech = tfa.seq2seq.BahdanauAttention(rnn_size,
                                                  enc_output,
                                                  text_length,
                                                  normalize=False,
                                                  name='BahdanauAttention')

    dec_cell = tfa.seq2seq.AttentionWrapper(dec_cell,
                                                          attn_mech,
                                                          rnn_size)
            
    
    initial_state = tfa.seq2seq.AttentionWrapperState(enc_state[0],_zero_state_tensors(rnn_size,batch_size,tf.float32))
     
    with tf.variable_scope("decode"):
        training_logits = training_decoding_layer(dec_embed_input, 
                                                  summary_length, 
                                                  dec_cell, 
                                                  initial_state,
                                                  output_layer,
                                                  vocab_size, 
                                                  max_summary_length)
    with tf.variable_scope("decode", reuse=True):
        inference_logits = inference_decoding_layer(embeddings,  
                                                    vocab_to_int['<GO>'], 
                                                    vocab_to_int['<EOS>'],
                                                    dec_cell, 
                                                    initial_state, 
                                                    output_layer,
                                                    max_summary_length,
                                                    batch_size)

    return training_logits, inference_logits
```

When I run the below block:

```
# Build the graph
train_graph = tf.Graph()
# Set the graph to default to ensure that it is ready for training
with train_graph.as_default():
    
    # Load the model inputs    
    input_data, targets, lr, keep_prob, summary_length, max_summary_length, text_length = model_inputs()

    # Create the training and inference logits
    training_logits, inference_logits = seq2seq_model(tf.reverse(input_data, [-1]),
                                                      targets, 
                                                      keep_prob,   
                                                      text_length,
                                                      summary_length,
                                                      max_summary_length,
                                                      len(vocab_to_int)+1,
                                                      rnn_size, 
                                                      num_layers, 
                                                      vocab_to_int,
                                                      batch_size)
    
    # Create tensors for the training logits and inference logits
    training_logits = tf.identity(training_logits.rnn_output, 'logits')
    inference_logits = tf.identity(inference_logits.sample_id, name='predictions')
    
    # Create the weights for sequence_loss
    masks = tf.sequence_mask(summary_length, max_summary_length, dtype=tf.float32, name='masks')

    with tf.name_scope("optimization"):
        # Loss function
        cost = tf.contrib.seq2seq.sequence_loss(
            training_logits,
            targets,
            masks)

        # Optimizer
        optimizer = tf.train.AdamOptimizer(learning_rate)

        # Gradient Clipping
        gradients = optimizer.compute_gradients(cost)
        capped_gradients = [(tf.clip_by_value(grad, -5., 5.), var) for grad, var in gradients if grad is not None]
        train_op = optimizer.apply_gradients(capped_gradients)
print("Graph is built.")
```

I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-111-2482e3ce02af> in <module>
      8 
      9     # Create the training and inference logits
---> 10     training_logits, inference_logits = seq2seq_model(tf.reverse(input_data, [-1]),
     11                                                       targets,
     12                                                       keep_prob,

<ipython-input-107-605aa3e33839> in seq2seq_model(input_data, target_data, keep_prob, text_length, summary_length, max_summary_length, vocab_size, rnn_size, num_layers, vocab_to_int, batch_size)
     12     dec_embed_input = tf.nn.embedding_lookup(embeddings, dec_input)
     13 
---> 14     training_logits, inference_logits  = decoding_layer(dec_embed_input, 
     15                                                         embeddings,
     16                                                         enc_output,

<ipython-input-106-b74ed3efc070> in decoding_layer(dec_embed_input, embeddings, enc_output, enc_state, vocab_size, text_length, summary_length, max_summary_length, rnn_size, vocab_to_int, keep_prob, batch_size, num_layers)
     24 
     25 
---> 26     initial_state = tfa.seq2seq.AttentionWrapperState(enc_state[0],_zero_state_tensors(rnn_size,batch_size,tf.float32))
     27 
     28     with tf.variable_scope("decode"):

TypeError: __new__() missing 3 required positional arguments: 'alignments', 'alignment_history', and 'attention_state'
```

Please help.

**Comment by GodsNightmare** [comment]
$ git clone https://github.com/user/repo.git
# Clone a repo
> Cloning into 'repo'...
> remote: Counting objects: 66179, done.
> remote: Compressing objects: 100% (15587/15587), done.
> remote: Total 66179 (delta 46985), reused 65596 (delta 46402)
> Receiving objects: 100% (66179/66179), 51.66 MiB | 667 KiB/s, done.
> Resolving deltas: 100% (46985/46985), done.
> warning: remote HEAD refers to nonexistent

**Comment by Jeet1994** [comment]
I don't understand. Whar are you suggesting?

**Comment by tilakrayal** [comment]
@Jeet1994 ,

I ran the code shared and face a different error, please find the [gist](https://colab.research.google.com/gist/tilakrayal/76580ef8070839db0c60bbda78d4772b/untitled48738.ipynb) here and share all dependencies to replicate the issue or share a colab gist with the reported error.

Thanks

**Comment by Jeet1994** [comment]
Hi @tilakrayal ,

Sorry for the delay.

Please find the collab link for the entire [code](https://colab.research.google.com/drive/1Nm24Qn6VN_TatOpAiElmxniZJe6eO0sY?usp=sharing)

Please help.

**Comment by tilakrayal** [comment]
@Jeet1994 ,

The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. Thanks!

**Comment by Jeet1994** [comment]
@tilakrayal 

Hi, 

The code is complex, understood. Let me explain you the issue once again, the problem is with the usage of function `tfa.seq2seq.AttentionWrapperState` , which is a function defined under *tensorflow addons**. 

Please look at the original code snippet added with the issue.

Request you to delegate the issue to someone who can help me in this matter, if you are unable to do so.

**Comment by Saduf2019** [comment]
@Jeet1994 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

You may refer to simialr error issue here: [link](https://github.com/tensorflow/tensorflow/issues/20727),[link2](https://stackoverflow.com/questions/37457207/python-typeerror-new-missing-1-required-positional-argument-namespace)

**Comment by Jeet1994** [comment]
Hello @Saduf2019 I am sorry, but I expected some help on the matter. I have asked this question on Stackoverflow without any input. If you cannot help, you may assign someone who can. 

Please pardon me, but I expected better.

**Comment by ymodak** [comment]
> Please find the collab link for the entire [code](https://colab.research.google.com/drive/1Nm24Qn6VN_TatOpAiElmxniZJe6eO0sY?usp=sharing)

@Jeet1994 Thanks for your issue but code snippet you gave upstream is not minimal. 

I see you have pinned the problem to usage of `tfa.seq2seq.AttentionWrapperState`
> The code is complex, understood. Let me explain you the issue once again, the problem is with the usage of function `tfa.seq2seq.AttentionWrapperState` , which is a function defined under **tensorflow addons**.

Ideally you want to create a toy example for `tfa.seq2seq.AttentionWrapperState` with minimal code to reproduce the reported behavior in your case. Also [tf-addon](https://github.com/tensorflow/addons/issues) repo can be a good platform for the issue. Tagging maintainers /tensorflow_addons/seq2seq/  @guillaumekln to take a further look.
Thanks!

**Comment by guillaumekln** [comment]
@Jeet1994, you should call the method [`AttentionWrapper.get_initial_state`](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/AttentionWrapper?hl=fr#get_initial_state) instead of manually building the initial state. For example:

```python
# Get the initial zero state.
initial_state = dec_cell.get_initial_state(batch_size=batch_size, dtype=tf.float32)

# Initialize the cell state from the encoder.
initial_state = initial_state.clone(cell_state=enc_state)
``` 

Also note that you are using RNN cells from `tf.compat.v1` which is not supported. You should update your code to TensorFlow 2.

**Comment by Jeet1994** [comment]
Thank you @guillaumekln . I solved the problem with your guidance. All the best to all who tried to help me.
