### ISSUE TITLE
TFlite on container problem

### ISSUE THREAD

**Issue by mind-mind** [tensorflow/tensorflow#48745]
Hello, I run inference model TFlite on this Github: https://github.com/Mjrovai/TFLite_IA_at_the_Edge 

It can run on raspbian 32 bit without any problem, but after I put it on the container. I got an error: 

Traceback (most recent call last):
  File "TFLite_IA_at_the_Edge/mMobile.py", line 42, in <module>
    model_path='./models/mobilenet_v1_1.0_224_quant.tflite')
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Could not open './models/mobilenet_v1_1.0_224_quant.tflite'.

I guess the problem may be TFlite doesn't support this image or something. I use base docker image jsurf/rpi-raspbian 

Any idea about this?

**Comment by abattery** [comment]
Please make sure the above model file is accessible in the container. Looks like there are possibilities that the file location is wrong or the model file is not available from the container.

**Comment by mind-mind** [comment]
I can fix it now, it was because of the path on the container. Thank you.
