### ISSUE TITLE
mbed/STM32F7 compiling issue with AllOpsResolver: undefined reference to `__SXTB16_RORn'

### ISSUE THREAD

**Issue by wdjose** [tensorflow/tensorflow#48741]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 8cae746d8449c7dda5298327353d68613f16e798
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm Mbed OS (ST-Discovery-STM32F746NG)
- Mbed version: mbed-cli==1.10.5
- GNU Arm embedded toolchain version: 10-2020-q4-major

**Describe the problem**
While running mbed compilation on the tflite micro example `hello_world`, I experienced errors relating to ``undefined reference to `__SXTB16_RORn'``. Investigating further, it seems to be a problem with the `AllOpsResolver`, specifically when it calls `AddConv2D()` (details below). 

**Please provide the exact sequence of commands/steps when you ran into the problem**
I followed the changes to `tensorflow/lite/micro/examples/hello_world` from the recent [pull request](https://github.com/tensorflow/tensorflow/pull/48659) for `tensorflow/lite/micro/examples/micro_speech` which updated the `make` command and `disco_f746ng/Makefile.inc` to use `TARGET` and `OPTIMIZED_KERNEL_DIR` instead of `TAGS`. See [changes here](https://github.com/tensorflow/tensorflow/pull/48740). 
```bash
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=disco_f746ng OPTIMIZED_KERNEL_DIR=cmsis_nn generate_hello_world_mbed_project
$ cd tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed
$ mbed config root .
$ mbed deploy
$ mbed compile -m DISCO_F746NG -t GCC_ARM
```
And here is the output of the `mbed compile` command: 
```bash
[mbed] Working path "/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed" (library)
[mbed] Program path "/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed"
[Warning] @,: Compiler version mismatch: Have 10.2.1; expected version >= 9.0.0 and < 10.0.0
Building project mbed (DISCO_F746NG, GCC_ARM)
Scan: mbed
Link: mbed
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.o: in function `arm_nn_mat_mult_nt_t_s8':
/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:109: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:110: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:116: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:123: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:134: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.o:/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:135: more undefined references to `__SXTB16_RORn' follow
collect2: error: ld returned 1 exit status
[ERROR] /usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.o: in function `arm_nn_mat_mult_nt_t_s8':
/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:109: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:110: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:116: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:123: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:134: undefined reference to `__SXTB16_RORn'
/usr/share/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.o:/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/NNSupportFunctions/arm_nn_mat_mult_nt_t_s8.c:135: more undefined references to `__SXTB16_RORn' follow
collect2: error: ld returned 1 exit status

[mbed] ERROR: "/home/user/.virtualenvs/mbed/bin/python" returned error.
       Code: 1
       Path: "/home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed"
       Command: "/home/user/.virtualenvs/mbed/bin/python -u /home/user/Git/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/mbed-os/tools/make.py -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```
If I [comment out `AddConv2D()` in `tensorflow/lite/micro/all_ops_resolver.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/all_ops_resolver.cc#L33), the problem goes away. 
Similarly in `tensorflow/lite/micro/examples/micro_speech`, if I replace the Op Resolver from `MicroMutableOpResolver` to `AllOpsResolver`, the same error above appears. 
I'm not sure if this is a problem upstream with [Mbed CLI](https://github.com/ARMmbed/mbed-cli/), or with the Arm CMSIS library.

**Comment by GodsNightmare** [comment]
$ git clone https://github.com/user/repo.git
# Clone a repo
> Cloning into 'repo'...
> remote: Counting objects: 66179, done.
> remote: Compressing objects: 100% (15587/15587), done.
> remote: Total 66179 (delta 46985), reused 65596 (delta 46402)
> Receiving objects: 100% (66179/66179), 51.66 MiB | 667 KiB/s, done.
> Resolving deltas: 100% (46985/46985), done.
> warning: remote HEAD refers to nonexistent

**Comment by patriklaurell** [comment]
@wdjose I believe this is related the problem described in the second half of [this example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/kernels/cmsis_nn#example-2---mbed) and the fix there should allow you to compile.

**Comment by wdjose** [comment]
@patriklaurell Thanks! I just tried it, and you're right, it seems that the old "cmsis_gcc.h" is needed. After copying "cmsis_gcc.h", the program successfully compiles. 

I'm just copying the specific lines I followed from the example you quoted (in case anyone else experiences the issue): 

> Note: Mbed has a dependency to an old version of arm_math.h. Therefore you need to copy the newer version as follows:
> ```
> cp tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/\
> arm_math.h mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h
>```
>
> There's also a dependency to an old cmsis_gcc.h, which you can fix with the following:
> ```
> cp tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include/\
> cmsis_gcc.h mbed-os/cmsis/TARGET_CORTEX_M/cmsis_gcc.h
> ```

I also added these same lines to the [pull request](https://github.com/tensorflow/tensorflow/pull/48740) I created to fix the compilation of `example/hello_world`, similar to the [pull request](https://github.com/tensorflow/tensorflow/pull/48659) (for `example/micro_speech`) that incidentally was submitted by you as well.

**Comment by fahadshah-groundtruth** [comment]
Hello, I am facing the same issue during the compilation of a project Hello Edge KWS using mbedOS. Please share the same files that you used in example. See my error details below;

************************************************************************
Compile [ 98.4%]: arm_max_pool_s8.c
Compile [ 98.6%]: arm_svdf_s8.c
Compile [ 98.7%]: arm_softmax_s8.c
Compile [ 98.9%]: arm_softmax_s8_s16.c
Compile [ 99.0%]: arm_softmax_s16.c
Compile [ 99.2%]: arm_nn_softmax_common_s8.c
Compile [ 99.3%]: arm_softmax_u8.c
Compile [ 99.4%]: plot_utils.cpp
[Error] arm_nnsupportfunctions.h@681,54: '__SXTB16_RORn' was not declared in this scope
[ERROR] In file included from ../Source/local_NN/local_NN.h:1:0,
                 from ../Source/NN/DS_CNN/ds_cnn.h:24,
                 from ../Source/KWS/KWS_DS_CNN/kws_ds_cnn.h:23,
                 from ../Source/KWS_F746NG/kws_f746ng.h:23,
                 from ../Examples/realtime_test\plot_utils.h:19,
                 from ../Examples/realtime_test\plot_utils.cpp:19:
../CMSIS_5/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'const int8_t* read_and_pad(const int8_t*, int32_t*, int32_t*)':
../CMSIS_5/CMSIS/NN/Include/arm_nnsupportfunctions.h:681:54: error: '__SXTB16_RORn' was not declared in this scope
     int32_t inAbuf1 = __SXTB16_RORn((uint32_t)inA, 8U);
                                                      ^

[mbed] ERROR: "C:\Python27\python.exe" returned error.
       Code: 1
       Path: "C:\prj_KWS\Deployment\ML-KWS-for-MCU\Deployment\kws_realtime_test"
       Command: "C:\Python27\python.exe -u C:\prj_KWS\Deployment\ML-KWS-for-MCU\Deployment\kws_realtime_test\tools\make.py -t GCC_ARM -m DISCO_F746NG --profile ../release_O3.json --source . --source ../Source --source ../Examples/realtime_test --source ../CMSIS_5/CMSIS/NN/Include --source ../CMSIS_5/CMSIS/NN/Source --source ../CMSIS_5/CMSIS/DSP/Include --source ../CMSIS_5/CMSIS/DSP/PrivateInclude --source ../CMSIS_5/CMSIS/DSP/Source --source ../CMSIS_5/CMSIS/Core/Include --build .\BUILD\DISCO_F746NG\GCC_ARM-RELEASE_O3 -j 8"
       Tip: You could retry the last command with "-v" flag for verbose output
