### ISSUE TITLE
bugNodeDef expected inputs 'float, int32' do not match 1 inputs specified

### ISSUE THREAD

**Issue by chenglong0317** [tensorflow/tensorflow#48746]
### env
win10
py3.6
tf-1.15.2
gpu1070
-------------------------------------------------------------------------------------------------------------------------
This is the code I run. The failure caused by this function-- tf.train.import_meta_graph. i want to reload 'mobilenet_v2_1.4_224.ckpt.meta'. this pre-model is from [slim pre-model](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.4_224.tgz).

```python
def copy_var_from_ckpt(ckpt_path, meta_graph_path):
    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        saver = tf.train.import_meta_graph(meta_graph_path)
        saver.restore(sess, ckpt_path)
        graph = tf.Graph().as_default()
```

The following information is obtained

```python
 File "C:\Program Files\Python36\lib\site-packages\tensorflow_core\python\framework\importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs 'float, int32' do not match 1 inputs specified; Op<name=CrossReplicaSum; signature=input:T, group_assignment:int32 -> output:T; attr=T:type,allowed=[DT_BFLOAT16, DT_FLOAT, DT_INT32, DT_UINT32]>; NodeDef: {{node TPUReplicate/loop/CrossReplicaSum}}
```
How to solve it?

**Comment by chenglong0317** [comment]
I want to load the weights from the pre training model into an extended network structure. this is full code.
```python
def copy_var_from_ckpt(session, graph01, dst_var_names, ckpt_path, meta_graph_path):
    '''
    session    新图的会话sess
    dst_var_names   新图的变量名字
    dst_vars     # 新图的变量节点
    ckpt_path   # 原始ckpt路径
    meta_graph_path # 原始的meta图文件
    '''
    graph = tf.Graph()
    with graph.as_default():
        with tf.Session() as sess:
            saver = tf.train.import_meta_graph(meta_graph_path)
            saver.restore(sess, ckpt_path)
            v_names = []
            for v in tf.trainable_variables():
                v_names.append(v)
                print(v.name,' --> ',v)
            for dst_var_name in dst_var_names:
                if dst_var_name.name in v_names:
                    tensor = graph.get_tensor_by_name(dst_var_name)
                    vs = graph01.get_tensor_by_name(dst_var_name)
                    weight = sess.run(tensor)
                    session.run(vs.assign(weight))

```

**Comment by tilakrayal** [comment]
@chenglong0317 ,

We see that you are using tf version 1.15, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

**Comment by chenglong0317** [comment]
> 
> 
> @chenglong0317 ,
> 
> We see that you are using tf version 1.15, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

but tf2.0 do not support slim. this code and pre-model is about slim. from :https://github.com/tensorflow/models/tree/master/research/slim

**Comment by chenglong0317** [comment]
> 
> 
> @chenglong0317 ,
> 
> We see that you are using tf version 1.15, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

let me try

**Comment by tilakrayal** [comment]
@chenglong0317 ,

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status 

Thanks!
