### ISSUE TITLE
win10  bazel Extracting Bazel installation...

### ISSUE THREAD

**Issue by rainmakerMa** [tensorflow/tensorflow#48748]
i wanna build the tf2.4 version with rtx3070,cuda11,cudnn8 on win10 system

according to the official tutorial, I have built the msys2, visual studio 2019,and all the configuration including the path set

however when i installed the bazel, when i open the cmd window, when i type bazel ,it just stagnate Extracting Bazel installation... and quit.

why was that?SOS

**Comment by amahendrakar** [comment]
@rainmakerMa,
Could you please run the `bazel version` command and share the output with us.

Also make sure you have installed bazel as per the [official guide](https://docs.bazel.build/versions/master/install-windows.html). Thanks!

**Comment by mihaimaruseac** [comment]
Not a TF issue. Your system might be too slow for Bazel to fully unpack. In any case, this is a Bazel issue, should be opened in the Bazel repository.
