### ISSUE TITLE
Error for Mac El-capitan while installing tensorflow GPU version on CUDA 8.0

### ISSUE THREAD

**Issue by dsl10brc** [tensorflow/tensorflow#4875]
Below is the error I am getting when I import tensorflow:

import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/d/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/d/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/d/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/d/anaconda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/d/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Users/d/anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

I don't understand why it is asking for libcudart.7.5.dylib when I have installed CUDA 8.0. Theano is working perfectly fine for me on GPU but tensorflow is not. Any help would be appreciated. I have exactly followed the steps mentioned on tensorflow website. I also tried disabling SIP protection in El-capitan as mentioned in other similar github issues but no luck.

**Comment by ohadle** [comment]
I'm a total TF newbie (literally running first net now), but AFAICT:
The stable version 0.11rc0 doesn't support CUDA 8. Next version (0.11rc1, <= 1 week) should solve this.

Refs:
https://github.com/tensorflow/tensorflow/issues/3069#issuecomment-252493740
https://github.com/tensorflow/tensorflow/issues/3052#issuecomment-252470239
https://github.com/tensorflow/tensorflow/issues/2559

**Comment by jart** [comment]
Correct. We don't support CUDA 8 yet. But that should hopefully change in a matter of weeks when rc2 comes out. Thanks for taking the time to report the issue.

**Comment by jart** [comment]
For people googling this issue in the future: the solution may have been to disable SIP (System Integrity Protection) by running `csrutil disable`.
