### ISSUE TITLE
Tensorflow latest GPU docker container doesn't include object detection API

### ISSUE THREAD

**Issue by mjbedford2017** [tensorflow/tensorflow#48769]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): From docker container
- TensorFlow version: latest docker container
- Python version: latest docker container
- Installed using virtualenv? pip? conda?: from docker container
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: last docker container, looks like 11.2
- GPU model and memory: Tesla P4

**Describe the problem**
I was under the impression (correct me if I am wrong about this) that I could use the docker container to do object detection tasks, mainly I would like to use the container to train models on my machine. However, it appears that this container does not include the Object Detection API and compiled protos that go along with it. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@mjbedford2017 ,

In order to expedite the trouble-shooting process, could you please provide the following information
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

Thanks

**Comment by mjbedford2017** [comment]
Hello, thank you for looking into this. Just to clarify, I am using the tensorflow docker container, which comes with software defined in the docker file. I got the docker container using "latest GPU" 2 days ago. Here is the docker file I believe it is using (latest GPU) https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile

TensorFlow installed from (source or binary): From binary.
TensorFlow version: Latest release, 2.4
Python version: 3.8
Installed using virtualenv? pip? conda?: Not sure, docker container?
Bazel version (if compiling from source): Not sure, docker container?
GCC/Compiler version (if compiling from source): Not sure, docker container?
CUDA/cuDNN version: Per docker file, this is 11.2 CUDA and cuDNN is 8.1.0.77-1
GPU model and memory: Nvidia Tesla P4 with 8GB GPU RAM

I am simply trying to use the docker container for training model. In order to do this, the "Object Detection API" needs to be installed. It does not seem to be included in the docker container and while I might be able to manually add it, each time an updated docker container is released, I would have to do it all over again. 

I would like this API in the container: https://github.com/tensorflow/models/tree/master/research/object_detection so I can do model stuff, like training.

**Comment by tilakrayal** [comment]
@mjbedford2017 ,

TensorFlow v2.4 is built and tested against CUDA 11.0 and cuDNN 8. Could you please install the CUDA and cuDNN packages on your machine to compatible versions and check if you are facing same issue.For more information please take a look at the [tested build configurations.](https://www.tensorflow.org/install/source#gpu)

Thanks
