### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by geo-dingky** [tensorflow/tensorflow#48766]
from tensorflow.contrib.layers.python import layers as tf layers

ModuleNotFoundError: No module named 'tensorflow.contrib'

Do I need to change tensorflow2.41 to 1.14? Do I need to delete tensorflow2.4?

**Comment by tilakrayal** [comment]
@geo-dingky ,

Please refer the  issues #36878, #35197, #30794, [37720](https://github.com/tensorflow/tensorflow/issues/37720#issuecomment-601624532) with similar error log.It helps.

Thanks

**Comment by bhack** [comment]
Tensorflow layer are now at https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer

**Comment by tilakrayal** [comment]
@geo-dingky ,

Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status

Thanks!
