### ISSUE TITLE
"Context not initialized" exception when calling tf.experimental.dlpack.from_dlpack()

### ISSUE THREAD

**Issue by gt1485a** [tensorflow/tensorflow#48765]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: Quadro M1000M (2GB) /1080 Ti (11GB)

**Describe the current behavior**
Unhandled Exception: "Context must be initialized first" when executing a tf.experimental.dlpack.from_dlpack() before any other tf commands..

**Describe the expected behavior**
tf.experimental.dlpack.from_dlpack() should complete when called with valid arguments before other tf calls.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
tensor = 1 #dummy argument to produce the error
OffsetData = tf.experimental.dlpack.from_dlpack(tensor)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**workaround**
this produces the correct exception of "incompatible function arguments"

```python
    import tensorflow as tf
    tensor = 1
    v = tf.constant([1])
    OffsetData = tf.experimental.dlpack.from_dlpack(tensor)
```

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in TF v2.4.v2.5.0rc1,nightly.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/d57c4ab38273df93affd2b1968f39226/48765.ipynb) here
