### ISSUE TITLE
Error when import: Failed to load the native TensorFlow runtime version GLIBC_2.28 not found

### ISSUE THREAD

**Issue by hassan-shehawy** [tensorflow/tensorflow#48761]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.1
- TensorFlow version: 2.2.0
- Hardware: Raspberry Pi 4 Model B Rev 1.4
- Architecture: aarch64
- Python version: 3.7.5 [64-bit]
- Installed using: virtualenv and pip
- ldd version: ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27

**Describe the problem**
I used the wheel referred to in this tutorial [tutorial](https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-64-os.html) and installed using pip successfully. However, when I tried to import TF I get this error:
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
Some sources suggest downgrading python which is not an option for me as this wheel I'm using needs explicitly 3.7 (if there's another wheel I can use, I'm willing to use other version of python, but I prefer to stick with ubuntu 18.04)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`sudo apt-get install python3.7 python3.7-dev  python3.7-venv`
`python3.7 -m venv donkey` 
`source donkey/bin/activate`
`gdown https://drive.google.com/uc?id=1fR9lsi_bsI_npPFB-wZyvgjbO0V9FbMf`
`pip install tensorflow-2.2.0-cp37-cp37m-linux_aarch64.whl`

**Any other info / logs**
<pre>
Traceback (most recent call last):
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/ubuntu/donkey/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.</pre>

**Comment by ymodak** [comment]
See https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel the note says that you need to have glibc >= 2.28 Thanks!

**Comment by hassan-shehawy** [comment]
> See https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel the note says that you need to have glibc >= 2.28 Thanks!

Thank you, although note you refer to is in fact in the page of TF "lite"

**Comment by hassan-shehawy** [comment]
I'm adding this comment to help anyone reading this and having same problems. I tried different things recommended by many persons trying to help, but I always got stuck with something. I think this is because it's usually very easy to overlook some details when I ask for help for my specific setup (RPI4+ARM64+Ubuntu18) and I found out that it's very common to receive help with the assumption that I'm using Raspbian or that my OS is 32-bit or I'm asking for TF lite or even thinking that Ubuntu 18 would be the same as 20. 

So what ended up working for me is building it from source following the official documentation tutorial [here](https://www.tensorflow.org/install/source) and it took 22 hours to compile. Don't be intimidated by the process; I know having a wheel file and just pip install looks way easier, but really building from source is quite straightforward. I also have the wheel file if you want (I will probably upload it on google drive or dropbox)

Because of the so many problems popping up, I don't remember them or their source. However, there were 4 errors that happened because I didn't give proper attention to some details:
1. Double check the .bazelversion file in the TF folder and make sure that this version really exists for ARM64 (at one point this created a problem for me because for a reason I don't know it was 1.3 and this version doesn't exist for aarch64)
2. If you are using a virtual environment: You *must* do the configuration (via the configure.py file) before building, don't forget to do this :-)
3. If you didn't create it with --system-site-packages, make sure you have got everything you need (numpy, keras-preprocessing ...)
4. I got an error when I tried to import TF complaining about the version of numpy (I don't remember it). I solved it by `pip install --upgrade numpy`
