### ISSUE TITLE
C API Locking prevents custom gradient definition

### ISSUE THREAD

**Issue by rnett** [tensorflow/tensorflow#48767]
I am trying to add custom gradient support to the Java bindings (tensorflow/java#292).  This is currently being prevented by the fact that `TF_AddGradientsWithPrefix` requires a lock on the graph, but so do any operation creation methods (i.e. `TF_NewOperation`), so it is impossible to create ops in gradient functions.

Is there a way I can get around this?  I am considering calling `TF_NewOperationLocked` directly but I assume the locks are there for a reason.

**Comment by kkimdev** [comment]
Thanks for reporting the issue!

**Comment by saxenasaurabh** [comment]
Please feel free to send a PR!

**Comment by rnett** [comment]
I can, but what's the preferred solution?  Providing and exposing a `TF_AddGradientsWithPrefixLocked` that doesn't lock, or exposing `TF_NewOperationLocked` and `TF_FinishOperationLocked`?  (See #48815)

**Comment by saxenasaurabh** [comment]
Exposing `TF_NewOperationLocked` and `TF_FinishOperationLocked` sgtm.
