### ISSUE TITLE
Request for an Efficient Way of handling NLP Tasks with Saving Model weights along with its tokenizer and architecture in JSON 

### ISSUE THREAD

**Issue by harshgeek4coder** [tensorflow/tensorflow#48768]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
- In the Current Feature of TensorFlow, when we work with Natural Language Processing Based Tasks, we have the ability to only save the ```model architecture``` and ``` model weights```, that too with two different function calls. We need to mention an explicit file handling operation to save the ```tokenizer```  in JSON format too. This might lead to a bit of inefficiency.

- Therefore , I would like to suggest and provide code for one single function , which would save the model weights , its architecture and the current tokenizer in JSON format ,  and along with it , a single load function to retrieve all these three files with one single function call. This will help to improve the efficiency and modular programming and ease of use of TensorFlow to save and load models with one single function call, rather than calling different function counterparts.

**Will this change the current api? How?**
Not to a great extent. Since these are two normal functions that will require ``` model``` as a parameter, it will save model architecture, its weights, and tokenizer.json will directly be saved from the tokenizer object created. 

**Who will benefit with this feature?**
All the developers who use TensorFlow for Natural Language Processing Tasks in deep learning.

**Any Other info.**
I already have the code snippet ready and have tested it with a couple of my models.

**Comment by mattdangerw** [comment]
@harshgeek4coder thanks for the report! If you have a code snippet ready, could you post it as a gist or colab here and we could take a look?

Is the goal to have JSON specifically? Or just a way to save a model architecture and weights. If the latter, the SavedModel format would be the way to do this today. Is there a reason that doesn't work for your use case?
https://www.tensorflow.org/guide/keras/save_and_serialize

Thanks!

**Comment by harshgeek4coder** [comment]
Hey, @mattdangerw   Thanks for replying back. So the thing is, when we handle basic NLP Tasks, we require the tokenizer's saved state data for later use so that once we load the saved models, we need tokenizer's data to identify word indexes for each unique word in custom data for the model prediction.

Coming Back to your question, the main goal is to save Tokenizer's state in JSON format which will be required by the loaded model along with the model's loaded architecture state.

The Current ```SavedModel``` format can be used to save the model architecture, we also have to use```save_weights``` to save model weights explicitly and do some file handling operation to save Tokeniser's data in JSON format. But all these different functions take some time to be annotated manually.
Here is the Flow of how It currently works [ NLP Operation ]:
- Step 1: Save Model
- Step 2: Save Model weights
- Step 3: Save Tokenizer in JSON format

All of the above steps can be performed, but have to be done via three different function calls explicitly, including some manual annotation and file handling operation, which is a bit time-consuming. The same thing has to be done to load all the respective components which again takes more time to be done.

Keeping this thing in mind and with the help of current TensorFlow's utility, I would like to contribute to TensorFlow's official repository and therefore would like to propose a single and simple function, which can be used with one simple call and can perform all these three tasks in one single function call. I have also written another custom function that could call all these three different components in one single call.

Here is the ```Gist``` and ```Colab``` Link For your Further Reference : 

- https://colab.research.google.com/drive/1D1swi-aSZdTliGIYS03ZeOyuFdylUX48?usp=sharing

- [Direct Link to Cell Of Colab - For ```save model''' function](https://colab.research.google.com/drive/1D1swi-aSZdTliGIYS03ZeOyuFdylUX48#scrollTo=71VEwiAjlYlM&line=1&uniqifier=1)

- [Direct Link to Cell Of Colab - For ```load model''' function](https://colab.research.google.com/drive/1D1swi-aSZdTliGIYS03ZeOyuFdylUX48#scrollTo=-fOxOjLQRLxP&line=10&uniqifier=1)

- [Gist File For the functions ](https://gist.github.com/harshgeek4coder/15c87917057db4937ace7b756e16b00b)

**Comment by mattdangerw** [comment]
Got it. Thanks!

For the SavedModel format, that is intended to save both the model architecture and the model weights. `model.save(some_path)` will do that.

On the tokenization front, we are actually working on new layers for tokenization (and mapping strings to indices generally), that will integrate better with a keras model:

https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/TextVectorization
https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/StringLookup

TextVectorization supports different tokenization steps which you can pass in. The state of these layers will be reflected in your architecture and weights as normal.

If you use these, or write your own custom layer for tokenization, then using SavedModel directly (`model.save`) will be the simplest way to save your entire model state. You could still save the model architecture and weights separately if you want.
