### ISSUE TITLE
Probele with make when trying to build the Test_hello_world_test TinyML

### ISSUE THREAD

**Issue by Mon3am** [tensorflow/tensorflow#48778]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 1.12.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): PC

**Describe the problem**
I'm trying to build the Test_hello_world_test from the TinyML book using make command but I receive the following error.
Make version is 4.3.
I found some other issues but they don't resolve my probleme. I'am bocked at this stage.
It seems that the probleme is with the makefile
Can Any One Help Me Please?

**Please provide the exact sequence of commands/steps when you ran into the problem**

C:\tensorflow>make -f tensorflow/lite/micro/tools/make/Makefile hello_world_test
process_begin: CreateProcess(NULL, uname -m, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:47: pipe: No error
-m était inattendu.
'tr' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
FIND : format incorrect de paramètre
FIND : format incorrect de paramètre
La syntaxe de la commande n’est pas correcte.
process_begin: CreateProcess(NULL, bash C:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:570: pipe: Bad file descriptor
tensorflow/lite/micro/tools/make/Makefile:572: *** Something went wrong with the flatbuffers download: .  Stop.

**Comment by tilakrayal** [comment]
@Mon3am ,

We see that you are using tf version 1.15, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

**Comment by Mon3am** [comment]
Hi
thank you for your response
I updated the Tensorflow to version 2.4.1 but I still receive the same error

**Comment by ymodak** [comment]
Please take a look at similar [thread](https://forums.tinyml.org/t/make-doesnt-work-on-hello-world-test-from-tinyml-book/344) for workarounds.
