### ISSUE TITLE
Wrong results of AvgPoolGrad and AvgPool3dGrad in some specific shapes

### ISSUE THREAD

**Issue by hmzzl** [tensorflow/tensorflow#48773]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
 **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
 **Linux Ubuntu 18.04**
- TensorFlow installed from (source or binary):
**source**
- TensorFlow version (use command below):
2.4.1 and 1.15 both tried
- Python version:
3.7.5

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hello, I'm using MaxPoolGrad and find that in same cases the results seemed to be wrong compared with hand-calculated results.   One of the cases is as follows.

    **grad_shape = (1, 1, 5, 1)
    input_shape = (1, 1, 5, 1)
    kernel_size = [1, 1, 7, 1]
    stride_size = [1, 1, 1, 1]
    padding = 'SAME'**

For the convenience of calculation， I set the grad with all one value. 
Then the result is
```
tf.Tensor(
[[[[0.8 ]
   [1.05]
   [1.05]
   [1.05]
   [1.05]]]], shape=(1, 1, 5, 1), dtype=float32)
```
While the hand-calculated result is 
```
[[[[0.85 ]
   [1.1]
   [1.1]
   [1.1]
   [0.85]]]]
tips:
0.85 = 1/4 + 1*3/5
1.1 = 1*2/4 +1*3/5
```

The differences appear in following cases:
-kernel_h > input_h &  kernel_h // 2 < input_h - 1
-kernel_w > input_w &  kernel_w // 2 < input_w - 1

**Describe the expected behavior**
Following cases can have right calculation results.
-kernel_h > input_h &  kernel_h // 2 < input_h - 1
-kernel_w > input_w &  kernel_w // 2 < input_w - 1

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops

def test_tf_avg_pool_grad(input_shape, grad_shape, ksize, strides, padding, data_format):
    x = tf.Variable(tf.ones(shape=grad_shape), dtype=tf.float32)
    avg_pool_grad = gen_nn_ops.avg_pool_grad(orig_input_shape=input_shape,
                                             grad=x, ksize=ksize,
                                             strides=strides,
                                             padding=padding,
                                             data_format=data_format)

    return avg_pool_grad

if __name__ == '__main__':
    grad_shape = (1, 1, 5, 1)
    input_shape = (1, 1, 5, 1)
    kernel_size = [1, 1, 7, 1]
    stride_size = [1, 1, 1, 1]
    padding = 'SAME'
    exp_result = test_tf_avg_pool_grad(input_shape, grad_shape,
                                       kernel_size, stride_size, padding,
                                       'NHWC')
    print("======================= the expect result of log:", exp_result)
```

**Other info / logs** 
hand-caculated process
![image](https://user-images.githubusercontent.com/72602911/116206344-45da2780-a771-11eb-8a56-dd37b902b244.png)

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in Tf version 2.4 and Nightly. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/a1c1cb7bda2d7ef7beac7525df1cf529/48773.ipynb).

**Comment by kkimdev** [comment]
Thanks for reporting! Contribution welcome!

**Comment by pointhex** [comment]
I am working on that.

**Comment by pointhex** [comment]
Hi @kkimdev,
Could you please help me who I can ask about some parameters of this function and how I can do that?
XlaOp AvgPoolGrad(XlaOp out_backprop, absl::Span<const int64> gradients_size,
                  absl::Span<const int64> kernel_size,
                  absl::Span<const int64> stride,
                  absl::Span<const std::pair<int64, int64>> spatial_padding,
                  const TensorFormat& data_format,
                  const bool counts_include_padding) {

**Comment by sanjoy** [comment]
@smit-hinsu maybe?

**Comment by smit-hinsu** [comment]
Thanks Sanjoy.

@pointhex Happy to answer any questions you have for AvgPoolGrad helper function.

**Comment by pointhex** [comment]
Hi @smit-hinsu,

I'm trying to write a unit test for AvgPoolGrad. But I can do the right data format. In file pooling_test.cc there is a function MakeNCHWFormat. I need the same but for NHWC. I don't fully understand how spatial_dimensions works in this case.
Could you please clarify that for me? Or maybe there are some useful links.

**Comment by smit-hinsu** [comment]
Look at XlaTensorFormat helper in the following file that converts from the tensorflow format to the XLA format.
third_party/tensorflow/compiler/tf2xla/kernels/pooling_ops.cc

For 4D tensor in NCHW format, spatial_dimensions are 2 and 3 as the last two dimensions are spatial dimensions. It would be 1 and 2 for NHWC format.

**Comment by kumariko** [comment]
Was able to reproduce the issue in Tf version 2.6 . Please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/f8ea671f657c84f914effdd2c87f8da5/48773.ipynb#scrollTo=9SGXZXynTP4Y).

**Comment by tilakrayal** [comment]
@hmzzl,
I tried to execute the mentioned above code on the tensorflow v2.14 and observed that the results are almost nearer to the handmade calculations. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/197181f09a9b35845eccf8b1a9389e9e/untitled1500.ipynb). 

```
======================= the expect result of log: tf.Tensor(
[[[[0.84999996]
   [1.0999999 ]
   [1.0999999 ]
   [1.0999999 ]
   [0.85      ]]]], shape=(1, 1, 5, 1), dtype=float32)
```
