### ISSUE TITLE
After installing cudatoolkit 10.1, cudnn 7.6.5 & tf 2.3.0, I still can´t see my GPU device.

### ISSUE THREAD

**Issue by epiedadjr** [tensorflow/tensorflow#48777]
**System information**
OS Platform and Distribution: Win10 x64
TensorFlow installed from (source or binary): binary
TensorFlow version: 2.3.0
Python version: 3.8.5
Installed using conda
CUDA toolkit/cuDNN version: 10.1 / 7.6.5
GPU model and memory: GTX1650 Ti

**Describe the problem**
I have installed the above version of packages plus jupyter notebook in Miniconda. 
![image](https://user-images.githubusercontent.com/9957900/116236369-4669c280-a75f-11eb-8ed1-b016dfdb219a.png)

![image](https://user-images.githubusercontent.com/9957900/116236390-4ec1fd80-a75f-11eb-9bce-6bc711392255.png)

![image](https://user-images.githubusercontent.com/9957900/116236422-584b6580-a75f-11eb-88a1-5bd6d6371435.png)

![image](https://user-images.githubusercontent.com/9957900/116236453-600b0a00-a75f-11eb-8a5c-88f521b6e1d7.png)

I still can´t see my GPU device after running the code.
![image](https://user-images.githubusercontent.com/9957900/116236592-87fa6d80-a75f-11eb-870f-2527ab50758b.png)

**Execution**
 
I have checked the compatibility of the versions and followed exactly the installation process.

I can verify my CUDA installation from my cmd prompt using `nvcc --version`. 
![image](https://user-images.githubusercontent.com/9957900/116233269-60a1a180-a75b-11eb-99af-f24ab6733244.png)

I have added the paths in my environment variable:
![image](https://user-images.githubusercontent.com/9957900/116233360-7911bc00-a75b-11eb-98eb-3b5f622af955.png)

I have rebooted before running the notebook and found no GPU running.

**Comment by saikumarchalla** [comment]
@epiedadjr  Could you please check whether are you facing the same issue outside the conda environment and let us know. Thanks!

**Comment by saikumarchalla** [comment]
@epiedadjr  Good to hear that the issue is resolved and that's the reason I asked you to check outside conda environment.Thanks!
