### ISSUE TITLE
restoring checkpoint from 2.3 fails on TPU version 2.4.0 

### ISSUE THREAD

**Issue by joannayoo0117** [tensorflow/tensorflow#48781]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.x

**Describe the current behavior**
We have a checkpoint that is trained using tpu with tf 2.3. We recently upgraded to 2.4.0 and tried restoring the checkpoint using tpu. We get some internal error from tpu.

**Describe the expected behavior**
We expect that the older checkpoints could be restored without any errors. 

**Standalone code to reproduce the issue**
*Will soon provide checkpoint and code example*

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![tf2 4_bug](https://user-images.githubusercontent.com/40743476/116276513-9b530c00-a752-11eb-93e7-5c6412f9ef46.png)
<img width="1576" alt="screen_shot 2021-04-27 at 12 16 40" src="https://user-images.githubusercontent.com/40743476/116276559-a27a1a00-a752-11eb-8308-f32e88cf53f3.png">
<img width="1678" alt="screen_shot 2021-04-27 at 12 17 09" src="https://user-images.githubusercontent.com/40743476/116276832-e4a35b80-a752-11eb-87df-fb8667aeaf7a.png">

**Comment by saikumarchalla** [comment]
@joannayoo0117  With out the Minimal code snippet, it will be difficult for us to debug the issue at our end. Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks
