### ISSUE TITLE
Help: Using Demo application of tflite java, how to run three different models on CPU, GPU and DSP in parallel 

### ISSUE THREAD

**Issue by nagbattula8** [tensorflow/tensorflow#48783]
System information

Have I written custom code: Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 8.1.0 
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MI 8 Pro with Qualcomm Snapdragon 845

Describe the problem

Qualcomm Snapdragon 845 contains three hardware devices named CPU, GPU and DSP. I am implementing the demo tflite Android application on the Mi 8 pro mobile phone based on https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java/demo. I am trying to write a code such that three different classifier instances execute in parallel on CPU, GPU and DSP simultaneously.

`  
private void startBackgroundThread() {
    backgroundThread = new HandlerThread(HANDLE_THREAD_NAME);
    backgroundThread.start();
    backgroundHandler = new Handler(backgroundThread.getLooper());
    
    for ( int i = 0; i < 200; i++) {
       
     TimeUnit.MILLISECONDS.sleep(1);

    backgroundHandler.post(periodicClassify);
    backgroundHandler.post(periodicClassify2);
    backgroundHandler.post(periodicClassify3);

    }

    updateActiveModel(); //initializes classifier1 on CPU, classifier2 on GPU, classifier3 on DSP
  }

  private Runnable periodicClassify =
      new Runnable() {
        @Override
        public void run() {
            if (runClassifier) {
              classifyFrame(classifier1,1);

            }
        }
      };

  private Runnable periodicClassify2 =
      new Runnable() {
        @Override
        public void run() {
            if (runClassifier) {
              classifyFrame(classifier2,4);

            }
        }
      };

  private Runnable periodicClassify3 =
      new Runnable() {
        @Override
        public void run() {
            if (runClassifier) {
              classifyFrame(classifier3, 3);

            }
        }
      };

  private void classifyFrame(ImageClassifier classifierNow, int batchSize) {
    if (classifier == null || getActivity() == null || cameraDevice == null) {
      // It's important to not call showToast every frame, or else the app will starve and
      // hang. updateActiveModel() already puts an error message up with showToast.
      // showToast("Uninitialized Classifier or invalid context.");
      return;
    }
    SpannableStringBuilder textToShow = new SpannableStringBuilder();
    Bitmap bitmap = textureView.getBitmap(classifier.getImageSizeX(), classifier.getImageSizeY());
    classifierNow.classifyFrame(bitmap, textToShow, batchSize); // Execute classifierNow with a batch size.
    bitmap.recycle();
    showToast(textToShow);
  }

`

With this code, I am able to successfully run the classifier1, classifier2, classifier3 on CPU, GPU and DSP respectively. However, the execution is not happening in parallel. i.e. classifier2 starts executing on GPU only after classifier1 is finished. Similarly classifier3 starts executing only after classifier2 is done.

To solve this I have written my startBackgroundThread function by creating different threads in this way:

`
private void startBackgroundThread() {
    backgroundThread = new HandlerThread(HANDLE_THREAD_NAME);
    backgroundThread.start();
    backgroundHandler = new Handler(backgroundThread.getLooper());

    backgroundThread2 = new HandlerThread(HANDLE_THREAD_NAME2);
    backgroundThread2.start();
    backgroundHandler2 = new Handler(backgroundThread2.getLooper());

    backgroundThread3 = new HandlerThread(HANDLE_THREAD_NAME3);
    backgroundThread3.start();
    backgroundHandler3 = new Handler(backgroundThread3.getLooper());
    
    
    for ( int i = 0; i < 200; i++) {
       
     TimeUnit.MILLISECONDS.sleep(1);

    backgroundHandler.post(periodicClassify);
    backgroundHandler2.post(periodicClassify2);
    backgroundHandler3.post(periodicClassify3);

    }

    updateActiveModel(); //initializes classifier1 on CPU, classifier2 on GPU, classifier3 on DSP
  }

`

This code creates new problems. If I implement this code, then I have no control over which thread executes at which time (race condition). Mostly the batch sizes are getting mixed up and the application crashes because of it.

My runInference function looks like this:

`    protected void runInference2(int tentativeBatchSize) {
         labelProbArray = new byte[tentativeBatchSize][getNumLabels()];

        Tensor t1 = tflite.getInputTensor(0);

        int[] dims = t1.shape();

        for ( int dim : dims ){
            System.out.println("Dimension " + dim + getModelPath());
        }

        long startModel = SystemClock.uptimeMillis();

        int[] timings2 = new int[] {tentativeBatchSize,224,224,3};

        tflite.resizeInput(0,timings2);

        for ( int dim : dims ){
            System.out.println("Dimension " + dim + getModelPath());
        }

        long endModel = SystemClock.uptimeMillis();

        System.out.println("Resize time " + (endModel-startModel));

        tflite.run(imgData, labelProbArray);
    }
`

Some one please help me with a fix in such a way that I can execute classifiers on CPU, GPU and DSP in parallel.

Thank you.

**Comment by abattery** [comment]
@srjoglekar246 could you triage this issue?

**Comment by srjoglekar246** [comment]
Are all three 'classifiers' different instances of [ImageClassifier](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/demo/app/src/main/java/com/example/android/tflitecamerademo/ImageClassifier.java#L48)? Note that TFLite Interpreters are not thread-safe, so using one from multiple threads will cause issues.

**Comment by nagbattula8** [comment]
Yes. To be precise, 'classifier' instance of ImageClassifier runs nasnet_mobile.tflite. 'classifier2' takes care of mobilenet_v1_0.25_224.tflite. classifier3 runs the inference for  inception_v1_224_quant.tflite. All these are from the Hosted models page https://www.tensorflow.org/lite/guide/hosted_models.

**Comment by srjoglekar246** [comment]
I am not sure what is going on here. The code samples you posted aren't very clear on why the classifiers would run serially if they are in different threads. This might be an Android thing, because of the memory required by the interpreters?

Adding @lintian06 who might have some insight.

**Comment by nagbattula8** [comment]
This code is making the threads in serial fashion. ( Here it is understandable because I am using only one thread ).

`
        private void startBackgroundThread() {
        backgroundThread = new HandlerThread(HANDLE_THREAD_NAME);
        backgroundThread.start();
        backgroundHandler = new Handler(backgroundThread.getLooper());
        
        for ( int i = 0; i < 200; i++) {
           
         TimeUnit.MILLISECONDS.sleep(1);
        
        backgroundHandler.post(periodicClassify);
        backgroundHandler.post(periodicClassify2);
        backgroundHandler.post(periodicClassify3);
        
        
        
        }
        
        
        
        updateActiveModel(); //initializes classifier1 on CPU, classifier2 on GPU, classifier3 on DSP
        }


`

However, if I use the code below which has different threads, then the application is crashing because the batch size of one thread's interpreter is getting mixed with the batch size of another thread's interpreter.

`

        private void startBackgroundThread() {
        backgroundThread = new HandlerThread(HANDLE_THREAD_NAME);
        backgroundThread.start();
        backgroundHandler = new Handler(backgroundThread.getLooper());
        
        backgroundThread2 = new HandlerThread(HANDLE_THREAD_NAME2);
        backgroundThread2.start();
        backgroundHandler2 = new Handler(backgroundThread2.getLooper());
        
        backgroundThread3 = new HandlerThread(HANDLE_THREAD_NAME3);
        backgroundThread3.start();
        backgroundHandler3 = new Handler(backgroundThread3.getLooper());
        
        
        for ( int i = 0; i < 200; i++) {
           
         TimeUnit.MILLISECONDS.sleep(1);
        
        backgroundHandler.post(periodicClassify);
        backgroundHandler2.post(periodicClassify2);
        backgroundHandler3.post(periodicClassify3);
        
        
        
        }
        
        
        
        updateActiveModel(); //initializes classifier1 on CPU, classifier2 on GPU, classifier3 on DSP
        }

`

This is the error if I implement the above code:

E/AndroidRuntime: FATAL EXCEPTION: CameraBackground3
    Process: android.example.com.tflitecamerademo, PID: 18540
    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input) with 602112 bytes from a Java Buffer with 451584 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:423)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:304)
        at com.example.android.tflitecamerademo.ImageClassifierInceptionV1Quant.runInference2(ImageClassifierInceptionV1Quant.java:132)
        at com.example.android.tflitecamerademo.ImageClassifier.classifyFrame(ImageClassifier.java:198)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.classifyFrame2(Camera2BasicFragment.java:4893)
        at com.example.android.tflitecamerademo.Camera2BasicFragment.access$2000(Camera2BasicFragment.java:101)
        at com.example.android.tflitecamerademo.Camera2BasicFragment$24.run(Camera2BasicFragment.java:3189)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

As you can see, in the thread which executes inception v1, the batch size isn't being updated. This is the issue I am facing if I use multiple threads.

**Comment by srjoglekar246** [comment]
Where do you update the batch size? There is some element of your code that isn't thread safe, and it might be somewhere in `ImageClassifierInceptionV1Quant` (and the other classes like that).

**Comment by nagbattula8** [comment]
This is the classifyFrame method I used in the ImageClassifier class. 

```
  void classifyFrame(Bitmap bitmap, SpannableStringBuilder builder, int batchSize) {
    if (tflite == null) {
      Log.e(TAG, "Image classifier has not been initialized; Skipped.");
      builder.append(new SpannableString("Uninitialized Classifier."));
    }

    tentative_batch_size = batchSize;

    imgData =
            ByteBuffer.allocateDirect(
                    tentative_batch_size
                            * 224
                            * 224
                            * 3
                            * getNumBytesPerChannel());


    imgData.order(ByteOrder.nativeOrder());

    String model_name = getModelPath();


    convertBitmapToByteBuffer(bitmap);
    // Here's where the magic happens!!!
    long startTime = SystemClock.uptimeMillis();
    runInference2(tentative_batch_size);
    long endTime = SystemClock.uptimeMillis();


    Log.d(TAG, "Timecost to run model inference: " + " " + model_name + " " + Long.toString(endTime - startTime));





    // Smooth the results across frames.
    applyFilter();

    // Print the results.
    long labelStartTime = SystemClock.uptimeMillis();
    printTopKLabels(builder);
    long duration = endTime - startTime;
    SpannableString span = new SpannableString(model_name + "  " + duration + " ms");
    span.setSpan(new ForegroundColorSpan(android.graphics.Color.LTGRAY), 0, span.length(), 0);
    builder.append(span);
    long labelEndTime = SystemClock.uptimeMillis();

    timeCostToPutLabel = labelEndTime - labelStartTime;


    Log.d(TAG, "Timecost to put labels: " + model_name + "    " + Long.toString(timeCostToPutLabel));

  }
```

I use this runInference method in ImageClassifierInceptionV1Quant class

```
    protected void runInference2(int tentative) {
         labelProbArray = new byte[tentative][getNumLabels()];


        long startModel = SystemClock.uptimeMillis();


        int[] timings2 = new int[] {tentative,224,224,3};

        tflite.resizeInput(0,timings2);

        tflite.run(imgData, labelProbArray);
    }
```
Do you think this is the code in classifyFrame method of ImageClassifier class that is not thread safe?

```
    imgData =
            ByteBuffer.allocateDirect(
                    tentative_batch_size
                            * 224
                            * 224
                            * 3
                            * getNumBytesPerChannel());
```

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
