### ISSUE TITLE
Example of tf.scatter_nd contains Session, which is obselete

### ISSUE THREAD

**Issue by worldpeaceaspirer** [tensorflow/tensorflow#48796]
## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/scatter_nd

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/scatter_nd

## Description of issue (what needs changing):
The Code, 

```python
with tf.Session() as sess:
      print(sess.run(scatter))
```
should be replaced with `print(scatter)`, as the **`Sessions`** are no longer required in **`Tensorflow 2.x`**.

### Correct links

Is the link to the source code correct? : NA

### Parameters defined

Are all parameters defined and formatted correctly? : Yes

### Returns defined

Are return values defined? : Yes

### Raises listed and defined

Are the errors defined? No

### Usage example

Is there a usage example? : Yes

**Comment by rmothukuru** [comment]
@worldpeaceaspirer,
Thank you for identifying it. This should be fixed with [this CL](https://critique-ng.corp.google.com/cl/370902959).

**Comment by ymodak** [comment]
This is fixed with latest TF api docs https://www.tensorflow.org/api_docs/python/tf/scatter_nd
Thanks!
