### ISSUE TITLE
Importing torchvision before tensorflow causes protobuf error.

### ISSUE THREAD

**Issue by YodaEmbedding** [tensorflow/tensorflow#48797]
**System information**
<details>
<summary>System information</summary>

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary? (package: `tensorflow-cuda` from official Arch repos)
- TensorFlow version (use command below): unknown 2.4.1
- Python version: 3.9.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA=11.3.0, cuDNN=8.1.1.33
- GPU model and memory: NVIDIA GeForce GTX 1060 6GB

</details>

**Describe the current behavior**

```python
import torchvision
import tensorflow
```

causes:

```python
  File "/usr/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 141, in <module>
    ResourceHandleProto = _reflection.GeneratedProtocolMessageType('ResourceHandleProto', (_message.Message,), {
SystemError: google/protobuf/pyext/descriptor.cc:354: bad argument to internal function
```

However,

```python
import tensorflow
import torchvision
```

...causes no such error.

**Describe the expected behavior**

No error.

**Standalone code to reproduce the issue**

```python
import torchvision
import tensorflow
```

**Other info / logs**

<details>
<summary>Traceback</summary>

```python
Traceback (most recent call last):
  File "/home/mulhaq/tmp.py", line 2, in <module>
    import tensorflow
  File "/usr/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/usr/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/lib/python3.9/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/lib/python3.9/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/lib/python3.9/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 141, in <module>
    ResourceHandleProto = _reflection.GeneratedProtocolMessageType('ResourceHandleProto', (_message.Message,), {
SystemError: google/protobuf/pyext/descriptor.cc:354: bad argument to internal function
```

</details>

Other users with similar issue: https://stackoverflow.com/questions/65874607/torchvision-and-tensorflow-gpu-import-error

**Comment by bhack** [comment]
Can you try to reporduce this with:

```
pip install tf-nightly-cpu
pip install --upgrade torchvision
```

**Comment by saikumarchalla** [comment]
@YodaEmbedding  I tried to import  in both ways using TF version 2.4.1 on colab and didn't face any protobuf errors. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/b1942aff2b53f239d4124def9e45d45e/48797.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
@YodaEmbedding  Any update on this?. Please feel free to close the issue if the issue was resolved already. Thanks!

**Comment by YodaEmbedding** [comment]
Reinstalling `torchvision` seems to fix the issue. Not sure what was causing it.

**Comment by kennedyCzar** [comment]
Calling tensorflow first (import tensorflow as tf) and all other dependencies before calling torch seems to solve the problem for me.

**Comment by YodaEmbedding** [comment]
Yes, the fix is:

```python
import tensorflow  # BEFORE all other imports

import torchvision
```

**Note:** I still have this issue on newer versions of packages on Arch Linux. The fix is either to reinstall `torchvision` or to always import `tensorflow` first, as shown above. Should I reopen since the issue isn't *technically* resolved (I have merely found consistent workarounds)?

**Comment by bhack** [comment]
I think you can open a ticket on arch in the meantime.
