### ISSUE TITLE
Tensorflow 2.3 or up Installation on Mac OS Big Sur 11.3

### ISSUE THREAD

**Issue by o0stsou0o** [tensorflow/tensorflow#48808]
Hi,

I am trying to install tensorflow 2.3 or up on Mac OS Big Sur 11.3.  I'm trying to do it in a conda environment with python 3.7.  This is a cpu install.  

When I try pip install tensorflow, and go into a python terminal and import, it says that the module does not exist.  
When I conda install tensorflow in the conda environment and go into a python terminal and import, I can only get tensorflow 2.0.0.  
When I try conda install -c conda-forge tensorflow and go into a python terminal and import tensorflow, I get a slew of warnings of signed and unsigned types:
/Users/blah/anaconda3/envs/funkmuffin2/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: 
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/blah/anaconda3/envs/funkmuffin2/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: 
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
.....
/Users/blah/anaconda3/envs/funkmuffin2/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
.... and when I conda update -f -c conda-forge tensorflow, I get the same warnings and I still only get tensorflow 1.14.

Would you know why I cannot simply get tensorflow 2.3 or higher installed?  and/or would anybody know how to do so?  Thank you.

**Comment by moflo** [comment]
Saw something similar. Are you on an M1 Mac?

**Comment by o0stsou0o** [comment]
Thanks for the speedy reply.  No.  It's Intel Core i7.  


> Saw something similar. Are you on an M1 Mac?

**Comment by Saduf2019** [comment]
@o0stsou0o 
What is the numpy version on your system, there seems to be compatibility issues with your tensorflow and numpy.

Can you try: pip install   tensorflow 2.4.1 with numpy  1.19.x and let us know. [ypu may refer to [this comment](https://github.com/tensorflow/tensorflow/issues/47878#issuecomment-802602008), [link](https://stackoverflow.com/questions/57381430/synonym-of-type-is-deprecated-in-a-future-version-of-numpy-it-will-be-underst),#30427,#31249]
