### ISSUE TITLE
Distillation and multi-gpu training with tf.keras

### ISSUE THREAD

**Issue by Bonsen** [tensorflow/tensorflow#48817]
I use https://github.com/keras-team/keras-io/blob/master/examples/vision/knowledge_distillation.py and single gpu everything is right.

When I use https://keras.io/guides/distributed_training/#singlehost-multidevice-synchronous-training and knowledge_distillation, the val_loss will become very big and the acc is very low.

If I only use distributed_training to train, everything is right too.

When I define test_step and train_step in class Distiller(keras.Model), should I use https://tensorflow.google.cn/guide/distributed_training#using_tfdistributestrategy_with_custom_training_loops?

**Comment by bhack** [comment]
As this is a specific  Keras.io guide I suggest you to open a ticket on https://github.com/keras-team/keras-io to check if they are interested to expand that example.

**Comment by jvishnuvardhan** [comment]
@bhack Looks like `keras` was imported from `tensorflow` (in both the examples). I guess you can use https://tensorflow.google.cn/guide/distributed_training#using_tfdistributestrategy_with_custom_training_loops to define `train_step` and `test_step`.

@nikitamaia Can you please take a loot at it. Thanks!

**Comment by bhack** [comment]
> @bhack Looks like `keras` was imported from `tensorflow` (in both the examples). I guess you can use https://tensorflow.google.cn/guide/distributed_training#using_tfdistributestrategy_with_custom_training_loops to define `train_step` and `test_step`.
> 
> @nikitamaia Can you please take a loot at it. Thanks!

Yes the new keras doc hosted there is always related to Keras in TF namespace but It Is a distinct repository

**Comment by Bonsen** [comment]
@bhack @jvishnuvardhan Thanks! I will try it soon.
