### ISSUE TITLE
TFDS link broken for Cars196

### ISSUE THREAD

**Issue by calvuser** [tensorflow/tensorflow#48818]
Trying to download Cars196 using tflite_model_maker

train_data, validation_data, test_data = ImageClassifierDataLoader.from_tfds('cars196')

DownloadError: Failed to get url https://imagenet.stanford.edu/internal/car196/cars_test.tgz. HTTP code: 404.

It was working previously, How to resolve?

**Comment by AdityaKane2001** [comment]
@calvuser 
This issue is better suited for [tensorflow/datasets](https://github.com/tensorflow/datasets). Thanks

**Comment by UsharaniPagadala** [comment]
@calvuser 
Could you please check the [link1](https://www.tensorflow.org/datasets/catalog/cars196) [,link2](https://ai.stanford.edu/~jkrause/cars/car_dataset.html) , and let us know if it helps.Thanks

**Comment by UsharaniPagadala** [comment]
@calvuser 
Could you please let us know if the above mentioned [comment](https://github.com/tensorflow/datasets) works for you as
The host website (stanford.edu) has ceased hosting the dataset which is parsed by tfds.load thus you see the error. Thanks

**Comment by calvuser** [comment]
Hi, I understand it has been fix on tfds.load.

I am downloading it on TF model maker. train_data, validation_data, test_data = ImageClassifierDataLoader.from_tfds('cars196')

seems like the link in TF model maker have to be fix as well
