### ISSUE TITLE
Convert Tensorflow trained model to older version compatible.

### ISSUE THREAD

**Issue by resera** [tensorflow/tensorflow#48820]
I want to make an object detection API. I decided to deploy it on AWS Lambda. For that purpose I used this git repository https://github.com/mikylucky/lambda-tensorflow-object-detection

As you can see it uses tensorflow 1.9 version. Unfortunately, I trained my model and exported inference graph with tensorflow 1.12 and when I try to run inference on AWS lambda with this script:

```
import os
import glob
import boto3
import numpy as np
import tensorflow as tf
import PIL
import matplotlib
import sys
from distutils.version import StrictVersion
from PIL import Image
from utils import ops as utils_ops
from matplotlib import pyplot as plt

# Object detection imports
from utils import label_map_util
from utils import visualization_utils as vis_util
import json

# Download Model From S3.
MODEL_GRAPH_DEF_PATH = '/tmp/model.pb'
BUCKET_NAME = 'solver'

def lambda_handler(event, context):
  s3 = boto3.resource('s3')
  print(event['queryStringParameters'])
  img_url = 'images/' + event['queryStringParameters']['image_name']
  model_path = 'models/' + event['queryStringParameters']['model_name'] + '.pb'
  print("DOWNLOADING MODEL " + model_path)
  s3.Bucket(BUCKET_NAME).download_file(model_path,MODEL_GRAPH_DEF_PATH)
  print("DOWNLOADING IMAGE " + img_url)
  s3.Bucket(BUCKET_NAME).download_file(img_url,'/tmp/image.jpg')
  label_path = 'models/' + event['queryStringParameters']['model_name'] + '.pbtxt'
  print("DOWNLOADING LABEL MAP " + label_path)
  s3.Bucket(BUCKET_NAME).download_file(label_path,'/tmp/label_map.pbtxt')
  print(glob.glob("/tmp/*"))
  detect()

def detect():
  PATH_TO_CKPT = '/tmp/model.pb'
  PATH_TO_IMAGE = '/tmp//image.jpg'
  NUM_CLASSES = 1
  label_map = label_map_util.load_labelmap('/tmp/label_map.pbtxt')
  categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
  category_index = label_map_util.create_category_index(categories)

  detection_graph = tf.Graph()
  with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

    sess = tf.Session(graph=detection_graph)

  # Define input and output tensors (i.e. data) for the object detection classifier

  # Input tensor is the image
  image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')

  # Output tensors are the detection boxes, scores, and classes
  # Each box represents a part of the image where a particular object was detected
  detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')

  # Each score represents level of confidence for each of the objects.
  # The score is shown on the result image, together with the class label.
  detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
  detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')

  # Number of objects detected
  num_detections = detection_graph.get_tensor_by_name('num_detections:0')
 
  print("SOMETHING WAS LOADED")
  print(num_detections)
```

I get an error like this: 

> NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, Truncate=false](image_tensor). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).: ValueError
> Traceback (most recent call last):
>   File "/var/task/lambda_function.py", line 36, in lambda_handler
>     detect()
>   File "/var/task/lambda_function.py", line 52, in detect
>     tf.import_graph_def(od_graph_def, name='')
>   File "/var/task/tensorflow/python/util/deprecation.py", line 432, in new_func
>     return func(*args, **kwargs)
>   File "/var/task/tensorflow/python/framework/importer.py", line 422, in import_graph_def
>     raise ValueError(str(e))
> ValueError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, Truncate=false](image_tensor). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

I read that it is because of tensorflow version difference between runtime environment and the one I trained model on. Sadly I cannot update tensorflow version on lambda to 1.12 to make it work, cause lambda has 200mb limit of function code, and this repository Im using is specially made to fit this requirement. Retraining models on 1.9 is not an option too, cause it would take a lot of time, and due to CUDA requirements I'm not even sure at the moment if my computer would be suitable for this.

I wonder if there is a way to somehow convert .pb file to match 1.9 tensorflow version and to make it work?

**Comment by UsharaniPagadala** [comment]
@resera 
Could you please have a look on [this,](https://www.tensorflow.org/guide/versions#backward_and_partial_forward_compatibility) and let us know if it helps

**Comment by bhack** [comment]
We don't support TF 1.x anymore. 
If you want to use modern TF version with AWS lambda check https://aws.amazon.com/it/blogs/compute/building-deep-learning-inference-with-aws-lambda-and-amazon-efs/

**Comment by resera** [comment]
> @resera
> Could you please have a look on [this,](https://www.tensorflow.org/guide/versions#backward_and_partial_forward_compatibility) and let us know if it helps

Hello, thanks for a suggestion. After saving a model with 

> strip_default_attrs=True

It now gives me a different error while running the object detection, it looks like this:

`Error parsing message: DecodeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 36, in lambda_handler
    detect()
  File "/var/task/lambda_function.py", line 51, in detect
    od_graph_def.ParseFromString(serialized_graph)
google.protobuf.message.DecodeError: Error parsing message`

is something wrong with my exported graph? I used this code:

`# Minimal code to successfully export tf model
import time
import os
import tensorflow as tf
trained_checkpoint_prefix = './training/model.ckpt-13605'
export_dir = os.path.join('trained-inference-graphs', time.strftime("%Y%m%d-%H%M%S"))
loaded_graph = tf.Graph()
with tf.Session(graph=loaded_graph) as sess:
    # Restore from checkpoint
    loader = tf.train.import_meta_graph(trained_checkpoint_prefix + '.meta')
    loader.restore(sess, trained_checkpoint_prefix)
    
    # Export checkpoint to SavedModel
    builder = tf.saved_model.builder.SavedModelBuilder(export_dir)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.tag_constants.TRAINING],
                                         strip_default_attrs=True)
    builder.add_meta_graph([tf.saved_model.tag_constants.SERVING], strip_default_attrs=True)
    builder.save()`

**Comment by sachinprasadhs** [comment]
@resera, We no longer support TF 1.x issues, you can go ahead and close this issue. Thanks!
