### ISSUE TITLE
make -f error

### ISSUE THREAD

**Issue by coffice12** [tensorflow/tensorflow#48828]
maos 11.3
Python 3.9.4
esp-idf4.2

error：

cafe@CafedeiMac tensorflow % make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32_default/prj/hello_world/esp-idf/components/tfmicro/third_party/gemmlowp/fixedpoint/fixedpoint.h', needed by 'generate_hello_world_esp_project'.  Stop.

**Comment by UsharaniPagadala** [comment]
@coffice12 

Could you please fill the template

In order to expedite the trouble-shooting process, please provide a code snippet/colab gist to reproduce the issue reported here. Thanks!
