### ISSUE TITLE
LSTM and GRU layers do not use cuDNN acceleration when processing RaggedTensors

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#48838]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian stable
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 / 8.0 (the ones on Colab were used)
- GPU model and memory: Colab

**Describe the current behavior**

When LSTM/GRU layers are executed on RaggedTensors, they do not use cuDNN acceleration on GPU and are much slower. The attached Colab notebook shows more than 5-times slowdown compared to manual conversion before/after the call.

**Describe the expected behavior**

The LSTM/GRU layers executed on RaggedTensors should use cuDNN acceleration on GPU.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1eR3ggwp-5sNKQjJld7XiTjet3BT740F1?usp=sharing

Note that when converting the RaggedTensors before/after the RNN call manually like this:
```python
outputs = rnn(inputs.to_tensor(), mask=tf.sequence_mask(inputs.row_lengths()))
outputs = tf.RaggedTensor.from_tensor(outputs, inputs.row_lengths())
```
allows using cuDNN implementation.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The problem is described directly in the sources: GRU here: https://github.com/tensorflow/tensorflow/blob/9a2545aecc498e7a5e8bf5d63c47af59e1550111/tensorflow/python/keras/layers/recurrent_v2.py#L447-L449 and LSTM here: https://github.com/tensorflow/tensorflow/blob/9a2545aecc498e7a5e8bf5d63c47af59e1550111/tensorflow/python/keras/layers/recurrent_v2.py#L1165-L1167

Note that same code is still in current head: GRU here: https://github.com/tensorflow/tensorflow/blob/9000e360d95b9d2c3925672ba100579bd459ee30/tensorflow/python/keras/layers/recurrent_v2.py#L434-L436 LSTM here: https://github.com/tensorflow/tensorflow/blob/9000e360d95b9d2c3925672ba100579bd459ee30/tensorflow/python/keras/layers/recurrent_v2.py#L1161-L1163

**Comment by saikumarchalla** [comment]
@foxik  I can see there is a performance issue with TF version 2.4. When i tried to execute your code on Nightly version,  I didn't see any performance issue. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/d8cb1b310aa880a9dda1bbf56d34fc5c/raggedtensorlstm.ipynb).Thanks!

**Comment by foxik** [comment]
@saikumarchalla Please note that tf-nightly does not use GPU on Colab (it required too new CUDA), which you can verify by adding for example
```python
print(tf.config.get_visible_devices())
```
which shows
```
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
```

The issue is not fixed in nightly, as visible for example in the following source:
https://github.com/tensorflow/tensorflow/blob/baaa9b23f76e307eb9e1dd2773ee5956f677dccc/tensorflow/python/keras/layers/recurrent_v2.py#L434-L438
so please remove the `Fixed in Nightly` tag - thanks :-)

**Comment by sachinprasadhs** [comment]
As mentioned in the Ragged Tensors [document](https://www.tensorflow.org/guide/ragged_tensor#tensorflow_apis), if you use Ragged Tensors or `ragged=True` in your layer you would get a warning like `WARNING:tensorflow:Layer lstm will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU`

**Comment by foxik** [comment]
@sachinprasadhs Yes, that is true -- the warning is caused by the source snippets above, which are marked with `TODO(b/156447398)`, which I assume it is some internal bug tracking number.

The current code path converts the ragged tensors to dense tensors (inside the LSTM/GRU) anyway, but then it does not use the cuDNN path. But if the conversion is done manually outside (using the same functions), cuDNN implementation is used -- so it is definitely possible to take the cuDNN path even with RaggedTensors -- which is why I filed this issue.

**Comment by sachinprasadhs** [comment]
@foxik Yes, you are right, there is already a internal bug(b/156447398) created for the same issue, till the issue is fixed the cuDNN GPU is disabled for the ragged inputs to avoid the input shape error due to the error in conversion of ragged tensors to dense tensors.

**Comment by foxik** [comment]
@sachinprasadhs It seemed like the issue is being tracked internally, but I did not find any mention about the problem here, so I created this issue to make it publicly visible.

It is however surprising that performing the conversion manually outside of the LSTM/GRU layer works without any problems (while I really encountered an issue when I tried to remove the workaround in the sources)...

**Comment by sachinprasadhs** [comment]
Manually conversion works fine, but as I have mentioned above the issue seems to be with the RNN code converts the ragged tensor to dense tensor before feeding it to cuDNN kernel, so the error might be in the conversion code.

**Comment by foxik** [comment]
I created a pull request in the keras repository https://github.com/keras-team/keras/pull/15756 .

**Comment by sachinprasadhs** [comment]
Hi, Could you please move this issue to closed since the PR is successfully merged. Thanks!

**Comment by foxik** [comment]
Definitely, thanks for the remainder! Cheers.
