### ISSUE TITLE
Error when loading TensorFlow SavedModel with tag set 'serve': FileFactory 'local_file' not found.

### ISSUE THREAD

**Issue by jroakes** [tensorflow/tensorflow#48830]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Preinstalled
- TensorFlow version: 2.4.1
- Python version:  3.7.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version:  11.2  
- GPU model and memory: Tesla P100 16G

**Describe the problem**
I have created a sequence classification model using tfhub `small_bert/bert_en_uncased_L-6_H-512_A-8` preprocessor and `bert_en_uncased_preprocess/2` encoder.  I have provided the main components of the code below.  After saving the saved_model and uploading to Google Cloud Storage, I am following the documentation for instantiating a BigQuery ML model from the saved model but receiving the following error:

```
Executing query with job ID: d6223072-8b7c-4672-a450-5ec8a23e7351
Query executing: 8.99s
ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/adapt-ml/queries/d6223072-8b7c-4672-a450-5ec8a23e7351?maxResults=0&timeoutMs=400&location=US: Error when loading TensorFlow SavedModel with tag set 'serve': FileFactory 'local_file' not found. The application has not been linked against the '//file/localfile' library or InitGoogle() has not been called yet.
	 [[{{node text_file_init/InitializeTableFromTextFileV2}}]]

(job ID: d6223072-8b7c-4672-a450-5ec8a23e7351)

                              -----Query Job SQL Follows-----                               

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE MODEL `adapt-ml.bigquery_ml.sentiment`
   2:OPTIONS (MODEL_TYPE='TENSORFLOW',  MODEL_PATH='gs://adapt-ml-bucket/finetuned_model/*')
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
````
I am not sure if this is a TensorFlow, TFHub, or BigQuery error as I was unable to locate any similar issue in web searches or Github searches.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
COmmand steps follow linearly below.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Model Information:
```
def build_classifier_model(train_dataset):
  text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
  preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name='preprocessing', )
  encoder_inputs = preprocessing_layer(text_input)
  encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name='BERT_encoder')
  outputs = encoder(encoder_inputs)
  pooled = outputs['pooled_output']

  net = tf.keras.layers.Dense(
              HIDDEN_LAYER_DIMS,
              kernel_initializer=tf.keras.initializers.TruncatedNormal(stddev=0.002),
              activation="relu",
              name="pre_classifier"
          )(pooled)  
  
  net = tf.keras.layers.Dropout(DROPOUT, trainable=True)(net)
  net = tf.keras.layers.Dense(2, activation="sigmoid", name='classifier')(net)
  model = tf.keras.Model(text_input, net)

  loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

  epochs = EPOCHS
  steps_per_epoch = tf.data.experimental.cardinality(train_dataset).numpy()
  num_train_steps = steps_per_epoch * epochs
  num_warmup_steps = int(0.1*num_train_steps)

  optimizer = optimization.create_optimizer(init_lr=LEARNING_RATE,
                                            num_train_steps=num_train_steps,
                                            num_warmup_steps=num_warmup_steps,
                                            optimizer_type='adamw')

  model.compile(optimizer=optimizer,
                          loss=loss,
                          metrics=['accuracy'])
  
  model.summary()
  
  return model
```

Train Model:
```
model = build_classifier_model(train_dataset)

checkpoint = ModelCheckpoint(filepath=SAVE_MODEL_PATH, 
                             verbose=1,
                             save_freq='epoch',
                             monitor='val_accuracy',
                             save_best_only=True, 
                             mode='max', 
                             save_weights_only=True)


# Training model...
history = model.fit(train_dataset, batch_size=BATCH_SIZE, epochs=EPOCHS, callbacks=checkpoint, validation_data=valid_dataset)
```

Reload model and save as saved_model:
```
model = build_classifier_model(train_dataset)
model.load_weights(SAVE_MODEL_PATH)
#model.save('finetuned_model', include_optimizer=False, save_traces=False)
#model = tf.keras.models.load_model('finetuned_model')

!rm -r finetuned_model

tf.saved_model.save(
    model,
    'finetuned_model',
    signatures=None,
    options=None, 
)
```

Checking correct signature:
```
loaded = tf.saved_model.load('finetuned_model')
print(list(loaded.signatures.keys()))  # ["serving_default"]

infer = loaded.signatures["serving_default"]
print(infer.structured_input_signature)
print(infer.structured_outputs)
-------------------------------------------------
['serving_default']
((), {'text': TensorSpec(shape=(None,), dtype=tf.string, name='text')})
{'classifier': TensorSpec(shape=(None, 2), dtype=tf.float32, name='classifier')}
```

After copying to GS Bucket:
```
%%bigquery

CREATE OR REPLACE MODEL `adapt-ml.bigquery_ml.sentiment`
OPTIONS (MODEL_TYPE='TENSORFLOW',  MODEL_PATH='gs://adapt-ml-bucket/finetuned_model/*')
```

**Comment by tilakrayal** [comment]
@jroakes ,

In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by jroakes** [comment]
@tilakrayal sure.  Here is the cleaned-up Colab notebook with the full example. 
https://colab.research.google.com/drive/1w-E1gjRVV-Qpur9SHBWWFHJKIXhfM1JI?usp=sharing

**Comment by jroakes** [comment]
Hi @tilakrayal and @Saduf2019.  I was able to resolve the issue by using `https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3` instead of `https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2`. It appears there is an incorrect reference to `vocab.txt` in the prior versions of this Model.  It may be worth a more explicit notification on https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2 alerting to this issue.

https://github.com/tensorflow/hub/issues/719

**Comment by Saduf2019** [comment]
@jroakes 
I ran you code on tf 2.5 and the issue does not exist, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7888e9968856a077d1057835157e07c1/untitled598.ipynb)

**Comment by Saduf2019** [comment]
@jroakes 
Apologies for the delayed response, thank you for your update glad the issue is resolved.
