### ISSUE TITLE
CMake build option TFLITE_ENABLE_RUY=OFF does not work

### ISSUE THREAD

**Issue by steven-johnson** [tensorflow/tensorflow#48836]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary): source
TensorFlow version: 2.5.0-rc2
Python version: 3.6.8 (but probably n/a)
Installed using virtualenv? pip? conda?: n/a
Bazel version (if compiling from source): n/a
GCC/Compiler version (if compiling from source): Apple clang version 12.0.0
CUDA/cuDNN version: n/a
GPU model and memory: n/a

**Describe the problem**

Follow the instructions at https://www.tensorflow.org/lite/guide/build_cmake to build `libtensorflow-lite.a`, using the default value of TFLITE_ENABLE_RUY=OFF. Then use `nm` to look at the library and see that there are many uses of ruy (including undefined symbols) that make this library unusable.

From a casual inspection, it appear that there are lots of references to ruy in the source code (eg #includes in optimized_ops.h) that may not be easily removed; if ruy is truly required to build TFLite, there shouldn't be an option to disable it. (Alternately, if it's not required, the code should actually allow excluding it.)

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by terryheo** [comment]
Plz check https://github.com/tensorflow/tensorflow/issues/47862 for the detail.

**Comment by steven-johnson** [comment]
Thanks for the link. If current versions of TFLite really do require Ruy, that's fine and dandy, but it doesn't really make sense to offer an option that claims to disable Ruy but does not -- surely the option should be removed in that case?
