### ISSUE TITLE
Can't build TFL micro build with armclang toolchain

### ISSUE THREAD

**Issue by freddan80** [tensorflow/tensorflow#48839]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): N/A
- Tensorflow version (commit SHA if source): 9000e360d95b9d2c3925672ba100579bd459ee30
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Any target

**Describe the problem**
When using the armclang toolchain to build the microlite lib, the warning `implicit-const-int-float-conversion` is hit. Warnings are treated as errors, hence build fails.

**Please provide the exact sequence of commands/steps when you ran into the problem**
For example:
`make -j -f tensorflow/lite/micro/tools/make/Makefile OPTIMIZED_KERNEL_DIR=ethos_u TOOLCHAIN=armclang TARGET=cortex_m_generic TARGET_ARCH=cortex-m55 microlite
`

Output with error:
```
armclang -std=c11 -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter -DCORTEX_M_GENERIC -DETHOS_U --target=arm-arm-none-eabi -mcpu=cortex-m55 -DTF_LITE_MCU_DEBUG_LOG -mthumb -mfloat-abi=hard -funsigned-char -mlittle-endian -Wno-implicit-fallthrough -Wno-strict-aliasing -Wno-unused-variable -Wno-type-limits -Wno-unused-private-field -fomit-frame-pointer -MD -DCPU_M55=1 -D__DSP_PRESENT=1 -D__FPU_PRESENT=1 -I. -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/ethos_u_core_driver/include -Itensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include -c tensorflow/lite/micro/tools/make/downloads/ethos_u_core_driver/src/ethosu_driver.c -o tensorflow/lite/micro/tools/make/gen/cortex_m_generic_cortex-m55_default/obj/tensorflow/lite/micro/tools/make/downloads/ethos_u_core_driver/src/ethosu_driver.o
tensorflow/lite/kernels/kernel_util.cc:342:15: error: implicit conversion from 'std::numeric_limits<int>::type' (aka 'int') to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]
        tmp <= std::numeric_limits<int32_t>::max());
```

**Comment by rmothukuru** [comment]
@freddan80,
Thank you for submitting the fix. As the PR #48840 has been merged, can you please let us know if we can close this issue? 
Thanks!

**Comment by freddan80** [comment]
Absolutely, you can close it.
