### ISSUE TITLE
[For GShard] parameter instruction in HLO could not get sharding information from annotated VarHandleOp

### ISSUE THREAD

**Issue by wangsiyu** [tensorflow/tensorflow#48849]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): (2.6.0)master branch on 30, April
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: 11.2/8
- GPU model and memory: V100 32GB

**Describe the current behavior**
I write some codes with GShard API provided in ``` experimental/xla_sharding/xla_sharding.py ```.  As proposed in GShard paper, the annotation can marked anywhere when needed. But As I annotated the trainable variable, it seems no effect on HLO for `parameter` instruction.

For example, a trainable variable could be created from the following API.  The ```self.in_weights``` is ```VarHandleOp``` Type
```
 self.weight = tf.get_variable(name="weights",
                                      shape=shape,
                                      dtype=tf.float32,
                                      initializer=self.initializer)
```

And When I annotates like the following:

```    
 self.weight = xla_sharding.split(self.weight, 0, 2)
```

I have checked the annotation on ```NodeDef``` and make sure that the ```_XLA_Sharding``` Attribute has beed added on. But this important information is missing in HLO when entering the ``` GpuCompiler::OptimizeHloModule```.

To debug the missing information, I noticed the ```XlaCompiler::CompileGraph()``` function intent to get Sharding Attribute from ```NodeDef``` by ```ComputeArgAndRetvalShardings```.  The  source code of this function is as follows: 

```
// Uses the _Arg and _Retval nodes in the graph to determine an OpSharding for
// each argument and return value.
xla::StatusOr<
    std::pair<std::map<int, xla::OpSharding>, std::map<int, xla::OpSharding>>>
ComputeArgAndRetvalShardings(const Graph& graph) {
  auto get_sharding_for_node =
      [](const Node* n) -> xla::StatusOr<absl::optional<xla::OpSharding>> {
    TF_ASSIGN_OR_RETURN(
        auto sharding,
        ParseShardingFromDevice(*n, std::numeric_limits<int32>::max(),
                                /*add_metadata=*/false));
    return sharding;
  };
  std::map<int, xla::OpSharding> arg_shardings;
  std::map<int, xla::OpSharding> retval_shardings;
  for (const Node* n : graph.nodes()) {
    if (n->IsArg()) {
      TF_ASSIGN_OR_RETURN(auto sharding, get_sharding_for_node(n));
      if (!sharding.has_value()) continue;
      int index;
      TF_RETURN_IF_ERROR(GetNodeAttr(n->attrs(), "index", &index));
      TF_RET_CHECK(index >= 0) << "Negative _Arg index";
      arg_shardings[index] = std::move(*sharding);
    } else if (n->IsRetval()) {
      TF_ASSIGN_OR_RETURN(auto sharding, get_sharding_for_node(n));
      if (!sharding.has_value()) continue;
      int index;
      TF_RETURN_IF_ERROR(GetNodeAttr(n->attrs(), "index", &index));
      TF_RET_CHECK(index >= 0) << "Negative _Retval index";
      retval_shardings[index] = std::move(*sharding);
    }
  }
  return std::make_pair(std::move(arg_shardings), std::move(retval_shardings));
}
```

But here the ```Arg``` and ```RetVals``` belongs to ```Xla_Compile``` Op , not ```XlaRun``` Op. The indices acquired from ```arg_shardings``` are different from ```XlaRun```'s. And the ```BuildArguments``` function uses these indices to
decide sharding information for HLO, which leads to the hlo_sharding missing due to the mismatched indices for 
 ```input_to_args```.
```
    for (std::vector<int>::size_type i = 0; i < input_to_args->size(); ++i) {
      auto it = arg_shardings.find(i);
      xla::XlaScopedShardingAssignment assign_sharding(
          builder, it == arg_shardings.end() ? absl::optional<xla::OpSharding>()
                                             : it->second);
```

Is that the expected  behavior for ```parameter_instruction``` or a bug for TensorFlow GraphDef?

**Describe the expected behavior**
I think the ```arg_shardings``` of ```XlaCompile``` Op is meaningless for deciding ``` parameter```'s sharding information. These arguments indices should be referred to the inputs of ENTRY computation for hlo module. 

Can anyone help for solving this problem? @ukoxyz

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
