### ISSUE TITLE
Inconsistencies in micro_speech example

### ISSUE THREAD

**Issue by henriwoodcock** [tensorflow/tensorflow#48841]
This may be related to https://github.com/tensorflow/tensorflow/issues/48752. The `micro_speech` model is int8 quantized for both input and output. The test for the example has some lines with `data.int8` and `data.uint8` when querying the output data.

For example:

https://github.com/tensorflow/tensorflow/blob/173b50a525e0f88fa25674980f1243ada460114e/tensorflow/lite/micro/examples/micro_speech/micro_speech_test.cc#L103

and:

https://github.com/tensorflow/tensorflow/blob/173b50a525e0f88fa25674980f1243ada460114e/tensorflow/lite/micro/examples/micro_speech/micro_speech_test.cc#L105

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch
- Python version: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
TFLM example micro_speech has inconsistencies in the test file. It treats some outputs as `int8` and some as `uint8`.

**Describe the expected behavior**
Treat all outputs from the model as the same as they are all `int8`.

**Standalone code to reproduce the issue**
Affected lines can be seen above. Does not raise an error but it does not make sense.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@henriwoodcock 

Could you please fill the template and elaborate your Query with clear details. What is your error and what are the steps followed to reproduce it. Thanks

**Comment by henriwoodcock** [comment]
@UsharaniPagadala I've added the template

**Comment by UsharaniPagadala** [comment]
@henriwoodcock 
Apologize for the late reply.Could you please reopen the issue if it is still persist.Thanks
