### ISSUE TITLE
Is tensorflow going to support amd gpu with ROCm ？ 

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#48846]
**Describe the problem**
I notice that ```pytorch``` supports amd gpu with ROCm in version 1.8.1 ([https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/)) . I want to know whether ```tensorflow``` is going to support amd gpu or not ...

**Comment by moflo** [comment]
Isn't that a question for AMD?

**Comment by saikumarchalla** [comment]
@DachuanZhao  Currently, I think tensorflow-gpu library isn't built for AMD as it uses CUDA. To get Tensorflow to work on an AMD GPU,  one way this could work is to compile Tensorflow to use OpenCl.

 Please go through the community supported build section [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream#community-supported-builds)  and you will get more information on this. 

Also, Please go through this  SO [Link](https://stackoverflow.com/questions/37892784/using-keras-tensorflow-with-amd-gpu) for detailed information. Thanks!

**Comment by saikumarchalla** [comment]
@DachuanZhao Seems Tensorflow is now supporting AMD GPU with ROCM. Please go through this [document](https://medium.com/analytics-vidhya/install-tensorflow-2-for-amd-gpus-87e8d7aeb812) for Step by step installation. Thanks!

**Comment by DachuanZhao** [comment]
> @DachuanZhao Seems Tensorflow is now supporting AMD GPU with ROCM. Please go through this [document](https://medium.com/analytics-vidhya/install-tensorflow-2-for-amd-gpus-87e8d7aeb812) for Step by step installation. Thanks!

Why not add the installation to the [offical tensorflow document](https://www.tensorflow.org/install/gpu)  ~~~
