### ISSUE TITLE
CenterNet TFLite crashes while running on Android

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#48850]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android 9, not specific device(RK3399 cpu, and QC835 cpu)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14 and 2.4
- Python version: 3.7
- Bazel version (if compiling from source): 3.5.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: not used
- GPU model and memory: not used 

**Describe the current behavior**
We have built a shared object (.so) with Tensorflow cpp API, and then we are linking it with Android App. The shared object contain CenterNet Model in order to predict skeleton detections. When we create a binary for arm64-v8a or armeabi-v7a which is linked against that .so and run it as executable it works just fine. But when we try to predict within android app we are getting the following crash error:
```
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (tflite::Subgraph::ReportErrorC(TfLiteContext*, char const*, ...)+112)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (TfLiteStatus tflite::ops::builtin::reduce::EvalLogic<int>(TfLiteContext*, TfLiteNode*, tflite::ops::builtin::reduce::OpContext*, int, tflite::ops::builtin::reduce::OpContext* (*)(tflite::ops::builtin::reduce::OpContext*, tflite::ops::builtin::reduce::OpContext*))+1668)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (_ZN6tflite3ops7builtin6reduce11EvalGenericILNS2_10KernelTypeE0ELNS2_10ReduceTypeE0EEE12TfLiteStatusP13TfLiteContextP10TfLiteNode+240)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (tflite::ops::builtin::reduce::EvalSum(TfLiteContext*, TfLiteNode*)+240)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (tflite::Subgraph::Invoke()+1008)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (tflite::Interpreter::Invoke()+92)
/data/app/com.example.app-XsHutFbryKx6M754dZvzBg==/lib/arm64/lib_centernet.so (lib::CenterNet::Detect(unsigned char*, int, int)+96)
``` 
**Describe the expected behavior**
As a binary we are getting output from the interpreter and we except to work the same in app. 

If you find that there is missing information just ask and I will try to add that to. 

Thank you in advance!

**Comment by thaink** [comment]
Does your model run correctly with the python API?

**Comment by ArtanBerisha1** [comment]
Hi @abattery , 
Yes I have trained and tested the TFLite model on the Python API and it works like it should. Currently I don't have the tflite model but I could provide one in couple of days.

**Comment by thaink** [comment]
The kernels are shared for C++ and Python API. So it is weird to have the problem in C++ but not Python.
Sure we need the model or someway to reproduce the issue.

**Comment by ArtanBerisha1** [comment]
Hi @thaink , here is the model: 
[CenterNetModel.zip](https://github.com/tensorflow/tensorflow/files/6432343/CenterNetModel.zip)
Just to clarify this is happening when I try to run the model in Android App, because as executable file is working fine.

**Comment by thaink** [comment]
Right. I mean out Java API is also based on C++ so I would expect the behavior to be the same as Python.

**Comment by ArtanBerisha1** [comment]
Now I have tried to run the model with Java API in Android and its not crashing but the output boxes are not correctly and all detections have accuracy 0.0%. 
Also for do you have any idea for the above error in C++, can I try anything else ? ( so I know to close this issue or not because the error is still happening)

Thank you!

**Comment by thaink** [comment]
Might be that version of TFLite is too old. It is very hard to know what went wrong if I cannot reproduce it.

**Comment by ArtanBerisha1** [comment]
What is the TFLite version that you recommend to use ?

**Comment by thaink** [comment]
In case if there are errors. I would absolutely recommend to check if it happens on the nightly version or not.

**Comment by ArtanBerisha1** [comment]
@thaink I was able to run with Java API on Android, but its giving the wrong output, the accuracy of all objects is always 0.0% , and the first coordinate of the rectangle detected is always 0 , and the other 3 are wrong also. Did that model that you tried gave you good detections ?

**Comment by thaink** [comment]
In most of the cases I saw, if the result when you run TFLite with Python is different than what you got on Android, the inputs to the model are not the same. So please print the array that you feed the model and check if they are the same first.

**Comment by tilakrayal** [comment]
@ArtanBerisha1 ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/48850#issuecomment-842877030) from the developer and test the code in latest stable v2.8.It helps.Thanks!

**Comment by ArtanBerisha1** [comment]
Hi @tilakrayal and @thaink 
Sorry for the late response, I have tried with v2.8 using java API directly (not with a shared object) and with some tries I was able to 'decode' the output of the model to box and keypoint coordinates.

Thank you for the help :)
