### ISSUE TITLE
Use of TensorFlow trademark in product name

### ISSUE THREAD

**Issue by 77blackbird** [tensorflow/tensorflow#48852]
After reading the licensing doc and the TM usage guidelines I am still unclear: can the TensorFlow TM be used in a product name, provided that the attributions, as described in the TM guide, are used in the product description.  As an example:

"xxxxx for Machine Learning - Includes Installed TensorFlow Distribution"

Thanks in advance.

**Comment by moflo** [comment]
Gotta follow the brand guidelines... 
https://www.tensorflow.org/extras/tensorflow_brand_guidelines.pdf

**Comment by 77blackbird** [comment]
That's the doc I referenced initially.  Unfortunately, it seems to be more of a style guide; we'd like to make sure our use is legal/acceptable.

**Comment by tilakrayal** [comment]
@77blackbird ,

Can you please provide more information/details to understand the issue.Thanks!

**Comment by 77blackbird** [comment]
@tilakrayal Hi and thank you for the follow-up.

Our proposed use is packaging this as part of a kit that would include a number of components, including a SD Card or SSD pre-loaded with TensorFlow (we'd also include the TPU co-processor as part of the package).  We do not intend to use the logo, or other branding, only the TM "TensorFlow" (we will use branding, if so required).  TensorFlow would be part of the product name, as indicated in the OP, and referenced in the short product description.

Thanks again!

**Comment by ymodak** [comment]
@77blackbird please try bhttps://github.com/tensorflow/tensorflow/issues/48413#issuecomment-817941455
