### ISSUE TITLE
[Mixed_precision] Model#__call__() behavior is different when using tf.Tensor input and when using tf.Variable input.

### ISSUE THREAD

**Issue by keisen** [tensorflow/tensorflow#48860]
**System information**
- OS: colab (Ubuntu 18.04.5)
- Where TensorFlow installed from : pre-installed in colab
- TensorFlow version: 2.4.1
- Python version: 3.7.10
- GPU model and memory: Tesla K80, 12GB

**The current behavior**

On default (`float32`) policy environment, I have to load and use a keras model that is loaded from a `h5` file that was created with `mixed_float16` policy.
When using `tf.Variable` instead of `tf.Tensor` as input value to model, a error bellow is occurred.

```
ValueError: Incompatible type conversion requested to type 'float32' for AutoCastVariable which is casted to type 'float16'
```

I want to calculate the gradient with respect to the input value and update the input value itself iteratively.
To do so, the input value needs to be `tf.Variable`.

**The expected behavior**

I believe that the behavior of both (tf.Tensor and tf.Variable) should be same, that's, the error should be NOT occurred.

**Standalone code to reproduce the issue**

The steps for reproducing:

1. Set mixed_float16 policy
1. Create a model file
1. Set float32 (default) policy
1. Load model and When using tf.Tensor for input of model that is loaded from h5 file, Model#__call__() will NOT throw the error.
1. Load model and When using tf.Valiable for input of model that is loaded from h5 file,Model#__call__() will throw the error.

I've uploaded a notebook to reproduce the error:

https://gist.github.com/keisen/087713c2e547b05a6867506ea5402b93

**Other info / logs**

N/A

Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.4 and Nightly versions. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c42138712e61aa3fcfb8c6253f372681/error-when-calling-model-with-tf_variables.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@keisen,
AFAIK, this behavior is expected because **`Tensorflow Variables`** are used when the values are not constant and if they change continuously, like the **`Weights`** in a **`Model`**. They are not used for **`Inputs`**  to the **`Model`** because **`Inputs`** to a **`Model`** is a **`Tensor`**, not a **`Variable`**.
What do you think?

**Comment by keisen** [comment]
@rmothukuru , Thank you for your response!

I've been implementing a library ([tf-keras-vis](https://github.com/keisen/tf-keras-vis)) that provide [Model Feature Visualization](https://distill.pub/2017/feature-visualization/#:~:text=Feature%20visualization%20answers%20questions%20about,looking%20for%20by%20generating%20examples.&text=As%20a%20young%20field%2C%20neural,not%20yet%20have%20standardized%20terminology). 
This algorism need to calculate the gradient with respect to the input value and to update the input value itself iteratively.
I believe, to do so, the input value needs to be `tf.Variable`, not `tf.constant`.

Since version 1.x, Tensorflow has helped realize this algorism!
So I expect Tensorflow will help realize it even if it adopts mixed-precision mechanism.

Thanks!

**Comment by laplacericky** [comment]
@keisen The idea still applies that the inputs to keras layers needs to be constant
There are multiple ways to achieve this, but the one that involves fewer codes is to have tf.Variable in that layer to track the inputs.
i.e.
```python
def call(self, inputs):
        self.my_tf_var.assign(tf.cast(inputs,self.variable_dtype))
        ...
```
And then, you can take the gradient with respect to this my_tf_var and applies updates to the appropriate tf.Variable that suits you purpose, maybe the variables in other layers. 

Please see if this would help

**Comment by keisen** [comment]
@laplacericky , Thank you for your reply.

I didn't understand what you said. 
Our library receives user's model instance, and then calculates the features of it with gradients.

> There are multiple ways to achieve this, but the one that involves fewer codes is to have tf.Variable in that layer to track the inputs.

Do you mean that our library have to re-build our user's model and replace target layer to be containing a variable instance?, or we have to define Input layer class that have a tf.Variable attribute?

In any cast, I don't think it's a good idea.
Could you explain that in a little more detail?

Thanks!

**Comment by laplacericky** [comment]
@keisen I am just replying to your comment,

> This algorism need to calculate the gradient with respect to the input value and to update the input value itself iteratively.
I believe, to do so, the input value needs to be tf.Variable, not tf.constant.

And actually tensorflow can get gradient with any possible tensors and I was just suggesting ways to achieve it. Please forget that if you find confusing. 

After viewing your gist, I guess this is what you want to do.
```python
input_value = tf.Variable(tf.random.uniform((1, 224, 224, 3), dtype=tf.float32))
model = tf.keras.models.load_model('model-with-mixed_float16-policy.h5')
with tf.GradientTape() as g:
   Loss=objective_function(model(input_value.value()))

dL_dinput_value=g.gradient(Loss,input_value)
```
This is how you can get gradient with respect to the input_value while still enjoying mixed_precision speed up of the model, and, without error message. Then you can take the `dL_dinput_value` and apply update back to `input_value` which is a variable.

**Comment by keisen** [comment]
@laplacericky , Thank you for your great reply!

> This is how you can get gradient with respect to the input_value while still enjoying mixed_precision speed up of the model, and, without error message. Then you can take the dL_dinput_value and apply update back to input_value which is a variable.

I have tried the way you suggested, and tested for  various situations, and then understood this is the best for us.
To be honest, at first, I thought that it was pretty tricky. However it has had no problem.
Thank you so much!

Best regards.

**Comment by keisen** [comment]
@laplacericky , I reopened this because of facing a issue.
It's that the result of the method you proposed and the result of the method adopted by our library are different.
Please see the notebook below for details.

https://gist.github.com/keisen/63724e83f843bc8585ec1c97d68b824e

Assuming one of them is the wrong value, which it is?
We're investigating the cause, but we don't know that for now.

Anyway, to avoid this or any similar problem, we want to understand the problem enough.

Thanks!

**Comment by laplacericky** [comment]
@keisen It is because `tf.keras.optimizers.Adam()` is stateful by default. If a new instance of `tf.Variable` is passed into it every time, it cannot apply the correct stateful effect on the variable like moment estimate, etc, because it would be treated as if it was a separate and new variable. Therefore, the same instance of variable has to be passed into it. You can use `tf.keras.optimizers.SGD()` with zero momentum and the two versions of codes will give the same results.

**Comment by keisen** [comment]
Thank you for your quick response!
I didn't know that. You're amazing!

Thanks!
