### ISSUE TITLE
Issues serializing model (resource conversion)

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#48867]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.2
- GPU model and memory: T4 16GB

**Describe the current behavior**

When attempting to serialize my model using model.save(), I get the following warnings/errors:

```
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe87653dc50>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fe87653dc50>, because it is not built.
WARNING:absl:Found untraced functions such as concatenate_layer_call_and_return_conditional_losses, concatenate_layer_call_fn, resnet_block_layer_call_and_return_conditional_losses, resnet_block_layer_call_fn, resnet_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 365). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as concatenate_layer_call_and_return_conditional_losses, concatenate_layer_call_fn, resnet_block_layer_call_and_return_conditional_losses, resnet_block_layer_call_fn, resnet_block_1_layer_call_and_return_conditional_losses while saving (showing 5 of 365). These functions will not be directly callable after loading.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    521                 as_ref=input_arg.is_ref,
--> 522                 preferred_dtype=default_dtype)
    523         except TypeError as err:

27 frames
ValueError: Tensor conversion requested dtype resource for Tensor with dtype float32: <tf.Tensor 'Adam/beta_1/Read/ReadVariableOp:0' shape=() dtype=float32>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    543           if input_arg.type != types_pb2.DT_INVALID:
    544             raise TypeError("%s expected type of %s." %
--> 545                             (prefix, dtypes.as_dtype(input_arg.type).name))
    546           else:
    547             # Update the maps with the default, if needed.

TypeError: Input 'resource' of 'AssignVariableOp' Op has type float32 that does not match expected type of resource.
```

I'm not sure what the warning about the batchnorm layer means and if it's relevant to the error. From #47479 it the warnings about untraced functions can be safely ignored. It seems odd though that it would error out on the beta parameter of the adam optimizer. Can someone clarify what this float32 -> resource conversion is and why it could fail? I'm unfamiliar with the concept of a "resource" and documentation is rather open ended.

**Describe the expected behavior**
The layer should properly serialize

**Standalone code to reproduce the issue**

```
tboard_callback = tf.keras.callbacks.TensorBoard(log_dir = logs)
model = build_model_functional()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.002, epsilon=1e-8)
model.compile(optimizer=optimizer, loss={'classes': ClassLoss()})
model.fit(final_ds, epochs=4, steps_per_epoch=4, callbacks = [tboard_callback])
```

Working on creating a minimal example but having difficulty pinpointing the exact element causing this issue. Worst case I can post my full project colab notebook but I'd rather be more general if possible. I'm using a pretty standard functional api model that has some internal custom layers that make use of the subclassing API.

**Comment by atyshka** [comment]
Update: I found the issue, it's adding 

```
 tf.debugging.experimental.enable_dump_debug_info(
     logs,
     tensor_debug_mode="FULL_HEALTH",
     circular_buffer_size=-1)
```

That causes the issue. This is related to #36833. I will disable the when saving models, but this issue should either be fixed or noted in the documentation for model.save() or tf.debugging

**Comment by tilakrayal** [comment]
@atyshka ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Thanks!

**Comment by ThijsStockmans** [comment]
> Update: I found the issue, it's adding
> 
> ```
>  tf.debugging.experimental.enable_dump_debug_info(
>      logs,
>      tensor_debug_mode="FULL_HEALTH",
>      circular_buffer_size=-1)
> ```
> 
> That causes the issue. This is related to #36833. I will disable the when saving models, but this issue should either be fixed or noted in the documentation for model.save() or tf.debugging

Hi @atyshka,

I have a similar problem with type conversion in model.save(), could you please indicate how you disabled this piece of code for the workaround to work before I start a new issue related to this. I can't find the input parameter related to this.

Thanks in advance!
