### ISSUE TITLE
Performance Issue: GTX 1080 Tensorflow training is stuck indefinitely | GPU Load 0%

### ISSUE THREAD

**Issue by MuSamiNaf** [tensorflow/tensorflow#48865]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): _**Yes**_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): _**Windows 10 Version 2004 Build 19041.928**_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): _**source**_
- TensorFlow version (use command below): _**Tensorflow = 2.4.0 / Keras = 2.4.3**_
- Python version: _**3.6.5 64-bit (virtualenv)**_
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: _**CUDA = 11.0.194 / CuDNN = 8.0.4**_  | **Nvidia Driver = 460.79**
- GPU model and memory: **_Nvidia GTX 1080 / 8GB Memory / 320.3 GBs Bandwitdh_**
- Other System Specs _**: Intel i5-3570K @4.1GHz | 16GB DDR3 RAM @1360Mhz | 5400RPM HDD (where the code is executed from)**_
- IDE:  **_Visual Studio Code 1.55.2_**

**Describe the current behavior**
_Running a custom code to train a BERT transformer on sentimenent analysis traning dataset.
Batch Size = 8
Sequence Length = 128
Dense Layers = 1 with 512 neurons_

_The GPU VRAM fills up to around 7.5GB without any OOM, however the GPU Load is 0~1%, and a CPU load is fluctuating between 60% ~ 100%
_The 1st training Epoch is stuck there indefinitely, without any progress in the training progress bar._
_If I trained using the CPU, it is slow, but there is a progress and it is not stuck.(CPU Load 100% all the time)_

**Describe the expected behavior**

_Running another non-custom code brought from github to test if the GPU is working or not,
After executing it, the GPU VRAM is filled at around 7.5GB with a GPU load of 22% to 27%.
I am expecting a similar behavior with the custom code._

**Standalone code to reproduce the issue**

- BERT.ipynb (The BERT Transformer) <-- The code that exhibits the current behaviour.
- cnn_tutorial.ipynb <-- A code that exhibits an expected behaviour to ensure TF is running on GPU.
- train.tsv <-- Training dataset for the custom code.
[Attachments.zip](https://github.com/tensorflow/tensorflow/files/6409674/Attachments.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached. **_(None)_**
@bhack

**Comment by Saduf2019** [comment]
@MuSamiNaf 
I am unable to access the code shared, can you please share a colab gist with the issue reported.
