### ISSUE TITLE
Stateful ConvLSTM2D reset_states() throws error

### ISSUE THREAD

**Issue by rschiewer** [tensorflow/tensorflow#48863]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10 (10.0.19042)
- TensorFlow installed from: binary
- TensorFlow version: v2.4.0-49-g85c8b2a817f, 2.4.1
- Python version: 3.7.7
- CUDA/cuDNN version: 11.0/8.0
- GPU model and memory: GeForce GTX 1080 Ti

**Describe the current behavior**

The `reset_states()` method of the `ConvolutionalLSTM2D` layer throws a TypeError if called with the default argument.

**Describe the expected behavior**

The `reset_states()` method of the `ConvolutionalLSTM2D` layer should reset its states if the method is called with the default argument.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
l = tf.keras.layers.ConvLSTM2D(32, kernel_size=3, strides=1, padding='same', stateful=True, batch_size=32)
l.reset_states()
```

**Other info / logs** 

Relevant part of the stack trace: 
```
File "...\venv\lib\site-packages\tensorflow\python\keras\layers\convolutional_recurrent.py", line 357, in reset_states
    state_shape = self.compute_output_shape(input_shape)
  File "...\venv\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 272, in wrapper
    output_shape = fn(instance, input_shape)
  File "...\venv\lib\site-packages\tensorflow\python\keras\layers\convolutional_recurrent.py", line 193, in compute_output_shape
    rows = input_shape[2]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.4 and Nightly versions.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/bdf24c8618cfd44fcfe0f18e0cda8ae4/-48863.ipynb#scrollTo=k-pQruNuQ-Hp).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/4a7347ca07a84514bd322a5dd728d1c3/untitled237.ipynb)..Thanks !

**Comment by kumariko** [comment]
Was able to replicate the issue with TF 2.6, please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/8bb2b739f5caf9a2fd2fe7351d95dd80/untitled237.ipynb#scrollTo=S9uBhSV1fLvo) . Thanks !
