### ISSUE TITLE
[Custom Layer]ValueError: tf.function-decorated function tried to create variables on non-first call

### ISSUE THREAD

**Issue by AdityaNikhil** [tensorflow/tensorflow#48878]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Colab**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **Colab**
- TensorFlow version (use command below): **Colab**
- Python version: **Colab**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **Colab**
- GPU model and memory: **Colab**

## **Describe the current behaviour**
I am trying to implement a custom transformer encoder layer **which I truly believe is the custom layer that is causing the above error**. Apart from the above layer, I have developed 3 more simple custom layers which I didn't mention here to maintain neatness.

### Transformer layer

    class transformer(layers.Layer):
      
      def __init__(self, num_heads, transformer_layers, patch_size):
        super(transformer, self).__init__()
        self.num_heads = num_heads
        self.transformer_layers = transformer_layers
        self.patch_size = patch_size
      
      def call(self, encoded_patches):
        for _ in range(self.transformer_layers):
            x1 = layers.LayerNormalization(epsilon=1e-6)(encoded_patches)
            attention_output = layers.MultiHeadAttention(
                num_heads = self.num_heads, key_dim = projection_dim, dropout = 0.1 
            )(x1,x1)
            x2 = attention_output + encoded_patches
            x3 = layers.LayerNormalization(epsilon=1e-6)(x2)
            x3 = mlp(x3, transformer_units, 0.2)
            encoded_patches = x3 + x2
    
        representation = layers.LayerNormalization(epsilon=1e-6)(encoded_patches)
        resize_img = layers.Reshape([image_size // self.patch_size, image_size // self.patch_size, 64])(representation)
        
        return resize_img 

### Model 

    def PVT():
    
      # Inputs
      input = layers.Input(shape=input_shape)
      augment = data_augmentation(input)
    
      # Stage 1
      patches_1 = Patch_1(patch_size_1)(augment)
      patches_1 = PatchEncoder(num_patches=(image_size // patch_size_1) ** 2, projection_dim=projection_dim)(patches_1)
      input_2 = transformer(num_heads, transformer_layers, patch_size_1)(patches_1) #Output 1
    
      # Stage 2
      patches_2 = Patch_2(patch_size_2)(input_2)
      patches_2 = PatchEncoder(num_patches=(image_size // patch_size_2) ** 2, projection_dim=projection_dim)(patches_2)
      input_3 = transformer(num_heads, transformer_layers, patch_size_2)(patches_2) #Output 2
    
      # Stage 3
      patches_3 = Patch_3(patch_size_3)(input_3)
      patches_3 = PatchEncoder(num_patches=(image_size // patch_size_3) ** 2, projection_dim=projection_dim)(patches_3)
      input_4 = transformer(num_heads, transformer_layers, patch_size_3)(patches_3) #Output 3
    
      # Stage 4
      patches_4 = Patch_4(patch_size_4)(input_4)
      patches_4 = PatchEncoder(num_patches=(image_size // patch_size_4) ** 2, projection_dim=projection_dim)(patches_4)
      input_5 = transformer(num_heads, transformer_layers, patch_size_4)(patches_4) #Output 4
    
      representation = layers.Flatten()(input_5)
      representation = layers.Dropout(0.5)(representation)
      # Classify outputs.
      logits = layers.Dense(num_classes)(representation)
      # Create the Keras model.  
      model = keras.Model(inputs=input, outputs=logits)
    
      return model

### Compiler and optimizer

    def run_experiment(model):
    
        optimizer = tfa.optimizers.AdamW(
            learning_rate=learning_rate, weight_decay=weight_decay, beta_1=0.9, beta_2=0.999
        )
    
        model.compile(
            optimizer=optimizer,
            loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
            metrics=[
                keras.metrics.SparseCategoricalAccuracy(name="accuracy"),
                keras.metrics.SparseTopKCategoricalAccuracy(5, name="top-5-accuracy"),
            ],
        )
    
    
        history = model.fit(
            x=xtrain,
            y=ytrain,
            batch_size=batch_size,
            epochs=5,
            validation_split=0.1
        )
    
        model.save('model-5.h5')
    
        return history
    
    pvt = PVT()
    history = run_experiment(pvt)

### Note
I have checked several sources about this but still, I am confused about understanding this error. Before you direct me to other sources, I assure you that I have already checked them all. So I sincerely request you to please provide a clean solution here. By the way, this code is my attempt to reproduce the [Pyramid vision transformers](https://arxiv.org/abs/2102.12122).

### Model summary(FYI)

    Model: "model_2"
    _________________________________________________________________
    Layer (type)                 Output Shape              Param #   
    =================================================================
    input_3 (InputLayer)         [(None, 32, 32, 3)]       0         
    _________________________________________________________________
    data_augmentation (Sequentia (None, 72, 72, 3)         7         
    _________________________________________________________________
    patch_1_2 (Patch_1)          (None, None, 48)          0         
    _________________________________________________________________
    patch_encoder_8 (PatchEncode (None, 324, 64)           23872     
    _________________________________________________________________
    transformer_8 (transformer)  (None, 18, 18, 64)        0         
    _________________________________________________________________
    patch_2_2 (Patch_2)          (None, None, 4096)        0         
    _________________________________________________________________
    patch_encoder_9 (PatchEncode (None, 81, 64)            267392    
    _________________________________________________________________
    transformer_9 (transformer)  (None, 9, 9, 64)          0         
    _________________________________________________________________
    patch_3_2 (Patch_3)          (None, None, 16384)       0         
    _________________________________________________________________
    patch_encoder_10 (PatchEncod (None, 16, 64)            1049664   
    _________________________________________________________________
    transformer_10 (transformer) (None, 4, 4, 64)          0         
    _________________________________________________________________
    patch_4_2 (Patch_4)          (None, None, 65536)       0         
    _________________________________________________________________
    patch_encoder_11 (PatchEncod (None, 4, 64)             4194624   
    _________________________________________________________________
    transformer_11 (transformer) (None, 2, 2, 64)          0         
    =================================================================
    Total params: 5,535,559
    Trainable params: 5,535,552
    Non-trainable params: 7

## **Describe the expected behavior**
To train without any bugs.

## **Standalone code to reproduce the issue**
[Colab Code](https://colab.research.google.com/drive/1o2SWFH74WnmR9Vkz352Zh9R9_fw5lnE5?usp=sharing)

## **Other info/logs** 
```
ValueError                                Traceback (most recent call last)
<ipython-input-15-b64accfa4347> in <module>()
     27     return history
     28 
---> 29 pvt = PVT()
     30 history = run_experiment(pvt)

13 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    <ipython-input-14-e002dca74606>:12 call  *
        x1 = layers.LayerNormalization(epsilon=1e-6)(encoded_patches)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:1008 __call__  **
        self._maybe_build(inputs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:2710 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/normalization.py:1206 build
        experimental_autocast=False)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:639 add_weight
        caching_device=caching_device)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py:810 _add_variable_with_custom_getter
        **kwargs_for_getter)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py:142 make_variable
        shape=variable_shape if variable_shape else None)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/variables.py:260 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/variables.py:221 _variable_v1_call
        shape=shape)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py:731 invalid_creator_scope
        "tf.function-decorated function tried to create "

    ValueError: tf.function-decorated function tried to create variables on non-first call.
```

**Comment by Saduf2019** [comment]
@AdityaNikhil 
While i replicate the colab shared i face a different error, please find the [gist here](url.)

Could you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/27120#issuecomment-768443779) and let us know if it helps. [similar issue #34983, [link](https://www.tensorflow.org/api_docs/python/tf/config/run_functions_eagerly)]

**Comment by AdityaNikhil** [comment]
Hi @Saduf2019,
It was just the cell where the variable was declared was below that function. Anyway, can you try again. Thank you!

**Comment by Saduf2019** [comment]
@AdityaNikhil 
Please share a colab gist with the issue faced.

**Comment by AdityaNikhil** [comment]
@Saduf2019 
If you really care about this issue, you wouldn't be here twice. 
The colab gist is in the issue I wrote above, you can find it there.

**Comment by Saduf2019** [comment]
@AdityaNikhil 
As mentioned in your previous comment that you face a new problem with eagerly and we do not face the same issue as shared in our gist, we request you to share a colab gist with the issue.

**Comment by AdityaNikhil** [comment]
@Saduf2019 
If it works fine, maybe there's something wrong when I am running on eagerly. I request you to send me your working gist with eagerly turned on.

**Comment by bhack** [comment]
Can you check https://github.com/tensorflow/tensorflow/issues/48851#issuecomment-830858393

**Comment by Saduf2019** [comment]
@AdityaNikhil 
Please update as per above comment.
