### ISSUE TITLE
download error for cars196 dataset when using tfds.load

### ISSUE THREAD

**Issue by imanvk** [tensorflow/tensorflow#48876]
It seems "cars196" dataset is not available:

(train_ds, val_ds, test_ds), metadata = tfds.load(
    'cars196',
    split=['train[:80%]', 'train[80%:]', 'test'],
    with_info=True
)

**DownloadError**: Failed to get url https://image-net.org/internal/car196/cars_test.tgz. HTTP code: 404.

**Comment by Saduf2019** [comment]
@imanvk 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

If it just about the dataset, you can find them here : [link](https://www.tensorflow.org/datasets/catalog/cars196) ,[link1](https://ai.stanford.edu/~jkrause/cars/car_dataset.html)

**Comment by ymodak** [comment]
duplicate #https://github.com/tensorflow/tensorflow/issues/48818
