### ISSUE TITLE
Possible memory leak in eager context's thread_local_data

### ISSUE THREAD

**Issue by ebrevdo** [tensorflow/tensorflow#48888]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
5.10.19-1rodete1-amd64 #1 SMP Debian 5.10.19-1rodete1 (2021-03-11) x86_64 GNU/Linux

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3 binary
- TensorFlow version (use command below): nightly (5/2)
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v1.12.1-52250-g36e43c933a8 2.5.0-dev20210305

**Describe the current behavior**

Details in https://github.com/tensorflow/agents/issues/569.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
pip3 install --upgrade tf-nightly
pip3 install --upgrade tf-agents-nightly[reverb]
```
(go to site-local `tf_agents/examples/dqn` directory)
```
python3 dqn_train_eval.py
```

if you edit that python file to `tracemalloc` snapshot on iterations of `learner.run()`, e.g., between iterations 1000 and 5000, you'll see the (possible) memory leak.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ebrevdo** [comment]
It's possible the leak was actually found and ignored in https://github.com/tensorflow/tensorflow/commit/11e09d9352066e564db9f0e16cc5f06c6f5f8b63?

**Comment by ebrevdo** [comment]
Adding Ed & Kibeom who approved that code.

**Comment by ebrevdo** [comment]
It's possible the error stems back to the fact that `eager_context_thread_local_data_map` and `eager_context_thread_local_data_defaults` are not associated with a particular context object (they're defined as `thread_local` in an anonymous namespace in a `.cc` file).  This was done [here](https://github.com/tensorflow/tensorflow/commit/8e1ef83d9ea91f1de915841690264b98b9a75c21).

**Comment by allenlavoie** [comment]
From the original bug report, "One of the possible solutions is to call gc.collect() but it significantly slows down training". That suggests to me that this is not a memory leak at all, just a reference cycle. I don't see much mention of that later on in the thread; seems like the thread_local bits are definitely a red herring if so.

There's a separate question of which objects are participating in the reference cycle. TF has some tests that basic stuff doesn't create reference cycles; I wouldn't rule core TF out entirely, but please check the agents code first. You can debug with the `gc` module, setting the DEBUG_SAVEALL flag.

**Comment by tomerk** [comment]
Yeah we know certain parts of TF (and e.g. Keras functional models) are susceptible to reference cycles that sometimes require a gc.collect to clear. We have some internal bugs open for Keras to fix these reference cycles, though it'll require a fairly involved rework of the internals of Keras History tracking in functional models, so we haven't been able to put it on the roadmap yet.

There's also been discussions of whether a device-memory OOM should trigger a gc.collect (as the reason these cycles don't get auto-cleaned up is standard python garbage collection doesn't take into account TF device memory usage when trying to decide whether to trigger a garbage collection).

@rxsang who has been involved in those discussions as well (especially around TPUs)

**Comment by ebrevdo** [comment]
I'm not sure this is a reference cycle so much as it's some kind of issue with eager context `thread_local` [objects](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/eager/pywrap_tfe_src.cc#L4289) "disappearing" between calls.  Why aren't these objects defined inside the appropriate eager context?

**Comment by edloper** [comment]
Yes, the issue is that the thread_local pointer eager_context_thread_local_data_map is (lazily) initialized to point to an object, but that never gets freed when the thread is destroyed.  (The pointer is destroyed, but not the object it points to.)  So a small amount of memory is leaked per thread created & destroyed.  I'm working on a fix for this.

**Comment by allenlavoie** [comment]
Edward, I sent you a change; it looks like this triggers even without any thread creation involved. Just repeatedly clearing and setting the function_call_options field triggers it, and that happens when you change some settings (soft device placement, optimizer options, etc.).

**Comment by ebrevdo** [comment]
@allenlavoie thank you for confirming!  we're seeing something like this even when we don't change config settings.  i expect that if you fix the problem under your test case, it'll resolve the problem in general.

**Comment by edloper** [comment]
Thanks, @allenlavoie!

**Comment by edloper** [comment]
(I think there is *also* a memory leak when lots of threads are created and destroyed; so I'll go ahead and fix that one as well.  But I think the one @allenlavoie found is the more significant/relevant one.)

**Comment by allenlavoie** [comment]
Interesting. I don't know what would have been clearing the function call options if you're not changing config/optimizer/etc. settings. If that change does help with the leak we may also want to figure out why the options are repeatedly recreated, since it sounds like a performance issue.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Also some of the PR's are raised and merged for the similar feature. Please take a look at the merged PR's.
https://github.com/tensorflow/tensorflow/commit/4bdae6bb3b3a31de0e7adc111e6ed4a83c9341a0
https://github.com/tensorflow/agents/commit/e9c59f4130d809973a0088d30f6cb72611dcf83c

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
