### ISSUE TITLE
Docker Hosted automl predict ignores score_threshold param

### ISSUE THREAD

**Issue by ayandebbarman** [tensorflow/tensorflow#48885]
I have deployed the .pb file exported out of GCP as per below instructions 
 
https://cloud.google.com/vision/automl/object-detection/docs/containers-gcs-tutorial
 
I am able to get the response but I am getting all predictions with all scores. I tried to limit the responses with below payload and score_threshold. But its still not filtering the response with low scores and seems to be ignoring score_threshold [](url)
 
I followed documentation at here
https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.PredictRequest
 
 
Place where Docker is hosted: http://localhost:8080/v1/models/default:predict
 
Payload:
{
    "instances": [
        {
            "image_bytes": {
                "b64": "<base64 image>”
          },
            "key": "your-chosen-image-key123"
        }
    ],
                "params": {
                "score_threshold": 0.7
            }
}

**Comment by bhack** [comment]
I think that you need to use the feedback button in that docs page footer. It is not in the TensorFlow perimeter.

**Comment by ayandebbarman** [comment]
> I think that you need to use the feedback button in that docs page footer. It is not in the TensorFlow perimeter.

The parameter is being accepted but not working. 
If you try something like below payload you get an error as parameter is not identified .. Ultimately whether you host it in Docker or in GCP it should be calling the predict api 

https://cloud.google.com/automl/docs/reference/rpc/google.cloud.automl.v1#google.cloud.automl.v1.PredictRequest

{
"instances": [
{
"image_bytes": {
"b64": "”
},
"key": "your-chosen-image-key123"
},
"params": {
"score_threshold": 0.7
}
]
}

**Comment by jvishnuvardhan** [comment]
@ayandebbarman Looks like this is more related to `automl`. Can you please post it in `automl` repo  https://github.com/google/automl/issues so that experts in that repository will resolve your issue faster. Thanks!

**Comment by ayandebbarman** [comment]
Done https://github.com/google/automl/issues/985

**Comment by ayandebbarman** [comment]
Closing as created new one in automl https://github.com/google/automl/issues/985
