### ISSUE TITLE
TFLite NNApi / GPU causes results to be outputted as 0.0, while on CPU results are correct

### ISSUE THREAD

**Issue by arctop-sk** [tensorflow/tensorflow#48884]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubunto 20.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 4 / 5
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.4

**Describe the current behavior**

When using the following code:

https://colab.research.google.com/gist/AiaHaruv/906b7d73395ef437f135c81f2c7754e9/filter_issue.ipynb

On the edge device (Pixel 4 or 5), some of the results are reported as 0.0, when GPU or NNAPI delegates are used. 
This is in the context of using TFLite on android, pulling the latest nightly build.
I cannot find any indication as to why this happens. 

Using CPU, or when ran via the normal TF (not lite), this produces correct results

**Describe the expected behavior**

Would expect to receive correct (non 0.0) results when using acceleration 

**Standalone code to reproduce the issue**

https://colab.research.google.com/gist/AiaHaruv/906b7d73395ef437f135c81f2c7754e9/filter_issue.ipynb

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by arctop-sk** [comment]
Some additional info. 
We have tried every combination of flags on both NNApi and GPU delegates, the problem persists.

**Comment by abattery** [comment]
@srjoglekar246 could you take a look?

**Comment by srjoglekar246** [comment]
@arctop-sk What code are you using to run the models with GPU/NNAPI on device?

**Comment by arctop-sk** [comment]
@srjoglekar246 - I've tried with all three functions. I've also tried all combinations of flags inside the options.

     `public static Interpreter.Options getOptionsForGPU() {
        Interpreter.Options options = new Interpreter.Options();
        CompatibilityList compatList = new CompatibilityList();
        if (compatList.isDelegateSupportedOnThisDevice()) {
            // if the device has a supported GPU, add the GPU delegate
            GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
            // Tried with and without these 2 lines.
            delegateOptions.setQuantizedModelsAllowed(false);
            delegateOptions.setPrecisionLossAllowed(false);
            GpuDelegate gpuDelegate = new GpuDelegate(delegateOptions);

            options.addDelegate(gpuDelegate);
        }
        return options;
    }

    public static Interpreter.Options getOptionsForNNAPI(){
        Interpreter.Options options = new Interpreter.Options();
        options.setUseNNAPI(true);
        return options;
    }


    public static Interpreter.Options getOptionsForNNAPIDelegate(){
        Interpreter.Options options = new Interpreter.Options();
        NnApiDelegate.Options delOptions = new NnApiDelegate.Options();
        // Tried with all variations of ExecutionPreference as well
        // delOptions.setExecutionPreference(NnApiDelegate.Options.);
       // Tried with or without these 2
        delOptions.setUseNnapiCpu(false);
        delOptions.setAllowFp16(false);
        options.addDelegate(new NnApiDelegate(delOptions));
        return options;
    }

Creating the interpreter, with theses options

          `tfLite = new Interpreter(tfLiteModel, tfLiteOptions);`

Creating the buffers is done in a loop with this code:

            `Tensor ten = tfLite.getInputTensor(i); // or getOutputTensor(i)
            ByteBuffer inputBuffer = ByteBuffer.allocateDirect(ten.numBytes());
            inputBuffer.order(ByteOrder.nativeOrder());`

Running inference is done via: (I keep a list of the buffers for quick iteration, while the model gets an array of the inputs and a a map of the outputs, as per examples, and function signatures.

       `for (InterpreterInputOutput input: mInputsList) {
            input.buffer.rewind();
        }
        for (InterpreterInputOutput output: mOutputsList) {
            output.buffer.clear();
        }
        tfLite.runForMultipleInputsOutputs(mInputs , mOutputs);`

**Comment by srjoglekar246** [comment]
The code seems fine to me. Have you added the proper dependencies, etc?
@lu-wang-g Can you take a look?

**Comment by arctop-sk** [comment]
@srjoglekar246 - yes all dependencies are there.

**Comment by srjoglekar246** [comment]
Do you see any errors in adb logcat? Its difficult to know what exactly might be going wrong in your case without looking at some debug logs or the overall code/app.

**Comment by lu-wang-g** [comment]
+1 on screening the logs. The delegates may not be set up successfully.

**Comment by arctop-sk** [comment]
I haven't seen anything. 
The model runs, and produces results. However, we get something like [ 4 results, 12 0.0 , 6 result ...]
and so on with NNApi / GPU. Works as expected on CPU.
Is there a flag I can send the runtime like adb shell setprop debug.tflite.trace 1 that will give more verbose data in the logcat?

**Comment by arctop-sk** [comment]
@srjoglekar246  @lu-wang-g 
It doesn't seem to me that we are using any operations that are not supported by the GPU/NNAPI, but that would have been my first guess. Since i'm getting no errors, I don't really have a lead as to where to start digging into this.

**Comment by srjoglekar246** [comment]
@arctop-sk Can you try using our [benchmark tool](https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary) on your model with GPU & NNAPI delegates? It has more verbose logging, and will tell us if the delegates are getting used at all.

**Comment by arctop-sk** [comment]
@srjoglekar246 same case with the GPU. not sure if this is the cause, but that's the only issue i'm seeing

**Comment by arctop-sk** [comment]
@srjoglekar246 any updates on this?

**Comment by srjoglekar246** [comment]
TBH, your code for inference seems fine.
As a sanity check, can you try building & running our image classification [sample](https://www.tensorflow.org/lite/examples/image_classification/overview) to see if it works fine w/GPU on your device? I just want to ensure that the basic runtime works as intended on your device.

**Comment by arctop-sk** [comment]
@srjoglekar246 

Loading that up on my device, first thing I notice while loading is this:

2021-05-18 19:58:44.058 32248-32273/org.tensorflow.lite.examples.classification I/AdrenoGLES-0: QUALCOMM build                   : 85da404, I46ff5fc46f
    Build Date                       : 11/30/20
    OpenGL ES Shader Compiler Version: EV031.31.04.01
    Local Branch                     : promo490_3_Google
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2021-05-18 19:58:44.058 32248-32273/org.tensorflow.lite.examples.classification I/AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
2021-05-18 19:58:44.058 32248-32273/org.tensorflow.lite.examples.classification I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2021-05-18 19:58:44.066 32248-32273/org.tensorflow.lite.examples.classification I/AdrenoGLES-0: PFP: 0x016ee189, ME: 0x00000000
2021-05-18 19:58:44.072 32248-32273/org.tensorflow.lite.examples.classification W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2021-05-18 19:58:44.072 32248-32273/org.tensorflow.lite.examples.classification W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2021-05-18 19:58:44.098 32248-32273/org.tensorflow.lite.examples.classification I/Gralloc4: mapper 4.x is not supported

The app crashes right after that due to our dev policy (i believe) that disallows usage of the camera. I'm getting this resolved with IT and will report other findings, but wanted to give first info that I have

**Comment by pjpratik** [comment]
Hi @arctop-sk 

Did you get a chance to re-evaluate the model?

Thanks.

**Comment by arctop-sk** [comment]
> Hi @arctop-sk 
> 
> 
> 
> Did you get a chance to re-evaluate the model?
> 
> 
> 
> Thanks.

Unfortunately not yet. We are a bit lacking in our TF staff atm. 

I'll update this ticket when we get a chance to upgrade our TF implementation and model, and test.

**Comment by arctop-sk** [comment]
We're still in the process of arriving at evaluating this issue. Thank you

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
