### ISSUE TITLE
Error occured Bidirectional layer with TPU

### ISSUE THREAD

**Issue by cosmoquester** [tensorflow/tensorflow#48880]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): Current Colab default (2.4.1)
- Python version: Colab default (3.7.10)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
('v2.4.1-0-g85c8b2a817f', '2.4.1')

**Describe the current behavior**
There is code below. The problem is error under the specific conditions.

Here are conditions under which an error occurs.
1. On TPU
2. Use Bidirectional layer with ``return_sequence==True``
3. Use tf.keras.layers.Masking or ``mask_zero=True`` with tf.keras.layers.Embedding

Under the triple of upper conditions, training code puts error below.
Without even only one of the conditions, error not occured.
```
InternalError: 9 root error(s) found.
  (0) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_79]]
  (1) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_143]]
  (2) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_159]]
  (3) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_95]]
  (4) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_127]]
  (5) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[tpu_compile_succeeded_assert/_1920970171686233974/_5/_63]]
  (6) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
	 [[cluster_train_function/control_after/_1/_195]]
  (7) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1920970171686233974/_5}}]]
  (8) Internal: {{function_node __inference_train_function_212595}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:1343) operand != nullptr 
 ... [truncated]
```

**Describe the expected behavior**
I expect to works well under the conditions also.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import os
import tensorflow as tf

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=os.environ["TPU_NAME"])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)

class TestModel(tf.keras.Model):
  def __init__(self):
    super().__init__()

    self.embedding = tf.keras.layers.Embedding(input_dim=6, output_dim=64)
    self.pad_masking = tf.keras.layers.Masking(0, name="masking")
    lstm = tf.keras.layers.LSTM(64, return_sequences=True)
    self.lstm = tf.keras.layers.Bidirectional(lstm)
    self.dense = tf.keras.layers.Dense(1)

  def call(self, input, training=None):
    output = self.embedding(input)
    output = self.pad_masking(output)
    output = self.lstm(output)
    output = self.dense(output[:, -1, :])
    return output

with strategy.scope():
  x = tf.data.Dataset.from_tensor_slices([tf.constant([1,2,3,4,5]), tf.constant([1,2,3,4,5]), tf.constant([1,2,3,4,5])])
  y = tf.data.Dataset.from_tensor_slices([[1],[2],[3]])
  dataset = tf.data.Dataset.zip((x,y)).repeat().batch(2)

  model = TestModel()
  model(tf.keras.Input([None]))

  model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam(1e-4),
                metrics=['accuracy'])
  model.fit(dataset, epochs=10, steps_per_epoch=10)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@cosmoquester 
Is this still an issue as the pr is merged.

**Comment by cosmoquester** [comment]
I bypassed the problem by using custom bidirectional layer in my repository. However, the issue is still alive. You can just reproduce this issue by running attached code on TPU environment.

**Comment by ymodak** [comment]
The code snippet fails with latest tf-nightly version as well. See [gist](https://colab.research.google.com/gist/ymodak/f4b0daeca83f6144d019d7fbed2df330/untitled14.ipynb)

**Comment by kumariko** [comment]
Was able to reproduce the issue in TF v2.6 please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/bce2855ba3276a95dc8012c3b7631b2d/untitled14.ipynb#scrollTo=7cT46uJLEBrp).Thanks!

**Comment by rxsang** [comment]
Hi David, this is a dynamic padder error. Could you take a look? Thanks!

**Comment by mohantym** [comment]
Hi @cosmoquester !

I am able replicate this issue in 2.11. 
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/6fef9b8aea810434878154bb6d99e009/untitled14.ipynb#scrollTo=7cT46uJLEBrp) for reference. 

Thank you!

**Comment by tilakrayal** [comment]
@cosmoquester,
I tried to execute the mentioned code on tensorflow v2.13 and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ff2bd44959babf23cf91fd36cb8e803a/untitled.ipynb). Thank you!

**Comment by cosmoquester** [comment]
It seems resolved, Thank you!
