### ISSUE TITLE
MIRROR PAD result mixed

### ISSUE THREAD

**Issue by curioyang** [tensorflow/tensorflow#48914]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):2.4

When I tested the mirror pad, I found that the result was a bit unexpected.
The input shape of pad is [1,1,2,2], paddings[[0, 0], [0, 0], [3, 3], [3, 3]],pad mode: SYMMETRIC.
I know that my parameters may not be in line with the correct usage of pad, but I want to know whether his result is caused by a bug or if I run it incorrectly.

### model [file](https://www.notion.so/tflite-pad-symmetric-mode-bb313fc05adc497cae4d719896da70f4)

###The wrong result:
![image](https://user-images.githubusercontent.com/39184746/117141626-588fd480-ade1-11eb-8bd3-4c57e341d761.png)

If i had took a mistake, please tell me how to fix it ! THX :p

**Comment by thaink** [comment]
Paddings must be no greater than the dimension size.
Here, your paddings is bigger, that leads to incorrect results.

**Comment by curioyang** [comment]
@thaink Got it, I checked the documentation, it did mention this, but I ignored it.   THX !
