### ISSUE TITLE
Failed init TFL interpreter when enabled XNNPACK

### ISSUE THREAD

**Issue by kitetaka** [tensorflow/tensorflow#48924]
**System information**
- IDE: XCode 12.5
- Mobile device: iPhone 12 Pro Max
- TensorFlow installed: 'TensorFlowLiteObjC' from CocoaPods
- TensorFlow version: tried '2.3.0', '2.4.0', and '0.0.1-nightly.20210503'

**Describe the current behavior**
Whenever enabled XNNPACK, model initiation will fail. (see code snippets below)

**Describe the expected behavior**
Expected to initiate mode successfully

**Standalone code to reproduce the issue**
NSError *err = nil;
TFLInterpreterOptions *options = [[TFLInterpreterOptions alloc] init];
options.useXNNPACK = YES;
NSString *modelPath = [[NSBundle mainBundle] pathForResource:@"mymodel" ofType:@"tflite"];
_modelInterpreter = [[TFLInterpreter alloc] initWithModelPath:modelPath options:options error:&err];

where mymodel.tflite is a custom trained model. If set 
         options.useXNNPACK = NO;
everything will work normally. When XNNPACK is enabled, the init will fail for interpreter. Specifically, it fails at 
         _interpreter = TfLiteInterpreterCreate(model, cOptions);
inside TFLInterpreter.mm in the framework, and there's no source code to trace further.

**Comment by abattery** [comment]
@yyoon @multiverse-tf could you take a look?

**Comment by sachinprasadhs** [comment]
Hi, Can you make sure you build the XNNPACK with TFLITE_ENABLE_XNNPACK=ON and test the code again.
For details on build, check the document [here](https://www.tensorflow.org/lite/guide/build_cmake). Thanks!
