### ISSUE TITLE
Only some Keras activations under `tf.keras.activations` are supported

### ISSUE THREAD

**Issue by mipsan** [tensorflow/tensorflow#48925]
Hi,

When adapting QAT(Quantization aware training) to get bbox regression with Keras, 
I've got following error:
`ValueError: Only some Keras activations under `tf.keras.activations` are supported. For other activations, use `Quantizer` directly, and update layer config using `QuantizeConfig`.
`
Even I referred some Tensorflow documents, I cannot find out what's problem at all.
[link](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization/keras/quantize_model?hl=ko): 

I attach my code block as below:
```
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

INIT_LR = 1e-4
NUM_EPOCHS = 1
BATCH_SIZE = 8

basemodel = MobileNetV2(weights="imagenet", include_top=False,
        input_tensor=Input(shape=(224, 224, 3)))
basemodel.trainable = False

# MobileNetV2
flatten = basemodel.output
bboxHead = Flatten(name="flatten")(flatten)
bboxHead = Dense(128, activation="relu")(bboxHead)
bboxHead = Dense(4, activation="sigmoid")(bboxHead)

model = Model(inputs=basemodel.input, outputs=bboxHead)
opt = Adam(INIT_LR)
model.compile(loss="mse", optimizer=opt)
H = model.fit(
        trainImages, trainTargets, 
        validation_data=(testImages, testTargets),
        batch_size=BATCH_SIZE,
        epochs=NUM_EPOCHS,
        verbose=1)

import tensorflow_model_optimization as tfmot
quantize_model = tfmot.quantization.keras.quantize_model

q_aware_model = quantize_model(model)
q_aware_model.compile(loss="mse", optimizer=opt, metrics=['accuracy'])
```
'**sigmoid**' of the last Dense layer may the error, because if I change this to the other activation, the error disappeared.
Just disappeared.

-----
[Edit]
TF: 2.4.1

Thanks,

**Comment by UsharaniPagadala** [comment]
@mipsan 
Could you please provide the dependencies as I am facing these [errors](https://colab.research.google.com/gist/UsharaniPagadala/82625cd04d3a942ed6a3d8f8482e358d/-48925.ipynb) .Thanks

**Comment by mipsan** [comment]
@UsharaniPagadala 

Thanks, 
Updated dependencies, then how about dataset?

**Comment by UsharaniPagadala** [comment]
@mipsan 

I was able to reproduce the error.Could you please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/b2ac4f74f2b6e399ccc41ee415b4499c/-48925.ipynb#scrollTo=8DqfVFCf6LVB) here, also have a look at [this](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize_aware_activation.py) and let us know if it helps.Thanks

**Comment by mipsan** [comment]
@UsharaniPagadala 

I tested this [guide](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide) as well, same errors as a result.

**Comment by mipsan** [comment]
@UsharaniPagadala 

Your [idea](https://github.com/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/python/core/quantization/keras/quantize_aware_activation.py) gave me a hint!

I found that a version of `tensorflow-model-optimization` is **0.5.0** 
and `quantize_aware_activation.py` slightly differs to what I have. 
`_PRE_QUANT_ACTIVATIONS = frozenset({'softmax', 'sigmoid'})`
But 
I have `_PRE_QUANT_ACTIVATIONS = frozenset({'softmax'})`. 

After add `sigmoid` to this line, I am able to get what I want.

Thanks,

**Comment by UsharaniPagadala** [comment]
@mipsan

Thank you for your update, glad its working fine for you, kindly move this issue to closed status as it is resolved.
