### ISSUE TITLE
compat.v1.resize_bilinear fails in 2.4.1

### ISSUE THREAD

**Issue by elad-c** [tensorflow/tensorflow#48928]
The following code works in 2.3.2 but fails in 2.4.1:

`
h, w = 3, 1
image = tf.constant(np.arange(h*w).reshape((h, w)), dtype=tf.float32)[tf.newaxis, ..., tf.newaxis]
_input = tf.keras.layers.Input((h, w, 1))
tf2_img = tf.image.resize(_input, [9, 1])
tf1_img = tf.compat.v1.image.resize(_input, [9, 1], align_corners=True)
tf1_img_bl = tf.compat.v1.image.resize_bilinear(_input, [9, 1], align_corners=True)  # <-- problematic line
out = tf.concat([tf1_img, tf2_img, tf1_img_bl], 2)

m = tf.keras.Model(inputs=_input, outputs=out)
`

**Comment by elad-c** [comment]
also fails in tf-nightly: 2.6.0-dev20210505

**Comment by UsharaniPagadala** [comment]
@elad-c 
I Could  reproduce the code in tf2.4 and tf-nightly. Could you please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/0e42ef32964ec9f4205a1f99b67e6038/untitled41.ipynb).Thanks

**Comment by elad-c** [comment]
I checked the gist. Seems to validate the bug. Will this issue be fixed?

**Comment by UsharaniPagadala** [comment]
@elad-c 
I could run this in tf2.4 as well.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/0e42ef32964ec9f4205a1f99b67e6038/untitled41.ipynb). Thanks

**Comment by UsharaniPagadala** [comment]
@elad-c 
 I could run the code in tf 2.4 as well.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/0e42ef32964ec9f4205a1f99b67e6038/untitled41.ipynb).Thanks

**Comment by elad-c** [comment]
Hi @UsharaniPagadala ,
Maybe we have some local differences, but running the code in the gist works well for 2.3 but fails for 2.4
i'm not sure how local changes might affect the colab notebook, maybe you didn't do "RESTART RUNTIME"?

Thanks,
Elad

**Comment by UsharaniPagadala** [comment]
@elad-c 
I did restart runtime  every time and worked for me and here is the [gist](https://colab.research.google.com/gist/UsharaniPagadala/0e42ef32964ec9f4205a1f99b67e6038/untitled41.ipynb).Thanks

**Comment by lior-dikstein** [comment]
Hi @UsharaniPagadala , @elad-c . I tried the code in the gist and it fails for me as well with tf 2.4 (after pressing "restart runtime").
You can add a print(tf.__version__) to make sure the correct version is running. Thanks

**Comment by reuvenperetz** [comment]
Hi,
I tried the gist and I see a similar result (works well in 2.3 but fails in 2.4)...
![screenshot](https://user-images.githubusercontent.com/44209964/120196859-00ee5880-c229-11eb-8699-28d4147d8fe7.png)

**Comment by tomerk** [comment]
It seems the nature of the compat.v1.resize_bilinear exporting and some odd deprecated decorator interactions means dispatching isn't being registered right now for some reason. We will look into this, but for now you can put the resize_bilinear call in a keras Lambda layer or a keras custom layer as a workaround.

**Comment by jvishnuvardhan** [comment]
@elad-c Is this still an issue for you? Did you follow the above suggestion? I changed the last line as shown below. With that modification, it doesn't throw any error. [Here](https://colab.research.google.com/gist/jvishnuvardhan/338596f938330a20cd2bbcaae1a6e7af/untitled41.ipynb) is a gist for reference. Thanks!

```
# tf1_img_bl = tf.compat.v1.image.resize_bilinear(_input, [9, 1], align_corners=True,) # <-- problematic line
tf1_img_bl = tf.image.resize(_input, size=[9, 1], method='bilinear')
```
