### ISSUE TITLE
Installing tensorflow headers and libs for c++

### ISSUE THREAD

**Issue by harendracmaps** [tensorflow/tensorflow#48926]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): from source
- TensorFlow version: 2.3.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 
- CUDA/cuDNN version: 10.2/8.0.0
- GPU model and memory: 256-core NVIDIA Pascal™ GPU architecture with 256 NVIDIA CUDA cores

**Describe the problem**
I have successfully compiled the code on Tx2. how should I install it. I see  bazel-bin,  bazel-out,  bazel-tensorflow directory got created. I want to to install .so in /usr/local/lib and headers in /usr/local/include/tensorflow paths. Tried searchign goole but not enough info available.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
below is the command I tried running for compilation
sudo bazel --host_jvm_args=-Xmx1624m build --config=opt --config=monolithic --config=v2 --local_cpu_resources=2 //tensorflow:libtensorflow_cc.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

`Target //tensorflow:libtensorflow_cc.so up-to-date:                                                                         
  bazel-bin/tensorflow/libtensorflow_cc.so                                                                                           
INFO: Elapsed time: 34104.697s, Critical Path: 909.56s                                                         
INFO: 3868 processes: 3868 local.                                                                                                        INFO: Build completed successfully, 4367 total actions `

**Comment by sachinprasadhs** [comment]
@harendracmaps , Could you try again with the latest Tensorflow version 2.9.1 and let us know if that works for you. Thanks!
