### ISSUE TITLE
tensorflow go bazel visibility issue during bazel build

### ISSUE THREAD

**Issue by b-entangled** [tensorflow/tensorflow#48930]
I'm using tensorflow 1.4.0 and  we are using bazel to build our service. During bazel build I'm getting the following error,

`in go_library rule @com_github_tensorflow_tensorflow//tensorflow/go/op:op: target '@com_github_tensorflow_tensorflow//tensorflow/go:go' is not visible from target '@com_github_tensorflow_tensorflow//tensorflow/go/op:op'. Check the visibility declaration of the former target if you think the dependency is legitimate`

I observed that the issue is existing because default package visibility is private.
Is there any way to override this visibility behavior.

**Comment by tilakrayal** [comment]
@b-entangled ,

We see that you are using tf version 1.4, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

Thanks!

**Comment by b-entangled** [comment]
Thank you @tilakrayal .
We are creating git patches to change visibility. So I'm closing this issue.
