### ISSUE TITLE
Tflite from pytorch-onnx - seesaw facenet very slow loading.

### ISSUE THREAD

**Issue by vizakshat** [tensorflow/tensorflow#48932]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Xiaomi Redmi Note 5 Pro
- TensorFlow installed from (source or binary): pip install tensorflow==2.4.0
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TFlite loading time is approximately 10 seconds on Redmi Note 5 Pro. Pytorch for android is giving me lesser inference time and loading time on same mobile device.
```

Average (of three) loading and running time (in ms) on 2 mobile devices!

                               Inference Time                Model Loading Time
                               Mobile 1 | Mobile 2            Mobile 1   | Mobile 2
Resnet-34 130 mb TFlite         768          1328               7                10
Seesaw Facenet 35 mb Tflite     1669        3507               9332          15867
Seesaw Facenet 35 mb Torch       922          2173               2925          9468

```

**Describe the expected behavior**
TFlite loading time should be under 1 second as with other models like ResNets (34, 100 etc.)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
''' Model code and pre-trained files here https://github.com/cvtower/seesawfacenet_pytorch/blob/master/src/seesaw_models/DW_seesawFaceNetv2.py ''''

# IMPORTS
from DW_seesawFaceNetv2 import *
model = DW_seesawFaceNetv2(512)
model = torch.nn.DataParallel(model)
model.load_state_dict(torch.load('./trained-model.pth', map_location=torch.device('cpu') ))
model.eval();
model.to('cpu')

print(model(torch.zeros(1,3,112,112))) # for checking output after conversion
input_names = ['input'] # ["Conv2d-1"]
output_names = ['output'] # ["DW_seesawFaceNetv2-826"]
inputs = torch.randn((1, 3, 112, 112), device = torch.device('cpu')) #to('cpu')
dummy_input = Variable(inputs, requires_grad=True)

torch_out = torch.onnx.export(model.module.to('cpu'), dummy_input, 'output.onnx', export_params=True, verbose=True,
                              input_names=input_names, output_names=output_names,
                              opset_version = 12, do_constant_folding=False,
                              enable_onnx_checker=True))

# onnx.checker.check_model('./output.onnx') # to check the onnx conversion is correct

model = onnx.load("output.onnx")
onnx.helper.printable_graph(model.graph) # print onnx graph!

sess = nxrun.InferenceSession("./output.onnx")
ximg = np.zeros((1, 3, 112, 112)).astype(np.float32)

print("The model expects input shape: ", sess.get_inputs()[0].shape)
print("The shape of the Image is: ", ximg.shape)

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
% time result = sess.run(None, {input_name: ximg})
prob = result[0]
print(prob.ravel()) # to check if onnx outputs are same as torch model

# Load ONNX model
model_onnx = onnx.load('./output.onnx')

# conv./output_onnxto TensorFlow format
tf_rep = prepare(model_onnx)

# Export model as .pb file
tf_rep.export_graph('./onnx2tf')

tf_model = tf.saved_model.load('./onnx2tf')

converter = tf.lite.TFLiteConverter.from_saved_model('./onnx2tf') # path to the SavedModel directory
converter.allow_custom_ops = True

# I have not used the below options!
# converter.experimental_new_converter = True
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert() # takes a lot of time !!

# Save the model.
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```
------------------------------------------------------------------------------------------------------

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The tflite model is the same size as the torch model approximately, the inference time is also in a good range. But the loadin time is coming out to be 10 seconds on some mobile devices, and consistently more than other models like ResNets (34,100 etc)

A sample tflite model can be found here. There is a slight change in the number of blocks in original model and this model
https://drive.google.com/file/d/1S52OXU0q9aFyk_IwGybyJ85WH1hEq3Hn/view?usp=sharing

**Comment by thaink** [comment]
I run the profiler with your model, here is what I got base on op type:
Number of nodes executed: 1023
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	      857	    95.729	    68.921%	    68.921%	     0.000	      857
	               TRANSPOSE	       47	    11.771	     8.475%	    77.395%	     0.000	       47
	                LOGISTIC	       18	     7.517	     5.412%	    82.807%	     0.000	       18
	                   SPLIT	        5	     6.587	     4.742%	    87.550%	     0.000	        5
	                    MEAN	        3	     6.388	     4.599%	    92.149%	     0.000	        3
	           CONCATENATION	       11	     4.572	     3.292%	    95.441%	     0.000	       11
	                     MUL	       21	     2.764	     1.990%	    97.430%	     0.000	       21
	                     PAD	        7	     1.560	     1.123%	    98.554%	     0.000	        7
	                 RESHAPE	       14	     0.665	     0.479%	    99.032%	     0.000	       14
	                     ADD	       10	     0.570	     0.410%	    99.443%	     0.000	       10
	           STRIDED_SLICE	       14	     0.492	     0.354%	    99.797%	     0.000	       14
	             MAX_POOL_2D	        1	     0.212	     0.153%	    99.950%	     0.000	        1
	         FULLY_CONNECTED	        9	     0.057	     0.041%	    99.991%	     0.000	        9
	                     ABS	        3	     0.007	     0.005%	    99.996%	     0.000	        3
	                     SUB	        3	     0.006	     0.004%	   100.000%	     0.000	        3

**Comment by thaink** [comment]
Confirmed that the loading time is high. Nettron and visualize tool both need very long time to process this model.

For runtime, @vizakshat Did you run all of them with single-thread?
Since Conv_2D is the most expensive one in your model, you can try to use multi-thread or delegates like GPU with TFLite.
Additionally, you can try if quantize the model to int8 help the performance. A lot of Conv2d op has stride of (2, 2), if you can remove that, it will help speeding it up too.

**Comment by thaink** [comment]
@karimnosseir do you know if there is a way to analyze why it has such high loading time?

**Comment by vizakshat** [comment]
> Confirmed that the loading time is high. Nettron and visualize tool both need very long time to process this model.
> 
> For runtime, @vizakshat Did you run all of them with single-thread?
> Since Conv_2D is the most expensive one in your model, you can try to use multi-thread or delegates like GPU with TFLite.
> Additionally, you can try if quantize the model to int8 help the performance. A lot of Conv2d op has stride of (2, 2), if you can remove that, it will help speeding it up too.

Running time is not an issue, Yes, I am using multi threads and using delegates for running. But main problem still exists. I cant even see what's going on while loading. Any suggestions? @thaink @karimnosseir @rmothukuru

**Comment by karimnosseir** [comment]
I pushed a change that should enhance the loading time. Can you retry past this [commit](https://github.com/tensorflow/tensorflow/commit/7957cde003aeb3284393cf960c1f2e369d9a8ddb)

Thanks
