### ISSUE TITLE
How to add the dependency of TensorFlow 2.5.1-rc1 in my build.gradle file?

### ISSUE THREAD

**Issue by karundawadi** [tensorflow/tensorflow#48946]
Hey y'all I am working on an android application. The tensor flow version I was using had couple of error, so I switched to nightly builds. However, the latest nightly build does not support my application. I am trying to switch to a newer version of pre-release probably 2.5.1. The TF 2.5.1 can be found in the link https://github.com/tensorflow/tensorflow/tags. How do I add this version of TF to my application in the build.gradle file? 

Currently I am using 2.4.0 (stable release), and it looks like this: 
```
dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.firebase:firebase-auth:20.0.3'
    implementation 'com.google.firebase:firebase-database:19.7.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
    implementation "org.tensorflow:tensorflow-lite:2.4.0"
    implementation group:'org.tensorflow',name:'tensorflow-lite-select-tf-ops',version:'2.4.0'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.3'
//    implementation 'org.tensorflow:tensorflow-lite:2.6.0.dev20210427-nightly-SNAPSHOT'
//    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
    testImplementation 'junit:junit:4.+'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```
 I tried searching for the dependency on https://search.maven.org/, however I could not find the implementation.

**Comment by thaink** [comment]
"the latest nightly build does not support my application" What is the exact error you got here?
I think it is better to just fix the issue since there is no guarantee it will not happen in the new release.

The pre-release is not hosted on Maven. If if you want to give it a try, you can build it following https://www.tensorflow.org/lite/guide/build_android

**Comment by karundawadi** [comment]
I think this issue was resolved in another issue thank you.
