### ISSUE TITLE
TF 1.15.0 GPU, 1050ti & 1650 super, CUDNN 7.4.2 CUDA 10.0.130

### ISSUE THREAD

**Issue by CoderStone** [tensorflow/tensorflow#48940]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 1.15.0 gpu
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: conda, pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.130, 7.4.2
- GPU model and memory: 1050ti, 4gb, 1650 super, 4gb

**Describe the problem**
![image](https://user-images.githubusercontent.com/34324909/117342305-13b37e80-ae71-11eb-9eb5-16e74c168067.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installed CUDA and CUDNN. Used conda to create new env with python 3.7.9, attempted 3.7.10 and lower versions too
including 3.6
python
import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
This exact installation worked on my other computer, and I was using it to test out a completely new rig.

**Comment by ymodak** [comment]
What is make/model of your machine? Does it support AVX instruction sets?

**Comment by CoderStone** [comment]
Dual xeon x5690, DDR3 96GB 1333mhz RAM, dell r710

**Comment by CoderStone** [comment]
Ah it seems AVX isn't supported. However, I have ran previous tensorflow versions on it without issues.

**Comment by ymodak** [comment]
TF 1.6 and above pre built binaries require systems to support AVX instructions set.
See https://www.tensorflow.org/install/pip#hardware-requirements
Your other option is to build TF by source by enabling CPU optimization flags or you can switch to google colab to use TF-here all you need is internet connection and , google colab host latest stable TF version and you also utilize gpu,tpu accelerators as well.

**Comment by CoderStone** [comment]
Weird, I clearly remember running tensorflow gpu 1.14.0 without issues however.

**Comment by CoderStone** [comment]
Are there specific instructions for building without AVX for versions prior to 2.0?

**Comment by CoderStone** [comment]
Interesting.
![image](https://user-images.githubusercontent.com/34324909/117345914-1a43f500-ae75-11eb-9de3-edd8f33897e5.png)
I got it working... am very confused. Did not install any separate wheel.
I will have to check the version of tensorflow to confirm.

**Comment by CoderStone** [comment]
Never mind. Code doesn't run, crashed right after without any log.

**Comment by CoderStone** [comment]
I found a nice wheel that lets me even use a higher version of CUDA and CUDNN, so that would hopefully work! Thank you.

**Comment by ymodak** [comment]
Awesome. Will close this thread now that you have found a potential workaround. Feel free to reopen if have further questions. Thanks!

**Comment by CoderStone** [comment]
![image](https://user-images.githubusercontent.com/34324909/117359176-086a4e00-ae85-11eb-8749-6bf52558bf7e.png)
I am not sure what config I am supposed to use for SSE4.2.
