### ISSUE TITLE
Building tensorflow for SSE4.2, cannot find proper option in configure.py

### ISSUE THREAD

**Issue by CoderStone** [tensorflow/tensorflow#48942]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>![image](https://user-images.githubusercontent.com/34324909/117359506-80387880-ae85-11eb-9821-290f3ddb3ee0.png)
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.0
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: build
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): not sure
- CUDA/cuDNN version: 10, 7.4
- GPU model and memory: 4gb, 1050ti and 1650 super, 6.1,7.5

**Describe the problem**
Building for SSE4.2. No suggestion on how to specify in ./configure.py

**Provide the exact sequence of commands / steps that you executed before running into the problem**
![image](https://user-images.githubusercontent.com/34324909/117359540-8c243a80-ae85-11eb-87f6-96d12a76cc09.png)

**Any other info / logs**
![image](https://user-images.githubusercontent.com/34324909/117359577-96463900-ae85-11eb-9df2-ba5a2fd241f0.png)

**Comment by bhack** [comment]
These are the available options:
https://github.com/tensorflow/tensorflow/blob/4bdae6bb3b3a31de0e7adc111e6ed4a83c9341a0/.bazelrc#L23-L33

You can use the native one if the SSE4.2 is the same where you are compiling TF.

**Comment by CoderStone** [comment]
I'm on windows, and it's an SSE4.2 server. I meant in ./configure.py where it suggests /arch:AVX. Do you mean I can use /arc:native or just use /arc:AVX?

**Comment by bhack** [comment]
Generally I don't compile on win I think that these are the available ones https://docs.microsoft.com/it-it/cpp/build/reference/arch-x64?view=msvc-160

**Comment by CoderStone** [comment]
It might be /arch:SSE2, I'll post an update here for any future people that need to do this.

**Comment by CoderStone** [comment]
![image](https://user-images.githubusercontent.com/34324909/117366373-a7477800-ae8e-11eb-95df-73f9918e8237.png)
No idea what this error is.

**Comment by CoderStone** [comment]
Having issues once I downgraded to VS2017 from VS2019 build tools, since bazel wants you to use 2013 to 2017 and build fails. When downgrading, the above error occurs? no idea what to do.

**Comment by bhack** [comment]
Sorry but we don't support TF 1.x anymore.

**Comment by CoderStone** [comment]
That is a BS move to be fair... we should be able to compile older versions without issue. Forcing visual studio 2019 for compilation while bazel demands 2017 or below shouldn't be allowed.

**Comment by bhack** [comment]
TF on win is tested with Visual studio 2019 https://www.tensorflow.org/install/source_windows?hl=en#install_visual_c_build_tools_2019

What I meant is that we don't support in general tickets on TF 1.x as it is defacto EOL

**Comment by CoderStone** [comment]
I just mean that both bazel and the tester should use the SAME visual studio code version. I guess I'll try using a higher bazel version though that'd 100% fail.

**Comment by bhack** [comment]
> I just mean that both bazel and the tester should use the SAME visual studio code version. I guess I'll try using a higher bazel version though that'd 100% fail.

Have you found this in the master branch?

**Comment by CoderStone** [comment]
I believe so...

**Comment by bhack** [comment]
In your template I see `TensorFlow version: 1.15.0` we don't suypport TF 1.x please use a recent Tensorflow version.

**Comment by CoderStone** [comment]
I've tried four different branches including master.

**Comment by bhack** [comment]
> since bazel wants you to use 2013 to 2017 
In master,  where do you have evidence of this request?

**Comment by CoderStone** [comment]
Compiling again to reach the final error, give me a few. Although, I think that error came bec I was using the wrong version of bazel for tf2... so you are probably right. Still, not supporting earlier builds compilation is heavily frowned upon...

**Comment by CoderStone** [comment]
Any updates? bazel issue is still ongoing.

**Comment by bhack** [comment]
What Is the bazel issue with master?
