### ISSUE TITLE
[keras] [tensorboard] buggy behavior of keras x tensorboard

### ISSUE THREAD

**Issue by blackyang** [tensorflow/tensorflow#48943]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Any
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  v2.4.0-rc4-71-g582c8d236cb 2.4.0 and above (e.g. 2.5.0rc2)
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

in the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard?hl=en) there are examples of how to use `tf.summary.histogram(...)` without specifying `step` in either subclass model or functiona api model. However it is actually broken since the step will always be 0.

This is due to `# TODO(b/151339474): Fix deadlock when not using .value() here.`  (in both 2.4.0 and 2.5.0) in  `tensorflow/tensorflow/python/keras/callbacks.py`. If I use `step` instead of `step.value()`, then everything is as expected. This is also explained in here https://github.com/tensorflow/tensorflow/pull/36839/commits/fed7d1a1fd23ca166c256bec0f9085a218f943e3#diff-d2cf8455ca3dbffe505170fa5fe38ed5e0d5969bcacb3b92e0b638b6d3c20461R230-R233 

May I ask what's the deadlock issue is and when the fix can be expected? Thx.

Also, I think it's better to move [this function call](https://github.com/tensorflow/tensorflow/blob/053ad9ed9222c9f201028f7fc1bd66eb9bd6baf6/tensorflow/python/keras/engine/training.py#L853) from `Model` to `Tensorboard` callback, in case if someone wants to overwrite step in `Tensorboard` (e.g. using a global step that can be save & restore in a continuous daily training model)

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): Yes

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

a code snippet
```
import tensorflow as tf


def my_summary(x):
  tf.summary.scalar("mean_functional", tf.reduce_mean(x))
  return x

class MyLayer(tf.keras.layers.Layer):
    def __init(self):
        super(MyLayer, self).__init__()

    def call(self, inputs):
        tf.summary.scalar("mean_subclass", tf.reduce_mean(inputs))
        return inputs

inputs = tf.keras.Input(10)
x = tf.keras.layers.Dense(10)(inputs)
outputs = tf.keras.layers.Lambda(my_summary)(x)
outputs = MyLayer()(outputs)
model = tf.keras.Model(inputs, outputs)
model.compile('sgd', 'mse')

# Make sure to set `update_freq=N` to log a batch-level summary every N batches.
# In addition to any `tf.summary` contained in `Model.call`, metrics added in
# `Model.compile` will be logged every N batches.
tb_callback = tf.keras.callbacks.TensorBoard('./logs240', update_freq=1)

inputs_data = tf.ones([16, 10])
labels_data = tf.ones([16, 10])

dataset = (
    tf.data.Dataset.from_tensors(inputs_data)
    .map(
        lambda x: (
            inputs_data,
            labels_data,
            None,
        )
    ).repeat(100)
)
model.fit(dataset, callbacks=[tb_callback], epochs=5)

```

with and without `.value()` : 
![Screen Shot 2021-05-06 at 12 40 42 PM](https://user-images.githubusercontent.com/3350930/117361380-d0581080-ae6e-11eb-92cc-e9743b2d29b9.png)
![Screen Shot 2021-05-06 at 11 30 19 AM](https://user-images.githubusercontent.com/3350930/117361382-d1893d80-ae6e-11eb-86db-1b4ee51cfab2.png)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by blackyang** [comment]
cc @omalleyt12 @foxik

**Comment by saikumarchalla** [comment]
I can able to replicate the issue. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/257f7f54b590baf7bb6748aa4781cb6a/untitled.ipynb). Thanks!

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.6 .Please, find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/588eb5083e8d5a6f517eed72392f95c3/untitled.ipynb#scrollTo=q5pYuw07JvVj).Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
