### ISSUE TITLE
[TFLite] Fully Connected layers are not outputting accurate values with INT16 inputs of rank > 2

### ISSUE THREAD

**Issue by michaelbenayoun** [tensorflow/tensorflow#48959]
**Describe the current behavior**

The Fully connected layers outputs in a TensorFlow Lite model when using INT16 acitvations are completely off when the input rank is greater than 2, but totally correct when the rank is 2. 

It seems that the computation is somehow broken when the rank >= 3.

I was able to reproduce this in TensorFlow 2.5.0-rc2 and 2.6.0-dev.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
print(tf.__version__)

class MyModel(tf.keras.Model):
    def __init__(self, squeeze=False):
        super().__init__()
        self.squeeze = squeeze
        self.dense = tf.keras.layers.Dense(5)
    
    def call(self, x):
        if self.squeeze:
            x = tf.squeeze(x)
        return self.dense(x)
    
def representative_dataset():
    for _ in range(100):
        yield [tf.random.uniform(shape=[1, 30, 5])]
   
model = MyModel(squeeze=False)
model(tf.random.uniform(shape=[1, 30, 5]))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]

tflite_model = converter.convert()

input_ = tf.random.uniform(shape=[1, 30, 5])
output = model(input_)

interpreter = tf.lite.Interpreter(model_content=tflite_model)

interpreter.allocate_tensors()
interpreter.set_tensor(interpreter.get_input_details()[0]['index'], input_)
interpreter.invoke()
tflite_output = interpreter.get_tensor(interpreter.get_output_details()[0]['index'])

print(tf.reduce_max(tf.abs(output - tflite_output)))
```
When running this code, the output was : `tf.Tensor(2.128053, shape=(), dtype=float32)`.
I ran it multiple times and always got a value of that order.

In the next snippet, I am using the same model, and the same input shape, but I squeeze the input in the forward pass so that the Fully Connected layer effectively receives an input tensor of rank 2:

```python
model = MyModel(squeeze=True)
model(tf.random.uniform(shape=[1, 30, 5]))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]

tflite_model = converter.convert()

input_ = tf.random.uniform(shape=[1, 30, 5])
output = model(input_)

interpreter = tf.lite.Interpreter(model_content=tflite_model)

interpreter.allocate_tensors()
interpreter.set_tensor(interpreter.get_input_details()[0]['index'], input_)
interpreter.invoke()
tflite_output = interpreter.get_tensor(interpreter.get_output_details()[0]['index'])

print(tf.reduce_max(tf.abs(output - tflite_output)))
```
This time the output was: `tf.Tensor(0.0044746697, shape=(), dtype=float32)`

**Comment by abattery** [comment]
@liyunlu0618 could you triage this issue?

**Comment by jianlijianli** [comment]
@Tessil ,

Hi Tessil, is this a known limitation?

**Comment by Tessil** [comment]
@jianlijianli  No, it seems it's also a problem with the reference int8 kernel. Using `experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF` with int8 will produce the same kind of error.

Applying the same `batches` and `output_depth` calculations as the [reference float kernel](https://github.com/tensorflow/tensorflow/blob/8e9ff73ded8f1f7a3de47378e9adba92307df5ab/tensorflow/lite/kernels/internal/reference/fully_connected.h#L34) to both the [int8 and int16 reference kernels](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/integer_ops/fully_connected.h) seems to solve the problem.

**Comment by jianlijianli** [comment]
Thanks Tessil. Confirmed that this happens to int8 reference kernel as well but int8 optimized kernel is OK.

Just to avoid duplicated work, do you plan to fix the issue (since it happens to 16x8 as well)? Otherwise, I can work on it.

**Comment by Tessil** [comment]
I can eventually work on a fix but as I will not be able to really work on it until the end of next week it'll be faster to leave it to you if possible.

**Comment by jianlijianli** [comment]
Thanks @Tessil,

There has been some changes in the tflite conversion workflow and squeeze logic is getting update, and I think https://github.com/tensorflow/tensorflow/issues/48959#issuecomment-883321475 is outdated. This is my current observation: for int8 quantization, int8 kernel (reference) works fine for both "squeeze = True" or "squeeze = False". For 16x8 quantization, "squeeze = True" works but "squeeze = False" fails during runtime for multiplier being too small.

Please take a look if you are interested. I am working on a fix.

Michael, I suppose you are not actually blocked by this issue, right?

**Comment by michaelbenayoun** [comment]
No, I found a workaround for what I was doing, no worries!

**Comment by pjpratik** [comment]
The session crashes when 16x8 quantization is used on TF >2.6 with both squeeze = True and False.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
