### ISSUE TITLE
Sanity Tests & Unity Test checking fails 

### ISSUE THREAD

**Issue by ashutosh1919** [tensorflow/tensorflow#48954]
Commands:
- `tensorflow/tools/ci_build/ci_build.sh CPU tensorflow/tools/ci_build/ci_sanity.sh`
- `tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/...`
While running above two commands, the test fails and stop because of pip package installation error as shown below.
```
2021-05-07 06:26:49 (1.75 MB/s) - 'get-pip.py' saved [1937346/1937346]

/install/install_pip_packages.sh: line 21: python3.6: command not found
```

**Comment by bhack** [comment]
Yes it is a known bug. 
See https://github.com/tensorflow/tensorflow/issues/47989 and the PR at https://github.com/tensorflow/tensorflow/pull/48371 
/cc @theadactyl @angerson

**Comment by ymodak** [comment]
Closing this issue since its being tracked already. Thanks!
