### ISSUE TITLE
recipe for target 'CMakeFiles/tensorflow-lite.dir/all' failed     issue while cross-compile tflite.

### ISSUE THREAD

**Issue by migod35** [tensorflow/tensorflow#48963]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Linux Ubuntu 16:

- TensorFlow  Lite version--Latest:
- Python version:3.7

**Describe the problem**

Hi I am new to tensorflow. I try to cross-compile and generate the python wheel for  the tensorflow-lite for aarch64. i followed the steps which given in the official tensorflow-lite website. https://www.tensorflow.org/lite/guide/build_cmake_pip. But I cannot able to cross compile it. 

The steps which I follow:
1. Git clone the tensorflow source code.
2. Execute the below command from the tensorflow src folder.

**tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh aarch64**
 
Then the program execute with some following error.

**Any other info / logs**

CMakeFiles/Makefile2:1139: recipe for target 'CMakeFiles/tensorflow-lite.dir/all' failed
make[2]: *** [CMakeFiles/tensorflow-lite.dir/all] Error 2
make[2]: Leaving directory '/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.7/cmake_build'
CMakeFiles/Makefile2:1247: recipe for target 'CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule' failed
make[1]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule] Error 2
make[1]: Leaving directory '/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.7/cmake_build'
Makefile:215: recipe for target '_pywrap_tensorflow_interpreter_wrapper' failed
make: *** [_pywrap_tensorflow_interpreter_wrapper] Error 2

**Comment by thaink** [comment]
@terryheo Could you take a look?

**Comment by terryheo** [comment]
```
CMakeFiles/tensorflow-lite.dir/build.make:1157: recipe for target 'CMakeFiles/tensorflow-lite.dir/kernels/lstm_eval.cc.o' failed
aarch64-linux-gnu-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
Thanks for the information. It seems that your Docker has OOM issue.
What's the host OS? You'd better assign more memory to your Docker.

**Comment by migod35** [comment]
@terryheo Thank you for your guidence! My host OS  is Ubuntu 18, And also Please guide me to increase the memory of the Docker while cross-compiling.

**Comment by migod35** [comment]
@terryheo Also I remember one thing  I was able to cross-compile the tflite without any error at the one week before.

**Comment by brunovollmer** [comment]
@migod35 How did you solve the problem?
