### ISSUE TITLE
Grappler does not fuse kernels in simple GELU implementation

### ISSUE THREAD

**Issue by dannyfriar** [tensorflow/tensorflow#48964]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.6
- CUDA/cuDNN version: CUDA 10.1
- GPU model and memory: V100 16GB

**Describe the current behavior**

Running the GELU example below in both graph and eager mode seems to result in the same kernel GPU kernel launches. Using nvprof and NVIDIA Visual Profiler reveals 5 kernel launches in each case:

3x eigen::internal::scalar_product_op
1x eigen::internal::1x scalar_pow_op
1x eigen::internal::1x scalar_sum_op

**Describe the expected behavior**

From reading https://www.tensorflow.org/guide/graph_optimization and the Stanford slides here http://web.stanford.edu/class/cs245/slides/TFGraphOptimizationsStanford.pdf, I was expecting Grappler to fuse some of these operations in the graph mode case.

It would be great to understand either why this does not happen in this case and exactly what kinds of operations can be fused with Grappler, or alternatively what else needs to be done to achieve this behaviour with Grappler.

**Standalone code to reproduce the issue**

```
import timeit
import math
import contextlib
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"

import tensorflow as tf
import cupy


@contextlib.contextmanager
def options(options):
    old_opts = tf.config.optimizer.get_experimental_options()
    tf.config.optimizer.set_experimental_options(options)
    try:
        yield
    finally:
        tf.config.optimizer.set_experimental_options(old_opts)


def _gelu(x):
    constant = tf.constant(0.5 * (1 + math.tanh(math.sqrt(2 / math.pi))))
    x_cubed = tf.pow(x, 3, name="x_cubed")
    return tf.multiply(constant * x, tf.add(x, 0.044715 * x_cubed), name="gelu")


def gelu_graph(x):
    @tf.function
    def gelu(x):
        return _gelu(x)

    return gelu(x)


def gelu_eager(x):
    def gelu(x):
        return _gelu(x)

    return gelu(x)


# with options({'min_graph_nodes': 1}):
print(tf.config.optimizer.get_experimental_options())

x = tf.random.uniform((int(1e6), 128))

# with cupy.cuda.profile(): 
print("Graph execution:", timeit.timeit(lambda: gelu_graph(x), number=100), "s")

print("Eager execution:", timeit.timeit(lambda: gelu_eager(x), number=100), "s")
```

**Comment by bhack** [comment]
Can you check what fusion we have with TF Gelu op https://github.com/tensorflow/tensorflow/blob/c097d1f82e237357025fee054adde6adc8e7a760/tensorflow/python/ops/nn_ops.py#L3626-L3667

**Comment by dannyfriar** [comment]
> Can you check what fusion we have with TF Gelu op
> 
> https://github.com/tensorflow/tensorflow/blob/c097d1f82e237357025fee054adde6adc8e7a760/tensorflow/python/ops/nn_ops.py#L3626-L3667

The implementation is a bit different to what I have above but it looks like this still results in 5 kernel launches (2 products, 1 sum, 1 quotient and 1 corresponding to `tf.math.erf`).

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7c476afdf66d5fa0f8ecd639e58558c1/untitled234.ipynb) ..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
