### ISSUE TITLE
save and load specific keras/tensorflow layers

### ISSUE THREAD

**Issue by rohanshingade** [tensorflow/tensorflow#48973]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
extract layer of one model with weights and use in another model. For example, using an embedding layer weights of one transformer model in another transformer model. Compared to glove embeddings and word2vec embeddings, it's difficult to map the embedding weights of a transformer.

**Will this change the current api? How?**
Most probably no.

**Who will benefit with this feature?**
those who need to export only embeddings layer (or any other layer) and use in another model.

**Any Other info.**

**Comment by bhack** [comment]
Do you meant something like https://keras.io/examples/nlp/pretrained_word_embeddings/ ?

**Comment by rohanshingade** [comment]
Closing this. exported the weights in pickle file. Thanks @bhack
