### ISSUE TITLE
python': double free or corruption (!prev): 0x0000556f555937e0 ***

### ISSUE THREAD

**Issue by ygliu-hub** [tensorflow/tensorflow#48987]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](INFO:tensorflow:Reading data files from /home/lyg/data/tmp/t2t/data/protein_specific_ligand_generation-train*
I0507 22:41:25.676374 140279178368768 problem.py:653] Reading data files from /home/lyg/data/tmp/t2t/data/protein_specific_ligand_generation-train*
*** Error in `/home/lyg/anaconda3/envs/tf/bin/python': double free or corruption (!prev): 0x0000556f555937e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x38f107956e)[0x7f954a23756e]
/lib64/libc.so.6(+0x38f1079d0f)[0x7f954a237d0f]
/lib64/ld-linux-x86-64.so.2(_dl_deallocate_tls+0x57)[0x7f954a7a1b37]
/lib64/libpthread.so.0(+0x38f1806266)[0x7f954a579266]
/lib64/libpthread.so.0(+0x38f180638a)[0x7f954a57938a]
/lib64/libpthread.so.0(pthread_join+0xc4)[0x7f954a57b264]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x10b7c01)[0x7f94cdc97c01]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZN10tensorflow6thread10ThreadPoolD1Ev+0x204)[0x7f94cdcacfd4]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZN10tensorflow8internal16GetMatchingPathsEPNS_10FileSystemEPNS_3EnvERKSsPSt6vectorISsSaISsEE+0x641)[0x7f94cdcaa061]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZN10tensorflow15PosixFileSystem16GetMatchingPathsERKSsPSt6vectorISsSaISsEE+0x30)[0x7f94cdc9d120]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.so.2(_ZN10tensorflow3Env16GetMatchingPathsERKSsPSt6vectorISsSaISsEE+0x40)[0x7f94cdca07e0]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/_pywrap_file_io.so(+0x2118e)[0x7f94c9f8318e]
/home/lyg/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/_pywrap_file_io.so(+0x1cb89)[0x7f94c9f7eb89]
/home/lyg/anaconda3/envs/tf/bin/python(_PyMethodDef_RawFastCallKeywords+0x264)[0x556f54be68b4]
/home/lyg/anaconda3/envs/tf/bin/python(_PyCFunction_FastCallKeywords+0x21)[0x556f54be69d1]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x4e0a)[0x556f54c52e5a]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x416)[0x556f54c4e466]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x4a99)[0x556f54c52ae9]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x4a99)[0x556f54c52ae9]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0xc30)[0x556f54b96640]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallDict+0x3ff)[0x556f54b9701f]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x1e47)[0x556f54c4fe97]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0x5da)[0x556f54b95fea]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallDict+0x3ff)[0x556f54b9701f]
/home/lyg/anaconda3/envs/tf/bin/python(_PyObject_Call_Prepend+0x63)[0x556f54bb57a3]
/home/lyg/anaconda3/envs/tf/bin/python(PyObject_Call+0x6e)[0x556f54ba83ae]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x1e47)[0x556f54c4fe97]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x556f54b95d09]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0x387)[0x556f54be60b7]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x14e9)[0x556f54c4f539]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0xc30)[0x556f54b96640]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallDict+0x3ff)[0x556f54b9701f]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x1e47)[0x556f54c4fe97]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x556f54b95d09]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0x325)[0x556f54be6055]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x556f54b95d09]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0x387)[0x556f54be60b7]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x14e9)[0x556f54c4f539]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0xc30)[0x556f54b96640]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0x387)[0x556f54be60b7]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x6a0)[0x556f54c4e6f0]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x4a99)[0x556f54c52ae9]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalCodeWithName+0x2f9)[0x556f54b95d09]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0x325)[0x556f54be6055]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x416)[0x556f54c4e466]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x416)[0x556f54c4e466]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]
/home/lyg/anaconda3/envs/tf/bin/python(_PyEval_EvalFrameDefault+0x4a99)[0x556f54c52ae9]
/home/lyg/anaconda3/envs/tf/bin/python(_PyFunction_FastCallKeywords+0xfb)[0x556f54be5e2b]https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
@ygliu-hub  Seems the issue is more related to this [repo](https://github.com/tensorflow/tensor2tensor/issues). Please submit a new issue here.Thanks!
