### ISSUE TITLE
num_parallel_calls= for tf.data map()

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#48999]
I was playing with different numbers for num_parallel_calls= for map(), however I can hardly get CPU usage above 400%. I am on a DGX-1, so there are 40 CPU cores. I used a very big prefetch number. Ideally if CPU is saturated, I should see ~4000% usage. Just wondering if I need to configure other parameters. I don't know how TF implements num_parallel_calls. I tried setting OMP_NUM_THREADS=40, but this setting doesn't work.

**Comment by tilakrayal** [comment]
@llodds ,

In order to expedite the trouble-shooting process, could you please provide the Tensorflow version, complete code and dataset to reproduce the issue reported here.

Thanks!

**Comment by llodds** [comment]
@tilakrayal 
You can close the issue. If I am training with bigger batch/model size, I saw CPU usage grows over %1000.

**Comment by tilakrayal** [comment]
@llodds ,

Please feel free to move this issue to closed status if the issue is resolved.Thanks!
