### ISSUE TITLE
Error in TF.pad API docs

### ISSUE THREAD

**Issue by infinitisp** [tensorflow/tensorflow#490]
Please note the following error in tf.pad in "array_ops.md":

Example 1 currently reads as follows:

    # 't' is [[1, 1], [2, 2]]
    # 'paddings' is [[1, 1]], [2, 2]] ##This is not a valid tensor
    # rank of 't' is 2
    pad(t, paddings) ==> 
         [[0, 0, 0, 0, 0] ##This is not the correct output
          [0, 0, 0, 0, 0]
          [0, 1, 1, 0, 0]
         [[0, 2, 2, 0, 0]
          [0, 0, 0, 0, 0]]

It can be fixed as follows:

    # 't' is [[1, 1], [2, 2]]
    # 'paddings' is [[1, 1], [2, 2]]
    # rank of 't' is 2
    pad(t, paddings) ==> 
        [[0, 0, 0, 0, 0, 0]
         [0, 0, 1, 1, 0, 0]
         [0, 0, 2, 2, 0, 0]
         [0, 0, 0, 0, 0, 0]]

**Comment by mrry** [comment]
Thanks for letting us know. This is now fixed upstream, and should be released soon.
