### ISSUE TITLE
MobileBert inference with TFlite GPU delegate

### ISSUE THREAD

**Issue by Mo-Abdelgawad** [tensorflow/tensorflow#49012]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version: (2.6.0)
- Are you willing to contribute it: (No)

**Describe the feature and the current behavior/state.**

**Requested feature**: Add support for [mobilebert](https://tfhub.dev/tensorflow/lite-model/mobilebert/1/metadata/1) model/operations in [TFlite GPU delegate](https://www.tensorflow.org/lite/performance/gpu)

**Current behaviour**: I'm trying to use the TFlite GPU delegate for mobilbert TFlite model inference. I'm using [TFlite benchmark tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark), with the GPU delegate enabled, to run the model. The inference automatically goes to the CPU backend with the following Info/Error:

```
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: tensorflow/lite/core/subgraph.cc:1169 node_index >= 0 was not true.
ERROR: Couldn't get node and registration info for op: -1793924896

INFO: Created 0 GPU delegate kernels.
Though GPU delegate is explicitly applied, the model graph will not be executed by the delegate.

```
and then continues to run on the CPU.

I'm not sure what this error means. I know that the TFlite GPU delegate only supports a handful of [models and operations](https://www.tensorflow.org/lite/performance/gpu#supported_models_and_ops). So I guess it is a support issue. However, the error does not seem to me a support issue because, I should have just received a warning as described [here](https://www.tensorflow.org/lite/performance/gpu#non-supported_models_and_ops) reporting the unsupported Ops.

I could not understand what node_index means and what makes it positive or negative.

Since the supported models runs perfectly with no errors , I speculated that it's a support issue.

**Will this change the current api? How?**
Not sure

**Who will benefit with this feature?**
Who is interested in accelerating BERT on mobile GPUs

**Any Other info.**

**Comment by abattery** [comment]
@renjie-liu could you take a look?

**Comment by renjie-liu** [comment]
Please use the gpu version here: https://github.com/mlcommons/mobile_models/blob/main/v0_7/tflite/mobilebert_float_384_gpu.tflite

Thanks

**Comment by Mo-Abdelgawad** [comment]
Thanks for the link.  Do you know where I can find the source training code (that trains mobilebert for gpu)? I couldn't find it here https://github.com/mlcommons/mobile_models/tree/main/v0_7/tflite. 

Much appreciated.

**Comment by renjie-liu** [comment]
The training code is the same as the other models except the conversion is a little bit different (the conversion tool is not open-sourced yet, will do later)

**Comment by Mo-Abdelgawad** [comment]
@renjie-liu Great to know you will open-source it, could you please just notify me when you do? I need to experiment with different mobilebert configurations and that will help a lot. 

Also it seems that the gpu model **still has operations that are not supported by the TFlite GPU delegate**  (CAST, GATHER, MUL, RESHAPE, UNPACK), and the model gets split on both CPU and the GPU. 

**Here is the output when I run it with  TFlite GPU delegate with OpenCL backend**:

```
STARTING!
Log parameter values verbosely: [0]
Min num runs: [1]
**Graph**: [mobilebert_float_384_gpu.tflite]
**Use gpu**: [1]
Loaded model mobilebert_float_384_gpu.tflite
**INFO**: Created TensorFlow Lite delegate for GPU.
**ERROR**: Following operations are not supported by GPU delegate:
CAST: Not supported cast case
GATHER: Operation is not supported.
MUL: MUL requires one tensor that not less than second in all dimensions.
RESHAPE: OP is supported, but tensor type isn't matched!
UNPACK: Operation is not supported.
**2661 operations will run on the GPU, and the remaining 81 operations will run on the CPU.**
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Explicitly applied GPU delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
The input model file size (MB): 100.239
Initialized session in 2491.9ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=2 first=434022 curr=247839 min=247839 max=434022 avg=340930 std=93091
```
Do you get the same when you run it?

Thanks.
