### ISSUE TITLE
@mitramir55 please open a new issue, fill in issue template and provide minimal code to reproduce. It's likely you have some dependency issue / some wrong version of TF installed. `pip list` should also help in identifying the issue

### ISSUE THREAD

**Issue by 99003731** [tensorflow/tensorflow#49015]
@mitramir55 please open a new issue, fill in the issue template and provide minimal code to reproduce. It's likely you have some dependency issue / some wrong version of TF installed. `pip list` should also help in identifying the issue

_Originally posted by @mihaimaruseac in https://github.com/tensorflow/tensorflow/issues/31315#issuecomment-643346367_

I have checked the version too still the same issue. Attribute error: TensorFlow has no attribute

**Comment by saikumarchalla** [comment]
@99003731 Could you please elaborate your query. Please provide the  standalone code/ colab to reproduce the issue at our end and share  error logs as well.  Also, let us know the TF version you are working on. Thanks!

**Comment by mihaimaruseac** [comment]
Issue template was not filled. Please fill in issue template, provide minimal code to reproduce the issue and give details. Otherwise, we are left to guess what could be the issue you are seeing and this is both not a good use of time and also will not lead to a quick solve of your issue.

The more details you provide, the faster it will be to provide a fix.

**Comment by 99003731** [comment]
code: label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
my error:File "C:\Users\<my path>\utils\label_map_util.py", line 137, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
AttributeError: module 'tensorflow' has no attribute 'gfile'

tensorflow version 2.3.0
these are the details is this okay or more description/details you require

**Comment by saikumarchalla** [comment]
@99003731  If possible, Could you please provide the complete reproducible code so that we can debug into issue and provide the response in a better way. Thanks!

**Comment by 99003731** [comment]
@saikumarchalla  here is the code you can debug

import glob
import math
import cv2
import numpy as np
import tensorflow.compat.v1 as tf
from PIL import Image
from utils import label_map_util
from utils import visualization_utils as vis_util


PATH_TO_LABELS = 'label_map_Thread.pbtxt'
NUM_CLASSES = 1
# Loading label map
# Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(
    label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

**Comment by sachinprasadhs** [comment]
@99003731  tf.gfile has been moved under tf.io. 
Instead of  `tf.gfile.GFile(path, 'r')` you can use `tf.io.gfile.GFile(name, mode='r')`. 
You can find more info about this from the document [here](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile).
