### ISSUE TITLE
tflite int8 12x times slower than float32

### ISSUE THREAD

**Issue by rossbucky** [tensorflow/tensorflow#49011]
Please check this colab to reproduce for huggingface gpt2 model

https://colab.research.google.com/drive/1DNTPR_GgidU8Jve0zoDI1MfoqWQ0L06n?usp=sharing

**Comment by pjpratik** [comment]
Hi @rossbucky I was checking if the issue still exists.

I have run the code on TF Nightly 2.13.0-dev20230308 and observed that tf_float32 for p50 has taken 94.42 percentile where as tf_int8 for p50 has taken 74.0089 which seems to be faster.

 Please find the gist [here](https://colab.research.google.com/gist/pjpratik/4da0488c96d8dfdea71f10a67f3799c3/49011.ipynb).

Thanks.
