### ISSUE TITLE
Problems when using a100 graphics card

### ISSUE THREAD

**Issue by Foreist** [tensorflow/tensorflow#49022]
Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

Is there any way to install tensorflow directly when using a100 server?
Do I have to use the docker image provided by nvidia?
Installation was done with pip tensorflow-gpu.

**Comment by saikumarchalla** [comment]
@Foreist Could you please be more specific about the missing libraries. Are you able to install tensorflow-gpu with pip package successfully? If not, Please provide the error logs.

Also, Provide the TF version so that it helps us to  figure out the issue.
