### ISSUE TITLE
why with mirroredStrategy GPUs have different memory footprint?

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#49027]
With data parallelization, I was expecting all GPUs will have the same memory footprint for a training model with GLOBAL_BATCH_SIZE divisible by #GPUs. But why I am seeing different memory footprint ranging from 5.2GB to 9.2G per GPU? I am on a DGX-1 and training a GAN model with GLOBAL_BATCH_SIZE=32 and 8 V100 GPUs. The model is quite small though (128x128)

After more testings, it seems that TF allocates a constant memory (~4GB) regardless of the model size and prefetch() causes this random memory footprint. Can someone help to explain TF memory model? 

<img width="890" alt="Screen Shot 2021-05-09 at 3 28 26 PM" src="https://user-images.githubusercontent.com/3358807/117586048-65f7d800-b0db-11eb-8648-ed342320ea16.png">

**Comment by llodds** [comment]
@tilakrayal 
```bash
In [3]: print(tf.version.VERSION)
2.4.1
```

**Comment by llodds** [comment]
@tilakrayal 
I did another round of testing and found the issue only occurs when I am training with a small model, and the issue appears randomly. I will report back when I see more consistent behavior.

**Comment by tilakrayal** [comment]
@llodds ,

Please feel free to move this issue to closed status if the issue is resolved.Thanks!
