### ISSUE TITLE
tf_uniform_replay_buffer Warning

### ISSUE THREAD

**Issue by weiT1993** [tensorflow/tensorflow#49028]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Springdale Linux 7.9 (Verona)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.9.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.3
- GPU model and memory: Tesla P100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TF uniform buffer raises error.

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): no

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import numpy as np

from tf_agents import specs
from tf_agents.agents.dqn import dqn_agent
from tf_agents.drivers import dynamic_step_driver
from tf_agents.environments import suite_gym
from tf_agents.environments import tf_py_environment
from tf_agents.networks import q_network
from tf_agents.replay_buffers import py_uniform_replay_buffer
from tf_agents.replay_buffers import tf_uniform_replay_buffer
from tf_agents.specs import tensor_spec
from tf_agents.trajectories import time_step

tf.compat.v1.enable_v2_behavior()

data_spec =  (
        tf.TensorSpec([3], tf.float32, 'action'),
        (
            tf.TensorSpec([5], tf.float32, 'lidar'),
            tf.TensorSpec([3, 2], tf.float32, 'camera')
        )
)

batch_size = 1
max_length = 1000

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec,
    batch_size=batch_size,
    max_length=max_length)

action = tf.constant(1 * np.ones(
    data_spec[0].shape.as_list(), dtype=np.float32))
lidar = tf.constant(
    2 * np.ones(data_spec[1][0].shape.as_list(), dtype=np.float32))
camera = tf.constant(
    3 * np.ones(data_spec[1][1].shape.as_list(), dtype=np.float32))

values = (action, (lidar, camera))
values_batched = tf.nest.map_structure(lambda t: tf.stack([t] * batch_size),
                                       values)

for _ in range(5):
    replay_buffer.add_batch(values_batched)

dataset = replay_buffer.as_dataset(sample_batch_size=4,single_deterministic_pass=False)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
[bug_report.txt](https://github.com/tensorflow/tensorflow/files/6448373/bug_report.txt)

**Comment by ymodak** [comment]
@weiT1993 The deprecation warning message you see in your `error.txt` is mentioned in the docs.
`Warning: THIS FUNCTION IS DEPRECATED. It will be removed in a future version. Instructions for updating: Use as_dataset(..., single_deterministic_pass=True) instead.`
See https://www.tensorflow.org/agents/api_docs/python/tf_agents/replay_buffers/replay_buffer/ReplayBuffer

**Comment by weiT1993** [comment]
@ymodak Thanks. I am aware of the deprecation for `get_next`. But the code snippet (taken from the documentation [here](https://www.tensorflow.org/agents/tutorials/5_replay_buffers_tutorial)) is not calling `get_next`. Does the deprecation warning pop up regardless?

**Comment by ymodak** [comment]
On debugging further I see that calling `TFUniformReplayBuffer` under the hood
```python
replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec,
    batch_size=batch_size,
    max_length=max_length)
```
hits `get_next method` defined at https://github.com/tensorflow/agents/blob/29daabcc11b277a914f6b848d44c30b4aabbf659/tf_agents/replay_buffers/replay_buffer.py#L85 which has a deprecation warning.

**Comment by weiT1993** [comment]
Thanks. I will just ignore the warning now.
