### ISSUE TITLE
Variable scope is created repeatedly

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#49021]
tensorflow version: 1.15.0
python version: 3.6.12
Variable scope is created repeatedly using tf.variable_scope as follows:
```python
with tf.variable_scope("my_variable_scope", reuse=tf.AUTO_REUSE):
    v = tf.get_variable("v", [1])
    print(v.name)
    w = tf.get_variable("w", [1])
    print(w.name)
    b = w + 1
    c = w + 1
    print(b.name, c.name)

with tf.variable_scope("my_variable_scope", reuse=tf.AUTO_REUSE) as scope:
    scope.reuse_variables()
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)

with tf.variable_scope("my_variable_scope", reuse=tf.AUTO_REUSE) as scope:
    scope.reuse_variables()
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)
```
Here comes the output:
```bash
my_variable_scope/v:0
my_variable_scope/w:0
my_variable_scope/add:0 my_variable_scope/add_1:0
my_variable_scope/v:0
my_variable_scope_1/add:0
my_variable_scope/v:0
my_variable_scope_2/add:0
```
So, why my_variable_scope, my_variable_scope_1, my_variable_scope_2 are created for a. Thanks for your help.

**Comment by daugraph** [comment]
it seems `variable_scope ` only share `variables` not `ops`

**Comment by daugraph** [comment]
If you want reenter a premade variable scope, you can try use `auxiliary_name_scope` with `tf.name_scope()` as follows:
```
with tf.variable_scope("my_variable_scope", reuse=tf.AUTO_REUSE) as scope1:
  print(tf.get_variable_scope())
  v = tf.get_variable("v", [1])
  print(v.name)
  w = tf.get_variable("w", [1])
  print(w.name)
  b = w + 1
  c = w + 1
  print(b.name, c.name)

with tf.variable_scope(scope1, auxiliary_name_scope=False) as scope2:
  with tf.name_scope(scope1.original_name_scope):
    print(tf.get_variable_scope())
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)

with tf.variable_scope(scope1, auxiliary_name_scope=False) as scope3:
  with tf.name_scope(scope1.original_name_scope):
    print(tf.get_variable_scope())
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)
```

**Comment by daugraph** [comment]
If you want reenter a premade variable scope, you can try use `auxiliary_name_scope=False` with `tf.name_scope()` as follows:

```
with tf.variable_scope("my_variable_scope", reuse=tf.AUTO_REUSE) as scope1:
  v = tf.get_variable("v", [1])
  print(v.name)
  w = tf.get_variable("w", [1])
  print(w.name)
  b = w + 1
  c = w + 1
  print(b.name, c.name)

with tf.variable_scope(scope1, auxiliary_name_scope=False) as scope2:
  with tf.name_scope(scope1.original_name_scope):
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)

with tf.variable_scope(scope1, auxiliary_name_scope=False) as scope3:
  with tf.name_scope(scope1.original_name_scope):
    v1 = tf.get_variable("v")
    a = v1 + 1
    print(v1.name)
    print(a.name)
```
Outputs:
```
my_variable_scope/v:0
my_variable_scope/w:0
my_variable_scope/add:0 my_variable_scope/add_1:0
my_variable_scope/v:0
my_variable_scope/add_2:0
my_variable_scope/v:0
my_variable_scope/add_3:0
```

**Comment by sachinprasadhs** [comment]
@lizhen2017 Did you try the solution provided by @daugraph [here](https://github.com/tensorflow/tensorflow/issues/49021#issuecomment-835840899). You can also go through the [document](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) for more info.

**Comment by lizhen2017** [comment]
> @lizhen2017 Did you try the solution provided by @daugraph [here](https://github.com/tensorflow/tensorflow/issues/49021#issuecomment-835840899). You can also go through the [document](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) for more info.

Yes, I've tried. And also tried https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/ops/variable_scope.py#L2104, both have succeeded.
But if the variable scope can't be known in advance, auxiliary_name_scope should be judged.

**Comment by lizhen2017** [comment]
> @lizhen2017 Did you try the solution provided by @daugraph [here](https://github.com/tensorflow/tensorflow/issues/49021#issuecomment-835840899). You can also go through the [document](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) for more info.

I've triedy

**Comment by lizhen2017** [comment]
> > @lizhen2017 Did you try the solution provided by @daugraph [here](https://github.com/tensorflow/tensorflow/issues/49021#issuecomment-835840899). You can also go through the [document](https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) for more info.
> 
> Yes, I've tried. And also tried https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/ops/variable_scope.py#L2104, both have succeeded.
> But if the variable scope can't be known in advance, auxiliary_name_scope should be judged.

I've tried with loops, scope variable must be reused, below I used a dict to store it with scope name as the key. And Would you please share a simpler code?
```python
scope = 'foo'
scopes = {}
for i in range(3):
    auxiliary_name_scope = True
    reuse=tf.AUTO_REUSE
    if scope in scopes:
        reuse = None
        auxiliary_name_scope = False
    else:
        scopes[scope] = tf.variable_scope(scope, auxiliary_name_scope=auxiliary_name_scope, reuse=tf.AUTO_REUSE)
    with scopes[scope] as vs:
        print(scope, auxiliary_name_scope, vs.original_name_scope, reuse)
        with tf.name_scope(vs.original_name_scope):
            v1 = tf.get_variable("v", [1])
            a = v1 + 1
            print(v1.name)
            print(a.name)
```
