### ISSUE TITLE
DSP(Hexagon) delegate run tensorflow-lite C++ example label_image more slowly than CPU

### ISSUE THREAD

**Issue by limdlh** [tensorflow/tensorflow#49047]
I compile tensorflow-lite and the example label_image in tensorflow-lite source code success,
I did run with delegates of DSP(Hexagon) and CPU by ADB with running comands:
CPU: ./label_image -m tflite_model_int8.tflite -i grace_hopper.bmp -l labels.txt 1
DSP: ./label_image -m tflite_model_int8.tflite -i grace_hopper.bmp -l labels.txt -j 1
Both seems runs success, but average time or DSP: 60.00 ms, average time or CPU : 40.00 ms
Is it right? DSP is more slow than CPU for 50% ?
If Not, what should I do to make DSP(Hexagon) runs at good performance?

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9.0
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: BBK S5d (SOC: Qualcomm Snapdragon 660)
TensorFlow installed from (source or binary): build by myself
TensorFlow version (use command below): tensorflow-2.4.1
Python version: Python 3.8.5
Bazel version (if compiling from source): 3.1.0
GCC/Compiler version (if compiling from source): g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CUDA/cuDNN version:
GPU model and memory:
SOC: Qualcomm Snapdragon 660

Could anyone help? Or give a advice?
Thank you so much~

**Comment by karimnosseir** [comment]
Hi,
Can you share the model you're using ? Also, the log should have how many ops are delegated, can you share these details ?

Usually for best performance the whole model should be delegated, partially delegated models will not have best performance and will have overhead from switching between DSP and CPU
Thanks

**Comment by limdlh** [comment]
@karimnosseir Hello, I have only part log as bellow. I tested it several days ago, and I have no device now. I tested several basic models.
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
INFO: TfLiteHexagonDelegate delegate: 69 nodes delegated out of 71 nodes with 1 partitions.

**Comment by karimnosseir** [comment]
Thanks @limdlh for the details.
Can you point to any of the basic models so i can try reproducing the issue on my side.

Thanks

**Comment by limdlh** [comment]
Hello @karimnosseir, please refor to: https://github.com/limdlh/share

**Comment by limdlh** [comment]
Hello @karimnosseir, do you want some other files or information?

**Comment by karimnosseir** [comment]
Hi @limdlh sorry for the delay.

I benchmarked the shared model on SD 660 and DSP is faster as expected.
CPU 4 threads ~38 ms
Hexagon ~15 ms

Also, tried on Samsung S9 the label_image and hexagon is also faster as expected.

You may want to retry.

Thanks

**Comment by limdlh** [comment]
Hello @karimnosseir, thank you for your reply.
Your result is a little more than 2 time faster for Hexagon than CPU, does Hexagon could only run this speed?
I think Hexagon should be faster than CPU for several times or even dozens
