### ISSUE TITLE
Unclear error message in keras.backend.bias_add

### ISSUE THREAD

**Issue by mathgaming** [tensorflow/tensorflow#49046]
https://github.com/tensorflow/tensorflow/blob/40caef44549a199eaac327b673fa862194b66fc4/tensorflow/python/keras/backend.py#L6004-L6007

Is line 6007 supposed to be `(len(bias_shape), ndim(x) - 1))`?

**Comment by bhack** [comment]
Thanks.. Can you submit a small PR?
