### ISSUE TITLE
TensorFlow won't detect GPU

### ISSUE THREAD

**Issue by Moronixo** [tensorflow/tensorflow#49107]
Hi, I'm beginning to use TensorFlow for a project and I'm having some issues with it picking up my GPU. When I run print(tf.config.list_physical_devices('GPU')) it returns an empty list instead.

I'm running it on TensorFlow 2.3.0, cudatoolkit 10.1 and my GPU is CUDA enabled.

Any help is very much appreciated.

**Comment by Moronixo** [comment]
My cuDNN version is 7.6.5 and python version is 3.8.

**Comment by Moronixo** [comment]
@sachinprasadhs When I try that I get [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')] returned

**Comment by Moronixo** [comment]
@sachinprasadhs My OS is Windows 10, GPU is GeForce GTX 1050 Ti and my IDE is PyCharm.

**Comment by sachinprasadhs** [comment]
@Moronixo seems normal, can you try installing tensorflow-gpu using `pip install tensorflow-gpu==2.3.0`. If your gpu is still not listed then one of your installation might be corrupted you can download the latest driver for your gpu from [here](https://www.nvidia.com/Download/driverResults.aspx/175403/en-us) ,cuda 10.1 from [here](https://developer.nvidia.com/cuda-10.1-download-archive-update2?target_os=Windows&target_arch=x86_64&target_version=10), cuDNN from [here](https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.5.32/production/10.1_20191031/cudnn-10.1-windows10-x64-v7.6.5.32.zip) and follow [this](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/) guide to setup again.

**Comment by Moronixo** [comment]
@sachinprasadhs Installing tensorflow-gpu has made it show up,

 I've added the result below just in case it's the wrong thing. Thank you so much for your help!
![clarify](https://user-images.githubusercontent.com/84026099/117961886-86f83d00-b316-11eb-8838-5a5f0d458d34.PNG)

**Comment by sachinprasadhs** [comment]
@Moronixo Yes it's listing properly now, you can go ahead and close the issue. Thanks!
