### ISSUE TITLE
`tf.keras.preprocessing.image.smart_resize` stable docs does not render properly

### ISSUE THREAD

**Issue by mattxwang** [tensorflow/tensorflow#49101]
## URL(s) with the issue:

> Please provide a link to the documentation entry, for example:

https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/smart_resize 

### Clear description

In the "Stable" tab of the [`tf.keras.preprocessing.image.smart_resize`](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/smart_resize ) docs, the output docs seem like they're HTML-escaped and/or input markdown (opposed to actually rendering as HTML). 

For reference, I'm reporting this bug from Chrome 90 on macOS. I get the same results on Firefox and Safari, also on macOS - likely, the generated docs page is incorrect.

### Usage example

N/A

### Request visuals, if applicable

> Are there currently visuals? If not, will it clarify the content?

Here's a screenshot of what I see on Chrome 90 on macOS, under the "stable" tab:

![Screen Shot 2021-05-10 at 5 18 41 PM](https://user-images.githubusercontent.com/14893287/117739761-d7a35500-b1b3-11eb-9575-a2d07c8cb151.png)

In contrast, here is the nightly tab, which works as intended:

![Screen Shot 2021-05-10 at 5 19 21 PM](https://user-images.githubusercontent.com/14893287/117739839-04f00300-b1b4-11eb-911b-a873dc323207.png)

### Submit a pull request?

Not very familiar with the tensorflow docs API, but if it's a simple change, I wouldn't mind taking a crack at it!

**Comment by sachinprasadhs** [comment]
@mattxwang , This has been fixed in nightly and will be fixed in the latest stable release.

**Comment by sachinprasadhs** [comment]
@mattxwang , Yes, closing this issue. Thanks!
