### ISSUE TITLE
Tensorflow Certificate on Mac M1

### ISSUE THREAD

**Issue by Leon-lianglyu** [tensorflow/tensorflow#49103]
**System information**
- OS Platform and Distribution: Mac M1 Big Sur 11.3
- TensorFlow version: 2.4.1
- Python version:3.8
- GPU model and memory: M1

**Describe the problem**

Anyone has tried to take the TF certificate exam on a Mac M1 device?

I've installed tensorflow-macos in an env and it works fine. However, the exam would create a new project in Pycharm using my global python and install original tensorflow 2.4.1. I tried to manually install original tensorflow 2.4.1 globally, but I got :

Process finished with exit code 132 (interrupted by signal 4: SIGILL)

So is there any way that I can use a existing env to run the exam or I get the original tensorflow working properly on Mac M1?

Many thanks!

**Comment by Leon-lianglyu** [comment]
> guide

Thanks for it. But I followed the offical guide and met the above problems.

**Comment by Leon-lianglyu** [comment]
> @Leon-lianglyu Please follow the official [guide](https://www.tensorflow.org/extras/cert/Setting_Up_TF_Developer_Certificate_Exam.pdf) to setup the environment for mac OS. Also, You will get a very detailed information on TF Certification. Hope It will help you to set up the environment and clear the Cerification as well.Thanks!

Thanks for it. But I followed the offical guide and met the above problems.

**Comment by sachinprasadhs** [comment]
@Leon-lianglyu , You can find the similar issues here which could solve your issue here, [issue1](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org), [issue2](https://stackoverflow.com/questions/65242614/why-does-loading-tensorflow-on-mac-lead-to-process-finished-with-exit-code-132)
