### ISSUE TITLE
Patch mkl_serv_intel_cpu() to speed up MKL on AMD CPUs

### ISSUE THREAD

**Issue by cowwoc** [tensorflow/tensorflow#49113]
Per https://www.agner.org/optimize/blog/read.php?i=49#1022 and https://danieldk.eu/Posts/2020-08-31-MKL-Zen.html patching `int mkl_serv_intel_cpu()` to return 1 will cause MKL to run significantly fast under AMD CPUs. The link provides background information.

Is it possible to patch this out-of-the-box in the tensorflow-mkl package?

Note: I am not associated with the authors of these blogs. I am just a TensorFlow end-user with an AMD processor.

**Comment by NeoZhangJianyu** [comment]
@cowwoc Thank you share the info.
But the method is not official proposal and not verified fully.
It could make the special function to be improved for performance, but there would be potential risk of Tensorflow functions and performance.

Intel and AMP CPU always have difference. It's possible to cheat MKL to speed up one function. But it's also possible to trigger MKL run hardware related code in wrong CPU, and make mistake/crash.

So, we don't recommend to use this method in official product.

Thank you!

**Comment by cowwoc** [comment]
So, excuse me for pointing this out but... you work for Intel so there is a conflict of interest here.

The web is full of online reports of people using `MKL_DEBUG_CPU_TYPE=5` to fool MKL into thinking that it's running on an Intel CPU and performance improved by 30%-300% (e.g. https://www.reddit.com/r/MachineLearning/comments/f2pbvz/discussion_workaround_for_mkl_on_amd/)

The aforementioned workaround was disabled by Intel in a subsequent release but the principal remains the same.

I propose patching this function to return a value that can be overridden using an environment variable (same concept as `MKL_DEBUG_CPU_TYPE=5`) and let people experiment with it. If enough people report that it works for them and is stable (which seems to have been the case in the past) then we can flip the default value.

**Comment by NeoZhangJianyu** [comment]
@cowwoc Yes, I'm working for Intel. :)
The MKL and Tensorflow-MKL are contributed by Intel.
They are only designed for and verified on Intel CPU.

It's unknown the result of running on other CPUs.
So, other CPUs are out of our scope.

**Comment by agramesh1** [comment]
@cowwoc  Thank you for submitting the issue. The support for MKL in Tensforflow-mkl was removed late last year and is no longer supported as of TF2.4. (https://github.com/tensorflow/tensorflow/pull/43586). It has been replaced by oneDNN which is opensourced at https://github.com/oneapi-src/oneDNN. You can submit a patch to oneDNN on github.

**Comment by cowwoc** [comment]
Thank you for the clarification. Closed in favor of https://github.com/oneapi-src/oneDNN/issues/1056.

**Comment by NeoZhangJianyu** [comment]
@cowwoc Thank you!
