### ISSUE TITLE
Greenish image when using convertYUV420ToARGB8888

### ISSUE THREAD

**Issue by riless** [tensorflow/tensorflow#4911]
I'm experimenting the [TensorFlow Android Camera Demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android). but it seems that the [ImageUtils.convertYUV420ToARGB8888](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java#L164) used to convert images from the camera input to RGB  bytes array is not handling very well the [YUV_420_888 format](https://developer.android.com/reference/android/graphics/ImageFormat.html).

Here is the output of `ImageUtils.saveBitmap(rgbFrameBitmap);`

![](http://i.imgur.com/bsL1czy.png)

**Comment by andrewharp** [comment]
Interesting, I noticed that the resulting bmp it's not just greenish, it's completely green -- all R and B values are 0.

I'd theorize that either your device is not providing a 420sp camera frame or is not providing an actual argb8888 output bitmap, as I'm unable to replicate this locally. Have you made any other modifications to the code? What sort of device are you using?

To get a little bit more detail, could you add some logging in YUV2RGB() in [yuv2rgb.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/yuv2rgb.cc), and see what both the input and output values look like?

**Comment by riless** [comment]
>  your device is not providing a 420sp camera frame or is not providing an actual argb8888 output bitmap

`LOGGER.i("IMAGE FORMAT: " + String.valueOf(image.getFormat()));` Outputs `IMAGE FORMAT: 35`. refering to [this page](https://developer.android.com/reference/android/graphics/ImageFormat.html), it is the YUV_420_888 format.

All [this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java#L122-L186) is exactly the same. I've just added a debug line after seeing that my model's output is incohérente.

`ImageUtils.saveBitmap(rgbFrameBitmap);`


I've added some logging to the YUV2RGB() function.

```
static inline uint32 YUV2RGB(int nY, int nU, int nV) {

  LOG(INFO) << "nY: " << nY << ", "
            << "nU: " << nU << ", "
            << "nV: " << nV << "\n";
  nY -= 16;
  nU -= 128;
  nV -= 128;
  if (nY < 0) nY = 0;

  // This is the floating point equivalent. We do the conversion in integer
  // because some Android devices do not have floating point in hardware.
  // nR = (int)(1.164 * nY + 2.018 * nU);
  // nG = (int)(1.164 * nY - 0.813 * nV - 0.391 * nU);
  // nB = (int)(1.164 * nY + 1.596 * nV);

  int nR = (int)(1192 * nY + 1634 * nV);
  int nG = (int)(1192 * nY - 833 * nV - 400 * nU);
  int nB = (int)(1192 * nY + 2066 * nU);

  LOG(INFO) << "nR: " << nR << ", "
            << "nG: " << nG << ", "
            << "nB: " << nB << "\n";


  nR = MIN(kMaxChannelValue, MAX(0, nR));
  nG = MIN(kMaxChannelValue, MAX(0, nG));
  nB = MIN(kMaxChannelValue, MAX(0, nB));

  nR = (nR >> 10) & 0xff;
  nG = (nG >> 10) & 0xff;
  nB = (nB >> 10) & 0xff;

  LOG(INFO) << "nR: " << nR << ", "
            << "nG: " << nG << ", "
            << "nB: " << nB << "\n\n";

  return 0xff000000 | (nR << 16) | (nG << 8) | nB;
}

```
Here is the output
```
...
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:33 nY: 69, nU: 0, nV: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:51 nR: -145976, nG: 221000, nB: -201272
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 215, nB: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:33 nY: 71, nU: 0, nV: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:51 nR: -143592, nG: 223384, nB: -198888
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 218, nB: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:33 nY: 75, nU: 0, nV: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:51 nR: -138824, nG: 228152, nB: -194120
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 222, nB: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:33 nY: 78, nU: 0, nV: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:51 nR: -135248, nG: 231728, nB: -190544
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 226, nB: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:33 nY: 80, nU: 0, nV: 0
10-14 10:31:59.406 28676-28716/? I/native: yuv2rgb.cc:51 nR: -132864, nG: 234112, nB: -188160
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 228, nB: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:33 nY: 80, nU: 0, nV: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:51 nR: -132864, nG: 234112, nB: -188160
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 228, nB: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:33 nY: 80, nU: 0, nV: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:51 nR: -132864, nG: 234112, nB: -188160
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 228, nB: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:33 nY: 78, nU: 0, nV: 0
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:51 nR: -135248, nG: 231728, nB: -190544
10-14 10:31:59.411 28676-28716/? I/native: yuv2rgb.cc:64 nR: 0, nG: 226, nB: 0
...
```

**Comment by riless** [comment]
A dump of `yuvBytes` just before [`ImageUtils.convertYUV420ToARGB8888()`](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java#L164) call

```
10-14 10:57:41.551 12667-12709/org.tensorflow.demo I/tensorflow: TensorFlowImageListener: yuvBytes[0]: [16, 76, 76, 76, 76, 76, 75, 73, 70, 64, 65, 70, 74, 76, 76, 77, 77, 77, 77, 78, ...]
10-14 10:57:41.571 12667-12709/org.tensorflow.demo I/tensorflow: TensorFlowImageListener: yuvBytes[1]: [-128, -125, -124, -124, -125, -125, -125, -125, -125, -125, -125, -126, -126, ...]
10-14 10:57:41.586 12667-12709/org.tensorflow.demo I/tensorflow: TensorFlowImageListener: yuvBytes[2]: [-128, 123, 123, 122, 122, 123, 123, 124, 124, 124, 124, 123, 124, 125, 125, 125, ...]
```

**Comment by riless** [comment]
I think that this issue is related to this one [#306](https://github.com/tensorflow/tensorflow/issues/306).

Updating Android version ...
