### ISSUE TITLE
"no module named tensorflow" when I "import tensorflow" after I install tensorflow on windows successfully

### ISSUE THREAD

**Issue by DevinCheung** [tensorflow/tensorflow#4912]
I followed ..\tensorflow\contrib\cmake\README to install tensorflow on windows. Everything went well and I installed tensorflow successfully. But after I "activate tensorflow", and tried to "import tensorflow" using python, it went wrong, saying "no module named tensorflow". How can I fix this problem? Many thanks!

**Comment by gunan** [comment]
@mrry might have an answer, but we do not officially have support for windows yet.
Therefore, pip packages built might not be working on windows.

**Comment by mrry** [comment]
Can you please share the exact commands that you ran between "activating tensorflow" and "importing tensorflow"?

**Comment by DevinCheung** [comment]
@mrry 
I followed the README: "Invoke MSBuild to build TensorFlow", run 
'MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj on cmd.exe'
And it It compiled.

Then I "activate tensorflow", and open the python.exe.
And I "import tensorflow", it said "no module named tensorflow".

Is there anything that I have missed?  Thanks

**Comment by mrry** [comment]
What command do you run to "activate tensorflow"? Is this an Anaconda command?

It sounds like there's a step missing where I'd expect you to install the PIP package. Something like the following (where `%TF_PIP_PACKAGE_FILENAME%` is replaced with the path to the PIP package that you just built):

```
C:\...\> pip install %TF_PIP_PACKAGE_FILENAME%
```

**Comment by DevinCheung** [comment]
@mrry 
Excuse me, after pip being successfully built, what the next step shall I do? Yes, of course, I use Anaconda.

Thanks for your generous help!

**Comment by mrry** [comment]
After you run the above `pip install` command, you should be able to run `python` and `import tensorflow as tf` should succeed.

**Comment by zafartahirov** [comment]
Probably, documentation should be temporarily be changed to "Docker flow" for Windows - at least until `pip` is fully working on Windows.

**Comment by DevinCheung** [comment]
hope tensorflow officially supports Windows soon~

**Comment by mrry** [comment]
Did you try to `pip install` the built wheel file, as I suggested [here](https://github.com/tensorflow/tensorflow/issues/4912#issuecomment-256356781)?

**Comment by gunan** [comment]
You can follow #17 for more updates on windows support. I will close this issue to merge all TF on Windows conversation.

**Comment by bhavsarpratik** [comment]
Hi, I have laid down step-by-step instructions to successfully install Tensorflow on Windows.

https://github.com/bhavsarpratik/install_Tensorflow_GPU_windows

**Comment by tehmeerali786** [comment]
Use python 3.5 or less. If Anaconda, you can use one of the three ways here. I used the second one. https://docs.anaconda.com/anaconda/faq#how-do-i-get-the-latest-anaconda-with-python-3-5
