### ISSUE TITLE
Keras Tensorboard callback not  generating profile with model.train_on_batch()

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#49125]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  pip
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
No profile shown in Tensorboard.

**Describe the expected behavior**
Should see active profile. 

**Standalone code to reproduce the issue**

```
  .
  '
   model.compile(optimizer='adam', loss='mse', metrics=['mae'])
   tboard_cb = tf.keras.callbacks.TensorBoard(log_dir = logs,
                                                 histogram_freq = 1,
                                                 update_freq = 'batch',
                                                 write_images = True,
                                                 write_graph = True,
                                                 profile_batch = '0,3',
                                                )
    pbar_cb = tf.keras.callbacks.ProgbarLogger(count_mode='steps',
                                stateful_metrics=None)
    cblist = tf.keras.callbacks.CallbackList(callbacks=[tboard_cb, pbar_cb],
                       model=model, add_history=True, add_progbar=True)
   X_batch = ...
   Y_batch = ...
   for i in range(10):
      loss = model.train_on_batch(X_batch, Y_batch)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Could you please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks
