### ISSUE TITLE
How could I get middle layers output of TFLite 

### ISSUE THREAD

**Issue by jwj04ok** [tensorflow/tensorflow#49129]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1

**Describe the feature and the current behavior/state.**
I would like to know how to get the middle layers output of TFLite models. 
For now, the method I used is:

interpreter.allocate_tensors()
interpreter.set_tensor(input_details["index"], test_image)
interpreter.invoke()

layer_output = interpreter.get_tensor(**index**), where index is the the index of the tensor

Is that correct?

**Who will benefit with this feature?**
Anyone who would like to access the middle layer outputs

**Comment by abattery** [comment]
If you want to get the intermediate tensors, you can use the experimental flag like the below one.

```
interpreter = tf.lite.Interpreter(
    model_path="test.tflite",
    experimental_preserve_all_tensors=True)
# Run evaluation
interpreter.invoke()
# Look at all tensors including intermediates.
print({
    t['name']: interpreter.get_tensor(t['index'])
    for t in interpreter.get_tensor_details()
})
```

**Comment by jwj04ok** [comment]
> If you want to get the intermediate tensors, you can use the experimental flag like the below one.
> 
> ```
> interpreter = tf.lite.Interpreter(
>     model_path="test.tflite",
>     experimental_preserve_all_tensors=True)
> # Run evaluation
> interpreter.invoke()
> # Look at all tensors including intermediates.
> print({
>     t['name']: interpreter.get_tensor(t['index'])
>     for t in interpreter.get_tensor_details()
> })
> ```

I tried the "experimental_preserve_all_tensors=True" but got "__init__() got an unexpected keyword argument 'experimental_preserve_all_tensors'"

It seems that tf.lite.Interpreter() does not accept argument experimental_preserve_all_tensors.
This argument also does not appear in formal reference https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter

**Comment by abattery** [comment]
This feature is newly enabled. Please try out with the tf-nightly version.

**Comment by abattery** [comment]
FYI, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/interpreter.py#L312

**Comment by jwj04ok** [comment]
Thanks, may I know if I do not use "experimental_preserve_all_tensors=True", I can still get information of all tensors by calling "interpreter.get_tensor(index)". Where does those values comes from?
