### ISSUE TITLE
Question about `input_fn` in Tensorflow's multi worker estimator tutorial

### ISSUE THREAD

**Issue by jiqiujia** [tensorflow/tensorflow#49127]
In this [tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator), function input_fn has a param named mode. I can't figure out how this param get passed to input_fn when training.
```python
BUFFER_SIZE = 10000
BATCH_SIZE = 64

def input_fn(mode, input_context=None):
  datasets, info = tfds.load(name='mnist',
                                with_info=True,
                                as_supervised=True)
  mnist_dataset = (datasets['train'] if mode == tf.estimator.ModeKeys.TRAIN else
                   datasets['test'])

  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

  if input_context:
    mnist_dataset = mnist_dataset.shard(input_context.num_input_pipelines,
                                        input_context.input_pipeline_id)
  return mnist_dataset.map(scale).cache().shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
```

To better clarify my question, see how this `input_fn` is passed as a function param. It is just passed without any wrapper that give `mode` a value.
```python
tf.estimator.train_and_evaluate(
    classifier,
    train_spec=tf.estimator.TrainSpec(input_fn=input_fn),
    eval_spec=tf.estimator.EvalSpec(input_fn=input_fn)
)
```

**Comment by tilakrayal** [comment]
@jiqiujia ,

In order to reproduce the issue reported here, could you please provide the tensorflow version,the complete code and the dataset you are using. Thanks!

**Comment by sachinprasadhs** [comment]
@jiqiujia , `mode` is basically value from [tf.estimator.ModeKeys](https://www.tensorflow.org/api_docs/python/tf/estimator/ModeKeys), it can be between `TRAIN, EVAL and PREDICT`. 
The value is passed to the input function when the [Train and evaluate](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator#train_and_evaluate_the_model) is called using [TrainSpec](https://www.tensorflow.org/api_docs/python/tf/estimator/TrainSpec) or [EvalSpec](https://www.tensorflow.org/api_docs/python/tf/estimator/EvalSpec), for example if `tf.estimator.TrainSpec(input_fn=input_fn)` is used the mode will be taken as `TRAIN` and for `tf.estimator.EvalSpec(input_fn=input_fn)` the mode will be `EVAL`.

**Comment by jiqiujia** [comment]
@sachinprasadhs Sorry for my late response. It seems this is not documented? If not, please help me to point out.

**Comment by sachinprasadhs** [comment]
@jiqiujia , As of now you can find only those information from different links provided in the comment above.
