### ISSUE TITLE
the input->params.scale must equal to output->params.scale of the pooling node

### ISSUE THREAD

**Issue by CristXu** [tensorflow/tensorflow#49133]
Hi,
     Recently, i found that inside the pooling.cc, it will assert the input->params.scale and the output->params.scale,
![image](https://user-images.githubusercontent.com/49855018/117932150-a1d8aa80-b332-11eb-9fa1-237550d923aa.png)
when using a quantization model which has a average pool or max pool.
     But when the kernel size of the pooling node is not equal to the input size, the right and the bottom will be discarded with valid padding. When the max value is just at there, then we can make sure the max value of the maxpooling layer is still the same with the input node.
    Also when we use the avg pool, the max value of the output can not be the same with the input, will always be smaller.
   So, i want to ask, why we assert the max value of the input / output scale is same?

Regards,
    Crist

**Comment by daverim** [comment]
In order to prevent additional quantization error from re-quantization and improve latency, for pooling operations, we keep the input scale and output scale the same during conversion.

**Comment by sachinprasadhs** [comment]
Could you please refer to the above comment and close the issue. Thanks!
