### ISSUE TITLE
How to reduce false positives when training a model using tensorflow object detection API?

### ISSUE THREAD

**Issue by Shobana1230** [tensorflow/tensorflow#49135]
I have trained a tensorflow object detection model which will detect a box, bag and crate. when i tested that trained model it is giving more false positives. I trained that with the cleaned datas with proper annotations, though it is giving more false positives. Is there any way to reduce the false positives?

I am using ssd_mobilenet_v1_coco to train a model. Do i need to change anything in the pipeline.config file to reduce the false positives?

**Comment by sachinprasadhs** [comment]
@Shobana1230  Could you please provide some sample images.

**Comment by sachinprasadhs** [comment]
@Shobana1230  You can refer [this](https://stackoverflow.com/questions/45666499/best-strategy-to-reduce-false-positives-googles-new-object-detection-api-on-sa) StackOverflow answer for general context on reducing false positives in Object detection APIs.
