### ISSUE TITLE
Training on tf distribute takes long time ->  Complete shape not known for Adam for SparseTensor

### ISSUE THREAD

**Issue by sat2000pts** [tensorflow/tensorflow#49137]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No mobile
- TensorFlow installed from (source or binary): Rejected
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7
- Bazel version (if compiling from source): Negative
- GCC/Compiler version (if compiling from source): Negative
- CUDA/cuDNN version: No
- GPU model and memory: No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to run my model with MultiWorkerMirroredStrategy() but I am facing this issue:
`2021-05-07 19:47:04.704974: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:455] error: Aborted: Complete shape not known for Adam/allreduce/CollectiveReduce_3
2021-05-07 19:47:04.705015: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1138] error: Aborted: Complete shape not known for Adam/allreduce/CollectiveReduce_3
2021-05-07 19:47:04.705027: E tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1155] ScopedAllocatorOptimizer: Aborted: Complete shape not known for Adam/allreduce/CollectiveReduce_3
2021-05-07 19:47:04.705033: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:928] error: Aborted: Complete shape not known for Adam/allreduce/CollectiveReduce_3
`
My code in the tf.distribute takes more than 1 hour per epoch whereas running it normally it takes 4 minutes per epoch. The difference is humongous, I am suspecting its maybe due to the warning msg above. 

For the dataset I am using sklearn's CountVectorizer to transform text to feature vector and LabelEncoder to encode the class names. I then convert x to SparseTensor. 

```
x # coo_matrix with 300k observations and 42000 feature size
y # array containing integer value of size 300k x 1 
BATCH_SIZE = 256
NUM_WORKERS = 2

GLOBAL_BATCH_SIZE = BATCH_SIZE * NUM_WORKERS

def build_model():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(512,  activation='relu'))
    model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))
    model.compile(optimizer="adam",
                  loss='sparse_categorical_crossentropy',
                  metrics=["accuracy"])

    return model

def coo_to_tensor(coo):
    return tf.sparse.SparseTensor(list(zip(coo.row, coo.col)), coo.data, coo.shape)

options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA 
ds = tf.data.Dataset.from_tensor_slices((coo_to_tensor(x),y)).batch(GLOBAL_BATCH_SIZE).with_options(options)..batch(GLOBAL_BATCH_SIZE)

with strategy.scope():
    multi_worker_model = build_model()

multi_worker_model.fit(ds, epochs=args.epochs, batch_size=BATCH_SIZE)
```

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sat2000pts** [comment]
I have been playing around with the from_generator function as well


```
feature_size = 42000 -> feature size after vectorizing text data 

def build_model():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.InputLayer(input_shape=(feature_size,), dtype=tf.int64, sparse=True))
    model.add(tf.keras.layers.Dense(512,  activation='relu'))
    model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))
    model.compile(optimizer="adam",
                  loss='sparse_categorical_crossentropy',
                  metrics=["accuracy"])

    return model

ds = tf.data.Dataset.from_generator(my_generator, output_signature=(tf.SparseTensorSpec(shape=(1,feature_size) ,dtype=tf.int64), tf.TensorSpec(shape=(1,), dtype=tf.int32)))

with strategy.scope():
    multi_worker_model = build_model()

multi_worker_model.fit(ds, epochs=args.epochs, batch_size=BATCH_SIZE , steps_per_epoch=my_steps)

```

However issues still prevail, this time I am getting such an error message 
`
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("cond_1/Identity:0", shape=(None, 3), dtype=int64, device=/job:worker/replica:0/task:0/device:CPU:0), values=Tensor("sequential/dense/Cast:0", shape=(None,), dtype=float32, device=/job:worker/replica:0/task:0/device:CPU:0), dense_shape=Tensor("cond_1/Identity_2:0", shape=(3,), dtype=int64, device=/job:worker/replica:0/task:0/device:CPU:0)). Consider casting elements to a supported type.`

**Comment by UsharaniPagadala** [comment]
@sat2000pts 

Sorry for the delayed response.
Looking at the error log,seems like this is similar to  the issue [#25980](https://github.com/tensorflow/tensorflow/issues/25980), and let me know if it helps.Thanks
