### ISSUE TITLE
Normalization using TensorFlow Keras

### ISSUE THREAD

**Issue by ashishsme14** [tensorflow/tensorflow#49138]
Our task is as below not sure what we done mistake in it -

```
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from matplotlib import pyplot
import seaborn as sns
import pandas as pd
from keras.layers import BatchNormalization
from keras.models import model_from_json
import tensorflow as tf
from sklearn.datasets import load_breast_cancer
from sklearn import metrics
import random as rn
from keras import backend as K
import matplotlib.pyplot as plt
import os
from keras.layers import Activation
```

```
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""
sd = 22 # Here sd means seed.
np.random.seed(sd)
rn.seed(sd)
os.environ['PYTHONHASHSEED']=str(sd)
```

```
config = tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1)
tf.set_random_seed(sd)
sess = tf.Session(graph=tf.get_default_graph(), config=config)
K.set_session(sess)
```

Load the breast cancer dataset using load_breast_cancer function

`X, y = load_breast_cancer(return_X_y=True)`

`X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=500)`

- Create a sequential model
- The model expects rows of data with 30 variables (the input_dim=30 argument)
- The first hidden layer has 90 nodes and uses the relu activation function.
- The second hidden layer has 60 nodes and uses the relu activation function.
- The third hidden layer has 30 nodes and uses the relu activation function.
- The output layer has 1 node and uses the sigmoid activation function.

```
While comipling the model pass the following parameters -

     -optimizer as Adagrad
     -loss as binary cross entropy 
     -metrics as accuracy

```
  ```
  model = Sequential()
    model.add(Dense(30, input_dim=30))
    model.add(Dense(90, activation='relu'))
    model.add(Dense(60, activation='relu'))
    model.add(Dense(30, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='Adagrad', metrics=['accuracy'])
```

fit the model with X_train, y_train, epochs=50, batch_size=50,shuffle=False,validation_split=0.2,verbose=1 and save it in history

`history = model.fit(X_train, y_train, epochs=50, batch_size=50,shuffle=False,validation_split=0.2,verbose=1 )`

```
_, train_acc = model.evaluate(X_train, y_train, verbose=0)
_,test_acc=  model.evaluate(X_test, y_test, verbose=0)
print('Train: %.2f, Test: %.2f' % (train_acc, test_acc))
```
Train: 0.61, Test: 0.69

```
def plot_history(history):
    loss_list = [s for s in history.history.keys() if 'loss' in s and 'val' not in s]
    val_loss_list = [s for s in history.history.keys() if 'loss' in s and 'val' in s]
    acc_list = [s for s in history.history.keys() if 'acc' in s and 'val' not in s]
    val_acc_list = [s for s in history.history.keys() if 'acc' in s and 'val' in s]
    
    if len(loss_list) == 0:
        print('Loss is missing in history')
        return 
    
    ## As loss always exists
    epochs = range(1,len(history.history[loss_list[0]]) + 1)
    
    ## Loss
    plt.figure(1)
    for l in loss_list:
        plt.plot(epochs, history.history[l], 'b', label='Training loss (' + str(str(format(history.history[l][-1],'.5f'))+')'))
    for l in val_loss_list:
        plt.plot(epochs, history.history[l], 'g', label='Validation loss (' + str(str(format(history.history[l][-1],'.5f'))+')'))
    
    plt.title('Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    
    ## Accuracy
    plt.figure(2)
    for l in acc_list:
        plt.plot(epochs, history.history[l], 'b', label='Training accuracy (' + str(format(history.history[l][-1],'.5f'))+')')
    for l in val_acc_list:    
        plt.plot(epochs, history.history[l], 'g', label='Validation accuracy (' + str(format(history.history[l][-1],'.5f'))+')')

    plt.title('Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.show()
# Calling the function
plot_history(history)

```

- Create a sequential model1
- The model1 expects rows of data with 30 variables (the input_dim=30 argument)
- The first hidden layer has 90 nodes.
- Add Batch Normalization using BatchNormalization function to the model1.
- Add the activation function as relu
- The second hidden layer has 60 nodes.
- Add Batch Normalization using BatchNormalization function to the model1.
- Add the activation function as relu
- The third hidden layer has 30 nodes.
- Add Batch Normalization using BatchNormalization function to the model1.
- Add the activation function as relu
- The output layer has 1 node and uses the sigmoid activation function.

```
While comipling the model1 pass the following parameters -

     -optimizer as Adagrad
     -loss as binary cross entropy 
     -metrics as accuracy

```   
   ```
 model1 =  Sequential()
    model1.add(Dense(30, input_dim=30))
    model1.add(Dense(90))
    model1.add(Dense(60))
    model1.add(Dense(30))
    model1.add(BatchNormalization())
    model1.add(Activation('relu'))
    model1.add(Dense(1, activation='sigmoid'))
    model1.compile(loss='binary_crossentropy', optimizer='Adagrad', metrics=['accuracy'])
```

`history1 =  model1.fit(X_train, y_train, epochs=50, batch_size=50,shuffle=False,validation_split=0.2,verbose=1 )
`
```
_, train_acc1 = model1.evaluate(X_train, y_train, verbose=0)
_,test_acc1 =  model1.evaluate(X_test, y_test, verbose=0)
print('Train: %.2f, Test: %.2f' % (train_acc1, test_acc1))
```
Train: 0.93, Test: 0.99

```
plt.figure(1)
pyplot.plot(history1.history['accuracy'], label='train')
pyplot.plot(history1.history['val_accuracy'], label='test')

plt.figure(2)
pyplot.plot(history1.history['loss'], label='train')
pyplot.plot(history1.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()
```

- Create a sequential model2
- The model2 expects rows of data with 30 variables (the input_dim=30 argument)
- The first hidden layer has 90 nodes and uses the relu activation function.
- Add Batch Normalization using BatchNormalization function to the model2.
- The second hidden layer has 60 nodes and uses the relu activation function.
- Add Batch Normalization using BatchNormalization function to the model2.
- The third hidden layer has 30 nodes and uses the relu activation function.
- Add Batch Normalization using BatchNormalization function to the model2.
- The output layer has 1 node and uses the sigmoid activation function.

```
While comipling the model2 pass the following parameters -

     -optimizer as Adagrad
     -loss as binary cross entropy 
     -metrics as accuracy
```  
   

   ```
model2 =  Sequential()
    model2.add(Dense(30, input_dim=30))
    model2.add(Activation('relu'))
    model2.add(BatchNormalization())
    model2.add(Dense(90))
    model2.add(Dense(60))
    model2.add(Dense(30))
    model2.add(Dense(1, activation='sigmoid'))
    model2.compile(loss='binary_crossentropy', optimizer='Adagrad', metrics=['accuracy'])

```

`history2 =  model2.fit(X_train, y_train, epochs=50, batch_size=50,shuffle=False,validation_split=0.2,verbose=1 )`

```
_, train_acc2 = model2.evaluate(X_train, y_train, verbose=0)
_,test_acc2 =  model2.evaluate(X_test, y_test, verbose=0)
print('Train: %.2f, Test: %.2f' % (train_acc2, test_acc2))

```
Train: 0.92, Test: 0.91

```
plt.figure(1)
pyplot.plot(history2.history['accuracy'], label='train')
pyplot.plot(history2.history['val_accuracy'], label='test')

plt.figure(2)
pyplot.plot(history2.history['loss'], label='train')
pyplot.plot(history2.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()

```

**Comment by ashishsme14** [comment]
We think issue is with before and after implementation code...

**Comment by ashishsme14** [comment]
any expertise advice :-)

**Comment by saikumarchalla** [comment]
@ashishsme14 Could you please confirm your TF version?  I tried to reproduce the issue but facing different error. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/ffaee10384289f40f682fba383a99d6f/untitled75.ipynb).If possible,Please provide the colab link to reproduce the issue at our end.Thanks


Note: tf.ConfigProto is deprecated in TF 2.0, In that case, use tf.compat.v1.ConfigProto() instead.

**Comment by ashishsme14** [comment]
tensorflow==1.13.1
numpy==1.14.5
pandas==0.24.2
scipy==1.1.0
scikit-learn==0.19.1
pytest==5.4.1
blinker==1.4.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
pickleshare==0.7.5
ipynb==0.5.1
matplotlib==3.0.3
seaborn==0.9.1
keras==2.3.1
six==1.14.0
setuptools==46.1.3

**Comment by saikumarchalla** [comment]
@ashishsme14 Could you please upgrade your Tensoflow version to 2.x  since 1.x is  no more supported actively.Thanks!

**Comment by ashishsme14** [comment]
tensorflow==1.13.1 is fixed for us

**Comment by ashishsme14** [comment]
plz help us

**Comment by tilakrayal** [comment]
@ashishsme14 ,

Please try to install 2.x and use tf.compat.v1.ConfigProto() in that version as 1.x is not actively supported.

Thanks!

**Comment by ashishsme14** [comment]
We trying to load 2.1.1

getting error as

The conflict is caused by:
    The user requested scipy==1.1.0
    keras 2.3.1 depends on scipy>=0.14
    seaborn 0.9.1 depends on scipy>=0.17.1
    tensorflow 2.1.1 depends on scipy==1.4.1; python_version >= "3"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by ashishsme14** [comment]
tensorflow==2.1.1
numpy==1.14.5
pandas==0.24.2
scipy==1.1.0
scikit-learn==0.19.1
pytest==5.4.1
blinker==1.4.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
pickleshare==0.7.5
ipynb==0.5.1
matplotlib==3.0.3
seaborn==0.9.1
keras==2.3.1
six==1.14.0
setuptools==46.1.3

**Comment by ashishsme14** [comment]
tensorflow==2.1.1
numpy==1.16.0
pandas==0.24.2
scipy==1.4.1
scikit-learn==0.19.1
pytest==5.4.1
blinker==1.4.0
jupyter==1.0.0
jupyter-client==6.1.2
jupyter-console==6.1.0
jupyter-core==4.6.3
pickleshare==0.7.5
ipynb==0.5.1
matplotlib==3.0.3
seaborn==0.9.1
keras==2.3.1
six==1.14.0
setuptools==46.1.3

**Comment by ashishsme14** [comment]
for above mentioned version we getting error -

```
sd = 22 # Here sd means seed.
np.random.seed(sd)
rn.seed(sd)
os.environ['PYTHONHASHSEED']=str(sd)

config = tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1)
tf.set_random_seed(sd)
sess = tf.Session(graph=tf.get_default_graph(), config=config)
K.set_session(sess)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-352ebeedbb53> in <module>
      4 os.environ['PYTHONHASHSEED']=str(sd)
      5 
----> 6 config = tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1)
      7 tf.set_random_seed(sd)
      8 sess = tf.Session(graph=tf.get_default_graph(), config=config)

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
```

**Comment by tilakrayal** [comment]
@ashishsme14 ,

Can you please try to execute your code in tensorflow stable version v2.4.1 or 2.5.0 and let us know if you are still facing the same issue.

Thanks!

**Comment by ashishsme14** [comment]
tried same result.. can u please check code for before and after normalization. seems it is not correct.

**Comment by tilakrayal** [comment]
@ashishsme14 ,

Please check this links for more information on Normalization.[Link1](https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization),[Link2](https://keras.io/api/layers/normalization_layers/batch_normalization/),[Link3](https://stackoverflow.com/questions/34716454/where-do-i-call-the-batchnormalization-function-in-keras).

Can you pease consider posting this issue in [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow)  as it is not either bug or feature request, where there is a large community to help and support each other. Thanks!

**Comment by ashishsme14** [comment]
Please let us know below part is correct

```
model1 =  Sequential()
 model1.add(Dense(30, input_dim=30))
 model1.add(Dense(90))
 model1.add(Dense(60))
 model1.add(Dense(30))
 model1.add(BatchNormalization())
 model1.add(Activation('relu'))
 model1.add(Dense(1, activation='sigmoid'))
 model1.compile(loss='binary_crossentropy', optimizer='Adagrad', metrics=['accuracy'])
```

**Comment by tilakrayal** [comment]
@ashishsme14 ,

Please refer this link for more information on [model](https://www.tensorflow.org/guide/keras/train_and_evaluate#the_compile_method_specifying_a_loss_metrics_and_an_optimizer) and add tensorflow.keras before as mentioned in this [link](https://www.tensorflow.org/api_docs/python/tf/keras/Model#expandable-1).

Also please feel free to move this issue to closed status and please submit a new issue from this [link](https://github.com/tensorflow/models/issues/new/choose).Thanks!
