### ISSUE TITLE
Keeping gradient of sqrt(x) stable for x = 0

### ISSUE THREAD

**Issue by egpbos** [tensorflow/tensorflow#4914]
I'm minimizing a function that contains a few `tf.sqrt(c * x)` terms. The `x` is a `tf.Variable` and `c` is a `tf.constant` that is sometimes zero. A `NaN` inevitably presents itself. In my case, the gradient is to `c`, which is `x * 0.5/sqrt(c * x)` and which equals `0 * inf = NaN` when `c` is `0`.

When such a `sqrt` is deeply buried in your function, it can be quite an effort to dig out where the `NaN` is coming from. I can understand and appreciate the fact that there is no check for zero in the `sqrt_grad` operator. However, I feel that debugging could be easier for ops that are known to be unstable in some numerical range.

Two possible fixes would be:
1. Add exceptions to the documentation of these ops. Right now this is not even indicated for `tf.div`, for instance. Since the use-cases of TensorFlow almost always mean that gradients will be involved, the allowed range should also be mentioned for the gradient, if different from that of the op itself.
2. Add debug-mode versions of the ops. These could include `NaN` and `inf` checks.

By the way, I was using the `tf.contrib.opt.ScipyOptimizerInterface` for the minimization, which does not support manually changing the gradients by using `compute_gradients` and `apply_gradients`. That's beside the point, though.

Below some example code for completeness' sake. The differences in outcome only add to the confusion.

``` python
from __future__ import absolute_import, division, print_function
import tensorflow as tf

c = tf.Variable(0.0)

sqrt_grad = tf.gradients(tf.sqrt(c), c)

# another possibility is when another factor in the argument is zero
x = tf.Variable(1.)
sqrt_x_grad = tf.gradients(tf.sqrt(x * c), x)

# try to use select to filter out the NaN
selsqrt_grad = tf.gradients(tf.select(c > 0, tf.sqrt(c), 0), c)

# try clipping of the sqrt
clipsqrt_grad = tf.gradients(tf.clip_by_value(tf.sqrt(c), 1e-10, 1), c)

# clip the argument of the sqrt --> only numerically stable option
clipargsqrt_grad = tf.gradients(tf.sqrt(tf.clip_by_value(c, 1e-10, 1)), c)

init_op = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init_op)

    print(sess.run([sqrt_grad, sqrt_x_grad, selsqrt_grad,
                    clipsqrt_grad, clipargsqrt_grad]))
    # [[inf], [nan], [nan], [nan], [0.0]]
```

**Comment by hholst80** [comment]
The `selsqrt_grad` was quite interesting. It should be equivalent to the first one I thought but I also got NaN like you.

Another interesting case:
```
import tensorflow as tf
sess = tf.InteractiveSession()

s = tf.Variable(0.0)
x = tf.square(tf.square(s))
f = tf.sqrt(x)
init_op = tf.initialize_all_variables()
sess.run(init_op)
dfds, = tf.gradients(f, [s])
```

dfds==0 analytically but we get a NaN because 0 * Inf = NaN.

**Comment by jart** [comment]
@girving could you please take a look at this one?

**Comment by hholst80** [comment]
I think @egpbos exposed a bug in `tf.select` and how it computes gradients. 

```
In [15]: x = tf.Variable(0.0)
In [16]: f = tf.select(x > 0, -x*tf.log(x), 0.0)
In [17]: g, = tf.gradients(f, [x])
In [18]: sess.run(x.initializer)
In [19]: g.eval()
Out[19]: nan
```

**Comment by girving** [comment]
@jart I'm on leave at the moment.

**Comment by yaroslavvb** [comment]
@hholst80 btw, the issue with select grad is that it seems to do "branch1+0*branch2", which doesn't properly get rid of branch2 when it's NaN. Here's a simpler way to show this problem -- the result is `NaN` even though problematic branch is not selected.

@yuanbyu may know if there's any potential way to remedy this problem. Maybe if `select` gradient used `select` instead of multiplication by 0?

```
x = tf.Variable(0.0)
f = tf.select(False, tf.log(x), 0)
g, = tf.gradients(f, [x])
sess = tf.InteractiveSession()
x.initializer.run()
g.eval()

```

**Comment by gibiansky** [comment]
I have run into similar problems with `tf.select`. It would be a good idea to have `tf.select` gradient use `tf.select` instead of multiplication by zero. It would produce much more intuitive behaviour when working with sequences that may include `NaN`.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by noe** [comment]
This is still happening with TF 1.2.1. The updated snippet, which outputs the same results, is:
```Python
from __future__ import absolute_import, division, print_function
import tensorflow as tf

c = tf.Variable(0.0)

sqrt_grad = tf.gradients(tf.sqrt(c), c)

# another possibility is when another factor in the argument is zero
x = tf.Variable(1.)
sqrt_x_grad = tf.gradients(tf.sqrt(x * c), x)

# try to use select to filter out the NaN
selsqrt_grad = tf.gradients(tf.where(c > 0, tf.sqrt(c), 0), c)

# try clipping of the sqrt
clipsqrt_grad = tf.gradients(tf.clip_by_value(tf.sqrt(c), 1e-10, 1), c)

# clip the argument of the sqrt --> only numerically stable option
clipargsqrt_grad = tf.gradients(tf.sqrt(tf.clip_by_value(c, 1e-10, 1)), c)

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)

    print(sess.run([sqrt_grad, sqrt_x_grad, selsqrt_grad,
                    clipsqrt_grad, clipargsqrt_grad]))
```

**Comment by yaroslavvb** [comment]
Reopening is as contributions welcome. There are two examples above which demonstrate the problem. A potential solution would be to use `tf.select(...,a, b)` for gradient instead of current `a*0+1*b`

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity, but please let me know if I'm mistaken. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by dmorrill10** [comment]
This can cause `NaN`s to pop-up with `tensorflow_probability.layers.DenseLocalReparameterization` since requires passing gradients through a sqrt of a sum of squares. It can't be avoided with `tf.where` in TF 1.13.0-rc1, just like the `selsqrt_grad` examples at the start of this thread.

**Comment by ruizengalways** [comment]
selsqrt_grad is very interesting

**Comment by ffanatic13** [comment]
Curious here, what behaviors do you exactly want near singularities?  Having the software perform analytic continuation, which is what I am reading here, isn't going to be an easy problem.

**Comment by hholst80** [comment]
IMHO you want to be able to select a specific gradient for certain values. Use the algebraic gradient for all values except at those given (singularites) and there use the provided gradient.

Artificial example f=x^2/x works fine for all values of x except at x=0 where calculus is needed to provide the limit value. For x=0 use the gradient 1, which is the gradient of d (for all x, including x=0).

**Comment by yaroslavvb** [comment]
Alternatively, you can side-step the singularity issue because 0.0 in machine precision (or any other floating point number), corresponds to an interval on the real line, so you can avoid pointwise singularities by disambiguating to another member of the interval. Related example is gradient of ReLU --- it is nan at 0 but 0 at 0.0

**Comment by hholst80** [comment]
floating point 0.0 is exactly equal to 0. check the specs. 

Tensorflow *defines* the gradient of ReLU(x) at x=0 to be equal 0. It's really that simple.
> 
> 
> Alternatively, you can side-step the singularity issue because 0.0 in machine precision (or any other floating point number), corresponds to an interval on the real line, so you can avoid pointwise singularities by disambiguating to another member of the interval. Related example is gradient of ReLU --- it is nan at 0 but 0 at 0.0

**Comment by yaroslavvb** [comment]
Specs say that any real number in range (-[ulp](https://en.wikipedia.org/wiki/Unit_in_the_last_place), +ulp) corresponds to 0.0 in machine precision.

Since -ulp/2 maps to 0.0 and has derivative 0, it makes sense to define Relu(0.0)'=0. It would also make sense to define it at 1 because of ulp/2. Defining it as 2 would not make sense. You can use this approach to figure out values around singularities without having to do limits
