### ISSUE TITLE
[XLA:GPU] Support integer convolutions

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#49140]
**System information**
- TensorFlow version (you are using): `2.6.0.dev20210512`
- Are you willing to contribute it (Yes/No): Yes (I am not familiar with that part of the codebase so would need a bit of help)

**Describe the feature and the current behavior/state.**

https://github.com/tensorflow/tensorflow/commit/89fc1ddd96f25aa9d8eb6a0104ca1fdb11b26753 added support for integer convolutions on `XLA:CPU` which means that `XLA:GPU` is now the only backend unable to run integer convolutions. This came up in https://github.com/google/jax/pull/6467 and it looks like it is already tracked internally in `b/183565702`.

Is there any timeline for integer convolution support on GPU? As far as I know CUDA and CUDNN have options to execute integer convolutions on NVIDIA GPUs so I don't think anything fundamental should block this conceptually.

**Who will benefit with this feature?**

Support for integer convolutions would bring the GPU backend inline with CPU and TPU which would be great for users as they might expect integer support for convolutions similar to how it currently works in `DotGeneral` which could enable novel research on true integer quantization aware training.

**Comment by cheshire** [comment]
We have an internal PR with int8xint8->int32 convolutions via cuBLAS, I expect it to land shortly. Will that be sufficient?

**Comment by lgeiger** [comment]
> We have an internal PR with int8xint8->int32 convolutions via cuBLAS, I expect it to land shortly. Will that be sufficient?

That's great to hear! I think `int8xint8->int32` will probably cover most cases. Although in the future it I think it would be great to have parity between the backends and also support the other datatypes.

**Comment by lgeiger** [comment]
> We have an internal PR with int8xint8->int32 convolutions via cuBLAS, I expect it to land shortly. Will that be sufficient?

@cheshire I saw the change to add a int8xint8->int32 GEMM landed some time ago. Do you have any plans to expose this to users in order to support int8xint8->int32 XLA convolutions as well?

**Comment by cheshire** [comment]
It should be exposed, does it work if you do the calculation with int8 type and put it under jit_compile=True?

**Comment by lgeiger** [comment]
Thanks for the fast reply!

I tried it via JAX and it doesn't seem to work on GPU yet:
```python
from jax import numpy as jnp
from jax import lax

lhs = jnp.ones((1, 1, 1), jnp.int8)
rhs = jnp.ones((1, 1, 1), jnp.int8)

x = lax.conv_general_dilated(
    lhs=lhs,
    rhs=rhs,
    window_strides=(1,),
    padding='SAME',
    dimension_numbers=('NCH', 'HIO', 'NCH'),
    preferred_element_type=jnp.int32,
)
```
```
RuntimeError: Unimplemented: Integer convolutions for CuDNN must have float or int8 output.  Use convert to cast output to float or the following pattern to int8: clamp(broadcast(-128), conv(int8_x, int8_w, ...), broadcast(127)).
```
and similar without setting `preferred_element_type`.
```python
x = lax.conv_general_dilated(
    lhs=lhs,
    rhs=rhs,
    window_strides=(1,),
    padding='SAME',
    dimension_numbers=('NCH', 'HIO', 'NCH'),
)
```
```
RuntimeError: Unimplemented: Integer convolutions for CuDNN must have this pattern: conv<InputT=int32, ResultT=int32>(convert<int32>(int8_x), convert<int32>(int8_y))
```

This might be a JAX issue though in which case, I'd be happy to move the discussion to the JAX repo, but the error gets thrown from the TensorFlow XLA code, so I thought this might be the right place.

> It should be exposed, does it work if you do the calculation with int8 type and put it under jit_compile=True?

From TF directly this seems to fail:
```python
import tensorflow as tf

x = tf.ones((1, 5, 5, 1), dtype=tf.int8)
kernel = tf.ones((2, 2, 1, 2), dtype=tf.int8)

@tf.function(jit_compile=True)
def conv(x, kernel):
    return tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding='VALID')

conv(x, kernel)
```
```
TypeError: Value passed to parameter 'input' has DataType int8 not in list of allowed values: float16, bfloat16, float32, float64, int32
```

However, I think this is expected since the default `tf.nn.conv2d` implementation doesn't support `int8` at all (Not sure if I properly test this since I think colab didn't correctly recognize the GPU with tf-nightly). Is there a way to directly call the XLA op from the Python side?

**Comment by lgeiger** [comment]
@cheshire Did you find a chance to look at my comment above? I'd be happy to move this issue to the JAX repo, if you think this is unrelated to general XLA:GPU support of int8 convolutions.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
