### ISSUE TITLE
Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

### ISSUE THREAD

**Issue by mao381332619** [tensorflow/tensorflow#49157]
I use tf.image.combined_non_max_suppression in my model. I can transfer it to tflite. But when I use it in Android or use python tf.lite.interpreter, I got the issue.
![118105343-d752c600-b40e-11eb-9810-5a12f18e1ce3](https://user-images.githubusercontent.com/54882489/118111091-cd809100-b415-11eb-9aca-f6ee3fd0b5ef.png)
How can I resolve it?

**Comment by abattery** [comment]
Looks like the model is converted with the Select TF option. In such case, the android application requires an extra requirement. See also https://www.tensorflow.org/lite/guide/ops_select.

```
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
}
```

**Comment by mao381332619** [comment]
@abattery    I did it. I ran it successfully. Thank you very much
