### ISSUE TITLE
problem using tf.compat.v1.get_variable in tf2

### ISSUE THREAD

**Issue by neuronblack** [tensorflow/tensorflow#49155]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source):no
- GCC/Compiler version (if compiling from source):no
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
reference：https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_variable?hl=en
I referenced the above links and got the following results
v1:<tf.Variable 'foo/v:0' shape=(1,) dtype=float32, numpy=array([1.3727096], dtype=float32)>
v2:<tf.Variable 'foo/v:0' shape=(1,) dtype=float32, numpy=array([-1.0603657], dtype=float32)>

**Describe the expected behavior**
v1 should be equal to v2
When I use tf1, I get the following results：
v1:[0.91463006]
v2:[0.91463006]

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): no
(if contributing):

**Standalone code to reproduce the issue**
reference：https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_variable?hl=en
tf2 version:
```import tensorflow as tf
def foo():
    with tf.compat.v1.variable_scope("foo", reuse=tf.compat.v1.AUTO_REUSE):
        v = tf.compat.v1.get_variable("v", [1], initializer=tf.compat.v1.glorot_uniform_initializer())
        return v
v1 = foo()
v2 = foo()
print(v1)
print(v2)
```
tf1 version:
```import tensorflow as tf
def foo():
    with tf.compat.v1.variable_scope("foo", reuse=tf.compat.v1.AUTO_REUSE):
        v = tf.compat.v1.get_variable("v", [1], initializer=tf.compat.v1.glorot_uniform_initializer())
        return v
v1 = foo()
v2 = foo()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(f'v1:{sess.run(v1)}')
    print(f'v2:{sess.run(v2)}')
```

**Comment by bhack** [comment]
In TF2 you are in graph mode right? 

So in TF2

```
import tensorflow as tf
@tf.function
def foo():
  with tf.compat.v1.variable_scope("foo", reuse=tf.compat.v1.AUTO_REUSE):
    v = tf.compat.v1.get_variable("v", [1])
  return v

v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.
assert v1 == v2
````

**Comment by neuronblack** [comment]
> In TF1 you are in graph mode right?
> 
> So in TF2
> 
> ```
> import tensorflow as tf
> @tf.function
> def foo():
>   with tf.compat.v1.variable_scope("foo", reuse=tf.compat.v1.AUTO_REUSE):
>     v = tf.compat.v1.get_variable("v", [1])
>   return v
> 
> v1 = foo()  # Creates v.
> v2 = foo()  # Gets the same, existing v.
> assert v1 == v2
> ```

Why do I get different values when I use  Eager Execution  and Graph Execution

**Comment by bhack** [comment]
It Is documented. 
Check;
https://github.com/tensorflow/tensorflow/issues/45876
https://github.com/tensorflow/tensorflow/issues/46133

**Comment by LokeSiewWen** [comment]
Hi, I am facing this error with tf.compat.v1.get_variable. 

TypeError: Dimension value must be integer or None or have an __index__ method, got value '27876.0' with type '<class 'float'>'
