### ISSUE TITLE
Inference with small tflite model does not benefit from warm up

### ISSUE THREAD

**Issue by Haag-se** [tensorflow/tensorflow#49158]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-lowlatency x86_64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Desktop
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.6.0
- Python version: n/a
- Bazel version (if compiling from source): 4.0.0
- GCC/Compiler version (if compiling from source): GCC 10.2.0

**Describe the current behavior**
Inference with small tflite model does not benefit from warm up. TFlite Benchmarking Tool indicates that it should.

**Describe the expected behavior**
When benchmarking my tflite-model with the TFlite Benchmarking Tool I cleary see a speed up in steady stage after the initial warm ups. `Inference timings in us: Init: 769, First inference: 533, Warmup (avg): 14.6845, Inference (avg): 15.5197`

When I'm running inference in my C++ code, the inference speed is always around 300-500 us. If I read the benchmarking tool output correctly, it should be able to reach well below 100 us after warm up.

The result from the benchmarking tool ->

```
STARTING!
Log parameter values verbosely: [0]
Num threads: [1]
Graph: [/home/gustaf/cprojects/pacific/nlp/en/model.tflite]
#threads used for CPU inference: [1]
Loaded model /home/gustaf/cprojects/pacific/nlp/en/model.tflite
The input model file size (MB): 0.367488
Initialized session in 0.769ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=33776 first=533 curr=14 min=13 max=533 avg=14.6845 std=3

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=63948 first=14 curr=17 min=13 max=90 avg=15.5197 std=2

Inference timings in us: Init: 769, First inference: 533, Warmup (avg): 14.6845, Inference (avg): 15.5197
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=0.574219 overall=0.574219
```

**Standalone code to reproduce the issue**

Output ->
```
Prediction 1: 477 us
Prediction 2: 307 us
Prediction 3: 320 us
Prediction 4: 319 us
Prediction 5: 299 us
```

Code ->
```
#include <tensorflow/lite/interpreter.h>
#include <tensorflow/lite/model.h>
#include <tensorflow/lite/kernels/register.h>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <fstream>
#include "tbb/concurrent_unordered_map.h"
#include <unicode/unistr.h>
#include <unicode/ustream.h>
#include <unicode/locid.h>
#include <chrono>
#include <boost/algorithm/string.hpp>

std::mutex mtx;

using namespace std;
using namespace std::chrono_literals;
using std::chrono::high_resolution_clock;
using std::chrono::duration_cast;
using std::chrono::duration;
using std::chrono::microseconds;	

tflite::ops::builtin::BuiltinOpResolver resolver_sv;
std::unique_ptr<tflite::FlatBufferModel> model_sv;
std::unique_ptr<tflite::Interpreter> interpreter_sv;
tbb::concurrent_unordered_map<string, int> vocab_sv;

float predict(string ss) {
	std::scoped_lock lock{mtx};
	int* input;
	float* output; 
	string s;
	icu::UnicodeString ustr(ss.c_str());
	ustr.toLower();
	ustr.toUTF8String(s);
	
	input = interpreter_sv->typed_input_tensor<int>(0);
	
	std::vector<std::string> result;
	boost::algorithm::split(result, s, boost::is_any_of(" *"), boost::token_compress_on);

	int i = 0;
	for(auto& word: result) { 
		try {
			input[i] = vocab_sv.at(word);
			i = i+1;
		}
		catch (const std::out_of_range& oor) {
			input[i] = 1;
			i = i+1;
		}
	}
	while(i<=20) {
		input[i] = 0;
		i = i+1;
	}

	interpreter_sv->Invoke();
	output = interpreter_sv->typed_output_tensor<float>(0);

	return output[0];
}

void init_model(){

	model_sv = tflite::FlatBufferModel::BuildFromFile("/home/gustaf/cprojects/pacific/nlp/en/model.tflite");
		
	if (model_sv == nullptr) {
			std::cerr << "Model not found!" << std::endl;
		}
	if (tflite::InterpreterBuilder(*model_sv, resolver_sv)(&interpreter_sv) != kTfLiteOk) {
		std::cerr << "Failed to build interpreter!" << std::endl;
		}

	interpreter_sv->SetNumThreads(1);

	if (interpreter_sv->AllocateTensors() != kTfLiteOk) {
		std::cerr << "Failed to allocate tensors." << std::endl;
	}
	if (interpreter_sv->Invoke() != kTfLiteOk) {
		std::cerr << "Cannot invoke interpreter" << std::endl;
	  }
	 
	ifstream infile("/home/gustaf/cprojects/pacific/nlp/en/vocab.txt");
	string a;
	int b;
	while (infile >> a >> b) {vocab_sv.insert(pair<string, int>(a, b));}

}

int main (){
	
	init_model();
	
	auto t1 = high_resolution_clock::now();
	predict("This is a warmup text");
	auto t2 = high_resolution_clock::now();
	predict("This is another warmup text");
	auto t3 = high_resolution_clock::now();
	predict("This is an example text");
	auto t4 = high_resolution_clock::now();
	predict("This is another example text");
	auto t5 = high_resolution_clock::now();
	predict("This is the final text");
	auto t6 = high_resolution_clock::now();


auto ms1 = duration_cast<microseconds>(t2 - t1);
auto ms2 = duration_cast<microseconds>(t3 - t2);
auto ms3 = duration_cast<microseconds>(t4 - t3);
auto ms4 = duration_cast<microseconds>(t5 - t4);
auto ms5 = duration_cast<microseconds>(t6 - t5);

cout << "Prediction 1: " << ms1.count() << " us" << endl;
cout << "Prediction 2: " << ms2.count() << " us" << endl;
cout << "Prediction 3: " << ms3.count() << " us" << endl;
cout << "Prediction 4: " << ms4.count() << " us" << endl;
cout << "Prediction 5: " << ms5.count() << " us" << endl;

}
```

**Comment by abattery** [comment]
@multiverse-tf could you take a look?

**Comment by Haag-se** [comment]
Rebuilding Tensorflow using Bazel seems to fix the issue. Previously I used `make -f ./tensorflow/lite/tools/make/Makefile` to build and linked the .a file when compiling my code. Now I used `bazel build --config= monolithic -c opt //tensorflow/lite:libtensorflowlite.so` and linked the .so file when compiling.

Seems to have made all the difference! I have no idea why though...

```
Prediction 1: 1285 us
Prediction 2: 39 us
Prediction 3: 29 us
Prediction 4: 28 us
Prediction 5: 23 us
```

**Comment by Haag-se** [comment]
A follow up question -> The warmup effect appears to degrade over time. I can do +250k inference runs in 7.2 seconds (about 28 microseconds per prediction in average) which is great, but if i do a single inference a few minutes later with the same model, it takes at least 10x as long time. 

Does Tensorflow clear the memory after some time? And if so, is there an option to stop that from happening?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
