### ISSUE TITLE
No operations will run on the GPU for mobilenet_v1_1.0_224_quant.tflite using C++

### ISSUE THREAD

**Issue by UnickSoft** [tensorflow/tensorflow#49160]
Hello.

I tired to load mobilenet_v1_1.0_224_quant.tflite from tflite example (tensorflow/lite/java/demo/app/src/main/), but it print errors to log:

```
Following operations are not supported by GPU delegate:
    AVERAGE_POOL_2D: OP is supported, but tensor type isn't matched!
    CONV_2D: OP is supported, but tensor type isn't matched!
    DEPTHWISE_CONV_2D: OP is supported, but tensor type isn't matched!
    RESHAPE: OP is supported, but tensor type isn't matched!
    SOFTMAX: OP is supported, but tensor type isn't matched!
    No operations will run on the GPU, and all 31 operations will run on the CPU.
```

I use this code to load:

```
  tflite::InterpreterBuilder interpreter_builder(flatbuffer, op_resolver);
  if (interpreter_builder(&interpreter) != kTfLiteOk || !interpreter) {
    return absl::InternalError("Unable to prepare TfLite interpreter.");
  }
  TfLiteGpuDelegateOptionsV2 options = TfLiteGpuDelegateOptionsV2Default();
  TfLiteDelegate* delegate = TfLiteGpuDelegateV2Create(&options);

  DelegateContext::DelegateData delegate_data{interpreter->inputs(),
                                              interpreter->outputs(), graph};

  delegate->data_ = &delegate_data;
  delegate->flags = kTfLiteDelegateFlagsNone;
  delegate->Prepare = DelegatePrepare;
  delegate->CopyFromBufferHandle = nullptr;
  delegate->CopyToBufferHandle = nullptr;
  delegate->FreeBufferHandle = nullptr;

  if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk)  // Error prints in in this call.
```

Why TFlite cannot run mobilenet_v1_1.0_224_quant.tflite on GPU? Or is it ok?

If I load mobilenet_v1_1.0_224_quant.tflite using Java interface I don't have any errors in log.

I have built TFlite by my self, run on Android Google Pixel 2.

**Comment by abattery** [comment]
@srjoglekar246 could you take a look at this?

**Comment by srjoglekar246** [comment]
Can you check which version of TFLite you are using? Last year we added support for quantization in our GPU delegate.

**Comment by UnickSoft** [comment]
I built using sources from master revision:
[XLA:GPU] Log error if LLVM IR parsing fails.	e6986d372fa	Chris Jones <cjfj@google.com>	29 Apr 2021, 11:46

I didn't find ready to use binary(for C++ API) and built them by myself. Maybe I took unstable changes and I have to take from sources from release branch.

**Comment by UnickSoft** [comment]
Also I tried to build from r2.5 branch and I have the same problem.

**Comment by srjoglekar246** [comment]
@lu-wang-g Can you check if @UnickSoft 's method of building the application is correct?

@UnickSoft Does the model run w/ GPU delegate with the Java API? Or you just tried the CPU path on Java?

**Comment by lu-wang-g** [comment]
The way of building the TFLite .so files looks good to me.

The error seems to come from the code [here](https://github.com/tensorflow/tensorflow/blob/5854c4a9c86ccb44d7bc43cfd2143ea5a56b2d8c/tensorflow/lite/delegates/gpu/common/model_builder.cc#L3048-L3069), where I think `allow_quant_ops` is not turned on (be default it's not, see [enable_quantization](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu#advanced-usage-delegate-options)), so Interpreter cannot handle quantized models.  However, seems TfLiteGpuDelegateOptionsV2Default() sets enable_quant as default. See [here](https://github.com/tensorflow/tensorflow/blob/5854c4a9c86ccb44d7bc43cfd2143ea5a56b2d8c/tensorflow/lite/delegates/gpu/delegate.cc#L451).

@talumbau are you familiar with the GPU settings?

**Comment by UnickSoft** [comment]
@srjoglekar246 I tried to use Java API with GPU. With Java API it loads and work correct (because I don't see any messages in log and GPU version is work much faster). I haven't build Java module by myself. I will try to add additional log to find a reason for a problem.

**Comment by UnickSoft** [comment]
We have found a reason of problem. Sorry for wasting time. It is my initialization code:

```
  delegate->data_ = &delegate_data;
  delegate->flags = kTfLiteDelegateFlagsNone;
  delegate->Prepare = DelegatePrepare;
  delegate->CopyFromBufferHandle = nullptr;
  delegate->CopyToBufferHandle = nullptr;
  delegate->FreeBufferHandle = nullptr;
```

I override delegate->Prepare. In this function I don't pass second parameter to function GetOpsToReplace (by default this parameter is false). 

Maybe I should take code from official docs, because I took this code from tensorflow/lite/delegates/gpu/common/testing/tflite_model_reader.cc and some other code from mediapipe.
Also I found potencial problem in file tensorflow/lite/delegates/gpu/gl_delegate.cc. The function DelegatePrepare from this file don't pass second parameter into GetOpsToReplace.

To fix my problem I just pass second paramert into GetOpsToReplace in DelegatePrepare function. And I think we can close this issue.

**Comment by srjoglekar246** [comment]
@UnickSoft The delegate code in delegates/gpu/delegate.h is what we recommend to use as the GPU delegate, since that is the well-maintained backend. Some of these delegate codebases are pretty complex, so modify with care :-). GLad that you found a fix!
