### ISSUE TITLE
Tensorflow2 - “tf.data.experimental.make_csv_dataset” doesn't work with “tf.keras.preprocessing.timeseries_dataset_from_array”

### ISSUE THREAD

**Issue by alexispomares** [tensorflow/tensorflow#49169]
Hello! I am trying to get TensorFlow to read +100 CSV files that ***don't*** fit in memory (+1GB size each). The files contain time-series data (EEG signals), with the labels in the first column. From the TensorFlow documentation it seems like I should be able to use the *tf.data* API to load my data off-disk.

For the sake of simplicity and reproducibility, let's consider the following "*sample_data.csv*" dataset:

| Label    | Feature 1 | Feature 2 | 
| -------- | --------- | --------- |
| Apple    | 1         | 2         |
| Banana   | 3         | 4         |
| Coconut  | 5         | 6         |
| Durian   | 7         | 8         |
| Eggplant | 9         | 10        |
| Fruit    | 11        | 12        |

I've tried using [tf.data.experimental.make_csv_dataset][1] to load the CSV files into *tf.data.Dataset* objects, and then [tf.keras.preprocessing.timeseries_dataset_from_array][2] to process the data into sliding windows with overlap. For the dataset above, I would do:

    import tensorflow as tf

    input_data = tf.data.experimental.make_csv_dataset(
        'sample_data.csv',
        batch_size=1,
        column_names=['Label', 'Feature 1', 'Feature 2']
        label_name='Label',
        num_epochs=1,
        shuffle=False
    )

Which we can check works correctly by looking at the output from `list(input_data.as_numpy_iterator())`:
```
[319:]   [(OrderedDict([('Feature 1', array([1])), ('Feature 2', array([2]))]),
          array([b'Apple'], dtype=object)),
         (OrderedDict([('Feature 1', array([3])), ('Feature 2', array([4]))]),
          array([b'Banana'], dtype=object)),
         (OrderedDict([('Feature 1', array([5])), ('Feature 2', array([6]))]),
          array([b'Coconut'], dtype=object)),
         (OrderedDict([('Feature 1', array([7])), ('Feature 2', array([8]))]),
          array([b'Durian'], dtype=object)),
         (OrderedDict([('Feature 1', array([9])), ('Feature 2', array([10]))]),
          array([b'Eggplant'], dtype=object)),
         (OrderedDict([('Feature 1', array([11])), ('Feature 2', array([12]))]),
          array([b'Fruit'], dtype=object))]
```

We can then feed `input_data` to the next function:

    my_dataset = tf.keras.preprocessing.timeseries_dataset_from_array(
        input_data,
        targets=None,
        sequence_length=3,
        sequence_stride=2,
        sampling_rate=1,  
        batch_size=1,
        shuffle=False
    )

Which unfortunately **throws this error**:

    [342]:  ~\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in __len__(self)
            452       raise TypeError("dataset length is infinite.")
            453     if length.numpy() == UNKNOWN:
        --> 454       raise TypeError("dataset length is unknown.")
            455     return length
            456 
    
    TypeError: dataset length is unknown.

I also tried using `my_dataset = input_data.window(3, shift=2)` (see the [tf.data.Dataset.window][3] documentation) and it didn't throw an error, but it seems to be returning an **empty dataset**? See "*_VariantDataset shapes: (None,)*" in the output:

    list(input_data.window(3, shift=2))

    [344]:
    [(OrderedDict([('Feature 1',
                    <_VariantDataset shapes: (None,), types: tf.int32>),
                   ('Feature 2',
                    <_VariantDataset shapes: (None,), types: tf.int32>)]),
      <_VariantDataset shapes: (None,), types: tf.string>),
     (OrderedDict([('Feature 1',
                    <_VariantDataset shapes: (None,), types: tf.int32>),
                   ('Feature 2',
                    <_VariantDataset shapes: (None,), types: tf.int32>)]),
      <_VariantDataset shapes: (None,), types: tf.string>),
     (OrderedDict([('Feature 1',
                    <_VariantDataset shapes: (None,), types: tf.int32>),
                   ('Feature 2',
                    <_VariantDataset shapes: (None,), types: tf.int32>)]),
      <_VariantDataset shapes: (None,), types: tf.string>)]

If I load the "*sample_data.csv*" in memory using pandas and then feed the *timeseries_dataset_from_array* function a numpy array instead, it works correctly.

Any ideas on how to solve this? **What's the best method to input overlapping windows from off-memory time-series data into TensorFlow**?

Thank you!

  [1]: https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset
  [2]: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/timeseries_dataset_from_array
  [3]: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#window

**Comment by tilakrayal** [comment]
@alexispomares ,

In order to reproduce the issue reported here, could you please provide the tensorflow version,complete code and the dataset or colab link you are using . Thanks!
