### ISSUE TITLE
Failure to load model files.

### ISSUE THREAD

**Issue by Anuj040** [tensorflow/tensorflow#49162]
I have a tensorflow model that I train using customizing the model.fit() as in following link
https://keras.io/guides/customizing_what_happens_in_fit/
Now when I save the model using ModelCheckpoint callback and then later try to reload the model (using tf.keras.models.Model.load_model) or weights (model.load_weights), I am unable to do that, with the following errors:

with _.load_model()_
> ValueError: No model found in config file. 

with _.load_weights()_
> ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.

My models are defined using FunctionalAPI (https://keras.io/guides/functional_api/).

I am currently working with tensorflow==2.4.1 but I have faced a similar issue with 2.2.0 before.

Back then, to solve this issue, I wrote my own custom callback to save the model (using `.save()`) and then reload with `.load_model()`, as I discuss in this article [link](https://medium.com/dive-into-ml-ai/customization-of-model-fit-to-write-a-combined-discriminator-generator-gan-trainer-in-keras-524bce10cf66). But I was wondering if there is a default way to this.

**Comment by UsharaniPagadala** [comment]
@Anuj040 

In order to expedite the trouble-shooting process, please provide a code snippet/ colab gist to reproduce the issue reported here and  Could you please [try](https://www.tensorflow.org/guide/keras/save_and_serialize) this, if it helps.Thanks!

**Comment by Anuj040** [comment]
Here is the [gist](https://gist.github.com/Anuj040/77a5ec315d8c5693f7e5e8dcb1072484.j).
I tried both the methods _load_model()_ method in the gist. 
so my question is what is the best way to save and load model if I am working with custom model.fit().
All help will be immensely appreciated.

**Comment by Anuj040** [comment]
Any updates/recommendations?

**Comment by UsharaniPagadala** [comment]
@Anuj040 

I was able to reproduce the error and here is the [gist](https://colab.research.google.com/gist/UsharaniPagadala/4b973157398c7bae0c1d59fdac99474f/untitled68.ipynb)

looking at the error log,seems this is similar to the issue  [#29545](https://github.com/tensorflow/tensorflow/issues/29545). Thanks

**Comment by UsharaniPagadala** [comment]
@jvishnuvardhan  Please take a look at this issue

I was able to reproduce the error.please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/4b973157398c7bae0c1d59fdac99474f/untitled68.ipynb) here.Thanks

**Comment by Anuj040** [comment]
Sorry for the delay in my response. 
Unfortunately, the suggested  issue #29545 does not seem to be connected to my issue, since I am working with _ModelCheckpoint_ callback.

Even if I remove the _file extension_ from the save file path, on trying to use _KM.load_model_ with the saved model object(s), throws the following error
![image](https://user-images.githubusercontent.com/66895104/120911185-f831d280-c6bf-11eb-8b29-670c66724ec8.png)

Further help would be immensely appreciated.

**Comment by Anuj040** [comment]
Just following up.

**Comment by jvishnuvardhan** [comment]
@Anuj040 Sorry for the late response. I could reproduce the issue. I was able to save and load simple models using ModelCheckPoint callback but with the custom training and custom metrics, it is throwing an error. 

As Keras moved to completely different repo to focus only on keras related issues, code owners are looking into the issues opened in new repo https://github.com/keras-team/keras/issues. Would you mind opening there and close it here. Thanks!

**Comment by Anuj040** [comment]
@jvishnuvardhan Sorry for my late response and thanks a lot for getting back on this. I will move the issue to the mentioned repo.
