### ISSUE TITLE
TF2.5.0 pip package depends on keras-nightly

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#49179]
**Describe the problem**

`pip install tensorflow==2.5.0` installs `keras-nightly`. Is that intended?

**Any other info / logs**
https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/tools/pip_package/setup.py#L105-L107

**Comment by mihaimaruseac** [comment]
It wasn't intended but given than there are no more `keras-nightly` releases with the same major.minor, this is effectively frozen.

We will patch in a future patch release once Keras has a new stable release, if possible. If not, we'll fix in 2.6

**Comment by UsharaniPagadala** [comment]
@bersbersbers 
Could you  please check the above comment by **mihai**  and please confirm if the issue still persist.Thanks

**Comment by bersbersbers** [comment]
There is a similar issue with TF2.8.0, which depends on `tf-estimator-nightly`. I won't reopen this issue since I believe it does not have any technical implications, but it surely looks weird to the user (and I wouldn't be surprised if `tf-estimator-nightly` interfered with a separately installed `tensorflow-estimator` package, which may be a different version.)

**Comment by mihaimaruseac** [comment]
That is correct, it is an issue on our release process that this keeps happening. Apologies for this.

Fortunately, I don't think there will be any issue in this case, but if we discover a bug that impact users we will do a patch release to fix. Estimator is deprecated and used only in maintenance mode, so there shouldn't be any breakages, but we're open to being wrong and fixing this in 2.8.1, if needed.
