### ISSUE TITLE
Tensorflow GPU Instructions should be updated for TF 2.5 and CUDA 11.2

### ISSUE THREAD

**Issue by TylerADavis** [tensorflow/tensorflow#49175]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu#windows_setup
https://github.com/tensorflow/docs/blob/master/site/en/install/gpu.md

## Description of issue (what needs changing):

[TensorFlow 2.5](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0) is built against CUDA 11.2 and cuDNN 8.1.0. However, the GPU instructions still refer to CUDA 11.0 and cuDNN 8.0.4. I believe that for the sake of clarity these should be updated to match TF 2.5. This includes both the installation commands for Linux and the path commands for Windows.

### Submit a pull request?

I'd be glad to submit a PR for the windows instructions, but I don't currently have access to a machine I can use to verify the Linux steps.

**Comment by PCJimmmy** [comment]
I just refreshed 3 machines on Ubuntu 20.04 to run machine learning using tf.  I noticed when installing tf that we are now version 2.5.  I made a specific check on tf web site to determine cuda and cudnn versions to install.  All machines have dual GPU and getting them running in tf is very dependent on the right cuda/cudnn.

You wasted my time by NOT updating GPU instructions - in fact the page I found shows that 2.4 and 2.5 still want 8/11.

**Comment by Saduf2019** [comment]
@TylerADavis 
The GPU page has been updated with latest information on [test build configurations](https://www.tensorflow.org/install/source?hl=en), kindly move this to closed status as resolved.

**Comment by TylerADavis** [comment]
@Saduf2019 Which page is it that got updated? While I can see that the [GPU tested configurations](https://www.tensorflow.org/install/source?hl=en#gpu) reference CUDA 11.2 and cuDNN 8.1, the GPU install page still references CUDA 11.0 and cuDNN 8.0, both on [github](https://github.com/tensorflow/docs/blob/master/site/en/install/gpu.md) and the [live site](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110)

**Comment by TylerADavis** [comment]
This issue should not be closed yet. It has been partially addressed by #1900, but not fully addressed yet.

**Comment by Saduf2019** [comment]
Moving this issue to closed status as PR is merged.

**Comment by itsayellow** [comment]
The PR https://github.com/tensorflow/docs/pull/1900 did not solve this issue.  The installation instructions still refer to out-of-date libraries.  Section https://www.tensorflow.org/install/gpu#install_cuda_with_apt instructions still refer to CUDA 11.0, not 11.2 as the first half of docs specify.

This: https://github.com/tensorflow/tensorflow/issues/49855#issue-905015666 is currently the only source of how to install the proper libnvinfer libraries.  It needs to be added to the gpu.md page install_cudo_with_apt instructions.
