### ISSUE TITLE
File system scheme '[local]' not implemented on TPU

### ISSUE THREAD

**Issue by RookieZB** [tensorflow/tensorflow#49177]
Hello, I have a task to train a model with millions of images using TPU, so I plan to load local data batch by batch when training. The main function to load data is shown below.

`def batch_processing(image):
    image1 = tf.image.decode_jpeg(tf.io.read_file(image), 3)
    return tf.image.resize(image1, [IMGSIZE, IMGSIZE])/255.

def data_loading(path, data, batch, buffer=1000, training=False):
    img1, start1 = [], 0
    
    while start1 < len(data):
        path1 = data['image_id'][start1:start1+buffer]
        img1 += path1.apply(lambda x: path+'train/'+x[0]+'/'+x[1]+'/'+x[2]+'/'+x+'.png').tolist()
        start1 += buffer

    set1 = tf.data.Dataset.from_tensor_slices((img1))
    set1 = set1.map(batch_processing, num_parallel_calls=AUTOTUNE)
    set1 = set1.shuffle(buffer).batch(batch) if training else set1.batch(batch)
    set1 = set1.prefetch(buffer_size=AUTOTUNE)
    return tpu_strategy.experimental_distribute_datasets_from_function(lambda _: set1)`

However, I have got an error "File system scheme '[local]' not implemented". Since this code works on GPU, I think such local file scheme isn't supported on TPU currently. Could you please tell me how to deal with this problem, when I have too many local images to load?

Thank you!

**Comment by king398** [comment]
Instead of using something like tf.io use os or PIL
https://stackoverflow.com/questions/62870656/file-system-scheme-local-not-implemented-in-google-colab-tpu

**Comment by RookieZB** [comment]
> Instead of using something like tf.io use os or PIL
> https://stackoverflow.com/questions/62870656/file-system-scheme-local-not-implemented-in-google-colab-tpu

I see, thank you.

**Comment by bhack** [comment]
See also https://github.com/google-research/language/issues/54
