### ISSUE TITLE
Installing tensorflow-gpu and upgrade grpcio

### ISSUE THREAD

**Issue by Chugua** [tensorflow/tensorflow#49185]
I have never had this problem before today, but now when I run code I have these errors:

`!pip install tensorflow-gpu >> /dev/null`

```
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
```

`!pip install --upgrade grpcio >> /dev/null`

```
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.37.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
ERROR: tensorflow-gpu 2.5.0 has requirement grpcio~=1.34.0, but you'll have grpcio 1.37.1 which is incompatible.
```

**Comment by bhack** [comment]
Can you try with ```!pip install --upgrade tensorflow-gpu >> /dev/null```

**Comment by Chugua** [comment]
> Can you try with `!pip install --upgrade tensorflow-gpu >> /dev/null`

There is the same Error:

`!pip install --upgrade tensorflow-gpu >> /dev/null`

```
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
```

**Comment by bhack** [comment]
Are you trying to install this in a fresh python env?

**Comment by bhack** [comment]
On colab: `pip install --upgrade tensorflow-gpu` will install tensorflow 2.5.0.

**Comment by Chugua** [comment]
> Are you trying to install this in a fresh python env?

Yes, I select "Factory reset runtime" in Colab and next run this code but the Error is the same

**Comment by bhack** [comment]
Why you need to install grpcio explicitly? TF 2.5.0 already install `grpcio~=1.34.0`

**Comment by Chugua** [comment]
Okay let's remove it but `pip install --upgrade tensorflow-gpu` still has an Error and when I run the model to train, training time is totally huge:
`4/10752 [..............................] - ETA: 92:54:27 - loss: 0.9374 - acc: 0.4141`

While before today it was just 2 hour.

**Comment by bhack** [comment]
Ok but i think this is tracked at https://github.com/tensorflow/tensorflow/issues/49190 and you can close this.

**Comment by Chugua** [comment]
> Ok but i think this is tracked at #49190 and you can close this.

But the problem is not solved here

**Comment by bhack** [comment]
Yes but we cannot have duplicate tickets

**Comment by Chugua** [comment]
Okay, I will close this, but please help to solve it, because I have almost finished my project and suddenly this issue appeared...
