### ISSUE TITLE
BUG: `RESHAPE` op is not always compatible with the `resize_tensor_input` method of the TF Lite Interpreter

### ISSUE THREAD

**Issue by mikolajpabiszczak** [tensorflow/tensorflow#49183]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur 11.2.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): v2.4.0-49-g85c8b2a817f (2.4.1)

**Provide the text output from tflite_convert**
N/A

**Description**
`RESHAPE` op (as converted from `tf.reshape` + `tf.shape` functions) is not compatible with the `resize_tensor_input` method of the TF Lite `Interpreter` when the tflite model is obtained from the model with the known input shape (e.g., the known shape being `(1, 1, 16000)`). In this case the `allocate_tensors` method called after `resize_tensor_input` (e.g., with the new input shape being `(1, 1, 32000)`) results in the

```
RuntimeError: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (32000 != 16000)Node number 0 (RESHAPE) failed to prepare.
```

On the other hand, when the tflite model is obtained from the model with partially unknown input shape (e.g. `(1, 1, None)`) then `resize_tensor_input` works correctly.

**Standalone code to reproduce the issue** 
Please see a Colab Notebook [here](https://colab.research.google.com/drive/1WEQbsJeB3cqQKVfsfuQsXvyTfh3FeF9A?usp=sharing) for a more detailed presentation of the issue (the last cell in the notebook results in the `RuntimeError` mentioned above).

**Any other info / logs**
N/A

**Comment by abattery** [comment]
This is an intended behavior. If you want to resize input tensors without any issues, the corresponding TF model should have dynamic dimension support on the specific dimensions, which should be overided.
