### ISSUE TITLE
Is it possible to use Sparse Tensor in Distributed Tensorflow ? 

### ISSUE THREAD

**Issue by sat2000pts** [tensorflow/tensorflow#49184]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hey everyone,

I have been trying to feed sparse tensor as an input into my distributed tensorflow model. The struggle is real at the moment, it doesn't seem to work -> all I get is this error message which makes me wonder is it even possible with tensorflow ?

`TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("cond_1/Identity:0", shape=(None, 3), dtype=int64, device=/job:worker/replica:0/task:0/device:CPU:0), values=Tensor("sequential/dense/Cast:0", shape=(None,), dtype=float32, device=/job:worker/replica:0/task:0/device:CPU:0), dense_shape=Tensor("cond_1/Identity_2:0", shape=(3,), dtype=int64, device=/job:worker/replica:0/task:0/device:CPU:0)). Consider casting elements to a supported type.`

Indeed, I have been reading other issue that others faced when using sparse tensor and the workaround that had been mentioned was to cast it to dense during runtime. However, the the training speed is heavily effected by it, at least for me causing it run 1 hour and 30 minutes per epoch whereas running it locally its 4 minute per epoch (**mind blown**) 

Best regards and stay safe

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Chugua** [comment]
I have never had this problem before today, but now when I run code I have these errors:
```
!pip install tensorflow-gpu >> /dev/null

ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
```

```
!pip install --upgrade grpcio >> /dev/null

ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.37.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
ERROR: tensorflow-gpu 2.5.0 has requirement grpcio~=1.34.0, but you'll have grpcio 1.37.1 which is incompatible.
```

**Comment by tilakrayal** [comment]
@sat2000pts ,

In order to reproduce the issue reported here, could you please provide the Tensorflow version, complete code and the dataset you are using. Thanks!

**Comment by Saduf2019** [comment]
@sat2000pts 
from the error logs it does not appear to be an incompatibility issue between the sparse tensor and training pipeline, can you isolate a single layer, try feeding the sparse inputs ti it and let us know.
