### ISSUE TITLE
the ceritificate for mirror.tensorflow.org is invalid

### ISSUE THREAD

**Issue by SarMesga** [tensorflow/tensorflow#49191]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 10.2/8.2
- GPU model and memory:

**Describe the problem**
while building tensorflow the following link is used by bazel to download an extension for aws:
https://mirror.tensorflow.org/github.com/aws/aws-sdk-cpp/archive
The Certificate under that link isn't for mirror.tensorflow.org but for *.storage.googleapis.com

**Provide the exact sequence of commands / steps that you executed before running into the problem**
not applicable

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
#37284
