### ISSUE TITLE
Can't save checkpoint when using multi-cells RNN

### ISSUE THREAD

**Issue by uebian** [tensorflow/tensorflow#49193]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: Python 3.7.6
- CUDA/cuDNN version: 11.3
- GPU model and memory: NVIDIA Corporation GV100GL [Tesla V100 PCIe 32GB] 

**Describe the current behavior**
I'm using multi-cells RNN with the following code:
```python
self.rnn_cells = [tf.keras.layers.LSTMCell(self.cfg.hidden_units) for _ in range(self.cfg.depth)]
self.encoder = tf.keras.layers.RNN(
    self.rnn_cells, return_sequences=True, return_state=True)
```
And I'm using `tf.train.Checkpoint` and `tf.train.CheckpointManager` to save checkpoint of my model.

However, `self.manager.save()` throws an error that is paste below:
```
ValueError: Unable to save the object ListWrapper([<tensorflow.python.keras.layers.recurrent_v2.LSTMCell object at 0x7f24a2c08f90>, <tensorflow.python.keras.layers.recurrent_v2.LSTMCell object at 0x7f24a2bc5810>, <tensorflow.python.keras.layers.recurrent_v2.LSTMCell object at 0x7f24a2bc5f10>, <tensorflow_addons.seq2seq.attention_wrapper.AttentionWrapper object at 0x7f24a3ee1090>]) (a list wrapper constructed to track trackable TensorFlow objects). A list element was replaced (__setitem__, __setslice__), deleted (__delitem__, __delslice__), or moved (sort). In order to support restoration on object creation, tracking is exclusively for append-only data structures.

If you don't need this list checkpointed, wrap it in a non-trackable object; it will be subsequently ignored.
```
**Describe the expected behavior**
`self.manager.save()`  can save the model correctly.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): No, I don't know how to solve this problem

**Comment by bhack** [comment]
Can you share a very minimal standalone example or a Colab that we could copy, paste and run?

**Comment by uebian** [comment]
Thanks for your reply, and I have found the mistake I made when trying to write a minimal standalone example.
