### ISSUE TITLE
Tensorflower gardener reverting changes made in PRs

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorflow#49201]
I had a couple of PRs merged before release of 2.5, and one after that. None of the changes in those PRs are now reflected in the code on master branch. Is this some internal process? 
The PRs before release are  #48000 #48491 and the one after the release is #48610

In all the three PRs, if we see in the History section of the file, we see Tensorflower gardener pushing the changes, but reverting them in the very next commit under the title "Internal change". Can someone please tell what's going on?

Following are the screenshots as well as links to the commits made by tensorflower-gardener

#48000: [Internal change](https://github.com/tensorflow/tensorflow/commit/a08001f32afab9952f27cd0b5fe15352569ce93e#diff-aedc7bfa50b8c6005dd96fb3d7f2d01d7d5538933829cbb52d11ced51e37eece)
![image](https://user-images.githubusercontent.com/64411306/118349261-46463100-b56d-11eb-8adc-8b09c5abbc55.png)

#48610: [Internal change](https://github.com/tensorflow/tensorflow/commit/0174bcb337e2c8e7d6782b60b094ea70460ad071#diff-f52657292a8a14c55f02a6cdacca9172be68e3fee9cd722cb5ac7d27326ecf9c)
![image](https://user-images.githubusercontent.com/64411306/118349280-6e359480-b56d-11eb-85bd-321fabbbd551.png)

**Comment by bhack** [comment]
In general, we are trying to be a little bit more transparent about this process and to automate the notification to the contibutors.

See https://github.com/google/copybara/issues/155

/cc @mihaimaruseac @nikitamaia @theadactyl

**Comment by AdityaKane2001** [comment]
@bhack 
Ok,  but what does that mean about the PRs? Are they reassessed internally or something?

Also, on a side note, about the DepthwiseConv1D issue, I couldn't get it to build on my PC with a quarter of the resources. Thus, I will  try to use colab for that henceforth.

**Comment by bhack** [comment]
It about something that was gone wrong internally so you are not the only one and we have other rollback conmit. You can see a recent one at https://github.com/tensorflow/tensorflow/commit/07dd16b3a09e0cfa007d9694251dd6b2cbdf36ad

About Depthwise please leave a comment about your compiling experience/issues in its own ticket as It could have something in common to other contributors candidates experience.

**Comment by AdityaKane2001** [comment]
Yes, I saw that some of the merged PRs by external contributors were rolled back. So, I suppose those will be merged again later, right?

>About Depthwise please leave a comment about your compiling experience/issues in its own ticket as It could have something in common to other contributors candidates experience.

Sure, will do

**Comment by bhack** [comment]
> So, I suppose those will be merged again later, right?

I don't think so as on Github you cannot re-open/unmerge PRs.

This why I want to improve the bot to automatically notify PR and re-open Its own linked ISSUES (when available) on rollbacks.

Then the internal Team member/reviewer can add additional comments about what happened internally and if the contributor can do something else and re-open a new "clone PR".

Probably there is also a better process but I currently I have no internal visibility to understand why rollbacks happens and why they are not blocked before merge by CI checks (probably Is this related to some missing coverage about internal assets?)

**Comment by AdityaKane2001** [comment]
Got it, thanks

**Comment by mihaimaruseac** [comment]
So, internally all Google code (from all projects) is in one big repository. We have tests for other projects that depend on TF. when any test is broken, there is an automatic rollback phase. Sometimes, some Googler that saw the PRs is able to notify the PR that it got rolled back, provide help as to why that happened, etc. But this is not a given, sadly.

**Comment by bhack** [comment]
I still think that we have margins to automate the bot as copybara API are available.

**Comment by AdityaKane2001** [comment]
@mihaimaruseac 
Thanks for the explanation. In that case is there any way that I can make sure that future PRs are clean?

**Comment by mihaimaruseac** [comment]
There is some work that is currently planned for the OSS DevInfra team so that the gap between internal and external code is minimized. Unfortunately, if other projects rely on internal code there is nothing that can be done from the OSS side and someone in TF team needs to take to bring the other internal project up to date with the new changes.

**Comment by AdityaKane2001** [comment]
Thanks for the prompt and detailed explanation. Hoping that this problem will be resolved soon.

**Comment by UsharaniPagadala** [comment]
@AdityaKane2001 

Could you please move this issue to closed status ,as it is resolved.Thanks
