### ISSUE TITLE
Model re-compilation updated under Distributed Mirror Strategy issue

### ISSUE THREAD

**Issue by EdouardDKP** [tensorflow/tensorflow#49204]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution : Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2080 Ti x4

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am faced to an issue with Tensorflow with a model trained on multiple GPUs (x4) with the Distributed Mirror Strategy. 
The first training works perfectly with the Distributed Mirror Strategy.
After, I want to update some parameters (in the same run) such as learning rate, optimizer. The model compilation works perfectly and when the new training sequence is starting, I got the error below.

Here is my code. Do you have any advise to avoid this error and the training stop ? When I reload the model and run the next step of the training, it works but not in the pipeline. Do you have any idea ?
```
mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
    # Everything that creates variables should be under the strategy scope.
    # In general this is only model construction & `compile()`.

    print("[INFO] compiling model...")
    baseModel, headModel, model = get_model(LastLayerNeurons=20, DropOut=0.5)

    for layer in baseModel.layers:
        layer.trainable = False

    # construct the set of metrics
    metrics = ['accuracy']
    opt = SGD(lr=1e-3)
    model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=metrics)

print("[INFO] training head...")
model.fit(train_dataset,
          steps_per_epoch=steps_per_epoch,
          validation_data=val_dataset,
          validation_steps=validation_steps,
          epochs=10,
          max_queue_size=500,
          callbacks=callbacks,
          verbose=1,
          use_multiprocessing=True,
          workers=20)

with mirrored_strategy.scope():
    print("[INFO] re-compiling model...")

    for layer in model.layers[:]:  # Dernier block i.e #5
        layer.trainable = True

    # construct the set of metrics
    metrics = ['accuracy']

    opt = SGD(lr=1e-4)
    model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=metrics)

print("[INFO] fine-tuning V2 model...")
model.fit(train_dataset,
        steps_per_epoch=steps_per_epoch,
        validation_data=val_dataset,
        validation_steps=validation_steps,
        epochs=100,
        max_queue_size=500,
        callbacks=callbacks,
        verbose=1,
        use_multiprocessing=True,
        workers=20)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f1bc3ea32b0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
```

**Comment by UsharaniPagadala** [comment]
@EdouardDKP 
Could you please share the colab gist with all the dependencies as to analyse the issue reported here.Thanks

**Comment by EdouardDKP** [comment]
Hello,
I have tested to add the code below into my callbacks files. Thanks to that, that works.
No more issue at this time.
```
import matplotlib
matplotlib.use('Agg')

```
Best Regards

**Comment by UsharaniPagadala** [comment]
@EdouardDKP 

Thank you for your update, glad its working fine for you, kindly move this issue to closed status as it is resolved.
