### ISSUE TITLE
SSIM performance degradation in TF v2.5.0.

### ISSUE THREAD

**Issue by DarshanDeshpande** [tensorflow/tensorflow#49206]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0/2.5.0
- Python version: 3.7
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 
- GPU model and memory: K80 GPU

**Describe the current behavior**
SSIM has become extremely slow in TF 2.5.0 as compared to TF 2.4.x
Here are some tests I ran on Colab
```
import tensorflow as tf
print(tf.__version__) # 2.5.0

%%timeit
ssim_ = tf.image.ssim(tf.random.normal((30,500,500,1)), tf.random.normal((30,500,500,1)), 1)

OUTPUT:
1 loop, best of 5: 30.1 s per loop
```
```
import tensorflow as tf
print(tf.__version__) # 2.4.0

%%timeit
ssim_ = tf.image.ssim(tf.random.normal((30,500,500,1)), tf.random.normal((30,500,500,1)), 1)

OUTPUT:
10 loops, best of 5: 93.5 ms per loop
```
The timeit tests warn clearly that there might be some caching involved for the 2.4.0 test (which isn't available for 2.5.0 I assume, I don't know why. Caching should be enabled for 2.5.0 as well if its the default behaviour)

**Describe the expected behavior**
There is clear performance degradation between the two versions. I haven't gotten the time to go through the `tensorflow/python/ops/image_ops_impl.py` but I assume there is some implementation change that is causing this issue

**Comment by bhack** [comment]
Are you sure isn't related to the recurrent Colab issue we have on new releases?
See https://github.com/googlecolab/colabtools/issues/2013

**Comment by DarshanDeshpande** [comment]
@bhack it is possible but if that is the case then why do some Colab environments have 2.5.0 by default?

**Comment by bhack** [comment]
Currently I have only found `2.4.1` default if the specific Colab notebook  doesn't have an explicit `pip install tensorflow`

**Comment by DarshanDeshpande** [comment]
Okay, that was a problem on my end. Apparently, pip installing Tensorflow IO automatically upgrades tensorflow version to 2.5.0 to go with its 0.18 version. Closing this issue. Thanks!
