### ISSUE TITLE
ERROR when benchmarking TFLite model "ERROR: Given shapes, [1, 40, 23, 256] and [1, 23, 40, 256], are not broadcastable."

### ISSUE THREAD

**Issue by yann-pourcenoux** [tensorflow/tensorflow#49216]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04/Android 10
- Mobile device: Xiaomi Redmi Note 7
- TensorFlow installed from: pip
- TensorFlow version: v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: Python 3.8.8

**Describe the current behavior**
I am training a model and converting it to TFLite but when benchmarking it on TFLite I got an unexpected error shown below.
```
ERROR: Given shapes, [1, 40, 23, 256] and [1, 23, 40, 256], are not broadcastable.
ERROR: Node number 80 (ADD) failed to prepare.
```

**Describe the expected behavior**
Since the training works and that the shapes are good when I visualize the model in [netron](https://netron.app/), I expect it to work.
![image](https://user-images.githubusercontent.com/43449205/118394198-78c25d80-b643-11eb-8b43-c55521453662.png)

**Standalone code to reproduce the issue**
I am running the benchmark using the native tool which includes TFOps and Flex Delegate that can be downloaded [here](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_arm_benchmark_model_plus_flex).

My model can be downloaded [here](https://github.com/tensorflow/tensorflow/files/6489086/model.zip).
I run the benchmark on an android device using the following lines:
```
adb push android_arm_benchmark_model_plus_flex /data/local/tmp/benchmark
adb shell chmod +x /data/local/tmp/benchmark
adb push model.tflite /data/local/tmp/model.tflite
adb shell "/data/local/tmp/benchmark"  --graph="/data/local/tmp/model.tflite" --use_gpu=true --input_layer=input,scale_input --input_layer_shape=1,640,360,3:1,4
```

I do not understand where the error could be coming from since can train and run inference on the Tensorflow model and that the graph in Netron is good.

Thanks in advance!

**Comment by abattery** [comment]
@yann-pourcenoux could you try TF -> TFLite model conversion with the tf-nightly version to see the above issue already fixed? If possible, please share a minimal reproducible step for the TFLite conversion.

**Comment by yann-pourcenoux** [comment]
Thanks for your quick reply @abattery, I just tried with tf-nightly `2.6.0-dev20210516` and the error is still the same. I convert my model by doing:
```
mobile_model = create_model(...) # I'd rather not share this
converter = tf.lite.TFLiteConverter.from_keras_model(mobile_model)

# Set the optimizations of quantization 
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

# Experimental environment
converter.experimental_new_converter = True
converter.experimental_new_quantizer = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.
]

# Converting model
tflite_model = converter.convert()
with open(tflite_filepath, "wb") as f:
    f.write(tflite_model)
```

**Comment by abattery** [comment]
Sorry. It is really hard to reproduce your issue at our end. Please consider creating the simple and minimal reproducible steps as a gist and share it to us if possible.

**Comment by YannPourcenoux** [comment]
While creating a script to reproduce the issue, I realized I swapped the axis when specifying the input_shape for the benchmark. The error was then totally on my side.
Would adding something to ensure that the model is fed the expected shape be possible to prevent such mistakes?
Anyway, thanks again for your quick reply!

**Comment by abattery** [comment]
Thanks for the confirmation!

@multiverse-tf could you take a look at https://github.com/tensorflow/tensorflow/issues/49216#issuecomment-842566632?

**Comment by multiverse-tf** [comment]
> While creating a script to reproduce the issue, I realized I swapped the axis when specifying the input_shape for the benchmark. The error was then totally on my side.
> Would adding something to ensure that the model is fed the expected shape be possible to prevent such mistakes?
Good suggestion! Will add more input-shape-related checks asap.

> Anyway, thanks again @abattery for your quick reply!
