### ISSUE TITLE
C++ compilation of rule '@llvm-project//llvm:Passes' failed

### ISSUE THREAD

**Issue by parsa-ra** [tensorflow/tensorflow#49211]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): source (2.5.0 release)
- TensorFlow version: 2.5.0
- Python version: 3.8.7 GCC 7.5.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.3 / 8.2 
- GPU model and memory: NVIDIA GTX 1070 Ti / 8GB

**Describe the problem**
During the 
build process following error is thrown: 
[Logs+Config.zip](https://github.com/tensorflow/tensorflow/files/6488908/Logs%2BConfig.zip)

```C++ compilation of rule '@llvm-project//llvm:Passes' failed (Exit 4): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/llvm-project/llvm/_objs/Passes/PassBuilder.pic.d ... (remaining 59 argument(s) skipped)```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Detailed config and log files attached.

config => bazel build --local_ram_resources=4096 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by parsa-ra** [comment]
Any input?

**Comment by mihaimaruseac** [comment]
Closing due to no more updates
