### ISSUE TITLE
TF 2.0 'Tensor' object has no attribute 'numpy' while using .numpy() when use disable_eager_execution()

### ISSUE THREAD

**Issue by SongyiGao** [tensorflow/tensorflow#49217]
I need to convert tensor to numpy array in Graph mode.

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/issues/27519#issuecomment-490388556

**Comment by SongyiGao** [comment]
> Check [#27519 (comment)](https://github.com/tensorflow/tensorflow/issues/27519#issuecomment-490388556)

Thank you!   For some reason, I have to use Graph mode in my code and would like to find a solution.

**Comment by bhack** [comment]
If you expect to autoconvert a Tensor to numpy in graph mode we cannot support this. 
For the details see https://github.com/tensorflow/tensorflow/issues/38887

**Comment by Saduf2019** [comment]
@SongyiGao 
We do not suppport tensor to numpy in graph mode, you can try with the [experimental numpy API](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy).
