### ISSUE TITLE
FileSystem::GetMatchingPaths doesn't work for simple pattern

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#4921]
With latest tensorflow.

``` bash
$ ls
test
```

``` cpp
std::vector<string> results;
auto ret = tensorflow::Env::Default()->GetMatchingPaths("te*", &results);
cout << results.size() << endl;  // 0
ret = tensorflow::Env::Default()->GetMatchingPaths("./te*", &results);
cout << results.size() << endl;  // 1
```

Reason:
In the implementation of `GetMatchingPaths` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system.cc#L94), when the pattern doesn't contain any directory, the prefix `.` is prepended to all elements in `all_files`, and then `MatchPath("./test", "te*")` evals to false.

**Comment by jart** [comment]
Maybe there's something about the design we're not considering, but that seems counter-intuitive enough that maybe @rohan100jain could help clarify.

**Comment by osdf** [comment]
Coming from the linked issue #4913 I wonder if https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system.cc#L104 leads to the reported problem with `/tmp`. More specifically, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system.cc#L118 possibly add non-readable directories below `/tmp` which then should throw the `PermissionDeniedError`.

**Comment by ppwwyyxx** [comment]
Haven't tried c++, but at least from `tf.gfile.Glob`, the problem seems to be fixed already.
