### ISSUE TITLE
Makefile: No such file or directory ( Windows )

### ISSUE THREAD

**Issue by SlimSidhom** [tensorflow/tensorflow#49213]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
Trying to run the test_hello_world_test with make command, yet the Makefile is not present although I checked its presence in the directory...
**Please provide the exact sequence of commands/steps when you ran into the problem**

![issue](https://user-images.githubusercontent.com/44801135/118394269-8ffd4d00-b63b-11eb-8679-8b448965172b.jpg)

**Comment by ymodak** [comment]
Can you please remove `test_` prefix and try again?
`make -f tensorflow/lite/micro/tools/make/Makefile hello_world_test`

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
