### ISSUE TITLE
Add a new split way in split_v_op.cc

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#49212]
Now tensorflow has two way to split tensor.
1. Split tensor by single thread.
2. Split tensor by multi-thread.
The current data split method is not very uniform, like:
![image](https://user-images.githubusercontent.com/33950866/118393504-1f255780-b672-11eb-83b0-b39e9a580392.png)
We should add a new parallel split way. like:
![image](https://user-images.githubusercontent.com/33950866/118393518-2fd5cd80-b672-11eb-8f0b-eb1c1f999814.png)

example:
```
import tensorflow as tf
import time
sess_config = tf.ConfigProto(allow_soft_placement=False,
                             log_device_placement=True)

count = 3
keys = tf.random_uniform(shape=[4800, 107, 9], dtype=tf.int64, maxval=int(1e8))
arr = []
for i in range(0, 30):
  arr.append(1)
arr.append(77)
ret = tf.split(keys, arr, axis=1)

sess = tf.Session(config = sess_config)

start = time.time()
for i in range(0, 10):
    _ = sess.run(ret)
print('split_v seconds: %f' % (time.time() - start))
```
performance: 0.308505s vs 0.188766s

**Comment by zhaozheng09** [comment]
I am happy to contribute my code

**Comment by Saduf2019** [comment]
The issue will move to closed status once the PR is merged.

**Comment by Saduf2019** [comment]
Moving this to closed status as pr is merged.
