### ISSUE TITLE
Android: read model file from arbitrary directory rather than from assets folder

### ISSUE THREAD

**Issue by barantes** [tensorflow/tensorflow#4922]
Currently, TensorFlowInferenceInterface's method initializeTensorFlow() and its underlying C implementation (in tensorflow_inference_jni.cc and jni_utils.cc) require the usage of Android's AssetManager in order to read model files stored in the assets folder. 

How can we modify TF's code to provide an alternative way to run the classification using a model file that's not stored in the assets folder (i.e. a location described by a File object, or by a String path pointing to another location outside the assets folder).

Is there branch where someone might be working on this? I have poor C skills so as to make such change by myself, but maybe I can work on something with some guidance.

Thanks.

Bruno.

**Comment by andrewharp** [comment]
If you remove the `file:///android_asset/` prefix from the model file in [TensorFlowImageListener.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java), it should just work. There already exists code that can load from non-assets in the native C++ layer. If that prefix is not present it will attempt to treat the location as a regular filepath.

The label file in the example is a different matter, but this is not difficult to fix in [TensorFlowImageClassifier.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java). I have a TODO open for this already, and will update the code soon to be more flexible.

**Comment by barantes** [comment]
Hi Andrew. It works pretty well using the instructions above. Thanks for the help!

Bruno.

**Comment by ofermoshsaioff** [comment]
@andrewharp I tried loading a model from the external storage folder but got a runtime exception: 

`Caused by: java.lang.RuntimeException: Failed to load model from '/storage/emulated/0/optimized_tfdroid.pb'
                                                                 at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:92)
                                                                 at com.***.app.tensorflow.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:118)`

Using tensorflow-android-1.2.0. The file definitely exists, what am I doing wrong?

**Comment by tanmay-1srivastava** [comment]
Sir I am trying the same thing as above but could not program it. 
Could you please share your code
@andrewharp

**Comment by aayushthakur** [comment]
> Sir I am trying the same thing as above but could not program it.
> Could you please share your code
> @andrewharp

Instead of using the AssetFileDescriptor use it like this, pass the full file path in load model method

```
private MappedByteBuffer loadModelFile(String modelPath) throws IOException {
try (FileInputStream fileInputStream = new FileInputStream(
                new File(modelPath))) {
            FileChannel fileChannel = fileInputStream.getChannel();
            return fileChannel.map(MapMode.READ_ONLY, 0, fileChannel.size());
        }
    }
```
