### ISSUE TITLE
tensorflow lite chatbot and flutter integration

### ISSUE THREAD

**Issue by LijaAlex12** [tensorflow/tensorflow#49221]
I would like to know if a chatbot built using tensorflow and exported as tensorflow lite model can be integrated into flutter.

**Comment by bhack** [comment]
To use TF lite with flutter see https://pub.dev/packages/tflite
https://pub.dev/packages/tflite_flutter

**Comment by tilakrayal** [comment]
@LijaAlex12 ,

Please refer the links mentioned and let us know if it helps.Thanks!

**Comment by bhack** [comment]
ThIs ticket (example request) is now tracked at https://github.com/am15h/tflite_flutter_plugin/issues/116. 
We can close this.

**Comment by LijaAlex12** [comment]
Thank You Very Much.

**Comment by LijaAlex12** [comment]
@bhack
