### ISSUE TITLE
```tf.keras.callbacks.EarlyStopping``` always stops at the first epoch

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#49227]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): google colab
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- CUDA/cuDNN version:  cuda11.2 cudnn8.2.0
- GPU model and memory: gtx1070

**Describe the current behavior**

```tf.keras.callbacks.EarlyStopping``` always stops at the first epoch .
Here is the colab :

[https://colab.research.google.com/drive/1FvWFE26IPrc8vcfbfEGWLPASP6ZJIBPu?usp=sharing](https://colab.research.google.com/drive/1FvWFE26IPrc8vcfbfEGWLPASP6ZJIBPu?usp=sharing)

**Describe the expected behavior**

It should stops at the best epoch like tensorflow2.4.1 .

**Comment by UsharaniPagadala** [comment]
@DachuanZhao
I Could reproduce the code shared.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/c1e109fd66344c3c8e243b881411303f/untitled1.ipynb).
Note:I changed the code little bit added **patience** keyword,Please let me know if it works
Thanks

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> I Could reproduce the code shared.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/c1e109fd66344c3c8e243b881411303f/untitled1.ipynb).
> Note:I changed the code little bit added **patience** keyword,Please let me know if it works
> Thanks


It works when I change 
```
tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',verbose=1,mode="max",restore_best_weights=True)
```
to
```
tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',verbose=1,mode="max",restore_best_weights=True,patience=1e-7)
```
But the parameter ```patience``` default value is ```0``` , which causes this issue ...

**Comment by Saduf2019** [comment]
@DachuanZhao 
Patience has to be an integer, it denoted the number of epochs to wait for , 1e-7 is not acceptable form for an epoch. [as in [this gist](https://colab.research.google.com/gist/UsharaniPagadala/c1e109fd66344c3c8e243b881411303f/untitled1.ipynb)

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> Patience has to be an integer, it denotes the number of epochs to wait for , 1e-7 is not acceptable form for an epoch as in [this gist](https://colab.research.google.com/gist/UsharaniPagadala/c1e109fd66344c3c8e243b881411303f/untitled1.ipynb)

Get it . And  I think the default value of  ```patience``` should be ```1``` ...

**Comment by Saduf2019** [comment]
@DachuanZhao 
please go through [this link](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping), and [example here](https://machinelearningmastery.com/how-to-stop-training-deep-neural-networks-at-the-right-time-using-early-stopping/).

Detailed explanation on patience parameter  [is here](https://towardsdatascience.com/a-practical-introduction-to-early-stopping-in-machine-learning-550ac88bc8fd), for any fuurther queries please open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) link as done [here](https://stackoverflow.com/questions/50284898/keras-earlystopping-which-min-delta-and-patience-to-use) and move this to close status as it is not a bug or a feature request.

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> please go through [this link](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping), and [example here](https://machinelearningmastery.com/how-to-stop-training-deep-neural-networks-at-the-right-time-using-early-stopping/).
> 
> Detailed explanation on patience parameter [is here](https://towardsdatascience.com/a-practical-introduction-to-early-stopping-in-machine-learning-550ac88bc8fd), for any fuurther queries please open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) link as done [here](https://stackoverflow.com/questions/50284898/keras-earlystopping-which-min-delta-and-patience-to-use) and move this to close status as it is not a bug or a feature request.

Let me show you the difference between 2.4.1 and 2.5.0 : 

2.4.1:
```Python
  def on_epoch_end(self, epoch, logs=None):
    current = self.get_monitor_value(logs)
    if current is None:
      return
    if self.monitor_op(current - self.min_delta, self.best):
      self.best = current
      self.wait = 0
      if self.restore_best_weights:
        self.best_weights = self.model.get_weights()
    else:
      self.wait += 1
      if self.wait >= self.patience:
        self.stopped_epoch = epoch
        self.model.stop_training = True
        if self.restore_best_weights:
          if self.verbose > 0:
            print('Restoring model weights from the end of the best epoch.')
          self.model.set_weights(self.best_weights)
```
2.5.0 : 
```Python
  def on_epoch_end(self, epoch, logs=None):
    current = self.get_monitor_value(logs)
    if current is None:
      return
    if self.restore_best_weights and self.best_weights is None:
      # Restore the weights after first epoch if no progress is ever made.
      self.best_weights = self.model.get_weights()

    self.wait += 1
    if self._is_improvement(current, self.best):
      self.best = current
      if self.restore_best_weights:
        self.best_weights = self.model.get_weights()
      # Only restart wait if we beat both the baseline and our previous best.
      if self.baseline is None or self._is_improvement(current, self.baseline):
        self.wait = 0

    if self.wait >= self.patience:
      self.stopped_epoch = epoch
      self.model.stop_training = True
      if self.restore_best_weights and self.best_weights is not None:
        if self.verbose > 0:
          print('Restoring model weights from the end of the best epoch.')
        self.model.set_weights(self.best_weights)
```
In 2.4.1 , no matter what ```patience``` is, the training will reach the second epoch . But in 2.5.0 , when ```patience = 0``` , the training will stop the first epoch .

**Comment by Saduf2019** [comment]
@DachuanZhao 
Can you please share a colab gist with the above update, as i do not see any output for the above code.

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> Can you please share a colab gist with the above update, as i do not see any output for the above code.

What should  I share ? I think you will know what I means if you see the difference of the raw code between 2.4.1 and 2.5.0 ...

**Comment by jvishnuvardhan** [comment]
@DachuanZhao Thanks for creating this issue. This is a bug recently introduced. We will work on it to update. If you are interested in it, you can raise a PR. Thanks!

**Comment by DachuanZhao** [comment]
> @DachuanZhao Thanks for creating this issue. This is a bug recently introduced. We will work on it to update. If you are interested in it, you can raise a PR. Thanks!

I have raised a PR at [https://github.com/keras-team/keras/pull/14750](https://github.com/keras-team/keras/pull/14750)  : )
