### ISSUE TITLE
Use gpudelegates failed: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

### ISSUE THREAD

**Issue by Boya-Na** [tensorflow/tensorflow#49224]
Hi,
Thanks for the project first.

### 1. System information

- OS Platform and Distribution: convert on Linux Ubuntu 20.04
- TensorFlow installation: pip package
- TensorFlow library: 2.4.1

### 2. Code
This is the model summary: 

![image](https://user-images.githubusercontent.com/30684101/118437622-8a743580-b715-11eb-8d4f-8dbbc1532540.png)

Converter code:
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file('model.h5')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model = converter.convert()
with open(modelpath + '/model.tflite', 'wb') as f: 
        f.write(tflite_model)
print("save successfully")

### 3. Any other info / logs
I want to deploy a trained model in android with tflite and it has been deployed successfully in cpu, but when I want to use the delegate (like gpu & nnapi) to improve the performance, I get the error info: failed: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

I guessed that I may miss some steps to fix the size (maybe the batch size?) after loading the trained model and before converting, but I have no idea what step I missed and what API I should use.

I also searched the some solution in this repo but I didn't still get the solution. Is there any solution, suggestion, or tutorial, please? 

Thanks so much!

**Comment by abattery** [comment]
To fix the input shape, you can wrap your trained TF model with the tf.Module to limit the input tensors and output tensors like this [gist](https://colab.research.google.com/gist/abattery/c9c39317664100fa104447099da20574/tflite-signature-example.ipynb).

**Comment by Boya-Na** [comment]
Solved! Thanks so much!
