### ISSUE TITLE
Question Pertaining to TanH Implementation for TFLite

### ISSUE THREAD

**Issue by ShikharJ** [tensorflow/tensorflow#49235]
I was reading through the [TFLite Zero Skew Representation paper](https://arxiv.org/pdf/1712.05877.pdf) which makes a reference to the implementation of most mathematical functions [here](https://github.com/tensorflow/tensorflow/blob/4952f981be07b8bf508f8226f83c10cdafa3f0c4/tensorflow/contrib/lite/kernels/internal/optimized/optimized_ops.h). However, though the paper mentions the implementation of TanH function being available in the file, I couldn't find the fixed-point integer-only inference implementation of TanH. Can someone point me to the correct source please?

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/integer_ops/tanh.h

**Comment by ShikharJ** [comment]
@bhack Thanks for the link. Closing this issue for now.

**Comment by ShikharJ** [comment]
@bhack Would you have an idea regarding what's the functional difference between `lite/kernels/internal/reference` and `lite/kernels/internal/optimized` implementations of integer ops? Which one is used by default in TFLite?

**Comment by bhack** [comment]
References have more readability and I think they are also fallback of the optimized ones. E.g. see a PR for the TANH  in Micro https://github.com/tensorflow/tensorflow/pull/48052
