### ISSUE TITLE
Should tf 2.5.0 recognize GPU on Windows 10 with CUDA 11.3/cuDNN 8.2 installed?

### ISSUE THREAD

**Issue by pythonic2020** [tensorflow/tensorflow#49233]
[Tf docs](https://www.tensorflow.org/install/gpu#software_requirements) say that GPU support will work with CUDA 11, I assume meaning 11.* (??)

I have heard that tf GPU 2.5.0 is designed to work with CUDA 11.2 (https://github.com/tensorflow/tensorflow/issues/49190#issuecomment-841656229).

I have also heard that tf build failed with CUDA 11.3 libraries (#48803).  I assume this means that tf 2.5.0 GPU will NOT WORK with CUDA 11.3.  (??)

Can any Win 10 x64 users get their GPU recognized by tf 2.5.0 when CUDA 11.3/cuDNN 8.2 are installed?  If not, I assume I must downgrade CUDA to 11.2.2 and cuDNN to 8.1.1.

My GPU was recognized by tf 2.4.1 in my environment with CUDA 11.3.  After tf 2.5.0 was installed using pip, my GPU is no longer recognized.  

Thanks in advance!

**Comment by tilakrayal** [comment]
@pythonic2020 ,

Every TensorFlow release is compatible with a certain CUDA/cuDNN version, for more information please take a look at the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu).Please try installing TensorFlow v2.5 with respective CUDA  and cuDNN  and check if you are facing the same error. 

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.5.0 | 3.6-3.9 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.4.0 | 3.6-3.8 | MSVC 2019 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow_gpu-2.3.0 | 3.5-3.8 | MSVC 2019 | Bazel 3.1.0 | 7.6 | 10.1
tensorflow_gpu-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0 | 7.6 | 10.1

Thanks!

**Comment by pythonic2020** [comment]
Ok, I will try to downgrade my CUDA/cuDNN and see what happens.

**Comment by pythonic2020** [comment]
Several hours wasted.  TF 2.5.0 GPU will not recognize GPU using CUDA 11.0 (cuDNN 8.0.4), 11.2 (cuDNN 8.1.1), or 11.3 (cuDNN 8.2).  TF 2.4.1 GPU recognizes my GPU using all three of those.

So, I ask again if there is any evidence that TF 2.5.0 GPU will recognize GPU in a Python 3.8 environment on WIndows 10, and, if so, using what CUDA and cuDNN versions?

**Comment by pythonic2020** [comment]
I finally got my GPU recognized by TF 2.5.0 using CUDA 11.2.2 + cuDNN 8.1.1.  Before too long, they will move to CUDA 11.3.

**Comment by ymodak** [comment]
@pythonic2020 Sorry for the inconvenience the website was showing older versions of cuda cudnn compatibility. I have updated the docs to reflect the correct versions which you found compatible as well.
https://www.tensorflow.org/install/source#gpu

**Comment by pythonic2020** [comment]
Thank you, @ymodak!  The outdated versions on the [GPU Support page](https://www.tensorflow.org/install/gpu) are what misled and frustrated me.

**Comment by chanangaza** [comment]
> @pythonic2020 Sorry for the inconvenience the website was showing older versions of cuda cudnn compatibility. I have updated the docs to reflect the correct versions which you found compatible as well.
> https://www.tensorflow.org/install/source#gpu

why does it say that it requires Bazel 3.1.0 while in ./comfigure.py it has

_TF_MAX_BAZEL_VERSION = '3.99.0' ?

note: I am referring to tensorflow tag==2.5.0
