### ISSUE TITLE
API Documentation pages do not allow providing written feedback

### ISSUE THREAD

**Issue by lonerzzz** [tensorflow/tensorflow#49234]
## URL(s) with the issue:

All pages in the document including:
https://www.tensorflow.org/api_docs/python/tf

## Description of issue (what needs changing):
Right now, there is no simple means to provide feedback on the generated documentation aside from a thumbs up/thumbs down and limited multiple choice selection, making such feedback hardly useful. The API documentation at this stage is far too terse in many locations making it hard to use or unusable. It would make far more sense to allow written commentary to be collected against each page so that periodically, the software developers for each component could read the commentary and add necessary code comments to address the issues raised by people attempting to use the code.

Given that this is tensorflow machine learning documentation, it might even be possible to do natural language processing to extract common themes where people are running into issues.

The current system, like the angular documentation does seem like a conscious effort to avoid taking input from users and that really should not be the case.

**Comment by lonerzzz** [comment]
@rmothukuru What is tensorflower? I could not see a description in google search or in repos with that name.

**Comment by rmothukuru** [comment]
@lonerzzz,
Sorry for the confusion. Tensorflower means Google Engineer, working on Tensorflow.

**Comment by MarkDaoust** [comment]
Yeah, it's "TenaorFlow-er" not "Tensor-Flower 🌸" .

IIRC the site used have this feature, and it was just too hard to turn into actionable feedback beyond what we already knew from the ratings. Plus we have plenty of bugs in this queue already, we don't need a whole new queue.

We encourage you to use the ratings, we check that signal.
If you have more specific feedback (it sounds like you do), raise a bug like this one, or send us a PR with a fix.

**Comment by lonerzzz** [comment]
If you are using the ratings and pull down options , it would still make sense to have a larger set of selectable options as the set now is incomplete for communicating problems.
