### ISSUE TITLE
Tutorial on contrib (load_csv) no longer works, please suggest solution

### ISSUE THREAD

**Issue by chivalry123** [tensorflow/tensorflow#4923]
I try to follow the turotial here:

https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html

But I get the error:

221:tensorflow_tutorial ME$ python contrib_learn_quick_origin.py 
Traceback (most recent call last):
  File "contrib_learn_quick_origin.py", line 13, in <module>
    training_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TRAINING,
AttributeError: 'module' object has no attribute 'load_csv'

Please suggests solutions and edit the online tutorial.

**Comment by jart** [comment]
Thank you for reporting this. I wrote up a change which will get approved soon fixing this. Once it gets pushed to GitHub this issue will be closed.

**Comment by boing102** [comment]
Hi, 

im afraid it still doesnt work with the changes. The new method takes 3 arguments instead of 2. This is how i made it work:
`training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
       filename=IRIS_TRAINING, target_dtype=np.int, features_dtype=np.float32)
 test_set = tf.contrib.learn.datasets.base.load_csv_with_header(
       filename=IRIS_TEST, target_dtype=np.int, features_dtype=np.float32)`

**Comment by zafartahirov** [comment]
Also, the example files don't exist, so even changing the code will fail -- the files `iris_test.csv` and  `iris_train.csv` need to be committed.

**Comment by auxsophia** [comment]
Hey,

You can see the changed file and the .csv files here at the [TensorFlow github page](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/monitors):
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/monitors

Download the files to a folder and change:
`# Data sets
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"`

to
`# Data sets
IRIS_TRAINING = "<path_to_file>/iris_training.csv"
IRIS_TEST = "<path_to_file>/iris_test.csv"`

**Comment by itsmeolivia** [comment]
If you read through the tutorial, it provides the datasets and says to download into the same file as your python script.
