### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'

### ISSUE THREAD

**Issue by AldrichCabrera** [tensorflow/tensorflow#49245]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- TensorFlow version: 2.2.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11 / 8
- GPU model and memory: GTX 780

I'm trying to run Keras version 2.2.4 on Ubuntu 20.04 with python 3.8 and tensorflow 2.2.0 with CUDA 11.1 and I get the following error.

I've been looking around and according to me there is no stable version for python 3.8 using CUDA 11.1, I've tried to install different versions to solve the problem but in all of them I get the same thing.

**Comment by ymodak** [comment]
Did you try importing keras from tensorflow?
```python
import tensorflow as tf
tf.keras.layers.Dense(...)
```

**Comment by AldrichCabrera** [comment]
@ymodak I get the same issue.

**Comment by bhack** [comment]
TF 2.2.0 Is CUDA 10.1

**Comment by bhack** [comment]
P.s. CUDA® 11 (TensorFlow> = 2.4.0)

**Comment by AldrichCabrera** [comment]
Thank you. I've tryed and it works. Thank you!! :)

**Comment by UsharaniPagadala** [comment]
@AldrichCabrera 
Could you please confirm if the issue still persist.Thanks

**Comment by UsharaniPagadala** [comment]
@AldrichCabrera 

Could you please confirm if the issue still persist.Thanks

**Comment by AldrichCabrera** [comment]
@UsharaniPagadala The issue was solved. Thank you!!

**Comment by UsharaniPagadala** [comment]
@AldrichCabrera 

Thank you for your update, glad its working fine for you, kindly move this issue to closed status as it is resolved.
