### ISSUE TITLE
dependency conflict between tensorflow and tensorflow-text

### ISSUE THREAD

**Issue by marcvanzee** [tensorflow/tensorflow#49253]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 7.5.0-3ubuntu1~18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.5.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

This command keeps trying to install different versions of various packages:

```pip install --upgrade pip tensorflow tensorflow-text```

It makes the Flax CI builds fail on Github ([example](https://github.com/google/flax/runs/2605209071?check_suite_focus=true)). We temporary fixed this by using `tensorflow==2.4.1`: https://github.com/google/flax/pull/1327

**Comment by mihaimaruseac** [comment]
This seems more like using a broken pip resolver that backtracks too much. TF uses the resolver before this.

**Comment by mohantym** [comment]
Hi @marcvanzee ! I think it is not replicating in [TF 2.8 version ](https://colab.sandbox.google.com/gist/mohantym/a7180399bb7b9b0bf5648ee5e4091590/github_49253.ipynb). Attaching gist in [2.5](https://colab.sandbox.google.com/gist/mohantym/d80def0855f8b046ab4458c0b511a738/github_49253.ipynb#scrollTo=M-IhZeMsTpkp) too for reference. Thanks!
