### ISSUE TITLE
Is  CUPTI error  due to tensorflow version or NVIDIA CUPTI libary API change ?

### ISSUE THREAD

**Issue by lyw615** [tensorflow/tensorflow#49255]
The problem i met is in this issue  https://github.com/tensorflow/tensorflow/issues/35860.  I just want to confirm what raises this probelm. Is this due to the tensorflow version or the new version of   NVIDIA CUPTI libary? In tensorflow version belowing 2.0, my program runs normally.

**Comment by tilakrayal** [comment]
@lyw615 ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Also please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-585390769).Hope it helps.Thanks!

**Comment by lyw615** [comment]
> @lyw615 ,
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.
> 
> Also please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-585390769).Hope it helps.Thanks!

Thank you for your reply. I have read the comments you mentioned  before opening the issue.  I prepare to updating my project written by keras and tensorflow 1.x  with tensorflow 2.2.  The problem my project meet  is  describing in issue https://github.com/tensorflow/tensorflow/issues/35860  , and has been solved.   What confuses me  is the reason. From the comments your mentioned, it's  likely NVIDIA CUPTI libary API change.  So , is this due to the tensorflow higher version  or my local changed  version of NVIDIA CUPTI libary   API  ?

**Comment by tilakrayal** [comment]
@lyw615 ,

Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-585390769).Hope it helps.

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ymodak** [comment]
@lyw615 Its due to nvidia cupti api changes. See https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-844217651

**Comment by tilakrayal** [comment]
@lyw615 ,

Please move the issue to closed status as it answers your question.Thanks!

**Comment by lyw615** [comment]
The problem solved by closing tensorboard. For any better resolution , please feel free to leave messages.

**Comment by tilakrayal** [comment]
@lyw615 ,

Glad the issue is resolved for you, please move this to closed status.

**Comment by lyw615** [comment]
@tilakrayal This issue caused by change of nvidia cupti api . Has the newest version of tensorflow solved the problem?

**Comment by ymodak** [comment]
That's good point but the release notes for TF 2.5 don't mention any information regarding it. 
Note that the recent TF version (2.5) supports cuda 11.2 and cudnn 8.1 if you want to test it.
