### ISSUE TITLE
Question VM UPGRADE Tensorflow

### ISSUE THREAD

**Issue by CHIMRLINUX** [tensorflow/tensorflow#49256]
Hello

Quick question, we are upgrading our systems from standalone to Virtual Machine environment Via VMware. 

Specs is GPU Tesla T4 

We are unsure for Tensorflow what would work best however maybe you might know?

what works best to move Tensor flow onto the VM enviroment ? ie what hardware specs. 

thanks

CH

**Comment by bhack** [comment]
I don't think that we handle any specific request for VMware here but you could rely on third_party official infos:
https://docs.vmware.com/en/VMware-vSphere-Bitfusion/index.html
https://docs.vmware.com/en/VMware-vSphere-Bitfusion/3.0/Example-Guide/GUID-1C053853-4D83-4D94-A6F3-D6958478AAB2.html

**Comment by UsharaniPagadala** [comment]
@CHIMRLINUX 

Could please check the above comment and move this closed status,if it is resolved.Thanks

**Comment by CHIMRLINUX** [comment]
Please close this activity.

Thanks

Ciaran
