### ISSUE TITLE
[TFLite] Failed to create Hexagon delegate on REALME x50 Pro

### ISSUE THREAD

**Issue by jiaojiaoYe** [tensorflow/tensorflow#49258]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:realme x50 Pro
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):
- Python version: 3.6.8
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I use this device on Hexagon delegate before and get expected results. However, after some time, maybe because of system security patch upgrade, I can never create delegate on this device. When I run benchmark on Heaxagon delegate, it is aborted. 
![image](https://user-images.githubusercontent.com/21187757/118629720-70fbe800-b800-11eb-95e7-521366ecb873.png)
And when in Android App, it will  cause following log, which seems to fastrpc called failed:

05-17 21:28:02.051   869   869 I com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/rpcmem_android.c:143: rpcmem_init_internal: opened ION device fd 77, configured heap IDs: system (0x2000000), contig (0x400000), secure (0x200), secure flags (0x80080000)
05-17 21:28:02.051   869   869 I com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2540: fastrpc_apps_user_init done
05-17 21:28:02.051   869   869 I com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1971: open_device_node: no access to default device of domain 3, open thru HAL
05-17 21:28:02.052   644   644 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.dsp::IDspService sid=u:r:untrusted_app:s0:c110,c257,c512,c768 pid=869 scontext=u:r:untrusted_app:s0:c110,c257,c512,c768 tcontext=u:object_r:vendor_hal_dspmanager_hwservice:s0 tclass=hwservice_manager permissive=0
05-17 21:28:02.052   869   869 E dsp-client: DspClient.cpp (42): Error: DspClient: unable to acquire dspservice instance
05-17 21:28:02.052   869   869 E dsp-client: DspClient.cpp (82): Error: openSession: IDspManager session is NULL
05-17 21:28:02.052   869   869 E dsp-client: DspClient.cpp (131): Error: open_hal_session: failed to open session, error -1
05-17 21:28:02.052   869   869 E com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1988: Error 0: open_device_node failed for domain 3 (errno Success)
05-17 21:28:02.052   869   869 E com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2342: Error 0x57: apps_dev_init failed for domain 3, errno Success
05-17 21:28:02.052   869   869 E com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2440: Error 0x57: open_dev (-1) failed for domain 3
05-17 21:28:02.052   869   869 E com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1038: Error 0x57: remote_handle_open failed for hexagon_nn
05-17 21:28:02.052   869   869 E com.example.energy: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:918: Error 0x2c: remote_handle_invoke failed for handle 0xffffffff, method 27 on domain 3 (sc 0x1b000100)

**Describe the expected behavior**
create Hexagon delegate successfully

**Comment by abattery** [comment]
@karimnosseir could you take a look?

**Comment by karimnosseir** [comment]
Hi,

I think it's the SELinux polic "SELinux : avc: denied { find }"
Looks like in some system update they added policy to disabled access to the DSP.

If your device is rooted can you run
adb root
adb set enforce 0

then retry

Thanks

**Comment by rthadur** [comment]
cc @jvishnuvardhan

**Comment by jiaojiaoYe** [comment]
thanks for your reply. Yes, I also suspected to be a problem with the SELinux policy. But my deivce has not been rooted, I can not try to disable SELinux.

More vendors may update security patches in the future, this may affect more devices that use Hexagon delegate.  What can we do to reduce this phenomenon?

Looking forward to your reply， thanks.

**Comment by karimnosseir** [comment]
Qualcomm is working with manufacturers to resolve issues. So hopefully with future security patches they will lift the restriction.

Thanks
