### ISSUE TITLE
Performance drop if I do some operation between predictions.

### ISSUE THREAD

**Issue by Litchilitchy** [tensorflow/tensorflow#49254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 1.15
- Python version: 3.6

**Describe the current behavior**
I am using CPU to predict, the issue occurs in both MKL(installed by conda, tested both default and TF_MKL_DISABLED=1) and non-MKL tensorflow(installed by pip).

If I run code like this
```
# warm up
for i in range(1000):
    predict my data
```
the time cost would be normal, but if change to 
```
# warm up
for i in range(1000):
    do some operation, let's denote it as op
    predict my data
```
The performance will drop, depending on op time cost, it would drop from about 10ms each batch to about 20ms when `TF_MKL_DISABLED=1`

Normally, each batch cost about 10ms, the less cost op is, the less drop would be. If op is 1ms, predict cost would be 11ms, if op is 5ms, predict cost would be 13ms.

**Describe the expected behavior**
no matter what operation between the predicts, the performance would not drop.

**Standalone code to reproduce the issue**
I do not know whether this is a normal behavior. If code is needed, I would post a colab.

**Comment by saikumarchalla** [comment]
@Litchilitchy  Please provide the simple standalone code/ colab link to reproduce the issue at our end.

Also, Please upgrade Tensorflow version since 1.x is no more supported actively.Thanks!
