### ISSUE TITLE
How team has made an animated 3D block diagram on tensorflow website?

### ISSUE THREAD

**Issue by smartaquarius10** [tensorflow/tensorflow#49261]
Hello Team,

This issue is not related to tensorflow package or any of its working. I am learning designing and I just wanted to know how google tensorflow team has made such a beautiful animated block diagram on the website [www.tensorflow.org](https://www.tensorflow.org/).

I'm referring to this diagram:
![Untitled](https://user-images.githubusercontent.com/7824529/118642791-6558f300-b7f9-11eb-984b-867b05ec6316.png)

Can anyone suggest what software are needed and from where can I start. The motion light animation and building up of diagram looks pretty awesome the moment website opens.

Please let me know. Thank you.

**Comment by Saduf2019** [comment]
@smartaquarius10 
You can start with [flutter](https://www.udemy.com/course/flutter-bootcamp-with-dart/?utm_source=adwords&utm_medium=udemyads&utm_campaign=GoogleFlutter_v.PROF_la.EN_cc.INDIA&utm_content=deal4584&utm_term=_._ag_113517924890_._ad_501402139574_._kw_flutter+tutorial_._de_c_._dm__._pl__._ti_kwd-432000815711_._li_1007768_._pd__._&matchtype=e&gclid=Cj0KCQjw7pKFBhDUARIsAFUoMDbSbmce9FoJKlIK0PaSPxzb3B2cFDzvuIyW5sDOXxZD3FFjmx8XGf0aArIFEALw_wcB).
Kindly open a [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!

**Comment by smartaquarius10** [comment]
Sure. I wasn't aware of that. Really sorry. In future, will ask such questions there only. Thanks for helping :)

**Comment by Saduf2019** [comment]
@smartaquarius10 
Please move the issue to closed status as it is resolved.

**Comment by smartaquarius10** [comment]
Sure.

**Comment by Saduf2019** [comment]
> Sure.

Also,if you are keen on designing from scratch, you can always import an image in to illustrator, trace it then expand to get [svg](https://www.svgator.com) object

**Comment by smartaquarius10** [comment]
@Saduf2019 , Hmm ok. But r u sure that we can make such images or block diagrams in flutter. I checked but didn’t find anything useful. Do you know any software through which we can make such kind of static 3d block diagrams.
