### ISSUE TITLE
 "download_dependencies.sh" doesn't work

### ISSUE THREAD

**Issue by haolingzhang1** [tensorflow/tensorflow#49265]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Mac OS BigSur 11.2.3(arm64):
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tensorflow
- TensorFlow version (use command below): the latest
- Python version: 3.8
- GPU model and memory:

**Describe the current behavior**
I try to use tensorflowlite with ios , and when i followed the instructions to the step "download_dependencies.sh" ,it shows that : 
 usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

I think something wrong with "grep -oP"
**Describe the expected behavior**
download the resources 

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes): - Briefly describe your candidate solution
(if contributing):
modify the grep -oP

<img width="571" alt="截屏2021-05-18 下午9 28 15" src="https://user-images.githubusercontent.com/55579125/118660438-c8aa4b80-b820-11eb-9d9c-283ccd0cf1a2.png">

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@haolingzhang1 

seems like this is similar to issue [#35747](https://github.com/tensorflow/tensorflow/issues/35747). Please take a look at this and let us know if you are still facing the same issue. Thanks!

**Comment by haolingzhang1** [comment]
It's not the same problem I think , I put some "echo" to test and I found that the problem starts from line 37 in "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/download_dependencies.sh"
and I foun some notes in this file in line 64
# TODO(petewarden): Some new code in Eigen triggers a clang bug with iOS arm64,#                   so work around it by patching the source.

**Comment by ljluisjimenez12** [comment]
How did this shit end up in production in the first place???? Are u stupid??? and with a TODO note too !!!11

what the fuck is your cto or whatever thinking bout this?! is he happy? because if I'd be him I would be slapping all your shitfaces with my dick by now

**Comment by shobanasuresh** [comment]
I am also hitting this same issue related to grep usage when running download_dependencies.sh on macOS Big Sur.

Any recommendation for fix / workaround to resolve this issue?

**Comment by terryheo** [comment]
How about using CMake?
https://www.tensorflow.org/lite/guide/build_cmake

**Comment by shobanasuresh** [comment]
`grep -oP` is not supported on macOS. 

download_dependencies.sh script starts working for me on macOS after updating all `grep -oP` usage with an equivalent perl command as shown below

Replace
`EIGEN_COMMIT="$(grep -oP 'EIGEN_COMMIT = "\K[0-9a-f]{40}' "${EIGEN_WORKSPACE_BZL_PATH}")"`

with
`EIGEN_COMMIT=$( perl -ne 'if (/EIGEN_COMMIT = "([0-9a-f]{40})/) { print $1 . "\n" }' ${EIGEN_WORKSPACE_BZL_PATH} )`

**Comment by sylajarlind** [comment]
@shobanasuresh can you share file here?

**Comment by shobanasuresh** [comment]
@sylajarlind I've attached the modified download_dependencies.sh script

[download_dependencies.zip](https://github.com/tensorflow/tensorflow/files/6997138/download_dependencies.zip)

**Comment by shobanasuresh** [comment]
Hi @terryheo - Would you be able to checkin the changes in the script that I've attached in my comment above in the tensorflow repo? These new changes work on both macOs and linux machines.

**Comment by sylajarlind** [comment]
<img width="388" alt="Screen Shot 2021-08-17 at 10 30 06" src="https://user-images.githubusercontent.com/80002509/129691969-88ba8b4f-7556-497f-bcdb-acce94a0531d.png">
I cannot run your script either

**Comment by terryheo** [comment]
Hi, as I shared today,
https://groups.google.com/a/tensorflow.org/g/tflite/c/NJq6abdIXkU/m/Rssm4t3pAgAJ
the Makefile build is deprecated. Plz try to use CMake.
