### ISSUE TITLE
infinite dataset while it is actually finite from tf.data.experimental.choose_from_datasets

### ISSUE THREAD

**Issue by laplacericky** [tensorflow/tensorflow#49276]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip3 install
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.3 cudnn 8.2.0
- GPU model and memory: NVIDIA TITAN V 12 GB

**Describe the current behavior**
For datasets created by tf.data.experimental.choose_from_datasets
when I do len(dataset), it always say it is infinite but when I iterate it, it is actually finite and completely functional
The problem with this is that when I want to work with keras model like using model.evaluate with this dataset, it gives error 

**Standalone code to reproduce the issue**

```
import tensorflow as tf
datasets = [tf.data.Dataset.from_tensors("foo").repeat(),
            tf.data.Dataset.from_tensors("bar").repeat(),
            tf.data.Dataset.from_tensors("baz").repeat()]

choice_dataset = tf.data.Dataset.range(3).repeat(3)

result = tf.data.experimental.choose_from_datasets(datasets, choice_dataset)

len(result)
#TypeError: dataset length is infinite.

result.cardinality()
#<tf.Tensor: shape=(), dtype=int64, numpy=-1>

for i in result:
  print(i)
#finite and works fine

model.evaluate(result,verbose=0)
#ValueError: When providing an infinite dataset, you must specify the number of steps to run (if you did not intend to create an infinite dataset, make sure to not call `repeat()` on the dataset).
#i.e. no longer works with keras model


```

**Comment by bhack** [comment]
Can you check dataset `cardinality`?

**Comment by laplacericky** [comment]
> Can you check dataset `cardinality`?

cardinality() gives a tensor with value -1 which is the constant for INFINITE cardinality

**Comment by bhack** [comment]
I think that internally It use interleave:

https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/data/experimental/ops/interleave_ops.py#L305

You could try to assert the cardinality

https://github.com/tensorflow/tensorflow/issues/36531#issuecomment-587654123

**Comment by laplacericky** [comment]
> I think that internally It use interleave:
> 
> https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/data/experimental/ops/interleave_ops.py#L305
> 
> You could try to assert the cardinality
> 
> [#36531 (comment)](https://github.com/tensorflow/tensorflow/issues/36531#issuecomment-587654123)

Yes, after asserting the cardinality by 
`result = result.apply(tf.data.experimental.assert_cardinality(expected_cardinality))`,
it works with keras model.
Thx a lot!

**Comment by bhack** [comment]
@jsimsa Do you need that we need to add something to the documentation or can we close this?

**Comment by tilakrayal** [comment]
@laplacericky ,

Please feel free to move the issue to closed status, if the issue is resolved.

Thanks!

**Comment by laplacericky** [comment]
The solution working fine so far. I am closing this.
