### ISSUE TITLE
When swig is not available, ./configure exits silently

### ISSUE THREAD

**Issue by gunan** [tensorflow/tensorflow#4928]
### Environment info
Operating System:
Ubuntu 16.04 

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda 8.0, cudnn does not matter, installation issue

If installed from binary pip package, provide:
Installing from sources

1. The commit hash (`git rev-parse HEAD`) 55bd9ccdb21a41b7c4046a1c1f2115066ed1f9bc
2. The output of `bazel version` 0.3.2

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
git clone github.com/tensorflow/tensorflow
./configure

exits before full config  is complete silently.

@caisq  @davidzchen any ideas?

**Comment by davidzchen** [comment]
The problem is that if swig isn't found, we fail immediately and the following error handling code never executes. Further, since we are redirecting stderr (so that we can print a more helpful error message), if the command fails, it fails silently:

```bash
SWIG_PATH=`type -p swig 2> /dev/null`
```

Opened #4948 to fix this.
