### ISSUE TITLE
013057005309211

### ISSUE THREAD

**Issue by Georgeiva** [tensorflow/tensorflow#49297]
One master `const int left_x_index = in_x > 0.0 ? floorf(in_x) : 0;` so I think that we could close this

https://github.com/tensorflow/tensorflow/blob/3fd3ae1fbb10961dd1aa6805280674c781fd4609/tensorflow/core/kernels/image/resize_bilinear_op_gpu.cu.cc#L60-L63
https://github.com/tensorflow/tensorflow/issues/38389#issuecomment-844015731
_Originally posted by @bhack in https://github.com/tensorflow/tensorflow/issues/38389#issuecomment-844015731_

**Comment by tilakrayal** [comment]
@Georgeiva ,

Please, fill issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and also please provide more information/details to understand the issue.

Thanks!
