### ISSUE TITLE
tensorflow 2.5.0 cuda and cudnn version

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#49295]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:

[https://www.tensorflow.org/install/source](https://www.tensorflow.org/install/source)
[https://github.com/tensorflow/docs/blob/master/site/en/install/source.md](https://github.com/tensorflow/docs/blob/master/site/en/install/source.md)

### Clear description
The document shows : 
<table>
<tr><th>Version</th><th>Python version</th><th>Compiler</th><th>Build tools</th><th>cuDNN</th><th>CUDA</th></tr>
<tr><td>tensorflow-2.5.0</td><td>3.6-3.9</td><td>GCC 7.3.1</td><td>Bazel 3.1.0</td><td>8.0</td><td>11.0</td></tr>
</table>

But according to [https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0)

```
TensorFlow pip packages are now built with CUDA11.2 and cuDNN 8.1.0
```
This table should be changed to : 
<table>
<tr><th>Version</th><th>Python version</th><th>Compiler</th><th>Build tools</th><th>cuDNN</th><th>CUDA</th></tr>
<tr><td>tensorflow-2.5.0</td><td>3.6-3.9</td><td>GCC 7.3.1</td><td>Bazel 3.1.0</td><td>8.1</td><td>11.2</td></tr>
</table>

**Comment by pythonic2020** [comment]
I very strongly second this ticket.  The outdated docs are misleading and unhelpful.  TF 2.5.0 GPU works perfectly with CUDA 11.2.2 and cuDNN 8.1.1, at least on Windows 10 x64 in a conda environment running python 3.9 into which TF was installed using `pip install tensorflow`.

I also think that the [GPU Support page](https://www.tensorflow.org/install/gpu#software_requirements) should be updated to reflect CUDA and cuDNN versions that TensorFlow 2.5.0 was built with and designed for.  Recommended TensorRT version should also be examined (look at 7.2.3: version 6.0 is outdated).

**Comment by MarkDaoust** [comment]
There's a fix in flight for the gpu page too.

https://github.com/tensorflow/docs/pull/1900
