### ISSUE TITLE
TF Import Error 

### ISSUE THREAD

**Issue by SanjuSoni** [tensorflow/tensorflow#49294]
Hello Everyone

While importing Tensorflow, I am getting an error which is attached here. 

But next time importing the TensorFlow, it works well.

can you please comment on it.

![err2](https://user-images.githubusercontent.com/61820415/118755553-b3680800-b886-11eb-8147-da9f599c39a9.JPG)

**Comment by bhack** [comment]
Sorry we don't officially support TF in conda env here.
If you still need conda you can ask support at https://github.com/AnacondaRecipes/tensorflow_recipes

**Comment by tilakrayal** [comment]
@SanjuSoni ,

We see that you are using tf version 1.9.0, there is no support for 1.x, please update to 2.x and let us know if you are using same issue.

Also as bhack mentioned above, Installation issues within the Anaconda environment are tracked in the Anaconda repo. Could you please submit new issue in [Anaconda repository](https://github.com/ContinuumIO/anaconda-issues/issues).

Thanks!

**Comment by SanjuSoni** [comment]
Thanks @tilakrayal  and @bhack  for your comment.

I am going to upgrade Tensorflow Version.
