### ISSUE TITLE
An idea of  `tf.one_hot`

### ISSUE THREAD

**Issue by zheyuye** [tensorflow/tensorflow#49299]
According to my personal experience , the mechanism of  `tf.one_hot` is returning the value of `0,1` that match the index number as in [one_hot](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/one_hot). But it might cause an unforeseen problem that can not handle the input larger than depth like following code snippets described. What it be better if raise a warning or alert that telling the user what happend inside.

### How to reproduce
Environment: `tensorflow=1.15`
```
# init
batch_size = 1
seq_len = 4
vocab_size = 2
data_vocab_size = 6

token_type_ids = tf.random.uniform([batch_size, seq_len], minval=0, maxval=data_vocab_size, dtype=tf.dtypes.int32)
# calculate
flat_token_type_ids = tf.reshape(token_type_ids, [-1])
one_hot_ids = tf.one_hot(flat_token_type_ids, depth=vocab_size)
with tf.Session() as sess:
    np_one_hot_ids = sess.run(one_hot_ids)
    np_flat_token_type_ids = sess.run(flat_token_type_ids)
    print(np_flat_token_type_ids)
    print(np_one_hot_ids)
```
>np_flat_token_type_ids: [0 0 2 3]
np_one_hot_ids:  
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

**Comment by bhack** [comment]
Sorry we don't support TF 1.x anymore. Please upgrade TF to the last release to verify that you can reproduce your issue.

**Comment by UsharaniPagadala** [comment]
@zheyuye 
We see that you are using tf version 1.15, Also as bhack mentioned above there is no support for 1.x, please upgrade to 2.x  and let us know if you are facing the same.Thanks

**Comment by UsharaniPagadala** [comment]
@zheyuye 
We see that you are using tf version 1.15, Also as bhack mentioned above there is no support for 1.x, please upgrade to 2.x and let us know if you are facing the same.Thanks

**Comment by zheyuye** [comment]
Thanks for the response, I am awared of this situation that TF 1.x is not supported anymore. I am going to close this issue, thanks again.
