### ISSUE TITLE
Hola desde hace días presento un problema con tensorflow lo he intentando todo he leído cada guía y parece siempre llego al mismo punto 

### ISSUE THREAD

**Issue by diamar338** [tensorflow/tensorflow#49291]
como se ve en la siguiente imagen mi problema es que al parecer 
![image](https://user-images.githubusercontent.com/67806145/118743784-aad8e880-b818-11eb-952a-fc4ac82d02f6.png)

**Comment by bhack** [comment]
Sorry we don't officially support  TF in conda Dev here.
If you still need conda you can ask support at https://github.com/AnacondaRecipes/tensorflow_recipes

**Comment by UsharaniPagadala** [comment]
@diamar338 
Closing this issue since it's related to conda env. Feel free to post another issue if still having problems installing TF using pip.

Thanks
