### ISSUE TITLE
dual gpu memory allocation problem in 0.6

### ISSUE THREAD

**Issue by zcyang** [tensorflow/tensorflow#493]
For the tensorflow 0.6, when I specifically assign the model on one gpu on a dual-gpu machine, it takes up the memory of both gpus.

This problem does not happen for tensorflow 0.5

**Comment by girving** [comment]
Cc @zheng-xq, but I think we may need more information to help here.

**Comment by zheng-xq** [comment]
@zcyang, did you try to use CUDA_VISIBLE_DEVICES to limit the set of GPUs you want to use with TF? 

The current TensorFlow works by going through all the GPUs visible to itself, check which one is compatible and assign a logical index to it. Note that this logical index might be different from your system device index. Then in your graph, you use the TensorFlow logic index to refer to each device. So all the devices will be occupied, regardless which one will be actually used later. 

If you don't want a device to be used by TensorFlow, one solution is to use CUDA_VISIBLE_DEVICES and make it invisible.

**Comment by vrv** [comment]
I believe I  fixed this sometime between 0.6 and 0.7 -- you only allocate memory for a GPU on first real use of it.
