### ISSUE TITLE
issue about feature_column with empty string feature

### ISSUE THREAD

**Issue by luckmoon** [tensorflow/tensorflow#49301]
Hi,
I am using tf1.15 with Py3.6.
Below is part of my code,
```
feature_description = {
    "city": FixedLenFeature(dtype=tf.string, shape=[], default_value="")
}

feature_columns = tf.feature_column.embedding_column(
                tf.feature_column.categorical_column_with_hash_bucket(
                   "city", hash_bucket_size=1  # 1 just for debug
                ),
                dimension=2
)
```
And I generated my train samples with tfrecord format.  If some of my train samples do not contains the key "city", when I parse them in training, they will be filled the "city" key with value "", right? So I can train my model successfully.
But when I inference with the exported model, if the data to predict does not contain "city", should I feed it with "", or just left it empty? I check both of them, I get different results. If i left it empty, the city will get zero embedding [0,0], while non-zeros embedding for city with "". Is this a bug, or which is the correct way to set city value?

**Comment by bhack** [comment]
Sorry we don't support TF 1.x anymore. Please upgrade TF to see if your issue is reproducible.

**Comment by Saduf2019** [comment]
@luckmoon 
Tf 1.x is not actively supported, Can you please upgrade to tf 2.x and let us know if you still face the issue.
