### ISSUE TITLE
Cannot import tensorflow: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization

### ISSUE THREAD

**Issue by Keshav2829** [tensorflow/tensorflow#49302]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version: tensorflow 2.5.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: GCC 9.3.0
- GPU model and memory: nvidia 940MX with 4GB memory

**
but i failed to install it. After then that i am unable to import tensorflow even after i reinstalled tensorflow i get import error as:
 
>>> import tensorflow
2021-05-19 19:21:42.165198: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib
2021-05-19 19:21:42.165227: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import models
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/models.py", line 20, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/metrics.py", line 37, in <module>
    from tensorflow.python.keras import activations
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 18, in <module>
    from tensorflow.python.keras.layers import advanced_activations
  File "/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/__init__.py", line 146, in <module>
    from tensorflow.python.keras.layers.normalization import LayerNormalization
ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization' (/home/keshav/.local/lib/python3.8/site-packages/tensorflow/python/keras/layers/normalization/__init__.py)

**

***i tried to install tensorflow on gpu and followed steps from following link and run the mentioned commands:
https://towardsdatascience.com/installing-tensorflow-gpu-in-ubuntu-20-04-4ee3ca4cb75d
$ sudo apt install nvidia-cuda-toolkit
$ tar -xvzf cudnn-10.1-linux-x64-v7.6.5.32.tgz
$ sudo cp cuda/include/cudnn.h /usr/lib/cuda/include/
$ sudo cp cuda/lib64/libcudnn* /usr/lib/cuda/lib64/
$ sudo chmod a+r /usr/lib/cuda/include/cudnn.h /usr/lib/cuda/lib64/libcudnn*
$ echo 'export LD_LIBRARY_PATH=/usr/lib/cuda/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
$ echo 'export LD_LIBRARY_PATH=/usr/lib/cuda/include:$LD_LIBRARY_PATH' >> ~/.bashrc
$ source ~/.bashrc
$ pip install tensorflow==2.2.0

after i failed to run tensorflow by this method i tried to revert changes that i made during installation so i tried following commands
sudo apt-get purge nvidia*
sudo apt-get autoremove
sudo apt-get autoclean
sudo rm -rf /usr/local/cuda*

and deleted cuda folder from usr/lib/cuda
**
now i am unable to import tensorflow please help as i am short on time to complete my collage project

thank you

**Comment by bhack** [comment]
Please check that you have the correct CUDA/Cudnn versions for TF 2.5. See https://github.com/tensorflow/tensorflow/issues/49175

**Comment by bhack** [comment]
Also if you are working with a venv please try to clean it https://www.tensorflow.org/install/pip?hl=en#2.-create-a-virtual-environment-recommended

**Comment by Keshav2829** [comment]
thank for your reply @tilakrayal 
as mentioned by you in comments i am not working with venv and from links that you have provided i have not found any solid solution. yes i have similar error log as mentioned in link2 but i am using ubuntu 
 please help

**Comment by bhack** [comment]
Can you try to make a 2.5.0 install with a fresh virtual env as in the official guide that I have mentioned?
Please verify Cuda/Cudnn version compatibility wtih 2.5.0?

**Comment by Keshav2829** [comment]
i tried with conda environment ... it works perfectly...
thank you for assistance @bhack  @tilakrayal
