### ISSUE TITLE
tensorflow error code 3221225501

### ISSUE THREAD

**Issue by cuneyttanrisever** [tensorflow/tensorflow#49309]
windows7 64bit 
what is the problem ?

Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_
tensorflow_internal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <modu
le>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python38\lib\site-packages\tensorflow\python\__init__.py", line 39, i
n <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed with error code 3221225501 while importing _pywrap_
tensorflow_internal

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by UsharaniPagadala** [comment]
@cuneyttanrisever 
Looking at the error log, seems like it is similar to  this [issue](https://github.com/tensorflow/tensorflow/issues/35598) and let us know if its help.Thanks

**Comment by cuneyttanrisever** [comment]
> @cuneyttanrisever
> Looking at the error log, seems like it is similar to this [issue](https://github.com/tensorflow/tensorflow/issues/35598) and let us know if its help.Thanks

I uploaded this link
https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.14.0/py37/CPU/sse2/tensorflow-1.14.0-cp37-cp37m-win_amd64.whl

import tensorflow as ft 
this error when the command is given:
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Python37\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureW
arning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a fu
ture version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
  
this error when the command is given:
>>> model = tf.keras.Sequential([
...     tf.keras.layers.Flatten(input_shape=(28, 28)),
...     tf.keras.layers.Dense(128, activation='relu'),
...     tf.keras.layers.Dense(10)
... ])

WARNING:tensorflow:From C:\Python37\lib\site-packages\tensorflow\python\ops\init
_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_
ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the c
onstructor

worked as a result but why am I getting these errors

Thanks for your help

**Comment by UsharaniPagadala** [comment]
@cuneyttanrisever 
Could you please confirm if the issue is resolved,if yes move this to close status.Thanks
