### ISSUE TITLE
tf.data.experimental.service does not reach optimal consumption rate

### ISSUE THREAD

**Issue by GuyPozner** [tensorflow/tensorflow#49304]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Using tensorflow/tensorflow:2.4.1-gpu docker image
- GPU model and memory: nvidia v100 32GB

Current behavior:
Training with `dataset = dataset.take(1).cache().repeat()` is 20% faster(iterations per sec) vs. training with the tf.data.experimental.service. Increasing the number of workers does not increase the number of iteration per second.
When increasing the number of workers, I can see that each worker is sending less data per time, but the data received in the consumer per time stays the same(126 MB/s, which is only 10% of the network in bandwidth of the consumer). 

I have tried setting the `max_outstanding_requests` [distributed function](https://www.tensorflow.org/api_docs/python/tf/data/experimental/service/distribute) which did not seem to have any effect. 

How can I optimize the data service?

**Comment by Saduf2019** [comment]
@GuyPozner 
Kindly share a colab gist or code such that we can replicate the issue reported.
