### ISSUE TITLE
How to get word alignment in attention_seq2seq in Translate.py?

### ISSUE THREAD

**Issue by wsnooker** [tensorflow/tensorflow#4934]
Hi, 
I'm wondering if i get the word alignment probability in the seq2seq model for language translation.

Thanks a lot! 
Stephen

**Comment by asimshankar** [comment]
@wsnooker : Apologies for the late reply. This question is probably best asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as the github issues try to remain focused on bugs and feature requests.
