### ISSUE TITLE
Does Distributed TensorFlow support Infiniband?

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#4935]
Based on stackoverflow, the answer is no.

If it is no, does TF have plans to support Infiniband?

http://stackoverflow.com/questions/39184496/does-distributed-tensorflow-support-infiniband-interconnections-out-of-the-box

**Comment by jart** [comment]
TensorFlow uses gRPC. We're going to support whatever gRPC supports. So I would encourage you to ask your question to the gRPC folks: https://github.com/grpc/grpc

**Comment by thinxer** [comment]
@jart Although TensorFlow uses gRPC for cross-node communication, there are flags that are intentionally reserved for OOB transfers like DMA. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/worker.proto#L223

Even though gRPC could use a RDMA transport, it requires messages be serialized in protobuf, which requires memory copying from GPU to CPU. With OOB transfers like RDMA, it is possible to transfer tensors directly from one GPU to another.

I believe the OP is asking for the OOB RDMA transport for tensors. Maybe some implementation around rdma_cm might be helpful.

**Comment by yaroslavvb** [comment]
There's related discussion on https://github.com/tensorflow/tensorflow/issues/2916

**Comment by jart** [comment]
I really appreciate you guys helping out with support @thinxer and @yaroslavvb. I was not aware of this fact.

I would still like to keep this issue closed since #2916 is requesting RDMA in general. AFAIK Infiniband is just a specific implementation of it. So Infiniband discussion is probably more appropriate there for the time being.
