### ISSUE TITLE
benchmark_model performance

### ISSUE THREAD

**Issue by fwz-fpga** [tensorflow/tensorflow#49367]
I have a tflite quantizd model(qat). 

To benchmark it's performance with device rk3399(arm), I build a binary benchmark_model form  source, command is : ./tensorflow/lite/tools/make/build_aarch64_lib.sh.

I also download a pre-build binary(linux_aarch64) here: https://www.tensorflow.org/lite/performance/measurement. 

Then I have two excutable binaries,  but the tflite models'performance  has a large difference. 

With the binary I build from source, The performance is 74ms, but with the downloaded binary, the performance is 55ms.

I am confused what's wrong with it. Does the command I build form source wrong?

Tensorflow commtid d99c821817e

**Comment by abattery** [comment]
@multiverse-tf could you take a look?

**Comment by multiverse-tf** [comment]
> I have a tflite quantizd model(qat).
> 
> To benchmark it's performance with device rk3399(arm), I build a binary benchmark_model form source, command is : ./tensorflow/lite/tools/make/build_aarch64_lib.sh.
> 
> I also download a pre-build binary(linux_aarch64) here: https://www.tensorflow.org/lite/performance/measurement.
> 
> Then I have two excutable binaries, but the tflite models'performance has a large difference.
> 
> With the binary I build from source, The performance is 74ms, but with the downloaded binary, the performance is 55ms.
> 
> I am confused what's wrong with it. Does the command I build form source wrong?
> 
> Tensorflow commtid [d99c821](https://github.com/tensorflow/tensorflow/commit/d99c821817e711972f78b0d01d24a57b45b831b6)

I guess the difference might come from two sources:
1. the RUY library isn't enabled for the make-based build. 
2. the compiler flags might be different. As for the pre-built one, we used "bazel --define=tflite_with_ruy=true --config=elinux_aarch64 --define tensorflow_mkldnn_contraction_kernel=0" to compile the binary. 

So, could you try the "bazel" to build your binary? Or try "cmake" to build the binary as shown [here](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_aarch64_arm64)?

**Comment by fwz-fpga** [comment]
Thanks very much. Does it mean ruy has a better performance than gemmlowp on arm platform?

**Comment by multiverse-tf** [comment]
> Thanks very much. Does it mean ruy has a better performance than gemmlowp on arm platform?

I think so as RUY is supposed to replace gemmlowp. @talumbau, could you shed some light on this?

Note RUY is automatically enabled when building tflite library on Android.
