### ISSUE TITLE
Segmentation fault (core dumped) - TFLite

### ISSUE THREAD

**Issue by ardtrkc** [tensorflow/tensorflow#49374]
@tensorflow/micro  x   @tensorflow/lite

Hi !

**Describe the problem**
To read a model from official [TensorFlow source (COCO SSD MobileNet v1)](https://www.tensorflow.org/lite/examples/object_detection/overview#get_started) and perform inference with [minimal.cc](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/lite/examples/minimal/minimal.cc), we get the error below.

**System information**
- Host OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): From source (branch r1.12)
- Target platform: iMX.6 (Arm v7)

**Please provide the exact sequence of commands/steps when you ran into the problem**
```
root@analytics:~# ./minimal ssd_mobilenet_v1_1_metadata_1.tflite
minimal: /usr/src/debug/tensorflow-lite/1.0-r0/git/tensorflow/contrib/lite/tools/make/downloads/eigen/unsupported/Eigen/CXX11/src/util/
MaxSizeVector.h:84: T& EigenForTFLite::MaxSizeVector<T>::operator[](std::size_t) [with T = EigenForTFLite::RunQueue
<EigenForTFLite::StlThreadEnvironment::Task, 1024u>*; std::size_t = unsigned int]: 
Assertion `i < size_' failed. 
Segmentation fault (core dumped)
```
Do you have any idea or suggestion about why we are facing this error (because of versions, TFlite binaries or the model etc.) ?
Thank you in advance.

**Comment by rmothukuru** [comment]
@ardtrkc,
You are using very older version of **`Tensorflow, 1.12`**. Can you please upgrade to the latest version of **`Tensorflow (2.5)`** and  see if the issue persists? Thanks!

**Comment by ardtrkc** [comment]
Thank you ! @rmothukuru
