### ISSUE TITLE
How to solve the INFO information: INFO:absl:resolver HttpCompressedFileResolver does not support the provided handle. INFO:absl:resolver GcsCompressedFileResolver does not support the provided handle. INFO:absl:resolver HttpUncompressedFileResolver does not support the provided handle.

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#49371]
> INFO:absl:resolver HttpCompressedFileResolver does not support the provided handle.
> INFO:absl:resolver GcsCompressedFileResolver does not support the provided handle.
> INFO:absl:resolver HttpUncompressedFileResolver does not support the provided handle.

When I train my text classification model, there always comes the info above. I do not know where they come from ?
Any solutions to ban these ?

**Comment by bhack** [comment]
Please share a very minimal example to reproduce this and fill the issue template with all the required info.

**Comment by Saduf2019** [comment]
@yananchen1989 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

@bhack 
Thank you for triaging the issue but we follow a process and a template for the same, kindly let us stick to the process, once information is shared by user your insights will be helpful.
