### ISSUE TITLE
switch_case returns wrong dataset in graph mode

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#49378]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
d1 = tf.data.Dataset.from_tensor_slices([tf.ones((2,2))]*2)
d2 = tf.data.Dataset.from_tensor_slices([tf.ones((4,4))]*2)
v = tf.Variable(0, dtype=tf.int32)
f = tf.function(lambda:tf.switch_case(v.read_value(), {0:(lambda:d1), 1:(lambda:d2)}))
print(f()) # shape is (2,2)
v.assign_add(1)
print(f()) # shape also is (2,2), which is wrong and it should be (4,4)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by MrinalTyagi** [comment]
```
<_VariantDataset shapes: (2, 2), types: tf.float32>

WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7fcb90d723b0> and will run it as-is.
Cause: could not parse the source code of <function <lambda> at 0x7fcb90d723b0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names.
Match 0:
(lambda : tf.switch_case(v.read_value(), {0: (lambda : d1), 1: (lambda : d2)}))

Match 1:
(lambda : d1)

Match 2:
(lambda : d2)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function <lambda> at 0x7fcb90d723b0> and will run it as-is.
Cause: could not parse the source code of <function <lambda> at 0x7fcb90d723b0>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names.
Match 0:
(lambda : tf.switch_case(v.read_value(), {0: (lambda : d1), 1: (lambda : d2)}))

Match 1:
(lambda : d1)

Match 2:
(lambda : d2)

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
<_VariantDataset shapes: (2, 2), types: tf.float32>
<_VariantDataset shapes: (2, 2), types: tf.float32>
```

On running the provided test case, following output is produced.  Could this be a issue due to the lambda function. Also i think the switch statement is processing 3 cases due to multiple lambda.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in TF v2.4,v2.5 and nightly.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/bb9d8bafa03f798d273732d9a895eed7/49378.ipynb) here

**Comment by mdanatg** [comment]
I rewrote the code a little bit to avoid the autograph warnings:

```
import tensorflow as tf
d1 = tf.data.Dataset.from_tensor_slices([tf.ones((2,2))]*2)
d2 = tf.data.Dataset.from_tensor_slices([tf.ones((4,4))]*2)
v = tf.Variable(0, dtype=tf.int32)
lam_d1 = lambda: d1
lam_d2 = lambda: d2
f = tf.function(lambda:tf.switch_case(v.read_value(), {0:lam_d1, 1:lam_d2}))
print(f()) # shape is (2,2)
v.assign_add(1)
print(f()) # shape also is (2,2), which is wrong and it should be (4,4)
```

This appears to be a bug in the shape inference, because attempting to consume the dataset raises a shape error, which means that the correct dataset is indeed being returned, but it's shape is incorrect:

```
import tensorflow as tf
d1 = tf.data.Dataset.from_tensor_slices([tf.ones((2,2))]*2)
d2 = tf.data.Dataset.from_tensor_slices([tf.ones((4,4))]*2)
v = tf.Variable(0, dtype=tf.int32)
lam_d1 = lambda: d1
lam_d2 = lambda: d2
f = tf.function(lambda:next(iter(tf.switch_case(v.read_value(), {0:lam_d1, 1:lam_d2}))))
print(f())  # prints a 2x2 tensor
v.assign_add(1)
print(f())  # errors out
```

```
...
InvalidArgumentError: {{function_node __inference_<lambda>_421}} Incompatible shapes at component 0: expected [2,2] but got [4,4].
	 [[{{node MakeIterator}}]] [Op:__inference_<lambda>_421]
```

**Comment by fsx950223** [comment]
No, it never returns d2

**Comment by tilakrayal** [comment]
@fsx950223,
Could you please confirm whether the issue still exists in the latest tensorflow version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e171e36c9aae3d15e4ac58628597c208/untitled589.ipynb).
