### ISSUE TITLE
Tensorflow 2.3 GPU build failed | NCCL no such package | RHEL 7

### ISSUE THREAD

**Issue by harishsureit** [tensorflow/tensorflow#49377]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): rhel 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.1
- Python version: 3.6.12
- Installed using virtualenv? pip? conda?: local
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.3.1
- CUDA/cuDNN version: 11.0 / 8.0
- Clang Version: 5.1
- GPU model and memory: 8 X Tesla V100 32GB

**Describe the problem**
  After successfull configuration of tensorflow build we executed bazel build command , then it failed with below error ------
-----------------------------------------------------------------------------------------------------------------

ERROR: /home/NTTA/vposaniadmin/tensorflow/tensorflow/core/kernels/BUILD:4689:1: C++ compilation of rule '//tensorflow/core/kernels:sparse_split_op' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/NTTA/vposaniadmin/.cache/bazel/_bazel_vposaniadmin/fbb878dda2a560b32c968c38a9e718c5/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.0 \
    GCC_HOST_COMPILER_PATH=/opt/rh/devtoolset-7/root/usr/bin/gcc \
    LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/usr/local/lib \
    PATH=/usr/local/cuda/bin:/usr/local/cuda/bin:/opt/rh/rh-python36/root/usr/bin:/home/NTTA/vposaniadmin/anaconda3/condabin:/usr/local/cuda/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/cuda/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/ssl/bin:/var/lib/snapd/snap/bin:/home/NTTA/vposaniadmin/.local/bin:/home/NTTA/vposaniadmin/bin:/usr/local/ssl/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/opt/rh/rh-python36/root/usr/bin/python3 \
    PYTHON_LIB_PATH=/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0 \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/sparse_split_op/sparse_split_op.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/sparse_split_op/sparse_split_op.pic.o' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/local_config_cuda -iquote bazel-out/k8-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/k8-opt/bin/external/local_config_tensorrt -Ibazel-out/k8-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/k8-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/local_config_cuda/cuda -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/k8-opt/bin/external/local_config_cuda/cuda/cuda/include -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DAUTOLOAD_DYNAMIC_KERNELS '-std=c++14' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DGOOGLE_CUDA=1' '-DTENSORFLOW_USE_NVCC=1' '-DTENSORFLOW_USE_XLA=1' -msse3 -pthread '-DGOOGLE_CUDA=1' '-DTENSORFLOW_USE_XLA=1' -c tensorflow/core/kernels/sparse_split_op.cc -o bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/sparse_split_op/sparse_split_op.pic.o)
Execution platform: @local_execution_config_platform//:platform
In file included from ./tensorflow/core/framework/op_kernel.h:35:0,
                 from tensorflow/core/kernels/sparse_split_op.cc:19:
tensorflow/core/kernels/sparse_split_op.cc: In member function 'void tensorflow::SparseSplitOp<T>::Compute(tensorflow::OpKernelContext*)':
tensorflow/core/kernels/sparse_split_op.cc:71:34: error: 'class tensorflow::TensorShape' has no member named 'AddDimWithStatus'
                      dense_shape.AddDimWithStatus(input_shape_flat(i)));
                                  ^
./tensorflow/core/framework/op_requires.h:52:29: note: in definition of macro 'OP_REQUIRES_OK'
     ::tensorflow::Status _s(__VA_ARGS__);                    \
                             ^~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build

***** Full log attached below *********

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure

Enabled CUDA support 
and rest of them are default

bazel build  //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@harishsureit 
This has already been reported and worked upon, you may refer to these issues and pr on similar error. [#47815, #45575, #48393]

I also came across a comment that says upgrading to 2.4.1, resolves the issue, please refer to the [comment here](https://github.com/tensorflow/tensorflow/issues/47832#issuecomment-800163367), and let us know by upgrading.

**Comment by harishsureit** [comment]
@Saduf2019 
Can we build tensorflow 2.4.1 offline , we are facing some network issues , is there any documentation or link for offline installation.

**Comment by harishsureit** [comment]
@Saduf2019 
As you said We have upgraded tensorflow to 2.4.1 and cuda - 11.3, cudnn 8.2 , clang 3.4.2 , then we tried build and we got the error,
/home/NTTA/vposaniadmin/.cache/bazel/_bazel_vposaniadmin/fbb878dda2a560b32c968c38a9e718c5/external/com_google_protobuf/BUILD:795:1: C++ compilation of rule '@com_google_protobuf//:python/google/protobuf/internal/_api_implementation.so' failed (Exit 1)
external/com_google_protobuf/python/google/protobuf/internal/api_implementation.cc:31:10: fatal error: Python.h: No such file or directory
#include <Python.h>
^~~~~~~~~~
compilation terminated.

Please help us.

**Comment by Saduf2019** [comment]
@harishsureit 
Could you please try with the correct [Cuda,cudnn](https://www.tensorflow.org/install/source#gpu) version, 2.4 is tested with 11.0/8.0, 11.3 is not even updated on the site.

**Comment by harishsureit** [comment]
@Saduf2019 
downgraded the CUDA to 11.0 and Cudnn to 8.0 , python 3.6.12, clang 5.1.0
and we got error again , error message updated in the top comment,

/home/NTTA/vposaniadmin/tensorflow/tensorflow/core/kernels/BUILD:4689:1: C++ compilation of rule '//tensorflow/core/kernels:sparse_split_op' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command

tensorflow/core/kernels/sparse_split_op.cc:71:34: error: 'class tensorflow::TensorShape' has no member named 'AddDimWithStatus'
                      dense_shape.AddDimWithStatus(input_shape_flat(i)));

**Comment by Saduf2019** [comment]
@harishsureit 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/49150#issuecomment-845195683), which is work in progress.

**Comment by harishsureit** [comment]
@Saduf2019 
Im not using tensorrt , and im not even enabled in configuration,
