### ISSUE TITLE
Build iOS sample failed

### ISSUE THREAD

**Issue by YangKuo221** [tensorflow/tensorflow#4937]
After I run the tensorflow/contrib/makefile/build_all_ios.sh command,
I got the messages bellow:

echo 'protoc not found at 
~/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.'
protoc not found at ~/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.

I check the protobuf-host directory. This folder contains nothing, how can I solve this?
Do I miss any steps?
Thanks!

**Comment by jart** [comment]
Assigning to @petewarden who maintains this Makefile.

**Comment by aselle** [comment]
Check the build_all_ios.sh for errors.

**Comment by YangKuo221** [comment]
@aselle 
I tried find ~/tensorflow -name 'protoc', 
No protoc folder found...

How should I do next? 
Thanks.

**Comment by aselle** [comment]
run $ build_all_ios.sh >& build_log
and attach it (don't inline it)

**Comment by YangKuo221** [comment]
@aselle 
OK, I run $ build_all_ios.sh >& build_log

Please help check the attachment
Thank you.
[build_log.txt](https://github.com/tensorflow/tensorflow/files/532353/build_log.txt)

**Comment by aselle** [comment]
It looks like you didn't follow the instructions (or they didn't work). See
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#before-you-start-all-platforms
Specifically the download prerequisites.

**Comment by YangKuo221** [comment]
@aselle 
It seems that running "tensorflow/contrib/makefile/download_dependencies.sh" is going well.

> downloading http://bitbucket.org/eigen/eigen/get/97c1ebe6ccc2.tar.gz
> downloading http://github.com/google/gemmlowp/archive/8b20dd2ce142115857220bd6a35e8a081b3e0829.tar.gz
> downloading https://github.com/google/googletest/archive/release-1.8.0.tar.gz
> downloading http://github.com/google/protobuf/archive/v3.1.0.tar.gz
> downloading http://github.com/google/re2/archive/7bab3dc83df6a838cc004cc7a7f51d5fe1a427d5.tar.gz
> download_dependencies.sh completed successfully.

And I also download example graph, it's in  ~/graphs.
Thanks.

**Comment by YangKuo221** [comment]
I tried running the tensorflow/contrib/makefile/build_all_ios.sh command again
But I still got the same issue.

Should I provide some other information?

**Comment by aselle** [comment]
Can you run and attach this log?
```
tensorflow/contrib/makefile/compile_ios_protobuf.sh 4 >& protobuf.compile.log
```
(you can look at the log and try to diagnose any errors there)

**Comment by YangKuo221** [comment]
Here's the log, and I found that protobuf-host is a new folder crated by script.
I have these in  tensorflow/contrib/makefile/downloads:
        eigen gemmlowp	googletest	protobuf	  re2

May I miss something ?
[protobuf.compile.log.txt](https://github.com/tensorflow/tensorflow/files/547149/protobuf.compile.log.txt)

**Comment by aselle** [comment]
Did you ever do this?
```
brew install automake
```

**Comment by aselle** [comment]
Also what version of mac os?

**Comment by YangKuo221** [comment]
Yes, I did brew install automake. It only says automake-1.15 is already installed.

My mac OS is El Capitan 10.11.6

**Comment by aselle** [comment]
This issue is quite old and hasn't had recent activity. Be sure to try the latest build instructions (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)
on the latest version of TensorFlow, and please create a new bug if it is still not working. Thanks.
