### ISSUE TITLE
Show search results of old path underneath 404 sign for dead links

### ISSUE THREAD

**Issue by berendjan** [tensorflow/tensorflow#49389]
A lot of old links to the Tensorflow documentation are now 404'ed. My suggestion would be that old link shows the 404 and also search results on tensorflow.org for the path. For example [https://www.tensorflow.org/deploy/distributed](https://www.tensorflow.org/deploy/distributed) should show the search results for [deploy distributed](https://www.tensorflow.org/s/results/?q=deploy%20distributed) underneath the 404 image.

**Comment by Saduf2019** [comment]
@berendjan 
Thank you for reporting the issue, we will fix this at the earliest.

**Comment by lamberta** [comment]
404 page WAI, as far as I can tell.
