### ISSUE TITLE
tf.io.serialize_tensor/parse_tensor: ValueError: as_list() is not defined on an unknown TensorShape in model training

### ISSUE THREAD

**Issue by sroener** [tensorflow/tensorflow#49456]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Systems are: Ubuntu 20.04.2 LTS; Google Colab

- TensorFlow installed from (source or binary):
Installed from conda (Ubuntu), preinstalled (Colab)

- TensorFlow version (use command below):
Tensorflow v2.4.1

- Python version:
Python 3.8.5 (Ubuntu), Python 3.7.10(Colab)

**Describe the current behavior**

Training a simple toy model on a custom iris TFRecords dataset throws the following error:
`ValueError: as_list() is not defined on an unknown TensorShape.`

The custom TFRecord dataset was created by serializing/deserializing the numpy arrays with `tf.io.serialize_tensor/tf.io.parse_tensor` to save/recover the original shapes. Afterwards the tensors were written to TFRecords following the official [Tutorial](https://www.tensorflow.org/tutorials/load_data/tfrecord). Reading and parsing the data seemed to work properly, as the original data was recovered (inspection by eye/shape), but  trying to feed the dataset to `model.fit()` did result in the described error.

**Describe the expected behavior**

Expected behavior would be successful training/evaluation, as training with custom records from serialized numpy arrays (`numpy.tobytes()`) and deserialization by tf.io.decode_raw() and subsequent recovery of array shape was possible.

**Standalone code to reproduce the issue**
I saved the notebook to a [gist](https://gist.github.com/sroener/e9ca6b870647dcdac3ea8df79fcae9c0) after running it in Colab.
It contains 3 main sections:
1) train model on raw numpy arrays (sanity check of toy model)
2) train model on TFRecrods created from said data, serialized by numpy.tobytes() and reconstructed afterwards (works, model training from TFRecord dataset possible)
3) train model on TFrecords created from same data, serialized by tf.io.serialize/parse_tensor. (throws error)

**Other info / logs** 

Full traceback:

> Epoch 1/150
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-22-4aa7a265b40e> in <module>()
>       7 model_tensor.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
>       8 # fit the model
> ----> 9 history_tensor = model_tensor.fit(parsed_train_dataset_tensor, epochs=150, batch_size=32, verbose=2)
>      10 
>      11 loss, acc = model.evaluate(parsed_test_dataset_tensor, verbose=0)
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
>    1098                 _r=1):
>    1099               callbacks.on_train_batch_begin(step)
> -> 1100               tmp_logs = self.train_function(iterator)
>    1101               if data_handler.should_sync:
>    1102                 context.async_wait()
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
>     826     tracing_count = self.experimental_get_tracing_count()
>     827     with trace.Trace(self._name) as tm:
> --> 828       result = self._call(*args, **kwds)
>     829       compiler = "xla" if self._experimental_compile else "nonXla"
>     830       new_tracing_count = self.experimental_get_tracing_count()
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
>     869       # This is the first call of __call__, so we have to initialize.
>     870       initializers = []
> --> 871       self._initialize(args, kwds, add_initializers_to=initializers)
>     872     finally:
>     873       # At this point we know that the initialization is complete (or less
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
>     724     self._concrete_stateful_fn = (
>     725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
> --> 726             *args, **kwds))
>     727 
>     728     def invalid_creator_scope(*unused_args, **unused_kwds):
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
>    2967       args, kwargs = None, None
>    2968     with self._lock:
> -> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)
>    2970     return graph_function
>    2971 
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
>    3359 
>    3360           self._function_cache.missed.add(call_context_key)
> -> 3361           graph_function = self._create_graph_function(args, kwargs)
>    3362           self._function_cache.primary[cache_key] = graph_function
>    3363 
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
>    3204             arg_names=arg_names,
>    3205             override_flat_arg_shapes=override_flat_arg_shapes,
> -> 3206             capture_by_value=self._capture_by_value),
>    3207         self._function_attributes,
>    3208         function_spec=self.function_spec,
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
>     988         _, original_func = tf_decorator.unwrap(python_func)
>     989 
> --> 990       func_outputs = python_func(*func_args, **func_kwargs)
>     991 
>     992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
>     632             xla_context.Exit()
>     633         else:
> --> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>     635         return out
>     636 
> 
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
>     975           except Exception as e:  # pylint:disable=broad-except
>     976             if hasattr(e, "ag_error_metadata"):
> --> 977               raise e.ag_error_metadata.to_exception(e)
>     978             else:
>     979               raise
> 
> ValueError: in user code:
> 
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
>         return step_function(self, iterator)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
>         return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
>         return self._call_for_each_replica(fn, args, kwargs)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
>         return fn(*args, **kwargs)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
>         outputs = model.train_step(data)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:758 train_step
>         self.compiled_metrics.update_state(y, y_pred, sample_weight)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:387 update_state
>         self.build(y_pred, y_true)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:318 build
>         self._metrics, y_true, y_pred)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py:1163 map_structure_up_to
>         **kwargs)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py:1258 map_structure_with_tuple_paths_up_to
>         func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py:1258 <listcomp>
>         func(*args, **kwargs) for args in zip(flat_path_gen, *flat_value_gen)
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py:1161 <lambda>
>         lambda _, *values: func(*values),  # Discards the path arg.
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:418 _get_metric_objects
>         return [self._get_metric_object(m, y_t, y_p) for m in metrics]
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:418 <listcomp>
>         return [self._get_metric_object(m, y_t, y_p) for m in metrics]
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:439 _get_metric_object
>         y_t_rank = len(y_t.shape.as_list())
>     /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:1190 as_list
>         raise ValueError("as_list() is not defined on an unknown TensorShape.")
> 
>     ValueError: as_list() is not defined on an unknown TensorShape.

**Comment by tilakrayal** [comment]
@sroener ,

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Please take a look at this [link](https://stackoverflow.com/questions/58933151/as-list-is-not-defined-on-an-unknown-tensorshape) with similar error log.It helps.

Thanks

**Comment by sroener** [comment]
@tilakrayal

Can you please explain why this is not a bug? As far as I understand, the official Tutorial points users towards tf.io.serialize_tensor/parse tensor as the go to methods to prepare/parse non-scalar data for/from TFRecords. If these functions don't work as expected (triggering errors), I would categorize this as a bug.

Even if these methods work as intended, I think it would still be worth an investigation why the .fit() method seems not be able to handle data prepared in this way.

The accepted answer in the shared [link](https://stackoverflow.com/a/58934046) is exactly how I solved the problem (tf.io.decode_raw + tf.reshape), but it is still just a workaround.

Thanks

**Comment by tilakrayal** [comment]
@rmothukuru,

I was able to reproduce the issue in TF [v2.4](https://colab.research.google.com/gist/tilakrayal/f9d047fd2178299c3377dffc98c49e13/49456-2-4.ipynb),[v2.5](https://colab.research.google.com/gist/tilakrayal/cdcd49255b0a04716a188c1722a0aa16/tfrecord_parse_tensor_problem2-5.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/198289bf9ad06b2d61a772231817cf1c/tfrecord_parse_tensor_problem-nightly.ipynb).Please find the gist.

**Comment by rmothukuru** [comment]
@sroener,
With respect to your statement, 

> the official Tutorial points users towards tf.io.serialize_tensor/parse tensor as the go to methods to prepare/parse non-scalar data for/from TFRecords. 

can you please provide the **`reference link of the Tutorial`** that point towards `tf.io.serialize_tensor/parse tensor` so that we can rectify it? Thanks!

**Comment by sroener** [comment]
@rmothukuru

Thanks for the reply.

Sure, the [link](https://www.tensorflow.org/tutorials/load_data/tfrecord#tftrainexample) to the tutorial was mentioned in my original post. The Tutorial points to `tf.io.serialize_tensor/parse_tensor` in the note directly below the three list types that are supported by `tf.train.feature`.

> Note: To stay simple, this example only uses scalar inputs. The simplest way to handle non-scalar features is to use tf.io.serialize_tensor to convert tensors to binary-strings. Strings are scalars in tensorflow. Use tf.io.parse_tensor to convert the binary-string back to a tensor.

**Comment by sroener** [comment]
Hi, any news on this issue?

**Comment by sroener** [comment]
Hey,

I just checked the colab notebook for the nightly build. This is still a problem and the documentation still recommends this way of converting non-scalar data.

Are you planning to do anything about this in the near future?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
