### ISSUE TITLE
text.tokenizer not removing filters char from text 

### ISSUE THREAD

**Issue by sid-sundrani** [tensorflow/tensorflow#49459]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubutnu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):'2.5.0'
- Python version: 3.8

**Describe the current behavior**
The filter parameter of `tf.keras.preprocessing.text.Tokenizer` does not seem to filter out characters included in the "filters" paramter. those characters have an index in keys of `.get_config()`. Is this expected? 

The description of the "filters parameteres reads " a string where each element is a character that will be filtered from the texts.". 
Hence I would not expect these characters to have been given an index, (perhaps they all could be given one OOV index)
 
**Describe the expected behavior**
The characters included in the filters paramter would not be having different indices in the tokenizer. Either all have one oov index or none. 

**Standalone code to reproduce the issue**
```
import tensorflow as tf 

char_tokenizer = tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True, char_level=True,
    document_count=0, 
)

char_tokenizer.fit_on_texts(['a%$#^ *'])
print(char_tokenizer.get_config()['index_word'])
```

`>> {"a": 1, "%": 2, "$": 3, "#": 4, "^": 5, " ": 6, "*": 7}`

Despite these special characters being included in the filters parameter, they are not filtered out and have been given an index. 

Expected behaviour
`>> {"a": 1}`

Is this expected?

**Comment by ymodak** [comment]
You have to set arg `char_level=False` to achieve the later (expected) result.

**Comment by sid-sundrani** [comment]
@ymodak `char_level` is set to `True` because the use case this to get character embeddings, as opposed to word embeddings

**Comment by sachinprasadhs** [comment]
Would you like to move this issue to keras. 

To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by sachinprasadhs** [comment]
Moved this issue to keras-team/keras repo, you can track the status of the issue from the above link, closing the issue here.
