### ISSUE TITLE
Colab doesnt use GPU despite connected to GPU runtime

### ISSUE THREAD

**Issue by drkhan107** [tensorflow/tensorflow#49455]
My code worked well with GPU in Colab a few days ago. But today it was very slow. After checking the availability of GPU fI found out GPU isn't getting used despite connected to one.

**Comment by UsharaniPagadala** [comment]
@drkhan107 
Colab offers optional accelerated compute environments, including GPU and TPU. Executing code in a GPU or TPU runtime does not automatically mean that the GPU or TPU is being utilized. To avoid hitting your GPU usage limits, we recommend switching to a standard runtime if you are not utilizing the GPU. Choose Runtime > Change Runtime Type and set Hardware Accelerator to None.For more info please go through this [Tensorflow with GPU](https://colab.research.google.com/notebooks/gpu.ipynb).Thanks

**Comment by lgeiger** [comment]
This is probably due to https://github.com/googlecolab/colabtools/issues/2013

As a workaround you should be able to use the GPU on colab with TF 2.4 for the time being.

**Comment by UsharaniPagadala** [comment]
@drkhan107 

Thank you for your update, If you could resolve it. kindly move this issue to closed status, and keep track that  issue mentioned or else subscribe. 
Thanks

**Comment by drkhan107** [comment]
Thank you. I will try TF 2.4

**Comment by UsharaniPagadala** [comment]
@drkhan107 

Could you please move this to closed status as it is resolved.Thanks
