### ISSUE TITLE
404 from https://www.tensorflow.org/get_started/embedding_viz

### ISSUE THREAD

**Issue by ToonTalk** [tensorflow/tensorflow#49457]
This is the link from http://projector.tensorflow.org/ to "Open documentation" (the circle with a question mark inside)

**Comment by tilakrayal** [comment]
@ToonTalk ,

We see that the issue template has not been filled, could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Thanks!

**Comment by ymodak** [comment]
we have a tracker for this https://github.com/tensorflow/tensorboard/issues/4896
Thanks!
