### ISSUE TITLE
Removal of PersistentTensor breaks custom ops (Horovod)

### ISSUE THREAD

**Issue by tgaddair** [tensorflow/tensorflow#49467]
The recent commit https://github.com/tensorflow/tensorflow/commit/f8153ae87a88586ac1c364116208cfb144c9b64a#diff-b35354f62819de66aaa049a9498cccc261c108a7c488d39e04882110bdee65b5 removed the `PersistentTensor` from the TensorFlow C++ API. For Horovod, we rely on this functionality to allocate the "fusion buffer" that packs multiple smaller tensors into a single buffer during allreduce [here](https://github.com/horovod/horovod/blob/master/horovod/common/fusion_buffer_manager.cc#L39) which ultimately calls into [here](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.cc#L198).

The docs recommend using `Tensor` with `allocate_temp` instead, but this does not seem like a viable workaround. My understanding is these tensors will not survive past the life of a single Op. Other frameworks including PyTorch and MXNet provide similar mechanisms for allocating long-lived tensor buffers, it seems reasonable TensorFlow should continue to do the same. Or is there a workaround I am missing?

Thanks.

cc @reedwm @romerojosh @DEKHTIARJonathan

**Comment by DEKHTIARJonathan** [comment]
@reedwm @sanjoy @pkanwar23 could you help addressing the issue or advising how we can work around the issue ?µ

@nluehr for viz

**Comment by gromovkg** [comment]
Hello Travis,
Tensors allocated with allocate_temp will survive past the life of a single Op. This call really needs to be renamed just "allocate"  or allocate_tensor for consistency.

Persistent tensor implementation that was just removed, and you are using, was a wrapper around Tensor class and allocate_temp.

It is completely safe to do the flowing update to your code:

FROM:
PersistentTensor ptensor_;
Tensor* second_tensor = nullptr;
    OP_REQUIRES_OK(context, context->allocate_persistent(
                                value, shape, &ptensor_, &second_tensor));
const Tensor& tensor = *ptensor_.AccessTensor(context);

TO
Tensor tensor;
OP_REQUIRES_OK(
        context, context->allocate_temp(value, shape, &tensor));

**Comment by tgaddair** [comment]
Thanks @gromovkg, that seems to have worked! I think what through me off about `allocate_temp` was [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h#L251) section of the docs that reads: "Tensor must not be used after kernel construction is complete." Can you clarify at which point the tensor can no longer be safely used?

**Comment by gromovkg** [comment]
@tgaddair You are welcome!

Tensor doesn't directly store the tensor contents. Tensor has a pointer to a TensorBuffer, which holds the tensot's contents and is refcounted. When a Tensor is copied, it doesn't copy the tensor contents but just copies the TensorBuffer pointer and increases the refcount. When the TensorBuffer's refcount reaches zero, it is destructed. In practice, usually only tensors reference TensorBuffers so when the last Tensor referencing a TensorBuffer is destructed, the TensorBuffer is also destructed.

**Comment by tgaddair** [comment]
I see, thanks for clarifying! I'll go ahead and close this issue then since it sounds like this is what we're looking for.
