### ISSUE TITLE
XLA with tf.function failed on tf2.5

### ISSUE THREAD

**Issue by cswhjiang** [tensorflow/tensorflow#49462]
I can run the tutorial code (https://www.tensorflow.org/xla/tutorials/jit_compile) successfully. But using XAL with `tf.function` on my code failed with the following errors:
```
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run __inference_train_multiple_steps_269495: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::ResourceDeleter [Op:__inference_train_multiple_steps_269495]
```
Is there anything I missed when using it?

**Comment by Saduf2019** [comment]
@cswhjiang 
Could you please share the code where you face error along with XLA and tf.function.
