### ISSUE TITLE
mixed precision training failed on tf2.5

### ISSUE THREAD

**Issue by cswhjiang** [tensorflow/tensorflow#49460]
The following momentum updating steps failed when mixed precision is enabled.
```
        cur_step = tf.cast(cur_step, tf.float32)  
        total_step = tf.cast(total_step, tf.float32)  # tensor
        PI = tf.constant(math.pi, tf.float32)
        tau = 1.0 - (1.0 - self.tau_base) * (tf.math.cos(PI * cur_step / total_step) + 1.0) / 2.0

        for param_online, param_target in zip(self.online_net.trainable_variables, self.target_net.trainable_variables):
            param_target.assign(param_target * tau + param_online * (1.0 - tau))
```
And here is the error message
```
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
```
Is there anything wrong with the code?

**Comment by tilakrayal** [comment]
@cswhjiang ,

In order to expedite the trouble-shooting process, could you please provide the tensorflow version,the complete code and dataset or colab gist to reproduce the issue reported here.

Thanks!

**Comment by tilakrayal** [comment]
@cswhjiang ,
Please take a look at these issues with similar error log.#33077,#33484,[link](https://stackoverflow.com/questions/59541629/typeerror-input-y-of-mul-op-has-type-float32-that-does-not-match-type-int32).It helps.

Thanks!
