### ISSUE TITLE
Error while installing tf-nightly in Jupyter Notebook

### ISSUE THREAD

**Issue by worldpeaceaspirer** [tensorflow/tensorflow#49487]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version: tf-nightly
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
When trying to install **`tf-nightly`** in the **`Jupyter Notebook`** of my **`PC`**, I'm encountering errors. It is working fine in **`Google Colab`**, by the way.

Errors are:

```python
ERROR: tf-nightly-2-0-preview 2.0.0.dev20190601 has requirement tb-nightly<1.15.0a0,>=1.14.0a0, but you'll have tb-nightly 2.4.0a20201022 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement gast==0.4.0, but you'll have gast 0.3.3 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement h5py~=3.1.0, but you'll have h5py 2.10.0 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement numpy~=1.19.2, but you'll have numpy 1.18.5 which is incompatible.
ERROR: tensorflow-transform 0.24.1 has requirement tensorflow!=2.0.*,!=2.1.*,!=2.2.*,<2.4,>=1.15.2, but you'll have tensorflow 2.5.0 which is incompatible.
ERROR: tensorflow-text 2.3.0 has requirement tensorflow<2.4,>=2.3.0, but you'll have tensorflow 2.5.0 which is incompatible.
ERROR: tensorflow-gpu 2.0.0b1 has requirement tb-nightly<1.14.0a20190604,>=1.14.0a20190603, but you'll have tb-nightly 2.4.0a20201022 which is incompatible.
ERROR: tensorflow-gpu 2.0.0b1 has requirement tf-estimator-nightly<1.14.0.dev2019060502,>=1.14.0.dev2019060501, but you'll have tf-estimator-nightly 2.4.0.dev2020090201 which is incompatible.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`!pip install tf-nightly`

**Any other info / logs**
Complete Error Log is present in this attachment,
[Error_Log.txt](https://github.com/tensorflow/tensorflow/files/6525736/Error_Log.txt)

**Comment by ashutosh1919** [comment]
@worldpeaceaspirer , I think you don't have CUDA support and that is what required for `tensorflow-gpu` it is trying to install.

**Comment by Saduf2019** [comment]
@worldpeaceaspirer 
Can you please try below commands and let us know, there clearly has been incompatibility issues, please verify [system requirements](https://www.tensorflow.org/install/pip):
Please refer to similar [gast issue here](https://github.com/tensorflow/tensorflow/issues/38734):
pip install --upgrade pip
pip install gast==0.2.2
pip install tensorflow

- for numpy refer to:[link](https://github.com/tensorflow/models/issues/9200), please verify an dupgrade/downgrade as per error log and let us know.

**Comment by worldpeaceaspirer** [comment]
@Saduf2019,
Sorry for the delayed response. My problem is not with installing **`Tensorflow`**, but with installing **`TF-Nightly`**. So, your answer didn't help me to resolve my problem. Thanks!

**Comment by Saduf2019** [comment]
@worldpeaceaspirer 
Please try with stable version and let us know.
