### ISSUE TITLE
RNN integer input error

### ISSUE THREAD

**Issue by Joocheol** [tensorflow/tensorflow#49496]
```
import numpy as np
import tensorflow as tf

x_1 = [ i for i in range(20) ]
x_2 = np.array(x_1)
x_3 = x_2.reshape([1,20,1])

rnn = tf.keras.layers.SimpleRNN(1)
rnn(x_3)
```

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-59-799b31aab8d4> in <module>()
      7 
      8 rnn = tf.keras.layers.SimpleRNN(1)
----> 9 rnn(x_3)

15 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    658 
    659     if initial_state is None and constants is None:
--> 660       return super(RNN, self).__call__(inputs, **kwargs)
    661 
    662     # If any of `initial_state` or `constants` are specified and are Keras

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
   1010         with autocast_variable.enable_auto_cast_variables(
   1011             self._compute_dtype_object):
-> 1012           outputs = call_fn(inputs, *args, **kwargs)
   1013 
   1014         if self._activity_regularizer:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py in call(self, inputs, mask, training, initial_state)
   1571     self._maybe_reset_cell_dropout_mask(self.cell)
   1572     return super(SimpleRNN, self).call(
-> 1573         inputs, mask=mask, training=training, initial_state=initial_state)
   1574 
   1575   @property

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py in call(self, inputs, mask, training, initial_state, constants)
    802         input_length=row_lengths if row_lengths is not None else timesteps,
    803         time_major=self.time_major,
--> 804         zero_output_for_mask=self.zero_output_for_mask)
    805 
    806     if self.stateful:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length, time_major, zero_output_for_mask)
   4347     # the value is discarded.
   4348     output_time_zero, _ = step_function(
-> 4349         input_time_zero, tuple(initial_states) + tuple(constants))
   4350     output_ta = tuple(
   4351         tensor_array_ops.TensorArray(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py in step(inputs, states)
    788       def step(inputs, states):
    789         states = states[0] if len(states) == 1 and is_tf_rnn_cell else states
--> 790         output, new_states = cell_call_fn(inputs, states, **kwargs)
    791         if not nest.is_nested(new_states):
    792           new_states = [new_states]

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
   1010         with autocast_variable.enable_auto_cast_variables(
   1011             self._compute_dtype_object):
-> 1012           outputs = call_fn(inputs, *args, **kwargs)
   1013 
   1014         if self._activity_regularizer:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py in call(self, inputs, states, training)
   1369       h = K.dot(inputs * dp_mask, self.kernel)
   1370     else:
-> 1371       h = K.dot(inputs, self.kernel)
   1372     if self.bias is not None:
   1373       h = K.bias_add(h, self.bias)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py in dot(x, y)
   1896     out = sparse_ops.sparse_tensor_dense_matmul(x, y)
   1897   else:
-> 1898     out = math_ops.matmul(x, y)
   1899   return out
   1900 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, a_is_sparse, b_is_sparse, name)
   3313     else:
   3314       return gen_math_ops.mat_mul(
-> 3315           a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
   3316 
   3317 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_math_ops.py in mat_mul(a, b, transpose_a, transpose_b, name)
   5530       return _result
   5531     except _core._NotOkStatusException as e:
-> 5532       _ops.raise_from_not_ok_status(e, name)
   5533     except _core._FallbackException:
   5534       pass

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6860   message = e.message + (" name: " + name if name is not None else "")
   6861   # pylint: disable=protected-access
-> 6862   six.raise_from(core._status_to_exception(e.code, message), None)
   6863   # pylint: enable=protected-access
   6864 

/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a int64 tensor but is a float tensor [Op:MatMul]

------------------

This is a dtype problem. Change int to float can solve the problem.
But I don't know why. Also, the final error message does not make sense.

```
import numpy as np
import tensorflow as tf

x_1 = [ float(i) for i in range(20) ]
x_2 = np.array(x_1)
x_3 = x_2.reshape([1,20,1])

rnn = tf.keras.layers.SimpleRNN(1)
rnn(x_3)

```

**Comment by ymodak** [comment]
This behavior is documented in the example of simple rnn. The input is explicitly converted to type float.
See https://www.tensorflow.org/api_docs/python/tf/keras/layers/SimpleRNN#examples

**Comment by Joocheol** [comment]
@ymodak You are right. So this is the reason why I report it as a bug. RNN should handle the dtype problem.

**Comment by tilakrayal** [comment]
@Joocheol ,

Can you please provide the tensorflow versin which you are trying to execute the mentioned code.Thanks!

**Comment by Joocheol** [comment]
@ymodak 2.4.1 
I run it on the colab.

**Comment by ymodak** [comment]
@Joocheol This is an intended behavior since TF 2 keras layers default dtype is `float32`.
See https://www.tensorflow.org/api_docs/python/tf/keras/backend/floatx
Thus you need to explicitly set the data type to `float32` as mentioned in the usage examples of Keras layers SimpleRNN and [SimpleRNNCell](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SimpleRNNCell#examples).

**Comment by Joocheol** [comment]
@ymodak OK. I will accept it. Thank you for your clarification.
