### ISSUE TITLE
micro: Port ABS for int8 and int16 from lite to micro

### ISSUE THREAD

**Issue by patriklaurell** [tensorflow/tensorflow#49492]
@tensorflow/micro

@advaitjain this issue tracks my work in porting int8 and int16 support for the ABS kernel in Micro

It will be delivered as one PR containing the porting of the operator and appropriate tests.

**Comment by rmothukuru** [comment]
@patriklaurell,
Can you please mention the link of your PR here so that we can understand that it is being taken care? Thanks!

**Comment by patriklaurell** [comment]
@rmothukuru I have not yet uploaded the PR. It is not ready yet. I opened the issue to indicate that I am working on it. Should I close it again until the PR is ready? or should I upload a draft PR?

**Comment by rmothukuru** [comment]
@patriklaurell,
We can leave it open and since you are committed to this repository, I have assigned this issue to you. Thanks!

**Comment by pjpratik** [comment]
Hi @patriklaurell 

The commit https://github.com/tensorflow/tflite-micro/commit/b34ced4f1bc240b3a31ab7d7f17075172d9a8cb8 adds int8 and int16 support in elementwise ABS. 

Could you please confirm the same and let us know if it is resolved?

Thanks.
