### ISSUE TITLE
Tutorial returning 404 on small part

### ISSUE THREAD

**Issue by Iskers** [tensorflow/tensorflow#49494]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/tutorials/keras/regression?hl=nb

### Clear description

Under ther part:

```
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()
```

Parts of the tutorial returns a imbeded site which is a 404 page.

### Correct links

Yes

### Parameters defined

Not relevant

### Returns defined

Not relevant

### Raises listed and defined

Not relevant

### Usage example

Not relevant

### Request visuals, if applicable

![Bug report](https://user-images.githubusercontent.com/22838996/119238071-99f1e500-bb40-11eb-8cef-4e7a90674a17.PNG)

### Submit a pull request?

Not relevant

**Comment by Saduf2019** [comment]
@Iskers 
This has been fixed, please refer to the page and confirm and move this to closed status as resolved.

**Comment by Iskers** [comment]
It looks like it should and has been resolved.
