### ISSUE TITLE
cannot use tf.nn.elu(features, name=None)

### ISSUE THREAD

**Issue by JacobIsrael123** [tensorflow/tensorflow#495]
Error Message:
AttributeError: 'module' object has no attribute 'elu'

When I try to use tf.nn.elu. 

Is it not written in the package yet?  Why it is included in the API document?

**Comment by girving** [comment]
You may be looking at the documentation for master or 0.6.0 and running TensorFlow version 0.6.0 or 0.5.0, respectively.  What is `tf.__version__`?

Cc @martinwicke in case there's something we can do to make that happen less often.

**Comment by martinwicke** [comment]
Default view on docs is at head, which is suboptimal. It should be 0.6, but
in this case, that may not be the issue.

**Comment by JacobIsrael123** [comment]
@girving  even tf.__version__ report the same error. 
How do I know the version of tensorflow on my computer?

**Comment by JacobIsrael123** [comment]
@martinwicke I checked, the document has two version "master" and "0.6.0",  both version has **tf.nn.elu**. Logically, **tf.nn.elu** should not be in one of them, right?

**Comment by vincentvanhoucke** [comment]
If tf.__version__ returns an error, your TensorFlow installation is old and didn't have support for elu() yet. Upgrading to 0.6.0 should solve your problem.
