### ISSUE TITLE
tf.data.Dataset.from_tensor_slices support more types than int32

### ISSUE THREAD

**Issue by pesekon2** [tensorflow/tensorflow#49503]
Currently, `tf.data.Dataset.from_tensor_slices` transforms any slice into `int32`. If working with `uint8` data, this leads to an unnecessary and unexpected data type shift leading to extremely enlarged memory use.

**Comment by Saduf2019** [comment]
@pesekon2 
Thank you for the request, we are working on this and will update you at the earliest.

**Comment by jvishnuvardhan** [comment]
@pesekon2 Can you please create a simple standalone code to reproduce the issue? I tried slicing `uint8` data in [this gist](https://colab.research.google.com/gist/jvishnuvardhan/d10b5d5511feb2085eeff987b6de0116/untitled992.ipynb) but couldn't see unexpected data type shift. May be i am missing something here. 

More details and a standalone code will help in resolving the issue. Thanks!
