### ISSUE TITLE
File "...", line 6, in <module> import tensorflow.compat.v1 as tf ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by fronrfron11** [tensorflow/tensorflow#49506]
When I push run the program shown me that. How can i solve it, plz and thank you everyone

**Comment by fronrfron11** [comment]
![image](https://user-images.githubusercontent.com/84584319/119275877-cb060e80-bc41-11eb-9a83-a9575afecea6.png)

**Comment by tilakrayal** [comment]
@fronrfron11 ,

In order to expedite the trouble-shooting process, could you please provide the Tensorflow version you are trying and also please take a look at this [link](https://github.com/tensorflow/tensorflow/issues/38800) with similar error.It helps.

Thanks

**Comment by ymodak** [comment]
From stack trace looks like TF is not correctly installed in your system. Can you mention what steps did you take to install TF?
See https://www.tensorflow.org/install/pip for installation.
