### ISSUE TITLE
No enable autoparallel optimizer doc in grappler

### ISSUE THREAD

**Issue by Stonepia** [tensorflow/tensorflow#49507]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/config/optimizer/set_experimental_options#args

## Description of issue (what needs changing):

The [document of grappler ](https://www.tensorflow.org/guide/graph_optimization#available_graph_optimizers) says it has an `autoparallel optimizer`, and it supposed to be enabled using `tf.config.optimizer.set_experimental_options`.  While in [`tf.config.optimizer.set_experimental_options`](https://www.tensorflow.org/api_docs/python/tf/config/optimizer/set_experimental_options#args), it does not have the corresponding option (auto_parallel).

**Comment by Saduf2019** [comment]
@Stonepia 

Thank you for the request, we are working on this and will update you at the earliest.
