### ISSUE TITLE
File system is not working on Windows through tf.io.gfile.GFile interface

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#49515]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): 2.5.0
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

It looks like on Windows, File system (e.g., gcs) is only working through `tf.io.read_file()` but not working through `tf.io.gfile.GFile().read()`.

On Windows, check the following command:
```bash
python3 -c "import tensorflow as tf;print(tf.version.VERSION);tf.io.read_file('gs://1234567')" 
```
throws out error of:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: GCS path doesn't contain an object name: gs://1234567 [Op:ReadFile]
```

This indicates GCS file system at least is available.

On the other hand, the following command:
```bash
python3 -c "import tensorflow as tf;print(tf.version.VERSION);tf.io.gfile.GFile('gs://1234567').read()" 
```
throws out error of:
```
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://1234567')
```

which indicate GCS file system is not even registered.

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): yes

**Standalone code to reproduce the issue**
See description above

The issue is due to the duplication of `Env::Default` in multiple places. The issue is exposed on Windows due to `config=monolithic` being passed to bazel. I think I have identified the places that cause the issue. Will submit a PR soon.

/cc @mihaimaruseac @vnvo2409 @kvignesh1420 @terrytangyuan @burgerkingeater

**Comment by tilakrayal** [comment]
The issue will move to closed status once the PR is merged.

**Comment by Saduf2019** [comment]
@yongtang 
Is this still an issue

**Comment by yongtang** [comment]
@Saduf2019 This is still an issue as #49520 has not been merged yet. (the PR has been approved but has not been imported internally yet). See https://github.com/tensorflow/tensorflow/pull/49520#issuecomment-862739157

**Comment by Saduf2019** [comment]
@yongtang
Is this still an issue

**Comment by yongtang** [comment]
@Saduf2019  PR #49520 has been approved, though it has not been imported and merged yet. Once it is merged this issue can be resolved.

**Comment by tilakrayal** [comment]
@yongtang,
Related PR https://github.com/tensorflow/tensorflow/pull/49520 was closed. Could you please take a look at the comments from the developer and respond accordingly. Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
