### ISSUE TITLE
I have never had success with Tensorflow (or lite version) build with cmake or bazel on windows

### ISSUE THREAD

**Issue by budibeta** [tensorflow/tensorflow#49512]
i downloaded source from here [https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.5.0.zip](url)

**why tensorflow doesn't directly provide static and dynamic windows library, why do we have to build it manually**

from this link [https://www.tensorflow.org/install/lang_c](url)

i can easily download tensorflowlite library
but it is **only x64 version**, whereas **i need x86 and x64** because i want to make an application that runs universally on **windows x86 and x64 versions**

**because tensorflow only provides the x64 version** [https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.5.0.zip](url)

i am not satisfied, **i want both x86 and x64 version** for my application to run on all windows versions universally

that's why I want to build it manually through the source provided [https://github.com/tensorflow/tensorflow](url)

- i downloaded tensorflow version 2.5.0 [https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.5.0.zip](url)
- i downloaded cmake gui x64 version 3.20.2 [https://cmake.org/download/](url)
- i downloaded bazel x64 version 4.1.0 [https://github.com/bazelbuild/bazel/releases](url)

I did tensorflow zip extraction to **D:\tensorflow \tensorflow-2.5.0**
i make BUILD folder to **D:\tensorflow\BUILD**

i run cmake gui
- "Where is the source code" set to **D:\tensorflow\tensorflow-2.5.0\tensorflow\lite**
- "Where to build the binaries" set to **D:/tensorflow/BUILD**
cmake configue is
- visual studio 15 2017
- x64 use default native compiler
**D:\tensorflow\tensorflow-2.5.0\tensorflow\lite** **has CMakeLists.txt**
the error detail is :
**Setting build type to Release, for debug builds use'-DCMAKE_BUILD_TYPE=Debug'.
Selecting Windows SDK version 10.0.17134.0 to target Windows 6.1.7601.
The C compiler identification is MSVC 19.15.26732.1
The CXX compiler identification is MSVC 19.15.26732.1
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 6.1.7601.
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/ExternalProject.cmake:2633 (message):
  error: could not find git for clone of abseil-cpp-populate
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/ExternalProject.cmake:3681 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "D:/tensorflow/BUILD/_deps/abseil-cpp-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1000 (message):
  CMake step for abseil-cpp failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1141:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1141 (cmake_language)
  tools/cmake/modules/OverridableFetchContent.cmake:531 (FetchContent_Populate)
  tools/cmake/modules/abseil-cpp.cmake:34 (OverridableFetchContent_Populate)
  tools/cmake/modules/Findabsl.cmake:18 (include)
  CMakeLists.txt:127 (find_package)

Configuring incomplete, errors occurred!
See also "D:/tensorflow/BUILD/CMakeFiles/CMakeOutput.log".**

**and then**
- TFLITE_ENABLE_FLEX  = unchecked **(i dont need it)**
- TFLITE_ENABLE_GPU  = unchecked **(i dont need it)**
- TFLITE_ENABLE_MMAP  = unchecked **(i dont need it)**
- TFLITE_ENABLE_NNAAPI = unchecked **(i dont need it)**
- TFLITE_ENABLE_RESOURCE  = unchecked **(i dont need it)**
- TFLITE_ENABLE_RUY  = unchecked **(i dont need it)**
- TFLITE_ENABLE_XNNPACK  = unchecked **(i dont need it)**
i reconfigure but still failed.

WHAT I WaNT IS, I WANT **TENSORFLOW LlTE STATIC LIBRARY BOTH x86 AND x64**
i dont want my app only working on x64, i want my app run unviversally both x86 and x64

please just tell me **"the right way to build tensorflow lite"**, because it says "**CMake step for abseil-cpp failed: 1**" do I have to download the abseil-cpp library. Thank you

i want STATIC library not DYNAMIC library
i need LITE version

**Comment by abattery** [comment]
@terryheo could you take a look?

**Comment by budibeta** [comment]
if you give me a static library, make sure you have both x86 and x64, and make sure builded with **/MT** Not **/MD**

**Comment by terryheo** [comment]
For Win32 (32bit Windows) build, you need https://github.com/tensorflow/tensorflow/pull/49171 (which will be merged soon)
BTW, you need to configure your build environment with https://www.tensorflow.org/install/source_windows
