### ISSUE TITLE
Tensorflow 2.5.0 Windows - Cannot import name 'keras' from partially initialized module 'tensorflow'

### ISSUE THREAD

**Issue by YuriyTigiev** [tensorflow/tensorflow#49518]
Python returns an error when I run script 
`Cannot import name 'keras' from partially initialized module 'tensorflow' (most likely due to a circular import) (C:\Users\ytigiev\source\repos\tensorflow\tensorflow.py)
`

OS - Wn 10 64 bit
IDE - VS 2019 16.9.6 + env (with Python 3.8.10 - 64 bit. (Downloaded from https://www.python.org/downloads/windows/))

Source code from https://www.tensorflow.org/api_docs/python/tf/keras (Is this sample code actual for tensorflow 2.5.0?)

I just copied first strings - "import"

import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

requirements.txt

absl-py==0.12.0
astunparse==1.6.3
cachetools==4.2.2
certifi==2020.12.5
chardet==4.0.0
cycler==0.10.0
flatbuffers==2.0
gast==0.4.0
google-auth==2.0.0.dev0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.38.0
h5py==3.2.1
idna==3.1
Keras==2.4.3
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
Markdown==3.3.4
matplotlib==3.4.2
numpy==1.20.3
oauthlib==3.1.0
opt-einsum==3.3.0
Pillow==8.2.0
pip==21.1.2
protobuf==3.17.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
scipy==1.6.3
setuptools==57.0.0
six==1.16.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
termcolor==1.1.0
typing-extensions==3.10.0.0
urllib3==1.26.4
Werkzeug==2.0.1
wheel==0.36.2
wrapt==1.12.1

**Comment by UsharaniPagadala** [comment]
@YuriyTigiev 

Could you please try to create model and route files and import them in main file.If you import everything at the top it would result in a circular import error, and let me if it helps.

and also refer similar [#44822](https://github.com/tensorflow/tensorflow/issues/44822), [#40265](https://github.com/tensorflow/tensorflow/issues/40265) issues.Thanks

**Comment by YuriyTigiev** [comment]
> @YuriyTigiev
> 
> Could you please try to create model and route files and import them in main file.If you import everything at the top it would result in a circular import error, and let me if it helps.
> 
> and also refer similar [#44822](https://github.com/tensorflow/tensorflow/issues/44822), [#40265](https://github.com/tensorflow/tensorflow/issues/40265) issues.Thanks

Sorry, 
I don't understand what do you mean ? - "create model and route files and import them in main file"

Could you send me a step by step instructions?

**Comment by UsharaniPagadala** [comment]
@YuriyTigiev 

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by YuriyTigiev** [comment]
The code snippet below. The second record raises error. 
The .py file doesn't contain any other strings of code.
Issue with import keras.  I have tested this code with python 3.7 and 3.8 with the same result.
For reproduce error 
1) Create empty console python project in Visual Studio Community 2019 
2) Add env with python 3.7  or 3.8 (both generates the same error)
3) Install all modules from requirments.txt 
4) Put this 4 strings 
5) Run it.

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
```

**Comment by UsharaniPagadala** [comment]
@YuriyTigiev 
Usually A circular import occurs when two or more modules depend on each other. This is due to the fact that each module is defined in terms of the other .Please make sure you followed the steps below

1.import inside the function. 
2.sysconfig is imported from the tensorflow module, so having this  
3.import at the top would cause a circular import, resulting in  
4.the tensorflow module missing symbols that come after sysconfig.  

for more information refer [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/sysconfig.py) ,find these steps [here](https://screenshot.googleplex.com/86FiqVnyAdFEJVN).Please let us know if it helps.Thanks

**Comment by YuriyTigiev** [comment]
> @YuriyTigiev
> Usually A circular import occurs when two or more modules depend on each other. This is due to the fact that each module is defined in terms of the other .Please make sure you followed the steps below
> 
> 1.import inside the function.
> 2.sysconfig is imported from the tensorflow module, so having this
> 3.import at the top would cause a circular import, resulting in
> 4.the tensorflow module missing symbols that come after sysconfig.
> 
> for more information refer [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/sysconfig.py) ,find these steps [here](https://screenshot.googleplex.com/86FiqVnyAdFEJVN).Please let us know if it helps.Thanks

Please, provide a correct example how to use import tensorflow. 

And based on your comments does it mean that the import in the example  from the https://www.tensorflow.org/api_docs/python/tf/keras doesn't defined correctly?

I'm trying to run this example in visual studio community 2019 with tenserflow 2.5.0

**Comment by YuriyTigiev** [comment]
I reinstalled visual studio community. 
Now everything works properly,
Thank you for attention.
