### ISSUE TITLE
tensorflow/core/user_kernels needed

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#496]
correct me if I am wrong, but I believe a subdir of tensorflow/core/user_kernels is needed to support user written GPU kernels (CPU is fine), this is due to the build rules in tensorflow/core/BUILD when building the user_ops_op_lib is a cc_library rather than say tf_cuda_library.

**Comment by martinwicke** [comment]
@keveman is working on the workflow for user written kernels/ops.

**Comment by keveman** [comment]
I added [instructions]( https://www.tensorflow.org/versions/master/how_tos/adding_an_op/index.html#adding-a-new-op) for building ops and kernels outside of TensorFlow source tree. Please have a look to see if it fits your need.
