### ISSUE TITLE
New Compatibility Problem of Stateful Random Binomial Operators

### ISSUE THREAD

**Issue by feiyouliang** [tensorflow/tensorflow#49607]
hi,
When tf is upgraded from 1.15 to 2.4.1, the implementation of the StatefulRandomBinomial operator is different in the two versions, and the verification rules for the input count and probs shape are changed. So what's the reason for this change? What are the differences between the two versions? In addition, the StatefulRandomBinomial operator is not found in API 1.15. Is this operator not supported in API 1.15?

**Comment by feiyouliang** [comment]
Are there any relevant conclusions?

**Comment by JW1992** [comment]
Hi feiyouliang,

Can you please clarify what you mean by "implementation is different"? Can you provide a piece of code to show the difference you were describing?

**Comment by wangpengmit** [comment]
Hi @feiyouliang , the shape restrictions were relaxed by https://github.com/tensorflow/tensorflow/commit/5396e7a3cd91b5f7895fa3dbe9809400e032d68a to allow broadcasting.

**Comment by feiyouliang** [comment]
@JW1992 The tf2.4.1 version is incompatible with tf1.5.1. For example, the input parameter shape is [3] and the value is [2, 2, 3], and the input parameter count is [1] and the value is [2]. The shape of the input parameter probs is [1] and the value is [0.5]. This example can work in version 1.15, but does not meet the verification requirements of version 2.4.1.

**Comment by jsmeredith** [comment]
Hi!  If I understand correctly, I believe this also works in TF2.  Using the example from rng.binomial:

```python
counts = [1.]
# Probability of success.
probs = [0.5]
 
rng = tf.random.Generator.from_seed(seed=234)
binomial_samples = rng.binomial(shape=[1], counts=counts, probs=probs)
print(binomial_samples)
```

Quick note: if this code used `counts = [1]`, it will (correctly) complain about lacking an integer kernel, so it requires the usage of the floating point value: `counts = [1.]`.

If that doesn't help explain, could you pass along an example which fails -- but that you expect to work?  Thanks!

**Comment by wangpengmit** [comment]
Hi @JW1992 , you are right that the semantics changed from broadcasting `counts` and `probs` from the *leftmost* dimension of `shape` to the *rightmost*. But we don't guarantee backward compatibility between TF1 and TF2.

BTW your example happen to work in both TF1 and TF2 because the leftmost and the rightmost dimension of shape `[3]` are the same thing.
