### ISSUE TITLE
Prediction difference in the converted TFlite model and trained checkpoint from TFOD API

### ISSUE THREAD

**Issue by Sudhan97** [tensorflow/tensorflow#49605]
### 1. System information

- OS Platform and Distribution : Android (Model trained linux Pop OS)
- TensorFlow installation : pip
- TensorFlow library : 2.4.1

**Descriptions**
We have been training model to predict corners using SSD MobileNet V2 320x320 FPNlite architecture model. We used TFOD API code files to train and convert the checkpoint into TFlite format . We were able to convert checkpoint (ckpt 55) into TFlite format without any errors. Analyzing prediction from TFlite model and checkpoint for the same image, we found there is significate difference in predicted coordinates and score values. We can't identify any issues when converting the model and the model is not quantized. 

Following are link includes to trained checkpoints, converted tflite model and prediction images.
 **link** : https://drive.google.com/drive/folders/1ZNJgMaUXWZTKCDQoB1gPFufwhypX6ZHB?usp=sharing

Tflite prediction -  
image : prediction_from_tflite.jpg
scores : [0.90501845 0.3708766  0.09824225 0.05691937 0.05246159 0.04990548
 0.04931968 0.03742141 0.03397185 0.03386968]

Checkpoint prediction 
image : prediction_from_checkpoint.jpg
scores : [0.98141104 0.9789326  0.7256872  0.49804866 0.309637   0.23567227
 0.19505009 0.05802718 0.056795   0.04440427]

**Comment by srjoglekar246** [comment]
Hey @Sudhan97 a few questions to clarify the issue:

1. Can you try the non-FPNLite `SSD MobileNet v2 320x320` from the [detection zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)? This will help me understand if the error is in the conversion of the model or inference side.
2. Could you show the commands you used to export & convert the model to TFLite?

**Comment by Sudhan97** [comment]
Hi @srjoglekar246, I also used non-FPNlite model previously there was no similar issues. Using FPNlite model  we were able to get more accurate predictions (using checkpoint) compared to non-FPNlite model. I'll update you on code used for export and conversion.

**Comment by Sudhan97** [comment]
@srjoglekar246 For the exporting we modified exporter_lib_v2 script (under object-detection : https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_lib_v2.py ) to export inference graph from specific checkpoint(using checkpoint number). In the following link, we have included the files used for exporting and converting.

exporter_lib_v2.py - modified to export inference graph from specific checkpoint.
export_saved_model_from_ckpt.py - script used to export into saved model using exporter_lib_v2 script
conversion_script.py - script used to convert into tflite model

**Comment by Sudhan97** [comment]
Hi @srjoglekar246, is there any update on this issue?

**Comment by srjoglekar246** [comment]
Hey @Sudhan97 , the procedure to generate a TFLite-friendly SavedModel is a little different, especially considering quantization & accelerator support. See [this g3doc](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). Note that the script to generate intermediate SavedModel is different (`export_tflite_graph_tf2.py`)

**Comment by Sudhan97** [comment]
@srjoglekar246, we followed instructions, generated intermediate saveModel using `export_tflite_graph_tf2.py` and converted into TFlite model enabling custom_ops as previously mentioned. 
Again it show the similar behaviour, where there is significant difference between prediction score from trained checkpoint and converted TFlite model for the same image. The model is not quantized. 

Prediction score from trained checkpoint
scores : [`0.98141104, 0.9789326, 0.7256872, 0.49804866`, 0.309637` 0.23567227,
0.19505009, 0.05802718, 0.056795, 0.04440427]

Prediction score from converted TFLite model
score : [`0.90501964, 0.37087825, 0.09824187, 0.05691952,` 0.05246329, 0.04990584,
 0.04931888, 0.03742117, 0.03397211, 0.03386891]

In the following link we have included the saved model generated using `export_tflite_graph_tf2.py script` and converted TFlite model. 
**Link for saved models and converted TFlite model**
https://drive.google.com/drive/folders/1ZsEHi8wXuberGjggYCZJp2Fuwqcd3gqL?usp=sharing

**Comment by srjoglekar246** [comment]
Can you try enabling regular NMS in TFLite using [this flag](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py#L122) in `export_tflite_graph_tf2.py`? This performs a slower (but more accurate) version of NonMaxSuppression in the SSD graph.

**Comment by Sudhan97** [comment]
@srjoglekar246 , we tried enbling regular NMS but it didn't chnage the results. We get the similar predictions and scores as previous converted models.

**Comment by srjoglekar246** [comment]
Hmm, it seems like the model is unsuitable somehow, since you are doing all the steps right :-/. Can you try using `SSD MobileNet V1 FPN 640x640` or `CenterNet MobileNetV2 FPN 512x512` from the same zoo? (See [CenterNet conversion Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/centernet_on_device.ipynb)). There might be some discrepenacy in output of the TF/TFLite kernels in that SSD FPNLite model you are trying.

**Comment by Sudhan97** [comment]
@srjoglekar246, We trained model using `SSD MobileNet V1 FPN 640x640` reducing the image input size 320x320. We experience similar issue with this architecture also. We are getting more accurate prediction and score from checkpoint but the **converted TFLite model** has low accuracy and score.  Following is the prediction score from checkpoint and converted TFLite model. 

Prediction score from **trained checkpoint**
scores : [`0.9993659,  0.99498355, 0.98933035, 0.80486923,` 0.42113468,  0.10038441,
 0.08877391, 0.08859652, 0.02857885, 0.02726579]

Prediction score from converted **tflite model**
score : [ `0.78976953, 0.28661278, 0.23196483, 0.152545,`   0.13510752, 0.11414424,
 0.0949465,  0.08693931, 0.07839099, 0.07618982, 0.07174137, 0.05871615]

We have shared the link for exported saved model and converted model.
**link :**https://drive.google.com/drive/folders/1zG4aFIRF6Rujmp-mrHKxEYPvw4XKUBe-?usp=sharing

**Comment by srjoglekar246** [comment]
I took a look at the code, and I think the [TF2 exporting library](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_lib_tf2.py) doesn't handle the FPN portion of the feature extractor correctly. (IIUC, a portion of the graph is missing)

There are two ideas I have. I don't have the cycles to fully debug this, but we can push with your help.

1) The CenterNet MobileNetV2 FPN 512x512 download doesn't have this issue. You can try using it with a higher resolution than 320x320 if possible, and it should perform well (especially with NNAPI/GPU acceleration). At the very least, we can verify that the SavedModel & the TFLite model have the same outputs.

2) The [Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection) folks recently added support for training EfficientDets with custom data, can you check if that works better for you?

Sorry about the confusion, there seem to be some [FPN-specific](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_ssd_graph_lib.py#L281) portions of the TF1 exporting script that weren't correctly ported to the TF2 version.

**Comment by Sudhan97** [comment]
@srjoglekar246 Hi, we trained model using **CenterNet MobileNet V2 FPN 512x512** as you suggested and we didn't find accuracy difference between predictions from checkpoint and converted TFlite model (prediction taken using Python API for tflite) `but when the  same model used in android application we don't get the accurate prediction (even for the same image).` We follow the similar approach, implemented in sample android applicaton https://github.com/tensorflow/examples/blob/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L186

Doesn't this mode required different approach because the sample android has used SSD Mobilenet architecture? 
FYI we use the float model.

**Converted tflite model link**:

**Comment by srjoglekar246** [comment]
Yup. As you correctly guessed, you need to make a few changes based on your model. Assuming you are not exporting the CenterNet model with keypoint output (since you only need bounding boxes), you simply need to disable input preprocessing that happens in the inference code. @lintian06 / @lu-wang-g  can you provide a pointer to how to disable preprocessing to support CenterNet?

**Comment by lu-wang-g** [comment]
@srjoglekar246 I may not have the full context, but why the input processing need to be disabled? Is there a custom implementation? 

As far as I understand, the converted model should be able to fit the tflite object detection reference app. But there are a few places need to be checked:
1. Have you added metadata to your model. See the instruction [here](https://www.tensorflow.org/lite/convert/metadata_writer_tutorial#object_detectors). Note that you need to pack the label file into the model. The label file in the [asset](https://github.com/tensorflow/examples/tree/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android/app/src/main/assets) folder is for demonstration purpose only.
2. Have you updated the [model and label file information](https://github.com/tensorflow/examples/blob/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/DetectorActivity.java#L53-L57) accordingly?
3. Try [building with Task Library](https://github.com/tensorflow/examples/tree/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android#switch-between-inference-solutions-task-library-vs-tflite-interpreter) , a high-level API compared to Interpreter. It encapsulates everything from init, to pre/post processing. So as long as you have the correct model file [here](https://github.com/tensorflow/examples/blob/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/DetectorActivity.java#L55), it will handle the rest for you.

**Comment by srjoglekar246** [comment]
The CenterNet graph obtained from ODAPI does the pre-processing [within the model](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_lib_tf2.py#L287), so the model takes as input a [float tensor with raw pixel values](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_lib_tf2.py#L268). IIUC we will need some changes so that we don't pre-process the data before invoking the model.

**Comment by lu-wang-g** [comment]
Does the model require an input image of 320x320 (read from Netron) or any random shape?

**Comment by srjoglekar246** [comment]
Shape is fixed (320x320)

**Comment by lu-wang-g** [comment]
Then we still need to convert the camera output to 320x320 RGB, right?

**Comment by srjoglekar246** [comment]
Aah yes, I just meant disabling the normalization etc in the pre-processing. My bad :-)

**Comment by lu-wang-g** [comment]
I see. That makes sense!

To disable normalization in lib_interpreter, just update the value for [MEAN and STD](https://github.com/tensorflow/examples/blob/fa33ab053877a0acbee1b78c5e3120554b94e5a5/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L62-L63) as follows:
```
private static final float IMAGE_MEAN = 0.0f;
private static final float IMAGE_STD = 1.0f;
```

To disable normalization in lib_task_api, set mean and std to the following value when [creating the metadata](https://www.tensorflow.org/lite/convert/metadata_writer_tutorial#object_detectors):
```
_INPUT_NORM_MEAN = 0.0
_INPUT_NORM_STD = 1.0
```
