### ISSUE TITLE
Update variable name within Anomaly Detection example

### ISSUE THREAD

**Issue by cl3m3nt** [tensorflow/tensorflow#49602]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:https://www.tensorflow.org/tutorials/generative/autoencoder?hl=en

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):
Within Anomaly Detection section, within Build the Model, some variables names are misleading with regard to data that is handled when using the encoder and decoder after training.
As a matter of fact, data here are ECG time series and no longer images like in previous example with mnist and fashion_mnist

### Clear description

encoded_imgs = autoencoder.encoder(normal_test_data).numpy()
decoded_imgs = autoencoder.decoder(encoded_imgs).numpy()

should be replaced by something like:
encoded_data = autoencoder.encoder(normal_test_data).numpy()
decoded_data = autoencoder.decoder(encoded_data).numpy()

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@cl3m3nt 
Thank you for your update, we will review the changes and submit a pr accordingly.

**Comment by 8bitmp3** [comment]
@Saduf2019 @cl3m3nt Thank you, will review.

**Comment by 8bitmp3** [comment]
https://github.com/tensorflow/docs/pull/1905 ✅

**Comment by Saduf2019** [comment]
@8bitmp3 
Thank you for the update, shall i move this issue to closed status.
