### ISSUE TITLE
Didn't find op for builtin opcode 'EXPAND_DIMS'

### ISSUE THREAD

**Issue by HMellor** [tensorflow/tensorflow#49603]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10  20H2 (19042.985)
- TensorFlow installed from (source or binary): Binary
- Tensorflow version (commit SHA if source): 2.4.0-alpha
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33 BLE

**Describe the problem**
I made a model which uses the following Keras layers:
* Conv1d
* Maxpooling1d
* Flatten
* Dense

After conversion and quantisation I get the following error when attempting to use the model:
```
Didn't find op for builtin opcode 'EXPAND_DIMS' version '1'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?

Failed to get registration from op code EXPAND_DIMS

Failed starting model allocation.

AllocateTensors() failed 
```

**Please provide the exact sequence of commands/steps when you ran into the problem**

This is the code that led to the error [from the hello world example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world)
```
  // Map the model into a usable data structure. This doesn't involve any
  // copying or parsing, it's a very lightweight operation.
  model = tflite::GetModel(g_model);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    TF_LITE_REPORT_ERROR(error_reporter,
                         "Model provided is schema version %d not equal "
                         "to supported version %d.",
                         model->version(), TFLITE_SCHEMA_VERSION);
    return;
  }
  
  // This pulls in all the operation implementations we need.
  // NOLINTNEXTLINE(runtime-global-variables)
  static tflite::AllOpsResolver resolver;

  // Build an interpreter to run the model with.
  static tflite::MicroInterpreter static_interpreter(
      model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
  interpreter = &static_interpreter;

  // Allocate memory from the tensor_arena for the model's tensors.
  TfLiteStatus allocate_status = interpreter->AllocateTensors();
  if (allocate_status != kTfLiteOk) {
    TF_LITE_REPORT_ERROR(error_reporter, "AllocateTensors() failed");
    return;
  } 
```

**Comment by mohantym** [comment]
Hi @HMellor  !
Could you test with instructions  from[ TFLite-micro-arduino ](https://github.com/tensorflow/tflite-micro-arduino-examples)repo.
Work around is add the op from OpResolver in the C++ code.
```
static tflite::MicroMutableOpResolver<1> micro_op_resolver; /* no of times I have added any ops through ops resolver
micro_op_resolver.AddExpand_dims(); /* I've added this operation */

```
[Reference.](https://github.com/tensorflow/tflite-micro/issues/284#issuecomment-880339107)

Thank you!
