### ISSUE TITLE
[QST] tensorflow 2.4.2 release date [security patches]

### ISSUE THREAD

**Issue by asishm-wk** [tensorflow/tensorflow#49611]
Synopsys Black Duck is flagging tensorflow 2.4.0 with security vulnerabilities

looking at the security advisories - it looks like these would be patched with 2.4.2 - Is there an estimated date of when 2.4.2 would be released?

Apologies if this is already discussed elsewhere and I just wasn't able to find it

**Comment by ymodak** [comment]
Thanks for your issue. We can expect a patch release for TF 2.4 in next week.

**Comment by asishm-wk** [comment]
@ymodak do you have any further updates? - didn't want the bot to close this :)

**Comment by ymodak** [comment]
TF 2.4.2 has been released https://github.com/tensorflow/tensorflow/releases/tag/v2.4.2
Thanks!
