### ISSUE TITLE
Where is the documentation for contrib/layers? (Docs in general ...)

### ISSUE THREAD

**Issue by Hvass-Labs** [tensorflow/tensorflow#4964]
In another thread I asked about consolidation of the builder API's for TensorFlow. (https://github.com/tensorflow/tensorflow/issues/3771)

The response was that contrib/layers was going to be one of the official builder API's to be included in TensorFlow core along with contrib/learn. So I wanted to see how it works and learn how to use it. But the only documentation I could find for contrib/layers was this:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/README.md

https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.layers.html

Is this really all the documentation there is for contrib/layers? Surely there must be more? You couldn't possibly expect people to be able to learn how to use it from these two documents alone? The README doesn't even make any sense. Am I missing something?

Please allow me a short rant.

I'm sure you're familiar with scikit-learn's beautifully designed API and extensive, polished documentation. It might serve as a good inspiration for TensorFlow. You may think that you don't have time to streamline the TensorFlow API and improve the documentation because there's more important things that must be done. But I believe this is actually the single most important thing you could do to move the project forward. Here's why:

If each new person wastes 10 hours trying to learn TensorFlow and there's 10,000 people who are learning to use it, then it's 100,000 wasted developer-hours! I actually think those numbers are very conservative. Personally I've probably wasted more than 100 hours trying to figure out how the complicated and poorly documented TensorFlow API works, and it seems there's many more than 10,000 people using TensorFlow. So maybe it's more than 1 million wasted developer-hours in total! That is 500 developer-years (assuming a month is about 160 work-hours)! Imagine if this developer-time was put into more constructive use. All it takes is for the TensorFlow API and docs to be more polished so it would be easier to learn. It would be a tiny investment in time and effort from the dev-team, compared to the return you'll get in productivity from the community. I really wish this is something you would prioritize highly.

Thanks!

**Comment by jart** [comment]
I agree @Hvass-Labs. TensorFlow needs to have world-class documentation that's slick, polished, intuitive, and accessible to everyone. We've got a lot of amazing people who've worked hard to bring our documentation pretty close to that level of quality. Everything else—as @martinwicke pointed out in #3771—goes in contrib.

We encourage you to get involved and help us improve. TensorFlow is a high impact project. Any time you generously choose to volunteer in improving our documentation will pay dividends for the 10,000 people who read it later.

**Comment by Hvass-Labs** [comment]
Thanks for the quick and positive reply.

I have already spent months trying to help explain TensorFlow to a wider audience. This is done on my own time for my own money:

https://www.youtube.com/playlist?list=PL9Hr9sNUjfsmEu1ZniY0XpHSzl5uihcXZ

But I am frequently stuck and spend days trying to figure out how to do things that should be fairly simple, because there's no example code showing how to do it, and the TensorFlow API is generally quite complicated and lots of features are poorly documented.

There is a school of thought in software engineering that beginners can help document code as they learn how to use it. I strongly disagree with that notion. It takes a beginner maybe 50x as much time to learn a piece of code as the engineer who wrote it, and it is unlikely that a beginner will understand all the implications of a particular function or class. In my opinion, code is not completed before it is polished and well-documented.

It is the same with fixing bugs. I previously posted a report here for a bug that occasionally showed itself. The TensorFlow developer couldn't reproduce and hence marked it as community support. Fair enough. Several other individuals later posted they experienced it as well. But the function where it happened wasn't well-documented so I had no idea what the function was supposed to do, and hence I couldn't help fix the bug. It was eventually fixed so all is good, but it demonstrates how difficult it is for the community to help out if the docs don't describe the API very well.

How many times do you have to ask a co-worker how to do something in TensorFlow? Well, people in the community don't have that extensive and quick support-network. All we can do is post a question on StackOverflow and hope it gets answered (a lot of questions don't even though @mrry is making a valiant effort).

Once again, I very much appreciate your friendly and welcoming response, but I hope that the TensorFlow team considers the possibility that perhaps you still have quite a way to go before the API and docs are as polished as e.g. scikit-learn. A good place to start would be consolidation and proper documentation of the builder API's (e.g. contrib.layers, contrib.slim and PrettyTensor).

Cheers!

**Comment by arahja** [comment]
At the risk of sound naive, I was searching for similar answers regarding the tensorflow contrib documentation and stumbled upon this. Hopefully this helps someone. 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc/api_docs/python
