### ISSUE TITLE
Messy in Python API Docs - state_ops.html#constant_initializer

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#4969]
https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#constant_initializer

On Constant Initializer  -> Examples:

The very large gray box contains the html of other initializer docs. Hope it can be fixed.

**Comment by Haroenv** [comment]
Error is because https://github.com/tensorflow/tensorflow/blob/d44d271c9da4d244ce4b2ffaf808adbe4cff759d/tensorflow/python/ops/init_ops.py#L142 isn't closing the code block I think.

**Comment by jart** [comment]
This is a duplicate of #4849 which has been corrected at HEAD. The site will be updated shortly.

**Comment by gunan** [comment]
This is fixed at master and r0.12
We will not merge the fix back to 0.11, therefore closing the issue.
