### ISSUE TITLE
ValueError: Shapes (None, 10, 10) and (None, 10) are incompatible

### ISSUE THREAD

**Issue by ghaliayik** [tensorflow/tensorflow#49706]
**System information**
- Have I written custom code (link bellow):
- On Google Colab using TF 2.x

Before today, my code can run without any problem. But suddenly today some error occur. 

`ValueError                                Traceback (most recent call last)
<ipython-input-37-91d03c49a48b> in <module>()
      2                          batch_size=128,
      3                          epochs=40,
----> 4                          validation_data=(x_val, y_val))

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    984           except Exception as e:  # pylint:disable=broad-except
    985             if hasattr(e, "ag_error_metadata"):
--> 986               raise e.ag_error_metadata.to_exception(e)
    987             else:
    988               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:830 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:813 run_step  *
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:771 train_step  *
        loss = self.compiled_loss(
    /usr/local/lib/python3.7/dist-packages/keras/engine/compile_utils.py:201 __call__  *
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/local/lib/python3.7/dist-packages/keras/losses.py:142 __call__  *
        losses = call_fn(y_true, y_pred)
    /usr/local/lib/python3.7/dist-packages/keras/losses.py:246 call  *
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/keras/losses.py:1631 categorical_crossentropy
        y_true, y_pred, from_logits=from_logits)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/keras/backend.py:4827 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 10, 10) and (None, 10) are incompatible`

link for colab : https://colab.research.google.com/drive/14CCxoPOE3cDGIsz8Ua6XeF-Rl9zM4KRe?usp=sharing
link for dataset : https://drive.google.com/drive/folders/1BUWx1YzE-MtL2L-YZG4r2uqwWwNjjDA6?usp=sharing

**Comment by tilakrayal** [comment]
@ghaliayik ,

I have tried to run the codein TF version  2.5. and nightly version and noticed that session is being crashed. Could you please provide a minimal code snippet which pinpoint the issue.

Thanks!

**Comment by ghaliayik** [comment]
@tilakrayal ,
You mean like this ?

![a](https://user-images.githubusercontent.com/11738835/119650557-29074180-be4e-11eb-9264-59292bf26fc0.PNG)
![b](https://user-images.githubusercontent.com/11738835/119650551-27d61480-be4e-11eb-94c7-a06aa0c2f031.PNG)

**Comment by ghaliayik** [comment]
I try to run again just now and there is no more error again. Thanks @tilakrayal

**Comment by ymodak** [comment]
The colab environment variables are lost if the notebook is idle for sometime (not sure exact amount of time). So you my want to rerun whole notebook from top most cell and try again.
