### ISSUE TITLE
Dtype error when using Mixed Precision and building EfficientNetB0 Model

### ISSUE THREAD

**Issue by gauravreddy08** [tensorflow/tensorflow#49725]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.5.0
- Python version: python 3.7
- GPU model and memory: Tesla T4

**Error**
`TypeError: Input 'y' of 'Sub' Op has type float16 that does not match type float32 of argument 'x'`

**Current behaviour**

While using Mixed Precision and building a Keras Functional API model (EfficientNet B0), it shows the below error

<img width="935" alt="image" src="https://user-images.githubusercontent.com/57211163/119546314-6669c180-bdb1-11eb-918f-3cb13d225759.png">
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/57211163/119546338-6c5fa280-bdb1-11eb-844d-91175160e6e5.png">

**Describe the expected behaviour**
The Global Policy I set in the previous cell was `mixed_float16`. The problem works fine when running on `tensorflow 2.4.1` so the bug is with `tensorflow 2.5.0`

You can reproduce the same error using the below notebook :
https://colab.research.google.com/drive/1TfNZSIJ_I7IZI35RsGFnTdj-6beMHV2_?usp=sharing

**Comment by mrdbourke** [comment]
Following this, I'm having the same issue.

Works on 2.4.1, breaks on 2.5.0

**Comment by innat** [comment]
It seems like a bug in `TF 2.5` (also in `tf-nightly`). Here is the reproducible code 

```
import tensorflow as tf 
print(tf.__version__) # 2.5

tf.keras.mixed_precision.set_global_policy('mixed_float16')
tf.keras.applications.EfficientNetB0(
    include_top=True, weights='imagenet', input_tensor=None,
    input_shape=None, pooling=None, classes=1000,
    classifier_activation='softmax'
)
```

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/deac7077472f47ce5624e2015ddf3056/49725-2-5.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/afe5a652eb182b7caf44cba1f54b34d6/food_visionnightly.ipynb). In tf v2.4, code executed without errors.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/a4753ef385f6d94f6034aac4983110d0/49725-2-4food_vision.ipynb).

**Comment by ashikshafi08** [comment]
It seems like a bug with `EfficientNetB0`itself. I was able to run `mixed_precision` without any errors on the Resnet101 model. 
![Screenshot 2021-05-27 at 5 14 47 AM](https://user-images.githubusercontent.com/45290954/119745070-048d8280-beab-11eb-871e-d1215ab3b577.png)

**Comment by innat** [comment]
The above error occurs only one 

- **TensorFlow 2.5** and **tf-nightly** (currently tf 2.6.
- Only on the **EfficientNet Bx** family but not other architecture.

**Comment by ssuhas76** [comment]
> It seems like a bug with `EfficientNetB0`itself. I was able to run `mixed_precision` without any errors on the Resnet101 model.
> ![Screenshot 2021-05-27 at 5 14 47 AM](https://user-images.githubusercontent.com/45290954/119745070-048d8280-beab-11eb-871e-d1215ab3b577.png)

Why is pooling layer not sued for ResNet 101 code?

**Comment by mlukianska** [comment]
For me worked this code:
**!pip install tensorflow-gpu==2.4.1** (!pip install tensorflow==2.4.1 - this didn't work, it didn't downgrade the version)
import tensorflow as tf
print(tf.__version__)
