### ISSUE TITLE
Wrong warning message for tf.data.experimental.enable.debug_mode()

### ISSUE THREAD

**Issue by aliencaocao** [tensorflow/tensorflow#49724]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 pro 64 bit 21H1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.3 update 1, 8.2.0
- GPU model and memory: RTX 2060 super 8GB

**Describe the current behavior**
When trying to access tensor.numpy inside a tf.data function, Tensorflow reports tensor object has no numpy attribute. A warning message is given: 
C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:3703: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable.debug_mode()`.
However, this warning message is wrong. The "tf.data.experimental.enable.debug_mode()" does not exist as a function.
**Describe the expected behavior**
The correct command is 'tf.data.experimental.enable_debug_mode()', thus there is a typo that replaced the underscore after enable to be a dot. I have not checked thoroughly in the entire repo for any other occurrence of the same typo.
**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): yes, fix typo.
https://github.com/tensorflow/tensorflow/pull/49825

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
As this is a simple typo issue, I don't think an example is needed. Here is a permalink to the line in the source code that has the typo.
https://github.com/tensorflow/tensorflow/blob/dc487160e67bdb9b4bb317e0922e3ae3eb513c43/tensorflow/python/data/ops/dataset_ops.py#L3918

**Comment by rmothukuru** [comment]
@aliencaocao,
I have linked [your PR](https://github.com/tensorflow/tensorflow/pull/49825) to this issue. Meanwhile, can you please provide a reproducible code demonstrating the bug so that community can understand it clearly? Thanks!

**Comment by aliencaocao** [comment]
Sure. But bfore the code itself, I would just like to remind that this is possibly just a typo and not really a program bug. The stack trace is provided in case of any use, but in this case I doubt if it will be useful.

On a side note, if anyone can suggest a way for me to convert a tensor into numpy array in this particular use case (inside a tf.data mapped function), please advise me as I desperately need to do this. I did try the suggested tf.data.experimental.enable_debug_mode() (I corrected the typo here), but it still gives the same 'AttributeError: 'Tensor' object has no attribute 'numpy'' error.

```
import tensorflow as tf
import tensorflow_datasets as tfds

ds = tfds.load('oxford_iiit_pet', split='train')
tf.config.run_functions_eagerly(True)

def preprocess(datapoint):
    mask = datapoint['segmentation_mask']
    mask.numpy()
    return mask

ds.map(preprocess)
```

Running this will give me a warning:

```
C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:3703: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable.debug_mode()`.
  warnings.warn(
```

full trace stack:

```
AttributeError                            Traceback (most recent call last)

<ipython-input-1-16c739303191> in <module>
     10     return mask
     11 
---> 12 ds.map(preprocess)

C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in map(self, map_func, num_parallel_calls, deterministic)
   1923         warnings.warn("The `deterministic` argument has no effect unless the "
   1924                       "`num_parallel_calls` argument is specified.")
-> 1925       return MapDataset(self, map_func, preserve_cardinality=True)
   1926     else:
   1927       return ParallelMapDataset(

C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in __init__(self, input_dataset, map_func, use_inter_op_parallelism, preserve_cardinality, use_legacy_function)
   4481     self._use_inter_op_parallelism = use_inter_op_parallelism
   4482     self._preserve_cardinality = preserve_cardinality
-> 4483     self._map_func = StructuredFunctionWrapper(
   4484         map_func,
   4485         self._transformation_name(),

C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in __init__(self, func, transformation_name, dataset, input_classes, input_shapes, input_types, input_structure, add_to_graph, use_legacy_function, defun_kwargs)
   3710     resource_tracker = tracking.ResourceTracker()
   3711     with tracking.resource_tracker_scope(resource_tracker):
-> 3712       self._function = fn_factory()
   3713       # There is no graph to add in eager mode.
   3714       add_to_graph &= not context.executing_eagerly()

C:\Program Files\Python38\lib\site-packages\tensorflow\python\eager\function.py in get_concrete_function(self, *args, **kwargs)
   3132          or `tf.Tensor` or `tf.TensorSpec`.
   3133     """
-> 3134     graph_function = self._get_concrete_function_garbage_collected(
   3135         *args, **kwargs)
   3136     graph_function._garbage_collector.release()  # pylint: disable=protected-access

C:\Program Files\Python38\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_garbage_collected(self, *args, **kwargs)
   3098       args, kwargs = None, None
   3099     with self._lock:
-> 3100       graph_function, _ = self._maybe_define_function(args, kwargs)
   3101       seen_names = set()
   3102       captured = object_identity.ObjectIdentitySet(

C:\Program Files\Python38\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   3442 
   3443           self._function_cache.missed.add(call_context_key)
-> 3444           graph_function = self._create_graph_function(args, kwargs)
   3445           self._function_cache.primary[cache_key] = graph_function
   3446 

C:\Program Files\Python38\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3277     arg_names = base_arg_names + missing_arg_names
   3278     graph_function = ConcreteFunction(
-> 3279         func_graph_module.func_graph_from_py_func(
   3280             self._name,
   3281             self._python_function,

C:\Program Files\Python38\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    997         _, original_func = tf_decorator.unwrap(python_func)
    998 
--> 999       func_outputs = python_func(*func_args, **func_kwargs)
   1000 
   1001       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in wrapped_fn(*args)
   3685           attributes=defun_kwargs)
   3686       def wrapped_fn(*args):  # pylint: disable=missing-docstring
-> 3687         ret = wrapper_helper(*args)
   3688         ret = structure.to_tensor_list(self._output_structure, ret)
   3689         return [ops.convert_to_tensor(t) for t in ret]

C:\Program Files\Python38\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in wrapper_helper(*args)
   3615       if not _should_unpack(nested_args):
   3616         nested_args = (nested_args,)
-> 3617       ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
   3618       if _should_pack(ret):
   3619         ret = tuple(ret)

C:\Program Files\Python38\lib\site-packages\tensorflow\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    693       except Exception as e:  # pylint:disable=broad-except
    694         if hasattr(e, 'ag_error_metadata'):
--> 695           raise e.ag_error_metadata.to_exception(e)
    696         else:
    697           raise

AttributeError: in user code:

    <ipython-input-1-16c739303191>:9 preprocess  *
        mask.numpy()
    C:\Program Files\Python38\lib\site-packages\tensorflow\python\framework\ops.py:401 __getattr__
        self.__getattribute__(name)

    AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by jvishnuvardhan** [comment]
@aliencaocao I noticed that your PR got approved but some errors are blocking it from merging. We will look into it. Thanks!
