### ISSUE TITLE
can't import plot_model from keras.utils

### ISSUE THREAD

**Issue by arsinnius** [tensorflow/tensorflow#49734]
When I run this line of code on google colab (with or without the GPU),

```from keras.utils import plot_model```

I get the following error:

"cannot import name 'plot_model' from 'keras.utils' (/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py)"

When I went to bed last night the code worked. This morning it doesn't. What happened and what can I do? Thanks in advance.

**Comment by borrerojuan** [comment]
Try with

from tensorflow.keras.utils import plot_model


but there is a bug in keras that should be fixed.

**Comment by ymodak** [comment]
Also see the guides for usage examples https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model
```python
import tensorflow as tf
tf.keras.utils.plot_model(model, "my_first_model.png")
```
