### ISSUE TITLE
Magic_wand example on Arduino Nano 33: 'class LSM9DS1Class' has no member named 'setContinuousMode' 

### ISSUE THREAD

**Issue by foost** [tensorflow/tensorflow#49733]
@tensorflow/micro

**System information**
Windows 10
Arduino 1.8.12 IDE
Arduino Nano 33 BLE Sense

**Describe the problem**
When trying Magic_wand example from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/magic_wand 
during compilation, the IDE reports the following error:

```
arduino_accelerometer_handler.cpp:50:7: error: 'class LSM9DS1Class' has no member named 'setContinuousMode'
   IMU.setContinuousMode();
```

**Please provide the exact sequence of commands/steps when you ran into the problem**
I have followed the steps in the documentation to fix v1.0.0 of the driver. LSM9DS1.cpp looks as follows:

```
int LSM9DS1Class::begin()
{
  _wire->begin();

  // reset
  writeRegister(LSM9DS1_ADDRESS, LSM9DS1_CTRL_REG8, 0x05);
  writeRegister(LSM9DS1_ADDRESS_M, LSM9DS1_CTRL_REG2_M, 0x0c);

  delay(10);

  if (readRegister(LSM9DS1_ADDRESS, LSM9DS1_WHO_AM_I) != 0x68) {
    end();

    return 0;
  }

  if (readRegister(LSM9DS1_ADDRESS_M, LSM9DS1_WHO_AM_I) != 0x3d) {
    end();

    return 0;
  }

  writeRegister(LSM9DS1_ADDRESS, LSM9DS1_CTRL_REG1_G, 0x78); // 119 Hz, 2000 dps, 16 Hz BW
  writeRegister(LSM9DS1_ADDRESS, LSM9DS1_CTRL_REG6_XL, 0x70); // 119 Hz, 4G

  writeRegister(LSM9DS1_ADDRESS_M, LSM9DS1_CTRL_REG1_M, 0xb4); // Temperature compensation enable, medium performance, 20 Hz
  writeRegister(LSM9DS1_ADDRESS_M, LSM9DS1_CTRL_REG2_M, 0x00); // 4 Gauss
  writeRegister(LSM9DS1_ADDRESS_M, LSM9DS1_CTRL_REG3_M, 0x00); // Continuous conversion mode

  // Enable FIFO (see docs https://www.st.com/resource/en/datasheet/DM00103319.pdf)
  writeRegister(LSM9DS1_ADDRESS, 0x23, 0x02);
  // Set continuous mode
  writeRegister(LSM9DS1_ADDRESS, 0x2E, 0xC0);
  
  return 1;
}
```

and 

```
int LSM9DS1Class::accelerationAvailable()
{
  //if (readRegister(LSM9DS1_ADDRESS, LSM9DS1_STATUS_REG) & 0x01) {
  //  return 1;
  //}
  // Read FIFO_SRC. If any of the rightmost 8 bits have a value, there is data
  if (readRegister(LSM9DS1_ADDRESS, 0x2F) & 63) {
    return 1;
  }
  return 0;
}
```

I also tried to use v1.1.0. In that case, no error during compilation and upload, but the Arduino Nano does not seem to run the code properly (no flashing LED, no serial port output). 

I have tried both approaches (v.1.0.0 modified, and v.1.1.0 unmodified) several times, including multiple resets and long waits of the Arduino Nano after upload.

**Comment by mmullen200** [comment]
I'm running into the same issue.

**Comment by sachinprasadhs** [comment]
Tflite Micro has been moved to a separate repository. The example which you are trying can be found here https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/magic_wand.
There has been few changes made to the example. Could you please try with the latest version and let us know the outcome. Thanks!
