### ISSUE TITLE
precompile model executable binaries

### ISSUE THREAD

**Issue by onyx22574** [tensorflow/tensorflow#49740]
Hello,

I'd like to ask you if there is the possibility to have aka ML compiler and execution engine for ARM MCUs (Cortex-M). Is it somehow possible to use for this TF-micro? Is there another way to prepare executable ML code (model) for Cortex-M devices with TensorFlow? As of now, I can get with TF-Lite-Micro as close as possible to MCU ARM Cortex-M class devices and leverage CMSIS-NN optimized kernels for this.

**Comment by sushreebarsa** [comment]
@onyx22574 The core runtime just fits in 16 KB on an Arm Cortex M3 and can run many basic models. Could you have a look at this [link](https://www.tensorflow.org/lite/microcontrollers) where the supported platforms and the relevant features are well explained. Please refer this and let us know if that helps?
Thank you!
