### ISSUE TITLE
Keras spectral normalization (SN) function has stopped working

### ISSUE THREAD

**Issue by arsinnius** [tensorflow/tensorflow#49761]
Something must have happened to Keras overnight because suddenly two Keras features have stopped working. I already reported the ```from keras.utils import plot_model```  bug. Now there's another. ```spectral_normalization.py``` is a function that takes a keras layer as input and implements the SN regularization algorithm. Since this morning it throws an ```AssertionError```.
```
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/wrappers.py(50)__init__()
     48 
     49   def __init__(self, layer, **kwargs):
---> 50     assert isinstance(layer, Layer)
     51     self.layer = layer
     52     super(Wrapper, self).__init__(**kwargs)
```
Of course, I can just not use spectral normalization, but it makes a HUGE difference in model stability. Thanks.

**Comment by UsharaniPagadala** [comment]
@arsinnius 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Thanks

**Comment by arsinnius** [comment]
UsharaniPagadala, I apologize for not following the template but I'm new at this.

**System information**
I'm running the program ```spectral_normalization``` copyrighted in 2020 by the Tensorflow team on google colab using a GPU. 
The Tensorflow version is ```v2.5.0-0-ga4dfb8d1a71 2.5.0```. 
The python version is 3.7.10

**Current Behavior**
```spectral_normalization``` is a wrapper for ```tf.keras.layers``` but it is not recognizing Keras layers. It throws the ```AssertionError``` shown above. 

**Standalone Code to Reproduce the Issue**
An MWE is
```
from keras.layers import Conv2D, Layer
layer = Conv2D
if not isinstance(layer, Layer):
    raise ValueError(
        'Please initialize `TimeDistributed` layer with a '
        '`Layer` instance. You passed: {input}'.format(input=layer))
```
The above code causes multiple errors but the first is the ```ValueError```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-4e881acf7107>", line 6, in <module>
    '`Layer` instance. You passed: {input}'.format(input=layer))
ValueError: Please initialize `TimeDistributed` layer with a `Layer` instance. You passed: <class 'keras.layers.convolutional.Conv2D'>
```
Thanks again.

**Comment by bhack** [comment]
You last gist is not a valid test as `Conv2D` is not a instance is a class.
```python
from keras.layers import Conv2D, Layer
import inspect 
layer_b = Conv2D
print(inspect.isclass(layer_b))
print(layer_b.__name__)
```

```
True
Conv2D
````

 Can you clearly share just a few line example to reproduce the bug?

**Comment by arsinnius** [comment]
Thank you, bhack. 

Based on your request, I got a copy of ```spectral_normalization``` from
```
https://github.com/tensorflow/addons/blob/v0.13.0/tensorflow_addons/layers/spectral_normalization.py#L21-L130
```
put it in my directory and ran the following code:
```
from keras.layers import Conv2D, Input
from spectral_normalization import SpectralNormalization

def foo_model( k_size, latent_dim, pwr_iter):
  z = Input(shape=(latent_dim,))
  x = SpectralNormalization(Conv2D(2**7, 
                                    kernel_size=(2, k_size), padding='same',   
                                    ), power_iterations=pwr_iter)(z)
  return Model(z, x)
  
f_model = foo_model(5, 128, 1)
```
Three frames down, it gave the following error:
```
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/wrappers.py in __init__(self, layer, **kwargs)
     48 
     49   def __init__(self, layer, **kwargs):
---> 50     assert isinstance(layer, Layer)
     51     self.layer = layer
     52     super(Wrapper, self).__init__(**kwargs)

AssertionError: 
```
My conclusion is that it's not recognizing a valid Keras layer. I hope this is okay and thanks again

**Comment by bhack** [comment]
I cannot run your code:
```python
from tensorflow.keras.layers import Conv2D, Input
from tensorflow_addons.layers import SpectralNormalization

def foo_model( k_size, latent_dim, pwr_iter):
  z = Input(shape=(latent_dim,))
  x = SpectralNormalization(Conv2D(2**7, 
                                    kernel_size=(2, k_size), padding='same',   
                                    ), power_iterations=pwr_iter)(z)
  return Model(z, x)
  
f_model = foo_model(5, 128, 1)

```   ValueError: Input 0 of layer conv2d_2 is incompatible with the layer: : expected min_ndim=4, found ndim=2. Full shape received: (None, 128)```

Can you share a valid example to reproduce your issue?

**Comment by arsinnius** [comment]
Hello bhack,

Thanks for your help. You didn't run my code. You ran the tensorflow version. My code is Keras-based. When I run the tensorflow version, I get the same error you did. When I run the Keras version, I get the ```AssertionError```. If you run the code exactly as I wrote it, you will reproduce the ```AssertionError```. 

More broadly, I wonder if the fact that the two versions produce different errors is telling us something about the underlying issue. Thanks again.

**Comment by bhack** [comment]
The old Keras is not support anymore. You need to use `tf.keras` in general and also for tensorflow addons compatibility.

**Comment by arsinnius** [comment]
bhack, when I converted the Keras code to tensorflow, the error disappeared. That also explains why it happened so suddenly. Thank you for all your help.

**Comment by arsinnius** [comment]
bhack, when I converted the Keras code to tensorflow, the error disappeared. That also explains why it happened so suddenly. Thank you for all your help.
