### ISSUE TITLE
BERT model not using GPU for training

### ISSUE THREAD

**Issue by kartik727** [tensorflow/tensorflow#49767]
I am following [this tutorial](https://www.tensorflow.org/text/tutorials/classify_text_with_bert) to use BERT for an NLP competition on Kaggle. 

I have created the model based on the tutorial but using the Kaggle data for training. But when I try to train with GPU enabled it still uses CPU only. I tried running my code and Colab with GPU enabled and there also the GPU is not being used, so it's not a Kaggle specific issue.

So far I have tried the small models [2/128](https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2) and [8/512](https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-8_H-512_A-8) and both are using CPU only while the GPU sits on 0% utilization and 2MB memory use.

The TF version is 2.5.0 which gives this warning when importing the libraries:

```
/opt/conda/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:67: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.3.0 and strictly below 2.5.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.5.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
```
But downgrading TF gives other errors that I am not able to resolve so I haven't tried running on older versions yet.
Any help is appreciated, thanks in advance.

**Comment by tilakrayal** [comment]
@kartik727 ,

I am to able to execute the code in v2.5 with GPU enabled and haven't faced any issues.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f719fa27121c3aaf83210f38221e16ca/49767.ipynb).

Could you please create a virtual environment and test your code again. It helps. Thanks!
