### ISSUE TITLE
saved model predict function call leads to OOM

### ISSUE THREAD

**Issue by rajatsaxena** [tensorflow/tensorflow#49806]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.4 64-bit
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.0, cuDNN 8.0.4.30
- GPU model and memory: NVIDIA GeForce GTX 1660 Ti (6 GB)

**Describe the current behavior**
I am trying to load a saved model (h5 file=3.8MB) using the setup described above and then use the model.predict on a numpy array of size `(45000, 32, 32, 3)` and `float32` datatype and I get a OOM memory error. 

I have set the memory growth option:
for gpu in tf.config.experimental.list_physical_devices('GPU'):
    tf.config.experimental.set_memory_growth(gpu, True)

**Describe the expected behavior**
while training the same model with dataset does not cause an error, the predict function. So, I am not sure what is happening. Th

**Standalone code to reproduce the issue**
https://github.com/rajatsaxena/test/blob/main/Similarity-CIFAR10-car.ipynb

**Comment by tilakrayal** [comment]
@rajatsaxena ,

Please take a look at this issues with similar error log.It helps.[link1](https://stackoverflow.com/questions/50760543/error-oom-when-allocating-tensor-with-shape/50764934),[link2](https://github.com/tensorflow/tensorflow/issues/16768),[link3](https://github.com/Borda/keras-yolo3/issues/7).

Thanks!

**Comment by rajatsaxena** [comment]
reducing the batch size helps, but the dataset isn't that big for both a 6gb and 12gb GPU to crash. I had run the same script on these exact same GPUs with Cuda10 and TF2.2 without any problem

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in TF [v2.4](https://colab.research.google.com/gist/tilakrayal/fa1959ee9212cd1a4510a4afb8d2d0f9/49806-2-4.ipynb),[v2.5](https://colab.research.google.com/gist/tilakrayal/3ba7475c03cd15a6a539062601e88508/49806.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/597e3e3396ae966d5a6361418e3f67ab/49806-nightly.ipynb).Please find the gist.

**Comment by Saduf2019** [comment]
@rajatsaxena 
 For GPU, try limiting GPU memory growth as per [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if it helps.

**Comment by rajatsaxena** [comment]
Alright, I will give it a shot

**Comment by rajatsaxena** [comment]
It did not help. Is there a specific location in the above script where I should add it?

**Comment by Saduf2019** [comment]
@rajatsaxena 
Add it before the model training.
