### ISSUE TITLE
FastGFile ResourceExhaustedError

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorflow#4981]
In https://github.com/tensorflow/models/commit/2390974a03a62b1388a004173477418db267074a @cshallue changed some `tf.gfile.FastGFile()` calls to `open()` because two RedHat users reported in #4685 that it causes ResourceExhaustedError even though resources don't appear to be exhausted.

We've also had the same issue reported in tensorflow/models#531, tensorflow/models#489, and tensorflow/models#480 but we're still waiting to learn if they're using RedHat.

Assigning to @rohan100jain who has done work on this code in the past.

**Comment by rohan100jain** [comment]
Yeah there was a memory leak by which file handles weren't being closed. Should have been fixed with https://github.com/tensorflow/tensorflow/commit/0f605abad3b30594416dc627860102e3382d6dea#diff-8dc0e318495c91370f8807ef81b589e0

Let me know if this is still an issue

**Comment by civilmanxx** [comment]
I meet the same issue, but in a different file 

**https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/imagenet/classify_image.py#L141**

This example only predict 1 image. if we change this example by using for loop to predict a large number images, it report the same **ResourceExhaustedError** error

**Comment by jart** [comment]
@civilmanxx are you building TensorFlow from source with Bazel at HEAD?

**Comment by civilmanxx** [comment]
yes, but my local code is not the latest version, which does not include a C++ fix (3 days ago? ) for this issue. Now I use **open()** instead of **read()** to avoid this issue.

If I get the lastest code, rebuild at local and use read() will be no issue anymore, is that right?

**Comment by jart** [comment]
As far as we know, the issue goes away if you sync to HEAD and build.
