### ISSUE TITLE
What is the purpose of autoshardpolicy when it actually gets the same outcome when it is turned off?

### ISSUE THREAD

**Issue by laplacericky** [tensorflow/tensorflow#49828]
## Description of issue (what needs changing):
the docs said when you set `options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF` , 
each worker will process all the data.
However, in my experimentation, tf.data.experimental.AutoShardPolicy.OFF gets the same results(in terms of how much data a worker will process) as tf.data.experimental.AutoShardPolicy.DATA
So what is purpose of autoshardpolicy? or do I have any misunderstanding here?

codes:
```
import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()
print(f'using distribution strategy\nnumber of gpus:{strategy.num_replicas_in_sync}')
tf2_dataset=tf.data.Dataset.from_tensor_slices(range(10))
tf2_dataset=tf2_dataset.shuffle(10)
tf2_dataset=tf2_dataset.batch(3)
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
tf2_dataset=tf2_dataset.with_options(options)
dt=strategy.experimental_distribute_dataset(tf2_dataset)
for i,j in enumerate(dt):
    print(f'batch {i}:')
    print(j)
```
number of gpus:2
batch 0:
PerReplica:{
  0: tf.Tensor([0 7], shape=(2,), dtype=int32),
  1: tf.Tensor([1], shape=(1,), dtype=int32)
}
batch 1:
PerReplica:{
  0: tf.Tensor([3 9], shape=(2,), dtype=int32),
  1: tf.Tensor([6], shape=(1,), dtype=int32)
}
batch 2:
PerReplica:{
  0: tf.Tensor([5 2], shape=(2,), dtype=int32),
  1: tf.Tensor([8], shape=(1,), dtype=int32)
}
batch 3:
PerReplica:{
  0: tf.Tensor([4], shape=(1,), dtype=int32),
  1: tf.Tensor([], shape=(0,), dtype=int32)
}
```
import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()
print(f'using distribution strategy\nnumber of gpus:{strategy.num_replicas_in_sync}')
tf2_dataset=tf.data.Dataset.from_tensor_slices(range(10))
tf2_dataset=tf2_dataset.shuffle(10)
tf2_dataset=tf2_dataset.batch(3)
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
tf2_dataset=tf2_dataset.with_options(options)
dt=strategy.experimental_distribute_dataset(tf2_dataset)
for i,j in enumerate(dt):
    print(f'batch {i}:')
    print(j)
```
number of gpus:2
batch 0:
PerReplica:{
  0: tf.Tensor([6 1], shape=(2,), dtype=int32),
  1: tf.Tensor([2], shape=(1,), dtype=int32)
}
batch 1:
PerReplica:{
  0: tf.Tensor([9 4], shape=(2,), dtype=int32),
  1: tf.Tensor([8], shape=(1,), dtype=int32)
}
batch 2:
PerReplica:{
  0: tf.Tensor([3 0], shape=(2,), dtype=int32),
  1: tf.Tensor([7], shape=(1,), dtype=int32)
}
batch 3:
PerReplica:{
  0: tf.Tensor([5], shape=(1,), dtype=int32),
  1: tf.Tensor([], shape=(0,), dtype=int32)
}

**Comment by UsharaniPagadala** [comment]
@jvishnuvardhan 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/0b7ea8dac63951bba7e4fb607a6753de/untitled15.ipynb).Thanks

**Comment by nikitamaia** [comment]
Hi @laplacericky, autoshardpolicy only applies when there are multiple workers. If you're using `MirroredStrategy`, there is only one worker, so there is no autosharding and the autosharding policy you set just registers as no-op.
