### ISSUE TITLE
sched_getaffinity fails on systems with more than 1024 cores

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#49833]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9

**Describe the current behavior**

On doing `import tensorflow` a warning is shown 2 times:

```
sched_getaffinity: Invalid argument
can't determine number of CPU cores: assuming 4
```

**Describe the expected behavior**

TF works correctly on large systems

**Other info / logs**

The reason is, that the default struct for the CPU set contains only space for 1024 cores, so it will fail with EINVAL on systems with more cores, even when they are inactive.
The solution is more or less simple, by using the macros of glibc to allocate a larger struct. See e.g. the CPython os Module implementation.

**Comment by rmothukuru** [comment]
@Flamefire,
Can you please elaborate about your issue so that everyone could understand what the issue exactly is? Thanks!

**Comment by Flamefire** [comment]
Sure:
The call at https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/platform/default/port.cc#L75 only works for systems with at most 1024 cores
This is due to the usage of the default `cpu_set_t` at https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/platform/default/port.cc#L74 which has only enough space for 1024 cores.

Hence: When using TF on a system with more than 1024 cores the call to `sched_getaffinity` will fail and TF will fallback to using only 4 cores as indicated by the warning.

The solution is to use the macros `CPU_ALLOC_SIZE` and `CPU_ALLOC` provided by glibc to dynamically increase the size of the struct passed to `sched_getaffinity` until there is enough space for all CPUs. See e.g. https://github.com/python/cpython/blob/0fa282c55f1a45765340cb24ed65c90ffe2aa405/Modules/posixmodule.c#L7129

**Comment by Flamefire** [comment]
This issue is not stale!

**Comment by Flamefire** [comment]
This issue is not stale!

**Comment by Flamefire** [comment]
This issue is not stale!

**Comment by rmothukuru** [comment]
@Flamefire,
Sorry for the inconvenience caused by the Stale Bot. It doesn't bother you anymore. Thanks!

**Comment by Flamefire** [comment]
@Saduf2019 as the problematic code linked at https://github.com/tensorflow/tensorflow/issues/49833#issuecomment-850355351 is still current, yes the issue still persists

**Comment by Flamefire** [comment]
I opened a PR with an implementation based on CPythons `os.sched_getaffinity` and used as a patch for building TF with EasyBuild for a while now: #56633
