### ISSUE TITLE
Error while trying to run train.py on Experiencor's yolov3 with keras project

### ISSUE THREAD

**Issue by noorraghib12** [tensorflow/tensorflow#49831]
The git: 
https://github.com/experiencor/keras-yolo3

The execution:
[full_run.txt](https://github.com/tensorflow/tensorflow/files/6553076/full_run.txt)

The error: 
[error.txt](https://github.com/tensorflow/tensorflow/files/6553063/error.txt)

**Comment by tilakrayal** [comment]
@noorraghib12 ,

Can you please provide the Tensorflow version you are using and also please take a look at this issues with similar error log.
[Link1](https://github.com/tensorflow/tensorflow/issues/27120),[Link2](https://github.com/tensorflow/tensorflow/issues/42183),[Link3](https://stackoverflow.com/questions/58352326/running-the-tensorflow-2-0-code-gives-valueerror-tf-function-decorated-functio).

Thanks!
