### ISSUE TITLE
MLIR-based TFLite converter - 16bit fake quantization

### ISSUE THREAD

**Issue by reuvenperetz** [tensorflow/tensorflow#49832]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5
- TensorFlow installation (pip package or built from source): 2.4.0
- TensorFlow library (version, if pip package or github SHA, if built from source): pip package

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
https://colab.research.google.com/drive/1Adz4A66PjnsvPigUi3cRL21C2aEe_dMI?usp=sharing

Error during tflite conversion:
Failed to convert element type '!quant.uniform<u16:f32, 6.1036087586785687E-5>': 'isSigned' can only be set for 8-bits integer type

Hi,
The model conversion works fine when using TOCO converter (which is deprecated) but fails when using MLIR-based TFLite converter.
It seems that fake-quant can be converted only when it quantizes using 8 bits...
Any ideas?

Thanks!

**Comment by reuvenperetz** [comment]
Hi, any news?

**Comment by mohantym** [comment]
Hi @reuvenperetz ! This issue is not replicating in TF [2.8](https://colab.sandbox.google.com/gist/mohantym/87e87f40265c25dc06c498b07149663c/copy-of-16bit-fake-quant-mlir-based-tflite-conversion.ipynb#scrollTo=kOyTcnb_0L3w) version . Can we move this to closed status now?

**Comment by reuvenperetz** [comment]
Thanks!
I see I still have to use the MLIR converter flag of optimizations:
converter.optimizations = [tf.lite.Optimize.DEFAULT]

Otherwise, I get the same error.... is is possible to convert 16bits fake-quant layer without using the converter optimizations?

Thanks again.

**Comment by fig666** [comment]
converter optimisation isn't faulty by comparison. its the lack of proper devices and components that need adjustments and updating to better produce fast and reliable results without lagging or booting data.

**Comment by fig666** [comment]
Currently in the process of being in the conversion of getting help with better components and malware protection software for the issues currently being produced towards my keyboard system
