### ISSUE TITLE
TFLite on GPU does not support quantised models by default

### ISSUE THREAD

**Issue by Cy-r0** [tensorflow/tensorflow#49835]
## URL(s) with the issue:

https://www.tensorflow.org/lite/performance/gpu_advanced

## Description of issue (what needs changing):

The documentation reads: "*Android APIs support quantized models by default. To disable, do the following:*"

However, when I try running my int8 quantised model on mobile GPU, it silently defaults to running on CPU. I'm importing the nightly version as below in build.gradle:
```
dependencies {
    implementation "androidx.appcompat:appcompat:1.1.0"

    implementation "org.tensorflow:tensorflow-lite:0.0.0-nightly"
    implementation "org.tensorflow:tensorflow-lite-support:0.0.0-nightly"
    implementation "org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly"
}
```

And when I do the below in my Android activity:
```
gpuOptions.setQuantizedModelsAllowed(true);
```
it successfully runs on GPU (confirmed by looking at GPU usage, also it runs much faster on GPU). 

This suggests that the Android APIs actually DON'T support quantised models on GPU by default, and the flag needs to be set manually.

**Comment by multiverse-tf** [comment]
> ## URL(s) with the issue:
> https://www.tensorflow.org/lite/performance/gpu_advanced
> 
> ## Description of issue (what needs changing):
> The documentation reads: "_Android APIs support quantized models by default. To disable, do the following:_"
> 
> However, when I try running my int8 quantised model on mobile GPU, it silently defaults to running on CPU. I'm importing the nightly version as below in build.gradle:
> 
> ```
> dependencies {
>     implementation "androidx.appcompat:appcompat:1.1.0"
> 
>     implementation "org.tensorflow:tensorflow-lite:0.0.0-nightly"
>     implementation "org.tensorflow:tensorflow-lite-support:0.0.0-nightly"
>     implementation "org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly"
> }
> ```
> 
> And when I do the below in my Android activity:
> 
> ```
> gpuOptions.setQuantizedModelsAllowed(true);
> ```
> 
> it successfully runs on GPU (confirmed by looking at GPU usage, also it runs much faster on GPU).
> 
> This suggests that the Android APIs actually DON'T support quantised models on GPU by default, and the flag needs to be set manually.

According to [the gpu delegate Java implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/java/src/main/java/org/tensorflow/lite/gpu/GpuDelegate.java#L90), the support of quantized model is enabled by default in TfLite library.

As the tensorflow-lite-support lib is also used, it looks like you are using the tflite via the TfLite task library? If yes, could you detail how it's used? Anyway, to help us debugging, could you share a minimal code piece that we could use to reproduce the issue? Thx!

**Comment by lu-wang-g** [comment]
It seems only Support library is used (to use Task library, it requires the dependency to Task library specifically). Yeah, the code snippet will help us understand what is going here.

**Comment by teijeong** [comment]
As a side note, running quantized model on GPU won't have performance benefit compared to running float16 model on GPU, as the weights are dequantized and the inference is being done in float16 (or float32). It also has extra quantize-dequantize between each layers, so the performance overall might even be slower than that of float16 model.

**Comment by Cy-r0** [comment]
Apologies for the late reply, I've been called to do other work.

A couple of notes:
- Indeed I was not using the Task Library. I loaded a custom model trained by myself.
- I'm aware that running quantised models on GPU will just dequantise them. That's not a problem at the moment, we are not optimising for accuracy (yet) and using a single model for GPU and NPU is more convenient.

Below is a snippet from my main activity:
```java
  private class RunBenchmarkTask extends AsyncTask<Void, Integer, Void> {
    private long totalTime = 0;
    private long maxTime = 0;
    private long minTime = 999999;
    private int numRuns = 100;
    private int numWarmupRuns = 5;

    protected void onPreExecute() {
      // Hide settings and button
      View l = findViewById(R.id.settingsLayout);
      l.setVisibility(View.GONE);

      settingsTextView.setText(String.format(
              "Model: %s \nDevice: %s \nOutput res: %d x %d \nWarmup runs: %d \nTimed runs: %d",
              modelPath, device, getOutputSize(inputHeight), getOutputSize(inputWidth), numWarmupRuns, numRuns));
      resultsTextView.setText("Benchmarking...");
    }

    protected Void doInBackground(Void... params) {

      // Load tflite model
      try {
        tfliteModel = FileUtil.loadMappedFile(MainActivity.this, modelPath);
        Log.i(TAG, String.format("Model loaded from %s", modelPath));
      } catch (IOException e) {
        Log.e(TAG, "Error loading model", e);
        finish();
      }

      // Initialise tflite
      tfliteOptions = new Interpreter.Options();
      try {
        switch (device) {
          case CPU:
            break;
          case GPU:
            GpuDelegate.Options gpuOptions = new GpuDelegate.Options();
            // TFLite on GPU documentation says that the below flag is True by default
            // but quantised models won't run on GPU by default
            // TODO github issue
            gpuOptions.setQuantizedModelsAllowed(true);
            gpuDelegate = new GpuDelegate(gpuOptions);
            tfliteOptions.addDelegate(gpuDelegate);
            break;
          case NPU:
            nnApiDelegate = new NnApiDelegate();
            tfliteOptions.addDelegate(nnApiDelegate);
            break;
        }
        tflite = new Interpreter(tfliteModel, tfliteOptions);

      } catch (Exception e) {
        Log.e(TAG, "Error initialising tflite interpreter", e);
        finish();
      }

      // Tell tflite to use this input size
      int[] inputShape = {batchSize, inputHeight, inputWidth, 3};
      DataType imageDataType = tflite.getInputTensor(0).dataType();
      Log.i(TAG, String.format("Input datatype: %s", imageDataType));
      inputImageBuffer = TensorBuffer.createFixedSize(inputShape, imageDataType);
      tflite.resizeInput(0, inputShape);

      // Initialise output
      int[] outputShape = {batchSize, getOutputSize(inputHeight), getOutputSize(inputWidth), 3};
      Log.d(TAG, String.format("Input shape: %s", Arrays.toString(inputShape)));
      Log.d(TAG, String.format("Calculated output shape: %s", Arrays.toString(outputShape)));
      outputTensorBuffer = TensorBuffer.createFixedSize(outputShape, imageDataType);

      // Do some warmup runs
      for (int i=0; i < numWarmupRuns; i++) {

        rerollInput(inputImageBuffer);
        tflite.run(inputImageBuffer.getBuffer(), outputTensorBuffer.getBuffer().rewind());
      }

      // Do some timed runs
      for (int i=0; i < numRuns; i++) {
        // Regenerate input tensor with different random values
        rerollInput(inputImageBuffer);

        // Start counting
        long startTime = SystemClock.uptimeMillis();

        // Run inference on the decoder
        tflite.run(inputImageBuffer.getBuffer(), outputTensorBuffer.getBuffer().rewind());

        // Stop counting
        lastProcessingTimeMs = (int) (SystemClock.uptimeMillis() - startTime);
        Log.i(TAG, String.format("Decoder inference time = %d ms", lastProcessingTimeMs));

        totalTime += lastProcessingTimeMs;
        maxTime = lastProcessingTimeMs > maxTime ? lastProcessingTimeMs : maxTime;
        minTime = lastProcessingTimeMs < minTime ? lastProcessingTimeMs : minTime;
        publishProgress(i, numRuns, lastProcessingTimeMs);
      }

      tflite.close();
      return null;
    }

    protected void onProgressUpdate(Integer... progressValues) {
      // progressValues contains current index and total number of iterations
      resultsTextView.setText(String.format(
              "Benchmarking %d/%d. Time (ms): %d",
              progressValues[0] + 1, progressValues[1], progressValues[2]));
    }

    protected void onPostExecute(Void result) {
      float avgTime = (float) totalTime / numRuns;
      Log.i(TAG, String.format(
              "Inference time (ms): mean = %f, max = %d, min = %d",
              avgTime, maxTime, minTime));

      // Show benchmark results on UI
      resultsTextView.setText(String.format(
              "Inference time (ms): \nmean = %.3f, max = %d, min = %d",
              avgTime, maxTime, minTime));

      // Unhide settings
      View l = findViewById(R.id.settingsLayout);
      l.setVisibility(View.VISIBLE);

      // Delete stuff
      tflite = null;
    }
  }
```

Please let me know if there's something I'm missing, or if you need more information.

**Comment by lu-wang-g** [comment]
From the [source code](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/delegates/gpu/java/src/main/java/org/tensorflow/lite/gpu/GpuDelegate.java#L90), quantized models should be enabled as default. And @Cy-r0 is using the nightly build. 

Looped in @srjoglekar246 to take a look.

**Comment by srjoglekar246** [comment]
We have [GpuDelegateTest](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/java/src/test/java/org/tensorflow/lite/gpu/GpuDelegateTest.java#L73) that unit-tests this behavior in our internal tooling, so I am surprised that you don't see the GPU delegate being enabled by default :-/. (Note that the test looks at the ops in the TFLite Interpreter to see if the whole graph has been delegated to GPU). I just re-ran these tests, and they pass.

To followup, what do you see in ADB logs from the TFLite runtime when you don't (vs do) set the flag to True explicitly? 
Also, can you try logging the value of `options.quantizedModelsAllowed` through adb (before you explicitly set it to True) as well?

**Comment by pjpratik** [comment]
Hi @Cy-r0 

I was checking if the issue still exists.

The code for GPU delegate test says that default behavior allows quantized models as well.
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/java/src/test/java/org/tensorflow/lite/gpu/GpuDelegateTest.java#L79

As @srjoglekar246 asks, could you please provide the ADB logs to better understand the issue?

Thanks.

**Comment by Cy-r0** [comment]
Apologies, I've moved on from this job. I'll check if I still have the code and if the issue is still present, but I can make no guarantees I'll find it.

**Comment by pjpratik** [comment]
Hi @Cy-r0 

Can we consider the issue is resolved?

Thanks.

**Comment by Cy-r0** [comment]
Yes, thank you.

**Comment by pjpratik** [comment]
Thanks for the confirmation.
