### ISSUE TITLE
tf.image.resize behavior

### ISSUE THREAD

**Issue by slala2121** [tensorflow/tensorflow#49847]
not working code
`
@tf.function
def read_dicom(sample_dicom_path):

	image_file_bytes=tf.io.read_file(sample_dicom_path)
	image=tfio.image.decode_dicom_image(image_file_bytes, dtype=tf.float32)
	
	image = tf.squeeze(image)
	image = tf.stack([image, image, image], axis=-1)

	size=tf.cast(tf.constant([224,224]), tf.int32)
	image = tf.image.resize(image, size)

	return image`

image=read_dicom('sample.dcm')

Running this the code yields the following error message:ValueError: 
![Screen Shot 2021-05-27 at 5 50 45 PM](https://user-images.githubusercontent.com/58089750/119913957-10f9f580-bf14-11eb-994d-570386f63fc3.png)

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here,Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/f32817ccef2db11884f4b65881a1725b/untitled74.ipynb#scrollTo=jDhOr1KwjVNG).  Thanks

**Comment by Saduf2019** [comment]
@slala2121 
Please try with out @tf function, we tried the same and see error ""kittycat; No such file or directory [Op:ReadFile]" which clearly shows there is an issue with the path you have provided, please fix that.
