### ISSUE TITLE
Update GPU support page to reflect correct libraries required for TF 2.5.0

### ISSUE THREAD

**Issue by benyeoh** [tensorflow/tensorflow#49855]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu

## Description of issue (what needs changing):

The documentation has not been updated to state the correct versions of cuda, cudnn and nvinfer that the current stable Tensorflow version (2.5.0) requires.

For example in the Ubuntu 18.04 configuration, instead of:

```bash
# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-11-0 \
    libcudnn8=8.0.4.30-1+cuda11.0  \
    libcudnn8-dev=8.0.4.30-1+cuda11.0
```

It should be something like:

```bash
# Install development and runtime libraries (~4GB)
sudo apt-get install --no-install-recommends \
    cuda-11-2 \
    libcudnn8=8.1.0.77-1-1+cuda11.2  \
    libcudnn8-dev=8.1.0.77-1+cuda11.2
```

It's also particularly unclear which version of the nvinfer libraries are required to enable TF-TRT optimizations since it's also not stated in the [Build from source](https://www.tensorflow.org/install/source) page and it's also not obvious how to check that TRT is enabled.

**Comment by ymodak** [comment]
Thanks for your issue. This is tracked with https://github.com/tensorflow/tensorflow/issues/49175
