### ISSUE TITLE
Why is profiler dir deleted for non-chief nodes in MWMS in keras?

### ISSUE THREAD

**Issue by burgerkingeater** [tensorflow/tensorflow#49852]
Hi,
Based on the keras tensorboard callback: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2472
The profiler dir of non-chief node is set to a temp dir when MWMS is being used, which will be deleted later on:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2227
https://github.com/tensorflow/tensorflow/blob/da15b34d11432b789527e4a3c3ad4eac5193a5f0/tensorflow/python/keras/callbacks.py#L2256

I understand checkpoints for non-chief nodes should be cleaned up, but why profiling result? 
Happy to contribute a PR if this is a bug. 

CC @jbaiocchi  @omalleyt12

**Comment by rmothukuru** [comment]
@burgerkingeater,
Neither [**`_log_write_dir`**](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2227) nor [**`log_dir`**](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L2257) is a temporary directory but they are the actual directories in which **`Tensorboard Events`** are stored. 

Please let me know if I have understood your question correctly. 

Thanks!

**Comment by burgerkingeater** [comment]
@rmothukuru thanks! But _log_write_dir is a temp dir for MWMS's non-chief node: https://github.com/tensorflow/tensorflow/blob/cda12732ca4610434937259b881965165564193d/tensorflow/python/keras/distribute/distributed_file_utils.py#L96

**Comment by rchao** [comment]
@burgerkingeater thanks for the question. With MWMS the workers are expected to have the same metrics with all-reduces. Is there a reason why the logging on chief alone isn't sufficient?

**Comment by burgerkingeater** [comment]
@rchao thanks for the reply. Trace view in the profiler is not necessarily to be the same across the nodes, right? E.g, two nodes are running with different hardware configuration

**Comment by rchao** [comment]
@burgerkingeater I see. Would you mind giving a try to not remove the profiling on non-chiefs (and re-build TensorFlow), and see if it matches what you're expecting?

**Comment by yisitu** [comment]
CC myself @yisitu

**Comment by burgerkingeater** [comment]
@rchao yes, and I submitted a PR to fix this issue: https://github.com/tensorflow/tensorflow/pull/50068/, would you mind taking a look?

**Comment by burgerkingeater** [comment]
@rchao also I wonder why not just not writing summary if it's non-chief? Why is the overhead of creating the temp dir, writing summary to temp dir, and deleting the temp dir necessary?

**Comment by rchao** [comment]
Thanks @burgerkingeater! With MWMS, any API calls can trigger all-reduces across the workers and if we only perform that on chief, there is a chance that things will just hang (because it keeps waiting to all-reduce with other workers). Therefore in general all workers (including chief) should perform the same actions, but if it involves file writing to a centralized place, we'd need temporary locations for non-chief for later deletion.

**Comment by rthadur** [comment]
Related PR has been merged , closing this issue. Thank you
