### ISSUE TITLE
polymorphism dtype tensor for custom op Attr?

### ISSUE THREAD

**Issue by gyin-ai** [tensorflow/tensorflow#49864]
Can I ask how we can add polymorphism dtype tensor for custom op Attr? For example, how can we allow the below `attr` dtype to be DT_FLOAT or DT_HALF?

example:
```
REGISTER_OP("DoStuff")
    .Attr("attr: tensor = { dtype: DT_FLOAT }")
    .Input("in: float")
    .Output("out: float");
```

```
REGISTER_OP("DoStuff")
    .Attr("attr: tensor = { dtype: DT_HALF }")
    .Input("in: float")
    .Output("out: float");
```

**Comment by ymodak** [comment]
This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
