### ISSUE TITLE
Wrong libcudart.so loaded with TF 2.5.0

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [tensorflow/tensorflow#49862]
**System information**
- OS Platform and Distribution : ubuntu 20.04
- TensorFlow installed from : binary via pip3
- TensorFlow version: 2.5.0
- Python version: 3.8.5
- Installed using : pip
- CUDA/cuDNN version: NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2  
- GPU model and memory: GeForce GTX 1070

After installing nvidia drivers, cuda and cudnn with matching versions from:
- https://www.tensorflow.org/install/source#gpu
- https://docs.nvidia.com/deploy/cuda-compatibility/index.html
- https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

and installing tensorflow with pip3 I get this message:
```
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-05-28 16:34:56.376524**: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory**
2021-05-28 16:34:56.376553: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> tf.__version__
'2.5.0'
```
Why is tensorflow 2.5.0 loading cuda 11.0 but the tensorflow compatibility page says that it must work with cuda 11.2 ?

nvcc output:
```
» /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```
nvidia-smi output:
Fri May 28 16:38:20 2021       
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   32C    P8     9W / 200W |    138MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by benyeoh** [comment]
`libcudart.so.11.0` should be the correct version of the cuda runtime library that is installed along with rest of the cuda 11.2 package. If TF is unable to find that binary, then I would double check that your runtime linker bindings have been setup correctly with `ldconfig -p | grep libcudart`. You should get an output like:

```bash
	libcudart.so.11.0 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.11.0
	libcudart.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
```

If not, I'd verify the cuda 11.2 runtime package was properly installed, and that `libcudart.so.11.0` exists somewhere in the install path, and finally that the ldconfig cache is properly setup in `/etc/ld.so.conf.d/` to point to that path.

Btw, it's a bit confusing but the `CUDA Version` reported by `nvidia-smi` is the **cuda driver** version that probably came with your GPU drivers. The **cuda runtime** libraries that are installed when you `apt-get install cuda-11-2` for example is a completely different thing. IE, it's possible to have cuda driver version 11.2 and have multiple cuda 10.1/10.2/11.0/11.3 runtimes installed.

**Comment by Guillaumebeuzeboc** [comment]
Nothing was listed with `ldconfig -p | grep libcudart`.
So I checked and found the lib in `/usr/local/cuda-11.2/targets/x86_64-linux/lib`
I added this path to `LD_LIBRARY_PATH`
Then it was loading but reporting a problem: `MemoryError in TensorFlow; and “successful NUMA node read from SysFS had negative value (-1)” `
So I `echo 0 | sudo tee -a /sys/bus/pci/devices/MyGPU/numa_node` and now eveything seem to work properly.
(Might be useful for someone)

Thank you for your help!
