### ISSUE TITLE
PiecewiseConstantDecay doesn't work with Wrapping Optimizer on GPUs

### ISSUE THREAD

**Issue by kaixih** [tensorflow/tensorflow#49889]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5/2.6
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.2
- GPU model and memory: 8.2

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When using the PiecewiseConstantDecay for an optimizer and wrapping optimizer, like:
```python
lr_fn = PiecewiseConstantDecay()
opt = SGD(lr_fn)
opt = WrapOpt(opt)
```
We will hit the error of
```
InvalidArgumentError: Cannot assign a device for operation sequential_1/dense_1/Tensordot/ReadVariableOp: Could not satisfy explicit device specification '' because the node {{colocation_node sequential_1/dense_1/Tensordot/ReadVariableOp}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices 
```
Note, this error seems to be hit only when PiecewiseConstantDecay schedule is used on GPUs.

**Describe the expected behavior**

We shouldn't see such error when using PiecewiseConstantDecay on GPUs.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Below is the colab link and please repro it with ***Runtime=GPU***.
https://colab.research.google.com/drive/1QPx4IqQNVpSR-ALfPYbjJjRUffyHo06G?usp=sharing

```python
import tensorflow as tf
from tensorflow.keras import layers, optimizers, models
print(tf.__version__)
class OptimizerWrapper(optimizers.Optimizer):
  def __init__(self, optimizer, name=None, **kwargs):
    super(OptimizerWrapper, self).__init__(name, **kwargs)
    self._optimizer = optimizer

  def _create_slots(self, var_list):
    self._optimizer._create_slots(var_list)

  def _resource_apply_dense(self, grad, var):
    return self._optimizer._resource_apply_dense(grad, var)

  def _resource_apply_sparse(self, grad, var):
    return self._optimizer._resource_apply_sparse(grad, var)

  def get_config(self):
    return self._optimizer.get_config()


model = tf.keras.Sequential()
model.add(layers.Dense(8))
x = tf.constant(12., shape=(5, 1, 2, 4))
boundaries = [100000, 110000]
values = [1.0, 0.5, 0.1]
learning_rate_fn = optimizers.schedules.PiecewiseConstantDecay(
    boundaries, values)
#learning_rate_fn = optimizers.schedules.ExponentialDecay(
#    0.1, decay_steps=100000, decay_rate=0.96, staircase=True)
#learning_rate_fn = optimizers.schedules.PolynomialDecay(
#    0.1, 10000, 0.01, power=0.5)
opt = optimizers.SGD(learning_rate=learning_rate_fn, momentum=1.0)
opt = OptimizerWrapper(opt)

@tf.function
def train_step(x):
  with tf.GradientTape(persistent=True) as tape:
    y = model(x)
    loss = tf.reduce_mean(y)

  grads = tape.gradient(loss, model.variables)
  opt.apply_gradients(zip(grads, model.variables))
  return loss

for i in range(3):
  loss = train_step(x)
  print("Loss:", loss)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-354cdd24a945> in <module>()
     45 
     46 for i in range(3):
---> 47   loss = train_step(x)
     48   print("Loss:", loss)
     49 

5 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: Cannot assign a device for operation sequential_1/dense_1/Tensordot/ReadVariableOp: Could not satisfy explicit device specification '' because the node {{colocation_node sequential_1/dense_1/Tensordot/ReadVariableOp}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
```

cc. @nluehr

**Comment by tilakrayal** [comment]
@kaixih ,

I was able to reproduce the issue in TF v2.4 and v2.5. In nightly i wasn't able to find the issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/4b1783af1b8cdd3e233575eea51411e6/49889.ipynb).

Thanks!

**Comment by kaixih** [comment]
@tilakrayal Thanks for trying this out.

Yes, it seems it is working on the colab with the nightly wheel. However, I can still see the error when I use the nightly-gpu docker on my machine. This is what I have tried:
(1) pull the tensorflow/tensorflow:nightly-gpu: I can see the version: 2.6.0-dev20210601 and still hit the error.
(2) pull the tensorflow/tensorflow:nightly: I can see the version: 2.6.0-dev20210601 and no error.

So, I have a feeling that the colab might not use the GPU env for the nightly wheel. Can you try it with docker images? Thanks.

**Comment by kaixih** [comment]
Some updates:
When using the nightly-gpu docker image (ie. the above (1) container), if I disable GPU, the error is gone:
```
CUDA_VISIBLE_DEVICES= python error_repro.py
```
So, I suspect the colab might not use the GPU for some cases even if the GPU runtime is selected. Please let me know your thoughts. Thanks.

**Comment by kaixih** [comment]
Hi @tilakrayal , I tweaked your gist code by adding this following code after printing the TF version.

```python
physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))
```
It confirms my findings that the 2.4 and 2.5 shows the GPU number is 1 but the nightly shows the GPU number is 0.

**Comment by rmothukuru** [comment]
@kaixih,
Your code could be run successfully with **`GPU Runtime`** by commenting the **`Wrapper for Optimizer`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/4e719f4b55293ce49aff36103a45a0f9/gh_49889.ipynb) of working code.

Is there any specific reason for using the **`Wrapper`** for the **`Optimizer`** instead of the **`Optimizer`** ?

**Comment by kaixih** [comment]
@rmothukuru Yes, I agree the original optimizer works fine. However, we are designing a wrapper optimizer to postprocess the variables after each updating and this design works fine with any other learning schedule or CPU env. Only the PiecewiseConstantSchedule + GPU will hit the error. We think our example is a legit use case and should be working.

Also, we found that when using the eager mode (by commenting out the `@tf.function`), this use case works fine. So, I believe it is a TF bug and the implementation of PiecewiseConstantSchedule might trigger some weird situation when using GPU + graph mode. What's your advise?

**Comment by kaixih** [comment]
Here are some more info that might help:
To mimic the PiecewiseConstantDecay, I created this
```python
class SimplePiecewiseConstantDecay(
    tf.keras.optimizers.schedules.LearningRateSchedule):
  def __init__(self, boundaries, values, name=None):
    super(SimplePiecewiseConstantDecay, self).__init__()
    if len(boundaries) != len(values) - 1:
      raise ValueError(
          "The length of boundaries should be 1 less than the length of values"
      )
    self.boundaries = boundaries
    self.values = values
    self.name = name

  def __call__(self, step):
    pred_fn_pairs = []
    pred_fn_pairs.append((step <= self.boundaries[0], lambda: self.values[0]))
    pred_fn_pairs.append((step > self.boundaries[-1], lambda: self.values[-1]))
    for low, high, v in zip(self.boundaries[:-1], self.boundaries[1:],
                            self.values[1:-1]):
      # Need to bind v here; can do this with lambda v=v: ...
      pred = (step > low) & (step <= high)
      pred_fn_pairs.append((pred, lambda v=v: v))

    # The default isn't needed here because our conditions are mutually
    # exclusive and exhaustive, but tf.case requires it.
    default = lambda: self.values[0]
    return tf.case(pred_fn_pairs, default, exclusive=True)

  def get_config(self):
    return {"boundaries": self.boundaries,
            "values": self.values,
            "name": self.name}
```
By using it instead of `optimizers.schedules.PiecewiseConstantDecay` in the original repro, we can still repro the error. From the log, I suspect the TF cannot correctly deal with the device assignment with the `tf.case` op in this use case.

**Comment by kaixih** [comment]
I just played with the `tf.case` vs `tf.cond` and it confirms only the `tf.case` will hit the error:
```python
  # This doesn't work!
  def __call__(self, step):
    pred_fn_pairs = []
    pred_fn_pairs.append((step <= self.boundaries[0], lambda: self.values[0]))
    pred_fn_pairs.append((step > self.boundaries[-1], lambda: self.values[-1]))
    default = lambda: self.values[0]
    return tf.case(pred_fn_pairs, default, exclusive=True)
```
```python
  # This works fine!
  def __call__(self, step):
    def case0():
      return self.values[0]
    def case1_2():
        return tf.cond(step > self.boundaries[-1], lambda: self.values[-1],
                       lambda: self.values[0])
    return tf.cond(step <= self.boundaries[0], case0, case1_2)
```
See the colab link https://colab.research.google.com/drive/1KUu7HSX4J7nNvYEaEDXCUZhGgxkoGiWe?usp=sharing.

**Comment by kaixih** [comment]
Any news @rmothukuru? Thanks.

**Comment by reedwm** [comment]
I'm not sure what's causing the issue, but delegating `apply_gradients` in `OptimizerWrapper` solves the issue:

```python
class OptimizerWrapper(optimizers.Optimizer):

  ...

  def apply_gradients(self,
                      grads_and_vars,
                      name=None,
                      experimental_aggregate_gradients=True):
    self._optimizer.apply_gradients(grads_and_vars, name,
                                    experimental_aggregate_gradients)
```

This is what `tf.keras.mixed_precision.LossScaleOptimizer` does, which is the only optimizer wrapper within Keras.

Still, this is a bad error message and this issue should be fixed. /CC @fchollet @tomerk, can either of you take a look or triage?

**Comment by kaixih** [comment]
Thanks @reedwm for this WAR. It works for this repro script. However, in our real case, it may be not easy for us to delegate the `apply_gradients()` in the wrapper. Roughly, what we are trying to do is that for some vars, we need to prune them before updating. And this logic can be implemented natually in `_resource_apply_dense(self, grad, var)` like:
```python
def _resource_apply_dense(self, grad, var):
  if var is elegible:
    self._optimizer._resource_apply_dense(...)
    new_var = prune(var)
    return var.assign(new_var)
  else:
    return self._optimizer._resource_apply_dense(...)
```
However, with the above delegating solution, it is not simple for us to insert the pruning in front of var updating. So, we are still looking forwards to more info on the root cause and solution of this issue.

**Comment by reedwm** [comment]
As a workaround, delegating `_prepare` in `OptimizerWrapper` and adding an `apply_state` argument to `_resource_apply_dense` fixes the issue:

```python
class OptimizerWrapper(optimizers.Optimizer):
  def __init__(self, optimizer, name=None, **kwargs):
    super(OptimizerWrapper, self).__init__(name, **kwargs)
    self._optimizer = optimizer

  def _prepare(self, var_list):
    return self._optimizer._prepare(var_list)

  def _create_slots(self, var_list):
    self._optimizer._create_slots(var_list)

  def _resource_apply_dense(self, grad, var, apply_state):
    return self._optimizer._resource_apply_dense(grad, var, apply_state)

  def _resource_apply_sparse(self, grad, var):
    return self._optimizer._resource_apply_sparse(grad, var)

  def get_config(self):
    return self._optimizer.get_config()
```

Still, this shouldn't be necessary. Will keep investigating.

**Comment by reedwm** [comment]
I found the root cause. The issue occurs if an optimizer subclass creates a `tf.string` tensor in `_resource_apply_dense`. The reason is due to [this colocation constraint](https://github.com/keras-team/keras/blob/06b04aeb745c90c5368be02928b08cc7fd592659/keras/optimizer_v2/optimizer_v2.py#L702) in Optimizer. This forces everything in `_resource_apply_dense` to be placed on the GPU if the variable is on the GPU (which is the case for practically every model run on the GPU). However, string tensors can only be placed on the CPU, so the error occurs if a string tensor is created under that colocation constraint, which includes the call to `_resource_apply_dense`.

As you noticed, an error occurs when you use a PiecewiseConstantDecay (or any `LearningRateSchedule` that calls `tf.case(..., exclusive=True)`) with certain custom optimizers (such as your OptimizerWrapper). This is because `tf.case` creates a string tensor, since it creates an Assert op which [takes in a string tensor](https://github.com/tensorflow/tensorflow/blob/53c3fc3e5a7cafc57e6644cbbbedea425a7b1db7/tensorflow/python/ops/control_flow_ops.py#L3112). A LearningRateSchedule is called from `_fallback_apply_state`, which is called from `_resource_apply_dense` in many optimizers if the `apply_state` argument is not passed through.

/CC @fchollet @rohan100jain what do you think the best solution is here? Perhaps we should have the concept of a "soft colocation constraint", which allows ops to be placed on the CPU if the colocation constraint cannot be satisfied? Or we can have Keras simply not use a colocation constraint, as [it is deprecated](https://www.tensorflow.org/api_docs/python/tf/compat/v1/colocate_with), and we could instead have grappler or some other optimization to move ops to the GPU if necessary to get optimal performance.

**Comment by reedwm** [comment]
Also /CC @yuefengz, as the issue occurs with `distribution.extended.colocate_vars_with`.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
