### ISSUE TITLE
List of Initializers are specified twice in the Classes Section of documentation

### ISSUE THREAD

**Issue by worldpeaceaspirer** [tensorflow/tensorflow#49894]
Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/initializers#classes

## Description of issue (what needs changing):
Every **`Initializer`** has been specified twice, (`Constant`, `GlorotUniform`,etc..) and (`constant`, `glorot_uniform`, etc..).

However, they, for example [GlorotUniform](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/GlorotUniform) and [glorot_uniform](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/GlorotUniform), point to the same link.

Is there any specific reason for this redundancy?

**Comment by ymodak** [comment]
They are intentionally retained, See comment
https://github.com/tensorflow/tensorflow/blob/d0e3ce5b4bc8bea4bbb9fe51635dd36104e4ad86/tensorflow/python/keras/initializers/__init__.py#L66

**Comment by UsharaniPagadala** [comment]
@worldpeaceaspirer 

Could you please check the above comment ,move this to closed status if it helps.Thanks

**Comment by worldpeaceaspirer** [comment]
> They are intentionally retained, See comment
> https://github.com/tensorflow/tensorflow/blob/d0e3ce5b4bc8bea4bbb9fe51635dd36104e4ad86/tensorflow/python/keras/initializers/__init__.py#L66

@ymodak,
I see that they are intentionally retained. Thank you.
