### ISSUE TITLE
TensorflowJS Issue : Looking for previous version of cusolver64_10

### ISSUE THREAD

**Issue by fireholster** [tensorflow/tensorflow#49891]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlowJS version: 3.6.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.3
- GPU model and memory: RTX 2060 MAXQ
**Describe the problem**
GPU build is looking for cusolver64_10 instead of latest cusolver64_11 version

**Comment by tilakrayal** [comment]
@fireholster ,

Issues related to TensorflowJS are tracked in tensorflow/tfjs repo.

**Comment by fireholster** [comment]
sure let me open it there

**Comment by tilakrayal** [comment]
@fireholster ,

Please feel free to move this issue to closed status, if new issue was submitted in tfjs repo  so that we can track the issue there. Thanks!

**Comment by fireholster** [comment]
moved it to tensorflow/tfjs reo
