### ISSUE TITLE
Means of GlorotNormal Initializer and HeNormal Initializer are not zero, respectively

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#49896]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version (use command below): 2.5
- Python version:
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior** : **`Mean`** of the **`Initial Weights`** using **`Glorot Normal Initializer`** is not **`zero`**. Same is the case with **`HeNormal Initializer`**.

**Describe the expected behavior**: As per the documentation of [Glorot Normal](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/GlorotNormal), and [HeNormal](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/HeNormal), **`mean`** of the **`Normal Distribution`** of the **`Initial Weights`** should be **`zero`**. 

> Draws samples from a truncated normal distribution centered on 0

**Standalone code to reproduce the issue** : [Colab Gist for Glorot Normal](https://colab.research.google.com/gist/rakeshmothukuru1/a44f7aaa1fd261247a1388c2e2f5a167/glorot_initializer_bug.ipynb)

[Colab Gist for HeNormal](https://colab.research.google.com/gist/rakeshmothukuru1/c2f6a4896f0a5414581bd438218f2eff/he_normal_initializer_bug.ipynb).

**Comment by benyeoh** [comment]
Using a larger number of weights seems to show convergence of the sample mean to 0 (ie, central limit theorem):
https://colab.research.google.com/gist/benyeoh/3ffec8ef0262e238918c36e00e11ccd2/glorot_initializer_bug.ipynb
https://colab.research.google.com/gist/benyeoh/f56b10487c343cabc3e509eab078fe3e/he_normal_initializer_bug.ipynb

**Comment by tilakrayal** [comment]
@rakeshmothukuru1 ,

Please take a look at above @benyeoh  comment and let us know if you are still facing the same issue? Thanks!

**Comment by rakeshmothukuru1** [comment]
> Using a larger number of weights seems to show convergence of the sample mean to 0 (ie, central limit theorem):
> https://colab.research.google.com/gist/benyeoh/3ffec8ef0262e238918c36e00e11ccd2/glorot_initializer_bug.ipynb
> https://colab.research.google.com/gist/benyeoh/f56b10487c343cabc3e509eab078fe3e/he_normal_initializer_bug.ipynb

@benyeoh,
Thank you for your response. I'm not sure if this is acceptable because we don't always use huge number of **`Weights`**.  The heuristic behind **`Glorot`** and **`He`** **`Initializers`** is to have a **`Mean`** of **`Zero`** and the **`Weights`** should be Initialized accordingly, irrespective of the number of Neurons used.

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist here.[Gist1](https://colab.research.google.com/gist/tilakrayal/fd764d6da6e2799c204acc7e8561f0e4/49896-glorot_initializer_bug.ipynb),[Gist2](https://colab.research.google.com/gist/tilakrayal/f89047ab8e3a7dbde283dab4029e8d48/49896-he_normal_initializer_bug.ipynb)

**Comment by benyeoh** [comment]
> > Using a larger number of weights seems to show convergence of the sample mean to 0 (ie, central limit theorem):
> > https://colab.research.google.com/gist/benyeoh/3ffec8ef0262e238918c36e00e11ccd2/glorot_initializer_bug.ipynb
> > https://colab.research.google.com/gist/benyeoh/f56b10487c343cabc3e509eab078fe3e/he_normal_initializer_bug.ipynb
> 
> @benyeoh,
> Thank you for your response. I'm not sure if this is acceptable because we don't always use huge number of **`Weights`**. The heuristic behind **`Glorot`** and **`He`** **`Initializers`** is to have a **`Mean`** of **`Zero`** and the **`Weights`** should be Initialized accordingly, irrespective of the number of Neurons used.

@rakeshmothukuru1 
Well, since you are drawing random samples to initialize the weights (from a truncated normal distribution with an arbitrary scale), the **sample mean** is unlikely to be exactly 0 especially for a small number of samples. But by the Central Limit Theorem, as the sample size approaches infinity, the sample mean will converge to the true **population mean**. From my earlier gists it seems like the sample means were converging to 0.

**Comment by rakeshmothukuru1** [comment]
@benyeoh,
In your Gist, you were using 4096 Neurons, which is a very big number. We usually use some hundreds of Neurons. So, sorry but I'm still not convinced. 

I want to listen it from Google Engineers too, about this bug.

**Comment by gowthamkpr** [comment]
@rakeshmothukuru1 As mentioned [here](https://stackoverflow.com/questions/67754649/mean-of-tensorflow-kerass-glorot-normal-initializer-is-not-zero), The initializer's mean is zero, you are random sampling from it. That's normal that sample's mean will not be exactly 0.
