### ISSUE TITLE
using #pragma once

### ISSUE THREAD

**Issue by abhinavagarwal07** [tensorflow/tensorflow#499]
Shouldn't we use both `pragma` once and `ifndef` gaurds ?

**Comment by vincentvanhoucke** [comment]
We can not replace the `#ifndef` guards with `#pragma once` for various reasons. What would be gained concretely from having both?

**Comment by girving** [comment]
If both are needed in any case, it would mean that the `#ifdef` guards are wrong and bugs will appear if `#pragma once` doesn't work.
