### ISSUE TITLE
Eager Execution Documentation includes Sections not Describing Relation or relevance to Eager Execution

### ISSUE THREAD

**Issue by lonerzzz** [tensorflow/tensorflow#49906]
## URL(s) with the issue:

https://www.tensorflow.org/guide/eager

## Description of issue (what needs changing):

In the documentation for Eager Execution, the following sections are included but no detail is provided as to why these sections are related to Eager Execution. A description is required to indicate if these capabilities/operations are only available, operate differently or in what other way are related to Eager Execution. Right now, it is entirely unclear why these sections are located on the Eager Execution page.

"Object-based saving"
"Summaries and TensorBoard"
"Advanced automatic differentiation topics"
"Performance"

**Comment by 8bitmp3** [comment]
Appreciate this @lonerzzz. We'll look into this cc @MarkDaoust

**Comment by sachinprasadhs** [comment]
The document has been chnaged to https://www.tensorflow.org/guide/basics, which does not mention about the topics which is mentioned by you.
Could you please refer the document and close the issue. Thanks!
