### ISSUE TITLE
Fail to load weights of Keras MobilenetV2

### ISSUE THREAD

**Issue by bratyslav** [tensorflow/tensorflow#49904]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux? (Google Colab)
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.10

**Describe the current behavior**
tensorflow.keras.applications.MobileNetV2() fail to return a model with Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1_224_no_top.h5: 404 -- Not Found.

**Describe the expected behavior**
Expect to get a model with loaded weights.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**
import tensorflow
model = tensorflow.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    alpha=1,
    include_top=False,
    weights='imagenet',
    input_tensor=tensorflow.keras.layers.Input((224, 224, 3)),
    pooling=None,
    classes=1000,
    classifier_activation='softmax'
)

Colab to reproduce: https://colab.research.google.com/drive/1d9aaTVCFDMWyyiKrEsIHBe_BFnEEiKKD?usp=sharing

**Other info / logs**
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    257       try:
--> 258         urlretrieve(origin, fpath, dl_progress)
    259       except urllib.error.HTTPError as e:

9 frames
HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    258         urlretrieve(origin, fpath, dl_progress)
    259       except urllib.error.HTTPError as e:
--> 260         raise Exception(error_msg.format(origin, e.code, e.msg))
    261       except urllib.error.URLError as e:
    262         raise Exception(error_msg.format(origin, e.errno, e.reason))

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1_224_no_top.h5: 404 -- Not Found

**Comment by tusharvickey1999** [comment]
in the arguments instead of alpha = 1 , write alpha = 1.0. It will work

**Comment by ymodak** [comment]
Docs mention that it expects a float between 0 and 1. https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNetV2#args
Perhaps we can silently convert the value to float and update the docs `alpha = 1.0`

**Comment by bratyslav** [comment]
> Docs mention that it expects a float between 0 and 1. https://www.tensorflow.org/api_docs/python/tf/keras/applications/MobileNetV2#args
> Perhaps we can silently convert the value to float and update the docs `alpha = 1.0`

Thanks a lot, it works :)
