### ISSUE TITLE
TfLite CUMSUM operator missing reference test 

### ISSUE THREAD

**Issue by ddavis-2015** [tensorflow/tensorflow#49913]
While porting the CUMSUM kernel op to TFLM, it was discovered that the reference code for the operator in tensorflow/lite/kernels/internal/reference/cumsum.h did not have a dedicated test.  The existing TfLite test for the CUMSUM kernel only tested the optimized version of the operator.  The Eval code for the TfLite CUMSUM kernel only calls the optimized operator code.

A test for the reference version of the operator has been created.

**Comment by pjpratik** [comment]
Hi @ddavis-2015 

The cumsum op test has been included in the https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/cumsum_test.cc 

Can you please let us know if this works for your case?

Thanks.
