### ISSUE TITLE
Check layer by layer execution time in tensorflow object detection API model

### ISSUE THREAD

**Issue by IAM-P-LP** [tensorflow/tensorflow#49918]
How to calculate the execution time of each layers in tensorflow object detection API model?
Also I am able to see the node names using the below code.How to use tf.graph() to get the layer names?

import tensorflow as tf
# read pb into graph_def

with tf.io.gfile.GFile("frozen_inference_graph.pb", "rb") as f:
  graph_def = tf.compat.v1.GraphDef()
  graph_def.ParseFromString(f.read())

with tf.Graph().as_default() as graph:
  tf.import_graph_def(graph_def)

for op in graph.get_operations(): 
  print(op.name, [inp for inp in op.inputs])

**Comment by tilakrayal** [comment]
@IAM-P-LP ,

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or completed code to reproduce the issue]  or if possible share a colab gist with the issue reported.

Thanks!

**Comment by IAM-P-LP** [comment]
Hi,
tf_version : 2.3.1

I have trained a mobilenet-ssd v2 tf model for face detection.So using the frozen pb file,I ran the code pasted above,to get the tensor names.How to use tf.graph(),such that I will get the layer names to get the inference time taken by each layers?.

**Comment by tilakrayal** [comment]
@IAM-P-LP ,

Can you please go through the issues with similar references.It helps.[Link1](https://stackoverflow.com/questions/35336648/list-of-tensor-names-in-graph-in-tensorflow),[Link2](https://www.tensorflow.org/api_docs/python/tf/Graph).It helps.Thanks!
