### ISSUE TITLE
[RNN] Post-training integer quantization got low performance when increasing the size of representative dataset.

### ISSUE THREAD

**Issue by Mrlyk423** [tensorflow/tensorflow#49927]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7 
- TensorFlow installation (pip package or built from source): tensorflow-nightly
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

My model is a 5-layer Bidirectional LSTM. The originally trained model accuracy is about 0.90. When I increase the size of the representative dataset from 400 to 20000，the quantitative model's acc decrease from 0.85 to 0.50. How is the representative dataset used? In my opinion, the more data I provide, the better quantization performance I will obtain. But it seems not, why?

```
def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(train_data).batch(1).take(400):
    yield [input_value]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

tflite_model_quant = converter.convert()
```

**Comment by Xhark** [comment]
Representative dataset is used to determine the quantization range. It's possible to model be worse if some data points are extreme. (e.g. makes huge numerical error or quantize op has huge error for the data.)

 We can debug it if you provide the actual model & dataset. Can you share some more details?
