### ISSUE TITLE
build tensorflow 1.15 from source code based on cuda 11

### ISSUE THREAD

**Issue by xieyi4650** [tensorflow/tensorflow#49923]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary):  source
- TensorFlow version: 1.15
- Python version: 3.6
- Installed using virtualenv? pip? conda?: docker container, build using tensorflow official dockerfile
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: 11.2/8.1
- GPU model and memory: v100/16G

**Describe the problem**
I want to build tensorflow 1.15 from source code, because I have added some code in contrib.
first, I build a docker image which is dev-gpu-bazel0.26.1-py3-cuda11.2-cudnn8.1.0-ubuntu18.04
then create a container base on this image. 
After run ./configure, a error occurred,
"ValueError: dictionary update sequence element #9 has length 1; 2 is required"
This seems that function to find cuda10 information is not work for cuda 11. So I replace "./third_party/gpus/cuda_configure.bzl"
and "third_party/gpus/find_cuda_config.py" with corresponding files in tensorflow2.
But, another error occurred, seems that the code are depended by other code and depend on other code.

I found a issue and get a reply,  https://github.com/tensorflow/tensorflow/issues/43629#issuecomment-702851560
said that, I can not use tf1.15 on cuda11.
But I found another page said, they can install tensorflow 1.15 on cuda 11, but by pip not by build from source code.
,  https://developer.nvidia.com/blog/accelerating-tensorflow-on-a100-gpus/

So, what I want is that, How can I build tensorflow 1.15 when cuda versio is 11.2.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@xieyi4650 
Tensorflow 1.15 is not actively supported, please upgrade to tensorflow 2.x, you may try tensorflow stable version 2.4.1 and cuda 11.0/cuddnn 8.0 and let us know.
Please refer to the [tested build configurations here](https://www.tensorflow.org/install/source_windows#gpu). [similar issue #49233]
