### ISSUE TITLE
Changes in Input size of the model do not save when calling saved_model.save

### ISSUE THREAD

**Issue by KapitanKabzon** [tensorflow/tensorflow#49920]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 2004
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: irrelevant?
- GPU model and memory:

**Describe the current behavior**
Changes in input shape of the model are not applied when saving the model, as can be seen that Input shape is changed before saving the model, and when opening the saved model the input shape reverts to [None,None,None,3] .

**Describe the expected behavior**
Input shape in the new saved model should change to the [1,640,640,3].

This is mainly required to convert the model into TFlite compatible one.

**Standalone code to reproduce the issue**

import tensorflow as tf

print(tf.__version__)

model = tf.saved_model.load("exported-models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model") #taken from Object detection zoo
model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 640, 640, 3])
tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
print(model.signatures['serving_default'].inputs[0])

model2 = tf.saved_model.load("saved_model_updated")

print(model2.signatures['serving_default'].inputs[0])

####################################
2.5.0

WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 155). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: saved_model_updated\assets

INFO:tensorflow:Assets written to: saved_model_updated\assets

Tensor("input_tensor:0", shape=(1, 640, 640, 3), dtype=uint8)
Tensor("input_tensor:0", shape=(None, None, None, 3), dtype=uint8)

**Comment by UsharaniPagadala** [comment]
@KapitanKabzon 

In order to expedite the trouble-shooting process, please provide a code snippet/colab gist to reproduce the issue reported here. Thanks!

**Comment by jvishnuvardhan** [comment]
@KapitanKabzon I tried your code with different model and I don't see the issue. only batch_size dimension is set as `None` for obvious reasons. [Here](https://colab.research.google.com/gist/jvishnuvardhan/8c7558d191c01242ffd5ee077300fb85/untitled.ipynb) is a gist for a reference. 

Please share the model you are using to verify it. Thanks!

**Comment by KapitanKabzon** [comment]
i am using this model: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.tar.gz
from the https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md.

Slightly modified my code for clarification.
`import tensorflow as tf

print(tf.__version__)


model = tf.saved_model.load("exported-models/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8/saved_model") #taken from Object detection zoo
print('Model Original input size: ')
print(model.signatures['serving_default'].inputs[0])
model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 640, 640, 3])
tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
print('Model modified input size: ')
print(model.signatures['serving_default'].inputs[0])



model2 = tf.saved_model.load("saved_model_updated")

print('Model loaded modified input size')
print(model2.signatures['serving_default'].inputs[0])`
########### Notebook output #############
2.4.1
Model Original input size: 
Tensor("input_tensor:0", shape=(1, None, None, 3), dtype=uint8)

WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 155). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 155). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: saved_model_updated\assets

INFO:tensorflow:Assets written to: saved_model_updated\assets

Model modified input size: 
Tensor("input_tensor:0", shape=(1, 640, 640, 3), dtype=uint8)
Model loaded modified input size
Tensor("input_tensor:0", shape=(1, None, None, 3), dtype=uint8)

**Comment by KapitanKabzon** [comment]
> 
> 
> @KapitanKabzon I tried your code with different model and I don't see the issue. only batch_size dimension is set as `None` for obvious reasons. [Here](https://colab.research.google.com/gist/jvishnuvardhan/8c7558d191c01242ffd5ee077300fb85/untitled.ipynb) is a gist for a reference.
> 
> Please share the model you are using to verify it. Thanks!

BTW, if you look at the loaded_model and model2 input tensors you can see that the batch size doesn't save, and quantization requires all the inputs to be set in stone.

**Comment by jvishnuvardhan** [comment]
@KapitanKabzon Can you try using `set_shape` method of set shape as shown in [this](https://github.com/tensorflow/tensorflow/issues/26708#issuecomment-474152784) GitHub response.  May be the following links may help you. [link2](https://github.com/tensorflow/tensorflow/issues/35736), [Link3](https://github.com/tensorflow/tensorflow/issues/34350). 

Hope it helps. Thanks!

**Comment by KapitanKabzon** [comment]
nothing changes if i use this method to change the input parameters.

concrete_func = model.signatures[
    tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 640, 640, 3])

Its still the same behavior, i guess a workaround of changing the input shape when specifically doing the TFlite conversion is doable, but it is weird that changes to the model do not save.

**Comment by jvishnuvardhan** [comment]
@KapitanKabzon Is it possible to share one standalone code to reproduce the issue? I see the parts of the code but if you can put together in one colab gist or Jupyter notebook, then it will help us resolving faster. Thanks!

**Comment by KapitanKabzon** [comment]
Here is the link to the folder Untitled.ipynb is the code, the model that is loaded is included in the folder.
https://github.com/KapitanKabzon/EiT_Metal/tree/master/TensorFlowIssue

**Comment by Zeeshan113-hub** [comment]
making this error: "AttributeError: 'str' object has no attribute 'signatures'"

**Comment by Zeeshan113-hub** [comment]
i have tflite model please change input size of my model provide me a code in which i can change my model input size 
thanks

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
