### ISSUE TITLE
Elu int8 quantization doesn't reduce the size needed by the model on Arduino

### ISSUE THREAD

**Issue by EleonoreBarges** [tensorflow/tensorflow#49929]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution : Mac OS 10.14.8 
- TensorFlow installed from source
- Tensorflow version : 2.5.0
- Target platform : Arduino Nano 33

**Describe the problem**
Context :
I would like to run inferencing of a DL-model on an Arduino and, since I don't have much memory available, I need to int8-quantize my model.
But the quantization of my model doesn't seem to be working, and it seems to be linked to the Elu activations functions in the model.
Indeed, I get no error during both the conversion and the quantization of the model on Python and the inferencing on Arduino, but the necessary size for the model on the Arduino remains the same than without quantization.

What I tried :
- I retrained a model in which I changed the Elu for Relu activation functions. Then quantization works : thanks to the line : tflInterpreter->arena_used_bytes() on Arduino, I can see that quantization helped me to reduce the necessary size for the model by 3.
- I analysed the model (quantized, with Elu) on the Netron App and I realised that there are steps of de-quantization and re-quantization before and after each call of Elu function : model de-quantize and re-quantize. I don't understand why is this doing so, when it doesn't append with Relu functions: <img width="582" alt="Screenshot 2021-05-31 at 15 42 59" src="https://user-images.githubusercontent.com/78730433/120202463-e5824e00-c226-11eb-8ac6-fe37c5d5911e.png">
- Finally, I found this commit on Tensorflow Git, which made me believe that int8 quantization for Elu is implemented : [commit Elu quant](https://github.com/tensorflow/tensorflow/commit/918f876bf812fd744151fea29b2df4aa18acfa8f) Nevertheless, they mentioned a LUT approach, which I don't understand and might (?) be linked to the troubles I am facing.

Does anyone face the same king of troubles for quantization of model containing Elu ? Do you have any idea of how to solve this problem ?

Thank you really much !

**Comment by teijeong** [comment]
Hi @EleonoreBarges, please close this issue if the fix is verified. Thanks!

**Comment by EleonoreBarges** [comment]
Thanks for your help, this is working now ! :)
