### ISSUE TITLE
Tensorflow1.10 CPU Exceed 10% of system memory, Segmentation fault 

### ISSUE THREAD

**Issue by AI-Friend** [tensorflow/tensorflow#49928]
**I would like to ask why the program will have segmentation fault if it exceeds 10% of the system memory. Obviously, there is still a lot of memory to use.**
**100G of memory is used, and 400G  unused.**

Thank you for your answer！
code:
os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(FLAGS.gpu_id)
... 
    with tf.train.MonitoredTrainingSession(
            checkpoint_dir=model_dir,
            hooks=hooks,
            config=config
    ) as sess:
        while not sess.should_stop():
            sess.run(train_op)
...
Exceed 10% of system memory, Segmentation fault !

**Comment by Saduf2019** [comment]
@AI-Friend 
We see that you are using 1.x which is not actively supported anymore, please upgrade to 2.x and let us know.
You may use stable version tf 2.4.1, refer to similar issue  [#49233] and refer to the tested [build configurations here.](https://www.tensorflow.org/install/source_windows#gpu)

**Comment by AI-Friend** [comment]
I mean, do you have any default settings in tf1.10 to limit the use of memory? 
At present, I only use 20% of the memory to report an error:

W tensorflow/core/framework/allocator.cc:108] Allocation of 105062400000 exceeds 10% of system memory. 
Segmentation fault

At present, TF1. X is still the most used version in our industry, not 2. X.
Thank you for your answer！

**Comment by Saduf2019** [comment]
@AI-Friend 
Can you please try [limiting gpu](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth),refer to [link](https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory).

As 1.x is not supported please have a look at similar issues:[link](https://github.com/tensorflow/tensorflow/issues/17783),#45310

**Comment by AI-Friend** [comment]
I am using CPU instead of GPU. 
I want to confirm whether TF1.10 limits the CPU usage, b
ecause the error is: 
W tensorflow/core/framework/allocator.cc:108] Allocation of 105062400000 exceeds 10% of system memory.
Exceed 10% of system memory, Segmentation fault !
If TF1.10 does not limit the CPU usage, the exit operation may be caused by other problems such as memory leaks！

Thank you for your answer！

**Comment by Saduf2019** [comment]
@AI-Friend 
Like i told you earlier there is no support for 1.x anymore[to check on memory leaks], it could be that memory is used for some other process in your system thats limiting usage for tensorflow.
There are issues related to the error reported in tf 1.x in past:#7717,#9263,#11550 [you may look up extremely old issues related to your error and configuration or try to build tf again on your system]
