### ISSUE TITLE
Improvement for tf.keras.utils.get_file

### ISSUE THREAD

**Issue by bizzyvinci** [tensorflow/tensorflow#49926]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
tf.keras.utils.get_file only works with `GET` request. I think it can work for `POST` request too if the `data` argument is utilized in [urlretrieve](https://github.com/tensorflow/tensorflow/blob/ecc0010f151cabb0a4730777790631fd6fff8f6f/tensorflow/python/keras/utils/data_utils.py#L259). 

**Will this change the current api? How?**
Yes, get_file would take in one other parameter (don't know which name and type would be best) to pass into the retrieve function.

**Who will benefit with this feature?**
Whoever wants to get file that's accessed through post method, such as files that require tokens or authorization.

**Side note on documentation.**
In [get_file documentation](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file), `untar` and `md5_hash` arguments have been depreciated in favor of `extract` and `file_hash`. I thought about some changes but I don't know if they would add value.
* Change [example](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file#example) argument from `untar=True` to `extract=True`
* Rearrange arguments in documentation and function to show `extract` and `file_hash` before `untar` and `md5_hash`.

**Comment by rmothukuru** [comment]
@bizzyvinci,
Can you please specify the use-cases  for this feature? Thanks!

**Comment by bizzyvinci** [comment]
I do compete on Zindi.africa and files can be downloaded using API. But, they use post method instead of get.

So using `tf.keras.utils.get_file(filename, api)` would fail with 4\*\* error. 

However, using `urlretrive(api, filename, data=b'auth_token=MY_AUTH_TOKEN')` would download the file. Because as per [urlretrieve documentation](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve), "the optional data argument may be given to specify a POST request (normally the request type is GET)"

`tf.keras.utils.get_file(filename, api+'?auth_token=MY_AUTH_TOKEN')` would not work either.

Right now, I can't find another example where `post` is used rather than `get` method to access a file.
