### ISSUE TITLE
DepthwiseConv2D documentation: a different filter per channel vs the same filter per channel

### ISSUE THREAD

**Issue by vinhill** [tensorflow/tensorflow#49933]
The documentation for [tf.keras.layers.DepthwiseConv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/DepthwiseConv2D) describes this operation as: split input into individual channels, convolve each with the layer's kernel and finally stack the results. This gives the impression the same kernel is applied to all channels. But I believe the actual implementation applies a different kernel per channel.

Relevant code sections
- Backend implementation: https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/ops/nn_impl.py#L760-L766
- Keras layer: https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/layers/convolutional.py#L2260-L2269

Also see [MobileNet Paper](https://arxiv.org/pdf/1704.04861.pdf) page 3 formula 3

**Comment by vinhill** [comment]
[Depthwise kernel shape](https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/layers/convolutional.py#L2403-L2405) further highlights, that DepthwiseConv2D is implemened as c kernels of shape (k, k) rather than one kernel of shape (k, k) applied to all c channels.

**Comment by MarkDaoust** [comment]
+1.

The description in the keras layer should be clarified. 

Note whenmaking the update that `channel_multiplier` in `nn_impl.py` is called `depth_multiplier` in `convolutional.py`

**Comment by vinhill** [comment]
I made a pull request to the keras repo, see https://github.com/keras-team/keras/pull/14817.
