### ISSUE TITLE
Pass epoch number as arg to `tf.data.Dataset.from_generator`

### ISSUE THREAD

**Issue by dakshvar22** [tensorflow/tensorflow#49935]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**: I am trying to implement a tensorflow dataset which uses a generator underneath yielding batches following a linearly increasing batch size scheme. So, the first epoch it could yield batches of size `x`, the next epoch it would yield batches of size `x+c`. `c` is dependent on the current epoch number. I am defining my tensorflow dataset as:

```
def gen(epoch_number):
    yield epoch_number # Just representative. In reality this will be some function of epoch_number and data.

dataset = tf.data.Dataset.from_generator(gen, output_types=(tf.int32), args=[x])

# A custom keras model derived from tf.keras.Model
model = SomeModel()

model.fit(dataset)
```

I am trying to figure out what to pass as `x` in the above code so that the generator has information about the current epoch number when the generator is called.
As far as I know, there is no instance attribute of `tf.keras.Model` which could be used as `x` so that it's evaluated at runtime and passed to the generator.

Is it possible to do so?
I'd like to avoid overriding the `fit` or `train_step` method of the model.

**Will this change the current api? How?**:  I don't think so.

**Who will benefit with this feature?**: Batch yielding from dataset can use training stages and depend on them, for example number of epochs passed in the above example.

**Comment by sachinprasadhs** [comment]
Hi, I think you can achieve this through normal python loop, where in for each epoch iteration you can specify the required batch size or steps.
