### ISSUE TITLE
need a custom implementation: BroadcastTo.

### ISSUE THREAD

**Issue by mahdaneh** [tensorflow/tensorflow#49934]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10, x86-64
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.15

**Provide the text output from tflite_convert**

```

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DIV, LEAKY_RELU, MAX_POOL_2D, MUL, SUB, TANH, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: BroadcastTo.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.
Traceback (most recent call last):
  File "c:\users\anaconda3\envs\pytorch1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\anaconda3\envs\pytorch1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anaconda3\envs\pytorch1\Scripts\toco_from_protos.exe\__main__.py", line 7, in <module>
  File "c:\users\anaconda3\envs\pytorch1\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "c:\users\anaconda3\envs\pytorch1\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\anaconda3\envs\pytorch1\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 52, in execute
    enable_mlir_converter)

**Comment by UsharaniPagadala** [comment]
@mahdaneh 
looking at the error log,seems like this is similar to  [issue](https://github.com/tensorflow/tensorflow/issues/33490) and let us know if it helps.Thanks

**Comment by abattery** [comment]
Please use the recent TF 2.x version for TFLite conversion after creating your TF model in TF 1.x. The above BroadcastTo op is already supported in the recent versions.

**Comment by mahdaneh** [comment]
Thanks for your hint @abattery. The issue is resolved by migrating my  code (in TF1.15) to TF2 via help of [this](https://www.tensorflow.org/guide/upgrade). Then using TF2 and setting `tf.compat.v1.disable_v2_behavior()`, I was able to convert my model to tflite throught `tf.compat.v1.lite.TFLiteConverter.from_frozen_graph`.
