### ISSUE TITLE
[RNN] Tflite's fused LSTM does not support masking

### ISSUE THREAD

**Issue by Mrlyk423** [tensorflow/tensorflow#49936]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7
- TensorFlow installation (pip package or built from source): tensorflow-nightly

### 2. Code

```
        model = LSTM_model
	run_model = tf.function(lambda x: model(x))
	## This is important, let's fix the input size.
	BATCH_SIZE = 1
	INPUT_LEN = 150
	INPUT_SIZE = 9
	concrete_func = run_model.get_concrete_function(
	    [tf.TensorSpec([BATCH_SIZE, INPUT_LEN, INPUT_SIZE], "float32")])
	MODEL_DIR = "lstm"
	model.save(MODEL_DIR, save_format="tf", signatures=concrete_func)
	# Convert the model.
	converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
        #converter = tf.lite.TFLiteConverter.from_keras_model(model)
	tflite_model = converter.convert()
```

### 3. Failure after conversion

   I find that the performance of LSTM with masking decreases heavily if I convert it into fused version by tf.function (The Tflite model work OK if I directly convert it with function "from_keras_model". And I find that the masking seems not to work in the fused version.

**Comment by renjie-liu** [comment]
Indeed we do not support masking for the fused lstm, also can you share the tflite model? thanks

**Comment by thaink** [comment]
The current TFLite UndirectionalSequenceLSTM doesn't support mask input yet. So fusing to LSTM with masking to that is being disabled at the moment.
Can you share the performance numbers?

**Comment by tilakrayal** [comment]
@Mrlyk423 ,
Can you please provide the required details to debug the issue.Also please try to execute the code in latest tf version 2.7.It helps.Thanks!
