### ISSUE TITLE
outputs  from tensor flow lite doesn't meet python script to generate output from any layer if i train the model 

### ISSUE THREAD

**Issue by mostafa1231** [tensorflow/tensorflow#49937]
https://i.stack.imgur.com/qZ2rl.png

image from "Quantization and Training of Neural Networks for Efficient
Integer-Arithmetic-Only Inference"

Hello , i am trying to catch the error which is simply i take input ,weight ,zeros , scales then add bias to the result and apply this equation in first image 
using python comparing the result with output from tensor flow lite 
but a weird thing happen which is if i untrained model just initialize it with random values the two output from python and tensor flow lite meet but if i train model and do the same thing i didn't get the same output. 
in details : to get output from point wise layer (conv2d ) 
i extract weights,zeros,inputs,scale from tensor flow lite 
and apply the equation in image get same result if i initialize model with random values 
in moment that  i train model the result is different , note that i extract the new parameters out for sure 
i  implemented moblie net and using normal relu not relu 6 is this can make problem ?
i upload my neutron model :
https://drive.google.com/file/d/1ENVZCf0hSOiIIh8-0X_-7I23sv3Az2_2/view?usp=sharing

**Comment by mostafa1231** [comment]
i try to know the operation done internal tensor flow lite cause i want to implement it on fpga 
is there is another way to view this operation of instead equation written in paper i will be okay with it 
cause my main target to implement this operation on and run model on fpga

**Comment by mostafa1231** [comment]
the soultion to 
tf.lite.Interpreter(
    model_path=None, model_content=None, experimental_delegates=None,
    num_threads=None,
    experimental_op_resolver_type=tf.lite.experimental.OpResolverType.AUTO,
    experimental_preserve_all_tensors=False
)
make >>   experimental_preserve_all_tensors=true to save inputs, scales cause if it false he will save outputs only and any ask to intermediate node will be garbage 
thanks to Eng.Karim Nosseir

**Comment by xunkai55** [comment]
Hi @mostafa1231 , can we close this issue because you already get the solution? Please feel free to reopen if it's not the case. Thanks!
