### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'seq2seq'

### ISSUE THREAD

**Issue by ABHAY-05** [tensorflow/tensorflow#49948]
Data ready!
Bucketing conversation number 9999
Bucketing conversation number 19999
Bucketing conversation number 9999
Bucketing conversation number 19999
Bucketing conversation number 29999
Bucketing conversation number 39999
Bucketing conversation number 49999
Bucketing conversation number 59999
Bucketing conversation number 69999
Bucketing conversation number 79999
Bucketing conversation number 89999
Bucketing conversation number 99999
Bucketing conversation number 109999
Bucketing conversation number 119999
Bucketing conversation number 129999
Bucketing conversation number 139999
Bucketing conversation number 149999
Bucketing conversation number 159999
Bucketing conversation number 169999
Bucketing conversation number 179999
Bucketing conversation number 189999
Number of samples in each bucket:
 [111977, 37536, 12893, 13731, 8591, 4756]
Bucket scale:
 [0.5909575478668384, 0.7890534293132929, 0.8570961136560343, 0.9295613349939836, 0.9749002554305377, 1.0]
Initialize new model
Create placeholders
Create inference
D:\Program Files\python\lib\site-packages\tensorflow\python\keras\layers\legacy_rnn\rnn_cell_impl.py:535: UserWarning: `tf.nn.rnn_cell.GRUCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.GRUCell`, and will be replaced by that in Tensorflow 2.0.
  warnings.warn("`tf.nn.rnn_cell.GRUCell` is deprecated and will be removed "
WARNING:tensorflow:`tf.nn.rnn_cell.MultiRNNCell` is deprecated. This class is equivalent as `tf.keras.layers.StackedRNNCells`, and will be replaced by that in Tensorflow 2.0.   
WARNING:tensorflow:At least two cells provided to MultiRNNCell are the same object and will share weights.
Creating loss...
It might take a couple of minutes depending on how many buckets you have.
Traceback (most recent call last):
  File "c:\Users\ABHAY VERMA\Documents\Chatbot\chatbot.py", line 243, in <module>
    main()
  File "c:\Users\ABHAY VERMA\Documents\Chatbot\chatbot.py", line 238, in main
    train()
  File "c:\Users\ABHAY VERMA\Documents\Chatbot\chatbot.py", line 119, in train
    model.build_graph()
  File "c:\Users\ABHAY VERMA\Documents\Chatbot\model.py", line 118, in build_graph
    self._create_loss()
  File "c:\Users\ABHAY VERMA\Documents\Chatbot\model.py", line 79, in _create_loss
    self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'seq2seq'

**Comment by Saduf2019** [comment]
@ABHAY-05 
We see that you have not filled in the issue template, please do so, for us to know the tf version and code, if possible share a colab gist with the issue reported.
Please try on latest version and let us know.

From the error logs please refer to these and let us know: [link](https://github.com/suriyadeepan/practical_seq2seq/issues/21),[link2](https://stackoverflow.com/questions/42619180/tensorflows-api-seq2seq)
