### ISSUE TITLE
Feature request: ExportCostModels in C/Python API?

### ISSUE THREAD

**Issue by codefever** [tensorflow/tensorflow#4994]
Exporting cost models of graphs seems to be a great feature with which users could figure out the resource-intensive (or even slowest) part of graphs, but currently it's not visible in the C/Python API.

I've tried to make it work and found that ExportCostModels() is not a member function in the "Session" interface. Also, a CostGraphDef object is related to a partition of some graph, placed on some device. ExportCostModels() in "DirectSession" only provides a mapping from partitions (note that for all the graphs executed) to CostGraphDef objects and it's hard to get CostGraphDef directly for the concerning parts. So I think there should be more works to make the code eligible and easy for use.

I wonder whether is anybody working on this and how developers think about this feature. Thank you!

**Comment by yaroslavvb** [comment]
@yuanbyu has been looking at CostModels recently

**Comment by codefever** [comment]
I looked though session.py and finally found that CostGraphDef is exported via RunMetaData which is one of the paramters for `Session.run`. I think this issue could be closed. Thanks anyway.

**Comment by asimshankar** [comment]
I'm going to close this issue for now since, as you pointed out the `CostGraphDef` is available from the `RunMetadata`. However, if profiling your graph is what is driving you, you might also want to consider [tracing](https://github.com/tensorflow/tensorflow/issues/1824#issuecomment-225754659)
