### ISSUE TITLE
Try to use TensorflowLite (API C++) NNAPI acceleration, meet errors.

### ISSUE THREAD

**Issue by yahuuu** [tensorflow/tensorflow#49947]
**BUILD .SO System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MI 9 (android 9, Snapdragon855)
- TensorFlow installed from (source or binary):   source  (branch in * tf25   15d5b93 [origin/r2.5] Merge pull request #49270 from angerson/r2.5)
- TensorFlow version: 2.5
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: conda 
- Bazel version (if compiling from source):  3.7.2
- GCC/Compiler version (if compiling from source):  7.3.0
- CUDA/cuDNN version: NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0  CUDANN Version: 7.3.1
- GPU model and memory:  Tesla K40m 11441MiB
- cmake version: 3.20.0
- NDK version : 21b (NDK API level us 21)
- SDK API level  use version 28 
**BUILD .apk System information**
- Windows 10 10.0
- Android build tools use versions: 28.0.3
- Android Studio 4.2.1
- compile sdk version: 28
- NDK version： 21.1.6352462

 
**Describe the problem**
Briefly：
 ubuntu build libnnapi_delegate.so ->  build .apk in windows10 Android Studio ->meet linkerror：java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol referenced by so.
verbosely： 
I refer to this super_resolution [example ](https://github.com/tensorflow/examples/tree/master/lite/examples/super_resolution/android) try to run the AI model on the mobile DSP，I build nnapi delegate  .so like this ：
####
bazel build -c opt --repository_cache=/home/wjl/dockerworkspace/tensorflow_16ubuntu/2cache --distdir=/home/wjl/dockerworkspace/tensorflow_16ubuntu/2cache --config=android_arm64  --cxxopt="-std=c++14"       //tensorflow/lite/delegates/nnapi:nnapi_delegate
####
then I get ：
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/nnapi/libnnapi_delegate.so (about  1.6M).
I add so and header files to the super_resolution demo.
No errors or warnings were reported when compiling the apk. But at runtime, logcat reports an error: jProcess: org.tensorflow.lite.examples.superresolution, PID: 15939
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite16logging_internal13MinimalLogger3LogENS_11LogSeverityEPKcz" referenced by "/data/app/org.tensorflow.lite.examples.superresolution-50dhWLUyWoZrFw8sIcvg5w==/lib/arm64/libnnapi_delegate_strip.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.tensorflow.lite.examples.superresolution.MainActivity.<clinit>(MainActivity.java:47)
        at java.lang.Class.newInstance(Native Method)  ...

1. How to solve the missing symbol of so？
2. I add the following code to the SR demo to call nnapi,  I have to use c++ interface and NDK .Is it correct to call nnapi like this? My apk hasn't run yet.
"""""""add this """"""
       #include "tensorflow/lite/delegates/nnapi/nnapi_delegate.h" 
       ...
      // reference link: ​https://github.com/lackhole/CuteModel/blob/master/CuteModel.cpp
     nnapiOptions = tflite::StatefulNnApiDelegate::Options();  // nnapi
      nnApiDelegate_ =  new tflite::StatefulNnApiDelegate(nnapiOptions);
      TfLiteInterpreterOptionsAddDelegate(options_, nnApiDelegate_);

**Comment by yahuuu** [comment]
./readelf   -d  libnnapi_delegate.so
>>
Dynamic section at offset 0x20a60 contains 26 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../../../_solib___Caarch64-linux-android-clang9.0.8-libcpp/:$ORIGIN/_solib___Caarch64-linux-android-clang9.0.8-libcpp/]
 0x000000000000001a (FINI_ARRAY)         0x21a48
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x0000000000000004 (HASH)               0x1c8
 0x000000006ffffef5 (GNU_HASH)           0x6a0
 0x0000000000000005 (STRTAB)             0x1af8
 0x0000000000000006 (SYMTAB)             0xa78
 0x000000000000000a (STRSZ)              10592 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x21c40
 0x0000000000000002 (PLTRELSZ)           2520 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4760
 0x0000000000000007 (RELA)               0x45f8
 0x0000000000000008 (RELASZ)             360 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x45b8
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0x4458
 0x000000006ffffff9 (RELACOUNT)          3

**Comment by abattery** [comment]
@miaowang14 could you take a look?

**Comment by yahuuu** [comment]
Online waiting for reply :)

**Comment by yahuuu** [comment]
libtensorflowlite_jni.so
libtensorflowlite_gpu_jni.so
and
libnnapi_delegate.so 
libnnapi_implementation.so
libnnapi_util.so
in my project/libraries.

**Comment by miaowang14** [comment]
The error is coming from libnnapi_delegate_strip.so:
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite16logging_internal13MinimalLogger3LogENS_11LogSeverityEPKcz" referenced by "/data/app/org.tensorflow.lite.examples.superresolution-50dhWLUyWoZrFw8sIcvg5w==/lib/arm64/libnnapi_delegate_strip.so"...
`

I wonder how is libnnapi_delegate_strip.so generated?

**Comment by yahuuu** [comment]
I use this command first：
bazel build -c opt --repository_cache=/2cache --distdir=/2cache --config=android_arm64  --cxxopt="-std=c++14"  
 //tensorflow/lite/delegates/nnapi:nnapi_delegate 
then stip by:
aarch64-linux-android-strip

**Comment by miaowang14** [comment]
I see. Do you see similar error with the unstriped version?

**Comment by yahuuu** [comment]
Yes it is.
I hava solved this error after replace libtensorflowlite_gpu_jni.so with libtensorflowlite_gpu_delegate.so.
Can you tell me why  @miaowang14 .

**Comment by yahuuu** [comment]
I have solved the problem of dynamic libraries, just replace libtensorflowlite_gpu_jni.so with libtensorflowlite_gpu_delegate.so.
 Can you teach me how to combine those dynamic libraries?

**Comment by miaowang14** [comment]
I am not sure what is going on here with libtensorflowlite_gpu_jni, @abattery do you know?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
