### ISSUE TITLE
need convert opencv to TfLiteTensorCopyFromBuffer

### ISSUE THREAD

**Issue by budibeta** [tensorflow/tensorflow#49949]
https://github.com/tensorflow/examples/blob/master/lite/examples/super_resolution/android/app/src/main/cc/SuperResolution.cpp

why so many python or java references.
while C++ is very little.

I'm angry because why developers don't provide compiled source code, why should we do the compilation ourselves.

at this line 108 [https://github.com/tensorflow/examples/blob/master/lite/examples/super_resolution/android/app/src/main/cc/SuperResolution.cpp#L108](url) 
how to convert cv::mat to TfLiteTensorCopyFromBuffer

and then at this line 137 [https://github.com/tensorflow/examples/blob/master/lite/examples/super_resolution/android/app/src/main/cc/SuperResolution.cpp#L137](url)
how to convert TfLiteTensorCopyToBuffer to cv::mat

i hope there person, will help,
because tensorflow reference on this link [https://github.com/tensorflow/examples/blob/master/lite/examples/super_resolution/android/app/src/main/cc/SuperResolution.cpp](url)
is not structured. Thanks

**Comment by abattery** [comment]
@lintian06 could you take a look?

**Comment by budibeta** [comment]
solved
