### ISSUE TITLE
TFLM project generation fail, missing gemmlowp 

### ISSUE THREAD

**Issue by yorange1** [tensorflow/tensorflow#49945]
@tensorflow/micro

**System information**
Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): f19bfff186754e621d59a65494b04ff9ab4e9ede
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):cortex-m4

**Describe the problem**

Using project genration failed, the log shows that the gemmlowp is missing.  Maybe there's a missing gemlowp download script in the make folder?

**Please provide the exact sequence of commands/steps when you ran into the problem**
STEP1: 
python tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py --makefile_options="OPTIMIZED_KERNEL_DIR=cmsis_nn TARGET_ARCH=cortex-m4" "project"

OUTPUT:
Traceback (most recent call last):
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 193, in <module>
    _copy(src_files, dest_files)
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 105, in _copy
    shutil.copy(src, dst)
  File "/home/yc/anaconda3/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/yc/anaconda3/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'tensorflow/lite/micro/tools/make/downloads/gemmlowp/fixedpoint/fixedpoint.h'

**Comment by tilakrayal** [comment]
@youshenmebutuo ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Thanks!

**Comment by youshenmebutuo** [comment]
@tilakrayal 
Well, this issue does not require the complete code and dataset. I just want to use Project generation in TFLM to output a tree containing only the sources and headers needed to use TFLM for a specific configuration. And my steps are as follows
**STEP1:**
`git clone https://github.com/tensorflow/tensorflow.git`
**STEP2:**
`cd tensorflow`
**STEP3:**
`python3 tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py --makefile_options="OPTIMIZED_KERNEL_DIR=cmsis_nn TARGET_ARCH=cortex-m4" "project"`

The execution of **STEP3** fails, and the output is as follows:
```
Traceback (most recent call last):
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 193, in <module>
    _copy(src_files, dest_files)
  File "tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py", line 105, in _copy
    shutil.copy(src, dst)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'tensorflow/lite/micro/tools/make/downloads/gemmlowp/fixedpoint/fixedpoint.h'
```
I think there may be some problems with the  gemmlowp download script

**Comment by yorange1** [comment]
Maybe I found the cause of this problem， But should I go to the [tensorflow/tflite-micro](https://github.com/tensorflow/tflite-micro) repositories to fix this problem? @advaitjain

**Comment by advaitjain** [comment]
Yes, please feel free to make a PR in https://github.com/tensorflow/tflite-micro

**Comment by ymodak** [comment]
I believe https://github.com/tensorflow/tflite-micro/pull/138 addresses this issue. Feel free to reopen if the still persists. Thanks!
