### ISSUE TITLE
Wrong hostnames in SlurmClusterResolver from expand_range_expression

### ISSUE THREAD

**Issue by Ivo-B** [tensorflow/tensorflow#49956]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7 (Core)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.8.10
- CUDA/cuDNN version: 11.2
- GPU model and memory: Tesla V100 and 32GB

**Describe the current behavior**
We have a Slurm cluster and I wanted to train with a multi-node setup. For the cluster_resolver I used tf.distribute.cluster_resolver.SlurmClusterResolver (without any configuration) and let this class fetch the information from the Slurm environment variables. Now "expand_hostlist(hostlist)" tries to get a list of hostnames, but depending on the naming convention of the hosts this leads to the following problem:
If the input names have a leading '0' like 'n[009-011]' in the string, it will be converted to ['n9', 'n10', 'n11'].

The ultimate conversion problem occurs in expand_range_expression(range_exp), where the range string is converted to an int():
```
for i in range(int(sub_range[0]), int(sub_range[1]) + 1):
        yield i
```
This will remove the leading 0’s.

**Describe the expected behavior**
The correct conversion would be [‘n009’, ‘n010’, ‘n011’]

**[Contributing](https://www.tensorflow.org/community/contribute)** 
- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution (if contributing):
```
string_length = len(sub_range[0])
for i in range(int(sub_range[0]), int(sub_range[1]) + 1):
        yield str(i).zfill(string_length)
```

**Standalone code to reproduce the issue**
I remove all the slurm stuff, because that is not necessary to show the problem. 
[colab example](https://colab.research.google.com/drive/1cH6UKVs-fS3QlRWONjItF432f_CO4uM-?usp=sharing)

**Comment by tilakrayal** [comment]
@ymodak ,
I was able to reproduce the issue in TF v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3b947d144b836f7b8aec88110bc5172e/49956.ipynb).

**Comment by crccw** [comment]
Hi Ivo, thanks for reporting the issue. Would you like to send a PR since you already have a fix?

**Comment by Ivo-B** [comment]
Hi @crccw, sure I can prepare a PR. I will also include such a case in the unit test.

**Comment by mypey** [comment]
Hi,
any update about this issue?
The problem still happens with tensorflow 2.7.0. Even on the master branch, the integer conversion is still there: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py#L63-L64.
Thanks

**Comment by tilakrayal** [comment]
@Ivo-B,
I tried to execute the mentioned code with the tf-nightly(2.15.0-dev20230918) and observed the output of the code is similar in both the cases. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/eb06beaa976c91207e9762bb25d91a3e/untitled1.ipynb). 

![image](https://github.com/tensorflow/tensorflow/assets/81610181/f5ee0f81-9def-4438-a27b-363ffdc2cb94)

Thank you!
