### ISSUE TITLE
Partial training of im2txt runs only 1 step

### ISSUE THREAD

**Issue by cescamilla** [tensorflow/tensorflow#4995]
After running an initial training of model 'im2txt' of 5100 steps, when trying to run more steps, it only runs one and saves the model, i've tried using 10 , 100 and 5000 steps

model url: https://github.com/tensorflow/models/tree/master/im2txt

Params:
--input_file_pattern="/Users/carlosescamilla/im2text/data/mscoco/train-?????-of-00256" 
--inception_checkpoint_file="/Users/carlosescamilla/im2text/data/inception_v3.ckpt" 
--train_dir="/Users/carlosescamilla/im2text/model/train"
 --train_inception=false 
--number_of_steps=100

Output:

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.dylib locally
INFO:tensorflow:Prefetching values from 256 files matching /Users/carlosescamilla/im2text/data/mscoco/train-?????-of-00256
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] OS X does not support NUMA - returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GT 750M
major: 3 minor: 0 memoryClockRate (GHz) 0.9255
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.77GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0)
INFO:tensorflow:Starting Session.
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 759.69MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 759.69MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 1.01GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 1.01GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 759.69MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 759.69MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 1.51GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 1.51GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 2.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
INFO:tensorflow:global step 5111: loss = 3.0275 (45.44 sec/step)
INFO:tensorflow:Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.

### Environment info
MacOS 10.11.6 El Capitan

Installed version of CUDA and cuDNN: 
CUDA Toolkit 7.5
cuDNN 5005

installed with pip3
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc0-py3-none-any.whl

**Comment by jart** [comment]
How much RAM do you have? We frequently encounter issues where people are running the stuff in tensorflow/models on systems that don't have a generous amount of resources.

**Comment by cescamilla** [comment]
i have 2 GB on GPU and 16 GB on RAM, i already tried running the training process on CPU only and it fails too after the initial steps

**Comment by drpngx** [comment]
Can you try --number_of_steps=5100 instead?

**Comment by cescamilla** [comment]
i have uninstalled tensorflow from my computer due to this issue, maybe in a near future i can give it another try.
