### ISSUE TITLE
Tensorflow Decove Wav

### ISSUE THREAD

**Issue by Astrohaker** [tensorflow/tensorflow#49950]
Please, help me with tf.audio.decode_wav:https://www.tensorflow.org/api_docs/python/tf/audio/decode_wav
(The -32768 to 32767 signed 16-bit values will be scaled to -1.0 to 1.0 in  float tensor.)

I want to read 16bit PCM wav file as 8 bit PCM (The -128 to 127 and scaled to -1.0 to 1.0 in  float tensor)

What should i do?

**Comment by UsharaniPagadala** [comment]
@Astrohaker 
Could you please share standalone code/colab gist to analyse the issue reported and tf vesion used along with all the dependencies.Thanks

**Comment by 8bitmp3** [comment]
Have you tried lowering the precision first before attempting to tensorize the waveforms ? https://stackoverflow.com/questions/44812553/how-to-convert-a-24-bit-wav-file-to-16-or-32-bit-files-in-python3

**Comment by herbiel** [comment]
can i Tensorflow Decove Wav by 8bit?
