### ISSUE TITLE
tflite esrgan super image resolution limited 50x50

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#49961]
how to train super image resolution, that accept any input image

**Comment by abattery** [comment]
@lintian06 could you take a look?

**Comment by cybergeekgyan** [comment]
I would like to work on this issue on improving the performance of the Super Resolution App on Android and iOS.
Can You assign this issue to me @lintian06 , I would like to focus on training images to a super-resolution.
Can you elaborate on the issue a bit to get me started @abattery

**Comment by pjpratik** [comment]
Hi, the [example](https://www.tensorflow.org/lite/examples/super_resolution/overview) for  ESR GAN super resolution on TFLite is using 50x50 input considering the model's performance and inference speeds.

As mentioned in the [example](https://www.tensorflow.org/lite/examples/super_resolution/overview), to increase the input size, we need to re-convert or re-train the original model.

Thanks.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!
