### ISSUE TITLE
'tf.Mul' op is neither a custom op nor a flex op when I convert saved_model to tflite model

### ISSUE THREAD

**Issue by jiangjing1989** [tensorflow/tensorflow#49969]
Environment is NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0 tensorflow-2.5/2.6 python3.8.

My net contain the ops: matmul, multiply. When I convert the saved model to tflite model, it report that

<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite(callsite(callsite("Mul_1@__inference_call_8437" at "conformer_encoder/conformer_block_3/mhsa_module/multi_head_attention_3/StatefulPartitionedCall@__inference_call_8638") at "transducer_encoder/StatefulPartitionedCall@__inference__wrapped_model_8931") at "StatefulPartitionedCall@__inference_signature_wrapper_18974") at "StatefulPartitionedCall")): 'tf.Mul' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: Mul
Details:
        tf.Mul {device = ""}

How can l solve it?

**Comment by abattery** [comment]
Please consider using the Select TF option to fallback unsupported TF ops in the TensorFlow Lite builtin op set.

https://www.tensorflow.org/lite/guide/ops_select
