### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (3 != 4)Node number 21 (PAD) failed to prepare.

### ISSUE THREAD

**Issue by asimsultan** [tensorflow/tensorflow#49979]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version 2.4

I have converted the mobilebert model to tflite and now I want to perform inference on that, for a single value, it works fine but for a batch, I am reshaping the input size of the tensor. I am running the following lines of code but it gives me the dimension error.

Code I am running: 
```
input_data10 = np.expand_dims(input_text[1:1001], axis=1)
interpreter.resize_tensor_input(input_details[0]['index'], [1000, 1, 100])
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]['index'], input_data10)
interpreter.allocate_tensors()
interpreter.invoke()
```

Error I am receiving

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-65-7d35ed1dfe14> in <module>
----> 1 interpreter.invoke()

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in invoke(self)
    538     """
    539     self._ensure_safe()
--> 540     self._interpreter.Invoke()
    541 
    542   def reset_all_variables(self):

RuntimeError: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (3 != 4)Node number 21 (PAD) failed to prepare.

``

**Comment by abattery** [comment]
Please make sure that the above TFLite model is capable of handling multiple batch inputs. Looks like the above model is designed and converted to handle only one input. However, due to a lack of information about the model details, it is really hard to give any other suggestions. If possible, please share a minimal and reproducible step for the above issue or the above TFLite model for debugging purpose.

**Comment by abattery** [comment]
It is possible to see the input tensor spec by printing the input tensor details. E.g., `interpreter.get_input_details()`

**Comment by asimsultan** [comment]
Hey @abattery, So when I go interpreter.get_input_details(), I get the following results.

[{'name': 'input_ids',
  'index': 0,
  'shape': array([1000,    1,  100], dtype=int32),
  'shape_signature': array([ -1, 100], dtype=int32),
  'dtype': numpy.int32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]


Here the shape is [1000, 1,100] since I resized it to pass it 1000 inputs at once where each input is of the shape (1,100) but I dont know why on interpreter.invoke, it gives the following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-7d35ed1dfe14> in <module>
----> 1 interpreter.invoke()

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in invoke(self)
    831     """
    832     self._ensure_safe()
--> 833     self._interpreter.Invoke()
    834 
    835   def reset_all_variables(self):

RuntimeError: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (3 != 4)Node number 21 (PAD) failed to prepare.

**Comment by asimsultan** [comment]
Also to add one more thing, I used TFMobileBertModel for this text classification model and then I converted that model using tflite and then I am performing inferece on that, for a single input its working fine but when i resize the input tensor to pass 1000 inputs, it gives the error.

**Comment by abattery** [comment]
Looks like the above model requires the following shape restrictions:

```'shape_signature': array([ -1, 100], dtype=int32),```

Probably, the right input shape is [1000, 100] for the batch case.

**Comment by asimsultan** [comment]
So how should i resize the input tensor then?
Currently I am doing it as: 

interpreter.resize_tensor_input(input_details[0]['index'], [1000, 1, 100])

What would be the right way of doing it?
Also is this model to support a batch of input to be inferenced?

**Comment by abattery** [comment]
According to the shape_signature field, the batched input size should be resized as follows:

`interpreter.resize_tensor_input(input_details[0]['index'], [1000, 100])`

The batched input should be prepared to follow the above shape [1000, 100].

**Comment by asimsultan** [comment]
Okay I entered the line that you mentioned and I got the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-ce0005dcf216> in <module>
----> 1 interpreter.set_tensor(input_details[0]['index'], input_data10)

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in set_tensor(self, tensor_index, value)
    570       ValueError: If the interpreter could not set the tensor.
    571     """
--> 572     self._interpreter.SetTensor(tensor_index, value)
    573 
    574   def resize_tensor_input(self, input_index, tensor_size, strict=False):

ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 2 for input 0.

The reason is because the input is (1,100) initially for 1 input i.e. in other words, 1 row and 100 columns but I needed to pass 1000 inputs at once.

Let me be a little more detailed here:

This was the initial code and it gave me the shape as:
input_data = np.expand_dims(input_text[0], axis=0)
(1,100)

but I wanted to pass 1000 values and changed the above code to 
input_data = np.expand_dims(input_text[0:1000], axis=0)
which gave me the following shape:

for axis =0: (1, 1000, 100) 
and gave me 
for axis =1: (1000, 1, 100)

Now I understood your point where you said to pass [1000,100] to resize the tensor because obviously intially it was [1,100] for 1 input but for 1000 inputs, I had to change it to [1000,100] but the problem arise from the input_data where I assign 1000 values and expand them using np.expands.

**Comment by abattery** [comment]
This is an intended behavior. You need to provide the input with [1000, 100] not [1000, 1, 100]. As the error described, the set_tensor method invocation needs 2 dimension but the given tensor data has 3 dimension.

**Comment by asimsultan** [comment]
Perfect! I got it working from that cell, some how, I tried to change the shape to [1000, 100] and now when I run interpreter.invoke(), It did show me result, but now I tried it and it killed the kernel. I closed all the kernels and ran this one again and on interpreter.invoke(), it kills the kernel again, Idk why it is happening now.

**Comment by abattery** [comment]
Great to hear that the interpreter works for you. Please upload a new issue to keep each issue focused.

**Comment by khirmansaleem** [comment]
I am using DenseNet-121 model and converted it to model.tflite to perform inference and i am experiencing following error:          java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 1)
Node number 0 (PAD) failed to prepare.
	at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensors(Native Method)
	at org.tensorflow.lite.NativeInterpreterWrapper.allocateTensorsIfNeeded(NativeInterpreterWrapper.java:308)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:248)
	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:101)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:77)
	at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:94)
	at org.tensorflow.lite.Interpreter.run(Interpreter.java:77)
	at com.example.appleleafdiseasedetection.DiseaseDetector$2.onClick(DiseaseDetector.java:72)
	at android.view.View.performClick(View.java:7743)
	at android.view.View.performClickInternal(View.java:7720)
	at android.view.View.access$3700(View.java:854)
	at android.view.View$PerformClick.run(View.java:29111)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8309)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) ,plz suggest me some solutions
