### ISSUE TITLE
MirroredStrategy throws warning during startup

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#49980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0 and 2.6.0-dev20210602
- Python version: 3.7 and 3.8

**Describe the current behavior**
When instantiating a `MirroredStrategy` at the top of a program using:
```python
import tensorflow as tf

tf.distribute.MirroredStrategy()
```
It throws the following warning suggesting users that they might run into performance problems:
```
WARNING:tensorflow:Collective ops is not configured at program startup. Some performance features may not be enabled.
```
This warning is thrown in
https://github.com/tensorflow/tensorflow/blob/280d27a99d5057f3ef421dd684fbb327cd1ff20a/tensorflow/python/distribute/mirrored_strategy.py#L375-L380
and it will be thrown as well even if the code is running directly after importing TensorFlow.

**Describe the expected behavior**

No warning should be thrown by default or the warning should include actionable items for the user to resolve this issue.

**Standalone code to reproduce the issue**
Checkout [this notebook for full reproduction](https://colab.research.google.com/drive/1h5b4Ve71n0e-VDngHRDMUL4CHwGqxvPE?usp=sharing).

**Comment by tilakrayal** [comment]
@ymodak ,
I was able to reproduce the issue in tf v2.5, nightly and in v2.4, code executed with warning.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7c5d5f7f1abfc90d0756e2fa184e693d/49980.ipynb).

**Comment by SysuJayce** [comment]
So what's the solution for this warning?

Any updates?

**Comment by lgeiger** [comment]
> So what's the solution for this warning?

The warning was removed in a27e3951d6a1f2cc4be53204e4d9e0da02e11830 which will be part of the 2.6 release.

For TF 2.5 it looks like it is save to ignore this warning for now (if I read @crccw's commit message correctly)

**Comment by SysuJayce** [comment]
Hi @lgeiger , thanks for the info!

May I ask you another question about tf distributed training?

In my practice, I found that it takes a long time to start training with MirroredStrategy.

I am using keras.model.fit() to train my model, and the program stucked after printing `Epoch 1/xx` for a LONG time.
