### ISSUE TITLE
Please make the documentation headlines linkable/clickable

### ISSUE THREAD

**Issue by 3rd3** [tensorflow/tensorflow#4998]
That would make it easier to refer to particular parts/anchors in the documentation.

**Comment by jart** [comment]
This is a terrific idea. Thank you for proposing it. Having anchor links for headers is a very common practice. Let's see what our documentation czar @xmbrst thinks.

**Comment by aselle** [comment]
This seems like a good idea that we haven't done even in the new docs.

**Comment by wolffg** [comment]
Sorry, what are we talking about here?  We provide header/subhead links, like this:

https://www.tensorflow.org/get_started/get_started#importing_tensorflow

All the links are available on the table of contents on the right.

Can you clarify which headers you want links to?

**Comment by 3rd3** [comment]
Indeed, the table of contents basically implements this feature. This issue remains a minor feature request that the headers which are already linkable via the table of contents should be wrapped in anchor elements to make them clickable. This is sometimes implemented by displaying a chain/link symbol 🔗 on the MouseOver event (e.g. in the [PyTorch docs](http://pytorch.org/docs/torch.html#torch.add)). That saves the step of scanning the table of contents for the particular section that one wants to link to.

**Comment by wolffg** [comment]
I will suggest this to the team that manages our CMS, but unless they implement it, we are not going to do it given there's an immediate workaround.  I'm closing the bug against TensorFlow, with the caveat that I will file it against the CMS on another tracker.
