### ISSUE TITLE
[bugs] TensorFlow ci_build docker bazel extration error

### ISSUE THREAD

**Issue by alrojo** [tensorflow/tensorflow#4999]
Within the past week I started getting a bazel extraction error when trying to build my docker image for testing.
Below is a reproducible description of the error.

Generic Ubuntu 14.04 on AWS (c4.4xlarge)
```
$uname -r
3.13.0-91-generic
```
Install docker according to installation instructions at [docker ubuntu](https://docs.docker.com/engine/installation/linux/ubuntulinux/) with a docker group added to the default user.
```
$sudo apt-get install git
$git clone https://github.com/tensorflow/tensorflow.git
$cd tensorflow
$tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/...
```
I then receive the following error
```
Step 10 : RUN /install/install_buildifier.sh
 ---> Running in f38c73826642
Cloning into 'buildifier'...
/buildifier /
Extracting Bazel installation...
.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': Error cloning repository: https://github.com/bazelbuild/rules_go.git: cannot open git-upload-pack caused by https://github.com/bazelbuild/rules_go.git: cannot open git-upload-pack caused by java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty.
____Elapsed time: 1.730s
The command '/bin/sh -c /install/install_buildifier.sh' returned a non-zero code: 1
ERROR: docker build failed. Dockerfile is at /home/ubuntu/tensorflow/tensorflow/tools/ci_build/Dockerfile.cpu
```

**Comment by jart** [comment]
This bug is most likely upstream. jgit is very buggy and prone to random failures such as these. I filed bazelbuild/buildifier#18. I'm not sure what to recommend for you as a workaround at this moment. But thank you for bringing this to our attention.

**Comment by gunan** [comment]
This bug is not in tensorflow code, but I may have a possible solution.
After installing JDK on your VM, could you run the two following commands?
These may solve your problems:

$ sudo apt-get install ca-certificates-java
$ sudo update-ca-certificates -f

This seems to fix the flakes we see in our own CI builds ( #5041 ) but if you want a fix faster you may try the two above commands.
