### ISSUE TITLE
TensorFlow Profiler stuck loading data

### ISSUE THREAD

**Issue by aecelaya** [tensorflow/tensorflow#50016]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Tesla T4, 16 GB

**Describe the current behavior**
When trying to use the TensorFlow Profiler on a GPU-enabled Colab notebook, the TensorBoard page displays the message "Loading data" and appears to be stuck there.
<img width="1008" alt="Screen Shot 2021-06-02 at 9 26 44 PM" src="https://user-images.githubusercontent.com/12498403/120582805-bc161d80-c3f2-11eb-9367-68ec7f9795c5.png">

**Describe the expected behavior**
The TensorFlow Profiler should appear as a TensorBoard page.
<img width="850" alt="Screen Shot 2021-06-02 at 10 38 13 PM" src="https://user-images.githubusercontent.com/12498403/120583129-4494be00-c3f3-11eb-9a70-a6720eb74de7.png">

**Standalone code to reproduce the issue**
This issue can be reproduced by running the TensorFlow Profiler tutorial notebook.
https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb

**Comment by UsharaniPagadala** [comment]
@aecelaya 
I did not face any loading issue when I reproduced the colab shared.Please find the [gist](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb#scrollTo=ZlRwCDoVinHV) .Thanks
