### ISSUE TITLE
tf.linalg.eigh yields invalid eigensystem when used inside a decorated tf.function with jitcompile=True flag

### ISSUE THREAD

**Issue by matthew-pickett** [tensorflow/tensorflow#50017]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 20.04 host using docker image tensorflow/tensorflow:2.5.0-gpu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
docker image tag 2.5.0-gpu
- TensorFlow version (use command below):
v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0

- Python version:
3.6.9
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudart.so.11.2.152
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudart_static.a

- GPU model and memory:
NVIDIA RTX 2070 8 GB

**Describe the current behavior**
Using the jitcompile=True flag for a decorated function that uses tf.linalg.eigh returns an incorrect solution. Removing the flag yields a correct solution. Note that this did work in TF 2.4.1 using the same code with experimentalcompile=True. It also fails for when CUDA_VISIBLE_DEVICES=-1 is to disable GPU evaluation.

**Describe the expected behavior**

The code snippet pasted below, which tests that the eigen system is a valid solution, should not raise an error. 

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

Possibly, if I can get some guidance on where the issue might be. As it stands I wouldn't know where to begin.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
# fails both with and without this environment variable set to disable GPU evaluation
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import numpy as np
import tensorflow as tf


a_mat = np.array([
    [0., -1., -1.,  1.],
    [-1.,  0.,  1., -1.],
    [-1.,  1.,  0., -1.],
    [1., -1., -1.,  0.]], dtype=np.float32)


@tf.function(input_signature=[
    tf.TensorSpec(None, dtype=tf.float32)],
    jit_compile=False)
def eigh_uncompiled(arg):
    return tf.linalg.eigh(arg)


@tf.function(input_signature=[
    tf.TensorSpec(None, dtype=tf.float32)],
    jit_compile=True)
def eigh_compiled(arg):
    return tf.linalg.eigh(arg)


for eigh in [np.linalg.eigh, eigh_uncompiled, eigh_compiled]:
    val, vec = eigh(a_mat)
    # assert A.x = lambda x for eigen system
    print(tf.linalg.matmul(a_mat, vec) - val[tf.newaxis] * vec)
    if not np.allclose(tf.linalg.matmul(a_mat, vec), val[tf.newaxis] * vec, atol=1e-6):
        raise AssertionError(f'Test fails for function {eigh.__name__}')
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

N/A. Should be easy to reproduce with the above code snippet.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in tf v2.5,v2.4 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/00bde45762a0c845b374e59752ef0530/50017.ipynb)

**Comment by matthew-pickett** [comment]
As a followup, this particular test matrix seems to be a corner case but one that is actually encountered in my application. The test actually passes when the matrix under test is a randomly generated self-adjoint matrix.

For example,
```
g_mat = np.random.normal(0, 1, (4, 4)).astype(np.float32)
a_mat = g_mat*g_mat.T
```

It fails again, however, if the diagonal of the random test matrix is set to all zeros, which might be a clue:
```
g_mat = np.random.normal(0, 1, (4, 4)).astype(np.float32)
a_mat = g_mat*g_mat.T
for n in range(4):
    a_mat[n, n] = 0.
```

**Comment by seanmor5** [comment]
Hi everyone,

Just jumping in to point out this bug is not present in TF 2.4 (`jit_compile` is not a valid option for `tf.function` in TF 2.4):

```python
import numpy as np
import tensorflow as tf


a_mat = np.array([
    [0., -1., -1.,  1.],
    [-1.,  0.,  1., -1.],
    [-1.,  1.,  0., -1.],
    [1., -1., -1.,  0.]], dtype=np.float32)


@tf.function(input_signature=[
    tf.TensorSpec(None, dtype=tf.float32)],
    experimental_compile=False)
def eigh_uncompiled(arg):
    return tf.linalg.eigh(arg)


@tf.function(input_signature=[
    tf.TensorSpec(None, dtype=tf.float32)],
    experimental_compile=True)
def eigh_compiled(arg):
    return tf.linalg.eigh(arg)


for eigh in [np.linalg.eigh, eigh_uncompiled, eigh_compiled]:
    val, vec = eigh(a_mat)
    # assert A.x = lambda x for eigen system
    print(tf.linalg.matmul(a_mat, vec) - val[tf.newaxis] * vec)
    if not np.allclose(tf.linalg.matmul(a_mat, vec), val[tf.newaxis] * vec, atol=1e-6):
        raise AssertionError(f'Test fails for function {eigh.__name__}')
```

```
tf.Tensor(
[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-2.9802322e-08  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-5.9604645e-08  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 1.7881393e-07 -1.4901161e-08  0.0000000e+00 -2.3841858e-07]
 [-1.7881393e-07  0.0000000e+00 -1.4901161e-08  2.3841858e-07]
 [-1.4901161e-07  0.0000000e+00  0.0000000e+00  2.3841858e-07]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  4.7683716e-07]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 8.9406967e-08 -1.1920929e-07 -1.1920929e-07  2.3841858e-07]
 [-8.9406967e-08  1.1920929e-07 -1.1920929e-07 -2.3841858e-07]
 [-1.1920929e-07 -5.9604645e-08  0.0000000e+00 -1.1920929e-07]
 [ 1.1920929e-07 -5.9604645e-08  0.0000000e+00  1.1920929e-07]], shape=(4, 4), dtype=float32)
```

Based on the fact that `jit_compile` is an XLA thing, the issue probably somewhere in the `eigh` kernel generated by XLA? Though, the issue is not present in JAX:

```python
from jax import jit
import jax.numpy as jnp
import numpy as np

a_mat = np.array([
    [0., -1., -1.,  1.],
    [-1.,  0.,  1., -1.],
    [-1.,  1.,  0., -1.],
    [1., -1., -1.,  0.]], dtype=np.float32)

@jit
def eigh_jit(arg):
  return jnp.linalg.eigh(arg)

val, vec = eigh_jit(a_mat)
print(jnp.matmul(a_mat, vec) - jnp.expand_dims(val, axis=0) * vec)
if not np.allclose(jnp.matmul(a_mat, vec), jnp.expand_dims(val, axis=0) * vec, atol=1e-6):
  raise AssertionError(f'Test fails for JAX')
```

But I believe JAX uses a Custom Call for it's `eigh` implementation rather than something else.

Is it possible this issue is related to the addition of `eigh_expander.h` by @hawkinsp in March (https://github.com/tensorflow/tensorflow/commits/master/tensorflow/compiler/xla/service/eigh_expander.h)?

**Comment by hawkinsp** [comment]
I agree, this is a bug. I will look into it. Something looks off about the 2x2 Jacobi rotations generated for this special case.

Note that this code path isn't a particularly good one to be using on CPU or GPU, so even if I fix this issue, you should not expect good performance from it on those platforms. TF needs to do the same thing JAX does here (call into an optimized kernel).

**Comment by hawkinsp** [comment]
This should now be fixed at head.
