### ISSUE TITLE
tf.contrib.framework.assign_from_variables in Tensorflow 2

### ISSUE THREAD

**Issue by ahbe** [tensorflow/tensorflow#50028]
I'm running an inference model that used tf1, and I've changed the code to tf2 but I can't find a proper tf2 alternative to contrib.framework.assign_from_variables anywhere. I've tried tf.compat.v1 but still the same issue.

**Comment by ahbe** [comment]
Just found out the solution ; just use tf_slim

**Comment by tilakrayal** [comment]
@ahbe ,

Please refer this link for info on contrib.[Link](https://www.tensorflow.org/guide/migrate).It helps.Thanks

**Comment by tilakrayal** [comment]
@ahbe ,

Please feel free to move this issue to closed status if the issue has resolved.Thanks!
