### ISSUE TITLE
problem with tf.image.ssim_multiscale 's filter size

### ISSUE THREAD

**Issue by poseidonchan** [tensorflow/tensorflow#50023]
when i use this function(with filter size=11) to compare two batches of images' (width:100,height:100)multiscale ssim score, i got error like 'Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: 10, 7, 7, 3 11'. I think this is due to the wrong filter size choosing, since 100 > 11, i think there is something wrong when you implement this function

**Comment by lovefromCode** [comment]
ghgch

**Comment by tilakrayal** [comment]
@poseidonchan ,

We see that the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.

Thanks!

**Comment by tilakrayal** [comment]
Can you please go through the issues with similar references.It helps.[Link1](https://github.com/tensorflow/tensorflow/issues/33840#issuecomment-633715778),[Link2](https://stackoverflow.com/questions/65484160/invalidargumenterror-expected-tf-tensorfalse-shape-dtype-bool-to-be-tr/65486274).
Thanks!

**Comment by poseidonchan** [comment]
tensorflow 2.4, Linux Ubuntu 20.04, no cuda
enhanced_pic is a [batch_size, height, width, channel] numpy ndarray, dslr_pic is the same
```python
tf.image.ssim_multiscale(enhanced_pic, dslr_pic, max_val=1, filter_size=11)
```
You may test this function with the same array [batch_size, 100, 100, 3]

**Comment by poseidonchan** [comment]
I make a colab example, here is the link <https://colab.research.google.com/drive/1gTt4p824c-rB1-TPLKg0i5mcmjMX99ur?usp=sharing>
