### ISSUE TITLE
Comparison of conversion and int8 conversion for TFLite 

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#50025]
Hi, I'm working on converting trained tensorflow model to uint8 and int8. But I found that the results between the two models are different, the followings are settings of conversion:

### 1. System information

- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 1.15.0

### 2. Code
[int8 conversion]
```
    converter.optimizations = [tf.lite.Optimize.DEFAULT] 
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8 
    converter.inference_output_type = tf.int8 
    converter.representative_dataset = representative_data_gen
    tflite_int8_model = converter.convert()
```

[uint8 conversion]
```
    converter.target_ops = [tf.compat.v1.lite.OpsSet.TFLITE_BUILTINS, tf.compat.v1.lite.OpsSet.SELECT_TF_OPS]
    converter.inference_type = tf.uint8

    input_arrays = converter.get_input_arrays()
    converter.quantized_input_stats = {input_arrays[0]: (127, 127)}    
    converter.default_ranges_stats = (-128, 127) 
    tflite_uint8_model = converter.convert()
```

### 3. Failure after conversion
The results between the int8 and uint8 models are different
(int 8 model with representative dataset)
![int8_with_representative_dataset](https://user-images.githubusercontent.com/8951991/120624329-2bdbe500-c493-11eb-94a8-4f24ffccad42.png)

(uint8 model with input_stats and ranges_stats)
![uint8_with_range](https://user-images.githubusercontent.com/8951991/120624431-47df8680-c493-11eb-9cbe-cdef9949518e.png)

 ### 5. (optional) Any other info
I also tried to applying `converter.optimizations = [tf.lite.Optimize.DEFAULT], converter.representative_dataset ` and `converter.quantized_input_stats, converter.default_ranges_stats` simultaneously, but the generated model contains two quantize layers, which generates wrong results.
![wrong_conversion](https://user-images.githubusercontent.com/8951991/120625297-24690b80-c494-11eb-86b0-8b3bdc16fa97.png)

Is it possible to generate uint8 models with `converter.representative_dataset ` with all layers are quantized as uint8 instead of int8?

Best regards

**Comment by Xhark** [comment]
@daverim Hi david, you may have know more details about this. Would you please take a look?
