### ISSUE TITLE
Convert tflite output location to screen location

### ISSUE THREAD

**Issue by shadmanadman** [tensorflow/tensorflow#50022]
Hi everyone. I have an android app that use a detection model. the model is working fine. I just have problem with converting the output location to screen location that user can see. I used the tflite android example and extract some code out of it. but the conversion is not correct. here is my function to converting:

```
`private fun mapOutputCoordinates(
        location: RectF,
        rotationDegrees: Int,
        width: Int,
        height: Int
    ): RectF {
        val frameToCropTransform = getTransformationMatrix(
            width,
            height,
            ModelInputSize,
            ModelInputSize,
            rotationDegrees,
            MAINTAIN_ASPECT
        )

        val cropToFrameTransform = Matrix()
        frameToCropTransform.invert(cropToFrameTransform)

        cropToFrameTransform.mapRect(location)
        val rotated = rotationDegrees % 180 == 90

        val multiplier = min(
            camera.height / (if (rotated) width else height).toFloat(),
            camera.width / (if (rotated) height else width).toFloat()
        )
        val frameToCanvasMatrix = getTransformationMatrix(
            width,
            height,
            (multiplier * if (rotated) height else width).toInt(),
            (multiplier * if (rotated) width else height).toInt(),
            rotationDegrees,
            false
        )
        //frameToCanvasMatrix.mapRect(location)
        val rgbFrameToScreen = Matrix(frameToCanvasMatrix)

        val detectionFrameRect = RectF(location)

        val detectionScreenRect = RectF()
        rgbFrameToScreen.mapRect(detectionScreenRect, detectionFrameRect)
        return detectionScreenRect
    }
}`
```

I don't know if this place is the right place for asking this question but i'm straggling with this for over a weak.

**Comment by tilakrayal** [comment]
@shadmanadman ,

Please fill the issue template and  in order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.

Thanks!

**Comment by xunkai55** [comment]
It's also relevant with how the detection model encodes bounding boxes (absolute coordinates, or relative ones), and how you preprocess the image (how you resize - any cropping? resizing maintaining/not maintaining aspect?)

You can also try `ImageProcessor` in TFLite Support library, which has API to transfer the location back to original coordinate system. (link: https://github.com/tensorflow/tflite-support/blob/cf5d79051856f4b06e29bb2a2e3361bfe748fc2e/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/image/ImageProcessor.java#L71)

Examples using `ImageProcessor`: https://github.com/tensorflow/examples/blob/a228a3460f3fdd8edee9e8b061a08ffc92629907/lite/examples/image_classification/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L308
