### ISSUE TITLE
Tensorflow 1.14.0 C++ can't get GPU device

### ISSUE THREAD

**Issue by silingtong123** [tensorflow/tensorflow#50027]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux centos 7.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version:  3.6
- Installed using virtualenv? pip? conda?: None
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): 4.85
- CUDA/cuDNN version: CUDA 10.0, cudnn 7.4
- GPU model and memory: Tesla T4

**Describe the problem**
 - run service can't get GPU device by use libtensorflow_cc.so and libtensorflow_framework.so.
    bazel build tensorflow_cc
- python3.6:
    - print(device_lib.list_local_devices())
        - [name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7969440054434969841
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 13181855577668801818
physical_device_desc: "device: XLA_GPU device"
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 13243497781981531688
physical_device_desc: "device: XLA_CPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 14892338381
locality {
  bus_id: 1
  links {
  }
}
incarnation: 8775195624210653350
physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:07.0, compute capability: 7.5"
]

- C++:
     - std::vector<tensorflow::DeviceAttributes> resp;
     - TF_CHECK_OK(session_->ListDevices(&resp));
     - for (const auto& dev : resp)   {std::cout<< "dev type = "<<dev.device_type()<<std::endl;}
         - dev type = CPU
dev type = XLA_CPU

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
None

**Comment by Saduf2019** [comment]
@silingtong123 
Kindly upgrade to 2.x as there is no active support for 1.x, and let us know if the issue persist.
