### ISSUE TITLE
C API crashes on simple problems  

### ISSUE THREAD

**Issue by sergiyprotsiv** [tensorflow/tensorflow#5003]
I am trying to incorporate Tensorflow into a larger OS X project, so using the stand-alone static library build (from contrib/makefile) and C API.

Once all the linking issues are resolved, the simplest Tensorflow programs compile fine, but do not run. I have so far found two issues when creating operations similarly to the c_api_test file:

- When adding a constant Operation, Tensorflow crashes on exit from TF_SetAttrTensor(). The issue is that the managed buffer is deallocated, but still has refcount of 1. I am not sure why this happens since the managed buffer should supposedly be passed to the node_builder (which should retain the reference), but the buffer still gets deallocated.

- Trying to work around that, it almost immediately hits another issue: TF_FinishOperation crashes because node_builder.Finalize call does not set the props of the Node and so ret->name() returns NULL.

I do not know the codebase well enough (just started today), so perhaps you could point me to a possible underlying cause.

Using OS X 10.11.6, Xcode 8, libc++ and C++14. Tensorflow current as of October 16.

**Comment by jart** [comment]
One thing you might be able to do is build the shared library with Bazel and then link that into your OS X project. If this does not work, please let us know, and we'll reopen the issue.

We appreciate you reporting this issue, but please take into consideration that the contrib/makefile build system is community supported on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Although we will happily review any PRs improving it.

**Comment by rchipka** [comment]
@sergiyprotsiv Were you able to solve the second issue related to TF_FinishOperation? I'm having the same problem.

**Comment by sergiyprotsiv** [comment]
The issue was resolved by building TF with Bazel as the developers suggested - none of the issues were present and I did not investigate the static build after that

**Comment by rchipka** [comment]
Thanks! I really want to make the static builds work for my application so I think I'll investigate a bit more.
