### ISSUE TITLE
Tensorflow 2.5 wheels depend on an unreleased keras version and restrict numpy to 1.19

### ISSUE THREAD

**Issue by maxnoe** [tensorflow/tensorflow#50042]
The published wheels for tensorflow 2.5 depend on a nightly dev version of keras and restrict numpy to 1.19.x.

Depending on a nightly build of some package in a stable version is just, in lack of a better word, crazy. 

The dependency on a specific numpy major version is maybe necessary, but is it really impossible to have a wheel that supports numpy >1.19 (including the current 1.20 release)?

```
❯ unzip -p tensorflow-2.5.0-cp37-cp37m-macosx_10_11_x86_64.whl  tensorflow-2.5.0.dist-info/METADATA | grep Requires-Dist
Requires-Dist: numpy (~=1.19.2)
Requires-Dist: absl-py (~=0.10)
Requires-Dist: astunparse (~=1.6.3)
Requires-Dist: flatbuffers (~=1.12.0)
Requires-Dist: google-pasta (~=0.2)
Requires-Dist: h5py (~=3.1.0)
Requires-Dist: keras-preprocessing (~=1.1.2)
Requires-Dist: opt-einsum (~=3.3.0)
Requires-Dist: protobuf (>=3.9.2)
Requires-Dist: six (~=1.15.0)
Requires-Dist: termcolor (~=1.1.0)
Requires-Dist: typing-extensions (~=3.7.4)
Requires-Dist: wheel (~=0.35)
Requires-Dist: wrapt (~=1.12.1)
Requires-Dist: gast (==0.4.0)
Requires-Dist: tensorboard (~=2.5)
Requires-Dist: tensorflow-estimator (<2.6.0,>=2.5.0rc0)
Requires-Dist: keras-nightly (~=2.5.0.dev)
Requires-Dist: grpcio (~=1.34.0)
```

Most version requirements here seem rather restrictive.

**Comment by CMCDragonkai** [comment]
Where is the source code for keras-nightly? I'm trying to see where it is actually built? It seems necessary to be able to package TF 2.5.0 into Nixpkgs.

**Comment by bnavigator** [comment]
Regarding numpy 1.20: See #47691, #48918, #48935. Please help in advocating to get it unpinned.

**Comment by mihaimaruseac** [comment]
Keras-nightly is an unfortunate oversight, but given the version number it's a pinned version. In the future we will not have this anymore. CC @qlzh727 

@bnavigator, we have already explained what are the blockers for numpy 1.20. Piling on other issues to ask for support is a little bit against the code of conduct, I'd say.

**Comment by mihaimaruseac** [comment]
@CMCDragonkai keras wheels are built from https://github.com/keras-team/keras

See also https://github.com/tensorflow/community/blob/master/rfcs/20200205-standalone-keras-repository.md

**Comment by diviramon** [comment]
Can it be changed the Keras nightly dependency? It really is stopping my team from using 2.5. Thanks!

**Comment by jvishnuvardhan** [comment]
@maxnoe Is this still an issue for you? numpy 1.20 is compatible with latest TF version.

Please verify once and close the issue if this was resolved. Thanks!
