### ISSUE TITLE
Python: Tensorflow 2.5 requires grpcio 1.34

### ISSUE THREAD

**Issue by gitpushdashf** [tensorflow/tensorflow#50045]
Tensorflow 2.5.0 requires grpcio 1.34, which prevents installation with some other packages that require 1.37 and later.

Related: #48109, https://github.com/tensorflow/tensorflow/commit/f1a51f07937e28e3194b3f8964a06f8390e798c3#diff-f526feeafa1000c4773410bdc5417c4022cb2c7b686ae658b629beb541ae9112

It seems like the above commit should've landed for 2.5.0, but it appears to not be that way in pypi.

Log output from Poetry:

```
(snip)
And because tensorflow (2.5.0) depends on grpcio (>=1.34.0,<1.35.0),
(snip)
```

**Comment by ymodak** [comment]
On master I see https://github.com/tensorflow/tensorflow/blob/53931158504a88468ff35bfd492b529876a04697/tensorflow/tools/ci_build/release/common_win.bat#L56

**Comment by mihaimaruseac** [comment]
This is the only relevant direct dependency on `grpcio` on TF: https://github.com/tensorflow/tensorflow/blob/1595ee17ff02b7ee8ede2db19096d4c36bd14bf4/tensorflow/tools/pip_package/setup.py#L130

Can you post the output of `pip list` and details about the architecture you are on?

**Comment by mihaimaruseac** [comment]
Oh, sorry, you meant the 2.5 release. There we indeed pin to 1.34. https://github.com/tensorflow/tensorflow/blob/15d5b930d7e6e4463e275cfcff22042105148e3f/tensorflow/tools/pip_package/setup.py#L126-L130

Unfortunately, we won't be able to alter this without doing a patch release. We currently need to do patch releases for the vulns mentions in the 25 release notes and we're also very close to the 2.6 release. So let's wait until 2.6 and there this issue would be solved.

In the future, we will add automation to ensure dependencies are updated before release (CC @pak-laura FYI)

**Comment by gitpushdashf** [comment]
That sounds good. Thank you!

**Comment by gitpushdashf** [comment]
Why was this closed? I don't see a 2.6.0 release.

**Comment by ymodak** [comment]
TF 2.6 has now released https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0
Perhaps we can close this thread now.

**Comment by gitpushdashf** [comment]
Working for me, thank you!
