### ISSUE TITLE
Different outputs for same input & model in Colab vs Laptop

### ISSUE THREAD

**Issue by vizakshat** [tensorflow/tensorflow#50040]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab and Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip install tensorflow==2.5.0
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- Bazel version (if compiling from source): na
- GCC/Compiler version (if compiling from source): na
- CUDA/cuDNN version:na
- GPU model and memory:na

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am getting different output for the same model.
The model is here: https://drive.google.com/file/d/1yUjCG5rMeVCKTSPbST2F9BrRRlkDPzEA/view
My test script is:

```
import tensorflow as tf
import PIL
import numpy as np

m = tf.keras.models.load_model('./model.h5')
ar = np.expand_dims(np.asarray(PIL.Image.open('./test.jpeg')), axis=0)
ar1 = (ar-127.5) / 127.5
e = m.predict(ar1)
```
**here e is different on my laptop/mobile(tflite) vs my server/Colab. i.e. output in my laptop matches tflite output on my mobile but is different from Colab/My Server.**

**Describe the expected behavior**
embeddings should be exactly same up to 4-5 decimal points!

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

![sample](https://user-images.githubusercontent.com/29163297/120754851-d4895380-c52a-11eb-9e3b-816db34af347.jpeg)

**Comment by UsharaniPagadala** [comment]
@vizakshat 

 In order to expedite the trouble-shooting process, please provide colab gist along with all the dependencies to reproduce the issue reported here. Thanks!

**Comment by vizakshat** [comment]
> @vizakshat
> 
> In order to expedite the trouble-shooting process, please provide colab gist along with all the dependencies to reproduce the issue reported here. Thanks!

How can I get the gist? I am using normal colab. Haven't changed any settings!

**Comment by UsharaniPagadala** [comment]
@vizakshat 

Copy and Paste the colab link you worked on and give me the access or Save the copy as github gist you will get a copy of the gist then copy and paste the link here.Thanks

**Comment by vizakshat** [comment]
https://colab.research.google.com/gist/vizakshat/7dc03a6278ab840e2a4a5e79639cd45c/emb-issue-tf.ipynb
here.

**Comment by vizakshat** [comment]
https://drive.google.com/file/d/1yUjCG5rMeVCKTSPbST2F9BrRRlkDPzEA/view
here

**Comment by vizakshat** [comment]
Any update on this?

**Comment by jvishnuvardhan** [comment]
@vizakshat Need the image also. But, this is more of a support issue (not a bug). Debugging your model may be required to find the root-cause. If you think this is a bug, can you use some public data and model to verify and find root-cause of the issue. Thanks!

This repo is mainly for bugs and performance related issues. For support issues, we recommend to post them in Stackoverflow where there is a big community to support and resolve issues faster. Thanks!

**Comment by vizakshat** [comment]
I think this is a bug. I have used tensorflow pre-built libraries everywhere nothing else. Plus image you can use anything. Just do a random image and you can check for the outputs. ex **np.random.random((1,112,112,3))** check for outputs using same array (use np.save and np.load)

This is a bug because same model output is different for different servers vs laptop vs colab vs tflite on mobile. (as shown in image above). I was expecting outputs to be **same atleast for 4-5 decimal points!!**

This model is also based on tensorflow-keras. You can check the code in the given repo: https://github.com/leondgarse/Keras_insightface

**Comment by vizakshat** [comment]
> @vizakshat Interesting. did you compare the model weights after loading? Can you please share the model `keras_mobilenet.h5`? Thanks!

How can I compare the weights while doing on different devices? Saving the model and then loading on a different device is resulting in the same difference in outputs!!

**Comment by jvishnuvardhan** [comment]
@vizakshat I ran [`Image_classification_model`](https://www.tensorflow.org/tutorials/images/classification) from TF tutorial page, saved it and loaded it on colab, local (mac OS), and local2 (Windows10 OS). I could see exactly same numbers. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/92918286d3195d11c07f530d6b739481/untitled1003.ipynb).

You could check `model.weights` on different systems. If the weights are same, then the results should be exactly same. If the weights are same but the results are not same, then there may be some uncertainty coming from the input. Thanks!
