### ISSUE TITLE
Adding EfficientNetV2 to tf.keras.applications 

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#50054]
I've noticed that the source code of [EfficientNetV2](https://github.com/google/automl/tree/master/efficientnetv2) has been released in `tf. keras` already. The subclassed API is used to build the model by customizing the `.fit` method. It seems interesting and unlike previous `keras` models until now where functional API is used.

So, I was just wondering will it be part of the `tf.keras.applications` any near soon? or it won't.

**Comment by fchollet** [comment]
Thanks for reaching out. We would welcome `EfficientNetV2` as a new Keras Application. Would you be interested in making a PR for it yourself (or finding other contributors who could do it)?

**Comment by innat** [comment]
Officially the `efficientnet v2` code is already in `tf. keras`. In that case, I would cordially request @mingxingtan san to contribute here. I can assist if it's needed.

**Comment by mingxingtan** [comment]
Hi @innat ,  yes, the automl/efficientnetv2 is already using keras and can be composed with other layers such as:

```
mode = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=[224, 224, 3]),
    effnetv2_model.get_model('efficientnetv2-b0', include_top=False, pretrained=True),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(4, activation='softmax'),
])
```

I would be really great to integrate them into keras applications, and benefit more users. 

@innat Could you prepare a PR, and I am happy to help review/iterate it, with the help from @fchollet , Thanks!

**Comment by innat** [comment]
@mingxingtan thank you. I would glad to send PR. However, currently, I'm on vacation, I'll start working as soon as possible.
