### ISSUE TITLE
Mismatch between TFLearn documentation and tutorial

### ISSUE THREAD

**Issue by alexshires** [tensorflow/tensorflow#5005]
Hi all,

The changes to the metric creation in Estimator in tflearn don't match the current documentation on monitors. For example:

https://www.tensorflow.org/versions/r0.11/tutorials/monitors/index.html

suggests:

```
validation_metrics = {"accuracy": tf.contrib.metrics.streaming_accuracy,
                      "precision": tf.contrib.metrics.streaming_precision,
                      "recall": tf.contrib.metrics.streaming_recall}
validation_monitor = tf.contrib.learn.monitors.ValidationMonitor(
    test_set.data,
    test_set.target,
    every_n_steps=50,
    metrics=validation_metrics)
```

wheras 

https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/contrib/learn/python/learn/estimators/rnn.py

contains:

```
# Single head metrics.
      if isinstance(predictions, dict):
        raise ValueError(
            'Metrics passed provide only name, no prediction, '
            'but predictions are dict. '
            'Metrics: %s, Targets: %s.' % (metrics, targets))
```
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None
### Environment info

Operating System:

Max OSX El Capitan

Installed version of CUDA and cuDNN:

N/A - cpu version
1. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

0.11.0rc0
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

https://gist.github.com/alexshires/d9674c58e352ad81be43f5f7da74c7e1
### What other attempted solutions have you tried?

Looking up MetricSpec configuration - no examples or help available
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

https://gist.github.com/alexshires/5310a751e9b767fbd3595570d618c342

**Comment by asimshankar** [comment]
Thanks for the detailed report @alexshires !

@martinwicke @ispirmustafa : IIRC, you guys were looking to switch to `MetricSpec` from a dict (a274c662b3f090193ead4138791896ffb65d680e). Would you be the right persons to fix the tutorial?

**Comment by martinwicke** [comment]
@sandersk, @ispirmustafa, looks like the monitors tutorial references an old form of metrics. Should we fix it, or are you making a new one for hooks anyway?

**Comment by sandersk** [comment]
@martinwicke, since we need to update regardless, I think it would be ideal to replace the Monitors tutorial with a new one on Hooks. I will work with @ispirmustafa on that.

**Comment by martinwicke** [comment]
That's perfect, thanks!

On Thu, Oct 27, 2016 at 2:35 PM, Sanders Kleinfeld <notifications@github.com

**Comment by dbfr3qs** [comment]
I made a quick and dirty hack to the example code on my own fork for those who (like me) got stuck because of this: [https://github.com/dbfr3qs/tensorflow/commit/e1006cf8307662e1984dba6560e67e246a7ba46c](url)

**Comment by martinwicke** [comment]
We're still working on new tutorial content, but this particular issue is out of date.
