### ISSUE TITLE
TF_StringEncode & TF_StringEncodedSize not found

### ISSUE THREAD

**Issue by budibeta** [tensorflow/tensorflow#50067]
![Screenshot_2](https://user-images.githubusercontent.com/68463485/120733533-97649780-c511-11eb-95e9-759a51232b57.png)

i need a source of TF_StringEncode & TF_StringEncodedSize.

**Comment by tilakrayal** [comment]
@budibeta ,

Please, fill issue template.Can you please provide more information/details to analyse the issue[tf version, steps followed before you ran into this error].

Thanks!
