### ISSUE TITLE
Error while quantizing a tensorflow bert model: ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT32 for input 0, name: input_ids 

### ISSUE THREAD

**Issue by asimsultan** [tensorflow/tensorflow#50069]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installation pip package
- TensorFlow library 2.4

I created a Bert Model for text Classification and then trying to convert to fully integer quantization where I am developing the representative_data_set as following. but on converter.convert, it gives me the following error.

### 2. Code
num_calibration_steps = 100

def representative_dataset_gen():
    for i in range(num_calibration_steps):
        value = np.expand_dims(input_text_ids[i], axis=0).astype('float32')
        yield [value]

and converts the model as 

converter = tf.lite.TFLiteConverter.from_keras_model(themodel)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.allow_custom_ops = True
print('Converting')

tflite_model = converter.convert()

------------------------------------------------------------------------------------

### 2. Error : 
ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT32 for input 0, name: input_ids

**Comment by CyberCrack** [comment]
I had similar issue while converting the BERT model to TFLite.
Check this issue if it helps [Issue converting full scale BERT Model to TFLite Model.  #50026](https://github.com/tensorflow/tensorflow/issues/50026)
It seems some of the ops are not yet fully supported by the TFLite Converter.

**Comment by Xhark** [comment]
input_ids seems int32 not float32.
Would you please try to change the data type of representative data?
(e.g. .astype('float32') -> .astype('int32'))

**Comment by asimsultan** [comment]
@CyberCrack Yes you are right because I have been stuck on this issue for quite some time now since adding on to what @Xhark said, I did also change it to astype('int32') that I had tried already and it gave me this error: 

RuntimeError: Failed to initialize op resolver for calibration:
There are unresolved custom ops: []Encountered unresolved custom op: Erf.Node number 95 (Erf) failed to prepare.

**Comment by CyberCrack** [comment]
@asimsultan Glad I could help.

If you are after reducing the size of the model you can try using the [ALBERT](https://tfhub.dev/tensorflow/albert_en_base/3) or [TF Lite Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_text_classification). Which can help you reduce size drastically.
Although it is possible that you might now achieve good enough metrics for your model and if this happens you can use the smaller versions of BERT, by reducing the number of Transformer Layers (this is what I ended up doing to solve my problem). TFHub provides many options you can check this [TFHub link](https://tfhub.dev/s?q=small_bert). I suggest starting with 4 Transformer Layers and choose the maximum hidden layers i.e. 768 [Direct Link](https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-768_A-12/2) and move your way up as per the difficulty of your problem you are trying to solve.

**Comment by asimsultan** [comment]
So here is the use case. 
I did perform Dynamic Range Quantization and it did give me smaller model from 1.3 GB (Actual Bert model) to 122 mbs(quantized bert model) but the problem arises at the inference while prediction And for that I read that someone referred using Full integer floatfallback quantization so I just tried that where the only thing i had to pass extra was representative_data to calibrate the variable tensor inputs, and over there i have this data coming like .astype(float32) but thats not taken by the already existing model and if i enter astype('int32') etc, it gives me custom ops not supported.


I think I will have to do some stuff like from scratch of the model development and for that currently I will have to look for it. 

But I just wanted to ask one simple question from every one.

For Bert Model, Can we get a small version of it that should be small in size and that should be quick in inference without any errors?

**Comment by mohantym** [comment]
Hi @asimsultan ! Could you please share the BERT model you are trying to convert in TFLite model? I converted a BERT model to Lite for testing . Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/971786f2350bdf11e1dd1b50d8eebf26/git_50069.ipynb) for reference . Thank you!
