### ISSUE TITLE
 TypeError: tf__call() got an unexpected keyword argument 'y'

### ISSUE THREAD

**Issue by qiyangzhang0329** [tensorflow/tensorflow#50079]
**System information**
I am using TensorFlow 2.5 with Python 3.6 I have pip-installed TF2.4 within an anaconda environment.

**Provide the text output from tflite_convert**

**Standalone code to reproduce the issue** 
import tensorflow as tf
assert float(tf.__version__[:3]) >= 2.3
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.compat.v1.InteractiveSession(config=config)
import tensorflow.keras as keras
import pathlib
import numpy as np
import tensorflow_model_optimization as tfmot
from tensorflow.keras.preprocessing.image import ImageDataGenerator

origin_model = tf.keras.applications.MobileNetV3Small(
    input_shape=(224, 224, 3), alpha=1.0, include_top=True, weights='imagenet',
    input_tensor=None, pooling=None, classes=1000,
    classifier_activation='softmax'
)
quant_aware_model = tfmot.quantization.keras.quantize_model(origin_model)
quant_aware_model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.00001),  # 0.045, momentum=0.9, decay=0.98),
                              loss='sparse_categorical_crossentropy',
                              metrics=['accuracy'])

**Any other info / logs**

![image](https://user-images.githubusercontent.com/32632952/120812356-7d619e00-c57f-11eb-84fb-d11cc3389b03.png)

When I use the API "tfmot.quantization.keras.quantize_model", there is a bug.I guess that some layers in mobilenetV3 do not support quantization operations, such as the lamba layer. I wonder if you have encountered it?

thanks in advance.

**Comment by yyoon** [comment]
@rino20 @ethkim Could you take a look?

**Comment by rino20** [comment]
Hi, thanks for reporting the issue. 

You are right, the current QAT is not supporting the part of layers in MobileNetV3. We are working to expand the support. 

I will update here when the support is ready.

**Comment by qiyangzhang0329** [comment]
> @qiyangzhang0329 I can reproduce the issue. [Here](https://colab.research.google.com/gist/jvishnuvardhan/626c3431377c67070094121d3e6a7be9/untitled.ipynb) is a gist for reference. Thanks!

Thanks. But the bug  has not been solved.

**Comment by qiyangzhang0329** [comment]
> @qiyangzhang0329 I can reproduce the issue. [Here](https://colab.research.google.com/gist/jvishnuvardhan/626c3431377c67070094121d3e6a7be9/untitled.ipynb) is a gist for reference. Thanks!

@jvishnuvardhan Thanks. But the bug has not been solved.

**Comment by qiyangzhang0329** [comment]
@rino20 How soon can this issue be expected to be supported? It means a lot to me. Thanks.

**Comment by qiyangzhang0329** [comment]
@rino20 , would the  vision of tf 2.6 support QAT ?

**Comment by rino20** [comment]
QAT is included in TFMOT's release. I thought this is fixed by recent updates, but assign @xhark for better information. 

@qiyangzhang0329  could you check this is still happening in the HEAD of the TF model optimization toolkit?

**Comment by sachinprasadhs** [comment]
While trying to reproduce your issue using Tf-nightly(2.10) version, I'm getting different error which says `'list' object has no attribute 'dtype'` , could you please check.
 Attaching gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/4888e822005db7cc9466f2fee145c7cb/untitled.ipynb) for reference. Thanks!
