### ISSUE TITLE
Update classify_image.py code to use latest pre-trained model

### ISSUE THREAD

**Issue by sudhashbahu** [tensorflow/tensorflow#5007]
The code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/imagenet/classify_image.py references the older pre-trained model at http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz however, a new pre-trained model is available at http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz and is referenced in other parts of the code tree (such as https://github.com/tensorflow/models/tree/master/inception).

Please update the code in classify_image.py to reflect the latest pre-trained  model.

**Comment by ghego** [comment]
This seems a pretty straightforward find/replace issue. Anyone against me fixing it?

**Comment by sudhashbahu** [comment]
@ghego I still see the older TGZ referenced

**Comment by asimshankar** [comment]
@ghego : Thanks for taking the initiative to update this!

@sudhashbahu : The pull request that @ghego made hasn't been merged yet. Follow along in the discussion for #5085

**Comment by mahnunchik** [comment]
Any news?

**Comment by mingxingtan** [comment]
Close due to inactivity, Please see the detailed discussion on #5085

**Comment by EddieOne** [comment]
Does anyone have a late 2019 or 2020 version? Because 600k biases images were removed from Image Net.
