### ISSUE TITLE
argmax for tf.sparse

### ISSUE THREAD

**Issue by jvhoffbauer** [tensorflow/tensorflow#50086]
**Describe the feature and the current behavior/state.**
Similar to tf.sparse.reduce_max, define an argmax operation. I think, computing an argmax over a dimension is not possible with sparse tensors otherwise. If it is, a hint would be appreciated

**Will this change the current api? How?**
Add function tf.sparse.argmax

**Who will benefit with this feature?**
People using argmax / sparse tensors

**Any Other info.**

Thanks!

**Comment by jvhoffbauer** [comment]
I would also be happy to implement this, if you could give me some hints.

**Comment by jvhoffbauer** [comment]
Any help from my side required? Any timeline on this?

**Comment by gowthamkpr** [comment]
@jvhoffbauer You can create a custom sparse_argmax() function using tf.sparse.reduce_max() and tf.boolean_mask(). Please take a look at this [colab](https://colab.research.google.com/gist/mohantym/15902b18281e4f0dcacfba24d1c00391/stack_67811443.ipynb). Thanks!
