### ISSUE TITLE
Compilation on Power8 and CUDA 7.5

### ISSUE THREAD

**Issue by doru1004** [tensorflow/tensorflow#5008]
I am compiling tensorflow on a Power8 CPU with CUDA enabled and I am getting the following error when running this command:

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR: /tensorflow/tensorflow/core/kernels/BUILD:46:1: output 'tensorflow/core/kernels/_objs/strided_slice_op_gpu/tensorflow/core/kernels/strided_slice_op_gpu.cu.pic.o' was not created.
ERROR:/tensorflow/tensorflow/core/kernels/BUILD:1714:1: C++ compilation of rule '//tensorflow/core/kernels:training_ops' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 118 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)

My gcc version is 4.8.4 on Ubuntu 14.04

Is this version of GCC supported for the compilation of tensorflow? Do I need a different version? Has anyone encountered a similar problem?

**Comment by asimshankar** [comment]
gcc 4.8.4 should be fine (I think), however we haven't had enough experience with Power8, so I'm not sure what's happening there. From the logs here, it seems that `gcc` is failing?

Perhaps you can try to diagnose further using `bazel build -s -c opt --config=cuda //tensorflow/tools/pip_package:buid_pip_package`?

(Do you have the same problem without `--config=cuda`?)

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please let us know when further information is available and we will reopen. Thanks!

**Comment by abdasgupta** [comment]
Exactly same issue I am facing. Compilation is getting killed all of a sudden. Any idea??

**Comment by aselle** [comment]
@abdasgupta, could you open a new issue referencing this one and providing all the information asked for in the template (i.e. platform, version of os, version of compiler, version of tensorflow, and maybe amount of memory in your system.)
