### ISSUE TITLE
How to set/modify quantization_parameters (specifically quantized_dimension) for model conversion?

### ISSUE THREAD

**Issue by tawiesn** [tensorflow/tensorflow#50109]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): tf-nightly 2.6.0.dev20210523  

### 2. Code

I have a model with an input shape (1, 128, 64, 16) with the ordering (NHWC), that is images with 16 channels. Conversion to tflite seems to be fine. Conversion to a quantized model also works fine using the following code.

```
converter = tf.lite.TFLiteConverter.from_saved_model(model_output_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
converter.inference_input_type =  tf.int8
converter.inference_output_type =  tf.int8
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
with open(<TFLITE_FILE>, 'wb') as w:
    w.write(tflite_model)
```

However, the resulting quality of the quantized model is quite bad. Seems to be a problem with the quantization. Checking the input_details of the quantized model using

```
import tflite_runtime
from tflite_runtime.interpreter import Interpreter
interpreter = tflite_runtime.interpreter.Interpreter(<TFLITE_FILE>)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
print("Input details: {}".format(input_details))
```

returns

```
Input details: [{'name': 'serving_default_model:0', 'index': 0, 'shape': array([  1, 128,  64,  16], dtype=int32), 'shape_signature': array([  1, 128,  64,  16], dtype=int32), 'dtype': <class 'numpy.int8'>, 'quantization': (0.006251777522265911, -128), 'quantization_parameters': {'scales': array([0.00625178], dtype=float32), 'zero_points': array([-128], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```

_**Obviously, the "quantized_dimension" is zero (that is, why we have only one scales and zero_points value. I would like to have "quantized_dimension" = 3 with 16 scales and 16 zero_points.**_

_**How can i tell the converter to use quantized_dimension = 3?**_

### 3. Failure after conversion

_**Conversion seems to be fine, however for 16 channel input images (input tensor shape = (1, 128, 64, 16)) the quantized_dimension = 0 (and i think it should be 3, to get channel-wise quantization).**_

Thanks for your help!

**Comment by yyoon** [comment]
@teijeong Could you take a look or triage this as appropriate?

**Comment by tawiesn** [comment]
@saikumarchalla @yyoon In between i was further digging into this issue: it seems that the tflite converter by default uses per-channel quantization, but per-channel (or you call it per-axis) quantization is only supported for a small subset of layers as one can see [here](https://www.tensorflow.org/lite/performance/quantization_spec). Basically only for certain parts of Conv_2d and deptwise_conv_2d. Since i have only 1 tensor (with 16 channels) as input, i guess for most of the layers it does only the per-tensor quantization. Unfortunately, the means and std-devs for the 16 channels are quite different such that this per-tensor quantization is suboptimal and produces bad results. Anyway, if you have comments/ideas on this topic, please let me know.

**Comment by teijeong** [comment]
Hi @tawiesn,

I understand what you're trying to do, but unfortunately it's not possible in the current design. The input and activations (outputs from layers) are always per-tensor quantized, and as you discovered only convolutions has support for per-channel quantization.

Looking from the performance point of view - say that input has 16 quantized dimensions, and the following convolution has 32 channels. To calculate correct outputs, it needs to calculate scale of output for `16 * 32` cases, and this quadratic behavior would increase scaling overhead for most cases.

If it's an input, can you consider normalizing the input activations per channel beforehand, so that a single scale can reasonably represent the entire input tensor? This would also possibly benefit model's stability and thus accuracy.

**Comment by chunduriv** [comment]
@tawiesn, Did you refer [above comment](https://github.com/tensorflow/tensorflow/issues/50109#issuecomment-861196932)?

**Comment by tawiesn** [comment]
@chunduriv Yes, i have seen the comment from @teijeong in June and it absolutely makes sense to me. Maybe it would make sense to clarify the restrictions/constraints with respect to channel-wise quantization in the documentation.
