### ISSUE TITLE
 error: 'class tensorflow::TensorShape' has no member named 'AddDimWithStatus'

### ISSUE THREAD

**Issue by hassan-shehawy** [tensorflow/tensorflow#50105]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.1 [64-bit]
- TensorFlow installed from: source
- TensorFlow version: 2.4
- Python version: 3.7.5 [64-bit]
- Installed using: virtualenv
- Bazel version: 3.4.0
- GCC/Compiler version (if compiling from source):  7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 
- Hardware: Raspberry Pi 4 Model B Rev 1.4
- Architecture: aarch64

**Describe the problem**
I could build TF 2.4 on a RPi 4 with Ubuntu 18.04 (64-bit) using bazel. However, when I tried doing this on a fresh one, it failed to build. What should I look into to make a comparison and see where the problem is?
Both have the same GCC version (7.5.0) and same bazel version (3.4.0).  Also in both caes, I'm using virtual enviornment (Python 3.7). I get this error:
`tensorflow/core/kernels/sparse_split_op.cc:71:34: error: 'class tensorflow::TensorShape' has no member named 'AddDimWithStatus'
                      dense_shape.AddDimWithStatus(input_shape_flat(i)));`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
<pre>ubuntu@ubuntu:~$ sudo apt-get install build-essential pkg-confi gi2c-tools avahi-utils joystick libopenjp2–7-dev libtiff5-dev gfortran libatlas-base-dev libopenblas-dev libhdf5-serial-dev git ntp

ubuntu@ubuntu:~$ sudo apt-get install python3.7 python3.7-dev python3.7-venv python3.7-distutils python3.7-lib2to3 python3.7-gdbm python3.7-tk python3-pip

ubuntu@ubuntu:~$ python3.7 -m venv py37env

ubuntu@ubuntu:~$ source py37env/bin/activate

(py37env) ubuntu@ubuntu:~$ python3.7 -m pip install — upgrade pip

(py37env) ubuntu@ubuntu:~$ pip install cython  wheel numpy h5py pybind11

(py37env) ubuntu@ubuntu:~$ pip install -U keras_preprocessing — no-deps

(py37env) ubuntu@ubuntu:~$ git clone https://github.com/tensorflow/tensorflow.git

(py37env) ubuntu@ubuntu:~$ cd tensorflow/

(py37env) ubuntu@ubuntu:~/tensorflow$ git checkout r2.4

ubuntu@ubuntu:~/tensorflow$ python3.7 configure.py 
You have bazel 3.4.0 installed.
Please specify the location of python. [Default is /home/ubuntu/py37env/bin/python3.7]:
Found possible Python library paths:
 /home/ubuntu/py37env/lib/python3.7/site-packages
Please input the desired Python library path to use. Default is [/home/ubuntu/py37env/lib/python3.7/site-packages]
Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.
Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.
Please specify optimization flags to use during compilation when bazel option “ — config=opt” is specified [Default is -Wno-sign-compare]:
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.
Preconfigured Bazel build configs. You can use any of the below by adding “ — config=<>” to your build command. See .bazelrc for more details.
 — config=mkl # Build with MKL support.
 — config=mkl_aarch64 # Build with oneDNN support for Aarch64.
 — config=monolithic # Config for mostly static monolithic build.
 — config=ngraph # Build with Intel nGraph support.
 — config=numa # Build with NUMA support.
 — config=dynamic_kernels # (Experimental) Build kernels into separate shared objects.
 — config=v2 # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
 — config=noaws # Disable AWS S3 filesystem support.
 — config=nogcp # Disable GCP support.
 — config=nohdfs # Disable HDFS support.
 — config=nonccl # Disable NVIDIA NCCL support.

(py37env) ubuntu@ubuntu:~/tensorflow$ bazel build //tensorflow/tools/pip_package:build_pip_package

(py37env) ubuntu@ubuntu:~/tensorflow$ python
Python 3.7.5 
[GCC 8.4.0] on linux
Type “help”, “copyright”, “credits” or “license” for more information.
>>> </pre>

**Any other info / logs**
<pre>(py37env) ubuntu@ubuntu:~/tensorflow$ bazel build //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=142
INFO: Reading rc options for 'build' from /home/ubuntu/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/ubuntu/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/ubuntu/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/ubuntu/py37env/bin/python3.7 --action_env PYTHON_LIB_PATH=/home/ubuntu/py37env/lib/python3.7/site-packages --python_path=/home/ubuntu/py37env/bin/python3.7 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/ubuntu/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/ubuntu/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/ubuntu/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/ubuntu/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/ubuntu/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (171 packages loaded, 26394 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/tensorflow/tensorflow/core/kernels/BUILD:4689:18: C++ compilation of rule '//tensorflow/core/kernels:sparse_split_op' failed (Exit 1)
In file included from ./tensorflow/core/framework/op_kernel.h:35:0,
                 from tensorflow/core/kernels/sparse_split_op.cc:19:
tensorflow/core/kernels/sparse_split_op.cc: In member function 'void tensorflow::SparseSplitOp<T>::Compute(tensorflow::OpKernelContext*)':
tensorflow/core/kernels/sparse_split_op.cc:71:34: error: 'class tensorflow::TensorShape' has no member named 'AddDimWithStatus'
                      dense_shape.AddDimWithStatus(input_shape_flat(i)));
                                  ^
./tensorflow/core/framework/op_requires.h:52:29: note: in definition of macro 'OP_REQUIRES_OK'
     ::tensorflow::Status _s(__VA_ARGS__);                    \
                             ^~~~~~~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 46060.242s, Critical Path: 750.27s
INFO: 9369 processes: 9369 local.
FAILED: Build did NOT complete successfully</pre>

**Comment by Saduf2019** [comment]
@hassan-shehawy 
This issue is already reported and tracked at #49850.
