### ISSUE TITLE
ValueError: No gradients provided for any variable: ['Variable:0']

### ISSUE THREAD

**Issue by mattpodolak** [tensorflow/tensorflow#50111]
I am using a custom training loop with GradientTape. This error `ValueError: No gradients provided for any variable: ['Variable:0']` is being thrown. 

I have written a complicated loss function so I imagine some operation I am doing is causing GradientTape to fail. What are some best practices to follow or common gotchas when doing calculations within a gradientape context? 

For example, should I avoid bit-wise operations, or working with numpy arrays instead of tensors?

**Comment by UsharaniPagadala** [comment]
@mattpodolak 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
Thanks

**Comment by mattpodolak** [comment]
Hi @UsharaniPagadala thanks for the response. I believe I had several errors in my implementation. I converted the tensor into a numpy array when passing it to my loss function. I have since fixed the error so I will close this issue.
