### ISSUE TITLE
tf.gather prints a deprecation warning when inside a @tf.function

### ISSUE THREAD

**Issue by bparr** [tensorflow/tensorflow#50112]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from: binary (from pip)
- TensorFlow version: 2.5.0
- Python version: 3.8.5

**Describe the current behavior**

tf.gather prints a deprecation warning about validate_indices when used inside a @tf.function, even when the call to the tf.gather does not provide a validate_indices.

**Describe the expected behavior**

No deprecation warning.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

@tf.function
def foo(x):
  return tf.gather(x, 0)

a = tf.constant([1, 2, 3])
print('\n\nThe next line causes a deprecation warning.\n\n')
print(foo(a))
```

**Comment by Saduf2019** [comment]
@bparr 
I ran the code on 2.4 and there is no warning please find the [gist here](https://colab.research.google.com/gist/Saduf2019/61fe0234ad17b54affb4a05b6b36c3ee/untitled.ipynb), tf 2.5 will be updated as there would be more releases to it.
