### ISSUE TITLE
how does tf name a variable in a partition?

### ISSUE THREAD

**Issue by eveliao** [tensorflow/tensorflow#50116]
I found var names are not as what I defined them:
```
base-network/fuly_connected/weights/ghts/part_9/Adagrad
base-network/fuly_connected/weights/ights/part_10/Adagrad
```

How do these substrings come up? And I found diff num of partitions leads to diff var names. Could someone tell where the corresponding code are? Thanks!

**Comment by UsharaniPagadala** [comment]
@eveliao 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced].
Thanks
