### ISSUE TITLE
Train cnn model

### ISSUE THREAD

**Issue by 7AM7** [tensorflow/tensorflow#50123]
tensorflow==2.5.0
run code on google colab

when I train my model I get this error and my code and message error bellow

My Code

import os

from silence_tensorflow import silence_tensorflow

silence_tensorflow()

import tensorflow as tf
from tensorflow.keras.layers import Dense, Activation, Dropout, Input, Conv2D, \
    MaxPooling2D, Flatten, BatchNormalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
tf.autograph.set_verbosity(0)
tf.get_logger().setLevel('ERROR')

class CharCNN(object):
    def __init__(self):
        self.Model = Sequential()
        self.build()

    def build(self):
        self.Model.add(Input(name='the_input', shape=(224, 224, 1), batch_size=16, dtype='float32'))
        self.Model.add(Conv2D(32, (3, 3), activation='sigmoid', name='conv1'))
        self.Model.add(MaxPooling2D(pool_size=(2, 2)))
        self.Model.add(Conv2D(32, (3, 3), activation='sigmoid', name='conv2'))
        self.Model.add(MaxPooling2D(pool_size=(2, 2)))
        self.Model.add(Conv2D(64, (3, 3), activation='relu', name='conv3'))
        self.Model.add(MaxPooling2D(pool_size=(2, 2)))
        self.Model.add(Flatten())

        self.Model.add(Dense(512))
        self.Model.add(Dropout(0.5))
        self.Model.add(BatchNormalization(scale=False))
        self.Model.add(Activation('relu'))
        self.Model.add(Dropout(0.5))
        self.Model.add(Dense(26, activation='softmax'))

    def summary(self):
        self.Model.summary()

if __name__ == "__main__":
    common_path = '/content/drive/MyDrive/alphdataset/'
    C = CharCNN()
    C.Model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])
    C.Model.summary()

    with tf.device('/device:GPU:0'):
        batch_size = 16
        epochs = 50
        train_dir = common_path + 'train/'
        test_dir = common_path + 'test/'
        checkpoint_path =   '/content/drive/MyDrive/SavedModels/Alphabet/'
        train_image_generator = ImageDataGenerator(rescale=1. / 255)  # Generator for our training data
        train_data_gen = train_image_generator.flow_from_directory(batch_size=batch_size,
                                                                   directory=train_dir,
                                                                   shuffle=True,
                                                                   target_size=(224, 224),
                                                                   class_mode='categorical',
                                                                   color_mode='grayscale')

        test_image_generator = ImageDataGenerator(rescale=1. / 255)  # Generator for our test data
        test_data_gen = test_image_generator.flow_from_directory(batch_size=batch_size,
                                                                 directory=test_dir,
                                                                 shuffle=False,
                                                                 target_size=(224, 224),
                                                                 class_mode='categorical',
                                                                 color_mode='grayscale')

        # C.Model = tf.keras.models.load_model(checkpoint_path)
        
        callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',
                                                    patience=10,
                                                    restore_best_weights=True,
                                                    baseline=0.45)
        
        history = C.Model.fit(train_data_gen,
                              steps_per_epoch=337,  # Number of images // Batch size
                              epochs=epochs,
                              verbose=1,
                              validation_data=test_data_gen,
                              validation_steps=37,
                              callbacks=[callback])

        C.Model.save(checkpoint_path, save_format='tf')
        # Evaluate Model:
        # Accuracy: 48.13%
        C.Model.evaluate(test_data_gen)

--------------------------------------------------------------------------------------------------------------------

Message Error 

  File "/content/drive/MyDrive/Lipify-LipReading/NN_Models/CharacterCNN.py", line 85, in <module>
    callbacks=[callback])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 917, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  required broadcastable shapes at loc(unknown)
	 [[node sequential/dropout/dropout/Mul_1 (defined at content/drive/MyDrive/Lipify-LipReading/NN_Models/CharacterCNN.py:85) ]] [Op:__inference_train_function_1105]

Function call stack:
train_function

^C

**Comment by jvishnuvardhan** [comment]
@7AM7 Can you please create a standalone code to reproduce the issue? I tried your code but it throws different error. 

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1d88ebd439f2fce20c202e8b71676d0a/untitled.ipynb). Can you update the gist or share a standalone code. Thanks!
