### ISSUE TITLE
 ' ValueError: `to_quantize` can only either be a tf.keras Sequential or Functional model.

### ISSUE THREAD

**Issue by Raisa06** [tensorflow/tensorflow#50126]
I've tried QAT implementation in my model training script. I'm using functional API for the model creation. 
Steps that I followed to implement QAT API:

1. Build the model acrhitecture
2. Inserted the appropriate quantize_model function
3. Train the model
Let me provide you the code snippet for more clearance
         
        words_input = Input(shape=(None,),dtype='int32',name='words_input')
        words = Embedding(input_dim=wordEmbeddings.shape[0], output_dim=wordEmbeddings.shape[1],  weights=[wordEmbeddings], trainable=False)(words_input)    
        ............
        convd_output= SeparableConv1D(kernel_size=4, filters=128, padding='same', activation='relu', strides=1, depth_multiplier=3, bias_regularizer=regularizers.l2(0.0001), kernel_constraint =min_max_norm(0.4,0.9))(output)
        #convd_output=tfmot.quantization.keras.quantize_annotate_layer(AveragePooling1D(pool_size=2, strides=1, padding='same')(convd_output)
        convd_output=AveragePooling1D(pool_size=2, strides=1, padding='same')(convd_output)
        convd_output=Dropout(0.1)(convd_output)	
        ...................
        flatten_output=TimeDistributed(Flatten())(pool_output)          
        
        output = TimeDistributed(Dense(len(label2Idx), activation='softmax'))(flatten_output)

        inputs_list=[words_input, casing_input,newline_input]
        model = Model(*inputs_list, output)
        q_aware_model = tfmot.quantization.keras.quantize_model(model)
        opt = Nadam(lr=0.0005)       
        q_aware_model.compile(loss='sparse_categorical_crossentropy', optimizer=opt,metrics = ['sparse_categorical_accuracy'])
        print(q_aware_model.summary())

**Version details**
tensorflow==1.15.3
tensorflow-model-optimization==0.5.0

**Issue :** I'm using functional API which i supported in QAT API, but still I'm getting a value error

 quantize_model     '`to_quantize` can only either be a tf.keras Sequential or
**ValueError:** `to_quantize` can only either be a tf.keras Sequential or Functional model.

Couldn't able to figure out the issue. It will be helpful if someone help to get over this. 
Thanks in advance

**Comment by tilakrayal** [comment]
@Raisa06 ,

TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the version 2.x  and check if you are facing the same issue. Thanks!

**Comment by Raisa06** [comment]
Yes @tilakrayal  I've upgraded tensorflow to 2.3.0 and tensorflow_model_optimization == 0.5.0
But still facing the same issue.

**Comment by tilakrayal** [comment]
@Raisa06 ,

In order to expedite the trouble-shooting process, can you please provide the complete updated code or gist to reproduce the issue.Thanks!

**Comment by Raisa06** [comment]
Let me provide you the model architecture

    def create_model(self,wordEmbeddings,caseEmbeddings,char2Idx, label2Idx,newlineEmbeddings):

        input_1= Input(shape=(None,),dtype='int32',name='input_1')
        text_1 = Embedding(input_dim=wordEmbeddings.shape[0], output_dim=wordEmbeddings.shape[1],  weights=[wordEmbeddings], trainable=False)(words_input)
        input_2= Input(shape=(None,), dtype='int32', name='input_2')
        text_2= Embedding(output_dim=caseEmbeddings.shape[1], input_dim=caseEmbeddings.shape[0], weights=[caseEmbeddings], trainable=False)(casing_input)
        input_3= Input(shape=(None,), dtype='int32', name='input_3')
        text_3= Embedding(output_dim=newlineEmbeddings.shape[1], input_dim=newlineEmbeddings.shape[0], weights=[newlineEmbeddings], trainable=False)(newline_input)        

        output = concatenate([text_1, text_2,text_3])

        convd_output= SeparableConv1D(kernel_size=4, filters=128, padding='same', activation='relu', strides=1, depth_multiplier=3, bias_regularizer=regularizers.l2(0.0001), kernel_constraint =min_max_norm(0.4,0.9))(output)
        convd_output=AveragePooling1D(pool_size=2, strides=1, padding='same')(convd_output)
        convd_output=Dropout(0.1)(convd_output)
		
        convd_output_1= SeparableConv1D(kernel_size=64, filters=128, padding='same', activation='relu', strides=1, depth_multiplier=3, bias_regularizer=regularizers.l2(0.0001), kernel_constraint =min_max_norm(0.4,0.9))(convd_output)
        pool_output1=AveragePooling1D(pool_size=5, strides=1, padding='same')(convd_output_1)
        pool_output1=Dropout(0.1)(pool_output1)
		
        convd_output_2= SeparableConv1D(kernel_size=32, filters=128, padding='same', activation='relu', strides=1, depth_multiplier=3, bias_regularizer=regularizers.l2(0.0001), kernel_constraint =min_max_norm(0.4,0.9))(pool_output1)
        pool_output=AveragePooling1D(pool_size=3, strides=1, padding='same')(convd_output_2) 
        pool_output=Dropout(0.3)(pool_output)
        flatten_output=TimeDistributed(Flatten())(output)          
        
        output = TimeDistributed(Dense(len(label2Idx), activation='softmax'))(flatten_output)

        inputs_list=[input_1, input_2,input_3]
        model = Model(*inputs_list, output)

        opt = Nadam(lr=0.0005)
        quant_aware_model = tfmot.quantization.keras.quantize_model(model)
        
        quant_aware_model.compile(loss='sparse_categorical_crossentropy', optimizer=opt,metrics = ['sparse_categorical_accuracy'])

        print(quant_aware_model.summary())
        return quant_aware_model

**Comment by tilakrayal** [comment]
@Raisa06 ,

Looks like code is incomplete. Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/b47865ade16c250d554506a338b1b63b/untitled50126.ipynb). Request you to provide complete code or colab link to reproduce the issue  in our environment. It helps us in localizing the issue faster.

Thanks!
