### ISSUE TITLE
GPU and NNAPI not working in Tensorflow Classify

### ISSUE THREAD

**Issue by ANTASGUPTA** [tensorflow/tensorflow#50127]
I am using this android aplication : https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification

 In this when I am selecting GPU or NNAPI along with Float_EfficientNet or Float_MobileNet, I am getting the following error: "Manipulating the hardware accelerators is not allowed in the task library. Only CPU is allowed". I am using K20 Pro mobile which is equipped with Adreno 640 GPU. I have added all the dependencies which were asked.

**Comment by UsharaniPagadala** [comment]
@ANTASGUPTA 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]Thanks

**Comment by yyoon** [comment]
I believe that the Java version of the task library doesn't support hardware acceleration yet, and the error you're seeing is expected. See:

https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview

You'll be able to use the GPU / NNAPI option when running the example with `lib_support` version.

@lu-wang-g @xunkai55 to confirm.

**Comment by xunkai55** [comment]
Thanks @yyoon. Indeed Task Library currently doesn't has acceleration support (but it will come soon!)

An other option: Please try use support library module instead of task api module. We provide both in that example app for users to find a fit. Move the default from "taskApi" to "support": https://github.com/tensorflow/examples/blob/2c3b90942fc9b4458140a197f02c31285f172d4c/lite/examples/image_classification/android/app/build.gradle#L38

**Comment by ANTASGUPTA** [comment]
@xunkai55 
As mentioned in line #38 
taskApi {           getIsDefault().set(true)           dimension "tfliteInference"       }.
I have done the same thing, i.e. set taskApi to True but then also, there is no change in the output.
Can you please tell me, what I should do now?

**Comment by xunkai55** [comment]
@ANTASGUPTA Sorry for not saying that clear. I suggest that to move the default to `support` (move line 38 to line 34, particularly) and then retry. Please do let us know if that still not works.
