### ISSUE TITLE
tf.case evaluates all operations

### ISSUE THREAD

**Issue by shangh1** [tensorflow/tensorflow#50125]
Hi:

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/case

From this official link, The tensors returned by the first pair whose predicate evaluated to True, or those returned by default if none does. If exclusive==False, execution stops at the first predicate which evaluates to True. But it seems that the tf.case still tries to run all operations although it should stop at the first one.

My code:
~~~~~~~~~~~~~~~~~~~~~
import tensorflow as tf
sess = tf.InteractiveSession()
x = 1.0
f1 = lambda: tf.constant(10.)
f2 = lambda: tf.constant(x/(x-1.0))
r = tf.case([(tf.less(x, 100.), f1)], default=f2, exclusive=False)
~~~~~~~~~~~~~~~~~~~~~~~
It produces error. r is supposed to return the value of f1, but it still tries to run f2 and produces error as follows: ZeroDivisionError: float division by zero.

Any suggestion what function I should use so the function can avoid run function f2 so it does not produce error? I have a more complex situation with this same issue. Thanks! I also tried tf.cond, it also produces error.  Thanks! 

**System information**
- OS Platform and Distribution: linux
- TensorFlow version: 1.15.0
- Python version: 3.7.6

**Comment by shangh1** [comment]
hi @saikumarchalla , could you please look at my issue at your convenience? Thanks.

**Comment by shangh1** [comment]
hi @google-admin  Nobody started to look at my issue yet, could you please help? Thanks!

**Comment by saikumarchalla** [comment]
@shangh1  Could you please upgrade to TF 2.x version since 1.x version is no more actively supported. Aplogize for the delay.Thanks!

**Comment by shangh1** [comment]
hi @saikumarchalla, thanks! Sorry for the late reply, I was camping last few days with bad signal. Upgrading to TF 2. version will involve the change for the whole framework, and our production model currently uses TF 1. if this tf.case is not actively supported in TF1. Is there any other functions you know in TF 1 that can overcome this issue? Thanks!

**Comment by rmothukuru** [comment]
@shangh1,
We recommend the Developers to switch to **`Tensorflow Version, 2.x`**.  Please refer the [Migration Guide](https://www.tensorflow.org/guide/migrate) and [Upgrade Guide](https://www.tensorflow.org/guide/upgrade) which makes migration from **`Tensorflow Version 1.x`** to **`Tensorflow Version 2.x`** easier. Thanks!
