### ISSUE TITLE
TensorFlow renames inputs when restoring/resaving SavedModel

### ISSUE THREAD

**Issue by dwyatte** [tensorflow/tensorflow#50130]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Any
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): tf-nightly
- Python version: 3.7
- CUDA/cuDNN version: CPU
- GPU model and memory: CPU

**Describe the current behavior**
When a user restores a SavedModel and resaves it, TensorFlow renames the model inputs in the signature, prefixing them with `"inputs/"`. I'm not sure when this behavior was introduced (it happened non-deterministically in `tensorflow==2.4.1`, but is deterministic in `tensorflow==2.5.0` and `tf-nightly`) or expected. I have a use case where I am constrained in my input names in the signature, although I can work around it if renaming is expected (and deterministic) so this issue is mainly to raise awareness if the renaming is unexpected 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import subprocess
import tensorflow as tf

inputs = {
    "first_feature": tf.constant([1, 2, 3]),
    "second_feature": tf.constant([4, 5, 6]),
}

class MyModel(tf.keras.Model):
    def call(self, inputs, training=None):
        return tf.random.uniform([3, 1])

model = MyModel()
model.compile(optimizer="sgd", loss="mse")
model.fit(inputs, tf.constant([7, 8, 9]))
model.save("model")
dict_model_def = subprocess.check_output("saved_model_cli show --dir model --tag_set serve --signature_def serving_default".split())
print("MODEL")
print(dict_model_def.decode("utf-8"))

print("RESTORED MODEL")
restored_model = tf.keras.models.load_model("model")
restored_model.save("restored_model")
restored_model_def = subprocess.check_output("saved_model_cli show --dir restored_model --tag_set serve --signature_def serving_default".split())
print(restored_model_def.decode("utf-8"))
```

Output:
```
1/1 [==============================] - 0s 117ms/step - loss: 56.5648
MODEL
The given SavedModel SignatureDef contains the following input(s):
  inputs['first_feature'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 1)
      name: serving_default_first_feature:0
  inputs['second_feature'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 1)
      name: serving_default_second_feature:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (3, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict

RESTORED MODEL
The given SavedModel SignatureDef contains the following input(s):
  inputs['inputs/first_feature'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 1)
      name: serving_default_inputs/first_feature:0
  inputs['inputs/second_feature'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 1)
      name: serving_default_inputs/second_feature:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (3, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in [TF 2.5](https://colab.research.google.com/gist/saikumarchalla/74ba0e9d6ee7c70332e9fa9e054a8be4/untitled.ipynb) but in [TF 2.4](https://colab.research.google.com/gist/saikumarchalla/3a336fa0e3587807e4f2696b09cec5e3/untitled97.ipynb) model inputs are same. Please find the attached gists. Thanks!

**Comment by jesford** [comment]
@saikumarchalla if I re-run your TF 2.4 gist a few times I do get the inputs modified intermittently about half the time.

**Comment by dwyatte** [comment]
Bump, as I dug further into this. If I change the code above to simply decorate `MyModel.call` with `@tf.function` and do `model.call.get_concrete_function(inputs).structured_input_signature`, I get

```
(({'first_feature': TensorSpec(shape=(3,), dtype=tf.int32, name='inputs/first_feature'),
   'second_feature': TensorSpec(shape=(3,), dtype=tf.int32, name='inputs/second_feature')},
  None),
 {})
```

This information is used when restoring the model in `infer_inputs_from_restored_function_call`
https://github.com/tensorflow/tensorflow/blob/0733c41e5cfe09362b6ec1559b1b02bd1c19fff2/tensorflow/python/keras/saving/saved_model/load.py#L1133

where the docstring notes:

```
Restored layer call function. It is assumed that `fn` has at least
        one concrete function and that the inputs are in the first argument.
```

When restoring the model above, `infer_inputs_from_restored_function_call` does have multiple concrete functions, but the input names differ across them (in tensorflow<2.5 perhaps there was some randomness in the ordering of these concrete functions).

Ideally `get_concrete_function` wouldn't join the Python variable name (`inputs` in this case) with the name of the TensorFlow variable (`first_feature` or `second_feature`), which seems to be the root of the issue.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
