### ISSUE TITLE
Need to fetch version from TFLite Model

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#50138]
https://github.com/tensorflow/tensorflow/issues/47176 

I have downloaded / created tfLite Model.

How do i know the version of the tfLite Model from just the flatbuffer model(*.tflite ) file..
Can i fetch the version information from this model ?

During automation, I was trying to fetch the TFLite Models and running inference over them. Currently , I am using TFLite 2.4.1 library. The models created above this versions which has unsupported operations, need to error out.

What is the best way of handling ? How to get TFLite version from the model.

**Comment by abattery** [comment]
The "min_runtime_version" model metadata in the TFLite mode file contains the information that describes the minimal runtime version that is capable of running the given model.

The above value in the TFLite flatbuffer schema can be read by the existing C++ and Python schema libraries. For example,

```
from tensorflow.lite.python import schema_py_generated as schema_fb

tflite_model = schema_fb.Model.GetRootAsModel(model_buf, 0)

# Gets metadata from the model file.
for i in range(tflite_model.MetadataLength()):
  meta = tflite_model.Metadata(i)
  if meta.Name().decode("utf-8") == "min_runtime_version":
    buffer_index = meta.Buffer()
    metadata = tflite_model.Buffers(buffer_index)
    min_runtime_version_bytes = metadata.DataAsNumpy().tobytes()
```

References:
[Model metadata table in TFLite flatbuffer schema](https://github.com/tensorflow/tensorflow/blob/8ad56264b31e0ae8c984f3c2f2ef0dc18cd6540b/tensorflow/lite/schema/schema.fbs#L1156)

**Comment by pranathibl** [comment]
Does this meta data available for all models ? Does it work ?
How to add the meta data to the model if it does not have?
Is there any validation to check if meta data exists or not ?

**Comment by abattery** [comment]
At least, converted models using TF 2.4 version always contains the metadata.

**Comment by pranathibl** [comment]
How to add the meta data to the model if it does not have?
Is there any validation to check if meta data exists or not ?

I am using TF version 2.1. Do i need to manually add ?
