### ISSUE TITLE
Python Tools Missing

### ISSUE THREAD

**Issue by sebastient** [tensorflow/tensorflow#5014]
The tools found under tensorflow/python/tools are not packaged along with the pip package making them only usable through bazel (as demonstrated in their header documentation).  It's not clear to me how bazel is told which bits of python should be part of the pip package but these would be very useful to have access to from python code (ie: optimize_for_inference_lib).

**Comment by asimshankar** [comment]
Thanks @sebastient. CCing @petewarden  who will have thoughts on how we want to structure and export these tools

**Comment by martinwicke** [comment]
You can fix this by adding the appropriate files/targets to the pip_backage rule [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L34). 

Basically, you want to add all the `py_binary` targets defined in tensorflow/python/tools/BUILD (but none of the tests.

I'd love a PR.

**Comment by Mistobaan** [comment]
Is this issue fixed with the merged PR ?

**Comment by sebastient** [comment]
Testing this out last week from master did install the tools as expected though I haven’t had a chance to track down the commit which added it to close this ticket yet.  Thank you.

**Comment by gunan** [comment]
Issue seems to be resolved.
Closing.
