### ISSUE TITLE
 NameError: name 'interpreter_wrapper' is not defined 

### ISSUE THREAD

**Issue by Ankita-020696** [tensorflow/tensorflow#50158]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hi,
I am executing tflite through mlperf on riscv linux, getting following error, how to fix it?

>     ./run_local.sh tflite --profile ssd-mobilenet-tf
> 
>     INFO:main:Namespace(accuracy=False, backend='tflite', cache=0, count=None, data_format=None, dataset='coco-300', dataset_list=None, dataset_path='/home/root/Ankita/data/coco', debug=False, find_peak_performance=False, inputs=['image_tensor:0'], max_batchsize=32, max_latency=None, mlperf_conf='../../mlperf.conf', model='/home/root/Ankita/model/resnet50_v1.tflite', model_name='ssd-mobilenet', output='/home/root/Ankita/inference/vision/classification_and_detection/output/tflite-cpu/resnet50', outputs=['num_detections:0', 'detection_boxes:0', 'detection_scores:0', 'detection_classes:0'], profile='ssd-mobilenet-tf', qps=None, samples_per_query=None, scenario='SingleStream', threads=4, time=None, user_conf='user.conf')
>     INFO:coco:reduced image list, 4997 images not found
>     INFO:coco:loaded 3 images, cache=0, took=9.0sec
>     /home/root/Ankita/inference/vision/classification_and_detection/python/coco.py:115: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>     self.label_list = np.array(self.label_list)
>     Traceback (most recent call last):
>     File "python/main.py", line 558, in
>     main()
>     File "python/main.py", line 436, in main
>     model = backend.load(args.model, inputs=args.inputs, outputs=args.outputs)
>     File "/home/root/Ankita/inference/vision/classification_and_detection/python/backend_tflite.py", line 32, in load
>     self.sess = interpreter_wrapper.Interpreter(model_path=model_path)
>     NameError: name 'interpreter_wrapper' is not defined

Thanks

**Comment by abattery** [comment]
Instead of using the interpreter_wrapper, could you try using the `tf.lite.Interpreter` in your Python code?

**Comment by Ankita-020696** [comment]
> Instead of using the interpreter_wrapper, could you try using the `tf.lite.Interpreter` in your Python code?

Hi,


> Instead of using the interpreter_wrapper, could you try using the `tf.lite.Interpreter` in your Python code?

Yes I tried but tensorflow is not ported to riscv so I got tensorflow module not found error. Any other way to fix this?

**Comment by ymodak** [comment]
You may use `tflite_runtime` package to import `Interpreter`
https://www.tensorflow.org/lite/guide/python#about_the_tensorflow_lite_runtime_package
