### ISSUE TITLE
MetricsContainer.update_state passes mask as sample_weight to metric_obj.update_state

### ISSUE THREAD

**Issue by avercau** [tensorflow/tensorflow#50154]
**System information**
- Have I written custom code YES
- OS Platform and Distribution OS X 10.15.6
- TensorFlow installed from binary
- TensorFlow version 2.5.0
- Python version 3.8

**Describe the current behavior**
After upgrading from tensorflow 2.2.1 to 2.5.0, I get an error while training an LSTM model with F1Score for the metrics (issue does not exist if using CategoricalAccuracy for the metrics). After comparing the source code for both versions I found a bug (I think).
In version 2.2.1, in tensorflow/python/keras/engine/compile_utils.py, line 411 (inside MetricsContainer.update_state), the metric_obj is updated by passing y_t and y_p, the optional argument sample_weight is not passed. In version 2.5.0, same method, line 460, something is passed for the optional argument sample_weight, but it is the mask obtained from y_p, hence of dtype tf.bool instead of tf.float32, which gives a TypeError when updating the state of F1Score, because it tries to multiply the boolean mask with tf.float32 tensors. I think tis is incorrect.

Full error:
```
in user code:

    /Users/aleksandra/Projects/Metamaze/metamaze-ml/nlp_ner_lstm/venv_lstm/lib/python3.8/site-packages/tensorflow_addons/metrics/f_scores.py:157 _weighted_sum  *
        val = tf.math.multiply(val, tf.expand_dims(sample_weight, 1))
    /Users/aleksandra/Projects/Metamaze/metamaze-ml/nlp_ner_lstm/venv_lstm/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /Users/aleksandra/Projects/Metamaze/metamaze-ml/nlp_ner_lstm/venv_lstm/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py:530 multiply
        return gen_math_ops.mul(x, y, name)
    /Users/aleksandra/Projects/Metamaze/metamaze-ml/nlp_ner_lstm/venv_lstm/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py:6249 mul
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /Users/aleksandra/Projects/Metamaze/metamaze-ml/nlp_ner_lstm/venv_lstm/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:555 _apply_op_helper
        raise TypeError(

    TypeError: Input 'y' of 'Mul' Op has type bool that does not match type float32 of argument 'x'.

```

**Describe the expected behavior**
No TypeError when updating metrics during training.

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? no

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.python.keras.layers import Masking, Bidirectional, LSTM, Dropout, TimeDistributed, Dense, Lambda
from tensorflow_addons.metrics import F1Score
import numpy as np

window_length = 50
embedding_dimension = 100
num_classes = 5

tf.random.set_seed(42)
embeddings = tf.keras.Input(shape=(window_length, embedding_dimension), dtype=tf.float32, name="embedding_sequence")
nwords = tf.keras.Input(shape=(), dtype=tf.int32, name="nwords")

masked_embedding = Masking()(embeddings)

bilstm = Bidirectional(
    LSTM(
        units=16,
        return_sequences=True,
        dropout=0.0,
        recurrent_dropout=0.0,
    )
)(masked_embedding)

bilstm = Dropout(rate=0.5, seed=42)(bilstm)

logits = TimeDistributed(Dense(num_classes, activation="softmax"), name="logits")(bilstm)

pred_ids = tf.argmax(logits, axis=2, output_type=tf.int32)

naming_layer = Lambda(lambda x: x, name="pred_ids")
pred_ids = naming_layer(pred_ids)

loss = {"logits": "categorical_crossentropy"}

model = tf.keras.Model(inputs=[embeddings, nwords], outputs=[logits, pred_ids], name="ner_bilstm")

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate= 0.001),
    loss=loss,
    metrics={"logits": [F1Score(num_classes=num_classes, average="micro")]},
)

dummy_pred_ids = np.array(["dummy"] * 7)



data_x = {"embedding_sequence": np.random.rand(7,window_length,embedding_dimension), "nwords": np.array([window_length]*7)}
data_y = {
    "logits": np.zeros((7, window_length, num_classes), dtype=int),
    "pred_ids": dummy_pred_ids,
}
model.fit(x=data_x, y=data_y, validation_data=(data_x, data_y))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5 version. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c598195a4804e3a939de844c14fb9200/untitled.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
