### ISSUE TITLE
how to set the buffer_size in tf.data

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#50166]
hi,dear
my code runs more slowly then not distribute training ,
with big dataset,I use tf.data.Dataset.from_generator,
is the buffer_size helpful for speeding up the training ?
similar to the [issue](https://github.com/tensorflow/tensorflow/issues/33898),but a little different

could you pls help me ?
thx

**Comment by tilakrayal** [comment]
@ucasiggcas ,

Please take a look at this links for more information on buffer size in tf.data.It helps.[Link1](https://www.programmersought.com/article/60464190812/),[Link2](https://github.com/tensorflow/tensorflow/issues/14857#issuecomment-347261151),[Link3](https://stackoverflow.com/questions/46444018/meaning-of-buffer-size-in-dataset-map-dataset-prefetch-and-dataset-shuffle)

**Comment by tilakrayal** [comment]
Also, this is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a larger community that reads questions there. Thanks!
