### ISSUE TITLE
Whose bug is this: gcc, MKL, or TF?

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#50176]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.9
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): gcc (Debian 11.1.0-2) 11.1.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
TF build fails with a strange error:
```shell
external/mkl_dnn_v1/src/common/primitive_cache.cpp: In member function 'virtual void dnnl::impl::lru_primitive_cache_t::update_entry(const key_t&, const dnnl::impl::primitive_desc_t*)':
external/mkl_dnn_v1/src/common/primitive_cache.cpp:155:60: error: no match for 'operator!=' (operand types are 'const std::thread::id' and 'const std::thread::id')
  155 |     if (it == cache_mapper_.end() || it->first.thread_id() != key.thread_id())
      |                                      ~~~~~~~~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~
      |                                                         |                  |
      |                                                         |                  const std::thread::id
      |                                                         const std::thread::id
In file included from /usr/include/c++/11/utility:70,

```

It looks that the `!=`  operator is not defined for `std::thread::id`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I am building with MKL:
```
bazel build --verbose_failures --config=mkl --config=v2 --config=nogcp --config=nonccl  -c opt --copt=-march=native --copt="-O3" -s //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by vpirogov** [comment]
This looks like a GCC 11 issue discussed in https://github.com/oneapi-src/oneDNN/issues/1023.

**Comment by vpirogov** [comment]
> Could this be caused by C++20 which removes the "!="?
> https://en.cppreference.com/w/cpp/thread/thread/id

GCC 11 defaults to `-std=gnu++17` according to the documentation, so this should not be the issue unless C++20 was explicitly enabled. oneDNN v2.3-rc builds correctly with GCC 11.1 and default C++ standard setting.

**Comment by eli-osherovich** [comment]
I think TF is compiles with `-std=c++14`, so, it cannot be the  issue. Furthermore, running the same command outside bazel (namely, without sandboxing) does not raise any error.

**Comment by eli-osherovich** [comment]
Closing it since it is fixed in oneDNN upstream.

**Comment by mihaimaruseac** [comment]
TF doesn't yet support C++17 (based on some comments above)

**Comment by eli-osherovich** [comment]
@mihaimaruseac 
It seems that some includes were missing in Intel's opeAPI library. The error surfaces in newer GCC versions (11+).

**Comment by vpirogov** [comment]
@eli-osherovich, @mihaimaruseac,

The build erros are the result of changes in header dependencies introduced in GCC 11. [oneDNN v2.2.4](https://github.com/oneapi-src/oneDNN/releases/tag/v2.2.4) and [oneDNN v2.3-rc2](https://github.com/oneapi-src/oneDNN/releases/tag/v2.3-rc2) include the fix. TF master branch [was just updated](https://github.com/tensorflow/tensorflow/pull/50329) to v2.3-rc2.
