### ISSUE TITLE
Error while using tf.io.encode_jpeg

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#50173]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.5
- Python version: 3.x
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior** : Using **`tf.io.encode_jpeg`** is resulting in error,

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-7f8b07d2c90d> in <module>()
      1 import tensorflow as tf
      2 
----> 3 tf.io.encode_jpeg('Developing_1.jpeg')

8 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     97   ctx.ensure_initialized()
---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
     99 
    100 

TypeError: Cannot convert 'Developing_1.jpeg' to EagerTensor of dtype uint8
```

**Describe the expected behavior** : There should be no error

**Standalone code to reproduce the issue**  : 

```python
import tensorflow as tf

tf.io.encode_jpeg('Any_Image.jpeg')
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by seanmor5** [comment]
Hi @rakeshmothukuru1, `tf.io.encode_jpeg` takes a tensor as input, not a string: https://www.tensorflow.org/api_docs/python/tf/io/encode_jpeg

```
import tensorflow as tf

tf.io.encode_jpeg(tf.constant([[[1, 0, 1]]], tf.uint8))
```

**Comment by ymodak** [comment]
```python
image_path = '/content/Any_Image.jpeg'
image = tf.keras.preprocessing.image.load_img(image_path)
input_arr = tf.keras.preprocessing.image.img_to_array(image)
tf.io.encode_jpeg(input_arr)
```

**Comment by rmothukuru** [comment]
@ymodak,
Thank you for the solution.

**Comment by rakeshmothukuru1** [comment]
@ymodak,
Thank you for the solution.
