### ISSUE TITLE
TF Quit working with  /lib/libstdc++.so.6: version `CXXABI_1.3.8' not found, I then reinstalled 

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#5017]
I had it working, and then went to use it once again (after some "normal" Ubuntu system updates one of which may have been bazel?) And I got the traceback with the CXXABI_1.3.8' not found

So how should I remove the whole install and try again? or something easier?

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
While I found this on SO I did not feel I should be messing around with this?
http://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by

### Environment info
Operating System:
Linux Ubuntu 16.04 Python3.5 Anaconda in root Using an NVIDIA 1060 board
Installed version of CUDA 8 and cuDNN: cudNN v5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
ls /usr/local/cuda/lib64/libcudnn*
/usr/local/cuda/lib64/libcudnn.so    /usr/local/cuda/lib64/libcudnn.so.5.1.5
/usr/local/cuda/lib64/libcudnn.so.5  /usr/local/cuda/lib64/libcudnn_static.a

Not sure what got updated but I got this message when importing tensorflow (which I had installed from source. So I reinstalled from source,, and got the same result but with the added message about should not run from source tree??

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`) 
28166c086204c5ca4134086f250469a3802546ea
2. The output of `bazel version`
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110

### What other attempted solutions have you tried?
Reinstall.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
tom@tomServal:~$ python -c "import tensorflow; print(tensorflow.__version__)"
Traceback (most recent call last):
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/tom/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/tom/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/tom/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/tom/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by asimshankar** [comment]
Do you have the `LD_LIBRARY_PATH` environment variable set? If so, what to?

I suspect that somehow when you're using python, it tries to link `pywrap_tensorflow.so` with `/home/tom/anaconda3/lib/libstdc++.so.6` which might be different from the `libstdc++` against which the TensorFlow library was built (perhaps somewhere in `/usr/lib/`).

Perhaps you can provide the output of:
- `echo $LD_LIBRARY_PATH`
- `ldd /home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so` when anaconda is activated
- `ldd /home/tom/anaconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so` after deactivating anaconda

Though, I must admit, this seems like its some interaction between your environment when building TensorFlow from source and the environment in anaconda. Perhaps this is more suited for a stackoverflow question.

**Comment by link-er** [comment]
I do not even have tensorflow in site-packages of anaconda. Is it possible that tensorflow installation from source will conflict with tensorflow installed in other conda environment?

**Comment by dartdog** [comment]
That is a good point that occurred to me as I was going to sleep, I never explicitly installed TensorFlow via Anaconda.I only installed via source since I'm on 16.05 of Ubuntu and wanted the latest Nvidia drivers for the new 1060 GPU, and it worked fine  but I did do an update of all Anaconda some days afterwards and that may have been the screw up, now pondering how to fix it.. I suppose a uninstall of the Anaconda version (if any, then pip uninstall the built from source version then try a reinstall? Opinions welcome, I'll raise the issue on the Anaconda issues as well.

**Comment by dartdog** [comment]
@asimshankar Thank you for your reply I agree that it seems Anaconda has screwed it up, I do not activate Anaconda but use the base install (root) which Anaconda has used by modifying the system to access Anaconda Python in all cases from the command prompt.
Would appreciate any guidance how to fix, I'll raise with Anaconda channel as well.
So in response to your questions: (note as mentioned I do not Activate Anaconda)


    tom@tomServal:~$ echo $LD_LIBRARY_PATH
    :/usr/local/cuda/lib64
    tom@tomServal:~$ ldd /home/tom/anaconda3/lib/python3.5/site-   packages/tensorflow/python/_pywrap_tensorflow.so
	linux-vdso.so.1 =>  (0x00007fff1f58f000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f875ce98000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f875cc6f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f875c966000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f875c749000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f875c3c6000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f875c1b0000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f875bde7000)
	/lib64/ld-linux-x86-64.so.2 (0x000055bcc7b32000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f875bbde000)
    tom@tomServal:~$

**Comment by asimshankar** [comment]
The `ldd` output here suggests that you're linking with `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`, but the error output you alluded to above (`ImportError: /home/tom/anaconda3/bin/../lib/libstdc++.so.6:`) was linking with `/home/tom/anaconda3/lib/libstdc++.so.6`.

So I'm not quite sure what exactly is happening but it does seem to be something specific to the environment on your setup.  Perhaps you can create an isolated environment with the [docker installation](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#docker-installation)? Doesn't quite solve your precise setup, but something to look into?

**Comment by gaussic** [comment]
try to do this:

```
# cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /home/tom/anaconda3/lib/
```

and it should work, at least it works for me.

**Comment by dartdog** [comment]
@gaussic Many thanks, It did the trick. saved me from ripping it all up and reinstalling from scratch (which of course might not have worked!)

**Comment by Olouge** [comment]
This trick also worked from me. Thank you.

**Comment by KT12** [comment]
For me, anaconda may have been the problem.
`conda install libgcc` updated libgcc from 4.x to 5.x and [fixed the problem](http://stackoverflow.com/a/40181952/6832816).

**Comment by mSLOPE** [comment]
this work for me.
conda install -c anaconda tensorflow

**Comment by monajalal** [comment]
@gaussic in centos I get 
$ ls /usr/lib/x86_64-linux-gnu/
ls: cannot access /usr/lib/x86_64-linux-gnu/: No such file or directory

what do you suggest?

**Comment by mavenzer** [comment]
![screenshot from 2018-07-04 02-39-02](https://user-images.githubusercontent.com/24300927/42244699-a45330cc-7f33-11e8-8884-77c476dfad36.png)

I am trying to implement darkflow which is a repo for yolo object detection algorithms , but constantly i am getting this error .I am using ubuntu 16.04 LTS .

**Comment by relh** [comment]
See https://github.com/FoldingAtHome/fah-issues/issues/1147 for an explanation of what might be going on.

You must just have the wrong GCC for the package you've installed.

**Comment by relh** [comment]
try this `conda update -f libstdcxx-ng`

**Comment by mmehedin** [comment]
If you are not using conda:
The gcc dynamic linker needs this path

`export LD_LIBRARY_PATH=${prefix}/lib:$LD_LIBRARY_PATH`
Practically: edited .bashrc with the following line:

`export LD_LIBRARY_PATH=/usr/lib64/:$LD_LIBRARY_PATH`
(depending on your system you may need /usr/lib/)

How did I find the path:

`locate libstdc++.so.6`

How it works:
https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_install

**Comment by whyisyoung** [comment]
> If you are not using conda:
> The gcc dynamic linker needs this path
> 
> `export LD_LIBRARY_PATH=${prefix}/lib:$LD_LIBRARY_PATH`
> Practically: edited .bashrc with the following line:
> 
> `export LD_LIBRARY_PATH=/usr/lib64/:$LD_LIBRARY_PATH`
> (depending on your system you may need /usr/lib/)
> 
> How did I find the path:
> 
> `locate libstdc++.so.6`
> 
> How it works:
> https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_install

Just for reference, I'm using linuxbrew and pyenv. When I type `import tensorflow` in a python shell. It always gives the error. I fixed this by editing my ~/.zshrc file with adding one line:

`export LD_LIBRARY_PATH=/usr/lib64/:$LD_LIBRARY_PATH`

Originally I thought it should be `~/.linuxbrew/lib/libstdc++.so.6`.
Anyway, I reload the zsh with `source ~/.zshrc` and it worked! Thanks @mmehedin !
