### ISSUE TITLE
EfficientNet fails to load with float16 policy on TF 2.5.0.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/tensorflow#50171]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary.
- TensorFlow version (use command below): v2.5.0-0-ga4dfb8d1a71 2.5.0
- Python version: 3.7.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.0 / 8.0.4
- GPU model and memory: Nvidia Tesla T4, 15109MiB 

**Describe the current behavior**
The model cannot be created when using the mixed precision policy.

```python
import tensorflow as tf

policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)

model = tf.keras.applications.efficientnet.EfficientNetB0()
```

The above will raise `ValueError` : `Tensor conversion requested dtype float16 for Tensor with dtype float32: <tf.Tensor 'normalization_1/Cast:0' shape=(None, 224, 224, 3) dtype=float32>`

Full error below.

**Describe the expected behavior**
The model should work in mixed policy - I remember it used to work in TF 2.4.1, perhaps some changes were made?
```python
!pip uninstall tensorlfow
!pip install tensorflow==2.4.1
policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)

model = tf.keras.applications.efficientnet.EfficientNetB0()  # OK
```

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - yes, BUT: I do not exactly know which part causes the issue (I assume the problem is in the Normalization layer). I could try to fix the issue with some help provided.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

policy = tf.keras.mixed_precision.Policy("mixed_float16")
tf.keras.mixed_precision.set_global_policy(policy)

model = tf.keras.applications.efficientnet.EfficientNetB0()
```

**Other info / logs** 
Full error message:
```python
```python
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py in binary_op_wrapper(x, y)
   1244             r_op = getattr(y, "__r%s__" % op_name)
-> 1245             out = r_op(x)
   1246             if out is NotImplemented:

17 frames
ValueError: Tensor conversion requested dtype float16 for Tensor with dtype float32: <tf.Tensor 'normalization_1/Cast:0' shape=(None, 224, 224, 3) dtype=float32>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    556                 "%s type %s of argument '%s'." %
    557                 (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
--> 558                  inferred_from[input_arg.type_attr]))
    559 
    560         types = [values.dtype]

TypeError: Input 'y' of 'Sub' Op has type float16 that does not match type float32 of argument 'x'.
```

Best regards,
Sebastian

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in [TF 2.5](https://colab.research.google.com/gist/saikumarchalla/9dc2f39888239c56699dfa950e281380/untitled.ipynb) where as in [TF 2.4 ](https://colab.research.google.com/gist/saikumarchalla/77c48aadcf55aac8741d57910edfeca3/untitled98.ipynb) it doesn't raise any error. Please find the attached gist.Thanks!

**Comment by jvishnuvardhan** [comment]
@sebastian-sz This was resolved in recent `tf-nightly` by this https://github.com/tensorflow/tensorflow/commit/f048e532985895311891aa5521239303d28a9ce0. 

[Here](https://colab.research.google.com/gist/jvishnuvardhan/288e047ee7ea64bf6d209471e079989d/untitled.ipynb) is a gist for a reference. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by sebastian-sz** [comment]
Ah, apologies I didn't find the linked issue before.

I can confirm that the model works on `tf-nightly`. Thanks!
