### ISSUE TITLE
How to use TF.data.Dataset for relational database like nuScenes

### ISSUE THREAD

**Issue by RRK13** [tensorflow/tensorflow#50188]
**System information**
- TensorFlow version (you are using): tensorflow==2.5.0 (pip installed, Ubuntu 20.04, CUDA 11.)

**Describe the feature and the current behavior/state.**
tf.data.Dataset is excellent while implementing the data-pipeline, with map, shuffle, batch and prefetch (inducing AUTOTUNE features) . But currently the relational database like nuScenes (https://www.nuscenes.org/nuscenes#data-format). has difficulty to implement with multiple sensor data like camera images and pointCloud's. Please guide or inform the steps to be taken, with examples.

**Will this change the current api? How?**

**Who will benefit with this feature?**
All relational database like nuScenes can use the tf.data.Dataset and also perform better while using the distributed training.

**Comment by tilakrayal** [comment]
@RRK13,
Have you got the chance to have a look at this **tf.data.experimental.SqlDataset** API which allows you to read data from a relational database using a SQL query. It is currently only supported for SQLite databases.

https://www.tensorflow.org/api_docs/python/tf/data/experimental/SqlDataset



```
dataset = tf.data.experimental.SqlDataset(
    driver_name="sqlite",
    data_source_name="/path/database.sqlite3",
    query="SELECT name, age FROM people",
    output_type=(tf.string, tf.int32),
)
```

Thank you!
