### ISSUE TITLE
When we save the model with the api of model.save, received the error of 'TpyeError call() missing 1 required positional argument'

### ISSUE THREAD

**Issue by a1391651300** [tensorflow/tensorflow#50187]
When we save the model with the api of model.save, received the error of 'TpyeError call() missing 1 required positional argument'. But when we try to send one tuple that includes one more parameters to the net instead of parameters directly,the net worked smoothly.Could someone tells me the reason?

**Comment by UsharaniPagadala** [comment]
@a1391651300 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by UsharaniPagadala** [comment]
@a1391651300 

Fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) to analyse the issue reported here. Please refer similar issues, [#47390](https://github.com/tensorflow/tensorflow/issues/47390), [#33388](https://github.com/tensorflow/tensorflow/issues/33388).Thanks
