### ISSUE TITLE
Unable to install tensorflow 2.5.0 on jetson nano

### ISSUE THREAD

**Issue by gitgkk** [tensorflow/tensorflow#50192]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04, Jetpack 4.5.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): automated pip install (see log below)
- TensorFlow version: 2.5.0
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: python3-venv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: Nvidia

**Describe the problem**
Unable to install tensorflow 2.5.0 on nvidia jetson nano. I'm running the installation inside a virtual environment.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I followed https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md
I was at the step: python -m pip install --use-feature=2020-resolver ., which is "python -m pip install  ." with the new version of pip.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Processing /home/leap/workspace/models/research
Requirement already satisfied: Cython in /home/leap/workspace/tf/lib/python3.7/site-packages (from object-detection==0.1)
Collecting apache-beam (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/dd/46/145223f4f89c6b2db0256d3770e28d02ab88fb8b700a84afa89a343cd094/apache-beam-2.30.0.zip
Collecting avro-python3 (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/cc/97/7a6970380ca8db9139a3cc0b0e3e0dd3e4bc584fb3644e1d06e71e1a55f0/avro-python3-1.10.2.tar.gz
Collecting contextlib2 (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Collecting lvis (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/72/b6/1992240ab48310b5360bfdd1d53163f43bb97d90dc5dc723c67d41c38e78/lvis-0.5.3-py3-none-any.whl
Collecting lxml (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/e5/21/a2e4517e3d216f0051687eea3d3317557bde68736f038a3b105ac3809247/lxml-4.6.3.tar.gz
Collecting matplotlib (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/60/d3/286925802edaeb0b8834425ad97c9564ff679eb4208a184533969aa5fc29/matplotlib-3.4.2.tar.gz
Collecting pandas (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/e8/81/f7be049fe887865200a0450b137f2c574647b9154503865502cfd720ab5d/pandas-1.2.4.tar.gz
Collecting pillow (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/21/23/af6bac2a601be6670064a817273d4190b79df6f74d8012926a39bc7aa77f/Pillow-8.2.0.tar.gz
Collecting pycocotools (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/de/df/056875d697c45182ed6d2ae21f62015896fdb841906fe48e7268e791c467/pycocotools-2.0.2.tar.gz
Collecting scipy (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz
Collecting six (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting tf-models-official (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/96/08/81bbc275e8e9c6d1e03dd26daec3a67f45e6322804cbce3d51f93eae1961/tf_models_official-2.5.0-py2.py3-none-any.whl
Collecting tf-slim (from object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/02/97/b0f4a64df018ca018cc035d44f2ef08f91e2e8aa67271f6f19633a015ff7/tf_slim-1.1.0-py2.py3-none-any.whl
Collecting crcmod<2.0,>=1.7 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/6b/b0/e595ce2a2527e169c3bcd6c33d2473c1918e0b7f6826a043ca1245dd4e5b/crcmod-1.7.tar.gz
Collecting dill<0.3.2,>=0.3.1.1 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/c7/11/345f3173809cea7f1a193bfbf02403fff250a3360e0e118a1630985e547d/dill-0.3.1.1.tar.gz
Collecting fastavro<2,>=0.21.4 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/6b/74/ea2e40fb661dcfcca3ab7744f8719869954514c69c1be69b409393860668/fastavro-1.4.1.tar.gz
Collecting future<1.0.0,>=0.18.2 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting grpcio<2,>=1.29.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/8c/34/7dafc9052bd9b2b41c5a8912aeeca01e179d16de17e9c275633d4b807330/grpcio-1.38.0.tar.gz
Collecting hdfs<3.0.0,>=2.1.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/08/f7/4c3fad73123a24d7394b6f40d1ec9c1cbf2e921cfea1797216ffd0a51fb1/hdfs-2.6.0-py3-none-any.whl
Collecting httplib2<0.20.0,>=0.8 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/15/dc/d14bce03f4bfd0214b90a3f556d7c96f75bb94ad597c816a641b962f22e9/httplib2-0.19.1-py3-none-any.whl
Requirement already satisfied: numpy<1.21.0,>=1.14.3 in /home/leap/workspace/tf/lib/python3.7/site-packages (from apache-beam->object-detection==0.1)
Collecting oauth2client<5,>=2.0.1 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl
Collecting protobuf<4,>=3.12.2 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/d5/e0/20ba06eb42155cdb4c741e5caf9946e4569e26d71165abaecada18c58603/protobuf-3.17.3-py2.py3-none-any.whl
Collecting pyarrow<4.0.0,>=0.15.1 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/62/d3/a482d8a4039bf931ed6388308f0cc0541d0cab46f0bbff7c897a74f1c576/pyarrow-3.0.0.tar.gz
Collecting pydot<2,>=1.2.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/ea/76/75b1bb82e9bad3e3d656556eaa353d8cd17c4254393b08ec9786ac8ed273/pydot-1.4.2-py2.py3-none-any.whl
Collecting pymongo<4.0.0,>=3.8.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/c4/2f/79e933655adcf6dbd00738b556cecae5f8ec709301ac10df6f488d83bb53/pymongo-3.11.4.tar.gz
Collecting python-dateutil<3,>=2.8.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pytz>=2018.3 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl
Collecting requests<3.0.0,>=2.24.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl
Collecting typing-extensions<3.8.0,>=3.7.0 (from apache-beam->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting kiwisolver>=1.1.0 (from lvis->object-detection==0.1)
  Downloading https://files.pythonhosted.org/packages/90/55/399ab9f2e171047d28933ae4b686d9382d17e6c09a01bead4a6f6b5038f4/kiwisolver-1.3.1.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 2.1MB/s 
Collecting opencv-python>=4.1.0.25 (from lvis->object-detection==0.1)
  Using cached https://files.pythonhosted.org/packages/bb/08/9dbc183a3ac6baa95fabf749ddb531bd26256edfff5b6c2195eca26258e9/opencv-python-4.5.1.48.tar.gz
Requirement already satisfied: pyparsing>=2.4.0 in /home/leap/workspace/tf/lib/python3.7/site-packages (from lvis->object-detection==0.1)
Collecting cycler>=0.10.0 (from lvis->object-detection==0.1)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.0 in /home/leap/workspace/tf/lib/python3.7/site-packages (from pycocotools->object-detection==0.1)
Collecting tensorflow>=2.5.0 (from tf-models-official->object-detection==0.1)
  Could not find a version that satisfies the requirement tensorflow>=2.5.0 (from tf-models-official->object-detection==0.1) (from versions: )
No matching distribution found for tensorflow>=2.5.0 (from tf-models-official->object-detection==0.1)

Thanks for the help.

Kashyap

**Comment by saikumarchalla** [comment]
@gitgkk  Could you please raise an issue in TF models [repo](https://github.com/tensorflow/models/issues/new/choose)  as it seems more related to object detection. Thanks!
