### ISSUE TITLE
Error while converting .pb file into tflite 

### ISSUE THREAD

**Issue by mehreenjabeen** [tensorflow/tensorflow#50194]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed using pip3

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: FULLY_CONNECTED, SOFTMAX. Here is a list of operators for which you will need custom implementations: AudioSpectrogram, DecodeWav, Mfcc. 
```

**Standalone code to reproduce the issue** 
tflite_convert --output_file=./model_converted.tflite --graph_def_file=./Pretrained_models/DNN/DNN_L.pb --input_shapes=0 --input_arrays=wav_data --output_arrays=labels_softmax --enable_select_tf_ops.

Link of model: https://github.com/ARM-software/ML-KWS-for-MCU/tree/master/Pretrained_models

**Comment by abattery** [comment]
Please consider turning on the Select TF option for unsupported TF ops through TFLite builtin op set.

https://www.tensorflow.org/lite/guide/ops_select

**Comment by abattery** [comment]
Instead of "--enable_select_tf_ops", use "--target_ops=TFLITE_BUILTINS,SELECT_TF_OPS"

**Comment by mehreenjabeen** [comment]
Thanks a lot. It worked.
