### ISSUE TITLE
Overwhelming issues on Mac M1 with newest TF 2.5

### ISSUE THREAD

**Issue by ryanrudes** [tensorflow/tensorflow#50196]
Several issues after installing the TensorFlow metal plugin for Mac M1 according to the provided [documentation](https://developer.apple.com/metal/tensorflow-plugin/):

- Model crashes when using Adam optimizer (logs will follow)
- Even on SGD optimizer, though it does not crash, the loss is as high as possible and does not change
- More issues, but since these were so fundamentally flawed, I think I'll just leave it at that

Here's a basic script, taken from a short [demo notebook](https://www.tensorflow.org/tutorials/quickstart/beginner):
```python
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], predictions).numpy()

model.compile(optimizer = 'sgd', loss = loss_fn)
model.fit(x_train, y_train, epochs=100)
```

Here's what one would expect the logs to look like (run on a Colab runtime):
```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.7249
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3882
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3217
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2853
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2566
```

And here's what they look like when run on the Mac M1:
```
Init Plugin
Init Graph Optimizer
Init Kernel
Metal device set to: Apple M1
2021-06-10 08:05:36.921503: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-06-10 08:05:36.921605: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2021-06-10 08:05:37.062193: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-10 08:05:37.062396: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/5
2021-06-10 08:05:37.140640: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
1875/1875 [==============================] - 5s 3ms/step - loss: 60000.0000
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 60000.0000
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 60000.0000
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 60000.0000
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 60000.0000
```

Here's what happens when you try to supplement that with the `'adam'` optimizer:
```
Init Plugin
Init Graph Optimizer
Init Kernel
Metal device set to: Apple M1
2021-06-10 08:07:02.300603: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-06-10 08:07:02.300696: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2021-06-10 08:07:02.375056: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-10 08:07:02.375226: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/5
2021-06-10 08:07:02.458202: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-06-10 08:07:02.487 python3[42618:4085236] -[MPSNDArrayIdentity encodeToCommandEncoder:commandBuffer:sourceArrays:resultState:destinationArray:kernelDAGObject:]: unrecognized selector sent to instance 0x1695be290
2021-06-10 08:07:02.490 python3[42618:4085236] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MPSNDArrayIdentity encodeToCommandEncoder:commandBuffer:sourceArrays:resultState:destinationArray:kernelDAGObject:]: unrecognized selector sent to instance 0x1695be290'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000199a4a320 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000199778c04 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000199ad9020 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001999ac184 ___forwarding___ + 1444
	4   CoreFoundation                      0x00000001999abb30 _CF_forwarding_prep_0 + 96
	5   libmetal_plugin.dylib               0x0000000134a55db4 ___ZN12metal_plugin14MPSApplyAdamOpIfE7ComputeEPNS_15OpKernelContextE_block_invoke.115 + 92
	6   libdispatch.dylib                   0x0000000199725420 _dispatch_client_callout + 20
	7   libdispatch.dylib                   0x0000000199733a98 _dispatch_lane_barrier_sync_invoke_and_complete + 60
	8   libmetal_plugin.dylib               0x0000000134a533c0 _ZN12metal_plugin14MPSApplyAdamOpIfE7ComputeEPNS_15OpKernelContextE + 4884
	9   libmetal_plugin.dylib               0x0000000134a51e78 _ZN12metal_pluginL15ComputeOpKernelINS_14MPSApplyAdamOpIfEEEEvPvP18TF_OpKernelContext + 44
	10  _pywrap_tensorflow_internal.so      0x0000000148076460 _ZN10tensorflow15PluggableDevice7ComputeEPNS_8OpKernelEPNS_15OpKernelContextE + 148
	11  libtensorflow_framework.2.dylib     0x0000000115d78664 _ZN10tensorflow12_GLOBAL__N_113ExecutorStateINS_15PropagatorStateEE7ProcessENS2_10TaggedNodeEx + 3080
	12  libtensorflow_framework.2.dylib     0x0000000115d79dbc _ZNSt3__110__function6__funcIZN10tensorflow12_GLOBAL__N_113ExecutorStateINS2_15PropagatorStateEE7RunTaskIZNS6_13ScheduleReadyEPN4absl14lts_2020_09_2313InlinedVectorINS5_10TaggedNodeELm8ENS_9allocatorISB_EEEEPNS5_20TaggedNodeReadyQueueEEUlvE0_EEvOT_EUlvE_NSC_ISL_EEFvvEEclEv + 56
	13  _pywrap_tensorflow_internal.so      0x00000001487aa230 _ZN5Eigen15ThreadPoolTemplIN10tensorflow6thread16EigenEnvironmentEE10WorkerLoopEi + 1508
	14  _pywrap_tensorflow_internal.so      0x00000001487a9b28 _ZZN10tensorflow6thread16EigenEnvironment12CreateThreadENSt3__18functionIFvvEEEENKUlvE_clEv + 80
	15  libtensorflow_framework.2.dylib     0x0000000116314b08 _ZN10tensorflow12_GLOBAL__N_17PThread8ThreadFnEPv + 120
	16  libsystem_pthread.dylib             0x00000001998d206c _pthread_start + 320
	17  libsystem_pthread.dylib             0x00000001998ccda0 thread_start + 8
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    42618 abort      python3 tf-demo.py
```

Run on both Python 3.8 and Python 3.9, the same errors occur.

**Comment by arge-7** [comment]
Same error on my end. M1 Mac mini, 16 GB RAM. I can't get anything to work since updating to tf2.5 from the Apple fork that they just archived.

**Comment by freedomtan** [comment]
FYR. on my MBP M1, I created a new python 3.8 venv,  then `pip install tensorflow-macos` and `pip install tensorflow-metal`. So far didn't meet any problem. Your little test python script worked with either sgd or adam.

**Comment by freedomtan** [comment]
> > FYR. on my MBP M1, I created a new python 3.8 venv,  then `pip install tensorflow-macos` and `pip install tensorflow-metal`. So far didn't meet any problem. Your little test python script worked with either sgd or adam.
> 
> Did you do the two steps before this in the instructions here https://developer.apple.com/metal/tensorflow-plugin/? Installing latest miniforge3 and installing the apple tensorflow-deps?

Nope, I am an old-school unix user. I use [macports](https://www.macports.org/) to build python and some dependency, e.g., BLAS for numpy, and use pip to build pip wheels needed by `tensorflow-macos`.

**Comment by Ryan-Rudes** [comment]
> > FYR. on my MBP M1, I created a new python 3.8 venv,  then `pip install tensorflow-macos` and `pip install tensorflow-metal`. So far didn't meet any problem. Your little test python script worked with either sgd or adam.
> 
> Did you do the two steps before this in the instructions here https://developer.apple.com/metal/tensorflow-plugin/? Installing latest miniforge3 and installing the apple tensorflow-deps?

Yes, I did this.

**Comment by aseembehl** [comment]
> > FYR. on my MBP M1, I created a new python 3.8 venv,  then `pip install tensorflow-macos` and `pip install tensorflow-metal`. So far didn't meet any problem. Your little test python script worked with either sgd or adam.
> 
> Did you do the two steps before this in the instructions here https://developer.apple.com/metal/tensorflow-plugin/? Installing latest miniforge3 and installing the apple tensorflow-deps?

Yes, I did this and can exactly replicate the issue.

**Comment by Ryan-Rudes** [comment]
@aseembehl, I did just that and did not get the same results. Here is exactly what I run:

```
conda create -n tf python=3.8
conda activate tf
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```

Then, I run the demo script and get exactly the original output I uploaded. Not sure why this differs between you and I.

**Comment by Ryan-Rudes** [comment]
Is it possible that I'd have to reinstall miniforge3? When I try to do this (using the `-u` (upgrade) flag), I get this error towards the end:

```
Encountered problems while solving:
  - nothing provides requested ca-certificates 2020.12.5 h4653dfc_0
  - nothing provides requested tzdata 2021a he74cb21_0
  - nothing provides requested idna 2.10 pyh9f0ad1d_0
  - nothing provides requested six 1.16.0 pyh6c4a22f_0
  - nothing provides requested wheel 0.36.2 pyhd3deb0d_0
  - nothing provides requested certifi 2020.12.5 py39h2804cbe_1
  - nothing provides requested pyopenssl 20.0.1 pyhd8ed1ab_0
  - nothing provides requested urllib3 1.26.4 pyhd8ed1ab_0
  - nothing provides requested requests 2.25.1 pyhd3deb0d_0

ERROR   Could not solve for environment specs
```

**Comment by Ryan-Rudes** [comment]
OH, did not see that MacOS Monterey is the requirement. I'm still on Big Sur but will update to the developer beta soon. That is almost certainly the problem here.

**Comment by aseembehl** [comment]
> @aseembehl, I did just that and did not get the same results. Here is exactly what I run:
> 
> ```
> conda create -n tf python=3.8
> conda activate tf
> conda install -c apple tensorflow-deps
> python -m pip install tensorflow-macos
> python -m pip install tensorflow-metal
> ```
> 
> Then, I run the demo script and get exactly the original output I uploaded. Not sure why this differs between you and I.

Maybe you misread my comment. TF with macOS doesn't work for me as well. I ran into the same problems as you did, NSexception with Adam and loss blowups with SGD.

**Comment by aseembehl** [comment]
> OH, did not see that MacOS Monterey is the requirement. I'm still on Big Sur but will update to the developer beta soon. That is almost certainly the problem here.

Where do you see the Monterey requirement? Are you referring to the mention on Metal homepage?

**Comment by Ryan-Rudes** [comment]
@aseembehl, it says it [here](https://developer.apple.com/metal/tensorflow-plugin/)
> ### **OS Requirements**
> * macOS 12.0+

**Comment by Ryan-Rudes** [comment]
Just updated to MacOS Monterey and this fixed the issue.

**Comment by kernytsky** [comment]
Updating to 12.0 beta worked for me as well! Perhaps that should be displayed in bold on the requirements page or be stressed that it is a beta OS. I mistakenly assumed it was the current stable release Big Sur (11.x). Thanks!!!

**Comment by aryan-at-ul** [comment]
I am having same issue , apple M1, python3.8 . I have tried the fix and similar things but nothing has worked 

here is the error stack  (I don't understand anything here )

Epoch 1/100
2021-11-10 15:09:53.313171: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-11-10 15:09:53.336 python[77750:5229041] -[MPSGraph adamUpdateWithLearningRateTensor:beta1Tensor:beta2Tensor:epsilonTensor:beta1PowerTensor:beta2PowerTensor:valuesTensor:momentumTensor:velocityTensor:maximumVelocityTensor:gradientTensor:name:]: unrecognized selector sent to instance 0x15e61f2c0
2021-11-10 15:09:53.354 python[77750:5229041] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MPSGraph adamUpdateWithLearningRateTensor:beta1Tensor:beta2Tensor:epsilonTensor:beta1PowerTensor:beta2PowerTensor:valuesTensor:momentumTensor:velocityTensor:maximumVelocityTensor:gradientTensor:name:]: unrecognized selector sent to instance 0x15e61f2c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000187e53838 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000187b7d0a8 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000187ee4694 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x0000000187db4cd4 ___forwarding___ + 1444
	4   CoreFoundation                      0x0000000187db4670 _CF_forwarding_prep_0 + 96
	5   libmetal_plugin.dylib               0x000000013ecae290 _ZN12metal_plugin14MPSApplyAdamOpIfEC2EPNS_20OpKernelConstructionE + 656
	6   libmetal_plugin.dylib               0x000000013ecadebc _ZN12metal_pluginL14CreateOpKernelINS_14MPSApplyAdamOpIfEEEEPvP23TF_OpKernelConstruction + 52
	7   libtensorflow_framework.2.dylib     0x0000000133d985d4 _ZN10tensorflow12_GLOBAL__N_120KernelBuilderFactory6CreateEPNS_20OpKernelConstructionE + 88
	8   libtensorflow_framework.2.dylib     0x0000000133e1a158 _ZN10tensorflow14CreateOpKernelENS_10DeviceTypeEPNS_10DeviceBaseEPNS_9AllocatorEPNS_22FunctionLibraryRuntimeEPNS_11ResourceMgrERKNSt3__110shared_ptrIKNS_14NodePropertiesEEEiPPNS_8OpKernelE + 784
	9   libtensorflow_framework.2.dylib     0x0000000133ff52b8 _ZN10tensorflow21CreateNonCachedKernelEPNS_6DeviceEPNS_22FunctionLibraryRuntimeERKNSt3__110shared_ptrIKNS_14NodePropertiesEEEiPPNS_8OpKernelE + 272
	10  libtensorflow_framework.2.dylib     0x0000000133f9fc20 _ZN10tensorflow26FunctionLibraryRuntimeImpl12CreateKernelERKNSt3__110shared_ptrIKNS_14NodePropertiesEEEPNS_22FunctionLibraryRuntimeEPPNS_8OpKernelE + 600
	11  libtensorflow_framework.2.dylib     0x0000000133e1dd80 _ZN10tensorflow9OpSegment12FindOrCreateERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_PPNS_8OpKernelENS1_8functionIFNS_6StatusESC_EEE + 272
	12  _pywrap_tensorflow_internal.so      0x000000011efc1258 _ZNSt3__110__function6__funcIZN10tensorflow13DirectSession15CreateExecutorsERKNS2_15CallableOptionsEPNS_10unique_ptrINS3_16ExecutorsAndKeysENS_14default_deleteIS8_EEEEPNS7_INS3_12FunctionInfoENS9_ISD_EEEEPNS3_12RunStateArgsEE4$_11NS_9allocatorISJ_EEFNS2_6StatusERKNS_10shared_ptrIKNS2_14NodePropertiesEEEPPNS2_8OpKernelEEEclESS_OSV_ + 140
	13  libtensorflow_framework.2.dylib     0x000000013400a430 _ZN10tensorflow22ImmutableExecutorState10InitializeERKNS_5GraphE + 1192
	14  libtensorflow_framework.2.dylib     0x0000000133ff5064 _ZN10tensorflow16NewLocalExecutorERKNS_19LocalExecutorParamsERKNS_5GraphEPPNS_8ExecutorE + 304
	15  libtensorflow_framework.2.dylib     0x0000000134002e6c _ZN10tensorflow12_GLOBAL__N_124DefaultExecutorRegistrar7Factory11NewExecutorERKNS_19LocalExecutorParamsERKNS_5GraphEPNSt3__110unique_ptrINS_8ExecutorENS9_14default_deleteISB_EEEE + 48
	16  libtensorflow_framework.2.dylib     0x00000001340037e8 _ZN10tensorflow11NewExecutorERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS_19LocalExecutorParamsERKNS_5GraphEPNS0_10unique_ptrINS_8ExecutorENS0_14default_deleteISG_EEEE + 92
	17  _pywrap_tensorflow_internal.so      0x000000011efbb1e4 _ZN10tensorflow13DirectSession15CreateExecutorsERKNS_15CallableOptionsEPNSt3__110unique_ptrINS0_16ExecutorsAndKeysENS4_14default_deleteIS6_EEEEPNS5_INS0_12FunctionInfoENS7_ISB_EEEEPNS0_12RunStateArgsE + 3160
	18  _pywrap_tensorflow_internal.so      0x000000011efbdd80 _ZN10tensorflow13DirectSession12MakeCallableERKNS_15CallableOptionsEPx + 276
	19  _pywrap_tensorflow_internal.so      0x000000011bb744c4 _ZN10tensorflow10SessionRef12MakeCallableERKNS_15CallableOptionsEPx + 192
	20  _pywrap_tensorflow_internal.so      0x000000011bb6e7e8 _ZN10tensorflow12_GLOBAL__N_118MakeCallableHelperEPNS_7SessionEPK9TF_BufferPxP9TF_Status + 116
	21  _pywrap_tf_session.so               0x0000000135755eec _ZZN8pybind1112cpp_function10initializeIZL32pybind11_init__pywrap_tf_sessionRNS_7module_EE3$_0xJP10TF_SessionPK9TF_BufferEJNS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE_8__invokeESQ_ + 212
	22  _pywrap_tf_session.so               0x0000000135741934 _ZN8pybind1112cpp_function10dispatcherEP7_objectS2_S2_ + 3216
	23  python                              0x00000001005cd8cc cfunction_call_varargs + 292
	24  python                              0x00000001005ccf50 _PyObject_MakeTpCall + 640
	25  python                              0x00000001006e23e0 call_function + 680
	26  python                              0x00000001006deebc _PyEval_EvalFrameDefault + 29472
	27  python                              0x00000001005cdd90 function_code_fastcall + 128
	28  python                              0x00000001005ccc1c _PyObject_FastCallDict + 284
	29  python                              0x00000001005cecc4 _PyObject_Call_Prepend + 156
	30  python                              0x0000000100645044 slot_tp_init + 288
	31  python                              0x0000000100652f28 type_call + 308
	32  python                              0x00000001005ccf50 _PyObject_MakeTpCall + 640
	33  python                              0x00000001006e23e0 call_function + 680
	34  python                              0x00000001006deebc _PyEval_EvalFrameDefault + 29472
	35  python                              0x00000001005cdd90 function_code_fastcall + 128
	36  python                              0x00000001006e2348 call_function + 528
	37  python                              0x00000001006deea0 _PyEval_EvalFrameDefault + 29444
	38  python                              0x00000001005cdd90 function_code_fastcall + 128
	39  python                              0x00000001006e2348 call_function + 528
	40  python                              0x00000001006deea0 _PyEval_EvalFrameDefault + 29444
	41  python                              0x00000001005cdd90 function_code_fastcall + 128
	42  python                              0x00000001005ccc1c _PyObject_FastCallDict + 284
	43  python                              0x00000001005cecc4 _PyObject_Call_Prepend + 156
	44  python                              0x0000000100642774 slot_tp_call + 296
	45  python                              0x00000001005ccf50 _PyObject_MakeTpCall + 640
	46  python                              0x00000001006e23e0 call_function + 680
	47  python                              0x00000001006def34 _PyEval_EvalFrameDefault + 29592
	48  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	49  python                              0x00000001005cdf10 _PyFunction_Vectorcall + 236
	50  python                              0x00000001005ccb84 _PyObject_FastCallDict + 132
	51  python                              0x0000000100793d0c partial_call + 444
	52  python                              0x00000001005ccf50 _PyObject_MakeTpCall + 640
	53  python                              0x00000001006e23e0 call_function + 680
	54  python                              0x00000001006defac _PyEval_EvalFrameDefault + 29712
	55  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	56  python                              0x00000001005cdf10 _PyFunction_Vectorcall + 236
	57  python                              0x00000001005d191c method_vectorcall + 156
	58  python                              0x00000001006e2348 call_function + 528
	59  python                              0x00000001006defac _PyEval_EvalFrameDefault + 29712
	60  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	61  python                              0x00000001005cdf10 _PyFunction_Vectorcall + 236
	62  python                              0x00000001005d191c method_vectorcall + 156
	63  python                              0x00000001006e2348 call_function + 528
	64  python                              0x00000001006defac _PyEval_EvalFrameDefault + 29712
	65  python                              0x00000001005cdd90 function_code_fastcall + 128
	66  python                              0x00000001006e2348 call_function + 528
	67  python                              0x00000001006def34 _PyEval_EvalFrameDefault + 29592
	68  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	69  python                              0x00000001007349d8 PyRun_StringFlags + 292
	70  python                              0x00000001006d20a0 builtin_eval + 748
	71  python                              0x000000010061f970 cfunction_vectorcall_FASTCALL + 284
	72  python                              0x00000001006e2348 call_function + 528
	73  python                              0x00000001006def34 _PyEval_EvalFrameDefault + 29592
	74  python                              0x00000001005cdd90 function_code_fastcall + 128
	75  python                              0x00000001006e2348 call_function + 528
	76  python                              0x00000001006def34 _PyEval_EvalFrameDefault + 29592
	77  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	78  python                              0x00000001005cdf10 _PyFunction_Vectorcall + 236
	79  python                              0x00000001006e2348 call_function + 528
	80  python                              0x00000001006def34 _PyEval_EvalFrameDefault + 29592
	81  python                              0x00000001006d7584 _PyEval_EvalCodeWithName + 3340
	82  python                              0x0000000100730e3c PyRun_SimpleFileExFlags + 1052
	83  python                              0x0000000100758eb0 Py_RunMain + 2980
	84  python                              0x000000010075a0a8 pymain_main + 1244
	85  python                              0x00000001005a41e0 main + 56
	86  libdyld.dylib                       0x0000000187cf5430 start + 4
)
libc++abi: terminating with uncaught exception of type NSException
[1]    77750 abort

**Comment by utrenic** [comment]
I need help as I cannot get tensorflow installed in M1 using macOS Monterey 12.0.1. 
I have managed to create conda virtual env and managed to install tensorflow-deps for apple.
However, I cannot install tensroflow-macos for some reason.

(tf) [~/Downloads/TensorFlow]
kelvin > python -m pip install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

Does anyone how to fix it?

Thanks
Kel

**Comment by aryan-at-ul** [comment]
To be safe its better to get MiniForge [https://github.com/conda-forge/miniforge]

Then you should create a virtual env

conda create -n mienv python=3.8

Then activate that env

source activate mien

Last step :

conda install -c apple tensorflow-deps
pip install tensorflow-macos
pip install tensorflow-metal

After that all will work fine.

regards
Aryan

On 18 Nov 2021, at 00:07, ***@***.******@***.***> wrote:

EXTERNAL EMAIL: This email originated from outside of the University of Limerick. Do not click on links or open attachments unless you recognize the sender's email address and know the content is safe.



I need help as I cannot get tensorflow installed in M1 using macOS Monterey 12.0.1.
I have managed to create conda virtual env and managed to install tensorflow-deps for apple.
However, I cannot install tensroflow-macos for some reason.

(tf) [~/Downloads/TensorFlow]
kelvin > python -m pip install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

Does anyone how to fix it?

Thanks
Kel

**Comment by aryan-at-ul** [comment]
To be safe its better to get MiniForge [https://github.com/conda-forge/miniforge]

Then you should create a virtual env 

conda create -n mienv python=3.8

Then activate that env 

source activate mien

Last step : 

conda install -c apple tensorflow-deps  
pip install tensorflow-macos  
pip install tensorflow-metal

**Comment by sxzhou1937** [comment]
try it many times, find the followings version  can work for 'adam optimizer'.
```
tensorflow-estimator          2.5.0
tensorflow-macos              2.5.0
tensorflow-metal              0.1.1
```
Mac OS 11，M1

**Comment by mohantym** [comment]
Hi @ryanrudes @sxzhou1937 !
 I can not replicate this exact behaviour . But I am getting below error with 2.9 and 2.11 api (Tested with metal plugin instruction) 
```
Traceback (most recent call last):
  File "/Users/mohantym/git_50196.py", line 1, in <module>
    import tensorflow as tf
  File "/Users/mohantym/miniforge3/envs/tf-gpu/lib/python3.10/site-packages/tensorflow/__init__.py", line 439, in <module>
    _ll.load_library(_plugin_dir)
  File "/Users/mohantym/miniforge3/envs/tf-gpu/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/mohantym/miniforge3/envs/tf-gpu/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 0x0006): symbol not found in flat namespace '__ZN3tsl8internal10LogMessage16VmoduleActivatedEPKci'
```

Re-opening as requested.
Thank you!

**Comment by bhuiyanmobasshir94** [comment]
I don't think this issue is specific to the optimizer. Please post the answer if anyone can fix this.

**Comment by SuryanarayanaY** [comment]
Hi @ryanrudes ,

I have tested the code on Mac M1 with `tensorflow-macos==2.11 `and its working fine. Please note older optimizers moved to legacy namespace hence we need to use `tf.keras.optimizers.legacy.Adam()` in place of 'adam' and it works as intended.

Please refer the attached logs below.

```
(tf-metal) suryanarayanay-macbookpro:~ suryanarayanay$ python 50196.py 
2.11.0
Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2023-03-30 13:41:43.720528: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-30 13:41:43.720935: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-03-30 13:41:44.060864: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/10
2023-03-30 13:41:44.213540: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2868
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1357
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0997
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0815
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0700
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0583
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0512
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0479
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0415
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0384
(tf-metal) suryanarayanay-macbookpro:~ suryanarayanay$ cat 50196.py
import tensorflow as tf
print(tf.__version__)
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], predictions).numpy()

model.compile(optimizer = tf.keras.optimizers.legacy.Adam(), loss = loss_fn)
model.fit(x_train, y_train, epochs=10)
(tf-metal) suryanarayanay-macbookpro:~ suryanarayanay$ 
```

If still anyone have issues please let us know.Thanks!
