### ISSUE TITLE
Why tensorflow convert the strings to bytes when using from_tensor_slices

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#50193]
tensorflow version: 2.5.0
ds.df is a pandas dataframe whose content are sentences.

```
dstf = tf.data.Dataset.from_tensor_slices((ds.df['content'].values, ds.df['label'].values))
dstf = dstf.shuffle(buffer_size=10000).batch(32)
for mm in dstf.map(lambda x, y: (x, y) ).take(5):
    print(mm)
```
however, it converts the `content` to bytes.
How to avoid this? 

![image](https://user-images.githubusercontent.com/26405281/121509758-8b993980-ca19-11eb-87e7-0f7db8eaddda.png)

**Comment by tilakrayal** [comment]
@yananchen1989 ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Thanks

**Comment by yananchen1989** [comment]
> @yananchen1989 that is because TensorFlow relies on NumPy `dtypes` while constructing tensors. By default, numpy represents strings as variable-length byte arrays. [Reference](https://www.tensorflow.org/guide/tensor#string_tensors)
> 
> Perhaps you can use a `map()` operation to decode those strings.

Thanks.  `byte-string` seems to be the default encoding format.
Is there a formal way to convert byte-string to unicode string?
I tries` tf.strings.unicode_decode` but it returns numbers.

**Comment by kvignesh1420** [comment]
@yananchen1989 https://www.tensorflow.org/api_docs/python/tf/strings/unicode_transcode, maybe this can help. However, I think as long as you use `tf.string` dtype tensors, they will be byte-strings only.
