### ISSUE TITLE
tensorflow removed numpy 1.20.3

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#50204]
So I built tensorflow 2.5.0 successfully, but when I installed the wheel it removed my numpy 1.20.3 and downgraded it to 1.19.5 instead. 

Is this version pin necessary?

**Comment by bnavigator** [comment]
It's a deliberate decision by TF, but the reasons are not very well documented.

See #47691, #48918, #48935.

**Comment by mihaimaruseac** [comment]
With numpy 1.20, a lot of tests will fail with

```
NotImplementedError: Cannot convert a symbolic Tensor (rnn/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
```

PR that tried to fix that got rolled back as it broke internal stuff.

Unforutnately, Google uses py3.6 in most of the CI and there's no numpy 1.20 there.

**Comment by bnavigator** [comment]
> Unforutnately, Google uses py3.6 in most of the CI and there's no numpy 1.20 there.

I think before anything else, this needs to be resolved first. See also https://github.com/tensorflow/tensorflow/pull/48918#issuecomment-847921424

**Comment by mihaimaruseac** [comment]
Yes, but moving a behemoth is slower. There are people working on that, takes a lot of time.

**Comment by bnavigator** [comment]
*activity*

**Comment by ClaudioBorges** [comment]
This makes `tensorflow >= 2.2` incompatible with `gensim >= 4.1`  because `gensim` requires `numpy >= 1.20` on `python 3.8`.

**Comment by mihaimaruseac** [comment]
This should be fixed now, I think?

**Comment by beew** [comment]
@mohantym 
> Hi @beew! We are checking to see if you still need help in this issue , Have you tried latest stable version TF 2.6 yet? Thanks!

TF 2.6 was released on Aug 9, https://github.com/tensorflow/tensorflow/tags, is it the one you meant?

**Comment by banderlog** [comment]
`ERROR: tensorflow 2.6.0 has requirement numpy~=1.19.2,`

**Comment by mohantym** [comment]
Hi @banderlog @beew, I upgraded Numpy version to 1.21.2 in Colab  succesfully in this[ issue](https://github.com/tensorflow/tensorflow/issues/52380),  will  check it in my local system too. Thanks!

**Comment by banderlog** [comment]
@mohantym numpy version is hardcoded in the METADATA file: `Requires-Dist: numpy (~=1.19.2)`. You could change it manually and upgrade numpy, but then you may find that something ceased to work abruptly.

**Comment by mihaimaruseac** [comment]
TF 2.7 will have wider range for numpy.

**Comment by jvishnuvardhan** [comment]
As numpy 1.20 is compatible with TF2.7 and later version (`tf-nightly`), I think this was resolved.

I am closing this issue as this was resolved. Please feel free to reopen if I am wrong. Thanks!
