### ISSUE TITLE
Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.

### ISSUE THREAD

**Issue by dianchia** [tensorflow/tensorflow#50217]
OS: Windows 10
Python: 3.9.1
Tensorflow:  2.5.0
CUDA: 11.3
cudnn: 8.2.0

Output of `nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```
```python
build['cuda_version']  = 64_112
build['cudnn_version'] = 64_8
```

I encountered problem stated in title when testing a model which I trained on the same machine.
During training, a log message stated that `cudnn version 8200` was loaded
```
2021-06-11 15:49:39.798483: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8200
```

But then during testing, the message below appeared.
```
2021-06-11 15:49:10.188342: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0. 
CuDNN library needs to have matching major version and equal or higher minor version. 
If using a binary install, upgrade your CuDNN library. 
If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
```

How should I solve the problem?
Thank you.

**Comment by Saduf2019** [comment]
@dianchia 
Can you please follow the [tested build configurations](https://www.tensorflow.org/install/source_windows), as per which could you please tru with cuda 11.0 or 11.2 and cudnn 8.0/8.1 and let us know. [as this as been tested and works fine, please use the same]

**Comment by dianchia** [comment]
@Saduf2019 
Hi, I have three version of CUDA on my machine, 11.0, 11.1, and 11.3. I have changed the path in environment to point to v11.0 but when I get the build info it still shows cuda version being 64_112. Can I know how to specify which version of cuda to use in tensorflow or which environment variable to change?

**Comment by Saduf2019** [comment]
@dianchia 
Please check at this path "Control Panel ->System and Security->System->Advanced System settings" , can you check with this [link](https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781) as well.

**Comment by dianchia** [comment]
@Saduf2019 
I have changed the path variable and now when importing tensorflow, it shows `2021-06-11 19:47:30.501214: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll`. But then in the build info the cuda version is still 64_112, is that normal?

**Comment by Saduf2019** [comment]
@dianchia 
Can you run some simple Tf code and see if you face any errors.

**Comment by dianchia** [comment]
@Saduf2019 
Hi, I tried running some simple code and it works fine. I have pinned point the issue to be one of the library that I have imported. The library uses PyTorch and I suspect that by importing torch it changes the environment variables of where cudnn was imported from.

**Comment by Saduf2019** [comment]
@dianchia 
I see you have pythorch and tensorflow in same evn, can you have them separated to avoid the issue your facing, do you want to try tensorflow on virtual env and see if you still face the issue.

**Comment by dianchia** [comment]
@Saduf2019 
I'm trying to move from pytorch to tensorflow currently. Since I know the problem is on that particular library, I will just rewrite it using tensorflow. Thanks for the help and I think this issue can be close now.
