### ISSUE TITLE
Backpropagation operators get blocked by NCCL operators when TF Profiler is enabled

### ISSUE THREAD

**Issue by joapolarbear** [tensorflow/tensorflow#50214]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10 (buster).
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.3
- Nvidia Driver: 418.116.00
- CUDA version: 11.0
- cuDNN: 8.0.5
- GPU model and memory: Tesla V100-SXM2-32GB
- NCCL version: 2.8.3
- Horovod version: 0.21.0
- Connection: 2 physical machines, each with 2 V100 GPUs
- Network: 100 Gbps RDMA

**Describe the current behavior**
When using TensorFlow's profiler `tf.profiler.experimental` API to see the timeline of a distributed training job with Horovod+NCCL, it seems that backpropagation (**BP** in short) operators are blocked by NCCL operators. The following figure is the timeline of rank 0 GPU, the row of `Stream #30` shows NCCL traces and the row of `TensorFlow Ops` shows the computation operators . Here we observe two cases of blocking:
1. When the `NCCL 1` operator starts to run, one **BP** operator is still running. The execution time of this **BP** operator is always larger than that of `NCCL 1`, saying that this **BP** operator is blocked and can only finishes after `NCCL 1` is finished.
2. Another case is that during the execution of `NCCL 2`, no `BP` operator is scheduled to run.
![image](https://user-images.githubusercontent.com/17765864/121631175-26912280-cab1-11eb-8c09-ec36c36e95f1.png)

**Describe the expected behavior**
However, these two kinds of blocking will not occur when TensorFlow Profiler is disabled. The following figure shows the corresponding timeline (rank 0 GPU) profiled with `nvprof`. We can see that there is no obvious gap between **BP** operators or extremely long **BP** operators.
![image](https://user-images.githubusercontent.com/17765864/121632493-a6b88780-cab3-11eb-84d8-b26d3ba05ada.png)

Actually, we also didn't observe these two kinds of blocking in Tensorflow 1.x, **it seems that it is a problem of the profiler of  TensorFlow 2.x**. Is that expected or a bug of TF 2' profiler ?

**Standalone code to reproduce the issue**
The python Script to reproduce:
https://github.com/joapolarbear/horovod/blob/b_v0.21.0_tfissue/examples/tensorflow2/tensorflow2_synthetic_benchmark.py
### Profile with TensorFlow Profiler
```
export TRACE_DIR= /path/to/dir
mpirun -np ${TOTAL_GPU_NUM} -H ${HOST_LIST} \
    -bind-to none -map-by slot -mca plm_rsh_args '-p 12345' \
    -mca pml ob1 -mca btl ^openib --allow-run-as-root \
    python3 tensorflow2_synthetic_benchmark.py --profile_range 10,20 --trace_dir ${TRACE_DIR}
```
### Profile with nvprof
```
export TRACE_DIR=/path/to/dir
export NVPROF_CMD="nvprof -o $TRACE_DIR/simple.%q{OMPI_COMM_WORLD_RANK}.nvprof "
mpirun -np ${TOTAL_GPU_NUM} -H ${HOST_LIST} \
    -bind-to none -map-by slot -mca plm_rsh_args '-p 12345' \
    -mca pml ob1 -mca btl ^openib --allow-run-as-root \ 
    ${NVPROF_CMD} python3 tensorflow2_synthetic_benchmark.py
```
**Other info / logs** Include any logs or source code that would be helpful to
The trace files we used in above two examples:
[tf_profiler](https://github.com/tensorflow/tensorflow/files/6635952/trace.json.gz)
[nvprof](https://github.com/tensorflow/tensorflow/files/6635957/rank0.json.zip)

**Comment by stephanwlee** [comment]
TF Profiler is in realm of https://github.com/tensorflow/profiler. Assigned it to its primary.

**Comment by yisitu** [comment]
Hi, could you try to enable concurrent kernel profiling and see if that helps? i.e. `TF_GPU_CUPTI_FORCE_CONCURRENT_KERNEL=1` https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/profiler/internal/gpu/device_tracer_cuda.cc;drc=4d618cb1fe451d5397f821fb2021c9028cec4f5c;l=133

There is a limitation of CUPTI profiling library that serializes kernel execution by default :

>**1.11.1.1. Execution overhead**
Factors affecting the execution overhead under tracing are:
>* Enabling serial kernel activity kind CUPTI_ACTIVITY_KIND_KERNEL can significantly change the overall performance characteristics of the application because all kernel executions are serialized on the GPU. For applications which use only a single CUDA stream and therefore cannot have concurrent kernel execution, this mode can be useful as it incurs less profiling overhead compared to the concurrent kernel mode.
>* Enabling concurrent kernel activity kind CUPTI_ACTIVITY_KIND_CONCURRENT_KERNEL doesn't affect the concurrency of the kernels in the application. In this mode, CUPTI instruments the kernel code to collect the timing information. Since every kernel in the CUDA module is instrumented, the overhead is propotional to the number of kernels in the module. This is a static overhead which happens at the time of loading the CUDA module. The overhead is attributed as CUPTI_ACTIVITY_OVERHEAD_CUPTI_INSTRUMENTATION in the activity record CUpti_ActivityOverhead. Starting with the CUDA 11.2, kernels are not instrumented at the module load time, instead a single instrumentation code is used for each kernel thus avoiding the static overhead at the CUDA module load time.
>* Due to the code instrumentation, concurrent kernel mode can add significant runtime overhead if used on kernels that execute a large number of blocks and that have short execution durations.
>* Collection of the kernel latency timestamps i.e. queued and submitted timestamps is a high overhead activity. These are not collected by default. One can enable the collection of these timestamps using the API cuptiActivityEnableLatencyTimestamps().

https://docs.nvidia.com/cupti/Cupti/r_main.html#r_overhead_tracing_execution

**Comment by joapolarbear** [comment]
@yisitu It works. Thanks for your reply.

**Comment by yisitu** [comment]
You are welcome!
