### ISSUE TITLE
model question

### ISSUE THREAD

**Issue by ewwll** [tensorflow/tensorflow#50222]
my problem:
TypeError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:800 train_step
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/compile_utils.py:460 update_state
        metric_obj.update_state(y_t, y_p, sample_weight=mask)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/metrics_utils.py:86 decorated
        update_op = update_state_fn(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:177 update_state_fn
        return ag_update_state(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:666 update_state  **
        matches, sample_weight=sample_weight)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/metrics.py:424 update_state
        with ops.control_dependencies([value_sum]):
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:5390 control_dependencies
        return get_default_graph().control_dependencies(control_inputs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py:363 control_dependencies
        self.control_captures.add(graph_element)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/keras_tensor.py:242 __hash__
        'Instead, use tensor.ref() as the key.' % self)

    TypeError: Tensors are unhashable. (KerasTensor(type_spec=TensorSpec(shape=(), dtype=tf.float32, name=None), name='tf.math.reduce_sum_1/Sum:0', description="created by layer 'tf.math.reduce_sum_1'"))Instead, use tensor.ref() as the key.
and my model:vae
batch_size=6
x = Input(shape=(120,120,3))
conv1 = Conv2d_BN(x, 8, (3, 3))
conv1 = Conv2d_BN(conv1, 8, (3, 3))
pool1 = MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same')(conv1)
conv2 = Conv2d_BN(pool1, 16, (3, 3))
conv2 = Conv2d_BN(conv2, 16, (3, 3))
pool2 = MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same')(conv2)
conv3 = Conv2d_BN(pool2, 32, (3, 3))
conv3 = Conv2d_BN(conv3, 32, (3, 3))
pool3 = MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same')(conv3)
conv4 = Conv2d_BN(pool3, 64, (3, 3))
conv4 = Conv2d_BN(conv4, 64, (3, 3))
pool4 = MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same')(conv4)
conv5 = Conv2d_BN(pool4, 128, (3, 3))
conv5 = Dropout(0.5)(conv5)
conv5 = Conv2d_BN(conv5, 128, (3, 3))
conv5 = Dropout(0.5)(conv5)
F=Flatten()(conv5)
h = Dense(256, activation='relu')(F)
z_mean = Dense(2)(h)
z_log_var = Dense(2)(h)
def sampling(args):
    z_mean, z_log_var = args
    #print(type(args))
    #print(type(z_log_var))
    #print(type(z_mean))
    epsilon = K.random_normal(shape=(2,), mean=0.,
                              stddev=1.0)
    #print(type(epsilon))
    return z_mean + K.exp(z_log_var / 2) * epsilon
z = Lambda(sampling,name = 'sampling', output_shape=(2))([z_mean, z_log_var])
decoder_h = Dense(256, activation='relu')
decoder_mean = Dense(256, activation='sigmoid')
h_decoded = decoder_h(z)
x_decoded_mean = decoder_mean(h_decoded)
decoder=Dense(8*8*128,activation='relu')(x_decoded_mean)
decoder=Reshape((8,8,128))(decoder)
decoder = Conv2DTranspose(128, kernel_size=(3,3), strides=2)(decoder)
decoder = Conv2D(filters=128, kernel_size=(3,3), strides=(1,1), activation='sigmoid')(decoder)
convt1 = Conv2dT_BN(decoder, 64, (3, 3))
convt1 = Dropout(0.5)(convt1)
conv6 = Conv2d_BN(convt1, 64, (3, 3))
conv6 = Conv2d_BN(conv6, 64, (3, 3))
convt2 = Conv2dT_BN(conv6, 32, (3, 3))
convt2  = Dropout(0.5)(convt2)
conv7 = Conv2d_BN(convt2 , 32, (3, 3))
conv7 = Conv2d_BN(conv7, 32, (3, 3))
convt3 = Conv2dT_BN(conv7, 16, (3, 3))
convt3 = Dropout(0.5)(convt3)
conv8 = Conv2d_BN(convt3, 16, (3, 3))
conv8 = Conv2d_BN(conv8, 16, (3, 3))
outpt = Conv2D(filters=3, kernel_size=(1,1), strides=(1,1), padding='same', activation='sigmoid')(conv8)
vae = Model(inputs=x, outputs=outpt)
vae.compile(optimizer='adam',loss='mean_squared_error',metrics = [KL_loss, recon_loss])
vae.summary()
how can i solve this question

**Comment by ymodak** [comment]
Does this https://stackoverflow.com/questions/61056781/typeerror-tensor-is-unhashable-instead-use-tensor-ref-as-the-key-in-keras help in your case?
