### ISSUE TITLE
[Feature request] Ability to specify TensorSpec.name in tf.Dataset

### ISSUE THREAD

**Issue by dniku** [tensorflow/tensorflow#50224]
**System information**
- TensorFlow version (you are using): 2.5.0 (Colab)
- Are you willing to contribute it (Yes/No): ❌

**Describe the feature and the current behavior/state.**

Please see an example Colab notebook [here](https://colab.research.google.com/drive/1CAPt7TqQrwaHA2WoHqx0VB-ybUCxqtTk?usp=sharing).

Consider a `tf.Dataset` of the following form:

```python
import numpy as np
import tensorflow as tf

def gen():
    # some data generator
    for x in range(10):
        yield {
            'x': np.arange(x + 1),
            'y': np.arange(15).reshape(3, 5).astype(np.float32),
        }

tf_dataset = tf.data.Dataset.from_generator(
    gen,
    output_shapes={
        'x': (None,),
        'y': (None, 5)
    },
    output_types={
        'x': tf.int32,
        'y': tf.float32,
    },
)

# tf_dataset.element_spec contains the following:
# {'x': TensorSpec(shape=(None,), dtype=tf.int32, name=None),
#  'y': TensorSpec(shape=(None, 5), dtype=tf.float32, name=None)}
# There seems to be no API to specify the name fields.

# An attempt to set the name directly fails with AttributeError: can't set attribute
tf_dataset.element_spec['x'].name = 'x'
```

It would be desirable to have an API to set `TensorSpec.name`.

**Will this change the current api? How?**

There could be an extra option for `from_generator`, such as `output_names`, that would specify tensor names for the generator output.

**Who will benefit with this feature?**

Anyone who needs to debug `keras.Model.fit()`. When there is a mismatch between what the model expects and what the dataset provides, one can see in the debugger exactly which tensors are yielded from the dataset. Currently, since Keras models can only receive tuples as inputs, there is no way to annotate these tensors other than via `Tensor.name` (if Keras models could receive dicts, there would have been no such problem).

**Comment by kvignesh1420** [comment]
@dniku you can try the following approach:
```python
import numpy as np
import tensorflow as tf

def gen():
    # some data generator
    for x in range(10):
        yield {
            'x': np.arange(x + 1),
            'y': np.arange(15).reshape(3, 5).astype(np.float32),
        }

tf_dataset = tf.data.Dataset.from_generator(
             gen,
             output_signature={
                 'x': tf.TensorSpec(shape=(None,), dtype=tf.int32, name='x'),
                 'y': tf.TensorSpec(shape=(None, 5), dtype=tf.float32, name='y')
             }
         )

print(tf_dataset.element_spec)
# {'x': TensorSpec(shape=(None,), dtype=tf.int32, name='x'),
# 'y': TensorSpec(shape=(None, 5), dtype=tf.float32, name='y')}
```

**Comment by dniku** [comment]
I seem to have consulted the documentation for an old TF version. Thanks for pointing out the `output_signature` parameter!
