### ISSUE TITLE
.predict() method when using saved & loaded subclassing model

### ISSUE THREAD

**Issue by quetil** [tensorflow/tensorflow#50225]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Windows/Linux as well)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0  (Google Colab default one)
- Python version:  3.7.10 (Google Colab default one)

**Describe the current behavior**
When loading a specific custom subclassing model (overriding the train_step and multiple inputs), the `.predict()` method doesn't work. Where as it's working when the model is defined (and not loaded) and it's also working by using the `.call()` method on the loaded model (see [gist](https://colab.research.google.com/gist/quetil/2b48f95c3a18c0dd6e5fc39e83109a12/save-and-predict-with-custom-class.ipynb?authuser=1#scrollTo=ngyMn-qeuhov)).

The following error message:
```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
      Positional arguments (2 total):
        * (<tf.Tensor 'inputs:0' shape=(32, 2) dtype=float32>, <tf.Tensor 'inputs_1:0' shape=(32, 2) dtype=float32>)
        * False
      Keyword arguments: {}
    
    Expected these arguments to match one of the following 4 option(s):
    
    Option 1:
      Positional arguments (2 total):
        * [TensorSpec(shape=(None, 2), dtype=tf.float32, name='inputs/0'), TensorSpec(shape=(None, 2), dtype=tf.float32, name='inputs/1')]
        * False
      Keyword arguments: {}
```
The option 1 is really matching with the inputs received though...

**Describe the expected behavior**
 The `.predict()` method should work on loaded model.

**Standalone code to reproduce the issue**
I tried to do a simple example to show you the issue.
[Gist](https://colab.research.google.com/gist/quetil/2b48f95c3a18c0dd6e5fc39e83109a12/save-and-predict-with-custom-class.ipynb?authuser=1#scrollTo=ngyMn-qeuhov)

Thank you in advance for you help, I imagine something is missing in the definition of the class to be able to use the `predict()` method on saved & loaded model.

**Comment by quetil** [comment]
Ok, I may find the issue. It sounds to be a mix between list and tuples. 
See [the following gist](https://colab.research.google.com/gist/quetil/957428b50901fa4020fd9c60fbeed5e1/save-and-predict-with-custom-class-tuple.ipynb?authuser=1) where all is working well.

If someone can confirm that the error made, I'd by happy.
Then, would it be worth to add a warning message, when the user is using list where tuple should be recommended? :)

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue with TF 2.5 with list but when using tuple predict method is working fine. Please find the [gist1](https://colab.research.google.com/gist/saikumarchalla/f3a50f6290b02777830985fe1c640d66/save-and-predict-with-custom-class.ipynb?authuser=1#scrollTo=cdwieu1bvCOn) and  [gist2](https://colab.research.google.com/gist/saikumarchalla/e16d40cf5e0031156b1ecd7d402855a5/save-and-predict-with-custom-class-tuple.ipynb?authuser=1#scrollTo=cdwieu1bvCOn). Thanks!

**Comment by sachinprasadhs** [comment]
Hi, Please try the solution mentioned [here](https://github.com/tensorflow/tensorflow/issues/37973#issuecomment-605448707).Thanks!
