### ISSUE TITLE
 Error while Installing tensorflow nightly 

### ISSUE THREAD

**Issue by ajinkeya007** [tensorflow/tensorflow#50228]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-windows 10:

Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

TensorFlow installed from (source or binary): pip install tf-nightly

TensorFlow version:2.5.0

Python version:3.9

Installed using virtualenv? pip? conda?: pip

Bazel version (if compiling from source):

GCC/Compiler version (if compiling from source):

CUDA/cuDNN version:

GPU model and memory: 6 gb ram and gt71

**Describe the problem**
Throwing an exception error

**Provide the exact sequence of commands / steps that you executed before running into the problem**
File "c:\users\ts\appdata\local\programs\python\python39\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
crit = self.state.criteria[name]
KeyError: 'tf-nightly-gpu'

During handling of the above exception, another exception occurred:below

**Any other info / logs**
`raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out`
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@ajinkeya007 

Looking at the error log seems it is similar to [#48034](https://github.com/tensorflow/tensorflow/issues/48034). Please let us know if it helps.Thanks
