### ISSUE TITLE
tensorflow lite on armv7

### ISSUE THREAD

**Issue by yvkrishna91** [tensorflow/tensorflow#50223]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  Debian package repo
- TensorFlow version: 
- Python version:3.6.9
- Installed using virtualenv? pip? conda?:apt-get
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Installed from Debian repo as my OS is ubuntu 16.04 on ARMv7l.
On apt-get update i see following message:
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://apt.corretto.aws stable InRelease' doesn't support architecture 'armhf'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://apt.kitware.com/ubuntu bionic InRelease' doesn't support architecture 'armhf'
Subsequently installed : sudo apt-get install python3-tflite-runtime
But tflite_runtime import failed.
Does it mean the repo does not support current target hardware
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Following are the commands:
echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install python3-tflite-runtime

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@yvkrishna91 ,

Can you please provide the tensorflow version you are using? Thanks!

**Comment by yvkrishna91** [comment]
I have not installed tensorflow. Intended to use tensorflow lite as specified in tensorflow python quick start guide.
________________________________

**Comment by PINTO0309** [comment]
@yvkrishna91 
If you are okay with unofficial, there is an installer that I created.
- TensorFlow Lite stand alone installer
https://github.com/PINTO0309/TensorflowLite-bin/tree/main/2.4.1
- TensorFlow installer
https://github.com/PINTO0309/Tensorflow-bin

**Comment by yvkrishna91** [comment]
Thank you
But the installation failed. Please find the attached error log.
[instalationfailure.txt](https://github.com/tensorflow/tensorflow/files/6642299/instalationfailure.txt)

**Comment by PINTO0309** [comment]
@yvkrishna91 
```
$ sudo pip3 install Cython
```

**Comment by yvkrishna91** [comment]
@PINTO0309 
Cython installation we successful. numpy,pybing11,tflite-runtime fails.
[instalationfailure.txt](https://github.com/tensorflow/tensorflow/files/6642356/instalationfailure.txt)

**Comment by PINTO0309** [comment]
@yvkrishna91 
```
$ sudo pip3 install wheel
```

**Comment by yvkrishna91** [comment]
Installation is successful
Tried label_image.py and resulted in following error. Tflite module runtime is failing.
[instalationfailure.txt](https://github.com/tensorflow/tensorflow/files/6642404/instalationfailure.txt)
[label_image.txt](https://github.com/tensorflow/tensorflow/files/6642405/label_image.txt)

**Comment by PINTO0309** [comment]
Your environment is strange. Xenial or Bionic? What is the result of the following command?
```
$ uname -a
$ ldd --version
```

**Comment by yvkrishna91** [comment]
Linux ubuntu 4.14.164-rt73-ampxlnx #10 SMP PREEMPT RT Wed Feb 19 09:49:00 JST 2020 armv7l armv7l armv7l GNU/Linux
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by PINTO0309** [comment]
I see. Ubuntu 18.04 had not yet created an installer for the armv7l version.

**Comment by yvkrishna91** [comment]
Does it mean it is not possible to have tensorflow lite or mediapipe on this hardware, untill Ubuntu creates an installer for armv7l?

**Comment by PINTO0309** [comment]
I just didn't target armv7l for my build because I thought the demand for it was low. 
Did you use either of the following?

https://github.com/PINTO0309/TensorflowLite-bin/blob/main/2.3.1/download_tflite_runtime-2.3.1-py3-none-linux_armv7l.whl.sh
or
https://github.com/PINTO0309/TensorflowLite-bin/blob/main/2.4.0/download_tflite_runtime-2.4.0-py3-none-linux_armv7l.whl.sh

**Comment by PINTO0309** [comment]
This is a work-around that you can try in your environment for now. I don't know if it will work.
```
$ wget https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.4.0/tensorflow-2.4.0-cp35-none-linux_armv7l.whl
$ mv tensorflow-2.4.0-cp35-none-linux_armv7l.whl tensorflow-2.4.0-cp36-none-linux_armv7l.whl
$ sudo pip3 install tensorflow-2.4.0-cp36-none-linux_armv7l.whl
```

**Comment by yvkrishna91** [comment]
I will try..

**Comment by PINTO0309** [comment]
I'm sorry, but I think you should probably clean it up and try it.

**Comment by yvkrishna91** [comment]
I have not cleaned it up. But got following error.
[instalationfailure.txt](https://github.com/tensorflow/tensorflow/files/6642485/instalationfailure.txt)
Do you think clean up would solve this error?

**Comment by PINTO0309** [comment]
Try
```
$ sudo apt-get install libhdf5-dev
```

**Comment by yvkrishna91** [comment]
It did not work after installation of libhdf5-dev. Error is still the same,
Loading library to get version: libhdf5.so
  error: libhdf5.so: cannot open shared object file: No such file or directory
Attaching the libhdf5-dev installation log.
[libhdf5-installation_succesful.txt](https://github.com/tensorflow/tensorflow/files/6642519/libhdf5-installation_succesful.txt)

**Comment by PINTO0309** [comment]
```
$ sudo pip3 uninstall h5py
$ sudo apt-get install libhdf5-dev 
```

**Comment by yvkrishna91** [comment]
Please check the attached logs.
[instalationfailure.txt](https://github.com/tensorflow/tensorflow/files/6642534/instalationfailure.txt)

**Comment by yvkrishna91** [comment]
Can you please suggest next steps soon?

**Comment by terryheo** [comment]
Do you want to build a TFLite Python wheel for your target armv7 OS?
Did you try https://www.tensorflow.org/lite/guide/build_cmake_pip ?

**Comment by yvkrishna91** [comment]
Yes i did, but get following error:
downloading 'https://storage.googleapis.com/mirror.tensorflow.org/www.kurims.kyoto-u.ac.jp/~ooura/fft2d.tgz' failed
          status_code: 1
          status_string: "Unsupported protocol"
          log:
          --- LOG BEGIN ---
          Protocol "https" not supported or disabled in libcurl
But i am able to download other packages

**Comment by yvkrishna91** [comment]
Is Glib version the root cause? Does upgrading Glib would solve the issue?

**Comment by terryheo** [comment]
FYI, https://github.com/tensorflow/tensorflow/issues/38642#issuecomment-988572129
