### ISSUE TITLE
Make tf.io.gfile / tf.data separate (standalone) packages?

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensorflow#50220]
**System information**
- TensorFlow version (you are using): 2.4.x
- Are you willing to contribute it (Yes/No): No (time constraints) 

**Describe the feature and the current behavior/state.**

At the moment we have to install `tensorflow` as a whole even though our data-processing pipeline only requires access to `tf.gfile` and/or `tf.data`.

Imo it could be beneficial if it was possible to install these two packages separately (standalone) without having to install the rest of Tensorflow. Especially `tf.gfile` could be useful in projects where not a single line related to machine-learning is written so this would be a candidate to become its own `pip`-installable package maybe with the option to install the `tf.data` functionalities. 

```
pip install tensorflow_gfile        # gfile only
pip install tensorflow_gfile[data]  # gfile + data
pip install tensorflow              # All the things
```

**Will this change the current api? How?**

The API should not change, only the fact that packages can be selectively installed.

**Who will benefit with this feature?**

Everyone who works on larger projects.

**Comment by mihaimaruseac** [comment]
There is no plan for this as it does not bring enough benefits to TF team to justify spending ~2 quarters for the separation.

**Comment by stefan-falk** [comment]
I can't really comment on how long this would take and whether or not the TF team itself would benefit from this but I have the feeling that particularly `tf.io.gfile` could be a separate thing. It's really useful and I think this is true even outside of a machine-learning setting. 

I personally would also like to be able to e.g. write shards in a separate pipeline without having to install the entire Tensorflow framework.

However, please close this issue if my suggestion doesn't make sense whatsoever.

**Comment by mihaimaruseac** [comment]
This would be a target of modularization efforts but so far all such efforts in the past few years have been discontinued. When our team grows again we can try launching a new process. If approved, we can work on this.

For now, I'd keep this open, as a reminder that we could do this.

**Comment by BhavanSekar** [comment]
j

**Comment by SidharajYadav** [comment]
How i can contribute
please guide me
I like to solve this problem

**Comment by mohantym** [comment]
Hi @stefan-falk !

We are checking to see whether you still need help in this issue .  
I think we can leverage [Tensorflow/Io](https://github.com/tensorflow/io) and [Tensorflow/datasets](https://github.com/tensorflow/datasets) now.

Thank you!
