### ISSUE TITLE
[RNN] Rolled SimpleRNN and GRU TFLite conversion

### ISSUE THREAD

**Issue by Ruomei** [tensorflow/tensorflow#50226]
### 1. System information
local server
- OS Platform and Distribution: Ubuntu 16.04.4 LTS
- TensorFlow installation: pip package
- TensorFlow library version: 2.6.0-dev20210603

colab
- OS Platform and Distribution: Ubuntu 18.04.5 LTS
- TensorFlow installation: pip package
- TensorFlow library version: 2.6.0-dev20210611

### 2. Code

To reproduce the issue, an end-to-end example is in: https://colab.research.google.com/drive/1_e_pcvIjeuUA_OdqpAYeJhedAAjP2UbL?usp=sharing

### 3. Question
In the colab above, we can see using the fused or unfused way of converting rolled GRU/SimpleRNN layer will result in the same error in TFLite converter: `"ValueError: Failed to parse the model: Only models with a single subgraph are supported, model had 3 subgraphs."`
If the conversion code in the example is correct, we are wondering whether there is any plan to support the rolled GRU/SimpleRNN conversion?
@daverim @jianlijianli @wwwind @akarmi for visibility

**Comment by abattery** [comment]
The above error shows that it is failed at the Model optimization toolkit. Model optimization toolkit has a limitation on supporting control flow ops.

**Comment by xhae** [comment]
Hi, this is a known issue, and I'm actively working on this. Going to update the thread once it's resolved.

**Comment by Ruomei** [comment]
Thank you both @abattery @xhae

**Comment by xhae** [comment]
Multiple subgraph support is now enabled with https://github.com/tensorflow/tensorflow/commit/cd5a9ad1338b01f5fd8ce64ed86ad09bf26468ee

**Comment by JanderHungrige** [comment]
Hi, I tried the stabel tf 2.6.0 version which was released on 11 August on pypi (installed 14.Sept). And the error is still there. Is _cd5a9ad_ added to this 2.6.0 version or the nightly build? 
Thanks

**Comment by abattery** [comment]
Please try out the tf-nightly version instead.

**Comment by JanderHungrige** [comment]
> Please try out the tf-nightly version instead.

Thanks for your quick answer. The nightly gives some other errors which I hoped to circumvent with the stable one. Anyways, onwards to new debugging adventures :-D
