### ISSUE TITLE
Custom tflite writer for pre-quantized model

### ISSUE THREAD

**Issue by mukul74** [tensorflow/tensorflow#50229]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hello,

I am looking for some help in the area of tflite write for conversion of a .pb file to a tflite(flatbuffer file).
1. I currently have a custom pre quantized optimized model, and I want to write this pretrained file to tflite format.
2. Being a custom quantized model, stock converter provided by tensorflow is not an ideal match for now.
3. As I have already optimized the pre-trained model, I want my conv layers to stored as int8 instead of float32, as the weights are in integer format.
4. Can we tweak the converter and make the datatype of conv layers as int8.

Thanks

**Comment by tilakrayal** [comment]
@mukul74 ,

Please go through the links which provide more information of TFlite models.[Link1](https://www.tensorflow.org/lite/guide#development_workflow),[Link2](https://www.tensorflow.org/lite/examples),[Link3](https://stackoverflow.com/questions/50632152/tensorflow-convert-pb-file-to-tflite-using-python).

Also, this is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a larger community that reads questions there. Thanks!

**Comment by mukul74** [comment]
Thanks, for the response.
