### ISSUE TITLE
Basic image classification tutorial missing minor step

### ISSUE THREAD

**Issue by mrpdaemon** [tensorflow/tensorflow#50231]
URL(s) with the issue:
https://www.tensorflow.org/tutorials/keras/classification

The step where the last plot is being drawn (following code) is missing `plt.show()` to display the plot, despite the plot being shown as displayed in the doc:

```
plot_value_array(1, predictions_single[0], test_labels)
_ = plt.xticks(range(10), class_names, rotation=45)
# missing plt.show() here
```

**Comment by ymodak** [comment]
You may want to try running the colab and check. All the plots are displayed as per the website example.

**Comment by mrpdaemon** [comment]
The plot *is* displayed when I run the colab, but I was running the tutorial snippets in a terminal and the plot isn't displayed without `plt.show()`

**Comment by songzy12** [comment]
hi @mrpdaemon I did a quick check about this. In section "Notes" of [1] it says:

> The jupyter backends (activated via %matplotlib inline, %matplotlib notebook, or %matplotlib widget), call show() at the end of every cell by default. Thus, you usually don't have to call it explicitly there.

[1] https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html

**Comment by 8bitmp3** [comment]
> plot_value_array(1, predictions_single[0], test_labels)
> _ = plt.xticks(range(10), class_names, rotation=45)
> # missing plt.show() here

@mrpdaemon Thanks, SGTM. Will add this!

**Comment by Saduf2019** [comment]
Created pr [#1909](https://github.com/tensorflow/docs/pull/1909) request , the issue will be closed once the pr will be merged.

**Comment by 8bitmp3** [comment]
A fix is on its way - you'll see the commit eventually. Thank you @Saduf2019 @mrpdaemon

**Comment by 8bitmp3** [comment]
Done https://github.com/tensorflow/docs/commit/5b21901487f0ed10083676f44a1bc5e1b0862c8b

Thanks again

**Comment by Saduf2019** [comment]
Moving this to closed status as the changes are implemented.
