### ISSUE TITLE
Why is cudaFree(nullptr) needed?

### ISSUE THREAD

**Issue by burgerkingeater** [tensorflow/tensorflow#50232]
Per code here: https://github.com/tensorflow/tensorflow/commit/4535bd5df4d077072a8f207146bf4cd051971237#diff-b0331d3a83e4697c835bec57bc002586de8a3f93b520cad43edf07218dc0ea0eR748, it is calling `cudaFree(nullptr)` as part of cuda initialization. However based on CUDA doc: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ga042655cbbf3408f01061652a075e094, cudaFree(nullptr) performs no operation. Wonder why this is needed here? CCed @yzhwang

**Comment by sanjoy** [comment]
We're likely relying on `cudaFree(nullptr)` to implicitly initialize the GPU.

**Comment by burgerkingeater** [comment]
@sanjoy thanks for the answer. Can you elaborate a bit? Like why would `cudaFree(nullptr)` initialize GPU? Based on the cuda doc cudaFree with null pointer performs no operation.  The reason I'm asking about the necessity of it is we are seeing error: 
`CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory` when calling this API.

**Comment by burgerkingeater** [comment]
@sanjoy Based on CUDA doc, `cudaSetDevice()` before cudaFree(https://github.com/tensorflow/tensorflow/commit/4535bd5df4d077072a8f207146bf4cd051971237#diff-b0331d3a83e4697c835bec57bc002586de8a3f93b520cad43edf07218dc0ea0eR743)
should already initialize the CUDA context, so do you think this is still needed? Happy to contribute a PR if this is the case.
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DRIVER.html
```
Primary Contexts

There exists a one to one relationship between CUDA devices in the CUDA Runtime API and CUcontext s in the CUDA Driver API within a process. The specific context which the CUDA Runtime API uses for a device is called the device's primary context. From the perspective of the CUDA Runtime API, a device and its primary context are synonymous.

Initialization and Tear-Down

CUDA Runtime API calls operate on the CUDA Driver API CUcontext which is current to to the calling host thread.

The function cudaSetDevice() makes the primary context for the specified device current to the calling thread by calling cuCtxSetCurrent().

The CUDA Runtime API will automatically initialize the primary context for a device at the first CUDA Runtime API call which requires an active context. If no CUcontext is current to the calling thread when a CUDA Runtime API call which requires an active context is made, then the primary context for a device will be selected, made current to the calling thread, and initialized.

```

**Comment by sanjoy** [comment]
Thanks for the info, a PR would be great!
