### ISSUE TITLE
IRFFT much slower than RFFT on GPU

### ISSUE THREAD

**Issue by hunse** [tensorflow/tensorflow#50230]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA Geforce 970 M (but I've observed similar on other NVIDIA GPUs)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

IRFFT takes much longer than RFFT (orders of magnitude) when running on the GPU. On the CPU, they take about the same amount of time.

**Describe the expected behavior**

IRFFT may be somewhat longer than RFFT, but hopefully at most a few times longer.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf

dims = 1024
seq_len = 1024

use_gpu = True

tf.profiler.experimental.start(
    logdir="test_fft_convolution_speed_log" + ("" if use_gpu else "_cpu")
)

with tf.device("/GPU:0" if use_gpu else "/CPU:0"):
    u = tf.random.uniform(shape=(dims, seq_len), minval=-1, maxval=1, seed=0)
    v = tf.random.uniform(shape=(dims, seq_len), minval=-1, maxval=1, seed=0)

    fu = tf.signal.rfft(u, fft_length=[2 * seq_len], name="fu")
    fv = tf.signal.rfft(v, fft_length=[2 * seq_len], name="fv")

    fw = fu * fv
    w = tf.signal.irfft(fw, fft_length=[2 * seq_len], name="iw")[..., :seq_len]

    print(w.numpy()[0, 0])

tf.profiler.experimental.stop()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by hunse** [comment]
Here's a picture of the trace viewer for the GPU, as well as the whole profile dir. In the picture, I've selected the ops on the GPU starting at about 650 ms and extending to the end of the IRFFT. You can see that the IRFFT is much longer than the RFFTs.

![tensorflow-irfft-profile](https://user-images.githubusercontent.com/1952250/121748991-e98c5680-cad7-11eb-8b75-339469e77fcc.png)

[test_fft_convolution_speed_log.zip](https://github.com/tensorflow/tensorflow/files/6640992/test_fft_convolution_speed_log.zip)

**Comment by tilakrayal** [comment]
I was able to reproduce the code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/44069a362db59c2f59ddd05b0c80a915/50230.ipynb).

**Comment by hunse** [comment]
Looking at this again, the GPU portion of the RFFT is very fast, but there's a CPU portion that appears to take much longer. Why is this the case?

**Comment by hunse** [comment]
![ifft-profile](https://user-images.githubusercontent.com/1952250/121915581-559dd300-cd01-11eb-94e2-bfe9840b248d.png)

Zooming in on the part around 650 ms, you can see what's actually happening in the "compute" stream. There, the RFFTs, mul, and IRFFT all happen quite quickly. But then the IRFFT tensorflow op takes forever afterwards, and it's not clear what it's doing (it appears to be doing nothing).

**Comment by sachinprasadhs** [comment]
You can find the similar issue discussion here #6541.

**Comment by jvishnuvardhan** [comment]
@hunse I tried running your code and noticed similar computational time. Please check [this gist](https://colab.research.google.com/gist/jvishnuvardhan/ae40b14b21fd85dfb09fdf113d1571e1/50230.ipynb) and let me know if I am missing anything here. Thanks!
