### ISSUE TITLE
How to convert .pkl file to tflite model

### ISSUE THREAD

**Issue by freakytejash** [tensorflow/tensorflow#50239]

**Comment by MhdAmr788** [comment]
Please stop!

**Comment by abattery** [comment]
To convert the given model to the corresponding TensorFlow Lite model, a pkl model should be converted to the TensorFlow Saved Model and then, the saved model converter (`tf.lite.TFLiteConverter.from_saved_model`) can be used for converting from the saved model to the corresponding TensorFlow Lite model.
