### ISSUE TITLE
Inconsistent gather_nd behavior on empty tensors

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#50246]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.9.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Using tf.gather_nd with empty tensors raises an invalid argument error, but works if tensors are not empty. tf.gather does not have this problem.

For example, this raises "Invalid argument: Requested more than 0 entries, but params is empty."
```python
tf.gather_nd(tf.zeros([2, 0, 5]), [[0]])
```

This alternative using tf.gather should be equivalent, but does not raise any error.
It returns an empty tensor of the right shape (1, 0, 5).
```python
tf.gather(tf.zeros([2, 0, 5]), [0])
```

The tf.gather_nd example works fine if the tensor is not empty. This returns a tensor of shape (1, 1, 5).
```python
tf.gather_nd(tf.zeros([2, 1, 5]), [[0]])
```

**Describe the expected behavior**
tf.gather_nd should be returning empty tensors of the appropriate shape just as tf.gather does. Note that while in this example tf.gather is an alternative, this is not always the case. For example, gathering based on multi-dimensional indices would force using tf.gather_nd, and any code that might face empty tensors now needs to handle these as corner cases.

**Standalone code to reproduce the issue**
The single line examples above are enough to reproduce the issue.

**Comment by leandro-gracia-gil** [comment]
I am aware of the documentation. That is precisely why I'm reporting this as an inconsistent behavior.

**Comment by rmothukuru** [comment]
@leandro-gracia-gil,
Can you please let us know why do you want to use Empty Tensors? Thanks!

**Comment by leandro-gracia-gil** [comment]
Rather than using empty tensors, what I want is not to have to code workarounds for tf.gather_nd if one of my tensors happens to be empty.

My use case involves using tf.gather_nd with the tensors in a nested structure. Depending on the situation, some of the tensors might have an inner dimension (not indexed by tf.gather_nd) with size 0, effectively making the whole tensor empty. However, because tf.gather_nd fails with empty tensors even if indexing does not happen in empty dimensions, the code fails in these cases. This is not the case of tf.gather, which correctly returns an empty tensor of the right shape after indexing the appropriate (non-empty) axes.

Unfortunately, I actually need to index 2 dimensions at once based on tensor indices, which means I must use tf.gather_nd. So, I'm being forced to apply ugly workarounds with tf.cond and tf.size to detect when a tensor is empty and avoid using tf.gather_nd altogether in these cases. The fact that tf.gather works fine with empty tensors but tf.gather_nd does not in equivalent scenarios is why I decided to submit this as an inconsistent behavior issue.

Hope this clarifies things a bit. The code I showed above is just the simplest way to reproduce the issue I could find.

**Comment by leandro-gracia-gil** [comment]
Replying to avoid it from closing automatically. Let me know if any further info is required.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by leandro-gracia-gil** [comment]
I'm closing this. It's been 3 years and I am no longer using TensorFlow. If there's anyone else interested, feel free to reopen.
