### ISSUE TITLE
`tf.TensorArray`  can't work in `tf.while_loop`

### ISSUE THREAD

**Issue by gdhy9064** [tensorflow/tensorflow#50243]
**Describe the current behavior**
I tried to implement a model like an auto-regressive model which can recurrently generate samples, one of the ways is using `tf.TensorArray` and `tf.while_loop`, but I found it would go wrong. [Here](https://colab.research.google.com/gist/gdhy9064/9b59b7f9097b506446d68f1b656316db/test.ipynb) is a gist for reference. I have simplified the source, this gist is just for illustration.

**Describe the expected behavior**
I can use another way with `tf.keras.backend.rnn` to reach my goal, but I just wonder what the wrong is in this way.

**Comment by tilakrayal** [comment]
@gdhy9064 ,

Can you please refer the links with similar error.It helps.[Link1](https://stackoverflow.com/questions/43849693/how-tensorarray-and-while-loop-work-together-in-tensorflow/43853600),[Link2](https://stackoverflow.com/questions/43701631/tensorflow-while-loop-with-tensorarray),[Link3](https://www.tensorflow.org/api_docs/python/tf/while_loop).
Thanks

**Comment by gdhy9064** [comment]
@tilakrayal ,
Many thanks to you, these links help me a lot. It is my first time to use `tf.TensorArray`, and I have made a careless mistake in the wrong usage of ` tf.TensorArray.write`, I should have received its return value as a new `tf.TensorArray`, but I didn't.
