### ISSUE TITLE
The performance of the saved model and the performance of the trained model seem to be different 

### ISSUE THREAD

**Issue by RayGuo-C** [tensorflow/tensorflow#50250]
I use tensorflow2.4 and generate images by using the GAN method.

During the training stage, the generated model at one certain step is good. And then I save it by .tf. However, when I load the model again and plan to generate new images, these images are pretty terrible. (I have tried many times). This should not be a common issue for the GAN method. So could you please tell me the reason why there are huge differences after saving the model?

**Comment by tilakrayal** [comment]
@RayGuo-C ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Thanks!
