### ISSUE TITLE
Use custom model_spec for object detection

### ISSUE THREAD

**Issue by mrjoelc** [tensorflow/tensorflow#50251]
**System information**
- MacOS
- TensorFlow from COLAB

I would like to use TF Lite Model Maker for transfer learning using a different model from EfficentDet[0-4].

so, is possible to use a different model spec?
if yes, how can I get model_spec for different model like ssd mobile net?

here is the problem:
 spec = model_spec.get('efficientdet_lite0')

**Comment by rmothukuru** [comment]
@mrjoelc,
Can you please go through the [Tutorial of Object Detection with TensorFlow Lite Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection) and let us know if it helps? Thanks!

**Comment by mrjoelc** [comment]
> @mrjoelc,
> Can you please go through the [Tutorial of Object Detection with TensorFlow Lite Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection) and let us know if it helps? Thanks!

I came directly from this tutorial. If I want to do transfer learning using model maker but for a net different from EfficentDet how can I do? for what I understood I need a "model_spec" but I don't know where to find a model_spec different from EfficientDet

**Comment by mohantym** [comment]
Hi @mrjoelc ! I have attached a relevant [thread](https://blog.tensorflow.org/2021/06/easier-object-detection-on-mobile-with-tf-lite.html) for usage of ssd mobilenet in model_spec.get() . Thank you!
