### ISSUE TITLE
Bug in keras custom layer

### ISSUE THREAD

**Issue by Oezkan23** [tensorflow/tensorflow#50254]
System: Python 3.8.3 64-bit | Qt 5.12.9 | PyQt5 5.12.3 | Linux 5.8.0-55-generic 
              keras (newest version)
```#!/usr/bin/env python3
from keras.layers import Layer
import numpy as np
from keras.layers import Input
from keras.models import Model 

InputTensor = [0.1,0.2,0.3]      # Attention! Different tensors cause errors. 
                                 # See  below the code!

InputTensor = np.array(InputTensor) 

class MyLayer(Layer):
    
    def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)
    def build(self, input_shape):
        self.built = True
        super(MyLayer,self).build(input_shape)

    def call(self, x):
        return x

inputlayer = Input(shape = InputTensor.shape)
layer = MyLayer()(inputlayer)

model = Model(inputlayer, layer ) 
model.summary()

Output = model.predict(InputTensor)
ausgabe = np.array(Output)
print("dim(Output) = "+str(output.ndim))
print("Output = "+str(Output))
```

1. Input tensor [0.1,0.2,0.3] cause no problems. Output is [[0.1][0.2][0.2]]. Access to tensor elements are possible. model.summary is (None,2), ndim is 2.
2. Input tensor [[0.1, 0.2,0.3],[0.2,0.3,0.4],[0.3,0.4,0.5]] has an output as [[0.1 0.2 0.3][0.2 0.3 0.4][0.3 0.4 0.5]] and model.summary indicate a shape like (None,3,3) so that a tensor of tree dimensions is expected. ndim should be 3 instead of 2! Access to tensor elements is possible if you consider 2 dimensions instead of 3.
3. Input tensor [[0.1,0.2,0.3],[0.2,0.3,0.4]] generates an error message. It expected a shape of (None,2,3) and found only (None,3) although model.summary shows (None,2,3). 

It shouldn't have any influence how many dimensions a tensor has, nor how big its elements are!
My task is, to get access to single elements of a tensor to generate an output tensor like
```
class MyLayer(Layer):
    def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)
    def build(self, input_shape):
        self.built = True
        super(MyLayer,self).build(input_shape)

    def call(self, x):
        OutputTensor = [[0.0, 0.0],
                        [0.0, 0.0]]
        OutputTensor[0][0] = x[0][0]
        OutputTensor[1][1] = x[1][0]
        OutputTensor[1][0] = x[2][0]
        return OutputTensor
```

**Comment by tilakrayal** [comment]
@Oezkan23 ,

Please, fill issue template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose).Also please confirm whether you are facing similar error(**AttributeError: 'list' object has no attribute 'ndim')** or different error while executing the code.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/d107929a3c8ee2f1d65e0d7641311f35/50254.ipynb) of it here.

Thanks!

**Comment by Oezkan23** [comment]
Sorry, I was mistaken because I had German expressions in the code.

The end of the code should be:
```
Output = model.predict(InputTensor)
output = np.array(Output)
print("dim(Output) = "+str(output.ndim))
print("Output = "+str(Output))
```
