### ISSUE TITLE
tf.data.experimental.service does not support from_generator

### ISSUE THREAD

**Issue by mikael-epigram** [tensorflow/tensorflow#50252]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Tensorflow docker image (tensorflow/tensorflow:2.5.0-gpu)
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Get error message and trace;
```
2021-06-14 09:56:03.953422: W tensorflow/core/framework/op_kernel.cc:1755] Invalid argument: ValueError: callback pyfunc_0 is not found

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 238, in __call__
    raise ValueError("callback %s is not found" % token)

ValueError: callback pyfunc_0 is not found
```
**Describe the expected behavior**
I expect the dataset to handle data from generators. 

In this instance, I would expect to get the same output as if `tf.data.experimental.service.distribute` was not applied to the dataset, or if `tf.data.Dataset.from_generator` was replaced with `tf.data.Dataset.range(5)`.

While the documentation states explicitly that `processing_mode="distributed_epoch"` has limitations, this is not the case for  `processing_mode="parallel_epochs"` where it is stated that you can ["Create the dataset however you were before using the tf.data service."](https://www.tensorflow.org/api_docs/python/tf/data/experimental/service#using_the_tfdata_service_from_your_training_job)

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**

minimal dataset:
```
    import tensorflow as tf

    ds = (
        tf.data.Dataset.from_generator(
            range,
            output_signature=(tf.TensorSpec(shape=(), dtype=tf.int32)),
            args=[5])
        .apply(tf.data.experimental.service.distribute(
            processing_mode="parallel_epochs",
            service='grpc://0.0.0.0:32121')
        )
    )

    for data in ds:
        print(data)
```
minimal worker code (run on same device):
```
import tensorflow as tf
dispatch_config = tf.data.experimental.service.DispatcherConfig(port=32121)
dispatcher = tf.data.experimental.service.DispatchServer(dispatch_config)
worker_config = tf.data.experimental.service.WorkerConfig(
        port=32122,
        dispatcher_address="0.0.0.0:32121",
        worker_address="0.0.0.0:32122",
)
worker = tf.data.experimental.service.WorkerServer(worker_config)
dispatcher.join()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by kvignesh1420** [comment]
@mikael-epigram the following worked for me:

```python
# interpreter 1
In [1]: import tensorflow as tf
   ...: dispatch_config = tf.data.experimental.service.DispatcherConfig(port=32121)
   ...: dispatcher = tf.data.experimental.service.DispatchServer(dispatch_config)
   ...: worker_config = tf.data.experimental.service.WorkerConfig(
   ...:         port=32122,
   ...:         dispatcher_address="localhost:32121",
   ...:         worker_address="localhost:32122",
   ...: )
   ...: worker = tf.data.experimental.service.WorkerServer(worker_config)
   ...: dispatcher.join()
   ...:
```

```python
# interpreter 2
In [2]: import tensorflow as tf
   ...: dataset = tf.data.Dataset.range(10)
   ...: dataset = dataset.apply(tf.data.experimental.service.distribute(processing_mode="parallel_epochs", service="grpc://localhost:32121"))
   ...: print(list(dataset.as_numpy_iterator()))
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

can you try replacing `0.0.0.0` with `localhost` and try?

**Comment by UsharaniPagadala** [comment]
@mikael-epigram 

Looking at the error log seems it is similar to [#23885](https://github.com/tensorflow/tensorflow/issues/23885),and let me know if it helps.Thanks

**Comment by mikael-epigram** [comment]
@UsharaniPagadala 

I don't think that issue is relevant.

My issue is with using `tf.data.Dataset.from_generator` together with `tf.data.experimental.service` servers.

**Comment by sachinprasadhs** [comment]
In the upcoming version of Tensorflow 2.6, there are some changes made on` tf.data` side as mentioned in the release note.
Check if any of the below update help your cause. 

`Added target_workers param to data_service_ops.from_dataset_id and data_service_ops.distribute. Users can specify "AUTO", "ANY", or "LOCAL" (case insensitive). If "AUTO", tf.data service runtime decides which workers to read from. If "ANY", TF workers read from any tf.data service workers. If "LOCAL", TF workers will only read from local in-processs tf.data service workers. "AUTO" works well for most cases, while users can specify other targets. For example, "LOCAL" would help avoid RPCs and data copy if every TF worker colocates with a tf.data service worker. Currently, "AUTO" reads from any tf.data service workers to preserve existing behavior. The default value is "AUTO".`

**Comment by mikael-epigram** [comment]
Those changes deal with optimizing which workers to read data from. This is not relevant for the issue.

**Comment by aaudiber** [comment]
@mikael-epigram Thanks for reporting this. As you found, tf.data service does not work with datasets created using `from_generator`, even though this limitation wasn't called out in the docs. https://github.com/tensorflow/tensorflow/commit/c9eafd47de1385390a659da5d97e7602b7f62185 will update the documentation to call out the limitation until we have a way to address it. For now, is it possible to write your dataset in a way that doesn't use `from_generator`?

**Comment by mikael-epigram** [comment]
The dataset is stored in a database, and requires some non-trivial computation to extract data, which then comes in large chunks. This is made efficient by storing some intermediate state, hence the generator. To not use `from_generator` is possible, eg. by using `map`, but it would mean it would be harder to reuse the intermediate state, making the input pipeline very inefficient.

I think for now I will have to pursue a non-tensorflow solution for the input pipeline 😔

**Comment by aaudiber** [comment]
To make this work well with TF, we would need TF kernels for reading the data from the specific type of database you are using. [tensorflow/io](https://github.com/tensorflow/io/tree/master/docs/tutorials) has many custom dataset implementations that you could use for reference.
