### ISSUE TITLE
Monolithic build for Tf Lite with CMake

### ISSUE THREAD

**Issue by keidav01** [tensorflow/tensorflow#50259]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5
- Python version: 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): Cmake 3.16
- GCC/Compiler version (if compiling from source): 7.4
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I want to create a monolithin build of the libtensorflow-lite.so library file. 

With bazel, you used to just add `--config=monolithic` to the `bazel build` command in order to stop having to ensure libraries like libflatbuffers.a, libruy.a, etc. had to be passed on along with libtensorflow-lite.so.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Steps provided from here:
https://www.tensorflow.org/lite/guide/build_cmake

**Comment by abattery** [comment]
@terryheo could you take a look at this?

**Comment by terryheo** [comment]
A monolithic static build is not available now.

But you can use a monolithic shared library for C API.
https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library

**Comment by keidav01** [comment]
We already have a codebase that is specifically designed for the C++ API. I don't think it will be trivial to change. Furthermore, I think the C API has considerably more limitations than that of the standard normal API. Would I be correct in these statements?

Is there any way for me to remove the dependency of certain libraries such as `libruy.a`. I figured that if I set it to off in CMAKE, I will not need to link to the libtensorflow-all.so file afterwards. I set it to off within the CMAKE settings, but it provokes failures during the android build:
`
CMARGS="-DTFLITE_ENABLE_XNNPACK=OFF \
        -DTFLITE_ENABLE_RUY=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DTFLITE_ENABLE_NNAPI=OFF \
        -DTFLITE_ENABLE_MMAP=OFF"
        
CMARGS="$CMARGS -DCMAKE_TOOLCHAIN_FILE=$PKG_DIR/android-ndk-r18/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=$ANDROID_ARM_ARCH \
        -DANDROID_PLATFORM=$ANDROID_PLATFORM"

$CMAKETOOLS/cmake $CMARGS $TFLITE_ROOT_DIR
`
This provokes the following set of errors: 
`
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/flatbuffer_conversions.cc:16:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/flatbuffer_conversions.h:28:
/home/keidav01/devenv/tensorflow/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 58%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/dequantize.cc.o
[ 58%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/depthwise_conv.cc.o
[ 60%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/detection_postprocess.cc.o
[ 60%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/div.cc.o
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/conv.cc:15:
/home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/internal/optimized/integer_ops/conv.h:18:10: fatal error: 'ruy/profiler/instrumentation.h' file not found
#include "ruy/profiler/instrumentation.h"  // from @ruy
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 60%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/eigen_support.cc.o
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/delegates/telemetry.cc:16:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/delegates/telemetry.h:22:
/home/keidav01/devenv/tensorflow/tensorflow/lite/experimental/acceleration/configuration/configuration_generated.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 60%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/elementwise.cc.o
[ 60%] Building CXX object CMakeFiles/tensorflow-lite.dir/kernels/embedding_lookup.cc.o
1 error generated.
CMakeFiles/tensorflow-lite.dir/build.make:192: recipe for target 'CMakeFiles/tensorflow-lite.dir/delegates/telemetry.cc.o' failed
make[2]: *** [CMakeFiles/tensorflow-lite.dir/delegates/telemetry.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc:26:10: fatal error: 'ruy/ruy.h' file not found
#include "ruy/ruy.h"  // from @ruy
         ^~~~~~~~~~~
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/c/c_api_experimental.cc:24:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/c/c_api_internal.h:25:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/op_resolver.h:23:
/home/keidav01/devenv/tensorflow/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/op_resolver.cc:16:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/op_resolver.h:23:
/home/keidav01/devenv/tensorflow/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/c/c_api.cc:20:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/c/c_api_internal.h:25:
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/core/api/op_resolver.h:23:
/home/keidav01/devenv/tensorflow/tensorflow/lite/schema/schema_generated.h:21:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/tensorflow-lite.dir/build.make:75: recipe for target 'CMakeFiles/tensorflow-lite.dir/core/api/flatbuffer_conversions.cc.o' failed
make[2]: *** [CMakeFiles/tensorflow-lite.dir/core/api/flatbuffer_conversions.cc.o] Error 1
/home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/audio_spectrogram.cc:22:10: fatal error: 'flatbuffers/flexbuffers.h' file not found
#include "flatbuffers/flexbuffers.h"  // from @flatbuffers
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/depthwise_conv.cc:16:
/home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/internal/optimized/integer_ops/depthwise_conv.h:23:10: fatal error: 'ruy/profiler/instrumentation.h' file not found
#include "ruy/profiler/instrumentation.h"  // from @ruy
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/keidav01/devenv/tensorflow/tensorflow/lite/kernels/detection_postprocess.cc:24:10: fatal error: 'flatbuffers/flexbuffers.h' file not found
#include "flatbuffers/flexbuffers.h"  // from @flatbuffers
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by pkgoogle** [comment]
Hi @keidav01 does the current bazel build with monolithic flag work for you?
