### ISSUE TITLE
make_csv_dataset fails inside Dataset.interleave()

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#50260]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): debian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
`make_csv_dataset`  fails  when used as a map function inside `data.Dataset.interleave()`

**Describe the expected behavior**
It must create datasets

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
files = tf.data.Dataset.list_files("*.csv")
ds3 = files.interleave(lambda x: tf.data.experimental.make_csv_dataset(x, batch_size=1))
```

[link to colab](https://colab.research.google.com/gist/eli-osherovich/ac1e62d1c2ba919fd450dfec4c178ab9/test.ipynb)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Running this code:
```python
files = tf.data.Dataset.list_files("*.csv")
ds3 = files.interleave(lambda x: tf.data.experimental.make_csv_dataset(x, batch_size=1))
```
I get the following error:
```
OperatorNotAllowedInGraphError: in user code:

    <ipython-input-5-fcdae26c49e4>:2 None  *
        lambda x: tf.data.experimental.make_csv_dataset(x, batch_size=1))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/experimental/ops/readers.py:480 make_csv_dataset_v2  **
        filenames = _get_file_names(file_pattern, False)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/data/experimental/ops/readers.py:1135 _get_file_names
        file_names = list(gfile.Glob(file_pattern))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py:383 get_matching_files
        return get_matching_files_v2(filename)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py:449 get_matching_files_v2
        for single_filename in pattern
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:520 __iter__
        self._disallow_iteration()
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:516 _disallow_iteration
        self._disallow_in_graph_mode("iterating over `tf.Tensor`")
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:496 _disallow_in_graph_mode
        " this function with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by eli-osherovich** [comment]
@saikumarchalla  friendly ping

**Comment by tilakrayal** [comment]
@rmothukuru ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/6f817f8b3efce2b2415462f05e20dad3/50260.ipynb).

**Comment by eli-osherovich** [comment]
@jvishnuvardhan 
Any update on this?

**Comment by aaudiber** [comment]
Thanks for reporting this @eli-osherovich, this looks like a real bug that I'll work on fixing.

The reason this hasn't come up before is that calling `make_csv_dataset` inside of `interleave` isn't usually necessary. `make_csv_dataset` will incorporate its own `interleave` when you set `num_parallel_reads`. i.e., instead of writing

```python
files = tf.data.Dataset.list_files("*.csv")
ds3 = files.interleave(lambda x: tf.data.experimental.make_csv_dataset(x, batch_size=1))
```

you could write

```python
ds3 = tf.data.experimental.make_csv_dataset("*.csv", batch_size=1, num_parallel_reads=tf.data.AUTOTUNE)
```

The second version may also be more performant, because it will use multiple threads to read from CSV files in parallel.

**Comment by eli-osherovich** [comment]
Thanks, @aaudiber 

May real code is a bit more complex: in my case each CSV file represents a  different class (with big skew between classes) and I wanted to do sort of round-robin sampling.

**Comment by aaudiber** [comment]
@eli-osherovich [CsvDataset](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset) accepts `Tensor` filenames, so you could use it directly from inside of `interleave`. `make_csv_dataset` on the other hand requires `string` filenames, so that it can infer column names based on the filenames. It would be convenient if `make_csv_dataset` could support `Tensor` filenames as well, but right now your best option is to use `CsvDataset` instead.

**Comment by eli-osherovich** [comment]
Thanks, @aaudiber  I will try CsvDataset, even though, I would prefer the automation of `make_csv_dataset`
