### ISSUE TITLE
TypeError: An op outside of the function building code is being passed 

### ISSUE THREAD

**Issue by imnimesh** [tensorflow/tensorflow#50276]
Hi, i am trying to replicate this https://www.kaggle.com/ratthachat/image-captioning-by-effnet-attention-in-tf2-1/notebook but when i try to run the below code 

```
# captions on the train set
rid = np.random.randint(0, len(img_name_train))
image = img_name_train[rid]
real_caption = ' '.join([tokenizer.index_word[i] for i in cap_train[rid] if i not in [0]])
result, attention_plot = evaluate(image)

print ('Real Caption:', real_caption)
print ('Prediction Caption:', ' '.join(result))
plot_attention(image, result, attention_plot)
```
i am getting this below error

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2

tensorflow version i am using is 2.4.1.

**Comment by UsharaniPagadala** [comment]
@imnimesh 

Looking at the error log seems it is similar [#32889](https://github.com/tensorflow/tensorflow/issues/32889),and let us know if it helps.Thanks
