### ISSUE TITLE
Bug: Bazel 3.7.2 fails to build with GCC 11.1.0 on ARMv8

### ISSUE THREAD

**Issue by samcom12** [tensorflow/tensorflow#50277]
Hi, 
`Bazel 3.7.2.` is failing to build on  `ARMv8`, hopefully, in the latest Bazel, they have fixed it.
Any plan to use upgraded Bazel?

**Comment by eli-osherovich** [comment]
What error do you get?

**Comment by samcom12** [comment]
With GCC-11 we need to explicitely add `#include <limits>` and `#include <stdexcept>`.

**Comment by eli-osherovich** [comment]
This issue was fixed upstream. See #50176 and link therein.

**Comment by tilakrayal** [comment]
@samcom12 ,

Looks like this is duplicate of issue #50303.Can you please close this issue, since it is already being tracked there? Thanks!
