### ISSUE TITLE
CUPTI could not be loaded & cupti.dll not found

### ISSUE THREAD

**Issue by BestSithInEU** [tensorflow/tensorflow#50273]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Windows 10
- TensorFlow installed from: Source
- TensorFlow version:  2.5.0
- Python version: 3.8.10
- CUDA/cuDNN version:  11.2 / 8.1.0 I believe
- GPU model and memory: RTX 2080
This is the error I've get;
I had [this issue](https://github.com/tensorflow/tensorflow/issues/43030#issuecomment-799969225). Once I did that copy trick, I started to get this issue...
![Ekran görüntüsü 2021-06-15 065118](https://user-images.githubusercontent.com/67585935/121990242-1d040500-cda6-11eb-9a79-b32762356f17.png)

**Comment by sachinprasadhs** [comment]
Can you try the solution mentioned [here](https://stackoverflow.com/questions/56860180/).

**Comment by BestSithInEU** [comment]
Nope, my paths are same;

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
> C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.2
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\extras\CUPTI\lib64
> C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.3.0\
> C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR

And I have `cupti64_2020.3.0.dll`, `cupti64_110.dll` in both `/CUDA/v11.2/bin` & `/CUDA/v11.2/extras/CUPTI/lib64`

**Comment by sachinprasadhs** [comment]
Can you rename the `cupti64_2020.3.0.dll `to `cupti64_112.dll` and try again.

**Comment by tooHotSpot** [comment]
https://stackoverflow.com/a/67731160/8523656

**Comment by Nathan-Chell** [comment]
> https://stackoverflow.com/a/67731160/8523656 Add C:\Program Files\NVIDIA Corporation\Nsight Systems 2020.4.3\target-windows-x64 add to PATH and both `cupti.dll` and `cupti64_11.dll` will be pulled ftom there.

Worked for me, not forgetting to restart VS Code
