### ISSUE TITLE
ValueError: image not in JPEG format for Custom Object Detection using TF Lite Model Maker

### ISSUE THREAD

**Issue by NSTiwari** [tensorflow/tensorflow#50281]
## URL(s) with the issue:
Codelabs Colab Notebook link for custom object detection using TF Lite Model Maker:
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_object_detection.ipynb#scrollTo=p79NHCx0xFqb

## Description of issue (what needs changing):
I have been following the above mentioned Codelabs for training a model for custom object detection using TF Lite Model Maker. However, when I try importing the image dataset as a CSV from local path, I face an error that says, `ValueError: image not in JPEG format`; although all the training, validation and test images are of the said format i.e. JPEG.  

### Clear description
Below is the screenshot of the same.
![image](https://user-images.githubusercontent.com/37960279/122074390-ce428380-ce16-11eb-915e-703b84aed02e.png)

### Correct links

Is the link to the source code correct?
Yes

### Parameters defined
CSV file.

Are all parameters defined and formatted correctly?
Yes

### Returns defined

Are return values defined?
Yes

### Raises listed and defined

Are the errors defined? For example,
https://github.com/sozercan/tensorflow-object-detection/blob/master/tensorflow-object-detection/generic_create_pascal_tf_record.py

### Usage example

Is there a usage example?
Yes, the example is taken from the following Codelabs: https://codelabs.developers.google.com/tflite-object-detection-android#8

**Comment by NSTiwari** [comment]
Awaiting a response on this issue.

**Comment by ymodak** [comment]
I see you have replaced the dataset from tutorial with your dataset. Can you confirm if all Images are in `jpeg` format. Also is it possible for you to provide gist as reference. It can help to debug quicker.

**Comment by NSTiwari** [comment]
@ymodak, it is confirmed that all the images are in `jpeg` format. Below is a gist as a reference as requested by you.

https://gist.github.com/NSTiwari/d2ae2b8af600d3865a2fd810691ed8f2

**Comment by NSTiwari** [comment]
Waiting for an update on this.

**Comment by NSTiwari** [comment]
I've resolved the issue. I had to explicitly and programmatically convert all the images into 'RGB' format using PIL library and it worked just fine afterwards. Thanks for the support, closing this issue here.
