### ISSUE TITLE
Keras generic_utils Mangles ConvLSTM2D Default Layer Name

### ISSUE THREAD

**Issue by craymichael** [tensorflow/tensorflow#50288]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.9.4

**Describe the current behavior**
```python
>>> import tensorflow as tf
>>> tf.keras.layers.ConvLSTM2D(1, 1).name
'conv_lst_m2d_0'
```

**Describe the expected behavior**
```python
>>> import tensorflow as tf
>>> tf.keras.layers.ConvLSTM2D(1, 1).name
'conv_lstm_2d_0'
```

**Other info**
Problem caused here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L2435
If a name is not provided to a `Layer` then it used the `generic_utils` function `to_snake_case`, which shows unexpected behavior here:
```python
>>> from tensorflow.python.keras.utils import generic_utils
>>> generic_utils.to_snake_case('ConvLSTM2D')
'conv_lst_m2d'
```

An ad hoc fix here seems inelegant in `generic_utils`. Moreover, changing the regex in the linked function will likely have repercussions for many other names where this may not be an issue.

Thoughts on setting a default name within ConvLSTM2D __init__ instead? https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional_recurrent.py#L154
Something passed to super like `name=kwargs.get('name', backend.unique_object_name('conv_lstm_2d', zero_based=True))`? I don't have an elegant solution here.

**Comment by craymichael** [comment]
Ok here is a quick fix which appears to me at least to not affect anything other than intended. Bonus is a special naming case for ReLU, which doesn't need to be included. All I did beyond that is remove the numerical regex pattern in the first regex line.

```python
import re
from tensorflow.python.keras.utils.generic_utils import to_snake_case
from tensorflow.python.keras.engine.base_layer import Layer

layers = Layer.__subclasses__()


def to_snake_case_proposed(name):
    name = name.replace('ReLU', 'Relu')
    intermediate = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    insecure = re.sub('([a-z])([A-Z])', r'\1_\2', intermediate).lower()
    # If the class is private the name starts with "_" which is not secure
    # for creating scopes. We prefix the name with "private" in this case.
    if insecure[0] != '_':
        return insecure
    return 'private' + insecure


for layer in sorted(layers, key=lambda x: x.__name__):
    current = to_snake_case(layer.__name__)
    proposed = to_snake_case_proposed(layer.__name__)
    if current != proposed:
        print(current, proposed)
```

Output (left is current behavior/default, right is with the proposed change):

```text
conv_lst_m2d_cell conv_lstm2d_cell
leaky_re_lu leaky_relu
p_re_lu p_relu
re_lu relu
thresholded_re_lu thresholded_relu
```
Looks like better defaults to me.

**Comment by saikumarchalla** [comment]
@craymichael Could you please submit a PR to fix the issue if you are aware of the changes required. Thanks!

**Comment by craymichael** [comment]
I opened PR #50374 to resolve this issue, awaiting feedback from a tensorflower

**Comment by rthadur** [comment]
As mentioned here https://github.com/tensorflow/tensorflow/pull/50374#issuecomment-884517069 , the issue has been fixed in a separate change , closing this issue. Thank you
