### ISSUE TITLE
Keras Reshape layers are not folded when converted to TFLite

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#50286]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11, Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): `2.5.0`, `tf-nightly`

### 2. Code

Keras `Reshape` layers are not correctly constant folded when converted to TFLite.

Consider the following two models which either use `tf.keras.layers.Reshape((50, 2))(x)`  or `tf.reshape(x, (-1, 50, 2))` to reshape tensors. The Keras layer here is equivalent to  calling `tf.reshape(x, (tf.shape(x)[0], 50, 2))` which unfortunately doesn't get fused due to a dynamic batch dimension.
This can be worked around by manually setting the Keras model batch size to 1, but I think this should be handled by the converter instead so that the default Keras reshape layer also gets converted to an efficient reshape op.

```python
import tensorflow as tf

def unfused_model():
    img = tf.keras.layers.Input(shape=(3, 3, 10))
    x = tf.keras.layers.Conv2D(100, (3, 3))(img)
    x = tf.keras.layers.Reshape((50, 2))(x)
    return tf.keras.Model(img, x)

def fused_model():
    img = tf.keras.layers.Input(shape=(3, 3, 10))
    x = tf.keras.layers.Conv2D(100, (3, 3))(img)
    x = tf.reshape(x, (-1, 50, 2))
    return tf.keras.Model(img, x)

def convert_model(model, filename):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    with open(filename, "wb") as f:
        f.write(converter.convert())

convert_model(unfused_model(), "/tmp/unfused_model.tflite")
convert_model(fused_model(), "/tmp/fused_model.tflite")
```

`unfused_model.tflite` | `fused_model.tflite`
---|---
<img width="219" alt="Screenshot 2021-06-15 at 18 36 12" src="https://user-images.githubusercontent.com/13285808/122098756-207ca800-ce09-11eb-9880-2b91b147cb5d.png"> | <img width="145" alt="Screenshot 2021-06-15 at 18 36 05" src="https://user-images.githubusercontent.com/13285808/122098753-1fe41180-ce09-11eb-9530-fc319eac8097.png">

### 3. Possible Solution

I think it would be possible to implement a `tfl.reshape` constant folder even for the dynamic batch size case that checks if only one dimension of the reshape is dynamic and replaces this with `-1`. However, this would opt out of possible shape error checking in cases the reshape would be invalid. On the other hand from looking at the netron graph it seems like the batch dimension is fixed to 1 anyway, so I am not sure why the reshape didn't get folded correctly in the first place, but let me know if I am missing something.

**Comment by abattery** [comment]
Thanks for filing up the feature request. Also, we are welcoming the community contribution in TensorFlow Lite MLIR converter regarding this feature request.

**Comment by lgeiger** [comment]
> Also, we are welcoming the community contribution in TensorFlow Lite MLIR converter regarding this feature request.

I am not sure if I would consider this as feature request, to me it seems more like a bug in the fusion rules which people tend to run into when using e.g. the Keras application MobileNets (see https://github.com/tensorflow/tensorflow/issues/45256#issuecomment-737985193).

Keras Reshape layers used to be converted correctly in TensorFlow version 2.2 with the MLIR graphdef converter since the batch size was always set to one before passing it into the MLIR converter:
https://github.com/tensorflow/tensorflow/blob/691563cb3e9c0d46058e2a7b8d270bc29a0dfe19/tensorflow/lite/python/lite.py#L824-L827

@abattery in the current converter it still looks like the batch size is fixed to one at some point when looking at the tflite flatbuffer (although I am not sure where this happens), or is it intended that the batch size stays dynamic? If so could you comment on the proposed solution I outlined above, since I am not 100% sure what the desired behaviour in case of dynamic dimension would be here.

**Comment by hlc1209** [comment]
I have to say that this problem stil exist in the latest version of tensorflow (colab 2.7.0)

It prevents me from generating a working model on the Arduino 33 ble.

This is a serious problem because we cannot even run this [official demo](https://www.tensorflow.org/lite/performance/post_training_integer_quant)

**Comment by MeghnaNatraj** [comment]
The solution should be resolved by setting Keras `batch_size` to 1. As this issue has a workaround and doesn't block major workflows, it will be marked as closed.
