### ISSUE TITLE
Device interconnect StreamExecutor with strength 1 edge matrix

### ISSUE THREAD

**Issue by samanemami** [tensorflow/tensorflow#50285]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 2.4
- Python version: 3.6.5

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am running the BoostedTree, and for the only binary problem, I faced the following error.
I am using the CPU version of the TensorFlow, and it is working fine for multi-class classification
```python
Skipping registering GPU devices...
2021-06-15 17:58:51.972609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-15 17:58:51.972635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 
2021-06-15 17:58:51.972653: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N N 
2021-06-15 17:58:51.973854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N N 
```

**Other info / logs** Include any logs or source code that would be helpful to
```python
 installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.

```

**Comment by tilakrayal** [comment]
@samanemami ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.
Thanks!

**Comment by tilakrayal** [comment]
Also please try to execute code in virtual environment and limiting GPU [memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) using any of the methods listed in this guide and check if it helps.Thanks!

**Comment by samanemami** [comment]
@tilakrayal  Thank you.
I fixed the issue by limiting the GPU.
