### ISSUE TITLE
tf2 could NOT start more than 2 processes/sessions (one process one tf session) on intel i9 processor while tf1.15.4 is ok

### ISSUE THREAD

**Issue by lnshi** [tensorflow/tensorflow#50298]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
   ```
   No
   ```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   ```
   Linux 289d7745a47e 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 GNU/Linux
   ```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
   ```
   N.A.
   ```
- TensorFlow installed from (source or binary):
   ```
   binary, direct pip install, so far tested with version 2.3.1 and 2.5.0
   ```
- TensorFlow version (use command below):
   ```
   2.3.1, 2.5.0
   ```
- Python version:
   ```
   Python 3.6.12
   ```
- Bazel version (if compiling from source):
   ```
   N.A.
   ```
- GCC/Compiler version (if compiling from source):
   ```
   gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
   Copyright (C) 2016 Free Software Foundation, Inc.
   This is free software; see the source for copying conditions.  There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   ```
- CUDA/cuDNN version:
   ```
   N.A.
   ```
- GPU model and memory:
   ```
   N.A.
   ```

1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
   ```
   N.A.
   ```
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
   ```
   v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
   ```

**Describe the current behavior**

tensorflow2 could **NOT** start more than 2 processes on **intel i9 processor**? (within docker container), i am not quite sure i9 processors is the issue here, but this is working great on my old laptop.

And i tested the exact behaviour with tensorflow 1.15.4 and it is ok.

```
Docker version 20.10.6, build 370c289
```
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
```
So far i tested on tensorflow `2.3.1` and `2.5.0`,  both cannot start more than 2 tf sessions, then behaviour is that for the first 2 tf sessions it is pretty quick, like a few seconds, but when i tried to start the 3rd tf session, it took quite long, like 5 or 6 mins+, eventually it still cant start, but one of the previous started tf session will get killed silently.

**Standalone code to reproduce the issue**

`tf2.py` to load model:
```
import tensorflow as tf

model = tf.saved_model.load("/models/tf2_models/od_ssd_mobilenet/1")

print('233333-------------')

while True:
  pass
```

the `od_ssd_mobilenet` model i download from here: [http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz)

- Step 1: do `python tf2.py &` to load the model and put the process to the background, and wait the `233333-------------` message get printed;
- Step 2: then use `ps -ef | grep tf2.py` to check the process is running;
- Repeat step 1 and 2 to start 2 ok processes;
- Repeat step 1 and 2 to try to start the 3rd process, you will find out it will take super long, and when eventually you see the `233333-------------`  message get printed, one of the previous 2 ok process was killed silently.

And i tested the exact behaviour with tensorflow 1.15.4 and it is ok.

the logs i had when the model was loading:
```
2021-06-16 04:33:57.384790: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-06-16 04:33:57.384844: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-06-16 04:34:00.171257: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-16 04:34:00.171318: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-16 04:34:00.171409: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (289d7745a47e): /proc/driver/nvidia/version does not exist
2021-06-16 04:34:00.171848: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
233333-------------
```

**Comment by UsharaniPagadala** [comment]
@lnshi 

Looking at the error log,seems like it is similar to this [#45930](https://github.com/tensorflow/tensorflow/issues/45930),and [#4196](https://github.com/tensorflow/tensorflow/issues/4196) and let me know if it helps.Thanks

**Comment by lnshi** [comment]
@UsharaniPagadala 

I think the concerns are totally different:

1. This issue/bug is happening on CPU deployment not GPU, and i am installing `tensorflow` not `tensorflow-gpu`;
2. The script i pasted is the simplified one to reproduce the issue, with my full procedure with **2** processes all the inferences are happening properly, no issues/errors;
3. Just previously i am able to run **more than 2** tf.Sessions/processes based on the number of the CPU cores for one model without any problem, now with this new laptop and intel i9 processors i am not able to doing this anymore.

That is why i raised this issue to check is this a bug in tf2, or some intel i9 hardware compatibilities issues? coz previously either with tf1 and tf2 i didn't encounter such issue.

Hope i made myself clear.

**Comment by lnshi** [comment]
Update
---
Tested on aws [G4dn](https://aws.amazon.com/ec2/instance-types/g4/) instance with tensorflow 2.4.1 and 2.5.0:
- Without utilising the GPU device, NO such issues, can start 3 processes and subsequent load tests are all fine;
- With GPU device, no enough GPU memory to start the 3rd process:
   ```
   2021-06-17 09:55:53.379762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13509 MB memory) -physical GPU (device: 0, name: NVIDIA Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5)
  
  31065                 ok(2nd request)
  31069                                    ok(3rd request)
  31073 ok(1st reques)  died(2nd request)
  
  0   N/A  N/A     31065      C   python3                          4567MiB
  0   N/A  N/A     31069      C   python3                          4567MiB
   ```

**Comment by UsharaniPagadala** [comment]
@lnshi 
The tested build Cuda  compatibility for tf2.5 is 11.2 .Please  check the latest [release](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0).This is also might be the reason and let us know if it helps.Thanks

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.5.0 | 3.6-3.9 | GCC 7.3.1 | Bazel 3.7.2 | 8.1 | 11.2
tensorflow-2.4.0 | 3.6-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 8.0 | 11.0
tensorflow-2.3.0 | 3.5-3.8 | GCC 7.3.1 | Bazel 3.1.0 | 7.6 | 10.1


<br class="Apple-interchange-newline">

**Comment by mihaimaruseac** [comment]
`pip install tensorflow` and `pip install tensorflow_gpu` will result in the exact same code in TF 2.x

If you want CPU-only code you have to use `tensorflow_cpu` package.

**Comment by mihaimaruseac** [comment]
The issue here seems to be a silent OOM killer when you run out of memory. It's not really the fault of TF.

**Comment by lnshi** [comment]
@mihaimaruseac  that is even more weird, i gave 7GB memory to the container, and it happens also on my local mac which has 32GB memory....

to highlight again, i never installed tensorflow-gpu, and exactly same code base working great on all my other MPBs, only on this new MBP 2021 with i9 processor i encounter this problem, t**hat is why i am checking whether TF has some compatible issues with this latest intel i9 processors**

**Comment by mihaimaruseac** [comment]
If you did `pip install tensorflow` then you installed `tensorflow-gpu`. They are exactly the same package.

**Comment by sachinprasadhs** [comment]
Could you please test with the latest version on your windows system.
If you would like to install Tensorflow cpu version only then you can follow below steps.
1. For pip install follow `pip install tensorflow-cpu` from https://pypi.org/project/tensorflow-cpu/
2. To build from source, follow the document here https://www.tensorflow.org/install/source_windows and for cpu version configure using the step mentioned [here](https://www.tensorflow.org/install/source_windows#optional_configure_the_build).
