### ISSUE TITLE
Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz 

### ISSUE THREAD

**Issue by darren-qiu** [tensorflow/tensorflow#5029]
Firstly, there is no internet access. And I'm sure protobuf is installed successly:

```
protoc --version
libprotoc 3.1.0
```

But there is the error on the tensorflow's configure:

```
./configure 
/data/home/darrenqiu/tensorflow-master /data/home/darrenqiu/tensorflow-master
Please specify the location of python. [Default is /usr/local/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/site-packages]
   
/usr/local/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] n
No GPU support will be enabled for TensorFlow
Configuration finished
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
ERROR: package contains errors: tensorflow/contrib/metrics.
ERROR: error loading package 'tensorflow/contrib/metrics': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz to /root/.cache/bazel/_bazel_root/028d9ecced2b5d3d3b3ba6868668372d/external/protobuf: Error downloading http://github.com/google/protobuf/archive/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz to /root/.cache/bazel/_bazel_root/028d9ecced2b5d3d3b3ba6868668372d/external/protobuf/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz: Proxy address 10.14.36.84:8080 is not a valid URL.
```

Are There other ways to solve in the absence of a network?

**Comment by asimshankar** [comment]
Bazel is intended for hermetic builds and when setting up the workspace for the first time, it will download required external dependencies at the precise state it wants. For example, at this time, tensorflow uses protobuf with a specific fix (see [`workspace.bzl`](https://github.com/tensorflow/tensorflow/blob/c20da14/tensorflow/workspace.bzl#L101)

Long story short, when setting up the workspace for the first time (or after a `bazel clean`), a network access is required.

**Comment by darren-qiu** [comment]
Now, the network access has been set, I'm trying to 'git clone' or 'wget', it's ok, but when I do the configure, somehow the error is still exist?

**Comment by darren-qiu** [comment]
Do you wish to build TensorFlow with GPU support? [y/N] n
No GPU support will be enabled for TensorFlow
Configuration finished
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
ERROR: package contains errors: tensorflow/c.
ERROR: error loading package 'tensorflow/c': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz to /root/.cache/bazel/_bazel_root/6e7ef39e0a4c86cda32543deecf0d6bd/external/protobuf: Error downloading http://github.com/google/protobuf/archive/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz to /root/.cache/bazel/_bazel_root/6e7ef39e0a4c86cda32543deecf0d6bd/external/protobuf/c2b3e70efd2038a54ef8973771ac58192885125e.tar.gz: Proxy address 10.14.36.84:8080 is not a valid URL.

**Comment by asimshankar** [comment]
This seems to be a result of how the proxy is configured on your machine.
This is out of our area of expertise, but perhaps you will find some hints in this bazel thread: https://github.com/bazelbuild/bazel/issues/587

**Comment by darren-qiu** [comment]
Thank you！ @asimshankar @sunil3590
To solve it, I did the following (hack) 
1. cd some_safe_folder
2. wget https://archive.openswitch.net/gmock-1.7.0.zip
3. python -m SimpleHTTPServer 8000
4. Change line 79 of models/syntaxnet/tensorflow/tensorflow/workspace.bzl from url = "https://archive.openswitch.net/gmock-1.7.0.zip" to url = "http://localhost:8000/gmock-1.7.0.zip"
Basically what you're doing is, downloading the required package manually and setting up a server to serve the package from your local machine.

**Comment by hahadashi** [comment]
> Thank you！ @asimshankar @sunil3590
> To solve it, I did the following (hack)
> 
> 1. cd some_safe_folder
> 2. wget https://archive.openswitch.net/gmock-1.7.0.zip
> 3. python -m SimpleHTTPServer 8000
> 4. Change line 79 of models/syntaxnet/tensorflow/tensorflow/workspace.bzl from url = "https://archive.openswitch.net/gmock-1.7.0.zip" to url = "http://localhost:8000/gmock-1.7.0.zip"
>    Basically what you're doing is, downloading the required package manually and setting up a server to serve the package from your local machine.
@darren-qiu @asimshankar @ry @jmhodges @eggie5 
hi, when i bazel build tensorflow, there are some wrong like"no such package '@gif_archive//':". and  i try your advice，in the file(tensorflow/workspace.bzl, `tf_http_archive(
 266         name = "gif_archive",
 267         build_file = clean_dep("//third_party:gif.BUILD"),
 268         sha256 = "34a7377ba834397db019e8eb122e551a49c98f49df75ec3fcc92b9a794a4f6d1",
 269         strip_prefix = "giflib-5.1.4",
 270         system_build_file = clean_dep("//third_party/systemlibs:gif.BUILD"),
 271         urls = [
 272             "http://127.0.0.1:8000/giflib-5.1.4.tar.gz",
 273             "http://mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz",
 274             "http://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz",
 275         ],
 276     ))`   when i repeat bazel bulid, there some message"127.0.0.1 - - [18/Apr/2020 05:02:29] "GET /giflib-5.1.4.tar.gz HTTP/1.1" 404 -" and i also get ""no such package '@gif_archive//':"."
 hope you give me some advice
