### ISSUE TITLE
The latest docker image cannot work on my computer

### ISSUE THREAD

**Issue by hnqmz** [tensorflow/tensorflow#50299]
<em>I pulled the latest tensorflow-gpu image but I cannot run this image </em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow version: docker image: 'tensorflow/tensorflow:latest-gpu-jupyter'
- CUDA/cuDNN version:CUDA version 10.2
- GPU model and memory: 2080ti * 4, each with memory 11019MB
- Docker version 19.03.8, build afacb8b7f0

**Describe the problem**
Since tensorflow-io installed by pip cannot work together with tensorflow installed by conda, I decided to use the docker image of tensorflow. I installed nvidia-docker according to this page: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker. And the result is this:
 ![捕获](https://tvax4.sinaimg.cn/large/006dgyGJgy1grk3opnyi6j30sd0h3goc.jpg)
Then, I pulled the tensorflow image by this:
`docker pull tensorflow/tensorflow:latest-gpu-jupyter`
and run this image by this:
`docker run --gpus=all -it tensorflow/tensorflow:latest-gpu bash`
then, I meet this error:
_docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled_
Why would it give this error: unsatisfied condition: cuda>=11.2

**Any other info / logs**
That's all images in this computer
![捕获](https://tvax4.sinaimg.cn/large/006dgyGJgy1grk3yb08ygj30tb06tq4o.jpg)

**Comment by jvishnuvardhan** [comment]
@hnqmz The error clearly states that `"requirement error: unsatisfied condition: cuda>=11.2, please update your driver to a newer version, or use an earlier cuda container\\n\""": unknown."`. 

It means that the latest tensorflow you are trying to install requires `cuda drivers >= 11.2` but you have `10.2` drivers. So,  select other container that requires only `cuda-10.2`. Thanks!
