### ISSUE TITLE
[_Derived_]RecvAsync is cancelled while running tensorflow RNN tutorial code on GPU

### ISSUE THREAD

**Issue by dhavalsays** [tensorflow/tensorflow#50296]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  CUDA: 11.2.0
- GPU model and memory: NVIDIA Titan RTX 24 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am running this tutorial https://www.tensorflow.org/text/tutorials/text_classification_rnn and during  training I am getting below error,

Epoch 1/10
 67/391 [====>.........................] - ETA: 18s - loss: 0.6928 - accuracy: 0.4977
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-25-d9321db1417e> in <module>
----> 1 model.fit(train_dataset, epochs=10,
      2                     validation_data=test_dataset,
      3                     validation_steps=30)

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1181                 _r=1):
   1182               callbacks.on_train_batch_begin(step)
-> 1183               tmp_logs = self.train_function(iterator)
   1184               if data_handler.should_sync:
   1185                 context.async_wait()

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py in __call__(self, *args, **kwds)
    887 
    888       with OptionalXlaContext(self._jit_compile):
--> 889         result = self._call(*args, **kwds)
    890 
    891       new_tracing_count = self.experimental_get_tracing_count()

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py in _call(self, *args, **kwds)
    915       # In this case we have created variables on the first call, so we run the
    916       # defunned version which is guaranteed to never create variables.
--> 917       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    918     elif self._stateful_fn is not None:
    919       # Release the lock early so that multiple threads can perform the call

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in __call__(self, *args, **kwargs)
   3021       (graph_function,
   3022        filtered_flat_args) = self._maybe_define_function(args, kwargs)
-> 3023     return graph_function._call_flat(
   3024         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   3025 

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1958         and executing_eagerly):
   1959       # No tape is watching; skip to running the function.
-> 1960       return self._build_call_outputs(self._inference_function.call(
   1961           ctx, args, cancellation_manager=cancellation_manager))
   1962     forward_backward = self._select_forward_and_backward_functions(

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    589       with _InterpolateFunctionError(self):
    590         if cancellation_manager is None:
--> 591           outputs = execute.execute(
    592               str(self.signature.name),
    593               num_outputs=self._num_outputs,

~\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node Adam/Adam/update/AssignSubVariableOp/_57}}]]
	 [[gradient_tape/sequential/embedding/embedding_lookup/Reshape/_54]] [Op:__inference_train_function_22715]

Function call stack:
train_function

**Describe the expected behavior**
It should work ok without issues. I have not changed any code, it is a tutorial from tensorflow official documentation. If you train on CPU there is no issue so something wrong with training on GPU

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
It is very easy to reproduce. Just run https://www.tensorflow.org/text/tutorials/text_classification_rnn in a jupyter notebook on a machine that has GPU

This seems to be similar to https://github.com/tensorflow/tensorflow/issues/33721, opening this because that previous issue was closed without a resolution.

**Comment by tilakrayal** [comment]
@dhavalsays ,

I haven't faced any issue while executing the code in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/d529b1c30cf0006c200aca1edfa5c81d/text_classification_rnn.ipynb) and [v2.4](https://colab.research.google.com/gist/tilakrayal/ccad84d997d457a573a834e205ec4357/2-4text_classification_rnn.ipynb).Please find the gist.

please try to execute code in virtual environment and limiting [GPU memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) using any of the methods listed in this guide and check if it helps.Thanks!

**Comment by dhavalsays** [comment]
I tried limiting GPU memory growth [check here, line # 3](https://github.com/codebasics/deep-learning-keras-tf-tutorial/blob/master/43_text_classification_rnn/rnn_text_classification.ipynb) but still getting error at line # 26
@tilakrayal I can see it works ok in Google colab but there is definitely a problem when someone runs this on local environment that has following,
tf 2.5
CUDA 11.2 (Windows 10)
Python 3.8.5
Also many others are facing same problem in https://github.com/tensorflow/tensorflow/issues/33721

**Comment by ymodak** [comment]
Have you tried reducing your batch size to a smaller value in addition to limiting gpu memory growth?
