### ISSUE TITLE
Request to add API documentation for using tf.flags

### ISSUE THREAD

**Issue by JacobIsrael123** [tensorflow/tensorflow#503]
I saw some tensorflow project contains hyperparameter configuration like:
```tf.flags.DEFINE_integer("embedding_dim", 128, "Dimensionality of character embedding (default: 128)")```

I think it is better to add corresponding document for using this feature.

**Comment by mrry** [comment]
Our policy so far has been only to document the features that we intend to support in TensorFlow long-term. Currently we use [`python-gflags`](https://github.com/gflags/python-gflags) as the implementation for `tf.flags`, but this is subject to change in future. In the meantime, the [documentation for that library](https://github.com/gflags/python-gflags/blob/master/gflags.py) is the best source of usage information.

**Comment by tobegit3hub** [comment]
I'm not sure if TensorFlow will use `python-gflags` in long-term or not, it would be better to add the link to refer to `python-glags`'s documentation. Anyway, it seems that project has little document, either :(

**Comment by sonu107** [comment]
Now Is there any documentation for hyperparameter configuration like?
