### ISSUE TITLE
How to create Tensorflow data ingestion pipeline for multiple related CSVs?

### ISSUE THREAD

**Issue by nitinmnsn** [tensorflow/tensorflow#50305]
Let us say we have some Relational data. 
Making a simple example for a retail store chain:
* Dataset 1 --> Store_id, Daily_sales
* Dataset 2 --> Customer_id, store_id, Time in, Time out

Let us say the task is to predict ```Daily_sales```.

I know how how to create data batches for one single CSV. I can use ```tf.data.experimental.make_csv_dataset``` and iterate over the dataset iterable that it returns to read the batches lazily. 

However, I want to read in the batches from ```Dataset 1``` and ```Dataset 2``` described above where the common id is ```store_id``` such that the batch reads the rows with same ```store_id```s from both the datasets. I want to do this because I will run two networks (RNN on ```Dataset 2``` and a single Fully connected layer on ```Dataset 1```) on both datasets and then merge them in the final fully connected layer.

Can you please guide me on how to approach this problem in scenarios where:
 * The datasets can fit into the memory
 * The datasets can not fit into the memory

Here is a concrete example of the behaviour I am looking  for:
```
import pandas as pd
Dataset_1 = pd.DataFrame({'id':['a','b','c','d'],'col1':[1,2,3,4]})
print(Dataset_1)
  id  col1
0  a     1
1  b     2
2  c     3
3  d     4
Dataset_2 = pd.DataFrame({'id':['a','a','b','c','c','c','d'],'col1':[10,11,12,13,14,15,16]})
print(Dataset_2)
	id	col1
0	a	10
1	a	11
2	b	12
3	c	13
4	c	14
5	c	15
6	d	16
#Let us say i want to create 2 batches. The following dataframes are how i want my batches to look like
batch_1 = (pd.DataFrame({'id':['a','b'],'col1':[1,2]}),pd.DataFrame({'id':['a','a','b'],'col1':[10,11,12]}))
print(batch_1[0])
	id	col1
0	a	1
1	b	2
print(batch_1[1])
  id  col1
0  a    10
1  a    11
2  b    12
batch_2 = (pd.DataFrame({'id':['c','d'],'col1':[3,4]}),pd.DataFrame({'id':['c','c','c','d'],'col1':[13,14,15,16]}))
print(batch_2[0])
id  col1
0  c     3
1  d     4

print(batch_2[1])
 id  col1
0  c    13
1  c    14
2  c    15
3  d    16
```

**Comment by AdityaKane2001** [comment]
@nitinmnsn 
Can you please tell if [this](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset?version=nightly) helps?

**Comment by nitinmnsn** [comment]
No, it does not insofar as I can see the behaviours CsvDataset API makes possible for me.
Here is a concrete example of the behaviour I am looking  for:
```
import pandas as pd
Dataset_1 = pd.DataFrame({'id':['a','b','c','d'],'col1':[1,2,3,4]})
print(Dataset_1)
  id  col1
0  a     1
1  b     2
2  c     3
3  d     4
Dataset_2 = pd.DataFrame({'id':['a','a','b','c','c','c','d'],'col1':[10,11,12,13,14,15,16]})
print(Dataset_2)
	id	col1
0	a	10
1	a	11
2	b	12
3	c	13
4	c	14
5	c	15
6	d	16
#Let us say i want to create 2 batches. The following dataframes are how i want my batches to look like
batch_1 = (pd.DataFrame({'id':['a','b'],'col1':[1,2]}),pd.DataFrame({'id':['a','a','b'],'col1':[10,11,12]}))
print(batch_1[0])
	id	col1
0	a	1
1	b	2
print(batch_1[1])
  id  col1
0  a    10
1  a    11
2  b    12
batch_2 = (pd.DataFrame({'id':['c','d'],'col1':[3,4]}),pd.DataFrame({'id':['c','c','c','d'],'col1':[13,14,15,16]}))
print(batch_2[0])
id  col1
0  c     3
1  d     4

print(batch_2[1])
 id  col1
0  c    13
1  c    14
2  c    15
3  d    16
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
