### ISSUE TITLE
layer order in functional API graph models

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#50306]
Do the layers in a graph model that is defined with the functional API have a specific order in the model. 
For example, when I have an Add layer that adds the outputs of two other layers, how is it decided which of the two layers comes first in the model?
I am wondering since in most cases the order seems to be the same as the order the layers are given, but not always.
This can be confusing, for example, when I tried to get the weights of the model, the order of them was not as expected in rare cases.
The following code illustrates the issue. I expected to find the weights of the Conv2D before the DepthwiseConv2D when I perform  model.get_weights().
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
in0Con6326 = tf.keras.layers.Input(shape=([2, 2, 2]))
in0Dep66009 = tf.keras.layers.Input(shape=([2, 2, 2]))
in0Con7723 = tf.keras.layers.Input(shape=([1, 1, 1]))
Con6326 = keras.layers.Conv2D(3, (2, 2),strides=(1, 1), padding='valid' )(in0Con6326)
Dep66009 = keras.layers.DepthwiseConv2D((2, 1),strides=(2, 2), padding='valid',)(in0Dep66009)
Con7723 = keras.layers.Concatenate(axis=3, )([Dep66009,in0Con7723])
Add80107 = keras.layers.Add()([Con6326,Con7723])
model = tf.keras.models.Model(inputs=[in0Con6326,in0Dep66009,in0Con7723], outputs=Add80107)
print(model.get_weights())
print(model.summary())
```

**Comment by tilakrayal** [comment]
@rschumi0 ,

We see that the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue and also please let us know the tensorflow version you are using?

Thanks!

**Comment by rschumi0** [comment]
@tilakrayal 
I was not sure which issue template would be the best, so I used the one for miscellaneous issues, which doesn't have a specific structure. 
I was running the example with the following System details:
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
    TensorFlow installed from (source or binary): binary
    TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
    Python version: 3.8.5

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the code in tf v2.4,v2.5 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/7ffc05b837104aacabc57fb67dd1f901/50306.ipynb).

**Comment by sachinprasadhs** [comment]
Since deep learning model is usually a  **directed acyclic graphs(DAG)** of layers and functional API is the way to do that way.
You can represent your layers in a graphical representation to understand the flow like below. 
![image](https://user-images.githubusercontent.com/73069040/122880346-8a400900-d357-11eb-8649-5448ffc63b8e.png)

If you want to get a layer weight then you can get the layer by it's name or you can iterate over the model layers and get the weights for the layer. 
Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7b9946de5965ad626aef9f8b17aaeb32/50306.ipynb) for more details. Thanks!

**Comment by rschumi0** [comment]
@sachinprasadhs Thank You for your answer. I am aware of this visualization method and also that it is possible to get the weights from an individual layer.
However, it would still be interesting to know if there is a specific order in which the DAG is processed?
In particular, in the example why is the DepthwiseConv2D before the Conv2D when the weights of the whole model are obtained?
Are deeper branches processed first or what could be the reason for this order?

**Comment by sachinprasadhs** [comment]
The reason is Tensorflow tries to optimize using shortest path finding in the layers arranged in a Topological order of DAG network. 
You can see the detailed explanation of DAG using mathematical concepts [here](https://en.wikipedia.org/wiki/Directed_acyclic_graph).

**Comment by rschumi0** [comment]
@sachinprasadhs I see, thanks.
Could you please refer me to the source code where the DAG is processed or ordered?

**Comment by ymodak** [comment]
You may want to to refer https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/utils/vis_utils.py#L67
