### ISSUE TITLE
how to auto format python code~

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#50304]
I change some code in tensorflow internal .
I use clang-format to be perfectly compatible with c++ code, but I can’t find a tool that is perfectly compatible with python code anyway.  @_@~ 
please help me, I would like to get an auto-format tools. 
I'm try to auto format by rcfile in .//tensorflow/tools/ci_build/, and I try yapf, autopep8, pylint.

I'm using tf-1.15, I find a same problem on tf 2.3

**Comment by zhaozheng09** [comment]
sh tensorflow/tools/ci_build/ci_sanity.sh     logs of error or warning, like:
tensorflow/python/ops/standard_ops.py:45: [W0622(redefined-builtin), ] Redefining built-in 'slice'
tensorflow/python/ops/standard_ops.py:75: [W0622(redefined-builtin), ] Redefining built-in 'abs'
tensorflow/python/ops/standard_ops.py:75: [W0622(redefined-builtin), ] Redefining built-in 'pow'
tensorflow/python/ops/standard_ops.py:75: [W0622(redefined-builtin), ] Redefining built-in 'complex'
tensorflow/python/ops/standard_ops.py:75: [W0622(redefined-builtin), ] Redefining built-in 'round'
tensorflow/python/ops/standard_ops.py:75: [W0622(redefined-builtin), ] Redefining built-in 'range'
tensorflow/python/ops/standard_ops.py:109: [W0622(redefined-builtin), ] Redefining built-in 'zip'

tensorflow/python/ops/linalg/linear_operator.py:334: [E1102(not-callable), LinearOperator.shape_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:369: [E1102(not-callable), LinearOperator.batch_shape_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:396: [E1102(not-callable), LinearOperator.tensor_rank] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:412: [E1102(not-callable), LinearOperator.tensor_rank_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:455: [E1102(not-callable), LinearOperator.domain_dimension_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:499: [E1102(not-callable), LinearOperator.range_dimension_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:558: [E1102(not-callable), LinearOperator.assert_non_singular] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:591: [E1102(not-callable), LinearOperator.assert_positive_definite] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:617: [E1102(not-callable), LinearOperator.assert_self_adjoint] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:671: [E1102(not-callable), LinearOperator.matmul] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:674: [E1102(not-callable), LinearOperator.matmul] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:721: [E1102(not-callable), LinearOperator.matvec] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:753: [E1102(not-callable), LinearOperator.determinant] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:782: [E1102(not-callable), LinearOperator.log_abs_determinant] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:864: [E1102(not-callable), LinearOperator.solve] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:867: [E1102(not-callable), LinearOperator.solve] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:924: [E1102(not-callable), LinearOperator.solvevec] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:947: [E1102(not-callable), LinearOperator.adjoint] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:975: [E1102(not-callable), LinearOperator.inverse] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1000: [E1102(not-callable), LinearOperator.cholesky] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1021: [E1102(not-callable), LinearOperator.to_dense] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1053: [E1102(not-callable), LinearOperator.diag_part] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1070: [E1102(not-callable), LinearOperator.trace] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1087: [E1102(not-callable), LinearOperator.add_to_tensor] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1111: [E1102(not-callable), LinearOperator.eigvals] self._name_scope is not callable
tensorflow/python/ops/linalg/linear_operator.py:1136: [E1102(not-callable), LinearOperator.cond] self._name_scope is not callable

**Comment by bhack** [comment]
I am trying to add linting pre-commit in our developer container at https://github.com/tensorflow/tensorflow/pull/48371

If you use master you can already run the plain `pylint` command.

I think that you can also use `yapf` for autoformatting if you set the style as python Google style.

**Comment by zhaozheng09** [comment]
> I am trying to add linting pre-commit in our developer container at #48371
> 
> If you use master you can already run the plain `pylint` command.
> 
> I think that you can also use `yapf` for autoformatting if you set the style as python Google style.

thx. I will try .

**Comment by sogartar** [comment]
> I am trying to add linting pre-commit in our developer container at #48371
> 
> If you use master you can already run the plain `pylint` command.
> 
> I think that you can also use `yapf` for autoformatting if you set the style as python Google style.

I want to resurrect this issue because
```
yapf --style google ...
```
is not the correct solution. For example the default indentation is 4 spaces where Tensorflow uses 2 spaces.

**Comment by bhack** [comment]
Now in python we have only 4 over 9 valid checks in the pylint conf see more at: https://github.com/tensorflow/tensorflow/issues/55442

So to know how to auto-format correctly the python code for TF standards we really need to understand what we want to enforce in pylint or if we need to integrate it with other tools (e.g. like in Keras-*).

/cc @learning-to-play
