### ISSUE TITLE
Unable to convert .pb file into .tflite

### ISSUE THREAD

**Issue by VirVisha** [tensorflow/tensorflow#50301]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installation (pip package or built from source):
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/gist/ymodak/e96a4270b953201d5362c61c1e8b78aa/tensorflow-datasets.ipynb?authuser=1): Demonstrate how to build your TF model.
2)  Reference [TensorFlow Lite Model Colab](https://colab.research.google.com/gist/ymodak/0dfeb28255e189c5c48d9093f296e9a8/tensorflow-lite-debugger-colab.ipynb): Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).

```
(You can paste links or attach files by dragging & dropping them below)
- Provide links to your updated versions of the above two colab notebooks.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
(You can paste links or attach files by dragging & dropping them below)
- Include code to invoke the TFLite Converter Python API and the errors.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by VirVisha** [comment]
I am doing an Image classification problem on Google Colab, The link for the code on Colab is https://colab.research.google.com/drive/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU

I am able to successfully retrain an efficeintdet-do model with custom mages. 
Within Colab i am able to do reasonable corect image classification as well, but when i convert the model (.pb file) into tflite, 
Upon invoking Interpreter i upon printing print(input_details) the result is 

[{'name': 'serving_default_input_tensor:0', 'index': 0, 'shape': array([1, 1, 1, 3], dtype=int32), 'shape_signature': array([ 1, -1, -1,  3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

The shape : array [1, 1, 1, 3] should have been shape[1, 250, 250, 3]. I am unable to understand how this conversion automatically happened, because during tflite creation i have specifically called concrete_func.inputs[0].set_shape([1, 250, 250, 3])

**Comment by srjoglekar246** [comment]
@VirVisha I am unable to access your Colab. Can you provide a snippet of how you are converting your model using the TFLite converter?

**Comment by VirVisha** [comment]
I have made the access to the notebook public the link is https://drive.google.com/file/d/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU/view?usp=sharing

**Comment by srjoglekar246** [comment]
Your code seems to be working on object detection with an SSD model. The steps to convert that are different, and we need to use a TFLite-specific script as opposed to exporter_main_v2. See [this Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb), specifically "Export & run with TensorFlow Lite" section & below. You might need to adapt it a bit for your use-case.

**Comment by VirVisha** [comment]
@srjoglekar246  As suggested in the colab notebook link you shared , I changed the code section of !python object_detection/exporter_main_v2.py \
    --trained_checkpoint_dir {last_model_path} \
    --output_directory {output_directory} \
    --pipeline_config_path {pipeline_file}!python object_detection/exporter_main_v2.py \
    --trained_checkpoint_dir {last_model_path} \
    --output_directory {output_directory} \
    --pipeline_config_path {pipeline_file}

to 

!python object_detection/export_tflite_graph_tf2.py \
  --pipeline_config_path {pipeline_file} \
  --trained_checkpoint_dir {last_model_path} \
  --output_directory {output_directory}

Subsequent to this there are error messages generated 

2021-06-17 05:06:22.085451: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-17 05:06:24.864052: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-06-17 05:06:24.903511: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.904230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-17 05:06:24.904282: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-17 05:06:24.908384: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-06-17 05:06:24.908475: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-06-17 05:06:24.910463: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-06-17 05:06:24.911133: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-06-17 05:06:24.922260: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.10
2021-06-17 05:06:24.923550: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-06-17 05:06:24.924141: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-06-17 05:06:24.924331: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.925346: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.926879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-17 05:06:24.928056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.929028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-17 05:06:24.929158: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.930647: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:24.931713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-06-17 05:06:24.931807: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-06-17 05:06:25.620583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-17 05:06:25.620658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-06-17 05:06:25.620679: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-06-17 05:06:25.620885: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:25.621582: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:25.622246: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-17 05:06:25.622862: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2021-06-17 05:06:25.622913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13837 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
I0617 05:06:25.629735 140131339650944 ssd_efficientnet_bifpn_feature_extractor.py:143] EfficientDet EfficientNet backbone version: efficientnet-b0
I0617 05:06:25.629959 140131339650944 ssd_efficientnet_bifpn_feature_extractor.py:144] EfficientDet BiFPN num filters: 64
I0617 05:06:25.630064 140131339650944 ssd_efficientnet_bifpn_feature_extractor.py:146] EfficientDet BiFPN num iterations: 3
I0617 05:06:25.634973 140131339650944 efficientnet_model.py:147] round_filter input=32 output=32
I0617 05:06:25.658451 140131339650944 efficientnet_model.py:147] round_filter input=32 output=32
I0617 05:06:25.658674 140131339650944 efficientnet_model.py:147] round_filter input=16 output=16
I0617 05:06:25.722052 140131339650944 efficientnet_model.py:147] round_filter input=16 output=16
I0617 05:06:25.722274 140131339650944 efficientnet_model.py:147] round_filter input=24 output=24
I0617 05:06:25.884342 140131339650944 efficientnet_model.py:147] round_filter input=24 output=24
I0617 05:06:25.884578 140131339650944 efficientnet_model.py:147] round_filter input=40 output=40
I0617 05:06:26.054194 140131339650944 efficientnet_model.py:147] round_filter input=40 output=40
I0617 05:06:26.054428 140131339650944 efficientnet_model.py:147] round_filter input=80 output=80
I0617 05:06:26.316348 140131339650944 efficientnet_model.py:147] round_filter input=80 output=80
I0617 05:06:26.316609 140131339650944 efficientnet_model.py:147] round_filter input=112 output=112
I0617 05:06:26.575680 140131339650944 efficientnet_model.py:147] round_filter input=112 output=112
I0617 05:06:26.575894 140131339650944 efficientnet_model.py:147] round_filter input=192 output=192
I0617 05:06:26.927866 140131339650944 efficientnet_model.py:147] round_filter input=192 output=192
I0617 05:06:26.928075 140131339650944 efficientnet_model.py:147] round_filter input=320 output=320
I0617 05:06:27.010624 140131339650944 efficientnet_model.py:147] round_filter input=1280 output=1280
I0617 05:06:27.047516 140131339650944 efficientnet_model.py:458] Building model efficientnet with params ModelConfig(width_coefficient=1.0, depth_coefficient=1.0, resolution=224, dropout_rate=0.2, blocks=(BlockConfig(input_filters=32, output_filters=16, kernel_size=3, num_repeat=1, expand_ratio=1, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=16, output_filters=24, kernel_size=3, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=24, output_filters=40, kernel_size=5, num_repeat=2, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=40, output_filters=80, kernel_size=3, num_repeat=3, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=80, output_filters=112, kernel_size=5, num_repeat=3, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=112, output_filters=192, kernel_size=5, num_repeat=4, expand_ratio=6, strides=(2, 2), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise'), BlockConfig(input_filters=192, output_filters=320, kernel_size=3, num_repeat=1, expand_ratio=6, strides=(1, 1), se_ratio=0.25, id_skip=True, fused_conv=False, conv_type='depthwise')), stem_base_filters=32, top_base_filters=1280, activation='simple_swish', batch_norm='default', bn_momentum=0.99, bn_epsilon=0.001, weight_decay=5e-06, drop_connect_rate=0.2, depth_divisor=8, min_depth=None, use_se=True, input_channels=3, num_classes=1000, model_name='efficientnet', rescale_input=False, data_format='channels_last', dtype='float32')
Traceback (most recent call last):
  File "object_detection/export_tflite_graph_tf2.py", line 161, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "object_detection/export_tflite_graph_tf2.py", line 157, in main
    FLAGS.centernet_include_keypoints, FLAGS.keypoint_label_map_path)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/export_tflite_graph_lib_tf2.py", line 348, in export_tflite_model
    max_detections, use_regular_nms)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/export_tflite_graph_lib_tf2.py", line 71, in __init__
    self._process_config(pipeline_config)
  File "/usr/local/lib/python3.7/dist-packages/object_detection/export_tflite_graph_lib_tf2.py", line 104, in _process_config
    image_resizer_config.WhichOneof('image_resizer_oneof')))
ValueError: Only fixed_shape_resizeris supported with tflite. Found keep_aspect_ratio_resizer

**Comment by VirVisha** [comment]
Subsequent to this i checked the same application with ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz and followed steps as mentioned in the "Export & run with TensorFlow Lite" .

Inference is happening reasonably correct and the model.tflite file is also getting created with the print(input_details) showing me

[{'name': 'input', 'index': 12, 'shape': array([  1, 320, 320,   3], dtype=int32), 'shape_signature': array([  1, 320, 320,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

Now when i export the tflite file with relevant labels.txt to Android application i am getting an error 

Caused by: java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (input) with 1228800 bytes from a Java Buffer with 150528 bytes.

**Comment by VirVisha** [comment]
Upon closer investigation of on revisiting colab notebook, the link is https://colab.research.google.com/drive/1Hs6-UVhtHZCpKz-6JcoS8xFTG24jBA6c?usp=sharing 
I found that saved_model.pb is of around 10MB but the model.tflite which was created is of only 2KB..

I followed

Step 1
 !python object_detection/export_tflite_graph_tf2.py \
  --pipeline_config_path {pipeline_file} \
  --trained_checkpoint_dir {last_model_path} \
  --output_directory {output_directory}

and subsequently Step 2

!tflite_convert --saved_model_dir='/content/gdrive/MyDrive/TFLite/fine_tuned_model/saved_model' --output_file='/content/gdrive/MyDrive/TFLite/model.tflite'

I even dropped the model.tflite file on Netron  found this as  description

![image](https://user-images.githubusercontent.com/85932233/122429088-206adc80-cfb0-11eb-8543-271598838ee0.png)

Unable to decipher if there was anything else needed to be done. The above colab notebook was trained for 2000 steps and only Bill Clinton images were trained. That way the inference is working fine in colab

**Comment by srjoglekar246** [comment]
Aah the exporting script doesn't support EfficientDets. From the detection zoo, we support [SSD MobileNet](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) & [CenterNet](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/centernet_on_device.ipynb). If you want EfficientDet necessarily, you can try [Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection).

**Comment by VirVisha** [comment]
For the above colab notebook i am using 
MODELS_CONFIG = {
    'ssd': {
        'model_name': 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8',
        'base_pipeline_file': 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.config',
        'pretrained_checkpoint': 'ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz',
        'batch_size': 8
    }
}

**Comment by srjoglekar246** [comment]
Aah. Your TFLite converter needs to be running TF 2.4 or later. We added these features after TF 2.3.

**Comment by VirVisha** [comment]
I am using Tensorflow version 2.5 for these colab notebooks

**Comment by VirVisha** [comment]
@srjoglekar246 If i share tflite file and labels.txt can you check that the model is correct. Though when i placed the tflite in netron app, it seems to me it is correct.

print(input_details) 
[{'name': 'serving_default_input:0', 'index': 0, 'shape': array([  1, 300, 300,   3], dtype=int32), 'shape_signature': array([  1, 300, 300,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

After this i used interpreter.set_tensor(input_index, input_tensor)

Followed by call interpreter.invoke()

After words I checked the output_details i get the following output

print(output_details)
[{'name': 'StatefulPartitionedCall:3', 'index': 247, 'shape': array([ 1, 10,  4], dtype=int32), 'shape_signature': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}},
 {'name': 'StatefulPartitionedCall:2', 'index': 248, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, 
{'name': 'StatefulPartitionedCall:1', 'index': 249, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, 
{'name': 'StatefulPartitionedCall:0', 'index': 250, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

Supposedly the output should be an image as seen during the inference in colab, how can I interpret the same from the above details

**Comment by VirVisha** [comment]
[Uploading tflitemodel.zip.zip…]()

**Comment by srjoglekar246** [comment]
The model isn't correct. For some reason, your model just contains zeros as the outputs.

How are you converting the exported SavedModel to TFLite? Can you share a snippet?

**Comment by VirVisha** [comment]
I am using following code snippets 

Step 1
!python /content/gdrive/MyDrive/TFLite_Check/models/research/object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path {pipeline_file} \
    --trained_checkpoint_dir {last_model_path} \
    --output_directory {outd}

Step 2
converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/TFLite_Check/freezetflite/saved_model/')

Step 3

converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True

Step 4 
tflite_model = converter.convert()

Step 5 
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

Step 6
with tf.io.gfile.GFile('/content/gdrive/MyDrive/TFLite_Check/test/model.tflite', 'rb') as f:
    model_content = f.read()

interpreter = tf.lite.Interpreter(model_content=model_content)
input_details = interpreter.get_input_details()

The Link to the complete notebook is https://colab.research.google.com/drive/1kisxBtImUS7sT2aQlsEKfcXaEnsKumGw?usp=sharing

When i print input details 
print(input_details) 
The ouptut is [{'name': 'serving_default_input:0', 'index': 0, 'shape': array([  1, 300, 300,   3], dtype=int32), 'shape_signature': array([  1, 300, 300,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

After passing the image as an input when check the output 
output_details = interpreter.get_output_details()
print(output_details) i get  following output 

[{'name': 'StatefulPartitionedCall:3', 'index': 239, 'shape': array([ 1, 10,  4], dtype=int32), 'shape_signature': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:2', 'index': 240, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:1', 'index': 241, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:0', 'index': 242, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

**Comment by srjoglekar246** [comment]
Your code seems fine to me. See [this Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb) for how to run the model in Python (specifically, the `Test .tflite model` section)

**Comment by VirVisha** [comment]
Did that, here is the notebook of your code https://colab.research.google.com/drive/1B4AEQJasbIRNmk-tOr0rt_VFvM4-w-qy?usp=sharing

At the end in the last cell there was an issue i came across  

label_id_offset = 1
for i in range(len(test_images_np)):
  input_tensor = tf.convert_to_tensor(test_images_np[i], dtype=tf.float32)
  boxes, classes, scores = detect(interpreter, input_tensor)

  plot_detections(
      test_images_np[i][0],
      boxes[0],
      classes[0].astype(np.uint32) + label_id_offset,
      scores[0],
      category_index, figsize=(15, 20), image_name="gif_frame_" + ('%02d' % i) + ".jpg")

IndexError                                Traceback (most recent call last)
<ipython-input-58-eb5ebe4f5c3c> in <module>()
     12   plot_detections(
     13       test_images_np[i][0],
---> 14       boxes[0],
     15       classes[0].astype(np.uint32) + label_id_offset,
     16       scores[0],

IndexError: invalid index to scalar variable.

**Comment by VirVisha** [comment]
@srjoglekar246 I retrieved the scores parameter in the notebook https://drive.google.com/file/d/1HEpM5LtJ6Hx4D9oEpAXlv1C7mwpEvqbw/view?usp=sharing in the plot detections functions in the last cell of the notebook.

The print(scores[0][0]) output gives me 0.9150113 which when i corroborated against the output figure is same, So i presume that this is giving me the accuracy of the input image match

Now i have to port this to Android.
Before this i just want to summarize how i generated the tflite file.

Step 1
!python /content/gdrive/MyDrive/TFLite4/models/research/object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path {pipeline_file} \
    --trained_checkpoint_dir {last_model_path} \
    --output_directory {outd}

This saves and create a saved_model directory containing assets, saved_model.pb in a folder freeezetflite in the above notebook

Step 2 
In order to generate the tflite file I implemented the following commands

converter = tf.lite.TFLiteConverter.from_saved_model('/content/gdrive/MyDrive/TFLite4/freezetflite/saved_model/')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True

tflite_model = converter.convert()

import pathlib
tflite_model_path = pathlib.Path('model.tflite')

with tf.io.gfile.GFile(tflite_model_path, 'wb') as f:
  f.write(tflite_model)

This generates model.tflite file in the test directory

Step 3
I created interpreter and set the input tensor followed by invoking it, the ouptut i capture in boxes, classes and scores

with tf.io.gfile.GFile('/content/gdrive/MyDrive/TFLite4/test/model.tflite', 'rb') as f:
    model_content = f.read()
interpreter = tf.lite.Interpreter(model_content=model_content)

interpreter.allocate_tensors()

boxes = interpreter.get_tensor(output_details[0]['index'])
classes = interpreter.get_tensor(output_details[1]['index'])
scores = interpreter.get_tensor(output_details[2]['index'])

This when passed into the plot_detections function gives me the output of the input image 
![mobile_capture](https://user-images.githubusercontent.com/85932233/123200880-3a844d80-d4cf-11eb-9405-7883f6cae84f.jpg)

I trained the model with images of Bill Clinton and got the above input

I hope that this all is correct way of doing.

Now I want to port this to Android, as pointed out by you https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb do i have to adapt the above tflite file using the mechanism pointed out in the link https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection

**Comment by srjoglekar246** [comment]
Awesome work! And yes, the link you have seems right. Specifically, see [this section](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android#switch-between-inference-solutions-task-library-vs-tflite-interpreter) for how to customize the app code based on your use case. For example, if you want to go the lib_interpreter route mentioned there, then you will have to modify the code [here](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L167) based on your model.

**Comment by srjoglekar246** [comment]
I will close this bug since the title issue is resolved. Feel free to followup with comments about the Android app if you have any. But you seem to have gotten the inference logic figured out in Python.

**Comment by VirVisha** [comment]
@srjoglekar246 Thanks a ton for your guidance and surely now I am porting this to Android
