### ISSUE TITLE
why the environment variable CUDA_VISIBLE_DEVICES no use

### ISSUE THREAD

**Issue by nkjulia** [tensorflow/tensorflow#50300]
hi, when i run tensorflow  project, i set those two  environment variables below to make the tensorflow use the GPUs as i expected, but the settings did not effect as i expected.

export CUDA_DEVICE_ORDER="PCI_BUS_ID"
export CUDA_VISIBLE_DEVICES="5,6"

as  i set the variable CUDA_VISIBLE_DEVICES as above, when i run tensorflow project , it only use the GPU:0 and GPU:1, it seems that it ignore what i set , just start with GPU:0.

can anyone give some advices?
thanks a lot.

PS my tensorflow version is 2.4.1

**Comment by pandrey-fr** [comment]
Tensorflow always labels devices starting from zero, but it _does_ use `CUDA_VISIBLE_DEVICES`. So, what TensorFlow labels as GPUs 0 and 1 should in fact be your system's GPUs 5 and 6. You can check that by monitoring GPU activity using tools such as `nvidia-smi` or `nvtop` from the command line while a TensorFlow job making use of the GPUs is running.

**Comment by tilakrayal** [comment]
@nkjulia ,

Please take a look at this link which provide more information on CUDA_VISIBLE_DEVICES. [Link1](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars),[Link2](https://www.tensorflow.org/guide/gpu).Thanks!

**Comment by nkjulia** [comment]
> @nkjulia ,
> 
> Please take a look at this link which provide more information on CUDA_VISIBLE_DEVICES. [Link1](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars),[Link2](https://www.tensorflow.org/guide/gpu).Thanks!

ok~ thanks

**Comment by nkjulia** [comment]
> Tensorflow always labels devices starting from zero, but it _does_ use `CUDA_VISIBLE_DEVICES`. So, what TensorFlow labels as GPUs 0 and 1 should in fact be your system's GPUs 5 and 6. You can check that by monitoring GPU activity using tools such as `nvidia-smi` or `nvtop` from the command line while a TensorFlow job making use of the GPUs is running.



> Tensorflow always labels devices starting from zero, but it _does_ use `CUDA_VISIBLE_DEVICES`. So, what TensorFlow labels as GPUs 0 and 1 should in fact be your system's GPUs 5 and 6. You can check that by monitoring GPU activity using tools such as `nvidia-smi` or `nvtop` from the command line while a TensorFlow job making use of the GPUs is running.

i checked the usage of GPUS when running a task with specified setting, no questions now, thank u.
