### ISSUE TITLE
Interpreter fails when trying to load CenterNet(Java API)

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#50319]
I have created an android example app and I am trying to run CenterNet(320x320, 512x512, 640x640).

When I run this model(trained): 
[centernet_320x320.zip](https://github.com/tensorflow/tensorflow/files/6668027/centernet_320x320.zip) in CPU works fine, but when I try to run with GPU Delegate I get the following error:
`java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`

When I run this two models(pre trained):
[centernet_model_test_640x640.zip](https://github.com/tensorflow/tensorflow/files/6668051/centernet_model_test_640x640.zip)
[centernet_model_test_512x512.zip](https://github.com/tensorflow/tensorflow/files/6668049/centernet_model_test_512x512.zip)
They work in CPU and GPU.

Now, when I try to run the same models in a Qualcomm device for better performance, for the first model I get the same behavior and for the two pre trained models when I run them in CPU they work(the output is good), but when I run the same model in QC **GPU the output of the models is not correct**. (its just weird when the same model in CPU gives good predictions and in GPU it gives really bad predictions)

```
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
```
I have tried with 2.3.0 , 2.4.0 and 2.5.0 and I get the same behavior.

**Comment by impjdi** [comment]
in the centernet 320x320, you have bunch of subgraphs.  try to remove those.

i'm not really sure the centernet models run on the GPU as I see bunch of incompatible ops.  do you have any logs?

**Comment by ArtanBerisha1** [comment]
Hi @impjdi,
The two pre trained models (512x512, and 640x640) in the first device (RK chip) worked on GPU, I am assuming this because the interpreter time dropped almost by 50% (from 1.2 seconds/frame to 0.6 seconds/frame) and the output was correct.
But when I change the device(Qualcomm) interpreter time drops but the output is not correct. 
The only change here is the GPU of the device :/ 
I can't find any useful logs because there isn't any warning or crashes of interpreter.

**Comment by mohantym** [comment]
Hi @ArtanBerisha1! Have you checked these [thread ](https://github.com/tensorflow/tensorflow/issues/38036#issuecomment-943959589)yet ?
