### ISSUE TITLE
`tf.keras.applications.EfficientNetB0` raises `CustomMaskWarning` when trained or saved

### ISSUE THREAD

**Issue by CaptainDario** [tensorflow/tensorflow#50324]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- CUDA version: 
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_22:08:44_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```
- cuDNN version: `cudnn-11.2-windows-x64-v8.1.1.33`
- GPU model and memory: RTX 2070 Super

**Describe the current behavior**
When saving an `EfficientNetB0` model to file (".pb"-file) it shows a warning:
```
E:\projects\DaKanjiRecognizerML\.venv\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '
```
This also happens when converting to tf lite.

**Describe the expected behavior**
Saving should work without a problem.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

eff_net = tf.keras.applications.EfficientNetB0(
    include_top=True,
    weights=None,
    input_shape=(64, 64, 1),
    classes=6543,
    pooling="max",
    classifier_activation="softmax"
)

eff_net.save(PATH_TO_SAVE_TO)
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issuein TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/94de5063ad4d015ef7d21223d93fdb58/untitled.ipynb). Thanks!

**Comment by ymodak** [comment]
The warning was added with TF 2.5 in commit [076b5be](https://github.com/tensorflow/tensorflow/commit/076b5be77d3933deb726de1fc9d954d284985b1e#diff-08518b3b0b22c5c9dc137c911fa716fe820878cb9bbf95806ffca0e0296ec7fa)
The model saves without warnings in TF 2.4

**Comment by CaptainDario** [comment]
Still curious about this.

**Comment by seermer** [comment]
same for MobileNetV3

**Comment by ghylander** [comment]
So why does the warning come up? Is it a bug or intentional?

**Comment by jvishnuvardhan** [comment]
@CaptainDario Agree with you that it was an issue with old versions.

This was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/32df0d4b8d83ac13e30e575ac8757835/untitled1128.ipynb) is a gist for reference. If you want stable version, then it will be available in the upcoming TF2.8 in near future. Thanks!

Please verify once and close the issue if the issue got resolved for you. Thanks!
