### ISSUE TITLE
AttributeError: 'module' object has no attribute 'batch_fft'

### ISSUE THREAD

**Issue by vanzytay** [tensorflow/tensorflow#5032]
Hi, 

I just reinstalled rebuilt tensorflow from source to use CUDA v8 (I changed GPU to gtx1070)

I was running tf.batch_fft perfectly fine previously. But now it returns 

AttributeError: 'module' object has no attribute 'batch_fft'

Can someone point me to where this batch_fft is implemented now? I am using version 0.11.0rc0 now. 

I can't remember if I was using 0.10 previously or not. Did the API change?

Thanks in advance! :)

**Comment by asimshankar** [comment]
Use `tf.fft` now

(For the curios, see commit 9287c2f08c8bf407074071a8a5ff57a4a54db05e)

Hope that helps!
