### ISSUE TITLE
Can i implement a model that learns weights that fit the quantization step size?

### ISSUE THREAD

**Issue by CloudZet** [tensorflow/tensorflow#50320]
I want to make model what can train quantization weights. Is there such a way?

I already know how to take out the weights of the trained model,
quantize them in an external tool, and then load them again.

Thanks for reading this question and have a nice day

**Comment by gowthamkpr** [comment]
@CloudZet Not sure if this is possible but I would recommend using quantization aware training. Here is an [example](https://www.tensorflow.org/model_optimization/guide/quantization/training_example). Thanks!
