### ISSUE TITLE
Error when loading tflite model created from saved_model

### ISSUE THREAD

**Issue by kylegerber94** [tensorflow/tensorflow#50335]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 19041.1052
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

- I converted a saved model using `tf.lite.TFLiteConverter.from_saved_model()`

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model cannot be loaded by `tflite_runtime.interpreter.Interpreter`
- I get the following error: _ValueError: Op builtin_code out of range: 131. Are you using old TFLite binary with newer model?Registration failed._
- I have confirmed that both `tensorflow` and `tflite_runtime` and on version 2.5.0

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@kylegerber94 Can you please share a simple standalone code to reproduce the error? Thanks!

**Comment by thaink** [comment]
Could you double check the TensorFlow version you are using for running the model?
The builtin op number 131 definitely exists in v2.5.0 https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/lite/builtin_ops.h#L161.
