### ISSUE TITLE
tf.where function is less friendly in TensorFlow2.x than it in TenosrFlow1.x

### ISSUE THREAD

**Issue by yjiangling** [tensorflow/tensorflow#50336]
In TensorFlow1.x（including TensorFlow 1.15）, the function of tf.where function can broadcast automaticly just like this:

`x=tf.constant([[0.1, 0.1, 0.1], [0.1, 0.1, 0.1]], dtype=tf.float32)
y=tf.constant([[0.2, 0.2, 0.2], [0.2, 0.2, 0.2]], dtype=tf.float32)
m=tf.constant([0.4, 0.6],dtype=tf.float32)
z=tf.where(m>0.5, x, y)
`
It can get the right result z=[[0.2, 0.2, 0.2], [0.1, 0.1, 0.1]]

However, when it run in TensorFlow2.x， it will give the error like this:
**InvalidArgumentError: condition [2], then [2,3], and else [2,3] must be broadcastable [Op:SelectV2]**

So, why not continue the automatic broadcast feature in TensorFlow1.x？

**Comment by jvishnuvardhan** [comment]
@yjiangling I update your code to change the size of condition as shown below. With that change, everything is working as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2673eb7b71bd63f4d0d3fb8e1d5f662d/untitled999.ipynb). Thanks!

```
x=tf.constant([[0.1, 0.1, 0.1], [0.1, 0.1, 0.1]], dtype=tf.float32) # shape [2 3]
y=tf.constant([[0.2, 0.2, 0.2], [0.2, 0.2, 0.2]], dtype=tf.float32) # shape [2 3]
# m=tf.constant([0.4, 0.6],dtype=tf.float32) # this fails as shape is [2]
m=tf.constant([[0.4], [0.6]],dtype=tf.float32) # this works as expected (shape[2 1])

z=tf.where(m>0.5, x, y)
print(z) #Output is `tf.Tensor([[0.2 0.2 0.2] [0.1 0.1 0.1]], shape=(2, 3), dtype=float32)`
```

**Comment by yjiangling** [comment]
> @yjiangling I update your code to change the size of condition as shown below. With that change, everything is working as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2673eb7b71bd63f4d0d3fb8e1d5f662d/untitled999.ipynb). Thanks!
> 
> ```
> x=tf.constant([[0.1, 0.1, 0.1], [0.1, 0.1, 0.1]], dtype=tf.float32) # shape [2 3]
> y=tf.constant([[0.2, 0.2, 0.2], [0.2, 0.2, 0.2]], dtype=tf.float32) # shape [2 3]
> # m=tf.constant([0.4, 0.6],dtype=tf.float32) # this fails as shape is [2]
> m=tf.constant([[0.4], [0.6]],dtype=tf.float32) # this works as expected (shape[2 1])
> 
> z=tf.where(m>0.5, x, y)
> print(z) #Output is `tf.Tensor([[0.2 0.2 0.2] [0.1 0.1 0.1]], shape=(2, 3), dtype=float32)`
> ```

Oh, I see, thanks a lot for the help.
