### ISSUE TITLE
Cannot import module for version mismatch?

### ISSUE THREAD

**Issue by ML-BOSS** [tensorflow/tensorflow#50332]
Always we are facing importing module problems. As for example, I am using TF 1.14 and keras 2.2.5. but it can not import this:
ImportError: cannot import name 'imagenet_utils' from 'tensorflow.keras.applications' (unknown location)
I don't know where it is, due to unknown location. Also I don't know the imagenet_utils is available in TF 1.14 or not!

Is there any documentation about it, especially for all version. Are there any differences or added method differences between TF 1.14 and TF 2.5? 
Would you provide any documentation about these issues?

**Comment by tilakrayal** [comment]
@ML-BOSS ,

Can you please, fill [issue template](https://github.com/tensorflow/models/issues/new/choose).Also please take a look at this links for more information on Imagenet_utils.It helps.
[Link1](https://www.tensorflow.org/api_docs/python/tf/keras/applications/imagenet_utils),[Link2](https://stackoverflow.com/questions/63527148/cannot-import-name-imagenet-utils-from-tensorflow-keras-applications),[Link3](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/imagenet_utils.py).

Thanks!
