### ISSUE TITLE
Error build hello_world targeting RISCV 

### ISSUE THREAD

**Issue by klchiu** [tensorflow/tensorflow#50334]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): N/A
- TensorFlow version: v2.4.2
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): GCC 7.5.0, riscv64-unknown-elf-g++ (GCC) 9.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
We are failed to build a runnable binary for RISCV as our targeting architecture following the steps described in this page.
https://www.tensorflow.org/lite/microcontrollers/library

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. clone the repository
2. make -f tensorflow/lite/micro/tools/make/Makefile hello_world_bin (this is okay)
3. make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mcu_riscv hello_world_bin (this builds, but it uses g++ instead of the riscv64-unknown-elf-g++)

4. So we copy mcu_riscv_makefile.inc to riscv32_mcu_makefile.inc
5. make -f tensorflow/lite/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world_bin (then there are errors, asm related, the log is attached below)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

cc1: warning: command line option '-fno-threadsafe-statics' is valid for C++/ObjC++ but not for C                                                               
cc1: warning: command line option '-fno-use-cxa-atexit' is valid for C++/ObjC++ but not for C                                                                           
In file included from tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:6:                                                  
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c: In function 'measure_cpu_freq':
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:170:3: error: 'asm' undeclared (first use in this function)                                
  170 |   asm volatile ("csrr %0, " #reg : "=r"(__tmp)); \                                                                                                      
      |   ^~~                                                                                                                                                          
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:152:32: note: in expansion of macro 'read_csr'               
  152 |   unsigned long start_mcycle = read_csr(mcycle);                                                                                                        
      |                                ^~~~~~~~                                                                                                                         
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:170:3: note: each undeclared identifier is reported only once for each function it appears in
  170 |   asm volatile ("csrr %0, " #reg : "=r"(__tmp)); \                                                                                    
      |   ^~~                                                                                                                                                                          
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:152:32: note: in expansion of macro 'read_csr'                                      
  152 |   unsigned long start_mcycle = read_csr(mcycle);                                                                                                                                
      |                                ^~~~~~~~                                                                                                                                     
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:170:7: error: expected ';' before 'volatile'                                                              
  170 |   asm volatile ("csrr %0, " #reg : "=r"(__tmp)); \                                                                                                                               
      |       ^~~~~~~~                                                                                                                                                                  
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:152:32: note: in expansion of macro 'read_csr'                                           
  152 |   unsigned long start_mcycle = read_csr(mcycle);                                                                                                                              
      |                                ^~~~~~~~                                                                                                                                          
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:170:7: error: expected ';' before 'volatile'                                                            
  170 |   asm volatile ("csrr %0, " #reg : "=r"(__tmp)); \                                                                                    
      |       ^~~~~~~~                                                         
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:158:32: note: in expansion of macro 'read_csr'
  158 |   unsigned long delta_mcycle = read_csr(mcycle) - start_mcycle;                                                    
      |                                ^~~~~~~~                            
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c: In function '_init':
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:225:25: warning: format '%d' expects argument of type 'int', but argument 2 has type 'long unsigned int' [-W
format=]                                                                       
  225 |   printf("core freq at %d Hz\n", get_cpu_freq());
      |                        ~^        ~~~~~~~~~~~~~~                                                                                                                                                     
      |                         |        |    
      |                         int      long unsigned int                                                                                                                          
      |                        %ld 
In file included from tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:6:
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:175:5: error: 'asm' undeclared (first use in this function)
  175 |     asm volatile ("csrw " #reg ", %0" :: "i"(val)); \        
      |     ^~~                                                          
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:227:3: note: in expansion of macro 'write_csr'
  227 |   write_csr(mtvec, &trap_entry);                                                                                                                                                                    
      |   ^~~~~~~~~                              
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:175:9: error: expected ';' before 'volatile'
  175 |     asm volatile ("csrw " #reg ", %0" :: "i"(val)); \
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:227:3: note: in expansion of macro 'write_csr'
  227 |   write_csr(mtvec, &trap_entry);
      |   ^~~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:177:9: error: expected ';' before 'volatile'
  177 |     asm volatile ("csrw " #reg ", %0" :: "r"(val)); })
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:227:3: note: in expansion of macro 'write_csr'
  227 |   write_csr(mtvec, &trap_entry);
      |   ^~~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:170:7: error: expected ';' before 'volatile'
  170 |   asm volatile ("csrr %0, " #reg : "=r"(__tmp)); \
      |       ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:228:7: note: in expansion of macro 'read_csr'
  228 |   if (read_csr(misa) & (1 << ('F' - 'A'))) { // if F extension is present
      |       ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:175:9: error: expected ';' before 'volatile'
  175 |     asm volatile ("csrw " #reg ", %0" :: "i"(val)); \
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:229:5: note: in expansion of macro 'write_csr'
  229 |     write_csr(mstatus, MSTATUS_FS); // allow FPU instructions without trapping
      |     ^~~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:177:9: error: expected ';' before 'volatile'
  177 |     asm volatile ("csrw " #reg ", %0" :: "r"(val)); })
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:229:5: note: in expansion of macro 'write_csr'
  229 |     write_csr(mstatus, MSTATUS_FS); // allow FPU instructions without trapping                                                                                                 
      |     ^~~~~~~~~                                                                                                                                                               
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:177:9: error: expected ';' before 'volatile'                                                             
  177 |     asm volatile ("csrw " #reg ", %0" :: "r"(val)); })                                                                                                                      
      |         ^~~~~~~~                                                                                                                                                                 
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:229:5: note: in expansion of macro 'write_csr'                                           
  229 |     write_csr(mstatus, MSTATUS_FS); // allow FPU instructions without trapping                                                                                                  
      |     ^~~~~~~~~                                                                                                                                                                    
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:175:9: error: expected ';' before 'volatile'                                                           
  175 |     asm volatile ("csrw " #reg ", %0" :: "i"(val)); \
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:230:5: note: in expansion of macro 'write_csr'
  230 |     write_csr(fcsr, 0); // initialize rounding mode, undefined at reset
      |     ^~~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/encoding.h:177:9: error: expected ';' before 'volatile'
  177 |     asm volatile ("csrw " #reg ", %0" :: "r"(val)); })
      |         ^~~~~~~~
tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.c:230:5: note: in expansion of macro 'write_csr'
  230 |     write_csr(fcsr, 0); // initialize rounding mode, undefined at reset
      |     ^~~~~~~~~
tensorflow/lite/micro/tools/make/Makefile:318: recipe for target 'tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_mcu/obj/tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freed
om-e300-hifive1/init.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/riscv32_mcu_riscv32_mcu/obj/tensorflow/lite/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/init.o] Error 1

**Comment by pjpratik** [comment]
Hi @klchiu 

Can you the tests on  RISCV using latest version and let us know if the issue still persists?

Run the cc test using bazel
```
bazel run tensorflow/lite/micro/examples/hello_world:hello_world_test

```
And to run it using make
```
make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
```
Thanks.
