### ISSUE TITLE
No registered 'swish_f32' OpKernel for GPU devices compatible with node {{node swish_3/swish_f32}}

### ISSUE THREAD

**Issue by lyw615** [tensorflow/tensorflow#50338]
When the model trained from tensorflow 1.4 infer images with tensorflow 2.3, the following message reported :

"2021-06-18 16:00:41.022400: W tensorflow/core/grappler/utils/graph_view.cc:836] No registered 'swish_f32' OpKernel for GPU devices compatible with node {{node swish_3/swish_f32}}.  Registered:  <no registered kernels>".   

My codes  implemented with tf 1.x  has been upgraded to tf2.3.  So i need to check  the model trained previously  can run normally with tf2.3.  Session  is replaced as tf.compat.v1.Session(). And the model trained with tf2.3 without this message during inference. There is also no error report when training.  Whether the message can be dropped?

**System information**

- OS Platform: Windows 7
- TensorFlow version : 2.3
- Python version: 3.7.1
- cudatoolkit  version: 10.1
- GPU : RTX 2060

**Comment by UsharaniPagadala** [comment]
@lyw615 
Could you please share the simple standalone code to reproduce the issue reported here.
Also refer similar issues [link1](https://github.com/google/automl/issues/24), [link2](https://www.programmersought.com/article/58604670525/) .Thanks

**Comment by lyw615** [comment]
I have tried the two links. But there is no   " relu_fn = tf.nn.swish" in my code. And  my code is mixed with tf and  tf.keras.

**Comment by lyw615** [comment]
The message only reported **once** during the operation  "self.sess.run(y, feed_dict={x: predict_tile[i * batch_size:(i + 1) * batch_size, :]})" .  And it company with the following message :

2021-06-21 10:35:45.565000: W tensorflow/core/grappler/utils/graph_view.cc:836] No registered 'swish_f32' OpKernel for GPU devices compatible with node {{node swish_69/swish_f32}}
	.  Registered:  <no registered kernels>
2021-06-21 10:35:45.988000: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2021-06-21 10:35:46.387000: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2021-06-21 10:35:47.976000: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.

**Comment by UsharaniPagadala** [comment]
@lyw615 

Could you please provide the standalone code/colab gist.Thanks

**Comment by lyw615** [comment]
Sorry， but the project is commercial code. Maybe i will ignore the problem by adding "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'"

**Comment by UsharaniPagadala** [comment]
@lyw615 

Could you please refer this [blog](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf) and also see the  [comment](https://stackoverflow.com/questions/65676011/invoking-gpu-asm-compilation-is-supported-on-cuda-non-windows-platforms-only-re),  hope it helps.Thanks
