### ISSUE TITLE
Conv2D fails with sparse input

### ISSUE THREAD

**Issue by Mastiff37** [tensorflow/tensorflow#50349]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Centos7
- TensorFlow installed from (source or binary):  Conda install
- TensorFlow version (use command below):  2.5.0-rc3
- Python version: 3.7.5

I'm not certain if this is a bug or missing feature?  Trying to run sparse data through convolutional layer, but error immediately results:

```
x = keras.Input(shape=(100,100,2), sparse=True)                        
C = keras.layers.Conv2D(16,(3,3))(x)  
```
Error as follows:

`TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("Placeholder_1:0", shape=(None, 4), dtype=int64), values=Tensor("Placeholder:0", shape=(None,), dtype=float32), dense_shape=Tensor("PlaceholderWithDefault:0", shape=(4,), dtype=int64)). Consider casting elements to a supported type.`

**Comment by UsharaniPagadala** [comment]
@Mastiff37 
Could you please provide complete code/colab gist in order to expedite the trouble-shooting process.
also refer similar  [issue](https://github.com/tensorflow/models/issues/6245) and let us know if it helps.Thanks

**Comment by Mastiff37** [comment]
All it takes to create the error is to enter those two lines, for example in an ipython terminal.  Do you need more than that?  Because I never got beyond that myself.  Thanks.

**Comment by UsharaniPagadala** [comment]
@Mastiff37 

Could you please refer [this](https://github.com/tensorflow/tensorflow/issues/25980),and let us know if it helps.Thanks

**Comment by Mastiff37** [comment]
Thanks for the reply.  I don't see anything there that exactly applies.  Are you referring to the solutions where the input is manually converted to dense before use?

**Comment by UsharaniPagadala** [comment]
@jvishnuvardhan 

I was able to replicate the issue reported.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/286ecb2930df1be64e9743b5bb63566e/untitled117.ipynb#scrollTo=rsUYR9Nhr5p0) here.Thanks

**Comment by jvishnuvardhan** [comment]
@Mastiff37 I think `sparse` input is not supported. Some other layers like `Dense` supports `sparse` tensors. You could convert sparse tensors into dense tensors and pass it to the `Conv` layers. Thanks!

**Comment by Mastiff37** [comment]
Understood.  The desired use case is one in which processing the non-sparse version is impractical.  But maybe this is a feature request rather than an issue.  Or maybe the issue is that a more helpful error message could be provided, indicating lack of support?

**Comment by jvishnuvardhan** [comment]
@Mastiff37 Recently keras team improved `layers.preprocessing` code. If the current preprocessing layers are not supporting, then please raise an issue in [keras-team/keras](https://github.com/keras-team/keras/issues). Please note that Keras development moved to another repository to focus entirely on only keras. 

When you open a new issue, please provide a standalone code with some toy data to test and understand the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
Agree with you on the error message. Will try to update it. Thanks!
