### ISSUE TITLE
fatal error C1007

### ISSUE THREAD

**Issue by XDSwang** [tensorflow/tensorflow#50341]
fatal error C1007: 无法识别的标志“-ReducedOptimizeHugeFunctions”(在“p2”中)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 16.981s, Critical Path: 1.50s
INFO: 8 processes: 8 internal.
FAILED: Build did NOT complete successfully

**Comment by tilakrayal** [comment]
@XDSwang ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

Thanks!

**Comment by XDSwang** [comment]
win64
TensorFlow-master
python3.6/3.88/3.95
virtualenv/conda
vs2019/c++2019..
cuda10.2/cudnn8.2
bazel3.7.2/5.
...
@tilakrayal 
 Used above

**Comment by tilakrayal** [comment]
@XDSwang ,

Installation issues within the Anaconda environment are tracked in the Anaconda repo.
 
Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!

**Comment by mihaimaruseac** [comment]
You need a very recent MSVC compiler

**Comment by XDSwang** [comment]
> You need a very recent MSVC compiler
The latest is not 2019?
Am I wrong about my circumstances

**Comment by mihaimaruseac** [comment]
See https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019

Make sure you have both the redistributable and the tools installed, not only the IDE

**Comment by XDSwang** [comment]
> See https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019
> 
> Make sure you have both the redistributable and the tools installed, not only the IDE
tensorflow/python/lib/core/bfloat16.cc(633): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(633): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(637): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(637): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(641): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(641): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(644): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(644): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(648): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(648): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(652): error C2664: “bool tensorflow::`anonymous-namespa
ce'::Initialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()(const char *,PyUFuncGen
ericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (__cdecl *)(char **,npy_
intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(652): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(627): note: 参见“tensorflow::`anonymous-namespace'::Ini
tialize::<lambda_d8b2248041b81857d7d292521348d314>::operator ()”的声明
[13,438 / 13,648] 75 actions, 3 running
    Compiling tensorflow/c/c_api_experimental.cc; 13s local
[13,441 / 13,648] 72 actions, 0 running
    [Scann] Compiling tensorflow/core/grappler/optimizers/data/map_vectorization.cc; 549s
Target //tensorflow/tools/pip_package:build_pip_package failed to build
[13,441 / 13,648] 72 actions, 0 running
    [Scann] Compiling tensorflow/core/grappler/optimizers/data/map_vectorization.cc; 549s
INFO: Elapsed time: 15910.390s, Critical Path: 393.21s
[13,441 / 13,648] 72 actions, 0 running
    [Scann] Compiling tensorflow/core/grappler/optimizers/data/map_vectorization.cc; 549s
INFO: 10536 processes: 10536 local.
[13,441 / 13,648] 72 actions, 0 running
    [Scann] Compiling tensorflow/core/grappler/optimizers/data/map_vectorization.cc; 549s
FAILED: Build did NOT complete successfully
???

**Comment by mihaimaruseac** [comment]
What version of `numpy` are you using?
