### ISSUE TITLE
What direction is tensorflow moving to 

### ISSUE THREAD

**Issue by partus** [tensorflow/tensorflow#50346]
I decided to formulate this as an issue as did not find any more appropriate place to write it.

Currently, there is a huge work done in between  tensorflow1 to tensorflow2. Tf 1 was heavily dependent on graphs, while tf2 has moved to functions. Meanwhile, there is a  `tf.compat` which tries to establish compatibility.  All this stuff rises some complexity. e.g,  someone may accounter to :  I want to eliminate variables so that my model run faster ( not with tf serving) ... ah... ok, I need to use tf.compat.v1 then transform it to graph... then you encounter with different methods of loading a model, with some functions in tf , some functions in tf.compat.v1 etc. All this stuff become not intuitive . I understand that all this stuff is transitional and will settle down at some point.  What would be nice to know in advance is where is it moving, so what is the destination. Is it a process of getting rid of graphs and becoming something similar to pytorch API ?Or,  will it settle down and become some nice combination of graphs+ functions so that the api is clear and comprehensible? What a tensorflow user should expect , what should they try to understand and what will be gone ? What will be the model of tensorflow in the future ?

It would be nice if you could explain your vision related to tensorflow  either in this issue or some different material.

**Comment by mihaimaruseac** [comment]
`@tf.function` decorator takes a Python imperative TF eager code and builds a graph behind the scenes.

Since this is not discussing bugs/features, but more a question about philosophy, maybe it's better to ask it on the [Community Forum](https://discuss.tensorflow.org/) instead?

**Comment by rmothukuru** [comment]
Closing the issue in favor of Mihai's comment. Thanks!
