### ISSUE TITLE
How string tensor to numpy array float32?

### ISSUE THREAD

**Issue by zhonghui5207** [tensorflow/tensorflow#50358]
tf.Tensor(
[b'[ 0.02097283 -0.00030136  0.02027434  0.01413146 -0.05076262]'
 b'[ 0.0262014   0.06108821  0.02988876  0.02189768 -0.10167235]'
 b'[ 0.03268104 -0.006452   -0.02572624 -0.02183151 -0.0120374 ]'
 b'[ 0.05750999  0.03042973 -0.00485849  0.03983038  0.01241926]'
 b'[-0.05423493  0.03896134  0.08271325 -0.00260455 -0.0601045 ]'
 b'[-0.05363343  0.0085776   0.06006461 -0.04733948  0.03426042]'
 b'[-0.00538311 -0.03473232  0.05594373  0.02615744 -0.00020107]'
 b'[-0.09023542 -0.01520202  0.02594413  0.0152848   0.02993004]'
 b'[ 0.02597977  0.01155447 -0.03341909  0.01283126 -0.00788336]'
 b'[-0.0311645  -0.02193766  0.01195193 -0.00156491  0.02515437]'
 b'[-0.02063796 -0.02474995 -0.00826916 -0.07110358 -0.01128928]'
 b'[-0.02542101  0.01105374  0.06318881 -0.06937706 -0.01915297]'
 b'[-0.09416252  0.00973927  0.03317858  0.06058807 -0.04148066]'
 b'[-0.01365746  0.03451785  0.06412476  0.02822566 -0.00999724]'
 b'[-0.0171374   0.0715599   0.05882246  0.01296736 -0.00091868]'
 b'[ 0.00693085 -0.04560864  0.02032861 -0.04077329 -0.00946539]'
 b'[-0.06874597  0.04256656 -0.02906736  0.04013787  0.00206867]'
 b'[-0.01034078 -0.05094369  0.08312039 -0.00587852  0.01176884]'
 b'[-0.06719685  0.05213002  0.03297217 -0.01096502 -0.0350911 ]'
 b'[ 0.05109432  0.02179589  0.05981123  0.00137072 -0.03289427]'
 b'[ 0.00146687  0.06880862  0.05646181  0.02786043 -0.03881097]'
 b'[-0.02244576  0.0231379   0.06871274 -0.00127656 -0.0272399 ]'
 b'[-0.04374747 -0.06226141  0.13758671 -0.00678062 -0.03487266]'
 b'[-0.00418507  0.03274211  0.0689674  -0.05106321 -0.03625463]'
 b'[-0.03213548  0.00827215  0.00770648 -0.03131473 -0.01863099]'
 b'[ 0.06207936  0.00689174  0.10711489 -0.03350456  0.01081521]'
 b'[ 0.02757066 -0.0253685   0.12062814 -0.00970585  0.02902891]'
 b'[-0.02885368 -0.0160449   0.14081968  0.02503997 -0.00294884]'
 b'[ 0.07023901  0.05541587  0.02016265 -0.03657229  0.04771656]'
 b'[-0.0209682  -0.0051748   0.09555192  0.02832836 -0.08762222]'
 b'[-0.05938871  0.07186659  0.12110886 -0.02638434  0.00429018]'
 b'[-0.11481152 -0.04604804  0.11981387 -0.00891783 -0.02516906]'
 b'[-0.03681243  0.03241169  0.07067283  0.03979958  0.03641473]'
 b'[ 0.08654588 -0.01150938 -0.0563741  -0.02497471  0.04594599]'
 b'[-0.03297099  0.01769503  0.11319669  0.01238059  0.0082001 ]'
 b'[-0.00865924 -0.01036084  0.01999265 -0.02626343 -0.01680002]'
 b'[-0.05190443  0.03164011  0.02040888  0.00856969 -0.0272375 ]'
 b'[-0.05195722  0.05240251  0.1554347   0.03092176  0.03021973]'
 b'[ 0.02322851 -0.04756063  0.02221033 -0.01971874  0.02247192]'
 b'[-0.04352621  0.04046606  0.0664994  -0.04015313 -0.0013613 ]'
 b'[-0.03193593 -0.04119597  0.08940079 -0.08665874 -0.01585988]'
 b'[-0.03285274 -0.09046161  0.02063147 -0.01080728  0.01723639]'
 b'[-0.04092724 -0.00503651  0.04953369  0.02530581 -0.02194984]'
 b'[-0.03308328  0.0108201   0.08706747  0.01400463  0.00957526]'
 b'[ 0.01701859  0.00838621  0.08922331 -0.00337605  0.02646657]'
 b'[-0.06959544  0.04555301  0.02370284  0.01276516  0.03738073]'
 b'[-0.01415364  0.02345778  0.13541281  0.00027695  0.03363715]'
 b'[-0.06227937  0.01147403  0.04096422  0.06501009 -0.05931246]'
 b'[ 0.04575171  0.02199615  0.09396678 -0.03892348 -0.00266673]'
 b'[-0.00880066  0.07396847  0.05845954  0.0611381  -0.02724584]'
 b'[-0.09053511 -0.07695854  0.08236924 -0.0004557   0.03071151]'
 b'[-0.06687004 -0.00884794  0.06785945 -0.01278874  0.00910276]'
 b'[-0.06192718  0.04024284  0.04660054  0.03686318 -0.05565461]'
 b'[ 0.00812656 -0.03686302  0.09414893  0.02846115 -0.0320286 ]'
 b'[ 0.00260613  0.02772786  0.02776031 -0.05296541 -0.06279145]'
 b'[ 0.06081159  0.04025939  0.01868677 -0.01511183 -0.06156038]'
 b'[ 0.06705007  0.02358671  0.05917825 -0.04668655 -0.01996517]'
 b'[-0.02651405 -0.03667055  0.1276829   0.02881959 -0.05748772]'
 b'[-0.04663552  0.02453288  0.16361675 -0.04503557 -0.04188378]'
 b'[-0.0375299   0.0024564   0.08636113 -0.00160064 -0.00404025]'
 b'[ 0.10195461 -0.09637161  0.08657964  0.01170785 -0.00702063]'
 b'[-0.00990426  0.01018562  0.051896   -0.02190032  0.01513071]'
 b'[-0.01914701  0.08492666  0.0164949   0.04085653  0.01324011]'
 b'[ 0.05544649  0.00318151  0.05673654 -0.00993952 -0.02152128]'
 b'[-0.0254409   0.01935307  0.01199189 -0.00708791  0.00387142]'
 b'[-0.0282771   0.04030829  0.05126983 -0.04400632 -0.0082527 ]'
 b'[0.01513346 0.01526676 0.03014831 0.02528955 0.05057558]'
 b'[ 0.00170263 -0.05140645  0.01383791  0.1049732  -0.0187094 ]'
 b'[-0.05105732 -0.00549103 -0.00211255  0.00382627  0.03240367]'
 b'[ 0.08392965  0.05782474  0.04813674 -0.012268   -0.01868831]'
 b'[ 0.02100096  0.02253112 -0.01667141 -0.01646966  0.02927297]'
 b'[ 0.02955185 -0.0215682   0.06128283 -0.07923301 -0.03955455]'
 b'[-0.00260352  0.05469373  0.03105753  0.01570494  0.04612614]'
 b'[-0.04520263 -0.01102473  0.04200301  0.00765652  0.02229562]'
 b'[-0.03557624  0.02408457  0.04376483  0.01995172  0.03095791]'
 b'[-0.02472683  0.05018009  0.05735757 -0.03225219 -0.02325426]'
 b'[ 0.01198511  0.07219561 -0.04000699  0.00166795  0.02750094]'
 b'[ 0.03821035 -0.05754133  0.05844725 -0.01565812 -0.02900359]'
 b'[ 0.00653413  0.05587009  0.01621004 -0.01408313  0.0698965 ]'
 b'[ 0.00032702  0.04052418  0.05641509 -0.03344009 -0.03914972]'
 b'[-0.04089393 -0.00665233  0.12799472 -0.02873646 -0.00894405]'
 b'[-0.01444164 -0.03190748  0.00951358 -0.00564088 -0.03646583]'
 b'[ 0.00547115  0.05014327 -0.01592914 -0.00122629  0.04477547]'
 b'[-0.01207544  0.00356778  0.00447336 -0.0287638  -0.03753311]'
 b'[-0.05884602  0.01072115  0.02425918  0.02255262 -0.01806048]'
 b'[-0.01731539 -0.02231116  0.09437364  0.00170555 -0.05407009]'
 b'[ 0.06500567  0.01848128 -0.0014751  -0.0306924  -0.02501157]'
 b'[-0.05805401 -0.03961165  0.02174086 -0.04895382  0.08139951]'
 b'[ 0.00627512 -0.10157526  0.02130324 -0.0502402   0.01576446]'
 b'[-0.00976898 -0.05913119  0.04541657  0.05631701  0.05014214]'
 b'[ 0.012176    0.01870439 -0.09938233 -0.02261297  0.00181638]'
 b'[ 0.00652808 -0.05605447 -0.07694134 -0.0147412  -0.00597148]'
 b'[ 0.11674304  0.01894933  0.04533885 -0.06286294 -0.00410459]'
 b'[ 0.01085297 -0.01358635  0.0152023   0.02346188 -0.02940939]'
 b'[-0.07113044 -0.0611495   0.08770485 -0.06983516 -0.05291767]'
 b'[ 0.05899842 -0.01446779  0.07837778 -0.03993104  0.00525863]'
 b'[-0.10755081  0.0300941   0.07934867 -0.02394172 -0.02204445]'
 b'[-0.0311101   0.04656944  0.03284094 -0.03410514 -0.05289885]'
 b'[ 0.08936132  0.01549069 -0.08579474 -0.0308104   0.03784556]'
 b'[ 0.00364001 -0.01364339  0.01154843 -0.00796111 -0.04738059]'
 b'[-0.03339433 -0.00842785  0.04478682 -0.01196976 -0.04958511]'
 b'[-0.03358311  0.04321984  0.05168601 -0.01089774 -0.02395501]'
 b'[-0.06558623  0.04269782  0.0612884  -0.05247656 -0.00742848]'
 b'[-0.02506015  0.03288777 -0.02826415 -0.03411807  0.02337966]'
 b'[-0.0063935  -0.06393326 -0.00221541 -0.00846948 -0.00674942]'
 b'[-0.01611812 -0.04033646  0.07721135 -0.03097609 -0.0332734 ]'
 b'[ 0.06345142 -0.02645344  0.0762206   0.0113527   0.02931798]'
 b'[0.02701272 0.03514359 0.12304931 0.00486567 0.05368165]'
 b'[-0.01498978  0.00275506  0.09848753 -0.05815676 -0.02021742]'
 b'[-0.07171111 -0.09847055  0.10210885 -0.01390746 -0.01117994]'
 b'[ 0.05652616  0.020263    0.08677369  0.04779573 -0.02989006]'
 b'[-0.00321592  0.08285369  0.07023705  0.01291879  0.02472301]'
 b'[ 0.07298638 -0.01532689  0.02540569 -0.02986414  0.01640994]'
 b'[-0.03712279  0.01163841  0.13998468 -0.00304863  0.04347893]'
 b'[-0.03525798  0.01185983  0.13191286 -0.01959012  0.03257367]'
 b'[-0.04548401 -0.02758195  0.00168344 -0.03186819  0.00271737]'
 b'[-0.03803202 -0.00824933  0.06340004 -0.01111551  0.01700836]'
 b'[-0.06189108 -0.03465553  0.07799784  0.01622717 -0.03012843]'
 b'[ 0.01731179 -0.00914969  0.00600643 -0.04678116  0.02879524]'
 b'[-0.01725049  0.02091795  0.11079015  0.04469016  0.03707935]'
 b'[-0.04465106  0.02234716  0.06541137  0.01215733 -0.00971021]'
 b'[ 0.01089822 -0.01503999 -0.01136935  0.05091227 -0.01141826]'
 b'[-0.01596685 -0.01873063  0.05162324  0.04050293 -0.0415377 ]'
 b'[ 0.03071246 -0.01387434  0.17381501  0.02932012  0.0157283 ]'
 b'[-0.07127521  0.03927163  0.08532428 -0.04077393 -0.05403168]'
 b'[-0.06733387  0.01606675 -0.04003966  0.05473982 -0.05073515]'
 b'[-0.02546638  0.02652799  0.08205058 -0.01278413 -0.00037502]'
 b'[-0.00655765 -0.0049662   0.02634083  0.04414084 -0.00299913]'], shape=(128,), dtype=string)
 
a embedding columns of Pandas dataframe,  i will do
 ds = tf.data.Dataset.from_tensor_slices((dict(df), label))
 
 [(train_features, label_batch)] = ds.take(1)
            print('Every feature:', list(train_features.keys()))
            print('A batch of feed_embedding:', train_features['feed_embedding'])
            
how string tensor to numpy array float32?

**Comment by ymodak** [comment]
Have you tried using `tf.strings.to_number` https://www.tensorflow.org/api_docs/python/tf/strings/to_number
