### ISSUE TITLE
HOW string Tensor  to Numpy array

### ISSUE THREAD

**Issue by zhonghui5207** [tensorflow/tensorflow#50357]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tens
[aaa.txt](https://github.com/tensorflow/tensorflow/files/6679901/aaa.txt)
orflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by UsharaniPagadala** [comment]
@zhonghui5207 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]. Thanks

**Comment by ymodak** [comment]
duplicate #https://github.com/tensorflow/tensorflow/issues/50358
