### ISSUE TITLE
 error C2664: “bool tensorflow::`anonymous-namespace'

### ISSUE THREAD

**Issue by XDSwang** [tensorflow/tensorflow#50369]
tensorflow/python/lib/core/bfloat16.cc(635): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(635): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(639): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(639): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(643): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(643): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(646): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(646): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(650): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(650): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
tensorflow/python/lib/core/bfloat16.cc(654): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(654): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1600.752s, Critical Path: 348.93s
INFO: 566 processes: 566 local.
FAILED: Build did NOT complete successfully

**Comment by UsharaniPagadala** [comment]
@XDSwang 
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md) has not been filled, could you please do so as it helps us analyse the issue .Thanks
