### ISSUE TITLE
Input to reshape is a tensor with 256 values, but the requested shape has 16 	 [[node sequential/dense_features/G/Reshape (defined at <ipython-input-39-b5709d2bb787>:2) ]] [Op:__inference_predict_function_9466]

### ISSUE THREAD

**Issue by pawansingh1610** [tensorflow/tensorflow#50378]
def predict_input_fn(fileNames,patch,bands):

  # You have to know the following from your export.
  PATCH_WIDTH, PATCH_HEIGHT = patch
  PATCH_DIMENSIONS_FLAT = [PATCH_WIDTH * PATCH_HEIGHT, 1]

  # Note that the tensors are in the shape of a patch, one patch for each band.
  imageColumns = [
    tf.io.FixedLenSequenceFeature(shape=PATCH_DIMENSIONS_FLAT, dtype=tf.float32, allow_missing=True) 
      for k in bands
  ]

  featuresDict = dict(zip(bands, imageColumns))
  dataset = tf.data.TFRecordDataset(fileNames, compression_type='GZIP')
  
  # Make a parsing function
  def parse_image(example_proto):
    parsed_features = tf.io.parse_single_example(example_proto, featuresDict)
    return parsed_features

  dataset = dataset.map(parse_image, num_parallel_calls=4)
  
  # Break our long tensors into many littler ones

  dataset = dataset.flat_map(lambda features: tf.data.Dataset.from_tensor_slices(features))

  # Read in batches corresponding to patch size.
  dataset = dataset.batch(PATCH_WIDTH * PATCH_HEIGHT)

  return dataset

predict_db = predict_input_fn(fileNames=imageFilesList,patch=[4,4],bands=['R', 'G', 'B', 'NDVI'])
predictions = model.predict(predict_db)

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by pawansingh1610** [comment]
https://colab.research.google.com/drive/1VKhYGnPDKDlEWoVOqlVykpt7PJq_vG05?usp=sharing

**Comment by saikumarchalla** [comment]
@pawansingh1610   Please create a colab gist and share with us since we are unable to access the drive which you have shared. Thanks!

**Comment by pawansingh1610** [comment]
https://github.com/pawansingh1610/tf_ee2/blob/main/tf_ee2.ipynb

**Comment by saikumarchalla** [comment]
Tried to reproduce the issue but facing different error like to signup on earth engine. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/4e45f565c4293976e6212b6ec62cbf72/tf_ee2.ipynb). Thanks!
