### ISSUE TITLE
Feature request: bounds_check header in python package

### ISSUE THREAD

**Issue by trsaunders** [tensorflow/tensorflow#5037]
I think it would be useful if "tensorflow/core/kernels/bounds_check.h" was included in the python package, so that FastBoundsCheck() can be used in a custom Op when building against the binary package.

I patched this manually by adding bounds_check.h to framework_headers in tensorflow/core/BUILD:

``` diff
diff --git a/tensorflow/core/BUILD b/tensorflow/core/BUILD
index 2c936bd..44210f7 100644
--- a/tensorflow/core/BUILD
+++ b/tensorflow/core/BUILD
@@ -1136,6 +1136,7 @@ filegroup(
         "framework/type_traits.h",
         "framework/types.h",
         "framework/unique_tensor_references.h",
+        "//tensorflow/core/kernels:bounds_check.h",
         "lib/core/errors.h",
         "lib/core/notification.h",
         "lib/core/refcount.h",
```

I'm not sure if this is the correct way of doing this, so I'm making a feature request instead of a pull request.

Thanks!

**Comment by drpngx** [comment]
Nice, please submit a pull request.

**Comment by trsaunders** [comment]
This has been  #superseded by issue #4996 and is no-longer required.

Thanks for your consideration.
