### ISSUE TITLE
Django 

### ISSUE THREAD

**Issue by Thecoderlegend101** [tensorflow/tensorflow#50373]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: 3.9
- Installed using virtualenv? pip? conda?:Pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
 I get this error when installing Django and Django rest framework :
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'c:\\python39\\Scripts\\django-admin.py'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install django djangorestframework

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Collecting django
  Using cached Django-3.2.4-py3-none-any.whl (7.9 MB)
Collecting djangorestframework
  Using cached djangorestframework-3.12.4-py3-none-any.whl (957 kB)
Requirement already satisfied: asgiref<4,>=3.3.2 in c:\python39\lib\site-packages (from django) (3.3.4)
Requirement already satisfied: sqlparse>=0.2.2 in c:\python39\lib\site-packages (from django) (0.4.1)
Requirement already satisfied: pytz in c:\python39\lib\site-packages (from django) (2021.1)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Installing collected packages: django, djangorestframework
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'c:\\python39\\Scripts\\django-admin.py'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.

**Comment by UsharaniPagadala** [comment]
@Thecoderlegend101 
The is not relevant to tensorflow issue.Please post this in [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow).There is a big community to answer these kind of questions.
Please also refer similar  [issue](https://stackoverflow.com/questions/37573350/error-while-installing-django-rest-framework).Thanks
