### ISSUE TITLE
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by ElectroSkills-channel** [tensorflow/tensorflow#50386]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows 10
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):   Tensorflow 2.5.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):  ARM

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

After a long search in other forums for my problem, any solution fund won’t work for me. I hope that you can help me to overcome this problem.
the problem is while doing post-training integer quantization of a GRU model, it gives me the following error :
**ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.**
I tried TensorFlow 2.4.1, tf-nightly, but no one works.
I think the problem is with my **representative_dataset** , but it works with CNN 1D.
**My code:**

`converter = tf.lite.TFLiteConverter.from_saved_model(LSTMMODEL_TF)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset_gen():
	for sample in XX_data:
	    sample = np.expand_dims(sample.astype(np.float32), axis=0)
	    yield [sample]

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

converter.representative_dataset = repr_data_gen
model_tflite = converter.convert()

open(LSTMODEL_TFLITE, "wb").write(model_tflite)`

**Comment by saikumarchalla** [comment]
@ElectroSkills-channel  Could you please submit a new issue here since all micro related issues are handled separately.Thanks!
