### ISSUE TITLE
Didn't find op for builtin opcode 'SUM' version '1'

### ISSUE THREAD

**Issue by drrll** [tensorflow/tensorflow#50383]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 11.4
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 2.5 (a4dfb8d1a71)
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): STM Cortex M4

**Describe the problem**
The SUM operator is not supported in TF Lite Microcontroller, even though it is supported in TF Lite. I assume it's a pretty easy operation to get ported to MCU? I'm getting 
`Didn't find op for builtin opcode 'SUM' version '1'`

**Please provide the exact sequence of commands/steps when you ran into the problem**
Run any TF Model with SUM operator, `AllocateTensors()` will print out `Didn't find op for builtin opcode 'SUM' version '1'`

**Comment by galah92** [comment]
I also need this. Is this something that's possible to contribute?
