### ISSUE TITLE
Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void * )' to 'PyUFuncGenericFunction'

### ISSUE THREAD

**Issue by XDSwang** [tensorflow/tensorflow#50387]
ERROR:.../pycharmprojects/pythonproject/tensorflow/tensorflow/python/BUILD:437:1: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (
Exit 2)
tensorflow/python/lib/core/bfloat16.cc(635): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(635): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
tensorflow/python/lib/core/bfloat16.cc(639): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(639): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
tensorflow/python/lib/core/bfloat16.cc(643): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(643): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
tensorflow/python/lib/core/bfloat16.cc(646): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(646): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
tensorflow/python/lib/core/bfloat16.cc(650): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(650): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
tensorflow/python/lib/core/bfloat16.cc(654): error C2664: 'bool tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::operato
r ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const': cannot convert argument 2 from 'void (__cdecl *)(char **,npy_intp *,npy_intp *,void *
)' to 'PyUFuncGenericFunction'
tensorflow/python/lib/core/bfloat16.cc(654): note: None of the functions with this name in scope match the target type
tensorflow/python/lib/core/bfloat16.cc(629): note: see declaration of 'tensorflow::`anonymous-namespace'::Initialize::<lambda_a7b8b31d992e5b5e4dc9d84f5f519c90>::
operator ()'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 12840.328s, Critical Path: 449.09s
INFO: 7087 processes: 7087 local.
FAILED: Build did NOT complete successfully
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Tested build configuration 
cpu  tensorflow-2.2.0	python3.7	MSVC 2019	Bazel 2.0.0

**Comment by Saduf2019** [comment]
I see multiple issues created, as requested earlier please fii in the issue template:#50356,#50369
Please verify:
1)if you have latest MSVC compiler
2)python & os of 64 bits
3)compatibility issues , system requirements
4)please try to change your numpy version and let us know if the issue exist, [run bazel clean after downgrading ur numpy if in case]
we will not be able to help you unless issue template is filled a sit helps us analyse the issue.
