### ISSUE TITLE
TypeError: An op outside of the function building code is being passed a "Graph" tensor.

### ISSUE THREAD

**Issue by ckhuangf** [tensorflow/tensorflow#50398]
Hi I got following error when including a customized DropConnectDense layer. The Error seems to be related to the update of  kernel and bias.  Any helps will be appreciated.  Thanks.

Traceback (most recent call last):

    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: MLRM_TFNN_DROPCONNECT/den2_1/dropout/Mul_1:0

The DropConnectDense class I have:
```
from tensorflow.python.ops import gen_math_ops
from tensorflow.python.ops import nn_ops

class DropConnectDense(Dense):
    def __init__(self, *args, **kwargs):
        self.rate = kwargs.pop('rate', 0.5)
        if 0. < self.rate < 1.:
            self.uses_learning_phase = True

        super(DropConnectDense, self).__init__(*args, **kwargs)

    def call(self, inputs):

        if 0. < self.rate < 1.:
            kernel = K.in_train_phase(nn_ops.dropout(self.kernel, rate = self.rate), self.kernel)
            bias = K.in_train_phase(nn_ops.dropout(self.bias, rate = self.rate), self.bias)
        else:
            kernel = self.kernel
            bias = self.bias
            self.kernel = kernel
            self.bias = bias

        outputs = gen_math_ops.MatMul(a = inputs, b = kernel)
        if self.use_bias:
          outputs = nn_ops.bias_add(outputs, bias)

        if self.activation is not None:
          outputs = self.activation(outputs)
        return outputs


    def get_config(self):
        config = super(DropConnectDense, self).get_config()
        config.update({
            'rate': self.rate,
            'uses_learning_phase': self.uses_learning_phase,
        })

        return config
```

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by ckhuangf** [comment]
Looks like I can get it worked with 
`            tf.compat.v1.disable_eager_execution()
`
before the model is built.

**Comment by saikumarchalla** [comment]
@ckhuangf  Could you please go ahead and close the issue if you don't have any further queries. Thanks!

**Comment by lekshmyharitha** [comment]
I had the same issue. How did you rectify this?
