### ISSUE TITLE
GPU resource can not be found in tensorlfow-gpu2.3.0

### ISSUE THREAD

**Issue by v3551G** [tensorflow/tensorflow#50391]
When I upgrade tensorflow from 2.1.0 to 2.3.0, the GPU can not be found.
My old environment: python3.6+CUDA10.2+Tensorflow-gpu2.1.0, I can successfully run my code using this environemnt, both in graph mode and non-Graph mode.

Then, I created a new environment: python3.7+Tensorflow-gpu2.3.0, and run my code using this environment. I found, the GPU resource could not be found (the output of the commound "tf.config.experimental.list_physical_devices('GPU'") is [ ]).
I think it's caused by the version of CUDA at the first glance. Then I upgrade CUDA from 10.2 to 11.0, but the issue remains unsolved.

Can anyone help solving this issue?

**Comment by UsharaniPagadala** [comment]
@v3551G 


We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Thanks
