### ISSUE TITLE
TFlite shape

### ISSUE THREAD

**Issue by xzy-666** [tensorflow/tensorflow#50396]
hello，
Computer environment:window 10 ;tensorflow 1.13.0; python3.6 ; tflite-runtime  2.1.0.post1; 
save tflite code
    **_def save(self):
        converter = tf.lite.TFLiteConverter.from_session(self.session, [self.ts.x, self.ts.x_peak], [self.ts.logits])
        tflite_model = converter.convert()
        with open("model/" + cfg.name + '/model.tflite', "wb") as f:
            f.write(tflite_model)
        print('model is in {}'.format(self.save_path))_**
when I set the  the x ( input model) shape is [10, 1801, 2], it product tflite is right ,and   in the tflite input_details is [10, 1801, 2],however, I need the shape is [1, 1801, 2];So, when I set the x shape is [None, 1801, 2] ; but when I train the model, it is error that as follows
**_Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/mix/train.py", line 400, in <module>
    app.train(train_data, val_data)
  File "C:/Users/Administrator/Desktop/mix/train.py", line 265, in train
    ts.train_summary, ts.loss_summary], feed)
  File "D:\Users\Administrator\anaconda3\envs\python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "D:\Users\Administrator\anaconda3\envs\python36\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 1801, 2) for Tensor 'self.x:0', which has shape '(1, 1801, 2)'_**

I know the reason is that producting tflite cause x that change it's shape ；but I don't know how to solve it ;I sincerely hope you can understand my poor English！Thanks！！！

**Comment by tilakrayal** [comment]
@xzy-666 ,

Can you please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also, We see that you are using tf version 1.x which is not actively supported, please update to 2.x and in order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by miaout17** [comment]
+1 to the idea of upgrading to TensorFlow 2.x. TensorFlow Lite in TensorFlow 2.x should have good support of dynamic shape. 

On the other hand, it seems you're running to some shape issues in your training script, which is not directly relevant to TensorFlow Lite. It's hard to help you without knowing what's the actually code you're running.

**Comment by xzy-666** [comment]
> +1 to the idea of upgrading to TensorFlow 2.x. TensorFlow Lite in TensorFlow 2.x should have good support of dynamic shape.
> 
> On the other hand, it seems you're running to some shape issues in your training script, which is not directly relevant to TensorFlow Lite. It's hard to help you without knowing what's the actually code you're running.

hello, miaout17, thanks！！！
 The problem is that the tflite-runtime does not adapt well to tensorflow1.x .So, I've converted offline and saved it as tflite model . however, I want to know why TensorFlow 1.x not  good support of dynamic shape.

**Comment by tilakrayal** [comment]
@xzy-666 ,

As mentioned above tf v1.x is not actively supported, can you please try to execute the code in tf v2.x and let us know if you are facing same issue.Thanks!

**Comment by xzy-666** [comment]
> @xzy-666 ,
> 
> As mentioned above tf v1.x is not actively supported, can you please try to execute the code in tf v2.x and let us know if you are facing same issue.Thanks!

@tilakrayal, hello
Shame to say, I'm not familiar with tensorflow 2.x. Can you provide some materials for learning tensorflow 2.0? I will master it as soon as possible.thanks!!!

**Comment by tilakrayal** [comment]
@xzy-666 ,

Please refer this tensorflow website which provides the information on tensorflow latest versions.[Link](https://www.tensorflow.org/lite/tutorials).

Please free free to move the issue to closed status as the issue has resolved.Thanks!
