### ISSUE TITLE
Pip installation error 

### ISSUE THREAD

**Issue by connorb573** [tensorflow/tensorflow#50399]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 1.15 (but affects any version i try)
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip, in a venv

**Describe the problem**
Trying to Install TensorFlow using pip yields the following error, I'm specifically trying to install 1.15 but I've tried 2.x also and the same happens. I have checked similar issues and am definitely using 64bit python 3.6; I know not using the correct version of python can cause this error, but the error still persists. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
(venv) ubuntu@dde1f763d711:~$ pip install --user --upgrade tensorflow==1.15
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@connorb573 
We see that you are using a old version of tf that is not actively supported, please upgrade to tf 2.x and let us know.
Also verify the system requirements, your OS and python is 64 bits, check you[ pip version and upgrade it and try.](https://github.com/tensorflow/tensorflow/issues/47151#issuecomment-778939251)
Also try :
```$ sudo pip3 install setuptools --upgrade```

**Comment by connorb573** [comment]
Hi @Saduf2019 as I said, if I attempt to install 2.x the same issue occurs. OS and Python are both 64 bits, and pip is 21.1.2, python is 3.6.9. 

Also tried the command given in your comment and this makes no change. 

Thanks.

**Comment by Saduf2019** [comment]
@connorb573 
Could you please try the virtual env and let us know if it still an issue.
