### ISSUE TITLE
Model can be benchmarked with GPU but can't be run with GPU inside android app

### ISSUE THREAD

**Issue by ysyyork** [tensorflow/tensorflow#50394]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 7.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: RK3399
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I use the `android_aarch64_benchmark_model_plus_flex` tool and it can run perfectly with gpu and I see performance gain. 
But when I follow this link (https://www.tensorflow.org/lite/performance/gpu_advanced) to load the same model inside my android app, the `isDelegateSupportedOnThisDevice` function returned false. 
**Describe the expected behavior**
`isDelegateSupportedOnThisDevice` should return true

Additionally, I figured with the benchmark script that I currently only have valid opencl installed. (if i set --gpu_backend=gl, the benchmark script doesn't work). However, in android, it seems it's not detecting the opencl runtime correctly. Not sure if I need to load any runtime libs for opencl manually or not but it wasn't in any documentation, so assume I don't need to do that. Just wanna check if this is indeed a bug or it's by design.

**Comment by impjdi** [comment]
without a model attached, it's hard to tell.

for android 12, you need to update the manifest file so that the delegate can detect libOpenCL.so

**Comment by ysyyork** [comment]
> without a model attached, it's hard to tell.
> 
> for android 12, you need to update the manifest file so that the delegate can detect libOpenCL.so

Here is the model. https://drive.google.com/file/d/1IzvcG9p4sXyWqoOqIcIjkM4larrgvhYC/view?usp=sharing

We are still on Android 7.1 (we build embedded systems, not customer app). For the manifest file, do you have an example? i couldn't find any in the doc.

**Comment by pjpratik** [comment]
Hi @ysyyork 

Can you add these lines in Android manifest file as [this](https://github.com/tensorflow/tensorflow/issues/50394#issuecomment-868105191) comment suggests and let us know if the issue still persists.


```
<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>
           
 ```
Thaks.
