### ISSUE TITLE
Crash in Backward-Pass of grouped Conv1D

### ISSUE THREAD

**Issue by ChWick** [tensorflow/tensorflow#50397]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

Backward-Pass of grouped Convolution (Conv1D) crashes:
```
InvalidArgumentError:  filter_size does not have enough elements, requested 896, got 224
	 [[node gradient_tape/sequential/conv1d/conv1d/Conv2DBackpropFilter (defined at <ipython-input-6-c99a994f0883>:1) ]] [Op:__inference_train_function_898]
```

Forward-Pass (simple call) works.

Code is available at Colab:

https://colab.research.google.com/drive/1yyxtQCeM81cEUAVA6_z1PdtEY2P5kZ2C?usp=sharing

**Comment by ChWick** [comment]
Possibly related to https://github.com/tensorflow/tensorflow/issues/49147, and https://github.com/tensorflow/tensorflow/issues/41107

**Comment by UsharaniPagadala** [comment]
@ChWick 

`groups` controls the connections between inputs and outputs. `in_channels` and `out_channels` must both be divisible by `groups` 
 For example,

1. At groups=1, all inputs are convolved to all outputs.

2. At groups=2, the operation becomes equivalent to having two conv layers side by side, each seeing half the input channels and producing half the output channels, and both subsequently concatenated.

3. At groups= `in_channels`, each input channel is convolved with its own set of filters (of size(out_channels/in_channels)

Thanks

**Comment by ChWick** [comment]
As you can see in my example code: `in_channels==out_channels==groups==4` (case 3 from your list).

Note, that the Forward-pass (normal call during prediction) is working properly (see code):
```
print(model(np.zeros((1, 28, 28))))
```

The error occurs during training only (`model.fit`). This is probably related to computing the correct gradients when using groups > 1.

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported .Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/146e4503c0b2167a4f9cb350b3e58d2b/untitled0.ipynb) here.Thanks

**Comment by Saduf2019** [comment]
@ChWick 
Can you please refer to [this link](https://stackoverflow.com/questions/66415623/group-convolution-in-keras).

**Comment by ChWick** [comment]
The link has nothing to do with the reported issue. In the link there is a problem, that the grouped convolution operation was not present at all for the CPU in the former 2.4.1 version of tensorflow.
I am using Tensorflow 2.5.x, and the CPU operation exists now. However, I am only able to use grouped convolutions in the forward pass, but (probably) not the backward pass (computing gradients).\
In the provided gits, you can see that `model(inputs)`, i. e. `model.predcit(inputs)` is working with the grouped convolution, however `model.fit` crashes with an error message:  `gradient_tape/sequential/conv1d/conv1d/Conv2DBackpropFilter`. Due to `gradient_tape` and `Conv2DBackpropFilter` I assume that this should be related to the gradiet computation and the backward pass.

**Comment by ymodak** [comment]
Cross posting this issue to stand alone keras-team/keras repo for further investigation
