### ISSUE TITLE
How to remove custom signature of savedmodel and re-export the model

### ISSUE THREAD

**Issue by haylie-murray** [tensorflow/tensorflow#50405]
Hello,

I currently have a saved model, it is using a custom signature, but it needs to have serving_default signature def, so it should look like this: 
`signature_def['serving_default'].`

If I do saved_model_cli show it currently shows

```
signature_def['image_quality']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_image'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 224, 224, 3)
        name: input_1:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['quality_prediction'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: dense_1/Softmax:0
  Method name is: tensorflow/serving/predict
```
Is there a way to remove the custom name and re-export the model in tensorflow v2 in order to have the serving_default signature?

**Comment by UsharaniPagadala** [comment]
@haylie-murray 
Could you please refer [this](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/saved_model.ipynb#scrollTo=2ujwmMQg7OUo) and let us know if  it  helps.Thanks

**Comment by haylie-murray** [comment]
@UsharaniPagadala 

I was looking at this document, and it is sort of like that. Except instead of creating a custom model, I was hoping to learn how to revert the custom model back to default signatures. Do you know how to read in the custom model, and then re-export the model to default?

**Comment by haylie-murray** [comment]
Would it be something like:

read in the custom model
`custom_mod = tf.saved_model.load(path_to_custom_model)`

set the signatures to default
`signatures = {"serving_default": ['serving_default']}`

Save the new model that has default signatures
`tf.saved_model.save(new_model, module_output_path ,signatures=signatures)`

I am looking for something like this? Or if it is possible to revert?

**Comment by UsharaniPagadala** [comment]
@haylie-murray 

This is not Build/Installation or Bug/Performance issue. Please post this kind of questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) or TF [Forum](https://discuss.tensorflow.org/).There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks

**Comment by haylie-murray** [comment]
I posted the question here as well: https://stackoverflow.com/questions/68086885/tf2-how-to-remove-custom-signature-of-savedmodel-and-re-exporting-the-model

**Comment by Saduf2019** [comment]
@haylie-murray 
Please follow [this guide](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export), as this is not a bug or feature request kindly move this to closed status.
