### ISSUE TITLE
image.pad_to_bounding_box throws unexpectedly

### ISSUE THREAD

**Issue by smedegaard** [tensorflow/tensorflow#50415]
I'm trying to add an arbitrary amount of padding to images in a preprocessing Apache Beam pipeline. 

I calculate the amount of padding needed and if it's greater than 0 I call `tf.image.pad_to_bounding_box()` as follows:

```python
if padding > 0:
    try:
        target_height = int(org_height + (2 * padding))
        target_width = int(org_width + (2 * padding))
        image_decoded = tf.image.pad_to_bounding_box(
            image=image_decoded,
            offset_height=padding,
            offset_width=padding,
            target_height=target_height,
            target_width=target_width,
        )
    except Exception as e:
        print("/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/")
        print("padding failed")
        print(
            f"""
        {e}
        org height: {org_height}
        org width: {org_width}

        after padding height: {target_height - padding - org_height}
        after padding width: {target_width - padding - org_width}

        target width: {int(org_width + (2 * padding))}
        target height: {int(org_height + (2 * padding))}

        padding: {padding}
        """
        )
        print("/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/")
```

an example of an unexpected exception looks like this:

```
/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/
padding failed

                        width must be <= target - offset
                        org height: 3744
                        org width: 5616

                        after padding height: 126
                        after padding width: 126

                        target width: 5868
                        target height: 3996

                        padding: 126
                        
/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/
```

Clearly the "after padding width" is greater than 0, so I do not understand why it throws here.

any help is greatly appreciated.

https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/ops/image_ops_impl.py#L1078

**Comment by rmothukuru** [comment]
@smedegaard,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by smedegaard** [comment]
Sorry for the late response. 
The error appeared in a loop. since then I changed the script and I no longer get the error.

Might be due to how Beam iterates over PCollections?

The working code is here: https://gitlab.com/smedegaard/birds_to_tfrecords/-/blob/trunk/src/i2t/transforms/par_dos.py#L78

But it still puzzels me that the error was thrown since I'm printing 
```
 after padding height: 126
 after padding width: 126
```
Those are calculated the same way as in the assert in image_ops_impl.py
