### ISSUE TITLE
Image transformations require Scipy but Scipy already installed

### ISSUE THREAD

**Issue by hernandezurbina** [tensorflow/tensorflow#50413]
Hello, I’m running Tensorflow 2.4.1 on a Windows 10 computer (system info below). I’m having problems trying to launch a CNN model using the ImageDataGenerator feeding from a Pandas dataframe. After defining the data generator and the model, I get the following error when running model.fit: **Image transformations require SciPy. Install SciPy.** However, when I can confirm that Scipy is installed by running “import scipy” without errors.

Image generator is defined as follows:
`
train_datagen = ImageDataGenerator(horizontal_flip=False,
                                   vertical_flip=False,
                                   rescale=1/255.0).flow_from_dataframe(dataframe=X,
                                                                        x_col='image_name',
                                                                        y_col='response',
                                                                        shuffle=False, 
                                                                        directory=src_path,
                                                                        target_size=(128, 128),
                                                                        class_mode=None
                                                                       )
`
The error occurs when running:
`
model.fit(train_datagen, epochs=5)
`

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.5
- CUDA/cuDNN version: 11.3/ 8.2.1
- GPU model and memory: NVIDIA GeForce RTX 2060

**Comment by hernandezurbina** [comment]
PS. I believe the error results from my GPU configuration. I am running a CPU version of the code and training is running (although extremely slow). I had to change my imagegenerator declaration to:
`
class_mode='raw',
`
as I am running a regression model.

**Comment by saikumarchalla** [comment]
@hernandezurbina   Please let is know if you are still facing the issue on GPU. Thanks!

**Comment by hernandezurbina** [comment]
@saikumarchalla On GPU yes. On CPU not.

**Comment by saikumarchalla** [comment]
@hernandezurbina  If possible could you please create a simple reproducible code/colab with the dataset you are using and share with us. Thanks!

**Comment by hernandezurbina** [comment]
@saikumarchalla Dataset is huge (thus, the need to use a image generator) so I am not sure if I can create a colab notebook to reproduce the error. The code that I am running is the following:

`
if tf.test.gpu_device_name():
    print('Default GPU device: {}'.format(tf.test.gpu_device_name()))
else:
    print('You need to install GPU version of TF') 
#returns Default GPU device: /device:GPU:0

X = pd.read_csv('temp_cnn_gpu_data.csv')
X.head()

def createCNN():
    model = Sequential()
    model.add(layers.Conv2D(128, (3, 3), activation='relu', input_shape=(128, 128, 3)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.Flatten())
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1))
    
    optimizer = tf.keras.optimizers.RMSprop(0.001)
    
    model.compile(optimizer=optimizer,
                  loss='mse',
                  metrics=['mae', 'mse'])

    return model

src_path = 'Data - SetA_Final/'

train_datagen = ImageDataGenerator(horizontal_flip=False,
                                   vertical_flip=False,
                                   rescale=1/255.0).flow_from_dataframe(dataframe=X,
                                                                        x_col='image_name',
                                                                        y_col='response_valence',
                                                                        shuffle=False, 
                                                                        directory=src_path,
                                                                        target_size=(128, 128),
                                                                        class_mode='raw',
                                                                        batch_size=32
                                                                       )
#returns Found 455190 validated image filenames.

model = createCNN()
history = model.fit(train_datagen, epochs=2)
`

Now, the error that I am getting today is different than in the previous time. Now, I get a "Epoch 1/2" but then after a few seconds I get a notification from jupyter that the notebook has died and will restart. No other messages appear in the notebook.
Thanks!

**Comment by hernandezurbina** [comment]
@saikumarchalla All sorted now. I look it up elsewhere and it seems that I was running out of memory when running the code in jupyter. Changed everything to a script and it's running fine. :)

**Comment by saikumarchalla** [comment]
@saikumarchalla  Glad to hear that the issue is resolved for you.
