### ISSUE TITLE
Bazel build ERROR with TF2.4 Cuda11.0 Cudnn8 Python3.8 MSVC2019 bazel 3.1.0

### ISSUE THREAD

**Issue by ctrouillefou** [tensorflow/tensorflow#50414]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform : Win10
- TensorFlow installed from (source or binary): TF2.4
- TensorFlow version:TF2.4 and TF-GPU2.4
- Python version: 3.8
- Installed using virtualenv? pip? conda?: no, yes, no
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8
- GPU model and memory: Nvidia GeForce 840M

**Describe the problem**
Bazel does not build my TF
I followed all these information: https://www.tensorflow.org/install/source_windows
And I have this:
tensorflow-2.4.0	python3.8	MSVC 2019	Bazel 3.1.0
tensorflow_gpu-2.4.0	python3.8	MSVC 2019	Bazel 3.1.0	8.0	11.0
I saw people indicating the same problem, but I did not find any solution anywhere.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
using
bazel build //tensorflow/tools/pip_package:build_pip_package
or
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
Give the same result ! Error!

**Any other info / logs**

**ERROR: An error occurred during the fetch of repository 'local_config_cuda':**
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
**ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda':** Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
WARNING: Target pattern parsing failed.
**ERROR: no such package '@local_config_cuda//cuda':** Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
**'C:/Program' is not recognized as an internal or external command,
operable program or batch file.**
INFO: Elapsed time: 2.304s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**FIRST PART OF THE LOG**

C:\tensorflow>**bazel build //tensorflow/tools/pip_package:build_pip_package**
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Program Files/Python38/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Program Files/Python38/python.exe --action_env PYTHON_LIB_PATH=C:/Program Files/Python38/lib/site-packages --python_path=C:/Program Files/Python38/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file c:\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1430:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1400
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 1075, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 606, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "C:/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "C:/tensorflow/third_party/remote_config/common.bzl", line 217, in execute
                fail(<1 more arguments>)
Repository command failed
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.

**OR** with

C:\tensorflow>**bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package**
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Program Files/Python38/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Program Files/Python38/python.exe --action_env PYTHON_LIB_PATH=C:/Program Files/Python38/lib/site-packages --python_path=C:/Program Files/Python38/python.exe --config=xla --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0 --action_env TF_CUDA_COMPUTE_CAPABILITIES=5.0 --config=cuda --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file c:\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:opt in file c:\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file c:\tensorflow\.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file c:\tensorflow\.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  C:/tensorflow/third_party/gpus/cuda_configure.bzl:1430:18: in <toplevel>

**Comment by Saduf2019** [comment]
@ctrouillefou 
Could you please try : ```sudo apt-get purge bazel``` followed by installation of binaries and let us know.
You may also refer to:l[ink](https://github.com/tensorflow/tensorflow/issues/11859), #47042 , [link](https://stackoverflow.com/questions/64650756/bazel-build-error-with-cuda-on-windows-10-how-resolve-it)

**Comment by ctrouillefou** [comment]
Hi,
I can not do "sudo apt-get purge bazel" on Win10; but I installed bazel 4.1.0 and obtained the same result.
The 3 links provided didn't help to solve the problem.

**Comment by ctrouillefou** [comment]
Any idea of what is the problem ?

**Comment by gadagashwini** [comment]
@ctrouillefou,
Try changing Python file path
`
python_path=C:/Program Files/Python3/python.exe -> this to C:/Python3/python.exe`
Check msys64 is  `C:\msys64\usr\bin` mast be present in your PATH variable.
