### ISSUE TITLE
TFlite memory persistence

### ISSUE THREAD

**Issue by Haag-se** [tensorflow/tensorflow#50418]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-lowlatency x86_64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Desktop
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.6.0
- Python version: N/A
- Bazel version (if compiling from source): 4.0.0
- GCC/Compiler version (if compiling from source): GCC 10.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Doing multiple inference runs directly after each other indicates good speed (after the initial warmup run). However, if I add a 5 seconds delay between inference runs, the speed is much worse. My guess is that this has something to do with memory persistence?

No delay between inference runs:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Prediction 1: 105 us
Prediction 2: 32 us
Prediction 3: 26 us
Prediction 4: 23 us
Prediction 5: 25 us
```

5 seconds delay between inference runs:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Prediction 1: 72 us
Prediction 2: 94 us
Prediction 3: 97 us
Prediction 4: 192 us
Prediction 5: 100 us
```

**Describe the expected behavior**
Inference speed should be similar even if there is a few seconds delay between runs.

**Standalone code to reproduce the issue**
```
#include <tensorflow/lite/interpreter.h>
#include <tensorflow/lite/model.h>
#include <tensorflow/lite/kernels/register.h>
#include <iomanip>
#include <iostream>
#include <mutex>
#include <fstream>
#include <chrono>
#include <thread>

std::mutex mtx;

using namespace std;
using namespace std::chrono_literals;
using std::chrono::high_resolution_clock;
using std::chrono::duration_cast;
using std::chrono::duration;
using std::chrono::microseconds;	

tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::FlatBufferModel> model;
std::unique_ptr<tflite::Interpreter> interpreter;

float predict() {
	std::scoped_lock lock{mtx};
	int* input;
	float* output; 
	
	input = interpreter->typed_input_tensor<int>(0);
	
	for (int i=0; i<20; ++i) {
		input[i] = rand()%((25000 - 0) + 1) + 0; 
	}
	
	interpreter->Invoke();
	
	output = interpreter->typed_output_tensor<float>(0);

	return output[0];
}

void init_model(){

	model = tflite::FlatBufferModel::BuildFromFile("/home/gustaf/cprojects/pacific/nlp/sv/model.tflite");

	tflite::InterpreterBuilder(*model, resolver)(&interpreter);

	//interpreter->SetNumThreads(1);

	interpreter->AllocateTensors();
	
	interpreter->Invoke();

}


int main (){
	
	init_model();
	
	int delay = 5;
	
	auto t1 = high_resolution_clock::now();
	predict();
	auto t2 = high_resolution_clock::now();
	
	std::this_thread::sleep_for(std::chrono::seconds(delay));
	
	auto t3 = high_resolution_clock::now();
	predict();
	auto t4 = high_resolution_clock::now();
	
	std::this_thread::sleep_for(std::chrono::seconds(delay));
	
	auto t5 = high_resolution_clock::now();
	predict();
	auto t6 = high_resolution_clock::now();
	
	std::this_thread::sleep_for(std::chrono::seconds(delay));
	
	auto t7 = high_resolution_clock::now();
	predict();
	auto t8 = high_resolution_clock::now();
	
	std::this_thread::sleep_for(std::chrono::seconds(delay));
	
	auto t9 = high_resolution_clock::now();
	predict();
	auto t10 = high_resolution_clock::now();


auto ms1 = duration_cast<microseconds>(t2 - t1);
auto ms2 = duration_cast<microseconds>(t4 - t3);
auto ms3 = duration_cast<microseconds>(t6 - t5);
auto ms4 = duration_cast<microseconds>(t8 - t7);
auto ms5 = duration_cast<microseconds>(t10 - t9);

cout << "Prediction 1: " << ms1.count() << " us" << endl;
cout << "Prediction 2: " << ms2.count() << " us" << endl;
cout << "Prediction 3: " << ms3.count() << " us" << endl;
cout << "Prediction 4: " << ms4.count() << " us" << endl;
cout << "Prediction 5: " << ms5.count() << " us" << endl;

}


```

**Comment by miaout17** [comment]
A few random thoughts. 

It seems the model is tiny. A few hundred us is blazing fast, and the difference might be just noise. Do you have a real use case that's affected by the performance difference? 

Is it possible because the CPU is doing other things in the 5 second wait, so the data is squeeze out of L1/L2 cache? and this doesn't happen if you're invoking the interpreter continuously.

**Comment by Haag-se** [comment]
> A few random thoughts. 
> 
> 
> 
> It seems the model is tiny. A few hundred us is blazing fast, and the difference might be just noise. Do you have a real use case that's affected by the performance difference? 
> 
> 
> 
> Is it possible because the CPU is doing other things in the 5 second wait, so the data is squeeze out of L1/L2 cache? and this doesn't happen if you're invoking the interpreter continuously. 

Making sure that there are no cache misses is a good thought. To test it I've limited the code to run on one core and closed all other processes using the same cpu. The results are the same unfortunately. Speed is degrading fast after the latest invoke. 

The model is tiny by purpose. Latency is extremely important for my use case, event driven high-frequency trading. Cutting a hundred microseconds is a huge improvement!

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
