### ISSUE TITLE
“Cloud TPU” console spam on every TensorFlow import

### ISSUE THREAD

**Issue by jpfarias** [tensorflow/tensorflow#50423]
**System information**

  *  Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
  *  OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
  *  Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
  *  TensorFlow installed from (source or binary): binary
  *  TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
  *  Python version: Python 3.9.5
  *  Bazel version (if compiling from source): N/A
  *  GCC/Compiler version (if compiling from source): N/A
  *  CUDA/cuDNN version: N/A
  *  GPU model and memory: N/A

**Describe the current behavior**

Importing TensorFlow prints an unnecessary and unhelpful warning:

   ` tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.`

**Describe the expected behavior**

Importing TensorFlow should not print any messages about Cloud TPUs.
This is a normal desktop installation that doesn’t have anything to do
with TPUs, and doesn’t need them.

**Code to reproduce the issue**

```
$ python -c "import logging; logging.basicConfig(level=logging.DEBUG); import tensorflow"
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7

```
**Other info / logs**

Likely introduced by 5364121.

The commit that supposedly fixes #35547 doesn't actually fixes the issue but only changes the log level from warning to debug.

It should instead not print any messages on a non TPU environment.

Thanks for your report! It should be fixed starting with the nightly build tomorrow morning (`2.1.0-dev20200104`).

_Originally posted by @frankchn in https://github.com/tensorflow/tensorflow/issues/35547#issuecomment-570694131_

**Comment by UsharaniPagadala** [comment]
@jpfarias 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
Thanks

**Comment by jpfarias** [comment]
> 
> 
> @jpfarias
> 
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
> Thanks

I updated the issue to match the template

**Comment by sahillone** [comment]
```
2022-10-17 10:35:43,879 Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2022-10-17 10:35:44,150 Creating converter from 7 to 5
2022-10-17 10:35:44,151 Creating converter from 5 to 7
2022-10-17 10:35:44,151 Creating converter from 7 to 5
2022-10-17 10:35:44,151 Creating converter from 5 to 7
2022-10-17 10:35:50,048 Creating converter from 3 to 5
```

Got the same message on `Tensorflow 2.9.2`

**Comment by SuryanarayanaY** [comment]
I have replicated the issue with tf-nightly(2.13.0-dev20230313). Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/692f2fdc81e01067abf6bdd203165b70/50423.ipynb).

**Comment by JimCircadian** [comment]
Being experienced as of Tensorflow 2.14.0 😉

**Comment by deepernewbie** [comment]
try the following at the very beginnig of your code

```
import logging
logging.getLogger('h5py').setLevel(logging.WARNING)
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
