### ISSUE TITLE
When you use math symbols instead of tf.math, tensorflow.keras.load_model does not properly load model for stuff like not equal

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tensorflow#50421]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): on mac 10.14.6  but on colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): default colab install
- TensorFlow version (use command below): 2.5 
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I used some stuff such as != or == in code and save graph, I am not able to load the graph
but when I use tf.math I am able too. 
**Describe the expected behavior**
I expect to be able to use that behavior and load the model. 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1gm5DujworX-7X1z01qUToOlzE8qLbfPO?usp=sharing
Please toggle on and off the commented line

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue  in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/a25b0e2b0736c1123f880c65e81a8b82/forgithub.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
As of now Tensorflow does not support those operations directly, adding **==** or **!=** would break lot of code, instead it's  suggested to use Tensorflow symbols like `tf.math.not_equal`.
