### ISSUE TITLE
Add Spresense instructions in README.md files on each examples of lite micro.

### ISSUE THREAD

**Issue by takayoshi-k** [tensorflow/tensorflow#50429]
@tensorflow/micro

**System information**
- Target platform : Sony Spresense

**Describe the problem**
There is no instructions for Sony Spresense board in README.md files of each examples in lite micro.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Nothing. Just README.md file.

**Comment by UsharaniPagadala** [comment]
@takayoshi-k 

Thank you for reporting this issue.It will be closed once the PR is merged.

Thanks
