### ISSUE TITLE
Cannot Compile tensorflow 1.14.0

### ISSUE THREAD

**Issue by zhli12** [tensorflow/tensorflow#50425]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 11.2.3
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
One script I need to use has the line `from tensorflow.examples.tutorials.mnist import input_data`. Since the tutorials folder is removed from tensorflow2, I activated another environment to use Python 3.7 and installed tensorflow 1.14.0 using `pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
` found from [https://stackoverflow.com/questions/63059979/cannot-install-tensorflow-1-x](https://stackoverflow.com/questions/63059979/cannot-install-tensorflow-1-x).

However, when running the script, I have an error saying `ModuleNotFoundError: No module named 'keras_applications', but I do have installed keras.

I found a related issue here [https://github.com/tensorflow/tensorflow/issues/21518](https://github.com/tensorflow/tensorflow/issues/21518) which was posted quite a while ago. Based on this pose, I ran successfully
```
pip install keras_applications==1.0.4 --no-deps
pip install keras_preprocessing==1.0.2 --no-deps
pip install h5py==2.8.0
```
but encountered another error saying `ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`` Below is my traceback.

**Any other info / logs**
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tensorflow.keras.layers.experimental.preprocessing'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2869, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c54fbe678627>", line 1, in <module>
    runfile('/Users/zhli12/Desktop/scGAIN/example.py', wdir='/Users/zhli12/Desktop/scGAIN')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/zh12/Desktop/scGAIN/example.py", line 25, in <module>
    from keras import applications
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by bhack** [comment]
TF 1.x is end of life, please install a recent TF 2.x release. 
For the MINST dataset you can use https://keras.io/api/datasets/mnist/

**Comment by zhli12** [comment]
> TF 1.x is end of life, please install a recent TF 2.x release.
> For the MINST dataset you can use https://keras.io/api/datasets/mnist/

Thanks! Should I replace `from tensorflow.examples.tutorials.mnist import input_data` with `tf.keras.datasets.mnist.load_data(path="mnist.npz")` then?

**Comment by bhack** [comment]
You could use like this https://github.com/tensorflow/tensorflow/issues/32790#issuecomment-594816297

Or 

https://www.tensorflow.org/datasets/keras_example

**Comment by saikumarchalla** [comment]
@zhli12  Also Please check this Tensorflow [tutorial](https://www.tensorflow.org/tutorials/quickstart/beginner) for  more information. Thanks!

**Comment by saikumarchalla** [comment]
@zhli12 Please let us know if you are facing any issues still else go ahead and close the issue.Thanks!

**Comment by zhli12** [comment]
Thanks! I'll switch to tensorflow 2.
