### ISSUE TITLE
Saved Keras model cannot be loaded using hub.KerasLayer API

### ISSUE THREAD

**Issue by bxshi** [tensorflow/tensorflow#50433]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `Yes`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux 8d350c6303d5 5.4.104+ #1 SMP Sat Jun 5 09:50:34 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux`

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `N/A`
- TensorFlow installed from (source or binary): `binary`
- TensorFlow version (use command below): `v2.5.0-0-ga4dfb8d1a71 2.5.0`
- Python version: `sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)`
- Bazel version (if compiling from source):  `N/A`
- GCC/Compiler version (if compiling from source):  `N/A`
- CUDA/cuDNN version:  `N/A`
- GPU model and memory:  `N/A`

**Describe the current behavior**

After creating a simple `tf.keras.Model` with `IntegerLookup`, the model can be saved using `save` API but cannot be load using `hub.KerasLayer` API. It throws the following error:

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-a9c000ccc830> in <module>()
----> 1 loaded_model = hub.KerasLayer('./saved_model')

/usr/local/lib/python3.7/dist-packages/tensorflow_hub/keras_layer.py in __init__(self, handle, trainable, arguments, _sentinel, tags, signature, signature_outputs_as_dict, output_key, output_shape, load_options, **kwargs)
    170 
    171     self._callable = self._get_callable()
--> 172     self._setup_layer(trainable, **kwargs)
    173 
    174   def _setup_layer(self, trainable=False, **kwargs):

/usr/local/lib/python3.7/dist-packages/tensorflow_hub/keras_layer.py in _setup_layer(self, trainable, **kwargs)
    187       for v in self._func.variables:
    188         if id(v) not in trainable_variables:
--> 189           self._add_existing_weight(v, trainable=False)
    190 
    191     # Forward the callable's regularization losses (if any).

/usr/local/lib/python3.7/dist-packages/tensorflow_hub/keras_layer.py in _add_existing_weight(self, weight, trainable)
    201     """Calls add_weight() to register but not create an existing weight."""
    202     if trainable is None: trainable = weight.trainable
--> 203     self.add_weight(name=weight.name, shape=weight.shape, dtype=weight.dtype,
    204                     trainable=trainable, getter=lambda *_, **__: weight)
    205 

AttributeError: 'NoneType' object has no attribute 'name'
```

**Describe the expected behavior**

Based on [Tensorflow's doc](https://www.tensorflow.org/hub/tf2_saved_model#saving_from_keras), the expected behavior is:
> Starting with TensorFlow 2, `tf.keras.Model.save()` and `tf.keras.models.save_model()` default to the SavedModel format (not HDF5). The resulting SavedModels that can be used with `hub.load()`, `hub.KerasLayer` and similar adapters for other high-level APIs as they become available.

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Please find the gist here: https://gist.github.com/bxshi/b0b99c4ed537fd57c05e2b1ef8964c52 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/0b24e7bf30745e4677bfb1df05e56092/reproduce-integerlookup-issue.ipynb). Thanks!

**Comment by bxshi** [comment]
@saikumarchalla link updated, thanks for following up.

**Comment by bxshi** [comment]
@jvishnuvardhan if you can instruct me on how to fix this, I'd be happy to contribute. Thanks!

**Comment by bxshi** [comment]
Hi @jvishnuvardhan and @saikumarchalla, could you please help ping someone from Google and give me some actionable instruction on fixing this? Thank you!

**Comment by RichK0** [comment]
Hi @bxshi. The model must implement the interface specified [here](https://www.tensorflow.org/hub/reusable_saved_models#interface_definition). See [this gist](https://colab.research.google.com/gist/RichK0/7d39eaf2e3dfba50128067f73f0851d0/reproduce-integerlookup-issue.ipynb#scrollTo=2QSLT69MZ-Zb) for an example fix. [Here](https://www.tensorflow.org/guide/saved_model) is some documentation to learn more about Saved Models in TensorFlow.
