### ISSUE TITLE
Android Studio is unable to Load https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

### ISSUE THREAD

**Issue by VirVisha** [tensorflow/tensorflow#50439]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

After cloning the repository https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android when I try to open the project in Android Studio version 4.2, the left window of IDE shows loading but it never loads..

**Comment by tilakrayal** [comment]
@VirVisha ,

In order to expedite the trouble-shooting process, could you please provide the tensorflow version,complete code and dataset or colag gist to reproduce the issue reported here.

**Comment by VirVisha** [comment]
@tilakrayal I am following the instructions mentioned on https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android. 
As mentioned in the link that Android Studio should be 3.2 or more, I am using Android Studio 4.2. Still the repository never gets loaded into Studio, it just waits there with Loading .. prompt in the Left window of the IDE

**Comment by tilakrayal** [comment]
@VirVisha ,

This is not related to TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a larger community that reads questions there. Thanks!

**Comment by VirVisha** [comment]
@tilakrayal I have rectified it, there is a dependency of Android SDK 29 for the repository to be loaded correctly.
