### ISSUE TITLE
JSON error when saving Tensorflow model. 

### ISSUE THREAD

**Issue by PitMilan** [tensorflow/tensorflow#50459]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 x64 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.14.0 gpu
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: GeForce GTX TITAN X

**Describe the current behavior**
When saving the model the following error occurs: typeerror: ('not json serializable:', b'\n\x03add\x12\x03add\x1a\x14dropout_1/cond/merge\x1a\x12dropout/cond/merge*\x07\n\x01t\x12\x020\x01') addition

**Describe the expected behavior**
Saving of the model and continuation to the next epoch.

**Standalone code to reproduce the issue**
The code for the model:
`#!/usr/bin/env python
# coding: utf-8

# In[1]:

import tensorflow
import miscnn
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, concatenate
from tensorflow.keras.layers import Conv3D, MaxPooling3D, Conv3DTranspose
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Conv2DTranspose, SeparableConv2D, DepthwiseConv2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import Concatenate, Add, concatenate
from tensorflow.keras.layers import ReLU
from tensorflow.keras.initializers import glorot_normal, Identity
#from tensorflow.keras.contrib.layers import repeat
#from tensorflow.keras.contrib.framework import Arg_Scope
from tensorflow.keras.regularizers import l2

from miscnn.neural_network.architecture.abstract_architecture import Abstract_Architecture

fc = Dense
conv = Conv2D
deconv = Conv2DTranspose
relu = ReLU
maxpool = MaxPooling2D
dropout_layer = Dropout
batchnorm = BatchNormalization
winit = glorot_normal()
#repeat = repeat
#arg_scope = Aarg_Scope
l2_regularizer = l2

class Architecture(Abstract_Architecture):
    def __init__(self,  n_classes=1, l2=None, is_training=True, upsampling=1):
#         self.input_x = input_x
        self.n_classes = n_classes
        self.l2=None
        self.is_training=True
        self.upsampling=1
    
    def create_model_2D(self, input_shape, n_classes=1, n_labels=1,is_training=True,l2=None,upsampling=1):
        inputs = Input(input_shape) 
    
        x = downsample(inputs, n_filters_in=3, n_filters_out=16, is_training=is_training, l2=l2, name="d1")
        

        x = downsample(x, n_filters_in=16, n_filters_out=64, is_training=is_training, l2=l2, name="d2")
        
        x = encoder_module(x,n_filters=64, is_training=is_training, dilation=[1, 1], l2=l2, name="fres3", dropout=0.0)
        
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres4", dropout=0.0)
        
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres5", dropout=0.0)
        
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres6", dropout=0.0)
        
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres7", dropout=0.0)
        
    
        x = downsample(x,  n_filters_in=64, n_filters_out=128, is_training=is_training, l2=l2, name="d8")
        
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 2], l2=l2, name="fres9", dropout=0.25)
        
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 4], l2=l2, name="fres10", dropout=0.25)
        
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 8], l2=l2, name="fres11", dropout=0.25)
        
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 16], l2=l2, name="fres12", dropout=0.25)
        

        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 1], l2=l2, name="fres13", dropout=0.25)
        
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 2], l2=l2, name="fres14", dropout=0.25)
        
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 8], l2=l2, name="fres15", dropout=0.25)
        
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 16], l2=l2, name="fres16", dropout=0.25)
        
    
        x = upsample(x, n_filters=64, is_training=is_training, l2=l2, name="up17")
        
        x3 = downsample(inputs, n_filters_in=3, n_filters_out=16, is_training=is_training, l2=l2, name="d7")
        
        x3 = downsample(x3, n_filters_in=16, n_filters_out=66, is_training=is_training, l2=l2, name="d7")
        print(x.shape)
        print(x3.shape)
        
        #x = x+x3
        x = Add()([x, x3])

        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres18", dropout=0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres19", dropout=0)
        x = upsample(x, n_filters=1, is_training=is_training, l2=l2, name="up23", last=True)

        #if upsampling > 1:
        x = tensorflow.image.resize(x, size= [128,128], align_corners=True)
        print(x.shape)
        
        x = Conv2D(1, (1, 1), activation='sigmoid')(x)
        
        model = Model(inputs=[inputs], outputs=[x])
        return model

    def create_model_3D(self, input_shape, n_labels=1, is_training=True):
        
        inputs = Input(input_shape)    
        
        x = downsample(inputs, n_filters_in=3, n_filters_out=16, is_training=is_training, l2=l2, name="d1")

        x = downsample(x, n_filters_in=16, n_filters_out=64, is_training=is_training, l2=l2, name="d2")
        x = encoder_module(x,n_filters=64, is_training=is_training, dilation=[1, 1], l2=l2, name="fres3", dropout=0.0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres4", dropout=0.0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres5", dropout=0.0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres6", dropout=0.0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres7", dropout=0.0)
    
        x = downsample(x,  n_filters_in=64, n_filters_out=128, is_training=is_training, l2=l2, name="d8")
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 2], l2=l2, name="fres9", dropout=0.25)
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 4], l2=l2, name="fres10", dropout=0.25)
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 8], l2=l2, name="fres11", dropout=0.25)
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 16], l2=l2, name="fres12", dropout=0.25)

        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 1], l2=l2, name="fres13", dropout=0.25)
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 2], l2=l2, name="fres14", dropout=0.25)
        x = encoder_module_multi(x, n_filters=128,is_training=is_training, dilation=[1, 8], l2=l2, name="fres15", dropout=0.25)
        x = encoder_module_multi(x,n_filters=128, is_training=is_training, dilation=[1, 16], l2=l2, name="fres16", dropout=0.25)
    
        x = upsample(x, n_filters=64, is_training=is_training, l2=l2, name="up17")
        x3 = downsample(input_x, n_filters_in=3, n_filters_out=16, is_training=is_training, l2=l2, name="d7")
        x3 = downsample(x3, n_filters_in=16, n_filters_out=64, is_training=is_training, l2=l2, name="d7")
        #x = x+x3
        x = Add()([x, x3])

        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres18", dropout=0)
        x = encoder_module(x, n_filters=64,is_training=is_training, dilation=[1, 1], l2=l2, name="fres19", dropout=0)
        x = upsample(x, n_filters=n_classes, is_training=is_training, l2=l2, name="up23", last=True)

        if upsampling > 1:
            x = tensorflow.image.resize_bilinear(x, size=[x.shape[1] * upsampling, x.shape[2] * upsampling], align_corners=True)
        
        
        model = Model(inputs=[inputs], outputs=[x])
        return model

def residual_separable(input, n_filters,  is_training=True, dropout=0.3, dilation=1, l2=None, name="down"):
        x = SeparableConv2D(n_filters, (3, 3), strides=1, padding='same', activation='relu', dilation_rate=dilation, use_bias=False, depthwise_initializer=winit, pointwise_initializer=winit, pointwise_regularizer=l2_regularizer(0.00004))(input)
        x = BatchNormalization()(x)
        x = dropout_layer(rate=dropout)(x)
        if input.shape[3] == x.shape[3]:
            x = Add()([x, input])
        return x

def residual_separable_multi(input, n_filters,  is_training, dropout=0.3, dilation=1, l2=None, name="down"):
        input_b = input
        d = DepthwiseConv2D(3, strides=(1, 1), depth_multiplier=1,  activation='relu', padding='same', use_bias=False)
        x = d(input)
        x = BatchNormalization()(x)

        d2= DepthwiseConv2D(3, strides=(1, 1), depth_multiplier=1,  activation='relu', padding='same', use_bias=False)
        d2.dilation_rate = (dilation, dilation)
        x2 = d2(input)
        x2 = BatchNormalization()(x2)

        #x +=x2
        x = Add()([x, x2])

        x = Conv2D(n_filters, 1, strides=1, padding='same', activation='relu', kernel_initializer=winit,
                         dilation_rate=1, use_bias=False, kernel_regularizer=l2_regularizer(0.00004))(x)
        x = BatchNormalization()(x)

        x = dropout_layer(rate=dropout)(x)

        if input.shape[3] == x.shape[3]:
            x = Add()([x, input_b])

        return x

def encoder_module(input, n_filters,  is_training = True, dropout=0.3, dilation=[1,1], l2=None, name="down"):
        x = residual_separable(input, n_filters,  is_training, dropout=dropout, dilation=dilation[0], l2=l2, name=name)
        x = residual_separable(x, n_filters,  is_training, dropout=dropout, dilation=dilation[1], l2=l2, name=name)
        return x

def encoder_module_multi(input, n_filters,  is_training = True, dropout=0.3, dilation=[1,1], l2=None, name="down"):
        x = residual_separable_multi(input, n_filters,  is_training, dropout=dropout, dilation=dilation[0], l2=l2, name=name)
        x = residual_separable_multi(x, n_filters,  is_training, dropout=dropout, dilation=dilation[1], l2=l2, name=name)
        return x

def upsample(x, n_filters, is_training=True, last=False, l2=None, name="down"):
        x = Conv2DTranspose(n_filters, 3, strides=2, padding='same',use_bias=True,
                               kernel_initializer=winit, activation='relu',
                                   kernel_regularizer=l2_regularizer(0.00004))(x)
        if not last:
            x = BatchNormalization()(x)

        return x
    
def upsample2(x, n_filters, is_training=True, last=False, l2=None, name="down"):
        x = Conv2DTranspose(n_filters, 3, strides=4, padding='same',use_bias=True,
                               kernel_initializer=winit, activation='relu',
                                   kernel_regularizer=l2_regularizer(0.00004))(x)
        if not last:
            x = BatchNormalization()(x)

        return x    

def downsample(input, n_filters_in, n_filters_out, is_training=True, bn=False, use_relu=False, l2=None, name="down"):
    
        maxpool_use = n_filters_in < n_filters_out

        if not maxpool_use:
            filters_conv = n_filters_out
        else:
            filters_conv = n_filters_out - n_filters_in

        x = Conv2D(filters_conv, kernel_size = 3,  strides=2, padding='same', activation='relu', kernel_initializer=winit,
                        dilation_rate=1, use_bias=False, kernel_regularizer=l2_regularizer(0.00004))(input)
        if maxpool_use:
            y = MaxPooling2D(pool_size=2, strides=2)(input)
            x = Concatenate(axis=-1)([x, y]) 

        x = BatchNormalization()(x)
#         x = ReLU(x)
        return x`

And the code I'm running:
`#!/usr/bin/env python
# coding: utf-8

# In[7]:

import os
import tensorflow as tf
import keras

import keras.backend.tensorflow_backend

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.40)
session = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
keras.backend.tensorflow_backend.set_session(session)

os.environ["CUDA_VISIBLE_DEVICES"]="1"

os.environ["LD_LIBRABY_PATH"]="/usr/local/cuda-10.2/lib64"

import sys
import miscnn
from miscnn.evaluation import cross_validation
from miscnn.data_loading.interfaces.png_IO import png_IO
#from miscnn.data_loading.interfaces.image_io import Image_interface
from miscnn.neural_network.metrics import dice_soft, dice_coefficient, dice_coefficient_loss
from miscnn.evaluation import split_validation
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
#from tf2cv.model_provider import get_model as tf2cv_get_model
import numpy as np

#os.environ["CUDA_VISIBLE_DEVICES"]="2"

# In[3]:

data_path = "Zip_files/CCA_ICA_Snake"#sys.argv[1]
output_path = "Zip_files/Results/MiniNet_Training_1_MiniNet_GPU_notebook" #sys.argv[2]
fold = 1 #int(sys.argv[3])
# print(fold)
# miscnn_surf(data_path,output_path)

# In[4]:

print('standard')
interface = png_IO( channels=1,classes=1,three_dim=False, im_width=128, im_height=128)
#interface = png_IO(classes=1, img_type="grayscale", img_format="png", pattern=None)
# Create the Data I/O object
data_io = miscnn.Data_IO(interface, data_path,output_path=output_path)
    # Create and configure the Data Augmentation class
data_aug = miscnn.Data_Augmentation(cycles=1, scaling=True, rotations=True,
                                        elastic_deform=True, mirror=True,
                                        brightness=True, contrast=True,
                                        gamma=True, gaussian_noise=True)
        
        # Create and configure the Preprocessor class
pp = miscnn.Preprocessor(data_io, data_aug=data_aug,batch_size=10,analysis="fullimage")

    # Import standard U-Net architecture and Soft Dice
from miscnn.neural_network.architecture.unet.MiniNetMiscnn import Architecture

#model = MiniNet2

# In[5]:

from miscnn.neural_network.metrics import dice_soft_loss
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Input, Dense, Flatten

#import warnings
#warnings.filterwarnings('ignore')

#H =  256;
#W = 256;
#n_classes = 1
#input_xx = Input((H,W,1),name='img')
#input_xx = tf.placeholder(tf.float32,shape=[1,H,W,3], name = 'input')
#training_flag = True
#output_resize_factor = 1
#Mininet = MiniNet2(input_xx, n_classes, is_training=training_flag, upsampling=output_resize_factor)

MiniNet = Architecture(n_classes=1, l2=None, is_training=False, upsampling=2)

# Create a deep learning neural network model with a standard U-Net architecture
model = miscnn.Neural_Network(preprocessor=pp, architecture=MiniNet,
                                 metrics=[dice_soft, dice_coefficient],
                                learninig_rate=0.0001,loss=dice_coefficient_loss)#, gpu_number=1)

sample_list = data_io.get_indiceslist()	

print("done")

# In[8]:

cross_validation(sample_list, model, k_fold=2, epochs=200,
                    iterations=None, evaluation_path=output_path+"evaluation",
                  draw_figures=False, run_detailed_evaluation=False,
                  callbacks=[], save_models=True, return_output=False)

# In[ ]:

#MiniNet

# In[ ]:

#model.model.summary()

# In[ ]:

model.model.save_weights('saved_model_MiniNet/weights')

# In[ ]:

`

Complete error log:
`Epoch 00001: val_loss improved from inf to 0.95021, saving model to Zip_files/Results/MiniNet_Training_1_MiniNet_GPU_notebookevaluation/fold_0/model.hdf5
Traceback (most recent call last):
  File "script_werkend_MiniNet.py", line 105, in <module>
    callbacks=[], save_models=True, return_output=False)
  File "/data/mapit/Data_Joerik/miscnn/evaluation/cross_validation.py", line 84, in cross_validation
    iterations=iterations, callbacks=cb_list)
  File "/data/mapit/Data_Joerik/miscnn/neural_network/model.py", line 269, in evaluate
    max_queue_size=self.batch_queue_size)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 673, in fit
    initial_epoch=initial_epoch)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 969, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 1000, in _save_model
    self.model.save(filepath, overwrite=True)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1211, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 113, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 101, in save_model_to_hdf5
    default=serialization.get_json_type).encode('utf8')
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/mapit/anaconda3/envs/MiniNet/lib/python3.7/site-packages/tensorflow/python/util/serialization.py", line 69, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', b'\n\x15resize/ResizeBilinear\x12\x0eResizeBilinear\x1a\x17conv2d_transpose_1/Relu\x1a\x0bresize/size*\x13\n\ralign_corners\x12\x02(\x01*\x18\n\x12half_pixel_centers\x12\x02(\x00*\x07\n\x01T\x12\x020\x01')
`

**Comment by Saduf2019** [comment]
@PitMilan 
As there is no active support for 1.x, please upgrade to 2.x and let us know if you still face the error.
