### ISSUE TITLE
Tensorflow failed to build with ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading MSVCpackage 'tensorflow/tools/pip_package'  on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [tensorflow/tensorflow#50457]
Hi All,

Tensorflow failed to build with ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in F:/gitp/tensorflow/tensorflow/tensorflow/tensorflow.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/rules_cc.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/default/rules_cc.bzl: in F:/bazeltemp/2powapgf/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors on windows with MSVC. This issue can be reproduced on latest version 32634e9, Could you please look at this issue?

Repro steps:
1. git clone https://github.com/tensorflow/tensorflow F:\gitP\tensorflow\tensorflow
2. git -C "F:\gitP\tensorflow\tensorflow" submodule update --init --recursive
3. Apply tensorflow_set_bazel_version.patch
4. Open a vs2019 x64 command prompt
5. cd F:\gitP\tensorflow\tensorflow
6. pip3 install six numpy wheel
7. pip3 install keras_applications==1.0.6 --no-deps
8. pip3 install keras_preprocessing==1.0.5 --no-deps
9. set PATH=F:\gitP\tensorflow\tensorflow\..\tools;%path%
10. set PATH=F:\gitP\tensorflow\tensorflow\..\tools\msys64\usr\bin;%path%
11. yes "" 2>nul | python ./configure.py
12. set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC
13. set BAZEL_VC_FULL_VERSION=14.29.30037
14. bazel --output_user_root F:\bazelTemp build --config=opt --subcommands //tensorflow/tools/pip_package:build_pip_package

Patch file:
[tensorflow_set_bazel_version.zip](https://github.com/tensorflow/tensorflow/files/6715357/tensorflow_set_bazel_version.zip)

Build log:
[build.log](https://github.com/tensorflow/tensorflow/files/6715358/build.log)

Error info:
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/4b20d65ea59434890477d1f24f4b660fd5a0491f.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
...
ERROR: F:/bazeltemp/2powapgf/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl:28:21: unexpected keyword 'incompatible_use_toolchain_transition', for call to function rule(implementation, test = False, attrs = None, outputs = None, executable = False, output_to_genfiles = False, fragments = [], host_fragments = [], _skylark_testable = False, toolchains = [], doc = '', provides = [], exec_compatible_with = [], analysis_test = False, build_setting = None, cfg = None)
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': in F:/gitp/tensorflow/tensorflow/tensorflow/tensorflow.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/rules_cc.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/default/rules_cc.bzl: in F:/bazeltemp/2powapgf/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': in F:/gitp/tensorflow/tensorflow/tensorflow/tensorflow.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/rules_cc.bzl: in F:/gitp/tensorflow/tensorflow/tensorflow/core/platform/default/rules_cc.bzl: in F:/bazeltemp/2powapgf/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 19.654s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
##[debug] Command #6 exited with code [1].
##[error] Detected error code [1].

**Comment by Saduf2019** [comment]
@spacelg 
Can you please confirm the bazel version used and roll back to a lower version and see if you are facing the issue, also please verify your system requirements and cuda if you are using from the tensorflow official page.

**Comment by spacelg** [comment]
@Saduf2019 
Thanks for your reply and info. The bazel version currently we use is 2.0.0, We try to modify configure.py to change the bazel version to the latest 4.0.0, Re-build still failed the same as above. 

We regularly update the commit of the open source. This time we encountered this problem after updating the commit of Tensorflow. The old Tensorflow commit(458bb34) before this, we can build successfully. 

The cuda version we use is 10.1 as below.
F:\gitP\tensorflow\tensorflow>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243

Did our lower version of cuda cause this problem? What is the minimum cuda version to meet the build success?

Thanks,
Lin

**Comment by spacelg** [comment]
@Saduf2019 
Please ignore the comments above, re-downloaded bazel version 3.7.2, and it has been able to build. I will close this ticket. Thanks again for your help.

Thanks,
Lin
