### ISSUE TITLE
api_docs tensor incoherent sentence

### ISSUE THREAD

**Issue by Jahnvi13** [tensorflow/tensorflow#50452]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/Tensor 

## Description of issue (what needs changing):
The first code snippet in the URL is coming in between the sentence which makes it incoherent.

### Submit a pull request?

I am new to open-source and wish to fix it myself. Can you please direct me to the file wherein the "view aliases" and "code snippets" are included. In the definition given in https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/framework/ops.py#L264 would removing the newline character after first line in multiline comment solve the issue?

**Comment by saikumarchalla** [comment]
@Jahnvi13 Removing the newline character after first line in multiline comment will not resolve the issue here since the changes need to be done in different element/section. Thanks!

**Comment by ymodak** [comment]
I am having a difficulty in understanding your query here. Can you please elaborate further, perhaps using screenshots to visualize better? Thanks!
