### ISSUE TITLE
Why the output tensor device type is GPU even though I set the HostMemory attr?

### ISSUE THREAD

**Issue by Young768** [tensorflow/tensorflow#50461]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: A100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi folks,
I am trying to create an Op recently. This is part of my Op kernel builder:
```
REGISTER_KERNEL_BUILDER(Name("Test").Device(::tensorflow::DEVICE_GPU)
                                                      .HostMemory("output"),
                        TestOp);

REGISTER_OP("Test")
    .Input("tensor: T")
    .Output("output: T")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      ::tensorflow::shape_inference::ShapeHandle output;
      TF_RETURN_IF_ERROR(c->ReplaceDim(c->input(0), 0, c->UnknownDim(), &output));
      c->set_output(0, output);
      return ::tensorflow::Status::OK();
    })
```
For my Op, it's expected the input is on the device while the output will be on the host. Inside the op_kernel, I used api ```cuPointerGetAttribute``` provided by NVIDIA to verify that the output memory is allocated on the host. However, after I call Op using Python and obtain the ```output``` tensor, I tried to print the device type ```print(output.device)```. I found that the output tensor is on the ```GPU```, which is supposed to be ```CPU``` for my case? I tried the scope ```with tf.device("/gpu:0")``` and ```with tf.device("/cpu:0"), but there was no difference

I also tried to set the attribute manually inside the Op_kernel.
```
::tensorflow::AllocatorAttributes alloc_attrs;
alloc_attrs.set_on_host(true);
OP_REQUIRES_OK_ASYNC(context, context->allocate_output(0, result_shape, &output), done);
```
But the result ```print(output.device)``` from Python is still on the device(GPU). 

I am concerned that TF do the Host2Device memory copy automatically.

So I wrote another DataPtr Op which reads the output from the above TestOp, and tried to print the memory address:

```
class DataPtrOp : public ::tensorflow::OpKernel {
    public:
    explicit DataPtrOp(::tensorflow::OpKernelConstruction* context) : OpKernel(context) {}

    void Compute(::tensorflow::OpKernelContext* context) override {
        // Grab the input tensor

        auto input_tensor = context->input(0);
        auto input = std::make_shared<TFTensor>(input_tensor, GetDeviceID(context));
        std::size_t address = reinterpret_cast<std::size_t>(input->data());
        std::cout << "Test. address:" << address << std::endl;
        // 
       //skip some unrelated code here
       ///
    }
    };


REGISTER_KERNEL_BUILDER(Name("DataPtr").Device(::tensorflow::DEVICE_CPU),
                        DataPtrOp);

REGISTER_OP("DataPtr")
        .Attr("T: {uint8, int8, uint16, int16, int32, int64, float16, float32, float64, bool}")  // 
        .Input("input: T")  // Tensor
        .Output("output: uint64")  // scalar
        .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        c->set_output(0, {}); // scalar
        return ::tensorflow::Status::OK();
        });

```

The output tensor memory address from TestOp on the host is the same as the input tensor memory address from DataPtr Op.

So I believe that the ```output``` tensor is allocated on the Host. So, is this a bug or issue with ```tensor.device``` API?
It is very confusing somehow.

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by szutenberg** [comment]
AFAIK for each device, we have host and device memory. In the Compute method, you should be also able to read tensor content (if it's on the host memory). 

It does not look like a bug.

**Comment by Young768** [comment]
@szutenberg yep I did verify that the output is on the Host. The issue is that I call the op using Python and and use TF python API to ```print(output.device)```, the result is ```GPU```. This is very confusing because the data is actually on CPU but the ```device``` API tells user the tensor device type is ```GPU```. You know, our user usually use python API, which, however does not provide the expected answer.

**Comment by UsharaniPagadala** [comment]
@Young768 

Could you please refer this [comment](https://github.com/tensorflow/tensorflow/issues/34071#issuecomment-592585783), hope it helps.Thanks

**Comment by Young768** [comment]
@UsharaniPagadala Hi thanks. It seems it is different from my case? 

For my case, the ```output``` tensor is expected on the ```CPU```, but the ```device``` API tells user it is ```GPU```.

I didnt do the ```tf.identity``` intentionally.

**Comment by UsharaniPagadala** [comment]
@Young768 

Could you please provide a colab gist with required dependencies to analyse the issue reported .Thanks
