### ISSUE TITLE
Blocking on webgl for first initialization

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tensorflow#50460]
On the first run of model using webgl backend it takes very long time. I understand that internally it has to set up the gpu but the method blocks and takes a long time(I see this with predict/execute and execute async.) Is this the expected behavior? What is the recommended behavior and any tips on speeding this up? Should we run in webworker? I have about six models I need to initialize. Is there a way to run them all at once?

**Comment by tilakrayal** [comment]
@rohanmuplara ,

In order to expedite the trouble-shooting process, could you please provide the tensorflow version,complete code and dataset to reproduce the issue reported here.

**Comment by rohanmuplara** [comment]
Sure I am not surer if a dataset is necessary. This is just inference. Tensorflow version is all of them especially latest one. I have found this to be true of any model

**Comment by tilakrayal** [comment]
@rohanmuplara ,

Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.

Thanks!
