### ISSUE TITLE
Softmax layer unexpected and confusing error message

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#50467]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the current behavior**
I am getting a strange error message for the following model. The error seems to originate from the softmax layer at the end. 
The message is the following:
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 2 and 4 for '{{node Sof43628/add/add}} = AddV2[T=DT_DOUBLE](Placeholder, Sof43628/mul)' with input shapes: [?,4,2,1], [?,4,2]."
The error is unexpected since I think the model should work and it is confusing since in the softmax layer there is no requirement for matching dimensions. What could be the reason for this error?

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
in0Mas92349 = tf.keras.layers.Input(shape=([4, 2, 1]))
in0Dep9315 = tf.keras.layers.Input(shape=([1, 2, 1]))
in0Ave93999 = tf.keras.layers.Input(shape=([2, 1]))
Mas92349 = keras.layers.Masking(mask_value=1, name = 'Mas92349', )(in0Mas92349)
Dep9315 = keras.layers.DepthwiseConv2D((1, 2),strides=(1, 1), padding='same', name = 'Dep9315', )(in0Dep9315)
Zer31495 = keras.layers.ZeroPadding2D(padding=((3, 0), (0, 0)), name = 'Zer31495', )(Dep9315)
Max17507 = keras.layers.Maximum(name = 'Max17507', )([Mas92349,Zer31495])
Ave93999 = keras.layers.AveragePooling1D(pool_size=(2), name = 'Ave93999', )(in0Ave93999)
Res89 = keras.layers.Reshape((1, 1, 1), name = 'Res89', )(Ave93999)
Zer84427 = keras.layers.ZeroPadding2D(padding=((3, 0), (1, 0)), name = 'Zer84427', )(Res89)
Sub42930 = keras.layers.Subtract(name = 'Sub42930', )([Max17507,Zer84427])
Sof43628 = keras.layers.Softmax(axis=1, name = 'Sof43628', )(Sub42930)
model = tf.keras.models.Model(inputs=[in0Mas92349,in0Dep9315,in0Ave93999], outputs=Sof43628)

in0Mas92349 = tf.constant([[[[1.8457], [1.4313]], [[1.8795], [1.1303]], [[1.4792], [1.9199]], [[1.996], [1.583]]]])
in0Dep9315 = tf.constant([[[[0.6111], [0.9861]]]])
in0Ave93999 = tf.constant([[[1.1779], [1.8115]]])
print (np.array2string(model.predict([in0Mas92349,in0Dep9315,in0Ave93999],steps=1), separator=', '))
```

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/66cbfa79b54960067d9d48350a535363/untitled121.ipynb) .Thanks

**Comment by Saduf2019** [comment]
@rschumi0 
Can you please refer to similar issues and let is know if it helps: [link](https://github.com/keras-team/keras/issues/11495), [link1](https://github.com/tensorflow/models/issues/8908),[link2](https://stackoverflow.com/questions/64404009/keras-valueerror-dimensions-must-be-equal-but-are-9-and-400-for-node-equal),[link2](https://stackoverflow.com/questions/55411222/tensorflow-error-dimensions-must-be-equal/55412026).

**Comment by szutenberg** [comment]
Hi @rschumi0 ,

Please have a look at [tf.keras.layers.Masking docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Masking).

I think that the error message may be confusing so I pushed PR #50586 .

**Comment by Saduf2019** [comment]
Moving this to closed status due to lack of activity.
