### ISSUE TITLE
I face same problem when I build VGG

### ISSUE THREAD

**Issue by ZephyRUXS** [tensorflow/tensorflow#50476]
`import numpy as np
import tensorflow as tf
from PIL import Image
from tensorflow.keras import Model,Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Dropout,BatchNormalization
from sklearn.model_selection import train_test_split
from keras_preprocessing.image import ImageDataGenerator
from PIL import Image
import os.path
import glob
import random

image_path=glob.glob('gar/*/*.jpg')

label_type=[image_p.split('\\')[1] for image_p in image_path]
labels=np.unique(label_type)

index_to_label=dict((l,n)for l,n in enumerate(labels))
label_to_index=dict((n,l)for l,n in index_to_label.items())

all_labels=[label_to_index.get(name)for name in label_type]

np.random.seed(22)
random_index=np.random.permutation(len(image_path))

path=np.array(image_path)[random_index]
signal_label=np.array(all_labels)[random_index]

sep=int(len(image_path)*0.7)
train_image_path=image_path[:sep]
train_y=all_labels[:sep]
test_image_path=image_path[sep:]
test_y=all_labels[sep:]

train=tf.data.Dataset.from_tensor_slices((train_image_path,train_y))
test=tf.data.Dataset.from_tensor_slices((test_image_path,test_y))

def load_pic(path,label):
    image=tf.io.read_file(path)
    image=tf.image.decode_jpeg(image,channels=3)
    image=tf.image.resize(image,[256,256])
    image=tf.cast(image,tf.float32)
    image=image/255
    return image,label
train=train.map(load_pic)

train=train.shuffle(1000).batch(64)

def get_model():
    gmodel=Sequential([
    Conv2D(64, kernel_size=[3, 3], padding="same", activation=tf.nn.relu,input_shape=(256,256,3)),
    Conv2D(64, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    MaxPooling2D(pool_size=[2, 2], strides=2, padding='same'),

    # Conv-Conv-Pooling单元2,输出通道提升至128，高宽大小减半
    Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    Conv2D(128, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    # 高宽减半
    MaxPooling2D(pool_size=[2, 2], strides=2, padding='same'),

    # Conv-Conv-Pooling单元3,输出通道提升至256，高宽大小减半
    Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    Conv2D(256, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    MaxPooling2D(pool_size=[2, 2], strides=2, padding='same'),

    # Conv-Conv-Pooling单元4,输出通道提升至512，高宽大小减半
    Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    MaxPooling2D(pool_size=[2, 2], strides=2, padding='same'),

    # Conv-Conv-Pooling单元5,输出通道提升至512，高宽大小减半
    Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    Conv2D(512, kernel_size=[3, 3], padding="same", activation=tf.nn.relu),
    MaxPooling2D(pool_size=[2, 2], strides=2, padding='same'),
    Dense(4)
    ])

    return gmodel
model=get_model()
# model.summary()

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.005),
    loss=tf.keras.losses.sparse_categorical_crossentropy,
    metrics=['acc']
)
history=model.fit(train,epochs=10,validation_data=test)`

The problem show that
 tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [64,1] vs. [64,8,8]

**Comment by 777ki** [comment]
"Incompatible shapes: [64,1] vs. [64,8,8]", it's looks like some ops in your graph with Incompatible shapes, your can print the shapes of key ops with binary search , that is a easy way to debug and solve your problem

**Comment by 8bitmp3** [comment]
You may also be able to get feedback at https://discuss.tensorflow.org/ 👍

**Comment by Saduf2019** [comment]
@777ki 
Please refer to similar issues here:l[ink](https://stackoverflow.com/questions/42822844/tensorflow-incompatible-shapes-100-155-vs-128-155-when-combining-cnn-and),[link1](https://github.com/keras-team/keras/issues/11749#issuecomment-804620973).

Kindly create an issue on tensorflow discussion forum for any further queries.


So just change the training batch size to 2 from 8
