### ISSUE TITLE
Error in .summary() on .pb model imported using 'tf.saved_model.load()'

### ISSUE THREAD

**Issue by Patrickbro13** [tensorflow/tensorflow#50470]
I was trying to load .pb model which was saved in "20180402-114759/" directory .
model can be found [here]( https://github.com/davidsandberg/facenet) under the section "pretrained model" .
So I just tried to check the summary with .summary() method but got an error .

Code : 
```
import tensorflow as tf
model_path = "20180402-114759/"
model = tf.saved_model.load(model_path)
print(model.summary())

```

Error :
```
Traceback (most recent call last):
  File "E:\Pathik\KJ\internships\Facial Expression recognition\20180402-114759\test.py", line 7, in <module>
    print(model.summary())
AttributeError: 'AutoTrackable' object has no attribute 'summary'

```
System information :
* OS Platform and Distribution : Windows 10
* TensorFlow version : 2.3.0
* Python version: 3.7.8

How to resolve this error ?

**Comment by jvishnuvardhan** [comment]
@Patrickbro13 `model.summary` method is available for `keras` models only. As your model is a TF model,  it is throwing an error. Try saving the model as a keras model and then use `model.summary`. Thanks!
