### ISSUE TITLE
TensorFlow Lite no consistency between C++ and C library names

### ISSUE THREAD

**Issue by distlibs** [tensorflow/tensorflow#50478]
Question related with TensorFlow Lite. Library for C API is named `tensorflowlite_c`. Library for C++ API `tensorflow-lite`. What the logic behind? I think consistency should be between library names. For example:
1. `tensorflow-lite-c` and `tensorflow-lite`.
2. `tensorflow_lite_c` and `tensorflow_lite`.
3. `tensorflowlite_c` and `tensorflowlite`.

**Comment by mohantym** [comment]
Hi @distlibs !
We are checking to see whether you still need help in this issue .
For 2.10 /2.11 version, you can use below document to use C wheel(  It builds a static library called 

 "libtensorflowlite_c .so "

[Ref](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/BUILD#:~:text=%23%20%20%20%2D%20Linux/Android%3A%20%60libtensorflowlite_c.so%60)

For C++ side, I see documentation on CMake for microcontroller which builds a static file  .

"libtensorflowlite.a"

[Ref ](https://www.tensorflow.org/lite/guide/build_cmake#:~:text=libtensorflow%2Dlite.a).

Does this  resolve your query now?

Thank you!
