### ISSUE TITLE
About the k210 from tflite to kmodel

### ISSUE THREAD

**Issue by KuoEuran** [tensorflow/tensorflow#50471]
System information :

OS Platform and Distribution : Windows 10
TensorFlow version : tf-nightly 2.6.0 
Python version: 3.8

Hi,
    I have converted my darknet weights to pb, and converted to tflite. Howerver, when I converted my tflite file to kmodel on nncase, it has the error message Fatal: inputs are not compatible to concat. 
    And I found that 
![image](https://user-images.githubusercontent.com/70742122/123503360-31d57800-d685-11eb-88bc-a60418ca6327.png) when I converted pb to tflite, and it has the tflite file, but I don't know whether the int8 conversion is fine? The original tflite also has the error message.
Below is my yolov4-tiny-int8.tflite on Netron
![image](https://user-images.githubusercontent.com/70742122/123503463-bde79f80-d685-11eb-96e6-c2fccd817c1a.png)

Does any one know the solution or give me some advice about the error?
Thanks.

**Comment by ymodak** [comment]
Perhaps https://github.com/kendryte/nncase/issues can be the right place for this issue since your question is related to converting tflite to kmodel on nncase. Thanks!
