### ISSUE TITLE
[API docs] `tf.keras.Sequential.predict_classes` is deprecated

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#50473]
https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#predict_classes

`tf.keras.Sequential.predict_classes` is deprecated - there should be a "deprecated" sign, similar to `Model.predict_generator`'s API doc:

[`/sequential.py`](https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/engine/sequential.py#L441-L468):
```
    warnings.warn('`model.predict_classes()` is deprecated and '
                  'will be removed after 2021-01-01. '
                  'Please use instead:'
                  '* `np.argmax(model.predict(x), axis=-1)`, '
                  '  if your model does multi-class classification '
                  '  (e.g. if it uses a `softmax` last-layer activation).'
                  '* `(model.predict(x) > 0.5).astype("int32")`, '
                  '  if your model does binary classification '
                  '  (e.g. if it uses a `sigmoid` last-layer activation).')
```

![image](https://user-images.githubusercontent.com/19637339/123527506-2e1f1100-d6d8-11eb-96d9-50e0e6a83b5d.png)

cc @lamberta @MarkDaoust

**Comment by MarkDaoust** [comment]
It looks like there are a few like this that are deprecated, but incompletely marked. 

Usually we use the `@deprecation.deprecated` decorator, it marks things in  a  way that the doc generator understands.

At minimum these should have a `Caution:` or `Warning:` in the description so you can't miss it (the decorator adds those).

I think the `set_deprecated/is_deprecated` functions in "tensorflow_docs/../api_generator/doc_controls.py" only affect the listings in the TOC, not within the page.

**Comment by rthadur** [comment]
I see this has been removed here https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#predict_classes , so we can close this request. Thank you
