### ISSUE TITLE
int8 conversion error "num_input_elements != num_output_elements" using TensorFlow 1.15

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#50480]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 1.15.0; 2.3.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

####Paste your code here or provide a link to a custom end-to-end colab
I followed *post-training quantization)[https://www.tensorflow.org/lite/performance/post_training_quantization] to convert my pb file to an int8 tf lite model in TensorFlow 1.15.0. But I meet an error: 
**num_input_elements != num_output_elements (32400 != 874800)Node number 81 (RESHAPE) failed to prepare.**

##### conversion code
```
    converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        "model.pb", 
        ["input_tensor"], 
        ["final_output"], 
        input_shapes=input_shape
        )
    converter.allow_custom_ops = True

    converter.optimizations = [tf.lite.Optimize.DEFAULT] # require representative dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8 
    converter.inference_output_type = tf.int8 

    # necessary for calibartion
    converter.representative_dataset = representative_data_gen
    tflite_int8_model = converter.convert()
  
    with open(os.path.join(model_root_dir, "convertedTFLite/int8_default.lite"), "wb") as f:
        f.write(tflite_int8_model)
```

##### representative dataset
```
def preprocess_image(src_image, input_tensor_size):
    output_image = src_image[:, :, (2, 1, 0)] # cvtColor
    output_image = cv2.resize(
        output_image,
        dsize=(input_tensor_size[0], input_tensor_size[1]),
        interpolation=cv2.INTER_LINEAR
    )
    output_image = output_image.astype('float32') / 255.0
    img_mean = np.array([0.5, 0.5, 0.5].reshape((1, 1, len([0.5, 0.5, 0.5])))
    img_std = np.array([0.5, 0.5, 0.5]).reshape((1, 1, len([0.5, 0.5, 0.5])))
    output_image -= img_mean
    output_image /= img_std
    
    return output_image
```

```
def representative_data_gen(): 
    DATASET_DIR = "train_image"
    GT_DIR = "classID"
    
    train_images = glob.glob(os.path.join(DATASET_DIR, "*.png"))
    
    counter = 0
    input_tensor_size = [int(360), int(360)]
    
    for image_path in train_images:
        if os.path.exists(image_path):
            print(str(counter) + " / " + str(len(train_images)) + ": " + image_path)
            input_image = cv2.imread(image_path)
            preprocessed_image = preprocess_image(input_image, input_tensor_size)
            image_in = preprocessed_image[np.newaxis, ...].astype(np.float32)
            counter +=1
            yield [image_in.astype(np.float32)]

        else:
            continue
```

### 3. Failure after conversion
When I convert the pb file to TFLite int8 model with TensorFlow 1.15.0, the process failed with the following error message:

```
RuntimeError: tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (32400 != 874800)Node number 81 (RESHAPE) failed to prepare.
tensorflow/lite/kernels/reshape.cc:66 num_input_elements != num_output_elements (32400 != 874800)Node number 81 (RESHAPE) failed to prepare.
```

For comparison, I converted the pb model to fp16 and uint8 precision without representative dataset, and the models were successfully converted. I tried to switch to TensorFlow 2.3.0 and convert the pb model to int8 precision with representative dataset, and the model was successfully converted. 
As a result, the error only happens when converting with TensorFlow 1.15.0. 
Is there any method to solve this error?

The attachment contains the pb file and the images for representative dataset.
[model_dataset.tar.gz](https://github.com/tensorflow/tensorflow/files/6722569/model_dataset.tar.gz)

Best regards,
Rahn

**Comment by thaink** [comment]
Can you try to convert and run the TFLite model with the current TF version?

**Comment by Rahn80643** [comment]
Hi, 
Which TF version should be tested? Do you mean TensorFlow 2.5?
I converted and ran the TFLite model with TensorFlow 2.3.0, the model could be converted successfully and produced detection results. However, the error mentioned above only occurs when using TensorFlow 1.15.

**Comment by thaink** [comment]
Right. Our latest version is 2.5.0. We no longer maintain 1.15 branch except for critical security bugs.

**Comment by Rahn80643** [comment]
Thank you for the information, I'll convert my model based on TensorFlow 2.5.0 instead of 1.15.
