### ISSUE TITLE
Label_image demo always gives same outputs 

### ISSUE THREAD

**Issue by ardtrkc** [tensorflow/tensorflow#50486]
@tensorflow/micro

Hi all !

While testing our models with basic [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image) example, we faced with strange results.

We tried _label_image_ with 2 different YOLO models with their corresponding label.txt. However regardless the input images and labels, the test output is always in the same order as [2 3 0 1]. Finally we also gave the Grace Hopper image from official source and still we faced with same issue. You can see the outputs in the image below.

Normally our models are working smoothly on PC. But, it is important for us to test them in our iMX6 device with this basic sample. Do you have any idea or solution about this problem ?
Thank you in advance.

![image](https://user-images.githubusercontent.com/56031118/123631875-8b6dac00-d817-11eb-8ba0-17047e522da4.png)

**Comment by saikumarchalla** [comment]
@ardtrkc  Could you please submit a new issue [here](https://github.com/tensorflow/tflite-micro/issues/new) since all micro related issues are handled separately.Thanks!
