### ISSUE TITLE
Wrong access modifiers in tf::ResourceHandle

### ISSUE THREAD

**Issue by mergian** [tensorflow/tensorflow#50481]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): all
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.1
- GPU model and memory: all

**Describe the current behavior**
During implementing an TensorFlow extension I stumbled upon this code line: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_handle.h#L99

I assume it should be ```private``` instead of ```public```.

**Describe the expected behavior**
Class probably should prevent direct access to class members.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
N/A

**Other info / logs**
N/A

**Comment by Saduf2019** [comment]
Moving this issue to closed status as pr is merged.
