### ISSUE TITLE
tf dataset builder issues

### ISSUE THREAD

**Issue by riyaj8888** [tensorflow/tensorflow#50482]
config = tfds.download.DownloadConfig(verify_ssl=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'verify_ssl'
>>> config = tfds.download.DownloadConfig()
>>> builder.download_and_prepare(download_config=config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 262, in download_and_prepare
    download_config=download_config)
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 662, in _make_download_manager
    register_checksums=download_config.register_checksums,
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 177, in __init__
    self._sizes_checksums = checksums.get_all_sizes_checksums()
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 129, in get_all_sizes_checksums
    data = _get_sizes_checksums(path)
  File "/home/ubuntu/anaconda3/envs/test_gpu/lib/python3.7/site-packages/tensorflow_datasets/core/download/checksums.py", line 119, in _get_sizes_checksums
    url, size, checksum = line.rsplit(' ', 2)
ValueError: not enough values to unpack (expected 3, got 1)

i am getting this error after trying to build dataset config file.

> # Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
_tflow_select             2.1.0                       gpu    anaconda
absl-py                   0.13.0           py37h06a4308_0
aiohttp                   3.6.3            py37h7b6447c_0    anaconda
astor                     0.8.1                    py37_0    anaconda
astunparse                1.6.3                      py_0    anaconda
async-timeout             3.0.1                    py37_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl    anaconda
blinker                   1.4                      py37_0    anaconda
brotlipy                  0.7.0           py37h7b6447c_1000    anaconda
c-ares                    1.17.1               h27cfd23_0
ca-certificates           2020.10.14                    0    anaconda
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.1.1                      py_0    anaconda
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37he30daa8_0    anaconda
chardet                   3.0.4                 py37_1003    anaconda
click                     7.1.2                      py_0    anaconda
coverage                  5.3              py37h7b6447c_0    anaconda
cryptography              3.1.1            py37h1ba5d50_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
cupti                     10.1.168                      0    anaconda
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
dm-tree                   0.1.6                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
future                    0.18.2                   py37_1    anaconda
gast                      0.4.0                      py_0    anaconda
gin-config                0.4.0                    pypi_0    pypi
google-api-core           1.30.0                   pypi_0    pypi
google-api-python-client  2.10.0                   pypi_0    pypi
google-auth               1.32.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.4.1                      py_2    anaconda
google-cloud-bigquery     2.20.0                   pypi_0    pypi
google-cloud-core         1.7.1                    pypi_0    pypi
google-crc32c             1.1.2                    pypi_0    pypi
google-pasta              0.2.0                      py_0    anaconda
google-resumable-media    1.3.1                    pypi_0    pypi
googleapis-common-protos  1.53.0                   pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.6               hb1b8bf9_0    anaconda
httplib2                  0.19.1                   pypi_0    pypi
idna                      2.10                       py_0    anaconda
importlib-metadata        2.0.0                      py_1    anaconda
importlib-resources       5.2.0                    pypi_0    pypi
intel-openmp              2020.2                      254    anaconda
ipython                   7.25.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
kaggle                    1.5.12                   pypi_0    pypi
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libgomp                   9.3.0               h5101ec6_17
libprotobuf               3.14.0               h8c45485_0
libstdcxx-ng              9.3.0               hd4cf53a_17
markdown                  3.3.2                    py37_0    anaconda
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mediapy                   1.0.2                    pypi_0    pypi
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
multidict                 4.7.6            py37h7b6447c_1    anaconda
ncurses                   6.2                  he6710b0_1
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.19.1           py37hfa32c7d_0    anaconda
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.1.0                      py_0    anaconda
opencv-python-headless    4.5.2.54                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0
opt-einsum                3.3.0                    pypi_0    pypi
opt_einsum                3.1.0                      py_0    anaconda
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.5                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.2           py37h06a4308_0
portalocker               2.0.0                    pypi_0    pypi
promise                   2.3                      py37_0    anaconda
prompt-toolkit            3.0.19                   pypi_0    pypi
proto-plus                1.18.1                   pypi_0    pypi
protobuf                  3.14.0           py37h2531618_1
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    anaconda
pyasn1-modules            0.2.8                      py_0    anaconda
pycocotools               2.0.2                    pypi_0    pypi
pycparser                 2.20                       py_2    anaconda
pygments                  2.9.0                    pypi_0    pypi
pyjwt                     1.7.1                    py37_0    anaconda
pyopenssl                 19.1.0                     py_1    anaconda
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    py37_1    anaconda
python                    3.7.10               h12debd9_4
python-dateutil           2.8.1                    pypi_0    pypi
python-flatbuffers        1.12               pyhd3eb1b0_0
python-slugify            5.0.2                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0
requests                  2.24.0                     py_0    anaconda
requests-oauthlib         1.3.0                      py_0    anaconda
rsa                       4.6                        py_0    anaconda
sacrebleu                 1.5.1                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.2            py37h91f5cce_0
sentencepiece             0.1.96                   pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0
six                       1.15.0                     py_0    anaconda
sqlite                    3.36.0               hc218d9a_0
tensorboard               2.5.0                      py_0
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0                      py_0    anaconda
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-addons         0.13.0                   pypi_0    pypi
tensorflow-base           2.4.1           gpu_py37h29c2da4_0
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.5.0              pyh7b7c402_0
tensorflow-gpu            2.4.1                h30adc30_0
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-metadata       1.1.0                    pypi_0    pypi
tensorflow-model-optimization 0.6.0                    pypi_0    pypi
termcolor                 1.1.0                    py37_1    anaconda
text-unidecode            1.3                      pypi_0    pypi
tf-models-official        2.5.0                    pypi_0    pypi
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0
tqdm                      4.61.1                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typeguard                 2.12.1                   pypi_0    pypi
typing_extensions         3.7.4.3                    py_0    anaconda
uritemplate               3.0.1                    pypi_0    pypi
urllib3                   1.25.11                    py_0    anaconda
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1                      py_0    anaconda
wheel                     0.36.2             pyhd3eb1b0_0
wrapt                     1.12.1           py37h7b6447c_1    anaconda
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0    anaconda
yarl                      1.6.2            py37h7b6447c_0    anaconda
zipp                      3.3.1                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3

**Comment by saikumarchalla** [comment]
@riyaj8888  Please upgrade you  tfds version to 4.3.0 and it will work.  Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/d9d06346416670be0ff3f2cbc7e56543/untitled103.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
@riyaj8888  Is the issue resolved for you?

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
