### ISSUE TITLE
Getting error while performing one hot encoding

### ISSUE THREAD

**Issue by Nehap-27** [tensorflow/tensorflow#50494]
MemoryError                               Traceback (most recent call last)
<ipython-input-333-6e9121367701> in <module>
      1 ## categorical processing
      2 
----> 3 df_cat_dum = pd.get_dummies(df_cat)

~\anaconda3\lib\site-packages\pandas\core\reshape\reshape.py in get_dummies(data, prefix, prefix_sep, dummy_na, columns, sparse, drop_first, dtype)
    887         for (col, pre, sep) in zip(data_to_encode.items(), prefix, prefix_sep):
    888             # col is (column_name, column), use just column data here
--> 889             dummy = _get_dummies_1d(
    890                 col[1],
    891                 prefix=pre,

~\anaconda3\lib\site-packages\pandas\core\reshape\reshape.py in _get_dummies_1d(data, prefix, prefix_sep, dummy_na, sparse, drop_first, dtype)
   1003 
   1004     else:
-> 1005         dummy_mat = np.eye(number_of_cols, dtype=dtype).take(codes, axis=0)
   1006 
   1007         if not dummy_na:

MemoryError: Unable to allocate 654. MiB for an array with shape (26187, 26187) and data type uint8

**Comment by UsharaniPagadala** [comment]
@Nehap-27 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Looking at the error log it is similar to the issues: [#39442](https://github.com/tensorflow/tensorflow/issues/39442), [#384144](https://github.com/tensorflow/tensorflow/issues/38414#issuecomment-642836301)  ,  and also check this [comment](https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type) ,let us know if it helps
Thanks
