### ISSUE TITLE
tensorflow lite (C++) crashes in tflite::reference_ops::Gather

### ISSUE THREAD

**Issue by druban** [tensorflow/tensorflow#50497]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina, Linux Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4, 2.5, current
- Python version: 3.8
- Bazel version (if compiling from source): N/A (tensorflow-lite was compiled w/ cmake)
- GCC/Compiler version (if compiling from source): clang-12.0.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
After a few iterations over the input data tensorflow-lite crashes in tflite::reference_ops::Gather<>

**Describe the expected behavior**
Not to crash!

**Standalone code to reproduce the issue**
[standalone.tar.gz](https://www.dropbox.com/s/dwkypf5skrxzfqa/standalone.tar.gz?dl=0)

**Other info / logs** 
Backtrace (using lldb on Mac OS Catalina):
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff69bb033a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff69c6ce60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff69b37808 libsystem_c.dylib`abort + 120
    frame #3: 0x000000010049ec05 standalone`void tflite::reference_ops::Gather<float, int>(op_params=0x00007ffeefbfeee0, input_shape=0x00007ffeefbfef48, input_data=0x0000000104136ce4, coords_shape=0x00007ffeefbfef28, coords_data=0x000000011261a000, output_shape=0x00007ffeefbfef08, output_data=0x000000011261d6c0) at gather.h:76:9
    frame #4: 0x000000010049cdc6 standalone`TfLiteStatus tflite::ops::builtin::gather::Gather<float, int>(params=0x000000010302a780, input=0x000000010380a310, positions=0x000000010380a000, output=0x000000010380a770) at gather.cc:125:3
    frame #5: 0x000000010049c9b9 standalone`tflite::ops::builtin::gather::Eval(context=0x0000000103038eb8, node=0x000000010381e000) at gather.cc:166:16
    frame #6: 0x0000000100039543 standalone`tflite::Subgraph::OpInvoke(this=0x0000000103038e90, op_reg=0x000000010381e050, node=0x000000010381e000) at subgraph.h:434:12
    frame #7: 0x000000010003919b standalone`tflite::Subgraph::Invoke(this=0x0000000103038e90) at subgraph.cc:1104:9
    frame #8: 0x00000001006b91af standalone`tflite::Interpreter::Invoke(this=0x0000000103038da0) at interpreter.cc:273:3
    frame #9: 0x0000000100004b2a standalone`main((null)=<unavailable>, (null)=<unavailable>) at main.cc:139:5 [opt]
    frame #10: 0x00007fff69a68cc9 libdyld.dylib`start + 1
    frame #11: 0x00007fff69a68cc9 libdyld.dylib`start + 1
(lldb) 
```

**Comment by abattery** [comment]
The attached model does not have any issues with running with the TFLite model benchmark tool. Please make sure that the given input in your code is compatible with the model's input requirement.

**Comment by druban** [comment]
I'm not sure what can possibly be incompatible here. Model accepts 3500 integers on input. At some point it crashes.

**Comment by druban** [comment]
I stand corrected, there was an issue w/ input data. Thank you for pointing it out!
