### ISSUE TITLE
Is there a plan to support horizontal scaling for KPL?

### ISSUE THREAD

**Issue by annyan09023** [tensorflow/tensorflow#50503]
Based on current preprocessing layer code: https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/engine/base_preprocessing_layer.py#L237

horizontal scaling is not supported for KPL. For example, I cannot have TextVectorization run on different machines with different sharded data and merge at the end. I wonder is there any plan for KPL to support horizontal scaling so that it can adapt with my large dataset?

**Comment by jvishnuvardhan** [comment]
@annyan09023 Thanks for creating the issue. keras moved to a new repository and that repo is dedicated for keras development. Earlier keras team published about the move in TF forum. The link is given below.

https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

Can you please create a new issue in that repository. Thanks!

**Comment by annyan09023** [comment]
done creating another ticket under keras repo. Feel free to close this one
