### ISSUE TITLE
Is there a way to update a dynamic variable used to filter a part of your training data during training?

### ISSUE THREAD

**Issue by harsh306** [tensorflow/tensorflow#50504]
```
def myfilter(x, my_var):
    return tf.equal(x['vars'], my_var)


data = tf.data.TFRecordDataset(tf.io.match_filenames_once('part-*'))
my_var  = tf.Variable(1, trainable=False, name='my_var', dtype=tf.int64)

data = data.map(parsing_func, num_parallel_calls=multiprocessing.cpu_count() - 1)
data= data.filter(lambda x : myfilter(x, my_var) )
data = data.batch(batch_size=32)

```

Here, using static `my_var`, I am able to filter the data. However, I want to keep updating the var value from [1, 2, .... n]. Any ideas on how to do this during training? 

I was trying something like this:

```
class CustomVarScheduler(tf.keras.callbacks.Callback):
    def __init__(self, my_var):
        super(CustomPhaseScheduler, self).__init__()
        self.var = my_var

    def on_epoch_end(self, epoch, logs=None):
        # Set the value back to the optimizer before this epoch starts
        tf.keras.backend.set_value(self.my_var, tf.math.add(self.my_var, 1))
        print("\nEpoch %05d: my_var is %6.4f." % (epoch, self.my_var))

```
Not able to get it to work properly. Any help? or Possible Documentation/Feature. 

Also, willing to contribute to such documentation.  

Thanks.

**Comment by harsh306** [comment]
Or do I need something like this: https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/utils/dataset_creator.py

**Comment by Saduf2019** [comment]
@harsh306 
Is this still an issue

**Comment by harsh306** [comment]
Yeah, I didn't find a proper way to do this.

**Comment by ymodak** [comment]
This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
