### ISSUE TITLE
Iterating through DistributedDataset created from dataset with raggedTensor raises InvalidArgumentError 

### ISSUE THREAD

**Issue by kenyonke** [tensorflow/tensorflow#50507]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): dockerhub 2.5.0-gpu
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda_11.2
- GPU model and memory:  4 * Tesla T4  with 15109MiB memory

**Describe the current behavior**
After creating a DistributedDataset instances from dataset with raggedTensor elements inside, I tried to iterate through it
but InvalidArgumentError raised.  What' more, I found that only raggedTensor with string dtype has this problem and int raggedtenor works fine. 

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
strategy = tf.distribute.MirroredStrategy(["GPU:0", "GPU:1"])

# it works
ragged_dict = {'ragged':tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], [], [3, 1, 4, 1], [3, 1], [2, 1, 4, 1]])}
ragged_ds = tf.data.Dataset.from_tensor_slices(ragged_dict ).batch(2)
dist_dataset = strategy.experimental_distribute_dataset(ragged_ds)
ds = iter(dist_dataset)
next(ds)

# it doesn't work
ragged_dict = {'ragged' : tf.ragged.constant([['3', '1', '4', '1'], [], ['5', '9', '2'], ['6'], [], ['3', '1', '4', '1'], ['3', '1'], ['2', '1', '4', '1']])}
ragged_ds = tf.data.Dataset.from_tensor_slices(ragged_dict).batch(2)
dist_dataset = strategy.experimental_distribute_dataset(ragged_ds)
ds = iter(dist_dataset)
next(ds)
```

**Other info / logs** 
```
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 686, in __next__
    return self.get_next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 730, in get_next
    self, self._strategy, return_per_replica=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 604, in _get_next_as_optional
    iterator._iterators[i].get_next_as_list())  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/input_lib.py", line 1948, in get_next_as_list
    self._iterator.get_next_as_optional())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 604, in get_next_as_optional
    result.append(self._device_iterators[i].get_next_as_optional())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 825, in get_next_as_optional
    self.element_spec)), self.element_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2809, in iterator_get_next_as_optional
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
         [[{{node RemoteCall}}]] [Op:IteratorGetNextAsOptional]

```

**Comment by UsharaniPagadala** [comment]
@kenyonke 

I was able to reproduce the code shared in tf-2.5 and tf-nightly versions  with no errors.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/aae8bf08f59f64f4b7754e6090547a23/untitled124.ipynb) here.Thanks

**Comment by kenyonke** [comment]
> @kenyonke
> 
> I was able to reproduce the code shared in tf-2.5 and tf-nightly versions with no errors.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/aae8bf08f59f64f4b7754e6090547a23/untitled124.ipynb) here.Thanks

Hi @UsharaniPagadala , it sitll doesn't work on my equipment. I have no idea about this problem. I work on tensorflow docker with Tesla T4 Gpu so I think the environment is fine.

**Comment by UsharaniPagadala** [comment]
@kenyonke 

Looking at the error log it is similar to  [#28007](https://github.com/tensorflow/tensorflow/issues/28007)  and [#71](https://github.com/TensorSpeech/TensorFlowASR/issues/71) and let us know if it helps.Thanks

**Comment by kenyonke** [comment]
> @kenyonke
> 
> Looking at the error log it is similar to [#28007](https://github.com/tensorflow/tensorflow/issues/28007) and [#71](https://github.com/TensorSpeech/TensorFlowASR/issues/71) and let us know if it helps.Thanks

You need to run this code on gpus, it works on cpu or single gpu. Colab doesn't use multiple gpu even if you add
```strategy = tf.distribute.MirroredStrategy(["GPU:0", "GPU:1"])```
You can see this link
[https://colab.research.google.com/drive/1tEpZ1TQxyfh-Mz5uDPPXy3RDnX4_yCBM?usp=sharing](url)

**Comment by UsharaniPagadala** [comment]
@kenyonke 

I was not able to access the gist provided,Could you Please provide the access.Thanks

**Comment by kenyonke** [comment]
@UsharaniPagadala 

Sorry, now you should have right of access
https://colab.research.google.com/drive/1tEpZ1TQxyfh-Mz5uDPPXy3RDnX4_yCBM?usp=sharing
I think it's necessary to check whether gpu is available before mirroredstrategy

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I  was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/44b953a32137acffd8eb052adb7edc32/untitled0.ipynb).Thanks

**Comment by SeeForTwo** [comment]
After investigation, commits https://github.com/tensorflow/tensorflow/commit/55a1146af14d38bcad9afe3c3aa392e94c5e07cc and https://github.com/tensorflow/tensorflow/commit/9418c87eaa8a927fbdec2b09fbde1ca461e2579c (and related supporting commits) seem sufficient to addressed expected use cases. Some corner cases around pure eager execution may remain.

Please re-open this bug if the same symptom re-occurs or create a new bug if there's a failure with a different symptom.

**Comment by SeeForTwo** [comment]
PS. Please see  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/ragged/ragged_factory_ops_test.py for examples of working cases of ragged tensors with DistributedDataset.
