### ISSUE TITLE
For Keras training, can we relax the steps checking when distributed dataset is passed in

### ISSUE THREAD

**Issue by annyan09023** [tensorflow/tensorflow#50509]
Recently, when we tried to use MultiWorkerMirroredStrategy with Keras, we found:
1) When Keras wrap our passed in dataset with experimental distributed dataset, we found we cannot scale over x nodes because it needs us pass in a global batch size and global batch size needs to take number of workers into consideration (global batch size = batch size * num of workers * num of replica). Therefore, when we have a lot of workers, compared with Mirrored strategy, we start seeing job failure due to OOM
2) We try to get around this issue by passing in distribute_datasets_from_function that we can have full control over per replica batch and sharding logic (and get around OOM issue). Then our job failed at: https://github.com/tensorflow/tensorflow/blob/1923123d32ea41d92b70a27a3f6ecf0763b56f6c/tensorflow/python/keras/engine/data_adapter.py#L733
When we passed in normal dataset, it has UNKNOWN cardinality and leverage https://github.com/tensorflow/tensorflow/blob/1923123d32ea41d92b70a27a3f6ecf0763b56f6c/tensorflow/python/keras/engine/data_adapter.py#L710 to recreate iterator for every epoch. Our use case is to have validation step to exhaust our dataset instead of hard coding steps. I wonder if we can relax check in L733 altogether with change to L714. Then we can support no steps input from users? If you agree, I can submit the PR to make the change. 

Please let me know if any downside of doing so.

Thanks

**Comment by 8bitmp3** [comment]
Excellent question. You may also be able to get feedback at https://discuss.tensorflow.org/ - try Title: "MultiWorkerMirroredStrategy with Keras: can we relax the steps checking when distributed dataset is passed in?" and maybe someone from the community/TF team will get back to you 👍

**Comment by saikumarchalla** [comment]
@annyan09023 It looks like the issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository. Thanks!

**Comment by annyan09023** [comment]
Asked this question in keras repo instead
