### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by sagniksanyal-99** [tensorflow/tensorflow#50513]
[
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.layers import Dense,Conv1D,Flatten
from tensorflow.keras.models import Sequential, Model
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import keras
from sklearn.metrics import accuracy_score,confusion_matrix
import plotly.offline as py
import xgboost as xgb
%matplotlib inline
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
model=Sequential()
model.add(Flatten(input_shape=(10,)))
model.add(Dense(100,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',metrics=['accuracy'],loss='SparseCategoricalCrossentropy')
model.fit(x_train,y_train,batch_size=64,validation_split=0.1,epochs=25)
preds=model.predict(x_test)
preds=np.where(preds>0.5,1,0)
accuracy_score(y_test,press)]
AttributeErrorTraceback (most recent call last)
<ipython-input-18-a68cc7861501> in <module>()
      3 model.add(Dense(100,activation='relu'))
      4 model.add(Dense(1,activation='sigmoid'))
----> 5 model.compile(optimizer='adam',metrics=['accuracy'],loss='SparseCategoricalCrossentropy')
      6 model.fit(x_train,y_train,batch_size=64,validation_split=0.1,epochs=25)
      7 preds=model.predict(x_test)

3 frames
/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_utils.pyc in get_loss_function(loss)
   1186   return losses.LossFunctionWrapper(
   1187       loss_fn,
-> 1188       name=loss_fn.__name__,
   1189       reduction=losses_utils.ReductionV2.SUM_OVER_BATCH_SIZE)
   1190 

AttributeError: 'SparseCategoricalCrossentropy' object has no attribute '__name__'

**Comment by 8bitmp3** [comment]
Did you load the dataset? After importing the modules, if you run:

```python
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
```

you will get:

```
...
----> 1 x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
...
NameError: name 'X' is not defined
```

**Comment by ymodak** [comment]
You may try with
```python
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False, reduction=losses_utils.ReductionV2.AUTO,
                                                                                               name='sparse_categorical_crossentropy')
model.compile(optimizer='adam',metrics=['accuracy'],loss=loss)
```

**Comment by sagniksanyal-99** [comment]
[model.add(Flatten())
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8))
model.add(tf.keras.layers.Dense(1))
model.compile(optimizer='sgd', loss='mse')
# This builds the model for the first time:
model.fit(x_train, y_train, batch_size=32, epochs=10)



ValueErrorTraceback (most recent call last)
<ipython-input-10-333e6d95c148> in <module>()
      5 model.compile(optimizer='sgd', loss='mse')
      6 # This builds the model for the first time:
----> 7 model.fit(x_train, y_train, batch_size=32, epochs=10)

6 frames
/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_utils.pyc in validate_input_types(inp, orig_inp, allow_dict, field_name)
   1243     raise ValueError(
   1244         'Please provide as model inputs either a single array or a list of '
-> 1245         'arrays. You passed: {}={}'.format(field_name, orig_inp))
   1246 
   1247 

ValueError: Please provide as model inputs either a single array or a list of arrays.](url)

**Comment by sagniksanyal-99** [comment]
> [model.add(Flatten())
> model = tf.keras.Sequential()
> model.add(tf.keras.layers.Dense(8))
> model.add(tf.keras.layers.Dense(1))
> model.compile(optimizer='sgd', loss='mse')
> 
> # This builds the model for the first time:
> model.fit(x_train, y_train, batch_size=32, epochs=10)
> 
> ValueErrorTraceback (most recent call last)
> in ()
> 5 model.compile(optimizer='sgd', loss='mse')
> 6 # This builds the model for the first time:
> ----> 7 model.fit(x_train, y_train, batch_size=32, epochs=10)
> 
> 6 frames
> /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_utils.pyc in validate_input_types(inp, orig_inp, allow_dict, field_name)
> 1243 raise ValueError(
> 1244 'Please provide as model inputs either a single array or a list of '
> -> 1245 'arrays. You passed: {}={}'.format(field_name, orig_inp))
> 1246
> 1247
> 
> ValueError: Please provide as model inputs either a single array or a list of arrays.](url)

how I can solve this problem?
