### ISSUE TITLE
ValueError: Python inputs incompatible with input_signature:

### ISSUE THREAD

**Issue by 1148330040** [tensorflow/tensorflow#50511]
environment：tf2.2\ linux \2080Ti \cuda:10.2

I use **tf.kerns.model** and **tf.gradienttape** to build my (BERT-CRF) custom model, and now I want to use **tensorflow_ model_ Serving** deploys my model, so the first thing I need to do is save the model as a **". Pb" file**

I tried to use **tf. saved_ model. save()** to save the model, but I encountered the problem of **dtype**, because in tf2.2, I can't change the dtype of tensor to tf.int32, whether I use **constant, cast or conver_to_tensor and variable** can't change dtype to tf.int32, and their output forms are changed to int32

I saw from the Internet that by setting **@tf. function (tf. TensorSpec())** before the **call()** function, I still encountered the problem that dtype could not be converted to tf. Int32

What I want to ask is, if you use tf.keras.model to build your own model, how can you save the model as ". Pb", or can you tell me how to change the tensor of tf2.2 to tf.int32?

[https://github.com/1148330040/nlp_cvs/blob/main/Models/bert_crf.py](url)

`
model:

 class MyBertCrf(tf.keras.Model):

    def __init__(self, use_crf, input_dim, output_dim):
        super(MyBertCrf, self).__init__(use_crf, input_dim, output_dim)
        self.use_crf = use_crf
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.bert = TFBertModel.from_pretrained('hfl/chinese-bert-wwm-ext')
        self.dropout = tf.keras.layers.Dropout(0.3)
        self.dense = tf.keras.layers.Dense(self.output_dim)
        self.other_params = tf.Variable(tf.random.uniform(shape=(output_dim, output_dim)))

    @tf.function(input_signature=[tf.TensorSpec([None, 128], name='ids', dtype=tf.int32),
                                  tf.TensorSpec([None, 128], name='mask', dtype=tf.int32),
                                  tf.TensorSpec([None, 128], name='tokens', dtype=tf.int32),
                                  tf.TensorSpec([None, 128], name='target', dtype=tf.int32),
                                  tf.TensorSpec([1], name='input_seq_len', dtype=tf.int32)])
    def call(self, ids, masks, tokens, target, input_seq_len):
        hidden = self.bert(ids, masks, tokens)[0]
        dropout_inputs = self.dropout(hidden, 1)
        logistic_seq = self.dense(dropout_inputs)
        print(hidden)
        print(ids, masks, tokens, target, input_seq_len)
        if self.use_crf:
            log_likelihood, self.other_params = tfa.text.crf.crf_log_likelihood(logistic_seq,
                                                                                target,
                                                                                input_seq_len,
                                                                                self.other_params )
            decode_predict, crf_scores = tfa.text.crf_decode(logistic_seq, self.other_params , input_seq_len)

            return decode_predict, log_likelihood, crf_scores
        else:
            prob_seq = tf.nn.softmax(logistic_seq)

            return prob_seq, None, None`

error:

`    
raise ValueError("Python inputs incompatible with input_signature:\n%s" %
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[ 101 6163 1906 ...    0    0    0]
 [ 101  872 4761 ...    0    0    0]
 ...
 [ 101 1259 6163 ...    0    0    0]
 [ 101 2769 2682 ...    0    0    0]], shape=(16, 128), dtype=int32),
    tf.Tensor(
[[1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]], shape=(16, 128), dtype=int32),
    tf.Tensor(
[[0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]], shape=(16, 128), dtype=int32),
    tf.Tensor(
[[2 2 2 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]], shape=(16, 128), dtype=int32),
    tf.Tensor([19 19 28 28 21 27 19 20 32 22 23 29 27 21 29 25], shape=(16,), dtype=int32))
  input_signature: (
    TensorSpec(shape=(None, 128), dtype=tf.int32, name='ids'),
    TensorSpec(shape=(None, 128), dtype=tf.int32, name='mask'),
    TensorSpec(shape=(None, 128), dtype=tf.int32, name='tokens'),
    TensorSpec(shape=(None, 128), dtype=tf.int32, name='target'),
    TensorSpec(shape=(1,), dtype=tf.int32, name='input_seq_len'))

Process finished with exit code 1
`

**Comment by 1148330040** [comment]
> environment：tf2.2\ linux \2080Ti \cuda:10.2
> 
> I use **tf.kerns.model** and **tf.gradienttape** to build my (BERT-CRF) custom model, and now I want to use **tensorflow_ model_ Serving** deploys my model, so the first thing I need to do is save the model as a **". Pb" file**
> 
> I tried to use **tf. saved_ model. save()** to save the model, but I encountered the problem of **dtype**, because in tf2.2, I can't change the dtype of tensor to tf.int32, whether I use **constant, cast or conver_to_tensor and variable** can't change dtype to tf.int32, and their output forms are changed to int32
> 
> I saw from the Internet that by setting **@tf. function (tf. TensorSpec())** before the **call()** function, I still encountered the problem that dtype could not be converted to tf. Int32
> 
> What I want to ask is, if you use tf.keras.model to build your own model, how can you save the model as ". Pb", or can you tell me how to change the tensor of tf2.2 to tf.int32?
> 
> [https://github.com/1148330040/nlp_cvs/blob/main/Models/bert_crf.py](url)
> 
> `
> model:
> 
> class MyBertCrf(tf.keras.Model):
> 
> ```
> def __init__(self, use_crf, input_dim, output_dim):
>     super(MyBertCrf, self).__init__(use_crf, input_dim, output_dim)
>     self.use_crf = use_crf
>     self.input_dim = input_dim
>     self.output_dim = output_dim
>     self.bert = TFBertModel.from_pretrained('hfl/chinese-bert-wwm-ext')
>     self.dropout = tf.keras.layers.Dropout(0.3)
>     self.dense = tf.keras.layers.Dense(self.output_dim)
>     self.other_params = tf.Variable(tf.random.uniform(shape=(output_dim, output_dim)))
> 
> @tf.function(input_signature=[tf.TensorSpec([None, 128], name='ids', dtype=tf.int32),
>                               tf.TensorSpec([None, 128], name='mask', dtype=tf.int32),
>                               tf.TensorSpec([None, 128], name='tokens', dtype=tf.int32),
>                               tf.TensorSpec([None, 128], name='target', dtype=tf.int32),
>                               tf.TensorSpec([1], name='input_seq_len', dtype=tf.int32)])
> def call(self, ids, masks, tokens, target, input_seq_len):
>     hidden = self.bert(ids, masks, tokens)[0]
>     dropout_inputs = self.dropout(hidden, 1)
>     logistic_seq = self.dense(dropout_inputs)
>     print(hidden)
>     print(ids, masks, tokens, target, input_seq_len)
>     if self.use_crf:
>         log_likelihood, self.other_params = tfa.text.crf.crf_log_likelihood(logistic_seq,
>                                                                             target,
>                                                                             input_seq_len,
>                                                                             self.other_params )
>         decode_predict, crf_scores = tfa.text.crf_decode(logistic_seq, self.other_params , input_seq_len)
> 
>         return decode_predict, log_likelihood, crf_scores
>     else:
>         prob_seq = tf.nn.softmax(logistic_seq)
> 
>         return prob_seq, None, None`
> ```
> 
> error:
> 
> `
> raise ValueError("Python inputs incompatible with input_signature:\n%s" %
> ValueError: Python inputs incompatible with input_signature:
> inputs: (
> tf.Tensor(
> [[ 101 6163 1906 ... 0 0 0]
> [ 101 872 4761 ... 0 0 0]
> ...
> [ 101 1259 6163 ... 0 0 0]
> [ 101 2769 2682 ... 0 0 0]], shape=(16, 128), dtype=int32),
> tf.Tensor(
> [[1 1 1 ... 0 0 0]
> ...
> [1 1 1 ... 0 0 0]], shape=(16, 128), dtype=int32),
> tf.Tensor(
> [[0 0 0 ... 0 0 0]
> ...
> [0 0 0 ... 0 0 0]], shape=(16, 128), dtype=int32),
> tf.Tensor(
> [[2 2 2 ... 0 0 0]
> ...
> [1 1 1 ... 0 0 0]], shape=(16, 128), dtype=int32),
> tf.Tensor([19 19 28 28 21 27 19 20 32 22 23 29 27 21 29 25], shape=(16,), dtype=int32))
> input_signature: (
> TensorSpec(shape=(None, 128), dtype=tf.int32, name='ids'),
> TensorSpec(shape=(None, 128), dtype=tf.int32, name='mask'),
> TensorSpec(shape=(None, 128), dtype=tf.int32, name='tokens'),
> TensorSpec(shape=(None, 128), dtype=tf.int32, name='target'),
> TensorSpec(shape=(1,), dtype=tf.int32, name='input_seq_len'))
> 
> Process finished with exit code 1
> `

**Comment by harshayelchuri** [comment]
I'm facing a similar problem, did your error got resolved?
 See https://github.com/tensorflow/tensorflow/issues/55403 for more details.

**Comment by 1148330040** [comment]
> 



> I'm facing a similar problem, did your error got resolved? See #55403 for more details.

Solved

Change it to the following form（One more '()'）:

![1648532978(1)](https://user-images.githubusercontent.com/34124260/160542276-7819e7af-39db-4005-8b81-43bf8d973dd7.png)

**Comment by harshayelchuri** [comment]
@1148330040 can you see https://github.com/tensorflow/tensorflow/issues/55403 and find out what exactly is causing the problem?

**Comment by 1148330040** [comment]
> @1148330040 can you see #55403 and find out what exactly is causing the problem?

sorry, i cant open your code, i use tf2.2, My mistake is missing a bracket. You can try it

**Comment by harshayelchuri** [comment]
@1148330040 I tried adding a bracket, but it's still not working

**Comment by 1148330040** [comment]
show me your model code，not web，I can't open it

---Original---
From: "Yelchuri venkata sai ***@***.***&gt;
Date: Tue, Mar 29, 2022 14:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/tensorflow] ValueError: Python inputs incompatible with input_signature: (#50511)




 
@1148330040 I tried adding a bracket, but it's still not working

**Comment by harshayelchuri** [comment]
This is model code:
def __init__(self):
    self.model = tf.keras.Sequential([
        tf.keras.layers.Dense(24,input_shape=(2,), activation='relu'),
        tf.keras.layers.Dense(12,activation='relu'),
        tf.keras.layers.Dense(1,activation='sigmoid')])

This is error:
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[ 9.       17.229916]
 [15.       10.601508]
 [15.       10.517618]
 [ 7.       26.893027]
 [15.       10.572687]
 [ 7.       27.393882]
 [15.        9.859101]
 [14.       11.724992]
 [12.       13.421819]
 [ 7.       28.229916]], shape=(10, 2), dtype=float64),
    tf.Tensor([1. 1. 1. 0. 1. 0. 1. 1. 1. 0.], shape=(10,), dtype=float64))
  input_signature: (
    TensorSpec(shape=(None, 2), dtype=tf.float64, name=None),
    TensorSpec(shape=(None, 1), dtype=tf.float64, name=None)).

**Comment by harshayelchuri** [comment]
This is the class code:

class Model(tf.Module):

  def __init__(self):
    self.model = tf.keras.Sequential([
        tf.keras.layers.Dense(24,input_shape=(2,), activation='relu'),
        tf.keras.layers.Dense(12,activation='relu'),
        tf.keras.layers.Dense(1,activation='sigmoid')])
    self.loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=False)
    self.optimizer = tf.keras.optimizers.Adam()
    self.train_loss_results = []
    self.train_accuracy_results = []
    self.epoch_loss_avg = tf.keras.metrics.Mean()
    self.epoch_accuracy = tf.keras.metrics.BinaryAccuracy()


  def loss(self,model, x, y, training):
    # training=training is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    y_ = self.model(x, training=False)
    return self.loss_object(y_true=y, y_pred=y_)

  def grad(self,model, inputs, targets):
    with tf.GradientTape() as tape:
      loss_value = self.loss(model, inputs, targets, training=False)
    return loss_value, tape.gradient(loss_value, model.trainable_variables)

  # The `train` function takes a batch of input images and labels.
  @tf.function(input_signature=[(tf.TensorSpec([None, 2], tf.float64)),
                                (tf.TensorSpec([None, 1], tf.float64))])
  def train(self, x, y):
    loss_value, grads = self.grad(self.model, x, y)
    self.optimizer.apply_gradients(zip(grads, self.model.trainable_variables))
    result = {"loss": loss_value}
    self.epoch_loss_avg.update_state(loss_value)  
    self.epoch_accuracy.update_state(y, self.model(x, training=True))
    return result

  @tf.function(input_signature=[
      tf.TensorSpec([None, 2], tf.float32),
  ])

  def infer(self, x):
    logits = self.model(x)
    prediction=tf.math.round(logits)
    return {
        "output": prediction,
        "logits": logits
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def save(self, checkpoint_path):
    tensor_names = [weight.name for weight in self.model.weights]
    tensors_to_save = [weight.read_value() for weight in self.model.weights]
    tf.raw_ops.Save(
        filename=checkpoint_path, tensor_names=tensor_names,
        data=tensors_to_save, name='save')
    return {
        "checkpoint_path": checkpoint_path
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def restore(self, checkpoint_path):
    restored_tensors = {}
    for var in self.model.weights:
      restored = tf.raw_ops.Restore(
          file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
          name='restore')
      var.assign(restored)
      restored_tensors[var.name] = restored
    return restored_tensors

**Comment by 1148330040** [comment]
# you can try this one:
# ==============================
max_len = 12
class MyModel(tf.keras.Model):
    def init(self, output_dim):
        super(MyModel, self).__init__(output_dim)
        self.dense1 = tf.keras.layers.Dense(24,input_shape=(2,), activation='relu')
        self.dense2 = tf.keras.layers.Dense(12,activation='relu')
        self.dense3 = tf.keras.layers.Dense(1,activation='sigmoid')

    @tf.function(input_signature=[(tf.TensorSpec([None, max_len], name='input_ds', dtype=tf.int32))])
    def call(self, batch_ds):
        input_ids = batch_ds
        hidden1 = self.dense1(input_ids)
        hidden1 = self.dense2(hidden1)
        predict = self.dense3(hidden1)
        return predict

def loss(self, x, y,):
    # training=training is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    return tf.keras.losses.BinaryCrossentropy(x, y)

def data_generator():
    # Here is your own data iterator
    return 1

def train():
    model = MyModel(1)
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-5)
    def grad(inputs, targets):
        with tf.GradientTape() as tape:
            loss_value = loss(model, inputs, targets)

        params = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(params, model.trainable_variables))
        return loss_value

    for ds in data_generator:
        input_ds = ds[0]
        label = ds[1]
        loss = grad(input_ds, label)

        model.save('your_model.weights')

# you can try like this one
# ========================

model = tf.keras.Sequential([
    tf.keras.layers.Dense(24,input_shape=(2,), activation='relu'),
    tf.keras.layers.Dense(12,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')])

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.BinaryCrossentropy # 'binary_crossentropy'
)

model.fit()

model.save()




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] ValueError: Python inputs incompatible with input_signature: (#50511)





 
This is the class code:
 
class Model(tf.Module):
 
def init(self):
 self.model = tf.keras.Sequential([
 tf.keras.layers.Dense(24,input_shape=(2,), activation='relu'),
 tf.keras.layers.Dense(12,activation='relu'),
 tf.keras.layers.Dense(1,activation='sigmoid')])
 self.loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=False)
 self.optimizer = tf.keras.optimizers.Adam()
 self.train_loss_results = []
 self.train_accuracy_results = []
 self.epoch_loss_avg = tf.keras.metrics.Mean()
 self.epoch_accuracy = tf.keras.metrics.BinaryAccuracy()
 
def loss(self,model, x, y, training):
 # training=training is needed only if there are layers with different
 # behavior during training versus inference (e.g. Dropout).
 y_ = self.model(x, training=False)
 return self.loss_object(y_true=y, y_pred=y_)
 
def grad(self,model, inputs, targets):
 with tf.GradientTape() as tape:
 loss_value = self.loss(model, inputs, targets, training=False)
 return loss_value, tape.gradient(loss_value, model.trainable_variables)
 
The train function takes a batch of input images and labels.
 
@tf.function(input_signature=[(tf.TensorSpec([None, 2], tf.float64)),
 (tf.TensorSpec([None, 1], tf.float64))])
 def train(self, x, y):
 loss_value, grads = self.grad(self.model, x, y)
 self.optimizer.apply_gradients(zip(grads, self.model.trainable_variables))
 result = {"loss": loss_value}
 self.epoch_loss_avg.update_state(loss_value)
 self.epoch_accuracy.update_state(y, self.model(x, training=True))
 return result
 
@tf.function(input_signature=[
 tf.TensorSpec([None, 2], tf.float32),
 ])
 
def infer(self, x):
 logits = self.model(x)
 prediction=tf.math.round(logits)
 return {
 "output": prediction,
 "logits": logits
 }
 
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
 def save(self, checkpoint_path):
 tensor_names = [weight.name for weight in self.model.weights]
 tensors_to_save = [weight.read_value() for weight in self.model.weights]
 tf.raw_ops.Save(
 filename=checkpoint_path, tensor_names=tensor_names,
 data=tensors_to_save, name='save')
 return {
 "checkpoint_path": checkpoint_path
 }
 
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
 def restore(self, checkpoint_path):
 restored_tensors = {}
 for var in self.model.weights:
 restored = tf.raw_ops.Restore(
 file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
 name='restore')
 var.assign(restored)
 restored_tensors[var.name] = restored
 return restored_tensors

**Comment by 1148330040** [comment]
TF. No suggestion first keras.Sequential () and self built inherit from TF.Moudle is used in combination. I don't understand. Is this the code in the tensorflow tutorial?


This is very different. As for the reason, you can find it yourself. It's a process of progress for you.




Next @ tf.function (input_signature=() is to specify the format of input data of the model


It won't be with TF.keras.Sequential () appears together, so your code gives me the feeling that it is very messy, a simplified process version TF keras. Seq and customized versions are mixed.



So you can take a look at the code examples I wrote for you first, and please take a closer look at the basic tutorial of tensorflow:
初学者的 TensorFlow 2.0 教程 &nbsp;|&nbsp; TensorFlow Core (google.cn)
针对专业人员的 TensorFlow 2.0 入门 &nbsp;|&nbsp; TensorFlow Core (google.cn)
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] ValueError: Python inputs incompatible with input_signature: (#50511)





 
This is the class code:
 
class Model(tf.Module):
 
def init(self):
 self.model = tf.keras.Sequential([
 tf.keras.layers.Dense(24,input_shape=(2,), activation='relu'),
 tf.keras.layers.Dense(12,activation='relu'),
 tf.keras.layers.Dense(1,activation='sigmoid')])
 self.loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=False)
 self.optimizer = tf.keras.optimizers.Adam()
 self.train_loss_results = []
 self.train_accuracy_results = []
 self.epoch_loss_avg = tf.keras.metrics.Mean()
 self.epoch_accuracy = tf.keras.metrics.BinaryAccuracy()
 
def loss(self,model, x, y, training):
 # training=training is needed only if there are layers with different
 # behavior during training versus inference (e.g. Dropout).
 y_ = self.model(x, training=False)
 return self.loss_object(y_true=y, y_pred=y_)
 
def grad(self,model, inputs, targets):
 with tf.GradientTape() as tape:
 loss_value = self.loss(model, inputs, targets, training=False)
 return loss_value, tape.gradient(loss_value, model.trainable_variables)
 
The train function takes a batch of input images and labels.
 
@tf.function(input_signature=[(tf.TensorSpec([None, 2], tf.float64)),
 (tf.TensorSpec([None, 1], tf.float64))])
 def train(self, x, y):
 loss_value, grads = self.grad(self.model, x, y)
 self.optimizer.apply_gradients(zip(grads, self.model.trainable_variables))
 result = {"loss": loss_value}
 self.epoch_loss_avg.update_state(loss_value)
 self.epoch_accuracy.update_state(y, self.model(x, training=True))
 return result
 
@tf.function(input_signature=[
 tf.TensorSpec([None, 2], tf.float32),
 ])
 
def infer(self, x):
 logits = self.model(x)
 prediction=tf.math.round(logits)
 return {
 "output": prediction,
 "logits": logits
 }
 
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
 def save(self, checkpoint_path):
 tensor_names = [weight.name for weight in self.model.weights]
 tensors_to_save = [weight.read_value() for weight in self.model.weights]
 tf.raw_ops.Save(
 filename=checkpoint_path, tensor_names=tensor_names,
 data=tensors_to_save, name='save')
 return {
 "checkpoint_path": checkpoint_path
 }
 
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
 def restore(self, checkpoint_path):
 restored_tensors = {}
 for var in self.model.weights:
 restored = tf.raw_ops.Restore(
 file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
 name='restore')
 var.assign(restored)
 restored_tensors[var.name] = restored
 return restored_tensors

**Comment by harshayelchuri** [comment]
Thanks for the suggestions, but hen I changed the input signature from (None,1) to (None)  the program started working

**Comment by 1148330040** [comment]
congratulations！~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] ValueError: Python inputs incompatible with input_signature: (#50511)





 
Thanks for the suggestions, but hen I changed the input signature from (None,1) to (None)  the program started working

**Comment by harshayelchuri** [comment]
Thank you!!
