### ISSUE TITLE
Label_image always giving same outputs

### ISSUE THREAD

**Issue by ardtrkc** [tensorflow/tensorflow#50518]
Hi all !

While testing our models with basic [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image) example, we faced with strange results.

We tried _label_image_ with 2 different YOLO models with their corresponding label.txt. However regardless the input images and labels, the test output is always in the same order as [2 3 0 1]. Finally we also gave the Grace Hopper image from official source and still we faced with same issue. You can see the outputs in the image below.

Normally our models are working smoothly on PC. But, it is important for us to test them in our iMX6 device with this basic sample. Do you have any idea or solution about this problem ?
Thank you in advance.

![image](https://user-images.githubusercontent.com/56031118/123631875-8b6dac00-d817-11eb-8ba0-17047e522da4.png)

**Comment by thaink** [comment]
Can you shows the input and output description of your models?
Note that label_image example assumes there is one output and that is the probabilities of each labels.

**Comment by ardtrkc** [comment]
> Can you shows the input and output description of your models?

Input and output are defined as below in our YOLO model.
![image](https://user-images.githubusercontent.com/56031118/123957548-39aa5a80-d9ac-11eb-914e-9a0b87420b30.jpg)


> Note that label_image example assumes there is one output and that is the probabilities of each labels.

Normally in terms of classification our model performs well on our tests in Colab, but basicly we also want to see how it works on label_image sample. 
When we try label_image with MobileNet model and grace hopper image, it works properly. So we want to figure out what we are doing wrong in our model...

**Comment by thaink** [comment]
`Normally in terms of classification our model performs well on our tests in Colab`
Did you run it with Tensorflow or Tensorflow Lite in Colab?

**Comment by ardtrkc** [comment]
> Did you run it with Tensorflow or Tensorflow Lite in Colab?

Actually, we run it with Tensorflow.

**Comment by thaink** [comment]
Could you try to run the TFLite model in Colab and check its result there.

The reason is you fully understand and control the input/output processing there (since you have the code working for the TF model) so it will be a good start to debug it there.

In my experience, most of these unexpected accuracy problems is in input/output handling.
