### ISSUE TITLE
tflite-runtime (2.5) needs GLIBC_2.29 with Python 3.8

### ISSUE THREAD

**Issue by brunovollmer** [tensorflow/tensorflow#50514]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mendel Linux (Coral Dev Board)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: tflite-runtime 2.5
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: --- 
- GPU model and memory: ---

Hey,

I'm not sure if this is the right place but I'm having problems with the tflite-runtime and python 3.8 on the coral dev board.
I've upgraded to python 3.8 due to some other requirements and installed tflite-runtime with version 2.5.
Now when I try to import the runtime I get this error:

```
Python 3.8.0 (default, May 17 2021, 08:51:42) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mendel/env3.8/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mendel/env3.8/lib/python3.8/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-38-aarch64-linux-gnu.so)
```

Any suggestions how to fix this?

Bruno

**Comment by brunovollmer** [comment]
Any ideas?

**Comment by terryheo** [comment]
You might need to build PIP by yourself. Check the following pages.

https://www.tensorflow.org/lite/guide/build_cmake_arm
https://www.tensorflow.org/lite/guide/build_cmake_pip

**Comment by brunovollmer** [comment]
No way around it with Python3.8?

**Comment by brunovollmer** [comment]
Is there any difference between building the binaries and building the wheel (and installing it with pip) for the final usage?

**Comment by terryheo** [comment]
It depends on programming language you want to use.
PIP is for [Python API](https://www.tensorflow.org/lite/guide/python) and other binaries are for [C++](https://www.tensorflow.org/lite/api_docs/cc) or C.

**Comment by brunovollmer** [comment]
Thanks @terryheo. When I run the docker container to cross-compile the wheel it does not find docker. Any idea how to fix this? I cloned the latest version of the tensorflow repo.

Error Message:
```

thon3.8/dist-packages/pybind11/include     CMakeFiles/cmTC_41885.dir/testCCompiler.c.o  -o cmTC_41885 
    aarch64-linux-gnu-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found
    compilation terminated.
    CMakeFiles/cmTC_41885.dir/build.make:89: recipe for target 'cmTC_41885' failed
    make[1]: *** [cmTC_41885] Error 1
    make[1]: Leaving directory '/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeTmp'
    Makefile:124: recipe for target 'cmTC_41885/fast' failed
    make: *** [cmTC_41885/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:40 (project)


CMake Error at CMakeLists.txt:40 (project):
  The CMAKE_CXX_COMPILER:

    /workspace/tensorflow/lite/tools/cmake/toolchains/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeOutput.log".
See also "/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeError.log".
```

**Comment by brunovollmer** [comment]
Solved by building myself. Thanks for the help!
