### ISSUE TITLE
Linking with TFLite v2.5.0 fails due to undefined reference to rdft2d

### ISSUE THREAD

**Issue by psyhtest** [tensorflow/tensorflow#50529]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NVIDIA Xavier Jetson AGX, JetPack 4.5.1 (Ubuntu 18.04.5)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): TFLite installed from source
- TensorFlow version: v2.5.0
- Python version: v3.6.9
- CMake version: v1.19.5
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Installing TensorFlow Lite via [Collective Knowledge](http://cknowledge.org/) (which uses CMake), as described in this [Jupyter notebook](https://github.com/krai/ck-mlperf/blob/master/jnotebook/image-classification-tflite-loadgen/image-classification-tflite-loadgen.ipynb), with a new patch to support v2.5.0, would go fine but then fail with a linking error with `rdft2d`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
$ ck install package --tags=lib,tflite,via-cmake,with.ruy,v2.5.0
$ ck compile program:image-classification-tflite --dep_add_tags.library=tflite,v2.5.0
...
/home/katya/CK-TOOLS/lib-tflite-src-static-gcc-7.5.0-v2.5.0-with.ruy-linux-64/lib/libtensorflow-lite.a(rfft2d.cc.o): In function `tflite::ops::builtin::rfft2d::Rfft2dImpl(int, int, double**, int*, double*)':
rfft2d.cc:(.text+0x978): undefined reference to `rdft2d'
collect2: error: ld returned 1 exit status
```

**Any other info / logs**
What's weird is that despite the [apparent intent](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/modules/fft2d/CMakeLists.txt#L54) to "export" `fftsg2d` which contains `rdft2d`, only `fftsg.c.o` would be linked against `libtensorflow-lite.a`. As a not completely logical workaround, I've managed just about to get it working with the following [patch](https://github.com/krai/ck-tensorflow/commit/09f8a605f4e69cc0e91a19844cef8f95a0d01f84#diff-8c0c02ef5dc0cea5405bd0bf376468e1107e5d721f8a99c534f9912b7ac59f35):

<pre><b>diff --git a/tensorflow/lite/tools/cmake/modules/fft2d/CMakeLists.txt b/tensorflow/lite/tools/cmake/modules/fft2d/CMakeLists.txt</b>
<b>index e7a5ed9b443..04c5b7c05db 100644</b>
<b>--- a/tensorflow/lite/tools/cmake/modules/fft2d/CMakeLists.txt</b>
<b>+++ b/tensorflow/lite/tools/cmake/modules/fft2d/CMakeLists.txt</b>
<font color="#2AA198">@@ -37,7 +37,7 @@</font> target_include_directories(fft2d_alloc PUBLIC &quot;${FFT2D_SOURCE_DIR}&quot;)
 add_library(fft2d_fft4f2d &quot;${FFT2D_SOURCE_DIR}/fft4f2d.c&quot;)
 target_include_directories(fft2d_fft4f2d PRIVATE &quot;${FFT2D_SOURCE_DIR}&quot;)

<font color="#DC322F">-add_library(fft2d_fftsg &quot;${FFT2D_SOURCE_DIR}/fftsg.c&quot;)</font>
<font color="#859900">+add_library(fft2d_fftsg &quot;${FFT2D_SOURCE_DIR}/fftsg.c&quot; &quot;${FFT2D_SOURCE_DIR}/fftsg2d.c&quot;)</font>

 # Requires implementation of fft2d_alloc.
 add_library(fft2d_fftsg2d &quot;${FFT2D_SOURCE_DIR}/fftsg2d.c&quot;)
</pre>

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
