### ISSUE TITLE
Does tf.data.Dataset.from_tensor_slices() and tf.cast() creates extra memory

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#50524]
Suppose "imageX", "imageY" are numpy arrays of size 20GB, is
dataset = tf.data.Dataset.from_tensor_slices((imageX, imageY))
creating an extra dataset using 40GB memory, or it will re-use the numpy array memory occupied by "imageX" and "imageY"?

Also, does tf.cast() create extra memory or re-use exist numpy memory?

**Comment by Saduf2019** [comment]
@llodds 
 it creates a dataset that on-the-fly consumes numpy arrays and provides a batch at a time. It doesn't increase memory
That is the goal of dataset.

Kindly create Stackoverflow/Tensorflow discussion group and move this to closed status.

**Comment by llodds** [comment]
Thanks for confirming this!
