### ISSUE TITLE
Numpy Version

### ISSUE THREAD

**Issue by Expert73** [tensorflow/tensorflow#50526]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): from source
- TensorFlow version: 2.5, 2.6, etc
- Python version: 3.9

Where can I find the nupmy version requirements for a Tensorflow build?
Please write requirements for numpy as you write for cuda.

**Comment by UsharaniPagadala** [comment]
@Expert73 

Could you please refer the similar issue [#31249](https://github.com/tensorflow/tensorflow/issues/31249),also refer this [documentation](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform-release-notes/tf-jetson-rel.html) ,let us  know if it helps.Thanks

**Comment by Expert73** [comment]
Before doing a build from tensorflow source where can I find out the REQUIRED version of numpy?

**Comment by melanopsis** [comment]
I would select the appropriate tag (version) in code view then check `tensorflow/tools/pip_package/setup.py` file for required packages.

**Comment by Expert73** [comment]
> I would select the appropriate tag (version) in code view

what do you mean? how to do it?

**Comment by UsharaniPagadala** [comment]
@Expert73 

TensorFlow NumPy is built on top of TensorFlow and hence interoperates seamlessly with TensorFlow. Please refer this [documentation](https://www.tensorflow.org/guide/tf_numpy#tf_numpy_and_tensorflow) and let us know if it helps.Thanks
