### ISSUE TITLE
Specifying resource subtypes when converting graphdef to MLIR

### ISSUE THREAD

**Issue by laszlo-luminous** [tensorflow/tensorflow#50521]
**System information**
- TensorFlow version (you are using): 2.7.0-dev20210629
- Are you willing to contribute it (Yes/No): Yes (but may need some guidance).

**Describe the feature and the current behavior/state.**
The current tools that allow conversion of TensorFlow models to MLIR, do not seem to allow specifying the subtype for resource type tensors in the input arguments.
Consider the following snippet:
```python
import tensorflow as tf
from tensorflow.python.pywrap_mlir import import_graphdef

SIZE = 3

class MyModel(tf.keras.Model):
    def build(self, input_shape):
        self.w = self.add_weight(shape=(SIZE,), trainable=True)

    def call(self, input):
        self.w.assign_add(input)
        return input

if __name__ == "__main__":
    model = MyModel()

    func = tf.function(model)
    concrete_func = func.get_concrete_function(
        tf.TensorSpec(shape=(SIZE,), dtype=tf.float32)
    )
    graph = concrete_func.graph

    mlir_tf = import_graphdef(
        graph.as_graph_def(add_shapes=True),
        "tf-standard-pipeline",
        False,
        input_names=[t.name for t in graph.inputs],
        input_data_types=["DT_FLOAT", "DT_RESOURCE"],
        input_data_shapes=[",".join(str(d) for d in t.shape) for t in graph.inputs],
        output_names=[t.name for t in graph.outputs],
    )
    print(mlir_tf)

    with open("model.mlir", "w") as f:
        f.write(mlir_tf)
```
which outputs the following MLIR:
```mlir
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 811 : i32}}  {
  func @main(%arg0: tensor<3xf32>, %arg1: tensor<!tf.resource>) -> tensor<3xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "args_0:0,my_model/AssignAddVariableOp/resource:0", outputs = "Identity:0"}} {
    "tf.AssignAddVariableOp"(%arg1, %arg0) {device = ""} : (tensor<!tf.resource>, tensor<3xf32>) -> ()
    %0 = "tf.Identity"(%arg0) {device = ""} : (tensor<3xf32>) -> tensor<3xf32>
    return %0 : tensor<3xf32>
  }
}
```
Trying to lower this to `hlo` produces an error:
```console
>>> tf-opt --tf-to-hlo-pipeline model.mlir -o out.mlir
model.mlir:2:3: error: expects resource type of argument 1 to have one subtype, got '!tf.resource'
  func @main(%arg0: tensor<3xf32>, %arg1: tensor<!tf.resource>) -> tensor<3xf32> attributes {tf.entry_function = {control_outputs = "", inputs = "args_0:0,my_model/AssignAddVariableOp/resource:0", outputs = "Identity:0"}} {
  ^
model.mlir:2:3: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<3xf32>, %arg1: tensor<!tf.resource>):  // no predecessors
  %0 = "tf.ReadVariableOp"(%arg1) : (tensor<!tf.resource>) -> tensor<*xf32>
  %1 = "tf.AddV2"(%0, %arg0) : (tensor<*xf32>, tensor<3xf32>) -> tensor<*xf32>
  "tf.AssignVariableOp"(%arg1, %1) : (tensor<!tf.resource>, tensor<*xf32>) -> ()
  "std.return"(%arg0) : (tensor<3xf32>) -> ()
}) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "args_0:0,my_model/AssignAddVariableOp/resource:0", outputs = "Identity:0"}, type = (tensor<3xf32>, tensor<!tf.resource>) -> tensor<3xf32>} : () -> ()
```
After manually modifying the type of `%arg1` to `tensor<!tf.resource<tensor<3xf32>>>`, the conversion to `hlo` works as expected.

It would be nice if there was a way to directly specify subtypes for resources when using `import_graphdef` (or `tf_mlir_translate` with the `--tf-input-arrays` option).

**Will this change the current api? How?**

Yes. One idea is that the `input_data_types` argument of `import_graphdef` could accept subtypes for `DT_RESOURCE` with a syntax like this:
```python
input_data_types=["DT_FLOAT", "DT_RESOURCE<tensor<3xf32>>"],
```
or like this
```python
input_data_types=["DT_FLOAT", "DT_RESOURCE(3:DT_FLOAT)"],
```
or something similar.
`tf_mlir_translate --tf-input-arrays` could adopt the same syntax.

**Who will benefit with this feature?**

Anyone who wants to export models with resource inputs to MLIR (e.g. the graph of a single training step).

**Any Other info.**

Please let me know if there is a different method to emit the desired MLIR.

**Comment by joker-eph** [comment]
This seems like it would be a nice improvement indeed!

**Comment by tilakrayal** [comment]
@laszlo-luminous,
I tried to execute the code on tensorflow v2.11 and it was executed without any error/issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d4fc6f44077d120895dd7bc7091a4ea6/untitled1008.ipynb) and also the related PR's #55791 & https://github.com/parsabee/tensorflow/pull/1/files were also merged.

https://github.com/tensorflow/tensorflow/pull/55791/files

Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
