### ISSUE TITLE
Grammatical Mistakes in the documentation of tf.keras.Model.load_weights

### ISSUE THREAD

**Issue by worldpeaceaspirer** [tensorflow/tensorflow#50536]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights

## Description of issue (what needs changing): 

The documentation is a bit confusing with the Terms like **`False Weights`**, **`should be the same as when`**, etc.. It can be refined.

**Comment by rmothukuru** [comment]
Created a CL to fix the mistakes.

**Comment by robotjellyzone** [comment]
Hi, Is this issue still active? Is anyone working on it?
