### ISSUE TITLE
tensorflow v2.0.0 compatibility with scipy 

### ISSUE THREAD

**Issue by saida11000** [tensorflow/tensorflow#50531]
hello ,
i'm developing a neural network to train a  data set , i'm getting this error:
raise ImportError('Image transformations require SciPy. '

ImportError: Image transformations require SciPy. Install SciPy.

i'm using tensorflow v2.0.0 what version of SciPy is compatible with tensorflow 2.0.0 ? what version of Scipy should i install and how ? I'm working with Nvidia Jetson  nano .
please help

**Comment by UsharaniPagadala** [comment]
@saida11000 
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md) has not been filled, could you please do so as it helps us analyse the issue

Could you please refer the similar [#40884](https://github.com/tensorflow/tensorflow/issues/40884) , [#87](https://github.com/apple/tensorflow_macos/issues/87) and also refer the [documentation](https://forums.developer.nvidia.com/t/official-tensorflow-for-jetson-nano/71770) ,let us know if it helps.Thanks
