### ISSUE TITLE
Change batching in timeseries_dataset_from_array to be optional

### ISSUE THREAD

**Issue by sebimarkgraf** [tensorflow/tensorflow#50532]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The ``keras.preprocessing.timeseries_dataset_from_array`` function works well for creating timeseries datasets, but when creating the dataset from multiple independent timeseries (e.g. different locations) one would need to merge the datasets.
As the current implementation requires batching to be used and to my knowledge batched datasets cannot be concatenated, developers cannot use the generating function in that case.
A simple fix would be to allow the developer to provide ``None`` for the batch size and do not perform batching in that case.
This would be in line with the other parameters.

**Will this change the current api? How?**
Small change, the documentation of ``batch_size`` would need to be updated.

**Who will benefit with this feature?**
Users wanting to train more complex timeseries problems.

**Any Other info.**

**Comment by Saduf2019** [comment]
@sebimarkgraf 

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by sebimarkgraf** [comment]
@Sadulf2019 thank you very much! Definitely going to do this.
Then there's no reason to keep this here open.
