### ISSUE TITLE
QNNPACK for TensorFlow Lite

### ISSUE THREAD

**Issue by onyx22574** [tensorflow/tensorflow#50538]
I am looking for an alternative for QNNPACK to execute quantized DNN effectively on CPU, ARM-based devices. In other words, what is the recommended approach to effectively interpret quantized NN?

Please can I have some examples?

Thank you.

**Comment by UsharaniPagadala** [comment]
@onyx22574 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow.](https://stackoverflow.com/questions/tagged/tensorflow) or in TF [Forum](https://discuss.tensorflow.org/) There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks
