### ISSUE TITLE
/libmetal_plugin.dylib: Symbol not found: _TF_AssignUpdateVariable

### ISSUE THREAD

**Issue by dbl001** [tensorflow/tensorflow#50541]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Big Sur OS X 11.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- Binary
- TensorFlow version (use command below):
-  python -m pip install tensorflow-metal
- Tensorflow Metal - v2.5
- Python version:
- 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
AMD Radeon Pro 5700 XT
You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d6579f534729> in <module>
----> 1 import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [2]: quit()
(tensorflow-metal) (base) davidlaxer@x86_64-apple-darwin13 notebooks % otool -hV /Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/tensorflow-plugins/libmetal_plugin.dylib
/Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/tensorflow-plugins/libmetal_plugin.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   X86_64        ALL  0x00       DYLIB    22       3160   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK NO_REEXPORTED_DYLIBS MH_HAS_TLV_DESCRIPTORS

 nm -n  /Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/tensorflow-plugins/libmetal_plugin.dylib | grep TF_AssignUpdate
                 U _TF_AssignUpdateVariable

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@dbl001 

 Could you please elaborate your use case with complete details. And what are the steps to get the above error.

Also refer the similar issues  [#45645](https://github.com/tensorflow/tensorflow/issues/45645), [#42482](https://github.com/tensorflow/tensorflow/issues/42482).Thanks

**Comment by dbl001** [comment]
I am trying to run Tensorflow 2.5 on an iMac 27" running Big Sur with an AMD Radeon Pro 5700 XT GPU.
I followed these installation instructions:

https://developer.apple.com/metal/tensorflow-plugin/

The error occurs when I try to import tensorflow from ipython in my tensorflow-metal virtual environment.

```
(base) davidlaxer@x86_64-apple-darwin13 ~ % source ~/tensorflow-metal/bin/activate
(tensorflow-metal) (base) davidlaxer@x86_64-apple-darwin13 ~ % conda list tensorflow
# packages in environment at /Users/davidlaxer/anaconda3:
#
# Name                    Version                   Build  Channel
mesh-tensorflow           0.1.19                   pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-metadata       1.0.0                    pypi_0    pypi
tensorflow-text           2.5.0rc0                 pypi_0    pypi
(tensorflow-metal) (base) davidlaxer@x86_64-apple-darwin13 ~ % ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-d6579f534729> in <module>
----> 1 import tensorflow

~/tensorflow-metal/lib/python3.8/site-packages/tensorflow/__init__.py in <module>
    447     _plugin_dir = _os.path.join(_s, 'tensorflow-plugins')
    448     if _os.path.exists(_plugin_dir):
--> 449       _ll.load_library(_plugin_dir)
    450       # Load Pluggable Device Library
    451       _ll.load_pluggable_device_library(_plugin_dir)

~/tensorflow-metal/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py in load_library(library_location)
    152 
    153     for lib in kernel_libraries:
--> 154       py_tf.TF_LoadLibrary(lib)
    155 
    156   else:

NotFoundError: dlopen(/Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 6): Symbol not found: _TF_AssignUpdateVariable
  Referenced from: /Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/tensorflow-plugins/libmetal_plugin.dylib
  Expected in: flat namespace


```
I am trying to get tensorflow to use the AMD GPU.

**Comment by jvishnuvardhan** [comment]
@dbl001 I have noticed couple of issues related to metal plugin. Unfortunately, we don't have any control. Please post them in [Apple Developer Forum](https://developer.apple.com/forums/tags/tensorflow-metal). Thanks!

**Comment by dbl001** [comment]
There are many issues in building tensor flow (e.g.compiler as well as building wheels, missing components (e.g. tensorflow-text), tensor flow-profile doesn’t work, training models runs into memory issues causing the kernel stops the process (e.g. ru_maxss), I’ve posted on GitHub, StackOverflow as well as Apple Developer Forum, but  haven’t gotten any resolutions.

**Comment by jvishnuvardhan** [comment]
@dbl001 Sorry to hear that but unfortunately we don't have any control on the plugin and don't have access to that hardware.  As of now there is no support but that can change in future. Thanks!

**Comment by JayanthBobbili** [comment]
I'm facing similar issue please help me out!!!!

**Comment by dbl001** [comment]
What's your environment?  Did you install Tensorflow-macos and tensorflow-metal as per these instructions?

https://developer.apple.com/metal/tensorflow-plugin/
