### ISSUE TITLE
The ball in “hello world” can only achieve a quarter cycle

### ISSUE THREAD

**Issue by elimsjxr** [tensorflow/tensorflow#50540]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux ubuntu 18.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: STM32F746
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:2.3.0
-   **Python version**:3.8
-   **Exact command to reproduce**:

### Describe the problem
I have followed readme.txt to deploy to STM32F746 with https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world
When I finished the whole process, the animation on the screen can only show a quarter cycle of sine?
### Source code / logs
Here is the screenshot of compiling
![微信图片_20210630213910](https://user-images.githubusercontent.com/52616905/123970379-a6911500-d9eb-11eb-9c63-2682b87c6439.jpg)

**Comment by sachinprasadhs** [comment]
Tflite Micro code has been migrated to a separate repository and the link which you have mentioned above is broken.
Could you please try the same example from here https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/hello_world with the latest Tensorflow version and let us know the outcome. Thanks!
