### ISSUE TITLE
tf.data Service Dispatcher/ Worker behaviour

### ISSUE THREAD

**Issue by TerenceHernandez** [tensorflow/tensorflow#50542]
## Tensorflow Version
TF v2.5.0

## URL(s) with the issue:

1. https://github.com/tensorflow/community/blob/master/rfcs/20200113-tf-data-service.md
2. https://www.tensorflow.org/api_docs/python/tf/data/experimental/service/distribute
3. https://www.tensorflow.org/api_docs/python/tf/data/experimental/service/from_dataset_id 

## Description

Hello, I'm trying to use tf.data.experimental.service to offload pre-processing into Compute Servers alongside my training jobs. I am also using [Horovod](https://github.com/horovod/horovod) as my distributed ML framework, so I will be referring to `worker_index` as `rank`.

I'm a little confused with the documentation. I understand that this was originally a contribution from the community so document (1) might not be up-to-date to the implementation supported by Tensorflow.

My understanding is as follows:
1. Datasets are registered into a DispatcherServer
2. A job is created by a training process to consume the dataset
3. The dataset is distributed across the Workers based on the distribution strategy

My questions follow:

1. Are jobs autonomously run on the Workers i.e. batches are autonomously computed, and stored by the Worker in-memory. Or are they only computed per request from dataset.apply(distribute()), which is called per training step/iteration?

2. When using `register_dataset()` and `from_dataset_id()` instead of `distribute()`, from my understanding we can use the dataset across multiple training processes from the same training job. In this case, one process would be in charge of registering the dataset and the others could simply retrieve elements using from_dataset_id(). In this way each process receives a partition of the dataset through one full sweep. Why is the parameter `processing_mode` in from_dataset_id() instead of register_dataset() in this case? Does this mean that each training process will process the dataset independently, and hence receive all of the dataset?

3. What is the difference between the `job_name` that links datasets to actual jobs in tf.data service and using `register_dataset()` and `from_dataset_id()`. Implementation wise, what's the difference between these two options in pseudocode:

### Option 1
``` python
# Input pipeline of ALL training processes
dataset = dataset.map(foo)
                 .batch(mini_batch_size)
                 .apply(tf.data.experimental.service.distribute(
                        service=dispatcher_address,
                        job_name="job1"
                  ))
                 .prefetch()
model.fit(dataset)
```
### Option 2
``` python
# Input pipeline of training process with index 0
dataset = dataset.map(foo)
                 .batch(mini_batch_size)
dataset_id = dataset.register_dataset(
                                        service=dispatcher_address
                                        dataset=dataset
                                   )
dataset = tf.data.experimental.service.from_dataset_id(
                           processing_mode="parallel_epochs",
                           service=dispatcher_string,
                           dataset_id=dataset_id,
                           element_spec=dataset.element_spec)
dataset = dataset.prefetch()
model.fit(dataset)
                           
# Input pipeline of training process with index 1 to n
# Assume we get dataset_id and element_spec from somewhere
dataset = tf.data.experimental.service.from_dataset_id(
                           processing_mode="parallel_epochs",
                           service=dispatcher_string,
                           dataset_id=dataset_id,
                           element_spec=element_spec)
dataset = dataset.prefetch()
model.fit(dataset)
```

4. What's the path for a data element once it is produced? Worker -> Dispatcher -> training process? Worker -> training process? I am assuming the latter

5. From document (2), does this imply the memory used on the training process side or the Worker side?
> **max_outstanding_requests**
(Optional.) A limit on how many elements may be requested at the same time. You can use this option to control the amount of memory used, since distribute won't use more than element_size * max_outstanding_requests of memory.

6. Is there a way to share pre-processing across simultaneous independent training jobs with tf.data service ?

**Comment by aaudiber** [comment]
Hi @TerenceHernandez, these are great questions! I have added my responses inline.

> My understanding is as follows:
> 
> 1. Datasets are registered into a DispatcherServer
> 2. A job is created by a training process to consume the dataset
> 3. The dataset is distributed across the Workers based on the distribution strategy

I would just tweak the above to say the dataset is distributed across the Workers based on the **processing mode**

> 1. Are jobs autonomously run on the Workers i.e. batches are autonomously computed, and stored by the Worker in-memory. Or are they only computed per request from dataset.apply(distribute()), which is called per training step/iteration?

Workers buffer a number of batches asynchronously so that the data is ready as soon as it is requested.

> 2. When using `register_dataset()` and `from_dataset_id()` instead of `distribute()`, from my understanding we can use the dataset across multiple training processes from the same training job. In this case, one process would be in charge of registering the dataset and the others could simply retrieve elements using from_dataset_id(). In this way each process receives a partition of the dataset through one full sweep. Why is the parameter `processing_mode` in from_dataset_id() instead of register_dataset() in this case? Does this mean that each training process will process the dataset independently, and hence receive all of the dataset?

The `register_dataset`/`from_dataset_id` lets you create a dataset once, register it, then consume from the dataset with multiple processes. It is functionally equivalent to constructing the same dataset in every process and then calling `apply(distribute(...))` on that dataset. Using `register_dataset`/`from_dataset_id` makes it more explicit that all the processes are reading from the same dataset.

The data that each worker receives is controlled by `job_name` and `processing_mode`. The data produced by a job is determined by the processing_mode. Processes which use the same `job_name` will consume from the same job. To partition a dataset across the training processes, you could set `processing_mode="distributed_epoch"` and set the same `job_name` for all training processes.

> 3. What is the difference between the `job_name` that links datasets to actual jobs in tf.data service and using `register_dataset()` and `from_dataset_id()`. Implementation wise, what's the difference between these two options in pseudocode:

The second option doesn't set a `job_name`, so each process will iterate through the dataset independently. The options would be equivalent if you passed `job_name="job1"` to the calls to `from_dataset_id`.

> 4. What's the path for a data element once it is produced? Worker -> Dispatcher -> training process? Worker -> training process? I am assuming the latter

Yes, the data goes directly from Worker to training process. Otherwise the dispatcher quickly becomes a bottleneck.

> 5. From document (2), does this imply the memory used on the training process side or the Worker side?
> 
> > **max_outstanding_requests**
> > (Optional.) A limit on how many elements may be requested at the same time. You can use this option to control the amount of memory used, since distribute won't use more than element_size * max_outstanding_requests of memory.

This is memory on the training process side.

> 6. Is there a way to share pre-processing across simultaneous independent training jobs with tf.data service ?

Not currently, but this is a direction we are exploring!
