### ISSUE TITLE
`Failed to convert a NumPy array to a Tensor (Unsupported object type dict).`

### ISSUE THREAD

**Issue by mathshangw** [tensorflow/tensorflow#50549]
`history = model.fit_generator(train_generator, epochs=epochs, steps_per_epoch=train_steps, verbose=1, callbacks=[checkpoint], validation_data=val_generator, validation_steps=val_steps)`

`def create_sequences(tokenizer, max_length, desc_list, photo, vocab_size):`
` X1, X2, y = list(), list(), list()`
` for desc in desc_list:`
`seq = tokenizer.texts_to_sequences([desc])[0]`
` for i in range(1, len(seq)):`
`in_seq, out_seq = seq[:i], seq[i] in_seq = pad_sequences([in_seq], maxlen=max_length)[0]`
` out_seq = to_categorical([out_seq], num_classes=vocab_size)[0]`
` X1.append(photo)`
` X2.append(in_seq)`
` y.append(out_seq)`
` return array(X1), array(X2), array(y)`

`def data_generator(descriptions, photos, tokenizer, max_length, imgsIds, vocab_size):`
`while 1:`
` for ind in range(len(imgsIds)): `
`photo = photos[ind]`
` key = imgsIds[ind]`
` desc_list = descriptions[str(key)] `
`in_img, in_seq, out_word = create_sequences( tokenizer, max_length, desc_list, photo, vocab_size)`
` yield [in_img, in_seq], out_word`

i got

`Failed to convert a NumPy array to a Tensor (Unsupported object type dict).`
if there is anything i should add it please comment … Thanks

`Traceback (most recent call last): File "fit.py", line 271, in <module> main(sys.argv) File "fit.py", line 268, in main fit_model(train, train_descriptions, train_rnn_input, val, val_descriptions, val_rnn_input) File "fit.py", line 255, in fit_model history = model.fit_generator(train_generator, epochs=epochs, steps_per_epoch=train_steps, verbose=1, callbacks=[checkpoint], validation_data=val_generator, validation_steps=val_steps) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func return func(*args, **kwargs) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1479, in fit_generator initial_epoch=initial_epoch) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper return method(self, *args, **kwargs) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 872, in fit return_dict=True) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper return method(self, *args, **kwargs) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1057, in evaluate model=self) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1112, in __init__ model=model) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 775, in __init__ peek = _process_tensorlike(peek) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1013, in _process_tensorlike inputs = nest.map_structure(_convert_numpy_and_scipy, inputs) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 617, in map_structure structure[0], [func(*x) for x in entries], File "/path/.local/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 617, in <listcomp> structure[0], [func(*x) for x in entries], File "/path/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1008, in _convert_numpy_and_scipy return ops.convert_to_tensor(x, dtype=dtype) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function return constant_op.constant(value, dtype, name=name) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant allow_broadcast=True) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl t = convert_to_eager_tensor(value, ctx, dtype) File "/path/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor return ops.EagerTensor(value, ctx.device_name, dtype) ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type dict). 2021-06-27 04:46:22.936001: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated. [[{{node PyFunc}}]]`

**Comment by saikumarchalla** [comment]
Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by namaannn** [comment]
I can do it using np.asarray(variable_name),np.expand_dims(variable_name,axis)
@saikumarchalla kindly  assign me this

**Comment by saikumarchalla** [comment]
@namaannn  We should not assign this issue  but you can comment the answer/ workaround here.Thanks!

**Comment by namaannn** [comment]
Sorry sir, but can you tell why you can't assign me this issue?

**Comment by mathshangw** [comment]
thanks for your replying , i solved it . the problem was in my arrays i passed it was in dict form not array structure
