### ISSUE TITLE
graph simplifications examples

### ISSUE THREAD

**Issue by TaeheeJeong** [tensorflow/tensorflow#50546]
I saw Tatiana Shpeisman's presentation about TF graph optimization at Stanford.

I want to simplify a frozen graph (tf 1.x) from pb.file

Do you have any end-to-end example on how to simplify a TF frozen graph?

For example, using tensorflow.python.grappler.tf_optimizer or  tf.config.optimizer.get_experimental_options?

When I contacted to Tatiana Shpeisman(shpeisman@google.com), she encouraged to post this request here.

Thanks

Taehee

**Comment by UsharaniPagadala** [comment]
@TaeheeJeong 

Could you please refer this [document](https://www.tensorflow.org/guide/graph_optimization) and [TFGraphOptimizationsStanford](http://web.stanford.edu/class/cs245/slides/TFGraphOptimizationsStanford.pdf),hope it helps.

Please upgrade to tf2.x ,as there is no active support for tf1.x. Thanks

**Comment by TaeheeJeong** [comment]
Hello Usharani

I already reviewed the linked files.

However, it is not clear for me how to simplify the frozen graph.

Because of that, I posted the request.

Could you provide end-to-end examples on how to simplify the frozen graph?

Thanks

Regards,

Taehee

**Comment by UsharaniPagadala** [comment]
@TaeheeJeong 

Could you please refer this [blog,](https://towardsdatascience.com/freezing-a-keras-model-c2e26cb84a38) hope it helps.Thanks

**Comment by TaeheeJeong** [comment]
Hello Usharani

The blog seems interesting.

I will check it in detail.

Thanks

Taehee

**Comment by UsharaniPagadala** [comment]
@TaeheeJeong 

Thank you for your update, glad it is useful for you, kindly move this issue to closed status as it is resolved.
