### ISSUE TITLE
Fail to use custom trained model on developing mobile app

### ISSUE THREAD

**Issue by azziqshmsdn** [tensorflow/tensorflow#50559]
## URL(s) with the issue:

https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

Have been downloaded the official example of object detection mobile app for android and have been run successfully. But when I replaced it with my custom trained model using SSD MobileNet V2 FPNLite 320x320, the app does not manage to start. I've been following the guide to change the .tflite and labelmap.txt and even set the quantized to false.

**Comment by thaink** [comment]
Please follow the issue template and provide logs.

**Comment by tilakrayal** [comment]
@azziqshmsdn ,

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.
