### ISSUE TITLE
Trying to install tensorflow==2.0.3 with bazel on google app engine wont work 

### ISSUE THREAD

**Issue by berhanpolat** [tensorflow/tensorflow#50557]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu Google App Engine

- TensorFlow installed from (source or binary):
- TensorFlow version: 2.0.3
- Python version: 3x
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): latest from google app engine deploy bazel
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: google app engine

**Describe the problem**

I have followed the exact commands from: https://www.tensorflow.org/install/source

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by berhanpolat** [comment]
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled 

the error I am receiving

**Comment by berhanpolat** [comment]
I have tried all the other solutions from other github issues, none has worked for me.

**Comment by berhanpolat** [comment]
I have deployed bazel through google click to deploy containers bazel and later followed the instructions here in command shell: https://www.tensorflow.org/install/source

I am using flex environment and just trying to reproduce a simple app that I have deployed with google cloud deploy but with better performance than on my computer

**Comment by UsharaniPagadala** [comment]
@berhanpolat 

 We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version,cuda and cudnn versions like that and steps followed before you ran into this error .Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md). Thanks

**Comment by berhanpolat** [comment]
> @berhanpolat
> 
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version,cuda and cudnn versions like that and steps followed before you ran into this error .Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md). Thanks

I have filled the info. Now I am trying to build tensorflow with CPU instead of GPU and it says 26617 targets configured, it seems that it will take hours. I am doing something wrong, I guess.

**Comment by UsharaniPagadala** [comment]
@berhanpolat 

Is there any specific reason to install tf2.0 instead of latest stable Tensoflow(2.5) version.

also look at the similar [issue](https://github.com/tensorflow/tensorflow/issues/34707) and let  us know if it helps.Thanks

**Comment by berhanpolat** [comment]
I have managed torun my app with the latest tensorflow version in python. However it takes 10 sec for my mac to compute. I want to deploy my app to google app engine with bazel so that it computes sentence encoder multilingual under 1 second. Is there a way to manage this easily?

Thank you for your help!

Kind regards

Berhan Polat

**Comment by UsharaniPagadala** [comment]
@berhanpolat 

As per the documentation there is no GPU support for macOS. For more info please refer this [documentation](https://www.tensorflow.org/install/source#install_bazel).Thanks

**Comment by berhanpolat** [comment]
I have tried this documentation. To install tensorflow with bazel it takes hours to install it locally and gives errors at the end.

I actually want to deploy my app to google engine and build tensorflow with bazel. I have also tried this but does not work. It takes too long and gives errors too.

Any methods to suggest?

**Comment by Saduf2019** [comment]
@berhanpolat 
Please refer to [this link](https://stackoverflow.com/questions/34562557/can-i-use-tensorflow-in-a-google-app-engine-module) and let us know.

**Comment by berhanpolat** [comment]
Hello

Sorry for my late answer, I was in vacation. I was trying from the beginning with flexible instances. The issue that is mentioned has been brought up 6 years ago. My problem is still not solved and issue persists. I find it weird that google does not make its own resources ready to use for gcloud applications, although so many people use them. 

It is close to impossible to install tensorflow with bazel in google app engine. This was my issue and the mentioned issue is not similar to mine.

Thank you for your help so far. 

Kind regards

Berhan Polat
