### ISSUE TITLE
XLA Operation Semantics documentation has self-conflict

### ISSUE THREAD

**Issue by junqinyang** [tensorflow/tensorflow#50558]
## URL(s) with the issue:

https://www.tensorflow.org/xla/operation_semantics#slice

### Clear description
the number of parameters are not match.
![image](https://user-images.githubusercontent.com/22614078/124128517-74e18200-daaf-11eb-9a91-5007d4dee8b0.png)

**Comment by Cheril311** [comment]
Hey, stride is an optional argument here, it can be used if you want to slice your array with some step-gaps

**Comment by chunduriv** [comment]
@junqinyang, Sorry for the late response. 

Thank you for reporting the bug. PR has been submitted internally on successful merge this issue will be closed automatically.
