### ISSUE TITLE
mbed compile -m DISCO_F746NG -t GCC_ARM error: mbed error: /usr/bin/python3 returned error

### ISSUE THREAD

**Issue by elimsjxr** [tensorflow/tensorflow#50555]
**System information**
- OS Platform and Distribution:Linux ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: STM32F746G
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.3.0
- Python version:3.8
- Installed using virtualenv? pip? conda?:pip
- GCC/Compiler version (if compiling from source):

**Describe the problem**
When I followed this project https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world#deploy-to-STM32F746
After I finished the whole process, it was successful, but when I run this command(in readme.txt) to use C++11 
‘’’’’’’
python3 -c ‘import fileinput, glob;
for filename in glob.glob(“mbed-os/tools/profiles/*.json”):
for line in fileinput.input(filename, inplace=True):
print(line.replace(""-std=gnu++98"",""-std=c++11", “-fpermissive”"))’

‘’’’’’

**Any other info / logs**
The error shows below:

    [mbed] Working path “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed” (library)
    [mbed] Program path “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed”
    WARNING: MBED_ARM_PATH set as environment variable but doesn’t exist
    Traceback (most recent call last):
    File “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/mbed-os/tools/make.py”, line 421, in
    main()
    File “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/mbed-os/tools/make.py”, line 354, in main
    build_profile=extract_profile(parser, options, internal_tc_name),
    File “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/mbed-os/tools/options.py”, line 128, in extract_profile
    contents = load(open(filename))
    File “/usr/lib/python3.8/json/init.py”, line 293, in load
    return loads(fp.read(),
    File “/usr/lib/python3.8/json/init.py”, line 357, in loads
    return _default_decoder.decode(s)
    File “/usr/lib/python3.8/json/decoder.py”, line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File “/usr/lib/python3.8/json/decoder.py”, line 355, in raw_decode
    raise JSONDecodeError(“Expecting value”, s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    [mbed] ERROR: “/usr/bin/python3” returned error.
    Code: 1
    Path: “~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed”
    Command: “/usr/bin/python3 -u ~/tensorflow/tensorflow/lite/micro/tools/make/gen/disco_f746ng_cortex-m4_default/prj/hello_world/mbed/mbed-os/tools/make.py -t GCC_ARM -m DISCO_F746NG --source . --build ./BUILD/DISCO_F746NG/GCC_ARM”
    Tip: You could retry the last command with “-v” flag for verbose output

**Comment by mohantym** [comment]
Hi @elimsjxr !

Currently tflite-micro issues are being addressed here[ tflite-micro](https://github.com/tensorflow/tflite-micro) repo.

Feel free to test the examples from [tflite-micro ](https://github.com/tensorflow/tflite-micro)to see the difference and report in the same repo if you need further assistance. 

Thank you!
