### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property styleTransferModelExecutor

### ISSUE THREAD

**Issue by ouclbc** [tensorflow/tensorflow#50556]
System information

Android 9 
Mobile device :One plus 8
when launcher google style transfer demo,it show Force close issue

07-01 16:32:53.894  5715  5715 E AndroidRuntime: FATAL EXCEPTION: main
07-01 16:32:53.894  5715  5715 E AndroidRuntime: Process: org.tensorflow.lite.examples.styletransfersample, PID: 5715
07-01 16:32:53.894  5715  5715 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property styleTransferModelExecutor has not been initialized
07-01 16:32:53.894  5715  5715 E AndroidRuntime:        at org.tensorflow.lite.examples.styletransfer.MainActivity.startRunningModel(MainActivity.kt:320)

**Comment by tilakrayal** [comment]
@ouclbc ,

Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also  in order to expedite the trouble-shooting process, could you please provide complete code and the TensorFlow version you are using.Thanks!
