### ISSUE TITLE
Protobuf incompatible with google-cloud-python?

### ISSUE THREAD

**Issue by wakahiu** [tensorflow/tensorflow#5056]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
- [Tensoflow Installation from source README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources)
- [Old google-cloud-sdk question of code.google.com](https://code.google.com/p/google-cloud-sdk/issues/detail?id=24
)

### Environment info
Ubuntu 14.04

### Installed version of CUDA and cuDNN: 
Cuda Toolkit 7.5 and cuDNN v5

### pip packages installed from source, provide 

https://google-cloud-python.readthedocs.io/en/stable/#

```
$ git clone git://github.com/GoogleCloudPlatform/google-cloud-python.git
$ cd google-cloud-python
$ python setup.py install
```

Tensorflow source
1. The commit hash (`git rev-parse HEAD`): 
```
2ed280b4f553e6aa1c7fe0bb41d52456a0ae452c
```
2. The output of `bazel version`
```
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Trying to import google.cloud
```
python -c "from google.cloud import logging as gclogging;"
```
results in the following error
```
ImportError: No module named cloud
```
### What other attempted solutions have you tried?
Whenever I install google protobuf using either of the following commands
```
sudo pip install /tmp/tensorflow_pkg/tensorflow-0.11.0rc0-py2-none-any.whl
# OR
pip install dist/<wheel file name>
```

I can no longer import google.cloud. 

### Logs or other output that would be helpful
I'm aware of the fact that you can build TensorFlow with Google Cloud Platform support comes with integration when running  ``./configure``. Howoever it's not clear how to integrate with Google Stackdriver.

**Comment by asimshankar** [comment]
Could you please fill in the answers to the template and also describe the problem a bit more. From what you've listed ("Protobuf incompatible with google-cloud-python"), I'm unable to figure out what your precise question is. Did you observe some incompatibility? What was the error?

**Comment by wakahiu** [comment]
Hi @asimshankar. Sorry, you posted this while I was still working on the question. Perhaps we can loop in the folks from google-cloud-python?

**Comment by asimshankar** [comment]
A few things:

(a) You mention "google protobuf", but it seems you're talking about TensorFlow and not protobuf? Or is there something about protobuf that I'm missing?

(b) Does `python -c "from google.cloud import logging as gclogging;"` succeed if you do not install TensorFlow?

(c) I'm not sure how source installations interact, but can you `pip install google-cloud` (from https://google-cloud-python.readthedocs.io/en/stable/#) instead of installing `google-cloud` from sources. Does that work?

**Comment by wakahiu** [comment]
TensorFlow pip package depends on protobuf pip package version 3.1.0 according to the [installation guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#installing-from-sources). In the **common problems** section.

> Protobuf's pip package downloaded from PyPI (when running pip install protobuf) is a Python only library, that has Python implementations of proto serialization/deserialization which can be 10x-50x slower than the C++ implementation. 

So essentially, the protobuf that comes with PyPI is slow and a c++ based one is much faster.

Yeah, `python -c "from google.cloud import logging as gclogging;"` succeeds if I don't install Protobuf with either the following command line
```
$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.11.0rc0-py2-none-any.whl
# OR
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp27-none-linux_x86_64.whl
# OR
pip install dist/protobuf-3.1.0-cp27-cp27mu-linux_x86_64.whl
```

**Comment by wakahiu** [comment]
This issue was referenced and solved here
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2563
