### ISSUE TITLE
build fails on AArch64, Fedora 33 due to --config=numa, missing sysctl.h

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [tensorflow/tensorflow#50574]
[jw@cn05 master]$ bazel --output_user_root=/tmp/bazel build --local_ram_resources=6144 --config=numa //tensorflow/tools/pip_package:build_pip_package --verbose_failures
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from /data/jw/tensorflow/master/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /data/jw/tensorflow/master/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /data/jw/tensorflow/master/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3.9/site-packages --python_path=/usr/bin/python3
INFO: Found applicable config definition build:short_logs in file /data/jw/tensorflow/master/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /data/jw/tensorflow/master/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:numa in file /data/jw/tensorflow/master/.bazelrc: --define=with_numa_support=true
INFO: Found applicable config definition build:linux in file /data/jw/tensorflow/master/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /data/jw/tensorflow/master/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /tmp/bazel/b636c1968d8e13825d4613e0f3304062/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /tmp/bazel/b636c1968d8e13825d4613e0f3304062/external/hwloc/BUILD.bazel:229:11: C++ compilation of rule '@hwloc//:hwloc' failed (Exit 1): gcc failed: error executing command
  (cd /tmp/bazel/b636c1968d8e13825d4613e0f3304062/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/FJSVstclanga/default/lib64:/opt/FJSVstclanga/default/lib64: \
    PATH=/home/jw/c4aarch64_installer/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/home/jw/.sdkman/candidates/gradle/current/bin:/opt/FJSVstclanga/default/bin:/usr/lib64/qt-3.3/bin:/usr/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.composer/vendor/bin:/home/jw/.dotnet/tools:/var/lib/snapd/snap/bin:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
  /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.o' -iquoteexternal/hwloc -iquotebazel-out/aarch64-opt/bin/external/hwloc -isystem external/hwloc/hwloc -isystem bazel-out/aarch64-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/aarch64-opt/bin/external/hwloc/include -w -DAUTOLOAD_DYNAMIC_KERNELS -I. -Ihwloc -Iinclude -Wno-vla '-DHWLOC_DUMPED_HWDATA_DIR=' '-DRUNSTATEDIR=' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/hwloc/hwloc/topology.c -o bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.o)
Execution platform: @local_execution_config_platform//:platform
external/hwloc/hwloc/topology.c:45:10: fatal error: sys/sysctl.h: No such file or directory
   45 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /data/jw/tensorflow/master/tensorflow/lite/toco/python/BUILD:89:10 C++ compilation of rule '@hwloc//:hwloc' failed (Exit 1): gcc failed: error executing command
  (cd /tmp/bazel/b636c1968d8e13825d4613e0f3304062/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/FJSVstclanga/default/lib64:/opt/FJSVstclanga/default/lib64: \
    PATH=/home/jw/c4aarch64_installer/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/home/jw/.sdkman/candidates/gradle/current/bin:/opt/FJSVstclanga/default/bin:/usr/lib64/qt-3.3/bin:/usr/condabin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jw/.composer/vendor/bin:/home/jw/.dotnet/tools:/var/lib/snapd/snap/bin:/opt/FJSVstclanga/default/bin:/home/jw/.local/bin:/home/jw/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
  /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.o' -iquoteexternal/hwloc -iquotebazel-out/aarch64-opt/bin/external/hwloc -isystem external/hwloc/hwloc -isystem bazel-out/aarch64-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/aarch64-opt/bin/external/hwloc/include -w -DAUTOLOAD_DYNAMIC_KERNELS -I. -Ihwloc -Iinclude -Wno-vla '-DHWLOC_DUMPED_HWDATA_DIR=' '-DRUNSTATEDIR=' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/hwloc/hwloc/topology.c -o bazel-out/aarch64-opt/bin/external/hwloc/_objs/hwloc/topology.o)
Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 3.058s, Critical Path: 0.74s
INFO: 98 processes: 49 internal, 49 local.
FAILED: Build did NOT complete successfully
[jw@cn05 master]$ 

Cf. issue #104801, which refers also to #45861.

**Comment by UsharaniPagadala** [comment]
@LutzWeischerFujitsu 

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error].

**Comment by LutzWeischerFujitsu** [comment]
Fedora 33
A64FX
source code, (recent) master
Python 3.9.5
no virtualenv, standard pip, conda
bazel 3.7.2- (@non-git), compiled from source 
gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
no CUDA
no GPU

./configure, standard answers

**Comment by coderforlife** [comment]
Also getting this with the following command line (but with config set up with CUDA)

```
TMP=/tmp bazel build --jobs 12 -c opt --config=opt --config=v2 --config=mkl --config=numa     ... //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

Compiling on Fedora 34 with CUDA. Commenting out the line mentioned in #45861 fixes the issue.

**Comment by NeoZhangJianyu** [comment]
@utzWeischerFujitsu 
In your case, have you set "--config=mkl" in the build cmd?

**Comment by NeoZhangJianyu** [comment]
@coderforlife 
In your case, there is error of the build setting:
  CUDA and "--config=mkl" can't be present in same time. 
  There is conflict of them in code path to implement the same OPs (like Conv2d). The result is unknown.

Please keep one of them in your build setting.

**Comment by LutzWeischerFujitsu** [comment]
Just noticed that ./configure already sets numa + mkl.

**Comment by NeoZhangJianyu** [comment]
@LutzWeischerFujitsu 

I see you are using Fedora 33 which includes glibc version 2.3 as default.
But glibc 2.3 has removed sys/sysctl.h.

Could you try glibc 2.2?

Thank you!
