### ISSUE TITLE
add multiple classifications  without network

### ISSUE THREAD

**Issue by xzy-666** [tensorflow/tensorflow#50576]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):arm-linux
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):tensorflow1.13.0
hello!
Users don't understand any code, and they may be in a environment without network. I'm using the classification algorithm model.How can users add multiple categories to the usage model? In addition, in model deployment, I use C + + to deploy the tflite model. What do I need to do on the tflite model node, hoping to give me a little idea?

**Comment by tilakrayal** [comment]
@xzy-666 ,

We see that you are using tf version 1.13, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.Thanks!

**Comment by xzy-666** [comment]
hello, @tilakrayal 
Personally, I think my question has little to do with tensorflow. It is more about forward reasoning.Thanks!

**Comment by thaink** [comment]
An example to run tflite with C++ API is here: https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter
