### ISSUE TITLE
[Colab TPU] [TF 2.5]  UnavailableError: Socket closed

### ISSUE THREAD

**Issue by FalsoMoralista** [tensorflow/tensorflow#50583]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  - Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  - Google Colab  enviroment
- TensorFlow version (use command below):
 - 2.5
- Python version:
  - 3.7.10

### Context: 
My model was training ok untill a certain number of steps then throwing the error mentioned in issue #50522 which i then came to realize that it was related to the in my tfrecord files causing different batch output sizes. As an attempt to fix it, i adapted the code to run with a dinamic batch size by using  ```tf.shape(x)```.  Coincidentally (or not) when trying to perform training the error ```UnavailableError: Socket closed``` began showing up.  After further research, as pointed by the [doc](https://cloud.google.com/tpu/docs/troubleshooting#dynamic_shapes_not_supported) i removed back the tf.shape op and added ```drop_remainder=True``` to my dataset.batch config. Despite that the error persisted, although after enabling drop_remainder the code was identical to the previous working version.

Obs: Dropping remainders and tf.shape were added as an attempt to deal with batch lenght different than the original configuration, as the data needs to be properly reshaped accordingly to the length of the augmented batch and the batch_size varies accordingly to the number of samples within my tfrecords that are not multiples. 

Code: 
```python

def train_model(train_path, validation_path, buffer_size, epochs, steps_per_epoch, model):
  data_augmentation = preprocessing_model()

  train_filenames = get_filenamesTPU(train_path)
  random.shuffle(train_filenames)

  validation_filenames = get_filenamesTPU(validation_path)
  random.shuffle(validation_filenames)

  dataset_length = 91758  
  train_size =  dataset_length * 0.7
  validation_size = dataset_length - train_size

  batch_size = 42 * tpu_strategy.num_replicas_in_sync

  shape = 32 * batch_size

  data_reshape = lambda x,y: (tf.reshape(x,shape=(shape,224,224,3)), (tf.reshape(y[0],shape=(shape,1000)), tf.reshape(y[1],shape=(shape,516)),tf.reshape(y[2],shape=(shape,124))))
  
  augmentation_pipeline = lambda x,y: (data_augmentation(tf.expand_dims(x,axis=0)),(tf.tile(tf.reshape(y[0],[1,1000]),[32,1]),tf.tile(tf.reshape(y[1],[1,516]),[32,1]),tf.tile(tf.reshape(y[2],[1,124]),[32,1]))) # apply augment then tile the labels to the correct length
  
  AUTO = tf.data.AUTOTUNE
  train_dataset = tf.data.TFRecordDataset(buffer_size=int(1e+8),num_parallel_reads=AUTO,filenames=train_filenames).map(parsing_fn,num_parallel_calls=AUTO).shuffle(buffer_size=buffer_size, reshuffle_each_iteration=True)
  train_dataset = train_dataset.map(augmentation_pipeline, num_parallel_calls=AUTO).batch(batch_size=batch_size, drop_remainder=True)
  train_dataset = train_dataset.map(data_reshape,num_parallel_calls=AUTO)
  train_dataset = train_dataset.repeat()
  train_dataset = train_dataset.prefetch(AUTO)
 
  # Create a validation dataset
  validation_dataset = tf.data.TFRecordDataset(num_parallel_reads=AUTO,filenames=validation_filenames).map(parsing_fn,num_parallel_calls=AUTO)
  validation_dataset = validation_dataset.batch(batch_size)
  validation_dataset = validation_dataset.prefetch(AUTO)
  validation_dataset = validation_dataset.repeat(1)

  validation_steps = validation_size / batch_size 
  history = model.fit(x=train_dataset,
                          epochs=epochs,
                          steps_per_epoch=steps_per_epoch,                        
                          validation_data=validation_dataset,
                          validation_steps=validation_steps)
  return history
```
### Perform training
```python
loss={
        "class_0": 'CategoricalCrossentropy',
        "class_1": 'CategoricalCrossentropy',
        "class2": 'CategoricalCrossentropy',
},

metrics = ['categorical_accuracy']
optimizer = Adam(learning_rate=5e-3)

weight_file = None
with tpu_strategy.scope():
  resnet_50V2 = load_and_configure_model(optimizer, loss, metrics, weight_file)
resnet_50V2 = load_and_configure_model(optimizer, loss, metrics, weight_file)
base_directory = 'gs://2015_tfrecords'

train_path = base_directory+'/train/'
validation_path = base_directory+'/validation/'

buffer_size = 10240
epochs = 30
steps_per_epoch = 192

resnet_50V2.summary()
history = train_model(train_path, validation_path, buffer_size, epochs, steps_per_epoch, resnet_50V2)
plot_training_history3(history)
```

### Error
```
==================================================================================================
Total params: 26,925,160
Trainable params: 7,825,000
Non-trainable params: 19,100,160
__________________________________________________________________________________________________
Epoch 1/30

---------------------------------------------------------------------------

UnavailableError                          Traceback (most recent call last)

<ipython-input-48-3332ce7f2ca9> in <module>()
      4 
      5 resnet_50V2.summary()
----> 6 history = train_model(train_path, validation_path, buffer_size, epochs, steps_per_epoch, resnet_50V2)
      7 plot_training_history3(history)
      8 

14 frames

/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

UnavailableError: Socket closed
```

**Comment by UsharaniPagadala** [comment]
@falcondai 

I am facing dependency errors,Could please provide the colab gist with all the required dependencies to analyse the issue.Thanks

**Comment by FalsoMoralista** [comment]
Working on that

**Comment by FalsoMoralista** [comment]
@UsharaniPagadala let me know if there are any permission issues

[gist link](https://colab.research.google.com/drive/1ZTeOA8-2UUqljrqM6G3MblD_D7NZEOhl?usp=sharing)

**Comment by UsharaniPagadala** [comment]
@FalsoMoralista 

Could you refer the similar [issue](https://github.com/tensorflow/tensorflow/issues/36136#issuecomment-627731715),hope it helps.Thanks

**Comment by FalsoMoralista** [comment]
Thank you but I have already checked this issue before. I have experimented with float32 labels as well but nothing happens. The thing is, as i mentioned before, the  same code was working fine on the previous issue that i've opened as you can check (#50522), the differences between that code and this one are: 
- removed augmentation on the validation step 
- set drop_remainder=True

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/76145dd8ea30c2a615bec17d957e227a/colab_gist.ipynb#scrollTo=5-e5xvVyggeZ).Thanks

**Comment by FalsoMoralista** [comment]
Any updates?
