### ISSUE TITLE
W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by suvadityamuk** [tensorflow/tensorflow#50589]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): pip 
- TensorFlow version: 2.5.0
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: pip

- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA GTX 1650Ti 4GB

Upon writing `import tensorflow as tf` in the command prompt-bases python interpreter, it displays the following error

![image](https://user-images.githubusercontent.com/70141886/124354459-bdbd4600-dc29-11eb-9d18-178768bf98d7.png)
![image](https://user-images.githubusercontent.com/70141886/124354446-a8481c00-dc29-11eb-9c96-a7728cfbbc66.png)
![image](https://user-images.githubusercontent.com/70141886/124354485-d75e8d80-dc29-11eb-8e13-724ecd456265.png)
![image](https://user-images.githubusercontent.com/70141886/124354596-6c618680-dc2a-11eb-950a-0fa956682c83.png)

I have even set the 4 PATHs to be set for use

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin`
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp`
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include`
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\extras\CUPTI\lib64`

I have gone through previous issues and other Google links before deciding to come here to create this issue. I have also restarted my computer several times in the hope that the path is updated, if that was the cause of this error. Please let me know how I can fix this problem. Thank you

**Comment by suvadityamuk** [comment]
Is this due to a possible conflict in versions of different packages?

**Comment by djbacad** [comment]
What cuDNN version are you using?  (you only mentioned CUDA)I was having the same problem before and I was able to solve it by installing versions that are suggested by the [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations).

**Comment by suvadityamuk** [comment]
CuDNN version 8.2.1, apparently. Seeing your link, it apparently is not compatible with said version as such. I am currently re-installing all the tools from scratch, and will check after that. Thank you

**Comment by suvadityamuk** [comment]
Nope, does not solve the problem for me.

Current versions :
Tensorflow - 
![image](https://user-images.githubusercontent.com/70141886/124381362-ab9ddf00-dcdf-11eb-838a-e894668a3d2b.png)
Keras - 
![image](https://user-images.githubusercontent.com/70141886/124381368-b5bfdd80-dcdf-11eb-960c-0b4771379d76.png)
CuDNN -
![image](https://user-images.githubusercontent.com/70141886/124381384-d5ef9c80-dcdf-11eb-8db1-ebc646f39b87.png)
CUDA -
![image](https://user-images.githubusercontent.com/70141886/124381389-e7d13f80-dcdf-11eb-983b-607e1221b0df.png)
Python - 3.9
GCC - 
![image](https://user-images.githubusercontent.com/70141886/124381419-118a6680-dce0-11eb-91cf-c5f8a7a7aac9.png)


I have only tried to do some stuff with Python. Could my GCC Version be the problem?

**Comment by djbacad** [comment]
In my understanding, you intend to utilize the GPU support right? Can you try doing `pip show tensorflow-gpu` and show the result? Also,[ guide](https://www.tensorflow.org/install/gpu#windows_setup) here tells that these (sample) are the necessary envi variables to be set:

```
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\lib64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%
```

**Comment by suvadityamuk** [comment]
@djbacad As I read the guides, it said that after Tensorflow 2.5.0, we can simply use 
`pip install tensorflow`.
Due to this, doing pip show tensorflow-gpu just doesn't do anything as such.
Also, all env variables mentioned here have been set. I did that as well, but this problem still crops up.

**Comment by Saduf2019** [comment]
@suvadityamuk 
Can you please refer to [this link ](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install)and let us know.

**Comment by suvadityamuk** [comment]
@Saduf2019 I have tried going through these steps as well. The answer which involved shifting the file to the System32 path did end up working, but it seems to be nothing better than a stop-gap solution as such. Is there a better method to solve this problem once and for all?

**Comment by Saduf2019** [comment]
@suvadityamuk 
You have used pip install hence its working as expected outside the venv, this is not a bug or error it is working as expected.

**Comment by suvadityamuk** [comment]
> @suvadityamuk 
> You have used pip install hence its working as expected outside the venv, this is not a bug or error it is working as expected.

I ran the pip install within the venv, not outside. Is that still supposed to work as such?

**Comment by Saduf2019** [comment]
@suvadityamuk
 Please share the pip list for the venv you are using.

**Comment by suvadityamuk** [comment]
`pip list`
![image](https://user-images.githubusercontent.com/70141886/124460674-4adcd800-ddad-11eb-8071-14ca601c40b5.png)
![image](https://user-images.githubusercontent.com/70141886/124460701-529c7c80-ddad-11eb-8f89-50ff1e801bfa.png)
![image](https://user-images.githubusercontent.com/70141886/124460720-56c89a00-ddad-11eb-8a07-1a58011e38ab.png)
![image](https://user-images.githubusercontent.com/70141886/124460736-5cbe7b00-ddad-11eb-9903-5f07fa7d71b4.png)
![image](https://user-images.githubusercontent.com/70141886/124460754-61832f00-ddad-11eb-97ab-1a17a0db8c7e.png)

**Comment by Saduf2019** [comment]
@suvadityamuk 
Cuda 11.4 is not tested, can you please refer to this link and use tested configurations, i suggest you can try 11.0 or 11.2 and let us know if the problem exist. [https://www.tensorflow.org/install/gpu]

also there seems to be the issue of a corrupted dll file due to which you have to explicitly mention the path in file 32 windows,
you can try rechecking this with a fresh venv install and and a fresh tf latest too. you may try this if the 11.0 does not help.

**Comment by suvadityamuk** [comment]
@Saduf2019 I actually did reinstall Cuda 11.2, but that didn't do me any good as such.
I shall try creating a new venv and checking if this problem persists.

**Comment by Saduf2019** [comment]
@suvadityamuk 

Do you wana try with 11.0 as per [this comment](https://github.com/tensorflow/tensorflow/issues/43174#issuecomment-874019987), though you are using windows

**Comment by suvadityamuk** [comment]
I tried that code snippet and added it to my program, but it did not solve the problem. 
I had previously used CUDA 11.0, but I have reverted back to 11.2 once again.
I got the following trace:
![image](https://user-images.githubusercontent.com/70141886/124553290-31da3280-de52-11eb-8f3d-27f17f32d4e7.png)
![image](https://user-images.githubusercontent.com/70141886/124553325-3a326d80-de52-11eb-86a1-fc0a15105625.png)
