### ISSUE TITLE
(0) Invalid argument:  In[0] mismatch In[1] shape: 

### ISSUE THREAD

**Issue by mathshangw** [tensorflow/tensorflow#50582]
`tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.`
`     (0) Invalid argument:  In[0] mismatch In[1] shape: 1108 vs. 1120: [42,1108] [1120,256] 0 0`
 `   [[node model/dense/MatMul (defined at rnn_flickr_fit.py:273) ]]`
`   (1) Invalid argument:  In[0] mismatch In[1] shape: 1108 vs. 1120: [42,1108] [1120,256] 0 0`
   ` [[node model/dense/MatMul (defined at rnn_flickr_fit.py:273) ]]`
  `  [[Adam/Cast_6/ReadVariableOp/_6]]`
 `   0 successful operations.`
`    0 derived errors ignored. [Op:__inference_train_function_7431]`
    
   ` Function call stack:`
`    train_function -> train_function`
    
 `   2021-07-02 14:23:52.766840: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.`
`    	 [[{{node PyFunc}}]]`

what should i check to solve it 

code is 

`def define_model(vocab_size, max_length, curr_shape):`
 `   inputs1 = Input(shape=curr_shape)`
  `  fe1 = Dropout(0.5)(inputs1)`
   ` fe2 = Dense(256, activation='relu')(fe1)`
    `inputs2 = Input(shape=(max_length,))`
  `  se1 = Embedding(vocab_size, 256, mask_zero=True)(inputs2)`
   ` se2 = Dropout(0.5)(se1)`
   ` se3 = LSTM(256)(se2)`
   ` decoder1 = Concatenate()([fe2, se3])`
    `decoder2 = Dense(256, activation='relu')(decoder1)`
    `outputs = Dense(vocab_size, activation='softmax')(decoder2)`
    `model = Model(inputs=[inputs1, inputs2], outputs=outputs)`
   ` model.compile(loss='categorical_crossentropy', optimizer='adam')`
    `return model`

**Comment by tilakrayal** [comment]
@mathshangw ,

Code shared is full of indentation errors, please share a colab gist with issue reported or complete code with dependencies.Also please share the tensorflow version you are using.Thanks

**Comment by mathshangw** [comment]
`tensorflow          2.5.0`
`tensorflow-gpu                1.15.0`

i tried to write a code and avoid the indentation errors but couldn't .. How can i write it well ?

**Comment by mathshangw** [comment]
is there any help please ?

**Comment by tilakrayal** [comment]
@mathshangw ,

Please refer this [link](https://www.geeksforgeeks.org/indentation-in-python/) for information on indentation.Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, please provide the complete code.Thanks!
