### ISSUE TITLE
Closing as stale. Please reopen if you'd like to work on this further.

### ISSUE THREAD

**Issue by mryusefVahedi01** [tensorflow/tensorflow#50592]
Closing as stale. Please reopen if you'd like to work on this further.

_Originally posted by @google-ml-butler[bot] in https://github.com/tensorflow/tensorflow/issues/49920#issuecomment-873439262_

**Comment by saikumarchalla** [comment]
@mryusefVahedi01  The issue was closed due to the  stalled label and we re-opened the issue now. Thanks!

**Comment by saikumarchalla** [comment]
@mryusefVahedi01  Closing the issue since the original issue was re opened. Thanks!
