### ISSUE TITLE
tensorflow.data.experimental.load not working inside tensorflow.data.Dataset().flatmap

### ISSUE THREAD

**Issue by kurudinesh** [tensorflow/tensorflow#50594]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Google Colab 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: CPU 8GB

**Describe the current behavior** tensorflow.data.experimental.load should return dataset when called from inside Dataset.interleave's map_function.

**Describe the expected behavior** Throwing error 'TypeError: expected str, bytes or os.PathLike object, not Tensor'

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):yes
- Briefly describe your candidate solution(if contributing): Create a constructor just like 'TextLineDataset' constructor which takes tensor and also strings of file paths.

**Standalone code to reproduce the issue**
````
import tensorflow as tf
path = "saved_data"

# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)



filenames = [path]
dataset = tf.data.Dataset.from_tensor_slices(filenames)
def parse_fn(filename):
  print(filename)
  return tf.data.experimental.load(filename)
dataset = dataset.flat_map(lambda x:
    parse_fn(x))

for item in dataset.as_numpy_iterator():
    print(item)
````

**Other info / logs** 

````
Traceback (most recent call last):
  File "C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues.py", line 19, in <module>
    dataset = dataset.interleave(lambda x:
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 2065, in interleave
    return InterleaveDataset(self, map_func, cycle_length, block_length)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 4596, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\eager\function.py", line 3134, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\eager\function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\eager\function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 695, in wrapper
Tensor("args_0:0", shape=(), dtype=string)
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues.py:20 None  *
        lambda x:
    C:/Users/kurud/Documents/ineaurondeeplearn/internship/DrowsyDetectCNNmodel/DataPipelineIssues.py:18 parse_fn  *
        return tf.data.experimental.load(filename)
    C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\experimental\ops\io.py:227 load  **
        return _LoadDataset(
    C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\site-packages\tensorflow\python\data\experimental\ops\io.py:134 __init__
        with gfile.GFile(os.path.join(path, DATASET_SPEC_FILENAME), "rb") as f:
    C:\Users\kurud\Anaconda3\envs\DrowsyDetectCNNmodel\lib\ntpath.py:78 join
        path = os.fspath(path)

    TypeError: expected str, bytes or os.PathLike object, not Tensor
````

**Comment by UsharaniPagadala** [comment]
@kurudinesh 
Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) to analyse the issue reported here.Thanks!

**Comment by kurudinesh** [comment]
> @kurudinesh
> Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) to analyse the issue reported here.Thanks!

I updated the issue with sample code to reproduce and system details. The code fails with interleave also and added almost same code to reproduce it also below. 


```
import tensorflow as tf
path = "saved_data"

# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)

#interleave code
filenames = [path]
dataset = tf.data.Dataset.from_tensor_slices(filenames)
def parse_fn(filename):
  print(filename)
  return tf.data.experimental.load(filename)
dataset = dataset.interleave(
    parse_fn)

for item in dataset.as_numpy_iterator():
    print(item)
```

**Comment by UsharaniPagadala** [comment]
@kurudinesh 

Could you please provide the colab gist with all the dependencies to analyse the issue better.Thanks

**Comment by kurudinesh** [comment]
> @kurudinesh
> 
> Could you please provide the colab gist with all the dependencies to analyse the issue better.Thanks
@UsharaniPagadala below is the colab gist.
`https://colab.research.google.com/drive/1UezT01v-liBnqCSZsYehQXOb19Ep3fw2?usp=sharing`

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/492fec48b85257202935a36ae5d19e0c/-50594.ipynb).Thanks

**Comment by Saduf2019** [comment]
@kurudinesh 
Can you please refer to these links and let us know.

[link](https://stackoverflow.com/questions/55490951/an-error-about-typeerror-expected-str-bytes-or-os-pathlike-object-not-nonetyp)
[link1](
https://github.com/tensorflow/tensorflow/issues/33730#issuecomment-546725105)
