### ISSUE TITLE
Feature Request - expose protobuf on syntaxnet as 'first class' interface

### ISSUE THREAD

**Issue by johndpope** [tensorflow/tensorflow#5061]
Clearly syntaxnet will parse sentences out of the box to a terminal with / without CoNLL format.

echo I saw the dude with glasses|./syntaxnet/demo.sh
<img width="298" alt="screen shot 2016-10-18 at 20 10 02" src="https://cloud.githubusercontent.com/assets/289994/19502649/725582b6-957c-11e6-8c94-e2230f6146ec.png">

I'm using a tensorflow in docker container - and now I want to interface to it from some other software via an api. I'd like to use some server side swift code. 

I spent time looking at following (parsey flask wrapper) 
https://github.com/JoshData/parsey-mcparseface-server

(parsey django wrapper) 
https://github.com/dan-nadler/ParseyAPI

and https://github.com/dmansfield/parsey-mcparseface-api

The last repo exposes parsey via protobufs - 
https://github.com/dmansfield/parsey-mcparseface-api/blob/160f3cbb5f96eff5fb8b73624228ceb7c8208b71/parsey_api/parsey_api.proto

using tensorflow serving but he had to fork the project and patch the files. 

While there's been help from other engineers to assist to get project working
https://github.com/dmansfield/parsey-mcparseface-api/issues/1

I suggest supporting protobufs out of the box as an api

**Comment by asimshankar** [comment]
@calberti might have more to say on this, but I suspect that we won't have the bandwidth to do this. The conll format is what syntaxnext produces and users are encouraged to build any higher level API that suits there needs.

**Comment by johndpope** [comment]
it appears that there are respective proto files created for syntax net - 
although - there doesn't appear to be any service layer grpc created. 
 
<img width="433" alt="screen shot 2017-04-28 at 2 42 37 pm" src="https://cloud.githubusercontent.com/assets/289994/25542529/f61b9dde-2c20-11e7-8c81-044b405ba9d1.png">

**Comment by johndpope** [comment]
https://github.com/tensorflow/models/tree/master/syntaxnet/syntaxnet

**Comment by girving** [comment]
This is a models issue, not a tensorflow core issue.

**Comment by johndpope** [comment]
seems like someone actually coded this 
https://github.com/dsindex/syntaxnet/blob/master/api/parsey_api.proto
