### ISSUE TITLE
cropping layer additional error message 

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#50612]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the current behavior**
When a cropping layer (Cropping1D, Cropping2D,Cropping3D) is used, it can happen that the cropping value is accidentally selected too big. Then, the output is just an empty list. It would be good to have an error or warning message for this case, since such an issue can be really cumbersome to find when it occurs deep in a complex graph model.
The issue is illustrated in the simplified example below.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
in0Cro69514 = tf.keras.layers.Input(shape=([1, 2]))
Cro69514 = keras.layers.Cropping1D(cropping=((5, 5)), name = 'Cro69514', )(in0Cro69514)
model = tf.keras.models.Model(inputs=[in0Cro69514], outputs=Cro69514)
in0Cro69514 = tf.constant([[[1.6058, 1.8537]]])
print (np.array2string(model.predict([in0Cro69514],steps=1), separator=', '))
```

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.4 and v2.5.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6297e9900e309ab8d8bf02612967ab87/untitled50612.ipynb).

**Comment by arubiales** [comment]
Hi @ymodak do you want to solve this issue? Can I work on it?

**Comment by ymodak** [comment]
@arubiales Feel free to take stab on this. Thanks!

**Comment by ymodak** [comment]
Keras project has moved to new repository in https://github.com/keras-team/keras
You may want to raise this PR on keras-team/keras repo.
See
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thanks for your PR and apologies for the overhead.
