### ISSUE TITLE
`tensorflow/python/keras` leads to inconsistencies when mixed with new Keras pip package in 2.6.0

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#50613]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0rc0
- Python version: 3.8

**Describe the current behavior**

Starting with TF 2.6.0rc0 [keras-team/keras](https://github.com/keras-team/keras) is replacing the code which previously located in `tensorflow/python/keras`. This changes the `tf.keras` endpoint to use the code from the OSS Keras pip package. 

Unfortunately the old code is still shipped with the TensorFlow pip package which can lead to very subtle inconsistencies in user code. This occurs especially in library code that tries to support different TF versions, which might be forced to rely on private imports since some functions might not be available in certain TF version. (E.g. `is_keras_tensor` has been only a public API since 2.1).

This duplicated code can lead to very weird behaviours since `isinstance` checks or similar will now break if users mix and match code. E.g. take these lines which previously where equivalent:
```python
from keras.engine.keras_tensor import KerasTensor  # imported from keras-team/keras

from tensorflow.python.keras.engine.keras_tensor import KerasTensor as KerasTensorFromTF # This import should not exist anymore

assert KerasTensorFromTF == KerasTensor   # This breaks!!!
```

```python
import tensorflow as tf

from tensorflow.keras.backend import is_keras_tensor
from tensorflow.python.keras.backend import is_keras_tensor as is_keras_tensor_tf  # this import should not exist anymore

assert is_keras_tensor(tf.keras.Input([10]))
assert is_keras_tensor_tf(tf.keras.Input([10])) # This breaks!!!
```
Checkout [this notebook](https://colab.research.google.com/drive/1-TcroLTdI4fx4dk5P3Cq_vk5AfiYuVOo?usp=sharing) for a full reproduction.

**Describe the expected behavior**

Since the intention to switch to keras-team/keras is clear I think the only way to get rid of this weirdness is to remove the `tensorflow/python/keras` code completely from the shipped pip package. This will likely frustrate some users relying on internal functions, but at least it won't lead to unintended behaviour or silent bugs that might be very hard to debug for inexperienced users. Also since `tensorflow.python` always has been a private API, I don't think breaking users of it will be a big problem. @fchollet @mihaimaruseac What do you think?

**Comment by UsharaniPagadala** [comment]
@lgeiger 

I was not able to access the notebook provided, Could you please provide the access .Thanks

**Comment by lgeiger** [comment]
> I was not able to access the notebook provided, Could you please provide the access .Thanks

Sorry about that. @UsharaniPagadala you should be able to access it now.

**Comment by UsharaniPagadala** [comment]
@rmothukuru 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/03fbde228c60a553ca3ee294e9fc9713/untitled40.ipynb).Thanks

**Comment by haifeng-jin** [comment]
@lgeiger Thank you for the issue!
`import keras` is not a standard usage after Keras became a dependency of TensorFlow.
We expect the users to only use `from tensorflow import keras`.
We may add additional guide to make sure the users are aware of this.

Regarding the duplication of the code, we will remove the code in tensorflow repo in the future.
@qlzh727 may have more info about this issue.

**Comment by lgeiger** [comment]
> `import keras` is not a standard usage after Keras became a dependency of TensorFlow.

@haifeng-jin I am aware of that. But unfortunately some APIs are not yet exposed via `tensorflow.keras` which means users and library authors are sometimes required to either rely on `tensorflow.python.keras` or `keras` directly. And as detailed above mixing and matching doesn't work as it is not the same code which can lead to not obvious issues. For more info checkout #44613 which e.g. also impacts TensorFlow Addons [here](https://github.com/tensorflow/addons/pull/2516/files#diff-bc6fb95c9ed9c45a0c8c0640531e3316ddb7894cc64f6d433c3dd1c013a0a44aR23-R26).

**Comment by qlzh727** [comment]
Thanks for reporting this issue and we are aware of this.

We leave the tensorflow.python.keras code in the release for now since we want to give user some time window (1 release) to migrate their code to use the new location if needed (although they shouldn't use the private APIs). Deleting the code will require immediate user action when they switch to TF 2.6. The code in tensorflow.python.keras and keras PIP are almost identical, and the only side effects are the `isinstance` type checking, which could lead to some user confusion. 

We think this shouldn't impact too many user since they should rely on TF public API only.

**Comment by haifeng-jin** [comment]
Actionable: add to release note about type checking and legacy code in tf.
Leave the code as it is for the next release.

**Comment by qlzh727** [comment]
As a workaround, you could replace any "tensorflow.python.keras.xxx" imports with "keras.xxx" for 2.6 release, and it should work for you. For TF Addon, we probably will work with Addon to expose necessary endpoints as \_\_internal__ API, so that ppl can avoid using private API and have some level of API guarantee.
