### ISSUE TITLE
Confusing about GPU state when ran out of memory

### ISSUE THREAD

**Issue by lonway** [tensorflow/tensorflow#50629]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not mobile device
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==1.15
- TensorFlow version (use command below): tensorflow-gpu==1.15
- Python version: 3.6.12
- Bazel version (if compiling from source): 0.18.0-
- GCC/Compiler version (if compiling from source):4.8.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
My GPU model ran out of memory during training process, it reports the GPU state as follows:

![截屏2021-07-06 下午6 51 53](https://user-images.githubusercontent.com/5723913/124589692-dc6f4700-de8c-11eb-868f-f0365e989bdd.png)

As shown above, "Limit" indicates that the total memory of my GPU is  22,676,357,120 bytes, which is equal to my Tesla P40 GPU's 22G memory. "InUse" means the GPU has allocated 11,866,777,088 bytes. Thus the remaining memory should be 22,676,357,120 - 11,866,777,088 = 10,809,580,032 bytes. Now the process need to allocate 5,352,895,488 bytes, which is less than 10,809,580,032 bytes. So why does it report the process ran out memory?

And what is the meaning of "MaxInUse" and "MaxAllocSize" ?

**Comment by Saduf2019** [comment]
@lonway 
Could you please upgrade the tensorflow version to 2.x and let us know if you face the issue as 1.x is not actively supported.

In 2.x you may try:
You may try limiting gpu memory growth in this case.
Put following snippet on top of your code;

```import tensorflow as tf```
```gpus = tf.config.experimental.list_physical_devices('GPU')```
```tf.config.experimental.set_memory_growth(gpus[0], True)```
```# your code```

**Comment by lonway** [comment]
@Saduf2019 Our online system does not support tensorflow 2.x :(

**Comment by Saduf2019** [comment]
@lonway 
As we have active support for 2.x now, please create this issue on tf discuss forum as there is a larger community to support there.
