### ISSUE TITLE
tf.math.sigmoid/tanh for RaggedTensor

### ISSUE THREAD

**Issue by Azmisov** [tensorflow/tensorflow#50620]
I was surprised to see that two common activation functions, sigmoid and tanh, are not provided in `tf.ragged` module. Makes me wonder how many people are actually using RaggedTensor features with no feature requests for these.

I am currently calculating both via mathematical identities. However, I still think the API's between regular Tensor and RaggedTensor should be as close as possible, as ideally you should be able to just swap in a RaggedTensor and have everything just work.

**Comment by edloper** [comment]
To apply elementwise ops (or other elementwise functions) to ragged tensors, you can generally use `tf.ragged.map_flat_values`.  E.g., `tf.ragged.map_flat_values(tf.math.tanh, x)`.

Though I agree that you shouldn't have to do that -- where possible, ops should just work w/ ragged tensors.  I'm not sure why these two ops were left off the list of elementwise ops to dispatch for.  

It looks like dispatch for `sigmoid` was added recently (bc5eddee3dda337c5b9287691b55d7a363b65c7b), but `tanh` hasn't been added yet.

**Comment by edloper** [comment]
I went through the ops under `tf.math`, and checked for any elementwise ops that didn't already have dispatch.  I'll send a PR to add dispatch for these ops.  The ops I identified were:

* tf.math.atan2
* tf.math.erfcinv
* tf.math.nextafter
* tf.math.recipricol_no_nan
* tf.math.softplus
* tf.math.tanh
* tf.math.bessel_i0 
* tf.math.bessel_i0e
* tf.math.bessel_i1
* tf.math.bessel_i1e

Let me know if you notice any other elementwise ops that should have dispatch enabled.

**Comment by edloper** [comment]
Fixed by 99f145872e474a603472e5d096631906bba86912.
