### ISSUE TITLE
Make layers from `tensorflow.keras.layers.experimental.preprocessing` usable in TF Lite

### ISSUE THREAD

**Issue by CaptainDario** [tensorflow/tensorflow#50625]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
It would be awesome if layers from `tensorflow.keras.layers.experimental.preprocessing` like `Resizing` would be convertable to TF Lite without implementing custom ops.

Currently a custom op definition is needed for (some of) them to work.
Especially Lanczos3 for Resizing would be nice.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
It would be very easy to add preprocessing inside a model. Therefore people who want to use those models do not need information about what input format should be used.

**Comment by Saduf2019** [comment]
@CaptainDario 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by CaptainDario** [comment]
Thank you!
I did not know that keras and TensorFlow are separated repos now.
I will open the issue in that repo than.
