### ISSUE TITLE
tensorflow lite compiling failed on docker

### ISSUE THREAD

**Issue by DannyIsFunny** [tensorflow/tensorflow#50624]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
I compile tensorflow lite in android mode according to the online guide: https://www.tensorflow.org/lite/guide/build_android

- the docker file provided by tflite can not be built successfully by docker
    - https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile

![image](https://user-images.githubusercontent.com/45189361/124571655-927d6580-de7a-11eb-9297-02e55932a6f7.png)

- However, I modified the docker file and rebuilt the docker successfully. I entered into docker container but tflite compiling still failed.
   - jdk version: 1.8
   - command : `bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   //tensorflow/lite/java:tensorflow-lite`

![image](https://user-images.githubusercontent.com/45189361/124571996-dbcdb500-de7a-11eb-8190-1d498580b2fb.png)

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by thaink** [comment]
Sorry. the "install default-jdk" is introduced by me to fix the error you mentioned below.

**Comment by thaink** [comment]
I sent a fix for that.
Changing:
`sudo apt install default-jdk`
to:
`RUN apt-get install -y --no-install-recommends default-jdk`

**Comment by thaink** [comment]
The fix is merged in the master branch. You can sync and try it now.
