### ISSUE TITLE
How can i know the order of multiple inputs when i use TrtGraphConverterV2 build. 

### ISSUE THREAD

**Issue by zhaocc1106** [tensorflow/tensorflow#50630]
tensorflow version: tensorflow-gpu 2.0.4
cuda version: 10.0
cudnn version: 7.4
tensorrt version: 5.1.5

When i use tensorrt converter to convert my model, i can't know the order of multiple inputs. Such as:

```
converter = trt.TrtGraphConverterV2(***)
converter.convert()
def my_inp_fn():
    inp_1 = np.zeros((2000, 120), np.int32)
    inp_2 = np.zeros((1, 47), np.int32)
    inp_3 = np.zeros((2000, 178), np.int32)
    inp_4 = np.zeros((1, 1493), np.int32)
    inp_5 = np.zeros((2000, 12), np.int32)
    inp_6 = np.zeros((1, 54), np.int32)
    inp_7 = np.zeros((2000, 178), np.float32)
    inp_8 = np.zeros((1, 1493), np.float32)
    inp_9 = np.zeros((2000, 93), np.float32)
    inp_10 = np.zeros((1, 12), np.float32)
    yield [inp_1, inp_2, inp_3, inp_4, inp_5, inp_6, inp_7, inp_8, inp_9, inp_10]
converter.build(input_fn=my_inp_fn)
```

I use saved_model_cli tool to check the signature input. But the signature input order is not true order for trt convert build function. Build function will report error with wrong order. Like:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute __inference_pruned_26473 as input #8(zero-based) was expected to be a int32 tensor but is a float tensor [Op:__inference_pruned_26473]
```
I can't analyse the order with the too simple error log.

Thanks very much!

**Comment by zhaocc1106** [comment]
So, how can i know the order of multiple inputs when i use TrtGraphConverterV2 build ?

**Comment by ymodak** [comment]
You may use TensorBoard to visualize TF-TRT graph
https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#tensorboard
