### ISSUE TITLE
Can't build tensorflow lite wheel in docker image for aarch64

### ISSUE THREAD

**Issue by brunovollmer** [tensorflow/tensorflow#50634]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow version: latest from github

**Describe the problem**
Following the instructions from [here](https://www.tensorflow.org/lite/guide/build_cmake_pip) I tried to build a python wheel for tensorflow lite for the aarch64 (mendel 4.0/coral dev board) architecture. 

`tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38   tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh aarch64`

When I run the suggested command an error occurs which indicates that cmake can't find the correct compiler. 

```
CMakeFiles/cmTC_8c684.dir/testCCompiler.c.o  -o cmTC_8c684 
    aarch64-linux-gnu-gcc: fatal error: -fuse-linker-plugin, but liblto_plugin.so not found
    compilation terminated.
    CMakeFiles/cmTC_8c684.dir/build.make:89: recipe for target 'cmTC_8c684' failed
    make[1]: *** [cmTC_8c684] Error 1
    make[1]: Leaving directory '/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeTmp'
    Makefile:124: recipe for target 'cmTC_8c684/fast' failed
    make: *** [cmTC_8c684/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:40 (project)


CMake Error at CMakeLists.txt:40 (project):
  The CMAKE_CXX_COMPILER:

    /workspace/tensorflow/lite/tools/cmake/toolchains/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeOutput.log".
See also "/workspace/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/cmake_build/CMakeFiles/CMakeError.log".

```
After some investigation it seems that for some reason the tar command has problems unpacking the downloaded toolchain. The error (if manually run) is 
`
tar: gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++: Cannot hard link to ‘gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-c++’: Operation not supported
`
Any suggestions how to fix this issue?

**Comment by terryheo** [comment]
I've just tried on master branch on my Linux machine and it works well.

Could you share branch you used and your build environment?

**Comment by brunovollmer** [comment]
The problem was that I tried to built it on an azure machine learning instance inside a mounted networking file system and apparently the untar option does not work there properly as it does not support hard links. Solution was to run it outside the mounted file system.
