### ISSUE TITLE
Compiling a keras model during a callback causes TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Lescurel** [tensorflow/tensorflow#50633]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary from pip/anaconda
- TensorFlow version (use command below): Tried with the following 
  - v2.4.0-49-g85c8b2a817f 2.4.1
  - v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
  - v1.12.1-59787-gd89220bfa4c 2.7.0-dev20210706 (tf-nightly)
- Python version: 3.8.5

**Describe the current behavior**

When compiling a model in a callback, the training breaks with the error `TypeError: 'NoneType' object is not callable`
I'm pretty sure there is a regression here, as it works when using TensorFlow v <= 2.3

**Describe the expected behavior**

No crash, and having the model recompiled with the new parameters passed during compilation. 

**Standalone code to reproduce the issue**

```
import tensorflow as tf

class MyCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epochs, logs=None):
        # we recompile at the end of the first epoch
        if epochs == 0:
            self.model.compile(
                optimizer="rmsprop",
                loss="mse",
            )

model = tf.keras.Sequential([tf.keras.layers.Dense(1,input_shape=(1,))])
my_callback = MyCallback()
x = tf.random.uniform((100,1))
y = tf.random.uniform((100,1))

model.compile(optimizer="rmsprop", loss="mse")

model.fit(x,y, callbacks=[my_callback], epochs=2)
```

**Other info / logs** Include any logs or source code that would be helpful to

The Traceback: 
```

Traceback (most recent call last):
  File "compile_callback.py", line 28, in <module>
    model.fit(x,y, callbacks=[my_callback], epochs=2)
  File "/home/user/miniconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
TypeError: 'NoneType' object is not callable
```

**Comment by tilakrayal** [comment]
@Lescurel,

 It looks like the issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](https://github.com/keras-team/keras/issues) repository. Thanks!

**Comment by Lescurel** [comment]
Done. Feel free to close the issue if needed.

**Comment by tilakrayal** [comment]
@Lescurel ,

Please feel free to close the issue here and open new issue in keras repo.Thanks!
