### ISSUE TITLE
Converting FasterRCNN from tf -> tflite fails: could not rewrite use of immutable bound input

### ISSUE THREAD

**Issue by florianletsch** [tensorflow/tensorflow#50635]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installation (pip package or built from source): `tensorflow==2.5.0` installed via pip

### 2. Code

Full code to reproduce my issue: https://github.com/florianletsch/torch2tflite-failing

I am trying to convert a Faster-RCNN with Resnet backbone following these 3 steps:  

1. PyTorch -> ONNX
2. ONNX -> Tensorflow
3. Tensorflow -> tflite

Step 3 takes a while (~18 minutes) and then fails. This is the code of step 3:

```
converter = tf.lite.TFLiteConverter.from_saved_model('assets/tfsavedmodel')
tflite_model = converter.convert()
```

Error message:

```
loc(callsite(callsite("onnx_tf_prefix_If_1347@__inference___call___15681" at "StatefulPartitionedCall@__inference_signature_wrapper_16224") at "StatefulPartitionedCall")): error: could not rewrite use of immutable bound input
Traceback (most recent call last):
  File "/home/florian/projects/torch2tflite-failing/venv/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 291, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/home/florian/projects/torch2tflite-failing/venv/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite("onnx_tf_prefix_If_1347@__inference___call___15681" at "StatefulPartitionedCall@__inference_signature_wrapper_16224") at "StatefulPartitionedCall")): could not rewrite use of immutable bound input
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
```

### The op node where it fails

The error message mentions op node `If_1347`. According to the onnx model, the then/else branches of that node contain the following results of PyTorch's JIT:

```
  %2632 = If[else_branch = <graph torch-jit-export2>, then_branch = <graph torch-jit-export1>](%2631)

(...)

graph torch-jit-export1 {
  %2633 = Constant[value = <Tensor>]()
  %2634 = ConstantOfShape[value = <Tensor>](%2633)
  return %2634
}

graph torch-jit-export2 {
  %2635 = ReduceMax[keepdims = 0](%2622)
  %2636 = Cast[to = 1](%2626)
  %2637 = Constant[value = <Scalar Tensor []>]()
  %2638 = Cast[to = 1](%2637)
  %2639 = Add(%2635, %2638)
  %2640 = Mul(%2636, %2639)
  %2641 = Unsqueeze[axes = [1]](%2640)
  %2642 = Add(%2622, %2641)
  %2643 = Unsqueeze[axes = [0]](%2642)
  %2644 = Unsqueeze[axes = [0]](%2624)
  %2645 = Unsqueeze[axes = [0]](%2644)
  %2646 = Constant[value = <Tensor>]()
  %2647 = Constant[value = <Tensor>]()
  %2648 = NonMaxSuppression(%2643, %2645, %2646, %2647)
  %2649 = Constant[value = <Tensor>]()
  %2650 = Gather[axis = 1](%2648, %2649)
  %2651 = Squeeze[axes = [1]](%2650)
  return %2651
}
```

I don't understand what's going on here, is there a pointer that explains the issue hidden here?

### Logs
Logs of my 3 conversion steps can be found here: https://github.com/florianletsch/torch2tflite-failing/tree/main/logs

### Converter issue or an unrelated problem?
Is this an issue or the tflite converter? Or is this likely an issue of an earlier step in the conversion pipeline? I am grateful for any pointers.

**Comment by abattery** [comment]
Mutable variable support is now available in the nightly when converting using from_saved_model.
You need to set this flag to True for now.

converter.experimental_enable_resource_variables = True

**Comment by florianletsch** [comment]
This solved it, thank you!
