### ISSUE TITLE
Container __per_step_0 does not exist

### ISSUE THREAD

**Issue by DaliaJaber** [tensorflow/tensorflow#50631]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- TensorFlow version (use command below):  2.3.1
- Python version: 3.7.7
- CUDA/cuDNN version:  library cudart64_101.dll v2.3.0-54-gfcc4b966f1 2.3.1

**Describe the current behavior**

While running multiple object detection inference in parallel the session crashed and the below error occurred.

Traceback (most recent call last):
    output_dict = model(input_tensor)
  File "/home//.conda/envs//lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1605, in __call__
    return self._call_impl(args, kwargs)
  File "/home//.conda/envs//lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1645, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home//.conda/envs//lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home//.conda/envs//lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home//.conda/envs//lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.NotFoundError:  Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysBatchMultiClassNonMaxSuppression/map/TensorArray_11_950)
         [[node BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_5/TensorArrayWriteV3 (defined at /home/workspace//utils/field_detection.py:15) ]] [Op:__inference_pruned_41885]

Function call stack:
pruned

**Describe the expected behavior**

**Standalone code to reproduce the issue**

Reproducing the issue was not possible.

**Comment by UsharaniPagadala** [comment]
@DaliaJaber 

Could you please refer the [comment](https://github.com/tensorflow/tensorflow/issues/28287#issuecomment-495005162)        ,hope it helps.Thanks
