### ISSUE TITLE
Problem resuming training with checkpoints in TF > 2.4.1

### ISSUE THREAD

**Issue by jelimomaswan** [tensorflow/tensorflow#50646]
**System information**
- Windows 10 Pro
- TF 2.4.1 and TF 2.5.0

**Describe the current behavior**
It is no longer possible to resume training with checkpoints in TF > 2.4.1. This is not the case in previous versions of TF. The following error is displayed: tensorflow ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: <tf.Tensor: shape=(), dtype=int32, numpy=0>. It appears to be caused by OptimizerV2, where all the hyperparameters are assumed to be float when loading the adam optimizer, yet the optimizer saves some of the hyperparameters as integers.

**Comment by ymodak** [comment]
I tried executing the [training checkpoint guide](https://www.tensorflow.org/guide/checkpoint) and it works fine with TF 2.5.0 as well.
Perhaps you want to create a minimal code example to reproduce the issue observed. Thanks!
