### ISSUE TITLE
Input shapes incompatible when using `tensorrt.Converter`

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#50648]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Using Colab (with GPU) and TensorFlow 2.5

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have an image classification model that takes 224x224x3 inputs. Now when I am trying to convert it to TensorRT with the pre-built engine options enabled it's running into:

```python
/usr/local/lib/python3.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py in build(self, input_fn)
   1187       if not first_input:
   1188         first_input = inp
-> 1189       func(*map(ops.convert_to_tensor, inp))
   1190 
   1191     if self._need_trt_profiles():

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   1709       TypeError: If the arguments do not match the function's signature.
   1710     """
-> 1711     return self._call_impl(args, kwargs)
   1712 
   1713   def _call_impl(self, args, kwargs, cancellation_manager=None):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/wrap_function.py in _call_impl(self, args, kwargs, cancellation_manager)
    245     else:
    246       return super(WrappedFunction, self)._call_impl(
--> 247           args, kwargs, cancellation_manager)
    248 
    249   def prune(self, feeds, fetches, name=None, input_signature=None):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1727             raise structured_err
   1728 
-> 1729       return self._call_with_flat_signature(args, kwargs, cancellation_manager)
   1730 
   1731   def _call_with_flat_signature(self, args, kwargs, cancellation_manager):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _call_with_flat_signature(self, args, kwargs, cancellation_manager)
   1749           "{} takes {} positional arguments but {} were given".format(
   1750               self._flat_signature_summary(), self._num_positional_args,
-> 1751               len(args)))
   1752     args = list(args)
   1753     kwargs = dict(kwargs)

TypeError: pruned(input_1) takes 1 positional arguments but 224 were given
```

**Describe the expected behavior**

It's not clear as of now. [The documentation](https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter) does mention about the specifications but following those didn't help. 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

```python
params = tf.experimental.tensorrt.ConversionParams(
    precision_mode="FP16",
    maximum_cached_engines=16)
converter = tf.experimental.tensorrt.Converter(
    input_saved_model_dir="classification_model", conversion_params=params)
converter.convert()

def data_gen():
    for image in images[:100]:
        yield image

converter.build(input_fn=data_gen)  
converter.save("tensorrt_embedding_model")  
```

where, `classification_model` is the location of the SavedModel (generated from `tf.keras.applications.DenseNet121`). 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@sayakpaul 

While running the code I am facing an error stating `OSError: SavedModel file does not exist at: classification_model/{saved_model.pbtxt|saved_model.pb}`

Could you please share the saved model file you are using in the code. Zip the contents of the folder, then drag and drop it in the input text box to share it. Thanks!

**Comment by sayakpaul** [comment]
You likely didn't read the description. 

> where, classification_model is the location of the SavedModel (generated from tf.keras.applications.DenseNet121).

This means you need first load the `DenseNet121` model, save it as a `SavedModel` and then proceed.

**Comment by srihari-humbarwadi** [comment]
`build` method expects you to return inputs in a tuple. I have changed your `data_gen` function to match the correct signature. 
Here is  the full script.

```python
import os

import tensorflow as tf
from tqdm import tqdm

print('TensorFlow version:', tf.__version__)

model = tf.keras.applications.DenseNet121()
tf.saved_model.save(model, 'classification_model')
print('classification_model:', os.listdir('classification_model'))

params = tf.experimental.tensorrt.ConversionParams(
    precision_mode="FP16",
    maximum_cached_engines=16)
converter = tf.experimental.tensorrt.Converter(
    input_saved_model_dir="classification_model",
    conversion_params=params)
converter.convert()

def data_gen(steps=1):
    for i in range(steps):
        # converter.build expects you to send it a tuple containing the inputs
        yield (tf.random.uniform([1, 224, 224, 3]),)

converter.build(input_fn=data_gen)  
converter.save("tensorrt_embedding_model")
print('tensorrt_embedding_model:', os.listdir('tensorrt_embedding_model'))

trt_model = tf.saved_model.load('tensorrt_embedding_model')
serving_fn = trt_model.signatures['serving_default']
image = tf.random.normal([1, 224, 224, 3])

for _ in tqdm(range(1000)):
    predictions = serving_fn(image)
```
---
```
TensorFlow version: 2.5.0
INFO:tensorflow:Assets written to: classification_model/assets
classification_model: ['variables', 'saved_model.pb', 'assets']
INFO:tensorflow:Linked TensorRT version: (0, 0, 0)
INFO:tensorflow:Loaded TensorRT version: (0, 0, 0)
INFO:tensorflow:Assets written to: tensorrt_embedding_model/assets
tensorrt_embedding_model: ['variables', 'saved_model.pb', 'assets']
100%|██████████| 1000/1000 [00:12<00:00, 79.92it/s]
```

**Comment by sayakpaul** [comment]
I see. This is nowhere mentioned in the docs. Thanks, @srihari-humbarwadi :)
