### ISSUE TITLE
ERROR: Didn't find op for builtin opcode 'MUL' version '5'

### ISSUE THREAD

**Issue by RedJyve** [tensorflow/tensorflow#50641]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): model built with tf2.5 converted to tflite with tf_nightly 2.7.0-dev20210705

**Output from tflite benchmark**

```
STARTING!
Log parameter values verbosely: [0]
Graph: [model_float16.tflite]
Enable op profiling: [1]
Loaded model model_float16.tflite
ERROR: Didn't find op for builtin opcode 'MUL' version '5'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?

ERROR: Registration failed.

Failed to initialize the interpreter
Benchmarking failed.

```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

The benchmark run was the prebuilt one provided on https://www.tensorflow.org/lite/performance/measurement#ios_benchmark_app.
I can't use any earlier version of TensorFlow to convert the model because of recent additions to tf_nightly

**Comment by abattery** [comment]
This is an intended behavior. You need to use the same or higher version used for conversion when invoking the converted graph.

**Comment by RedJyve** [comment]
I little confused, from what I understand the I am using the same or higher version of TensorFlow. Should I build the benchmark from source since the pre-built ones don't seem to be working, or maybe they aren't the newest version of nightly like I was lead to believe? Maybe I am missing something?
