### ISSUE TITLE
Custommask warning when saving to h5 using built-in keras layers

### ISSUE THREAD

**Issue by ghylander** [tensorflow/tensorflow#50647]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- TensorFlow installed from (source or binary): pypi
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.5

**Describe the current behavior**
When saving a model to h5 format, and the model contains one of the following layers:
```
tf.keras.layers.experimental.preprocessing.Resizing()
tf.keras.layers.experimental.preprocessing.CenterCrop()
```

there is a:

`CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.`

When trying to load the keras model with tf.keras.models.load_model, it'll fail with:

`TypeError: ('Keyword argument not understood:', 'crop_to_aspect_ratio')`

**Describe the expected behavior**
It should both correctly save and load

**Standalone code to reproduce the issue**

**Comment by tilakrayal** [comment]
@ghylander ,

In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by ghylander** [comment]
unfortunately i can't, provide the dataset, but it's not relevant, it happens when saving an untrained model (only default weights from imagenet)
by doing further tests i found out that the issue just started happening on the AWS machine we use for training models

it just began happening even with model architectures that have been working for months.
There is specially something that confuses me, the code i am using to save the model is:


```
model.save('FULLPATHTODIRECTORY/tf_model')
model.save('FULLPATHTODIRECTORY/keras_model.h5')
```

and the output is:
```
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
/home/ubuntu/miniconda3/envs/VENVNAME/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '
INFO:tensorflow:Assets written to: FULLPATHTODIRECTORY/tf_model/assets
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
```

why is it rising a warning about compiling the model?

here gist with simplified code:
https://colab.research.google.com/drive/1GOYa3nBBmw27h7aayCfskz-p0SxElQ0S?usp=sharing

i used this dataset for the gist: https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip

**Comment by ghylander** [comment]
Hi, i cloned my venv and installed tf 2.4.2 on it and i don't have this issue
is there something that changed in how models are saved?
previous to the stable 2.5.0 i had used both 2.5.0 nightly november release and march release, and i didnt have this issue before
i changed nothing in the code, just uninstalled 2.5.0 and installed 2.4.2
the issue is also present in the gist i linked, which i assume to be a "clean" install

**Comment by tilakrayal** [comment]
@ghylander ,

The warning was added with TF 2.5 in commit [076b5be](https://github.com/tensorflow/tensorflow/commit/076b5be77d3933deb726de1fc9d954d284985b1e#diff-08518b3b0b22c5c9dc137c911fa716fe820878cb9bbf95806ffca0e0296ec7fa).Please refer this [comment](https://github.com/tensorflow/tensorflow/issues/50324#issuecomment-864687940) from the issue.Thanks!

**Comment by ghylander** [comment]
i usppose i'll close it as it seems to be a duplicate then
