### ISSUE TITLE
RaggedTensor not broadcasting correctly

### ISSUE THREAD

**Issue by Azmisov** [tensorflow/tensorflow#50642]
Ubuntu 20.04, Tensorflow 2.5

A broadcast should be able to work across a RaggedTensor, so long as the dimension has fixed size. See the following example:

```python
import tensorflow as tf
BATCHES = 4
CHANNELS = 8

# Two methods to create an "equivalent" RaggedTensor
ragged_1 = tf.expand_dims(tf.RaggedTensor.from_row_lengths(
	tf.random.normal((10*BATCHES, CHANNELS)),
	[12,8,7,13]
), -2)
ragged_2 = tf.expand_dims(tf.RaggedTensor.from_row_lengths(
	tf.RaggedTensor.from_uniform_row_length(
		tf.random.normal((10*BATCHES*CHANNELS, )),
		CHANNELS
	),
	[12,8,7,13]
), -2)

# A simple multiplication kernel
kernel = tf.random.normal((1, 1, 16, CHANNELS))

# Try to multiply
print("ragged 1 shape: ", ragged_1.shape)
print("ragged 2 shape: ", ragged_2.shape)
print("kernel shape: ", kernel.shape)

# ragged_1 succeeds
out_1 = tf.multiply(ragged_1, kernel)
print("mult 1 success")
# ragged_2 fails !
out_2 = tf.multiply(ragged_2, kernel)
print("mult 2 success")
```
Output:
```
ragged 1 shape:  (4, None, 1, 8)
ragged 2 shape:  (4, None, 1, 8)
kernel shape:  (1, 1, 16, 8)
mult 1 success
Traceback (most recent call last):
   ...
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'Unable to broadcast: dimension size mismatch in dimension'
2
b'lengths='
16
b'dim_size='
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
```
Even though `ragged_1` and `ragged_2` have identical shapes, the multiply only succeeds for the first. Seems like an over-zealous assertion is preventing the `ragged_2` multiply?

**Comment by UsharaniPagadala** [comment]
@Azmisov 
As per the definition of Broadcasting, [Broadcasting](https://www.tensorflow.org/guide/ragged_tensor#broadcasting) is the process of **making** tensors with different shapes have compatible shapes for elementwise operations, there is no need to specify tf.expand_dims explicitly, Tensorflow will take care of it.

Could you please refer the similar [issue](https://stackoverflow.com/questions/61947237/broadcasting-with-ragged-tensor),Let us know if it helps.Thanks

**Comment by Azmisov** [comment]
> As per the definition of Broadcasting, [Broadcasting](https://www.tensorflow.org/guide/ragged_tensor#broadcasting) is the process of **making** tensors with different shapes have compatible shapes for elementwise operations, there is no need to specify tf.expand_dims explicitly, Tensorflow will take care of it.

Consider the following two broadcasts:
```
a:       (r1) x 3 x 3
b:              3 x 3
result:  (r1) x 3 x 3
```
```
a:       (r1) x 3 x 1 x 3
b:                  3 x 3
result:  (r1) x 3 x 3 x 3
```
The two calculations give different results. Mine is the second case, which you see would require inserting a shape 1 dimension at -2. So even though certain shapes are already compatible and tensorflow can handle it, that may not be the computation you want.

> Could you please refer the similar [issue](https://stackoverflow.com/questions/61947237/broadcasting-with-ragged-tensor),Let us know if it helps.Thanks

For the issue you linked, the OP was trying to do this broadcast:
```
a:       2 x (r1)
b:              3
```
Which obviously would not work since the trailing dimension did not match. However, for the test case I gave, the shapes are:
```
a:       4 x (r1) x  1 x 8
b:       1 x    1 x 16 x 8
result:  4 x (r1) x 16 x 8
```
Definitely compatible there, and the multiplication works fine for `ragged_1`. However, `ragged_2`, which has the exact same shape at runtime/graph-computation, throws an error that the shapes are not compatible.
Could you please take a closer look at the test case I showed, and the different behavior between `ragged_1` and `ragged_2`?

**Comment by UsharaniPagadala** [comment]
@rmothukuru 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/632c1ce4d196753d98bded818460c12a/-50642.ipynb).Thanks

**Comment by edloper** [comment]
The code for broadcasting ragged tensors ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/ragged/ragged_tensor_shape.py)) was written before the `uniform_row_length` option was added for partitioning ragged tensors.  (`uniform_row_length` was mainly added to help with multiple *leading* uniform dimensions -- shapes like `[5, 3, None]` -- which otherwise wouldn't be representable.)

I agree that `ragged_tensor_shape.py` should be updated to handle `uniform_row_length` values.

**Comment by gonnet** [comment]
I'm hitting a similar problem. The difference seems to be:

```python
print(f"ragged 1 shape: {ragged_1.shape}, ragged_rank: {ragged_1.ragged_rank}")
print(f"ragged 2 shape: {ragged_2.shape}, ragged_rank: {ragged_2.ragged_rank}")
```
```
ragged 1 shape: (4, None, 1, 8), ragged_rank: 1
ragged 2 shape: (4, None, 1, 8), ragged_rank: 3
```

i.e. although the Tensors are identical, they have different ragged ranks.

**Comment by tilakrayal** [comment]
@Azmisov,
I was able to execute the provided code without any issues on tf v2.11.0-dev20220829. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b04f2b6fc5607f7cd78f1090cbc279fa/untitled546.ipynb) and confirm if the issue still persists. Thank you!

**Comment by Azmisov** [comment]
Yes looks like it is fixed
