### ISSUE TITLE
same host memory address copy tensor to different device memory address

### ISSUE THREAD

**Issue by crischeng** [tensorflow/tensorflow#50649]
I have a question. I export TF_CPP_MIN_VLOG_LEVEL=3 want to dump the log, then I find something I can't understand. I saw tensorflow from the same host memory address copy tensor to different device memory address, I want to know why does tensor flow do this? What are the advantages?
I think it will rely on CUDA Events for synchronization. Why not from different host memory  address?  
Looking forward to a reply.

![tf_log](https://user-images.githubusercontent.com/27774893/124728011-d0918c80-df41-11eb-8168-598cf9803599.jpg)

**Comment by sanjoy** [comment]
There are many possible reasons for this.

If you have a beefy machine that can build TensorFlow, I'd suggest rebuilding TF and using a [`CurrentStackTrace`](https://github.com/tensorflow/tensorflow/blob/91ec0d83972d2c73facaf80e0da3c755ff5910e9/tensorflow/core/platform/default/stacktrace.h#L42) call in `ThenMemcpy` to figure out where the copies are coming from.

**Comment by tilakrayal** [comment]
@crischeng,
Could you please take a look at the above comment from the developer and use **CurrentStackTrace** which provides the information where the error arises. Also Could you please create a virtual environment and install the latest stable v2.10.
For the points you could also set the environment variable TF_CPP_MIN_VLOG_LEVEL to 1 (used [here](https://github.com/tensorflow/tensorflow/blob/8191585626f438c185ce608e177a8c33fb9d3bee/tensorflow/core/platform/default/logging.cc#L178)) which will turn on verbose logging. Thank you!
