### ISSUE TITLE
Urgently need the pip installation package with ubuntu14/04/05 & cuda8 & cudnn5(bithpy27 an py34))

### ISSUE THREAD

**Issue by rzai** [tensorflow/tensorflow#5064]
In some country , it cannot download some package like bazel or protobuff etc, so install from source is impossible.

### Environment info
Operating System:
ubuntu14/04/05

Installed version of CUDA and cuDNN: 
cuda8 & cudnn5

**Comment by asimshankar** [comment]
All the release packages for TensorFlow (pip, docker etc.) are listed at https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

Any other combinations will require a source installation.
Sorry I don't have better news.
