### ISSUE TITLE
How to export the wide and deep model and use java client to request

### ISSUE THREAD

**Issue by jasonhere** [tensorflow/tensorflow#5065]
It seems that now we can export model for serving with the learn api 

`tf.contrib.learn.monitors.ExportMonitor` or  `tf.contrib.learn.utils.export`

in _w_d.py_

```
  export_dir = './export/'
  export_monitor = tf.contrib.learn.monitors.ExportMonitor(
        every_n_steps=100, export_dir=export_dir, exports_to_keep=2,signature_fn=???????)

  m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps, monitors=[export_monitor])
```

or

```
  m.export(export_dir, input_fn=??????, input_feature_key=??????, 
      use_deprecated_input_fn=False, signature_fn=??????, default_batch_size=1, exports_to_keep=2)

```

I am confused about the input parameters `input_fn`, `input_feature_key`, and `signature_fn`,and how can i use java to request.

Does anyone could provide  a runnable demo? 

thank you.

**Comment by asimshankar** [comment]
@jasonhere : I'm missing some context here, where are these code snippets from? What is `m` and `w_d.py`?

Regardless, it appears that you're looking for some demo code for serving a model. Perhaps [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) will be a more appropriate venue for seeking such advice from the community.
