### ISSUE TITLE
Tensorflow 2.3.x link error when use delay load

### ISSUE THREAD

**Issue by hksonngan** [tensorflow/tensorflow#50658]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 / Visual Studio 2017
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0~2.3.3
- Python version: N/A
- CUDA/cuDNN version: cuda 10.1 cudnn 7.6.5
- GPU model and memory: NVIDIA Quadro P4000

**Describe the current behavior**
I try to use delay load tensorflow and it work for TF 1.15.0 and 2.4.0 but not for all 2.3.x version.
Note I need stick with TF 2.3.x and error in build Release not Debug
Get link error as:
Error	LNK1194	cannot delay-load 'tensorflow.dll' due to import of data symbol '__imp_TF_DeleteStatus'; link without /DELAYLOAD:tensorflow.dll

`
#include <windows.h>
#include <delayimp.h>
#include <mutex>

namespace
{
    bool tf_useGPU = true;// true;
    bool tf_dllLoaded = false;

    FARPROC WINAPI DelayLoadHook(unsigned dliNotify, PDelayLoadInfo pdli)
    {
        switch (dliNotify)
        {
            //case dliNotePreLoadLibrary:
        case dliFailLoadLib:
            if (lstrcmpiA(pdli->szDll, "tensorflow.dll") == 0)
            {
                FARPROC p = NULL;
                if (tf_useGPU)
                {
                    // Disable the error window if the dll cannot be loaded
                    // Save the original mode and restore it after the load
                    UINT origin_mode = SetErrorMode(SEM_FAILCRITICALERRORS);

                    // Load the dll
                    p = (FARPROC)LoadLibraryA("tensorflow_gpu.dll");

                    // Restore the original mode.
                    SetErrorMode(origin_mode);

                    if (p)
                    {
                        std::cout << "TensorFlow GPU dll loaded\n" << std::endl;
                    }
                }

                if (!p)
                {
                    p = (FARPROC)LoadLibraryA("tensorflow_cpu.dll");

                    if (p)
                    {
                        std::cout <<"TensorFlow CPU dll loaded\n" << std::endl;
                    }
                }

                tf_dllLoaded = p != NULL;

                return p;
            }
        default:
            return NULL;
        }

        return NULL;
    }

    extern "C" const PfnDliHook __pfnDliFailureHook2 = DelayLoadHook;
}

void LoadTensorFlow(int iGPUOption)
{
    // dll can only be loaded once
    if (tf_dllLoaded)
    {
        assert(0);
        return;
    }
    tf_useGPU = iGPUOption != 0;

    // Call any tensorflow function to trigger the dll load
    const char* version = TF_GetVersion();
}
`

**Describe the expected behavior**
Link without error as other version of Tensorflow.

**Comment by ymodak** [comment]
Can you please try with MSVC 2019 as mentioned in this tested build configurations chart
https://www.tensorflow.org/install/source_windows#cpu Thanks!

**Comment by hksonngan** [comment]
Hi,
This issue because of download file direcvtly from tensorflow website.
And I compiled with vs 2017 without issue.

**Comment by ymodak** [comment]
I am sorry but I don't think I follow.  Can you please elaborate how you solved the issue?

**Comment by hksonngan** [comment]
[10:15 AM] David Guigonis
    I am using the dll/lib provided on the web site directly (C API - https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.3.0.zip). We also do not have access to VS2019 to try. We are working with VS2017. I did build the dll/lib myself and I am getting the same issue than the downloaded files. We want to use the pre-built files for production.

The problem is not solved, I am still getting the linker error regardless if I used downloaded files or built.

**Comment by sachinprasadhs** [comment]
Hi, Could you please try with the latest Tensorflow version by matching the requirements from the table here https://www.tensorflow.org/install/source_windows#cpu and let us know if you still face an issue. Thanks!
