### ISSUE TITLE
Which is the smallest SSD model to use in a MCU like ESP-EYE and using tensorflow lite micro?

### ISSUE THREAD

**Issue by VicGoico** [tensorflow/tensorflow#50656]
Hi,

I am trying to work with the smallest SSD model of tensorflow, but my problem is that I am working with an [ESP-EYE](https://www.espressif.com/en/products/devkits/esp-eye/overview) and this MCU has only 4 MB of memory.

All SSD models that I saw in the [pretrained models Garden of tensorflow](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md), are too big (more than 4 MB) or they dont have a ".tflite" file. 
In this last case, I saw that there is a way to convert the file ".pb" to ".tflite" [HERE](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r1/convert/python_api.md#convert-a-frozen-graphdef-from-file-) and a video where explain which parameters you must use [VIDEO](https://youtu.be/EAE-vjL2Nps?t=238), but the size of the files increase a lot.
For example, if the size of a ".pb" file is 5 MB, the conversion makes a file of 25 MB and things like this.

Here is a example of the code in python that I use for the conversion:

```python
import tensorflow as tf

# Convert the model.
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file='tflite/tflite_graph.pb', # Dir of the ".pb" file
    input_arrays=['normalized_input_image_tensor'],
    input_shapes={'normalized_input_image_tensor' : [1, 300, 300,3]}, # Shape of the images of the model you will need to change the 300 and 300
    output_arrays=['TFLite_Detection_PostProcess', 'TFLite_Detection_PostProcess:1', 'TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'],
)
converter.allow_custom_ops=True

# converter.quantized_input_stats = {'input' : (0., 1.)}  # mean, std_dev (input range is [-1, 1])
# converter.inference_type = tf.int8 # this is the recommended type.
# converter.inference_input_type=tf.uint8 #optional
# converter.inference_output_type=tf.uint8 #optional
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Save the model.
with open('quantized_model.tflite', 'wb') as f:
  f.write(tflite_model)
```

Soo my questions are:

1. Do you know some SSD model with a size less than 4 MB, for example, 3MB or 2MB, with the capability to detect persons?
2. Is posible to work with a SSD model and make the "Invoke"(prediction) of the model in the ESP-EYE or is a lot of work for a MCU?
I found some documentation, but I´m not sure if it works:
- [Documentation of tensorflow](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/cc/task#object-detector)
- [Code](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/cc/task#object-detector)

Thanks for read and have a good day.

See you XD

**Comment by ymodak** [comment]
Did you refer person detection example for tf lite micro to get some pointers?
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/person_detection/training_a_model.md

**Comment by VicGoico** [comment]
Hi,

I saw that tutorial, but they explain how to train a classification model where the model can say if there is a person in the image, but not how many.
In my case, I would need a very lite SSD model, that can detected multiple objects in the same image, specifically people.

**Comment by VicGoico** [comment]
Hi,

My main question is:

Could I work with an object detection model in a MCU like ESP-EYE, with 4MB of size, using TFLiteMicro or TFLiteMicro only can support object classification models, like this [example](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection#running-on-esp32)? 

Because all object detection models that I saw are more heavy than 4MB.

See you XD

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
