### ISSUE TITLE
OpKernelConstruction allocate tensor that can persistent for Compute 

### ISSUE THREAD

**Issue by gyin-ai** [tensorflow/tensorflow#50650]
How can we allocate a tensor or buffer that could exist among each Compute invocation?  If so, how can we free them after usage? 

Based on the description in op_kernel.h, `allocate_temp` seems to only allow temporary tensor allocation during the construction. Is this correct?

Thanks a lot.

**Comment by tilakrayal** [comment]
@gyin-ai ,

Can you please refer this link which provide information on [OpKernelConstruction](https://www.tensorflow.org/guide/create_op).It helps.

**Comment by tilakrayal** [comment]
Also this is not bug or feature request.Please feel free to close here and post in [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) where larger community reads questions there.Thanks!

**Comment by gyin-ai** [comment]
@tilakrayal I have checked the source code but didn't see any potential function to do so. https://github.com/tensorflow/tensorflow/blob/ae38275fbbb602ef00930a8969ee4a352ae107e3/tensorflow/core/framework/op_kernel.h#L254

**Comment by tilakrayal** [comment]
@gyin-ai ,

In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.Thanks!
