### ISSUE TITLE
Quantized Version of tf-lite model returning "ERROR: Didn't find op for builtin opcode 'CONV_2D' version '5'" when measuring performance

### ISSUE THREAD

**Issue by djbacad** [tensorflow/tensorflow#50652]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy A50
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.7.2

**Describe the current behavior**

Currently following along this [guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/android) to measure performance of tf-lite models. When doing this: 

`adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/non-quantized.tflite --enable_op_profiling=true `

I am able to successfully return results like this: 

`Average inference timings in us: Warmup: 432930, Init: 35157, no stats: 387831`

However, when I'm using a quantized version of the model:

`adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/quantized.tflite --enable_op_profiling=true` 

I am getting this error

```
Loaded model /data/local/tmp/quantized.tflite
resolved reporter
ERROR: Didn't find op for builtin opcode 'CONV_2D' version '5'

ERROR: Registration failed.

Failed to construct interpreter
Aborted
```

**Comment by abattery** [comment]
Please make sure that the TensorFlow version of the benchmark tool is the same or higher version than the TensorFlow version used for the TensorFlow Lite conversion.

**Comment by djbacad** [comment]
> Please make sure that the TensorFlow version of the benchmark tool is the same or higher version than the TensorFlow version used for the TensorFlow Lite conversion.

Thanks. I was able to resolve it by using TF v2.5.0 both for the benchmark tool and the TF lite conversion. 
Just one quick question before I close the issue:
In terms of inference time, what is expected for quantized versions of model? Higher or Lower?

**Comment by ymodak** [comment]
What inference timings do you observe in quantized version vs non-quantized version?
Performance improvement is observed for some well know models listed here https://www.tensorflow.org/lite/performance/measurement#android_performance_benchmarks
