### ISSUE TITLE
Tensorflow int32 matmul slower than float32 matmul

### ISSUE THREAD

**Issue by yunjiangster** [tensorflow/tensorflow#50654]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.4
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v1.15.3-68-gdf8c55c 1.15.4

**Describe the current behavior**
int32 matmul is almost twice as slow as float32 matmul for large-ish matrices.

**Describe the expected behavior**
int32 multiplication is typically faster on CPU, so I expect matmul speed should be at least close to that of float32. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import time
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
for dtype in [tf.float32, tf.int32, tf.float32, tf.int32]:
  a = tf.constant([list(range(int(1e6), int(1e6) + 1024)) for _ in range(1024)], dtype=dtype)
  start = time.time()
  with tf.Session() as sess:
    for _ in range(100):
        sess.run(tf.matmul(a, a))
  end = time.time()
  print(dtype, end - start)
```
print result:

> <dtype: 'float32'> 5.6830058097839355
> <dtype: 'int32'> 7.759643077850342
> <dtype: 'float32'> 3.646965742111206
> <dtype: 'int32'> 8.087013483047485

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@yunjiangster ,

We see that you are using tf version 1.15, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.Thanks!

**Comment by yunjiangster** [comment]
@tilakrayal I tried this on tf2.5 (latest from pip packages) and the same issue persists:

```
import tensorflow as tf
import time
for dtype in [tf.float32, tf.int32, tf.float32, tf.int32]:
  a = tf.constant([list(range(int(1e6), int(1e6) + 1024)) for _ in range(1024)], dtype=dtype)
  start = time.time()
  for _ in range(100):
    tf.matmul(a, a)
  end = time.time()
  print(dtype, end - start)
```

> <dtype: 'float32'> 0.3444669246673584
> <dtype: 'int32'> 2.04129958152771
> <dtype: 'float32'> 0.2095959186553955
> <dtype: 'int32'> 2.0492682456970215

**Comment by tilakrayal** [comment]
@rmothukuru ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/22cdd66c42b58dc3d2a09e1b6aaec601/untitled50654.ipynb).

**Comment by cantonios** [comment]
If this is running on CPU via Eigen, note that Eigen has optimized implementations for float that uses explicit AVX simd instructions.  This is not currently implemented for int32 (though there is an MR [here](https://gitlab.com/libeigen/eigen/-/merge_requests/489)).

**Comment by mohantym** [comment]
I was able to reproduce this issue in [2.8](https://colab.sandbox.google.com/gist/mohantym/04eda407014ef7951e3986a2ca817ba6/git_50654.ipynb#scrollTo=NneCJM36cle3), [2.9](https://colab.sandbox.google.com/gist/mohantym/44ec8268809535db0ebd0e872abce315/git_50654.ipynb#scrollTo=GfwI8NHNaRC6) and [nightly](https://colab.sandbox.google.com/gist/mohantym/f7bfd654466064c22b398e7171b1c1ca/git_50654.ipynb).

**Comment by cantonios** [comment]
Eigen's optimized implementations are in.  Note that the [integer multiply instructions](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_mullo_epi32&ig_expand=5055,4960,5055,5055) just are much slower than [floating point ones](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_mul_ps&ig_expand=5055,4960,5055,5055,4960), so it will always be the case that int32 matmuls are slower than float32 matmuls.  If you absolutely need the speed, and if you know your numbers fall within the range of floats, you could always cast back and forth.
