### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'add_slot'

### ISSUE THREAD

**Issue by RedJyve** [tensorflow/tensorflow#50659]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.4
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): built on tf 2.5.0 converted on tf_nightly 2.7.0-dev20210707

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
(You can paste links or attach files by dragging & dropping them below)
- Include code to invoke the TFLite Converter Python API and the errors.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    tflite_quant_model = converter.convert()

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "/Users/redjyve/PycharmProjects/particleflow/quantization_convert_test.py", line 12, in <module>
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1353, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 863, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 902, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/Users/redjyve/PycharmProjects/particleflow/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'

**Comment by abattery** [comment]
The above error is coming from the TF saved model library while loading the saved model with the user objects.

**Comment by RedJyve** [comment]
Thanks for pointing that out, it was part of the converting process so I thought I would just post it here, but I'll do it differently in the future.

**Comment by ymodak** [comment]
Can you please share a reproducible code to validate the issue? Thanks!

**Comment by RedJyve** [comment]
Sure

Here is the link:
[collab](https://colab.research.google.com/drive/1KwygD93TKndmIgZTQQVQzhzwN2nbAOzB?usp=sharing)

Here is the saved model directory:
[model_full_real.zip](https://github.com/tensorflow/tensorflow/files/6793257/model_full_real.zip)

**Comment by ymodak** [comment]
I successfully converted your model into tflite by setting `custom_ops = True`. I have used TF 2.5 for conversion.
See [gist](https://colab.research.google.com/gist/ymodak/fa1aec30c936a85ed357f0c612676e42/add_slot_error_reproduction.ipynb)

**Comment by abattery** [comment]
@ymodak , it would be better to suggest using TF select op instead of custom ops since the custom ops require user implemented TFLite ops.

**Comment by ymodak** [comment]
Thanks for the pointer. I see that the conversion fails without `custom_ops` and using TF select ops.
See [gist](https://colab.research.google.com/gist/ymodak/9e26b08a1ab1bd80712aadc88626519d/add_slot_error_reproduction.ipynb)

**Comment by Practical-AI** [comment]
@RedJyve 
I had the same issue. I loaded the model in the same notebook that I was converting the samed_model to tflite and it solved the issue. I assume TensorFlow recognizes the used objects in RAM and it prevents further errors.
