### ISSUE TITLE
Quadratic runtime behavior in model.fit/predict with tf.keras.layers.experimental.preprocessing.TextVectorization

### ISSUE THREAD

**Issue by aucth** [tensorflow/tensorflow#50666]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
O(n^2) runtime behavior when calling model.fit or model.predict with a single TextVectorization layer. E.g. calling predict 2 times with n/2 vectors is twice as fast compared to calling predict one time with n vectors. For model.fit the batch_size seems to reduce the runtime linearly. Runtime seems to be O(n * number_of_iterations).

**Describe the expected behavior**
The runtime should be linear with n (O(n))

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

print(tf.__version__)

# generate some dummy data
n = 1000000
x = np.random.randint(1, 100, (n, 1)).astype(str)
y = np.random.uniform(0, 1, (n, 1))

input = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
vectorization = tf.keras.layers.experimental.preprocessing.TextVectorization()
vectorization.adapt(np.unique(x))
output = vectorization(input)
model = tf.keras.Model(inputs=[input], outputs=[output])
model.compile(loss="mse", optimizer="adam")

# compare runtime of model.fit with different batch_size
# -> for large n, doubling the batch_size halves the execution time!!!
model.fit(x, y, epochs=1,batch_size=32)
model.fit(x, y, epochs=1,batch_size=64)
model.fit(x, y, epochs=1,batch_size=8192)

# compare runtime of model.predict with different input size
# -> for large n, calling predict 2 times with n/2 is twice as fast!!!
pred = model.predict(x,verbose=1)
pred = model.predict(x[:int(n/2)],verbose=1)
pred = model.predict(x[int(n/2+1):],verbose=1)
```

**Other info / logs** 
Observed runtimes. Absolute values may depend on your hardware. Ratios between runtimes should be reproducible.
```
31250/31250 [==============================] - 207s 7ms/step - loss: 3416.8721 (model.fit with batch_size = 32)
15625/15625 [==============================] - 121s 8ms/step - loss: 3416.8367 (model.fit with batch_size = 64)
123/123 [==============================] - 1s 10ms/step - loss: 3416.8489 (model.fit with batch_size = 8192)
31250/31250 [==============================] - 221s 7ms/step (model.predict on n vectors)
15625/15625 [==============================] - 56s 4ms/step (model.predict on n/2 vectors)
15625/15625 [==============================] - 59s 4ms/step (model.predict on n/2 vectors)

```

**Comment by tilakrayal** [comment]
@aucth ,

I ran the code shared and face a different error, please find the [gist](https://colab.research.google.com/gist/tilakrayal/78dd094a8f723caec480dadce6e21e8e/untitled50666.ipynb) here and share all dependencies to replicate the issue or share a colab gist with the reported error.Thanks!

**Comment by aucth** [comment]
@tilakrayal 
Sorry, there was a typo in my code example. I updated my code example above. You can also find the gist [here](https://colab.research.google.com/gist/aucth/9a020572f3427ad3e0f0974be2ae4b2e/untitled50666.ipynb).

**Comment by tilakrayal** [comment]
@aucth ,

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by aucth** [comment]
[Link](https://github.com/keras-team/keras/issues/14915) to the issue on keras.

**Comment by tilakrayal** [comment]
@aucth ,

Can you please feel free to close this issue, since it is already being tracked there? Thanks!
