### ISSUE TITLE
Can tf.function fully support control flow

### ISSUE THREAD

**Issue by liangzelang** [tensorflow/tensorflow#50665]
Hi， In eager mode, control flow is fully supported;
however, in graph mode, Does tf2.x fully support control flow. if so,  we write whether the control flow can be expressed in python statements, or tf2.x specific API 。

**Comment by Saduf2019** [comment]
@liangzelang 
Please check this [documentation](https://www.tensorflow.org/guide/function) it answers all your questions, kindly open a new issue in tensorflow discussion in case of any further queries as this is not a bug or a feat request.
