### ISSUE TITLE
Can't use preprocess_input with mixed precision and Lambda layer

### ISSUE THREAD

**Issue by anth2o** [tensorflow/tensorflow#50668]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac and Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I recently upgraded tensorflow from 2.4 to 2.5 and I have a break in my code that didn't happen before. It is related to the use of mixed precision and preprocessing functions in tf.keras.applications. When using both with a Lambda layer:
```python
input = tf.keras.Input((224, 224, 3), name="image")
tf.keras.layers.Lambda(tf.keras.applications.densenet.preprocess_input, name="x_preprocess")(input)
```
, I have the following error:
```bash
TypeError: x and y must have the same dtype, got tf.float16 != tf.float32
```
You can find a minimal example [here](https://colab.research.google.com/drive/1BrYCu4Bo7Y0D7_MaLbDlFW1_uHzaRuGE?usp=sharing)

The issue isn't raised if I don't use Lambda:
```python
input = tf.keras.Input((224, 224, 3), name="image")
tf.keras.applications.densenet.preprocess_input(input)
```
I can use this solution, but the Lambda layer was useful to group all the preprocessing operations into a single layer.

**Describe the expected behavior**

Before TF 2.5, this worked, so I assume this should still work

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1BrYCu4Bo7Y0D7_MaLbDlFW1_uHzaRuGE?usp=sharing

**Comment by saikumarchalla** [comment]
@anth2o It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!
