### ISSUE TITLE
"Given shapes (...) are not broadcastable" after conversion from tensorflow to tflite

### ISSUE THREAD

**Issue by floriandotpy** [tensorflow/tensorflow#50676]
### 1. System information

-    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
-    TensorFlow installation (pip package or built from source): `tb-nightly==2.6.0a20210706` installed via pip

### 2. Code

I am trying to convert a model from Pytorch -> ONNX -> Tensorflow -> tflite. The conversion works, but the results diverge between Tensorflow and tflite.

The original model is a Faster-RCNN with a ResNet backbone (`torchvision.models.detection.fasterrcnn_resnet50_fpn` to be exact).

```python
import tensorflow as tf
import numpy as np

# tensorflow inference: works
model_tf = tf.saved_model.load('assets/tfsavedmodel')
sample = np.zeros((1, 3, 256, 256), dtype=np.float32)
model_tf(input=sample)  #works

# tflite inference: fails
interpreter = tf.lite.Interpreter('model-conversion/assets/model.tflite')
model_tflite = interpreter.get_signature_runner()
out_tflite = model_tflite(input=sample)
```

Fails with error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/florian/projects/video-analysis-prototype/model-conversion/venv/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 231, in __call__
    self._interpreter.allocate_tensors()
  File "/home/florian/projects/video-analysis-prototype/model-conversion/venv/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 453, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Given shapes, [1, 199, 199, 256] and [1, 200, 200, 256], are not broadcastable.Node number 365 (ADD) failed to prepare.
```

Model files mentioned can be found here: https://florianletsch.de/media/assets-tflite.zip (468 MB)

The model was converted following the answer on that issue: https://github.com/tensorflow/tensorflow/issues/50635
**Conversion code** (full conversion code:  https://github.com/florianletsch/torch2tflite-failing):

```
converter = tf.lite.TFLiteConverter.from_saved_model('assets/tfsavedmodel')
converter.experimental_enable_resource_variables = True  # requires tf-nightly or tf-nightly-cpu
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS
]

tflite_model = converter.convert()
with open('assets/model.tflite', 'wb') as f:
    f.write(tflite_model)
```

### 3. Failure after conversion

- Conversion works but model can't be loaded for inference, see error message above.

### Environment 

Output of `pip freeze`

```
absl-py==0.13.0
astunparse==1.6.3
cachetools==4.2.2
certifi==2021.5.30
chardet==4.0.0
flatbuffers==1.12
gast==0.4.0
google-auth==1.32.1
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.38.1
h5py==3.1.0
idna==2.10
keras-nightly==2.6.0.dev2021062500
Keras-Preprocessing==1.1.2
libclang==12.0.0
Markdown==3.3.4
netron==5.0.0
numpy==1.19.2
oauthlib==3.1.1
onnx==1.9.0
onnx-tf==1.8.0
onnxruntime==1.8.0
opt-einsum==3.3.0
Pillow==8.3.1
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.15.0
tb-nightly==2.6.0a20210706
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-addons==0.13.0
termcolor==1.1.0
tf-estimator-nightly==2.6.0.dev2021062501
tf-nightly-cpu==2.7.0.dev20210706
torch==1.9.0
torchvision==0.10.0
typeguard==2.12.1
typing-extensions==3.7.4
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.12.1
```

**Comment by MeghnaNatraj** [comment]
@wangtz Re-assigning to support rotation. 

Initial debugging:
Possible issues:
1. TF model - Not possible (the model works as shows by the user)
2. TFLite model (error during conversion)- Possible. It looks there is an issue with the TFLite model itself as the interpreter is unable to allocate tensors. 
3. TF and TFLite model input - Not possible. Unlike similar issues that have the same error (eg: #46686), in this issue the TF & TFLite model input type is correct. (Refer to below code snippet (the commented print and Output statements)).

```
import tensorflow as tf
import numpy as np

# # tensorflow inference: works
model_tf = tf.saved_model.load('gdrive/MyDrive/Colab Notebooks/tfsavedmodel')
# print("TF model Input shape: ", model_tf.signatures['serving_default'].structured_input_signature[1]['input'])
# Output: TensorSpec(shape=(None, 3, 256, 256), dtype=tf.float32, name='input')
sample = np.zeros((1, 3, 256, 256), dtype=np.float32)
model_tf(input=sample)  #works

# tflite inference: fails
interpreter = tf.lite.Interpreter('model.tflite')
# print("TFLite model input shape: ", interpreter.get_input_details()[0]['shape'])
# Output: [  1   3 256 256]
interpreter.allocate_tensors() 
# Fails here with error: RuntimeError: Given shapes, [1, 199, 199, 256] and [1, 200, 200, 256], are not broadcastable.Node number 365 (ADD) failed to prepare.
# model_tflite = interpreter.get_signature_runner()
# out_tflite = model_tflite(input=sample)
```

**Comment by wangtz** [comment]
I managed to reproduce this issue in https://colab.research.google.com/drive/1B88EAjAvXw0RKhM_mDN6OEbWznLfcz2_#scrollTo=7ZG29GucZ6J6


The model seems to be alright. Node 365 has both input tensors with shape [1, 200, 200, 256] 
I didn't find where 199 is coming from. My best guess is that some where in the Prepare method, the shape was changed incorrectly.

<img width="999" alt="Screen Shot 2021-07-26 at 7 51 55 PM" src="https://user-images.githubusercontent.com/34290063/126984391-ea92e23d-01a6-4c9f-8269-67d14bd3de05.png">

**Comment by pjpratik** [comment]
@floriandotpy I was trying to reproduce this issue in TF 2.11. I got the error while inferring the saved tf model. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/d71fe121cd1151ff5cac8fb633f46f54/50676.ipynb). Thank you.

**Comment by vankhoa01** [comment]
Hi @wangtz @pjpratik @floriandotpy ,

I'm beginner and today, I  tried to train the model with TensorFlow and the model is working well with testing script, please see video below:
https://github.com/tensorflow/flutter-tflite/assets/8953129/4e174215-aa59-49c4-b8a5-b6cdd2b1ad81

After that, I convert exported graph file into TFLite model file with script below:
<img width="1026" alt="Screenshot 2023-09-14 at 12 15 58 PM" src="https://github.com/tensorflow/flutter-tflite/assets/8953129/37a02113-ee6a-4798-af39-0e614ac32e80">

Then I used tflite model with live_object_detection_ssd_mobilenet sample, and I got this issue.
<img width="897" alt="Screenshot 2023-09-14 at 12 18 02 PM" src="https://github.com/tensorflow/flutter-tflite/assets/8953129/31a53312-a701-4302-957a-2b688604590d">

Here's tflite model file:
[ssd_mobilenet.tflite.zip](https://github.com/tensorflow/tensorflow/files/12607611/ssd_mobilenet.tflite.zip)
And Colab: https://colab.research.google.com/drive/1JTLHChxUtmpSBUfroFoLvlNyNBbvmryt?authuser=1#scrollTo=d2AoKvqghCX5

Do you have any solution to fix it ?
Thank you so much

**Comment by m-lafont** [comment]
Hi everyone ! I am also trying to convert a pytorch model -> ONNX -> TF -> TFLite to use it on a Coral USB Accelerator. I converted the model in TF using the SavedModel format but when trying to do the int8 quantization I get a similar issue as @floriandotpy : "Given shapes, [1,199,271,256] and [1,200,272,256], are not broadcastable. Node number 197 (ADD) failed to prepare. " . I am using TF == 2.13.1 and here is my code to convert : 
```
def representative_dataset(): 
    for _ in range(0,100):

        # Yield the image in the required format
        yield [tf.random.uniform(shape=[3,800, 1067], minval=0, maxval=256, dtype=tf.float32)] # [tf.cast(tf.random.uniform(shape=[3,800, 1067], minval=0, maxval=256, dtype=tf.int32), tf.uint8)] 


converter = tf.lite.TFLiteConverter.from_saved_model("TF_TFLITE/output2_fixed_input_3_800_1067_tf_2.13.1")

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_dataset

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS ] # tf.lite.OpsSet.SELECT_TF_OPS  tf.lite.OpsSet.TFLITE_BUILTINS
# converter.target_spec.supported_types = [tf.int8]

converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8

converter.experimental_new_converter = True
converter.experimental_enable_resource_variables = True

# converter.experimental_new_quantizer = True

tflite_quant_model = converter.convert()

```
I can convert the model without quantization, when I am looking at node 197 on Netron there is no problem : 

![Screenshot from 2024-05-28 10-45-01](https://github.com/tensorflow/tensorflow/assets/60701600/b2746a5d-f521-47e6-935d-016746bebb70)

Have you find a way @floriandotpy to convert the model to TFLITE ? 

Thanks in advance !
