### ISSUE TITLE
Internal: libdevice not found at ./libdevice.10.bc

### ISSUE THREAD

**Issue by Nason-S** [tensorflow/tensorflow#50670]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOS 7.4 

- TensorFlow installed from (source or binary): pip install 
- TensorFlow version: 1.15
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip 

- CUDA/cuDNN version:
Cudatoolkit 10.0.130, cuDNN 7.6.5.32

- GPU model and memory:
```
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:15:00.0 Off |                    0 |
| N/A   37C    P0    53W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |

```

**Describe the problem**

I'm trying to run my tensorflow based project on a cluster, I've installed all relevant dependencies within my anaconda environment the exact same way I did on my local machine where the project runs but I'm getting this error message:

    tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
      (0) Internal: libdevice not found at ./libdevice.10.bc
             [[{{node cluster_2_1/xla_compile}}]]
             [[cluster_1_1/merge_oidx_20/_1]]
      (1) Internal: libdevice not found at ./libdevice.10.bc
             [[{{node cluster_2_1/xla_compile}}]]

**Any other info / logs**

```
2021-06-30 08:27:50.484735: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:69] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
    2021-06-30 08:27:50.484775: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:70] Searched for CUDA in the following directories:
    2021-06-30 08:27:50.484781: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   ./cuda_sdk_lib
    2021-06-30 08:27:50.484784: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   /usr/local/cuda
    2021-06-30 08:27:50.484787: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:73]   .
    2021-06-30 08:27:50.484791: W tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:75] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work. 
```

This section of the traceback makes me think that tensorflow is searching for cuda locally instead of within the conda environment, to fix this do I need to set the XLA_FLAGS to `/u/usr/anaconda3/envs/Project_BM/lib/libdevice.10.bc`, if not where can I find the `/cuda/` directory within the `Project_BM` environment? 

Its also worth knowing that I'm running this on a cluster so I don't have root permissions.

Full traceback - https://pastebin.com/njqNFWvC

**Comment by UsharaniPagadala** [comment]
@Nason-S 

Kindly upgrade to 2.x stable version as there is no active support for 1.x, and let us know if the issue persist.
Please refer the similar issues [#4452](https://github.com/google/jax/issues/4452) and [#17801](https://github.com/tensorflow/tensorflow/issues/17801).
For latest test build configurations please refer [this](https://www.tensorflow.org/install/source#gpu)
and as you are building in conda env please refer [link](https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/) and let us know if it helps.
Thanks

**Comment by Nason-S** [comment]
Thanks for the links, @martiningram answer found at #4452 was the solution to this issue.

**Comment by mhmatsumura** [comment]
For those using miniconda just copy de file libdevice.10.bc into the root folder of python application or notebook. 

It´s works here using  python=3.9, cudatoolkit=11.2, cudnn=8.1.0, and tensorflow==2.9
