### ISSUE TITLE
How to use weights to create a new op in Tensorflow

### ISSUE THREAD

**Issue by Lucy20211** [tensorflow/tensorflow#50675]
I'd like to define a convolutional op by following this: https://www.tensorflow.org/guide/create_op. How can I access filter weights in the Compute method? In the call to the REGISTER_OP macro, should I define filter dimensions? Where the weights are updated?

**Comment by UsharaniPagadala** [comment]
@Lucy20211 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow)/ TF [Forum](https://discuss.tensorflow.org/) There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. 
Thanks!

**Comment by Lucy20211** [comment]
Ok, sorry.

**Comment by UsharaniPagadala** [comment]
@Lucy20211 

Could you please move this to closed status and open  new issue with mentioned links above.Thanks!
