### ISSUE TITLE
InvalidArgumentError: No OpKernel was registered to support Op 'QuantizedMatMulWithBiasAndDequantize'

### ISSUE THREAD

**Issue by peiwenhuang27** [tensorflow/tensorflow#50686]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Google Colab
- TensorFlow installed from: binary
- TensorFlow version: 2.4.0
- Python version: 3.7
- (run on CPU)

I used a quantization package [LPOT](https://github.com/intel/lpot) supported with [Intel-Tensorflow](https://github.com/Intel-tensorflow/) to quantize my model, and ran inference under native Tensorflow environment.

**Describe the current behavior**
The Quantized kernel does not seem to have registered OpKernel.

**Describe the expected behavior**
The session should run fine and print the MSE loss, which is the case for my trained & un-quantized TF 2.4 frozen pb model (converted from keras model).

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No

**Other info / logs** 

Source code:
`with tf.compat.v1.Session(graph=graph) as sess:`
 `       output = graph.get_tensor_by_name(output_tensor_name)`
`        predictions = sess.run(output, {input_tensor_name: x})`
 `       mse = tf.reduce_mean(tf.keras.losses.mean_squared_error(y, predictions))`
  `      print(mse.eval())`

**Traceback:**

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1374     try:
-> 1375       return fn(*args)
   1376     except errors.OpError as e:

8 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1357       # Ensure any changes to the graph are reflected in the runtime.
-> 1358       self._extend_graph()
   1359       return self._call_tf_sessionrun(options, feed_dict, fetch_list,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _extend_graph(self)
   1397     with self._graph._session_run_lock():  # pylint: disable=protected-access
-> 1398       tf_session.ExtendSession(self._session)
   1399 

InvalidArgumentError: No OpKernel was registered to support Op 'QuantizedMatMulWithBiasAndDequantize' used by {{node model/dense/Tensordot/MatMul_eightbit_requantize}} with these attrs: [input_quant_mode="MIN_FIRST", Toutput=DT_FLOAT, T1=DT_QUINT8, T2=DT_QINT8, Tbias=DT_QINT32, transpose_a=false, transpose_b=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[model/dense/Tensordot/MatMul_eightbit_requantize]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-ade3637a3169> in <module>()
----> 1 loss = inference(path_to_pb='./model.pb',                  
input_tensor_name='x:0', output_tensor_name='Identity:0',                  
x=x[:64], y=y[:64])

<ipython-input-3-c2f290fad90b> in inference(path_to_pb, input_tensor_name, output_tensor_name, x, y)
     20       with tf.compat.v1.Session(graph=graph) as sess:
     21         output = graph.get_tensor_by_name(output_tensor_name)
---> 22         predictions = sess.run(output, {input_tensor_name: x})
     23         mse = tf.reduce_mean(tf.keras.losses.mean_squared_error(y, predictions))
     24         print(mse.eval())

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    966     try:
    967       result = self._run(None, fetches, feed_dict, options_ptr,
--> 968                          run_metadata_ptr)
    969       if run_metadata:
    970         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1189     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1190       results = self._do_run(handle, final_targets, final_fetches,
-> 1191                              feed_dict_tensor, options, run_metadata)
   1192     else:
   1193       results = []

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1367     if handle is None:
   1368       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1369                            run_metadata)
   1370     else:
   1371       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1392                     '\nsession_config.graph_options.rewrite_options.'
   1393                     'disable_meta_optimizer = True')
-> 1394       raise type(e)(node_def, op, message)
   1395 
   1396   def _extend_graph(self):

InvalidArgumentError: No OpKernel was registered to support Op 'QuantizedMatMulWithBiasAndDequantize' used by node model/dense/Tensordot/MatMul_eightbit_requantize (defined at <ipython-input-2-28418ad07e47>:24)  with these attrs: [input_quant_mode="MIN_FIRST", Toutput=DT_FLOAT, T1=DT_QUINT8, T2=DT_QINT8, Tbias=DT_QINT32, transpose_a=false, transpose_b=false]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

**Comment by peiwenhuang27** [comment]
By the way, my goal is to load this model on ML.NET framework for inference. So any help/suggestions on how this issue could be resolved on ML.NET is also greatly appreciated!

**Comment by ymodak** [comment]
Perhaps you want to post this issue on https://github.com/intel/lpot or https://github.com/Intel-tensorflow/tensorflow repositories for better assistance.
On a side note: TensorFlow has its own [TFMOT](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot) library for quantization related tooling.
