### ISSUE TITLE
Provide XLA as a standalone library

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#50681]
**System information**
- TensorFlow version (you are using): n/a
- Are you willing to contribute it (Yes/No): Maybe, depends on the complexity of the problem (my C++ knowledge is minimal).

**Describe the feature and the current behavior/state.**
XLA is packaged with TensorFlow. I'd like to be able to install it as a standalone library.

**Will this change the current api? How?**
I don't really know. It may change the location of XLA files, but not the functionality itself.

**Who will benefit with this feature?**
People using XLA without TensorFlow, such as (possibly) JAX, but also my project.

**Comment by rnett** [comment]
This would be useful for me, as well.

**Comment by PSilvestre** [comment]
This would also be useful for me! We want to use XLA for a research project.

**Comment by joelberkeley** [comment]
there is something like this in [elixir-nx/xla](https://github.com/elixir-nx/xla), see [this comment](https://github.com/google/jax/issues/2861#issuecomment-920410280)

**Comment by joelberkeley** [comment]
this looks promising https://github.com/openxla/xla

**Comment by mihaimaruseac** [comment]
That is indeed the separated XLA. TF will still use a vendored in copy of XLA for now though, but I think this can be now closed?

**Comment by joelberkeley** [comment]
Yes, looks like it. That's awesome, thanks
