### ISSUE TITLE
Add support for WebP decoding in tf.io.decode_image

### ISSUE THREAD

**Issue by gtoderici** [tensorflow/tensorflow#50683]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

tf.io.decode_image does not support WebP decoding. This makes using tfds and loading lsun/car impossible to use due to the fact that all images are encoded in WebP. 

I'm somewhat surprised that DecodeImageV2Op doesn't support this relatively popular file format.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
All researchers trying to move away from using JPEG

**Any Other info.**
The code needed to decode WebP already exists in Tensorflow in:
https://www.tensorflow.org/io/api_docs/python/tfio/image/decode_webp

**Comment by bhack** [comment]
I think it is a dup of https://github.com/tensorflow/io/issues/930

**Comment by gtoderici** [comment]
It is a dupe indeed.
