### ISSUE TITLE
Build tensorflow-lite for armv7-a (embedded linux) failed？

### ISSUE THREAD

**Issue by yangyuimmerse** [tensorflow/tensorflow#50692]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

> 

**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04 LTS
-target platform - embedded linux - OS Openwrt, CPU - IMX6ULL;
TensorFlow installed from source:
TensorFlow version: 2.4.2
Cross compilation using C++ and CMake. CMake version - 3.16.0

**Describe the problem**
Trying to cross-compile Tensorflow-lite minimal c++ example using CMake.

`cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc   -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++   -DCMAKE_C_FLAGS="${ARMCC_FLAGS}"   -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}"   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON   -DCMAKE_SYSTEM_NAME=Linux    -DCMAKE_SYSTEM_PROCESSOR=armv7-a   ../tensorflow-2.4.2/tensorflow/lite/
`

The results are as follows

> -- Available targets (use: make TARGET):
-- ---------+--------------------------------------------------------------
-- Target   |   Description
-- ---------+--------------------------------------------------------------
-- install  | Install Eigen. Headers will be installed to:
--          |     <CMAKE_INSTALL_PREFIX>/<INCLUDE_INSTALL_DIR>
--          |   Using the following values:
--          |     CMAKE_INSTALL_PREFIX: /usr/local
--          |     INCLUDE_INSTALL_DIR:  include/eigen3
--          |   Change the install location of Eigen headers using:
--          |     cmake . -DCMAKE_INSTALL_PREFIX=yourprefix
--          |   Or:
--          |     cmake . -DINCLUDE_INSTALL_DIR=yourdir
-- doc      | Generate the API documentation, requires Doxygen & LaTeX
-- blas     | Build BLAS library (not the same thing as Eigen)
-- uninstall| Remove files installed by the install target
-- ---------+--------------------------------------------------------------
-- 
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT - Success
**And then it doesn't go down，What should I do?**

**Comment by yangyuimmerse** [comment]
The build was not executed. What did I do wrong？

**Comment by ymodak** [comment]
Are you following the steps mentioned in https://www.tensorflow.org/lite/guide/build_cmake?
