### ISSUE TITLE
TFLite Variable Batch Size for Models

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#50695]
Lets say my TFLite Model (mobilenet_v1) whose size is [1,224,224,3] where 1 is batch size.

I want to run for batch size 2. 

```
l = np.ones((2,224,224,3), dtype = 'float32');
interpreter.reset_all_variables()
interpreter.resize_tensor_input(0, [2, 224, 224, 3])
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]["index"], l)
interpreter.invoke()
```

Will the code I mentioned works for any TFLite model irrespective of any operations involved in model ?
Can I rely on the code for any TFLite Model ?

I got issue with Variable sequence length for few models. So wanted to confirm whether the same issue holds for variable batch size . 
Variable Sequence length is not supported for few operations - https://github.com/tensorflow/tensorflow/issues/44819 (confirmed from this issue).
So needed a confirmation regarding the support of variable batch size and usage of the code I mentioned.

**Comment by pranathibl** [comment]
Needed update

**Comment by pkgoogle** [comment]
Hi @pranathibl, we currently do not support dynamic input shapes: https://www.tensorflow.org/lite/guide/inference#run_inference_with_dynamic_shape_model So the input shape has to be the same as the original converted model.
