### ISSUE TITLE
Error log when using Dataset.group_by_window with Dataset.padded_batch

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#50693]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: 2.6.0rc0
- Python version: 3.6.9

**Describe the current behavior**

In TensorFlow 2.6.0rc0, an error log is emitted when `tf.data.Dataset.padded_batch` is used in the `reduce_func` of `tf.data.Dataset.group_by_window`.

This code did not log any error in previous TensorFlow versions.

**Describe the expected behavior**

No errors should be logged for this operation.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? no
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**

Here's a dummy example to reproduce the log:

```python
import tensorflow as tf

batch_size = 5

def key_func(element):
    return tf.size(element, out_type=tf.int64)

def reduce_func(key, dataset):
    return dataset.padded_batch(batch_size, padded_shapes=tf.TensorShape([None]))

dataset = tf.data.Dataset.from_tensor_slices(["a", "bb", "ccc"])
dataset = dataset.map(tf.strings.bytes_split)
dataset = dataset.group_by_window(key_func, reduce_func, window_size=batch_size)
next(iter(dataset))
```

**Other info / logs**

The code above logs the following line:

> `2021-07-09 12:04:33.530961: E tensorflow/core/framework/dataset.cc:552] Failed precondition: Cannot compute input sources for dataset of type PaddedBatchDatasetV2, because sources could not be computed for input dataset of type Window`

**Comment by guillaumekln** [comment]
@saikumarchalla This is a C++ error log which is not visible by default on Colab. Please see this [gist](https://colab.research.google.com/drive/1YTo60nZzCeXl2VCb1tOW55yGNg-o0ZQP?usp=sharing) to reproduce on Colab.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue on colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/458b9a6b2d7f5ad51912a156999c8152/window_padded_dataset.ipynb).

**Comment by Saduf2019** [comment]
@guillaumekln 
Can you please try with the [tested configurations](https://www.tensorflow.org/install/source#gpu) and let us know if the issue persist.

**Comment by guillaumekln** [comment]
I did not compile TensorFlow from the source, so I'm not sure how this link is relevant to this issue?

The issue I'm reporting is in the binary release of TensorFlow 2.6.0rc0.

**Comment by Saduf2019** [comment]
@guillaumekln 
Irrespective of the source, this link has the tested configurations, so that one does not face such issues, can you please try and let us know.

**Comment by guillaumekln** [comment]
I'm testing the release candidate of TensorFlow 2.6 and reporting this issue early so that developers can fix the bug before the final release. I think that is the goal of a release candidate.

I know this issue did not exist before, but that is not the point. This issue should be fixed in future releases.

**Comment by aaudiber** [comment]
Thanks for reporting this @guillaumekln! The issue was fixed in master but the fix wasn't cherry-picked to the release branch. It should be fixed by https://github.com/tensorflow/tensorflow/pull/50794
