### ISSUE TITLE
tf.saved_model.save() much slower than tf.compat.v1.saved_model.loader.load()

### ISSUE THREAD

**Issue by thierryherrmann** [tensorflow/tensorflow#50705]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Ubuntu 18.04.5 LTS
- TensorFlow installed from: binary
- TensorFlow version: 2.3.2
- Python version: 3.8.5
- CUDA/cuDNN version: 11.1.74 / 8.0.5
- GPU model and memory: NVidia Tesla V100-SXM2-32GB

**Describe the current behavior**
To load a `tf.Module` saved with `tf.saved_model.save()`, `tf.saved_model.load()` is much slower than `tf.compat.v1.saved_model.loader.load()`
(4x slower in the attached colab)

**Describe the expected behavior**
Should be approximately the same time.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1baHS4efEYUP_BCvP8OzStMe9zv92vQhs?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
We have strict latency requirements and need to use `tf.compat.v1.saved_model.loader.load()`, extract operations and tensors from the graph to use `session.run()` to meet them.

The same was observed with TF2.5.0

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf [v2.4](https://colab.research.google.com/gist/tilakrayal/7ab322cbb7d7dd770b165ed1af3ebdd1/2-4latency_of_loading_saved_model.ipynb),[v2.5](https://colab.research.google.com/gist/tilakrayal/bfe2a0d3d9eeacfde723419c7ae67c7d/2-5latency_of_loading_saved_model.ipynb) and nightly.Please find the gist here.

**Comment by sachinprasadhs** [comment]
`tf.saved_model.save()` has been deprecated and users are suggested to save a model using `model.save()` method from Tensorflow 2.5 onwards.
Please refer the below warning message and make the necessary changes.

> The object that you are saving contains one or more Keras models or layers. If you are loading the SavedModel with `tf.keras.models.load_model`, continue reading (otherwise, you may ignore the following instructions). Please change your code to save with `tf.keras.models.save_model` or `model.save`, and confirm that the file "keras.metadata" exists in the export directory. In the future, Keras will only load the SavedModels that have this file. In other words, `tf.saved_model.save` will no longer write SavedModels that can be recovered as Keras models (this will apply in TF 2.5).

**Comment by thierryherrmann** [comment]
@sachinprasadhs I'm sorry to contradict you. `tf.saved_model.save()` is absolutely not deprecated.

It's not deprecated even as of TF2.9: https://www.tensorflow.org/versions/r2.9/api_docs/python/tf/saved_model/save

And it is also described in details in the guide (at least as of today): https://www.tensorflow.org/guide/saved_model#saving_a_custom_model

**Comment by sachinprasadhs** [comment]
Sorry for the confusion, Could you try replacing `tf.saved_model.save()` with `model.save()` since it is the suggested way from Tensorflow 2.5 version and let us know if you find any satisfactory improvement. Thanks!

**Comment by thierryherrmann** [comment]
As mentioned in the description we did not save a keras model but a `tf.Module`. And `tf.Module` has no `save()` method. This issue was opened more than 1 year ago with no satisfactory response. We recently joined an organization that uses pytorch. So you can close this issue.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
