### ISSUE TITLE
AttributeError: 'ReLU' object has no attribute '_saved_model_inputs_spec'

### ISSUE THREAD

**Issue by DanBmh** [tensorflow/tensorflow#50702]
Got following error `AttributeError: 'ReLU' object has no attribute '_saved_model_inputs_spec'` when trying to export a model (`tf.keras.models.save_model`) with an `input_signature`.

-> I could solve it by switching `tensorflow.keras.layers.ReLU()(x)` to `tf.nn.relu(x)`

<br>

Tested in tf=2.4.0
Stack trace:
```
/Scribosermo/extras/exporting/model.py:164 call  *
    x = self.model(x)
/Scribosermo/training/scode/nets/quartznet.py:221 call  *
    x = self.model(x, training=False)
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:786 __call__  **
    outputs = call_fn(cast_inputs, *args, **kwargs)
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/functional.py:424 call
    return self._run_internal_graph(
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/functional.py:560 _run_internal_graph
    outputs = node.layer(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py:1018 __call__
    if self._saved_model_inputs_spec is None:

AttributeError: 'ReLU' object has no attribute '_saved_model_inputs_spec'
```

**Comment by UsharaniPagadala** [comment]
@DanBmh 

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced]. Thanks

**Comment by DanBmh** [comment]
I did use Nvidia's tensorflow container: nvcr.io/nvidia/tensorflow:21.03-tf2-py3
Python version is 3.8.5

I've been trying to export a model with weights loaded from .index and .data-xxx files (exported in tf=2.4). As far as I remember it did not happen with a model loaded directly from saved_model.pb + variables/ (exported in tf=2.3)

The model+exporting code can be found at: https://gitlab.com/Jaco-Assistant/Scribosermo/-/tree/6c5b988e991a878cc3f25c1abd78c03b253dc52e/extras/exporting

**Comment by jvishnuvardhan** [comment]
@DanBmh Can you please share a simple standalone code to reproduce the issue? Thanks!
