### ISSUE TITLE
Failed precondition: Cannot compute input sources for dataset of type PaddedBatchDatasetV2

### ISSUE THREAD

**Issue by LinJM** [tensorflow/tensorflow#50709]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0 rc0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 8.1
- GPU model and memory:

When I use bucket_by_sequence_length function, program appear the following error message: 

2021-07-10 03:46:46.503910: E tensorflow/core/framework/dataset.cc:552] Failed precondition: Cannot compute input sources for dataset of type PaddedBatchDatasetV2, because sources could not be computed for input dataset of type Window

**Comment by guillaumekln** [comment]
Also reported in https://github.com/tensorflow/tensorflow/issues/50693

**Comment by Saduf2019** [comment]
@LinJM 
Can you please try with [tested configurations](https://www.tensorflow.org/install/source#gpu), and let us know if the issue persist.

**Comment by LinJM** [comment]
@Saduf2019 I directly use the binary release of Tensorflow 2.6.0 rc0.

**Comment by Saduf2019** [comment]
@LinJM 
The issue for 2.6 is already reported, please try to use the tested build configurations to avoid this issue which will be resolved in issue mentioned above [50693]
