### ISSUE TITLE
Upgrade Udacity class Docker image.

### ISSUE THREAD

**Issue by vincentvanhoucke** [tensorflow/tensorflow#5070]
Current Docker image uses TF 7.1.0, which is no longer showing on the online documentation page.
Need to:

1- Update to latest stable release.
2- Make sure the assignments still work.
3- Move from b.gcr.io to gcr.io

**Comment by jdamiani27** [comment]
The tensorflow base image is ubuntu 14.04.  I used the following Dockerfile to successfully pip install Pillow 3.x (based on instructions here https://pillow.readthedocs.io/en/3.0.0/installation.html#linux-installation)

```
FROM gcr.io/tensorflow/tensorflow:latest
MAINTAINER Vincent Vanhoucke <vanhoucke@google.com>
RUN apt-get update && apt-get install -y libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev \
 liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
RUN pip install scikit-learn pyreadline Pillow
RUN rm -rf /notebooks/*
ADD *.ipynb /notebooks/
WORKDIR /notebooks
CMD ["/run_jupyter.sh"]
```

**Comment by vincentvanhoucke** [comment]
A new image will be published with the next merge from our internal repo.
