### ISSUE TITLE
tf.repeat memory consumption and performance

### ISSUE THREAD

**Issue by denix56** [tensorflow/tensorflow#50712]
Windows 10
TF 2.5.0
Python 3.8
CUDA 11.2
RTX 3060 6 GB

tf.repeat consumes much more memory with axis=0 in comparison if I create the same array with tf.gather.

```
D = 4000
a = tf.ones((D, 20))
Ns = tf.repeat([1000], D)
b = tf.repeat(a, Ns, axis=0)
tf.config.experimental.get_memory_info('GPU:0')
# {'current': 320337920, 'peak': 676338176}
```

```
D = 4000
a = tf.ones((D, 20))
Ns = tf.repeat([1000], D)
Ns_r = tf.range(0, D, dtype=tf.int64)
Ns_r = tf.repeat(Ns_r, Ns)
c = tf.gather(a, Ns_r, axis=0)
tf.config.experimental.get_memory_info('GPU:0')
# {'current': 352337920, 'peak': 352337920}
```

Also my code ( I might share it, but is quite huge) runs 58 sec when I use tf.gather on each iteration and 73 sec when I use repeat, that is a bit strange (as tf.repeat is just a particular case of gather in this case). 
When I add creration of Ns_r on each it too, the time is same, but I do not consider tf.gather as optimal - the elements are ordered and just repeated, while gather does not use this assumption

**Comment by saikumarchalla** [comment]
@denix56 Was able to reproduce the issue in TF 2.5 Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/67ebf3af75b075b1161cafdc78247d2d/untitled114.ipynb#scrollTo=_SNuzVBDwifK). Thanks!
