### ISSUE TITLE
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 13 (FlexRandomStandardNormal) failed to prepare.

### ISSUE THREAD

**Issue by jiangzhen3s** [tensorflow/tensorflow#50714]
hi

i use colab to train and  save an VAE model (use default colab environment ,tensorflow version is 2.5.0)
i want deploy model on jetson nano ,
i install tflite_runtime version is  2.5.0 

when running(  interpreter.allocate_tensors() ) error come:

usr/bin/python3 /home/jz/Desktop/test/demo/testTFLiteRuntime.py
Traceback (most recent call last):
File "/home/jz/Desktop/test/demo/testTFLiteRuntime.py", line 6, in <module>
interpreter.allocate_tensors()
File "/home/jz/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 259, in allocate_tensors
return self._interpreter.AllocateTensors()
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 13 (FlexRandomStandardNormal) failed to prepare.

i think tflite_runtime 2.5.0 is supported RandomStandardNormal op
so i don't know what i missing...

edit:
in colab enviroment,
i install tflite_runtime 2.5.0  and test 
interpreter init well and allocate_tensors() run well too 

https://stackoverflow.com/questions/68341183/jetson-nano-install-tflite-runtime-2-5-0-didt-supported-randomstandardnormal-op

thank you for any help~!!

**Comment by mohantym** [comment]
Hi @jiangzhen3s ! Can you let us know the result after using Select Ops in Supported Ops during TFlite conversion using below code snippet.

```
converter.target_spec.supported_ops = [
 tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
 tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
model_content = converter.convert()
```


Attaching [relevant](https://stackoverflow.com/a/70689423/11530462) thread for reference. Thanks!
