### ISSUE TITLE
TFlite from keras model full integer quantization fails with zero padding

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/tensorflow#50725]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): oneAPI AI Analytics Toolkit
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.10
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Full integer quantization fails with RuntimeError: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 3)Node number 0 (PAD) failed to prepare.

**Describe the expected behavior**
Model should be optimized

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

		def representative_dataset():

			data_dir = pathlib.Path(
				self.helpers.confs["data"]["train_dir"])
			data = list(data_dir.glob(
				'*' + self.helpers.confs["data"]["file_type"]))

			for rimage in data:
				fpath = str(rimage)
				fname = os.path.basename(rimage)

				image = self.data.resize(fpath, self.helpers.confs["data"]["dim"])

				if image.shape[2] == 1:
					image = np.dstack(
						[image, image, image])

				print(image.shape)

				yield [image]

		converter = tf.lite.TFLiteConverter.from_keras_model(model)
		converter.optimizations = [tf.lite.Optimize.DEFAULT]
		converter.representative_dataset = representative_dataset
		converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
		converter.inference_input_type = tf.int8  # or tf.uint8
		converter.inference_output_type = tf.int8  # or tf.uint8
		tflite_model = converter.convert()

**Other info / logs** Include any logs or source code that would be helpful

Shape is (100, 100, 3) - 3D not 4D

  File "/home/nuci71/Acute-Lymphoblastic-Leukemia-TFLite-Classifier/modules/model.py", line 195, in convert_to_tflite_test
    tflite_model = converter.convert()
  File "/home/nuci71/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1058, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/nuci71/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 795, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/nuci71/.local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 522, in _calibrate_quantize_model
    self.representative_dataset.input_gen)
  File "/home/nuci71/.local/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 172, in calibrate
    self._calibrator.Prepare([list(s.shape) for s in sample])
RuntimeError: tensorflow/lite/kernels/pad.cc:79 SizeOfDimension(op_context->paddings, 0) != op_context->dims (4 != 3)Node number 0 (PAD) failed to prepare.

Model:

self.tf_model = tf.keras.models.Sequential([
	tf.keras.layers.ZeroPadding2D(
		padding=(2, 2), input_shape=self.data.X_train.shape[1:]),
	tf.keras.layers.Conv2D(30, (5, 5), strides=1,
		padding="valid", activation='relu'),
	tf.keras.layers.ZeroPadding2D(padding=(2, 2)),
	tf.keras.layers.Conv2D(30, (5, 5), strides=1,
		padding="valid", activation='relu'),
	tf.keras.layers.MaxPooling2D(
		pool_size=(2, 2), strides=2, padding='valid'),
	tf.keras.layers.Flatten(),
	tf.keras.layers.Dense(2),
	tf.keras.layers.Activation('softmax')

**Comment by AdamMiltonBarker** [comment]
Thank you for updating the issue. I thought I would mention if I only use dynamic range quantization the optimization completes.

**Comment by ymodak** [comment]
@AdamMiltonBarker I tried https://www.tensorflow.org/lite/performance/post_training_integer_quant tutorial by adding 
`tf.keras.layers.ZeroPadding2D(padding=(2, 2)),` in the sequential model architecture.
I see that full integer quantization is successful.
Perhaps you may want to refer this tutorial and your example to potentially spot the error prone area.
Thanks!

**Comment by AdamMiltonBarker** [comment]
Hi thanks, could you suggest what you think it is we have been using this model for at least a year it is part of multiple projects the only issue is with optimizer.  Model structure is provided above.

**Comment by AdamMiltonBarker** [comment]
Hi @ymodak ok I see now that it is expecting 4d, the missing reshape is the problem :) At least I think so, retraining now :)

**Comment by AdamMiltonBarker** [comment]
@ymodak ok I see now I was wrong in my understanding of the error, it is expecting 4D,  the issue is no reshape I believe, retraining now :)

**Comment by AdamMiltonBarker** [comment]
Hi @ymodak no sorry not getting there, this architecture is the architecture I intended to use, it is based on a research paper and the model is in use in a number of the our projects, the only issue is here. The goal was to use our architecture on an Arduino board. 

I have also replicated adding zero padding to the tutorial model, but that is a different network. 

Our expected architecture::

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
zero_padding2d (ZeroPadding2 (None, 104, 104, 3)       0
_________________________________________________________________
conv2d (Conv2D)              (None, 100, 100, 30)      2280
_________________________________________________________________
zero_padding2d_1 (ZeroPaddin (None, 104, 104, 30)      0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 100, 100, 30)      22530
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 50, 30)        0
_________________________________________________________________
flatten (Flatten)            (None, 75000)             0
_________________________________________________________________
dense (Dense)                (None, 2)                 150002
_________________________________________________________________
activation (Activation)      (None, 2)                 0
=================================================================

Tutorial architecture:


_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
zero_padding2d (ZeroPadding2 (None, 104, 104, 3)       0
_________________________________________________________________
conv2d (Conv2D)              (None, 100, 100, 30)      2280
_________________________________________________________________
zero_padding2d_1 (ZeroPaddin (None, 104, 104, 30)      0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 100, 100, 30)      22530
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 50, 30)        0
_________________________________________________________________
flatten (Flatten)            (None, 75000)             0
_________________________________________________________________
dense (Dense)                (None, 2)                 150002
_________________________________________________________________
activation (Activation)      (None, 2)                 0
=================================================================

If there is something that you are seeing that I am not please put me out of my misery :)

**Comment by AdamMiltonBarker** [comment]
OK I got it working at least on one epoch, so the issue was the images were not from tensors, so I converted the images to tensors then ran the conversion, doing a full train now, hopefully this will now run on the BLE Sense :)

**Comment by AdamMiltonBarker** [comment]
OK I got it working at least on one epoch, so the issue was the images needed to be converted to an numpy array before passing them to tf.data.Dataset.from_tensor_slices, doing a full train now, hopefully this will now soon be running on the BLE Sense :)

**Comment by AdamMiltonBarker** [comment]
2021-07-13 16:45:13.114543: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2021-07-13 16:45:13.115646: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1144] Optimization results for grappler item: graph_to_optimize
  function_optimizer: function_optimizer did nothing. time = 0.007ms.
  function_optimizer: function_optimizer did nothing. time = 0.001ms.

2021-07-13 16:45:13.141248: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:345] Ignored output_format.
2021-07-13 16:45:13.141279: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:348] Ignored drop_control_dependency.
2021-07-13 16:45:13.143635: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
fully_quantize: 0, inference_type: 6, input_inference_type: 3, output_inference_type: 3
WARNING:absl:For model inputs containing unsupported operations which cannot be quantized, the `inference_input_type` attribute will default to the original type.

**Comment by AdamMiltonBarker** [comment]
Sigh:


New Line
9600 baud
19:3:22.373 -> Didn't find op for builtin opcode 'QUANTIZE' version '1'. An older version of this builtin might be supported. Are you using an old TFLite binary with a newer model?
19:3:22.681 -> 
19:3:22.681 -> Failed to get registration from op code QUANTIZE
19:3:23.118 ->  
19:3:23.665 -> Failed starting model allocation.
19:3:24.108 -> 
19:3:24.646 -> AllocateTensors() failed
19:3:25.590 ->
