### ISSUE TITLE
Model with nested input spec fails

### ISSUE THREAD

**Issue by nicolaspi** [tensorflow/tensorflow#50721]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9

**Describe the current behavior**
The [logic](https://github.com/tensorflow/tensorflow/blob/0d4c07f5ae1b264bdfbae9e4d683d769852d88db/tensorflow/python/keras/engine/functional.py#L266)  to test if a structure is nested is wrong. Example of failing case: `{"a": {"b": 1}}`

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
Change this [line](https://github.com/tensorflow/tensorflow/blob/0d4c07f5ae1b264bdfbae9e4d683d769852d88db/tensorflow/python/keras/engine/functional.py#L266) from:
```python
if (isinstance(self._nested_inputs, (dict, list, tuple)) and
        len(self._nested_inputs) != len(self.inputs)):
```
to:
```python
if max([len(path) for path in nest.yield_flat_paths(
        self._nested_inputs)]) > 1:
```

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np

input_tensor_shape = [16]
random_tensor = np.random.random([1]+input_tensor_shape)

def sequential():
  layers = [tf.keras.layers.InputLayer(input_shape=input_tensor_shape),
            tf.keras.layers.Dense(8)]
  return tf.keras.Sequential(layers=layers)

network = sequential()
network2 = sequential()

nested_input = {'input': {'sub_input1': network.input,
                          'sub_input2': network2.input}}

model = tf.keras.Model(inputs=nested_input, outputs=network.output)

input = {'input': {'sub_input1': random_tensor,
                   'sub_input2': random_tensor}}
# Works
model(input)

fail_nested_input = {'input': {'sub_input': network.input}}
fail_model = tf.keras.Model(inputs=fail_nested_input, outputs=network.output)

input = {'input': {'sub_input': random_tensor}}
# Fails
fail_model(input)
```

**Comment by tilakrayal** [comment]
@nicolaspi ,

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by nicolaspi** [comment]
@tilakrayal  ,

Done

**Comment by tilakrayal** [comment]
@nicolaspi ,

Please feel free to move this to closed status as this issue has been tracked in keras repo.Thanks!
