### ISSUE TITLE
Translate use of Adam Optimizer from TF 1 to TF2 causing TF2 to coredump

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#50727]
**System information**

- OS Platform and Distribution: Ubuntu 21.04
- TensorFlow installed from (source or binary): pip install tensorflow=2.5.0
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3/8/10
- CUDA/cuDNN version: cuda_11.3.r11.3/compiler.29920130_0
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti, 11GB

**Describe the current behavior**

I am trying to translate this [Tensorflow 1 notebook](https://github.com/mgroncki/IPythonScripts/blob/master/BermudanTensorFlow.ipynb) by Matthias Groncki to do Bermudan option pricing, from Tensorflow 1 to Tensorflow 2.

To move from non-eager graph mode with placeholders to eager mode with `tf.function`s, I have had to unroll his code and isolate spots where the unrolling runs into problems.

My use of the Adam optimizer is causing Tensorflow versions 2.4.1 and 2.5 with GPU to coredump. 

NOTE: This is pure Tensorflow 2 code with eager mode on, no use of TF 1 compatibility features, and no use of NumPy.

**Describe the expected behavior**

No coredump.  I think it's coredumping because the expression `y = E_t[:, i+1:i+2]`, where `i=1` and the shape of `E` is (10000,2), is giving an empty tensor for `y` with signature

`    <tf.Tensor: shape=(10000, 0), dtype=float32, numpy=array([], shape=(10000, 0), dtype=float32)>`

Tensorflow could do better than to coredump in this case, there should be guards in the tensor operations to raise exceptions in Python rather than simply die.

**[Contributing](https://www.tensorflow.org/community/contribute)**

I don't know candidate solution, I am not a TF internals programmer.

**Standalone code to reproduce the issue**

```
import tensorflow as tf

N_samples_learn = 10000
N_samples_pricing = 100000
calldates = 2
tf.random.set_seed(7)

N = tf.random.normal((N_samples_learn,calldates))
N_pricing = tf.random.normal((N_samples_pricing,calldates))
(S_0, strike, exTimes, impliedvol, riskfree_r) = (100., 110., tf.constant([1., 1.]), 0.2, 0.03)

number_call_dates = len(exTimes)       
dW = tf.sqrt(exTimes)*N

S=tf.Variable(S_0)
r=tf.Variable(riskfree_r)
sigma=tf.Variable(impliedvol)
previous_exercises = 0

# Last exercise date
with tf.GradientTape() as tape:
    S_t = S * tf.math.cumprod(tf.exp((r-sigma**2/2)*exTimes + sigma*dW), axis=1)
    E_t = tf.exp(-r*tf.cumsum(exTimes))*tf.maximum(S_t-strike, 0)
    inMoney = tf.cast(tf.greater(E_t[:,-1], 0.), tf.float32)
    exercise = inMoney * (1-previous_exercises)
    npv = exercise*E_t[:,-1]
    npv = tf.reduce_mean(npv)

greeks = tape.gradient(npv, [S, r, sigma])

training_functions = []
for i in range(number_call_dates):
    w = tf.Variable(tf.random.normal((3,1))*0.1)
    b = tf.Variable(tf.ones(1)*1)
    training_functions.append((w, b))
    state = S_t[:, i]
    feature_0 = tf.pow(state,0)
    feature_1 = tf.pow(state,1)
    feature_1_mean = tf.reduce_mean(feature_1)
    feature_1_std = tf.sqrt(tf.reduce_sum(tf.square(feature_1 - feature_1_mean))/(N_samples_pricing+1))
    feature_1_norm = (feature_1 - feature_1_mean) / feature_1_std
    feature_2 = 2*tf.pow(state,2)-1
    feature_2_mean = tf.reduce_mean(feature_2)
    feature_2_std = tf.sqrt(tf.reduce_sum(tf.square(feature_2 - feature_2_mean))/(N_samples_pricing+1))
    feature_2_norm = (feature_2 - feature_2_mean) / feature_2_std
    feature_3 = 4*tf.pow(state,3)-3*feature_1
    feature_3_mean = tf.reduce_mean(feature_3)
    feature_3_std = tf.sqrt(tf.reduce_sum(tf.square(feature_3 - feature_3_mean))/(N_samples_pricing+1))
    feature_3_norm = (feature_3 - feature_3_mean) / feature_3_std
    features = tf.stack([feature_1_norm, feature_2_norm, feature_3_norm])
    X = tf.transpose(features)
    contValue = tf.add(tf.matmul(X, w),b)
    inMoney = tf.cast(tf.greater(E_t[:,i], 0.), tf.float32)
    exercise = tf.cast(tf.greater(E_t[:,i], contValue[:,0]), tf.float32) * inMoney * (1-previous_exercises)
    previous_exercises += exercise
    npv += exercise*E_t[:,i]

i=number_call_dates-1

(w, b) = training_functions[i]
y = E_t[:, i+1:i+2]
X = S_t[:, i]

X = tf.stack([X**1, 2*X**2-1, 4*X**3 - 3 * X], axis=1)

X = (X - tf.reduce_mean(X, axis=0)) / tf.math.reduce_std(X, axis=0)

epoch = 0

input_x = X[E_t[:,i]>0]
input_y = y[E_t[:,i]>0]
y_hat = tf.Variable(tf.add(tf.matmul(input_x,w), b))
pre_error = tf.Variable(tf.pow(input_y-y_hat,2))
error = lambda: tf.reduce_mean(pre_error)

opt = tf.keras.optimizers.Adam(learning_rate=0.1)

train = opt.minimize(error, [pre_error])  ### COREDUMP
```
**Note:** I tried to create a simpler coredumpy example like

```
import tensorflow as tf
foo=tf.Variable([[1.,1.]])
foo=foo[:,2:3]
bar=lambda: foo
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
train = opt.minimize(bar, [foo])
```
However, this shorter version doesn't coredump, it instead raises the exception

`AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_in_graph_mode'`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
[tf_log.txt](https://github.com/tensorflow/tensorflow/files/6797227/tf_log.txt)

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/88a77af10d777c8263540f515001476f/untitled50727.ipynb).

**Comment by Saduf2019** [comment]
@catskillsresearch 
Can you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/26922#issuecomment-498812923) and let us know if it helps.

**Comment by catskillsresearch** [comment]
@Saduf2019 I know I can fix the problem for my purposes by not passing a tensor slice which has a 0-d axis.

However it remains that TF is coredumping in that case, which is reproducible.  Coredump is never a good way to raise an exception.  There should be some checking somewhere in the process so that if it is likely to coredump on a tensor with a 0-d axis, then it raises an exception instead.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.11.0-dev20220822. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b96b466af8014d8e3f55aec82700882e/untitled521.ipynb). Thank you!

**Comment by tilakrayal** [comment]
@catskillsresearch,
The reason for the issue is that the tf.keras optimizers apply gradients to variable objects (of type tf.Variable), while you are trying to apply gradients to tensors (of type tf.Tensor). Tensor objects are not mutable in TensorFlow, thus the optimizer cannot apply gradients to it.

You should initialize the variable img as a tf.Variable. This is how your code should be:

 NOTE: The original image is lost here. If this is not desired, then you can
 rename the variable to something like img_var.
```
img = tf.Variable(img)
opt = tf.optimizers.Adam(learning_rate=lr, decay = 1e-6)

for _ in range(epoch):
    with tf.GradientTape() as tape:
        tape.watch(img)
        y = model(img.value())[:, :, :, filter]
        loss = -tf.math.reduce_mean(y)

    grads = tape.gradient(loss, img)
    opt.apply_gradients(zip([grads], [img]))
```
Also, it is recommended to calculate the gradients outside the tape's context. This is because keeping it in will lead to the tape tracking the gradient calculation itself, leading to higher memory usage. This is only desirable if you want to calculate higher-order gradients. Since you don't need those, try to keep them outside.

Note: Please try to change the line y = model(img)[:, :, :, filter] to y = model(img.value())[:, :, :, filter]. This is because tf.keras models need tensors as input, not variables. Thank you!
