### ISSUE TITLE
TF25 inconsistency between eager and graph mode

### ISSUE THREAD

**Issue by roebel** [tensorflow/tensorflow#50728]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes, I use a custom layer.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

CentOS 7, Ubuntu 20.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

not mobile

- TensorFlow installed from (source or binary):

pypi

- TensorFlow version (use command below):

2.5.0

- Python version:

3.7

- CUDA/cuDNN version:

11

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

T2.5 no longer supports creating layers using Conv1D as base class when the derived class 
changes the output shape.

The problem appears only in graph mode, eager mode runs fine

**Describe the expected behavior**

Similar to TF2.4 it should be possible to create new layer types that change the output shape
of the final result by means of deriving from  the Conv1D layer

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):

yes

- Briefly describe your candidate solution(if contributing):

The problem is in  lines 270- 273 in convolutional.py

```
    if not context.executing_eagerly():
      # Infer the static output shape:
      out_shape = self.compute_output_shape(input_shape)
      outputs.set_shape(out_shape)
```

Calling self.compute_output_shape calls the method of the derived class.
This is not providing the correct value.

Proposed solutions:

1) the related lines did not exist in previous versions of TF2, so probably they should simply be removed.
In any case they will introduce a difference in behavior between eager and graph mode.  Which is probably a problem

2) if the explicit imposition of the output shape is required in tf 2.5 then it should be performed like

```
   if not context.executing_eagerly():
      # Infer the static output shape:
      out_shape = Conv.compute_output_shape(self, input_shape)
      outputs.set_shape(out_shape)
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

This script fails on TF2.5  but runs fine on TF2.4. It also runs fine under TF2.5 
once the `@tf.function` annotation is removed

```
import tensorflow as tf
print(tf.version.VERSION)

class MyFlatConv(tf.keras.layers.Conv1D):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

    def compute_output_shape(self, input_shape):

        res_shape = super().compute_output_shape(input_shape)
        return res_shape[0], res_shape[1]*res_shape[2]

    @tf.function
    def call(self, inputs):
        res = super().call(inputs)

        return tf.reshape(res, (res.shape[0], -1))

if __name__ == "__main__":

    mm = MyFlatConv(filters=3, kernel_size=3, padding="same")
    zz= tf.zeros((3,10,3), dtype=tf.float32)
    print(mm(zz))

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/12928bc9a30931dd7fccc69ca3e3e76c/untitled139.ipynb).Thanks

**Comment by Saduf2019** [comment]
@ymodak 
The issue does nor exist in rf 2.4.1, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5ddd86fd982f1431495e75ad1a84a18c/untitled617.ipynb.)

**Comment by jvishnuvardhan** [comment]
@roebel I updated `call` function in your code and everything works in graph and eager modes. [Here](https://colab.research.google.com/gist/jvishnuvardhan/18647fb6109aab893d0f41fc3e36466f/untitled.ipynb) is a gist for reference. Thanks!

```
    @tf.function
    def call(self, inputs):
      # res = super().call(inputs)
      return tf.reshape(inputs, (inputs.shape[0], -1))
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by roebel** [comment]
Hello

thanks for looking into this, but your solution does not solve anything.  You remove the convolution from the graph so the FlatConv model simply does a reshape. It should do a Convolution followed by a reshape. 
Very obviously removing the Convolution operator from a Network that should do convolution + reshape is not an acceptable solution.

For the motivation: This FlatConv layer is supposed to perform upsampling by means of SubPixel convolution as described
here

https://arxiv.org/abs/1707.02937

Subpixel based upsampling has become quite common nowadays. I wanted to create a Conv1D Layer that does both steps. Convolution + reshape by means of deriving from Conv1D. This worked until T2.4 but does no longer work since TF2.5, due to a change in the Conv1D internals I described above and for that a fix in the Conv1D layer is necessary.

**Comment by jvishnuvardhan** [comment]
@roebel Is it possible for you to open this issue in keras-team/keras repo as the development of Keras moved to that repo.

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues). Thanks!

**Comment by roebel** [comment]
Ok I moved the issue.
