### ISSUE TITLE
Docker image tensorflow:latest or tensorflow:2.5.0 is missing git

### ISSUE THREAD

**Issue by snthibaud** [tensorflow/tensorflow#50720]
Following the steps in Docker Linux builds / CPU-only from https://www.tensorflow.org/install/source , I noticed git was missing when issuing git pull. It works with the :devel image, but not with :latest or :2.5.0.
Even installing git manually inside the container is not enough, because the source code is also missing in /tensorflow.
Perhaps the documented steps only work for certain versions?

**Comment by angerson** [comment]
Thanks for the report. Git is missing intentionally, since `devel` and `latest`/`2.5.0` do different things. If you want to contribute to TensorFlow, use `devel`. You can read more here: https://hub.docker.com/r/tensorflow/tensorflow.
