### ISSUE TITLE
tfa.activations.snake - wrong function in docs

### ISSUE THREAD

**Issue by SianoP** [tensorflow/tensorflow#50737]
## URL(s) with the issue:

https://www.tensorflow.org/addons/api_docs/python/tfa/activations/snake

## Description of issue (what needs changing):

The computed function in the source code is:

x + (1 - cos(2*frequency*x)) / (2*frequency)

but the function in the docs is:

(x + (1 - cos(2*frequency*x))) / (2*frequency)

**Comment by PratsBhatt** [comment]
This issue is redundant and can be closed. 

The doc is matching with the code.

**Comment by Saduf2019** [comment]
@PratsBhatt 
Thank you for the update please feel free to move this to closed status.

**Comment by gadagashwini** [comment]
@SianoP,

Given Function is in the doc and source code is same.

```
import tensorflow as tf
frequency = 60
x = tf.constant([-1.0, 0.0, 1.0])
a = x + (1 - tf.cos(2 * frequency * x)) / (2 * frequency)
a
```
`<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.99845153,  0.        ,  1.0015485 ], dtype=float32)>`
