### ISSUE TITLE
Increasing physical memory usage implemented with tensorflow.

### ISSUE THREAD

**Issue by lfch** [tensorflow/tensorflow#50733]
** Version Info **
Version: v3.9.2
Language: C++
OS Version: Centos 7.2 final
Tensorflow version: 2.4
Compiler: g++ 8.3

**What did you do?**
We are ready to use libtensorflow_cc 2.4 on machine learning platform and libtensorflow uses protobuf of which the Arena memory management is a requirement. We use the message GraphDef and SparseWeights (which are variables on stack) to deserialize data from pb files every 10 minutes. We see the usage of physical memory is increasing slowly when our application runs for a long time。
From the manual, I known that Arena is suggested for short-time variables and that is what we did. Using the pmap tool, i  see that a lot of memory are with the type of anonymous mapping, which are allocated by jemalloc.
What can we do to let the physical memory not to increase ?

**What did you expect to see**
The usage of physical memory is not increasing.

**What did you see instead?**
The physical memory is increasing slowly.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
<img width="1072" alt="截屏2021-07-12 下午5 19 13" src="https://user-images.githubusercontent.com/5698293/125266073-04045a80-e338-11eb-9722-a4e3637466ad.png">

**Comment by UsharaniPagadala** [comment]
@lfch 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow.](https://stackoverflow.com/questions/tagged/tensorflow) / Tensorflow [Forum](https://discuss.tensorflow.org/)  There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks
