### ISSUE TITLE
Explanation for GetInvSqrtQuantizedMultiplierExp()?

### ISSUE THREAD

**Issue by ShikharJ** [tensorflow/tensorflow#50738]
Hey everyone,

I was looking at the L2 Normalization routine for TFLite, and noticed the use of `GetInvSqrtQuantizedMultiplierExp` function [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/common.h#L642). While I understand the high level goal of this routine is to find a multiplier which acts as 1 / sqrt(sum_of_squared_inputs) normalizing factor, I'm having trouble understanding how exactly is this computation being done, and what is the purpose and formulation for Newton-Raphson in this function? Any help would be appreciated. Thanks in advance.

**Comment by ymodak** [comment]
This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
