### ISSUE TITLE
Possibility to define operator version

### ISSUE THREAD

**Issue by ItsMeTheBee** [tensorflow/tensorflow#50731]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip package 2.3.0 CPU
- TensorFlow library (version, if pip package or github SHA, if built from source): from installation

### 2. Code

```
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet import preprocess_input

TEST_DIR = "/mnt/Storage/training/unet_multi_class/dataset/kellogs/combo/valid/images"
#IMAGE_SIZE = [480, 640]
IMAGE_SIZE = [256, 256]

#converter = tf.lite.TFLiteConverter.from_saved_model('/media/sally/STORAGE/training/unet_multi_class/conversion/checkpoint')
model=tf.keras.models.load_model("/mnt/Storage/training/unet_multi_class/Multiclass-Segmentation-in-Unet/conversion/model_non_custom_256x256.h5")
converter = tf.lite.TFLiteConverter.from_keras_model(model)

def representative_data_gen():

  dataset_list = tf.data.Dataset.list_files(TEST_DIR + '/*.png')
  for i in range(100):
    image = next(iter(dataset_list))
    image = tf.io.read_file(image)
    image = tf.io.decode_png(image, channels=3)
    image = tf.image.resize(image, IMAGE_SIZE)
    image = tf.cast(image / 255., tf.float32)
    image = tf.expand_dims(image, 0)
    yield [image]

#converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = False
#converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model_quant = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model_quant)
input_type = interpreter.get_input_details()[0]['dtype']
print('input: ', input_type)
output_type = interpreter.get_output_details()[0]['dtype']
print('output: ', output_type)



with open('/mnt/Storage/training/unet_multi_class/Multiclass-Segmentation-in-Unet/conversion/model_non_custom_256x256.tflite', 'wb') as f:
  f.write(tflite_model_quant)
```

### 5. (optional) Any other info / logs

I've trained a UNet model according to these [intructions](https://colab.research.google.com/drive/1CCSM2FLOtHx0dPr1HgHFX0yLAgpOs7eT?usp=sharing#scrollTo=ikrzoG24qwf5) but with two classes instead of three. Converting and compiling the model works fine, but loading the model with the interpreter yields an error.

Error when loading the interpreter:
` Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'`

 I'm on a custom aarch64 system and already needed to build tflite runtime 2.1.0 for python 3.6 and python 3.8 to get it running for other models. Do I need to upgrade to another tflite runtime version and if so which version? Or would it be possible to specify which version of the TRANSPOSE_CONV operator should be used to avoid this error?
 
 Best regards,
Sally

**Comment by tilakrayal** [comment]
@ItsMeTheBee ,

I ran the code shared and face a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/ae5862d7e1811ccecfe41873da8dd0bb/untitled50731.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.
