### ISSUE TITLE
Getting Embeddings from sequence of one-hot vectors 

### ISSUE THREAD

**Issue by Bharathi-A-7** [tensorflow/tensorflow#50739]
TF version : 2.5

Data : Lists of sequences, some of which may contain nested sequences.(As in the example below)

I have input sequences that contain not just single elements, but also lists. 

Eg : i1 = [2, 5, 10, [1, 7 ,9 , 20], 11, 32].

If it were just a sequence like [2,4,6,7] that does not contain a nested sequence, I would just directly pass them to the embedding layer. 

But, in my case, that's not possible. So, I have decided to one-hot encode my sequences. 

For example, 

input = [2, 3, [1,4], 5]

Its one hot representation would be :

```
one_hot = [[0,0,1,0,0,0],
                  [0,0,0,1,0,0],
                  [0,1,0,0,1,0],
                  [0,0,0,0,0,0]]
```
How do I get embeddings for such one hot vector sequences ? Or, could someone suggest better ways to represent my inputs to get embeddings, rather than using one-hot vectors ?

**Comment by tilakrayal** [comment]
@Bharathi-A-7 ,

 
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version,nature of your data].Thanks!

**Comment by Bharathi-A-7** [comment]
@tilakrayal I have updated it. Do you need any more info ? Thanks

**Comment by Saduf2019** [comment]
@Bharathi-A-7 
Can you clarify if your data is text audio, what does the  nested list represent.

**Comment by Bharathi-A-7** [comment]
My data is basically text. I have many ordered sequences of events(like entities representing an event), ordered by their date of occurence. 

So, for each ID, I have a sequence of ordered events. 
Sometimes, multiple events occur on the same day, which leads to nested lists. 

For example, consider the sequence [A, B, [D, C, I, K], M]

This means, Event A occured on day 1, event B on day two, and events[D,C,I,K] on day 3 etc. 
So, given a sequence of events for each unique ID, my goal is to predict what will be the next event/sequence of events. 

I have just converted these events represented by text into integer tokens, and subsequently got their count vectors/one-hot vector representation, which is shown above. But, I'm facing troubles getting embeddings from such an input representation. 

Does that help ?

**Comment by Saduf2019** [comment]
@Bharathi-A-7 
t just encode the entire series and represent it as a single unit which is a number in your case? This method will increase your output nodes but will flatten the nested structure.

A second option may be to pass this list through a separate embedding layer and obtain a single time series or a single value representation of the entire sublist. This may require tuning your embedding size to get the best results but this should work well if the number of events in a sublist is large and it is not possible for you to exhaustively assign a number to all sublist combinations as explained in the first solution

This is not a bug or a Feat Request, kindly open this in tensorfow discussion for any further queries and move this to closed status.

**Comment by Bharathi-A-7** [comment]
Thanks for your answer. I will open this in tensorflow discussion.
