### ISSUE TITLE
Getting Embeddings from nested sequences

### ISSUE THREAD

**Issue by Bharathi-A-7** [tensorflow/tensorflow#50748]
With reference to my previous issue : #50739 

@Saduf2019, I just wanted to get some clarifications on your answer, particularly the second approach. 

```
t just encode the entire series and represent it as a single unit which is a number in your case? This method will increase your output nodes but will flatten the nested structure.

A second option may be to pass this list through a separate embedding layer and obtain a single time series or a single value representation of the entire sublist. This may require tuning your embedding size to get the best results but this should work well if the number of events in a sublist is large and it is not possible for you to exhaustively assign a number to all sublist combinations as explained in the first solution

Example for approach 1:
Original: A,B,[D,E,F],K
Final: A,B,C,K

Example for approach 2:
Original: A,B,[D,E,F],K
After passing [D,E,K] through a trainable embedding layer: A,B,C=flatten(emb([DEK])),K where C is a flattened representation of the output of the embedding layer

```
Supposing I use 250-dimension embeddings, then events A, B would be 250-dim embeddings whereas C would be 3*250 = 750 dim since it is flattened. In that case, how would I be able to pass this input sequence to LSTM since all elements do not have the same dim-embeds ?

**Comment by Saduf2019** [comment]
@Bharathi-A-7 
You wouldn't need such huge embedding vector,please try with one or two dimensional.
you may create a single output dense network and see for yourself.

**Comment by Bharathi-A-7** [comment]
Thanks @Saduf2019, But I'm not entirely sure that I get your idea. 

Could you please provide a small and simple working example in TF to demo the primary and secondary embedding layers that you're describing ? Perhaps for some sample sequences like below: 

1. [A, B, [D, C, E], L]
2. [[S,T,B], M]
3. [M, N, [L,U]]
4. [A, B, L]

Where A, B, C,.. etc are events represented by text and lets say I want to represent those events by embedding vectors of size 50 or 100.  With padding length = 4. In that case, my Input dim should be (None, 4) and the output via embedding layer should be (None, 4, 50) or (None, 4, 100) depending on the vector size. [None - batch size] 

```
With Integer tokens  : 

A - 1, B-2, C-3, D-4, E-5, L-6, M-7, N-8, P-9, S-10, T-11, U-12

The padded sequences would look like this : 

1. [1, 2, [4,3,5], 6, 0]
2. [[10, 11, 2], 7, 0, 0]
3. [7, 8, [6, 12], 0]
4. [1, 2, 6, 0]

Now, could you please provide a working example to get embeddings as output for the sample above sequences? How do I implement primary and seondary embedding layers to get outputs of the form (None, seq_len, dim_len)? It would be a great help, since I'm only a beginner in tensorflow and I'm finding it challenging to design the architecture for this problem. 

Thanks a lot. 

```

**Comment by Saduf2019** [comment]
@Bharathi-A-7 
Kindly open this issue in tensorflow discussion forum or stackoverflow as this is not a feature request or a bug.

**Comment by Bharathi-A-7** [comment]
Okay. I have done the same. Thanks.
