### ISSUE TITLE
In distributed training, different workers get different results from the information

### ISSUE THREAD

**Issue by yeshenyong** [tensorflow/tensorflow#50746]
In distributed training.
The savedmodel model saved by the estimator.
Is it different to save in different workers?
However, I have different results in different savedmodels of different workers for C + + online inference
![43701B~1](https://user-images.githubusercontent.com/52573793/125428034-a7ef27b7-9123-4455-89fa-4ab1ae32ffc6.PNG)

**Comment by jvishnuvardhan** [comment]
@yeshenyong Can you please explain the problem with little more details? Did you save a single model (savedmodel1) and inferencing on three different workers with the same data but noticing different results? Also, add any other details to resolve the issue faster. Thanks!
