### ISSUE TITLE
Custom metric fails with "ValueError: Metric should be a callable"

### ISSUE THREAD

**Issue by obtu** [tensorflow/tensorflow#50749]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 34
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: Python 3.8.10
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Given the _minimal viable program_ below I get an error (also when defining `call` instead of `__call__`):
```
ValueError: Metric should be a callable, found: <__main__.MyLoss object at 0xaddress>
```

**Describe the expected behavior**
I expect the fitting to commence and complete without error.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
```python
import tensorflow.keras as keras
import numpy as np

class MyLoss(keras.losses.Loss):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def __call__(self, x, y):
        return x-y

def get_model():
    i = keras.Input((1,))
    m = keras.layers.Dense(10)(i)
    m = keras.layers.Dense(1)(i)
    return keras.Model(i,m)

m = get_model()
m.compile(loss='mse', metrics=[MyLoss()])
m.fit(np.arange(100), np.arange(100))
```

**Other info / logs**
[Full output](https://gist.github.com/obtu/763908fb4111b5da0f785cb13e1d7d34)

**Comment by saikumarchalla** [comment]
Was able to replicate the issue on colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/3d074af2b2a5dcdbc75116be890ae3e7/untitled112.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
@obtu It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by obtu** [comment]
I have created a new issue at the keras repo: https://github.com/keras-team/keras/issues/14965

**Comment by saikumarchalla** [comment]
@obtu  Closing the issue here since issue was created in keras repo.

**Comment by sfo** [comment]
The solution is to just provide a proper value for the `name` parameter when constructing the Loss object:
```python
m.compile(loss='mse', metrics=[MyLoss("myloss")])
```

More details here: https://github.com/keras-team/keras/issues/14965
