### ISSUE TITLE
quantize.cpp:58 input->type == kTfLiteFloat32 || input->type == kTfLiteInt16 || inp was not true

### ISSUE THREAD

**Issue by AdamMiltonBarker** [tensorflow/tensorflow#50753]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 2.5.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33 BLE Sense

**Describe the problem**

I have converted our CNN to TFLite using full integer quantization (in and out: uint8)
AllocateTensors fails with quantize.cpp:58 input->type == kTfLiteFloat32 || input->type == kTfLiteInt16 || inp was not true

![all_nano_33_ble_sense](https://user-images.githubusercontent.com/6291410/125519397-d10a8aa4-e1c9-4631-b896-a4f59b23aeee.png)

**Comment by tilakrayal** [comment]
@AdamMiltonBarker ,

This issue is more suitable for TensorFlow Micro repo. Please post it on [tflite/micro](https://github.com/tensorflow/tflite-micro/issues) repo from here. Thanks!

**Comment by AdamMiltonBarker** [comment]
Did do thanks.
