### ISSUE TITLE
Dynamic-sized CoreML Delegate

### ISSUE THREAD

**Issue by tylerweitzman** [tensorflow/tensorflow#50758]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The TensorflowLite Core ML delegate currently does not support graphs with dynamic-sized tensors. However, Core ML can in fact support dynamic re-shaping, as demonstrated by the `coremltools` package being able to create dynamic-sized core ML models since WWDC 2020. Therefore, it should hopefully be possible to get the Core ML delegate to support dynamic shapes.

**Will this change the current api? How?**
The API will be the same, but it will no longer throw this error:
```
TensorFlow Lite Error: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```

**Who will benefit with this feature?**
iOS developers building complex models with dynamic-sized tensors for mobile who wish to maintain just one tflite mobile model for both Android and iOS devices, instead of converting the tensorflow models to Core ML to support dynamic sizes.

**Comment by wangtz** [comment]
Hi Youngseok,

Could you have a look on this iOS related issue?

Thanks,
Tiezhen

**Comment by yyoon** [comment]
Hi @tylerweitzman, thanks for filing the feature request. Unfortunately we don't have plans to add support for this in the near future, but would be happy to review any PRs related to this.
