### ISSUE TITLE
As (x*w+x1*w1+...xn*wn+b) checks if the obtained value is the difference between (x) and (y).

### ISSUE THREAD

**Issue by neiev** [tensorflow/tensorflow#50751]
It would be interesting that at the end of the model.predict function the value obtained the difference between the X_test and the y_test, thus being necessary to multiply the test matrix (X_test) and the prediction matrix (y_preds) to obtain the final value (y_train), instead of needing to multiply the matrix I'm trying to predict (y_train) and the prediction matrix (y_preds) to get the matrix I'm trying to predict (y_train).
This would be useful in cases of future price forecasts of some stock on the stock exchange, because in a real use case, we would have the opening price of the day for example, and we would like to predict the closing price of that same day, using for this the opening price we have at hand.

**System information**
- TensorFlow version (you are using):
2.4.1

- Are you willing to contribute it (Yes/No):
Yes.

**Describe the feature and the current behavior/state.**
By default as this happens at the moment we depend on the closing price itself (y_train) to be multiplied by the forecast matrix (y_preds) to get the closing price itself (y_train), this doesn't make much sense in case of future forecasts, of which we do not yet have the future price in hand.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Developers.

**Comment by jvishnuvardhan** [comment]
@neiev What kind of model (TF/Keras) and what kind of layers (Dense/RNN) you are planning to use? Can you show us what is missing with the current implementation? Please provide a simple standalone code to demonstrate the feature.

As you mentioned that you are willing to contribute, you could raise a PR to update any code. Once you open a PR, you can connect this issue to the PR. Thanks!

**Comment by mihaimaruseac** [comment]
`model.predict(input)` does exactly this. It's just one line, there's no need to complicate TF API for this
