### ISSUE TITLE
InvalidArgumentError: 2 root error(s) found.

### ISSUE THREAD

**Issue by AlicanAKCA** [tensorflow/tensorflow#50755]
### System information

- Colab with GPU
- Latest tflite version

[COLAB LINK](https://colab.research.google.com/drive/18HYg1-SLnNnYcGTIy4yQCgPGA0ZKyYx5?usp=sharing)

### Failure after conversion

INFO:tensorflow:Load image with size: 25002, num_label: 2, labels: Cat, Dog.
INFO:tensorflow:Load image with size: 25002, num_label: 2, labels: Cat, Dog.
INFO:tensorflow:Retraining the models...
INFO:tensorflow:Retraining the models...
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
WARNING:tensorflow:Please add `keras.layers.InputLayer` instead of `keras.Input` to Sequential model. `keras.Input` is intended to be used by Functional model.
Model: "sequential_2"

Total params: 3,415,586
Trainable params: 2,562
Non-trainable params: 3,413,024

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/image_classifier.py in create(cls, train_data, model_spec, validation_data, batch_size, epochs, train_whole_model, dropout_rate, learning_rate, momentum, shuffle, use_augmentation, use_hub_library, warmup_steps, model_dir, do_train)
    318     if do_train:
    319       tf.compat.v1.logging.info('Retraining the models...')
--> 320       image_classifier.train(train_data, validation_data)
    321     else:
    322       # Used in evaluation.

/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/image_classifier.py in train(self, train_data, validation_data, hparams)
    179       lib = train_image_classifier_lib
    180     self.history = lib.train_model(self.model, hparams, train_data_and_size,
--> 181                                    validation_data_and_size)
    182     return self.history
    183 

/usr/local/lib/python3.7/dist-packages/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py in train_model(model, hparams, train_data_and_size, valid_data_and_size, log_dir)
    249       validation_data=valid_data,
    250       validation_steps=validation_steps,
--> 251       callbacks=callbacks)
    252 
    253 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1181                 _r=1):
   1182               callbacks.on_train_batch_begin(step)
-> 1183               tmp_logs = self.train_function(iterator)
   1184               if data_handler.should_sync:
   1185                 context.async_wait()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    887 
    888       with OptionalXlaContext(self._jit_compile):
--> 889         result = self._call(*args, **kwds)
    890 
    891       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    915       # In this case we have created variables on the first call, so we run the
    916       # defunned version which is guaranteed to never create variables.
--> 917       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    918     elif self._stateful_fn is not None:
    919       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   3022        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   3023     return graph_function._call_flat(
-> 3024         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   3025 
   3026   @property

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1959       # No tape is watching; skip to running the function.
   1960       return self._build_call_outputs(self._inference_function.call(
-> 1961           ctx, args, cancellation_manager=cancellation_manager))
   1962     forward_backward = self._select_forward_and_backward_functions(
   1963         args,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    594               inputs=args,
    595               attrs=attrs,
--> 596               ctx=ctx)
    597         else:
    598           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) _Invalid argument:  Trying to decode BMP format using a wrong op. Use `decode_bmp` or `decode_image` instead. Op used: DecodePng_
	 [[{{node cond/else/_1/cond/DecodePng}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_2]]
  (1) _Invalid argument:  Trying to decode BMP format using a wrong op. Use `decode_bmp` or `decode_image` instead. Op used: DecodePng_
	 [[{{node cond/else/_1/cond/DecodePng}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_33212]

Function call stack:
train_function -> train_function

**Comment by ymodak** [comment]
The model is failing at training step. Are you using images in jpeg format?
Also refer this guide if haven't already 
https://www.tensorflow.org/lite/tutorials/model_maker_image_classification

**Comment by AlicanAKCA** [comment]
Hello again sir, it only contains pictures in jpg format.
![image](https://user-images.githubusercontent.com/27694294/125687778-205675d8-065c-4dfd-9556-0ba714b91611.png)
![image](https://i.ibb.co/hZybtBY/2.png)
