### ISSUE TITLE
Error converting  mask_rcnn/inception_resnet_v2_1024x1024 Tensorflow model from TFHub to Tflite 

### ISSUE THREAD

**Issue by TranATT** [tensorflow/tensorflow#50750]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

### System information

- Ubuntu 18.02
- Tensorflow 2.5
- WSL

**Describe the current behavior**
I have been trying to convert the [mask_rcnn/inception_resnet_v2_1024x1024](https://hub.tensorflow.google.cn/tensorflow/mask_rcnn/inception_resnet_v2_1024x1024/1) model from TFHub to Tflite using the using the saved model conversion here https://www.tensorflow.org/lite/convert. The problem here is that for some reason when I run the sample code from Tensorflow the model does not convert correctly and gives me a segmentation fault or an error.

**Describe the expected behavior**
Should be able to have a successful conversion from saved_model to tflite model.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
This is the source code I used for the conversion here taken from the Tensorflow website. All I did was download the model from Tfhub onto my Ubuntu.
![image](https://user-images.githubusercontent.com/22630158/125495414-930090b6-20b4-4ac1-8bec-cde371f59edb.png)

Here is the error when I try to convert the .pb file to a .tflite
![image](https://user-images.githubusercontent.com/22630158/125495918-146443da-7041-480a-9cf9-393d005d44b4.png)

My files
![image](https://user-images.githubusercontent.com/22630158/125496188-77a0b99f-8f0e-4c37-839f-c36ca51e4ebb.png)

**Comment by tilakrayal** [comment]
@TranATT ,

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Also please provide the complete code to reproduce the issue.Thanks!

**Comment by TranATT** [comment]
> @TranATT ,
> 
> We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Also please provide the complete code to reproduce the issue.Thanks!

Hi @tilakrayal I have updated the template! Hope that helps.

**Comment by MeghnaNatraj** [comment]
Is it possible to provide an end-to-end [colab](https://colab.research.google.com/) link with your code and also attach your model? We need to be able to reproduce the issue thoroughly on our end to debug this further. 

*Ensure that you provide read permissions for all the links you share*
