### ISSUE TITLE
Incomplete Installation of Tensorflow FreeBSD

### ISSUE THREAD

**Issue by Amzo** [tensorflow/tensorflow#50766]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): FreeBSD 13
- TensorFlow installed from (source or binary): Source
- TensorFlow version: v2.1.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.29.0
- GCC/Compiler version (if compiling from source):  clang version 11.0.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
While tensorflow will build on FreeBSD, the installation is incomplete and only provides lib/python3.8/site-packages/tensorflow_core with nothing else.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Commands for building:
`        @cd ${WRKSRC} && \
                bazel --bazelrc="${WRKDIR}/bazelrc" ${BAZEL_BOOT} build ${BAZEL_COPT} --host_copt="-I${LOCALBASE}/include" \
                --host_linkopt="-L${LOCALBASE}/lib" --linkopt="-L${LOCALBASE}/lib" --copt="-I${LOCALBASE}/include" \
                --verbose_failures -s --incompatible_restrict_string_escapes=false \
                --distdir=${WORKDIR}/bazel-dist --linkopt='-fuse-ld=lld' \
                //tensorflow:libtensorflow_framework.so \
                //tensorflow:libtensorflow.so \
                //tensorflow:libtensorflow_cc.so \
                //tensorflow/tools/pip_package:build_pip_package
`
The creation of the pip package:

`
        @cd ${WRKSRC} && ${SETENV} TMPDIR=${WRKDIR} \
                bazel-bin/tensorflow/tools/pip_package/build_pip_package \
                ${WRKDIR}/whl
`

The following variables in the above command contain the following information:

LOCALBASE=/usr/local
BAZEL_BOOT= --output_user_root=${WRKDIR}/bazel_out
BAZEL_COPT="-c opt --copt=-march=native --copt=-mfpmath=sse"

**Any other info / logs**
I'm assuming the problem is just from the build files failing to default to a suitable platform and is falling back to default values. If I could be pointed into the right direction and files so that I could move forward and patch them it would be helpful.

**Comment by UsharaniPagadala** [comment]
@Amzo 

Could you please refer the similar [link1](https://github.com/tensorflow/tensorflow/issues/193) and [link2](https://github.com/tensorflow/tensorflow/issues/37345) and let us know if it helps.Thanks

**Comment by Amzo** [comment]
Nope. those seem to be build issues. I've remedied and patched them and tensorflow builds successfully. However, on the creation of the pip packages, there only seems to be usr/lib/python3.8/site-packages/tensorflow_core available. All other directories are not being installed during pip creation, even though I see they have been built. 

I'm not sure if there is some platform checks I've overlooked during build that I've failed to catch.

**Comment by Saduf2019** [comment]
@Amzo 
Can you please try on virtual env and let us know.

**Comment by Amzo** [comment]
I'll put this on hold for now, and see if I can get tensorflow 2.5.x to build on FreeBSD once I finish through the documentation to create a toolchain to allow it to build, as it currently errors out about no toolchains being found for now. Mostly due to there being no support for FreeBSD in bazel toolchain, and currently no docker support. 

I'll see if the problem still persists in the newer version of tensorflow. Might be easier to just run a virtual env in the linuxulator on FreeBSD and avoid a native port.

**Comment by gt2416** [comment]
I see on https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250646 you said you have not submitted the fix, is there any reason why.
I am trying to build photoprism (great google photo replacement), and it needs tensorflow :(

**Comment by Amzo** [comment]
The patch only fixes the import of tensorflow by a broken stage in the Makefile, a lot of stuff is still missing. photoprism only needs libtensorflow which the makefile builds, if you're on freebsd you can build tensorflow from the port and take the library files from the build directory until i finish working out issues with the port. Though this is off topic. i should have things fixed in a day or two. For your issue to build protoprism i can submit a patch tomorrow to package the tensorflow libraries in.

**Comment by gt2416** [comment]
Oh ok wow, thanks a bunch! and take your time. Silly me thought you fixed it but just haven't submitted it yet.

**Comment by Huskers2020** [comment]
@Amzo - Were you able to make progress?

**Comment by Amzo** [comment]
Yeah, i upgraded to 2.1.4 and fixed the packaging in the Makefile, and it works as intended on freebsd.

**Comment by Huskers2020** [comment]
@Amzo Appreciate the quick response!

Is your updated code available in ports or was it something you just did locally on your m/c?
If you had locally compiled on your m/c how long did it take?

Also, can you point to any specifics that one to be aware of to compile TF on FreeBSD

**Comment by Amzo** [comment]
Code hasn't been merged yet, but this should work on FreeBSD, best to just email me about it or report on there instead of on here.

https://github.com/Amzo/FreeBSD-Tensorflow/tree/master/science/py-tensorflow

**Comment by Huskers2020** [comment]
how much time did it take to compile TF?
