### ISSUE TITLE
Not linking properly on XCode with Mac M1

### ISSUE THREAD

**Issue by bylowerik** [tensorflow/tensorflow#50762]
Platform: MacBook M1 BigSur
Installed: CocoaPods

**Describe the problem**
I have created a new project and added a Podfile from here: https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios

When I build in XCode I get 

`building for iOS Simulator, but linking in object file built for iOS, file.
'/Users/name/Code/name2/ios/SwingAIAnalyzer/Pods/TensorFlowLiteC/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC' for architecture arm64`

But when I try the example `ImageClassification` directly it works. I have check the settings of the two projects but cannot find any differences.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1 Create a new project
2 Copy the Podfile in ImageClassfication and change project name in podfile.
3 Run pod install or pod update
4 Open .xcworkspace
5 Build and here I fail

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Looks like you are running into problems when trying to run [customized image classification](https://www.tensorflow.org/lite/examples/image_classification/overview#customize-model) example whereas the standalone example works successfully. Is that correct?

**Comment by bylowerik** [comment]
No, I have not done anything with TensorFlow in my code. I have just run CocoaPods, and then I cannot build.

**Comment by sachinprasadhs** [comment]
Could you please try again with latest IOS and Tensorflow nightly version and let us know if you still face any problem. Thanks!
