### ISSUE TITLE
AssertionError occurred when initializing NLClassifier with TFlite model

### ISSUE THREAD

**Issue by nikhilAgarwalM** [tensorflow/tensorflow#50764]
I am using NLClassifier in my android application for a text classification problem

Dependency used - **implementation 'org.tensorflow:tensorflow-lite-task-text:0.2.0'**

I am downloading the TFlite model from firebase using FirebaseModelDownloader with the following code
Dependency used - **implementation 'com.google.firebase:firebase-ml-modeldownloader-ktx:24.0.0'**

```
val conditions = CustomModelDownloadConditions.Builder().build()
    FirebaseModelDownloader.getInstance()
    .getModel(ADULT_FILTER_MODEL, DownloadType.LOCAL_MODEL_UPDATE_IN_BACKGROUND, conditions)
    .addOnSuccessListener { model: CustomModel? ->
        model?.file?.let { modelFile ->
            try {
                val classifier = NLClassifier.createFromFile(model)
            } catch (e: IOException) {
                e.printStackTrace()
            }
        }

    }
    .addOnFailureListener {
        // failure handling
    }
```

**Describe the current behavior**
I am getting AssertionError while creating NLClassifier instance with given line of code irregularly
`val classifier = NLClassifier.createFromFile(model)`

StackTrace - 
_Fatal Exception: java.lang.AssertionError: Error occurred when initializing NLClassifier: The model is not a valid Flatbuffer buffer
       at org.tensorflow.lite.task.text.nlclassifier.NLClassifier.initJniWithFileDescriptor(NLClassifier.java)
       at org.tensorflow.lite.task.text.nlclassifier.NLClassifier.access$000(NLClassifier.java:67)
       at org.tensorflow.lite.task.text.nlclassifier.NLClassifier$1.createHandle(NLClassifier.java:195)
       at org.tensorflow.lite.task.core.TaskJniUtils.createHandleFromLibrary(TaskJniUtils.java:91)
       at org.tensorflow.lite.task.text.nlclassifier.NLClassifier.createFromFileAndOptions(NLClassifier.java:191)
       at org.tensorflow.lite.task.text.nlclassifier.NLClassifier.createFromFile(NLClassifier.java:161)_

**Describe the expected behavior**
I should not get the Error while creating NlClassifier on an irregular basis

Any reason for this and a solution?

**Comment by lu-wang-g** [comment]
First, please make sure the model is a valid TFLite model. You can do so by using the [Python Interpreter](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) and see if the model can be successfully loaded into Interpreter.

If the model is valid, please try the two answers in this [StackOverflow question](https://stackoverflow.com/questions/66958171/custom-machine-learning-code-to-import-in-the-android-studio). It seems to be a common issue from Firebase.
