### ISSUE TITLE
when i use tf2.4, tf.image_resize takes more time than tf1.2

### ISSUE THREAD

**Issue by superlxt** [tensorflow/tensorflow#50779]
when i use tf.compact.v1 to run the tensorflow1.2 code , find that tf.image_resize takes 40% longer
Besides，unpool and conv2d_transpose encountered the same phenomenon
Is this a bug or a normal phenomenon?

**Comment by old-school-kid** [comment]
No this is normal phenomenon, since Tensorflow 1 uses only graph execution and thus has higher performance. On the other hand 
Tensorflow 2 uses Eager execution by default and is slower than Tensorflow 1, but easier to debug. You can increase your performance in Tendorflow 2 by using @tf.function above the function declaration to execute the piece of code as a graph.

**Comment by Saduf2019** [comment]
@superlxt 
Please refer to [this link](https://towardsdatascience.com/eager-execution-vs-graph-execution-which-is-better-38162ea4dbf6) and final notes for better understanding. [also [link1](https://stackoverflow.com/questions/58441514/why-is-tensorflow-2-much-slower-than-tensorflow-1])]

**Comment by superlxt** [comment]
> No this is normal phenomenon, since Tensorflow 1 uses only graph execution and thus has higher performance. On the other hand
> Tensorflow 2 uses Eager execution by default and is slower than Tensorflow 1, but easier to debug. You can increase your performance in Tendorflow 2 by using @tf.function above the function declaration to execute the piece of code as a graph.

So you mean that although I use tf.compact.v1 to run the code on tf2.4, it is still executed by eager?
By the way, if I want to use tf.funcation to speed up, how should I implement it。
thanks

**Comment by superlxt** [comment]
At the same time, if I only use conv to build the network, tf1.2 and tf2.4 get the same speed. If tf.image.resize, unpool, conv_transpose are added after conv, the time consuming in tf2.4 will increase significantly

**Comment by old-school-kid** [comment]
@superlxt 
Resizing image requires interpolation which are mathematically more expensive than matrix multiplication in case of convolution. As they are served into a graph the various tf.Operation objects are executed and are accelerated in case of graph execution while in Eager execution doesn't provide this opportunity of acceleration.

**Comment by old-school-kid** [comment]
Also even if you use tf.compat.v1 it uses Tensorflow 2 as backend and executes Eager Execution which is default. 
You can find examples of @tf.function [here](https://www.tensorflow.org/api_docs/python/tf/function?version=nightly)

**Comment by Saduf2019** [comment]
@superlxt 
Kindly open this issue in discussion forum/stackoverflow and move it to closed status here.

**Comment by superlxt** [comment]
@Saduf2019 
ok,I will try to see if tf.function works, and I will close this question after I confirm
