### ISSUE TITLE
MKL XLA CPU Runtime Test Failure

### ISSUE THREAD

**Issue by philipphack** [tensorflow/tensorflow#50776]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0

**Describe the problem**

When MKL is enabled, the `tensorflow/compiler/xla/service/cpu:cpu_runtime_test` unit test fails while attempting to load the  [third_party/intel_mkl_ml/include/mkl_cblas.h](https://github.com/tensorflow/tensorflow/blob/81b2bcb9ba3316759a08db614bd76d572a1cb320/tensorflow/compiler/xla/service/cpu/runtime_matmul_mkl.h#L22) header file.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel test --config=mkl //tensorflow/compiler/xla/service/cpu:cpu_runtime_test`

**Any other info / logs**

```
ERROR: /opt/tensorflow/tensorflow-source/tensorflow/compiler/xla/service/cpu/BUILD:858:11: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:cpu_runtime_test' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/cpu/_objs/cpu_runtime_test/cpu_runtime_test.d ... (remaining 390 argument(s) skipped)
cc1plus: warning: command line option ‘-Wno-pointer-sign’ is valid for C/ObjC but not for C++
In file included from tensorflow/compiler/xla/service/cpu/cpu_runtime_test.cc:28:
./tensorflow/compiler/xla/service/cpu/runtime_matmul_mkl.h:22:10: fatal error: third_party/intel_mkl_ml/include/mkl_cblas.h: No such file or directory
   22 | #include "third_party/intel_mkl_ml/include/mkl_cblas.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by mohantym** [comment]
Hi @philipphack !
We are checking to see whether you still need help in this issue . 
Build seems to be passing for Master branch with Bazel 5.3.0 . Attached[ gist](https://colab.sandbox.google.com/gist/mohantym/d6e3fc5ae83e769e75677fdead2a7cbb/tensorflow-ranking.ipynb#scrollTo=DtEuxvobaRf5) for reference.

Could you let us know for your side.
Thank you!
