### ISSUE TITLE
gast_archive URL error

### ISSUE THREAD

**Issue by kevininderhees** [tensorflow/tensorflow#50777]
There's an error in the mirrored URL for gast_archive:

https://github.com/tensorflow/tensorflow/blob/e7017fd09cc249d0d522a2b77f0dcae4642dd04a/tensorflow/workspace2.bzl#L441
That URL gives an error, "The specified key does not exist."  The URL should be `https://storage.googleapis.com/mirror.tensorflow.org/files.pythonhosted.org/packages/83/4a/07c7e59cef23fb147454663c3271c21da68ba2ab141427c20548ae5a8a4d/gast-0.4.0.tar.gz`

We've only whitelisted storage.googleapis.com in our firewall, so when the build tries to fall back to the official files.pythonhosted.org source, it fails.

**Comment by Saduf2019** [comment]
@kevininderhees 
A pris created to update the changes, this issue will be closed once the [pr](https://github.com/tensorflow/tensorflow/pull/50882) is merged.

**Comment by Saduf2019** [comment]
Moving this to closed status pr is merged.
