### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (lstm_20/strided_slice:0) to a numpy array...

### ISSUE THREAD

**Issue by kimwoo0** [tensorflow/tensorflow#50784]
My code:

model = Sequential()

model.add(LSTM(50, return_sequences=True, input_shape=(50, 1)))

model.add(LSTM(64, return_sequences=False))

model.add(Dense(1, activation='linear'))

model.compile(loss='mse', optimizer='rmsprop')

model.summary()

-------------------------------------------------------------------------

NotImplementedError                       Traceback (most recent call last)
<ipython-input-111-b51fee4336b3> in <module>
      1 model = Sequential()
      2 
----> 3 model.add(LSTM(50, return_sequences=True, input_shape=(50, 1)))
      4 
      5 model.add(LSTM(64, return_sequences=False))

~\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    455         self._checkpoint.restore_saveables(tensor_saveables, python_saveables))
    456     return restore_ops
--> 457 
    458   @property
    459   def checkpoint(self):

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py in add(self, layer)
    204               batch_shape=batch_shape, dtype=dtype, name=layer.name + '_input')
    205           # This will build the current layer
--> 206           # and create the node connecting the current layer
    207           # to the input layer we just created.
    208           layer(x)

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    661 
    662     # If any of `initial_state` or `constants` are specified and are Keras
--> 663     # tensors, then add them to the inputs and temporarily modify the
    664     # input_spec to include them.
    665 

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in __call__(self, *args, **kwargs)
    923       ValueError: if the layer's `call` method returns None (an invalid value).
    924       RuntimeError: if `super().__init__()` was not called in the constructor.
--> 925     """
    926     if not hasattr(self, '_thread_local'):
    927       raise RuntimeError(

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1115         layer=self, inputs=inputs, build_graph=True, training=training_value):
   1116       # Symbolic execution on symbolic tensors. We will attempt to build
-> 1117       # the corresponding TF subgraph inside `backend.get_graph()`
   1118       # TODO(reedwm): We should assert input compatibility after the inputs
   1119       # are casted, not before.

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent_v2.py in call(self, inputs, mask, training, initial_state)
   1106         recurrent_activation=recurrent_activation,
   1107         use_bias=use_bias,
-> 1108         kernel_initializer=kernel_initializer,
   1109         recurrent_initializer=recurrent_initializer,
   1110         bias_initializer=bias_initializer,

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in _process_inputs(self, inputs, initial_state, constants)
    860 
    861     if len(initial_state) != len(self.states):
--> 862       raise ValueError('Layer has ' + str(len(self.states)) +
    863                        ' states but was passed ' + str(len(initial_state)) +
    864                        ' initial states.')

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in get_initial_state(self, inputs)
    643           inputs=None, batch_size=batch_size, dtype=dtype)
    644     else:
--> 645       init_state = _generate_zero_filled_state(batch_size, self.cell.state_size,
    646                                                dtype)
    647     # Keras RNN expect the states in a list, even if it's a single state tensor.

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in get_initial_state(self, inputs, batch_size, dtype)
   2521   "We find that LSTM augmented by 'peephole connections' from its internal
   2522   cells to its multiplicative gates can learn the fine distinction between
-> 2523   sequences of spikes spaced either 50 or 49 time steps apart without the help
   2524   of any short training exemplars."
   2525 

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in _generate_zero_filled_state_for_cell(cell, inputs, batch_size, dtype)
   2966       return x
   2967     if isinstance(x, tuple):
-> 2968       return list(x)
   2969     return [x]
   2970 

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in _generate_zero_filled_state(batch_size_tensor, state_size, dtype)
   2982 
   2983 def _generate_zero_filled_state_for_cell(cell, inputs, batch_size, dtype):
-> 2984   if inputs is not None:
   2985     batch_size = array_ops.shape(inputs)[0]
   2986     dtype = inputs.dtype

~\anaconda3\lib\site-packages\tensorflow\python\util\nest.py in map_structure(func, *structure, **kwargs)
    633     ValueError: If no structure is provided or if the structures do not match
    634       each other by type.
--> 635     ValueError: If wrong keyword arguments are provided.
    636   """
    637   if not callable(func):

~\anaconda3\lib\site-packages\tensorflow\python\util\nest.py in <listcomp>(.0)
    633     ValueError: If no structure is provided or if the structures do not match
    634       each other by type.
--> 635     ValueError: If wrong keyword arguments are provided.
    636   """
    637   if not callable(func):

~\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py in create_zeros(unnested_state_size)
   2979   return (hasattr(state_size, '__len__') and
   2980           not isinstance(state_size, tensor_shape.TensorShape))
-> 2981 
   2982 
   2983 def _generate_zero_filled_state_for_cell(cell, inputs, batch_size, dtype):

~\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in wrapped(*args, **kwargs)
   2745                          [1, 2, 3],
   2746                          [0, 4, 5]],
-> 2747                         [[1, 2, 0],
   2748                          [5, 6, 4],
   2749                          [6, 1, 2],

~\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in zeros(shape, dtype, name)
   2792       the left (right-pads the row). It is the packing format LAPACK uses.
   2793       cuSPARSE uses "LEFT_RIGHT", which is the opposite alignment.
-> 2794   """
   2795   return gen_array_ops.matrix_set_diag_v3(
   2796       input=input, diagonal=diagonal, k=k, align=align, name=name)

~\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py in _constant_if_small(value, shape, dtype, name)
   2730           [7, 5, 7, 7],
   2731           [7, 7, 6, 7]]]
-> 2732 
   2733   # A superdiagonal (per batch).
   2734   tf.matrix_set_diag(input, diagonal, k = 1)

<__array_function__ internals> in prod(*args, **kwargs)

~\anaconda3\lib\site-packages\numpy\core\fromnumeric.py in prod(a, axis, dtype, out, keepdims, initial, where)
   3028         but the type of the resulting values will be cast if necessary.
   3029 
-> 3030     Returns
   3031     -------
   3032     cumprod : ndarray

~\anaconda3\lib\site-packages\numpy\core\fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

~\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in __array__(self)
    843   # operators to run when the left operand is an ndarray, because it
    844   # accords the Tensor class higher priority than an ndarray, or a
--> 845   # numpy matrix.
    846   # TODO(mrry): Convert this to using numpy's __numpy_ufunc__
    847   # mechanism, which allows more control over how Tensors interact

NotImplementedError: Cannot convert a symbolic Tensor (lstm_20/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

-----------------------------------------------------------------------------------------------

Tensorflow : 2.4.1
numpy : 1.19.5

NumPy version 1.20 or later has been reported to be a problem, so I changed it to 1.19.5 but it is the same.
Even if I downgrade TensorFlow to 2.2, it's the same.
What action should I take?

**Comment by UsharaniPagadala** [comment]
@kimwoo0 

Tensorflow 2.4.1 requires numpy~=1.19.2  is compatible version,Please check the same you have

Could you please provide the colab gist with all the dependencies.And also refer similar issues [link1](https://stackoverflow.com/questions/66207609/notimplementederror-cannot-convert-a-symbolic-tensor-lstm-2-strided-slice0-t) and [link2](https://www.reddit.com/r/tensorflow/comments/lgcgby/numpyrelated_error_when_building_model/)     ,let us know if it helps.
Refer this [comment](https://groups.google.com/g/machine-learning-for-physicists/c/-ofwo29YgpY) as well.  Thanks
