### ISSUE TITLE
tf.keras.preprocessing.timeseries_dataset_from_array function is broken in latest code

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#50781]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow installed from (source or binary): latest source
- TensorFlow version (use command below): latest source
- Python version: 3.x.x
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4
- GPU model and memory:

**Describe the current behavior**
The error says that there is a circular Keras reference. However , if i install last month's code, it works.

**Describe the expected behavior**

**Comment by UsharaniPagadala** [comment]
@summa-code 

Is this the [link](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/timeseries_dataset_from_array)  you are talking about, if no Could you please share the broken  link.Thanks

**Comment by summa-code** [comment]
Yes, those are the links. Anything changed ?

**Comment by summa-code** [comment]
Should i get the latest code and test it ? Let me know... I can do testing part of it.

**Comment by UsharaniPagadala** [comment]
@summa-code 

Could you please try [this](https://github.com/tensorflow/tensorflow/tree/v2.5.0/tensorflow/python/keras/preprocessing) and let us if it helps.Thanks

**Comment by summa-code** [comment]
Huh ? Yes, it is still a problem with latest code.

https://www.tensorflow.org/tutorials/structured_data/time_series

Use this example. This will throw the error. I pulled the code today and built. Same error.

```from keras import __version__
ImportError: cannot import name '__version__' from partially initialized module 'keras' (most likely due to a circular import) (/home/xxxx/.virtualenvs/tensorflow/lib/python3.8/site-packages/keras/__init__.py)```

**Comment by summa-code** [comment]
I cleaned and reinstalled, there is some version compatibility. I am closing this issue.
