### ISSUE TITLE
About pb model quantification

### ISSUE THREAD

**Issue by Zengyf-CVer** [tensorflow/tensorflow#50785]
Hello, I have a `float32 pb` model, and I want to convert it to an `int8 pb` model, how should I operate it?

**Comment by UsharaniPagadala** [comment]
@Zengyf-CVer 

Could you please let us know are you Converting from pb to tflite. If yes Please refer the [documentation](https://www.tensorflow.org/lite/performance/post_training_quantization) and also look at this [article](https://medium.com/axinc-ai/convert-keras-models-to-tensorflow-lite-e654994fb93c) ,hope it helps.Thanks

**Comment by Zengyf-CVer** [comment]
@UsharaniPagadala 
Instead of converting to tflite, but converting float32 type pb model to int8 type pb model, in other words, `(float32)pb=>(int8)pb`

**Comment by UsharaniPagadala** [comment]
@Zengyf-CVer 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) / TF [Forum](https://discuss.tensorflow.org/) . There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. 
and move this to closed status.Thanks

**Comment by Zengyf-CVer** [comment]
@UsharaniPagadala 
Thank you very much for your reply.
