### ISSUE TITLE
ValueError: destinations can not be empty

### ISSUE THREAD

**Issue by Yurushia1998** [tensorflow/tensorflow#50788]
I'm having this bug when I try to: get features at the layer before last layer, compute loss with expected features using cosine similarity, then propagate back to input (I update input, not network's weight) with optimizer.minimine(loss,var_list = input). I cannot find any information about this bug. Please give me advice

**Comment by UsharaniPagadala** [comment]
@Yurushia1998 

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by Yurushia1998** [comment]
> @Yurushia1998
> 
> We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

TF Version: 2.3.0, but I use disable_v2_behaviour
OS Ubuntu 20.04, PC
Python 3.6.13
gcc  10.2.0
CUDA 10, cudnn 7.6.5
GPU memory 11019MB

 A simplified version of code would be:

class Model
  def init(some_network):
    self.probe_images_weight = tf.get_variable("probe_images_weight",  initializer=tf.ones([100,32,32,3]), trainable = True)
    self.net = some_network
    self.optimizer_probe = tf.train.GradientDescentOptimizer(
          learning_rate=0.005)
  def update_probe_operator(self):
    
      def step_update_probe():
        """Step functon.

        Args:
          inputs: inputs from data iterator

        Returns:
          a set of variables want to observe in Tensorboard
        """
        net = self.net
        logits,features = net(self.probe_images_weight, name='model', reuse=tf.AUTO_REUSE, training=True)
        probe_loss = tf.keras.losses.cosine_similarity(self.expect_features, features)
        probe_loss = tf.reduce_mean(probe_loss)
        minimizer_op = self.optimizer_probe.minimize(probe_loss, var_list= [self.probe_images_weight])
        with tf.control_dependencies([minimizer_op]):      #Error appear here when I update the input 
              return tf.identity(probe_loss)
      # end of parallel
      probe_loss = self.strategy.run(
           step_update_probe)
  
      probe_loss = self.strategy.unwrap(probe_loss)    
      return [probe_loss]

**Comment by UsharaniPagadala** [comment]
@Yurushia1998 

 I am facing indentation errors.Could you please share the colab gist with clear details.Thanks

**Comment by Yurushia1998** [comment]
> @Yurushia1998
> 
> I am facing indentation errors.Could you please share the colab gist with clear details.Thanks

Hi, can you acces this link: https://drive.google.com/drive/folders/1dpBhVutc15sputAIlFymLdGZ8FTqZP0y?usp=sharing
To run the code, please install
!pip install --upgrade tensorflow-gpu
!pip install torch torchvision
!pip install tqdm numpy absl-py sklearn gast tensorflow_datasets tensorflow_addons Pillow 
!pip install git+https://github.com/qubvel/classification_models.git
!pip install scikit-learn-extra keras

on a virtual environment, then run by command:
bash ieg/run_cifar10_diversity_and_balance_only_clean_balance_mix_cosine_real_features_0.006_resnet29.sh

**Comment by UsharaniPagadala** [comment]
@Yurushia1998 

 Could you please provide the colab gist rather than a script,it will help me to analyse the issue better.Thanks

**Comment by Yurushia1998** [comment]
> @Yurushia1998
> 
> Could you please provide the colab gist rather than a script,it will help me to analyse the issue better.Thanks

Is this what you want: https://gist.github.com/Yurushia1998/404fc4bd55909768d1d90f2ffeb54c1a? Please let me know if you want something else

**Comment by UsharaniPagadala** [comment]
@rmothukuru 

I was able to  replicate the issue reported here.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/c2b9c6fc826c90737e1e9a5125ace181/ieg.ipynb#scrollTo=E3n3TIi_Fo93). Thanks

**Comment by ymodak** [comment]
This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
