### ISSUE TITLE
Tensorflow on Ubuntu 14 with cuda 8 and cudnn 5.1

### ISSUE THREAD

**Issue by kdkalvik** [tensorflow/tensorflow#5078]
Hello I am trying to install tensorflow on ubuntu 14 with cuda 8 and cudnn 5.1. I followed the instructions here  https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources
I was able to run the demo model but when I try to import tensorflow in python I get the following error

>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 165, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'

**Comment by ajkl** [comment]
I get the same error, how did you fix this ?

**Comment by kdkalvik** [comment]
I used 0.10 instead of the master and that fixed it
