### ISSUE TITLE
Import error when multiple versions of tensorflow are in python path

### ISSUE THREAD

**Issue by chudyandrej** [tensorflow/tensorflow#50789]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10 (buster)
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): 2.4.1 and 2.5.0
- Python version: 3.7
- CUDA/cuDNN version: Environment without GPU
- GPU model and memory: Environment without GPU

**Initial environment**
I have empty virtual environment without system libraries, created via command `virtualenv --system-site-packages`. Outside of the environment I have installed a set of common data-science libraries , including `tensorflow==2.4.1`. My python path looks like this: 
```
['/usr/local/lib/python37.zip',
 '/usr/local/lib/python3.7',
 '/usr/local/lib/python3.7/lib-dynload',
 '/root/venv/lib/python3.7/site-packages',
 '/usr/local/lib/python3.7/site-packages',
 '/shared-libs/python3.7/py/lib/python3.7/site-packages',
 '/deepnote-config/ipython',
 '/root/work']
```

where `/shared-libs/python3.7/py/lib/python3.7/site-packages` contains tensorflow==2.4.1.

**Describe the current behavior**
When I import tensorflow in this environment, everything works ok. Problem appears when I install newer `tensorflow` to my env via command `pip install tensorflow==2.5.0`. After succesfull installation I get this error while importing tensorflow:
`NotFoundError: /shared-libs/python3.7/py/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6thread10ThreadPool26TransformRangeConcurrentlyExxRKSt8functionIFvxxEE `. 

Why is tensorflow trying  to load `libtfkernel_sobol_op.so` module form last path in python path `/shared-libs/python3.7/py`. Just to clarify, `cat /root/venv/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so` file exists.

When I remove  '/shared-libs/python3.7/py/lib/python3.7/site-packages' (which contains tf 2.4.1) from python path, the problem seems to disappear. Therefore it seems like presence of different version of tf later in the path causes the issue, which is unexpected. 

**Describe the expected behavior**
I expect that python will search tensorflow according to the order of the python path. In other words, I expect that tensorflow 2.5.0 will be imported from  '/root/venv/lib/python3.7/site-packages' and tensorflow outside of my venv will be ignored '/shared-libs/python3.7/py/lib/python3.7/site-packages'. 

**Other info / logs** 
I found this similar error https://github.com/tensorflow/tensorflow/issues/42978 . I tried to run logic for for sorting site_packages dirs:

```python
import six as _six
import sys as _sys
import site as _site

# Get sitepackages directories for the python installation.
_site_packages_dirs = []
if _site.ENABLE_USER_SITE and _site.USER_SITE is not None:
  _site_packages_dirs += [_site.USER_SITE]
  _site_packages_dirs += [_p for _p in _sys.path if 'site-packages' in _p]
  print(_site_packages_dirs)
```
Output:
```
[ '/root/venv/lib/python3.7/site-packages', '/usr/local/lib/python3.7/site-packages', '/shared-libs/python3.7/py/lib/python3.7/site-packages']
```
Happy to provide any assistance in debugging and I am also happy to provide a fix if anyone can point me in the right direction.

**Comment by UsharaniPagadala** [comment]
@chudyandrej 

Could you please refer this [comment](https://stackoverflow.com/questions/65405705/undefined-symbol-zn10tensorflow8opkernel11tracestringepns-15opkernelcontexteb/65467331), and also refer the [documentation,](https://www.tensorflow.org/install/pip#virtual-environment-install) and let us know if it helps.Thanks

**Comment by chudyandrej** [comment]
Hi @UsharaniPagadala, thanks for your comment. I tried to update TF outside of my virtual environment to the latest version 2.5.0. Now when i install any other version of TF (i tried **2.4.1**, **2.4.2**, **2.6.0rc0**) in a virtual environment I getting the same error.

```
NotFoundError: /shared-libs/python3.7/py/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_09_2311string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
```

I was using this setup for quite a long time. For example when TF outside of venv is **2.0.1** and the installed version of TF inside of venv is  **2.0.0** everything works just fine. This problem appeared with version **2.5.0**. 
Thanks for your time.

**Comment by Saduf2019** [comment]
@chudyandrej 
Can you please remove all the installations and start from scratch so that way the correct files can be in correct path.
