### ISSUE TITLE
Serialize tf.keras Preprocessing layers

### ISSUE THREAD

**Issue by sidhartha-roy** [tensorflow/tensorflow#50793]
I created some keras preprocessing layers using the following:
This example is for categorical columns but I could have done this for any type of preprocessing as shown in [Module: tf.keras.layers.experimental.preprocessing](Module: tf.keras.layers.experimental.preprocessing)
```
categorical_col = tf.keras.Input(shape=(1,), name=header, dtype='string')

index = preprocessing.StringLookup(max_tokens=max_tokens)
index.adapt(feature_ds)
encoder = preprocessing.CategoryEncoding(num_tokens=index.vocabulary_size())
encoding_layer = lambda feature: encoder(index(feature))
```
Now if I want to serialize this `encoding_layer` or the `categorical_col` there is no way to do this.

I tried pickle dump and got the following error:
`pickle.dumps(encoding_layer)`
```
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-da3341eebce4> in <module>
      1 import pickle
----> 2 pickle.dumps(tfp.encoded_features[0])

AttributeError: Can't pickle local object 'PreprocessingLayer.make_adapt_function.<locals>.adapt_step'
```
I also tried to use the tf.keras serializer and I got the following error:
`tf.keras.layers.serialize(encoding_layer)`

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-c9875a7f3e69> in <module>
----> 1 tf.keras.layers.serialize(tfp.encoded_features[0])

~/Dev-Stage/armet/env/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py in serialize(layer)
    141 @keras_export('keras.layers.serialize')
    142 def serialize(layer):
--> 143   return generic_utils.serialize_keras_object(layer)
    144 
    145 

~/Dev-Stage/armet/env/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    528   if hasattr(instance, '__name__'):
    529     return get_registered_name(instance)
--> 530   raise ValueError('Cannot serialize', instance)
    531 
    532 

ValueError: ('Cannot serialize', <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization')>)
```
Is there a way to serialize the keras preprocessing layers? I am not sure why this serialization is not working.

**Comment by UsharaniPagadala** [comment]
@sidhartha-roy 

we see the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled please do so,  and provide the colab gist, it will helps us to analyse better, 

also refer [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/generic_utils.py#L515), and let us know if it helps.Thanks
