### ISSUE TITLE
tf.keras.models.clone_model ignores input_tensors argument 

### ISSUE THREAD

**Issue by LeonhardFeiner** [tensorflow/tensorflow#50791]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution. Linux Ubuntu 20.04:
- TensorFlow installed from binary:
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.5
- CUDA/cuDNN version: 11.2
- GPU model and memory: NVIDIA Quadro RTX 8000

**Describe the current behavior**

`tf.keras.models.clone_model` ignores `input_tensors` argument and reuses the inputs of the original model for functional models. It works for sequential models.

**Describe the expected behavior**

If I provide `input_tensors`, it should use it.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes

I think that the error is in the following [line](https://github.com/tensorflow/tensorflow/blob/383f3a58a682aaf8e460170ccd76f216db375f9f/tensorflow/python/keras/models.py#L187)

I would replace this line:
`new_input_layers[original_input_layer] = original_input_layer`
by this line:
`new_input_layers[original_input_layer] = input_tensor._keras_history.layer`

This would be similar to the [line in sequential models](https://github.com/tensorflow/tensorflow/blob/383f3a58a682aaf8e460170ccd76f216db375f9f/tensorflow/python/keras/models.py#L344)

It works for me, but I'm not 100% sure if that is the intended behavior.

**Standalone code to reproduce the issue**
[Colab](https://colab.research.google.com/drive/1ljevVbdSon7Vkz21lA9Bd0-dYw1tkuES?usp=sharing)
```
import tensorflow as tf
from tensorflow.keras import layers

inputs_small = layers.Input((64, 64, 3), name="small")
outputs = layers.Conv2D(32, 1)(inputs_small)
model_small = tf.keras.models.Model(inputs=inputs_small, outputs=outputs)

inputs_large = layers.Input((128, 128, 3), name="large")
model_large = tf.keras.models.clone_model(model_small, input_tensors=inputs_large)
model_large.summary()
```
This results into:
```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
small (InputLayer)           [(None, 64, 64, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 64, 64, 32)        128       
=================================================================
Total params: 128
Trainable params: 128
Non-trainable params: 0
_________________________________________________________________
```
I like to see this behavior:
```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
large (InputLayer)           [(None, 128, 128, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 128, 128, 32)      128       
=================================================================
Total params: 128
Trainable params: 128
Non-trainable params: 0
_________________________________________________________________
```
The same happens if the new input tensor just has a different name than the original one

**Comment by tilakrayal** [comment]
@LeonhardFeiner ,

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by LeonhardFeiner** [comment]
I created an issue there: https://github.com/keras-team/keras/issues/14937
