### ISSUE TITLE
Document the broadcasting behavior for `tf.mul` etc.

### ISSUE THREAD

**Issue by mrry** [tensorflow/tensorflow#508]
The fact that many of the elementwise operators in TensorFlow support numpy-style broadcasting is not well documented or discoverable. (e.g. [This SO question.](http://stackoverflow.com/questions/34220374/apply-1-channel-mask-to-3-channel-tensor-in-tensorflow/34220963)) We should improve the documentation on this.

**Comment by girving** [comment]
@mrry: Are you still planning to work on this?

**Comment by mrry** [comment]
Not urgently, so perhaps "contributions welcome" is more appropriate.

**Comment by girving** [comment]
If anyone takes this on, it should go in the doc string at the top of `math_ops.py`.

**Comment by siddharth-agrawal** [comment]
@girving Should this be a generic comment saying that TF uses numpy-style broadcasting? Or should it be specific to the operations that are affected by it (alternatively just mention the operations)?

**Comment by girving** [comment]
TF doesn't use numpy style broadcasting for all ops, just for elementwise operations (specifically binary elementwise operations).  Referring to elementwise ops is sufficient; there's no need to list them all.

**Comment by siddharth-agrawal** [comment]
@girving Should this issue be closed? Or are there other changes that need to be made?

**Comment by vrv** [comment]
We could have documentation on every elementwise op that supports broadcasting (numpy does mention broadcasting somewhere in the notes of every op.

**Comment by girving** [comment]
@vrv Putting it in every op seems unpleasant to maintain.

**Comment by siddharth-agrawal** [comment]
Final thoughts on this? I agree with @vrv, I think we should have one sentence for each op that supports broadcasting.

**Comment by girving** [comment]
I'll reverse my previous position: putting a sentence in every op, ideally with a link to a more detailed discussion of broadcasting, would be great.

**Comment by michaelisard** [comment]
@zffchen78 would you update the doc based on the comments in #3534?

**Comment by tatatodd** [comment]
@zffchen78 Friendly ping, can you update this issue once it's fixed?

**Comment by vrv** [comment]
I believe this has been "fixed" with a commit that added this to all of the element wise ops in their cc files.
