### ISSUE TITLE
Saving data as SequenceExample and reading TFRecords for LSTM

### ISSUE THREAD

**Issue by dishkakrauch** [tensorflow/tensorflow#50804]
Let's say I have a 3dimentional dataset with shape (sample, timesteps, features) and I want to save it with suitable tensroflow dataset format, e.g. using SequenceExample for further reading with TFRecord and using in LSTM. There is a dataset:

```
import numpy as np
import tensorflow as tf
import numexpr

data = np.array(
[
    [
        [1 , 10, ],
        [2 , 11, ],
    ],
    [
        [2 , 11, ],
        [3 , 12, ],
    ]
], dtype=np.float32)
y = np.array([101., 202.], dtype=np.float32)
```

There is a model:

```
inputs= tf.keras.layers.Input(
shape=(2, 2),
name='input',
)
model = tf.keras.layers.LSTM(
    units=data.shape[2],
    return_sequences=False,
    return_state=False,
    name='lstm',
)(inputs)
model = tf.keras.layers.Dense(
    units=1,
    name='dense',
)(model)
outputs = model
loss = tf.keras.losses.MSE
model = tf.keras.Model(
    inputs=inputs,
    outputs=outputs,
    name='model',
)
model.compile(
    optimizer='rmsprop',
    loss='mse',
    metrics='mse',
)
model.summary()
model.fit(
    x=data,
    y=y,
    batch_size=1,
)
```

Let's try to save and read dataset using tensorflow API:

```
def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

# writer
options = tf.io.TFRecordOptions(
    compression_type='ZLIB',
    flush_mode=None,
    input_buffer_size=None,
    output_buffer_size=None,
    window_bits=None,
    compression_level=0,
    compression_method=None,
    mem_level=None,
    compression_strategy=None,
)
writer = tf.io.TFRecordWriter(
    path=r'test.tfrecord',
    options=options,
)
# iterate over each row
for i in range(data.shape[0]):
    # set example id
    sample_dict = {
        'index': tf.train.Feature(int64_list=tf.train.Int64List(value=[i]))
    }
    features_list = {}
    # iterate over each feature
    for c in range(data[0].shape[1]):
        feature_values = [
            _float_feature(v) for v in data[i][:, c]
        ]
        features_list[str(c)] = tf.train.FeatureList(feature=feature_values)
    # set example
    example = tf.train.SequenceExample(
        context=tf.train.Features(feature=sample_dict),
        feature_lists=tf.train.FeatureLists(feature_list=features_list)
    )
    # write
    writer.write(example.SerializeToString())
writer.close()

# read raw
data_raw = tf.data.TFRecordDataset(
    filenames=[r'test.tfrecord'],
    compression_type='ZLIB',
    buffer_size=10*1024, # 10MB
    num_parallel_reads=numexpr.detect_number_of_cores()-1,
)
# parse real
schema = dict(
    zip(
        [str(s) for s in range(data[0].shape[1])],
        [tf.io.FixedLenSequenceFeature([], dtype=tf.float32)] * data[0].shape[1]
    )
)
def decode_fn(record_bytes):
    context, features = tf.io.parse_single_sequence_example(
        serialized=record_bytes,
        context_features={'index': tf.io.FixedLenFeature([], dtype=tf.int64)},
        sequence_features=schema,
    )
    return features
# read real
for r in data_raw.map(decode_fn):
    print(r, '\n')
```

When I'm trying to fit model with tensorflow dataset it's getting me an error

```
model.fit(
    data_raw,
    batch_size=1,
)
ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=0. Full shape received: []
```

I understand that I did not add label to tensorflow dataset but it does not matter in this case cause dataset has no incomplitable shape. Can anybody help me to understand why and where am I wrong in the code?

**Comment by UsharaniPagadala** [comment]
@dishkakrauch 

Could you please share the colab gist,it will help us analyse better.

and also refer similar issues  [link1](https://github.com/keras-team/keras/issues/7403) , [link2](https://ai-pool.com/d/input-0-is-incompatible-with-layer-lstm--expected-ndim-3--found-ndim-2-in-keras), and let us know if it helps.Thanks

**Comment by dishkakrauch** [comment]
@UsharaniPagadala hey, your are not related to my problem with TFRecords.
Have you read all description of my question?
Here is colab link - https://colab.research.google.com/drive/1uOT4Mx7oP44HRqvKok9HVWjEBvcLSJuj?usp=sharing

**Comment by UsharaniPagadala** [comment]
@dishkakrauch 

It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](https://github.com/keras-team/keras/issues) repository instead. As [previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) all future development of Keras is expected to happen in the keras-team/keras repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by dishkakrauch** [comment]
@UsharaniPagadala 

I can't see relation between problem with TFReocrds and keras library. I've attached code and colab notebook. I hope that you read it from the scratch and understand that this issue 100% related to tensorflow python library.
Let me shortly describe what am I trying to do is saveing 3dimentional time series data with TFRecords and using it with LSTM net.
Hope this helps.

**Comment by dishkakrauch** [comment]
I've added decode function and mapped it to tfrecord dataset. This fixed everything. Thx.
