### ISSUE TITLE
Regarding Scroll for the nearest points

### ISSUE THREAD

**Issue by Srkshaikh5** [tensorflow/tensorflow#50808]
When we make a  projector using the vectors and select the 100 nearest points, then for the name of points we can see in the bottom left is not scrollable to see more nearest points.

The area can be see  in the attached file.
![image](https://user-images.githubusercontent.com/37951124/125999818-e7cdec52-f761-4c67-9465-13a5b2b78282.png)

**Comment by UsharaniPagadala** [comment]
@Srkshaikh5 

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced] .

and also refer the similar [issue](https://github.com/tensorflow/tensorflow/issues/17867)

If this is only related to the scroll option post this in tensorboard [repo](https://github.com/tensorflow/tensorboard/issues).Thanks
