### ISSUE TITLE
make tf.rsqrt available!

### ISSUE THREAD

**Issue by codingpy** [tensorflow/tensorflow#50803]
**System information**
- TensorFlow version: 2.5.0
- Are you willing to contribute it: Not Sure

Since TensorFlow 2.0.0, why `tf.rsqrt` is unavailable while `tf.square`, `tf.reduce_sum` and etc are not?

From my opinion, TensorFlow should acts as a math calculating framework, so it should provide some shortcuts for `tf.math` calculation. Like PyTorch, every calculation can be carried out via top-level module.

Why you guys remove them from `tensorflow` module?

```python
tf.sqrt  # <function tensorflow.python.ops.math_ops.sqrt(x, name=None)>

tf.rsqrt # AttributeError: module 'tensorflow' has no attribute 'rsqrt'
```

I think not only `tf.rsqrt`, there are also some other functions should be bring back. Or, you should provide some reasonable explanation, especially:
  - Why `tf.sqrt` are available while `tf.rsqrt` are not?
  - Why some math functions are removed from top-level module since 2.0.0?

**Comment by rmothukuru** [comment]
@codingpy,
The **`Tensorflow API`** for **`rsqrt`** is available as [tf.math.rsqrt](https://www.tensorflow.org/api_docs/python/tf/math/rsqrt?hl=en). Is this what you are looking for? Thanks!

**Comment by codingpy** [comment]
Yes, I know. But I also wanna know that:
  - Why tf.sqrt are available while tf.rsqrt are not?
  - Why some math functions are removed from top-level module since 2.0.0?

**Comment by cantonios** [comment]
@codingpy the move was for better modularization.

The `sqrt` function is also now under `tf.math`, and is not documented as being top-level anymore (although the example in the documentation does use it at the top level... that should be updated).  In fact, all the math ops were moved - we just happen to export some at the top-level still, mainly for backward compatibility for some existing models.
