### ISSUE TITLE
no such package '@lodash//': Error downloading...

### ISSUE THREAD

**Issue by ChadTaljaardt** [tensorflow/tensorflow#5080]
Trying to install Tensorflow and getting this issue:

chad@chad-GA-990XA-UD3:~/tensorflow$ ./configure
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.5
Please specify the location where cuDNN 5.1.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.

INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..........
ERROR: /home/chad/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@lodash//': Error downloading from https://github.com/lodash/lodash/archive/3.8.0.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/lodash: Error downloading https://github.com/lodash/lodash/archive/3.8.0.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/lodash/3.8.0.tar.gz: Timed out connecting to https://github.com/lodash/lodash/archive/3.8.0.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: /home/chad/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@lodash//': Error downloading from https://github.com/lodash/lodash/archive/3.8.0.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/lodash: Error downloading https://github.com/lodash/lodash/archive/3.8.0.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/lodash/3.8.0.tar.gz: Timed out connecting to https://github.com/lodash/lodash/archive/3.8.0.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
chad@chad-GA-990XA-UD3:~/tensorflow$ 

Can anyone help?

**Comment by ChadTaljaardt** [comment]
So i ran it again and now i'm getting the same sort of error but for different packages..

chad@chad-GA-990XA-UD3:~/tensorflow$ ./configure
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.5
Please specify the location where cuDNN 5.1.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
...........
ERROR: /home/chad/tensorflow/tensorflow/core/platform/default/build_config/BUILD:75:1: no such package '@highwayhash//': Error downloading from http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/highwayhash: Error downloading http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/highwayhash/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz: Timed out connecting to http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz : connect timed out and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: /home/chad/tensorflow/tensorflow/core/platform/default/build_config/BUILD:75:1: no such package '@highwayhash//': Error downloading from http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/highwayhash: Error downloading http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz to /home/chad/.cache/bazel/_bazel_chad/e711407cb831141b1f7166a396931060/external/highwayhash/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz: Timed out connecting to http://github.com/google/highwayhash/archive/4bce8fc6a9ca454d9d377dbc4c4d33488bbab78f.tar.gz : connect timed out and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
chad@chad-GA-990XA-UD3:~/tensorflow$ 


I have run pings to google.com and github.com while running this operation and both pings are fine and don't time out.

**Comment by ChadTaljaardt** [comment]
Every time i run this it happens with different packages..

**Comment by asimshankar** [comment]
This seems like there might be some networking issues on the device you're running the build on. I see many error messages of the form "Timed out connecting to <some URL>" in the output you've provided above.

Perhaps your internet connection is a bit flaky at this time?

**Comment by ChadTaljaardt** [comment]
@asimshankar I don't think so, i have been running many tests constantly and getting this same issue, while the configure is running i can see the script is transferring and 0b/s but if i open the link its trying to download in the browser then it downloads fine, but the script still cant get it. and while the test is running i had monitors monitoring the network , pints, qos, and i did live transfers and everything went smoothly. 

I think this is something code related, but im not sure.

**Comment by asimshankar** [comment]
Perhaps there is some proxy or other networking configuration set in the browser?
Can you download these files on the command line using `curl` or `wget`?

**Comment by ChadTaljaardt** [comment]
There is no specific config set, brand new os installed. and yeah i can download with curl and wget :)

**Comment by ChadTaljaardt** [comment]
I have tried this morning and getting same issue but internet seems fine.

**Comment by ChadTaljaardt** [comment]
@asimshankar Do you know if there is a temporary workaround where i can download the packages manually and put them somewhere to make it work?

**Comment by asimshankar** [comment]
So it seems like you're having an issue with bazel being able to download dependencies. Unfortunately, debugging that isn't something that we have the bandwidth for in the TensorFlow team. I'd encourage you to seek advice on stackoverflow and/or bazel. 

That said, one possibility is that there is some configuration issue preventing Java programs from fetching data over the network (bazel is written in Java). Is there a simpler program (such as something like https://docs.oracle.com/javase/tutorial/networking/urls/readingURL.html) you can use to validate network access from the JVM?

An alternative workaround: we did see someone try this trick: https://github.com/tensorflow/tensorflow/issues/5029#issuecomment-254769127
to work with pre-downloaded packages.

Hope that helps!

**Comment by asimshankar** [comment]
Closing this issue out due to inactivity. Let us know if there still is a problem. Thanks!

**Comment by ChadTaljaardt** [comment]
Thanks, the method worked. I forgot to reply back. 

I downloaded all the files manually and made a virtual server to serve the files and then changed the urls in the code manually so that it would download the files locally.

Thanks for the help you provided.
