### ISSUE TITLE
Problem in adjust gamma function (tf.image.adjust_gamma)

### ISSUE THREAD

**Issue by tejal567** [tensorflow/tensorflow#50800]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Not applicable (NA)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below):  2.5.0
- Python version: NA
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Pixels values are manipulated using this equation: Out = gain * In**gamma

**Describe the expected behavior**
This function should preserve range of pixel values by first converting them between 0 and 1 and then again rescaling back to original range or atleast provide an argument for preserving range.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):  yes

**Comment by tilakrayal** [comment]
@tejal567 ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Thanks!

**Comment by tejal567** [comment]
You can take any image and call tf.image.adjust_gamma on it. You will see that range of image pixel values is changed. This should not happen. Suppose a person calls this function on RGB images where pixel value of each channel is between 0 and 255. After using this function it will no longer remain between 0 and 255. We can provide an argument in this function to preserve range.

**Comment by tilakrayal** [comment]
@tejal567 ,

Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet you are using.Thanks!
