### ISSUE TITLE
TensorFlow Certificate Network - region - australiasia 

### ISSUE THREAD

**Issue by BrianHwang** [tensorflow/tensorflow#50812]
https://developers.google.com/certification/directory/tensorflow

select australia for region is not available due to incorrect name shown as australiasia.

selecting australiasia shows noting nether australia or Asia. 

I just passed Tensorflow exam and want to show my profile correct in australia.

![image](https://user-images.githubusercontent.com/24234662/126030411-4bf4f5e5-917e-46d9-bc13-9c025d357c2f.png)

**Comment by Saduf2019** [comment]
@BrianHwang 
Kindly open a tf discussion forum issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!
