### ISSUE TITLE
why there are so many different versions for models?

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5081]
I am confused about the versions of tensor flow models. There are at lease 3.

1) This one i can call as **main** folder.

https://github.com/tensorflow/models

2) Another one is inside of the main folder is called **slim** and it has instructions about how to use, such as **train_image_classifier.py** , which currently i am using. I do not need write more code, just input some parameters.

https://github.com/tensorflow/models/tree/master/slim

3) the second **slim** is in the folder blow, which provide different instructions as above **slim**.  It seems that I must write additional python code to make it work. And the **learning.py** under this slim folder is different from above **train_image_classifier.py**.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim

============

Is there any necessity to provide so many branches or versions?  I guess they belong to different teams? Is there any consensus (internally) about which is the major one? This may not be a technical issue but a political issue.

**Comment by asimshankar** [comment]
The tensorflow/models repository contains models for multiple tasks and the code used to build them. For example, tensorflow/models/im2txt is very different from tensorflow/models/inception.

(2) and (3) that you point out are very similar and over time they will be consolidated.
A general rule of thumb is that models in the tensorflow/models are more of a demonstration of interesting models built with TensorFlow while the code in the tensorflow/tensorflow repository is the supported API of TensorrFlow.

Hope that helps.
