### ISSUE TITLE
TF2 ‘saved_model.pb’ from ‘exporter_main_v2.py’ is different than ‘saved_model.pb’ from official TF2 Zoo

### ISSUE THREAD

**Issue by ahmadchalhoub** [tensorflow/tensorflow#50817]
Please make sure that this is a bug. As per our
GitHub Policy,
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
TensorFlow installed from (source or binary): pip
TensorFlow version (use command below): 2.3.0
Python version: 3.6.9
Bazel version (if compiling from source): -
GCC/Compiler version (if compiling from source): -
CUDA/cuDNN version: CUDA 11.4
GPU model and memory: GeForce RTX 3090
I am trying to convert a re-trained TF2 object detection SSD MobilenetV2 model to a proprietary framework. I have successfully re-trained the network and it runs properly. However, I am having trouble with converting the saved_model.pb to the other framework. The conversion script from the SDK I am working with performs optimization on the saved_model.pb, using 'meta_optimizer.cc', which returns an empty graph after running through my re-trained model. I used 'exporter_main_v2.py' to export my re-trained checkpoint to the saved_model.pb which I am having trouble with.

The issue is not with my training or checkpoints, but with the exporting process from checkpoint to a saved_model.pb using 'exporter_main_v2.py'. I know this because I downloaded the SSD MobilenetV2 model from the TF2 Zoo to test with it. I have no issue converting the official saved_model.pb file found in the official repo, but when I try to convert the official checkpoints found in the repo to a saved_model.pb using 'exporter_main_v2.py', I face the same issue trying to convert the newly produced saved_model.pb file to the proprietary framework. This means that something wrong is happening when executing the 'exporter_main_v2.py' script.

Describe the expected behavior
The exported saved_model.pb file should not be different than the official saved_model.pb file found in the official repo.

The following is what I get, showing 0 nodes and 0 edges grappler_empty_graph
![AAEA8FD8-1609-4BAC-AE9B-53918E23EA20](https://user-images.githubusercontent.com/84783887/126050092-3161c0b0-ce22-4cb5-a054-8fcb08c4933e.png)

Standalone code to reproduce the issue
The model I downloaded is: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz

The command I used to export the official checkpoint to a saved_model.pb is: python ~/models/research/object_detection/exporter_main_v2.py --input_type image_tensor --pipeline_config_path pipeline.config --trained_checkpoint_dir checkpoint/ --output_directory exported_model/

**Comment by ahmadchalhoub** [comment]
I have had some discussion about this on the tensorflow/models repo and they suggested that I ask for https://github.com/tensorflow/models/issues/10120 assistance here. Refer to for details.

**Comment by bhack** [comment]
Have you tried to `sha256sum` the savedmodel in the official `tar.gz` with the one exported yourself with TF 2.4.0 from that same `tar.gz`?

**Comment by ahmadchalhoub** [comment]
I have not heard of `sha256sum` before to be honest and not sure how to use it. Any guidance/details you could help with? What would I be looking for exactly?

**Comment by bhack** [comment]
E.g. on Ubuntu https://help.ubuntu.com/community/HowToSHA256SUM

If the process is determinstic you could have that same hash in the end with 2.4.0.

**Comment by ahmadchalhoub** [comment]
Thank you for the suggestion! I do not have access to my computer at the moment but I will try it within the coming 2 days and I will keep you updated.

**Comment by bhack** [comment]
I hope that now you can understand my comment at https://github.com/tensorflow/models/issues/10120#issuecomment-881955457

So If the process is determinstic also the model garden team could reproduce exaclty that same hash on the savedmodel in `tar.gz` with a new export using a specific fixed TF and model garden version (exaclty the one that produced the saved model in the `tar.gz`).

**Comment by ahmadchalhoub** [comment]
I am closing this issue since it has been resolved on the original issue post (https://github.com/tensorflow/models/issues/10120)
