### ISSUE TITLE
Which version of CUDA and cuDNN should i use with tensorflow2.5.0 ?

### ISSUE THREAD

**Issue by Patrick-CH** [tensorflow/tensorflow#50819]
https://tensorflow.google.cn/install/source_windows#gpu
In this page, I can't figure out what version of CUDA and cuDNN should I use with tf2.5.0.
When I use my tensorflow, it can't recognize my GPU.
it shows:
2021-07-18 14:45:58.223694: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-18 14:45:58.223904: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**System information**
- Windows 10
- TensorFlow installed from (source or binary): https://pypi.python.org/simple
- TensorFlow version: 2.5.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.2 cuDNN 8.2
- GPU model and memory: Nvidia 1660 Ti

**Describe the problem**
When I use my tensorflow, it can't recognize my GPU.
I think it is a version problem, but in this page[https://tensorflow.google.cn/install/source_windows#gpu] I can't find which version to use.

So, please update the installation info page and let us know which version of CUDA and cuDNN to use. Thanks!

**Comment by brightening-eyes** [comment]
you need cuda 11.2 and cuDNN 8.1.0
also,, you should copy cuDNN to cuda's path.
type nvcc --version in your cmd/shell window and you should get the version of your cuda. if you don't get that, it means you havent properly installed cuda and/or you havent added it to path

**Comment by Patrick-CH** [comment]
Thanks！

**Comment by ymodak** [comment]
https://www.tensorflow.org/install/source_windows#gpu

**Comment by BEStefanKerren** [comment]
I have a similiar issue where my CUDA V11.2 as well as my CUDNN V 8.1.0 does not get recognized by tensorflow 2.5. I managed to fix this by adding the mentioned libraries in System32. As described in this Issue https://github.com/tensorflow/tensorflow/issues/50589.
