### ISSUE TITLE
"ModuleNotFoundError", Some times the import of "tensorflow_addons" doesn't take place

### ISSUE THREAD

**Issue by RanaBan** [tensorflow/tensorflow#50827]
Some time the import works, some time it doesn't.
    `!pip install --user tensorflow-addons`
    `import tensorflow_addons as tfa`

Output:
Collecting tensorflow-addons
  Downloading https://files.pythonhosted.org/packages/66/4b/e893d194e626c24b3df2253066aa418f46a432fdb68250cde14bf9bb0700/tensorflow_addons-0.13.0-cp37-cp37m-manylinux2010_x86_64.whl (679kB)
     |████████████████████████████████| 686kB 4.3MB/s 
Requirement already satisfied: typeguard>=2.7 in /usr/local/lib/python3.7/dist-packages (from tensorflow-addons) (2.7.1)
Installing collected packages: tensorflow-addons
Successfully installed tensorflow-addons-0.13.0

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-29-4c254e4a3ee7> in <module>()
      1 get_ipython().system('pip install --user tensorflow-addons')
----> 2 import tensorflow_addons as tfa

ModuleNotFoundError: No module named 'tensorflow_addons'
-------------------------------------------------------------------------------------------------------------------------------
What to do?

**Comment by saikumarchalla** [comment]
@RanaBan  Please follow this [link](https://pypi.org/project/tensorflow-addons/) to  install tensorflow-addons package. 

I tried to import tensorflow addons on [colab](https://colab.research.google.com/gist/saikumarchalla/19580a43954bc479e5362d6cb8727f13/untitled113.ipynb) and it is working fine but not sure why it is not working some times.  Could you please try in virtual environment and let us know  if you are facing the issue still. Thanks!

**Comment by RanaBan** [comment]
Due to scarcity of resources, I use colab. 

The module imported this time and working fine.
