### ISSUE TITLE
Setting of Number of Threads for TFLite Interpreter API

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#50822]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I am using TFLite  label image example - https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/label_image/label_image.cc 

In this example, We are setting number of threads at line number 238.
```
if (settings->number_of_threads != -1) {
    interpreter->SetNumThreads(settings->number_of_threads);
  }
```

Could you confirm whether the number of threads setting is needed or not ?

Do the user need to specify the number of threads compulsory ?

**If not specified will it take max number of threads available ?** 

**Will this change the current api?** 

No need of setting the number of threads in the workflow.

**Who will benefit with this feature?**

Users need not to manually set the number of threads if its set to max threads available.

**Comment by ymodak** [comment]
If the number of threads are not specified then they will be implementation-defined and platform-dependent. 
See https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/Interpreter.Options#public-interpreter.options-setnumthreads-int-numthreads
