### ISSUE TITLE
dataset support prefetch_to_device

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#50825]
If model in the device(GPU) and dataset in the host(CPU), the data output by dataset must be memcpyH2D, All compute graph spend long time to wait memcpyH2D done.
I think we need a queue to cache output of dataset. so I find  https://github.com/tensorflow/tensorflow/issues/43905, this issues tell me we can use ```prefetch_to_device ``` by ```map().batch()``` or ```experimental::map_and_batch```. But in fact ```map(parallel_num).batch()``` is too slow, we need ```batch().map()``` and ```prefetch_to_device```

batch().map() nsys profiling:
![image](https://user-images.githubusercontent.com/33950866/126093526-c21f6edc-1bf2-4f7c-a6d2-2d6812f1bd4f.png)

I re-copy output of ParallelMapDataset::Iterator to device by set_gpu_compatible(true), and I got a more obvious speedup.
so I would like to add a dataset named copy_to_device, usage like:

```
ds = tf.data.TFRecordDataset(files).batch(batch_size).map(map_func,4).copy_to_device().prefetch(2).
it = ds.make_one_shot_iterator()
gn = it.get_next()
...
```

**Comment by jsimsa** [comment]
There is already `copy_to_device` transformation ([documentation](https://www.tensorflow.org/api_docs/python/tf/data/experimental/copy_to_device) and `prefetch_to_device` is implemented as you suggest [source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/ops/prefetching_ops.py#L62-L63). Could you explain how is what's available different from what you would like? Thanks.

**Comment by zhaozheng09** [comment]
> There is already `copy_to_device` transformation ([documentation](https://www.tensorflow.org/api_docs/python/tf/data/experimental/copy_to_device)) and `prefetch_to_device` is implemented as you suggest ([source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/ops/prefetching_ops.py#L62-L63)). Could you explain how is what's available different from what you would like? Thanks.

thx, and  I will close this question ~
