### ISSUE TITLE
Feature request - Check that QueueRunner enqueue ops use the correct queue

### ISSUE THREAD

**Issue by bb4242** [tensorflow/tensorflow#5082]
The documentation for [`tf.train.QueueRunner.__init__`](https://www.tensorflow.org/versions/r0.11/api_docs/python/train.html#QueueRunner) states:

"The enqueue ops do not have to all be the same op, but it is expected that they all enqueue tensors in `queue`."

Would it be possible for tensorflow to check that the given ops do in fact enqueue tensors in the correct queue, and throw an error if they do not?  I encountered a problem recently where I mistakenly passed the wrong queue to my `QueueRunner`, and as a result, the clean shutdown behavior described [here](https://www.tensorflow.org/versions/r0.11/how_tos/reading_data/index.html#creating-threads-to-prefetch-using-queuerunner-objects) wasn't working as expected.  Changing to the correct queue solved the problem.  This was definitely user error on my part, but it was a bit tricky to track this problem down, and it seems like the kind of thing that would be possible to check automatically.

**Comment by yaroslavvb** [comment]
There was no check preventing people from doing that, so there may be people using single queue runner to enqueue to multiple queues successfully out there. So starting to enforce that now will break those people

**Comment by bb4242** [comment]
OK, that sounds like a reasonable argument for not doing this. :)
