### ISSUE TITLE
'utf-8' codec can't decode byte 0xc1 in position 103: invalid start byte

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tensorflow#50837]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce 3090

**Describe the current behavior**
 when loading pipeline.config, it cause error. 
config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
even I installed tensorflow nightly version. but it is same. 

error is
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 103: invalid start byte

full log error is
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16452/1215164193.py in <module>
      1 print("s")
----> 2 config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

c:\users\pedro\anaconda3\envs\tensorflow1\lib\site-packages\object_detection\utils\config_util.py in get_configs_from_pipeline_file(pipeline_config_path, config_override)
    138 
    139     print("protto")
--> 140     proto_str = f.read()
    141     print(proto_str)
    142     print("proto")

c:\users\pedro\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    117       string if in string (regular) mode.
    118     """
--> 119     self._preread_check()
    120     if n == -1:
    121       length = self.size() - self.tell()

c:\users\pedro\anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     80       print(self.__name)
     81       self._read_buf = _pywrap_file_io.BufferedInputStream(
---> 82           compat.path_to_str(self.__name), 1024 * 512)
     83 
     84   def _prewrite_check(self):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 103: invalid start byte

**Comment by Saduf2019** [comment]
@kotran88 
Could you please refer to [this link](https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s) and let us know. [[link1](https://www.edureka.co/community/51644/python-unicodedecodeerror-codec-decode-position-invalid)],[[link2](https://github.com/llSourcell/tensorflow_chatbot/issues/17#issuecomment-866719858)]

**Comment by Saduf2019** [comment]
Moving this to closed status due to lack of activity.
