### ISSUE TITLE
tensorflow.python.data.ops.dataset_ops.BatchDataset to HDF5

### ISSUE THREAD

**Issue by bethven** [tensorflow/tensorflow#50840]
Hello,
I need to load large image datasets (JPEG and other types) with tensorflow and then transform them to HDF5, I have loaded the dataset with the following code, but I don't know how to transform it to HDF5.**

img = tf.keras.preprocessing.image_dataset_from_directory(
    '/home/tiny-imagenet-200/train/',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
)

I tried to do it like it did in python, but it doesn't work:

for i in range(len(img)):
    Imagen = cv2.imread(img)
    Imagen = cv2.resize(Imagen, (224, 224), interpolation=cv2.INTER_CUBIC)
    Imagen = cv2.cvtColor(Imagen, cv2.COLOR_BGR2RGB)
*****************
The error:

typeError                                 Traceback (most recent call last)
<ipython-input-18-94fcf3e072ce> in <module>
 
---> 10     Imagen = cv2.imread(img)
     11     Imagen = cv2.resize(Imagen, (224, 224), interpolation=cv2.INTER_CUBIC)
     12     Imagen = cv2.cvtColor(Imagen, cv2.COLOR_BGR2RGB)

TypeError: Can't convert object of type 'tensorflow.python.framework.ops.EagerTensor' to 'str' for 'filename'

I guess it is because of the type of object it generates that it is: tensorflow.python.data.ops.dataset_ops.BatchDataset

Please I would appreciate if someone can help me to know how to transform this to HDF5. Thank you.

**Comment by vulkomilev** [comment]
Will [`this`](https://stackoverflow.com/questions/55606909/how-to-use-tensorflow-dataset-with-opencv-preprocessing) work?

**Comment by UsharaniPagadala** [comment]
@bethven 

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=type%3Afeature&template=30-feature-request.md) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced].

also please refer this [comment](https://stackoverflow.com/questions/62211655/python-data-ops-dataset-ops-batchdataset-how-to-use-it-to-create-training-and).    Thanks
