### ISSUE TITLE
tensorflow-serving-apt signature key expired

### ISSUE THREAD

**Issue by jonathanlawhh** [tensorflow/tensorflow#50841]
### System information
- OS Platform and Distribution: Ubuntu 1804, Windows - Dockerfile, Google Cloud Build (Dockerfile)
- TensorFlow installed from (source or binary): apt

### Problem
tensorflow serving apt key is expired
[https://www.tensorflow.org/tfx/serving/setup#installation_2](https://www.tensorflow.org/tfx/serving/setup#installation_2)

**Command to run**
```bash
echo "deb [arch=amd64] http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | sudo tee /etc/apt/sources.list.d/tensorflow-serving.list && \
curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | sudo apt-key add -
```

**Error**
GPG error: http://storage.googleapis.com/tensorflow-serving-apt stable InRelease: The following signatures were invalid: KEYEXPIRED...

**Comment by lilao** [comment]
This is a duplicate of https://github.com/tensorflow/serving/issues/1896 and should be resolved now. Please let us know if it still doesn't work.

**Comment by jonathanlawhh** [comment]
Hi, sorry I might have missed that issue while searching, causing a duplicate. Thank you it works fine now. Closing this issue.
