### ISSUE TITLE
Discrepancy between expected and tflite quantization parameters

### ISSUE THREAD

**Issue by abagrahari** [tensorflow/tensorflow#50857]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux Ubuntu 20.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `N/A`
- TensorFlow installed from (source or binary): `binary (pip package)`
- TensorFlow version (use command below): `2.5.0`
- Python version: `3.8.10`
- Bazel version (if compiling from source): `N/A`
- GCC/Compiler version (if compiling from source): `N/A`
- CUDA/cuDNN version: `N/A`
- GPU model and memory: `N/A  (using CPU)`

**Describe the current behavior**
Hi there! :wave: Thank's for the great work on Tensorflow, TFLite!

Unfortunately, I’m facing an issue where there seems to be a discrepancy between the quantization parameters recorded by a fully-quantized tflite model.

For an input `x` and kernel `w`, I manually compute `tf.matmul(x, w)` and then compute the scale/zero-point of the result.  These are the values I get:
```
Parameters from manual computation
Scale: 0.09185781291886871, Zero-point: -3.0351044277537085
````
but when I build the equivalent model in tflite, these are the scale/zp it calculates:
```
Parameters from tflite model
Scale: 0.09184519201517105, Zero-point: -3
```
I would expect them to be the same, but they are not. [Here is an example to reproduce the issue](https://colab.research.google.com/drive/1QjwtcNIBb-lqtuMod6tV233D4UFvQ0dS?usp=sharing).

This discrepancy is causing larger TFLite models to produce significantly different outputs than expected, when compounded across multiple layers. [Here is a demonstration of how these errors compound with more layers](https://colab.research.google.com/drive/1PJjr6EOGJXZ0dvaoGKSJaFzA4pIiv9xe?usp=sharing). 

**Describe the expected behavior**
I would expect the quantization parameters to be the same.

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): `no`
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

[Link to Colab example](https://colab.research.google.com/drive/1QjwtcNIBb-lqtuMod6tV233D4UFvQ0dS?usp=sharing )
The model is 1 Flatten layer + 4 simple `Dense` layers with `use_bias=False`, on the `MNIST` dataset.

**Other info / logs** Include any logs or source code that would be helpful to diagnose the problem.

A visualization of the tflite model using `python -m tensorflow.lite.tools.visualize` and netron are attached.

![gist](https://user-images.githubusercontent.com/70828198/126397792-54a3f092-de97-41a0-9fdc-f4b9c2af563e.png)
![gist_netron](https://user-images.githubusercontent.com/70828198/126397793-c4b93dda-4aa2-4044-81d0-9b5912187f2c.png)

**Comment by wangtz** [comment]
Hi Renjie/Jian,

Could any of you help check on this issue with quantization parameters? Feel free to pass it around.

Thanks,
Tiezhen

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11 as well. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/1058229809827a239722f5dcbb9f128e/50857.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
