### ISSUE TITLE
Crash/Force termination in distributed training

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#50853]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.9
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.6
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.2.0
- CUDA/cuDNN version: 11.1.1
- GPU model and memory: A100

**Describe the current behavior**

When running the distributed training, i.e. with MultiWorkerMirroredStrategy, the application runs through and then crashes with "terminate called without an active exception"

**Standalone code to reproduce the issue**

Taken from #50790: 

```
import tensorflow as tf
from mpi_cluster_resolver import MPIClusterResolver

resolver = MPIClusterResolver()
strategy = tf.distribute.MultiWorkerMirroredStrategy(cluster_resolver=resolver)

with strategy.scope():
    (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
    x_train = x_train / 255.0
    train_data = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(128)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.SGD(),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

is_master = resolver.task_id == 0
verbose = 2 if is_master else 0
model.fit(train_data.repeat(), epochs=1, steps_per_epoch=10, verbose=verbose)
```

With 
[mpi_cluster_resolver.py.txt](https://github.com/tensorflow/tensorflow/files/6823734/mpi_cluster_resolver.py.txt)

**Other info / logs**
I traced the crash to `TF_DeleteGraph` Python wrapper by following the stacktrace and inserting debug information: 
[tf.txt](https://github.com/tensorflow/tensorflow/files/6848724/tf.txt)

As you can see the code is called during runtime shutdown and ultimately reaches pybind11s `~gil_scoped_release` which calls `PyEval_RestoreThread`. This is documented as terminating when the runtime is finalized: https://docs.python.org/3/c-api/init.html#c.PyEval_RestoreThread

So to fix this either all threads created by TF must be collected and freed before python starts finalizing or the `pybind11::gil_scoped_release` must be removed from cleanup functions
See also https://github.com/pybind/pybind11/pull/2657

**Comment by berlinsaint** [comment]
does this has a workaround？

**Comment by Flamefire** [comment]
Workaround/fix is https://github.com/tensorflow/tensorflow/pull/56634
