### ISSUE TITLE
Prediction depends on Batch size

### ISSUE THREAD

**Issue by pedrogalher** [tensorflow/tensorflow#50860]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: https://colab.research.google.com/drive/1moHCzJlvoc4KXdOFpwQTqBaQLJ9paeHi?usp=sharing
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **TensorFlow version (use command below)**: TF 2.5.1
-   **Python version**: 3.6
-   **GPU model and memory**: NVIDIA 3080 10GB

### Describe the problem

I have trained a model for semantic segmentation in Tensorflow. I want to run the predictions of a set of 64 new images (they are greyscale images, therefore the number of channels is 1). For this, I wrote two methods and compare the results (I initially expected that they would provide the same value):

Method A: Load all the images into a 4D array (NB_IMAGES, ROWS, COLS, 1). I run the prediction in the entire 4D array, i.e., all images at the same time (Batch size=64).

Method B: I run the predictions in each image separately. Each image is loaded as a 4D array of the shape (1, ROWS, COLS, 1). Batch size=1.

After running it in colab and displaying the prediction of the third class for the first image: 

```
Method A:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Method B
[[0.02932691 0.01693235 0.0095239  ... 0.33940026 0.14944448 0.1266723 ]
 [0.00729698 0.00919143 0.00475383 ... 0.21612257 0.05683496 0.05206718]
 [0.00214194 0.00178528 0.0010777  ... 0.35763222 0.11783648 0.05261206]
 ...
 [0.00742953 0.00188467 0.00282917 ... 0.04309301 0.01660612 0.01606987]
 [0.01856694 0.00265247 0.00360173 ... 0.03587637 0.01677576 0.02269481]
 [0.04196882 0.01845963 0.01436812 ... 0.07170304 0.09968089 0.16050124]]
```

However, as you can see in the colab attached, thre predictions differ greatly. 
I'm really lost about these differences in the predictions, considering that the model is the same, no batch_normalization was used and the data set is also the same. Does anybody know or have any experience regarding the effect of batch size and prediction?

### Source code / logs
https://colab.research.google.com/drive/1moHCzJlvoc4KXdOFpwQTqBaQLJ9paeHi?usp=sharing

**Comment by UsharaniPagadala** [comment]
@pedrogalher 

It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](https://github.com/keras-team/keras/issues) repository instead. As previously [announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) all future development of Keras is expected to happen in the keras-team/keras repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!
