### ISSUE TITLE
Some workers doesn't exist when training in distributed mode

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#5086]
We have tried distributed TensorFlow and it works for training. But sometimes only some workers will execute the code and exit after training. Sometimes all workers will exit finally with the same code. 

The code of distributed TensorFlow application is [here](https://github.com/tobegit3hub/deep_recommend_system/tree/master/distributed). Is that a bug or can anyone explain why?

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN:  Not installed.

TensorFlow version: 0.11.0rc0

**Comment by yaroslavvb** [comment]
Your ps should never exit (because of `server.join()`)

**Comment by tobegit3hub** [comment]
Thanks @yaroslavvb for quick response.

Sorry about my statement. When I mention "worker", I mean the "worker task" not including "ps". 

I thinks the actual workers should exit after training. And sometimes they work like what we expect but sometimes not.

**Comment by yaroslavvb** [comment]
I'm interpreting your original issue is that some workers get stuck. If so, there can be many reasons, and you could isolate better where exactly it gets stuck, here's a related issue with better information -- https://github.com/tensorflow/tensorflow/issues/4932#issuecomment-254234355

**Comment by tobegit3hub** [comment]
Yes and thanks @yaroslavvb . We will have a look at that issue.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please let us know when further information is available and we will reopen. Thanks!
