### ISSUE TITLE
copies data from gpu to cpu

### ISSUE THREAD

**Issue by xmy19029** [tensorflow/tensorflow#50869]
I learned that the GPU ops' running code is in` /lite/delegates/gpu/cl/api.cc`.The code for Run() is as follows:
```
absl::Status Run() override {
#ifdef CL_DELEGATE_ALLOW_GL
    if (gl_interop_fabric_) {
      RETURN_IF_ERROR(gl_interop_fabric_->Start());
    }
#endif
    for (const auto& input : inputs_) {
      RETURN_IF_ERROR(input->CopyFromExternalObject());
    }

    RETURN_IF_ERROR(RunWithoutExternalBufferCopy());

    bool has_async_copies = false;
    for (const auto& output : outputs_) {
      RETURN_IF_ERROR(output->CopyToExternalObject());
      if (output->def().external_def.object_def.object_type ==
          ObjectType::CPU_MEMORY) {
        has_async_copies = true;
      }ng 
    }
#ifdef CL_DELEGATE_ALLOW_GL
    if (gl_interop_fabric_) {
      RETURN_IF_ERROR(gl_interop_fabric_->Finish());
    }
#endif
    if (has_async_copies) {
      RETURN_IF_ERROR(queue_->WaitForCompletion());
    }
    return absl::OkStatus();
  }
```
I found that the outputs_ has only one element,and the elapsed time of CopyToExternalObject() depends on the number of ops running on the GPU.In other words,the more ops are deployed on GPU,the longer the time will be.
It doesn't make sense.Normally,we only need to copy the last op's data.I wonder why this is the case.
Thanks in advance!

**Comment by tilakrayal** [comment]
@xmy19029 ,

In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.Thanks!

**Comment by xmy19029** [comment]
@tilakrayal Hi,the version is 2.4.2.
I got all the code from tensorflow.All I did is measuring the elapsed time of CopyToExternalObject(),which is in /tensorflow/lite/delegates/gpu/cl/api.cc.
Thanks for your reply!

**Comment by tilakrayal** [comment]
@xmy19029 ,

In order to reproduce the issue,can you please provide the exact link for the code or colab gist.It helps to debug the issue in our environment.Thanks!
