### ISSUE TITLE
Tensorflow estimator returns the same answer

### ISSUE THREAD

**Issue by aleks73337** [tensorflow/tensorflow#50872]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform: Ubuntu 18.04.5 LTS
- TensorFlow installed from pip3
- TensorFlow version (use command below): all versions 2.5+
- Python version: 3.6.9
- CUDA/cuDNN version:  11.2
- GPU model and memory: 3090, 2060

**Describe the current behavior**
I create a tf.keras model, train it and save it with model.save as keras model. After that I transform model to tf estimator with 
`tf.keras.estimator.model_to_estimator`, create input reciever and save estimator with it `estimator.export_saved_model(EXPORT_PATH, serving_input_receiver_fn = serving_fn)`
After that I load this 2 models in my jupyter notebook and send same pictures. From two same models in different formats I get different results. Moreover, model that were saved as estimator returns the same answer on all pictures, but the model in H5 format returns different answers.

**Describe the expected behavior**
Estimator and H5 model return the same answer. Estimator return different answers.

It works with all tested models and datasets (5 models and 3 datasets). I watched answers in tensorboard during training and they are normal. The problem starts when I create estimator. I can't avoid creating estimator because I need it for TF serving.

**Comment by tilakrayal** [comment]
@aleks73337 ,

In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.Thanks!

**Comment by aleks73337** [comment]
@tilakrayal 
[test_html.txt](https://github.com/tensorflow/tensorflow/files/6860896/test_html.txt)
[test_ipynb.txt](https://github.com/tensorflow/tensorflow/files/6860897/test_ipynb.txt)

**Comment by tilakrayal** [comment]
@aleks73337 ,

Given .txt formatted code is hard to replicate .Can you please provide the code or colab gist to reproduce and analyse the issue in our environment.Thanks!

**Comment by aleks73337** [comment]
Just change the format. It's normal jupyter files, but with changed formats for uploading to github 
-------- Исходное сообщение --------От: tilakrayal ***@***.***> Дата: 23.07.2021  09:48  (GMT+03:00) Кому: tensorflow/tensorflow ***@***.***> Копия: aleks73337 ***@***.***>, Mention ***@***.***> Тема: Re: [tensorflow/tensorflow] Tensorflow estimator returns the same answer (#50872) 
@aleks73337 ,
Given .txt formatted code is hard to replicate .Can you please provide the code or colab gist to reproduce and analyse the issue in our environment.Thanks!

**Comment by tilakrayal** [comment]
@aleks73337 ,

Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet or colab gist.Thanks!

**Comment by aleks73337** [comment]
@tilakrayal, it's fully reproducible code just saved in txt format for uploading it to github. Ok, let me explain how to use it.
1. Download test_ipynb.txt
2. Change the format of file. test_ipynb.txt -> test.ipynb
3. Open it with jupyter notebook
Github doesn't allow to upload ipynb format files. So I just changed the format. But if you change the format back, it will work.

**Comment by tilakrayal** [comment]
@Saduf2019 ,

I was able to reproduce the issue in TF version [2.4](https://colab.research.google.com/gist/tilakrayal/86c34b6b96233d4b81662cb3c7a3137f/2-4test_ipynb.ipynb), [2.5](https://colab.research.google.com/gist/tilakrayal/28e143fe63730b17f3f3791b72182de2/2-5test.ipynb) and whereas in [nightly](https://colab.research.google.com/gist/tilakrayal/a8466b35f51345a7c66939d84977d080/nightlytest_ipynb.ipynb) version and it is  noticed that session is being crashed. Please, find the gist here. Thanks!
