### ISSUE TITLE
C++ style concern of potential memory leak

### ISSUE THREAD

**Issue by byronyi** [tensorflow/tensorflow#5087]
All the factories methods consisting a ``static`` pointer to heap allocated variable potentially cause memory leak, as the static in-function variables are allocated/disposed for the program life-time, but if the object is dynamically allocated on heap, the object itself is never disposed (only its pointer gets disposed).

For example, in [session_factory.cc:37](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/session_factory.cc#L37)

```cpp
static mutex* get_session_factory_lock() {
  static mutex session_factory_lock;
  return &session_factory_lock;
}

typedef std::unordered_map<string, SessionFactory*> SessionFactories;
SessionFactories* session_factories() {
  static SessionFactories* factories = new SessionFactories;
  return factories;
}
```

Note that the ``factories`` is a *static pointer*, not a *pointer to a static object*. Since the object itself is not static, it will not be disposed and cause memory leak.

Suggested change:
```cpp
static mutex* get_session_factory_lock() {
  static mutex session_factory_lock;
  return &session_factory_lock;
}

typedef std::unordered_map<string, SessionFactory*> SessionFactories;
SessionFactories* session_factories() {
  static SessionFactories factories = SessionFactories();
  return &factories;
}
```

One could easily write a small program and use ``valgrind`` to verify the memory leak. One example is [here](https://gist.github.com/a5b0d262e5f64f36b299003634493eca).

**Comment by asimshankar** [comment]
@byronyi : Destruction order of static objects is not fully specified in C++, so our [programming style](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables) avoids using them. This does mean that the destructor for objects allocated for the lifetime of the process are never called, but one could make the case that running those destructors at program exit (when all process memory is going to be released anyway) is of questionable value.

Hope that helps. Thanks.
