### ISSUE TITLE
AttributeError: type object 'IteratorBase' has no attribute 'from_structure'

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#50871]
ｔｅｎｓｏｒｆｌｏｗ　２．５
```

`
import tensorflow as tf

training_dataset = tf.data.Dataset.range(100).map(
    lambda x: x + tf.random.uniform([], -10, 10, tf.int64))
validation_dataset = tf.data.Dataset.range(50)

# A reinitializable iterator is defined by its structure. We could use the
# `output_types` and `output_shapes` properties of either `training_dataset`
# or `validation_dataset` here, because they are compatible.
iterator = tf.data.Iterator.from_structure(training_dataset.output_types,
                                           training_dataset.output_shapes)
next_element = iterator.get_next()

training_init_op = iterator.make_initializer(training_dataset)
validation_init_op = iterator.make_initializer(validation_dataset)

# Run 20 epochs in which the training dataset is traversed, followed by the
# validation dataset.
for _ in range(20):
    # Initialize an iterator over the training dataset.
    sess.run(training_init_op)
    for _ in range(100):
        sess.run(next_element)

    # Initialize an iterator over the validation dataset.
    sess.run(validation_init_op)
    for _ in range(50):
        sess.run(next_element)`
```

**Comment by sjtusmartboy** [comment]
Please tell me how to revise this piece of code and let it run with tf 2.5? The sooner the better, thanks a million.

**Comment by sjtusmartboy** [comment]
@saikumarchalla @ry @jmhodges @eggie5

**Comment by sjtusmartboy** [comment]
@saikumarchalla Is there any update?

**Comment by sjtusmartboy** [comment]
@Saduf2019 Any progress yet

**Comment by sjtusmartboy** [comment]
@Saduf2019 Any progress yet

**Comment by sjtusmartboy** [comment]
＠Saduf2019 Don't you think this is an important issue that should be fixed immediately. I've issued this for over three weeks, why there's no reply at all.

**Comment by mohantym** [comment]
Hi! @sjtusmartboy !Was able to resolve the issue with TF v2.5 ,  I changed the code using migration document . find the[ gist](https://colab.research.google.com/gist/mohantym/a8b6faa09656636c48c3ff84f096beab/50871.ipynb#scrollTo=gzq4U3SpmlQT) here Thanks!

**Comment by sjtusmartboy** [comment]
@mohantym thanks for your reply. If we're using eager mode, then how do we use tf.data.Iterator

**Comment by sjtusmartboy** [comment]
@mohantym thanks for your reply. If we're using eager mode, then how do we use tf.data.Iterator

**Comment by mohantym** [comment]
Hi @sjtusmartboy ,
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade code base to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Comment by dafengtian** [comment]
> ｔｅｎｓｏｒｆｌｏｗ　２．５
> 
> 
> `
> import tensorflow as tf
> 
> training_dataset = tf.data.Dataset.range(100).map(
>     lambda x: x + tf.random.uniform([], -10, 10, tf.int64))
> validation_dataset = tf.data.Dataset.range(50)
> 
> # A reinitializable iterator is defined by its structure. We could use the
> # `output_types` and `output_shapes` properties of either `training_dataset`
> # or `validation_dataset` here, because they are compatible.
> iterator = tf.data.Iterator.from_structure(training_dataset.output_types,
>                                            training_dataset.output_shapes)
> next_element = iterator.get_next()
> 
> training_init_op = iterator.make_initializer(training_dataset)
> validation_init_op = iterator.make_initializer(validation_dataset)
> 
> # Run 20 epochs in which the training dataset is traversed, followed by the
> # validation dataset.
> for _ in range(20):
>     # Initialize an iterator over the training dataset.
>     sess.run(training_init_op)
>     for _ in range(100):
>         sess.run(next_element)
> 
>     # Initialize an iterator over the validation dataset.
>     sess.run(validation_init_op)
>     for _ in range(50):
>         sess.run(next_element)`
> ```

**Comment by dafengtian** [comment]
问题已经解决。出现这个问题是因为TensorFlow2.X版本中，IteratorBase这个对象对应的类，没有封装from_structure这个属性。安装TensorFlow1.x版本即可解决这个问题。
The problem has been solved. This problem occurs because in TensorFlow2.X, the class corresponding to the IteratorBase object does not encapsulate the from_structure attribute. Install the TensorFlow1.x version to resolve this issue.

**Comment by dafengtian** [comment]
> ｔｅｎｓｏｒｆｌｏｗ　２．５
> 
> ```
> 
> `
> import tensorflow as tf
> 
> training_dataset = tf.data.Dataset.range(100).map(
>     lambda x: x + tf.random.uniform([], -10, 10, tf.int64))
> validation_dataset = tf.data.Dataset.range(50)
> 
> # A reinitializable iterator is defined by its structure. We could use the
> # `output_types` and `output_shapes` properties of either `training_dataset`
> # or `validation_dataset` here, because they are compatible.
> iterator = tf.data.Iterator.from_structure(training_dataset.output_types,
>                                            training_dataset.output_shapes)
> next_element = iterator.get_next()
> 
> training_init_op = iterator.make_initializer(training_dataset)
> validation_init_op = iterator.make_initializer(validation_dataset)
> 
> # Run 20 epochs in which the training dataset is traversed, followed by the
> # validation dataset.
> for _ in range(20):
>     # Initialize an iterator over the training dataset.
>     sess.run(training_init_op)
>     for _ in range(100):
>         sess.run(next_element)
> 
>     # Initialize an iterator over the validation dataset.
>     sess.run(validation_init_op)
>     for _ in range(50):
>         sess.run(next_element)`
> ```


问题已经解决。出现这个问题是因为TensorFlow2.X版本中，IteratorBase这个对象对应的类，没有封装from_structure这个属性。安装TensorFlow1.x版本即可解决这个问题。
The problem has been solved. This problem occurs because in TensorFlow2.X, the class corresponding to the IteratorBase object does not encapsulate the from_structure attribute. Install the TensorFlow1.x version to resolve this issue.
