### ISSUE TITLE
TF -> TFLite conversion error: could not rewrite use of immutable bound input

### ISSUE THREAD

**Issue by alexispascual** [tensorflow/tensorflow#50885]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**
- TensorFlow installation (pip package or built from source): **pip package**
- TensorFlow library (version, if pip package or github SHA, if built from source): **2.5.0**

### 2. Code

The model I'm trying to convert is a FasterRCNN model with an AlexNet backbone trained using PyTorch. From what I've gathered, the only way I could do this is by going from Torch -> ONNX -> Tensorflow -> TFLite. The conversion from Torch to ONNX succeeds but there's a couple of errors I encountered when converting from ONNX -> Tensorflow and subsequently from Tensorflow to TFLite. 

**Error 1:**  Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow. (solved but may be related)

This is an error on the ONNX -> TF conversion side which I solved by modifying the transforms in the Torch model to include an `align_corners=True` argument in the interpolation call:

```
def ObjDetModel():
  
    # Define backbone
    backbone = torchvision.models.alexnet(pretrained=True).features
    backbone.out_channels = 256

    # Define anchor generator
    anchor_generator = AnchorGenerator(sizes=((32, 64, 128, 256, 512),),
                           aspect_ratios=((0.5, 1.0, 2.0),))

    # Define ROI pooler
    roi_pooler = torchvision.ops.MultiScaleRoIAlign(featmap_names=['0'],
                                        output_size=7,
                                        sampling_ratio=2)

    # put the pieces together inside a FasterRCNN model
    model = FasterRCNN(backbone,
                      num_classes=2,
                      rpn_anchor_generator=anchor_generator,
                      box_roi_pool=roi_pooler)

    min_size=800
    max_size=1333
    image_mean = [0.485, 0.456, 0.406]
    image_std = [0.229, 0.224, 0.225]


    # Change the transform op through subclassing the original transform class
    transform = ModifiedRCNNTransform(min_size, max_size, image_mean, image_std)
    model.transform = transform

    return model

@torch.jit.unused
def _get_shape_onnx(image):
    # type: (Tensor) -> Tensor
    from torch.onnx import operators
    return operators.shape_as_tensor(image)[-2:]

@torch.jit.unused
def _fake_cast_onnx(v):
    # type: (Tensor) -> float
    # ONNX requires a tensor but here we fake its type for JIT.
    return v

def _resize_image_and_masks(image: Tensor, 
                            self_min_size: float, 
                            self_max_size: float,
                            target: Optional[Dict[str, Tensor]] = None,
                            fixed_size: Optional[Tuple[int, int]] = None,
                            ) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:
    if torchvision._is_tracing():
        im_shape = _get_shape_onnx(image)
    else:
        im_shape = torch.tensor(image.shape[-2:])

    size: Optional[List[int]] = None
    scale_factor: Optional[float] = None
    recompute_scale_factor: Optional[bool] = None

    if fixed_size is not None:
        size = [fixed_size[1], fixed_size[0]]
    else:
        min_size = torch.min(im_shape).to(dtype=torch.float32)
        max_size = torch.max(im_shape).to(dtype=torch.float32)
        scale = torch.min(self_min_size / min_size, self_max_size / max_size)

        if torchvision._is_tracing():
            scale_factor = _fake_cast_onnx(scale)
        else:
            scale_factor = scale.item()
        recompute_scale_factor = True

    # Had to add align_corners=True to make the conversion work
    image = torch.nn.functional.interpolate(image[None], size=size, scale_factor=scale_factor, mode='bilinear',
                                            recompute_scale_factor=recompute_scale_factor, align_corners=True)[0]

    if target is None:
        return image, target

    if "masks" in target:
        mask = target["masks"]
        mask = torch.nn.functional.interpolate(mask[:, None].float(), size=size, scale_factor=scale_factor,
                                               recompute_scale_factor=recompute_scale_factor)[:, 0].byte()
        target["masks"] = mask

    return image, target


def resize_boxes(boxes, original_size, new_size):
    # type: (Tensor, List[int], List[int]) -> Tensor
    ratios = [
        torch.tensor(s, dtype=torch.float32, device=boxes.device) /
        torch.tensor(s_orig, dtype=torch.float32, device=boxes.device)
        for s, s_orig in zip(new_size, original_size)
    ]
    ratio_height, ratio_width = ratios
    xmin, ymin, xmax, ymax = boxes.unbind(1)

    xmin = xmin * ratio_width
    xmax = xmax * ratio_width
    ymin = ymin * ratio_height
    ymax = ymax * ratio_height
    return torch.stack((xmin, ymin, xmax, ymax), dim=1)

# Subclass the original GeneralizedRCNNTransform object and overwrite the resize method
class ModifiedRCNNTransform(GeneralizedRCNNTransform):
   """docstring for ModifiedRCNNTransform"""
    def __init__(self, min_size, max_size, image_mean, image_std):
        super(ModifiedRCNNTransform, self).__init__(min_size, max_size, image_mean, image_std)
        
    def resize(self,
               image: Tensor,
               target: Optional[Dict[str, Tensor]] = None,
               ) -> Tuple[Tensor, Optional[Dict[str, Tensor]]]:

        h, w = image.shape[-2:]

        if self.training:
            size = float(self.torch_choice(self.min_size))
        else:
            # FIXME assume for now that testing uses the largest scale
            size = float(self.min_size[-1])
        image, target = _resize_image_and_masks(image, size, float(self.max_size), target, self.fixed_size)
Error 2:
        if target is None:
            return image, target

        bbox = target["boxes"]
        bbox = resize_boxes(bbox, (h, w), image.shape[-2:])
        target["boxes"] = bbox

        if "keypoints" in target:
            keypoints = target["keypoints"]
            keypoints = resize_keypoints(keypoints, (h, w), image.shape[-2:])
            target["keypoints"] = keypoints
        return image, target
```

It is a very janky fix but it works (at least for the Torch -> ONNX -> Tensorflow conversion)

**Error 2:** 
2021-07-21 17:15:33.799749: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: ./saved_models/tf_model
2021-07-21 17:15:33.854208: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2021-07-21 17:15:33.854259: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: ./saved_models/tf_model
2021-07-21 17:15:33.961926: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-07-21 17:15:34.185671: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: ./saved_models/tf_model
2021-07-21 17:15:34.399376: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 599629 microseconds.
2021-07-21 17:15:35.011283: I tensorflow/compiler/mlir/tensorflow/translate/import_model.cc:1856] Unmodelled op type `CropAndResize` is not stateful but will be treated as such conservatively

Exception: <unknown>:0: error: loc(callsite(callsite("onnx_tf_prefix_If_600@__inference___call___7107" at "StatefulPartitionedCall@__inference_signature_wrapper_7170") at "StatefulPartitionedCall")): could not rewrite use of immutable bound input

The way I'm converting the model is very simple:

```
def TensorflowToTFLite(self, tf_path, tflite_path):

        print("Converting from Tensorflow to TFLite")
        # make a converter object from the saved tensorflow file
        print("Initializing TFLite converter")
        converter = tf.lite.TFLiteConverter.from_saved_model(tf_path)

        converter.optimizations = [tf.lite.Optimize.DEFAULT]

        # tell converter which type of optimization techniques to use
        if self.full_quantize:
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
            converter.representative_dataset = self.representative_dataset
            converter.inference_input_type = tf.uint8
            converter.inference_output_type = tf.uint8  

        else:
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                                   tf.lite.OpsSet.SELECT_TF_OPS]
        
        try:
            print("Converting to TFLite model")
            tf_lite_model = converter.convert()

            print("Saving TFLite Model...")
            with open(tflite_path, 'wb') as f:
                f.write(tf_lite_model)

        except Exception as e:
            sys.exit(f"Tensorflow to TFLite conversion failed! Exception: {e}")
```

Regardless of whether or not I am full quantizing, I encounter the error. For the life of me, I could not figure out why this is happening. If anyone could point me in the right direction, that would be great. Here's a [link](https://drive.google.com/drive/folders/1bZ4pGbsEOwmB4fxvUPFpain_NPnV_rmk?usp=sharing) to the models and the MLIR reproducer.

Thanks so much!

**Comment by abattery** [comment]
We recently landed new freezing mechanism in MLIR but it is guarded by flag for now and it gets enabled only with enabling resource variables (converter.experimental_enable_resource_variables = True), we are planning to enable it by default later but after more confidence we think :)

**Comment by alexispascual** [comment]
Hi @abattery , thank you for the response. I don't know what that  just did but somehow the conversion now works. However, invoking the interpreter gives me the following error:

```
RuntimeError: tensorflow/lite/kernels/non_max_suppression.cc:107 (max_output_size_value >= 0) was not true.Node number 5 (NON_MAX_SUPPRESSION_V4) failed to prepare.
Node number 7 (WHILE) failed to prepare.
Node number 9 (WHILE) failed to prepare.
Node number 147 (IF) failed to prepare.
```

Prior to that, there were info messages when allocating the tensors but no errors. Here's how I am invoking the interpreter:

```
def generate_TFLite_result(self,
                               tflite_path):

        interpreter, in_details, out_details = self._initialize_interpreter(tflite_path)

        interpreter.set_tensor(in_details[0]['index'], self._sample_input.numpy())

        print("Invoking interpreter")
        # Error encountered here. Invoke fails.
        interpreter.invoke()

        tflite_result_dict = {key: interpreter.get_tensor(out_details[i]['index']) for i, key in enumerate(self.output_names)}
        tflite_result_dict['name'] = 'TFLite'

        # self.compare_results(tflite_result_dict)
        
    def _initialize_interpreter(self, tflite_path):

        print(f"Using tensorflow {tf.__version__}")
        print("Initializing interpreter...")
        interpreter = tf.lite.Interpreter(model_path=tflite_path)

        print("Allocating tensors...")
        interpreter.allocate_tensors()

        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()

        return interpreter, input_details, output_details
```

I have uploaded the converted TFLite model in the same google drive if that helps.

**Comment by abattery** [comment]
Did you provide the valid input values?

**Comment by alexispascual** [comment]
Hi @abattery,

Yep. I am pretty sure I am. I tried feeding in an image that has range [0., 255.] as well as [0, 1]. I encounter the same error for both times. My thinking was that the converted model might have expected inputs from those ranges, but I guess I am mistaken. I cannot actually feed a uint8 type image because I am not full quantizing the model yet (I tried, but it gave me flex op errors. This will have to be a different issue, I imagine.)

Anyway, I am confident that I am feeding in the right  input because the Tensorflow model is giving me results:

```
{'output_0': <tf.Tensor: shape=(11, 4), dtype=float32, numpy=
array([[ 439.6666  ,  331.39816 ,  613.25104 ,  479.07257 ],
       [   0.      ,  679.2871  ,   29.266216,  712.7054  ],
       [  22.223734,  708.92993 ,   62.30639 ,  719.9272  ],
       [1233.7614  ,    0.      , 1279.9366  ,  212.73343 ],
       [   0.      ,  676.146   ,   54.730453,  712.2286  ],
       [   0.      ,  688.35754 ,    7.232581,  715.50336 ],
       [  16.303509,  715.3977  ,  319.86813 ,  719.9698  ],
       [1229.1129  ,    0.      , 1260.742   ,   12.602079],
       [1260.8397  ,    0.      , 1279.9738  ,    9.131262],
       [1252.0791  ,  274.9876  , 1279.9617  ,  350.96954 ],
       [1251.2029  ,  448.05634 , 1279.9604  ,  494.23047 ]],
      dtype=float32)>, 
'output_1': <tf.Tensor: shape=(11,), dtype=int64, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>, 
'output_2': <tf.Tensor: shape=(11,), dtype=float32, numpy=
array([0.9997458 , 0.36914745, 0.36914745, 0.36914745, 0.36914745,
       0.36914745, 0.36914745, 0.36914745, 0.36914745, 0.36914745,
       0.36914745], dtype=float32)>, 'name': 'Tensorflow'}

```
As a context, `output_0` are bounding boxes, `output_1` are classes, and `output_2` are confidence scores. The first bounding box with 99% confidence is the correct prediction. Hence, I think that the PyTorch -> ONNX -> Tensorflow conversion is successful and I am feeding the correct input.

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/8f0c23a8227df4a45d701b42fb9350ef/50885.ipynb). Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
