### ISSUE TITLE
[Question] TfLiteTensor is supposed to be deleted/released with TfLiteTensorFree?

### ISSUE THREAD

**Issue by CarlosYeverino** [tensorflow/tensorflow#50886]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): from source
- TensorFlow version (use command below): master branch
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**TfLiteTensor is supposed to be deleted/released with TfLiteTensorFree?**
I found the function TfLiteTensorFree and TfLiteTensorReset in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/common.h#L608 ,  however, it is not clarified in the documentation and not seen in examples that TfLiteTensor(s) are supposed to be freed.

**Describe the expected behavior**
Clarify whether TfLiteTensor(s) are supposed to be freed.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by wangtz** [comment]
Hi Carlos,

Normally the TfLite interpreter would take care of tensor's lifecycle. But if you created the tensor yourself (instead of getting the tensor from the interpreter), you can use TfLiteTensorFree to free the field inside TFLite tensor.

Thanks,
Tiezhen

**Comment by CarlosYeverino** [comment]
Hi Tiezhen @wangtz,

thanks for your reply. 

I am using the following arrays of pointers within an Obj structure to pass the input tensor and get the output tensors
```
const TfLiteTensor* tfliteInputTensors[1];
const TfLiteTensor* tfliteOutputTensors[4];
```
Then, I get the tensors from the model using the corresponding TfLiteInterpreterGetInputTensor and TfLiteInterpreterGetOutputTensor APIs
```
pObj->tfliteInputTensors[0] = TfLiteInterpreterGetInputTensor(interpreter, 0);

pObj->tfliteOutputTensors[0] = TfLiteInterpreterGetOutputTensor(interpreter, 0);
pObj->tfliteOutputTensors[1] = TfLiteInterpreterGetOutputTensor(interpreter, 1);
pObj->tfliteOutputTensors[2] = TfLiteInterpreterGetOutputTensor(interpreter, 2);
pObj->tfliteOutputTensors[3] = TfLiteInterpreterGetOutputTensor(interpreter, 3);

```
Since they are arrays of pointers and you mentioned that the TfLite interpreter would take care of the tensor's lifecycle, then there is no need to free the arrays, right?

**Comment by wangtz** [comment]
Yes. Since these tensors were created and managed by the interpreter. You don't need to do deallocate them manually. Also you might want to set pObj->tfliteInputTensors[0] = nullptr after the interpreter is deallocated. Otherwise they may point to invalid memory addresses.
