### ISSUE TITLE
Predict data from a collection to determine a single object with the most used data.

### ISSUE THREAD

**Issue by GlauberF** [tensorflow/tensorflow#50897]
**System information**
- Linux Ubuntu 16.04
- TensorFlow Lite JS

**Description** 
I need to start from a set of objects, define a single object, with the most used data among the javascript object collection informed.

**Example of set of objects:**
```javascript
[{
    name: "Pedro",
    product: "Caneta"
}, {
    name: "Ana",
    product: "Caderno"
}, {
    name: "Maria",
    product: "Boracha"
}, {
    name: "Pedro",
    product: "Caneta"
}, {
    name: "Pedro",
    product: "Caneta"
}]
```

**Single object with the most used values in the above collections:**
```javascript
{
    name: "Pedro",
    product: "Caneta"
}
```

That's what I need, based on the javascript collections array you can see that the most used information for the fields (name and product), were `name: "Pedro"` and `product: "Caneta"`.
That kind of analysis I need.

What function or how could I do this using tensorflow javascript, if you have any examples I'm very grateful, because I'm new to this.

**Comment by tilakrayal** [comment]
@GlauberF ,

In order to expedite the trouble-shooting process, could you please provide the complete code, dataset and tensorflow version to reproduce the issue reported here.Thanks!

**Comment by GlauberF** [comment]
@tilakrayal 
it wouldn't be a problem, I would just like to know how to implement using tensorflow javascript, a solution that solves what I mentioned above.
I know it might not be the right place here, but I'm new around here.
If you have an example with tensorflow javascript that I can use to create the solution I need.

**Comment by wangtz** [comment]
Hi Glauber,

You might want to raise issues in https://github.com/tensorflow/tfjs for TFJS related issues.

Thanks,
Tiezhen
