### ISSUE TITLE
Could not find org.tensorflow:tensorflow-lite-support:0.1.0-rc1

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tensorflow#50896]
Hello everybody :)

I am converting a transformer model for text classification to TFLite. Conversion works. When I integrate it in the Android Studio template for text classification ([https://www.tensorflow.org/lite/examples/text_classification/overview](url)) I use lib_interpreter and obtain the following error:

Execution failed for task ':app:checkInterpreterDebugAarMetadata'.
> Could not resolve all files for configuration ':app:interpreterDebugRuntimeClasspath'.
   > Could not find org.tensorflow:tensorflow-lite-support:0.1.0-rc1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
       - https://repo.maven.apache.org/maven2/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
       - http://oss.sonatype.org/content/repositories/snapshots/org/tensorflow/tensorflow-lite-support/0.1.0-rc1/tensorflow-lite-support-0.1.0-rc1.pom
     Required by:
         project :app > project :lib_interpreter

I would like to know if this is a problem related to the conversion of the model or what is going on here. Thank you very much!

**Comment by abattery** [comment]
Could you file a bug at https://github.com/tensorflow/tflite-support ?

**Comment by yuyecreus** [comment]
Solved in [https://github.com/tensorflow/tflite-support/issues/616](url)
