### ISSUE TITLE
converting tensorflow model to mlir

### ISSUE THREAD

**Issue by ArunaKote** [tensorflow/tensorflow#50890]
I saved tf model using model.save().Then I tried to convert it to mlir using tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --graphdef-to-mlir /data/aruna/tf_models/saved_model.pb -o /data/aruna/tf_models/convolution.mlir  but I am getting error as  tensorflow/compiler/mlir/tensorflow/translate/tf_mlir_translate.cc:163] SavedModel import failed: Failed precondition: Could not restore saved variable: Adam/conv2d/kernel/m
Am I giving correct flag to convert tf to mlir?

**Comment by tilakrayal** [comment]
@ArunaKote ,

Please  take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/31501) with similar error.Also  this is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) or tensorflow discussion [forum](https://discuss.tensorflow.org/). There is a larger community that reads questions there. Thanks!
