### ISSUE TITLE
LSTM's forget gate biases

### ISSUE THREAD

**Issue by giancds** [tensorflow/tensorflow#5090]
Hi all,

I was looking into the LSTMCell code and I got confused:

[Line 505](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L505) show us the computations of new input and the gates: input, forget and output.

Both [line 517](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L517) and [line 520](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L517) show the addition of the forget gate (which is a scalar in this particular piece of code).

I got confused by this addition as it seems to be already done when we split the gate's values  in line 505 as mentioned before. Am I missing something or is this a second addition to the forget gate computations? If it is a second addition, wouldn't that change the computations?

By the way, that bias shouldn't be a vector instead of a single scalar?

Sorry if I am saying nonsense. but I'd like to double check that before saying it is a bug.

**Comment by asimshankar** [comment]
@ebrevdo : Any insights?

**Comment by ebrevdo** [comment]
Those lines don't both get executed.  Only one of them does.  It depends on you enable using peepholes or not.  Finally, this forget_bias is added via broadcasting (so it's ok for it to be a scalar).  The "true" bias is added at line 504, via tf.bias_add.
