### ISSUE TITLE
loading a keras model on raspberry pi

### ISSUE THREAD

**Issue by karimanis** [tensorflow/tensorflow#50915]
```
Traceback (most recent call last):
  File "/home/pi/Desktop/testting/client.py", line 21, in <module>
    modelLSTM = load_model('/home/pi/Desktop/ANN_model.keras')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 263, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 234, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional
```

> I get this error when running a client code from the socket communication module. The role of the client is to receive inputs from the server code in a NumPy array format fed to a saved Keras model where I saved first on my laptop and transferred to my raspberry pi. so a brief:

`import tensorflow as tf
from random import randint
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Activation, Dense, Input
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Nadam, Ftrl
from tensorflow.keras.metrics import categorical_crossentropy, mean_squared_error
from tensorflow.keras.models import model_from_json
import pandas as pd
import numpy as np
import xlrd
import matplotlib.pyplot as plt
import openpyxl
from math import sqrt
import sklearn

train_inputs = []
train_outputs = []
test_inputs = []
test_outputs = []
test_time = []

train_inputs = np.array(train_inputs)
train_outputs = np.array(train_outputs)
test_inputs = np.array(test_inputs)
test_outputs = np.array(test_outputs)
test_time = np.array(test_time)

output = pd.read_excel(r'K:\BachelorThesis\Data\Training_data\Mix_Data_outputs.xlsx')
train_outputs = output.to_numpy()
#print(type(train_outputs[-1][0]))

input = pd.read_excel(r'K:\BachelorThesis\Data\Training_data\Mix_Data_inputs.xlsx')
train_inputs = input.to_numpy()
#print(type(train_inputs[-1][0]))

temp_output = pd.read_excel(r'K:\BachelorThesis\Data\TestingData\Mix_Data_outputs.xlsx')
test_outputs = temp_output.to_numpy()
#print(type(train_outputs[-1][0]))

temp_input = pd.read_excel(r'K:\BachelorThesis\Data\TestingData\Mix_Data_inputs.xlsx')
test_inputs = temp_input.to_numpy()
#print(type(train_inputs[-1][0]))

time = pd.read_excel(r'K:\BachelorThesis\Data\TestingData\Nuneaton_RDE_Track\DataNuneaton_time.xlsx')
test_time = time.to_numpy()

scaler_i = MinMaxScaler()
scaler_o = MinMaxScaler()
scaler_i.fit(train_inputs)
normalized_inputs = scaler_i.transform(train_inputs)
scaler_o.fit(train_outputs)
normalized_outputs = scaler_o.transform(train_outputs)

tf.random.set_seed(16)

layer1 = Input(shape = (8, ))
layer2 = Dense(2048, activation='tanh')(layer1)
layer3 = Dense(1024, activation='tanh')(layer2)
layer4 = Dense(512, activation='tanh')(layer3)
layer5 = Dense(512, activation='tanh')(layer4)
layer6 = Dense(256, activation='tanh')(layer5)
layer7 = Dense(256, activation='tanh')(layer6)
layer8 = Dense(512, activation='tanh')(layer7)
layer9 = Dense(512, activation='tanh')(layer8)
layer10 = Dense(1024, activation='tanh')(layer9)
layer11 = Dense(2048, activation='tanh')(layer10)
output = Dense(8, )(layer11)
model = Model(inputs = layer1, outputs = output)

model.compile(optimizer=Adam(learning_rate=0.0001), loss='mse', metrics=['mean_squared_error'])

history = model.fit(x=normalized_inputs, y=normalized_outputs, validation_split=0.3, epochs=30, verbose=2)#, batch_size = 400, validation_batch_size= 100)

history.history.keys()

plt.plot(history.history['loss'])
plt.plot(history.history['mean_squared_error'])
plt.title('training')
plt.ylabel('loss & mse')
plt.xlabel('epochs')
plt.legend(['loss','mse'],loc='upper left')
plt.show()

plt.plot(history.history['val_loss'])
plt.plot(history.history['val_mean_squared_error'])
plt.title('validation')
plt.ylabel('val_loss & val_mse')
plt.xlabel('epochs')
plt.legend(['val_loss','val_mse'],loc='upper left')
plt.show()

scaler_ti = MinMaxScaler()
scaler_to = MinMaxScaler()
scaler_ti.fit(test_inputs)
normalized_test_inputs = scaler_ti.transform(test_inputs)
scaler_to.fit(test_outputs)
normalized_test_outputs = scaler_to.transform(test_outputs)

model.evaluate(normalized_test_inputs, normalized_test_outputs)

prediction = model.predict(normalized_test_inputs)
inverse = scaler_to.inverse_transform(prediction)

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,0])
ax.plot(test_time, test_outputs[:,0], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,1])
ax.plot(test_time, test_outputs[:,1], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,2])
ax.plot(test_time, test_outputs[:,2], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,3])
ax.plot(test_time, test_outputs[:,3], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,4])
ax.plot(test_time, test_outputs[:,4], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,5])
ax.plot(test_time, test_outputs[:,5], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,6])
ax.plot(test_time, test_outputs[:,6], linestyle = 'dashed')
plt.show()

fig, ax = plt.subplots(figsize=(30,10))
ax.plot(test_time, inverse[:,7])
ax.plot(test_time, test_outputs[:,7], linestyle = 'dashed')
plt.show()

model.save('K:\BachelorThesis\code testing\TireForces.LSTM\ANN_model.keras')

#model_json = model.to_json()
#with open("K:\BachelorThesis\code testing\tireForcesANN/modelANN.json", "w") as json_file:
 #   json_file.write(model_json)
# serialize weights to HDF5
#model.save_weights("K:\BachelorThesis\code testing\tireForcesANN/modelANN.h5")
#print("Saved model to disk")`

> This code on my laptop was used to train a model and save it in my laptop then the saved model was transferred using WinSCP to my raspberry pi.

`import socket
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import MinMaxScaler

scaler_ti = MinMaxScaler()
test_inputs = []
test_inputs = np.array(test_inputs)
temp_in = pd.read_excel(r'K:\BachelorThesis\Data\TestingData\Mix_Data_inputs.xlsx')
test_inputs = temp_in.to_numpy()
rows = test_inputs.shape[0]
scaler_ti.fit(test_inputs)
normalized_test_inputs = scaler_ti.transform(test_inputs)

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = ''
port = 62402
s.bind((host,port))
s.listen(5)

while True:
    
    clientsocket, address = s.accept()
    print(f"connection from {address} has been established!")
    strg = test_inputs
    temp = strg.tobytes()
    clientsocket.send(temp)
    clientsocket.close()
        

`

> This code is the server code on my laptop to feed the client code with the inputs.

`import socket
import numpy as np
#import pandas as pd
#import sklearn
#from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import load_model
import tensorflow as tf
from random import randint
import h5py
#import argparse

#ap = argparse.ArgumentParser()
#ap.add_argument("-d", "--dataset", required=True,
	#help="path to input dataset")
#ap.add_argument("-m", "--LSTM_model.h5", required=True, help="/home/pi/Desktop")
#args = vars(ap.parse_args())

i = 0
final = []
final = np.array(final)
modelLSTM = load_model('/home/pi/Desktop/ANN_model.keras')
#json_file = open('LSTM_model.json', 'r')
#loaded_model_json = json_file.read()
#json_file.close()
#loaded_model = model_from_json(loaded_model_json)

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = '192.168.1.24'
port = 62402
s.connect((host, port))

while True:
    if i in range(65533):
        i = i + 1
        msg = s.recv(64)
        out = np.frombuffer(msg)
        #out = out.reshape(1,8)
        #out = out.reshape(1,1,8)
        #prediction = modelLSTM.predict(out)
        #inverse = scaler_ti.inverse_transform(prediction.reshape(1,8))
        #print(prediction)
        #print(inverse)
        #final = np.vstack(inverse) 
        print(out)
        if len(msg) <= 0:
            break
#print (final)

`

> This code is the client code on my raspberry pi where I get the error every time I run.

**Comment by UsharaniPagadala** [comment]
@karimanis 

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by jvishnuvardhan** [comment]
@karimanis Code is too long to debug. Any (TF/Keras) model needs to be converted to TFlite model to run on Raspberry Pi. Did you convert the model? 

Please check the instructions here https://www.tensorflow.org/lite/tutorials
