### ISSUE TITLE
Are these two lines of code okay? It may cause compilation errors

### ISSUE THREAD

**Issue by jasonjx-w** [tensorflow/tensorflow#50919]
https://github.com/tensorflow/tensorflow/blob/b61c987109eaad755c2b36ba51a0b233d54d4e57/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/fusion_utils.cc#L203
https://github.com/tensorflow/tensorflow/blob/b61c987109eaad755c2b36ba51a0b233d54d4e57/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/fusion_utils.cc#L204
@wyzero 

tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/fusion_utils.cc:203:27: error: 'class mlir::Operation' has no member named 'region'
   for (Operation& op : op.region().getBlocks().front()) {

**Comment by tilakrayal** [comment]
@jasonjx-w ,

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled and also the tensorflow version you are using, could you please do so as it helps us analyse the issue.Thanks!

**Comment by crischeng** [comment]
![image](https://user-images.githubusercontent.com/27774893/154609381-53c1732f-7d12-4665-9a28-dc1f4a6e76e2.png)
I have the same problem when i use GCC 5.4.0. Maybe use GCC 7.3.1 can solve this problem.

**Comment by j1anx** [comment]
@crischeng thx！
