### ISSUE TITLE
SECURITY.md

### ISSUE THREAD

**Issue by Apidwalin** [tensorflow/tensorflow#50922]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**
[SECURITY.md](https://github.com/tensorflow/tensorflow/files/6868801/SECURITY.md)

**Any Other info.**

**Comment by tilakrayal** [comment]
@Apidwalin ,

Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by mihaimaruseac** [comment]
This is spam
