### ISSUE TITLE
Error in saving model: TypeError: No conversion path for dtype: dtype('<U30')

### ISSUE THREAD

**Issue by thebinyang** [tensorflow/tensorflow#50925]
<em>I am building a new model based an existed model. However, I found that I could not save the new model</em>

**Important Notice**

I have an existed model which was built based on VGG16 (namely, 'base_network' in the following picture). Now, I am building a new model based on the existed model (namely, 'model' in the following picture). However, the existed model could be saved using the keras.models.save, but the new model could not.

For simplicity, the code is as follows,

<img width="414" alt="微信截图_20210723233351" src="https://user-images.githubusercontent.com/24711658/126806731-1f1828be-fcf2-4d0d-bc18-1ec57be44189.png">

As you can see, the first base_network.save('out.h5') works. the base_network can be saved. However, when it comes to model.save('out2.h5'), problems occur.

I do not know why. the base_network and model looks the same in these codes. Could anyone help me? thanks.

<img width="688" alt="20210723234456" src="https://user-images.githubusercontent.com/24711658/126807518-c2160c9e-47f7-42a0-976c-afad5ac294ff.png">

Here, I also uploaded the summary information.
<img width="618" alt="20210723234641" src="https://user-images.githubusercontent.com/24711658/126807803-5b111478-2d82-4349-8fe4-e8bf3a2a11a3.png">
<img width="588" alt="20210723234659" src="https://user-images.githubusercontent.com/24711658/126807810-74a744bc-e363-4c64-939b-4ca167ff4852.png">

**Comment by thebinyang** [comment]
problems solved when I built a new environment. Looks like it is caused by the environment.

**Comment by gowthamkpr** [comment]
Yes, make sure you use a clean environment as saving become tricky and you can run into these errors which are hard to debug
