### ISSUE TITLE
validation_split for tensorflow.dataset

### ISSUE THREAD

**Issue by old-school-kid** [tensorflow/tensorflow#50937]
ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>]

I believe there is explicitly no support to divide a tensorflow dataset  into train and validation on the go while calling model.fit. Would be really helpful if this feature can be added.
**System information**
- TensorFlow version (you are using): 2.5
- Are you willing to contribute it (Yes/No): Yes

**Comment by tilakrayal** [comment]
@old-school-kid ,

Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by old-school-kid** [comment]
@tilakrayal 
The error I am speaking about can be found in this [notebook](https://colab.research.google.com/drive/1BySKPLDhoBGN5Sby-_klwuESr61Qu4dF?usp=sharing)

So what I wanted was to split the dataset on the go while training.

**Comment by rmothukuru** [comment]
@old-school-kid,
Validation Split can be obtained using the code shown below:

**`test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 15, 75])`**

Please refer in [this comment](https://github.com/tensorflow/datasets/issues/291#issuecomment-474668134) and the [respective Tensorflow Documentation](https://www.tensorflow.org/datasets/splits) for more information.

**Comment by old-school-kid** [comment]
@rmothukuru 
I believe you meant `ds1, ds2 = tfds.load(..., split=[ 'train[:50%]', 'train[50%:]'])` as mentioned [in this issue](https://github.com/tensorflow/datasets/issues/1998#issuecomment-625293235). 
Also I guess this support is only present for datasets present in tensorflow_datsets. If there is a way around for custom dataset please let me know how to split since the arguments in both the Slicing APIs [as mentioned in the document](https://www.tensorflow.org/datasets/splits) require the dataset to be present in tensorflow_dataset.

**Comment by aaudiber** [comment]
@rmothukuru `mode.fit(..., validation_split=...)` is a Keras API, so this would be better routed to the Keras team.

**Comment by old-school-kid** [comment]
@aaudiber @rmothukuru 
So do I need to close this issue here and head over to the keras repository. But also isn't the issue with tensorflow.data.dataset?

**Comment by aaudiber** [comment]
@old-school-kid 
It makes sense for this issue to stay here -- `tf.keras` is a part of this repo: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras

`tf.data.Dataset`s aren't randomly accessible, so there isn't an efficient way to split a dataset into train/eval datasets. Instead, users need to decide what data should be part of the train dataset and which should be part of the eval dataset.

**Comment by jvishnuvardhan** [comment]
@old-school-kid The [TF doc](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit) clearly mentions that it is not supported when x is a dataset

> This argument is not supported when x is a dataset, generator or keras.utils.Sequence instance. validation_split is not yet supported with tf.distribute.experimental.ParameterServerStrategy.

If you still need this feature, open the issue as a feature in keras-team/keras repo as Keras development moved there to focus entirely on Keras.

Keras development moved to another repository to focus on only keras. Could you please repost this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)

**Comment by old-school-kid** [comment]
@jvishnuvardhan I suppose for the time being I have to go with @aaudiber and decide train and test split beforehand. So I guess I will close the issue.
Thank you.

**Comment by vivekbhargava23** [comment]
Is the issue resolved?

**Comment by Reginaekwere** [comment]
> Is the issue resolved?

No
