### ISSUE TITLE
Problems on TensorFlow-ROCm installation

### ISSUE THREAD

**Issue by Photonico** [tensorflow/tensorflow#50944]
Hi,

My PC has AMD CPU(Ryzen 5900X) and an AMD graphic card(RX6800XT). The operating system is openSUSE Tumbleweed(20210726). I want to use my GPU to do some scientific computation by tensorflow-rocm. 

I add the repository resource via: `sudo zypper addrepo --no-gpgcheck http://repo.radeon.com/rocm/zyp/zypper/ rocm`
But I don't know which are the necessary packages for the ROCm.
And I find that:

Some packages can be installed directly.
`rock-dkms`
`rocm-gdb`: requires me to install python36 (My OS has python38 installed)
`rocminfo`
`rocm-opencl`
`rocm-opencl-devel`
`rocm-device-libs`
`hsakmt-roct`
`hipify-clang`
...

Some packages cannot be installed with dependencies problems.
`rocm-dkms` 
`rocm-dev`
`rccl`
`rocm-libs`
`hip-samples`
...

I'm new to computational science, could you tell me the minimal installation of ROCm environment(Could let me use tensorflow-rocm) requires me to install which packages from the [official repo](http://repo.radeon.com/rocm/zyp/zypper/)?
I just want to use [tensorflow-rocm](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream).

I would appreciate it if you can respond to me.

**Comment by Saduf2019** [comment]
@Photonico 
Please refer to [this link ](https://medium.com/analytics-vidhya/install-tensorflow-2-for-amd-gpus-87e8d7aeb812)and let us know.

**Comment by Photonico** [comment]
> @Photonico
> Please refer to [this link ](https://medium.com/analytics-vidhya/install-tensorflow-2-for-amd-gpus-87e8d7aeb812)and let us know.

Thanks a lot for your reply. I have installed ROCm.
However, ROCm current version 4.2 does not support my graphic card: RX6800XT(gfx 1030). 
I need to wait for the ROCm 4.3 released.

**Comment by Saduf2019** [comment]
@Photonico 
Can we please move this to closed status and open in case you face any issues after release.

**Comment by Photonico** [comment]
> Can we please move this to closed status and open in case you face any issues after release.

of course
