### ISSUE TITLE
Build TensorFlowLite C API with GPU delegate with CMake

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#50940]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: nightly
- Python version: 3.6
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): N/A, using CMake 3.20
- GCC/Compiler version (if compiling from source): GCC 8.2
- CUDA/cuDNN version: CUDA 11.1, cuDNN 8
- GPU model and memory: GTX 1650

**Describe the problem**
I am trying to build the C API for Tensorflow Lite, with GPU delegate enabled, and using CMake. The resulting `libtensorflowlite_c.so` does not have GPU delegate symbols.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I basically followed https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library . With the only difference that I added `-DTFLITE_ENABLE_GPU=ON` in the CMake config step. From what I gathered from `tensorflow/lite/c/CMakeLists.txt`, we build `libtensorflow-lite.a` (C++ API, static) first, and bake this into `libtensorflowlite_c.so`. The GPU delegate symbols can be found inside `libtensorflow-lite.a`, but are stripped away from `libtensorflowlite_c.so`. I found a workaround which consists of changing:
```
target_link_libraries(tensorflowlite_c
  tensorflow-lite
)
```
to
```
target_link_libraries(tensorflowlite_c
  -Wl,--whole-archive
  tensorflow-lite
  -Wl,--no-whole-archive
)
```
inside `tensorflow/lite/c/CMakeLists.txt` and removing `${TFLITE_C_SRCS}` from the list of source files associated to the `tensorflow-lite` target inside `tensorflow/lite/CMakeLists.txt`. This latter step is necessary because both `tensorflowlite_c` and `tensorflow-lite` targets include this same set of source files and will lead to a linker multiple-definition error.

Is there better way to achieve this without having to patch the CMake files on my end? Can we add better support for delegates for the CMake workflow?

**Comment by terryheo** [comment]
That change makes sense to me. Could you provide a PR?

BTW, did you verify the GPU delegate works well with C API?

**Comment by DwayneDuane** [comment]
Hi @terryheo , sorry for taking so long. I got sidetracked onto another project and was only able to return to this recently. So basically I can confirm that with GPU delegate does work with C API on NVidia GPUs if I build using CMake with the aforementioned changes. Also, I was able to build for Android after making one additional modification to `tensorflow/lite/CMakeLists.txt` in order to exclude `minimal_logging_default.cc` from the list of source files to build. Otherwise, on Android, it will attempt to compile both `minimal_logging_default.cc` and `minimal_logging_android.cc` and link them to produce a multiple definition error.

Before I make a PR for these fixes, I noticed a crash on exit bug in the latest master and nightly branches:
https://github.com/tensorflow/tensorflow/issues/51751

I was only able to get everything successfully building and running on the v2.6.0 tag.

**Comment by tonysung** [comment]
[This problem](https://github.com/tensorflow/tensorflow/issues/50940#issuecomment-908498923) is still unfixed:

> Also, I was able to build for Android after making one additional modification to tensorflow/lite/CMakeLists.txt in order to exclude minimal_logging_default.cc from the list of source files to build. Otherwise, on Android, it will attempt to compile both minimal_logging_default.cc and minimal_logging_android.cc and link them to produce a multiple definition error.
>
> Before I make a PR for these fixes, I noticed a crash on exit bug in the latest master and nightly branches:
https://github.com/tensorflow/tensorflow/issues/51751

**Comment by fergushenderson** [comment]
The issue mentioned in #issuecomment-1078904109 seems to have been fixed in https://github.com/tensorflow/tensorflow/commit/1b67c2dd5f4cbf854bf4914dde942d8a18a74211
back in March 2023.

**Comment by fergushenderson** [comment]
Terry Heo wrote:

> That change makes sense to me. Could you provide a PR?

I have some concerns with that plan.  See <https://github.com/tensorflow/tensorflow/pull/77352#pullrequestreview-2451219412> and subsequent comments on that issue.
