### ISSUE TITLE
Where is convert_all_kernels_in_model in tensorflow 2.5.0?

### ISSUE THREAD

**Issue by chudur-budur** [tensorflow/tensorflow#50941]
I can't import `convert_all_kernels_in_model` from `tensorflow.keras.utils` in `tf 2.5.0`

```python
from tensorflow.keras.utils import convert_all_kernels_in_model
```

I get this error:

```bash
ImportError: cannot import name 'convert_all_kernels_in_model' from 'tensorflow.keras.utils' ...
```

I have an old code written in `tf 2.3.0` and I need to port it to `tf 2.5.0`.  

Where did that function go?

**Comment by tilakrayal** [comment]
@chudur-budur ,

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
