### ISSUE TITLE
Unexpected warning when using tf.data.Dataset.cache(filename)

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/tensorflow#50952]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0 and 2.7.0.dev20210725
- Python version: 3.9.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v1.12.1-60944-g65153d2677e 2.7.0-dev20210725

**Describe the current behavior**
When tf.data.Dataset is cached into a file there is a warning
```
W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```
Eventhough dataset is fully read.

**Describe the expected behavior**
There should be no warning when dataset is fully read.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import os
import tensorflow as tf

os.system('rm -f /tmp/foo*')

def gen():
    for i in range(5):
        yield i

dataset = tf.data.Dataset.from_generator(gen, output_signature=tf.TensorSpec(shape=(), dtype=tf.int32))
dataset = dataset.cache('/tmp/foo')
# dataset = dataset.take(3).cache('/tmp/foo').repeat(2)

for x in dataset:
    print(x)
```

Even if `take.cache.repeat` is used just like the warning suggests, it doesn't help

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Output of the script above:
```
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
2021-07-26 13:35:10.940312: W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
```

Running this script under `strace` shows that a shard file is removed just before it's existence is checked:
```
[pid   910] stat("/tmp/foo_0.index", {st_mode=S_IFREG|0644, st_size=201, ...}) = 0
[pid   910] openat(AT_FDCWD, "/tmp/foo_0.index", O_RDONLY) = 4
[pid   910] pread64(4, "y\10\206\1\16\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 48, 153) = 48
[pid   910] pread64(4, "\0\1\2!\0t\0\0\0\0\1\0\0\0\0t\214P\20", 19, 134) = 19
[pid   910] pread64(4, "\0\0\6\10\1\32\2\10\1\0\t\v      0_0\10\3\22\0(\0045\246{\21:"..., 121, 0) = 121
[pid   910] close(4)                    = 0
[pid   910] rename("/tmp/foo_0.data-00000-of-00001", "/tmp/foo.data-00000-of-00001") = 0
[pid   910] openat(AT_FDCWD, "/tmp/foo.index", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
[pid   910] fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
[pid   910] write(4, "\0\0\6\10\1\32\2\10\1\0\t\v      0_0\10\3\22\0(\0045\246{\21:"..., 201) = 201
[pid   910] close(4)                    = 0
[pid   910] unlink("/tmp/foo_0.index")  = 0
[pid   910] unlink("/tmp/foo_0.lockfile") = 0
[pid   910] access("/tmp/foo.index", F_OK) = 0
[pid   910] access("/tmp/foo_0.index", F_OK) = -1 ENOENT (No such file or directory)
[pid   910] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
[pid   910] write(2, "2021-07-26 13:17:56.497443: W te"..., 4242021-07-26 13:17:56.497443: W tensorflow/core/kernels/data/cache_dataset_ops.cc:233] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
) = 424
```

**Comment by tilakrayal** [comment]
@0x0badc0de ,

Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/44801#issuecomment-727712745) and [link](https://stackoverflow.com/questions/64305438/warning-the-calling-iterator-did-not-fully-read-the-dataset-being-cached-in-or) with similar error.It helps.Thanks!

**Comment by 0x0badc0de** [comment]
@tilakrayal could you elaborate how this helps? I'm not following. Setting CUDA_LAUNCH_BLOCKING=1 changes nothing in this case. And SO answer on one hand mentions RAM cache (but the warning comes from FS cache). On another hands it mentions no warnings in Google Colab. But they still exist - https://stackoverflow.com/a/53353891

So the snippet has to be modified:
```
!pip install wurlitzer

import os
import tensorflow as tf
from wurlitzer import pipes

os.system('rm -f /tmp/foo*')

def gen():
    for i in range(5):
        yield i

dataset = tf.data.Dataset.from_generator(gen, output_signature=tf.TensorSpec(shape=(), dtype=tf.int32))
dataset = dataset.cache('/tmp/foo')
# dataset = dataset.take(3).cache('/tmp/foo').repeat(2)

with pipes() as (out, err):
    for x in dataset:
        print(x)

print(out.read())
print(err.read())
```

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.5 and nightly, in v2.4 i was able to execute the code without any warning.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/be9cde87e4572e7298359ac59870d0bf/untitled50952.ipynb).

**Comment by saswatac** [comment]
the same behaviour is also seen in tf 2.6

**Comment by mark-r-anderson** [comment]
Can confirm that I still experience this behaviour in all versions of TensorFlow I have tried after 2.4 (including 2.5, 2.8, and most recently 2.11). Have there been any updates on this at all? Or is there an easy fix or way to disable this warning?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
