### ISSUE TITLE
Identifying the type of input 

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#50953]
Creating a generalized application that can accept both sequence inputs and non-sequence inputs.
To check whether its sequence input or non-sequence input, have written c++ API to get this information.

Need confirmation regarding checking whether it's RNN input or not? 
`    int t_size1 = this->interpreter->tensors_size();
    for (int i = 0; i < t_size1; i++) {
        if (this->interpreter->tensor(i)->name != nullptr) {
            if ((std::string(this->interpreter->tensor(i)->name)
                     .compare("tfl.unidirectional_sequence_lstm") == 0) ||
                (std::string(this->interpreter->tensor(i)->name).compare("tfl.lstm") == 0) ||
                (std::string(this->interpreter->tensor(i)->name).compare("tfl.basic_lstm") == 0) ||
                (std::string(this->interpreter->tensor(i)->name)
                     .compare("tfl.unidirectional_sequence_rnn ") == 0)) {
                *isRNNType = true;
                break;
            }
        }
    }`

**Comment by pranathibl** [comment]
Using TensorFlow 2.4.1, Does the above-written code valid for all kind of models and differentiate RNN and non RNN models ?
Does this work for all type of Models FP32, Quant(uint8, int8 and Fp16)
Is there an API to check if its sequence input or non-sequence inputs? If there, provide the API .

**Comment by renjie-liu** [comment]
Sorry I'm confused about the question, what problem did you get?

**Comment by pranathibl** [comment]
I need to get information on whether the Model accepts sequence input (RNN) or non-sequence input.

I have a TFLite Model. I want to detect whether the model is sequence type or not.

For that I have written code to identify, If its non-sequence, N,H,W,C is the data format. If its sequence, N, S,C is the order .

Is there an API to identify the type of model

**Comment by pjpratik** [comment]
Hi @pranathibl 

The type of input can be identified using the input shape and input details provided by interpreter using `get_input_details()` functionality.

```
A list in which each item is a dictionary with details about an input tensor. Each dictionary contains the following fields that describe the tensor:
name: The tensor name.
index: The tensor index in the interpreter.
shape: The shape of the tensor.
shape_signature: Same as shape for models with known/fixed shapes. If any dimension sizes are unknown, they are indicated with -1.

dtype: The numpy data type (such as np.int32 or np.uint8).

quantization: Deprecated, use quantization_parameters. This field only works for per-tensor quantization, whereas quantization_parameters works in all cases.

quantization_parameters: A dictionary of parameters used to quantize the tensor: ~ scales: List of scales (one if per-tensor quantization). ~ zero_points: List of zero_points (one if per-tensor quantization). ~ quantized_dimension: Specifies the dimension of per-axis quantization, in the case of multiple scales/zero_points.

sparsity_parameters: A dictionary of parameters used to encode a sparse tensor. This is empty if the tensor is dense.
```
Thanks.
