### ISSUE TITLE
Error in build phase (iOS and Android sample)

### ISSUE THREAD

**Issue by fabiodimicco** [tensorflow/tensorflow#5095]
Hi, 
   I followed all the instructions to build the iOS sample app but I encountered many errors like this: 

```
./tensorflow/core/framework/types.h:112:48: error: unknown type name 'DataType'
inline bool TypesCompatible(DataType expected, DataType actual) {
                                               ^
./tensorflow/core/framework/types.h:142:11: error: unknown type name 'DataType'
template <DataType VALUE>
```

and all in the same file: **types.h**

I dind't found anything on the web (or Stackoverflow) about these errors. 
### Environment info

Operating System: MacOS Sierra version 10.12 (16A323)

I used Docker quickstart terminal to run tensorflow and build the apps. 
Also with the Android sample app I have the same issues. 

I followed also this [blog](https://petewarden.com/2016/02/28/tensorflow-for-poets/) and all the instruction here in the github project, but I receive the same errors also opening the project with xCode Version 8.0 (8A218a). 

Could you please help me to understand how to solve the problem with the DataType? 

Thanks
Fabio

**Comment by asimshankar** [comment]
@fabiodimicco : Which instructions did you follow for iOS? Have you seen this: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#ios

**Comment by fabiodimicco** [comment]
Yes I tried exactly all these steps and during the compiling phase I receive 20 errors about the DataType (error: unknown type name 'DataType'). 

I tried with the build_all_ios.sh and also with the separated steps (download_dependencies.sh, compile_ios_protobuf.sh and compile_ios_tensorflow.sh).

**Comment by asimshankar** [comment]
Hmm...`DataType` is defined in `types.pb.h`, which is generated from the .proto file. Your issue might possibly be related to #4997 

@petewarden might have some thoughts on this.

**Comment by fabiodimicco** [comment]
yes...this is the problem. the file `types.pb.h` is not generated :( 

I tried also the solution by @petewarden, but I have already installed the libtool using this line od code `brew install libtool`. 

Do you have any suggestions to create this file? I noticed now that also the file `resource_handle.pb.h` is not generated.

**Comment by fabiodimicco** [comment]
Hi @petewarden 
  I discovered that the issue happens only on MacOS Sierra because I have tried with El Capitan and everything is working fine. 

Do you think this issue can been solved also for MacOS Sierra?

**Comment by KevinAyuque** [comment]
I'm also having the same problem on MacOS Sierra and Xcode 8. Help please!

**Comment by aselle** [comment]
This issue is quite old by now, MacOS has been used for awhile now. Be sure to try the latest build instructions on the latest version of TensorFlow, and please create a new bug if it is still not working. Thanks.
