### ISSUE TITLE
Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#50959]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.6.13
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 8.1
- GPU model and memory: RTX 2080 Ti

**Describe the current behavior**
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("Placeholder_1:0", shape=(None, 2), dtype=int64), values=Tensor("Placeholder:0", shape=(None,), dtype=float32), dense_shape=Tensor("PlaceholderWithDefault:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.

**Describe the expected behavior**
The same results as dense tensor.

We encounter this issue when we try to use sparse tensors in keras. We checked ReLU and BatchNormalization layer and we met this error. From the document "Working with sparse tensors", "The tf.keras API natively supports sparse tensors without any expensive casting or conversion ops". But we found a similar issue 25980 which meets a similar error but it's about dropout layer. I checked dropout layer and confirmed it is fixed in tf2.5, but other layers may still have bugs.

So my question is, is it safe to assume all tf.keras apis work with sparse tensors?

**Standalone code to reproduce the issue**
import tensorflow as tf
input = tf.keras.layers.Input(shape=(4), sparse=True)
output = tf.keras.layers.ReLU()(input)
\# output = tf.keras.layers.BatchNormalization()(input)
model = tf.keras.Model(inputs=[input], outputs=[output])
print(model(np.array([[1, 0, 1, 0]])))

**Comment by tilakrayal** [comment]
@jiannanWang ,

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by jiannanWang** [comment]
Thank you for your reply! I have created a new issue in keras-team/keras: https://github.com/keras-team/keras/issues/15009. Closing this issue.
