### ISSUE TITLE
Reading TFRecords from S3 with a window shift leads to a large performance degradation

### ISSUE THREAD

**Issue by BogdanRuzh** [tensorflow/tensorflow#50956]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): tried both types
- TensorFlow version (use command below): 2.4.2
- Python version: 3.8.0
- Bazel version (if compiling from source): 4.1.0
- GCC/Compiler version (if compiling from source): 7.5.0

**Describe the current behavior**
I have a list of filenames of TFRecords that are stored on S3. Each TFRecord contains a list of frames stored in a type: `tf.io.FixedLenFeature((), tf.string)`. If I want to select every 100th frame from a TFRecord, TFRecordDataset downloads the whole file and then select required frames. 

I'm running p3dn.24xlarge that have 100Gb network bandwidth (EC2 and S3 on the same region + VPC).

`iftop` shows average bandwidth around 20Gb and 25 threads (probably, because of this hard limitation: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L69 )

Increasing `num_parallel_calls` don't have any affect.

```python
dl = tf.data.TFRecordDataset.from_tensor_slices(filenames)
dl = dl.interleave(
    lambda y: tf.data.TFRecordDataset(y).window(size=1, shift=100, stride=5, drop_remainder=True).flat_map(lambda x: x.batch(1)), 
num_parallel_calls=10)

```
**Describe the expected behavior**
I would've expect any of the two following cases:
* TFRecordDataset downloads only selected frames
* TFRecordDataset scales up to 100Gb of network bandwidth

**Comment by Saduf2019** [comment]
@BogdanRuzh 
Code provided is not sufficient to replicate th eissue faced, Can you replicate the issue in colab gist and share for us to analyse.
