### ISSUE TITLE
Cannot run  "bazel build tensorflow/examples/image_retraining:retrain"

### ISSUE THREAD

**Issue by deeptigp** [tensorflow/tensorflow#5096]
Hi,

I've been having issues in building the [image retraining](https://www.tensorflow.org/versions/r0.11/how_tos/image_retraining/index.html#training-on-flowers) example. When I run bazel build tensorflow/examples/image_retraining:retrain I get the following error:

ERROR: $TF_HOME/tensorflow/core/BUILD:991:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate  "bazel-out/host/genfiles/tensorflow/core/util/version_info.cc"': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 221, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 152, in generate
    spec, head_symlink, _, dest_file = arglist
ValueError: need more than 1 value to unpack
Target //tensorflow/examples/image_retraining:retrain failed to build

The file gen_git_source.py exists but the file "bazel-out/host/genfiles/tensorflow/core/util/version_info.cc" does not seem to exist. 

Could this be happening because the generate() method inside gen_git_source expects multiple arguments which are not being provided?

## **Environment info**

Debian 4.6.4-1

## **What other attempted solutions have you tried?**

If I comment out the line 991 in core/BUILD, that doesn't help either. It gives an array of other errors.

I found another related error: https://github.com/tensorflow/tensorflow/issues/4701

**Comment by asimshankar** [comment]
@deeptigp : I'm unable to reproduce, but perhaps you can provide some more information. Please try the following when you get a chance:

```sh
bazel build -s //tensorflow/core:version_info_gen
```

This should print out something like:
```sh
tensorflow/tools/git/gen_git_source.py --generate tensorflow/tools/git/gen/spec.json tensorflow/tools/git/gen/head tensorflow/tools/git/gen/branch_ref "bazel-out/local-fastbuild/genfiles/tensorflow/core/util/version_info.cc"'
```

If you can execute that snippet, it should print out the details of why the python script that generates `version_info.cc` failed. Let us know what that is, and we might be able to pinpoint the problem.

Thanks.

**Comment by deeptigp** [comment]
Hi Asim,

Thanks for looking into this! When I run the above command (with --verbose_failures), I get the following error message:

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
>>>>> # //tensorflow/core:version_info_gen [action 'Executing genrule //tensorflow/core:version_info_gen']
(cd /home/deepti/.cache/bazel/_bazel_deepti/2ff5020c8dabdcb4abc9307fab6c0bfa/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate  "bazel-out/local-fastbuild/genfiles/tensorflow/core/util/version_info.cc"')
ERROR:$TFLOW/tensorflow/core/BUILD:991:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command 
  (cd /home/deepti/.cache/bazel/_bazel_deepti/2ff5020c8dabdcb4abc9307fab6c0bfa/execroot/tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate  "bazel-out/local-fastbuild/genfiles/tensorflow/core/util/version_info.cc"'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 221, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 152, in generate
    spec, head_symlink, _, dest_file = arglist
ValueError: need more than 1 value to unpack
Target //tensorflow/core:version_info_gen failed to build
INFO: Elapsed time: 0.143s, Critical Path: 0.03s

```

Line 991 in the BUILD file under core/ directory has the following call: tf_version_info_genrule()

I hope this message is helpful to you. 

Thanks!

**Comment by asimshankar** [comment]
@deeptigp : Which version of Bazel are you using? If less than 0.3.2, please upgrade to 0.3.2 and retry. (You can get the version with `bazel version`).

(In the future, please do try an include all information requested in the [New issue template](https://github.com/tensorflow/tensorflow/issues/new) )

**Comment by deeptigp** [comment]
Hi Asim,

Thanks for your response. The bazel version installed on my machine was 0.3.2, but I had an older version of tensorflow. Upgrading to 0.11 resolved this issue.

Thanks for your help!

**Comment by rlrosa** [comment]
In my case I had branched off after running configure. As suggested here, running this exposed what was making tf unhappy:

````
bazel build -s //tensorflow/core:version_info_gen
INFO: Found 1 target...
>>>>> # //tensorflow/core:version_info_gen [action 'Executing genrule //tensorflow/core:version_info_gen']
(cd /home/rrosa/.cache/bazel/_bazel_rrosa/0bc32e86368550ea439dcf6daa0b227b/execroot/org_tensorflow && \
  exec env - \
    ....
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; tensorflow/tools/git/gen_git_source.py --generate tensorflow/tools/git/gen/spec.json tensorflow/tools/git/gen/head tensorflow/tools/git/gen/branch_ref "bazel-out/local-opt/genfiles/tensorflow/core/util/version_info.cc"')
ERROR: /home/rrosa/tensorflow/tensorflow/core/BUILD:1416:1: Executing genrule //tensorflow/core:version_info_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "tensorflow/tools/git/gen_git_source.py", line 264, in <module>
    generate(args.generate)
  File "tensorflow/tools/git/gen_git_source.py", line 215, in generate
    (old_branch, new_branch))
RuntimeError: Run ./configure again, branch was 'refs/heads/r1.3' but is now 'refs/heads/mynewbranch'
Target //tensorflow/core:version_info_gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.901s, Critical Path: 0.03s
```

**Comment by narrowsnap** [comment]
check whether you install git package
```
sudo apt install git
```
