### ISSUE TITLE
Tensorflow Lite Model Maker cannot train EfficientDet-Lite using Cloud TPU

### ISSUE THREAD

**Issue by tve** [tensorflow/tensorflow#50965]
**System information**
- Have I written custom code: minimally modified stock example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab Pro w/TPU
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5

**Describe the current behavior**

Attempting to use a CloudTPU for training results in the following error:
```
INFO:absl:Using /tmp/tfhub_modules to cache modules.
INFO:absl:Downloading TF-Hub Module 'https://tfhub.dev/tensorflow/efficientdet/lite0/feature-vector/1'.
INFO:absl:Downloaded https://tfhub.dev/tensorflow/efficientdet/lite0/feature-vector/1, Total size: 29.61MB
INFO:absl:Downloaded TF-Hub Module 'https://tfhub.dev/tensorflow/efficientdet/lite0/feature-vector/1'.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-9-fb7d2e23be2c> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, batch_size=8, epochs=4, train_whole_model=True, validation_data=validation_data)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in shape(self)
   1196         # `_tensor_shape` is declared and defined in the definition of
   1197         # `EagerTensor`, in C.
-> 1198         self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())
   1199       except core._NotOkStatusException as e:
   1200         six.raise_from(core._status_to_exception(e.code, e.message), None)

InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /tmp/tfhub_modules/0771ebbebbfa831cd20c20680920ec4ad9deb2bd/variables/variables: Unimplemented: File system scheme '[local]' not implemented (file: '/tmp/tfhub_modules/0771ebbebbfa831cd20c20680920ec4ad9deb2bd/variables/variables')
```

**Standalone code to reproduce the issue**

See: https://gist.github.com/tve/615f4b51fa88dc643358176c86d6537e
Use the "open in colab" button and run it to get the error (or just read the results in the gist).
The original tutorial is https://www.tensorflow.org/lite/tutorials/model_maker_object_detection
I added:
- `tpu = tf.distribute.cluster_resolver.TPUClusterResolver()`

and I changed:
- from `spec = model_spec.get('efficientdet_lite0')`
- to `spec = object_detector_spec.efficientdet_lite0_spec(strategy='tpu', tpu=tpu.master(), debug=True)`

It's quite possible that I'm missing some magic, but I cannot find any tutorial or example that shows the use of model maker to train an object detection model using cloud TPU...

**Comment by tve** [comment]
The problem I'm having appears to be related to https://github.com/tensorflow/hub/issues/604, but I haven't confirmed that yet.

**Comment by gowthamkpr** [comment]
@tve This issue is related to hub and tpu and . As mentioned [here](https://github.com/tensorflow/hub/issues/604#issuecomment-772619178), use this workaround to solve the issue. Thanks!
