### ISSUE TITLE
protobuf error while saving the model 

### ISSUE THREAD

**Issue by zeeshannisar** [tensorflow/tensorflow#50967]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 16.04.7 LTS
- TensorFlow installed from: conda
-  TensorFlow version: 1.15.0
- Python version: 3.6.13 from Anaconda
- GPU: Quadro P6000 (Memory 24.5GB)

I am trying to adopt the pixelcnn++ code available at https://github.com/openai/pixel-cnn. Initiallly with tensorflow version 1.10.0 it was working fine. Later I updated the code with an addition of incorporating ` tf.compat.v1.extract_image_patches` and run it using tensorflow version 1.15.0 (as ` tf.compat.v1.extract_image_patches` is nor compatible with tensorflow 1.10.0). 

While saving the model after every 1000 iterations with: 
`saver.save(sess, args.save_dir + '/best_params_' + args.data_set + '.ckpt') `      
error occurs:
```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'tensorflow.TensorShapeProto.Dim.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
Traceback (most recent call last):
  File "train_pxpp_softmax_random_patch_extraction.py", line 325, in <module>
    saver.save(sess, args.save_dir + '/best_params_' + args.data_set + '.ckpt')
  File "/home/nisar/anaconda3/envs/pixelcnn/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1203, in save
    save_debug_info=save_debug_info)
  File "/home/nisar/anaconda3/envs/pixelcnn/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1246, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/home/nisar/anaconda3/envs/pixelcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3238, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/home/nisar/anaconda3/envs/pixelcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3166, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message
```
Though it saves the model succesffuly at iteration 0. I also tried to save the model after every 500 iterations and it works fine for 0 and 500 but same error occurs at 1000 iteration. Following is the complete updated pixelcnn++ code with additions:

**Comment by tilakrayal** [comment]
@zeeshannisar ,

We see that you are using tf version 1.15, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.Thanks!
