### ISSUE TITLE
At Chrome run Tensorflow.js.

### ISSUE THREAD

**Issue by blcyzycc** [tensorflow/tensorflow#50968]
Use the square layer tf.layers.conv2d, This file prompts a run error.

webgl_util.js

Error: Failed to compile fragment shader.

**Comment by UsharaniPagadala** [comment]
@blcyzycc 

The issue posted  looks like related to [Tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues) repo. Could you please post this issue in that repo. Hence there is a big community to support for tfjs issues. Thanks

**Comment by blcyzycc** [comment]
This error does not always appear, it can run normally on Edge, and this error will not appear.

**Comment by Saduf2019** [comment]
@blcyzycc 
Please check these issues:[ link](https://stackoverflow.com/questions/51296173/failed-to-compile-fragment-shader-when-using-tensorflow-on-angular),[link2](https://github.com/tensorflow/tfjs/issues/1644) in case the issue still exist please create an issue @ [this repo](https://github.com/tensorflow/tfjs/issues/) and move this to closed status.
