### ISSUE TITLE
The max version of bazel supported by tensorflow should be increased to 4.1.0 or higher

### ISSUE THREAD

**Issue by Cheney-W** [tensorflow/tensorflow#50966]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 21H1
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.4

**Describe the problem**
I'm a member of Microsoft VCPKG team, we recently upgraded the version of bazel used in vcpkg to 4.1.0, then tensorflow build failed with following error:
```
You have bazel 4.1.0 installed.
Please downgrade your bazel installation to version 3.99.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```
This issue is due to the fact that tensorflow has set the maximum supported version of bazel to 3.99.0 on line 53 of the https://github.com/tensorflow/tensorflow/blob/master/configure.py file.

For fixing this issue, the max version of bazel supported by tensorflow should be increased to 4.1.0 or higher.

**Any other info / logs**
I have tested that tensorflow could installed successfully when using bazel 4.1.0.

**Comment by Saduf2019** [comment]
@Cheney-W 
A [pr](https://github.com/tensorflow/tensorflow/pull/50882) has been created to reflect the changes once its merged this issue will move to closed status.

**Comment by Cheney-W** [comment]
@Saduf2019 
The related PR has been merged, but the max version of bazel is still 3.99.0. 
I saw Mihai Maruseac changed the value to 4.1.0 but then changed it back.
For the moment, this problem still exists.

**Comment by mihaimaruseac** [comment]
Commented on #51045: we have had some compile fail when we last tried to update. Afaik, it's related to the protobuf dep being too tied in in both TF and Bazel

**Comment by Cheney-W** [comment]
Thanks for your help!
