### ISSUE TITLE
RuntimeError: Attempting to capture an EagerTensor without building a function.

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#50978]
**tensorflow 2.5**

Adding the code of 
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
indeed solves the problem. But it maynot be what I want. Because in the function of `dense_tensor_to_sparse_tensor` , I indeed need the eager execution of `tensor.numpy()`, which means I should not disable the v2 behaviour. So is this the internal bug of tf 2.5. Any suggestion of how to modify this piece of code?

### source code

```

import tensorflow as tf
import numpy as np
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()


from tensorflow.python.ops.linalg.sparse import sparse_csr_matrix_ops


a_indices = np.array([[0, 0], [2, 3], [2, 4], [3, 0]])
a_values = np.array([1.0, 5.0, -1.0, -2.0], np.float32)
a_dense_shape = [4, 5]

a_st = tf.sparse.SparseTensor(a_indices, a_values, a_dense_shape)

def dense_tensor_to_sparse_tensor(tensor):

    col = tensor.shape.as_list()[0]
    print(col)

    x = np.arange(col)
    y = np.zeros(1)
    xi, yi = np.meshgrid(x, y)
    sparse_tensor = tf.sparse.SparseTensor(indices=np.array(np.vstack([xi.ravel(), yi.ravel()]).T),
                                           values=tensor.numpy(),
                                           dense_shape=[col, 1])
    return sparse_tensor


b_indices = np.array([[0,0], [1,0], [2,0], [3,0],[4,0]])
# b_indices = np.array([[0,0], [0,1], [0,2], [0,3],[0,4]])
b_values = np.array([2.0, 7.0, 8.0,9.0,10.0], np.float32)
b_dense_shape = [5,1]

B = tf.constant([2.0, 7.0, 8.0,9.0,10.0])
B_sparse = dense_tensor_to_sparse_tensor(B)
print(B_sparse.indices, B_sparse.values, B_sparse.dense_shape)

with tf.compat.v1.Session() as sess:
    # Define (COO format) Sparse Tensors over Numpy arrays
    a_st = tf.sparse.SparseTensor(a_indices, a_values, a_dense_shape)
    # b_st = tf.sparse.SparseTensor(b_indices, b_values, b_dense_shape)
    b_st = B_sparse

    # Convert SparseTensors to CSR SparseMatrix
    a_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        a_st.indices, a_st.values, a_st.dense_shape)
    b_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        b_st.indices, b_st.values, b_st.dense_shape)

    # Compute the CSR SparseMatrix matrix multiplication
    c_sm = sparse_csr_matrix_ops.sparse_matrix_sparse_mat_mul(
        a=a_sm, b=b_sm, type=tf.float32)

    # Convert the CSR SparseMatrix product to a dense Tensor
    c_sm_dense = sparse_csr_matrix_ops.csr_sparse_matrix_to_dense(
        c_sm, tf.float32)
    # Evaluate the dense Tensor value
    c_sm_dense_value = sess.run(c_sm_dense)
    print(c_sm_dense_value)
    # print(sess.run(a_st))

```

### **error  message:**
```


Traceback (most recent call last):
  File "test3.py", line 92, in <module>
    b_st.indices, b_st.values, b_st.dense_shape)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/ops/linalg/sparse/gen_sparse_csr_matrix_ops.py", line 1332, in sparse_tensor_to_csr_sparse_matrix
    dense_shape=dense_shape, name=name)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 522, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1525, in convert_to_tensor
    raise RuntimeError("Attempting to capture an EagerTensor without "
RuntimeError: Attempting to capture an EagerTensor without building a function.

```

**Comment by sjtusmartboy** [comment]
The problem exists because the `b_st` is the value from the calling the function of `dense_tensor_to_sparse_tensor`. From the perspective of  a user, it should not be the problem, which means whether `b_st` is directly the assigned sparse tensor or the return value from the function should not be different.

**Comment by sjtusmartboy** [comment]
I've made some arrangement of the code, resulting in the same problem.

```
import tensorflow as tf
import numpy as np
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()


from tensorflow.python.ops.linalg.sparse import sparse_csr_matrix_ops

a_indices = np.array([[0, 0], [2, 3], [2, 4], [3, 0]])
a_values = np.array([1.0, 5.0, -1.0, -2.0], np.float32)
a_dense_shape = [4, 5]

a_st = tf.sparse.SparseTensor(a_indices, a_values, a_dense_shape)

B = tf.constant([2.0, 7.0, 8.0,9.0,10.0])

def sparse_matrix_dense_tensor1d_matmul(sparse_matrix, tensor1d):
    # Convert SparseTensors to CSR SparseMatrix
    a_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        sparse_matrix.indices, sparse_matrix.values, sparse_matrix.dense_shape)

    col = tensor1d.shape.as_list()[0]

    x = np.arange(col)
    y = np.zeros(1)
    xi, yi = np.meshgrid(x, y)
    b_st = tf.sparse.SparseTensor(indices=np.array(np.vstack([xi.ravel(), yi.ravel()]).T),
                                  values=tensor1d.numpy(),
                                  dense_shape=[col, 1])

    b_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        b_st.indices, b_st.values, b_st.dense_shape)

    # Compute the CSR SparseMatrix matrix multiplication
    c_sm = sparse_csr_matrix_ops.sparse_matrix_sparse_mat_mul(
        a=a_sm, b=b_sm, type=tf.float32)

    # Convert the CSR SparseMatrix product to a dense Tensor
    c_sm_dense = sparse_csr_matrix_ops.csr_sparse_matrix_to_dense(
        c_sm, tf.float32)

    return c_sm_dense

with tf.compat.v1.Session() as sess:
    sparse_matrix_dense_tensor1d_matmul(a_st, B)
```

**Comment by old-school-kid** [comment]
@sjtusmartboy 
Instead of defining your own function to convert dense tensor to sparse tensor you can use 
`tf.sparse.from_dense`. So you wont need eager tensors at all. Also you are using tensorflow1 which uses Graph execution but your function returns an eager tensor which is not allowed, and thus the error.

**Comment by sjtusmartboy** [comment]
@old-school-kid Thank you, I've solved the problem

**Comment by sjtusmartboy** [comment]
@old-school-kid If `a` is a sparse column vector(n*1), then how to get the result of `a matmul a.T`, which is also the sparse matrix with dense_shape (n*n) ? Any available solution in tensorflow, haha?

**Comment by old-school-kid** [comment]
Hi @sjtusmartboy I believe this is what you are looking for
`tf.linalg.matmul(tf.sparse.to_dense(a),
              tf.sparse.to_dense( tf.sparse.transpose(a)),
              a_is_sparse=True, b_is_sparse=True)`

If the product is too large you can store the values and index only and reconstruct the tensor when needed. Details can be found in the [doc](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor)

**Comment by sjtusmartboy** [comment]
@old-school-kid It seems `tf.linalg.matmul` returns the dense matrix of `a matmul a.T`, which is too large to be stored in the memory.

**Comment by rxy1212** [comment]
I have same issue in code below:
`   def simcse_loss(y_true, y_pred):
        batch = tf.shape(y_pred)[0]
        idx = tf.range(0, batch, dtype=tf.int32)
        idx_1 = idx[None, :]
        idx_2 = (idx + 1 - idx % 2 * 2)[:, None]
        y_true = tf.equal(idx_1, idx_2)
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.math.l2_normalize(y_pred, axis=1)
        similarities = tf.matmul(y_pred, tf.transpose(y_pred))
        similarities = similarities - tf.eye(tf.shape(y_pred)[0]) * 1e12
        similarities = similarities * 20
        loss = tf.keras.losses.categorical_crossentropy(y_true, similarities, from_logits=True)
        return tf.reduce_mean(loss)`
`tf.eye` trigger the error "RuntimeError: Attempting to capture an EagerTensor without building a function."
Notably, in tf2.5 it works fine, but throw error in tf2.3

**Comment by rxy1212** [comment]
> I have same issue in code below:
> 
> ```
> def simcse_loss(y_true, y_pred):
>       batch = tf.shape(y_pred)[0]
>       idx = tf.range(0, batch, dtype=tf.int32)
>       idx_1 = idx[None, :]
>       idx_2 = (idx + 1 - idx % 2 * 2)[:, None]
>       y_true = tf.equal(idx_1, idx_2)
>       y_true = tf.cast(y_true, tf.float32)
>       y_pred = tf.math.l2_normalize(y_pred, axis=1)
>       similarities = tf.matmul(y_pred, tf.transpose(y_pred))
>       similarities = similarities - tf.eye(tf.shape(y_pred)[0]) * 1e12
>       similarities = similarities * 20
>       loss = tf.keras.losses.categorical_crossentropy(y_true, similarities, from_logits=True)
>       return tf.reduce_mean(loss)
> ```
> 
> `tf.eye` trigger the error "RuntimeError: Attempting to capture an EagerTensor without building a function."
> Notably, in tf2.5 it works fine, but throw error in tf2.3

I guess that tensorflow doesn't allow user to create new tensor in some context. But I can't find any documents for this

**Comment by sjtusmartboy** [comment]
@rxy1212 I agree. tf is so difficult to use. It cannot let us focus on the model optimization, but wasting lots of time on these meaningless bugs.

**Comment by old-school-kid** [comment]
Hi @rxy1212 
Tensorflow 2 by default executes in Eager mode and thus `tf.shape(y_pred)[0]` will throw and error. Had it been in graph mode which can turn on by disabling the tensorflow2 behavior there would have been no such error. There was a major update in Tensorflow2.5 which made it more friendly to use and in the background tf.autograph is executed for you. Thus you will face the error in Tf2.3 and not in Tf2.5.

Also @sjtusmartboy 
A framework is merely a tool and the most important part of DL is the [maths](https://www.tensorflow.org/guide/intro_to_graphs) underneath.

**Comment by sjtusmartboy** [comment]
@old-school-kid I agree with, the most import part is the math, but I find it not easy to make iteration of algorithms in a short time

**Comment by mdanatg** [comment]
You should avoid using the Session API in TF2. I'm not 100% sure, but it likely is the cause for your error. See [this guide](https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls).
