### ISSUE TITLE
FunctionalPreprocessingStage incompatible with some keras preprocessing layers

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tensorflow#50979]
**Describe the current behavior**

[FunctionalPreprocessingStage](https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/layers/preprocessing/preprocessing_stage.py#L98-L133) provides a Functional like interface for connecting up multiple keras preprocessing layers, and adapting them all with a single call. If I understand the intended use correctly, you must first call the instances of the various preprocessing layers in order to connect them up into a DAG, wrap the inputs & outputs with FunctionalPreprocessingStage and then call adapt on that. However, some of the preprocessing layers throw an error if you call them before they have been adapted (eg. [IndexLookup](https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/layers/preprocessing/index_lookup.py#L599-L602) which is also used by other related classes like StringLookup, although this was not the case in [v2.4.0](https://github.com/tensorflow/tensorflow/blob/582c8d236cb079023657287c318ff26adb239002/tensorflow/python/keras/layers/preprocessing/index_lookup.py#L370-L373)).

**Describe the expected behavior**

All Keras preprocessing layers should be compatible with FunctionalPreprocessingStage.

Minimal reproducible example:

```python
# Expected usage
input_layer = tf.keras.Input(name='scalar_string', shape=(1,), dtype=tf.string)
lookup_layer = tf.keras.layers.experimental.preprocessing.StringLookup(num_oov_indices=1, name="scalar_string_idx")
output_layer = lookup_layer(input_layer) # this actually raises a ValueError
fps = preprocessing_stage.FunctionalPreprocessingStage(input_layer, output_layer)
fps.adapt(tf.constant([['testing'], ['one'], ['two'], ['three']]))
```

**Comment by tilakrayal** [comment]
@peteboothroyd ,

Please post this issue on keras-team/keras repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by peteboothroyd** [comment]
Thanks for the pointer @tilakrayal . Looking at the keras repo I can see that this has already been [fixed](https://github.com/keras-team/keras/commit/fe31a34aa3447c5a7a768a8f61dcfd022ac2467b#diff-85c5529af75b28bafb4ddf95a2f4909eb6016ebd747ee62d3308bb738a7cfc80) in 2.6.0 there, so this issue is no longer relevant
