### ISSUE TITLE
Documentation: old installation requirements

### ISSUE THREAD

**Issue by ternite** [tensorflow/tensorflow#50973]
Hi,

on the [page with installation instructions](https://www.tensorflow.org/install?hl=en), the listed requirements have not been updated: it lists Python 3.6–3.8 explicitly.

According to the [pip installation guide](https://www.tensorflow.org/install/pip), Python 3.9 is a valid requirement.

I suggest updating the page.

Best regards
Thomas

**Comment by PINTO0309** [comment]
@ternite I fixed it.
https://www.tensorflow.org/install?hl=en
![Screenshot from 2021-07-28 13-21-04](https://user-images.githubusercontent.com/33194443/127263222-0abca4f2-1263-4291-b753-8a871e821646.png)

**Comment by Saduf2019** [comment]
Moving this to closed status as issue is resolved.
