### ISSUE TITLE
XLA compilation error for TPU

### ISSUE THREAD

**Issue by lamyiowce** [tensorflow/tensorflow#50980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04 (GCP Cloud TPU VM)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): default cloud TPU VM installation
- TensorFlow version (use command below): unknown 2.6.0
- Python version: 3.8.10
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: no
- GPU model and memory: TPU

**Describe the current behavior**
Model compilation for TPU fails with logs:
```
2021-07-27 14:46:12.541836: I tensorflow/core/tpu/kernels/tpu_compilation_cache_interface.cc:435] TPU host compilation cache miss: cache_key(7086181526061168380), session_name()
2021-07-27 14:46:14.141350: I tensorflow/core/tpu/kernels/tpu_compile_op_common.cc:66] TpuCompileOp was cancelled. Sleeping for 300 seconds to give time for TPUCompileOp to finished.
2021-07-27 14:46:17.250612: I tensorflow/core/tpu/kernels/tpu_compile_op_common.cc:175] Compilation of 7086181526061168380 with session name  took 4.708620071s and failed
2021-07-27 14:46:17.250711: F tensorflow/core/tpu/kernels/tpu_program_group.cc:86] Check failed: xla_tpu_programs.size() > 0 (0 vs. 0)
```

**Describe the expected behavior**
The model compiles or at least a meaningful error message with a cause is printed.

**Standalone code to reproduce the issue**

The code ran was this: https://github.com/TensorSpeech/TensorFlowASR/blob/main/examples/conformer/train.py

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Full log: https://gist.github.com/lamyiowce/2e9c0adc3c9c52b4785c63898c0a6b43

**Comment by UsharaniPagadala** [comment]
@lamyiowce 

Could you please refer similar issues [#30580](https://github.com/tensorflow/tensorflow/issues/30580) and  [#48268](https://github.com/tensorflow/tensorflow/issues/48268) ,let us know if it helps.Thanks

**Comment by lamyiowce** [comment]
Thank you for the tips. However, both of those are supposed to be fixed in TF 2.6 and none of the methods showed there helped me.

**Comment by UsharaniPagadala** [comment]
@lamyiowce 

Could you please share the colab gist with all the dependencies to analyse the issue better.Thanks

**Comment by thsunkid** [comment]
My models failed in different situations with the same log. 
> F tensorflow/core/tpu/kernels/tpu_program_group.cc:86] Check failed: xla_tpu_programs.size() > 0 (0 vs. 0)
In those cases, reducing model size or reducing the batch size often helped. 
I suspect it could be a memory related issue.

**Comment by thsunkid** [comment]
@UsharaniPagadala 
This gist produces the similar error https://gist.github.com/thsunkid/28731eddd4192cb10f8441e338d84d35.
Can you take a look on it?

**Comment by steveepreston** [comment]
this issue still exists in tf 2.16.1 (on Kaggle TPU VM v3-8)
```shell
TPU host compilation cache miss: cache_key(zzz:0:0), session_name()
```

**Comment by steveepreston** [comment]
is TPU support dead?
