### ISSUE TITLE
fake quant in tflite ignores the num_bits that is passed

### ISSUE THREAD

**Issue by reuvenperetz** [tensorflow/tensorflow#50993]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0

### 2. Code

``` python
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

keras = tf.keras
layers = tf.keras.layers

input_shape = (1, 1000)
inputs = layers.Input(shape=input_shape)
outputs = tf.quantization.fake_quant_with_min_max_args(inputs=inputs, num_bits=2, min=-2, max=2)
model = keras.Model(inputs=inputs, outputs=outputs)


def convert_to_tflite(model):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    return tflite_model


def infer(tflite_model, img):
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    interpreter.set_tensor(input_details["index"], img)
    interpreter.invoke()
    output_details = interpreter.get_output_details()[0]
    output = interpreter.get_tensor(output_details["index"])[0]
    return output


img = np.sort(np.random.random((1,)+input_shape).astype(np.float32) * 5 - 2.5)
tflite_model = convert_to_tflite(model)
tf_output = model.predict(img)
tflite_output = infer(tflite_model, img)

fig, axs = plt.subplots(2)
fig.suptitle('FakeQuant TFLite vs TF')

x = img.flatten()
axs[0].plot(x, tflite_output.flatten())
axs[1].plot(x, tf_output.flatten())
plt.show()
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:
When quantizing using fake quant with less than 8 bits, it seems to actually quantize the input with 8 bits anyway.
In Tensorflow it seems to work, but not in TFLite.

### 5. (optional) Any other info / logs
Here for example is a plot of quantizing a tensor using 2 bits. The upper subplot is the output of TFLite, while the bottom subplot is the output of Tensorflow.

![fq_issue](https://user-images.githubusercontent.com/44209964/127321225-4b2181bc-a822-40d4-bebc-3557a3deb8c7.png)

**Comment by daverim** [comment]
Currently TFLite doesn't support any quantized data type with bitwidth less than 8, so even though the fake quant op seens to be working in TF, when converted to TFLite, (with default optimization) it will assume that the requested behavior is to produce an 8bit operation (quantize to 8 bits). In the future we may support 4bit and ternary types, but at the moment, there is no way to get the behavior you desire.
