### ISSUE TITLE
Help Me 😅

### ISSUE THREAD

**Issue by Shion7581** [tensorflow/tensorflow#50990]
Can Anyone tell me why is this happening? I am new to Python so it might be a silly issue 😅
![dfhdfhdtr](https://user-images.githubusercontent.com/70793550/127268620-ba792466-e339-4231-95a3-d66d4fed52b5.JPG)

**Comment by bensuperpc** [comment]
i think you need to install the python package: pillow 
`pip install Pillow`

**Comment by tilakrayal** [comment]
@Shion7581 ,
Can you please take a look at this [link](https://www.geeksforgeeks.org/python-pillow-a-fork-of-pil/) for more information.It helps.Thanks!

**Comment by tilakrayal** [comment]
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Shion7581** [comment]
Thank you everyone for telling me the solution appreciate your kindness :)

**Comment by tilakrayal** [comment]
@Shion7581 ,
Glad the issue is resolved for you, please feel free to move this to closed status.
