### ISSUE TITLE
Ubuntu ImportError: No module named core.framework.graph_pb2

### ISSUE THREAD

**Issue by liuyipei** [tensorflow/tensorflow#51]
I am unable to import tensorflow.
This problem appears whether I try to rebuild from source or by using the .whl directly.

```
(tensorflow)$ uname -a
Linux yi-2014 3.13.0-64-generic #104-Ubuntu SMP Wed Sep 9 12:36:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
(tensorflow)$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2
>>> 
```

**Comment by ebrevdo** [comment]
Are you running python inside the tensorflow source directory?  If the directory 'tensorflow' is in your pwd, it may break imports.  Try running python outside the source tree.

If that's not it, please give some info about your system, version of python, etc.

**Comment by liuyipei** [comment]
Thank you. This solves it. 

I am still having other import issues, which I will open a new thread for.

**Comment by PeterBeukelman** [comment]
from another directory, the error just changes to
ImportError: cannot import name compat
