### ISSUE TITLE
TensorFlow Lite C API full example

### ISSUE THREAD

**Issue by barbaragabriella** [tensorflow/tensorflow#51026]
Is there any example fully in C language using Tensorflow Lite C API? More specifically for image classification or object detection? I have not been able to find any TensorFlow example in C.

**Comment by sushreebarsa** [comment]
@barbaragabriella Could you please refer to this [link](https://www.tensorflow.org/lite/guide/android#use_tflite_c_api) and let us know if it helps ? Thanks !

**Comment by barbaragabriella** [comment]
The instructions there say to download TensorFlow Lite AAR hosted at MavenCentral which leads to the started page https://search.maven.org/. Which project is it referring to exactly?

**Comment by sushreebarsa** [comment]
That link is not proper for downloading AAR which is used in TFlite projects, you may refer to these two already prepared Tensorflow lite AAR.
https://search.maven.org/artifact/org.tensorflow/tensorflow-lite-task-text
https://search.maven.org/artifact/org.tensorflow/tensorflow-lite-task-vision
This two mavens can be used in build file as following inside the android code

dependencies {
    implementation 'org.tensorflow:tensorflow-lite-task-vision:0.1.0'
    implementation 'org.tensorflow:tensorflow-lite-task-text:0.1.0'
}
