### ISSUE TITLE
TfLite python delegate support for RB5 robotics platform

### ISSUE THREAD

**Issue by marko19a** [tensorflow/tensorflow#51030]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
Robotics RB5 Platform
Linux qrb5165-rb5 4.19.125 aarch64 GNU/Linux
CPU: Qualcomm QRB5165
RAM: 8GB
- TensorFlow version (you are using):
- Python 3.6.9
- python3-tflite-runtime (2.5.0.post1)
- hexagon_nn_skel_v1.20.0.1
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Currently it works on cpu cores, I would like to delegate it to libhexagon_nn_skel.so.
When I run:
`tflite.load_delegate('libhexagon_nn_skel.so')`
It returns:
`OSError: libhexagon_nn_skel.so: wrong ELF class: ELFCLASS32`
Same with v65 and v66
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Everyone using RB5 platform with python, and likely oyher sililar Qualcomm products
**Any Other info.**

**Comment by multiverse-tf** [comment]
> _Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template_
> 
> **System information**
> Robotics RB5 Platform
> Linux qrb5165-rb5 4.19.125 aarch64 GNU/Linux
> CPU: Qualcomm QRB5165
> RAM: 8GB
> 
> * TensorFlow version (you are using):
> * Python 3.6.9
> * python3-tflite-runtime (2.5.0.post1)
> * hexagon_nn_skel_v1.20.0.1
> * Are you willing to contribute it (Yes/No):
>   Yes
> 
> **Describe the feature and the current behavior/state.**
> Currently it works on cpu cores, I would like to delegate it to libhexagon_nn_skel.so.
> When I run:
> `tflite.load_delegate('libhexagon_nn_skel.so')`

At first sight, judging from the delegate file name, I don't think you are loading the correct one.  Here's an example of using this API: [src code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/interpreter_test.py#L416-L429) and [build rule to compile the delegate .so](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/testdata/BUILD#L89-L97)
@terryheo could provide more info about using delegate APIs in Python.

As for the TfLite hexagon delegate, have you built the TfLite Hexagon delegate .so file? @karimnosseir could provide more info about this delegate.

> It returns:
> `OSError: libhexagon_nn_skel.so: wrong ELF class: ELFCLASS32`
> Same with v65 and v66
> **Will this change the current api? How?**
> No
> **Who will benefit with this feature?**
> Everyone using RB5 platform with python, and likely oyher sililar Qualcomm products
> **Any Other info.**

**Comment by marko19a** [comment]
> At first sight, judging from the delegate file name, I don't think you are loading the correct one. Here's an example of using this API: [src code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/interpreter_test.py#L416-L429) and [build rule to compile the delegate .so](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/testdata/BUILD#L89-L97)
> @terryheo could provide more info about using delegate APIs in Python.
> 
> As for the TfLite hexagon delegate, have you built the TfLite Hexagon delegate .so file? @karimnosseir could provide more info about this delegate.

I have downloaded the .so files from [TensorFlow Lite Hexagon delegate](https://www.tensorflow.org/lite/performance/hexagon_delegate) page. It's for Android not for ubuntu based linux I am using, my device has hexagon 698 (Snapdragon 865 should be supported). Mybe I need a native build, can someone help me build .so file as i can't find any guide for building it?

**Comment by karimnosseir** [comment]
If you want to run on non-android then you will need to build
* the hexagon delegate (libhexagon_delegate.so - or statically)
* libhexagon_interface.so (You can reach to me directly and i can compile it and share it with you, the code to build it yourself is not fully in OSS yet, we are working on adding the remaining parts).

**Comment by feefro** [comment]
Hi, @karimnosseir can you share a procedure or example to use tflite hexagon delegate for RB5 platform with python or c++?

**Comment by karimnosseir** [comment]
Hi @feefro Sorry this thread got missed.
All the code for building Hexagon delegate is already on Github under [tensorflow/lite/delegates/hexagon](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/hexagon).
You can build it using your own toolchain of desire.
The C/C++ API can be found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_delegate.h)

**Comment by Sauroncheg** [comment]
maybe you can provide some CMake example for C++ code?

**Comment by Sauroncheg** [comment]
@karimnosseir can you help please?

**Comment by St190706025** [comment]
> maybe you can provide some CMake example for C++ code? which of those libraries should be linked ? libhexagon_delegate.so or libhexagon_interface.so or libhexagon_nn_skel(_v65/_v66).so

I have the same ıssue. Should I add libhexagon_nn_skel library for aarch64? Is it necessary?
