### ISSUE TITLE
Autograph set_verbosity doc example shows using integer values for env vars, but only strings can be used

### ISSUE THREAD

**Issue by Avelina9X** [tensorflow/tensorflow#51038]
## URL(s) with the issue:    
https://www.tensorflow.org/api_docs/python/tf/autograph/set_verbosity

## Description of issue (what needs changing):

The documentation usage description for setting verbosity through environment variables uses an integer value, however this is not possible as environment variables must be strings. In the current state the following code example is provided:

```py
import os
import tensorflow as tf

os.environ['AUTOGRAPH_VERBOSITY'] = 5
# Verbosity is now 5

tf.autograph.set_verbosity(0)
# Verbosity is now 0

os.environ['AUTOGRAPH_VERBOSITY'] = 1
# No effect, because set_verbosity was already called.
```

However it should actually be:

```py
import os
import tensorflow as tf

os.environ['AUTOGRAPH_VERBOSITY'] = '5'
# Verbosity is now 5

tf.autograph.set_verbosity(0)
# Verbosity is now 0

os.environ['AUTOGRAPH_VERBOSITY'] = '1'
# No effect, because set_verbosity was already called.
```

**Comment by tilakrayal** [comment]
@Saduf2019  ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/de7a8dd4b12cdfbe135adb82ca1af253/untitle51038.ipynb).

**Comment by Avelina9X** [comment]
This issue is TF version independent as this issue is python specific and purely a documentation error. There probably more instances in the docs of setting env vars to something other than strings, so I'll try and have a look to find more doc errors like this, but it might take a while to find more if they exist.

**Comment by ymodak** [comment]
The above commit fixes the issue. Thanks!
