### ISSUE TITLE
Release candidate 2.6.0rc1 is not built with HDFS support anymore?

### ISSUE THREAD

**Issue by robzor92** [tensorflow/tensorflow#51046]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary from pip
- TensorFlow version:
2.6.0rc1
- Python version:
3.7.10
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I installed the release candidate 2.6.0rc1 and tried to read files from HDFS and it failed complaining that hdfs is an unknown filesystem scheme. I have seen this problem before when working TensorFlow builds that were not built with HDFS support.

All previous TF 2.* versions including release candidates that I've tested is built with HDFS support and looking at the release notes I'm none the wiser as it does not mention that HDFS support is being dropped from the pip wheel.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
import tensorflow as tf
tf.io.gfile.glob("hdfs://localhost:8020/data")
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-6-3127c92cb05e> in <module>
----> 1 tf.io.gfile.glob("hdfs://localhost:8020/data")

/srv/hops/anaconda/envs/theenv/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py in get_matching_files_v2(pattern)
    441         compat.as_str_any(matching_filename)
    442         for matching_filename in _pywrap_file_io.GetMatchingFiles(
--> 443             compat.as_bytes(pattern))
    444     ]
    445   else:

UnimplementedError: File system scheme 'hdfs' not implemented (file: 'hdfs://localhost:8020/data')
```

**Comment by sushreebarsa** [comment]
@robzor92 Could you please take a look at the  [tested build configuration](https://www.tensorflow.org/install/source) for reference and let us know if it helps ?Thank you!

**Comment by robzor92** [comment]
Hi @sushreebarsa ! The **Tested Build Configuration** does not mentioned particular build flags, like HDFS support for example.

However I did some digging in the code and found out that HDFS and S3 support is not enabled by default anymore. https://github.com/tensorflow/tensorflow/pull/48522

Can I also confirm with you that this is the case for the builds that are published on PyPi? So basically this is the question: _Should TensorFlow 2.6.0 installed through pip support HDFS or do I need to build TensorFlow myself in order for it to work_?

**Comment by yongtang** [comment]
@robzor92 Please see PR #51036 and PR #51037. HDFS is now supported through tensorflow-io PyPI package (in together with tensorflow 2.6).

**Comment by robzor92** [comment]
That's great @yongtang I will try it out! I think this information may be missing from the current release notes for the rc1.

**Comment by robzor92** [comment]
Or maybe not, I see it was already done. https://github.com/yongtang/tensorflow/commit/9fcaf0838677d1095a7573e36ebb4d17511af6ed

Thanks for the help! I will close this issue now.
