### ISSUE TITLE
Does the "p" in "pfor" stand for "print" or something?

### ISSUE THREAD

**Issue by albert10jp** [tensorflow/tensorflow#51041]
https://github.com/tensorflow/tensorflow/blob/bfb74e15879212c3e4573fb83cd87358e964b4be/tensorflow/python/ops/parallel_for/pfor.py#L924

**Comment by ymodak** [comment]
`p` in `pfor` stands for parallel. See https://github.com/tensorflow/tensorflow/blob/72552c4a73650962abe5c110ab4e4068e741cef0/tensorflow/python/ops/parallel_for/pfor.py#L15
