### ISSUE TITLE
Add version to Zenodo

### ISSUE THREAD

**Issue by dmey** [tensorflow/tensorflow#51071]
I need to cite a specific version of TensorFlow in a paper -- Any chance you could add 2.3.1 to https://zenodo.org/record/4724125?

EDIT: this is no bug -- please change to Feature Request/Other Issues.

**Comment by jvishnuvardhan** [comment]
@dmey There is version TF2.3.3 listed there, the only difference between TF2.3.1 and 2.3.3 is security patches. Can you use that TF2.3.3 for citation? I think we may have no plans to go back and add older versions. Thanks!

**Comment by dmey** [comment]
@jvishnuvardhan thanks and not really. The requirements are to cite the exact same version used however I will work around this by updating the TF version used in my repo -- I see your point. Feel free to close this issue now.

**Comment by jvishnuvardhan** [comment]
@dmey Thanks!

**Comment by Fremih** [comment]
I was wondering if there was the plan to add more versions to Zenodo. I have the same problem, that I want to cite a certain version, namely v.2.11, that is not yet on Zenodo. I would be glad to have it there. Else, I have to stick to the older TF version v.2.9.1, which is the most up-to-date version on Zenodo.

**Comment by mihaimaruseac** [comment]
Zenodo is handled via automation. It is a bug if a recent entry is missing.

**Comment by mihaimaruseac** [comment]
Yes please. It is a bug
