### ISSUE TITLE
__iter__() is only supported inside of tf.function or when eager execution is enabled

### ISSUE THREAD

**Issue by nhutthanh340** [tensorflow/tensorflow#51076]
**System information**
- Tensorflow version: 2.2.0 
- Python version: 3.8.6

![image](https://user-images.githubusercontent.com/36669308/127742743-1fcc6fe6-24a3-40cc-9433-0d244fb54276.png)

It working in tensorflow 1.10.1 and python 3.6.5, but not 2.2.0
How can anyone resolve it, please?
Thanks

**Comment by sushreebarsa** [comment]
@nhutthanh340 Could you please have a look at the [link1](https://stackoverflow.com/questions/63182524/runtimeerror-iter-is-only-supported-inside-of-tf-function-or-when-eager-e) ,[link2](https://stackoverflow.com/questions/55576133/tensorflow-2-0-dataset-iter-is-only-supported-when-eager-execution-is-enab/56736763) which are similar issues mentioned in stackoverflow and let us know if it helps ? Thank you!

**Comment by nhutthanh340** [comment]
I have tried, but still error

**Comment by nhutthanh340** [comment]
The data in my code is batch inputs

**Comment by sushreebarsa** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
