### ISSUE TITLE
Linux setup guide update for Ubuntu 20.04 

### ISSUE THREAD

**Issue by omerferhatt** [tensorflow/tensorflow#51075]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu#install_cuda_with_apt

## Description of issue (what needs changing):

Ubuntu 20.04 installation guide for new CUDA and CUDnn versions.

### Clear description

Since new LTS released by Ubuntu, maybe CUDA installation can be updated.

### Correct links

None

### Parameters defined

None

### Returns defined

None

### Raises listed and defined

None

### Usage example

None

### Request visuals, if applicable

None

### Submit a pull request?

None

**Comment by tilakrayal** [comment]
@omerferhatt ,

Similar issue has been tracked with #43693.Can you please subscribe the issue to get the update for Ubuntu 20.04.Thanks
