### ISSUE TITLE
Can sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix be used in the graph mode?

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51072]
tensorflow 2.5

When I run `sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix` this function in the graph mode, it gives out the error of `    ValueError: Invalid rank: -1.  Expected a known rank of either 2 or 3. for '{{node SparseTensorToCSRSparseMatrix}} = SparseTensorToCSRSparseMatrix[T=DT_DOUBLE](SparseConcat_4, SparseConcat_4:1, SparseConcat_4:2)' with input shapes: [?,?], [?], [?].`It seems that this function cannot recognize the rank of csr matrix. However, if I run the function not in the graph mode, it works well without any debug. Why?

**Comment by sjtusmartboy** [comment]
from tensorflow.python.ops.linalg.sparse import sparse_csr_matrix_ops

**Comment by tilakrayal** [comment]
@sjtusmartboy ,

Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!

**Comment by sjtusmartboy** [comment]
I'm so sorry because the code requires the local dataset which is too large. The parameter of  `sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix` is from the dataset.from_generator. The same kind of error occurs where I use `tensor.shape` in the graph, but no error if I use `tf.shape(tensor)`to get the shape of a tensor in the graph.

**Comment by tilakrayal** [comment]
@sjtusmartboy ,

Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide completed code.Thanks!
