### ISSUE TITLE
Op type not registered 'NormalizeUTF8' in binary running  when reload model 

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#51080]
tf version: 2.4.1

```
def get_model_bert(num_classes):

    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string) # shape=(None,) dtype=string

    encoder = hub.KerasLayer("./resource/albert_en_base_2", trainable=True)

    encoder_inputs = preprocessor_layer(text_input)
    outputs = encoder(encoder_inputs)
    embed = outputs["pooled_output"]  

    if num_classes == 2:
        out = layers.Dense(1, activation='sigmoid')(embed)
        model = tf.keras.Model(inputs=text_input, outputs=out)
        model.compile(Adam(lr=2e-5), "binary_crossentropy", metrics=["binary_accuracy"])
    else:
        out = layers.Dense(num_classes, activation="softmax")(embed)
        model = tf.keras.Model(inputs=text_input, outputs=out)
        model.compile(Adam(lr=2e-5), "sparse_categorical_crossentropy", metrics=["acc"])
    return model

model = get_model_bert(2)
model.save('tttmodel').
```  

> 2021-08-01 03:46:36.957767: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
> WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 85). These functions will not be directly callable after loading.
> WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 85). These functions will not be directly callable after loading.
> INFO:tensorflow:Assets written to: tttmodel/assets
> INFO:tensorflow:Assets written to: tttmodel/assets

Then I tried reload it from disk:

`model = tf.keras.models.load_model('tttmodel')`

The error:

> ----> 1 model = tf.keras.models.load_model('tttmodel')
> 
> /workspace/user-workspace/conda-34805-py37/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
>     210       if isinstance(filepath, six.string_types):
>     211         loader_impl.parse_saved_model(filepath)
> --> 212         return saved_model_load.load(filepath, compile, options)
>     213 
>     214   raise IOError(
> 
> /workspace/user-workspace/conda-34805-py37/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load(path, compile, options)
>     142   for node_id, loaded_node in keras_loader.loaded_nodes.items():
>     143     nodes_to_load[keras_loader.get_path(node_id)] = loaded_node
> --> 144   loaded = tf_load.load_partial(path, nodes_to_load, options=options)
>     145 
>     146   # Finalize the loaded layers and remove the extra tracked dependencies.
> 
> /workspace/user-workspace/conda-34805-py37/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_partial(export_dir, filters, tags, options)
>     763     A dictionary mapping node paths from the filter to loaded objects.
>     764   """
> --> 765   return load_internal(export_dir, tags, options, filters=filters)
>     766 
>     767 
> 
> /workspace/user-workspace/conda-34805-py37/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls, filters)
>     891       except errors.NotFoundError as err:
>     892         raise FileNotFoundError(
> --> 893             str(err) + "\n If trying to load on a different device from the "
>     894             "computational device, consider using setting the "
>     895             "`experimental_io_device` option on tf.saved_model.LoadOptions "
> 
> FileNotFoundError: Op type not registered 'NormalizeUTF8' in binary running on jp-34805-jjj. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
>  If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.

Any solution ?

**Comment by sushreebarsa** [comment]
@yananchen1989 Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
