### ISSUE TITLE
Does TFLite Support conv + LSTM ?

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#51086]
https://github.com/tensorflow/tensorflow/issues/49381 - 

I have raised the above issue for getting data formats,

Here, it is mentioned that N, S, D is only supported format in tflite .

Need, confirmation whether conv + lstm is supported or not in TFLite ?

Using TFLite version 2.4.1.

**Comment by abattery** [comment]
@MeghnaNatraj @renjie-liu could you take a look at this question?

**Comment by renjie-liu** [comment]
Yes, it's supported.

**Comment by pranathibl** [comment]
I would try to create a script, How to know which are supported? Its not listed in tflite operator support .
