### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (digit_capsule_layer_2/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

### ISSUE THREAD

**Issue by yashkarbhari** [tensorflow/tensorflow#51082]
tensorflow - 2.5.0
numpy - 1.21.1
python - 3.8 
CUDA - 11.2
CuDNN - 8.1

Many other issues related to it suggested downgrading the NumPy version to 1.19.5, after downgrading the NumPy version, unfortunately, it still doesn't work.

**Comment by tilakrayal** [comment]
@yashkarbhari ,

 In order to expedite the trouble-shooting process, could you please provide a complete code to reproduce the issue.Thanks!

**Comment by tilakrayal** [comment]
Also Could you please try to test your code again in new virtual environment and let us know if you are facing same issue. Thanks!

**Comment by yashkarbhari** [comment]
> Also Could you please try to test your code again in new virtual environment and let us know if you are facing same issue. Thanks!

I'm currently working in a virtual environment, and it shows the same issue

**Comment by yashkarbhari** [comment]
```
def output_layer(inputs):
    return tf.sqrt(tf.sum(tf.square(inputs), -1) + tf.epsilon())

digit_caps = DigitCapsuleLayer()(squashed_output)
outputs = Lambda(output_layer)(digit_caps)
```

**Comment by yashkarbhari** [comment]
> @yashkarbhari ,
> 
> In order to expedite the trouble-shooting process, could you please provide a complete code to reproduce the issue.Thanks!

```
class DigitCapsuleLayer(Layer):
    # creating a layer class in keras
    def __init__(self, **kwargs):
        super(DigitCapsuleLayer, self).__init__(**kwargs)
        
    
    def build(self, input_shape): 
        # initialize weight matrix for each capsule in lower layer
        self.W = self.add_weight(shape = [2, 6*6*6*32, 16, 8], name = 'weights')
        self.built = True
    
    def call(self, inputs):
        inputs = tf.expand_dims(inputs, 1)
        inputs = tf.tile(inputs, [1, 2, 1, 1])
        # matrix multiplication b/w previous layer output and weight matrix
        inputs = tf.map_fn(lambda x: tf.keras.backend.batch_dot(x, self.W, [2, 3]), elems=inputs)
        b = tf.zeros(shape = [tf.shape(inputs)[0], 2, 6*6*6*32])
        
        # routing algorithm with updating coupling coefficient c, using scalar product b/w input capsule and output capsule
        for i in range(3-1):
            c = tf.nn.softmax(b, dim=1)
            s = tf.keras.backend.batch_dot(c, inputs, [2, 2])
            v = squash(s)
            b = b + tf.keras.backend.batch_dot(v, inputs, [2,3])
            
        return v 
    def compute_output_shape(self, input_shape):
        return tuple([None, 10, 16])

def output_layer(inputs):
    return tf.sqrt(tf.sum(tf.square(inputs), -1) + tf.epsilon())

digit_caps = DigitCapsuleLayer()(squashed_output)
outputs = Lambda(output_layer)(digit_caps)

```

**Comment by tilakrayal** [comment]
@yashkarbhari ,
On running the given code snippet, I am facing an error stating **NameError: name 'Layer' is not defined** Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0cbd77fd94b232b99b09b89504da1884/untitled51082.ipynb).
 
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Thanks!

**Comment by yashkarbhari** [comment]
> @yashkarbhari ,
> On running the given code snippet, I am facing an error stating **NameError: name 'Layer' is not defined** Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0cbd77fd94b232b99b09b89504da1884/untitled51082.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Thanks!

As my work is a research project, I'm not sure if I can show the complete code to reproduce the issue. Also for the **NameError**
Layer is equal to tensorflow.keras.layers.Layer I had imported it earlier as Layer.

**Comment by tilakrayal** [comment]
@yashkarbhari ,

Without the reproducible code, it would be difficult for us to debug the issue. If you cannot simplify the code,please consider posting this issue in Stackoverflow or [tensorflow discussion forum](https://discuss.tensorflow.org/) where there is a large community to help and support each other. Thanks!
