### ISSUE TITLE
RTX30 series: unsupported compute compability for CUDA 9.0

### ISSUE THREAD

**Issue by Neutrino0532** [tensorflow/tensorflow#51088]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from: source 
- TensorFlow version: 1.10
- Python version: 3.6
- Installed using virtualenv? pip? conda?: building, not installed yet
- Bazel version: 0.15
- GCC/Compiler version (if compiling from source): 4.8
- CUDA/cuDNN version: 9.0/7.1.2
- GPU model and memory: RTX3060*4, 64GB

**Describe the problem**

I'm trying to build TensorFlow 1.10 from source, with compute compatibility of 3060 assigned. The building process failed at : 
```
ERROR: /home/yulab/packages_software/tensorflow-r1.10/tensorflow/core/kernels/BUILD:3699:1:error while parsing .d file: /home/yulab/.cache/bazel/_bazel_yulab/0ab03e3c981f656d0173f64ae90fcc89/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/core/kernals/_objs/batch_space_ops_gpu/tensorflow/core/kernels/spacetobatch_functor_gpu.cu.pic.d (No such file or directory)
nvcc fatal: unsupported GPU architecture 'compute_86'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
I manually assigned compute compatibility of 3060 in compile options,  but seems CUDA 9.0 does not support it. And I can't update TF to 2.x as  my application specified TF 1.10. 
Can this error be fixed by changing parameters? Or I have to give up GPU support?

**Comment by sushreebarsa** [comment]
@Neutrino0532 We are not actively supporting TF 1.x , as it is officially considered as end of life ,we recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions ? Could you please have a look at the [link 1](https://www.tensorflow.org/install/gpu?hl=fr), [link 2](https://www.tensorflow.org/install/source) , [link 3](https://www.tensorflow.org/guide/migrate)  for your reference and let us know if it helps ? Thank you!

**Comment by Neutrino0532** [comment]
> @Neutrino0532 We are not actively supporting TF 1.x , as it is officially considered as end of life ,we recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions ? Could you please have a look at the [link 1](https://www.tensorflow.org/install/gpu?hl=fr), [link 2](https://www.tensorflow.org/install/source) , [link 3](https://www.tensorflow.org/guide/migrate) for your reference and let us know if it helps ? Thank you!

I referenced the link 1&2 before compile. The application that uses TensorFlow is developed by another team, so I can't change the code as I do not know it well. So these links didn't help much.

**Comment by sushreebarsa** [comment]
@Neutrino0532 Could you please have a look on this[ link](https://www.tensorflow.org/install/source#gpu),and let us know if it helps? Thanks!

**Comment by Neutrino0532** [comment]
@sushreebarsa I also referenced this link before compile,  to decide the versions of my building tools. I think my building tools are in the correct version, as I have listed in the system information. 
I'd like to discuss if it's possible to assign a lower compute compatibility so that compile will continue, despite the compute compatibility is not supported by my graphics card. And how will the new build behave under 3060 device. Because official builds without assigning compute compatibility will freeze for a long time before graphic cards start to work. Do you have any idea? Thanks!

**Comment by ymodak** [comment]
@Neutrino0532 TF 1.10 is obsolete and out of support window. Have you considered installing tf 1.10 pip packages instead? Also is it possible to try latest TF 1.15 version if not TF 2.X? Thanks!
