### ISSUE TITLE
16x8 quantization mode & TFLite Micro

### ISSUE THREAD

**Issue by kozlova666** [tensorflow/tensorflow#51089]
### 1. System information

- OS Platform Ubuntu 20.04
- TensorFlow installation : pip package
- TensorFlow library 2.5.0

Hi, 
I'm using 16x8 experimental quantization on my model.
I convert my model after I follow instructions on the tflite 16x8 info page, i also set:
converter_fp.inference_input_type = tf.int16
converter_fp.inference_output_type = tf.int16

When I invoke the converted model from Jupyter Notebook everything works fine.

When I transfer the converted model to TFLite Micro then I get the following error:
../src/tensorflow/lite/micro/kernels/fully_connected.cc Hybrid models are not supported on TFLite Micro.
input->type is kTfLiteInt16
filter->type is kTfLiteInt8

Is there a way to make this work? And if not, when is this functionality expected to be available on TFLite Micro?

Thanks and Best Regards,
Alex

**Comment by abattery** [comment]
@kozlova666 could you post this issue at the TFLite micro project(https://github.com/tensorflow/tflite-micro) ?
