### ISSUE TITLE
tf.io.read_file memory leackage

### ISSUE THREAD

**Issue by emenshoff** [tensorflow/tensorflow#51083]
Hello all!

If've found the mem leackage bug in tf.io.read_file  function during my inference testing;

**Describe the current behavior**

This code eats over 30 Gb memory when I read 10000 jpeg images from local nvme drive. And the library does not release memory for data that is not in use anymore. The process eats all available RAM during the intensive file io and then got killed by the OS kernel.

When I changed   string  "img_string = tf.io.read_file(fpath)"  on  "img_string = open(fpath, 'rb').read()" (and remove tf.function decorator) the leackage has gone. 

When i try to read the same images again in the same session, there is no leackage (memory consumption stops on the prevoius value). 

**Describe the expected behavior**
Library should release memory for not used data. I expected some kind of garbage collection. Or, if there is a caching under the hood, I expect to have an option to turn it off.  In current sutuation it is impossible to use this function in inference for intence io operations. 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): the code is based on tf 2.5 documentation, tf.io module.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): built from sources
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
- CUDA/cuDNN version: CUDA Version: 11.2 / CUDNN 8.0.5.39
- GPU model and memory: NVIDIA RTX3080TI 12Gb, NVIDIA RTX2070 8Gb

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
@tf.function
def read_jpg(fpath):
        img_string = tf.io.read_file(fpath)       
        img_tensor = tf.io.decode_jpeg(img_string)      
        return img_tensor

*in cycle of 10000 image reading eats over 30 Gb of RAM

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
There is no logs. The memory leackage was detected in htop utillite.

**Comment by sushreebarsa** [comment]
@emenshoff In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by emenshoff** [comment]
> @emenshoff In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
import os
import sys
import tensoflow as tf

MEDIA_FOLDER = '/media/jpeg_samples/'  # over 300 000 images
SAMPLES_NUM = 10000
fnames = os.path.listdir(MEDIA_FOLDER )

for  fname in fnames [:SAMPLES_NUM ]:
  fpath = os.path.join(MEDIA_FOLDER, fname)
  img_string = tf.io.read_file(fpath)
  img_tensor = tf.io.decode_jpeg(img_string)

**Comment by jung-hunsoo** [comment]
Had the same problem.

In addition, even `content = open(fpath, 'rb').read()` doesn't occur mem leakage, following tf codes are making the mem leakage eventually. For me, `tf.audio.decode_wav(content, ...)` after opning the file occurs mem leakage.

Only a file of 16MB wav consumes over 9GB of GPU mem.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
