### ISSUE TITLE
Cannot split windowed data when batching is used in tf.data.Dataset

### ISSUE THREAD

**Issue by n-chennakeshava** [tensorflow/tensorflow#51084]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I have written custom code 
- Linux 20.04
- TensorFlow installed from binary
- TensorFlow version: 2.3/2.4/2.5
- Python version: 3.7.5
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA RTX 2080/11GB

**Describe the current behavior**

train_dataset = tf.data.Dataset.from_tensor_slices((x, y)).window(2, 1, True).shuffle(buffer_size=tr_s).batch(batch_size)

for x in train_dataset_dataset.take(1):
    a, b = x
    c, d = tf.split(list(a), num_or_size_splits=2, axis=0)

For the above described code, I cannot split up the windowed data. However, when I do not use batching, I can split the windowed data. I get the following error in various flavours when I attempt to do so:

TypeError: '_NestedVariant' object is not iterable

**Describe the expected behavior**

I expect to be able to split up the data, when windowed data is batched

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

funda = tf.data.Dataset.range(7).window(2, 1, True).batch(1)

for x in funda.take(1):
    a, b = x
    c, d = tf.split(list(a), num_or_size_splits=2, axis=0)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sanatmpa1** [comment]
I am able to reproduce the error in `TF 2.5` and `TF nightly`. Please find the [gist here](https://colab.research.google.com/gist/sanatmpa1/5ecdd2cf08cce6cd9f542e1e6ce53c12/51084.ipynb). Thanks!

**Comment by chunduriv** [comment]
@n-chennakeshava,

As per this https://github.com/tensorflow/tensorflow/issues/51084#issuecomment-906724563, Is this still an issue for you? 

The [Dataset.flat_map](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#flat_map) methods can be used to flatten a dataset of windows into a single dataset.

The argument to `flat_map` is a function that takes an element from the dataset and returns a Dataset. `flat_map` chains together the resulting datasets sequentially.

For example, to turn each window into a dense tensor:
```
import tensorflow as tf

dataset = tf.data.Dataset.range(7).window(2, shift=1,
                                          drop_remainder=True)
batched = dataset.flat_map(lambda x:x.batch(2))
for batch in batched:
  print(batch.numpy())
```
Output:

```
[0 1]
[1 2]
[2 3]
[3 4]
[4 5]
[5 6]
```
