### ISSUE TITLE
Parameter description generating weirdly in `tf.keras.metrics.AUC`

### ISSUE THREAD

**Issue by v715** [tensorflow/tensorflow#51097]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/metrics/AUC

## Description of issue (what needs changing):

The description for `num_labels` is generating weirdly:
![Screen Shot 2021-08-02 at 9 30 05 AM](https://user-images.githubusercontent.com/29757116/127869653-5cc9728d-9c29-4de2-9c85-f8452fb1eaa1.png)

**Comment by ymodak** [comment]
This is fixed in tf-nightly version docs. See https://www.tensorflow.org/api_docs/python/tf/keras/metrics/AUC?version=nightly#args
