### ISSUE TITLE
2.6.0rc1 regression: isinstance(layer, Layer) no longer works. Affects: `keras.layers.Wrapper`

### ISSUE THREAD

**Issue by t-kalinowski** [tensorflow/tensorflow#51099]
Hello,
  One of the CI tests in the [R interface to keras](https://github.com/rstudio/keras) surfaced this regression in 2.6.0rc1: 
  `tf.keras.layers.Wrapper` seemingly doesn't work the way it used to.
  
Specifically, this assertion is being raised where it wasn't before:

https://github.com/tensorflow/tensorflow/blob/8406c010e1793f458a9fd5d73404c1a93689bcfc/tensorflow/python/keras/layers/wrappers.py#L50

Tracking this down, it seems this is a minimal example in the change in behavior:
```python
import tensorflow as tf

from tensorflow.python.keras.engine.base_layer import Layer
layer = tf.keras.layers.Dense(1)

isinstance(layer, Layer) # True with 2.5.0, False with 2.6.0rc1
```

**Comment by sushreebarsa** [comment]
@t-kalinowski Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
  Thank you!

**Comment by t-kalinowski** [comment]
Moved issue to https://github.com/keras-team/keras/issues/15056 as requested.

**Comment by sushreebarsa** [comment]
@t-kalinowski Thank you for your response ,closing this issue here as you have moved the issue to  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) .You will get the right help there,Thanks!
