### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'add_slot' 

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#51098]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below):v2.6.0-rc1-12-gb61c987109e 2.6.0-rc1
- Python version:3.8.5 
- Bazel version (if compiling from source):3.7.2
- GCC/Compiler version (if compiling from source):7.5.0 
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
git checkout r2.6
build the source (CPU only), install, generate mnist model, then try to convert it, has issue.

1. install
sudo apt install python3-dev python3-pip
pip install -U --user pip numpy wheel
pip install -U --user keras_preprocessing --no-deps

bazel build //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-2.6.0rc1-cp38-cp38-linux_x86_64.whl

pip install tensorflow-model-optimization

2. generate model: refer to below code
3. convert:
bazel-bin/tensorflow/lite/python/tflite_convert --saved_model_dir mnist_qat_notdocker/float_model/ --output_file oo

error message:
...
  File "/home/tensorflow2/tensorflow/bazel-bin/tensorflow/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

import tempfile
import os

import tensorflow as tf
from tensorflow import keras

# Load MNIST dataset
mnist = keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the input image so that each pixel value is between 0 to 1.
train_images = train_images / 255.0
test_images = test_images / 255.0

# Define the model architecture.
model = keras.Sequential([
  keras.layers.InputLayer(input_shape=(28, 28)),
  keras.layers.Reshape(target_shape=(28, 28, 1)),
  keras.layers.Conv2D(filters=12, kernel_size=(3, 3), activation='relu'),
  keras.layers.MaxPooling2D(pool_size=(2, 2)),
  keras.layers.Flatten(),
  keras.layers.Dense(10)
])

# Train the digit classification model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(
  train_images,
  train_labels,
  epochs=1,
  validation_split=0.1,
)

model.save('mnist_qat_notdocker/float_model')

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@tensorbuffer ,
I was able to execute the given code without any error.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/19559c9ef0d9b598e6d0177e1af90bca/untitled51098.ipynb).Also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/50659) with similar error.It helps.Thanks!

**Comment by tensorbuffer** [comment]
@tilakrayal Thanks for the quick response. The problem happens when you convert, your link does not have the convert step.
Yes I have searched and read that issue you referred, in that case I think a custom OP is used, different than mine.
I also tried to do a new conda environment and do everything there (checkout source, build pip package, install, run python to save model and convert). I had the same issue with branch 2.6, however 2.5 branch works. So I do believe there's some problem.

**Comment by PINTO0309** [comment]
Using the Python API seems to convert without problems. I think it might be a problem with tflite_convert built with Bazel.
https://colab.research.google.com/drive/1uuAl1BP8v1R1xhcOyBIDyh9nkO8AW6xD?usp=sharing
```python
converter = tf.lite.TFLiteConverter.from_saved_model('mnist_qat_notdocker/float_model')
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
with open('mnist_qat_notdocker/float_model/model_float32.tflite', 'wb') as w:
    w.write(tflite_model)
```

**Comment by tensorbuffer** [comment]
Thanks. Ok I will try that. I remember that with python convert, I can set attributes like inference type, while in tflite_convert command line there's no such option. Wondering if they are the same.

**Comment by PINTO0309** [comment]
I remember that command line tools were deprecated a long time ago. They are probably rarely maintained.

**Comment by ymodak** [comment]
As mentioned by @PINTO0309 Python API is recommended for TF Lite converter,  command line tool support basic model conversion.
https://www.tensorflow.org/lite/convert
Feel free to reopen if running into issues using Python API for conversion. Thanks!

**Comment by Aida-yy** [comment]
I have same problem, in TF2.6. But, I fix it just need append
from tensorflow.keras import Model

hope it's useful for you.
