### ISSUE TITLE
How to collect code coverage of C++ code when running Python tests?

### ISSUE THREAD

**Issue by sturmianseq** [tensorflow/tensorflow#51091]
I am trying to figure out the way to get the code coverage of C++ code for tests written in Python. I know that `coverage` is the package to measure code coverage of Python code for tests that run in Python.
Also, it appears to me that `bazel` is the build system for C++ projects, and `bazel coverage` can collect the C++ code coverage for C++ tests.

If there is anything wrong with my previous findings, please feel free to point out!

I am currently looking for the way to collect the code coverage of C++ when running Python code. Is there any potential ways? Thanks!

**Comment by sturmianseq** [comment]
I have tried some commands like this after compiling tensorflow from source:
```
export flags="--config=opt --collect_code_coverage=true"
bazel test ${flags} tensorflow/python/kernel_tests:softmax_op_test
```
The tests under `tensorflow/python/kernel_tests` are indeed python tests.
However, an issue arise:
```
FAIL: //tensorflow/python/kernel_tests:softmax_op_test (see SOME_PATH_HERE/288208e8edcff60b9143f8b7da1d43aa/execroot/org_tensorflow/
bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/softmax_op_test/test.log)
ERROR: tensorflow/python/kernel_tests/BUILD:2467:1: output 'tensorflow/python/kernel_tests/softmax_op_test/coverage.dat' was not created
ERROR: tensorflow/python/kernel_tests/BUILD:2467:1: not all outputs were created or valid
```

Am I running the correct command for coverage collection? Thanks!

**Comment by Saduf2019** [comment]
@sturmianseq 
Can you please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/18839) and let us know.

**Comment by sturmianseq** [comment]
Thanks for your reminding!
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): source
- TensorFlow version: Tensorflow 1.14.0 (branch/tag1.14.0, from git)
- Python version: 3.7
- Installed using virtualenv? conda
- Bazel version (if compiling from source): Bazel 0.24.1 (as indicated in https://www.tensorflow.org/install/source?hl=uk for tf1.14.0)
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: N/A (only CPU version, without CUDA support)
- GPU model and memory: N/A (only CPU version, without CUDA support)

**Comment by sturmianseq** [comment]
I have also tried commands from https://github.com/tensorflow/tensorflow/issues/46477 (`bazel coverage -s --instrument_test_targets --coverage_report_generator=@bazel_tools//tools/test:coverage_report_generator --coverage_support=@bazel_tools//tools/test:coverage_support --collect_code_coverage --jobs 5 //tensorflow`), but it simply didn't work.

**Comment by Saduf2019** [comment]
> Thanks for your reminding!
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
> * TensorFlow installed from (source or binary): source
> * TensorFlow version: Tensorflow 1.14.0 (branch/tag1.14.0, from git)
> * Python version: 3.7
> * Installed using virtualenv? conda
> * Bazel version (if compiling from source): Bazel 0.24.1 (as indicated in https://www.tensorflow.org/install/source?hl=uk for tf1.14.0)
> * GCC/Compiler version (if compiling from source): 4.8.5
> * CUDA/cuDNN version: N/A (only CPU version, without CUDA support)
> * GPU model and memory: N/A (only CPU version, without CUDA support)

Can you confirm if you have upgraded tf version as there is no active support for 1.x now.

**Comment by BiophiliaSWDA** [comment]
I am soory. I was wondering if there is a good solution to this particular problem.
