### ISSUE TITLE
Can't save custom layers to .h5 file !

### ISSUE THREAD

**Issue by jiayugedede** [tensorflow/tensorflow#51096]
<em>Can't save custom layers to .h5 file !</em>

**Can't save !**
I use tensorflow 2.4.1, this code works very well, but it can't save to .h5 file. I have tried Sequential() method, but it not working. I want to ask which approch should I adopt it. I have add get_config params, and which not working in my network that is very puzzle me. I don't know what cause this problem, can somebody tell me, thank you very much.
Please note that `tf.keras` code was moved entirely to
```
class MultiSpectralAttentionLayer(layers.Layer):
def __init__(self, reduction=16, freq_sel_method='top16'):
    super(MultiSpectralAttentionLayer, self).__init__()
    self.reduction = 16
    self.freq_sel_method = freq_sel_method

def build(self, input_shape):
    _, h, w, c = input_shape
    self.channel = int(c)
    self.reduction = self.reduction
    self.fc1 = layers.Dense(self.channel / self.reduction, use_bias=True, activation='relu')
    self.fc2 = layers.Dense(self.channel, use_bias=True, activation='sigmoid')
    self.reshapeTensor = tf.keras.layers.Reshape((1, 1, c))
    self.mapper_x, self.mapper_y = self.get_freq_indices(self.freq_sel_method)
    self.dynamic_weight = tf.Variable(self.get_dct_filter(h, w, self.mapper_x, self.mapper_y, channel=c))
    self.mapper_x = [temp_x * (h // 7) for temp_x in self.mapper_x]
    self.mapper_y = [temp_y * (2 // 7) for temp_y in self.mapper_y]

    super().build(input_shape)

def get_freq_indices(self, methods):
    assert methods in ['top1', 'top2', 'top4', 'top8', 'top16', 'top32',
                       'bot1', 'bot2', 'bot4', 'bot8', 'bot16', 'bot32',
                       'low1', 'low2', 'low4', 'low8', 'low16', 'low32']
    num_freq = int(methods[3:])

    if 'top' in methods:
        all_top_indices_x = [0, 0, 6, 0, 0, 1, 1, 4, 5, 1, 3, 0, 0, 0, 3, 2, 4, 6, 3, 5, 5, 2, 6, 5, 5, 3, 3, 4, 2,
                             2,
                             6, 1]
        all_top_indices_y = [0, 1, 0, 5, 2, 0, 2, 0, 0, 6, 0, 4, 6, 3, 5, 2, 6, 3, 3, 3, 5, 1, 1, 2, 4, 2, 1, 1, 3,
                             0,
                             5, 3]
        mapper_x = all_top_indices_x[:num_freq]
        mapper_y = all_top_indices_y[:num_freq]

    elif 'low' in methods:
        all_low_indices_x = [0, 0, 1, 1, 0, 2, 2, 1, 2, 0, 3, 4, 0, 1, 3, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 1,
                             2,
                             3, 4]

        all_low_indices_y = [0, 1, 0, 1, 2, 0, 1, 2, 2, 3, 0, 0, 4, 3, 1, 5, 4, 3, 2, 1, 0, 6, 5, 4, 3, 2, 1, 0, 6,
                             5,
                             4, 3]

        mapper_x = all_low_indices_x[:num_freq]
        mapper_y = all_low_indices_y[:num_freq]

    elif 'bot' in methods:
        all_bot_indices_x = [6, 1, 3, 3, 2, 4, 1, 2, 4, 4, 5, 1, 4, 6, 2, 5, 6, 1, 6, 2, 2, 4, 3, 3, 5, 5, 6, 2, 5,
                             5,
                             3, 6]
        all_bot_indices_y = [6, 4, 4, 6, 6, 3, 1, 4, 4, 5, 6, 5, 2, 2, 5, 1, 4, 3, 5, 0, 3, 1, 1, 2, 4, 2, 1, 1, 5,
                             3,
                             3, 3]
        mapper_x = all_bot_indices_x[:num_freq]
        mapper_y = all_bot_indices_y[:num_freq]
    else:
        raise NotImplementedError
    return mapper_x, mapper_y

def get_dct_filter(self, tile_size_x, tile_size_y, mapper_x, mapper_y, channel):
    dct_numpy_filter = np.zeros(shape=(tile_size_y, tile_size_x, channel), dtype=np.float32)
    c_part = channel // len(mapper_x)

    for i, (u_x, u_y) in enumerate(zip(mapper_x, mapper_y)):
        for t_x in range(tile_size_x):
            for t_y in range(tile_size_y):
                dct_numpy_filter[t_y, t_x, i * c_part: (i + 1) * c_part] = self.build_filter(t_x, u_x, tile_size_x) * \
                                                                           self.build_filter(t_y, u_y, tile_size_y)
    return dct_numpy_filter


def build_filter(self, pos, frequency, POS):
    result = np.cos(np.pi * frequency * (pos + 0.5) / POS) / np.sqrt(POS)
    if frequency == 0:
        return result
    else:
        return result * np.sqrt(2)


def get_config(self):
    base_config = super(MultiSpectralAttentionLayer, self).get_config()
    config = {
        "reduction": self.reduction,
        "freq_sel_method": self.freq_sel_method,
    }
    return dict(list(base_config.items()) + list(config.items()))


@tf.function
def call(self, inputs, training=None):
    x = inputs * self.dynamic_weight
    result = tf.math.reduce_sum(x, axis=[1, 2], keepdims=True)
    x = self.fc1(result)
    x = self.fc2(x)
    x = self.reshapeTensor(x)
    return inputs * x
```

**I use the following code to inference images, but it not working.**

```
    def load_trained_model():
    _custom_objects = {
    "SeBlock" : SeBlock,
    "MultiSpectralAttentionLayer": MultiSpectralAttentionLayer,
}
    model_name = r"F:\log\ablation\model.01-3.4231-1.h5"  
    function_model = load_model(model_name, custom_objects=_custom_objects)
    print('model load success')
    return function_model
```

The error message is " init() got an unexpected keyword argument 'name' ". I have assigned names to this custom layers each times.

The code is re-implement FcaNet -->**https://github.com/cfzd/FcaNet/blob/aa5fb63505575bb4e4e094613565379c3f6ada33/model/layer.py#L29**.

**Comment by sushreebarsa** [comment]
@jiayugedede Could you please refer to the [link](https://www.tensorflow.org/guide/keras/save_and_serialize) having documentation on save and load keras models and these similar issues[ link1](https://stackoverflow.com/questions/64337087/typeerror-init-got-an-unexpected-keyword-argument-name-when-loading-a-m), [link2](https://stackoverflow.com/questions/62280161/saving-keras-models-with-custom-layers) mentioned  in stackoverflow and let us know if it helps ? Thank you!

**Comment by jiayugedede** [comment]
OK， I have a try.

**Comment by sushreebarsa** [comment]
@jiayugedede Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by jiayugedede** [comment]
> @jiayugedede Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
> To know more see;
> https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
> Thank you!

Thank you, your suggestion sloved my problem, thank you very much.

**Comment by sushreebarsa** [comment]
@jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!

**Comment by jiayugedede** [comment]
> @jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!

Yes, you can close this issue, your suggestion is working to me.

**Comment by jiayugedede** [comment]
> @jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!

Thank you very much!

**Comment by jiayugedede** [comment]
> @jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!



> @jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!

> @sushreebarsa Yes, you can close this issue, your suggestion is working to me. Thank you very much.

**Comment by jiayugedede** [comment]
> @jiayugedede Can you please let us know if we can close this issue as it has been resolved? Thanks!

Yes, you can close this issue, your suggestion is working to me. Thank you very much.
