### ISSUE TITLE
Large RNN graphs, incredibly slow graph creation and step time...

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#511]
When I build a large seq2seq RNN graph (i.e., 3000 timesteps encoder, and 100 time steps decoder), both the graph construction and step time is insanely slow.

For example, using approx 3000 timesteps of stacked 4 layers of GRUs (in a seq2seq model w/ attention), we get something like this:

*** graph creation time ***
create_encoder graph time 77.442740
create_decoder graph time 7.298214
create_loss graph time 0.934293
create_optimizer graph time 349.426908
create_model graph time 489.119399

create_optimizer is the part where i call something like this (pulled from the tutorial):
  def create_optimizer(self):
    start_time = time.time()

    params = tf.trainable_variables()

    self.gradient_norms = []
    self.updates = []
    opt = tf.train.GradientDescentOptimizer(0.001)

    gradients = tf.gradients(self.losses, params)
    clipped_gradients, norm = tf.clip_by_global_norm(gradients, self.max_gradient_norm)

    self.gradient_norms.append(norm)
    self.updates.append(opt.apply_gradients(
        zip(clipped_gradients, params), global_step=self.global_step))

    print('create_optimizer graph time %f' % (time.time() - start_time))

*** step time ***
step_time: 142.356251001

When I run nvidia-smi while the graph is computing , the utilization is something like 12% ... definitely something wrong...

In my personal framework (not TF), creating a graph of equal size takes approx 2 secs (as opposed to TF almost 8 mins) and the step time is less 4 seconds (as opposed to TF 2 mins).... something really weird is going on.

I wasn't able to profile / debug it too much (are there public tools for that? i cant find anything on tensorboard). also, is there a command i can run to confirm how many weights i have (and the dimensions and the device location of the variables).

I've confirmed with the tensorboard and log_device_placement=True, and seems like most of the graph is in the GPU (except for embedding layers).

If you want a link to my graph, send me an email.

Thanks All!

**Comment by mrry** [comment]
This is a known issue for large unrolled RNNs in TensorFlow, and we are working on (currently experimental) functionality to express loops directly in the graph, to avoid creating a very verbose representation for those models.

Out of interest, is the step time you report for the first step, or a subsequent step? There is a non-trivial amount of setup work per node in the graph, but this only affects the first step. I would expect it to speed up for subsequent steps.

**Comment by wchan** [comment]
1st step time: 144.380403996
2nd step time: 30.2505180836

still too slow... my framework is around 4 seconds (using even bigger LSTM nodes, so something is definite wrong here)

**Comment by wchan** [comment]
Is there a way to profile my graph? I want to see which sections of the graph corresponds to what part of the runtime.

**Comment by wchan** [comment]
FYI... through trial and error, it seems like the encoder is the slower part, which is weird, because I'm passing in the sequence_length and there should be dynamic computation on that part.....

**Comment by wchan** [comment]
FYI... more debug info, if I use an encoder length of say 256 (1/10 of 2560) the step time reduces to 1 second! woohoo! this suggests massive inefficiency in the attention mechanism... my bet would be the reduction code across multiple layers... gonna debug it later... any advice on the profiling code?

**Comment by mrry** [comment]
Right now, we don't have TensorFlow-specific profiling tools available, but a sampling profiler (such as [`pprof`](http://goog-perftools.sourceforge.net/doc/cpu_profiler.html)) should give enough information to point you in the right direction.

**Comment by wchan** [comment]
at each timestep of the backprop of the RNN chain, does it create a new dE/dW and then the optimizer does a reduction? or does the network write to the exact same dE/dW and no reduction is needed? i think this is part of the slowdown.

**Comment by ludimagister** [comment]
Can you try to use one of those two (currently not on by default) gradient accumulation methods and see if this improves steptime:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_test.py#L204
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_test.py#L231

Also, for experimentation I would recommend to use a small batch_size=1 and make it bigger when everything works to keep memory down.

Overall, we are fully aware that long unrolled RNNs/LSTMs are still problematic in TensorFlow, we are working on making it better.

**Comment by wchan** [comment]
@ludimagister , not running the test because even the fprop alone is insanely slow compared to my framework (i.e., I do forward only pass and its still an order of magnitude behind). Right now I'm writing a monolithic RNN Op that does the entire RNN sequence (w/ dynamic computation but not dynamic memory) in 1 block.

**Comment by ebrevdo** [comment]
Lol @william.  How'd I know you were going to do this.

**Comment by wchan** [comment]
@ebrevdo cant be that much harder than DistBelief right? Actually, kinda stuck... if my Tensor is in GPU memory, how can I get the value in CPU memory? can't find any API function available in tensor.h or in Eigen Tensor for that, i.e., for the sequence_length to do the dynamic compute.

**Comment by ebrevdo** [comment]
You mark it as a host input when creating your kernel.  See I think my
ReverseSequence kernel.  That has a bunch of tricks.  You can also just
register your kernel as cpu only for now. Everything will stay on cpu.

**Comment by wchan** [comment]
thanks for the pointer! no, i need GPU for sure... i dont have google infrastructure, definitely need GPUs :p

**Comment by ebrevdo** [comment]
OK FYI though it's not clear that you can work with multiple gpus in one
kernel. I may be wrong.  Derek or Sherry can probably say more.  Depending
how you need to split data you may be limited with the current
infrastructure to tower-like computation.

**Comment by LeavesBreathe** [comment]
Bit late to this discussion, but I too am doing seq2seq in tf [here](https://github.com/LeavesBreathe/Project_RNN_Enhancement).

I don't want to beat a dead horse, but I have slow step times, though my compilation isn't too bad. I currently run 2 layers of 1536 units (GRU). However, the biggest hurdle by far is the memory.

When I run these two layers, each of them on a 980 TI, I get 99% usage, and I'm overclocking my GPUs. So I feel that the GPU is being used. However the usage percent is sinusoidal with a average of 50%, but I also had the same experience in Theano.

But because of memory usage, I can only use a batch size of 16 whereas in theano I could use a batch size of 256 easily. And it is the batch size that makes tf very slow for me. 

I know you guys are working hard on improving the memory allocator. I'm very appreciative of it. Just wanted to give my 2 cents.

**Comment by wchan** [comment]
i've coded up a monolithic gru op, it compiles but im getting a really weird dynamic link error when I do the python import statement for just "import tensorflow as tf":

ImportError: /home/wchan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _ZN5Eigen8internal14TensorExecutorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIfLm1ELi1ElEELi1EEEKNS_19TensorCwiseBinaryOpINS0_20scalar_difference_opIKfEEKNS7_INS0_17scalar_product_opIS9_S9_EEKNS3_INS4_IS9_Lm1ELi1ElEELi1EEESF_EESH_EEEENS_9GpuDeviceELb1ELb0EE3runERSL_RKSM_

Anyone see something like that before? I'm guessing this must be related to the Eigen::Tensor?

impl path: https://github.com/wchan/tensorflow/blob/master/tensorflow/core/kernels/gru_op.cc

**Comment by wchan** [comment]
// h[t] = z[t] .* h[t - 1] + (1 - z[t]) .* g[t]
      dz.vec<float>().device(ctx->eigen_device<Device>()) =
          dh.vec<float>() * h_prev->vec<float>() -
          dh.vec<float>() * g.vec<float>();

      dh_prev.vec<float>().device(ctx->eigen_device<Device>()) =
          dh_prev.vec<float>() + dh.vec<float>() * z.vec<float>();

      dg.vec<float>().device(ctx->eigen_device<Device>()) =
          dh.vec<float>() * (z.vec<float>().constant(1.0f) - z.vec<float>());


am I allowed to do something like that when Device == GpuDevice

_ZN5Eigen8internal14TensorExecutorIKNS_14TensorAssignOpINS_9TensorMapINS_6TensorIfLm1ELi1ElEELi1EEEKNS_19TensorCwiseBinaryOpINS0_20scalar_difference_opIKfEEKNS7_INS0_17scalar_product_opIS9_S9_EEKNS3_INS4_IS9_Lm1ELi1ElEELi1EEESF_EESH_EEEENS_9GpuDeviceELb1ELb0EE3runERSL_RKSM

notice the “Tensor” reference and “GpuDevice” in the name mangling … I’m guessing this must be a template error, and the GpuDevice specialization failed

**Comment by wchan** [comment]
ok... I think those are the problem, is there an example I can follow to add a custom CwiseBinaryOp for Eigen::Tensor that will work on the GPU, or should I wrote my own CUDA kernel? What's the proper way to impl this?

**Comment by ebrevdo** [comment]
You should be able to use Eigen ops with the gpu device. This seems like a
bug with user op declarations in the build rules.

**Comment by wchan** [comment]
FYI, I've got a working implementation for "Gru" and "GruCell" .. GruCell is 1 timeslice monolithic op, while "Gru" operates on a sequence (dynamic computation). GruCell is roughly 20% faster per step (on TITAN X), and both ops have massive edge in the graph creation time (esp if you unroll large timesteps). The code is by no means optimized at this point (using 6 matrices atm, proper impl should concat them and use 3 matrices), and lots of code cleanup -- but if anyone needs/wants to try the code, give me a ping and I can point you to the right direction.

I'll work w/ @ebrevdo to get this pushed to upstream "soon", but atm, I have other priorities. Also, not in the mood of learning how to write tests : p

**Comment by ludimagister** [comment]
That sounds great. Please send to @evrevdo or me and we'll get this in. As
of today (I think) we also accept outside contributions so that's another
option.

**Comment by vrv** [comment]
Assigning to @ebrevdo since he's done some work recently on this.

**Comment by wchan** [comment]
I wrote a bunch of monolithic ops for the RNNs, is there interest for me to
push this upstream? I can work w/ Eugene on this.

--
William Chan
Carnegie Mellon University
(650) 450-9455
williamchan.ca

**Comment by ebrevdo** [comment]
Have you tried dynamic_rnn for comparison?

**Comment by wchan** [comment]
i haven't... but looking at the source, it still won't fix the memory issue
(i.e., for long sequences > 2000 timesteps)? i.e., the monotholic op is
much more efficient in the memory, (at least until TF supports optimization
by merging ops?)

--
William Chan
Carnegie Mellon University
(650) 450-9455
williamchan.ca

**Comment by ebrevdo** [comment]
Try it. Should solve a lot of memory issues.

**Comment by carpedm20** [comment]
Thanks, 45197e07c0dc410bde203462992841b457e0f61c looks great!

**Comment by alquraishi** [comment]
It will be awesome to get this working but I've run into multiple problems which I suspect are bugs. I opened a separate issue here #1306

**Comment by ebrevdo** [comment]
That bug should be fixed at HEAD

**Comment by girving** [comment]
@ebrevdo: Is this resolved?

**Comment by ebrevdo** [comment]
Yes, using either functions.Defun or dynamic_rnn.

**Comment by lightingghost** [comment]
Hi @ebrevdo ,

I have tried `dynamic_rnn`. But it is still ultra slow when building the graph

My model is 200~300 steps encoder and 30 steps decoder with attention,

The mini model of 100 steps encoder and 30 steps decoder takes 400s to build.

I cannot even build the full model on my machine (16 G Memory) due to out of memory, while the same model without attention using mxnet takes approx 20% of the memory.

Could you please provide any solution to that?

Thanks all

**Comment by ebrevdo** [comment]
Can you post a gist with your model so we can look at it and figure out
what's slowing it down?

**Comment by lightingghost** [comment]
Hi @ebrevdo ,

Thank you for helping me out. The code was shown in 

[](https://bitbucket.org/lightingghost/sent2mat)

with the model defined in seq2seq.py

**Comment by ebrevdo** [comment]
I see.  For now you should write your own encoder using tf.nn.dynamic_rnn.
For the decoder we are working on something equivalent to dynamic_rnn.

**Comment by lightingghost** [comment]
Oh, Thanks @ebrevdo. I will have a try on that.

**Comment by LeavesBreathe** [comment]
@lightingghost just to comment on this as I have heavily worked on seq2seq in tensorflow. I have found that I need at minimum 24gb of ram to have a working model of the timesteps you're describing. The demands go up even further to 32 or 64gb for large sized models (2048 sizes). Your 16gb limitation seems normal to me.

**Comment by lightingghost** [comment]
@LeavesBreathe Thanks for letting me know that. Already ordered more RAMs on BestBuy =.=

**Comment by qingzew** [comment]
```python
with tf.device('/cpu:0'):
            print('create encoder...')
            with tf.variable_scope("lstm_encoder") as scope:
                initializer = tf.random_uniform_initializer(-1., 1.)
                lstm_cell = tf.nn.rnn_cell.LSTMCell(self.hidden_units, initializer = initializer, state_is_tuple = True)
                # lstm_cell = tf.nn.rnn_cell.LSTMCell(self.hidden_units, initializer = initializer)
                if self.is_training and self.keep_prob < 1:
                    lstm_cell = tf.nn.rnn_cell.DropoutWrapper(lstm_cell, output_keep_prob = self.keep_prob)

                cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self.num_layers, state_is_tuple = True)
                # cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self.num_layers)

                initial_state = cell.zero_state(batch_size, tf.float32)

                encoder_outputs, _ = tf.nn.rnn(cell, inputs, initial_state = initial_state, sequence_length = early_stops)

                # lstm = tf.add_n(encoder_outputs, scope.name)
                # early_stops = tf.cast(early_stops, tf.float32)
                # early_stops = tf.reshape(early_stops, [batch_size, 1])
                # lstm = tf.div(lstm, early_stops)


            print('create decoder...')
            with tf.variable_scope("lstm_decoder") as scope:
                initializer = tf.random_uniform_initializer(-1., 1.)
                # lstm_cell = tf.nn.rnn_cell.LSTMCell(self.hidden_units, initializer = initializer)
                lstm_cell = tf.nn.rnn_cell.LSTMCell(self.hidden_units, initializer = initializer, state_is_tuple = True)
                if self.is_training and self.keep_prob < 1:
                    lstm_cell = tf.nn.rnn_cell.DropoutWrapper(lstm_cell, output_keep_prob = self.keep_prob)

                # cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self.num_layers)
                cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * self.num_layers, state_is_tuple = True)

                state = cell.zero_state(batch_size, tf.float32)

                weight_input = self._variable_with_weight_decay('weight_context', [self.hidden_units, 1])
                weight_context = self._variable_with_weight_decay('weight_input', [cell.state_size[0][0], 1])

                for x in range(num_steps):
                    if x > 0:
                        tf.get_variable_scope().reuse_variables()
                    # tanh
                    w = []
                    for y in range(num_steps):
                        w.append(tf.tanh(tf.matmul(encoder_outputs[y], weight_input) + tf.matmul(state[0][0], weight_context)))

                    # softmax
                    w = tf.reshape(tf.pack(w), [num_steps])
                    w = tf.exp(w - tf.reduce_max(w))
                    w /= tf.reduce_sum(w)

                    input_x = tf.zeros_like(encoder_outputs[0])
                    for y in range(num_steps):
                        input_x += encoder_outputs[y] * w[y]

                    _, state  = cell(input_x, state)

```

I write a endocer-decoder, the decoder cost too much time,  still can't run, and there's no mistakes, anyway to modify this decoder?

**Comment by jakob-grabner** [comment]
@qingzew you could try to use `tf.nn.dynamic_rnn` instead of `tf.nn.rnn`. I found that graph creation is way faster with dynamic_rnn. 

The only difference is the input format. dynamic_rnn expects the input as a single tensor instead of a list of tensors. The input format as described in the documentation: 

```
If time_major == False (default), this must be a tensor of shape:
        `[batch_size, max_time, input_size]`.
      If time_major == True, this must be a tensor of shape:
        `[max_time, batch_size, input_size]`.
```

**Comment by qingzew** [comment]
@jakob-grabner  yes, I saw this function,  it can be used in encoder,  but I don't think it can be used in decoder, maybe this [Dynamic_RNN](https://github.com/qingzew/Dynamic_RNN_Tensorflow/blob/master/LSTM/LSTM.py) would be ok

**Comment by LeavesBreathe** [comment]
@jakob-grabner  is `dynamic_rnn` only faster in graph creation or actual computation time? It doesn't seem that it should be

**Comment by wchan** [comment]
faster graph creation, slightly slower in computation

**Comment by jakob-grabner** [comment]
@LeavesBreathe definitely faster graph creation time, not sure about computation times.

**Comment by LeavesBreathe** [comment]
@wchan  thanks for your response -- Also big thanks for your attempts to make the LSTM faster. Really looking forward to that!

@jakob-grabner  thanks for getting back but I'm pretty sure as @wchan stated its slower on comp time.

**Comment by ebrevdo** [comment]
by slower, william meant 2-3% (if that)

**Comment by LeavesBreathe** [comment]
okay good to know thanks @ebrevdo

**Comment by doubler** [comment]
I found tf.nn.dynamic_rnn is much slower than tf.nn.rnn in tensorflow_serving inference.
Using tf.__version__ == 0.9.0

**Comment by ebrevdo** [comment]
Indeed, for inference you probably want to run some small fixed number of
time steps at a time yourself (since you need to decide when to stop based
on your business logic); in which case you just want to build a tf.nn.rnn
with that small number of inputs.
