### ISSUE TITLE
Fail to export model with exporter with distributed session

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#5110]
We have try `exporter` and `signature` to export our TensorFlow models. The code works in standalone mode but not in distributed mode.

We got `InvalidArgumentError` when calling `exporter.Exporter(saver).init()`. It asks to feed the placeholder but it's not training process and I just want to get the `op`'s name to pass as model's signatures. The error log looks like this.

![screen shot 2016-10-21 at 17 27 17](https://cloud.githubusercontent.com/assets/2715000/19593672/52ddc706-97b4-11e6-8b5e-f278d2197dc2.png)

Do anyone has tried to export models with distributed session? Here is my sample code if it helps.

![screen shot 2016-10-21 at 17 28 22](https://cloud.githubusercontent.com/assets/2715000/19593691/67092bf8-97b4-11e6-872a-e6b4daf05005.png)
### Environment info

Operating System: Ubuntu 16.04
CUDA and cuDNN: Not install
TensorFlow version: 0.11.0rc0

**Comment by asimshankar** [comment]
@tobegit3hub : Is it possible to provide a minimal reproducible example. As text instead of a screenshot so we can copy the exact code used ourselves?

With some more context we might be able to provide a useful diagnosis. The error log and snippet you've provided are just a little shy of being very useful. For example, it's not clear to me which line corresponds to task.py, line 120. And also, would be good to have the stacktrace of the InvalidArgumentException.

Do chime in with a small, reproducible example that we can run. Thanks!

**Comment by tobegit3hub** [comment]
Thanks for quick response. @asimshankar 

I have moved the code into this project, <https://github.com/tobegit3hub/distributed_tensorflow> .

You can follow the README to run in standalone and distributed mode. It's easy to re-produce the issue. If it's the problem of our code, please let me know and any feedback is really appreciated.

**Comment by asimshankar** [comment]
@tobegit3hub : Can you trim your code down considerably so that it focuses on this problem?Currently, there is a lot of code there that seems unrelated to the problem at hand. It would also be nice to factor out the common parts between distributed and standalone versions so its easier to see what the two share and what they do not.

**Comment by tobegit3hub** [comment]
Thanks @asimshankar . 

Of course I can trim it down and refactor the code. But it's only ~200 lines and I have tried to make it easy to read and runnable. 

You can run the `standalone` part to make sure the `exporter` will work with this model. And run the similar code of `distributed` part and checkout the error message.

**Comment by aselle** [comment]
@concretevitamin , @wicke, do you have any insight on if this could be caused by the new checkpoint format (it's 11.0rc0 and it was in by this time). Could it be using placeholders in the signature? The mnist_export.py in our example uses an Identity tensor.

**Comment by concretevitamin** [comment]
It's not related to the checkpoint format, I'll say.  (Biggest reason being 0.11rc0 does not have complete support for V2.)  Adding @sukritiramesh @nfiedel to see if this is something obvious in the Exporter.

**Comment by tobegit3hub** [comment]
I have tried with 0.12.0 and it failed in the same way. The I trace and log the exception like this.

```
ipdb> pp e
InvalidArgumentError()
ipdb> pp e.error_code
3
ipdb> pp e.message
u'You must feed a value for placeholder tensor \'Placeholder_2\' with dtype float\n\t [[Node: Placeholder_2 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:master/replica:0/task:0/cpu:0"]()]]'
ipdb> e.op
<tensorflow.python.framework.ops.Operation object at 0x7ff87957a050>
```

I was trying to export the generic signature and not sure why it need to feed the placeholder. It's caused by this line of code while it works in standalone mode.

```
exporter.generic_signature({"keys": keys_placeholder,
                                                  "X": X})
```

**Comment by tobegit3hub** [comment]
Thanks for @asimshankar @aselle and @concretevitamin .

It's easy to reproduce. Can anyone help to verify the issue or give the proper example for distributed TensorFlow application to export the mode?

**Comment by concretevitamin** [comment]
Pinging @sukritiramesh

**Comment by tobegit3hub** [comment]
There are two problems we need to fix for this code and now it works.

The placeholder problem is similar to http://stackoverflow.com/questions/38825741/running-distributed-tensorflow-with-invalidargumenterror-you-must-feed-a-value?rq=1 . We should not use `summary_op` in `Supervisor` when using placeholder(not sure if we need to fix this later). Now it doesn't complain about `You must feed a value for placeholder tensor` with this code.

```
        sv = tf.train.Supervisor(is_chief=(task_type == "master"),
                                 logdir=FLAGS.checkpoint_path,
                                 init_op=init_op,
                                 summary_op=None,
                                 saver=saver,
                                 global_step=global_step,
                                 save_model_secs=60)
``` 

But I still have the problem about `Graph is finalized and cannot be modified`. It's related to https://github.com/tensorflow/tensorflow/issues/5439 witch can be fixed by defining `exporter` and any other `op` before `Supervisor`.

Thanks for the help from Github issues and StackOverflow. Still need to improve the document and example code for any other TensorFlow developers.
