### ISSUE TITLE
TFLite flex delegate on x86_64 failed to link

### ISSUE THREAD

**Issue by Kipsora** [tensorflow/tensorflow#51115]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 4.1.0
- GCC/Compiler version (if compiling from source): 11.1.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: RTX 2080Ti 11GB

**Describe the problem**

I am trying to compile the C++ API of flex delegate on x86_64 desktop but failed due to link errors (see below). But if i compile the same target with option `--config=android_arm64` everything runs smoothly. I am wondering if the C++ API of flex delegate is supported and if it is how to avoid the link errors. The log file is attached below. Please kindly check it. Thanks!

Compiling

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build --compilation_mode=opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --experimental_ui_max_stdouterr_bytes=1073741819 -- //tensorflow/lite/delegates/flex:libtensorflowlite_flex.so`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[tflite_flex.log](https://github.com/tensorflow/tensorflow/files/6919287/tflite_flex.log)

**Comment by abattery** [comment]
@thaink could you take a look at this?

**Comment by thaink** [comment]
Can you add `--config=monolithic` and try again.
Beside, If you are building for x86_64 PC, it is true not to add `--config=android_arm64`.
However for Android, you should use `--config=android_arm64` or `--config=android_x86_64` depends on the target platform.

**Comment by Kipsora** [comment]
Yeah, adding `--config=monolithic` works for me. Thanks!
