### ISSUE TITLE
ValueError(Missing predictions) in tf.estimator

### ISSUE THREAD

**Issue by waynamigo** [tensorflow/tensorflow#51120]
I defined the two spec for eval and prediction with tf.estimator, My goal is to get **predictions**'s content, like[1,1,1], not printed like "Tensor(shape=(),dtype=float32)"
- here is the code
```python
def model_fn():
    ...
    predictions = tf.argmax(logits,axis=-1,name="pred_node") 
    pred = {'pred':prediction}
    acc = tf.metrics.accuracy(labels,predictions)
    eval_metrics={"acc":acc}
    if mode == tf.estimator.ModeKeys.EVAL:
        eval_spec = tf.estimator.EstimatorSpec(
            mode=mode,
            loss=total_loss,
            eval_metrics=eval_metrics,
            scaffold_fn=scaffold_fn
        )
    if mode == tf.estimator.ModeKeys.PREDICT:
        eval_spec = tf.estimator.EstimatorSpec(
            mode=mode,
            predictions=pred
        )
    return eval_spec
```
and when do eval mode using `estimator.eval()`, it can print the content of *eval_metrics*,acc(0.966) however, when i use `estimator.predict()`, raised ValueError(Missing predictions).

I also tried these ways to get tensor predictions:
- using session to `session.run(predictions)`, and `tf.print(predictions)`, failed
- restore model.ckpt to model.pb to `tf.get_default_graph.get_tensor_by_name()`,I got all of argmax nodes' output, Then i found the node that calculates `predictions` not in the graph ????

Finally I found in [estimator source code](https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/model_fn.py) that:
```python
Raises:
    ValueError: If:
      - predictions is None and we are in predict mode.
      - predictions `Tensor` is not in default_graph or else it is a dict of
        `Tensor` where at least one is not in default_graph.
    TypeError:  If predictions is not a `Tensor` or dict of `Tensor`.
  """
```
but i got acc(0.996969907284) using predictions, which means this tensor is not NONE. So it must be the second cause, **not in default_graph**, the same as my second try.

So how should I deal with this? how to add this argmax node to graph?

Thanks in advance for answering.

**Comment by sushreebarsa** [comment]
@waynamigo 
Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
