### ISSUE TITLE
Does tensorflow support to write checkpoint to hdfs?

### ISSUE THREAD

**Issue by qingzew** [tensorflow/tensorflow#5112]
now tensorflow 0.11 can read data from hdfs, so how can I write checkpoint to hdfs? for example:
```python
saver.save(save_path='hdfs://some_dir')
```

**Comment by asimshankar** [comment]
@jhseu

**Comment by tobegit3hub** [comment]
Not test yet but I think so. TensorFlow has implemented the C++ filesystem interfaces which is used for almost all data interface. Now it supports to read data from HDFS, it's really possible to support writing into HDFS.

@qingzew It would be great to test by yourself or ask in StackOverview/Google group/Mail list instead of opening an issue 😃

**Comment by qingzew** [comment]
ok, I have tested it. It can do that, but sometimes with an error:
```shell
Traceback (most recent call last):
  File "cifar10_train.py", line 134, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "cifar10_train.py", line 130, in main
    train()
  File "cifar10_train.py", line 122, in train
    saver.save(sess, checkpoint_path, global_step=step)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1281, in save
    self.last_checkpoints, latest_filename)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 743, in update_checkpoint_state
    file_io.rename(temp_pathname, coord_checkpoint_filename, overwrite=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 295, in rename
    compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.UnknownError
```

you just to modify cifar10 like this:
```python
tf.app.flags.DEFINE_string('train_dir', 'hdfs://localhost:9000/cifar10_train'
```

**Comment by gunan** [comment]
@jhseu is this resolved in master, or is this a legitimate issue we need to resolve.
If this is resolved let's close the issue.

**Comment by qingzew** [comment]
I rebuild tensorflow from master branch, it works now, if you saw this, maybe it's ok:
```shell
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format is deprecated; V2 will become the default shortly after 10/31/2016.
WARNING:tensorflow:Consider switching to the more efficient V2 format now:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:to prevent breakage.
WARNING:tensorflow:*******************************************************

```

**Comment by kelly-tlz** [comment]
I use the tensorflow1.0, but when I write saver.save(sess, hdfs_path+"save_net.ckpt"), it tells me that parent directory is not exists. How can I tackle this problem? Thanks @qingzew @asimshankar @tobegit3hub @gunan @ry

**Comment by qingzew** [comment]
@kelly-tlz try to create root dir first?

**Comment by gctian** [comment]
> I use the tensorflow1.0, but when I write saver.save(sess, hdfs_path+"save_net.ckpt"), it tells me that parent directory is not exists. How can I tackle this problem? Thanks @qingzew @asimshankar @tobegit3hub @gunan @ry

Hi, Do you tackled this problem ? I also meet this problem now.@kelly-tlz
