### ISSUE TITLE
Question: Can we get all the intermidiate tensors when using gpu(opencl) delegate??

### ISSUE THREAD

**Issue by FdyCN** [tensorflow/tensorflow#51126]
Hi guys, i wanna ask if there is any method that we can get the intermidiate tensors on gpu(opencl) delegate.   Which means, when delegate invoke is finished , all the intermidiate tensors' cl_mem are NAIVE stored and we can WRITE into a cpu ptr which is hold by TfliteTensor form the marched tensor id on CPU.   

I see there is TensorTieFactory for subgraph global input & output's conversion. However I'm not really clear some details. 
Could you help me ? Thanks a lot.!

**Comment by abattery** [comment]
@impjdi could you take a look at this?

**Comment by impjdi** [comment]
Not easily achieved at the code level, as we implement https://arxiv.org/abs/2001.03288 buffers used by intermediate tensors are reused and overwritten.

However, one quick hack you can do is the following:
- Assume the output of a CONV_2D is to be inspected.  Let that tensor be A.
- Let the rest of the network intact, but attach a ADD 0 or MUL 1 to A, which is essentially a no-op.  Let its output be B.
- Declare B to be the graph output when you use tflite_converter.

In case TFLite tries to do something smart and prunes out ADD 0 or MUL 1, change it to ADD 0.0000001 or MUL 0.99999999.

**Comment by FdyCN** [comment]
> Not easily achieved at the code level, as we implement https://arxiv.org/abs/2001.03288 buffers used by intermediate tensors are reused and overwritten.
> 
> However, one quick hack you can do is the following:
> 
> * Assume the output of a CONV_2D is to be inspected.  Let that tensor be A.
> * Let the rest of the network intact, but attach a ADD 0 or MUL 1 to A, which is essentially a no-op.  Let its output be B.
> * Declare B to be the graph output when you use tflite_converter.
> 
> In case TFLite tries to do something smart and prunes out ADD 0 or MUL 1, change it to ADD 0.0000001 or MUL 0.99999999.

I really appreciate your reply, i still got one more question. If we cannot get intermidiate buffers from internal op of graph. How can we debug the result of ops in graph if graph's result is wrong？(**assume op single test is passed, but op may not be fully tested or there comes some platform-related bugs.**)

BTW,  i figure we can use MemoryStrategy::NAIVE when create gpu buffers so that buffers won't be reused. Am I wrong?

**Comment by FdyCN** [comment]
@impjdi Please take a look.

**Comment by impjdi** [comment]
> How can we debug the result of ops in graph if graph's result is wrong？

While we can't rule out the possibility of a bug in the shader, it's often FP16 not being good enough (precision-wise), to do the math computation.  See whether FP32 works fine; if it does, you know it's a precision issue.

In our team, we bisect the graph and inspect the output.  Unfortunately, it's not easily achieved with an automatic tool, but you need to visually inspect the graph and find the right cut off point by yourself.

> i figure we can use MemoryStrategy::NAIVE when create gpu buffers so that buffers won't be reused.

Oh, I didn't know naive was one of the possible options.  If it's the same "naive" as in the paper (and I assume it is as it's the same dude who wrote the paper and implemented it), it may do the work.  I have never used it myself though.

**Comment by FdyCN** [comment]
@impjdi  thank you so much !  
**one last question about gpu layout:**

seems like gpu(opencl) uses (C/4)HWB(C4) layout converted from BHWC(CPU layout)，why choose this layout？ maybe BHW(C4) or BH(C/4)W(C4) will be better?  These are my reasons: 

1. data from different batches are independent; 
2. channel data usually are accumulated together in conv ops which costs most of inference time in most CNN.  

So Batch-size being outermost will reduce Scattered-access of threads in the same warp/wave as much as possible and Channel-size being innermost will reduce loop times when doing channel-accumulate. Plus, Channel-size being innermost will be more flexible in boundary procession.

**Comment by FdyCN** [comment]
> @impjdi thank you so much !
> **one last question about gpu layout:**
> 
> seems like gpu(opencl) uses (C/4)HWB(C4) layout converted from BHWC(CPU layout)，why choose this layout？ maybe BHW(C4) or BH(C/4)W(C4) will be better? These are my reasons:
> 
> 1. data from different batches are independent;
> 2. channel data usually are accumulated together in conv ops which costs most of inference time in most CNN.
> 
> So Batch-size being outermost will reduce Scattered-access of threads in the same warp/wave as much as possible and Channel-size being innermost will reduce loop times when doing channel-accumulate. Plus, Channel-size being innermost will be more flexible in boundary process.

@impjdi please take a look.  thank you so much.

**Comment by impjdi** [comment]
While I don't have any documentation to share, that's what the owner of OpenCL profiled and determined to be the fastest performing memory layout.  This usually goes with the parallelization of the workload and how GPU threads run.

**Comment by sushreebarsa** [comment]
@FdyCN Is this still an issue?
Please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/51126#issuecomment-896324362) above.
Thanks!
