### ISSUE TITLE
Need help: How to build tensorflow-lite with "Pyro" version of Yocto, for ARM platform

### ISSUE THREAD

**Issue by ptrivedi2610** [tensorflow/tensorflow#51123]
Hi,

I need to build tensorflow-lite on "Pyro" version of Yocto for one of my Projects, for ARM platform
Can someone point me to fetch the "*.bb" file for the same ? Or the steps to build the same from scratch ?

Thanking in advance

**Comment by abattery** [comment]
@terryheo could you take a look at this?

**Comment by terryheo** [comment]
There is no *official* recipe for Yocto.
Regarding cross compilation, please check the following.
https://www.tensorflow.org/lite/guide/build_cmake_arm
