### ISSUE TITLE
Issue with tf.nn.conv2d restarting kernel

### ISSUE THREAD

**Issue by mdtm1g14** [tensorflow/tensorflow#51122]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10

- TensorFlow installed from (source or binary):
Pip install

- TensorFlow version (use command below):
v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0

- Python version:
3.8

- CUDA/cuDNN version:
CUDA 11.2; cuDNN 8.2

- GPU model and memory:
Nvdia RTX 3060Ti 8GB

**Describe the current behavior**
I am running the exmple script found on the tf.nn.conv2d documentaion page (found here: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d)

Upon running the final line in spyder the kernel immediately restarts with no error message displayed

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

x_in = np.array([[
  [[2], [1], [2], [0], [1]],
  [[1], [3], [2], [2], [3]],
  [[1], [1], [3], [3], [0]],
  [[2], [2], [0], [1], [1]],
  [[0], [0], [3], [1], [2]], ]])
kernel_in = np.array([
 [ [[2, 0.1]], [[3, 0.2]] ],
 [ [[0, 0.3]],[[1, 0.4]] ], ])
x = tf.constant(x_in, dtype=tf.float32)
kernel = tf.constant(kernel_in, dtype=tf.float32)
tf.nn.conv2d(x, kernel, strides=[1, 1, 1, 1], padding='VALID')
```

**Comment by sushreebarsa** [comment]
@mdtm1g14 I tried to run your code on **Colab** & **Spyder** with **`TF v2.5`** , and didn't face  any error .Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/b3bc8a9bfce3e3c522c324f6f6e8dafa/untitled354.ipynb)  for your reference.Thank you!
