### ISSUE TITLE
recompute_grad + keras: "TypeError: Cannot convert a symbolic Keras input/output to a numpy array."

### ISSUE THREAD

**Issue by Danny4** [tensorflow/tensorflow#51131]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro, Version 21H1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.0

**Describe the current behavior**
tf.recompute_grad does not accept tf.keras.layers objects.
Instead, I get: "TypeError: Cannot convert a symbolic Keras input/output to a numpy array."

**Describe the expected behavior**
The API documentation explicitly mentions tf.keras.layers objects.
Also, according to several comments on GitHub, it should work with keras layers.

**Contributing**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Input
from tensorflow.keras.models import Model

def block(x):
    x = Conv2D(filters = 32, kernel_size = (3, 3))(x)
    x = Conv2D(filters = 32, kernel_size = (3, 3))(x)
    return x
block = tf.recompute_grad(block)

input = Input(shape = (128, 128, 3))
block_1 = block(input)
block_2 = block(block_1)
model = Model(input, block_2)
```

**Other info / logs**

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-15-d90add487c0c> in <module>
>      10 
>      11 input = Input(shape = (128, 128, 3))
> ---> 12 block_1 = block(input)
>      13 block_2 = block(block_1)
>      14 model = Model(input, block_2)
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\custom_gradient.py in __call__(self, *a, **k)
>     259 
>     260   def __call__(self, *a, **k):
> --> 261     return self._d(self._f, a, k)
>     262 
>     263 
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\custom_gradient.py in decorated(wrapped, args, kwargs)
>     213 
>     214     if context.executing_eagerly():
> --> 215       return _eager_mode_decorator(wrapped, args, kwargs)
>     216     else:
>     217       return _graph_mode_decorator(wrapped, args, kwargs)
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\custom_gradient.py in _eager_mode_decorator(f, args, kwargs)
>     456   flat_result = nest.flatten(result)
>     457   # TODO(apassos) consider removing the identity below.
> --> 458   flat_result = [gen_array_ops.identity(x) for x in flat_result]
>     459 
>     460   input_tensors = [ops.convert_to_tensor(x) for x
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\custom_gradient.py in <listcomp>(.0)
>     456   flat_result = nest.flatten(result)
>     457   # TODO(apassos) consider removing the identity below.
> --> 458   flat_result = [gen_array_ops.identity(x) for x in flat_result]
>     459 
>     460   input_tensors = [ops.convert_to_tensor(x) for x
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\gen_array_ops.py in identity(input, name)
>    3954       pass
>    3955     try:
> -> 3956       return identity_eager_fallback(
>    3957           input, name=name, ctx=_ctx)
>    3958     except _core._SymbolicException:
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\ops\gen_array_ops.py in identity_eager_fallback(input, name, ctx)
>    3974 
>    3975 def identity_eager_fallback(input, name, ctx):
> -> 3976   _attr_T, (input,) = _execute.args_to_matching_eager([input], ctx, [])
>    3977   _inputs_flat = [input]
>    3978   _attrs = ("T", _attr_T)
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\eager\execute.py in args_to_matching_eager(l, ctx, allowed_dtypes, default_dtype)
>     271 
>     272       if tensor is None:
> --> 273         tensor = ops.convert_to_tensor(
>     274             t, dtype, preferred_dtype=default_dtype, ctx=ctx)
>     275 
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\profiler\trace.py in wrapped(*args, **kwargs)
>     161         with Trace(trace_name, **trace_kwargs):
>     162           return func(*args, **kwargs)
> --> 163       return func(*args, **kwargs)
>     164 
>     165     return wrapped
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
>    1564 
>    1565     if ret is None:
> -> 1566       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>    1567 
>    1568     if ret is NotImplemented:
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
>     337                                          as_ref=False):
>     338   _ = as_ref
> --> 339   return constant(v, dtype=dtype, name=name)
>     340 
>     341 
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
>     262     ValueError: if called on a symbolic tensor.
>     263   """
> --> 264   return _constant_impl(value, dtype, shape, name, verify_shape=False,
>     265                         allow_broadcast=True)
>     266 
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
>     274       with trace.Trace("tf.constant"):
>     275         return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
> --> 276     return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
>     277 
>     278   g = ops.get_default_graph()
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
>     299 def _constant_eager_impl(ctx, value, dtype, shape, verify_shape):
>     300   """Implementation of eager constant."""
> --> 301   t = convert_to_eager_tensor(value, ctx, dtype)
>     302   if shape is None:
>     303     return t
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
>      96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
>      97   ctx.ensure_initialized()
> ---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
>      99 
>     100 
> 
> ~\.conda\envs\histology\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py in __array__(self)
>     252 
>     253   def __array__(self):
> --> 254     raise TypeError(
>     255         'Cannot convert a symbolic Keras input/output to a numpy array. '
>     256         'This error may indicate that you\'re trying to pass a symbolic value '
> 
> TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.

**Comment by UsharaniPagadala** [comment]
@Danny4 

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo. To know more refer to:https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

I have reproduced the code with minimal changes.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/823a4d13ebd2baa005248c6b0aba4533/untitled161.ipynb)
Could you please refer the similar issues [link](https://github.com/tensorflow/tensorflow/issues/47311) .Thanks
