### ISSUE TITLE
Documentation link broken at projector.tensorflow.org

### ISSUE THREAD

**Issue by fz-29** [tensorflow/tensorflow#51135]
## URL(s) with the issue:
https://projector.tensorflow.org/

## Description of the issue (what needs changing):

The question mark icon in the top right of navbar is supposed to be a hyperlink to the documentation.
The icon is a hyperlink to https://www.tensorflow.org/get_started/embedding_viz , which is broken.

**Comment by Saduf2019** [comment]
@fz-29 
We are looking in to this and will update you at the earliest.

**Comment by SubhasmitaSw** [comment]
This is fixed now, I think this issue should be closed to avoid confusion.

**Comment by Saduf2019** [comment]
Moving this to closed status as its resolved.
