### ISSUE TITLE
TFLite conversion notebook will no longer install dependencies

### ISSUE THREAD

**Issue by Drewbie18** [tensorflow/tensorflow#51137]
## URL(s) with the issue:

Doc Link: https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/ml/README.md

Notebook link (also on doc page): 
https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/ml/tensorflowjs_to_tflite_colab_notebook.ipynb

## Description of issue (what needs changing):

Updated notebook that will install the dependencies, and run successfully to convert a Tf 1.x model to a TFLite model. 

### Clear description

Following the steps for the TFLite example project you are recommended to use a python notebook (linked above). I have used it many times before, however it has recently stopped working. I was using it on Collab as per the instructions. 

### Usage example

The following command: `!pip3 install tensorflow==1.14.0 keras==2.2.4 tensorflowjs==0.6.4 --force-reinstall`

Results in: 

```
ERROR: Cannot install keras==2.2.4 and tensorflowjs==0.6.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested keras==2.2.4
    tensorflowjs 0.6.4 depends on keras==2.2.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

```

**Comment by abattery** [comment]
@xunkai @lintian06 could you take a look at this report?

**Comment by lintian06** [comment]
Thank you for the report! You can add the flag --use-deprecated=legacy-resolver, and it is pip's version change.
```
!pip3 install tensorflow==1.14.0 keras==2.2.4 tensorflowjs==0.6.4 --force-reinstall --use-deprecated=legacy-resolver
```

**Comment by Drewbie18** [comment]
Hi @lintian06. You're welcome for the report. 

The fix did work for the initial error, however the next part of the notebook would then end up in an error unfortunately. 


Command:
```
import traceback
import logging
import tensorflow.compat.v1 as tf
import keras.backend as K
import os

from google.colab import files

from keras import Model, Input
from keras.applications import MobileNet
from keras.engine.saving import load_model

from tensorflowjs.converters import load_keras_model

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
```

Error:
```
AttributeError: module 'tensorflow._api.v1.compat.v2.compat' has no attribute 'v1'
```

Fortunately I was able to find the solution to this error myself here: https://stackoverflow.com/questions/67703514/tensorflow-issue-google-colab-tensorflow-api-v1-compat-v2-has-no-attribute

**Comment by ymodak** [comment]
Closing this issue since it's resolved now. Feel free to reopen if necessary. Thanks!
