### ISSUE TITLE
Memory corrupt when running in distributed mode with CUDA 8.0 and Tesla M40

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#5113]
We have implemented tested the distributed TensorFlow applications. It works in CPU environment and the GPU environment with CUDA 7.5 and Tesla K40. But it fails with CUDA 8.0 and Tesla M40.

![screen shot 2016-10-21 at 19 10 37](https://cloud.githubusercontent.com/assets/2715000/19597024/9882b2de-97c4-11e6-930a-3c373524d21b.png)

![screen shot 2016-10-21 at 19 11 16](https://cloud.githubusercontent.com/assets/2715000/19597035/ab8502ec-97c4-11e6-9028-80d10347dbf2.png)

Not sure if it's related to CUDA 8.0. The test code is [here](https://github.com/tobegit3hub/distributed_tensorflow) and 100% re-produce if I run it with CUDA 8.0 and Tesla M40.

### Environment info

Operating System: CentOS 7.0
CUDA and cuDNN: CUDA 8.0 and cuDNN v5
TensorFlow version: 0.11.0rc0

**Comment by tobegit3hub** [comment]
We have tested and it works with CUDA 7.5 and M40.

It seems to be the problem of TensorFlow 0.11.0rc0 with CUDA 8.0.

**Comment by tobegit3hub** [comment]
Supporting CUDA 8.0 is released by `v0.11.0rc1`. I test with the latest release version and everything works with CUDA 8.0 and Nvidia M40.

Thanks for the contribution 😃

**Comment by yaroslavvb** [comment]
This seems like a lot of work for maintainers to reproduce, it would be
productive to isolate the issue further -- ie, finding which ops/conditions
give an unexpected result
