### ISSUE TITLE
Google Developers Certification Plugin

### ISSUE THREAD

**Issue by idee24** [tensorflow/tensorflow#51146]
The Google Developers Certification Plugin is not available on Android Studio Arctic Fox 2020.3.1
![dd](https://user-images.githubusercontent.com/40315618/128174071-8755f5fb-5161-4991-9151-df731784dda8.PNG)

**Comment by sushreebarsa** [comment]
@idee24 Could you please refer to the **`Plugin description`** in this [documentation](https://www.tensorflow.org/certificate) of **`Review Candidate Handbook`** where it is recommended that Certification Plugin is available in Pycharm .Please take a look on that link to  try Google Developers certification [plugin](https://www.tensorflow.org/extras/cert/TF_Certificate_Candidate_Handbook.pdf) in Pycharm   and let us know if it helps? Thank you!

**Comment by idee24** [comment]
This helped. My issue has been resolved thanks.
