### ISSUE TITLE
tf.saved_model.save fails when there is tf.reshape in tf.keras.Model call method

### ISSUE THREAD

**Issue by kacper-kleczewski** [tensorflow/tensorflow#51143]
**Current behavior**
tf.saved_model.save fails to save tf.keras.Model if there is tf.reshape operation in Model call method.

I have debugged it and I found that during saving the Model, SimpleModel.call is called twice. The first time everything is fine and **batch_size = 1,** but in the second call **batch_size = None** and this is why it fails.

**Expected behavior**
Model should be saved as Savedmodel

**Tested with**
TF 2.4.1 and TF 2.5 installed by PIP
Windows 10
Ubuntu 18.04
Nvidia GPU

**Example code for easy reproduction**
```
import tensorflow as tf

class SampleModel(tf.keras.Model):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.dense_1 = tf.keras.layers.Dense(
            units=10,
            activation=tf.nn.relu
        )

    def call(self, inputs, **kwargs):
        batch_size, height, width, filters = inputs.get_shape().as_list()
        x = tf.reshape(inputs, [batch_size, height * width * filters])
        x = self.dense_1(x)

        return x

def get_model():
    input_shape = (10, 10, 3)
    input = tf.keras.layers.Input(shape=input_shape, batch_size=1)

    x =  tf.keras.layers.Conv2D(
        filters=10,
        kernel_size=3
    )(input)

    sample_model = SampleModel()
    output = sample_model(x)
    model = tf.keras.Model(inputs=input, outputs=output)

    return model

if __name__ == "__main__":
    model = get_model()

    tf.saved_model.save(
        obj=model,
        export_dir="./savemodel_test"
    )


```

**Comment by sushreebarsa** [comment]
@kacper-kleczewski Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by kacper-kleczewski** [comment]
Ok, thanks.
Issue added to keras repo:
https://github.com/keras-team/keras/issues/15066
