### ISSUE TITLE
Cloud TPU Memory Leak causing OOM Error 

### ISSUE THREAD

**Issue by Julianna3141** [tensorflow/tensorflow#51149]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): n1-standard-2 VM on GKE; Container-Optimized OS with Docker (cos) 
- TensorFlow installed from (source or binary): binary (pip command) 
- TensorFlow version (use command below): 2.3.0 
- Python version: 3.6 
- Bazel version (if compiling from source): None 
- GCC/Compiler version (if compiling from source): None 
- CUDA/cuDNN version: None 
- GPU model and memory: None (v2.8 preemptible TPU with GKE) 

**Describe the current behavior**
I am performing large-scale hyperparameter optimization using Cloud TPUs on GKE. Unfortunately, I keep encountering a memory leak that causes the TPUs to return an OOM after training several networks. Initially, I thought this issue was due to the buildup of old models, so I tried methods such as tf.backend.clear_session(), del model, and gc.collect(). Those methods fixed a memory leak that had been happening with the controller CPU, but the memory leak persists on the TPU worker node. Occasionally, I instead get an "Unavailable: Socket Closed" error. To fix these issues, I tried solutions suggested by other posts, such as typecasting my data to float32, not caching my dataset into memory, using a smaller mini-batch size, and using from_logits in my cost function. Unfortunately, those solutions have not helped.  I have not encountered these problems with either a CPU/GPU/Colab TPU. 

**Describe the expected behavior**
Same as CPU/GPU/Colab TPU (no memory leak) 

**Standalone code to reproduce the issue**
The issue does not occur on Colab, but here is a [link](https://colab.research.google.com/drive/1tjPh6-UQuEtFKNQcJfaVA3vQ0eIV5SG_?usp=sharing) to code that reproduces the issue on GCP.

**Other info / logs** 
Log trace: 
[TPU_Traceback.txt](https://github.com/tensorflow/tensorflow/files/6932886/TPU_Traceback.txt)

**Comment by sushreebarsa** [comment]
@Julianna3141  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by Julianna3141** [comment]
Thank you for the suggestion. Unfortunately, when I try to create tf 2.5 nodes in Kubernetes with the following line (tf-version.cloud-tpus.google.com: "2.5") in my Kubernetes pod spec, I get this error message: `"Failed to provision Cloud TPU(s): failed to create Cloud TPU in zone "us-central1-c": googleapi: Error 400: Cloud TPU received an invalid argument. The field "TensorflowVersion" cannot be "2.5".` I was able to create a node with version 2.4.1, but for some reason, my code seems to get stuck at the "Started server with target:  grpc://localhost:30001" line. I tried re-deploying the code, but it has been at that line for the past 20 minutes (previously, it had only stayed at that line for 2-3 minutes). Also, strangely, the CPU utilization on the controller drops from 40% to below 1%, though I'm not sure why and have not experienced this problem before. Did I need to change anything in my TPU initialization code to work with 2.4.1?

**Comment by sbl1996** [comment]
I am also using TPU to perform HPO (with Optuna), and find that the only way works is to spawn a new process for every new trial. You may check [here](https://github.com/sbl1996/hanser/blob/master/examples/hpo/optuna/mnist.py) for example.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
