### ISSUE TITLE
Performance regression: Tensorflow 2.5.0

### ISSUE THREAD

**Issue by liyinhgqw** [tensorflow/tensorflow#51145]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Centos 7**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.5.0**
- Python version: 3.8.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I observed significant performance regression (+20% latency) using TF 2.5.0 compared to TF 2.3.0 on CPU.
One op to highlight is `sparse_tensor_dense_matmul `.
The cause could be Eigen or change of this kernel.

**Describe the expected behavior**
Performance on parity with TF 2.3.0.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1gNaQsRZzhmKYFQGMxOO9vzSR6AFpVMci?usp=sharing

**Comment by pavanky** [comment]
Performance
- 2.3.0:  ~245 ms
- 2.4.0:  ~240 ms
- 2.5.0: ~350ms
- tf-nightly (latest): ~350ms

Something broke between 2.4 and 2.5

**Comment by SohaibAnwaar** [comment]
Hy! I am processing matrix multiplication operations on TensorFlow and NumPy to check the processing time difference on CPU and GPU. It's taking more time to process operation on GPU than on CPU

On Cpu its taking:1.15 sec

On GPU it's taking: 34 sec

why so? According to my understanding GPU should perform fast operations than CPU..

**CPU CODE**

```
    import numpy as np
    import time
    from tqdm import tqdm
    
    
    # Making Tensor Constant
    np_arr = np.asarray([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [4.0, 5.0, 6.0]])
    print("Starting cpu processing")
    st = time.time()
    for i in tqdm(range(0,1000000)):
        np_arr @ np_arr
        
    # Took 1 sec    
    print(f"Time Taken BY CPU {time.time() -st}")

```

**GPU Code**


```
    import tensorflow as tf
    physical_devices = tf.config.list_physical_devices('GPU') 
    
    # Gpu Settings for rtx3070
    from tensorflow.compat.v1.keras.backend import set_session
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
    config.log_device_placement = True  # to log device placement (on which device the operation ran)
    sess = tf.compat.v1.Session(config=config)
    set_session(sess)
    
    import time
    from tqdm import tqdm
    
    print("Here is the tensorflow version ",tf.__version__)
    
    # Making Tensor Constant
    tensor1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [4.0, 5.0, 6.0]])
    
    # Getting the shape of the tensor
    print(tensor1.get_shape())
    
    
    st = time.time()
    for i in tqdm(range(0,1000000)):
        # Using tensorflow function to use gpu functionality
        tf.linalg.matmul(tensor1, tensor1)
    
    # Took 34 sec
    print(f"Time Taken BY GPU {time.time() -st}")

```

**Comment by sushreebarsa** [comment]
@rmothukuru Was able to reproduce on colab using TF [v2.3](https://colab.research.google.com/gist/sushreebarsa/93de3d9cbb52daaf1e6589a951f234ca/sparse_tensor_dense_matmul_benchmark.ipynb#scrollTo=IyCaVfHFK3QO),[v2.4](https://colab.research.google.com/gist/sushreebarsa/b823c7b058446445728dacf45ba4d9c0/sparse_tensor_dense_matmul_benchmark.ipynb#scrollTo=qCrlrsqG2I4M),&  [v2.5](https://colab.research.google.com/gist/sushreebarsa/9ef89549732293595306666bfdf939d1/sparse_tensor_dense_matmul_benchmark.ipynb#scrollTo=IyCaVfHFK3QO),please find the gists attached here.
Thank you!

**Comment by ImtiazSajwani** [comment]
Try using the Intel Tensor Flow 2.5, pip install intel-tensorflow==2.5.0

**Comment by penpornk** [comment]
@ImtiazSajwani Intel TensorFlow doesn't have any optimization for `SparseTensor` ops, so I think the performance will be similar.

**Comment by liyinhgqw** [comment]
@penpornk , do you have a plan to patch the performance fix of Eigen and TF to master or any version of release?

**Comment by penpornk** [comment]
@liyinhgqw Currently there is no plan. But I can investigate if the issue can be fixed in the master branch. (The patch for v2.5 alone requires reverting / changing 5 commits between 2.3 and 2.5. There could be more commits after 2.5 which affects compiler optimization.)

**Comment by kwlzn** [comment]
@penpornk that would be super helpful - thank you!

ideally, we could get this into master for 2.8 (and future versions) and then cherry-pick that to a 2.7.1 patch release for near-term consumption (we're going to try to jump from 2.5 -> 2.7 as soon as we have a 2.7 release with this patch).

**Comment by chunduriv** [comment]
I was able to reproduce the issue in `TF2.8` and `tf-nightly(2.9.0-dev20220401)`. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/089435bb89b30c4dbef646e47a604958/51145.ipynb#scrollTo=Zn9YOhi7aIdE) for reference. Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
