### ISSUE TITLE
Inference is slower on Densenet121 when using XLA 

### ISSUE THREAD

**Issue by crawlingcub** [tensorflow/tensorflow#51179]
Hi,

When running the Densenet121 model using **XLA** on Imagenet dataset, the inference is about 5-7 seconds slower than normal on GPU.

**Environment**:
Tensorflow 2.5.0
keras-nightly==2.5.0.dev2021032900
Python 3.7
OS: Ubuntu 18.04
CUDA 11.1
GPUs: 8 Nvidia GA100

**Current behaviour**:
Running inference using Densenet121 without XLA takes ~14s on 10000 images
Running inference using Densenet121 with XLA takes ~20s on 10000 images

**Expected behaviour**:
Times should be similar or XLA should be faster!

My code is currently quite complex. If needed, I can try to provide a simplified version. Please let me know if you need any additional information.

**Comment by sanatmpa1** [comment]
@crawlingcub,

Please provide the reproducible standalone code to expedite the trouble shooting process. Thanks!

**Comment by crawlingcub** [comment]
Hi, 

Please find the code to reproduce the bug below. You will need to download the imagenet dataset and pre-sort it. Change the directory from `'./imagenet/val` to where you downloaded. 

Download the model files from [here](https://drive.google.com/file/d/1AMnRXvEpmIIxVtM7xsHWloDlcSTuBLQ0/view?usp=sharing), untar, and run the script below with the path to the directory.


```python
import os
import sys
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['XLA_FLAGS']="--xla_gpu_cuda_data_dir=/usr/local/cuda-11.1"
import tensorflow.keras as keras
import tensorflow as tf
tf.keras.backend.set_image_data_format('channels_first')


def load_dataset(data_format, target):
    val_ds = keras.preprocessing.image_dataset_from_directory(
                    directory='./imagenet/data',
                    labels="inferred",
                    label_mode="categorical",
                    class_names=[],
                    image_size=(224,224),
                    batch_size=100,
                    validation_split=0.2,
                    subset="validation",
                    seed=1234
                )

    val_ds = val_ds.map(lambda x, y: (tf.transpose(x, [0, 3, 1, 2]), y))
    val_ds = val_ds.map(lambda x, y:
                        (keras.applications.imagenet_utils.preprocess_input(
                            x,
                            data_format=data_format,
                            mode=target), y))
    return val_ds


img_input = keras.layers.Input(shape=(3,224,224))
test_ds = load_dataset('channels_first', 'torch')
print("Data loaded")
model = keras.models.load_model(sys.argv[1])
opt = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, decay=1e-6)
model.compile(optimizer=opt,
             loss='categorical_crossentropy',
             metrics=['accuracy', tf.keras.metrics.AUC(from_logits=True)])

model.evaluate(test_ds, verbose=1)

# enable xla
tf.keras.backend.clear_session()
tf.config.optimizer.set_jit(True)

print("xla")
model = keras.models.load_model(sys.argv[1])
opt = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, decay=1e-6)
model.compile(optimizer=opt,
             loss='categorical_crossentropy',
             metrics=['accuracy', tf.keras.metrics.AUC(from_logits=True)])

model.evaluate(test_ds, verbose=1)
```

Running this script produces the following output, where XLA is slower than normal execution!

Output:
```
Found 50000 files belonging to 1000 classes.
Using 10000 files for validation.
Data loaded
100/100 [==============================] - 14s 75ms/step - loss: 0.4465 - accuracy: 0.7186 - auc: 0.9826
xla
100/100 [==============================] - 22s 87ms/step - loss: 0.4465 - accuracy: 0.7185 - auc: 0.9826
```


Hope this helps. Let me know if you need more info.

**Comment by sanatmpa1** [comment]
@crawlingcub,

Thanks for sharing the code, Can you also share the sample data as well to reproduce the issue from our end.

**Comment by crawlingcub** [comment]
Hi, I am using the imagenet dataset. I don't think I can directly share the imagenet dataset. You can download it from https://image-net.org/download.php

**Comment by crawlingcub** [comment]
I also reproduced the same problem with cifar10. Please find the code below and the model [here](https://drive.google.com/file/d/19Vhn-jLTAwQY3i19SP93cMLU-9mOWBSK/view?usp=sharing): 

Hope this unblocks you.

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['XLA_FLAGS']="--xla_gpu_cuda_data_dir=/usr/local/cuda-11.1"

import tensorflow.keras as keras
import tensorflow as tf
tf.keras.backend.set_image_data_format('channels_first')


def load_cifar():  
    (x, y), (x_test, y_test) = keras.datasets.cifar10.load_data()
    x_test = keras.applications.imagenet_utils.preprocess_input(x_test, data_format='channels_first', mode='torch')
    y_test = keras.utils.to_categorical(y_test, num_classes=10)
    x = keras.applications.imagenet_utils.preprocess_input(x, data_format='channels_first', mode='torch')
    y = keras.utils.to_categorical(y, num_classes=10)
    train_ds = tf.data.Dataset.from_tensor_slices((x, y)).batch(100)
    test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(100)
    return train_ds, test_ds


def create_train_model():
    model = keras.Sequential()
    model.add(keras.applications.densenet.DenseNet121(input_shape=None, weights="imagenet", include_top=False,  pooling='avg'))
    model.add(keras.layers.Dense(10, activation='softmax'))
    model.layers[0].trainable = False
    opt = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, decay=1e-6)
    model.compile(
        optimizer=opt,
        loss='categorical_crossentropy',
        metrics=['accuracy'])
    return model

train_ds, test_ds = load_cifar()


img_input = keras.layers.Input(shape=(3,32,32))
model = keras.models.load_model('bugmodel')
opt = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, decay=1e-6)
model.compile(optimizer=opt,
             loss='categorical_crossentropy',
             metrics=['accuracy', tf.keras.metrics.AUC(from_logits=True)])

model.evaluate(test_ds, verbose=1)

tf.keras.backend.clear_session()
tf.config.optimizer.set_jit(True)
print("xla")
model = keras.models.load_model('bugmodel')
opt = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9, decay=1e-6)
model.compile(optimizer=opt,
             loss='categorical_crossentropy',
             metrics=['accuracy', tf.keras.metrics.AUC(from_logits=True)])

model.evaluate(test_ds, verbose=1)

```

Output
```
100/100 [==============================] - 8s 21ms/step - loss: 8.9364 - accuracy: 0.5511 - auc: 0.7836
xla
100/100 [==============================] - 10s 18ms/step - loss: 8.9355 - accuracy: 0.5511 - auc: 0.7837
```

**Comment by sanatmpa1** [comment]
@crawlingcub,

When I tried extracting the tar file of bug model provided, I am getting `ReadError: unexpected end of data` and I am not able to use the model that you created, [gist here](https://colab.research.google.com/gist/sanatmpa1/9538a075bf83bf823a2dfb9a370fa7be/51179.ipynb). Can you share the reproduced colab gist of the issue? Thanks!

**Comment by crawlingcub** [comment]
can you just extract the folder using command line: `tar -xvf bugmodel.tar.gz` and then use that folder to read the model?

**Comment by sanatmpa1** [comment]
@crawlingcub,

I am able to reproduce the code in colab with GPU and take a look at this [gist](https://colab.research.google.com/gist/sanatmpa1/9538a075bf83bf823a2dfb9a370fa7be/51179.ipynb#scrollTo=5ZnEJYZL_22p). I am not seeing slower inference when using XLA as both the evaluation takes similar time. Can you try updating to latest stable version `2.6.0` and let me know if the issue persists? Thanks!

**Comment by crawlingcub** [comment]
Hi,

I think the issue was more apparent with imagenet dataset. I cannot share the dataset directly due to distribution restrictions. Can you try it out? It can be obtained from [here](https://image-net.org/download.php)

**Comment by sanatmpa1** [comment]
@crawlingcub,

Are you able to update your tensorflow version to `2.6.0` and check if the same issue persists? because the one that I reproduced in colab is with TF 2.6.0 and I see the issue reported by you is with `TF 2.5.0`.
