### ISSUE TITLE
seq2seq tutorial example not working for python 3.4/3.5

### ISSUE THREAD

**Issue by briangoodness** [tensorflow/tensorflow#5118]
I am trying to get the sequence-to-sequence Tensorflow tutorial (https://www.tensorflow.org/versions/r0.11/tutorials/seq2seq/index.html) up and running, but after downloading the WMT data, I am facing an error upon creating the vocabulary: 

```
>> python3 translate.py --data_dir ~/tf-data/
Preparing WMT data in /home/user/tf-data/
Creating vocabulary /home/user/tf-data/vocab40000.fr from data /home/user/tf-data/giga-fren.release2.fixed.fr
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/home/user/tensorflow3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 287, in main
    train()
  File "translate.py", line 147, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/home/user/tensorflow3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 271, in prepare_wmt_data
    create_vocabulary(fr_vocab_path, train_path + ".fr", fr_vocabulary_size, tokenizer)
  File "/home/user/tensorflow3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 140, in create_vocabulary
    tokens = tokenizer(line) if tokenizer else basic_tokenizer(line)
  File "/home/user/tensorflow3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 109, in basic_tokenizer
    words.extend(_WORD_SPLIT.split(space_separated_fragment))
TypeError: cannot use a bytes pattern on a string-like object
```

Operating System: Ubuntu 16.04.1 LTS

I tried running on two different systems (Python 3.4.3, Python 3.5.2), and the same error arises.

I am running an up-to-date, CPU-only version of Tensorflow 0.11.0rc0 (for the appropriate version of Python 3.4/3.5) in a virtualenv, with an up-to-date version of the github repository.

My hunch is that this is related to a similar issue (https://github.com/tensorflow/tensorflow/issues/1432) that had been previously fixed, but this error is not identical, so am not sure if this is new.

Any insight would be much appreciated!

**Comment by asimshankar** [comment]
@briangoodness : Sorry for the trouble, and I believe you are right about this being an issue of Python2 vs Python3. As a short term workaround, could you try after changing [data_utils.py:44](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/data_utils.py#L44) to:

```python
_WORD_SPLIT = re.compile(u"([.,!?\"':;)(])")
```

(replacing the `b` with a `u`)?

**Comment by asimshankar** [comment]
Ah, this was fixed by PR #4793 (https://github.com/tensorflow/tensorflow/commit/36ebbf1ddc3ed820b7a5572ff4ed8e9bc707b8e5)

Unfortunately, this fix didn't make it into the images for the latest release, I will look into that. 
In the mean time, an alternative would be to copy the latest files from 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/rnn
into your own directory and run them.

**Comment by briangoodness** [comment]
@asimshankar, thank you for the help and direction! This makes sense-- I was wondering why the files in the models/rnn folder in the repo were not in sync with those in the python pip installation (e.g., I couldn't find the translate.py file in the python install).

Per your suggestion, I copied the models/rnn folder from the master branch of the tensorflow repo into the python installation, and re-ran. It downloads and tokenizes the files, and then breaks at the same point-- after line 22,500,000 in the 'giga-fren.release2.fixed.en' file. See below for the precise error.

I've replicated it on my laptop (8Gb RAM) and desktop (32Gb RAM)-- the code breaks on both machines, at the same location. It seems strange that it would be break at this specific point, not sure if this might be related to memory. In my example below, I toyed with tweaks at the command line (e.g., limiting the training size) to see if it affected success.

```
>> python3 translate.py --data_dir ~/tf-data/ --train_dir ~/tf-data/ --size=256 --num_layers=2 --steps_per_checkpoint=50 --max_train_data_size=50000
Preparing WMT data in /home/user/tf-data/
Downloading http://www.statmt.org/wmt10/training-giga-fren.tar to /home/user/tf-data/training-giga-fren.tar
Succesfully downloaded training-giga-fren.tar 2595102720 bytes
Extracting tar file /home/user/tf-data/training-giga-fren.tar
Unpacking /home/user/tf-data/giga-fren.release2.fixed.fr.gz to /home/user/tf-data/giga-fren.release2.fixed.fr
Unpacking /home/user/tf-data/giga-fren.release2.fixed.en.gz to /home/user/tf-data/giga-fren.release2.fixed.en
Downloading http://www.statmt.org/wmt15/dev-v2.tgz to /home/user/tf-data/dev-v2.tgz
Succesfully downloaded dev-v2.tgz 21393583 bytes
Extracting tgz file /home/user/tf-data/dev-v2.tgz
Creating vocabulary /home/user/tf-data/vocab40000.fr from data /home/user/tf-data/giga-fren.release2.fixed.fr
  processing line 100000
  processing line 200000
  processing line 300000
  processing line 400000
  processing line 500000

....

  processing line 22200000
  processing line 22300000
  processing line 22400000
  processing line 22500000
Creating vocabulary /home/user/tf-data/vocab40000.en from data /home/user/tf-data/giga-fren.release2.fixed.en
  processing line 100000
  processing line 200000
  processing line 300000
  processing line 400000

...

  processing line 22300000
  processing line 22400000
  processing line 22500000
Tokenizing data in /home/user/tf-data/giga-fren.release2.fixed.fr
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/home/user/tf-env-py3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "translate.py", line 287, in main
    train()
  File "translate.py", line 147, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/home/user/tf-env-py3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 279, in prepare_wmt_data
    data_to_token_ids(train_path + ".fr", fr_train_ids_path, fr_vocab_path, tokenizer)
  File "/home/user/tf-env-py3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 243, in data_to_token_ids
    normalize_digits)
  File "/home/user/tf-env-py3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 209, in sentence_to_token_ids
    words = basic_tokenizer(sentence)
  File "/home/user/tf-env-py3/lib/python3.5/site-packages/tensorflow/models/rnn/translate/data_utils.py", line 110, in basic_tokenizer
    words.extend(_WORD_SPLIT.split(space_separated_fragment))
TypeError: cannot use a bytes pattern on a string-like object
```

**Comment by asimshankar** [comment]
@briangoodness : That does seem weird, though I'm not sure it's a good idea to copy the files over the installation. An alternative would be to copy the files to their own directory and rewrite the imports a bit, so that example code isn't picked up from the installation.

**Comment by churichard** [comment]
I'm having this same problem at the same point in the code with Python 3.5.2 and TensorFlow v0.11.0rc2. Is there a fix?

**Comment by asimshankar** [comment]
@churichard : Unfortunately, this fix didn't make it to 0.11.
I'm sorry I don't have better news, but in the mean time your options are to use Python 2.7 or copy and fix the example code as mentioned above.

**Comment by Invisibility** [comment]
I also hit this issue in 0.11.0rc2, even though I pull the latest source code and build the library. 
I think the previous fix [PR #4793 (36ebbf1)] is incomplete. I am able to resolve it by adding the following line at the beginning of `sentence_to_token_ids` in tensorflow/models/rnn/translate/data_utils.py

  `sentence = tf.compat.as_bytes(sentence)`

**Comment by asimshankar** [comment]
@Invisibility : Thanks for the update and for tracking this down. Would you be interested in submitting a PR for this? (And perhaps instead of changing `sentence_to_token_ids`, you can change its [callsite in `data_to_token_ids`](https://github.com/tensorflow/tensorflow/blob/36ebbf1ddc3ed820b7a5572ff4ed8e9bc707b8e5/tensorflow/models/rnn/translate/data_utils.py#L242)  so that `tf.compat.as_bytes(line)` is the argument? This would make the call consistent with the documentation of `sentence_to_token_ids` (which says it takes bytes) and [the other call site](https://github.com/tensorflow/tensorflow/blob/816ecb7a342c25c19daa8b19627346e1fb38e56f/tensorflow/models/rnn/translate/translate.py#L240).

**Comment by Invisibility** [comment]
@asimshankar : OK, I will work on this and try to submit a PR by the end of this week.

**Comment by MMars9** [comment]
@Invisibility : does the addition of the sentence line above solve the issue OP experienced? I'm in the same boat, and not sure if additional work is needed. If there's a version with all the working files, I'd be grateful if someone could point me in the right direction.

**Comment by Invisibility** [comment]
Yes, it works for me.

**Comment by aselle** [comment]
It seems like this is resolved. Please let us know if this is still an issue for anybody.
