### ISSUE TITLE
[CoreML Delegate] validator error: Padding type for the pooling layer 'PoolingLayerBuilder (MEAN)_2' is not set.

### ISSUE THREAD

**Issue by airman00** [tensorflow/tensorflow#51180]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX Big Sur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone XS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- Bazel version (if compiling from source): 3.7.2

**Describe the current behavior**
I have used Google AutoML Vision to create object detection models in the past. Previously the models that were generated were all TOCO converted on runtime 1.15. Recently, AutoML has been generating object detection models that are MLIR converted on TF runtime 2.5. All models are in TensorFlow Lite format.

My previous object detection models run without any issues with the CoreML Delegate. The new object detection models run on CPU but throw an error when using the CoreML delegate. It's the same Object Detection sample code running for both - older model the CoreML works, newer one does not work.

The specific error is `Error compiling model Error reading protobuf spec. validator error: Padding type for the pooling layer 'PoolingLayerBuilder (MEAN)_2' is not set.`

**Describe the expected behavior**
CoreML Delegate should create an ML model without any errors.

**Other info / logs** 
I attempted to solve the problem by explicitly setting padding to SAME for kTfLiteBuiltInMean operation as follows. It appeared to work, the error was gone and the delegate was initialized. However, with that one small change it also seemed to crash every now and then with BAD_EXC_ACCESS error. 

I made this PR today but closed it once I noticed the crashes.
https://github.com/tensorflow/tensorflow/pull/51174/commits/602cd90c1d55bc205c4230060c4423af4cdf82fd

Pooling Layer Params specification:
https://apple.github.io/coremltools/mlmodel/Format/NeuralNetwork.html#poolinglayerparams

I am building the CoreML framework locally by running this in `tensorflow/tensorflow/lite` and testing on an iPhoneX (I am making sure to Clean the Build Folder between tests)
```
 bazel build -c opt --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteCCoreML_framework
tflite_ios_framework(
    name = "TensorFlowLiteCCoreML_framework",
    hdrs = [
        ":coreml_delegate.h",
    ],
    allowlist_symbols_file = ":allowlist_TensorFlowLiteCCoreML.txt",
    bundle_name = "TensorFlowLiteCCoreML",
    minimum_os_version = TFL_MINIMUM_OS_VERSION,
    deps = [
        "//tensorflow/lite/delegates/coreml:coreml_delegate",
    ],
)
```

Questions:
1. Was my approach correct to explicitly set the padding or is there something else at play here?
2. What else can I try to get CoreML working and fix this error?

**Comment by sushreebarsa** [comment]
@airman00 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by airman00** [comment]
@sushreebarsa thank you for the quick reply!

Please pull this repo to reproduce the error. I have included sample tflite files. 
https://github.com/airman00/tensorflow-object-detection-example


The error:
```
ObjectDetection[50052:5356650] Failed to Compile and save Model.
ERROR: Failed to Compile and save Model.

ObjectDetection[50052:5356650] Error compiling model Error reading protobuf spec. validator error: Padding type for the pooling layer 'PoolingLayerBuilder (MEAN)_1' is not set.
```

**Comment by airman00** [comment]
Hi,

Confirming this is still happening even in the latest version, TensorFlow 2.6.0

**Comment by po0ya** [comment]
I'm facing the same issue, any resolutions?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by natanaels12** [comment]
still same issue in 2.10...

**Comment by elephantum** [comment]
Recently we got the same error when tried to run EfficientNet on CoreML delegate.

We also tried converting tensorflow model directly to CoreML via coremltools and it worked.

After some digging it seems that coremltools convert global mean operator to ReduceMeanLayer and not Pool layer. Maybe it's a good direction to follow in tflite as well?
