### ISSUE TITLE
Error : AttributeError: 'module' object has no attribute 'maybe_download_and_extract'

### ISSUE THREAD

**Issue by Yaffa1607** [tensorflow/tensorflow#5120]
When I do : 

import cifar10
cifar10.maybe_download_and_extract()

I get the error: AttributeError: 'module' object has no attribute 'maybe_download_and_extract'
how Do I download and extract the model?

**Comment by asimshankar** [comment]
@Yaffa1607 : Please fill in all the details of the [New issue template](https://github.com/tensorflow/tensorflow/issues/new) and most importantly the steps to reproduce the problem.

I'm not quite sure what context you're using `import cifar10` in, perhaps you meant to follow this tutorial: https://www.tensorflow.org/versions/r0.11/tutorials/deep_cnn/index.html ?

**Comment by asimshankar** [comment]
Closing this out due to inactivity. Feel free to reopen if there still is an issue (and do add in the requested details). Thanks!

**Comment by PeanutMonkey** [comment]
I believe that he was referring to the tutorial: 
https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/cifar10.py

I'm having the same problem unfortunately. When calling 

`maybe_download_and_extract()`

I get

`module 'download' has no attribute 'maybe_download_and_extract'`

(I downloaded "download" through pip install) 
Is there a way around this? Thanks!

**Comment by rsk97** [comment]
I have a very similar error using the vgg16 architecture from the same tutorial spot and I also downloaded download using pip install download.
