### ISSUE TITLE
Can Mask_rcnn being converted into fully integer quantized TF Lite model?  Got error: Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select  TF Select ops: CropAndResize during converting.

### ISSUE THREAD

**Issue by JiashuGuo** [tensorflow/tensorflow#51209]
### 1. System information

- OS Platform and Distribution:  Linux Ubuntu 18.04
- TensorFlow installation: pip package
- TensorFlow library version: 2.7.0-dev20210804

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option B: provide a link to a custom end-to-end colab

Please see code to reproduce the issue in Colab [here](https://colab.research.google.com/drive/1cHh5BYiKkm1At6eStDQnwcg9xDK5E3Ci#scrollTo=bXcd5l9x6A07)

Pretrained mask_rcnn model is downloaded from: [link](https://tfhub.dev/tensorflow/mask_rcnn/inception_resnet_v2_1024x1024/1)

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ConverterError: <unknown>:0: error: loc(callsite(callsite("CropAndResize/CropAndResize@__inference___call___39142" at "StatefulPartitionedCall@__inference_signature_wrapper_44195") at "StatefulPartitionedCall")): 'tf.CropAndResize' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("CropAndResize/CropAndResize@__inference___call___39142" at "StatefulPartitionedCall@__inference_signature_wrapper_44195") at "StatefulPartitionedCall")): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite("CropAndResize_1/CropAndResize@__inference___call___39142" at "StatefulPartitionedCall@__inference_signature_wrapper_44195") at "StatefulPartitionedCall")): 'tf.CropAndResize' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("CropAndResize_1/CropAndResize@__inference___call___39142" at "StatefulPartitionedCall@__inference_signature_wrapper_44195") at "StatefulPartitionedCall")): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: CropAndResize
Details:
	tf.CropAndResize(tensor<1x64x64x1088xf32>, tensor<?x4xf32>, tensor<100xi32>, tensor<2xi32>) -> (tensor<100x17x17x1088xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}
	tf.CropAndResize(tensor<1x64x64x1088xf32>, tensor<?x4xf32>, tensor<300xi32>, tensor<2xi32>) -> (tensor<300x17x17x1088xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}
```

**Comment by abattery** [comment]
Please consider using the Select TF option. https://www.tensorflow.org/lite/guide/ops_select

**Comment by JiashuGuo** [comment]
> Please consider using the Select TF option. https://www.tensorflow.org/lite/guide/ops_select

Using select TF option in
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]`
solved the error during converting. But the converted model failed to be compiled by `edgutpu_compiler`, the output is 
`Edge TPU Compiler version 15.0.340273435
ERROR: Didn't find op for builtin opcode 'FILL' version '3'

ERROR: Registration failed.

Invalid model: model_int_quantized.tflite
Model could not be parse`

**Comment by abattery** [comment]
Could you file a separate issue for the edge tpu issue at the coral project?

**Comment by JiashuGuo** [comment]
> Could you file a separate issue for the edge tpu issue at the coral project?
Actually, I found the converted TFLite model couldn't run through the TFLite interpreter with the error: 

`Traceback (most recent call last):
  File "converter.py", line 100, in <module>
    interpreter.invoke()
  File "/home/dev/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 858, in invoke
    self._interpreter.Invoke()
RuntimeError: Input tensor 1283 lacks data
`
Do you know what does this info means?.
