### ISSUE TITLE
No performance improvement when I change prefetch() to prefetch_to_device()

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#51226]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 1.15.0
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): devtools gcc 9.3.0
- CUDA/cuDNN version: 11.2
- GPU model and memory:  single card 40536MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
bash: v1.15.4-830-g656e13f8ba: command not found(custom version)

I decode the features in the CPU and run the model in the GPU, so I need to synchronize the movement of the features from the CPU to the GPU. I found from the timeline that it took a long time to move the features. like:
![image](https://user-images.githubusercontent.com/33950866/128280087-279bb510-73f5-431b-8474-3935083a52bf.png)

 so, I would like to async memcpyH2D features by ```prefetch_to_device```, then I get a new timeline:
![image](https://user-images.githubusercontent.com/33950866/128280627-469e6a7b-b1a1-4a5b-b879-bb0aa26b7373.png)

From the timeline point of view, I expect to improve performance by more than 30%.
I successfully async memcpyH2D, but global_steps/s is same as sync memcpyH2D. I have no idea about this. please help~

**Comment by sushreebarsa** [comment]
@zhaozheng09 We see that you are using older version of tensorflow 1.15 which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Thanks!
