### ISSUE TITLE
tensorflow saved model to tf dialect mlir

### ISSUE THREAD

**Issue by ArunaKote** [tensorflow/tensorflow#51233]
May I know command available in tensorflow to convert saved_model.pb to model_tf_dialect.mlir?

Thanks

**Comment by sushreebarsa** [comment]
@ArunaKote Could you please have a look on the [link ](https://www.tensorflow.org/guide/saved_model)and let us know if it helps? Thanks!

**Comment by ArunaKote** [comment]
Thank You .But this link does not show about getting tf dialect(mlir).I tried tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --savedmodel-objectgraph-to-mlir --tf-savedmodel-exported-names=saved_model /path/to/savedmodel -o out.mlir using this I am getting tf dialect but it is encapsulated with tf.excutor .it also contains  %72 = "tf.PartitionedCall"(%71) {_collective_manager_ids = [], _read_only_resource_inputs = [], config = "", config_proto = "\0A\07\0A\03CPU\10\01\0A\07\0A\03GPU\10\002\02J\008\01\82\01\00", device = "", executor_type = "", f = @__inference_conv3_block4_1_relu_layer_call_and_return_conditional_losses_127420} : (tensor<*xf32>) -> tensor<*xf32>

and is not exactly  in the tf dialect form. May I know If I am doing any mistake in command line options?


Thanks.

**Comment by ymodak** [comment]
Have you tried [tf.mlir.experimental.convert_graph_def()](https://www.tensorflow.org/api_docs/python/tf/mlir/experimental/convert_graph_def) for your case?
