### ISSUE TITLE
Training weak learners in using video or image dataset on TensorFlow

### ISSUE THREAD

**Issue by Srkshaikh5** [tensorflow/tensorflow#51237]
Hi I have a problem statement where I have to train an action recognizer using videos.
but due to non availability of good dataset there is a slight misclassification.
Is there any setting or function where I can train the misclassified or weak learners by assigning them more weights.
Its sounds similar like Xgboost but I want something which can work on Deeplearning frame works and on Image and Video data set

Thanks.

**Comment by sushreebarsa** [comment]
@Srkshaikh5 Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!
