### ISSUE TITLE
How can I use multi_gpu in tf.keras?

### ISSUE THREAD

**Issue by llfzllfz** [tensorflow/tensorflow#51236]
How can I use multi_gpu in tf.keras?
WARNING:tensorflow:From train_conv.py:214: multi_gpu_model (from tensorflow.python.keras.utils.multi_gpu_utils) is deprecated and will be removed after 2020-04-01.

**Comment by sushreebarsa** [comment]
@llfzllfz Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
