### ISSUE TITLE
Tensorflow tf.map_fn over ragged tensor fails with object of type 'RaggedTensor' has no len

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#51234]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (both RHEL 7 Power PC and Ubuntu 21.04 with Intel)

- TensorFlow installed from (source or binary): conda install tensorflow
- TensorFlow version (use command below): Tested on 2.4.1 and 2.5.0
- Python version: 3.7.10
- CUDA/cuDNN version: cudatoolkit 10.1.243 (Intel) and 10.2 (PowerPC)
- GPU model and memory: 2080TI (Intel) and A100 (PowerPC)

```
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)
> "
2021-08-04 23:57:32.182116: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
unknown 2.4.1
```

**Describe the current behavior**

https://stackoverflow.com/questions/68658093/tensorflow-tf-map-fn-over-ragged-tensor-fails-with-object-of-type-raggedtensor
This Tensorflow doc gives this example of using tf.map_fn on ragged tensors which works for Tensorflow 2.4.1 and above:

```
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
print(tf.map_fn(tf.math.square, digits))
```
However the following example results in error "object of type 'RaggedTensor' has no len" when run in Tensorflow 2.4.1 or Tensorflow 2.5:

```
import tensorflow as tf

X=tf.ragged.constant([[1.,2.],[3.,4.,5.]], dtype=tf.float32)

@tf.function
def powerX(i):
    global X
    return X**i

Y = tf.map_fn(powerX, tf.range(3, dtype=tf.float32))
```

**Describe the expected behavior**

It should return a ragged tensor.   

**Standalone code to reproduce the issue**

```
import tensorflow as tf

X=tf.ragged.constant([[1.,2.],[3.,4.,5.]], dtype=tf.float32)

@tf.function
def powerX(i):
    global X
    return X**i

Y = tf.map_fn(powerX, tf.range(3, dtype=tf.float32))
```

**Comment by sanatmpa1** [comment]
@catskillsresearch,

I am able to reproduce the error in `TF 2.5` and `TF nightly`. Please find the [gist here](https://colab.research.google.com/gist/sanatmpa1/fca7b3cb87d6bc407453600b4c784472/51234.ipynb).

**Comment by catskillsresearch** [comment]
Any luck on this?  I'm finding it extremely hard to parallelize any function that involves tf.where and tf.gather resulting in any intermediate step where there are unequal length tensors.  This makes Tensorflow super difficult and unsuitable for coding parallel algorithms as opposed to doing cookbook machine learning stuff where everything is the same size.

**Comment by edloper** [comment]
When you use `tf.map_fn` with RaggedTensors, you currently need to specify the output signature of your function.  In this case, your function returns a 2D RaggedTensor, so either of the following will work:

```
Y = tf.map_fn(powerX, tf.range(3, dtype=tf.float32), 
              fn_output_signature=tf.RaggedTensorSpec([None, None], tf.float32))
```

Or:

```
Y = tf.map_fn(powerX, tf.range(3, dtype=tf.float32), 
              fn_output_signature=tf.RaggedTensorSpec([2, None], tf.float32))
```

**Comment by edloper** [comment]
(The reason the `tf.map_fn(tf.math.square, digits)` example works without specifying the output signature is that the output signature is identical to the input signature.  In that case, you don't need to specify it.)

**Comment by catskillsresearch** [comment]
Thanks for the clarification. My experience on `tf.map_fn` is that it will not, in any event, result in parallel kernels running on the GPU.  It's about the same as a Python `for` loop.  The only way to get real parallelism is with `tf.vectorized_map`, with same-sized tensors. This requires some very tedious refactoring of methods and padding of vectors and clever tricks so that the algorithm for 1 problem instance of size M1 can be inside-outed for N problems  into a sequence of pure vector operations that operate on uniformly sized vectors of size max(M1,...MN).  I'm not sure if the experience would be the same if I tried to go down the `cupy` route.  In any event it's quite frustrating.

**Comment by mohantym** [comment]
Hi @catskillsresearch !
I was able to get output by lamda function. 
Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/5a8d5187b48a0fafe0c5e502aa64bffd/51234.ipynb#scrollTo=W-qBG0YahqwI) for reference.

Thank you!
