### ISSUE TITLE
kears.Model memory leak and tf.funtion block the thread

### ISSUE THREAD

**Issue by yangtao121** [tensorflow/tensorflow#51243]
I tried to run Keras Model by multiprocessing.Process for RL, it has some problems. The code as belows:

```python
def get_action(self, obs):
    mu, sigma = self.Model(obs)

    dist = tfp.distributions.Normal(mu, sigma)
    action = tf.squeeze(dist.sample(), axis=0)
    prob = tf.squeeze(dist.prob(action), axis=0)

    return action, prob
```

This code will cause memory leak,but it can work in multiprocess. Then I add `tf.function` decorator, it can run in single process, and has no more memory leak,. However, I when I try to run in multiprocess, this function will block the thread.

**Comment by sushreebarsa** [comment]
@yangtao121 Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by yangtao121** [comment]
thanks I will
