### ISSUE TITLE
Documentation request: NN regression

### ISSUE THREAD

**Issue by ldmtwo** [tensorflow/tensorflow#5126]
There is a disconnect between the CSV documentation and the regression docs. I've documented one example here: http://stackoverflow.com/questions/40093776/csv-tensorflow-regression-via-neural-network-model

I would like to request clearer examples of feeding neural networks with CSV or NDArrays. Most of the NN examples I've seen were strictly classification. They do not show how to take Numpy NDarrays (features x instances or class column) or CSV to predict a regression column.

The documentation I found on these pages below was confusing or vague. Overall, there are major gaps for doing the task above. The proposed documentation would clearly demonstrate with complete code using any of these: DNNRegressor, TensorFlowDNNRegressor, LinearRegressor, TensorFlowLinearRegressor, TensorFlowRNNRegressor, TensorFlowRegressor. If such documentation exists and I have yet to discover it, please advise me. Thanks.

- Base code that reads CSV and works (classifier): https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html
- Regressor: https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.learn.html#DNNRegressor
- CSV reading: https://www.tensorflow.org/versions/master/how_tos/reading_data/index.html#csv-files
- Column embedding: https://www.tensorflow.org/versions/r0.11/tutorials/wide_and_deep/index.html
- List of APIs (DNNRegressor, TensorFlowDNNRegressor, LinearRegressor, TensorFlowLinearRegressor, TensorFlowRNNRegressor, TensorFlowRegressor): https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.learn.html

**Comment by asimshankar** [comment]
@ldmtwo : I'm sorry that the documentation is lacking. We welcome pull requests to improve them! So, please don't hesitate to contribute.

Since the issue description is a bit broad, I'm going to close this out. But if you can point out specific examples of what you find vague on individual documents, we'll be happy to address those (in which case re-open this issue or file a new one).
