### ISSUE TITLE
TFLite GPU Delegate with OpenGL wrong output

### ISSUE THREAD

**Issue by sylajarlind** [tensorflow/tensorflow#51276]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Dragonboard 845c (db845c)
- TensorFlow installed from (source or binary): Yes
- TensorFlow version (use command below): 2.4.2
- Python version:
- Bazel version (if compiling from source): 4.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I am running a tflite ssd mobilenet face detection model on CPU and the results are correct but when I delegate to GPU using code below I get wrong results ( score is max): 
```
const TfLiteGpuDelegateOptionsV2 options = {
            .is_precision_loss_allowed = 1, // FP16
            .inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER,
            .inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY,
            .inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
            .inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
            .experimental_flags = TFLITE_GPU_EXPERIMENTAL_FLAGS_GL_ONLY,
        };

        TfLiteDelegate *delegate = TfLiteGpuDelegateV2Create(&options);
        if (m_interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk)
        {
            std::cerr << "Failed to modify graph with delegate" << std::endl;
            exit(0);
        }
``` 

I have tried more than 3 models and the results are the same, on CPU is working correctly but on gpu no detection or output is trash. 

> NOTE: I have Dragonboard 845 running latest Android 11 (flashed from master branch) and it currently supports only OpenGL.

Output when delegating: 

```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
98 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
INFO: Replacing 98 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions.
INFO: Initialized OpenGL-based API.
INFO: Created 1 GPU delegate kernels.
```

**Describe the expected behavior**
Model should have same results when delegating on GPU using OpenGL only.

> For reference I will upload tflite model also.
[face_ssd_mobilenet_v2.tflite.zip](https://github.com/tensorflow/tensorflow/files/6940801/face_ssd_mobilenet_v2.tflite.zip)

**Comment by abattery** [comment]
@impjdi could you take a look?

**Comment by impjdi** [comment]
what happens when you set
```
            .is_precision_loss_allowed = 0
```
?

**Comment by sylajarlind** [comment]
Same results

> what happens when you set
> 
> ```
>             .is_precision_loss_allowed = 0
> ```
> 
> ?

**Comment by sylajarlind** [comment]
[opengl_tflite_fail.txt](https://github.com/tensorflow/tensorflow/files/6944107/opengl_tflite_fail.txt)
**adb logcat when running model with gpu delegate on OpenGL**

**Comment by sylajarlind** [comment]
**Extra info:**
When delegating with XNNPACK: 
```
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 191 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 12 partitions.
```
results are good, inference time is lower (I get around 8fps compared to running on CPU without delegate with 3fps)

**Comment by sylajarlind** [comment]
@impjdi any idea why this is happening?

**Comment by impjdi** [comment]
If `.is_precision_loss_allowed = 0` and you're still seeing that, something is really broken.  Given that a lot of models use `CONV_2D` and `DEPTHWISE_CONV_2D`, I doubt there's bugs there.  I suspect reshapes and concats are not versatile as on the CPU and you might be hitting a corner case.

**Comment by sylajarlind** [comment]
I am building Tensorflow from latest master in bazel and my executable there, I really want to see if this has to do anything with the implemented OpenGL drivers from MESA-Freedreno as I don't have a device with proprietary Qualcomm driver implementation. I have tried one of this models and I didn't have any of these problems before.

**Comment by impjdi** [comment]
We have a decent amount of specialization logic (behave different if a certain GPU model, or have specialized code for 3x3 convolution, etc.), and the majority of the code path will be for Arm Mali & Qualcomm Adreno.  You might be hitting a corner case either hitting a specialization that isn't used anywhere, or MESA-Freedeno has a different behavior on undefined behavior; e.g. drivers behave differently when you access memory out of bounds.

**Comment by sylajarlind** [comment]
Do you have any suggestions on where should I file this issue or how to properly debug?

**Comment by impjdi** [comment]
This is the right component, but all the owners are out for an extended period of time (some until next January), and you won't get a response in a reasonable time frame.

If you want to debug and isolate the issue yourself, the best is bisecting the graph and isolating the problem to a single operation with specific input/output dimension.

**Comment by sylajarlind** [comment]
This is happening on latest master build, which is currently tensorflow-2.5.0

**Comment by tilakrayal** [comment]
@sylajarlind ,
Is this still an issue?
Could you update TensorFlow to the latest stable version v.2.9 and let us know if you are facing the same error. Thanks!
