### ISSUE TITLE
 ValueError: Input 0 of node model/x/ was passed float from model/x/resource:0 incompatible with expected resource 

### ISSUE THREAD

**Issue by sunw70** [tensorflow/tensorflow#51277]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow installation: pip package 
- Tensorflow version: 2.4.1
- Python version: 3.8

### 2. Code

I created a Keras custom layer which implements a custom causal Conv1D. To do it, I simply used the classes Conv and Conv1D (they are in tensorflow/python/keras/layers/convolutional.py) and modified Conv. I'll show you how I use this layer with a very silly example dataset, which is characterized by only two training samples (given an ordered sequence of numbers as a training sample, the model should predict its next sequence: for example, if I've [0, 1, 2] the output will be [3, 4, 5]). However I get the following warnings and errors (I read similar problems, but this seems a little bit different):

    Epoch 1/10
    WARNING:tensorflow:Gradients do not exist for variables ['MyConv/kernel:0'] when minimizing the loss.
    WARNING:tensorflow:Gradients do not exist for variables ['MyConv/kernel:0'] when minimizing the loss.
    2/2 [==============================] - 1s 1ms/step - loss: 113.0949 - accuracy: 1.0000
    Epoch 2/10
    2/2 [==============================] - 0s 1ms/step - loss: 117.4004 - accuracy: 1.0000
    Epoch 3/10
    2/2 [==============================] - 0s 1ms/step - loss: 124.0515 - accuracy: 1.0000
    Epoch 4/10
    2/2 [==============================] - 0s 994us/step - loss: 132.9754 - accuracy: 1.0000
    Epoch 5/10
    2/2 [==============================] - 0s 1ms/step - loss: 154.4105 - accuracy: 1.0000
    Epoch 6/10
    2/2 [==============================] - 0s 4ms/step - loss: 157.2047 - accuracy: 1.0000
    Epoch 7/10
    2/2 [==============================] - 0s 981us/step - loss: 184.0751 - accuracy: 1.0000
    Epoch 8/10
    2/2 [==============================] - 0s 902us/step - loss: 201.2888 - accuracy: 1.0000
    Epoch 9/10
    2/2 [==============================] - 0s 888us/step - loss: 219.6019 - accuracy: 1.0000
    Epoch 10/10
    2/2 [==============================] - 0s 5ms/step - loss: 238.6077 - accuracy: 1.0000

    ValueError: Input 0 of node model/MyConv/model/MyConv/strided_slice/_assign was passed float from 
    model/MyConv/ReadVariableOp/resource:0 incompatible with expected resource.

I attached the example code used to train the model:
[model.zip](https://github.com/tensorflow/tensorflow/files/6941085/model.zip)

**Comment by abattery** [comment]
For the better story of variable support, please consider using Select TF ops and converter.experimental_enable_resource_variables = True by using the TensorFlow 2.7 candidate or TensorFlow 2.6 versions.

**Comment by sunw70** [comment]
Thanks @abattery for your reply. I upgraded to TensorFlow 2.6.0rc2, but now it appears this error:

    Traceback (most recent call last):
    File "model.py", line 406, in <module>
    model = build_model(x_train, y_train)
    File "model.py", line 373, in build_model
    r=Myconv1D(filters=1,kernel_size=3,padding='causal',dilation_rate=1,use_bias=False,name="MyConv")(inp)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1057, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
    File "model.py", line 181, in call
    z[0,4+i,0].assign(inputs[0,i,0])  
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1235, in assign
    return var._strided_slice_assign(
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1392, in   
    _strided_slice_assign
    value=ops.convert_to_tensor(value, dtype=self.dtype),
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 346, in    
     _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 271, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 283, in    
    _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 308, in   
    _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
    File "/home/es/venv/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 106, in    
    convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
    File "/home/es/venv/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 244, in __array__
    raise TypeError(
    TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a     
    symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF    
    API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the     
    Functional Model.

**Comment by abattery** [comment]
Please export the keras model as a saved model and use the `from_saved_model` api instead.

**Comment by sunw70** [comment]
Now I'm using SavedModel format in this way at the end of file, after `model = build_model(x_train, y_train)`:

    model.save('my_model')     
    converter = tf.lite.TFLiteConverter.from_saved_model('my_model')
    converter.experimental_enable_resource_variables = True
    tflite_model = converter.convert()
    open(tflite_model_name + '.tflite', 'wb').write(tflite_model)

However the error remains: it seems that it happens before TFLite converter is called.
If I use SavedModel format, should I add another code to use the custom layer?

**Comment by abattery** [comment]
I would recommend using tf.saved_model.save API instead. https://www.tensorflow.org/api_docs/python/tf/saved_model/save

**Comment by abattery** [comment]
If the error happens at the exporting stage, please upload a new post regarding the failure of the keras exporting to the saved model.
