### ISSUE TITLE
[GPU DELEGATE] [2.5.0] Failed to apply delegate: TfLiteGpuDelegate Init: MUL: Expected a 3D tensor of shape HxWxC or a 4D tensor of shape 1xHxWxC but got 12x4

### ISSUE THREAD

**Issue by MaybeAndroid** [tensorflow/tensorflow#51348]
System information

OS Platform and Distribution: Android all possible versions
TensorFlow version : 2.5.0
Describe the current behavior
Gpu delegate failed to initialize with model

java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: TfLiteGpuDelegate Init: MUL: Expected a 3D tensor of shape HxWxC or a 4D tensor of shape 1xHxWxC but got 12x4 TfLiteGpuDelegate Prepare: delegate is not initialized Node number 243 (TfLiteGpuDelegateV2) failed to prepare.

implementation("org.tensorflow:tensorflow-lite:2.5.0")
implementation("org.tensorflow:tensorflow-lite-gpu:2.5.0")

**Comment by sushreebarsa** [comment]
@MaybeAndroid In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by MaybeAndroid** [comment]
> @MaybeAndroid In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

`   val options = Interpreter.Options().apply{
        if(compatList.isDelegateSupportedOnThisDevice){
            // if the device has a supported GPU, add the GPU delegate
            val delegateOptions = compatList.bestOptionsForThisDevice
            this.addDelegate(GpuDelegate(delegateOptions))
        } else {
            // if the GPU is not supported, run on 4 threads
            this.setNumThreads(4)
        }
    }

    val interpreter = Interpreter(model, options)
`

All according this article - https://www.tensorflow.org/lite/performance/gpu

**Comment by abattery** [comment]
@impjdi could you take a look?

**Comment by impjdi** [comment]
looks like the MUL is malformed with bad dimensions.  If you have A MUL B, then the dimensions of A and B must match.

**Comment by MaybeAndroid** [comment]
According to the advice in #45845 thread I checked 2.3.0 and 2.2.0 version of gpu delegate and they are working well with the model. I'm not familiar with internal structure of calculation, it looks like the 2.5.0 is corrupted.

**Comment by MaybeAndroid** [comment]
> looks like the MUL is malformed with bad dimensions. If you have A MUL B, then the dimensions of A and B must match.

According to the advice in #45845 thread I checked 2.3.0 and 2.2.0 version of gpu delegate and they are working well with the model. I'm not familiar with internal structure of calculation, it looks like the 2.5.0 is corrupted.

**Comment by mohantym** [comment]
Hi @MaybeAndroid !
We are checking to see whether you still need help in this issue .
Have you checked this issue in TF 2.9/2.10 version yet.
Thank you!
