### ISSUE TITLE
Possible bug with session handle as feed dict input

### ISSUE THREAD

**Issue by kevint324** [tensorflow/tensorflow#51344]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version:Python 3.8.5 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 (nvcr.io/nvidia/tensorflow:21.03-tf2-py3)
- GPU model and memory: TeslaT4

```
$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2021-08-06 02:34:51.763077: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
unknown 2.4.0
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Below is the minimum reproduce code snippet derived from 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/v1_compat_tests/session_ops_test.py#L249

```python
"""Tests for tensorflow.ops.session_ops."""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from tensorflow.python.framework import constant_op
from tensorflow.python.framework import ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import session_ops
from tensorflow.core.protobuf import rewriter_config_pb2
import tensorflow as tf
import sys
import time

tf.debugging.set_log_device_placement(True)

def testFeedOneHandleDirectly():
  config = tf.compat.v1.ConfigProto()
  config.graph_options.optimizer_options.opt_level = -1
  config.allow_soft_placement = True
  config.graph_options.rewrite_options.constant_folding = (
      rewriter_config_pb2.RewriterConfig.OFF)
  config.graph_options.rewrite_options.pin_to_host_optimization = (
      rewriter_config_pb2.RewriterConfig.OFF)
  with tf.compat.v1.Session(config=config) as sess:

    a = constant_op.constant(10.0)
    b = constant_op.constant(5.0)
    c = math_ops.multiply(a, b)
    d = math_ops.multiply(c, c)

    h_c = sess.run(session_ops.get_session_handle(c))
    print(sess.run(d, feed_dict={c: h_c}))
    #print("result = %f " % d.eval())


testFeedOneHandleDirectly()

```

Run  with command 
```
python handle_test.py
```
or
```
TF_CPP_MIN_VLOG_LEVEL=2 python handle_test.py 2>&1 | tee log.txt
```

**Describe the current behavior**
d = c * c = (a * b) * (a * b) = (10 * 5) * (10 * 5) = 2500.00
If you run above script on cpu or gpu you'll get the correct result, but it seems there is something fishy underneath.

We are running tensorflow unit tests on our asic chip to verify our chip works properly on tensorflow and we failed on this test
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/v1_compat_tests/session_ops_test.py#L249

The error was related to memory copy between CPU and device. 
We found a peculiar CopyCPUTensorToGPU call which invoked
  Stream &ThenMemcpy(DeviceMemoryBase *gpu_dst, const void *host_src,  uint64 size);
The fishy part is that both gpu_dst and host_src are device pointers, which later triggered an error in our driver.

Then we tried the same piece of code on GPU and surprisingly on GPU it has exactly the same issue. But the funny part is it seems nvidia cuda driver silently handled the wrong memory copy call. If you pass two device pointers to cuMemcpyHtoDAsync it just does a silent D2D copy and reports nothing. But on our platform it is illegal to call H2D memcpy interface with two device pointers.

```
I tensorflow/core/common_runtime/gpu/gpu_util.cc:303] CopyCPUTensorToGPU                                                                                                                            
I tensorflow/stream_executor/stream.cc:1543] [stream=0x2c48a6e0,impl=0x2c489490] Called Stream::ThenWaitFor(other=0x61ba9a0)
I tensorflow/stream_executor/stream.cc:4655] [stream=0x2c48a6e0,impl=0x2c489490] Called Stream::ThenMemcpy(gpu_dst=0x7f6860000800, host_src=0x7f6860000700, size=4)
```

**Describe the expected behavior**

When call CopyCPUTensorToGPU it should have a device pointer as dest address and a host address as source address.
It seems to me the there is something flaky with the session handle mechanism.
the **h_c** got a session(resource) handle and corresponding resource is on devices. and when you pass h_c to feed dict it always assume the feed is on host and tries to send it to device again.
```
sess.run(d, feed_dict={c: h_c})
```

https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No, I'm not sure how to fix it
- Briefly describe your candidate solution(if contributing):

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

[log.txt.gz](https://github.com/tensorflow/tensorflow/files/6942630/log.txt.gz)

**Comment by sushreebarsa** [comment]
@Saduf2019  Was able to reproduce the issue in TF v2.4 , TF v2.5 , please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/648145f54639cb34e614669fcafa4add/untitled357.ipynb)here.Thanks!

**Comment by jvishnuvardhan** [comment]
@kevint324 Can you please check with recent TF versions and let us know whether the issue persisting or not. Thanks!

**Comment by kevint324** [comment]
@jvishnuvardhan  The issue is valid on tf2.4 and tf2.5.  by recent you mean  tf2.6 or master? Is there a related bugfix or something?

**Comment by jvishnuvardhan** [comment]
> by recent you mean tf2.6 or master?

Yes. `2.6` or `tf-nightly`. Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
