### ISSUE TITLE
TF1.13.1 how to shiled tensorflow device mapping information?

### ISSUE THREAD

**Issue by MrCrazyCrab** [tensorflow/tensorflow#51340]
i don't want to print the device mapping information in my console when i am training my model, i tried some methods, which only can shiled the tensorflow warning information. How should i do to shiled device mapping and the first warning?
![image](https://user-images.githubusercontent.com/52489106/128446262-5779c7bc-450b-4eab-9dd4-efd770401d1b.png)
![image](https://user-images.githubusercontent.com/52489106/128446278-17fe472b-93e4-4b8f-974c-783255eb3bad.png)

**Comment by sushreebarsa** [comment]
@MrCrazyCrab We see that you are using old version of tensorflow  1.13 which is officially considered as end of life hence not actively supported , We recommend that you upgrade to latest stable version of TF (2.5) and let us know if the issue still persists in newer versions Thanks!
