### ISSUE TITLE
type dependent output

### ISSUE THREAD

**Issue by superplay1** [tensorflow/tensorflow#51349]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 5.8.14-arch1-1
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.6

**Describe the current behavior**
Output is type dependent
**Describe the expected behavior**
It should not be type dependent

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? ?
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import tensorflow as tf
print(tf.range(21.70725420531782, 42.707254205317824,dtype=tf.float64))
print(tf.range(21.70725420531782, 42.707254205317824,dtype=tf.float32))
```

**Comment by kumariko** [comment]
@Saduf2019 I am able to reproduce the error in [**`TF v2.5`** ](https://colab.research.google.com/gist/kumariko/98e2b572f9ab95e93632c0fe7f709010/51349.ipynb ),[**`TF nightly`**](https://colab.research.google.com/gist/kumariko/b383fc69c00b004740a79b7025dc6f9f/51349.ipynb) and [**`TF v2.4`**](https://colab.research.google.com/gist/kumariko/f972bbd2364a95cf2a279b32d51bce19/untitled4.ipynb) Please find the gists for your reference here. Thanks!

**Comment by Saduf2019** [comment]
@superplay1 
This is expected behavior, there is minor difference in the output.

**Comment by superplay1** [comment]
Yes, so my problem is the not the difference in the values but the size of the output vector. In the documentation it says that 
`tf.range(start, limit, delta=1, dtype=None, name='range')`
the output does not include limit, but for `dtype=float64` it does.

**Comment by Saduf2019** [comment]
@superplay1 
Can you please share the document link you are referring to.
