### ISSUE TITLE
Out-of-memory error in eager mode loop

### ISSUE THREAD

**Issue by esghif** [tensorflow/tensorflow#51354]
Following code gives an out-of-memory error when running in tensorflow-2.5. The code itself does not do anything useful it is just meant to highlight what I believe is a problem.

For the small problem (i.e. ```b, a, c = 1, 1000, 5 # small problem```) the program completes. For the large problem (i.e. ```b, a, c = 1, 10000, 5 # large problem```) the program runs out of memory.

My expectation would have been that in eager mode allocated tensors have the lifetime of one iteration, while it seems more memory is being allocated with each iteration. Similar code with identical parameters runs in Pytorch.

Am I wrong in my expectation or is this a bug? If I am wrong how could I do this in Tensorflow?

```python
import tensorflow as tf

from tensorflow.keras.losses import Loss

class EagerOom(Loss):

    def __init__(self):
        super(EagerOom, self).__init__()

    def __call__(self, targets, logits):
        logits = tf.reshape(logits, [-1])
        targets = tf.reshape(targets, [-1])
        return self.inner(targets, logits)


    @tf.custom_gradient
    def inner(self, targets, logits):

        g_logits = tf.zeros_like(logits)

        for idx in range(len(targets)):
            print(f"idx: {idx}")
            g_logits_upd = logits - logits[idx]
            g_logits += g_logits_upd
        
        loss = tf.reduce_mean(targets * logits)

        def grad_fn(upstream):
            g_targets = tf.zeros_like(targets)
            return g_targets, g_logits

        return loss, grad_fn



def main():
    tf.random.set_seed(0)
    # b, a, c = 1, 1000, 5 # small problem
    b, a, c = 1, 10000, 5 # large problem
    logits = tf.random.normal((b, a, c))
    targets = tf.random.uniform((b, a), 0, c + 1, dtype=tf.int32)
    targets = tf.one_hot(targets, depth=c, axis=-1)
    loss_fn = EagerOom()
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(logits)
        loss = loss_fn(targets, logits)
    print("Done.")


if __name__ == '__main__':
    main()
```

**Comment by tilakrayal** [comment]
Have you considered limiting gpu memory growth?
Make sure you close all python sessions and exit python interpreter to free up memory and try running script as:

```
#On top of your script
import tensorflow as tf
gpu = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu[0], True) #limits gpu memory
# Rest of your code
```

**Comment by esghif** [comment]
Thanks for your suggestion I tried it out. I don't see any change, it still runs out of memory.

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf 2.4,v2.5 and tf-nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/002f2769f9e5f67886c67f0e29268e92/untitled51354.ipynb).

**Comment by Saduf2019** [comment]
@esghif 
Can you lower your [batch size](https://github.com/tensorflow/tensorflow/issues/16768#issuecomment-405587015), also try  kill -9 PID and run again and let us know.

**Comment by esghif** [comment]
Batch size is 1. OOM persists.

**Comment by Saduf2019** [comment]
@esghif 
Check with nvidia-smi. [this is not a tf issue, can u close it here and create in discussion forum as there are more supporters there to suggest]

colab_00_introduction.ipynb - Colaboratory
https://colab.research.google.com/github/drinkingkazu/2019-06-17-NeuralNets/blob/master/Preparation%20-%205%20Minutes%20Colaboratory.ipynb

**Comment by esghif** [comment]
Is there any chance that someone will address the issue I am raising? The loop in the example should not lead to an OOM error irrespective of the number of iterations.

**Comment by esghif** [comment]
Hi *, I tried it out again with tf 2.6 and 2.8.0-dev20211104. Both led to OOM as previously. @jvishnuvardhan when b=1000 is the small problem that worked previously also. For b=10000 it still leads to OOM.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
