### ISSUE TITLE
TensorArray Can't be used for tf.concat?

### ISSUE THREAD

**Issue by ymzlygw** [tensorflow/tensorflow#51350]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf2.3
- Python version: python 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 10.1
- GPU model and memory: None

**Describe the current behavior**
I want to use model.fit but in my model definition, I use python list and for loop. So I want to change it by using TensorArray.
but I have tf.concat after for loop. So I test following code to see if it works:
```python
a = tf.ones([2,3])
b = [a] * 2

ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
ta = ta.write(0, a)
ta = ta.write(1, a)
ta = ta.stack()

d1 = tf.concat(b, axis=1)
print("d1:", d1)

d2 = tf.concat(ta, axis=1)
print("d1:", d2)

But  I get these results:  
------------------------------------------------
d1: tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(2, 6), dtype=float32)

d1: tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)
------------------------------------------------
**Describe the expected behavior**
I want TensorArray have the same shape as result of "d1", but nothing changed. It's a bug?
d1: tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(2, 6), dtype=float32)

IF not bug, please tell me how to change TensorArray shape with tf.concat? Thanks
```
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Comment by sushreebarsa** [comment]
@ymzlygw In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymzlygw** [comment]
> @ymzlygw In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

There is no error messages but only wrong result. Code is simple as:
---------------------------
import tensorflow as tf
a = tf.ones([2,3])
b = [a] * 2

ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
ta = ta.write(0, a)
ta = ta.write(1, a)
ta = ta.stack()

d1 = tf.concat(b, axis=1)
print("d1:", d1)

d2 = tf.concat(ta, axis=1)
print("d1:", d2)
--------------------------

**Comment by MaanasArora** [comment]
Hi @ymzlygw,

You're using `tf.concat` over a `TensorArray`, and `tf.concat` seems only to support lists (see [documentation](https://www.tensorflow.org/api_docs/python/tf/concat)). Instead, you can use [`TensorArray.concat()`](https://www.tensorflow.org/api_docs/python/tf/TensorArray#concat).

Let me know if this solves the issue, thanks.

**Comment by ymzlygw** [comment]
> Hi @ymzlygw,
> 
> You're using `tf.concat` over a `TensorArray`, and `tf.concat` seems only to support lists (see [documentation](https://www.tensorflow.org/api_docs/python/tf/concat)). Instead, you can use [`TensorArray.concat()`](https://www.tensorflow.org/api_docs/python/tf/TensorArray#concat), i.e. call `ta.concat():`
> 
> ```
> a = tf.ones([2,3])
> b = [a] * 2
> 
> ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
> ta = ta.write(0, a)
> ta = ta.write(1, a)
> ta = ta.stack()
> 
> d1 = tf.concat(b, axis=1)
> print("d1:", d1)
> 
> d2 = ta.concat()
> print("d1:", d2)
> ```
> 
> Let me know if this resolves the issue, thanks.

Thanks for your reply , yeah,  as  I said above: """ I find that I can use [TensorArray.concat() + tf.reshape(ta, shape= [X,X])] to achieve the correct the result( as tf.concat(list) do ), but it's a little bad because you should caculate the resize_shape before. And in factly I want that TensorArray can do it itself ,  Maybe developer can develop it to support this?"""

**Comment by sushreebarsa** [comment]
@Saduf2019  Was able to replicate the issue in TF v2.3,2.4 & 2.5 , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/861bf61854b276b163b2f68b23cb5f78/untitled365.ipynb#scrollTo=HPDGc-XGqzHo) for reference.Thank you!

**Comment by sushreebarsa** [comment]
@ymzlygw I tried to replicate the issue on colab using TF v2.8.0 ,could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c5c43df35ef74203e1328d9d7965a485/51350.ipynb) and the  outcome as follows.Please let us know if it helps?
```
[<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>, <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>]
[<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>, <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>]
d1: tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(2, 6), dtype=float32)
d1: tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(2, 6), dtype=float32)
```
Thanks!
