### ISSUE TITLE
How to interpret the model analysis report of TensorFlow2

### ISSUE THREAD

**Issue by Misoknisky** [tensorflow/tensorflow#51358]
2021-08-07 22:21:14.783664: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-07 22:21:14.783849: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-07 22:21:14.783983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7077 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-08-07 22:21:14.790480: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 216 nodes (198), 329 edges (310), time = 3.612ms.
  function_optimizer: function_optimizer did nothing. time = 0.07ms.
How should we understand these two times（time = 3.612ms and time = 0.07ms）?

**Comment by Misoknisky** [comment]
The tensorflow version is 2.4.0 with gpu

**Comment by tilakrayal** [comment]
@Misoknisky ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Thanks!

**Comment by Misoknisky** [comment]
> @ tilakrayal ,
> 

###  Hellow, i use code  like this 
`import tensorflow as tf
from tensorflow.python.keras.engine.base_layer import Layer
from tensorflow.keras.layers import Conv2D
from tensorflow.python.profiler.model_analyzer import profile
from tensorflow.python.profiler.option_builder import ProfileOptionBuilder
print('TensorFlow:', tf.__version__)


model = tf.keras.applications.ResNet50()
forward_pass = tf.function(
    model.call,
    input_signature=[tf.TensorSpec(shape=(1,) + (1, 1, 3))])

graph_info = profile(forward_pass.get_concrete_function().graph,
                        options=ProfileOptionBuilder.float_operation())

print('Flops: {:,}'.format(flops))     # 7
`
The ### outpus:
> 22:21:14.790480:** I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: 
  graph_to_optimize  

> function_optimizer: Graph size after: 216 nodes (198), 329 edges (310), time = 3.612ms.  

> function_optimizer: function_optimizer did nothing. time = 0.07ms.  


Before getting the FLOPS results, there aforementioned outputs are confusing, I don't know how to interpret the both time = 3.612ms and time = 0.07ms.

**Comment by tilakrayal** [comment]
@Misoknisky ,
On running the given code snippet, I am facing an error stating **NameError: name 'flops' is not defined**. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6aea252d919ae748643b57f3491d995f/untitled46.ipynb).Please provide the complete code to reproduce the issue.Thanks!

**Comment by tilakrayal** [comment]
@Misoknisky ,

Please take a look at this links for more information on how to interpret the model.[Link1](https://towardsdatascience.com/interpretability-in-machine-learning-70c30694a05f),[Link2](https://towardsdatascience.com/explainable-artificial-intelligence-part-3-hands-on-machine-learning-model-interpretation-e8ebe5afc608),It helps.Thanks!
