### ISSUE TITLE
How do I train a semantic segmentation to recognise only one type of object? 

### ISSUE THREAD

**Issue by Yaffa1607** [tensorflow/tensorflow#5136]
I want to detect and segment hands in images and that is the only thing I want to detect. 
I 'm using FCN. How do I train it to recognise only the object I want ?

**Comment by asimshankar** [comment]
@Yaffa1607 : Thanks for your question, but I believe it is better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). The github issues are meant to be focused on bugs or feature requests. Thanks much.
