### ISSUE TITLE
transfer learning model based on universal sentence encoder cannot save to tf model for tensorflow serving

### ISSUE THREAD

**Issue by jacksonfengwa** [tensorflow/tensorflow#51378]
The model is created using the following codes,

    model = tf.keras.models.Sequential()

    model.add(hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4", input_shape=[], output_shape=[512], dtype=tf.string, trainable=False))

    model.add(tf.keras.layers.Dense(10, activation='relu'))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

    model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

......
    model.fit(X_train, Y_train, epochs=1, validation_data=(X_test, Y_test))
    model.save(model_save_loc)
......

I tried tensorflow 2.5.0 and 2.2.0. Both gave me the following exception when I saved the model after fully training it, (model training works perfectly)

Traceback (most recent call last):
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py", line 277, in __del__
    self._destroy_resource()
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 924, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3022, in __call__
    filtered_flat_args) = self._maybe_define_function(args, kwargs)
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/feng/workspace/venv3.8/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
AttributeError: 'NoneType' object has no attribute '__wrapped__'

**Comment by jacksonfengwa** [comment]
To reproduce, please simply create the model using the codes and save it in 'tf' format. TIA

**Comment by sushreebarsa** [comment]
@jacksonfengwa 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by sushreebarsa** [comment]
@jacksonfengwa Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by jacksonfengwa** [comment]
@sushreebarsa  If you look at the codes, all the issues happen in tensorflow, instead of keras. any particular reason you want this issue to move to keras?

**Comment by sushreebarsa** [comment]
@jacksonfengwa This issue is more related to save and load Keras model . For more information please have a look on the [link](https://www.tensorflow.org/tutorials/keras/save_and_load) , [link1](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) ,[ link2](https://keras.io/guides/training_with_built_in_methods/) and let us know if it helps ?Thanks!

**Comment by jacksonfengwa** [comment]
Thanks sushreebarsa. Just opened a ticket there. will see how it goes.

**Comment by sushreebarsa** [comment]
@jacksonfengwa Thank you for the update .Could you please move this issue to closed status as you have opened a new ticket in Keras repo , you will get the right help there !Thank you!
