### ISSUE TITLE
InputSpec argument ignored 

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#51377]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the current behavior**
The `ndim` argument of the [InputSpec](https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputSpec?hl=ja) of a layer seems to be ignored when the `shape` argument is set. The issue is illustrated in the following example with a simple custom layer. 

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

class TempLayer(tf.keras.layers.Activation):
    def __init__(self):
        super(keras.layers.Activation, self).__init__()
        self.input_spec = keras.layers.InputSpec(ndim=5, shape=(1,2))
    def call(self, input_1, training=False):
        return input_1
        
model = keras.Sequential([TempLayer()])
x = tf.constant([[1.4392, 1.9206]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

**Comment by tilakrayal** [comment]
@rschumi0 ,

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by rschumi0** [comment]
@tilakrayal It's now in the keras repo: https://github.com/keras-team/keras/issues/15225

**Comment by tilakrayal** [comment]
@rschumi0 ,
Please feel free to move this issue to closed status,as it  has been tracked in keras repo.Thanks!
