### ISSUE TITLE
trainable_variables being empty in tf2.5

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51375]
tf2.5
```

initial = tf.random.normal(shape=[2, 5], mean=0, stddev=0.05, dtype=tf.dtypes.float64)
initial = tf.Variable(initial, name='eeeeeee', trainable=True)

print(tf.compat.v1.trainable_variables())
```

In tf2.5, the above output is [ ], but in tf1.13, it has variables `[<tf.Variable 'eeeeeee:0' shape=(2, 5) dtype=float64_ref>]`. Why?

**Comment by sushreebarsa** [comment]
@sjtusmartboy Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sjtusmartboy** [comment]
@sushreebarsa try the code and you will find it

**Comment by sushreebarsa** [comment]
@sjtusmartboy I tried to run your code on colab with TF v2.5 and 1.15, and was able to replicate the issue as reported here .
`tf.compat.v1.trainable_variables()`  API was designed for TensorFlow v1. Please refer to this [link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/trainable_variables?version=nightly) to migrate from this API to a native TensorFlow v2 equivalent and let us know if it helps? Thank you!

**Comment by sjtusmartboy** [comment]
@sushreebarsa thanks
