### ISSUE TITLE
Android Studio CPU Profiler

### ISSUE THREAD

**Issue by yuyecreus** [tensorflow/tensorflow#51389]
Hello!

I have a model built with tensorflow and exported to tensorflow lite and integrated to Android Studio.  I want to profile it and hence i follow the steps [] (https://www.tensorflow.org/lite/performance/measurement#android_studio_cpu_profiler) in the section of Android Studio CPU Profiler.  However, in the end, I see no thread like the one called "recognizeImage()" in the example and I am not able to see the "per-op" profile as in the example.

What do I need to implement to visualize the per-op results there?

Thank you!

**Comment by yyoon** [comment]
Can you confirm that you've also followed the steps right above the section you linked?
https://www.tensorflow.org/lite/performance/measurement#trace_tensorflow_lite_internals_in_android

Also, what version of TFLite are you running?
