### ISSUE TITLE
can not open include file,   无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory

### ISSUE THREAD

**Issue by zhousteven** [tensorflow/tensorflow#51388]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): source
- TensorFlow version:1.2.0
- Python version:3.5.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): CMake 3.8.12
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: disable
- GPU model and memory: disable

**Describe the problem**
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.cc)
  table.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\format.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\buffered_inputstream.cc)
  table_builder.cc
  two_level_iterator.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\gtl\array_slice_internal.h(89): error C2064: 项不会计算为接受 0 个参数的函数 (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\histogram\histogram.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\block.cc)
  zlib_inputstream.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\inputbuffer.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\threadpool.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\block_builder.cc)
  zlib_outputbuffer.cc
  jpeg_handle.cc
  jpeg_mem.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\iterator.cc)
  collection_registry.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\record_reader.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\inputstream_interface.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\record_writer.cc)
  distribution_sampler.cc
  simple_philox.cc
  weighted_picker.cc
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\random_inputstream.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\snappy\snappy_outputbuffer.cc)
f:\temp\tensorflow-1.2.0\tensorflow\core\lib\core\status.h(22): fatal error C1083: 无法打开包括文件: “tensorflow/core/lib/core/error_codes.pb.h”: No such file or directory (编译源文件 F:\temp\tensorflow-1.2.0\tensorflow\core\lib\io\path.cc)
  base64.cc
  proto_text_util.cc
  str_util.cc

**Provide the exact sequence of commands / steps that you executed before running into the problem**
when i use cmake to compile tensorflow from source code, raise up error.
if anyone occur the same error

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zhousteven** [comment]
[error.log](https://github.com/tensorflow/tensorflow/files/6951901/error.log)
attachment is whole error log for reference

**Comment by sushreebarsa** [comment]
@zhousteven 
We see that you are using older version of tensorflow ( 1.2.0 ) which is officially considered as end of life and not actively supported.We recommend that you upgrade to TF v2.5 & please let us know if the issue still persists in newer versions .Thanks!

**Comment by zhousteven** [comment]
> @zhousteven
> We see that you are using older version of tensorflow ( 1.2.0 ) which is officially considered as end of life and not actively supported.We recommend that you upgrade to TF v2.5 & please let us know if the issue still persists in newer versions .Thanks!

thanks for your kindly response, according your advice, try TF v2.x
