### ISSUE TITLE
[AutoML] [Tensorflow Lite] Export for TensorFlow Lite is broken for confidence score

### ISSUE THREAD

**Issue by airman00** [tensorflow/tensorflow#51395]
**System information**
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.5

**Describe the current behavior**
I trained a model on a dataset via AutoML Vision and exported models[ using the UI.](https://cloud.google.com/vision/automl/object-detection/docs/export-edge)  I've used AutoML in the past and the models have always worked well.

The .tflite version has bounding boxes and class names that are perfectly correct, but the confidence scores are wrong.

Specifically, the .tflite seems to cap its confidence score at 50%. It never goes higher than 50%.

Given the same input image, the top 4 confidence scores are as follows:
for .tflite `0.5, 0.0429, 0.0273, .002343`
for tf js `0.9975, 0.02638, 0.0182, 0.00969`

**Describe the expected behavior**
The top confidence score should not be 0.5 and should instead be around 0.99 in the tflite

According to Netron, the TF run time for the TFLite was 2.5.0. For the TF JS, the model.json indicates that it was generated by 2.7.0 (the brand new release). I don't have any obvious way to select what runtime I want TFLite to be exported in.

**Standalone code to reproduce the issue**
I used basic code to test the TF JS
```
<!---- python -m SimpleHTTPServer 8000 ---->

<script src="https://unpkg.com/@tensorflow/tfjs"></script>
<script src="https://unpkg.com/@tensorflow/tfjs-automl"></script>
<img id="salad" crossorigin="anonymous" src="test.jpeg">
<script>
async function run() {
  const model = await tf.automl.loadObjectDetection('model.json');
  const img = document.getElementById('salad');
const options = {score: 0.005, iou: 0.5, topk: 5};
  const predictions = await model.detect(img, options); // , options
  console.log(predictions);
  // Show the resulting object on the page.
  const pre = document.createElement('pre');
  pre.textContent = JSON.stringify(predictions, null, 2);
  document.body.append(pre);
}
run();
</script>
```

And the Tensorflow Lite tester:
```
import numpy as np
import tensorflow as tf
import cv2

img = cv2.imread("test.jpeg")
new_img = cv2.resize(img, (320,320))

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
interpreter.set_tensor(input_details[0]['index'], [new_img])

interpreter.invoke()

# Show the scores
scores = interpreter.get_tensor(output_details[2]['index'])
print(scores)
```

Couple of questions:
1. What would a capped confidence of 50% be a symptom of? (Something weird with quantization?)
2. Should I just multiple the confidence score by 2 or is that completely wrong?
3. Is this the right place to post about AutoML bugs?

**Comment by ymodak** [comment]
Can you please post this issue on automl repo https://github.com/google/automl for support?
This repository focuses on TF Core and TF Lite related bugs. Thanks!

**Comment by airman00** [comment]
Done, thanks! 

https://github.com/google/automl/issues/1070
