### ISSUE TITLE
setting learning rate with `tk.backend.set_value` fails with `tf.keras.optimizers.schedules`

### ISSUE THREAD

**Issue by pbk0** [tensorflow/tensorflow#51399]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): '2.5.0'
- Python version: '3.8.10'

**Describe the current behavior**

Check the code snippet with two cases below

**Describe the expected behavior**

Both the cases should succeed.
Currently, when `learning_rate` is not a schedule it works.

**Standalone code to reproduce the issue**

```python
import tensorflow.keras as tk

# [1] this case works
_o = tk.optimizers.Adam(learning_rate=3.44)
tk.backend.set_value(_o.learning_rate, 0.01)

# [2] but when using learning rate sheculer it fails
_o = tk.optimizers.Adam(learning_rate=tf.keras.optimizers.schedules.ExponentialDecay(0.1, 1000, 0.96))
tk.backend.set_value(_o.learning_rate, 0.01)
```
Fails with below error
```txt
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-b93ddba04c22>", line 3, in <module>
    tk.backend.set_value(_o.learning_rate, 0.01)
  File "C:\Python38\lib\site-packages\tensorflow\python\keras\backend.py", line 3769, in set_value
    value = np.asarray(value, dtype=dtype(x))
  File "C:\Python38\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Python38\lib\site-packages\tensorflow\python\keras\backend.py", line 1516, in dtype
    return x.dtype.base_dtype.name
AttributeError: 'ExponentialDecay' object has no attribute 'dtype'
```

**Comment by sanatmpa1** [comment]
@pbk0,

This looks like a issue related to Keras. So can you please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see;[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by samllSs** [comment]
can you tell me how you can solve it?
