### ISSUE TITLE
Question about tf.compat.v1.metrics.auc

### ISSUE THREAD

**Issue by jiqiujia** [tensorflow/tensorflow#51407]
I try to migrate my code from tf1.* to tf2, while in [tf2 doc](https://www.tensorflow.org/api_docs/python/tf/compat/v1/metrics/auc) it says that `tf.compat.v1.metrics.auc` is deprecated because "**The value of AUC returned by this may race with the update**". This statement is vague to me. Does it mean that it can't be used in multithreading context? If not, in what situation can I use this function?

**Comment by jvishnuvardhan** [comment]
@jiqiujia I am not sure about the words used in `deprecation` warning. But, as mentioned in that deprecation warning, please use `tf.keras.metrics.AUC` in place of `tf.compat.v1.metrics.auc`. It is always best not to mix `v1` (related to TF1.x) and `v2` (related to TF2.x) modules. 

That warning will be removed soon when next auto update cycle runs to update TF webpages. Thanks!
