### ISSUE TITLE
AttributeError: type object 'IteratorBase' has no attribute 'from_structure'

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51401]
ｔｅｎｓｏｒｆｌｏｗ　２．５

I've issued this https://github.com/tensorflow/tensorflow/issues/50871. However, there's no reply at all. May it has been forgotten, so I have to raise this issue again.

```
import tensorflow as tf

training_dataset = tf.data.Dataset.range(100).map(
    lambda x: x + tf.random.uniform([], -10, 10, tf.int64))
validation_dataset = tf.data.Dataset.range(50)

# A reinitializable iterator is defined by its structure. We could use the
# `output_types` and `output_shapes` properties of either `training_dataset`
# or `validation_dataset` here, because they are compatible.
iterator = tf.data.Iterator.from_structure(training_dataset.output_types,
                                           training_dataset.output_shapes)
next_element = iterator.get_next()

training_init_op = iterator.make_initializer(training_dataset)
validation_init_op = iterator.make_initializer(validation_dataset)

# Run 20 epochs in which the training dataset is traversed, followed by the
# validation dataset.
for _ in range(20):
    # Initialize an iterator over the training dataset.
    sess.run(training_init_op)
    for _ in range(100):
        sess.run(next_element)

    # Initialize an iterator over the validation dataset.
    sess.run(validation_init_op)
    for _ in range(50):
        sess.run(next_element)`

```

**Comment by sushreebarsa** [comment]
@sjtusmartboy Could you please refer to the[ link ](https://www.tensorflow.org/api_docs/python/tf/compat/v1/data/Iterator),[ link1](https://www.tensorflow.org/api_docs/python/tf/data/Iterator) and let us know if it helps?Thanks!

**Comment by sjtusmartboy** [comment]
@sushreebarsa Thanks, but the link certainly would not help because I've read it several times. Please teach me how to revise the code because it's the tensorflow's kernel error.

**Comment by sushreebarsa** [comment]
@sjtusmartboy Thank you for the update! I tried to run your code using `tf.compat.v1.disable_v2_behavior()` on colab with TF v2.5 and It is throwing warning message ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2bf39b081ae5fa2e31c2ef68ace334c3/untitled374.ipynb) for your reference.Session is not supported in TF version 2.x . Please find the [link](https://www.tensorflow.org/guide/effective_tf2#functions_not_sessions) ,[ link1](https://www.tensorflow.org/guide/migrate) for more information on migration from 1.x to 2.x and let us know if it helps?Thank you!
