### ISSUE TITLE
Gather not working as expected in TFLite

### ISSUE THREAD

**Issue by jlabarbera11** [tensorflow/tensorflow#51402]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
In TFLite, gather over a tensor of string types fails.

**Describe the expected behavior**
I expect it to behave in the same way gather over integer types does

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

names = tf.keras.Input(shape=(2,), dtype=tf.string)
model = tf.keras.Model(
    inputs=names,
    outputs=tf.gather(names, tf.constant([0])),
)

model.save('./export')
converter = tf.lite.TFLiteConverter.from_saved_model('./export')
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

interpreter = tf.lite.Interpreter(model_path='model.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], np.array([[1, 2]], dtype=np.string))
interpreter.invoke()
interpreter.get_tensor(output_details[0]['index'])
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-533b631ac475> in <module>
     15 
     16 interpreter = tf.lite.Interpreter(model_path='model.tflite')
---> 17 interpreter.allocate_tensors()
     18 input_details = interpreter.get_input_details()
     19 output_details = interpreter.get_output_details()

/code/venvs/venv/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    406   def allocate_tensors(self):
    407     self._ensure_safe()
--> 408     return self._interpreter.AllocateTensors()
    409 
    410   def _safe_to_run(self):

RuntimeError: tensorflow/lite/kernels/gather.cc:76 NumDimensions(input) != 1 (2 != 1)Node number 0 (GATHER) failed to prepare.
```

Changing the types from `string` to `int64` returns `array([[1, 2]])`, though I don't totally understand why it doesn't return `array([1, 2])`

**Comment by abattery** [comment]
Does the keras model work with the above input given to the TensorFlow Lite as well?

**Comment by jlabarbera11** [comment]
The keras model works as intended

```
import tensorflow as tf
import numpy as np

names = tf.keras.Input(shape=(2,), dtype=tf.string)
model = tf.keras.Model(
    inputs=names,
    outputs=tf.gather(names, tf.constant([0])),
)

model(np.array([1, 2], dtype=np.str))
```

```
<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'1'], dtype=object)>
```

**Comment by srjoglekar246** [comment]
TFLite's Gather kernel does not support >1 dimensions in its inputs. So, assuming you want to run single-batch inference, this code works (Note the `reshape` to 1-dim tensor before `tf.gather`):

```
  names = tf.keras.Input(shape=(2,), dtype=tf.string, batch_size=1)
  model = tf.keras.Model(
      inputs=names,
      outputs=tf.gather(tf.reshape(names, [2]), tf.constant([0])),
  )

  print("KERAS OUTPUT IS", model(np.array([1, 2], dtype=np.str)))

  model.save('./output')
  converter = tf.lite.TFLiteConverter.from_saved_model('./output')
  tflite_model = converter.convert()
  with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

  interpreter = tf.lite.Interpreter(model_path='model.tflite')
  interpreter.allocate_tensors()
  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()
  interpreter.set_tensor(input_details[0]['index'], np.array([[1, 2]], dtype=np.str))
  interpreter.invoke()
  print("TFLITE OUTPUT IS", interpreter.get_tensor(output_details[0]['index']))
```

**Comment by jlabarbera11** [comment]
@srjoglekar246 thanks, this works for me. In regards to not supporting >1 dimensions, is using `batch_dims=1` in the gather call also not supported in TFLite?

**Comment by srjoglekar246** [comment]
Yeah, any two-dimensional tensor is rejected by the TFLite op (unfortunately). But reshaping the input as suggested above should do the trick.

**Comment by abattery** [comment]
https://github.com/tensorflow/tensorflow/commit/d76fbad66d84c5e051a0f90c4d73278856f2e22a fixes the converter issue.

Now, the above original model will require the Select TF op since TFLite gather op can not handle the 2D string inputs.
