### ISSUE TITLE
1.15.4

### ISSUE THREAD

**Issue by van-68** [tensorflow/tensorflow#51408]
We found vulnerabilities about tensorflow on the website （https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=tensorflow&search_type=all&isCpeNameSearch=false）. These vulnerabilities are basically fixed in versions greater than 2.0. But how are these vulnerabilities fixed in version 1.15.4? Thank you.

**Comment by Saduf2019** [comment]
@van-68 
can you please provide with more information and details when you say about vulnerabilities, as there is no active support for tf 1.x,  can you upgrade to 2.x and let us know.

**Comment by van-68** [comment]
> @van-68
> can you please provide with more information and details when you say about vulnerabilities, as there is no active support for tf 1.x, can you upgrade to 2.x and let us know.

Thank you for your reply. If upgrade, the previous model in version 1. X and the subsequent Quantization Compression need to be reconstructed.
Do you have a good way
thanks。

**Comment by Saduf2019** [comment]
@van-68 
You will have to reconstruct in later versions, in case you still have queries please post this in tf discussion forum as it has a larger community who could respond there.

**Comment by mihaimaruseac** [comment]
1.15 is EOL. We no longer patch it.

You will have to convert to TF 2.4 or above.

**Comment by van-68** [comment]
> 1.15 is EOL. We no longer patch it.
> 
> You will have to convert to TF 2.4 or above.

Thank you for your reply. The latest version is 1.15.5 of tensorflow 1.x，Will maintenance and upgrade be performed on version 1.15.5 in the future.
If convert to TF 2.4 or above, Do the previous models have to be reconstructed and modified from training, compression, quantization and integration.
Thanks

**Comment by van-68** [comment]
> 1.15 is EOL. We no longer patch it.
> 
> You will have to convert to TF 2.4 or above.

Thank you for your reply. The latest version is 1.15.5 of tensorflow 1.x，Will maintenance and upgrade be performed on version 1.15.5 in the future.
If convert to TF 2.4 or above, Do the previous models have to be reconstructed and modified from training, compression, quantization and integration.
Thanks

**Comment by mihaimaruseac** [comment]
No. TF 1.x will not be updated at all.

In theory, most models should still work.

**Comment by van-68** [comment]
> No. TF 1.x will not be updated at all.
> 
> In theory, most models should still work.

In you mean, The current version is 1.15.5, and there will be no later version?
Won't the following vulnerabilities be fixed in version 1. X。
If used, be must upgrade to 2. X？

**Comment by mihaimaruseac** [comment]
You must upgrade to TF 2.x if you want fixes for vulnerabilities.

TF 1.x will not be updated at all. Use it at own risk
