### ISSUE TITLE
Amazon SageMaker Debugger - 'RuleEvaluationStatus': 'Error'

### ISSUE THREAD

**Issue by Raisa06** [tensorflow/tensorflow#51414]
I'm facing the following error while running Overfit built-in rule in tensorflow

'RuleConfigurationName': 'Overfit',
 'RuleEvaluationStatus': 'Error',
 'StatusDetails': 'ClientError: No debugging data was saved by the training '
                  'job. Check that the debugger hook was configured correctly '
                  'before starting the training job. Exception: Training job '
                  'has ended. All the collection files could not be loaded\n'
                  'Traceback (most recent call last):\n'

Below is my code,

import boto3
import sagemaker
from time import gmtime, strftime
from sagemaker.tensorflow import TensorFlow
from sagemaker.debugger import ProfilerConfig, DebuggerHookConfig, Rule, ProfilerRule, rule_configs, CollectionConfig

base_job_name_prefix= 'SDK-SMDebug-built-in-rules-'+ strftime("%d-%H-%M-%S", gmtime())

collection_config_biases = CollectionConfig(name='biases')
collection_config_weights = CollectionConfig(name='weights')
collection_config_metrics = CollectionConfig(name='metrics')

debugger_hook_config = DebuggerHookConfig(
    s3_output_path=f"s3://bgt-lensxraymodeling/URPM/MajorModel/SageMakerOutput/debug-output",
    collection_configs=[
        collection_config_biases,
        collection_config_weights,
        collection_config_metrics
    ]
)

estimator = TensorFlow(
    entry_point='SCNN_custom_v1/sagemaker_train_v1.py',
    instance_type='ml.p2.xlarge',
    instance_count=1,
    image_uri='763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:1.15.5-gpu-py36-cu100-ubuntu18.04',
    #script_mode=True,
    framework_version="1.15",
    py_version="py3",
    role=role,
    base_job_name=base_job_name_prefix, 
    **debugger_hook_config=debugger_hook_config,
    rules=[
        Rule.sagemaker(rule_configs.overfit()),
        Rule.sagemaker(rule_configs.loss_not_decreasing())
    ],**
)
estimator.fit()

Could someone please suggest me a solution for this? I don't find any issue with regard to debugger hook configuration in the above code

**Comment by sushreebarsa** [comment]
@Raisa06 Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
