### ISSUE TITLE
Outer dimensions of indices and update must match

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#51412]
```python
x     = tf.random.normal((128, 4096))
x_slc = tf.random.normal((128, 1023))
slc = list(range(x_slc.shape[-1]))
tf.tensor_scatter_nd_update(x, slc, x_slc)
```
I cannot find any shape of `slc` that doesn't make the command fail, and the error message is inaccurate: the inner (non-assignment) dimensions do match:

```python
InvalidArgumentError: Inner dimensions of output shape must match inner dimensions of updates shape. 
Output: [128,4096] updates: [128,1023] [Op:TensorScatterUpdate]
```

Either a bug or a documentation issue. The intended behavior is to emulate `x[:, :1023] = x_slc`.

**Comment by OverLordGoldDragon** [comment]
@tilakrayal [TensorFlow 2.5.0](https://anaconda.org/anaconda/tensorflow) (no GPU), Windows 10, Python 3.9.6, [tf_scatter_nd_update](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update), no existing Issues.

**Comment by tilakrayal** [comment]
@sanatmpa1  ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0d7291d364d89edc48c9610f6ea1149b/41512.ipynb).

**Comment by sanatmpa1** [comment]
@OverLordGoldDragon,

> I cannot find any shape of slc that doesn't make the command fail

You've created `slc` which is a list of range of values  `[0,1,2,...,1022]` with length 1023, 
whereas the ideal values should have been a list of indices, with the shape `(128, 1023, 2)` as shown below.
` array([[[0,0],[ 0,1], ...[0, 1022]],
   ......,
       [[ 127,0],[ 127,    1],...,[ 127, 1022]]])`

The solution is to change the second line of your code from, `slc = list(range(x_slc.shape[-1]))` to `slc = tf.where(tf.math.logical_not(tf.math.is_nan(x_slc))).numpy().reshape([128,1023,2])`.

Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/2e2fd0e69cd6049ee7789b693c550a48/51412.ipynb#scrollTo=aSBaShDTtY9w), for the working solution and the validation. let me know if it answers your question. Thanks!

**Comment by OverLordGoldDragon** [comment]
@sanatmpa1 This works ... sort of: it makes a copy (set `result = x`) despite the indexing being contiguous. That's a deal-breaker for performance; can a copy be avoided?

**Comment by sanatmpa1** [comment]
@OverLordGoldDragon 

Glad that it worked! To answer your question, as per TensorFlow [documentation](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update) of `tensor_scatter_nd_update` , it clearly states that a new tensor will be created and we don't have inplace option implemented at this point of time.

As the solution that I proposed has worked for you, please confirm if we are good to close this issue. Thanks!

**Comment by sanatmpa1** [comment]
@OverLordGoldDragon,

Thanks for pointing that out. I mentioned in-place operation is not implemented yet, as per the below line in the document.

> #Not implemented: tensors cannot be updated inplace.
> tensor[indices] = updates

If you feel that it can be a potential performance problem, can you kindly create a new issue/feature request specifically for the same. Thanks!

**Comment by OverLordGoldDragon** [comment]
@sanatmpa1 Thanks for the help.

Hard to imagine a big data library not having a basic performant operation. Regardless, below implements arbitrary indexing and more efficiently, assuming `x_slc` has no NaNs.

<details>
  <summary><b>code</b></summary>

```python
import tensorflow as tf
import numpy as np

# generate data
x     = tf.random.normal((128, 4096))
x_slc = tf.random.normal((128, 1023))

# generate arbitrary indexing
seq = np.random.randint(0, 4096, 20000)
ix = np.unique(seq, return_index=True)[1][:1023]
idxs = seq[np.sort(ix)]
idxs = np.arange(5, 5+1023)

# index last dimension
slc = tf.ones(x_slc.shape)
slc = tf.where(slc).numpy().reshape([128, 1023, 2])
slc[..., 1] = idxs

# update
out = tf.tensor_scatter_nd_update(x, slc, x_slc)

# validate
xn, xsn = out.numpy(), x_slc.numpy()
d = np.abs(xn[:, idxs] - xsn)
assert np.allclose(xn[:, idxs], x_slc), np.abs(d).mean()
```
</details>
