### ISSUE TITLE
Tensorflow 2.5: Segmentation Fault

### ISSUE THREAD

**Issue by shifdz** [tensorflow/tensorflow#51410]
I am trying to run a large 3D U-net and my dataset size is 55GB. It doesn't finish more than 6 epochs and then I get a segmentation fault. 

System information: TF 2.5 / CUDA 11.2 / cuDNN 8.1
GPU : 10GB
Server has 32GB of RAM.

The code for my data generator is as follows: 

```
def open_data_file(filename, readwrite="r"):
    return tables.open_file(filename, readwrite)

data_file_opened = open_data_file(os.path.abspath("../data/data.h5"))

train_generator, validation_generator, n_train_steps, n_validation_steps = get_training_and_validation_generators(
        data_file_opened,
        ......)
```

where:

```
def get_training_and_validation_generators(data_file, batch_size, ...):
    training_generator = data_generator(data_file, training_list,....)
```
data_generator function is as follows:

```
def data_generator(data_file, index_list,....):
      orig_index_list = index_list
    while True:
        x_list = list()
        y_list = list()
        if patch_shape:
            index_list = create_patch_index_list(orig_index_list, data_file, patch_shape,
                                                 patch_overlap, patch_start_offset,pred_specific=pred_specific)
        else:
            index_list = copy.copy(orig_index_list)

        while len(index_list) > 0:
            index = index_list.pop()
            add_data(x_list, y_list, data_file, index, augment=augment, augment_flip=augment_flip,
                     augment_distortion_factor=augment_distortion_factor, patch_shape=patch_shape,
                     skip_blank=skip_blank, permute=permute)
            if len(x_list) == batch_size or (len(index_list) == 0 and len(x_list) > 0):
                yield convert_data(x_list, y_list, n_labels=n_labels, labels=labels, num_model=num_model,overlap_label=overlap_label)
                x_list = list()
                y_list = list()

```

Can someone please tell me how to solve this issue? What causes the segmentation fault? Also, training is very slow. It takes about 7000s to complete one epoch.

**Comment by sanatmpa1** [comment]
@shifdz,

Please take a look on the links [ref_1](https://stackoverflow.com/questions/54333809/how-to-remedy-segmentation-fault-core-dumped-error-when-trying-to-fit-a-kera), [ref_2](https://stackoverflow.com/questions/53302958/how-to-debug-tensorflow-segmentation-fault-in-model-fit). For your question on what causes segmentation fault, one of the answer in this [thread](https://stackoverflow.com/questions/54333809/how-to-remedy-segmentation-fault-core-dumped-error-when-trying-to-fit-a-kera) mentions that `"Segmentation fault error stands for a failure of the parallelization of your training process on the GPU"` 

We may need a simple reproducible code and sample data to trouble shoot the issue from our end. But I suggest you can try out the solutions mentioned in the links provided and let us know if it helps. Thanks!
