### ISSUE TITLE
TfLiteGpuDelegate Init: CONCATENATION: Node 2 is already a consumer of the value 0

### ISSUE THREAD

**Issue by hongye007** [tensorflow/tensorflow#51422]
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: Following operations are not supported by GPU delegate:
    DEPTH_TO_SPACE: Operation is not supported.
    DEQUANTIZE: 
    13 operations will run on the GPU, and the remaining 23 operations will run on the CPU.
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: TfLiteGpuDelegate Init: CONCATENATION: Node 2 is already a consumer of the value 0
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution I/tflite: Created 0 GPU delegate kernels.
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: TfLiteGpuDelegate Prepare: delegate is not initialized
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: Node number 36 (TfLiteGpuDelegateV2) failed to prepare.
2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: Restored original execution plan after delegate application failure.
2021-08-10 20:31:39.969 15740-15740/org.tensorflow.lite.examples.superresolution E/super_resolution::: Failed to create TFLite interpreter

**Comment by abattery** [comment]
@impjdi could you take a look?

**Comment by impjdi** [comment]
Please attach a tflite model.

**Comment by hongye007** [comment]
[demo_model.tflite.zip](https://github.com/tensorflow/tensorflow/files/6972604/demo_model.tflite.zip)
@impjdi

**Comment by impjdi** [comment]
Yeah, the `CONCAT` node is taking the input 4 times to stitch it together.  This doesn't work on the GPU.  From the shader's point of view, if a shader program takes in input A and input B, they have to be distinct GPU objects.

@renjie-liu I think TAC could mitigate this use case?  This i s applicable to any op that takes in the same intermediate tensor twice or more.

**Comment by hongye007** [comment]
I am sorry, my delayed reply
so.  now what should i do for this case?

**Comment by impjdi** [comment]
Can you elaborate what's happening in that network?  Why do you replicate the input 4 times and then add it with the output of your convolutions?

Anyway, one obvious trick is to do the replication of input_1 outside the network and then feed 2 input tensors to the network.  This might be the easiest.

The other trick is to enforce creation of other textures by `ADD 0` or `MUL 1` and feed that 4 times to a concat, so that the concat reads from 4 different locations rather than the same location 4 times.  However, I'm not sure whether tflite_convert would prune out that sort of trick...

**Comment by hongye007** [comment]
Thanks for your reply, I will try to do as your recommendation

I want to train a model about image super-resolution. I am trying to combine residual and depth_to_space ops.
3 channels and 2x up-scale need 12 channels, so I replicate the input 4 times(outputs: 12channels)
then add with 12 feature channels , and as the final input of depth_to_space

I am a beginner of tf and don't know if there is something wrong，Any good suggestions?

**Comment by impjdi** [comment]
Hm, I haven't worked with superres models in the past and can't say what's a good architecture =/

One thing to note is that `DEPTH_TO_SPACE` (and any kind of `CONCAT`, `RESHAPE`, `TRANSPOSE`) is bad for GPU performance.  It's generally okay on the CPU side, but GPU is often bounded by memory bandwidth, and those operations are not desired for GPU execution, and we typically ask our neural net architects to design networks around it if they are planning to use GPU primarily.

**Comment by hongye007** [comment]
It seems impossible to achieve real-time superres on the CPU（>24fps or 30、60fps）. so I think GPU should be a good choice
However, I feel that TF’s support for mobile SR currently has many limitations. 
Thank you very much for your reply。

**Comment by TerenceYang** [comment]
@hongye007 I have the same problem when deploy super-resolution model on android device

**Comment by ygch** [comment]
I also met the same problem. It seems CONCAT is very common operation for superresolution, can tf give an elegant solution?
