### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by skj092** [tensorflow/tensorflow#51425]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- TensorFlow version: 1.15
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: conda
- GPU model and memory: CPU

**Describe the problem**
Getting error while importing tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

![Capture](https://user-images.githubusercontent.com/43055935/128979222-c29efaba-82db-451e-aef0-134e16b9a7d2.PNG)

**Comment by sushreebarsa** [comment]
@skj092 We see that you are using older version of tensorflow 1.15 which is officially considered as end of life , We recommend that you upgrade to 2.5 and let us know if the issue still persists in newer versions.Thanks!

**Comment by skj092** [comment]
Yes, I am able to install and import the latest version successfully.

**Comment by sushreebarsa** [comment]
@skj092 Thank you for the update! Could you please confirm if the issue is resolved and feel free to move this issue to closed status ? Thanks!
