### ISSUE TITLE
GPU performance issue when calling slicing for tensors of types tf.int16, tf.int32 (op StridedSlice)

### ISSUE THREAD

**Issue by farotem** [tensorflow/tensorflow#51428]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- binary wheel via PyPI
- TensorFlow version (use command below):
- v2.5.0-0-ga4dfb8d1a71 2.5.0
- Python version:
- 3.6
- CUDA/cuDNN version:
- CUDA 11.2
- GPU model and memory:
- V100 32 GB

**Describe the current behavior**
When slicing tensors of shape int16 or int32 it takes significant amount of time comparing to float16, float32
*****************************************************
type array: <dtype: 'int16'>
took 35.05420684814453
*****************************************************
type array: <dtype: 'int32'>
took 22.861242294311523
*****************************************************
type array: <dtype: 'int64'>
took 5.330085754394531
*****************************************************
type array: <dtype: 'float16'>
took 1.550912857055664
*****************************************************
type array: <dtype: 'float32'>
took 2.5637149810791016
*****************************************************
type array: <dtype: 'float64'>
took 5.917549133300781
*****************************************************
type array: <dtype: 'bool'>
took 1.6639232635498047

**Describe the expected behavior**
takes around the same time as the float versions

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): no

when running the code using tf.debugging.set_log_device_placement(True) found that slicing int16 is not using gpu at all:
type array: <dtype: 'int16'>
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0

for int32 I don't understand the reason for such difference comparing to float32

**Standalone code to reproduce the issue**
```
import tensorflow as tf
# tf.debugging.set_log_device_placement(True)
import numpy as np
import time

def test_slicing():

    with tf.device('/GPU:0'):
      shape = (52000, 2, 15, 15)
      np_array = np.ones(shape, dtype=np.uint16)

      dtypes= [tf.uint16, tf.int16, tf.int64, tf.float16, tf.float32, tf.float64, tf.bool]
      start = 0
      end = 50000
      for dtype in dtypes:
        print("*****************************************************")

        tf_array = tf.constant(np_array, dtype=dtype) * 1 if dtype != tf.bool else tf.math.logical_and(tf.constant(np_array, dtype=dtype) , tf.constant(np_array, dtype=dtype)) 
        print(f'type array: {tf_array.dtype}')
        
        for i in range(1):
            tf_array = tf.constant(np_array, dtype=dtype) * 1 if dtype != tf.bool else tf.math.logical_and(tf.constant(np_array, dtype=dtype) , tf.constant(np_array, dtype=dtype)) 

            tic = time.time()
            a = tf_array[start:end]
            a[0][0][0][0].numpy()
            toc = time.time()
            print(f'took {(toc - tic)*1000}')

print()          
print(tf.version.GIT_VERSION, tf.version.VERSION)
test_slicing()
```

**Comment by sushreebarsa** [comment]
@farotem Could you please take a look at the [link](https://www.tensorflow.org/api_docs/python/tf/strided_slice) and let us know if it helps ? Thanks!

**Comment by farotem** [comment]
Thank you for the fast response.
I looked at it before and I'm not sure how it helps,
I think the behavior for all types should work the same the link for the low level api is not helping if only for specific type there is a need for the low level api.
any other ideas?

**Comment by sushreebarsa** [comment]
@sanatmpa1  Was able to replicate the issue on Colab with TF [v2.4](https://colab.research.google.com/gist/sushreebarsa/0ea29c048266b56cbd66deb01d0c835e/51428.ipynb#scrollTo=8-N00DpkFqHi), [v2.5](https://colab.research.google.com/gist/sushreebarsa/ec94cf63bfd9a465a27dd748f840cc48/51428.ipynb) , [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/8d86c84c3ecc09e3f0c4c166bd58db73/51428.ipynb#scrollTo=xWdtpONIGSwi) ,please find the gists attached.Thank you!

**Comment by sanatmpa1** [comment]
@farotem,

Please take a look at this [gist-2.6 ](https://colab.research.google.com/gist/sanatmpa1/d831e4f48f85388d413aa835433149ec/51428-tf-2-6.ipynb) from `TF 2.6.0` and [gist-nightly](https://colab.research.google.com/gist/sanatmpa1/40d1b9105daee4c7f8b3ffa5a708ed14/51428-nightly.ipynb) from `tf-nightly`, The time difference between int and float has reduced significantly in `TF 2.6` and you can notice that in `tf-nightly` the time taken for `int` is mostly close to what it takes for `float`, which indicates that its already fixed in nightly. Let me know if it addresses your issue. Thanks!

**Comment by farotem** [comment]
Thank you for the response,
I looked at both gists (2.6, nightly) and I see some concerned issues:

- timing
  1. float in tf 2.5: ~1.5ms - 2.5ms
  2. float in tf 2.6, nightly ~14-16ms
 
- runtime machine (enabling tf.debugging.set_log_device_placement(True))
  1.  tf 2.5 looking the op StridedSlice for float is device:**GPU**:0
  2.  tf 2.6, nightly looking the op StridedSlice for float is device:**CPU**:0

so if I understand correctly the reason for the closing gap between int to float is that now the performance of float decrease because the op StridedSlice is no longer in GPU and only runs on CPU is that on purpose?

I hoped the opposite direction would work and the int op StridedSlice that runs in tf 2.5 on CPU only will run on GPU in later releases just like float and the performance for int and float will be the same and increased.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
