### ISSUE TITLE
Depth_to_space

### ISSUE THREAD

**Issue by hongye007** [tensorflow/tensorflow#51421]
**System information**
- OS Platform and Distribution (e.g., mac):
- TensorFlow installed from (tensorflow 2.5):
- TFLite: 2.5.0

2021-08-10 20:31:39.968 15740-15740/org.tensorflow.lite.examples.superresolution E/tflite: Following operations are not supported by GPU delegate:
    DEPTH_TO_SPACE: Operation is not supported.
    DEQUANTIZE: 
    13 operations will run on the GPU, and the remaining 23 operations will run on the CPU.

**Comment by hongye007** [comment]
How can I use DEPTH_TO_SPACE with GPU support (tflite)?

**Comment by chunduriv** [comment]
@hongye007,

TensorFlow Lite supports `depth_to_space`. For more details please refer [here](https://www.tensorflow.org/mlir/tfl_ops#tfldepth_to_space_mlirtfldepthtospaceop).
