### ISSUE TITLE
SparseTensorToCSRSparseMatrix wastes so much time on cpu

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51438]
tensorflow 2.5

```

import tensorflow as tf
import numpy as np
import datetime
from tensorflow.python.ops.linalg.sparse import sparse_csr_matrix_ops

a_indices = np.array([[0, 0], [2, 3], [2, 4], [3, 0]])
a_values = np.array([1.0, 5.0, -1.0, -2.0], np.float32)
a_dense_shape = [4, 5]

b_indices = np.array([[0, 0], [3, 0], [3, 1]])
b_values = np.array([2.0, 7.0, 8.0], np.float32)
b_dense_shape = [5, 3]


stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'logs/csrmatrix_test/%s' % stamp
tf.profiler.experimental.start(logdir)

with tf.profiler.experimental.Trace("Train", step_num=0):
    # with tf.device('/gpu:0'):
        # with tf.compat.v1.Session() as sess:
            # Define (COO format) Sparse Tensors over Numpy arrays
    a_st = tf.sparse.SparseTensor(a_indices, a_values, a_dense_shape)
    b_st = tf.sparse.SparseTensor(b_indices, b_values, b_dense_shape)

    # Convert SparseTensors to CSR SparseMatrix
    a_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        a_st.indices, a_st.values, a_st.dense_shape)
    b_sm = sparse_csr_matrix_ops.sparse_tensor_to_csr_sparse_matrix(
        b_st.indices, b_st.values, b_st.dense_shape)

    # Compute the CSR SparseMatrix matrix multiplication
    c_sm = sparse_csr_matrix_ops.sparse_matrix_sparse_mat_mul(
        a=a_sm, b=b_sm, type=tf.float32)

    # Convert the CSR SparseMatrix product to a dense Tensor
    c_sm_dense = sparse_csr_matrix_ops.csr_sparse_matrix_to_dense(
        c_sm, tf.float32)
    # Evaluate the dense Tensor value
    # c_sm_dense_value = sess.run(c_sm_dense)

    print(c_sm_dense)
tf.profiler.experimental.stop()
```

### trace
![Screenshot from 2021-08-12 08-09-44](https://user-images.githubusercontent.com/12267324/129119243-edb879ee-6300-480d-b7ed-406f0277e116.png)

I wonder why **sparse_tensor_to_csr_sparse_matrix** and **sparse_matrix_sparse_mat_mul** is calculated on both cpu and gpu because theoretically they should be calculated on gpu only for the sake of performance acceleration. Also, I've found the corresponding code [sparse_mat_mul_op](https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/core/kernels/sparse/sparse_mat_mul_op.cc#L534) and [csr_sparse_matrix_to_dense_op](https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/sparse/csr_sparse_matrix_to_dense_op.cc#L211) for gpu version. But unexpectedly, the calculation is placed on both the cpu and gpu for twice, so is it the duplicate calcualtion?

**Comment by tilakrayal** [comment]
@sjtusmartboy,
I tried to execute the code on tensorflow v2.11.0-dev20220829. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/86cbafccb1403a2280fa6e0f2f8202fe/untitled545.ipynb) and let us know if the issue still persists. Thank you!
