### ISSUE TITLE
n-api supports automatic downgrade instead of hard-coded

### ISSUE THREAD

**Issue by yangshengdong** [tensorflow/tensorflow#51443]
### background
I used @tensorflow/tfjs-node to build a coding service, but the deployment failed due to the inconsistency of the node version during build and runtime.

Uncontrollable node version during build and runtime

### for example：

build：node v12.19.1 corresponds to N-API 7
runtime ：node v12.22.3 corresponds to N-API 8

### result：
"The Node.js native addon module (tfjs_binding.node) can not be found at path: /code/node_modules/_@tensorflow_tfjs-node@3.8.0@@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node."

### feature Request：

The higher version of n-api will automatically be compatible with the lower version, but [here](https://github.com/tensorflow/tfjs/blob/e36545270e8176aa14d03e82ccf2baf6e9693f69/tfjs-node/package.json#L84) is hard to write

**Comment by tilakrayal** [comment]
@yangshengdong ,
This issue is more suitable for TensorFlow JS repo. Please post it on Tensorflow/tfjs repo from [here](https://github.com/tensorflow/tfjs/issues). Thanks!

**Comment by yangshengdong** [comment]
Have moved [here](https://github.com/tensorflow/tfjs/issues/5484)
