### ISSUE TITLE
dlopen/dlclose a so file which contain tensorflow static library cause memory leak

### ISSUE THREAD

**Issue by erizen** [tensorflow/tensorflow#51441]
In our scenario, there is only one process to serve the request, and the process will be closed only when an exception occurs. Each model inference algorithm is complied into a so file and loaded into this process.  Multiple model inference algorithms will be loaded in this process. Each so file contain a tensorflow static library.

In the service, the so file of different model inference algorithms (model _ 1.so...) will often be loaded and closed through dlopen and dlclose. Because some static variables in tensorflow are created through the “new” method , as shown below. When closing the “so” with dlclose，these static variables will not be released， which will cause memory leaks.
```
    typedef std::unordered_map<string, SessionFactory*> SessionFactories;     
    SessionFactories* session_factories() {
        static SessionFactories* factories = new SessionFactories;
        return factories;
    }
```

```
    DirectSession* session = new DirectSession(options, new StaticDeviceMgr(std::move(devices)), this);
    {
        mutex_lock l(sessions_lock_);
        sessions_.push_back(session);
    }
    *out_session = session;
    return Status::OK();
```

What is the purpose of tensorflow designed like this？Will it be optimized for this problem in the future?

**Comment by sushreebarsa** [comment]
@erizen  In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
