### ISSUE TITLE
saved_model  bug

### ISSUE THREAD

**Issue by gao8954** [tensorflow/tensorflow#51448]
tf version 2.3.2

when  train the model,some features is multi hot,use the split func like this:
```
        def split(x):
            x['seq_grade_clicks'] = tf.strings.split(x['seq_grade_clicks'], sep=":").to_sparse()
            x['seq_subject_clicks'] = tf.strings.split(x['seq_subject_clicks'], sep=":").to_sparse()
            x['seq_course_clicks'] = tf.strings.split(x['seq_course_clicks'], sep=":").to_sparse()
            return x
```

but saved model,and load model
`model = tf.keras.models.load_model(saved_model_dir)`
the errors is
![image](https://user-images.githubusercontent.com/7404433/129173015-dc7a033a-c145-4801-a334-27e6fb88a775.png)

although I specified the name of to_sparse(name="features"),it also report the above error,

when use `tf.saved_model.load(saved_model_dir)` is ok,but lose the feature name like this:

![image](https://user-images.githubusercontent.com/7404433/129173426-8f7b857c-4c0e-4688-b643-73811726cf41.png)

when use the tf serving ,serving the model ,it also can not konwn the feature name,

when  train the model,some features is multi hot,use the split func like this:
```
        def split(x):
            x['seq_grade_clicks'] = tf.strings.split(x['seq_grade_clicks'], sep=":").to_tensor()
            x['seq_subject_clicks'] = tf.strings.split(x['seq_subject_clicks'], sep=":").to_tensor()
            x['seq_course_clicks'] = tf.strings.split(x['seq_course_clicks'], sep=":").to_tensor()
            return x
```
![image](https://user-images.githubusercontent.com/7404433/129179798-70a5974d-7025-4d02-9418-c76f3c344b85.png)

everything is ok ,but when use the tf serving ,serving the model or predict, it can not batch infer ,because some features is multi hot and is variable length, but the tensor is fixed length

**Comment by sanatmpa1** [comment]
@gao8954,

Can you kindly provide standalone code with sample data, for us to reproduce the issue and expedite the trouble-shooting process? Thanks!

**Comment by gao8954** [comment]
> @gao8954,
> 
> Can you kindly provide standalone code with sample data, for us to reproduce the issue and expedite the trouble-shooting process? Thanks!

my code is a bit messy, but the issue is almost about use the feature_column embedding

```
        combiner = feature_conf.get("combiner", "mean")
        id_feature = tf.feature_column.categorical_column_with_hash_bucket(key=name,
                                                                           hash_bucket_size=feature_conf[
                                                                               'hash_bucket_size'], dtype=dtype)
        emb_col = tf.feature_column.embedding_column(id_feature, dimension=feature_conf['embedding_dimension'],
                                                     combiner=combiner)
```

the train data  is a csv file,and some feature is a sequence，so i organize data like this:
`4:5:6,1:2:23:59`

when train the model,the input is like this:

```
    def input_fn():
        df_train = pd.read_csv(FLAGS.record_train, header=0)
        df_test = pd.read_csv(FLAGS.record_test, header=0)
        y_train = df_train.pop('is_trans')
        y_test = df_test.pop('is_trans')

        train_dataset = tf.data.Dataset.from_tensor_slices((dict(df_train), y_train))
        test_dataset = tf.data.Dataset.from_tensor_slices((dict(df_test), y_test))

        def split(x):
            x['seq_grade_clicks'] = tf.strings.split(x['seq_grade_clicks'], sep=":").to_tensor()
            x['seq_subject_clicks'] = tf.strings.split(x['seq_subject_clicks'], sep=":").to_tensor()
            x['seq_course_clicks'] = tf.strings.split(x['seq_course_clicks'], sep=":").to_tensor()
            return x

        train_dataset = train_dataset.shuffle(buffer_size=2048).batch(2048).prefetch(buffer_size=2048 * 2)
        train_dataset = train_dataset.map(lambda x, y: (split(x), y))
        test_dataset = test_dataset.batch(2048)
        test_dataset = test_dataset.map(lambda x, y: (split(x), y))
        return train_dataset, test_dataset
```

because have seq features,and did not find a better way,so use the dataset map func to transform the data, tf.strings.split() func  return  a type of   tf.RaggedTensor ,it can not fit to the model,export the error of RaggedTensorSpec can not conver to tensor, so call the to_sparse()  then all the problems can be reproduced above

**Comment by sanatmpa1** [comment]
@gao8954,

As I can see you are using `TF 2.3.2`, Could you try updating to latest stable version `TF 2.5` and let us know if this issue still persists? Thanks!

**Comment by gao8954** [comment]
> @gao8954,
> 
> As I can see you are using `TF 2.3.2`, Could you try updating to latest stable version `TF 2.5` and let us know if this issue still persists? Thanks!

update to TF 2.5, this issue still persists

**Comment by sanatmpa1** [comment]
@gao8954,

Thanks for the update, In this case, we may need the reproducible code to analyze the issue properly. Can you share the standalone code or colab gist to expedite the troubleshooting process?
