### ISSUE TITLE
dtype of RNN cell's state is changed to tf.float32 during reset_states

### ISSUE THREAD

**Issue by TillHa** [tensorflow/tensorflow#51449]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: both win10 and CentOS Linux
-   **TensorFlow installed from (source or binary)**: pip
-   **TensorFlow version (use command below)**: 2.6.0
-   **Python version**: 3.8
-   **Bazel version (if compiling from source)**:
-   **Exact command to reproduce**: see below

### Describe the problem
I have implemented a recurrent cell which is to be wrapped within a `tf.keras.layers.RNN.` The cell has a state whose data type is not `tf.float32` but `tf.complex64`. However, each time when `layer.reset_states()` is invoked, the data type of the state is changed to `tf.float32`. 

I assume, a reason for this issue is line 933, 934 in keras/layers/recurrent.py
```
      flat_states_variables = tf.nest.map_structure(
          backend.variable, flat_init_state_values)
```
Here, the initialized state values are stored in `flat_init_state_values` and `backend.variable` is called on each of the states. However, no `dtype` argument is passed to `backend.variable`. As a consequence it defaults to `tf.float32` for all states. Then a value error is thrown during the initial symbolic call. See attached stack trace. 

I would recommend the following patch, which solves the issue for me
```
      flat_states_variables = tf.nest.map_structure(
    lambda var: backend.variable(var, var.dtype), flat_init_state_values)
```

### Source code / logs
Currently, the example fails at the construction of the RNN layer.
```
import tensorflow as tf

class RecurrentCell(tf.keras.layers.Layer):
    def __init__(self, state_size):
        super(RecurrentCell, self).__init__()
        self.state_size = state_size

    def build(self, input_shape):
        super(RecurrentCell, self).build(input_shape)

    def get_initial_state(self, inputs=None, batch_size=None, dtype=None):
        # explicit initialization with tf.complex64
        return tf.zeros((self.state_size, ), dtype=tf.complex64)

    @tf.function
    def call(self, inputs, states):
        # toy example
        x = inputs
        xfd = tf.signal.rfft(x)[..., :self.state_size]
        yfd = tf.multiply(xfd, states)
        return tf.signal.irfft(yfd), states


recCell = RecurrentCell(state_size=5)

inp = tf.keras.Input(shape=(None, 8),
                     batch_size=32)
out = tf.keras.layers.RNN(recCell,
                          return_sequences=True,
                          stateful=True,
                          return_state=False)(inp)
model = tf.keras.Model(inputs=[inp], outputs=[out])

y = model.predict(tf.random.normal((32, 16, 8)))
```

Stack trace:
[stacktrace.txt](https://github.com/tensorflow/tensorflow/files/6975576/stacktrace.txt)

**Comment by tilakrayal** [comment]
@TillHa ,

We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Thanks!

**Comment by TillHa** [comment]
Hello @tilakrayal, From the templates I see that keras related issues belong to the keras repository. Hence I [raised the issue there](https://github.com/keras-team/keras/issues/15164).
Thanks a lot!
