### ISSUE TITLE
tf.identity cannot support a tuple value

### ISSUE THREAD

**Issue by sddi** [tensorflow/tensorflow#51440]
I have recently use v1.13 of Tensorflow.
In my code:
```
topk = tf.nn.top_k(out_softmax, k=100)
with tf.control_dependencies([some ops]):
      topk = tf.identity(topk)
      # topk[0] = tf.identity(topk[0])
      # topk[1] = tf.identity(topk[1])
```
it shows ： 
```
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'int32'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'Xpredict__scope__/TopKV2:1' shape=(?, 100) dtype=int32>)
````

or 

```
TypeError: 'TopKV2' object does not support item assignment
```
how can i fix it ?

**Comment by tilakrayal** [comment]
@sddi ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by tilakrayal** [comment]
Also We can see you are using tf v1.13, can you please update to latest stable tensorflow version(v2.5) and let us know if the issue still persists.Thanks!

**Comment by sddi** [comment]
> Also We can see you are using tf v1.13, can you please update to latest stable tensorflow version(v2.5) and let us know if the issue still persists.Thanks!

In my team, it just support v1.13. 
cases:
```
logits = tf.add(tf.matmul(hidden_out, weights["layer_1"]), weights["layer_1_bias"])
out_softmax = tf.nn.softmax(logits)
with tf.control_dependencies(user_define_ops): # user_define_ops: just like some assign ops (using tf.assign ):
        topk = tf.identity(topk)
```
then  when i run my code, is shows the errors.

**Comment by tilakrayal** [comment]
@sddi ,
As  mentioned can you please update to latest stable tensorflow version(v2.5) as v1.x is not actively supported and let us know if the issue still persists.Thanks!
