### ISSUE TITLE
Dereferencing null pointer in GPU delegate

### ISSUE THREAD

**Issue by GoldFeniks** [tensorflow/tensorflow#51457]
The following code in GPU delegate constructor should probably use `options_` instead of `options` that is potentially a null pointer

https://github.com/tensorflow/tensorflow/blob/8b06339173d65b9f48236f4051d31e32a2e86191/tensorflow/lite/delegates/gpu/delegate.cc#L95-L102

**Comment by sanatmpa1** [comment]
@GoldFeniks 

Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) for us to expedite the trouble-shooting process? Thanks!

**Comment by GoldFeniks** [comment]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Just using tflite as a cpp library
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Arch
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): commit hash b2b7933ffe56f140a34c452ab48a7738cf352b2b
- Bazel version (if compiling from source): I used CMake 3.21.1
- GCC/Compiler version (if compiling from source): 11.1.0

**Describe the current behavior**
Calling `TfLiteGpuDelegateV2Create(nullptr)` cases a `segmentation fault`

**Describe the expected behavior**
Code executes without an error 

**Standalone code to reproduce the issue**
```c++
auto tf_delegate = tflite::Interpreter::TfLiteDelegatePtr(TfLiteGpuDelegateV2Create(nullptr), TfLiteGpuDelegateV2Delete);
```

**Other info / logs** 
The error is caused by this https://github.com/tensorflow/tensorflow/blob/8b06339173d65b9f48236f4051d31e32a2e86191/tensorflow/lite/delegates/gpu/delegate.cc#L95-L102

`options_` should be used instead of `options` because the latter can be a null pointer

**Comment by mohantym** [comment]
Hi @GoldFeniks !
Thanks for reporting the bug.
Required changes has already been made in Master branch. Could we consider this resolved now.
[Ref.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/delegate.cc)

Thank you!

**Comment by GoldFeniks** [comment]
Hi!
Yes, the issue is resolved. Thank you!
