### ISSUE TITLE
Multiple versions of TensorFlow co-installed potentially cause ABI mismatch

### ISSUE THREAD

**Issue by sclarkson** [tensorflow/tensorflow#51451]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): both
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

When multiple tensorflow instances are installed in different parts of your python path, TensorFlow will attempt to load kernel libraries from all of them, potentially resulting in an ABI mismatch.

```
$ python3 -c "import tensorflow"
No protocol specified
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sclarkson/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 438, in <module>
    _ll.load_library(_main_dir)
  File "/home/sclarkson/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/lib/python3/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb

```

Observe above, the TensorFlow instance in `~/.local/lib/python3/` attempting to load a shared library from `/usr/lib/python3/`. Because of different compilation options, the library from the system-wide install is expecting symbols that do not exist in the pip install.

**Describe the expected behavior**

TensorFlow should only load kernels from its own install.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): modify kernel preloading to only use its own install

**Standalone code to reproduce the issue**

Compile TensorFlow from source and install system-wide.
Install TensorFlow from pip with `pip install --user tensorflow`
Then run `python -c "import tensorflow"`

**Other info**

This is a continuation of #42978

**Comment by sushreebarsa** [comment]
@sclarkson The issue will move to closed status once the PR is merged.Thank you!
