### ISSUE TITLE
"ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors" for a graph that doesn't appear to have dynamic-sized tensors

### ISSUE THREAD

**Issue by skillingt** [tensorflow/tensorflow#51467]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary (pip wheel)
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.7.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When using the Edge TPU compiler on a TFLite model (converted via `tf.compat.v1.TFLiteConverter.from_session` from a TensorFlow model), the compiler fails with the error message:
`ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.`
I've examined the model in Netron and haven't been able to find a dynamic-sized tensor input.

**Describe the expected behavior**
The Edge TPU compiler successfully compiles the model as it has static-sized tensors.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): Sure, I would
- Briefly describe your candidate solution(if contributing): Not a solution, but it would be great to understand which part(s) of the model the compiler thinks have dynamic sizes.

**Standalone code to reproduce the issue**
`edgetpu_compiler -s <path/to/model>`
See attached file [mobilenet_v2_small_from_session_quant_exp_conv_exp_quant_sel_ops_static.zip](https://github.com/tensorflow/tensorflow/files/6977427/mobilenet_v2_small_from_session_quant_exp_conv_exp_quant_sel_ops_static.zip)
It's converted from the `mobilenet_v2_small` model in this repository: https://github.com/gsethi2409/tf-pose-estimation

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Snippet of code used for conversion to TFlite:
```
def rep_data_gen():
    for x in tf.data.Dataset.list_files(</path/to/training/images/):
        image = tf.io.read_file(x.numpy())
        image = tf.image.decode_jpeg(image)
        image = tf.image.convert_image_dtype(image, tf.float32)
        image = tf.image.resize(image, [320, 240])
        image = image[np.newaxis, :, :, :]
        # image = image / 255.0
        yield [image, tf.constant([160, 120])]

# Set input shape for non-placeholder, output tensors only look at name
self.tensor_image.set_shape([1, 320, 240, 3])
self.upsample_size.set_shape([2])
sess_converter = tf.compat.v1.lite.TFLiteConverter.from_session(
    self.persistent_sess,
    input_tensors=[self.tensor_image, self.upsample_size],
    output_tensors=[self.tensor_peaks, self.tensor_heatMat_up, self.tensor_pafMat_up]
)
sess_converter.experimental_new_converter = True
model_name = "mobilenet_v2_small_from_session_quant_exp_conv_exp_quant_sel_ops_static.tflite"
sess_converter.optimizations = [tf.lite.Optimize.DEFAULT]
sess_converter.representative_dataset = rep_data_gen
sess_converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS,
                                            tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
sess_converter.inference_input_type = tf.int8  # or tf.uint8
sess_converter.inference_output_type = tf.int8  # or tf.uint8
sess_converter.experimental_new_quantizer = True
tflite_model = sess_converter.convert()
```

**Comment by skillingt** [comment]
Checking in on this issue - is there any additional information I can provide to help move the investigation along?

**Comment by mohantym** [comment]
Hi @skillingt !
Can you add one more flag in above conversion with 2.9/2.10  and let us know the result.
`converter.Target_Spec.supported_types=[tf.int8]
`
Thank you!

**Comment by mohantym** [comment]
Hi @skillingt !

Could you confirm that did above [pointer](https://github.com/tensorflow/tensorflow/issues/51467#issuecomment-1269765351)  solve this issue. 
Keeping this issue open until it is confirmed from your side.

Thank you!

**Comment by mohantym** [comment]
Keeping this issue open until it is confirmed from your side.
