### ISSUE TITLE
ResNetV2 implementation problem

### ISSUE THREAD

**Issue by seermer** [tensorflow/tensorflow#51464]
**System information**
(not related to installation)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0 GPU
- Python version: 3.8

**Describe the expected behavior**
As shown in the image below from **Identity Mappings in Deep Residual Networks** by He et al.\
ResNetV2 block has its preactivation **after** branching (bn-relu-conv-bn-relu-conv are all in contained in residual)
![image](https://user-images.githubusercontent.com/49250812/129236962-d30af2fc-8bac-4ddf-a951-6d986d25bef3.png)
the **only** exception on preactivation is the first block of the first stage\
quote from the original paper:
> For the first Residual Unit (that follows a stand-alone convolutional layer,
> conv1), we adopt the first activation right after conv1 and before splitting into
> two paths

**Describe the current behavior**
ResNetV2 Falsefully put preactivation before branching when channel increases for **all stages**
![image](https://user-images.githubusercontent.com/49250812/129238244-89917129-a60f-45a0-a29c-26cd3134a249.png)
As shown in above image, the output of `ResNet50V2(weights=None).summary()`\
the red arrow I added points to the shortcut path, it is connected to preact_relu, which means the preactivation is done **before** branching to residual and shortcut, which is not true according to the original paper\
a simple drawing representing the first block of each stage in current implementation, which is obviously not equivalent to the image from the original paper:
![image](https://user-images.githubusercontent.com/49250812/129239135-4cf8449e-87c8-439a-89c1-070ccd09411f.png)

**Comment by sushreebarsa** [comment]
@seermer In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by seermer** [comment]
> @seermer In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

Thanks for replying, I am not sure what you mean by "provide a code snippet to reproduce the issue", it doesn't cause error or unexpected behavior, so you can't reproduce it, it is an implementation problem on model architecture. You can find the problem by reading the output from the below code if this is what you mean:
```
from tensorflow.keras import applications
applications.ResNet50V2(weights=None).summary()
```

**Comment by sushreebarsa** [comment]
@seermer Thank you for the update! We see that this is ResNetv2 implementation issue which is more specific to Keras api application.
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues), you will get the right help there.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by seermer** [comment]
Thanks for notifying, sorry that I did not notice the repo has been split. I am closing this one and will open a new one on that repo.
