### ISSUE TITLE
Add support/upgrade for flatbuffers 2.0

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#51487]
**System information**
- TensorFlow version (you are using): 2.6.0 / latest nightly
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The TensorFlow pip package currently pins the flatbuffers dependency to `~1.12`:
https://github.com/tensorflow/tensorflow/blob/20b1e26b1df7b5dbe4548b9af8a6ff2348f620cc/tensorflow/tools/pip_package/setup.py#L86

Flatbuffers 2.0 has been release in May and it would be great if TensorFlow would support the new release as well, or upgrade it's required Flatbuffers version to ~2.0. This might require some minor code changes similar to https://github.com/google/jax/pull/6710, but I don't think there should be any major blockers that would prevent an upgrade.

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Anyone using Flatbuffers 2.0 in their code or relying on packages that require 2.0.

**Comment by mihaimaruseac** [comment]
This is on the long term roadmap

**Comment by Saduf2019** [comment]
This issue will be closed once [the pr](https://github.com/tensorflow/tensorflow/pull/51504) is merged.

**Comment by Saduf2019** [comment]
Moving this to closed status as pr is merged.

**Comment by lgeiger** [comment]
> Moving this to closed status as pr is merged.

@Saduf2019 The PR you linked didn't fully solve the issue. I think this should be reopened until #51577 has been merged.

**Comment by yan12125** [comment]
Is flatbuffers 2.x support complete? Another similar issue is closed https://github.com/tensorflow/tensorflow/issues/55740.

**Comment by mohantym** [comment]
@yan12125 @lgeiger !
In 2.10 release , Flatbuffer version has successfully been upgraded to >=2.0 .[ Reference](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py).
Could we mark this issue as resolved now.
Thank you!
