### ISSUE TITLE
New TensorRT model occupying more GPU-Memory as compared to the older version

### ISSUE THREAD

**Issue by memr5** [tensorflow/tensorflow#51484]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.1/8.1.0
- GPU model and memory: NVIDIA GeForce RTX 3080 10GB

**Describe the current behavior**
I am converting a tensorflow model (.h5 -> saved_model_format -> tensorrt model) to a tensorrt model using tensorflow 2.5.0 (attached tensorrt.py). The code is occupying almost **3.5GB** of GPU Memory. 

If I load the same model in the below specified environment, then that code is occupying max **~1.1GB** of GPU memory:
**TensorRT Version**: 5.1.2.2-1
**GPU Type**: GeForce RTX 2080 Ti
**Nvidia Driver Version**: 418.87.00
**CUDA Version**:  10.1
**CUDNN Version**: 7.6.2
**Operating System + Version**:  Ubuntu 16.04.7 LTS
**Python Version (if applicable)**: 3.6.13
**TensorFlow Version (if applicable)**:  1.14.1

**Describe the expected behavior**
I want to figure out what is causing this huge memory usage difference. The base models (.h5) are same just the way of converting the models differs in TF1.14.1 & TF2.5. 

Also I am getting this at inference time:
E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger INVALID_ARGUMENT: Cannot set empty memory.

I have attached codes & output for reference and reproducing this issue.

**Standalone code to reproduce the issue**
[attachment.zip](https://github.com/tensorflow/tensorflow/files/6981299/attachment.zip)
- tensorrt.py - code to convert the dummy_model to a tensorrt_model
- gpu_usage - to track the gpu usage
- Code-Output - tensorrt_output.txt

**Other info / logs**
[tensorrt_output.txt](https://github.com/tensorflow/tensorflow/files/6981335/tensorrt_output.txt)
[gpu_usage_dummy.txt](https://github.com/tensorflow/tensorflow/files/6981337/gpu_usage_dummy.txt)

**Comment by sushreebarsa** [comment]
@memr5 Could you please try using latest stable version of tensorflow  2.6.0 and let us know if the issue still persists ?Thank you!

**Comment by memr5** [comment]
> @memr5 Could you please try using latest stable version of tensorflow **`2.6.0`** and let us know if the issue still persists ?Thank you!

Hey @sushreebarsa, 
I will try the stable version. 
Recently, I also tried [NGC Tensorflow](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow) but the memory occupied is way more than before. I am also going to try an older version of the NGC Container to see if the issue still persists. 

I will keep updating this thread.

**Comment by memr5** [comment]
Hey @sushreebarsa,

I tried with TF2.6, now I am not getting this error: 
E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:42] DefaultLogger INVALID_ARGUMENT: Cannot set empty memory.

but still the memory usage is around ~3.5GB.

**Comment by sushreebarsa** [comment]
@sanatmpa1 Was able to reproduce the issue in TF  [v2.5](https://colab.research.google.com/gist/sushreebarsa/d1881891194b308ec508a565414aff07/51484.ipynb), [2.6.0](https://colab.research.google.com/gist/sushreebarsa/a7a33f972fe7dd375beedb30bcd9ee97/untitled390.ipynb) , please find the gists attached .Thank you!

**Comment by christopherbate** [comment]
In both cases are you using "TensorRT 5.1.2.2-1"?

I will take a look tomorrow.

FWIW, TRT 5 support is removed in master already.

**Comment by memr5** [comment]
Talking about the NGC Tensorflow containers, I am using whatever I get in the container. 
For 2080 container (19.10) it is TensorRT 5.1.5.
And for 3080 container (21.07) it is TensorRT 8.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
