### ISSUE TITLE
same issue with CUDA=10.0 CUDNN=7.4 Tensorflow=1.14.0

### ISSUE THREAD

**Issue by YongyuG** [tensorflow/tensorflow#51482]
same issue with CUDA=10.0 CUDNN=7 Tensorflow=1.14.0
stuck at `I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10`

**Comment by sushreebarsa** [comment]
@YongyuG We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Thanks!
