### ISSUE TITLE
No registered 'EagerPyFunc' OpKernel for XLA_GPU_JIT devices compatible with node {{node EagerPyFunc}}){{node EagerPyFunc}}

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51493]
**tensorflow 2.6
ubuntu 18.10
python 3.6**

### The whole error message:

Traceback (most recent call last):
  File "main_Semantic3D.py", line 626, in <module>
    main1()
  File "main_Semantic3D.py", line 562, in main1
    model = Network(dataset, cfg)
  File "/home/sjtusmartboy/opt/Projects/RandLA-Net/Net.py", line 97, in __init__
    self.train( xyz_batch, color_batch)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3040, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_train_8311[_XlaMustCompile=true,config_proto="\n\007\n\0...02\001\000",executor_type=""] on XLA_GPU_JIT: EagerPyFunc (No registered 'EagerPyFunc' OpKernel for XLA_GPU_JIT devices compatible with node {{node EagerPyFunc}}){{node EagerPyFunc}}**
The op is created at: 
File "main_Semantic3D.py", line 626, in <module>
  main1()
File "main_Semantic3D.py", line 562, in main1
  model = Network(dataset, cfg)
File "/home/sjtusmartboy/opt/Projects/RandLA-Net/Net.py", line 97, in __init__
  self.train( xyz_batch, color_batch)
File "/home/sjtusmartboy/opt/Projects/RandLA-Net/Net.py", line 586, in train
  self.adjacency_sparse_batch, self.scaledLaplacian_sparse_batch = self.get_graph(xyz_batch,
File "/home/sjtusmartboy/opt/Projects/RandLA-Net/Net.py", line 176, in get_graph
  ret = tf.py_function(**DP.knn_search**, [xyz_batch, xyz_batch, cfg.k_n], [tf.int32, tf.float64]) [Op:__inference_train_8311]

---------------------------------------------------------------------------------------------------------------------

**knn_search is the wraper of an op, code is as follows,**

```
void cpp_knn_batch(const float* batch_data, const size_t batch_size, const size_t npts, const size_t dim,
			const float* queries, const size_t nqueries,
			const size_t K, long* batch_indices, float* batch_dist){

	for(size_t bid=0; bid < batch_size; bid++){

	    std::cout<<1111111111111<<std::endl;

		const float* points = &batch_data[bid*npts*dim];
		long* indices = &batch_indices[bid*nqueries*K];
		float* dist = &batch_dist[bid*nqueries*K];

		// create the kdtree
		typedef KDTreeTableAdaptor< float, float> KDTree;
		KDTree mat_index(npts, dim, points, 10);
		
		mat_index.index->buildIndex();

		std::vector<float> out_dists_sqr(K);
		std::vector<size_t> out_ids(K);

		// iterate over the points
		for(size_t i=0; i<nqueries; i++){
			nanoflann::KNNResultSet<float> resultSet(K);
			resultSet.init(&out_ids[0], &out_dists_sqr[0] );
			mat_index.index->findNeighbors(resultSet, &queries[bid*nqueries*dim + i*dim], nanoflann::SearchParams(10));
			for(size_t j=0; j<K; j++){
				indices[i*K+j] = long(out_ids[j]);
				dist[i*K+j] = float(out_dists_sqr[j]);

			}
		}

	}

}

void cpp_knn_batch_omp(const float* batch_data, const size_t batch_size, const size_t npts, const size_t dim, 
				const float* queries, const size_t nqueries,
				const size_t K, long* batch_indices, float* batch_dist){

# pragma omp parallel for
	for(size_t bid=0; bid < batch_size; bid++){

		const float* points = &batch_data[bid*npts*dim];
		long* indices = &batch_indices[bid*nqueries*K];
		float* dist = &batch_dist[bid*nqueries*K];

		// create the kdtree
		typedef KDTreeTableAdaptor< float, float> KDTree;
		KDTree mat_index(npts, dim, points, 10);
		
		mat_index.index->buildIndex();

		std::vector<float> out_dists_sqr(K);
		std::vector<size_t> out_ids(K);

		// iterate over the points
		for(size_t i=0; i<nqueries; i++){
			nanoflann::KNNResultSet<float> resultSet(K);
			resultSet.init(&out_ids[0], &out_dists_sqr[0] );
			mat_index.index->findNeighbors(resultSet, &queries[bid*nqueries*dim + i*dim], nanoflann::SearchParams(10));
			for(size_t j=0; j<K; j++){
				indices[i*K+j] = long(out_ids[j]);
				if(out_dists_sqr[j]>3.4028235e+37)
				    out_dists_sqr[j] = 0;
				dist[i*K+j] = sqrt(float(out_dists_sqr[j]));
// 				std::cout<<out_dists_sqr[j]<<std::endl;
			}
		}

	}

}
```

------------------------------------------------------------------------------------------------------------------------------------------------

So what causes the error, the **tf.py_function** is not compatible with the xla or the **c++ op** is not compatible with the xla? If the code is not decorated with     `@tf.function(autograph=True, jit_compile=True)`, the program runs well.

**Comment by sjtusmartboy** [comment]
Able to reproduce the error with the minimum code.

```
import tensorflow as tf

class Dense(tf.Module):
    def __init__(self, input_dim, output_size, name=None):
        super(Dense, self).__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([input_dim, output_size]), name='w')
        self.b = tf.Variable(tf.zeros([output_size]), name='b')


    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

model = Dense(2,4)

class Test(object):
    def __init__(self):
        self.output = model([[7.0, 3]])
        self.optimizer = tf.compat.v1.train.AdamOptimizer(0.4)

        self.run()


    def compare(self, y_true, output):
        return tf.square(y_true - output)

    def loss_fn(self):
        y_true = tf.ones([1,4])

        self.output = model([[7.0, 3]])

        comp = tf.py_function(self.compare, [y_true , self.output], tf.float32)
        loss = tf.reduce_mean(comp) # error

        # output2 = model([[7.0, 3]])
        # loss = tf.reduce_mean(tf.square(y_true - output2))

        print(loss)
        return loss

    @tf.function(autograph=True, jit_compile=True)
    def run(self):
        for i in range(10):
            train_op = self.optimizer.minimize(self.loss_fn)

Test()

```


### Error message

```
2021-08-14 22:03:16.020356: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xla_ops.cc:247 : Invalid argument: Detected unsupported operations when trying to compile graph __inference_run_1334[_XlaMustCompile=true,config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001\202\001\000",executor_type=""] on XLA_GPU_JIT: EagerPyFunc (No registered 'EagerPyFunc' OpKernel for XLA_GPU_JIT devices compatible with node {{node EagerPyFunc}}){{node EagerPyFunc}}
The op is created at: 
File "test8.py", line 47, in <module>
  Test()
File "test8.py", line 22, in __init__
  self.run()
File "test8.py", line 44, in run
  for i in range(10):
File "test8.py", line 45, in run
  train_op = self.optimizer.minimize(self.loss_fn)
File "test8.py", line 33, in loss_fn
  comp = tf.py_function(self.compare, [y_true , self.output], tf.float32)
Traceback (most recent call last):
  File "test8.py", line 47, in <module>
    Test()
  File "test8.py", line 22, in __init__
    self.run()
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3040, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/sjtusmartboy/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_run_1334[_XlaMustCompile=true,config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0012\005*\0010J\0008\001\202\001\000",executor_type=""] on XLA_GPU_JIT: EagerPyFunc (No registered 'EagerPyFunc' OpKernel for XLA_GPU_JIT devices compatible with node {{node EagerPyFunc}}){{node EagerPyFunc}}
The op is created at: 
File "test8.py", line 47, in <module>
  Test()
File "test8.py", line 22, in __init__
  self.run()
File "test8.py", line 44, in run
  for i in range(10):
File "test8.py", line 45, in run
  train_op = self.optimizer.minimize(self.loss_fn)
File "test8.py", line 33, in loss_fn
  comp = tf.py_function(self.compare, [y_true , self.output], tf.float32) [Op:__inference_run_1334]

```

**Comment by sjtusmartboy** [comment]
In the first project code, `ret = tf.py_function(DP.knn_search, [xyz_batch, xyz_batch, cfg.k_n], [tf.int32, tf.float64])`, in which `DP.knn_search` is the python function that takes array parameter, while  `[xyz_batch, xyz_batch, cfg.k_n]` are all of type tensorflow tensor, how can I pass the tensorflow parameter into the python function without using `tf.py_function`

**Comment by sjtusmartboy** [comment]
If I'm using tf.function(jit_compile=True), should I disable eager execution?

**Comment by sjtusmartboy** [comment]
Let me conclude my demand.
What I have: 1)Python function: DP.knn_search
                     2)parameter of fun is tensor

What I need: tf.function(jit_compile=True)

Difficulties: 1.cannot pass tensor into python function directly
                   2. cannot use tf.py_function since it contradicts tf.function

**Comment by sjtusmartboy** [comment]
@sanatmpa1 Please first try the reproduction code and try to fix it.

**Comment by sanatmpa1** [comment]
@sjtusmartboy,

As per documentation of `tf.function`, when setting `jit_compile=True`, it throws `InvalidArgumentError` if the whole function is not compileable by `XLA` and [here](https://www.tensorflow.org/xla/known_issues) are few known issues. Have you already took a look at this link?

**Comment by sjtusmartboy** [comment]
@sanatmpa1 I've checked that link, it seems tf.function is not included in it, especially when  setting jit_compile=True

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
