### ISSUE TITLE
tf2.6 training speed can be ~1/10 of tf2.5 when embedding_column has medium bucket size(e.g. 4M)

### ISSUE THREAD

**Issue by ttang235** [tensorflow/tensorflow#51490]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.7 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0 and 2.5.0
- Python version: 3.6.11
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I run the same piece of code using tf 2.5.0 and 2.6.0, and the training is much slower on tf 2.6.0 (can be ~1/10 of tf 2.5.0)
The code is attached below. Using tf 2.5.0, the training speed on my server is ~58 step/s. Using tf 2.6.0, the training speed is ~ 0.9 step/s

**Describe the expected behavior**
The training speed should be similar on tf 2.5.0 and 2.6.0.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```Python
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)
from tensorflow.feature_column import categorical_column_with_hash_bucket, embedding_column
cat_column = categorical_column_with_hash_bucket('video_id', hash_bucket_size=4000000, dtype=tf.int64)
emb_column = embedding_column(cat_column, dimension=64, combiner='sum')
cls = tf.estimator.DNNClassifier([512,256], [emb_column], "/tmp/model/")

def input_fn():
    ds = tf.data.Dataset.range(10000000)
    ds = ds.map(lambda x: ({'video_id':x}, x % 2)).batch(1024)
    return ds

cls.train(input_fn)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ttang235** [comment]
@sanatmpa1 Hi Sanat, have you been able to reproduce this problem? Just run the attached code in tf 2.5.0 and tf 2.6.0 env, and the training speed difference should be obvious.

This is a big problem for us, because we want to use the MutableHashTable in tf 2.6.0 (which doesn't exist in tf 2.x before 2.6), but got stuck in this issue. 
Looking forward to hearing from you :)

**Comment by sanatmpa1** [comment]
@jvishnuvardhan,

I am able to reproduce the issue and please take a look on the colab [gist here](https://colab.research.google.com/gist/sanatmpa1/7940b81b6e83a91371aa0302b4797201/51490.ipynb). As mentioned in issue description, the training is around 10 times slower in `TF 2.6` compared to `TF 2.5`.

**Comment by ttang235** [comment]
@jvishnuvardhan Hi Vishnuvardhan,
Could you help take a look at this issue at your earliest convenience? This is a real blocking issue for us. 
Thanks!

**Comment by ttang235** [comment]
@jvishnuvardhan Hi Vishnuvardhan, are you currently looking into this issue?

**Comment by jvishnuvardhan** [comment]
@ttang235 I can see lower performance with `TF2.6` but not sure what is the root-cause of the issue. 

I think `tf.estimator` and `tf.feature_columns` are old style `TF1.x` APIs. In the long run you can use `tf.keras` and `tf.distribute` to update `tf.estimator` based code.

Regarding `feature_columns`, you can use tf.keras `preprocesing` layers. I think these layers provide better functionality and improved performance when compared to `tf.estimator` and `feature_column`.

@rchao Can you please take a look at this issue? Thanks!

**Comment by ttang235** [comment]
@rchao Hi Rick

**Comment by rchao** [comment]
Hello @ttang235, thanks for opening the issue. For a regression like this, running a bisect is usually the easiest way to figure out the culprit.

**Comment by moog-moloco** [comment]
any updates on this issue?

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate from `feature column` to `keras preprocessing`, `feature column` will be deprecated going forward.
For more details refer [Migrate tf.feature_columns to Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns)
Also, refer the list of API's fate under feature column here https://www.tensorflow.org/api_docs/python/tf/feature_column?version=nightly
