### ISSUE TITLE
Apple M1 - TF Master - Build Error: Symbol not found

### ISSUE THREAD

**Issue by 0xA1B2** [tensorflow/tensorflow#51494]
**System information**
- OS Platform: Apple MacBook Pro - M1 - MacOS Monterey 12 Beta 5
- TensorFlow installed from (source or binary): Source
- TensorFlow version: Master
- Python version: 3.9.6
- Bazel version (if compiling from source): 3.7.2 using brew tap bazelbuild/tap

**Describe the problem**

Build string:

bazel build --config=v2 //tensorflow/tools/pip_package:build_pip_package

Build Error:

`WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/sqlite.org/2021/sqlite-amalgamation-3360000.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/XXX/tensorflow/tensorflow/python/BUILD:812:29: Executing genrule //tensorflow/python:spectral_ops_pygenrule failed (Aborted): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_XXX/6fa7ea051f5393a8574f3349fa920010/execroot/org_tensorflow && \
  exec env - \
    PATH=/opt/homebrew/opt/bison/bin:/Users/XXX/miniforge3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin \
    PYTHON_BIN_PATH=/opt/homebrew/opt/python@3.9/bin/python3.9 \
    PYTHON_LIB_PATH=/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash bazel-out/darwin-opt/bin/tensorflow/python/spectral_ops_pygenrule.genrule_script.sh)
Execution platform: @local_execution_config_platform//:platform
dyld[47884]: symbol not found in flat namespace '_ChaCha20_ctr32'`

**Comment by tilakrayal** [comment]
@0xA1B2 ,

Please refer to similar issues #44751,#47782 and for installation please take a look at this [link](https://github.com/apple/tensorflow_macos). It helps.Thanks!
