### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51500]
https://colab.research.google.com/drive/1gfsLuugiqEgAbyj7P6_6trgiNaq1dAW2

I've tried downgrading Pillow to be 8.2.0 and 8.3.1 on my own machine, still not solving the problem,so it may be the tensorflow internal error.

Please teach me how to revise this code and let it run without bugs.

As I just paste the code onto the colab,I have no idea of the tf and python version, please help me check it.

**Comment by collinzrj** [comment]
Can you post the code to reproduce the error? Your Colab notebook is private so others cannot open it.

**Comment by sjtusmartboy** [comment]
@collinzrj Sorry,I didn't realize that, first time to use colab
```
import numpy as np
import tensorflow as tf

import PIL
print(PIL.__version__)


class Foo:
    def __init__(self):
        self.storage = np.zeros((10, 3, 1))

    @staticmethod
    def get_value(): 
        return np.array([[1], [2], [3]])

    @tf.function
    def case1(self):  # works
        self.storage[0] = self.get_value()

    def case2(self):  # works
        self.storage[0] = tf.py_function(self.get_value, inp=[], Tout=tf.float32)

    @tf.function  # fails
    def case3(self):
        self.storage[0] = tf.py_function(self.get_value, inp=[], Tout=tf.float32)


if __name__ == '__main__':
    foo = Foo()
    foo.case1()
    foo.case2()
    foo.case3()

```

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.4,v2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bd4e2927d626c6816f1468536570134a/51500.ipynb).

**Comment by Saduf2019** [comment]
@sjtusmartboy 
Can you refer to [this link](https://stackoverflow.com/questions/23944657/typeerror-method-takes-1-positional-argument-but-2-were-given) with same error and let us know, also[ this link](https://exerror.com/typeerror-array-takes-1-positional-argument-but-2-were-given/) has worked for few users.

**Comment by sjtusmartboy** [comment]
@Saduf2019 I've tried all these methods before posting this issue but none of these solutions worked. I think it's the tensorflow's internal error of combining tf.function and tf.py_function.

**Comment by collinzrj** [comment]
I am tracing the call stack and I found that in `case3`, `tf.function` generates the code as below
```
def outer_factory():

    def inner_factory(ag__):

        def tf__case3(self):
            with ag__.FunctionScope('case3', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
                ag__.ld(self).storage[0] = ag__.converted_call(ag__.ld(tf).py_function, (ag__.ld(self).get_value,), dict(inp=[], Tout=ag__.ld(tf).float32), fscope) ## critical
        return tf__case3
    return inner_factory
```
While in `case1`, it generates the code as this
```
def outer_factory():

    def inner_factory(ag__):

        def tf__case1(self):
            with ag__.FunctionScope('case1', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
                ag__.ld(self).storage[0] = ag__.converted_call(ag__.ld(self).get_value, (), None, fscope) ## critical
        return tf__case1
    return inner_factory
```
The line I marked critical in `case3` produce the problem, while `ag__.converted_call(ag__.ld(tf).py_function, (ag__.ld(self).get_value,), dict(inp=[], Tout=ag__.ld(tf).float32), fscope)` evaluates to `<tf.Tensor 'EagerPyFunc_1:0' shape=<unknown> dtype=float32>` which does not contain value. But in `case1`, `ag__.converted_call(ag__.ld(self).get_value, (), None, fscope)` evaluates to a numpy array, so it proceeds correctly. 
But I did not figure out why and whose the `__array__` is called, any ideas?

**Comment by rainwoodman** [comment]
I got the same error with, so this has little do do with py_function.

```
@tf.function
def case3(self):
     self.storage[0] = tf.constant(32.)
```

I think in this case we are supposed to get an error, because the right hand side is a 'symbolic' tensor (error occurs during `tf.function`'s trace-compilation), and the left hand-side is a numpy container. These two are incompatible, since during trace-compilation we in general do not know the value of the symbolic tensor.

The error message is definitely confusing and looks like a bug. Something like 'cannot convert a symbolic tensor to a numpy array' might be more useful.

**Comment by collinzrj** [comment]
The Error message
```
TypeError: __array__() takes 1 positional argument but 2 were given
```
is thrown by numpy, when we set an item of a numpy ndarray to be an object like `x[0] = y`, the `__array__` method of that object will be called, and a parameter will be passed to it, 
```
import numpy as np
import tensorflow as tf

class Foo:
  def __init__(self):
    self.x = 3

  def __array__(self):
    print(x)
    return np.array([self.x, self.x, self.x])

x = np.zeros((10, 3))
foo = Foo()
x[0] = foo
```
If you run this code, the same error will be thrown

As I mentioned above 

> ag__.converted_call(ag__.ld(tf).py_function, (ag__.ld(self).get_value,), dict(inp=[], Tout=ag__.ld(tf).float32), fscope) evaluates to <tf.Tensor 'EagerPyFunc_1:0' shape=<unknown> dtype=float32>

While the `__array__` method of `<tf.Tensor 'EagerPyFunc_1:0' shape=<unknown> dtype=float32>` is defined as 
```
def __array__(self):
  raise NotImplementedError(
      "Cannot convert a symbolic Tensor ({}) to a numpy array."
      " This error may indicate that you're trying to pass a Tensor to"
      " a NumPy call, which is not supported".format(self.name))
```
I guess the expected behavior is throwing the `NotImplementedError`, but since an extra parameter is passed to `__array__`, an error is thrown before entering the method. This is the direct cause of the error, while I don't know whether `ag__.converted_call(ag__.ld(tf).py_function, (ag__.ld(self).get_value,), dict(inp=[], Tout=ag__.ld(tf).float32), fscope)` evaluates to an empty tensor is an expected behavior.

**Comment by rainwoodman** [comment]
Indeed. A fix has been committed to avoid the extra argument error:

https://github.com/tensorflow/tensorflow/commit/fc0f0e61ca9fe3ca3b9b58f51bcf00e0643ed9e3

**Comment by tilakrayal** [comment]
@sjtusmartboy,
Could you please take a look at this commit where the implementation happened and also the changes are reflected in the respective files.

https://github.com/tensorflow/tensorflow/commit/fc0f0e61ca9fe3ca3b9b58f51bcf00e0643ed9e3 


```python
@def_function.function
    def g():
      # Raises during trace compilation.
      return np.array(constant_op.constant(32))
    with self.assertRaisesRegex(NotImplementedError,
                                "Cannot convert a symbolic Tensor"):
      f()
    with self.assertRaisesRegex(NotImplementedError,
                                "Cannot convert a symbolic Tensor"):
```

Thank you!
