### ISSUE TITLE
Normalization and Quantization of inputs issue

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#51501]
I have observed differences between the documentation and the example.
Reference - https://www.tensorflow.org/lite/convert/metadata#normalization_and_quantization_parameters
![tfliteinputnormalization](https://user-images.githubusercontent.com/47776253/129476236-f3d1dc4e-9202-4cf6-80ff-13d730870d50.JPG)

But in the example, I have found differences.

![Capturefgregtrgtr](https://user-images.githubusercontent.com/47776253/129476310-9b0f1b17-ae54-410a-82ff-2f334546e50a.JPG)

We are not doing normalization when input and output are int8 and uint8? why is that so?

![Capturesssssss](https://user-images.githubusercontent.com/47776253/129476426-ada45a4e-3624-46aa-842e-0868a154cc2b.JPG)

As per documentation, the output does not need normalization? why are we doing this in this example ?

In the example, we are not using any scale and zero point ? we are not using quantization params?

**Comment by lu-wang-g** [comment]
Hi @pranathibl where do the examples come from? Can you please give a pointer?
