### ISSUE TITLE
Can't create multiple instances of tf.keras.Model subclasses

### ISSUE THREAD

**Issue by fm966mhz** [tensorflow/tensorflow#51509]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No.
- TensorFlow installed from (source or binary): pip install.
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0.
- Python version: 3.9.6.
- Bazel version (if compiling from source): NA.
- GCC/Compiler version (if compiling from source): NA.
- CUDA/cuDNN version: NA.
- GPU model and memory: GTX 2080 Ti.

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Here is an example of triggering the issue:
```python
import tensorflow as tf

class MyModel(tf.keras.Model):

  def __init__(self, input_shape):
    super(MyModel, self).__init__()
    self.my_model_input_shape = input_shape
    self.dense1 = tf.keras.layers.Dense(5, activation=tf.nn.relu)
    self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    input_layer = tf.keras.layers.Input(self.my_model_input_shape)
    output_layer = self.call(input_layer)
    super(MyModel, self).__init__(
      inputs=input_layer,
      outputs=output_layer
    )

  def call(self, inputs, training=None):
    x = self.dense1(inputs)
    return self.dense2(x) + x


model_1 = MyModel((10,))
model_1.summary()

model_2 = MyModel((20,))
model_2.summary()
```
It fails at the creation of `model_2` with
```
File ".../lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```

Without the the second 2-param `super().__init__` call at the end of `MyModel.__init__`, it is OK to run, but the summary and `model_1.layers` outputs are different: the one with the second `__init__` call contains more and better information, such as the input and last addition layers and a `Connected to` columns:
```
Model: "my_model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 10)]         0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 5)            55          input_1[0][0]                    
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 5)            30          dense[0][0]                      
__________________________________________________________________________________________________
tf.__operators__.add (TFOpLambd (None, 5)            0           dense_1[0][0]                    
                                                                 dense[0][0]                      
==================================================================================================
Total params: 85
Trainable params: 85
Non-trainable params: 0
```
I would much prefer the one with better information. I learned this from various examples such as https://github.com/matterport/Mask_RCNN/issues/921#issuecomment-432846634.

**Describe the expected behavior**
Creating multiple instances of subclasses should have no issue and the variables and models should be independent from each other.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no.
- Briefly describe your candidate solution(if contributing): NA.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
See above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sanatmpa1** [comment]
@fm966mhz,

This looks like an issue with Keras, can you kindly post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see;[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by fm966mhz** [comment]
@sanatmpa1 

Thanks. I asked this question at keras-team/keras too. Please feel free to close this one for now.

**Comment by sanatmpa1** [comment]
Thanks for the confirmation @fm966mhz
