### ISSUE TITLE
How to get a coarse-grained op-level graph in tensorflow

### ISSUE THREAD

**Issue by JF-D** [tensorflow/tensorflow#51510]
Hi, tensorflow community,
I want to use tensorflow to get the full computation graph (including forward, backward and parameter update). I tried tf.functions, but the graph I got is too fine-grained, as many ops (Adam for example) are splited into smaller operators (add, mul, div etc.). So is there any methods that I can get a coarse-grained op-level graph? Thanks a lot!

Jiangfei

**Comment by tilakrayal** [comment]
@JF-D ,
Kindly open a tf discussion [forum](https://discuss.tensorflow.org/) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.Thanks!

**Comment by JF-D** [comment]
Ok. Thanks!
