### ISSUE TITLE
Tensorflow 2.4: where is tf.contrib.layers.fully_connected?

### ISSUE THREAD

**Issue by zhr-ar** [tensorflow/tensorflow#51515]
How can I replace tf.contrib.layers.fully_connected of tensorflow 1.x with a similar function in 2.4?

Got the following error:
    import tensorflow.contrib.layers as layers
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by tilakrayal** [comment]
@zhr-ar ,

Kindly open a tf [discussion forum](https://discuss.tensorflow.org/) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.

**Comment by tilakrayal** [comment]
@zhr-ar ,

Please refer the issues #36878, #35197, #30794, #37720 with similar error log.It helps.

Thanks

**Comment by mihaimaruseac** [comment]
There is no contrib in TF 2.x.
