### ISSUE TITLE
Time Series Documentation Doesn't Display on Chrome

### ISSUE THREAD

**Issue by spencerconnor** [tensorflow/tensorflow#51517]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/structured_data/time_series#the_weather_dataset

## Description of issue (what needs changing):

In Chrome, the weather dataset table only shows a portion of the table.

ALSO, I have been struggling to learn from this documentation. It would be MUCH easier to learn if there were at least one complete script (preferably one per section) in a single code block. For example. It would be much easier to understand if I could see a code block that had everything needed to train and test a Single-Step and Multi-Step model

Also Also, it would help if all the variable's names were consistent with the diagrams and their purpose was described in text i.e.
 [https://www.tensorflow.org/tutorials/structured_data/time_series#multi-step_dense](CONV_WIDTH) is not described and it's purpose can only be guessed at from the diagram.

### Request visuals, if applicable
<img width="951" alt="ZR61xt1sYW" src="https://user-images.githubusercontent.com/52757442/129586646-f7ae0920-2dfd-4f91-8ab8-26db833d1371.png">

**Comment by ymodak** [comment]
I see all 5 rows of the dataset as shown in the left image above. I am using chrome Version 92.0.4515.131 (Official Build) (x86_64)
Perhaps you may want to check for browser updates. Also which browser are you using to display the left image above?

**Comment by sanatmpa1** [comment]
@spencerconnor,

As mentioned by @ymodak , even I am able to see all the 5 rows as usual and I am using chrome `Version 92.0.4515.130 (Official Build) (64-bit)`. Attached the image below for your reference. 

You can take a look at this [ipynb](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/time_series.ipynb) which consolidates all the code blocks in one notebook as you requested. Let me know if it helps. Thanks!

![image](https://user-images.githubusercontent.com/87846724/129667753-1ac8d554-5dbc-4825-b46e-98f8bee129ec.png)

**Comment by spencerconnor** [comment]
So the previous image was Firefox and Chrome respectively. This one is Chrome (Incognito) and Chrome (normal). Extensions are disabled. 
<img width="960" alt="chrome_4KNNRJ8Lb7" src="https://user-images.githubusercontent.com/52757442/129725410-27f14a04-fb79-4b4c-b7ad-b7c8ab978828.png">


 It worked for a moment in a normal Chrome window, but now it's back to the partial view.

<img width="960" alt="kGBqPApc5x" src="https://user-images.githubusercontent.com/52757442/129725064-7e34b999-1524-4207-9f27-66b398857694.png">

 I noticed that when loading in the incognito window, the table briefly appears in a partial view before expanding immediately to the full size.

After some testing (changing DNS, removing/refreshing cookies, reloading page and window) it looks like it is an issue with the cookies. It seems like it happens when Google Analytics is opted out of or blocked.

**Comment by spencerconnor** [comment]
This is one of two cookies that are different between working and non-working. (Incognito - Normal)

<img width="960" alt="3c8b46SwsX" src="https://user-images.githubusercontent.com/52757442/129729912-ec3b4f42-8316-493e-9e12-9a1b93cb91e7.png">

**Comment by sanatmpa1** [comment]
@spencerconnor,

Thanks for the information that its not an issue from TF end and mostly related to cookies. Also I've added link for ipynb in my previous comment, which consolidated all codes into one as you requested. Please confirm if we are good to close this issue. Thanks!

**Comment by spencerconnor** [comment]
Thanks for the help :)
