### ISSUE TITLE
Question about custom convolution layer

### ISSUE THREAD

**Issue by ntyoshi** [tensorflow/tensorflow#51519]
Hi,

**Question**
Is it possible to make a custom convolution layer by scratch?
Can you tell me how to do it?

**What I'm thinking**
I am thinking to create a custom convolution layer that works like tf.keras.layers.Conv2D.
I still don't have codes but it will work like FIR filter.
Basic FIR filter could be implemented by Conv2D or Conv1D but the layer I want can't be, because it'll has some process that Conv2D and Conv1D don't have.
 
If I try to implement by tf.keras.layers.Layer, I need to have some for-loops or while-loops. 
And the loops will make the computation slow and consume a lot of GPU memory.

**Comment by tilakrayal** [comment]
@ntyoshi ,

Can you please take a look at this links for information on custome convolution layer.[Link1](https://towardsdatascience.com/custom-neural-networks-in-keras-a-street-fighters-guide-to-build-a-graphcnn-e91f6b05f12e),[Link2](https://medium.com/analytics-vidhya/creating-a-custom-convolutional-neural-network-in-tensor-flow-a9b29ae9fcf9),[Link3](https://keras.io/api/layers/convolution_layers/).It helps.Thanks
