### ISSUE TITLE
I want to know Is it supported that the C_API can use the Core ML delegate? 

### ISSUE THREAD

**Issue by xunbing** [tensorflow/tensorflow#51512]
**System information**
- MacOS11.2 Compile the C_API for IOS 12

**Describe the problem**
I want to know Is it supported that the C_API can use the Core ML delegate? 
What I can learn about the Doc is CoreML only compiled as Framework not a static library. Now I have a project used the tf-lite with C API, And.I want to know whether it can use the CoreML delegate with C API . So that I don't need change the export way (just give a dynamic library out) to the caller .

**Comment by yyoon** [comment]
Hi @xunbing. Yes, this is supported. Please see the example code at https://www.tensorflow.org/lite/performance/coreml_delegate#c-until-2.3.0.

**Comment by xunbing** [comment]
> Hi @xunbing. Yes, this is supported. Please see the example code at https://www.tensorflow.org/lite/performance/coreml_delegate#c-until-2.3.0.

 Thank you for your reply！I 've seen this example code. But I cannot find the Interface about CoreMLDelegate in c_api.cc. So I guess is CoreML Delegate cc_libarry not supported for now?  If I want to use the Core ML Delegate  like this code example , Do I have to link the framework build separately with bazel instead of a c static library ? Becuase In my case, I really need a C static library linked to my present final library. Looking forward to your reply！

**Comment by yyoon** [comment]
So, you mean the compiled CoreML delegate implementation is not included in your TFLite C static library, correct?

Can you tell me more details about how you are building the TFLite C static library for your project?
I might be able to help with adding the CoreML delegate code into the static library.

**Comment by xunbing** [comment]
> So, you mean the compiled CoreML delegate implementation is not included in your TFLite C static library, correct?
> 
> Can you tell me more details about how you are building the TFLite C static library for your project?
> I might be able to help with adding the CoreML delegate code into the static library.

First I use 'bazel build -c opt --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteC_static_framework' command to get the TensorFlowLiteC, which is Mach-O consist of 4 architectures.

Second I use 'lipo TensorFlowLiteC -thin arm64 -output arm64.a' to get the arm64 arch: current at archive.

And then use 'ar -x arm64.a' to get all the .o files.

At last use 'ld -r *.o -o libTensorflowLiteC.a' .

Now I have a project named A.dylib which linked to a APP.  I linked the  libTensorflowLiteC.a to the A.dylib. So in this App I can do some inference work with tf-lite now.  Further I want to use the Core ML to accelerate the inference. But I 've not found a way to compile a static library to link to my current project.

Can you tell me what should i do？It will be a great help for me.

**Comment by yyoon** [comment]
I see. You'll need to modify the `tensorflow/lite/ios/BUILD` file on your side to make it work.
In the `TensorFlowLiteC_static_framework` rule in this file, add the followings:
1) Add `":coreml_delegate.h"` under `hdrs`.
2) Add `"//third_party/tensorflow/lite/delegates/coreml:coreml_delegate"` under `deps`.

The resulting rule would look like:

```
# Similar to TensorFlowLiteC_framework but this is a static framework and symbol
# hiding is not applied. Note both have the same bundle name.
ios_static_framework(
    name = "TensorFlowLiteC_static_framework",
    hdrs = [
        ":builtin_ops.h",
        ":c_api.h",
        ":c_api_experimental.h",
        ":common.h",
        ":coreml_delegate.h",
        ":xnnpack_delegate.h",
        "//third_party/tensorflow/lite/c:c_api_types.h",
    ],
    bundle_name = "TensorFlowLiteC",
    minimum_os_version = TFL_MINIMUM_OS_VERSION,
    deps = [
        ":tensorflow_lite_c",
        "//third_party/tensorflow/lite/delegates/coreml:coreml_delegate",
    ],
)
```

After this, run your bazel build again and extract the `.a` file for arm64 platform as you did before.
Let me know if this works for you.

**Comment by xunbing** [comment]
Thanks!  I modified the ios/BUILD like you said. There is a ERROR: 'missing input file '//tensorflow/lite/delegates/coreml:coreml_delegate.mm'.

Complete error message is:

> xunbinggao@DARYLGAO-MB0 tensorflow-master % bazel build --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteC_static_framework --verbose_failures
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=111
INFO: Reading rc options for 'build' from /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /Users/xunbinggao/darylgao/2.task/tensorflow-master/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/local/opt/python@3.9/bin/python3.9 --action_env PYTHON_LIB_PATH=/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages --python_path=/usr/local/opt/python@3.9/bin/python3.9
INFO: Found applicable config definition build:short_logs in file /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:ios_fat in file /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc: --config=ios --ios_multi_cpus=armv7,arm64,i386,x86_64
INFO: Found applicable config definition build:ios in file /Users/xunbinggao/darylgao/2.task/tensorflow-master/.bazelrc: --apple_platform_type=ios --apple_bitcode=embedded --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
INFO: Build options --cpu and --ios_multi_cpus have changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/lite/ios:TensorFlowLiteC_static_framework (0 packages loaded, 9952 targets configured).
INFO: Found 1 target...
ERROR: /Users/xunbinggao/darylgao/2.task/tensorflow-master/tensorflow/lite/delegates/coreml/BUILD:105:13: //tensorflow/lite/delegates/coreml:coreml_delegate_kernel: missing input file '//tensorflow/lite/delegates/coreml:coreml_delegate_kernel.mm'
Target //tensorflow/lite/ios:TensorFlowLiteC_static_framework failed to build
ERROR: /Users/xunbinggao/darylgao/2.task/tensorflow-master/tensorflow/lite/delegates/coreml/BUILD:105:13 1 input file(s) do not exist
INFO: Elapsed time: 1.600s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

I noticed there is no cc_library called in the ios/delegates/coreml/BUILD.  Is the reason about this ERROR?
Looking forward your reply. I feel I found some hope!

**Comment by yyoon** [comment]
Sorry, I had some mistakes in my earlier reply. The dependency should be `"//tensorflow/lite/delegates/coreml:coreml_delegate",` with out the `third_party/` portion.

Looking at your error logs, I guess you've figured this out already though.

Can you navigate to the `tensorflow/lite/delegates/coreml` directory and see if `coreml_delegate_kernel.mm` file actually exists? I'll try the same build on my side and see if it works.

**Comment by yyoon** [comment]
FYI, the build was successful on my side, so it ideally should work for you assuming your configuration is correct.

**Comment by xunbing** [comment]
Yeah. That "third_party" caused some confuse indeed. Just like you say, I figured this out.
After I checked my directory, I noticed I make a ridiculous mistake. I modify the .mm to .cc because of Ignorance of the relationship between C and OC.

It's worked!

Thank you very much! And through this experience, I feel the charm of the community.

**Comment by yyoon** [comment]
Great to hear that it worked for you!

**Comment by xunbing** [comment]
Emm... May I ask something more? I'm still a little confused.
Now I've prepared the static library like we talked above.
When I compile the whole project, there is some ERROR message like this:

>[100%] Linking CXX shared library libA.dylib
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MLFeatureValue", referenced from:
      objc-class-ref in libTensorFLowLiteC_CoreML.a
  "_OBJC_CLASS_$_MLModel", referenced from:
      objc-class-ref in libTensorFLowLiteC_CoreML.a
  "_OBJC_CLASS_$_MLModelConfiguration", referenced from:
      objc-class-ref in libTensorFLowLiteC_CoreML.a
  "_OBJC_CLASS_$_MLMultiArray", referenced from:
      objc-class-ref in libTensorFLowLiteC_CoreML.a
  "_OBJC_CLASS_$_MLPredictionOptions", referenced from:
      objc-class-ref in libTensorFLowLiteC_CoreML.a
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So I have to doubt whether Using CoreML delegate with C static library is correct. Is the only way that Linking the whole framework in xcode prj ?

**Comment by xunbing** [comment]
I use 'nm TensorFlowLite | grep MLModelConfiguration', found the front flag is 'U' .
like this:
> U _OBJC_CLASS_$_MLFeatureValue
U _OBJC_CLASS_$_MLModel
U _OBJC_CLASS_$_MLModelConfiguration
U _OBJC_CLASS_$_MLMultiArray
U _OBJC_CLASS_$_MLPredictionOptions
U _OBJC_CLASS_$_NSArray
U _OBJC_CLASS_$_NSFileManager
U _OBJC_CLASS_$_NSMutableArray
U _OBJC_CLASS_$_NSNumber
U _OBJC_CLASS_$_NSObject
U _OBJC_CLASS_$_NSProcessInfo
U _OBJC_CLASS_$_NSSet
U _OBJC_CLASS_$_NSString
U _OBJC_CLASS_$_NSURL
U _OBJC_METACLASS_$_NSObject

To find out the relationship between the two Framework and my compiled static library, I check the CoreMLFramework with bazel with same way. The result is also 'U' undefined.

And finally , I found these symbols belongs to iPhoneOS.sdk's CoreML.framework Headers. 

I'm not sure what should i do to solve these ERRORs.

**Comment by yyoon** [comment]
Hi @xunbing,

Sounds like you are missing the CoreML.framework in your project setting. In Xcode, try navigating to the project settings -> General -> Frameworks, Libraries, and Embedded Content -> Add `Coreml.framework` under iOS.

![image](https://user-images.githubusercontent.com/1309817/129812998-b5017455-6b00-417e-864e-9ef9c02a74b7.png)

**Comment by xunbing** [comment]
@yyoon thx for your reply!
This is also what puzzles me. I learned Adding Coreml.framework is necessary by reading the examples code. 
But maybe my situation is special. I want to compile all of symbols to a final C static library and **call the interface in this library.** So I can just use the tf-lite(TfLiteCoreMlDelegateCreate) c_api  in the final static library without adding the Coreml.framework in Xcode prj.

After all, my role is the backend developer. The simpler my product, things will be better.

Can CoreML Delegate be used like this? Or its interface must be used in a  xcode.prj?

**Comment by yyoon** [comment]
> **call the interface in this library.**

Call the interface from what? I assume your static library will be called from an iOS app anyways, and you would have to use an Xcode project for it.

Coreml.framework is part of the iOS, and I don't think it's possible to statically link it to your own library.

**Comment by xunbing** [comment]
For example, now I encapsulate the interface in lite/c/c_api.h to my custom interface. So somewhere in my final static library, customer interface will be called to do some inference work. Just output custom result like labels to iOS fore-end.

**Comment by xunbing** [comment]
I am beginning to understand. What I pursue is that there is only one curtom interface to iOS fore-end to do some ml interface work. Like give me a picture, I give the labels out. So pure C library compiled with tensorflow/lite/c/ can cover this case. But if I  want use the CoreML delegate further, the solution just now is not work anymore. Maybe I should split the custom interface to several parts. Let iOS fore-end call the tf-lite inference interface. I do some preprocess and postprecess work.

Am I right?

**Comment by yyoon** [comment]
You can still have a single interface to include coreml delegate feature as well.

It's just that users of your static library (app developers) still need to manually add the coreml.framework as a dependency in their Xcode projects for their apps. This part is inevitable, and even if you split your C API, users still need to add the Coreml.framework dependency in their app.

**Comment by xunbing** [comment]
I get it. The Coreml.framework is a part of iOS. I can not compile it into my final C static library. For Objective-C code, it's supported using the C API. My mistake is that **I want to use the C API about coreml delegate feature in a library compiled with pure C code.** So it appeared errors above:
> U OBJC_CLASS$_MLFeatureValue

Now I figure it out.

1. For the pure C code product , by using 'ar -x' to extact all the obj files, there will have not weak symbols like OBJC_CLASS about Objective-C. It can used in C code to do some inference work without CoreML delegate feature. Even not in iOS, it can be cross platform easily.
2. For the xcode prj, If I want use the CoreML delegate in my app. I cant use the C API or Objective-C API by linking the CoreML.framework  in Objective-C code.
