### ISSUE TITLE
Links lead to 404 on food101 dataset page 

### ISSUE THREAD

**Issue by shashwat9kumar** [tensorflow/tensorflow#51514]
## Whats Wrong?
The link of Homepage of Food101 on the Food101 page of the catalog section of tensorflow datasets doesnt work.
Link of the page: https://www.tensorflow.org/datasets/catalog/food101

### Description

The link given for the Homepage of the Food-101 doesn't work
![image](https://user-images.githubusercontent.com/43718923/129578159-57c489d4-b98b-47bc-930c-c993ee2a9999.png)

It leads to a 404 Page not found
![image](https://user-images.githubusercontent.com/43718923/129578246-4b2680d0-d519-4885-8135-edc51133f202.png)

### Correct links

Link to the correct paper: https://data.vision.ee.ethz.ch/cvl/datasets_extra/food-101/

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by sanatmpa1** [comment]
@shashwat9kumar 

Thanks for pointing it out and the correct link for food 101 dataset is https://data.vision.ee.ethz.ch/cvl/datasets_extra/food-101/

I can see that you have already submitted a PR for the same. Thanks!

**Comment by ymodak** [comment]
This is fixed with https://github.com/tensorflow/datasets/commit/5d1d3c9ec95f8bf6c7d1a73befbd3e8b4458363d#diff-e36263420b0922ac75692057d52dd1a3bcfe57bafaeed330caffba97c16bdadc Thanks!
