### ISSUE TITLE
How to fuse tensors of two different dimensions?

### ISSUE THREAD

**Issue by 1148330040** [tensorflow/tensorflow#51523]
env：tf2.2

I have two sets of tensors. I want them to merge together as a new input. Which method should I use?

tensor 1：from bert-encoder-hidden: (batch_size, max_len, 768)
tensor 2:   from tensor 1 through tf.Gather(tensor1, position, batch_dim=1): (batch_size, 768)

Tensor 2 is the position tensor extracted from tensor 1 through TF. Gather() method. Now I want to integrate tensor 2 into tensor 1. What should I do?

**Comment by sanatmpa1** [comment]
@1148330040,

Can you explain your question clearly with a sample data? If you're looking to update the values in tensor based on indices, you can checkout this function `scatter_nd_update`, [link](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update). Thanks!

**Comment by 1148330040** [comment]
Sorry, this is an **information extraction** task. **Tensor 1** is the encoder coded output **hidden of Bert** model. I first obtain the **subject** prediction output from **tensor 1** through CRF, and then extract the corresponding tensor 2 (TF. Gather) from **tensor 1** through the obtained **subject location information.** Then I want to integrate **tensor 2** into **tensor 1** as the input of **prediction object**

**Comment by 1148330040** [comment]
The key is fusion, not renewal，It is equivalent to an alternative weighting, but here tensor2 is weighted to tensor1

**Comment by Saduf2019** [comment]
@1148330040 
PLease refer to these similar links : [link](https://stackoverflow.com/questions/49294326/expanding-a-tensor-by-another-one-with-different-dimensions-in-tensorflow), [link1](https://developpaper.com/question/how-do-tensors-of-different-dimensions-of-tensorflow-merge/),[link2](https://jovian.ai/aiwithsreekanthrshekar/merging-tensors-5-functions-you-should-be-aware-of)

You may open an issue in tf discussion forum as its a bigger community to support, kindly move this to closed status as its not a bug or performance issue.

**Comment by 1148330040** [comment]
1
