### ISSUE TITLE
CUDA information inconsistent in PyPI (and missing in release notes)

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#51526]
@jvishnuvardhan, #43712 is not solved, unfortunately: it is still hard to find out which CUDA version has been used to build TensorFlow pip packages.

- Good: v2.5 release notes list "CUDA11.2 and cuDNN 8.1.0":
https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0

- Bad: v2.6 release notes don't mention any CUDA/CuDNN information at all:
https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0

One might assume that v2.6 uses the same CUDA 11.2 as v2.5 if release notes don't report any change. (Still, it would be hard to find that information a few releases from now.)

PyPI might be a good source for this type of information. However:

- While PyPI lists "GPU :: NVIDIA CUDA :: 11.2" for `tf-nightly`, it lists "GPU :: NVIDIA CUDA :: 11.0" for `tensorflow` v2.6 (and v2.5):
https://pypi.org/project/tf-nightly/2.7.0.dev20210815/
https://pypi.org/project/tensorflow/2.6.0/

**Comment by jvishnuvardhan** [comment]
Agree with you that the info is inconsistent. best place to look at is TF webpage https://www.tensorflow.org/install/source_windows#gpu . You can see tested build configuration for most of the released branches. 

You can also check here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py for dependencies.  

@mihaimaruseac Please take a look at this issue. Thanks!

**Comment by bersbersbers** [comment]
@jvishnuvardhan thanks, these links are very helpful. From these, I can also see that the issue has been introduced in April (https://github.com/tensorflow/tensorflow/commit/68e6c8da5a56b4895114ec47fc6aeccb8027de88) and fixed some 10 days ago (https://github.com/tensorflow/tensorflow/commit/3daf758918c40c00560101b2395ffa96e8fea656), at least for 2.7.0 onwards. 

Not sure if past PyPI packages can be fixed.

**Comment by mihaimaruseac** [comment]
Sadly, they cannot.

We attempted to fix this on PyPI a few months ago but the tag was not available so packages would not be able to be uploaded.

**Comment by SuryanarayanaY** [comment]
Hi @bersbersbers ,

We have verified with new releases and the CUDA information found Ok.Please refer to [tf-nightly](https://pypi.org/project/tf-nightly/) and [TF2.11v](https://pypi.org/project/tensorflow/) which is up to date.

As mentioned in above [comment-900421820](https://github.com/tensorflow/tensorflow/issues/51526#issuecomment-900421820), unfortunately it is not possible earlier versions (2.6v or 2.5v) due to Tag related issues and also they are quiet outdated now. As latest versions are up to date shall we move this issue to closed. Thanks!

**Comment by SuryanarayanaY** [comment]
@bersbersbers ,

Thanks for coming back.Are we good to close this issue now. Please feel free to close the issue. Thanks!

**Comment by bersbersbers** [comment]
I guess so. It's still not in the release notes, but if PyPI is correct, that shall be good enough for me.

**Comment by SuryanarayanaY** [comment]
@bersbersbers ,
Release notes not really exhaustive and it mainly focuses on breaking changes,Bugs and New features.The main source is documentation which is up to date and PyPi is also up to date. I think we are good to close this.Awaiting your confirmation

**Comment by bersbersbers** [comment]
Sorry, I meant to close with the previous comment already!
