### ISSUE TITLE
make_early_stopping_hook will always return _MultiWorkerEarlyStoppingHook, no matter what strategy is used

### ISSUE THREAD

**Issue by FelixHo** [tensorflow/tensorflow#51525]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): v2.2 ~ v2.6
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

make_early_stopping_hook will always return _MultiWorkerEarlyStoppingHook, no matter what strategy is used.( since TF2.2)

There is a bug in this line of code(early_stopping.py#L86), because the second condition is an array with two elements, which must be True, which means that this IF judgment is always True, so it will always return _MultiWorkerEarlyStoppingHook
``` python
train_distribute = estimator.config.train_distribute
mwms = ['CollectiveAllReduceStrategy', 'MultiWorkerMirroredStrategy']
if train_distribute and (train_distribute.__class__.__name__.startswith(
    strategy) for strategy in mwms): # <--- bug here. [False, False] will be considered TRUE.
  if run_every_secs:
    raise ValueError('run_every_secs should not be set when using '
                     'MultiWorkerMirroredStrategy.')
  return _MultiWorkerEarlyStoppingHook(should_stop_fn, run_every_steps)

if estimator.config.is_chief:
  return _StopOnPredicateHook(should_stop_fn, run_every_secs, run_every_steps)
else:
  return _CheckForStoppingHook()
```

https://github.com/tensorflow/estimator/blob/r2.6/tensorflow_estimator/python/estimator/early_stopping.py#L86

**Describe the expected behavior**

make_early_stopping_hook should return the correct hook according to the strategy

**Comment by mohantym** [comment]
In order to expedite the trouble-shooting process, please provide a  sample code snippet to reproduce the issue reported here. Thanks!

**Comment by Fanoid** [comment]
When train_distribute  is MirroredStrategy, 
```
(train_distribute.__class__.__name__.startswith(
    strategy) for strategy in mwms)
```
returns `True`, which should be unexpected.
