### ISSUE TITLE
cmake build doesn't work for debug build

### ISSUE THREAD

**Issue by cg31** [tensorflow/tensorflow#5152]
On Windows, cmake build work fine for release build.

But for debug build, some projects are still using Release settings, for example:

protobuf\src\protobuf\Release\protoc.exe is used, should be protobuf\src\protobuf\Debug\protoc.exe
zlib.lib is used, should be zlibd.lib

**Comment by asimshankar** [comment]
Thanks for the report @cg31 
I'm not sure whether the intention with the Debug build is to use the debug build of external dependencies as well, or restrict the  debug build to apply to TensorFlow code.

@mrry will have more insight.

**Comment by cg31** [comment]
Hi, thanks for reponse.

Looks like the tool/lib being used in build are specified by the option to invokde cmake, -DCMAKE_BUILD_TYPE=Release or -DCMAKE_BUILD_TYPE=Debug.

When -DCMAKE_BUILD_TYPE=Release (or Debug) is used, the generated projects can only used to build that type. Ideally, the projects should be able to build both Debug and Release build.

**Comment by cg31** [comment]
OK, the readme states clearly that Debug type is not supportly not.

This is not an issue. I am going to close this.

**Comment by mrry** [comment]
Just to follow up on this, as you realized there's no current support for Debug builds using TensorFlow-on-Windows, and the recommended workaround is to use RelWithDebInfo, so that you can use the VS debugger etc.

If anybody wanted to contribute support for the Debug build, that'd be great!
