### ISSUE TITLE
skflow: DNNClassifier fit has no logdir Parameter

### ISSUE THREAD

**Issue by codingyourlife** [tensorflow/tensorflow#5153]
I'm missing the logdir parameter on DNNClassifier  fit. This is either a bug or a changed behaviour that I don't get (sorry if this should be on stackoverflow, I'm not sure)

TensorFlowDNNClassifier tells me it's depracted and I should use DNNClassifier:
![tensorflowdnnclassifier](https://cloud.githubusercontent.com/assets/10122382/19629647/835ef85c-9979-11e6-9966-0aeedb8107bc.png)

But when I use DNNClassifier the classifier.fit() Method loses it's logdir parameter (I use for tensorboard):
![logdir](https://cloud.githubusercontent.com/assets/10122382/19629870/60dd7ba0-997e-11e6-8071-5c5f1c1ee81c.PNG)

The behaviour slightly changes in general like now max_steps behaves like steps previously did and steps or no parameter about steps trains very long/forever.

**Comment by terrytangyuan** [comment]
Use `model_dir`. Yes that is the right change in behavior.

**Comment by asimshankar** [comment]
@codingyourlife : Just to add a little more detail - `model_dir` is a constructor parameter to to [DNNClassifier](https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.learn.html#DNNClassifier).

Hope that helps. I'm going to close this issue as it seems you have an answer. But in case you run into trouble, please feel free to reopen. Thanks!
