### ISSUE TITLE
tf.print() mixes up the keys and values in a nested dictionary, leading to incorrect representation of the object content

### ISSUE THREAD

**Issue by Andreas5739738** [tensorflow/tensorflow#51532]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): pip binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7.11
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

tf.print mixes up the order of dictionary keys and values when printing a dict which is nested inside a namedtuple. See example below, tf.print claims that the key 'a' has the value 2, when in fact it has the value 1.

**Describe the expected behavior**

tf.print represents the content of the object correctly.

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/Andreas5739738/d8abda0605692c3a37c28ba94da510d6/notebook.ipynb
```
import tensorflow as tf
from collections import namedtuple

# create a dict inside a namedtuple
X = namedtuple('X', ['x', 'y'])
data = X(x=tf.constant([0]), y={'b': tf.constant([2]), 'a': tf.constant([1])})

dataset = tf.data.Dataset.from_tensor_slices(data)
output_item = list(dataset)[0]

print(f'Actual tensor content:\n{output_item}\n')

print('tf.print mixes up the order of the keys and values in the dict:')
tf.print(output_item)
```
Output:
```
Actual tensor content:
X(x=<tf.Tensor: shape=(), dtype=int32, numpy=0>, y={'b': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>})

tf.print mixes up the order of the keys and values in the dict:
X(x=0, y={'b': 1, 'a': 2})
```

**Comment by Aditya-Komaravolu** [comment]
_@Andreas5739738_ I am not pretty sure what it is exactly but I could find out that `tf.print` kernels do get into an issue when we define tensors inside nested python sets. 

_Do you have any inputs from your end?_

Here's the link: [Exceptions](https://github.com/tensorflow/community/blob/master/rfcs/20180824-tf-print-v2.md#supported-input-types)

Specifically these points :
![image](https://user-images.githubusercontent.com/64011471/129771214-f9c8992d-3d31-46e0-8410-8c229cb052ff.png)

**Comment by Andreas5739738** [comment]
The nested structure I am using (namedtuple and dict) seems well supported by tf.nest otherwise, at least I haven't observed any problems anywhere in my data pipeline so far. tf.print seems to be the only operator that has issues with this setup.

**Comment by mohantym** [comment]
Hi! @Andreas5739738 ! I followed  [tf.dataset ](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#as_numpy_iterator)documentation , replaced` output_item = list(dataset)[0] ` with` output_item = list(dataset.as_numpy_iterator())[0]`and was able to replicate and resolve this issue in 2.6. please find the [gist ](https://colab.research.google.com/gist/mohantym/f5d044e710da26e6da6191c83dbd4863/notebook.ipynb#scrollTo=xWKC7vEbKIQz)for reference. Thanks!

**Comment by Andreas5739738** [comment]
Hi, I don't think as_numpy_iterator this is a viable workaround, since it will not work in graph mode, for example.

**Comment by mohantym** [comment]
Hi!@Andreas5739738 , Could you please try the fix and update whether fix is working or not in graph mode?

**Comment by Andreas5739738** [comment]
Hi, tf.print is the only option I know of that can print output in graph mode. Neither `print()` nor `tensor.to_numpy()` are available in graph mode. So this is not a workaround that can be used in graph mode.

**Comment by mohantym** [comment]
Hi! @sanatmpa1 ,Could you please look into this issue , providing [gist](https://colab.research.google.com/gist/mohantym/f5d044e710da26e6da6191c83dbd4863/notebook.ipynb#scrollTo=xWKC7vEbKIQz) for reference.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
