### ISSUE TITLE
metric_learning的损失函数如何应用在检索中，目前实现中都存在传labels给到度量损失函数

### ISSUE THREAD

**Issue by frostjsy** [tensorflow/tensorflow#51546]
https://github.com/tensorflow/tensorflow/blob/r1.10/tensorflow/contrib/losses/python/metric_learning/metric_loss_ops_test.py

**Comment by mohantym** [comment]
Hi!@frostjsy!We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks
