### ISSUE TITLE
Unknown git option: -C

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#5154]
I'm trying to compile the latest TensorFlow, but I'm getting a `git` error:

    $ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
    INFO: Loading package: @local_config_xcode//
    INFO: Found 1 target...
    INFO: From Executing genrule //tensorflow/core:version_info_gen:
    Unknown option: -C
    usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
               [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
               [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
               [-c name=value] [--help]
               <command> [<args>]
    ! 

It looks like the `git -C` option is used, but that is only supported in git version >= 1.8.

It looks like it's not worth requiring git 1.8 just for this?

**Comment by asimshankar** [comment]
@markusdr : Thanks for the note.
We welcome contributions to make this work with git < 1.8 (you probably have to change things in [gen_git_source.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/git/gen_git_source.py#L150). Feel free to submit a Pull Request.

However, given than git 1.8 is over 4 years old, it may be hard to predict other issues that might arise with using very old versions of git. If you consider it particularly important to work with such old versions of git, I'd be curious to hear your thoughts.

**Comment by drpngx** [comment]
Please watch PR #4580.

**Comment by drpngx** [comment]
Submitted. Woohoo!
