### ISSUE TITLE
TFlite GPU Delegate Use input and output ssbo at the same time,the result is error.

### ISSUE THREAD

**Issue by yangchengtest** [tensorflow/tensorflow#51545]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): android ndk 21c
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.15
- Device: qcom snapdragon 855

My code step:
imread -> texture -> ssbo1 ->tflite ->ssbo2
I test ssbo1,the input ssbo1 is ok.
```
 glActiveTexture(GL_TEXTURE0);
  glBindTexture(GL_TEXTURE_2D, uInput);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 256, 256, 0, GL_RGB, GL_FLOAT, data);

  glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, input_buffer);
  glUniform1i(2, 256);
  glUniform1i(3, 256);
  glDispatchCompute(32, 32, 1);
  glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT);
  auto outData = glMapBufferRange(GL_SHADER_STORAGE_BUFFER, 0, 256*256*12, GL_MAP_READ_BIT);
```

ssbo2 return error.
`coef 0,1,2,3:0.59072,0.842416,0.85824,0.454508`

When I don't use input ssbo:
imread ->tflite ->ssbo
the result is OK.
`coef 0,1,2,3:0.198929,0.524968,0.660745,0.634005`

Can I bind input and output ssbo at the same time?
Here is my c++ code.
```
  TfLiteDelegate* gpuDelegate = TfLiteGpuDelegateCreate(&options);
  std::cout<<"set output buffer handle"<<std::endl;
  interpreter->SetAllowBufferHandleOutput(true);
  // The buffer must be bound before the delegate is installed.
  std::cout<<"set tensor bind"<<std::endl;
  //just like bindBufferBase?
  TfLiteGpuDelegateBindBufferToTensor(gpuDelegate,input_buffer,interpreter->inputs()[0]);
  TfLiteGpuDelegateBindBufferToTensor(gpuDelegate,output_buffer,interpreter->outputs()[0]);
  std::cout<<"modify delegate"<<std::endl;
  if(interpreter->ModifyGraphWithDelegate(gpuDelegate) != kTfLiteOk){
    return;
  }

glUniform1i(2, 256);
glUniform1i(3, 256);
//texture to ssbo 
glBindBufferBase(GL_SHADER_STORAGE_BUFFER, 0, input_buffer);
glDispatchCompute(32, 32, 1);

glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT);
 // Run inference; the null input argument indicates use of the bound buffer for input.
 if (interpreter->Invoke() != kTfLiteOk) return;
 glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT);
```
It seems like the input_buffer ssbo data is not put into the tflite model,how can I use it?
Thanks!

**Comment by sushreebarsa** [comment]
@yangchengtest We see that you are using older version of tensorflow 1.15 which is not actively supported, We recommend that you upgrade to 2.6.0 the latest version of TF and let us know if the issue still persists in newer versions.Thanks!

**Comment by yangchengtest** [comment]
> @yangchengtest We see that you are using older version of tensorflow 1.15 which is not actively supported, We recommend that you upgrade to 2.6.0 the latest version of TF and let us know if the issue still persists in newer versions.Thanks!

I don't have tf 2.6 models.In my project, the original model is trained by pytorch, use my own tools change to tensorflow model.
My Input is not huge, I think I will use cpu input first to solve the problem.

**Comment by ymodak** [comment]
TF 1.X out of the support window. You may try posting this question on [TensorFlow Forum](https://discuss.tensorflow.org/) for community support. Thanks!
