### ISSUE TITLE
 how to get the middle layer of tflite model with c++ API

### ISSUE THREAD

**Issue by likefxz2009** [tensorflow/tensorflow#51548]
I want to know how to get the middle layer of tflite model with c++ API
i find some information in https://github.com/tensorflow/tensorflow/issues/49129, but it present with python
then I use the PreserveAllTensorsExperimental() of interpreterbuilder and interpreter->tensor() to extract middle layer tensor, but the tensor which i got is null, so how to do this correct with c++ API ?

**Comment by mohantym** [comment]
Hi @likefxz2009 ! Work around is to visualize the model architecture through[ netron ](https://netron.app/)web app and use [get_tensor_details()](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#get_tensor_details) ( use experimental_preserve_all_tensors=True in interpreter while loading the TFlite model)  to extract the desired tensor with index value.
