### ISSUE TITLE
What architecture do block3 and stack3 from tf.python.keras.applications.resnet correspond to?

### ISSUE THREAD

**Issue by mightestDuck** [tensorflow/tensorflow#51550]
## URL(s) with the issue:

[https://www.tensorflow.org/api_docs/python/tf/keras/applications/resnet](https://www.tensorflow.org/api_docs/python/tf/keras/applications/resnet)

### Clear description
The building blocks provided in `tensorflow.python.keras.applications.resnet` are not well described. I am having a hard time identifying which architecture do block3 and stack3 come from. I posted a related question on StackOverflow hoping someone would know: [https://stackoverflow.com/questions/68815764/what-architecture-do-block3-and-stack3-from-keras-applications-resnet-correspond](https://stackoverflow.com/questions/68815764/what-architecture-do-block3-and-stack3-from-keras-applications-resnet-correspond)

### Correct links

[https://github.com/tensorflow/tensorflow/blob/b47b4139710fda407b56e1dc8de84b05779353e6/tensorflow/python/keras/applications/resnet.py#L345-L436](https://github.com/tensorflow/tensorflow/blob/b47b4139710fda407b56e1dc8de84b05779353e6/tensorflow/python/keras/applications/resnet.py#L345-L436)

**Comment by tilakrayal** [comment]
@mightestDuck ,

 
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.Thanks!
