### ISSUE TITLE
Need TF-TRT support to INT32 OPs

### ISSUE THREAD

**Issue by bixia1** [tensorflow/tensorflow#51559]
Currently, some TF-TRT converters already allow INT32 data types. Need to find out other TensorRT layers that support INT32 data types and make the TF-TRt converters to reflect that. Need to add test cases.

**Comment by poulsbo** [comment]
Due to age and inactivity for an extended period of time, this issue has been closed as obsolete and has been added to TensorFlow’s bug bankruptcy list. If this issue is still relevant, please re-open it and add any appropriate context.
