### ISSUE TITLE
InvalidArgumentError:  indices[15,28] = 22105 is not in [0, 22015)  [[node encoder/embedding/embedding_lookup 

### ISSUE THREAD

**Issue by EthanIrby8** [tensorflow/tensorflow#51555]
I am using tf 2.4.1, keras 2.4.3, and python 3.8.10 on CPU. 
I have downloaded pretrained GloVe word embeddings to train an Encoder-Decoder Model for abstractive summarization. 
I have created two embedding matrices, one to represent the vocabulary of the source input documents and one to represent the summary vocabulary. I am a little unsure if this is the correct practice but the model is able to train on 100 batches until the bug in the title stops training. 

Currently, the embedding matrix is of size 22015, 200. The first dimension represents the indices of the word embeddings and the second dimension represents the embedding dimension size for each word. The size of the encoder (source documents) vocabulary is taken directly from the embedding matrix = 22015. The summary vocabulary size is 7932 which is also the size of the first dimension of the summary embedding matrix. I should note that the original vocabulary sizes taken directly from dictionaries are different though come before the implementation of glove. 

The Decoder model is expected to output a probability distribution over the summary vocabulary (7932 "classes"). It seems that the decoder output head is functioning as intended but the error occurs when the encoder starts to work on its word embeddings

CODE to SIMULATE issue
`from keras.layers import Embedding`

```
encoder_vocab_size = 22015
emb_dim = 200
```

```
input_dim = encoder_vocab_size 
output_dim = emb_dim
```
- Setting the weights of the Embedding layer to pretrained GloVe matrix (22015x200)
`weights = [embmatrix]`

- The Encoder uses this embedding layer with exact configuration
`embedding = Embedding(input_dim, output_dim, input_length=200, weights=weights, is_trainable=False)`

- Training the Encoder-Decoder Model
``for` epoch in range(25):`

    ``for` batch, (encoder_inp_batch, decoder_input_batch, target_input_batch) in enumerate(generator):`
        - encoder_inp_batch is shape (batch_size, 200)
        - decoder_input_batch is shape (batch_size, 49)
        - target_input_batch is shape (batch_size, 49)

        with tf.GradientTape() as tape:
            - Code breaks here AFTER successfully training over 100 batches of data
            encoder_output, encoder_hidden_states = encoder(encoder_inp_batch)

The loss used is sparse_categorical_crossentropy as targets are not one-hot encoded. Data is passed to the model in batches of 16. Number of data points used for training ~ 5,000. 
Still trying to pinpoint where exactly the embedding index out of bounds error might lie. Is it an issue arising from indices in the encoder embedding matrix or does the index out of bounds occur when feeding sequences of encoder training data where indices might be greater than the allowable range up to 22015

**Comment by sushreebarsa** [comment]
@EthanIrby8 Thank you for the post!  In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by EthanIrby8** [comment]
@sushreebarsa Thanks for the heads up! I added the code you requested. If it's possible, could you add a keras label to the issue as per the embedding layer?

**Comment by sushreebarsa** [comment]
@EthanIrby8 Thank you for the update! This issue is related to Keras.
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by EthanIrby8** [comment]
@sushreebarsa issue posted on keras-team/keras-repo as of yesterday

**Comment by sushreebarsa** [comment]
@EthanIrby8 Thank you for the update! Could you please move this issue to closed status as you have posted this issue in Keras repo ?Thanks!
