### ISSUE TITLE
Tape Gradient 

### ISSUE THREAD

**Issue by domGitDev** [tensorflow/tensorflow#51552]
How to use Tape gradient in tensorflow/c/eager/gradients in C++ application?

- Cento 7
- tensorflow 2.6
- Cuda 11.2

**Comment by mohantym** [comment]
Hi!@domGitDev,We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by domGitDev** [comment]
Thanks, posted in the forum.
