### ISSUE TITLE
esrgan failed on image over 50x50 pixels : error output tensor

### ISSUE THREAD

**Issue by budibeta** [tensorflow/tensorflow#51551]

**Comment by sushreebarsa** [comment]
@budibeta In order to expedite the trouble-shooting process,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by budibeta** [comment]
> @budibeta In order to expedite the trouble-shooting process,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

dont picky, if use "bug issue" tag, people still doesnt help my issue

**Comment by sushreebarsa** [comment]
@budibeta Could you please update the content , it will be helpful for us in order to expedite the trouble-shooting process for the issue reported here.Thank you!
