### ISSUE TITLE
numpy dependency on 1.19.2

### ISSUE THREAD

**Issue by ganand1** [tensorflow/tensorflow#51554]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L81

why is there a dependency on 1.19.2 when there are later version of numpy?

**Comment by bhack** [comment]
See https://github.com/tensorflow/tensorflow/issues/47691

**Comment by tilakrayal** [comment]
@ganand1 ,

As mentioned in this [link](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/tools/pip_package/setup.py#L84), there is a bound on numpy versions supported by TF2.4 ( ~=1.19.2). Currently numpy version should be >=1.19.2 and < 1.20.

Also for future releases please subscribe to #47691

Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate
