### ISSUE TITLE
Faster R-CNN TFlite conversion and inference works on CPU, but when run on GPU results in segmentation fault during inference

### ISSUE THREAD

**Issue by oalcabes** [tensorflow/tensorflow#51556]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
import tensorflow as tf
import numpy as np
import cv2 as cv
import time

def reduce_size(im,percent=None,new_width=None):
    '''
    Get a reduced size version of an image
    
    Inputs:
        im: numpy array of an image
        percent: if not None, the percent at which to scale the image
        new_width: if not None, the new width to scale the image to (scales the
                   height proportinally)
                   
    Returns: numpy array of new, smaller image
    
    Note: please only set either percent OR new_width, it doesn't make sense
          to set both
    '''
    
    if percent:
        width = int(im.shape[1] * percent / 100)
        height = int(im.shape[0] * percent / 100)
        dim = (width, height)
    elif new_width:
        new_percent = new_width / im.shape[1]
        height = int(im.shape[0] * new_percent)
        dim = (new_width,height)
        
    small_im = cv.resize(im,dim,interpolation = cv.INTER_AREA)
    
    return small_im

print('tensorflow version: %s' %tf.__version__)

tf.config.list_physical_devices()

saved_model_dir = 'faster_rcnn_resnet50_v1_800x1333_coco17_gpu-8/saved_model'

img_path = 'Test_image.jpg'
im = cv.imread(img_path)
small_im = reduce_size(im,percent=10)
input_tensor = tf.convert_to_tensor(small_im)
input_tensor = input_tensor[tf.newaxis, ...]

print('Loading model normally...', end='')
start_time = time.time()
detect_fn = tf.saved_model.load(saved_model_dir)
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

print('Inferring...', end='')
start_time = time.time()
detections = detect_fn(input_tensor)
end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

print('Converting model to tflite...', end='')
start_time = time.time()
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.allow_custom_ops=True
converter.experimental_new_converter = True

converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
end_time = time.time()
elapsed_time = end_time - start_time
tflite_model = converter.convert()
print('Done! Took {} seconds'.format(elapsed_time))

print('Creating an interpreter...', end='')
start_time = time.time()
interpreter = tf.lite.Interpreter(model_content=tflite_model)

input_index = interpreter.get_input_details()[0]["index"]
output_index = interpreter.get_output_details()[0]["index"]

interpreter.resize_tensor_input(0, [1, input_tensor.shape[1], input_tensor.shape[2], 3])
interpreter.allocate_tensors()
end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

print('Inferring image...', end='')
start_time = time.time()
interpreter.set_tensor(input_index, input_tensor)
interpreter.invoke()
raw_prediction = interpreter.tensor(output_index)
end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

```
Example model used:  [Faster R-CNN ResNet50 V1 800x1333](http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet50_v1_800x1333_coco17_gpu-8.tar.gz) from the tensorflow 2.0 model zoo

Test image I'm currently using (this is just to get any output at all, I plan to use a different image to test bounding boxes once I can get the code working):
![Test_image](https://user-images.githubusercontent.com/50996925/129928612-b0baa83e-4f0e-46bb-b47c-fbee8c8fca7a.jpg)

### 3. Failure after conversion

The above code runs fine on a CPU, but when run on a GPU, a segmentation fault is raised during the interpreter.invoke() command. I have tried a number of different options for the conversion step of converter.target_spec.supported_types = [tf.float16], including uint16 and some of the more experimental options, as well as just completely not including that step. In all cases, the code works on the CPU and results in a segment fault on the GPU, although for some the segmentation fault occurs much faster than with others.

I expect there is some fix in the conversion script, but I'm not sure if it's a problem with my commands, or if a model this large is not yet possible to use with TFlite on a GPU.

**Comment by abattery** [comment]
fyi @impjdi @renjie-liu

**Comment by renjie-liu** [comment]
Can you try just tf.float for GPU first? thanks!

**Comment by oalcabes** [comment]
Sure! When I run that I just get the error

```
  File "tflite_test.py", line 79, in <module>
    converter.target_spec.supported_types = [tf.float]
AttributeError: module 'tensorflow' has no attribute 'float'
```
Does that require an updated tensorfow version?

**Comment by renjie-liu** [comment]
sorry I mean tf.float32

**Comment by oalcabes** [comment]
Oh, ok. That one results in the segmentation fault.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
