### ISSUE TITLE
Model input channel Question

### ISSUE THREAD

**Issue by JunHyunjae** [tensorflow/tensorflow#51566]
Generally, Tensorflow uses channel last. 

But I get input from channel first because I converted Torch --> ONNX --> Pb --> TFlite.

input = (1, 3, 224, 224)
out = TFLiteModel(input)

Is there a method that can be used as above?

**Comment by abattery** [comment]
TFLite converter & runtime prefers NCHW data format since we have optimized kernels for the data format not other data formats. Currently, we don't have such a feature to produce the other data format. We will consider this post as the feature request.

**Comment by JunHyunjae** [comment]
@abattery 
Thanks, i solved it by performing a permute on the input.
