### ISSUE TITLE
setup(python_requires) argument

### ISSUE THREAD

**Issue by majiang** [tensorflow/tensorflow#51565]
**Describe the problem**

[`setup.py` uses only `setup(classifier)` argument to specify supported Python versions.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py)

According to [Python Packaging User Guide > Packaging and distributing projects](https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers),
> this information is only used for searching & browsing projects on PyPI, not for installing projects. To actually restrict what Python versions a project can be installed on, use the [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) argument.

Adding `python_requires='>=3.7,<3.10'` would help version resolution for installing proper version of tensorflow.

**Comment by mihaimaruseac** [comment]
This is not high priority/very relevant as we need to release different wheels for each version of Python we support anyway.
