### ISSUE TITLE
Feature Request : inline graph visualization for ipython

### ISSUE THREAD

**Issue by AshishBora** [tensorflow/tensorflow#5156]
Building TensorFlow graphs is much easier when done in an interactive environment like ipython.

Would be nice to have an interactive display of the current graph inline in ipython using something like mpld3. Another simpler possibility would be to just output an image of the current graph (no interactivity).

**Comment by yaroslavvb** [comment]
There's already a way to do it. The widget that's used to visualize the graph in TensorBoard is embeddable into Jupyter notebook: http://stackoverflow.com/questions/38189119/simple-way-to-visualize-a-tensorflow-graph-in-jupyter/38192374#38192374

**Comment by AshishBora** [comment]
This is awesome! Thanks!

Maybe this should be documented better? Also something like tf.show_graph() might be nicer than the current solution.

**Comment by asimshankar** [comment]
FYI @jart @danmane 
(Thanks @yaroslavvb!)
Closing this out since there is a way to do what @AshishBora asked for.
