### ISSUE TITLE
LSTM & BiLSTM can't run correct results while batch processing on Mobile 

### ISSUE THREAD

**Issue by kylechang523** [tensorflow/tensorflow#51561]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux and Android
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (or github SHA if from source): tensorflow2.5.0-gpu

**Provide the text output from tflite_convert**

```
run_model = tf.function(lambda x: basemodel(x))
# This is important, let's fix the input size.
BATCH_SIZE = 1
STEPS = 32
INPUT_SIZE = 320
CHANNEL = 1
concrete_func = run_model.get_concrete_function(
  tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE, CHANNEL], basemodel.inputs[0].dtype))


MODEL_DIR = "BiLSTM"
basemodel.save(MODEL_DIR, save_format="tf", signatures=concrete_func)

converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_model = converter.convert()
open("BiLSTM.tflite", "wb").write(tflite_model)

```

**Standalone code to reproduce the issue** 
We developed a text recognition model including BiLSTM basing on TF2.5, and convert the model to TFlite, which can run on mobile GPU successfully. 

While the batch size=1, the model can recognize the text correctly. But when btachsize>1, only the first batch result is correct, and others are incorrect. And before using the tflite model, we need to reset all variables:
```
interpreter.reset_all_variables()
interpreter.set_tensor(input_details[0]['index'], X)
interpreter.invoke()
y_pred = interpreter.get_tensor(output_details[0]['index'])
```
I think the LSTM states need to be reset after being called. Is there any solution to reset them within a batch?

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by renjie-liu** [comment]
Yes, you need to call `interpreter.reset_all_variables()` after each `interpreter.invoke()`.

It should work for batch inference as well.

**Comment by kylechang523** [comment]
> Yes, you need to call `interpreter.reset_all_variables()` after each `interpreter.invoke()`.
> 
> It should work for batch inference as well.

We have added the `interpreter.reset_all_variables()` after each `interpreter.invoke()`. And the batch process can run well on the computer. However when we deployed this model to mobile,  the results are inconsistent. It seems that there is no status reset for each instance inside the batch. For example, we concat 4 images into (4,32,320,1) as the input, but only the first image can have correct prediction while the rest of them are wrong. 

Can you check the LSTM or BiLSTM implementation for the mobile phone and add the reset status inside the batch process for the sequence model?

**Comment by renjie-liu** [comment]
I see, adding YC.

On mobile (assume you're using c++), the equivalent c++ call is : **ResetVariableTensors**: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/interpreter.h#L624

**Comment by kylechang523** [comment]
I have added this call: ResetVariableTensors, but it only works after the
interpreter invoke, not working for the LSTM inside the batch.

**Comment by kylechang523** [comment]
Hi Renjie, 
This is our engineering code:

`//reset variables for models like lstm
        if(config.resetVariable) {
            interpreter.resetVariableTensors();
        }
        interpreter.runForMultipleInputsOutputs(inputBuffers, outputs);`

And this is our model output:
<img width="1046" alt="截屏2021-08-20 上午9 57 33" src="https://user-images.githubusercontent.com/33585287/130268198-c566896b-08b2-429e-b0f8-af8981c66003.png">

The prediction on the top is the tflite results on the computer and the bottom is from a mobile device. Is there anyway to reset the status of LSTM inside the batch?

**Comment by renjie-liu** [comment]
I see, in this case, I suggest there are two options:

1) run prediction 1 by 1, it should always work
2) if you really need batch inference, please set the batch_size during model conversion, and run the fixed batch size inference as well

**Comment by kylechang523** [comment]
Hi,

We already used the fixed batch size while converting the tflite model
`run_model = tf.function(lambda x: basemodel(x))
# This is important, let's fix the input size.
BATCH_SIZE = 4
STEPS = 32
INPUT_SIZE = 320
CHANNEL = 1
concrete_func = run_model.get_concrete_function(
    tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE, CHANNEL], basemodel.inputs[0].dtype))


MODEL_DIR = "model"
basemodel.save(MODEL_DIR, save_format="tf", signatures=concrete_func)

converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)`

Is it possible that tensorflow  team can solve this bug?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
