### ISSUE TITLE
Error: "Failed to connect to all addresses", TPU on Colab

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#51579]
When I attempt to train on Colab using Keras and TPU, I get this error and training stops before the first epoch.

Link to code for reproduction: https://colab.research.google.com/drive/1ddTaQNmKbapwDPhrPlDKpnoCb8Exa_XI?usp=sharing

**Comment by kashyapraval** [comment]
Is this also in previous versions of TF2.x?

**Comment by sushreebarsa** [comment]
@Tylersuard Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by Tylersuard** [comment]
@sushreebarsa Thank you!

**Comment by sushreebarsa** [comment]
@Tylersuard Could you please confirm if you have posted this issue on Keras repo ? If you did so please move this issue to closed status .Thanks!
