### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message when using tf.function

### ISSUE THREAD

**Issue by wangwei-cmd** [tensorflow/tensorflow#51589]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 21.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda binary
- TensorFlow version (use command below): tf.2.5
- Python version: python 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 11.4, cudatoolkit 11.0.221,  cudnn 8.2.1.32
- GPU model and memory: NVIDIA TITAN RTX, 24Gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
Successfully opened dynamic library libcudart.so.11.0 v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
**Describe the current behavior**
I write a custom model involving the tf.gather_nd function. When the 'train_step' function is not decorated   by 'tf.function', the model can be well-trained. But when I use 'tf.function' to decorate the 'train_step' function, I get the error 'google.protobuf.message.DecodeError: Error parsing message'.

**Describe the expected behavior**
The model can be trained.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing): no

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
import tensorflow as tf
import numpy as np

class GatherModel(tf.keras.Model):
    def __init__(self,ind1,w1):
        super(GatherModel, self).__init__()
        self.ind1=ind1
        self.w1=tf.cast(w1,tf.float32)
        self.lambda1 = tf.Variable(initial_value=tf.constant(0.1), trainable=True, name='lambda1')

    def __call__(self, inputs,training=0):
        y=inputs
        for i in range(5):
            y=tf.transpose(y, [1, 2, 3, 0])
            y=tf.gather_nd(y*1.0, self.ind1)
            y=y*self.w1
            y=tf.reduce_sum(y,0)
            y=tf.transpose(y,[3,0,1,2])
            y = self.lambda1*y
        return y

# @tf.function
def train_step(model, inputs, labels, Loss, optimizer):
    with tf.GradientTape() as tape:
        predictions = model(inputs, training=1)
        loss = Loss(labels, predictions)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    return loss

if __name__ == '__main__':
    ind1=np.random.randint(0,300,[367, 217, 721, 2])
    w1=np.random.normal(size=[367, 217, 721, 1, 1])
    Model=GatherModel(ind1,w1)
    inputs=tf.random.normal([2,256,256,1])
    labels= tf.random.normal([2,217,721,1])
    loss=tf.keras.losses.MeanSquaredError()
    optimizer=tf.keras.optimizers.Adam(0.001)
    for i in range(10):
        LL=train_step(Model,inputs,labels,loss,optimizer)
        print(LL)
  
In the google colab https://colab.research.google.com/drive/1TrTctTKjYOIrZ2rvKhQmdTDS77d0gmg9#scrollTo=WMcegEVFWW_M, it says that the program crashed because of  exhausting of RAM.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@wangwei-cmd ,

Can you please try to execute the in tf v2.6 which it is executing without any errors.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3f3cb42450844c117e42351676c448ef/u51589.ipynb).

Also please take a look at this links with similar error.[Link1](
https://github.com/tensorflow/tensorflow/issues/23809),[Link2](https://stackoverflow.com/questions/57642264/how-to-fix-google-protobuf-message-decodeerror-error-parsing-message-when-cr).It helps.Thanks

**Comment by wangwei-cmd** [comment]
Hi, @tilakrayal ， after uncomment @tf.function in the gist provided by your link,  the colab also crashed.

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I have tried to uncomment the tf.function from code and executed in colab with TF version 2.5, 2.6 and nightly version and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/b26597c7d9157d04a35cd7652bdb3108/untitled62.ipynb). Thanks!

**Comment by ymodak** [comment]
Closing since its a Duplicate https://github.com/tensorflow/tensorflow/issues/51588
Thanks!
