### ISSUE TITLE
[TF Lite C API] XNNPACK option not available using C API 

### ISSUE THREAD

**Issue by sivers2021** [tensorflow/tensorflow#51597]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 11.4
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: Pixel 4
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: tensorflow-lite-2.5.0  AAR 
-   **Python version**: 3.7
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: n/a
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem

I am using TFlite C API available with `tensorflow-lite-2.5.0`  AAR  binary downloaded from Maven. I can not find any way of setting XNNPACK. 

I am looking for **C API** to enable XNNPACK (not ObjC, or Java), something like this:
```
TFL_CAPI_EXPORT extern void TfLiteInterpreterOptionsSetXNNPACK(TfLiteInterpreterOptions* options, bool enable);
```
unless it is already available in some form

**Comment by abattery** [comment]
@multiverse-tf @Maratyszcza could you take a look?

**Comment by fergushenderson** [comment]
I think you may be able to enable XNNPACK in the C API by using the 
TfLiteXNNPackDelegateCreate function from
tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h to create a delegate,
and then passing that delegate to the TfLiteInterpreterOptionsAddDelegate function
(or the TfLiteInterpreterModifyGraphWithDelegate function in older versions)?

**Comment by sushreebarsa** [comment]
@sivers2021 Could you please refer to the above [comment](https://github.com/tensorflow/tensorflow/issues/51597#issuecomment-1054169559) and let us know the outcome? Thanks!
