### ISSUE TITLE
Determinism OP bug on TF 2.6.0

### ISSUE THREAD

**Issue by raudipra** [tensorflow/tensorflow#51596]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7.11
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.2
- GPU model and memory: Tesla K80 / 12MB

**Describe the current behavior**
I've setup the TF determinism environment like what I usually done on Google Colab with TF 2.4.1
-  Setup all the global seeds
- run ```os.environ['TF_DETERMINISTIC_OPS'] = '1'``` and ```os.environ['TF_CUDNN_DETERMINISTIC'] = '1'```

It used to work fine on 2.4.1 but when I run the training on 2.6.0 I got this error
```
UnimplementedError:  Deterministic GPU implementation of SparseSoftmaxXentWithLogitsOp not available.
	 [[node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at <ipython-input-25-471bb77471a2>:5) ]] [Op:__inference_train_function_1044]
```

**Describe the expected behavior**
No error occured during training

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): -

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

[Colab link](https://colab.research.google.com/drive/1ogEnSN-E9ZKc09kMWRs8vXgBj9Zlfaoo?usp=sharing)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Mrwoks** [comment]
# Get your gradients after training
loss_value, grads = grad(model, features, labels)

# Apply some clipping
grads = [tf.clip_by_norm(g, norm)
             for g in grads]

# Continue on with training
optimizer.apply_gradients(grads)

**Comment by raudipra** [comment]
> # Get your gradients after training
> loss_value, grads = grad(model, features, labels)
> 
> # Apply some clipping
> grads = [tf.clip_by_norm(g, norm)
> for g in grads]
> 
> # Continue on with training
> optimizer.apply_gradients(grads)

is this the fix to model.fit() implementation? any PR for this fix already?

**Comment by tilakrayal** [comment]
@raudipra ,
Can you please try to test your code in tf-nightly version which the code is executed without any error.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/19f1395da404ff0a1abd0565fc303ea6/nightly-51596.ipynb).Thanks
