### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'Layer'

### ISSUE THREAD

**Issue by MAHESH47T** [tensorflow/tensorflow#51594]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): using pip install tensorflow in jupyter
- TensorFlow version: 2.6.0
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
  While run the code I am getting below error. Kindly on this. 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-fc46460c6aba> in <module>
      4 import mrcnn.config
      5 import mrcnn.utils
----> 6 from mrcnn.model import MaskRCNN
      7 from pathlib import Path
      8 

~\Documents\Mahe_Juptyer\Mask_RCNN-master\mrcnn\model.py in <module>
    253 
    254 
--> 255 class ProposalLayer(KE.Layer):
    256     """Receives anchor scores and selects a subset to pass as proposals
    257     to the second stage. Filtering is done based on anchor scores and

**AttributeError: module 'keras.engine' has no attribute 'Layer'**
-------------------------------------------------------------------------------------------
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi! @MAHESH47T  ,
In order to expedite the trouble-shooting process, please provide a  Colab Gist / sample code snippet to reproduce the issue reported here. Thanks!

**Comment by MAHESH47T** [comment]
Dear @mohantym,
    Thanks for the reply,
    Kindly find the code below which is used and its output generated. Please let me know if anything else is required.
--------------------------------
**Code:**
import os
import numpy as np
import cv2
import mrcnn.config
import mrcnn.utils
from mrcnn.model import MaskRCNN
from pathlib import Path

**Error Output:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-f0bd135e195a> in <module>
      4 import mrcnn.config
      5 import mrcnn.utils
----> 6 from mrcnn.model import MaskRCNN
      7 from pathlib import Path

~\Documents\Mahe_Juptyer\Mask_RCNN-master\mrcnn\model.py in <module>
    253 
    254 
--> 255 class ProposalLayer(KE.Layer):
    256     """Receives anchor scores and selects a subset to pass as proposals
    257     to the second stage. Filtering is done based on anchor scores and

AttributeError: module 'keras.engine' has no attribute 'Layer'

**Comment by MAHESH47T** [comment]
Mistakenly closed it.

**Comment by LudwigStumpp** [comment]
Hi @MAHESH47T,

Taking a look at the Issues of the library `mrcnn` that you are using at https://github.com/matterport/Mask_RCNN/issues/2587 we can find a solution to your issue.

The issue is caused by the library not being upward compatible to the latest keras version `2.6.0`.

Please take a look at the proposed version as stated in the link above.

Also please note that this issue is not caused by the Tensorflow library, but by the mrcnn library not specifying their dependencies correctly. For the future, it would be great if you first take a look at the already reported issues of the library that is throwing the error instead of creating an issue here.

Hope that helps!

Best,
Ludwig

**Comment by mohantym** [comment]
Hi! @MAHESH47T ,
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by MAHESH47T** [comment]
Hi,
  Yeah, I have tried lowering the version of tensorflow, keras. Now it is working.
  
 #!pip install tensorflow==1.15
# !pip install keras==2.3.0

**Comment by LudwigStumpp** [comment]
Hi @MAHESH47T,

great to hear! Glad that I could help! :) Please could you upvote my provided solution such that others see it?

All the best,
Ludwig

**Comment by mohantym** [comment]
Hi @MAHESH47T , if you can also  replace the `import keras.engine as KE with  import keras.layers as KE` after forking the repo , so the KE.layer will do it work if you want to use TF 2.x versions.

**Comment by Onkar20018** [comment]
AttributeError: module 'keras.engine' has no attribute 'Layer'
I am getting this error , even after using the keras version2.0.8 and tensor flow version 1.14.0
