### ISSUE TITLE
Feature Request: AdaDelta optimizer

### ISSUE THREAD

**Issue by fabiencro** [tensorflow/tensorflow#516]
AdaDelta (http://arxiv.org/abs/1212.5701) is a popular training algorithm for Neural Network. It is available in most other libraries I have used, like Torch or chainer. 

In my small personal experience (and at least for the Neural Networks I have used), AdaDelta is often the optimizer that works best out of the box (RMSProp working quite well as well, while Adam, Adagrad and SGD typically being not as good)

Therefore, it would be nice if AdaDelta could be added to the set of available optimizers.

**Comment by Mistobaan** [comment]
I tried to give it a shot in [this branch](https://github.com/tensorflow/tensorflow/compare/master...Mistobaan:master)

I tried to follow as much as possible the paper and the other training operations, but as Is my first tensorflow operator I would like some feedback and guidelines if anyone has time to review the code.

**Comment by Mistobaan** [comment]
@martinwicke I think we can close this issue. The adadelta operator is in the codebase

**Comment by vrv** [comment]
thank you!
