### ISSUE TITLE
Build failure when building Tensorflow MLIR 

### ISSUE THREAD

**Issue by sjarus** [tensorflow/tensorflow#51601]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 7221ec4eace8d163954fd391c8f8e5accd3ae771
- Python version: Python 3.6.9
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

A build failure is seen while compiling for MLIR from the current HEAD, using a standard build command that's otherwise always worked. The error appears to be absl usage related, within  tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc

Assumed this was transient, but it has been present for 4 days now. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

$ bazel build --config=v2 --linkopt="-fuse-ld=lld" tensorflow/compiler/mlir/...  -j 32

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: {$MYPATH}/tensorflow/compiler/mlir/tfrt/BUILD:136:16: C++ compilation of rule '//tensorflow/compiler/mlir/tfrt:tf_cpurt_kernels' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 419 argument(s) skipped)
In file included from ./tensorflow/core/profiler/lib/traceme.h:27:0,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:32:
./tensorflow/core/profiler/lib/traceme_encode.h: In instantiation of 'tensorflow::profiler::TraceMeArg::TraceMeArg(absl::lts_20210324::string_view, Value) [with Value = llvm::StringRef]':
tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:285:70:   required from here
./tensorflow/core/profiler/lib/traceme_encode.h:35:61: error: no matching function for call to 'absl::lts_20210324::AlphaNum::AlphaNum(llvm::StringRef&)'
   TraceMeArg(absl::string_view k, Value v) : key(k), value(v) {}
                                                             ^
In file included from external/com_google_absl/absl/container/internal/layout.h:176:0,
                 from external/com_google_absl/absl/strings/internal/cord_rep_ring.h:25,
                 from external/com_google_absl/absl/strings/cord.h:81,
                 from ./tensorflow/core/platform/default/cord.h:22,
                 from ./tensorflow/core/platform/cord.h:25,
                 from ./tensorflow/core/platform/tstring.h:24,
                 from ./tensorflow/core/platform/types.h:23,
                 from ./tensorflow/core/platform/logging.h:20,
                 from ./tensorflow/core/platform/status.h:25,
                 from ./tensorflow/core/lib/core/status.h:19,
                 from ./tensorflow/core/util/device_name_utils.h:21,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_structs.h:28,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_op_interfaces.h:27,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_ops.h:39,
                 from ./tensorflow/compiler/mlir/tensorflow/dialect_registration.h:24,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:24:
external/com_google_absl/absl/strings/str_cat.h:283:3: note: candidate: template<class T, typename std::enable_if<(std::is_class<_Tp>::value && (std::is_same<T, std::_Bit_reference>::value || std::is_same<T, bool>::value))>::type* <anonymous> > absl::lts_20210324::AlphaNum::AlphaNum(T)
   AlphaNum(T e) : AlphaNum(static_cast<bool>(e)) {}  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:283:3: note:   template argument deduction/substitution failed:
external/com_google_absl/absl/strings/str_cat.h:282:11: error: no type named 'type' in 'struct std::enable_if<false, void>'
           nullptr>
           ^~~~~~~
external/com_google_absl/absl/strings/str_cat.h:282:11: note: invalid template non-type parameter
external/com_google_absl/absl/strings/str_cat.h:271:3: note: candidate: template<class T, class> absl::lts_20210324::AlphaNum::AlphaNum(T)
   AlphaNum(T e)  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:271:3: note:   template argument deduction/substitution failed:
external/com_google_absl/absl/strings/str_cat.h:269:13: error: no type named 'type' in 'struct std::enable_if<false, void>'
             typename = typename std::enable_if<
             ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:252:3: note: candidate: template<class Allocator> absl::lts_20210324::AlphaNum::AlphaNum(const std::__cxx11::basic_string<char, std::char_traits<char>, Allocator>&)
   AlphaNum(  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:252:3: note:   template argument deduction/substitution failed:
In file included from ./tensorflow/core/profiler/lib/traceme.h:27:0,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:32:
./tensorflow/core/profiler/lib/traceme_encode.h:35:61: note:   'llvm::StringRef' is not derived from 'const std::__cxx11::basic_string<char, std::char_traits<char>, Allocator>'
   TraceMeArg(absl::string_view k, Value v) : key(k), value(v) {}
                                                             ^
In file included from external/com_google_absl/absl/container/internal/layout.h:176:0,
                 from external/com_google_absl/absl/strings/internal/cord_rep_ring.h:25,
                 from external/com_google_absl/absl/strings/cord.h:81,
                 from ./tensorflow/core/platform/default/cord.h:22,
                 from ./tensorflow/core/platform/cord.h:25,
                 from ./tensorflow/core/platform/tstring.h:24,
                 from ./tensorflow/core/platform/types.h:23,
                 from ./tensorflow/core/platform/logging.h:20,
                 from ./tensorflow/core/platform/status.h:25,
                 from ./tensorflow/core/lib/core/status.h:19,
                 from ./tensorflow/core/util/device_name_utils.h:21,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_structs.h:28,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_op_interfaces.h:27,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_ops.h:39,
                 from ./tensorflow/compiler/mlir/tensorflow/dialect_registration.h:24,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:24:
external/com_google_absl/absl/strings/str_cat.h:249:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(absl::lts_20210324::string_view)
   AlphaNum(absl::string_view pc) : piece_(pc) {}  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:249:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'absl::lts_20210324::string_view'
external/com_google_absl/absl/strings/str_cat.h:248:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(const char*)
   AlphaNum(const char* c_str) : piece_(c_str) {}  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:248:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'const char*'
external/com_google_absl/absl/strings/str_cat.h:244:3: note: candidate: template<long unsigned int size> absl::lts_20210324::AlphaNum::AlphaNum(const absl::lts_20210324::strings_internal::AlphaNumBuffer<size>&)
   AlphaNum(  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:244:3: note:   template argument deduction/substitution failed:
In file included from ./tensorflow/core/profiler/lib/traceme.h:27:0,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:32:
./tensorflow/core/profiler/lib/traceme_encode.h:35:61: note:   'llvm::StringRef' is not derived from 'const absl::lts_20210324::strings_internal::AlphaNumBuffer<size>'
   TraceMeArg(absl::string_view k, Value v) : key(k), value(v) {}
                                                             ^
In file included from external/com_google_absl/absl/container/internal/layout.h:176:0,
                 from external/com_google_absl/absl/strings/internal/cord_rep_ring.h:25,
                 from external/com_google_absl/absl/strings/cord.h:81,
                 from ./tensorflow/core/platform/default/cord.h:22,
                 from ./tensorflow/core/platform/cord.h:25,
                 from ./tensorflow/core/platform/tstring.h:24,
                 from ./tensorflow/core/platform/types.h:23,
                 from ./tensorflow/core/platform/logging.h:20,
                 from ./tensorflow/core/platform/status.h:25,
                 from ./tensorflow/core/lib/core/status.h:19,
                 from ./tensorflow/core/util/device_name_utils.h:21,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_structs.h:28,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_op_interfaces.h:27,
                 from ./tensorflow/compiler/mlir/tensorflow/ir/tf_ops.h:39,
                 from ./tensorflow/compiler/mlir/tensorflow/dialect_registration.h:24,
                 from tensorflow/compiler/mlir/tfrt/jit/tf_cpurt_kernels.cc:24:
external/com_google_absl/absl/strings/str_cat.h:241:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(absl::lts_20210324::Dec)
   AlphaNum(Dec dec);  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:241:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'absl::lts_20210324::Dec'
external/com_google_absl/absl/strings/str_cat.h:240:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(absl::lts_20210324::Hex)
   AlphaNum(Hex hex);  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:240:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'absl::lts_20210324::Hex'
external/com_google_absl/absl/strings/str_cat.h:237:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(double)
   AlphaNum(double f)  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:237:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'double'
external/com_google_absl/absl/strings/str_cat.h:235:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(float)
   AlphaNum(float f)  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:235:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'float'
external/com_google_absl/absl/strings/str_cat.h:231:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(long long unsigned int)
   AlphaNum(unsigned long long x)  // NOLINT(*)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:231:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'long long unsigned int'
external/com_google_absl/absl/strings/str_cat.h:228:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(long long int)
   AlphaNum(long long x)  // NOLINT(*)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:228:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'long long int'
external/com_google_absl/absl/strings/str_cat.h:225:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(long unsigned int)
   AlphaNum(unsigned long x)  // NOLINT(*)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:225:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'long unsigned int'
external/com_google_absl/absl/strings/str_cat.h:222:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(long int)
   AlphaNum(long x)  // NOLINT(*)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:222:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'long int'
external/com_google_absl/absl/strings/str_cat.h:219:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(unsigned int)
   AlphaNum(unsigned int x)  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:219:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'unsigned int'
external/com_google_absl/absl/strings/str_cat.h:216:3: note: candidate: absl::lts_20210324::AlphaNum::AlphaNum(int)
   AlphaNum(int x)  // NOLINT(runtime/explicit)
   ^~~~~~~~
external/com_google_absl/absl/strings/str_cat.h:216:3: note:   no known conversion for argument 1 from 'llvm::StringRef' to 'int'
INFO: Elapsed time: 3705.770s, Critical Path: 377.10s
INFO: 11312 processes: 719 internal, 10593 local.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment]
I think this should be fixed now. Please reopen if that's not the case.

Culprit: TFRT introduced C++17 code via MLIR/LLVM but TF is using C++14.
