### ISSUE TITLE
installation issue：Can we install TensorFlow in Ubuntu14.04 without UI environment?

### ISSUE THREAD

**Issue by Lewis-Liu** [tensorflow/tensorflow#5160]
Can we install TensorFlow in Ubuntu14.04 **without UI environment**?
I try install to install tensorflow in ubuntu with out UI, but i fail. So I want to know ,does the tensorflow support the ubuntu without UI environment?  thanks~

### Environment info
Operating System:
Ubuntu 14.04 without UI.
`Linux data-science-toolbox 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

If installed from binary pip package, provide:
1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl

**Comment by yaroslavvb** [comment]
I've installed TensorFlow without UI, you just need shell access and be able to run "pip install" on the wheel

**Comment by asimshankar** [comment]
@Lewis-Liu : Could you add some details about how you went about the install and what the failure was? (As much as possible, please fill in the details asked for in the [New issue template](https://github.com/tensorflow/tensorflow/issues/new) for future issues. Having more context helps us diagnose issues more effectively).

**Comment by Lewis-Liu** [comment]
@asimshankar   

### Environment info 
ubuntu 14.04  x86-64  on the VirtualBox. 
**I delete the Unity UI from OS for saving the system resource.**
python version: python 2.7.6

### A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl

### What other attempted solutions have you tried?
Firstly, I use pip to install the tensorflow. 
> sudo pip install --upgrade $TF_BINARY_URL

But it is very slow to download the  package.
So I use another way to download the package from the site.
Then I cd to the directory of the package.
And I use the following command to install tensorflow,but IOError happen.
>vagrant@data-science-toolbox:~$ pwd
/home/vagrant
vagrant@data-science-toolbox:~$ ls
book  get-pip.py  tensorflow-0.11.0rc1-cp27-none-linux_x86_64.zip
vagrant@data-science-toolbox:~$ **sudo pip install tensorflow-0.11.0rc1-cp27-none-linux_x86_64.zip**
Unpacking ./tensorflow-0.11.0rc1-cp27-none-linux_x86_64.zip
  Running setup.py (path:/tmp/pip-w8yLzr-build/setup.py) egg_info for package from file:///home/vagrant/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    **IOError: [Errno 2] No such file or directory: '/tmp/pip-w8yLzr-build/setup.py'**
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

 > File "<string>", line 17, in <module>

>**IOError: [Errno 2] No such file or directory: '/tmp/pip-w8yLzr-build/setup.py'**

>\----------------------------------------
>Cleaning up...
>Command python setup.py egg_info failed with error code 1 in /tmp/pip-w8yLzr-build
>Storing debug log for failure in /home/vagrant/.pip/pip.log

**Comment by asimshankar** [comment]
@Lewis-Liu :  You seem to be using a customized installation process that does not work with pip. Simply downloading the file, renaming it to a `.zip` and using `pip install` on it will not work (for one, any dependencies will not be downloaded and installed). 

Please use one of the [supported installation procedures](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup).

Unfortunately, we do not have the bandwidth to support customized installation processes. Sorry about that.

That said, the installation process does not require a UI, so you're good there :)

**Comment by Lewis-Liu** [comment]
@asimshankar  ok, thanks a lot.
