### ISSUE TITLE
TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by arjunskumar** [tensorflow/tensorflow#51600]
TF Version: `2.6.0`

using `tf.random.set_seed(7) `  produce  TypeError: 'int' object is not callable

**Comment by arjunskumar** [comment]
This one `tf.compat.v1.set_random_seed(7)` worked for me in `TF 2.6.0` in Google Colab but dont know why I cant get the same with `tf.random.set_seed(7)`

**Comment by LudwigStumpp** [comment]
Hi @arjunskumar,

I was trying to replicate what you stated above in a Google Colab environment:

```python
import tensorflow as tf
print(tf.__version__)  # 2.6.0
tf.random.set_seed(7)
```

However, this does not throw any errors in my Colab environment.

Could you please provide a minimal code example where the bug occured?
Also, could you please copy above code and execute it in a new environment "https://colab.research.google.com/notebooks/empty.ipynb" to verify?

Best,
Ludwig

**Comment by arjunskumar** [comment]
Now it's working on my google colab. Dont know the exact reason why the same code behaved strange earlier.

Thanks @LudwigStumpp
