### ISSUE TITLE
RuntimeError: Given shapes, [1, 23], ] and [1, 10], are not broadcastable.Node number 1392 (SELECT_V2) failed to prepare.

### ISSUE THREAD

**Issue by SkylerZheng** [tensorflow/tensorflow#51602]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu1804
- TensorFlow installation (pip package or built from source): tf-nightly 2.7.0
- TensorFlow library (version, if pip package or github SHA, if built from source): pip

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
I used dymamic axes when using onnx to convert pytorch model to onnx model, later on, I convert onnx to tensorflow model .pb and then to quantized tflite model.

Here shows the dynamic axes in my input data
                      dynamic_axes={
                          "img_feat": {0: "batch_size", 1: "sequences"},
                          "img_pos_feat": {0: "batch_size", 1: "sequences"},
                          "obj_masks": {0: "batch_size", 1: "sequences"},
                          "obj_boxes": {0: "batch_size", 1: "sequences"},
                          "input_ids": {0: "batch_size", 1: "sequences"},
                          "position_ids": {0: "batch_size", 1: "sequences"},
                          "attn_masks": {0: "batch_size", 1: "sequences"},
                          "gather_index": {0: "batch_size", 1: "sequences"}
                      },

### 3. Failure after conversion
I was able to convert the model successfully to int tflite model. 
During the inference phase of int tflite model, I resized the input_details to set tensor to match the dynamic axes in the tflite model. 

    shape_0 = list(named_args['img_feat'].shape)
    interpreter.resize_tensor_input(input_details[0]['index'], tuple(shape_0))

    shape_1 = list(named_args['img_pos_feat'].shape)
    interpreter.resize_tensor_input(input_details[1]['index'], tuple(shape_1))

    shape_2 = list(named_args['obj_masks'].shape)
    interpreter.resize_tensor_input(input_details[2]['index'], tuple(shape_2))

    shape_3 = list(named_args['position_ids'].shape)
    interpreter.resize_tensor_input(input_details[3]['index'], tuple(shape_3))

    shape_4 = list(named_args['attn_masks'].shape)
    interpreter.resize_tensor_input(input_details[4]['index'], tuple(shape_4))

    shape_5 = list(named_args['gather_index'].shape)
    interpreter.resize_tensor_input(input_details[5]['index'], tuple(shape_5))

    shape_6 = list(named_args['input_ids'].shape)
    interpreter.resize_tensor_input(input_details[6]['index'], tuple(shape_6))

All other input data work well except the obj_masks, and I got the error: 
  File "/home/ubuntu/Projects/Vesta/uniter/scripts/uniter_model_convert_quant_test.py", line 579, in model_prediction
    out_tflite_quant, pred_box_tflite_quant = run_tflite(interpreter, input_details, output_details, named_args, quant=True, detect_feature=detect_feature)
  File "/home/ubuntu/Projects/Vesta/uniter/scripts/uniter_model_convert_quant_test.py", line 436, in run_tflite
    interpreter.invoke()
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 879, in invoke
    self._interpreter.Invoke()
RuntimeError: Given shapes, [1, 23], ] and [1, 10], are not broadcastable.Node number 1392 (SELECT_V2) failed to prepare.

I'm wondering why the shape is [1,23],], instead of [1,23]? Did I do anything wrong?

#### Option A: Reference colab notebooks

Here is the visualization of SELECTV2 node in Netron.
![image](https://user-images.githubusercontent.com/32310519/130302354-ad89e43f-4f8a-4320-a30d-f01c48776f94.png)

Even if I donot use dynamic axes, the int tflite model is much slower than the float tflite model.

**Comment by mohantym** [comment]
Hi @SkylerZheng ,
In order to expedite the trouble-shooting process, could you please provide a stand alone code code to reproduce the issue reported here. Thanks!
