### ISSUE TITLE
Resource exhausted: EfficientNetB7 OOM

### ISSUE THREAD

**Issue by cjfghk5697** [tensorflow/tensorflow#51614]
<h1>1. System information</h1>
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
TensorFlow installation (pip package or built from source): 2.6.0
TensorFlow library (version, if pip package or github SHA, if built from source): all other libraries cloned from https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/

<h1>2. Error Code</h1>
Full Error code was saved in
https://github.com/cjfghk5697/Dacon_Code_Review/blob/main/cifar10.ipynb

Error code
```python
epochs = 40 
hist = model.fit(ds_train, epochs=epochs, validation_data=ds_test, verbose=2)
````
Error
```python
ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted:  OOM when allocating tensor with shape[64,192,300,300] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sequential_2/model_2/efficientnetb7/block2a_expand_conv/Conv2D (defined at /lib/python3.7/threading.py:926) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

	 [[div_no_nan_1/ReadVariableOp/_26]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

  (1) Resource exhausted:  OOM when allocating tensor with shape[64,192,300,300] and type half on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sequential_2/model_2/efficientnetb7/block2a_expand_conv/Conv2D (defined at /lib/python3.7/threading.py:926) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_308507]
```
I use a EfficientNetB7. But EfficientNetB7 fails fit model. Because the Resource exhausted in Colab. So I wish want to know how do fix this error.

<h1>3. After an Error</h1>
First, I added operations such as batch normalization because the efficientnetb7 parameter was too large to cause oom, but it didn't help.

Second, I followed the code on https://stackoverflow.com/questions/49665757/how-to-add-report-tensor-allocations-upon-oom-to-runoptions-in-keras, but the tensorflow version was different, so I couldn't use it.

Third
I've tried similar code on https://stackoverflow.com/questions/64197155/tf2-add-report-tensor-allocations-upon-oom-to-runoptions, but I don't know if this is the solution. The error remained the same.

**Comment by edwardyehuang** [comment]
How about EfficientNet-B1 or B2 ? Since EfficientNet-B7 requires large GPU memory, have you tried to use TPU in colab  ? (https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/tpu.ipynb).

**Comment by cjfghk5697** [comment]
@edwardyehuang Thanks for your answer.  I was tried to EfficientNet-B2. It was work well. But when i was used TPU in colab. It has a some error about labels. So i will try to more code. Once Again Thx for your answer.
