### ISSUE TITLE
`import tensorflow` with CUDA throws segmentation fault in macOS

### ISSUE THREAD

**Issue by youknowone** [tensorflow/tensorflow#5161]
```
$ export DYLD_LIBRARY_PATH=/usr/local/cuda/lib
$ python -c 'import tensorflow'
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
[1]    9772 segmentation fault  python -c 'import tensorflow'
```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Similar one: http://stackoverflow.com/questions/38924568/tensorflow-0-10-cuda-on-osx-segfaults-on-python-import
But the answer is not helpful.

### Environment info

Operating System: macOS 10.12

Installed version of CUDA and cuDNN:
```
$ ls -l libcud*
-rwxr-xr-x 1 root wheel 13504 Sep 27 06:59 libcuda.dylib
lrwxr-xr-x 1 root wheel    45 Sep 27 07:00 libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x 1 root wheel    50 Sep 27 07:00 libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x 1 root wheel    46 Sep 27 07:00 libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x 1 root wheel    49 Sep 27 07:00 libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:

wheel: https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc1-py2-none-any.whl
(CUDA driver version: 8.0.46)

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

Not possible.

### Logs or other output that would be helpful
How can I capture more detail of the segmentation fault? I will attach more if it is possible.

**Comment by TimZaman** [comment]
You're probably using the wrong python binary that does not correspond with your pip binary used for tf installation.
For MacOS this is usually a PITA with the built-in python and pip in /usr/bin/ and other ones from brew,macports,virtualenvs,etc. Make perfectly sure they match.

**Comment by drpngx** [comment]
This seems related to #5141.

**Comment by drpngx** [comment]
Do you want to try the resolutions in #5141 ? (Re-install CUDNN)

**Comment by youknowone** [comment]
Thanks, it looks like the same issue. Unfortunately, I still have same problem after installing cuddn. I will close this issue and subscribe #5141
