### ISSUE TITLE
use SPICE tf-lite model in Swift but get error "Provided data count 64000 must match the required count 4"

### ISSUE THREAD

**Issue by KittenYang** [tensorflow/tensorflow#51621]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS15.0
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 
```
    'TensorFlowLiteSwift', '~> 0.0.1-nightly'  
    'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
```

**Provide the text output from tflite_convert**

```
Failed to invoke the interpreter with error: Provided data count 64000 must match the required count 4.
```

**Standalone code to reproduce the issue** 
I'm using the SPICE model [here](https://tfhub.dev/google/lite-model/spice/1) which is used to recognize the dominant pitch in sung audio. 

This model's input is like below:
<img width="482" alt="截屏2021-08-22 下午2 05 14" src="https://user-images.githubusercontent.com/5517281/130344383-fac8767c-906e-474a-8184-5291435c0037.png">

It says this input sample rate should be 16000, so I set the sameRate to 16000,I run model in Swift like this:
```swift
func runModel(onBuffer buffer: [Int16]) -> [Dictionary<String, Any>]? { // here buffer has 16000 elements.
   do {
            // Copy the `[Int16]` buffer data as an array of `Float`s to the audio buffer input `Tensor`'s.
            let audioBufferData = Data(copyingBufferOf: buffer.map { Float($0) / maxInt16AsFloat32 })
            try interpreter.copy(audioBufferData, toInputAt: 0)

            // Run inference by invoking the `Interpreter`.
            let startDate = Date()
            try interpreter.invoke(). <------ Here get the error:  Provided data count 64000 must match the required count 4
            ...
    }
}
```

But finally I got this error. Could anyone tell me where am I wrong?  Thanks!

**Comment by abattery** [comment]
You need to resize the input tensor before invoking the model.
