### ISSUE TITLE
tf.keras.layers.LocallyConnected2D crashes with implementation mode = 2 and negative strides

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#51624]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4 and 2.6
- Python version: 3.6

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np                                                                                                                                                                         
strides = [-4,4,]
layer = tf.keras.layers.LocallyConnected2D(filters=3,kernel_size=3,padding="valid",strides=strides,implementation=2)
input = tf.random.uniform((3, 6, 10, 4), dtype=tf.float32)
res = layer(input)
```

**Describe the current behavior**
I run this snippet on TensorFlow 2.4 and it outputs `Floating point exception (core dumped)` and crashes. I tried to execute it on Google Colab with TensorFlow 2.6.0, and the session also crashes.

**Comment by sushreebarsa** [comment]
@lugalUrim 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by yongtang** [comment]
This issue seems to have been fixed by the latest tf-nightly.

**Comment by sushreebarsa** [comment]
@lugalUrim I tried to run your code on colab using TF-nightly 2.7.0-dev20210824 and didn't face the error as reported here , please find the attached gist  [here](https://colab.research.google.com/gist/sushreebarsa/bf73be4ca71e28640957401b965ba76a/untitled406.ipynb#scrollTo=9S1Di1lI9V0U) for reference .Please confirm the same.Thank you!
