### ISSUE TITLE
tf.keras.layers.ConvLSTM2D crashes when kernel_size contains zero

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#51625]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4 and 2.6.0
- Python version: 3.6

**Standalone code to reproduce the issue**
```
import tensorflow as tf
data_format = "channels_first"
return_sequences = False
filters = 2
kernel_size = [0, 1]
padding = "valid"
layer = tf.keras.layers.ConvLSTM2D(data_format=data_format,return_sequences=return_sequences,filters=filters,kernel_size=kernel_size,padding=padding,)
x = tf.keras.Input(shape = (2, 2, 5, 5))
y = layer(x)
model = tf.keras.Model(x, y)
input = tf.random.uniform((2, 2, 2, 5, 5), dtype=tf.float32)
res = model(input)
```

**Describe the current behavior**
It crashes in both TF 2.4 and TF 2.6.

**Comment by mohantym** [comment]
Hi @lugalUrim ,
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by yongtang** [comment]
This issue seems to have been fixed by the latest tf-nightly as well.

**Comment by mohantym** [comment]
Hi@yongtang, But what is reason behind making kernel size = 0 . We give a kernel size  as it will filter  through image extracting certain features. Defining kernel size 0 sounds  you are moving across the image with 0 filter size to extract features.

**Comment by mihaimaruseac** [comment]
@mohantym if user supplies invalid arguments then there should be an error, not a crash. An attacker will try to pass invalid arguments, so we should still handle these properly.
