### ISSUE TITLE
How to use tf c api with cuda ?

### ISSUE THREAD

**Issue by tanguofu** [tensorflow/tensorflow#5162]
I followed the  tutorial of  "https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html#usage-with-the-c-api" 

but it is only support CPU, so how to enable GPU supported ?

**Comment by asimshankar** [comment]
@tanguofu : Adding `--config=cuda` to your `bazel build` command should enable GPU support. So, in this case it would be:

```sh
bazel build --config=cuda tensorflow/examples/label_image/...
```

Hope that helps. Let us know either way. Thanks.

**Comment by tanguofu** [comment]
@asimshankar  
i build build_pip_package is ok  
`./configure with cuda `
`bazel build -c opt --config=cuda --jobs 2 //tensorflow/tools/pip_package:build_pip_package`

but when run 
`bazel build --config=cuda --jobs 2 tensorflow/examples/label_image/label_image`
come to:
_ERROR: /home/tanguofu/.cache/bazel/_bazel_tanguofu/5e46183ef599b405375ab0f36c679e7e/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/tanguofu/.cache/bazel/_bazel_tanguofu/5e46183ef599b405375ab0f36c679e7e/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/tanguofu/.cache/bazel/_bazel_tanguofu/5e46183ef599b405375ab0f36c679e7e/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/tanguofu/.cache/bazel/_bazel_tanguofu/5e46183ef599b405375ab0f36_

so which tf version do you build success ?
`
bazel build --config=cuda tensorflow/examples/label_image/..
`
and mine is mater ,the head git log is : 
_tanguofu@tanguofu-ThinkPad-T450:~/workspace/tensorflow$ git log
commit 4e8497dcdb7918082732c01cf777f3559fc8168b
Merge: ef2ca7f ae36978
Author: drpngx <drpngx@users.noreply.github.com>
Date:   Sun Oct 23 14:36:54 2016 -0700

    Merge pull request #5135 from villasv/master
    
    Option to config python lib path from env var_

**Comment by firolino** [comment]
Did you reboot your machine or restart the bazel daemon after ./configure and pip build? If yes, it might be related to [#4705](https://github.com/tensorflow/tensorflow/issues/4705) and [#4841](https://github.com/tensorflow/tensorflow/issues/4841)

**Comment by asimshankar** [comment]
@tanguofu : Could you also provide details on what happened with the `./configure` script? From the bazel errors, it seems that CUDA wasn't enabled with `./configure`.

**Comment by asimshankar** [comment]
Also, could you try with `bazel build -c opt --config=cuda //tensorflow/examples/label_image/...`?

**Comment by tanguofu** [comment]
`bazel build -c opt --config=cuda //tensorflow/examples/label_image/... ` also came to same error 

## and the output of ./configure is : 
`
### tanguofu@tanguofu-ThinkPad-T450:~/workspace/tensorflow$ ./configure 
~/workspace/tensorflow ~/workspace/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3.5
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]
 /usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: /usr/bin/gcc-4.9
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to CUDA 7.5 toolkit. /usr/local/cuda/lib64/libcudart.so.7.5 cannot be found
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-7.5
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-7.5]: /home/tanguofu/workspace/cudnn/cuda
libcudnn.so resolves to libcudnn.5
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
WARNING: failed to remove one or more convenience symlinks for prefix 'bazel-':
  bazel-out: /home/tanguofu/workspace/tensorflow/bazel-out (Directory not empty).
.............
WARNING: /home/tanguofu/workspace/tensorflow/tensorflow/contrib/cmake/build/grpc/src/grpc/third_party/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/tanguofu/workspace/tensorflow/tensorflow/contrib/cmake/build/grpc/src/grpc/third_party/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
`

@firolino  its always ok when i build pip_package with cuda， so i think there is no relation about  #4705 and #4841

do you have build label_image  sucessfully with cuda ?
thanks !

**Comment by asimshankar** [comment]
Glad it worked out. If you have any insight into what may have been broken in the previous checkout, do share. 

But since it seems things are working when you start from a clean slate, I'm going to close this issue out. Feel free to reopen if I'm mistaken. Thanks!
