### ISSUE TITLE
tf.image.non_max_suppression does not return a dynamic valid detection number after converting to TFLite models

### ISSUE THREAD

**Issue by zldrobit** [tensorflow/tensorflow#51629]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1/2.5.0/2.6.0

### 2. Code
https://colab.research.google.com/drive/1F4L9cdlhkxKHe70_5_H2SOAlH9Zl-jn-?usp=sharing

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

In eager mode, after NMS, the valid detection number is zero. 
After conversion to the TFLite model, the shape of the `valid_detection` is always `100`.
And I checked that `tf.shape` works flawlessly after converting to TFLite models in https://colab.research.google.com/drive/1dFeffpoi3Cd3ua6x6ny4k_-foPC8_mOe?usp=sharing

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I check that `tf.image.non_max_suppression_padded` could output the correct valid detection number.

**Comment by abattery** [comment]
In the first colab, print(keras_model(inp)) also gave the same result with the TFLite interpreter's result.

**Comment by abattery** [comment]
@srjoglekar246 could you take a look at the nms issue?

**Comment by srjoglekar246** [comment]
@zldrobit To help me debug can you share the model (with NMS) here? I can take a look at the ops & help debug.

**Comment by zldrobit** [comment]
@srjoglekar246 Of course. [The model](https://drive.google.com/file/d/131FsXY7SmDgy1-SMucm4-0cNS2gds9c7/view?usp=sharing) is an object detection model with `tf.image.non_max_suppression` op.
I extract the number of valid detections by `tf.shape(selected_indices)[0]` returned from the NMS https://github.com/zldrobit/yolov5/blob/fa277e5a54ecc572bfcff1b88808ce85de5bfede/models/tf.py#L409-L410.


I also add [the colab notebook](https://colab.research.google.com/drive/1MbP1jFogryuQIY581cPWNLa1wTTOXFIX?usp=sharing) to reproduce this model.

**Comment by mohantym** [comment]
Hi @zldrobit @ymodak  was able to replicate this issue in TF [2.6](https://colab.research.google.com/gist/mohantym/2a8cc0bc6c5aeadda3308e8bee77705c/tflite_nms_valid_det_nr.ipynb#scrollTo=oxhGNjJVDJ7m) and [2.5](https://colab.research.google.com/gist/mohantym/06a9b93aa041aa48b8fbd08376f55428/tflite_nms_valid_det_nr.ipynb#scrollTo=6NBf9_I--rHf) , got different error in TF [nightly](https://colab.research.google.com/gist/mohantym/1db4d79abb164577b91b19c98dcee1e0/tflite_nms_valid_det_nr.ipynb#scrollTo=6NBf9_I--rHf) .

**Comment by srjoglekar246** [comment]
@zldrobit You are right, I played around with your script & the padded version of NMS performs correctly. This might be because we map the TF implementation of padded NMS to TFLite's custom NMS op. This essentially 'fuses' the whole NMS procedure into a single op - this does not happen for `tf.image.non_max_suppression`, which results in a big graph that is kinda buggy.

The following code snippet seems to work:

```
def agnostic_nms(x):                                                                                                  
    boxes, classes, scores = x                                                                                        
    class_inds = tf.cast(tf.argmax(classes, axis=-1), tf.float32)                                                     
    scores_inp = tf.reduce_max(scores, -1)                                                                            
    selected_indices_padded, num_valid = tf.image.non_max_suppression_padded(                                                                     
        boxes, scores_inp, max_output_size=100, iou_threshold=0.45, score_threshold=0.25,
        pad_to_max_output_size=True)
    selected_inds = tf.slice(selected_indices_padded, tf.constant([0]), tf.reshape(num_valid, [1]))
    selected_boxes = tf.gather(boxes, selected_inds)                                                                  
    padded_boxes = tf.pad(selected_boxes,                                                                             
                          paddings=[[0, 100 - tf.shape(selected_boxes)[0]], [0, 0]],                         
                          mode="CONSTANT", constant_values=0.0)                                                       
    selected_scores = tf.gather(scores_inp, selected_inds)                                                            
    padded_scores = tf.pad(selected_scores,                                                                           
                           paddings=[[0, 100 - tf.shape(selected_boxes)[0]]],                                
                           mode="CONSTANT", constant_values=-1.0)                                                     
    selected_classes = tf.gather(class_inds, selected_inds)                                                           
    padded_classes = tf.pad(selected_classes,                                                                         
                            paddings=[[0, 100 - tf.shape(selected_boxes)[0]]],                               
                            mode="CONSTANT", constant_values=-1.0)                                                                                                                       
    return padded_boxes, padded_scores, padded_classes, num_valid
```

Just be mindful that the output order is changed, so you will have to look at the output details to confirm.

I will check if we can prioritize doing what we did for NMS padded for normal NMS as well (essentially the whole procedure of converting TF function to TFLite's fused NMS op), but we probably won't get to it this quarter.

Does using padded NMS atleast unblock your use-case?

**Comment by zldrobit** [comment]
@srjoglekar246 Thanks for your detailed explanation. I could use padded NMS in my use case, though it will break some backward compatibility in the project.

**Comment by alexdwu13** [comment]
@srjoglekar246 I tried your code snippet that uses `tf.image.non_max_suppression_padded` and was able to get the correct # of detections. However I'm unable to run this toy model on the TFlite GPU delegate:
```
./android_aarch64_benchmark_model --use_gpu=true --graph=nms.tflite                                                                                          
STARTING!
Log parameter values verbosely: [0]
Graph: [nms.tflite]
Use gpu: [1]
Loaded model nms.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Failed to apply GPU delegate.
```
I was under the impression that `tf.image.non_max_suppression_padded` was intended to specifically address the dynamic-sized tensor issue? 

Inspecting the model, I do notice a `While` operation. Could that be the culprit?
![image](https://user-images.githubusercontent.com/20094729/136872431-e8e49a15-2740-47a6-b6ab-c31cdbe60aa7.png)

Model:
[nms.tflite.zip](https://github.com/tensorflow/tensorflow/files/7326062/nms.tflite.zip)

To reproduce:
https://colab.research.google.com/drive/1F4L9cdlhkxKHe70_5_H2SOAlH9Zl-jn-?usp=sharing

**Comment by pkgoogle** [comment]
Hi @zldrobit, have the above merged PRs fix this issue?
