### ISSUE TITLE
Document XLA core functionality

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#51634]
## URL(s) with the issue:

https://www.tensorflow.org/xla/operation_semantics

## Description of issue (what needs changing):

There are references throughout the XLA docs to various core types that aren't fully documented. These include `XlaBuilder`, `XlaOp`, `XlaComputation` and `Parameter`. There may be others. It would be really helpful if these were documented.

### Clear description

Ideally there would be comprehensive API docs including all public functionality, how and why to use each, but anything in this direction would be most appreciated.

### Correct links

Where they exist

### Parameters defined

No

### Returns defined

No

### Raises listed and defined

No

### Usage example

Some

### Request visuals, if applicable

I don't know. I don't think they're crucial. Don't know if they'd help.

### Submit a pull request?

No

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you please look into this issue.

**Comment by Saduf2019** [comment]
@joelberkeley 
Please feel free to submit a pr with the changes expected.

**Comment by joelberkeley** [comment]
@Saduf2019 I can't because I don't know how the functionality works

**Comment by hohilwik** [comment]
I am not sure where to make the pull request though. The documentation folder seems to have been moved. 
@Saduf2019 If you could suggest something, and maybe assign this issue to me

**Comment by joelberkeley** [comment]
this might be it tensorflow/compiler/xla/g3doc/operation_semantics.md

**Comment by hohilwik** [comment]
Alright, I'll work on it then

**Comment by hohilwik** [comment]
XLA documentation uses different markdown from github so it took me a while to figure out. Sorry about that. Will submit PR in a day or two

**Comment by joelberkeley** [comment]
hi @hohilwik how did it go?
