### ISSUE TITLE
Error in model.fit

### ISSUE THREAD

**Issue by old-school-kid** [tensorflow/tensorflow#51633]
Made a Tensorflow fuctional API model on top of  TFAutoModelForSequenceClassification with 3 sentence as input. 

Training model directly on tokenized input raises
**ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {'(<class \'list\'> containing values of types {"<class \'tensorflow.python.framework.ops.EagerTensor\'>"})'}), (<class 'list'> containing values of types {"<class 'int'>"})**

If I convert it into numpy array it raises 
**ValueError: Data cardinality is ambiguous:**

`model(X_train[0])`  prduces the desired result in both cases but on training the model it raises errors.

Code can be found in this [notebook](https://colab.research.google.com/drive/1wsVVHiaqBF8joIEsP_XSMF35fnDQS19D?usp=sharing)

**Comment by sushreebarsa** [comment]
@old-school-kid Could you please have a look at the [link](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit), and similar[ issue1](https://stackoverflow.com/questions/64718185/efficiently-converting-for-model-fit), [issue2](https://stackoverflow.com/questions/58605279/tensorflow-value-error-in-model-fit-how-to-fix).Please let us know if it helps?Thanks!
