### ISSUE TITLE
Does a Docker container need to use the same exact libcuda version as the host's driver?

### ISSUE THREAD

**Issue by ricardofunke** [tensorflow/tensorflow#51641]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: libcuda reported version is: 450.142.0 kernel reported version is: 450.66.0
- GPU model and memory: GeForce RTX 2080 SUPER

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm trying to run an application that uses torch and tensorflow inside a docker container but I'm getting this error message:

"kernel version 450.66.0 does not match DSO version 450.142.0 -- cannot find working devices in this configuration"

The cuda-compat-11-0 version inside the container is 450.142.0 but the host driver version is 450.66.0.

As I can't find cuda-compat-11-0 version 450.66.0, I tried other versions around it but I got the same error.

I'm not able to change the Host driver, so my question is:

Do I really have to install the exact same version on the docker container in order to make it work, or am I doing something wrong?

Please help me understand this issue. Thanks in advance!

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @ricardofunke , Could you please look into answers of following similar[ issue.](https://github.com/tensorflow/tensorflow/issues/48722)
