### ISSUE TITLE
model.layers returns empty list

### ISSUE THREAD

**Issue by NihalHarish** [tensorflow/tensorflow#51645]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom Code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6
- Python version: `3.8.2`
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`model.layers` returns an empty list `[]`

Minimum reproducible example:

```
# Third Party
import numpy as np
from tensorflow.keras.layers import Concatenate, Dense
from tensorflow.python.keras.models import Model

class MyModel(Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.con = Concatenate()
        self.dense = Dense(10, activation="relu")

    def call(self, x):
        x = self.con([x, x])
        return self.dense(x)

if __name__ == "__main__":
   model = MyModel()
   print(model.layers)
```

When I attach a pdb and step through the code, I find that there is a change in the boolean logic here:
https://github.com/tensorflow/tensorflow/blob/002e5f47fa2ea99aa910ba83e66240c0cda8ff8a/tensorflow/python/keras/engine/base_layer.py#L2853

I suspect that is part of the breaking changes described [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0)

**Describe the expected behavior**
If the `model.layers` API is being deprecated, what is correct API to use? If not, what is the correct class to use to create layers.

**Comment by tilakrayal** [comment]
@NihalHarish ,

Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by NihalHarish** [comment]
The issue is present only with the `tf.keras` APIs and not `keras.` APIs.
Is there a plan to support both APIs for TF `2.6.x` while we transition to `2.7.x`

The code snippet shared above works fine if I change the import statements to:

```
from keras.layers import Concatenate, Dense
from keras.models import Model
```

**Comment by tilakrayal** [comment]
@NihalHarish ,
As mentioned above comment,all the keras related issues can be tracked in keras repo.Please feel free to post in keras repo.Thanks!
