### ISSUE TITLE
tensorflow-gpu==2.6 don't run on cuda by default 

### ISSUE THREAD

**Issue by sparrow84001** [tensorflow/tensorflow#51644]
dear all dev,

tensorflow-gpu==2.6 by default use oneAPI/oneDNN library 

put on by default cuda lib like previous version 2.5.

problem:

previous version , when import tensorflow as tf then 2nd message gave Successfully opened dynamic library cudart64_110.dll
but now 2.6 version don't saw that message and by default use intel integrated gpu (oneAPI/oneDNN library).

**Comment by mohantym** [comment]
Hi! @sparrow84001  , 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue.

**Comment by sparrow84001** [comment]
[

https://user-images.githubusercontent.com/37022413/130611931-760cbb11-c6f2-4797-8b91-a5d2a3c2107d.mp4

](url)

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you please look into this feature request.

**Comment by Saduf2019** [comment]
@sparrow84001 
This is not replica table, kindly use colab to run your code and let us know if you face any issues.
