### ISSUE TITLE
Cannot load model checkpoints: Two checkpoint references resolved to different objects

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorflow#51640]
I am trying to load model checkpoints saved during training. My model has custom layers and the full implementation can be found [here](https://github.com/AdityaKane2001/regnety/issues/15). 

My model looks as follows:
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
PreStem (PreStem)            (None, 224, 224, 3)       0         
_________________________________________________________________
Stem (Stem)                  (None, 111, 111, 32)      992       
_________________________________________________________________
Stage_0 (Stage)              (None, 56, 56, 24)        4542      
_________________________________________________________________
Stage_1 (Stage)              (None, 28, 28, 56)        12390     
_________________________________________________________________
Stage_2 (Stage)              (None, 14, 14, 152)       277400    
_________________________________________________________________
Stage_3 (Stage)              (None, 7, 7, 368)         2567444   
_________________________________________________________________
Head (Head)                  (None, 1000)              369000    
=================================================================
Total params: 3,231,768
Trainable params: 3,210,920
Non-trainable params: 20,848
_________________________________________________________________
```

When I try to load the model checkpoint after initializing the model architecture, I get the following warning message with an error as described below. 

```
Two checkpoint references resolved to different objects (<regnety.models.blocks.Stage object at 0x7f3c2049e110> and <regnety.models.blocks.Stage object at 0x7f3c2058ed50>).
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.
...
(many such messages)
...
ValueError                                Traceback (most recent call last)
<ipython-input-4-0c1dca79eafe> in <module>()
      1 from regnety.models import RegNetY
      2 
----> 3 model = RegNetY("200mf", load_weights=True)
      4 
 
(long traceback)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1159     """
   1160     if not self.is_compatible_with(other):
-> 1161       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1162 
   1163   def most_specific_compatible_shape(self, other):

ValueError: Shapes (56,) and (24,) are incompatible
```
Gist [here](https://colab.research.google.com/gist/AdityaKane2001/424e9f482c52b2e205d344d6cc27a8d9/groupedconvissue.ipynb?authuser=5). 

Other info:

TF version: 2.6.0
Environment: Colab with GPU

**Comment by sushreebarsa** [comment]
@AdityaKane2001 Could you please have a look at the [link ](https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint?version=nightly) and similar [issue](https://github.com/tensorflow/models/issues/8892) .Please let us know if it helps?Thanks!

**Comment by AdityaKane2001** [comment]
@sushreebarsa 

I don't think the issue is relevant as none of them had the same issue. But I'll try with the link and get back to you.

The link suggests that we must compile and load the relevant optimizer also when loading the weights. AFAIK that isn't the case with Keras models without custom layers.

**Comment by sushreebarsa** [comment]
@sanatmpa1 Was able to replicate this issue on colab using TF v[2.5](https://colab.research.google.com/gist/sushreebarsa/77833cb4ef97e25eb685ff0e6d7aceeb/groupedconvissue.ipynb#scrollTo=2ktbxlQ7klob),[2.6 ](https://colab.research.google.com/gist/sushreebarsa/8ab1cd8eb7b5cd3a37e98993cfa06ca8/groupedconvissue.ipynb#scrollTo=YmloOJA1cd4i)and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/e59d3712ab7003365176c67c714d84cf/untitled403.ipynb) ,please find the attached gists . Thanks!
