### ISSUE TITLE
How to wrap a CuPy function inside a function decorated by tf.function

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#51642]
I have a CuPy function tweaking TF tensor as follows:
TF tensor => dlpack => CuPy device array => apply some CuPy functions => CuPy device array => dlpack => TF tensor.

The code will work in eager mode, but once I decorate the function with tf.function, it won't work.

```
dlcapsule = tf.experimental.dlpack.to_dlpack(x)
InvalidArgumentError: The argument to `to_dlpack` must be a TF tensor, not Python object
```

I believe the general question should be: how to wrap up a python function calling TF tensor and also returning TF tensor in graph mode? Thanks.

**Comment by tilakrayal** [comment]
@llodds ,
In order to expedite the trouble-shooting process, could you please provide a complete code and tensorflow you are using.Thanks!

**Comment by llodds** [comment]
@tilakrayal 

As requested:

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # suppress tf messages
os.environ['TF_GPU_THREAD_MODE'] = 'gpu_private' # GPU has dedicated CPU threads

import tensorflow as tf
# so we know exactly the GPU memory usage
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
    
import cupy as cp
# conversion functions between tensorflow and cupy
def tf2cp(x):
    dlcapsule = tf.experimental.dlpack.to_dlpack(x)
    return cp.fromDlpack(dlcapsule)
def cp2tf(x):
    dlcapsule = x.toDlpack()
    return tf.experimental.dlpack.from_dlpack(dlcapsule)

# now, test how to use cupy with distributed TF
import numpy as np
X = np.random.random_sample((100, 128, 128, 128))
Y = np.random.random_sample((100, 128, 128, 128))
dataset = tf.data.Dataset.from_tensor_slices((X, Y))
dataset = dataset.shuffle(50, reshuffle_each_iteration=True)
dataset = dataset.batch(10, drop_remainder=True).prefetch(tf.data.AUTOTUNE)
strategy = tf.distribute.MirroredStrategy()
dataset_dist = strategy.experimental_distribute_dataset(dataset)


def simple_cupy_op(X, Y):
    X_cp = tf2cp(X)
    Y_cp = tf2cp(Y)
    Y_cp = X_cp + Y_cp
    X = cp2tf(X_cp)
    Y = cp2tf(Y_cp)
    
@tf.function
def simple_cupy_op_dist(X, Y):
    strategy.run(simple_cupy_op, args = (X, Y))
    
for X, Y in dataset_dist:
    simple_cupy_op_dist(X, Y)
```

Error message:
```
    ./test_cupy_with_dist_TF.py:41 simple_cupy_op_dist  *
        strategy.run(simple_cupy_op, args = (X, Y))
    ./test_cupy_with_dist_TF.py:33 simple_cupy_op  *
        X_cp = tf2cp(X)
    ./test_cupy_with_dist_TF.py:15 tf2cp  *
        dlcapsule = tf.experimental.dlpack.to_dlpack(x)
    /hpc/apps/pyhpc/dist/conda/x86_64/envs/cuda-11.0/lib/python3.8/site-packages/tensorflow/python/dlpack/dlpack.py:45 to_dlpack  **
        return pywrap_tfe.TFE_ToDlpackCapsule(tf_tensor)

    InvalidArgumentError: The argument to `to_dlpack` must be a TF tensor, not Python object
```

Thanks!

**Comment by mdanatg** [comment]
CuPy, like NumPy, is dependent on a Python runtime to run. When executing a tf.function, there is no such Python runtime - all ops are compiled into a graph that is executed inside the TF executor, which isolated from Python.

To mix such Python-reliant ops into the TF graph, you can use [py_function](https://www.tensorflow.org/api_docs/python/tf/py_function):

```
@tf.function
def simple_cupy_op(X, Y):
    tf.py_function(simple_cupy_op, ...)
```

cc @yuefengz 

Note however that `py_function` code is not portable, and I don't think it will work well with tf.distribute. For use with tf.function / tf.distribute, my advice would be to rewrite the CuPy code into TF ops. Fundamentally, they should be similar - in both cases you'd run GPU kernels.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
