### ISSUE TITLE
My libnnappi_delegate.so is debug or release

### ISSUE THREAD

**Issue by yahuuu** [tensorflow/tensorflow#51652]
**System information**
- OS Platform: ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MI 9(mobile phone） 
- TensorFlow installed from: Source 
- TensorFlow version: 2.5.0
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla K40m 

**Describe the problem**
I use bazel to build libnnappi_delegate.so.
Command :
```
bazel build -c opt  --config=android_arm64  --cxxopt="-std=c++11"  --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     //tensorflow/lite/delegates/nnapi:nnapi_delegate 
```
get libnnappi_delegate.so .
How can I know the shared library is "Debug" and "Release"?

**Comment by mohantym** [comment]
Hi @yahuuu  !This does not seem to be  a bug or feature request, for any further queries you may open this issue in [TF discussion forum ](https://discuss.tensorflow.org/)as there is a larger community there.Thank you!
