### ISSUE TITLE
Upgrade TF to CUDA 11.4 and cuDNN 8.2 

### ISSUE THREAD

**Issue by pkanwar23** [tensorflow/tensorflow#51659]
Upgrade TF to CUDA 11.4 and cuDNN 8.2

**Comment by karanveersingh5623** [comment]
What are the steps to upgrade TF to CUDA 11.4 and cuDNN 8.2 using docker image 
 tensorflow/tensorflow:latest-devel-gpu

**Comment by pkanwar23** [comment]
We do plan on adding support for cuda 11.4 and cudnn 8.2 in a future release. If you want to add support to your local build, you'll need to build from source.

**Comment by abwilf** [comment]
Hi was there ever an update on this?  I've been trying to pip install tensorflow within this image, `docker://nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04`,  but I keep getting these errors: https://github.com/google/jax/issues/7239, https://github.com/google/jax/discussions/6843. It'd be really helpful if you could put out an image with tensorflow and jax already inside!

**Comment by SuryanarayanaY** [comment]
Hi all,
As per announcement at [TF-Forum](https://discuss.tensorflow.org/t/cuda-updated-to-11-8/12942) TF nightly(2.12V) now extended support to CUDA 11.8 .With this the purpose of opening the issue resolved?

**Comment by SuryanarayanaY** [comment]
Hi @pkanwar23 ,

Currently for TF2.12v/ tf-nightly versions CUDA upgraded to 11.8 from 11.2 earlier. Shall we mark this as resolved now?

Thanks!
