### ISSUE TITLE
Error: 'tf.UnsortedSegmentJoin' op is neither a custom op nor a flex op

### ISSUE THREAD

**Issue by puggxlii** [tensorflow/tensorflow#51654]
### 1. System information

- OS Platform and Distribution : google colab
- TensorFlow installation (pip package or built from source): tensorflow 2.6 gpu
- TensorFlow library: 2.6.0

### 2. Code

converter = tf.lite.TFLiteConverter.from_saved_model('translator') # path to the SavedModel directory
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

The output from the converter invocation
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-78-a4bd67ed5756> in <module>()
      4 converter.optimizations = [tf.lite.Optimize.DEFAULT]
----> 5 tflite_model = converter.convert()

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    311       for error_data in _metrics_wrapper.retrieve_collected_errors():
    312         converter_error.append_error(error_data)
--> 313       raise converter_error
    314 
    315   return _run_toco_binary(model_flags_str, toco_flags_str, input_data_str,

ConverterError: <unknown>:0: error: loc(callsite(callsite(callsite(callsite("RaggedSegmentJoin/UnsortedSegmentJoin@__inference_detokenize_676" at "StatefulPartitionedCall@__inference_restored_function_body_185084") at "StatefulPartitionedCall_2@__inference___call___187672") at "StatefulPartitionedCall@__inference_signature_wrapper_188041") at "StatefulPartitionedCall_4")): 'tf.UnsortedSegmentJoin' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall_4"): called from
<unknown>:0: note: loc(callsite(callsite(callsite(callsite("RaggedSegmentJoin/UnsortedSegmentJoin@__inference_detokenize_676" at "StatefulPartitionedCall@__inference_restored_function_body_185084") at "StatefulPartitionedCall_2@__inference___call___187672") at "StatefulPartitionedCall@__inference_signature_wrapper_188041") at "StatefulPartitionedCall_4")): Error code: ERROR_NEEDS_CUSTOM_OPS
<unknown>:0: error: loc(callsite(callsite(callsite(callsite("RaggedSegmentJoin_1/UnsortedSegmentJoin@__inference_detokenize_676" at "StatefulPartitionedCall@__inference_restored_function_body_185084") at "StatefulPartitionedCall_2@__inference___call___187672") at "StatefulPartitionedCall@__inference_signature_wrapper_188041") at "StatefulPartitionedCall_4")): 'tf.UnsortedSegmentJoin' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall_4"): called from
<unknown>:0: note: loc(callsite(callsite(callsite(callsite("RaggedSegmentJoin_1/UnsortedSegmentJoin@__inference_detokenize_676" at "StatefulPartitionedCall@__inference_restored_function_body_185084") at "StatefulPartitionedCall_2@__inference___call___187672") at "StatefulPartitionedCall@__inference_signature_wrapper_188041") at "StatefulPartitionedCall_4")): Error code: ERROR_NEEDS_CUSTOM_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom 
Custom ops: UnsortedSegmentJoin
Details:
	tf.UnsortedSegmentJoin(tensor<?x!tf.string>, tensor<?xi64>, tensor<i32>) -> (tensor<1x!tf.string>) : {Tindices = i64, Tnumsegments = i32, device = "", separator = " "}
	tf.UnsortedSegmentJoin(tensor<?x!tf.string>, tensor<?xi64>, tensor<i32>) -> (tensor<?x!tf.string>) : {Tindices = i64, Tnumsegments = i32, device = "", separator = " "}

I was trying to convert the model from https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/transformer.ipynb
to a tflite model. The issue could be reproduced by running this in google colab and add 
converter = tf.lite.TFLiteConverter.from_saved_model('translator') # path to the SavedModel directory
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
at the bottom.

**Comment by abattery** [comment]
@MeghnaNatraj could you take a look at this flex op addition?

**Comment by MeghnaNatraj** [comment]
Support added in https://github.com/tensorflow/tensorflow/commit/13196b41f38779020459fa3e64fa65a9ad60c641
