### ISSUE TITLE
[unexpected keyword argument 'syntax'] occurs on Ubuntu 16.04 with protobuf 3 of 4e8497d by installing from source

### ISSUE THREAD

**Issue by zhouphd** [tensorflow/tensorflow#5168]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
#4

### Environment info
Operating System: Ubuntu 16.04
Installed version of CUDA and cuDNN: CUDA 8 & CUDNN 5.1

1. The commit hash (`git rev-parse HEAD`)
Download the zip file by http. Version:[4e8497d](https://github.com/tensorflow/tensorflow/commit/4e8497dcdb7918082732c01cf777f3559fc8168b)

2. The output of `bazel version`
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110

### What other attempted solutions have you tried?
Change /usr/bin/protoc & /usr/include/google version from 2 to 3.

### Logs or other output that would be helpful
[2,290 / 2,578] Still waiting for 196 jobs to complete:
      Running (standalone):
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 2425.533s, Critical Path: 2122.33s

####Problem 

python -c "import tensorflow"

I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/name/.local/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"m\n\x0eResourceHandle\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB4\n\x18org.tensorflow.frameworkB\x13ResourceHandleProtoP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by drpngx** [comment]
Could you post your _pb2.py files?

**Comment by zhouphd** [comment]
Thx, @drpngx  
[resource_handle_pb2.txt](https://github.com/tensorflow/tensorflow/files/549427/resource_handle_pb2.txt)

pls, :)

**Comment by drpngx** [comment]
It looks like you're loading a python protobuf that doesn't have "syntax". Could you look at https://github.com/tensorflow/tensorflow/issues/57?

**Comment by zhouphd** [comment]
While, I tried, still not work:

```
$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> print google.protobuf.__version__
3.1.0
```

```
$ protoc --version
libprotoc 3.1.0
```


```
$ pip show numpy protobuf
Name: numpy
Version: 1.11.2
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: NumPy Developers
Author-email: numpy-discussion@scipy.org
Installer: pip

Name: protobuf
Version: 3.1.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
Installer: pip
```

After pip uninstall protobuf, pip uninstall tensorflow, & reComplied the tensorflow-master/configure, 
according to [os_setup](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#create-the-pip-package-and-install) , still not work, but release no module problem:

```
$ python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
```

**Comment by drpngx** [comment]
you need to pip re-install the tensorflow:

```
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip install /tmp/tensorflow_pkg/tensorflow-*.whl 
```

**Comment by zhouphd** [comment]
OK, afer series opts, mainly about solution is protoc need to update to version 3 & replace apt install libprotoc by download from https://github.com/google/protobuf, & rebuild tensorflow. 

this issue may be cause by the libprotoc of ubuntu version 2 but python protobuf version 3 compliing.

Anyway, thx @drpngx
