### ISSUE TITLE
Nan gradient when calling tf.gradients() more than 1 time in graph mode for TF Dormand-Prince solver

### ISSUE THREAD

**Issue by MIHIRKHAMBETE** [tensorflow/tensorflow#51688]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

(Please see jupyter notebook in the attached ZIP file)

I notice that if `tf.gradients() ` is called more than one time inside a `@tf.function`-decorated function `ode_gradient_graph()` (graph mode) when using a Tensorflow Dormand-Prince ODE solver, the later gradients can evaluate incorrectly to have NaN values. Switching the order of the tf.gradients()` calls allows computation of the second gradient but not the first. 

However, all gradients are computed normally in eager mode using GradientTape with `persistent=True`. 

**Describe the expected behavior**

`tf.gradients()` should return a non-NaN answer for the second gradient computed inside the `@tf.function`-decorated function `ode_gradient_graph()`. Additionally, when parameters `ys` and `xs` to `tf.gradients()` are both single tensorflow tensors,` tf.gradients()` should have the same behavior as `tf.GradientTape.gradient()`.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**
See attached ZIP file for notebook
[ode_gradients_bug.ipynb.zip](https://github.com/tensorflow/tensorflow/files/7049692/ode_gradients_bug.ipynb.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached. N/A

**Comment by tilakrayal** [comment]
@MIHIRKHAMBETE,
I tried to execute the code on the latest tensorflow version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/58761b64381652055719f50ef088a467/2-11nightly.ipynb) and let us know if the issue still persists. Thank you!
