### ISSUE TITLE
TFLite for conv1D and DepthwiseConv1D

### ISSUE THREAD

**Issue by wenjingyang** [tensorflow/tensorflow#51692]
**System information**
- OS Platform and Distribution  Linux Ubuntu 16.04:
- TensorFlow installed from binary:
- TensorFlow version (tf-nightly 2.7.0.dev20210824):

The h5 is:
![image](https://user-images.githubusercontent.com/4407779/130913616-d18620ec-cdab-45e5-8db8-dc25849cc155.png)
When I convert it to tflite. It becomes 
![image](https://user-images.githubusercontent.com/4407779/130913708-57624af5-60d8-4551-a7b2-3cd3b1413c04.png)

My input is only a speech spectrum. I have to add one additional dim if I use conv2d. So I think conv1d is enough and use conv1d/depthwiseconv1d to generate model.  But the problem is that I still get conv2d and ds2d in tflite. It isn't helpful to deal with my high MIPS issue if it is still conv2d.  Any idea on it? Thanks.

**Comment by abattery** [comment]
For your information, this is not a bug since the generated graph also works.

**Comment by wenjingyang** [comment]
My concern is that why it isn't CONV1D in tflite.  We can see a lot of reshape/expandim inside. Anyway, it could work. Thanks.

**Comment by karimnosseir** [comment]
Conv1D is implemented using conv2d as mentioned already. 

Thanks
