### ISSUE TITLE
Grappler graph optimizations may add nondeterministic behavior

### ISSUE THREAD

**Issue by jackyesf** [tensorflow/tensorflow#51716]
**System information**
- OS windows 10
- tensorflow-gpu==2.5.1
- python=3.7
- CUDA/cuDNN version: 11.2
- GPU model and memory: 471.68-desktop-win10-win11-64bit-international-dch-whql

**Got non-determinism on GPU.I found out it's the problem of Grappler graph optimizations,then i set this option false,but the train is more slower than cpu.**
options = {'implementation_selector':False}
tf.config.optimizer.set_experimental_options(options)

https://github.com/tensorflow/community/blob/master/rfcs/20210119-determinism.md#grappler-changes
**I found out this document may help me to fix this problem ,but don't know how to disabled timeout with a RewriteConfig option on tensorflow-gpu==2.5.1.**

**Comment by sanatmpa1** [comment]
@jackyesf,

Can you share a simple reproducible code to expedite the trouble-shooting process? Thanks!
