### ISSUE TITLE
How to modify ckpt value

### ISSUE THREAD

**Issue by qinhuan** [tensorflow/tensorflow#51713]
### First,
I can get variable name by  `tf.train.list_variables('./ckpt/ckpt-30')`

### Second,
[https://www.tensorflow.org/guide/checkpoint#manual_checkpointing](url)
I can get value by :
```
reader = tf.train.load_checkpoint('./ckpt/ckpt-30')
shape_from_key = reader.get_variable_to_shape_map()
dtype_from_key = reader.get_variable_to_dtype_map()
sorted(shape_from_key.keys())
key = 'net/l1/kernel/.ATTRIBUTES/VARIABLE_VALUE'
reader.get_tensor(key)
```

result is `array([[4.715253 , 4.832879 , 4.754512 , 4.891385 , 4.8498716]], dtype=float32)`

### So
I want to modify ckpt value,  but I don't know how to do it.

```
model = Model()
ckpt = tf.train.Checkpoint(model=model)
status = ckpt.restore('./ckpt/ckpt-30')

```
Can I get the value from ckpt, and modify value, and  ckpt.save() or ckpt.write(),   get a new ckpt file?
Please show me simple code, thanks!!!!!!!

**Comment by qinhuan** [comment]
> If this is the case I thin the best and most convenient solution is to load the model form the checkpoint ,modify the layer with set_weights() and save the model in a checkpoint

I want to merge conv and BN manually, so I need load checkpoint and modify some value of conv,  delete BN value and save a new checkpoint. How can I implement this operation？ Thank you for reply!

**Comment by mohantym** [comment]
Hi @qinhuan !
This is not a bug or feature request, for any further queries you may open this issue in TF discussion[ forum](https://discuss.tensorflow.org/) as there is a larger community there.Thank you!

**Comment by qinhuan** [comment]
> If this is the case I thin the best and most convenient solution is to load the model form the checkpoint ,modify the layer with set_weights() and save the model in a checkpoint

@vulkomilev Thanks for reply!  I  found a way to solve my problem.
first, 
```
model = Model()
dir(model)
model.variables
```

and we need inputs, and inference; then `model.variables` will have values.
```
inputs=[tf.random.uniform([10000,3],dtype=tf.float32)*60.0, tf.constant([10000],dtype=tf.int32)]
_ = model(inputs)
type(model.variables) 
<class 'list'>
```
load ckpt file, `model.variables `will be changed;
```
ckpt = tf.train.Checkpoint(model=model)
status = ckpt.restore('./ckpt/ckpt-30')
```

now, we can modify the value by` assgin`.

```
tmp1 = tf.zeros([8])
<tf.Tensor: shape=(8,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>
model.variables[58].assign(tmp1)
ckpt.save('/path/to/save/ckpt')
```
