### ISSUE TITLE
Separable Conv2D allows dilation_rate!=1 and strides !=1

### ISSUE THREAD

**Issue by pokecheater** [tensorflow/tensorflow#51710]
Hey Tensorflow Community :-),

Nothing serious :).

I just noticed in tensorflow 2.4 (sry can not update to 2.7 currently since I am stuck to this version because of other compatibilty issues, so I can't tell if this also affects your newest version) that the layer Separable Conv2D states in it's documentations that if I assign another value for the dilation rate than 1 the strides are not to be allowed to have another value than 1 and vice versa. 

_dilation_rate: An integer or tuple/list of 2 integers, specifying the dilation rate to use for dilated convolution. Currently, specifying any dilation_rate value != 1 is incompatible with specifying any strides value != 1._

https://keras.io/api/layers/convolution_layers/separable_convolution2d/

But in fact it is possible to set both parameters with values > 1. 
(Since this is also true (and you will get an exception if you try to apply other values than 1 for both parameters) for the normal covolutional layers I think it is either a bug or a documentation copycat issue.)

Cheers :)

**Comment by pokecheater** [comment]
@tilakrayal

**Comment by sanatmpa1** [comment]
@pokecheater,
 
This looks like as an issue related to keras component. Can you please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see; [https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by sanatmpa1** [comment]
@pokecheater,

As you have already opened an issue with `Keras` repo, please confirm if we are good to close this issue here? Thanks!

**Comment by ymodak** [comment]
The docs are fixed with [b2f6e34](https://github.com/keras-team/keras/commit/81b6a9b369234aff58a975c5a9c5e0101b6f93a9) Thanks!
