### ISSUE TITLE
TensorRT model outputs/performance keeps changing across conversions

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tensorflow/tensorflow#51719]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TensorFlow 2.6 , 2.7.0.dev20210825
- Python version: 3.7
- CUDA/cuDNN version: 11.0/8.0 and / 11.2/8.1
- TensorRT: LIBNVINFER=7.2.2-1
- GPU model and memory: v100 16GB

**Describe the current behavior**
I have been trying to convert an object detection model using the TensorRT converter.
I can successfully convert the model and also get the desired boost in latency while still maintaining the same outputs/performance. But more often or so, I see that my model shows degraded performance.

mAP score for `tf saved_model`: 40.3  (this does not change no matter how many times I run `tf.saved_model.save(...)`)
mAP score for `tf-trt saved_model`:  the results keep changing on each conversion [40.4, 36.0] (detailed metrics below)

```
conversion run 1 (FP16)
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.360
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.528
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.391
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.175
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.420
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.531
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.323
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.488
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.507
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.250
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.571
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.713
```

```
conversion run 2 (FP16)
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.404
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.598
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.434
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.220
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.453
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.575
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.333
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.522
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.549
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.331
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.610
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.732
```
This happens for both FP16 and FP32. And I have made sure that there is absolutely nothing that is changed/different in my environment across runs.

I am attaching the conversion logs for both the runs with
`TF_CPP_VMODULE=trt_engine_op=2,convert_nodes=2,convert_graph=2,segment=2,trt_shape_optimization_profiles=2,trt_engine_resource_ops=2`

**Describe the expected behavior**
Consistent outputs/performance across conversions

**Standalone code to reproduce the issue**
[`saved_model` download_link](https://github.com/srihari-humbarwadi/retinanet-tensorflow2.x/releases/download/v0.1.0/mscoco-retinanet-resnet50-640x640-30x-256.zip)

code to convert 
```python
import os
import sys

import tensorflow as tf

os.environ['TF_TRT_ALLOW_NMS_TOPK_OVERRIDE'] = '1'
print(tf.__version__)

physical_devices = tf.config.list_physical_devices('GPU')
[tf.config.experimental.set_memory_growth(x, True)
 for x in physical_devices]

PRECISION = 'FP16'

params = tf.experimental.tensorrt.ConversionParams(
    minimum_segment_size=10,
    precision_mode=PRECISION)


input_saved_model_dir = 'mscoco-retinanet-resnet50-640x640-30x-256'
output_saved_model_dir = 'tf-trt-' + PRECISION
print('Using saved_model from : ', input_saved_model_dir)

converter = tf.experimental.tensorrt.Converter(
    input_saved_model_dir=input_saved_model_dir,
    use_dynamic_shape=False,
    conversion_params=params)


def input_fn(steps=1):
    for i in range(steps):
        yield (
            tf.random.uniform([1, 640, 640, 3]), tf.constant(1, dtype=tf.int32),
            tf.ones([1, 4]))


converter.convert()
converter.build(input_fn=input_fn)

print('Saving converted saved_model to : ', output_saved_model_dir)
converter.save(output_saved_model_dir)
```

[36.0_run.log](https://github.com/tensorflow/tensorflow/files/7068995/36.0_run.log)
[40.4_run.log](https://github.com/tensorflow/tensorflow/files/7068996/40.4_run.log)

I cannot submit a standalone colab notebook because my model uses `tf.image.combined_non_max_suppression` which needs the TensorRT `batchedNMSPlugin` to run and that cannot be loaded in colab since
colab needs to have tensorrt python client installed to call so that it can load the plugin
```
import tensorrt as trt
trt.init_libnvinfer_plugins(None, '')
```
which is not possible currently https://github.com/googlecolab/colabtools/issues/1844

**Comment by mohantym** [comment]
Hi @Saduf2019 , Could you please look at this issue. providing gist in [2.5 ](https://colab.research.google.com/gist/mohantym/aa709eed3ee2ff0913f5eda6a01e57a3/github_51719_tf_2-6.ipynb#scrollTo=iYyjwZaCx17R),[2.6](https://colab.research.google.com/gist/mohantym/c7699da28d8c60b24d17e1c75027c3a8/github_51719_tf_2-6.ipynb) and [2.7](https://colab.research.google.com/gist/mohantym/78421807c8baf9165de02f0fcf55f57d/github_51719_tf_2-6.ipynb#scrollTo=5M1IfJiD0hDq) for reference. Session is crashing in TF 2.5.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
