### ISSUE TITLE
Several links to the github code are broken in https://www.tensorflow.org/

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#51726]
As the title says, some links from https://www.tensorflow.org/ to the corresponding code on github are broken.
[here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Activation) an example. 
I believe this is due to the removal of the `python` module.

Also, some other links have a line offset, such as [Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D).
This is probably because some imports were removed.

**Comment by mohantym** [comment]
Hi @Saduf2019 ,could you please look into this  issue?

**Comment by Saduf2019** [comment]
@NEGU93 
I have opened the links shared and all of them work as expected, can you please share a screen shot of the issue reported.

**Comment by NEGU93** [comment]
Steps to reproduce:
1. Go [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Activation)
2. Click on the `View source on GitHub` button.
3. The button will take you to [this](https://github.com/keras-team/keras/tree/master/keras/layers/core.py#L389-L430) broken link.

**Comment by Saduf2019** [comment]
@NEGU93 
A CL is created to resolve this, thank you for reporting.

**Comment by NEGU93** [comment]
Your welcome! 
It was not the only example I found, there are a few and for sure many more I did not found yet.

I think since version 2.6 or 2.5 the `tf.keras.python` module was removed (and items moved to another place) that is my theory and it may help to track the broken links.

**Comment by Saduf2019** [comment]
@NEGU93 
Please move this to closed status as the issue has been resolved,and feel free to share any further issues [broken links]
