### ISSUE TITLE
Build stuck at Linking _pywrap_tensorflow_internal.so step

### ISSUE THREAD

**Issue by akkshay0107** [tensorflow/tensorflow#51723]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): From source
- TensorFlow version: 2.6.0
- Python version: 3.9.2
- Installed using virtualenv? pip? conda?: Bazel
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): VS 2019

**Describe the problem**

The build gets stuck at "Linking tensorflow/python/ _pywrap_tensorflow_internal.so" step. It takes more than 5000s and never completes the build

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.6
python ./configure.py
bazel --output_user_root=C:\tfb build --jobs=3 --config=opt --define=no_tensorflow_py_deps=true /tensorflow/tools/pip_package:build_pip_package
```
In the configuration , I have chosen all the default options

**Any other info / logs**
![2021-08-27 21_22_53-Window](https://user-images.githubusercontent.com/64022998/131206786-a30fa5fc-213c-4b0c-b9b4-1fa40ccfcdb2.png)

**Comment by mohantym** [comment]
Hi @akkshay0107! you have mentioned OS you are using Windows 10 , but installation procedure is different. Could you confirm you are following below procedure for [windows ](https://www.tensorflow.org/install/source_windows) , for Ubuntu the  steps can be found [here](https://www.tensorflow.org/install/source),

**Comment by akkshay0107** [comment]
I have followed all the steps given in https://www.tensorflow.org/install/source_windows . Due to RAM being less in my system I had to reduce the number of jobs and because my user folder contains a space I had to set the output root to a folder in C:\ drive.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look into this issue!

**Comment by sanatmpa1** [comment]
@akkshay0107,

You can take a look at this issue #27471 for reference, though in your case it haven't failed and just took longer time.Can you try modifying the configuration to disable `XLA JIT Support` if its enabled, and build again to see if its working fine?

Also check if the graphics card in your machine supports the corresponding cuda version as per this [link](https://www.tensorflow.org/install/source_windows#gpu)

**Comment by akkshay0107** [comment]
In ``configure.py`` there is no option to disable XLA JIT, do i have to disable it in the .bazelrc file manually? Also I dont have a GPU in my computer and have inputted "N" to this line in ``configure.py`` and so i dont use cuda / cudNN
```
Do you wish to build TensorFlow with CUDA support? [y/N]:
```

**Comment by akkshay0107** [comment]
@sanatmpa1 the build has worked after disabling XLA JIT but after that there is an installation error 
```
C:\tensorflow>bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg
Wed Sep 1 20:40:33 IST 2021 : === Preparing sources in dir: /tmp/tmp.Y95WQ31j0L
Unzipping simple_console_for_windows.zip to create runfiles tree...
c:\tensorflow\bazel-bin\tensorflow\tools\pip_package\build_pip_package: line 132: unzip: command not found
```
is there any way to fix this ?

**Comment by sanatmpa1** [comment]
@akkshay0107,

Can you update on what's the output you're getting for the commands `which unzip` and `unzip`?

**Comment by akkshay0107** [comment]
@sanatmpa1 

i get that unzip is not recognized as an internal or external command
![2021-09-08 22_02_49-](https://user-images.githubusercontent.com/64022998/132549146-e4fb4cb1-1107-4714-897d-55f1e3633cea.png)

**Comment by sanatmpa1** [comment]
@akkshay0107,

`unzip` is not a normal program in Windows. It won't work directly when using CMD as your shell. So you should install command line archiving programs like [unzip](http://gnuwin32.sourceforge.net/packages/unzip.htm) and add corresponding path to your environments. This is not an issue with TF and its a common windows error. Please try the same and check if its working. Thanks!

**Comment by akkshay0107** [comment]
It as started working. Thanks a lot !
