### ISSUE TITLE
Unable to save custom model using save_model, even though documentation states it is possible

### ISSUE THREAD

**Issue by microcoder-py** [tensorflow/tensorflow#51727]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Throws error

Unable to save function b'__inference_paraphrase_detector_1_layer_call_fn_2757942' because it captures graph tensor Tensor("dense_83/BiasAdd_3:0", shape=(16, 32), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`.

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Colab: https://colab.research.google.com/drive/11VGeylggSZ-0yb9CJmg3fE79CiRAvERX?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

No need for the database, even if you simply build the model with no training and try to save it, it throws the same error.

**Comment by sanatmpa1** [comment]
@microcoder-py,

Can you provide the sample data if possible, to reproduce the issue from our end? Thanks!

**Comment by microcoder-py** [comment]
HI, unable to attach file because GitHub doesn't support tsv files. However, I tried to save the weights and that happened just fine. I think the error is coming in because i have declared python lists inside my layers, and those python lists are inaccessible to the tf computation graph

**Comment by sanatmpa1** [comment]
@microcoder-py,

If you feel that the issue is already fixed, please feel free to move the issue to closed status. Thanks!

**Comment by DanBmh** [comment]
Had a similar error (`ValueError: Unable to save function b'__inference_my_model_layer_call_fn_85894' because it captures graph tensor Tensor("add:0", shape=(), dtype=int32) from a parent function which cannot be converted to a constant with 'tf.get_static_value'.`) with tf=2.7. 

In my case it could be solved by using `enable_eager_execution()` instead of `disable_eager_execution()` in the export script
