### ISSUE TITLE
Image transformations require SciPy. Install SciPy.

### ISSUE THREAD

**Issue by jackfrost1411** [tensorflow/tensorflow#51736]
I am running tensorflow with the help of miniforge3 on MacBook Pro M1.

I have followed the steps to install tensorflow on M1 from here: https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb

- TensorFlow version (use command below): tensorflow-mac 2.5.0
- Python version: 3.9
- Bazel version (if compiling from source):
- GPU model and memory: M1 8gb

ImportError                               Traceback (most recent call last)
/var/folders/k9/t0sd91511s16j207y0y2wps40000gn/T/ipykernel_91808/2572958566.py in <module>
      9 import scipy
     10 
---> 11 history = model.fit(
     12     train_generator,
     13     steps_per_epoch = 15,

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1131          training_utils.RespectCompiledTrainableState(self):
   1132       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
-> 1133       data_handler = data_adapter.get_data_handler(
   1134           x=x,
   1135           y=y,

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py in get_data_handler(*args, **kwargs)
   1362   if getattr(kwargs["model"], "_cluster_coordinator", None):
   1363     return _ClusterCoordinatorDataHandler(*args, **kwargs)
-> 1364   return DataHandler(*args, **kwargs)
   1365 
   1366 

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
   1152     adapter_cls = select_data_adapter(x, y)
   1153     self._verify_data_adapter_compatibility(adapter_cls)
-> 1154     self._adapter = adapter_cls(
   1155         x,
   1156         y,

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, shuffle, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    930     self._keras_sequence = x
    931     self._enqueuer = None
--> 932     super(KerasSequenceAdapter, self).__init__(
    933         x,
    934         shuffle=False,  # Shuffle is handed in the _make_callable override.

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    807     # Since we have to know the dtype of the python generator when we build the
    808     # dataset, we have to look at a batch to infer the structure.
--> 809     peek, x = self._peek_and_restore(x)
    810     peek = self._standardize_batch(peek)
    811     peek = _process_tensorlike(peek)

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/keras/engine/data_adapter.py in _peek_and_restore(x)
    941   @staticmethod
    942   def _peek_and_restore(x):
--> 943     return x[0], x
    944 
    945   def _handle_multiprocessing(self, x, workers, use_multiprocessing,

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/keras_preprocessing/image/iterator.py in __getitem__(self, idx)
     63         index_array = self.index_array[self.batch_size * idx:
     64                                        self.batch_size * (idx + 1)]
---> 65         return self._get_batches_of_transformed_samples(index_array)
     66 
     67     def __len__(self):

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/keras_preprocessing/image/iterator.py in _get_batches_of_transformed_samples(self, index_array)
    236             if self.image_data_generator:
    237                 params = self.image_data_generator.get_random_transform(x.shape)
--> 238                 x = self.image_data_generator.apply_transform(x, params)
    239                 x = self.image_data_generator.standardize(x)
    240             batch_x[i] = x

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/keras_preprocessing/image/image_data_generator.py in apply_transform(self, x, transform_parameters)
    861         img_channel_axis = self.channel_axis - 1
    862 
--> 863         x = apply_affine_transform(x, transform_parameters.get('theta', 0),
    864                                    transform_parameters.get('tx', 0),
    865                                    transform_parameters.get('ty', 0),

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/keras_preprocessing/image/affine_transformations.py in apply_affine_transform(x, theta, tx, ty, shear, zx, zy, row_axis, col_axis, channel_axis, fill_mode, cval, order)
    279     """
    280     if scipy is None:
--> 281         raise ImportError('Image transformations require SciPy. '
    282                           'Install SciPy.')
    283     transform_matrix = None

ImportError: Image transformations require SciPy. Install SciPy.

**Comment by mohantym** [comment]
Hi ! @jackfrost1411 , That is issue related to installation of Scipy.  Please uninstall and install Scipy and check the issue again. Thank you.

**Comment by devnev39** [comment]
This kind of error on m1 macbooks usually are only solved by reinstalling the tensorflow. Just remove the tensorflow that you have installed and follow the instruction on the apple site ->

https://developer.apple.com/metal/tensorflow-plugin/

After doing all the steps, you also need to install tensorboard also using pip in the same environment.

**Comment by mohantym** [comment]
Thanks  @jackfrost1411 ! Could you close  the issue then!

**Comment by gopalkalpande** [comment]
[This link helped me](https://github.com/jasmcaus/opencv-course/pull/26#issuecomment-981225561)

1. reinstall scipy  
2. shutdown and reopen jupyter server. 

It worked for me. Thank you
