### ISSUE TITLE
Failed to get compute capability major for device: UNKNOWN ERROR (1); 0

### ISSUE THREAD

**Issue by Silvio-Ma** [tensorflow/tensorflow#51730]
Dear All,

I have installed tensorflow-cpu 2.6.0 on my anaconda. Both Tensorflow and Keras will be imported correctly, but running a cell containing them raises error:

> RuntimeError Traceback (most recent call last) in 1 from tensorflow.python.client import device_lib ----> 2 print(device_lib.list_local_devices())
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\client\device_lib.py in list_local_devices(session_config) 43 serialized_config = session_config.SerializeToString() 44 return [ ---> 45 _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config) 46 ]
> 
> RuntimeError: failed to get compute capability major for device: UNKNOWN ERROR (1); 0

**System information**
- Python 3.8.5 (Anaconda)
- Tensorflow 2.6.0
- keras 2.6.0
- Windows 7 64

Thank alot
Silvio

**Comment by sanatmpa1** [comment]
@Silvio-Ma,

> Both Tensorflow and Keras will be imported correctly, but running a cell containing them raises error:

Do you mean the import lines are throwing you this error, or after importing when you try running some other code, its throwing you this error?

Can you share a standalone code snippet to reproduce this issue, so that we can expedite the trouble shooting process?Thanks!

**Comment by Silvio-Ma** [comment]
Thanks for your consideration Sanatmpa, I'm really stuck.
No, the import lines return no error, they work fine:

```
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense,  Activation
from keras.utils import np_utils
```

This will run properly. And also when I run this cell:

`!pip show tensorflow
`
The result is:

> Name: tensorflow
> Version: 2.6.0
> Summary: TensorFlow is an open source machine learning framework for everyone.
> Home-page: https://www.tensorflow.org/
> Author: Google Inc.
> Author-email: packages@tensorflow.org
> License: Apache 2.0
> Location: d:\programs\anaconda\lib\site-packages
> Requires: absl-py, flatbuffers, keras, termcolor, keras-preprocessing, h5py, wrapt, google-pasta, gast, protobuf, astunparse, typing-extensions, six, tensorboard, opt-einsum, wheel, numpy, tensorflow-estimator, grpcio, clang
> Required-by: 

Now when I run this cell:

```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
This error will raise:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-25-0ca82b29604d> in <module>
>       1 from tensorflow.python.client import device_lib
> ----> 2 print(device_lib.list_local_devices())
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\client\device_lib.py in list_local_devices(session_config)
>      43     serialized_config = session_config.SerializeToString()
>      44   return [
> ---> 45       _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config)
>      46   ]
> 
> RuntimeError: failed to get compute capability major for device: UNKNOWN ERROR (1); 0


Or when I run this cell:

```
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=25))
model.add(Dense(10, activation='softmax'))
```

This will be the result, sorry, it's too long:

> InternalError                             Traceback (most recent call last)
> <ipython-input-3-e1250b93a859> in <module>
> ----> 1 model = Sequential()
>       2 model.add(Dense(64, activation='relu', input_dim=25))
>       3 model.add(Dense(10, activation='softmax'))
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
>     528     self._self_setattr_tracking = False  # pylint: disable=protected-access
>     529     try:
> --> 530       result = method(self, *args, **kwargs)
>     531     finally:
>     532       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access
> 
> D:\Programs\Anaconda\lib\site-packages\keras\engine\sequential.py in __init__(self, layers, name)
>     105     """
>     106     # Skip the init in FunctionalModel since model doesn't have input/output yet
> --> 107     super(functional.Functional, self).__init__(  # pylint: disable=bad-super-call
>     108         name=name, autocast=False)
>     109     base_layer.keras_api_gauge.get_cell('Sequential').set(True)
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
>     528     self._self_setattr_tracking = False  # pylint: disable=protected-access
>     529     try:
> --> 530       result = method(self, *args, **kwargs)
>     531     finally:
>     532       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access
> 
> D:\Programs\Anaconda\lib\site-packages\keras\engine\training.py in __init__(self, *args, **kwargs)
>     287     self._steps_per_execution = None
>     288 
> --> 289     self._init_batch_counters()
>     290     self._base_model_initialized = True
>     291 
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
>     528     self._self_setattr_tracking = False  # pylint: disable=protected-access
>     529     try:
> --> 530       result = method(self, *args, **kwargs)
>     531     finally:
>     532       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access
> 
> D:\Programs\Anaconda\lib\site-packages\keras\engine\training.py in _init_batch_counters(self)
>     295     # `evaluate`, and `predict`.
>     296     agg = tf.VariableAggregation.ONLY_FIRST_REPLICA
> --> 297     self._train_counter = tf.Variable(0, dtype='int64', aggregation=agg)
>     298     self._test_counter = tf.Variable(0, dtype='int64', aggregation=agg)
>     299     self._predict_counter = tf.Variable(
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py in __call__(cls, *args, **kwargs)
>     266       return cls._variable_v1_call(*args, **kwargs)
>     267     elif cls is Variable:
> --> 268       return cls._variable_v2_call(*args, **kwargs)
>     269     else:
>     270       return super(VariableMetaclass, cls).__call__(*args, **kwargs)
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py in _variable_v2_call(cls, initial_value, trainable, validate_shape, caching_device, name, variable_def, dtype, import_scope, constraint, synchronization, aggregation, shape)
>     248     if aggregation is None:
>     249       aggregation = VariableAggregation.NONE
> --> 250     return previous_getter(
>     251         initial_value=initial_value,
>     252         trainable=trainable,
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py in <lambda>(**kws)
>     241                         shape=None):
>     242     """Call on Variable class. Useful to force the signature."""
> --> 243     previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
>     244     for _, getter in ops.get_default_graph()._variable_creator_stack:  # pylint: disable=protected-access
>     245       previous_getter = _make_getter(getter, previous_getter)
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\variable_scope.py in default_variable_creator_v2(next_creator, **kwargs)
>    2660   shape = kwargs.get("shape", None)
>    2661 
> -> 2662   return resource_variable_ops.ResourceVariable(
>    2663       initial_value=initial_value,
>    2664       trainable=trainable,
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\variables.py in __call__(cls, *args, **kwargs)
>     268       return cls._variable_v2_call(*args, **kwargs)
>     269     else:
> --> 270       return super(VariableMetaclass, cls).__call__(*args, **kwargs)
>     271 
>     272 
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py in __init__(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, variable_def, import_scope, constraint, distribute_strategy, synchronization, aggregation, shape)
>    1600       self._init_from_proto(variable_def, import_scope=import_scope)
>    1601     else:
> -> 1602       self._init_from_args(
>    1603           initial_value=initial_value,
>    1604           trainable=trainable,
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py in _init_from_args(self, initial_value, trainable, collections, caching_device, name, dtype, constraint, synchronization, aggregation, distribute_strategy, shape)
>    1743               self._update_uid = initial_value.checkpoint_position.restore_uid
>    1744               initial_value = initial_value.wrapped_value
> -> 1745             initial_value = ops.convert_to_tensor(initial_value,
>    1746                                                   name="initial_value",
>    1747                                                   dtype=dtype)
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\profiler\trace.py in wrapped(*args, **kwargs)
>     161         with Trace(trace_name, **trace_kwargs):
>     162           return func(*args, **kwargs)
> --> 163       return func(*args, **kwargs)
>     164 
>     165     return wrapped
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
>    1564 
>    1565     if ret is None:
> -> 1566       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>    1567 
>    1568     if ret is NotImplemented:
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\tensor_conversion_registry.py in _default_conversion_function(***failed resolving arguments***)
>      50 def _default_conversion_function(value, dtype, name, as_ref):
>      51   del as_ref  # Unused.
> ---> 52   return constant_op.constant(value, dtype, name=name)
>      53 
>      54 
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name)
>     269     ValueError: if called on a symbolic tensor.
>     270   """
> --> 271   return _constant_impl(value, dtype, shape, name, verify_shape=False,
>     272                         allow_broadcast=True)
>     273 
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
>     281       with trace.Trace("tf.constant"):
>     282         return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
> --> 283     return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
>     284 
>     285   g = ops.get_default_graph()
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
>     306 def _constant_eager_impl(ctx, value, dtype, shape, verify_shape):
>     307   """Creates a constant on the current device."""
> --> 308   t = convert_to_eager_tensor(value, ctx, dtype)
>     309   if shape is None:
>     310     return t
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
>     103     except AttributeError:
>     104       dtype = dtypes.as_dtype(dtype).as_datatype_enum
> --> 105   ctx.ensure_initialized()
>     106   return ops.EagerTensor(value, ctx.device_name, dtype)
>     107 
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\eager\context.py in ensure_initialized(self)
>     534       opts = pywrap_tfe.TFE_NewContextOptions()
>     535       try:
> --> 536         config_str = self.config.SerializeToString()
>     537         pywrap_tfe.TFE_ContextOptionsSetConfig(opts, config_str)
>     538         if self._device_policy is not None:
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\eager\context.py in config(self)
>     962     """Return the ConfigProto with all runtime deltas applied."""
>     963     # Ensure physical devices have been discovered and config has been imported
> --> 964     self._initialize_physical_devices()
>     965 
>     966     config = config_pb2.ConfigProto()
> 
> D:\Programs\Anaconda\lib\site-packages\tensorflow\python\eager\context.py in _initialize_physical_devices(self, reinitialize)
>    1291         return
>    1292 
> -> 1293       devs = pywrap_tfe.TF_ListPhysicalDevices()
>    1294       self._physical_devices = [
>    1295           PhysicalDevice(name=d.decode(), device_type=d.decode().split(":")[1])
> 
> InternalError: failed to get compute capability major for device: UNKNOWN ERROR (1); 0

**Comment by sanatmpa1** [comment]
@Silvio-Ma,

Can you let us know how you have installed tensorflow 2.6.0? Have you tried installation with PIP or built it from source?

Also do you have MSVC2019 installed as per the tested build configuration [link](https://www.tensorflow.org/install/source_windows#cpu)?

**Comment by Silvio-Ma** [comment]
I tried conda install, it did not work. pip install just worked for me.
I'm quite a novice in this field, and in installing instructions I've seen nothing about Bazel or MSVC2019 as noted in your link. But if you mean microsoft visual c++ 2019, yes I have installed 2015-2019 redistributable.

**Comment by sanatmpa1** [comment]
@Silvio-Ma,

Have you tried following this [guide](https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow_cpu-2.6.0-cp38-cp38-win_amd64.whl) to install the tensorflow for windows? If not, Can you try creating a new venv and install as per the guide and let us know if it helps? Thanks!

**Comment by Silvio-Ma** [comment]
@sanatmpa1 

May you send the guide again, the link you have sent above is pointing to a wheel file.
Thanks

**Comment by sanatmpa1** [comment]
@Silvio-Ma,

Can you checkout this [guide](https://www.tensorflow.org/install/source_windows) for TF installation in windows. Thanks!

**Comment by Silvio-Ma** [comment]
Solved
I tried too many ways for days, this is what finally worked for me:

1- Run cmd as administrator

2- Uninstall tensorflow package

3- Delete unnecessary files, this will save lots of space:
`conda clean --tarballs -packages`
 
4- Create a new Virtual Environment: 
`conda create --name env-tf python=3.8.5 `

5- Download tensorflow whl file, close ALL apps (including browsers), activate the new environment in cmd:
`conda activate env-tf`

6- Install the downloaded tensorflow wheel file:
`pip install f:/ tensorflow_cpu-2.6.0-cp38-cp38-win_amd64.whl`

7- Check if it has been installed correctly:
`python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

8- Install jupyter in the new environment:
```
pip install jupyter
pip install jupyter lab
```

9- Install python kernel:
`conda install ipykernel`

It's done!

**Comment by sanatmpa1** [comment]
@Silvio-Ma,

Thanks for the detailed steps that worked for you, as it may help someone else in the future to try out. As your problem is resolved, can you move this issue to closed status? Thanks!

**Comment by Silvio-Ma** [comment]
@sanatmpa1 
Thanks for your help Sanat, and sure, I will do it now.
