### ISSUE TITLE
TF RNN subclass model called twice although sequence length is one

### ISSUE THREAD

**Issue by mgkumar138** [tensorflow/tensorflow#51731]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 / 8
- GPU model and memory: RTX 2070 8 GB

**Describe the current behavior**
I am building a custom RNN layer using tensorflow's model subclass documentation. My input is a 1D vector while the RNN states are also fed into the model at each timestep i.e. my input is generated at each timestep, the RNN's state is obtained from the previous timestep and I need the model output at each timestep. The issue I am facing is that when a single input is given each timestep, the RNN's call function is called twice instead of just once i.e. print('--------- Loop --------') is displayed twice instead of just once when the input is only given once. This becomes a bigger issue as runtime is doubled when I am running a bigger network for a reinforcement learning problem where weights are updated at each timestep instead of the Monte Carlo method.

**Describe the expected behavior**
The expected behaviour would be that the call function is only called once at each timestep so that print('--------- Loop --------') runs once at each timestep.

**Standalone code to reproduce the issue**

`

    class MinimalRNNCell(tf.keras.layers.Layer):
        def __init__(self, units=100, **kwargs):
            self.units = units
            self.state_size = units
            super(MinimalRNNCell, self).__init__(**kwargs)

        def build(self, input_shape):
            self.kernel = self.add_weight(shape=(input_shape[-1], self.units),
                                      initializer='uniform',
                                      name='kernel')
            self.recurrent_kernel = self.add_weight(
            shape=(self.units, self.units),
            initializer='uniform',
            name='recurrent_kernel')
            self.built = True

        def call(self, inputs, states):
            prev_output = states[0]
            h = tf.matmul(inputs, self.kernel)
            output = h + tf.matmul(prev_output, self.recurrent_kernel)
            print('--------- Loop --------')
            return output, [output]

    rnncell = MinimalRNNCell()
    rnn = tf.keras.layers.RNN(rnncell, return_state=True, return_sequences=False, time_major=False, stateful=False)

    x = tf.random.normal(shape=[1,67],stddev=1)
    state = tf.random.normal(shape=[1,100],stddev=1)
    for t in range(3):
        r, state = rnn(x[None,:], state)
        print('{} timestep done'.format(t+1))
`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Run log: 
--------- Loop --------
--------- Loop --------
1 timestep done
--------- Loop --------
--------- Loop --------
2 timestep done
--------- Loop --------
--------- Loop --------
3 timestep done

**Comment by sushreebarsa** [comment]
@mgkumar138 Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by mgkumar138** [comment]
Will do thanks!
