### ISSUE TITLE
Importing layers from keras instead of tensorflow.keras causes erroneous model.summary() behavior

### ISSUE THREAD

**Issue by hdavis472** [tensorflow/tensorflow#51738]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 21H1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.6

**Describe the current behavior**

```
from tensorflow import keras 
from keras import layers
model = keras.Sequential()
model.add(layers.Dense(1,input_shape=(10, 1)))
model.summary()
```

This code results in a "model has not yet been built" error, even though `input_shape` is specified in the first layer. I noticed that changing the `from keras import layers` to `from tensorflow.keras import layers` solves the problem. But this seems like a trivial change so I don't see why it solves the problem, the error shouldn't be present even if the import is directly from `keras`

**Comment by sushreebarsa** [comment]
@hdavis472 I tried to run your code on Colab using TF **`v2.6.0`** , **`tf-nightly`** and didn't face the error reported here.Please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/65359c429a4860297b819d79dc1e5638/51738.ipynb)for your reference and let us know if it helps ? Thank you!
