### ISSUE TITLE
Reshape output tensor in Tensorflow lite.

### ISSUE THREAD

**Issue by jonpsy** [tensorflow/tensorflow#51740]
**System information**
- TensorFlow version (you are using): master branch
- Are you willing to contribute it (Yes/No): YEs

**Describe the feature and the current behavior/state.**

I'm currently working on this [pull request](https://github.com/tensorflow/tflite-support/pull/612). I want to resize both the input and output tensor of an interpreter. The current API supports only `ResizeInputTensor()` for some reason. Any leads?

**Will this change the current api? How?**
   This is an internal API, there won't be any visible change.

**Who will benefit with this feature?**
   
  Those working with core TFLite C++ API.

**Any Other info.**

**Comment by abattery** [comment]
The output tensors will be determined by the input tensor's shape and the model graph structure by programmatically.

Could you share why this feature is needed to understand the context of your problem?

**Comment by jonpsy** [comment]
@abattery For image-to-image task, it's desirable to have the output shape being determined by the input image shape. 

For ex: If input is input dims: `[1, 1, 1, 3]` and output dims: `[1, 1, 1, 16]`. But height and width have `dim_signature` as -1. So, based on the input `(height, width)`, input dim should be `[1, height, width, 3]` and `[1, height, width, 16]`. You can find more information in the PR I've linked.

Could you please guide me on how to resize output tensor? Thanks.

**Comment by mohantym** [comment]
Hi @ymodak ,Could you please look into this feature request .

**Comment by abattery** [comment]
After invoking with the inputs, you can get the correct output shapes automatically.

**Comment by abattery** [comment]
Resizing output tensor won't beb

**Comment by jonpsy** [comment]
@abattery Thanks a lot, Invoking() worked!
