### ISSUE TITLE
TransformGraphWithStringInputs is available in tf2.0 however I am planning to jump to tf2.2 or tf2.3 but I couldn't find "TransformGraphWithStringInputs" in these 2 versions. Any suggestions ?

### ISSUE THREAD

**Issue by py2ai** [tensorflow/tensorflow#51742]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by sushreebarsa** [comment]
@py2ai Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!
