### ISSUE TITLE
Error loading saved model

### ISSUE THREAD

**Issue by dash-myelin** [tensorflow/tensorflow#51746]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA GeForce RTX 2060, 6144 MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After saving a Quant Aware model to saved_model using model.save(), I get this error while loading it with tf.keras.models.load_model() - KeyError: '__inference_depthwise_conv2d_layer_call_and_return_conditional_losses_8913'. This happens only when the model has SeparableConv2D layer.

**Describe the expected behavior**
The model should load without any error. It does if the model has only Conv2D layers, but doesn't if it has SeparableConv2D layers

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1_afuGL5IUrquuXEhAJkOExN5HXJUbtOt?usp=sharing 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
KeyError: '__inference_depthwise_conv2d_layer_call_and_return_conditional_losses_8913'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-39c24960e684> in <module>
      1 with tfmot.quantization.keras.quantize_scope():
----> 2     q_model = tf.keras.models.load_model(saved_model_dir.format(epoch=epoch))
      3 
      4 PATH = '/media/dash/027A71F47A71E537/Dash_ext/sonyliv/exp/vids/input/KBC_1_1080p_640x360_664_kbps/input_2.png'
      5 im = cv2.imread(PATH)

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
    210       if isinstance(filepath, six.string_types):
    211         loader_impl.parse_saved_model(filepath)
--> 212         return saved_model_load.load(filepath, compile, options)
    213 
    214   raise IOError(

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/load.py in load(path, compile, options)
    142   for node_id, loaded_node in keras_loader.loaded_nodes.items():
    143     nodes_to_load[keras_loader.get_path(node_id)] = loaded_node
--> 144   loaded = tf_load.load_partial(path, nodes_to_load, options=options)
    145 
    146   # Finalize the loaded layers and remove the extra tracked dependencies.

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_partial(export_dir, filters, tags, options)
    763     A dictionary mapping node paths from the filter to loaded objects.
    764   """
--> 765   return load_internal(export_dir, tags, options, filters=filters)
    766 
    767 

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls, filters)
    888       try:
    889         loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
--> 890                             ckpt_options, filters)
    891       except errors.NotFoundError as err:
    892         raise FileNotFoundError(

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in __init__(self, object_graph_proto, saved_model_proto, export_dir, ckpt_options, filters)
    158       self._concrete_functions[name] = _WrapperFunction(concrete_function)
    159 
--> 160     self._load_all()
    161     self._restore_checkpoint()
    162 

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _load_all(self)
    254   def _load_all(self):
    255     """Loads all nodes and functions from the SavedModel and their edges."""
--> 256     self._load_nodes()
    257     self._load_edges()
    258     # TODO(b/124045874): There are limitations with functions whose captures

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _load_nodes(self)
    432         # interface.
    433         continue
--> 434       node, setter = self._recreate(proto, node_id)
    435       nodes[node_id] = node
    436       node_setters[node_id] = setter

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _recreate(self, proto, node_id)
    550     if kind not in factory:
    551       raise ValueError("Unknown SavedObject type: %r" % kind)
--> 552     return factory[kind]()
    553 
    554   def _recreate_user_object(self, proto, node_id):

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in <lambda>()
    539             lambda: self._recreate_user_object(proto.user_object, node_id)),
    540         "asset": lambda: self._recreate_asset(proto.asset),
--> 541         "function": lambda: self._recreate_function(proto.function),
    542         "bare_concrete_function": functools.partial(
    543             self._recreate_bare_concrete_function,

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in _recreate_function(self, proto)
    578   def _recreate_function(self, proto):
    579     return function_deserialization.recreate_function(
--> 580         proto, self._concrete_functions), setattr
    581 
    582   def _recreate_bare_concrete_function(self, proto):

~/Dash/virtual_envs/tf2_gpu_conda/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py in recreate_function(saved_function, concrete_functions)
    275   concrete_function_objects = []
    276   for concrete_function_name in saved_function.concrete_functions:
--> 277     concrete_function_objects.append(concrete_functions[concrete_function_name])
    278 
    279   for cf in concrete_function_objects:

KeyError: '__inference_depthwise_conv2d_layer_call_and_return_conditional_losses_8913'

**Comment by dash-myelin** [comment]
Is there any way to save the Quant aware model to saved model or pb format?

**Comment by mohantym** [comment]
Hi @dash-myelin , It seems you have missed two steps  - model.compile() and model.fit() before saving the model , you can use the setup_pretrained_weights() function from this reference [colab link](https://colab.research.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training_comprehensive_guide.ipynb#scrollTo=lvpH1Hg7ULFz) to train your model.

**Comment by dash-myelin** [comment]
Hi @mohantym , actually I am training the model in a VM, with a custom training loop (not the default fit method). In my local, I get the relevant .ckpt files, load it to a new model, and save the model to a saved_model. 

Any suggestions for this?

**Comment by dash-myelin** [comment]
@mohantym The model I am trying to save is already trained for some epochs with quantization aware training. The issue seems to be saving a QAT model with QuantWrapper(SeparableConv2D)

**Comment by mohantym** [comment]
Ok! Could you please provide the  same complete code to expedite the issue  then?

**Comment by dash-myelin** [comment]
@mohantym - https://colab.research.google.com/drive/1_afuGL5IUrquuXEhAJkOExN5HXJUbtOt?usp=sharing 

There you go. I have shown clearly in the code the issue with Quantize Aware SeparableConv2D layer

**Comment by dash-myelin** [comment]
@mohantym It's a critical feature. I use SeparableConvs in all my models for speed. And tf2.x allows only model.save() to create pb files. It's a serious bug.

Please tell me if there is another way to achieve saving and loading Quant aware models with SeparableConvs.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look into this issue?

**Comment by dash-myelin** [comment]
@mohantym @sanatmpa1 Is anyone going to help me with this issue? It's a critical bug that is not supposed to be there in the first place and still, no one is responding for the past 2 days. 

It's really frustrating that after all the training and evaluation when you are finally going to deploy a model, you can't even save it! 

Also, it's a **Quantization Aware Model** that is being saved. 

Please help me..

**Comment by sanatmpa1** [comment]
@dash-myelin,

I am able to reproduce the issue with `TF 2.6.0` whereas it works fine when using `tf-nightly`. Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/b4d16c99e24f16c7fbbd2af1832c6de9/51746.ipynb) and let me know if it helps. Thanks!

**Comment by dash-myelin** [comment]
@sanatmpa1,

Thanks for the suggestion to use ```tf-nightly```. However, I ran into this issue - [gist here](https://colab.research.google.com/drive/1_afuGL5IUrquuXEhAJkOExN5HXJUbtOt?usp=sharing) 

Please let me know what can be done.

**Comment by dash-myelin** [comment]
@sanatmpa1 

Can you please help me solve this issue. I am really stuck with this QAt issue with tf-nightly

**Comment by sanatmpa1** [comment]
@dash-myelin,

I can see that this issue with your custom model is not just with `tf-nightly`, it happens even in `2.6.0`. Take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/f2e4ca93d3110ae0da974bcc590d5aa9/issue.ipynb).

**Comment by dash-myelin** [comment]
@sanatmpa1 

Ok. But with tf-nightly, I can save the QAT model with Separable Convs. How Do I get rid of this error?

**Comment by sanatmpa1** [comment]
@dash-myelin,

I feel the issue is probably related to model optimization. Can you submit an issue with [model optimization repo](https://github.com/tensorflow/model-optimization/issues). Thanks!
