### ISSUE TITLE
CAST: Not supported Cast case.

### ISSUE THREAD

**Issue by hongye007** [tensorflow/tensorflow#51741]
Version: TFLite 2.6.0
Device: Huawei Mate30

08-30 11:00:38.255 28325 28842 I tflite  : Initialized TensorFlow Lite runtime.
08-30 11:00:38.257 28325 28842 E tflite  : Following operations are not supported by GPU delegate:
08-30 11:00:38.257 28325 28842 E tflite  : CAST: Not supported Cast case.
08-30 11:00:38.257 28325 28842 E tflite  : DEQUANTIZE: 
08-30 11:00:38.257 28325 28842 E tflite  : 6 operations will run on the GPU, and the remaining 8 operations will run on the CPU.

**Comment by sanatmpa1** [comment]
@hongye007,

Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) for us to expedite the trouble-shooting process. Thanks!
