### ISSUE TITLE
NameError:

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51744]
![4](https://user-images.githubusercontent.com/26819449/131285254-1698b895-d3d7-4c10-9251-8c169d7d5dd8.JPG)

![5](https://user-images.githubusercontent.com/26819449/131285259-61b09421-68ae-490e-9a1d-30aeefa364a5.JPG)

TensorFlow version : 2.2
 Keras version : 2.4.3
Even after defining it. It's telling to define it.

**Comment by sanatmpa1** [comment]
@starboyvarun,

Can you share a reproducible code to expedite the trouble-shooting process? Thanks!

**Comment by sanatmpa1** [comment]
Duplicate of #51745

**Comment by starboyvarun** [comment]
@sanatmpa1  you replied very late that's why.

**Comment by starboyvarun** [comment]
@sanatmpa1  Here is code.
![1](https://user-images.githubusercontent.com/26819449/131329177-db11ab2b-5d8c-438c-8686-1c1517c49ec4.JPG)
![2](https://user-images.githubusercontent.com/26819449/131329187-25c36f3b-adba-4cd6-ae65-e18ec7af7466.JPG)
![3](https://user-images.githubusercontent.com/26819449/131329190-9f00478e-37ed-49de-9289-200397a4b973.JPG)
Do you need google Collab link?

**Comment by sanatmpa1** [comment]
@starboyvarun,

As this is a duplicate, I would recommend you to provide the colab gist on #51745 and confirm if I can close this issue. Thanks!

**Comment by starboyvarun** [comment]
you solve it. I  will close the other one. @sanatmpa1

**Comment by sanatmpa1** [comment]
@starboyvarun,

As I see that @sushreebarsa is already working on the issue #51745. To avoid duplication of efforts, Can you kindly confirm if we can close the issue here? Thanks!

**Comment by starboyvarun** [comment]
@sanatmpa1 solve the issue I have closed that issue.
If you cant do it .assign someone else.

**Comment by starboyvarun** [comment]
@sanatmpa1  solve the issue or assign someone else

**Comment by sanatmpa1** [comment]
@starboyvarun,

Can you share your code as colab gist for us to take a look? I am not able to access the colab link that you posted in #51745.

**Comment by starboyvarun** [comment]
@sanatmpa1  can you just tell me how to add the path to a particular library in google collab?

**Comment by sanatmpa1** [comment]
@starboyvarun,

Can you take a look at this [blog](https://zerowithdot.com/colab-workspace/) and this SO [thread](https://stackoverflow.com/questions/55253498/how-do-i-install-a-library-permanently-in-colab) and let me know if this is what you are looking for?

**Comment by starboyvarun** [comment]
@sanatmpa1  I have solved this particular error. Thank you for your blog and thread link really appreciate it.

Thanks!
