### ISSUE TITLE
mips toolchain compile tflite2.6 error

### ISSUE THREAD

**Issue by KennyTang1988** [tensorflow/tensorflow#51757]
I extract tflite 2.6 source code, and make it with different toolchains. Arm and linux toolchains works fine. But mips-mti-elf-gcc/g++ appears the following error:

I confirm that my mips toolchain has supported c++11. Because mips toolchain not define _GLIBCXX11_USE_C99_STDIO,  it does not support to_string function. 

I don't know why mips not support _GLIBCXX11_USE_C99_STDIO, and if tf can help solve this problem?

tflite/tf_latest/tensorflow/lite/kernels/kernel_util.cc: In function ‘std::__cxx11::string tflite::GetShapeDebugString(const TfLiteIntArray*)’:
tflite/tf_latest/tensorflow/lite/kernels/kernel_util.cc:423:24: error: ‘to_string’ is not a member of ‘std’
       str = "[" + std::to_string(shape->data[d]);
                        ^~~~~~~~~
tflite/tf_latest/tensorflow/lite/kernels/kernel_util.cc:423:24: note: suggested alternative: ‘__sso_string’
       str = "[" + std::to_string(shape->data[d]);
                        ^~~~~~~~~
                        __sso_string
tflite/tf_latest/tensorflow/lite/kernels/kernel_util.cc:425:26: error: ‘to_string’ is not a member of ‘std’
       str += ", " + std::to_string(shape->data[d]);
                          ^~~~~~~~~
tflite/tf_latest/tensorflow/lite/kernels/kernel_util.cc:425:26: note: suggested alternative: ‘__sso_string’
       str += ", " + std::to_string(shape->data[d]);
                          ^~~~~~~~~
                          __sso_string
<builtin>: recipe for target 'tflite/tf_latest/tensorflow/lite/kernels/kernel_util.o' failed
make: *** [tflite/tf_latest/tensorflow/lite/kernels/kernel_util.o] Error 1

**Comment by chunduriv** [comment]
@KennyTang1988, Did you tried as suggested [here](https://github.com/tensorflow/tensorflow/issues/51757#issuecomment-938333253)? and let us know?
