### ISSUE TITLE
[tflite conversion] Invalid file dropped for invalid shape without error

### ISSUE THREAD

**Issue by seanshpark** [tensorflow/tensorflow#51756]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip package version 2.6.0
- TensorFlow library (version, if pip package or github SHA, if built from source): N/A

### 2. Code
_Provide code to help us reproduce your issues using one of the following options:_

Download model:
```
wget https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/inception_v3_2018_04_27.tgz

tar zxvf inception_v3_2018_04_27.tgz
```

```py
import tensorflow as tf

input_path = "./inception_v3.pb"
output_path = "./inception_v3.tflite"

input_shapes = {"input": [0, 299, 299, 3]}
input_nodes = ["input"]
output_nodes = ["InceptionV3/Predictions/Reshape_1"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            input_path, input_nodes, output_nodes, input_shapes)
converter.allow_custom_ops = True
tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)
```
I suppose `input_shapes = {"input": [0, 299, 299, 3]}` is invalid where batch is 0.
And expect there be some error reporting.

### 3. Failure after conversion
_If the conversion is successful, but the generated model is wrong, then state what is wrong:_

- tflite model has only input and output nodes without any valid network

### 5. (optional) Any other info / logs
_Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached._

Invalid input shape is a NEGATIVE test to check TensorFlow is working OK.
This time it didn't.

TF2.3.0 showed this error. But TF 2.6.0 ended without error but dropped invalid tflite file.

> loc("InceptionV3/InceptionV3/Mixed_7c/concat"): error: 'tfl.concatenation' op failed to verify that values and output must have same element type
Traceback (most recent call last):
File ".../tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
enable_mlir_converter)
File ".../tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
enable_mlir_converter)
Exception: :0: error: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): 'tfl.concatenation' op failed to verify that values and output must have same element type
:0: note: loc("InceptionV3/InceptionV3/Mixed_7c/concat"): see current operation: %0 = "tfl.concatenation"() {axis = 3 : i32, fused_activation_function = "NONE"} : () -> tensor<0x8x8x2048xf32>

**Comment by seanshpark** [comment]
From https://github.com/Samsung/ONE/issues/7589#issuecomment-908819727, this is a capture image using netron with generated tflite file.

![image](https://user-images.githubusercontent.com/4616940/131426761-b4629572-5ffd-4853-97b0-76744e614237.png)

**Comment by seanshpark** [comment]
If above script to convert to tflite has any problems, it would be grateful to point it out...

**Comment by mohantym** [comment]
Hi @seanshpark , I found this comment

>  "Tuple of strings representing input tensor names and list of integers representing input shapes (e.g., [("foo" : [1, 16, 16, 3])]). Use only when graph cannot be loaded into TensorFlow and **when input_tensors and output_tensors are None.** "(default None)

 for input_arrays_with_shape from [v1 document.](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter) .  Changed the code

```
import tensorflow as tf
print(tf.__version__)
input_path = "./inception_v3.pb"
output_path = "./inception_v3.tflite"

input_shapes = {"input": [0, 299, 299, 3]}
input_nodes = ["input"]
output_nodes = ["InceptionV3/Predictions/Reshape_1"]

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            input_path, input_nodes, output_nodes, input_shapes = None)
converter.allow_custom_ops = True
tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)

```


providing [gist](https://colab.research.google.com/gist/mohantym/fcf5822199ec52816176025e941712c1/github_51756.ipynb) fore reference

**Comment by seanshpark** [comment]
@mohantym , thanks for the comment, but I am not asking correct script to get correct tflite

What I expect from is that, 
- if invalid input shape, like `input_shapes = {"input": [0, 299, 299, 3]}` , is given, I expect `tflite_model = converter.convert()` to drop an error

So, this happens
- Current TF2.6.0 doesn't drop and error
- I cannot catch the error
- An invalid TensorFlow lite file is generarted (like the one in the netron capture)

This is a problem to me...

**Comment by mohantym** [comment]
Hi @ymodak ,Could you please look into this issue!

**Comment by karimnosseir** [comment]
If i am not mistaken, when you specify a shape with 0 batch, the converter just optimizes your model away.
It is not invalid, but may be useless.

**Comment by seanshpark** [comment]
> It is not invalid, but may be useless.

Thanks for the vertification :) I'll think this as optimization result.
