### ISSUE TITLE
Issue about using Nsight System on Tensorflow2.6.0

### ISSUE THREAD

**Issue by duck7216** [tensorflow/tensorflow#51766]
**System information**

\- OS Platform Linux Ubuntu 18.04.5

\- TensorFlow installed from **docker**(tensorflow/tensorflow:2.6.0rc2-gpu)

\- TensorFlow version :**2.6.0rc2-gpu** (default)

\- Python version:**3.6.9** (default)

\- CUDA version:**11.2** (default)

\- cuDNN version:**8.1.0** (default)

\- GPU model and memory:**NVIDIA A6000** / 48685MiB

 

**Describe the current behavior**

When using Nsight System to profile my training, I found that there were only cuDNN and cuBLAS in my profiling file like this, but CUDA API and CUDA HW was missing.

 
![1](https://user-images.githubusercontent.com/89841382/131491418-ef079c92-c7b9-47e8-a557-7bf57950ff0c.png)

But when I change the tensorflow version from 2.6.0rc2 to 2.4.3(with CUDA 11.0), the CUDA API and CUDA HW appeared.

 
![2](https://user-images.githubusercontent.com/89841382/131491433-f980c222-5c22-480c-9661-af95bf80bf4e.jpg)

I'd like to know the cause of this problem and what  I can do to make CUDA API and CUDA HW appear on Tensorflow2.6.0.rc2.

Thank you.

**Standalone code to reproduce the issue**

The run scripts is like this.

```
nsys profile -t cuda,osrt,nvtx,cudnn,cublas \
       -o $1 \
       -f true \
       -w true \
       --sampling-period 2000000\
       python train.py

```

The core code of train.py is like this.

```python
# ---preprocess dataset---
# ---get model and compile
# Add nvtx to nsys
import ctypes
_cuda_tools_ext = ctypes.CDLL("libnvToolsExt.so")
_cuda_tools_ext.nvtxRangePushA(ctypes.c_char_p("start train".encode('utf-8')))

model.fit(train_db, 
	epochs=1, 
	validation_data = test_db,
	validation_freq=1)
_cuda_tools_ext.nvtxRangePop()

```

**Comment by sanjoy** [comment]
@nluehr Do you happen to know if this is an issue with TensorFlow or with Nsight?

**Comment by sachinprasadhs** [comment]
Could you please try again with the below build configuration with the tensorflow 2.9.1 and let us know if you still face an issue. 



Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.9.0 | 3.7-3.10 | GCC 9.3.1 | Bazel 5.0.0 | 8.1 | 11.2
