### ISSUE TITLE
Saving a NSL model

### ISSUE THREAD

**Issue by old-school-kid** [tensorflow/tensorflow#51769]
**NotImplementedError: Saving `AdversarialRegularization` models is currently not supported. Consider using `save_weights` or saving the `base_model`.**
I trained a Neural Structured Learning model with AdversarialRegularization and tried to save the model as a SavedModel format as well as a HDF5 model. And in both case I faced this error. Can anyone let me know how to save the model or a workaround.
A simple example can be found in this [notebook](https://colab.research.google.com/drive/1CV6uCAys9lcbD33oZv39BvU5AfnHDYya?usp=sharing)

**Comment by sanatmpa1** [comment]
@old-school-kid,

Can you take a look at this [issue](https://github.com/tensorflow/neural-structured-learning/issues/23) in `
neural-structured-learning` repo, where a similar type of question is already answered. Let me know if it helps. Thanks!

**Comment by old-school-kid** [comment]
Thank you @sanatmpa1 
I was trying to save the model with the regularization. But saving the base model works too. So we can close the issue. 
I was wondering if we could save the nsl model directly as a tensorflow model and not save the base model explicitly. Would be easy in that way.

**Comment by sanatmpa1** [comment]
@old-school-kid,

Thanks for the update, glad its working fine for you, kindly move this issue to closed status as it is resolved.
