### ISSUE TITLE
How is TensorFlow compatible with Python2 and Python3 ？

### ISSUE THREAD

**Issue by shlee007** [tensorflow/tensorflow#51763]
I'm doing some development based on the community's TensorFlow, but it only supports a single version of Python.It seems that the community’s TensorFlow supports both Python2 and Python3：
![image](https://user-images.githubusercontent.com/54703662/131481441-bf9f99a2-5456-4e1d-b3d1-c7b3e35240e8.png)

I have read the [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#s2.20-modern-python), and know that "from __future__ import" is used to make Python 2 and 3 compatible. However, it seems to involve only a few aspects, but there are many differences between Python2 and Python3(e.g. zip()). I want to know, in addition to the above, what work has TensorFlow done to achieve compatibility between Python 2 and 3 ?

Besides, what should I do to test and verify the compatibility of my code?

**Comment by mohantym** [comment]
Hi @shlee007 !We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by shlee007** [comment]
> Hi @shlee007 !We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

hi @mohantym , the issue template：

**tf version:** 1.15.0
**Python version:** 2.7 & 3.6
**the problem:** I am not asking a specific issue, I just want to know the implementation of TensorFlow on Py2/3 compatibility. I have learned about the functions and usage of the [six](https://pypi.org/project/six/), [future](https://pypi.org/project/future/), and [past](https://pypi.org/project/past/) libraries. Learn how to write Py2/3 compatible code and convert Py2 or Py3 style code to Py2/3 compatible code. Below is my question:
- Does tensorflow have any development specifications on Py2/3 compatibility?
- How does tensorflow test the Py2/3 compatibility of the code? If I missed something in the development process (make it only support Py2 or Py3), how can I find it?

Thanks for answering !

**Comment by mohantym** [comment]
Supported Python versions for Tensorflow are Python 3.6-3.9 . 
For further details on supported hardware and OS ,Please refer - https://www.tensorflow.org/install
