### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'label_map'

### ISSUE THREAD

**Issue by remotepilotsam** [tensorflow/tensorflow#51772]
I was running the notebook in Jupyter Notebook (the version that can be downloaded from the Colab notebook), and ran into this error in step 3 shown in the image.

![label_map error](https://user-images.githubusercontent.com/81659220/131559999-97b99027-43f1-4ff0-8198-c79286fdb1b4.png)
 
Anyone know how to fix this?

**Comment by vulkomilev** [comment]
Are you sure that you have initialized the train_data variable

**Comment by sanatmpa1** [comment]
@remotepilotsam,

Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) for us to expedite the trouble-shooting process. Thanks!
