### ISSUE TITLE
Sizing problem with BatchDataset in Tensorflow 2.3.1

### ISSUE THREAD

**Issue by jimcost** [tensorflow/tensorflow#51774]
I want to extract the tensor contained within a BatchDataset. It appears I run into a sizing issue -- if I call a batch of 4500 elements no problem (i.e., extractable), but if I create a batch of 5000 elements no dice.

![image](https://user-images.githubusercontent.com/6710629/131588513-c9ddacbd-c5ec-4ff0-b5de-bc9a75def56b.png)

If `inp` does not exist in the second example above, then when trying to call `inp` there is a `NameError: name 'inp' not defined.`

Broadly speaking, anyone know a work around? I am looking to create (and draw from) with a batch size of ~7500.

**System information**
- Stock Tensorflow installed using `pip`
- Ubuntu 20.04
- Sony Vaio Laptop
- Tensorflow: `v2.3.0-54-gfcc4b966f1 2.3.1`
- Python: `3.8.5`

**Comment by mohantym** [comment]
Hi @jimcost , Could you also provide the complete code which will help us to expedite the issue?
