### ISSUE TITLE
tensorboard no runs found for PyTorch 1.9 in VSCode in CentOS 7

### ISSUE THREAD

**Issue by monajalal** [tensorflow/tensorflow#51773]
<img width="1127" alt="Screen Shot 2021-08-31 at 7 22 57 PM" src="https://user-images.githubusercontent.com/1892917/131588221-3152f224-9a08-40d6-8474-f404e26dd9a7.png">

Any tips on how to use Tensorboard in VSCode for PyTorch 1.9?

**Comment by sushreebarsa** [comment]
@monajalal Could you please refer to the [link](https://pytorch.org/tutorials/recipes/recipes/tensorboard_with_pytorch.html),[link1 ](https://www.tensorflow.org/tensorboard/get_started?hl=en)and let us know if it helps?Thanks!
