### ISSUE TITLE
tf.nn.max_pool_with_argmax to support multiple dimensions (ND)

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#51787]
Currently, there is a function called [tf.nn.max_pool_with_argmax](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax). 
This function is useful to, for example, implement [MaxUnpooling](https://www.oreilly.com/library/view/hands-on-convolutional-neural/9781789130331/6476c4d5-19f2-455f-8590-c6f99504b7a5.xhtml).

However, it would be great if the function supported several dimensions, not only 2D images.  [`tf.nn.max_pool`](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool) for example supports any dimensionality. 

This feature will enable the implementation of ND max unpooling.
In particular, it will help me implement the [feature request](https://github.com/NEGU93/cvnn/issues/10) asked on my repository.

**Comment by mohantym** [comment]
Hi @NEGU93 ,Please fill the template for feature request too. Thanks!
