### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51783]
![3](https://user-images.githubusercontent.com/26819449/131661895-8f6100c7-9d01-43c4-bf4f-034853cafaa4.JPG)

![2](https://user-images.githubusercontent.com/26819449/131661655-91576b86-8977-475a-b107-13dad63be3d1.JPG)

![1](https://user-images.githubusercontent.com/26819449/131661662-97ec164b-8596-4b7b-b7ab-e17b39b65d82.JPG)
The error is in this part only before that is nothing just library import.
This is a bug I think.

**Comment by mohantym** [comment]
Hi @starboyvarun !We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by starboyvarun** [comment]
@mohantym Thank you so much. Can you please change type: support to type: Bug.
Thanks!

**Comment by starboyvarun** [comment]
```
from keras.layers import Conv2D
from keras.layers import AveragePooling2D
from janggu import inputlayer
from janggu import outputconv
from janggu import DnaConv2D
from janggu.data import ReduceDim


# load the dataset which consists of
# 1) a reference genome
REFGENOME = resource_filename('janggu', 'resources/pseudo_genome.fa')
# 2) ROI contains regions spanning positive and negative examples
ROI_FILE = resource_filename('janggu', 'resources/roi_train.bed')
# 3) PEAK_FILE only contains positive examples
PEAK_FILE = resource_filename('janggu', 'resources/scores.bed')

# DNA sequences are loaded directly from the reference genome
DNA = Bioseq.create_from_refgenome('dna', refgenome=REFGENOME,
                                   roi=ROI_FILE,
                                   binsize=200)

# Classification labels over the same regions are loaded
# into the Coverage dataset.
# It is important that both DNA and LABELS load with the same
# binsize, stepsize to ensure
# the correct correspondence between both datasets.
# Finally, the ReduceDim dataset wrapper transforms the 4D Coverage
# object into a 2D table like object (regions by conditions)
LABELS = ReduceDim(Cover.create_from_bed('peaks', roi=ROI_FILE,
                               bedfiles=PEAK_FILE,
                               binsize=200,
                               resolution=None), aggregator='mean')


# 2. define a simple conv net with 30 filters of length 15 bp
# and relu activation.
# outputconv as opposed to outputdense will put a conv layer as output
@inputlayer
@outputdense('sigmoid')
def double_stranded_model(inputs, inp, oup, params):
    with inputs.use('dna') as layer:
        # The DnaConv2D wrapper can be used with Conv2D
        # to scan both DNA strands with the weight matrices.
        layer = DnaConv2D(Conv2D(params[0], (params[1], 1),
                                 activation=params[2]))(layer)

    output = GlobalAveragePooling2D(name='motif')(layer)
    return inputs, output


# 3. instantiate and compile the model
model = Janggu.create(template=double_stranded_model,
                      modelparams=(30, 15, 'relu'),
                      inputs=DNA, outputs=LABELS)
model.compile(optimizer='adadelta', loss='binary_crossentropy',
              metrics=['acc'])

# 4. fit the model
model.fit(DNA, ReduceDim(LABELS, epochs=100)

```

@mohantym actually I am trying to run this from the Janggu documentation, but it gives several errors related to tensor flow and some other errors too
.Can you try running in the gist and let me know if this runs.

![9](https://user-images.githubusercontent.com/26819449/133374059-3f9a49fb-62f1-40ab-a321-5e3f60dc6d2e.JPG)
![9 1](https://user-images.githubusercontent.com/26819449/133374075-6ec205b6-9fa1-45b8-91f7-478fa5c8b011.JPG)

Thanks!

**Comment by starboyvarun** [comment]
Should I close this issue now?
@mohantym

**Comment by mohantym** [comment]
@starboyvarun ! Sorry for the late response . Actually tried to replicated above issue , was getting  different error. Attaching [Gist](https://colab.research.google.com/gist/mohantym/c426a30b58b0d295c1bdf4d16ae5b259/github_51783.ipynb) for reference .Can you  please share a Colab gist from your end with above error stack trace?

**Comment by starboyvarun** [comment]
@mohantym 
Ya, I attached the gist can you have a look [Gist](https://colab.research.google.com/gist/starboyvarun/9ab39f94d3c33afd039a9ab0b774c221/14sept.ipynb).
I am trying to implement the last parts of this example in my example(Examples shown in link). [Link](https://github.com/BIMSBbioinfo/janggu/blob/master/src/examples/janggu_convnet_examples.ipynb)
I saw your gist I have already solved the issue. Now can you tell me how can I do the last 3 parts of the link?

Thank you.!

**Comment by starboyvarun** [comment]
@mohantym  Did you check?

**Comment by starboyvarun** [comment]
@mohantym Did you see it ?? Can you what should I do?

**Comment by mohantym** [comment]
Hi @starboyvarun , Please open a separate issue to proceed further and Feel free to close this one . Thank you!

**Comment by starboyvarun** [comment]
ok, thanks! @mohantym
