### ISSUE TITLE
Type Error: __init__() got an unexpected keyword argument 'epochs'

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51786]
![1](https://user-images.githubusercontent.com/26819449/131669104-e1037302-ddde-4eda-9ecf-bfd57a583653.JPG)
![2](https://user-images.githubusercontent.com/26819449/131669108-9b95b63c-1054-4195-95bc-445a29095346.JPG)
![3](https://user-images.githubusercontent.com/26819449/131669115-228d7a39-91f2-4aa3-9482-86fc1dc9944e.JPG)
![4](https://user-images.githubusercontent.com/26819449/131669118-a39aab97-1181-4cb3-b600-4284912004e8.JPG)
 
I tried to solve this particular error. I was trying to implement a particular library from Github.
tensorflow=2.2 
keras=2.4.3
I am only using these two libraries in this Code.

And please also tell me which documentation to refer to, it helps.
Thank You.

**Comment by sushreebarsa** [comment]
@starboyvarun In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
@starboyvarun We see that this issue is more specific to Janggu.Please post this issue in Janggu repo to get the right help!Thanks!

**Comment by starboyvarun** [comment]
@sushreebarsa you must be getting other errors when compiling it. because you haven't done the previous import.
But the error I have reported here is related to TensorFlow or Keras. This is a code snippet.
Also, tell me why do we get such errors and also give the reference.
Thanks!
