### ISSUE TITLE
Interpreter invocation error after input tensor resizing 

### ISSUE THREAD

**Issue by harshitadd** [tensorflow/tensorflow#51797]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.6.0

Error: Post reshaping the input sizes of my tensors - the interpreter invocation fails with an input-output shape mismatch. [ Stack trace in the linked colab file ]. 

### 2. Code

[Here](https://colab.research.google.com/drive/1Vsinmju5FsbiEtfD9BqBHWeKxM3LES-U?usp=sharing ) is the end-end flow of conversion. You can refer to the test files used to generate the test data ( for dummy input ) here: [dev.hi](https://drive.google.com/file/d/1HJtbqzF3X-51S01DFGn5XOUambvMQriO/view?usp=sharing ) and [dev.en](https://drive.google.com/file/d/1IKqg2c-SJiKmd2fsFmODxeB0af3rBATl/view?usp=sharing)

### 3. Failure after conversion

The model gets converted ( and quantized ) successfully though despite setting the model inputs with a valid input sample ( during model.predict(), I have also explicitly tried using model._set_inputs() - that doesn't work either ) the input shapes of the graph are [1,1] for all the arguments. I am forced to reshape them hence, and that's when the error occurs. 

Note: In the colab file, I have shown the input details pre and post resizing - while the argument shape seems to be altered according to my resizing shapes - the 'shape_signature' does not change. Could this be the source of the error ? ( Is this expected behaviour ) 

### 5. (optional) Any other info / logs

The linked colab file has the exact stack traces. Note that if I do not reshape my tensors - the invocation runs but due to the [1,1] limitation - there is no meaningful input that I can provide to the model.

**Comment by karimnosseir** [comment]
If i am not mistaken, shape_signature [-1, 1]  means first dimension can be resized but not the second dimension. you are trying to resize second dimension which is invalid.
If you passed parameter strict=True to resize_tensor_input you should get invalid resize warning

```
interpreter.resize_tensor_input(input_details[0]['index'], np.shape(batch['attention_mask']), strict=True)
```

**Comment by harshitadd** [comment]
> If i am not mistaken, shape_signature [-1, 1] means first dimension can be resized but not the second dimension. you are trying to resize second dimension which is invalid.
> If you passed parameter strict=True to resize_tensor_input you should get invalid resize warning
> 
> ```
> interpreter.resize_tensor_input(input_details[0]['index'], np.shape(batch['attention_mask']), strict=True)
> ```

Thanks for clarifying that. The documentation indicates the same - which is why I was asked if this was expected behavior - since I didn't get an error in the first place  ( when the tensors are resized, they appear to be converted to the altered tensor successfully ); 

[Side Note: This probably goes as a separate issue ] Additionally, in the issue description I have mentioned that the frozen graph size [1,1] is not expected behavior - the conversion process is altering ( in this case making the input size [1,1] ) the saved model's input format despite setting model inputs to a different value explicitly.

**Comment by karimnosseir** [comment]
You will need to set strict=True to get the error.

> [Side Note: This probably goes as a separate issue ] Additionally, in the issue description I have mentioned that the frozen graph size [1,1] is not expected behavior - the conversion process is altering ( in this case making the input size [1,1] ) the saved model's input format despite setting model inputs to a different value explicitly.

Can you share the saved model, and how you're converting it. Conversion shouldn't alter the model input. In the sample you shared above it looks like your model has [-1, 1] shape.

**Comment by harshitadd** [comment]
> You will need to set strict=True to get the error.
>
> > [Side Note: This probably goes as a separate issue ] Additionally, in the issue description I have mentioned that the frozen graph size [1,1] is not expected behavior - the conversion process is altering ( in this case making the input size [1,1] ) the saved model's input format despite setting model inputs to a different value explicitly.
> 
> Can you share the saved model, and how you're converting it. Conversion shouldn't alter the model input. In the sample you shared above it looks like your model has [-1, 1] shape.

1. Noted. 
2. The sample specified above does mirror the exact conversion process I follow ( and how I generate the Saved Model). I edited the code so that it now specifies the explicit assignment of inputs to the model ( before saving, and that shape is not [1,1] ) as well.

I was able to trace the inconsistent behavior ( of model.save() altering the outputs ) to a embedding resizing that I perform during the model training ( I train using the Hugging Face TFTrainer API). If I do not resize the model embeddings - and then save the model: the behavior is as expected i.e model.save() does not alter the inputs and the tflite file is generated with the inputs that it was saved with). Having said that - Even in that case: I cannot resize the tensors at runtime and get the same error. Kindly let me know if this out of scope for resolution ( due to the cross-platform dependency on HF ) and I shall close the issue for the time being.

**Comment by karimnosseir** [comment]
I am not familiar with HF API, but if you can make the shapes dynamic in a correct way before saving, then you can resize correctly after converting.

> Edit: I just noticed another AutoGraph Warning in the beginning of the stack trace; Kindly let me know If I should file a separate issue for that as indicated.

Yes file another Issue.

I am closing the issue since it is not a problem with TFLite. Feel free to file issues if you're having a problem.

Thanks
