### ISSUE TITLE
Undefined reference to CheckOpMessageBuilder::NewString() when linking libtensorflow_cc.so

### ISSUE THREAD

**Issue by hemalshahX** [tensorflow/tensorflow#5179]
I am trying to use the TensorFlow Session C++ API (Python-free) to load a pre-trained model for inference. For build-time considerations, I am trying to deploy TensorFlow as a "system" package by linking against libtensorflow_cc.so and including headers into my Bazel-based workspace which has its own copies of protobuf and Eigen. I am almost there except that I have run into linker errors for missing implementations of tensorflow::internal::CheckOpMessageBuilder::NewString(). The symbols appear to be exported by libtensorflow_cc.so and it does seem to all be linking correctly, just not this symbol.

Any help fixing this issue or suggestions for a better way of doing this would be greatly appreciated.

Thanks, 
Hemal

My setup is the following: 
Docker image from ubuntu:16.04 using gcc5.
Bazel 0.3.1 (needed to upgrade from 0.3.0 because of other Tensorflow build issues) 
I matched the Eigen version but the protobuf used to build the Tensorflow wheel below is installed via apt-get and there is another copy (3.0.0) within my workspace's third_party directory.

The following is in my Dockerfile to build and "deploy" Tensorflow: 
RUN git clone https://github.com/tensorflow/tensorflow.git /tmp/tensorflow \ 
&& cd /tmp/tensorflow && git checkout r0.11 \ 
&& yes '' | ./configure \ 
&& bazel build -c opt //tensorflow/tools/pip_package:build_pip_package \ 
&& /tmp/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg \ 
&& pip2 install --quiet --upgrade /tmp/tensorflow_pkg/*.whl \ 
&& bazel build -c opt //tensorflow:libtensorflow_cc.so \ 
&& cp /tmp/tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so /usr/lib/libtensorflow_cc.so \ 
&& ln -sv /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow /usr/include/tensorflow \ 
&& ln -sv /usr/local/lib/python2.7/dist-packages/tensorflow/include/third_party /usr/include/third_party

164:1: Linking of rule '//estimation/detection:playback_ground_truth' failed: clang-3.6 failed: error executing command 
  (cd /code/.cache/bazel/_bazel_hemalshah/6fa7a91faa1abdfbb41bc875fa66f0f6/execroot/robotics && \
  exec env - \
  /usr/bin/clang-3.6 -o bazel-out/local_linux-opt/bin/estimation/detection/playback_ground_truth -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -Wl,-O1 -Wl,-Bsymbolic-functions -pthread -B/usr/bin/ -Wl,@bazel-out/local_linux-opt/bin/estimation/detection/playback_ground_truth-2.params): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

bazel-out/local_linux-opt/bin/estimation/detection/libtof_pose_estimator.lo(tof_pose_estimator.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<long long, long long>(long long const&, long long const&, char const*)':
/usr/include/tensorflow/core/platform/default/logging.h:170: undefined reference to`tensorflow::internal::CheckOpMessageBuilder::NewString()'
bazel-out/local_linux-opt/bin/estimation/detection/libtof_pose_estimator.lo(tof_pose_estimator.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* tensorflow::internal::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
/usr/include/tensorflow/core/platform/default/logging.h:170: undefined reference to`tensorflow::internal::CheckOpMessageBuilder::NewString()'

**Comment by drpngx** [comment]
Could you attach the full Dockerfile?

**Comment by hemalshahX** [comment]
Sure, 

FROM ubuntu:16.04

RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true \
        | /usr/bin/debconf-set-selections \
    && apt-get -q update \
    && apt-get install -qy \
        bash-completion \
        ccache \
        clang-3.6 \
        clang-format-3.6 \
        g++ \
        gcc \
        gdb \
        gdbserver \
        gfortran \
        git \
        graphviz \
        imagemagick \
        libarchive-dev \
        libassimp-dev \
        libboost-all-dev \
        libelf-dev \
        libffi-dev \
        libgl1-mesa-dev \
        libjpeg-dev \
        liblapack3 \
        libmysqlcppconn-dev \
        libnlopt-dev \
        #libprotobuf-dev \
        libraw1394-11 \
        libssl-dev  \
        libsparsehash-dev \
        libunwind8-dev \
        libzookeeper-mt-dev \
        lsb-core \
        lsof \
        libwebsocketpp-dev \
        nodejs \
        oracle-java8-installer \
        pkg-config \
        pylint \
        python-dev  \
        python-pip \
        python-setuptools \
        python-sphinx \
        python-yaml \
        python-h5py \
        python3-pip \
        python-numpy \
        python-scipy \
        python-nose \
        python-wheel \
        libopenblas-dev \
        strace \
        sudo \
        swig \
        tcpdump \
        valgrind \
        unzip \
        xorg-dev \
        xvfb \
        zip \
        zlib1g-dev \
    && update-java-alternatives -s java-8-oracle

# Build Bazel and build and install Bazel autocomplete
RUN bazel_version='0.3.1' \
    && git clone https://github.com/bazelbuild/bazel.git /bazel \
    && cd /bazel \
    && git checkout $bazel_version \
    && echo "startup --batch\nbuild --spawn_strategy=standalone\nbuild --genrule_strategy=standalone\ntest --test_strategy=standalone" > /bazel/bazelrc \
    && BAZELRC=/bazel/bazelrc /bazel/compile.sh \
    && ln -s /bazel/output/bazel /usr/bin/bazel \
    && /usr/bin/bazel --bazelrc=/bazel/bazelrc build //scripts:bash_completion \
    && cp /bazel/bazel-bin/scripts/bazel-complete.bash /etc/bash_completion.d/

# Python libraries that aren't available via apt
RUN pip2 install --quiet --upgrade \
    cpplint \
    gsutil \
    yapf \
    Theano \
    keras \
    h5py

RUN pip3 install --quiet --upgrade \
    portpicker

RUN git clone https://github.com/tensorflow/tensorflow.git /tmp/tensorflow \
    && cd /tmp/tensorflow && git checkout r0.11 \
    && yes '' | ./configure \
    && bazel build -c opt //tensorflow/tools/pip_package:build_pip_package \
    && /tmp/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg \
    && pip2 install --quiet --upgrade /tmp/tensorflow_pkg/*.whl \
    && bazel build -c opt //tensorflow:libtensorflow_cc.so \
    && cp /tmp/tensorflow/bazel-bin/tensorflow/libtensorflow_cc.so /usr/lib/libtensorflow_cc.so \
    && ln -sv /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow /usr/include/tensorflow \
    && ln -sv /usr/local/lib/python2.7/dist-packages/tensorflow/include/third_party /usr/include/third_party

# Clean up leftover stuff at the very end
RUN apt-get clean \
    && apt-get autoremove -qy \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

**Comment by drpngx** [comment]
So, I followed the steps (except that I used openjdk) and it worked for me.  It built using gcc, though, as it should from the Dockerfile. But your error points to clang-3.6.

(Note that if you want to use ccache, you have to use -v <somedir>:/root/.ccache and create a gcc, g++ script.)

**Comment by hemalshahX** [comment]
Thanks for taking a look! Producing the Docker image is not a problem and I can successfully get libtensorflow_cc.so built and headers all in place. 

When I build and link against them to use the Session API in my Bazel-built project, however, I get the linker error from a cc_binary target that relies on a cc_library target the links against libtensorflow_cc.so.

The Bazel target that links in the libtensorflow_cc.so is as follows for reference:
cc_library(
    name = "tof_pose_estimator",
    srcs = ["tof_pose_estimator.cc"],
    hdrs = ["tof_pose_estimator.h"],
    copts = [
        "-D_FORCE_INLINES",
        "-I/usr/include/tensorflow",
        "-I/usr/include/python2.7",
        "-I/usr/include/x86_64-linux-gnu/python2.7",
        "-fno-strict-aliasing",
        "-D_FORTIFY_SOURCE=2",
        "-g",
        "-fstack-protector",
        "--param=ssp-buffer-size=4",
        "-Wformat",
        "-Werror=format-security",
        "-DNDEBUG",
        "-g",
        "-fwrapv",
        "-O2",
        "-Wall",
        "-Wstrict-prototypes",
    ],
    linkopts = [
        "-L/usr/lib/python2.7/config-x86_64-linux-gnu",
        "-L/usr/lib",
        "-lpthread",
        "-ldl",
        "-ltensorflow_cc",
        "-lutil",
        "-lm",
        "-lpython2.7",
        "-Wl,-O1 -Wl,-Bsymbolic-functions",
    ],
    deps = [
        "//base",
        "//config:util",
        "//geometry/camera_model",
        "//geometry/image",
        "//geometry/normals",
        "//geometry/plane:find_planes",
        "//hardware/monocular_camera",
        "//hardware/stereo_camera:stereo_grabber",
        "//math",
        "//messages:camera_model",
        "//messages:camera_model_io",
        "//messages:math_io",
        "//messages:tof_frame",
        "//messages:tof_frame_io",
        "//vis/websocket:server",
    ],
    alwayslink = 1,
)

**Comment by drpngx** [comment]
Can you check if it's in tensorflow_cc?

```
nm bazel-bin/tensorflow/libtensorflow_cc.so|c++filt|grep tensorflow::internal::CheckOpMessageBuilder::NewString
```

It should show as `T` (not `t`).

If you link with `-Wl,--undefined`, then `ldd` the output, what do you see?

**Comment by hemalshahX** [comment]
Thanks for taking a look! Producing the Docker image is not a problem and I
can successfully get libtensorflow_cc.so built and headers all in place.

When I build and link against them to use the Session API in my Bazel-built
project, however, I get the linker error from a cc_binary target that
relies on a cc_library target the links against libtensorflow_cc.so.

**Comment by hemalshahX** [comment]
The symbol seems to be there:
0000000002b3ed40 T tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()

ldd output shows nothing unusual as far as library dependencies:
	linux-vdso.so.1 =>  (0x00007ffc6abfe000)
	libSegFault.so => /lib/x86_64-linux-gnu/libSegFault.so (0x00007f9ae9554000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9ae9350000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9ae9047000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9ae8e2a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9ae8aa8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9ae8892000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9ae84c9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9aeceb0000)

Did you want to add flags to the build of libtensorflow_cc.so?

Thanks,
Hemal

**Comment by hemalshahX** [comment]
Interesting. If I check libtensorflow_cc.so as built in under Ubuntu 14.04 outside of the Docker image, I do not see the abi:cxx11 part of the above. The following post seems to indicate that the issue is CXX_ABI and copy-on-write for std::string causing the problem:
http://stackoverflow.com/questions/36159238/linking-problems-due-to-symbols-with-abicxx11

**Comment by drpngx** [comment]
Yes I usually set -D_GLIBCXX_USE_CXX11_ABI=0 everywhere, but that's not always the right thing. They made that change more than a year ago IIRC, so maybe clang has caught up with it. You could try 3.9? Or switch to gcc everywhere?

**Comment by hemalshahX** [comment]
The symbol seems to be there:
0000000002b3ed40 T
tensorflow::internal::CheckOpMessageBuilder::NewString[abi:cxx11]()

ldd output shows nothing unusual as far as library dependencies:
linux-vdso.so.1 =>  (0x00007ffc6abfe000)
libSegFault.so => /lib/x86_64-linux-gnu/libSegFault.so (0x00007f9ae9554000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9ae9350000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9ae9047000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f9ae8e2a000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007f9ae8aa8000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9ae8892000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9ae84c9000)
/lib64/ld-linux-x86-64.so.2 (0x00007f9aeceb0000)

Did you want to add flags to the build of libtensorflow_cc.so?

Thanks,
Hemal



On Tue, Oct 25, 2016 at 11:05 AM drpngx <notifications@github.com> wrote:

Can you check if it's in tensorflow_cc?

nm bazel-bin/tensorflow/libtensorflow_cc.so|c++filt|grep
tensorflow::internal::CheckOpMessageBuilder::NewString

It should show as T (not t).

If you link with -Wl,--undefined, then ldd the output, what do you see?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/5179#issuecomment-256112655>,
or mute the thread

**Comment by drpngx** [comment]
Using the default `-D_GLIBCXX_USE_CXX11_ABI=1`, is the right thing, but it will break non-hermetic builds, so in general it's not a good idea for us to do that, esp on a gcc5 system. You can do that on your private build.

The best is to use a bazel configuration which matches on both ends -- either change your tensorflow bazel build, or change your project bazel config so that they match, or add your project as a subdirectory of tensorflow.

**Comment by hemalshahX** [comment]
So, that is definitely the problem, but how to solve it has me puzzled. I tried globally reverting to the old ABI, but then I have trouble with boost libraries linking. I end up playing whack-a-mole until everything is consistent. Clang 3.9 would supposedly help the situation, but not available yet as a Debian package it seems except in the nightly.

The root cause though is why is tensorflow::internal::MakeCheckOpString trying to link against the non-CXX11 ABI version of tensorflow::internal::CheckOpMessageBuilder::NewString (when the cxx11 ABI version is available)? I'm trying to find why that particular function is the only one with what appears to be this ABI mismatch.

**Comment by drpngx** [comment]
There should be a lot more. Anything with `std::string` should be tainted. Feel free to attach the output of nm (without `--demangle` or `c++filt`).

**Comment by hemalshahX** [comment]
[nm-output.txt](https://github.com/tensorflow/tensorflow/files/552340/nm-output.txt)

Here's the output of nm on libtensorflow_cc.so within the Docker image. All of the functions seem to be using cxx11 ABI correctly, so not sure why local references would be looking for the non-cxx11 ABI version of the method.

**Comment by drpngx** [comment]
I think it's that clang is too old and doesn't support the `__attribute__` for the cxx abi.

So, maybe, *either*:

1. Use gcc-4.8 to build tensorflow (apt-get install gcc-4.8), then set env variables `CC` and `CXX`
2. Upgrade llvm using [this procedure](http://askubuntu.com/questions/787383/how-to-install-llvm-3-9) so that it honors the flags. You can build a hello world and check `nm` output
3. Rebuild your code using the system compiler, gcc5

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, we will reopen if further information becomes available. Thanks!

**Comment by hemalshahX** [comment]
@drpngx: Thanks for your help! I've had some trouble getting things to build with the same compiler, but we identified the problem and just working on getting one of the solutions implemented correctly.

**Comment by chesschi** [comment]
@hemalshahX I have encountered similar issue by building tensorflow 1.4.0 from sources in Ubuntu 17.10 using bazel. Please can you kindly explain how did you resolve the linker error for `tensorflow::internal::CheckOpMessageBuilder::NewString`? Many thanks!

**Comment by RoboEvangelist** [comment]
CXX11_ABI is causing a log or issues between boost 1.58 and tensorflow 1.4.1 in my computer. When can this be correctly addressed by tensorflow?
