### ISSUE TITLE
weighted_moments produces NaNs when weights are all zeros

### ISSUE THREAD

**Issue by eli-osherovich** [tensorflow/tensorflow#51792]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git
- Python version: 3.9
- Bazel version (if compiling from source): 4.2
- GCC/Compiler version (if compiling from source): gcc-10
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tf.nn.weighted_moments` produces NaNs when all weights are zeros.
**Describe the expected behavior**
Correct result in this case should be zeros.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
Do not divide by 0 unless you are Chuck Norris.

**Standalone code to reproduce the issue**
```python
x = tf.random.uniform((5, 3))
w = tf.zeros((5, 1))

tf.nn.weighted_moments(x, axes=0, frequency_weights=w)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([nan, nan, nan], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([nan, nan, nan], dtype=float32)>)


```

**Comment by mohantym** [comment]
Hi @eli-osherovich !You should provide only positive weights  in w , Here 0's are not positive weights.
Reference -https://www.tensorflow.org/api_docs/python/tf/nn/weighted_moments#args

**Comment by eli-osherovich** [comment]
I understand the rationale, yet, I believe that all-zeros is still a valid case.

**Comment by mohantym** [comment]
Hi @Saduf2019 , Could you look into this please . providing[ gist](https://colab.research.google.com/gist/mohantym/bfc557013a0db04183e0c2d2ba4cec79/github_51792.ipynb) for reference . issue is replicating in 2.5 ,2.6 and nightly

**Comment by Saduf2019** [comment]
@eli-osherovich 
The weighted_moments function sums your weights with zero vector and  then determines the divisor by taking a reciprocal of the broadcasted vector. In this case, your sum will be zero and since the reciprocal of zero is infinity, nans are appearing.
Don't use zero weights, logically it makes no sense, instead 1's weight every element equally.
For any further queries i suggest to open an issue at tf [discussion forum](https://discuss.tensorflow.org/) as there is a larger community to support/respond.

**Comment by eli-osherovich** [comment]
@Saduf2019 
I know why it happens. Let me assure you zeroes are perfectly logical. I do not see why zeros should be replaced with ones....

P. S. 
It is a bit difficult to understand is this the TF team answer or a recommendation from a fellow user....
