### ISSUE TITLE
Attributes section in Keras Model (documentation) is not generated properly

### ISSUE THREAD

**Issue by bizzyvinci** [tensorflow/tensorflow#51796]
Model attributes section in the documentation has 2 issues:

1. It is duplicated: [attributes](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#attributes) and [attributes_1](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#attributes_1). You might have to look at table of content to spot the difference.
2. Some attributes are missing even though they have been documented and have @property decorator in the github code. E.g [metrics](https://github.com/bizzyvinci/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L635-L683) is missing but [metrics_name](https://github.com/bizzyvinci/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L685-L723) is included.

Note that the documentation link is nightly and the code link is the current master. I guess there might be issue with how the attribute section is generated.

**Comment by mohantym** [comment]
Hi @Saduf2019. Could you please look at this issue!

**Comment by Saduf2019** [comment]
@bizzyvinci 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by bizzyvinci** [comment]
Ok. Thanks.
