### ISSUE TITLE
tensorflow2 memory leak when using tf.function

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51798]
I post this question here because no one is able to answer it for over a month. Hope someone here would give the solution.
https://stackoverflow.com/questions/68379996/how-to-profile-tensorflow-memory

**Comment by ymodak** [comment]
Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.
