### ISSUE TITLE
Android GPU delegate gives same output from intermediate layers output 

### ISSUE THREAD

**Issue by letdivedeep** [tensorflow/tensorflow#51800]
Hi Team

I have trained a mobilnetv2  model using the tfod API.  Along with the normal detector output (bbox, score,num_detection, confidences), I also wanted an intermediate layers output, so  while converting the model to tflite i specified the intemediate node from where i needed the output ('FeatureExtractor/MobilenetV2/expanded_conv_9/add') as illustrated below : 

`tflite_convert --graph_def_file=$1/tflite_graph/tflite_graph.pb --output_file=$1/tflite_graph/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3','FeatureExtractor/MobilenetV2/expanded_conv_9/add' --inference_type=FLOAT --allow_custom_ops
`

the resulted graph is like this : 

<img width="1659" alt="Screenshot 2021-09-02 at 7 38 20 PM" src="https://user-images.githubusercontent.com/74127861/131858728-3b53a171-2e37-4848-ab57-2932f20d52b4.png">

When I run the tflite model on the android with the XNNPack or CPU, I am able to get the different output  of the intermediate layer which is coming at index 4 
code snippet : 
```
try {
      Interpreter.Options options = new Interpreter.Options();
      options.setNumThreads(NUM_THREADS);
      options.setUseXNNPACK(true);
      d.tfLite = new Interpreter(modelFile, options);
      // 4th index for intermediate output
      int[] shape = d.tfLite.getOutputTensor(4).shape();
      d.tfLiteOptions = options;
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

```

But when i run the same model on GPU delegate, I am getting the same output for every different frame I am passing. The other output like (bbox, score,num_detection, confidences) changes but the intermediate output remains the same 
```
try {
      Interpreter.Options options = new Interpreter.Options();
      CompatibilityList compatList = new CompatibilityList();
      GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
      GpuDelegate gpuDelegate = new GpuDelegate(delegateOptions);
      options.addDelegate(gpuDelegate);

      d.tfLite = new Interpreter(modelFile, options);
      // 4th index for intermediate output
      int[] shape = d.tfLite.getOutputTensor(4).shape();
      d.tfLiteOptions = options;
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
```

**System information**
- Mobile device: OnePlus 6T, Mi Note5 pro
- TFOD Api TensorFlow version : 1.15
- Android Tensorflow Lite version: 2.4.0

Need help to figure out what may be going wrong

[detect_10.tflite.zip](https://github.com/tensorflow/tensorflow/files/7099629/detect_10.tflite.zip)

**Comment by sanatmpa1** [comment]
@letdivedeep,

I see that you have mentioned the TF version as `1.5` which is no more supported officially. Can you try updating to latest stable version i.e `2.6.0` and let us know if the issue still persists? Thanks!

**Comment by letdivedeep** [comment]
@sanatmpa1 Thanks for the response

 I mean to say I trained a model with tfod API with TensorFlow 1.15 version. But while inferencing on the android I used 'org.tensorflow:tensorflow-lite:2.4.0' version

**Comment by letdivedeep** [comment]
@ymodak .. Just to update you on this part.

I even tried to run the model on GPU delegate on the Linux platform, it gives the same issue

**Comment by impjdi** [comment]
Because GPU delegate reuses memory objects, you cannot dump intermediate tensors.  If you really wish to do so, you have to insert a fake node, e.g. ADD 1e-6, and declare the output of that op as graph output.

**Comment by letdivedeep** [comment]
@impjdi  thanks for the suggestion.  I will try this approach and let you knaow

**Comment by letdivedeep** [comment]
> Because GPU delegate reuses memory objects, you cannot dump intermediate tensors. If you really wish to do so, you have to insert a fake node, e.g. ADD 1e-6, and declare the output of that op as graph output.

@impjdi this worked. thanks for the inputs
