### ISSUE TITLE
Can not install python3-pip

### ISSUE THREAD

**Issue by Burtininkas69** [tensorflow/tensorflow#51805]
Hello, I am new to python. I was trying to install pip, but I get and error whitch I can not find a way to fix it
Code that I am running:
`sudo apt install python3 python3-pip`
What I am getting:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.9.4-1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 nodejs : Depends: libnode72 (= 12.21.0~dfsg-3ubuntu1) but it is not going to be installed
 python3-pip : Depends: python3-setuptools but it is not going to be installed
               Depends: python3-wheel but it is not going to be installed
               Depends: python-pip-whl (= 20.3.4-1ubuntu2) but it is not going to be installed
               Recommends: python3-dev (>= 3.2) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

```
Also tried to do `sudo apt --fix-broken install` like statet in the last line, but got this:
```

Unpacking nodejs (16.8.0-deb-1nodesource1) over (12.21.0~dfsg-3ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_16.8.0-deb-1nodesource1_amd64.deb (
--unpack):
 trying to overwrite '/usr/share/doc/nodejs/api/process.html', which is also in package nodejs-do
c 12.21.0~dfsg-3ubuntu1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_16.8.0-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)


```

Any ideas on how to fix it?
Running Linux PopOs
npm -v: 6.14.15

**Comment by mohantym** [comment]
Hi @Burtininkas69 , This does not look like a Tensorflow issue. You can have a look a the instructions[ here ](https://docs.python-guide.org/starting/install3/linux/) though in case you might have missed some steps.

**Comment by sravansai04** [comment]
@Burtininkas69  You can find the Solution [here](https://askubuntu.com/questions/148383/how-to-resolve-dpkg-error-processing-var-cache-apt-archives-python-apport-2-0)

**Comment by mihaimaruseac** [comment]
Not a TF issue, please open only TensorFlow related issues here.

**Comment by elisha136** [comment]
I also encountered same and I found this solution on stackoverflow which works.
First $ sudo apt-get install aptitude and then install python3-pip with $ sudo aptitude install python3-pip
