### ISSUE TITLE
Connection to pythong

### ISSUE THREAD

**Issue by mateusz1981** [tensorflow/tensorflow#51814]
I got folowing error using tensorflow in R
```
> library(tensorflow)
> tf$constant("Hellow Tensorflow")
Error in system2(python, stdout = TRUE, args = c("-c", shQuote("import sys; import platform; sys.stdout.write(platform.architecture()[0])"))) : 
  'CreateProcess' failed to run 'C:\Python27\ArcGIS10.8\python.exe -c "import sys; import platform; sys.stdout.write(platform.architecture()[0])"'

**Comment by mohantym** [comment]
Hi @mateusz1981 ! Could  you please fill the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks
