### ISSUE TITLE
Converting Hard Swish activation to TFLite efficiently

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#51819]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

when using a hard swish activation:
```
x = 0.16667 * x * tf.nn.relu6(x+3)
```
what shows up in the Tensorflow Lite model is is just the computation graph of the above definition:
x
 -> multiply by 0.167 
 -> add 3-> relu6 (those are fused together)
         -> multiply results from above
(see diagram [here](https://imgur.com/a/OZcWZWQ))

 ** Expected behavior ** 

Tensorflow Lite has a hard swish operator already. Question is, how should I define the computation in Tensorflow such that when converted to TFLite, the output would be a single hard swish node for this activation?

**Comment by renjie-liu** [comment]
I think if you do

```
tf.nn.relu6(x+3.0) * 0.1666666666666 * x
```

the fusion should works

**Comment by yakovdan** [comment]
Confirmed. It works. 

Can you please explain why 
```x = 0.16667 * x * tf.nn.relu6(x+3)``` 
does not work but
```tf.nn.relu6(x+3.0) * 0.1666666666666 * x```
works? 
Is it a matter of types, or operator order or something else?

**Comment by renjie-liu** [comment]
you can check out our existing fusion patterns here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/optimize_patterns.td#L253-L317

see two reasons your ops are not fused:

* operator order
* 0.1666666666666 does not match 0.16667

**Comment by yakovdan** [comment]
Ok, that's great! Thank you.
