### ISSUE TITLE
Building TFlite for windows with flex delegate error

### ISSUE THREAD

**Issue by jobpasin** [tensorflow/tensorflow#51816]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.6.0
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: None
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): MSVC 2019 (Not sure how to check more in detail)
- CUDA/cuDNN version: 10.1/ 7.6.5
- GPU model and memory: Nvidia GTX 1050

**Describe the problem**
I want to build tflite for windows with support for Tensorflow ops outside of standard tflite operation.
So, I followed this guide: https://www.tensorflow.org/lite/guide/ops_select#c
Although it is ambiguous and since I am pretty new in this field, I looked around for other site and do the following.

Note that I would like to build TF with no CUDA support. (Only using cpu)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Add "//tensorflow/lite/delegates/flex:delegates" to `deps` in `tensorflow/tensorflow/lite/BUILD`
2. Using following command to build tflite
`bazel build --config=monolithic -c opt --cxxopt='--std=c++11' //tensorflow/lite:libtensorflowlite.so`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Here are some part of the result logs:
```   
 SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\jobpa\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\jobpa\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/HostX64/x64/link.exe @bazel-out/x64_windows-opt/bin/tensorflow/lite/libtensorflowlite.so-2.params
Execution platform: @local_execution_config_platform//:platform
LINK : warning LNK4044: unrecognized option '/s'; ignored
builtin_ops.lib(register.obj) : error LNK2005: "public: __cdecl tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver(void)" (??0BuiltinOpResolver@builtin@ops@tflite@@QEAA@XZ) already defined in builtin_ops_all_linked.lo.lib(register.obj)
builtin_ops.lib(register.obj) : error LNK2005: "public: virtual class std::vector<class std::unique_ptr<struct TfLiteDelegate,void (__cdecl*)(struct TfLiteDelegate *)>,class std::allocator<class std::unique_ptr<struct TfLiteDelegate,void (__cdecl*)(struct TfLiteDelegate *)> > > __cdecl tflite::ops::builtin::BuiltinOpResolver::GetDelegates(int)const " (?GetDelegates@BuiltinOpResolver@builtin@ops@tflite@@UEBA?AV?$vector@V?$unique_ptr@UTfLiteDelegate@@P6AXPEAU1@@Z@std@@V?$allocator@V?$unique_ptr@UTfLiteDelegate@@P6AXPEAU1@@Z@std@@@2@@std@@H@Z) already defined in builtin_ops_all_linked.lo.lib(register.obj)
builtin_ops.lib(register.obj) : error LNK2005: "public: virtual class std::vector<class std::unique_ptr<struct TfLiteDelegate,void (__cdecl*)(struct TfLiteDelegate *)>,class std::allocator<class std::unique_ptr<struct TfLiteDelegate,void (__cdecl*)(struct TfLiteDelegate *)> > > __cdecl tflite::ops::builtin::BuiltinOpResolverWithoutDefaultDelegates::GetDelegates(int)const " (?GetDelegates@BuiltinOpResolverWithoutDefaultDelegates@builtin@ops@tflite@@UEBA?AV?$vector@V?$unique_ptr@UTfLiteDelegate@@P6AXPEAU1@@Z@std@@V?$allocator@V?$unique_ptr@UTfLiteDelegate@@P6AXPEAU1@@Z@std@@@2@@std@@H@Z) already defined in builtin_ops_all_linked.lo.lib(register.obj)
LINK : fatal error LNK1189: library limit of 65535 objects exceeded
Target //tensorflow/lite:libtensorflowlite.so failed to build
```

According to this [post](https://github.com/tensorflow/tensorflow/issues/43367), I tried to add `--copt=/bigobj` but that does not help either.

I'm not sure if I did something wrong, or if there is a limitation of adding flex delegate to tflite on windows...

**Comment by terryheo** [comment]
Please check https://github.com/tensorflow/tensorflow/issues/43367#issuecomment-1021211279
