### ISSUE TITLE
Better support for initializing without explicit initializer for tf.string

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#5181]
When we use `tf.get_variable()` we have to provide `initializer` except `DT_FLOAT` dtype, or it causes error.

```
tf.get_variable(name="a", shape=(), dtype=tf.string)

TypeError: Expected string, got -1.7320508075688772 of type 'float' instead.
```

While I think it's unfriendly to TensorFlow users. So I want to open a PR to support initializing from non initializer for `tf.string`. 

The same issue for `tf.int` is [#4419](https://github.com/tensorflow/tensorflow/issues/4419).
And I have opend a PR [#4816](https://github.com/tensorflow/tensorflow/pull/4826)  to fix that including `tf.string`, but @ebrevdo suggested  me to open a separate PR fot `tf.string`.

@aselle Could you ensure is it a issue and may I open a PR to fix it?

**Comment by ebrevdo** [comment]
Andrew, you know best if there's a numpy-like way to do this.

**Comment by aselle** [comment]
Looks to be resolved. Thanks @DjangoPeng!
