### ISSUE TITLE
Facing issue while initializing parameters in tensorflow.

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51817]
![2](https://user-images.githubusercontent.com/26819449/131990627-7504f592-80e1-478f-ab3d-19a48d7b50b9.JPG)

![1](https://user-images.githubusercontent.com/26819449/131990652-bc585eb8-0be2-4ace-b3c2-b88f05da8e9c.JPG)

Where i am lacking.
I have already ready tensor flow documentation.
Just tell me what should I do.
tf_version_2.3.0
Thanks!

**Comment by mohantym** [comment]
Hi @starboyvarun 
This is not a bug or feature request, Please open these type of  issues in [tf discussion forum ](https://discuss.tensorflow.org/)as there is a larger community there.   

```
initializer = tf.keras.initializers.GlorotNormal()
values = initializer(shape=(2, 2))

print(values.numpy())

```
Reference :https://www.tensorflow.org/api_docs/python/tf/keras/initializers/GlorotNormal#examples_2
Thank you!

**Comment by starboyvarun** [comment]
@mohantym I already told you I have read the documentation.
I asked where I am lacking.
you just copying and pasting the code here.
Thanks!.

**Comment by mohantym** [comment]
Hi @starboyvarun !This is not a bug or feature request, for any further queries you may open this issue in tf discussion[ forum](https://discuss.tensorflow.org/) as there is a larger community there.Thank you!
