### ISSUE TITLE
Tensorflow sort changes values in output list to 0 when the tensor datatype is tf.float32 but not for tf.float64

### ISSUE THREAD

**Issue by mohanr** [tensorflow/tensorflow#51820]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): M1 Macbook Air where is the issue is seen / Intel Mac where I don't see any issue
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
When n<=16 it sorts the values properly but when n>16 it sorts the list and then changes the values at 
position 16 and higher to  value  -0.

import tensorflow as tf

n=17
a = tf.random.uniform(shape=[n], dtype=tf.float32)
print(a)
print(tf.sort(a))

tf.Tensor(
[ 0.00088847  0.03644979  0.06494105  0.07945895  0.13768506  0.153288
  0.27231824  0.39109504  0.4003389   0.41191268  0.48915362  0.528106
  0.5799836   0.6125376   0.65293264  0.8135816  -0.        ], shape=(17,), dtype=float32)

on M1 Macbook Air ( tensorflow 2.5.0 ) and

tf.Tensor(
[0.41191268 0.48915362 0.65293264 0.6125376  0.00088847 0.03644979
 0.13768506 0.528106   0.27231824 0.4003389  0.5799836  0.83420205
 0.06494105 0.39109504 0.8135816  0.153288   0.07945895], shape=(17,), dtype=float32)

on Intel Mac ( tensorflow 2.4,3 )

```
**Describe the expected behavior**

```
tf.Tensor(
[0.41191268 0.48915362 0.65293264 0.6125376  0.00088847 0.03644979
 0.13768506 0.528106   0.27231824 0.4003389  0.5799836  0.83420205
 0.06494105 0.39109504 0.8135816  0.153288   0.07945895], shape=(17,), dtype=float32)



```

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): 
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @mohanr ,Please look at the [comment ](https://github.com/tensorflow/tensorflow/issues/51499#issuecomment-904821790)of the this similar[ issue ](https://github.com/tensorflow/tensorflow/issues/51499)  . Try with 
`a = tf.random.uniform(shape=[n], dtype=tf.float64)`
