### ISSUE TITLE
[Tensorflow Executor Dialect]  

### ISSUE THREAD

**Issue by FullZing** [tensorflow/tensorflow#51823]
**MLIR operation format is :**
operation            ::= op-result-list? (generic-operation | custom-operation)
                         trailing-location?
generic-operation    ::= string-literal `(` value-use-list? `)`  successor-list?
                         region-list? dictionary-attribute? `:` function-type
custom-operation     ::= bare-id custom-operation-format
op-result-list       ::= op-result (`,` op-result)* `=`
op-result            ::= value-id (`:` integer-literal)
successor-list       ::= `[` successor (`,` successor)* `]`
successor            ::= caret-id (`:` bb-arg-list)?
region-list          ::= `(` region (`,` region)* `)`
dictionary-attribute ::= `{` (attribute-entry (`,` attribute-entry)*)? `}`
trailing-location    ::= (`loc` `(` location `)`)?

**here is tf_executor.graph operation :**
%fetches = tf_executor.graph : tensor<*xf32> {
  // Operations in the current block execute when their inputs are ready,
  // possibly concurrently.
  // Only operations in the tf_executor dialect are expected here.
  // Ops can return multiple outputs and a control token for control
  // dependencies.
  // We don’t mention the control token in the return type here, it is implicit.
  %0, %ctl0 = tf_executor.opA %feed#0, %feed#1 : tensor<*xf32>
  %1, %ctl1 = tf_executor.opB : tensor<*xf32>
  %2, %ctl2 = tf_executor.opC %1, %ctl0 : tensor<*xf32>
  %3, %ctl3 = tf_executor.opD %2 : tensor<*xf32>
  tf_executor.fetch %3 : tensor<*xf32>
} // end of the “tf_executor.graph" operation/region

According to Operation format,   {} stands for dictionary-attribute
obviously, tf_executor.graph operation looks like abnormal case
the {} of tf_executor consists of several operations

could anyone explain and point out how to understand tf_executor.graph operation
many thanks

**Comment by sushreebarsa** [comment]
@FullZing Could you please have a look at the[ link1](https://www.tensorflow.org/mlir/includes/tf_passes), [link2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/ir/tf_executor_ops.td) and let us know if it helps ?

**Comment by FullZing** [comment]
Hi @sushreebarsa 

thank you for replying
but my problem still exists
1.   i checked the Region defination in MLIR from 
 https://mlir.llvm.org/docs/LangRef/#regions
and it shows a sample with region 
  "any_op"(%a) ({ // if %a is in-scope in the containing region...
	 // then %a is in-scope here too.
    %new_value = "another_op"(%a) : (i64) -> (i64)
  }) : (i64) -> (i64)

2.  check tf_executor.graph Operation description from https://github.com/tensorflow/community/blob/master/rfcs/20190612-mlir-dialect.md
and it shows a sample with region
%fetches = tf_executor.graph : tensor<*xf32> {
  // Operations in the current block execute when their inputs are ready,
  // possibly concurrently.
  // Only operations in the tf_executor dialect are expected here.
  // Ops can return multiple outputs and a control token for control
  // dependencies.
  // We don’t mention the control token in the return type here, it is implicit.
  %0, %ctl0 = tf_executor.opA %feed#0, %feed#1 : tensor<*xf32>
  %1, %ctl1 = tf_executor.opB : tensor<*xf32>
  %2, %ctl2 = tf_executor.opC %1, %ctl0 : tensor<*xf32>
  %3, %ctl3 = tf_executor.opD %2 : tensor<*xf32>
  tf_executor.fetch %3 : tensor<*xf32>
} // end of the “tf_executor.graph" operation/region


compared tf_executor.graph with any_op,   you can find parentheses for region is missing in tf_executor
so i wonder what is his grammar ？

3.  from  https://mlir.llvm.org/docs/LangRef/,   failed to find any same usage

please check again

**Comment by sushreebarsa** [comment]
@FullZing 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
