### ISSUE TITLE
Keras model with TPUStrategy get InternalError

### ISSUE THREAD

**Issue by howl-anderson** [tensorflow/tensorflow#51824]
When I fit a Keras Model with TPUStrategy, it got following errors:
```
InternalError: 7 root error(s) found.
  (0) Internal: {{function_node __inference_train_function_163744}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1630677855.531027249","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1630677855.531025671","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
Executing non-communication op <MultiDeviceIteratorGetNextFromShard> originally returned UnavailableError, and was replaced by InternalError to avoid invoking TF network error handling logic.
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
	 [[Pad_9/paddings/_152]]
  (1) Internal: {{function_node __inference_train_function_163744}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1630677855.531027249","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1630677855.531025671","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
Executing non-communication op <MultiDeviceIteratorGetNextFromShard> originally returned UnavailableError, and was replaced by InternalError to avoid invoking TF network error handling logic.
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
	 [[cond_14/switch_pred/_140/_90]]
  (2) Internal: {{function_node __inference_train_function_163744}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1630677855.531027249","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1630677855.531025671","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
Executing non-communication op <MultiDeviceIteratorGetNextFromShard> originally returned UnavailableError, and was replaced by InternalError to avoid invoking TF network error handling logic.
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
	 [[TPUReplicate/_compile/_10521736726166110026/_4/_194]]
  (3) Internal: {{function_node __inference_train_function_163744}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
: ... [truncated]
```

TensorFlow Version: 
v2.6.0-0-g919f693420e 2.6.0

**Standalone code to reproduce the issue**

The code used to reproduce this error can be found at https://drive.google.com/file/d/1ceB5VBwFd87Z0ANa_91vhvrOdG4SJQLY/view?usp=sharing

**Comment by mohantym** [comment]
Hi @howl-anderson !We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by howl-anderson** [comment]
Hi  @mohantym, I have added the TF version and colab link to reproduce the issue. Steps followed before I ran into this error are also list in the colab link.

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you look into this issue ! providing gist in TF [2.5](https://colab.research.google.com/gist/mohantym/0ed4686d38b613687b0e8d588953d496/layers_crf_with_tpu.ipynb?authuser=1#scrollTo=l3WJsqUBxpFX) ,[2.6 ](https://colab.research.google.com/gist/mohantym/961390e60a7b3c780a46ec2abc506802/layers_crf_with_tpu.ipynb?authuser=1#scrollTo=HKbmByByTVEP), [nightly ](https://colab.research.google.com/gist/mohantym/ce0ed003afee869053e792ef51bee3c7/layers_crf_with_tpu.ipynb?authuser=1#scrollTo=pFMeRQTrPI1B)for reference.

**Comment by howl-anderson** [comment]
Thank you @mohantym for your swift response.

**Comment by Saduf2019** [comment]
@howl-anderson 
Could you please refer to [similar error](https://github.com/tensorflow/tensorflow/issues/44963) issue and try with 2.4, also [link](https://github.com/keras-team/keras-io/issues/150).
In case the issue still persists:

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by howl-anderson** [comment]
Hi @Saduf2019, thank you for your help.  My code target is TF 2.6. So, it surely has `StringLookup` issue under TF 2.5.  The true issue will show under TF 2.6, you can reproduce it from this code: https://drive.google.com/file/d/1ceB5VBwFd87Z0ANa_91vhvrOdG4SJQLY/view?usp=sharing . Sorry for the confusion. And thank you for your reminder, I will move this issue to keras-team/keras repo.

**Comment by howl-anderson** [comment]
Move this issue to keras-team/keras#15317
