### ISSUE TITLE
Build error: missing dependency declarations for the following files included by 'external/jpeg_archive

### ISSUE THREAD

**Issue by landinggao** [tensorflow/tensorflow#5182]
I have problem when building r0.9 source code without GPU, always have below errors:
ERROR: /home/hadoop/.cache/bazel/_bazel_hadoop/688bf433e3d98b943fba735d08e17b8c/external/jpeg_archive/BUILD:77:1: undeclared inclusion(s) in rule '@jpeg_archive//:jpeg':
this rule is missing dependency declarations for the following files included by 'external/jpeg_archive/jpeg-9a/jdatasrc.c':
'bazel-out/host/genfiles/external/jpeg_archive/jconfig.h'.

The error file is changed if I run bazel build again, in fact the file exists in the directory.
There is no problem when I build TF master source code, version 0.11.
bazel version is 0.3.2-jdk7.
Build command:
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --local_resources 4096,.5,1.0

I saw some fix  are related with GPU, but I didn't configure GPU.

**Comment by drpngx** [comment]
It looks like there was a bug in the BUILD file. You should add a dependency. It's probably a new check with bazel 0.3.2 that wasn't there when we released r0.9.

**Comment by landinggao** [comment]
Thanks @drpngx, I'll try to figure out it.

**Comment by drpngx** [comment]
OK, let me knowhow this goes.

**Comment by landinggao** [comment]
Sorry, I'm failed to fix it. But I found a walkaround:
I built the master branch successfully, then checkout to branch r0.9, and built it with --fetch=fasle, it's done.
In fact, before that I tried fetch //..., but it always failed for some packages.

**Comment by drpngx** [comment]
Great to see you figured it out!
