### ISSUE TITLE
Custom signatures not working with Subclasssed Keras Model

### ISSUE THREAD

**Issue by sumitbinnani** [tensorflow/tensorflow#51827]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
When saving keras_models (checked for Subclassed Model) and providing custom signatures, `keras_model.save(export_dir, signatures)`  does not work and the saved model does not have the exported signature. The custom signature however works if we are using `tf.saved_model.save(keras_model, export_dir, signatures)`.

**Describe the expected behavior**
tf.saved_model.save(keras_model, export_dir, signatures) and `keras_model.save(export_dir, signatures)` should have similar signatures.

**Comment by mohantym** [comment]
Hi @sumitbinnani !Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by mohantym** [comment]
Ok @sumitbinnani ,Feel free to close this one . Thank!

**Comment by sumitbinnani** [comment]
Tracking in keras-team/keras#15324
