### ISSUE TITLE
Problems when using "bazel build"  to download ImageNet data

### ISSUE THREAD

**Issue by yichengwang125** [tensorflow/tensorflow#5183]
Hi all,
I tried to download the Imagenet data with the code provided in Inception model, but there was a problem when I used code:
 `bazel build inception/download_and_preprocess_imagenet`
The tensorflow was installed in a Singularity container. And the environment is a high-performance cluster.
### Running Code:
`[yichengwang125@i21a-s2 ~]$ ml load tensorflow`
`[yichengwang125@i21a-s2 ~]$ cd ufrc/image/image/models-master/inception/`
`[yichengwang125@i21a-s2 inception]$ touch WORKSPACE`
`[yichengwang125@i21a-s2 inception]$ DATA_DIR=$HOME/image/`
`[yichengwang125@i21a-s2 inception]$ bazel build inception/download_and_preprocess_imagenet`
`WARNING: Output base /home/yichengwang125/.cache/bazel/_bazel_yichengwang125/bad337a79300dc0e5a9ba2ac2e22c48a' is on NFS. This may lead to surprising failures and undetermined behavior.`
`WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target... `
`Target //inception:download_and_preprocess_imagenet up-to-date:
  bazel-bin/inception/download_and_preprocess_imagenet
INFO: Elapsed time: 2.952s, Critical Path: 0.02s`
`ERROR  : Could not remove session directory /tmp/.singularity-session-4308.2575366.144117625721484141: Device or resource busy`

### Environment info
Operating System:
Red Hat Enterprise Linux Server release 6.7 (Santiago)

### I tried to 
`lsof +D /tmp/.singularity-session-4308.2575366.144117625721484141`
but only shows
`COMMAND   PID     USER             FD   TYPE    DEVICE SIZE/OFF       NODE NAME`
`java         25707  yichengwang125  7r   DIR             8,3            4096 43779163 /tmp/.singularity-session-4308.2575366.144117625721484141`

**Comment by drpngx** [comment]
Did you try to build anything else?

**Comment by drpngx** [comment]
Perhaps also put this: `workspace(name = "inception")` in `WORKSPACE`?

**Comment by yichengwang125** [comment]
I tried with basic hello world code, 
```
$ bazel build :hello
bazel build :hello
ERROR  : Could not obtain shared lock on /tmp/.singularity-session-4308.2575366.144117625721484141: Resource temporarily unavailable
ABORT  : Retval = 255
```

**Comment by dotasheepliu** [comment]
I think that could possibly be the problem of **singularity**. By the way, you should put your code in a single code block for easier reading.

**Comment by drpngx** [comment]
Sorry I'm not familiar with Singularity. I think it's a config issue where you need to give some more permissions.

@davidzchen bazel doesn't work on Singularity, if you're interested.

**Comment by davidzchen** [comment]
That's interesting. I'm not too familiar with Singularity either.

@yichengwang125 Can you open a bug on bazelbuild/bazel for this issue? Thanks!

**Comment by drpngx** [comment]
Feel free to link the issue once created.

**Comment by yichengwang125** [comment]
I created an issue on bazel
https://github.com/bazelbuild/bazel/issues/1989
