### ISSUE TITLE
tf.linalg.diag issue

### ISSUE THREAD

**Issue by sidhomj** [tensorflow/tensorflow#51843]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8.11

**Describe the current behavior**
When providing the tf.linalg.diag function an input > length of 32, the function returns this error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [32,32] vs. shape[1] = [1,1] [Op:ConcatV2] name: concat
```

**Describe the expected behavior**
The function should return a tensor of shape [n,n] no mater how large the tensor is.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

#input
input_data = np.ones(33)

#model
input = tf.keras.layers.Input([],dtype=tf.float32)
out = tf.linalg.diag(input)
model = tf.keras.Model(inputs=input, outputs=out)

#inference
pred = model.predict(input_data)
```

**Comment by collinzrj** [comment]
Keras is expecting to receive inputs in batch
```
import tensorflow as tf
import numpy as np

#input
input_data = np.ones((1, 33))

#model
input = tf.keras.layers.Input([],dtype=tf.float32)
out = tf.linalg.diag(input)
model = tf.keras.Model(inputs=input, outputs=out)

#inference
pred = model.predict(input_data)

print(pred)
print(pred.shape)
```
It works

The `predict` method of model has an attribute `batch_size`, the doc says

```
batch_size: Integer or `None`.
    Number of samples per batch.
    If unspecified, `batch_size` will default to 32.
    Do not specify the `batch_size` if your data is in the
    form of dataset, generators, or `keras.utils.Sequence` instances
    (since they generate batches).
```
In your case, the code is seperated into half, I think that produces the problem

**Comment by sidhomj** [comment]
thank you, i realized this soon after!
