### ISSUE TITLE
OS Error while installing tensorflow on virtualenv

### ISSUE THREAD

**Issue by pathikg** [tensorflow/tensorflow#51841]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow version: 2.6.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv with pip install --upgrade tensorflow
- GPU model and memory: none (Using CPU)

**Describe the problem** : 
I tried installing tensorflow on my local machine in a virtual environment I got this error  : 
```
Installing collected packages: tensorflow
ERROR: Could not install packages due to an OSError: [Errno 2] 
No such file or directory: 'E:\\Pathik\\KJ\\internships\\Facial Expression recognition\\Github Repo\\Emotion-recognition\\venv\\Lib\\sitepackages\\tensorflow\\include\\external\\cudnn_frontend_archive\\_virtual_includes\\cudnn_frontend\\third_party\\cudnn_frontend\\include\\cudnn_frontend_EngineConfigGenerator.h'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
virtualenv venv
.\venv\Scripts\activate 
pip install --upgrade tensorflow
```

**Any other info / logs**
All the dependencies were successfully installed except the tensorflow.

**Comment by sushreebarsa** [comment]
@pathikg Could you please have a look at the [link](https://www.tensorflow.org/install/source_windows) and similar [issue1](https://github.com/tensorflow/tensorflow/issues/46934),[issue2](https://stackoverflow.com/questions/59302043/error-when-installing-tensorflow-python-3-8) .Please let us know if it helps?

**Comment by pathikg** [comment]
Yes enabling long_path solved the error , thanks 👍

**Comment by sushreebarsa** [comment]
@pathikg Could you Please close the ticket if it is resolved for you ?Thank you!

**Comment by pathikg** [comment]
Yes
