### ISSUE TITLE
Can't run iOS makefile on MacOS Sierra, required file 'build-aux/ltmain.sh' not found

### ISSUE THREAD

**Issue by KevinAyuque** [tensorflow/tensorflow#5184]
Well from now on I should probably think twice before I update. Before it used to work correctly but now I get this message when i run `compile_ios_protobuf.sh`

```
+ ./autogen.sh
+ autoreconf -f -i -Wall,no-obsolete
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:30: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1
```

I hav MacOS Sierra installed and Xcode 8. If anyone has a workaround for this please let me know.

**Comment by drpngx** [comment]
Ugh, configure.

@jart if you're interested.

**Comment by MattSich** [comment]
running into the same issue

**Comment by drpngx** [comment]
Could you try this? Verify that glibtoolize works first?

https://github.com/Homebrew/legacy-homebrew/issues/43874

**Comment by jart** [comment]
Thanks for bringing this to our attention @KevinAyuque. The problem is most likely upstream and related to the Homebrew issue @drpngx provided. If we have reason to suspect otherwise, please let us know, and I'll re-open this issue.

**Comment by MattSich** [comment]
@KevinAyuque this solved my issue:
`cd "$(brew --repository)" && git fetch && git reset --hard origin/master`

source: https://github.com/Homebrew/brew/issues/557

**Comment by KevinAyuque** [comment]
Thanks, `brew uninstall libtool && brew install libtool` worked for me but now i have another error `configure: error: cannot run C compiled programs` which I imagine has something to do with my Xcode. I'll post here if I find a solution.
