### ISSUE TITLE
The ModifyGraphWithDelegate function fails on some devices.

### ISSUE THREAD

**Issue by hotstone1993** [tensorflow/tensorflow#51842]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac OS Big sur (11.3.1)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  Galaxy s21 ultra
- TensorFlow installed from (source or binary): source  
- TensorFlow version: r2.6
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.7.2

I currently use libtensorflowlite_gpu_delegate.so which compiled from source(r2.6).
ModifyGraphWithDelegate function works fine on Galaxy Note 10.
But, it's not working in Galaxy s21 ultra.
(returns kTfLiteApplicationError.)

Does it work according to the device? 
(Can't use gpu delegate for Galaxy s21 ultra?)
Or do I need to set additional options?

(Currently I am setting it as the default as below.)
```
  TfLiteGpuDelegateOptionsV2 option = TfLiteGpuDelegateOptionsV2Default();
  delegate_ = TfLiteGpuDelegateV2Create(/*default options=*/&option);
  TfLiteStatus result = interpreter_->ModifyGraphWithDelegate(delegate_);

  if (result != kTfLiteOk) {
    return kAudioNodeError;
  }
```

I built the libraries as follows.

libtensorflowlite.so(3.7MB): bazel build -c opt --config android_x86 android_x86_64 android_arm android_arm64 --define tflite_with_xnnpack=true
libtensorflowlite_gpu_delegate.so(98.5MB): bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so 

Thanks!!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @hotstone1993 ,Could you look into  [link ](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter?hl=zh-cn#modifygraphwithdelegate)of this error.

**Comment by hotstone1993** [comment]
thanks for answering.
But, I already read the page.

"Delegation failed to be applied due to the incompatibility with the TfLite runtime" 
Does this sentence mean that some devices may not work because of compatibility?

Is there no way??

**Comment by terryheo** [comment]
Each device could have different OpenCL or OpenGL version and capability so it is possible.

But could you share the logcat dump of  Galaxy s21 Ultra? I'm curious what kind of issue the device has.

**Comment by hotstone1993** [comment]
Sorry now that I check, the model is the problem.

my log is 
"Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#42 is a dynamic-sized tensor)."

thanks for your help
