### ISSUE TITLE
Cannot load saved tflite model when model contains dropout. However quantization-aware model is fine.

### ISSUE THREAD

**Issue by HongtaoYang** [tensorflow/tensorflow#51848]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): No 
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.9
- CUDA/cuDNN version:  cuDNN-8.1.1.33. CUDA-11.2.0

**Describe the current behavior**
If a model contains dropout layers, if can be converted to tflite, but the tflite model cannot be loaded. The error message is:
```
ValueError: Did not get operators or tensors in subgraph 1.
```

Confusingly, if I make the model quantization-aware, the model can be successfully converted to tflite and loaded. Does QAT automatically remove dropout?

**Describe the expected behavior**
If a tflite model that contain dropout is not supported, then the desired behavior are:

1.  Raise an error during tflite conversion instead of at runtime. Or
2. Remove the dropout operation during tflite conversion.

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import tensorflow_model_optimization as tfmot


quantize_annotate_layer = tfmot.quantization.keras.quantize_annotate_layer
quantize_apply = tfmot.quantization.keras.quantize_apply



def get_model(quantization_aware: bool = False):
    input_embeddings = tf.keras.Input(shape=(512,), dtype=tf.float32, name="input_embeddings")
    is_training = tf.keras.Input(shape=(), dtype=tf.bool, name="is_training")

    x = tf.keras.layers.Dropout(rate=0.5)(inputs=input_embeddings, training=is_training)

    if quantization_aware:  # apply quantization to dense layer and return quantization-aware model
        out = quantize_annotate_layer(
            tf.keras.layers.Dense(units=512,name="dense")
        )(x)

        model = quantize_apply(
            tf.keras.Model(
                inputs=[input_embeddings, is_training],
                outputs=[x, out],
                name="toy_model",
            )
        )
    else: # return vanilla model
        out = tf.keras.layers.Dense(units=512,name="dense")(x)
        model = tf.keras.Model(
            inputs=[input_embeddings, is_training],
            outputs=[x, out],
            name="toy_model",
        )

    return model

def convert_to_tflite(saved_model_path, output_model_path):
    converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_path))
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS,
    ]
    tflite_quant_model = converter.convert()

    with open(output_model_path, "wb") as fh:
        fh.write(tflite_quant_model)



model = get_model(quantization_aware=False)  # set to False will raise the error. Set to True the code runs successfully.
input_data = np.random.rand(16, 512)
embeddings, out = model([input_data, True])

model.save("toy_model")

convert_to_tflite("toy_model", "toy_model.tflite")
interpreter = tf.lite.Interpreter("toy_model.tflite")
```

I'm wondering how should I deal with dropout layer in tflite? As dropout is essential for training, how can I export a trained model without dropout? This is [a similar issue](https://github.com/tensorflow/tensorflow/issues/44232), and I'm not satisfied by the workaround proposed there.

**Comment by HongtaoYang** [comment]
Oh I figured out what I did wrong and also the correct way to use dropout. 

Basically I shouldn't explicitly pass the `training` argument to dropout layer, it is handled during model invocation where we can tell the model to be in training mode by `out = model(input_batch, training=True`. This way tflite can handle dropout correctly.

**Comment by pjpratik** [comment]
@HongtaoYang I was checking if this is still an issue.

I have tried with TF Nightly 2.13.0-dev20230308 and TF MOT 0.7.3. I did not face any error while `quantization_aware = False`. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/7a37eb446f1a59ac8e2335e7bd4c6f91/51848.ipynb#scrollTo=Dr2Qz0UQIDte).

It is observed that dropout is indeed removed during the conversion when observed in netron.

Thanks.
