### ISSUE TITLE
Error when reading .wav files using TPU

### ISSUE THREAD

**Issue by invoxiaglo** [tensorflow/tensorflow#51856]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab

**Describe the current behavior**

I am trying to read .wav files in my input pipeline and train on TPU. I am using tfio.audio.AudioIOTensor but it is not working with TPU.

Here is a colab that shows the error:
https://colab.research.google.com/drive/1gSP3bhmDkMFwHwxWWc3B3hdR9SNA0hM9#scrollTo=FItPzgJ1xJzZ

The error is the following:
```
NotFoundError: Op type not registered 'IO>AudioReadableInit' in binary running on n-6a025964-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [Op:BatchDatasetV2]
```

Is there another way to decode .wav files when using TPU?

**Comment by Saduf2019** [comment]
@invoxiaglo 
Please refer to [this link](https://github.com/tensorflow/io/issues/716#issuecomment-879999571) and let us know.
You can use tf.audio.decode_wav,it is part of tensorflow and will eliminate tfio, avoiding the error faced.
