### ISSUE TITLE
Wrong training count in eager execution mode!

### ISSUE THREAD

**Issue by Nima-pw** [tensorflow/tensorflow#51860]
Hi,

I am using MNIST dataset with 54,000 training data on a CNN model. TensorFlow version 2.6.0.

When the code runs in enabled eager execution, in the training step only 844 data are used in each epoch!
 I think the output shots is clear:

`1- When eager execution is enabled in default`
![image](https://user-images.githubusercontent.com/84374136/132291914-1b899fd0-ef9d-4975-acfe-f5d7c1aca693.png)

`2- tf.compat.v1.disable_eager_execution()`
![image](https://user-images.githubusercontent.com/84374136/132291580-30fbd06e-c704-4f39-824e-f02621aac804.png)

What's the problem? Does anyone know the reason for this difference in numbers?

**Comment by mohantym** [comment]
Hi @Nima-pw !We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by Nima-pw** [comment]
Not solved yet!

**Comment by mohantym** [comment]
Hi @Nima-pw ,Could you please share a stand alone code to reproduce this issue then?
