### ISSUE TITLE
For the model trained on tensorflow 1. X, how to quickly infer on tensorflow 2. X

### ISSUE THREAD

**Issue by van68** [tensorflow/tensorflow#51878]
For the model trained on tensorflow 1. X, how to quickly infer on tensorflow 2. X？

Based on the model trained on tensorflow 1. X, how to infer on tensorflow 2. X, and Quantization Compression Based on tflite 2. X，Is there any relevant example reference, thanks!

**Comment by sushreebarsa** [comment]
@van68 Could you please refer to the [link1](https://www.tensorflow.org/lite/performance/post_training_quantization), [link2](https://www.tensorflow.org/model_optimization/guide/quantization/training) ,[ link 3](https://www.tensorflow.org/hub/model_compatibility) and let us know if it helps ? Thanks!

**Comment by van68** [comment]
> @van68 Could you please refer to the [link1](https://www.tensorflow.org/lite/performance/post_training_quantization), [link2](https://www.tensorflow.org/model_optimization/guide/quantization/training) ,[ link 3](https://www.tensorflow.org/hub/model_compatibility) and let us know if it helps ? Thanks!

thank you reply, but it is no using.
Our problem is based on tensorflow 1. X training model, if reasoning under tensorflow 2. X

**Comment by sushreebarsa** [comment]
@van68  In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
