### ISSUE TITLE
[TF SavedModel Export] - 2GB Tensor size constraint 

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#51870]
Hi,

CC: @nluehr @WhiteFangBuck

We discussed this already a few times with @bixia1 @sanjoy and @pkanwar23.

With the recent progress in dynamic shapes support for TF-TRT, we are trying to process larger models (e.g. BERT Large, DLRM, TransformerXL) and some of them have issues to be saved in SavedModel format due to the 2GBs tensor size limit.

We have compiled a Google Colab to expose this issue: https://colab.research.google.com/drive/1NUrzK_m8HMBTx44WNQOIZ8baJHO60gDm#scrollTo=dqgB2jkpGDIj

```bash
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-3-de5a306b1fff> in <module>()
     50 print('\n3. Converting')
     51 converter = trt.TrtGraphConverterV2(input_saved_model_dir=args.saved_model_path)
---> 52 converter.convert()
     53 
     54 # def input_fn():

4 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape, allow_broadcast)
    526     if nparray.size * nparray.itemsize >= (1 << 31):
    527       raise ValueError(
--> 528           "Cannot create a tensor proto whose content is larger than 2GB.")
    529     tensor_proto.tensor_content = nparray.tobytes()
    530     return tensor_proto

ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

@fang @sanjoy could you please orient us on what should be a way forward to address this situation in the short term and potentially come up with a path forward more robust on the long term. I don't believe only TF-TRT runs into this issue

**Comment by sanjoy** [comment]
IMO the ideal solution is:
1. TensorRT lifts the restriction of needing layer weights to be compile time constants.
2. We no longer freeze graphs, which means the SavedModel proto can be small (the variable values are in checkpoint files).

Questions:
 - Do you see (1) happening soon?
 - Can (2) happen independently of (1)?

**Comment by bixia1** [comment]
The Google Colab provided by Jonathan shows two issues:
(1) a freeze graph exceeds the savedModel 2GB limit.
(2) a single constant exceeds the 2GB limit for "tensor proto".

Here are the concerns for the proposed solution to have TF-TRT work on checkpoints instead of savedModel:
(1) It doesn't address the second problem above.
(2) Common ML practice is to use savedModel for inference. Now we can trying to convince people to use checkpoints for inference, if you want to enable TF-TRT. If SavedModel a more stable interface comparing with checkpoints?

**Comment by DEKHTIARJonathan** [comment]
@sanjoy as promised here a few additional data points:

## 1. It's totally doable to save in a SavedModel format >= 2GBs

```python
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import array_ops

class MyModule(tf.Module):
  def __init__(self):
    self.v = None

  @tf.function
  def __call__(self, x):
    if self.v is None:
      # 4 GiB variable
      self.v =  tf.Variable(tf.random.uniform((1024,1024,1024), dtype=tf.dtypes.float32))
    x = tf.math.reduce_sum(x * self.v)
    return array_ops.identity(x, name="output_0")

input = np.random.uniform(size=(1024,)).astype(np.float32)
func = MyModule()
out = func(input)

cfunc = func.__call__.get_concrete_function(tf.TensorSpec(input.shape, tf.float32))
tf.saved_model.save(func, 'my_saved_model', signatures=cfunc)
```
Which produces the following:
```bash
$ tree my_saved_model/
my_saved_model/
├── assets
├── saved_model.pb
└── variables
    ├── variables.data-00000-of-00001
    └── variables.index

2 directories, 3 files

$ ls -lh my_saved_model/variables
total 4.1G
-rw-r--r-- 1 root root 4.1G Sep  8 23:58 variables.data-00000-of-00001     # <===== Larger than 2GBs
-rw-r--r-- 1 root root  211 Sep  8 23:58 variables.index
```

If we look into the SavedModel documentation: https://www.tensorflow.org/api_docs/python/tf/saved_model/save

> **Variables and Checkpoints**
Variables must be tracked by assigning them to an attribute of a tracked object or to an attribute of obj directly. TensorFlow objects (e.g. layers from tf.keras.layers, optimizers from tf.train) track their variables automatically. This is the same tracking scheme that tf.train.Checkpoint uses, and an exported Checkpoint object may be restored as a training checkpoint by pointing tf.train.Checkpoint.restore to the SavedModel's "variables/" subdirectory.

So in consequence, it appears that we don't seem to run in a limitation of the SavedModel itself, rather of the `Const` OP and how it is serialized: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/constant_op.cc#L94-L137

A few possibilities exists so far:
- Increase the protobuf maxsize => unfortunately this seems very difficult to do
- Implement inside the SavedModel API a "translation mechanism":
  - during save: `Const` => `ConstSerializable` (a new OP created that is serialized differently and doesn't have this size limit)
  - during loading:  `ConstSerializable` => `Const` to not break any of existing TF code.

The second approach would be fairly easy to implement, totally backward compatible and can be implement as a graph transformation.

## 2. Why "lazy graph freezing" will not work for TF-TRT 100% of the time :

Indeed it's a fair assumption that we could "lazily" freeze the graph just before building the engine, which absolutely would solve the problem (only for TF-TRT) in the graph is saved "unfrozen". In addition this change can be made easily backward compatible.

However, this absolutely breaks TF-TRT in the following scenarios:
- TRT Engine built ahead of time => There is no way to build the engine without freezing the graph, so if we build before saving => this can't work
- Ahead of time TRT Engine INT8 calibration, similarly you can't calibrate without building the TRT Engine(s), so same issue here, and we both know customer(s) to whom INT8 calibration is fairly essential.

## 3. Solutions already discussed that would be less then ideal
- Changing TRT to not enforce graph freezing, even in the very hypothetical world where they would agree to do this and it is feasible. This is a very long time ahead (between time to implement, next release and time for Google to pick it up).

- Using TF Checkpoints and dropping SavedModel:
  - major API change and would totally break backward compatibility on every TF-TRT code ever written.
  - Would break backward/forward compatibility as TF Checkpoints tends be significantly less stable over time (way more TF  version dependant)

**Comment by mohantym** [comment]
Hi @DEKHTIARJonathan !Could you please look into  [answer](https://github.com/tensorflow/tensorflow/issues/4291#issuecomment-245995340) of this [issue.](https://github.com/tensorflow/tensorflow/issues/4291) Replicating in [TF 2.5](https://colab.research.google.com/gist/mohantym/b1358880ec360b5872c314fbef7218d2/-tf-savedmodel-export-2gb-tensor-size-constraint-in-tf-trt-conversion.ipynb#scrollTo=LRODRnetacZG), [2.6](https://colab.research.google.com/gist/mohantym/b311392185889e21c74c989b1694d4a3/-tf-savedmodel-export-2gb-tensor-size-constraint-in-tf-trt-conversion.ipynb#scrollTo=30ets2JqFwrC) and [nightly(2.7.0dev)](https://colab.research.google.com/gist/mohantym/d42d25f5f5e63572cf6ae9f9c8c19a84/-tf-savedmodel-export-2gb-tensor-size-constraint-in-tf-trt-conversion.ipynb#scrollTo=t0YQOjhPa-HV)

**Comment by DEKHTIARJonathan** [comment]
@mohantym this solution will not work because TF-TRT (behind the hood) relies on graph freezing API and there's no way to use variable partitioner / tf.split() OPs AFAIK

**Comment by donglinz** [comment]
Hi guys I am facing the same issue when using TF-TRT converting model >=2GB. Do we have any plan to support this in the future? As in 2022, it is very common to have a model with more than 2GB parameters.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
