### ISSUE TITLE
Bug: Loading the  older versions of tfs and keras

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51879]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: No
![4 1](https://user-images.githubusercontent.com/26819449/132501060-50a9033b-f984-4828-9715-a77b50fa1c8a.JPG)
![4 2](https://user-images.githubusercontent.com/26819449/132501064-9121e22f-bf76-4648-92fb-2b68456a500f.JPG)

I wanted to run a Bioinformatics library, a deep learning model which supports particular versions.
The before model which I wanted to run showed error in TensorFlow also but this model also requirement can't be met.
I was using google-collab.
I think the issue is with integrating with google-collab or maybe with TensorFlow only.
Thanks!

**Comment by mohantym** [comment]
Hi @starboyvarun! We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks

**Comment by starboyvarun** [comment]
@mohantym Other template question was not important that's why I only filled important ones.
 and I have mentioned a screenshot that clearly says version. This is just the beginning of the code.
Thanks!

**Comment by mohantym** [comment]
Hi @starboyvarun , The above commands ran fine in Colab .Please  Find [Gist ](https://colab.research.google.com/gist/mohantym/973ccfa19402bedeb4aca8659b914a7c/github_51789.ipynb)for reference  . Please provide Full Error stack trace to proceed further. 
Also,It seems a duplicate issue to [this issue](https://github.com/tensorflow/tensorflow/issues/51783) who response has have been updated  recently with example code as a [GIST.](https://colab.research.google.com/gist/mohantym/5cb3c61f95b40a50f82b470574d9375a/github_51789.ipynb)
Thanks!

**Comment by starboyvarun** [comment]
@mohantym its fine but see the version is 2.3 of tf ,check I wanted the version to be 2.2 of Tensorflow

**Comment by mohantym** [comment]
Yes , Its a bug. I have update the [Gist ](https://colab.research.google.com/gist/mohantym/973ccfa19402bedeb4aca8659b914a7c/github_51789.ipynb#scrollTo=itREjrDQFN79).

**Comment by starboyvarun** [comment]
@mohantym 
Now, will anyone fix it?? 
Fix with older versions as people of bioinformatics use older versions.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look at this issue?

**Comment by starboyvarun** [comment]
@mohantym  @sanatmpa1  yes I have posted the issue where you have mentioned.
Please let me know when it gets fixed.
Thank you.

**Comment by mohantym** [comment]
Ok ! @starboyvarun ,Please mention that issue here and feel free to close this one.

**Comment by starboyvarun** [comment]
@mohantym I have already mentioned it, please fix this ASAP. 
Sure I will close the issue now. But do let me know in the comments when it gets fixed.
Thank you.

**Comment by mohantym** [comment]
Ok @starboyvarun ,but Can you please mention this issue in the respective issue in Keras repository so we can track and update you in time.

**Comment by starboyvarun** [comment]
@mohantym  I have already mentioned it in Keras repository already.

**Comment by starboyvarun** [comment]
ok, thank you. I am closing this issue now.
Hope it gets fixed soon.
Thanks!.

**Comment by mihaimaruseac** [comment]
This seems to be WAI.

**Comment by starboyvarun** [comment]
@mihaimaruseac  WAI ??

**Comment by mihaimaruseac** [comment]
working as intended
