### ISSUE TITLE
tensorflow/python/kernel_tests/metrics_test.py fail in assertAlmostEqual comparison; E TypeError: type numpy.ndarray doesn't define _round_ method

### ISSUE THREAD

**Issue by puneeshkhanna** [tensorflow/tensorflow#51877]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.6.0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
E TypeError: type numpy.ndarray doesn't define _round_ method

Above failure can potentially come from assert all close comparision when expected scalar value is compared against the actual numpy output from the device via self.eval.

Issue may not be seen on some devices if actual output is identical to expected value and so round call in assert all close implementation will not be called.

**Describe the expected behavior**
 One quick place where we can quickly reproduce the issue is in tensorflow/python/kernel_tests/metrics_test.py::PrecisionRecallThresholdsTest::testWithMultipleUpdates

Overwrite expected prec as an example  - 0.9393305437365417
Overwirte prec Actual output as a  numpy array with value [0.93933064]

self.assertAlmostEqual(expected_prec, self.evaluate(prec), 2)

Based upon the values, assert almost equal call should pass but "E TypeError: type numpy.ndarray doesn't define _round_ method" will be thrown.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): 
To fix it, we can first compare the shapes of actual output as [1] and then in assertAlmostEqual call, change as below:
self.assertAlmostEqual(expected_prec, self.evaluate(prec)[0], 2).

There are other test files too which have this issue whenever assertAllClose will be called and will fail if actual output is passed as numpy array and is not identical to expected ouput.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Reproducible by just running the test itself.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
NA

**Comment by tilakrayal** [comment]
@puneeshkhanna ,
Can you please refer this SO [link](https://stackoverflow.com/questions/41319292/error-typeerror-type-numpy-ndarray-doesnt-define-round-method) with similar error.It helps.Thanks!

**Comment by puneeshkhanna** [comment]
Usage of assertAllClose is done correctly in tensorflow/python/feature_column/sequence_feature_column_integration_test.py. Someone realized there the issue.
self.assertEqual(list(ctx_result['float_ctx'].shape), [1])
self.assertAlmostEqual(ctx_result['float_ctx'][0], 123.6, places=1)
This is how it needs to be changed wherever applicable and not pass numpy array to the call.

**Comment by tilakrayal** [comment]
@puneeshkhanna ,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet you are trying to execute.Thanks

**Comment by puneeshkhanna** [comment]
import numpy as np
class test(unittest.TestCase):
    def test_assert_1(self):
        actual = np.array([0.93933064])
        expected = 0.9393305437365417
        self.assertAlmostEqual(expected, actual, 2)

    def test_assert_2(self):
        actual = np.array([0.93933064])
        expected = 0.9393305437365417
        self.assertEqual(list(actual.shape), [1])
        self.assertAlmostEqual(expected, actual[0], 2)

f = test()
f.test_assert_2()
f.test_assert_1()

Please exeucte above code in jupyter or colab or any python environment. Test cases which use assertAlmostEqual need to redesigned as shown in test_assert_2(). Right now they are written as test_assert_1().

**Comment by tilakrayal** [comment]
@puneeshkhanna ,
I ran the code shared and face a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/5688c716f71604e9b9815c0028ff46fe/untitled74.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.

**Comment by puneeshkhanna** [comment]
```
import numpy as np
import unittest
class test(unittest.TestCase):
    def test_assert_1(self):
        actual = np.array([0.93933064])
        expected = 0.9393305437365417
        self.assertAlmostEqual(expected, actual, 2)

    def test_assert_2(self):
        actual = np.array([0.93933064])
        expected = 0.9393305437365417
        self.assertEqual(list(actual.shape), [1])
        self.assertAlmostEqual(expected, actual[0], 2)

f = test()
f.test_assert_2()
f.test_assert_1()
```

**Comment by puneeshkhanna** [comment]
Please try above in Colab. I ran it at my end. Sorry there was a typo in my earlier code.

**Comment by puneeshkhanna** [comment]
Hope the issue is clear now.

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
I was able to reproduce the issue in tf v2.5, v2.6 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a58301ba706b73c67166dd4686761e33/unti51877.ipynb).

**Comment by rainwoodman** [comment]
Thanks for the thorough investigation.

 `ndarray.__round__` is necessary to support unittest.TestCase.assertAlmostEqual() with single item ndarray input. See the example below.

The lack of `__round__` in ndarray is discussed in numpy/numpy#6248.
Although I note that even with `__round__` added, assertAlmostEqual for arrays with more than 1 item is still not clearly defined (due to the `== 0` comparison on ndarray in the same line).

```
import numpy as np
class A(np.ndarray):

  def __round__(self, places):
    return np.round_(self, places)

import unittest
class test(unittest.TestCase):
    def test_assert_1(self):
        actual = np.array([0.93933064]).view(type=A)
        expected = 0.9393305437365417
        self.assertAlmostEqual(expected, actual, 2)
    def test_assert_2(self):
        actual = np.array(0.93933064).view(type=A)
        expected = 0.9393305437365417
        self.assertAlmostEqual(expected, actual, 2)
    def test_assert_3(self):
        actual = np.array(0.93933064).view(type=np.ndarray)
        expected = 0.9393305437365417
        self.assertAlmostEqual(expected, actual, 2)

f = test()
f.test_assert_1() 
f.test_assert_2()
f.test_assert_3()
```
As there are no current test failures, a reasonable approach fixing calls to assertAlmostEqual on a case-by-case basis as failures are encountered.

Also, I think `TensorflowTestCase.assertAllclose` checks both the shape and the value, which appears to be the desired behavior you described? If so, maybe we should replace / override assertAlmostEqual with assertAllclose in TensorflowTestCase?

**Comment by sachinprasadhs** [comment]
@puneeshkhanna , Is this still an issue, could you please refer above comment and let us know your response. Thanks!
