### ISSUE TITLE
M1 Mac TensorFlow metal

### ISSUE THREAD

**Issue by par1hsharma** [tensorflow/tensorflow#51876]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): M1 MAC
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): mini forge
- TensorFlow version: 2.5
- Python version: 3.9
- Installed using virtualenv? pip? conda?: condo
- I HAVE INSTALLED THROUGH :  https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb

CODE 
import numpy as np
from keras.preprocessing import image
import matplotlib.pyplot as plt
from pathlib import Path
import tensorflow as tf
import sys
import tensorflow.keras
import pandas as pd
import sklearn as sk

print(tf.test.gpu_device_name())
print(tf.config.list_physical_devices('GPU'))
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

OUTPUT

/device:GPU:0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Tensor Flow Version: 2.5.0
Keras Version: 2.5.0

Python 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:55:16) 
[Clang 11.1.0 ]
Pandas 1.3.2
Scikit-Learn 0.24.2
GPU is available
2021-09-08 11:25:29.831941: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-09-08 11:25:29.832018: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

I am not sure what above 2 warning means . Is there any problem with installation.

**Comment by mohantym** [comment]
Hi @par1hsharma , Could you look into this [link ](https://developer.apple.com/forums/thread/684178)for answers ? It suggests upgrading to MacOS 12.0

**Comment by par1hsharma** [comment]
> Hi @par1hsharma , Could you look into this [link ](https://developer.apple.com/forums/thread/684178)for answers ? It suggests upgrading to MacOS 12.0




> Hi @par1hsharma , Could you look into this [link ](https://developer.apple.com/forums/thread/684178)for answers ? It suggests upgrading to MacOS 12.0

can you tell me if i followed correct tutorial to install TensorFlow for M1 Mac
I followed this link  https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb
the above link contains  "tensorflow-apple-metal.yml" . is this yml file a correct way to install or should I have followed 
this  https://developer.apple.com/metal/tensorflow-plugin/

**Comment by mohantym** [comment]
Both approach includes  required  packages and steps , But Could you test the second approach and update whether issue is replicating or not?

**Comment by AmondialCapital** [comment]
Here is how to build TF on M1:

https://github.com/tensorflow/tensorflow/issues/51506#issuecomment-901460541

**Comment by par1hsharma** [comment]
> Here is how to build TF on M1:
> 
> [#51506 (comment)](https://github.com/tensorflow/tensorflow/issues/51506#issuecomment-901460541)
is this not a correct way to install it on M1 . Can you please go through the link and share your response ?
 https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb

**Comment by mohantym** [comment]
Hi @par1hsharma ,Is the issue still replicating  with same error stack trace?

**Comment by par1hsharma** [comment]
> Hi @par1hsharma ,Is the issue still replicating with same error stack trace?

Yes it is still replicating. Can you suggest me come commands to check if my installation is successful especially for arm Mac (m1 Mac). how to check if I have everything M1 native installed (from python to TensorFlow)

**Comment by mohantym** [comment]
Ok @par1hsharma  
**Commands to check python version .**
```
python --version (in terminal)
```
**Commands to check Tensorflow version**
```
import tensorflow as tf
print(tf.__version__)
```
**Command to check successful Tensorflow installation .**
```
python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"  
#if a tensor is returned you have installed Tensorflow Sucessfully
```
