### ISSUE TITLE
Hexagon delegate

### ISSUE THREAD

**Issue by waqarahmad84** [tensorflow/tensorflow#51872]
I am trying to build a simple "Hexagon delegate" based android app by using https://www.tensorflow.org/lite/performance/hexagon_delegate link. 
I have pixel 2xl phone for test this. I have rooted my phone for access all facility but i was fail to make this app. 
I am facing 1 error which is  "java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dlopen" referenced by "/data/app/~~2R44BqWkRYHRwpMUOwTYfg==/com.example.myapplication-2UccuMnXIaXolmx6-6ftSQ==/lib/arm64/libtensorflowlite_hexagon_jni.so"..."
Now, requesting help from anybody. Thank you

**Comment by sushreebarsa** [comment]
@waqarahmad84  In order to expedite the trouble-shooting process here, Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), and explain more about your issue ?Thanks!

**Comment by sushreebarsa** [comment]
@waqarahmad84 Could you please refer to the similar [issue1](https://github.com/tensorflow/tensorflow/issues/39539), [issue2 ](https://github.com/tensorflow/tensorflow/issues/36804) and please let us know if it helps? Thank you!
