### ISSUE TITLE
IOS tflite model doesn't have ResetVariableTensors() attribute

### ISSUE THREAD

**Issue by karimkalimu** [tensorflow/tensorflow#51880]
- OS Platform and Distribution : Mac os(xcode)
- TensorFlow installed from (source or binary): pod install
- TensorFlow version : TensorFlowLiteSwift 2.6.0

I am using model that contain two LSTM layers, if I don't use a function that has same functionality like reset_all_variables()(python), ResetVariableTensors()(java, and c++), the output will be different from what I want.

I need the function using swift or objective-c, I just want a way to reset variables inside tflite model in IOS app

I hope there is a way to do that, thanks

Links to the function that I want :
python : https://github.com/tensorflow/tensorflow/blob/v2.6.0/tensorflow/lite/python/interpreter.py#L877-L878
java : https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/Interpreter#resetVariableTensors()
c++ : https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter#classtflite_1_1_interpreter_1a3f5386d1e3569a55cfe0990dda8c4d92

**Comment by karimkalimu** [comment]
I did manage a way to include the feature within the pod lib for xcode until they release a newer version with it, because they already have it in the c files but still experimental, and not included in the swift nightly version.

Used the same command from this page (https://www.tensorflow.org/lite/guide/build_ios)
bazel build --config=ios_fat -c opt \
  //tensorflow/lite/ios:TensorFlowLiteC_framework

I edited three files before running the command :

Add function to tensorflow/lite/c/c_api.h 

```
TFL_CAPI_EXPORT extern TfLiteStatus TfLiteInterpreterResetVariableTensors(
    TfLiteInterpreter* interpreter);
```


Add function to tensorflow/lite/c/c_api.cc 
```

TfLiteStatus TfLiteInterpreterResetVariableTensors(
    TfLiteInterpreter* interpreter) {
  return interpreter->impl->ResetVariableTensors();
}
```


Inside xcode project add function to Pods/TensorFlowLiteSwift/tensorflow/lite/swift/Sources/Interpreter.swift 

```
    public func ResetVariableTensors() throws {
      guard TfLiteInterpreterResetVariableTensors(cInterpreter) == kTfLiteOk else {
        throw InterpreterError.allocateTensorsRequired
      }
    }
```

I am not sure if I did something wrong, but I just wanted this feature to work, and it did work

Thanks anyway

**Comment by MeghnaNatraj** [comment]
@karimkalimu is the issue resolved? Feel free to request a PR with these changes. 

Follow up: The`TensorFlowLiteC_framework` build target includes the `tensorflow/lite/c/c_api_experimental.h/cc` files which define the `TfLiteInterpreterResetVariableTensors(..)` function. Why did you add it to the `tensorflow/lite/c/c_api.h/cc` files as well?

**Comment by karimkalimu** [comment]
yes the issue resolved, using the way I mentioned

I tried to include c_api_experimental.h inside this  file "tensorflow_src/tensorflow/lite/ios/BUILD", but it didn't work, and I didn't know where to put c_api_experimental.cc file to be included, I thought it will be compiled if .h file included. 

I am not familiar with bazel process, and which file to edit to make the change I want

FROM :
`# bazel build -c opt --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteC_framework
tflite_ios_framework(
    name = "TensorFlowLiteC_framework",
    hdrs = [
        ":c_api.h",
        ":common.h",
        ":xnnpack_delegate.h",
        "//tensorflow/lite/c:c_api_types.h",
    ],
    allowlist_symbols_file = ":allowlist_TensorFlowLiteC.txt",
    bundle_name = "TensorFlowLiteC",
    minimum_os_version = TFL_MINIMUM_OS_VERSION,
    deps = [
        ":tensorflow_lite_c",
    ],
)
`


TO :

`# bazel build -c opt --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteC_framework
tflite_ios_framework(
   ​name = "TensorFlowLiteC_framework",
   ​hdrs = [
      ":builtin_ops.h",
      ":c_api_experimental.h", 
      ​":c_api.h",
       ​":common.h",
       ​":xnnpack_delegate.h",
       ​"//tensorflow/lite/c:c_api_types.h",
   ​],
   ​allowlist_symbols_file = ":allowlist_TensorFlowLiteC.txt",
   ​bundle_name = "TensorFlowLiteC",
   ​minimum_os_version = TFL_MINIMUM_OS_VERSION,
   ​deps = [
       ​":tensorflow_lite_c",
   ​],
)
`

Anyway the issue has been resolved, thank you for your time

**Comment by MeghnaNatraj** [comment]
@karimkalimu Thank you for the information! Glad the issue is fixed on your end.
