### ISSUE TITLE
freeze_graph.py "AttributeError: 'module' object has no attribute 'checkpoint_exists' in latest commit

### ISSUE THREAD

**Issue by neuralearner** [tensorflow/tensorflow#5188]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
none, latest commit from 4 days ago caused this issue to arise.

### Environment info
Operating System: OSX Sierra

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
no Cuda support

If installed from binary pip package, provide:

1. A link to the pip package you installed: compiled from source
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0rc1

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
bac7faa9a3eb5b60687a83336202cd3493de5385

2. The output of `bazel version`
Build label: 0.3.2-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Oct 8 08:02:20 2016 (1475913740)
Build timestamp: 1475913740
Build timestamp as int: 1475913740

### What other attempted solutions have you tried?
Used a version prior to the latest commit 4 days ago and it worked.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

$ python freeze_graph.py --input_graph=train.txt --input_checkpoint=model.ckpt-194000 --output_graph=frozen_graph.pb --output_node_names=final_result

  File "freeze_graph.py", line 135, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "freeze_graph.py", line 132, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "freeze_graph.py", line 84, in freeze_graph
    if not tf.train.checkpoint_exists(input_checkpoint):
AttributeError: 'module' object has no attribute 'checkpoint_exists'

**Comment by mostafachatillon** [comment]
I have the same error. How did you solve this problem?

**Comment by gsoul** [comment]
I have the same issue. As a temporary measure, I commented this check out.

**Comment by lintzuhsiang** [comment]
simply change the tf.train.checkpoint_exists(....) into tf.gfile.Exists(.....) and it can work

**Comment by stprior** [comment]
In my case a similar error was due to trying to run scripts from the latest source while an earlier compiled tensorflow package was installed. The correct fix would be to compile and install from source, but as @lintzuhsiang suggests tf.gfile.Exists(.....) is a workaround
