### ISSUE TITLE
GET returned 404 Not Found

### ISSUE THREAD

**Issue by hrw** [tensorflow/tensorflow#51886]
**System information**
- OS Platform and Distribution: manylinux2014
- TensorFlow version: git HEAD
- Python version: 3.6 - 3.9
- Installed using virtualenv
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10

**Describe the problem**

File missing on mirror?

```
20:49:09     Analyzing: target //tensorflow/tools/pip_package:build_pip_package (243 packages loaded, 3941 targets configured)
20:49:09     Analyzing: target //tensorflow/tools/pip_package:build_pip_package (409 packages loaded, 16799 targets configured)
20:49:09     WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/dfe763f462d3569323de6caa085d8b06ce38eb7b.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
20:49:09     INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (433 packages loaded, 25206 targets configured).
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
20:49:09     bazel clean --expunge
20:49:09     export BAZEL_LINKLIBS=-l%:libstdc++.a
20:49:09     bazel build --config=nonccl //tensorflow/tools/pip_package:build_pip_package --verbose_failures
20:49:09     mkdir tensorflow-pkg
20:49:09     bazel-bin/tensorflow/tools/pip_package/build_pip_package --cpu --project_name tensorflow_aarch64 ./tensorflow-pkg
```

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you look into this issue?

**Comment by Saduf2019** [comment]
@hrw 
Can you please confirm if this issue occurs with the stable version of tensorflow as the nightly could have daily updates, can you let us know if it works fine on stable tested version 3.4/2.5 or 2.6

**Comment by hrw** [comment]
This was on Linaro CI. Our 'manylinux tensorflow nightly' job builds Tensorflow in a loop for Python 3.[6789] versions.

Log: https://ci.linaro.org/job/ldcg-python-manylinux-tensorflow-nightly/89/console

It looks like it built git HEAD for Python 3.6 and then started for 3.7 and failed.

Build of TF:
```
set -xe
source /tmp/workspace/venv-cp37-cp37m/bin/activate
expect configure_tensorflow
bazel clean --expunge
export BAZEL_LINKLIBS=-l%:libstdc++.a
bazel build --config=nonccl //tensorflow/tools/pip_package:build_pip_package --verbose_failures
mkdir tensorflow-pkg
bazel-bin/tensorflow/tools/pip_package/build_pip_package --cpu --project_name tensorflow_aarch64 ./tensorflow-pkg
```

Our Ansible playbooks/roles used for building: https://git.linaro.org/ci/job/configs.git/tree/ldcg-python-manylinux-tensorflow/ansible (parent dir has build.sh and build-manylinux2014-wheels.sh scripts which install and run Ansible).

**Comment by hrw** [comment]
I am aware that build scripts I use may need some improvements. All comments are welcome.

**Comment by hrw** [comment]
It built: https://snapshots.linaro.org/ldcg/python/tensorflow-manylinux-nightly/20210909-90/tensorflow-aarch64/

Closing. Sorry for mess.

**Comment by hrw** [comment]
And another one:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f5b8f1247cd9d1b18b7b95f6f197d4d654597529.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/cf83c1cba92cb2ae97c08399531685fd9ccfe983.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

Can't you first mirror and THEN commit? I have daily build so it fetches HEAD and do build. At some moment during 24h.
