### ISSUE TITLE
tensorflow/compiler/mlir/tensorflow:gen_gen_mlir_passthrough_op_py_py_wrappers_cc' failed 

### ISSUE THREAD

**Issue by doubibobo** [tensorflow/tensorflow#51881]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux, Kylin 4.4.131 (a system like Ubuntu16.04, which is based on the aarch64 architecture)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.6
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: no cuda, just with cpu
- GPU model and memory: 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. bazel clean
2. ./configure
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /home/b517-120/miniforge3/envs/tensorflow-build/bin/python3]: 

Found possible Python library paths:
  /home/b517-120/miniforge3/envs/tensorflow-build/lib/python3.9/site-packages
Please input the desired Python library path to use.  Default is [/home/b517-120/miniforge3/envs/tensorflow-build/lib/python3.9/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

3.  bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (427 packages loaded, 25634 targets configured).
INFO: Found 1 target...
ERROR: /home/b517-120/tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:2037:21: Linking of rule '//tensorflow/compiler/mlir/tensorflow:gen_gen_mlir_passthrough_op_py_py_wrappers_cc' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/compiler/mlir/tensorflow/gen_gen_mlir_passthrough_op_py_py_wrappers_cc-2.params
bazel-out/aarch64-opt/bin/_solib_aarch64/_U_S_Stensorflow_Scompiler_Smlir_Stensorflow_Cgen_Ugen_Umlir_Upassthrough_Uop_Upy_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `std::allocator<absl::lts_20210324::string_view>::allocator()'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4758.311s, Critical Path: 2844.81s
INFO: 12916 processes: 3232 internal, 9684 local.
FAILED: Build did NOT complete successfully

The above is all the errors I met.

**Comment by sushreebarsa** [comment]
@doubibobo Could you please have a look at the [link1](https://www.tensorflow.org/mlir),[link2](https://www.tensorflow.org/install/source), similar[ issue ](https://github.com/tensorflow/tensorflow/issues/46630) and try to install using latest stable TF version 2.6 from source ?Please let us know if it helps? Thanks!

**Comment by doubibobo** [comment]
Thanks for your timely response. Following [https://github.com/tensorflow/tensorflow/issues/46630#issuecomment-885816590](url), I set TF_ENABLE_MLIR=0 and TF_ENABLE_XLA=0, but I still get the same error while compiling a new file.
It seems like that the absl package is not installed correctly......


ERROR: /home/b517-120/tensorflow/tensorflow/cc/BUILD:621:22: Linking of rule '//tensorflow/cc:ops/experimental_dataset_ops_gen_cc' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/cc/ops/experimental_dataset_ops_gen_cc-2.params
bazel-out/aarch64-opt/bin/_solib_aarch64/_U_S_Stensorflow_Scc_Cops_Sexperimental_Udataset_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `std::allocator<absl::lts_20210324::string_view>::allocator()'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/b517-120/tensorflow/tensorflow/lite/toco/python/BUILD:89:10 Linking of rule '//tensorflow/cc:ops/experimental_dataset_ops_gen_cc' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/cc/ops/experimental_dataset_ops_gen_cc-2.params
INFO: Elapsed time: 3776.873s, Critical Path: 2912.50s
INFO: 11654 processes: 3053 internal, 8601 local.
FAILED: Build did NOT complete successfully

**Comment by Saduf2019** [comment]
@doubibobo 
Can you try running a bazel clean --expunge before building again, try changed to gcc7.5.0 and let us know.

**Comment by doubibobo** [comment]
Thank you so much!
Follow your tips, I changed to gcc7.5.0 and tried running a `bazel clean --expunge` before built
And then it succeeds! It really works!
Thank you again for solving such a confusing problem for me!

**Comment by Saduf2019** [comment]
@doubibobo 
Thank you for your update, glad the issue is resolved.
