### ISSUE TITLE
official guide on developer.apple.com/metal/tensorflow-plugin fails to build grpcio

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tensorflow#51897]
Apple Silicon steps it fails to install base tensorflow:

````
python -m pip install tensorflow-macos
````

with the following error message:

````

Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sascha/miniforge3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bj/kl9gdt8145n_pgcjlm9j4_x00000gn/T/pip-install-b32jlj8u/grpcio_6d3ece3d284848398f436707643d6149/setup.py'"'"'; __file__='"'"'/private/var/folders/bj/kl9gdt8145n_pgcjlm9j4_x00000gn/T/pip-install-b32jlj8u/grpcio_6d3ece3d284848398f436707643d6149/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bj/kl9gdt8145n_pgcjlm9j4_x00000gn/T/pip-wheel-efohlhk7
       cwd: /private/var/folders/bj/kl9gdt8145n_pgcjlm9j4_x00000gn/T/pip-install-b32jlj8u/grpcio_6d3ece3d284848398f436707643d6149/
````

What is the proposed solution?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): https://developer.apple.com/metal/tensorflow-plugin/
- TensorFlow version: unknown as they is no 
- Python version: https://pypi.org/project/tensorflow-macos/ 2.5
- Installed using virtualenv? pip? conda?: miniforge3 https://developer.apple.com/metal/tensorflow-plugin/
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source): ?
- CUDA/cuDNN version: `
- GPU model and memory:?

**Comment by ymodak** [comment]
[Apple developer forum](https://developer.apple.com/forums/tags/tensorflow-metal) is the right place to raise this issue since those builds are maintained by them.

**Comment by SaschaHeyer** [comment]
solution
https://developer.apple.com/forums/thread/683757

SYSTEM_VERSION_COMPAT=0 pip install tensorflow-macos tensorflow-metal

**Comment by ymodak** [comment]
Thanks for sharing your solution. I will close this thread now.

**Comment by AraibKarim** [comment]
I am also facing the above issue. What is the solution for it?
