### ISSUE TITLE
how to barrier when run distribution trainning by estimator api

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#51892]
When run distribution trainning by tf.estimator api ，other workers will be hanging when one worker finished training.So i add sleep function below estimator funtion.But it seemed tricky this way.
```
tf.estimator.train_and_evaluate(self._tf_estimator, train_spec, eval_spec)
 time.sleep(300)

```
Any other good ways to fix this estimator issue?
TF version is 1.14

**Comment by sushreebarsa** [comment]
@liumilan We see that you are using TF **`v1.14`** which is not actively supported, please try to upgrade the TF version to **`2.6.0`** which is the latest stable TF version. Please let us know if the issue still persists in newer versions? Thank you!

**Comment by liumilan** [comment]
> @liumilan We see that you are using TF **`v1.14`** which is not actively supported, please try to upgrade the TF version to **`2.6.0`** which is the latest stable TF version. Please let us know if the issue still persists in newer versions? Thank you!

Can tf 2.6.0 support tf 1.14 api?

**Comment by sushreebarsa** [comment]
@liumilan As per [TF official documentation](https://www.tensorflow.org/) ,There is a caution for using estimator api. To know more could you please have a look at the [link](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator) for reference.Thank you!
