### ISSUE TITLE
Can I use the GPU when installing via pip? If so where is the 'configure' script? If not where should I clone the repo?

### ISSUE THREAD

**Issue by boyentenbi** [tensorflow/tensorflow#519]
Hi all, 

I am installing tensorflow and am really stuck with the GPU setup ( pip install worked fine for CPU ).

I was forced to install via source because I could not find the 'configure' script anywhere at all when installing by pip. In fact the source directory was not created at all, only the 'tensorflow' folder in the level below.

To install by source I followed the tutorial here: https://www.tensorflow.org/versions/master/get_started/os_setup.html#installation-for-linux and successfully ran bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

However, importing tensorflow into a python file gives the familiar 'No module' import error. I cloned the repo while in my home directory, but I am not sure if this is correct.

Is the pip installation supposed to allow GPU use? If so where can I locate the 'configure' script? If not where should I clone the repo, and is this the cause of the import error? 

Any help is greatly appreciated because I am very much lost!

**Comment by martinwicke** [comment]
You don't need to run configure when you use the provided pip binaries. There are two different wheels that we provide for Linux, one with GPU support, and one without. If you want to use GPU, install this wheel: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
