### ISSUE TITLE
Cannot find tensorflow 2.2.0rc4 as available option with pip install

### ISSUE THREAD

**Issue by bulgarianboy** [tensorflow/tensorflow#51906]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.9.5 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.2.0rc4
- Python version: 3.6.4
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

**Describe the problem**

I am installing a programme which requires a conda env with tensorflow 2.2.0rc4. When I do this it says no matching distribution can be found.

ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0rc4 (from versions: 1.15.4, 1.15.5, 2.0.1, 2.0.3, 2.1.2, 2.2.1, 2.3.1)
ERROR: No matching distribution found for tensorflow==2.2.0rc4

**Provide the exact sequence of commands / steps that you executed before running into the problem**

pip install tensorflow==2.2.0rc4

How can I install this version?

**Comment by bulgarianboy** [comment]
Should mention pip is 21.2.4 (latest)

**Comment by mohantym** [comment]
Hi @bulgarianboy , In that  case ,select from suggested versions i.e  2.2.1 ,But Minimum MacOS requirement is 10.12.6 or later . Detail instructions are here in this[ link](https://www.tensorflow.org/install/pip#macos) .
