### ISSUE TITLE
tf.self_adjoint_eig does not work for complex matrices

### ISSUE THREAD

**Issue by szali** [tensorflow/tensorflow#5190]
The documentation of tf.self_adjoint_eig (and the likes) does not state that which data types are accepted by this function. Turns out, only float32 and float64. But the name is misleading: self-adjointness is a property of complex matrices, and one could expect that this function would work on complex64 and complex128 as well.

For me it would be very useful if tf.self_adjoint_eig could work for complex matrices.

Please amend the documentation with the list of accepted dtypes (this goes for SVD and other similar functions as well). And of course it would be great if tf.self_adjoint_eig could accept complex data. :)

**Comment by drpngx** [comment]
Good to know, would you be able to send a PR?

**Comment by szali** [comment]
I would happily send a pull request if I knew how to make it work for complex matrices.

**Comment by drpngx** [comment]
@rmlarsen checking if that makes sense.

**Comment by rmlarsen** [comment]
Yes, the documentation is lacking (and yes, it was lame to name an op self_adjoint and then not support complex - I filed an appropriately snarky meme for that a while ago). Feel free to send a PR to add support for complex. You would simply need to add the kernel registrations for complex types here: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/self_adjoint_eig_v2_op.cc#L85

and update the unit tests here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py

You can look at svd_op* as an example.

**Comment by yongtang** [comment]
Created a PR #8662 to support complex64 and complex128. Please take a look.
