### ISSUE TITLE
Convert Tensorflow functions to Tensorflow Lite functions

### ISSUE THREAD

**Issue by CodeMonkey3435** [tensorflow/tensorflow#51904]
### 1. System information

- Linux
- TensorFlow version: 2.5.0, also TFLite 2..5.0

### 2. Code
`    masks = tf.image.crop_and_resize(tf.cast(roi_masks, tf.float32), boxes, box_ids, config.MASK_SHAPE)`

Hi there,
I am currently trying to convert the Mask R CNN model from Matterport/Leekunhee (https://github.com/leekunhee/Mask_RCNN) to Tensorflow Lite. I fixed the problem temporarily by allowing Select Ops for the tensorflow lite interpreter. Now I need to speed up the entire process of inference. If I remember correctly last time I got this error message:

> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 275 (FlexCropAndResize) failed to prepare.

Can anybody help me translate this one line of code to something the tflite Interpreter and converter will accept? Any workaround is appreciated.

Thank you all for reading.

**Comment by CodeMonkey3435** [comment]
Okay, so I wanted to try on Tf 2.6 and tf nightly and this is what I found: 

```
keraModel = model.keras_model


converter = tf.lite.TFLiteConverter.from_keras_model(keraModel)
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS#, # enable TensorFlow Lite ops.
]

converter.optimizations = [ tf.lite.Optimize.DEFAULT ]

tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
```
And this is the error message:

> ConverterError: /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListReserve' op requires element_shape to be 1D tensor during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
/home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False

**Comment by CodeMonkey3435** [comment]
And after I disabled "converter._experimental_lower_tensor_list_ops = False", the code looks like this:

```
keraModel = model.keras_model


converter = tf.lite.TFLiteConverter.from_keras_model(keraModel)
#converter.allow_custom_ops = True
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS#, # enable TensorFlow Lite ops.
    #tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

converter.optimizations = [ tf.lite.Optimize.DEFAULT ]
converter._experimental_lower_tensor_list_ops = False

tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
```

My new error message is this:

> ConverterError                            Traceback (most recent call last)
> <ipython-input-14-d2e1b8b44f0d> in <module>
>      15 converter._experimental_lower_tensor_list_ops = False
>      16 
> ---> 17 tflite_model = converter.convert()
>      18 
>      19 interpreter = tf.lite.Interpreter(model_content=tflite_model)
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in wrapper(self, *args, **kwargs)
>     770   def wrapper(self, *args, **kwargs):
>     771     # pylint: disable=protected-access
> --> 772     return self._convert_and_export_metrics(convert_func, *args, **kwargs)
>     773     # pylint: enable=protected-access
>     774 
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in _convert_and_export_metrics(self, convert_func, *args, **kwargs)
>     756     self._save_conversion_params_metric()
>     757     start_time = time.process_time()
> --> 758     result = convert_func(self, *args, **kwargs)
>     759     elapsed_time_ms = (time.process_time() - start_time) * 1000
>     760     if result:
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in convert(self)
>    1165         Invalid quantization parameters.
>    1166     """
> -> 1167     saved_model_convert_result = self._convert_as_saved_model()
>    1168     if saved_model_convert_result:
>    1169       return saved_model_convert_result
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in _convert_as_saved_model(self)
>    1148       if self.saved_model_dir:
>    1149         return super(TFLiteKerasModelConverterV2,
> -> 1150                      self).convert(graph_def, input_tensors, output_tensors)
>    1151     finally:
>    1152       shutil.rmtree(temp_dir, True)
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/lite.py in convert(self, graph_def, input_tensors, output_tensors)
>     944         input_tensors=input_tensors,
>     945         output_tensors=output_tensors,
> --> 946         **converter_kwargs)
>     947 
>     948     return self._optimize_tflite_model(
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/convert_phase.py in wrapper(*args, **kwargs)
>     221         else:
>     222           report_error_message(str(converter_error))
> --> 223         raise converter_error from None  # Re-throws the exception.
>     224       except Exception as error:
>     225         report_error_message(str(error))
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/convert_phase.py in wrapper(*args, **kwargs)
>     214     def wrapper(*args, **kwargs):
>     215       try:
> --> 216         return func(*args, **kwargs)
>     217       except ConverterError as converter_error:
>     218         if converter_error.errors:
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
>     824       input_data.SerializeToString(),
>     825       debug_info_str=debug_info_str,
> --> 826       enable_mlir_converter=enable_mlir_converter)
>     827   return data
>     828 
> 
> ~/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
>     313       for error_data in _metrics_wrapper.retrieve_collected_errors():
>     314         converter_error.append_error(error_data)
> --> 315       raise converter_error
>     316 
>     317   return _run_toco_binary(model_flags_str, toco_flags_str, input_data_str,
> 
> ConverterError: /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListReserve' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListFromTensor' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListStack' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.DenseToDenseSetOperation' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: error: 'tf.CropAndResize' op is neither a custom op nor a flex op
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:1048:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListGetItem' op is neither a custom op nor a flex op
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: called from
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: error: 'tf.TensorListSetItem' op is neither a custom op nor a flex op
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: called from
> <unknown>:0: note: loc("StatefulPartitionedCall"): called from
> /home/codemonkey/anaconda3/envs/tflite_converter/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py:552:0: note: Error code: ERROR_NEEDS_FLEX_OPS
> <unknown>:0: error: failed while converting: 'main': 
> Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
> TF Select ops: CropAndResize, DenseToDenseSetOperation, TensorListFromTensor, TensorListGetItem, TensorListReserve, TensorListSetItem, TensorListStack
> Details:
> 	tf.CropAndResize(tensor<?x?x?x256xf32>, tensor<?x4xf32>, tensor<?xi32>, tensor<2xi32>) -> (tensor<?x14x14x256xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}
> 	tf.CropAndResize(tensor<?x?x?x256xf32>, tensor<?x?xf32>, tensor<?xi32>, tensor<2xi32>) -> (tensor<?x7x7x256xf32>) : {T = f32, device = "", extrapolation_value = 0.000000e+00 : f32, method = "bilinear"}
> 	tf.DenseToDenseSetOperation(tensor<1x?xi64>, tensor<1x?xi64>) -> (tensor<?x2xi64>, tensor<?xi64>, tensor<2xi64>) : {T = i64, device = "", set_operation = "intersection", validate_indices = true}
> 	tf.TensorListFromTensor(tensor<?xi32>, tensor<0xi32>) -> (tensor<!tf_type.variant<tensor<i32>>>) : {device = ""}
> 	tf.TensorListGetItem(tensor<!tf_type.variant<tensor<i32>>>, tensor<i32>, tensor<0xi32>) -> (tensor<i32>) : {device = ""}
> 	tf.TensorListReserve(tensor<i32>, tensor<i32>) -> (tensor<!tf_type.variant<tensor<*xi64>>>) : {device = ""}
> 	tf.TensorListSetItem(tensor<!tf_type.variant<tensor<*xi64>>>, tensor<i32>, tensor<?xi64>) -> (tensor<!tf_type.variant<tensor<*xi64>>>) : {device = ""}
> 	tf.TensorListStack(tensor<!tf_type.variant<tensor<*xi64>>>, tensor<1xi32>) -> (tensor<?x100xi64>) : {device = "", num_elements = -1 : i64}

**Comment by CodeMonkey3435** [comment]
Is it possible to upload the model and then just use the tf lite converter code to reproduce the error?

**Comment by ymodak** [comment]
> Is it possible to upload the model and then just use the tf lite converter code to reproduce the error?

Yes that will work to reproduce the error on our end.
