### ISSUE TITLE
tf.pad crashes with large paddings

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#51908]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.6.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tf.pad` crashes when the argument "paddings" has large values.

**Describe the expected behavior**
Expect an exception to be thrown if the input `paddings` is unexpected.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
input_tensor = tf.random.uniform([1, 32, 32, 3], dtype=tf.float32)
paddings = [[125106557, 1415887920], [747509374, 2136925906], [413308538, 904601717], [1900762018, 831358864]]
res = tf.pad(input_tensor,paddings)
```
outputs:
```
2021-09-09 12:46:38.123113: F tensorflow/core/framework/tensor_shape.cc:352] Check failed: 0 <= new_num_elements (0 vs. -1)
Aborted (core dumped)
```

**Comment by sushreebarsa** [comment]
@lugalUrim Could you please have a look at the[ link](https://www.tensorflow.org/api_docs/python/tf/pad), and similar [issue](https://github.com/tensorflow/tensorflow/issues/42293) ,Please let us know if it helps ?Thanks!

**Comment by lugalUrim** [comment]
Yes, thanks @sushreebarsa for pointing to that. I will close this issue.

**Comment by yongtang** [comment]
In case of check failure, tensorflow should return an error gracefully instead of crash with undefined behaviors. Created a PR #51973 for the fix.
