### ISSUE TITLE
Multi gpus can not run parallel when using run_eagerly=True in model.fit() in MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by qq747688898** [tensorflow/tensorflow#51900]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 11.3.0/8.2.1
- GPU model and memory: Tesla P100(16GB)

My code is very simple:
```

import tensorflow as tf
import tensorflow_datasets as tfds
import os
import json

gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

num_epochs = 50
batch_size_per_replica = 32
learning_rate = 0.001

num_workers = 1
os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["172.37.2.20:8888"]
    },
    'task': {'type': 'worker', 'index': 0}
})
strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
print('~~' * 10)
print('Number of devices: %d.' % strategy.num_replicas_in_sync)
print('~~' * 10)
batch_size = batch_size_per_replica * num_workers * strategy.num_replicas_in_sync


def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label


dataset = tfds.load("cats_vs_dogs", split=tfds.Split.TRAIN, as_supervised=True)
dataset = dataset.map(resize).shuffle(1024).batch(batch_size)

with strategy.scope():
    model = tf.keras.applications.MobileNetV2(weights=None, classes=2)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy],
        run_eagerly=True
    )

model.fit(dataset, epochs=num_epochs)
```

**Describe the current behavior**
If I remove the ` run_eagerly=True` in model.compile, the multi gpus will run parallel. But after add this kwarg to make the model is runing in eager mode, the multi gpus will run one by one.

**Describe the expected behavior**
The parameter should not determine the gpu running mode.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@qq747688898 Could you please have a look at the [link](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) for reference and please let us know if it helps ? Thanks!

**Comment by qq747688898** [comment]
> @qq747688898 Could you please have a look at the [link](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) for reference and please let us know if it helps ? Thanks!

Thanks for your reply. This page introduces how to start a distributed training by using Keras and tf.distribute.Strategy, but it can not explain why the gpus does not run parallel when using `model.compile(run_eagerly=True)`

**Comment by Saduf2019** [comment]
@qq747688898 
Can you please refer to [this issue](https://stackoverflow.com/questions/56062017/hot-to-fix-tensorflow-model-not-running-in-eager-mode-with-fit) and let us know if it helps.

**Comment by qq747688898** [comment]
@Saduf2019 
Hello, thanks for your reply.
I try to run my model with this issue's way as:
`model.compile()`
`model.run_eagerly = True`
But the gpus still doesn't run parallel.

**Comment by Saduf2019** [comment]
@qq747688898 
You dont have to necessitate eager execution  when using the distributed strategies, please follow the official doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile).

For any further queries i suggest you open an issue at the tf discussion forum as there is a larger community to support there.

**Comment by qq747688898** [comment]
@Saduf2019 
So can i think that if I want to make my gpus run parallel when using distributed strategies, the model must run without eager mode?

**Comment by Saduf2019** [comment]
@qq747688898 
run_eagerly=True in model.fit is suggested only to debug
once debugging is over, it is always recommended to removed that flag

As requested before for any further queries i suggest you open an issue at the tf discussion forum as there is a larger community to support there, this is not a bug or a performance issue.
