### ISSUE TITLE
crash in (loading?) libtensorflow_framework.so.2

### ISSUE THREAD

**Issue by bkgoodman** [tensorflow/tensorflow#51909]
**System information**
- No custom code - just loading
- Ubuntu 20.0.4
- Intel(R) Atom(TM) CPU D2500   @ 1.86GHz
- Installed from Ubuntu release binary apt-get
- Cannot determine (see below)
- Python version: 3.8
- CUDA/cuDNN version: None
- GPU model and memory: None
- Everything very "stock" - new, clean ground-up install from binary repos
- CPU flags:  `fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat`

Any attempt to load TensorFlow Python module, or run `tensorboard` (no parameters - no files) results in Illegal Instruction crash.

Both crashes appear to be within `libtensorflow_framework.so.2` - possibly calling into `librt-2.31.so`

Some sort of "python" core dump for `import tensorflow` here:
[https://s3.amazonaws.com/s3.bradgoodman.com/_usr_bin_python3.8.0.crash](https://s3.amazonaws.com/s3.bradgoodman.com/_usr_bin_python3.8.0.crash)

Standard Core dump for `tensorboard` crash here:
[https://s3.amazonaws.com/s3.bradgoodman.com/tensorboard.core](https://s3.amazonaws.com/s3.bradgoodman.com/tensorboard.core)

**Comment by mohantym** [comment]
Could you please confirm the Tensorflow version too?
