### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.eager'

### ISSUE THREAD

**Issue by rfmeloneto** [tensorflow/tensorflow#51915]
**System information**
-  I wrote a custom code
- Windows 10
- TensorFlow installed from source
- TensorFlow version : 2.6.0
- Python version:3.9

**Describe the current behavior**

When i run the code, the following error appears :
from tensorflow.python.eager import context
ModuleNotFoundError: No module named 'tensorflow.python.eager'

**Describe the expected behavior**

This error shouldn't happen. The tensorflow was correct installed. I also tried to re-install it, and the same error continue.

**Standalone code to reproduce the issue**
This is a load error, i cant run any tensorflow code.

**Other info / logs** 
  from tensorflow.python.eager import context
ModuleNotFoundError: No module named 'tensorflow.python.eager'

**Comment by mohantym** [comment]
Hi @rfmeloneto ! Did you verify with instructions here for building from [source](https://www.tensorflow.org/install/source_windows). Can you please try with Python 3.6.? I was not able to replicate this issue in  Colab though.
