### ISSUE TITLE
Attention and AdditiveAttention Layers not well documented.

### ISSUE THREAD

**Issue by nectario** [tensorflow/tensorflow#51913]
The attention layers (Attention and AdditiveAttention Layers) are not well documented. For example, I am able to pass a 4D input without issue when the current documentation say we should pass a 3D input.

What does it mean when I pass 4D input? Please provide more examples.

Thank you!

Nektarios

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by sushreebarsa** [comment]
@nectario Could you please have a look at the [link1](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention),[ link2](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AdditiveAttention), Please let us know if it helps?Thanks!

**Comment by nectario** [comment]
@sushreebarsa These examples I know about. They do not mention of what happens when 4D tensors are passed. Attention mechanism is a difficult topic, and more examples would be appreciated.

**Comment by nectario** [comment]
I really want to see more examples and information. I have a hard time understanding what a query is and value in regards to data that is not NLP related.

**Comment by Bhavay192** [comment]
Hey, is this issue still available to be worked upon?? If yes, then pls assign it to me.
