### ISSUE TITLE
How can I the outputs of tf_logging  on a TestCase

### ISSUE THREAD

**Issue by wu-yy** [tensorflow/tensorflow#51921]
I write a `test.TestCase` file, and i could't find the outputs of tf_logging.

code:
```
from tensorflow.python.platform import tf_logging
import logging
import sys
tf_logging.set_verbosity(tf_logging.INFO)
logger = logging.getLogger("tensorflow")
if len(logger.handlers) == 1:
  logger.handlers = []
  logger.setLevel(logging.INFO)
  formatter = logging.Formatter(
      "%(asctime)s - [%(filename)s:%(lineno)d] - %(name)s - %(levelname)s - %(message)s")
  ch = logging.StreamHandler(sys.stdout)
  ch.setLevel(logging.INFO)
  ch.setFormatter(formatter)
  logger.addHandler(ch)

class PipelineTest(test.TestCase):
  def __init__(self, method_name="runTest"):
    super(PipelineTest, self).__init__(method_name)

  def testBuild(self):
      tf_logging.info("Output")
```

compile command:
`
bazel test --test_arg=--v=3 --test_output=streamed //tensorflow/python:pipeline_embedding_ops_test
`
But I couldn't find the output of "logging.info("Output")".

throw a error : No handlers could be found for logger "tensorflow"

**Comment by tilakrayal** [comment]
@wu-yy ,
Can you please let us know the tensorflow version you are trying to execute the code.It helps in analysing the issue.Thanks

**Comment by wu-yy** [comment]
@tilakrayal ,  hi, the tensorflow version is `r1.15`.

**Comment by tilakrayal** [comment]
@wu-yy ,
We see that you are using tf version 1.0, 1.x is not actively supported, please update to latest stable version v2.5 or v2.6 and let us know if you are using same issue.
