### ISSUE TITLE
C++ compile tensorflow r2.5

### ISSUE THREAD

**Issue by MisRight** [tensorflow/tensorflow#51928]
tensorflow_cc.dll.if.exp : error LNK2001: 无法解析的外部符号 "public: __cdecl tensorflow::TensorShapeBase<class tensorflow::TensorShape>::TensorShapeBase<class tensorflow::TensorShape>(class absl::lts_2020_02_25::Span<__int64 const >)" (??0?$TensorShapeBase@VTensorShape@tensorflow@@@tensorflow@@QEAA@V?$Span@$$CB_J@lts_2020_02_25@absl@@@Z)
bazel-out\x64_windows-opt\bin\tensorflow\tensorflow_cc.dll : fatal error LNK1120: 1 个无法解析的外部命令
Target //tensorflow:tensorflow_cc.dll failed to build
INFO: Elapsed time: 28.003s, Critical Path: 25.68s
INFO: 4 processes: 2 internal, 2 local.
FAILED: Build did NOT complete successfully

**Comment by mohantym** [comment]
Hi @MisRight! We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks
