### ISSUE TITLE
How to edit Tensorflow SavedModel

### ISSUE THREAD

**Issue by marsupialtail** [tensorflow/tensorflow#51933]
I have a Tensorflow model trained in Python, exported to a .pb file and then used with Tensorflow Serving.

I have written a custom op that greatly speeds up the inference of some operators in this Tensorflow model, but only works for inference -- I can't use this custom op during training time.

I am wondering if it's possible for me to use this custom op with the .pb file in Tensorflow serving. I figure I will probably have to edit the .pb file such that it uses my custom op in place of the original op, and Tensorflow serving should then go about looking for the custom op implementation which I can link against its runtime.

So -- how does one go about modifying a Tensorflow .pb file and swap out operators? Are there example codes doing this that I can refer to?

Please help. Thank you very much.

**Comment by sushreebarsa** [comment]
@marsupialtail Could you please refer to the[ link1](https://www.tensorflow.org/tutorials/keras/save_and_load),[ link2](https://www.tensorflow.org/tutorials/keras/save_and_load) and let us know if it helps?Thanks!
