### ISSUE TITLE
Build on FreeBSD fails with protbuf related error

### ISSUE THREAD

**Issue by Huskers2020** [tensorflow/tensorflow#51932]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : FreeBSD
- TensorFlow installed from (source or binary): Source -
- TensorFlow version: 2.6
- Python version:3.8.11
- Installed using virtualenv? pip? conda?: compile 
- Bazel version (if compiling from source): 0.29
- GCC/Compiler version (if compiling from source): gcc10
- CUDA/cuDNN version: none
- GPU model and memory: n/a

**Protobuf version -3.17.3**

**Describe the problem**
During compile, I got the following error - I googled but did not find any related comments that could help me move forward. I did find one comment on gentoo where it was suggested the json file in questions needs to updated. Could not gather what exactly needs to be updated to get the build going.

[Gentoo issue link ](https://bugs.gentoo.org/800824)

Let me know if any additional info you need to support triage.

**ERROR: /usr/home/xxxx/Downloads/TensorFlow/FreeBSD-Tensorflow-master/science/py-tensorflow/work-py38/tensorflow-2.1.4/tensorflow/core/platform/BUILD:53:1: C++ compilation of rule '//tensorflow/core/platform:human_readable_json_impl' failed (Exit 1)
tensorflow/core/platform/default/human_readable_json.cc:36:29: error: no member named 'error_message' in 'google::protobuf::util::status_internal::Status'
   auto error_msg = status.error_message();
                    ~~~~~~ ^
tensorflow/core/platform/default/human_readable_json.cc:54:29: error: no member named 'error_message' in 'google::protobuf::util::status_internal::Status'
   auto error_msg = status.error_message();
                    ~~~~~~ ^
2 errors generated.****



**Provide the exact sequence of commands/steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Huskers2020** [comment]
Hello,
Thanks for the follow up!

The default compile did not work and upgrading to protobuf did not take me any further in Sept, 2022 when this defect was logged.

 Users like me when we run into OS specific roadblock have to depend on FreeBSD volunteers to compile this and post Sept, 2022 volunteers have compiled and posted the latest version on freshports and I have not checked on the latest config or make file updates to comment on. 

So for now we are good as we have an alternate compiled version available -

https://www.freshports.org/science/py-tensorflow/

Thanks

**Comment by mohantym** [comment]
Ok @Huskers2020 !

Thanks for the update. 
Marking this issue as resolved from above [comment](https://github.com/tensorflow/tensorflow/issues/51932#issuecomment-1381996844). 


Alternate linux version to  test  are Ubuntu 18/20 /Fedora linux /Debian-linux. 
Please post on [TF-Forum ](https://discuss.tensorflow.org/)for further assistance. 

Thank you!
