### ISSUE TITLE
Why is there no get in tensorflow version 2.3_ output_ Shape this function？

### ISSUE THREAD

**Issue by 86236291** [tensorflow/tensorflow#51931]
https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/engine/base_layer.py#L1463-L1480

**Comment by mohantym** [comment]
Hi @86236291 ,
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!
