### ISSUE TITLE
multiple tflite_runtime interpreters perform bad when loaded and invoked at the same time

### ISSUE THREAD

**Issue by FSet89** [tensorflow/tensorflow#51930]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: YOCTO Linux
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: not installed (tflite runtime only)
-   **TensorFlow version (use command below)**: not installed (tflite runtime only)
-   **Python version**: 3.6
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
I have a ARM64 board running YOCTO Linux equipped with a NPU and I have some quantized tflite models (one detection model and two classification models). I am testing a script that acquires images and makes inferences using the tflite_runtime module (with NNAPI delegate). Since the first inferences are slow, I introduced a warmup phase where I load the models and make an inference for each of them. However, this causes the models to produce wrong/unstable outputs during the normal functioning of the script. The same does not seem to happen when the interpreters are invoked at different times.

The detection model is a SSDMobileNetV2. The classification models are very simple custom architectures.

### Source code / logs

```
# relevant import
import tflite_runtime.interpreter as tflite

class DetectionModel(object):
	def __init__(self, path):
		self.interpreter = tflite.Interpreter(model_path=path)
		self.interpreter.allocate_tensors()
		self.input_details = self.interpreter.get_input_details()
		self.output_details = self.interpreter.get_output_details()
		self.input_shape = self.input_details[0]['shape']

	def predict(self, input_img):
		R, C, _ = input_img.shape
		img = cv2.resize(input_img, (self.input_shape[2], self.input_shape[1]))	
		if not self.input_details[0]['dtype'] == np.uint8:
			img = img.astype(np.float32)
			img = (img-128.0)/128.0
		img = np.expand_dims(img, 0)
		self.interpreter.set_tensor(self.input_details[0]['index'], img)			
		self.interpreter.invoke()			
		boxes = self.interpreter.get_tensor(self.output_details[0]['index'])
		classes = self.interpreter.get_tensor(self.output_details[1]['index'])
		scores = self.interpreter.get_tensor(self.output_details[2]['index'])

		return boxes, classes, scores
		
def initialize_classification_interpreter(path):
	interpreter = tflite.Interpreter(model_path=path)
	interpreter.allocate_tensors()
	input_details = interpreter.get_input_details()
	output_details = interpreter.get_output_details()

	input_shape = input_details[0]['shape']


	return interpreter, input_details, output_details

def classify(interpreter, input_details, output_details, img):
	
	input_shape = input_details[0]['shape']		

	img = (img/255.0).astype(np.float32)

	img = np.expand_dims(img, 0)
	interpreter.set_tensor(input_details[0]['index'], img)				
	interpreter.invoke()			
	output = interpreter.get_tensor(output_details[0]['index'])
	output = np.squeeze(output)

	return output

detection_model = DetectionModel(detection_path)
interpreter1, input_details1, output_details1 = initialize_classification_interpreter(classification_path_1)
interpreter2, input_details2, output_details2 = initialize_classification_interpreter(classification_path_2)

# warmup: this causes the issue
img = cv2.imread('test_img.jpg')
detection_model.predict(img)
classify(interpreter1, input_details1, output_details1, img)

cap = cv2.VideoCapture(0)

while cap.isOpened():
    ret, img = cap.read()
    # different conditions require different inferences
    if condition_1:
        result = detection_model.predict(img)
    if condition_2:
        result = classify(interpreter1, input_details1, output_details1, img)
    if condition_3:
        result = classify(interpreter2, input_details2, output_details2, img)

    # other operations...


```

**Comment by FSet89** [comment]
Any news on this?

**Comment by pkgoogle** [comment]
Hi @FSet89, what is 'detection_path' supposed to refer to?

**Comment by FSet89** [comment]
> Hi @FSet89, what is 'detection_path' supposed to refer to?

It's the path of the tflite model

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
