### ISSUE TITLE
NotImplementedError: quantile is not implemented: StudentT

### ISSUE THREAD

**Issue by mpkuperman** [tensorflow/tensorflow#51948]
Hi, all

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow version : 2.6.0
- Tensorflow probability version: 0.13.0
- Python version: 3.8.10

When trying to compute the [well documented](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/StudentT) quantile of a Student's T distribution, the following error shows in console: `NotImplementedError: quantile is not implemented: StudentT
`

Here is a MWE:

 ``` python
from tensorflow_probability import distributions as d 

t = d.StudentT(4.13, 0.0, 1.0)
t.quantile(0.2)
```
I think this issue is very similar to [20208](https://github.com/tensorflow/tensorflow/issues/20208) and [1259](https://github.com/tensorflow/probability/issues/1259).

Is there something I am missing?

Thanks in advance!

**Comment by tilakrayal** [comment]
@mpkuperman ,
This issue is more suitable for tensorflow/probability repo.Please feel free to close this issue and post in respective repo from [here](https://github.com/tensorflow/probability/issues).Thanks!
