### ISSUE TITLE
ValueError: Protocol message object_detection.protos.StringIntLabelMapItem has no non-repeated field "frequency"

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#51950]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow==1.15 (anaconda)
- TensorFlow version (use command below): 1.15
- Python version: 3.7.11

i am trying to run the script: updated_old_example.py from a tutorial without errors (see source:https://github.com/Bengemon825/TF_Object_Detection2020)

after i selected the correct interpreter with **tensorflow 1.15** and **python 3.7** i got the first error: **AttributeError: module 'tensorflow' has no attribute 'GraphDef'.**

Solution: **tf.compat.v1.GraphDef() + tf.compat.v2.io.gfile.GFile()**

at the end i get this error message: **ValueError: Protocol message object_detection.protos.StringIntLabelMapItem has no non-repeated field "frequency"** , where i didn't find a solution.

thanks for your help!

**Comment by sushreebarsa** [comment]
@Petros626 We see that you are using old version of tensorflow 1.15 which is not actively supported , We recommend that you upgrade to 2.6.0 and let us know if the issue still persists in newer versions. Thanks!

**Comment by Petros626** [comment]
@sushreebarsa hey thanks for your answer.

the funny thing is, before i had loaded an interpreter with **python 3.8** and **tensorflow 2.5**, there i got the error message that **Image** and **pyplot** would not contain a module. I think I could only install Image as a package the error for the Matplotlib remained, so I used an interpreter with tensorflow 1.15. finally the tutorial is also based on the older version :/

i can try again with the other interpreter and report back what happens

**Comment by Petros626** [comment]
@sushreebarsa i was also not successful with tensorflow 2  unfortunately i get other error messages which i could partially fix but the script remains unworkable.

with tensorflow 1 I have in any case the error because of the matplotlib and image no longer, also is marking in the code at tf.Graphdef() and tf.gfile.Gfile() disappeared, but still the error: AttributeError: module 'tensorflow' has no attribute 'GraphDef'

![gfile](https://user-images.githubusercontent.com/62354721/132981325-07d020d1-813c-47da-af3f-c3c448cf19b2.JPG)

**Comment by sushreebarsa** [comment]
@Petros626 Thanks for the update! Could you please provide the updated 2.x colab gist or notebook link to reproduce the issue reported here ?Thanks!

**Comment by Petros626** [comment]
@sushreebarsa  hey sorry i was very busy.. if i understand you correctly, you want the link to run the tutorial on jupyter notebook?

**Comment by sushreebarsa** [comment]
@Petros626  Can you please execute your code using Latest Version (2.6.0) and let us know if the issue still persists?  If so please provide the code snippet or colab gist in order to reproduce the issue . Thanks!

**Comment by Petros626** [comment]
> @Petros626 Thanks for the update! Could you please provide the updated 2.x colab gist or notebook link to reproduce the issue reported here ?Thanks!

**Comment by Petros626** [comment]
> @Petros626 Can you please execute your code using Latest Version (2.6.0) and let us know if the issue still persists? If so please provide the code snippet or colab gist in order to reproduce the issue . Thanks!

I use tf 2.6 as I mentioned before but it doesn't solve the error. Look above I describe what's happens if I use tf 2.6

**Comment by Saduf2019** [comment]
AttributeError: module 'tensorflow' has no attribute 'GraphDef'
please refer to [link](https://stackoverflow.com/questions/57614436/od-graph-def-tf-graphdef-attributeerror-module-tensorflow-has-no-attribut),[link2](https://githubmemory.com/repo/nikitakit/self-attentive-parser/issues/57)

**Comment by Petros626** [comment]
@sushreebarsa you can also write me privately by email to ask your expectation/question there?

**Comment by Petros626** [comment]
> 
> 
> AttributeError: module 'tensorflow' has no attribute 'GraphDef' please refer to [link](https://stackoverflow.com/questions/57614436/od-graph-def-tf-graphdef-attributeerror-module-tensorflow-has-no-attribut),[link2](https://githubmemory.com/repo/nikitakit/self-attentive-parser/issues/57)

i think i have tried these two sources once, but i will check again to see if they are of any use.
