### ISSUE TITLE
GPU Delegate Issue !

### ISSUE THREAD

**Issue by seragENTp** [tensorflow/tensorflow#51954]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android OS Oreo (API Level 27)
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: Surveillance Camera with QCS605 Qualcomm ship.
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.5
-   **Python version**: 3.8
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**: Adreno GPU 615
-   **Exact command to reproduce**:
-       final Interpreter.Options options = new Interpreter.Options();
        CompatibilityList compatList = new CompatibilityList();

        if (compatList.isDelegateSupportedOnThisDevice()) {
            // if the device has a supported GPU, add the GPU delegate
            GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
            GpuDelegate gpuDelegate = new GpuDelegate(delegateOptions);
            options.addDelegate(gpuDelegate);
            Log.i(LOGTAG, "-----------Running using GPU Delegate-----------");
        } else {
            // if the GPU is not supported, run on numThreads threads
            options.setNumThreads(numThreads)
                    .setAllowFp16PrecisionForFp32(allowFp16PrecisionForFp32)
                    .setUseNNAPI(useNNAPI);
            Log.i(LOGTAG, "------------Running using CPU Delegate---------");
        }

### Describe the problem

Trying to run [Movinet ](https://tfhub.dev/google/collections/movinet) tflite model on a vendor camera with Adreno GPU 615. 

The network runs on the CPU without any issues. But it can't be run on the GPU.  

I'm using Java TFLite run time with version 2.5. I tried the nightly version but didn't work also. 

### Source code / logs
I/Adreno: QUALCOMM build                   : e3ea17d, I2eff518144
I/Adreno: Build Config                     : S L 4.0.10 AArch64
I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

**Comment by impjdi** [comment]
Given

```
E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

```

I have the impression you are using a separate thread to asynchronously initialize and speed up things.  You cannot do that with OpenGL because GL context is bound to the thread.

**Comment by seragENTp** [comment]
@impjdi The only option i have now is to run the model inference part in background android service . Do you have any suggestions for workarounds  in order to make the GPU delegate run in background service  ?

**Comment by impjdi** [comment]
Hm, I'm not familiar with background services in Android, but as long as you use the *same thread*, it should be okay.  I'm not up to date with asynchronous programming in Java, but if you don't rely on fancy language structures that take care of the async execution behind your back (and thus has a chance to run your stuff in a different thread), you should be fine.  In other words, have a dedicated thread in which you initialize TFLite GPU and run inference.

**Comment by seragENTp** [comment]
@impjdi Thanks for your feedback. I rechecked my app and found that i was running the GPU inference part in a different thread than the main app thread.
