### ISSUE TITLE
Sum Total of in-use chunks: 7.23GiB, but it tried to allocate 8.00GiB

### ISSUE THREAD

**Issue by ckcz123** [tensorflow/tensorflow#5195]
> I tensorflow/core/common_runtime/bfc_allocator.cc:689]      Summary of in-use Chunks by size: 
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 22 Chunks of size 256 totalling 5.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 5 Chunks of size 512 totalling 2.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 1280 totalling 1.2KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 7499 Chunks of size 2048 totalling 14.65MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1087 Chunks of size 4096 totalling 4.25MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 4608 totalling 4.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 6144 totalling 6.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 616 Chunks of size 8192 totalling 4.81MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 9984 totalling 9.8KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 4 Chunks of size 10240 totalling 40.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 2 Chunks of size 12288 totalling 24.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 303 Chunks of size 14336 totalling 4.14MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 5 Chunks of size 198656 totalling 970.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 208384 totalling 203.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 919 Chunks of size 8388608 totalling 7.18GiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 10775552 totalling 10.28MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 14428160 totalling 13.76MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] Sum Total of in-use chunks: 7.23GiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:698] Stats: 
> Limit:                  7967745639
> InUse:                  7764832256
> MaxInUse:               7764842496
> NumAllocs:                   60834
> MaxAllocSize:             14428160
> 
> W tensorflow/core/common_runtime/bfc_allocator.cc:270] ****************************************************************************************************
> W tensorflow/core/common_runtime/bfc_allocator.cc:271] Ran out of memory trying to allocate 8.00MiB.  See logs for memory state.
> W tensorflow/core/framework/op_kernel.cc:968] Resource exhausted: OOM when allocating tensor with shape[1024,2048]
> E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
> E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 8.00G (8589934592 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

I have a 8G GPU memory (7.8G for free), and the allocator need to use 7.23G, which could be able to allocate.
But, it tried to allocate 8.00G, and threw out CUDA_ERROR_OUT_OF_MEMORY
I also set `config.gpu_options.allow_growth=True` , but it didn't matter.
How can I solve it? Thanks a lot!

**Comment by yaroslavvb** [comment]
Note that 7.23 GiB = 7.76 GB, so you were on the verge of exceeding your 7.8GB limit of the system. Generally the solution is to is to reduce memory usage. You can get more detailed memory allocation stats by recompiling with VLOG_IS_ON as described [here](http://stackoverflow.com/questions/36331419/tensorflow-how-to-measure-how-much-gpu-memory-each-tensor-takes/36505898#36505898) or using StepStats to see where memory gets allocated (that requires your .run call to succeed ) -- http://stackoverflow.com/questions/40190510/tensorflow-how-to-log-gpu-memory-vram-utilization/40197094#40197094

**Comment by drpngx** [comment]
Yaroslav's answer should be sufficient. Feel free to re-open if you encounter a bug.
