### ISSUE TITLE
host to device transfer is not utilizing close to PCIE bandwidth

### ISSUE THREAD

**Issue by rllin** [tensorflow/tensorflow#51951]
**System information**
- TensorFlow version (use command below): 2.3.0, 2.5.0, 2.6.0
- Python version: 3.7
- CUDA/cuDNN version: 11.2
- GPU model and memory: see colab on K80s, but this seems to happen on T4s, V100s, and A100s too

**Describe the current behavior**
device memory bandwidth is marketed as quite high, e.g.
> pciBusID: 0000:00:07.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s

**Describe the expected behavior**
cannot get over a few GB/s transferring tensors from CPU -> GPU

**Standalone code to reproduce the issue**
On a K80 in [colab](https://colab.research.google.com/drive/1RXQ79Phc5niKvtiq3FW403KtO36ok5zV#scrollTo=oP2iH3qXYOCn), we perform the following:

1. create a dataset that generates `100` batches of `[1024, 10000]` float32s
2. move tensor to GPU
3. multiple by own transpose

we measure the time it takes to do this `100` batches, effectively moving 
 `10000 float32 * 4 bytes/float32 * 1024 elements / step * 100 step * 1 GB / 1e9 bytes = 4.1 GB` of data from CPU to GPU.
 
we do this in both tensorflow and torch.

I get around `8.7s (0.47 GB/s)` in tensorflow and `2.5s (1.65 GB/s)` in torch; torch is 3.5x faster no matter how I move my tensors to the device in tensorflow.  (I tried a variety of approaches as discussed in https://github.com/tensorflow/tensorflow/issues/43905)

According to [this](https://www.techpowerup.com/gpu-specs/tesla-k80.c2616), K80s have PCIE 3.0x16 which look to be `15.75 GB/s` based on [wikipedia](https://en.wikipedia.org/wiki/PCI_Express)

**Neither pytorch nor tensorflow seem to approach this speed**

**Comment by mohantym** [comment]
Hi @rllin , Could not replicate issue in [2.5](https://colab.research.google.com/gist/mohantym/adb7d99b2ccd373fb0d9d0b81bf1295e/htd_test.ipynb#scrollTo=oP2iH3qXYOCn) ,[2.6](https://colab.research.google.com/gist/mohantym/ac446bbb9d6ad57b933109b4e433fb4f/htd_test.ipynb#scrollTo=QlgVm-dvT0M0) or [2.7 ](https://colab.research.google.com/gist/mohantym/74f5e2d826986cd477319006fc73813a/htd_test.ipynb#scrollTo=oP2iH3qXYOCn)in colab , was getting this issue only in TF 2.6 ,seems to be fixed in TF nightly (2.7.0 dev again) . Thanks!

**Comment by rllin** [comment]
@mohantym did you link the right colab?  (looks like it is bc i see 2.7.0 dev as the tf version)

but i see still ~8s which comes in at `0.47 GB/s`

![image](https://user-images.githubusercontent.com/1923997/133124804-f6b182b1-be34-4690-9784-5677f6388fe4.png)

**Comment by mohantym** [comment]
Yes ,The values match with my 2.7 colab gist , But I saw a difference in Torch timing in 2.7 (11.493 Torch 8.02  TF) unlike in TF 2.6 (3.13 Torch , 8.02 TF ).

**Comment by rllin** [comment]
@mohantym ah i see, good to know.  any thoughts so far?  perhaps torch 11 saw a similar regression with how htd is done that exists in tf?  because the most salient issue at hand is that neither of these throughputs approach hardware limits

**Comment by rllin** [comment]
thinking more about this @mohantym @sanatmpa1 , it doesn't matter really that torch is slower, and i should have put them in separate notebooks.  bc i would guess there's just contention with gpu memory when used in the same kernel as tensorflow.

the important comparison is tensorflow against the PCIEx16 bandwidth, and the torch replication is just a verification of that.

- tf (all versions) takes `8s` to transfer `4.1GB`
- torch (in its own [kernel/notebook](https://colab.research.google.com/drive/1rdoqs-tAQDDBvCp7CukvBKTInEk7Rx3O#scrollTo=Nx2MEFo7xioO)) takes `2.6s` to transfer `4.1GB`
- PCIEx16 should give up to `16 GB/s`

**Comment by rllin** [comment]
compare [against](https://colab.research.google.com/drive/1M5yFqlAgSY9KYpwuZf5AHyq0IH5EkTq9?usp=sharing) **NOT** using `tf.data` and just moving `tf.tensor`s manually from CPU -> GPU

- create `100` random `tf.tensor`s of `[1024, 10000]` of `tf.float32`
- move each of these one by one from CPU to GPU

this is also moving `4.1GB` total but only takes `0.62s`

**Comment by rllin** [comment]
if I replace the `tf.random.uniform` call with something faster:

```
features = np.random.uniform(size=[1024, 10000])
ds = tf.data.Dataset.from_tensors(features).repeat()
```

i get more reasonable speeds, `~1 s, 4 GB/s`

this is still quite below the `16 GB/s` the hardware permits however

**Comment by michal-hradis** [comment]
I ran into similar issue and created [stackoverflow question](https://stackoverflow.com/questions/70081599/is-cpu-to-gpu-data-transfer-slow-in-tensorflow). The question includes simple benchmark code, which I hope provides fair comparison. In my test CPU to GPU transfer is 2-8x faster in PyTorch (depending on the tensor size) with similar behavior with TF 2.4 and 2.6 (on RTX 2080ti and GTX 1080ti). Interestingly, Tensorflow slows down with large(r) tensors, PyTorch behaves well. This is frustratingly slow. 

Timing in TF:
`
code: tf.cast(x, dtype=tf.float32)[0, 0]
Batch size 1; Batch time 0.0005; BPS 1851.8; FPS 1851.8; MB/S 364.1
Batch size 2; Batch time 0.0004; BPS 2223.5; FPS 4447.1; MB/S 874.3
Batch size 4; Batch time 0.0006; BPS 1555.2; FPS 6220.6; MB/S 1223.0
Batch size 8; Batch time 0.0006; BPS 1784.8; FPS 14278.7; MB/S 2807.3
Batch size 16; Batch time 0.0013; BPS 755.3; FPS 12084.7; MB/S 2376.0
Batch size 32; Batch time 0.0023; BPS 443.8; FPS 14201.3; MB/S 2792.1
Batch size 64; Batch time 0.0035; BPS 282.5; FPS 18079.5; MB/S 3554.6
Batch size 128; Batch time 0.0061; BPS 163.4; FPS 20916.4; MB/S 4112.3
Batch size 256; Batch time 0.0241; BPS 41.5; FPS 10623.0; MB/S 2088.6
Batch size 512; Batch time 0.0460; BPS 21.7; FPS 11135.8; MB/S 2189.4
`

Timing in pytorch:
`
Code: torch.from_numpy(x).to(self.device).type(torch.float32)[0, 0].cpu()
Batch size 1; Batch time 0.0001; BPS 10756.6; FPS 10756.6; MB/S 2114.8
Batch size 1; Batch time 0.0001; BPS 12914.7; FPS 12914.7; MB/S 2539.1
Batch size 2; Batch time 0.0001; BPS 10204.4; FPS 20408.7; MB/S 4012.5
Batch size 4; Batch time 0.0002; BPS 5841.1; FPS 23364.3; MB/S 4593.6
Batch size 8; Batch time 0.0003; BPS 3994.4; FPS 31955.4; MB/S 6282.7
Batch size 16; Batch time 0.0004; BPS 2713.8; FPS 43421.3; MB/S 8537.0
Batch size 32; Batch time 0.0007; BPS 1486.3; FPS 47562.7; MB/S 9351.2
Batch size 64; Batch time 0.0015; BPS 679.3; FPS 43475.9; MB/S 8547.7
Batch size 128; Batch time 0.0028; BPS 359.5; FPS 46017.7; MB/S 9047.5
Batch size 256; Batch time 0.0054; BPS 185.2; FPS 47404.1; MB/S 9320.0
Batch size 512; Batch time 0.0108; BPS 92.9; FPS 47564.5; MB/S 9351.6
`

**Comment by sachinprasadhs** [comment]
I observe better performance in Tensorflow 2.12 compared to the previous versions, could you please find the attached gist [here](https://gist.github.com/sachinprasadhs/17076678ae6bb6ca9a551a3394bb84f3) and let us know if this result is satisfactory for you. Thanks!
![image](https://user-images.githubusercontent.com/73069040/232578750-e92d939f-0cd2-4e88-a5b6-03917592f3eb.png)
