### ISSUE TITLE
How to use tensorflow.experimental.numpy in tensorflow?

### ISSUE THREAD

**Issue by jiayugedede** [tensorflow/tensorflow#51963]
I have known `tensorflow.experimental.numpy` in tensorflow, but I don't know how to assign a value to a numpy NDarry, just like this.
`
    def get_dct_filter(self, tile_size_x, tile_size_y, mapper_x, mapper_y, channel):
        dct_numpy_filter = np.zeros(shape=(tile_size_y, tile_size_x, channel), dtype=np.float32)
        c_part = channel // len(mapper_x)

        for i, (u_x, u_y) in enumerate(zip(mapper_x, mapper_y)):
            for t_x in range(tile_size_x):
                for t_y in range(tile_size_y):
                    dct_numpy_filter[t_y, t_x, i * c_part: (i + 1) * c_part] = self.build_filter(t_x, u_x,
                                                                                                 tile_size_x) * \
                                                                               self.build_filter(t_y, u_y, tile_size_y)
        return dct_numpy_filter

    def build_filter(self, pos, frequency, POS):
        result = np.cos(np.pi * frequency * (pos + 0.5) / POS) / np.sqrt(POS)
        if frequency == 0:
            return result
        else:
            return result * np.sqrt(2)
`

When I use `tensorflow.experimental.numpy` do **dct_numpy_filter[t_y, t_x, i * c_part: (i + 1) * c_part] = self.build_filter(t_x, u_x, tile_size_x) * self.build_filter(t_y, u_y, tile_size_y)**, error has occured which told me tensor can't assign. I have used `np.experimental_enable_numpy_behavior(prefer_float32=True)` in code, but it not working, I don't know how to use the mechanism in deep learning training.

**Comment by sushreebarsa** [comment]
@jiayugedede In order to reproduce the issue reported here, could you please provide the complete code and the dataset , tensorflow version you are using. Thanks!

**Comment by sushreebarsa** [comment]
@jiayugedede Could you please refer to the[ link](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy) and let us know if it helps? Thanks!

**Comment by jiayugedede** [comment]
This link is helpless for me, part of the assignment in my code is the biggest problem, this link don't have this.

**Comment by jiayugedede** [comment]
Many algorithm in pytorch has efficient solution, however, we re-implement that in tensorflow which performance not satisfaction for us. This is the most block between pytorch and tensorflow 2.X.

**Comment by sushreebarsa** [comment]
@jiayugedede I tried to run your code on Colab using TF **v2.6**, **tf-nightly** and didn't face any error .Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/16ac35caf23156b1fcdeae6c751364f7/untitled203.ipynb#scrollTo=44-a43xJwwZJ) for reference and confirm the same ? Thank you!

**Comment by jiayugedede** [comment]
> @jiayugedede I tried to run your code on Colab using TF **v2.6**, **tf-nightly** and didn't face any error .Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/16ac35caf23156b1fcdeae6c751364f7/untitled203.ipynb#scrollTo=44-a43xJwwZJ) for reference and confirm the same ? Thank you!

I have saw the gist, I will find the way to solute it, all is well, never mind.

**Comment by sushreebarsa** [comment]
@jiayugedede Thanks for the update! Could you please let us know if we can close this issue as it has been resolved? Thanks!
