### ISSUE TITLE
Mac nightly build links in readme are broken

### ISSUE THREAD

**Issue by willwhitney** [tensorflow/tensorflow#5197]
Maybe this is because the last successful build was a month ago?

e.g. 
Mac CPU-only: Python 3 ->
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac1-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0rc1-py3-none-any.whl

This page shows:

```
HTTP ERROR 404

Problem accessing /view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac1-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0rc1-py3-none-any.whl. Reason:

    Not Found
```

**Comment by drpngx** [comment]
How about this one?

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0rc1-py3-none-any.whl

**Comment by yaroslavvb** [comment]
Also, nightly wheels for Mac GPU are present, but still using the old 11rc0
name instead of 11rc1
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-mac/

**Comment by willwhitney** [comment]
Yup, that works.

**Comment by drpngx** [comment]
Woohoo!
