### ISSUE TITLE
OSError: SavedModel file does not exist but I never explicitly saved a model

### ISSUE THREAD

**Issue by bensilver95** [tensorflow/tensorflow#51981]
I am trying to load a model from a URL with hub.load, but TF is trying to find a saved version of the model on my computer, even though I never saved the model.

When I did this the very first time, it worked no problem and loaded the model from the URL. But I believe now it's not working because it's looking for some sort of cached model file that doesn't actually exist. Note that I'm running this in a Jupyter notebook.

Any ideas how to solve this? Below find my code and traceback error.

`module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"`
`model = hub.load(module_url)`

OSError                                   Traceback (most recent call last)
<ipython-input-5-51e1a5214226> in <module>
    198 
    199 module_url = "https://tfhub.dev/google/universal-sentence-encoder/4"
--> 200 model = hub.load(module_url)
    201 #def embed(input):
    202 #    return model(input)

~/anaconda3/lib/python3.7/site-packages/tensorflow_hub/module_v2.py in load(handle, tags, options)
    104         module_path, tags=tags, options=options)
    105   else:
--> 106     obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
    107   obj._is_hub_module_v1 = is_hub_module_v1  # pylint: disable=protected-access
    108   return obj

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load(export_dir, tags, options)
    862   """
    863   metrics.IncrementReadApi(_LOAD_V2_LABEL)
--> 864   result = load_internal(export_dir, tags, options)["root"]
    865   metrics.IncrementRead()
    866   return result

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls, filters)
    876     tags = nest.flatten(tags)
    877   saved_model_proto, debug_info = (
--> 878       loader_impl.parse_saved_model_with_debug_info(export_dir))
    879 
    880   if (len(saved_model_proto.meta_graphs) == 1 and

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py in parse_saved_model_with_debug_info(export_dir)
     58     parsed. Missing graph debug info file is fine.
     59   """
---> 60   saved_model = _parse_saved_model(export_dir)
     61 
     62   debug_info_path = os.path.join(

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py in parse_saved_model(export_dir)
    119         "SavedModel file does not exist at: %s%s{%s|%s}" %
    120         (export_dir, os.path.sep, constants.SAVED_MODEL_FILENAME_PBTXT,
--> 121          constants.SAVED_MODEL_FILENAME_PB))
    122 
    123 

OSError: SavedModel file does not exist at: /var/folders/6z/8r9107bj20dcmrqn9kp8l2n40000gp/T/tfhub_modules/063d866c06683311b44b4992fd46003be952409c/{saved_model.pbtxt|saved_model.pb}

**Comment by sushreebarsa** [comment]
@bensilver95 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
