### ISSUE TITLE
Profile TensorFlow Performance: Multiple occurences of single Conv2D op

### ISSUE THREAD

**Issue by shelkesagar29** [tensorflow/tensorflow#51995]
------------------------

### System information

-   **Custom Code**
-   **Linux Ubuntu 20.04**
-   **TensorFlow installed from (source or binary)**: Binary
-   **TensorFlow version (use command below)**: 2.6
-   **Python version**: 3.8
-   **Bazel version (if compiling from source)**: None
-   **GCC/Compiler version (if compiling from source)**: None
-   **CUDA/cuDNN version**: 11.4/8.2
-   **GPU model and memory**: RTX3090/24GB
-   **Exact command to reproduce**:

### Describe the problem
Profile NN layers runtime on GPU device (I am concerned only with inference). I am using
tf.profiler module. 

### Source code / logs
I have created a dummy network with just a single convolution layer.
dummy_net.py
```
import tensorflow as tf
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

class Net(tf.keras.Model):
    def __init__(self) -> None:
        super().__init__()
        self.conv = tf.keras.layers.Conv2D(6,3)
    
    def call(self, x):
        x = self.conv(x)
        return x
```
And testing it on random input.

test_dummy_net.py

```
import tensorflow as tf
import dummy_net

inp = tf.random.uniform([1,300,300,3])
model = dummy_net.Net()
tf.profiler.experimental.start('./dummy_infer_logs')
y = model(inp)
tf.profiler.experimental.stop()
tf.debugging.set_log_device_placement(True)
```
When I check profile logs in the TensorBoard, it shows that Conv2D op has occurred multiple times.
![image](https://user-images.githubusercontent.com/25697952/133319278-cb43ff62-9b35-4909-bfce-84fb9692f5cb.png)

When I add more Conv2D layers, occurrences go on increasing. For example, for 4 Conv2D layers more than 1900 occurrences are shown. This makes it difficult to get exact run times.

Also, why same operations are also run on the host?
![image](https://user-images.githubusercontent.com/25697952/133319852-30e13c82-955f-43ec-8ca5-b561b41bde4b.png)

**Comment by tilakrayal** [comment]
@shelkesagar29 ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Also tensorflow is compatible with specific cuda and cudnn version.Please refer the [link](https://www.tensorflow.org/install/source#gpu) for the same and try to install as mentioned.Thanks

**Comment by shelkesagar29** [comment]
I could not change template. I am closing this and have opened #52048
