### ISSUE TITLE
tensorflow-macos fails to install due to wheel build failure

### ISSUE THREAD

**Issue by kode54** [tensorflow/tensorflow#51999]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey beta 6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version: tensorflow-macos 2.5.0
- Python version: 3.8.10, 3.9.7
- Installed using virtualenv? pip? conda?: Mambaforge 4.10.3-5, conda, pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): Xcode 13 beta 6
- CUDA/cuDNN version:
- GPU model and memory: Apple G13G, 16GB system RAM

**Describe the problem**
When attempting to install tensorflow-macos with either Python 3.8 or 3.9, it fails when it tries to install grpcio.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
conda create -n tf python=3.8
```

or:

```
conda create -n tf
```

Then following with:
```
conda activate tf
conda install -c apple tensorflow-deps
pip install tensorflow-macos
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[pip.log](https://github.com/tensorflow/tensorflow/files/7165907/pip.log)

numpy appears to be trying to install a version of wheels that thinks that anything that isn't x86 has altivec.

**Comment by kode54** [comment]
Oops, I just realized this is probably best covered by Apple's Tensorflow repository issue tracker. I can leave this here if it's useful to anyone, though.

**Comment by tilakrayal** [comment]
@kode54 ,
Every TensorFlow release is compatible with a certain version, for more information please take a look at the tested build [configurations](https://www.tensorflow.org/install/source#cpu_2).In this case, can you please try installing TensorFlow v2.5 with compatible compiler and bazel version and check if you are facing the same error. Thanks!
