### ISSUE TITLE
A few documentation errors and omissions for "Install TensorFlow for C"

### ISSUE THREAD

**Issue by EricTheRed20** [tensorflow/tensorflow#51996]
The page **https://www.tensorflow.org/install/lang_c** "Install TensorFlow for C" has several errors and omissions:-
1. The first link "bindings for other languages" is a dead link (error 404)
2. It says that it is built nightly, but the second link "libtensorflow-nightly GCS bucket" says that it was last built about a year ago
3. It looks as though it was last built about a month ago.  It would be good to have the date that it was last built somewhere on the page
4. For "Supported Platforms", it says that it works for "macOS, Version 10.12.6 (Sierra) or higher", but the download file says that it is for a x86_64 (ie. Intel) CPU.  The latest Macs (for almost a year now) use the M1 processor.  Does it support the M1 Mac.

**Comment by Saduf2019** [comment]
@EricTheRed20 
We have created a CL for this once the CL is closed, we will update this issue to resolved.

**Comment by EricTheRed20** [comment]
I've tested the libtensorflow.dylib file (and the other ones) for compatibility with the M1 Mac by running the XCode command: xcrun lipo -info "libtensorflow.dylib" and it returns "libtensorflow.dylib is architecture x86_64".  It should return "libtensorflow.dylib are: arm64 x86_64" in order to support both the Intel Mac and the M1 Mac.

The line "macOS, Version 10.12.6 (Sierra) or higher" can therefore be updated to say "macOS, Version 10.12.6 (Sierra) or higher for Intel Macs only (M1 Mac not available yet)

**Comment by Saduf2019** [comment]
@EricTheRed20 
Is this still an issue.

**Comment by EricTheRed20** [comment]
Item 1 has been fixed, but items 2, 3 and 4 haven't been fixed, so yes, it is still an issue

**Comment by mohantym** [comment]
Hi @EricTheRed20 
For Mac M1 , You can refer[ metal plugin ](https://developer.apple.com/metal/tensorflow-plugin/)document from Apple forum .  Mentioning dates in  nightly-gcs-bucket is a good idea though to reflect the update.
Thank you!

**Comment by mohantym** [comment]
Hi @EricTheRed20 !

Can  you raise a PR and do the  the rest of the needed changes in the source code [here](https://github.com/tensorflow/docs/blob/master/site/en/install/lang_c.ipynb). Regarding Mac M1, Engg. Team is into building official wheel for M1 and other ArM support.

Thank you!

**Comment by tilakrayal** [comment]
@EricTheRed20,
 The first link `"bindings for other languages"` from the doc https://www.tensorflow.org/install/lang_c  is working as expected.  [Reference](https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/extend/bindings.md)

The link libtensorflow-nightly GCS bucket was working and also **<LastModified 2022-03-04T10:13:22.655Z LastModified>** [Reference](https://storage.googleapis.com/libtensorflow-nightly) & the last tensorflow build was 2.11.0 which was update under the **download and extract** https://www.tensorflow.org/install/lang_c#setup

And the last one Could you please ignore this command in MacOS as per https://github.com/protocolbuffers/protobuf/issues/2570#issuecomment-271358087 here. This command was used earlier for MacOS
**sudo update_dyld_shared_cache** which was deprecated with the latest MacOS versions.

To resolve this please try to use this command `export LD_LIBRARY_PATH=/usr/local/lib` when installing on Mac instead of 
`sudo ldconfig /usr/local/lib`

**Comment by EricTheRed20** [comment]
Thanks for the update.

The Mac OS CPU file name is still called "libtensorflow-cpu-darwin-x86_64-2.11.0.tar.gz" which means that it has been built for the old Intel x86_64.  Macs started using their own M1 processor from October 2021.  It would be good if "libtensorflow" for the Mac ran on the latest Mac or even better as a Universal Binary where it runs natively on both.

The XCode command     xcrun lipo -info "libtensorflow.dylib"   should return   "libtensorflow.dylib are: arm64 x86_64"    which means it runs on both old and new CPUs.

Yes we can probably compile it ourselves, but that is in the too hard basket for most of us.  It would be much better if we could download it and just use it like we can for Linux and Windows.

**Comment by SuryanarayanaY** [comment]
> The Mac OS CPU file name is still called "libtensorflow-cpu-darwin-x86_64-2.11.0.tar.gz" which means that it has been built for the old Intel x86_64. Macs started using their own M1 processor from October 2021. It would be good if "libtensorflow" for the Mac ran on the latest Mac or even better as a Universal Binary where it runs natively on both.

@EricTheRed20 ,  Right now TF won't have Binaries for Arm architecture.Not sure whether we can have it in Future and that may depends on Community Ask in future. You can see in the doc page that its only for macos-cpu only though not explicit about Arm architecture.

Right now all pre-built binaries are for X86-64 architecture. For Mac M1,M2 Apple have its own binaries and one can follow the instructions [here](https://developer.apple.com/metal/tensorflow-plugin/).Please note this might be for Python only.

For Point-3 you can check the last updated time at the bottom of the [page](https://www.tensorflow.org/install/lang_c#:~:text=Last%20updated%202023%2D01%2D21%20UTC.).

Thanks!
