### ISSUE TITLE
tensor.eval() function converts a tensor to a numpy array is very slow. 

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5199]
I am using inception V1 model to predict image. The input needs a 4d array.

This section is read a image and resize to 224 * 224 * 3, then whitening, then convert to 4D tensor

-----------------------------------------------------------------------------------------------
  with open(image, 'rb') as f:
    image_data = f.read()
  
  image_buffer=tf.image.decode_jpeg(image_data)
  resize_image=tf.image.resize_images(image_buffer,[224,224])
  unified_image=tf.image.per_image_whitening(resize_image)
  image_4dTensor=tf.expand_dims(unified_image, 0)

------------------------------------------------------------------------------------------------

This section is to input an image and run the session. Since i can't input a 4D tensor but a numpy array into the session, I need convert 4D tensor to 4D array by call **tensor.eval()**. However i found that this conversion for a 1 * 224 * 224 * 3 tensor is very slow. It needs 0.4-0.6s. The prediction itself only takes less than 0.2s (run through 22 layers for a input 4D array ). So Is there anyway to convert a tensor to a numpy array faster?

  with tf.Session() as sess:

    stamp1=time.time()
    image_array=image_4dTensor.eval()
    time_cost=time.time()-stamp1
    print (time_cost)

**Comment by yaroslavvb** [comment]
This may be better for stackoverflow, but I would guess you need to hook up your inception v1 to accept a tensor instead of numpy array, possibly using graph_editor to do the change if you are loading an existing graph

**Comment by civilmanxx** [comment]
I am using the public inception v1 model. pb file. I do not change anything.

**Comment by civilmanxx** [comment]
tensor flow model itself does not accept a tensor object is very ironic.

**Comment by yaroslavvb** [comment]
That's because to accept a tensor, you need to connect a node to an existing graph, and until recently (graph_editor), this was not possible because graphs were append-only (no prepend)

**Comment by gnujimmik** [comment]
I also have the same issue but with my own code. I tried to use image_batch.eval() and it is extremely slow. the batch size is only 3, 1024, 1024, 3. I am not sure if the eval() works properly.

**Comment by yaroslavvb** [comment]
`eval` recalculates all tensors that are needed to get the result, if you want to speed things up, you should cache things into `tf.Variable` objects
