### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#51990]
![9](https://user-images.githubusercontent.com/26819449/133263607-e9733e7c-b6d5-4d11-87e2-8dbc740009c6.JPG)

![9 1](https://user-images.githubusercontent.com/26819449/133263637-5905c37b-0c77-4ff9-a983-426e3aea5f9d.JPG)

 tensor flow = 2.2
 keras = 2.4.3
 
I am not able to solve this error.
Can you please tell me where should I refer?
Thanks!

**Comment by sushreebarsa** [comment]
@starboyvarun 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
