### ISSUE TITLE
Problem running RNN example

### ISSUE THREAD

**Issue by kentonl** [tensorflow/tensorflow#52]
The shape argument in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py#L123 should be a tensor ( [-1] instead of -1). Otherwise, the example does not run.

**Comment by rafaljozefowicz** [comment]
Thanks for the report. We'll update the code.

**Comment by vrv** [comment]
Fixed in the source in https://github.com/tensorflow/tensorflow/commit/41930f0b81b52a34fb56d921c9bad65c36168323.  Will be also pushed out in the next binary release.
