### ISSUE TITLE
Changing 1 kernel op requires recompile of the entire kernel package... slow : (

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#520]
For example, I make some working changes into any one tensorflow/core/my_kernel.{cc,h} file will require the recompile of the entire:

240 tf_cuda_library(
241     name = "kernels",

library, which may be OK for Google assuming you guys have many cores and very fast machines, but for the average developer on say mac laptop, its insanely slow ... total compile time can range several minutes : (

I am not sure what the correct solution is, either fix this in Bazel or seperate out each kernel to have its own build rule?

**Comment by mrry** [comment]
This will (probably) be addressed by the work @keveman is doing to improve registration for user ops, so I'll assign to him for now.

**Comment by keveman** [comment]
I added [instructions]( https://www.tensorflow.org/versions/master/how_tos/adding_an_op/index.html#adding-a-new-op) for building ops and kernels outside of TensorFlow source tree. Please have a look to see if it fits your need.
