### ISSUE TITLE
Handle `attrs` objects in `tensorflow.python.util.nest.assert_shallow_structure`

### ISSUE THREAD

**Issue by christiaanjs** [tensorflow/tensorflow#52000]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): *Yes*
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (use command below): **v1.12.1-63725-gfeb49693266 2.7.0-dev20210914**
- Python version: **3.7.11**
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Error when trying to use the methods in `tensorflow.python.util.nest` that call `assert_shallow_structure`, e.g. `map_structure_up_to`, on an instance of a class created by `attrs`.

This happens when trying to subclass `tensorflow_probability.python.distributions.Distribution` where `_event_shape` is an `attrs` object and the public `event_shape` method calls `map_structure_up_to`.

**Describe the expected behavior**

This call should run without an error on `attrs` objects like `map_structure` does.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): **yes**
- Briefly describe your candidate solution(if contributing): **Add another case before the default one that checks `_is_attrs` and makes sure that the names are the same using `_get_attrs_items`.**

**Standalone code to reproduce the issue**

```python
import attr
import tensorflow as tf
from tensorflow.python.util import nest

@attr.attrs(auto_attribs=True)
class Container:
    a: object
    b: object

shape_object = Container(a=[1, 2], b=[3])
shallow_object = Container(a=None, b=None)
shape_res = nest.map_structure_up_to(shallow_object, tf.TensorShape, shape_object)

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "scratch.py", line 14, in <module>
    shape_res = nest.map_structure_up_to(shallow_object, tf.TensorShape, shallow_object)
  File "/home/cswa648/miniconda3/envs/tftest/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 1380, in map_structure_up_to
    **kwargs)
  File "/home/cswa648/miniconda3/envs/tftest/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 1462, in map_structure_with_tuple_paths_up_to
    expand_composites=expand_composites)
  File "/home/cswa648/miniconda3/envs/tftest/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 1090, in assert_shallow_structure
    if len(input_tree) != len(shallow_tree):
TypeError: object of type 'Container' has no len()
```

**Comment by sushreebarsa** [comment]
@christiaanjs I tried to run the code on Colab using `TF v2.6` and `tf-nightly` ,and faced type error ,please find the gist[ here ](https://colab.research.google.com/gist/sushreebarsa/bc5dcd38caed585940d3b88b887671f8/untitled199.ipynb)for reference. Could you please confirm the same ? Thanks!

**Comment by christiaanjs** [comment]
@sushreebarsa yes, this is the same error I’m reporting (see the output I provided)

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue on colab using `TF v2.9.0`, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a0be01714f207d03c199e9e215fe82be/52000.ipynb) for reference.
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
