### ISSUE TITLE
Error when building /pi_examples/label_image on RPi 3 (/usr/include/jpeglib.h:792:3: error: ‘size_t’ does not name a type)

### ISSUE THREAD

**Issue by drag0** [tensorflow/tensorflow#5200]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Some comments here mention the same problem: https://github.com/tensorflow/tensorflow/issues/4680#issuecomment-256078792

### Environment info
Operating System:
Raspberry Pi 3
RASPBIAN JESSIE WITH PIXEL
Image with PIXEL desktop based on Debian Jessie
Version:September 2016
Release date:2016-09-23
Kernel version:4.4
If installed from source, provide 

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
followed instructions here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples/

### What other attempted solutions have you tried?
Tried changing compiler defined in Makefile to g++-4.8 but to no avail

### Logs or other output that would be helpful

> 
> make -f tensorflow/contrib/pi_examples/label_image/Makefile 
> gcc --std=c++11 -O0 -I/usr/local/include -I. -I/home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/downloads -I/home/pi/code/tensorflow/t
> ensorflow/contrib/pi_examples/label_image/../../makefile/downloads/eigen/ -I/home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/gen/proto
> / -I/home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/gen/proto_text/ -c tensorflow/contrib/pi_examples/label_image/label_image.cc -o /
> home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/gen/obj/tensorflow/contrib/pi_examples/label_image/label_image.o
> In file included from tensorflow/contrib/pi_examples/label_image/label_image.cc:26:0:
> /usr/include/jpeglib.h:792:3: error: ‘size_t’ does not name a type
>    size_t free_in_buffer; /* # of byte spaces remaining in buffer */
>    ^
> /usr/include/jpeglib.h:804:3: error: ‘size_t’ does not name a type
>    size_t bytes_in_buffer; /* # of bytes remaining in buffer */
>    ^
> In file included from /usr/include/jpeglib.h:29:0,
>                  from tensorflow/contrib/pi_examples/label_image/label_image.cc:26:
> /usr/include/jpeglib.h:835:3: error: ‘size_t’ has not been declared
>    JMETHOD(void *, alloc_small, (j_common_ptr cinfo, int pool_id,
>    ^
> /usr/include/jpeglib.h:837:3: error: ‘size_t’ has not been declared
>    JMETHOD(void FAR *, alloc_large, (j_common_ptr cinfo, int pool_id,
>    ^
> In file included from tensorflow/contrib/pi_examples/label_image/label_image.cc:26:0:
> /usr/include/jpeglib.h:990:34: error: ‘size_t’ has not been declared
>  EXTERN(void) jpeg_CreateCompress JPP((j_compress_ptr cinfo,
>                                   ^
> /usr/include/jpeglib.h:992:36: error: ‘size_t’ has not been declared
>  EXTERN(void) jpeg_CreateDecompress JPP((j_decompress_ptr cinfo,
>                                     ^
> /usr/include/jpeglib.h:1000:30: error: ‘FILE’ has not been declared
>  EXTERN(void) jpeg_stdio_dest JPP((j_compress_ptr cinfo, FILE * outfile));
>                               ^
> /usr/include/jpeglib.h:1001:29: error: ‘FILE’ has not been declared
>  EXTERN(void) jpeg_stdio_src JPP((j_decompress_ptr cinfo, FILE * infile));
>                              ^
> tensorflow/contrib/pi_examples/label_image/label_image.cc: In function ‘tensorflow::Status LoadJpegFile(std::string, std::vector<unsigned char>*, int*, int*, int*)’:
> tensorflow/contrib/pi_examples/label_image/label_image.cc:108:32: error: cannot convert ‘FILE* {aka _IO_FILE*}’ to ‘int*’ for argument ‘2’ to ‘void jpeg_stdio_src(j_dec
> ompress_ptr, int*)’
>    jpeg_stdio_src(&cinfo, infile);
>                                ^
> tensorflow/contrib/pi_examples/label_image/label_image.cc: In function ‘int main(int, char**)’:
> tensorflow/contrib/pi_examples/label_image/label_image.cc:318:3: error: ‘vector’ was not declared in this scope
>    vector tensorflow::Flag > flag_list = {
>    ^
> tensorflow/contrib/pi_examples/label_image/label_image.cc:318:3: note: suggested alternatives:
> In file included from /usr/include/c++/4.9/vector:64:0,
>                  from tensorflow/contrib/pi_examples/label_image/label_image.cc:29:
> /usr/include/c++/4.9/bits/stl_vector.h:214:11: note:   ‘std::vector’
>      class vector : protected _Vector_base<_Tp, _Alloc>
>            ^
> /usr/include/c++/4.9/bits/stl_vector.h:214:11: note:   ‘std::vector’
> tensorflow/contrib/pi_examples/label_image/label_image.cc:333:52: error: ‘flag_list’ was not declared in this scope
>    string usage = tensorflow::Flags::Usage(argv[0], flag_list);
>                                                     ^
> tensorflow/contrib/pi_examples/label_image/label_image.cc:335:8: error: in argument to unary !
>    if (!parse_result) {
>         ^
> tensorflow/contrib/pi_examples/label_image/label_image.cc:341:49: error: cannot convert ‘std::string {aka std::basic_string<char>}’ to ‘const char*’ for argument ‘1’ to
>  ‘void tensorflow::port::InitMain(const char*, int*, char***)’
>    tensorflow::port::InitMain(usage, &argc, &argv);
>                                                  ^
> tensorflow/contrib/pi_examples/label_image/Makefile:79: recipe for target '/home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/gen/obj/tensorflow/contri
> b/pi_examples/label_image/label_image.o' failed
> make: *** [/home/pi/code/tensorflow/tensorflow/contrib/pi_examples/label_image/gen/obj/tensorflow/contrib/pi_examples/label_image/label_image.o] Error 1
> 
>

**Comment by drag0** [comment]
I've solved half of errors by adding 
`#include <stdio.h>`
before line:
`#include <jpeglib.h>`

Now I'm getting:

> tensorflow/contrib/pi_examples/label_image/label_image.cc:319:3: error: ‘vector’ was not declared in this scope

**Comment by drag0** [comment]
Just managed to build it successfully with slight code changes. I don't know C++ but I followed errors and fixed it one by one. It seems that this commit broke things: https://github.com/tensorflow/tensorflow/commit/20c02ffe0e6b8af4902487f852e15daa16caa523#diff-48887acc98c15e53f942842ecd65190f

So what I did was:

Open label_image.cc and do this:

Add:
`#include <stdio.h>`
before 
`include <jpeglib.h>`


Find:
`vector tensorflow::Flag > flag_list = {` around line 320 and change it to:
`std::vector<tensorflow::Flag> flag_list = {`

Last thing, just couple lines after last change:
`tensorflow::port::InitMain(usage, &argc, &argv);` change it to:
`tensorflow::port::InitMain(argv[0], &argc, &argv);`

That's it, now just run:
`make -f tensorflow/contrib/pi_examples/label_image/Makefile`
and wait a minute while it finishes, you can then run example by running:
`tensorflow/contrib/pi_examples/label_image/gen/bin/label_image`

Could anyone help me understand what happened in this diff that broke things and how it got merged to master? Also, I'm not really sure last change is the right thing to do, but it compiles and builds so it is a quickfix for me.

**Comment by drpngx** [comment]
Thanks! Would you mind sending a PR?

**Comment by drag0** [comment]
No problem, It's getting a bit late here so I might send it tomorrow morning.

**Comment by drpngx** [comment]
Nice, thanks!

**Comment by marktheunissen** [comment]
Thanks, worked for me! Some really obvious errors there that a linter would have picked up.

**Comment by karunmj** [comment]
Go this to work, thank you @drag0
