### ISSUE TITLE
Cannot load save tf model

### ISSUE THREAD

**Issue by pacospace** [tensorflow/tensorflow#52013]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 33
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`:
`v2.6.0-rc2-32-g919f693420e 2.6.0`

**Describe the current behavior**
`tf.saved_model.load(model_path)` fails with the following error:

```
Traceback (most recent call last):
  File "convert_to_onnx.py", line 3, in <module>
    tf.saved_model.load('/home/fmurdaca/work/aicoe/elyra-aidevsecops-tutorial/models/210915165333-7b04047d1220f5cd')
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 902, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/home/fmurdaca/.local/share/virtualenvs/convert-onnx-KeTiB-gU/lib64/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

This also breaks tensorflow-onnx package: https://github.com/onnx/tensorflow-onnx/issues/1715

**Describe the expected behavior**
method is able to load model, so that other actions can be performed.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): adjust attribute provided by that object

**Standalone code to reproduce the issue**
1. clone https://github.com/AICoE/elyra-aidevsecops-tutorial
2. pip install tensorflow
3. run python script with import tensoflow as tf and `tf.saved_model.load('./models/210124112759-d97fd1f46b13ee40')`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @pacospace ! Please use following code to load your model. 
`tf.keras.models.load_model("./elyra-aidevsecops-tutorial/models/210124112759-d97fd1f46b13ee40")`

**Comment by daniel-kukiela** [comment]
Hi!
I have the very same issue with TensorFlow 2.6

I'm loading our upsample model and saving it as a saved model:
```py
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow_addons.layers import InstanceNormalization, SpectralNormalization

model = load_model('upsample---[_20]---[______3171]---[_____63420].h5', custom_objects={'InstanceNormalization': InstanceNormalization, 'SpectralNormalization': SpectralNormalization})

tf.saved_model.save(model, 'upsample_saved_model')
```
Then, when I'm trying to load it:
```py
import tensorflow as tf

model = tf.saved_model.load('./upsample_saved_model')
```
It errors with:
```
Traceback (most recent call last):
  File "/home/daniel/trt/2_find_layer_names.py", line 4, in <module>
    model = tf.saved_model.load('upsample_saved_model')
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 902, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 162, in __init__
    self._load_all()
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 259, in _load_all
    self._load_nodes()
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/saved_model/load.py", line 448, in _load_nodes
    slot_variable = optimizer_object.add_slot(
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

The same code works just fine in TensorFlow 2.5.

If you need the model to test: https://github.com/Sentdex/GANTheftAuto/tree/main/trained_models (it's the upsample one).


Regards,
Daniel

**Comment by mohantym** [comment]
Hi @daniel-kukiela ,Could not replicate above issue in TF 2.6 after putting complete path of model file as below.  
`model = load_model('/content/GANTheftAuto/trained_models/upsample---[_20]---[______3171]---[_____63420].h5', custom_objects={'InstanceNormalization': InstanceNormalization, 'SpectralNormalization': SpectralNormalization})`

providing [Gist ](url)for reference.

**Comment by mohantym** [comment]
Hi @pacospace ,Feel free to close issue if it helped.

**Comment by pacospace** [comment]
> Hi @pacospace ,Feel free to close this issue if it helped.

Thanks @mohantym, your suggestion worked!

**Comment by daniel-kukiela** [comment]
@mohantym I have no such path. Where did you get it from? I have a script and a folder with a model in the same folder, it's nothing like what you proposed. I'm not sure what your suggestion is supposed to do. Can you elaborate?

Also, it works this way in TF 2.5 and there's no reason it should not work in TF 2,6. It's like I have TF 2.6 and it does not work, then I'm downgrading to TF 2.5 and the same scripts work as expected.

I still call it a bug and it should not be closed IMO.

**Comment by daniel-kukiela** [comment]
Oh wait @mohantym - in your reply to me, you mentioned the wrong line of code. Loading a model and saving it as a saved model works (the upper script). Loading the saved model is what does not (the lower script).

**Comment by daniel-kukiela** [comment]
Hi @pacospace ,
Can I expect anything still here to happen (I can patiently wait), or do I have to open another issue?

**Comment by pacospace** [comment]
> Hi @pacospace ,
> Can I expect anything still here to happen (I can patiently wait), or do I have to open another issue?

Hey @daniel-kukiela, from the initial issue/question, I would consider this solved, because using `tf.keras.models.load_model("./elyra-aidevsecops-tutorial/models/210124112759-d97fd1f46b13ee40")` solved my problem. If you want specifically Tensorflow team to solve the issue when you use `tf.saved_model.load` I can reopen it, wdyt @ 
mohantym?

**Comment by mohantym** [comment]
Hi @daniel-kukiela , Sorry for the late response! Actually I checked in Colab earlier.Tried to replicate and resolve the issue. [GIST ](https://colab.research.google.com/gist/mohantym/187d7a2dc387998237211d7c590c6b1a/github_52013_sentdex.ipynb)for reference .For Further help! Please open a new issue. Thanks!

**Comment by daniel-kukiela** [comment]
@mohantym 
You are running everything in a single runtime.
After you downloaded/installed everything and converted a model to a saved model, please use Runtime -> Restart runtime and then try to load saved model (in a new runtime).
I'm going to post it as a separate issue.

Thank you
