### ISSUE TITLE
tf.keras   TypeError: unsupported operand type(s) for +: 'NoneType' and 'float

### ISSUE THREAD

**Issue by Winndy** [tensorflow/tensorflow#52010]
<em>Please make sure that this is an issue related to keras.
tag:keras_template</em>

**Important Notice**

Please note that `tf.keras` code was moved entirely to
[keras-team/keras](https://github.com/keras-team/keras) repository

You can open any code/doc bugs, performance issues, and feature requests
 in [keras-team/keras](https://github.com/keras-team/keras/issues) repository

`tf.keras` related issues opened in
[tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repository may
not get attention as [keras-team/keras](https://github.com/keras-team/keras)
repository is dedicated for the development of `keras` code

**Comment by tilakrayal** [comment]
@Winndy ,
Please take a look at this issues with similar error.[1](https://github.com/tensorflow/tensorflow/issues/20867#issuecomment-422246723) and [2](https://github.com/AppliedDataSciencePartners/DeepReinforcementLearning/issues/12). It helps.Thanks!
