### ISSUE TITLE
cannot import name 'Adadelta' from 'keras.optimizers (Keras-Bidaf)

### ISSUE THREAD

**Issue by ReetuData** [tensorflow/tensorflow#52026]
ImportError                               Traceback (most recent call last)
<ipython-input-26-bc8a96d755fb> in <module>
----> 1 from bidaf.models import BidirectionalAttentionFlow
      2 #bidaf_model = BidirectionalAttentionFlow(400)
      3 #keras_model = bidaf_model.model

~\AppData\Roaming\Python\Python38\site-packages\bidaf\models\__init__.py in <module>
----> 1 from .bidaf import BidirectionalAttentionFlow

~\AppData\Roaming\Python\Python38\site-packages\bidaf\models\bidaf.py in <module>
      1 from keras.layers import Input, TimeDistributed, LSTM, Bidirectional
      2 from keras.models import Model, load_model
----> 3 from keras.optimizers import Adadelta
      4 from keras.callbacks import CSVLogger, ModelCheckpoint
      5 from ..layers import Highway, Similarity, C2QAttention, Q2CAttention, MergedContext, SpanBegin, SpanEnd, CombineOutputs

ImportError: cannot import name **'Adadelta' from 'keras.optimizers' (C:\Users\vishd\AppData\Roaming\Python\Python38\site-packages\keras\optimizers.py)**

****
I have been trying to recreate the Keras-bidaf model in my python notebook and running this code in python **from bidaf.models import BidirectionalAttentionFlow** which keeps giving me the above error and saying Adadelta can't be imported from Keras. I have tried so many options to solve it but no luck. 

I am stuck here. Any suggestions and ideas are highly appreciated.

**Comment by tilakrayal** [comment]
@ReetuData ,
Can you please try to execute as mentioned in the [gist](https://colab.research.google.com/gist/tilakrayal/593a1ecbf14b9a17bc12a8512a727c57/untitled77.ipynb).It helps. Thanks!

**Comment by ReetuData** [comment]
> @ReetuData ,
> Can you please try to execute as mentioned in the [gist](https://colab.research.google.com/gist/tilakrayal/593a1ecbf14b9a17bc12a8512a727c57/untitled77.ipynb).It helps. Thanks!



> @ReetuData ,
> Can you please try to execute as mentioned in the [gist](https://colab.research.google.com/gist/tilakrayal/593a1ecbf14b9a17bc12a8512a727c57/untitled77.ipynb). It helps. Thanks!

**Comment by ReetuData** [comment]
@tilakrayal, 

Hi, Thanks for the quick reply. I have tried the code mentioned in the gist. But still getting the same issue. 

**import tensorflow as tf**
**from tensorflow import keras**
**from tensorflow.keras.optimizers import Adadelta**

**ImportError: cannot import name 'Adadelta' from 'keras.optimizers' (C:\Users\vishd\AppData\Roaming\Python\Python38\site-packages\keras\optimizers.py)**

Any other idea how can we solve it?

**Comment by tilakrayal** [comment]
@ReetuData ,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset  and tensorflow version you are using. Thanks!

**Comment by tilakrayal** [comment]
Also please take a look at this [link](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adadelta) for Adadelta.It helps.Thanks!

**Comment by ReetuData** [comment]
@tilakrayal  

Thanks for your answer again. I have tried another solution as well. No luck again. I am sending you the google collab notebook where I have run the code. I have tried both python and google collab to run this code

**https://colab.research.google.com/drive/10r52gvoSdwzWH9tIFosPwjQ37poY6oLy#scrollTo=f5b95a09**

I am just trying to recreate the code provided by the below model of Parikh. 

**https://github.com/ParikhKadam/bidaf-keras**

I want to train this model for hindi/tamil datasets of the question-answering model. 

Please take a look if you can find some solution.

**Comment by tilakrayal** [comment]
@ReetuData ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by ReetuData** [comment]
> @ReetuData ,
> Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
> To know more refer to:
> https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by tilakrayal** [comment]
@ReetuData ,
Please free feel to close this issue as it has been tracked in Keras repo.Thanks
