### ISSUE TITLE
Bug report: Commit 20c02ff broke something concerning building example /label_image for Raspberry Pi

### ISSUE THREAD

**Issue by drag0** [tensorflow/tensorflow#5202]
This is the diff in question:
https://github.com/tensorflow/tensorflow/commit/20c02ffe0e6b8af4902487f852e15daa16caa523#diff-48887acc98c15e53f942842ecd65190fR318

I managed to successfully build this example by changing code. Since I'm not really good with C++ I'm not sure if my solution is the best. It would be great if someone more experienced could take a look at it.

Here is the issue where I explain how I fixed it: https://github.com/tensorflow/tensorflow/issues/5200

**Comment by drpngx** [comment]
See #5200, PR coming.
