### ISSUE TITLE
Protobuf version conflict between tensorflow and grpc

### ISSUE THREAD

**Issue by Z-yq** [tensorflow/tensorflow#52022]
**System information**
- Linux Ubuntu 20.04
- TensorFlow installed from source
- TensorFlow version: C 2.5.1
- Python version: 3.8.0
- Bazel version: 3.7.2
- GCC/Compiler version: 9.3.0

**Describe the problem**

I want to use C-GRPC to encapsulate the Tensorflow model（TensorflowC） as a service, compiling is OK. But errors will occur when running server：

> [libprotobuf FATAL /mnt/d/CODE/grpc/third_party/protobuf/src/google/protobuf/stubs/common.cc:87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
> terminate called after throwing an instance of 'google::protobuf::FatalException'
>   what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
> Aborted (core dumped)

**Any other info / logs**

So I want to know if I can specify a version of protobuf when compiling tensorflow C lib with bazel myself.

If so, which profile should be modified and how?

Thank you for your guidance and help ：)

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ,Could you please look at this issue ?

**Comment by Z-yq** [comment]
The answer is YES
