### ISSUE TITLE
Nested tensor as a feature incompatible with tf.data.Dataset.from_tensor_slices

### ISSUE THREAD

**Issue by deshiyan1010** [tensorflow/tensorflow#52024]
I'm trying to create a Dataset object with the following record structure(list):
```
['YoVfDbnISlW0f7abNQACIg', 'RA4V8pr014UyUbDvI-LW2A', 0.0499525, 0.6, 'Framingham', 7, 
['Department Stores', 'Optometrists', 'Home & Garden', 'Discount Store', 'Fashion', 'Furniture Stores', 
'Grocery', 'Food', 'Shopping', 'Drugstores', 'Electronics', 'Health & Medical', '<PAD>', '<PAD>', 
'<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', 
'<PAD>', '<PAD>', '<PAD>', '<PAD>']]
```
```
ValueError: Can't convert Python sequence with mixed types to Tensor.
```
I converted to NumPy and I got the following error:
```
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).
```
Without having the category list, the Dataset object is created.

**Comment by sushreebarsa** [comment]
@deshiyan1010 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), Please provide the standalone code to reproduce the issue reported here.
Thanks!
