### ISSUE TITLE
Error in lowering tf.ResizeBilinear and tf.ResizeNearestNeighbor using tf-mlir-translate and tf-opt 

### ISSUE THREAD

**Issue by ArunaKote** [tensorflow/tensorflow#52023]
Model for tf.ResizeNearestNeighbor looks like:
model = tf.keras.Sequential([
tf.keras.layers.Conv2D(4, (1, 1),input_shape = (10, 10, 3),batch_size=1, name='fpn_c5p5'),
tf.keras.layers.UpSampling2D(size=(2, 2),interpolation='nearest', name="fpn_p5upsampled")
])

Model for tf.ResizeBilinear looks like:
model = tf.keras.Sequential([
tf.keras.layers.Conv2D(4, (1, 1),input_shape = (10, 10, 3),batch_size=1, name='fpn_c5p5'),
tf.keras.layers.UpSampling2D(size=(2, 2),interpolation='nearest', name="fpn_p5upsampled")
])
Error in lowering tf.ResizeBilinear and tf.ResizeNearestNeighbor to HLO.

I have attached log file and python code to get saved_model.pb
[codeandlog.zip](https://github.com/tensorflow/tensorflow/files/7174773/codeandlog.zip)

1.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --savedmodel-objectgraph-to-mlir --tf-savedmodel-exported-names=predict  -tf-enable-shape-inference-on-import=true $PWD -o sample.mlir
2.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt -canonicalize --tf-executor-to-functional-conversion --tf-shape-inference -xla-legalize-tf  --print-ir-before-all &>1  sample.mlir

If tf.ResizeNearestNeighbor if it has argument half_pixel_centers = false I able to lower to MHLO. But in the above case half_pixel_centers = true. and i am not able to lower to HLO.

**Comment by tilakrayal** [comment]
@ArunaKote ,
Can you please let us know the tensorflow version you are using to test the code.Thanks!

**Comment by ArunaKote** [comment]
@tilakrayal ,
1.tensorflow version 2.7.0-dev20210831

2.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt --version
LLVM (http://llvm.org/):
  LLVM version 14.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake
3.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --version
LLVM (http://llvm.org/):
  LLVM version 14.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake

**Comment by sanatmpa1** [comment]
@ArunaKote,

As you have already added `tf.ResizeBilinear` and `tf.ResizeNearestNeighbor` in the issue #52030. Can you confirm if we can close this issue as duplicate and track everything at one place in #52030 ? Thanks!

**Comment by ArunaKote** [comment]
OK .Thanks
