### ISSUE TITLE
Tensor board wont load log files 

### ISSUE THREAD

**Issue by vulkomilev** [tensorflow/tensorflow#52038]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.1
- Python version:3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuDNN v 8100
- GPU model and memory: 3080 10gb 
I am trying to explore the log files generated by 
tf.debugging.experimental.enable_dump_debug_info(
    "/tmp/tfdbg2_logdir",
    tensor_debug_mode="FULL_HEALTH",
    circular_buffer_size=-1)
but after loading the tensorboard 2.6 with the following command 
tensorboard --logdir /tmp/tfdbg2_logdir/ --load_fast=false

I get a message that there is no data to be loaded 
I have checked and there are log files in this dir

**Comment by tilakrayal** [comment]
@vulkomilev ,
This issue is more suitable for TensorBoard repo. Please post it on [tensorflow/tensorboard](https://github.com/tensorflow/tensorboard/issues) repo from here. Thanks!
