### ISSUE TITLE
Code completion of Keras Moudle no longer work since 2.6 (removed keras)

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#52031]
Code completion of Keras Module no longer work in VSCode after Keras code is remvoed from TensorFlow 2.6

**Comment by sushreebarsa** [comment]
@edwardyehuang 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here and provide some more details on this issue. Thanks!
