### ISSUE TITLE
tf.audio.decode_wav mmap like scipy.io.wavfile.read

### ISSUE THREAD

**Issue by bjarthur** [tensorflow/tensorflow#52037]
would be much faster in my use case to read in just a portion of a WAV file.  scipy has a nice memory map keyword argument which permits this:  `scipy.io.wavfile.read(path_to_wavfile, mmap=True)`.  sadly `tf.audio.decode_wav` does not.  thanks!

**Comment by mohantym** [comment]
Hi @bjarthur 
Could you please fill the feature template from [here ](https://github.com/tensorflow/tensorflow/issues/new/choose), It will help us expedite the issue. Thanks!

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you look at this feature request?

**Comment by bjarthur** [comment]
**System information**
- TensorFlow version (you are using):  2.5 currently, will upgrade to 2.6 soon
- Are you willing to contribute it (Yes/No): no



**Describe the feature and the current behavior/state.**. add a means to (lazily?) load a small portion of a WAV file, perhaps with a memory map keyword argument, or alternatively by passing in an offset and length.

**Will this change the current api? How?**. will add to the API in a backwards compatible way

**Who will benefit with this feature?**. those with large WAV files that only train on a portion of them

**Any Other info.**

**Comment by Saduf2019** [comment]
@bjarthur 
Please feel free to submit a pr for the change requested or share the link where the change is to be made.
