### ISSUE TITLE
Trying to follow simple Tutorial For LOADING TEXT but tensorflow_text won't import 

### ISSUE THREAD

**Issue by bestmatthew** [tensorflow/tensorflow#52036]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary? Not sure, just following https://www.tensorflow.org/tutorials/load_data/text
- TensorFlow version: 
tensorflow                    2.6.0
tensorflow-estimator          2.6.0
tensorflow-hub                0.12.0
tensorflow-io-gcs-filesystem  0.21.0
tensorflow-text               2.6.0
tensorflow-text-nightly       2.7.0.dev20210916
- Python version: Python 3.7.7
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

First steps of loading text. "Be sure you're using stable versions of tf and tf-text"   Followed instructions to uninstall and re install tf-nightly / tensorflow-text-nightly.

First issue was package conflict/dependency issues  about wanting "flat buffers 2.0" but I currently had flat buffers 1.12; after updating to flat buffers2.0 I get another package conflict that a separate tevnsofrlow package wants flat buffers 1.12 but I now have flatbuffers 1.12 which is, you guessed it, incompatible. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
From the tutorial:
'''
import collections
import pathlib
import re
import string

import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras import preprocessing
from tensorflow.keras import utils
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

import tensorflow_datasets as tfds
import tensorflow_text as tf_text
'''

warning:2021-09-16 13:16:16.308765: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/dropout/temp_rate_is_zero

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
AlreadyExistsError                        Traceback (most recent call last)
/var/folders/wg/tzq4qwy97x3_999pctn35jlh0000gn/T/ipykernel_1983/2446760814.py in <module>
      6 import tensorflow as tf
      7 
----> 8 from tensorflow.keras import layers
      9 from tensorflow.keras import losses
     10 from tensorflow.keras import preprocessing

~/opt/anaconda3/lib/python3.7/site-packages/keras/api/_v2/keras/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from keras import __version__
     11 from keras.api._v2.keras import __internal__
     12 from keras.api._v2.keras import activations

~/opt/anaconda3/lib/python3.7/site-packages/keras/__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from keras import models
     26 
     27 from keras.engine.input_layer import Input

~/opt/anaconda3/lib/python3.7/site-packages/keras/models.py in <module>
     18 import tensorflow.compat.v2 as tf
     19 from keras import backend
---> 20 from keras import metrics as metrics_module
     21 from keras import optimizer_v1
     22 from keras.engine import functional

~/opt/anaconda3/lib/python3.7/site-packages/keras/metrics.py in <module>
     24 
     25 import numpy as np
---> 26 from keras import activations
     27 from keras import backend
     28 from keras.engine import base_layer

~/opt/anaconda3/lib/python3.7/site-packages/keras/activations.py in <module>
     18 
     19 from keras import backend
---> 20 from keras.layers import advanced_activations
     21 from keras.utils.generic_utils import deserialize_keras_object
     22 from keras.utils.generic_utils import serialize_keras_object

~/opt/anaconda3/lib/python3.7/site-packages/keras/layers/__init__.py in <module>
     29 
     30 # Image preprocessing layers.
---> 31 from keras.layers.preprocessing.image_preprocessing import CenterCrop
     32 from keras.layers.preprocessing.image_preprocessing import RandomCrop
     33 from keras.layers.preprocessing.image_preprocessing import RandomFlip

~/opt/anaconda3/lib/python3.7/site-packages/keras/layers/preprocessing/image_preprocessing.py in <module>
     22 from keras.engine import base_layer
     23 from keras.engine import base_preprocessing_layer
---> 24 from keras.preprocessing import image as image_preprocessing
     25 from keras.utils import control_flow_util
     26 from tensorflow.python.ops import stateless_random_ops

~/opt/anaconda3/lib/python3.7/site-packages/keras/preprocessing/__init__.py in <module>
     24 from keras.preprocessing import text
     25 from keras.preprocessing import timeseries
---> 26 from keras.utils import all_utils as utils
     27 
     28 # This exists for compatibility with prior version of keras_preprocessing.

~/opt/anaconda3/lib/python3.7/site-packages/keras/utils/all_utils.py in <module>
     32 from keras.utils.generic_utils import serialize_keras_object
     33 from keras.utils.layer_utils import get_source_inputs
---> 34 from keras.utils.multi_gpu_utils import multi_gpu_model
     35 from keras.utils.np_utils import normalize
     36 from keras.utils.np_utils import to_categorical

~/opt/anaconda3/lib/python3.7/site-packages/keras/utils/multi_gpu_utils.py in <module>
     18 from keras import backend
     19 from keras.engine.training import Model
---> 20 from keras.layers.core import Lambda
     21 from keras.layers.merge import concatenate
     22 

~/opt/anaconda3/lib/python3.7/site-packages/keras/layers/core/__init__.py in <module>
     18 from keras.layers.core.activity_regularization import ActivityRegularization
     19 from keras.layers.core.dense import Dense
---> 20 from keras.layers.core.dropout import Dropout
     21 from keras.layers.core.flatten import Flatten
     22 from keras.layers.core.lambda_layer import Lambda

~/opt/anaconda3/lib/python3.7/site-packages/keras/layers/core/dropout.py in <module>
     26 keras_temporary_dropout_rate = tf.__internal__.monitoring.BoolGauge(
     27     '/tensorflow/api/keras/dropout/temp_rate_is_zero',
---> 28     'Temporarily record if Keras dropout layer was created w/'
     29     'constant rate = 0')
     30 

~/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py in __init__(self, name, description, *labels)
    359     """
    360     super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
--> 361                                     len(labels), name, description, *labels)
    362 
    363   def get_cell(self, *labels):

~/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py in __init__(self, metric_name, metric_methods, label_length, *args)
    133           self._metric_name, len(self._metric_methods)))
    134 
--> 135     self._metric = self._metric_methods[self._label_length].create(*args)
    136 
    137   def __del__(self):

AlreadyExistsError: Another metric with the same name already exists.

**Comment by Saduf2019** [comment]
@bestmatthew 
You may refer to similar solved issues: [link](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam),[link1](https://discuss.tensorflow.org/t/alreadyexistserror-another-metric-with-the-same-name-already-exists/3787),[link2](https://github.com/tensorflow/tensorflow/issues/32574)

**Comment by Saduf2019** [comment]
@bestmatthew 
The code provided seems incomplete please share a colab gist of possible with the error reported.

**Comment by bestmatthew** [comment]
Hi @Saduf2019, unfortunately  the code is complete and  provided above. 

It is VERBATIM copied from the tensorflow tutorial for loading text. (https://www.tensorflow.org/tutorials/load_data/text)

The block of code, again:
'''
# Be sure you're using the stable versions of both tf and tf-text, for binary compatibility.
pip uninstall -y tensorflow tf-nightly keras

pip install -q -U tf-nightly
pip install -q -U tensorflow-text-nightly
'''

'''
import collections
import pathlib
import re
import string

import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras import preprocessing
from tensorflow.keras import utils
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

import tensorflow_datasets as tfds
import tensorflow_text as tf_text
'''

**Comment by Saduf2019** [comment]
@bestmatthew 
I ran the code shared and do not face any issues as reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/171b9d50384674d134162546e2d1c71d/untitled641.ipynb)

**Comment by nershman** [comment]
@bestmatthew Did you make any progress on this issue? I'm having an issue related to flatbuffer dependency when installing tf-text as well.

**Comment by bestmatthew** [comment]
@nershman thank you for understanding tensorflow better than the tf staff. 

I was not able to resolve the issue, TF refuses to import so I ran my work in google colabs out of necessity. I have not been able to get TF running in my native ide but will troubleshoot this a little further with my package versions. I am moving to a new machine shortly and I imagine (hope) the new environment will also not have this issue. Thanks for the suggestion, will report back later this week if I can get it running a more current python iteration, I was using python 3.7.7 for school but have no reason to stick with it anymore. Thanks.

**Comment by nershman** [comment]
@bestmatthew I'm also having issues with imports but I'm on on a earlier version of macOS. If it mentions a "symbol not found" or a missing dylib it may be an issue with how TF was built. There seems to be a few issues related to this which are in the process of being resolved. If you have more issues another option is to try building TF yourself (there's an option for that in pip, but you need to have XCode installed). Good luck and I hope you can get it working!
