### ISSUE TITLE
bug while summing ragged  tensors

### ISSUE THREAD

**Issue by aiace9** [tensorflow/tensorflow#52035]
**System information**
Not needed, check colab example below 

**Current behavior**
When summing 2 ragged tensor of (apparently) the same shape the following error is rised:
`InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'Unable to broadcast: dimension size mismatch in dimension' 
`

**Describe the expected behavior**
Well, the sum to proceed correctly

**Standalone code to reproduce the issue**
colab: https://colab.research.google.com/drive/1U7IVgd7T2Y4LrUXCsgBmlHU0VWBX6Ka4?usp=sharing

**Comment by tilakrayal** [comment]
@aiace9 ,
Please take a look at this SO [link](https://stackoverflow.com/questions/61947237/broadcasting-with-ragged-tensor) with similar error.It helps.Thanks!
