### ISSUE TITLE
Error in lowering tf ops to HLO using tf-opt

### ISSUE THREAD

**Issue by ArunaKote** [tensorflow/tensorflow#52030]
I am trying to lower following tf ops to HLO using :tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt  -xla-legalize-tf  sample.mlir
    tf.CropAndResize 
    tf.StridedSlice 
    tf.Unique
    tf.Where 
    tf.SparseToDense 
    tf.NonMaxSuppressionV4 
    tf.TensorListFromTensor 
    tf.TensorListGetItem 
    tf.TensorListReserve       
    tf.TensorListSetItem 
    tf.TensorListStack 
    tf.TopKV2
    tf.ResizeBilinear
    tf.ResizeNearestNeighbor
I am getting error as 
The following operations cannot be legalized. These legalization failure(s) may be due to missing TF to HLO lowerings and/or unsupported attributes, etc.
I am trying to lower these ops with dynamic input shape.
I have attached tf dialect mlir files for each failed ops.
[mlir_files.zip](https://github.com/tensorflow/tensorflow/files/7177750/mlir_files.zip)

Thanks

**Comment by ArunaKote** [comment]
@tilakrayal ,
Environment details:
1.tensorflow version 2.7.0-dev20210831

2.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt --version
LLVM (http://llvm.org/):
LLVM version 14.0.0git
Optimized build.
Default target: x86_64-unknown-linux-gnu
Host CPU: cascadelake
3.tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --version
LLVM (http://llvm.org/):
LLVM version 14.0.0git
Optimized build.
Default target: x86_64-unknown-linux-gnu
Host CPU: cascadelak

**Comment by sanatmpa1** [comment]
@ArunaKote,

As you're using `2.7.0-dev20210831` which is the nightly-version and not a stable release, Can you clarify if the same issue exists even in `2.6.0`?

**Comment by ArunaKote** [comment]
@sanatmpa1 ,yes in tf 2.6.0 also same issue exists.

**Comment by jpienaar** [comment]
Legalize is only for the 2nd phase, you need to run first phase of the bridge too to convert TensorList ones. Assigning to bridge team to triage.

**Comment by ArunaKote** [comment]
Thank you.For the static inputs,TensorList ops are decomposed using tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-opt  -tf-tensor-list-ops-decomposition tf.mlir then I able to convert it to HLO. But for dynamic inputs its not decomposing  and that's why I am not able to lower these ops to HLO. Actually I wanted lower above tf-ops to HLO with dynamic shape. These ops are failing in MRCNN network.

**Comment by ArunaKote** [comment]
@smit-hinsu,lowering tf.ResizeBilinear is not available with  -xla-legalize-tf .  Sir, for ResizeBilinear op lowering the below flow can be used? or is there any other optimized flow which can be used for lowering.
For input_image=hxw and output_image=h1xw1
tx=w/w1
ty=h/h1
for (i=0;i<h1;i++){
for(j=0;j<w1;j++){
x=int(tx*j)
y=int(ty*i)
x_diff=((tx*j)-x)
y_diff=((ty*i)-y)
output_image[i][j]=input_image[y][x]*(1-x_diff))*(1-y_diff)+
                                input_image[y][x+1]*(x_diff))*(1-y_diff)+
		        input_image[y+1][x]*(1-x_diff))*(y_diff)+
		        input_image[y+1][x+1]*(x_diff))*(y_diff)

}}

Thanks

**Comment by sun2011yao** [comment]
@ArunaKote HI, Did you solve this problem？I also met the tf.ResizeBilinear operation cannot be legalized.

**Comment by smit-hinsu** [comment]
@ArunaKote Dynamic inputs are not yet supported for many ops like ResizeBilinear. We could discuss if you would like to contribute a change to support dynamic inputs.

**Comment by blacklong28** [comment]
Is there any update regarding support for dynamic input ?

**Comment by bhack** [comment]
We had a similar error in Keras CV enabling the MLIR bridge for https://github.com/keras-team/keras-cv/issues/895:
 `tf.TensorListReserve' op unknown tensor list element shape`

`note: see current operation: %38 = "tf.TensorListReserve"(%26, %25) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf_type.variant<tensor<*xi32>>>`

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
