### ISSUE TITLE
Jupyter notebook can't launch the program correctly, but  anaconda prompt can.

### ISSUE THREAD

**Issue by Beliefuture** [tensorflow/tensorflow#52043]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow version: 2.3.0
- Python version: 3.7.11
- Installed using virtualenv? pip? conda?: conda
- CUDA/cuDNN version: 10.1

**Describe the problem**

With Anaconda, I create a virtual environment to install the cpu version of tensorflow. The System information is shown above. I install tensorflow using the command ``conda install tensorflow`` that deals with dependency automatically.

It appears to be normal when I run some basic example in **"anaconda prompt"**.

But when I try to run these in **"Jupyter Notebook"**. The kernel can't restart and turns to be dead finally.

Then I downgrade the version of **"numpy"**. It raises the problem about **"numpy import error"**:

![image](https://user-images.githubusercontent.com/62245023/133754574-ffbd33bc-1dda-4c65-b1ae-6f31e0e2d924.png)

**Comment by tilakrayal** [comment]
@Beliefuture ,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.Also please try to downgrade the numpy version and try installing latest stable tensorflow v2.6 from [here](https://www.tensorflow.org/install).It helps.Thanks!

**Comment by Beliefuture** [comment]
> @Beliefuture ,
> Installation issues within the Anaconda environment are tracked in the Anaconda repo.Also please try to downgrade the numpy version and try installing latest stable tensorflow v2.6 from [here](https://www.tensorflow.org/install).It helps.Thanks!

Thanks for your reply. It seems to be the version of numpy, pyzmq, h5py. I previously think that "conda" will manage the version dependency well. But it is apparently not.
