### ISSUE TITLE
tensorflow runs much slower/ installation issue?

### ISSUE THREAD

**Issue by amrit-poudel** [tensorflow/tensorflow#5205]
I installed tensorflow version 0.11.0rc0 using the .whl provided and the following code runs terribly slower (on macosx cpu) compared to its numpy counterpart.

Is  tf version  0.11.0rc0 a stable release?  Is tensorflow expected to run extremely slow inside a python for loop?
````
from math import *
import numpy as np
import sys
from multiprocessing import Pool
import tensorflow as tf

def Trajectory_Fun(tspan, a, b, session=None, server=None):
    if session==None:
        if server==None:
            sess = tf.Session()
        else:
            sess = tf.Session(server.target)       
    else:
        sess = session
    B = np.zeros(np.size(tspan), dtype=np.float64)
    B[0] = b
    for i, t in enumerate(tspan):
        r = np.random.rand(1)
        if r>a:
            c = sess.run(tf.trace(tf.random_normal((4, 4), r, 1.0)))
        else:
            c = 0.0 # sess.run(tf.trace(tf.random_normal((4, 4), 0.0, 1.0)))
        B[i] = c
    if session==None:
        sess.close()
    return B


def main(argv):
   tspan = np.arange(0.0, 1000.0)
   a = 0.1
   b = 0.0
   B = Trajectory_Fun(tspan, a, b, None, None)
   print 'Done!'


if __name__ == "main":
    main(sys.argv[1:]) `

**Comment by drpngx** [comment]
Could you cross-post on stackoverflow with tag "tensorflow"?

@aselle about numpy comparison.

**Comment by amrit-poudel** [comment]
@drpngx, I already posted on stackoverflow as well. Technically, this is not quite a numpy comparison. It is more about running tensorflow inside a python for loop. I must be missing something here.

**Comment by drpngx** [comment]
Of a total elapsed time of 54s.

|   ncalls |  tottime | percall | cumtime | percall | `filename:lineno(function)`|
|---------:|---------:|---------|---------|---------|----------|
|       904 |  35.775 |   0.040 |  35.775 |   0.040 | `{_pywrap_tensorflow.TF_ExtendGraph}` |
|       904 |   6.605 |   0.007 |   6.605 |   0.007 | `{_pywrap_tensorflow.TF_Run}` |
| 378938/246954 |   1.420 |   0.000 |   3.013 |   0.000 | `python_message.py:481(init)` |
|       904 |   0.585 |   0.001 |   2.634 |   0.003 | `ops.py:2191(_as_graph_def)` |
| 239560/128368 |   0.507 |   0.000 |   1.808 |   0.000 | `python_message.py:1229(MergeFrom)` |

[profile.txt](https://github.com/tensorflow/tensorflow/files/551851/profile.txt)

**Comment by amrit-poudel** [comment]
Thanks.  Now, if you replace  

c = sess.run(tf.trace(tf.random_normal((4, 4), r, 1.0)))

with

c = np.sum(np.diag(np.random.normal(0.0, 1.0, (4, 4))))


in for loop of Trajectory_Fun

The entire program runs in about  1 second.

**Comment by drpngx** [comment]
@annarev @mrry for potential additional insights.

**Comment by mrry** [comment]
As far as TensorFlow programs go, this is a pessimal case. The underlying assumption in TensorFlow is (approximately) that you'll build a graph once and then call `sess.run()` on (various parts of) it multiple times. The tax of calling `TF_ExtendGraph` is paid once on the first use, and subsequent uses are much cheaper. If you must use a loop *within* your TensorFlow graph, there are constructs like `tf.while_loop()` (and, similarly, `tf.cond()` for if-statements) that you can use.

You can make this program much faster by constructing the graph once and using (e.g.) a placeholder to feed in the value that changes in each iteration. For example, the following should do the trick:

```python
def Trajectory_Fun(tspan, a, b, session=None, server=None):
    if session==None:
        if server==None:
            sess = tf.Session()
        else:
            sess = tf.Session(server.target)       
    else:
        sess = session
    B = np.zeros(np.size(tspan), dtype=np.float64)
    B[0] = b

    # Define the TensorFlow graph once and reuse it in each iteration of the for loop.
    r_placeholder = tf.placeholder(tf.float32, shape=[])
    out_t = tf.trace(tf.random_normal((4, 4), r_placeholder, 1.0))

    for i, t in enumerate(tspan):
        r = np.random.rand(1)
        if r>a:
            c = sess.run(out_t, feed_dict={r_placeholder: r})
        else:
            c = 0.0
        B[i] = c
    if session==None:
        sess.close()
    return B
```

You could potentially make this even more efficient by using a TF loop and making fewer calls to `sess.run()`, but the principle is the same.

**Comment by amrit-poudel** [comment]
Many thanks for clarifying. It certainly cleared up some of my confusions.
