### ISSUE TITLE
TF probability cannot broadcast last batch dimension if event_shape is not a scalar

### ISSUE THREAD

**Issue by LukeBolly** [tensorflow/tensorflow#52054]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: GTX 1060M

**Describe the current behavior**
log_prob fails to broadcast to batch dims if event_shape is not a scalar, even if event_shape matches. I'm pretty sure this should be a trivial broadcast, but maybe I'm wrong here.
NotImplementedError: Broadcasting is not supported; unexpected batch and event shape (expected [2 3 2], saw [2 1 2]).

**Describe the expected behavior**
In the example here: https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes#computing_log_prob_for_scalar_distributions
At the section describing "get the log probability of each value at each point in the batch", an example is shown of broadcasting a tensor shaped [2, 2, 1] into a distribution with batch_shape [2, 3] and event_shape of (). The broadcasted shape is then [2, 2, 3].

Attempting to do the same where the shape instead is [2, 2, 1, 2] into a distribution with batch_shape [2, 3] and event_shape of [2]. The expected broadcast shape would simply be [2, 2, 3, 2], where the last batch_dim would be broadcast just like in the example.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
from tensorflow_probability import distributions as tfd


if __name__ == '__main__':
    x = tf.constant([[[0.5, 0.75], [0.1, 0.25], [0.35, 0.9]], [[0.4, 0.45], [0.5, 0.7], [0.8, 0.25]]], tf.float32)
    p_x = tfd.Independent(tfd.Normal(x, 1), 1)

    x_dist = tfd.BatchReshape(distribution=p_x, batch_shape=[2, 3], validate_args=True)

    # compare each point against every other point
    transposed_elems = tf.expand_dims(tf.transpose(x, perm=(1, 0, 2)), axis=-2)
    pointwise_log_prob = x_dist.log_prob(transposed_elems)
    pass
```

**Comment by LukeBolly** [comment]
I just noticed the error is actually on broadcasting on a BatchReshape layer. Is there a workaround for this until it is implemented?

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look into this issue?

**Comment by sanatmpa1** [comment]
I am able to reproduce the error and here's the [gist](https://colab.research.google.com/gist/sanatmpa1/7dd035860a40bdaf41c4c3f5bd177261/52054.ipynb). Found a similar [issue](https://github.com/tensorflow/probability/issues/1206) in tf-probability repo.

**Comment by sanatmpa1** [comment]
@LukeBolly,

As this issue if related to `BatchReshape` in `tensorflow_probability`, Can you open an issue in this [repo](https://github.com/tensorflow/probability) for proper assistance? Thanks!
