### ISSUE TITLE
Issue with tensorflow lite interpreter 

### ISSUE THREAD

**Issue by vanajareedy0426** [tensorflow/tensorflow#52058]
`import tensorflow as tf
import tensorflow_datasets as tfds
(ds_train, ds_test), ds_info = tfds.load( 'mnist',
split=['train', 'test'],
shuffle_files=True,
as_supervised=True,
with_info=True,
)
def normalize_img(image, label):
return tf.cast(image, tf.float32) / 255., label

ds_train = ds_train.map(normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.experimental.AUTOTUNE)
ds_test = ds_test.map(normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)

ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.experimental.AUTOTUNE)

#model
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape=(28, 28)),
tf.keras.layers.Reshape((1,784)),
tf.keras.layers.Conv1D( 16, 1,use_bias=False,activation = 'relu' ),
tf.keras.layers.Conv1D(16, 1,use_bias=False ,activation = 'relu' ),
tf.keras.layers.Conv1D( 16, kernel_size=3, strides=1, padding= "causal", dilation_rate=2**0, groups=16,use_bias=False,activation ='relu'),
tf.keras.layers.Conv1D( 16, 1 ,use_bias=False) ,
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(10)
])
model.compile(
optimizer=tf.keras.optimizers.Adam(0.001),
loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
metrics=[tf.keras.metrics.SparseCategoricalAccuracy()],
)

model.fit(
ds_train,
epochs=1,
validation_data=ds_test,
)
model.summary()
model.save("./model.h5")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
f.write(tflite_model)
`

This the code of my model , after executing this code I'm getting .tflite model . 
But when I'm trying to interpret the tflite model I'm getting the error. 
`interpreter = tf.lite.Interpreter(model_path="./assignment.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
`
This is the tflite inference code I'm using 

2021-09-18 20:55:19.573161: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
  File "C:\Users\itmee\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\itmee\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\itmee\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\itmee\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\itmee\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\itmee\anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\itmee\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\itmee\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\MVNS\assignment\tf_Asg-1.py", line 17, in <module>
    interpreter.invoke()
  File "C:\Users\itmee\anaconda3\lib\site-packages\tensorflow\lite\python\interpreter.py", line 833, in invoke
    self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/conv.cc:349 input->dims->data[3] != filter->dims->data[3] (16 != 1)Node number 13 (CONV_2D) failed to prepare.
 Error traceback details are as mentioned above.

**Comment by mohantym** [comment]
Hi @vanajareedy0426 ,
Could you please fill the issue template,  as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by vanajareedy0426** [comment]
> Hi @vanajareedy0426 ,
> Could you please fill the issue template, as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

Tensorflow version is 2.5.0 
entire code is given above. Once I got the mode. h5 , then I'm converting it into tflite . 

tflite conversion is successful . And I'm trying to use that .tflite model and get output (inference) 
`interpreter = tf.lite.Interpreter(model_path="./assignment.tflite") 
interpreter.allocate_tensors()
 input_details = interpreter.get_input_details() 
output_details = interpreter.get_output_details() 
input_shape = input_details[0]['shape'] 
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32) 
interpreter.set_tensor(input_details[0]['index'], input_data)
 interpreter.invoke()
 output_data = interpreter.get_tensor(output_details[0]['index'])`

This is the code I'm using for interpreting .


2021-09-18 20:55:19.573161: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
File "C:\Users\itmee\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\itmee\anaconda3\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "c:\Users\itmee.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy_main.py", line 45, in
cli.main()
File "c:\Users\itmee.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
run()
File "c:\Users\itmee.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
runpy.run_path(target_as_str, run_name=compat.force_str("main"))
File "C:\Users\itmee\anaconda3\lib\runpy.py", line 265, in run_path
return _run_module_code(code, init_globals, run_name,
File "C:\Users\itmee\anaconda3\lib\runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "C:\Users\itmee\anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "d:\MVNS\assignment\tf_Asg-1.py", line 17, in
interpreter.invoke()
File "C:\Users\itmee\anaconda3\lib\site-packages\tensorflow\lite\python\interpreter.py", line 833, in invoke
self._interpreter.Invoke()
RuntimeError: tensorflow/lite/kernels/conv.cc:349 input->dims->data[3] != filter->dims->data[3] (16 != 1)Node number 13 (CONV_2D) failed to prepare.
Error traceback details are as mentioned above.

**Comment by mohantym** [comment]
@vanajareedy0426 , I was different error in model.fit() operation , attaching [gist](https://colab.research.google.com/gist/mohantym/55b7ee284c7c0d25accb49880a05657c/github_52058.ipynb) for reference. The error stack trace was similar to this [issue ](https://github.com/tensorflow/tensorflow/issues/50397). Could you provide a colab gist with above Error stack trace?

**Comment by mohantym** [comment]
But the above Colab link is restricted and asking permission , Could you please share the same as a Colab Gist.

**Comment by vanajareedy0426** [comment]
> Could you please share the same as a Colab Gist?

[gist](https://colab.research.google.com/gist/vanajareedy0426/263f985bd45e8579891507896a0093d4/issue_github.ipynb)

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look at this issue , This issue's Error stack trace is similar this one  and replicating in TF [2.4](https://colab.research.google.com/gist/mohantym/11fed15ea42a02ec58b0d15b6755285d/issue_github.ipynb#scrollTo=rT_RErtZMVo8),[2.5](https://colab.research.google.com/gist/mohantym/aba97023fafc2986c822e34b4985f608/issue_github.ipynb#scrollTo=rT_RErtZMVo8),[2.6](https://colab.research.google.com/gist/mohantym/99a8bd75c5fbc873045f41398f91377b/issue_github.ipynb#scrollTo=4VeNDoFX2MH9) and [2.7.0dev](https://colab.research.google.com/gist/mohantym/f40447c6e638b03d72782314cae40989/issue_github.ipynb#scrollTo=8mFYoV3x2mc7)(nightly) . The real cause  might be in  model.fit() operation.

**Comment by sanatmpa1** [comment]
@vanajareedy0426,

As per the [gist](https://colab.research.google.com/gist/vanajareedy0426/263f985bd45e8579891507896a0093d4/issue_github.ipynb) that you provided, you have commented out the model.fit() and have you trained the model properly and saved it before converting it to lite?

As pointed out by @mohantym [here](https://github.com/tensorflow/tensorflow/issues/52058#issuecomment-922665116), we got the below error while training your model, `InvalidArgumentError:  filter_size does not have enough elements, requested 768, got 48`. On checking, it is mostly related to  value provided for `group` argument in the `3rd Conv1D layer` in your architecture.

I removed the `group` argument from that layer and now the code is running fine without any errors. please take a look at this [gist](https://colab.research.google.com/gist/sanatmpa1/6c7d4be50ed3dbc345e3a084dc844050/52058.ipynb)

**Comment by vanajareedy0426** [comment]
> I removed the `group` argument from that layer and now the code is running fine without any errors. Please take a look at this [gist](https://colab.research.google.com/gist/sanatmpa1/6c7d4be50ed3dbc345e3a084dc844050/52058.ipynb)

Thanks for the confirmation, with out groups it is working fine. But  I want to use grouped convolution in this model.

Does tflite converter and interpreter works in case grouped convolutions ? or not ? Can you provide any comments on this

**Comment by sanatmpa1** [comment]
@vanajareedy0426,

You can take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/40044) to know more about grouped convolution support in TFLite
