### ISSUE TITLE
bazel test //tensorflow/tools/docs:tf_doctest fails on aarch64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#52069]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git HEAD
- Python version: 3.8.10
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Test fails

**Describe the expected behavior**

Test passes

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): I think the test needs to be relaxed slightly to accept the values produced by AARCH64 CPUs.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

bazel test //tensorflow/tools/docs:tf_doctest

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

======================================================================
FAIL: Tanh (tensorflow.python.ops.gen_math_ops)
Doctest: tensorflow.python.ops.gen_math_ops.Tanh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for tensorflow.python.ops.gen_math_ops.Tanh
  File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 408, in Tanh

----------------------------------------------------------------------
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 416, in tensorflow.python.ops.gen_math_ops.Tanh
Failed example:
    tf.math.tanh(x)
Expected:
    <tf.Tensor: shape=(8,), dtype=float32, numpy=
    array([-1.        , -0.99990916, -0.46211717,  0.7615942 ,  0.8336547 ,
            0.9640276 ,  0.9950547 ,  1.        ], dtype=float32)>
Got:
    <tf.Tensor: shape=(8,), dtype=float32, numpy=
    array([-0.99999976, -0.99990916, -0.46211717,  0.7615942 ,  0.8336546 ,
            0.9640276 ,  0.9950547 ,  0.99999976], dtype=float32)>

    #############################################################
    Check the documentation
    (https://www.tensorflow.org/community/contribute/docs_ref) on how to write testable docstrings.
    #############################################################

======================================================================
FAIL: tanh (tensorflow.python.ops.gen_math_ops)
Doctest: tensorflow.python.ops.gen_math_ops.tanh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for tensorflow.python.ops.gen_math_ops.tanh
  File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 11336, in tanh

----------------------------------------------------------------------
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 11344, in tensorflow.python.ops.gen_math_ops.tanh
Failed example:
    tf.math.tanh(x)
Expected:
    <tf.Tensor: shape=(8,), dtype=float32, numpy=
    array([-1.        , -0.99990916, -0.46211717,  0.7615942 ,  0.8336547 ,
            0.9640276 ,  0.9950547 ,  1.        ], dtype=float32)>
Got:
    <tf.Tensor: shape=(8,), dtype=float32, numpy=
    array([-0.99999976, -0.99990916, -0.46211717,  0.7615942 ,  0.8336546 ,
            0.9640276 ,  0.9950547 ,  0.99999976], dtype=float32)>

    #############################################################
    Check the documentation
    (https://www.tensorflow.org/community/contribute/docs_ref) on how to write testable docstrings.
    #############################################################

======================================================================
FAIL: sigmoid (tensorflow.python.ops.math_ops)
Doctest: tensorflow.python.ops.math_ops.sigmoid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for tensorflow.python.ops.math_ops.sigmoid
  File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 174, in sigmoid

----------------------------------------------------------------------
File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 187, in tensorflow.python.ops.math_ops.sigmoid
Failed example:
    tf.math.sigmoid(x)
Expected:
    <tf.Tensor: shape=(4,), dtype=float32,
    numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>
Got:
    <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 0.9999998, 0.9999998], dtype=float32)>

**Comment by elfringham** [comment]
@cfRod
@nSircombe

**Comment by soffieswan041** [comment]
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
> * TensorFlow installed from (source or binary): source
> * TensorFlow version (use command below): git HEAD
> * Python version: 3.8.10
> * Bazel version (if compiling from source): 3.7.2
> * GCC/Compiler version (if compiling from source): 10.3.0
> * CUDA/cuDNN version: n/a
> * GPU model and memory: n/a
> 
> You can collect some of this information using our environment capture
> [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with:
> 
> 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
> 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **Describe the current behavior**
> 
> Test fails
> 
> **Describe the expected behavior**
> 
> Test passes
> 
> **[Contributing](https://www.tensorflow.org/community/contribute)**
> 
> * Do you want to contribute a PR? (yes/no): no
> * Briefly describe your candidate solution(if contributing): I think the test needs to be relaxed slightly to accept the values produced by AARCH64 CPUs.
> 
> **Standalone code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate
> the problem. If possible, please share a link to Colab/Jupyter/any notebook.
> 
> bazel test //tensorflow/tools/docs:tf_doctest
> 
> **Other info / logs** Include any logs or source code that would be helpful to
> diagnose the problem. If including tracebacks, please include the full
> traceback. Large logs and files should be attached.
> 
> ## ======================================================================
> FAIL: Tanh (tensorflow.python.ops.gen_math_ops)
> Doctest: tensorflow.python.ops.gen_math_ops.Tanh
> Traceback (most recent call last):
> File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
> raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for tensorflow.python.ops.gen_math_ops.Tanh
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 408, in Tanh
> 
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 416, in tensorflow.python.ops.gen_math_ops.Tanh
> Failed example:
> tf.math.tanh(x)
> Expected:
> <tf.Tensor: shape=(8,), dtype=float32, numpy=
> array([-1. , -0.99990916, -0.46211717, 0.7615942 , 0.8336547 ,
> 0.9640276 , 0.9950547 , 1. ], dtype=float32)>
> Got:
> <tf.Tensor: shape=(8,), dtype=float32, numpy=
> array([-0.99999976, -0.99990916, -0.46211717, 0.7615942 , 0.8336546 ,
> 0.9640276 , 0.9950547 , 0.99999976], dtype=float32)>
> 
> ```
> #############################################################
> Check the documentation
> (https://www.tensorflow.org/community/contribute/docs_ref) on how to write testable docstrings.
> #############################################################
> ```
> 
> ## ======================================================================
> FAIL: tanh (tensorflow.python.ops.gen_math_ops)
> Doctest: tensorflow.python.ops.gen_math_ops.tanh
> Traceback (most recent call last):
> File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
> raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for tensorflow.python.ops.gen_math_ops.tanh
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 11336, in tanh
> 
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/gen_math_ops.py", line 11344, in tensorflow.python.ops.gen_math_ops.tanh
> Failed example:
> tf.math.tanh(x)
> Expected:
> <tf.Tensor: shape=(8,), dtype=float32, numpy=
> array([-1. , -0.99990916, -0.46211717, 0.7615942 , 0.8336547 ,
> 0.9640276 , 0.9950547 , 1. ], dtype=float32)>
> Got:
> <tf.Tensor: shape=(8,), dtype=float32, numpy=
> array([-0.99999976, -0.99990916, -0.46211717, 0.7615942 , 0.8336546 ,
> 0.9640276 , 0.9950547 , 0.99999976], dtype=float32)>
> 
> ```
> #############################################################
> Check the documentation
> (https://www.tensorflow.org/community/contribute/docs_ref) on how to write testable docstrings.
> #############################################################
> ```
> 
> ## ======================================================================
> FAIL: sigmoid (tensorflow.python.ops.math_ops)
> Doctest: tensorflow.python.ops.math_ops.sigmoid
> Traceback (most recent call last):
> File "/usr/lib/python3.8/doctest.py", line 2204, in runTest
> raise self.failureException(self.format_failure(new.getvalue()))
> AssertionError: Failed doctest test for tensorflow.python.ops.math_ops.sigmoid
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 174, in sigmoid
> 
> File "/home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow/bazel-out/aarch64-opt/bin/tensorflow/tools/docs/tf_doctest.runfiles/org_tensorflow/tensorflow/python/ops/math_ops.py", line 187, in tensorflow.python.ops.math_ops.sigmoid
> Failed example:
> tf.math.sigmoid(x)
> Expected:
> <tf.Tensor: shape=(4,), dtype=float32,
> numpy=array([0.5 , 0.7310586, 1. , 1. ], dtype=float32)>
> Got:
> <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5 , 0.7310586, 0.9999998, 0.9999998], dtype=float32)>

**Comment by soffieswan041** [comment]
> @cfRod
> @nSircombe

**Comment by mohantym** [comment]
Hi @Saduf2019 ,Could you please at this issue!

**Comment by kkimdev** [comment]
non-critical failure if it only fails on aarch64, marking contributions welcome!

**Comment by mihaimaruseac** [comment]
Doesn't seem to be caused by spacing, the error message has very different numbers

```
Expected:
<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-1. , -0.99990916, -0.46211717, 0.7615942 , 0.8336547 ,
0.9640276 , 0.9950547 , 1. ], dtype=float32)>
Got:
<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-0.99999976, -0.99990916, -0.46211717, 0.7615942 , 0.8336546 ,
0.9640276 , 0.9950547 , 0.99999976], dtype=float32)>
```

**Comment by elfringham** [comment]
The tolerance is 1e-03. The numbers are close enough to match. It is the spaces that cause the string comparison to fail.
https://github.com/tensorflow/tensorflow/blob/c1ddc3f097997094d0e045bd81502805a169937c/tensorflow/tools/docs/tf_doctest_lib.py#L117
