### ISSUE TITLE
NotFoundError: NewRandomAccessFile failed to Create/Open: images/labelmap.pbtxt : The system cannot find the file specified; No such file or directory

### ISSUE THREAD

**Issue by TriangularFarOutPoint** [tensorflow/tensorflow#52062]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Install-TensorFlow-Python 3.7 file from github repository given by the tutorial below.
- TensorFlow version: 2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4
- GPU model and memory: 

**Describe the problem**
OK, so I followed this tutorial to the T: https://www.youtube.com/watch?v=a1br6gW-8Ss&t=157s. And then I get this random error. Everything was fine, I used labelImg, I generated the tfrecords, I downloaded all the software, I organized the files and extracted all the files. I'm using an up to date version of tensorflow. And the images/labelmap.pbtxt exists in the images folder (maniacal laughter). Why can't it find this file? I added a path, that still doesn't work.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
python model_main_tf2.py --pipeline_config_path=training/ssd_efficientdet_d0_512x512_coco17_tpu-8.config --model_dir=training --alsologtostderr.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

![Screen Shot 2021-09-18 at 8 18 19 PM](https://user-images.githubusercontent.com/69585784/133936283-762c2bfa-dc92-4cc7-a8ea-b86b42942b95.png)
![Screen Shot 2021-09-19 at 1 07 55 PM](https://user-images.githubusercontent.com/69585784/133936400-d9c7b782-9a8f-4000-bdf0-e01096105dd6.png)

**Comment by Saduf2019** [comment]
@TriangularFarOutPoint 
please share the error in text so it will benefit any other user with similar error. [Also please upgrade your tf version to tf 2.4.1/2.5]
You may refer to these issues and let us know:[link](https://github.com/tensorflow/models/issues/6595),[link1](https://github.com/tensorflow/tensorflow/issues/14905)
