### ISSUE TITLE
Can't install tensorflow 1.8 on windows 10

### ISSUE THREAD

**Issue by godomainz** [tensorflow/tensorflow#52073]
python --version --> `Python 3.8.8`
 pip --version --> `pip 21.0.1 from C:\Python\anaconda3\lib\site-packages\pip (python 3.8)`

I typed `pip install tensorflow==1.8`
but it's giving me an error

```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.8
ERROR: No matching distribution found for tensorflow==1.8
```

there is no more tensorflow 1.8 ?
How can I install tensorflow 1.8 ?

**Comment by tilakrayal** [comment]
@godomainz ,
We see that you are using tf version 1.8, 1.x is not actively supported, please update to tf v2.5 or 2.6 and let us know if you are using same issue.Also please take a look at this [link](https://www.tensorflow.org/install) for installing tf latest version.It helps.Thanks

**Comment by godomainz** [comment]
@tilakrayal my CODE is done from  tf version 1.8. 
Is it possible to get tf version 1.8 ?
updating the whole program is NOT possible

**Comment by tilakrayal** [comment]
@godomainz ,
Kindly open a tf discussion forum issue for this as there is no support for 1.x is not actively supported. There is a big community to support and learn from your questions.Thanks

**Comment by jvishnuvardhan** [comment]
@godomainz The available versions are as follows
`from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0)
`

So, TF1.8 is not available. But, you should be able to run your code in `TF1.15.5` which is the most latest `TF1.x` code. Please note that there is no support for `TF1.x` related issues so we suggest users to try using `TF2.x` versions. Thanks!

I am closing this issue as this was resolved. Thanks!
