### ISSUE TITLE
[PluggableDevice] C-API Symbols not exposed

### ISSUE THREAD

**Issue by bsarden** [tensorflow/tensorflow#52077]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pypi)
- TensorFlow version: 2.6.0.dev20210612 
- Python version: 3.7.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Hello,

I’m getting started with building a plugin using the new PluggableDeviceAPI, and am hitting a few snags. Using [this example](https://github.com/jzhoulon/community/tree/plugin_tutorial/rfcs/20200624-pluggable-device-for-tensorflow/sample) as my starting point, my current goal is to have my own custom optimize callback function that walks the NodeDef's and prints the shapes of each of the Input/Output Tensor(s).

Version of tensorflow I’m using:
tf-nightly == 2.6.0.dev20210612

This problem reproduced on the latest tf-nightly for me too.

The c_api.cc symbols and the grappler.cc symbols are not exposed in the monolithic libtensorflow_framework.so. The header files are part of the tensorflow wheel distribution, but we get linker errors for things calling functions like TF_NewBuffer when using @local_config_tf//:tf_header_lib as a dep. When running nm -gDC libtensorflow_framework.so.2 it’s clear that these symbols aren’t exposed. Are there any known workarounds for this?

Also, what is the recommended way to use the C-API _with_ `libtensorflow_framework.so`? When using the `@local_config_tf` provided in the BUILD files at the example linked above, I get duplicate registries / static global's when trying to link `libtensorflow.so` _with_ `libtensorflow_framework.so` at runtime. 

Cross post from [the Tensorflow forum](https://discuss.tensorflow.org/t/pluggabledeviceapi-c-api-symbols-not-exposed/3662) due to inactivity.

Thanks in advance!

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ,Could you please look at this issue?

**Comment by gadagashwini** [comment]
@bsarden,
[This post](https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html), introduces the [PluggableDevice](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md) architecture which offers a plugin mechanism for registering devices with TensorFlow without the need to make changes in TensorFlow code. Thanks!
