### ISSUE TITLE
AttributeError: module 'tensorflow_datasets' has no attribute 'deprecated'

### ISSUE THREAD

**Issue by luguzman** [tensorflow/tensorflow#52070]
I'm using tensorflow Version: 2.3.0
and python 3.8.5

**Comment by Saduf2019** [comment]
@luguzman 
Kindly fill the issue template which helps resolve the issue.
Meanwhile you may verify if you have followed this [link](https://www.tensorflow.org/datasets/api_docs/python/tfds) and similar error issues: [link](https://stackoverflow.com/questions/40956954/tensorflow-attributeerror-module-object-has-no-attribute-deprecated), [link1](https://github.com/tensorflow/tensorflow/issues/6063),[link2](https://github.com/tensorflow/datasets/issues/2647)
