### ISSUE TITLE
make error in Tensorflow Lite Micro

### ISSUE THREAD

**Issue by GiacomoMarchioni** [tensorflow/tensorflow#52079]
**System information**
- Linux Ubuntu 20.04
- Python version: 3.8.10

**The problem**
I'm trying to generate the example projects from the tensorflow C++ library with Make and I run in this error:

/bin/sh: 1: python: not found
make: *** [tensorflow/lite/micro/examples/network_tester/Makefile.inc:52 tensorflow/lite/micro/tools/make/gen/linux_x86_64default/prj/network_tester_test/keil/keil_project.uvprojx] Error 127

**Sequence of commands**
git clone https://github.com/tensorflow/tflite-micro
cd tflite-micro
make -f tensorflow/lite/micro/tools/make/Makefile generate_projects

**Comment by vulkomilev** [comment]
Do you have python installed.
You can check by typing
python
in the terminal

**Comment by GiacomoMarchioni** [comment]
I've checked and I confirm that I have python version 3.8.10

**Comment by sanatmpa1** [comment]
@GiacomoMarchioni,

Can you provide us the detailed error trace to expedite the trouble-shooting process? Thanks!

**Comment by GiacomoMarchioni** [comment]
the following is the whole message after the make command is executed for the first time:

giacomo@LAPTOP-KEM6AB3A:~/tflite-micro$ make -f tensorflow/lite/micro/tools/make/Makefile generate_projects
--2021-09-23 01:41:57--  https://github.com/google/flatbuffers/archive/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/google/flatbuffers/zip/dca12522a9f9e37f126ab925fd385c807ab4f84e [following]
--2021-09-23 01:41:58--  https://codeload.github.com/google/flatbuffers/zip/dca12522a9f9e37f126ab925fd385c807ab4f84e
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1760478 (1.7M) [application/zip]
Saving to: ‘/tmp/tmp.GHo8RbXi4W/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip’

/tmp/tmp.GHo8RbXi4W/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip    100%[==================================================================================================================================================================>]   1.68M   551KB/s    in 3.1s

2021-09-23 01:42:02 (551 KB/s) - ‘/tmp/tmp.GHo8RbXi4W/dca12522a9f9e37f126ab925fd385c807ab4f84e.zip’ saved [1760478/1760478]

Applying /home/giacomo/tflite-micro/tensorflow/lite/micro/tools/make/downloads/flatbuffers/.//../../flatbuffers.patch to /home/giacomo/tflite-micro/tensorflow/lite/micro/tools/make/downloads/flatbuffers/./
Switched to a new branch 'tflm-patch'
Cloning into 'tensorflow/lite/micro/tools/make/downloads/pigweed'...
remote: Sending approximately 19.19 MiB ...
remote: Counting objects: 6, done
remote: Finding sources: 100% (6/6)
remote: Total 29760 (delta 13305), reused 29757 (delta 13305)
Receiving objects: 100% (29760/29760), 19.12 MiB | 2.70 MiB/s, done.
Resolving deltas: 100% (13305/13305), done.
Note: switching to '47268dff45019863e20438ca3746c6c62df6ef09'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 47268dff pw_hdlc_lite: Client I/O improvements
Applying /home/giacomo/tflite-micro/tensorflow/lite/micro/tools/make/downloads/pigweed/.//../../pigweed.patch to /home/giacomo/tflite-micro/tensorflow/lite/micro/tools/make/downloads/pigweed/./
Switched to a new branch 'tflm-patch'
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
+ [[ 0 -eq 0 ]]
+ break
++ openssl dgst -md5 /tmp/tmp.9jJDGT6r7s/temp_file
++ sed 's/.* //g'
+ DOWNLOADED_MD5=7e8191b24853d75de2af87622ad293ba
+ '[' 7e8191b24853d75de2af87622ad293ba '!=' 7e8191b24853d75de2af87622ad293ba ']'
++ echo https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
++ sed 's/\?.*//'
+ url=https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip
+ [[ https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip == *gz ]]
+ [[ https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip == *tar.xz ]]
+ [[ https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip == *bz2 ]]
+ [[ https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip == *zip ]]
+ unzip /tmp/tmp.9jJDGT6r7s/temp_file -d /tmp/tmp.ss16fJXxBU
++ find /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425 -maxdepth 0
++ wc -l
+ '[' 1 = 1 ']'
+ '[' -d /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425 ']'
+ cp -R /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/AUTHORS /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/BUILD /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/CONTRIBUTING /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/CONTRIBUTORS /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/LICENSE /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/Makefile.travis /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/README.md /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/WORKSPACE /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/contrib /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/doc /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/eight_bit_int_gemm /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/fixedpoint /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/flags.bzl /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/internal /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/jni /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/meta /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/profiling /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/public /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/scripts /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/standalone /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/test /tmp/tmp.ss16fJXxBU/gemmlowp-719139ce755a0f31cbf1c37f7f98adcc7fc9f425/todo tensorflow/lite/micro/tools/make/downloads/gemmlowp/
+ rm -rf /tmp/tmp.ss16fJXxBU /tmp/tmp.9jJDGT6r7s
+ find tensorflow/lite/micro/tools/make/downloads/gemmlowp -type f -name '*BUILD' -delete
+ [[ '' == \p\a\t\c\h\_\a\m\_\s\d\k ]]
+ [[ '' == \p\a\t\c\h\_\k\i\s\s\f\f\t ]]
+ [[ '' == \p\a\t\c\h\_\c\i\f\a\r\1\0\_\d\a\t\a\s\e\t ]]
+ [[ '' == \b\u\i\l\d\_\e\m\b\a\r\c\_\m\l\i ]]
+ [[ '' == \s\e\t\u\p\_\z\e\p\h\y\r ]]
+ [[ -n '' ]]
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip" "abf7a91eb90d195f016ebe0be885bb6e" tensorflow/lite/micro/tools/make/downloads/ruy
downloading https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip
+ [[ 0 -eq 0 ]]
+ break
++ openssl dgst -md5 /tmp/tmp.ucWBxUdbkV/temp_file
++ sed 's/.* //g'
+ DOWNLOADED_MD5=abf7a91eb90d195f016ebe0be885bb6e
+ '[' abf7a91eb90d195f016ebe0be885bb6e '!=' abf7a91eb90d195f016ebe0be885bb6e ']'
++ echo https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip
++ sed 's/\?.*//'
+ url=https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip
+ [[ https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip == *gz ]]
+ [[ https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip == *tar.xz ]]
+ [[ https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip == *bz2 ]]
+ [[ https://github.com/google/ruy/archive/d37128311b445e758136b8602d1bbd2a755e115d.zip == *zip ]]
+ unzip /tmp/tmp.ucWBxUdbkV/temp_file -d /tmp/tmp.F2WR9Q1PzY
++ find /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d -maxdepth 0
++ wc -l
+ '[' 1 = 1 ']'
+ '[' -d /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d ']'
+ cp -R /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/BUILD /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/CMakeLists.txt /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/CONTRIBUTING.md /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/LICENSE /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/README.md /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/WORKSPACE /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/cmake /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/doc /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/example /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/ruy /tmp/tmp.F2WR9Q1PzY/ruy-d37128311b445e758136b8602d1bbd2a755e115d/third_party tensorflow/lite/micro/tools/make/downloads/ruy/
+ rm -rf /tmp/tmp.F2WR9Q1PzY /tmp/tmp.ucWBxUdbkV
+ find tensorflow/lite/micro/tools/make/downloads/ruy -type f -name '*BUILD' -delete
+ [[ '' == \p\a\t\c\h\_\a\m\_\s\d\k ]]
+ [[ '' == \p\a\t\c\h\_\k\i\s\s\f\f\t ]]
+ [[ '' == \p\a\t\c\h\_\c\i\f\a\r\1\0\_\d\a\t\a\s\e\t ]]
+ [[ '' == \b\u\i\l\d\_\e\m\b\a\r\c\_\m\l\i ]]
+ [[ '' == \s\e\t\u\p\_\z\e\p\h\y\r ]]
+ [[ -n '' ]]
tensorflow/lite/micro/tools/make/download_and_extract.sh "http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip" "438ba1fef5783cc5f5f201395cc477ca" tensorflow/lite/micro/tools/make/downloads/kissfft patch_kissfft
downloading http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip
+ [[ 0 -eq 0 ]]
+ break
++ openssl dgst -md5 /tmp/tmp.DhpnNpXt7U/temp_file
++ sed 's/.* //g'
+ DOWNLOADED_MD5=438ba1fef5783cc5f5f201395cc477ca
+ '[' 438ba1fef5783cc5f5f201395cc477ca '!=' 438ba1fef5783cc5f5f201395cc477ca ']'
++ echo http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip
++ sed 's/\?.*//'
+ url=http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip
+ [[ http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip == *gz ]]
+ [[ http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip == *tar.xz ]]
+ [[ http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip == *bz2 ]]
+ [[ http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip == *zip ]]
+ unzip /tmp/tmp.DhpnNpXt7U/temp_file -d /tmp/tmp.TjPZqCpIdY
++ find /tmp/tmp.TjPZqCpIdY/kissfft-130 -maxdepth 0
++ wc -l
+ '[' 1 = 1 ']'
+ '[' -d /tmp/tmp.TjPZqCpIdY/kissfft-130 ']'
+ cp -R /tmp/tmp.TjPZqCpIdY/kissfft-130/CHANGELOG /tmp/tmp.TjPZqCpIdY/kissfft-130/COPYING /tmp/tmp.TjPZqCpIdY/kissfft-130/Makefile /tmp/tmp.TjPZqCpIdY/kissfft-130/README /tmp/tmp.TjPZqCpIdY/kissfft-130/README.simd /tmp/tmp.TjPZqCpIdY/kissfft-130/TIPS /tmp/tmp.TjPZqCpIdY/kissfft-130/_kiss_fft_guts.h /tmp/tmp.TjPZqCpIdY/kissfft-130/kiss_fft.c /tmp/tmp.TjPZqCpIdY/kissfft-130/kiss_fft.h /tmp/tmp.TjPZqCpIdY/kissfft-130/kissfft.hh /tmp/tmp.TjPZqCpIdY/kissfft-130/test /tmp/tmp.TjPZqCpIdY/kissfft-130/tools tensorflow/lite/micro/tools/make/downloads/kissfft/
+ rm -rf /tmp/tmp.TjPZqCpIdY /tmp/tmp.DhpnNpXt7U
+ find tensorflow/lite/micro/tools/make/downloads/kissfft -type f -name '*BUILD' -delete
+ [[ patch_kissfft == \p\a\t\c\h\_\a\m\_\s\d\k ]]
+ [[ patch_kissfft == \p\a\t\c\h\_\k\i\s\s\f\f\t ]]
+ patch_kissfft tensorflow/lite/micro/tools/make/downloads/kissfft
+ sed -i -E 's@#ifdef FIXED_POINT@// Patched automatically by download_dependencies.sh so default is 16 bit.\
#ifndef FIXED_POINT\
#define FIXED_POINT (16)\
#endif\
// End patch.\
\
#ifdef FIXED_POINT@g' tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.h
+ sed -i -E '/^#include <sys\/types.h>/d' tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.h
+ sed -i -E 's@#ifdef FIXED_POINT@#ifdef FIXED_POINT\
#include <stdint.h> /* Patched. */@g' tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.h
+ sed -i -E 's@#define KISS_FFT_MALLOC malloc@#define KISS_FFT_MALLOC(X) (void*)(0) /* Patched. */@g' tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.h
+ sed -i -E 's@#define KISS_FFT_FREE free@#define KISS_FFT_FREE(X) /* Patched. */@g' tensorflow/lite/micro/tools/make/downloads/kissfft/kiss_fft.h
+ sed -ir -E 's@(fprintf.*\);)@/* \1 */@g' tensorflow/lite/micro/tools/make/downloads/kissfft/tools/kiss_fftr.c
+ sed -ir -E 's@(exit.*\);)@return; /* \1 */@g' tensorflow/lite/micro/tools/make/downloads/kissfft/tools/kiss_fftr.c
+ echo 'Finished patching kissfft'
Finished patching kissfft
/bin/sh: 1: python: not found
make: *** [tensorflow/lite/micro/examples/network_tester/Makefile.inc:52: tensorflow/lite/micro/tools/make/gen/linux_x86_64_default/prj/network_tester_test/keil/keil_project.uvprojx] Error 127

**Comment by jvishnuvardhan** [comment]
@GiacomoMarchioni This is more related to tflite micro. I was able to run those commands in colab. [Here](https://colab.research.google.com/gist/jvishnuvardhan/4af29c05d36d04488e2c75c6c067fa78/untitled.ipynb) is a gist for our reference.

As this is more related to TFlite micro, posting it on TFlite micro repository would result in faster resolution  https://github.com/tensorflow/tflite-micro

Thanks

**Comment by mohantym** [comment]
Hi @GiacomoMarchioni !

Could you go with below work around and let us know. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/76ba7c2d5fa5ac68bceb35fd461f9f23/git_52079.ipynb)for reference.
`make -f tensorflow/lite/micro/tools/make/Makefile `

Please post on tflite-micro repo as suggested in above  [comment](https://github.com/tensorflow/tensorflow/issues/52079#issuecomment-930526545) for further assistance .

Thank you!
