### ISSUE TITLE
How to reduce libtensorflowlite.so size with C++ api

### ISSUE THREAD

**Issue by Liupengshuaige** [tensorflow/tensorflow#52088]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 12.0.5
- CUDA/cuDNN version: None
- GPU model and memory: android GPU

**Describe the problem**
Hello , I want to build libtensorflowlite.so for android with c++ api, I want to build the selective so with a tflite model  .I follow the guide in https://github.com/tensorflow/tensorflow/issues/50946
I add tflite_custom_cc_library like this:

load("//tensorflow/lite:build_def.bzl", "tflite_cc_shared_object", "tflite_copts", "tflite_copts_warnings", "tflite_custom_cc_library")
tflite_custom_cc_library(
    name = "custom_tflite_lib",
    models = [
        "test.tflite",
    ],
)
and the trained tflite model for selective build. And the the command is :
bazel build -c opt --config android_arm64 tensorflow/lite:custom_tflite_lib

It built successfully.And the  so size reduced from 3.7M to 380K. But when I link the so, I found that it only contains the kernels and so on ,it doesn't contain the flatbuffer and other functions such as "TfLiteDelegateCreate" and so on.I have also read the issue https://github.com/tensorflow/tensorflow/issues/50946 
but the so built is only for c api, I want to use the android gpu to inference with opencl, so how should I reduce the libtensorflowlite.so for c++ api with other necessary parts?

Thanks.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build -c opt --config android_arm64 tensorflow/lite:custom_tflite_lib

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ,Could you please look at this issue!

**Comment by thaink** [comment]
That cc_library is for using as dependencies of other bazel rule.
for cc shared object, you can try: in tensorflow/lite/BUILD:
- remove ":framework"  and "//third_party/tensorflow/lite/kernels:builtin_ops_all_linked" in the deps field
- add your new custom cc_library there
Then you can try to build the //tensorflow/lite:tensorflowlite.
