### ISSUE TITLE
Build libtensorflow_cc.dll x86 error on Window

### ISSUE THREAD

**Issue by VNTamao** [tensorflow/tensorflow#52098]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.6.0
- Python version: Python 3.9.7
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version:  11.2
- GPU model and memory: NVIDIA GeForce GTX 1650

As title, I got an error when try to create libtensorflow_cc.lib and libtensorflow_cc.dll which can be used with MSVC2019_32bit compiler.

I used below command:
`bazel build --cpu=x86 --config=opt --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings --local_ram_resources=2048 tensorflow:tensorflow_cc`
But I got below error:
` The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=225
INFO: Reading rc options for 'build' from c:\users\1111\desktop\work\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/1111/AppData/Local/Programs/Python/Python39/python.exe
INFO: Reading rc options for 'build' from c:\users\1111\desktop\work\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from c:\users\1111\desktop\work\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/1111/AppData/Local/Programs/Python/Python39/python.exe --action_env PYTHON_LIB_PATH=C:/Users/1111/AppData/Local/Programs/Python/Python39/lib/site-packages --python_path=C:/Users/1111/AppData/Local/Programs/Python/Python39/python.exe --action_env TF_CUDA_VERSION=11.2 --action_env TF_CUDNN_VERSION=8 --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 --config=cuda --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Found applicable config definition build:short_logs in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file c:\users\1111\desktop\work\tensorflow\.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:cuda in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:windows in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\1111\desktop\work\tensorflow\.bazelrc: --define framework_shared_object=false
DEBUG: C:/users/1111/_bazel_1111/ejl7ywpf/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: C:/users/1111/_bazel_1111/ejl7ywpf/external/local_config_cuda/crosstool/BUILD:24:19: in cc_toolchain_suite rule @local_config_cuda//crosstool:toolchain: cc_toolchain_suite '@local_config_cuda//crosstool:toolchain' does not contain a toolchain for cpu 'x86'
ERROR: Analysis of target '//tensorflow:tensorflow_cc' failed; build aborted: Analysis of target '@local_config_cuda//crosstool:toolchain' failed
INFO: Elapsed time: 1.352s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (35 packages loaded, 175 targets configured)`

Is there any way to fix this?
If yes, please share with me.
Thanks

**Comment by VNTamao** [comment]
@tilakrayal 
Could you please help me check this issue?
Thanks

**Comment by Saduf2019** [comment]
@VNTamao 
This may be due to conflicts in dependencies.Always it would be better to create an virtual environment and install tensorflow .

You might be facing this issue because of the following reasons

You are running 32-bit Python or 32-bit OS
You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) package
Your CPU does not support AVX instructions.
Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.


Thanks!

**Comment by VNTamao** [comment]
@Saduf2019 
Can we create a library 32 bit to using with Desktop applition?
I'm developing a Desktop application, use Qt IDE and MSVC 2019 32bit.
I tried with MSVC 2019 64bit and it's ok. But when I tried change to MSVC 2019 32bit, I cannot create tensorflow_cc library.
Does tensorflow support to create library using for MSVC 2019 32bit?
Thanks

**Comment by Saduf2019** [comment]
No, as explained in most of the issues, there is no support for 32 bits. Please use 64 bit its tested and works as expected. You may move this issue to closed status as the issue reported is addressed.
