### ISSUE TITLE
Couldn't import 'tensorflow.tools.graph_transforms' in tensorflow 2.5.0

### ISSUE THREAD

**Issue by amitkumardatta** [tensorflow/tensorflow#52094]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary pip install
- TensorFlow version (use command below): 2.5.0
- Python version: 3.9.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

```
from tensorflow.tools.graph_transforms import TransformGraph
```

Error message:

```
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
```

Tensorflow version:
```
> pip show tensorflow

Name: tensorflow
Version: 2.5.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: ..\appdata\local\programs\python\python39\lib\site-packages
Requires: tensorboard, wheel, keras-nightly, grpcio, wrapt, six, astunparse, gast, protobuf, typing-extensions, google-pasta, numpy, tensorflow-estimator, h5py, flatbuffers, opt-einsum, absl-py, keras-preprocessing, termcolor
Required-by:
```

**Describe the expected behavior**
Successfully import the graph_transforms module.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
from tensorflow.tools.graph_transforms import TransformGraph
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Source code: https://replit.com/@Amit-KumarKuma4/objectdetection

**Comment by Saduf2019** [comment]
@amitkumardatta 
Please refer to these same error issues: [link](https://github.com/tensorflow/tensorflow/issues/33352), [link1](https://stackoverflow.com/questions/59825444/modulenotfounderror-no-module-named-tensorflow-tools-graph-transforms-when-us)
