### ISSUE TITLE
Unable to run the exe that has wheel generated by Rosetta terminal on MacOs Mojave, error: Symbol not found: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by Nizarazo** [tensorflow/tensorflow#52090]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs Mojave 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not relevant
- TensorFlow installed from (source or binary): private wheel
- TensorFlow version: 1.13.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): not relevant 
- CUDA/cuDNN version: not relevant
- GPU model and memory: not relevant

**Describe the problem**
Following the instructions in forum: https://github.com/tensorflow/tensorflow/issues/46044
I compiled tensorflow 1.13.1 using Bazel 0.21.1 under Bigsur using rosetta terminal in order to run this wheel under Rosettna emulator over arm/intel cpu, the generated wheel works fine on Bigsur and Catalina but it didn't work on Mojave I am getting error appeared in the logs section.
However the public wheel works fine on Mojave 10.14.6.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Use Big Sir with arm processor m1 since it has Terminal for Rosetta

2. open Terminal Get Info and enable "Open using Rosetta" (duplicate Terminal app for this and open Rosetta terminal)

3. git clone https://github.com/tensorflow/tensorflow.git

4. cd tensorflow

5. git checkout branch_name (for us: v1.13.1)

6. install bazel version 0.21.0

7. generate virtual environment of python3.6 that has in the requirements tensorflow==1.13.1 and other packages related to our project

8. ./configure (say N to everything except setting the python virtual environment created in 7 here)

9. bazel build //tensorflow/tools/pip_package:build_pip_package

10. bazel-bin/tensorflow/tools/pip_package/build_pip_package/tmp/tensorflow_pkg

11. rename .whl file to disable OS restrictions (us: tensorflow-1.13.1-py3-none-any.whl)

12. Take this wheel that support rosetta and set it in the virtual environment (instead of downloading public wheel), in requirements: ./wheels/tensorflow-1.13.1-py3-none-any.whl 

13. Build the exe using pyinstaller version 3.4 with this virtual environment that has private tensorflow wheel.

14. Run the exe from 13 on Moajve and you will get the error attached in logs 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

2021-09-20 14:10:58,992 INFO Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
  File "/p4client/ProAudio/dev_mainV12/ProAudio/XPlatform/Apps/WavesPluginServer/pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: dlopen(/Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so, 6): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sushreebarsa** [comment]
@Nizarazo 
We see that you are using old version of tensorflow(`1.13`) which is not actively supported. We recommend that you upgrade to `2.6.0` and let us know if the issue still persists in newer versions. Please have a look at the [link](https://www.tensorflow.org/install/source#macos) to `Build from source` and let us know if it helps ?Thanks!

**Comment by Nizarazo** [comment]
Hi @sushreebarsa @Saduf2019 

The issue is not related to tensorflow version 1.13 because the public wheel of tensorflow 1.13 is working fine on Mojave, the issue is the private wheel generated using rosetta terminal under BigSur M1 does not run on Mojave so I guess it is something related to the way I build the private wheel under BigSir M1 rosetta terminal.
Is there any configuration I need to add while building in BigSur M1 using Bazel for example "minimum macos version" so that it can support Mojave?
I wrote the 14 steps how I build the wheel above please have a look and let me know what step is wrong/missing.

Thanks

**Comment by Saduf2019** [comment]
@Nizarazo 
The Apple TF on M1 chips is a private fork of TF owned by Apple. We don't have access to fixing code issues there.

For more information, please go through issue #44751. Thanks!

**Comment by Nizarazo** [comment]
@Saduf2019 I am not using Apple TF but I am using your tensorflow by building it from source using rosetta terminal under Big Sur as explained in thread #46044 so the generated wheel runs fine over BigSur M1 using Rosetta emulator and it runs fine also on catalina but it doesn't run on Mojave I am getting this:
2021-09-20 14:10:58,992 INFO Traceback (most recent call last):
File "tensorflow/python/pywrap_tensorflow_internal.py", line 18, in swig_import_helper
File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "tensorflow/python/pywrap_tensorflow.py", line 58, in
File "/p4client/ProAudio/dev_mainV12/ProAudio/XPlatform/Apps/WavesPluginServer/pythonVirtualEnv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
File "tensorflow/python/pywrap_tensorflow_internal.py", line 28, in
File "tensorflow/python/pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: dlopen(/Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so, 6): Symbol not found: ___darwin_check_fd_set_overflow
Referenced from: /Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so (which was built for Mac OS X 11.0)
Expected in: /usr/lib/libSystem.B.dylib
in /Library/Application Support/Waves/WavesPluginServer/WavesPluginServerV13.1.bundle/Contents/MacOS/_pywrap_tensorflow_internal.so

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

**Comment by Saduf2019** [comment]
@Nizarazo 
For the error, can you refer to same error issues and let us know: "ImportError: No module named '_pywrap_tensorflow_internal'"
[link](https://github.com/tensorflow/tensorflow/issues/40459),[link1](https://github.com/tensorflow/tensorflow/issues/37906),[link2](https://stackoverflow.com/questions/44080677/no-module-named-pywrap-tensorflow-internal),[link](https://github.com/tensorflow/tensorflow/issues/11571)

**Comment by Nizarazo** [comment]
@Saduf2019
These links are all for Windows while the issue I am facing is in MacOs Mojave any similar issues in MacOs?

By the way I see that the file _pywrap_tensorflow_internal.so exists but seems that the symbol ___darwin_check_fd_set_overflow is missing.

**Comment by Nizarazo** [comment]
Fixed by building Tensorflow using older macOS Catalina instead of Big Sur seems sadly it is not backward compatible.
