### ISSUE TITLE
Undeclared identifier when building from source v2.3.2

### ISSUE THREAD

**Issue by Ramsonjehu** [tensorflow/tensorflow#52092]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.3.2
- Python version: 3.8
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): msvc v142
- CUDA/cuDNN version: CUDA 10.2 / cuDNN 7.6
- GPU model and memory: Nvidia GeForce RTX 2060 / 14 GB

**Describe the problem**
Undeclared identifier error when building from source v2.3.2. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
**Configuration**
> $ python configure.py
> You have bazel 3.1.0 installed.
> Please specify the location of python. [Default is C:\python\python.exe]:
> 
> 
> Found possible Python library paths:
>   C:\python\lib\site-packages
> Please input the desired Python library path to use.  Default is [C:\python\lib\site-packages]
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]: n
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: y
> CUDA support will be enabled for TensorFlow.
> 
> Found CUDA 10.2 in:
>     C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64
>     C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include
> Found cuDNN 7 in:
>     C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64
>     C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/include
> 
> 
> Please specify a list of comma-separated CUDA compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
> Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]:
> 
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
> 
> 
> Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: n
> Not overriding eigen strong inline, some compilations could take more than 20 mins.
> 
> Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
> Not configuring the WORKSPACE for Android builds.
> 
> Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
>         --config=mkl            # Build with MKL support.
>         --config=monolithic     # Config for mostly static monolithic build.
>         --config=ngraph         # Build with Intel nGraph support.
>         --config=numa           # Build with NUMA support.
>         --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
>         --config=v2             # Build TensorFlow 2.x instead of 1.x.
> Preconfigured Bazel build configs to DISABLE default on features:
>         --config=noaws          # Disable AWS S3 filesystem support.
>         --config=nogcp          # Disable GCP support.
>         --config=nohdfs         # Disable HDFS support.
>         --config=nonccl         # Disable NVIDIA NCCL support.
> 
**Build command:**
`bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package` 

**Any other info / logs**
`external/com_google_absl\absl/time/clock.h(70): error C2065: 'Duration': undeclared identifier
external/com_google_absl\absl/time/clock.h(70): error C2146: syntax error: missing ')' before identifier 'duration'
external/com_google_absl\absl/time/clock.h(70): error C2143: syntax error: missing ';' before '{'
external/com_google_absl\absl/time/clock.h(70): error C2447: '{': missing function header (old-style formal list?)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 899.084s, Critical Path: 504.33s
INFO: 1352 processes: 1352 local.
FAILED: Build did NOT complete successfully` 

The issue has been reported already [#38316](https://github.com/tensorflow/tensorflow/issues/38316). But the solution is not proper.

**Comment by tilakrayal** [comment]
@Ramsonjehu ,
Can you please try installing TensorFlow v2.3 with CUDA 10.1 and cuDNN 7.6 and check if you are facing the same error.TF v2.3 is little older version.Suggesting to upgrade to latest stable tf v2.6. For more information please take a look at the tested [build configurations](https://www.tensorflow.org/install/source_windows#gpu) Thanks!

**Comment by Ramsonjehu** [comment]
@tilakrayal 
1. I'm Trying to use NXP's eIQ portal application which requires TF v2.3.2. so I can't upgrade to TF v2.6. 
2. Does this error has anything to do with CUDA 10.2? because all the other build configuration are same as the in the link you provided.

**Comment by Ramsonjehu** [comment]
Hi @tilakrayal ,
As you said i tried building with CUDA 10.1. But im facing a new issue as mentioned below.

`DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  C:/users/surya/_bazel_surya/h5eisutx/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1214, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1214, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed

WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
                _create_local_cuda_repository(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213, in _create_local_cuda_repository
                to_list_of_strings(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1214, in to_list_of_strings
                _cuda_include_path(<2 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in _cuda_include_path
                inc_entries.append(<1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 363, in inc_entries.append
                realpath(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 268, in realpath
                execute(repository_ctx, <1 more arguments>)
        File "F:/ramson/tensorflow_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed

INFO: Elapsed time: 0.968s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package`

**Comment by tilakrayal** [comment]
@Ramsonjehu ,
Can you please refer this [comment](https://github.com/tensorflow/tensorflow/issues/44251#issuecomment-724863274) from issue with the similar error.It helps.Thanks!

**Comment by Ramsonjehu** [comment]
@tilakrayal , In the [comment](https://github.com/tensorflow/tensorflow/issues/44251#issuecomment-724863274) you mentioned, its been told to check the line which causes the error. 
 

    def _cuda_autoconf_impl(repository_ctx):
    """Implementation of the cuda_autoconf repository rule."""
     if not enable_cuda(repository_ctx):
        _create_dummy_repository(repository_ctx)
    elif get_host_environ(repository_ctx, _TF_CUDA_CONFIG_REPO) != None:
        has_cuda_version = get_host_environ(repository_ctx, _TF_CUDA_VERSION) != None
        has_cudnn_version = get_host_environ(repository_ctx, _TF_CUDNN_VERSION) != None
        if not has_cuda_version or not has_cudnn_version:
            auto_configure_fail("%s and %s must also be set if %s is specified" %
                                (_TF_CUDA_VERSION, _TF_CUDNN_VERSION, _TF_CUDA_CONFIG_REPO))
        _create_remote_cuda_repository(
            repository_ctx,
            get_host_environ(repository_ctx, _TF_CUDA_CONFIG_REPO),
        )
    else:
        _create_local_cuda_repository(repository_ctx) // **This is line number 1369 mentioned in the error**

As you can see **_repository_ctx_** is the argument to the function, im unable to find from where the function is called, so i can't validate if the path exists or not.  Can you please suggest any specific solution ?

**Comment by Saduf2019** [comment]
@Ramsonjehu 
Is there any specific reason for using 2.3.2, as many bugs are fixed is later versions would you want to try on later versions.

Also can you try:
Could you please try and let us know:
$ bazel clean
$ ./configure # make sure to choose gpu support
$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

If you still face error please follow [this comment](https://github.com/tensorflow/tensorflow/issues/50943#issuecomment-912322300).

**Comment by Ramsonjehu** [comment]
Hi @Saduf2019 ,
**_Is there any specific reason for using 2.3.2?_** 
Yes, as i mentioned before I'm Trying to use NXP's eIQ portal application which requires TF v2.3.2. so I can't upgrade to TF v2.6.

**_Also can you try:
Could you please try and let us know:
$ bazel clean
$ ./configure # make sure to choose gpu support**
I couldn't run ./configure, instead i tried running python configure.py and choose gpu support 
**$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer** 
when running the above command, I get the following error:
`ERROR: While parsing option -c -opt: Not a valid compilation mode: '-opt' (should be fastbuild, dbg or opt)`

**Comment by Saduf2019** [comment]
@Ramsonjehu 
 Did you try : If you still face error please follow this comment. above, do let us know.
