### ISSUE TITLE
Very slow inference on TF Lite>=2.4.0 converted model

### ISSUE THREAD

**Issue by ebraraktas** [tensorflow/tensorflow#52105]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur 11.4 and Ubuntu 18.04 LTS on Colab machine
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.3.0 and 2.6.0

### 2. Code

This notebook demonstrates the bug with the simplest example I came up with.

https://colab.research.google.com/gist/ebraraktas/30d0a24ce2fb391a22e68a30e2f9cdc1

### 3. Failure after conversion

Inference takes too much time on models converted by `tensorflow>=2.4.0` (See `Inference Logs`). I have attached the models; but as it is described in the colab, you can create them as well. 

As you can see from the logs below, quantized `CONV2D` seems to updated to `version '5'` and this **runs approximately 27x slower** on x86_64 machine. However, it runs slightly faster on ARM.

##### x86_64 - Colab
```
TF Runtime Version: 2.6.0
Model path: model_2.3.0.tflite
Test Duration: 0.5242369174957275 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.6.0
Model path: model_2.3.0_quant.tflite
Test Duration: 0.7532312870025635 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.6.0
Model path: model_2.6.0.tflite
Test Duration: 0.532163143157959 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.6.0
Model path: model_2.6.0_quant.tflite
Test Duration: 18.914307594299316 s
= = = = = = = = = = = = = = = = = = = = 
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.3.0
Model path: model_2.3.0.tflite
Test Duration: 0.5360305309295654 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.3.0
Model path: model_2.3.0_quant.tflite
Test Duration: 0.5518338680267334 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.3.0
Model path: model_2.6.0.tflite
Test Duration: 0.5399584770202637 s
= = = = = = = = = = = = = = = = = = = = 
TF Runtime Version: 2.3.0
Model path: model_2.6.0_quant.tflite
Cannot create Interpreter! Exception:
Didn't find op for builtin opcode 'CONV_2D' version '5'
Registration failed.
```

##### ARM - iPhone 12 - TensorFlowLite 2.6.0

```
| model_2.3.0.tflite | 199.0520 ms | 
| model_2.6.0.tflite | 183.2420 ms | 
| model_2.3.0_quant.tflite |  71.3949 ms | 
| model_2.6.0_quant.tflite |  63.4819 ms | 
```

[models.zip](https://github.com/tensorflow/tensorflow/files/7216038/models.zip)

**Comment by pranve** [comment]
Hi Ethan, can you please take a look at this possible regression issue?..Thanks!

**Comment by ebraraktas** [comment]
Hi, are there any updates on this issue? @ethkim I think it is crucial, because it is easy to be misleaded by benchmark results of the model converted by recent tensorflow version.

**Comment by ebraraktas** [comment]
Ping @ethkim . This is a blocker for me, because tensorflow `2.3` is getting older. Some operations do not have lite kernels in tensorflow `2.3`, but I need to use TF `2.3` to convert a model having `Conv` layer. I have tested the gist above with TF `2.7` and the issue still exists, unfortunately.

**Comment by ebraraktas** [comment]
Hi, I have investigated this issue and found some points which would be helpful for the assignee of the issue @ethkim  and anyone having the issue. 

The new `Conv2D` implementation of the quantized tflite model uses [`HybridConvPerChannel`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L1423) which depends on the `ruy`, previously it was using [`HybridConv`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L1331).  And current `tensorflow` official python runtime was not built with AVX enabled, hence it uses [(Standard Cpp) implemation of the `ruy:TrMul`](https://github.com/google/ruy/blob/master/ruy/kernel.h#L209). My findinds are:

1 - It is mentioned by @talumbau in [an issue](https://github.com/tensorflow/tensorflow/issues/42941#issuecomment-722038724) that using `RUY_PATHS=0x20` enables the AVX2 path, and it really runs faster with that environment variable. However, it creates wrong outputs. Actually, if it is easy to correct this output, it would be the quickest solution of the issue.
2 - It is possible to [build `tensorflow` from source](https://www.tensorflow.org/install/source) on Ubuntu with those instruction sets enabled using `--copt=-march=native --define=tflite_with_ruy=true` flags. Then using that python version runs even faster than the model converted by tf 2.3.0 (depending on your CPU).
3 - Unfortunately, the workaround in 2 does not apply to MacOS. See [this issue in `ruy`](https://github.com/google/ruy/issues/299).

According to my findings, it would be better to add another optimized implementation or distribute tensorflow with AVX enabled for the current implementation. For the Apple MacOS, I think `ruy` team must update their implementation, I may be mistaken about this.

**Comment by sachinprasadhs** [comment]
Hi, Could you test against the build from latest Tensorflow version and check the inference time.
Also, since many changes are made in the TFLite, backward compatibility for all the builtin op or quantization method would be challenging. It is suggested to use the latest version with the model trained on same version. Thanks!
