### ISSUE TITLE
Pricing details for Tensorflow 

### ISSUE THREAD

**Issue by AditiG27** [tensorflow/tensorflow#52106]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

Hi Team,
I am interested in knowing the pricing details and the storage availability as I want to use this Tensorflow software in my project. I also would want to know any new and important feature the latest version has come up with. Appreciating the response at the latest.
Thanking you.

Regards,
Aditi G

**Comment by sushreebarsa** [comment]
@AditiG27     **`TensorFlow`** is an **Open-source platform** for creating ML-enabled applications. To know more on Tensorflow please visit to  our [official site of Tensorflow](https://www.tensorflow.org/overview/) and refer to the documentation .Please let us know if it helps ? Thank you!

**Comment by AditiG27** [comment]
Does this has any subscription or package ? I couldnt find these pricing and storage details. Please provide me these details.

**Comment by sushreebarsa** [comment]
@AditiG27 Tensorflow is a `free` and `open source` Software library for Machine learning and Artificial Intelligence. This framework is free to use. Thanks!

**Comment by AditiG27** [comment]
Any professional support services charges included or required ?

**Comment by sushreebarsa** [comment]
@AditiG27 There is no support  service charges included for using Tensorflow .It is free and open source platform .

**Comment by sushreebarsa** [comment]
@AditiG27 Could you please let us know if we can close this ticket as it has been resolved ?Thank you!

**Comment by fsx950223** [comment]
https://cloud.google.com/blog/products/ai-machine-learning/introducing-tensorflow-enterprise-supported-scalable-and-seamless-tensorflow-in-the-cloud

**Comment by AditiG27** [comment]
Can you provide the infrastructure requirement for Tensorfllow setup along with its security features ?

**Comment by mihaimaruseac** [comment]
TF Enterprise is provided via GCP. Pricing details should be obtained via Google Cloud sales.

TF itself is open source, free to use.

GitHub is not a good place to discuss this. This space is for issues related to the code, bugs, feature requests, etc.
