### ISSUE TITLE
Inconsistent broadcast behavior when using model.fit vs custom training loop

### ISSUE THREAD

**Issue by pavanky** [tensorflow/tensorflow#52115]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linunx ? Repro on colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6
- Python version: 3.7 ? 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/a

**Describe the current behavior**

broadcast behavior different between `keras.Model.fit` v/s custom training loop

**Describe the expected behavior**

broadcast behavior is consistent.

**[Contributing](https://www.tensorflow.org/community/contribute)**
N/A

- Do you want to contribute a PR? (yes/no): no

- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
https://gist.github.com/pavanky/95d6ae0a1e875d2cd9e60e24e9d3e1b6

**Comment by pavanky** [comment]
Note: The behavior of custom training loop is consistent with eager mode execution (without keras), and numpy. However this inconsistent behavior may cause unnecessary debugging overhead.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look at this issue ? It is replicating in TF [2.5](https://colab.research.google.com/gist/mohantym/896dcd25d8288ced6e216debd88518f4/github_52115.ipynb#scrollTo=GeJIUD2Dg_c6),[2.6 ](https://colab.research.google.com/gist/mohantym/63b366893cf0417a93734fdc3b4156c5/github_52115.ipynb#scrollTo=1ZcpdRU8hH3C) and showing different error in Model1.fit() operation in  [2.7.0dev].(https://colab.research.google.com/gist/mohantym/278bda43f794d9ea3f881196361d82b9/github_52115.ipynb#scrollTo=fOMZqEGxg8Td)
