### ISSUE TITLE
'pip install tensorflow' does not work on FreeBSD

### ISSUE THREAD

**Issue by probonopd** [tensorflow/tensorflow#52125]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): FreeBSD 12.2
- TensorFlow installed from (source or binary): trying to install binary using `pip`
- TensorFlow version: any
- Python version: 3.8

**Describe the problem**

`pip install tensorflow` does not work on FreeBSD. Apparently there is no precompiled package for FreeBSD. Why?

```
FreeBSD% ./spleeter/bin/pip install tensorflow     
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Any other info / logs**
Was pointed to this issue tracker from https://github.com/pypa/packaging-problems/issues/547.

**Comment by omxpro** [comment]
Same error

**Comment by omxpro** [comment]
#52143

**Comment by tilakrayal** [comment]
@probonopd ,
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

**Comment by probonopd** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): __`FreeBSD 12.2`__
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: __Not a mobile device__
TensorFlow installed from (source or binary): __trying to install binary using `pip`__
TensorFlow version: __any__
Python version: __3.8.10__
Installed using virtualenv? pip? conda?: __trying to install binary using `pip`__
Bazel version (if compiling from source): __n/a__
GCC/Compiler version (if compiling from source): __n/a__
CUDA/cuDNN version: __n/a__
GPU model and memory: __n/a__

**Comment by Saduf2019** [comment]
@probonopd 
Can you please refer to similar error [issues](https://github.com/tensorflow/tensorflow/issues/42482#issuecomment-680855973) and let us know: #44615, #47205, [link](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip)

Please, uninstall everything and then install in new environment.

Step 1: pip install -U pip
Step 2: pip install -U setuptools
Step 3: pip install tensorflow
TensorFlow 2 packages require a pip version >19.0. Could you please upgrade pip using the below command and let us know if it works.

**Comment by omxpro** [comment]
I have pip 21

**Comment by Saduf2019** [comment]
@omxpro 
Can you please refer to : #37345, #50766, [link](https://githubmemory.com/repo/pypa/packaging-problems/issues/547)

**Comment by probonopd** [comment]
Why refer to other tickets. The fact is that there is not FreeBSD builds:

https://storage.googleapis.com/tensorflow lists binaries for Mac (`darwin`), Windows (`windows`), and Linux (`linux`) but *not* for FreeBSD.

**Comment by mihaimaruseac** [comment]
The team responsible for the official Google TF builds has very few people and cannot manage the large space of `{operating system} x {python version} x {dependency versions} x {CPU/GPU} x {C/Python/C++/Java/etc.} x {TF/TFLite/etc}`. Given that more support is not really rewarded at perf review time, the team really has to limit amount of support offered.

Custom builds are available via SIG Build (https://github.com/tensorflow/build), you can also join the monthly meeting to discuss support for the custom builds there (bit.ly/tf-sig-build-notes)

**Comment by probonopd** [comment]
I understand that the team responsible for the official Google TF builds cannot do builds for everything.

So would it be possible to 

---

provide source distributions on PyPI and let https://www.pypa.io/ do the building?

https://github.com/pypa/packaging-problems/issues/547#issuecomment-926882371

> I think the answer to your problem is that TensorFlow doesn't distribute any source distributions on PyPI

**Comment by mihaimaruseac** [comment]
Wouldn't that result in timeouts? A current builds takes hours.

**Comment by mihaimaruseac** [comment]
We could attempt to provide one though

**Comment by mihaimaruseac** [comment]
There might be an issue here in that TF builds with Bazel (no cmake support) and pypa might not be able to run these.

**Comment by mihaimaruseac** [comment]
But that is no longer TF issue, Bazel is a separate team

**Comment by mihaimaruseac** [comment]
CC @perfinion, based on the SIG Build discussion

**Comment by mohantym** [comment]
Hi @probonopd @Vadim-Maklakov !

We are checking to see whether you still need help in this issue . 
Regarding  a cpu build for freebsd  using build from source , You can check [build from source ](https://www.tensorflow.org/install/source)document and [sample bazel notebook ](https://colab.sandbox.google.com/gist/mohantym/d7479993bd95a7ad4f2bb028ca5d8d0d/tensorflow-ranking.ipynb#scrollTo=zswxtT0qp51z)for reference. 

Attached relevant [thread](https://github.com/tensorflow/tensorflow/issues/51932#issuecomment-1381996844) on freebsd-tensorflow installation.

Please post on Tensorflow/build  or TF-Forum for further queries.

Thank you!

**Comment by probonopd** [comment]
Thanks for checking @mohantym. Well, a (for me) satisfactory solution would be a working `pip install tensorflow ` on FreeBSD. Apparently this would require tensorflow to be compiled by someone in the TensorFlow team. All other solutions mean that TensorFlow on FreeBSD is not fully supported on the same level as it is on Linux, Windows, and the Mac. Compiling it from source is error-prone and needs a lot of time, resources, and skills.

**Comment by henryiii** [comment]
You can't precompile wheels for FreeBSD and upload them to PyPI. Last I checked, there's not a proper BSD compatibility guarantee (either forward or between BSDs, from what I understand) to allow a "ManyBSD" wheel (like manylinux & GLIBC, or even musllinux with MUSL), so binaries cannot be provided for it by anyone on PyPI - this is not tensorflow specific. Currently the only option is to go with some sort of BSD packaging system other than pip.

**Comment by probonopd** [comment]
Thanks for the clarification @henryiii. If this is the case, then there is no point in keeping this issue open imho.
