### ISSUE TITLE
Tensorflow site language switching

### ISSUE THREAD

**Issue by zzz7net** [tensorflow/tensorflow#52129]
![tf-site](https://user-images.githubusercontent.com/5677691/134763303-c4bb3386-de5f-41e6-9ac7-6c5ef0f58e9e.png)
Switching from Russian to English doesn't work.
English -> Russian is ok
Russian -> French is ok
Russian -> Deutsch is ok
I've tried this: https://www.tensorflow.org/ and this
https://www.tensorflow.org/?hl=en
Also I've deleted all other languages except English from my Google Account.

**Comment by zzz7net** [comment]
Tested in Google Chrome and Mozilla Firefox browser.

**Comment by mohantym** [comment]
Hi @zzz7net! I checked the translation in Russian then switched to English from Drop down .Link is working fine for me. Could you  check again after disconnecting from any VPN service if you are using.

**Comment by zzz7net** [comment]
VPN is off and the same result. Even if I connect through VPN a language of the interface should not depend on my location. Because I switch the language manually. I can switch from Russian to any language except English. And this is a bug or web-designer flaw.

**Comment by mohantym** [comment]
Hi @zzz7net ! I tried to replicate the above situation in my local system (connected with VPN) , It lagged a bit after switched from Russian to English and then worked when I refreshed the Site once. Can you check after refreshing the page once?

**Comment by zzz7net** [comment]
@mohantym I appreciate your efforts, but I'm already used to this feature. It shouldn't work that way, but let's say it is a Google feature, not a bug. Hopefully in the future someone will rewrite tensorflow site and everything will work as it should.

**Comment by mohantym** [comment]
@zzz7net ,We will definitely track this issue . Feel free to close this issue if it helped!

**Comment by zzz7net** [comment]
As far as I know it will be closed automatically after some amount of time. But anyway thanks. This was a nice conversation.

**Comment by mohantym** [comment]
Closing the issue as language translation is reflecting after refresh( website lags a bit when connected to VPN ).
