### ISSUE TITLE
ubuntu16.04 GTX1060 cuda8.0 Found 0 targets...

### ISSUE THREAD

**Issue by hammer2505** [tensorflow/tensorflow#5212]
tensorflow$ ./configure ~/Documents/tensorflow ~/Documents/tensorflow
Please specify the location of python. [Default is /home/hammer/anaconda2/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] y
Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /home/hammer/anaconda2/lib/python2.7/site-packages
  /home/hammer/Documents/SSD/caffe/python
Please input the desired Python library path to use.  Default is [/home/hammer/anaconda2/lib/python2.7/site-packages]

/home/hammer/anaconda2/lib/python2.7/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
libcudnn.so resolves to libcudnn.5
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
...........
INFO: All external dependencies fetched successfully.
Configuration finished
GT72VR-6RD:~/Documents/tensorflow$ bazel build -c opt --config=cuda
INFO: Found 0 targets...
INFO: Elapsed time: 1.535s, Critical Path: 0.01s

I get no error, but I don't know what to do.

**Comment by firolino** [comment]
You have to specify at least one target to build, e.g. tensorflow/examples/label_image:label_image or the pip package:
`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

Please follow the next step after ./configure [Installing from sources](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#create-the-pip-package-and-install).

**Comment by hammer2505** [comment]
Thank you. I always think "//" means note
