### ISSUE TITLE
Function call stack: train_function 

### ISSUE THREAD

**Issue by starboyvarun** [tensorflow/tensorflow#52134]
![2](https://user-images.githubusercontent.com/26819449/134773664-3244a63e-aab1-4259-8c1a-27a0fb2b91df.JPG)

Why I am getting this error? any solution?

**Comment by bguetarni** [comment]
It seems that one of your images is corrupted. Check your data.

**Comment by starboyvarun** [comment]
@bguetarni  how to know which one is corrupted ??

**Comment by bguetarni** [comment]
Not easy. Try to make a script that read each one of your images (without display) and check if the image is correctly opened. Seems that your images are JPEG, find a library to open JPEG images and try that.

**Comment by starboyvarun** [comment]
@bguetarni  thank you. actually, I tried running again. Doing a factory reset in google colab and clearing the output. It worked perfectly then.
