### ISSUE TITLE
TF 2.6 OOM Error not happening in TF 2.3

### ISSUE THREAD

**Issue by skrishnanv** [tensorflow/tensorflow#52132]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2.2/8.2.1
- GPU model and memory: NVIDIA GEForce GTX 1060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Code crashes at the end of an epoch when training 
[tf-2-6.log](https://github.com/tensorflow/tensorflow/files/7229788/tf-2-6.log)
with a larger size. In TF2.3, warning was generated but code used to run. Also, I have tried using as below
'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
When I set this env variable and run, the code simple exits after sometime and as far as i can see, the fit function is not called. 
**Describe the expected behavior**
Code is expected to run without crash. In TF 2.3, there is no problem. In tf 2.6, there is a crash.
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Code is same as the keras example below
https://keras.io/examples/vision/image_classification_from_scratch/
Problem occurs at batch size 32. For this batch size, though i get the initial warning about memory,the code does not crash.
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by RomanFoell** [comment]
Hi,

it seems we have a similar error: https://github.com/tensorflow/tensorflow/issues/52123

Best, Roman

**Comment by mohantym** [comment]
Hi @skrishnanv ,Could you try again with 

> batch size =16 

Reference:
https://github.com/tensorflow/models/issues/8487

You can also stop the  memory growth using commands in below link
https://forums.developer.nvidia.com/t/tensorflow-python-framework-errors-impl-resourceexhaustederror/155746

**Comment by skrishnanv** [comment]
Hi,
I have tried with batch size 16 and 24. There is no problem.
I have also stopped the memory growth. It does not help for 2.6.
For 2.3 everything works fine(no crash).
Thanks

**Comment by RomanFoell** [comment]
I get a GPU OOM also when I use model.predict(x_input,batch_size = batch_size) with batch_size =1.

The training is gone through with batch-size 40.

x_input was also the training-input with size [5704,122,242,1]. First index is training-amount.

Even more strange is the fact, that when I  try the same code for different times, it sometimes works, sometimes crashes (model.predict with batch-size 1).

I load the saved model with:

```
strategy = tensorflow.distribute.MirroredStrategy(cross_device_ops=tensorflow.distribute.HierarchicalCopyAllReduce())
    
## Open a strategy scope
with strategy.scope():

    ## load model
    if load_model == 1:
        model.load_weights(save_load_path_model + load_model_name + '.h5')
        
    ## compile model
    loss = tensorflow.keras.losses.MeanSquaredError(name='MeanSquaredError')
        autoencoder.compile(loss=loss, metrics=[tensorflow.keras.metrics.BinaryCrossentropy()])
```


(see also, as already mentioned: https://github.com/tensorflow/tensorflow/issues/52123)

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue! providing GIST in TF [2.5](https://colab.research.google.com/gist/mohantym/2e27202a8a28595da1cc2c4e3b732c4b/image_classification_from_scratch.ipynb#scrollTo=82v3sePkvlva) ,[2.6](https://colab.research.google.com/gist/mohantym/37aecab0cc4b784f56b470b9c0ec65ff/image_classification_from_scratch.ipynb#scrollTo=Dw0o6l9Evlvb) and [2.7 ](https://colab.research.google.com/gist/mohantym/2c5f96c5438653643456e2fec5c15a46/image_classification_from_scratch.ipynb#scrollTo=64m-_h9pvlvb)for reference . Training took a bit longer time and does not seem to replicate in Colab Environment.
