### ISSUE TITLE
When does tensorflow 2.x support crf？

### ISSUE THREAD

**Issue by colynhn** [tensorflow/tensorflow#52139]
In view of the fact that the crf implemented by tensorflow addons or implemented by ourselves are integrated into the tensorflow 2.x framework is not friendly, so, when will tensorflow 2.x support crf?

**Comment by mohantym** [comment]
Hi @colynhn! ,Could you please fill the template for[ feature request](https://github.com/tensorflow/tensorflow/issues/new/choose) from here as It will help us track and expedite the feature request.

**Comment by colynhn** [comment]
@mohantym Is asking me to resubmit an issue according to the template for feature request？

**Comment by mohantym** [comment]
Hi @colynhn ! It was request for specific instructions .Actually I looked into this issue earlier from [here ](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/CRF) , As you said CRF is already part of add-ons. We will be able to help the community better if you provide specific instructions in form of template.
