### ISSUE TITLE
build failed with bazel 4.2.1 ( windows 10 )

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#52131]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7.0rc0
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): Visual Studio 2019
- CUDA/cuDNN version: 11.4 / 8.2.6
- GPU model and memory: RTX3090 GDDR6X 24GB

**Describe the problem**

build error (permission)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel build --copt=-nvcc_options=disable-warnings --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
INFO: Repository llvm-project instantiated at:
  D:/repo/tensorflow/WORKSPACE:15:14: in <toplevel>
  D:/repo/tensorflow/tensorflow/workspace2.bzl:1090:21: in workspace
  D:/repo/tensorflow/tensorflow/workspace2.bzl:654:15: in _tf_repositories
  D:/repo/tensorflow/third_party/llvm/setup.bzl:10:19: in llvm_setup
Repository rule llvm_configure defined at:
  C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/configure.bzl:83:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'D:/anaconda3/python.exe C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw --overlay C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-project\\.bazelignore'

ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'D:/anaconda3/python.exe C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw --overlay C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-project\\.bazelignore'

ERROR: D:/repo/tensorflow/tensorflow/tools/pip_package/BUILD:278:10: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/compiler/mlir/tensorflow:gen_mlir_passthrough_op_py in repository @ which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'D:/anaconda3/python.exe C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw --overlay C:/users/alanp/_bazel_alanp/ibqopsat/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\alanp\_bazel_alanp\ibqopsat\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\alanp\\_bazel_alanp\\ibqopsat\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 110.401s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (53 packages loaded, 14 targets configured)
    currently loading: tensorflow/lite/python ... (2 packages)
    Fetching @flatbuffers; fetching
    Fetching ...uffers; Extracting C:/users/alanp/_bazel_alanp/ibqopsat/external/flatbuffers/temp10953078659403648945/\
v1.12.0.tar.gz
```

**Comment by alanpurple** [comment]
same with bazel 3.7.2

2.6.0 had no problems like this

**Comment by sushreebarsa** [comment]
@alanpurple We see that you are using` tf-nightly` version(2.7.0rc0) which is not stable release. Could you please try to  Build from [Source](https://www.tensorflow.org/install/source) using Latest Stable version of TF 2.6.0 and let us know if the issue still persists? Thank you!

**Comment by alanpurple** [comment]
@sushreebarsa I've already told......   see the upper comment

**Comment by sushreebarsa** [comment]
@alanpurple Could you please let us know if we can close the issue?Thanks!

**Comment by jkooooo99** [comment]
ERROR: An error occurred during the fetch of repository 'llvm-project'

I have the same problem with master branch(2.6)!!!!!!!!!!!!

win10      bazel 3.7.2   vs2019

I followed everything in offical website but I still have this problem......

sorry for my english

`Repository rule llvm_configure defined at:
  C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/utils/bazel/configure.bzl:83:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'C:/Users/admin/AppData/Local/Programs/Python/Python38/python.exe C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw --overlay C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:`

**Comment by jkooooo99** [comment]
~~~
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/f6def0e40525562b44741e9c489a26f74183f250.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
    Fetching @llvm-raw; fetching 43s
    Fetching ...vm-raw; Extracting C:/users/admin/_bazel_admin/xv6zejqw/external/llvm-raw/temp17527059103751939930/90b\
abc86c3feda7f9395b36ccfe72ca61bbc39e2.tar.gz 18s
~~~

Could it be the link of "llvm" down?

**Comment by sanatmpa1** [comment]
@alanpurple,

As it looks like a permission error, Can you confirm if you have tried running the command prompt as admin? Thanks!

**Comment by alanpurple** [comment]
@sanatmpa1 

executing powershell with admin privilege solved this
of course "nogcp" & "nonccl" options still not work in windows

It seems that bazel&llvm now needs admin privilege execution

**Comment by sanatmpa1** [comment]
@alanpurple,

Glad that your problem is solved with admin privilege, infact I have also advised to run with admin privilege in this [comment](https://github.com/tensorflow/tensorflow/issues/52131#issuecomment-940185962) as it looked like a permission error.

Can you confirm if we are good to close this issue? Thanks!

**Comment by alanpurple** [comment]
closing, but isn't this still a problem? ( since admin privilege wasn't needed before )

I mean, bazel's problem

**Comment by OgreTransporter** [comment]
Admin privilege needed:

TensorFlow:
> closing, but isn't this still a problem? ( since admin privilege wasn't needed before )
> 
> I mean, bazel's problem

Bazel:
> If the tool requires admin privilege to run, then it's not a Bazel bug, I don't think there is anything we can do from the Bazel side.

Solution:
