### ISSUE TITLE
Restart kernel (Ipython Konsole in Spyder 5.1.5) with os._exit(0) does not work when using tensorflow.distribute.MirroredStrategy

### ISSUE THREAD

**Issue by RomanFoell** [tensorflow/tensorflow#52135]
Hi together,

I have installed

****System information**
- OS Platform and Distribution: Windows Server 2016
- TensorFlow installed from: binary? (conda install)
- TensorFlow version: 2.6.0
- Python version: 3.9.7
- Installed using: pip & conda
- Bazel version: ?
- GCC/Compiler version:  4.7.0 20111220
- CUDA/cuDNN version: 8.1.0.77 & 11.2.2
- GPU model and memory:  2xTesla M60, 2x8gb**

**When I use the code:

```
import tensorflow
import os

os._exit(0)
```

in Spyder 5.1.5 the kernel (IPython-Konsole) gets restarted without problems.

When I use the code:

```
import tensorflow
import os

strategy = tensorflow.distribute.MirroredStrategy(cross_device_ops=tensorflow.distribute.HierarchicalCopyAllReduce())

os._exit(0)
```

in Spyder 5.1.5 the kernel (IPython-Konsole) could not be restarted properly.

The error message which is displayed is:

```
**Beim Starten des Kernels ist ein Fehler aufgetreten** (GERMAN)

2021...15:44:01.699142: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance‑critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021...15:44:02.898151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6938 MB memory: ‑> device: 0, name: Tesla M60, pci bus id: 0000:04:00.0, compute capability: 5.2
2021...15:44:02.903256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 6939 MB memory: ‑> device: 1, name: Tesla M60, pci bus id: 0000:05:00.0, compute capability: 5.2
```
**

I want to quit and restart a kernel session when a condition in the training arises to start the current script from new. (GPU memory etc. gets released with a restart)

Why is this behaviour and how can I get around this, thanks?

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue ? .

**Comment by sanatmpa1** [comment]
@RomanFoell,

I tried replicating it with Spyder 4.2.1, but I am not getting the error mentioned. By any chance can you try with spyder `4.2.1` and let us know if you're facing the same?

**Comment by RomanFoell** [comment]
Hi sanatmpa1,

I did not try it on my Remote Server, so the setting in my first post, but I tried it on my Laptop:

****System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary? (conda install)
- TensorFlow version: 2.6.0
- Python version: 3.9.7
- Installed using: pip & conda
- Bazel version: ?
- GCC/Compiler version:  10.2.0
- CUDA/cuDNN version: 8.2.1 & 11.0.221
- GPU model and memory:  no GPU**

Error for the same code with Spyder 5.1.5:

`An error ocurred while starting the kernel
202117:34:51.150757: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
202117:34:51.150866: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
202117:34:51.158362: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: RT‑Z0M6A
202117:34:51.158967: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: RT‑Z0M6A
202117:34:51.159515: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance‑critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.`

When I use Spyder 4.2.1, the kernel gets frozen with no error message, but no restart of the kernel.

Do you need any further information. Package list or something like that?

Thanks, Roman

**Comment by sanatmpa1** [comment]
@RomanFoell,

As per this [comment](https://github.com/spyder-ide/spyder/issues/16561#issuecomment-947891068), It has been addded to milestone of spyder for 5.2.1 release. Can you close this issue for now and you can create a new one in future if you want to report any issues from TF end. Thanks!
