### ISSUE TITLE
Unable to run "bazel build tensorflow/examples/image_retraining:retrain

### ISSUE THREAD

**Issue by QuantumTCode** [tensorflow/tensorflow#5214]
Hello! I was running the tensorflow example to retrain, and I got this error.

/Users/student/Downloads/tf/tensorflow/core/BUILD:1030:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/student/Downloads/tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/student/Downloads/tf/tensorflow/core/BUILD:1030:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/student/Downloads/tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/student/Downloads/tf/tensorflow/core/BUILD:1030:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/student/Downloads/tf/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/examples/image_retraining:retrain' failed; build aborted.
INFO: Elapsed time: 1.020s

Does anyone know what I am doing wrong?

**Comment by drpngx** [comment]
Could it possibly be that you have an incomplete working copy of tensorflow?

**Comment by QuantumTCode** [comment]
I downloaded tensorflow from [https://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow), and then immediately followed the instructions of the tutorial at [https://www.tensorflow.org/versions/r0.11/how_tos/image_retraining/index.html](https://www.tensorflow.org/versions/r0.11/how_tos/image_retraining/index.html).

**Comment by drpngx** [comment]
Just to be clear, you ran configure?

**Comment by QuantumTCode** [comment]
I ran configure, and now it's working. 

Thank you very much!

**Comment by SJTUzhanglj** [comment]
Hello, i met the same problem with you. I followed the installation instruction of the pip install way, so the tensorflow is located in usr/local/lib and no configure file available. Can you show me your solution on this in detail? @QuantumTCode @drpngx

**Comment by QuantumTCode** [comment]
I ran `./configure` in terminal of the main tensorflow directory.

**Comment by gitDawn** [comment]
Hi, I've the same problem with the installation, but when I'm trying to run './configure' in Ubuntu terminal I'm getting "./configure: No such file or directory". @QuantumTCode

**Comment by drpngx** [comment]
you have to run that from the main tensorflow directory, as pointed out above. If you don't have it, then you have an incomplete version of the code.

**Comment by gitDawn** [comment]
@drpngx  I've installed tensorflow-0.12.1 in windows as described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md).
After the installation is complete, I can't find the configure file in 
C:\Program Files\Anaconda3\Lib\site-packages\tensorflow.

Below is the package information I'm getting from pip.

```
> C:\WINDOWS\system32>pip show tensorflow
> Name: tensorflow
> Version: 0.12.1
> Summary: TensorFlow helps the tensors flow
> Home-page: http://tensorflow.org/
> Author: Google Inc.
> Author-email: opensource@google.com
> License: Apache 2.0
> Location: c:\program files\anaconda3\lib\site-packages
> Requires: numpy, wheel, protobuf, six
```

**Comment by drpngx** [comment]
This is a binary release, you need to build from source

**Comment by ammarasmro** [comment]
Can you please provide how you filled the configure file?

**Comment by luoken** [comment]
when promped to input I actually just did where python 2.7 was installed and it worked...

**Comment by aph3xtwink** [comment]
please can you show how you ran ./configure in the terminal, with your tensorflow directory? I'm confused about how to do that.
