### ISSUE TITLE
tf.matmul returns wrong results if called within tf.vectorized_map

### ISSUE THREAD

**Issue by mganahl** [tensorflow/tensorflow#52148]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- macOS Big Sure, Version 11.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: 3.8.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tf.matmul(a,b, transpose_a=False, transpose_b=True)` returns wrong result for `a,b` of complex
dtypes if wrapped with `tf.vectorized_map`. In fact, `tf.matmul(a,b, transpose_a=False, transpose_b=True)` returns the result expected from the call `tf.matmul(a,b, adjoint_a=False, adjoint_b=True)`, and vice versa.
**Describe the expected behavior**
`tf.matmul(a,b, transpose_a=False, transpose_b=True)` should return `a@b.T` if wrapped in `tf.vectorized_map`

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
```python 
import tensorflow as tf
import numpy as np
def matmul_adjoint(args):
    t1, t2 = args
    return tf.matmul(t1, t2, adjoint_a=False, adjoint_b=True)


def matmul_transpose(args):
    t1, t2 = args
    return tf.matmul(t1, t2, transpose_a=False, transpose_b=True)

def test_vectorized_matmul(dtype):
    rdtype= np.ones(0, dtype).real.dtype
    if dtype in (np.complex64, np.complex128):
        a = np.random.rand(2,4,4).astype(rdtype) + 1j * np.random.rand(2,4,4).astype(rdtype)
        b = np.random.rand(2,4,4).astype(rdtype) + 1j * np.random.rand(2,4,4).astype(rdtype)
    else:
        a = np.random.rand(2,4,4).astype(rdtype) 
        b = np.random.rand(2,4,4).astype(rdtype)
    A = tf.convert_to_tensor(a, dtype=dtype)
    B = tf.convert_to_tensor(b, dtype=dtype)
    result_adjoint = tf.vectorized_map(matmul_adjoint,(A,B))
    result_transpose = tf.vectorized_map(matmul_transpose,(A,B))
    expected_transpose = []
    for n in range(2):
        expected_transpose.append(a[n] @ b[n].T)
    expected_transpose = np.stack(expected_transpose)
    expected_adjoint = []
    for n in range(2):
        expected_adjoint.append(a[n] @ (b[n].T.conj()))
    expected_adjoint = np.stack(expected_adjoint)
    eps = np.finfo(rdtype).eps
    try:
        np.testing.assert_allclose(result_adjoint, expected_adjoint, 
                                   atol=10*eps, rtol=10*eps)
    except AssertionError as err:
        print(''.join(['#']*60))
        print(f"matmul adjoint test failed failed for dtype {dtype} with error {err}")
    try:
        np.testing.assert_allclose(result_transpose, expected_transpose, atol=10*eps, rtol=10*eps)
    except AssertionError as err:
        print(''.join(['#']*60))
        print(f"matmul_transpose failed for dtype {dtype} with error {err}")
      
    # the following passes, so it seems that the transpose and adjoint arguments
    # to tf.matmul need to be swapped
    np.testing.assert_allclose(result_adjoint, expected_transpose, 
                               atol=10*eps, rtol=10*eps)
    
    np.testing.assert_allclose(result_transpose, expected_adjoint, 
                               atol=10*eps, rtol=10*eps)
    
test_vectorized_matmul(np.float32)
test_vectorized_matmul(np.complex64)

```

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
I was able to reproduce the issue in tf v2.5, v2.6 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/dc2cc8f88a4ed682904f6a05123202ec/52148.ipynb).

**Comment by sachinprasadhs** [comment]
Hi, Could you please refer the comment here https://github.com/tensorflow/tensorflow/issues/55639#issuecomment-1233238644 which explains about the possible reasons for vectorized_map issues with different OPS.

**Comment by bhack** [comment]
> Hi, Could you please refer the comment here [#55639 (comment)](https://github.com/tensorflow/tensorflow/issues/55639#issuecomment-1233238644) which explains about the possible reasons for vectorized_map issues with different OPS.

I don't think it is related. It is the impl of the converter:
https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/python/ops/parallel_for/pfor.py#L2695-L2746

/cc @ishark

**Comment by refraction-ray** [comment]
the error is still there in 2.17.1
