### ISSUE TITLE
More than 20% of video memory missing both Linux and Windows [RTX 3080]

### ISSUE THREAD

**Issue by rudimytro** [tensorflow/tensorflow#52140]
### **System information**
**- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
This is the same for my custom code and for simple scripts while setting GPU in TensorFlow. 
**- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
This was tested on Windows 10 and Linux Ubuntu 20.04
**- TensorFlow installed from (source or binary):**
TensorFlow installed from binary.
**- TensorFlow version (use command below):**
This was tested on 2.5.0, 2.5.1 and 2.6.0
**- Python version:**
Python 3.8.10
**- CUDA/cuDNN version:**
Tested on 
Cuda Toolkit: 11.2, 11.4
CuDNN: 8.1.0, 8.1.1, 8.2.4
**- GPU model and memory:**
MSI RTX 3080 10GB memory

### **Describe the current behavior**
I have a 10GB 3080RTX GPU, NVidia-smi reports 10014MiB memory, Tensorflow reports:
> Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7591 MB memory

After initial research I was convinced that this is related to Windows 10 OS limitations, so I installed Ubuntu 20.04 in dual boot. It didn't change anything, I tried various versions of Tensorflow, Cuda, Cudnn.
I tried using:

```
physical_devices = tf.config.list_physical_devices('GPU')
for gpu_instance in physical_devices:
    tf.config.experimental.set_memory_growth(gpu_instance, True)

```

It didn't fix the problem. Also, I tried :

```
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 1.0
session = InteractiveSession(config=config)

```
And indeed, TensorFlow started to report proper full 10GB of memory in 'Created device' message, so tf should see the memory properly. With this method I was able to push memory to almost 8GB and it even allowed me to run slightly higher batch size. But, if I specify fraction of more than 0.8 (it may slightly vary from run-to-run) than i have:
> 2021-09-26 12:48:26.691479: F tensorflow/core/util/cuda_solvers.cc:115] Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.

One important thing to note, while TensorFlow is reporting a device with ~7.5GB, in nvidia-smi it is reporting more than 9GB by /usr/bin/python3! I am not running any other Python script in parallel. 

![Screenshot from 2021-09-26 12-53-00](https://user-images.githubusercontent.com/13711526/134804804-3dced212-188e-4e49-881e-d19e7e6c8d90.png)

So, the memory usage in reality is reaching its limits while I am able to use only 7.5GB, which is even less than known 81% limitation for Windows 10 users! Why am I being allocated almost extra 2GB on top which I can't even use for training?

I was trying to fix it for a long time and really don't have any idea what to do now. Other people's problems with missing tf memory that I found on Internet were related to Windows OS, mine is not. Am I missing something? I would really appreciate any idea on what is going on.
Thank you in advance.

**Comment by RomanFoell** [comment]
Have you tried:

```
gpus = tensorflow.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tensorflow.config.experimental.set_virtual_device_configuration(gpu, [tensorflow.config.experimental.VirtualDeviceConfiguration(memory_limit=10000)])
```

**Comment by Valret** [comment]
> Have you tried:
> 
> ```
> gpus = tensorflow.config.experimental.list_physical_devices('GPU')
> for gpu in gpus:
>     tensorflow.config.experimental.set_virtual_device_configuration(gpu, [tensorflow.config.experimental.VirtualDeviceConfiguration(memory_limit=10000)])
> ```

I tried this and it is having similar effect to

`config.gpu_options.per_process_gpu_memory_fraction = 1.0
`

Basically, if I Specify something slightly higher like 8500 I get:

> 2021-09-26 14:03:44.463333: F tensorflow/core/util/cuda_solvers.cc:115] Check failed: cusolverDnCreate(&cusolver_dn_handle) == CUSOLVER_STATUS_SUCCESS Failed to create cuSolverDN instance.

If I try to allocate almost the totality of ram by setting 10000 for VirtualDeviceConfiguration or 1.0 for per_process_gpu_memory_fraction than I get something like:

> 2021-09-26 14:07:49.020930: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 9.78G (10501423104 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
> ...
> 2021-09-26 14:07:52.205567: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
> ...
> tensorflow.python.framework.errors_impl.InternalError: Blas xGEMM launch failed : a.shape=[1,1,512], b.shape=[1,512,512], m=1, n=512, k=512 [Op:MatMul]

**Comment by Valret** [comment]
Small Update:
When I installed tf 2.4.x I get 

> Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8703 MB memory
This is looking much more acceptable, but I can't train anything because of:

> 2021-09-27 02:05:29.061057: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> ...
> tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

May be the compatibility issue with my cuda version, but I can't downgrade it much because of rtx3000 card support. I have a feeling that something in cuda/tensorflow allocates 2GB for some compatibility thing with rtx3000, but does it really need that much? I would appreciate if owners of those cards would reach out with their status.

**Comment by Valret** [comment]
**Update 2:**

I tested some networks on PyTorch 1.9.1 + CUDA 11.1 and facing similar issue. For example, on Windows right before running the script I have  520MiB / 10240MiB allocated:

![image](https://user-images.githubusercontent.com/13711526/135730824-6d366c9b-fb46-4711-b04e-f3b5fdb05b4f.png)

After I run the training I get:

> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.00 GiB total capacity; 7.39 GiB already allocated; 0 bytes free; 7.44 GiB reserved in total by PyTorch)

nvidia-smi shows that almos all available memory is allocated:

![image](https://user-images.githubusercontent.com/13711526/135730828-e51d63a0-0514-4aa1-8c25-af7e9174481e.png)

PyTorch info:
![image](https://user-images.githubusercontent.com/13711526/135730831-7dc52bff-02a9-49b9-b495-d84a27eb05a1.png)
So again very similar issue. Pytorch allocated  7.39 GiB, nvidia-smi shows memory usage increased by ~9.5GiB after I launched the script, extra 2GB is taken for unknown reason, as with TensorFlow. I wrote to Nvidia but they didn't give me definitive answer by now, maybe people who work on Tensorflow+CUDA side of things know what to say about this?

**Comment by tulbureandreit** [comment]
Any updates? @Valret

**Comment by sachinprasadhs** [comment]
Could you please try using the latest Tensorflow version for windows which can be installed with WSL2. 
Also, from TensorFlow 2.12 CUDA and CuDNN dependency has been upgraded to 11.8 and 8.6 respectively.
Refer the document here for installation instructions https://www.tensorflow.org/install/pip and let us know if you observe the same behavior in the latest Tensorflow version. Thanks!

**Comment by rafyakbar** [comment]
same issue
