### ISSUE TITLE
tensorFlow.compat.v1 no module named compat

### ISSUE THREAD

**Issue by SHILPASHIVAMALLU** [tensorflow/tensorflow#52147]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are
not verified bugs in TensorFlow, please go to
[Discourse](https://discuss.tensorflow.org/).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by SHILPASHIVAMALLU** [comment]
using tensorflow 2.6 , python 3.9. running generate_tfrecord.py file in pycharm . Getting no module compat found error. Any idea how to resolve this issue

**Comment by tilakrayal** [comment]
@SHILPASHIVAMALLU ,
Can you please refer this [link](https://github.com/tensorflow/tensorflow/issues/50121) with similar error.It helps.Also, In order to expedite the trouble-shooting process, could you please provide a complete code you are using.Thanks!
