### ISSUE TITLE
Keras model saved with user-defined signature works with TensorFlow Serving but not Python

### ISSUE THREAD

**Issue by dwyatte** [tensorflow/tensorflow#52156]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Any
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): TensorFlow 2.6 and Nightly
- Python version: Python 3.7
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When manually specifying the signature in [tf.keras.Model.save](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save) a correct model that works with TensorFlow Serving is saved. However, when reloading the same model in Python, TensorFlow tries to execute the incorrect concrete function.

In the example below, I create a model that accepts a `[None, 4]` input but when saving, change it to a `[None, 2]` input that I simply concatenate along `axis=1` to turn it into a `[None, 4]` input. TensorFlow Serving can run this model without problems, but reloading the model with `restored_model = tf.keras.model.load_model(...)` and calling the restored model as a function incorrectly tries to run a function that expects a `[None, 4]` input instead of my user-specified one that expects a `[None, 2]` input.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


input_name = "abc"

#####################################################################################################
# model that accepts [None, 4] input
#####################################################################################################
class MyModel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.x = tf.keras.layers.Dense(1)

    def call(self, inputs, training=None):
        return self.x(inputs[input_name])


inputs = tf.data.Dataset.from_tensor_slices(({input_name: [[1, 2, 3, 4]]}, [1])).batch(1)
model = MyModel()
model.compile(loss="binary_crossentropy", optimizer="sgd")
model.fit(inputs)
model.save("4d_model")
#####################################################################################################


#####################################################################################################
# override the signature to accept [None, 2] and simply concatenate it into [None, 4] for the model
#####################################################################################################
@tf.function(input_signature=[tf.TensorSpec([None, 2], dtype=tf.int32, name=input_name)])
def serve(x):
    return model({input_name: tf.concat((x, x), axis=1)})

model.save("2d_model", signatures={"serving_default": serve})
#####################################################################################################

restored_model = tf.keras.models.load_model("2d_model")
x = next(iter(tf.data.Dataset.from_tensor_slices({input_name: [[1, 2]]}).batch(1)))
outputs = restored_model(x)  # incorrectly requires [None, 4] instead of [None, 2]
```

```python
>>> print(restored_model.signatures["serving_default"].structured_input_signature)
((), {'abc': TensorSpec(shape=(None, 2), dtype=tf.int32, name='abc')})
```

**Other info / logs** Include any logs or source code that would be helpful to
```
ValueError: Exception encountered when calling layer "my_model" (type MyModel).

Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * {'abc': <tf.Tensor 'inputs:0' shape=(1, 2) dtype=int32>}
    * False
  Keyword arguments: {}

 Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (2 total):
    * {'abc': TensorSpec(shape=(None, 4), dtype=tf.int32, name='inputs/abc')}
    * False
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * {'abc': TensorSpec(shape=(None, 4), dtype=tf.int32, name='inputs/abc')}
    * True
  Keyword arguments: {}

Option 3:
  Positional arguments (2 total):
    * {'abc': TensorSpec(shape=(None, 4), dtype=tf.int32, name='abc')}
    * False
  Keyword arguments: {}

Option 4:
  Positional arguments (2 total):
    * {'abc': TensorSpec(shape=(None, 4), dtype=tf.int32, name='abc')}
    * True
  Keyword arguments: {}

Call arguments received:
  • args=({'abc': 'tf.Tensor(shape=(1, 2), dtype=int32)'},)
  • kwargs={'training': 'None'}
```

**Comment by mohantym** [comment]
Hi @dwyatte! ,Could you please look at  these similar issues  [link1](https://github.com/tensorflow/tensorflow/issues/37973),[link2](https://stackoverflow.com/questions/58575586/could-not-find-matching-function-to-call-loaded-from-the-savedmodel)

**Comment by dwyatte** [comment]
Update: It looks like I can use `restored_model.signatures["serving_default"](abc=tf.constant([[1, 2,]]))` to include run user-defined signature in Python. This makes sense to me and should be sufficient for my use case.

**Comment by Crazy-LittleBoy** [comment]
> Update: It looks like I can use `restored_model.signatures["serving_default"](abc=tf.constant([[1, 2,]]))` to run the user-defined signature in Python. This makes sense to me and should be sufficient for my use case.

thx, bro
