### ISSUE TITLE
Building failure of libtensorflowlite_gpu_delegate.so

### ISSUE THREAD

**Issue by mpromonet** [tensorflow/tensorflow#52155]
**System information**
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6.0
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0

**Describe the problem**
Building libtensorflowlite_gpu_delegate.so fails complaining about `absl::Status`.
However building libtensorflowlite_c.so works well (using `bazel build -c opt tensorflow/lite/c:libtensorflowlite_c.so`)

Using lastest or v2.5.0 also fails.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
git clone https://github.com/tensorflow/tensorflow -b v2.6.0   
cd tensorflow  
bazel build -c opt tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```

**Any other info / logs**

```
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=201
INFO: Reading rc options for 'build' from /home/michel/gin-tflite/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/michel/gin-tflite/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Found applicable config definition build:short_logs in file /home/michel/gin-tflite/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/michel/gin-tflite/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/michel/gin-tflite/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /home/michel/gin-tflite/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/michel/.cache/bazel/_bazel_michel/2729c94059558bc79129827a71924973/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/michel/gin-tflite/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/michel/gin-tflite/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /home/michel/.cache/bazel/_bazel_michel/2729c94059558bc79129827a71924973/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/michel/.cache/bazel/_bazel_michel/2729c94059558bc79129827a71924973/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/michel/gin-tflite/tensorflow/tensorflow/lite/delegates/gpu/gl/BUILD:48:11: C++ compilation of rule '//tensorflow/lite/delegates/gpu/gl:api2' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 43 argument(s) skipped)
In file included from external/opencl_headers/CL/cl.h:32,
                 from ./tensorflow/lite/delegates/gpu/api.h:42,
                 from ./tensorflow/lite/delegates/gpu/gl/api2.h:23,
                 from tensorflow/lite/delegates/gpu/gl/api2.cc:16:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |                                                                                                        ^
In file included from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/EGL/egl.h:39,
                 from ./tensorflow/lite/delegates/gpu/gl/portable_gl31.h:21,
                 from ./tensorflow/lite/delegates/gpu/api.h:50,
                 from ./tensorflow/lite/delegates/gpu/gl/api2.h:23,
                 from tensorflow/lite/delegates/gpu/gl/api2.cc:16:
./tensorflow/lite/delegates/gpu/api.h:261:17: error: expected unqualified-id before 'int'
  261 |   virtual absl::Status SetInputShape(int index,
      |                 ^~~~~~
./tensorflow/lite/delegates/gpu/api.h:271:17: error: expected unqualified-id before 'int'
  271 |   virtual absl::Status SetInputObjectDef(int index, ObjectDef def) = 0;
      |                 ^~~~~~
./tensorflow/lite/delegates/gpu/api.h:272:17: error: expected unqualified-id before 'int'
  272 |   virtual absl::Status SetOutputObjectDef(int index, ObjectDef def) = 0;
      |                 ^~~~~~
./tensorflow/lite/delegates/gpu/api.h:273:17: error: expected unqualified-id before 'int'
  273 |   virtual absl::Status SetAllInputObjectDefsTo(ObjectDef def) {
      |                 ^~~~~~
```

**Comment by sushreebarsa** [comment]
@mpromonet Could you please have a look at the similar issue [link1,](https://github.com/tensorflow/tensorflow/issues/44926) [link2](https://stackoverflow.com/questions/63438024/using-tensorflow-lite-gpu-delegate-in-androids-native-environment-with-c-api) and let us know if it helps ?Thanks!

**Comment by mpromonet** [comment]
Hi sushreebarsa,

I read these before writing this issue, may you clarify what can helps.
From https://github.com/tensorflow/tensorflow/issues/44926 I tried `bazel build -c opt  --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -s --strip always tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so`, the build error seems the same.

Best Regards,
Michel.

**Comment by freedomtan** [comment]
@mpromonet What do you want? libtensorflowlite_gpu_delegate.so for your machine running Ubuntu 20.04 or or Android platform. 

For the latter case, please run `./configure` and set Android NDK and SDK paths.
For the former one, I guess it's not supported and well-tested. Messages like
```
./tensorflow/lite/delegates/gpu/api.h:261:17: error: expected unqualified-id before 'int'
  261 |   virtual absl::Status SetInputShape(int index,
      |                 ^~~~~~
./tensorflow/lite/delegates/gpu/api.h:271:17: error: expected unqualified-id before 'int'
  271 |   virtual absl::Status SetInputObjectDef(int index, ObjectDef def) = 0;
      |                 ^~~~~~
```
are because of something like `#define Status int` in `X11/Xlib.h`

**Comment by mpromonet** [comment]
Hi freedomtan,

Thanks for your answer, I was trying to build tensorflow lite with gpu support for running it on Ubuntu20.04 not for Android.
It seems the `#define Status int` in `X11/Xlib.h` brings conflict, I tried to put some `#undef Status` build is continuing, but raise others problems with eigen.

Best Regards,
Michel.

**Comment by impjdi** [comment]
Depending on the platform, you may have to define `MESA_EGL_NO_X11_HEADERS` and/or `EGL_NO_X11` which don't include the X11 headers that @freedomtan mentioned above.  Depending on the version of the header file, it may be named slightly differently, so you need to dig into your EGL header files a little bit.

**Comment by mariecwhite** [comment]
I ran into a similar error when building `benchmark_model` with OpenCL on x86. This command worked for me:

```
bazel build -c opt --copt=-DCL_DELEGATE_NO_GL --copt=-DMESA_EGL_NO_X11_HEADERS=1 tensorflow/lite/tools/benchmark:benchmark_model
```

**Comment by WillLiGitHub** [comment]
i had build gpu delegate successfully on ubuntu18.04 with command:
bazel build --local_cpu_resources=3 -s -c opt --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so

but，when i run tflite model on ubuntu18.04 with tflite c++ api, i met some errors:
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:63:9: error: expected unqualified-id before ‘int’
   absl::Status Read(absl::Span<T> data) const;
         ^
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:67:9: error: expected unqualified-id before ‘int’
   absl::Status Write(absl::Span<const T> data);
         ^
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:72:9: error: expected unqualified-id before ‘int’
   absl::Status MappedRead(
         ^
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:78:9: error: expected unqualified-id before ‘int’
   absl::Status MappedWrite(
         ^
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:81:9: error: expected unqualified-id before ‘int’
   absl::Status MakeView(size_t offset, size_t bytes_size, GlBuffer* gl_buffer);
         ^
~/tensorflow_src/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:87:9: error: expected unqualified-id before ‘int’

CMakeLists.txt info:
LINK_DIRECTORIES(~/tensorflow_src/bazel-bin/tensorflow/lite/)
LINK_DIRECTORIES(~/tensorflow_src/bazel-bin/tensorflow/lite/delegates/gpu)
message(${OpenCV_INCLUDE_DIRS})

set(TF_SOURCE_DIR "~/tensorflow_src")
INCLUDE_DIRECTORIES(
        ${CMAKE_CURRENT_SOURCE_DIR}/
        ${TF_SOURCE_DIR}
        ${TF_SOURCE_DIR}/tensorflow
        ${TF_SOURCE_DIR}/tensorflow/lite/tools/make/downloads/absl
        ${TF_SOURCE_DIR}/tensorflow/lite/tools/make/downloads/absl/absl
        ${TF_SOURCE_DIR}/tensorflow/lite/tools/make/downloads/fp16/include
        ${TF_SOURCE_DIR}/tensorflow/lite/tools/make/downloads/flatbuffers/include
        ${TF_SOURCE_DIR}/tensorflow/lite/delegates/
        ${TF_SOURCE_DIR}/tensorflow/lite/delegates/gpu
        ${TF_SOURCE_DIR}/tensorflow/lite/delegates/gpu/common
        ${TF_SOURCE_DIR}/tensorflow/lite/delegates/gpu/gl
        ${OpenCV_INCLUDE_DIRS}
)

anyone have a idea to deal with this problem?
