### ISSUE TITLE
Why does tensorflow only use one GPU, but it takes up two GPUs? 

### ISSUE THREAD

**Issue by wqcsim** [tensorflow/tensorflow#52159]
|=============================================================================|
|    0   N/A  N/A     27330      C   ...envs/p3.8_t2.2/bin/python      249MiB |
|    1   N/A  N/A     27330      C   ...envs/p3.8_t2.2/bin/python     7517MiB |
+-----------------------------------------------------------------------------+

I have two GPUs on my machine. I run the GPU training code and found that the process occupies 2 GUPs. The actual use is the No. 1 GPU, but the No. 0 GUP occupies 249 MiB of memory but is not used. I don’t understand why if only one GPU is used, the other should be occupied? 

**Reproduce the code：**
```python
import tensorflow as tf
import os


mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train[..., tf.newaxis].astype("float32")
x_test = x_test[..., tf.newaxis].astype("float32")

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(10, kernel_size=(3, 3),input_shape=(28, 28, 1)),
  tf.keras.layers.Conv2D(20, kernel_size=(3,3)),
  tf.keras.layers.DepthwiseConv2D(kernel_size=(3,3)),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.summary()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=32, epochs=1)
```

**Comment by yananchen1989** [comment]
Same issue.

I find that even I assign gpu-1 to the model construction, it stills occupy two gpus's memory. Only one gpu has work load.

```
        #with tf.distribute.MirroredStrategy().scope():
        with tf.device('/GPU:{}'.format(1)):
            if model_name == 'albert':
                model = get_model_bert(df_test.label.unique().shape[0])
                
            elif model_name == 'former':
                model = get_model_former(df_test.label.unique().shape[0])
                
            elif model_name == 'cnn':
                model = get_model_cnn(df_test.label.unique().shape[0])
                
            else:
                raise KeyError("input model illegal!")

        history = model.fit(
            x_train, y_train, batch_size=batch_size, epochs=epochs, \
            validation_data=(x_test, y_test), verbose=verbose, validation_batch_size=64,validation_freq=freq
            #callbacks = [EarlyStopping(monitor='val_acc', patience=3, mode='max')]
        )
```

**Comment by wqcsim** [comment]
**Supplement:** When the memory of both GUPs is occupied by other processes, and CUDA_VISIBLE_DEVCES is set to specify any one GUP, the program will throw an exception error. (Normal) However, if the CUDA_VISIBLE_DEVCES variable is not set, the program will segfault and crash directly.

**Comment by Saduf2019** [comment]
@yananchen1989 
You may also refer to [link](https://stackoverflow.com/questions/43577668/tensorflow-seems-to-be-using-two-gpus-but-one-gpu-seems-not-be-doing-anything),[link1](https://jhui.github.io/2017/03/07/TensorFlow-GPU/),[link2](https://datascience.stackexchange.com/questions/90324/why-the-my-tensorflow-code-just-use-one-gpu-when-i-assign-more-than-one)

**Comment by yananchen1989** [comment]
@Saduf2019  Thanks, Very helpful.

**Comment by wqcsim** [comment]
@Saduf2019 
Thank you for your answers, but my problem is not to use multi-GPU training. The issues is that Tensorflow uses GUP0 by default but occupies some memory of GUP1, and when both GPU memory is occupied by other processes, run training script will segfault instead of throwing an exception.

**Comment by Saduf2019** [comment]
@wqcsim 
That is how any computer device would work [be it cpu,gpu,tpu]
Both GPU memories are full and you try to run another script obviously it will crash, kindly move tihs to closed status and create an issue on discussion forum as there is a larger community there to support.
