### ISSUE TITLE
TensorFlow Lite C library built with CMake, ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

### ISSUE THREAD

**Issue by CarlosYeverino** [tensorflow/tensorflow#52158]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **from Source**
- TensorFlow version: 
- Python version: 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): **GNU 7.5.0**
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
The project I am working on requires the **TensorFlow Lite C API** which I built with **CMake** following this instructions https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library (shared library).

I have built and run pretrained models successfully before, however, I am currently trying to integrate a model that takes 2 images as input such as **HITNet** from google-research group (https://github.com/google-research/google-research/tree/master/hitnet). The model mentioned in the paper is in protobuf format here https://storage.googleapis.com/tensorflow-graphics/models/hitnet/default_models/middlebury_d400.pb, and I found in this repo https://github.com/PINTO0309/PINTO_model_zoo/tree/main/142_HITNET the model converted to tflite model https://drive.google.com/uc?export=download&id=1cqxZ-hCQagdwYQee4U8LsaHAJA3y-Go3

The following error arises when creating the model from file with `TfLiteModelCreateFromFile`:
```
ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
ERROR: Node number 271 (FlexStridedSlice) failed to prepare.
```

_**How to add support of Select TensorFlow op(s)/Flex delegate to TensorFlow Lite C API with CMake?**_
I didn't find any suggestion for C API in https://www.tensorflow.org/lite/guide/ops_select

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`TfLiteModel* model = TfLiteModelCreateFromFile((test_data_dir() + "/tflite_hitnet_model/hitnet_model_float32_480x640.tflite").c_str());`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by thaink** [comment]
It can be used in the same way as with C++ API. Just build https://www.tensorflow.org/lite/guide/ops_select#c and load it then It should work fine.

**Comment by CarlosYeverino** [comment]
@thaink thanks for your reply.

The solution you mentioned is based on **bazel**. Any plans to provide a solution for **CMake**?

**Comment by miaout17** [comment]
My understanding is that the Flex (Select TensorFlow ops) feature is supported by neither CMake, nor the Makefile build process that CMake replaced. It would be a significant amount of engineering effort to make the entire TensorFlow buildable with CMake on mobile, and there is no plan for this yet. 

The best way to use Flex delegate is sticking with Bazel build. 

Tagging @terryheo who works on CMake build -- Please correct me if I'm wrong.

**Comment by terryheo** [comment]
@miaout17 is correct. To support CMake for Flex, we need a CMake rule for TensorFlow kernels. They used to exist but it's not available now.

If you can remove Flex usage, you can avoid this issue. I wonder why your model requires FlexStridedSlice since StridedSlice is also available for TFLite.

**Comment by chunduriv** [comment]
@CarlosYeverino, Did you refer solutions discussed [here](https://github.com/tensorflow/tensorflow/issues/52158#issuecomment-932659820), [here](https://github.com/tensorflow/tensorflow/issues/52158#issuecomment-932743058)?  Can you let us know why your model requires FlexStridedSlice since StridedSlice is also available for TFLite?

**Comment by FengMu1995** [comment]
@CarlosYeverino , I wonder how to apply the  Flex with cmake in my own project? Could you give me a reference of your cmakeLists.txt?
