### ISSUE TITLE
bazel build tensorflow:tensorflow_cc is not working

### ISSUE THREAD

**Issue by kaustubhjirapure** [tensorflow/tensorflow#52163]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6.0
- Python version: 3.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): bazel 3.7.2
- GCC/Compiler version (if compiling from source): 8.1.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

I am using conda environment which does not have tensorflow installed. I am using tensorflow 2.6 from github and building it using bazel.

**Describe the problem**
I am trying to use tensorflow c++ api to simulate tensorflow from python into c++ to simulate tensorflow models using c++. 
I am facing a problem while using bazel to build tensorflow and get .cc and .h files from tensorflow to use in c++ api.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout v2.6

bazel build tensorflow:tensorflow_cc

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
   Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow-master\.bazelrc:
   Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Anaconda3/envs/tfcpp/python.exe                                                     
INFO: Reading rc options for 'build' from d:\tensorflow\tensorflow-master\.bazelrc:                                       
    'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils    

INFO: Found applicable config definition build:short_logs in file d:\tensorflow\tensorflow-master\.bazelrc: --output_filter=DONT_MATCH_ANYTHING                                                                                                 
INFO: Found applicable config definition build:v2 in file d:\tensorflow\tensorflow-master\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1                                                                                       
INFO: Found applicable config definition build:windows in file d:\tensorflow\tensorflow-master\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false                                                                                                   INFO: Found applicable config definition build:monolithic in file d:\tensorflow\tensorflow-master\.bazelrc: --define framework_shared_object=false                                                                                             

WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/8d3c2c75e02d3333df81807ff8f6c64f55353766.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found                                                                                                 

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/efb284c07e97776e01933f470afb5215a561db3e.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found                                                                          

INFO: Repository local_config_python instantiated at:                                                                    
  D:/tensorflow/tensorflow-master/WORKSPACE:15:14: in <toplevel>                                                          
  D:/tensorflow/tensorflow-master/tensorflow/workspace2.bzl:1080:19: in workspace                                         
  D:/tensorflow/tensorflow-master/tensorflow/workspace2.bzl:99:21: in _tf_toolchains                                    
Repository rule python_configure defined at:                                                                              
  D:/tensorflow/tensorflow-master/third_party/py/python_configure.bzl:294:35: in <toplevel>                             

ERROR: An error occurred during the fetch of repository 'local_config_python':                                             
   Traceback (most recent call last):                                                                                          
       File "D:/tensorflow/tensorflow-master/third_party/py/python_configure.bzl", line 267, column 40, in _python_autoconf_impl                                                                                                                               _create_local_python_repository(repository_ctx)                                                                 
       File "D:/tensorflow/tensorflow-master/third_party/py/python_configure.bzl", line 209, column 22, in 
               _create_local_python_repository                                                                                                                     
                  _check_python_bin(repository_ctx, python_bin)                                                                   
       File "D:/tensorflow/tensorflow-master/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin                                                                                                                                   
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])                                    
       File "D:/tensorflow/tensorflow-master/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin                
                bash_bin_path = which(repository_ctx, "bash")                                                                   
       File "D:/tensorflow/tensorflow-master/third_party/remote_config/common.bzl", line 27, column 22, in which                       
                out = execute(                                                                                                  
       File "D:/tensorflow/tensorflow-master/third_party/remote_config/common.bzl", line 230, column 13, in execute                    
                fail(                                                                                                   

Error in fail: Repository command failed                                                                                
INFO: Could not find files for the given pattern(s).                                                                    
INFO: Repository go_sdk instantiated at:                                                                                  
   D:/tensorflow/tensorflow-master/WORKSPACE:23:14: in <toplevel>                                                          
   D:/tensorflow/tensorflow-master/tensorflow/workspace0.bzl:120:20: in workspace                                          
   D:/_bazel/lshsjacg/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps                    
   D:/_bazel/lshsjacg/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains             
   D:/_bazel/lshsjacg/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk                            
Repository rule _go_download_sdk defined at:                                                                              
   D:/_bazel/lshsjacg/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>                                 
ERROR: Analysis of target '//tensorflow:tensorflow_cc' failed; build aborted: Repository command failed                 
INFO: Could not find files for the given pattern(s).                                                                    
INFO: Elapsed time: 288.274s                                                                                            
INFO: 0 processes.                                                                                                      
FAILED: Build did NOT complete successfully (11 packages loaded, 15 targets configured)                                     
    Fetching @local_execution_config_python; fetching                                                                       
    Fetching ...docker; Cloning 9bfcd7dbf0294ed9d11a99da6363fc28df904502 of https://github.com/bazelbuild/rules_docker\ .git 

The warning that "download from....Exception GET returned 404 Not Found",  occurs twice in above trace log. And it occurs everytime I run the same commands.

**Comment by Saduf2019** [comment]
@kaustubhjirapure 
We see this issue is already reported and is work in progress please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/45059) and let us know

**Comment by kaustubhjirapure** [comment]
I have seen the issue and will wait for that issue to be resolved and see if it helps me.
