### ISSUE TITLE
BoostedTreesClassifier Not Progressing Past Step 0

### ISSUE THREAD

**Issue by tcheath** [tensorflow/tensorflow#52165]
OS: macOS Catalina 10.15.7
TF 2.6.0 from binary
Python 3.9.6
Running inside Jupyter Notebook

**Describe the current behavior**
Training a BoostedTreesClassifier based on a transformation of TFRecordsDataset does not progress past step 0, and thus has no trees.  Evaluation results come back as if no prediction is being made and running feature importance afterwords raises an error that says the model must be trained first.

**Describe the expected behavior**
Should train a model with trees, make predictions, and be able to analyze the trees with say experimental_feature_importances

- Do you want to contribute a PR? (yes/no): No

**Code**
```
def parse(record):
    attributes = {feat: tf.io.FixedLenFeature([], tf.float32) for feat in feature_names}
    attributes["label.label_xf"] = tf.io.FixedLenFeature([], tf.int64)

    parsed = tf.io.parse_single_example(record, attributes)
    features = {feat: tf.convert_to_tensor(parsed[feat]) for feat in feature_names}

    return features, tf.convert_to_tensor(parsed["label.label_xf"])

def train_fn():
    train_examples = tf.data.TFRecordDataset(TRAIN_PATH, compression_type="GZIP")
    
    return train_examples.map(parse).batch(train_size)

def eval_fn():
    eval_examples = tf.data.TFRecordDataset(EVAL_PATH, compression_type="GZIP")
    
    return eval_examples.map(parse).batch(eval_size)

btc_est = tf.estimator.BoostedTreesClassifier(feature_columns, 1)

btc_est.train(train_fn, max_steps=10)
```
does not progress beyond step 0, and
`btc_est.evaluate(eval_fn)`
gives results
```
{'accuracy': 0.5158002,
 'accuracy_baseline': 0.51580024,
 'auc': 0.5,
 'auc_precision_recall': 0.7420999,
 'average_loss': 0.69314647,
 'label/mean': 0.4841998,
 'loss': 0.69314647,
 'precision': 0.0,
 'prediction/mean': 0.5,
 'recall': 0.0,
 'global_step': 0}
```
and
```btc_est.experimental_feature_importances()```
raises the error
```ValueError: Found empty serialized string for TreeEnsemble.You should only call this method after training.```
where as a LinearClassifier trained and evaluated in the same way
```
lin_est = tf.estimator.LinearClassifier(feature_columns)

lin_est.train(train_fn)
lin_est.evaluate(eval_fn)
```
yields sensible results that indicate a model has been successfully trained
```
{'accuracy': 0.5897044,
 'accuracy_baseline': 0.5158002,
 'auc': 0.59089816,
 'auc_precision_recall': 0.59708935,
 'average_loss': 0.6869413,
 'label/mean': 0.4841998,
 'loss': 0.6869413,
 'precision': 0.6975477,
 'prediction/mean': 0.49952453,
 'recall': 0.26947367,
 'global_step': 1}
```

**Comment by tilakrayal** [comment]
@tcheath ,
In order to expedite the trouble-shooting process, could you please provide a complete code  and the dataset you are using.Thanks
