### ISSUE TITLE
sparse tensor.shape method returns a tensor object  

### ISSUE THREAD

**Issue by amrit-poudel** [tensorflow/tensorflow#5216]
sparse tensor.shape method returns a tensor object which seems to be of no use to extract the actual shape of the sparse tensor without resorting to run function.

To clarify what I mean, first consider a sparse tensor:

 a = tf.SparseTensor(indices=[[0, 0, 0], [1, 2, 1]], values=[1.0+2j, 2.0], shape=[3, 4, 2])

a.shape returns:

 tf.Tensor 'SparseTensor_1/shape:0' shape=(3,) dtype=int64

This is kind of no use. 

Now, consider a dense tensor:

a = tf.constant(np.random.normal(0.0, 1.0, (4, 4)).astype(dtype=np.complex128))

a.get_shape() returns:
TensorShape([Dimension(4), Dimension(4)])

I can use this output and cast it into a list or tuple of integers without ever invoking run(). However, I cannot do the same for sparse tensor, unless I first convert sparse tensor to dense (which is *not* implemented for complex sparse tensor yet) and then call get_shape() method on it, but this is kind of  redundant, defeats the purpose of using a sparse tensor in the first place and also leads to error down the road if the input sparse tensor is complex.

Is there a way to obtain the shape of a sparse tensor without invoking run() or converting it to a dense tensor first?

**Comment by drpngx** [comment]
Could you post on stackoverflow with tag "tensorflow"? We can continue the discussion there.

**Comment by amrit-poudel** [comment]
posted it on stackoverflow as well. Sorry, I should have posted there directly, but thought this was related to feature request/enhancement, so posted it here. Thanks.

**Comment by drpngx** [comment]
Good point. Let's see what you get on stackoverflow first. If you don't get a pull there, let's continue here.

**Comment by amrit-poudel** [comment]
No reply at stackoverflow yet. Any thoughts?

**Comment by cwhipkey** [comment]
`a.shape` is a Tensor representing the shape that was passed to SparseTensor's constructor.

So `tf.contrib.util.constant_value(a.shape)`   should give the numpy array corresponding to the shape of the sparse tensor.:
```
  a = tf.SparseTensor(indices=[[0, 0, 0], [1, 2, 1]], values=[1.0+2j, 2.0], shape=[3, 4, 2])
  print(tf.contrib.util.constant_value(a.shape))
  print(type(tf.contrib.util.constant_value(a.shape)))

```
Outputs:
```
[3 4 2]
<type 'numpy.ndarray'>
```

**Comment by drpngx** [comment]
@amrit-poudel if you could cross-post the answer to stackoverflow, that would be great. Thanks!
