### ISSUE TITLE
Different prediction on GPU between `tf.keras.models.load_model(..)` and `tf.saved_model.load(..)`

### ISSUE THREAD

**Issue by prakharverma** [tensorflow/tensorflow#52178]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.2
- CUDA/cuDNN version: 11.0
- GPU model and memory: GeForce GTX 1050, 4 GB

**Describe the current behavior**

I have a CNN based regression model. Surprisingly, the model is predicting different outputs when loaded with `tf.keras.models.load_model(..)` and `tf.saved_model.load(..)`. However, this only occurs when I am using a GPU and also not always but ~5% of inference times. On CPU, they both produce the same outputs always. The difference is rather small, happens after `1e-7` but still big for my use case.

**Describe the expected behavior**
Irrespective of the loading method and whether GPU is used for inference or not, predicted values should always be the same.

**Standalone code to reproduce the issue**
The link to colab: `https://colab.research.google.com/drive/1JwXNx-MbVqB7HDXF4z9lqa91oWsfvpA0?usp=sharing`

Colab uses different TF and python versions but the issue still exists.

**Other info / logs** 
`AssertionError: [[0.12652352]] and [[0.12652355]]`

**Comment by jessecantu** [comment]
https://github.com/tensorflow/tensorflow/issues/52178#issue-1010644453

**Comment by jvishnuvardhan** [comment]
@prakharverma Agree with you that there is small discrepancy in 8th decimal of the predictions between tensorflow model and keras model. As the initial model is a keras model, using `load_model` to load model results in identical results when compared to original model. 

I think (may be I am wrong) when you load a keras model as a TF model, under the hood, there might be some conversions happening which are resulting in very small discrepancy of the order of precision/round-off level. 

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/710530887644651324a56fe566532bc1/nightly-and-2-6.ipynb). In the gist, I compared predictions from loaded_keras_model (`trained_model1`) with original `model`. Thanks!

**Comment by prakharverma** [comment]
Hi, @jvishnuvardhan! Thanks for the response! Yes, I agree original model and the Keras load model produces similar results. I just wasn't sure why the tf load model is producing different results, that too not always but only for certain inputs and also the precision varies with inputs. 

Is there a way to set the precision in the tf load model or check where this conversion is happening exactly?

**Comment by jvishnuvardhan** [comment]
@prakharverma When loading keras model as a TF model, there are some conversions required to be compatible as a TF model. I guess one of those conversion steps is introducing this 8th decimal discrepancy some times. I think TF/Keras teams are working on high priority issues so they may not handle this in near future (i guess).

If you have bandwidth, debug the `load_model` path and `tf.saved_model.load` path to find the root-cause and raise a PR to contribute code change. Thanks!
