### ISSUE TITLE
Different results between model.fit() and model.predict()

### ISSUE THREAD

**Issue by houzeyu2683** [tensorflow/tensorflow#52174]
I get the problem when I try to fine-tuned my model.
Here is my `model.fit` code and training progress bar.

![2021-09-29 10-42-31 的螢幕擷圖](https://user-images.githubusercontent.com/42731603/135195990-85ea0501-fd37-4ac9-a575-48a719872c89.png)

![2021-09-29 10-42-46 的螢幕擷圖](https://user-images.githubusercontent.com/42731603/135196092-1e32fdae-5149-445c-a17c-0647512b970d.png)

I found the `keras.losses.CategoricalCrossentropy()` and `keras.metrics.CategoricalCrossentropy()` return different results when training epoch.

Moreover, I use the same validation data in the `model.predict` function, and check the AUC-score, **the socre in the final epoch** and **the score which compute manually** not the same. 

![2021-09-29 10-42-59 的螢幕擷圖](https://user-images.githubusercontent.com/42731603/135196679-a9245642-9a94-4227-94ea-61a3500a9c51.png)

And I research the similar [issue](https://github.com/keras-team/keras/issues/5140]) before, but I didn't found the solution.

Does anyone get the same problem?

OS and environment information:
- Ubuntu 20.04.3 LTS
- Conda virtual environment
- Cuda 11.2
- Nvidia-driver 460
- Tensorflow 2.5.0 (use Keras inside tensorflow)

**Comment by mohantym** [comment]
Hi @houzeyu2683! Could you  please fill the template from [here ](https://github.com/tensorflow/tensorflow/issues/new/choose)and share the complete stand alone code as It will help expedite the issue.
