### ISSUE TITLE
TF not using GPU for models

### ISSUE THREAD

**Issue by Loganpi** [tensorflow/tensorflow#52192]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Latest Windows 10
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4 CUDA, 8.1.0
- GPU model and memory: 3060 12gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Tensorflow uses the cpu when training models and not the gpu. I have installed Cuda and cudnn properly, and TensorFlow confirms the loading of cudnn lib. When I train models, the gpu fan doesn't spin, nor does it heat up, and the cpu shows heavy usage in task manager
**Describe the expected behavior**
TF uses gpu and not cpu
**Standalone code to reproduce the issue**
this is the can notebook I am using:
https://www.tensorflow.org/tutorials/images/cnn

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Loganpi** [comment]
Tensorflow returns 1

**Comment by Saduf2019** [comment]
@Loganpi 
Can you try os.environ["CUDA_VISIBLE_DEVICES"]="0". [if this dis not work please try os.environ["CUDA_VISIBLE_DEVICES"]="" ]

**Comment by Loganpi** [comment]
Hello, in an attempt to solve this problem I moved to linux and setup Tensorflow properly there.
len(tf.config.list_physical_devices('GPU')) gives this error:

E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
