### ISSUE TITLE
NVlink for tensorflow2.5, linux, 3090 GPU

### ISSUE THREAD

**Issue by FavorLionQY** [tensorflow/tensorflow#52208]
OS: Linux Ubuntu18.04
TF building method: TF docker with Nvidia Docker,  CUDA version: 11.1
Version: Tensorflow 2.5.0
GPUs: RTX3090 x2

Hi there.

I noticed that the NVlink for 3090 is published. I got a workstation with 2 3090 GPU cards. I wish to know is it necessary to got a NVlink to accelerate data transfer between these 2 cards?

For tensorflow building via docker, should i install some extra toolkit? And when I train model with MirrowedStrategy, what should I do to activate the NVlink?

**Comment by sushreebarsa** [comment]
@FavorLionQY Sorry for the late response! Could you please refer to the [link ](https://www.tensorflow.org/install/source#linux)to build from source and have a look on the similar issue [link1](https://github.com/tensorflow/tensorflow/issues/36510), [link2 ](https://github.com/tensorflow/tensorflow/issues/34067), [link3 ](https://github.com/tensorflow/tensorflow/issues/43947)for reference .Please let us know if it helps?Thank you!
