### ISSUE TITLE
Could not run the task evaluation!-tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/

### ISSUE THREAD

**Issue by xddcore** [tensorflow/tensorflow#52219]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:tf2.6.0
- Python version:3.7.4
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):3.7.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
When I use **thetensorflow/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/** link tool to build and evaluate my tflite model, it shows that the evaluation task cannot be run. I have confirmed that the file path of all transmission parameters is correct. Hope to get your help!
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

$ bazel run -c opt \
>   -- \
>   //tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification:run_eval \
>   --model_file=mobilenet_224_1_0_INT8.tflite \
>   --ground_truth_images_path=./test/ \
>   --ground_truth_labels=validation_ground_truth.txt \
>   --model_output_labels=mobilenet_labels.txt \
>   --output_file_path=/tmp/accuracy_output.txt \
>   --num_images=0 # Run on all images.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/xdd/project/mobilenet/tf/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/a21c557955c6ea5cd02b9a145ad6469c608446c7.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/ad9981d394f5ccc784d6273e51aa41c38b7cf727.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/xdd/project/mobilenet/tf/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/xdd/project/mobilenet/tf/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  /home/xdd/.cache/bazel/_bazel_xdd/238513a408dfab846cdfe0f15ca64c47/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /home/xdd/.cache/bazel/_bazel_xdd/238513a408dfab846cdfe0f15ca64c47/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/694d2524757f9040e65a02c374e152a462fe57eb.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification:run_eval (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification:run_eval up-to-date:
  bazel-bin/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/run_eval
INFO: Elapsed time: 0.089s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/run_eval '--model_file=mobilenet_224_1_0_INT8.tflite' '--ground_truth_images_path=./test/' '--ground_truth_labels=validation_ground_truth.txt' '--model_output_labels=mobilenet_labels.txt' '--output_file_path=/tmp/INFO: Build completed successfully, 1 total action
Could not run the task evaluation!

**Comment by xddcore** [comment]
I seem to have found the reason for the above problem: because I use the conda environment, I did not use bazel to compile the tool in an environment containing tensorflow. As a result, the tool cannot find tensorflow related dependencies. In the end, the data set could not be verified.
The solution is, if you use anaconda to manage different Python environments, please run the build command in this question log in an environment containing tensorflow to use the corresponding tools.

**Comment by sushreebarsa** [comment]
@xddcore Could you please move this issue to closed status if it has been resolved for you as per the [comment ](https://github.com/tensorflow/tensorflow/issues/52219#issuecomment-932494580)?Thank you!

**Comment by xddcore** [comment]
> @xddcore Could you please move this issue to closed status if it has been resolved for you as per the [comment ](https://github.com/tensorflow/tensorflow/issues/52219#issuecomment-932494580)?Thank you!

ok, thank you for your reply!
