### ISSUE TITLE
Mac m1 tf2.5.0: No layer for IntegerLookup, Normalization, StringLookup

### ISSUE THREAD

**Issue by JTWang2000** [tensorflow/tensorflow#52216]
**System information**
- OS Platform and Distribution: macOS Big Sur Version 11.3.1 with mac m1 chip
- TensorFlow installed from: https://developer.apple.com/metal/tensorflow-plugin/
- TensorFlow version (use command below): tf 2,5
- Python version: 3.8

Debug output:
```
import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION)
```
unknown 2.5.0

**Describe the current behavior**
```
from tensorflow.keras.layers import IntegerLookup
from tensorflow.keras.layers import Normalization
from tensorflow.keras.layers import StringLookup
```
ImportError                               Traceback (most recent call last)
/var/folders/1z/77jbzk11477gc69_s8n2y0r00000gn/T/ipykernel_27569/1759035919.py in <module>
----> 1 from tensorflow.keras.layers import IntegerLookup

ImportError: cannot import name 'IntegerLookup' from 'tensorflow.keras.layers' (/Users/username/miniforge3/envs/env/lib/python3.8/site-packages/tensorflow/keras/layers/__init__.py)

**Standalone code to reproduce the issue**
Follow link https://developer.apple.com/metal/tensorflow-plugin/ to install tf2.5 on mac and then run the import

**Comment by mohantym** [comment]
Hi @JTWang2000 ! Sorry for the late response,Could you try again the imports like below .
```
from tensorflow.python.keras.layers.preprocessing.integer_lookup import IntegerLookup
from tensorflow.python.keras.layers.preprocessing.normalization import Normalization
from tensorflow.python.keras.layers.preprocessing.string_lookup import StringLookup
```
[Reference source code](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/python/keras/layers/__init__.py)

**Comment by JTWang2000** [comment]
Hi @mohantym Thank you so much for your reply. This works!
I also tried with 
```
from tensorflow.keras.layers.experimental.preprocessing import StringLookup, IntegerLookup, Normalization
```
These two commands both work

**Comment by mohantym** [comment]
Ok @JTWang2000 ! Feel free to close this issue if it helped.
