### ISSUE TITLE
Creating dataset from large numpy arrays via from_tensor_slices crashes without any error message or warning

### ISSUE THREAD

**Issue by MattWolf74** [tensorflow/tensorflow#52215]
I use tf 2.6 and when I try to create datasets from larger numpy arrays (>10GB) via from_tensor_slices the code breaks when I try to train via "fit" or even just attempt to iterate over the dataset. The code just breaks and exists, no warning, no error message, nothing. I have not found any similar issue mentioned anywhere else. What is the actual limitation here? 

I have over 128GB ram and due to the code breaking already on the dataset iteration part it is surely unrelated to my GPU and its memory (24GB). The numpy arrays load without issues into memory but once the iterator causes the execution of "from_tensor_slices", the code breaks shortly after. 

What are workable solutions here? DataGenerators? Creating TFRecord files? I try to avoid going the route of TFRecords because it appears very poorly documented how to create such binary files. 

As no warning or error message is output there is no log to show at all. 

The problem can be reproduced with a large numpy array (random data works) and the following code:

#obtain training data
    print("loading training data...")
    train_data = np.load(os.path.join(os.getcwd(), "source_datasets", f"{train_data_id}_features.npy"))
    train_targets = np.load(os.path.join(os.getcwd(), "source_datasets", f"{train_data_id}_targets.npy"))

    print("training dataset construction...")
    train_ds = tf.data.Dataset.from_tensor_slices((train_data, train_targets))

    for x,y in train_ds:
        do_something

**Comment by ShubhamShaswat** [comment]
Hi, Try iterating your dataset using this :
```
for x,y in train_ds.take(1):
    do_something
```
and check if it is able to print out elements from the first list of `train_ds`

Also, try defining a batch size for your train dataset here, using this:
`train_ds = train_ds.batch(BATCH_SIZE)`
I recommend using a smaller BATCH SIZE first.

The above suggestions might not be enough to fix your problem.Even with a a large RAM, loading a data this big directly into the memory is not very efficient.It would be better to load just a chunk of the file directly into memory rather loading all of them at once.

**Comment by MattWolf74** [comment]
Thanks for your suggestions, unfortunately those ideas did not solve the issue of crashing due to large size of numpy arrays even though there are no internal memory limitations. I decided to ditch from_tensor_slices and went with generators which seems to work just fine.
