### ISSUE TITLE
what is the feature layer of inception v1 model

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5222]
As show in **classify_image.py** for inception v3 model, the feature layer is **pool_3:0**

    # 'pool_3:0': A tensor containing the next-to-last layer containing 2048
    #   float description of the image.

I print out the nodes of inception v1 model .pb file as below. I guess the feature layer is **avgpool0/reshape**, is that right? 

input
conv2d0_w
conv2d0_b
conv2d1_w
conv2d1_b
conv2d2_w
conv2d2_b
... 
...
...
...
mixed5b/concat_dim
mixed5b
**avgpool0**
head0_pool
head0_bottleneck_pre_relu/conv
head0_bottleneck_pre_relu
head0_bottleneck
head0_bottleneck/reshape/shape
head0_bottleneck/reshape
nn0_pre_relu/matmul
nn0_pre_relu
nn0
nn0/reshape/shape
nn0/reshape
softmax0_pre_activation/matmul
softmax0_pre_activation
softmax0
head1_pool
head1_bottleneck_pre_relu/conv
head1_bottleneck_pre_relu
head1_bottleneck
head1_bottleneck/reshape/shape
head1_bottleneck/reshape
nn1_pre_relu/matmul
nn1_pre_relu
nn1
nn1/reshape/shape
nn1/reshape
softmax1_pre_activation/matmul
softmax1_pre_activation
softmax1
avgpool0/reshape/shape
**avgpool0/reshape**
softmax2_pre_activation/matmul
softmax2_pre_activation
softmax2
output
output1
output2

**Comment by drpngx** [comment]
Hi, do you want to try stackoverflow (with tag "tensorflow")?

**Comment by civilmanxx** [comment]
OK

**Comment by drpngx** [comment]
Thanks!

**Comment by civilmanxx** [comment]
yes, It is correct. **avgpool0/reshape** is the feature layer.

**Comment by drpngx** [comment]
Did you mean to post on stackoverflow?

**Comment by nikogamulin** [comment]
@civilmanxx have you managed to retrain the inception v1 model?

I am currently trying to reshape the script retrain.py to retrain inception v1 model.

Where did you get the nodes above? I also tried to print them out in order to modify parameters BOTTLENECK_TENSOR_NAME, JPEG_DATA_TENSOR_NAME, and RESIZED_INPUT_TENSOR_NAME and got the following:

```
['input']
['conv2d0_w']
['input', '0']
['conv2d0_w', '0']
['conv2d0_pre_relu/conv']
['conv2d0_b']
['conv2d0_pre_relu/conv', '0']
['conv2d0_b', '0']
['conv2d0_pre_relu']
['conv2d0_pre_relu', '0']
['conv2d0']
['conv2d0', '0']
['maxpool0']
['maxpool0', '0']
...
...
...
['softmax2_w']
['avgpool0/reshape', '0']
['softmax2_w', '0']
['softmax2_pre_activation/matmul']
['softmax2_b']
['softmax2_pre_activation/matmul', '0']
['softmax2_b', '0']
['softmax2_pre_activation']
['softmax2_pre_activation', '0']
['softmax0']
['softmax0', '0']
['softmax1']
['softmax1', '0']
['softmax2']
['softmax2', '0']
['pool_3/_reshape', '0']
```

**Comment by civilmanxx** [comment]
please use the code below in python to print out all the tensor names

for tensor in tf.get_default_graph().as_graph_def().node:
      print(tensor.name)
