### ISSUE TITLE
Blas xGEMV launch failed error when running on GPU. 

### ISSUE THREAD

**Issue by mrnucleation** [tensorflow/tensorflow#52222]
I've ran into a really strange error that is incredibly difficult to track down.  I have a version of Tensorflow (2.6.0-rc1) using Cuda 11.3 that I compiled from source.  When I run it using my GPU for evaluating a pretty normal feed forward model I constantly get this crash on this one particular line. 

```
    h = tf.matmul(h, self.output_weight)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py", line 3654, in matmul
    return gen_math_ops.mat_mul(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5696, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMV launch failed : a.shape=[1,2728550,5], b.shape=[1,5,1], m=2728550, n=1, k=5 [Op:MatMul]

```
When I look up this error it usually indicates a problem in the CUDA install or other similar problems, but in this particular case CUDA is working just fine. I am able to run another script which uses Keras from the same Tensorflow install and use the GPU with zero problem. In fact in this same exact code 2-3 TF.MatMul calls go through with zero problem right before it crashes on this line.  

``
h = tf.matmul(h, self.output_weight)
``
Where self.output_weight is a tensorflow Variable class and h is as well.  Both data types float32.  The thing is the h variable also was computed by multiple sequential calls that run on the GPU just fine.  When I run in CPU only mode it runs just fine with zero problems.  The model only uses matmul opperations and standard tensorflow library functions. What's even stranger is this same exact code works on the GPU for a different set of input!  

I'm running this on Linux Mint 20.2 with Kernel version 5.4.0-88-generic.  Cuda version 11.3 with the corresponding compatible version of TensorRT, the NVidia drivers, etc.  This is being done on a RTX 3090 graphics card.   It's an incredibly strange error since it only pops up on this one particular line. I also tested out my Cuda install via the samples folder in the Cuda install directory.  My other Cuda based GPU applications work just fine as well.  Nvidia-smi also shows Python3 taking up most of the card's memory as it usually does.

**Comment by aaronmondal** [comment]
My guess would be that the `[1,2728550,5]` tensor is wayyy too large, so your input is probably too large.

You could feed inputs of increasing sizes into your model to find the point at which the code collapses.

**Comment by sushreebarsa** [comment]
@mrnucleation 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Could you please try as per the [comment](https://github.com/tensorflow/tensorflow/issues/52222#issuecomment-932737035) above and let us know if it helps? Thanks!

**Comment by mrnucleation** [comment]
> My guess would be that the `[1,2728550,5]` tensor is wayyy too large, so your input is probably too large.
> 
> You could feed inputs of increasing sizes into your model to find the point at which the code collapses.

I was able to get it to compute by cutting up the array into blocks of 1/100th of the original size and passing them through one at a time.  Then pasting the fragments together at the end. Though it' still a bit perplexing why it crashes on the last line.  That's more what's absolutely confusing.

If anything it should have crashed in the middle of the network where the intermediate tensors are far larger. The finally tensor is just a Nx5 tensor where as the intermediate ones are Nx16 and Nx32 in size.  I'm thinking it might have to do with the previous computations hanging around in memory and clogging things up. 

The computer this is running on has 64GB of system memory and 24GB of GPU RAM. When I measure the ram consumption with NVIDIA-SMI it only takes up 3GB of ram.  It seems like rendering a 8K image should be a more resource intensive task than this and this system can do that just fine. So it seems to have more to do with the TF backend not liking that.

**Comment by mrnucleation** [comment]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Mint 20.2**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): **2.6.0-rc1**
- Python version: 3.8.10
- Bazel version (if compiling from source): **3.7.2**
- GCC/Compiler version (if compiling from source): **9.3.0**
- CUDA/cuDNN version: **11.3**
- GPU model and memory: **MSI Geforce RTX 3090 24GB**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.6.0-rc1-4-g9a63e4600fa 2.6.0-rc1

**Describe the current behavior**

Crashes when running in GPU mode on final computation of a network.  Passes two layers of a feed forward type model perfectly and then throws a BLAS error when computing the final output.  Works just fine in CPU Only mode. Crashes with the error message
```

  File "/<redacted>/SymbolicNetworks/ThreeBody/StabiliyTest/symbolic_network.py", line 162, in __call__
    h = tf.matmul(h, self.output_weight)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py", line 3654, in matmul
    return gen_math_ops.mat_mul(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5696, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas xGEMV launch failed : a.shape=[1,18800375,6], b.shape=[1,6,1], m=18800375, n=1, k=6 [Op:MatMul]

```

**Describe the expected behavior**

Computation passes through two layers of the network successfully in GPU mode and crashes on final computation.

**Comment by sushreebarsa** [comment]
@mrnucleation We see that you are using 2.6.0-rc1 ,Could you please try with the stable version of TF 2.6.0 ,please refer to build from [source](https://www.tensorflow.org/install/source#gpu).Please refer to some similar issues[ link1](https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed), [link2](https://github.com/tensorflow/tensorflow/issues/25403),[link3](https://github.com/tensorflow/tensorflow/issues/11812) and let us know if it helps?Thanks!

**Comment by njzjz** [comment]
I have a similar issue when using CUDA 11.3. I would suggest to downgrade CUDA 11.2. There should be some unknown compatibility issues with CUDA 11.3. (And I hope it can be investigated)

**Comment by njzjz** [comment]
UPDATE: It may be a bug of cublas. See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cublas-11.4.0

**Comment by gadagashwini** [comment]
@mrnucleation, This issue can be due to several reasons, 
1. out of memory: Limit the GPU memory growth
2. configuration Mismatch with CUDA/cuDNN
3. remove the cache folder ~/.nv/

**Comment by skyson** [comment]
您的邮件已经收到--阿杰
