### ISSUE TITLE
Shaky sidebar on the docs

### ISSUE THREAD

**Issue by logankilpatrick** [tensorflow/tensorflow#52239]
## Description of issue (what needs changing):

When I scroll down in the docs, the left side of pages shakes very aggressively.

https://user-images.githubusercontent.com/35577566/135758613-fbdf9612-e663-4dda-af53-aaae4d26b97a.mov

**Comment by logankilpatrick** [comment]
I am viewing this on Safari, Chrome seems much less shaky, but still a little jitter.

**Comment by mohantym** [comment]
Hi @logankilpatrick! @sanatmpa1!, I checked  the above link in Firefox,chrome,Edge Browser for Windows a for stability of above link , It seems to be working  fine though It was lagging bit in Safari Browser for windows .

**Comment by logankilpatrick** [comment]
I am not on a VPN and running the most up to dat safari version.

**Comment by mohantym** [comment]
@sanatmpa1 ,Could you please look at this issue?

**Comment by sanatmpa1** [comment]
@logankilpatrick,

We've checked it in `Chrome(Version 94.0.4606.71 (Official Build) (64-bit)), Firefox(78.14.0esr (64-bit)) and also in Safari(Version 14.1.2 (16611.3.10.1.6))`, but we don't see any such shaking issue that you have mentioned. 

Can you provide the version of safari you are using and other hardware details if possible? Also try using another device and update us if the problem exists in that as well? Thanks!

**Comment by sanatmpa1** [comment]
@logankilpatrick,

Yes it could be related to the processor as it works fine on non M1 macbook, Also the issue is not present in different hardwares that we tested it on.

**Comment by logankilpatrick** [comment]
Can you get access to a M1 Mac to test? I only have access to one.

**Comment by sanatmpa1** [comment]
@logankilpatrick,

Unfortunately we don't have the M1 mac to test, Can you try opening an issue in this [repo](https://github.com/apple/tensorflow_macos) to see if this can be checked? Thanks!

**Comment by logankilpatrick** [comment]
@sanatmpa1 that repo is archives so I cannot open an issue there.

**Comment by logankilpatrick** [comment]
I have updated to the newly release macOS version and no longer have any issues. Thanks for debugging with me!
