### ISSUE TITLE
Building tflite with xnnpack on windows 10 

### ISSUE THREAD

**Issue by amoghht** [tensorflow/tensorflow#52258]
hello team,
 
i wanted to use xnnpack with tflite on my windows 10 machine. found out that we need to build tf from source with tflite_with_xnnpack=true flag. i was not able to build successfully ,and I am not sure I am following the correct steps or not as I didn't get proper installation guide for building tf with xnnpack on windows. It would be helpful if I get any documentation or resource to build and use tflite with XNN pack

**Comment by tilakrayal** [comment]
@amoghht ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled and the tensorflow version you are using, could you please do so as it helps us analyse the issue.Thanks!

**Comment by tilakrayal** [comment]
@amoghht ,
Can you please take a look at this [link](https://github.com/tensorflow/tensorflow/issues/38852) with the similar issue.It helps.Thanks!

**Comment by amoghht** [comment]
@tilakrayal ,
thank you,will try and update soon

**Comment by sachinprasadhs** [comment]
Hi, Could you please follow this [link](https://www.tensorflow.org/lite/guide/build_cmake) to build the tflite with TFLITE_ENABLE_XNNPACK=ON for Windows and let us know if you still face an issue. Thanks!
