### ISSUE TITLE
The difference in the return order of object detection results in tf2.5-cpu and tf2.6-gpu

### ISSUE THREAD

**Issue by MaoXianXin** [tensorflow/tensorflow#52259]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/lite/tutorials/model_maker_object_detection#optional_test_the_tflite_model_on_your_image

## Description of issue (what needs changing):
the return order in tf2.5-cpu in google colab is 
```
  boxes = get_output_tensor(interpreter, 0)
  classes = get_output_tensor(interpreter, 1)
  scores = get_output_tensor(interpreter, 2)
  count = int(get_output_tensor(interpreter, 3))
```

but in tf2.6-gpu the return order is
```
    scores = get_output_tensor(interpreter, 0)
    print(scores)
    boxes = get_output_tensor(interpreter, 1)
    print(boxes)
    count = int(get_output_tensor(interpreter, 2))
    print(count)
    classes = get_output_tensor(interpreter, 3)
    print(classes)
```

the link to my script is: https://github.com/MaoXianXin/Tensorflow_tutorial/blob/tf_hub/TFLite_prac/object_detection_lite.py
the detect result is in the Clear description

### Clear description
![2021-10-05-19-58-43](https://user-images.githubusercontent.com/22192610/136018975-a943ff2b-3698-44c7-bd32-d5ab4d156f33.png)
the following is my result:
![result](https://user-images.githubusercontent.com/22192610/136019965-c69c2071-149b-49fa-8cee-b41318e41012.png)

if i use the code in docs the error is result:
![2021-10-05-20-13-48](https://user-images.githubusercontent.com/22192610/136020174-4ff542e1-37a3-4adb-96b7-0894d43f6e49.png)

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@MaoXianXin 
Can you please share a colab gist with the difference in result in cpu and gpu.

**Comment by MaoXianXin** [comment]
![2021-10-14-22-21-35](https://user-images.githubusercontent.com/22192610/137337391-d535f39b-f33f-46ce-835d-e94ef0420937.png)
![2021-10-14-22-24-08](https://user-images.githubusercontent.com/22192610/137337403-5e1e57bd-1c61-46be-b696-dd2d25e28a52.png)

**Comment by sachinprasadhs** [comment]
Hi, We are investigating on this issue. 
Could you please close this issue and track the progress [here](https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182) in the similar issue.
Along with the linked comment workaround, the suggested way to use is make use of signatures in your model https://www.tensorflow.org/lite/guide/signatures
