### ISSUE TITLE
tf.data.service worker occasionally fails "to send worker update" and will be unrecoverable

### ISSUE THREAD

**Issue by rllin** [tensorflow/tensorflow#52252]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Mostly congruent to https://github.com/tensorflow/ecosystem/blob/master/data_service/tf_std_data_server.py 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Image based on `https://gcr.io/deeplearning-platform-release/tf2-gpu.2-5`
- TensorFlow installed from (source or binary): see image
- TensorFlow version (use command below): 2.5
- Python version: 3.7 (see image)

**Describe the current behavior**
Occasionally, a third of my 10 workers will all report something like this about 30 times

```
2021-10-05 02:19:10.033421: W tensorflow/core/data/service/worker_impl.cc:311] Failed to send task updates to dispatcher: Not found: Failed to send worker update: Task 4003 not found
```

and then not serve any data.  This is confirmed by checking network egress metrics for the workers.  And throughput on the training node will collapse.

This seems to come from https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/data/service/worker_impl.cc;l=308-312;bpv=0;bpt=1

This happens maybe every 3 times I use the service.  It does not seem to recover by itself.  I have to manually restart each worker that is experiencing this to recover throughput.

It is okay that this fails, but it does not seem to exit code as a failure and just sits there.

None of these workers have high mem pressure or cpu usage.

NOTE: I am not trying to consume multiple datasets.  there is only 1 job and 1 dataset but multiple consumers (using `strategy.distribute_dataset`)

**Describe the expected behavior**
Either workers report this an error and exit code properly or retry until success.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ! Could you please look at this issue .Attaching [Gist f](https://colab.research.google.com/gist/mohantym/4712a0805340cebc0501c9d5db8aa357/github_52252.ipynb)or reference , Process is not ending once started.

**Comment by rllin** [comment]
It would also be ideal if I could understand what causes this failure so I can perhaps construct my dataset to avoid it in the first place.  Thanks!

**Comment by sanatmpa1** [comment]
@rllin,

Can you share the stand-alone code or colab gist to reproduce the issue and expedite the trouble-shooting process? Thanks!

**Comment by rllin** [comment]
Unfortunately I'm not certain I can give you a reproduction easily as this requires multiple separate machines.  The closest I can recommend would be probably to follow the ecosystem link I pasted to stand things up in GKE (pretty much exactly how we deploy the workers/dispatchers but on tf 2.5).  And then we consume elements aggressively on MirroredStrategy, e.g.:

```
      from tensorflow.python.data.experimental.ops.data_service_ops import _from_dataset_id, _register_dataset
      # NOTE: use underlying ops directly to avoid compression.
      dataset_id = _register_dataset(
        service=dispatcher_name,
        dataset=dataset,
        compression=None,
      )
      def dataset_fn(input_context):
        del input_context
        return _from_dataset_id(
          processing_mode="parallel_epochs",
          service=dispatcher_name,
          dataset_id=dataset_id,
          element_spec=dataset.element_spec,
          job_name=job_name,
          compression=None,
        ).prefetch(prefetch)
      dataset = strategy.experimental_distribute_datasets_from_function(dataset_fn)
      
...
@tf.function
def train_step(inputs):
  return tf.identity(inputs)
  
for element in dataset:
  strategy.run(train_step, element)
  
```

**Comment by rllin** [comment]
@yangustc07 the dispatchers were not restarted during these failures afaict (is obvious when looking at pod restarts)

this happens very quickly when i first start all the requisite deployments/services and the workers do not recover even if i force restart them it seems.
