### ISSUE TITLE
issue with tf.saved_model.save

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#52254]
https://github.com/tensorflow/tensorflow/issues/51587

I cannot understand why this serious issue is not paid any attention for such a  long time

**Comment by mihaimaruseac** [comment]
Duplicates #51587

Please don't open duplicate issues to raise awareness to other other as this wastes time. Issues are triaged and will be resolved pending time / questions will be asked on the original issue as needed.
