### ISSUE TITLE
TensorFlowLite with XNNPack error with dynamic shapes (while loop in model appeared after TFLite conversion)

### ISSUE THREAD

**Issue by AnastGerus** [tensorflow/tensorflow#52265]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device if the issue happens on mobile device: ARM64
- TensorFlow installed from (source or binary): from source
- TensorFlow version (use command below): nightly 2.8.0-dev20211004  and 2.6.0
- Python version: python 3.8.10
- Bazel version (if compiling from source): bazel 3.7.2., installed using bazelisk
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: no cuda
- GPU model and memory: no

**Describe the current behavior**
1. I've converted my model from the ONNX file to TFLite.
2. I've built TensorFlow Lite for ARM64 device using XNNpack with `bazel build --config=elinux_aarch64 --define tflite_with_xnnpack=true -c opt //tensorflow/lite:libtensorflowlite.so`. (used TF [guide](https://www.tensorflow.org/lite/guide/build_arm))
When I run it I see:
```
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Failed to modify graph!
```
Everything works correctly without XNNpack, but I need it so desperately.
Also, I've tried using the TensorFlow delegation mechanism for the [ARM NN](https://github.com/ARM-software/armnn/tree/branches/armnn_20_11/delegate) library, but it has the same issue.

**Describe the expected behavior**
I expect it to process my model. 
I've been exploring my model after conversion. All tensors shapes are defined, no `None` s are present. But it seems to me that the conversion process created some `while` loop and it can be the cause of the issue. Please correct me if I'm wrong. I also don't know why it's created. Maybe it is possible just to find a workaround in the converter.

**Standalone code to reproduce the issue**
I'm adding here my ONNX model and TFLite model archived. Please put them on the `some_path `variable. [model.zip](https://github.com/tensorflow/tensorflow/files/7288640/model.zip)
Converter code:
```
onnx_model = onnx.load(some_path)   # load onnx model
tf_rep = prepare(onnx_model, 'CPU')   # ONNX -> TensorFlowRep representation (computational graph)
tf_rep.export_graph(some_path) 
converter = tf.lite.TFLiteConverter.from_saved_model(some_path)
converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()
with open(os.path.join(some_path,'model.tflite'), 'wb') as f:
  f.write(tflite_model)    
```   

**Other info / logs**
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 32 nodes with 1 partitions.
INFO: TfLiteFlexDelegate delegate: 4 nodes delegated out of 4 nodes with 1 partitions.
INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.
INFO: TfLiteFlexDelegate delegate: 4 nodes delegated out of 29 nodes with 1 partitions.
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Failed to modify graph!

**Comment by mohantym** [comment]
Hi @AnastGerus ! Could you look at similar issues for reference  . [Link1 ](https://github.com/tensorflow/tensorflow/issues/38036),[Link2](https://stackoverflow.com/questions/66789210/converting-tf-keras-model-to-tflite-model-is-slow-and-doesnt-work-with-xnn-pac),[Link3](https://www.tensorflow.org/lite/performance/nnapi)

**Comment by AnastGerus** [comment]
Hi @mohantym,
Yes, I've seen these links. I would also benefit from [this ](https://github.com/tensorflow/tensorflow/issues/42491) request, but it doesn't look like something that will be added soon.
In other ones, the root of the issue is dynamic shapes of input (resizing basically), but I don't get where it can come from in my model. I have fixed input size, no resize ops in the model, all ops are supported by TFLite builtins. The only suspicious thing after conversion is the 'while' loop that came from nowhere. 
Where it came from in the conversion time? How can I do a workaround for it? Does it make sense to wait until XNNPACK with dynamic shapes of tensors support will be implemented?

Thanks for your attention,
Best regards,
Anastasiia

**Comment by mohantym** [comment]
Hi @AnastGerus @sachinprasadhs ! I  edited above code using below reference ans was getting Assertion error . Can you please checkout  this code base. Attaching [Gist](https://colab.research.google.com/gist/mohantym/a4800e625b86a36171cff0d0cdb89cd7/github_52265.ipynb#scrollTo=ZEVrkAmCpzIW) for Reference.
[Reference:](https://colab.research.google.com/github/joshuacwnewton/ONNX-to-TFLite/blob/master/onnx_to_tflite.ipynb#scrollTo=oXwuHawWvXmk)

**Comment by multiverse-tf** [comment]
This is a known issue with XNNPACK delegate (and other TFLite delegates) as it doesn't support model graphs with dynamic tensors. Note that a tensor could be marked dynamic at TFLite runtime when there's a control-flow op (like if, while etc.) prepared. In other words, even when the model graph itself doesn't have any tensors of dynamic shapes statically, at runtime, a model could have dynamic tensors.

We are putting resources internally to resolve such issues as soon as possible, hopefully by the next TF release.
