### ISSUE TITLE
TFLite: How to mix floating-point kernels with quantized kernels for different parts of the graph.

### ISSUE THREAD

**Issue by shariq-audiofocus** [tensorflow/tensorflow#52266]
## URL(s) with the issue:
https://www.tensorflow.org/lite/performance/post_training_quant

## Description of issue (what needs changing):
On this page it says:

> TFLite supports on the fly quantization and dequantization of activations to allow for:
>
> 1. Using quantized kernels for faster implementation when available.
> **2. Mixing of floating-point kernels with quantized kernels for different parts of the graph.**

Where is it documented how this can be done?

### Clear description

I would like to create a TFLite model where the first and last layer use floating-point kernels and the intermediate layers use use quantized kernels. From the bold section above it seems possible.

The TFLite version of my model has high accuracy using float32. But it has really poor accuracy with int8. I've narrowed the issue down to my convolution layer which is used to pre and post process my audio signal. These layers have a very low parameter count compared to the rest of my model.

If I could quantized the only the big, middle portion of my model then I could get a high accuracy model with much faster accuracy and latency.

If there's another solution to this I'd love to hear about it.

### Correct links

Yes

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

Yes

### Usage example

Is there a usage example?

No

### Request visuals, if applicable

No

### Submit a pull request?

No

**Comment by shariq-audiofocus** [comment]
Perhaps this isn't actually possible since it's on the TFLite Roadmap:

> Selective post-training quantization to exclude certain layers from quantization.
[1] https://www.tensorflow.org/lite/guide/roadmap 
[2] https://github.com/tensorflow/tensorflow/issues/21596

**Comment by tilakrayal** [comment]
@shariq-audiofocus ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.Thanks!

**Comment by shariq-audiofocus** [comment]
I don't see how the rest of the template is relevant but I filled it out as best I could.
