### ISSUE TITLE
Build r2.6 fails when build ppc64le machine

### ISSUE THREAD

**Issue by Sueoka-ppc** [tensorflow/tensorflow#52272]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):**source build**
- TensorFlow version: **2.6(with gpu)**
- Python version: **python3.6**
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source):**bazel 3.7.2- (@non-git)**
- GCC/Compiler version (if compiling from source):gcc 5.5.0(but gcc7 is also the same err is happened)
- CUDA/cuDNN version: cuda 10.2 cuDNN7.6
- GPU model and memory: RTX 2070 super(8gb gpu memory)

when build blow error is happen and abend build...

ERROR: /home/sueoka/gitrepo/tensorflow/tensorflow/core/platform/default/BUILD:147:11: C++ compilation of rule '//tensorflow/core/platform/default:env_time' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/ppc-opt/bin/tensorflow/core/platform/default/_objs/env_time/env_time.d ... (remaining 43 argument(s) skipped)
In file included from external/eigen_archive/Eigen/Core:210:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/core/platform/bfloat16.h:21,
                 from ./tensorflow/core/platform/types.h:21,
                 from ./tensorflow/core/platform/env_time.h:20,
                 from tensorflow/core/platform/default/env_time.cc:19:
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmul(const Packet&, const Packet&) [with Packet = __vector(8) short int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:801:122: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet8s   pmul<Packet8s>  (const Packet8s&   a, const Packet8s&   b) { return vec_mul(a,b); }
                                                                                                                          ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmul(const Packet&, const Packet&) [with Packet = __vector(8) short unsigned int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:802:122: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet8us  pmul<Packet8us> (const Packet8us&  a, const Packet8us&  b) { return vec_mul(a,b); }
                                                                                                                          ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmul(const Packet&, const Packet&) [with Packet = __vector(16) signed char]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:803:122: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet16c  pmul<Packet16c> (const Packet16c&  a, const Packet16c&  b) { return vec_mul(a,b); }
                                                                                                                          ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmul(const Packet&, const Packet&) [with Packet = __vector(16) unsigned char]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:804:122: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet16uc pmul<Packet16uc>(const Packet16uc& a, const Packet16uc& b) { return vec_mul(a,b); }
                                                                                                                          ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmadd(const Packet&, const Packet&, const Packet&) [with Packet = __vector(8) short int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:833:127: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet8s pmadd(const Packet8s& a, const Packet8s& b, const Packet8s& c) { return vec_madd(a,b,c); }
                                                                                                                               ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Packet Eigen::internal::pmadd(const Packet&, const Packet&, const Packet&) [with Packet = __vector(8) short unsigned int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:834:131: error: invalid parameter combination for AltiVec intrinsic
 template<> EIGEN_STRONG_INLINE Packet8us pmadd(const Packet8us& a, const Packet8us& b, const Packet8us& c) { return vec_madd(a,b,c); }
                                                                                                                                   ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'Eigen::internal::Packet8bf Eigen::internal::F32ToBf16(Eigen::internal::Packet4f)':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1267:89: error: 'vec_cmpne' was not declared in this scope
   Packet4bi is_mant_not_zero = vec_cmpne(mantissa, reinterpret_cast<Packet4ui>(p4i_ZERO));
                                                                                         ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::predux_mul(const Packet&) [with Packet = __vector(8) short int; typename Eigen::internal::unpacket_traits<T>::type = short int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1546:37: error: invalid parameter combination for AltiVec intrinsic
   pair = vec_mul(a, vec_sld(a, a, 8));
                                     ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1547:46: error: invalid parameter combination for AltiVec intrinsic
   quad = vec_mul(pair, vec_sld(pair, pair, 4));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1548:46: error: invalid parameter combination for AltiVec intrinsic
   octo = vec_mul(quad, vec_sld(quad, quad, 2));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::predux_mul(const Packet&) [with Packet = __vector(8) short unsigned int; typename Eigen::internal::unpacket_traits<T>::type = short unsigned int]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1557:37: error: invalid parameter combination for AltiVec intrinsic
   pair = vec_mul(a, vec_sld(a, a, 8));
                                     ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1558:46: error: invalid parameter combination for AltiVec intrinsic
   quad = vec_mul(pair, vec_sld(pair, pair, 4));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1559:46: error: invalid parameter combination for AltiVec intrinsic
   octo = vec_mul(quad, vec_sld(quad, quad, 2));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::predux_mul(const Packet&) [with Packet = __vector(16) signed char; typename Eigen::internal::unpacket_traits<T>::type = signed char]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1577:37: error: invalid parameter combination for AltiVec intrinsic
   pair = vec_mul(a, vec_sld(a, a, 8));
                                     ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1578:46: error: invalid parameter combination for AltiVec intrinsic
   quad = vec_mul(pair, vec_sld(pair, pair, 4));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1579:46: error: invalid parameter combination for AltiVec intrinsic
   octo = vec_mul(quad, vec_sld(quad, quad, 2));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1580:48: error: invalid parameter combination for AltiVec intrinsic
   result = vec_mul(octo, vec_sld(octo, octo, 1));
                                                ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::predux_mul(const Packet&) [with Packet = __vector(16) unsigned char; typename Eigen::internal::unpacket_traits<T>::type = unsigned char]':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1589:37: error: invalid parameter combination for AltiVec intrinsic
   pair = vec_mul(a, vec_sld(a, a, 8));
                                     ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1590:46: error: invalid parameter combination for AltiVec intrinsic
   quad = vec_mul(pair, vec_sld(pair, pair, 4));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1591:46: error: invalid parameter combination for AltiVec intrinsic
   octo = vec_mul(quad, vec_sld(quad, quad, 2));
                                              ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/PacketMath.h:1592:48: error: invalid parameter combination for AltiVec intrinsic
   result = vec_mul(octo, vec_sld(octo, octo, 1));
                                                ^
In file included from external/eigen_archive/Eigen/Core:212:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/core/platform/bfloat16.h:21,
                 from ./tensorflow/core/platform/types.h:21,
                 from ./tensorflow/core/platform/env_time.h:20,
                 from tensorflow/core/platform/default/env_time.cc:19:
external/eigen_archive/Eigen/src/Core/arch/AltiVec/Complex.h: In member function 'Eigen::internal::Packet2cf Eigen::internal::Packet2cf::operator-() const':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/Complex.h:77:31: error: 'vec_neg' was not declared in this scope
     return Packet2cf(vec_neg(v));
                               ^
external/eigen_archive/Eigen/src/Core/arch/AltiVec/Complex.h: In member function 'Eigen::internal::Packet1cd Eigen::internal::Packet1cd::operator-() const':
external/eigen_archive/Eigen/src/Core/arch/AltiVec/Complex.h:330:31: error: 'vec_neg' was not declared in this scope
     return Packet1cd(vec_neg(v));
                               ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 76.801s, Critical Path: 11.73s
INFO: 221 processes: 7 internal, 214 local.
FAILED: Build did NOT complete successfully

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sachinprasadhs** [comment]
Could you please try again with the r2.6.5 release or you can try with the latest stable version 2.9.1 and let us know if you still face an error. Thanks!

**Comment by Bozbozi** [comment]
در تاریخ پنجشنبه ۱۵ سپتامبر ۲۰۲۲،‏ ۳:۳۸ google-ml-butler[bot] <
***@***.***> نوشت:
