### ISSUE TITLE
`tf.random.shuffle` is deterministic when XLA is used

### ISSUE THREAD

**Issue by callumm-graphcore** [tensorflow/tensorflow#52277]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary (I assume that's what `pip install` does, at least)
- TensorFlow version (use command below): `v2.6.0-rc2-32-g919f693420e 2.6.0`
- Python version: Python 3.6.9
- CUDA/cuDNN version: N/A, program runs on CPU
- GPU model and memory: N/A, program runs on CPU

**Describe the current behavior**

If I call `tf.random.shuffle` on a 1D tensor of float-32 values of size 10 (for example) inside a JIT-compiled `tf.function`, the shuffled tensor is the same every time I run the program.

**Describe the expected behavior**

The shuffled tensor should usually be different between runs.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

@tf.function(jit_compile=True)
def shuffle_me(some_tensor):
    output = tf.random.shuffle(some_tensor)
    return output

input_ = [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]
input_ = tf.constant(input_, dtype=tf.float32)

shuffled = shuffle_me(input_)
print(shuffled)
```

I ran this program 20 times, and the output was always `tf.Tensor([0. 2. 5. 9. 3. 4. 8. 7. 6. 1.], shape=(10,), dtype=float32)`. The probability of this happening at random is 1 in (10!)^19, or about 1 in 4.3 x 10^124. If you comment out the line `@tf.function(jit_compile=True)`, the outputs are random.

If you are running on Linux, you may find it easiest to do something like:

```bash
for N in $(seq 1 20); do python test_shuffle_xla.py; done 2> /dev/null
```

This will filter out all of the warnings and just show each of the shuffled tensors.

**Other info / logs**

I do not have any other information or logs to share at this time, but I would be happy to generate any logs that the TensorFlow team might find useful.

Thank you for your time!

**Comment by cheshire** [comment]
This is the seeding behavior: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/tf2xla/tf2xla_util.cc;l=547-556;drc=3381da37560d64c7cb62b53879a0a931ff9036c4

it looks like it will generate a new seed each time you run it within a single execution, ignoring TF seed. Which behavior would you expect?

**Comment by cheshire** [comment]
We can seed the first calculation with the TF seed, let me see if there are any known blockers.

**Comment by wangpengmit** [comment]
For RNG in general, `tf.random.stateless_*` and `tf.random.Generator` are recommended over `tf.random.shuffle` and alike. Please see https://www.tensorflow.org/guide/random_numbers . We don't have `stateless_shuffle` or `Generator.shuffle` yet. We are working on adding the former.

**Comment by callumm-graphcore** [comment]
Hi @cheshire, thank you for looking into this. I would still expect to be able to make the first call to `tf.random.shuffle` produce different results across multiple runs, even if that meant changing the seed each time. It'd be great if we could use the TF random seed for this purpose.

Thank you for pointing me to the stateless RNG ops and the RNG generators, @wangpengmit. I will use those when possible in the future.

**Comment by denshade** [comment]
I've checked the kernel function in the Tf2xla It appears some functions warn about the seed not being used. I tried it and can confirm that seeding does nothing.

**Comment by sachinprasadhs** [comment]
@callumm-graphcore , Could you please refer the new API [tf.random.experimental.stateless_shuffle ](https://www.tensorflow.org/api_docs/python/tf/random/experimental/stateless_shuffle) and check if this is useful in your case. Thanks!

**Comment by callumm-graphcore** [comment]
Sorry, I've been busy and haven't had time to look at this. I will pass on to my colleagues that they should use the stateless random ops with TF + XLA + CPU, including `stateless_shuffle`.

**Comment by callumm-graphcore** [comment]
And thanks to everyone for their help :)
