### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: ReorderAxes. See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 284 (ReorderAxes) failed to prepare.

### ISSUE THREAD

**Issue by ymzlygw** [tensorflow/tensorflow#52281]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab 
- TensorFlow version (or github SHA if from source): convert model in TF1.x / interpreter in  latest tf-nightly.

I convert a model to tflite using following codes:

    co = tf.compat.v1.lite.TFLiteConverter.from_saved_model(modelName)
    co.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
    co.allow_custom_ops=True

There are no error in converting.But when I try to interpreter the tfliter model, I encoder error:
--> 916     self._interpreter.Invoke()
    917 
    918   def reset_all_variables(self):

**RuntimeError: Encountered unresolved custom op: ReorderAxes.**
See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 284 (ReorderAxes) failed to prepare.
Could you please tell me how to solve this?

**Comment by ymzlygw** [comment]
> @ymzlygw Thank you for the update! Was able to reproduce the issue on colab using `TF 2.6 `and `tf-nightly` on `gpu runtime`, Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/4774bc7fd89fb3430868361dd4761c98/untitled448.ipynb). This issue is not replicating on [`TF 2.6-cpu` ](https://colab.research.google.com/gist/sushreebarsa/b9ef0cd01875e6d6bba53e510396af3e/untitled446.ipynb)runtime.Could you please find the attached gists and let us know if it is the right way to reproduce the issue? Thanks!

@sushreebarsa Thanks for you reply.
And sorry I should make a more detailed error occurs situation as follows:

**Without change any_code in** 
https://github.com/NVlabs/stylegan2/blob/81ae61d7753c6a7b5a38c29aa81aed15adb19c2f/dnnlib/tflib/ops/fused_bias_act.py#L64-L66. 
https://github.com/NVlabs/stylegan2/blob/81ae61d7753c6a7b5a38c29aa81aed15adb19c2f/dnnlib/tflib/ops/upfirdn_2d.py#L58-L60
I mean: if change **[ 'cuda': _fused_bias_act_cuda] --> ['cuda': _fused_bias_act_ref]**  and  **['cuda': _upfirdn_2d_cuda] --> ['cuda': _upfirdn_2d_ref]** ,  then it can be converted to a tflite_model that can interpreter in cpu run_time as above.

1):**Tflite Model_1 download:** 

    !gdown "https://drive.google.com/uc?id=1fdhClAZHUIiJoIhCmTlzZi3qCPaHIu-z"
1): tflite model converted in tf1.15.2 with setting as follows:

    co.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS]
1): interpreter in **tf 1.15.2** and get error:

    RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 0 (FlexConst) failed to prepare.
1): interpreter in latest tf-nightly and get error:

    RuntimeError: Encountered unresolved custom op: FusedBiasAct.See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 317 (FusedBiasAct) failed to prepare.

2): 1):**Tflite Model_2 download:** 

    !gdown "https://drive.google.com/uc?id=1DvFOmx_VY2hmJASMeFyW9mB6mLSEnSdJ"
2): tflite model converted in tf1.15.2 with setting as follows:

     co.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
2): interpreter in **tf 1.15.2** and get error:

    RuntimeError: tensorflow/lite/kernels/strided_slice.cc new_axis_mask is not implemented yet.Node number 1 (STRIDED_SLICE) failed to prepare.
2): interpreter in latest tf-nightly and get error:

    RuntimeError: Encountered unresolved custom op: FusedBiasAct.See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 29 (FusedBiasAct) failed to prepare.

**Comment by ymzlygw** [comment]
> > @ymzlygw Thank you for the update! Was able to reproduce the issue on colab using `TF 2.6 `and `tf-nightly` on `gpu runtime`, Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/4774bc7fd89fb3430868361dd4761c98/untitled448.ipynb). This issue is not replicating on [`TF 2.6-cpu` ](https://colab.research.google.com/gist/sushreebarsa/b9ef0cd01875e6d6bba53e510396af3e/untitled446.ipynb)runtime.Could you please find the attached gists and let us know if it is the right way to reproduce the issue? Thanks!
> 
> @sushreebarsa Thanks for you reply. And sorry I should make a more detailed error occurs situation as follows:
> 
> **Without change any_code in** https://github.com/NVlabs/stylegan2/blob/81ae61d7753c6a7b5a38c29aa81aed15adb19c2f/dnnlib/tflib/ops/fused_bias_act.py#L64-L66. https://github.com/NVlabs/stylegan2/blob/81ae61d7753c6a7b5a38c29aa81aed15adb19c2f/dnnlib/tflib/ops/upfirdn_2d.py#L58-L60 I mean: if change **[ 'cuda': _fused_bias_act_cuda] --> ['cuda': _fused_bias_act_ref]** and **['cuda': _upfirdn_2d_cuda] --> ['cuda': _upfirdn_2d_ref]** , then it can be converted to a tflite_model that can interpreter in cpu run_time as above.
> 
> 1):**Tflite Model_1 download:**
> 
> ```
> !gdown "https://drive.google.com/uc?id=1fdhClAZHUIiJoIhCmTlzZi3qCPaHIu-z"
> ```
> 
> 1): tflite model converted in tf1.15.2 with setting as follows:
> 
> ```
> co.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS]
> ```
> 
> 1): interpreter in **tf 1.15.2** and get error:
> 
> ```
> RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 0 (FlexConst) failed to prepare.
> ```
> 
> 1): interpreter in latest tf-nightly and get error:
> 
> ```
> RuntimeError: Encountered unresolved custom op: FusedBiasAct.See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 317 (FusedBiasAct) failed to prepare.
> ```
> 
> 2): 1):**Tflite Model_2 download:**
> 
> ```
> !gdown "https://drive.google.com/uc?id=1DvFOmx_VY2hmJASMeFyW9mB6mLSEnSdJ"
> ```
> 
> 2): tflite model converted in tf1.15.2 with setting as follows:
> 
> ```
>  co.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> ```
> 
> 2): interpreter in **tf 1.15.2** and get error:
> 
> ```
> RuntimeError: tensorflow/lite/kernels/strided_slice.cc new_axis_mask is not implemented yet.Node number 1 (STRIDED_SLICE) failed to prepare.
> ```
> 
> 2): interpreter in latest tf-nightly and get error:
> 
> ```
> RuntimeError: Encountered unresolved custom op: FusedBiasAct.See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 29 (FusedBiasAct) failed to prepare.
> ```

**Comment by MeghnaNatraj** [comment]
@ymzlygw You need to write your own custom version of the `FusedBiasAct` op in TFLite. The [TFLite custom ops page](https://www.tensorflow.org/lite/guide/ops_custom) is unfortunately incomplete (we don't have the bandwidth to update it) but the [TF custom op page](https://github.com/tensorflow/custom-op), though not relevant to you, is more detailed. 

Another option is, if you can substitute `FusedBiasAct` with any of the operators [here](https://www.tensorflow.org/lite/guide/op_select_allowlist) then you can simply use the [TF operator in TFLite](https://www.tensorflow.org/lite/guide/ops_select).
