### ISSUE TITLE
wrong cupti dll name

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#52309]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  source
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9.7
- Bazel version (if compiling from source): 3.9.2
- GCC/Compiler version (if compiling from source): Visual Studio 2019
- CUDA/cuDNN version: 11.4/8.2.4
- GPU model and memory: RTX3090 GDDR6x 24GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
wrong cupti name for loading

**Describe the expected behavior**
cupti loaded

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):  change filename to  cupti64*.dll

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="logs")
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="logs")
```

**Comment by tilakrayal** [comment]
@alanpurple ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!
