### ISSUE TITLE
Cannot compile library  for iOS. Please see attached issues with compiling protobuf. 

### ISSUE THREAD

**Issue by arpwal** [tensorflow/tensorflow#5230]
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/arpit/Desktop/tensorflow-master/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use`--host'.
See `config.log' for more details

**Comment by drpngx** [comment]
do you have any more info about system? Please fill out whatever you can from the template.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, we will reopen if further information becomes available. Thanks!
