### ISSUE TITLE
[FEATURE REQUEST] More than 2D matmul

### ISSUE THREAD

**Issue by whr94621** [tensorflow/tensorflow#5231]
Hello!
I just would like to know if high dimensional matmul will be supported in the future?
For example, I have a 3D tensor a and a matrix b as below:

``` python
a = [[[1,1],
         [1,1]],
        [[2,2],
         [2,2]]]
b = [[1,1], [1,1]]
```

In numpy, np.dot(a, b) will return

``` python
[[[2,2],
   [2,2]],
  [[4,4],
    [4,4]]]
```

But in tensorflow tf.matmul only supports 2D \* 2D.

Actually using tf.conv2d and reshaping can do the same thing,  it would be more natural that tf.matmul could do as well. And such operators frequently occurr in NLP tasks like attention or memory network.

Forgive my offense and really thanks for any help

**Comment by drpngx** [comment]
@rmlarsen for any additional thoughts.  It seems like a reasonable idea.

**Comment by drpngx** [comment]
@aselle on numpy parity.

**Comment by shoyer** [comment]
Note also `tf.batch_matmul`, which handle some of this (I think the plan is to eventually consolidate all cases into `tf.matmul`).

**Comment by rmlarsen** [comment]
The general form of this is called tensor contraction. The underlying Eigen library supports this, but the functionality is not currently exposed by TensorFlow (ironically, given the name). It is also possible to implement tensor contraction as a sequences of transpose->reshape->matmul->reshape->transpose ops, which can be quite efficient. We have such an implementation of this approach as well, but some work is needed on the shape inference part, but I think we should try to include it in the open source version.

**Comment by rmlarsen** [comment]
Update: The code is out for review. I expect it to land sometime next week.

**Comment by rmlarsen** [comment]
Got sidetracked (and asked to implement this as 'tensordot' instead) so still working on it. Getting close, though...

**Comment by rmlarsen** [comment]
The code was submitted and should be pushed to github within a few days. We settled on the op name "tf.tensordot" for numpy compatibility.
