### ISSUE TITLE
keras.layers.IntegerLookup fails to deserialize vocubulary

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#52325]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6
- Python version: 3.7

**Describe the current behavior**
When creating a keras.layers.IntegerLookup, we provide a vocabulary.  This is saved off via serialization.  However, upon deserialization, the vocabulary is not loaded correctly --- the layer continues to work, however, one cannot serialize again.

**Describe the expected behavior**
We should be able to serialize and deserialize IntegerLookups any number of times.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

To reproduce, see https://colab.research.google.com/drive/1tpXdEsfYKyax5QhYLR7KAV4P2vQHIT8D?usp=sharing .  It is interesting to note that I cannot reproduce by just serializing to JSON --- I have to serialize to SavedModel.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

From looking at the code, https://github.com/keras-team/keras/blob/v2.6.0/keras/layers/preprocessing/index_lookup.py#L200 , it appears that we are setting `vocabulary`, but not `input_vocabulary`.  Since `vocabulary` is set, the layer works fine.  But, upon the next serialization, we do serialize an empty vocab: https://github.com/keras-team/keras/blob/v2.6.0/keras/layers/preprocessing/index_lookup.py#L333 .

It is not clear to me the difference between `input_vocabulary` and `vocabulary`.

This is also related to https://github.com/tensorflow/tensorflow/issues/43834

**Comment by jeisinge** [comment]
Done - I just reposted at https://github.com/keras-team/keras/issues/15508 .  It is not clear to me if this is a Keras issue or a TF issue.

**Comment by sanatmpa1** [comment]
@jeisinge,

As I see a new issue has been raised in `Keras` repo and it is in progress, Can you close this issue here? Thanks!

**Comment by jeisinge** [comment]
Sure --- if that is the best place for the defect!
