### ISSUE TITLE
Tutorial link is missing

### ISSUE THREAD

**Issue by MaoXianXin** [tensorflow/tensorflow#52321]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/lite/tutorials/pose_classification

## Description of issue (what needs changing):

![2021-10-11-16-41-12](https://user-images.githubusercontent.com/22192610/136760032-46631c11-5db9-46f4-9833-2ae4f2e4618a.png)
Tutorial link is missing:
![2021-10-11-16-42-33](https://user-images.githubusercontent.com/22192610/136760173-e6fcbaa5-db92-4f74-8ffb-3fe1870f4ff4.png)
![2021-10-11-16-43-19](https://user-images.githubusercontent.com/22192610/136760314-73b2970d-d283-4cfe-b319-918b0549b848.png)

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by mohantym** [comment]
Hi @sachinprasadhs !Could you please look at this bug ?

**Comment by rthadur** [comment]
The related PR has been merged , closing this issue.Thank you
