### ISSUE TITLE
build_pip_package broken by removal of keras/api directory

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#52361]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

build_pip_pacakge fails with error output
cp: cannot stat /tmp/tmp.enXUtfEE9u/tensorflow/python/keras/api/_v2/keras/: No such file or directory

**Provide the exact sequence of commands / steps that you executed before running into the problem**

$ bazel build --config=nonccl //tensorflow/tools/pip_package:build_pip_package --verbose_failures
$ mkdir tensorflow-pkg
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package --cpu --project_name tensorflow_aarch64 ./tensorflow-pkg

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Seems to be a result of the commit 
https://github.com/tensorflow/tensorflow/commit/61754492129f651f23f05b5aed889f376ec35bb8#diff-cebea885ef40f295a311dfe2879c002bba33695e437f859f7ce111645a99c0ec

**Comment by mihaimaruseac** [comment]
I think @qlzh727 sent a fix to this.
