### ISSUE TITLE
Extend the info in the placement log to include the node type

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#5236]
Small suggestion:

In the function SimplePlacer::AssignAndLog, change the print and log to be:

```
printf("%s (%s): %s\n", node->name().c_str(),
       node->type_string().c_str(),
       node->assigned_device_name().c_str());
```

**Comment by drpngx** [comment]
thanks! you could submit a PR and go through the review process.

**Comment by DavidNorman** [comment]
oops - didn't see your response. sorry. thanks for doing the work @burness.  nice job.
