### ISSUE TITLE
Build libtensorflow-lite.a failed on centos 7 platform

### ISSUE THREAD

**Issue by liuchang3** [tensorflow/tensorflow#52377]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux CentOS 7):
- TensorFlow installed from (source or binary):source 
- TensorFlow version:current master branch and r2.6
- Python version:N/A
- Installed using virtualenv? pip? conda?: compile from source code
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the problem**
cmake ../tensorflow_src/tensorflow/lite return fail

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
2. mkdir tflite_build
3. cd tflite_build
4. cmake ../tensorflow_src/tensorflow/lite  

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

er@RC802802663 tflite_build]$ cmake ../tensorflow_src/tensorflow/lite
-- Setting build type to Release, for debug builds use'-DCMAKE_BUILD_TYPE=Debug'.
[ 11%] Performing download step (git clone) for 'eigen-populate'
Cloning into 'eigen'...
error: RPC failed; result=22, HTTP code = 422
fatal: the remote end hung up unexpectedly
Cloning into 'eigen'...
error: RPC failed; result=22, HTTP code = 422
fatal: the remote end hung up unexpectedly
Cloning into 'eigen'...
error: RPC failed; result=22, HTTP code = 422
fatal: the remote end hung up unexpectedly
-- Had to git clone more than once:
          3 times.
CMake Error at tmp/eigen-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://gitlab.com/libeigen/eigen'

gmake[2]: *** [/home/80280266user/work/ubuntu/mylite/tflite_build/src/eigen-populate-stamp/eigen-populate-download] Error 1
gmake[1]: *** [CMakeFiles/eigen-populate.dir/all] Error 2
gmake: *** [all] Error 2

CMake Error at /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:987 (message):
  Build step for eigen failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1082:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1082 (cmake_language)
  tools/cmake/modules/OverridableFetchContent.cmake:531 (FetchContent_Populate)
  tools/cmake/modules/eigen.cmake:39 (OverridableFetchContent_Populate)
  tools/cmake/modules/Findeigen.cmake:18 (include)
  CMakeLists.txt:128 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/80280266user/work/ubuntu/mylite/tflite_build/CMakeFiles/CMakeOutput.log".
See also "/home/80280266user/work/ubuntu/mylite/tflite_build/CMakeFiles/CMakeError.log".
[80280266user@RC802802663 tflite_build]$ 

solution:
er@RC802802663 tensorflow_src]$ git diff
diff --git a/tensorflow/lite/tools/cmake/modules/eigen.cmake b/tensorflow/lite/tools/cmake/modules/eigen.cmake
index 0b9080a476e..8879364bac2 100644
--- a/tensorflow/lite/tools/cmake/modules/eigen.cmake
+++ b/tensorflow/lite/tools/cmake/modules/eigen.cmake
@@ -21,7 +21,7 @@ include(OverridableFetchContent)
 
 OverridableFetchContent_Declare(
   eigen
-  GIT_REPOSITORY https://gitlab.com/libeigen/eigen
+  GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git
   # Sync with tensorflow/third_party/eigen3/workspace.bzl
   GIT_TAG 7b35638ddb99a0298c5d3450de506a8e8e0203d3
   # It's not currently (cmake 3.17) possible to shallow clone with a GIT TAG
[80280266user@RC802802663 tensorflow_src]$

**Comment by terryheo** [comment]
I think we've updated eigen tag. Do you still have the issue?

**Comment by liuchang3** [comment]
i check the modified code, it's solved now i think.
