### ISSUE TITLE
Run lite/tools/benchmark: setting use_hexagon to be true does not works.

### ISSUE THREAD

**Issue by yangruoqi** [tensorflow/tensorflow#52376]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung, cpuinfo: "Qualcomm Technologies, Inc KONA"
![image](https://user-images.githubusercontent.com/39039715/137239991-47fa8809-e78f-4955-99d3-ad3ff7ac0c6f.png)

- TensorFlow installed from (source or binary): source 
- TensorFlow version: commit id: 0088a1ada5a45c383e35c31ba7a552894936f998
![image](https://user-images.githubusercontent.com/39039715/137240102-942e1b22-9a43-4734-b024-67ed8e7d324b.png)

- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): bazel 3.7.2
- GCC/Compiler version (if compiling from source): gcc (GCC) 7.3.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Run lite/tools/benchmark: setting use_hexagon to be true does not works.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Build from source:
```
bazel build -c opt --config=android_arm --distdir=/usr1/tf_downloads --repository_cache=/usr1/tf_downloads tensorflow/lite/tools/benchmark:benchmark_model
```
2. push `benchmark_model` and `libhexagon_interface.so` to the phone
3. Run the model:
```
./benchmark_model --graph=video_infer.tflite --use_hexagon=true
```

```
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
```

![Snipaste_2021-10-14_10-14-07](https://user-images.githubusercontent.com/39039715/137240424-19c1b665-b485-4e38-b6bf-422dda385663.png)

> `libhexagon_nn_skel.so` is in the path `/vendor/lib/rfsa/adsp`, which is read-only file system. 

4. To solve the problem in step3, I download `libhexagon_nn_skel.so` from the [document](https://www.tensorflow.org/lite/performance/hexagon_delegate). I download hexagon_nn_skel.run of v1.21. `/vendor/lib/rfsa/adsp`  is read-only file system, so I push the `libhexagon_nn_skel.so` to path  `/data/local/tmp/tf` 

```
LD_PRELOAD=/data/local/tmp/tf/libhexagon_nn_skel.so ./benchmark_model --graph=video_infer.tflite --use_hexagon=true
```

```
CANNOT LINK EXECUTABLE "./benchmark_model": "/data/local/tmp/tf/libhexagon_nn_skel.so" is for EM_??? (164) instead of EM_ARM (40)
```

![image](https://user-images.githubusercontent.com/39039715/137242448-14680126-c881-4c38-b9e8-91f329764a78.png)

How can I run  `benchmark_model` with `use_hexagon=true`?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@yangruoqi Thanks for the report!
We see that you are using nightly version which is not a stable one could you please try to use TF **v2.6.0** and have a look at the guide to build from  [source,](https://www.tensorflow.org/install/source)[link](https://www.tensorflow.org/lite/performance/hexagon_delegate) for TF lite Hexagon.Please have a look at the [issue](https://github.com/tensorflow/tensorflow/issues/37506) for reference and let us know if it helps? Thank you!

**Comment by yangruoqi** [comment]
@sushreebarsa Thank you for your reply.
I got the code from the r2.6 branch and recompiled it. I replaced the phone with a Samsung S9 (Inc SDM845) but still got the error.

```
STARTING!
Log parameter values verbosely: [0]
Graph: [mobilenet_v2_1.0_224_quant.tflite]
Use Hexagon: [1]
Loaded model mobilenet_v2_1.0_224_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
Func remote_handle_control not available on this device (NULL).
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.

Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
Going to apply 0 delegates one after another.
The input model file size (MB): 3.57776
Initialized session in 41.075ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=15 first=43572 curr=34309 min=34210 max=43572 avg=34953.2 std=2305

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=34309 curr=34347 min=34182 max=34499 avg=34319.5 std=69

Inference timings in us: Init: 41075, First inference: 43572, Warmup (avg): 34953.2, Inference (avg): 34319.5
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=3.58984 overall=7.78516
```

This is my workspace on the phone, with benchmark_model and the *.so needed. 
![image](https://user-images.githubusercontent.com/39039715/137453210-fa9e2b6c-2568-404b-b7ce-a7d343b36a99.png)


Did I choose the wrong unsupported  device?  Or is there any other reason?

**Comment by karimnosseir** [comment]
If you're using benchmark tool push all your files to /data/local/tmp/  this is the default path the tool is configured to look for the shared libraries in.
