### ISSUE TITLE
Problem compiling tensorflow for iOS 

### ISSUE THREAD

**Issue by apphipster** [tensorflow/tensorflow#5237]
**Environment info:**
Operating System: macOS 10.11.6 
xcode 7.3.1 

**Steps to reproduce:**
I follow the steps from here [ios_examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples) and the steps specific to install for iOS described here
[makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)

**Basically what i did:**
- Clone the repository
- Download the graph
- Build

**Building all at once:** 

`tensorflow/contrib/makefile/build_all_ios.sh`

Results in:

```
+ PROTOC_PATH=/Users/ppcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc
+ [[ ! -f /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc ]]
+ echo 'protoc not found at /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.'
protoc not found at /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.
+ make_host_protoc /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host
+ [[ ! -n /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host ]]
+ HOST_GENDIR=/Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host
+ ./autogen.sh
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    172      0 --:--:-- --:--:-- --:--:--   172
100  362k  100  362k    0     0   177k      0  0:00:02  0:00:02 --:--:--  349k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    176      0 --:--:-- --:--:-- --:--:--   176
100  618k  100  618k    0     0   288k      0  0:00:02  0:00:02 --:--:--  511k
+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1


```

**Building by hand:**

I have downloaded all dependencies with the command:
`tensorflow/contrib/makefile/download_dependencies.sh`
Result:
`download_dependencies.sh completed successfully.`

**Than when I try to compile protobufs:**

`tensorflow/contrib/makefile/compile_ios_protobuf.sh`

**I have the following result, similar to the one from above:**

```
+ PROTOC_PATH=/Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc
+ [[ ! -f /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc ]]
+ echo 'protoc not found at /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.'
protoc not found at /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc. Build it first.
+ make_host_protoc /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host
+ [[ ! -n /Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host ]]
+ HOST_GENDIR=/Users/appcenter/Documents/devDownloads/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host
+ ./autogen.sh
+ autoreconf -f -i -Wall,no-obsolete
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1


```

**Observation:**

When I look into the folder from bellow it contains an empty folder named lib:
`tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios`

The folder from bellow is empty:
`tensorflow/tensorflow/contrib/makefile/gen/protobuf-host`

Conclusion: it seems to me that there is a problem building protobuf.
What does the message "Google Mock not present." exactly mean?

**Comment by drpngx** [comment]
Google Mock is the testing framework, which is downloaded automatically. We've had problems with `glibtoolize` in the past. Let me see...

**Comment by drpngx** [comment]
Just making sure: `brew install libtool`?

**Comment by apphipster** [comment]
Yes, **libtool** is installed correctly.
The folder usr/local/Cellar have the following content:
**cmake** -  installed a long time ago
**autoconf** - installed recently v 2.69
**automake** - installed recently v 1.15
**libtool** - installed recently v 2.4.6

**Comment:** 
I have parallel two versions of Xcode installed but I don't think it is causing any problem:
Applications/Xcode - v 7.3.1
Applications/Xcode8 - v 8

**Comment by drpngx** [comment]
Do you have aclocal as well? Can you run libtoolize --force?

**Comment by apphipster** [comment]
**When I try to install libtool:**
```
brew install libtool
Warning: libtool-2.4.6 already installed, it's just not linked

```

**When I try to install libtoolize:**
```
brew install libtoolize
Error: No available formula for libtoolize 
==> Searching formulae...
==> Searching taps...
==> You haven't updated Homebrew in a while.
A formula for libtoolize might have been added recently.
Run `brew update` to get the latest Homebrew updates!
MacBook-Air:tensorflow audiappcenter$ brew update

```

**I have libtool but not libtoolize :**
/usr/local/Cellar/libtool/2.4.6/share/aclocal/libtool.m4

**Comment by drpngx** [comment]
this is the libtool m4 macro file, but not libtool itself.
can you try

```
which libtool
```

**Comment by apphipster** [comment]
```
$ which libtool
/usr/bin/libtool
```

**Comment by aminbenarieb** [comment]
Same error.

**Comment by aminbenarieb** [comment]
Fixed by reinstalling libtool: `brew uninstall libtool && brew install libtool`.

**Comment by apphipster** [comment]
When trying to 
`$ brew uninstall libtool && brew install libtool`

It displays the message:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/libltdl
/usr/local/include is not writable.
```

Create the folder (if not exist) and take ownership of it:
`$ sudo mkdir /usr/local/include`
`$ sudo chown -R $USER:admin /usr/local/include`

Now try to build:
`$ tensorflow/contrib/makefile/compile_ios_protobuf.sh`

**I managed to compile tensorflow now.**
I have observed only some deprecation warnings like this one:
` warning: 'OSAtomicAdd32' is deprecated: first deprecated in macOS 10.12`

Many thanks for help!

**Comment by honghaoli** [comment]
Same here! 

Followed all the discussion above, also did
`brew uninstall libtool && brew install libtool`

Now my error information is:
`+ HOST_GENDIR=/Users/honghaoli/git_folder/tensorflow/tensorflow/contrib/makefile/gen/protobuf-host
+ ./autogen.sh
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    417      0 --:--:-- --:--:-- --:--:--   418
100  362k  100  362k    0     0   440k      0 --:--:-- --:--:-- --:--:-- 2110k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    393      0 --:--:-- --:--:-- --:--:--   394
100  618k  100  618k    0     0   611k      0  0:00:01  0:00:01 --:--:-- 2106k
+ autoreconf -f -i -Wall,no-obsolete
Can't exec "libtoolize": No such file or directory at /usr/local/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN8> line 6.
autoreconf: failed to run libtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool`


Help please!

**Comment by honghaoli** [comment]
` which libtool
   /usr/bin/libtool`

**Comment by honghaoli** [comment]
Now it works.

turns out there is already Apple's own `libtool`;
`⇒  brew uninstall libtool && brew install libtool
  Uninstalling /usr/local/Cellar/libtool/2.4.6_1... (70 files, 3.7M)
  ==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.sierra.bottle.tar.gz
  Already downloaded: /Users/honghaoli/Library/Caches/Homebrew/libtool-2.4.6_1.sierra.bottle.tar.gz
  ==> Pouring libtool-2.4.6_1.sierra.bottle.tar.gz
  ==> Caveats
  In order to prevent conflicts with Apple's own libtool we have prepended a "g"
  so, you have instead: glibtool and glibtoolize.
  ==> Summary
  🍺  /usr/local/Cellar/libtool/2.4.6_1: 70 files, 3.7M`

So I have to rename glibtool and glibtoolize back to libtool and libtoolize.

Just post it here in case anyone has the same issue later.

**Comment by AndreJFBico** [comment]
Im having a similar issue with either release 1.2.1, 1.2 or 1.1

```
libtool: link: g++ -D_THREAD_SAFE -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.0 -arch i386 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk -D_THREAD_SAFE -arch i386 -fembed-bitcode -mios-simulator-version-min=8.0 -stdlib=libc++ -o protoc google/protobuf/compiler/main.o -Wl,-bind_at_load  -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/usr/lib/system ./.libs/libprotobuf.a ./.libs/libprotoc.a /Users/Andre/BazelWorkSpace/TensorFlowForked/tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotobuf.a -lz -lc++ -lc++abi
ld: -bind_at_load and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [protoc] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
