### ISSUE TITLE
tf.image.non_max_suppression_padded returns dynamic-sized tensors: fails on TFlite GPU Delegate

### ISSUE THREAD

**Issue by alexdwu13** [tensorflow/tensorflow#52388]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Mobile device: Snapdragon 845 (Pixel 3, Galaxy S9)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7

**Describe the current behavior**
Exporting `tf.image.non_max_suppression_padded` to tflite yields a model that fails to run on the TFlite GPU delegate:
```
$ ./android_aarch64_benchmark_model --use_gpu=true --graph=nms (3).tflite                                                                       
STARTING!
Log parameter values verbosely: [0]
Graph: [nms (3).tflite]
Use gpu: [1]
Loaded model nms (3).tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
Failed to apply GPU delegate.
Benchmarking failed.
```

**Describe the expected behavior**
Compared to `tf.image.non_max_suppression`, `tf.image.non_max_suppression_padded` should not return dynamic-sized tensors, and should therefore be able to run on the GPU delegate.

**Standalone code to reproduce the issue**
Collab to reproduce model:
https://colab.research.google.com/drive/14KIEfiNIHB9q2erUgHs3uwEY4mxvgGeU?usp=sharing

Model:
[nms (3).tflite.zip](https://github.com/tensorflow/tensorflow/files/7355110/nms.3.tflite.zip)

Benchmarking tool:
[android_aarch64_benchmark_model.zip](https://github.com/tensorflow/tensorflow/files/7349358/android_aarch64_benchmark_model.zip)
(source: https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary )

![image](https://user-images.githubusercontent.com/20094729/137530204-f1bd75d0-44b2-40e5-bfa2-d4d944f91f31.png)

**Comment by alexdwu13** [comment]
@mohantym https://gist.github.com/alexdwu13/cb08ceea33c546c1fcabac3b1b6b0c25

**Comment by pkgoogle** [comment]
Hi @alexdwu13, it appears the fix is merged, please close if this issue is now resolved.
