### ISSUE TITLE
More descriptive error message when op is not defined for GPU or CPU

### ISSUE THREAD

**Issue by sguada** [tensorflow/tensorflow#524]
When trying to use MaxPoolWithArgmax I got the following error:

InvalidArgumentError: No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs
	 [[Node: MaxPoolWithArgmax_5 = MaxPoolWithArgmax[Targmax=DT_INT64, ksize=[1, 3, 3, 1], padding="SAME", strides=[1, 2, 2, 1]](random_normal_4)]]

Which doesn't tell me that the op is available in GPU but not in CPU.

**Comment by LeavesBreathe** [comment]
I second this as well -- someting that would clearly define gpu compatibility would be great. If the documentation had it, that would be even better. 

On the docs, we could just assume all ops are gpu compatible, but if they are marked as "CPU only", it would help!!!

**Comment by vrv** [comment]
The op may be defined on GPU, but just not for those specific set of attributes (e.g., it could have been the case that it was defined for Targmax=DT_INT32).

It would be too cryptic of an error message to enumerate all possible registrations for that Op (which might be tens of kernels) in the error message. 

In addition, it's totally legal for an op to be defined on GPU, but the binary to not include it, so even if we put something in the docs, it wouldn't be right.

I agree that we could do a better job here, but it'll take some care to make sure we don't spam the error message with content that nobody can read.

**Comment by martinwicke** [comment]
Maybe it is enough to change the error by adding the information which
placement was requested:

InvalidArgumentError: No OpKernel was registered to support Op
'MaxPoolWithArgmax' *for device '/gpu:0'* with these attrs
[[Node: MaxPoolWithArgmax_5 = MaxPoolWithArgmaxTargmax=DT_INT64, ksize=[1,
3, 3, 1], padding="SAME", strides=[1, 2, 2, 1] <http://random_normal_4/>]]

**Comment by jacksonloper** [comment]
Newbie question: how do I get a list of all registered opkernels?  If it's easy, the error message could advise the user on how to peruse the list.  It would then become obvious to the user that, e.g., the op they wanted wasn't registered for the gpu...

**Comment by syed-ahmed** [comment]
Can anyone help me with this No opkernel registered error: #1269 . Following from the main.cc in label_image example and looking into the android demo tensorflow_jni.cc, I see that the android demo is directly reading the RGB values and putting it into an input tensor, whereas the label_image example builds a graphdef builder and runs several ops to derive to its input tensor. Could this difference be the reason for that error?

**Comment by girving** [comment]
@martinwicke, @vrv: Martin's suggested fix seems reasonable.  Should we assign this to someone or give some more details are and mark it contributions welcome?

**Comment by vrv** [comment]
I believe we have fixed the error message to be much more helpful, but someone would have to verify ;)

**Comment by girving** [comment]
It doesn't look like we fixed it: https://github.com/tensorflow/tensorflow/blob/e9953ee70d45bfba8083eaa7ac902714f1a0b0a5/tensorflow/core/common_runtime/simple_placer.cc#L514

**Comment by vrv** [comment]
That codepath only gets hit if there are no kernels at all that support that op.  There is no placement specified, and no kernels registered.  I think the situation @sguada has been fixed, you're pointing at a different error path.

**Comment by girving** [comment]
@vrv: Assigning to you since you seem to be the C++ runtime czar.  Feel free to reassign.

**Comment by girving** [comment]
Oops, sorry, missed your comment.  Never mind.

**Comment by YutingZhang** [comment]
I am using TF1.1. I found this op have no CPU kernel for either Targmax=tf.int32 or Targmax=tf.int64. For GPU (CUDA8 on a Titan X), it has kernel for Targmax=tf.int64, but no kernel for Targmax=tf.int32

**Comment by martinwicke** [comment]
Did you find the error message to be bad? If so, can you paste the error message here, and how you would have improved it?

If your comment is about the absence of the kernel registration, please open a separate issue (or send a PR).

**Comment by caffinatedmonkey** [comment]
@jacksonloper You can find a list of opcodes available in the makefile build from here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt
