### ISSUE TITLE
Windows GPU gradient always 0 but CPU works

### ISSUE THREAD

**Issue by Bren077s** [tensorflow/tensorflow#5242]
Hello all,
I was working on installing and testing the new windows gpu support and it does not seem to be working right for me. To start off, I was following [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md) and I have all of the same software as their windows 10 known good configuration, except I have Microsoft Visual Studio **Community** 2015 with Visual C++ 2015.
My github head is: 2cbb9b529a6723ebbe07663156b18c04fbaf4531
After I few times of trying to get it to install, I managed to get it to install by changing to cmake 3.6 from 3.7. It installed fine but it does not seem to work properly. 
I downloaded some known good code, file [here](http://pastebin.com/AiTaaizs), and when I run it specifiying that tensorflow should use cpu, I get good output that looks like [this](http://pastebin.com/nQFcMZ07). If I allow it to run on gpu, I get bad output that looks like [this](http://pastebin.com/dcDYsfWr). I am not sure why. I feel like it is probably an issue with my install even though it had no errors. Any help would be greatly appreciated.

**Comment by drpngx** [comment]
Sorry, it doesn't work on 3.7. We're amending the documentation PR #5103 . I think it's possible to make it work, but not out of the box.

**Comment by Bren077s** [comment]
I know that it doesn't work on 3.7. I got it to install by changing from cmake 3.7 to cmake 3.6, but even though it installed, it does not run code properly on gpu for me. As shown by the above outputs, the code fails on gpu but works fine on cpu.

**Comment by drpngx** [comment]
We're still working on the windows GPU, which is an outstanding community contribution, so not everything works quite yet. We're hoping to get more fixes in the next few days.

@guschmue FYI

**Comment by Bren077s** [comment]
Thanks for the information. I will make sure to stay in tune. I will also mess around and see if I can get it to work.

**Comment by guschmue** [comment]
This sounds a lot like https://github.com/tensorflow/tensorflow/pull/5207. 
I ran your sample code on my box and it works ok.

**Comment by drpngx** [comment]
@Bren077s Please try @guschmue 's PR or wait until we push.

**Comment by Bren077s** [comment]
I tried installing tensorflow, by using the commands you told me and I got new errors. I also tried downloading directly from @guschmue github fork of tensorflow and got the same errors. Here are the errors that I get: [Errors](http://pastebin.com/f8eb3Qrr)

**Comment by guschmue** [comment]
This was fixed with: https://github.com/tensorflow/tensorflow/pull/5157 and merged into the master yesterday. #5207 was merged today into the master.
I have a jenkins for windows gpu following the master and its happy.

**Comment by drpngx** [comment]
Nice!
