### ISSUE TITLE
Allow setting session level options and run_metadata in SKFlow Estimator.fit()

### ISSUE THREAD

**Issue by momeara** [tensorflow/tensorflow#5244]
Feature request: Allow specifying `Session.run()` parameters `options` and `run_metadata` when calling `Estimator.fit()`.  

Use case: The [Chrome Timeline profiling method](http://stackoverflow.com/questions/37751739/tensorflow-code-optimization-strategy/37774430#37774430) requires setting these options.

Possible implementation:  add an additional fields to the `RunConfig` class that can be set when when the `Estimator` is initialized. Then pass these options to `graph_actions._monitored_train()`, which then added them to the `MonitoredSession.run()` function call.

**Comment by drpngx** [comment]
@martinwicke does that look like something we'd want to have?

**Comment by martinwicke** [comment]
We're actually working on that. It will likely be in the form of exactly what you have outlined: the ability to give a RunOptions proto as part of RunConfig.

**Comment by momeara** [comment]
fantastic, I look forward to it.

**Comment by buptjz** [comment]
hello,does Estimator has this feature yet? @drpngx

**Comment by martinwicke** [comment]
We got sidetracked, so no, I am sorry.

**Comment by caixuanting** [comment]
Is this feature ready yet?

Thanks.

**Comment by caixuanting** [comment]
I thought it would be a simple change by adding 2 more fields in RunConfig proto, is it?

Thanks.
