### ISSUE TITLE
mean_squared_error gives warning about sum_of_squared_error

### ISSUE THREAD

**Issue by weiliu620** [tensorflow/tensorflow#5245]
I used tf.contrib.losses.mean_squared_error, but during training stage, tensorflow give me warning ```WARNING:tensorflow:sum_of_squares (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-10-01.```

But I already used mean_squared_error, so this warning should not show. 

Also the mean_squared_error [definition link](https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.losses.html#mean_squared_error) has the same warning, which I guess should not be there?

**Comment by drpngx** [comment]
What version are you using? In the current version it's been removed (as threatened).

**Comment by weiliu620** [comment]
tf.__version__ gives me '0.10.0'. Yeah, I guess that's the reason. I may need update my TF version. (would be good to see the document update, though)

**Comment by drpngx** [comment]
I don't know that we cherry-pick for errors in documentation, but if so, you're welcome to submit a PR.

@yifeif @gunan

**Comment by gunan** [comment]
We probably wont update 0.10 docs, as we are working on finalizing 0.11 now.

**Comment by weiliu620** [comment]
Wait...when I upgrade TF to 0.11.0rc1, I still get the same warning when using mean_squared_error. Also, more surprisingly, ```sum_of_squares``` and ```mean_squared_error``` gives me same results, and it looks the result is the mean squared error. 

I hope it's a small issue, because ```sum_of_squares``` is deprecated anyway.

**Comment by gunan** [comment]
If we have a doc update for 0.11, we are accepting them until EOD today.

**Comment by drpngx** [comment]
It's been removed at `HEAD`, so I think it's OK. It's not easy to fix the docs so I think it's fine to have that little quirk.

FTR, we had

```python
@deprecated("2016-10-01", "Use mean_squared_error.")
def sum_of_squares(predictions, targets, weight=1.0, scope=None):
 ...

mean_squared_error = sum_of_squares
```
