### ISSUE TITLE
tensorboard demos don't work because of wrong paths

### ISSUE THREAD

**Issue by kierson** [tensorflow/tensorflow#5247]
Checked on commit 32d1dcc10e1fdf33dc6742337c6e0869f7b3c557.

Issue:
While going through tensorboard/DEVELOPMENT.MD it is not possible to have tensorboard's demos working as demo's html as well as components htmls import other html with wrong file names.

For example in:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/demo/index.html

there is an import of `../components/tf-tensorboard/tf-tensorboard.html` and in fact this file doesn't exist. It exist under slightly different file name with replaced "-" with "_" (../components/tf_tensorboard/tf-tensorboard.html)

The difference is in directory names.
The same occurs if I want to load particular component's demo.

**Comment by drpngx** [comment]
Nice find! Do you have a PR you could send?

@danmane to double-check

**Comment by SriramRamesh** [comment]
https://github.com/tensorflow/tensorflow/pull/5262

**Comment by SriramRamesh** [comment]
This issue can be closed. 
Changes have been merged.

**Comment by drpngx** [comment]
Thanks for reporting back!

**Comment by kierson** [comment]
Hey again.
The merged PR is not the real fix as directory names should be changed because more html files depend on old names (names with "-" not with "_").
Basically currently any single html file inside https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tensorboard/components and subdirectories has wrong paths.

**Comment by drpngx** [comment]
Ouch, right. Feel free to send a general PR.
