### ISSUE TITLE
AttributeError: 'module' object has no attribute 'save_v2'

### ISSUE THREAD

**Issue by cyc** [tensorflow/tensorflow#5249]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
/usr/local/cuda/lib64/libcudadevrt.a	/usr/local/cuda/lib64/libcudart.so.8.0.44  /usr/local/cuda/lib64/libcudnn.so.5
/usr/local/cuda/lib64/libcudart.so	/usr/local/cuda/lib64/libcudart_static.a   /usr/local/cuda/lib64/libcudnn.so.5.1.5
/usr/local/cuda/lib64/libcudart.so.8.0	/usr/local/cuda/lib64/libcudnn.so	   /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
`0.11.0rc1`

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
`tf.train.Saver(..., write_version=tf.train.SaverDef.V2)`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1077, in __init__
   self.build()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1106, in build
   restore_sequentially=self._restore_sequentially)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 702, in build
   save_tensor = self._AddSaveOps(filename_tensor, saveables)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 309, in _AddSaveOps
   save = self.save_op(filename_tensor, saveables)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 252, in save_op
   return io_ops.save_v2(filename_tensor, tensor_names, tensor_slices,
AttributeError: 'module' object has no attribute 'save_v2'
```

**Comment by drpngx** [comment]
@concretevitamin This is straight from our pip package. I don't see how this could have passed the tests.

**Comment by drpngx** [comment]
@yifeif that is the rc1 package. I looked at the `training.py` and it's not like `HEAD`. Not sure what it's supposed to be.

**Comment by drpngx** [comment]
`saver.py` does indeed have `save_v2`, but `ops/io_ops` doesn't have `Register.*V2`.

**Comment by yifeif** [comment]
@concretevitamin could you take a look?

**Comment by concretevitamin** [comment]
I'll take a look tomorrow.

**Comment by concretevitamin** [comment]
Sorry for the troubles -- rc2 will likely not have this issue (we either will completely release the V2 functionalities, or none of it will go in; TBD).

Are you eager to use V2 right now to save peak memory?

**Comment by cyc** [comment]
No, using v2 is not hugely important. I just tried it out because I heard v1 was going to be deprecated soon.

**Comment by drpngx** [comment]
OK, closing. rc2 will do it, and you can use v1 in rc1.

**Comment by jmoney4769** [comment]
I am getting this same issue using rc2 on Mac OSX el capitan.  Python 2.7, CPU only in Anaconda.  It works fine when I build from source, but using the pip package it does not work.  I downloaded the rc2 pip package today to check and installed using `pip install --ignore-installed --upgrade $TF_BINARY_URL` while my environment is activated.  $TF_BINARY_URL was set using `export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc2-py2-none-any.whl`

**Comment by concretevitamin** [comment]
@jmoney4769 can you try installing that pip package using a fresh environ?

**Comment by jmoney4769** [comment]
@concretevitamin Tried a couple of things:
First, same environment, I ran `pip install --ignore-installed $TF_BINARY_URL` (not no upgrade here).  Same results.

Second, I ran `pip uninstall tensorflow` then `pip install --ignore-installed $TF_BINARY_URL`.  Same results.

Third, I created a new environment (`conda create -n test python=2.7 -y`), then `source activate test` then `pip install --ignore-installed $TF_BINARY_URL`.  Same results as before.  

The pip package created when building from source works when installing to a clean environment.

**Comment by yifeif** [comment]
@jmoney4769, thanks for your feedback. Let me take a look at our pip packages and get back to you.

**Comment by yifeif** [comment]
@jmoney4769, could you give "pip install" with $TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc2-py2-none-any.whl another shot?

**Comment by jmoney4769** [comment]
That is working now.  Thank you for the quick responses.
