### ISSUE TITLE
Consider adding tf.identity_like()

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#525]
Hey TF, 

This is not a big deal, but you may want to add an identity_like function that theano has here:
http://nullege.com/codes/search/theano.tensor.identity_like

It would be useful for orthogonality with RNN's. 

It would basically be something like:

```python
def identity_like(input_tensor, scope = None):
  with tf.variable_scope(scope or "identity_like"): #in this linear scope, the library that you're retriving is Linear
    shape_0 = tf.shape(input_tensor)[0]
  return tf.diag(tf.ones(shape_0))
```

**Comment by Hello1024** [comment]
Please consider a different API here.

I could imagine "ones_like()", "uniform_random_like()", etc. quickly causing clutter.

**Comment by martinwicke** [comment]
Maybe an op that copies the shape, but lets you pass an initializer (many
of those functions already exist, and more should exist anyway)?

**Comment by girving** [comment]
Dup of #434.
