### ISSUE TITLE
Document whether the GPU execution of concrete functions are asynchronous

### ISSUE THREAD

**Issue by tfeher** [tensorflow/tensorflow#52520]
## URL(s) with the issue:
- https://www.tensorflow.org/guide/eager#performance
- https://www.tensorflow.org/guide/intro_to_graphs#seeing_the_speed-up
- https://www.tensorflow.org/api_docs/python/tf/experimental/async_scope

## Description of issue (what needs changing):
The comment in the example code at https://www.tensorflow.org/guide/eager#performance states:
```
# tf.matmul can return before completing the matrix multiplication
# (e.g., can return after enqueing the operation on a CUDA stream).
# The x.numpy() call below will ensure that all enqueued operations
# have completed
```

In contrast, the benchmark script at https://www.tensorflow.org/guide/intro_to_graphs#seeing_the_speed-up do not contain the `numpy()` call:

```python
def power(x, y):
  result = tf.eye(10, dtype=tf.dtypes.int32)
  for _ in range(y):
    result = tf.matmul(x, result)
  return result

print("Eager execution:", timeit.timeit(lambda: power(x, 100), number=1000))

power_as_graph = tf.function(power)
print("Graph execution:", timeit.timeit(lambda: power_as_graph(x, 100), number=1000))
```

Is the second example correct, don't we need a `numpy()` call to ensure that the computation is completed?

### Improve the documentation of graph function execution

While reading through the guides https://www.tensorflow.org/guide/intro_to_graphs#graph_execution_vs_eager_execution and https://www.tensorflow.org/guide/function, I did not find any reference to the possibly asynchronous nature of function execution.

Can we improve the guide by stating that 
```
A graph function can return before completing the computation (e.g., can return after enqueing the operation on a CUDA stream).
```
~~If this is not the case, then can we state that explicitly?~~

### async_scope

The description at https://www.tensorflow.org/api_docs/python/tf/experimental/async_scope mentions that "function calls inside the scope can return before finishing the actual execution. ". But looking into the source code indicates that the scope controls whether remote executions are synchronous.

What is the status with a function execution on a local GPU? Is that affected by this scope? Could you expand the docstring with this information?

**Comment by tfeher** [comment]
In general, there is a difference in terminology what do we mean by "synchronous". `async_scope`, or `tf.config.experimental.set_synchronous_execution` use a different meaning, compared to what we use in CUDA terminology.

For reference: [async_wait](https://github.com/tensorflow/tensorflow/blob/2f73ac99e94c1e0c8a8b6ce0efdb3d11b834fe3d/tensorflow/python/eager/context.py#L2571) (used by `set_synchronous_execution` ) is calling [SyncExecutors](https://github.com/tensorflow/tensorflow/blob/2f73ac99e94c1e0c8a8b6ce0efdb3d11b834fe3d/tensorflow/core/common_runtime/eager/context.cc#L929) which uses WaitForAllPendingNodes. The C wrapper has the [following docstring](https://github.com/tensorflow/tensorflow/blob/799eb5181378cbdbcf77002366f89d99e805c803/tensorflow/c/eager/c_api_experimental.h#L346-L353):

// Causes the calling thread to block till all ops dispatched in this executor
// have been executed. Note that "execution" here refers to kernel execution /
// scheduling of copies, etc. Similar to sync execution, it doesn't guarantee
// that lower level device queues (like GPU streams) have been flushed.

**Comment by sachinprasadhs** [comment]
Since in the document https://www.tensorflow.org/guide/intro_to_graphs#seeing_the_speed-up, it is the comparison between eager and `tf.function`, if you use numpy() it will throw error, since `numpy()` is not supposed to be used in the graph mode or inside tf.function.

**Comment by tfeher** [comment]
Thank you @sachinprasadhs for the answer. If we want to compare performance of any calculation, we need to ensure that the calculation is finished. The question of this issue: how to ensure that the calculation is finished when we are working with GPU kernels. For the https://www.tensorflow.org/guide/intro_to_graphs#seeing_the_speed-up link, this is how to insert the numpy calls to ensure synchronization:

```python
def power(x, y):
  result = tf.eye(10, dtype=tf.dtypes.int32)
  for _ in range(y):
    result = tf.matmul(x, result)
  return result

print("Eager execution:", timeit.timeit(lambda: power(x, 100)[0].numpy(), number=1000))

power_as_graph = tf.function(power)
print("Graph execution:", timeit.timeit(lambda: power_as_graph(x, 100)[0].numpy(), number=1000))
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
