### ISSUE TITLE
whether there is a timeout value can be set for bazel building download action?

### ISSUE THREAD

**Issue by flowold** [tensorflow/tensorflow#52527]
When I use bazel build tensorflow, which will download a lot of rep, so often timeout and rebuild and timeout agian...
whether thesre is a timeout value can be set for download action for bazel?

**Comment by tilakrayal** [comment]
@flowold ,
Can you please refer this [link](https://docs.bazel.build/versions/main/user-manual.html#bazelrc) which provided the more information.It helps.Thanks

**Comment by hushanxue** [comment]
> When I use bazel build tensorflow, which will download a lot of rep, so often timeout and rebuild and timeout agian... whether thesre is a timeout value can be set for download action for bazel?

Excuse  me, how to set the timeout for bazel? with that [link](https://docs.bazel.build/versions/main/user-manual.html#bazelrc), not found the right one
