### ISSUE TITLE
Let user to choice whether to do bazel clean during configure

### ISSUE THREAD

**Issue by EricFisher** [tensorflow/tensorflow#5253]
Currently running the configure will do 'bazel clean --expunge' by default.  It is OK for the first time to run configure.  But when I need to rerun the configure (because some errors occur, I will retry), I have to spend much time to download files from internet again each time during to the execution of 'bazel clean --expunge'. 

So, should we let user to choice whether to do bazel clean during configure?

**Comment by drpngx** [comment]
@jart 

I have also been puzzled by that. It prevents using the cache, and doesn't really belong in a configure script. You can use sed s/bazel.clean/true/ <configure|bash as a workaround.

**Comment by jart** [comment]
The `bazel clean --expunge` and `bazel fetch //tensorflow/...` need to happen unfortunately to work around bugs in Bazel. There's issues relating to cache invalidation on remote repositories. There's also issues relating to passing environment variables to repository rules. CC: @davidzchen

It'd probably be better if we didn't have an option to disable the clean and fetch. We want to guarantee that builds work, even if that means things go a little slower. We're going to be improving the state of the build real soon though. We're actually planning to make the configure script optional. I think the Bazel team is doing amazing work helping to make that happen.

Thanks for bringing this to our attention. Feel free to post any other questions you might have and I'll be happy to answer them.

**Comment by jart** [comment]
One other note, if you're 100% certain you want to roll the dice by disabling the clean and fetch, it shouldn't be too difficult to comment out those lines in the configure script.

**Comment by drpngx** [comment]
If you have a link to the issue, please post here and/or in the code.

**Comment by jart** [comment]
It's possible that the related issues are https://github.com/bazelbuild/bazel/issues/1022 and https://github.com/bazelbuild/bazel/issues/1595 and https://github.com/bazelbuild/bazel/issues/974. There was another one, but I'm having trouble digging it up.

Also here is an explanation that @davidzchen gave me a week ago regarding the necessity of fetch.

> The reason why we fetch in the configure script is because the way the script
> passes values to the cuda_configure workspace rule is via environment variables
> (see comment at the top of [cuda_configure.bzl](https://github.com/tensorflow/tensorflow/blob/d95a5b7cc6dca2d3603d73da1078274b29639ec7/third_party/gpus/cuda_configure.bzl)).

> The configure script exports these environment variables before calling bazel
> fetch, which will set up external repositories, such as @local_config_cuda,
> according to the values provided by the user. However, if we do not do this,
> when the user runs bazel fetch/build after running ./configure, then
> cuda_configure will use the environment variables in the user's shell, which
> would not contain any of the values set by ./configure.

> That is, with this change, even if the user runs ./configure to enabling
> building with CUDA, when the user subsequently runs bazel build, the build will
> fail because @local_config_cuda would have been configured without GPU support.

> It might be more ideal to be able to pass values to Skylark repository rules
> via command line flags. For example, something like the following would build
> with CUDA support enabled, and cuda_configure would look for the cuda
> installation in a set of standard install locations:

>     bazel build --enable_cuda //tensorflow/...

> If the user would like to specify a custom cuda install location, then she
> would be able to do so with another flag:

>     bazel build --enable_cuda --cuda_toolkit_path=/opt/local //tensorflow/...

> If adding arbitrary flags is not feasible, then perhaps we can use an approach
> similar to the kubernetes vars:

>     bazel build --vars=enable_cuda=true,cuda_toolkit_path=/opt/local //tensorflow/...

> These are hypothetical examples, and I haven't scoped out the work that would
> be required to implement this feature. However, with the way things are set up
> currently, removing the fetch from the configure script would cause the build
> to fail.

We're also working hard to pay off the technical debt in TensorFlow that is contributing to this broader problem. For example, we recently committed https://github.com/tensorflow/tensorflow/commit/1dba78b997dc49df9df663a838e0bacd6602f5b8 which removes SWIG from the configure script. So we're one step closer to having a hermetically sealed build.

Once the Bazel bugs are fixed, and once TensorFlow is fully hermetically sealed, `bazel clean` will become a command that no one will ever need to run again.

**Comment by drpngx** [comment]
Nice, thanks!

**Comment by Randl** [comment]
https://github.com/bazelbuild/bazel/issues/2033
If I try to build tensorflow on NFS, it's necessary to provide `--output_user_root` for `clean` to work properly

**Comment by davidzchen** [comment]
FYI @damienmg is working on [improvements](https://bazel-review.googlesource.com/c/6697/3/site/designs/_posts/2016-10-18-repository-invalidation.md) to Bazel's Skylark remote repositories to both improve its caching and invalidation and make it possible to pass environment variables to workspace rules, which will enable us to implement the kind of interface I suggested in [@jart's comment](https://github.com/tensorflow/tensorflow/issues/5253#issuecomment-257000911).
