### ISSUE TITLE
Ref() does not return the same ref for the element.

### ISSUE THREAD

**Issue by MalcolmMielle** [tensorflow/tensorflow#52537]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 34
- TensorFlow installed from (source or binary): 2.6.0
- Python version: 3.9.7

**Describe the current behavior**

When loading MINST and requesting the ref() of the first element, it is not equal to itself.

**Describe the expected behavior**

The element should have the same ref at all time.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no, I don't know why it's doing this.

**Standalone code to reproduce the issue**

```
import tensorflow_datasets as tfds

# %% Train dataset
(ds_train_original, ds_test_original), ds_info = tfds.load(
    "mnist",
    split=["train", "test"],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)

iterator = iter(ds_train_original)
el = iterator.get_next()[0]
el[0].ref() == el[0].ref()   # <- this should be True
```

**Comment by tilakrayal** [comment]
@MalcolmMielle ,
I tried to reproduce the issue and haven't found any issue in execution.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/420e1417beb10b77183748861756b074/untitled92.ipynb).Can you please provide the error you are facing or more details about the issue mentioned.It helps to analyse the issue.Thanks

**Comment by MalcolmMielle** [comment]
@tilakrayal 
Thanks for looking it up. I have updated the gist [here](https://colab.research.google.com/gist/MalcolmMielle/ca49d1687fdc608f6243ed73d6e507fd/untitled92.ipynb). I have simply added the last comparison into an assert to show the difference in the refs of `el[0]` even thought it is the same element.

The last line of the gist IMO should return True. However, this is False.

According to the ref documentation:
_Returns a hashable reference object to this Tensor. The primary use case for this API is to put tensors in a set/dictionary._

My understanding is that you should be able to use the ref() to check for equality between Tensor. Here the problem doesn't happen anymore once I have extracted the ref. For example, this is True:

```
a_ref = el[0].ref()
a_deref = a_ref.deref()
another_ref = a_deref.ref()
a_ref == another_ref
```

So the "problem" seems confined to extracting the ref() from iterator.

**Comment by sachinprasadhs** [comment]
You can use [tf.data.experimental.sample_from_datasets](https://www.tensorflow.org/api_docs/python/tf/data/experimental/sample_from_datasets) and set seed in the parameter to get the consistent behavior.

**Comment by MalcolmMielle** [comment]
This [gist](https://colab.research.google.com/gist/MalcolmMielle/ca49d1687fdc608f6243ed73d6e507fd/untitled92.ipynb) still crashes on the assert. Is that what you meant?

**Comment by sachinprasadhs** [comment]
Sorry my bad, above reference was for multiple dataset, for checking if both the iter items are same, you can convert the tensor to numpy and test with .all(). 
Here is the [gist](https://colab.research.google.com/gist/sachinprasadhs/8655f7bcd83c9591eff0d73b5a9122be/untitled92.ipynb) for reference.

**Comment by MalcolmMielle** [comment]
This seems like the perfect solution for datasets like MNIST where each input is distinct. Thanks for the gist!
However, for other dataset where multiple samples can be identical, that method can return `True` for two similar samples, right?

Thanks for taking the time to answer on this thread. I really appreciate the help!

**Comment by sachinprasadhs** [comment]
Yes, if the two samples are identical it should return True.
