### ISSUE TITLE
TensorFlow unit test failure python/kernel_tests:self_adjoint_eig_op_test

### ISSUE THREAD

**Issue by K1504296** [tensorflow/tensorflow#52544]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Aarch64 Centos-8
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.6.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the current behavior**

Running the bazel : python/kernel_tests/self_adjoint_eig_op_test fails. 
Building the self_adjoint_eig_op_test with the following command: 
`bazel build --flaky_test_attempts=3 --test_output=all --cache_test_results=no --noremote_accept_cached --config=noaws --config=nogcp --config=nonccl --verbose_failures -- //tensorflow/python/kernel_tests:self_adjoint_eig_op_test`

dtypes of float32 and complex64 with a [size](https://github.com/tensorflow/tensorflow/blob/5646333e1ece8170dff7b1980905e8f9c8383881/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py#L247) of 10 all fail while the rest pass:
```
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_float32_3_10_10_True
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_float32_3_10_10_False
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_float32_10_10_True
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_float32_10_10_False
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex64_3_10_10_True
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex64_3_10_10_False
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex64_10_10_True
[  FAILED  ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex64_10_10_False

[       OK ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex128_3_10_10_False
[       OK ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_complex128_3_10_10_True
[       OK ] SelfAdjointEigGradTest.test_SelfAdjointEigGrad_float64_3_10_10_True
```

This error is occurs on Aarch64 after [discarding a random input: `_ = RandomInput()`](https://github.com/tensorflow/tensorflow/blob/5646333e1ece8170dff7b1980905e8f9c8383881/tensorflow/python/kernel_tests/self_adjoint_eig_op_test.py#L205) sample in the _GetSelfAdjointEigGradTest function. Without this input, or with when there is a second input discarded before running the tests, they pass as expected.

**Describe the expected behavior**

For python/kernel_tests/self_adjoint_eig_op_test to pass.

**Comment by K1504296** [comment]
Andrew Goodbody has also tested this and said that the tests pass by disabling Fused Multiply Add instructions via `--copt=-ffp-contract=off --cxxopt=-ffp-contract=off`

**Comment by cfRod** [comment]
Are these tests built using -03? For the purpose of unit testing, I guess it is ok to disable these FMA instructions (?).
Tagging @penpornk  and @nSircombe here!

**Comment by elfringham** [comment]
By default it builds with -O2.

**Comment by penpornk** [comment]
Sorry for the late response! @cantonios has been on a long vacation. I think we can move forward with a 0.08 delta in the meanwhile. (We can revisit this later when @cantonios is back and if he thinks this needs more work.) 

Would you mind sending a PR for this and tag me? Thank you very much!

**Comment by cantonios** [comment]
My preference is small delta, leave FMA on.
