### ISSUE TITLE
 Steps to create tensorflow lite c++ dynamic library through cmake.

### ISSUE THREAD

**Issue by bhpatray** [tensorflow/tensorflow#52542]
I am trying to create dynamic TFLite c++ shared library.
https://www.tensorflow.org/lite/guide/build_cmake -

When I run step 5 , It creates static library.

Could you provide steps to create c++ dynamic library using cmake.
There is mentioned how to create only for c shared dynamic library but not c++.

**Comment by bhpatray** [comment]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**

- Debian 10(e.g., Linux Ubuntu 16.04):
- trying to TensorFlow Lite install from source:
- TensorFlow Lite version 2.4.1:
**Describe the current behavior**
Only able to generate C++ TFLite static library 
**Describe the expected behavior**
Need to create C++ TFLite dynamic library

**Comment by sushreebarsa** [comment]
@bhpatray We see that you're using TF v2.4.1,Could you please try to use TF v2.6.0 and let us know if it is still an issue ? Thanks!

**Comment by bhpatray** [comment]
Yes it still the issue.
I need steps to build C++ TFLite dynamic library.
That is independent of TFLite version used

**Comment by bhpatray** [comment]
Hi,

I was able to create the shared library with the below changes in CMakeLists.txt present in tensorflow/lite folder.
But I was unable to use the generated shared library through CMake.
I was able to run tflite models using shared library generated through bazel but not CMake.

![diff1](https://user-images.githubusercontent.com/92724011/139819511-1b832fce-1068-4ba7-8dba-5f7d25d5e3ba.JPG)

![diff2](https://user-images.githubusercontent.com/92724011/139819525-c08394c9-b419-45a6-9a5a-6b6eff1ced79.JPG)

What's the issue with modified CMakeLists ?
What's the procedure of creating a usable shared tflite library through CMake?

**Comment by bhpatray** [comment]
Any update

**Comment by mohantym** [comment]
Hi @bhpatray! Could you refer these threads for building shared library using CMake.[ link1](https://stackoverflow.com/questions/17511496/how-to-create-a-shared-library-with-cmake),[link2](https://surfertas.github.io/cmake/cpp/projecteuler/2019/05/01/cmake.html).Please post this issue on Stackoverflow/[TF forum ](https://discuss.tensorflow.org/)for further assistance.Thank you!

**Comment by terryheo** [comment]
If you want to use shared library distribution of TFLite, you'd better use C API.

https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library

Then you can use TFLite with necessary header files and the generated shared library.

**Comment by bhpatray** [comment]
Are you planning to create a process for C++ CMake shared library in future releases ?
What's the complexity in creating C++ shared library through CMake? why it is only for C?

I was able to generate shared-library through bazel using the below command.
bazel build  -c opt //tensorflow/lite:libtensorflowlite.so 

Why such process not there for CMake.
The generated shared library through CMake was not working. Could you provide a fix for that?

**Comment by terryheo** [comment]
> Are you planning to create a process for C++ CMake shared library in future releases?

We don't have such a plan at the moment.

> What's the complexity in creating C++ shared library through CMake? why it is only for C?

There is no easy way to share necessary header files. For C, you only need few C header files.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/README.md
> 
> I was able to generate a shared library through Bazel using the below command.
> bazel build -c opt //tensorflow/lite:libtensorflowlite.so

I believe this is still possible. If this is sufficient for you, please use Bazel.
> 
> Why is such a process not there for CMake?

The way how they handle dependent libraries are different.

> The generated shared library through CMake was not working. Could you provide a fix for that?

You mean C shared library? You need to use C API instead of C++.
