### ISSUE TITLE
Error compiling Raspberry Pi label_image

### ISSUE THREAD

**Issue by daddym85** [tensorflow/tensorflow#5255]
Hi there,
I'm trying to build Temsorflow on a Raspberry pi 3 running Raspbian Jessie and kernel 4.3.
I followed the instructions on: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile 
When I compile the label_image example, as described in:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples
I receive the following compilation errors with:  make -f tensorflow/contrib/pi_examples/label_image/Makefile

gcc --std=c++11 -O0 -I/usr/local/include -I. -I/home/pi/utensor/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/downloads -I/home/pi/utensor/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/downloads/eigen-latest/ -I/home/pi/utensor/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/gen/proto/ -I/home/pi/utensor/tensorflow/tensorflow/contrib/pi_examples/label_image/../../makefile/gen/proto_text/ -c tensorflow/contrib/pi_examples/label_image/label_image.cc -o /home/pi/utensor/tensorflow/tensorflow/contrib/pi_examples/label_image/gen/obj/tensorflow/contrib/pi_examples/label_image/label_image.o
In file included from ./tensorflow/core/framework/tensor.h:19:0,
                 from tensorflow/contrib/pi_examples/label_image/label_image.cc:32:
./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:4:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such ffile or directory
 #include "unsupported/Eigen/CXX11/Tensor"
                                                                    ^
compilation terminated.

Is there anyway to fix it?
Thanks.

**Comment by drpngx** [comment]
Could you paste the exact error log? That "ffile" looks suspicious.

**Comment by daddym85** [comment]
To fix the errors, I have followed the steps in:
https://github.com/tensorflow/tensorflow/issues/4680
