### ISSUE TITLE
2.7.0rc1 build error

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#52561]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubnutu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7.0rc1
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source):  gcc 9.3.0
- CUDA/cuDNN version: 11.4/8.2
- GPU model and memory: RTX3090 GDDR6X 24GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
configure with CUDA support
bazel build --config=numa --config=nogcp //tensorflow/tools/pip_packages:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
ERROR: /home/alan/.cache/bazel/_bazel_alan/166d89c2dc31e370baae784b1f517718/external/llvm-project/mlir/BUILD.bazel:2292:11: Compiling mlir/lib/Conversion/ShapeToStandard/ShapeToStandard.cpp failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/llvm-project/mlir/_objs/ShapeToStandard/ShapeToStandard.d ... (remaining 124 argument(s) skipped)
In file included from /usr/include/c++/9/bits/unique_ptr.h:37,
                 from /usr/include/c++/9/memory:80,
                 from external/llvm-project/mlir/include/mlir/Conversion/ShapeToStandard/ShapeToStandard.h:12,
                 from external/llvm-project/mlir/lib/Conversion/ShapeToStandard/ShapeToStandard.cpp:9:
/usr/include/c++/9/tuple: In instantiation of ‘constexpr std::_Tuple_impl<_Idx, _Head, _Tail ...>::_Tuple_impl(std::_Tuple_impl<_Idx, _Head, _Tail ...>&&) [with long unsigned int _Idx = 0; _Head = mlir::Value; _Tail = {mlir::Value}]’:
external/llvm-project/mlir/lib/Conversion/ShapeToStandard/ShapeToStandard.cpp:85:53:   recursively required from ‘constexpr std::tuple<_T1, _T2>::tuple(std::tuple<_T1, _T2>&&) [with _T1 = mlir::Value; _T2 = mlir::Value]’
external/llvm-project/mlir/lib/Conversion/ShapeToStandard/ShapeToStandard.cpp:85:53:   required from here
/usr/include/c++/9/tuple:227:7: internal compiler error: in lookup_template_class_1, at cp/pt.c:9466
  227 |       _Tuple_impl(_Tuple_impl&& __in)
      |       ^~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by alanpurple** [comment]
another error without numa support
```
ERROR: /mnt/data/repo/tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:436:15: Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops_n_z.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/_objs/tensorflow_ops_n_z/tf_ops_n_z.pic.d ... (remaining 226 argument(s) skipped)
In file included from tensorflow/compiler/mlir/tensorflow/ir/tf_ops_n_z.cc:3291:
bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/ir/tf_ops_n_z.cc.inc:22271:1: internal compiler error: Segmentation fault
22271 | void ResourceApplyAdamOp::build(::mlir::OpBuilder &odsBuilder, ::mlir::OperationState &odsState, ::mlir::Value var, ::mlir::Value m, ::mlir::Value v, ::mlir::Value beta1_power, ::mlir::Value beta2_power, ::mlir::Value lr, ::mlir::Value beta1, ::mlir::Value beta2, ::mlir::Value epsilon, ::mlir::Value grad, bool use_locking, bool use_nesterov) {
      | ^~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by mohantym** [comment]
Hi @alanpurple !Did you check with  Python 3.6-3.9 and [tested configuration ](url)for stable version 2.6 ?https://www.tensorflow.org/install/source_windows#gpu

**Comment by mohantym** [comment]
Ok @alanpurple! Thanks for confirming the same. Attaching threads for reference for the above error . [Link1](https://github.com/tensorflow/tensorflow/issues/13481),[Link2](https://stackoverflow.com/questions/37313212/tensorflow-bazel-build-failing),[Link3](https://askubuntu.com/questions/749441/tensorflow-crosstool-wrapper-driver-is-not-gcc-failed-error-executing-command).Feel free to close this issue if it helped . Thanks!
