### ISSUE TITLE
Crash with camera2api due to unsupported ImageFormat.YUV_420_888

### ISSUE THREAD

**Issue by xRiot** [tensorflow/tensorflow#52573]
### Reproducible example
Example project from https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android crashes after allowing camera permission due to:
```bash
org.tensorflow.lite.examples.poseestimation W/CameraDevice-JV-4: Stream configuration failed due to: createSurfaceFromGbp:1583: Camera 4: No supported stream configurations with format 0x23 defined, failed to create output stream
```

### Adbcat error log

From start to crash:
https://gist.githubusercontent.com/xRiot/f50680c94ec65dfdfae52fda609665b7/raw/aa95bf99362751f1af6d2e53fb20bfc9168c4bdc/gistfile1.txt

### Environment
This issue is specific to Android 11 on Samsung Galaxy s20+

### Source of the issue

This line causes the error, it seems like `YUV_420_888` is not supported on my particular device:
```kotlin
ImageReader.newInstance(PREVIEW_WIDTH, PREVIEW_HEIGHT, ImageFormat.YUV_420_888, 3)
```

**Comment by mohantym** [comment]
Hi @xRiot !
Have you checked this issue in Android Studio version (Chip munk) and TF 2.8 version yet?
Thank you!
