### ISSUE TITLE
tf.io.read_file loads indefinitely

### ISSUE THREAD

**Issue by masterholdy** [tensorflow/tensorflow#52587]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): `v2.4.0-49-g85c8b2a817f 2.4.1`
- Python version: `3.8.5`
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: - 
- GPU model and memory: - 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Splitting a Dataset  and then reading the first item of the Validation Dataset loads indefinitely.
```python
train_dataset = dataset.take(n_train_items)
val_dataset = dataset.skip(n_train_items)
```
Calling `next(iter(train_dataset .take(1)))` works calling `next(iter(val_dataset .take(1)))` loads indefinitely.

**Describe the expected behavior**
I want my Validation Dataset to just return Data as expected. 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): -
- Briefly describe your candidate solution(if contributing): -

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Notebook, that Produces the Issue: https://colab.research.google.com/drive/1w5RQDp6W3Zyu4p1kEBRlHT2Vl9zvxVOk?usp=sharing

Stackoverflow Post: https://stackoverflow.com/questions/69634758/reading-validation-dataset-takes-indefinitely-long
The Problem is withing `prep_image`, when i just return the Filename without opening the Data everything works as expected:

```python
def prep_image(filename, img_shape=(144,144), channels=3, dtype=tf.float32):
    return filename
#    image_string = tf.io.read_file(filename)
#    image = tf.image.decode_jpeg(image_string, channels=channels)
#    image = tf.image.convert_image_dtype(image, dtype)
#    image = tf.image.resize(image, img_shape)
#    return image
```
If i just return the Output of `tf.io.read_file` the first item of the Validation-Dataset already loads indefinitely:
```python
def prep_image(filename, img_shape=(144,144), channels=3, dtype=tf.float32):
    return tf.io.read_file(filename)
```

Edit:// Loading the First Train-Dataset Item Takes:
`0:00:00.063014`  `HH:MM:SS:ms`
and getting the first Validation item takes:
`0:31:09.717694`

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf [v2.6](https://colab.research.google.com/gist/tilakrayal/f942af07c7c2a8c88815700941c8ebdb/2-6minimal_sample.ipynb), v2.5 and [nightly](https://colab.research.google.com/gist/tilakrayal/e1600c211b2f17c1faf7d9837e71c80a/minimal_sample.ipynb).Please find the gist.

**Comment by masterholdy** [comment]
?

**Comment by mohantym** [comment]
Hi @masterholdy !
It is still replicating in [2.9](https://colab.sandbox.google.com/gist/mohantym/837df6873f3e2966f340fbe213537931/minimal_sample.ipynb#scrollTo=Kb-1wJ7Zp0Xr) and [nightly](https://colab.sandbox.google.com/gist/mohantym/c5667a374ab06ad49a2babe3b43761d3/minimal_sample.ipynb#scrollTo=Eso7xaFHp20D).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
