### ISSUE TITLE
Will Tensorflow support Keras in the future? 

### ISSUE THREAD

**Issue by adsk2050** [tensorflow/tensorflow#52592]
In the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) 2.6 release notes, it is mentioned that keras is going to be separated from tensorflow. 
 
My query is - Does this mean that tf.keras will be in sync with the separated keras library? (I understand that tf.python.keras is deprecated and will be removed). 

So as a recommendation, should I use tf.keras or directly import and use keras in my future projects?

**Comment by Saduf2019** [comment]
@adsk2050 

Please refer to below post and you may raise your query there as well.
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

Or post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:

**Comment by jvishnuvardhan** [comment]
Closing this as this was resolved. Thanks!
