### ISSUE TITLE
Asset initialization using SavedModel C++ API

### ISSUE THREAD

**Issue by tfeher** [tensorflow/tensorflow#52599]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from: source, commit 1dd2070b5f9
- TensorFlow version: 2.8
- Python version: 3.8.5
- Bazel version: 3.7.2
- GCC version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.3
- GPU model and memory: V100-SXM2 16GB

**Describe the current behavior**
I would like to infer a TF-TRT converted model using the C++ API of tensorflow. I have followed the https://github.com/bmzhao/saved-model-example. Before saving the model I have converted it with TF-TRT. See https://github.com/tfeher/tf-trt-saved-model-example for details.

While loading the SavedModel, the assets are initialized. This is confirmed by the printout from TF-TRT's op that initializes the engine from the asset file:
```
I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_resource_ops.cc:160] Loaded 1 TRT engines for op TRTEngineOp_0_0 on device /job:localhost/replica:0/task:0/device:GPU:0 from file
 /data/saved-model-example/mnist_model_trt/assets/trt-serialized-engine.TRTEngineOp_0_0

```

Afterwards, when I try to infer the model, I receive the following error:
```
Error executing session.Run() INVALID_ARGUMENT: 2 root error(s) found.
  (0) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'asset_path_initializer' with dtype string
         [[{{node asset_path_initializer}}]]
         [[Func/StatefulPartitionedCall/input/_1/_67]]
  (1) INVALID_ARGUMENT: You must feed a value for placeholder tensor 'asset_path_initializer' with dtype string
         [[{{node asset_path_initializer}}]]
0 successful operations.
0 derived errors ignored.
```

I do not understand why does it want to initialize the assets again. They are already initialized. In fact, if I modify the example to add the asset_path, then TRT resource initializer throws the following error:
```
Error executing session.Run() INTERNAL: 2 root error(s) found.                                                                                                                                                    
  (0) INTERNAL: Expect engine cache to be empty, but got 1 entries.                                                                                                                                               
         [[{{function_node __inference_<lambda>_42188}}{{node InitializeTRTResource}}]]                                                                         
         [[StatefulPartitionedCall/_69]]                                                                                                                                                                          
  (1) INTERNAL: Expect engine cache to be empty, but got 1 entries.                                                                                                                                               
         [[{{function_node __inference_<lambda>_42188}}{{node InitializeTRTResource}}]]   
```

**Describe the expected behavior**
I expect that I can infer the model once it is loaded by `LoadSavedModel`, since `LoadSavedModel` runs initialization on the assets and variables.

**Standalone code to reproduce the issue**
https://github.com/tfeher/tf-trt-saved-model-example 

Tagging @bixia1 and @DEKHTIARJonathan  for visibility.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
