### ISSUE TITLE
Why the embedding_lookup() returns zeros when the index exceed embedding matrix size?

### ISSUE THREAD

**Issue by kkjh0723** [tensorflow/tensorflow#5260]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

I'm now using TF version 0.10.0 installed from source.
I'm not sure its a bug or intended implementation but the `embedding_lookup()` returns zeros when the index exceed embedding matrix size. For example,

     import tensorflow as tf
     import numpy as np

     embd_mat = np.linspace(1,10,10).reshape([10,1])*np.array([1,2,3]).reshape([1,3])
     idx = np.linspace(0,19,20)

     embd_in = tf.placeholder(tf.float32,[10,3])
     idx_in = tf.placeholder(tf.int32,[20])

     output = tf.nn.embedding_lookup(embd_in,idx_in)

     with tf.Session() as sess:
         sess.run(tf.initialize_all_variables())
     
         embd_out = sess.run(output,feed_dict={embd_in:embd_mat, idx_in:idx})
     
         print embd_out

The output of above code is,

    [[  1.   2.   3.]
     [  2.   4.   6.]
     [  3.   6.   9.]
     [  4.   8.  12.]
     [  5.  10.  15.]
     [  6.  12.  18.]
     [  7.  14.  21.]
     [  8.  16.  24.]
     [  9.  18.  27.]
     [ 10.  20.  30.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]
     [  0.   0.   0.]]
    
Is there any reason it returns zeros not raises an error?
I think that case happens only when programmers make a mistake.
Unless there is any specific reason which I don't know of, I think it should raise a value error that the index is exceeding the matrix size.

**Comment by drpngx** [comment]
@strategist333 not sure what the expected behavior is

**Comment by kkjh0723** [comment]
I expected that it would return an error similar to when two matrices with unmatched sizes are multiplied (e.g. `tf.matmul(tf.ones([3,10]),tf.ones([20,1]))`).

**Comment by strategist333** [comment]
I'm not able to reproduce this on the 0.10.0 TF binary release. Could it be possible that you've made local source modifications?

The intended behavior is indeed to error:
`tensorflow.python.framework.errors.InvalidArgumentError: indices[10] = 10 is not in [0, 10)
	 [[Node: embedding_lookup_1 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Placeholder_2"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Placeholder_2_0, _recv_Placeholder_3_0)]]
`

**Comment by kkjh0723** [comment]
It's weird... I downloaded TF from master branch about a month ago and installed ( I checked the version in the python as stated in the instruction).  I haven't changed the code except some BUILD files because of errors while configuring (related to issue #4312).

**Comment by drpngx** [comment]
OK, please continue debugging side-by-side and re-open if you find that the actual problem is in our bits.

**Comment by kkjh0723** [comment]
@drpngx Today, I re-installed latest Tensorflow from source without any modification and it showed the same output as in my first question. According to @strategist333 , it seems it should raise an error though... 
Printed version from Tensorflow is `0.11.head` and commit hash is 55dbc54192a378c5e685c52595f42503f037320e

**Comment by poxvoculi** [comment]
Marking this as duplicate of #5847 which contains further discussion.
