### ISSUE TITLE
MirroredStrategy throw always AttributeError at the end of execution

### ISSUE THREAD

**Issue by TheEnigmist** [tensorflow/tensorflow#52607]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Python version: 3.7
- CUDA/cuDNN version: 11.2/8.1.0
- GPU model and memory: 10x GTX 1080ti

**Describe the current behavior**
When using a strategy at the end of the program I got an AttributeError exception.
```
Exception ignored in: <function Pool.__del__ at 0x7f06a661ac10> 
Traceback (most recent call last): 
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 268, in del 
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 362, in put 
AttributeError: 'NoneType' object has no attribute 'dumps'
```
The program works as expected, but it shows always that exception.

**Describe the expected behavior**
The program should exit without this exception

**Standalone code to reproduce the issue**
```
import tensorflow as tf 
strategy = tf.distribute.MirroredStrategy()
 ```

**Comment by TheEnigmist** [comment]
> Hi @TheEnigmist! Is this issue replicating in TF 2.6 too? Attaching Gist in [2.4](https://colab.research.google.com/gist/mohantym/e48e599458ec4ad9d93fad602f8ced92/github_52607.ipynb#scrollTo=vHQr5QPCSDuh),[2.5](https://colab.research.google.com/gist/mohantym/0a857a6c5c8d5fe541192185a54b379d/github_52607.ipynb#scrollTo=vHQr5QPCSDuh) and [2.6](https://colab.research.google.com/gist/mohantym/0a857a6c5c8d5fe541192185a54b379d/github_52607.ipynb#scrollTo=wpP0uFfdSF-I) for reference.

Just installed TF-gpu 2.6.0 and the Exception ignored appears. I don't know why it doesn't appear on colab executions

**Comment by sanatmpa1** [comment]
@TheEnigmist,

This looks like an issue with Multi processing on windows. Can you please paste the complete stack trace of the error? Thanks!
