### ISSUE TITLE
Running a computation graph in C++ with custom ops

### ISSUE THREAD

**Issue by elca4u** [tensorflow/tensorflow#5261]
The current C API does not seem to support loading custom op library, which is tf.load_op_library for python.
Because of this, I cannot run a computation graph with custom ops.
Is there any way I can register custom ops in C?

**Comment by drpngx** [comment]
@jhseu checking what the correct route is

**Comment by jhseu** [comment]
It does support it:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h#L973

Python's load_op_library calls it underneath:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/load_library.py#L55

**Comment by jhseu** [comment]
Closing, but feel free to reopen if I misinterpreted the issue.

**Comment by dhingratul** [comment]
What is the usage for C API?
