### ISSUE TITLE
quantization aware training issue

### ISSUE THREAD

**Issue by Sgsouham** [tensorflow/tensorflow#52630]
Hi, I am training a U2Net model and want to use quantization aware training to reduce the size of the model. According to the official Docs regarding this, We need to import the library of tensorflow_model_optimization and use the quantize model function.

Issue - When i am using this, I am getting AttributeError: 'list' object has no attribute 'dtype'
This is my model declaration code-

quantize_model = tfmot.quantization.keras.quantize_model

net_input = Input(shape=(256,256,3)) 

model_output = U2NET(net_input)

model = Model(inputs = net_input, outputs = model_output)

qa_model = quantize_model(model)
lr = 1e-3

opt = tf.keras.optimizers.Adam(learning_rate = lr)

bce = BinaryCrossentropy()

qa_model.compile(optimizer = opt, loss = loss, metrics = None)

U2net function is the model declaration part.
I am able to get the normal model.summary()

I am trying to train the model of google colab gpu

Without QAT the model is training fine.

Please help

**Comment by rsuriano** [comment]
Could you find a solution? I'm having the same problem, can't use the _quantize_model_ function. This is my code:

`number_of_classes = 10

inputs = tf.keras.Input(shape=(51))
embedding = landmarks_to_embedding(inputs)

layer = keras.layers.Dense(128, activation="relu")(embedding)
layer = keras.layers.Dropout(0.5)(layer)
layer = keras.layers.Dense(64, activation="relu")(layer)
outputs = keras.layers.Dense(number_of_classes, activation="softmax")(layer)

model = keras.Model(inputs, outputs)
quant_aware_model = tfmot.quantization.keras.quantize_model(model)

model.summary()`

**Comment by Sgsouham** [comment]
from what i can gather @rsuriano , tihs api works only with sequential or functional api, and for custom class, layers need to be annotated manually. Though i am still waiting for an official answer. In your case, you can move the entire layers into a sequential api and it might work.

**Comment by sachinprasadhs** [comment]
There will be some limitations and complications while using `quantization aware training`, instead you can also try with `post_training quantization `to reduce the model size with less complications. Thanks!

**Comment by rsuriano** [comment]
Thanks for the comment @Sgsouham! At the end of the day I solved my problem without quantization, as the issue was somewhere else.
