### ISSUE TITLE
' TypeError: '<=' not supported between instances of 'list' and 'Rectangle'  ' from pose_classification.ipynb

### ISSUE THREAD

**Issue by donghyun128** [tensorflow/tensorflow#52644]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Github : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb

Google colab : https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb 

## Description of issue (what needs changing):

I'm following steps from that URL (Movenet yoga pose classification) by google colab and Jupyter notebook. 
When executing 'Preprocess the TRAIN dataset' code, an error occurs.

-----------------------------------------------------------------------------------

Code 
-------------

if not is_skip_step_1:
  images_in_train_folder = os.path.join(IMAGES_ROOT, 'train')
  images_out_train_folder = 'poses_images_out_train'
  csvs_out_train_path = 'train_data.csv'

  preprocessor = MoveNetPreprocessor(
      images_in_folder=images_in_train_folder,
      images_out_folder=images_out_train_folder,
      csvs_out_path=csvs_out_train_path,
  )

  preprocessor.process(per_pose_class_limit=None)

---------------------------------------------------------------------------

Error message
-------------

Preprocessing chair
  0%|          | 0/200 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  0%|          | 0/200 [00:00<?, ?it/s]
'---------------------------------------------------------------------------'
TypeError                                 Traceback (most recent call last)
<ipython-input-11-87cdca3ca58e> in <module>()
     10   )
     11 
---> 12   preprocessor.process(per_pose_class_limit=None)

2 frames
<__array_function__ internals> in amin(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

TypeError: '<=' not supported between instances of 'list' and 'Rectangle'

![image](https://user-images.githubusercontent.com/43366200/138588872-3d9f22a0-28f8-4807-a02d-e69fd99cb801.png)

How can I solve this issue?

**Comment by yao-th** [comment]
I met the exact same issue, does anyone know any solution to this?
