### ISSUE TITLE
Typo in the model.compile code examples: tf.keras.optimizers not tf.keras.optimizer

### ISSUE THREAD

**Issue by rand42studios** [tensorflow/tensorflow#52640]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile

## Description of issue (what needs changing):
Error in the model.compile code examples: tf.keras.optimizers not tf.keras.optimizer
The code is misspelt. See link
<img width="705" alt="Screen Shot 2021-10-23 at 10 58 08 PM" src="https://user-images.githubusercontent.com/93064122/138578511-289edad0-d236-4b5d-8ef8-a689b66ca2c4.png">
.

**Comment by rthadur** [comment]
This has been fixed in r2.6.1 , Thank you all
