### ISSUE TITLE
xla compile op cache many tensors to out of memory .

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#52645]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): master
- Python version: 3.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.1 (clang-1001.0.46.4)
- CUDA/cuDNN version: - 
- GPU model and memory: - 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
zsh: command not found: v1.12.1-54214-gb51e7cff1aa

**Describe the current behavior**
xla OOM

**Describe the expected behavior**
xla not OOM

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
    flat_hash_map -> LRUCache(with large size) .

1. OOM
    XlaCompilationCache in XlaCompileOp maybe cache many tensors in ```absl::flat_hash_map<Signature, std::unique_ptr<Entry>, Signature::Hash> cache_```.
    My XlaCompileOp has an input named TruncatedNormalV2, and TruncatedNormalV2 will output a dynamic shape, so my XlaCompileOp will compile many exe file and cache lots of input tensors. 

2. LOG
  I spend 3 days to find tensor OOM, so I think  If there is too much content in cache_, at least print a warning to remind it.

I want to confirm whether there is such a problem in TF ? or I have a mistake usage ?
If you think it's a bug, I am happy to fix this problem.

**Comment by zhaozheng09** [comment]
> There's a known limitation of XLA that for dyamic size, it may need to do multiple recompilations and so that may be the reason for the cache to get filled and cause OOM. It can also add unexpected latency for the dynamic shapes. You can take a look at this section of the [video](https://youtu.be/cPAD9vLKE0c?t=822) which explains about the same.

When the cache reaches a certain amount, should we tell the user that XLA caches a lot of data?

**Comment by zhaozheng09** [comment]
> There's a known limitation of XLA that for dyamic size, it may need to do multiple recompilations and so that may be the reason for the cache to get filled and cause OOM. It can also add unexpected latency for the dynamic shapes. You can take a look at this section of the [video](https://youtu.be/cPAD9vLKE0c?t=822) which explains about the same.

1. Should we replace flat_map with LRUCache ?
2. If user misuse leads to OOM, is there a log to remind them of this in time ?

**Comment by sachinprasadhs** [comment]
Displaying warning message on memory usage will not be a good option since it will be specific to system hardware specific level.
Instead you can mange your GPU memory using options like `set_memory_growth`, more details [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). 
Additionally, you can investigate further on memory consumption using HLO graph, you can find the reference and similar discussion [here](https://discuss.tensorflow.org/t/xla-jit-compile-flag-and-gpu-memory-usage/5127/10). Thanks!
