### ISSUE TITLE
Can I use multiple CPU but none GPU on inception v3 code?

### ISSUE THREAD

**Issue by yichengwang125** [tensorflow/tensorflow#5268]
I have access to GPUs on the server, but the sysadmin has trouble on setting up CuDNN and CUDA, and I found when I use multi CPU on CIFAR-10 code, the speed was similar with GPUs. 
So I wonder whether there is a way to use the inception code to train the ImageNet in a environment with multiple CPUs like 32 or 64 CPU cores but none GPU?

**Comment by drpngx** [comment]
Yes, in theory it's possible, but inception going to be very, very slow so that's probably not something that you'd want to do. Setting up cuda and cudnn can be tricky, but worth the trouble IMO.
