### ISSUE TITLE
Title: Input shape compatibility of ZIP-object of (image and image ImageDataGenerator objects) and CNN

### ISSUE THREAD

**Issue by tusneemA** [tensorflow/tensorflow#52705]
**System information**
Have I written custom code (as opposed to using a stock example script
provided in TensorFlow): custom code
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
happens on a mobile device: NA
TensorFlow installed from (source or binary): binary (added as library to Anaconda )
TensorFlow version (use command below): 2.1.0
Python version: 3.7
Bazel version (if compiling from source): NA
GCC/Compiler version (if compiling from source): NA
CUDA/cuDNN version: 10.1
GPU model and memory:
NVIDIA GeForce RTX 2070 with Max-Q Design
Driver version: 30.0.14.7196
Driver date: 8/27/2021
DirectX version: 12 (FL 12.1)
Physical location: PCI bus 1, device 0, function 0
Utilization 0%
Dedicated GPU memory 0.0/8.0 GB
Shared GPU memory 0.1/7.9 GB
GPU Memory 0.1/15.9 GB- Exact command to reproduce:
########################################

I have 64 RGB images with their corresponding masks. I use ImageDataGenerator and flow_from_directory function to read the images and masks from the directory folder.
The folder structures are as follows:
Images
---- imgs
-------- ---ROI
----------------1.tiff
----------------2.tiff
Masks 
------imgs
------- -----ROI
------------------1.tiff
------------------2.tiff
Images and masks are stored with the same file names. In my case, ImageDataGenerator is an Iterator of size 2 with a batch size of 32. I did the following:
1.	I read the images and masks into lists named as “images” and ‘’masks’’ respectively.

```
size = 231 
images = []

for directory_path in glob.glob(“. /Images/imgs/ROI/"):
    for img_path in glob.glob(os.path.join(directory_path, "*.tiff"):
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)       
        img = cv2.resize(img, (size, size))
        images.append(img)
        images = np.array(images)

masks = [] 
for directory_path in glob.glob(“. /Masks/imgs/ROI/"):
    for mask_path in glob.glob(os.path.join(directory_path, "*.tiff"):
        mask = cv2.imread(mask_path, 0)       
        mask = cv2.resize(mask, (size, size))
        masks.append(mask)     
masks = np.array(masks)
masks = np.expand_dims(masks, axis=3)
```
**Note: I obtained images of shape (64, 231,231,3) and masks of shape (64, 231, 231, 1)**

2.	I then used keras documentation the process of transforming the images and masks together as follows:

          a.	I created a dict to specify the augmentation parameters as follows for both images and masks.
          data_gen_args_imgs = dict rotation range=90,
                               rescale = 1. /255.)
          data_gen_args_masks = dict rotation range=90)
                       
          b.	The I created ImageDataGenerator objects for both images and masks as follows:
          ```
          image_datagen = ImageDataGenerator(**data_gen_args_imgs)
          mask_datagen = ImageDataGenerator(**data_gen_args_masks)
          ```
          
          c.	I use the fit and flow functions using the same seeds and keyword arguments for images and masks as follows: 
          ```
          seed = 1
          
          image_datagen.fit(images, augment=True, seed=seed)
          mask_datagen.fit(masks, augment=True, seed=seed)
          
          image_generator = image_datagen.flow_from_directory(
              'data/images',
              class_mode=None,
              shuffle= False,
              seed=seed)
          
          mask_generator = mask_datagen.flow_from_directory(
              “. /Images/imgs/”,
              class_mode=None,
              shuffle= False,
              seed=seed)
          ```
          
          d.	Then I created an iterator on the zip object to return a matched pair of images and corresponding masks as follows:
          
          `train_generator = (pair for pair in zip (image_generator, mask_generator))`
          
          e.      Then I build a CNN model as follows: 
          ```
          
          activation= 'relu'
          model = Sequential()
          model.add (Conv2D(16, kernel_size=(3, 3),activation='relu',input_shape=(231,231,3),padding='same'))
          model.add (Conv2D(16, kernel_size=(3, 3),activation= activation,    padding='same'))
          model.add (Flatten())
          model.add (Dense(5))
          model.add (Dense(3))
          model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
          model.summary()
          
          ```
          
          e.	Then I used fit_generator to fit the model as follows: 
          
          `model.fit_generator (train_generator, steps_per_epoch= 15, epochs=2, verbose=1)`

But I got the following error regarding input dimensionality:
```
InvalidArgumentError:  Input to reshape is a tensor with 33554432 values, but the requested shape requires a multiple of 853776
 [[node sequential_8/flatten_8/Reshape (defined at <ipython-input-91-2871596287c2>:12) ]] [Op:__inference_distributed_function_7252]

Function call stack:
distributed_function
```
Following is the full code:
```
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import glob
import cv2
import os
import glob
import tensorflow as tf
import pickle
from scipy import ndimage as nd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow .keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import sklearn.utils 
from tensorflow.keras.optimizers import Adadelta, RMSprop,SGD,Adam

print(tf.__version__)

train_path="C://Users//Tusneem//Documents//Untitled Folder//Tusneem_Seg//SEG_OBJ1//BAS//ROI_1//"
mask_path="C://Users//Tusneem//Documents//Untitled Folder//Tusneem_Seg//SEG_OBJ1//BAS//ROI_2//"

############################################################################
size = 231 
images = []

for directory_path in glob.glob("C://Users//Tusneem//Documents//Untitled Folder//Tusneem_Seg//SEG_OBJ1//BAS//ROI_1//ROI_train//"):
    for img_path in glob.glob(os.path.join(directory_path, "*.tiff")):
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)       
        img = cv2.resize(img, (size, size))
        #img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        images.append(img)
        #train_labels.append(label)
        
images = np.array(images)

masks = [] 
for directory_path in glob.glob("C://Users//Tusneem//Documents//Untitled Folder//Tusneem_Seg//SEG_OBJ1//BAS//ROI_2//ROI_train//"):
    for mask_path in glob.glob(os.path.join(directory_path, "*.tiff")):
        mask = cv2.imread(mask_path, 0)       
        mask = cv2.resize(mask, (size, size))
        masks.append(mask)
                
masks = np.array(masks)
masks=np.expand_dims(masks, axis=3)

#######################Example of transforming images and masks together.
import tensorflow as tf

# we create two instances with the same arguments
data_gen_args = dict(featurewise_center=True,
                     featurewise_std_normalization=True,
                     rotation_range=90)
                     
## what is images
## what is masks
# what is **data_gen_args

image_datagen = ImageDataGenerator(data_gen_args)
mask_datagen = ImageDataGenerator(data_gen_args)
# Provide the same seed and keyword arguments to the fit and flow methods
seed = 1
image_datagen.fit(images, augment=True, seed=seed)
mask_datagen.fit(masks, augment=True, seed=seed)

image_generator = image_datagen.flow_from_directory(
    train_path,
    class_mode=None,
    shuffle= False,
    seed=seed)

mask_generator = mask_datagen.flow_from_directory(
    "C://Users//Tusneem//Documents//Untitled Folder//Tusneem_Seg//SEG_OBJ1//BAS//ROI_2//",
    class_mode=None,
    shuffle= False,
    seed=seed)
# combine generators into one which yields image and masks
#train_generator = zip(image_generator, mask_generator)
train_generator = (pair for pair in zip(image_generator, mask_generator))

activation= 'relu'

model = Sequential()
model.add(Conv2D(16, kernel_size=(3, 3),activation='relu',input_shape=(231,231,3),padding='same'))
model.add(Conv2D(16, kernel_size=(3, 3),activation='relu',padding='same'))
model.add(Flatten())
model.add(Dense(5))
model.add(Dense(3))
model.compile( loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

model.fit_generator(train_generator, steps_per_epoch= 15, epochs=2, verbose=1)
```
**my question is: How can I fix the problem of train_generator and CNN input shapes??**
#########attachments 
[The code.txt](https://github.com/tensorflow/tensorflow/files/7439208/The.code.txt)
[summary of ImageDataGenarator_ZIP object_CNN.docx](https://github.com/tensorflow/tensorflow/files/7439221/summary.of.ImageDataGenarator_ZIP.object_CNN.docx)

**Comment by tilakrayal** [comment]
@tusneemA ,
Can you please upgrade to latest stable tensorflow version 2.6 and test the code in new virtual environment and let us know if the issue still persists.It helps.Thanks!

**Comment by tusneemA** [comment]
OK, I will.

**Comment by tusneemA** [comment]
I did install Tensorflow 2.6 and I got the following error:

 ValueError: Shapes (None, None, None, None) and (None, 3) are incompatible

also I was not able to install any version of Spyder therfore, I run it Jupyter

**Comment by tilakrayal** [comment]
@tusneemA ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
