### ISSUE TITLE
Tensorflow C api is no longer supported on mac OSX High Sierra (Sierra too)

### ISSUE THREAD

**Issue by Toon34** [tensorflow/tensorflow#52726]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac OSX High Sierra
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.6 -> 2.8
- Python version: None
- Installed using virtualenv? pip? conda?: None 
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory:

![Capture d’écran 2021-10-27 à 19 50 12](https://user-images.githubusercontent.com/8608052/139119271-a594bd58-8cd7-4c2d-b214-2e04acf433e2.png)

**Describe the problem**
Using the tensorflow C api, a compatibility issue appeared on High Sierra (Maybe Sierra too)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Compiling a program works well but at runtime : dyld: Symbol not found: ____chkstk_darwin (which was built for Mac OS X 10.15)

**Any other info / logs**
To fix the problem, just recompile tensorflow api with the option in bazel : --macos_minimum_os=10.13 (high sierra)

**Comment by sachinprasadhs** [comment]
Did you try and follow the steps mentioned in the link here https://www.tensorflow.org/install/lang_c#macos

**Comment by Toon34** [comment]
> Did you try and follow the steps mentioned in the link here https://www.tensorflow.org/install/lang_c#macos

Hello ! 
Yes of course, same problem.

**Comment by sachinprasadhs** [comment]
Could you please raise this issue in the dedicated Apple developer forum https://developer.apple.com/forums/
