### ISSUE TITLE
Tensorflow stop running while running "sess=tf.Session()"

### ISSUE THREAD

**Issue by liu-mingyuan** [tensorflow/tensorflow#5272]
I am running tensorflow on ubuntu14.04 server using GPU and I had successuflly run the demo in the tutorial about mnist a few days ago.
Today, I run the same demo but to find it get stucked. I find out that I can import tensorflow successfully, but every time I run "sess=tf.Session()" the program will stop. It is strange that **neither error information sent back nor the python quit**. The cursor just stop there, enen "ctrl+c" does not work. 
As the server I installed tensorflow is public, I suspect that someone had changed something on the server. But I do not know. How can I fix it?

**Comment by drpngx** [comment]
OK, please gdb attach to the process and check the stack trace. Try to install nmon ("n", "d", "c") and see if anything is happening.

**Comment by drpngx** [comment]
also, `nvidia-smi -l`.

**Comment by liu-mingyuan** [comment]
Thank you very much, the problem has been solved. As **drpngx** said, when I run "nvidia-smi", the server also stoped working. As a result, I re-install the CUDA and Cudnn, then all the problem has been solved. Not intentionally, maybe someone who share the same machine or even I myself had changed some configuration.  All in all, thank you very much.

**Comment by drpngx** [comment]
Glad to hear you're good to go!

**Comment by dimahdera** [comment]
I am having the same problem on windows .I am getting the following error
c:\tf_jenkins\home\workspave\release-win\device\gpu\os\windows\tensorflow\stream_excutor\cuda\duda_driver.cc:94] check failed: s.ok() could not find cuDevicePrimaryCtxSetFlags in libcuda DSO; dlerror: cuDevicePrimaryCtxSetFlags not found

and python has stopped working whenever I run tf.Session, 
Could you please help I am struggling with this problem
