### ISSUE TITLE
TensorBoard histograms NaN value handling

### ISSUE THREAD

**Issue by timmeinhardt** [tensorflow/tensorflow#5276]
Recently I had to fight a lot with exploding gradients and thereby weights turning NaN after only several iterations event hough I was using _tf.contrib.layers.variance_scaling_initializer_ correctly. To monitor the problem I started saving weight histograms which seemed totally messed up. I thought this was due to me using the initializer wrongly and only after some debugging I realised my initialization was totally fine. The NaN values appearing in iteration _n_ seem to mess with the visualization of values in previous iterations which seems like a very misleading behaviour to me. Histograms and distributions should be visualized correctly until this is not really possible because of ill values.

I can easily provide tensorflow summary data to reproduce this behaviour.

**Comment by drpngx** [comment]
@danmane not sure what the proper thing to do with NaN is, maybe report them in a separate counter or ignore?

**Comment by drpngx** [comment]
Yes, @timmeinhardt please attach summary data in case we want to repro.

**Comment by timmeinhardt** [comment]
Yes, of course. Here is some example summary data. All weights were initialised with the default parameters for _tf.contrib.layers.variance_scaling_initializer_.

[events.out.tfevents.1477816723.Tims-MacBook-Pro.local.zip](https://github.com/tensorflow/tensorflow/files/560359/events.out.tfevents.1477816723.Tims-MacBook-Pro.local.zip)

**Comment by chihuahua** [comment]
I migrated this issue to tensorflow/tensorboard#87 because TensorBoard has moved into its own, separate repo. Lets continue discussion there.

**Comment by ankur-98** [comment]
The weights being written to the histogram needs to be clipped.
