### ISSUE TITLE
How to convert a tensorlfow SpaceToBatchND-Conv2D-BatchToSpaceND to a single Conv2D in tflite

### ISSUE THREAD

**Issue by zding047** [tensorflow/tensorflow#52774]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installation (pip package or built from source): docker image
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0-gpu-jupyter

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

```
import tensorflow as tf
from tensorflow.keras.layers import (
        Concatenate,
        DepthwiseConv2D,
        ZeroPadding2D,
        Activation,
        GlobalAveragePooling2D,
        BatchNormalization,
        Conv2D,
        Input,
)
from tensorflow.keras.models import Model

def SepConv_BN(x, filters, prefix, stride=1, kernel_size=3, rate=1, depth_activation=False, epsilon=1e-3):
    if stride == 1:
        depth_padding = "same"
    else:
        kernel_size_effective = kernel_size + (kernel_size - 1) * (rate - 1)
        pad_total = kernel_size_effective - 1
        pad_beg = pad_total // 2
        pad_end = pad_total - pad_beg
        x = ZeroPadding2D((pad_beg, pad_end))(x)
        depth_padding = "valid"

    if not depth_activation:
        x = Activation(tf.nn.relu)(x)
    x = DepthwiseConv2D(
        (kernel_size, kernel_size),
        strides=(stride, stride),
        dilation_rate=(rate, rate),
        padding=depth_padding,
        use_bias=False,
        name=prefix + "_depthwise",
    )(x)
    x = BatchNormalization(name=prefix + "_depthwise_BN", epsilon=epsilon)(x)
    if depth_activation:
        x = Activation(tf.nn.relu)(x)
    x = Conv2D(filters, (1, 1), padding="same", use_bias=False, name=prefix + "_pointwise")(x)
    x = BatchNormalization(name=prefix + "_pointwise_BN", epsilon=epsilon)(x)
    if depth_activation:
        x = Activation(tf.nn.relu)(x)

    return x

x = Input(shape=(22, 40, 160))
b0 = Conv2D(256, (1, 1), padding="same", use_bias=False, name="aspp0")(x)
b0 = BatchNormalization(name="aspp0_BN", epsilon=1e-5)(b0)
b0 = Activation(tf.nn.relu, name="aspp0_activation")(b0)
b1 = SepConv_BN(x, 256, "aspp1", rate=4, depth_activation=True, epsilon=1e-5)
b2 = SepConv_BN(x, 256, "aspp2", rate=8, depth_activation=True, epsilon=1e-5)
b3 = SepConv_BN(x, 256, "aspp3", rate=12, depth_activation=True, epsilon=1e-5)
b4 = GlobalAveragePooling2D()(x)
b4 = tf.reshape(b4, (-1, 1, 1, b4.shape[-1]))
b4 = Conv2D(256, (1, 1), padding="same", use_bias=False, name="image_pooling")(b4)
b4 = BatchNormalization(name="image_pooling_BN", epsilon=1e-5)(b4)
b4 = Activation(tf.nn.relu)(b4)
size_before = tf.shape(x)
b4 = tf.image.resize(b4, size_before[1:3], method=tf.image.ResizeMethod.BILINEAR)
y = Concatenate(name="concat_head")([b4, b0, b1, b2, b3])
model = Model(x, y, name="aspp")

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
model.save("example.h5")
open("example.tflite", "wb").write(tflite_model)
```
The models and graphs are also provided.
[models.zip](https://github.com/tensorflow/tensorflow/files/7432732/example.zip)

![keras model using Netron](https://user-images.githubusercontent.com/86588364/139223891-45dadbd6-4960-46c1-a222-3da0db42a5d0.png)
![tflite model using Netron](https://user-images.githubusercontent.com/86588364/139223763-66e0167f-4046-42e6-84a8-3eda2a1bc238.png)

### 3. Failure after conversion
The codes is an implementation of ASPP structure as used in segmentation. In the Keras model, there is no `space_to_batch` or `batch_to_space` operations. However, in the converted tflite model, they appear, which are not supported by tflite gpu-delegate. This means the inference speed will be slowed down due to those operations. 

Is there a way to convert the keras model without  those gpu-unsupported operations?

I found a related [issue](https://github.com/tensorflow/tensorflow/issues/29509), but the issue still exists.

**Comment by mohantym** [comment]
Hi @zding047 !
You can disable the layers with SpaceToBatchND-Conv2D-BatchToSpaceND and other nodes which are not gpu compatible  with the  below command ,
```
tf.lite.experimental.QuantizationDebugOptions(
    denylisted_nodes=suspected_layers)
debugger = tf.lite.experimental.QuantizationDebugger(
    converter=converter,
    debug_dataset=representative_dataset(ds),
    debug_options=debug_options)
```
[Ref.](https://www.tensorflow.org/lite/performance/quantization_debugger)
You can find the layers which are not compatible with GPU with below command.
`tf.lite.experimental.Analyzer.analyze(model_content=fb_model, gpu_compatibility=True)
`
[Ref](https://www.tensorflow.org/lite/performance/quantization_debugger).

Thank you!

**Comment by zding047** [comment]
> 

Many thanks for your information. May I ask which version does support this piece of code? I could not run it in TF2.5.0. By the way, I think the provided codes are used for debugging but not conversion. Also, I don't want quantization during conversion which might lead to a precision drop.

**Comment by mohantym** [comment]
@zding047 !
You can skip the quantization of Conv2D-SpaceBatchND-BatchToSpaceND through usage of denylisted nodes in debugger and get the non-quantized model through below command.

`debugger.get_nondebug_quantized_model()`

I think It was introduced in 2.8.2 or 2.9 .

Thank you!
