### ISSUE TITLE
TFLite GPU Delegate Precision loss enabled produces different/wrong result.

### ISSUE THREAD

**Issue by misheeltoli** [tensorflow/tensorflow#52794]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Galaxy Note20 Ultra(Snapdragon), Galaxy S10(Exynos)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0, 2.6.0, 2.7.0 (All same result)
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): Android NDK 19.2.5345600
- CUDA/cuDNN version: -
- GPU model and memory: Snapdragon 865, Exynos 9820

**Describe the current behavior**
I have been trying to run inference of my custom model using TFLite 2.5.0 or 2.6.0 with OpenCL GPU delegate enabled.
When I set gpu_precision_loss_allowed=true, avg_error is 0.334995. But for gpu_precision_loss_allowed=false, it is 6.36335e-06. The error diff between precision_loss enabled(fp16) and precision_loss disabled(fp32) is so large. It can be understandable that if fp16 result is less than 0.003. But 0.33 is so large.

Here are outputs of the inference_diff/run_eval tool obtained using [my model](https://github.com/tensorflow/tensorflow/files/7434381/model.zip) on Galaxy Note20 Ultra:

```
➜   adb shell /data/local/tmp/run_eval \
    --model_file=/data/local/tmp/model.tflite \
    --delegate=gpu \
    --num_runs=5 \
    --gpu_precision_loss_allowed=true 
GPU delegate created.
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Replacing 623 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:77 Test interpreter has been initialized.
native : lite/tools/evaluation/stages/tflite_inference_stage.cc:144 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 389 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 336 partitions.
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:91 Reference interpreter (1 thread on CPU) has been initialized.
Num evaluation runs: 5
Reference run latency: avg=645950(us), std_dev=40910(us)
Test run latency: avg=62793.9(us), std_dev=3209(us)
OutputDiff[0]: avg_error=0.394511, std_dev=0.139682
```

```
➜   adb shell /data/local/tmp/run_eval \
    --model_file=/data/local/tmp/model.tflite \
    --delegate=gpu \
    --num_runs=5 \
    --gpu_precision_loss_allowed=false
GPU delegate created.
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Replacing 623 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:77 Test interpreter has been initialized.
native : lite/tools/evaluation/stages/tflite_inference_stage.cc:144 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 389 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 336 partitions.
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:91 Reference interpreter (1 thread on CPU) has been initialized.
Num evaluation runs: 5
Reference run latency: avg=650665(us), std_dev=44175(us)
Test run latency: avg=162572(us), std_dev=2556(us)
OutputDiff[0]: avg_error=5.53458e-06, std_dev=1.72756e-06
```

**Describe the expected behavior**
The result difference between CPU and GPU result should be similar. It is expected that avg_error should less than 0.003.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
1. The custom model I attached 
2. GPU Delegate - OpenCL backend
3. Precision loss enabled

Please let me know, if you need more details/logs/code etc. Thanks in advance.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
