### ISSUE TITLE
Retrieving exactly the same recommendations for all users

### ISSUE THREAD

**Issue by hamcapem** [tensorflow/tensorflow#52831]
## URL(s) with the issue:
https://www.tensorflow.org/recommenders/examples/basic_retrieval#making_predictions

## Description of issue (what needs changing):
When making predictions, the model is retrieving the exact same predictions for all users when using other datasets.

### Clear description
When model is trained and we're making predictions, everything works fine when using the movielens dataset which is provided in the tutorial.
But if swapping to any other dataset (have tried several datasets), the recommendation becomes the exact same for all users.

### Correct links
I cannot publish my data since it is GDPR sensitive. However, this user has used an open source data and has published his work on Github:
https://github.com/fickaz/TFRS-on-Retail-Data/blob/main/src%20a.%20Retrieval.ipynb

Unfortunately, he has not checked predictions for any other user than "user 42". But if you replicate his work, you will see that the predictions are same for all users.

### Parameters defined
In my dataset (recipes), I have tried to mimic the Movielens dataset as close as possible, ending up with around 1k users, 1k recipes and 100k rows. each user has interacted with about 60-300 recipes during 1 year.
Movielens dataset have 25-700 movies per user. Other than that, very similair.

**Comment by sushreebarsa** [comment]
@hamcapem 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by hamcapem** [comment]
There is no template for "other issues" though

**Comment by sushreebarsa** [comment]
@hamcapem Could you please let us know which TF version you are using ? Thanks!

**Comment by hamcapem** [comment]
@sushreebarsa I am using the following versions:
tf   version:    2.6.0
tfrs version:   v0.6.0
tfds version:    4.4.0

**Comment by sushreebarsa** [comment]
@Saduf2019 Was able to replicate the issue on colab using TF v2.6.0 ,please find the [gist](https://colab.research.google.com/gist/sushreebarsa/cb2ac34b3cdabd2ad1ccdace0dd19f07/basic_retrieval.ipynb) for reference.Thanks!

**Comment by hamcapem** [comment]
@Saduf2019 any luck with this?

**Comment by hamcapem** [comment]
@jvishnuvardhan did you have a chance to look at this?

**Comment by jvishnuvardhan** [comment]
@hamcapem Sorry for the late response. I checked with `TF2.7` and I see different recommendations for different users. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/436a436b1cc63c1d712b9196f55fe15e/basic_retrieval.ipynb).

```
# Get recommendations.
_, titles = index(tf.constant(["42"]))
print(f"Recommendations for user 42: {titles[0, :3]}")

Recommendations for user 42: [b'Bridges of Madison County, The (1995)'
 b'Father of the Bride Part II (1995)' b'Rudy (1993)']

# Get recommendations.
_, titles = index(tf.constant(["44"]))
print(f"Recommendations for user 44: {titles[0, :3]}")

Recommendations for user 44: [b'Lion King, The (1994)' b'Aristocats, The (1970)'
 b'Sword in the Stone, The (1963)']

# Get recommendations.
_, titles = index(tf.constant(["2"]))
print(f"Recommendations for user 2: {titles[0, :3]}")

Recommendations for user 2: [b'A Chef in Love (1996)' b'Secrets & Lies (1996)' b'Kolya (1996)']

```

Please let us know if I am interpreting the results correctly or not. Thanks!

**Comment by hamcapem** [comment]
> @hamcapem Sorry for the late response. I checked with `TF2.7` and I see different recommendations for different users. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/436a436b1cc63c1d712b9196f55fe15e/basic_retrieval.ipynb).
> 
> ```
> # Get recommendations.
> _, titles = index(tf.constant(["42"]))
> print(f"Recommendations for user 42: {titles[0, :3]}")
> 
> Recommendations for user 42: [b'Bridges of Madison County, The (1995)'
>  b'Father of the Bride Part II (1995)' b'Rudy (1993)']
> 
> # Get recommendations.
> _, titles = index(tf.constant(["44"]))
> print(f"Recommendations for user 44: {titles[0, :3]}")
> 
> Recommendations for user 44: [b'Lion King, The (1994)' b'Aristocats, The (1970)'
>  b'Sword in the Stone, The (1963)']
> 
> # Get recommendations.
> _, titles = index(tf.constant(["2"]))
> print(f"Recommendations for user 2: {titles[0, :3]}")
> 
> Recommendations for user 2: [b'A Chef in Love (1996)' b'Secrets & Lies (1996)' b'Kolya (1996)']
> ```
> 
> Please let us know if I am interpreting the results correctly or not. Thanks!

Hi @jvishnuvardhan,

I think you missed the description of the issue:

`When model is trained and we're making predictions, everything works fine when using the movielens dataset which is provided in the tutorial.
But if swapping to any other dataset (have tried several datasets), the recommendation becomes the exact same for all users.
`

In your test, you seem to have used the movielens dataset again.

**Comment by hamcapem** [comment]
Is anyone still working on this? It's soon half a year now..

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
