### ISSUE TITLE
Is there a way of 'cutting' a network?

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/tensorflow#5283]
I wonder if there is a way of 'cutting' the network. What I want to achieve is fine-tuning of the whole inception v3 network and then implement transfer learning by replacing the last 2 inception modules with new layers. I did the whole fine-tuning using this code https://github.com/tensorflow/models/tree/master/inception on my own dataset taking the last checkpoint that I need but now I don't know how I can implement the transfer learning by taking the output of 8th inception module and train the new layers. Is there a standard tensorflow-way of doing this operation?

**Comment by drpngx** [comment]
You can keep the layers in the graph. Just add a new connection and `sess.run(x)`.

**Comment by chrisrn** [comment]
If I add a new connection, I will have new variables and I think I will have problem with the checkpoint restoration.

**Comment by chrisrn** [comment]
I have worked at this code https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py
too and the transfer learning here is easy to understand, but if I decide to implement it in this way I need to create a protocol buffer file for my 'fine-tuning' graph. But I hope there is an easier way.

**Comment by aselle** [comment]
Unless there is a bug you suspect, please re-ask this issue on StackOverflow. That forum is a better place to ask "how do I do something." Thanks!
