### ISSUE TITLE
please add tf.size support

### ISSUE THREAD

**Issue by zuozhen** [tensorflow/tensorflow#52852]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.4.1

**Provide the text output from tflite_convert**
```
tf.size' of is neither a custom op nor a flex op
```

**Standalone code to reproduce the issue** 
https://www.tensorflow.org/lite/tutorials/pose_classification

Also, please include a link to a GraphDef or the model if possible.

=====In Addition======
I know that the convert works if add following line,
```
converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.  --> because tf.Size is not supported by tflite
    ]
```
but, this tflite model does not work on Android even if I add "tensorflow-lite-select-tf-ops.aar" inside my project.
So, could you please add tf.size support, please?

Or is there another way to replace tf.size when training this pose_classification model?
there're two place using the 'tf.size' inside the tutorial:

```
pose_center = tf.broadcast_to(pose_center, 
                                [tf.size(landmarks) // (17*2), 17, 2])
```

**Comment by sachinprasadhs** [comment]
Since Tensorflow Life supports limited number of builtin operators, however you can still enable `tf.size` with the `select TF option`.
Refer [this](https://www.tensorflow.org/lite/guide/ops_select) documentation for more details. Thanks!

**Comment by karimnosseir** [comment]
@zuozhen Regarding the part about not working in your app after converting with TF_SELECT.
Can you please follow the instructions [here](https://www.tensorflow.org/lite/guide/ops_select#android_aar) and let us know how it works

**Comment by zuozhen** [comment]
> @zuozhen Regarding the part about not working in your app after converting with TF_SELECT. Can you please follow the instructions [here](https://www.tensorflow.org/lite/guide/ops_select#android_aar) and let us know how it works

@karimnosseir Thanks for your reply. I did follow that instruction step by step, but it crush at the native part.  In consideration of it works now by an alternative method, I'd close this issue.
