### ISSUE TITLE
[Tflite] quantized ABS operator doesn't behave as intended

### ISSUE THREAD

**Issue by johan-gras** [tensorflow/tensorflow#52854]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master/nightly
- Python version: 3.7
- Bazel version (if compiling from source): 3.7.2

**Describe the current behavior**
(Please read the standalone code)
I have quantized tf.math.abs via int8 post-training quantization with a representative dataset of negative values only.
When running the model in tflite by giving negative values to the model the output will be zeros.
When looking at the tflite model in Netron it seems that the output_scaling and output_zero_point is erroneous (the range can only represent negative values). output_scale = 0.003921568859368563 and output_zero_point = -127

**Describe the expected behavior**
I expect the quantized tf.math.abs operator to output positive values and to have a correct output scaling and zero_point.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): depending on the complexity of the solution

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

input_data = np.array([-0.2, -0.33, -1.0, -0.4, -0.1], dtype=np.float32)

inp = tf.keras.Input(shape=(5,))
out = tf.math.abs(inp)
model = tf.keras.Model(inp, out)

# Post training quantization
def representative_dataset():
    yield [input_data]
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_quant_model = converter.convert()
tflite_model_path = "model.tflite"
with open(tflite_model_path, "wb") as f:
    f.write(tflite_quant_model)

# Tflite inference with the quantized model
interpreter = tf.lite.Interpreter(tflite_model_path)
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]["index"], [input_data])
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]["index"])

# The quantized model doesn't behave as expected:
# The quant output should be able to represent positive numbers
# However, the quant output can't represent positive numbers
# Input_scale = output_scale = 0.003921568859368563
# Input_zero_point = output_zero_point = -127
print("input: ", input_data)  # [-0.2, -0.33, -1.0, -0.4, -0.1]
print("expected output: ", model(input_data))  # [0.2  0.33 1.   0.4  0.1 ]
print("quantized output: ", output_data)  # [[0. 0. 0. 0. 0.]]
```

**Comment by mohantym** [comment]
Hi @sachinprasadhs! Could you please look at this issue! Attaching Gist in [2.5](https://colab.sandbox.google.com/gist/mohantym/a977debead828c24a0d72d7c6c0320d0/github_52854.ipynb#scrollTo=9bXl_OvYRhis),[2.6 ](https://colab.sandbox.google.com/gist/mohantym/f0a7d4dfb0db0cf0067a0b5d20bd0b76/github_52854.ipynb)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/495ed934741467da97352bef5c09b6f1/github_52854.ipynb#scrollTo=9bXl_OvYRhis)for reference . Thanks!

**Comment by Tessil** [comment]
We looked a bit on our side and it seems the quantizer takes either the scaling/zero-point of one of the inputs or of one of the outputs when the operator has the `SameOperandsAndResultsScale` trait and override all the inputs and outputs scaling/zero-point with it.

Ideally I think it should calculate the common scaling/zero-point based on the union of all the inputs ranges and outputs ranges of the operator (e.g. if we have a `[-1.0; 0]` input range and a `[0; 1.0]` output range, a common union range of `[-1.0; 1.0]` should be used to calculate the scaling/zero-point that will be affected to the input and output). I wonder though if there may be a reason why it wasn't done like that initially?

**Comment by daverim** [comment]
Sorry for the delay, adding this to my to fix queue

**Comment by Tessil** [comment]
It seems the problem was resolved by https://github.com/tensorflow/tensorflow/commit/99bc50cb35133301f0fb1700b7308d4bdea1d546. The ticket can be closed, thanks.
