### ISSUE TITLE
Linker command not proper, as it does not look under /usr/local/lib

### ISSUE THREAD

**Issue by Ashvith** [tensorflow/tensorflow#52867]
## URL(s) with the issue:

https://www.tensorflow.org/install/lang_c

## Description of issue (what needs changing):

In the **Linker** section, the given command is `sudo ldconfig`, but as per the description, it only links to the trusted directories (`/lib` and `/usr/lib`). This needs to be replaced with `sudo ldconfig /usr/local/lib -v` (-v is optional, only for verbose) assuming that the libtensorflow files have been extracted in `/usr/local`.

### Clear description

If this method is not used, then we get this error while building the example "Hello World" program:
`libtensorflow.so.2: cannot open shared object file: No such file or directory`.

**Comment by Saduf2019** [comment]
@Ashvith 
A CL has been created and once that is closed this issue will be closed.

**Comment by Saduf2019** [comment]
@Ashvith 
Please refer to the page for the update and move the issue to closed status.

**Comment by Ashvith** [comment]
@Saduf2019 thanks for the improvement, I'll be closing this issue.
