### ISSUE TITLE
Ability of flow, flowFromDirectory and flowFromDataFrame in ImageDataGenerator to self generate class weights

### ISSUE THREAD

**Issue by MrinalTyagi** [tensorflow/tensorflow#52884]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.** Addition of new attribute to generator in order to compute class weights in case of a class imbalanced dataset.

**Will this change the current api? How?** Yes. It will add a new attribute to the flow, flowFromDirectory, flowFromDataFrame and a method that will compute class weights based on strategy provided by the user as in scikitlearn compute class weights.

**Who will benefit with this feature?** It will benefit users with an imbalanced dataset to be able to compute the class weights within TensorFlow and not rely on any other library to compute class weights. 

**Any Other info.** Will be really helpful for users.

**Comment by tilakrayal** [comment]
@MrinalTyagi ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by MrinalTyagi** [comment]
Addition of a new attribute and a method that will be available to the objects of this class. If the user wants to use class weights in model training then this attribute can directly be used rather than relying on any other library like scikit learn or method to compute class weights. This will be very useful in case of class imbalanced dataset as it will fasten up the process of training a model as well as they don't have to spend time searching how to get class weights. It will be also helpful for beginners who have very less knowledge regarding class imbalance issue and how to solve it.

**Comment by sachinprasadhs** [comment]
Hi, Thanks for this feature request, could you please open this feature request in [keras repo](https://github.com/keras-team/keras/issues) since `ImageDataGenerator` comes under tf.keras and we can track this separately there.

**Comment by MrinalTyagi** [comment]
sure
