### ISSUE TITLE
Handpose model doesn't get image data from React Native Canvas

### ISSUE THREAD

**Issue by svzj95** [tensorflow/tensorflow#52888]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Expo, Windows
- Xiaomi Redmi note 9 pro 5g

package.json:
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@tensorflow-models/handpose": "^0.0.7",
    "@tensorflow/tfjs": "^3.9.0",
    "@tensorflow/tfjs-backend-webgl": "^3.9.0",
    "@tensorflow/tfjs-converter": "^3.9.0",
    "@tensorflow/tfjs-core": "^3.9.0",
    "@tensorflow/tfjs-react-native": "^0.7.0",
    "async-storage": "^0.1.0",
    "base-64": "^1.0.0",
    "expo": "~42.0.1",
    "expo-camera": "~11.2.2",
    "expo-gl": "^10.4.2",
    "expo-gl-cpp": "~10.4.1",
    "expo-image-picker": "~10.2.2",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-canvas": "^0.1.38",
    "react-native-fs": "^2.18.0",
    "react-native-get-real-path": "https://github.com/Wraptime/react-native-get-real-path.git",
    "react-native-web": "~0.13.12",
    "react-native-webview": "11.6.2",
    "three": "^0.133.1"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "@types/react-native-canvas": "^0.1.8",
    "@types/three": "^0.133.0",
    "typescript": "~4.0.0"
  },
  "private": true
}
`

code:
`
import React, {Component} from 'react';
import {Image, ScrollView, StatusBar, View, StyleSheet, Button, Platform} from 'react-native';
import * as ImagePicker from 'expo-image-picker';

import Canvas, {Image as CanvasImage} from 'react-native-canvas';

import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';
import * as handpose from "@tensorflow-models/handpose";
import {decode as atob, encode as btoa} from "base-64";

const Example = ({children}) => (
    <View style={styles.example}>
        <View style={styles.exampleLeft}>{children}</View>
    </View>
);

export default class App extends Component {
    constructor(props) {
        super(props);

        this.state = {
            image: null,
            tfIsReady: false, model: null
        };

        this.handleImageData = this.handleImageData.bind(this);
        this.pickImage = this.pickImage.bind(this);
        this.processImage = this.processImage.bind(this);
        this.canvas = React.createRef();
    }

    async componentDidMount() {
        await (async () => {
            if (Platform.OS !== 'web') {
                const {status} = await ImagePicker.requestMediaLibraryPermissionsAsync();
                if (status !== 'granted') {
                    alert('Sorry, we need camera roll permissions to make this work!');
                }
            }
        })();

        await tf.ready();
        // Signal to the app that tensorflow.js can now be used.
        this.setState({
            isTfReady: true,
        });

        console.log("tfReady");

        this.setState({model: await handpose.load()});

        console.log("handposeLoad");
    };

    handleImageData() {
        const image = this.state.image;
        const canvas = this.canvas.current;
        const model = this.state.model;

        if (canvas && image && model) {

            if (!(canvas instanceof Canvas)) {
                return;
            }

            console.log("Drawing picture");
            const img = new CanvasImage(canvas);
            let aspectRatio = image.width / image.height;

            let width = 200;
            let height = 200;

            canvas.width = width;
            canvas.height = height;

            const context = canvas.getContext('2d');

            img.src = 'data:image/png;base64,' + image.base64;
            img.addEventListener('load', () => {
                context.drawImage(img, 0, 0, width, height);
            });

        }
    };

    async processImage() {
        const canvas = this.canvas.current;
        const model = this.state.model;
        const image = this.state.image;

        if (model && canvas) {
            console.log()
            const context = canvas.getContext('2d');

            let imageData = await context.getImageData(0, 0, image.width, image.height);

            const hand = await model.estimateHands(imageData);
            console.log(hand);
        }
    }

    async pickImage() {
        let result = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.All,
            allowsEditing: true,
            quality: 1,
            base64: true
        });

        console.log(result.width);

        if (!result.cancelled) {
            this.setState({image: result})
        }
    };

    render() {
        return (
            <View style={styles.container}>
                <StatusBar hidden={true}/>
                <Button title="Pick an image from camera roll" onPress={this.pickImage}/>
                <Button title="Draw image" onPress={this.handleImageData}/>
                <Button title="Process image" onPress={this.processImage}/>
                <ScrollView style={styles.examples}>
                    <Example>
                        <Canvas ref={this.canvas}/>
                    </Example>
                </ScrollView>
            </View>
        );
    }
}

const commonStyles = StyleSheet.create({
    full: {
        left: 0,
        width: '100%',
        height: '100%',
    },
    cell: {
        flex: 1,
        padding: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
});

const styles = StyleSheet.create({
    container: {
        backgroundColor: 'white',
        ...commonStyles.full,
    },
    examples: {
        ...commonStyles.full,
        padding: 5,
        paddingBottom: 0,
    },
    example: {
        paddingBottom: 5,
        flex: 1,
        flexDirection: 'row',
    },
    exampleLeft: {
        ...commonStyles.cell,
    },
    exampleRight: {
        ...commonStyles.cell,
    },
});

`

**Describe the current behavior**
Got error: 
`[Unhandled promise rejection: Error: pixels passed to tf.browser.fromPixels() must be either an HTMLVideoElement, HTMLImageElement, HTMLCanvasElement, ImageData in browser, or OffscreenCanvas, ImageData in webworker or {data: Uint32
Array, width: number, height: number}, but was ImageData]
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:8871:14 in fromPixels_
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:5406:25 in f2
at node_modules\@tensorflow-models\handpose\dist\index.js:170:40 in tf.tidy$argument_0
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4394:23 in scopedRun$argument_2
at node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:4404:23 in Engine.prototype.scopedRun
at node_modules\@tensorflow-models\handpose\dist\index.js:168:32 in __generator$argument_1
at node_modules\@tensorflow-models\handpose\dist\index.js:48:17 in step
at node_modules\@tensorflow-models\handpose\dist\index.js:23:13 in <anonymous>
at node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
at node_modules\@tensorflow-models\handpose\dist\index.js:19:11 in <anonymous>
at App.tsx:98:31 in processImage
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:165:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
`

**Describe the expected behavior**
It should happen estimation hands on Image Data

**Comment by sushreebarsa** [comment]
@svzj95 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!
