### ISSUE TITLE
Tensorflow2.4 matmul returns different result(CPU)  comparing  numpy & torch matmul

### ISSUE THREAD

**Issue by lxsyz** [tensorflow/tensorflow#52893]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.6.9

**Describe the current behavior**
```
>>> tf.matmul(inputs, kernel)
<tf.Tensor: shape=(1, 27, 512), dtype=float32, numpy=
array([[[ 0.28822073, -1.4294956 , -0.98417675, ..., -1.3555392 ,
          1.3087683 ,  1.0613352 ],
        [-0.2037763 ,  0.5733212 ,  0.13983761, ..., -0.27103314,
         -0.47976002, -1.5966026 ],
        [-0.20868134,  0.33820766,  0.3898036 , ...,  0.09645928,
         -0.34314552, -0.85622734],
        ...,
        [ 0.7347749 , -0.20192856, -0.6455916 , ...,  0.8365166 ,
         -0.14322701,  0.32350197],
        [-0.02274738,  0.2568301 ,  0.39510253, ..., -0.6229611 ,
          1.9619648 , -0.9404138 ],
        [ 0.2989933 , -1.4857576 , -1.4279732 , ..., -2.0946026 ,
          1.0505235 ,  0.51986885]]], dtype=float32)>

>>> np.matmul(inputs, kernel)
array([[[ 0.28822058, -1.4294958 , -0.9841767 , ..., -1.3555391 ,
          1.308768  ,  1.061335  ],
        [-0.20377651,  0.5733212 ,  0.13983764, ..., -0.27103332,
         -0.47975984, -1.5966021 ],
        [-0.20868114,  0.33820775,  0.38980353, ...,  0.09645933,
         -0.34314537, -0.8562276 ],
        ...,
        [ 0.7347748 , -0.20192836, -0.6455917 , ...,  0.83651644,
         -0.14322703,  0.3235021 ],
        [-0.02274731,  0.25683013,  0.39510256, ..., -0.6229611 ,
          1.9619651 , -0.94041383],
        [ 0.29899323, -1.4857576 , -1.4279728 , ..., -2.0946023 ,
          1.0505236 ,  0.5198687 ]]], dtype=float32)
# And in torch
>>> input.matmul(weight.t()).numpy()
array([[[ 0.28822058, -1.4294958 , -0.9841767 , ..., -1.3555391 ,
          1.308768  ,  1.061335  ]],
       [[-0.20377651,  0.5733212 ,  0.13983764, ..., -0.27103332,
         -0.47975984, -1.5966021 ]],
       [[-0.20868114,  0.33820775,  0.38980353, ...,  0.09645933,
         -0.34314537, -0.8562276 ]],
       ...,
       [[ 0.73477507, -0.20192847, -0.6455916 , ...,  0.83651686,
         -0.14322712,  0.32350177]],
       [[-0.02274727,  0.25683028,  0.39510256, ..., -0.62296104,
          1.9619647 , -0.94041365]],
       [[ 0.29899323, -1.4857576 , -1.427973  , ..., -2.0946026 ,
          1.0505236 ,  0.51986873]]], dtype=float32)
```
As we can see, the number in seventh decimal is different.  TF is 0.28822073, torch and numpy are both 0.28822058.
The function is very important.I want to know why the error appears and how to fix it. Thank you.
**Describe the expected behavior**
The results are all the same.
If someone wants the data(input & weight), I can upload.
ps: input shape is 27 * 512, weight shape is 512 * 512

**Comment by tilakrayal** [comment]
@lxsyz ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by lxsyz** [comment]
@tilakrayal I'm sorry I can't upload entire code and model. I have uploaded test code and weights in this repo
[https://github.com/lxsyz/temp](https://github.com/lxsyz/temp)
just run `test.py`, and you will see the result is different.

**Comment by tilakrayal** [comment]
@lxsyz ,
I was able to execute the code without any issues.Please find the metrics in gist [here](https://colab.research.google.com/gist/tilakrayal/e2b4e12e4815f9b3a89ccbc057b45e07/52893.ipynb).I was not able to find the mentioned issue(0.28822073) in v2.6.Requesting to test your code in latest tf v2.6.Thanks
