### ISSUE TITLE
How to install tensorflow to ARM32 Windows platform? Is there any solution for this problem?

### ISSUE THREAD

**Issue by alenandry** [tensorflow/tensorflow#52895]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- ARM32 Windows10
- GPU model and memory:16G

**Describe the problem**
ARM base Windows system can't install tensorflow?
Is there any solution for this?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Can't install tensorflow

**Any other info / logs**
Can't install tensorflow on ARM32  Windows10

**Comment by mohantym** [comment]
Hi @alenandry ! Could you check out these threads ? [link1](https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel),[link2](https://stackoverflow.com/questions/33634525/tensorflow-on-32-bit-linux). Thanks!

**Comment by mihaimaruseac** [comment]
We don't support ARM architectures at the moment
