### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Mohammedirfan25** [tensorflow/tensorflow#52897]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.5 LTS x86_64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.6.0
- Python version:3.6.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory: VMware SVGA II Adapter, 16035MiB

![Screenshot at 2021-11-01 20-31-51](https://user-images.githubusercontent.com/55286282/139698557-1530fd25-fc97-4aa1-bb44-9a240c6f9009.png)
![Screenshot at 2021-11-01 20-55-10](https://user-images.githubusercontent.com/55286282/139698566-a21d34f8-e85d-479e-a0f2-77bdc87e6c95.png)
![Screenshot at 2021-11-01 20-56-47](https://user-images.githubusercontent.com/55286282/139698570-675ead7b-48d0-4a72-a939-a34c16db435b.png)

**Describe the problem**
i am using latest tensorflow and i am getting error. kindly help me to fix this issue.
i saw some fixes they said me to use tensorflow version 1.5 but i have to use tensorflow version 2 is there any other ways to fix it?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Comment by Saduf2019** [comment]
@Mohammedirfan25 
Can you please run below code and share the output [also please share text in place of screenshots next time which will help ither users as well]

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/47245#issuecomment-786245812), and similar issues :[link](https://github.com/tensorflow/tensorflow/issues/40814#issuecomment-663838196), #47002.

**Comment by sorenwacker** [comment]
It seems impossible to run 

    print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

if the tensorflow import breaks already.

I have that on a node without any GPUs.
