### ISSUE TITLE
Bug: SomeTimes Coredumped using tfjob

### ISSUE THREAD

**Issue by berlinsaint** [tensorflow/tensorflow#52894]
hello, iam using tfjob to train keras model.

most of times, they work fine. But some times, it will crash  after train and savemodel.

our partial train code is here:

```python
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="/workspace/model/fit_logs/", histogram_freq=1)

    model.fit(
        dataset,
        epochs=epochs,
        verbose=2#,
#         validation_data=test_dataset#,
#         callbacks = [tensorboard_callback]
#         callbacks=[EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)]
    )

    # checkpoint_path = '/'.join((args.checkpoint_path, save_day, save_hour))
    # if TASK_INDEX == 0:
    #    checkpoint_path = checkpoint_path
    # else:
        # Save to a path that is unique across workers.
    #    checkpoint_path = checkpoint_path + '/worker_tmp_' + str(TASK_INDEX)

    inputs = tf.keras.layers.Input(shape=(input_length,), dtype=tf.int64, name='input')
    outs = model(inputs)
    mymodel = tf.keras.Model(inputs, outs)
    mymodel.save(checkpoint_path)

    if TASK_INDEX == 0:
        # tf2onnx
        try:
            onnx_args = OnnxArgs()
            onnx_args.saved_model = checkpoint_path
            onnx_args.output = checkpoint_path + '/deepfm.onnx'
            onnx_args.tag = 'serve'


            parse2onnx(onnx_args)
            logging.info("Success")
            logging.info(onnx_args.saved_model)
        except Exception as e:
            logging.error("Failed convert")
            logging.error(str(e))
```
And the log is:
![image](https://user-images.githubusercontent.com/10629930/139662542-31221f80-a0de-4c76-b4f5-cfd017612de4.png)

I get the coredumpe file;

it show this:
![image](https://user-images.githubusercontent.com/10629930/139662656-6a26ea88-2d49-4472-a1b3-e5b07d801654.png)

the operator log is :

i don't know the reason and don't know whether it is a tensorflow bug...
![image](https://user-images.githubusercontent.com/10629930/139662899-d21133db-6b1c-4567-ac5d-6811f41f00f4.png)

Any help will be appreciated... Thanks alot

**Comment by berlinsaint** [comment]
Tensorflow Version is 2.6， and i also try 2.7dev.  But some times They both occur the same coredumped....

**Comment by sushreebarsa** [comment]
@berlinsaint 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by berlinsaint** [comment]
> @berlinsaint Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!

i thinks it may not be the keras problem...

i have the same  symptom as the [issue-50853](https://github.com/tensorflow/tensorflow/issues/50853)

**Comment by sushreebarsa** [comment]
@berlinsaint 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by berlinsaint** [comment]
> @berlinsaint 
> 
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

i dont know how to reproduce it，it's strange!  Just in distributed training . And it has nearlt the same stack as

**Comment by sushreebarsa** [comment]
@berlinsaint Without the reproducible code it is difficult for us to replicate the issue from our end. Could you please open this issue in [TF discussion forum](https://discuss.tensorflow.org/) as there is a larger community there.Thank you!
