### ISSUE TITLE
tf.linalg.triangular_solve different behaviour on CPU vs GPU

### ISSUE THREAD

**Issue by qiq208** [tensorflow/tensorflow#52896]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- https://colab.research.google.com/drive/1uTUzEQXDR6JvCkFQyS-3n2pAUKAH-TLk?usp=sharing#scrollTo=BcSb0SDQ5nI0
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 (also Colab)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.3 (also Colab)
- Python version: 3.7.10

**Describe the current behavior**
When trying to apply tf.linalg.triangular_solve on an invalid input matrix (in my case I included np.nan in the matrix) - different behaviour is observed when running on CPU vs GPU. On GPU - the functions returns NaNs, whereas on CPU an InvalidArgumentError occurs

**Describe the expected behavior**
Consistent behaviour between CPU & GPU

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1uTUzEQXDR6JvCkFQyS-3n2pAUKAH-TLk?usp=sharing#scrollTo=BcSb0SDQ5nI0

**Comment by sanatmpa1** [comment]
@qiq208,

As per the colab link provided, with CPU we get `InvalidArgumentError` and with GPU, it returns NaNs whereas in the issue description you have mentioned in the opposite way.

**Comment by sanatmpa1** [comment]
I am able to reproduce the issue reported, in colab with both TF `2.6.0` and nightly `2.8.0-dev20211101`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/3e3ef7ffc3c1fff14c57d2b112679d38/triangular_solve_cpu_gpu.ipynb)
