### ISSUE TITLE
tf.repeat fails with jit_compile when repeats is a tensor!

### ISSUE THREAD

**Issue by MedAbdelkaderAbba** [tensorflow/tensorflow#52905]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**: 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):compiled from source
- TensorFlow version (use command below):2.5.6
- Python version:3.8
- Bazel version (if compiling from source):bazel 4.2.1
- GCC/Compiler version (if compiling from source):9.3.0
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.repeat fails if the repeats argument is a tensor
**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np


####
#### test repeat within jit_compile
####

repeats = tf.constant([10, 5, 1])

@tf.function(jit_compile = True)
def repeat_vector(x):
    return tf.repeat(x, repeats, axis=-1)

x = [1., 2., 3.] 
repeat_vector(x)
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
2021-11-01 19:00:56.491404: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x221bf60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-01 19:00:56.491446: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): Host, Default Version
2021-11-01 19:00:56.496213: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at xla_ops.cc:247 : Invalid argument: Detected unsupported operations when trying to compile graph __inference_repeat_vector_58[_XlaMustCompile=true,config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000",executor_type=""] on XLA_CPU_JIT: Where (No registered 'Where' OpKernel for XLA_CPU_JIT devices compatible with node {{node Repeat/boolean_mask/Where}}){{node Repeat/boolean_mask/Where}}
The op is created at: 
File "test_repeat.py", line 20, in <module>
  repeat_vector(x)
File "test_repeat.py", line 14, in repeat_vector
  return tf.repeat(x, repeats, axis=-1)
Traceback (most recent call last):
  File "test_repeat.py", line 20, in <module>
    repeat_vector(x)
  File "/home/mabba/tf_cpu_source/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/home/mabba/tf_cpu_source/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 956, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/home/mabba/tf_cpu_source/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/mabba/tf_cpu_source/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/mabba/tf_cpu_source/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_repeat_vector_58[_XlaMustCompile=true,config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000",executor_type=""] on XLA_CPU_JIT: Where (No registered 'Where' OpKernel for XLA_CPU_JIT devices compatible with node {{node Repeat/boolean_mask/Where}}){{node Repeat/boolean_mask/Where}}
The op is created at: 
File "test_repeat.py", line 20, in <module>
  repeat_vector(x)
File "test_repeat.py", line 14, in repeat_vector
  return tf.repeat(x, repeats, axis=-1) [Op:__inference_repeat_vector_58]

```

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue ? It's replicating in [2.5](https://colab.sandbox.google.com/gist/mohantym/ce936b3de46b2a1b4ca88a6abbaa94cd/github_52905.ipynb#scrollTo=PUBnLDhStk5G),[2.6](https://colab.sandbox.google.com/drive/1PKuqXyhgob9oFsK_phrguptAcJf1kGT6?resourcekey=0-rknXJyWPxX_dTBg3sXh8ow#scrollTo=PUBnLDhStk5G) and [nightly](https://colab.sandbox.google.com/gist/mohantym/9e0d3cc296f5b87faf83c9bd186e6445/github_52905_2-6.ipynb#scrollTo=PUBnLDhStk5G).

**Comment by sanatmpa1** [comment]
@MedAbdelkaderAbba,

Can you take a look at this [documentation](https://www.tensorflow.org/xla#explicit_compilation_with_tffunctionjit_compiletrue) which says,

> The jit_compile API has must-compile semantics: either the entire function is compiled with XLA, or an errors.InvalidArgumentError exception is thrown.  

As per the error trace, it says that `No registered 'Where' OpKernel for XLA_CPU_JIT devices compatible with node` and since you have an unsupported operation, `InvalidArgumentError` is thrown which is expected. Can you try using auto-clustering for your case and try if it helps? Thanks!

**Comment by MedAbdelkaderAbba** [comment]
@sanatmpa1,
I am not sure I understand the auto-clustering part. I tried to set the following options in the code but nothing changed:
```
import os
  os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit``
```
Also, my concern is that the above code workd fine when the argument ''repeats" was a list
```
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import os
os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit'
####
#### test repeat within jit_compile
####

#repeats = tf.constant([10,5,1])
repeats = [10,5,1]
@tf.function(jit_compile = True)
def repeat_vector(x):
    return tf.repeat(x, repeats)


x = tf.constant([1., 5., 10.])
tf.print(repeat_vector(x))
```
this behavior is counter intuitive.

**Comment by ishark** [comment]
The support for Where op in XLA was added recently and should be available in TF nightly. 
@MedAbdelkaderAbba Could you please try to run the original code snippet again to check if this is resolved?

Thanks!

**Comment by sushreebarsa** [comment]
@MedAbdelkaderAbba This issue is not replicating in the latest TF versions, could you please refer to the attached [gist](https://colab.research.google.com/gist/sushreebarsa/84a9115a22ef18b875a277f558b9c1cd/52905.ipynb) and confirm the same?
Thanks!
