### ISSUE TITLE
WARNING : tensorflow:AutoGraph could not transform

### ISSUE THREAD

**Issue by pgrantgit** [tensorflow/tensorflow#52908]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.6.0
- Python version: 3.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudnn-11.4-windows-x64-v8.2.4.15 and cuda_11.4.2_471.41_win10
- GPU model and memory: N/A
-PyCharm details: PyCharm 2021.3 EAP (Community Edition)

**Describe the problem**
The issue occurs when creating an executable in PyCharm using TensorFlow. When running the program in the PyCharm IDE, no errors occur, but when the executable runs, this error and warning occurs:

2021-11-02 00:26:13.629314: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000015EDA772670> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function Model.make_train_function.<locals>.train_function at 0x0000015EDA772670>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
4333/4352 [============================>.] - ETA: 0s - loss: 0.0565 - accuracy: 0.9866WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x0000015EDA8F0A60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function Model.make_test_function.<locals>.test_function at 0x0000015EDA8F0A60>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Created a project in Python using TensorFlow. Converted the .py file to an executable using: pyinstaller --onefile xxxxxxx.py
When the executable runs, the warning/error occurs.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[TensorFlowBugReport.txt](https://github.com/tensorflow/tensorflow/files/7458622/TensorFlowBugReport.txt)
[TensorFlowPythonCode.txt](https://github.com/tensorflow/tensorflow/files/7458624/TensorFlowPythonCode.txt)

**Comment by sachinprasadhs** [comment]
You could silence the warning by decorating with  the function `@tf.autograph.experimental.do_not_convert`
