### ISSUE TITLE
[feature request & discuss] observe tensor execution efficiency by eBPF tracepoints.

### ISSUE THREAD

**Issue by SimonCqk** [tensorflow/tensorflow#52912]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

NONE

**Describe the feature and the current behavior/state.**

Have you guys ever think about expose tensor processing efficiency in large scale distributed training leveraging eBPF? The traced metrics can be consumed by other components, e.g. resource scheduler and infers the execution quality of each worker and find straggler worker (one of thousands scenarios, just a casual thinking)

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by tilakrayal** [comment]
@SimonCqk ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!
