### ISSUE TITLE
Build broken by incorrectly dropped comma

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#52910]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 8.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Build breaks with -
error in tensorflow_aarch64 setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'< 2.8'": Expected stringEnd

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=nonccl //tensorflow/tools/pip_package:build_pip_package --verbose_failures

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

See https://ci.linaro.org/job/ldcg-python-manylinux-tensorflow-nightly/156/console

Problem commit is https://github.com/tensorflow/tensorflow/commit/3e842b053711f2d81cd775037875a8d744d79ed5

**Comment by mohantym** [comment]
Hi @elfringham! Thanks for the PR .This issue will be closed once PR[ #52911](https://github.com/tensorflow/tensorflow/pull/52911) is merged.

**Comment by DEKHTIARJonathan** [comment]
Thanks, this indeed fix the issue

**Comment by elfringham** [comment]
The pending PR was ignored and the fix applied directly by @tensorflower-gardener  https://github.com/tensorflow/tensorflow/commit/ad8a18eaab4bf0b6e18272c9e54d8818e5875ac0
