### ISSUE TITLE
Installing tensorflow in python

### ISSUE THREAD

**Issue by LordFenny** [tensorflow/tensorflow#52915]
<em>hi, i'm trying to install tensorflow for python but i get two errors installing it, and i google but every solution dosn't work</em>

### **CODE**
`pip3 install tensorflow`

output: 
```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

### **2° TRIAL**
`pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.2.0-py2-none-any.whl`

output
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: tensorflow-1.2.0-py2-none-any.whl is not a supported wheel on this platform.

```

**_IT DOESN'T WORK_**
what shall i do??

**Comment by LordFenny** [comment]
just wanted to say that on the other computer it works, but on this one not

_can i transfer it somehow_ ?

**Comment by mohantym** [comment]
Hi @LordFenny !
Could you please the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) too as it helps us analyse the issue. Thanks!

**Comment by sachinprasadhs** [comment]
Could you please open this issue in https://developer.apple.com/forums/. Thanks

**Comment by mihaimaruseac** [comment]
Please fill in issue template.

Please make sure you are running on a 64 bit computer, have the newest pip package.

Please make sure your Python version is 3.7, 3.8 or 3.9. TF is not yet ready for Python 3.10 and versions below 3.7 are deprecated.

Please make sure you are installing TF 2.4 or later. Older versions are no longer supported
