### ISSUE TITLE
Missing libtensorflow builds for 2.6.1, 2.5.2 and 2.4.4

### ISSUE THREAD

**Issue by JustinWickMS** [tensorflow/tensorflow#52916]
There don't appear to be prebuilt binaries for libtensorflow (https://www.tensorflow.org/install/lang_c) for 2.6.1, 2.5.2 and 2.4.4.

These binaries exist for earlier point releases for those minor versions on https://storage.googleapis.com/tensorflow/libtensorflow/, but none exist for the above point releases.

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.6.1.tar.gz is one of the missing files.

See #48550 for a similar occurrence.

Would it be possible to push those binaries/trigger CI builds to generate them?

Thanks!

**Comment by mihaimaruseac** [comment]
Unfortunately automation for these releases has been broken and we had to do it manually. Will release these artifacts and publish them soon. Apologies for the delay

**Comment by mihaimaruseac** [comment]
I think all should be uploaded now. Please let us know if something is missing.

Thank you!

**Comment by JustinWickMS** [comment]
I've confirmed the availability of linux x86_64, presumably you've got the rest. My teams and I appreciate the quick turnaround time on this!

I'd say you can close the ticket now.

**Comment by sachinprasadhs** [comment]
Closing this,, since the issue was resolved. Thanks.
