### ISSUE TITLE
ValueError: input resource[0] expected type resource != float, the type of embeddings_sharded_0[0]

### ISSUE THREAD

**Issue by farzanehnakhaee70** [tensorflow/tensorflow#52921]
Hi,
I'm going to optimize my model and convert it to FP16. When using trt_conver, this error raises:
```
ValueError: input resource[0] expected type resource != float, the type of embeddings_sharded_0[0]
        In {{node EncoderTransformer/EmbeddingLookup/EmbeddingLookupUnique/embedding_lookup/Gather}}
```

**Comment by sushreebarsa** [comment]
@farzanehnakhaee70 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by liuyibox** [comment]
Got similar issue on tensorflow 2.9, any updated solution here.
