### ISSUE TITLE
Restoring a model with frozen TimeDistributed layers onto an unfrozen model does not work

### ISSUE THREAD

**Issue by brandon-wu76** [tensorflow/tensorflow#52923]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 21H1
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.6.0-0-g919f693420e 2.6.0
- Python version: 3.7.12
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The following (minimal) implementation of the model and weight saving and loading fails with the timedistributed layer but works without it.

```
import os
from tensorflow.keras.layers import Dense, Input, TimeDistributed
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.metrics import BinaryAccuracy
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications import MobileNetV2

def get_model(working_dir, finetune):

    base_model = MobileNetV2(weights='imagenet',
                             include_top=False,
                             alpha=1.4,
                             input_shape=(224, 224, 3),
                             pooling='avg')

    inp = Input((10, 224, 224, 3))
    x = TimeDistributed(base_model)(inp)

    # Comment out the previous two lines
    # and uncomment these next two lines to see the expected behavior

    # inp = base_model.input
    # x = base_model.output

    predictions = Dense(1, activation=sigmoid)(x)

    model = Model(inputs=inp, outputs=predictions)

    if not finetune:
        for layer in base_model.layers:
            layer.trainable = False
        learning_rate = 0.001
    else:
        saved_model_path = os.path.join(working_dir, "saved_model.h5")
        model.load_weights(saved_model_path)
        learning_rate = 0.00001

    binacc = BinaryAccuracy(name="binary_accuracy")
    adam = Adam(lr=learning_rate, epsilon=1e-09, clipnorm=0.001)

    model.compile(optimizer=adam,
                    loss='binary_crossentropy',
                    metrics=[binacc])
    model.summary()

    return model

working = "/content/test"

model = get_model(working, False)
model.save(os.path.join(working, "saved_model.h5"))
model = get_model(working, True)
```

I'm trying to finetune a model that I'm working on. I'm initially creating a model with a pretrained model connected to some new layers. The pretrained model is frozen for the first round of training and the model is saved. I then create the same model with the pretrained model unfrozen and try to restore the weights using model.load_weights. This results in the following error on my local pc running tensorflow 2.4.0.

"ValueError: Cannot assign to variable expanded_conv_depthwise/depthwise_kernel:0 due to variable shape (3, 3, 48, 1) and value shape (48,) are incompatible" and 

On Google Colab running tensorflow 2.6.0, I get

"ValueError: axes don't match array"

**Describe the expected behavior**

Weights should be restored correctly.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1X92pRi4yqNhOO0l_AAbpbSpaGidwytlP

**Comment by sanatmpa1** [comment]
@brandon-wu76,

I modified your code to save the model in `SavedModel` format and not on `h5 format`, which is working fine and I am able to load the model. Can you take a look at this [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/51357fe30394b38a564a41286fadecc9/untitled3.ipynb). Thanks!
