### ISSUE TITLE
tf.keras import raises an AlreadyExistsError with keras 2.7

### ISSUE THREAD

**Issue by frgfm** [tensorflow/tensorflow#52937]
Hello there :wave:

I encountered a CI problem with a build job today that wasn't happening yesterday. So I checked the difference in terms of dependency and the only difference was keras. So I inspected the traceback and ended up tracking the import from keras that causes trouble. I already reported this to the keras team in https://github.com/keras-team/keras/issues/15585 but I figured it might be of importance to you folks considering this impacts several imports from tensorflow itself!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.4.100 & cuDNN 8.2.2 
- GPU model and memory: NVIDIA GeForce RTX 2070 with Max-Q Design

**Describe the current behavior**

Running the standalone code throws an `AlreadyExistsError`

**Describe the expected behavior**

Not raising any error.

- Do you want to contribute a PR? (yes/no): happy to do so, but I'm not sure how to solve this
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

```python
from tensorflow.keras.utils import img_to_array
```

**Other info / logs** Include any logs or source code that would be helpful to

```
---------------------------------------------------------------------------
AlreadyExistsError                        Traceback (most recent call last)
<ipython-input-1-a2ab22b98110> in <module>
----> 1 from tensorflow.keras.utils import img_to_array

~/miniconda3/lib/python3.8/site-packages/keras/api/_v2/keras/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from keras import __version__
     11 from keras.api._v2.keras import __internal__
     12 from keras.api._v2.keras import activations

~/miniconda3/lib/python3.8/site-packages/keras/__init__.py in <module>
     23 
     24 # See b/110718070#comment18 for more details about this import.
---> 25 from keras import models
     26 
     27 from keras.engine.input_layer import Input

~/miniconda3/lib/python3.8/site-packages/keras/models.py in <module>
     18 import tensorflow.compat.v2 as tf
     19 from keras import backend
---> 20 from keras import metrics as metrics_module
     21 from keras import optimizer_v1
     22 from keras.engine import functional

~/miniconda3/lib/python3.8/site-packages/keras/metrics.py in <module>
     24 
     25 import numpy as np
---> 26 from keras import activations
     27 from keras import backend
     28 from keras.engine import base_layer

~/miniconda3/lib/python3.8/site-packages/keras/activations.py in <module>
     18 
     19 from keras import backend
---> 20 from keras.layers import advanced_activations
     21 from keras.utils.generic_utils import deserialize_keras_object
     22 from keras.utils.generic_utils import serialize_keras_object

~/miniconda3/lib/python3.8/site-packages/keras/layers/__init__.py in <module>
     21 
     22 # Generic layers.
---> 23 from keras.engine.input_layer import Input
     24 from keras.engine.input_layer import InputLayer
     25 from keras.engine.input_spec import InputSpec

~/miniconda3/lib/python3.8/site-packages/keras/engine/input_layer.py in <module>
     19 from keras import backend
     20 from keras.distribute import distributed_training_utils
---> 21 from keras.engine import base_layer
     22 from keras.engine import keras_tensor
     23 from keras.engine import node as node_module

~/miniconda3/lib/python3.8/site-packages/keras/engine/base_layer.py in <module>
     41 from keras.engine import node as node_module
     42 from keras.mixed_precision import autocast_variable
---> 43 from keras.mixed_precision import loss_scale_optimizer
     44 from keras.mixed_precision import policy
     45 from keras.saving.saved_model import layer_serialization

~/miniconda3/lib/python3.8/site-packages/keras/mixed_precision/loss_scale_optimizer.py in <module>
     16 
     17 from keras import backend
---> 18 from keras import optimizers
     19 from keras.mixed_precision import loss_scale as keras_loss_scale_module
     20 from keras.optimizer_v2 import optimizer_v2

~/miniconda3/lib/python3.8/site-packages/keras/optimizers.py in <module>
     24 from keras.optimizer_v1 import Optimizer
     25 from keras.optimizer_v1 import TFOptimizer
---> 26 from keras.optimizer_v2 import adadelta as adadelta_v2
     27 from keras.optimizer_v2 import adagrad as adagrad_v2
     28 from keras.optimizer_v2 import adam as adam_v2

~/miniconda3/lib/python3.8/site-packages/keras/optimizer_v2/adadelta.py in <module>
     20 import numpy as np
     21 from keras import backend_config
---> 22 from keras.optimizer_v2 import optimizer_v2
     23 from tensorflow.python.util.tf_export import keras_export
     24 

~/miniconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py in <module>
     34 
     35 
---> 36 keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
     37     "/tensorflow/api/keras/optimizers", "keras optimizer usage", "method")
     38 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/monitoring.py in __init__(self, name, description, *labels)
    358       *labels: The label list of the new metric.
    359     """
--> 360     super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
    361                                     len(labels), name, description, *labels)
    362 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/monitoring.py in __init__(self, metric_name, metric_methods, label_length, *args)
    133           self._metric_name, len(self._metric_methods)))
    134 
--> 135     self._metric = self._metric_methods[self._label_length].create(*args)
    136 
    137   def __del__(self):

AlreadyExistsError: Another metric with the same name already exists.
```

**Comment by bhayden53** [comment]
see https://github.com/tensorflow/tensorflow/issues/52922

keras 2.7 is not compatible with tf 2.6.x but the dependency specification in tensorflow 2.6.0 and 2.6.1 for keras `~=2.6` allows keras 2.7 to be installed.

**Comment by frgfm** [comment]
I see, so I guess this shouldn't be an issue anymore with TF 2.6.2 patch release?

**Comment by bhayden53** [comment]
seems to be the case, 2.6.2 is installing the correct versions of the dependencies in my builds

**Comment by jli** [comment]
This issue broke some of my team's production pipelines. We specify a dependency on `tensorflow==2.6.0`, but didn't specify a pinned version of Keras, so we automatically got 2.7.0 yesterday.

I think this is a bug with either:
1. [tensorflow's requirements specification](https://github.com/tensorflow/tensorflow/blob/v2.6.0/tensorflow/tools/pip_package/setup.py#L106) (eg for TF 2.6, I think the dependency should be `'keras == 2.6.*'` instead of `'keras ~= 2.6'`), or
2. Keras versioning not following [semver](https://semver.org/), since a minor version release was not backwards compatible.

Looks like TF's setup.py on master has been updated for this, so hopefully we won't see similar issues in the future: https://github.com/tensorflow/tensorflow/blob/8a2a4c3ca06a622989823c7dfa58e01044244935/tensorflow/tools/pip_package/setup.py#L102

**Comment by mihaimaruseac** [comment]
Should be fixed by TF 2.6.2 and TF 2.7

**Comment by mohantym** [comment]
Hi @frgfm ! This issue is not replicating with TF 2.6  or TF-nightly in Colab Environment.  Attaching [Gist](https://colab.research.google.com/gist/mohantym/0e6f734312f9b78b0f2760a5cc136800/github_52937.ipynb) for reference .

**Comment by frgfm** [comment]
Hi @mohantym,
I'm sure not sure this is related? The bottom of this issue is that there was a loose version constraint for keras on the TF side up until 2.6.2 and 2.7. So yes, if you manually install keras 2.6, it does work as expected :)
My point was that if you had installed one of the release before 2.6.2 (say 2.6.0), the installer might be tempted to install keras 2.7 which was not compatible. I haven't had time to test whether the issue still happens with TF 2.6.2 but this appears to have been solved :+1:

**Comment by mohantym** [comment]
Ok @frgfm ! Thanks for confirming the same .You can also test with TF 2.7 and Keras 2.7. Closing this issue as it seems to be resolved.
