### ISSUE TITLE
[TF-TRT] - TRTEngineOP do not show output shape

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#52934]
TRTEngineOP node attribute `_output_shapes` returns an empty list. We need to fix that.

@bixia1 @tfeher  FYI

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this feature request . PR has been created  for this issue in #52625

**Comment by DEKHTIARJonathan** [comment]
@mohantym a PR has not been created for the feature. It's left as a TODO. @bixia1 requested to create a GH issue for this

**Comment by Saduf2019** [comment]
@DEKHTIARJonathan 
please verify the PR and move this to closed status.

**Comment by DEKHTIARJonathan** [comment]
I specifically implemented the PR to fix this issue, so I don't need to check anything
