### ISSUE TITLE
TFlite model always have fixed dimensions output

### ISSUE THREAD

**Issue by whalefa1I** [tensorflow/tensorflow#52935]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):all the platform:(win10 ubuntu android)
- TensorFlow installed from (source or binary):(colab default)
- TensorFlow version:2.6.0(colab default)

I try to add some postprocess layers after [a Keras model](https://drive.google.com/file/d/1yKLW5F7-6x9ylH65MgVxH5N5oQJgK8wq/view?usp=sharing) which can detect faces in an image, then I convert it to Savedmodel format and the savedmodel also works well.After that I convert it to[ a tflite model](https://drive.google.com/file/d/1i1fLQTQGA7V8tcihyWhldoIswOaEe0tq/view?usp=sharing), but no matter what image I input, the tflite model alway has a fixed dimensions and it equals to a parameter [**max_output_size**,17] which I set in  
`out_boxes = tf.image.non_max_suppression(box_tlbr, scores, max_output_size=5,
                                                 score_threshold=0.5, iou_threshold=0.3)`
eg:
![no_face](https://user-images.githubusercontent.com/32239722/140266840-bab3021e-548f-4b28-8079-5d8902cf5c57.PNG)
tflite model output:
`[[ 4.5394583e+00  3.3936653e+00  2.9001554e+01  2.9001198e+01
   3.2894442e+00 -1.5875316e+00  9.0569210e+00 -7.6022291e-01
   5.5141363e+00  2.7957358e+00  3.5612986e+00  8.0328922e+00
  -3.7986336e+00  9.2154026e-02  1.3225850e+01  2.9794626e+00
   4.5634112e-03]
 [ 4.5394583e+00  3.3936653e+00  2.9001554e+01  2.9001198e+01
   3.2894442e+00 -1.5875316e+00  9.0569210e+00 -7.6022291e-01
   5.5141363e+00  2.7957358e+00  3.5612986e+00  8.0328922e+00
  -3.7986336e+00  9.2154026e-02  1.3225850e+01  2.9794626e+00
   4.5634112e-03]
 [ 4.5394583e+00  3.3936653e+00  2.9001554e+01  2.9001198e+01
   3.2894442e+00 -1.5875316e+00  9.0569210e+00 -7.6022291e-01
   5.5141363e+00  2.7957358e+00  3.5612986e+00  8.0328922e+00
  -3.7986336e+00  9.2154026e-02  1.3225850e+01  2.9794626e+00
   4.5634112e-03]
 [ 4.5394583e+00  3.3936653e+00  2.9001554e+01  2.9001198e+01
   3.2894442e+00 -1.5875316e+00  9.0569210e+00 -7.6022291e-01
   5.5141363e+00  2.7957358e+00  3.5612986e+00  8.0328922e+00
  -3.7986336e+00  9.2154026e-02  1.3225850e+01  2.9794626e+00
   4.5634112e-03]
 [ 4.5394583e+00  3.3936653e+00  2.9001554e+01  2.9001198e+01
   3.2894442e+00 -1.5875316e+00  9.0569210e+00 -7.6022291e-01
   5.5141363e+00  2.7957358e+00  3.5612986e+00  8.0328922e+00
  -3.7986336e+00  9.2154026e-02  1.3225850e+01  2.9794626e+00
   4.5634112e-03]]`
and 
![friends](https://user-images.githubusercontent.com/32239722/140267008-b24ebde3-66b3-431c-b9bb-31a1fbd36e9d.jpg)
tflite model output:
`[[ 26.30391     45.815998    15.318579    15.318455    25.36796
   41.83495     29.585167    45.42548     25.27378     46.95403
   23.45119     49.55304     22.601065    40.5007      32.286842
   48.044865     0.7468504 ]
 [ 78.23201     51.20295     19.179186    19.179142    78.84692
   47.8986      83.48271     50.48215     80.6107      52.646446
   78.44246     54.880447    72.91944     45.85292     83.785065
   51.694183     0.6747569 ]
 [ 53.54354     47.331875    19.37531     19.375237    50.628742
   43.143784    55.891808    45.867424    51.231808    47.359013
   50.78139     50.537304    49.22387     43.62208     60.94362
   48.629707     0.6197063 ]
 [101.9684      49.856655    19.639782    19.639744    98.39309
   46.63186    104.05909     46.658813   100.23142     49.016006
  100.64084     52.422737    96.56004     47.981262   109.495316
   47.874664     0.5907868 ]
 [ 43.294758    48.23123     18.912622    18.91256     41.17029
   45.106667    45.666157    46.91061     41.867565    48.94021
   41.34953     51.683       38.825493    43.775955    50.385445
   47.55902      0.57340574]]`
The last column means the face confidence, I know I can filter some boxes,  just out of curiosity，  does it have to be a fixed dimension output or it is some bug in tflite's nms

Codes I use for add some layers:
```
blazeface_tf_model = tf.keras.models.load_model(r"/content/blazeface_tf.h5")
class FaceDetetor(layers.Layer):
    def __init__(self):
        super(FaceDetetor, self).__init__()
        self.classifier = blazeface_tf_model


    def call(self, inputs):
        input_tensor = (inputs / 127.5) - 1
        temp_tensor = self.classifier(input_tensor)
        
        reshape_tensor = tf.reshape(temp_tensor, [-1, temp_tensor.shape[2]])
        final_boxes = tf.slice(reshape_tensor, [0, 0], [-1, 4])
        
        temp_boxex_1 = tf.slice(final_boxes, [0, 0], [-1, 2])  # 中心 y_x
        temp_boxex_2 = tf.slice(final_boxes, [0, 2], [-1, 2])  # w_h
        temp_boxex_2_1 = temp_boxex_2 / 2
        
        ts_sub1 = tf.subtract(temp_boxex_1, temp_boxex_2_1, name=None)
        temp_clip = tf.clip_by_value(ts_sub1, 0, 100000000)
        
        ts_add1 = tf.add(temp_boxex_1, temp_boxex_2_1, name=None)
        
        yx1_columns = tf.unstack(temp_clip, axis=-1)
        xy1_columns = tf.stack([yx1_columns[1], yx1_columns[0]], axis=-1)
        yx2_columns = tf.unstack(ts_add1, axis=-1)
        xy2_columns = tf.stack([yx2_columns[1], yx2_columns[0]], axis=-1)
        box_tlbr = tf.concat([xy1_columns, xy2_columns], 1)
        #### xywh_to_tlbr ####
        raw_scores = tf.slice(reshape_tensor, [0, temp_tensor.shape[2] - 1], [-1, 1])
        scores = tf.reshape(raw_scores, [-1])
        out_boxes = tf.image.non_max_suppression(box_tlbr, scores, max_output_size=5,
                                                 score_threshold=0.5, iou_threshold=0.3)
       
        rows = tf.gather(reshape_tensor, out_boxes, axis=0)
        final_boxes = tf.slice(rows, [0, 0], [-1, temp_tensor.shape[2] - 1])
        if len(final_boxes.shape) == 1:
            final_boxes = tf.expand_dims(final_boxes, axis=0)
        orig_points = final_boxes * 128
        final_scores = tf.gather(raw_scores, out_boxes, axis=0)
        final_result = tf.concat([orig_points, final_scores], 1)
        return final_result
max_output_size = 5
score_threshold = 0.75
iou_threshold = 0.5
inputs_0 = keras.Input(batch_shape=((1, 128, 128, 3)), dtype=tf.float32, name="input_images")
# inputs_1 = keras.Input(shape=(1), dtype=tf.int32, name="max_output_size")
# inputs_2 = keras.Input(shape=(1), dtype=tf.float32, name="score_threshold")
# inputs_3 = keras.Input(shape=(1), dtype=tf.float32, name="iou_threshold")
outputs = FaceDetetor()(inputs_0)

model_folder_path = r"/content/face_detector_inputs3"
model = keras.Model(inputs_0, outputs=outputs)
model.save(model_folder_path, save_format='tf')
print("saved model!")
```

Codes I use for savedmodel convert to tflite:
```
converter = tf.lite.TFLiteConverter.from_saved_model(model_folder_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
    ]
tflite_model = converter.convert()
output_tflite_path_float = r'/content/face_detector_float16.tflite'
with open(output_tflite_path_float, 'wb') as f:
    f.write(tflite_model)
```

**Standalone code to reproduce the issue** 
For more  details: [colab ](https://colab.research.google.com/drive/12fIvXNJvrtgeUvgfwVbUwISQdWStmStz?usp=sharing)

**Comment by tilakrayal** [comment]
@whalefa1I ,
On running the given code, I was facing different error. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/cd328e6d5a60e8148c4826f15aa36622/52935.ipynb).Please provide all the dependencies to reproduce the issue.Thanks!

**Comment by tilakrayal** [comment]
Also please refer this [issue](https://github.com/tensorflow/tensorflow/issues/41391) with the similar error.It helps.Thanks!
