### ISSUE TITLE
session config conflict with server_def_

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#52938]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): master
- Python version:3.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.1 (clang-1001.0.46.4)
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
```zsh: command not found: v1.12.1-54214-gb51e7cff1aa```

code:
```
config0 = tf.ConfigProto(intra_op_parallelism_threads=0)
config1 = tf.ConfigProto(intra_op_parallelism_threads=1)
server = tf.train.Server.create_local_server(config=config0)
sess0 = tf.Session(server.target, config=config0)
sess1 = tf.Session(server.target, config=config1)
```
**Describe the current behavior**
sess1 have config0
**Describe the expected behavior**
sess1 have config1

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
-     https://github.com/tensorflow/tensorflow/pull/52939

session config in server to session: https://github.com/tensorflow/tensorflow/issues/8982 
background:
1. We use two sessions to run two graphs in two thread.
2. two graph share a resource-mgr, because we hope save a checkpoint .

**Comment by sachinprasadhs** [comment]
Could you please fill the issue template https://github.com/tensorflow/tensorflow/issues/new/choose to expedite the process. Thanks
