### ISSUE TITLE
Build did NOT complete successfully

### ISSUE THREAD

**Issue by amirbehbahanian** [tensorflow/tensorflow#52947]
Hi,

I'm using python Python 3.6.8 on CentOS 7, my bazel version is bazel 3.1.0. Using "git checkout r2.4" and trying to make the C++ interface I get the following error:

`INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=237
INFO: Reading rc options for 'build' from /home/u211355/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/u211355/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/u211355/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3.6 --action_env PYTHON_LIB_PATH=/usr/lib/python3.6/site-packages --python_path=/usr/bin/python3.6 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/u211355/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/u211355/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/u211355/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/u211355/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/u211355/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/u211355/.cache/bazel/_bazel_u211355/4bc589a879d91108e775a9cd349c5c7c/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
INFO: Build options --action_env, --define, and --host_copt have changed, discarding analysis cache.
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow:libtensorflow_cc.so (211 packages loaded, 20042 targets configured).
INFO: Found 1 target...
ERROR: /home/u211355/.cache/bazel/_bazel_u211355/4bc589a879d91108e775a9cd349c5c7c/external/com_google_protobuf/BUILD:110:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): gcc failed: error executing command
  (cd /home/u211355/.cache/bazel/_bazel_u211355/4bc589a879d91108e775a9cd349c5c7c/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib \
    PATH=/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-7/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-8/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-9/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-10/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/home/u211355/miniconda3/condabin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/.local/bin:/home/u211355/bin:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -w -g0 '-std=c++14' -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/any_lite.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.o)
Execution platform: @local_execution_config_platform//:platform
gcc: error: unrecognized command line option '-std=c++14'
Target //tensorflow:libtensorflow_cc.so failed to build
ERROR: /home/u211355/tensorflow/tensorflow/BUILD:820:1 C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): gcc failed: error executing command
  (cd /home/u211355/.cache/bazel/_bazel_u211355/4bc589a879d91108e775a9cd349c5c7c/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib \
    PATH=/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-7/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-8/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-9/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/opt/sge/bin:/opt/sge/bin/lx-amd64:/opt/rh/devtoolset-10/root/usr/bin:/home/u211355/xcrysden-1.5.60-bin-semishared:/home/u211355/miniconda3/condabin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/.local/bin:/home/u211355/bin:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util:/home/u211355/xcrysden-1.5.60-bin-semishared/scripts:/home/u211355/xcrysden-1.5.60-bin-semishared/util \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -g0 -w -g0 '-std=c++14' -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/any_lite.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/any_lite.o)
Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 55.118s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
`
I would appreciate your help with this error. I have also tried different versions of GCC from 7-10 and that also didn't solve the error.

Thanks
Amir

**Comment by sushreebarsa** [comment]
@amirbehbahanian 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!

**Comment by amirbehbahanian** [comment]
I opened a build issue is that what you meant?

**Comment by sushreebarsa** [comment]
@amirbehbahanian Could you please try with the latest stable TF version `2.6.0` and refer to the [build from source](https://www.tensorflow.org/install/source) .Please let us know if it helps ?Thanks!
