### ISSUE TITLE
TensorFlow 2.4.1  data.Dataset.from_generator  Report Error in Distributed Training

### ISSUE THREAD

**Issue by xingkong1994** [tensorflow/tensorflow#52959]
I use TF2.4.1 API tf.data.Dataset.from_generator in ps-worker distributed training, but it report error, the message is "Cannot assign a device for operation PyFunc: {{node PyFunc}} was explicitly assigned to /job:localhost/replica:0/task:0 but available devices are [ /job:worker/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device."  but my codes run in TF 2.2.0,  the training workers fine.    

my demo code test.py is :
```python
import tensorflow.compat.v1 as tf
import time
import random
from tensorflow.python.framework import ops
import logging
import numpy as np
tf.disable_v2_behavior()

tf.app.flags.DEFINE_string("ps_hosts", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_string("worker_hosts", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_string("job_name", "worker", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")
tf.app.flags.DEFINE_string("buckets", None, "oss buckets")
tf.app.flags.DEFINE_integer("interval", 60, "interval")
tf.app.flags.DEFINE_string("protocol", "grpc", "interval")

FLAGS = tf.app.flags.FLAGS

def data_generator():
    dataset = np.array(range(1000))
    for d in dataset:
        yield d
def train(task_index, cluster, is_chief, target, buckets):
  available_worker_device = "/job:worker/task:%d" % (task_index)
  with tf.device(
      tf.train.replica_device_setter(worker_device=available_worker_device,
                                     cluster=cluster)):
    dataset = tf.data.Dataset.from_generator(data_generator, (tf.int32), (tf.TensorShape([])))
    dataset = dataset.repeat(3)
    dataset = dataset.batch(4)
    iterator = dataset.make_one_shot_iterator()
    one_element = iterator.get_next()

    local_step = 1
    config = tf.ConfigProto(inter_op_parallelism_threads=7)
    with tf.train.MonitoredTrainingSession(master=target,
                                           is_chief=is_chief,
                                           hooks=[],
                                           save_checkpoint_secs=60,
                                           checkpoint_dir=buckets,
                                           config=config) as mon_sess:
      while True:
        l = mon_sess.run(one_element)
        local_step += 1
        if local_step % 100 == 0:
          logging.info(l)


def main(argv):
  print("job name = %s" % FLAGS.job_name)
  print("task index = %d" % FLAGS.task_index)
  is_chief = FLAGS.task_index == 0

  ps_spec = FLAGS.ps_hosts.split(",")
  worker_spec = FLAGS.worker_hosts.split(",")
  cluster = tf.train.ClusterSpec({"ps": ps_spec, "worker": worker_spec})

  config = tf.ConfigProto(inter_op_parallelism_threads=8)
  server = tf.distribute.Server(cluster,
                                job_name=FLAGS.job_name,
                                protocol=FLAGS.protocol,
                                task_index=FLAGS.task_index,
                                config=config)

  # join the ps server
  if FLAGS.job_name == "ps":
    server.join()
  # start the training
  print("start trainig")
  print(FLAGS.buckets)
  train(task_index=FLAGS.task_index,
        cluster=cluster,
        is_chief=is_chief,
        target=server.target,
        buckets=FLAGS.buckets)
if __name__ == "__main__":
  tf.app.run()
```

my start command is below:
python test.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100 --task_index=0 --job_name=ps
python test.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100 --task_index=0 --job_name=worker

could you please tell me what's wrong with my code? my code works fine in TF2.2.0,  but error in TF2.4.1。
hope for your answer, thanks!

**Comment by SuyunCDN** [comment]
GREETINGS IT SPECIALIST! SUYUN CDN IS HIRING NOW! 

Company name: SuyunCDN

Title of position: Python Developer

Position type: Full Time, Part Time, or Contractual

Pay range: $800 - $2000


Location: Remote

Preferred Qualifications: 
	
●	Graduated in any IT related course
●	Proficient in English and Mandarin Language
●	Proficient in Python Coding

Description of responsibilities: 

●	Writing and testing code, debugging programs and integrating applications with third-party web services

●	Develop back-end components to improve responsiveness and overall performance
●	Integrate user-facing elements into applications
●	Test and debug programs
●	Improve functionality of existing systems
●	Implement security and data protection solutions
●	Assess and prioritize feature requests
●	Coordinate with internal teams to understand user requirements and provide technical solutions


Required experience: 
●	Work experience as a Python Developer

Required skills: 
●	Proficient with Django Python framework
●	Proficient with DevOps and Ansible
●	Extensive Knowledge on object-relational mapping (ORM)
●	Problem Solving Skill- Advance
●	Communication Skill - Advance
●	Highly Resourceful
●	Team-oriented personality


For information on SuyunCDN, including more information on our staff and our company culture, you may check our website at https://www.suyuncdn.com.

If interested, email your resume to suyuncdnclaudie@gmail.com
with the subject line of the job, you're applying for.
Check out our FB page for more info on available jobs we have
Suyuncdn

**Comment by sushreebarsa** [comment]
@xingkong1994 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by xingkong1994** [comment]
> @xingkong1994 In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), Thanks!

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8.3
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: no cuda, only use cpu
- GPU model and memory:

**Describe the current behavior**
I use TF2.4.1 API tf.data.Dataset.from_generator in ps-worker distributed training, but it report error, the message is "Cannot assign a device for operation PyFunc: {{node PyFunc}} was explicitly assigned to /job:localhost/replica:0/task:0 but available devices are [ /job:worker/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device." but my codes run in TF 2.2.0, the training workers fine.

**Describe the expected behavior**
tf.data.Dataset.from_generator works fine in tf2.4.1

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
my demo code test.py is :
```python
import tensorflow.compat.v1 as tf
import time
import random
from tensorflow.python.framework import ops
import logging
import numpy as np
tf.disable_v2_behavior()

tf.app.flags.DEFINE_string("ps_hosts", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_string("worker_hosts", "", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_string("job_name", "worker", "One of 'ps', 'worker'")
tf.app.flags.DEFINE_integer("task_index", 0, "Index of task within the job")
tf.app.flags.DEFINE_string("buckets", None, "oss buckets")
tf.app.flags.DEFINE_integer("interval", 60, "interval")
tf.app.flags.DEFINE_string("protocol", "grpc", "interval")

FLAGS = tf.app.flags.FLAGS

def data_generator():
    dataset = np.array(range(1000))
    for d in dataset:
        yield d
def train(task_index, cluster, is_chief, target, buckets):
  available_worker_device = "/job:worker/task:%d" % (task_index)
  with tf.device(
      tf.train.replica_device_setter(worker_device=available_worker_device,
                                     cluster=cluster)):
    dataset = tf.data.Dataset.from_generator(data_generator, (tf.int32), (tf.TensorShape([])))
    dataset = dataset.repeat(3)
    dataset = dataset.batch(4)
    iterator = dataset.make_one_shot_iterator()
    one_element = iterator.get_next()

    local_step = 1
    config = tf.ConfigProto(inter_op_parallelism_threads=7)
    with tf.train.MonitoredTrainingSession(master=target,
                                           is_chief=is_chief,
                                           hooks=[],
                                           save_checkpoint_secs=60,
                                           checkpoint_dir=buckets,
                                           config=config) as mon_sess:
      while True:
        l = mon_sess.run(one_element)
        local_step += 1
        if local_step % 100 == 0:
          logging.info(l)


def main(argv):
  print("job name = %s" % FLAGS.job_name)
  print("task index = %d" % FLAGS.task_index)
  is_chief = FLAGS.task_index == 0

  ps_spec = FLAGS.ps_hosts.split(",")
  worker_spec = FLAGS.worker_hosts.split(",")
  cluster = tf.train.ClusterSpec({"ps": ps_spec, "worker": worker_spec})

  config = tf.ConfigProto(inter_op_parallelism_threads=8)
  server = tf.distribute.Server(cluster,
                                job_name=FLAGS.job_name,
                                protocol=FLAGS.protocol,
                                task_index=FLAGS.task_index,
                                config=config)

  # join the ps server
  if FLAGS.job_name == "ps":
    server.join()
  # start the training
  print("start trainig")
  print(FLAGS.buckets)
  train(task_index=FLAGS.task_index,
        cluster=cluster,
        is_chief=is_chief,
        target=server.target,
        buckets=FLAGS.buckets)
if __name__ == "__main__":
  tf.app.run()
```
my start command is below:
```python
python test.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100 --task_index=0 --job_name=ps
python test.py --ps_hosts=127.0.0.1:9200 --worker_hosts=127.0.0.1:9100 --task_index=0 --job_name=worker
```

**Comment by sushreebarsa** [comment]
@xingkong1994 Could you please try on the latest version of `TF 2.7.0` and let us know if it is still an issue ?  Thanks!

**Comment by hangweiqiang-uestc** [comment]
same problem on tf2.6.5 and tf2.5.2, any solutions?

**Comment by sushreebarsa** [comment]
@hangweiqiang-uestc Could you please raise a new ticket for your issue as it is difficult for us to track in closed one?
Thank you!
