### ISSUE TITLE
[Help] How to feed the RaggedTensor as inputs in Graph execution ?

### ISSUE THREAD

**Issue by wawltor** [tensorflow/tensorflow#52958]

**Comment by SuyunCDN** [comment]
GREETINGS IT SPECIALIST! SUYUN CDN IS HIRING NOW! 

Company name: SuyunCDN

Title of position: Python Developer

Position type: Full Time, Part Time, or Contractual

Pay range: $800 - $2000


Location: Remote

Preferred Qualifications: 
	
●	Graduated in any IT related course
●	Proficient in English and Mandarin Language
●	Proficient in Python Coding

Description of responsibilities: 

●	Writing and testing code, debugging programs and integrating applications with third-party web services

●	Develop back-end components to improve responsiveness and overall performance
●	Integrate user-facing elements into applications
●	Test and debug programs
●	Improve functionality of existing systems
●	Implement security and data protection solutions
●	Assess and prioritize feature requests
●	Coordinate with internal teams to understand user requirements and provide technical solutions


Required experience: 
●	Work experience as a Python Developer

Required skills: 
●	Proficient with Django Python framework
●	Proficient with DevOps and Ansible
●	Extensive Knowledge on object-relational mapping (ORM)
●	Problem Solving Skill- Advance
●	Communication Skill - Advance
●	Highly Resourceful
●	Team-oriented personality


For information on SuyunCDN, including more information on our staff and our company culture, you may check our website at https://www.suyuncdn.com.

If interested, email your resume to suyuncdnclaudie@gmail.com
with the subject line of the job, you're applying for.
Check out our FB page for more info on available jobs we have
Suyuncdn

**Comment by sachinprasadhs** [comment]
Could you please fill the issue template here https://github.com/tensorflow/tensorflow/issues/new/choose to understand your problem. Thanks

**Comment by sachinprasadhs** [comment]
Closing this since no information is available. Thanks.
