### ISSUE TITLE
TFLite int8 quantization failure in TensorFlow 2.7.0

### ISSUE THREAD

**Issue by zldrobit** [tensorflow/tensorflow#52954]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): v2.7.0

### 2. Code

The MWE is provided in the following colab notebook:
https://colab.research.google.com/drive/1K-Hwq6LEfjFr-4dSLEI4dhQd6pCR0K-F?usp=sharing

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The log is attached as below:
```
INFO:tensorflow:Assets written to: /tmp/tmp0cb_yd9c/assets
INFO:tensorflow:Assets written to: /tmp/tmp0cb_yd9c/assets
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-674e2748ac1c> in <module>()
     16 converter.inference_output_type = tf.uint8  # or tf.int8
     17 converter.experimental_new_quantizer = False
---> 18 tflite_model = converter.convert()

10 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/schema_py_generated.py in Pack(self, builder)
   5704             for i in reversed(range(len(self.operatorCodes))):
   5705                 builder.PrependUOffsetTRelative(operatorCodeslist[i])
-> 5706             operatorCodes = builder.EndVector(len(self.operatorCodes))
   5707         if self.subgraphs is not None:
   5708             subgraphslist = []

TypeError: EndVector() takes 1 positional argument but 2 were given
```

This error only occurs with `flabbuffers==2.0`. I could convert an int8 quantization model with `tensorflow==2.7.0` and `flatbuffers==1.12`. This problem is related to the PR https://github.com/tensorflow/tensorflow/pull/51504. In the 
 issue https://github.com/google/flatbuffers/issues/6858, it is discussed that the number of `EndVector()`'s arguments changed from two to one with the flatbuffers version changing from `1.12` to `2.0`.

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue . It is replicating in TF [2.6](https://colab.sandbox.google.com/gist/mohantym/b4faca62759831aafe849e56357c448c/tf2-7-0-fb-2-0-tfl-int8-quant.ipynb#scrollTo=CBaIlu0d7JmG),[2.7](https://colab.sandbox.google.com/gist/mohantym/426183f718608c162ca345ca1608489d/tf2-7-0-fb-2-0-tfl-int8-quant.ipynb) and [nightly](https://colab.sandbox.google.com/gist/mohantym/ddbc510fd21f2ca7b564dbdc44a6c07c/tf2-7-0-fb-2-0-tfl-int8-quant.ipynb#scrollTo=wUAXNyAnKn-c) and related to PR #51504

**Comment by Saduf2019** [comment]
@zldrobit 
Could you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/51590#issuecomment-912614740) and let us know if it [helps](https://github.com/tensorflow/tensorflow/issues/51590#issuecomment-915458143).

**Comment by zldrobit** [comment]
@Saduf2019 The link actually helps, and downgrading flatbuffers fixes the problem.

**Comment by Saduf2019** [comment]
@zldrobit 
Thank you for your update, Kindly move this to closed status.
