### ISSUE TITLE
"tf.print()" breaks the tensor value order in OrderedDict

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#52952]
**System information**
- OS Platform and Distribution: macOS Big Sur 11.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version: The issue occurs in both TF v1.15.2 and TF v2.7.
- Python version: Python 3.6.5 with TF v1.15.2, or Python 3.8.3 with TF v2.7

**Issue Description & Repro Code**

I am using `tf.print()` to log the intermediate values evaluated from a OrderedDict containing the string-tensor pair, but the evaluation result shows that the tensor order is messed up. The following python script `try_tf_print.py` is an example.

```
from collections import OrderedDict

import tensorflow as tf

tf.compat.v1.disable_eager_execution()


def build_tf_print_ops_with_dict() -> None:
    a = tf.compat.v1.placeholder(dtype=tf.float32, shape=[None, 1])
    b = tf.compat.v1.placeholder(dtype=tf.float32, shape=[None, 3])
    c = tf.compat.v1.placeholder(dtype=tf.float32, shape=[None, 2])
    d = tf.compat.v1.placeholder(dtype=tf.float32, shape=[None, 5])
    p_dict = OrderedDict([
        ("foo", a),
        ("bar", b),
        ("baz", c),
        ("qux", d)
    ])
    tf_print_ops = tf.print(p_dict)
    sess = tf.compat.v1.Session()
    sess.run(tf_print_ops, feed_dict={
        a: [[1]],
        b: [[2, 4, 6]],
        c: [[0.2, 0.2]],
        d: [[100, 200, 300, 400, 500]]
    })


build_tf_print_ops_with_dict()
```
I'd expect tf.print() evaluation result to be as `OrderedDict([('foo', [[1]]), ('bar', [[2 4 6]]), ('baz', [[0.2 0.2]]), ('qux', [[100 200 300 400 500]])])`, while what I got was `OrderedDict([('foo', [[2 4 6]]), ('bar', [[0.2 0.2]]), ('baz', [[1]]), ('qux', [[100 200 300 400 500]])])`, in which the tensor value order is broken -- It is supposed to follow the OrderedDict order `("foo", a), ("bar", b), ("baz", c), ("qux", d)`, but the order it gets is `("foo", b), ("bar", c), ("baz": a), ("qux", d)`. The issue could be 100% reproduced by running above script `try_tf_print.py`.

**Comment by sanatmpa1** [comment]
I am able to reproduce the issue in colab with `2.6.0`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/d22ff38bff24c7313182ec3c623c60e2/52952.ipynb#scrollTo=yNgtEmUglESQ)

**Comment by sanatmpa1** [comment]
@RuofanKong,

I've found [this](https://github.com/tensorflow/community/blob/master/rfcs/20180824-tf-print-v2.md#supported-input-types) documentation, which states that 
> Tensors nested inside of python sets will not be properly and their values will not be shown/formatted when the tf.print kernels run.

Can you take a look on it? Thanks!

**Comment by RuofanKong** [comment]
Thank you @sanatmpa1 for the comment. I just looked at the doc that you shared, and the following is the feedback from a user point of view.

1.  The note stated in the documentation is critical for users to be aware of, while I don't see it is being included in the TF official public doc (https://www.tensorflow.org/api_docs/python/tf/print)
2. Regardless of 1, per my experience as a user, it is a very common use case to have the struct tensor to work with `tf.print()`, and not supporting it is unreasonable to me. Plus, the official doc here has an example that it should work with a tensor embedded in the python dict. see here (https://www.tensorflow.org/api_docs/python/tf/print#example)

Hope this makes sense.

**Comment by sanatmpa1** [comment]
Thanks for the clarification. I've found a similar [issue](https://github.com/tensorflow/tensorflow/issues/51532) here which also discusses about the similar problem.

**Comment by RuofanKong** [comment]
Any updates on it?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
