### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto.

### ISSUE THREAD

**Issue by Crispisu** [tensorflow/tensorflow#52957]
Hi I am still getting the 'TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto.' even after applying the fix mentioned previously.
Any suggestions?

**Comment by mohantym** [comment]
Hi @Crispisu! Could you please fill the template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) as it helps expedite the issue.

**Comment by Crispisu** [comment]
Hi @mohantym ! Thank you for this. In the meantime I have managed to solve this as per instructions You provided to previous similar issues. The problem was related to my laptop as I am using an M1 chip which causes multiple issues for tensorflow. 
Can you please close this one?

**Comment by mohantym** [comment]
Ok @Crispisu! Thanks for confirming the same. Attaching similar issue for reference. [link1](https://github.com/tensorflow/tensorflow/issues/50545),[link2](https://stackoverflow.com/questions/67570696/typeerror-parameter-to-mergefrom-must-be-instance-of-same-class-expected-ten). Please close this issue once it has been resolved.
