### ISSUE TITLE
Python import error, undefined symbol: _Z14tf_git_versionv

### ISSUE THREAD

**Issue by joshsuihn** [tensorflow/tensorflow#5295]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

### Environment info
Operating System: Ubuntu16.04

Installed version of CUDA and cuDNN: 8.0 and 5

Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: _Z14tf_git_versionv

I'm getting this error above with r0.10, can you please give me some insights or solutions to this? 

Thanks

**Comment by drpngx** [comment]
Can you attach the copy of:

```
nm /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
```

Did you build this yourself or did you download a binary distribution?

**Comment by drpngx** [comment]
I am suspecting that this is an older version of the so file, and since we introduced the `tf.GIT_VERSION` later, you have the new python files loading the old shared object.

**Comment by joshsuihn** [comment]
I built this myself with this commit: 
git clone https://github.com/tensorflow/tensorflow
git checkout a5f8f42cb29d890650c4ca5fac6654884856a8e1

Yes, TF version is r0.10.

**Comment by drpngx** [comment]
Can you check the dates on the so file and the python file? Are you using virtualenv?

**Comment by joshsuihn** [comment]
$ ls -alh /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
-rwxr-xr-x 1 root staff 129M Oct 31 04:05 /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so

$ ls -al /usr/bin/python
lrwxrwxrwx 1 root root 9 Dec 10  2015 /usr/bin/python -> python2.7

ls -al /usr/bin/python2.7
-rwxr-xr-x 1 root root 3111304 Jul  2 20:31 /usr/bin/python2.7

Actually, I just reproduced build procedures that I've already been through before.

**Comment by drpngx** [comment]
OK, it looks recent enough. `nm` output, please.

**Comment by joshsuihn** [comment]
The nm output is too big (24 mb txt file) Is there any specific lines you want to check?

**Comment by joshsuihn** [comment]
Is this related to gcc version ? or c++ mingling?

**Comment by drpngx** [comment]
Yes, it shows as U, which means undefined. I'd need to check later, but I'm guessing that the script failed to define the symbol. Could you bazel clean, to be sure? See what happens to the `tf_version_info_generate`. It's supposed to put something in `bazel-genfiles/tensorflow/util/version_info.cc`. That should have the git version in there. If it's there, check the lib file and so on.

**Comment by joshsuihn** [comment]
Ok, Thanks, I'm rebuilding after bazel clean now. Let me check the path and the file then will let you know.

**Comment by joshsuihn** [comment]
I can't find version_info.cc  file, neither util dir. :( 
$ ls ./bazel-genfiles/tensorflow/
contrib  core  models  python

**Comment by drpngx** [comment]
Do you have this?

```
bazel-bin/tensorflow/core/_objs/version_lib/tensorflow/core/util/version_info.o
```

What does 

```
nm bazel-bin/tensorflow/libtensorflow.so|grep _git_version
```

say?

**Comment by vrv** [comment]
I'd also try to upgrade to 0.11 -- I believe there might have been some git_version issues in 0.10 that have been long since fixed.

**Comment by joshsuihn** [comment]
I built tensorflow r0.10 on aarch64 with my own patch. In the patch,
I had to uncomment ":version_lib" in tensorflow/core/BUILD due to "duplicate version" error.
With the same version and commit, 2 - 3 weeks later, I tried building again, but I had the issue mentioned above. I don't still know why, but anyway,  it turns out ":version_lib" is needed at this moment, again.

Thank you for your help!

**Comment by drpngx** [comment]
@jart FYI
