### ISSUE TITLE
Missing tensorflow 2.6.2 Windows wheels

### ISSUE THREAD

**Issue by jponf** [tensorflow/tensorflow#52953]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow version: 2.6.2
- Python version: 3.8
- Installed using: poetry (pip)

After running poetry (1.1.11) on a project, the dependency resolution picks tensorflow version 2.6.2 but when it tries to install the package it fails because tensorflow 2.6.2 is missing the Windows wheels (https://pypi.org/project/tensorflow/2.6.2/#files).

Windows wheels are available for versions 2.6.0 (https://pypi.org/project/tensorflow/2.6.0/#files), 2.6.1 (https://pypi.org/project/tensorflow/2.6.1/#files) and 2.7.0 (https://pypi.org/project/tensorflow/2.7.0/#files).

**Comment by sushreebarsa** [comment]
@jponf In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!

**Comment by jponf** [comment]
**System information**

- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.6.2
- Python version: 3.8
- Installed using: poetry (pip)

**Describe the problem**

After running poetry (1.1.11) on a project, the dependency resolution picks tensorflow version 2.6.2 but when it tries to install the package it fails because tensorflow 2.6.2 is missing the Windows wheels (https://pypi.org/project/tensorflow/2.6.2/#files).

Windows wheels are available for versions 2.6.0 (https://pypi.org/project/tensorflow/2.6.0/#files), 2.6.1 (https://pypi.org/project/tensorflow/2.6.1/#files) and 2.7.0 (https://pypi.org/project/tensorflow/2.7.0/#files). 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

For the sake of simplicity, I provide a simpler sequence of steps that generates the same error.

Using Python 3.8.5 installed with conda on Windows 10.

```console
python -m venv test
.\test\Scripts\activate
pip3 install tensorflow==2.6.2
```

**Any other info / logs**

Trying to install another version, for example 2.6.1 or 2.7.0 works as expected.

```console
python -m venv test
.\test\Scripts\activate
pip3 install tensorflow==2.6.1
```

```console
python -m venv test
.\test\Scripts\activate
pip3 install tensorflow==2.7.0
```

**Comment by JMeyerEngineering** [comment]
Please tag me when a solution is proposed.  I ran into the same issue today!

**Comment by a42664** [comment]
Me too. Waiting for the windows wheels on pip.

**Comment by mihaimaruseac** [comment]
The Windows builds are extremely slow (18 hours and more) and very flaky. Hopefully we'd have all wheels by tomorrow.

**Comment by mihaimaruseac** [comment]
> [19,687 / 19,942] Compiling tensorflow/core/kernels/matmul_op_real.cc; 13710s local, remote-cache ... (63 actions running)

**Comment by mihaimaruseac** [comment]
Still delayed, two more jobs restarted :(

**Comment by jponf** [comment]
I never though it was so complicated to create the windows wheels, thanks @mihaimaruseac for keeping us posted :)

**Comment by mihaimaruseac** [comment]
One more build left to do, sorry for all these delays :(

**Comment by JMeyerEngineering** [comment]
@mihaimaruseac   Thanks for the status updates!

**Comment by mihaimaruseac** [comment]
The windows wheels should now be updated. Apologies for the long delay

> [20,917 / 21,397] Compiling tensorflow/core/kernels/matmul_op_real.cc; 30162s local, remote-cache ... (4 actions running)

**Comment by chaobai** [comment]
@mihaimaruseac works now for me. Thanks for updating.

**Comment by mihaimaruseac** [comment]
Thanks for confirming. Closing the issue then.
