### ISSUE TITLE
Change the input layer from a saved TF model

### ISSUE THREAD

**Issue by AlexisPapaioannou** [tensorflow/tensorflow#52956]
Is there any way to load a Tensorflow model, change the input layer and save again the new model? (I would like to convert a model from NHWC vs NCHW)

**Comment by sushreebarsa** [comment]
@AlexisPapaioannou 
Could you please refer to [Save and load model ](https://www.tensorflow.org/tutorials/keras/save_and_load) , for any further queries you may open this issue in [TF discussion forum ](https://discuss.tensorflow.org/) as there is a wider community to respond. Thank you!

**Comment by AlexisPapaioannou** [comment]
Thanks, @sushreebarsa !
