### ISSUE TITLE
<unknown> shape of Tensor, as_list() is not defined on a unknown TensorShape

### ISSUE THREAD

**Issue by FernandoDorado** [tensorflow/tensorflow#52965]
Good afternoon, 

I am trying to implement a pipeline using TFX and Tensorflow. For this, I use 3 accelerometer measurements to predict the activity that is being performed at that moment (6 classes). To do the processing, I have to transform the dataset to sequences, and for that I make use of .windows function. The code used to perform this processing is the following: 

```python
HISTORY_SIZE = 80
BATCH_SIZE = 32
SHIFT = 40

def parse_function(example_proto):
    '''Parse the values from tf examples'''
    feature_spec = tf_transform_output.transformed_feature_spec()
    features = tf.io.parse_single_example(example_proto, feature_spec)
    values = list(features.values())
    values = [float(_fill_in_missing(value)) for value in values]    
    features = tf.stack(values, axis=0)
    return features

def add_mode(features):
    '''Calculate mode of activity for the current history size of elements'''
    # Removes dimensions of size 1 from the shape of a tensor.
    features = tf.squeeze(features)
    
    # Finds unique elements in a 1-D tensor.
        # This operation returns a tensor y containing all of the unique elements of x sorted in the same order that they occur in x. 
        # This operation also returns a tensor idx the same size as x that contains the index of each value of x in the unique output y. 
        # Finally, it returns a third tensor count that contains the count of each element of y in x
    unique, idx, count = tf.unique_with_counts(features[:,0])
    
    # Computes tf.math.maximum of elements across dimensions of a tensor.
    max_occurrences = tf.reduce_max(count)
    
    # Returns the truth value of (x == y) element-wise.
    max_cond = tf.equal(count, max_occurrences)
    
    # Gather slices from params axis axis according to indice
    max_numbers = tf.squeeze(tf.gather(unique, tf.where(max_cond)))

    #Features (X) are all features except activity (x-acc, y-acc, z-acc)
    #Target(Y) is the mode of activity values of all rows in this window
    return (features[:,1:], max_numbers)

def get_dataset(path):
    '''Get the dataset and group them into windows'''
    dataset = tf.data.TFRecordDataset(path, compression_type="GZIP")
    dataset = dataset.map(parse_function)
    dataset = dataset.window(HISTORY_SIZE, shift=SHIFT, drop_remainder=True)dataset
    dataset = dataset.flat_map(lambda window: window.batch(HISTORY_SIZE))
    dataset = dataset.map(add_mode)
    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.repeat()
    return dataset

def _fill_in_missing(x):
    """Replace missing values in a SparseTensor.
    Fills in missing values of `x` with '' or 0, and converts to a dense tensor.
    Args:
    x: A `SparseTensor` of rank 2.  Its dense shape should have size at most 1
      in the second dimension.
    Returns:
    A rank 1 tensor where missing values of `x` have been filled in.
    """
    default_value = '' if x.dtype == tf.string else 0
    # Todo fix
    return x`
```

Once this is done, I get the following tensors as outputs: 
Features (x-acc, y-acc, z-acc):

(32, 80, 3)
tf.Tensor(
[[[0.6224036  0.77866393 0.526603  ]
  [0.61964923 0.7690456  0.5003369 ]
  [0.48020944 0.96107006 0.5791352 ]
  ...
  [0.5549216  0.89545894 0.5957243 ]
  [0.63135535 0.85801584 0.6734857 ]
  [0.5490686  0.50144786 0.5694582 ]]

 [[0.2963554  0.9882078  0.5528691 ]
  [0.41926903 0.38533998 0.41773698]
  [0.49363694 0.79515266 0.30230445]
  ...
  [0.57041496 0.9882078  0.69595015]
  [0.5394283  0.3602634  0.43259805]
  [0.5752351  0.9294669  0.63961625]]

 [[0.57213646 0.67526615 0.5044842 ]
  [0.615862   0.41144708 0.4481503 ]
  [0.47814363 0.30220947 0.30403247]
  ...
  [0.33112925 0.9514518  0.3537998 ]
  [0.6468486  0.7594272  0.6831627 ]
  [0.48124233 0.33999607 0.27119985]]

 ...

 [[0.5742022  0.7168314  0.50724906]
  [0.61000896 0.754618   0.4702691 ]
  [0.5122289  0.83843553 0.51519793]
  ...
  [0.5294437  0.6666783  0.5093227 ]
  [0.5683492  0.743969   0.48201975]
  [0.5036216  0.6886632  0.4954984 ]]

 [[0.505343   0.84427524 0.53351516]
  [0.505343   0.6299222  0.51899964]
  [0.5294437  0.9236271  0.6054013 ]
  ...
  [0.5810881  0.7515263  0.645146  ]
  [0.5645619  0.8047711  0.52003646]
  [0.563529   0.837405   0.5003369 ]]

 [[0.6175835  0.8944283  0.5587444 ]
  [0.50431013 0.84324473 0.5238381 ]
  [0.5101631  0.7343506  0.516926  ]
  ...
  [0.54700285 0.76114476 0.534552  ]
  [0.55285585 0.6879761  0.50241053]
  [0.49466982 0.6886632  0.5093227 ]]], shape=(32, 80, 3), dtype=float32)

Target (activity):

tf.Tensor(
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2.
 2. 2. 2. 2. 2. 2. 2. 2.], shape=(32,), dtype=float32)
(32,)

When I want to get the information from this tensor, I get the following result: <RepeatDataset shapes: (< unknown>, < unknown>), types: (tf.float32, tf.float32)>

If I want to train a simple model using these sequences, I get the following error, and I don't know how to fix it: ValueError: as_list() is not defined on an unknown TensorShape.

The code of the model is below: 
```python
model = Sequential()
model.add(LSTM(units=200, input_shape=(HISTORY_SIZE,3),name="LSTM_1"))
model.add(Dropout(0.15))
model.add(Dense(units=20, activation='relu',name="DENSE_1"))
model.add(Dropout(0.15))
model.add(Dense(units=10, activation='relu'))
model.add(Dense(6, activation='softmax',name="OUTPUT"))
adam = Adam(lr = 0.001, beta_1 = 0.9, beta_2 = 0.999, epsilon = 1e-08, decay = 0.0)
model.compile(loss= 'CategoricalCrossentropy' , optimizer=adam, metrics=['accuracy']) #, weighted_metrics=METRICS)
model.fit(train_dataset, epochs=500, steps_per_epoch=20)`
```

Is there any way to solve it, I have seen some solution in the case of images, but not in the case of sequences. 

Versions: 
tfx-bsl==1.3.0
tensorflow-model-analysis==0.34.1
tensorflow-data-validation==1.3.0
tfx==1.3.2
tensorflow-metadata==1.2.0
ml-metadata==1.3.0
tensorflow-transform==1.3.0
tensorflow==2.6.2
pyarrow==2.0.0
apache-beam==2.32.0
tensorflow-serving-api==2.6.0
tensorflow-estimator==2.6.0

**Comment by sachinprasadhs** [comment]
Could you please refer the answer [here](https://stackoverflow.com/questions/67573468/) and let me know if this helps, Thanks!

**Comment by FernandoDorado** [comment]
This problem seems to have solved my doubt. I have other derived errors, but they will be in other issues.
