### ISSUE TITLE
Need clarification and assistance on this one (Friday with Leanne)

### ISSUE THREAD

**Issue by jessecantu** [tensorflow/tensorflow#52975]
Need clarification and assistance on this one (Friday with Leanne)

_Originally posted by @ZCorso in https://github.com/WorldEES/Q/issues/5#issuecomment-351091481_

__Originally posted by @jessecantu in https://github.com/jessecantu/overriddes/issues/1__

**Comment by tilakrayal** [comment]
@jessecantu ,
 In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.
