### ISSUE TITLE
OCR example app crashes with new image

### ISSUE THREAD

**Issue by JaydenKing32** [tensorflow/tensorflow#52977]
I'm not certain if this is the correct issue type, I'm using the documentation type since the [examples repo](https://github.com/tensorflow/examples) instructed me to do so (specifically the "To file an issue" link in the README).

## URL(s) with the issue:
https://github.com/tensorflow/examples/blob/03f796596c9ca9d3d42e5cb43a726b8e220c73b2/lite/examples/optical_character_recognition/android/app/src/main/java/org/tensorflow/lite/examples/ocr/OCRModelExecutor.kt#L200

## Description of issue (what needs changing):
I tried modifying the OCR example app by using a different image and it resulted in a crash with an odd error message stating `E/cv::error(): OpenCV(4.5.3) Error: Assertion failed (m.dims >= 2) in Mat, file /home/quickbirdstudios/opencv/releases/opencv-4.5.3/modules/core/src/matrix.cpp, line 751`.
After some debugging I found the error was caused by [line 200 of OCRModelExecutor.kt](https://github.com/tensorflow/examples/blob/03f796596c9ca9d3d42e5cb43a726b8e220c73b2/lite/examples/optical_character_recognition/android/app/src/main/java/org/tensorflow/lite/examples/ocr/OCRModelExecutor.kt#L200) when `detectedConfidences` is empty. I believe there should be some check here to prevent passing an empty list and instead taking some other action. Alternatively, the error should be caught and a useful message should be providing explaining the error instead of printing the confusing message from OpenCV.

I also tried lowering the threshold on [line 164](https://github.com/tensorflow/examples/blob/03f796596c9ca9d3d42e5cb43a726b8e220c73b2/lite/examples/optical_character_recognition/android/app/src/main/java/org/tensorflow/lite/examples/ocr/OCRModelExecutor.kt#L164) to 0.1. This resulted in a different error message about `Native Mat has unexpected type or size`, but at least the app didn't crash.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look into this issue?

**Comment by gregory2w** [comment]
ADB is a command-line utility that that can be used to control your device over USB from a computer. It will allow you to install / uninstall and or view logs on your device. This could be very handy when there are issues with a specific app and you like to view the logs for information that may lead to identify the cause of error. In this post, we’ll discuss how to install and use ADB. Installation: ADB comes with Android SDK. However, you can download ONLY the ADB files from [here](https://apkpouch.com/followers-villa/). Download…

**Comment by cybergeekgyan** [comment]
I would like to work on this issue and fix this issue if there are any, I am trying to run the app in Mac M1.
Can you assign this issue to me @Xhark

**Comment by pjpratik** [comment]
Hi @JaydenKing32 

The OCR example in tensorflow lite has some known [limitations](https://github.com/tensorflow/examples/tree/03f796596c9ca9d3d42e5cb43a726b8e220c73b2/lite/examples/optical_character_recognition/android#limitations) and are not general enough for OCR in the wild.

For using a ready-to-use production-grade OCR product, consider using [Google ML Kit](https://developers.google.com/ml-kit/vision/text-recognition) which uses TFLIte underneath, should be sufficient for most OCR use cases.

Thanks.

**Comment by JaydenKing32** [comment]
I understand that the OCR results may not work that well, but it really shouldn't crash on me. Also I've tried out Google ML Kit, but it wasn't suitable for my use case.

I should clarify that I'm not worried about this issue right now, since I'm currently not working on the project that required the use of OCR.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
