### ISSUE TITLE
TFLite static library generated is not working

### ISSUE THREAD

**Issue by bhpatray** [tensorflow/tensorflow#52979]
The generated static library through CMake sources as per tflite documentation is not working.

**System information**
- Debian 10 (e.g., Linux Ubuntu 16.04):
- TensorFlow Lite installed from CMake (source or binary): Source
- TensorFlow version 2.4.1

**Describe the current behavior**
Currently, the static library when generated through the bash script present in tensorflow/lite/tools/make/build_lib.sh is working.
But when generated as per documentation through CMake is not working.

**Describe the expected behavior**
Need the working static library generated through CMake.
Provide us the working CMakeLists file.
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
1)Use the steps of cmake build to generate static library on host.
2)Run build_lib.sh and generate static library.

There are differences between two libraries and only second one is working.
Need a proper CMakeLists file to generate static library,
.

**Comment by sushreebarsa** [comment]
@bhpatray 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by miaout17** [comment]
I'm adding @terryheo, who is familiar with CMake build for TFLite. 

However, as stated by @sushreebarsa, we do need more information (what is not working? how do you reproduce the issue?) Otherwise it's unlikely we can find out the issue and help you.

**Comment by terryheo** [comment]
@bhpatray if you're using C++ API, you should have a CMake build for your project.
https://www.tensorflow.org/lite/guide/build_cmake#create_a_cmake_project_which_uses_tensorflow_lite
It's because the generated TFLite static library doesn't contain all the required libraries.

FYI, you can also use C API with shared library. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c
