### ISSUE TITLE
Issue on Compile protobuf.sh?

### ISSUE THREAD

**Issue by sahil912** [tensorflow/tensorflow#5297]
Hi,

I am trying to setup latest version from tensorflow for iOS, in the process first step to  run **download_dependencies.sh** works fine, and then in the next step to run the **compile_ios_protobuf.sh**  is resulting in following error:

    .....
    glibtoolize: copying file 'm4/ltsugar.m4'
    glibtoolize: copying file 'm4/ltversion.m4'
    glibtoolize: copying file 'm4/lt~obsolete.m4'
    configure.ac:61: installing './compile'
    configure.ac:48: installing './missing'
    benchmarks/Makefile.am: installing './depcomp'
    + rm -rf autom4te.cache config.h.in~
    + exit 0
    + '[' 0 -ne 0 ']'
    + make distclean
    make: *** No rule to make target `distclean'.  Stop.

Let me know If I am missing anything, Please guide.

Thanks

**Comment by aselle** [comment]
What version of MacOS? Did you do
```brew install automake``` yet?

**Comment by sahil912** [comment]
I am using macOS Seirra version 10.12. On running brew automake i get the following 

   Warning: automake-1.15 already installed
   Warning: You are using OS X 10.12.

jfyi I am having Xcode 7.3 and Xcode 8.0 on the same system, hope that should not be a problem.

Thanks

**Comment by zafartahirov** [comment]
I cannot replicate the problem (I am on Sierra)

Try doing the following from the tensorflow root directory (make sure everything else was compiled :
```bash
brew install automake autoconf libtool
tensorflow/contrib/makefile/build_all_ios.sh
```

If that works, the documentation has to updated, if it doesn't, what is the error that fails? Note that the process might take some time to finish.

**Comment by zafartahirov** [comment]
Also, can you copy-paste the following in the tensorflow root directory:

```bash
TF=`pwd`
./configure \
  --build=x86_64-apple-darwin14.0.0 \
  --host=x86_64-apple-darwin14.0.0 \
  --disable-shared \
  --enable-cross-compile \
  --with-protoc=${TF}/tensorflow/contrib/makefile/gen/protobuf-host/bin/protoc \
  --prefix=${TF}/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_x86_64 \
  --exec-prefix=${TF}/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_x86_64 \
  'CFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk' \
  CXX= 'CXXFLAGS=-DNDEBUG -Os -pipe -fPIC -fno-exceptions -std=c++11 -stdlib=libc++ -mios-simulator-version-min=8.2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk' \
  'LDFLAGS=-arch x86_64 -mios-simulator-version-min=8.2 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/usr/lib/system' \
  'LIBS=-lc++ -lc++abi'
```

Just to explain what it does, so you wouldn't think it's malicious:
- `--build` and `--host` are architecture specs, where `x86_64-apple-darwin14.x` is iOS. I am assuming you will be running and debugging it on iOS, so both build and host are the same
- `--disabled-shared` we don't need shared libraries, only static ones!
- `--enable-cross-compile` exactly what it says
- `--with-protoc` this comes from [here](https://github.com/google/protobuf/blob/master/src/README.md)
- `--prefix` this is where everything is gonna be installed
- `--exec-prefix` same as the previous
- `CXX, LDFLAGS, LIBS` these are the compilation settings for compiler, library flags, and libraries to include

If it takes too long, add this flag: `--expunge_async`

I cannot really replicate your problem, but yet again, I have a lot of stuff installed, and not sure which one is the fix (I don't have a virtual machine). 

I think the problem is with the protobuffers, so maybe if you try installing the `protobuf` separately, it might fix it: [https://github.com/google/protobuf/releases](https://github.com/google/protobuf/releases),or using brew: `brew install protobuf`

**Comment by sahil912** [comment]
Let me try the above steps and get back. Thanks

**Comment by aselle** [comment]
Try this (see #5184)
```
brew install automake autoconf libtool
brew uninstall libtool && brew install libtool
```

**Comment by sahil912** [comment]
I have tried all the above step but still stuck with the same issue, providing more info on this:

    

> checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking target system type... x86_64-apple-darwin14.0.0
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for x86_64-apple-darwin14.0.0-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/jsahil/projects/tensorflow/latest_november/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by aselle** [comment]
@petewarden, do you have any suggestions here. I don't yet have access to a Sierra dev machine, so I can't really try this on my end.

**Comment by sahil912** [comment]
I tried to setup a new mac which had MacOS Seirra tried to follow the same steps and again stuck with the same issue. 

When I run compile_ios_protobuf.sh I am get the following error:

> .....
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:61: installing './compile'
configure.ac:48: installing './missing'
benchmarks/Makefile.am: installing './depcomp'
+ rm -rf autom4te.cache config.h.in~
+ exit 0
+ '[' 0 -ne 0 ']'
+ make distclean
make: *** No rule to make target `distclean'.  Stop.

and On running the build_all_ios.sh getting the following error 

> checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in /Users/jsahil/projects/tensorflow/latest_november/tensorflow/tensorflow/contrib/makefile/downloads/protobuf': configure: error: cannot run C compiled programs. If you meant to cross compile, use--host'.
See `config.log' for more details

**Comment by aselle** [comment]
This is apparently the same error as #5333.

**Comment by johndpope** [comment]
I suggest find the requirements / dependencies -
Then create a Gemfile
```
source 'https://rubygems.org'
ruby "2.2.3"
```

then you can use RVM + bundler to lock into specific version requirements.
```
curl -sSL https://get.rvm.io | bash    
rvm install ruby-2.2.3   
gem install rvm  (restart terminal)      
gem install bundler  
bundle install  
bundle exec make
```

**Comment by sahil912** [comment]
trying to dig more, came across #4640 which is exactly the same issue as I am facing. I just followed the fixes pointed out removing  all occurence of **X86_64** bits from the build scripts compile_ios_protobuf.sh & compile_ios_tensorflow.sh and then running build_all_ios.sh
works great on device.

**Comment by codingyourlife** [comment]
I had the same distclean error and the workaround from #4640 didn't help for the compile_ios_protobuf.sh file. Just saw you wrote you should run build_all_ios.sh, didn't do that...

For me the solution was to do a git pull (don't know if that helped), turned sleep mode to never under energy saver (search for it) and run build_all_ios.sh again. Then executing compile_ios_protobuf.sh worked.

My pc went to sleep several times during first execution of build_all_ios.sh. Either that or the git pull helped with this error.

**Comment by sahil912** [comment]
This error is specific to MacOS Seirra and building tensorflow for simulator, so making corresponding changes in the scripts and running them works for me. May be the latest git pull that you did already have the changes that I did manually in the scripts.

**Comment by alphamule** [comment]
Chiming in from https://github.com/tensorflow/tensorflow/issues/4640 , I'm pretty sure this has something to do with a clang change in Sierra (downgrading Xcode does not fix).  I believe the make distclean issue is a related issue of the shell scripts getting confused on failure.

I'm not really sure how to get help diagnosing a compiler toolchain issue like this.  If we can't figure it out, perhaps would it be prudent to detect Sierra in the script and conditional out the simulator build with some messaging?  MacOS people are hitting this as they upgrade and there are now three github issues with the same problem.

The work-around I posted is good enough for people to do on-device work & to see the demo, but it is still impossible to do any simulator testing in Sierra.

**Comment by beniroquai** [comment]
I have the same issue on Mac OSX El-Capitan when building `tensorflow/contrib/makefile/build_all_android.sh`

Also tried the steps above.. Any update on this? Thanks!
