### ISSUE TITLE
Cannot run TensorFlow 2.7 in Docker on M1 (Apple Silicon)

### ISSUE THREAD

**Issue by kennysong** [tensorflow/tensorflow#52972]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.0 Monterey
- TensorFlow installed from (source or binary): pre-built binary (Docker and pip)
- TensorFlow version (use command below): 2.7
- Python version: 3.8.10

**Describe the current behavior**

Our team needs to run TensorFlow as part of a larger application in Docker. However, this doesn't seem possible on an M1 Mac.

For example, if I use the default TF Docker image (for x86-64 only, an ARM64 image is not available): 

```
> docker run -it tensorflow/tensorflow /bin/bash
> python -c "import tensorflow"
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

I get the same error when installing from pip on an x86-64 Linux container:

```
> docker run -it --platform=linux/amd64 python:3.8-buster /bin/bash
> pip install --upgrade pip && pip install tensorflow
> python -c "import tensorflow"
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

Ostensibly, this is because the pre-built TensorFlow [requires the CPU](https://www.tensorflow.org/install/pip#hardware-requirements) to support AVX instructions, but this is not supported by Docker / QEMU when emulating an x86-64 container on M1.  

**Describe the expected behavior**

There should be a way to run TensorFlow in Docker on M1! (Without building from source.)

Every other ML/DS library works with on Docker on M1: PyTorch, Scikit-Learn, Numpy, Scipy, etc. 

**Standalone code to reproduce the issue**

See code snippets above.

**Comment by bhack** [comment]
I think this is a dup of https://github.com/tensorflow/tensorflow/issues/52845

**Comment by kennysong** [comment]
The environments are similar, but the actual error is different (AVX not available vs. floating point error), so may be worth keeping as separate issues.

**Comment by bhack** [comment]
If you want to emulate on qemu you need to build TF [from sources](https://www.tensorflow.org/install/source) to disable AVX.

Instead if you are interested on an aarch64 images check:

https://github.com/tensorflow/tensorflow/issues/52845#issuecomment-962594728

**Comment by kennysong** [comment]
Got it – personally I'd like to avoid building from source since it complicates our dependency management. 

Most other ML libraries work fine out-of-the-box in x86 emulation on M1: PyTorch, Scikit-Learn, Numpy, Scipy, etc. It would be great if TF supported it as well.

**Comment by bhack** [comment]
This more general that M1 so if you want to use this in emulation you can close this and ad a comment to https://github.com/tensorflow/tensorflow/issues/19584

**Comment by bhack** [comment]
P.s. I don't have that hw bout also you can check this Docker claim https://github.com/docker/for-mac/issues/5485#issuecomment-834163428

**Comment by alexcombessie** [comment]
> Got it – personally I'd like to avoid building from source since it complicates our dependency management.
> 
> Most other ML libraries work fine out-of-the-box in x86 emulation on M1: PyTorch, Scikit-Learn, Numpy, Scipy, etc. It would be great if TF supported it as well.

Fully agree, I am in the same situation. Tensorflow is one of the only ML libraries not supporting emulation. It would be really a big win for me to have this. I use an M1-based macbook as my main development machine.

**Comment by bhack** [comment]
If this is only about the X86 emulation we could close it:
https://github.com/tensorflow/tensorflow/issues/52845#issuecomment-968383242

**Comment by kennysong** [comment]
Yeah, it looks like #52845 has converged on the AVX issue as well, so let's move this discussion there.

**Comment by diyor28** [comment]
You can use my prebuilt TensorFlow .whl files for Docker and M1 (arch64): https://github.com/diyor28/tf-docker-m1

**Comment by mbalty** [comment]
> You can use my prebuilt TensorFlow .whl files for Docker and M1 (arch64): https://github.com/diyor28/tf-docker-m1

This very helpful. Thank you! Can you give more details on how you accomplished building those wheels?

**Comment by harraz** [comment]
> > > You can use my prebuilt TensorFlow .whl files for Docker and M1 (arch64): https://github.com/diyor28/tf-docker-m1
> > 
> > 
> > This very helpful. Thank you! Can you give more details on how you accomplished building those wheels?
> 
> Actually the build instruction are included in the repo. Under tensorflow folder there is a Dockerfile containing all the instructions

This doesn't work, the build get's stuck at the bazel build
Also, none of the wheels in the four links are working on M1

**Comment by Zhao-Dongyu** [comment]
I can’t believe this issue still exists in 2024. I tried installing TensorFlow with Anaconda, Docker, and specific TensorFlow versions, but none worked. Finally, this is how I solved it:

## Step 1: Install Miniforge

Miniforge is optimized for Apple Silicon.
```
curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
bash Miniforge3-MacOSX-arm64.sh
source ~/miniforge3/bin/activate
```

## Step 2: Create a New Environment and Install TensorFlow

### 1.	Create and activate a new Conda environment:
```shell
conda create -n tensorflow_env python=3.10 -y
conda activate tensorflow_env
```

### 2.	Install TensorFlow:
```shell
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```
## Step 3: Test the Installation

Run the following script to verify:
```shell
import tensorflow as tf
print("TensorFlow Version:", tf.__version__)
print("Is GPU available:", tf.config.list_physical_devices('GPU'))
```

**Comment by ftuyama** [comment]
Try

```
curl -L -O https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
bash Miniforge3-MacOSX-arm64.sh
source ~/miniforge3/bin/activate

conda install -c conda-forge tensorflow 
conda install tensorflow=2.9
```

**Comment by mateo-st** [comment]
I'm still experiencing the very same issue. I want to use TensorFlow 2.7 inside a docker container on MacOS; no official base images provided are compatible with ARM64 architecture. Jupyter does provide some ARM64-focused TF images but only 2.12>. It is incredible to see as well that other tf libraries as tfx do not work with python 3.11 (the python that comes with such docker image from jupyter). It's 2025 and we are at M4...
