### ISSUE TITLE
Cannot build from source and illegal instruction on import tensorflow

### ISSUE THREAD

**Issue by DJT777** [tensorflow/tensorflow#52974]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04

- TensorFlow installed from (source or binary): Source and Binary

- TensorFlow version: 2.6.

- Python version: 3.8

- Installed using virtualenv? pip? conda?: Using virtualenv to install by pip, and build from source

- Bazel version (if compiling from source): 4.2.1

- GCC/Compiler version (if compiling from source): 9.3.0

- CUDA/cuDNN version: 11.4

- GPU model and memory: EVGA RTX 3060

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

When using pip to install, attempting to import tensorflow produces an "Illegal instruction(core dumped)" error.

When using Bazel to build from source using the command, `bazel build --jobs=2 --local_ram_resources=2048 --config=opt config=cuda //tensorflow/tools/pip_package:build_pip_package` I come back hours later to find the screen frozen and the computer unresponsive.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Currently unable to copy and paste logs from terminal because my computer freezes during the build.

**Comment by DJT777** [comment]
Photo of the terminal at screen freeze:

![PXL_20211107_040457264](https://user-images.githubusercontent.com/47899472/140632226-056d12c5-599f-4792-99a2-b654fb23096d.jpg)

**Comment by mohantym** [comment]
Hi @DJT777! Could you try again with with [tested configurations](https://www.tensorflow.org/install/source#tested_build_configurations) for TF 2.6.

**Comment by DJT777** [comment]
I was able to get past the screen freeze by using a swap, but now I am getting this error: 

@mohantym 

`
ERROR: /home/dylan/tensorflow/tensorflow/lite/python/BUILD:63:10 Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)`

When I try "python3 -m pip install keras-preprocessing"

Requirement already satisfied: keras_preprocessing in /home/dylan/tf-from-source/lib/python3.8/site-packages (1.1.2)

**Comment by mohantym** [comment]
Hi @DJT777! Sorry for the late response . You should try again with Bazel 3.7.2 and GCC 7.3.1 . 
```

**Comment by DJT777** [comment]
@mohantym 

I was able to build successfully by not using a virtual environment, installing the dependencies in the installation instructions, and using a swap. Tensorflow is now importing without error.

**Comment by mohantym** [comment]
Ok @DJT777! Thanks for confirming the same. Please movie this issue to closed status if issue is resolved .Thanks!
