### ISSUE TITLE
Release pre-built wheels for manylinux2014_aarch64 and macosx_arm64

### ISSUE THREAD

**Issue by kennysong** [tensorflow/tensorflow#52973]
**System information**
- TensorFlow version (you are using): 2.6
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

You can't `pip install tensorflow` natively on an M1 Mac, since there are no pre-built wheels for macosx_arm64 or manylinux2014_aarch64 (for a native Linux container or VM on M1). 

PyTorch [has provided these pre-built binaries](https://pypi.org/project/torch/#files) for several versions now. It would be great if TF was similarly easy to install on the latest generation of Macs. 

(I know that the separate PyPI package tensorflow-macos exists, but it isn't a portable solution and is not documented.)

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Any user of the latest and future generations of Macs.

**Comment by mihaimaruseac** [comment]
We don't have support for these architectures, we are stretched quite thin already with the official builds.

Apple M1 builds were never supported officially by Google.

**Comment by alexcombessie** [comment]
Really looking forward to this support. Thanks!

**Comment by matteosantama** [comment]
@mihaimaruseac It would be helpful to compile a list of outstanding issues that must be resolved before being able to provide these wheels. This would allow people to track progress, and contribute to the blocking issues.

**Comment by mihaimaruseac** [comment]
We don't even have access to infra to run these builds. While we're blocked on that we're completely blind.

**Comment by dwyatte** [comment]
As far as aarch64 goes, looks like a Dockerfile for building manylinux2014 wheels was recently added in https://github.com/tensorflow/tensorflow/commit/c5ae019abd2f260cf3400abcce4962c75cc5182c

I think what would be needed is official support for configuring bazel to cross-compile tensorflow for these wheels (a quick search on aarch64 shows that most of the support for aarch64 is in tflite)

**Comment by bhack** [comment]
Just a side note also having a Linux aarch64 image on M1 we are not going to be able to use the AMX2 instruction set:

https://github.com/tensorflow/tensorflow/issues/52845#issuecomment-974559363

https://nod.ai/comparing-apple-m1-with-amx2-m1-with-neon/

**Comment by bhack** [comment]
And also ANE https://developer.apple.com/forums/thread/673627

**Comment by ddelange** [comment]
From the GPU perspective: 

- It looks like TensorRT won't work on ARM ([missing](https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/) `libnvinfer` deb) ref https://github.com/tensorflow/tensorrt/issues/142#issuecomment-1077394968
- The rest of the [CUDA math libraries](https://developer.nvidia.com/gpu-accelerated-libraries) and `cuDNN` should be fine, they're all available for arm: they are for instance included in the cuda [`runtime`](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=cudnn8-runtime) images which are also built for arm64, on which [`gpu.Dockerfile`](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/tools/dockerfiles/dockerfiles/gpu.Dockerfile) could base

**Comment by dakl** [comment]
Any progress on this? It would be great if someone could provide some sort of timeline, as in "next minor version" or >1 year away or something like that?

**Comment by mihaimaruseac** [comment]
There are talks about this support, analyzing all possible roadmaps that we could take. A nice thing is that now we have manylinux2014 support, but we still need to tackle the question of how to test these builds if CI infra is not yet there.

**Comment by dakl** [comment]
> CI infra is not yet there.

I pretty sure codemagic has M1s that one can provision for CI these days. Maybe others have it too.

**Comment by mihaimaruseac** [comment]
Yes, but we need people to maintain the infra and they need to be paid, so this means it needs to be something in the roadmap that helps Google or a community contribution project.

**Comment by dakl** [comment]
Hello @mihaimaruseac , I'm just checking in here since it's been a couple of months since our last comms. Is there any progress on this? What exactly would be needed/you need from the community to make this happen?

**Comment by mihaimaruseac** [comment]
I no longer work on TF, just consult the team from time to time

**Comment by SuryanarayanaY** [comment]
Hi @kennysong ,

Current tf-nightly version installs prebuilt Arm wheel for Apple silicon devices i.e Mac M1.M2 etc. Please refer the same from setup.py file from TF Master branch below.

https://github.com/tensorflow/tensorflow/blob/3ace0c0eb8ef5856acc7a0fe6396b696ff800262/tensorflow/tools/pip_package/setup.py#L155-L159

You can try installing tf-nightly using `pip install tf-nightly` on macos_arm64 devices and it can install Arm wheel now.

Please note that currently it is available for only nightly version.

Thanks!

**Comment by ddelange** [comment]
judging by the file sizes, there is no CUDA support on [pypi](https://pypi.org/project/tensorflow/2.12.0/#files) for platforms other than `x86_64` yet, pleeze freeze life cycle @SuryanarayanaY

**Comment by SuryanarayanaY** [comment]
@ddelange ,

There are no prebuilt binaries for platforms other than x86_64 from Tensorflow team , except for Mac M1/M2 (Arm64) which were built and maintained by Apple itself for the Mac M1/M2 users. From TF2.13rc0 `pip install tensorflow` command allowing Mac M1/M2 users to install Apple built binaries. Earlier Mac users need to use `pip install tensorflow-macos ` to install Mac Arm wheels and now from 2.13rc0 there is no need to use explicit `tensorflow-macos`.

If you want to build binaries for Linux Aarch you have to opt for build from [source](https://www.tensorflow.org/install/source).

Thanks!

**Comment by janhartman** [comment]
@SuryanarayanaY Is there any plan to build [libtensorflow](https://www.tensorflow.org/install/lang_c) for ARM64?

**Comment by SuryanarayanaY** [comment]
AFAIK, There is no plan in pipeline for ARM64 pre built wheels for TF or libtensorflow. I am not aware of Future and exact timeline but for now no such plans. Thanks!
