### ISSUE TITLE
Problem with calling the same object twice in the "call" part

### ISSUE THREAD

**Issue by alemyewno** [tensorflow/tensorflow#52982]
My model is this:

```
class DenseModel(Model):
    def __init__(self):
        super(DenseModel, self).__init__(name='class_dense_model')
        self.dense_1 = layers.Dense(1)
        self.dense_64 = layers.Dense(64, activation=tf.nn.relu)
        self.dense_100 = layers.Dense(100,activation=tf.nn.relu)
        self.dense_200 = layers.Dense(200,activation=tf.nn.relu)
        self.dense_200_2 = layers.Dense(200, activation=tf.nn.relu)

    def call(self, input_tensor, training=False, **kwargs):
        out_1 = self.dense_64(input_tensor)
        out_2 = self.dense_100(out_1)
        out_3 = self.dense_200(out_2)
        out_4 = self.dense_200(out_3)
        return self.dense_1(out_4)

    def build_graph(self, shape):
        x = tf.keras.layers.Input(shape=shape)
        return Model(inputs=[x], outputs=self.call(x))
```

Then I build it like this 

```
model = DenseModel()
model.build_graph(INPUT_SHAPE)
```

This gives me the following error:

"ValueError: Dimensions must be equal, but are 200 and 100 for '{{node dense_5/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](Placeholder, dense_5/MatMul/ReadVariableOp)' with input shapes: [?,200], [100,200]."

When I change ```out_4 = self.dense_200(out_3)``` into ```out_4 = self.dense_200_2(out_3)``` the error is gone. I realized that the error is caused when using the same object twice in the "call" part. I checked the documentation from this link https://www.tensorflow.org/guide/keras/custom_layers_and_models

I saw that you build two objects from the same class and the same parameters in __init__ part. Why? I mean, why do we have problem with calling the same object twice in the "call" part? What if I want to call one object 100 times in for loop? I mean, I just don't understand why I get this error when it shouldn't be the error.

**Comment by sushreebarsa** [comment]
@alemyewno 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
