### ISSUE TITLE
Function _implements is missing when create a new object

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#52987]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):debian10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.7.0
- Python version:3.9.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```_implements``` is missing in new objects.
**Describe the expected behavior**
```_implements``` exists.
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

experimental_implements = " ".join(['name: "addons:MaxUnpooling2D"'])
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32), tf.TensorSpec(shape=[], dtype=tf.float32)], experimental_implements = experimental_implements)
def test(a, b):
    return a+b



class Test(tf.Module):
    @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.float32), tf.TensorSpec(shape=[], dtype=tf.float32)], experimental_implements = experimental_implements)
    def test(self, a, b):
        return a+b

model = Test()
model2 = Test()
model.test = test
assert model.test._implements == test._implements
assert model2.test._implements == Test.test._implements
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look into this issue? It is replicating in TF [2.6,](https://colab.research.google.com/gist/mohantym/bdbcb7c7483706e884ac09f932d0ba4e/github_52987.ipynb#scrollTo=Ep2KdhZbrhga) [2.7 ](https://colab.research.google.com/drive/1ZfkNCjNIb4qY5jkeJ3_NYo9q1nLAeQ70?resourcekey=0-lEO7IYc7t-tJOS2o8IDQ7A#scrollTo=Ep2KdhZbrhga)and [Nightly ](https://colab.research.google.com/gist/mohantym/0a8bef4beafa4c302960d74877f38967/github_52987.ipynb#scrollTo=iEQw-Z_rr_jk).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
