### ISSUE TITLE
tensorflow-estimatior==2.0.0 not available so can't fix known issue

### ISSUE THREAD

**Issue by GrigoriiTarasov** [tensorflow/tensorflow#52983]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution Linux Ubuntu 20.04.2 LTS
- Installed using mamba
- TensorFlow version: 2.0.0
- Python version: 2.7.0

**Describe the problem**
Default  tensorflow-estimator  mismatches tensorflow as in https://stackoverflow.com/questions/66022256/modulenotfounderror-no-module-named-tensorflow-core-estimator-for-tensorflow
but for 2.0.0 can't be installed direclty as in https://stackoverflow.com/a/66027093/7607734
(it worked for tf 2.1.0)
also https://stackoverflow.com/a/66027135/7607734 gives nothing.
So seem to be unresolved for 2.0.0

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1) 
mamba create --name py3_7_keras_ocr  python=3.7.0 keras-ocr anaconda
2) 
conda activate py3_7_keras_ocr
3)
 conda list | grep tensorflow
4)
mamba install tensorflow-estimatior==2.0.0
or
conda install tensorflow-estimatior==2.0.0

**Any other info / logs**
3)
> conda list | grep tensorflow

```
tensorflow                2.0.0           mkl_py37h66b46cc_0  
tensorflow-base           2.0.0           mkl_py37h9204916_0  
tensorflow-estimator      2.6.0              pyh7b7c402_0  
```

4)
> conda install tensorflow-estimatior==2.0.0
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow-estimatior==2.0.0
Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

**Comment by mihaimaruseac** [comment]
You have a typo

```diff
-conda install tensorflow-estimatior==2.0.0
+conda install tensorflow-estimator==2.0.0
```

**Comment by GrigoriiTarasov** [comment]
Thank you!
