### ISSUE TITLE
Unable to use tensorflow after installing

### ISSUE THREAD

**Issue by josephcoveai** [tensorflow/tensorflow#52994]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I try to install tensorflow and it just says all of the requirements are already satisfied but it throws an error everytime I try to use tensorflow.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**

C:\Users\josep\Videos>pip3 install --user --upgrade tensorflow
Requirement already up-to-date: tensorflow in c:\users\josep\anaconda3\lib\site-packages (2.7.0)
Requirement already satisfied, skipping upgrade: absl-py>=0.4.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (0.15.0)
Requirement already satisfied, skipping upgrade: flatbuffers<3.0,>=1.12 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.12)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Requirement already satisfied, skipping upgrade: grpcio<2.0,>=1.24.3 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.41.1)
Requirement already satisfied, skipping upgrade: gast<0.5.0,>=0.2.1 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (0.4.0)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: wheel<1.0,>=0.32.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (0.37.0)
Requirement already satisfied, skipping upgrade: h5py>=2.9.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<2.8,~=2.7.0rc0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (2.7.0)
Requirement already satisfied, skipping upgrade: keras<2.8,>=2.7.0rc0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (2.7.0)
Requirement already satisfied, skipping upgrade: numpy>=1.14.5 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.21.4)
Requirement already satisfied, skipping upgrade: libclang>=9.0.1 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (12.0.0)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.1 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.9.2 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (3.19.1)
Requirement already satisfied, skipping upgrade: tensorflow-io-gcs-filesystem>=0.21.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (0.21.0)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied, skipping upgrade: opt-einsum>=2.3.2 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.6 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (3.7.4.3)
Requirement already satisfied, skipping upgrade: astunparse>=1.6.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied, skipping upgrade: tensorboard~=2.6 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (2.7.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.1.1 in c:\users\josep\anaconda3\lib\site-packages (from tensorflow) (1.1.2)
Requirement already satisfied, skipping upgrade: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (0.6.1)
Requirement already satisfied, skipping upgrade: setuptools>=41.0.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (58.5.3)
Requirement already satisfied, skipping upgrade: tensorboard-plugin-wit>=1.6.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.8.0)
Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (2.24.0)
Requirement already satisfied, skipping upgrade: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (0.4.6)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.0.1)
Requirement already satisfied, skipping upgrade: google-auth<3,>=1.6.3 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (2.3.3)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\josep\anaconda3\lib\site-packages (from tensorboard~=2.6->tensorflow) (3.3.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\josep\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2020.6.20)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\josep\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (1.25.11)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\josep\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\josep\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (3.0.4)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in c:\users\josep\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (1.3.0)
Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= "3.6" in c:\users\josep\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.7.2)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in c:\users\josep\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.2.8)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in c:\users\josep\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.2.4)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\users\josep\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (3.1.1)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in c:\users\josep\anaconda3\lib\site-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.4.8)

C:\Users\josep\Videos>python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\Users\josep\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\josep\anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\josep\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\josep\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 79, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\josep\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

**Comment by tilakrayal** [comment]
@josephcoveai ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from the issue with similar error.It helps.
Also in order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

and the exact sequence of commands / steps that you executed before running into the problem.Thanks
