### ISSUE TITLE
How to specify the output layers during model conversion to TFLite in TF2?

### ISSUE THREAD

**Issue by qqwerter** [tensorflow/tensorflow#52999]
**Describe the problem**
Is there any way to remove the TFLite_Detection_PostProcess in tf2 ssd mobilenet model during conversion to tflite model？In tf1, there is a option to do so, but it seems that in tf2 the option for specifying the output layers is removed. 

In tf1, I can specify the output layers by putting the name in output_array:
input_arrays=["normalized_input_image_tensor"]
output_arrays=["raw_outputs/box_encodings","raw_outputs/class_predictions"]
input_tensor={"normalized_input_image_tensor":[1,320,320,1]}

import tensorflow as tf
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph('tflite_graph.pb',input_shapes = input_tensor,
input_arrays = input_arrays ,output_arrays = output_arrays)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.allow_custom_ops = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,tf.lite.OpsSet.SELECT_TF_OPS]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
open('ssd_mobilenet_v2_tf1.tflite', "wb").write(tflite_model)

**Comment by sushreebarsa** [comment]
@qqwerter 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
