### ISSUE TITLE
Tensorboard from pip installation broken 

### ISSUE THREAD

**Issue by kentonl** [tensorflow/tensorflow#530]
Tensorboard tries to load a file here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/tensorboard.py#L145

but `tensorboard/TAG` is missing from the pip installation, so it produces the following message:
```
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG
WARNING:tensorflow:Unable to read TensorBoard tag
Starting TensorBoard  on port 6006
(You can navigate to http://localhost:6006)
```
and does not render any logged events.

**Comment by pradyu1993** [comment]
+1 I am also facing the same issue

**Comment by windeveloper** [comment]
the same problem here. tensorboard cannot list the events, possibly related to the warning...

**Comment by vrv** [comment]
I believe missing the TAG is just a warning and shouldn't cause any problems.  If you look at the source code of tensorboard.py, you'll see TAG is just for debugging.

Not rendering any logged events is probably an independent problem -- can you verify / validate / reproduce the problem in a way we can help debug?

**Comment by kentonl** [comment]
I built the pip package from source and installed it. Tensorboard can't render the events if I run:
```
tensorboard --logdir=/tmp/logs
```
but it works when I build tensorboard and run:
```
./bazel-bin/tensorflow/tensorboard/tensorboard --logdir=/tmp/logs
```
The only difference here seems to be the pip packaging.

**Comment by kentonl** [comment]
I can't seem to reproduce the problem anymore. Perhaps I was write summaries incorrectly before. Closing this for now...

**Comment by PeterARBork** [comment]
I had similar problems until I realized that the summary writer did not actually write the file unless I called the summary writer's flush() function.

I'm not sure, but it's probably because I had the summary writer's code snippet in a code part that did not close (and the code finished before the standard 120 seconds between each automatic flush).

**Comment by eriche2016** [comment]
same problem here

**Comment by schmiflo** [comment]
Same here. Out of a sudden I needed to add flush the summary writer after writing to see any summaries...

**Comment by danmane** [comment]
Do you mind filing another issue re: the summary writer not flushing, with a reproduction? Since it is pretty different from the TensorBoard pip installation issue discussed here.

**Comment by jaycode** [comment]
I got a similar same problem, this is the code to demonstrate:

```
graph = tf.Graph()
with graph.as_default(), tf.device('/cpu:0'):
  a = tf.constant(5.0)
  b = tf.constant(6.0)
  c = a * b
  
  # Enter data into summary.
  c_summary = tf.scalar_summary("c", c)
  merged = tf.merge_all_summaries()

with tf.Session(graph=graph) as session:
  writer = tf.train.SummaryWriter("log/test_logs", session.graph_def)

  result = session.run([merged])
  tf.initialize_all_variables().run()
  writer.add_summary(result[0], 0)
```

I then ran `tensorboard --logdir={absolute path to log/test_logs}` but no event was listed there. Is there anything I should have written differently in the code maybe?

Note that `log/test_logs` does contain files like `events.out.tfevents.1459102927.0a8840dee548`.

**Comment by jaycode** [comment]
Update: Running `https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py` also does not make tensorboard list the events.

**Comment by danmane** [comment]
@jaycode: Can you `ls -lah` your events file and tell me the size? Also, how did you install TensorBoard, and which version of pip are you using?

**Comment by jaycode** [comment]
@danmane 
Results of ls -lah:
```
total 8.5K
drwxrwxrwx 1 root root 4.0K Mar 27 20:23 .
drwxrwxrwx 1 root root    0 Mar 27 20:36 ..
-rwxrwxrwx 1 root root  592 Mar 28 06:09 events.out.tfevents.1459102927.0a8840dee548
-rwxrwxrwx 1 root root  592 Mar 28 06:09 events.out.tfevents.1459103131.0a8840dee548
-rwxrwxrwx 1 root root  500 Mar 28 06:09 events.out.tfevents.1459103348.0a8840dee548
-rwxrwxrwx 1 root root  500 Mar 28 06:09 events.out.tfevents.1459103526.0a8840dee548
-rwxrwxrwx 1 root root  500 Mar 28 06:09 events.out.tfevents.1459103820.0a8840dee548
-rwxrwxrwx 1 root root  537 Mar 28 06:09 events.out.tfevents.1459110199.0a8840dee548
```
for `test_logs`, and

```
total 1.2M
drwxrwxrwx 1 root root 4.0K Mar 27 20:38 .
drwxrwxrwx 1 root root    0 Mar 27 20:36 ..
-rwxrwxrwx 1 root root  21K Mar 27 20:38 events.out.tfevents.1459111009.0a8840dee548
-rwxrwxrwx 1 root root  32K Mar 27 20:38 events.out.tfevents.1459111051.0a8840dee548
-rwxrwxrwx 1 root root 1.1M Mar 28 06:09 events.out.tfevents.1459111110.0a8840dee548
```

for `mnist_logs` (from script [mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py)). Both shows no event in tensorboard.

Tensorflow and Tensorboard were both installed by default from tensorflow/tensorflow docker. Pip version is `pip 8.0.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)`.

**Comment by ultrons** [comment]
@jaycode I am having similar problems. I am not able to even see the computation graph.
Are you able to see the graph?

**Comment by jaycode** [comment]
Yeah. In my case the path was incorrect. Try running tensorboard with
`--debug` to see what the problem is.
On Apr 11, 2016 2:58 AM, "ultrons" <notifications@github.com> wrote:

@jaycode <https://github.com/jaycode> I am having similar problems. I am
not able to even see the computation graph.
Are you able to see the graph?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/530#issuecomment-208052591>

**Comment by ultrons** [comment]
Thanks for the --debug option tip. I see only one event file in my directory though. Doesn't seem right.
I was looking for a method to just visualize the computation graph and nothing else (no histogram, learning curve etc). Have you tried to do it by any chance?

**Comment by danmane** [comment]
@ultrons We actually have an internal debugging tool that is just the graph visualizer without the rest of TensorBoard. It wouldn't be too difficult to export this as a standalone tool. If you want it, can you please file another issue requesting this feature, and we can ask @dsmilkov to take a look.

**Comment by ultrons** [comment]
@danmane , good to know that this functionality exists. I will create another issue to request this as a feature in future releases.

**Comment by Fhrozen** [comment]
I do not if it is correct to ask this here, but I am wondering about the installation for developers using bazel. The problem is that when I tried to compile tensorflow (tf), bazel cleans the cache so when i tried to run tensorboard (tb) it show the message that tb is not in the list. and then when I tried to compile tb it cleans tf. Is possible to keep both of them using the source code? and avoiding run bazel every single time that i need tf or tb?  or Do i need to have two installations folders one for tf and another for tb?

**Comment by danmane** [comment]
@Fhrozen 
You should be able to build both tensorflow and tensorboard using bazel without having the two conflict. I'm not sure what's going wrong in your case - you could try building all your targets (without using bazel run) and then run them by invoking the built target in `bazel-bin`.
If you keep having issues with bazel, please open a separate issue with a clear reproduction of the exact commands you're using and the errors that you're seeing.

**Comment by ruthyaneth** [comment]
Install docker, tensorflow and python 
https://youtu.be/OiPjSnKAmSI
