### ISSUE TITLE
[tflite] any way to extract operator attributes from interpreter

### ISSUE THREAD

**Issue by chensterliu** [tensorflow/tensorflow#53003]
**System information**
- python 3.8.11
- TensorFlow 2.5.1
- Are you willing to contribute it: No

**Describe the feature and the current behavior/state.**
With current APIs I can extract operator details with
> ip = tf.lite.Interpreter(model_path=tflite_file)
> ip._get_ops_details()

I could get (for example):

> {'index': 0,
>   'op_name': 'CONV_2D',
>   'inputs': array([0, 4, 2], dtype=int32),
>   'outputs': array([13], dtype=int32)}

I would expect another key "builtin_option" in this dict to expose all attributes of this layer contained in flatbuffer, e.g. fused_activation_function, padding, stride_h/w etc.
Currently, I'm parsing a tflite model and automating code preparation for an edge device with a customized DNN accelerator. Those attributes data is important to configure hardware components. Now I'm parsing the tflite model with flatbuffer API to extract those attributes, but the code is bloated and ugly, so I expect that the interpreter._get_ops_details() can include this part.

**Will this change the current api? How?**
The required "attributes" key doesn't change the current API.
In `_get_ops_details()` of `interpreter.py`, a new line like
> op_attributes = self._interpreter.NodeAttributes(op_index)

could be added.
**Who will benefit with this feature?**
Anyone who only wants to take the single tflite model as the entry and easily parse both tensors and operators content for their own backend.
**Any Other info.**
I'm still new to tensorflow, if anyone can extract operators in a easy way, please leave comments below :)

**Comment by miaout17** [comment]
If you want to read the information from TensorFlow Lite builtin ops and write your own backends, the TensorFlow Lite **Delegate** mechanism is exactly for doing that. 

Please take a look at https://www.tensorflow.org/lite/performance/implementing_delegate

Let us know if you have any further questions. Thanks!
