### ISSUE TITLE
Can I init a XlaBuilder using a existing XlaComputation？

### ISSUE THREAD

**Issue by chenzhengda** [tensorflow/tensorflow#53001]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

It will be useful to modify a existing  HloModule with XlaBuilder Operation Semantics

**Comment by tilakrayal** [comment]
@chenzhengda ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!
