### ISSUE TITLE
Wrong Tensorflow Lite link to hexagon_nn_skel.run v1.21 (actually is pointing to the v1.20.0.1)

### ISSUE THREAD

**Issue by glodanclaudia** [tensorflow/tensorflow#53000]
Hi, I want to download the hexagon_nn_skel.run v1.21. In the Tensorflow Lite Hexagon guide there are many links to many versions: https://www.tensorflow.org/lite/performance/hexagon_delegate. The problem is that v1.21 is pointing to v1.20. So the question is where can I find the version 1.21 of hexagon_nn_skel.run?
Also, in the guide it is specified that we must use the hexagon_nn libraries with the compatible version of interface library, as stated in bazel config. From bazel config (https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) I understand that I must use the version 20.0.3 of the interface. So where can I find the version 20.0.3 of the interface library?

**Comment by mohantym** [comment]
Hi! @sachinprasadhs! Could you please look at this bug?

**Comment by karimnosseir** [comment]
Hi @glodanclaudia thanks for reporting this.

This is the correct version. I think updating the documentation to mention v1.20.0.1 might be better.
I sent a fix to update the documentation.

Regarding the interface library.
If you're using the delegate through java API, then everything will be pulled from the gradle dependency as mentioned [here](https://www.tensorflow.org/lite/performance/hexagon_delegate#step_1_edit_appbuildgradle_to_use_the_nightly_hexagon_delegate_aar)
If you want to do it through bazel then you can do

bazel build -c opt --config=android_arm64 //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface

or download the tar file in the bzl file you pointed to and you will find the library inside it with header files.

Thanks again, and please let me know if you are having any issues.

Thanks

**Comment by glodanclaudia** [comment]
Hi @karimnosseir , thank you for help! 
I understand now that v1.21 is actually v1.20.0.1.
But I want to use the delegate using C API, not Java. So yes, we built the interface using bazel but the resulted interface has version 1.20.0.3. This means that we need hexagon_nn_skel.run v1.20.0.3 in order to assure the compatibility. Where can I found this?

**Comment by glodanclaudia** [comment]
One more thing.... I want to use tensorflow lite 2.6.0 or higher so that's why I need the version 1.20.0.3 of hexagon_nn_skel.run.
Also here https://github.com/tensorflow/tensorflow/blob/v2.7.0/third_party/hexagon/workspace.bzl is mentioned this version.

**Comment by karimnosseir** [comment]
As mentioned here
https://github.com/tensorflow/tensorflow/blob/v2.7.0/third_party/hexagon/workspace.bzl#L5

You should be using 1.20 this includes 1.20.0.1. So you should be good to go.
If you have issues when you use, please let us know.

**Comment by miaout17** [comment]
Closing because the questions seem fully answered. Please feel free to reopen if there are more questions.
