### ISSUE TITLE
Issue in import tensorflow

### ISSUE THREAD

**Issue by Jeevvenrat** [tensorflow/tensorflow#53007]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Jeevvenrat** [comment]
Hi @sushreebarsa,

I have installed Anaconda 3 which has integrated python 3.7 within it.
Currently i need to install the latest version of tensorflow-base 2.6.0 from the below link for windows 64bit
https://anaconda.org/main/tensorflow-base/files
File Name: tensorflow-base-2.6.0-mkl_py37h9201259_0.tar.bz2
Tensorflow is installed using command
conda install tensorflow-base-2.6.0-mkl_py37h9201259_0.tar.bz2
but when i try to import the tensorflow using below command
import tensorflow as tf

I get the below error and fails to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 28, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'

can anyone please provide me a solution as it is very critical for me to resolve this

**Comment by sushreebarsa** [comment]
@Jeevvenrat Thanks for the update!
Could you please refer to the  official site to [install TF](https://www.tensorflow.org/install/pip#windows_1)  and [Build from source](https://www.tensorflow.org/install/source_windows) and let us know if it helps? Thank you!

**Comment by Jeevvenrat** [comment]
Also i want to install the library offline without creating environment or using pip install as the fire wall policies blocks and give an ssl error

**Comment by Jeevvenrat** [comment]
@sushreebarsa please let me know if there is any other dependencies other than pip version greater than 19.0 and c++  redistributable.

**Comment by Jeevvenrat** [comment]
When i install absl library offline using conda install command and then try to import tensorflow i get the below error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

**Comment by Jeevvenrat** [comment]
In the end when i install all the libraries which is giving no module named, i get a different error.
(base) C:\Temp\anaconda library>conda install googleapis-common-protos-1.53.0-py37h9ae81ce_1.tar.bz2

Downloading and Extracting Packages
############################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Temp\anaconda library>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
>>> exit()

(base) C:\Temp\anaconda library>conda install protobuf-3.14.0-py37hd77b12b_1.tar.bz2

Downloading and Extracting Packages
############################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Temp\anaconda library>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 37, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 23, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x0000024B9C8FB868> returned a result with an error set

**Comment by sushreebarsa** [comment]
@Jeevvenrat 
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) from here.
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
Please, check Your CPU/Python is on 32 bits?Please, refer #36167, #42367,#42197,#45435
Please refer to the common [errors](https://www.tensorflow.org/install/errors) and let us know if it helps ?

If the issue still persists please post it on [Anaconda repo ](https://github.com/ContinuumIO/anaconda-issues/issues)as we do not support conda environment.
This issue is more suitable on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues) repo since its related to TF installation with Anaconda.
Please post it on Continuum Anaconda.
Thanks you!
