### ISSUE TITLE
Feature request: Automated builds for AVX2 

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#5301]
Would it be possible to add also AVX2 optimized builds to the automated PIP builds provided by Google?

**Comment by caisq** [comment]
@gunan, what do you think?

**Comment by gunan** [comment]
Unfortunately, we do not have machines that have avx2 support for all configurations we have.
I can see ourselves upgrading some of the machines soon, however as Apple did not update mac pro's this year, I see no way for us to release avx2 images for mac.
For linux, this might be possible in some near future, but not immediately.

**Comment by hholst80** [comment]
For us Linux amd_64 and Python 3.5. We have no need for MacOSX or Python 2.7 support at the moment.

**Comment by gunan** [comment]
I just checked, and no machines test and release infra currently has avx2 extensions.
We are all blocked on services providing these machines to us, therefore for the time being, we can build, but we cannot test it for avx2.

Given the fragility of the avx build, we have to test it and fix all the issues with avx2.
http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu-mavx/

All things considered, official support for avx2 is infeasible right now. We will reevaluate this in a quarter. I am closing this issue for now.
