### ISSUE TITLE
Interconnect Issue + NaN Error

### ISSUE THREAD

**Issue by AnishKumarNayak** [tensorflow/tensorflow#53017]
When I run python train.py (attached here) it does not give a Y next to the GPU when Interconnect Matrix is checked. Following which it runs the CPU version, and NaN error is attained after a few steps. i have not seen any such issue when training on NVIDIA Tesla K40c (attached as sm25epc.log) or Tesla T4 (attached as nohup.txt
[nohup.txt](https://github.com/tensorflow/tensorflow/files/7510510/nohup.txt)
[sm25epc.log](https://github.com/tensorflow/tensorflow/files/7510523/sm25epc.log)
[train.txt](https://github.com/tensorflow/tensorflow/files/7510530/train.txt)
)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS

- TensorFlow installed from (source or binary): Anaconda (GPU)
- TensorFlow version: latest version (I'm guessing 2.5 above) I installed using conda create -n tf-gpu or something similar last week
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: Anaconda (2021.05 release)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NVIDIA-SMI 450.142.00   Driver Version: 450.142.00   CUDA Version: 11.0  
- GPU model and memory: A100-SXM4-40GB

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by AnishKumarNayak** [comment]
[job.21631.txt](https://github.com/tensorflow/tensorflow/files/7510565/job.21631.txt)
Error file attached here

**Comment by AnishKumarNayak** [comment]
This is submitted in a GPU cluster (there's a SLURM script and all)
I find that when submitting to a local A100 it does not give a N error but it still has a CUDA initialisation error and reverts to Tensorflow CPU Libary (There I use CUDA 11.5) Remaining is the same

**Comment by sanatmpa1** [comment]
@AnishKumarNayak,

Can you confirm if you're trying the code in latest stable version i.e `2.7.0`? Also from the template, I can see that you mentioned the CUDA version as 11.0 whereas as per tested build config for 2.7.0, cuda version 11.2 is used. You can refer this [link](https://www.tensorflow.org/install/source#gpu) and make sure you have corresponding versions of compiler, CUDA and cuDNN are used. Thanks!

**Comment by AnishKumarNayak** [comment]
Hi,
It should be 2.7.0 as I have installed the default latest version available in Anaconda3 just a week back.
My bad, I was a little careless. I am using a GPU cluster at the moment, and we submit our job using SLURM script. I have used source to call upon CUDA 11.0.2 and CUDA 11.2 on separate occasions with the same issue.
As far as compilers are concerned, I am not familiar with that as we did not build Tensorflow from source, but rather installed using Anaconda3 as a virtual environment. CUDA and cuDNN have been confirmed to be compatible with each other.

**Comment by sanatmpa1** [comment]
@AnishKumarNayak,

I took a look at your code in train.txt and I am not able to get the `core` library that you've used in import section. Can you share a standalone reproducible code or a colab gist to expedite the trouble-shooting process? Thanks!
