### ISSUE TITLE
New problem in TF 2.6 that does not appears in 2.3.1 (TypeError: Input must be a SparseTensor.)

### ISSUE THREAD

**Issue by FernandoDorado** [tensorflow/tensorflow#53010]
Hi, 
I've been migrating our tensorflow images from 2.3 to 2.6. To my surprise, I've found bugs in the code that didn't appear before. The error is as follows: 
```bash
TypeError: in user code:

    <ipython-input-108-26abd43eddb2>:11 parse_function  *
        values = [float(_fill_in_missing(value)) for value in values]
    <ipython-input-110-f4a86837955a>:92 _fill_in_missing  *
        return tf.sparse.to_dense(x, default_value)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/sparse_ops.py:1711 sparse_tensor_to_dense  **
        sp_input = _convert_to_sparse_tensor(sp_input)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/sparse_ops.py:71 _convert_to_sparse_tensor
        raise TypeError("Input must be a SparseTensor.")

    TypeError: Input must be a SparseTensor.
```

The functions that return this error are the following: 
```python
def parse_function(example_proto):
    '''Parse the values from tf examples'''
    feature_spec = tf_transform_output.transformed_feature_spec()
    features = tf.io.parse_single_example(example_proto, feature_spec)
    values = list(features.values())
    values = [float(_fill_in_missing(value)) for value in values]  
    features = tf.stack(values, axis=0)
    return features
def _fill_in_missing(x):
    """Replace missing values in a SparseTensor.
    Fills in missing values of `x` with '' or 0, and converts to a dense tensor.
    Args:
    x: A `SparseTensor` of rank 2.  Its dense shape should have size at most 1
      in the second dimension.
    Returns:
    A rank 1 tensor where missing values of `x` have been filled in.
    """
    default_value = '' if x.dtype == tf.string else 0
    return tf.sparse.to_dense(x, default_value)

def get_dataset(path):
    '''Get the dataset and group them into windows'''

    dataset = tf.data.TFRecordDataset(path, compression_type="GZIP")
    dataset = dataset.map(parse_function)
    dataset = dataset.window(HISTORY_SIZE, shift=SHIFT, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(HISTORY_SIZE))
    dataset = dataset.map(add_mode)
    dataset = dataset.batch(BATCH_SIZE, drop_remainder=True)
    dataset = dataset.repeat()
    
    return dataset
```

I've tried ignoring the _fill_in_missing function and some new errors appears related to the batch (these errors also don't appear the TF 2.3 version): 
`Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [2,1], [batch]: [1] [Op:IteratorGetNext]`

It's interesting that the previous batches can be used without any problem, but the last batch has a problem and I don't find a way to fix it. 

Older versions (in which the code run without problems):
TF version: 2.3.1
Beam version: 2.28.0
TFMA version: 0.24.3
TFT version: 0.24.1
TFX version: 0.24.0

Current Versions:
tfx-bsl==1.3.0
tensorflow-model-analysis==0.34.1
tensorflow-data-validation==1.3.0
tfx==1.3.2
tensorflow-metadata==1.2.0
ml-metadata==1.3.0
tensorflow-transform==1.3.0
tensorflow==2.6.2
pyarrow==2.0.0
apache-beam==2.32.0
tensorflow-serving-api==2.6.0
tensorflow-estimator==2.6.0

**Comment by sushreebarsa** [comment]
@FernandoDorado 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by FernandoDorado** [comment]
I've create a [COLAB ](https://colab.research.google.com/drive/1LC1B-wA_evEOi9X8vG2dYk02nVqyO3sT?usp=sharing) notebook in order to reproduce the error.

This is the [link ](https://drive.google.com/file/d/1nV7LGX5A8RroGh3ABPN6Z2agJs0IMsVM/view?usp=sharing) of the data, in case of problems with the data that I've previously loaded into the notebook.

**Comment by sushreebarsa** [comment]
@FernandoDorado Could you please try to execute your code on latest TF version `2.7.0` and have a look at the  [tf.sparse](https://www.tensorflow.org/api_docs/python/tf/sparse/to_dense) and [guide](https://www.tensorflow.org/guide/sparse_tensor) for reference ? Please let us know if it helps ? Thanks!

**Comment by FernandoDorado** [comment]
I took a look, but for now, don't work. Anyway, I see that the problem is more from my side, but I don't understand why the code works perfectly in the older version.
