### ISSUE TITLE
IDLE Time so long period.

### ISSUE THREAD

**Issue by berlinsaint** [tensorflow/tensorflow#53027]
TF version： v2.6, using distributed stragedy.

![image](https://user-images.githubusercontent.com/10629930/141219850-a5cfa6d5-270a-4974-9504-c559cc83b7cf.png)

![image](https://user-images.githubusercontent.com/10629930/141219519-1a3a9680-2bbe-4d3e-818e-d8028fe9ac2b.png)
![image](https://user-images.githubusercontent.com/10629930/141224856-57638193-3d17-4aa2-bc87-ecdc478dc217.png)

![image](https://user-images.githubusercontent.com/10629930/141223727-f40cb68d-cb44-495a-8ec2-4c3e0561ceb3.png)

training deepfm model by using cpu  without gpu train.

input files are tfrecords (15Mb per file)by spark. 

The key  train code like this:

![image](https://user-images.githubusercontent.com/10629930/141219749-49a5a82a-7c59-4605-8695-69c1fbf159b4.png)

why the idle time is so long, and is there some ways to enchance. my problems is that using multimirrored worker can't reduce training time....

**Comment by jvishnuvardhan** [comment]
@berlinsaint Can you please check with `TF2.7` and `tf-nightly` and let us know whether the issue is persisting with recent `TF` versions. Thanks!
