### ISSUE TITLE
Adding images with no bounding box to tflite model maker object detection dataset

### ISSUE THREAD

**Issue by topherbuckley** [tensorflow/tensorflow#53029]
I want to add images without any bounding boxes to the dataset used to train an object detector using tflite model maker. 

According to the [docs](https://cloud.google.com/vision/automl/object-detection/docs/csv-format) I can add 

>one row for each image with no bounding box (such as row 4 below).

```
 TRAIN,gs://folder/image1.png,car,0.1,0.1,,,0.3,0.3,,
 TRAIN,gs://folder/image1.png,bike,.7,.6,,,.8,.9,,
 UNASSIGNED,gs://folder/im2.png,car,0.1,0.1,0.2,0.1,0.2,0.3,0.1,0.3
 TEST,gs://folder/im3.png,,,,,,,,,
```

When doing so I am getting a ValueError "could not convert string to float", which is caused by an attempt to cast the None object to a float in the following [line](https://github.com/tensorflow/examples/blob/c930d0af2983ee438dcc005f9373188734f1624f/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py#L337-L338):

```
    xmin, ymin = float(line[3]) * width, float(line[4]) * height
```

How can I properly add such images without bounding boxes? Possibly a more important question; are these empty images even helpful towards retraining the model (i.e. does this give higher precision to the default classifier of None or Empty)?

**Comment by sushreebarsa** [comment]
@topherbuckley 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by topherbuckley** [comment]
## URL(s) with the issue:
https://cloud.google.com/vision/automl/object-detection/docs/csv-format

## Description of issue (what needs changing):
Unable to add images without any bounding boxes to the dataset used to train an object detector using tflite model maker.

### Clear description

I want to add images without any bounding boxes to the dataset used to train an object detector using tflite model maker. 

According to the [docs](https://cloud.google.com/vision/automl/object-detection/docs/csv-format) I can add 

>one row for each image with no bounding box (such as row 4 below).

```
 TRAIN,gs://folder/image1.png,car,0.1,0.1,,,0.3,0.3,,
 TRAIN,gs://folder/image1.png,bike,.7,.6,,,.8,.9,,
 UNASSIGNED,gs://folder/im2.png,car,0.1,0.1,0.2,0.1,0.2,0.3,0.1,0.3
 TEST,gs://folder/im3.png,,,,,,,,,
```

When doing so I am getting a ValueError "could not convert string to float", which is caused by an attempt to cast the None object to a float in the following [line](https://github.com/tensorflow/examples/blob/c930d0af2983ee438dcc005f9373188734f1624f/tensorflow_examples/lite/model_maker/core/data_util/object_detector_dataloader_util.py#L337-L338):

```
    xmin, ymin = float(line[3]) * width, float(line[4]) * height
```

How can I properly add such images without bounding boxes? Possibly a more important question; are these empty images even helpful towards retraining the model (i.e. does this give higher precision to the default classifier of None or Empty)?

### Correct links

Yes / Not applicable

### Parameters defined

Yes / Not applicable

### Returns defined

Yes / Not applicable

### Raises listed and defined

Yes

### Usage example

See Clear description

### Request visuals, if applicable

Not applicable

### Submit a pull request?

Happy to if I know what the expected handling of None entries should be in this case.

**Comment by sushreebarsa** [comment]
@topherbuckley 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by miaout17** [comment]
Adding @ziyeqinghan and @lu-wang-g, who may be able to answer TFLite model maker related questions.

**Comment by topherbuckley** [comment]
> @topherbuckley In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

You can just use the existing colab or notebook [here](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection) but add an additional line to the csv file without bounding box verticies. e.g.:

```
[existing csv entries above]
TEST,gs://cloud-ml-data/img/openimage/3/2520/3916261642_0a504acd60_o.jpg,,,,,,,,,
```

**Comment by Oliverhiggins93** [comment]
Hi, 
I have also ran into this problem when trying to add images without bounding boxes to a dataset. I am importing the images from a CSV stored locally on my harddrive, which was created using pandas, and am getting the same error. The images without bounding boxes have the format:

> TRAIN,filepath,,,,,,,,,

Can you confirm whether images without bounding boxes are able to be included in the training at all using model maker? I have been reading mixed opinions on this from stackoverflow etc.

**Comment by ziyeqinghan** [comment]
Hi, please don't use images without bounding boxes. We can't accept the image without bounding box for training. We will update our doc later. Thanks a lot
