### ISSUE TITLE
C++ memory leak after `Session::Close()` /  C++ equivalent to Python `reset_default_graph()` ?

### ISSUE THREAD

**Issue by beniz** [tensorflow/tensorflow#5302]
Using C++ API, memory (RAM) does not appear to be fully released after `Session::Close()` is called. 

See code snippet below. Running it within a loop eventually eats up all RAM and gets killed by system.

From reading around, I understand that the closing of the session does not release the underlying graph. In Python it seems that `reset_default_graph()` releases the graph resources.

Is there any equivalent to `reset_default_graph()` in C++ ?

I initially reported this question on the mailing list, https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/NG7n6emda78 with no echo, so posted as an issue here. My apologies if this isn't the right procedure.

Note:
GPU memory appears to not be released when looking it up with `nvidia-smi` but I believe it is an `nvidia-smi` problem as in practice the GPU memory appears to be reusable, so no problem on this side.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

http://stackoverflow.com/questions/35695183/tensorflow-memory-leak-even-while-closing-session
https://github.com/tensorflow/tensorflow/issues/1578
https://github.com/fchollet/keras/issues/2102
https://github.com/tensorflow/tensorflow/issues/700
https://github.com/tensorflow/tensorflow/issues/3106

### Environment info
Operating System:

Ubuntu 16.04 LTS

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
-rw-r--r-- 1 root root   560184 Sep  7 18:22 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep  7 18:22 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep  7 18:22 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Sep  7 18:22 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Sep  7 18:22 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 Sep 11 08:45 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 Sep 11 08:45 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 Sep 11 08:45 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Sep 11 08:45 /usr/local/cuda/lib64/libcudnn_static.a
```

### From source installation

1. The commit hash (`git rev-parse HEAD`)

```
5c1ca717e8ddd16b0be8410a798dc174380a600d
```

2. The output of `bazel version`

```
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
```
### Short code snippet

Put the code below into a loop, and RAM keeps on growing, replace `_inputLayer` and `_outputLayer` with proper network layer names, and `vtfinputs` is a `std::vector<tensorflow::Tensor>`.

```C++
tensorflow::GraphDef graph_def;
tensorflow::Status graphLoadedStatus = ReadBinaryProto(tensorflow::Env::Default(),graphFile,&graph_def);
tensorflow::SessionOptions options;
tensorflow::ConfigProto &config = options.config;
config.mutable_gpu_options()->set_allow_growth(true);
std::unique_ptr<tensorflow::Session> session = std::unique_ptr<tensorflow::Session>(tensorflow::NewSession(options));
tensorflow::Status session_create_status = session->Create(graph_def);                                                        
...                                                                               
tensorflow::Status run_status  = session->Run({{_inputLayer,*(vtfinputs.begin())}},{_outputLayer},{},&finalOutput)  /* runs file, results are what they should be, and are acquired via finalOutput. */
...
session->Close();                                                                                                          
session.reset();

/* RAM keeps building up if code above put into a loop */
```
### What other attempted solutions have you tried?

using ```session->Reset(options,containers)``` does not appear to compile (Reset does not exist for Session). Looking at ```session.h``` and ```direct_session.h``` I don't yet understand why this is the case.

**Comment by aselle** [comment]
Are you using tcmalloc? If not you should try that first. tcmalloc is a much more efficient malloc than default which prevents memory fragmentation which can easily look like a memory leak.

**Comment by beniz** [comment]
@aselle stunning, memory now perfectly handled! Many thanks for the quick answer.

I guess TF is developed with and thus for `tcmalloc` as default. Using various `resnet` architectures, the C++ code above was in practice not usable with standard `malloc`.

Slightly more info for the users possibly finding this thread in the future:
- TF + tcmalloc appears to be the way to go: https://github.com/tensorflow/tensorflow/issues/2384#issuecomment-228577365 and https://github.com/tensorflow/tensorflow/issues/3009#issuecomment-235993119
- some mitigated results, depending on number of threads, 
https://github.com/tensorflow/tensorflow/issues/3009#issuecomment-255633245

**Comment by lordadamson** [comment]
@beniz I love you

**Comment by beniz** [comment]
@lordadamson I love you back :)

**Comment by ktsumura** [comment]
Hi, I have the same problem (It looks like GPU doesn't release its memory after session.Close() is called, but apparently there are memory available as I can deploy a saved model in my app many times) and tcmalloc doesn't seem to solve the problem. I use Windows and I add tcmalloc library to my visual studio project using the following instruction. 
https://github.com/gperftools/gperftools/blob/master/README_windows.txt

Is there anything I can try?
Thank you,

**Comment by czcbangkai** [comment]
How to build with `tcmalloc` in `bazel`?

**Comment by samhodge** [comment]
@ktsumura I just got tcmalloc working under Windows, the difference is spectacular to say the least, memory is given back and shared between sessions, I love both @beniz  for pointing out what was becoming a show stopper for me, that I couldn't rely on GPU memory being given back in a tidy way.

**Comment by pawarrick** [comment]
@samhodge, could you post some C++ sample code or tips for setting up for the Windows case using tcmalloc?  I am also seeing steady memory creep after cycles of NewSession() ... Session.Close() in a heavy load context.  In my case, it is a CPU-only inference context (almost ready) for production use and this is a clear show stopper. Thanks

**Comment by samhodge** [comment]
There isn’t much to tell

See this


https://github.com/gperftools/gperftools/tree/master/vsprojects/libtcmalloc_minimal

Compile it as a shared library and link against it

There were a few modifications to make it a shared library after that close and reset actually worked.

**Comment by samhodge** [comment]
This should have everything you need 

https://github.com/gperftools/gperftools/blob/master/README_windows.txt

**Comment by samhodge** [comment]
Oh acttI did the whole archive trick to force all the symbols in there rather than the __tcmalloc thing the guide suggests

**Comment by pawarrick** [comment]
@samhodge Many thanks.

**Comment by samhodge** [comment]
@parwarrick

Glad to help, please respond if it actually works out for you

**Comment by pawarrick** [comment]
@samhodge Finally got around to trying this.  It was fairly straightforward. I needed to use the VC2015 property to "force" the __tcmalloc symbol to be included in the link.  The main benefit that I can observe are finer grained allocations.
