### ISSUE TITLE
unit test //tensorflow/compiler/xla/tests:local_client_aot_test fails to build on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53021]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Build fails with -
2021-11-10 12:32:55.390296: F tensorflow/compiler/xla/tests/local_client_aot_test_helper.cc:81] unsupported TARGET_CPU: aarch64

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --copt=-ffp-contract=off --cxxopt=-ffp-contract=off --verbose_failures -- //tensorflow/compiler/xla/tests/...

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /home/builder/1/tensorflow_build/tensorflow-git/tensorflow/compiler/xla/tests/BUILD:199:8: Executing genrule //tensorflow/compiler/xla/tests:local_client_aot_test_computation failed (Aborted): bash failed: error executing command 
(cd /home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow && \

exec env - \

PATH=/home/builder/.cache/bazelisk/downloads/bazelbuild/bazel-3.7.2-linux-arm64/bin:/home/builder/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \

PYTHON_BIN_PATH=/usr/bin/python3 \

PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \

TF2_BEHAVIOR=1 \

/bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/aarch64-opt/bin/tensorflow/compiler/xla/tests/local_client_aot_test_helper aarch64 > bazel-out/aarch64-opt/bin/tensorflow/compiler/xla/tests/local_client_aot_test_computation.o')
Execution platform: @local_execution_config_platform//:platform
2021-11-10 12:32:55.390296: F tensorflow/compiler/xla/tests/local_client_aot_test_helper.cc:81] unsupported TARGET_CPU: aarch64
/bin/bash: line 1: 729298 Aborted                 (core dumped) bazel-out/aarch64-opt/bin/tensorflow/compiler/xla/tests/local_client_aot_test_helper aarch64 > bazel-out/aarch64-opt/bin/tensorflow/compiler/xla/tests/local_client_aot_test_computation.o
INFO: Elapsed time: 579.863s, Critical Path: 253.00s
INFO: 5482 processes: 2358 internal, 3124 local.
FAILED: Build did NOT complete successfully

**Comment by mohantym** [comment]
Hi @Saduf2019  ! Could you look at this issue ?A  Pull request has been created at  #53022 .
