### ISSUE TITLE
built-in method __contains__ of dict object at 0xffff8b79a200  on aarch64， ubuntu20.04， tf：v2.5.0， py: v3.8.0

### ISSUE THREAD

**Issue by hecheng64** [tensorflow/tensorflow#53038]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution：Ubuntu 20.04):
- Mobile device ：aarch64
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): V2.5.0
- Python version: 3.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0

You can collect some of this information using our environment capture：

Python 3.8.11 (default, Aug  6 2021, 14:51:49) 
[GCC 10.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.keras import models,layers
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/mlsql/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/root/miniconda3/envs/mlsql/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/root/miniconda3/envs/mlsql/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 37, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/root/miniconda3/envs/mlsql/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 23, in <module>
    from tensorflow.python._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0xffff8b79a200> returned a result with an error set
>>>

**Comment by mohantym** [comment]
Hi @hecheng64 ! Could you try again upgrading your numpy using below command ?                                                                  `pip install numpy --upgrade` , Attaching Reference .[link1](https://issueexplorer.com/issue/google-research/ravens/15),[link2](https://github.com/freqtrade/freqtrade/issues/4281#issuecomment-770288601). Thanks!

**Comment by hecheng64** [comment]
@mohantym tks!
