### ISSUE TITLE
Unable to install Tensorflow through Pip due to no versions to install from

### ISSUE THREAD

**Issue by No767** [tensorflow/tensorflow#53031]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro and Linux Ubuntu 20.04 LTS (through WSL2)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Moto G Stylus (Running on Termux)
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.6.2, 2.7.0
- Python version: 3.10.0
- Installed using virtualenv? pip? conda?: Pip and Pipenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.4.153
- GPU model and memory: Nvidia Quadro P4000 (8GB VRAM)

**Describe the problem**
When installing tensorflow, it seems like it can't find the selected versions to install from. I've checked for any builds, and on pypi there seems to be existing builds for windows and linux. This also happens with `pip install tensorflow==2.7.0`.

Steps:
1. Install Python 3.10.0 
2. Upgrade pip to the latest version
3. Run `pip install tensorflow`
4. Wait until it returns that it can't find any versions for tensorflow to install from

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

When running `pip install tensorflow`, this is what it returns
```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by sanatmpa1** [comment]
@No767,

I've tried installing `TF 2.6.0` & `2.7.0` and both are working fine from my end. Please find the colab [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/08cdb47110981cf8c3a2c54345827a8c/53031.ipynb).

One catch that I found is, you've installed `Python 3.10` whereas the [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) of `TF 2.7.0` supports `Python 3.7 - 3.9` for both Windows and Ubuntu. So you can try downgrading to see if it helps.

Another alternate that you can try is, upgrading your pip version using `pip3 install --upgrade pip`

Let me know if any of it helps in resolving your issue. Thanks!

**Comment by No767** [comment]
Thanks for the response. I have also tested this on Python 3.8 and 3.9 and those seem working fine. I have also upgraded both pip3 and pip and seen the same result. I think it's due to 3.10 having issues, but I could be wrong.

**Comment by sanatmpa1** [comment]
@No767,

`Python 3.10` is released after release cut of `TF 2.7` and so its not supported yet. But you can follow this [thread](https://discuss.tensorflow.org/t/support-python-3-10/124/5) in TF Forum for updates on the same. Thanks!

**Comment by No767** [comment]
Thanks for the info. I'll keep track of the thread on the forums.

**Comment by mikila85** [comment]
py -3.9 -m pip install tensorflow

**Comment by Radulepy** [comment]
This helped me:

`pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl`

**Comment by Bayaniii** [comment]
> This helped me:
> 
> `pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl`

This was the only thing that worked for mince. Thank you!!

**Comment by IOPZHP** [comment]
> pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

You are my hero

**Comment by KKhujo** [comment]
> This helped me:
> 
> `pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl`

Bless you
