### ISSUE TITLE
The Problem of "UpSamples2D“ Layer when transfering h5 model file to tflite model file。

### ISSUE THREAD

**Issue by pengzhikang** [tensorflow/tensorflow#53033]
### 1. System information

- Windows 10
- pip package
- '2.3.1'

### 2. Code

    print('<-------------------------------------保存为tflite文件:------------------------------------>\n')
    new_model = tf.keras.models.load_model(pbfile)  # path to the SavedModel directory
    new_model.summary()
    converter = tf.lite.TFLiteConverter.from_keras_model(new_model)
    tflite_model = converter.convert()

    # Save the model.
    with open(tflitefile, 'wb') as f:
        f.write(tflite_model)

### 3. Confused of This Code's Result
The Above Code can Successfully converted h5 model to tflite model file, But I'm Confused of the result of tflite model
when "UpSamples2D“ Layer is showed in h5 model file as following:\
```
       |
      \|/
UpSampling2D
       |
      \|/
```
but is showed in tflite model file as following:
```
               |
              \|/
       |                  |
      \|/                |
    shape           
       |                  |
      \|/                |
  StridedSlice    
       |                  |
      \|/                |
      Mul             
       |                  |
      \|/                \|/
   ResizeNearestNeighbor
               |
              \|/
```
Problem: Why UpSampling2D is divided into two route calculations?

**Comment by mohantym** [comment]
Hi @pengzhikang! Could you update the Error stack trace in above template too?

**Comment by pengzhikang** [comment]
I have update comment, please Help me check the problem.

**Comment by mohantym** [comment]
Hi @sachinprasadhs! Could you look at this issue?

**Comment by sachinprasadhs** [comment]
Could you please provide the sample reproducible code to investigate on the issue. Thanks!
