### ISSUE TITLE
Why MutableDenseHashTableV2 in tensorflow 1.10 but gone in 1.15 ?

### ISSUE THREAD

**Issue by venusw2u** [tensorflow/tensorflow#53032]
There is some questions to ask about the file  tensorflow/core/ops/lookup_ops.cc, I see in v1.10 there is two MutableDenseHashTable, MutableDenseHashTable and MutableDenseHashTableV2, both with the same input and attributes but returning different types of output.

But in the version of 1.15, there is only MutableDenseHashTable with MutableDenseHashTableV2 deleted.

May I ask is there some OP which can substitute MutableDenseHashTableV2 in tensorflow 1.15 ?

**Comment by venusw2u** [comment]
@annarev @rohan100jain

**Comment by sushreebarsa** [comment]
@venusw2u We see that you are using `1.15` which is out of support window .Could you please upgrade to latest `TF v2.7.0 `and refer to the [page](https://www.tensorflow.org/api_docs/python/tf/lookup/experimental/MutableHashTable) for more details ? Let us know if it helps! Thank you!

**Comment by venusw2u** [comment]
But, we have already actually used tf1.15 in our production environment which can not be replaced easily. @sushreebarsa 
Could someone can ask this question ?

**Comment by sushreebarsa** [comment]
@venusw2u 
TF version 1.x is  not actively supported so could you please open this issue in [TF discussion forum](https://discuss.tensorflow.org/) as there is a larger community to get you the right help.Thank you!
