### ISSUE TITLE
The qna model demo does not return answer results

### ISSUE THREAD

**Issue by torressam333** [tensorflow/tensorflow#53037]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**Describe the current behavior**
In trying to run the qna model demo for TensorFlow.js I found that the answers always return an empty array. I did not alter any code I ran the out of the box demo direct from the Github page. I left the default information about Nikola Tesla in place and asked the question `Who is Tesla`. In the Chrome console I saw an Array with 0 results.

**Describe the expected behavior**
I expect answers to be returned by the model and output to the browser.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**
The reproducible example exists at the link provided from Github.

https://storage.googleapis.com/tfjs-models/demos/mobilebert-qna/index.html

Thank you.

**Comment by sushreebarsa** [comment]
@torressam333 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sushreebarsa** [comment]
@torressam333 This issue is more related to **TensorFlow.js** .Could you please post the issue in [TensorFlow.js](https://github.com/tensorflow/tfjs/issues) repo  ?Thank you!

**Comment by torressam333** [comment]
@sushreebarsa absolutely, I will do that. Thank you.

**Comment by sushreebarsa** [comment]
@torressam333 Thank you for the response! 
Please move this ticket to closed status  once you open the issue in [TF.js](https://github.com/tensorflow/tfjs/issues) repo.  Thanks!
