### ISSUE TITLE
Different variable declaration for `inner_shape` and `outer_shape` in `Slice updates` section of `tensor_scatter_nd_update` 

### ISSUE THREAD

**Issue by inpap** [tensorflow/tensorflow#53046]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update#slice_updates

## Description of issue (what needs changing):

The `inner_shape` and `outer_shape` variables should have the definition of :

`inner_shape = tensor.shape[index_depth:]`
`outer_shape = tensor.shape[:index_depth]`

### Clear description

In the first code block of the section the variables `inner_shape` and `outer_shape` are defined as:

`inner_shape = tensor.shape[:index_depth]`
`outer_shape = tensor.shape[index_depth:]`

In the fourth code block the same variables are defined as:

`inner_shape = tensor.shape[index_depth:]`
`outer_shape = tensor.shape[:index_depth]`

Note that in the two definitions the slices are used inversely for every variable.
However I believe that the definition of the fourth block is the correct one, namely

`inner_shape = tensor.shape[index_depth:]`
`outer_shape = tensor.shape[:index_depth]`

#### Code example

By replicating the example in the `Slice updates` section:

* the `outer_shape` should be 6 
* the `inner_shape` should be 3

that is achieved with the definition

`inner_shape = tensor.shape[index_depth:]`
`outer_shape = tensor.shape[:index_depth]`

Below I provide the code with the corresponding output

```
tensor = tf.zeros([6,3], dtype=tf.int32)
indices = tf.constant([[2],[4]])
num_updates, index_depth = indices.shape.as_list()
print(f"num_updates == {num_updates}, index_depth == {index_depth}")
print("")

print("The outer_shape should be 6 and the inner_shape should be 3")
print("")
      
print("If we use the definition of the first code block")
outer_shape_1st = tensor.shape[index_depth:]
inner_shape_1st = tensor.shape[:index_depth]
print(f"outer_shape is {outer_shape_1st[0]}, the inner_shape is {inner_shape_1st[0]}")      
print("")


print("If we use the definition of the forth code block")
outer_shape_4th = tensor.shape[:index_depth]
inner_shape_4th = tensor.shape[index_depth:]
print(f"outer_shape is {outer_shape_4th[0]}, the inner_shape is {inner_shape_4th[0]}")
```

![image](https://user-images.githubusercontent.com/35838787/141491130-d6f95932-214b-4057-8034-6652845c8894.png)

**Comment by tilakrayal** [comment]
@inpap ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.
