### ISSUE TITLE
Tensorflow using Intel UHD graphics instead of Nvidia

### ISSUE THREAD

**Issue by Abhinav-Bhattarai** [tensorflow/tensorflow#53049]
While training my model tensorflow is using the Intel UHD graphics instead of Nvidia RTX 2060. But the thing is even if utilization is 0% the RTX memory is being used.
tensorflow = 2.7.0
cudaa = 11.2
cudnn = 8.1
![Screenshot 2021-11-13 091117](https://user-images.githubusercontent.com/69339222/141604087-f1d98ea3-3713-48e6-8c0b-b3a6a39fbdf6.png)

**Comment by mohantym** [comment]
Hi @Abhinav-Bhattarai! Could you try again specifying GPU device  using [tf.device ](https://www.tensorflow.org/guide/gpu)?

**Comment by Abhinav-Bhattarai** [comment]
It started to use my Nvidia graphics for a bigger dataset
