### ISSUE TITLE
SpaceToDepth and DepthToSpace were not named as expected

### ISSUE THREAD

**Issue by dvtran221** [tensorflow/tensorflow#53045]
Hello,

In the API, we can give a name for the SpaceToDepth (or DepthToSpace) operator. However, I found that whatever the name I provided, tensorflow always fixes the name of SpaceToDepth as **tf.nn.space_to_depth** (and the same problem for DepthToSpace).

I'm using Windows 10, version 21H1, build 19043.1348 and Tensorflow 2.6

You can easily reproduce the issue with a minimal example as follows:
```
import tensorflow as tf
import json

def sample_network(input_layer):
    s2d = tf.nn.space_to_depth(input_layer, block_size=2, name="Space2Depth")
    d2s = tf.nn.depth_to_space(s2d, block_size=2, name="Depth2Space")
    return d2s

if __name__ == "__main__":
    input_net = tf.keras.Input(shape=(64, 64, 3), dtype=tf.float32)
    output = sample_network(input_net)
    model = tf.keras.Model(inputs=input_net, outputs=output)
    model_json = json.loads(model.to_json())
    with open("github_issue.json", "w") as f:
        json.dump(model_json, f, indent=2)
```
I would expect the name of these operators are Space2Depth and Depth2Space, but they are not.
![DepthToSpace](https://user-images.githubusercontent.com/12828532/141489907-6f5d4263-abf1-4ac7-b117-e650bcbae8ac.PNG)
![SpaceToDepth](https://user-images.githubusercontent.com/12828532/141489910-c9d24747-fcc6-459a-9899-a939655ed544.PNG)
Thank you for your consideration.

**Comment by mohantym** [comment]
Hi @dvtran221! Could you try again using [tf.name_scope](https://www.tensorflow.org/api_docs/python/tf/name_scope) in the above code ? Attaching  relevant threads for reference.[link1](https://colab.sandbox.google.com/github/zaidalyafeai/Notebooks/blob/master/WeightTransfer.ipynb),[link2](https://stackoverflow.com/questions/42708989/why-do-we-use-tf-name-scope/42712602). Thank you!

**Comment by dvtran221** [comment]
Hello @mohantym. I tried the tf.name_scope (as follows) but it does not change anything. I always observed the name tf.nn.space_to_depth and tf.nn.depth_to_space. As in the documentation, I expected they should be Space2Depth/s2d1 and Depth2Space/d2s1, but it's not the case.
```
def sample_network(input_layer):
    with tf.name_scope("Space2Depth"):
        s2d = tf.nn.space_to_depth(input_layer, block_size=2, name="s2d1")
    with tf.name_scope("Depth2Space"):
        d2s = tf.nn.depth_to_space(s2d, block_size=2, name="d2s1")
    return d2s
```

**Comment by mohantym** [comment]
Hi @dvtran221!
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) too.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by dvtran221** [comment]
Hello @mohantym 

I don't know if it relate to keras. I just discovered that if I disable the eager mode (by adding tf.compat.v1.disable_eager_execution()), the names are expected. I have an impression that tensorflow add the name of operator (e.g. tf.nn.space_to_depth) as a prefix. I don't know what happen but I hope this can give you some information. 
Finally, do I always need to post the issue on keras team?

```
import tensorflow as tf
import json

def sample_network(input_layer):
    s2d = tf.nn.space_to_depth(input_layer, block_size=2, name="Space2Depth")
    d2s = tf.nn.depth_to_space(s2d, block_size=2, name="Depth2Space")
    print(s2d.name, d2s.name)  # print out: Space2Depth:0 Depth2Space:0
    return d2s


if __name__ == "__main__":
    # Disable eager mode
    tf.compat.v1.disable_eager_execution() 

    input_net = tf.keras.Input(shape=(64, 64, 3), dtype=tf.float32)
    output = sample_network(input_net)
    model = tf.keras.Model(inputs=input_net, outputs=output)
    model_json = json.loads(model.to_json())
    with open("github_issue.json", "w") as f:
        json.dump(model_json, f, indent=2)
```

**Comment by mohantym** [comment]
@dvtran221 ! Thanks for the confirming the same . Please close issue this here as It will be tracked in Keras repo.
