### ISSUE TITLE
lite Benchmark_Model build failed on ARM platform without hexgon

### ISSUE THREAD

**Issue by sunshinemyson** [tensorflow/tensorflow#53043]
I'm trying to build benchmark_model with NXP M865 arm dev board, it was successfuly with v2.6.0, but failed with v2.7.0.

I found it was because this patch:
https://github.com/tensorflow/tensorflow/commit/feb49693266f444d5d8ce1a439ffbe7ff6e15e8a

This patch enabled hexgon delegate on all ARM platform, this is not make sense. Please consider rework it make sure it only compiled with platform with qualcomm chip.

**Comment by sushreebarsa** [comment]
@sunshinemyson Could you please refer to the [comment ](https://github.com/tensorflow/tensorflow/issues/52895#issuecomment-964268999) and open this issue in [TF forum](https://discuss.tensorflow.org/) where there is a larger community to help? Thanks!
