### ISSUE TITLE
TF/MLIR: lhlo to linalg conversion for BroadcastInDimOp - invalid IR

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#53041]
This is from the latest Tensorflow git repo 33dc8e4b4d4115b308cc55bd99ed5a9cd8b36b4c (Nov 10)

On the input:

```
  func @main(%in: memref<1x40x1xf16>, %out: memref<1x40x8xf16>) {
    "lmhlo.broadcast_in_dim"(%%in, %out) {broadcast_dimensions = dense<[0, 1, 2]> : tensor<3xi64>} : (memref<1x40x1xf16>, memref<1x40x8xf16>) -> ()
    return
  }
```

```
$ tf-opt -lhlo-legalize-to-linalg lmhlo.broadcast_in_dim.mlir 
lmhlo.broadcast_in_dim.mlir:7:5: error: 'memref.collapse_shape' op expected collapsed type to be 'memref<1x40xf16>', but got 'memref<1x40xf16, affine_map<(d0, d1) -> (d0 * 40 + d1)>>'
    "lmhlo.broadcast_in_dim"(%arg3, %arg5) {broadcast_dimensions = dense<[0, 1, 2]> : tensor<3xi64>} : (memref<1x40x1xf16>, memref<1x40x8xf16>) -> ()
    ^
lmhlo.broadcast_in_dim.mlir:7:5: note: see current operation: %2 = "memref.collapse_shape"(%arg3) {reassociation = [[0], [1, 2]]} : (memref<1x40x1xf16>) -> memref<1x40xf16, affine_map<(d0, d1) -> (d0 * 40 + d1)>>
```

The IR generated is invalid here. 

Separately, but related to the reshaping being introduced here: it was introduced by this commit:

```
commit 967782ff2a870fbc82e0db99c04eae78dded61d7
Author: Alexander Belyaev <pifon@google.com>
Date:   Fri Jun 5 06:40:28 2020 -0700

    [XLA][MLIR] Insert linalg.reshape when lowering LHLO BroadcastInDimOp.
    
    If size-1 dimensions require expansion, we insert linalg.reshape to get rid of them.
    
    PiperOrigin-RevId: 314918927
    Change-Id: I3e9cd380b93421858343ba299e659c0396ca7bcf
```

The reshaping isn't actually needed here. Was the reason for the reshape to preserve some canonical form for linalg.generic? In that case, adding a pattern on the latter would be a much better separation and placement of concerns without the need to add such code in the lowering pattern.

The rationale for inserting the reshape isn't clear and not summarized on the commit. The above example is just a broadcast via 1x40x1 -> 1x40x8 which can and was easily handled by mapping to `linalg.generic` prior to this commit (without any extra reshapes). The above commit split the converter templated for both hlo and lhlo while adding a large amount of code to introduce the reshape. The `linalg.reshape` itself was subsequently specialized to `collapse/expand` and moved to the memref dialect (`memref.collapse/expand_shape`). After a lowering to loops,  these reshapes on memrefs would get in the way of transformations like affine fusion unless they are eliminated via "in-placing"/special fusion (which is separately useful to anyway exist); in the absence of such inplacing, they would just get in the way of other downstream transformations like affine fusion for example. For the lmhlo.broadcast_in_dim lowering itself, the pre-existing lowering was simple.

CC: @pifon2a @joker-eph @jpienaar

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue?

**Comment by pifon2a** [comment]
@bondhugula 
Uday, is this still relevant? there is no lowering from LHLO to Linalg anymore.

**Comment by bondhugula** [comment]
As @pifon2a comments, this has now become moot.
