### ISSUE TITLE
How do I set up multi capabilities when run the configure file

### ISSUE THREAD

**Issue by Zhangts98** [tensorflow/tensorflow#53040]
gpu ： one gtx 1060
system: linux
source code: tensorflow/r1.15
expect capability: 5.2,6.0,6.1,7.0,7.5

I have only one gpu, but i want to set mutil capabilities  when build libtensorflow.

![企业微信截图_1636692704760](https://user-images.githubusercontent.com/61573829/141411648-b523408a-ca36-42b0-8956-4b87b02c4816.png)

**Comment by Zhangts98** [comment]
input   `5.2,6.0,6.1,7.0,7.5` or `[5.2,6.0,6.1,7.0,7.5]` or others?

**Comment by sushreebarsa** [comment]
@Zhangts98 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), 
Can you please share the output [please share text in place of screenshots which will help other users as well]
Thanks!
