### ISSUE TITLE
Concat tensor of[None, 192] with tensor of [1,128]

### ISSUE THREAD

**Issue by gunners009** [tensorflow/tensorflow#53052]
How to concatenate tensors of shapes [None, 128] with tensor of [1,128]. Here the first tensor will some data of unknown length and the second tensor is fixed tensor not dependant on data size. The final output should be of shape[None, 328]. This is a part of a neural network concatenation.

I tried 
`c = Concatenate(axis = -1, name = 'DQN_Input')([ a, b])`
but it gives error.
Here a.shape = (None, 192) and b.shape = (1,128) But this does not work. The error is

> ValueError: A Concatenate layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 192), (1, 128)]

**Comment by mohantym** [comment]
Hi @gunners009! Could you provide a simple stand alone code to replicate this issue?
