### ISSUE TITLE
Current implementation only supports equal length strides in the row and column dimensions.

### ISSUE THREAD

**Issue by beginner401** [tensorflow/tensorflow#53055]
When I use layers related  to DepthwiseConv2d operation, such as tf.keras.layers.SeparableConv2d, exception occurs like that: 'Current implementation only supports equal length strides in the row and column dimensions. [Op: DepthwiseConv2dNative]'. It means that i cannot use parameter 'strides' like [1, 2], however, that conflicts with the documentation, which allows 'strides'  with list format without mentioning that elements within the list should be the same.
I'm using TensorFlow 2.0.0, and I guess this bug exisits in 3D scenariothe and further edition.
![1](https://user-images.githubusercontent.com/94270103/141666163-3ba1d244-6efb-49b2-aa49-322d0b4d0889.png)

**Comment by mohantym** [comment]
Hi @beginner401! 
Could you please the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by beginner401** [comment]
**System information**
- Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-74-generic x86_64)
- TensorFlow 2.0.0 installed by anaconda
- gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2
**Describe the current behavior**
tf.keras.layers.SeparableConv2d do not support different value for rows and columns, caused by depthwiseConv2dNative not supporting different stride value for rows and columns.
**Describe the expected behavior**
tf.keras.layers.SeparableConv2d and depthwiseConv2dNative obviously should support different value for rows and columns.

**Standalone code to reproduce the issue**
e.g.
separable_conv2d = tf.keras.layer.SeparableConv2D(32, 3, [1, 2], depth_multiplier=3)

**Other info / logs**
![image](https://user-images.githubusercontent.com/94270103/141972774-8169ba95-81c4-409f-aa1d-1106f76f6cf3.png)

**Comment by mohantym** [comment]
Hi @beginner401 ! I could not replicate this issue from above stand alone code in TF 2.0/TF 2.7 (Colab) . Could you try again in latest version? Attaching [Gist ](https://colab.research.google.com/gist/mohantym/f6aa82ab4a4af6f26927f89e5532d170/github_53055.ipynb#scrollTo=64I8XIFWietp)for reference. Thanks!

**Comment by beginner401** [comment]
Hello, it seems that when I upgrade my tensorflow version to the latest 2.7, similar exceptions still occurs, the error-info takes a bit changes, but the problem stay the same. Have you ever call your layer after defining it? Only defining the layer doesn't work, you should try to at least call it once, Thanks!
I copy the same environment as 2.0, and just upgrade my tensorflow to the latest. By the way, my environment has installed tensorflow-probability, I suggest that makes no sense, but maybe that's valuable for you.
Below is the error info for the latest version:
![QQ截图20211118111138](https://user-images.githubusercontent.com/94270103/142345009-90608418-e267-4bcf-89ab-22b7ec33e543.png)

**Comment by mohantym** [comment]
Hi @beginner401 !
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) too.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by beginner401** [comment]
Hi @mohantym !
I have post this issue on keras-team/keras repo., and thanks for your guidance.
