### ISSUE TITLE
yolov5s-int8.tflite can not be run on the npu of I.MX8M Plus.

### ISSUE THREAD

**Issue by weili1457355863** [tensorflow/tensorflow#53056]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04)
- TensorFlow installation (pip package or built from source): pip package 
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Code

Provide code to help us reproduce your issues using one of the following options: python export.py --int8 --weights yolov5s.pt --include tflite

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

Model can be run on cpu of I.MX8M Plus, but can not be run on npu.

root@imx8mpevk:/usr/bin/tensorflow-lite-2.4.1/examples# ./benchmark_model --graph=/home/2tflite/yolov5s-int8.tflite --use_nnapi=true
 STARTING!
Log parameter values verbosely: [0]
Graph: [/home/yolov5test/yolov5s-int8.tflite]
Use NNAPI: [1]
NNAPI accelerators available: [vsi-npu]
Loaded model /home/yolov5test/yolov5s-int8.tflite
INFO: Created TensorFlow Lite delegate for NNAPI.
WARNING: Operator RESIZE_NEAREST_NEIGHBOR (v3) refused by NNAPI delegate: NNAPI does not support half_pixel_centers == true.
WARNING: Operator RESIZE_NEAREST_NEIGHBOR (v3) refused by NNAPI delegate: NNAPI does not support half_pixel_centers == true.
Explicitly applied NNAPI delegate, and the model graph will be partially executed by the delegate w/ 3 delegate kernels.
The input model file size (MB): 7.70178
Initialized session in 13.48ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
ERROR: NN API returned error ANEURALNETWORKS_OP_FAILED at line 4056 while running computation.

ERROR: Node number 284 (TfLiteNnapiDelegate) failed to invoke.

count=1 curr=13456030
	
Benchmarking failed.

**Comment by tilakrayal** [comment]
@weili1457355863 ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by tilakrayal** [comment]
Also Could you please update TensorFlow to the latest stable version v.2.7 and test your code and let us know if you are facing the same error. Thanks!
