### ISSUE TITLE
Error during training of EfficientDet-lite0 on GPU using the code model_maker_object_detection.ipynb

### ISSUE THREAD

**Issue by LittleDijkstraZ** [tensorflow/tensorflow#53057]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Code: [model_maker_object_detection.ipynb](https://github.com/tensorflow/tensorflow/blob/3beeeff5abbaf24562722c4cbe3af8614346286c/tensorflow/lite/g3doc/tutorials/model_maker_object_detection.ipynb)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab Pro Ubuntu 18.05
- TensorFlow installed from (source or binary): commands in the notebook (!pip install --upgrade tensorflow==2.5.0)
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.12
- CUDA/cuDNN version: 11.2
- GPU model and memory: P100-PCIE 16GB

## Current behavior
The line:
` 
model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)
`
will run into the following error:

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
	 [[Func/cond_6/then/_3438/input/_6900/_104]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_96848]

Function call stack:
train_function -> train_function

## Expected behavior
It should be able to train on GPU.

## Full Output

Epoch 1/50

UnknownError                              Traceback (most recent call last)
<ipython-input-5-187f39c1697e> in <module>()
----> 1 model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/object_detector.py in create(cls, train_data, model_spec, validation_data, epochs, batch_size, train_whole_model, do_train)
    285     if do_train:
    286       tf.compat.v1.logging.info('Retraining the models...')
--> 287       object_detector.train(train_data, validation_data, epochs, batch_size)
    288     else:
    289       object_detector.create_model()

/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/object_detector.py in train(self, train_data, validation_data, epochs, batch_size)
    156       return self.model_spec.train(self.model, train_ds, steps_per_epoch,
    157                                    validation_ds, validation_steps, epochs,
--> 158                                    batch_size, val_json_file)
    159 
    160   def evaluate(self,

/usr/local/lib/python3.7/dist-packages/tensorflow_examples/lite/model_maker/core/task/model_spec/object_detector_spec.py in train(self, model, train_dataset, steps_per_epoch, val_dataset, validation_steps, epochs, batch_size, val_json_file)
    270         callbacks=train_lib.get_callbacks(config.as_dict(), val_dataset),
    271         validation_data=val_dataset,
--> 272         validation_steps=validation_steps)
    273     return model
    274 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1181                 _r=1):
   1182               callbacks.on_train_batch_begin(step)
-> 1183               tmp_logs = self.train_function(iterator)
   1184               if data_handler.should_sync:
   1185                 context.async_wait()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    887 
    888       with OptionalXlaContext(self._jit_compile):
--> 889         result = self._call(*args, **kwds)
    890 
    891       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    948         # Lifting succeeded, so variables are initialized and we can run the
    949         # stateless function.
--> 950         return self._stateless_fn(*args, **kwds)
    951     else:
    952       _, _, _, filtered_flat_args = \

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   3022        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   3023     return graph_function._call_flat(
-> 3024         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   3025 
   3026   @property

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1959       # No tape is watching; skip to running the function.
   1960       return self._build_call_outputs(self._inference_function.call(
-> 1961           ctx, args, cancellation_manager=cancellation_manager))
   1962     forward_backward = self._select_forward_and_backward_functions(
   1963         args,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    594               inputs=args,
    595               attrs=attrs,
--> 596               ctx=ctx)
    597         else:
    598           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
	 [[Func/cond_6/then/_3438/input/_6900/_104]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/efficientnet-lite0/StatefulPartitionedCall/stem/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_96848]

Function call stack:
train_function -> train_function

**Comment by LittleDijkstraZ** [comment]
I just tested that this line can start training normally with tensorflow version 2.7.
Haven't tested other lines' compatiblity with tensorflow 2.7 yet.

**Comment by sushreebarsa** [comment]
@LittleDijkstraZ Could you please try to execute your code on latest stable TF version `2.7.0` and let us know if it is still an issue? Thanks!

**Comment by LittleDijkstraZ** [comment]
> @LittleDijkstraZ Could you please try to execute your code on latest stable TF version `2.7.0` and let us know if it is still an issue? Thanks!

Yeah, I had tested and there is no bug on that line anymore. 

> @LittleDijkstraZ Could you please try to execute your code on latest stable TF version `2.7.0` and let us know if it is still an issue? Thanks!

**Comment by LittleDijkstraZ** [comment]
> @LittleDijkstraZ Could you please try to execute your code on latest stable TF version `2.7.0` and let us know if it is still an issue? Thanks!

I had tested it on tensorflow 2.7.0 and there is no bug

**Comment by sushreebarsa** [comment]
@LittleDijkstraZ Thank you for the quick update! 
Could you please move this issue to closed status if it is resolved ? Thanks!
