### ISSUE TITLE
Move parameter `return_attention_weights` of `BaseAttentionLayer.call` to the constructor 

### ISSUE THREAD

**Issue by mishc9** [tensorflow/tensorflow#53058]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
Currently the method compute_output_shape is not implemented for layers derived from `BaseAttentionLayer`. Hence, it's impossible to use these layers with, for example, `TimeDistributed` wrapper (see [issue](https://github.com/keras-team/keras/issues/15515) Attention module not working with TimeDistributed layer).
To fix this, one could use eager mode or implement some workaround. Another way is to implement `compute_output_shape` method for `BaseAttentionLayer`. But `BaseAttentionLayer.call` method has a parameter `return_attention_weights` that adds attention weights tensor to values returned by attention layer, if set. It could change output shape of the layer after build.
Moreover, parameter `return_attention_weights` does not change a state of the layer when provided and is not saved to the object's attributes. So, it's impossible to implement `compute_output_shape` method while `return_attention_weights` belongs to the parameters of the call method. 

My suggestion is to change the API like this:

from 
```python3
class BaseDenseAttention(Layer):
    def __init__(self, causal=False, dropout=0.0,
                 **kwargs):
      ...
    
    def call(self,
             inputs,
             mask=None,
             training=None,
             return_attention_scores=False):
      ...
```

to

```python3
class BaseDenseAttention(Layer):
    def __init__(self, causal=False, dropout=0.0, return_attention_scores=False),  # move the parameter to the constructor
                 **kwargs):
      self.return_attention_scores=return_attention_scores
      ...
    
    def call(self, 
             inputs,
             mask=None,
             training=None,
             return_attention_scores=False):   # <- make it deprecated and add deprecation warning, remove in future versions
      ...

  def compute_output_shape(self, input_shape):
      # this function returns output shape using self.return_attention_scores as a conditional 
      ...

These changes make computation of output shape possible, but keep the possibility to return attention weights, if it's necessary for model debugging and/or analysis. For most use cases, it's enough to place `return_attention_scores` in a constructor of a class. Likewise, in other keras layers the parameters that change output shape of the layer are placed in a constructor of the layer (for example, `return_sequences` in recurrent layers). 
```

Related issues:
- [Unable to create](https://github.com/keras-team/keras/issues/15515) TimeDistributed wrapper for Attention layers
- [Feature request](https://github.com/tensorflow/tensorflow/issues/44127) for the parameter `return_attention_weights` to the `call` method. 

**Will this change the current api? How?**
Parameter return_attention_weights will be moved from call method of BaseAttentionLayer layers to constructor of BaseAttentionLayer. That allows to compute output shape of the attention layers and use them with, for example, TimeDistributed wrapper (that fixes previously mentioned issue).

**Who will benefit with this feature?**
Anyone who would use attention layers.

**Any Other info.**
It could break some of the tutorials/examples. Fixes may be required in the future: [this NMT tutorial](https://github.com/tensorflow/text/blob/master/docs/tutorials/nmt_with_attention.ipynb) uses `return_attention_scores` parameter.

**Comment by mohantym** [comment]
Hi @mishc9! 
Please post this feature request on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by mishc9** [comment]
@mohantym thank you, it seem that I've missed these changes. Will move PR to the Keras repository.
