### ISSUE TITLE
Error when Saving model with data augmentation layer on Tensorflow 2.7 

### ISSUE THREAD

**Issue by moumed** [tensorflow/tensorflow#53053]
I am getting an error when trying to save a model with data augmentation layers in last tensorflow version (2.7.0).

Here is the code of data augmentation:

> 
    input_shape_rgb = (img_height, img_width, 3)
    data_augmentation_rgb = tf.keras.Sequential(
      [ 
        layers.RandomFlip("horizontal"),
        layers.RandomFlip("vertical"),
        layers.RandomRotation(0.5),
        layers.RandomZoom(0.5),
        layers.RandomContrast(0.5),
        RandomColorDistortion(name='random_contrast_brightness/none'),
      ]
    )

Now I build my model like this:

> 
     input_shape = (img_height, img_width, 3)

    model = Sequential([
    layers.Input(input_shape),
    data_augmentation_rgb,
    layers.Rescaling((1./255)),
  
    layers.Conv2D(16, kernel_size, padding=padding, activation='relu', strides=1, 
       data_format='channels_last'),
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
  
    layers.Conv2D(32, kernel_size, padding=padding, activation='relu'), # best 4
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
  
    layers.Conv2D(64, kernel_size, padding=padding, activation='relu'), # best 3
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
  
    layers.Conv2D(128, kernel_size, padding=padding, activation='relu'), # best 3
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
  
    layers.Flatten(),
    layers.Dense(128, activation='relu'), # best 1
    layers.Dropout(0.1),
    layers.Dense(128, activation='relu'), # best 1
    layers.Dropout(0.1),
    layers.Dense(64, activation='relu'), # best 1
    layers.Dropout(0.1),
    layers.Dense(num_classes, activation = 'softmax')
     ])
  
     model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=metrics)
     model.summary()

Then after the training is done I just make:

> 
     model.save("./")

And I'm getting this error:

> 
      
      ---------------------------------------------------------------------------
      KeyError                                  Traceback (most recent call last)
      <ipython-input-84-87d3f09f8bee> in <module>()
      ----> 1 model.save("./")
      
      
      /usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in 
       error_handler(*args, **kwargs)
       65     except Exception as e:  # pylint: disable=broad-except
       66       filtered_tb = _process_traceback_frames(e.__traceback__)
       ---> 67       raise e.with_traceback(filtered_tb) from None
       68     finally:
       69       del filtered_tb
      
       /usr/local/lib/python3.7/dist- 
       packages/tensorflow/python/saved_model/function_serialization.py in 
       serialize_concrete_function(concrete_function, node_ids, coder)
       66   except KeyError:
       67     raise KeyError(
       ---> 68         f"Failed to add concrete function '{concrete_function.name}' to 
       object-"
       69         f"based SavedModel as it captures tensor {capture!r} which is 
       unsupported"
       70         " or not reachable from root. "
      
       KeyError: "Failed to add concrete function 
       'b'__inference_sequential_46_layer_call_fn_662953'' to object-based SavedModel as it 
       captures tensor <tf.Tensor: shape=(), dtype=resource, value=<Resource Tensor>> which 
       is unsupported or not reachable from root. One reason could be that a stateful 
       object or a variable that the function depends on is not assigned to an attribute of 
       the serialized trackable object (see SaveTest.test_captures_unreachable_variable)."

I inspected the reason of getting this error by changing the architecture of my model and I just found that the reason came from the `data_augmentation` layer since the `RandomFlip` and `RandomRotation` and others are changed from `layers.experimental.prepocessing.RandomFlip` to `layers.RandomFlip`, but still the error appears.

**Comment by tilakrayal** [comment]
@moumed ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by ngchanway** [comment]
I am also having the same issue with data augmentation layers. Interestingly, no error raised after removing `data_augmentation` from `model`.
```python
data_augmentation = tf.keras.Sequential(
    [
        tf.keras.layers.RandomFlip(),
        tf.keras.layers.RandomContrast(.1),
        tf.keras.layers.RandomRotation(.5, fill_mode='nearest'),
    ]
)

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, channels))
base_model = tf.keras.applications.ResNet50V2(
    input_shape=(IMG_SIZE, IMG_SIZE, channels),
    include_top=False,
)
x = data_augmentation(inputs)
x = tf.keras.applications.resnet_v2.preprocess_input(x)
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(dropout)(x)
outputs = tf.keras.layers.Dense(1)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer=optimizer, loss=loss, metrics=metrics)
```
As I encountered the same issue as @moumed without his complete code and dataset, I believe the issue is not specific to any dataset. Here's my `callbacks`.
```python
callbacks = [
    tf.keras.callbacks.TensorBoard(
        log_dir=tb_dir,
        histogram_freq=5,
        write_graph=True,
        write_images=True,
    ),
    tf.keras.callbacks.ModelCheckpoint(
        model_dir,
        monitor='val_accuracy',
        save_best_only=True,
    ),
]
model.fit(train_ds, epochs=100, callbacks=callbacks, validation_data=val_ds)
```

**Comment by moumed** [comment]
> @moumed , In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

like @ngchanway said the problem is not specific to any dataset, just creating and compiling the model with `data_augmentation_rgb ` and then saving the model raises the error, and when removing the data `data_augmentation_rgb ` the error disappears.  

I tried to test the provided colab in tensorflow core documentation with the provided `tf_flowers`dataset: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/data_augmentation.ipynb
the error appears when saving model with  the option 1 of Making the preprocessing layers part of the model.

**Comment by Yoan-D** [comment]
Posted a workaround [here](https://stackoverflow.com/questions/69955838/saving-model-on-tensorflow-2-7-0-with-data-augmentation-layer/69975495#69975495).

**Comment by tilakrayal** [comment]
@moumed ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)

**Comment by moumed** [comment]
> Posted a workaround [here](https://stackoverflow.com/questions/69955838/saving-model-on-tensorflow-2-7-0-with-data-augmentation-layer/69975495#69975495).

i am getting this error when trying to save with h5 format: 

> NotImplementedError: 
Layer RandomColorDistortion has arguments ['self', 'contrast_range', 'brightness_delta', 'gamma_correction', 'contrast_fact', 'crop_fact', 'variablity']
in `__init__` and therefore must override `get_config()`.

**Comment by Yoan-D** [comment]
@moumed you obviously have to override the config of your custom layer and add the parameters you are using. It has nothing to the with the original issue that you posted.

**Comment by moumed** [comment]
> @moumed you obviously have to override the config of your custom layer and add the parameters you are using. It has nothing to the with the original issue that you posted.

Here is the error when trying to load the model: 

> ValueError: Unknown layer: RandomColorDistortion. Please ensure this object is passed to the `custom_objects` argument.

**Comment by tilakrayal** [comment]
@moumed 
Please feel free to close this issue here as it has tracked in Keras repo.Thanks

**Comment by moumed** [comment]
this issue is moved to keras repo. Here is the link: https://github.com/keras-team/keras/issues/15699
