### ISSUE TITLE
Hợp nhất thành công một yêu cầu kéo có thể đóng vấn đề này

### ISSUE THREAD

**Issue by lam19892089** [tensorflow/tensorflow#53050]
https://github.com/tensorflow/tensorflow/blob/7e5b561df1f1dbcba9216e662c345eccb46b3048/tensorflow/go/session_test.go#L252

**Comment by tilakrayal** [comment]
@lam19892089 ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.
