### ISSUE TITLE
Errors in setting up GPU with CUDA and cuDNN

### ISSUE THREAD

**Issue by mshariful** [tensorflow/tensorflow#53054]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
TensorFlow installed from (source or binary): pip install tensorflow (in Anaconda)
TensorFlow version: 2.5.0
Python version: 3.8
Installed using virtualenv? pip? conda?: pip install tensorflow (in Anaconda)
CUDA/cuDNN version: CUDA: cuda_11.0.3_451.82_win10 and cuDNN: cudnn-11.0-windows-x64-v8.0.5.39
GPU model and memory: NVIDIA GeForce GTX 1660 Ti with Max-Q Design 6 GB

Dear All,

I have tried several CUDA and cuDNN versions for setting up my GPU without luck. Finally, I have used

**cuda_11.0.3_451.82_win10 and
cudnn-11.0-windows-x64-v8.0.5.39**

in Anaconda (Python 3.8.12). I see there are few positive results and 3 errors  (please see the full output below) as I executed this command:
```
import tensorflow
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

Error 1:
**2021-11-13 22:15:44.176901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found**

Error 2:
**2021-11-13 22:15:44.191130: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found**

Error 3:
**2021-11-13 22:15:44.191174: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU.** 

I tried to delete EVERYTHING from previous CUDA & cuDNN installations; I wonder if I had missed something!?

Could you please look into the following error messages and give me some suggestoins, please?

I am using Anaconda 3 in a Windows 10 laptop (Lenovo legion 7 slim with NVIDIA GeForce GTX 1660 Ti with Max-Q Design ).

TIA
Sheri

> >>> import tensorflow
> 2021-11-13 22:50:53.719861: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
> >>> from tensorflow.python.client import device_lib
> >>> print(device_lib.list_local_devices())
> 2021-11-13 22:51:32.529087: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-11-13 22:51:32.531546: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library nvcuda.dll
> 2021-11-13 22:51:33.925024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties:
> pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1660 Ti with Max-Q Design computeCapability: 7.5
> coreClock: 1.335GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
> 2021-11-13 22:51:33.925223: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
> 2021-11-13 22:51:33.932212: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublas64_11.dll
> 2021-11-13 22:51:33.932294: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cublasLt64_11.dll
> 2021-11-13 22:51:33.935750: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cufft64_10.dll
> 2021-11-13 22:51:33.936811: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library curand64_10.dll
> 2021-11-13 22:51:33.937346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
> 2021-11-13 22:51:33.939861: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cusparse64_11.dll
> 2021-11-13 22:51:33.940487: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
> 2021-11-13 22:51:33.940591: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> 2021-11-13 22:51:34.007417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2021-11-13 22:51:34.007508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
> 2021-11-13 22:51:34.008197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
> [name: "/device:CPU:0"
> device_type: "CPU"
> memory_limit: 268435456
> locality {
> }
> incarnation: 10668262798735033247
> ]
> >>>

**Comment by sushreebarsa** [comment]
@mshariful Could you please try using latest stable TF version **2.7.0** & refer to the [build from source ](https://www.tensorflow.org/install/source_windows).Please let us know if it helps? Thank you!

**Comment by mshariful** [comment]
Hi @sushreebarsa Thanks for your response. I will try to do that and inform you.

**Comment by mshariful** [comment]
Hi @sushreebarsa ,

I have gone through all the installations as described in [build from source](https://www.tensorflow.org/install/source_windows). Now after git cloning the tensorflow, as I execute the config.py file
I get repeatedly the following message; though I enter the correct paths of CUDA and cuDNN paths.

> C:\Users\endro\tensorflow>python ./configure.py
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is C:\Users\endro\AppData\Local\Programs\Python\Python39\python.exe]:


Found possible Python library paths:
  C:\Users\endro\AppData\Local\Programs\Python\Python39\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\endro\AppData\Local\Programs\Python\Python39\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: CUDA 11.5


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: cuDNN 8.3


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include


Could not find any cuda.h matching version 'CUDA 11.5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: CUDA 11.5


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: cuDNN


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\


Could not find any cuda.h matching version 'CUDA 11.5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: CUDA 11.5


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: cuDNN 8.3


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5


Could not find any cuda.h matching version 'CUDA 11.5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: CUDA 11.5


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: cuDNN 8.3


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA


Could not find any cuda.h matching version 'CUDA 11.5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: Traceback (most recent call last):
  File "C:\Users\endro\tensorflow\configure.py", line 96, in get_input
    answer = raw_input(question)
NameError: name 'raw_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\endro\tensorflow\configure.py", line 1475, in <module>
    main()
  File "C:\Users\endro\tensorflow\configure.py", line 1387, in main
    set_tf_cuda_version(environ_cp)
  File "C:\Users\endro\tensorflow\configure.py", line 898, in set_tf_cuda_version
    tf_cuda_version = get_from_env_or_user_or_default(environ_cp,
  File "C:\Users\endro\tensorflow\configure.py", line 600, in get_from_env_or_user_or_default
    var = get_input(ask_for_var)
  File "C:\Users\endro\tensorflow\configure.py", line 98, in get_input
    answer = input(question)  # pylint: disable=bad-builtin
KeyboardInterrupt
^C
C:\Users\endro\tensorflow>

C:\Users\endro\tensorflow>nano configure.py

C:\Users\endro\tensorflow>python ./configure.py
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is C:\Users\endro\AppData\Local\Programs\Python\Python39\python.exe]:


Found possible Python library paths:
  C:\Users\endro\AppData\Local\Programs\Python\Python39\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\endro\AppData\Local\Programs\Python\Python39\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Could not find any cudnn.h, cudnn_version.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: CUDA 11.5


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: cuDNN 8.3


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include, C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin, C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\lib\x64


Could not find any cuda.h matching version 'CUDA 11.5' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        'C:\ProgramData\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

Could you please tell me what I should do?

TIA
Sheri

**Comment by sushreebarsa** [comment]
@mshariful Could you please have a look at the instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) from here.
.Also, please follow the instructions  to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
Please, refer #36167, #42367,#42197,#45435
Could you please refer to the common [errors](https://www.tensorflow.org/install/errors) and let us know if it helps ?

If the issue still persists please post it on [Anaconda repo ](https://github.com/ContinuumIO/anaconda-issues/issues)as we do not support conda environment.
This issue is more suitable on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues) repo since its related to TF installation with Anaconda.
Please post it on Continuum Anaconda.
Thank you!

**Comment by mshariful** [comment]
Hi @sushreebarsa Thanks for your response. I will do these steps and inform you accordingly. TIA

**Comment by sushreebarsa** [comment]
@mshariful Could you please let us know if you have tried as per the [comment ](https://github.com/tensorflow/tensorflow/issues/53054#issuecomment-970084016)and if it is still an issue ? Thanks!

**Comment by mshariful** [comment]
Hallo @sushreebarsa, Thanks for your message. I






























Hallo @sushreebarsa , thanks for your message. I have got installed tensorflow through 'Anaconda' way very easily. 
Installing CUDA and cuDNN from Nvidia and setting up all the paths....it turned out to be a horror for me! What a frustrating experience it was!
