### ISSUE TITLE
Unit test //tensorflow/compiler/xla/service/cpu:vectorized_reduce_with_no_vector_registers_test fails on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53067]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git HEAD
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Test fails with
==================== Test output for //tensorflow/compiler/xla/service/cpu:vectorized_reduce_with_no_vector_registers_test:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CodegenReduceOnArchWithNoVectorRegisters
[ RUN      ] CodegenReduceOnArchWithNoVectorRegisters.Test
tensorflow/compiler/xla/service/cpu/vectorized_reduce_with_no_vector_registers_test.cc:85: Failure
Value of: _status_or_value7.status().ok()
  Actual: false
Expected: true
INTERNAL: TargetRegistry::lookupTarget failed: No available targets are compatible with triple "i686-none-android"
[  FAILED  ] CodegenReduceOnArchWithNoVectorRegisters.Test (13 ms)
[----------] 1 test from CodegenReduceOnArchWithNoVectorRegisters (13 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (13 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CodegenReduceOnArchWithNoVectorRegisters.Test

 1 FAILED TEST
================================================================================

**Describe the expected behavior**

Test passes

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): Add tag to allow test to be excluded on AARCH64 builds

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The test has a hard coded link to an x86 platform triple. But more than that, the test simply does not make sense on AARCH64 as it wants to test the behaviour if there were no vector registers available, but that is never going to be the case on AARCH64. So rather than attempting to fix the test, which would probably bypass any content on AARCH64, just add a tag to the definition to allow it to be excluded.

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by mohantym** [comment]
Hi @elfringham! This issue will be closed once PR #53068 is merged. Thanks!
