### ISSUE TITLE
TF2 does not load optimizer weights when restoring a saved model

### ISSUE THREAD

**Issue by janhartman** [tensorflow/tensorflow#53064]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, very little
- OS Platform and Distribution: Ubuntu 20.04 + Colab
- TensorFlow installed from: binary
- TensorFlow version: 2.7.0 (also happens on 2.6 and 2.5)
- Python version: 3.8.10

**Describe the current behavior**
When loading a saved (Keras) model, the optimizer weights are not restored. No error or warning is printed to make the user aware of this. [The documentation](https://www.tensorflow.org/guide/keras/save_and_serialize) also does not mention this. 

**Describe the expected behavior**
The optimizer weights should be restored automatically when loaded a saved model that was saved with its optimizer.

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
- [Notebook that shows the issue in TF2](https://colab.research.google.com/drive/1WyRoHFnNvoFocqm7jKC1CiH0KzzKh2lk?usp=sharing)
- [Notebook that shows that TF1 does not have the same issue](https://colab.research.google.com/drive/1HDcX9wauIuArJpBlTmfDRlk0Yhr3ngQT?usp=sharing)

**Other info / logs** 
This is a TF2 bug, it does not occur when using TF1 compat mode. It is a very significant bug - it means that models cannot be trained correctly if we want the training to be able to stop and resume. Workarounds such as setting the optimizer weights manually are buggy too - see https://github.com/keras-team/keras/issues/15298.

Issue https://github.com/tensorflow/tensorflow/issues/52346 is related, but not the same - that one is about using checkpoints and getting errors, while here I am using the SavedModel format and not getting any errors (where there should be one).

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/adfb6c1a41fabc878c649a9ff0380cd4/2-5.ipynb), [v2.7](https://colab.research.google.com/gist/tilakrayal/b3fe36096bf7c6de3962e66118cfcedf/2-7.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/822e39371a5f040a23f89154f287c7f9/nightly.ipynb).Please find the gist [1](https://colab.research.google.com/gist/tilakrayal/09f30740c3e521e9a03bba1c54b15141/2-5-tf1_optimizer_issue.ipynb), [2](https://colab.research.google.com/gist/tilakrayal/b23fced25b7cd6a7b615f8cfc9ecab47/2-7-tf1_optimizer_issue.ipynb) and [3](https://colab.research.google.com/gist/tilakrayal/250246bbf45194f4311b71885539eb85/nightly-tf1_optimizer_issue.ipynb) here.

**Comment by sachinprasadhs** [comment]
`Keras Savedmodel `does not save the optimizer's weight, instead it saves the optimizer's state to continue the training from where it is left off. Refer [this](https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model#usage) documentation on what does the saved model contains.
Also, you can see the optimizer config in the loaded model by `loaded.optimizer.get_config()`.

**Comment by janhartman** [comment]
@sachinprasadhs The docs you linked state:
> The SavedModel and HDF5 file contains:
>   - the model's configuration (topology)
>   - the model's weights
>   - the model's optimizer's state (if any)
>
> Thus models can be reinstantiated in the exact same state, without any of the code used for model definition or training.

I would argue the the optimizer's weights are its state. This is further corroborated by the last sentence - we can reinstantiate models in the exact same state. We cannot reach the exact same state if the optimizer's weights are not restored. 
Furthermore, the `model.save(include_optimizer=True)` function does actually save the optimizer weights. If you compare the size of two saved models, one with SGD and the other with Adam, you'll see that the one with Adam is 3x larger due to the extra optimizer weights.

As for `optimizer.get_config()`, its docs state:
> The same optimizer can be reinstantiated later (without any saved state) from this configuration.

This method only returns the optimizer's hyperparameters, which as the docs imply are not its state.

**Comment by sachinprasadhs** [comment]
Thanks for the details.
Since, development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo, would be happy to help there.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by janhartman** [comment]
@sachinprasadhs Thank you for the link. I actually just found a similar issue already being discussed in the Keras repo: https://github.com/keras-team/keras/issues/15512. I will move the discussion there.
