### ISSUE TITLE
AlreadyExistsError: File system for s3 already registered

### ISSUE THREAD

**Issue by Sanjaygowda66** [tensorflow/tensorflow#53060]
**System information**
- OS Platform and Distribution ): windows 10 
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.50
- Python version: 3.8
- Installed using: Conda

**Describe the problem**

** Not able to verify the scripts model_builder_tf2_test.py **

VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py')
!python {VERIFICATION_SCRIPT}

**tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registeredr**

2021-11-15 00:16:54.612239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-15 00:16:54.636703: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\Sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "C:\Users\sanjay\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
  File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\__init__.py", line 17, in <module>
    from tensorflow_io.python.api import *  # pylint: disable=wildcard-import
  File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\api\__init__.py", line 19, in <module>
    from tensorflow_io.python.ops.io_dataset import IODataset
  File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops\__init__.py", line 96, in <module>
    plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs")
  File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops\__init__.py", line 64, in _load_library
    l = load_fn(f)
  File "C:\Users\sanjay\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops\__init__.py", line 56, in <lambda>
    load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None
  File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow\python\framework\load_library.py", line 218, in register_filesystem_plugin
    py_tf.TF_RegisterFilesystemPlugin(plugin_location)
**tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered**

**Comment by Saduf2019** [comment]
@Sanjaygowda66 
Could you please try with cuda 11.0 and cudnn 8.0 as i see you have the error.
please refer to similar isues:[link](https://github.com/tensorflow/tensorflow/issues/48868#issuecomment-841396124),#43193,#50819,#44381.#44291

**Comment by Sanjaygowda66** [comment]
> **System information**
> 
> * OS Platform and Distribution ): windows 10
> * TensorFlow installed from (source or binary):
> * TensorFlow version: 2.50
> * Python version: 3.8
> * Installed using: Conda
> 
> **Describe the problem**
> 
> ** Not able to verify the scripts model_builder_tf2_test.py **
> 
> VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py') !python {VERIFICATION_SCRIPT}
> 
> **tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registeredr**
> 
> 2021-11-15 00:16:54.612239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found 2021-11-15 00:16:54.636703: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. Traceback (most recent call last): File "Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 25, in from object_detection.builders import model_builder File "C:\Users\Sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\builders\model_builder.py", line 37, in from object_detection.meta_architectures import deepmac_meta_arch File "C:\Users\sanjay\Anaconda3\envs\tensorflow\lib\site-packages\object_detection-0.1-py3.8.egg\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in import tensorflow_io as tfio # pylint:disable=g-import-not-at-top File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io__init__.py", line 17, in from tensorflow_io.python.api import * # pylint: disable=wildcard-import File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\api__init__.py", line 19, in from tensorflow_io.python.ops.io_dataset import IODataset File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops__init__.py", line 96, in plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs") File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops__init__.py", line 64, in _load_library l = load_fn(f) File "C:\Users\sanjay\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_io-0.22.0-py3.8-win-amd64.egg\tensorflow_io\python\ops__init__.py", line 56, in load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None File "C:\Users\sanjay\Anaconda3\envs\tensorflowEnv\lib\site-packages\tensorflow\python\framework\load_library.py", line 218, in register_filesystem_plugin py_tf.TF_RegisterFilesystemPlugin(plugin_location) **tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered**

**Comment by Sanjaygowda66** [comment]
> @Sanjaygowda66 Could you please try with cuda 11.0 and cudnn 8.0 as i see you have the error. please refer to similar isues:[link](https://github.com/tensorflow/tensorflow/issues/48868#issuecomment-841396124),#43193,#50819,#44381.#44291

I don't have GPU, I'm just loading pre-trained model checkpoints.

**I ran the below-mentioned code twice after restarting kernel on jupyter notebook** Since then I'm getting S3 already registered error whenever I ran verifying **model_builder_tf2_test.py** script 

And this is how I installed Tensorflow Object detection 
```
if os.name=='nt':
    url="https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/protoc-3.15.6-win64.zip"
    wget.download(url)
    !move protoc-3.15.6-win64.zip {paths['PROTOC_PATH']}
    !cd {paths['PROTOC_PATH']} && tar -xf protoc-3.15.6-win64.zip
    os.environ['PATH'] += os.pathsep + os.path.abspath(os.path.join(paths['PROTOC_PATH'], 'bin'))   
    !cd Tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=. && copy object_detection\\packages\\tf2\\setup.py setup.py && python setup.py build && python setup.py install
    !cd Tensorflow/models/research/slim && pip install -e . 
```

**Comment by jim2046** [comment]
I have similar problem.
OS Platform and Distribution ): windows 10
TensorFlow version: TensorFlow-gpu=2.4.1
Python version: 3.8
Installed using: Conda
cudatoolkit = 11.0.221
cuDNN = 8.0.4 for CUDA 11.0

python object_detection/builders/model_builder_tf2_test.py
2021-11-16 21:55:05.642660: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "D:\tf_train\models\research\object_detection\builders\model_builder.py", line 37, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
  File "D:\tf_train\models\research\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in <module>
    import tensorflow_io as tfio  # pylint:disable=g-import-not-at-top
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\__init__.py", line 17, in <module>
    from tensorflow_io.python.api import *  # pylint: disable=wildcard-import
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\api\__init__.py", line 19, in <module>
    from tensorflow_io.python.ops.io_dataset import IODataset
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 96, in <module>
    plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs")
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 64, in _load_library
    l = load_fn(f)
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 56, in <lambda>
    load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None
  File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow\python\framework\load_library.py", line 178, in register_filesystem_plugin
    py_tf.TF_RegisterFilesystemPlugin(plugin_location)
tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered

**Comment by tilakrayal** [comment]
@Sanjaygowda66 ,
Can you please try to test your code in latest stable v2.7 and let us know if the issue still persists.Please check this link for tested build [configurations](https://www.tensorflow.org/install/source_windows).

**Comment by Sanjaygowda66** [comment]
> @Sanjaygowda66 , Can you please try to test your code in latest stable v2.7 and let us know if the issue still persists.Please check this link for tested build [configurations](https://www.tensorflow.org/install/source_windows).

Thanks for your help, It's working completely fine with v2.7

**Comment by akzenith** [comment]
> > @Sanjaygowda66 , Can you please try to test your code in latest stable v2.7 and let us know if the issue still persists.Please check this link for tested build [configurations](https://www.tensorflow.org/install/source_windows).
> 
> Thanks for your help, It's working completely fine with v2.7

How did you upgrade it?
 I tried doing !pip install --upgrade tensorflow==2.7.0 but its showing version upto 2.6.2 only.
ERROR: No matching distribution found for tensorflow==2.7.0

Current specifications:
tensorflow              2.5.0.dev2021032900
Python                  3.6.5 :: Anaconda
ipykernel               5.5.6
protobuf                3.19.1
tensorflow-addons       0.12.1
tf-estimator-nightly       2.5.0.dev2021032501
pip                                 21.3.1
Keras-Preprocessing           1.1.2
jupyter-client          7.1.0
jupyter-core            4.9.1
Cython                  3.0a6

**Comment by Sanjaygowda66** [comment]
> > > @Sanjaygowda66 , Can you please try to test your code in latest stable v2.7 and let us know if the issue still persists.Please check this link for tested build [configurations](https://www.tensorflow.org/install/source_windows).
> > 
> > 
> > Thanks for your help, It's working completely fine with v2.7
> 
> How did you upgrade it? I tried doing !pip install --upgrade tensorflow==2.7.0 but its showing version upto 2.6.2 only. ERROR: No matching distribution found for tensorflow==2.7.0
> 
> Current specifications: tensorflow 2.5.0.dev2021032900 Python 3.6.5 :: Anaconda ipykernel 5.5.6 protobuf 3.19.1 tensorflow-addons 0.12.1 tf-estimator-nightly 2.5.0.dev2021032501 pip 21.3.1 Keras-Preprocessing 1.1.2 jupyter-client 7.1.0 jupyter-core 4.9.1 Cython 3.0a6

Just use `!pip install --upgrade tensorflow`, it will automatically upgrade to a newer version.

**Comment by akzenith** [comment]
> 

I tried that but it is upgrading to 2.6.2 not 2.7

**Comment by Sanjaygowda66** [comment]
> > 
> 
> I tried that but it is upgrading to 2.6.2 not 2.7

Maybe you should upgrade your python >3.7, mine was 3.9 or try reinstalling TensorFlow.

**Comment by akzenith** [comment]
> > > 
> > 
> > 
> > I tried that but it is upgrading to 2.6.2 not 2.7
> 
> Maybe you should upgrade your python >3.7, mine was 3.9 or try reinstalling TensorFlow.

Ok.

**Comment by Sanjaygowda66** [comment]
> > > > 
> > > 
> > > 
> > > I tried that but it is upgrading to 2.6.2 not 2.7
> > 
> > 
> > Maybe you should upgrade your python >3.7, mine was 3.9 or try reinstalling TensorFlow.
> 
> Ok.

[System requirements
Python 3.7–3.9
Python 3.9 support requires TensorFlow 2.5 or later.
Python 3.8 support requires TensorFlow 2.2 or later.](https://www.tensorflow.org/install/pip)

**Comment by Ashish-neo** [comment]
> I have similar problem. OS Platform and Distribution ): windows 10 TensorFlow version: TensorFlow-gpu=2.4.1 Python version: 3.8 Installed using: Conda cudatoolkit = 11.0.221 cuDNN = 8.0.4 for CUDA 11.0
> 
> python object_detection/builders/model_builder_tf2_test.py 2021-11-16 21:55:05.642660: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll Traceback (most recent call last): File "object_detection/builders/model_builder_tf2_test.py", line 25, in from object_detection.builders import model_builder File "D:\tf_train\models\research\object_detection\builders\model_builder.py", line 37, in from object_detection.meta_architectures import deepmac_meta_arch File "D:\tf_train\models\research\object_detection\meta_architectures\deepmac_meta_arch.py", line 28, in import tensorflow_io as tfio # pylint:disable=g-import-not-at-top File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io__init__.py", line 17, in from tensorflow_io.python.api import * # pylint: disable=wildcard-import File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\api__init__.py", line 19, in from tensorflow_io.python.ops.io_dataset import IODataset File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops__init__.py", line 96, in plugin_ops = _load_library("libtensorflow_io_plugins.so", "fs") File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops__init__.py", line 64, in _load_library l = load_fn(f) File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow_io\python\ops__init__.py", line 56, in load_fn = lambda f: tf.experimental.register_filesystem_plugin(f) is None File "C:\Users\jim\anaconda3\envs\tf2_gpu\lib\site-packages\tensorflow\python\framework\load_library.py", line 178, in register_filesystem_plugin py_tf.TF_RegisterFilesystemPlugin(plugin_location) tensorflow.python.framework.errors_impl.AlreadyExistsError: File system for s3 already registered

use gpu==2.5.1 i think it works.
