### ISSUE TITLE
full 8 bit quantization generates unreasonable quant_scale for uint8 on input tensor

### ISSUE THREAD

**Issue by danielriege** [tensorflow/tensorflow#53069]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.6.0

### 2. Code

```
def representative_dataset():
    for img in imgs: # img are shape (224,640,3)
        data = np.expand_dims(img, axis=0)
        yield [data.astype(np.float32)]
        
converter = tf.lite.TFLiteConverter.from_keras_model(model) # path to keras model
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8 
#converter.experimental_new_quantizer = False

tflite_quant_model = converter.convert()
open(f"converted_model.tflite", "wb").write(tflite_quant_model)
```
Keras Model: https://cloud.haw-hamburg.de/index.php/s/FPxeczAoaJJgMly (Password: tf)
Tensorflow Lite converted Model: https://cloud.haw-hamburg.de/index.php/s/m9RKnJdOtHg8K3I (Password: tf)

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

The conversion succeeds but the quant_scale provided by the 'input_details["quantization"]' on the input tensor seems wrong. It is set to 0.029... which would map my float32 [0.0-1.0] images to [0-34] (zero_point = 0). That are a lot of details gone on the input, which makes the model perform bad.

When I set the 'experimental_new_quantizer' to 'False', it geneartes 0.0039... for quant_scale and still 0 for zero_point. That would map my images to [0-255], but the invoke fails with an error, that the input tensor lacks data. 

To my knowledge, the quant_scale is calculated by (max-min) / quant_range. quant_range is 255 for uint8. Where does the min max come from? from the representative dataset? I have checked that my representative dataset does not go below 0.0 or above 1.0.

**Comment by xhae** [comment]
The latest recommended way is to use tf.int instead of tf.uint, is there any specific reason you're using uint?

**Comment by danielriege** [comment]
just for convenience. If I convert my model using int8, I still get 0.027 as scale, just with -128 as zero point. That maps my float32 [0.0, 1.0] to [-128, -91]. I am wondering why I am getting these scales. A color depth of around 37 is not usable in my case.

**Comment by danielriege** [comment]
When I try it on a different machine, I get a scale of 0.074 which is even worse. Any ideas?

**Comment by sachinprasadhs** [comment]
Could you please provide the code for the model part to analyze more on this issue.  
Refer to our post training quantization document for more details https://www.tensorflow.org/lite/performance/post_training_quantization

**Comment by danielriege** [comment]
What is the "model part"? The only thing needed is the provided code above to reproduce the problem. By checking the quant_scale you can already see that there is something off. Besides, the quant scale differs with different tensorflow versions on the same model.

**Comment by sachinprasadhs** [comment]
The Keras model which you have provided in the link here  https://cloud.haw-hamburg.de/index.php/s/FPxeczAoaJJgMly is not loading anything.
Could you please share the same Keras model information using the colab Gist. Thanks!
