### ISSUE TITLE
I want to convert tFLite model into PB save_model, can you help me?  

### ISSUE THREAD

**Issue by LMR2018** [tensorflow/tensorflow#53075]
I want to convert tFLite model into PB save_model, can you help me?  

After I transform the TFlite model of four output tensors into RKNN model, the data structure and result are completely different. Do you know why?

**Comment by tilakrayal** [comment]
@LMR2018 ,
Can you please take a look at this links [1](https://stackoverflow.com/questions/53664279/converting-tflite-to-pb) [2](https://coderedirect.com/questions/293517/converting-tflite-to-pb) and [3](https://www.tensorflow.org/lite/convert).It helps.Thanks

**Comment by LMR2018** [comment]
> @LMR2018， 你能看看这个链接[1 ](https://stackoverflow.com/questions/53664279/converting-tflite-to-pb) [2](https://coderedirect.com/questions/293517/converting-tflite-to-pb)和[3](https://www.tensorflow.org/lite/convert)吗。它有帮助。谢谢

import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

So this is normal, and then how do we convert to pb model ？

**Comment by LMR2018** [comment]
tensorflow_1.12/tensorflow/bazel-bin/tensorflow/contrib/lite/toco/toco -- 
output_file=coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.pb -- 
output_format=TENSORFLOW_GRAPHDEF --input_format=TFLITE -- 
input_file=coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite -- 
inference_type=FLOAT --input_type=FLOAT --input_array="" --output_array="" -- 
input_shape=1,450,450,3 --dump_grapHviz=./

It is successful to convert into PB model according to TOCO, but pb model cannot be converted into TFLite model or RKNN model again？So there's something wrong with him?

**Comment by tilakrayal** [comment]
@LMR2018 ,
We see that you are using tf version 1.12, 1.x is not actively supported, please update to v2.6 or 2.7 and let us know if you are using same issue.
