### ISSUE TITLE
how to control thread number in Tensorflow1.12?

### ISSUE THREAD

**Issue by warren-lei** [tensorflow/tensorflow#53078]
I am using [https://github.com/mlcommons/training](mlcommon/training) to train resnet50.
On my device, it is thread limitation.
So I want to control the thread number while trainging.
There are too many threads, As shown in the figure below.
![image](https://user-images.githubusercontent.com/17714376/141889577-41a39540-e6b2-413f-a7d9-2c7125a5c4c0.png)

**Comment by tilakrayal** [comment]
@warren-lei ,
We see that you are using tf version 1.12, 1.x is not actively supported, please update to 2.6 or 2.7 and let us know if you are using same issue.

**Comment by tilakrayal** [comment]
Also please take a look at this reference link [1](https://github.com/pudae/tensorflow-densenet/issues/7#issuecomment-351054685) and [2](https://github.com/tensorflow/models/issues/3176) with similar query.It helps.Thanks!
