### ISSUE TITLE
tflite::ops::builtin::BuiltinOpResolver resolver is causing crash in a webassembly application opened in Android chrome browser.

### ISSUE THREAD

**Issue by Jargon4072** [tensorflow/tensorflow#53079]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): Tensorflow lite (compiled for web assembly)
- TensorFlow version (or GitHub SHA if from source): (2.5.0)

**Standalone code to reproduce the issue** 
```
  void init(const char *api_key)
    {

        cout << "initilizing the init function"<< endl;
        const char *env = getenv("ENVIRONMENT");
        ENV = std::string(env);
        sdk_status = statuscode->running;
        
        cout << "initilizing step 2"<< endl;

    
        sdk_status = statuscode->success;

        auto landmark_predict_model_ = tflite::FlatBufferModel::BuildFromFile("data/face_detection_front_128x128_float32.tflite");
        if(!landmark_predict_model_){
            cout <<  "Failed to load model " << endl;
        }else{
                cout <<  "Model loaded " << endl;
        }
        cout <<  "start " << endl;
        // tflite::MutableOpResolver resolver;
        // RegisterSelectedOps(&resolver);
        tflite::ops::builtin::BuiltinOpResolver resolver;    //this is causing crash. 
        // std::unique_ptr<tflite::Interpreter> landmark_interpreter_;
        // tflite::InterpreterBuilder(*landmark_predict_model_, resolver)(&landmark_interpreter_);
        // landmark_interpreter_->AllocateTensors();
        // landmark_interpreter_->SetAllowFp16PrecisionForFp32(true);
        // landmark_interpreter_->SetNumThreads(4);

        cout << "initilizing step 3"<< endl;

    }
```

Also, please include a link to a GraphDef or the model if possible.
model file: tflite model from [here](https://drive.google.com/uc?export=download&id=1DOEH2xS_bGVXEsriNJkKE3my62ZH3FUl)

**Any other info / logs**
The crash is happening only in chrome running in mobile phones (tested on Android phone, Processor: snapdragon 710 and above). It is running properly in PC chrome browser.

**Comment by sushreebarsa** [comment]
@Jargon4072 Could you please try to execute your code on latest stable version of TF `2.7.0` and let us know if the issue still persists? Thank you!

**Comment by Jargon4072** [comment]
Hi @sushreebarsa. I will try it and let you by tomorrow. Thank you!

**Comment by sushreebarsa** [comment]
@Jargon4072 Could you please let us know if you have tried with TF v2.7.0 ? Please let us know the outcome .Thank you!

**Comment by Jargon4072** [comment]
> 

I am not able to build tflite for wasm. I have tried with version 2.6.1 (source : https://github.com/visualcamp/tensorflow) and it is still giving issues. I have tried bazel to build but there are two issues: 1. there is no proper instruction to build tflite for wasm, 2. if I am setting --config=wasm, it is giving an error that .bazelrc doesn't have any config for wasm. Can anyone please help me in builduing tf 2.7.0 for wasm?

**Comment by sachinprasadhs** [comment]
Could you please try again with the latest version with the required hardware compatibility.
https://www.tensorflow.org/lite/android/lite_build
