### ISSUE TITLE
Understanding TFLite interpreter output tensor names and ordering

### ISSUE THREAD

**Issue by kydonian** [tensorflow/tensorflow#53071]
### 1. System information

OS: Ubuntu 20.04 LTS
TF v2.4.1, built from source

### 2. Code

Can supply code later if necessary. Mostly just wanted ask a quick question to see if this is a known issue with a known solution.

### 3. Failure after conversion

It seems that TFLite model outputs are generically named and not ordered in a predictable way. If my original TF model has outputs like `["my_output_1", "my_output_2"]`, the TFLite model's outputs (e.g. obtained from `interpreter.outputs()`, `interpreter.output_tensor(idx)` will have names like `PartitionedCall:1` and `PartitionedCall:0`. These two outputs will correspond to the two outputs of the TF model, but their order may be permuted.

After searching the API as well as looking googling around a good amount, I was unable to find any information about
* How to tell, other than manually checking shapes and verified expected output values, which output is which.
* If there is a way to induce TFLite to keep the original output tensor names, or at least name the output tensors in a fashion that deterministically links them to their TF counterparts.

**Comment by xhae** [comment]
The recommended way to map Input/Output tensor information is to use SignatureDef, since SignatureDef name will be reserved between TF and TFLite conversion.

**Comment by kydonian** [comment]
@xhae Oh, nice, thanks. Looks like I'll need to upgrade to TF 2.5+ in order to get the signature list in the python API.

**Comment by dimiz51** [comment]
@xhae any examples on how you set that up?
