### ISSUE TITLE
Tensorflow environment variables breaking python import

### ISSUE THREAD

**Issue by jonwittmer** [tensorflow/tensorflow#53072]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Rocky Linux 8.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Both source and Pip
- TensorFlow version: 2.7.0, 2.4.1
- Python version: 3.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 11.4/ cudnn 8.2
- GPU model and memory: Nvidia A100 40 GB

What environment variables does TF look for when being imported in Python? I have 2 installations on my system: 1 is compiled from source (2.4.1) and stored in a user directory. This installation is only for linking to the C++ libraries. The second is installed with pip for use in Python. 

I discovered that by setting the environment variable `TF_LIB_PATH`, the Python installation fails to import Tensorflow with this error:
```
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/username/.local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

I use various environment variables to set the paths to my source compiled C++ libraries.

But, by not setting the environment variable `TF_LIB_PATH`, I am able to import Tensorflow. Is this expected behavior?

**Comment by jonwittmer** [comment]
I narrowed it down to `TF_LIB_PATH=<path to libtensorflow_cc.so>` being added to `LD_LIBRARY_PATH`. By removing this, I am able to import Tensorflow in Python again.

**Comment by SergioG-M** [comment]
I had the same problem with TF 2.8 and [jonwittmer's answer](https://github.com/tensorflow/tensorflow/issues/53072#issuecomment-969283744) was the solution
