### ISSUE TITLE
assets/vocab.txt; No such file or directory when loading/saving BERT models from TFhub

### ISSUE THREAD

**Issue by sfvaroglu** [tensorflow/tensorflow#53086]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 21.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Using models https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4 and https://tfhub.dev/google/experts/bert/wiki_books/squad2/2, `tf.saved_model.save` fails with error below.

```
Traceback (most recent call last):
  File "/home/tensorflow/test_load_save.py", line 30, in <module>
    tf.saved_model.save(model, model_path)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1280, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1327, in save_and_return_nodes
    builder_impl.copy_assets_to_destination_dir(asset_info.asset_filename_map,
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/builder_impl.py", line 781, in copy_assets_to_destination_dir
    file_io.copy(asset_source_filepath, asset_destination_filepath)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 589, in copy
    copy_v2(oldpath, newpath, overwrite)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 583, in copy_v2
    _pywrap_file_io.CopyFile(
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/tmps54xx3u2/assets/vocab.txt; No such file or directory
```

**Describe the expected behavior**
No errors

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
model_name = "./models/bert_en_uncased_L-12_H-768_A-12_4.tar.gz"

if tarfile.is_tarfile(model_name):
    with tempfile.TemporaryDirectory() as td:
        with tarfile.open(model_name, "r") as tar:
            tar.extractall(path=td)
        model = tf.saved_model.load(td)

with tempfile.TemporaryDirectory() as td:
    model_path = os.path.join(td, "saved_model")
    tf.saved_model.save(model, model_path)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @sfvaroglu! Could you try again by loading the model using using [hub API](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4) ?
