### ISSUE TITLE
Get an index of each worker in `ParameterServerStrategy `

### ISSUE THREAD

**Issue by moog-moloco** [tensorflow/tensorflow#53080]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
In the current implementation of ParameterServerStrategy, the `ClusterCoordinator.schedule method` assumes workers are equivalent and thus assumes the datasets on different workers are the same except they may be shuffled differently if they contain a `Dataset.shuffle` operation.

But i want to shard the dataset across the worker.
Let's assume that i want to make a dataset from generator function using `tf.data.Dataset.from_generator`. If there's a way to get the index of the environment where the function is running, it's possible for the generator to emit a different result by the task index. 
For now, i couldn't find a way to do it. so I filed this issue. (if there's a way, please let me know)

example code
```
NUM_WORKERS = 10
def example_generator(raw_dataset): 
 worker_idx = tf.??? # the feature i request. [0-9] should be returned as the num_worker = 10
 for i,d in enumerate(examples):
    if (i % NUM_WORKERS) == worker_idx:
      yield d
```

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this feature request ?

**Comment by sachinprasadhs** [comment]
You may have to look into [PerWorkerValues](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/coordinator/PerWorkerValues) which can help you. Thanks!

**Comment by moog-moloco** [comment]
@sachinprasadhs could you elaborate more please?

here's the explanation on the `PerWorkerValues` page
```
Currently, the only supported path to create an object of tf.distribute.experimental.coordinator.PerWorkerValues is through calling iter on a ClusterCoordinator.create_per_worker_dataset returned distributed dataset instance. The mechanism to create a custom tf.distribute.experimental.coordinator.PerWorkerValues is not yet supported.
```
the point i'm wondering about is how to get a worker index inside the function generating per-worker dataset.

**Comment by w-xinyi** [comment]
Hi, in short, we advise not to do so because 1. iterating through dataset but not using it (in this case, using 1/(#worker) of it) could be quite expensive and wasting resource 2. accessing the worker index inside the dataset creation function is very error prone and can't be achieved with public APIs.

**Comment by sushreebarsa** [comment]
@moog-moloco Could you please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/53080#issuecomment-1003533848)  above and let us know if it helps?Thanks!
