### ISSUE TITLE
Query regarding contributing

### ISSUE THREAD

**Issue by Naman23-coder** [tensorflow/tensorflow#53089]
i have reformatted all files in python directory of tensorflow with black and this is it's link:-https://github.com/Naman23-coder/tensorflow/tree/Naman23-coder ,should i open a pull request?

**Comment by Naman23-coder** [comment]
@mohantym I have closed this issue as my commits has 500k additions and 600k deletions so this might create bugs in tensorflow

**Comment by mohantym** [comment]
Hi @Naman23-coder ! Sorry for the late response! Please create an issue if you face any issue raising pull requests. Thanks!
