### ISSUE TITLE
tflite with C/C++ on Android, iOS, Linux, MacOS: Is it possible? How to do it?

### ISSUE THREAD

**Issue by fzyzcjy** [tensorflow/tensorflow#53087]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): n/a
- TensorFlow version: latest
- Python version: n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Hi thanks for the wonderful tf and tflite! I need to use it in Android and iOS apps, and also test my code on MacOS and Linux. Therefore, I need the C++ library of tflite on all these four platforms. I wonder what should I do to compile it?

p.s. I have searched and found related issues, but they seem to be outdated, so I create a new one. I have also read all documents, but get confused since most of them creates libs for java/swift/objc/c/..., instead of C++. I have even seen [doc saying](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c) C++ on ios must use bazel - but I do not know what part should use bazel - is it saying *all my code* must use bazel, or simply compile with bazel?

It is best if I can do it with C++. If not possible, I can accept C.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
n/a

**Any other info / logs**
n/a

**Comment by tilakrayal** [comment]
@fzyzcjy ,
Can you please take a look at this [link](https://www.tensorflow.org/install/lang_c) for installation of tensorflow for C.It helps.Thanks

**Comment by fzyzcjy** [comment]
@tilakrayal No I need tflite, not tensorflow.

In addition, it would be best if I can get *static* lib instead of *dynamic* lib.

**Comment by tilakrayal** [comment]
@fzyzcjy ,
Please refer this official [document](https://www.tensorflow.org/lite/guide/build_cmake) for the installation.Thanks

**Comment by fzyzcjy** [comment]
Thank you. I will have a try.
