### ISSUE TITLE
Can't run Hexagonal Delegate with Java API

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#53099]
I am following this doc: 
https://www.tensorflow.org/lite/performance/hexagon_delegate#add_the_shared_library_to_your_app
I did all 3 steps that are in Java API example (added the dependencies, and added Hexagonal Delegate as option when loading the interpreter), but when I run the interpreter I am getting the error:

`java.lang.UnsupportedOperationException: This Device doesn't support Hexagon DSP execution.`

I tried also all the suggestions that are in the bottom of the documentation provided by tensorflow: 
1. `adb shell cat /proc/cpuinfo | grep Hardware`  returns -> `Hardware        : Qualcomm Technologies, Inc APQ8098` , so I guess we are good here.
2.  I disabled SELinux enforce by running `adb shell setenforce 0` as super user, and when I run `adb shell getenforce` this returns -> `Permissive` , which means that the command worked.

Also another information: `adb shell getprop ro.board.platform` returns -> `msm8998`

I added 3 .so files that I generated by running the script `hexagon_nn_skel.run` ` v1.20.0.1`, in two main folders: `app/src/main/jniLibs/arm64-v8a` and `app/src/main/jniLibs/armeabi-v7a`, now I think that I am missing the part when we load these .so files. Does anybody have any idea ?

Update: 
More information related to issue: 
Device is running on Android 10, Snapdragon 835.
Also I saw that Hexagonal Delegate class is trying to load this native library 'tensorflowlite_hexagon_jni', but I can't find it in my project.

**Comment by mohantym** [comment]
Hi @sachinprasadhs! Could you look at this issue ?

**Comment by sachinprasadhs** [comment]
Could you please provide details about your device, and which Hexagon you are using and also check the similar issue [here](https://github.com/tensorflow/tensorflow/issues/39024). Thanks!

**Comment by karimnosseir** [comment]
Hi @ArtanBerisha1 
As long as the libraries are in the lib directory on the device it should work.
One reason we noticed before is `enableUncompressedNativeLibs` option, this optimization will cause a problem, so you need to disable it to make sure libraries are in the loadable directory
```
Note: If you're using App Bundle for publishing your Application, you might want to set android.bundle.enableUncompressedNativeLibs=false in the gradle.properties file.
```

After setting this option, verify that the libraries are in the libs directory on the device after installing the app.

Thanks

**Comment by pjpratik** [comment]
Hi @ArtanBerisha1 

Can you please refer to the above [comment](https://github.com/tensorflow/tensorflow/issues/53099#issuecomment-1144238783)?

Please add `android.bundle.enableUncompressedNativeLibs=false` in the gradle.properties file and let us know if it helps.

Thanks.
