### ISSUE TITLE
Same input of Models loaded on Apple M1 and GCP COS instance have different output vectors.

### ISSUE THREAD

**Issue by GabboM** [tensorflow/tensorflow#53097]
**Describe the current behavior**
When giving the same input to the same model loaded in 2 different architectures we expect the output to be "almost" identical. In my case I have an encoder model and when I give the same input in the 2 different systems listed below, I find the output vectors to be too different. In particular take a look at the first 6 entries of the output vector in the mentioned scenarios. In both cases inference is done on CPU

**System information 1**
- OS Platform and Distribution: 
      System Version: macOS 11.2.1 (20D75)
      Kernel Version: Darwin 20.3.0
- TensorFlow installed from: source
- TensorFlow version: v1.12.1-44683-gbcaa5ccc43e 2.4.0-rc0
- Python version: Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:57) [Clang 11.0.1 ] on darwin

output vector: `[2.94306199e-03, -1.54599566e-02,  1.47927711e-02, 4.50096987e-02, -1.71471871e-02,  7.42880329e-02, ...]`

**System information 2**
- OS Platform and Distribution: 
      Linux cff446c83c59 5.10.68+ #1 SMP Sat Nov 6 09:06:00 UTC 2021 x86_64 GNU/Linux
- TensorFlow installed from: source
- TensorFlow version: v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: Python 3.7.7 (default, Jun  9 2020, 17:58:51) [GCC 8.3.0] on linux

output vector: `[3.02067166e-03, -1.54666584e-02,  1.48272496e-02, 4.50056419e-02, -1.72036942e-02,  7.43456334e-02, ...]`

**Describe the expected behavior**
I expect the 2 vectors to be "almost" equal. The difference shown across the 2 systems is not acceptable.

**Comment by tilakrayal** [comment]
@GabboM ,
Could you please update TensorFlow to the latest stable version v2.7 and let us know if you are facing the same error. Thanks!

**Comment by GabboM** [comment]
Hey @tilakrayal thanks for your help.

I updated the `tensorflow-macos` version to `2.6.0` (that is the latest available in [pip](https://pypi.org/project/tensorflow-macos)) and indeed it looks like the problem is solved :
`[ 3.02065164e-03, -1.54666286e-02,  1.48272403e-02, 4.50056605e-02, -1.72036830e-02,  7.43457153e-02, ...]`

**Comment by tilakrayal** [comment]
@GabboM ,
Glad the issue is resolved for you, please feel free to move this to closed status.
