### ISSUE TITLE
Pylint `disable` should be followed by `enable`

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#5309]
There is a problem, which might have high severity:

A lot of files disable `pylint` messages, but don't enable them in the end -- this potentially might cause a missed warning if several files are imported, because `# pylint disable` is a global disable.

[Here are all the files that modify the `pylint` related to the `wildcard-import`](https://github.com/tensorflow/tensorflow/search?utf8=%E2%9C%93&q=pylint+disable+wildcard-import&type=Code)
[Here is an example file that doesn't revert the modifications](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/contrib/learn/python/learn/preprocessing/__init__.py)

There might be other wildcards that are disabled without reverting the changes

**Comment by drpngx** [comment]
Do you have a PR that you could send?

**Comment by zafartahirov** [comment]
I don't -- I might be able to look into the fix over the weekend

**Comment by drpngx** [comment]
Feel free to send CC me on the PR when you're ready! Thanks.
