### ISSUE TITLE
TFDS CLI Fails to Install: TFDS Command not Found 

### ISSUE THREAD

**Issue by Royston2708** [tensorflow/tensorflow#53102]
I am getting the following error when trying to install TFDS CLI. I am running the commands as per the documentation/tutorial on the tensorflow website (https://www.tensorflow.org/datasets/cli). I basically clicked on the open in colab button on the link I attached and tried to run the first cell with. the below listed commands and it failed.

>> !pip install -q tfds-nightly (Executes Successfully)
>> !tfds --version (Throws and Error)

Error Message:
Traceback (most recent call last):
File "/usr/local/bin/tfds", line 5, in
from tensorflow_datasets.scripts.cli.main import launch_cli
File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 40, in
from tensorflow_datasets.scripts.utils import flag_utils
ModuleNotFoundError: No module named 'tensorflow_datasets.scripts.utils'

NOTE:

On inspection of this path --> /usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/cli/main.py
I realize that there should exist a similar path --> usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/utils.py with the flag_utils function in it for the ~/cli/main.py script to import/call but it does not exist in the Google Colab directory and I think this is a bug as someone might have deleted it or replcated its functionality elsewhere without realizing that this script would break.

Here is a screenshot of the error. 

![image](https://user-images.githubusercontent.com/35322634/142265312-47476721-f27f-4fd2-b8a2-b5b2c185c693.png)

**Comment by mohantym** [comment]
Hi @Royston2708 ! I was able to print version using below command `print(tfds.__version__)`. For further assistance ,please create an issue in this[ repo](https://github.com/tensorflow/datasets/issues). Thanks!

**Comment by Royston2708** [comment]
Hi @mohantym that did not work for me. TFDS is not recognized. The issue is that I don't really care about finding out the version. The objective for me is to be able to create a new TFDS dataset that I can fine tune a model on in Tensorflow. In order to create a new dataset i need TFDS CLI but due to errors and bugs in the package the code is looking for a function called " flag_utils" in a package/script called "utils" that does not exist.  Are you trying to run this from a generic google account? Could you check what happens ig you to login to your personal google account then go to the colab website using the link I provided, click the run in colab button and try to run the code. It does not run for me and keeps giving me this error. I looked into the **/usr/local/lib/python3.7/dist-packages/tensorflow-datasets** path and there is no utils script or any mention of **def flag utils** in any of the scripts which means someone from Google deleted that script/function withouth realizing that it is being called elsewhere. 


<img width="1792" alt="Screen Shot 2021-11-18 at 12 10 02 PM" src="https://user-images.githubusercontent.com/35322634/142463258-005c65b0-02db-4636-abb5-caa43ac122a9.png">

**Comment by mohantym** [comment]
@Royston2708 ! You can print version after importing tensorflow_dataset as tfds through `"import tensorflow_datasets as tfds"`. Was able to replicate and resolve the issue.  Attaching [Gist](https://colab.research.google.com/gist/mohantym/4bc33436df8e554ceaa90ab12823d341/github_53102.ipynb#scrollTo=PsUbtvMAza51) for reference . Please create this issue in [Dataset repo](https://github.com/tensorflow/datasets) if you need further assistance . Thank you!
