### ISSUE TITLE
layers.LocallyConnected2D takes a lot of time to get initialized.

### ISSUE THREAD

**Issue by old-school-kid** [tensorflow/tensorflow#53104]
Tensorflow version: 2.7.0
layers.LocallyConnected2D takes an awful amount of time to build. The time taken to build increases dramatically with increasing size of input. 

> LocallyConnected2D in mode 1 takes 11.0303 seconds which is 43.0397 times Normal Conv2D
> LocallyConnected2D in mode 2 takes 6.6656 seconds which is 26.0089 times Normal Conv2D
> LocallyConnected2D in mode 3 takes 4.1878 seconds which is 16.3407 times Normal Conv2D

Here mode means implementation. 
Sample code to generate the problem can be found in this [notebook](https://colab.research.google.com/drive/1r--vgfn9_6UD-ff7pIYSRfNoZlXQN0gk?usp=sharing)

Moreover the sparse tensor generated in implementation mode 2 uses sparse_mat_mul which is deprecated.

**Comment by tilakrayal** [comment]
@old-school-kid ,
Please post this issue on keras-team/keras repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by tilakrayal** [comment]
@old-school-kid ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by old-school-kid** [comment]
Thank you! Shifted this to the [issue here](https://github.com/keras-team/keras/issues/15668#issue-1057314962)
