### ISSUE TITLE
Mixed precision doesn't work properly on NVIDIA A10G GPUs

### ISSUE THREAD

**Issue by goncinious** [tensorflow/tensorflow#53116]
A large U-Net 3D model configured with mixed precision fails with `No algorithm worked!` (see full `a10g.log` attached) when running inference on a NVIDIA A10G 20GB GPU (compute capability 8.6).

Using `tensorflow/tensorflow:nightly-gpu` Docker image, the error points to an out-of-memory issue (see full log `a10g_tf_nightly.log` attached):
```
No algorithm worked!  Error messages:
  Profiling failure on CUDNN engine 1#TC: RESOURCE_EXHAUSTED: Allocating 4718624784 bytes exceeds the memory limit of 4294967296 bytes.
  Profiling failure on CUDNN engine 1: RESOURCE_EXHAUSTED: Allocating 4718624784 bytes exceeds the memory limit of 4294967296 bytes.
         [[{{node model/conv3d_transpose_3/conv3d_transpose}}]] [Op:__inference_predict_function_1150]

```
I'm able to overcome the issue by using full precision instead (i.e by setting `mixed_precision.set_global_policy("float32")`.

The same model configured with mixed precision works fine on the previous generation T4 Tesla GPU (compute capability 7.5), which have even less GPU memory - 16GB (see full `t4_tesla.log` attached).

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1019-aws x86_64)
- TensorFlow installed from (source or binary): Official `tensorflow:latest-gpu` Docker image (`sha256@fc5eb0604722c7bef7b499bb007b3050c4beec5859c2e0d4409d2cca5c14d442`)
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8.10
- CUDA/cuDNN version: 11.2.1 / 8.1.0.77-1
- GPU model and memory: A10G (20G) and Tesla T4 (16G).
- NVIDIA driver: 470.82
- `nvidia-smi` outputs for both GPU types provided in attachments.

**Describe the expected behavior**

Mixed precision mode should not exhaust all GPU memory on the newest generation of NVIDIA A10G.

**Standalone code to reproduce the issue**
Steps to reproduce:

1. Start instance with A10G GPU

2. Start interactive Docker container and pass `test.py` (copy from [Colab](https://colab.research.google.com/drive/1Vg8LPNNrYJYAd4qjA_p_GuabzjQdqTwU?usp=sharing))
```
$ docker run --gpus all -v /path/to/test.py:/srv/test.py -it tensorflow/tensorflow:latest-gpu /bin/bash
```
3. Run script
```
python /srv/test.py
```
4. Repeat steps using Tesla T4 (no error obtained)

**Other info / logs**
[a10g.log](https://github.com/tensorflow/tensorflow/files/7565542/a10g.log)
[a10g_tf_nightly.log](https://github.com/tensorflow/tensorflow/files/7565545/a10g_tf_nightly.log)
[t4_tesla.log](https://github.com/tensorflow/tensorflow/files/7565547/t4_tesla.log)

[a10g_nvidia_smi.log](https://github.com/tensorflow/tensorflow/files/7565555/a10g_nvidia_smi.log)
[t4_tesla_nvidia_smi.log](https://github.com/tensorflow/tensorflow/files/7565558/t4_tesla_nvidia_smi.log)

**Comment by tilakrayal** [comment]
@goncinious ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by goncinious** [comment]
Thanks @tilakrayal, I've submitted to Keras' team as requested - https://github.com/keras-team/keras/issues/15678.

**Comment by tilakrayal** [comment]
@goncinious ,
Please feel free to move this issue to closed status as it has been tracking in keras repo.Thanks
