### ISSUE TITLE
Missing wheels for tflite-runtime on PyPI

### ISSUE THREAD

**Issue by rikardn** [tensorflow/tensorflow#53110]
Thanks for releasing tflite to PyPI! I have been using the tflite wheels from the coral release previously (https://github.com/google-coral/pycoral/releases), but having tflite on PyPI greatly simplifies usage as a dependency of other python packages.

The PyPI release however doesn't have wheels for all the major platforms as the pycoral release has. For example is `linux_x86_64` missing and there are no wheels for python 3.9.

It would also be really great to have wheels for python 3.10 (which i previously asked for here: https://github.com/google-coral/pycoral/issues/58) in PyPI.

**Comment by sushreebarsa** [comment]
@rikardn 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by sachinprasadhs** [comment]
`Pypi` wheels for `tflite-runtime` is maintained by `Coral Support`, you can track the progress in the issue https://github.com/google-coral/pycoral/issues/58 which you raised in pycoral repository. Thanks!

**Comment by hjonnala** [comment]
@rikardn coral team added packages to PyPI just to ensure somebody else doesn't take the library name. We don't ave any plans to update or maintain it. Please get the required wheels from [pycoral releases](https://github.com/google-coral/pycoral/releases)

**Comment by rikardn** [comment]
Thanks @sachinprasadhs and @hjonnala for the explanation. May I ask why there is no plan to have tflite on PyPI? This is the most standard way of distributing python packages and it would open up for other python packages to have it as a dependency.

**Comment by hjonnala** [comment]
Hi @rikardn tflite-runtime install is not recommended using pip for [Debian packages](https://www.tensorflow.org/lite/guide/python) as it can cause runtime failures. We recommend installing tflite-runtime using this [guide](https://www.tensorflow.org/lite/guide/python) or form [coral software center](https://coral.ai/software/#pycoral-api). As PyPI distribution does not work for all the platforms we  host all our supported wheels on GitHub instead. Also we(coral team) support for only limited platforms.
 
On a side note,  tflite-runtime v2.5.0 does not support python3.9. The latest version `tflite-runtime==2.5.0.post1` has wheels for python 3.9.
 
Please follow up [here](https://github.com/google-coral/pycoral/issues/58) for any further questions on `tflite-runtime`. Thanks!

**Comment by rikardn** [comment]
Thanks for explaining the situation.
