### ISSUE TITLE
@org_tensorflow//tensorflow/lite/toco:toco  build error

### ISSUE THREAD

**Issue by shiyalun** [tensorflow/tensorflow#53128]
**Hi,
I am trying to build the tensorflow code, When I execute this command：**

> bazel build -s --cxxopt="-std=c++14" -c dbg --cxxopt=-msse4 @org_tensorflow//tensorflow/lite/toco:toco  --experimental_repo_remote_exec

**， it gives this error:**
tensorflow/tensorflow/core/platform/default/BUILD:147:11: C++ compilation of rule '//tensorflow/core/platform/default:env_time' failed (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped)
tensorflow/core/platform/default/env_time.cc:26:17: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime(CLOCK_REALTIME, &ts);
                ^
1 error generated.
Target //tensorflow/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/xm20200921/project/tf260_tflite/kikaime-engine-model-15-so-tf260/dict_maker/tensorflow/tensorflow/core/framework/BUILD:1279:31 C++ compilation of rule '//tensorflow/core/platform/default:env_time' failed (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped)，

Thank you!

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you look at this issue?

**Comment by shiyalun** [comment]
**I use this command to solve the problem, but I have a new error.**

> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
**the new error as bellow:**

In file included from external/eigen_archive/Eigen/Core:15:
external/eigen_archive/Eigen/src/Core/util/DisableStupidWarnings.h:48:38: warning: unknown warning group '-Wimplicit-int-float-conversion', ignored [-Wunknown-warning-option]
    #pragma clang diagnostic ignored "-Wimplicit-int-float-conversion"
                                     ^
external/org_tensorflow/tensorflow/core/platform/status.cc:234:35: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
  if (state_ == nullptr) state_ = std::make_unique<State>();
                                  ^~~~~~~~~~~~~~~~
                                  absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(
                                                      ^
external/org_tensorflow/tensorflow/core/platform/status.cc:234:35: error: no template named 'make_unique' in namespace 'std'; did you mean 'absl::make_unique'?
  if (state_ == nullptr) state_ = std::make_unique<State>();
                                  ^~~~~~~~~~~~~~~~
                                  absl::make_unique
external/com_google_absl/absl/memory/memory.h:168:55: note: 'absl::make_unique' declared here
typename memory_internal::MakeUniqueResult<T>::scalar make_unique(

**Comment by shiyalun** [comment]
**To deal the error above, I replace 'std::make_unique' with 'absl::make_unique', but when I build,   I have a new error:**
ERROR: /private/var/tmp/_bazel_xm20200921/0cbb1a73cb22dbd58b43fa1332cd18ae/external/org_tensorflow/tensorflow/core/platform/default/BUILD:273:11: C++ compilation of rule '@org_tensorflow//tensorflow/core/platform/default:platform_port' failed (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/org_tensorflow/tensorflow/core/platform/default/port.cc:18:
In file included from external/org_tensorflow/tensorflow/core/platform/logging.h:20:
In file included from external/org_tensorflow/tensorflow/core/platform/types.h:21:
In file included from external/org_tensorflow/tensorflow/core/platform/bfloat16.h:21:
In file included from external/org_tensorflow/third_party/eigen3/Eigen/Core:1:
In file included from external/eigen_archive/Eigen/Core:15:
external/eigen_archive/Eigen/src/Core/util/DisableStupidWarnings.h:48:38: warning: unknown warning group '-Wimplicit-int-float-conversion', ignored [-Wunknown-warning-option]
    #pragma clang diagnostic ignored "-Wimplicit-int-float-conversion"
                                     ^
external/org_tensorflow/tensorflow/core/platform/default/port.cc:360:14: error: no matching constructor for initialization of 'tensorflow::port::MemoryInfo'
  MemoryInfo mem_info = {INT64_MAX, INT64_MAX};
             ^          ~~~~~~~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/core/platform/mem.h:62:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct MemoryInfo {
       ^
external/org_tensorflow/tensorflow/core/platform/mem.h:62:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
external/org_tensorflow/tensorflow/core/platform/mem.h:62:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
external/org_tensorflow/tensorflow/core/platform/default/port.cc:373:23: error: no matching constructor for initialization of 'tensorflow::port::MemoryBandwidthInfo'
  MemoryBandwidthInfo membw_info = {INT64_MAX};
                      ^            ~~~~~~~~~~~
external/org_tensorflow/tensorflow/core/platform/mem.h:67:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'long long' to 'const tensorflow::port::MemoryBandwidthInfo' for 1st argument
struct MemoryBandwidthInfo {
       ^
external/org_tensorflow/tensorflow/core/platform/mem.h:67:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'long long' to 'tensorflow::port::MemoryBandwidthInfo' for 1st argument
external/org_tensorflow/tensorflow/core/platform/mem.h:67:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
1 warning and 2 errors generated.
ERROR: /private/var/tmp/_bazel_xm20200921/0cbb1a73cb22dbd58b43fa1332cd18ae/external/org_tensorflow/tensorflow/lite/toco/BUILD:406:13 C++ compilation of rule '@org_tensorflow//tensorflow/core/platform/default:platform_port' failed (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 57 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 11.038s, Critical Path: 8.78s
INFO: 34 processes: 5 internal, 29 darwin-sandbox.
FAILED: Build did NOT complete successfully
