### ISSUE TITLE
How can I modify the layer parameters of Bert model at trainabel_variables?

### ISSUE THREAD

**Issue by 1148330040** [tensorflow/tensorflow#53129]
tensorflow：2.2
os：linux
I want to try to train a 12-layer Robert model and a 6-layer Robert model. In the process of training, I will calculate the average value of some layer parameters of the 12 layer Robert model and all layer parameters of the 6-layer Robert model, so as to see whether this method can distill knowledge。
This is the code for modifying layer parameters：
`bert6 = TFBertModel.from_pretrained('uer/chinese_roberta_L-6_H-768', output_hidden_states=True)
bert12 = TFBertModel.from_pretrained('uer/chinese_roberta_L-12_H-768', output_hidden_states=True)

for var in bert6.trainable_variables:
    if 'attention' in var.name:
        name = ''.join(var.name.split('/')[3:])
        for var2 in bert12.trainable_variables:
            if 'attention' in var2.name:
                name2 = ''.join(var.name.split('/')[3:])
                if name2 == name:
                    print("start var: ", var)
                    var.numpy = (var + var2) / 2
                    print("end var: ", var)
                    print("(var + var2) / 2: ", (var + var2) / 2)`

![1637313249(1)](https://user-images.githubusercontent.com/34124260/142597068-858ecb12-2975-49ee-b3bc-0eb6b3d4afae.png)

However, after checking the status before and after **var** average calculation, I found that it did not update successfully。
So I want to know if there is any way to solve this problem in tensorflow 2.2?
Thank you》

**Comment by tilakrayal** [comment]
@1148330040 ,
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!

**Comment by 1148330040** [comment]
This is not a bug. I just want to find a way to manually change the model layer parameters.

---Original---
From: ***@***.***&gt;
Date: Fri, Nov 19, 2021 22:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/tensorflow] How can I modify the layer parameters ofBert model at trainabel_variables? (Issue #53129)




 
@1148330040 ,
 Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tilakrayal** [comment]
@1148330040 ,
Kindly open a tf discussion forum issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
