### ISSUE TITLE
undefined reference to `tensorflow::str_util::EndsWith’

### ISSUE THREAD

**Issue by xjj210130** [tensorflow/tensorflow#53133]
On  centos 8
TensorFlow 2.6  installed from source.
Python 3.8.2
gcc version 8.4.1 20200928

First:  I build libtensorflow  use cmd: bazel build //tensorflow:libtensorflow_cc.so
second: I build example: tensorflow/tensorflow/examples/label_image/main.cc 

g++ -g  -std=c++14  -DLINUX -fpermissive  -fPIC -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H   -I/usr/local/include/ -I/opensource/tf/  -I/usr/local/include/eigen3   -I/opensource/tf/third_party -I /opensource/tf/third_party/eigen3  -c src/main.cc -o src/main.o

This is wrong message：
undefined reference to `tensorflow::str_util::EndsWith(absl::string_view, absl::string_view)'

undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, absl::string_view, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'

undefined reference to `tensorflow::strings::internal::CatPieces[abi:cxx11](std::initializer_list<absl::string_view>)'

however, I run cmd:
nm -Ca libtensorflow_cc.so |grep EndsWith
nm -Ca libtensorflow_framework.so

The function is in the lib. 
I use std=c++11, c++17 ,It doesn't work.
Any help?
Thanks.

**Comment by NiuKeke** [comment]
> 

How did you solve thie issue? I got the same issue just like you. thanks a lot.

**Comment by xjj210130** [comment]
@NiuKeke this problem caused  by the the 3rd code version. you should use the right version match the tensorflow needed.
