### ISSUE TITLE
Tensorflow datasets - Eurosat data installation issue - ConnectionError: HTTPConnectionPool(host='madm.dfki.de', port=80): Max retries exceeded with url: /files/sentinel/EuroSATallBands.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f44a745ec50>: Failed to establish a new connection: [Errno 110] Connection timed out'))

### ISSUE THREAD

**Issue by aashika-varma** [tensorflow/tensorflow#53139]
Hi,

I have been facing this issue while trying to download Eurosat dataset from Tensorflow datasets API. Is anyone experiencing the same issue since 11/19/2021?

**Code used in Jupyter notebook:**

builder = tfds.builder("eurosat/all")

**Error message:**

Downloading and preparing dataset eurosat (1.93 GiB) to /home/jovyan/tensorflow_datasets/eurosat/all/2.0.0...
Dl Completed...: 0 url [00:00, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Extraction completed...: 0 file [00:00, ? file/s]

/opt/conda/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    174             conn = connection.create_connection(
--> 175                 (self._dns_host, self.port), self.timeout, **extra_kw
    176             )

/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     95     if err is not None:
---> 96         raise err
     97 

/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     85                 sock.bind(source_address)
---> 86             sock.connect(sa)
     87             return sock

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    705                 headers=headers,
--> 706                 chunked=chunked,
    707             )

/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    393             else:
--> 394                 conn.request(method, url, **httplib_request_kw)
    395 

/opt/conda/lib/python3.7/site-packages/urllib3/connection.py in request(self, method, url, body, headers)
    238             headers["User-Agent"] = _get_default_user_agent()
--> 239         super(HTTPConnection, self).request(method, url, body=body, headers=headers)
    240 

/opt/conda/lib/python3.7/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1280         """Send a complete request to the server."""
-> 1281         self._send_request(method, url, body, headers, encode_chunked)
   1282 

/opt/conda/lib/python3.7/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1326             body = _encode(body, 'body')
-> 1327         self.endheaders(body, encode_chunked=encode_chunked)
   1328 

/opt/conda/lib/python3.7/http/client.py in endheaders(self, message_body, encode_chunked)
   1275             raise CannotSendHeader()
-> 1276         self._send_output(message_body, encode_chunked=encode_chunked)
   1277 

/opt/conda/lib/python3.7/http/client.py in _send_output(self, message_body, encode_chunked)
   1035         del self._buffer[:]
-> 1036         self.send(msg)
   1037 

/opt/conda/lib/python3.7/http/client.py in send(self, data)
    975             if self.auto_open:
--> 976                 self.connect()
    977             else:

/opt/conda/lib/python3.7/site-packages/urllib3/connection.py in connect(self)
    204     def connect(self):
--> 205         conn = self._new_conn()
    206         self._prepare_conn(conn)

/opt/conda/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    186             raise NewConnectionError(
--> 187                 self, "Failed to establish a new connection: %s" % e
    188             )

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f44a745ec50>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    755             retries = retries.increment(
--> 756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    757             )

/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    573         if new_retry.is_exhausted():
--> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    575 

MaxRetryError: HTTPConnectionPool(host='madm.dfki.de', port=80): Max retries exceeded with url: /files/sentinel/EuroSATallBands.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f44a745ec50>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-4-d5e677d3f673> in <module>
     13 print(builder)
     14 # Prepare the data.
---> 15 builder.download_and_prepare()
     16 
     17 

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    332           self._download_and_prepare(
    333               dl_manager=dl_manager,
--> 334               download_config=download_config)
    335 
    336           # NOTE: If modifying the lines below to put additional information in

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1028     super(GeneratorBasedBuilder, self)._download_and_prepare(
   1029         dl_manager=dl_manager,
-> 1030         max_examples_per_split=download_config.max_examples_per_split,
   1031     )
   1032 

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, **prepare_split_kwargs)
    869         prepare_split_kwargs)
    870     for split_generator in self._split_generators(
--> 871         dl_manager, **split_generators_kwargs):
    872       if splits_lib.Split.ALL == split_generator.split_info.name:
    873         raise ValueError(

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/image/eurosat.py in _split_generators(self, dl_manager)
    129   def _split_generators(self, dl_manager):
    130     """Returns SplitGenerators."""
--> 131     path = dl_manager.download_and_extract(self.builder_config.download_url)
    132     path = os.path.join(path, self.builder_config.subdir)
    133     return [

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py in download_and_extract(self, url_or_urls)
    372     with self._downloader.tqdm():
    373       with self._extractor.tqdm():
--> 374         return _map_promise(self._download_extract, url_or_urls)
    375 
    376   @property

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py in _map_promise(map_fn, all_inputs)
    413   """Map the function into each element and resolve the promise."""
    414   all_promises = utils.map_nested(map_fn, all_inputs)  # Apply the function
--> 415   res = utils.map_nested(_wait_on_promise, all_promises)
    416   return res

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    157         return tuple(mapped)
    158   # Singleton
--> 159   return function(data_struct)
    160 
    161 

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py in _wait_on_promise(p)
    397 
    398   def _wait_on_promise(p):
--> 399     return p.get()
    400 
    401 else:

/opt/conda/lib/python3.7/site-packages/promise/promise.py in get(self, timeout)
    510         target = self._target()
    511         self._wait(timeout or DEFAULT_TIMEOUT)
--> 512         return self._target_settled_value(_raise=True)
    513 
    514     def _target_settled_value(self, _raise=False):

/opt/conda/lib/python3.7/site-packages/promise/promise.py in _target_settled_value(self, _raise)
    514     def _target_settled_value(self, _raise=False):
    515         # type: (bool) -> Any
--> 516         return self._target()._settled_value(_raise)
    517 
    518     _value = _reason = _target_settled_value

/opt/conda/lib/python3.7/site-packages/promise/promise.py in _settled_value(self, _raise)
    224             if _raise:
    225                 raise_val = self._fulfillment_handler0
--> 226                 reraise(type(raise_val), raise_val, self._traceback)
    227             return self._fulfillment_handler0
    228 

/opt/conda/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    717             if value.__traceback__ is not tb:
    718                 raise value.with_traceback(tb)
--> 719             raise value
    720         finally:
    721             value = None

/opt/conda/lib/python3.7/site-packages/promise/promise.py in handle_future_result(future)
    842         # type: (Any) -> None
    843         try:
--> 844             resolve(future.result())
    845         except Exception as e:
    846             tb = exc_info()[2]

/opt/conda/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

/opt/conda/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/opt/conda/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

/opt/conda/lib/python3.7/site-packages/tensorflow_datasets/core/download/downloader.py in _sync_download(self, url, destination_path)
    229         response = urllib.request.urlopen(request, context=ca_verify['urllib'])
    230     else:
--> 231       response = session.get(url, stream=True)
    232       if response.status_code != 200:
    233         raise DownloadError('Failed to get url %s. HTTP code: %d.' %

/opt/conda/lib/python3.7/site-packages/requests/sessions.py in get(self, url, **kwargs)
    553 
    554         kwargs.setdefault('allow_redirects', True)
--> 555         return self.request('GET', url, **kwargs)
    556 
    557     def options(self, url, **kwargs):

/opt/conda/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543 
    544         return resp

/opt/conda/lib/python3.7/site-packages/requests/sessions.py in send(self, request, **kwargs)
    653 
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656 
    657         # Total elapsed time of the request (approximately)

/opt/conda/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='madm.dfki.de', port=80): Max retries exceeded with url: /files/sentinel/EuroSATallBands.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f44a745ec50>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by sushreebarsa** [comment]
@aashika-varma 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
