### ISSUE TITLE
Benchmark Operator Profiling with GPU

### ISSUE THREAD

**Issue by heeh** [tensorflow/tensorflow#53138]
Thanks for the great work.

The benchmark program on CPU and hexagon delegate shows detailed information on neural net operators.
However, GPU delegate shows only `TfLiteGpuDelegateV2` node.
(I believe this is a squashed operator that runs on the GPU.)

It is hard to see what's going on inside GPU here.
Would it be possible to see the internal of this operator like CPU and Hexagon? 
Or, am I missing anything?

# CPU

```adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_xnnpack=false &> 01_cpu_noxnn.txt```

```
...
Number of nodes executed: 64
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	       34	   266.475	    75.118%	    75.118%	     0.000	       34
	       DEPTHWISE_CONV_2D	       13	    83.740	    23.606%	    98.724%	     0.000	       13
	TFLite_Detection_PostProcess	        1	     3.579	     1.009%	    99.733%	     0.000	        1
	           CONCATENATION	        2	     0.483	     0.136%	    99.869%	     0.000	        2
	                LOGISTIC	        1	     0.233	     0.066%	    99.935%	     0.000	        1
	                 RESHAPE	       13	     0.232	     0.065%	   100.000%	     0.000	       13
```

# GPU
```adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_gpu=true --use_xnnpack=false &> 03_gpu_noxnn.txt```

```
...
Number of nodes executed: 2
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     TfLiteGpuDelegateV2	        1	    44.928	    90.775%	    90.775%	     0.000	        1
	TFLite_Detection_PostProcess	        1	     4.566	     9.225%	   100.000%	     0.000	        1
```

# Hexagon Delegate
```adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_xnnpack=false --use_hexagon=true --hexagon_profiling=true &> 05_hexagon.txt```
```
...
Number of nodes executed: 65
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	     Supernode_8x8p32to8	       34	  4690.936	    71.401%	    71.401%	     0.000	       42
	DepthwiseSupernode_8x8p32to8	       13	  1551.444	    23.615%	    95.016%	     0.000	       13
	         Requantize_8to8	        1	   113.790	     1.732%	    96.748%	     0.000	        2
	       QuantizedConcat_8	        1	    65.657	     0.999%	    97.747%	     0.000	        1
	   TfLiteHexagonDelegate	        1	    56.703	     0.863%	    98.610%	     0.000	        1
	                 Reshape	       13	    56.144	     0.855%	    99.465%	     0.000	       13
	      QuantizedSigmoid_8	        1	    30.509	     0.464%	    99.929%	     0.000	        1
	TFLite_Detection_PostProcess	        1	     4.651	     0.071%	   100.000%	     0.000	        1
```

**Comment by tilakrayal** [comment]
@heeh ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.

**Comment by heeh** [comment]
@tilakrayal Thanks for the response. Here you go!

- TensorFlow version: 2.8.0
- Ubuntu 20.04
- Bazel version: 3.7.2
- Android version:
  - SDK: 27
  - NDK: r21e
  - Android Build Tools: 28.0.3

Complete code: 
- Build and push benchmark tool
```bash
bazel build -c opt \
  --config=android_arm64 \
  tensorflow/lite/tools/benchmark:benchmark_model
```
- Connect your android device. Push the binary to your phone with adb push (make the directory if required):
```bash
adb push bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model /data/local/tmp
```

- Make the binary executable.
```bash
adb shell chmod +x /data/local/tmp/benchmark_model
```

- Execution on CPU
```bash
adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_xnnpack=false &> 01_cpu_noxnn.txt
```

- Execution on GPU
```bash
adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_gpu=true --use_xnnpack=false &> 03_gpu_noxnn.txt
```

- Execution on Hexagon Delegate
```bash
adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/detect.tflite --num_threads=4 --enable_op_profiling=true --use_xnnpack=false --use_hexagon=true --hexagon_profiling=true &> 05_hexagon.txt
```

The result is described on the original post.
I did not include hexagon setup since my question is about GPU Delegate.
Let me know if you need anything.
Thanks!

**Comment by heeh** [comment]
@tilakrayal @jvishnuvardhan 
Any updates on this issue? 
Thank you!

**Comment by multiverse-tf** [comment]
@impjdi, could you help with this issue? Thx!

**Comment by impjdi** [comment]
The GPU delegate hides away whether you can use OpenGL or OpenCL and does that selection under the hood.  In OpenCL, the APIs allow you to have op-level profiling numbers, but OpenGL doesn't offer this.  Thus, it's not possible to have this op-level profiling data.

If you're using OpenCL, you can play around with `//tflite/delgates/gpu/cl/testing/run_performance_profiling.sh` to get some op-level stats.
