### ISSUE TITLE
//tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark fails to build on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53130]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

//tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark fails to build

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --copt=-ffp-contract=off --cxxopt=-ffp-contract=off --copt=-Og --copt=-ggdb --cxxopt=-Og --cxxopt=-ggdb --verbose_failures -- //tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=161
INFO: Reading rc options for 'test' from /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'test' from /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'test' from /home/builder/1/tensorflow_build/tensorflow-git/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'test' from /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc:
  Inherited 'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Reading rc options for 'test' from /home/builder/1/tensorflow_build/tensorflow-git/.tf_configure.bazelrc:
  'test' options: --flaky_test_attempts=3 --test_size_filters=small,medium
INFO: Found applicable config definition build:short_logs in file /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition test:v2 in file /home/builder/1/tensorflow_build/tensorflow-git/.tf_configure.bazelrc: --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
INFO: Found applicable config definition build:nonccl in file /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc: --define=no_nccl_support=true
INFO: Found applicable config definition build:linux in file /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/builder/1/tensorflow_build/tensorflow-git/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/274f12a44c606ecd20152f3e63c4f186793d9a8c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/0e24cef9fbfb6ac93dd326d458b6bae5183aaa4b.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark (3 packages loaded, 1583 targets configured).
INFO: Found 1 test target...
ERROR: /home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/external/mkl_dnn_v1/BUILD.bazel:166:11: C++ compilation of rule '@mkl_dnn_v1//:mkl_dnn' failed (Exit 1): gcc failed: error executing command 
  (cd /home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/builder/.cache/bazelisk/downloads/bazelbuild/bazel-3.7.2-linux-arm64/bin:/home/builder/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
  /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/_objs/mkl_dnn/0/gemm.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/_objs/mkl_dnn/0/gemm.o' -iquoteexternal/mkl_dnn_v1 -iquotebazel-out/aarch64-opt/bin/external/mkl_dnn_v1 -isystem external/mkl_dnn_v1/include -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/include -isystem external/mkl_dnn_v1/src -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src -isystem external/mkl_dnn_v1/src/common -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src/common -isystem external/mkl_dnn_v1/src/common/ittnotify -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src/common/ittnotify -isystem external/mkl_dnn_v1/src/cpu -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src/cpu -isystem external/mkl_dnn_v1/src/cpu/gemm -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src/cpu/gemm -isystem external/mkl_dnn_v1/src/cpu/x64/xbyak -isystem bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/src/cpu/x64/xbyak -w -DAUTOLOAD_DYNAMIC_KERNELS '-ffp-contract=off' -Og -ggdb '-std=c++14' '-ffp-contract=off' -Og -ggdb -fexceptions -UUSE_MKL -UUSE_CBLAS -DDNNL_ENABLE_MAX_CPU_ISA -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/mkl_dnn_v1/src/common/gemm.cpp -o bazel-out/aarch64-opt/bin/external/mkl_dnn_v1/_objs/mkl_dnn/0/gemm.o)
Execution platform: @local_execution_config_platform//:platform
external/mkl_dnn_v1/src/common/gemm.cpp: In function 'dnnl_status_t dnnl_threadpool_interop_sgemm(char, char, dnnl::impl::dim_t, dnnl::impl::dim_t, dnnl::impl::dim_t, float, const float*, dnnl::impl::dim_t, const float*, dnnl::impl::dim_t, float, float*, dnnl::impl::dim_t, void*)':
external/mkl_dnn_v1/src/common/gemm.cpp:97:5: error: 'threadpool_utils' has not been declared
   97 |     threadpool_utils::activate_threadpool(
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp:101:5: error: 'threadpool_utils' has not been declared
  101 |     threadpool_utils::deactivate_threadpool();
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp: In function 'dnnl_status_t dnnl_threadpool_interop_gemm_u8s8s32(char, char, char, dnnl::impl::dim_t, dnnl::impl::dim_t, dnnl::impl::dim_t, float, const uint8_t*, dnnl::impl::dim_t, uint8_t, const int8_t*, dnnl::impl::dim_t, int8_t, float, int32_t*, dnnl::impl::dim_t, const int32_t*, void*)':
external/mkl_dnn_v1/src/common/gemm.cpp:109:5: error: 'threadpool_utils' has not been declared
  109 |     threadpool_utils::activate_threadpool(
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp:113:5: error: 'threadpool_utils' has not been declared
  113 |     threadpool_utils::deactivate_threadpool();
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp: In function 'dnnl_status_t dnnl_threadpool_interop_gemm_s8s8s32(char, char, char, dnnl::impl::dim_t, dnnl::impl::dim_t, dnnl::impl::dim_t, float, const int8_t*, dnnl::impl::dim_t, int8_t, const int8_t*, dnnl::impl::dim_t, int8_t, float, int32_t*, dnnl::impl::dim_t, const int32_t*, void*)':
external/mkl_dnn_v1/src/common/gemm.cpp:121:5: error: 'threadpool_utils' has not been declared
  121 |     threadpool_utils::activate_threadpool(
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp:126:5: error: 'threadpool_utils' has not been declared
  126 |     threadpool_utils::deactivate_threadpool();
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp: In function 'dnnl_status_t dnnl_threadpool_interop_gemm_bf16bf16f32(char, char, dnnl::impl::dim_t, dnnl::impl::dim_t, dnnl::impl::dim_t, float, const dnnl::impl::bfloat16_t*, dnnl::impl::dim_t, const dnnl::impl::bfloat16_t*, dnnl::impl::dim_t, float, float*, dnnl::impl::dim_t, void*)':
external/mkl_dnn_v1/src/common/gemm.cpp:134:5: error: 'threadpool_utils' has not been declared
  134 |     threadpool_utils::activate_threadpool(
      |     ^~~~~~~~~~~~~~~~
external/mkl_dnn_v1/src/common/gemm.cpp:138:5: error: 'threadpool_utils' has not been declared
  138 |     threadpool_utils::deactivate_threadpool();
      |     ^~~~~~~~~~~~~~~~
Target //tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark failed to build
INFO: Elapsed time: 2.945s, Critical Path: 2.14s
INFO: 71 processes: 57 internal, 14 local.
FAILED: Build did NOT complete successfully
//tensorflow/core/kernels/mkl:mkl_matmul_op_benchmark           FAILED TO BUILD

FAILED: Build did NOT complete successfully

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by sushreebarsa** [comment]
@elfringham This issue will be closed once the PR is merged .Thanks!

**Comment by cfRod** [comment]
thanks!

**Comment by sushreebarsa** [comment]
@elfringham Could you please let us know if we can close this issue as the PR is merged ?Thanks!

**Comment by elfringham** [comment]
All good now thanks.
