### ISSUE TITLE
replace private grpc with tensorflow's grpc

### ISSUE THREAD

**Issue by TheGreatRandall** [tensorflow/tensorflow#53137]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos-7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary(pip download & conda install)
- TensorFlow version: 2.3.0
- Python version:3.8.11
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am an undergraduate research from the Ohio State University. My group is focusing on optimizing grpc(v1.38.0). Right now, we want to fills our optimized grpc into tensorflow to increase the performance of distributed trainning. However, the problem is we don't know how to modify the configuration to let tensorflow using our optimized grpc. I would very appreciate your help and please let me know if you need further information. Thank you!
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @TheGreatRandall ! Could you please post this query on TF Forum /Stackoverflow as this is not a bug feature request. Attaching Relevant threads for your reference though.[ link1](https://discuss.tensorflow.org/t/about-how-grpc-works-on-tensorflow/4723/3),[link2](https://rubikscode.net/2020/02/24/deploying-machine-learning-models-pt-3-grpc-and-tensorflow-serving/). Thanks!
