### ISSUE TITLE
Cannot install tensorflow-gpu==2.3.0rc0

### ISSUE THREAD

**Issue by jmudy** [tensorflow/tensorflow#53142]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04.5 LTS` (Google Colab)
- TensorFlow version: `tensorflow-gpu 2.3.0rc0`
- Python version: `Python 3.7.12`
- Installed using virtualenv? pip? conda?: `pip`
- CUDA/cuDNN version: CUDA Version: `11.2`. Cuda compilation tools, release `11.1`, `V11.1.105`
- GPU model and memory: `NVIDIA Tesla K80`

**Describe the problem**

I get the following error when trying to install tensorflow-gpu in version `2.3.0rc0`:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.3.0rc0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow-gpu==2.3.0rc0

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`pip install tensorflow-gpu==2.3.0rc0`

**Comment by arshPratap** [comment]
@jmudy sir, you might have to make sure the tensorflow version you are trying to install is a valid version. The  reason for the above error is that the distribution you are  tryingto install does not exist. I would suggest you take a look at the current gpu distributions that are available [here](https://www.tensorflow.org/install/source#gpu) and install the version that you feel is appropriate for you. Also I would suggest taking a look at the tensorflow [installation section](https://www.tensorflow.org/install) for a smoother and easier installation experience.Feel free to let the community know about the progress on your tensorflow  issue here.Thanks !
