### ISSUE TITLE
Python TFlite not using multiple threads for float inference with xnnpack

### ISSUE THREAD

**Issue by kodonnell** [tensorflow/tensorflow#53146]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Not really.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry Pi 64 bit.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pi Zero 2 W
- TensorFlow installed from (source or binary): Source.
- TensorFlow version (use command below): 365a3b68471f158defc3aea79a25fdaa56be4ac8 (i.e. few days old)
- Python version: 3.7
- Bazel version (if compiling from source): cmake 3.16.3
- GCC/Compiler version (if compiling from source): gcc (Debian 8.3.0-6) 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

I've trained MobileNet v3 Small using Tensorflow Object Detection API - models [here](https://github.com/tensorflow/tensorflow/files/7576019/models.zip). When I infer with `./linux_aarch64_benchmark_model --graph=models/mobilenetv3_224x224_FLOAT.tflite --num_threads=4 --use_xnnpack=true` I'm happy - around 25ms inference. Running with 1 thread is 57ms, 2 is 35ms, and 3 is 27ms, which is all expected. However, when I run the same tests with the simple script below, I'm getting 56-57ms seconds for any number of threads. Given this is similar to the single threaded performances from the benchmark tool, it'd imply that only a single thread is being used in python. Note that I am seeing `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.` which seems to imply XNNPACK is being used (though I've also seen that log in the benchmark before it later on complaining and not using XNNPACK - I don't see that here, but I can't seem to get more logging.)

Lastly, it's worth noting that if I use a quantized model in Python, it behaves as expected (i.e. faster with more threads, and matches the benchmark tool). Also, while I compiled the pip package with the provided scripts, I tested the wheel from [here](https://wiki.seeedstudio.com/reTerminal_ML_TFLite/), and had the same issue which is at least another data point.

**Describe the expected behavior**

I would expect to see similar behaviour with fp32 inference as with quantized i.e. increased performance with more threads. And I would expect it to match the benchmark tool.

**Standalone code to reproduce the issue**

```python
import time

import numpy as np
from tflite_runtime.interpreter import Interpreter

interpreter = Interpreter("models/mobilenetv3_224x224_FLOAT.tflite", num_threads=4)
interpreter.allocate_tensors()
for _ in range(10):
    t0 = time.time()
    interpreter.invoke()
    print(int((time.time() - t0) * 1000))
```

**Other info / logs** NA

**Comment by multiverse-tf** [comment]
Thx for reporting this issue! We will look into this and get this fixed asap.

**Comment by multiverse-tf** [comment]
@kodonnell, I noticed that you performed the experiments on Raspberry Pi 64 bit. Could you re-compile your pip with an additional bazel flag "--define=tflite_with_xnnpack=true" which explicitly enables the xnnpack-by-default feature, and then re-run your test program?

Based on the latest [bazel BUILD rule](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/BUILD#L703-L718), I'm afraid xnnpack-by-default isn't enabled on Raspberry Pi 64 bit. There was [an earlier attempt](https://github.com/tensorflow/tensorflow/commit/b36bc5b0d44a4aa6b1d98aefc835737c4bf16b35) to enable this feature on more platforms, but it's [rolled back](https://github.com/tensorflow/tensorflow/commit/31994539956beac283c064effd0885033a33ab4c) due to some issues that were found later internally.

**Comment by kodonnell** [comment]
Thanks @multiverse-tf - as above, I compiled with cmake, which enables xnnpack by default (and, as above, there’s strong evidence to support xnnpack being used). Note I just built aarch64 I.e. independent of raspberry pi.

**Comment by multiverse-tf** [comment]
@kodonnell, thanks again for clarification! I failed to reproduce the issue on my side with the [Python label image example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/python) on a Linux machine (where I explicitly turned on XNNPACK-by-default feature).

To help debug the issue further (as you did compilation on your own :-)), could you change the tensorflow  lite source code as follows to add more logs:
* Change [TFLITE_LOG](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/subgraph.cc#L427) here in tensorflow/lite/core/subgraph.cc to TFLITE_LOG_PROD.
* Log the [`context_->recommended_num_threads`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/interpreter.cc#L326) here and the resulted `delegate_ptr` value (i.e. simply logging delegate_ptr.get() value itself) by using TFLITE_LOG_PROD?

Afterwards, pls recompile tflite, re-run your test program and share the log? Many thanks!

**Comment by zichuan-wei** [comment]
still can't reproduce the error on the latest tip, running XNNPACK on 1 - 4 threads results in: 39.441ms, 19.834ms, 14.066ms and 11.099ms respectively, matching expected behaviour

**Comment by Byte247** [comment]
I have the same error. In python all 4 threads use 80%+ CPU Util, while in c++ also 4 threads are created but only one of them uses 60% while the others stay below 10%. Here is my Issue: https://github.com/tensorflow/tensorflow/issues/110160
