### ISSUE TITLE
dataset as_numpy_iterator() failing when using RaggedTensor

### ISSUE THREAD

**Issue by kingatlas** [tensorflow/tensorflow#53149]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.6 / docker tensorflow:2.5.0-gpu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0 and 2.6.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Calling `as_numpy_iterator()` on a `tf.data.Dataset` having `RaggedTensorSpec` will fail with the error:

```
  File "/Users/xx/Library/Caches/pypoetry/virtualenvs/sandbox-hasb3I3q-py3.6/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4685, in to_numpy
    numpy = x._numpy()  # pylint: disable=protected-access
AttributeError: 'RaggedTensor' object has no attribute '_numpy'
```
Sample code to reproduce the issue:

```python
import tensorflow as tf

def gen():
    ragged_tensor = tf.ragged.constant([[1, 2], [3]])
    yield 42, ragged_tensor

dataset = tf.data.Dataset.from_generator(gen, output_signature=(
                tf.TensorSpec(shape=(), dtype=tf.int32),
                tf.RaggedTensorSpec(shape=(2, None), dtype=tf.int32)))

iterator = dataset.as_numpy_iterator()
print(iterator.next()) # failing with: AttributeError: 'RaggedTensor' object has no attribute '_numpy'

```
This regression has been brought by this [commit](https://github.com/tensorflow/tensorflow/commit/3e98cbc83e73c834d14137b98da0a26d1d8b7034)

**Describe the expected behavior**

Returning the numpy iterator as for `Tensor` without failing.
OR: providing a workaround or alternative usage to make it work.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
I was able to reproduce the issue in tf v2.6, v2.7 and nightly.Please find the gist of [here](https://colab.research.google.com/gist/tilakrayal/93dcf6f3dcb0a16929c09ea0bc6e3657/untitled122.ipynb).

**Comment by sanatmpa1** [comment]
@kingatlas,

Instead of using `iterator = dataset.as_numpy_iterator()` , Can you try using this `iterator = iter(dataset)` to iterate through the dataset? You can take a look at the working [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/174830194b1985587d44230372faa66f/untitled122.ipynb#scrollTo=LRqg1is5v2Os). Thanks!

**Comment by kingatlas** [comment]
@sanatmpa1 the `iter(dataset)` is returning a set of tensors, this is not what I want, I want numpy results (as expected with `as_numpy_iterator`)

**Comment by sachinprasadhs** [comment]
The element returned from dataset contains tuple object and hence it throws the error.
Below is the output for the above code.
```
for element in dataset:
  print(element)

(<tf.Tensor: shape=(), dtype=int32, numpy=42>, <tf.RaggedTensor [[1, 2], [3]]>)
```

**Comment by clarkzinzow** [comment]
Bump on this, this is still broken as of 2.9.1.

**Comment by sachinprasadhs** [comment]
@clarkzinzow, Could you please open a new issue as feature request to support `numpy_iterator()` for ragged tensor inputs. Thanks!

**Comment by OhadRubin** [comment]
Bump

**Comment by JXRiver** [comment]
Calling numpy on a RaggedTensor will create numpy array of dtype object.
For your example, it could return something like
`(42, array([array([1, 2], dtype=int32), array([3], dtype=int32)], dtype=object))`.

Is this your expected output?

**Comment by darsnack** [comment]
Yes that would be the best option that I would expect.

**Comment by tilakrayal** [comment]
@kingatlas,
I tried to execute the mentioned code on tf-nightly(2.16.0-dev20231026) and it was executed without any issue/error like the earlier versions. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/68b48789703fcd42a7875d4c4215c516/53149.ipynb). Thank you!
