### ISSUE TITLE
Whether the padding property in the convolution is valid affects network speed.

### ISSUE THREAD

**Issue by yahuuu** [tensorflow/tensorflow#53141]
### 1. System information

- OS Platform and Distribution :  Android 11
- TensorFlow installation (pip package or built from source): pip installed
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.2.2
- Inference device: SnapDragon 855 GPU and DSP 
### 2.  After conversion
After post quantized the model, the quantized model runs slower on DSP than fp32 model on GPU. My model's convolution weight is int8, padding property is valid, does valid affect the computational speed of convolution?
I downloaded the mobileNet model from the tensorflow hub and compared it to find that the convolutional property of mobileNet is same.

**Comment by tilakrayal** [comment]
@yahuuu ,
Could you please update TensorFlow to the latest stable version v.2.6 or v2.7 and let us know if you are facing the same error. Thanks!
