### ISSUE TITLE
Add more "synthetic" datasets in the `contrib.learn`

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#5314]
The feature request is as in the title -- having synthetic datasets for demo purposes, and to see how different algorithms behave would be beneficial. It is fairly straightforward to generate two-dimensional multi-class set for a lot of synthetic problems.

**Comment by aselle** [comment]
@martinwicke @ilblackdragon, do you have any comments on this. I could mark this contributions welcome.

**Comment by vrv** [comment]
See https://github.com/tensorflow/tensorflow/pull/5315

**Comment by zafartahirov** [comment]
This should be reopened -- there was accidental contamination which caused the commit comment include the reference to the current issue. The actual solution to the current issue is #5315

**Comment by zafartahirov** [comment]
Sorry, accidentally closed. Solution is implemented #5315
