### ISSUE TITLE
Outdated documentation for `DataFormatVecPermute`

### ISSUE THREAD

**Issue by Nyrio** [tensorflow/tensorflow#53157]
This came up while creating a TF-TRT converter for `DataFormatVecPermute` in #52942 
cc @bixia1 

## URL(s) with the issue:

 - Python: https://www.tensorflow.org/api_docs/python/tf/raw_ops/DataFormatVecPermute
 - C++: https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/data-format-vec-permute
 - Java: https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/op/nn/DataFormatVecPermute

## Description of the issue (what needs changing):

- Examples imply that an input of shape `(2, 4)` is valid, but that should be `(4, 2)`.
- The format strings can be of size 4 or 5 (e.g `"NHWC"`, `"NDHWC"`).
- The first dimension of the input shape vector can be `src_format.size()` or `src_format.size() - 2`, in which case it is assumed that non-spatial dimensions are omitted.

As an example, here is a valid Python code that is not covered by the documentation:

```python
import tensorflow as tf
a = tf.constant([1, 2, 3, 4, 5])
print(tf.raw_ops.DataFormatVecPermute(x=a, src_format="NDHWC", dst_format="NCDHW"))
```
Output:
```
tf.Tensor([1 5 2 3 4], shape=(5,), dtype=int32)
```

## Submit a pull request?

I'm planning to submit a PR.

**Comment by mohantym** [comment]
Hi @Nyrio ! This issue will be closed once the PR #53158  is merged. Thanks!

**Comment by mohantym** [comment]
Hi @Nyrio ! Is this issue good to close now ? As the above PR seems to be merged now . Thanks!

**Comment by Nyrio** [comment]
@mohantym No, that's a different PR. #53158 is the one that closes this issue.

**Comment by mohantym** [comment]
Ok @Nyrio! Thanks for the confirmation!
