### ISSUE TITLE
tf.keras.callbacks.TensorBoard(update_freq=#) doesn't work/is buggy on Windows

### ISSUE THREAD

**Issue by roballsopp** [tensorflow/tensorflow#53150]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
__Yes, but its still very simple__
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
__Windows 11 Home__
- TensorFlow installed from (source or binary):
__just did `pip install tensorflow`__
- TensorFlow version (use command below):
__same behavior on 2.6.1 and 2.7.0__
- Python version:
__3.8__
- CUDA/cuDNN version:
__11.2__
- GPU model and memory:
__NVIDIA GeForce RTX 2060, 6144MiB__

**Describe the current behavior**
using `tf.keras.callbacks.TensorBoard(log_dir=log_dir, update_freq=15)` does not correctly log metrics for both training and validation sets every 15 batches, as the docs state it should. Instead, in tensorboard I either see only a plot for the training set and nothing for validation, or most of the time I don't see a plot for either. Additionally, if I do a training run with the `update_freq` argument set, the plots for any previous runs stop appearing in tensorboard when I hit the refresh button. If I then delete the "bad" run (the one that had `update_freq` set), my existing plots come back. When I simply remove the `update_freq` argument and just train with `tf.keras.callbacks.TensorBoard(log_dir=log_dir)`, everything works as expected, and I see plots with points at each epoch.

**Describe the expected behavior**
using something like `tf.keras.callbacks.TensorBoard(log_dir=log_dir, update_freq=15)` should produce metrics every 15 batches, and I should be able to view a plot of this in tensorboard, just as I can without specifying to log metrics every `update_freq` batches.

My code:
```python
import tensorflow as tf
import numpy as np
import glob
import datetime
import pandas as pd

num_features = 4000

model = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(input_shape=(num_features, 1)),
    tf.keras.layers.Conv1D(filters=7, kernel_size=(256,), activation='swish'),
    tf.keras.layers.Conv1D(filters=1, kernel_size=(2048,), activation=None),
    tf.keras.layers.Flatten()
])

model.summary()

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.MeanSquaredError(),
    metrics=[tf.metrics.MeanAbsoluteError()]
)

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
checkpoint_path = './tf_checkpoints/naive_cnn/{epoch:02d}_{batch:02d}.ckpt'

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, write_graph=False, update_freq=15)
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, save_freq=100, verbose=1)
train_X = None
train_Y = None

with tf.device('/device:CPU:0'):
    train_X = tf.signal.frame(allair1, frame_length=num_features, frame_step=1000)
    train_Y = tf.signal.frame(label_data[(num_features - 1698):], frame_length=1698, frame_step=1000)
    
train_X = np.expand_dims(train_X, axis=-1)
    
val_X = train_X[:500]
val_Y = train_Y[:500]
train_X = train_X[500:5000]
train_Y = train_Y[500:5000]

history = model.fit(
    x=train_X,
    y=train_Y,
    validation_data=(train_X, train_Y),
    batch_size=100,
    epochs=10,
    callbacks=[cp_callback, tensorboard_callback],
    verbose=1
)

hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail()
```

**Comment by sushreebarsa** [comment]
@roballsopp This issue is more related to Tensorboard .Could you please open the issue in [Tensorboard repo](https://github.com/tensorflow/tensorboard/issues) ?Thank you!
