### ISSUE TITLE
Classify issues using more specific labels

### ISSUE THREAD

**Issue by fridex** [tensorflow/tensorflow#53159]
Hi all,

based on the discussion on TF SIG build meeting, raising this issue here.

It would be great if TensorFlow issue tracker would have more specific labels so issues could be classified and browsed only based on some specific criteria. An example of labels that would be very helpful for us:

1. labels specific to dependency issues on Python layer (dependency compatibility issues, underpinning/overpining, ...)
2. labels specific to runtime/buildtime environment issues on software layer ouside of Python libs (python interpreter incompatibilities, CUDA issues, glibc issues, ...)
3. labels specific to runtime/buildtime environment issues on hardware layer (GPU issues, ...)

We would like to consume labeled issues - combining efforts on this front would be very helpful for us (Red Hat) to provide better environments to TensorFlow open-source community.

Thanks in advance for any response.

**Comment by yarri-oss** [comment]
Thanks for adding this as an issue for us to discuss. Can you please review the existing [labels](https://github.com/tensorflow/tensorflow/labels) and give us some specific recommendations. For example, we have used a common convention to create label categories using the syntax <category>:<feature> and have categories that we use in our automation processes (ie., "cla" or "comp").

Are you suggesting that we add new labels in a specific category, such as "type: python" or "type: cuda" or something else? Thanks!

**Comment by bhack** [comment]
@fridex I don't know if you are interested to have these set of labels for TF only or also for the `strict ecosystem` TF+TF SIGs repos. 
If the case is the last one I think that could be useful to have a common label subset in sync on TF+SIGs with some syncing solution e.g.:

- https://label-sync.com/
- https://github.com/micnncim/action-label-syncer 
- etc...

**Comment by goern** [comment]
@bhack or we learn from the Kubernetes ecosystem and their way to have labels declared for the org, or for individual repos, its even generating a markdown documentation of the labels. see https://github.com/kubernetes/test-infra/tree/master/label_sync

**Comment by bhack** [comment]
The Kubernetes example is quite clear as they have also the "orchestration yaml" in the repository. 

Generally the orchestration isn't always clear in the TF CI infra so sometimes it is a little bit harder to contribute.

I am fine with every transparent approach where the contribution path is clear

**Comment by fridex** [comment]
To keep this updated: we will try to scope a label proposal for this till the next SIG build meeting and update this issue. Thanks a lot for cooperating on this and being open to inputs from the community.

**Comment by fridex** [comment]
We have created a set of labels that would help us to consume issues:

- `env:runtime` - issues that araise on runtime
- `env:buildtime` - issues that arise on buildtime
- `env:hardware` - issues that are caused by hardware and hardware configuration
- `env:python-lib` - issues specific to Python packages that TensorFlow depends on (ex. numpy specific issues)
- `env:native-lib` - issues specific to native dependencies (ex. CUDA. cuDNN, glibc, ...)
  - `env:cudnn`, `env:cuda` - issues specific to CUDA and cuDNN

These are just proposed, feel free to rename them based on your preferences (not sure about prefixes). You are probably using some of them already - for example `type:build/install` label. If they match the proposed one, we can reuse already existing ones - just to make sure we can map our expectations to these labels.

Thanks again. Please let us know if there is a need to clarify something or any additional input from our end is needed.

**Comment by fridex** [comment]
Maybe the reason for this - we are developing a [Python resolver](https://thoth-station.ninja/) that runs in the cloud. It can resolve application dependencies based on prescribed rules, the resolver is [offered to the community](https://www.youtube.com/watch?v=UCt37waSa6g). See [example rules for TensorFlow](https://github.com/thoth-station/prescriptions/tree/master/prescriptions/te_/tensorflow) for some of the rules to resolve specifically for a TensorFlow application. The database of resolver rules ("[prescriptions](https://github.com/thoth-station/prescriptions)") is available publicly - we would like to enhance it based on the issue classification proposed. If issues arise with TensorFlow, we can try to configure the resolver to resolve application dependencies so that users do not encounter known issues. The [following tutorial](https://redhat-scholars.github.io/managing-vulnerabilities-with-thoth/managing-vulnerabilities-with-thoth/index.html) walks through some security aspects of the resolver. We are open to combining efforts.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
