### ISSUE TITLE
MirroredStrategy: Efficient allreduce is not supported for n IndexedSlices

### ISSUE THREAD

**Issue by SysuJayce** [tensorflow/tensorflow#53160]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.4
- Python version: 3.8
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: cuda11.0+cudnn8
- GPU model and memory: V100+32GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
With Embedding layer, MirroredStrategy will report a warning: `MirroredStrategy: Efficient allreduce is not supported for n IndexedSlices`.
Trianing speed can scale up with 2-4 GPUs, but as we increase GPU devices, the training speed can not scale up anymore.
Besides, the GPU utilization is quite low if we add more GPUs (can jump from 0 ~ 100%).

I have search the Internet and find some workaround, e.g. #41898. But even if I change MirroredStrategy with MultiWorkerMirroredStrategy, the GPU utilization is quite low and the training time is nearly the same as MirroredStrategy.

**Describe the expected behavior**
In single machine with multiple GPUs, can use MirroredStrategy to scale up training speed with IndexedSlices (Embedding Layer).

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Borrow from @ratovarius
```
import sys
import tensorflow as tf
import numpy as np

def build_model_():

	input_a_size = 20
	input_b_size = 4
	num_classes = 2
	len_embedding = 256

	input_a = tf.keras.layers.Input(shape=(input_a_size,), name='input_a', dtype=np.uint8)
	input_b = tf.keras.layers.Input(shape=(input_b_size,), name='input_b', dtype=np.float32)

	x = tf.keras.layers.Embedding(len_embedding, 100)(input_a)
	x = tf.keras.layers.Conv1D(128, 4, activation='relu')(x)
	x = tf.keras.layers.MaxPooling1D(4)(x)
	x = tf.keras.layers.Flatten()(x)
	branch_a = tf.keras.layers.Dense(64, activation='relu')(x)

	x = tf.keras.layers.Dense(32, activation='relu')(input_b)
	branch_b = tf.keras.layers.Dense(32, activation='relu')(x)

	concat = tf.keras.layers.Concatenate()([
				                            branch_a,
				                            branch_b,
				                           ])

	x = tf.keras.layers.Dense(512, activation = 'relu')(concat)
	output = tf.keras.layers.Dense(num_classes, name='output', activation='softmax')(x)

	model = tf.keras.models.Model(inputs=[
				                          input_a,
				                          input_b,
				                         ],
				                  outputs=[output])

	return model

strategy = tf.distribute.MirroredStrategy(['/gpu:0', '/gpu:1'])
with strategy.scope():
    model = build_model_()
    model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

y_train = True
y_train = tf.keras.utils.to_categorical(y_train, 2)

dataset = tf.data.Dataset.from_tensors(
    (
        {"input_a": [[1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.], [1.]], 
         "input_b": [[1.], [1.], [1.], [1.]],}, 
        {"output": y_train},
    )
).repeat(1000000).batch(256)

history = model.fit(
    x = dataset,
    epochs=10,
    verbose = 1,
)

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@SysuJayce Could you please try with the latest stable TF version `2.7.0` and refer to the similar[ issue](https://stackoverflow.com/questions/63034145/warningtensorflowefficient-allreduce-is-not-supported-for-1-indexedslices), [issue1](https://github.com/tensorflow/tensorflow/issues/41898),[ issue2](https://github.com/tensorflow/tensorflow/issues/39545) and let us know if it helps? For further queries please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by SysuJayce** [comment]
> @SysuJayce Could you please try with the latest stable TF version `2.7.0` and refer to the similar[ issue](https://stackoverflow.com/questions/63034145/warningtensorflowefficient-allreduce-is-not-supported-for-1-indexedslices), [issue1](https://github.com/tensorflow/tensorflow/issues/41898),[ issue2](https://github.com/tensorflow/tensorflow/issues/39545) and let us know if it helps? For further queries please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!

@sushreebarsa Hi, I have tried tf2.7.0 and MultiWorkerMirroredStrategy. But as I mentioned above, the GPU utilization is low and the training speed is not scaled up.

Actually, in issue #39545, @dubey and @byronyi have given some suggestion. For instance, convert sparse tensor to dense one. But I don't know how to do this because I do not use sparse tensor myself.

I dig the tensorflow source code and find that sparse allreduce is used and I guess it is because tensorflow use sparse tensor in Embedding layer.
https://github.com/tensorflow/tensorflow/blob/c256c071bb26e1e13b4666d1b3e229e110bc914a/tensorflow/python/distribute/cross_device_ops.py#L929

Do we need to post distributed training performance issue on keras repo now ?

**Comment by SysuJayce** [comment]
Hello, @sushreebarsa @jvishnuvardhan .
It's been 2 days. Is there any progress? 

I think this is a common use case in NLP, why nobody in TF team cares about it?

**Comment by byronyi** [comment]
> the GPU utilization is low and the training speed is not scaled up.

You are using multi-host training and the performance will be depending on multiple factors, including your network architecture, available bandwidth, system bus topology, etc. For us, It is rather difficult to provide a universally applicable tuning guide for all possible scenario.

You could start by pasting your [nccl-test](https://github.com/NVIDIA/nccl-tests) benchmark results, assuming your are using NCCL for multi-host all-reduce.

**Comment by SysuJayce** [comment]
> > the GPU utilization is low and the training speed is not scaled up.
> 
> You are using multi-host training and the performance will be depending on multiple factors, including your network architecture, available bandwidth, system bus topology, etc. For us, It is rather difficult to provide a universally applicable tuning guide for all possible scenario.
> 
> You could start by pasting your [nccl-test](https://github.com/NVIDIA/nccl-tests) benchmark results, assuming your are using NCCL for multi-host all-reduce.

Hi @byronyi, I am currently using single host with multiple GPUs.

If I set embedding layer untrainable, everything is fine, the GPU utilization in `MultiWorkerMirroredStrategy` and `MirroredStrategy` can reach nearly 100% all the time.
But if I set embedding layer trainable, the warning appears and the GPU utilization drops as the number of GPUs increasing.


As the warning saying, `Efficient allreduce is not supported for n IndexedSlices`, is there any way that we can use `MirroredStrategy` to train network with embedding layer since `MultiWorkerMirroredStrategy` is not as performant as `MirroredStrategy` in single machine environment?

> You could start by pasting your nccl-test benchmark results

Thanks! I'll do this test later.

**Comment by byronyi** [comment]
If you are using single host, switch to mirrored strategy. Are you using NVLink/NVSwitch or PCIe for your BUS topology? It'd be helpful to set `NCCL_DEBUG=INFO` and paste the NCCL log here.

Btw, GPU utilization says little about the actual performance. Take a look at your GPU power consumption; if it is stuck on NCCL deadlock, the utilization could reach 100% while the power consumption stays relatively low.

**Comment by SysuJayce** [comment]
> If you are using single host, switch to mirrored strategy. Are you using NVLink/NVSwitch or PCIe for your BUS topology? It'd be helpful to set `NCCL_DEBUG=INFO` and paste the NCCL log here.
> 
> Btw, GPU utilization says little about the actual performance. Take a look at your GPU power consumption; if it is stuck on NCCL deadlock, the utilization could reach 100% while the power consumption stays relatively low.

Hi @byronyi , I did the test in a machine with P40 GPUs, but in another machine with V100 GPUs, the problem exists too.

the system env is:
```
NV_LIBCUBLAS_VERSION=11.2.0.252-1
NVIDIA_VISIBLE_DEVICES=all
NV_NVML_DEV_VERSION=11.0.167-1
NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.11.4-1+cuda11.0
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.11.4-1
NVIDIA_REQUIRE_CUDA=cuda>=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-11-0=11.2.0.252-1
NV_NVTX_VERSION=11.0.167-1
NV_ML_REPO_ENABLED=1
NV_CUDA_CUDART_DEV_VERSION=11.0.221-1
NV_LIBCUSPARSE_VERSION=11.1.1.245-1
NV_LIBNPP_VERSION=11.1.0.245-1
NCCL_VERSION=2.11.4-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NV_LIBNPP_PACKAGE=libnpp-11-0=11.1.0.245-1
NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
NV_LIBCUBLAS_DEV_VERSION=11.2.0.252-1
NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-11-0
NV_CUDA_CUDART_VERSION=11.0.221-1
CUDA_VERSION=11.0.3
NV_LIBCUBLAS_PACKAGE=libcublas-11-0=11.2.0.252-1
NV_LIBNPP_DEV_PACKAGE=libnpp-dev-11-0=11.1.0.245-1
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-0
NV_LIBNPP_DEV_VERSION=11.1.0.245-1
NV_LIBCUSPARSE_DEV_VERSION=11.1.1.245-1
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
SHLVL=1
NV_CUDA_LIB_VERSION=11.0.3-1
NVARCH=x86_64
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-0
NV_LIBNCCL_PACKAGE=libnccl2=2.11.4-1+cuda11.0
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NV_LIBNCCL_PACKAGE_NAME=libnccl2
NV_LIBNCCL_PACKAGE_VERSION=2.11.4-1
```

the topology is:
```
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity
GPU0     X      PIX     PHB     PHB     SYS     SYS     SYS     SYS     0-13,28-41      0
GPU1    PIX      X      PHB     PHB     SYS     SYS     SYS     SYS     0-13,28-41      0
GPU2    PHB     PHB      X      PIX     SYS     SYS     SYS     SYS     0-13,28-41      0
GPU3    PHB     PHB     PIX      X      SYS     SYS     SYS     SYS     0-13,28-41      0
GPU4    SYS     SYS     SYS     SYS      X      PIX     PHB     PHB     14-27,42-55     1
GPU5    SYS     SYS     SYS     SYS     PIX      X      PHB     PHB     14-27,42-55     1
GPU6    SYS     SYS     SYS     SYS     PHB     PHB      X      PIX     14-27,42-55     1
GPU7    SYS     SYS     SYS     SYS     PHB     PHB     PIX      X      14-27,42-55     1
```

with GPU 4-7, the NCCL_DEBUG msg is:
```
WARNING:tensorflow:Efficient allreduce is not supported for 2 IndexedSlices
WARNING:tensorflow:Efficient allreduce is not supported for 2 IndexedSlices
WARNING:tensorflow:Efficient allreduce is not supported for 2 IndexedSlices
WARNING:tensorflow:Efficient allreduce is not supported for 2 IndexedSlices
dbe753952c3d:1013:1261 [0] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.23<0>
dbe753952c3d:1013:1261 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
dbe753952c3d:1013:1261 [0] NCCL INFO NET/IB : No device found.
dbe753952c3d:1013:1261 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.23<0>
dbe753952c3d:1013:1261 [0] NCCL INFO Using network Socket
NCCL version 2.7.6+cudaCUDA_MAJOR.CUDA_MINOR
dbe753952c3d:1013:1420 [0] NCCL INFO Channel 00/02 :    0   1   2   3
dbe753952c3d:1013:1421 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dbe753952c3d:1013:1423 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dbe753952c3d:1013:1422 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dbe753952c3d:1013:1420 [0] NCCL INFO Channel 01/02 :    0   1   2   3
dbe753952c3d:1013:1421 [1] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] 2/-1/-1->1->0|0->1->2/-1/-1
dbe753952c3d:1013:1423 [3] NCCL INFO Trees [0] -1/-1/-1->3->2|2->3->-1/-1/-1 [1] -1/-1/-1->3->2|2->3->-1/-1/-1
dbe753952c3d:1013:1422 [2] NCCL INFO Trees [0] 3/-1/-1->2->1|1->2->3/-1/-1 [1] 3/-1/-1->2->1|1->2->3/-1/-1
dbe753952c3d:1013:1423 [3] NCCL INFO Setting affinity for GPU 7 to fffc00,0fffc000
dbe753952c3d:1013:1422 [2] NCCL INFO Setting affinity for GPU 6 to fffc00,0fffc000
dbe753952c3d:1013:1421 [1] NCCL INFO Setting affinity for GPU 5 to fffc00,0fffc000
dbe753952c3d:1013:1420 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
dbe753952c3d:1013:1420 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
dbe753952c3d:1013:1420 [0] NCCL INFO Setting affinity for GPU 4 to fffc00,0fffc000
dbe753952c3d:1013:1421 [1] NCCL INFO Channel 00 : 1[86000] -> 2[89000] via direct shared memory
dbe753952c3d:1013:1423 [3] NCCL INFO Channel 00 : 3[8a000] -> 0[85000] via direct shared memory
dbe753952c3d:1013:1422 [2] NCCL INFO Channel 00 : 2[89000] -> 3[8a000] via P2P/direct pointer
dbe753952c3d:1013:1420 [0] NCCL INFO Channel 00 : 0[85000] -> 1[86000] via P2P/direct pointer
dbe753952c3d:1013:1423 [3] NCCL INFO Channel 00 : 3[8a000] -> 2[89000] via P2P/direct pointer
dbe753952c3d:1013:1422 [2] NCCL INFO Channel 00 : 2[89000] -> 1[86000] via direct shared memory
dbe753952c3d:1013:1421 [1] NCCL INFO Channel 00 : 1[86000] -> 0[85000] via P2P/direct pointer
dbe753952c3d:1013:1423 [3] NCCL INFO Channel 01 : 3[8a000] -> 0[85000] via direct shared memory
dbe753952c3d:1013:1421 [1] NCCL INFO Channel 01 : 1[86000] -> 2[89000] via direct shared memory
dbe753952c3d:1013:1420 [0] NCCL INFO Channel 01 : 0[85000] -> 1[86000] via P2P/direct pointer
dbe753952c3d:1013:1422 [2] NCCL INFO Channel 01 : 2[89000] -> 3[8a000] via P2P/direct pointer
dbe753952c3d:1013:1423 [3] NCCL INFO Channel 01 : 3[8a000] -> 2[89000] via P2P/direct pointer
dbe753952c3d:1013:1423 [3] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dbe753952c3d:1013:1422 [2] NCCL INFO Channel 01 : 2[89000] -> 1[86000] via direct shared memory
dbe753952c3d:1013:1421 [1] NCCL INFO Channel 01 : 1[86000] -> 0[85000] via P2P/direct pointer
dbe753952c3d:1013:1422 [2] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dbe753952c3d:1013:1420 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dbe753952c3d:1013:1421 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
dbe753952c3d:1013:1420 [0] NCCL INFO comm 0x7d03a00010d0 rank 0 nranks 4 cudaDev 0 busId 85000 - Init COMPLETE
dbe753952c3d:1013:1423 [3] NCCL INFO comm 0x7d038c0010a0 rank 3 nranks 4 cudaDev 3 busId 8a000 - Init COMPLETE
dbe753952c3d:1013:1422 [2] NCCL INFO comm 0x7d03980010a0 rank 2 nranks 4 cudaDev 2 busId 89000 - Init COMPLETE
dbe753952c3d:1013:1421 [1] NCCL INFO comm 0x7d03940010a0 rank 1 nranks 4 cudaDev 1 busId 86000 - Init COMPLETE
```

the nccl-test info:
```
root@dbe753952c3d:/workspace/nccl-tests-master# ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 8
# nThread 1 nGpus 8 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid   1524 on dbe753952c3d device  0 [0x04] Tesla P40
#   Rank  1 Pid   1524 on dbe753952c3d device  1 [0x05] Tesla P40
#   Rank  2 Pid   1524 on dbe753952c3d device  2 [0x08] Tesla P40
#   Rank  3 Pid   1524 on dbe753952c3d device  3 [0x09] Tesla P40
#   Rank  4 Pid   1524 on dbe753952c3d device  4 [0x85] Tesla P40
#   Rank  5 Pid   1524 on dbe753952c3d device  5 [0x86] Tesla P40
#   Rank  6 Pid   1524 on dbe753952c3d device  6 [0x89] Tesla P40
#   Rank  7 Pid   1524 on dbe753952c3d device  7 [0x8a] Tesla P40
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2     float     sum    131.0    0.00    0.00  1e-07    133.7    0.00    0.00  1e-07
          16             4     float     sum    368.5    0.00    0.00  1e-07    157.5    0.00    0.00  1e-07
          32             8     float     sum    407.3    0.00    0.00  6e-08    45.10    0.00    0.00  6e-08
          64            16     float     sum    40.39    0.00    0.00  6e-08    53.87    0.00    0.00  6e-08
         128            32     float     sum    54.46    0.00    0.00  6e-08    141.0    0.00    0.00  6e-08
         256            64     float     sum    130.5    0.00    0.00  3e-08    134.8    0.00    0.00  3e-08
         512           128     float     sum    138.7    0.00    0.01  3e-08    325.2    0.00    0.00  3e-08
        1024           256     float     sum    51.86    0.02    0.03  1e-07    35.52    0.03    0.05  1e-07
        2048           512     float     sum    72.45    0.03    0.05  2e-07    33.34    0.06    0.11  2e-07
        4096          1024     float     sum    150.1    0.03    0.05  2e-07   1004.7    0.00    0.01  2e-07
        8192          2048     float     sum    149.4    0.05    0.10  2e-07    187.6    0.04    0.08  2e-07
       16384          4096     float     sum    179.0    0.09    0.16  2e-07    171.1    0.10    0.17  2e-07
       32768          8192     float     sum    420.5    0.08    0.14  2e-07    157.6    0.21    0.36  2e-07
       65536         16384     float     sum    168.8    0.39    0.68  2e-07    171.3    0.38    0.67  2e-07
      131072         32768     float     sum    339.6    0.39    0.68  2e-07    352.6    0.37    0.65  2e-07
      262144         65536     float     sum    356.8    0.73    1.29  2e-07    600.6    0.44    0.76  2e-07
      524288        131072     float     sum    568.6    0.92    1.61  2e-07    412.5    1.27    2.22  2e-07
     1048576        262144     float     sum   1064.3    0.99    1.72  2e-07   2835.2    0.37    0.65  2e-07
     2097152        524288     float     sum   2624.7    0.80    1.40  2e-07   2075.9    1.01    1.77  2e-07
     4194304       1048576     float     sum   7038.9    0.60    1.04  2e-07   2286.6    1.83    3.21  2e-07
     8388608       2097152     float     sum   7334.6    1.14    2.00  2e-07   6914.2    1.21    2.12  2e-07
    16777216       4194304     float     sum   9180.5    1.83    3.20  2e-07   9864.8    1.70    2.98  2e-07
    33554432       8388608     float     sum    16978    1.98    3.46  2e-07    15446    2.17    3.80  2e-07
    67108864      16777216     float     sum    29175    2.30    4.03  2e-07    26977    2.49    4.35  2e-07
   134217728      33554432     float     sum    63809    2.10    3.68  2e-07    62694    2.14    3.75  2e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.06089 
```

**Comment by byronyi** [comment]
Your bus topology is suboptimal for all-reduce between 8 GPUs across multiple NUMA nodes. Mind to share all_reduce_perf between GPU 0-3 or 4-7?

**Comment by SysuJayce** [comment]
> Your bus topology is suboptimal for all-reduce between 8 GPUs across multiple NUMA nodes. Mind to share all_reduce_perf between GPU 0-3 or 4-7?

Yes, that's why I use GPUs 4-7 to train my network in the above comment.

Below is the topo of another machine with V100, but the problem exists too.
```
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity
GPU0     X      NV1     NV1     NV2     NV2     SYS     SYS     SYS     0-19,40-59      0
GPU1    NV1      X      NV2     NV1     SYS     NV2     SYS     SYS     0-19,40-59      0
GPU2    NV1     NV2      X      NV2     SYS     SYS     NV1     SYS     0-19,40-59      0
GPU3    NV2     NV1     NV2      X      SYS     SYS     SYS     NV1     0-19,40-59      0
GPU4    NV2     SYS     SYS     SYS      X      NV1     NV1     NV2     20-39,60-79     1
GPU5    SYS     NV2     SYS     SYS     NV1      X      NV2     NV1     20-39,60-79     1
GPU6    SYS     SYS     NV1     SYS     NV1     NV2      X      NV2     20-39,60-79     1
GPU7    SYS     SYS     SYS     NV1     NV2     NV1     NV2      X      20-39,60-79     1
```

**Comment by byronyi** [comment]
Your V100 machine has NVLink. 

To me that seems to be a TF related issue. Mind to share a small model training script to reproduce the issue? Thanks.

**Comment by SysuJayce** [comment]
> Your V100 machine has NVLink.
>
> To me that seems to be a TF related issue. Mind to share a small model training script to reproduce the issue? Thanks.

Hi @byronyi , 
```
import os
import sys

import numpy as np
import tensorflow as tf


def build_model():
    input_a = tf.keras.Input(shape=(256,), dtype=tf.int64, name="input_a")
    input_b = tf.keras.Input(shape=(256,), dtype=tf.int64, name="input_b")

    emb_a = tf.keras.layers.Embedding(
        input_dim=20000,
        output_dim=128,
        input_length=256,
        embeddings_initializer=tf.keras.initializers.TruncatedNormal(stddev=0.02),
        trainable=True)
    emb_b = tf.keras.layers.Embedding(
        input_dim=20000,
        output_dim=128,
        input_length=256,
        embeddings_initializer=tf.keras.initializers.TruncatedNormal(stddev=0.02),
        trainable=True)

    x = tf.keras.layers.add([emb_a(input_a), emb_b(input_b)])
    x = tf.keras.layers.Conv1D(filters=128,
                               kernel_size=3,
                               activation="relu")(x)
    x = tf.keras.layers.Conv1D(filters=128,
                               kernel_size=3,
                               activation="relu")(x)
    x = tf.keras.layers.Conv1D(filters=128,
                               kernel_size=3,
                               activation="relu")(x)
    x = tf.keras.layers.Conv1D(filters=128,
                               kernel_size=3,
                               activation="relu")(x)
    x = tf.keras.layers.Conv1D(filters=128,
                               kernel_size=3,
                               activation="relu")(x)
    x = tf.keras.layers.GlobalMaxPooling1D()(x)
    x = tf.keras.layers.Dense(64, activation='relu')(x)
    output = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(x)

    model = tf.keras.models.Model(
        inputs=[
            input_a,
            input_b,
        ],
        outputs=output
    )

    return model


def main():
    assert len(sys.argv) == 2
    os.environ["CUDA_VISIBLE_DEVICES"] = sys.argv[1]
    gpus = sys.argv[1].split(",")
    if len(gpus) == 1:
        strategy = tf.distribute.get_strategy()
    else:
        strategy = tf.distribute.MirroredStrategy()

    with strategy.scope():
        model = build_model()
        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
        model.summary()

    batch_size = 1024 * strategy.num_replicas_in_sync
    dataset = tf.data.Dataset.from_tensors(
        (
            {"input_a": np.random.randint(0, 20001, (256,), int),
             "input_b": np.random.randint(0, 20001, (256,), int)},
            {"output": np.random.randint(0, 2, (1,), int)},
        )
    ).repeat(1000000).batch(batch_size)

    model.fit(
        x=dataset,
        epochs=10,
        verbose=1,
    )


if __name__ == "__main__":
    main()

```
If we save the code in `main.py`, we use an additional arg to specify the GPUs to use, each GPU idx is separated by a comma.

1. `python3 main.py 1 `

   > GPU utilization: ~80%
   >
   > Speed: 121s/epoch

2. `python3 main.py 2,3`

   > GPU utilization: ~90% for the 1st, ~80% for the 2nd
   >
   > Speed: 34s/epoch

3. `python3 main.py 4,5,6,7`

   > GPU utilization: ~95% for the 1st, ~38% for the others
   >
   > Speed: 43s/epoch

4. `python3 main.py 0,1,2,3,4,5,6,7 `

   > GPU utilization: 95%-100% for the 1st, 0-70% for the others, and there are always some GPUs have 0 utilization.
   >
   > Speed: 135s/epoch

**Comment by byronyi** [comment]
So using 2 GPUs the performance is more than 2x compared to using single GPU? That's weird...

**Comment by SysuJayce** [comment]
> So using 2 GPUs the performance is more than 2x compared to using single GPU? That's weird...

Yes, it is weird. It is really disappointing that MirroredStrategy can not handle this situation :(

If you can't reproduce this issue, ask me to provide anything you need.

**Comment by SysuJayce** [comment]
@byronyi @jvishnuvardhan Hi, is there any progress? What should I do to help you solve this problem?

**Comment by SysuJayce** [comment]
It's been a month and yet no one comes to solve this problem :(

**Comment by jszaday** [comment]
It's been awhile... but, if this is still an active issue, would you mind testing whether a distributed dataset improves performance? For example, you could change your code to something like this:

```py
dataset = tf.data.Dataset.from_tensors((
  {"input_a": np.random.randint(0, 20001, (256,), int),
   "input_b": np.random.randint(0, 20001, (256,), int)},
  {"output": np.random.randint(0, 2, (1,), int)},
)).repeat(1000000)
# determine the cardinality/size of the dataset, then distribute it
cardinality = tf.data.experimental.cardinality(dataset).numpy()
dataset = dataset.batch(batch_size).with_options(options)
dataset = strategy.experimental_distribute_dataset(dataset)
# determine the number steps/epoch (necessary for distributed datasets)
epochs = 10
batches = cardinality // batch_size
steps_per_epoch = batches // epochs
# train the model...
history = model.fit(
  x=dataset,
  epochs=epochs,
  steps_per_epoch=steps_per_epoch,
  verbose=1)
```

**Comment by utkarshgupta137** [comment]
Not stale

**Comment by utkarshgupta137** [comment]
Not stale

**Comment by anirban-mu** [comment]
Has there been any update on this issue? It would be very useful to know a little bit more about how we can either avoid this issue when developing our model.

**Comment by lly-zero-one** [comment]
I would like to share what we did to resolve the embedding table training scalability problem. The root cause seems to be the sparse gradient aggregation among all GPUs. Basically, every GPU is collecting all triggered indices from all GPUs, then deduplicating the indices and adding together gradient from same indices. When the batch size is large, this sparse gradient aggregation time will linearly increase with number of GPUs, which makes the multiple training be not scalable at all. 

We tried two solutions, and both seems to be working depending table size.
1) if the embedding table is not large, we can actually treat it as dense and circulate the gradient among all GPUs with all-reduce. To achieve this, we could use horovod and in the optimizer constructor, there is one flag "sparse_as_dense", which can be set to true.
2) we can also do the table sharding by using Nvidia HugeCTR and rely on collective communication(all2all,or reduce_scatter and etc depending the sharding strategy) to distribute the embedding lookup and gradient update among all GPUs.

Hopefully it helps.

**Comment by sachinprasadhs** [comment]
@SysuJayce , Could you please refer the above comment.
Also, Refer the detailed document about `MirroedStrategy` here https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy for the best practices. Thanks!

**Comment by shivamsbatra** [comment]
not stale, please reopen

**Comment by anirban-mu** [comment]
1. Can you please confirm the accuracy of these statements? "The root cause seems to be the sparse gradient aggregation among all GPUs. Basically, every GPU is collecting all triggered indices from all other GPUs, then deduplicating the indices and adding together gradient with same indices. When the batch size is large, this sparse gradient aggregation time will linearly increase with number of GPUs, which makes the multiple GPU training be not scalable at all."
2. Would you recommend the solutions proposed by [lly-zero-one](https://github.com/lly-zero-one)?
3. Are there alternative solutions, other than those suggested by [lly-zero-one](https://github.com/lly-zero-one), that we could take into consideration?

We understand that it is not expected to have a tuning guide for every model in every scenario. However, it seems reasonable to request documentation and commentary on performance issues when using core components. One concern with TensorFlow is that the documentation might be dispersed across various sources, making it challenging to find consolidated information. This particular issue serves as an example of this concern, where the use-case is fairly straightforward (an application-specific embedding), the functions used to create the components come from the baseline TensorFlow framework, and the distribution strategy is based on TensorFlow code. Despite this, there seems to be a lack of official guidance for over two years, leaving the community with limited information on why they may encounter problems.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
