### ISSUE TITLE
filter dataset too slow .

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#53169]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6
- Are you willing to contribute it (Yes/No): if need I want 

I must have filter dataset, so I must write ```map.filter.batch```, but map batch is too slow than batch map, like:
```
ds = tf.data.TFRecordDataset("a.txt")
ds = ds.map()
ds = ds.filter()
ds = ds.batch()
it = ds.get_one_shot_iterator()
gn = it.get_next()
```
so I want:
```
ds = tf.data.TFRecordDataset("a.txt")
ds = ds.batch()
ds = ds.map() // parallel batch map
ds = ds.unbatch() // unbatch
ds = ds.filter() // filter
ds = ds.batch() // rebatch 
it = ds.get_one_shot_iterator()
gn = it.get_next()
```

but I get : 
```
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    sess.run(train_data_reader(""));
  File "main.py", line 169, in train_data_reader
    train_iterator = train_data_set.make_one_shot_iterator()
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'
```

I want a best profromance filter dataset .

**Comment by zhaozheng09** [comment]
![image](https://user-images.githubusercontent.com/33950866/143202509-f7d0dfa0-c5a2-4e71-b926-5d6acbe95e98.png)
I calculated the time spent on the data set pipeline, and I got the unbatch and filter cost for a long time, so I want to get a parallel unbatch and filter function.
How to parallel unbatch and filter ?

**Comment by mohantym** [comment]
Hi @zhaozheng09! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. You can refer latest documents on [ tf.data](https://www.tensorflow.org/api_docs/python/tf/data)  from 2.6/2.7 version or [use migration document](https://www.tensorflow.org/guide/migrate)  to proceed further. Thanks!

**Comment by zhaozheng09** [comment]
> Hi @zhaozheng09! It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. You can refer latest documents on [ tf.data](https://www.tensorflow.org/api_docs/python/tf/data) from 2.6/2.7 version or [use migration document](https://www.tensorflow.org/guide/migrate) to proceed further. Thanks!

I change my issue 1.15->2.6 ...

**Comment by mohantym** [comment]
Hi @chunduriv! Could you please look at this issue?

**Comment by chunduriv** [comment]
@zhaozheng09, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by zhaozheng09** [comment]
Data confidentiality, re-fake data is too complicated

**Comment by chunduriv** [comment]
@zhaozheng09, If you unable to provide necessary information, it would be difficult for us to debug the issue.

Kindly open this issue in [Tensorflow forum](https://discuss.tensorflow.org/) as there is a larger community to support. Thanks!
