### ISSUE TITLE
tf1.14 tensorboard cannot profile multi batch

### ISSUE THREAD

**Issue by arthur-yh** [tensorflow/tensorflow#53161]
My aim: I use tf1.14 keras to train my model, while I find my gpu utilization rate is very lower, so I want to use tensorboard profile to see which stage cost too much. I follow the wiki from tensorflow set profile_batch to 'str' or 'tuple', it show some error.
my code is below:
`tf.keras.callbacks.TensorBoard(log_dir=FLAGS.get("model_path") + "logs/", histogram_freq=1, profile_batch='2, 10')`
while it shows error like :
`
File "/data/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks_v1.py", line 365, in on_batch_end
    self._total_batches_seen == self._profile_batch - 1):
TypeError: unsupported operand type(s) for -: 'str' and 'int'
`
use tuple like 
`tf.keras.callbacks.TensorBoard(log_dir=FLAGS.get("model_path") + "logs/", histogram_freq=1, profile_batch=(2, 10))`
it show error like :
`TypeError: unsupported operand type(s) for -: 'tuple' and 'int'`

Can anyone help me?  if I really need to use tf1.14

**Comment by mohantym** [comment]
Hi @arthur-yh! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Could you please try with `tf.keras.callbacks.TensorBoard(log_dir=FLAGS.get("model_path") + "logs/", histogram_freq=1, profile_batch=(2, 10))   `   as the Error suggests! Please create an issue in [TF forum ](https://discuss.tensorflow.org/)or Stackoverflow for further assistance !Thanks!

**Comment by arthur-yh** [comment]
@mohantym  thanks for helping，maybe only higher version support str and tuple form of parameter profile_batch.
