### ISSUE TITLE
Unit tests //tensorflow/core/ir/... fail or crash depending on optimization level

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53166]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 8.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git HEAD
- Python version: 3.6.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Tests fail with errors like

<stdin>:4:22: error: custom op 'tfg.AddV2' attribute '_mlir_device' occurs more than once in the attribute list
    %AddV2, %ctl_0 = AddV2(%placeholder, %placeholder_1) device("GPU") assigned_device("TPU") {_mlir_device = "GPU", some_attribute = "some attr!"} : (tensor<*xi32>, tensor<*xi32>) -> (tensor<*xi32>)
                     ^
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/llvm-project/llvm/FileCheck /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/ops.mlir

**Describe the expected behavior**

All tests pass

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): Correct improper use of ArrayRef and StringRef

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --copt=-ffp-contract=off --copt=-O0 --copt=-ggdb --verbose_failures -- //tensorflow/core/ir/tests:ops.mlir.test

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
================================================================================
==================== Test output for //tensorflow/core/ir/tests:ops.mlir.test:
-- Testing: 1 tests, 1 workers --
FAIL: MLIR tests :: ops.mlir (1 of 1)
******************** TEST 'MLIR tests :: ops.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/tfg-opt-no-passes /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/ops.mlir | /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/tfg-opt-no-passes | /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/llvm-project/llvm/FileCheck /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/ops.mlir
--
Exit Code: 2

Command Output (stderr):
--
<stdin>:4:22: error: custom op 'tfg.AddV2' attribute '_mlir_device' occurs more than once in the attribute list
    %AddV2, %ctl_0 = AddV2(%placeholder, %placeholder_1) device("GPU") assigned_device("TPU") {_mlir_device = "GPU", some_attribute = "some attr!"} : (tensor<*xi32>, tensor<*xi32>) -> (tensor<*xi32>)
                     ^
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/llvm-project/llvm/FileCheck /home/andrew/.cache/bazel/_bazel_andrew/c61c5f84d239689cb19a72cfde16be9f/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/ir/tests/ops.mlir.test.runfiles/org_tensorflow/tensorflow/core/ir/tests/ops.mlir

--

********************
********************
Failed Tests (1):
  MLIR tests :: ops.mlir

Testing Time: 0.11s
  Failed: 1
================================================================================

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by tilakrayal** [comment]
@elfringham ,
The issue will move to closed status once the PR is merged.
