### ISSUE TITLE
training stuck in first epoch at random batch # while using rmsprop as optimizer

### ISSUE THREAD

**Issue by makermotion** [tensorflow/tensorflow#53174]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10

- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): >= 2.5.0
- Python version:  >= 3.6

- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 / 8.1
- GPU model and memory: RTX8000 48GB

**Describe the current behavior**
training stuck at first epoch at random batch # while using rmsprop as optimizer. Same code is working with RTX3090.

**Describe the expected behavior**
continue training till end of the defined epoch

- Do you want to contribute a PR? (yes/no): no

**Comment by tilakrayal** [comment]
@makermotion ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by tilakrayal** [comment]
Also please take a look at this links [1](https://stackoverflow.com/questions/53471855/why-does-keras-halt-at-the-first-epoch-when-i-attempt-to-train-it-using-fit-gene) [2](https://stackoverflow.com/questions/59808666/stuck-in-the-first-epoch-when-training-the-cnn-lstm-using-keras) and [3](https://stackoverflow.com/questions/66900639/tensorflow-stuck-on-first-epoch) with the similar error.Please upgrade to latest tf v2.7 and let us know if the issue still exists.Thanks
