### ISSUE TITLE
TypeError: '<' not supported between instances of 'WhileBodyFuncGraph' and 'FuncGraph'

### ISSUE THREAD

**Issue by Avra2** [tensorflow/tensorflow#53176]
Hello,

I have ran tensorflow 2.1 and python 3.8 on a tensorflow project. I got the fp;;

> Start training loop... 0%|          | 0/16153 [00:00<?, ?it/s]2021-11-23 17:42:25.980547: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2) 2021-11-23 17:42:33.055750: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll 2021-11-23 17:42:33.387709: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll Traceback (most recent call last): File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 350, in _flatten_module leaves = nest.flatten_with_tuple_paths( File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 1425, in flatten_with_tuple_paths flatten(structure, expand_composites=expand_composites))) File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 341, in flatten return _pywrap_utils.Flatten(structure, expand_composites) TypeError: '<' not supported between instances of 'WhileBodyFuncGraph' and 'FuncGraph' 
> 
> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "code2seq.py", line 29, in <module> model.train() File "C:\modelrunner.py", line 129, in train gradients = tape.gradient(loss, self.model.trainable_variables) File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 175, in trainable_variables return tuple( File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 390, in _flatten_module for subvalue in subvalues: File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 390, in _flatten_module for subvalue in subvalues: File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 390, in _flatten_module for subvalue in subvalues: File "C:\Anaconda3\lib\site-packages\tensorflow\python\module\module.py", line 353, in _flatten_module six.raise_from( File "<string>", line 3, in raise_from ValueError: Error processing property '_dropout_mask_cache' of <ContextValueCache at 0x2675729b820> 0%|          | 0/16153 [00:10<?, ?it/s]

**Comment by mohantym** [comment]
Hi! @Avra2 ! 
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!
