### ISSUE TITLE
Build - leftover bazel processes after build complete

### ISSUE THREAD

**Issue by edrozenberg** [tensorflow/tensorflow#5317]
After running a successful build, 2 or 3 bazel processes remain along with many child processes for each one - they don't take up any CPU resources. Have to kill the processes manually to get rid of them.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None!

### Environment info
Operating System:
```Slackware 64 14.2```

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
libcudadevrt.a
libcudart.so -> libcudart.so.8.0
libcudart.so.8.0 -> libcudart.so.8.0.44
libcudart.so.8.0.44
libcudart_static.a
libcudnn.so -> libcudnn.so.5
libcudnn.so.5 -> libcudnn.so.5.1.5
libcudnn.so.5.1.5
libcudnn_static.a
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
```6f7cf60a4158a6d7861dc1b41a6446b575153a2e```

2. The output of `bazel version`
```
Build label: 0.3.2- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Oct 16 21:50:19 2016 (1476654619)
Build timestamp: 1476654619
Build timestamp as int: 1476654619
```
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

o Configure with GPU support and run a standard build.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```
ps aux | grep bazel
```
```
root     21080  0.5  0.3 50920612 649256 ?     Ssl  19:00   0:09 bazel(tensorflow) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 -Xverify:none -Djava.util.logging.config.file=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93/javalog.properties -Djava.library.path=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/ -Dfile.encoding=ISO-8859-1 -jar /root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/A-server.jar --max_idle_secs 10800 --install_base=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4 --install_md5=26cccb4705ab94af88df4f6dfb1e20c4 --output_base=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 --workspace_directory=/usr/local/src/tensorflow/tensorflow-git --deep_execroot --experimental_oom_more_eagerly_threshold=100 --nofatal_event_bus_exceptions --product_name=Bazel --option_sources=
root     23518 10.0  1.1 51042312 2339964 ?    Ssl  19:03   2:31 bazel(tensorflow) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 -Xverify:none -Djava.util.logging.config.file=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93/javalog.properties -Djava.library.path=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/ -Dfile.encoding=ISO-8859-1 -jar /root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/A-server.jar --max_idle_secs 10800 --install_base=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4 --install_md5=26cccb4705ab94af88df4f6dfb1e20c4 --output_base=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 --workspace_directory=/usr/local/src/tensorflow/tensorflow-git --deep_execroot --experimental_oom_more_eagerly_threshold=100 --nofatal_event_bus_exceptions --product_name=Bazel --option_sources=
```

**Comment by aselle** [comment]
@jart, this looks a little like the bug you filed against bazel concerning persistent workers https://github.com/bazelbuild/bazel/issues/1868?

Could it be related to this https://github.com/bazelbuild/bazel/issues/614?
(did you interrupt it?)

Do you find that if you clean and run another build you keep getting an accumulation of more processes?

**Comment by edrozenberg** [comment]
Thanks for following up - as a workaround I'm currently doing ```pkill -f "bazel\(tensorflow\)"``` after each build. Also I'm deleting /root/.cache/bazel/_bazel_root/ after the build since on most Linux systems the root partition is quite small and these gigabyte+ caches are going to fill up /root rather quickly.

**Comment by edrozenberg** [comment]
Sounds like it could be related to https://github.com/bazelbuild/bazel/issues/614 yes but I'm seeing the issue even without interrupting anything using CTRL-C. I just ran a successful ./configure and the following process is left over:

```
root     29914  167  0.6 51021036 1312840 ?    Ssl  10:43   1:23 bazel(tensorflow) -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 -Xverify:none -Djava.util.logging.config.file=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93/javalog.properties -Djava.library.path=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/ -Dfile.encoding=ISO-8859-1 -jar /root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4/_embedded_binaries/A-server.jar --max_idle_secs 10800 --install_base=/root/.cache/bazel/_bazel_root/install/26cccb4705ab94af88df4f6dfb1e20c4 --install_md5=26cccb4705ab94af88df4f6dfb1e20c4 --output_base=/root/.cache/bazel/_bazel_root/d63fa4ac02658c8e5f9c2e0f1f523a93 --workspace_directory=/usr/local/src/tensorflow/tensorflow-git --deep_execroot --experimental_oom_more_eagerly_threshold=100 --nofatal_event_bus_exceptions --product_name=Bazel --option_sources=
```

**Comment by jart** [comment]
Bazel keeps a dæmon process in the background in order to make subsequent
invocations of the Bazel command go blazing fast. If this is not what you
want, run `bazel shutdown` after the build, or use the `--batch` flag. This
issue can be closed. The issue I reported regarding persistent workers
shouldn't apply here, because those are opt in.

**Comment by edrozenberg** [comment]
Thanks I'll try ```bazel shutdown``` from now on - a build tool that spawns a daemon was unexpected. I did see up to 2-3 leftover processes at least a couple of times, not just one.

**Comment by jart** [comment]
I would recommend filing an issue with Bazel asking them to display a log message indicating when it's starting a dæmon, which can be shutdown with bazel shutdown. I would support that feature.
