### ISSUE TITLE
TensorFlow Lite Quantization quality parameters.

### ISSUE THREAD

**Issue by bkovalenkocomp** [tensorflow/tensorflow#53186]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version 2.6.1:
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**

It would be great to have quantization pamrameters / threshold to be exposed in API. Usually quantization algorithms have something like desired similarity between original activations histogram and int8 activations or something like this. I assume TFLite has such parameters buried inside. It would be great to have control over them. Perhaps per layer?

**Will this change the current api? How?**

No api breaks.

**Who will benefit with this feature?**

people who use tflite for int8 inference.

**Any Other info.**

I could look into it, please give me pointers.

**Comment by tilakrayal** [comment]
@bkovalenkocomp ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by bkovalenkocomp** [comment]
> @bkovalenkocomp ,
> Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

TFLite neural network layer quantization algorithm has parameters, that control speed of quantization vs quality of quantization, IT would be great to have these parameters exposed in api.

Use case: users can choose tradeoff between need to quantize fast with lower precision or slow quantise with good precision.

**Comment by jvishnuvardhan** [comment]
@bkovalenkocomp This is more related to [TF model optimization](https://github.com/tensorflow/model-optimization/issues) tool. If possible, post it in that repository where model-optimization team is focussing on their efforts to resolve issues faster. Thanks!
