### ISSUE TITLE
group conv2d can't backprop properly

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#53180]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.7.0-rc1-69-gc256c071bb2 2.7.0

**Describe the current behavior**

I extend tf.keras.layers.Conv2D with the public member function convolution_op() to do group convolution. error occurs at backpropagation. if I change the group number to 1, backpropagation is ok.

**Describe the expected behavior**

extended convolution op should support backpropagation of group convolution.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

class WSConv2D(tf.keras.layers.Conv2D):
  def build(self, input_shape):
    super(WSConv2D, self).build(input_shape);
    self.gain = self.add_weight(shape = (tf.shape(self.kernel)[-1],), dtype = tf.float32, initializer = tf.keras.initializers.Ones()); # self.gain.shape = (cout,)
  def call(self, inputs):
    input_shape = inputs.shape;
    if self._is_causal:  # Apply causal padding to inputs for Conv1D.
      inputs = array_ops.pad(inputs, self._compute_causal_padding(inputs));
    # standardize weight
    mean, var = tf.nn.moments(self.kernel, axes = [0, 1, 2], keepdims = True);
    fan_in = tf.cast(tf.math.reduce_prod(tf.shape(self.kernel)[:-1]), dtype = tf.float32); # fan_in.shape = ()
    kernel = self.gain * (self.kernel - mean) / tf.math.sqrt(tf.math.maximum(var * fan_in, 1e-4));
    # convolution
    outputs = self.convolution_op(inputs, kernel);
    if self.use_bias:
      outputs = outputs + self.bias;
    if self.activation is not None:
      return self.activation(outputs);
    return outputs;

inputs = tf.random.normal(shape = (4,224,224,256));
conv2d = WSConv2D(256, (3,3), groups = 4, padding = 'same');
with tf.GradientTape() as tape:
  outputs = conv2d(inputs);
# NOTE: error occurs here
grads = tape.gradient(outputs, conv2d.trainable_weights);
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```shell
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    grads = tape.gradient(outputs, conv2d.trainable_weights);
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1084, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 159, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/ops/nn_grad.py", line 581, in _Conv2DGrad
    gen_nn_ops.conv2d_backprop_input(
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1247, in conv2d_backprop_input
    _ops.raise_from_not_ok_status(e, name)
  File "/home/xieyi/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Computed input depth 256 doesn't match filter input depth 64 [Op:Conv2DBackpropInput]
```

**Comment by sushreebarsa** [comment]
@breadbread1984 Could you please refer to the [api_docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) and similar [issue](https://stackoverflow.com/questions/65417415/tf-keras-layers-conv2d-usage), [issue2](https://github.com/tensorflow/tensorflow/issues/11327),[issue3](https://stackoverflow.com/questions/60803445/tensorflow-keras-error-using-conv2d-input-depth-and-filter-depth-are-not-compati) ,[issue4](https://stackoverflow.com/questions/35488717/confused-about-conv2d-transpose) ?Please let us know if it helps? Thank you!

**Comment by breadbread1984** [comment]
the refered issues mention no group convolution with customized conv layer. I follow the api doc and make sure that "Input channels and filters must both be divisible by groups". channels 256 and filters 256 is divisible by 4. the forward path can be runned without any problem, the backward path causes errors.

**Comment by breadbread1984** [comment]
I found the buildin conv2d has the same problem. so the code to reproduce the issue can be further simplified as the following code

```python
import tensorflow as tf;

inputs = tf.random.normal(shape = (4,224,224,256));
conv2d = tf.keras.layers.Conv2D(256, (3,3), groups = 4, padding = 'same');
with tf.GradientTape() as tape:
  outputs = conv2d(inputs);
# NOTE: error occurs here
grads = tape.gradient(outputs, conv2d.trainable_variables);
```

**Comment by sushreebarsa** [comment]
@sanatmpa1 Was able to replicate the issue on Colab using TF v2.7.0 and tf-nightly, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/0485d198b6761f103fdbde50421e302c/53180.ipynb) for reference .Thank you!

**Comment by sanatmpa1** [comment]
@breadbread1984,

The reported issue mostly looks like Keras related one, So can you please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues),To know more see;[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) you

**Comment by breadbread1984** [comment]
have transferred the issue here https://github.com/keras-team/keras/issues/15713

**Comment by sanatmpa1** [comment]
Thank you @breadbread1984, In this case, Can you close this issue here, as it will be followed up in `Keras` repo?
