### ISSUE TITLE
How to build tensorflow lite C api for Linux on a MacOS machine?

### ISSUE THREAD

**Issue by fzyzcjy** [tensorflow/tensorflow#53183]
Hi thanks for the lib! I need to build tensorflow lite C api for Linux on a MacOS machine. If I do `bazel build -c opt //tensorflow/lite/c:tensorflowlite_c`, I get a `.dylib` that is of mach-o (macos) format instead of a `.so` that is of linux format. Thus I wonder what should I do? Thanks!

I have tried: `--cpu=linux` and its friends (no luck). `--config-linux` (also no use).

**Comment by tilakrayal** [comment]
@fzyzcjy ,
Could you please take a look at this [link](https://www.tensorflow.org/lite/guide/build_ios) which helps for the installation of tensorflowlite.Thanks!

**Comment by fzyzcjy** [comment]
no it is for ios

**Comment by tilakrayal** [comment]
@fzyzcjy ,
Can you please refer this [link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite) for the installation.Thanks

**Comment by fzyzcjy** [comment]
I have tried that

**Comment by tilakrayal** [comment]
@fzyzcjy ,
Can you please provide the error log where you are facing issue.It helps to analyse the issue.Thanks!
