### ISSUE TITLE
Unit test //tensorflow/compiler/xla/tests:xla_hlo_profile_test_cpu gives illegal instruction on AARCH64

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#53189]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): git HEAD
- Python version: 3.8.10
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 11.2.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Test fails as illegal instruction is thrown.

**Describe the expected behavior**

Test passes

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only --copt=-ffp-contract=off --cxxopt=-ffp-contract=off --copt=-Og --copt=-ggdb --verbose_failures -- //tensorflow/compiler/xla/tests:xla_hlo_profile_test_cpu

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

bazel-bin/tensorflow/compiler/xla/tests/xla_hlo_profile_test_cpu
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from HloProfileTest
[ RUN      ] HloProfileTest.ProfileSingleComputation
2021-11-24 17:03:03.560320: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x3c904070 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-24 17:03:03.560415: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): Host, Default Version
2021-11-24 17:03:03.560854: I tensorflow/compiler/xla/service/service.cc:171] XLA service 0x3c904d60 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2021-11-24 17:03:03.560885: I tensorflow/compiler/xla/service/service.cc:179]   StreamExecutor device (0): Interpreter, <undefined>
Illegal instruction (core dumped)

When running under gdb

Thread 70 "xla_hlo_profile" received signal SIGILL, Illegal instruction.
[Switching to Thread 0xfffec6ffcd80 (LWP 420853)]
0x0000fffff7ff8014 in ProfileSingleComputation.5 ()
(gdb) disass
Dump of assembler code for function ProfileSingleComputation.5:
   0x0000fffff7ff8000 <+0>:	str	d12, [sp, #-48]!
   0x0000fffff7ff8004 <+4>:	stp	d11, d10, [sp, #16]
   0x0000fffff7ff8008 <+8>:	stp	d9, d8, [sp, #32]
   0x0000fffff7ff800c <+12>:	mov	x10, xzr
   0x0000fffff7ff8010 <+16>:	ldp	x9, x13, [x3, #8]
=> 0x0000fffff7ff8014 <+20>:	mrs	x8, pmccntr_el0
   0x0000fffff7ff8018 <+24>:	add	x11, x9, #0x20
   0x0000fffff7ff801c <+28>:	ldr	x9, [x3]
   0x0000fffff7ff8020 <+32>:	add	x12, x9, #0x30
   0x0000fffff7ff8024 <+36>:	add	x13, x13, #0x20
   0x0000fffff7ff8028 <+40>:	mov	x14, xzr
   0x0000fffff7ff802c <+44>:	add	x15, x11, x14
   0x0000fffff7ff8030 <+48>:	add	x16, x13, x14
   0x0000fffff7ff8034 <+52>:	ldp	q0, q1, [x15, #-32]
   0x0000fffff7ff8038 <+56>:	ldp	q2, q3, [x16, #-32]
   0x0000fffff7ff803c <+60>:	ldp	q4, q5, [x15]
   0x0000fffff7ff8040 <+64>:	fadd	v0.4s, v0.4s, v2.4s
   0x0000fffff7ff8044 <+68>:	fadd	v1.4s, v1.4s, v3.4s
   0x0000fffff7ff8048 <+72>:	ldp	q2, q3, [x16]
   0x0000fffff7ff804c <+76>:	fadd	v2.4s, v4.4s, v2.4s
   0x0000fffff7ff8050 <+80>:	add	x15, x12, x14
   0x0000fffff7ff8054 <+84>:	stp	q0, q1, [x15, #-48]
   0x0000fffff7ff8058 <+88>:	fadd	v0.4s, v5.4s, v3.4s
   0x0000fffff7ff805c <+92>:	stp	q2, q0, [x15, #-16]
   0x0000fffff7ff8060 <+96>:	add	x14, x14, #0x40
   0x0000fffff7ff8064 <+100>:	cmp	x14, #0x400
   0x0000fffff7ff8068 <+104>:	b.ne	0xfffff7ff802c <ProfileSingleComputation.5+44>  // b.any
   0x0000fffff7ff806c <+108>:	add	x10, x10, #0x1
   0x0000fffff7ff8070 <+112>:	add	x11, x11, #0x400
   0x0000fffff7ff8074 <+116>:	add	x12, x12, #0x400
   0x0000fffff7ff8078 <+120>:	add	x13, x13, #0x400
   0x0000fffff7ff807c <+124>:	cmp	x10, #0x100
   0x0000fffff7ff8080 <+128>:	b.ne	0xfffff7ff8028 <ProfileSingleComputation.5+40>  // b.any
   0x0000fffff7ff8084 <+132>:	mov	x10, xzr
   0x0000fffff7ff8088 <+136>:	mrs	x11, pmccntr_el0
   0x0000fffff7ff808c <+140>:	mov	w12, #0xb717                	// #46871
   0x0000fffff7ff8090 <+144>:	movk	w12, #0x39d1, lsl #16
   0x0000fffff7ff8094 <+148>:	dup	v0.4s, w12
   0x0000fffff7ff8098 <+152>:	mov	w12, #0x25c0                	// #9664
   0x0000fffff7ff809c <+156>:	movk	w12, #0xa59f, lsl #16
   0x0000fffff7ff80a0 <+160>:	dup	v1.4s, w12
   0x0000fffff7ff80a4 <+164>:	mov	w12, #0x337e                	// #13182
   0x0000fffff7ff80a8 <+168>:	movk	w12, #0x2a61, lsl #16
   0x0000fffff7ff80ac <+172>:	dup	v2.4s, w12
   0x0000fffff7ff80b0 <+176>:	mov	w12, #0x37ff                	// #14335
   0x0000fffff7ff80b4 <+180>:	movk	w12, #0xaebd, lsl #16
   0x0000fffff7ff80b8 <+184>:	dup	v3.4s, w12
   0x0000fffff7ff80bc <+188>:	ldr	x12, [x5, #24]
   0x0000fffff7ff80c0 <+192>:	sub	x11, x11, x8
   0x0000fffff7ff80c4 <+196>:	add	x11, x11, x12
   0x0000fffff7ff80c8 <+200>:	str	x11, [x5, #24]
   0x0000fffff7ff80cc <+204>:	mov	w11, #0x41                  	// #65
   0x0000fffff7ff80d0 <+208>:	movk	w11, #0x335c, lsl #16
--Type <RET> for more, q to quit, c to continue without paging--q

So the problem seems to be reading the performance counter register as the illegal instruction flagged is "mrs	x8, pmccntr_el0"

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue?

**Comment by elfringham** [comment]
Reading the documentation at https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/arm64/cpu-feature-registers.rst?h=v5.16-rc2 it seems that it is not possible for a user space application like TensorFlow to read the performance counters directly on AARCH64 Linux.

**Comment by elfringham** [comment]
It seems like the use of llvm::Intrinsic::readcyclecounter at https://github.com/tensorflow/tensorflow/blob/f37b7b1f619a424b420fcaebb7826c76a6eb9627/tensorflow/compiler/xla/service/cpu/ir_emitter.cc#L2939 is not going to work on AARCH64 Linux.

**Comment by d0k** [comment]
XLA's profiling feature is not going to work on ARM/AArch64 unless the system is configured to set `PMUSERENR.EN`. I think the only reasonable thing we can do for now is disabling that test on ARM.

Do you want to send a PR for that? Otherwise I can take a look.

**Comment by elfringham** [comment]
I propose to add the same tag as suggested in #53068 to exclude the test. I will add a PR for this shortly.

This does only deal with the unit tests however. It still leaves the feature in TF and if ever anyone attempts to make use of it on AARCH64, it will fail with SIGILL which is not really that nice for the unlucky user. So if you have some idea of how best to avoid that situation, that would be great, thanks @d0k .
