### ISSUE TITLE
Tested TF Object Detection Models for Jetson Nano

### ISSUE THREAD

**Issue by franferraz98** [tensorflow/tensorflow#53198]
Hi,

I'm currently working on an AI project using an NVIDIA Jetson Nano (4GB) and TensorFlow 2 where we were planning on using a Faster R-CNN Inception ResNet V2 640x640 model. We tried using TF-TRT to reduce the network, but it seems to be too big to fit in, the vRAM memory is not big enough and using Swap doesn't solve the issue.

We have done several tests and, for the moment, the heaviest network from the TensorFlow Model Zoo we managed to get working is the SSD MobileNet V2 FPNLite 640x640.

I've been searching for a list of networks that have been tested on this device for TF2, but I can't seem to find it. I know of the existence of [this list](https://github.com/NVIDIA-AI-IOT/tf_to_trt_image_classification/#models), but it is for TF1 and doesn't involve the TF2 Model Zoo models.

Is there any chance that a list of working models with their speed, memory usage and mAP tested on a common dataset (COCO or similar) will be developed? This would be specially interesting regarding the different methods available to deploy a model, either via CPU, optimized CPU with TFLite, GPU, optimized GPU with TF-TRT, fully optimized with pure TensorRT or any other possible option that I haven't considered.

Thank you in advance.

**Comment by mohantym** [comment]
Hi @franferraz98! Could you check out these threads for answer? [link1](https://github.com/NVIDIA-AI-IOT/tf_trt_models),[link2](https://gilberttanner.com/blog/run-tensorflow-on-the-jetson-nano),[link3](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html). For further assistance , Please raise an query either in [TF forum](https://discuss.tensorflow.org/) as there will be larger community to address this issue.

**Comment by franferraz98** [comment]
Thanks for the quick response. I will open a new topic on the forum, but I'm guessing that I'll need to check myself if the [supported operators](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#supported-ops) match each model and try the pure TensorRT option.

**Comment by mohantym** [comment]
Hi @franferraz98 !Thanks for confirming the same! Did you check the models in  [link1](https://github.com/NVIDIA-AI-IOT/tf_trt_models) too?
