### ISSUE TITLE
ERROR: tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by andreaghezzi** [tensorflow/tensorflow#53199]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs BigSur 11.1
- Python version: 3.9.9
- Bazel version (if compiling from source): bazel 3.7.2

**Describe the problem**
I decided to install tensorflow from source as I had the AVX2 FMA instruction problem and read that one (the only) way to fix it is to have Tensorflow from source. <br>
I followed the guide on the tensorflow site for installing tensorflow from source. 
I have performed almost all the steps and they have been successful, I miss the last one of the installation of the package. <br>

**Provide the exact sequence of commands / steps that you executed before running into the problem** <br>
This is the command that provides me the error:
` pip install /tmp/tensorflow_pkg/tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl`
and this is the ERROR that returned me:
`ERROR: tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.`
<br>
How can I solve this problem?

**Comment by sachinprasadhs** [comment]
Did you try installing from this [source](https://pypi.org/project/tensorflow-macos/2.6.0/#files).

**Comment by andreaghezzi** [comment]
@sachinprasadhs  Yes but also this `pip install tensorflow-macos==2.6.0` I can't install. I need to execute this command `pip install /tmp/tensorflow_pkg/tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl` (is the command above in my question) to complete the tensorflow source installation.

**Comment by sachinprasadhs** [comment]
Could you please post this issue in the dedicated Apple developer forum https://developer.apple.com/forums/ . Thanks!
