### ISSUE TITLE
Converted TFlite image segmentation model crashes in Android.

### ISSUE THREAD

**Issue by Sudhan97** [tensorflow/tensorflow#53191]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android sdk version 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung A10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4
- Python version: 3,9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I have implemented image segmentation model with two stream and was able convert the model into TFlite format. There is no issue when prediction taken using Python API from coverted TFlite. When model in used in Android application using task api library it crashes without any errors in the line below.  It seems there is memory allocation issue when segment method is called. 
```
imageSegmenter.segment(image);
``` 
I have included the link for converted TFlite model below.
https://drive.google.com/drive/folders/1sBRCNNa8c59315wXZ3tPzkINnV_F2o3E?usp=sharing

Android dependancy used.
implementation 'org.tensorflow:tensorflow-lite-task-vision:0.3.0'

**Comment by sushreebarsa** [comment]
@Sudhan97 Could you please try with the latest `TF v2.7.0` and refer to the similar [issue](https://stackoverflow.com/questions/54762245/tensorflow-tf-lite-android-app-crashing-after-detection) , [link](https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_segmenter) of TFlite doc  ? Please let us know if it helps? Thanks!

**Comment by Sudhan97** [comment]
Hi @sushreebarsa, I trained the model and converrted into TFlite format using TF v.2.7.0 it work fine with python tf interpreter api but fails in android.  When imageSegmenter.segment() method is called in Android application it crashes without raising any exceptions. I used the following dependancy in Android and referred to instruction in [link](https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_segmenter#step_2_using_the_model).
`
implementation 'org.tensorflow:tensorflow-lite-task-vision:0.3.0+'
`

**Comment by JunyoungLim** [comment]
Hi @Sudhan97, are you using Android Studio to run the code on your device? Android Studio must have a `Logcat` tab that displays detailed error messages associated with the crash. If you can find it, can you share the error message here?
