### ISSUE TITLE
Restoring mixed placement tf.keras.Model attempts to place CPU variable on GPU.

### ISSUE THREAD

**Issue by rllin** [tensorflow/tensorflow#53196]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `gcr.io/deeplearning-platform-release/tf2-gpu.2-5`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): `gcr.io/deeplearning-platform-release/tf2-gpu.2-5`
- TensorFlow version (use command below): 2.5
- Python version: 3.7
- CUDA/cuDNN version: `NVIDIA-SMI 450.119.04   Driver Version: 450.119.04   CUDA Version: 11.4 `
- GPU model and memory: `V100`

**Describe the current behavior**
1. A model is created where a embedding layer (list of `Variable`s) is placed on CPU and subsequent `Dense` layers are placed according to a given `strategy`.  The embedding layer variables are large and fit on CPU but do not fit on GPU.
2. this model trains (fwd and bwd pass).
3. this model is saved.
3. then an attempt to restore this model is made, but gives the following error, indicating that restoration tries to assign a CPU variable to GPU:
```
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2000000,256] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator gpu_host_bfc [Op:AssignVariableOp]
```
resulting in OOM on GPU.

**Describe the expected behavior**
Restoration of CPU variables should not go through the `gpu_host_bfc` allocator.

**Standalone code to reproduce the issue**

- I ran the following code on a [8xV100 on GCP with 128 GB in GPU memory and 624 GB in RAM](https://cloud.google.com/compute/docs/gpus#other_available_nvidia_gpu_models)

```

import os

from absl import app, flags, logging
import tensorflow as tf

FLAGS = flags.FLAGS

flags.DEFINE_string('workspace', None, '')


class Embeddings(tf.keras.layers.Layer):
  def __init__(self):
    super().__init__()
    with tf.device('cpu:0'):
      self.table = [
        tf.Variable(name=f'shard_{idx}', initial_value=tf.keras.initializers.glorot_normal()([int(2e6), 256]))
        for idx in range(20)
      ]

  def call(self, inputs):
    with tf.device('cpu:0'):
      looked_up = tf.reduce_sum(tf.nn.embedding_lookup(self.table, inputs), axis=1)
    return looked_up


class M(tf.keras.Model):
  def __init__(self, strategy):
    super().__init__()
    with tf.device('cpu:0'):
      self.embeddings = Embeddings()
    with strategy.scope():
      self.mlp = tf.keras.Sequential([tf.keras.layers.Dense(1)])

  def call(self, inputs):
    inputs = self.embeddings(inputs)
    out = self.mlp(inputs)
    return out


strategy = tf.distribute.MirroredStrategy()

model = M(strategy)
loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=True, reduction=tf.keras.losses.Reduction.NONE)
def _replica_loss(labels, logits):
  return tf.nn.compute_average_loss(loss_fn(labels, logits), global_batch_size=10)

with tf.device('cpu:0'):
  emb_optimizer = tf.keras.optimizers.Adam()
with strategy.scope():
  mlp_optimizer = tf.keras.optimizers.Adam()


def split_variables(tv):
  from itertools import filterfalse, tee
  from tensorflow.python.distribute.values import MirroredVariable
  def partition(pred, iterable):
    'Use a predicate to partition entries into false entries and true entries'
    # partition(is_odd, range(10)) --> 0 2 4 6 8   and  1 3 5 7 9
    t1, t2 = tee(iterable)
    return list(filterfalse(pred, t1)), list(filter(pred, t2))
  return partition(lambda v: isinstance(v, MirroredVariable), tv)


def save_or_restore(save_dir: str, step: int , **to_save):
 ckpt = tf.train.Checkpoint(**to_save)
 manager = tf.train.CheckpointManager(ckpt, save_dir, max_to_keep=10)
 latest_checkpoint = tf.train.latest_checkpoint(save_dir)
 if latest_checkpoint is not None:
   logging.info(f'Restoring checkpoint: {latest_checkpoint}')
   ckpt.restore(latest_checkpoint)
 else:
   manager.save(checkpoint_number=step)


def _train_step(inputs, labels):
  with tf.GradientTape() as tape:
    logits = model(inputs)
    loss = _replica_loss(labels, logits)

  emb_var, mlp_var = split_variables(model.trainable_variables)
  emb_grad, mlp_grad = tape.gradient(loss, [emb_var, mlp_var])
  mlp_optimizer.apply_gradients(zip(mlp_grad, mlp_var))

  return loss, emb_var, emb_grad

def distribute_step(step_fn):
  @tf.function
  def _step(*step_args):
    loss, emb_var, emb_grad = strategy.run(step_fn, args=step_args)
    loss = strategy.reduce(tf.distribute.ReduceOp.SUM, loss, axis=None)
    emb_grad = strategy.reduce(tf.distribute.ReduceOp.SUM, emb_grad, axis=None)
    emb_optimizer.apply_gradients(zip(emb_grad, emb_var))
    return loss
  return _step

def main(_argv):
  save_dir = os.path.join(FLAGS.workspace, 'save_dir')

  train_step = distribute_step(_train_step)
  ds = tf.data.Dataset.from_tensors((tf.random.uniform([10, 10], minval=0, maxval=10, dtype=tf.int64), tf.random.uniform([10, 1], minval=0, maxval=1, dtype=tf.int64)))
  ds = strategy.experimental_distribute_dataset(ds)

  for example, label in ds:
    loss = train_step(example, label)
    logging.info(f'loss: {loss}')
    break

  # Save
  logging.info(f'Saving from {save_dir}')
  save_or_restore(
    save_dir=save_dir,
    step=1,
    model=model,
    cpu_optimizer=emb_optimizer,
    gpu_optimizer=mlp_optimizer,
  )

  # Restore
  logging.info(f'Restoring from {save_dir}')
  save_or_restore(
    save_dir=save_dir,
    step=1,
    model=model,
    cpu_optimizer=emb_optimizer,
    gpu_optimizer=mlp_optimizer,
  )


if __name__ == "__main__":
  app.run(main)
```

- It creates an embedding table of 20 shards of ~2GB `Variable`s
- **It trains and saves successfully**
- **However, it fails to restore**

with the following attached full logs [repro_save.txt](https://github.com/tensorflow/tensorflow/files/7600948/repro_save.txt)

**Comment by tilakrayal** [comment]
@rllin ,
Can you please take a look at this issues [1](https://github.com/tensorflow/tensorflow/issues/52132) [2](https://github.com/tensorflow/models/issues/8487) and [3](https://stackoverflow.com/questions/46066850/understanding-the-resourceexhaustederror-oom-when-allocating-tensor-with-shape) with the similar error.Also please try to test the code in latest tf v2.7.It helps.Thanks

**Comment by rllin** [comment]
they do not look the same.  please take a closer look at my error message.  mine is specifically showing a CPU variable trying to be restored thru a GPU allocator.

When i make the CPU variables smaller and restoration works, they appear in CPU as expected.  So it seems like they trigger GPU allocation but are moved to the CPU.

**Comment by rllin** [comment]
Also when using `gcr.io/deeplearning-platform-release/tf2-gpu.2-7`, I get the following error [repro_save_2_7.txt](https://github.com/tensorflow/tensorflow/files/7605694/repro_save_2_7.txt)

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
I have tried in colab with TF version 2.5, 2.7 and nightly version and noticed that session is being crashed. Please, find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/53ce7f0dd9d33d6c8d3f0a46ff15be63/untitled127.ipynb).

**Comment by rllin** [comment]
@tilakrayal this will definitely crash in a colab.

if you look at the code I am creating an embedding layer of 20 variables that take up 40 GB.  You will have to reproduce this on a machine where there is more CPU memory (RAM) than per-device GPU memory.

a little more context:
- my goal is to create a large embedding layer on CPU (RAM is more abundant and I only need to do lookups)
- and then keep downstream layers on GPU (MLPs are smaller and thus fit on GPU but can be computed very fast on GPU)

**Comment by rllin** [comment]
fwiw this problem is not reproducible if you use `memory_limit` to virtualize a setup where GPU memory < CPU memory.  so it cannot be reproduced in colab unless you connect to a GCP instance that is similar to the one I used where CPU memory > per-device GPU memory:

> - I ran the following code on a [8xV100 on GCP with 128 GB in GPU memory and 624 GB in RAM](https://cloud.google.com/compute/docs/gpus#other_available_nvidia_gpu_models)

**Comment by rllin** [comment]
hey @sachinprasadhs lmk if there's anything i can clarify, the repro should be very straightforward, but i can provide any necessary context, thanks!

**Comment by rllin** [comment]
when i look at memory growth, it looks like when writing is in progress, 250% of the model size is needed in memory is needed to hold buffered data before writing begins.  and 130% is needed during restoration.  what my errors are are due to not having 2.5x or 1.3x the amount of memory as model size when saving/restoring.

however i still have a problem with how slow the saving is.  it is only writing to gs:// at about 100 MB/s.  This is far below expected speeds of 2 GB/s.  Is there any control over multithreading when writing to remote?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
