### ISSUE TITLE
Addition of GradCAM visualization option for output visualization of CNNs

### ISSUE THREAD

**Issue by MrinalTyagi** [tensorflow/tensorflow#53195]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
GradCAM visualization is a great algorithm to showcase the activation part of an image from a CNN. As described in this paper(https://arxiv.org/pdf/1610.02391.pdf), it can allow users to visualize the issues their model is making in a more interactive way and fix the models.

**Will this change the current api? How?**
Yes, it will change the current API by the addition of a GradCAM visualization function in utils or the addition of a new visualization module itself. Depends on the admins.

**Who will benefit from this feature?**
It will help users who are using CNN to visualize the issue their model is making in a more interactive way by looking at the class activation map of the image and having a look at which part of the image the model gets activated to predict the class. 

**Any Other info.**
No.

**Comment by mohantym** [comment]
Hi @MrinalTyagi ! But There is already[ GradCAM visualization](https://keras.io/examples/vision/grad_cam/) in Keras ? Are you indicating to include everything as single method?

**Comment by MrinalTyagi** [comment]
@mohantym yeah. Currently, the user has to copy-paste the code from the website and modify it according to their model data and all that. I was thinking of the addition of a single function in utils or a new visualization section in which all these visualization techniques can be included in form of user handy functions. Would love to know your thoughts in the same.

**Comment by innat** [comment]
@MrinalTyagi I like your proposal. There are some 3rd party implementations ([tf.keras viz](https://github.com/keisen/tf-keras-vis)) but to have them on core API would be great of course. However, I think such a request is more fit on [keras](https://github.com/keras-team/keras).

**Comment by MrinalTyagi** [comment]
@innat Thank you for your response. Let's see what @mohantym thinks. Will it be better to add just a method or add a separate section in TensorFlow for visualization.

**Comment by MrinalTyagi** [comment]
@mohantym like in the link @innat provided, there are multiple visualization algorithms. What I was suggesting was to like alongside utils we could add another module of visualization having all these multiple visualization algorithms.

**Comment by mohantym** [comment]
Ok @MrinalTyagi ! Please post this issue with this clarity  on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by MrinalTyagi** [comment]
Sure. I have updated it under keras issues.

**Comment by mohantym** [comment]
Ok! Could you please this issue here as It will be tracked there in Keras repo?

**Comment by MrinalTyagi** [comment]
@mohantym As Keras team is not interested in adding this feature in their core API and wants to rely the users on third-party implementation for the same, is there any option of adding it into TensorFlow or should I scrap off the idea completely?

**Comment by mohantym** [comment]
Hi @MrinalTyagi ! Could you please mention that Keras ticket here?

**Comment by MrinalTyagi** [comment]
> Hi @MrinalTyagi ! Could you please mention that Keras ticket here?
https://github.com/keras-team/keras/issues/15704

**Comment by sachinprasadhs** [comment]
Closing this issue as per the comment here https://github.com/keras-team/keras/issues/15704#issuecomment-984897075
