### ISSUE TITLE
Importing models directly into Python Variables from model files stored in S3 bucket

### ISSUE THREAD

**Issue by altruistcoder** [tensorflow/tensorflow#53190]
Hello,

I have been thinking from quite some time that if it would have been possible to ***import the ML models directly into python variables*** when the model file is actually not at the local disk where the code is running but rather is ***stored in an S3 bucket***.

As we can load a model file/folder present in the local disk using the tensorflow functions like `tf.keras.models.load_model("<model_file_name>")`, is there any possible way to import the model from the model files stored in the S3 bucket?

Because there can be scenarios where we are running some code to import model inside a container and that container has a limited storage bandwidth but we know the model sizes can be extremely large and thus it would become difficult for it to be stored inside a container or a persistent storage.

For, eg. I am able to use the below specified code to import a dataset (CSV File) directly into memory (basically into a python variable) using the ***Pandas*** and the ***Boto3*** library:

```
filename = "dataset/items_dataset.csv"
s3 = boto3.client('s3',
                  aws_access_key_id = '<AWS_ACCESS_KEY_ID>',
                  aws_secret_access_key = '<AWS_SECRET_ACCESS_KEY>')

obj = s3.get_object(Bucket='<AWS_BUCKET_NAME>', Key=filename)
df = pd.read_csv(io.BytesIO(obj['Body'].read()))
df.head()
```
where `dataset/items_dataset.csv` is the path of the dataset file in the S3 bucket. 
<br>
Thus, I wanted to know whether is it possible to have a similar way of importing the model file stored in the S3 bucket without having the need of downloading it to the local disk before loading it to memory through tensorflow functions.

Also, if there is any way of achieving this, then is there any way to do the vice-versa as well, i.e. *to store the model directly into the S3 bucket?*

**Comment by tilakrayal** [comment]
@altruistcoder ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.

**Comment by altruistcoder** [comment]
@tilakrayal I am sorry if it was not clear from the Title but this is not any issue specifically or it maybe I am not sure. I have general query which might be valid for all the versions of Tensorflow and there are no specific steps to reach this.  
I just want to know whether is it possible to directly load a model (using any Tensorflow function) from the model file which is stored in a S3 bucket.  
If yes, can you please instruct me to navigate somewhere where I can get more information regarding how to achieve this. It would be really very helpful for me.

**Comment by tilakrayal** [comment]
@altruistcoder ,
This question is better asked on TensorFlow Forum. Kindly open a tensorflow discussion [forum](https://discuss.tensorflow.org/) issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.

**Comment by altruistcoder** [comment]
Hello @tilakrayal, I have tried asking this on the Tensorflow's forum as well but I haven't got any reply there as well. You can find the topic I created here:
[https://discuss.tensorflow.org/t/importing-models-directly-into-python-variables-from-model-files-stored-in-s3-bucket/6538](https://discuss.tensorflow.org/t/importing-models-directly-into-python-variables-from-model-files-stored-in-s3-bucket/6538)

**Comment by tilakrayal** [comment]
@altruistcoder ,
As it is not a bug or feature request from tensorflow side, we suggest to follow the raise tensorflow forum discussion.Thanks!
