### ISSUE TITLE
Does TF now support neural network inferring on DSP ，using snapdragon 865 equipped with hexagon698

### ISSUE THREAD

**Issue by dxxhjk** [tensorflow/tensorflow#53207]
When i run benchmark on snapdragon 865, it didn't work and said :"Could not create Hexagon delegate: platform may not support delegate or required libraries are missing". Then i checked my chip information, it was equipped with hexagon698. I read the [document](https://www.tensorflow.org/lite/performance/hexagon_delegate) that tensorflow-lite supports hexagon 690 and others, so I want to know whether it supports 698.
```sh
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [models/resnetv1_50_quant.tflite]
Input layers: [input]
Input shapes: [1,224,224,3]
Enable op profiling: [1]
#threads used for CPU inference: [4]
Use Hexagon: [1]
Hexagon profiling: [1]
Loaded model models/resnetv1_50_quant.tflite
loaded libcdsprpc.so
Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
Tensor # 0 is named input_1 but flags call it input
The input model file size (MB): 26.2023
Initialized session in 65.973ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=6 first=100521 curr=80282 min=79211 max=100521 avg=83420.5 std=7670

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=78236 curr=79387 min=76850 max=84289 avg=79728.5 std=1611
```

**Comment by tilakrayal** [comment]
@dxxhjk ,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.

**Comment by dxxhjk** [comment]
I compiled the .so files and benchmark_model file from the latest code yesterday, run benchmark on my android device.

**Comment by dxxhjk** [comment]
In fact, I now change my device into a mobile phone with snapdargon 855 chip and run benchmark again. The result was still not good, Hexagon delegate created successfully, but it said: "Though Hexagon delegate is explicitly applied, the model graph will not be executed by the delegate."
```sh
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [models/resnetv1_50_quant.tflite]
Input layers: [input]
Input shapes: [1,224,224,3]
Enable op profiling: [1]
#threads used for CPU inference: [4]
Use Hexagon: [1]
Hexagon profiling: [1]
Loaded model models/resnetv1_50_quant.tflite
loaded libcdsprpc.so
Hexagon delegate created.
Though Hexagon delegate is explicitly applied, the model graph will not be executed by the delegate.
Tensor # 0 is named input_1 but flags call it input
The input model file size (MB): 26.2023
Initialized session in 69.282ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=10 first=133134 curr=42337 min=42148 max=133134 avg=53368.5 std=26750

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=42322 curr=42725 min=42218 max=42725 avg=42393.8 std=102
```
So how can I run neural network inferring with hexagon?

**Comment by sachinprasadhs** [comment]
For Snapdragon 855 it should be Hexagon 690 which is the listed supported device in the documentation.

**Comment by karimnosseir** [comment]
1) For the unsupported case, can you run this 
adb shell cat /sys/devices/soc0/soc_id
and share the result

2) Is it possible to share the model you're testing ? I'd like to have a look.

Thanks
