### ISSUE TITLE
Keras Nadam optimizer behaves different to `ApplyAdamOp` with `use_nesterov` option

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#53204]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 (but irrelevant)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary (but irrelevant)
- TensorFlow version (use command below): 2.3, 2.7.0, current master
- Python version: 3.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

Nadam as implemented in the kernel via the `use_nesterov` option (`tensorflow/tensorflow/core/kernels/training_ops_gpu.cu.cc`) behaves different to `tf.keras.optimizers.Nadam`.

We observed this problem (here: https://github.com/rwth-i6/returnn/issues/766#issuecomment-979216833) where the model converged in TF 1 with the old Nadam and does not anymore with TF 2 with the new Nadam.

Specifically, in the kernel, you have this code:
```cpp
const T mul_factor = (*lr_) * sqrt(static_cast<T>(1.0) - (*beta2_power_)) /
                     (static_cast<T>(1.0) - (*beta1_power_));

...

auto m_i = m[i];
auto g_i = grad[i];
auto v_i = v[i];

m_i += one_minus_beta1 * (g_i - m_i);
v_i += one_minus_beta2 * (g_i * g_i - v_i);
if (use_nesterov) {
  var[i] -= mul_factor * (m_i * beta1 + one_minus_beta1 * g_i) /
            (epsilon + sqrt(v_i));
} else {
  var[i] -= mul_factor * m_i / (epsilon + sqrt(v_i));
}

m[i] = m_i;
v[i] = v_i;
```
And in the Keras Nadam optimizer, we have this code:
```
g_prime = grad / coefficients['one_minus_m_schedule_new']
m_t = (coefficients['beta_1_t'] * m +
       coefficients['one_minus_beta_1_t'] * grad)
m_t = tf.compat.v1.assign(m, m_t, use_locking=self._use_locking)
m_t_prime = m_t / coefficients['one_minus_m_schedule_next']
v_t = (coefficients['beta_2_t'] * v +
       coefficients['one_minus_beta_2_t'] * tf.square(grad))
v_t = tf.compat.v1.assign(v, v_t, use_locking=self._use_locking)
v_t_prime = v_t / coefficients['v_t_prime_denominator']
m_t_bar = (coefficients['one_minus_m_t'] * g_prime +
           coefficients['m_t_1'] * m_t_prime)
var_t = var - coefficients['lr_t'] * m_t_bar / (
    tf.sqrt(v_t_prime) + coefficients['epsilon'])
```

There are differences is the calculation of `m_t` and `v_t`. While mathematically the same, the variant in the kernel is probably numerically more stable.

Another difference is `mul_factor` vs `lr`.

**Describe the expected behavior**

I would expect that Nadam as implemented in the kernel via the `use_nesterov` option (`tensorflow/tensorflow/core/kernels/training_ops_gpu.cu.cc`, available since TF 1, also still in current master), which could be used via `tensorflow.contrib.opt.NadamOptimizer` in TF 1, is conceptually the same as `tf.keras.optimizers.Nadam`.

**Comment by sushreebarsa** [comment]
@albertz Could you please let us know if we can close this issue as we see the [PR](https://github.com/rwth-i6/returnn/pull/768) is merged? Thanks!

**Comment by albertz** [comment]
> @albertz Could you please let us know if we can close this issue as we see the [PR](https://github.com/rwth-i6/returnn/pull/768) is merged? Thanks!

No, this is just our workaround to avoid the Keras Nadam optimizer by copying the old Nadam optimizer code from TF 1.

Maybe you could do the same in TF 2, i.e. replace the current Keras Nadam optimizer by the old TF 1 Nadam optimizer?

**Comment by albertz** [comment]
First of all, it should be clarified what variant is better:

```cpp
m_i = m_i + one_minus_beta1 * (g_i - m_i);
```
vs
```cpp
m_i = m_i * beta1 + one_minus_beta1 * g_i;
```

I think the first variant is better here. So this can be just adopted in the Keras code.

**Comment by albertz** [comment]
Then, there is this difference in behavior on how `var[i]` (`var_t`) is calculated. This looks really different to me (or I oversee something). So maybe this is wrong in Keras? This should be clarified.

If this is not wrong, it should at least be clearly documented. And then there should maybe be an option to be able to use the old behavior (because in our case, the old behavior seems to work better).

**Comment by albertz** [comment]
But also further, the old TF 1 Nadam optimizer used the native TF ops (`ApplyAdamOp` etc) directly. This is probably a bit more efficient than the pure TF code in the Keras Nadam optimizer. So why not use them?

**Comment by sushreebarsa** [comment]
@albertz 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by albertz** [comment]
Well, yes, I can do that. However, this is only one aspect of the issue here.

Maybe Keras Nadam was anyway always different and the Keras team decides to not change the Keras Nadam to what TF 1 had before. In that case, this stays a TF problem: Because what I need in any case is the Nadam optimizer from TF 1.

Also, the TF op for that is anyway still there.

**Comment by sushreebarsa** [comment]
@albertz Thank you for the update! We see that you have mentioned the issue in [keras repo](https://github.com/keras-team/keras/issues/15710) . Could you please close this ticket as we will track the other one there? FYI 1.x is out of support window and we are supporting 2.4 and later versions.Thanks!

**Comment by albertz** [comment]
I'm not exactly sure how the Keras team decides on this. If they decide that the Keras Nadam optimizer should not be changed, then this issue stays relevant for TensorFlow itself and should not be closed.

**Comment by sachinprasadhs** [comment]
The above linked keras issue was discussed in the keras meeting and you can track the progress there and you can close this issue. Thanks!

**Comment by albertz** [comment]
Thanks!
