### ISSUE TITLE
Feature request: tensorflow.keras layer to let us reorder the channels on a specific dimension of a tensor

### ISSUE THREAD

**Issue by piEsposito** [tensorflow/tensorflow#53203]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): w.7
- Are you willing to contribute it (Yes/No):
- Yes, thou I don't know in how much time I would be able to ship it due to day job.

**Describe the feature and the current behavior/state.**
The feature is a `tf.keras` layer to let us reorder the channels of a specific dimension on during the feedforward operation without having to rely on custom implementation. This would be nice to finetune and deploy models with RGB and BGR without having to change the software that calls the TF Serving API. 

It would be something like
```python
rgb2bgr_layer = tf.keras.layers.ReorderChannel(axis=-1, order[2, 1, 0])
```

**Will this change the current api? How?**
Yes. It would add a new `tf.keras` layer such as the following:

```python
rgb2bgr_layer = tf.keras.layers.ReorderChannel(axis=-1, order[2, 1, 0])
```

**Who will benefit with this feature?**
Everyone who wants to try and deploy different models without changing the software that calls the TF Serving API. 

**Any Other info.**
We can still to something like that-ish with a lambda layer:
```python
tf.keras.layers.Lambda(lambda i: i[..., ::-1])
````

But that just does not seem right. Also, with a native layer things could be done faster on prediction time, which might be a must for some people.

**Comment by piEsposito** [comment]
For instance, if we can do that on TF python API I can do that almost surely.

**Comment by piEsposito** [comment]
Just opened a PR on keras: https://github.com/keras-team/keras/pull/15707 .

**Comment by tilakrayal** [comment]
@piEsposito ,
Please feel free to close this issue here as it has been raised in Keras repo to avoid the duplicacy.Thanks!
