### ISSUE TITLE
Cannot build via pip on macOS ARM64 M1 Apple Silicon

### ISSUE THREAD

**Issue by KTRosenberg** [tensorflow/tensorflow#53210]
I am running macOS 11, python 3.9, and am using ARM64 hardware (Apple Silicon M1). It's a MacBook Air.

Trying to install tensor flow via pip
`pip3.9 install tensorflow-macos==2.6.0`

results in the following error:

```
ERROR: Could not find a version that satisfies the requirement h5py~=3.1.0 (from tensorflow-macos) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.3.0, 3.4.0, 3.5.0, 3.6.0)
ERROR: No matching distribution found for h5py~=3.1.0
```

h5py doesn't currently have a wheel available. I can install from source, for example, by installing using home-brew and the following command:
`HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.1 pip3.9 install --no-binary=h5py h5py==3.1.0`
This just installs without the binary.

However, there's no way for me to specify this in the tensor flowinstallation via pip, so it won't work.

How can we resolve this issue?

**Comment by mohantym** [comment]
Hi @KTRosenberg ! Could you refer these [thread ](https://developer.apple.com/metal/tensorflow-plugin/)for installation. I suggest for 2.5 branch as  2.6 branch is having some issues during model creation in MacOS. You can also build from source referring  this [link](https://www.tensorflow.org/install/source). Thanks!

**Comment by KTRosenberg** [comment]
Oh I see. So does this absolutely require anaconda? I'm in a challenging situation in which a few libraries I depend on entirely have to install tensorflow, so it's not simple to migrate to using conda instead of basic pip, as some of those libraries don't behave under conda.
In other words, the problem isn't just tensorflow. I'm sure the solutions you linked are great standalone. The library interop is not likely to work though for something like this.

Do you anticipate the basic pip installation being usable again sometime in the near future? I imagine things are still transitioning over.
If that's the case, I could hang on a bit longer on an intel-based machine. Hopefully fixes are on the order of a couple of months max? Do you have a sense of how things are coming along?

**Comment by mohantym** [comment]
@KTRosenberg !It is always advised to test the ongoing work in virtual environments  to avoid library conflicts . But you can create virtual environment without Conda too. Attaching relevant [thread](https://www.tensorflow.org/install/pip#ubuntu) for reference .Thanks!

**Comment by KTRosenberg** [comment]
Yes I did this testing, but cannot control what others do and can only hope they’ll figure out everything.

Are the tensorflow people going to work on a simpler installation process using just pip eventually? Not everyone likes conda.

**Comment by mohantym** [comment]
@KTRosenberg ! I feel positive about that too. Feel free to close this issue if it helped. Thanks!
