### ISSUE TITLE
Loading dynamic library cannot find definition of a symbol

### ISSUE THREAD

**Issue by kovkev** [tensorflow/tensorflow#53217]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): using google-research/language
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): installed with pip
- TensorFlow version (use command below): git - v2.7.0-rc1-69-gc256c071bb2 , tf - 2.7.0
- Python version: 3.8.10 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
- GPU model and memory: RTX 3090 , 20GB available

**Describe the current behavior**
The dynamic library file does not have definition/implementation for a symbol
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kevin/pdev/lmrl/language/language/search_agents/muzero/muzero_main.py", line 25, in <module>
    from language.search_agents.muzero import agent_lib
  File "/home/kevin/pdev/lmrl/language/language/search_agents/muzero/agent_lib.py", line 25, in <module>
    from muzero import actor
  File "/home/kevin/pdev/lmrl/language/muzero/actor.py", line 28, in <module>
    from seed_rl import grpc
  File "/home/kevin/pdev/lmrl/language/seed_rl/grpc/__init__.py", line 21, in <module>
    from seed_rl.grpc.python.ops import *  
  File "/home/kevin/pdev/lmrl/language/seed_rl/grpc/python/ops.py", line 25, in <module>
    from seed_rl.grpc.python.ops_wrapper import gen_grpc_ops
  File "/home/kevin/pdev/lmrl/language/seed_rl/grpc/python/ops_wrapper.py", line 25, in <module>
    gen_grpc_ops = tf.load_op_library(
  File "/home/kevin/pdev/lmrl/language/language/search_agents/env/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 59, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/kevin/pdev/lmrl/language/seed_rl/grpc/python/../grpc_cc.so: undefined symbol: _ZN4absl14lts_2020_02_2518container_internal18global_next_sampleE
(env) root@kevin-System-Product-Name:/home/kevin/pdev/lmrl/language# 
```

**Describe the expected behavior**
The libraries load successfully and tensorflow can create the node graph on the gpu

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): fix some dependency?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

It takes some time but setup google-research/language/language/seach_agents/muzero and run muzero_main.py

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @kovkev! 
Could you please share a standalone code to reproduce this issue?

**Comment by kovkev** [comment]
It would require some work but 

Git clone http://github.com/google-research/language.git

Cd language

Pip install -r language/search_agents/requirements.txt

Python3 -m language.search_agents.muzero.muzero_main

**Comment by kovkev** [comment]
I solved this by downgrading my version of tensorflow

**Comment by mohantym** [comment]
Hi @kovkev !Sorry for the late response. I was getting a lot of import errors. I think this issue would suit in this[ repo](https://github.com/google-research/seed_rl/issues).Thanks!
