### ISSUE TITLE
Filesystem FileExists interface is broken

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5321]
The FileSystem define the following interface, which can't handle temporary runtime errors properly but just swallow them (like GCS, HDFS and any customized DFS),
```c++
virtual bool FileExists(const string& fname) = 0;
```
It should be changed to
```c++
virtual Status FileExists(const string& fname) = 0;
```
I can provide a patch if no one is working on this.

**Comment by aselle** [comment]
@jhseu, I'm marking this contributions welcome, assuming you agree with that change.

**Comment by jhseu** [comment]
Yeah, I agree that's an issue. I can make the change, though, because we also have to change the implementation for our internal filesystem.

**Comment by llhe** [comment]
This is more friendly for the caller:
```c++
virtual Status FileExists(const string& fname, bool* result) = 0;
```

**Comment by jhseu** [comment]
Fixed internally. It'll show up during the next sync.

As mentioned in your pull request, we decided on:
```c++
virtual Status FileExists(const string& fname);
```
for consistency with how we've been using these error codes elsewhere.
