### ISSUE TITLE
Error after running `python generate2.py --output_dir=/tmp/out`

### ISSUE THREAD

**Issue by m-ahmadi** [tensorflow/tensorflow#53216]
**System information**
- OS Platform and Distribution: Windows 10 1809 build: 17763.2300
- Mobile device if the issue happens on mobile device: 
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.6.0
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Got no GPU

**Describe the problem**
Followed [these instructions](https://www.tensorflow.org/community/contribute/docs#build_api_docs), but encountered the following error after running `python generate2.py --output_dir=/tmp/out`:

![q](https://user-images.githubusercontent.com/16363767/143685950-4fd00fd2-4b4a-478e-ac65-2592cc21ecd9.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```shell
pip install git+https://github.com/tensorflow/docs

git clone https://github.com/tensorflow/tensorflow
cd tensorflow/tensorflow/tools/docs
python generate2.py --output_dir=/tmp/out
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
[tf.log](https://github.com/tensorflow/tensorflow/files/7611906/tf.log)

**Comment by sachinprasadhs** [comment]
I'm able to run this in colab, I don't see any issue with the source link problem, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/9d6b135d60baa67b6e58d2c50738dfb0/53216.ipynb) for reference.
On your windows machine, could you please try the same steps by creating the virtual environment and fresh install Tensorflow 2.7, if you find the issue again try installing tf-nightly an check.

**Comment by m-ahmadi** [comment]
> try the same steps by creating the virtual environment and fresh install Tensorflow 2.7

<details>
<a href="https://github.com/tensorflow/tensorflow/files/7708994/2.7.txt">log</a>
<img src="https://user-images.githubusercontent.com/16363767/145939594-ba2e774b-9687-4438-992c-5dd051debac4.png" />
</details>

> try installing tf-nightly and check
<details>
<a href="https://github.com/tensorflow/tensorflow/files/7709002/nightly.txt">log</a>
<img src="https://user-images.githubusercontent.com/16363767/145940079-7b678499-d810-4bf1-a55d-4d8cb40b262f.png" />
</details>

**Comment by sachinprasadhs** [comment]
In the `--output_dir` instead of `/tmp/out` create a folder in the same level and give the absolute path and check it.

**Comment by m-ahmadi** [comment]
[log](https://github.com/tensorflow/tensorflow/files/7724436/abs.txt)

note: did not `pull` in `tensorflow` (it still is at 6b13ceba780)

**Comment by wolffg** [comment]
@markmcd might also look at this.

**Comment by markmcd** [comment]
Looks like a recent change wasn't including templates when `pip install`ing on Windows. I've got a PR out to fix that, though this should get us back to the original issue, which I'll check out next.

**Comment by markmcd** [comment]
It looks like the generated links are in Windows path format:

e.g. `tf/summary/audio.md`: 
```
<a target="_blank" href="https://github.com/tensorflow/tensorboard/tree/2.7.0/tensorboard\plugins\audio\summary_v2.py#L32-L125">
```

Smells like `os.path.join` is being used for URLs somewhere.

**Comment by markmcd** [comment]
Quick update - I have a PR in the works to sort this out, but I still need to do some more testing to make sure I've got everything. Should be ready for review tomorrow.

**Comment by markmcd** [comment]
tensorflow/docs@01d385dda9778a426f4d1cc84c60917a21856816 is in, just waiting for tensorflow/docs#1991 and this should be resolved.

**Comment by markmcd** [comment]
Everything is in now, sync to head and see if it works for you now. There's been a bit of churn on this code recently but hopefully it's all working now.

**Comment by m-ahmadi** [comment]
Yes, it works! Thanks! [log](https://github.com/tensorflow/tensorflow/files/7857931/tf.txt)
 
**Just one other thing:**

currently, my python installation sits in `C:\python39`.

so everything works fine when I create the virtual Python environment in the `C:\` drive. (e.g. `C:\foo`)

but if I go to `D:\` drive and create the `venv` in there (e.g. `D:\bar`), then, the following error occurs:
<details>
<a href="https://github.com/tensorflow/tensorflow/files/7858289/log2.txt">log</a>
<img src="https://user-images.githubusercontent.com/16363767/149230678-592cc549-d184-4c8b-8e9f-96f27b34881d.png" />
</details>

I also tried `py .../generate2.py --output_dir=D:\out`, but encountered the same error.

I'm not sure if this counts as an issue,
but I thought it's worth mentioning as long as the attention is on it.

Anyways, thanks again 🙏

**Comment by mohantym** [comment]
Hi @m-ahmadi ! I checked the instructions in this [template ](https://github.com/tensorflow/tensorflow/issues/53216#issue-1065060058) in my local machine with  TF 2.8   and did not get any issue  . Can you please try again after  correcting  the typo in **--output_dir=D:\output** to **--output_dir=D:/out**  ?Thanks!

**Comment by MarkDaoust** [comment]
Hi,

Thanks for your patience on this one.

So the code where it's failing now is here:

https://github.com/tensorflow/docs/blob/6914e839f3b89d4d25c56277108ab2b8d1c18619/tools/tensorflow_docs/api_generator/parser.py#L588

Basically it's trying to determine which file a python object was defined in, and then convert that to a URL pointing to github.

The code path is:
```
def get_defined_in(py_object,  parser_config) -> Optional[FileLocation]:
  base_dirs_and_prefixes = zip(parser_config.base_dir,
                               parser_config.code_url_prefix)
  obj_path = inspect.getfile(py_object)

  code_url_prefix = None
  for base_dir, temp_prefix in base_dirs_and_prefixes:
    rel_path = os.path.relpath(path=obj_path, start=base_dir)
    # A leading ".." indicates that the file is not inside `base_dir`, and
    # the search should continue.
    if rel_path.startswith('..'):
      continue
```

* `base_dirs_and_prefixes` is a list of `(directory, url)` pairs.
* `obj_path` is the file we found this object was defined in.

The code is trying to determine which "base directory" the source lives in, so it can apply the right URL prefix.

So I guess some of the code is installed on `C:` and some is installed on `D:`. So it's trying to document an object it found on C, and it's trying to check if that source file is in a directory on D. I think there's a simple fix here using `pathlib.Path.is_relative_to`.
