### ISSUE TITLE
[Docker] Tensorflow 2.4.4 images are missing from docker hub

### ISSUE THREAD

**Issue by tomzx** [tensorflow/tensorflow#53214]
Tensorflow 2.4.4 has been released 25 days ago, but it appears that the docker images have not made their way to docker hub yet.

Would it be possible to investigate the problem and push the images to docker hub?

Thanks!

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue?

**Comment by mohantym** [comment]
Hi @tomzx ! 
Have you checked [2.8.0 docker image ](https://hub.docker.com/layers/tensorflow/tensorflow/2.8.0/images/sha256-7c01f75d58fadc2cd1109d5baac1925ed131e05925d840b1b49363c794d1c4db?context=explore)yet ?

**Comment by tomzx** [comment]
I do not have a need for this image, I was only letting you know it's unavailable.

Feel free to close if there's no plan to release 2.4.4 on docker hub.

**Comment by mohantym** [comment]
@tomzx ! Thanks for responding . Closing this issue now.
