### ISSUE TITLE
how to run tests in the tensorflow/compiler/mlir/hlo/tests

### ISSUE THREAD

**Issue by yuqj1991** [tensorflow/tensorflow#53227]
Hi,
could you provide sime related command case to run the cases in the tensorflow/compiler/mlir/hlo/tests/*.mlir.

thanks

**Comment by mohantym** [comment]
Hi @yuqj1991 ! Could you please post this query on [TF forum](https://discuss.tensorflow.org/)? Thanks!

**Comment by yuqj1991** [comment]
> Hi @yuqj1991 ! Could you please post this query on [TF forum](https://discuss.tensorflow.org/)? Thanks!

hi， my question is not about the tf error in the using stage. So Please allow me to simplify this issue!

As you know, in the Compiler/mlir module,  there are many tests in the tensorflow/compiler/mlir/hlo/tests
![image](https://user-images.githubusercontent.com/38523749/145782770-a8c0895a-1421-47e7-b622-6b092d325e34.png)

but in the BUILD file, there is not any test command about the test files
![image](https://user-images.githubusercontent.com/38523749/145782889-0069ba91-eafa-414f-930c-a7b0f1a167aa.png)


so i want to know how to add test comman in this BUILD file , so i can verifly the mlir code

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue?

**Comment by sachinprasadhs** [comment]
Hi, Did you have a look into this [file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/hlo/tests/BUILD)? Thanks!
