### ISSUE TITLE
Remove unnecessary GCS customized python code

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5322]
We have a GCS-like file system (blob store) and added the support without any customized python code (event summary input for tensorboard is not needed either).

It's better to clean them up. At least, refactor and clean up the following code because wen shouldn't change any python code when we adding a new file system:
```python
    if (io_wrapper.IsGCSPath(specification) or                                  
        specification.startswith('hdfs://')): 
```

I can contribute if no one is working on this.

**Comment by aselle** [comment]
@jhseu, since you are doing HDFS work, do you have any thoughts on this or know who might be a good person to consult. It seems like these checks could be encapsulated into some kind of filesystem registry, but maybe we already have plans to do that?  If not, please mark this contributions welcome if you agree with the premise.

**Comment by jhseu** [comment]
@llhe Yeah, if you have any ideas about what to do there, contributions are welcome. Perhaps we should just check if it's a URI?

This is very tensorboard-specific code, so I'm not sure it's worth plumbing through filesystem registry from C++ to make it work.

**Comment by jhseu** [comment]
If you send a pull request, mention me on it.

**Comment by llhe** [comment]
@aselle @jhseu I think just check the URI is ok, check if it's start with xyz://, which won't conflict with the event file lists like group_name:/path/to/directory (Looks like the current code has a bug for group_name:xys://?). So it can be fixed without touching the C++ code.
