### ISSUE TITLE
Will benchmark use GPU?

### ISSUE THREAD

**Issue by dxxhjk** [tensorflow/tensorflow#53225]
I'm running bench mark on desktop following the [guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark).
Will this command below use GPU?
```sh
bazel-bin/tensorflow/tools/benchmark/benchmark_model \
  --graph=tensorflow_inception_graph.pb \
  --input_layer="input:0" \
  --input_layer_shape="1,224,224,3" \
  --input_layer_type="float" \
  --output_layer="output:0"
```
If not, how can I run benchmark on GPU?

**Comment by tilakrayal** [comment]
@dxxhjk ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.
