### ISSUE TITLE
How can I find map@50 and ap for whole test data on tflite model?

### ISSUE THREAD

**Issue by Lnazvkl** [tensorflow/tensorflow#53223]
Hi, 
is there any way to find custom trained tflite model map@50 and ap on whole test dataset?

**Comment by sushreebarsa** [comment]
@Lnazvkl 
 Could you please provide more details ? 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by Lnazvkl** [comment]
I have trained yolov4 on my custom dataset, then I converted weights to .pb and then to .tflite, for using on android app, now I need to test my .tflite weights on the whole test dataset to find map@50 and ap on the whole test dataset, but I don't know how I can do this?

**Comment by Lnazvkl** [comment]
> @sushreebarsa
> I have trained yolov4 on my custom dataset, then I converted weights to .pb and then to .tflite, for using on android app, now I need to test my .tflite weights on the whole test dataset to find map@50 and ap on the whole test dataset, but I don't know how I can do this?

@sushreebarsa
I have trained yolov4 on my custom dataset, then I converted weights to .pb and then to .tflite, for using on android app, now I need to test my .tflite weights on the whole test dataset to find map@50 and ap on the whole test dataset, but I don't know how I can do this?

**Comment by Lnazvkl** [comment]
> @Lnazvkl Could you please provide more details ? In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), Thanks!

@sushreebarsa
I have trained yolov4 on my custom dataset, then I converted weights to .pb and then to .tflite, for using on android app, now I need to test my .tflite weights on the whole test dataset to find map@50 and ap on the whole test dataset, but I don't know how I can do this?

**Comment by sachinprasadhs** [comment]
You can refer to the similar tflite YoloV4 implementation [here](https://github.com/hunglc007/tensorflow-yolov4-tflite) and [here](https://haroonshakeel.medium.com/yolov4-on-android-tflite-without-tears-f0d87784e8f9). Let us know if this helps you. Thanks!
