### ISSUE TITLE
How to use benchmark

### ISSUE THREAD

**Issue by dxxhjk** [tensorflow/tensorflow#53237]
I want to use [benchmark tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) to benchmark my compute graph and its individual operators.
I downloaded a Resnet50 saved_model file from tensorflow hub, then i want to frozen it into a .pb file to use benchmark tool. But i dont't know how to frozen it.
I compiled benchmark tool from the latest source code and it was able to run the [demo](https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip).
I want to know how can I frozen a saved_model into a .pb file which is able to be benchmarked by the tool.

**Comment by mohantym** [comment]
Hi @dxxhjk ! You can refer this[ thread](https://www.tensorflow.org/hub/tf2_saved_model) to load models from Tensorflow models from Tensorflow hub using  [hub.Keraslayer() ](https://www.tensorflow.org/hub/api_docs/python/hub/KerasLayer)command , then train and save it in .pb format. For further assistance , Please post on [TF forum](https://discuss.tensorflow.org/). Thanks!
