### ISSUE TITLE
Windows heap corruption caused by upgrading protobuf

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#53234]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
     Windows

- TensorFlow version:
   At https://github.com/tensorflow/tensorflow/pull/52853

- Bazel version (if compiling from source):
  3.7.2
- GCC/Compiler version (if compiling from source):
  MSVC

### Describe the problem
This is a summary of the Windows heap corruption bug discovered when upgrading protobuf in https://github.com/tensorflow/tensorflow/pull/52853#issuecomment-963081770.

In the PR, we tried to upgrade protobuf from 3.9.2 to 3.19.0, but some tf optimizer related tests are failing on Windows with
```
Windows fatal exception: code 0xc0000374
```
The error code indicates a heap corruption. After some investigation, we discovered the problem is caused by:
- How protobuf is linked in TensorFlow on Windows
   On Windows, most of TF C++ code is linked into `_pywrap_tensorflow_internal.pyd` and some extension code is linked into individual pyd files, like `_pywrap_tf_optimizer.pyd`. The later is also linked to the former. However, the protobuf library is statically linked into both dynamic libraries.
- How protobuf works
  Basically, protobuf [deletes some global string in a proto desctructor](https://cs.opensource.google/protobuf/protobuf/+/master:src/google/protobuf/arenastring.h;l=402) after comparing the address of [some global default string](https://cs.opensource.google/protobuf/protobuf/+/master:src/google/protobuf/message_lite.h;l=135). When there are two protobuf runtimes, there are two default strings with different addresses, which caused some memory to be accidentally deleted when mixed together.

 @acozzette also explained why protobuf doesn't work well when linked in multiple places at https://github.com/tensorflow/tensorflow/pull/52853#issuecomment-973138129

### Provide the exact sequence of commands / steps that you executed before running into the problem

To reproduce the original error in a full build:
```
git clone https://github.com/meteorcloudy/tensorflow.git
cd tensorflow
git fetch origin upgrade_protobuf_grpc
configure
bazel test --announce_rc --config=opt tensorflow/python/grappler:memory_optimizer_test --test_arg=MemoryOptimizerSwapTest.testNoSwapping
```

However, the full TF build isn't debuggable, I have constructed [some smaller targets](https://github.com/meteorcloudy/tensorflow/commit/55263135a5b5f71cc254838d6dd97852fb8758a9) to imitate the situation.
To build the minimal reproduce case in a debug build:
```
git clone https://github.com/meteorcloudy/tensorflow.git
cd tensorflow
git fetch origin reproduce_win_heap_corruption_2
configure
bazel run --announce_rc --config=dbg tensorflow/python/grappler:tf_optimizer_wrapper_bin
```

When debugging in Visual Studio, you should be able to see the following:
![image](https://user-images.githubusercontent.com/4171702/143913840-08256bf0-c657-4c74-b5f6-1424b8568b9b.png)

### Possible Solution

To properly solve this problem, we probably need to migrate TF to [cc_shared_library](https://github.com/bazelbuild/rules_cc/blob/main/examples/experimental_cc_shared_library.bzl), which makes dynamic linking more controllable.

**Comment by meteorcloudy** [comment]
FYI @r4nt @mihaimaruseac @learning-to-play

**Comment by mohantym** [comment]
Hi @sanatmpa1 ! Could you please look at  this Issue?

**Comment by learning-to-play** [comment]
Adding @vam-google who's looking at protobuf upgrade.

**Comment by mihaimaruseac** [comment]
Closing due to https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38
