### ISSUE TITLE
error: illegal scale: INF trying Full integer quantization

### ISSUE THREAD

**Issue by laumecha** [tensorflow/tensorflow#53235]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.5 
- TensorFlow version: 2.7.0
- Python version: 3.9.5

**Describe the current behavior**
I am trying to quantize a model using the "Full integer quantization" guide existing in the "Post-training quantization guide". 

If I try to run the Dynamic range quantization the model is quantized correctly. However, when I run the Full integer quantization guide with the dummy dataset I got the following error:
```
Estimated count of arithmetic ops: 134.256 G  ops, equivalently 67.128 G  MACs
fully_quantize: 0, inference_type: 6, input_inference_type: 0, output_inference_type: 0
error: illegal scale: INF
Segmentation fault (core dumped)
```
[EDIT]: I put tensorflow version 3.7.0 instead of 2.7.0

**Comment by tilakrayal** [comment]
@laumecha ,
In order to expedite the trouble-shooting process, could you please provide code snippet and the TensorFlow version you are using.

**Comment by tilakrayal** [comment]
Also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/35625) and [link](https://www.tensorflow.org/lite/performance/post_training_integer_quant) with the similar error.It helps.Thanks

**Comment by laumecha** [comment]
I am using Tensorflow version 2.7.0 installed from pip3. I am also trying to run the same quantize code as the link.
```
def representative_dataset_gen():
    for i in range(1):
        # creating fake images
        data = np.random.rand(1,3,608,608)
        yield [data.astype(np.float32)]

#Import ONNX
modelonnx = onnx.load('model.onnx') # Load the ONNX file
tf_rep = prepare(modelonnx, logging_level="WARN", auto_cast=True)

output_names = [n.name for n in modelonnx.graph.output]

#Run the ONNX model
providers = ['CPUExecutionProvider']

#Export the ONNX model to Tensorflow model
tf_rep.export_graph("model.pb")

#Check the new Tensorflow model
new_model = tf.saved_model.load('model.pb')
#print(new_model.summary())

converter =  tf.compat.v1.lite.TFLiteConverter.from_saved_model("model.pb/")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
tf_lite_model = converter.convert()
# save the converted model
open('yolo.tflite', 'wb').write(tf_lite_model)
                                                                    
```

The dimensions from representative_dataset_gen corresponds to the input of the model. If I remove the dataset line the model is quantized correctly (just the weights). However, now I am trying to quantize all the layers.

**Comment by laumecha** [comment]
I have been able to quantize completely the Resnet50 model with the same code that I posted so I assume that the problem is with my model... my question now is: there are some layers not supported for this type of quantization?

**Comment by sachinprasadhs** [comment]
@laumecha This could be due to some of the layers and ops don't have Tensorflow lite equivalents, and the corresponding model will not be convertible if they can't be elided or fused.
You can check the `ops_compatibility` for lite [here](https://www.tensorflow.org/lite/guide/ops_compatibility).
As of now the tflite layers support is not fully supported, you can see our [roadmap](https://www.tensorflow.org/lite/guide/roadmap#optimization) on tflite to see what can be expected in our future releases and the document does not reflect any type of priority.
