### ISSUE TITLE
nasm Error when compilig for other x86_64 architecture.

### ISSUE THREAD

**Issue by rafariossaa** [tensorflow/tensorflow#53238]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 21.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.9
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 8
- CUDA/cuDNN version: no
- GPU model and memory: no
- Host processor architecture: Coffee Lake  (i7-8750H)
- Destination architecture: Ice Lake

**Describe the problem**
When trying to compile TF for Ice Lake, I got the following error when in the `libjpeg_turbo` dependency:

```
/bin/bash: line 1:  1429 Illegal instruction     (core dumped) bazel-out/k8-opt/bin/external/nasm/nasm -f elf64 -DELF -DPIC -D__x86_64__ -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfig.h)/ -I $(dirname bazel-out/k8-opt/bin/external/libjpeg_turbo/jconfigint.h)/ -I $(dirname external/libjpeg_turbo/simd/nasm/jsimdcfg.inc.h)/ -I $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/ -o $out $(dirname external/libjpeg_turbo/simd/x86_64/jccolext-sse2.asm)/$(basename ${out%.o}.asm)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
 - Clone this repository. I am using master branch
 - Set the following env vars:
 ```bash
export BAZEL_VERSION=
export BUILD_AVX2_CONTAINERS=no
export BUILD_AVX_CONTAINERS=no
export BUILD_CLX_CONTAINERS=no
export BUILD_ICX_CLIENT_CONTAINERS=no
export BUILD_ICX_SERVER_CONTAINERS=yes
export BUILD_PY2_CONTAINERS=no
export BUILD_SKX_CONTAINERS=no
export BUILD_SSH=no

export BUILD_TF_BFLOAT16_CONTAINERS=no
export BUILD_TF_V2_CONTAINERS=yes

export ENABLE_DNNL1=no
export ENABLE_GCC8=no
export ENABLE_HOROVOD=no
export ENABLE_SECURE_BUILD=yes

export FINAL_IMAGE_NAME=test/optimized-tensorflow

export OPENMPI_DOWNLOAD_URL=
export OPENMPI_VERSION=
export HOROVOD_VERSION=
export INSTALL_HOROVOD_FROM_COMMIT=no
export IS_NIGHTLY=no
export RELEASE_CONTAINER=no

export TF_BUILD_VERSION_IS_PR=no
export TF_BUILD_VERSION=master

export TF_DOCKER_BUILD_DEVEL_BRANCH_IS_PR=no
export TF_DOCKER_BUILD_DEVEL_BRANCH=master

export TF_REPO=https://github.com/tensorflow/tensorflow

export ROOT_CONTAINER_TAG=latest-python3.9
export ROOT_CONTAINER=tensorflow/build
```
- go to directory `master/tensorflow/tools/ci_build/linux/mkl`
- run: `build-dev-container.sh`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached

[compilation.log](https://github.com/tensorflow/tensorflow/files/7620570/compilation.log)

I also changed the bazel execution line in the dockerfile to limit the number of jobs and provide more info when faling:
```diff
$ git diff Dockerfile.devel-mkl
diff --git a/tensorflow/tools/ci_build/linux/mkl/Dockerfile.devel-mkl b/tensorflow/tools/ci_build/linux/mkl/Dockerfile.devel-mkl
index 55f68a73..d1c3a35f 100755
--- a/tensorflow/tools/ci_build/linux/mkl/Dockerfile.devel-mkl
+++ b/tensorflow/tools/ci_build/linux/mkl/Dockerfile.devel-mkl
@@ -68,7 +68,7 @@ RUN echo "import /root/.mkl.bazelrc" >>/root/.bazelrc
 # Install futures>=0.17.1 for Python2.7 compatibility mode
 RUN ${PIP} install future>=0.17.1
 
-RUN bazel --bazelrc=/root/.bazelrc build -c opt \
+RUN bazel --bazelrc=/root/.bazelrc build -c opt --jobs=4 --verbose_failures \
     tensorflow/tools/pip_package:build_pip_package && \
     bazel-bin/tensorflow/tools/pip_package/build_pip_package "${TF_NIGHTLY_FLAG}" "${WHL_DIR}" && \
     ${PIP} --no-cache-dir install --upgrade "${WHL_DIR}"/*.whl && \
```

I am not sure if this is the way of doing this kind of compilation of if I need to compile it in a Icelake machine.

**Comment by learning-to-play** [comment]
Please use [TF SIG Build's Docker images](https://github.com/tensorflow/build/tree/master/tf_sig_build_dockerfiles).

**Comment by rafariossaa** [comment]
Hi @learning-to-play ,
  Could you elaborate a little bit more ? As far as I can see, the `build-container-dev.sh` is running a `docker build ... -f Dockerfile.devel-mkl`, and in this dockerfile you can see: `FROM ${ROOT_CONTAINER}:${ROOT_CONTAINER_TAG}`, and those environment variables are set to: 
```
export ROOT_CONTAINER_TAG=latest-python3.9
export ROOT_CONTAINER=tensorflow/build
```
  So it is using the images indicated in the link you provided.

**Comment by rafariossaa** [comment]
I found the issue.

It was that nasm was compiled with AVX instructions (`BUILD_ICX_SERVER_CONTAINERS=yes`) and the machine were I was building TF has not those instructions.

It would be nice if the intermediate tooling used to build TF can be excluded of using those flags and only the final "product" is compiled using them. This way it would be possible to compile on any processor generation.
