### ISSUE TITLE
Error in lowering tf.Where with iree-import-tf

### ISSUE THREAD

**Issue by sun2011yao** [tensorflow/tensorflow#53231]
I use iree-import-tf tool to convert some model, but failed, error log:
<unknown>:0: error: The following illegal operations still remain:
	tf.Where (count: 1)

**Comment by tilakrayal** [comment]
@sun2011yao ,
In order to expedite the trouble-shooting process, could you please provide a code snippet and the TensorFlow version you are using.

**Comment by tilakrayal** [comment]
Also please take a look at this link [1](https://google.github.io/iree/ml-frameworks/tensorflow/#samples) and [2](https://www.tensorflow.org/api_docs/python/tf/where) which provides more information.It helps.Thanks

**Comment by sun2011yao** [comment]
the run command is 'iree-import-tf --tf-import-type=savedmodel_v1 -o=dlrm.mlir dlrm_model'
dlrm model comes from https://github.com/NodLabs/tensorflow-dlrm
It seems that tf->mhlo does not support where op?

**Comment by sun2011yao** [comment]
@tilakrayal

**Comment by sun2011yao** [comment]
using the latest code of tensorflow

**Comment by tilakrayal** [comment]
@sun2011yao ,
Can you please confirm the tensorflow version you are using and also please provide the code snippet to analyse the issue.Thanks!
