### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS when calling tf.debugging.assert_less using tf.uint8

### ISSUE THREAD

**Issue by kretes** [tensorflow/tensorflow#53243]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): collab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-0-gc256c071bb2 2.7.0
- Python version: 3.7.12
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: K80 12GB (collab)

**Describe the current behavior**
tf 2.7 throws `CUDA_ERROR_ILLEGAL_ADDRESS` on calling `tf.debugging.assert_less` using `dtype=tf.uint8` tensors
When running with `CUDA_LAUNCH_BLOCKING` = 1 we can see some more information:

running:
```
a = tf.convert_to_tensor((2,), dtype=tf.uint8)
b = tf.convert_to_tensor((4,), dtype=tf.uint8)
tf.debugging.assert_less(
        a,
        b,
        message="assertion failed",
    )
```
gives:
`InternalError: 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_ILLEGAL_ADDRESS' [Op:Less]`

**Describe the expected behavior**
this worked in tf 2.6, should still work

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1bn9grH_nI76_BtTUvyXVJQt0kZ6TPg0M?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @chunduriv! Could you please look at this issue? It is replicating in  2.7 through GPU mode only. Attaching Gist for reference [2.6_Gpu](https://colab.sandbox.google.com/gist/mohantym/b1292e3f89f18957c2a391082f7b38e3/tf27_debugging_cuda_error_illegal_address.ipynb#scrollTo=pE3cD4RvvfkY),[2.7_CPU](https://colab.sandbox.google.com/gist/mohantym/342925b3b14fcb486a4e2dbc9cf19ef5/tf27_debugging_cuda_error_illegal_address.ipynb#scrollTo=Z4iGqbLWFXAQ),[2.7_Gpu](https://colab.sandbox.google.com/gist/mohantym/8824cec15550d119fb36909fa29e901b/tf27_debugging_cuda_error_illegal_address.ipynb#scrollTo=kJ5d9D7VCI2Q) and[ nightly](https://colab.sandbox.google.com/gist/mohantym/1f53b7b237af5a7bee1186ec6e31ca85/tf27_debugging_cuda_error_illegal_address.ipynb#scrollTo=WKFGmdKuHZQw) for reference.

**Comment by sushreebarsa** [comment]
@kretes This issue is not replicating in TF v2.8.0 on colab ,could you please refer to the gist [here](https://colab.research.google.com/gist/sushreebarsa/e78dc37a7b63b9947c6d4b601d5eed17/tf27_debugging_cuda_error_illegal_address.ipynb) and confirm the same?
Thanks!

**Comment by sushreebarsa** [comment]
@kretes Please refer to the TF [release](https://github.com/tensorflow/tensorflow/releases) note.
Thanks!
