### ISSUE TITLE
Small documentation error in iOS Example

### ISSUE THREAD

**Issue by JosiahKane** [tensorflow/tensorflow#5324]
I'm following the wonderfully comprehensive instructions here (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/ios_examples/README.md)  for building an iOS project with tensorflow with the makefile system. 

The instructions, in the section "creating your own app" suggest adding 
tensorflow/contrib/makefile/downloads/eigen-latest
to the header search paths; however this folder does not exist after running the make scripts.
I believe it should be changed to 
tensorflow/contrib/makefile/downloads/eigen

(I have not seen anything suggesting tensorflow can be built for iOS using bazel, so I assume that this remains the recommended approach.)

**Comment by aselle** [comment]
@petewarden, can you confirm this fix is correct?

**Comment by petewarden** [comment]
Yes, I believe it is correct.
