### ISSUE TITLE
tfhub yamnet model can't perform batch prediction

### ISSUE THREAD

**Issue by AlejandroBaron** [tensorflow/tensorflow#53246]
I'm trying to use a pretrained model to extract embeddings.

Single observation
```
X = np.random.uniform(-1,1,(10, 1000)) # 10 samples of length 1000
yamnet_model_handle = 'https://tfhub.dev/google/yamnet/1'
yamnet_model = hub.load(yamnet_model_handle)

yamnet_model(X[0]) # Works, outputs (scores, embeddings, spectrogram)
```

Multiple observations does not work
```
yamnet_model(X) # Doesn't work
hub.KerasLayer(yamnet_model_handle, 
               trainable=False,)(X) #Doesn't work either
````

How can I get the output for all observations in X at once? Is this intended?

**Comment by pierrejeambrun** [comment]
Hi @AlejandroBaron,

It looks like the model only take a one dimensional waveform. `(num_samples,)`, then batch inference might not be available off the bat.

On the other hands your waveform will be split in "patches", and you will get as many `predictions` and `embeddings`. (1 of each for each patch).

With this in mind, an idea would be to flatten your 10 waveforms in one so they result in 10 patches. You will get your 10 embeddings and 10 classes, 1 for each patch i.e time frame.

Your input is padded first before going through the network by the [pad_waveform](https://github.com/tensorflow/models/blob/238922e98dd0e8254b5c0921b241a1f5a151782f/research/audioset/yamnet/features.py#L82) function. Your first time frame will be of size `15600`, then afterwards each hop is about `7680`.

Pad manually your 10 waveforms, the first to a size of 15600, and the 9 following to a size of 7680. Concatenate everything and run the inference.

:warning:  I'm not sure about this one as this is a bit hacky, let me know if this helps.

> Note: This is a little bit different for the `spectrograms` as you will get more than 10 of them. Spectograms frames have their own calculation.

**Comment by sanatmpa1** [comment]
@AlejandroBaron,

If this issue is related to `yament` from `tfhub`, Can you post this issue on [tfhub repo](https://github.com/tensorflow/hub/issues)? Thanks!
