### ISSUE TITLE
iOS using TFLiteC API TfLiteInterpreterInvoke() cause memory continues increasing on Metal delegate mode

### ISSUE THREAD

**Issue by fakeyee** [tensorflow/tensorflow#53241]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):not really
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 12
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- GPU model and memory: GPU(Metal)

**Describe the current behavior**
I'm using TensorFlowLiteC API to handle video per frame. The model I used is trained by myself. The memory continues increasing while using Metal delegate after called TfLiteInterpreterInvoke() method.  This issue not happens while using CPU mode on iOS, and not happened on Android using GPU.

I'm running this demo code 30 times to simulate a 30 seconds duration video. And invoke the interpreter 30 times in one second to simulate 30 fps. The picture bellow shows memory decrease between the twice play event.

![3491638255212_ pic_hd](https://user-images.githubusercontent.com/3894482/144003649-acddafa6-2c6d-421a-b72d-fe735ff3d339.jpg)

Note: If the video is long enough,  the app will crash!!!

The memory usage using CPU mode:

![3471638254474_ pic_hd](https://user-images.githubusercontent.com/3894482/144006077-c15e9caa-4227-4164-989e-adacf1934f30.jpg)

**Describe the expected behavior**
Hope the memory not increasing continuously while using Metal delegate on iOS. 

**Standalone code to reproduce the issue**
The attachment bellow is the demo project to reproduce the issue. Please execute `pod install`  and then configure the code signing to run on iPhone (not simulator). After launch the app, please press the button `start`. You can see the issue.

PS: I don't think the model is the problem. Because using `mobilenet_v1_1.0_224.tflite` model has the same problem.
[demo.zip](https://github.com/tensorflow/tensorflow/files/7623664/demo.zip)

Any suggestion is appreciate. Thanks. 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
there seems no useful log output

**Comment by fakeyee** [comment]
I think I have resolve the problem, I add `@autoreleasepool{}` before invoke interpreter. I will close the issue. Thank you!

**Comment by espbee** [comment]
@fakeyee did this indeed solve the problem?
