### ISSUE TITLE
Quantized model demonstrates bad performance on DSP compared to CPU

### ISSUE THREAD

**Issue by aviaisr** [tensorflow/tensorflow#53247]
I trained the same binary segmentation model with the same architecture with TF2.2.0 vs TF2.4.0.
I converted the 2.4.0 model to a quantized TFlite and got inferior performance on DSP compared to CPU. 
By inferior performance, I mean that most of the maps are empty / contain very few white pixels, while the maps on the CPU seem as expected. 
The 2.2.0 model (2.2.0) showed similar results on both CPU and DSP.   

What can be the problem?

**Comment by mohantym** [comment]
Hi @aviaisr! 
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by aviaisr** [comment]
### 1. System information

Tensor flow versions: 2.2.0 vs. 2.4.0

### 2. Code

I copied the main training lines of both training session to this notebook:
Note: 1st model trained with TF 2.2.0 :quantized tflite model demonstrates the similar segmentation outputs on CPU and DSP.
2nd model trained with TF2.4.0: quantized tflite model demonstrates bad output maps on the DSP and the results doesn’t match the CPU outputs.
https://colab.research.google.com/drive/14rghRb2-0kknbCfSnxcU3WR4mI8mL9La?authuser=1#scrollTo=TWL3gEpKIm0B

### 3. Failure after conversion
The conversion is successful, but the generated model gives bad results on DSP
![image](https://user-images.githubusercontent.com/39811082/144209418-1c3ee009-f240-423b-af84-db52e0897906.png)

**Comment by mohantym** [comment]
Ok @aviaisr ! Above notebook seems to be restricted. Did you check in latest version TF 2.7 too?

**Comment by aviaisr** [comment]
I updated the link to the notebook. Can you please try again?

Another important note- I continued investigating and saw that when I loaded the model trained with TF 2.2 in two different ways
1. With load_model + compile =False, I get this number of trainable parameters;

Total params: 3,136,005
**Trainable params: 911,913**
Non-trainable params: 2,224,092

2. When I initialize the model and Just load the weights I get a different number of trainable params:

Total params: 3,136,005
**Trainable params: 3,101,673**
Non-trainable params: 34,332

What is the reason for that?

**Comment by aviaisr** [comment]
I uploaded the Keras hdf5 file + quantized TFLite file here:
https://drive.google.com/drive/folders/1IoUiItzZ1ePoQCQmH0Yy2EA7eCiEq9Fo?usp=sharing

**Comment by aviaisr** [comment]
BTW, I tried converting from Keras to quantized TFLite with TF2.7 the model I trained with 2.4, which shows the difference between DSP and CPU, and got empty maps on both...

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by sachinprasadhs** [comment]
Could you please train the model in the latest version and try again, this can be due to the changes made in the saved models after Tensorflow version 2.4.

**Comment by aviaisr** [comment]
I ran a short training with TF2.7 and I do see matching results DSP vs CPU after saving the HDF5 and converting to quantized TFLite.
![image](https://user-images.githubusercontent.com/39811082/145179616-5ea84690-6b87-428f-97c1-8327c19ddf09.png)

My model was trained for over a month over millions of images. Any chance I can do something to fix this issue in the existing model without re-training it?

**Comment by aviaisr** [comment]
Hi,
Any chance you can help me with the model I already trained on 2.4? It was trained for over a month and I need it to work soon. Re-training will take a lot of time.
Thanks.

**Comment by aviaisr** [comment]
Update - I tried to train my model with the large (4.5M) images and checked the results ~20 epochs - and the CPU DSP results were completely different as well with **TF version 2.7**. So updating the version didn't solve the problem. What should I do?
![image](https://user-images.githubusercontent.com/39811082/146264788-9a40782f-542b-42fe-90c0-75edc925663f.png)

**Comment by aviaisr** [comment]
Hi,
I continued debugging and tried training different versions and I suspect that the problem is different. I get matching results CPU and DSP when the maps contains low values, and none matching results when the maps contain high values. Hence, I suspect it is an overflow issue and that the values are being clamped.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
