### ISSUE TITLE
Adding GPU delegate fails for (mediapipe) Hand landmarks TFLite model in C API

### ISSUE THREAD

**Issue by Abhijit16** [tensorflow/tensorflow#53240]
I am trying to run handlandmark TFLite model in a Visual C++ 2022 project (running it on Windows 10 desktop) and am using TensorFlowLite's C API (I have built tensorflow 2.6.0 from source & am using it's dynamic library dll linked with my project) to locate the hand landmark points, after using the palm detector model. I am using GPU delegate for both palm detector model as well as hand landmark model, downloaded from below mediapipe link:

https://google.github.io/mediapipe/solutions/models.html#hands

However, while adding & using GPU delegate for palm detector model works prefectly, adding GPU delegate for hand landmark model fails (maybe in TfLiteInterpreterOptionsAddDelegate()), as the function TfLiteInterpreterCreate() returns NULL.
Note that if I do not use GPU delegate, the interpreter creation works fine, & I am also able to locate and display the 21 hand landmarks correctly in the image/frame.

There is no error or crash reported, only that debugging indicates that the interpreter creation function returns NULL, if GPU delegate is added to interpreter options.

Below is the code snippet:

```
//string hand_model_name = <path to hand landmark model>.

TfLiteModel *m_hand_landmark_model = TfLiteModelCreateFromFile(hand_model_name.c_str());	
	if (!m_hand_landmark_model)
		return kTfLiteError;

	// set GPU delegate for faster inference in TFLite.
	TfLiteGpuDelegateOptionsV2 gpu_options = TfLiteGpuDelegateOptionsV2Default();
	TfLiteDelegate *m_hand_gpu_delegate = TfLiteGpuDelegateV2Create(&gpu_options);
	TfLiteInterpreterOptions *m_tfl_hand_interpreter_options = TfLiteInterpreterOptionsCreate();
	
	TfLiteInterpreterOptionsAddDelegate(m_tfl_hand_interpreter_options, m_hand_gpu_delegate); // hand interpreter creation fails due to this function failing. If comment this line, below function creates the interpreter as desired.

	// (2) create interpreter.
	TfLiteInterpreter *m_hand_interpreter = TfLiteInterpreterCreate(m_hand_landmark_model, m_tfl_hand_interpreter_options);
	if (!m_hand_interpreter)
		return kTfLiteError;
```

   Can anyone please help me out on why this issue is coming & how to resolve it ? 

Thanks,
Abhijit.

**Comment by impjdi** [comment]
```
in a Visual C++ 2022 project (running it on Windows 10 desktop)
```

This is not gonna work unless you make sufficient plumbing to enable OpenGL for your Windows desktop.  It's also not an intended use case; we haven't explored desktop usage AT ALL, only mobile GPUs (Adreno, Mali, PowerVR, and Apple iPhone GPUs), and thus don't know whether things will work or not.  We've seen the delegate used in a linux desktop with Mesa, but I personally didn't manage to make it to work.

**Comment by Abhijit16** [comment]
@impjdi , thanks for the info.... 

I use the palm detector in the same code too, just above the provided snippet (that has same code for using GPU delegate; only the model name differs), & that works as desired with the GPU delegate on desktop, so I believe that this should too; could it be that the hand landmark model has something that disallows using GPU delegate ?

Could you elaborate, if possible, what extra do I need to enable regarding openGL/openCL on my desktop so that I can make this run ?
