### ISSUE TITLE
 
 ​  ​puts​ ​"I got some JSON: ​#{​push​.​inspect​}​"

### ISSUE THREAD

**Issue by Jurek54321** [tensorflow/tensorflow#53255]
https://github.com/github/platform-samples/blob/master/hooks/ruby/configuring-your-server/server.rb#L6

**Comment by chunduriv** [comment]
@Jurek54321,
Please take a look at [issue](https://stackoverflow.com/questions/63870668/how-to-get-request-body-as-json-with-sinatra-in-ruby), [issue1](https://stackoverflow.com/questions/5694139/ruby-receive-and-print-json-object) may help you. Thanks!

**Comment by mihaimaruseac** [comment]
Doesn't seem related to TF.
