### ISSUE TITLE
different convergence behavior and performance if including 2nd order gradient in loss function via two slightly different ways

### ISSUE THREAD

**Issue by UsherWang** [tensorflow/tensorflow#53266]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 20H2, OS build 19042.1348
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): anaconda pip install
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: Python 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: cuda10.0/cudnn11.5
- GPU model and memory: 2080TI

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
In this model a 2nd order gradient is included in loss function as part of regularization term. A significant different convergence behavior is found when calculating 2nd order in two slightly different ways:

with tf.GradientTape(persistent=True) as tape_bnd:
    ...
    tape_bnd.watch(input_bulk_x)
    with tf.GradientTape(persistent=True) as tape_bulk2:
        tape_bulk2.watch(input_bulk_x)
        tape_bulk2.watch(input_bulk_t)
        bulk_pack = tf.concat([input_bulk_x, input_bulk_t], 1)
        prediction_bulk = tf_model(bulk_pack, training=True)
        prediction_bulk_r = prediction_bulk[:,0:1]  (prediction_bulk_r = prediction_bulk[:,0])
        prediction_bulk_i = prediction_bulk[:,1:2]  (prediction_bulk_i = prediction_bulk[:,1])
    ...
    grad_x_r = tape_bulk2.gradient(prediction_bulk_r, input_bulk_x) / (pbin[1] - pbin[0]) * 2
    grad_x_i = tape_bulk2.gradient(prediction_bulk_i, input_bulk_x) / (pbin[1] - pbin[0]) * 2
    del tape_bulk2
...
grad_xx_r = tape_bnd.gradient(grad_x_r, input_bulk_x) / (pbin[1] - pbin[0]) * 2
grad_xx_i = tape_bnd.gradient(grad_x_i, input_bulk_x) / (pbin[1] - pbin[0]) * 2
del tape_bnd

In above code, the following lines:
prediction_bulk_r = prediction_bulk[:,0:1]  (prediction_bulk_r = prediction_bulk[:,0])
prediction_bulk_i = prediction_bulk[:,1:2]  (prediction_bulk_i = prediction_bulk[:,1])
represents two different ways to divide an n by 2 tensor prediction_bulk into two n tensors before calculating 2nd order gradient, 
prediction_bulk_r = prediction_bulk[:,0:1] keeps dimension so prediction_bulk_r is n by 1
prediction_bulk_r = prediction_bulk[:,0] doesn't so prediction_bulk_r  dimension is n

During training process, at initial training step both methods print the same loss, meaning both 2nd order gradient operators return with approximately the same value. But after about 100 steps, for  (prediction_bulk_r = prediction_bulk[:,0]) method the loss no longer decreases, but for prediction_bulk_r = prediction_bulk[:,0:1] method loss decreases smoothly. 

Following are the training outputs for both methods: (loss_loc =lt_loc +lbc_loc +lb_loc )
prediction_bulk_r = prediction_bulk[:,0:1]:
Finished epoch 0 , loss_loc =  0.965272963 , lt_loc =  0.95177114 , lbc_loc =  0.00729189115 , lb_loc =  0.00620991644
Finished epoch 10 , loss_loc =  0.57811451 , lt_loc =  0.569292963 , lbc_loc =  0.000788190926 , lb_loc =  0.00803333055
Finished epoch 20 , loss_loc =  0.454473078 , lt_loc =  0.451767802 , lbc_loc =  0.000194555934 , lb_loc =  0.00251073623
Finished epoch 30 , loss_loc =  0.448864669 , lt_loc =  0.442887783 , lbc_loc =  0.000913872384 , lb_loc =  0.00506302295
Finished epoch 40 , loss_loc =  0.446891814 , lt_loc =  0.441026747 , lbc_loc =  0.000472803076 , lb_loc =  0.00539224083
Finished epoch 50 , loss_loc =  0.441752672 , lt_loc =  0.437939882 , lbc_loc =  0.000413463975 , lb_loc =  0.00339930598
Finished epoch 60 , loss_loc =  0.434724897 , lt_loc =  0.431893885 , lbc_loc =  0.000759351416 , lb_loc =  0.00207163556
Finished epoch 70 , loss_loc =  0.418205 , lt_loc =  0.412783265 , lbc_loc =  0.00237809378 , lb_loc =  0.00304362969
Finished epoch 80 , loss_loc =  0.377492219 , lt_loc =  0.360962123 , lbc_loc =  0.00959464908 , lb_loc =  0.00693544187
Finished epoch 90 , loss_loc =  0.303197145 , lt_loc =  0.260590762 , lbc_loc =  0.0136152282 , lb_loc =  0.0289911665
Finished epoch 100 , loss_loc =  0.239446223 , lt_loc =  0.156737462 , lbc_loc =  0.0188848432 , lb_loc =  0.0638239235
Finished epoch 110 , loss_loc =  0.184993118 , lt_loc =  0.11391528 , lbc_loc =  0.0112376083 , lb_loc =  0.0598402321
Finished epoch 120 , loss_loc =  0.158851862 , lt_loc =  0.105409048 , lbc_loc =  0.00738385599 , lb_loc =  0.0460589677
Finished epoch 130 , loss_loc =  0.14423281 , lt_loc =  0.096214287 , lbc_loc =  0.00382424705 , lb_loc =  0.0441942662
Finished epoch 140 , loss_loc =  0.135551393 , lt_loc =  0.0879743248 , lbc_loc =  0.00334015535 , lb_loc =  0.0442369059
Finished epoch 150 , loss_loc =  0.127870142 , lt_loc =  0.0826394185 , lbc_loc =  0.0032730191 , lb_loc =  0.0419577062
Finished epoch 160 , loss_loc =  0.124033585 , lt_loc =  0.0774272084 , lbc_loc =  0.00544774719 , lb_loc =  0.0411586352
Finished epoch 170 , loss_loc =  0.11641103 , lt_loc =  0.0722029954 , lbc_loc =  0.00310491584 , lb_loc =  0.0411031172
Finished epoch 180 , loss_loc =  0.112142481 , lt_loc =  0.0685963407 , lbc_loc =  0.00335948449 , lb_loc =  0.0401866585
Finished epoch 190 , loss_loc =  0.10562592 , lt_loc =  0.0646096841 , lbc_loc =  0.00248501729 , lb_loc =  0.0385312214
Finished epoch 200 , loss_loc =  0.102625497 , lt_loc =  0.0603574775 , lbc_loc =  0.00585670117 , lb_loc =  0.0364113152
Finished epoch 210 , loss_loc =  0.0917019099 , lt_loc =  0.0549113117 , lbc_loc =  0.00164440088 , lb_loc =  0.0351461954
Finished epoch 220 , loss_loc =  0.086815238 , lt_loc =  0.050563138 , lbc_loc =  0.00135485874 , lb_loc =  0.0348972455
Finished epoch 230 , loss_loc =  0.0829412341 , lt_loc =  0.0474774539 , lbc_loc =  0.00106860022 , lb_loc =  0.0343951844
Finished epoch 240 , loss_loc =  0.0905935 , lt_loc =  0.0465794131 , lbc_loc =  0.0101005193 , lb_loc =  0.0339135714
Finished epoch 250 , loss_loc =  0.0806988478 , lt_loc =  0.0442230441 , lbc_loc =  0.00325619429 , lb_loc =  0.0332196057
Finished epoch 260 , loss_loc =  0.0765827522 , lt_loc =  0.0422764085 , lbc_loc =  0.00129232195 , lb_loc =  0.0330140218
Finished epoch 270 , loss_loc =  0.0742470622 , lt_loc =  0.0410219878 , lbc_loc =  0.000781063805 , lb_loc =  0.0324440114
Finished epoch 280 , loss_loc =  0.0724530667 , lt_loc =  0.0398085974 , lbc_loc =  0.000717243936 , lb_loc =  0.031927228
Finished epoch 290 , loss_loc =  0.0706587136 , lt_loc =  0.0384904146 , lbc_loc =  0.000621825 , lb_loc =  0.0315464735
Finished epoch 300 , loss_loc =  0.0689978376 , lt_loc =  0.0371541791 , lbc_loc =  0.000595943304 , lb_loc =  0.0312477164

prediction_bulk_r = prediction_bulk[:,0]:
Finished epoch 0 , loss_loc =  0.965273 , lt_loc =  0.95177114 , lbc_loc =  0.00729189115 , lb_loc =  0.00620994624
Finished epoch 10 , loss_loc =  0.578066528 , lt_loc =  0.56924212 , lbc_loc =  0.000787865836 , lb_loc =  0.00803656224
Finished epoch 20 , loss_loc =  0.455324501 , lt_loc =  0.451724261 , lbc_loc =  0.000195783374 , lb_loc =  0.00340447319
Finished epoch 30 , loss_loc =  0.450048655 , lt_loc =  0.442762583 , lbc_loc =  0.000911012234 , lb_loc =  0.00637508277
Finished epoch 40 , loss_loc =  0.447754472 , lt_loc =  0.441224217 , lbc_loc =  0.000452358043 , lb_loc =  0.00607788702
Finished epoch 50 , loss_loc =  0.443184465 , lt_loc =  0.438365817 , lbc_loc =  0.00038639488 , lb_loc =  0.0044322731
Finished epoch 60 , loss_loc =  0.43666774 , lt_loc =  0.432844132 , lbc_loc =  0.000703800179 , lb_loc =  0.00311980979
Finished epoch 70 , loss_loc =  0.422279418 , lt_loc =  0.415714264 , lbc_loc =  0.00206818013 , lb_loc =  0.00449697534
Finished epoch 80 , loss_loc =  0.389064491 , lt_loc =  0.371193707 , lbc_loc =  0.00833481457 , lb_loc =  0.00953596272
Finished epoch 90 , loss_loc =  0.328366399 , lt_loc =  0.281947851 , lbc_loc =  0.0159796905 , lb_loc =  0.0304388851
Finished epoch 100 , loss_loc =  0.27213338 , lt_loc =  0.184210449 , lbc_loc =  0.0128458692 , lb_loc =  0.0750770569
Finished epoch 110 , loss_loc =  0.250225097 , lt_loc =  0.15421848 , lbc_loc =  0.00745057128 , lb_loc =  0.0885560513
Finished epoch 120 , loss_loc =  0.243634969 , lt_loc =  0.156038091 , lbc_loc =  0.00717799319 , lb_loc =  0.0804188848
Finished epoch 130 , loss_loc =  0.238658771 , lt_loc =  0.155048981 , lbc_loc =  0.0044888882 , lb_loc =  0.0791209042
Finished epoch 140 , loss_loc =  0.234584287 , lt_loc =  0.149133667 , lbc_loc =  0.00342479628 , lb_loc =  0.082025826
Finished epoch 150 , loss_loc =  0.232386291 , lt_loc =  0.147789568 , lbc_loc =  0.00371110067 , lb_loc =  0.0808856115
Finished epoch 160 , loss_loc =  0.230131447 , lt_loc =  0.147337914 , lbc_loc =  0.00357931526 , lb_loc =  0.0792142153
Finished epoch 170 , loss_loc =  0.228197023 , lt_loc =  0.145577312 , lbc_loc =  0.00342653901 , lb_loc =  0.0791931748
Finished epoch 180 , loss_loc =  0.226216674 , lt_loc =  0.143941388 , lbc_loc =  0.00312073436 , lb_loc =  0.0791545585
Finished epoch 190 , loss_loc =  0.224205345 , lt_loc =  0.142434448 , lbc_loc =  0.00279783597 , lb_loc =  0.0789730474
Finished epoch 200 , loss_loc =  0.222144008 , lt_loc =  0.140951037 , lbc_loc =  0.00249917456 , lb_loc =  0.0786937848
Finished epoch 210 , loss_loc =  0.220653415 , lt_loc =  0.139468715 , lbc_loc =  0.00276256143 , lb_loc =  0.0784221515
Finished epoch 220 , loss_loc =  0.22345908 , lt_loc =  0.139065936 , lbc_loc =  0.00693785353 , lb_loc =  0.0774553
Finished epoch 230 , loss_loc =  0.217616767 , lt_loc =  0.136467338 , lbc_loc =  0.00320873177 , lb_loc =  0.077940695
Finished epoch 240 , loss_loc =  0.214142546 , lt_loc =  0.134901837 , lbc_loc =  0.00151732983 , lb_loc =  0.0777233839
Finished epoch 250 , loss_loc =  0.211947292 , lt_loc =  0.132908329 , lbc_loc =  0.00112436293 , lb_loc =  0.0779145882
Finished epoch 260 , loss_loc =  0.209894076 , lt_loc =  0.131119698 , lbc_loc =  0.000880624109 , lb_loc =  0.0778937489
Finished epoch 270 , loss_loc =  0.207739949 , lt_loc =  0.128978983 , lbc_loc =  0.000651250419 , lb_loc =  0.0781097189
Finished epoch 280 , loss_loc =  0.206072122 , lt_loc =  0.126908109 , lbc_loc =  0.000791691651 , lb_loc =  0.078372322
Finished epoch 290 , loss_loc =  0.204720557 , lt_loc =  0.125317663 , lbc_loc =  0.00118191785 , lb_loc =  0.0782209784
Finished epoch 300 , loss_loc =  0.205160156 , lt_loc =  0.123641305 , lbc_loc =  0.00302041182 , lb_loc =  0.078498438

Another observation is that when using prediction_bulk_r = prediction_bulk[:,0] method, the average training speed per step is way slower than prediction_bulk_r = prediction_bulk[:,0:1] case.

My thought here is since when applying GradientTape.gradient() method to a tensor target, it adds all gradient from all target entries together to produce a gradient tensor with the same shape of source tensor, thus the dimension of tensor prediction_bulk_r (either n by 1 or n) should not matter.

**Describe the expected behavior**
Both methods give the same convergence behavior.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

import sys
sys.path.insert(0, '../../Utilities/')

import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import matplotlib.pyplot as plt
import scipy.io
from scipy.interpolate import griddata
from pyDOE import lhs
from plotting import newfig, savefig
from mpl_toolkits.mplot3d import Axes3D
import time
import matplotlib.gridspec as gridspec
from mpl_toolkits.axes_grid1 import make_axes_locatable
import pickle

np.random.seed(1234)
tf.random.set_seed(1234)

if __name__ == "__main__":
    
    tf.keras.backend.set_floatx('float32')
    
    with open('objs.pkl', 'rb') as f:
        idx_x, idx_t, lhs_res, weights_output, biases_output = pickle.load(f)
    
    
    noise = 0.0     
    
    pos_bound = np.array([-5, 5]).astype(np.float32)
    t_bound = np.array([0, np.pi / 2]).astype(np.float32)
    
    N0 = 50
    N_b = 50
    N_f = 20000
    layers = [2, 100, 100, 100, 100, 2]
    #layers = [2, 100, 100, 2]
    
    data = scipy.io.loadmat('../Data/NLS.mat')
    
    t_val = data["tt"]
    pos_val = data["x"]
    func_val = data["uu"]
    
    #rand_idx_x = np.random.choice(func_val.shape[0], N0, replace=False)
    #rand_idx_t = np.random.choice(func_val.shape[1], N_b, replace=False)
    rand_idx_x = idx_x
    rand_idx_t = idx_t
    
    rand_x = (pos_val[0, rand_idx_x] - pos_bound[0]) / (pos_bound[1] - pos_bound[0]) * 2 - 1
    rand_t = (t_val[0, rand_idx_t] - t_bound[0]) / (t_bound[1] - t_bound[0]) * 2 - 1
    
    #X_f = lhs(2, N_f) #Latin-Hypercube (lhs)
    #X_f[:,0] = X_f[:,0] * 2 - 1
    #X_f[:,1] = X_f[:,1] * 2 - 1
    X_f = lhs_res
    X_f[:,0] = X_f[:,0] * 2 - 1
    X_f[:,1] = X_f[:,1] * 2 - 1
    
    #init tf tensors
    tf_pt_lb = tf.constant([[pos_bound[0]], [t_bound[0]]], dtype=tf.float32)
    tf_pt_ub = tf.constant([[pos_bound[1]], [t_bound[1]]], dtype=tf.float32)
    
    t0_arr_tmp = np.zeros(shape=[2, N0])
    t0_arr_tmp[0, :] = rand_x
    t0_arr_tmp[1, :] = np.zeros(rand_x.shape[0]) - 1
    tf_t0 = tf.convert_to_tensor(np.transpose(t0_arr_tmp), dtype=tf.float32)
    
    tmp_f_val_0 = func_val[rand_idx_x,0]
    tmp2_f_val_0 = np.zeros(shape=[2, N0])
    tmp2_f_val_0[0, :] = np.real(tmp_f_val_0)
    tmp2_f_val_0[1, :] = np.imag(tmp_f_val_0)
    tf_ans_t0 = tf.convert_to_tensor(np.transpose(tmp2_f_val_0), dtype=tf.float32)
    
    xlb_arr_np = np.zeros(N_b) - 1
    xub_arr_np = np.zeros(N_b) + 1
    xb_arr_t = rand_t
    tf_xlb_x_ten = tf.convert_to_tensor(np.expand_dims(xlb_arr_np, axis=1), dtype=tf.float32)
    tf_xub_x_ten = tf.convert_to_tensor(np.expand_dims(xub_arr_np, axis=1), dtype=tf.float32)
    tf_xb_t_ten = tf.convert_to_tensor(np.expand_dims(xb_arr_t, axis=1), dtype=tf.float32)
    
    tf_bulk_px_tensor = tf.convert_to_tensor(np.expand_dims(X_f[:, 0], axis=1), dtype=tf.float32)
    tf_bulk_pt_tensor = tf.convert_to_tensor(np.expand_dims(X_f[:, 1], axis=1), dtype=tf.float32)
    
    
    ##nn layers
    initializer = tf.keras.initializers.GlorotNormal()
    initializer0 = tf.keras.initializers.Zeros()
    tf_model = tf.keras.Sequential()
    for i in range(0, len(layers)):
        if i == 0:
            tf_model.add(tf.keras.Input(shape=(layers[i])))
        elif i == (len(layers)-1):
            tf_model.add(tf.keras.layers.Dense(layers[i], activation=None, kernel_initializer=initializer, bias_initializer=initializer0))
        else:
            tf_model.add(tf.keras.layers.Dense(layers[i], activation='tanh', kernel_initializer=initializer, bias_initializer=initializer0))
    
    optimizer = tf.keras.optimizers.Adam(epsilon=1e-08)
    
    #set weight manually
    for i in range(0, len(layers)-1):
        tf_model.layers[i].set_weights([np.array(weights_output[i]), np.array(biases_output[i].T[:,0])])
    
    
    
    
    @tf.function
    def loss_function(input_t0, label_t0, input_plb, input_pub, input_ptb, input_bulk_x, input_bulk_t, pbin, tbin):

        predictions_t0 = tf_model(input_t0, training=True)
        loss_t0 = tf.math.reduce_mean(tf.math.square(predictions_t0[:,0] - label_t0[:,0]))
        loss_t1 = tf.math.reduce_mean(tf.math.square(predictions_t0[:,1] - label_t0[:,1]))
            
        with tf.GradientTape(persistent=True) as tape_bnd:
            tape_bnd.watch(input_plb)
            lb_input_pack = tf.concat([input_plb, input_ptb], 1)
            prediction_plb = tf_model(lb_input_pack, training=True)
            prediction_plb_r = prediction_plb[:,0]
            prediction_plb_i = prediction_plb[:,1]
            
            tape_bnd.watch(input_pub)
            ub_input_pack = tf.concat([input_pub, input_ptb], 1)
            prediction_pub = tf_model(ub_input_pack, training=True)
            prediction_pub_r = prediction_pub[:,0]
            prediction_pub_i = prediction_pub[:,1]
            
            tape_bnd.watch(input_bulk_x)
            with tf.GradientTape(persistent=True) as tape_bulk2:
                tape_bulk2.watch(input_bulk_x)
                tape_bulk2.watch(input_bulk_t)
                bulk_pack = tf.concat([input_bulk_x, input_bulk_t], 1)
                prediction_bulk = tf_model(bulk_pack, training=True)
                prediction_bulk_r = prediction_bulk[:,0:1]
                prediction_bulk_i = prediction_bulk[:,1:2]
                
            grad_x_r = tape_bulk2.gradient(prediction_bulk_r, input_bulk_x) / (pbin[1] - pbin[0]) * 2
            grad_x_i = tape_bulk2.gradient(prediction_bulk_i, input_bulk_x) / (pbin[1] - pbin[0]) * 2
            grad_t_r = tape_bulk2.gradient(prediction_bulk_r, input_bulk_t) / (tbin[1] - tbin[0]) * 2
            grad_t_i = tape_bulk2.gradient(prediction_bulk_i, input_bulk_t) / (tbin[1] - tbin[0]) * 2
            
            del tape_bulk2
        
        loss_bnd_dl_r = tape_bnd.gradient(prediction_plb_r, input_plb) / (pbin[1] - pbin[0]) * 2
        loss_bnd_du_r = tape_bnd.gradient(prediction_pub_r, input_pub) / (pbin[1] - pbin[0]) * 2
        
        loss_bnd_dl_i = tape_bnd.gradient(prediction_plb_i, input_plb) / (pbin[1] - pbin[0]) * 2
        loss_bnd_du_i = tape_bnd.gradient(prediction_pub_i, input_pub) / (pbin[1] - pbin[0]) * 2
        
        grad_xx_r = tape_bnd.gradient(grad_x_r, input_bulk_x) / (pbin[1] - pbin[0]) * 2
        grad_xx_i = tape_bnd.gradient(grad_x_i, input_bulk_x) / (pbin[1] - pbin[0]) * 2
        
        del tape_bnd
        
        loss_bnd_r = tf.math.reduce_mean(tf.math.square(prediction_plb_r - prediction_pub_r))
        loss_bnd_i = tf.math.reduce_mean(tf.math.square(prediction_plb_i - prediction_pub_i))
        
        loss_bnd_dr = tf.math.reduce_mean(tf.math.square(loss_bnd_dl_r - loss_bnd_du_r))
        loss_bnd_di = tf.math.reduce_mean(tf.math.square(loss_bnd_dl_i - loss_bnd_du_i))
        
        h_mag_sq = prediction_bulk_r**2 + prediction_bulk_i**2
        loss_bulk_r = tf.math.reduce_mean(tf.math.square(-grad_t_i+0.5*grad_xx_r+h_mag_sq*prediction_bulk_r))
        loss_bulk_i = tf.math.reduce_mean(tf.math.square(grad_t_r+0.5*grad_xx_i+h_mag_sq*prediction_bulk_i))
        
        loss_t_sum = loss_t0 + loss_t1
        loss_bnd_sum = loss_bnd_r + loss_bnd_i + loss_bnd_dr + loss_bnd_di
        loss_bulk_sum = loss_bulk_r + loss_bulk_i
        loss_total = loss_t_sum + loss_bnd_sum + loss_bulk_sum
        
        return [loss_total, loss_t_sum, loss_bnd_sum, loss_bulk_sum]
    
    
    @tf.function
    def train_step(input_t0, label_t0, input_plb, input_pub, input_ptb, input_bulk_x, input_bulk_t, optimizer_in, pbin, tbin):
        with tf.GradientTape() as tape:
            loss_total_loc, loss_t_sum_loc, loss_bnd_sum_loc, loss_bulk_sum_loc = loss_function(
                input_t0, label_t0, input_plb, input_pub, input_ptb, input_bulk_x, input_bulk_t, pbin, tbin)
        gradients = tape.gradient(loss_total_loc, tf_model.trainable_variables)
        optimizer_in.apply_gradients(zip(gradients, tf_model.trainable_variables))
        return [loss_total_loc, loss_t_sum_loc, loss_bnd_sum_loc, loss_bulk_sum_loc]
    
    
    def function_factory(model, loss, input_t0, label_t0, input_plb, input_pub, input_ptb, input_bulk_x, input_bulk_t, pbin, tbin):
        # obtain the shapes of all trainable parameters in the model
        shapes = tf.shape_n(model.trainable_variables)
        n_tensors = len(shapes)
        # we'll use tf.dynamic_stitch and tf.dynamic_partition later, so we need to
        # prepare required information first
        count = 0
        idx = [] # stitch indices
        part = [] # partition indices
        for i, shape in enumerate(shapes):
            n = np.product(shape)
            idx.append(tf.reshape(tf.range(count, count+n, dtype=tf.int32), shape))
            part.extend([i]*n)
            count += n
        part = tf.constant(part)
        
        @tf.function
        def assign_new_model_parameters(params_1d):
            params = tf.dynamic_partition(params_1d, part, n_tensors)
            for i, (shape, param) in enumerate(zip(shapes, params)):
                model.trainable_variables[i].assign(tf.reshape(param, shape))
        
        # now create a function that will be returned by this factory
        @tf.function
        def f(params_1d):
            # use GradientTape so that we can calculate the gradient of loss w.r.t. parameters
            with tf.GradientTape() as tape:
                # update the parameters in the model
                assign_new_model_parameters(params_1d)
                # calculate the loss
                loss_value, _, _, _ = loss(input_t0, label_t0, input_plb, input_pub, input_ptb, input_bulk_x, input_bulk_t, pbin, tbin)
                
            # calculate gradients and convert to 1D tf.Tensor
            grads = tape.gradient(loss_value, model.trainable_variables)
            grads = tf.dynamic_stitch(idx, grads)
            
            # print out iteration & loss
            f.iter.assign_add(1)
            tf.print("TFP Iter:", f.iter, ", TFP loss:", loss_value)
            
            # store loss value so we can retrieve later
            tf.py_function(f.history.append, inp=[loss_value], Tout=[])
            
            return loss_value, grads
        
        # store these information as members so we can use them outside the scope
        f.iter = tf.Variable(0)
        f.idx = idx
        f.part = part
        f.shapes = shapes
        f.assign_new_model_parameters = assign_new_model_parameters
        f.history = []
        
        return f
    
    
    
    for epoch in range(50000):
        loss_loc, lt_loc, lbc_loc, lb_loc = train_step(
            tf_t0, tf_ans_t0, tf_xlb_x_ten, tf_xub_x_ten, tf_xb_t_ten, tf_bulk_px_tensor, tf_bulk_pt_tensor, optimizer, pos_bound, t_bound)
        if epoch % 10 == 0:
            tf.print("Finished epoch", epoch, ", loss_loc = ", loss_loc, ", lt_loc = ", lt_loc, ", lbc_loc = ", lbc_loc, ", lb_loc = ", lb_loc)
    
    
    
    func = function_factory(tf_model, loss_function, tf_t0, tf_ans_t0, tf_xlb_x_ten, tf_xub_x_ten, tf_xb_t_ten, tf_bulk_px_tensor, tf_bulk_pt_tensor, pos_bound, t_bound)
    init_params_TFP = tf.dynamic_stitch(func.idx, tf_model.trainable_variables)
    results = tfp.optimizer.lbfgs_minimize(
        value_and_gradients_function=func, initial_position=init_params_TFP, max_iterations=50000, 
        tolerance=1.0 * np.finfo(float).eps, num_correction_pairs=50)
    
    

Some comments: 
Since GlorotNormal() method generates initial weights randomly thus the provided code calls some input files related to initial weights and training set choice, in order to ensure the code is with the same initial state for different runs. Please run the packed code attached below.
    
[tf_testcase.zip](https://github.com/tensorflow/tensorflow/files/7631672/tf_testcase.zip)

    
    

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by UsherWang** [comment]
Another thing I noticed is that for prediction_bulk_r = prediction_bulk[:,0] method the gpu memcpy engine is busy while for prediction_bulk_r = prediction_bulk[:,0:1] method the gpu memcpy engine is idle, that probably explains the performance difference.

**Comment by tilakrayal** [comment]
@UsherWang ,
This issue is more related to tensorflow probability.Please post in that repo from [here](https://github.com/tensorflow/probability).

**Comment by UsherWang** [comment]
Hi @tilakrayal , 

Thank you for your reply and link. Before posting issue there I would like to double confirm with you about tfp problem.

I think the iteration steps shown above are related to adam optimizer, not for tfp.optimizer.lbfgs. Basically I use 2 different optimizer for training: first adam and then l-bfgs. 
Adam part:
for epoch in range(50000):
    loss_loc, lt_loc, lbc_loc, lb_loc = train_step(
        tf_t0, tf_ans_t0, tf_xlb_x_ten, tf_xub_x_ten, tf_xb_t_ten, tf_bulk_px_tensor, tf_bulk_pt_tensor, optimizer, pos_bound, t_bound)
    if epoch % 10 == 0:
        tf.print("Finished epoch", epoch, ", loss_loc = ", loss_loc, ", lt_loc = ", lt_loc, ", lbc_loc = ", lbc_loc, ", lb_loc = ", lb_loc)
and you can find adam routines been called in train_step()
l-bfgs part:
func = function_factory(tf_model, loss_function, tf_t0, tf_ans_t0, tf_xlb_x_ten, tf_xub_x_ten, tf_xb_t_ten, tf_bulk_px_tensor, tf_bulk_pt_tensor, pos_bound, t_bound)
init_params_TFP = tf.dynamic_stitch(func.idx, tf_model.trainable_variables)
results = tfp.optimizer.lbfgs_minimize(
    value_and_gradients_function=func, initial_position=init_params_TFP, max_iterations=50000, 
    tolerance=1.0 * np.finfo(float).eps, num_correction_pairs=50)

I am not sure what do you mean by 'tensorflow probability', is this the actual tfp pack in tf and the link you attached refer to tfp related support team, or it's a different tf support team that deal with convergence issues?

Thanks

UsherWang

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
While trying to reproduce the issue in tf v2.7 and nightly, code execution is taking the longer than the expected time-interval.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/95c51683177c699508bda2541369305f/53266.ipynb).

**Comment by UsherWang** [comment]
Hi @tilakrayal  and @sanatmpa1 

You can decrease iteration number from 50000 to 200 or 300 for adam optimizer
for epoch in range(50000): -> for epoch in range(200 or 300):

and comment out the bfgs part at the very end:

func = function_factory(tf_model, loss_function, tf_t0, tf_ans_t0, tf_xlb_x_ten, tf_xub_x_ten, tf_xb_t_ten, tf_bulk_px_tensor, tf_bulk_pt_tensor, pos_bound, t_bound)
init_params_TFP = tf.dynamic_stitch(func.idx, tf_model.trainable_variables)
results = tfp.optimizer.lbfgs_minimize(
    value_and_gradients_function=func, initial_position=init_params_TFP, max_iterations=50000, 
    tolerance=1.0 * np.finfo(float).eps, num_correction_pairs=50)

**Comment by wangpengmit** [comment]
Hi @UsherWang , I agree that the two ways shouldn't differ, but we need a much smaller reproduce, ideally just containing `tf.GradientTape`. The current reproduce is not actionable.

TensorFlow Probability is a separate repo from TensorFlow (though under the same "tensorflow" GitHub organization). It has its own GitHub Issues page.
