### ISSUE TITLE
Closing as stale. Please reopen if you'd like to work on this further.

### ISSUE THREAD

**Issue by terrycmchan** [tensorflow/tensorflow#53268]
Closing as stale. Please reopen if you'd like to work on this further.

_Originally posted by @google-ml-butler[bot] in https://github.com/tensorflow/tensorflow/issues/52214#issuecomment-947901218_

**Comment by terrycmchan** [comment]
Hi,

I am also facing the exact problem.
I can do the batch inference on TF 2.4.1 but cannot do that on TF  2.6.2.

Do you have any idea?
Thank you!

Regards,
Terry

**Comment by mohantym** [comment]
Hi @terrycmchan ! 
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by mohantym** [comment]
Ok @terrycmchan !Could you please try again with latest version TF 2.7 with Cuda 11.2 and CuDNN 8.1?

**Comment by terrycmchan** [comment]
@mohantym I tested with Tf v2.7.0 with Cuda release 11.2, V11.2.152 and CuDNN 8.1.1. However, the result is still not OK. Only the 1st frame can detect object.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by srjoglekar246** [comment]
@terrycmchan What error do you see? If possible, can you provide the two models (working/not working)?

**Comment by terrycmchan** [comment]
@srjoglekar246 The problem is that:
I was going to run the inference on video.
It was ok when I ran on TF version 2.4.1. However, I found that the code could not be ran on TF version 2.6.2 and 2.7.0 successfully.
When running on TF v2.6.2/v2.7.0, only the 1st frame could detect object and the rest of frames could not.
[results.zip](https://github.com/tensorflow/tensorflow/files/7646337/results.zip)

You can get the source from [here](https://drive.google.com/file/d/16Nl4T6p2f9459acT86xclytwxUjFAfuc/view?usp=sharing).
Just run:
`python3 detect_video.py --weights ./checkpoints/yolov4-416 --size 416 --model yolov4 --video ./data/video/video.mp4 --output ./detections/results.avi
`

**Comment by srjoglekar246** [comment]
I think your code isn't running TFLite, correct? @sachinprasadhs can we route to an appropriate person on the TF side?

**Comment by terrycmchan** [comment]
@srjoglekar246 The code is not running on TFLite. It is running on TF.

**Comment by terrycmchan** [comment]
@srjoglekar246 @sachinprasadhs @mohantym Any update on this issue?

**Comment by terrycmchan** [comment]
@sachinprasadhs @mohantym Any update on this issue? Thanks!

**Comment by mohantym** [comment]
Hi @terrycmchan ! Sorry for the late response! Team is still investigating this issue. Thank you for your patience!

**Comment by terrycmchan** [comment]
Hi @mohantym Would you mind to update the progress?

**Comment by mohantym** [comment]
Hello @terrycmchan !
Could you provide a new colab gist to replicate this issue in 2.11.
Thank you!
