### ISSUE TITLE
Allowing Input Tensors to be dynamic for Predictions when using the Subclass method for defining a model 

### ISSUE THREAD

**Issue by AshwinJay101** [tensorflow/tensorflow#53267]
I am trying to write a Keras Model which implements some complex logic. That logic has been implemented in my call method

As my network layers are convolutional, my model can theoretically predict on input sizes which are different than the size I trained on. Is there any way to specify that for running Predictions on the data.

Here is the skeletal code

     class CustomModel(tf.keras.Model):
         def __init__(self):
              super().__init__()
              self.conv1 = tf.keras.layers.Conv2D(filters=4, kernel_size=4)
              self.conv2= tf.keras.layers.Conv2D(filters=4, kernel_size=4)
      
         def call(inputs):
             image = inputs[0]
             output = self.conv1(image)
             # There is more complex logic here for inputs[1]
             # For sake of simplicity, writing this as output
             another_output = self.conv2(inputs[1])
             combined_output = (output, another_output)
             return combined_output 

And this is the code I am using for running the model

    model = CustomModel()
    model.compile()
    model.fit(x=Train_TF_Dataset)
    
    model.save(filename)
    
    load_model = tf.keras.models.load_model(filename)
    
    model.predict(x=Predict_TF_Dataset)

The train TF Dataset and the predict TF Datasets consist of different sizes which is our usecase.

The training data consisted of a tuple of 28x28x2 images and a second image while the prediction data consists of 512x512x2 along with the corresponding second images. The size of the first input in the tuple can be anything.

Is there some way of specifying that the input shape is (None, None, None, 2) instead of (None, 28, 28, 2). The first value of None is variable by default for the batch size.

The solutions I have seen on stackoverflow just convert it to a functional model which is not possible because of how complex my call method is

Note: 28 and 512 are just numbers. The actual sizes are different. 

Right now when I predict, I will get the following error 

    ValueError: `generator` yielded an element of shape (512, 512, 2) where an element of shape (28, 28, 2) was expected.

**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes

**Will this change the current api? How?** 
No the issue will be present in the current API as well 

**Who will benefit with this feature?**
This will allow people to develop subclass models with variable input sizes for Inference. This is huge use case in many industries 

**Any Other info.**

**Comment by chunduriv** [comment]
@AshwinJay101, In order to expedite the trouble-shooting process, please provide standalone code snippet to reproduce the issue reported here.

**Comment by chunduriv** [comment]
Please take a look at this [issue](https://stackoverflow.com/questions/60847311/valueerror-generator-yielded-an-element-of-shape-2-200-200-3-where-an-el) with the similar error. Also, Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!

**Comment by AshwinJay101** [comment]
Thanks, let me do that

**Comment by AshwinJay101** [comment]
This is a standalone script. You will notice that the model type of functional will work while the model type of subclass will fail but the model type of functional will work. The 2 models though are identical 

I tested it on tensorflow2.7 as well and got a similar error. I hope that this code snippet works. I can attach the file as well if required 

    import tensorflow as tf
    import numpy as np
    import os
    import shutil
    
    class CustomModel(tf.keras.Model):
        def __init__(self):
            super().__init__()
            self.conv1 = tf.keras.layers.Conv2D(filters=32, kernel_size=4, kernel_regularizer='l2')
            self.conv2= tf.keras.layers.Conv2D(filters=32, kernel_size=4, kernel_regularizer='l2')
    
        def call(self, inputs):
            image = inputs[0]
            output = self.conv1(image)
            another_output = self.conv2(inputs[1])
            combined_output = (output, another_output)
            self.add_loss(self.loss)
            return combined_output
        
        def loss(self):
            return tf.constant(1)
    
    
    def get_functional_model():
        input1 = tf.keras.Input(shape=(None, None, 6))
        input2 = tf.keras.Input(shape=(256, 256, 6))
        conv1 = tf.keras.layers.Conv2D(filters=32, kernel_size=4, kernel_regularizer='l2')(input1)
        conv2 = tf.keras.layers.Conv2D(filters=32, kernel_size=4, kernel_regularizer='l2')(input2)
        model = tf.keras.Model(inputs=[input1, input2], outputs=[conv1, conv2])
        return model
        
    
    def generate_train_dataset(num_data):
        image1 = np.random.random((num_data, 256, 256, 6))
        image2 = np.random.random((num_data, 256, 256, 6))
        label = np.random.randint(size=(num_data, 1), low=0, high=5)
        return ((image1, image2), label)
    
    
    def generate_predict_dataset(num_data):
        image1 = np.random.random((num_data, 512, 512, 6))
        image2 = np.random.random((num_data, 256, 256, 6))
        label = np.random.randint(size=(num_data, 1), low=0, high=5)
        return ((image1, image2), label)
    
    def train_tf_dataset(data, batch=1):
        ds = tf.data.Dataset.from_tensor_slices((data[0], data[1]))
        ds = ds.batch(batch)
        ds = ds.repeat()
        return ds
    
    def predict_tf_dataset(data, batch=1):
        ds = tf.data.Dataset.from_tensor_slices((data[0], data[1]))
        ds = ds.batch(batch)
        return ds
    
    
    run_path = 'Models'
    if os.path.exists(run_path):
        shutil.rmtree(run_path)
    os.makedirs(run_path)
    keras_run_path = os.path.join(run_path, 'Keras/')
    
    num_data = 10
    train_output = generate_train_dataset(num_data)
    train_data = train_tf_dataset(train_output)
    
    pred_num_data = 20
    predict_output = generate_predict_dataset(pred_num_data)
    predict_data = predict_tf_dataset(predict_output)
    
    model_type = 'functional'
    
    if model_type == 'subclass':
        model = CustomModel()
    elif model_type == 'functional':
        model = get_functional_model()
    
    model.compile()
    model.fit(x=train_data, epochs=2, steps_per_epoch=num_data, batch_size=1)
    
    model.save(keras_run_path)
    
    load_model = tf.keras.models.load_model(keras_run_path)
    
    predictions = load_model.predict(x=predict_data)
    
    print(len(predictions))

**Comment by AshwinJay101** [comment]
@chunduriv Can we remove the awaiting response tag?

**Comment by chunduriv** [comment]
@AshwinJay101, Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).Thanks!

**Comment by AshwinJay101** [comment]
Added the issue in that repo [Link](https://github.com/keras-team/keras/issues/15752)

**Comment by chunduriv** [comment]
@AshwinJay101, Let's track the progress there [keras-team/keras#15752 ](https://github.com/keras-team/keras/issues/15752) and  i am closing issue here.
