### ISSUE TITLE
How to change a saved model input shape in Tensorflow?

### ISSUE THREAD

**Issue by sun2011yao** [tensorflow/tensorflow#53270]
I have a pretrained saved model, input shape is [1, None, None, 3], i want to change model input shape to [1, 320, 320, 3], what should i do?

**Comment by AshwinJay101** [comment]
Have you tried looking at this [Link](https://stackoverflow.com/questions/55841854/how-to-change-a-saved-model-input-shape-in-tensorflow/55846130)

**Comment by Saduf2019** [comment]
@sun2011yao 
As you say it is [1,none,none,3] then you can just pass the 320,320,3 image to it.None input shape is just a placeholder and can take any value.
This is not a bug, i suggest you open this in discussion forum/stackoverflow for any further queries.
