### ISSUE TITLE
java.lang.UnsatisfiedLinkError:java.lang.String[] org.tensorflow.lite.NativeInterpreterWrapper.getSignatureKeys(long)

### ISSUE THREAD

**Issue by JencharFung** [tensorflow/tensorflow#53289]
AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] org.tensorflow.lite.NativeInterpreterWrapper.getSignatureKeys(long) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_getSignatureKeys and Java_org_tensorflow_lite_NativeInterpreterWrapper_getSignatureKeys__J)
10-16 08:37:52.057 32388 32435 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.getSignatureKeys(Native Method)
10-16 08:37:52.057 32388 32435 E AndroidRuntime:        at org.tensorflow.lite.NativeInterpreterWrapper.getSignatureKeys(NativeInterpreterWrapper.java:414)
10-16 08:37:52.057 32388 32435 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.getSignatureKeys(Interpreter.java:313)
10-16 08:37:52.057 32388 32435 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:232)
10-16 08:37:52.057 32388 32435 E AndroidRuntime:        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:226)

**Comment by JencharFung** [comment]
implementation 'org.tensorflow:tensorflow-lite-support:0.3.1'

**Comment by Saduf2019** [comment]
@JencharFung 
an you please refer to [this link](https://stackoverflow.com/questions/48223347/unsatisfiedlinkerror-while-building-tensorflow-lite-demo-source-code) and let us know.
