### ISSUE TITLE
'_VariantDataset' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by ghylander** [tensorflow/tensorflow#53280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes and no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu18.04
- TensorFlow installed from (source or binary): pypi 
- TensorFlow version (use command below): 2.5.0.dev20210108
- Python version:  3.8.5

**Describe the current behavior**
```
for window in win_train_dataset:
  print([item.numpy() for item in window])
<output>:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_877/1363250068.py in <module>
      1 for window in win_train_dataset:
----> 2   print([item.numpy() for item in window])

/tmp/ipykernel_877/1363250068.py in <listcomp>(.0)
      1 for window in win_train_dataset:
----> 2   print([item.numpy() for item in window])

AttributeError: '_VariantDataset' object has no attribute 'numpy'
```

**Describe the expected behavior**
```
for window in win_train_dataset:
  print([item.numpy() for item in window])
<output>:
item#1
item#2
...
item#n
```

**Pseudocode to reproduce the issue**

```
training_dataset = tf.keras.utils.image_dataset_from_directory(training_data_dir,
                                                               shuffle=False,
                                                               label_mode='categorical',
                                                               batch_size=hyperparameters["BATCH_SIZE"],
                                                               image_size=IMG_SIZE)) 
# Returns a batched dataset, proceed to unbatch it
unb_training_dataset = training_dataset.unbatch()

# Window the unbatched dataset
win_train_dataset = unb_train_dataset.window(3, 
                                    shift=1, 
                                    stride=1,
                                    drop_remainder=True,
                                    )

for window in win_train_dataset:
  print([item.numpy() for item in window])
```

**Comment by ghylander** [comment]
I'd like to add:

```
for window in win_train_dataset:
  print([item.numpy() for item in window])
```

is code from the tf.data.Dataset [documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#window)

I am using categorical labels, I don't know if that somehow affects how the dataset object is constructed, or if it has some effect on how the WindowDataset object is created

**Comment by tilakrayal** [comment]
@ghylander ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/30664#issuecomment-511035643) from the similar issue and also please try to execute the code in latest stable v2.7 and let us know if the issue still persists.Thanks!

**Comment by ghylander** [comment]
I believe I am already doing that, let me change the variable names so it looks closer to the comment you linked.

My code:
```
for window in win_train_dataset:
  print([item.numpy() for item in window])
```

The code in #30664:
```
for i in y:
  for j in i:
    print(j.numpy())
```

My code using y, i and j as variable names:
```
for i in y:
  print([j.numpy() for j in i])
```

Either  way, I tried the exact code in #30664 and it produces the same result:
![image](https://user-images.githubusercontent.com/74593034/144563208-f567f9de-1156-4571-98be-8298c7b3aa62.png)

**Comment by ghylander** [comment]
this is the output of:

```
for i in y:
  for j in i:
    print(dir(j))
<output>:
['_GeneratorState', '__abstractmethods__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_add_variable_with_custom_getter', '_apply_options', '_as_serialized_graph', '_checkpoint_dependencies', '_consumers', '_deferred_dependencies', '_flat_shapes', '_flat_structure', '_flat_types', '_functions', '_gather_saveables_for_checkpoint', '_graph', '_graph_attr', '_handle_deferred_dependencies', '_has_captured_ref', '_inputs', '_list_extra_dependencies_for_serialization', '_list_functions_for_serialization', '_lookup_dependency', '_map_resources', '_maybe_initialize_trackable', '_name_based_attribute_restore', '_name_based_restores', '_no_dependency', '_object_identifier', '_options_attr', '_preload_simple_restoration', '_restore_from_checkpoint_position', '_self_name_based_restores', '_self_saveable_object_factories', '_self_setattr_tracking', '_self_unconditional_checkpoint_dependencies', '_self_unconditional_deferred_dependencies', '_self_unconditional_dependency_names', '_self_update_uid', '_setattr_tracking', '_shape_invariant_to_type_spec', '_single_restoration_from_checkpoint_position', '_structure', '_tf_api_names', '_tf_api_names_v1', '_trace_variant_creation', '_track_trackable', '_tracking_metadata', '_type_spec', '_unconditional_checkpoint_dependencies', '_unconditional_dependency_names', '_update_uid', '_variant_tensor', '_variant_tensor_attr', '_variant_tracker', 'apply', 'as_numpy_iterator', 'batch', 'cache', 'cardinality', 'concatenate', 'element_spec', 'enumerate', 'filter', 'flat_map', 'from_generator', 'from_tensor_slices', 'from_tensors', 'interleave', 'list_files', 'map', 'options', 'padded_batch', 'prefetch', 'range', 'reduce', 'repeat', 'shard', 'shuffle', 'skip', 'take', 'unbatch', 'window', 'with_options', 'zip']

```

**Comment by tilakrayal** [comment]
@ghylander ,
Can you please provide the complete code to reproduce the issue.Thanks!

**Comment by ghylander** [comment]
I'll also add this since I didn't mention it before: I did try updating to tf2.7, but produces the same result

About the code, you can plug the code in the OP, all you need is a keras-style dataset for the tf.keras.utils.image_dataset_from_directory() function:
```
main_directory/
...class_a/
......a_image_1.jpg
......a_image_2.jpg
...class_b/
......b_image_1.jpg
......b_image_2.jpg
```

**Comment by tilakrayal** [comment]
@ghylander ,
We don't see any code to reproduce the issue reported.Can you please provide the complete code or colab gist to debug the issue.Thanks!

**Comment by ghylander** [comment]
find gist [here](https://gist.github.com/ghylander/71e55a5d676dcc468fc2911a7f9af77d)

**Comment by tilakrayal** [comment]
@ghylander ,
I ran the code shared and face a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/0660e2f442c47c8b2b1615bae854501b/untitled146.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.

**Comment by ghylander** [comment]
Hi, 
updated the gist [here](https://colab.research.google.com/gist/ghylander/e64c0274e0c4d08e11c817272f57a519/untitled146.ipynb)

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue tf v2.7, v2.5 and tf-nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d8e8255540c8f87e88f50a98ec304513/53280.ipynb).

**Comment by ghylander** [comment]
let me also add:
ultimately, what i'm trying to achieve is to get the filenames of the elements in the dataset.

When first creating the tf.data.Dataset object with `tf.keras.preprocessing.image_dataset_from_directory()`, the oject has the `file_paths` attribute, which returns a list of the full file path including file name.

The `file_paths` attribute however is lost when a method is applied

**Comment by Saduf2019** [comment]
@ghylander 
On making a few changes I do not see the error, please find the gist [here](https://colab.research.google.com/gist/Saduf2019/86455b19d976848a414ce8a0719f65d9/untitled650.ipynb), you may also try:
for i in win_train_dataset:
  for np.j in i:
    print(j)

Please create an issue at discussion forum for any further queries as this is not a bug or feature request.

**Comment by ghylander** [comment]
@Saduf2019 
from the [docs](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#window) :
```
for window in dataset:
  print([item.numpy() for item in window])
```
which does not work
your code, as you stated, is modified from the one on the docs. It would seem that the behaviour of the dataset API changed at some point, making the code in the docs stop working
