### ISSUE TITLE
Model not learning when using Dataset.from_generator() instead of Dataset.from_tensor_slices()

### ISSUE THREAD

**Issue by DanBmh** [tensorflow/tensorflow#53284]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): Nvidia docker (nvcr.io/nvidia/tensorflow:21.08-tf2-py3)
- TensorFlow version (use command below): 2.5 (default installation) / 2.7 (updated with pip), doesn't work for both
- Python version: 3.8.10
- CUDA/cuDNN version: 11.4

**Describe the current behavior**

I'm trying to train a Pose Recognition model (SimpleBaseline - ResNet50) with the COCO dataset. The labels are loaded with a python function first and are then converted to a tf.dataset and further processed. It works well when using Dataset.from_tensor_slices() for conversion, but the model doesn't learn anything if Dataset.from_generator() is used instead. The later dataset functions are kept the same. Currently the training and evaluation are executed on the same (eval) split of the dataset for debugging. When printing the outputs of the dataset while training they are exactly the same for both approaches. 

```

# Loading labels as python list of dicts:
...
print(labels[0])
{
  'annotids': [183126], 
  'imageid': 425226,
  'raw_keypoints': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 142, 309, 1, 177, 320, 2, 191, 398, 2, 237, 317, 2, 233, 426, 2, 306, 233, 2, 92, 452, 2, 123, 468, 2, 0, 0, 0, 251, 469, 2, 0, 0, 0, 162, 551, 2], 
  'keypoints': [[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [142, 309, 1], [177, 320, 2], [191, 398, 2], [237, 317, 2], [233, 426, 2], [306, 233, 2], [92, 452, 2], [123, 468, 2], [0, 0, 0], [251, 469, 2], [0, 0, 0], [162, 551, 2]]], 
  'imgpath': '/datasets/coco2017/annotations/../images/val2017/000000425226.jpg',
  'raw_width': 480,
  'raw_height': 640,
  'bbox': [73.35, 206.02, 300.58, 372.5], 
  'score': 1.0
}

# This does work
# Convert to dict-of-lists format and create dataset
labels = {k: [dic[k] for dic in labels] for k in labels[0]}
ds = tf.data.Dataset.from_tensor_slices(labels)

# This doesn't work
output_types = {
    "annotids": tf.int32,
    "imageid": tf.int32,
    "raw_keypoints": tf.float32,
    "keypoints": tf.float32,
    "imgpath": tf.string,
    "raw_width": tf.int32,
    "raw_height": tf.int32,
    "bbox": tf.float32,
    "score": tf.float32,
}
ds = tf.data.Dataset.from_generator(lambda: iter(labels), output_types=output_types)

# Postprocessing like image loading and heatmap generation with dataset.map calls
# They don't change for both approaches
...
```

**Describe the expected behavior**

The model should be able to learn something as well when using from_generator() instead of from_tensor_slices()

**Standalone code to reproduce the issue**
Currently the complete training code is to complex to extract a short standalone example

**Other info / logs**
Training uses Mirrored Strategy on two gpus. It takes about one epoch of training (~6000 images or ~90x2x32 batch examples) that a difference in the loss can be seen clearly. When training for more epochs the loss of the from_generator() approach doesn't decrease further. The heatmaps the network is trying to learn only show a lot of black with some random noise instead of clear gaussian distributions around a point.

**Current workaround**
Use Dataset.from_tensor_slices() instead of Dataset.from_generator()

**Comment by tilakrayal** [comment]
@DanBmh ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by DanBmh** [comment]
@tilakrayal 
I uploaded the code to: https://gitlab.com/DANBER/Pingoora

I hope the instructions in the _Pose2D_ folder are good enough to help you set up the project. You only need to download the _val_ part of the coco dataset. The data pipeline part can be found [here](https://gitlab.com/DANBER/Pingoora/-/blob/main/Pose2D/training/scode/pipelines/pl_top_down.py#L175). You also can find some pipeline debugging tools [here](https://gitlab.com/DANBER/Pingoora/-/blob/main/Pose2D/training/run_tests.py).

In case you have any problems with it, please contact me again.

**Comment by tilakrayal** [comment]
@DanBmh ,
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro or colab gist? That will allow us to determine the source of the issue easily. Thanks!

**Comment by DanBmh** [comment]
Before we simplify the example, could you please test if you can replicate the error with the current code?

**Comment by tilakrayal** [comment]
@DanBmh ,
In order to reproduce the issue, the mentioned code is fairly complex.So it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro or colab gist?

**Comment by DanBmh** [comment]
I found the error. The problem is that I'm using an optimizer with CosineDecaying learning rate schedule. To match the decay steps to the epoch number the steps per epoch are required which I calculated with:
 `steps_per_epoch = tf.data.experimental.cardinality(dataset_train).numpy()`

This works when the dataset is created with `from_tensor_slices`, but when `from_generator` is used instead, a negative (-2) steps per epoch number is returned. When the schedule is created no error is raised but the network doesn't learn then.

**Comment by DanBmh** [comment]
You can still find it at: https://gitlab.com/DANBER/Pingoora
I now have deleted most extra parts, except the datasets and training related scripts.

**Comment by tilakrayal** [comment]
@DanBmh ,
Without the reproducible code, it would be difficult for us to debug the issue.There are multiple files of code available in the link mentioned.So we request you to post `only reproducible code` which you are facing issue.It helps to analyse the issue.If you are unable to provide exact code which you are facing the issue please feel free to post in tf discussion forum.Thanks!

**Comment by DanBmh** [comment]
The linked code contains only the scripts to train the train the network with which I'm facing the learning problem. If you follow the readme steps to run a training you should be able to reproduce the problem.

But as I wrote above the problem seems to be that one dataset generation method keeps the length information and the other doesn't:
```python3
import tensorflow as tf
labels = [{"a": "aa"}, {"a": "aaa"}, {"a": "aaaa"}]

output_types = {"a": tf.string}
ds = tf.data.Dataset.from_generator(lambda: iter(labels), output_types=output_types)
print(tf.data.experimental.cardinality(ds).numpy())
# -2

labels2 = {k: [dic[k] for dic in labels] for k in labels[0]}
ds = tf.data.Dataset.from_tensor_slices(labels2)
print(tf.data.experimental.cardinality(ds).numpy())
# 3
```

And later on I used this value to create a learning rate schedule, which accepted the negative decay steps value, but didn't work for training the network.
```python3
from tensorflow.keras.optimizers import schedules
steps_per_epoch = tf.data.experimental.cardinality(ds).numpy()

lr_schedule = schedules.CosineDecay(
    initial_learning_rate=learning_rate,
    decay_steps=config["training_epochs"] * steps_per_epoch,
)
```

**Comment by tilakrayal** [comment]
On running the given code snippet, I am facing an error stating `NameError: name 'learning_rate' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/509ed5ace38e4db5cf79b7c92dff7b7d/untitled164.ipynb).

**Comment by DanBmh** [comment]
The learning rate is just some small value. I updated the comment above.

**Comment by tilakrayal** [comment]
@DanBmh ,
On running the given code snippet, I am facing an error stating NameError: name 'config' is not defined. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/cd8e558cefc2eacf10b62792adaa9154/untitled166.ipynb).

**Comment by DanBmh** [comment]
Sorry. Updated the config definition in the snippet above.

**Comment by tilakrayal** [comment]
@DanBmh ,
I was not able to find any issue or error while executing the given code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b50514cb7e78a956f33665a3efd8e3bc/untitled169.ipynb).Can you please provide the error log you are facing while running the code.It helps to debug the issue.Thanks!

**Comment by DanBmh** [comment]
> I was not able to find any issue or error while executing the given code

That's the problem. That you can initialize the schedule with a negative _decay_steps_ value, which results in the optimizer not optimizing the network, but doesn't raise an error.

**Comment by aaudiber** [comment]
From the tf.data side, it is expected that the cardinality of `Dataset.from_generator()` is [unknown](https://www.tensorflow.org/api_docs/python/tf/data/experimental#UNKNOWN_CARDINALITY). There's isn't a good way to determine how much data a given generator will produce. The generator could be infinite or produce random amounts of data.

It does seem strange that CosineDelay allows a negative number of decay steps without producing an error. It may be worth creating new issue or sending a PR for that problem specifically.

**Comment by jsimsa** [comment]
As a stop gap, if the number of elements produced by the generator is known, then the tf.data `assert_cardinality` could be used to provide the cardinality information, which should resolve the learning issue.

**Comment by SuryanarayanaY** [comment]
A PR [No.17499](https://github.com/keras-team/keras/pull/17499) has been raised in Keras repo which can enable `CosineDecay` to raise the error if the `decay_steps` argument is a negative value or even for zero and float values.
Thanks!

**Comment by tilakrayal** [comment]
@DanBmh,
The related PR was raised for the similar proposal which has been merged.
https://github.com/keras-team/keras/pull/18722

The learning rate schedulers like CosineDecay ,ExponentialDecay, PolynomialDecay, InverseTimeDecay , CosineDecayRestarts has an argument decay_steps which should be >0. If user passes zero or -ve value this will leads to different behaviour like constant learning_rate or making learning_rate to zero or NaN etc.

In the above comment https://github.com/tensorflow/tensorflow/issues/53284#issuecomment-1017997229 it is suggested to raise an exception which can save time instead of silently training the model.
