### ISSUE TITLE
Is there any way to use `gather_nd` more simpler?

### ISSUE THREAD

**Issue by lan2720** [tensorflow/tensorflow#5328]
Hi all, 

Now I'm using [tf.gather_nd](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#gather_nd). 

When batched indexing into a matrix:
```
indices = [[[0, 0]], [[0, 1]]]
params = [['a', 'b'], ['c', 'd']]
output = [['a'], ['b']]
```

I wonder if there any simpler solution if my `indices.shape[0] = params.shape[0]`. That means I want to take values from **EVERY** row of params. 

So if I want to get 
`output = [['a'], ['c']]` ('a' is from params[0], 'c' is from params[1])
 I can code like `indices = [[0], [0]]` instead of `indices = [[[0, 0]], [[1, 0]]]` since people hardly have the row info in `indices`

For example,
```
import tensorflow as tf

indices = [[[0, 4], [0, 1], [0, 6], [0, 2]],
          [[1, 1], [1, 4], [1, 0], [1, 9]],
          [[2, 5], [2, 1], [2, 9], [2, 6]]]

params = [[4,6,3,6,7,8,4,5,3,8], [9,5,6,2,6,5,1,9,6,4], [4,6,6,1,3,2,6,7,1,8]]
output = tf.gather_nd(params, indices)

sess = tf.Session()
print sess.run(output)
```
There output is 
```
[[7 6 4 3]
 [5 6 9 4]
 [2 6 8 6]]
```

I want to take out 7, 6, 4, 3 from params[0]. However, I have to set row index 0 in `indices` because params[0][4] = 7, params[0][1] = 6, params[0][6] = 4, params[0][2] = 3.
But what I already know is just 
```
raw_indices = [[4, 1, 6, 2],
               [1, 4, 0, 9],
               [5, 1, 9, 6]]
```
How can I add the "row index" in each elem of `raw_indices` to get
```
indices = [[[0, 4], [0, 1], [0, 6], [0, 2]],
          [[1, 1], [1, 4], [1, 0], [1, 9]],
          [[2, 5], [2, 1], [2, 9], [2, 6]]]
```

￼

￼
￼￼￼

**Comment by aselle** [comment]
This question is more appropriate to ask on StackOverflow, since it is not a specific feature request or bug and is concerned with best practices. Thanks!
