### ISSUE TITLE
compiled tf.function and tf.data.Iterator error

### ISSUE THREAD

**Issue by ramonmatas** [tensorflow/tensorflow#53294]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-61734-g21f65a888d6 2.7.0-dev20210806
- Python version: Python 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2
- GPU model and memory: GeForce RTX 2080 Ti / 11019MiB

**Describe the current behavior**
Hitting an error when calling next on a tf.data.Iterator within a compiled (jit_compiled=True) tf.function:

`tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run __inference_run_compiled_61: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::ResourceDeleter [Op:__inference_run_compiled_61]
`
**Describe the expected behavior**

The same code without compilation works fine (does not hit the error above). I am expecting the same behavior.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**

```
import tensorflow as tf

data = tf.data.Dataset.from_tensor_slices(list(range(10)))
data = data.repeat()
iterator = iter(data)

@tf.function(jit_compile=False)
def run(it):
    t = 0
    for _ in range(10):
        x = next(it)
        t += x
    return t

@tf.function(jit_compile=True)
def run_compiled(it):
    t = 0
    for _ in range(10):
        x = next(it)
        t += x
    return t

print(run(iterator))
print(run_compiled(iterator))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Full output of the test above:

`tf.Tensor(45, shape=(), dtype=int32)
Traceback (most recent call last):
  File "../error.py", line 24, in <module>
    print(run_compiled(iterator))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 904, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 976, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1965, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 597, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run __inference_run_compiled_61: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::ResourceDeleter [Op:__inference_run_compiled_61]`

**Comment by hxyue1** [comment]
I ran your example on Google Colab and got a different error message which might be more informative

```InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_run_compiled_61[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: IteratorGetNext (No registered 'IteratorGetNext' OpKernel for XLA_CPU_JIT devices compatible with node {{node IteratorGetNext}}){{node IteratorGetNext}}```

I'm not sure what tensorflow version you're using, but mine is 2.7.0

**Comment by hxyue1** [comment]
Quickly scanning some of the documentation, `jit_compile=True` invokes compilation using XLA (Accelerated Linear Algebra) while very fast is known to have some [problems](https://www.tensorflow.org/xla/known_issues). 

Unfortunately it doesn't look like your use case fits neatly into any of those listed. If I had to hazard a guess, it may have something to do with an iterator being unbounded which may be related to the issue of XLA not liking infinite loops.
