### ISSUE TITLE
Update https://www.tensorflow.org/install/gpu#install_cuda_with_apt for Ubuntu 21.04

### ISSUE THREAD

**Issue by mperino** [tensorflow/tensorflow#53297]
## URL(s) with the issue:
https://www.tensorflow.org/install/gpu#install_cuda_with_apt

## Description of issue (what needs changing):

Please add a section for Ubuntu 21.04:

For Ubuntu 21.04 the manual installation instructions are a thing of the past assuming that you have installed your NVIDIA drivers from the Canonical default apt repo .  All one needs to do is:
pip3 install tensorflow
sudo apt install nvidia-cuda-toolkit

This resolves the library error issues: "Could not load dynamic library 'libcudart.so.11.0'"

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@mperino 
Could you install sudo apt instead of install nvidia-cuda-toolkit 
using specific cuda toolkit, it needs to be installed based on Tensorflow version accordingly.
