### ISSUE TITLE
LSTM expansion

### ISSUE THREAD

**Issue by allhavebrainimplantsandmore** [tensorflow/tensorflow#53303]
**System information**
- TensorFlow version (you are using): 1.3
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**

Simple LSTMs have limitations. It cannot extract some features, i.e. some mathematical operands, conditional logic, etc. I don't think the LSTM advancements cover this. This paper kind of shows what logic needs to be part of LSTM out of the box: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8610074 
Can we improve the LSTM to include ability to figure out some basic logic like mathematical operands and conditional logic?

**Will this change the current api? How?**
Shouldn't.

**Who will benefit with this feature?**
Everyone.

**Any Other info.**
LSTM is brokened at the moment. Pretty rudimentary.

**Comment by Saduf2019** [comment]
@allhavebrainimplantsandmore 
Please feel free to create a pr or let us know the changes to be made to which file for the requested change.
