### ISSUE TITLE
tf.stack silently output wrong result with 0-dimension tensor

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#53300]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0 and 2.8.0-dev20211203 (nightly)
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.random.uniform(shape=[0,3])
y = tf.random.uniform(shape=[1,3])
print(tf.stack([x,y]).shape)
```

**Describe the current behavior**
Outputs:
```
(2, 0, 3)
```
Stacking `x` and `y`, and we got an empty tensor! 
I found that this issue occurs in both tf2.7.0 and tf-nightly.

**Describe the expected behavior**
According to the documentation, the stacked tensors should have the same shape. Here the input tensor `x` and `y` don't have the same shape, so an `InvalidArgumentError` error should be raised.

**Comment by meSajied** [comment]
It shows no error till shape of first tensor is 0.

**Comment by yongtang** [comment]
Added a PR #53367  for the fix.
