### ISSUE TITLE
Could not find the DLL(s) 'msvcp140_1.dll'

### ISSUE THREAD

**Issue by muriloasouza** [tensorflow/tensorflow#53305]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: (Windows 10)
- TensorFlow installed from: binary
- TensorFlow version: 2.6
- Python version: 3.8.0
- Installed using virtualenv? pip? conda?: pip (on a fresh anaconda environment)
- CUDA/cuDNN version: CUDA 11.2.2/ cuDNN 8.1.0.77
- GPU model and memory: Nvidia GeForce GTX 1650 Ti with 4096 MB GDDR6 

**Describe the problem**

`import tensorflow`

**Any other info / logs**

```
Traceback (most recent call last):

  File "C:\Users\Muril\AppData\Local\Temp/ipykernel_6432/4294963926.py", line 1, in <module>
    import tensorflow

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()

  File "C:\Users\Muril\anaconda3\envs\tf-keras-gpu\lib\site-packages\tensorflow\python\platform\self_check.py", line 54, in preload_check
    raise ImportError(

ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
```

I have installed the DLLs from that link, restarted my PC, but the problem remains.

The msvcp140_1.dll is in C:\Windows\System32, wich is already in my path environemnt variable.

![Capturar1](https://user-images.githubusercontent.com/40600889/144713654-f1f7e0f4-c657-4479-97c8-c12bc6dbb00d.JPG)

**Comment by Saduf2019** [comment]
@muriloasouza 
Please check these: [link](https://github.com/tensorflow/tensorflow/issues/18116#issuecomment-854379687), [link1](https://stackoverflow.com/questions/60157335/cant-pip-install-tensorflow-msvcp140-1-dll-missing).
#50955,#43193,#35618
Please verify your python/os version os not 32 bit.

**Comment by muriloasouza** [comment]
@Saduf2019

I don't have a Program folder inside AppData\Local. Instead, i got Python38 folder inside Roaming\Python.
Python 64 bit.
![Capturar1](https://user-images.githubusercontent.com/40600889/144757777-aa36c8a3-561e-4cd3-8eed-ffc02dc96ba1.JPG)

Well, i just tried upgrading tensorflow (`pip install tensoflow` ). Now i am with tf 2.7.  Did one try, and the error was there. I restarted my PC, and when i was about to post this message, i did one last try and `import tensorflow` worked. So, i trained a small MLP just fine. Closed my IDE (Spyder), opened it again, and the error reappeared.

**Comment by Saduf2019** [comment]
@muriloasouza 
It clearly says windows 32, like i explained earlier there is no support for 32 bits.

**Comment by muriloasouza** [comment]
@Saduf2019 

win 32 is just saying my Anaconda is installed on Windows OS. My OS is 64 bit, and AMD64 indicates that my code is running in a 64 bit process

[link1](https://stackoverflow.com/questions/28526062/does-64-bit-anaconda-on-win32-uses-32-bit-or-64-bit)
[link2](https://www.w3resource.com/python-exercises/python-basic-exercise-42.php)
[link3](https://www.scivision.dev/python-check-32-64-bit/)

**Comment by Saduf2019** [comment]
@muriloasouza 
Could you please try on virtual env and let us know.

**Comment by muriloasouza** [comment]
Yes, everything is in the correct version and my CPU does support AVS.

At this point i'm just giving up, too much of a headache to make this work. I'm sticking with Google Colab.

Thanks for your help @Saduf2019

**Comment by justanotheranonymoususer** [comment]
I had the same problem, this guide helped me:
https://winbindex.m417z.com/?file=msvcp140_1.dll
