### ISSUE TITLE
how to fix  undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, absl::lts_20211102::string_view, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'

### ISSUE THREAD

**Issue by xjj210130** [tensorflow/tensorflow#53317]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>
Hi all:
   I build libtensorflow with source as follow:
  1: i build grpc first.
  2:  copy  pb, absl the include, and lib to /usr/lib64
  3: bazel build --action_env TF_SYSTEM_LIBS='com_google_protobuf,absl_py' //tensorflow:libtensorflow_cc.so
  4 build my owner example with the libtensorflow.so,but it's wrong.
   In function `tensorflow::Status::Status(tensorflow::error::Code, absl::lts_20211102::string_view)':
/opensource/tf/tensorflow/core/platform/status.h:49: undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, absl::lts_20211102::string_view, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'
  
pls, how to fix the bug.
ths.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @xjj210130 ! Could you please look at this [thread](https://github.com/tensorflow/tensorflow/issues/48813#issuecomment-838098803) for answer? Thanks!

**Comment by mihaimaruseac** [comment]
You need to make sure all components linked together use the same absl version.

**Comment by xjj210130** [comment]
Yes, now i change the method, i use absl download by tensorflow. the version is old, and grpc ,pb  is the same problem.
I use tensorflow version is r2.6。The problem is gone

**Comment by xjj210130** [comment]
fixed

**Comment by hmaarrfk** [comment]
Can you share a few words about how you were able to address the issue? We seem to be hitting the same bug with the recent upgrade to 

20211102

Thanks!
