### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by jntdst** [tensorflow/tensorflow#53316]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/text/tutorials/text_classification_rnn

## Description of issue (what needs changing):
"Run a prediction on a new sentence:

If the prediction is >= 0.0, it is positive else it is negative."
### Clear description

If the prediction is >= 0.5, it is positive else it is negative.

**Comment by sushreebarsa** [comment]
@jntdst I have raised a [PR](https://github.com/tensorflow/text/pull/788) to fix this issue. This issue will be closed once the PR is merged.Thanks!

**Comment by foxik** [comment]
Note that the inequality `prediction is >= 0.0` is actually correct -- see https://github.com/tensorflow/text/pull/788#issuecomment-988336985 for more details.

**Comment by sushreebarsa** [comment]
@foxik Thank you for the update! 
@jntdst Could you please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/53316#issuecomment-988337352) above and move this issue to closed status ? Thanks!
