### ISSUE TITLE
Build Debug Version of TF 2.4

### ISSUE THREAD

**Issue by ZiqiFrancisFan** [tensorflow/tensorflow#53319]
**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow version: 2.4
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.2

**Command**
 bazel build --config=cuda --config=dbg //tensorflow/tools/pip_package:build_pip_package

**Error Message**
ERROR: /tensorflow/tensorflow/BUILD:724:1: Linking of rule '//tensorflow:libtensorflow_framework.so.2.4.4' failed (Exit 1)
/usr/bin/ld: bazel-out/k8-dbg/bin/tensorflow/stream_executor/cuda/libcublas_plugin.lo(cuda_blas.pic.o): relocation R_X86_64_PC32 against undefined symbol `_ZN15stream_executor3gpu12_GLOBAL__N_120CUDABlasLtMatmulPlan14kMaxBatchCountE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 42.168s, Critical Path: 26.85s
INFO: 1059 processes: 1059 local.
FAILED: Build did NOT complete successfully

**Question**
Is there a convenient/systematic way to build debug version of tf 2.4 with CUDA support?

**Comment by sushreebarsa** [comment]
@ZiqiFrancisFan Could you please try with the latest **TF v2.7.0** and refer to [build from source](https://www.tensorflow.org/install/source) , [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) ? Please let us know if it helps? Thanks!

**Comment by ZiqiFrancisFan** [comment]
@sushreebarsa Unfortunately, the product of my company is based on TF v2.4, and the code we developed as wrappers of TF won't work with a newer version. Is there a way to build debug particularly for TF v2.4?

**Comment by bhack** [comment]
There is already a reply [in the forum](https://discuss.tensorflow.org/t/how-to-build-tensorflow-debug-version/6356/5)

**Comment by sushreebarsa** [comment]
@ZiqiFrancisFan Could you please check the [comment](https://github.com/tensorflow/tensorflow/issues/53319#issuecomment-987330888) above and let us know if it helps?Thanks!

**Comment by ZiqiFrancisFan** [comment]
> @ZiqiFrancisFan Could you please check the [comment](https://github.com/tensorflow/tensorflow/issues/53319#issuecomment-987330888) above and let us know if it helps?Thanks!

**Comment by ZiqiFrancisFan** [comment]
@sushreebarsa Actually, I am the one who asked the question on tensorflow forum, and I am posting the question here to see if someone has met a same issue and probably would provide a solution. If there is no official debug build for tf2.4, then there is nothing more I can do. Thanks.

**Comment by sachinprasadhs** [comment]
I see there was already a issue #45570 about TF 2.4 build in debug mode, you can refer to that and for additional follow ups you can refer to your original post in [TF Forum](https://discuss.tensorflow.org/t/how-to-build-tensorflow-debug-version/6356) and move this issue to closed status. Thanks!
