### ISSUE TITLE
"Create an op" documentation is outdated

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#53313]
## URL(s) with the issue:

https://www.tensorflow.org/guide/create_op
https://github.com/tensorflow/custom-op

## Description of issue (what needs changing):

> `g++ -std=c++11 ...`

The option `std-c++11` is wrong, I think. It needs at least `std-c++14` for TensorFlow >=2.7.

This issue also exists in the [custom-op](https://github.com/tensorflow/custom-op) repo.

I think C++14 as default was introduced here: https://github.com/tensorflow/tensorflow/commit/f09d3e299752226f7a28c09a8e2018430b691a36

It can be seen here: https://github.com/tensorflow/tensorflow/blob/908e8010ff2c4249f0c81ed85f1013bbd4b7682e/.bazelrc#L320

> Note on gcc version >=5: gcc uses the new C++ ABI since version 5. The binary pip packages available on the TensorFlow website are built with gcc4 that uses the older ABI. If you compile your op library with gcc>=5, add -D_GLIBCXX_USE_CXX11_ABI=0 to the command line to make the library compatible with the older abi.

This is long outdated. The TF pip packages use a more recent GCC version since a long time (I don't exactly know since when).

**Comment by sushreebarsa** [comment]
@albertz This issue will be closed ,once the PR is merged.Thanks!

**Comment by albertz** [comment]
> @albertz This issue will be closed ,once the PR is merged.Thanks!

What PR are you referring to?

**Comment by sushreebarsa** [comment]
@albertz We could see the [PR](https://github.com/rwth-i6/returnn/pull/826) that you have raised is merged. Could you please let us know if we can move this issue to closed status?Thanks!

**Comment by albertz** [comment]
I don't understand. The linked PR is on our RETURNN project. It does not touch or fix the TensorFlow documentation.

**Comment by mihaimaruseac** [comment]
There has been a confusion @albertz , please ignore @sushreebarsa 's comment about the PR on your project.

If you want to send a PR to the custom op and tag me, I'd be happy to review. Sorry for the confusion

**Comment by MarkDaoust** [comment]
https://github.com/tensorflow/docs/pull/1989

**Comment by Saduf2019** [comment]
Moving this to closed status and the pr is merged
