### ISSUE TITLE
Getting [java.lang.IllegalArgumentException: Internal error: Error applying delegate] error while applying NNAPI Delegate

### ISSUE THREAD

**Issue by sj120698** [tensorflow/tensorflow#53335]
**Describe the current behavior**

I am using the tensorflow [model_personalization ](https://github.com/tensorflow/examples/tree/master/lite/examples/model_personalization) example and I have modified the android application code ([LiteMultipleSignatureModel.java](https://github.com/tensorflow/examples/blob/master/lite/examples/model_personalization/android/transfer_api/src/main/java/org/tensorflow/lite/examples/transfer/api/LiteMultipleSignatureModel.java)) to run the TF Lite interpreter on NNAPI delegate in the following manner. 

```
Interpreter.Options options = (new Interpreter.Options());
NnApiDelegate nnApiDelegate = null;
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
  nnApiDelegate = new NnApiDelegate();
  options.addDelegate(nnApiDelegate);
}
this.interpreter = new Interpreter(tfLiteModel, options);

```

I am getting the following error on initializing the interpreter with the NNAPI delegate option : 

```
12-07 15:35:51.585 11444 11444 E AndroidRuntime: java.lang.IllegalArgumentException: Internal error: Error applying delegate: 
12-07 15:35:51.585 11444 11444 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
12-07 15:35:51.585 11444 11444 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:93)
12-07 15:35:51.585 11444 11444 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
12-07 15:35:51.585 11444 11444 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
12-07 15:35:51.585 11444 11444 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:226)

```

I suspect that this error is arising due to the "train" signature of the tfliteModel which uses the [optimizer.apply_gradients](https://github.com/tensorflow/examples/blob/1e624527d2fea0333894156ad7a59d8d455b2c73/lite/examples/model_personalization/transfer_learning/generate_training_model.py#L96) function to update the model weights, as on creating a different tfliteModel with  this particular line commented, the above error is not observed.  

**Describe the expected behavior**

Is there any way to add NNAPI delegate to the TF Lite interpreter for this trainable model?

**Comment by sushreebarsa** [comment]
@sj120698 
In order to reproduce the issue reported here, could you please provide the complete code and the dataset , tensorflow version you are using. Thanks!

**Comment by sj120698** [comment]
@sushreebarsa 
I have used the same code snippet to apply NNAPI delegate over TF Lite Interpreter as given on the link you have mentioned. The problem is that the TF Lite model I am giving to the interpreter has optimizer.apply_gradients function in one of its signatures which is causing the issue.

**Comment by sushreebarsa** [comment]
@sj120698 
In order to reproduce the issue reported here, could you please provide tensorflow version you are using. Thanks!

**Comment by sj120698** [comment]
@sushreebarsa 
On the python side I am using tensorflow v2.7.0 (as given in [requirements.txt](https://github.com/tensorflow/examples/blob/master/lite/examples/model_personalization/transfer_learning/requirements.txt)) and on android side I am importing TF Lite as follows through [build.gradle](https://github.com/tensorflow/examples/blob/master/lite/examples/model_personalization/android/transfer_api/build.gradle) - 

```
implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
```

**Comment by srjoglekar246** [comment]
The model personalization example currently does not support delegates :-). We are working on it, but there are multiple performance bottlenecks in on-device training (for eg usage of dynamically-shaped TF ops in TFLite) that hamper usage of backends like NNAPI. For now, CPU is the only path unfortunately.

**Comment by bogdantmm92** [comment]
Not sure what is the solution for this issue. I'm having the same problem with a Conv2D layer.
