### ISSUE TITLE
op requires element_shape to be static during TF Lite transformation pass <unknown>:0: note: loc("StatefulPartitionedCall")

### ISSUE THREAD

**Issue by shhdSU** [tensorflow/tensorflow#53333]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Macbook Pro 
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source):  version 2.7.0

### 2. Code

`from tensorflow import lite
converter = lite.TFLiteConverter.from_keras_model(h_model)

tfmodel = converter.convert()
open('model.tflite', 'wb').write(tfmodel)`

### 3. Failure after conversion

ConverterError: /Users/shahadsulaiman/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py:1315:0: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
/Users/shahadsulaiman/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py:1315:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False

### 4. (optional) RNN conversion support
`
inputs1 = Input(shape=(2048,))
fe1 = Dropout(0.5)(inputs1)
fe2 = Dense(256, activation='relu')(fe1)

inputs2 = Input(shape=(max_length,))
se1 = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs2)
se2 = Dropout(0.5)(se1)
se3 = LSTM(256)(se2)

decoder1 = add([fe2, se3])
decoder2 = Dense(256, activation='relu')(decoder1)
outputs = Dense(vocab_size, activation='softmax')(decoder2)

h_model = Model(inputs=[inputs1, inputs2], outputs=outputs)`

**Comment by mathshangw** [comment]
excuse me did you solve it

**Comment by shhdSU** [comment]
> excuse me did you solve it

Yes, by the following code > 

`from tensorflow import lite
converter = lite.TFLiteConverter.from_keras_model(model_new)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]

tfmodel = converter.convert()
open('image_model.tflite', 'wb').write(tfmodel)

  `

**Comment by bisnu-sarkar-inverseai** [comment]
Thanks a lot. It works for me.
