### ISSUE TITLE
c++ tensorflow api inference .pb model is too slower, What can I do to speed it up ?

### ISSUE THREAD

**Issue by zzusunquan** [tensorflow/tensorflow#53334]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows 10  
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary):  tensorflow c++ api 
- TensorFlow version (use command below):  tensorflow 1.15 c++ api

**Describe the current behavior**

I compiled the api of tensorflow1.15_cpu version c++ and successfully called my pb model on the windows system. The problem now is that the speed of inference cannot meet my requirements.
I use deeplabv3+ (a model for semantic segmentation of graphics), which was trained on an Ubuntu system computer. GPU acceleration is used in the training process of this model.
The configuration of the Ubuntu system is as follows
-GPU: GeFore RTX 2080
-Memory: 7979MiB
The size of the pb model is 175MB. I call the pb model for inference on windows. I tested the time of seesion->run. It takes 3.5 seconds to infer a photo. This is too expensive. What can I do to shorten this time.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
`
void cvMat2tfTensor(cv::Mat input, tensorflow::Tensor& outputTensor)   
{
	auto outputTensorMapped = outputTensor.tensor<unsigned char, 4>();
	input.convertTo(input, CV_32FC3);
	cv::resize(input, input, cv::Size(1024, 1448));              

	int height = input.size().height;
	int width = input.size().width;
	int depth = input.channels();

	const float* data = (float*)input.data;
	for (int y = 0; y < height; ++y)
	{
		const float* dataRow = data + (y * width * depth);
		for (int x = 0; x < width; ++x)
		{
			const float* dataPixel = dataRow + (x * depth);
			for (int c = 0; c < depth; ++c)
			{
				const float* dataValue = dataPixel + c;
				outputTensorMapped(0, y, x, c) = *dataValue;
			}
		}
	}
}
`
`
int main()
{
	const std::string model_path = "D:/sunquan/home/home/TensorflowTest/tensorflowTest/frozen_inference_graph_wuhan.pb";	
	const std::string image_path = "D:/sunquan/home/home/TensorflowTest/segmantation/*.jpg";		// inference  image
	const std::string input_name = "ImageTensor";						  // input name
	const std::string output_name = "SemanticPredictions";				 // outpur name

	vector<String> image_files;   //inference image
	glob(image_path, image_files);  

	GraphDef graph_def;
	TF_CHECK_OK(ReadBinaryProto(Env::Default(), model_path, &graph_def));
	//	intial  tensorflow session
	std::unique_ptr<tensorflow::Session> session(tensorflow::NewSession(tensorflow::SessionOptions()));
	TF_CHECK_OK(session->Create(graph_def));

	for (int i = 0; i < image_files.size(); i++)
	{
		cv::Mat rgbImage = read_image(image_files[i]); 
		int channels = rgbImage.channels();
		tensorflow::Tensor input_tensor(DT_UINT8, TensorShape({ 1, 1448, 1024, channels })); 	
		cvMat2tfTensor(rgbImage, input_tensor); 
		std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = { { input_name, input_tensor } };
		std::vector<tensorflow::Tensor> outputs;
		clock_t start = clock();
		session->Run(inputs, { output_name }, {}, &outputs);
		clock_t end = clock();
		double endtime = (double)(end - start) / CLOCKS_PER_SEC;
		cout << " The cost of time is : " << endtime << " S " << endl;			
	}
	system(" pause ");
	return 0;
}
`
![image](https://user-images.githubusercontent.com/48703273/144982916-e6c16652-ba7a-49ef-9064-b5ebdf854bdd.png)

As you can see, except for the first photo that takes 8s to load the model, each of the remaining photos takes about 3.5s, which is too expensive

**Comment by tilakrayal** [comment]
@zzusunquan ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.

**Comment by zzusunquan** [comment]
@tilakrayal  Thank you very much for your prompt reply. I will try the 2.x version of tensorflow next week. I will reply to you in time if there is any progress.
