### ISSUE TITLE
Can I repeat a 1-D tensor in segment form?

### ISSUE THREAD

**Issue by HaozhengLi** [tensorflow/tensorflow#53336]
According to the doc, TF has: tf.segment_xxx and tf.repeat. But can I repeat a 1-D tensor in segment form?

#### Example:
segment = [0 0 0 1 1]
value = [0 1 2 3 4]

#### [ 1 ] If repeat_cnt = [2 2 2 1 1]
With tf.repeat, I can easily repeat value to: [0 0 1 1 2 2 3 4]

#### [ 2 ] But I want a segment repeat, which means: segment-0 repeat 2 times, segment-1 repeat 1 time.
That is to say, if repeat_cnt_new = [2 1], and I want to repeat value to: [0 1 2 0 1 2 3 4].

#### I mean, repeat blocks in a vector: [0 1 2] * 2 + [3 4] * 1. Are there any TF func or api can help?
Thanks!

**Comment by mohantym** [comment]
Hi @HaozhengLi ! Could you look at this [Gist](https://colab.research.google.com/gist/mohantym/b2f9af937f8a138b06aa7fcb93c41092/github_53336.ipynb#scrollTo=Dfk9iJC_OKrG) for answer?

**Comment by HaozhengLi** [comment]
> Hi @HaozhengLi ! Could you look at this [Gist](https://colab.research.google.com/gist/mohantym/b2f9af937f8a138b06aa7fcb93c41092/github_53336.ipynb#scrollTo=Dfk9iJC_OKrG) for answer?

No. I want [0 1 2 0 1 2 3 4], but not [0 0 1 1 2 2 3 4].

In this Gist, I understood what you want to do. You want to split value into [0 1 2] and [3 4], then repeat 2 times and 1 time, and finally concat.

But when I trying to train a MLP network, I must do all this things in ONE op. That is to say, my value.shape = [batch_size, 1].

It means that I can not manually split the value in Python, but only deal with the whole vector in serveral ops.

Thanks.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ! Could you please look at this issue?

**Comment by edloper** [comment]
One possible approach would be to use `RaggedTensor`. You can use `RaggedTensor.from_value_rowids` to construct a ragged tensor from values+segments. E.g.:

```python
>>> segment = [0, 0, 0, 1, 1]
>>> value = [0, 1, 2, 3, 4]
>>> rt = tf.RaggedTensor.from_value_rowids(value, segment)
print(rt)
<tf.RaggedTensor [[0, 1, 2], [3, 4]]>
```

And then you can use repeat + gather to repeat those rows:

```python
>>> repeat_cnt = [2, 1]
>>> gather_indices = tf.repeat(tf.range(tf.size(repeat_cnt)), repeat_cnt)
>>> repeated = tf.gather(rt, gather_indices)
>>> print(repeated)
<tf.RaggedTensor [[0, 1, 2], [0, 1, 2], [3, 4]]>
```

If you want the flat tensor (rather than a ragged tensor), you can use repeated.values:

```python
>>> print(repeated.values)
tf.Tensor([0 1 2 0 1 2 3 4], shape=(8,), dtype=int32)
```

**Comment by JXRiver** [comment]
Close the bug thanks to the example given by edloper. Please reopen the bug if the solution doesn't serve your purpose.
