### ISSUE TITLE
CTC Loss throwing errors in half/mixed precision

### ISSUE THREAD

**Issue by frgfm** [tensorflow/tensorflow#53345]
Hello there :wave: 

I have been running some experiments with automatic mixed-precision using TensorFlow recently. And I encountered an issue with the CTC loss, which throws an obscure dtype incompatibility issue. And I'm not sure how to solve this :thinking: 
Any ideas?

**System information**
- Have I written custom code: yes, the code snippet
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: binary, via pip
- TensorFlow version: 2.6.0
- Python version: 3.8
- CUDA/cuDNN version: CUDA 11.4 (cuDNN 8.2.0)
- GPU model and memory: NVIDIA GeForce RTX 2070 with Max-Q Design

**Describe the current behavior**

As of now, running the snippet further down below throws the following error:

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-2c1811c7c1ed> in <module>
     13 model_output = tf.random.uniform((batch_size, out_chans, vocab_size + 1), minval=0, maxval=1, dtype=tf.float16)
     14 
---> 15 tf.nn.ctc_loss(gt, model_output, seq_len, input_length, logits_time_major=False, blank_index=vocab_size)

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    204     """Call target, and fall back on dispatchers if there is a TypeError."""
    205     try:
--> 206       return target(*args, **kwargs)
    207     except (TypeError, ValueError):
    208       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/ctc_ops.py in ctc_loss_v3(labels, logits, label_length, logit_length, logits_time_major, unique, blank_index, name)
    960     blank_index = 0
    961 
--> 962   return ctc_loss_dense(
    963       labels=labels,
    964       logits=logits,

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/ctc_ops.py in ctc_loss_dense(labels, logits, label_length, logit_length, logits_time_major, unique, blank_index, name)
   1094       return result[0], grad
   1095 
-> 1096     return compute_ctc_loss(*args)
   1097 
   1098 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py in __call__(self, *a, **k)
    307 
    308   def __call__(self, *a, **k):
--> 309     return self._d(self._f, a, k)
    310 
    311 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py in decorated(wrapped, args, kwargs)
    261 
    262     if context.executing_eagerly():
--> 263       return _eager_mode_decorator(wrapped, args, kwargs)
    264     else:
    265       return _graph_mode_decorator(wrapped, args, kwargs)

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/custom_gradient.py in _eager_mode_decorator(f, args, kwargs)
    489   """Implement custom gradient decorator for eager mode."""
    490   with tape_lib.VariableWatcher() as variable_watcher:
--> 491     result, grad_fn = f(*args, **kwargs)
    492   args = nest.flatten(args)
    493   all_inputs = list(args) + list(kwargs.values())

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/ctc_ops.py in compute_ctc_loss(logits_t, labels_t, label_length_t, logit_length_t, *unique_t)
   1086       if unique_t:
   1087         kwargs["unique"] = unique_t
-> 1088       result = ctc_loss_and_grad(**kwargs)
   1089       def grad(grad_loss):
   1090         grad = [array_ops.reshape(grad_loss, [1, -1, 1]) * result[1]]

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/ctc_ops.py in ctc_loss_and_grad(logits, labels, label_length, logit_length, unique)
    689 
    690   ilabel_log_probs = nn_ops.log_softmax(logits)
--> 691   state_log_probs = _ilabel_to_state(labels, num_labels, ilabel_log_probs)
    692   state_trans_probs = _ctc_state_trans(labels)
    693   initial_state_log_probs, final_state_log_probs = ctc_state_log_probs(

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/ctc_ops.py in _ilabel_to_state(labels, num_labels, ilabel_log_probs)
    591   one_hot = array_ops.expand_dims(one_hot, axis=0)
    592   ilabel_log_probs = array_ops.expand_dims(ilabel_log_probs, axis=2)
--> 593   state_log_probs = math_ops.reduce_sum(ilabel_log_probs * one_hot, axis=3)
    594   state_log_probs = array_ops.concat([state_log_probs, blank], axis=2)
    595   return array_ops.pad(

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py in binary_op_wrapper(x, y)
   1365         #   r_binary_op_wrapper use different force_same_dtype values.
   1366         x, y = maybe_promote_tensors(x, y, force_same_dtype=False)
-> 1367         return func(x, y, name=name)
   1368       except (TypeError, ValueError) as e:
   1369         # Even if dispatching the op failed, the RHS may be a tensor aware

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py in _mul_dispatch(x, y, name)
   1708     return sparse_tensor.SparseTensor(y.indices, new_vals, y.dense_shape)
   1709   else:
-> 1710     return multiply(x, y, name=name)
   1711 
   1712 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    204     """Call target, and fall back on dispatchers if there is a TypeError."""
    205     try:
--> 206       return target(*args, **kwargs)
    207     except (TypeError, ValueError):
    208       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py in multiply(x, y, name)
    528   """
    529 
--> 530   return gen_math_ops.mul(x, y, name)
    531 
    532 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py in mul(x, y, name)
   6234       return _result
   6235     except _core._NotOkStatusException as e:
-> 6236       _ops.raise_from_not_ok_status(e, name)
   6237     except _core._FallbackException:
   6238       pass

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6939   message = e.message + (" name: " + name if name is not None else "")
   6940   # pylint: disable=protected-access
-> 6941   six.raise_from(core._status_to_exception(e.code, message), None)
   6942   # pylint: enable=protected-access
   6943 

~/miniconda3/lib/python3.8/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a half tensor but is a float tensor [Op:Mul]
```

**Describe the expected behavior**

the snippet running smoothly

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow.keras import mixed_precision

mixed_precision.set_global_policy('mixed_float16')

batch_size = 2
out_chans = 32
vocab_size = 10

gt = tf.zeros((batch_size, 5), dtype=tf.int32)
seq_len = [3, 4]
input_length = tf.fill((batch_size,), out_chans)
model_output = tf.random.uniform((batch_size, out_chans, vocab_size + 1), minval=0, maxval=1, dtype=tf.float16)

tf.nn.ctc_loss(gt, model_output, seq_len, input_length, logits_time_major=False, blank_index=vocab_size)

```

**Comment by tilakrayal** [comment]
@sanatmpa1 ,
I was able to reproduce the issue in tf 2.7, 2.5 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/02292fbc8236872182b34be86936b511/53345.ipynb).

**Comment by sanatmpa1** [comment]
@frgfm 

I modified dtype in model_output to tf.float32 and I can see that no error is thrown. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/3b6fb0a9a1ea76f324661dee6238fde3/53345.ipynb). Thanks!

**Comment by frgfm** [comment]
Hi @sanatmpa1, thanks for the reply!

However, I'm not sure I follow here: the reason why I create the model output in `tf.float16` is because that's what comes out of keras model in this dtype_policy (at least in my short experience with mixed precision in TF). So are you suggesting to cast the model output to float32 before sending it to the loss?

If so, shouldn't users be able to use this policy without modifying their internal loss computation? (I was expecting the loss to perform those operations internally if necessary considering I set the dtype_policy globally)
If not, would you mind elaborating a bit please? :pray:

**Comment by sachinprasadhs** [comment]
Generally when you set the Mixed precision dtype policy to float16, it uses float16 for computations and float32 for variables in-order to bring the numeric stability. 
You can try printing the below lines to validate.
```
print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
```
Refer [this](https://www.tensorflow.org/guide/mixed_precision) document for more details.

**Comment by frgfm** [comment]
> Generally when you set the Mixed precision dtype policy to float16, it uses float16 for computations and float32 for variables in-order to bring the numeric stability. You can try printing the below lines to validate.
> 
> ```
> print('Compute dtype: %s' % policy.compute_dtype)
> print('Variable dtype: %s' % policy.variable_dtype)
> ```
> 
> Refer [this](https://www.tensorflow.org/guide/mixed_precision) document for more details.

Hi @sachinprasadhs,

I'm not sure I understand how it's related to my previous comment :thinking:
Simply put: if mixed precision policy is used, the CTC loss crashes. My snippet above is reproducing this error, because the CTC doesn't support float16.

So there are 2 questions here:
- is this normal that this loss doesn't support float16?
- if it is, how should one use this? I understand quite well that variables are in fp32 and operations in fp16, but I guess that still means that it's normal for the model output to be in fp16. And in that case, I would argue that some additional information should be added to document the usage.

**Comment by sachinprasadhs** [comment]
Refer to [this](https://github.com/keras-team/keras/blob/83bee297d7176beb6ed197963669b0dd55acea0c/keras/mixed_precision/policy.py#L262) compute_dtype code of mixed_precision_policy and the explanation below that, hope it clarifies your above question. Thanks!

**Comment by frgfm** [comment]
Hi @sachinprasadhs !

Thanks, but I still think there is something missing here: the way the operations are handled internally is not an issue. Here I didn't write a custom loss function.

The problem is:
- using the mixed precision policy, my model output logits comes in `tf.float16` (which is expected)
- I used the official TF ctc_loss. So this takes as arguments a tensor in `tf.float16` (because of the mixed precision policy mentioned just above), which is also logical/expected
- but here the loss doesn't accept that data type

So either:
- I missed something in the doc saying "You have to cast any args to `tf.float32` for the CTC loss" :man_shrugging: 
- or this is an issue that hasn't been handled

**Comment by reedwm** [comment]
@frgfm, as a workaround until this bug is fixed, you can cast the model output (the second argument to ctc_loss) to float32 before passing it to `tf.nn.ctc_loss`. The [mixed precision guide](https://www.tensorflow.org/guide/mixed_precision) also recommends this, mostly because numeric issues can occur if the tensor flowing between a softmax and cross entropy loss is in float16, but also due to issues where losses do not support float16 or have numeric issues with float16. All built-in losses should support float16 though, so this is bug.

/CC @nluehr @benbarsdell, the errors come from the fact float32 tensors are created, followed by dtype mismatches on [this line](https://github.com/tensorflow/tensorflow/blob/8f761b623768c5ed59a502d7eff35cc0c3bccb16/tensorflow/python/ops/ctc_ops.py#L591) and [this line](https://github.com/tensorflow/tensorflow/blob/8f761b623768c5ed59a502d7eff35cc0c3bccb16/tensorflow/python/ops/ctc_ops.py#L595). Do you think we should fix these individual dtype mismatches, or just have `ctc_loss` cast its inputs to float32 and outputs back to float16? I don't understand how ctc loss works, but it has a lot of reductions and exponentials, making me worried that just fixing the individual dtype mismatches will cause numeric issues.
