### ISSUE TITLE
Debugger-V2 crashes with KeyError

### ISSUE THREAD

**Issue by dniku** [tensorflow/tensorflow#53344]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Docker image based on Ubuntu 18.04 Bionic
- TensorFlow installed from (source or binary): built from patched source code
- TensorFlow version (use command below): `v2.1.3-0-g77f47d6ed6c 2.1.3`
- Python version: `3.6.9`
- Bazel version (if compiling from source): `4.2.1`
- GCC/Compiler version (if compiling from source): `g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`
- CUDA/cuDNN version:  `libcudnn8/unstable 8.0.5.39-1+cuda11.1 amd64`
- GPU model and memory: Nvidia GeForce RTX 2080

**Describe the current behavior**

I am trying to set up Debugger-V2. My project currently uses Tensorflow 2.1.3 and, as far as I understand, the corresponding Tensorboard version does not support Debugger-V2. Therefore I have set up a separate Conda environment with Tensorboard 2.7.0, where I load logs written using Tensorflow 2.1.3. The "system information" block above provides details on the environment in which the rest of my project runs.

In this setup, the Debugger-V2 UI comes up empty (e.g. it says `Graph Executions (0)` in the top right corner), and there is the following traceback in stdout:

```
> tensorboard --logdir tensorboard_logs/train/ --port 6010
2021-12-07 18:07:08.627387: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.7.0 at http://localhost:6010/ (Press CTRL+C to quit)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "<redacted>/.miniconda3/envs/dl-tensorflow/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "<redacted>/.miniconda3/envs/dl-tensorflow/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "<redacted>/.miniconda3/envs/dl-tensorflow/lib/python3.9/site-packages/tensorboard/plugins/debugger_v2/debug_data_multiplexer.py", line 62, in _run_repeatedly
    target()
  File "<redacted>/.miniconda3/envs/dl-tensorflow/lib/python3.9/site-packages/tensorflow/python/debug/lib/debug_events_reader.py", line 1116, in update
    self._load_graphs()
  File "<redacted>/.miniconda3/envs/dl-tensorflow/lib/python3.9/site-packages/tensorflow/python/debug/lib/debug_events_reader.py", line 1013, in _load_graphs
    debugged_graph = self._graph_by_id[op_creation_proto.graph_id]
KeyError: '0410a4d0-d88b-44f9-b7f5-a49008436b15'
```

The error comes from [this line](https://github.com/tensorflow/tensorflow/blob/d1c4acc743e6f5710e38595ea0c6c876205e8399/tensorflow/python/debug/lib/debug_events_reader.py#L1009).

The directory structure of `tensorboard_logs` is as follows:

```
tensorboard_logs/
└── train
    ├── events.out.tfevents.1638889539.<redacted>.118102.192768.v2
    ├── tfdbg_events.1638889418.<redacted>.execution
    ├── tfdbg_events.1638889418.<redacted>.graph_execution_traces
    ├── tfdbg_events.1638889418.<redacted>.graphs
    ├── tfdbg_events.1638889418.<redacted>.metadata
    ├── tfdbg_events.1638889418.<redacted>.source_files
    └── tfdbg_events.1638889418.<redacted>.stack_frames
```

and I set up debug logging with the following line:

```
        tf.debugging.experimental.enable_dump_debug_info(
            os.path.join(<tensorboard_logs>, 'train'),
            tensor_debug_mode='FULL_TENSOR',  # b/c TF 2.1 doesn't support FULL_HEALTH
            circular_buffer_size=10000)
```

I won't be able to share the log files that cause this crash, and I don't have a minimal reproducing example (yet?). Hopefully this is debuggable without the two.

Aside from the obvious problem with this crash, I am also not sure where I should put debug info (what the first parameter of `enable_dump_debug_info` should be). My logging is done via Keras, and the typical directory structure is as follows:

```
tensorboard_logs/
└── train
└── validation
```

I see 3 places where I could put debug info:

```
tensorboard_logs/  # <- here
└── train  # <- here
└── validation
└── debug_info  # <- here
```

and then I could point Tensorboard to any of those directories. Which is the preferred way?

**Comment by mohantym** [comment]
Hi @sanatmpa1 ! Could you please look at this issue?

**Comment by sanatmpa1** [comment]
@dniku,

This looks like an issue that is mostly related to `Tensorboard`, Can you kindly create a new issue on [Tensorboard repo](https://github.com/tensorflow/tensorboard/issues)? Thanks!

**Comment by dniku** [comment]
Per request from @sanatmpa1, migrated this to https://github.com/tensorflow/tensorboard/issues/5482 .
