### ISSUE TITLE
sound_classification example can not work on iOS 15.0+

### ISSUE THREAD

**Issue by zxl777** [tensorflow/tensorflow#53351]
Source:
https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/ios

I tested it on an iOS14 device and it worked fine.

I changed several iOS15.0+ devices, but they couldn't work. The phenomenon is that the progress bar jumps randomly and the data is messy.

I am sure that this is a bug that only appears on iOS 15.0+ and will recur 100%.

**Comment by sushreebarsa** [comment]
@zxl777 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by zxl777** [comment]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No, https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/ios
The source code has not changed.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
iOS 15.0+

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
iPhone 12 mini, iPhone X, iPhone 13 mini

- TensorFlow installed from (source or binary):
source

- TensorFlow version (use command below):


- Python version:
No Python

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The app did not correctly recognize the applause. The progress bar is constantly changing, and the progress bar does not respond to sound as normal as in iOS14.

**Describe the expected behavior**
Like in iOS14, when I clap my hands, the bottom progress bar shows the largest.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/ios


**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by MrinalTyagi** [comment]
I would like to work in this issue do fix the example. There were many updates in iOS 15 that makes the developers to change features a bit. That could be a reason.

**Comment by zxl777** [comment]
Any news?

**Comment by mohantym** [comment]
@MrinalTyagi ! Feel free to raise a PR for this issue. Thanks!

**Comment by pjpratik** [comment]
The podfiles have now been updated to latest versions with commit https://github.com/tensorflow/examples/commit/3df76a9e45e3a1d6165e42c565a2f8622f7c1f8c

with the following lines 
https://github.com/tensorflow/examples/blob/3df76a9e45e3a1d6165e42c565a2f8622f7c1f8c/lite/examples/sound_classification/ios/Podfile.lock#L2-L9

 ```
  - TensorFlowLiteC (0.0.1-nightly.20230414):
    - TensorFlowLiteC/Core (= 0.0.1-nightly.20230414)
  - TensorFlowLiteC/Core (0.0.1-nightly.20230414)
  - TensorFlowLiteSelectTfOps (0.0.1-nightly.20230414)
  - TensorFlowLiteSwift (0.0.1-nightly.20230414):
    - TensorFlowLiteSwift/Core (= 0.0.1-nightly.20230414)
  - TensorFlowLiteSwift/Core (0.0.1-nightly.20230414):
    - TensorFlowLiteC (= 0.0.1-nightly.20230414)
```
Could you please in latest version and let us know if it is resolved?

Thanks.
