### ISSUE TITLE
[Help] how to fix i tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] none of the mlir optimization passes are enabled (registered 2)

### ISSUE THREAD

**Issue by dekkuz** [tensorflow/tensorflow#53354]
i used tf-cpu 2.6.0, python 3.9 run program in vscode env for conda find fault 
**i tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] none of the mlir optimization passes are enabled (registered 2)**

how this fix ??
chatbot with LSTM
thanks

**Comment by sushreebarsa** [comment]
@dekkuz 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
