### ISSUE TITLE
tf.random.uniform can't generate random tensor of type tf.int32

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#53355]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8.10
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.7.0-rc1-69-gc256c071bb2 2.7.0

**Describe the current behavior**

tf.random.uniform can generate random tensor of type tf.float32 with distinct minvals and maxvals, but can't do it for tf.int32.

**Describe the expected behavior**

tf.random.uniform should generate random tensor for both tf.float32 and tf.int32 with distinct minvals and maxvals.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
#!/usr/bin/python3
import tensorflow as tf;
# generate random tensor of tf.float32 is OK
a = tf.random.uniform(minval = (1,2,3,4), maxval = (3,4,5,6), shape = (4,), dtype = tf.float32);
# generate random tensor of tf.int32 is not OK
a = tf.random.uniform(minval = (1,2,3,4), maxval = (3,4,5,6), shape = (4,), dtype = tf.int32);
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: minval must be 0-D, got shape [4] [Op:RandomUniformInt]
```

**Comment by mohantym** [comment]
Hi @breadbread1984 ! As per this [document](https://www.tensorflow.org/api_docs/python/tf/random/uniform#args) For minval and maxval -Tensor or Python value of type dtype, broadcastable with shape **(for integer types, broadcasting is not supported, so it needs to be a scalar)**. So you need to provide a scalar value in case of using dtype int32. Attaching [Gist](https://colab.research.google.com/gist/mohantym/7bfe663a5806b4ed119d9737671771f4/github_53355.ipynb) for reference. Thanks!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
