### ISSUE TITLE
Abnormally long loading/calling time for Tensorflow

### ISSUE THREAD

**Issue by Irene-kim** [tensorflow/tensorflow#53352]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.3 LTS
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version:CUDA: 11.1 / 8.1.4
- GPU model and memory: RTX 3080, 10GB x 2

**Describe the current behavior**
We've found that it takes an unexpectedly long loading time when calling Tensorflow or machine learning models. Once the library/model is loaded, it takes significantly less time afterwards. However, whenever we are restarting the kernel we run into the exact same problem. 

**Standalone code to reproduce the issue**
The reproducible code is provided below:
```
import tensorflow as tf
import time

print(f"TensorFlow version: {tf.__version__}")

start = time.time()
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
end = time.time()

print(f"it took = {end - start} seconds")
```
Below is the result of the above code block:
```
TensorFlow version: 2.4.1
tf.Tensor(973.3261, shape=(), dtype=float32)
it took = 273.7537660598755 seconds
```
As you can see it takes way too much time for such a simple task. This issue applies the same when we are trying to call functions such as `model.fit` or `model.summary()`. The reproducible code below is another example of the problem. We used a simple CNN model with the cifar10 dataset. It took extensive time to just load the model for some reason. Additionally, when we are calling the `fit` function it takes forever time to actually run Epochs.
```
import random
import numpy as np

import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
import time

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

X_train = X_train.reshape(50000, 32, 32, 3).astype("float32") / 255
X_test = X_test.reshape(10000, 32, 32, 3).astype("float32") / 255

def CNN():
    input_layer = keras.Input(shape=(32,32,3))
    conv = keras.layers.Conv2D(32, (3,3), padding='same', activation = 'relu', kernel_initializer = keras.initializers.HeUniform(seed=1))(input_layer)
    max_pool = keras.layers.MaxPooling2D((2, 2))(conv)
    flatten = keras.layers.Flatten()(max_pool)
    dense = keras.layers.Dense(128, activation='relu', kernel_initializer = keras.initializers.HeUniform(seed=1))(flatten)
    output_layer = keras.layers.Dense(10, activation='softmax')(dense)
    model = keras.Model(inputs=input_layer, outputs=output_layer, name = 'CNN')
    model.compile(loss='categorical_crossentropy', optimizer= keras.optimizers.Adam(learning_rate=0.001),  metrics=['acc', 'AUC'])
    return model 

start = time.time()
model = CNN()
end = time.time()
print(f"it took = {end - start} seconds")
>>> it took = 109.86318612098694 seconds

start = time.time()
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))
end = time.time()
print(f"it took = {end - start} seconds")
>>> it took = 809.008472442627 seconds
```

We would love to figure out what is causing such a problem and a way to fix this. We greatly appreciate your help and support in advance.

**Comment by mohantym** [comment]
Hi @Irene-kim ! Could you try again in latest version with test [configurations](https://www.tensorflow.org/install/source)?Could not replicate this issues in Colab  neither in CPU /GPU. Attaching Gist in [2.7](https://colab.research.google.com/gist/mohantym/5650123ba1bf5809615c763fdfb5d135/github_53352_2-7_gpu.ipynb#scrollTo=VVWfkQUpKmUg) for reference. Thank you!

**Comment by jaeyung1001** [comment]
Hi @mohantym ! I'm a coworker with @Irene-kim, I have installed tensorflow-gpu=2.7.0 version. and ran the below commands but now the tensorflow cannot recognize my local gpu machine.

```python
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices())
# 2.7.0
# [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
# 0
```

**Comment by mohantym** [comment]
Ok @jaeyung1001 ! Could you confirm on whether you have properly [configured](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) Cuda 11.2 and CudNN 8.1 or not?

**Comment by jaeyung1001** [comment]
hi @mohantym ! I reinstalled my CUDA11.2 & cuDNN 8.1 for TF2.7, but I still encounter same issue about cannot recognize my local gpu machine.

when I ran below command & show result:
```
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices())
2.7.0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
2021-12-10 13:28:55.407463: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-10 13:28:55.407668: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-10 13:28:55.410724: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64:/usr/local/cuda-11/lib64
2021-12-10 13:28:55.410733: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

and
- the libcudnn.so.8 file exists in /usr/local/cuda-11.2/lib64
- the LD_LIBRARY_PATH(/usr/local/cuda-11.2/lib64) exists in ENV

**Comment by mohantym** [comment]
Hi @chunduriv! Could you please look at this issue. Its not replicating in Colab environment though. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/5650123ba1bf5809615c763fdfb5d135/github_53352_2-7_gpu.ipynb#scrollTo=VVWfkQUpKmUg) in 2.7  for reference. Thanks!

**Comment by chunduriv** [comment]
@Irene-kim, Generally if there was any incompatible between TF, CUDA and cuDNN versions we can observe this behavior. To get benefit we recommend to follow [tested build configurations](https://www.tensorflow.org/install/source#gpu).

@jaeyung1001, Can you please let us know steps that you have followed to install Tensorflow?

**Comment by jaeyung1001** [comment]
hi @chunduriv !. I follow the environment that you told me the link.
- tensorflow-gpu 2.6.0, CUDA11.2, cuDNN8.1

first I created the virtualenv using conda. and ran the command like below
- conda create -n check python=3.8
- pip install tensorflow-gpu==2.6.0

but it's still cannot recognize my local gpu machine. output like below
```
2.6.0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
2021-12-13 12:28:52.446773: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-13 12:28:52.446958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-13 12:28:52.450091: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.2/lib64/
2021-12-13 12:28:52.450100: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

**Comment by chunduriv** [comment]
@jaeyung1001, Sorry for late response.

Can you please confirm that you have followed steps mentioned below?

#Set Up Anaconda Environments
`conda create --name tf_gpu python=3.8
`
#Activate the new Environment
`source activate tf_gpu
`
#Install CUDA and cuDNN
`tf_gpu$conda install -c anaconda cudatoolkit=11.2 cudnn=8.1
`
#Install Tensorflow
`tf_gpu$ pip install tensorflow-gpu==2.6`

**Comment by jaeyung1001** [comment]
hi @chunduriv , there is no same version of cudatoolkit and cudnn
![image](https://user-images.githubusercontent.com/11284021/147191464-f2315c95-f6e6-4c28-8de9-e7f72865922c.png)
![image](https://user-images.githubusercontent.com/11284021/147191489-d6aca22d-59c9-497a-a1cf-19cda899a6b8.png)

**Comment by jaeyung1001** [comment]
I think something go wrong with my system problem. So I used **docker image file** to resolved it. thank you.

https://hub.docker.com/layers/tensorflow/serving/2.6.0-devel-gpu/images/sha256-f935ceb90139a7b12d61e1a13bc5e1cc0332728f7c223f469cb9b39b7a67b1d2?context=explore
