### ISSUE TITLE
Passing empty tensors to TFLite converted signatures fails with an exception

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#53356]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): tf-nightly 2.8.0-dev20211203 and 2.7 are both affected

### 2. Code

```python
import tensorflow as tf

class TestModel(tf.keras.models.Model):
  @tf.function
  def test(self, x):
    return x

test_model = TestModel()
signatures = [test_model.test.get_concrete_function(tf.TensorSpec([None], tf.float32))]

converter = tf.lite.TFLiteConverter.from_concrete_functions(signatures, test_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# This raises "ValueError: Cannot set tensor: Tensor is unallocated. Try calling allocate_tensors() first"
result = interpreter.get_signature_runner()(x=tf.zeros([0], tf.float32))
```

### 3. Failure after conversion
Conversion seems to work fine, but trying to run the signature fails with the following exception if an empty tensor is passed.

`ValueError: Cannot set tensor: Tensor is unallocated. Try calling allocate_tensors() first`

Despite the message, calling `allocate_tensors()` before has no effect. Passing a tensor that is not empty does not cause the failure.

While passing an empty tensor might seem absurd at first, I'm hitting this issue in much more subtle scenarios like passing shapes of tensors (it fails if the shape is for a scalar because it's empty), or when using ragged tensors where one of its internal row splits happens to be empty.

Note that returning empty tensors from within a TFLite converted function also fails. In that case you get this other exception:

`ValueError: Invalid tensor size.`

A workaround would be much appreciated if possible, though it seems unlikely without a proper fix.

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.5 , v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b097f87fda554821341bb11b6c278d56/53356.ipynb).

**Comment by karimnosseir** [comment]
@leandro-gracia-gil Can you please retry from master branch ?

**Comment by karimnosseir** [comment]
If easier wait for a new nightly and then retry.

Thanks

**Comment by leandro-gracia-gil** [comment]
> If easier wait for a new nightly and then retry.

I'll do that, thanks!

**Comment by leandro-gracia-gil** [comment]
Seems to work fine now. Thanks for the fix! I'll be closing this issue.
