### ISSUE TITLE
Is there any way to add classes in inception?

### ISSUE THREAD

**Issue by daddym85** [tensorflow/tensorflow#5335]
Hi there,
I'm working on retrain example; I have TensorFlow built from source on Ubuntu 14.04, and the examples on flowers work great. However, the process strips away the Inception's final layer and removes all 1,000 existing categories, which means it can now identify 5 species of flowers, but can no longer identify pandas, for example. https://www.tensorflow.org/versions/r0.8/how_tos/image_retraining/index.html

How can I add the 5 flower categories to the existing 1,000 categories from ImageNet (and add training for those 5 new flower categories) so that I have 1,005 categories that a test image can be classified as? In other words, be able to identify both those pandas and sunflowers?

Thanks

**Comment by aselle** [comment]
This question is more important for StackOverflow, since it concerns using Inception so closing for now. @shlens might have a quick answer. Barring anything else, why not just try adding 5 to the original labels and see if that works.
