### ISSUE TITLE
tensorflow/c/c_api_experimental.cc:698:41: error: 'class tensorflow::EagerContext' has no member named 'StoreCollectiveOpsServer'

### ISSUE THREAD

**Issue by luojuan2020** [tensorflow/tensorflow#53366]
编译  tensorflow 1.14版本，提示
tensorflow/c/c_api_experimental.cc:698:41: error: 'class tensorflow::EagerContext' has no member named 'StoreCollectiveOpsServer'

**Comment by mohantym** [comment]
Hi @luojuan2020 ! 
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!
