### ISSUE TITLE
Autoformat entire codebase?

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/tensorflow#53360]
There are two popular ways of applying and enforcing automatic source code formatting a codebase like yours, these are:
- [clang-format](https://clang.llvm.org/docs/ClangFormat.html) (e.g., for your C++ and protobuf files)
- [black](https://github.com/psf/black) (for your Python and Jupyter Notebook files)

Which is as easy as:
```sh
$ python -m black .
$ fd -eh -ec -ehpp -ecpp -eproto -x clang-format -i --style=Google {} \;
```

Review changes:

  - https://github.com/offscale/tensorflow/tree/clang-format-apply from `clang-format` 13.0.0 at 9ebfeab
  - https://github.com/offscale/tensorflow/tree/black from `python -m black` 21.12b0 also at 9ebfeab

---

**Related**:

   - https://github.com/tensorflow/addons does a bunch of auto format and auto linting
   - My recently merged PR: #53329

**Disadvantages**:

  - Impact just about every file in the codebase
  - Require open PRs to be modified and forks to be updated

**Mitigation of disadvantages**:

  - To avoid stepping on toes, one can write a pull request scanner to avoid touching any file that has a current pull request lodged against it. I'm happy to write this script, but will also need someone to run this internally so it knows what files are being affected by non public PRs

**Advantages**:

  - Easier for automated tooling to make automated fixes (whitespace / prettyprinting issues don't get in the way)
  - More consistent codebase (which is somewhat of a quality metric)

**Comment by tilakrayal** [comment]
@SamuelMarks ,
Please feel free to submit a PR for the requested change or share the link where requested change is to be made in respective repo.Thanks!

**Comment by MarkDaoust** [comment]
See my comment on the PR. 

We have internal systems for this, and generally we only apply autoformatting to code when we're updating it for other reasons. 

Formatting just to format makes code history harder to follow.

**Comment by SamuelMarks** [comment]
@MarkDaoust Yeah I agree formatting makes code history harder to follow. Which is why generally all these niceties (autolinters, autoformatters, &etc.) are done at the beginning of a project (and not 6 years later).

Still though, I wanted to start the discussion and see if there was any appetite for such.

Naturally autoformatters greatly simplify automated code modification tooling, and the consistency aids in readability/grokking.

**Comment by MarkDaoust** [comment]
Yeah, we have them. Some as presubmit checks in github, some as internal presubmits. But typically we don't apply them to existing code unless it's something we're touching for other reasons.
