### ISSUE TITLE
Selective build for iOS does not produce TensorFlowLiteC_framework.zip

### ISSUE THREAD

**Issue by sliu54** [tensorflow/tensorflow#53364]
### System information
-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 11.4
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: building from source using latest TF source code
-   **Python version**: 3.9.4
-   **Bazel version (if compiling from source)**: 4.2.1
-   **GCC/Compiler version (if compiling from source)**: Apple clang 13.0.0
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**: 
```
bash tensorflow/lite/ios/build_frameworks.sh --input_models=model.tflite --target_archs=x86_64,armv7,arm64
```

### Describe the problem
We are performing a selective build for iOS to reduce TF binary size following the instructions here:
https://www.tensorflow.org/lite/guide/reduce_binary_size#selective_build_for_ios

Recently we have followed the instructions for Android on the same page and used the same machine to successfully compile the selective build AAR. For iOS, we followed a similar procedure of running `./configure` with iOS support, then running the selective build script to generate the framework using the command above. 

According to the documentation, the framework should be located at `bazel-bin/tensorflow/lite/ios/tmp/TensorFlowLiteC_framework.zip`, but the file does not exist after the build is complete. There are no errors in the output, and it states that the build is successful at the end.

The issue does not seem to be related to our specific model, since we also tried it with the MobileNet provided here but encountered the same issue:
https://www.tensorflow.org/lite/guide/reduce_binary_size#overview

### Source code / logs
The complete output is attached. Also attached the log when using the provided MobileNet on a fresh repo. That one had some warnings the first time it was run but still stated that the build was successful (no output still), not sure if it's significant.

[tf-lite-log.txt](https://github.com/tensorflow/tensorflow/files/7682282/tf-lite-log.txt)
[tf-lite-log-mobilenet.txt](https://github.com/tensorflow/tensorflow/files/7682384/tf-lite-log-mobilenet.txt)

**Comment by tilakrayal** [comment]
@sliu54 ,
Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/25800#issuecomment-475818277) from the issue with similar error.It helps.Thanks

**Comment by sliu54** [comment]
@tilakrayal Thanks for your reply. Do you mind elaborating on how that comment relates to the issue I'm seeing? My issue is that the selective build script does not generate TensorFlowLiteC_framework.zip. Looks like in that comment they already assumed that TensorFlowLiteC_framework.zip exists and talked about how to get it working with CocoaPods. Please let me know if I misunderstood.

**Comment by sumocodes** [comment]
I am seeing this issue as well, the `build_frameworks.sh` script runs successfully but does not provide a build output (TensorFlowLiteC_framework.zip).

**Comment by MoonshotQuest** [comment]
I am experiencing the same issue as well. I am on MacOs 11.1 with TensorFlow 2.8.0 and Bazel 4.2.1 also. 

This is the original instruction (I removed my username with ***). I tried with and without `sudo`, I thought it was a permission issue. Same result the file is missing at the end.

`sudo bash tensorflow-2.8.0/tensorflow/lite/ios/build_frameworks.sh --input_models=/Users/***/models/model1.tflite,/Users/***/models/model2.tflite --target_archs=arm64`

And this is the end of the log after 6h running. Is there any solution?
```
INFO: Elapsed time: 27512.231s, Critical Path: 809.68s
INFO: 13693 processes: 3141 internal, 10552 local.
INFO: Build completed successfully, 13693 total actions
Output can be found here:
ls: /Users/***/tensorflow-2.8.0/bazel-bin/tensorflow/lite/ios/tmp/TensorFlowLiteC_framework.zip: No such file or directory
```

**Comment by MoonshotQuest** [comment]
I just found 2 framework files `TensorFlowLiteC_framework.zip` and `TensorFlowLiteSelectTfOps_framework.zip` in this folder:
`/private/var/tmp/_bazel_root/843fec9a8c5b415f6f82b90b06399d42/execroot/org_tensorflow/bazel-out/applebin_ios-ios_arm64-opt-ST-02f4a105b518/bin/tensorflow/lite/ios/tmp`

and also in this folder (I tried 2 times the build, with/without sudo, so this would make sense): 
`/private/var/tmp/_bazel_[MY_USERNAME]/843fec9a8c5b415f6f82b90b06399d42/execroot/org_tensorflow/bazel-out/applebin_ios-ios_arm64-opt-ST-02f4a105b518/bin/tensorflow/lite/ios/tmp`

Looking at the dates of these files:
- `TensorFlowLiteC_framework.zip` was created when the process started 
- `TensorFlowLiteSelectTfOps_framework.zip` created when the build was complete

Are these the files? 😆

@sumocodes @sliu54 - Can you confirm you see the same files by doing a search for the word "framework" inside `/private/var/tmp/_bazel_root` and/or `/private/var/tmp/_bazel_[YOUR_USERNAME]`?

@teijeong @tilakrayal If that's the case (and I hope so) that would mean potential error in this [file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/ios/build_frameworks.sh)
Here:
```
function print_output {
  echo "Output can be found here:"
  for i in "${OUT_FILES[@]}"
  do
    # ls command returns failure if the file does not exist.
    ls -1a ${ROOT_DIR}/$i
  done
}
```
Thanks.

**Comment by sumocodes** [comment]
Thanks for responding @MoonshotQuest! I was able to find the framework files in `/private/var/tmp/_bazel_[MY_USERNAME]`. It looks like the script needs to be updated output the new location.

**Comment by sliu54** [comment]
@MoonshotQuest Great finding! I was also able to find the framework files at the location you specified. Thanks a lot!

@MoonshotQuest @sumocodes As a side question, have you guys been able to successfully incorporate the generated framework file into your Xcode project? I'm following the instructions [here](https://www.tensorflow.org/lite/guide/build_ios#using_local_tensorflow_lite_core), but I'm not very familiar with CocoaPods so I'm not sure if my `Podfile` and `podspec` configurations are correct. It seems like we need two `podspec`, one for `TensorFlowLiteC` and one for `TensorFlowLiteSwift`? The instructions also mentioned about setting up a private repo, but I have seen solutions where in `podspec` the source is pointed to a local path, so I'm also wondering if this step is required? I tried to have the source in `TensorFlowLiteC.podspec` point to the generated `TensorFlowLiteC_framework.zip`, but I'm confused about how to have the dependency in `TensorFlowLitSwift.podspec` also point to my local `TensorFlowLiteC`. I don't think I'm doing it correctly because right now if I run `pod update`, the process completes successfully, but Xcode is unable to find the TensorFlowLite module when I import it. Just wondering if you have gotten this to work and appreciate any suggestions :)

**Comment by pkgoogle** [comment]
Hi @sliu54, we believe this is fixed now, can you try again to see if your issue is resolved?
