### ISSUE TITLE
Running quantized TF Lite model on Android receives error "Failed to run on the given Interpreter"

### ISSUE THREAD

**Issue by sliu54** [tensorflow/tensorflow#53361]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: tested on Samsung Galaxy device and Pixel 4 emulator
-   **TensorFlow installed from (source or binary)**: tried both (binary compiled on macOS 11.4)
-   **TensorFlow version (use command below)**: tried 2.2.0, 2.5,0, 2.7.0, and nightly
-   **Python version**: Python 3.9
-   **Bazel version (if compiling from source)**: 4.2.1
-   **GCC/Compiler version (if compiling from source)**: Apple clang 13.0.0
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
When running inference on a quantized LSTM TF Lite model in Android, we receive the following error:
```
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/transpose.cc:55 op_context->perm->dims->data[0] != dims (3 != 2)
    Node number 9 (TRANSPOSE) failed to prepare.
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:241)
        at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:135)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:80)
        at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:128)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:80)
```

The unquantized model works fine in Android. The quantized model works fine in iOS and Python.
We have tried using 2.2.0, 2.5.0, 2.7.0, and nightly to quantize the model in Python and include the respective versions in the Android build.gradle dependencies:
```
implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
```
We have also tried using selective builds with the latest TF source code.

### Source code / logs
Code for quantizing the model in Python:
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_quantizer = True
converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

We referenced the text classification example for Android in the repo for performing inference in Java:
```
ByteBuffer buffer = loadModelFile(assetManager, modelPath);
private Interpreter tflite = new Interpreter(buffer);
float[][] output = new float[1][labels.size()];
tflite.run(input, output);

private static MappedByteBuffer loadModelFile(AssetManager assetManager, String modelPath)
    throws IOException {
  try (AssetFileDescriptor fileDescriptor = assetManager.openFd(modelPath);
      FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor())) {
    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }
}
```

**Comment by sliu54** [comment]
I looked into the source code for `transpose.cc` and saw that the error might mean there is a mismatch between the input and output sizes. My input was a 1-D array, so I added an extra dimension and now it works. However, I'm still curious as to why the unquantized model works fine with 1-D inputs.

**Comment by pkgoogle** [comment]
Hi @arfaian, I'm reassigning to you for now. Thanks.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
