### ISSUE TITLE
How to train specific variables in SavedModel in Tensorflow format ?

### ISSUE THREAD

**Issue by adjhawar** [tensorflow/tensorflow#53372]
I have a pre-trained model in Tensorflow (not keras) format which I want to retrain .
[mobilenetv2.zip](https://github.com/tensorflow/tensorflow/files/7685965/mobilenetv2.zip)

However, in this model the list of variables is empty. The re-training needs to be done on a certain set of variables but those variables are not declared as trainable. How to access the variables from this model and make them trainable?

**Comment by sushreebarsa** [comment]
@adjhawar Could you please refer to the [SavedModel](https://www.tensorflow.org/guide/saved_model) format and let us know if it helps?Thank you!

**Comment by adjhawar** [comment]
I have tried to access the .trainable_variables and .variables attributes from the SavedModel but the lists returned from both are empty. However, I am able to run inference on the model, which implies that the variables are there in the model. 
I wanted to know if there was a way to get the list of variables.
The task I am trying to accomplish is to retrain the some part of the model and for that I require trainable_variables, but the list returned from the pre-trained SavedModel is empty

**Comment by sushreebarsa** [comment]
@adjhawar 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by adjhawar** [comment]
@sushreebarsa 
model = tf.saved_model.load("attached model")
print(model.signatures("serving_default").variables)
print(model.variables)


Print statement ----->
{}
error

**Comment by sushreebarsa** [comment]
@adjhawar 
In order to reproduce the issue reported here, could you please provide the complete code and the dataset , tensorflow version you are using. Thanks!
