### ISSUE TITLE
ValueError: Unsupported data type 14 in tensor

### ISSUE THREAD

**Issue by gaurxvreddy** [tensorflow/tensorflow#53377]
_<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>_

**System information**
- Have I written custom code : `interpreter = tf.lite.Interpreter(model_path="models/saved_model.tflite")`
- OS Platform and Distribution : **`RaspberryPi 3B+`**
- TensorFlow Git version : `v2.4.0-0-g582c8d2` 
- TensorFlow version : `2.4.0`
- Installation Source : [`https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl`](https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl)
- Python version: `Python 3.7.3`
- More Info about the **tflite** Model : Custom trained **EfficientDet-B0** on `40` classes

#### ERROR : 
```
Traceback (most recent call last):
  File "detect.py", line 8, in <module>
    interpreter = tf.lite.Interpreter(model_path="models/saved_model.tflite")
  File "/home/pi/.local/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 209, in __init__
    model_path, self._custom_op_registerers))
ValueError: Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
Unsupported data type 14 in tensor
```

> Note : If you are suggesting me to upgrade or downgrade the packages, please provide necessary code with it.

Thanks @tilakrayal !!

**Comment by tilakrayal** [comment]
@gaurxvreddy ,
Could you please update TensorFlow to the latest stable version v2.7 and let us know if you are facing the same error. Thanks!

**Comment by gaurxvreddy** [comment]
Is there `TF 2.7.0` available on Raspberry Pi, If yes, Can you provide me with the instructions to install it ?

**Comment by gaurxvreddy** [comment]
Hey @tilakrayal, 

It would be great if we could get some traction on this issue, is it possible for you to look at this?

**Comment by gaurxvreddy** [comment]
Update : Still facing the issue

**Comment by tilakrayal** [comment]
@gaurxvreddy ,
Can you please take a look at this [doc](https://www.tensorflow.org/lite/guide/build_arm) for the installation.It helps.Thanks!
