### ISSUE TITLE
How to install Tensorflow on windows for Ananconda?

### ISSUE THREAD

**Issue by SmithaShivakumar** [tensorflow/tensorflow#5337]
![image](https://cloud.githubusercontent.com/assets/12981723/19903991/c07a065c-a03e-11e6-8265-512ad1077b41.png)

**Comment by aselle** [comment]
As far as I know ( @mrry  please correct me if I'm wrong), Windows support still requires you to install manually using CMake see commint on the PR https://github.com/tensorflow/tensorflow/pull/4778.
Also see http://stackoverflow.com/questions/37522676/install-tensorflow-on-windows-with-anaconda

**Comment by mrry** [comment]
There are no binary packages for Windows (yet), so as Andrew says you'll have to build it yourself. It's currently possible to build a TensorFlow PIP package on Windows using Bazel or (if you want GPU support) CMake.

There's an example script for using Bazel on Windows [here](https://github.com/tensorflow/tensorflow/blob/816ecb7a342c25c19daa8b19627346e1fb38e56f/tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh) and instructions for using CMake on Windows [here](https://github.com/tensorflow/tensorflow/blob/816ecb7a342c25c19daa8b19627346e1fb38e56f/tensorflow/contrib/cmake/README.md).
