### ISSUE TITLE
UnsatisfiedLinkError when attempting to use HexagonDelegate

### ISSUE THREAD

**Issue by KieronQuinn** [tensorflow/tensorflow#53380]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Using example from https://www.tensorflow.org/lite/performance/hexagon_delegate
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OnePlus 7T Pro
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): `org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT` and `org.tensorflow:tensorflow-lite-hexagon:0.0.0-nightly-SNAPSHOT` with hexagon libraries `v1.20.0.1`
- Python version: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a, but the 7T Pro has a Snapdragon 855+ with a Hexagon 690

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Attempting to create `HexagonDelegate` results in a `java.lang.UnsatisfiedLinkError`

**Describe the expected behavior**

HexagonDelegate should work on the device in question

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Create a new project, and add the Java API as described here: https://www.tensorflow.org/lite/performance/hexagon_delegate#hexagon_delegate_java_api

You should end up with the three skel binaries in app/src/main/jniLibs, and the tensorflow-lite & tensorflow-lite-hexagon nightly AARs downloaded and built into the app, resulting in the following lib folder after installation:

```
OnePlus7TPro:/data/app/~~an-4OVJU49vmn0JQVRH4TQ==/<pname>-QzF_0vIwaxg6M2SwPMqdug==/lib/arm64 #
ls
libhexagon_interface.so  libhexagon_nn_skel_v65.so  libtensorflowlite_hexagon_jni.so
libhexagon_nn_skel.so    libhexagon_nn_skel_v66.so  libtensorflowlite_jni.so
```

Add code to create a HexagonDelegate, as follows:

```
try {
   HexagonDelegate(context)
}catch (e: UnsupportedOperationException){
   //Fall back to NNAPI delegate
}
```

Run the app, it will crash with an exception:

```
12-10 01:21:39.599 20658 20658 E AndroidRuntime: FATAL EXCEPTION: main
12-10 01:21:39.599 20658 20658 E AndroidRuntime: Process: <pname>, PID: 20658
12-10 01:21:39.599 20658 20658 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dlopen" referenced by "/data/app/~~an-4OVJU49vmn0JQVRH4TQ==/<pname>-QzF_0vIwaxg6M2SwPMqdug==/lib/arm64/libtensorflowlite_hexagon_jni.so"...
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at org.tensorflow.lite.HexagonDelegate.ensureNativeLibraryLoaded(HexagonDelegate.java:66)
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at org.tensorflow.lite.HexagonDelegate.<init>(HexagonDelegate.java:35)
12-10 01:21:39.599 20658 20658 E AndroidRuntime:        at <line of HexagonDelegate creation>(....kt:89)
```

As shown with the `ls` above, all the required libraries are present in that directory.

This behaviour is identical to #51872, which was closed as stale without a solution. The linked issues from the comments on that issue do not solve this problem, as for issue 1 the crash is occurring before the actual DSP check, which would be caught and handled by my sample code. Issue 2 is for Ubuntu Mobile and Python, and thus totally irrelevant.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @KieronQuinn ! Did you check with this[ threa](https://github.com/tensorflow/tensorflow/issues/36804#issuecomment-591571178)d yet?

**Comment by KieronQuinn** [comment]
> Hi @KieronQuinn ! Did you check with this[ thread](https://github.com/tensorflow/tensorflow/issues/36804#issuecomment-591571178) yet?

Yes, like I said in the issue that topic is for Python and is not relevant. I'm already using the nightly.

**Comment by mohantym** [comment]
@sachinprasadhs ! Could you please look at this issue ?

**Comment by karimnosseir** [comment]
Can you make sure that you're using the latest nightlies - may be clear the gradle cash ?

I just cloned tensorflow examples and updated image classification example to include hexagon. I followed the [guide](https://www.tensorflow.org/lite/performance/hexagon_delegate#hexagon_delegate_java_api)

by adding the gradle dep in build.gradle
```
implementation 'org.tensorflow:tensorflow-lite-hexagon:0.0.0-nightly-SNAPSHOT'
```

and created directory jniLibs/arm64-v8a and included the files i got from the libhexagon_nn_skel extraction. as explained [here](https://www.tensorflow.org/lite/performance/hexagon_delegate#add_the_shared_library_to_your_app)

Also, can you share the log ?

Thanks

**Comment by KieronQuinn** [comment]
I cleared the cache and made sure it's using the nightly, it is. 

The JNI folder (app\src\main\jniLibs\arm64-v8a) looks like this:

![image](https://user-images.githubusercontent.com/3430869/145914145-1c5e2a57-b07d-4639-9aca-973a4a039e5c.png)

And the log is in the issue but here it is again:

```
12-14 01:03:12.924  7339  7339 E AndroidRuntime: Process: <pname>, PID: 7339
12-14 01:03:12.924  7339  7339 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dlopen" referenced by "/data/app/~~uTBWoFr6BqliVZ652EhEiQ==/<pname>-h930g9ig2G8v9bcinuLslg==/lib/arm64/libtensorflowlite_hexagon_jni.so"...
12-14 01:03:12.924  7339  7339 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
12-14 01:03:12.924  7339  7339 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
12-14 01:03:12.924  7339  7339 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
12-14 01:03:12.924  7339  7339 E AndroidRuntime:        at org.tensorflow.lite.HexagonDelegate.ensureNativeLibraryLoaded(HexagonDelegate.java:66)
12-14 01:03:12.924  7339  7339 E AndroidRuntime:        at org.tensorflow.lite.HexagonDelegate.<init>(HexagonDelegate.java:35)
```

**Comment by karimnosseir** [comment]
Can you provide all the information about the ndk and api version you are using and android version too.

Thanks

**Comment by KieronQuinn** [comment]
I'm not using the NDK in this project as I'm using the prebuilts - if that's incorrect please let me know as the guide does not mention the NDK. 

API wise I'm targeting 31, and the phone is running Android 11 (30)

**Comment by karimnosseir** [comment]
I just tried our image classification [example](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android) and added code to use hexagon delegate.

To make sure we have similar setup, can you share your project, or try from the example as i mentioned earlier.

If you don't want to share here, you can send it to me on email - same name as here at google dot com

Thanks

**Comment by KieronQuinn** [comment]
I've uploaded and shared with your email on Google Drive my project setup, as well as a precompiled APK. I'll have a look at the example too, see if I can reproduce it on that also, thanks.

**Comment by KieronQuinn** [comment]
Update on the above, by using the example, adding the hexagon gradle dependency and the libs and changing the code using

```
tfliteOptions.addDelegate(new HexagonDelegate(activity));
```

at line 225 of Classifier.java, the same exception happens with my config. Could I possibly be missing a step somewhere?

**Comment by karimnosseir** [comment]
Thanks. Can you share the example project you updated  - it will be easier to look into it.

Thanks

**Comment by KieronQuinn** [comment]
Absolutely, here you go: https://drive.google.com/file/d/1vs3ghix6SzL9CG6EtbERY5VKZSzSHdbC/view?usp=sharing

**Comment by KieronQuinn** [comment]
Thanks for the updated example code with the fix, unfortunately it doesn't help my original project.

Started by running a comparison between the before and after example to identify what had been changed, to try to replicate it in my own project, nothing really jumped out other than updating gradle (which I've done - no change), and adding Sonatype to the sources (again, no change).

I've copied all the dependency lines from the gradle again, made sure all the libs are correct (even copying the known-working libs from the fixed example), I've even decompiled the resulting APK and replaced the libs to no avail, always the same crash. 

I think I may just give up on using Hexagon entirely and just use NNAPI as Hexagon seems to have very limited support (it doesn't work on my OnePlus 7T Pro even with selinux disabled for example)

**Comment by deanh-sr** [comment]
I've encountered what appears to be this exact issue on my own project.  I'm trying to use the hexagon delegate on a Samsung Galaxy Tab S7 (snapdragon 865) and when I load the delegate I encounter a runtime crash with the same exception and identical stack trace as reported in this issue above.  From my program:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.legonetandroid, PID: 30171
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "dlopen" referenced by "/data/app/~~dVPIFpHRrBcjznj_lAHvhA==/com.example.legonetandroid-zcRv5ajrqr355wCmT88zeA==/base.apk!/lib/arm64-v8a/libtensorflowlite_hexagon_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at org.tensorflow.lite.HexagonDelegate.ensureNativeLibraryLoaded(HexagonDelegate.java:66)
        at org.tensorflow.lite.HexagonDelegate.<init>(HexagonDelegate.java:35)
```

I attempted to reproduce the issue using the tensorflow image classification example (modified to use the hexagon delegate), and I encounter the same runtime crash as I do on my own project.

> Thanks for the updated example code with the fix, unfortunately it doesn't help my original project.

@karimnosseir or @KieronQuinn , could you please post the example code fix mentioned above for the benefit of the community?  While it appears to not have been helpful for the original poster, perhaps it will be helpful for others.

**Comment by KieronQuinn** [comment]
Absolutely, here you go, this is the example @karimnosseir sent to me. https://drive.google.com/file/d/1ZY6Ku9VE10Qt-eeLgAtk7aiGSzRbWGqw/view?usp=sharing

As I said above, I was unable to solve the issue on my project, and ended up scrapping Hexagon support. If you get yours working, please let me know how so I can see if the same works for me!

**Comment by deanh-sr** [comment]
Thank you @KieronQuinn !

**Comment by karimnosseir** [comment]
@deanh-sr Please let us know if you have any questions. 
Thanks @KieronQuinn for sharing.
I am sorry the example wasn't enough to know what's the problem in your case.

Thanks

**Comment by deanh-sr** [comment]
I'm currently using the fixed version of the image classification example provided by @KieronQuinn above, and it doesn't appear to actually work correctly for me.  On the app GUI I am able to select the HEXAGON device, and it appears to continue classifying.  However, if I inspect the run logs I find the following:
```
D/tensorflow: CameraActivity: Updating  device: HEXAGON
D/tensorflow: ClassifierActivity: Closing classifier.
D/tensorflow: ClassifierActivity: Creating classifier (model=QUANTIZED_EFFICIENTNET, device=HEXAGON, numThreads=1)
E/tflite: Failed to load libhexagon_interface.so, Error: dlopen failed: library "libadsprpc.so" not found: needed by /data/app/~~HRSw6P2_Mad6sIxoxJc_5Q==/org.tensorflow.lite.examples.classification-fjRemGNRXWPUEZgIsd26Pg==/lib/arm64/libhexagon_interface.so in namespace classloader-namespace
I/tflite: Hexagon Delegate is not supported.
D/ClassifierWithSupport: Hexagon delegate is not supported on this device.
D/ClassifierWithSupport: Created a Tensorflow Lite Image Classifier.
```
It looks like loading the hexagon delegate failed, but classification continued using another mechanism?  In any case, it's a quiet failure, but appears to fail to load the hexagon delegate.

I was able to address the specific error by providing the missing library file libadsprpc.so (from the Qualcomm Hexagon SDK), however now I see the following message instead:
```
D/tensorflow: CameraActivity: Updating  device: HEXAGON
V/ClassifierWithSupport: Timecost to load the image: 3
V/ClassifierWithSupport: Timecost to run model inference: 12
D/tensorflow: ClassifierActivity: Closing classifier.
D/tensorflow: ClassifierActivity: Creating classifier (model=QUANTIZED_EFFICIENTNET, device=HEXAGON, numThreads=1)
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.
D/ClassifierWithSupport: Hexagon delegate is not supported on this device.
D/ClassifierWithSupport: Created a Tensorflow Lite Image Classifier.
```
Again, this is a quiet failure and from the app it appears that classifications continued.

It's not clear to me what's missing at this point.  I haven't changed the build.gradle file or the hexagon library files that were included in the project, so I'm doubtful that the problem is indeed due to incompatible versions.

@karimnosseir or @KieronQuinn , are you certain that this updated example app was loading the hexagon delegate correctly in your testing?  Is it possible that it was failing quietly for you as well?

**Comment by deanh-sr** [comment]
Thanks for the speedy reply @karimnosseir !

> This is an OS provided library, you should not add this library. 

Ok, good to know.  I checked the device file system, and the library does exist under /system/vendor/lib.  So I'm not sure why it isn't found correctly, I'll have to figure that out.

> What device are you using ? are you sure it has supported QC SoC ?

The device is a Samsung Galaxy Tab S7, which has a Qualcomm 865+ (Hexagon 698).  It is not explicitly listed as a supported device, however I believed it would be supported based on this thread: https://github.com/tensorflow/tensorflow/issues/39035
Is there a way to determine explicitly if a device is supported?  Alternatively, do you know if this device is or is not supported?

> Please re-download the libhexagon latest version and use them with the nightly to make sure you are using compatible

Ok, I re-downloaded hexagon_nn_skel_v1.20.0.1.  The lib_support build.gradle is configured to use the TensorFlow Lite nightly snapshots:
```
    // Build off of nightly TensorFlow Lite
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-hexagon:0.0.0-nightly-SNAPSHOT'

    implementation 'org.tensorflow:tensorflow-lite-support:0.3.0'
```
(I also tried using the nightly snapshot for tensorflow-lite-support)

I still get the same error.

> Re "are you certain that this updated example app was loading the hexagon delegate correctly in your testing"
Yes

Ok, thank you for confirming.  Just wanted to check as the failure was not immediately obvious on my device.

**Comment by karimnosseir** [comment]
Can you run these commands with the device plugged in

```
adb shell cat /proc/cpuinfo | grep Hardware
adb shell cat /sys/devices/soc0/soc_id
adb shell cat /sys/devices/system/soc/soc0/id
```

**Comment by deanh-sr** [comment]
```
gts7lwifi:/ $ cat /proc/cpuinfo | grep Hardware
Hardware        : Qualcomm Technologies, Inc KONA
gts7lwifi:/ $ cat /sys/devices/soc0/soc_id
356
gts7lwifi:/ $ cat /sys/devices/system/soc/soc0/id
cat: /sys/devices/system/soc/soc0/id: No such file or directory
```
I checked the full output of `cat /proc/cpuinfo` and there wasn't anything on the next line.

**Comment by karimnosseir** [comment]
Thanks for sharing the info. This SoC should be supported by the delegate.

Can you try the [benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) tool and share the log and commands used.

**Comment by karimnosseir** [comment]
A fix for this issue has been sent and should be available now in the latest nightly.
