### ISSUE TITLE
I think nvidia-driver is not working.

### ISSUE THREAD

**Issue by Sameerbobde** [tensorflow/tensorflow#53383]
I think nvidia-driver is not working.

You have to check command `nvidia-smi` 

If these command is not working, you have reboot your computer.

Maybe `nvidia-smi` works correctly.

_Originally posted by @SnowMasaya in https://github.com/tensorflow/tensorflow/issues/255#issuecomment-384846967_

**Comment by mohantym** [comment]
Hi @Sameerbobde ! 
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by Sameerbobde** [comment]
bash: /usr/bin/nvidia-smi: No such file or directory
i have install nvidia-cuda-toolkit but that it is not showing

**Comment by mohantym** [comment]
Hi @Sameerbobde ! Could you try again after pointing your file from Cuda installation location through [environment variable ](https://www.tensorflow.org/install/gpu#linux_setup). Thanks!
