### ISSUE TITLE
Perspective transformation data augmentation for object detection

### ISSUE THREAD

**Issue by MostafaFiroozi** [tensorflow/tensorflow#53384]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version :2.7.0
- Are you willing to contribute it 🆗 

**Perspective transformation data augmentation for object detection.**

**Will this change the current api? How? No, the change will be done only in the preprocessing layer.

**Who will benefit with this feature? As it has been described in [this article](https://ieeexplore.ieee.org/abstract/document/8943416), this feature could be helpful to make the models more general in the object detection projects.

**Comment by Saduf2019** [comment]
@MostafaFiroozi 
Please share your details in issue template for us to understand the issue faced. if possible share the URL where you request the change.

**Comment by MostafaFiroozi** [comment]
In object detection projects for the sake of more robust models we need some data augmentation. In the  [preprocessor.py](https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py)
there are some possible functions that can be used in the pipeline config of a TensorFlow model to act as a data-augmentations tool.
![image](https://user-images.githubusercontent.com/73081215/145672704-d7bf2368-1e78-49a3-af0a-2da0e8354560.png)
However, there is no technique for perspective transformation data augmentation for object detection. While, as it has been investigated in [this article](https://ieeexplore.ieee.org/abstract/document/8943416), this also could be good practice for data augmentation.
I wanted to ask to add this function also to [preprocessor.py](https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py).
Hope this will clarify the matter
Regards,

**Comment by bhack** [comment]
Take a look at https://github.com/keras-team/keras-cv/issues/333

**Comment by gowthamkpr** [comment]
@MostafaFiroozi Can you please close this issue as it is already being discussed [here](https://github.com/keras-team/keras-cv/issues/333). Please follow the  issue for updates. Thanks!

**Comment by MostafaFiroozi** [comment]
Thanks, I guess the discussion is what I was searching for. I close the issue. Regards,
