### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'predict_classes'

### ISSUE THREAD

**Issue by aritraMandal02** [tensorflow/tensorflow#53391]
```
seed_text = "I've got a bad feeling about this"
next_words = 100
  
for _ in range(next_words):
	token_list = tokenizer.texts_to_sequences([seed_text])[0]
	token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
	predicted = model.predict_classes(token_list, verbose=0)
	output_word = ""
	for word, index in tokenizer.word_index.items():
		if index == predicted:
			output_word = word
			break
	seed_text += " " + output_word
print(seed_text)
```

This codeblock is giving me the error shown below:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-52-70399a5f93d3> in <module>()
      5         token_list = tokenizer.texts_to_sequences([seed_text])[0]
      6         token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
----> 7         predicted = model.predict_classes(token_list, verbose=0)
      8         output_word = ""
      9         for word, index in tokenizer.word_index.items():

AttributeError: 'Sequential' object has no attribute 'predict_classes'
```

How can I solve this error? Please help.

Here is the link of the full code:
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDVSTGdJczNoa2ZBeXpObWxobGJldGd5Q2pLd3xBQ3Jtc0trSVRobkVBM2EtV3lTajlQNzhXbEhGTjN3WXhFTGo3d1U4b3h1Rjl4Rk9ubUVVWG95cUNfaWFoTHpmRlpEM1VmM2NrOXFqc21WYkRKZ0c3WWgtcE5VRV9kZF9pZDZMUDVmWnRtNUtMS3NzUnZodFB3RQ&q=https%3A%2F%2Fgoo.gle%2F3aSTLGx

**Comment by sushreebarsa** [comment]
@aritraMandal02 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by aritraMandal02** [comment]
I used keras issue template.

**Comment by sushreebarsa** [comment]
@aritraMandal02 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by aritraMandal02** [comment]
Okay posted there.

**Comment by sushreebarsa** [comment]
@aritraMandal02 Thank you for confirming ! Could you please move this issue to closed status as we will track the other one in [keras-team/keras repo](https://github.com/keras-team/keras/issues). Thanks!

**Comment by aritraMandal02** [comment]
Okay done. Thank you for helping
