### ISSUE TITLE
To support casting int32 in HEX format 

### ISSUE THREAD

**Issue by khatrishubham88** [tensorflow/tensorflow#53398]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.x
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**
I want something like hex_tensor = tf.cast(int32_tensor, dtype=tf.hex) which allows me to get the hex value representation and can be used for further computation. This becomes relevant for several data where label information is in hex colours while the label images are in PNG (RGB) format. It is one of the basic op in python [Python hex](https://docs.python.org/3/library/functions.html#hex).

**Will this change the current api? How?**
No, extends the functionality.

**Who will benefit with this feature?**
Any tensor op that needs to work with hex values, o

**Any Other info.**
Same as #30493 seems it is closed before finishing.

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this feature request?

**Comment by Saduf2019** [comment]
@khatrishubham88 
Please feel free to submit a PR for the requested change.

**Comment by khatrishubham88** [comment]
@Saduf2019 can you point me to the right module to start?

**Comment by khatrishubham88** [comment]
@Saduf2019 :bump:

**Comment by sachinprasadhs** [comment]
@khatrishubham88 , You can refer [this](https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/python/ops/math_ops.py#L938-L1007) code to start with  `tf.cast`.

**Comment by khatrishubham88** [comment]
The issue is being worked on

**Comment by sachinprasadhs** [comment]
Could you please mention the PR which is linked to the issue.

**Comment by sagarchapara** [comment]
@sachinprasadhs I would like to contribute to this.

**Comment by sagarchapara** [comment]
@sachinprasadhs I would like to contribute to this, any references on how to add a new type

**Comment by LawJarp-A** [comment]
Hey! Can I take up this issue? I'm looking to make my first OS contribution to Tensorflow

**Comment by Siddharth220903** [comment]
Hi! is this issue open up as I need to start with my first contribution?

**Comment by sachinprasadhs** [comment]
Feel free to contribute.
> Hi! is this issue open up as I need to start with my first contribution?

**Comment by LawJarp-A** [comment]
@sachinprasadhs  I traced the implementation to these kernels [cast_op.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cast_op.h), [cast_op_impl.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cast_op_impl.h), [cast_op.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cast_op.cc). I'm not very sure how to proceed next. Some guidance would be appreciated

**Comment by Shreyas-SAS** [comment]
@sachinprasadhs I will be working on this issue. Please assign it to me.

**Comment by khanxbahria** [comment]
It seems like the OP is asking for casting to hex merely for the representation of tensors.
This could already be achieved using numpy's `set_printoptions` method:
```py
import numpy as np
import tensorflow as tf

np.set_printoptions(formatter={'int':hex})

tensor = tf.constant( [15], tf.int32 )
print(tensor)  # tf.Tensor([0xf], shape=(1,), dtype=int32)
```
@sachinprasadhs Adding a new hex datatype solely for the representation might bloat the library.

**Comment by khatrishubham88** [comment]
Hi @khanxbahria,

The ask was to have the representation available at the train time such that dataset class can perform the transformation on the device. This is not solely for representation but also for training and evaluation.

**Comment by khatrishubham88** [comment]
Apologies for closing it by mistake

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
