### ISSUE TITLE
exit code 409 when trying to run through tensorflow example in pycharm

### ISSUE THREAD

**Issue by skywo1f** [tensorflow/tensorflow#53392]
I am trying to go through the DCGAN example on the tensorflow website https://www.tensorflow.org/tutorials/generative/dcgan. it seems to run fine up until the step where it uses the generator generated_image = generator(noise, training=False). At that point it exits with error code Process finished with exit code -1073740791 (0xC0000409).

I am running on Windows 10 using pycharm. I have tried messing with the batch size in case this is a memory issue, but even setting it to 1 gives the same results. I have also tried running pycharm as administrator.

**Comment by Saduf2019** [comment]
@skywo1f 
Can you please try on colab and see if you face the same issue, you use gpu option aswell.

**Comment by skywo1f** [comment]
I am using the gpu option, I installed cuda/cudnn/drivers and made sure that tensorflow did not throw any errors with regards to that. Running the code on google's colab does not replicate the error

**Comment by skywo1f** [comment]
pycharm defaults to python 3.9. is it possible that tensorflow is not compatible with python 3.9?

**Comment by Saduf2019** [comment]
@skywo1f 
Could you downgrade to 3.7/3.8 and see if you still face the issue. you may refer to similar compatibility issues.
#51573,#44485
As explained earlier unless we have all the required information we cannot help you, you may open this issue with pycharm or at the discussion forum.
