### ISSUE TITLE
Can't run inference with YAMNET based model that's been converted to TFLite

### ISSUE THREAD

**Issue by p30arena** [tensorflow/tensorflow#53393]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes and No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: Not a Mobile Device
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.8.5
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: using CPU
- GPU model and memory: using CPU

**Describe the current behavior**
I used [this tutorial](https://www.tensorflow.org/tutorials/audio/transfer_learning_audio) to train a model.
Then I combined the classification model and YAMNet model using the instructions in the tutorial.
Next, I converted the model to TFLite using int8 quantization.
The first problem I faced was that the input shape of YAMNet is variable and the TFLite model's shape is now 1.
![image](https://user-images.githubusercontent.com/1261332/145704398-248d5793-8441-4a4c-a4c5-08c1286474d8.png)

So I had to resize the input to accept 16k audio samples.

```
model.resize_tensor_input(
    input_details[0]['index'], (16000,))
```

But then I encountered another error I couldn't fix:

**Pad value has to be greater than equal to 0.Node number 17 (PAD) failed to invoke.**

**Standalone code to reproduce the issue**

```
import numpy as np
import tensorflow as tf

from yamnet_commons import filenames, model_path, load_wav_for_map, AUTOTUNE, commands

files_ds = tf.data.Dataset.from_tensor_slices(filenames)
files_ds = files_ds.map(load_wav_for_map, num_parallel_calls=AUTOTUNE)
files_ds = files_ds.cache()

model = tf.lite.Interpreter(str(model_path.joinpath('./model.tflite')))
input_details = model.get_input_details()
output_details = model.get_output_details()

model.resize_tensor_input(
    input_details[0]['index'], (16000,))

model.allocate_tensors()

results = {}

for frame_data, lbl_idx in files_ds:
    lbl_idx = lbl_idx.numpy()
    model.set_tensor(input_details[0]['index'],
                     tf.cast(frame_data * 255 - 128, tf.int8))
    model.invoke()
    prediction = model.get_tensor(output_details[0]['index'])
    print(prediction)
    sm = tf.nn.softmax(prediction.astype(np.float) / 128)
    idx = np.argmax(sm)

    if lbl_idx not in results:
        results[lbl_idx] = {
            'n_total': 0,
            'n_ok': 0
        }

    results[lbl_idx]['n_total'] += 1
    if idx == lbl_idx:
        results[lbl_idx]['n_ok'] += 1


print(results)

for lbl, v in results.items():
    print("{0} accuracy: {1}".format(commands[lbl], v['n_ok']/v['n_total']))
```

**Comment by p30arena** [comment]
I've seen a similar issue #10235 but I've no idea how to fix mine.

**Comment by p30arena** [comment]
I resized to 15600 and the error is gone.
But faced a new Error:

**RuntimeError: tensorflow/lite/kernels/complex_support.cc:43 output->type != kTfLiteFloat32 (INT8 != FLOAT32)Node number 46 (COMPLEX_ABS) failed to prepare.**

seems that TFLite doesn't support complex and can't generate spectrogram using it.

**Comment by sachinprasadhs** [comment]
You need to provide input as float32, it is failing in the code check [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv.cc#L458).

**Comment by p30arena** [comment]
> You need to provide input as float32, it is failing in the code check [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv.cc#L458). Also, refer [this](https://stackoverflow.com/questions/63806975/get-fully-qunatized-tflite-model-also-with-in-and-output-on-int8) issue for int8 and uint8 input and output.

I had no problem converting other models to a fully quantized model.
But YAMNET is a pain.

It seems that there are OPs not supported by TFLite or some OPs cannot be fully quantized?!

**Comment by sachinprasadhs** [comment]
Yes, all the OPs can not be quantized since those Ops don't have TFLite equivalents. You can check the ops_compatibility [here](https://www.tensorflow.org/lite/guide/ops_compatibility). 
Also, check our [roadmap](https://www.tensorflow.org/lite/guide/roadmap#optimization) on tflite.

**Comment by p30arena** [comment]
@sachinprasadhs 
Thank You
