### ISSUE TITLE
tf.reduce_logsumexp throws exception when reducing over RaggedTensor

### ISSUE THREAD

**Issue by abhmul** [tensorflow/tensorflow#53399]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **Ubuntu 18.04.6 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.7.0-rc1-69-gc256c071bb2 2.7.0**
- Python version: **Python 3.9.0**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**: When reducing over a ragged dimension, `tf.reduce_logsumexp` throws a `ValueError: TypeError: object of type 'RaggedTensor' has no len()`.

**Describe the expected behavior**: When reducing over a ragged dimension, `tf.reduce_logsumexp` should successfully reduce and return a non-ragged tensor. This matches the behavior of other reduce operations like `tf.reduce_sum` or `tf.reduce_max`/

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): **no**
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**:
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

a = tf.ragged.constant([[0, 0, 0], [0, 0]], dtype=tf.float32)
a.shape  # TensorShape([2, None])
tf.reduce_sum(a, axis=1)
# >>> <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>
tf.reduce_logsumexp(a, axis=1)  
# >>> ValueError: TypeError: object of type 'RaggedTensor' has no len()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This same error shows up when you try to transpose a ragged tensor.

A simple workaround:
```python
a_max = tf.reduce_max(a, axis=1, keepdims=True)
tf.math.log(tf.math.reduce_sum(tf.math.exp(a - a_max), axis=1)) + a_max
# >>> <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.0986123, 0.6931472], dtype=float32)>
```
```

**Comment by tilakrayal** [comment]
@abhmul ,
Can you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/45569#issuecomment-744527190) from the issue with similar error.It helps.Thanks!

**Comment by abhmul** [comment]
@tilakrayal Thanks for linking. That comment has a good workaround as well. It looks like the issue was fixed on tf-nightly so I'll go ahead and close.
