### ISSUE TITLE
Cuda 10.2 compatible with which tensorlow-gpu version?

### ISSUE THREAD

**Issue by pn12** [tensorflow/tensorflow#53390]
I am getting error while importing tensorflow where it is looking cuda 11.0 version, I have cuda with 10.2, unable to find compatible TF version with 10.2.

Can anyone confirm the TF version ?

**Comment by Saduf2019** [comment]
@pn12 
We see that you have not mentioned the tf version used, please use issue template a sit helps us help you.
Please refer to this link to use the [correct compatibility](https://www.tensorflow.org/install/source_windows#gpu).

**Comment by pn12** [comment]
@Saduf2019 - It's resolved now, there was a version compatibility issue among cuda , tf , cudnn.
Thanks.
