### ISSUE TITLE
tf.sparse.sparse_dense_matmul vs tf.matmul has numerical error

### ISSUE THREAD

**Issue by jocampo2** [tensorflow/tensorflow#53395]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: MacOs Cataline 10.15.7
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tested with 2.4.1, 2.6.0 2.7.0
- Python version: 3.7.12
- CUDA/cuDNN version: Used cpu
- GPU model and memory:

**Bug**

Numerical errors appear when using `tf.sparse.sparse_dense_matmul` compared to `tf.matmul`. This happens when the number of sparse elements becomes large ~100. Code to reproduce:

```
d = 10
matrix = tf.reshape(tf.linspace(0.,1.,d*d), [d,d])
sparse_matrix = tf.sparse.from_dense(matrix)

x = tf.reshape(tf.linspace(0.,1.,d), [d,1])

y = tf.matmul(matrix,x)
sy = tf.sparse.sparse_dense_matmul(sparse_matrix,x)

error = tf.reduce_mean(tf.abs(y-sy))
=> error = 1e-8
```

Couldn't seem to find this issue anywhere apart from [here](https://www.gitclear.com/open_repos/tensorflow/tensorflow/release/v2.5.0-rc2), where they mention that there is truly random noise when using tf.sparse.sparse_dense_matmul using GPU. But it seems like here it also appears with CPU

**Comment by Saduf2019** [comment]
@jocampo2 
Please refer to [the gist](https://colab.research.google.com/gist/Saduf2019/78cdd298fd13ee3e3d8518b087acb202/untitled652.ipynb) attached for tf 2.7

**Comment by jocampo2** [comment]
anyone?
