### ISSUE TITLE
Tuner tutorial rebuilds model rather than saving it

### ISSUE THREAD

**Issue by dansbecker** [tensorflow/tensorflow#53408]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/keras/keras_tuner

## Description of issue (what needs changing):
The bottom of this tutorial says `Re-instantiate the hypermodel and train it with the optimal number of epochs from above.` But there's no reason to train the model twice when you could use the callback to save the model at the best epoch. I and others have speculated [here](https://twitter.com/HamelHusain/status/1470492047404580865) that the call to re-train the model is supposed to be on the full data (with no validation split). If that's the intention, the resulting change would be to remove `validation_split=0.2` from the final `fit` call.

Otherwise, it seems you should add a `ModelCheckpoint` callback to the save the best model when you first fit the model... and then not refit the model.

**Comment by tilakrayal** [comment]
@dansbecker ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by dansbecker** [comment]
Thanks @tilakrayal . I've submitted [the issue there](https://github.com/keras-team/keras/issues/15789). I'll leave it to you to decide if this issue should be closed.

**Comment by tilakrayal** [comment]
@dansbecker ,
Please feel free to move this issue to closed status as it has been tracking in Keras repo.Thanks!
