### ISSUE TITLE
Rename argument names in tf.train.exponential_decay()

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#5340]
The current function signature reads: 

```python
tf.train.exponential_decay(learning_rate, global_step, decay_steps, decay_rate, staircase=False, name=None)
```

When passing the parameters by keyword name (for example after reading a configuration file), it's pretty weird that the first parameter is called `learning_rate` since the function can be used for other decaying parameters as well.

A better name would be `initial_value`.

**Comment by aselle** [comment]
@martinwicke, who would be good for this. It seems close to the argument ordering work you were telling me about yesterday.

**Comment by martinwicke** [comment]
It would be lovely to change that, I agree. I am not sure that we'll get to it -- we're accumulating work fast, and this seems to be a slightly lesser problem than the others.

**Comment by martinwicke** [comment]
We did not get to this before 1.0 and now it's too late. It's not a terrible bug, so I'll close this.

**Comment by danijar** [comment]
Taking about cleaning up the API, an exponential decay op should also not live in `tf.train`. Maybe worth cleaning up and reorganizing some ops for TF 2.0?

**Comment by jonasrauber** [comment]
Why not create a new exponential_decay function with the correct argument names and at the correct location now, and leave the current one for compatibility? This would be a non-breaking change that would solve this issue.

**Comment by danijar** [comment]
Yeah I should do that.

**Comment by martinwicke** [comment]
We are working on cleaning up the API, this could be one of the things we do (make an alias and soft-deprecate the old form).

@aselle FYI
