### ISSUE TITLE
When I use   tensorflow_lite(1.13.1) it has report error  it looks ...

### ISSUE THREAD

**Issue by csdf-ssm** [tensorflow/tensorflow#53402]
error tip : Model provided has model identifier 'AFRG', should be 'TFL3'

I have model.tflite when I creat     
model = tflite::FlatBufferModel::BuildFromBuffer(newmodel_data, modellength);

How Can I do?

**Comment by tilakrayal** [comment]
@csdf-ssm ,
We see that you are using tf version 1.13, 1.x is not actively supported, please update to 2.x and let us know if you are using same issue.

**Comment by csdf-ssm** [comment]
I had download  tensorflow.git and use demo in /tensorflow/tensorflow/lite/examples/ios/camera  directory ,run pod and it pod.lock 
PODS:
  - TensorFlowLite (1.13.1)

DEPENDENCIES:
  - TensorFlowLite (= 1.13.1)

SPEC REPOS:
  trunk:
    - TensorFlowLite

SPEC CHECKSUMS:
  TensorFlowLite: 8b9dc4eb32eac0f8cb660c66bca7604da56dcc5a

PODFILE CHECKSUM: 1f44a2ab814725d3675508d4a66a5efdb4140d58

COCOAPODS: 1.11.2


then  I   check my pods version and  it shows last version is 1.13.1 
-> TensorFlowLite (1.13.1)
   TensorFlow Lite
   pod 'TensorFlowLite', '~> 1.13.1'
   - Homepage: https://www.tensorflow.org/lite/
   - Source:  
   https://dl.google.com/dl/cpdc/a3cc8a8fb2aec8f6/TensorFlowLite-1.13.1.tar.gz
   - Versions: 1.13.1, 1.12.0, 1.11.0, 1.10.1, 1.10.0, 1.9.0, 0.1.7, 0.0.3,
   0.0.2 [master repo]

**Comment by csdf-ssm** [comment]
> @csdf-ssm , We see that you are using tf version 1.13, 1.x is not actively supported, please update to latest stable tf v2.7 and let us know if you are using same issue.

to  reply  =========================


I had download tensorflow.git and use demo in /tensorflow/tensorflow/lite/examples/ios/camera directory ,run pod and it pod.lock
PODS:

TensorFlowLite (1.13.1)
DEPENDENCIES:

TensorFlowLite (= 1.13.1)
SPEC REPOS:
trunk:
- TensorFlowLite

SPEC CHECKSUMS:
TensorFlowLite: 8b9dc4eb32eac0f8cb660c66bca7604da56dcc5a

PODFILE CHECKSUM: 1f44a2ab814725d3675508d4a66a5efdb4140d58

COCOAPODS: 1.11.2

then I check my pods version and it shows last version is 1.13.1
-> TensorFlowLite (1.13.1)
TensorFlow Lite
pod 'TensorFlowLite', '~> 1.13.1'

Homepage: https://www.tensorflow.org/lite/
Source:
https://dl.google.com/dl/cpdc/a3cc8a8fb2aec8f6/TensorFlowLite-1.13.1.tar.gz
Versions: 1.13.1, 1.12.0, 1.11.0, 1.10.1, 1.10.0, 1.9.0, 0.1.7, 0.0.3,
0.0.2 [master repo]

**Comment by csdf-ssm** [comment]
@tilakrayal

**Comment by csdf-ssm** [comment]
> @csdf-ssm , We see that you are using tf version 1.13, 1.x is not actively supported, please update to latest stable tf v2.7 and let us know if you are using same issue.

@tilakrayal   
I had download tensorflow.git and use demo in /tensorflow/tensorflow/lite/examples/ios/camera directory ,run pod and it pod.lock
PODS:

TensorFlowLite (1.13.1)
DEPENDENCIES:

TensorFlowLite (= 1.13.1)
SPEC REPOS:
trunk:
- TensorFlowLite

SPEC CHECKSUMS:
TensorFlowLite: 8b9dc4eb32eac0f8cb660c66bca7604da56dcc5a

PODFILE CHECKSUM: 1f44a2ab814725d3675508d4a66a5efdb4140d58

COCOAPODS: 1.11.2

then I check my pods version and it shows last version is 1.13.1
-> TensorFlowLite (1.13.1)
TensorFlow Lite
pod 'TensorFlowLite', '~> 1.13.1'

Homepage: https://www.tensorflow.org/lite/
Source:
https://dl.google.com/dl/cpdc/a3cc8a8fb2aec8f6/TensorFlowLite-1.13.1.tar.gz
Versions: 1.13.1, 1.12.0, 1.11.0, 1.10.1, 1.10.0, 1.9.0, 0.1.7, 0.0.3,
0.0.2 [master repo]

**Comment by csdf-ssm** [comment]
@tilakrayal  and I also download tensorflowSwift demo  ImageClassification run success  but

**Comment by tilakrayal** [comment]
@csdf-ssm ,
As commented tf v1.x is not supported  actively, please update to 2.x and let us know if you are using same issue.Thanks
