### ISSUE TITLE
00M report after I upgrade tensorflow for tf2.5 to tf2.7

### ISSUE THREAD

**Issue by wangwei-cmd** [tensorflow/tensorflow#53400]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): tf2.5 and tf 2.7
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  CUDA11.2.2/cudnn8.1.0.77 for both tf2.5 and tf2.7 
- GPU model and memory: NVIDIA RTX A6000, 43660 MB memory

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I upgrade tensorflow from version 2.5 to 2.7. The code that can run in tf2.5 enviroment cannot run in tf2.7 enviroment since when run in tf2.7, the GPU memory exhaust.
**Describe the expected behavior**
The code can also run in tf2.7 without reporting OOM happens.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
The link of code script is here   [https://colab.research.google.com/drive/1zb_SAqKZPGinzdWWl5CUySwzX5T_CatU?usp=sharing](url). It cannot reporduce the isuue in colab since the code needs about 50G RAM memory.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
2021-12-13 13:04:10.364463: W tensorflow/core/common_runtime/bfc_allocator.cc:474] *************************************************************************************************___
2021-12-13 13:04:10.364557: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at gather_nd_op.cc:47 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[772,753,768,1,1] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 220, in <module>
    train(epoch, batch, iternum, restore=0,
  File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 210, in train
    hist = Model.fit(x, y, batch_size=batch, epochs=epoch, validation_split=0.1,
  File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[772,753,768,1,1] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node GatherNd_35
 (defined at /media/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/fan_radon_iradon_line.py:8)
]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_12544]

Errors may have originated from an input operation.
Input Source operations connected to node GatherNd_35:
In[0] mul_129:
In[1] GatherNd_5/indices:

Operation defined at: (most recent call last)
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 220, in <module>
>>>     train(epoch, batch, iternum, restore=0,
>>> 
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 210, in train
>>>     hist = Model.fit(x, y, batch_size=batch, epochs=epoch, validation_split=0.1,
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/engine/training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/engine/training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/engine/training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/engine/training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 109, in train_step
>>>     predictions = self(x, training=1)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "/home/wangwei/.conda/envs/tf2.7/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 98, in call
>>>     for i in range(1, len(self.oneiterstack) - 1):
>>> 
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 102, in call
>>>     Au = self.radon(u)
>>> 
>>>   File "/home/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/incomplete_2_parker_line_150.py", line 82, in radon
>>>     self.w11,self.w12,self.w21,self.w22,u)
>>> 
>>>   File "/media/wangwei/T7/GitLab/incomplete-CT/fan-beam/fan_line_parker/fan_radon_iradon_line.py", line 8, in radon_fan_line
>>>     pf = tf.gather_nd(f * 1.0, ind11) * w11 + \
>>> 

Function call stack:
train_function -> call

**Comment by sushreebarsa** [comment]
@wangwei-cmd 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by wangwei-cmd** [comment]
@sushreebarsa 
The code script is here [https://github.com/tensorflow/tensorflow/issues/url](url). It cannot reporduce the isuue in colab since the code needs about 50G RAM memory and colab only give me 12.69G . Besides, colab doesn't has the RTX A6000.

When debugging the code, I found a strange phenomenon. When the number (not batch size) of training samples is small, the code can successfully run in tf 2.7, but when the number become large, 00M error was raised. 
For example, when the shapes of img_label and img_ini in the code script  are [10, 512, 512, 1] and the shapes of  sin_label and sin_ini are [10, 753, 768, 1], the script can run in tf2.7. But when the number becomes 1000 ([1000, 512, 512, 1] and  [1000, 753, 768, 1]),  00M error was thrown.
In tf2.5, no matter the number is 10 or 1000, the code can run.

**Comment by sushreebarsa** [comment]
@wangwei-cmd In the above [comment](https://github.com/tensorflow/tensorflow/issues/53400#issuecomment-992187042) could you please check  code [script URL](https://github.com/tensorflow/tensorflow/issues/url) and provide the correct one?Thanks!

**Comment by jostheim** [comment]
i have the same issue.  model trains on 2.5.2, and fails on 2.6.2 and 2.7 latest.  same cuda and drivers for all.  something is eating a lot more memory in post 2.5.2 releases.

**Comment by jostheim** [comment]
For future lookers, you can fix the issue of OOM with > 2.5 versions by using tf.dataset, it is the only way to pass data to fit and have it not run out of memory.  I was using numpy in memory arrays and fit failed for oom, using tf.dataset from_generator I no longer fail.  I don't know why and this seems like a significant bug, but this is the fix.
