### ISSUE TITLE
TFLite GPU failed to delegate with ssd_mobilenet_v2_fpnlite_320 model

### ISSUE THREAD

**Issue by michaelnguyen11** [tensorflow/tensorflow#53417]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  2.6.0
- Python version: 3.9.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: GeForce GTX 1050Ti 4G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I downloaded SSD MobileNet V2 FPNLite 320x320 pretrained model from [TF Model Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) , then used export_tflite_graph_tf2.py script to convert checkpoints to saved model.

```
python export_tflite_graph_tf2.py \
    --pipeline_config_path ssd_mobilenet_v2_fpnlite_320/pipeline.config \
    --trained_checkpoint_dir ssd_mobilenet_v2_fpnlite_320/checkpoint \
    --output_directory ssd_mobilenet_v2_fpnlite_320 \
    --config_override " \
            model{ \
            ssd{ \
              post_processing { \
                batch_non_max_suppression { \
                        score_threshold: 0.0 \
                        iou_threshold: 0.5 \
                } \
             } \
          } \
       } \
       "
```

Then convert saved model to tflite
```
converter = tf.lite.TFLiteConverter.from_saved_model(ssd_mobilenet_v2_fpnlite_320/saved_model)
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.target_spec.supported_types = [tf.float16]
converter.experimental_new_converter = True
tflite_model = converter.convert()
open(output_name, "wb").write(tflite_model)
```

However, when use NNAPI to delegate this model, it's failed with error :
```
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
DEQUANTIZE: 
327 operations will run on the GPU, and the remaining 2 operations will run on the CPU.
ERROR: TfLiteGpuDelegate Init: PACK: Tensor "ssd_mobile_net_v2fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/w_stack" has bad input dims size: 5.
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 329 (TfLiteGpuDelegateV2) failed to prepare.
```

**Describe the expected behavior**
TFLite NNAPI could delegate ssd_mobilenet_v2_fpnlite_320 model.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by srjoglekar246** [comment]
Hey @michaelnguyen11 , can you try this process with the non-FPN SSD version? 

Also, you seem to be using the GPU delegate (as shown by your logs), and not the NNAPI delegate - and for float16 models, GPU is indeed the correct delegate - just wanted to confirm.

**Comment by michaelnguyen11** [comment]
Hi @srjoglekar246 ,

I'm using the SSD Mobilenet V2 and it's working well (used TF1 to convert to TFLite). And now I want to use FPN SSD versison.

Yes I'm using GPU delegate. Both float16 and float32 have the same issue :
```
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
154 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
ERROR: TfLiteGpuDelegate Init: PACK: Tensor "ssd_mobile_net_v2fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/w_stack" has bad input dims size: 5.
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 155 (TfLiteGpuDelegateV2) failed to prepare.

ERROR: Restored original execution plan after delegate application failure.
```

**Comment by lejekjr** [comment]
Is CUSTOM TFLite_Detection_PostProcess supported by GPU delegate?

**Comment by mohantym** [comment]
Hi @michaelnguyen11 !
It looks like you are doing the inference in a desktop with Ubuntu OS.  NNAPI and GPU delegates performance meets expectation when inference are done in  Android/IOS  devices.

For Desktop purpose, You can inference with default CPU/XNNPack  delegate. 
Please do a [benchmark test](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) in android/Desktop machine to see the difference in performance and find the best delegate for your use-case.

Thank you!
