### ISSUE TITLE
Gradient for gather_nd is not implemented

### ISSUE THREAD

**Issue by lan2720** [tensorflow/tensorflow#5342]
Hi all,

when I use `tf.gather_nd`, It gives me the error "NotImplementedError: Gradient for gather_nd is not implemented".

I can temporarily solve this problem to flatten both of `params` and `indices` and then use `tf.gather`. But it isn't the best way to do so.

Is there any plan to support that? Thanks!

**Comment by aselle** [comment]
Yes, we are planning to support that. The patch will be imminently committed. @narphorium is implementing it.

**Comment by lan2720** [comment]
@aselle Oh great. Thanks for your quick reply. I'm looking forward to it.

**Comment by tfka** [comment]
@lan2720 。。how to flatten， I meet the same problem and I am a newer to tensorflow . Hope some advice for me . Thanks

**Comment by lan2720** [comment]
@tfka Yes, to use tf.gather you just need to reshape your params and indices.

For example 
```
params = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
indices = [[2, 3, 1], [4, 0, 2], [3, 4, 0]]
# After some operation
new_params = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
new_indices = [2, 3, 1, 4+5, 0+5, 2+5, 3+10, 4+10, 0+10]
```

**Comment by gdelab** [comment]
Hi,
Is it fixed yet ? I'm using gather_nd() and I don't get any warning, but my gradient descent does not seem to work properly, so I guess it could come from there...

**Comment by ebrevdo** [comment]
gather_nd gradients are available on master, and should be in the latest minor release:

https://github.com/tensorflow/tensorflow/blob/cb17d1b0e2b581b5da1d9597b7929ba764749d38/tensorflow/python/ops/array_grad.py
