### ISSUE TITLE
Tf Keras Dense layer output nan with kernel_initializer='random_normal' before fitting

### ISSUE THREAD

**Issue by mainguyenanhvu** [tensorflow/tensorflow#53432]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory:

**Describe the current behavior**
Before fitting, I used model.predict with my train set, It was ensure that train set was free of nan values. Next, I printed output of each layer.
 The output is:
```
0 [[ 1.000000e-03 -1.310000e-01 -9.504200e-02 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 0.000000e+00 -1.000000e-02  1.556190e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 1.000000e+00  5.763000e+00  3.027034e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 ...
 [ 8.930000e-01 -5.760000e-01  4.266911e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 1.000000e+00  5.978000e+00  4.650479e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 8.500000e-01  8.910000e-01  7.704330e-01 ...  0.000000e+00
   0.000000e+00  1.000000e+00]]
1 [[ 1.000000e-03 -1.310000e-01 -9.504200e-02 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 0.000000e+00 -1.000000e-02  1.556190e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 1.000000e+00  5.763000e+00  3.027034e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 ...
 [ 8.930000e-01 -5.760000e-01  4.266911e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 1.000000e+00  5.978000e+00  4.650479e+00 ...  0.000000e+00
   0.000000e+00  1.000000e+00]
 [ 8.500000e-01  8.910000e-01  7.704330e-01 ...  0.000000e+00
   0.000000e+00  1.000000e+00]]
2 [[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 ...
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
inputs = Input(shape=data.shape)
x = Flatten()(inputs)
x = Dense(data.classnum, kernel_initializer='random_normal')(x)
x = tf.keras.layers.Softmax()(x)
model = tf.keras.Model(inputs=inputs, outputs=x)

for idx in range(len(model.layers)):
        # print(model.layers[idx].name,model.layers[idx].get_weights())
        intermediate_layer_model = keras.Model(inputs=model.input,
                                    outputs=model.layers[idx].output)
        intermediate_output = intermediate_layer_model.predict(data.train_dataset)
        print(idx,intermediate_output)
```

**Comment by mainguyenanhvu** [comment]
I tried with other kernel_initializer strategies such as Ones() and Zeros() but bug is still here.

**Comment by Saduf2019** [comment]
@mainguyenanhvu 
Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thanks!

**Comment by mainguyenanhvu** [comment]
I posted [here](https://github.com/keras-team/keras/issues/15798).

**Comment by Saduf2019** [comment]
@mainguyenanhvu 
Please move this to closed status as it is tracked in keras repo.
