### ISSUE TITLE
Documentation for unit testing is not clear

### ISSUE THREAD

**Issue by IAL32** [tensorflow/tensorflow#53434]
## URL(s) with the issue:

Official TF tests documentation page: https://www.tensorflow.org/community/contribute/tests

## Description of issue (what needs changing):

It is not at all clear how one should run unit tests. In fact, some unit tests are _very_ hard to execute singularly.

For example, I have been working on a PR that requires some testing on `//tensorflow/core/lib/io` libraries, and I have spent half an hour understanding how to run the unit test [`zlib_buffers_test.cc`](https://github.com/tensorflow/tensorflow/blob/610d01a46ca531231986c75d053a0fe81e87f101/tensorflow/core/lib/io/BUILD#L382).

This is how the exploration went:

`zlib_buffers_test.cc` is included in the `filegroup` with name `legacy_lib_io_all_tests`. This in turn is included in [`//tensorflow/core:low_level_library_tests`](https://github.com/tensorflow/tensorflow/blob/610d01a46ca531231986c75d053a0fe81e87f101/tensorflow/core/BUILD#L1856).

This set of tests however is defined using `tf_cc_tests` (mind the final "s" here), which behavior is declared in [`//tensorflow/tensorflow.bzl`](https://github.com/tensorflow/tensorflow/blob/610d01a46ca531231986c75d053a0fe81e87f101/tensorflow/tensorflow.bzl#L1520), which basically allows me to run the tests under `legacy_lib_io_all_tests` like this:

```
bazel test //tensorflow/core:__tensorflow_core_lib_io_legacy_lib_io_all_tests
```

which is, at least for me, not really intuitive. And I still haven't understood how to effectively just test the `zlib_buffers_test.cc` unit test, if not by adding the flag `--test_filter=<filter>`.

I couldn't find any resource online, nor on any issue here, that mentions the behavior of unit tests or a guideline on how they should be structured and tested for using `bazel`.

I found, however, [a guy with my same issue](https://www.cxybb.com/article/weixin_44351244/116571161), so at least I know I am not alone 😅

### Clear description

> For example, why should someone use this method? How is it useful?

Anytime someone wants to make improvements on a unit test, it should be relatively easy to execute it, and relevant documentation about how that process work can really speed up development and contributions to existing parts of the project.

### Submit a pull request?

I am very happy to help! If there is some existing documentation about the unit testing process, I would happily refer to that one. If it doesn't exist, but the testing process is "known" somehow, I would gladly add a piece of documentation to the existing page mentioning how to generally run unit tests.

**Comment by MarkDaoust** [comment]
Hello, 

In any complex system there's some archaeology necessary to figure out what's going on. There's no way without at least learning the basics of bazel, and struggling is how we all learn.

If we want to provide better docs for people with this sort of problem, then this is probably the place to add them:

https://github.com/tensorflow/docs/blob/master/site/en/community/contribute/tests.md

It sounds like what you're looking for is a "finding and running tests" section. That sounds like a reasonable addition. If we can make the content clear and generic enough to be helpful in general.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
