### ISSUE TITLE
Segmentation fault and no log information available, add some tips about segmentation fault

### ISSUE THREAD

**Issue by beiluo97** [tensorflow/tensorflow#53430]
**System information**
- TensorFlow version (you are using): tensorflow 1.12.0, python 3.6.13
- Are you willing to contribute it (Yes/No): Yes. 

**Describe the feature and the current behavior/state.**
I have trouble retraining my colleague's code from a year ago. I notice that when I try to load my model in the former code base on *libtensorflow-cpu-linux-x86_64-1.12.0* it reports a `Segmentation fault`, without any further information. Upon inspecting my code, I notice that it stops when I load the model, function `TF_SessionRun`. I'm not sure what to do to fix it. A moment later, my colleague realized the problem was the parameters in the placeholder name were incorrect. A moment later, my colleague realized the problem was the parameters in the placeholder name were incorrect. We fixed it after changing the placeholder name.

**Will this change the current api? How?**
No.
**Who will benefit with this feature?**
Those who are not familiar with tensorflow v1's place holder.
**Any Other info.**
No.

**Comment by tilakrayal** [comment]
@beiluo97 ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!

**Comment by tilakrayal** [comment]
Also we see that you are using tf version 1.12, 1.x is not actively supported, please update to v2.7 and let us know if you are using same issue.
