### ISSUE TITLE
[TFLite] Support building external delegate with CMake

### ISSUE THREAD

**Issue by Honry** [tensorflow/tensorflow#53447]
TensorFlow Lite supports external delegate but not supported in CMake build, do we have plan to support it?

**Comment by Honry** [comment]
Sorry, looks like https://github.com/tensorflow/tensorflow/pull/52962 is addressing this request.

**Comment by mohantym** [comment]
@Honry! Thank for the feature request. This issue will be closed once above [PR](https://github.com/tensorflow/tensorflow/pull/52962) is merged.  Thanks!

**Comment by mohantym** [comment]
Hi @Honry ! Can this issue be closed now ? The above PR is merged now.

**Comment by Honry** [comment]
Yeah sure, thank you for your great work!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
