### ISSUE TITLE
Support partial parameter warm-start from pretrained checkpoints in tensorflow v2 (non-estimator mode)

### ISSUE THREAD

**Issue by yunjiangster** [tensorflow/tensorflow#53443]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow 2.x
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Warm-starting from an existing checkpoint is an important feature for all kinds of model training that's well supported under tf.estimator framework. The latter unfortunately seems relegated to second class status in tensorflow 2.x, since it's not eager (at least not natively?). 

The closest way to achieve warm-start in tf2.x seems to be via tf.train.Checkpoint, a more directly approach than tf.estimator.warm_start_utils, that is, if implemented well. So far however I see that it supports loading all the parameters in a checkpoint altogether, but not loading only some of the parameters. 

**Will this change the current api? How?**
Possibly. Maybe provide a kwarg in Checkpoint initializer called parameter_list.

**Who will benefit with this feature?**
Anyone who wants to reuse a pretrained model but not all of its parameters.

**Any Other info.**
There is a lot of emphasis on eagerness, efficiency, in tensorflow v2, but in my opinion not sufficient focus on flexibility and directness of usage so far. Warm-starting is one example.

Update: my colleague found an unofficial implementation of flexible warm-start from a checkpoint in the TF2 version of BERT [here](https://github.com/kpe/bert-for-tf2/blob/master/bert/loader.py#L236). I would recommend adding some official examples along similar lines.

**Comment by ArtyomZemlyak** [comment]
Found a solution to load specific weights of a pretrained model. The solution is described in the following comment:
https://github.com/tensorflow/tensorflow/issues/37793#issuecomment-1003677482
Maybe it will help you in some way.

**Comment by jvishnuvardhan** [comment]
@yunjiangster Is this resolved or still an issue for you. Also, please check the "comment" as mentioned by @ArtyomZemlyak.  

Please let us know If there is any actionable item like PR to update or create a tutorial or guide. Thanks!
