### ISSUE TITLE
[PluggableDevice] Cross-device copies support

### ISSUE THREAD

**Issue by PatriceVignola** [tensorflow/tensorflow#53446]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.12.1-69032-gfb972503145 2.8.0-dev20211220
- Python version: 3.9
- Bazel version (if compiling from source): 3.7.2

**Describe the current behavior**

When using a PluggableDevice plugin with 2 physical graphics cards, the `memcpy_dtod` function is invoked. This function, however, only has a single `SP_Device` as a parameter, even when the `src` and `dst` memory regions are from different devices.

**Describe the expected behavior**

The `memcpy_dtod` function should have 2 `SP_Device` parameters in case the copy is done cross-adapter to give the plugin a chance to handle cross-device copies.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): Adding a `memcpy_dtod_cross_adapter` function for cross-device memory copies, or adding a second `SP_Device` parameter to `memcpy_dtod` (although the latter wouldn't be backward compatible).

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

a = tf.compat.v1.placeholder(dtype=tf.float32, shape=[3,1])
a_values = [[1],[2],[3]]

b = tf.compat.v1.placeholder(dtype=tf.float32, shape=[3,1])
b_values = [[4],[6],[11]]

c = tf.compat.v1.placeholder(dtype=tf.float32, shape=[1,3])
c_values = [[2,4,5]]

with tf.device("/device:CUSTOM:0"):
    y1 = tf.raw_ops.AddN(inputs=[a,b], name="MyAdd")
with tf.device("/device:CUSTOM:1"):
    y2 = tf.raw_ops.MatMul(a=y1, b=c, name="MyMultiply")

with tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True)) as s:
    print(s.run(y2, feed_dict={a:a_values, b:b_values, c:c_values}))
```

**Comment by sushreebarsa** [comment]
@PatriceVignola 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by PatriceVignola** [comment]
@sushreebarsa Thank you, I updated the issue with the template.

**Comment by sushreebarsa** [comment]
@PatriceVignola Thank you for the update! 
We see that you are using `TF v1.12` which is not actively supported ,could you please upgrade to `TF v2.4. or later`(FYI Latest stable TF v2.7.0 )?  
This` tf.compat.v1.Session` API was designed for TensorFlow v1. Please check this [details](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session) on how to migrate from this API to a native TensorFlow v2 equivalent. See the TensorFlow v1 to TensorFlow v2 [migration guide](https://www.tensorflow.org/guide/migrate) for instructions on how to migrate the rest of your code.
As `TensorFlow version 1.x `is out of support window so for any further queries  please post this issue in [TF Forum](https://discuss.tensorflow.org/) where there is a larger community to help .Thank you!

**Comment by PatriceVignola** [comment]
I'm not using 1.12, I'm using 2.8.0-dev20211220 (I was also using 2.7.0 and having the same problem). This is a PluggableDevice specific issue, which is a TF 2 feature.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
