### ISSUE TITLE
Import error: AttributeError: 'module' object has no attribute 'Default'

### ISSUE THREAD

**Issue by JohnnyY8** [tensorflow/tensorflow#5344]
### Environment info
Operating System:  Ubuntu 14.04 LTS

Installed version of CUDA and cuDNN: CUDA-8.0 and cuDNN v5.1

Hi everyone:
   I have met an ImportError and do not what happened? Before this, I use tensorflow normally for about one month.
   Can anyone help me? Thanks a lot!

The error info as following (in Ipython).

```python
In [2]: import tensorflow as tf
```
```
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcurand.so.8.0 locally

AttributeError                            Traceback (most recent call last)
<ipython-input-2-41389fad42b5> in <module>()
----> 1 import tensorflow as tf

/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *
     24 
     25 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py in <module>()
     61 
     62 # Protocol buffers
---> 63 from tensorflow.core.framework.graph_pb2 import *
     64 from tensorflow.core.framework.node_def_pb2 import *
     65 from tensorflow.core.framework.summary_pb2 import *

/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py in <module>()
      7 from google.protobuf import message as _message
      8 from google.protobuf import reflection as _reflection
----> 9 from google.protobuf import symbol_database as _symbol_database
     10 from google.protobuf import descriptor_pb2
     11 # @@protoc_insertion_point(imports)

/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py in <module>()
    163 
    164 
--> 165 _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
    166 
    167 

AttributeError: 'module' object has no attribute 'Default'
```

**Comment by aselle** [comment]
What .whl did you use to install?
Did you use a virtualenv (try one if you haven't already)?
DId you try ```pip install --upgrade protobuf```?

**Comment by JohnnyY8** [comment]
Hi @aselle :
I use to install tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl and run tensorflow normally for one month. This error suddenly occured. Now, I have tried to reinstall the tensorflow, but when I run ./configure, I got this error:
```
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/common/tools/tensorflow/third_party/gpus/cuda_configure.bzl", line 517
		_create_cuda_repository(repository_ctx)
	File "/home/common/tools/tensorflow/third_party/gpus/cuda_configure.bzl", line 432, in _create_cuda_repository
		_cuda_toolkit_path(repository_ctx, cuda_version)
	File "/home/common/tools/tensorflow/third_party/gpus/cuda_configure.bzl", line 148, in _cuda_toolkit_path
		str(repository_ctx.path(cuda_toolkit...)
	File "/home/common/tools/tensorflow/third_party/gpus/cuda_configure.bzl", line 148, in str
		repository_ctx.path(cuda_toolkit_path).realpath
Object of type 'path' has no field "realpath".
```
I am not sure what happened exactly?

**Comment by aselle** [comment]
So you switched from using a precompiled binary to compiling from source? Correct?
Does it work if you go back to the old whl that was working?
Did you try upgrading your version of bazel? You did not provide the output of bazel --version?

**Comment by JohnnyY8** [comment]
Hi @aselle :
I have tried to reinstall tensorflow from compiling the source, but it did not work. I do not why, but I noticed that tensorflow can be installed by pip with CUDA 8.0 and cuDNN v5.1. It works for me.
I tried to upgrading my version of bazel and got the different error.
Although pip works for me, but I still do not know why does the my tensorflow crash?
I will close this issue, if anyone need it, I will reopen it.
Thanks for your time and help!

**Comment by CTTC** [comment]
Hi, @JohnnyY8  How do you solved your problem? I just installed latest tensorflow with CUDA 8.0 and cuDNN 5.1 using the Pip installation method. And I met the same problem.

**Comment by JohnnyY8** [comment]
@CTTC Hi:
     I installed tensorflow with CUDA 8.0 AND cuDNN 5.1 from source, but got that error. Then I noticed the latest tensorflow can be installed by pip, and it works for me. Do you use pip and got the same error as mine?

**Comment by JohnnyY8** [comment]
@CTTC Have you installed tensorflow successfully by any ways?

**Comment by CTTC** [comment]
@JohnnyY8 I haven't solved this problem yet. I have tried both ways. And pip installation didn't work for me.

**Comment by JohnnyY8** [comment]
@CTTC Pip installlation works for me, but I still do not know the root reason about this problem. I have reopened this issue, hope anyone can provide some suggestions. If you solved this problem, please share with me the method. Thank you!

**Comment by girving** [comment]
The original comment includes `No module named tensorflwo`.  This is not surprising, since it's called tensorflow, not tensorflwo.  Was that the problem?

**Comment by JohnnyY8** [comment]
@girving Hi:
I am sorry for my mistake, but my original code is writed and run correctly. Suddenly got this error.
I want to reinstall tensorflow from source, it did not work, but pip installation works.
@CTTC has the same problem, I do not know what happened exactly?

**Comment by girving** [comment]
@JohnnyY8 Can you reformat your original post so that the code and code output is easier to read?  Indenting by 4 spaces causes code formatting.  Also, can you say what the current error you are experiencing is?  The "Object of type 'path' has no field "realpath"." was fixed (https://github.com/tensorflow/tensorflow/issues/5319), and I'm having trouble following the thread to know if that was the final issue.

**Comment by JohnnyY8** [comment]
@girving Hi：
I have reformated the original post, is that easier to read? I am sorry that I do not know the right code format. Maybe @aselle  will try the #5319 , hope it will work.

**Comment by girving** [comment]
@JohnnyY8 Yep, much easier to read.  Thank you!

If understand correctly that #5319 was the last error, let me know if upgrading past that fixes the problem.  If something else was the last error, also let me know.

**Comment by JohnnyY8** [comment]
@girving Hi:
Thanks for your help!
