### ISSUE TITLE
When I use ObjectDetection Demo,it tips Invalid tensor index 1, max index is 0.How can I do?

### ISSUE THREAD

**Issue by csdf-ssm** [tensorflow/tensorflow#53455]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) 11.6 (20G165)
- TensorFlow installed from (source or binary):TensorFlowLiteSwift','2.6.0'
- TensorFlow version (or github SHA if from source):TensorFlowLiteSwift','2.6.0'

question:
When I use ObjectDetection Demo,it tips Invalid tensor index 1, max index is 0,How can I do?  
I do not know where is Error ,I just use my tflitemodel to replace Demo tflitemodel ,it show last tips:

Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Failed to invoke the interpreter with error: Invalid tensor index 1, max index is 0.
Failed to invoke the interpreter with error: Invalid tensor index 1, max index is 0.
Failed to invoke the interpreter with error: Invalid tensor index 1, max index is 0.
...

**Comment by tilakrayal** [comment]
@csdf-ssm ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by tilakrayal** [comment]
Also please take a look at this issue [1](https://github.com/tensorflow/tensorflow/issues/33976) and [2](https://github.com/tensorflow/tensorflow/issues/39803) with the similar error.It helps.Thanks!

**Comment by csdf-ssm** [comment]
@tilakrayal  I use yolov5 to train model  and output only 1 data ,so the demo is  not suit me,thanks
