### ISSUE TITLE
Description error of 'non_max_suppression_with_scores'

### ISSUE THREAD

**Issue by raoshenglong** [tensorflow/tensorflow#53453]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py

### Clear description
1. In line 3755，I think it we should modify `tf.image.non_max_suppression_padded` to be `tf.image.non_max_suppression_with_scores`;
2. In line 3760，I think it we should modify `tf.image.non_max_suppression_padded` to be `tf.image.non_max_suppression_with_scores`;

**Comment by raoshenglong** [comment]
@sushreebarsa should i submit a PR ？ or someone will fix docs bug together?

**Comment by sushreebarsa** [comment]
@raoshenglong Sorry for the late response! 
Please let me know if I should raise a PR on your behalf to fix this issue ?Thanks!

**Comment by raoshenglong** [comment]
@sushreebarsa OK，you can raise a PR to fix it and then close this issue.

**Comment by sushreebarsa** [comment]
@raoshenglong This issue will be closed once the [PR](https://github.com/tensorflow/tensorflow/pull/53496) is merged.Thanks!

**Comment by sushreebarsa** [comment]
@raoshenglong Could you please confirm if we can close this issue as the [PR](https://github.com/tensorflow/tensorflow/pull/53496) is merged?Thanks!

**Comment by raoshenglong** [comment]
OK, I will close it. @sushreebarsa
