### ISSUE TITLE
TensorFlow Lite Model Maker has version conflict during install on RPi02W

### ISSUE THREAD

**Issue by baqwas** [tensorflow/tensorflow#53464]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/lite/guide/model_maker

Please provide a link to the documentation entry, for example:
[Model Maker Object Detection](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/)

## Description of issue (what needs changing):

Cannot install **tflite_model_maker** and **tflite_support** on Raspberry Pi Zero 2 W

` uname -a
Linux raspbari17 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux
`
### Clear description

To fix this you could try to:
1. _loosen_ the range of package versions you've specified
2. _remove_ package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

### Correct links

Is the link to the source code correct? n/a

### Parameters defined

Are all parameters defined and formatted correctly? Yes

### Returns defined

Are return values defined? n/a

### Raises listed and defined

ERROR: Cannot install tflite-model-maker==0.1.0, tflite-model-maker==0.1.1, tflite-model-maker==0.1.2, tflite-model-maker==0.2.0, tflite-model-maker==0.2.1, tflite-model-maker==0.2.2, tflite-model-maker==0.2.3, tflite-model-maker==0.2.4, tflite-model-maker==0.2.5, tflite-model-maker==0.3.0, tflite-model-maker==0.3.1, tflite-model-maker==0.3.2, tflite-model-maker==0.3.3 and tflite-model-maker==0.3.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    tflite-model-maker 0.3.4 depends on tensorflow-addons>=0.11.2
    tflite-model-maker 0.3.3 depends on tensorflow-addons>=0.11.2
    tflite-model-maker 0.3.2 depends on tensorflow-addons>=0.11.2
    tflite-model-maker 0.3.1 depends on tensorflow-addons>=0.11.2
    tflite-model-maker 0.3.0 depends on tensorflow-addons>=0.11.2
    tflite-model-maker 0.2.5 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.4 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.3 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.2 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.1 depends on tf-nightly==2.4.0.dev20200811
    tflite-model-maker 0.2.0 depends on tf-nightly==2.4.0.dev20200810
    tflite-model-maker 0.1.2 depends on tf-nightly
    tflite-model-maker 0.1.1 depends on tf-nightly
    tflite-model-maker 0.1.0 depends on tf-nightly

### Usage example

Is there a usage example?

`sudo python3 -m pip install tflite-model-maker`

### Request visuals, if applicable

Are there currently visuals? No but terminal output entered above.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? No, beyond my job grade. Sorry.

**Comment by jimjam-slam** [comment]
I've been getting the same error trying to install on an M1 Mac for a few months. I've tried to install:

* In a Miniforge3 environment;
* In a Python Docker image;
* In a Miniconda3 x86 environment, using a version of Terminal running through Rosetta.

I was, however, able to install it using a Miniconda environment or a Python Docker image on Windows via WSL2.

**Comment by chunduriv** [comment]
@baqwas,

Could you let us know what is the version of `tflite-model-maker` and `tensorflow` installed? 

Please refer [requirements.txt](https://github.com/tensorflow/examples/blob/master/tensorflow_examples/lite/model_maker/requirements.txt) for dependent libraries and let us know if it helps you? Thanks!

**Comment by baqwas** [comment]
Hello @chunduriv,

Sorry, I couldn't locate any _applicable_ `requirements.txt` file (related to TFL) except for Pete Warden's famous _Magic Wand_ example. My installation steps are:

```
git clone https://github.com/tensorflow/tensorflow.git tensorflow
cd tensorflow && ./tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/lite/tools/make/build_rpi_lib.sh

```

I don't have the knowledge to loosen the version requirements. I tried the `-Wno-error=class-memaccess` option but that did not eliminate that specific error. The Flatbuffers team claim to have fixed the issue at their end several versions ago. Here is the advice from Rients at Q-Engineering (who success in leveraging RPi0 I was trying to emulate with RPi02W):

```
They repaired the issue on May 29, 2020. The next fixed version will be v2.0.0 released on May 10, 2021.
Looking at the download script of TF 2.6 and 2.7 you see they use v1.12.0. That is why it errors. (BTW, only with gcc 10.2.1 found in Bullseye).
TF has deprecate the script building of lite, leaving with the hint to use Bazel.
Tip: try replacing the v.1.12.0 with the v2.0.0.tar.gz in the download_dependencies.sh (tensorflow/lite/tools/make/)

```

I apologize for not being able to reply more precisely to your request for information (so that you can provide further guidance).

The hardware platform information is:
```

cat /proc/cpuinfo
...
processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: 902120
Model		: Raspberry Pi Zero 2 Rev 1.0

cat /proc/version
Linux version 5.10.63-v7+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1488 SMP Thu Nov 18 16:14:44 GMT 2021

cat /home/pi/projects/tensorflow/tensorflow/lite/micro/examples/magic_wand/train/requirements.txt
numpy==1.16.2
tensorflow==2.5.0

```

We're all doing TFL modeling on our desktops and downloading to our TinyML devices but being to do _one stop shopping_ using RPi02W would be more productive, versatile and ubiquitous. Thanks for your help and understanding.

Kind regards.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by baqwas** [comment]
Understood. Thanks for all the previous help.
