### ISSUE TITLE
Cannot create hexagon delegate on my tablet

### ISSUE THREAD

**Issue by walex** [tensorflow/tensorflow#53463]
Hello I'm trying to create a dsp/hexagon delegate on my android tablet, but for some reason ioctrl fails as reported on device log
Any help!
Regards,
Walter

Relevant C++ code:

//TfLiteHexagonInit(); // also desnt works
TfLiteHexagonInitWithPath("dsp;/data/dsp;/system/vendor/lib/rfsa/adsp");
TfLiteHexagonDelegateOptions hexagon_opts = {0};
TfLiteDelegate* hexagonDelegate = TfLiteHexagonDelegateCreate(&hexagon_opts)  // fails here

Log:

I/tflite: Initialized TensorFlow Lite runtime.
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:688::error: -1: 0 == ioctl(dev, FASTRPC_IOCTL_INIT, (unsigned long)&init)
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:764::error: -1: !apps_dev_init(domain)
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:431::error: -1: -1 != open_dev(domain)
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:688::error: -1: 0 == ioctl(dev, FASTRPC_IOCTL_INIT, (unsigned long)&init)
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:764::error: -1: !apps_dev_init(domain)
E/adsprpc: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:329::error: -1: -1 != (dev = open_dev(domain))
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.

cat /proc/cpuinfo | grep Hardware
Hardware        : Qualcomm Technologies, Inc APQ8096

adb shell getprop ro.product.device
msm8996

adb shell getprop ro.board.platform
msm8996

Using Hexagon libraries v1.20.0.1 downladed from here https://www.tensorflow.org/lite/performance/hexagon_delegate

Benchmark app throws this log:

STARTING!
Log parameter values verbosely: [0]
Graph: [mobilenet_v1_0.25_192_quant.tflite]
Use Hexagon: [1]
Loaded model mobilenet_v1_0.25_192_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libadsprpc.so
Func remote_handle_control not available on this device (NULL).
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.

Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
The input model file size (MB): 0.497264
Initialized session in 285.927ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=68 first=17405 curr=6455 min=6361 max=17405 avg=7354.15 std=2021

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=143 first=6432 curr=6750 min=6371 max=12065 avg=6967.24 std=676

Inference timings in us: Init: 285927, First inference: 17405, Warmup (avg): 7354.15, Inference (avg): 6967.24
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=0.972656 overall=2.53125

**Comment by tilakrayal** [comment]
@walex ,
 In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.

**Comment by tilakrayal** [comment]
Also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/39024) with the similar error.It helps.Thanks

**Comment by walex** [comment]
Hello, this is the complete code: (Its a big system so I remove some no needed parts)


// C++

 jlong JNICALL Java_com_dsense_PersonScannerWrapper_nativeInit(JNIEnv* env, jobject thiz , jstring modelPath, jboolean forceDSPProcessing) {


	const char* pModelPath = env->GetStringUTFChars(modelPath, 0);
	
	// load model
	TfLiteModel* model = TfLiteModelCreateFromFile(modelPath.c_str());

	// create interpreter
	TfLiteInterpreterOptions* options = TfLiteInterpreterOptionsCreate();
	TfLiteInterpreterOptionsSetNumThreads(options, 1);
	TfLiteInterpreter* interpreter = TfLiteInterpreterCreate(pModelPath, options);
	TfLiteInterpreterOptionsDelete(options);

	// release model
	TfLiteModelDelete(model);

	env->ReleaseStringUTFChars(modelPath, pModelPath);
	
	return reinterpret_cast<jlong>(interpreter);
}

// JAVA

public class PersonScannerWrapper {

    static
    {
        System.loadLibrary("tensorflowlite_jni");
        System.loadLibrary("tensorflowlite_hexagon_jni");
        System.loadLibrary("PersonScanner");
    }

    private static native long nativeInit(String modelPath, boolean forceDSPProcessing);
  

    private long mHandle = 0;
    public PersonScannerWrapper(String modelPath, boolean forceDSPProcessing) throws Exception {


        long handle = PersonScannerWrapper.nativeInit(modelPath, forceDSPProcessing);
        if (handle == 0) {

            throw new Exception();
        }

        this.mHandle = handle;
    }
}

public class MainActivity extends AppCompatActivity {

    static String modelName = "mobilenet_v1_0.25_192_quant.tflite";
    PersonScannerWrapper mScanner = null;
    AssetsUtils mAssetsUtils = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

      
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

		// copy model to android device local storage
        String modelPathName = this.getFilesDir().getAbsolutePath() + modelName;
        mAssetsUtils = new AssetsUtils(this);
        mAssetsUtils.copyFile(modelName, modelPathName);

   
    }


    @Override
    protected void onResume() {

        try {
            String modelPathName = this.getFilesDir().getAbsolutePath() + modelName;
            mScanner = new PersonScannerWrapper(modelPathName, forceUseDSP);
        } catch (Exception e) {
            e.printStackTrace();
            mScanner = null;
        }
        super.onResume();
    }

    @Override
    protected void onPause() {

        super.onPause();
    }
}

**Comment by sachinprasadhs** [comment]
Please follow [this](https://www.tensorflow.org/lite/performance/hexagon_delegate) document and make sure you are using the  hexagon_nn libraries with the [compatible version](https://www.tensorflow.org/lite/performance/hexagon_delegate#step_2_add_hexagon_libraries_to_your_android_app_2) of interface library.
