### ISSUE TITLE
[TFLite] iOS app crashes with EXC_RESOURCE when building with XCode 13

### ISSUE THREAD

**Issue by anhappdev** [tensorflow/tensorflow#53461]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: iOS 15
- Mobile device if the issue happens on mobile device: iPhone
- TensorFlow installed from: source
- TensorFlow version: 2.6.0
- Python version: Python 3.9.7
- Bazel version: 4.2.1-homebrew
- GCC/Compiler version: Apple clang version 13.0.0 (clang-1300.0.29.3)
- CUDA/cuDNN version: n.a.
- GPU model and memory: n.a.

**Describe the current behavior**
The app crashes with `EXC_RESOURCE` when running TFLite model on iOS device.
* This problem occurs only when the app is built with XCode 13.0 / 13.1 / 13.2 and using Core ML backend.
* The problem does not occur when the app is built with XCode 12.

**Describe the expected behavior**
App run without crash when built with XCode 13

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

@freedomtan has identified the issue:
> FYR. I upgraded my macOS, iOS, and Xcode to 12.1, 15.2, and Xcode 13.2 yesterday. Then, I spent some time profiling and found that the culprit is [CoreML delegate's invoke function].(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_delegate_kernel.mm#L207-L230). Adding `@autoreleasepool {}` to it resolved the EXC_RESOURCE issue. Tested on iPhone 11 Pro and iPhone 13 running iOS 15.2. Supposedly, it worked for earlier Xcode 13.x and iOS.

**Standalone code to reproduce the issue**
Not possible since the app need to be built and run.

**Other info / logs**

The app used is located here: https://github.com/mlcommons/mobile_app_open

Crash log:
```
flutter: Running Benchmark:IS_float32 in performance mode...

...

li:cpp/flutter/main.cc:252@run_backend4
2021-10-02 14:21:30.769776: I cpp/backends/external.cc:135] Using default allocator
Enabling CoreML delegate 0x2836b5a00
CoreML delegate: 76 nodes delegated out of 77 nodes, with 1 partitions.
INFO: CoreML delegate: 76 nodes delegated out of 77 nodes, with 1 partitions.

li:cpp/flutter/main.cc:257@run_backend4
2021-10-02 14:21:31.456619: E cpp/datasets/ade20k.cc:76] Failed to list all the ground truth files in provided path. Only measuring performance.
li:cpp/flutter/main.cc:285@run_backend4
li:cpp/flutter/main.cc:289@run_backend4
* thread #26, name = 'DartWorker', queue = 'com.apple.CoreMLBatchProcessingQueue', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001f37d864c libsystem_platform.dylib`_platform_memmove + 76
libsystem_platform.dylib`_platform_memmove:
->  0x1f37d864c <+76>: stnp   q0, q1, [x3]
    0x1f37d8650 <+80>: add    x3, x3, #0x20             ; =0x20 
    0x1f37d8654 <+84>: ldnp   q0, q1, [x1]
    0x1f37d8658 <+88>: add    x1, x1, #0x20             ; =0x20 
Target 0: (Runner) stopped.
```
![135967965-1e284466-a072-4b15-8895-9bbd6001a70a](https://user-images.githubusercontent.com/85728587/146400916-bc8d5e6d-5053-41fb-b4ba-2df5bca58fc1.png)

**Comment by sushreebarsa** [comment]
@anhappdev This issue will be closed once the [PR](https://github.com/tensorflow/tensorflow/pull/53468) is merged.Thanks!
