### ISSUE TITLE
tensorflow-cpu install from conda-forge fails with 'requires grpc-cpp >=1.39.1,<1.40.0a0, but none of the providers can be installed'

### ISSUE THREAD

**Issue by brsolomon-deloitte** [tensorflow/tensorflow#53462]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04.3 LTS
- TensorFlow installed from (source or binary): binary, `tensorflow-cpu` latest as of 12 Dec 2021
- TensorFlow version: latest (should install 2.6.2, installs 2.6.0 due to existing packages)
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: `mamba` `/ conda`
- GPU model and memory: none, CPU only

**Describe the problem**

Run following Docker container:

```
docker container run -it --rm --entrypoint=bash --user=0 \
  jupyter/all-spark-notebook
```

Run these commands:

```
cat << EOF > req.txt
jupyterhub
nbgitpuller
pyspark
boto3
elasticsearch
altair
beautifulsoup4
bokeh
bottleneck
cloudpickle
cython
dask
h5py
ipympl
ipywidgets
matplotlib-base
nltk
gensim
numba
numexpr
pandas
patsy
protobuf
pytables
scikit-learn
scikit-image
scipy
seaborn
statsmodels
xlrd
EOF

mamba install -q --file req.txt -y
mamba install -v -y -c conda-forge tensorflow-cpu
```

Will result in:

```
info     Problem count: 1
Encountered problems while solving:
  - package tensorflow-base-2.6.0-cpu_py39h7e79a0b_2 requires grpc-cpp >=1.39.1,<1.40.0a0, but none of the providers can be installed
```

Notice that:

- 2.6.2 is latest version of tensorflow, but this appears to install 2.6.0
- grpc-cpp 1.42.0 is installed already prior to tensorflow-cpu attempted install

So let's try:

```
mamba install -v -y -c conda-forge tensorflow-cpu==2.6.2
```

Result:

```
info     Problem count: 1
Encountered problems while solving:
  - package grpc-cpp-1.42.0-ha1441d3_1 requires libprotobuf >=3.19.1,<3.20.0a0, but none of the providers can be installed
```

Funny thing is, `libprotobuf` 3.19.1 _is_ installed:

```
mamba list | grep proto
# libprotobuf               3.19.1               h780b84a_0    conda-forge
```

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue?

**Comment by brsolomon-deloitte** [comment]
I believe the root of this is that `grpc-cpp` 1.42 gets installed by those previous requirements from reqs.txt, and is unable to downgrade to >=1.39.1,<1.40.0a0.

Suffice it to say, we have had a miserable time trying to install any version at all of `tensorflow-cpu` alongside this list of scientific computing packages.

**Comment by brsolomon-deloitte** [comment]
FYI I have opened a separate issue at https://github.com/mamba-org/mamba/issues/1354. This install also fails using `conda`, and takes quite literally over an hour to fail to solve.

**Comment by Saduf2019** [comment]
@brsolomon-deloitte 
Could you please try a version below and let us know.

**Comment by brsolomon-deloitte** [comment]
> @brsolomon-deloitte Could you please try a version below and let us know.

What is "a version below"? This install fails with both tensorflow-cpu==2.6.0 and tensorflow-cpu==2.6.2.

**Comment by brsolomon-deloitte** [comment]
Please reopen, this was never resolved.

**Comment by brsolomon-deloitte** [comment]
not stale

**Comment by sachinprasadhs** [comment]
As mentioned here https://github.com/tensorflow/tensorflow/issues/54154, conda-forge is a community build and these are not supported by Tensorflow.
For any issue specific to `conda-forge` for tensorflow you can refer to https://github.com/conda-forge/tensorflow-feedstock and regarding issues on mamba you can refer `mamba-org/mamba` repository, I can already see your related issues filed on the same repository for specific error message.
