### ISSUE TITLE
Remove references to HCC

### ISSUE THREAD

**Issue by searlmc1** [tensorflow/tensorflow#53475]
https://github.com/tensorflow/tensorflow/blob/b56e6db5e7cccfffa824bbc1b5e018c6cc413c21/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc#L739

HCC was removed from ROCm in Summer 2020; references to it are likely cruft / removable.

Mark

**Comment by sushreebarsa** [comment]
@searlmc1 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by Saduf2019** [comment]
The Pr created has been merged hence moving this to closed status.
