### ISSUE TITLE
Change http://ufpr.dl.sourceforge.net links for http_archive to another more stable one

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5347]
TensorFlow build dependens on external links, for example:
```python
  native.new_http_archive(                                                      
    name = "gif_archive",                                                       
    url = "http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz",
    sha256 = "34a7377ba834397db019e8eb122e551a49c98f49df75ec3fcc92b9a794a4f6d1",
    strip_prefix = "giflib-5.1.4/lib",                                          
    build_file = str(Label("//:gif.BUILD")),                                    
  )
```
Looks like http://ufpr.dl.sourceforge.net is just a SF mirror located in Brazil, and not quite stable, see #3929, #4085. I also encountered this some times. Considering change to another stable one, for example: http://downloads.sourceforge.net

A list of SF sites/mirrors:
https://github.com/fink/fink-mirrors/blob/master/sourceforge

**Comment by llhe** [comment]
By the way, I can't access it both in China and US-West, now, so the reason is that mirror is down instead of my network connection issue.

**Comment by aselle** [comment]
Thanks for reporting the issue! @gunan, I don't know if there was a specific reason we chose than link, but the fix seems to make sense.

**Comment by gunan** [comment]
#5346 already addressed this.
To the best of my knowledge, debian links should also be ok in China.
