### ISSUE TITLE
how to change model from default efficientnet_lit0 in tflite model maker image_classifier.create()

### ISSUE THREAD

**Issue by suyash-narain** [tensorflow/tensorflow#53478]
Hi,

I wanted to know in tflite model maker, if i want to use a custom model and not the default model to train and quantize with custom data, how do i do that? image.classifier.create() seems to be using efficientnet_lite0 as default and i cannot seem to change it to any other model, say mobilenet_v2.

thanks

**Comment by tilakrayal** [comment]
@suyash-narain ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.

**Comment by tilakrayal** [comment]
Also please take a look at this [link](https://www.tensorflow.org/lite/api_docs/python/tflite_model_maker/image_classifier/create) which provides more information.It helps!
