### ISSUE TITLE
Tensorflow.fit method is using 3 times more memory than it should

### ISSUE THREAD

**Issue by Chaudry24** [tensorflow/tensorflow#53488]
Hi! 

I am running two near-identical scripts. The code is provided in the following links:
script1.py: https://pastebin.com/66i8kEnK
script2.py: https://pastebin.com/AWfQUguq

The code for the helper-function which is in some_file_1.py:
helper.py: https://pastebin.com/fXgWcuz5

script1.py is using a 3 times more memory than script2.py. The only main difference between the two is that, in script1, I am converting my data and params to tf.tensors as I pass into model.fit method and in script2, I convert before passing into the .fit method.

My python version is 3.9.7 and tensorflow version is 2.4.1. 

The OS is: Red Hat Enterprise Linux
The Kernel is: Linux 3.10.0-1160.2.1.el7.x86_64
The architecture is: x86-64

The GPU is Nvidia either P100 or Nvidia V100.

**Comment by mohantym** [comment]
Hi @Chaudry24 ! Could you please provide the above code as Colab gist as its hard to replicate to this issue because of missing .py and .npy files.
