### ISSUE TITLE
Off by one discrepancy for tf.nn.conv1d between cpu and gpu

### ISSUE THREAD

**Issue by abhmul** [tensorflow/tensorflow#53489]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information (CPU Tensorflow code)**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.6 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.7.0-rc1-69-gc256c071bb2 2.7.0**
- Python version: **Python 3.9.0**
-  Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**System information (GPU Tensorflow code)**
- Running Docker image **tensorflow/tensorflow:latest-gpu-jupyter**, imageID: **8da916739a38**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04.3 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **unsure**
- TensorFlow version (use command below): **v2.7.0-rc1-69-gc256c071bb2 2.7.0**
- Python version: **3.8.10**
- Bazel version (if compiling from source): **unsure**
- GCC/Compiler version (if compiling from source): **unsure**
- CUDA/cuDNN version: 
  - Cuda: **11.2.152** build **cuda_11.2.r11.2/compiler.29618528_0**
  - CUDNN: **8100**
- GPU model and memory: **GeForce GTX 1060** w/ **6078MiB**

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**:
Code attached takes as input a binary sequence and convolves a filter over it to compute the decimal representation of each length 5 binary substring. For example, the binary sequence` [0, 1, 1, 0, 1, 1]` gets converted to `[13, 27]`.

When the length of the string is 33 or greater, the CPU and GPU outputs differ. CPU is correct and GPU is off-by-one in some cases. There is no noticeable pattern for when the GPU is off-by-one:

**CPU:**
Input binary sequence: `[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0]`
Converted decimal sequence `[1, 3, 7, 14, 28, 24, 16, 0, 0, 1, 3, 7, 15, 31, 31, 31, 31, 31, 31, 31, 30, 29, 27, 22, 12, 25, 19, 6, 13, 27, 23, 14, 28]`

**GPU:**
Input binary sequence: `[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0]`
Converted decimal sequence: `[1, 3, 7, 13, 28, 23, 16, 0, 0, 1, 3, 6, 14, 30, 30, 30, 30, 31, 30, 30, 30, 29, 26, 22, 12, 25, 19, 6, 12, 26, 22, 13, 27]`

**Describe the expected behavior**

Both converted decimal sequences should agree. The CPU sequence is the correct one.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): **no**
- Briefly describe your candidate solution(if contributing): **N/A**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
import numpy as np


def base_2_accumulator(length: int):
    powers_of_2 = tf.bitwise.left_shift(1, tf.range(length))
    return powers_of_2[::-1]

rng = np.random.default_rng(0)

dump_file = './cpu_outputs.txt'
# dump_file = './gpu_outputs.txt'

f = open(dump_file, 'w')

batch_size = 1000
block_len=33
msg = tf.constant(rng.integers(0, 2, size=(batch_size, block_len, 1)), dtype=tf.int32)
print('msg', file=f)
print(msg, file=f)

window = 5
base_2 = base_2_accumulator(window)
print('base_2', file=f)
print(base_2, file=f)
print(base_2)

base_2_filter = tf.cast(base_2[:, None, None], dtype=tf.float32)
print('base_2_filter', file=f)
print(base_2_filter, file=f)

msg_prepended = tf.pad(msg[:, :, 0], paddings=tf.constant([[0, 0], [window-1, 0]]))
print('msg_prepended', file=f)
print(msg_prepended, file=f)

conv_msg_input = tf.cast(msg_prepended[:,:,None], dtype=tf.float32)
print('conv_msg_input', file=f)
print(conv_msg_input, file=f)

state_sequence = tf.cast(tf.nn.conv1d(conv_msg_input, base_2_filter, stride=1, padding='VALID'), dtype=tf.int32)[:,:,0]
print('state_sequence', file=f)
print(state_sequence, file=f)
print('first binary sequence', file=f)
print(msg_prepended[0].numpy().tolist(), file=f)
print('first state sequence', file=f)
print(state_sequence[0].numpy().tolist(), file=f)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@abhmul ,
I was able to run the code without any issues on TF v2.7. Please find the gist [1](https://colab.research.google.com/gist/tilakrayal/fb0f066ca7955cdc7a8f88b1cb2eee5f/53489-cpu.ipynb) and [2](https://colab.research.google.com/gist/tilakrayal/a83c1ac1f61891dad6545c11f9a963fa/53489-gpu.ipynb) of it here.
