### ISSUE TITLE
ImportError: DLL load failed while importing trace: The specified module could not be found.

### ISSUE THREAD

**Issue by hasinonpc** [tensorflow/tensorflow#53482]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-045H3MF
System Manufacturer	LENOVO
System Model	80XL
System Type	x64-based PC
System SKU	LENOVO_MT_80XL_BU_idea_FM_ideapad 320-15IKB
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2712 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO 4WCN47WW, 6/30/2020
SMBIOS Version	3.0
Embedded Controller Version	1.47
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Product	LNVNB161216
BaseBoard Version	NO DPK
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1151"
User Name	DESKTOP-045H3MF\LENOVO
Time Zone	Bangladesh Standard Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.88 GB
Available Physical Memory	1.69 GB
Total Virtual Memory	14.9 GB
Available Virtual Memory	5.98 GB
Page File Space	7.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
###import requests
import cartopy.crs as ccrs 
import matplotlib.pyplot as plt
import os
from PIL import Image
import random
import pyttsx3
engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
engine.setProperty('voices',voices[0].id)

def Speak(audio):
    print(" ")
    print(f": {audio}")
    engine.say(audio)
    engine.runAndWait()
    print(" ")

Api_Key = "FxwAGG1PWubblMdnFrHZAgHy0KdT86QPDRwLz2Is"

def NasaNews(Date):

    Speak("Extracting Data From Nasa . ")

    Url = "https://api.nasa.gov/planetary/apod?api_key=" + str(Api_Key)

    Params = {'date':str(Date)}
    
    r = requests.get(Url,params = Params)

    Data = r.json()

    Info = Data['explanation']

    Title = Data['title']

    Image_Url = Data['url']

    Image_r = requests.get(Image_Url)

    FileName = str(Date) + '.jpg'

    with open(FileName,'wb') as f:

        f.write(Image_r.content)

    Path_1 = "C:\\AI\\" + str(FileName)

    Path_2 = "C:\\AI\\DataBase\\NasaDataBase\\" + str(FileName)

    os.rename(Path_1, Path_2)

    img = Image.open(Path_2)

    img.show()

    Speak(f"Title : {Title}")
    Speak(f"According To Nasa : {Info}")

def Summary(Boby):

    list__ = ('2','3','4','5')

    value = random.choice(list__)

    path = "C:\\AI\\DataBase\\NasaDataBase\\ImageUsed\\" + str(value) + ".jpg"

    os.startfile(path)

    name = str(Boby)

    url = "https://hubblesite.org/api/v3/glossary/" + str(name)

    r = requests.get(url)

    Data = r.json()

    if len(Data) != 0:
        retur =  Data['definition']

        Speak(f"According To The Nasa : {retur}")

    else:

        Speak("No Data Available , Try Again Later!")
def MarsImage():

    name = 'curiosity' 

    date = '2020-12-3'

    Api_ = str(Api_Key)

    url = f"https://api.nasa.gov/mars-photos/api/v1/rovers/{name}/photos?earth_date={date}&api_key={Api_}"
    r = requests.get(url)

    Data = r.json()

    Photos = Data['photos'][:20]

    try:

        for index , photo in enumerate(Photos):

            camera = photo['camera']

            rover = photo['rover']

            rover_name = rover['name']

            camera_name = camera['name']

            full_camera_name = camera['full_name']

            date_of_photo = photo['earth_date']

            img_url = photo['img_src']

            p = requests.get(img_url)

            img = f'{index}.jpg'

            with open(img,'wb') as file:
                file.write(p.content)

            Path_1 = "C:\\AI\\" + str(img)

            Path_2 = "C:\\AI\\DataBase\\NasaDataBase\\MarsImage\\" + str(img)

            os.rename(Path_1,Path_2)

            os.startfile(Path_2)

            Speak(f"This Image Was Captured With : {full_camera_name}")

            Speak(f"This Image Was Captured On : {date_of_photo}")

    except:
        Speak("There IS An Error!")
def IssTracker():

    url = "http://api.open-notify.org/iss-now.json"

    r = requests.get(url)

    Data = r.json()

    dt = Data['timestamp']

    lat = Data['iss_position']['latitude']

    lon = Data['iss_position']['longitude']

    print(f"Time And Date : {dt}")
    print(f"Latitude : {lat}")
    print(f"Longitude : {lon}")

    plt.figure(figsize=(10,8))

    ax = plt.axes(projection = ccrs.PlateCarree())

    ax.stock_img()

    plt.scatter(float(lon),float(lat),color = 'blue' , marker= 'o')

    plt.show()
IssTracker() 
   ###

PS C:\AI> pip install numpy
Collecting numpy
  Using cached numpy-1.21.4-cp310-cp310-win_amd64.whl (14.0 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.4
PS C:\AI> & C:/Users/LENOVO/AppData/Local/Programs/Python/Python310/python.exe c:/AI/Nasa.py
Traceback (most recent call last):
  File "c:\AI\Nasa.py", line 2, in <module>
    import cartopy.crs as ccrs
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\cartopy\__init__.py", line 109, in <module>
    import cartopy.crs
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\cartopy\crs.py", line 26, in <module>
    import cartopy.trace
ImportError: DLL load failed while importing trace: The specified module could not be found.
PS C:\AI>

**Comment by sushreebarsa** [comment]
@hasinonpc 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
