### ISSUE TITLE
No way to unstack ragged tensors

### ISSUE THREAD

**Issue by ablanch5** [tensorflow/tensorflow#53486]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: NO
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: COLAB
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: N/A
-   **TensorFlow installed from (source or binary)**: N/A
-   **TensorFlow version (use command below)**: latest COLAB
-   **Python version**: latest COLAB
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: COLAB
-   **CUDA/cuDNN version**: COLAB
-   **GPU model and memory**: COLAB
-   **Exact command to reproduce**:

### Describe the problem
I want to be able to unstack a ragged tensor so I can pass the unstacked tensors to a function with multiple inputs.

Here is some example code of what I want to do.

```
import tensorflow as tf
X = tf.ragged.constant([[0, 1, 2], [0, 1]])

def sum_func(x1,x2):
  return tf.reduce_sum(x1) + tf.reduce_sum(x2)

sum_func(tf.unstack(X))
```

> ValueError: TypeError: object of type 'RaggedTensor' has no len()

Please note I know there are other ways to achieve the above with this function but this is just a minimal example

**Comment by Saduf2019** [comment]
@ablanch5 
Ragged tensor do not have "len" defined for them because of their dynamic shape capabilities, hence tf.unstack  does not work with ragged tensors.
Kindly open this in discussion forum in case of further queries, and move this to closed status.

**Comment by ablanch5** [comment]
Hey thanks for the reply! I realize the reason for the error but i was making a feature request. You're saying I should make features requests in discussion forum? Or that this is just not possible to be implemented?

**Comment by Saduf2019** [comment]
@ablanch5 
But its understood that with a none dimension you cant stack or unstack, it is like adding two tensors with none dimension, you cannot do that because you don't know if its broad-castable.
as requested you can open this in discussion forum for more information and move this to closed status. If you still want a feature request please feel free to create a PR.
