### ISSUE TITLE
Include libcurl into the bazel build

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5349]
Currently tensorflow serving project will build gcs_file_system target which may fail, with the following message:
```
ERROR: /home/heliangliang/work/tensorflow/tensorflow/core/platform/cloud/BUILD:49:1: C++ compilation of rule '//tensorflow/core/platform/cloud:http_request' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers ... (remaining 100 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./tensorflow/core/platform/cloud/http_request.h:22:0,
                 from tensorflow/core/platform/cloud/http_request.cc:16:
tensorflow/core/platform/cloud/http_request.cc: In member function 'virtual tensorflow::Status tensorflow::HttpRequest::Init()':
tensorflow/core/platform/cloud/http_request.cc:219:30: error: 'CURL_HTTP_VERSION_2_0' was not declared in this scope
                              CURL_HTTP_VERSION_2_0);
```

The reason is gcs_file_system dependens on libcurl 7.33.0+, and this is higher than the default package versions of many Linux distros.

It's better to include libcurl as bazel build library instead of using the system one.

**Comment by aselle** [comment]
For Linux we are supporting Ubuntu 14   and newer which has 7.35.  RHEL 6 currently does have an older version at 7.19, but that is 6 years old at this point and ending its production phase 1. We don't generally promise to make changes to support older Linux systems, but maybe this is an easy change.   @jart could you take this?

**Comment by jart** [comment]
I would love to integrate libcurl into the bazel build. I'll do this at some point in the next two months.

**Comment by aselle** [comment]
Thanks @jart and thanks for the suggestion @llhe

**Comment by gregfrank** [comment]
Even RHEL7 / Centos7 only has libcurl 7.29 as default.  As a result, building from r0.11 source and selecting GCP support during configure will fail when building the pip package.

**Comment by skavulya** [comment]
This feature would be very helpful. I had to manually install the latest version of libcurl on Centos 7, and compile with `bazel build --cxxopt="-I/<path_to_latest_curl_include_dir>" -c opt tensorflow_serving/...` to get it to work.

**Comment by jart** [comment]
I've written up a change internally that makes Bazel build libcurl from scratch. This is one of the most challenging vendor libraries we've dealt with so far. libcurl has a pretty large set of configure defines. We're getting more eyes on the BUILD file we've written to make sure we're doing it correctly. I can't make any promises this is going to work. But with a little bit of luck, this change might be good enough to be merged. Then no one should hopefully need to worry about curl again.

**Comment by llhe** [comment]
@jart What about using `mkdir tmp && cp to tmp && pushd tmp && configure --prefix=target-bazel-out-path && make && make install && popd && rm -rf tmp`? It's much easier to make the integration.

**Comment by jart** [comment]
I wish it were that simple @llhe. The problem with building it that way inside a genrule is that Bazel wouldn't be building it anymore. It would be delegating the build to autotools, m4, make, libtool and friends. That may or may not work depending on how the system is configured. So we usually end up writing our own build code for these things, e.g. [jpeg.BUILD](https://github.com/tensorflow/tensorflow/blob/master/third_party/jpeg.BUILD), with tightly controlled versioning and configuration. That way builds should be guaranteed to work on the systems we support, so long as Bazel works, and the only tool/library the user needs to worry about installing is Bazel.

**Comment by GregBowyer** [comment]
Can I see your build file, I am struggling with libcurl myself

**Comment by llhe** [comment]
@GregBowyer Here is an example that I use to build another 3rd party poco library which is also `configure-make-make install` pattern, hope this can help:
```py
POCO_HEADERS = [                                                                
        "include/Poco/Process.h",                                               
        "include/Poco/MemoryStream.h", 
        ......
]
POCO_LIBRARIES = [                                                              
        "lib/libPocoNetSSL.a",                                                  
        "lib/libPocoCrypto.a",                                                  
        "lib/libPocoNet.a",                                                     
        "lib/libPocoUtil.a",                                                    
        "lib/libPocoXML.a",                                                     
        "lib/libPocoJSON.a",                                                    
        "lib/libPocoFoundation.a",                                              
]                                                                               
                                                                                
genrule(                                                                        
    name = 'make',                                                              
    srcs = glob(                                                                
        ["**/*"],                                                               
        exclude = ["**/*.psd", "**/*.txt"], # supress bazel complain            
    ),                                                                          
    outs = POCO_HEADERS + POCO_LIBRARIES,                                       
    cmd = "pushd $$(dirname $(location configure)); workdir=$$(mktemp -d -t poco-build.XXXXXXXXXX); cp -aL * $$workdir; pushd $$workdir; ./configure --static --cflags='-fPIC -Wl,-Bdynamic -lpthread -Wl,-Bdynamic -ldl -Wl,-Bdynamic -lrt' --omit=ApacheConnector,Data,MongoDB,PageCompiler,CppParser,CppUnit,NetSSL_Win,PocoDoc,PDF,ProGen,SevenZip,Zip --no-sharedmemory --no-sharedlibs --no-fpenvironment --no-tests --no-samples --prefix=$$workdir/install; make -j10; make install; popd; popd; cp -a $$workdir/install/* $(@D); rm -rf $$workdir",
)                                                                               
                                                                                
cc_library(                                                                     
    name = "poco",                                                              
    hdrs = POCO_HEADERS,                                                        
    srcs = POCO_LIBRARIES,                                                      
    includes = ["include"],                                                     
    visibility = ["//visibility:public"],                                       
    linkopts = [                                                                
        "-lssl",                                                                
        "-lcrypto",                                                             
    ],                                                                          
) 
```

**Comment by gunan** [comment]
Would adding libcurl dependency work in windows?
Or does windows make things infeasible here?

**Comment by jart** [comment]
I strongly recommend against running configure, make, and make install inside a genrule.

**Comment by llhe** [comment]
@gunan @jart I'm not suggesting to push this into trunk, but provides a quick hacking solution for whom has this problem now. Of course, comment out the gcs rule is much more easier.

We use this approach internally because the library we need to integrate is **really nasty** to convert to normal Bazel rule and we don't want to invest too much time on this because we don't use bazel except tensorflow.

**Comment by GregBowyer** [comment]
yeah I am not running make in my BUILD

**Comment by jart** [comment]
This should be fixed now. See https://github.com/yifeif/tensorflow/commit/bb890ea5fa4c8a2100a295e93c5bf37b3c88b55a. So happy I was able to help you guys! Thank you for your patience.

**Comment by jart** [comment]
Whoops, re-opening because that commit hasn't been merged into master yet.
