### ISSUE TITLE
Range of parameters while converting to TFLite models

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#53497]
Hi,

We are trying to apply an INT8 TFLite model to Arm NPU; however, there are some requirements in the operations. For example, convolution must satisfy the (requirements below)[https://github.com/ARM-software/ethos-n-driver-stack/blob/master/SUPPORTED.md#convolution-2d]:
```
I*W/O must be between 2.33e-10 and 1, where:
I is the input quantization scale.
W is the weight quantization scale.
O is the output quantization scale. 
```

As a result, is it possible to set the values of input, weight, and output quantization scales in convolution and depthwise convolution layers while converting the pb files to INT8 TFLite models?

**Comment by tilakrayal** [comment]
@Rahn80643 ,
Please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/48879) and the [link](https://www.tensorflow.org/lite/performance/quantization_spec) for more information on quantization scales.It helps.Thanks!

**Comment by Rahn80643** [comment]
Hi,
The [issue](https://github.com/tensorflow/tensorflow/issues/48879) mentions how to modify the weight values in tflite models, and the [link](https://www.tensorflow.org/lite/performance/quantization_spec) is about the specification of the scales of operations. 

The following steps are how we convert pb files to tflite files:
1. load the pb file and set the input and output node name as a tflite converter
2. set the parameter "optimization" as "tf.lite.Optimize.DEFAULT"
3. set the parameter "target_spec.supported_ops" as "tf.lite.OpsSet.TFLITE_BUILTINS_INT8"
4. set the parameter "inference_input_type as "tf.int8"
5. set the parameter "inference_output_type" as "tf.int8"

But we want to know is it possible to control the range of the scale values for the input and output of convolution and depthwise convolution layers.

**Comment by tilakrayal** [comment]
@Rahn80643 ,
Kindly open a tf discussion forum issue for this as it is not a bug or feature request. There is a big community to support and learn from your questions.Thanks!
