### ISSUE TITLE
Error occur: undefined reference when trying to ndk-build to run tflite example

### ISSUE THREAD

**Issue by woojinn8** [tensorflow/tensorflow#53491]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: RK3399 embedded board
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.7
- Python version: 3.7
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): NDK r21

---

**Describe the problem**

I'm trying to NDK build simple tflite example code.

When I build, this error is occured.

```error: undefined reference to 'tflite::InterpreterBuilder::operator()(std::__1::unique_ptr<tflite::Interpreter, std::__1::default_delete<tflite::Interpreter> >*)'```

---

**Provide the exact sequence of commands / steps that you executed before running into the problem**

First, I build tflite. I type command ```bazel build --config=elinux_aarch64 -c opt //tensorflow/lite:libtensorflowlite.so``` and libtensorflow.so file is created.

And Secondely, I prepare tflite code.
```C
  // Load model
  std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile(model_file.c_str());

  // Build the interpreter
  tflite::ops::builtin::BuiltinOpResolver resolver;
  std::unique_ptr<tflite::Interpreter> interpreter;
  tflite::InterpreterBuilder(*model, resolver)(&interpreter);    <<<<<<----- This is where the error occurs. 

  interpreter->SetNumThreads(num_thread);
  interpreter->AllocateTensors();

  // Set input
  float* input = interpreter->typed_input_tensor<float>(0);   
  for(int y=0; y<height; y++)
  {
    for(int x=0; x<width; x++)
    {
      *(input + y*width + x) = ((float)img.data[3*y*width + 3*x]);
      *(input + y*width + x + 1 * height*width) = ((float)img.data[3*y*width + 3*x + 1]);
      *(input + y*width + x + 2 * height*width) = ((float)img.data[3*y*width + 3*x + 2]);
    }
  }

  TfLiteTensor* output_tensor = nullptr;
  interpreter->Invoke();
  output_tensor = interpreter->tensor(interpreter->outputs()[0]);
  printf("Elapsed: %f\n\n",sec.count()*1000);
```

and then, I link the libtensorflow.so file.

I add two line in my Android.mk

```
TFLITE_INSTALL_PATH := packages/apps/3rdparty/tflite
LOCAL_LDLIBS:= $(TFLITE_INSTALL_PATH)/lib_android/libtensorflowlite.so
```

---

What I tried to solve the error is followed

1) change ndk version
Now I'm using ndk ver 21, and I try another version(13, 15, 18) too.

2) re-build tensorflow lite
I add option such as --config=monolithic, --config=dynamic_kernels and --cxxopt=--std=c++14 And I also change option --config=elinux_aarch64 to --config=android_arm64

In this situation, Is there anything to check? I don't know what to do anymore. Is this problem of Android.mk setting? or build bazel setting?

---

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@woojinn8 Could you please have a look at the similar [issue1](https://github.com/tensorflow/tensorflow/issues/39118) , [issue2 ](https://stackoverflow.com/questions/64805224/undefined-references-when-trying-to-use-tensorflow-lite-c-api-built-for-arm64-w)and let us know if it helps?Thanks!

**Comment by woojinn8** [comment]
@sushreebarsa Thank you for reply. Unfortunately both issue are not useful. I'd better to check my configuration again.

**Comment by ruyanyinian** [comment]
@woojinn8 Did you finally figure this issues out? I got in the same trouble.

**Comment by ruyanyinian** [comment]
@woojinn8 hi，I finally figured this out

**Comment by mohantym** [comment]
@ruyanyinian ! Could you share your work around for this issue. Thank you!
