### ISSUE TITLE
tf.random is broken on macOS Monterey 12.1

### ISSUE THREAD

**Issue by ker2x** [tensorflow/tensorflow#53505]
On a Mac M1 with Tensorflow-metal 0.3.0 and Tensorflow-2.7.0

this code used to generate different sequences but now generate the same sequence : 
```
import tensorflow as tf

x = tf.random.uniform((10,))
y = tf.random.uniform((10,))

tf.print(x)
tf.print(y)
[0.178906798 0.8810848 0.384304762 ... 0.162458301 0.64780426 0.0123682022]
[0.178906798 0.8810848 0.384304762 ... 0.162458301 0.64780426 0.0123682022]
```

It works on CPU, it works on collab, it works on cuda, it used to works on MacOS 12.0.

I tried many workaround like using a generator, but generator can't be used on M1 GPU, eg  : 
```
randomgen = tf.random.Generator.from_non_deterministic_state()
#%%
for _ in range(10):
        g2 = tf.random.get_global_generator()
        x = g2.uniform((10,),(1,2))
        y = g2.uniform((10,),(3,4))
        tf.print(x)
        tf.print(y)
```

```
NotFoundError: No registered 'RngReadAndSkip' OpKernel for 'GPU' devices compatible with node {{node RngReadAndSkip}}
	.  Registered:  device='CPU'
 [Op:RngReadAndSkip]
```

other people reported other problems with various code that used to works in 12.0 but the problems are likely to be related to randomness.
a broken random is obviously bad in machine learning ^^

I opened an apple feedback as well as a discussion : https://developer.apple.com/forums/thread/697057?answerId=699100022#699100022

**Comment by tilakrayal** [comment]
@ker2x ,
We don't see any issue while running the given code in colab.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/28dd551b99618132c68dc3f85dfde981/untitled149.ipynb). Since its not a bug from TF end and you also mentioned that the issue is with M1, Can you try posting your question in this [tf-metal ](https://developer.apple.com/forums/tags/tensorflow-metal)developer forum of Apple? Thanks!

**Comment by ker2x** [comment]
Yes, as mentioned in the bug report, I already posted it on tf-metal dev forum. I wasn't sure if it had its place here, couldn't find any GitHub for Tensorflow-metal. Feel free to close this request if it's off topic. 

Thank you for your answer.

**Comment by tilakrayal** [comment]
@ker2x ,
Can you please feel free to move this issue to closed status.Thanks!

**Comment by ker2x** [comment]
okay closing :)
