### ISSUE TITLE
The TensorFlow contrib module will not be included in TensorFlow 2.0.

### ISSUE THREAD

**Issue by kusumlata123** [tensorflow/tensorflow#53500]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W1221 15:55:51.620390 140392233633600 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

 and i checked that version of tensorflow in my system is 1.15

**Comment by tilakrayal** [comment]
@kusumlata123 ,
Please take a look at this issue [link](https://github.com/tensorflow/tensorflow/issues/47204) and the doc [link](https://www.tensorflow.org/guide/migrate) which has more info on tf.contrib.It helps.Thanks!

**Comment by deepak52** [comment]
File "C:\tensorflow1\models\research\object_detection\train.py", line 51, in <module>
    from object_detection.builders import dataset_builder
  File "C:\Users\deepaksabu\AppData\Roaming\Python\Python311\site-packages\object_detection\builders\dataset_builder.py", line 27, in <module>
    from object_detection.data_decoders import tf_example_decoder
  File "C:\Users\deepaksabu\AppData\Roaming\Python\Python311\site-packages\object_detection\data_decoders\tf_example_decoder.py", line 27, in <module>
    slim_example_decoder = tf.contrib.slim.tfexample_decoder
                           ^^^^^^^^^^
AttributeError: module 'tensorflow' has no attribute 'contrib'
