### ISSUE TITLE
Installing Tensor flow on multiple machines (on GCP).

### ISSUE THREAD

**Issue by sanketkadge1** [tensorflow/tensorflow#5351]
i am trying to install tensorflow on two machines(2 instances on Google Cloud Platform) how i can do that?
or it is not supported only thing is you can write programs in tensorflow in distributed manner.

**Comment by aselle** [comment]
Please re-ask this question on StackOverflow which is a better forum for asking questions about how to use TensorFlow. GitHub in mainly for bugs and problems. Thanks!
