### ISSUE TITLE
[TF:TRT]How to write my input_fn when I conver my tf model to trt? 

### ISSUE THREAD

**Issue by GuoGuiRong** [tensorflow/tensorflow#53520]
use nvcr.io/nvidia/tensorflow:19.12-tf2-py3 in docker
my model is

max_batch_size: 512
input [{
	name: "dense_input"
	data_type: TYPE_FP32
	format: FORMAT_NONE
	dims: [-1]
	is_shape_tensor: false
	allow_ragged_batch: false
}, {
	name: "sparse_ids_input"
	data_type: TYPE_INT32
	format: FORMAT_NONE
	dims: [-1]
	is_shape_tensor: false
	allow_ragged_batch: false
}, {
	name: "seq_input"
	data_type: TYPE_INT32
	format: FORMAT_NONE
	dims: [-1, -1]
	is_shape_tensor: false
	allow_ragged_batch: false
}, {
	name: "sparse_wgt_input"
	data_type: TYPE_FP32
	format: FORMAT_NONE
	dims: [-1]
	is_shape_tensor: false
	allow_ragged_batch: false
}]
output: [{
	name: "tf_op_layer_Sigmoid"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_pctr"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_dapan_action"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_pcvr_ctr"
	data_type: TYPE_FP32
	dims: [2]
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_pctcvr_1"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_delay_time"
	data_type: TYPE_FP32
	dims: [2]
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_pcvr"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_pctcvr"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}, {
	name: "tf_op_layer_Sigmoid_1"
	data_type: TYPE_FP32
	dims: [1]
	reshape: {
		shape: []
	}
	label_filename: ""
	is_shape_tensor: false
}]
I want to know how to write my input_fn when I conver it to trt, my code is blew but not ok :

# -*- coding: utf-8 -*-
import os

from tensorflow import make_tensor_proto
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import tensorflow as tf
import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL'] = "3"

if __name__ == "__main__":
    input_saved_model_dir = "./TF-recommend/1634309909"
    output_saved_model_dir = "./TF-recommend-trt/"

    conversion_params = trt.DEFAULT_TRT_CONVERSION_PARAMS
    conversion_params = conversion_params._replace(
        max_workspace_size_bytes=(1 << 32))
    conversion_params = conversion_params._replace(precision_mode="FP16")
    conversion_params = conversion_params._replace(
        maximum_cached_engines=100)

    converter = trt.TrtGraphConverterV2(
        input_saved_model_dir=input_saved_model_dir,
        conversion_params=conversion_params)

    converter.convert()

    def my_input_fn():
        dense_input = np.ones([438]).astype('float32')
        sparse_ids_input = np.ones([79]).astype('int32')
        sparse_wgt_input = np.ones([79]).astype('float32')

        req = {
            "dense_input": make_tensor_proto(dense_input, shape=(dense_input.shape)),
            "sparse_ids_input": make_tensor_proto(sparse_ids_input, shape=(sparse_ids_input.shape)),
            "sparse_wgt_input": make_tensor_proto(sparse_wgt_input, shape=(sparse_wgt_input.shape)),
        }
        yield req

    converter.build(input_fn=my_input_fn)
    converter.save(output_saved_model_dir)

**Comment by Saduf2019** [comment]
@GuoGuiRong 
Please refer t below links: as this is not a feat req or a bug please create this issue in discussion forum.
[link](https://github.com/tensorflow/tensorrt)
[link1](https://blog.tensorflow.org/2021/01/leveraging-tensorflow-tensorrt-integration.html),
[link2](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html)

**Comment by GuoGuiRong** [comment]
```
Traceback (most recent call last):
  File "/Users/guirong/venv/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 5 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource.

```

IS this a bug that hasn't been solved until now?

**Comment by Saduf2019** [comment]
@GuoGuiRong 
Can you please run your code in google colab and share a gist as it is not indented, so we can help you.
