### ISSUE TITLE
line 123 of build_pip_package_with_cmake.sh to be adapted

### ISSUE THREAD

**Issue by WillemD61** [tensorflow/tensorflow#53522]
**System information**
- Linux Ubuntu 20.04 on WSL2
- Cmake 3.16
- Host system with i5-10210u processor, 4 cores

Line 123 of the script as shown on
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh#L123
causes the script to crash as result of not limiting number of processors. 
Error message: ERRO[0169] error waiting for container: invalid character ‘u’ looking for beginning of value

In a similar way, running the cmake build command directly on the Linux host (i.e. without using a docker container) causes compiler errors if the number of processors (4 in this case) is not specified correctly. (need to use "cmake --build . -j 4" as correct command)

If ${BUILD_NUM_JOBS} is replaced by the actual number of processors/cores available (in my case 4) then both the script to create the pip wheel as well as the basic cmake command perform as desired and complete without errors.

See [this thread](https://discuss.tensorflow.org/t/instructions-for-cmake-on-raspberry-pi-zero-are-inaccurate/6610/12) for further details.

**Comment by terryheo** [comment]
You can easily override the value BUILD_NUM_JOBS as the following.

```
BUILD_NUM_JOBS=1 build_pip_package_with_cmake.sh 
```
or
```
export BUILD_NUM_JOBS=1
build_pip_package_with_cmake.sh 
```

**Comment by WillemD61** [comment]
> You can easily override the value BUILD_NUM_JOBS as the following.
> 
> ```
> BUILD_NUM_JOBS=1 build_pip_package_with_cmake.sh 
> ```
> 
> or
> 
> ```
> export BUILD_NUM_JOBS=1
> build_pip_package_with_cmake.sh 
> ```

True, but without documenting this problem, bringing it to the user attention or resolving it in another way, many more users will run into the same issue. Just mentioning a possible solution here as a reply does not really prevent this from happening in the future and will leave the build script as vulnerable as before.
