### ISSUE TITLE
Type 'INT8' is not supported by tile.Node number 92 (TILE) failed to invoke

### ISSUE THREAD

**Issue by pkarimib** [tensorflow/tensorflow#53525]
### 1. System information

- OS Platform and Distribution: MacOS 10.15.7
- TensorFlow installation (pip package or built from source): pip3
- TensorFlow library (version): 2.7.0

### 2. Code

Code to run the inference on the int8 model (change `np.int8` to `np.float32` in you want to try float16 model):

```
import numpy as np
import tensorflow as tf

# Load the TFLite model and allocate tensors.
generator_interpreter = tf.lite.Interpreter(model_path="kp_detector.tflite")
generator_interpreter.allocate_tensors()

# Get input and output tensors.
input_details = generator_interpreter.get_input_details()
output_details = generator_interpreter.get_output_details()

for i in range(0, len(input_details)):
    # Test the model on random input data.
    input_shape = input_details[i]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.int8)
    generator_interpreter.set_tensor(input_details[i]['index'], input_data)

generator_interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = generator_interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

#### 3. Failure after conversion
I have converted a `.pb` model to `.tflite` with float16 and int8 conversions. The inference is correct on float16, but not the int8. Let me know if you want me to provide the models.

**Comment by sushreebarsa** [comment]
@pkarimib 
In order to reproduce the issue reported here, could you please provide the complete code(models) that you are using. Thanks!

**Comment by pkarimib** [comment]
@sushreebarsa 
Thanks for your response. The code is in [this link](https://drive.google.com/file/d/1ZpWAyFw-Zk8b5CwGy4-kX7_DOidme60K/view?usp=sharing). 

Run the following to test the quantized model:
```
python3 test_quantized_model.py 
```

To build the int8 module, please run:
```
python3 build.py --int8 --module generator 
```

Please let me know if you need anything else.

**Comment by sachinprasadhs** [comment]
What is the difference in accuracy you are getting from float16 to int8?.
Also, check the model performance using the tools [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks#accuracy--correctness).

**Comment by pkarimib** [comment]
I have not been successful in running the model so I could measure the accuracy. The code exits with `failed to invoke` error.

**Comment by mohantym** [comment]
Hi @pkarimib ! The notebook in the above [comment](https://github.com/tensorflow/tensorflow/issues/53525#issuecomment-1000885285) is not accessible any more. Could you please share a minimal stand alone code( as colab gist) including your model file , conversion and inference to help expedite the issue? Thanks!
