### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.keras.applications'

### ISSUE THREAD

**Issue by hackermondev** [tensorflow/tensorflow#53538]
<em>Please make sure that this is an issue related to keras.
tag:keras_template</em>

I am running a script that is trying to import this:

``import tensorflow.python.keras.applications``

but it gives the bellow error:

```ModuleNotFoundError: No module named 'tensorflow.python.keras.applications'```

My TensorFlow version is 2.8.0 and Keras version is 2.8.0.
I'm trying to train an object detection model but I keep getting that error.

Here is my pip list: https://pastebin.com/xjfTW28W

**Comment by sushreebarsa** [comment]
@hackermondev I was able to import this  `import tensorflow.python.keras.applications` on colab.
 Could you please find the gist [here](https://colab.sandbox.google.com/gist/sushreebarsa/7205e420b464689776e57e4a387e3fbe/53538.ipynb#scrollTo=zdITO1jmn9kH) for reference and confirm the same?Thank you!

**Comment by hackermondev** [comment]
I was able to fix the problem by uninstalling TensorFlow and installing it back.

```
pip uninstall tensorflow
pip install tensorflow
```

I'm not sure why I had to do this though.
