### ISSUE TITLE
[PluggableDevice] TF_RESOURCE is not deserializable since 2.7

### ISSUE THREAD

**Issue by PatriceVignola** [tensorflow/tensorflow#53531]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.9

**Describe the current behavior**
When calling `TF_TensorData` in `TF >= 2.7.0` on a tensor containing a `TF_RESOURCE`, the returned data is the resource handle itself instead of being a string serialization of it. This seems to have been caused by [this commit](https://github.com/tensorflow/tensorflow/commit/6f8c6dbdf7bf9155a931aaefb77fdbcff3b06e16) which removed the `TF_RESOURCE` serialization logic from TF 2.

**Describe the expected behavior**
Calling `TF_TensorData` on a tensor containing a `TF_RESOURCE` should return some kind of cross-abi serialization of the resource handle or the resource proto. For example, reverting [this commit](https://github.com/tensorflow/tensorflow/commit/6f8c6dbdf7bf9155a931aaefb77fdbcff3b06e16) produces the expected behavior from a plugin standpoint.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): I can if needed
- Briefly describe your candidate solution(if contributing): 

**Standalone code to reproduce the issue**

```cpp
void* tensor_data = TF_TensorData(tensor);
size_t tensor_size = TF_TensorByteSize(tensor)
std::string serialized_data(reinterpret_cast<const char*>(tensor_data), tensor_size);
auto resource_handle = std::make_shared<tensorflow::ResourceHandleProto>();

if (!resource_handle->ParseFromString(serialized_data)) {
  std::abort();
}
```

**Comment by sushreebarsa** [comment]
@PatriceVignola 
In order to expedite the trouble-shooting process,please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by PatriceVignola** [comment]
@sushreebarsa I provided a code snippet above. All this code uses is the TF C API, the STD library and protocol buffers. I want to know how we can deserialize resource tensors from pluggable device code since the 2.7 change that broke it.
