### ISSUE TITLE
First tensorflow operation on numpy or list data takes long time after tf.GradientTape

### ISSUE THREAD

**Issue by geometrikal** [tensorflow/tensorflow#53530]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8.10
- CUDA/cuDNN version: 11.2 | 8.2.4.15-1+cuda11.4
- GPU model and memory: RTX 2080 8GB

**Describe the current behavior**

First tensorflow operation on numpy or list data after `with tf.GradientTape() as ...` takes much longer than subsequent operations, and is dependant on model size

**Describe the expected behavior**

Operation takes the same amount of time as all others. Note that in 2.6.0 both the first operation before, and the first operation after, would take a long time, but in 2.7.0 it is only the first operation after.

**Standalone code to reproduce the issue**

```
import time
import tensorflow as tf
from keras import Input, Model
from keras.layers import Conv2D
import numpy as np


def Backbone(filters):
    x = Input((None, None, 3))
    inp = x
    x = Conv2D(filters=filters, kernel_size=(3, 3), activation='relu')(x)
    x = Conv2D(filters=filters, kernel_size=(3, 3), activation='relu')(x)
    x = Conv2D(filters=filters*2, kernel_size=(3, 3), activation='relu')(x)
    x = Conv2D(filters=filters*2, kernel_size=(3, 3), activation='relu')(x)
    x = Conv2D(filters=filters*4, kernel_size=(3, 3), activation='relu')(x)
    x = Conv2D(filters=filters*4, kernel_size=(3, 3), activation='relu')(x)
    return Model(inp, x)


class TrainModel(tf.keras.Model):
    def __init__(self, *args, **kwargs):
        super(TrainModel, self).__init__(*args, **kwargs)

    def train_step(self, data):
        ts1 = time.time()
        test = tf.reduce_mean([1.0])
        te1 = time.time()

        ts2 = time.time()
        test = tf.reduce_mean([1.0])
        te2 = time.time()

        with tf.GradientTape() as tape:
            res = self(data)
            loss = tf.reduce_mean(res)

        ts3 = time.time()
        test = tf.reduce_mean([1.0])
        # test = tf.reduce_mean(np.random.randint(0, 100, (100, 100)))
        te3 = time.time()

        ts4 = time.time()
        test = tf.reduce_mean([1.0])
        te4 = time.time()

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        print(f"before: {te1 - ts1:.05f}s {te2 - ts2:.05f}s, after: {te3 - ts3:.05f}s {te4 - ts4:.05f}s")

        return {m.name: m.result() for m in self.metrics}


print("filters = 8")
model = Backbone(filters=8)
model = TrainModel(model.inputs, model.outputs)
model.compile(optimizer='adam', run_eagerly=True)
model.fit(x=tf.random.normal([32,224,224,3]),
          batch_size=4,
          epochs=1,
          verbose=0)


print("filters = 32")
model = Backbone(filters=32)
model = TrainModel(model.inputs, model.outputs)
model.compile(optimizer='adam', run_eagerly=True)
model.fit(x=tf.random.normal([32,224,224,3]),
          batch_size=4,
          epochs=1,
          verbose=0)
```

**Other info / logs**

Output from above:

```
filters = 8
before: 0.00079s 0.00030s, after: 0.00082s 0.00050s
before: 0.00042s 0.00034s, after: 0.00125s 0.00040s
before: 0.00051s 0.00038s, after: 0.00115s 0.00029s
before: 0.00039s 0.00035s, after: 0.00121s 0.00029s
before: 0.00039s 0.00035s, after: 0.00124s 0.00035s
before: 0.00039s 0.00040s, after: 0.00127s 0.00041s
before: 0.00048s 0.00041s, after: 0.00125s 0.00030s
before: 0.00048s 0.00047s, after: 0.00123s 0.00040s
filters = 32
before: 0.00075s 0.00049s, after: 0.00600s 0.00043s
before: 0.00049s 0.00042s, after: 0.01974s 0.00063s
before: 0.00057s 0.00043s, after: 0.01396s 0.00036s
before: 0.00043s 0.00036s, after: 0.01337s 0.00040s
before: 0.00052s 0.00040s, after: 0.01359s 0.00040s
before: 0.00062s 0.00039s, after: 0.01354s 0.00041s
before: 0.00054s 0.00042s, after: 0.01387s 0.00043s
before: 0.00060s 0.00062s, after: 0.01415s 0.00073s
```

**Comment by tilakrayal** [comment]
@geometrikal ,
We don't find any issue in the result.Can you please find the gist [here](https://colab.research.google.com/gist/tilakrayal/17aa98d4638ef865f67cc18c401cefb0/untitled153.ipynb).Also please let us know if we are missing anything here.Thanks!

**Comment by geometrikal** [comment]
@tilakrayal Try again in colab using a GPU runtime and you will see the issue

**Comment by geometrikal** [comment]
Further investigation reveals this is not a bug.

The tensoflow operations within `with tf.GradientTape() as tape` are running in parallel with the python code. When a tensorflow operation is performed on numpy or list data, it forces the two to synchronise, meaning that there is a delay while waiting for the previous code to complete. The delay is proportional to the size of the model, as the time taken to call a bigger model is longer.

Hope this helps someone who is trying to time their code in python and wondering why some basic operations take a long time.

![image](https://user-images.githubusercontent.com/1187528/147297608-6ad00bf4-5ab4-4de0-af1a-b01a03957cb2.png)
