### ISSUE TITLE
Improving error message on CUDA version search and specification during build `./configure`

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#53543]
This is from TF git version: 5e8cd1162cc8eeb9cf493d071293a621dcbb51f0 (Dec 22).

When building from sources and when the `./configure` step fails to find a CUDA version with a message below, could it actually report what it found? The message below leaves things ambiguous:

```
Could not find any cuda.h matching version 'CUDA 11' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib/i386-linux-gnu'
        '/lib/x86_64-linux-gnu'
        '/lib32'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/local/cuda'
        '/usr/local/cuda/targets/x86_64-linux/lib'
        '/usr/local/lib'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
```

When it says "Could not find any cuda.h .... matching version ..", could it report what exactly was found and whether it found anything?  From this prompt itself, it isn't immediately clear whether one should enter "11" or "11.2" (with minor version), or "CUDA 11". I do have a `/usr/local/cuda/include/cuda.h` and 

```console
$ cat /usr/local/cuda/include/cuda.h  | grep CUDA_VERSION
#define CUDA_VERSION 11020
 * \defgroup CUDA_VERSION Version Management
/** @} */ /* END CUDA_VERSION */
```

Update: Finally, specifying "11.2" worked.

**Comment by mohantym** [comment]
Hi @bondhugula ! Did the issue get resolved after specifying 11.2 as Cuda Version?

**Comment by bondhugula** [comment]
> Hi @bondhugula ! Did the issue get resolved after specifying 11.2 as Cuda Version?Tested configurations can be found from [here](https://www.tensorflow.org/install/source_windows).

Yes, specifying 11.2 does work. I now see the version table at https://www.tensorflow.org/install/source.

**Comment by mohantym** [comment]
Ok @bondhugula ! Is this issue good to close then?

**Comment by bondhugula** [comment]
> Ok @bondhugula ! Is this issue good to close then?

@mohantym The issue really was on `./configure` not reporting what it actually found and whether it found something. Without that it wouldn't be clear to a user as to why. In any case, this may not be a high priority issue.

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@bondhugula 
We see that you are using the latest tf version, as per this [link]( https://www.tensorflow.org/install/source), the cuda version is already mentioned to be 11.2, hence there is no need to modify error message as its already specified which version is compatible. Kindly move this to closed status as you are able to use TF with the correct cuda version.
