### ISSUE TITLE
I FUCKING HATE TENSORFLOW

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#53549]
I hate Tensorflow.
Yes. I fucking hate Tensorflow.
I created this GitHub account only to open this issue.
Please use Jax or Pytorch or anything else. Don't use Tensorflow.
Don't report me. Don't mad at me. Don't ask me why.
Because I don't want to talk about it anymore.

I. FUCKING. HATE. TENSOR-FUCKING-FLOW.

**Comment by yawn999** [comment]
imagine not having a fucking life

**Comment by yawn999** [comment]
I. FUCKING. HATE. BITCHES. LIKE. YOU.

**Comment by Randy1435** [comment]
I'm sorry you feel about Tensorflow this way, but that doesn't mean you can open an issue and just trashtalk Tensorflow.

**Comment by TruncatedDinosour** [comment]
> I. FUCKING. HATE. BITCHES. LIKE. YOU.

ok boomer

**Comment by yawn999** [comment]
> > I. FUCKING. HATE. BITCHES. LIKE. YOU.
> 
> ok boomer

I believe you miss understand. I hate people like that. I was calling them the bitch

**Comment by Oman395** [comment]
This man is extremely based

**Comment by Oman395** [comment]
> I hate Tensorflow. Yes. I fucking hate Tensorflow. I created this GitHub account only to open this issue. Please use Jax or Pytorch or anything else. Don't use Tensorflow. Don't report me. Don't mad at me. Don't ask me why. Because I don't want to talk about it anymore.
> 
> I. FUCKING. HATE. TENSOR-FUCKING-FLOW.

This man is exceedingly based

**Comment by pokurt** [comment]
The type of people who can't afford a GPU lmaooo

**Comment by KKrisu** [comment]
> Don't ask me why. Because I don't want to talk about it anymore.

very constructive :D

**Comment by louis-she** [comment]
When and why are you so mad at TensorFlow? Installing it?

**Comment by kylejmorris** [comment]
thanks for the feedback LGTM 👍

**Comment by xiBread** [comment]
Ë

**Comment by simpleParadox** [comment]
Why though?

**Comment by TruncatedDinosour** [comment]
> > > I. FUCKING. HATE. BITCHES. LIKE. YOU.
> > 
> > 
> > ok boomer
> 
> I believe you miss understand. I hate people like that. I was calling them the bitch

and I am calling you the boomer, what's your point

**Comment by flobee** [comment]
Mindestens Zwei Quellen für das Abitur

**Comment by GlowingEgg** [comment]
Hell yeah brother

**Comment by vascobarbosa** [comment]
what is this ? reddit ?

**Comment by Dreamedc2015** [comment]
# not a bad opinion

**Comment by sanggusti** [comment]
This is just too funny

**Comment by Dreamedc2015** [comment]
> This is just too funny
its an odd series of events

**Comment by yongen9696** [comment]
Lmao

**Comment by dmadisetti** [comment]
@sushreebarsa Can you lock this? I think this is going viral on twitter, you can only expect more inane comments

**Comment by sollyucko** [comment]
See https://www.reddit.com/r/ProgrammerHumor/comments/rpkxg2/an_honest_guy/ for some explanation

**Comment by sarunmrzn** [comment]
based
