### ISSUE TITLE
tf.data.experimental.save not saving my created tf.data.Dataset 

### ISSUE THREAD

**Issue by Jaydeemourg** [tensorflow/tensorflow#53556]
Tensorflow version: 2.7.0

**Description of the issue:**

i made use of the tf.data.experimental.CsvDataset class to create tf.data.Dataset from my csv data which i want to save with tf.data.experimental.save. upon attempting to save the dataset, the tf.data.experimental.save keeps running endlessly without saving the data. 

`csv data file size: 67108864 bytes`

**Description of the expected behavior:**
tf.data.experimental.save should save the tf.data.Dataset created to a file

**Code to create the tf.data.Dataset and save same to file:**
```
Dataset = tf.data.experimental.CsvDataset(
    my_data.csv', 
    record_defaults=column_types, 
    header=True) # this runs successfully
```

`tf.data.experimental.save(Dataset, "./Dataset", compression='GZIP')` # this runs endlessly without throwing an error nor saving the dataset  to file

**Comment by tilakrayal** [comment]
@Jaydeemourg ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by Jaydeemourg** [comment]
@tilakrayal thanks for your response. i have been able to save the dataset object. 

Another question: Are the `tf.data.experimental.CsvDataset` available [Methods](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset#methods_2) enough to perform data wrangling and transformation usually done using libraries like scipy, numpy and pandas? . for example, i have been trying to perform an equivalent of the below line of pandas code using dataset methods but couldn't find the suitable one for it.   Looking forward to your reply.

```
sum_of_features = {}
for col in features:
    sum_of_features[col] = sum_ofs[col].groupby(["year", "month", "day", "second"]).sum(col)
```

**Comment by tilakrayal** [comment]
@Jaydeemourg ,
Kindly open a tf discussion forum issue for this as it is not a bug or feature request. There is a big community to support and learn from your questions.Thanks!

**Comment by Jaydeemourg** [comment]
@tilakrayal Done. Thanks!!! i am closing this issue
