### ISSUE TITLE
Is it possible to build tensorflow lite C API to .hex file if the microcontroller such as AURIX TC29xT, which doesn't have any operating system 

### ISSUE THREAD

**Issue by lusiliang93** [tensorflow/tensorflow#53558]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): None
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: AURIX TC29xT
- TensorFlow installed from (source or binary): 
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Even if I understand we can build tensorflow lite C API into .so file for microcontroller with linux system, for the application of electrical control unit (ECU), is that possible to build C API into .hex file so as to use the library into the microcontroller without OS?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @lusiliang93 ! Could you check these threads for answer ? Ref [1](https://www.tensorflow.org/lite/microcontrollers), [2](https://towardsdatascience.com/tensorflow-on-arduino-b336f08fa0e9), [3](https://ss64.com/osx/xxd.html) .

**Comment by lusiliang93** [comment]
Thanks for the reference. Based on your references, I guess the model needs to be dumped into hex file. In addition, there is no need to build tensorflow lite api into .so in order to use tensorflow lite C API in such microcontroller. Am I right?

**Comment by mohantym** [comment]
Yes @lusiliang93 ! You can use the lite model  after[ converting ](https://blog.tensorflow.org/2019/11/how-to-get-started-with-machine.html)into header file and importing it as a library . I found a thread from [Mouser electronics](https://www.mouser.com/applications/voice-assistant-tensorflow-lite/) confirming the same.  


![image](https://user-images.githubusercontent.com/86464649/147633036-c7e74415-eb0f-4d68-9a21-d3230247a3b4.png)

**Comment by lusiliang93** [comment]
Many thanks for your answer. I have another question that if tensorflow lite for microcontrollers have C API since the compiler used currently can only compile C scripts. Thanks!

**Comment by mohantym** [comment]
@lusiliang93 ! TFlite library is based on C++ api. Please refer this [guide](https://www.tensorflow.org/lite/microcontrollers/library) to start with. Thank you!

**Comment by lusiliang93** [comment]
Thanks for your answer. A very naive question: If the compiler is C99 compliance only, how much effort will it take to make the microcontroller succeed in running tensorflow lite? Thanks!

**Comment by mohantym** [comment]
Hi @lusiliang93 ! Can you please post on [Forum/](https://discuss.tensorflow.org/) [SO](https://stackoverflow.com/) about this ?
