### ISSUE TITLE
I failed  to install   tflite-model-maker

### ISSUE THREAD

**Issue by chensisi0730** [tensorflow/tensorflow#53550]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Linux Ubuntu 18):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I want to install   tflite-model-maker  ,   i use "pip3 install tflite-model-maker  " or  "pip install tflite-model-maker  " 
print:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 3.3.6 requires pyqt5<5.13; python_version >= "3", which is not installed.
spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
conda 4.10.1 requires ruamel_yaml_conda>=0.11.14, which is not installed.
astroid 2.3.1 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", which is not installed.
spleeter 1.5.0 requires librosa==0.7.2, but you have librosa 0.8.1 which is incompatible.
spleeter 1.5.0 requires pandas==0.25.1, but you have pandas 1.3.5 which is incompatible.
spleeter 1.5.0 requires tensorflow==1.15.0, but you have tensorflow 2.7.0 which is incompatible.
astroid 2.3.1 requires six==1.12, but you have six 1.16.0 which is incompatible.
astroid 2.3.1 requires wrapt==1.11.*, but you have wrapt 1.13.3 which is incompatible.

**Comment by hwaking** [comment]
邮件已收到！

**Comment by mohantym** [comment]
Hi @chensisi0730! Could you try again with 3.8 ? Please make you sure your pip version is updated to latest version and your are using a virtual environment. Attaching relevant threads for reference. Ref [1](https://www.tensorflow.org/lite/guide/model_maker) , [2 ](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_object_detection.ipynb#scrollTo=sr3q-gvm3cI8), [3](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_image_classification.ipynb) .Thank you!

**Comment by chensisi0730** [comment]
> Hi @chensisi0730! Could you try again with Python 3.8 ? Please make you sure your pip version is updated to latest version and you are using a virtual environment. Attaching relevant threads for reference. Ref [1](https://www.tensorflow.org/lite/guide/model_maker) , [2 ](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/model_maker_object_detection.ipynb#scrollTo=sr3q-gvm3cI8), [3](https://colab.sandbox.google.com/gist/mohantym/7cee04a31addf6a5cd4caa8b5b354df2/model-maker-image-classification-tutorial.ipynb) .Thank you!

hi @mohantym  
pip3 install tflite-model-maker   or    conda install tflite-model-maker   ?

**Comment by mohantym** [comment]
Please try with `pip install tflite-model-maker`.

**Comment by Nikhil-Mudgal** [comment]
hey @mohantym, I want to start contributing to tensorflow. I checked some of the issues tagged contribution welcome and good first issue but  they were too confusing at this earlier stage. Can you please suggest some issues I can start on. I will be highly obliged. Thanks

**Comment by chensisi0730** [comment]
> using a virtual environment
Refer to tflite-model-maker  and https://github.com/hoitab/TFLClassify.git ，
 Is it suitable for general picture classification ？

**Comment by mohantym** [comment]
@chensisi0730 ! Above[ thread](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android#6) is a good example if you are looking for end to end deployment in android. You can explore more on android deployment from[ here.](https://www.tensorflow.org/lite/guide/android) .Thank you!

**Comment by mohantym** [comment]
@Nikhil-Mudgal ! Please check this [thread ](https://github.com/freeCodeCamp/how-to-contribute-to-open-source) as a pointer start  contributing in opensource libraries like Tensorflow. You can keep a tab on recurring feature requests ,bugs and pull requests to get an overall idea of Tensorflow ecosystem.  Feel free to visit  TF [forum](https://discuss.tensorflow.org/) for further assistance. Thank you!

**Comment by chensisi0730** [comment]
in vir_env , i can  not use gpu ,   i setup cuda10.0 , but report below: 
Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64::/usr/local/cuda-10.1/lib64:/usr/local/lib

**Comment by mohantym** [comment]
@chensisi0730 ! Could you please confirm your Tensorflow version? You can find suitable Cuda and CudNN version according to your Tensorflow version from [here](https://www.tensorflow.org/install/source#gpu)  . You can also[ set path](https://www.tensorflow.org/install/gpu) your cuda file using below command.  Ref [1](https://stackoverflow.com/questions/64193633/could-not-load-dynamic-library-libcublas-so-10-dlerror-libcublas-so-10-cann), [2](https://forums.developer.nvidia.com/t/tensorflow-fails-to-find-libcudart/154411/7), [3](https://github.com/tensorflow/tensorflow/issues/38578) .Thank you!
```
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\lib64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%
```

**Comment by chensisi0730** [comment]
> @chensisi0730 ! Could you please confirm your Tensorflow version? You can find suitable Cuda and CudNN version according to your Tensorflow version from [here](https://www.tensorflow.org/install/source#gpu) . You can also[ set path](https://www.tensorflow.org/install/gpu) your cuda file using below command. Ref [1](https://stackoverflow.com/questions/64193633/could-not-load-dynamic-library-libcublas-so-10-dlerror-libcublas-so-10-cann), [2](https://forums.developer.nvidia.com/t/tensorflow-fails-to-find-libcudart/154411/7), [3](https://github.com/tensorflow/tensorflow/issues/38578) .Thank you!
> 
> ```
> SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin;%PATH%
> SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\lib64;%PATH%
> SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include;%PATH%
> SET PATH=C:\tools\cuda\bin;%PATH%
> ```
when in  a virtual environment , using  "pip install -q tflite-model-maker " ,  automatic installation tensorflow2.7  , i  can not  select it .

**Comment by mohantym** [comment]
You can install respective Cuda and Cudnn files manually by referring guide from [here](https://www.tensorflow.org/install/gpu#software_requirements) . Please move this issue to closed status if it helped . Thanks!

**Comment by HripsimeS** [comment]
@mohantym Hello. I have a Windows OS and while I am trying to pip install tflite-model-maker
I receive the following error  **tflite-model-maker 0.4.2 requires scann==1.2.6, which is not installed.**

Then I tried to **pip install scann==1.2.6** and got this error
**ERROR: Could not find a version that satisfies the requirement scann==1.2.6 (from versions: none)
ERROR: No matching distribution found for scann==1.2.6**

Do you have tips how to install properly **install tflite-model-maker** on Windows OS ?

**Comment by hakimus2k** [comment]
Same here! Recently with python 3.9, I was unable o insatall because the requirement scann==1.2.6, cannot be isntalled, pip doesnt found it! My pip versios is the lastest.

Befere that, I tryied with Python 3.10, it was a nightmare! it falls in a loop installing "niggtly versions", eating disk space.  I read that it could be caused by the Python version.

Maybe I should try python 3.6?

**Comment by HripsimeS** [comment]
I could install tflite-model-maker with python 3.8 using the following command **pip install tflite-model-maker-nightly**
And training runs good also for mobile models.

**Comment by mohantym** [comment]
@HripsimeS !

Thanks for the confirmation on lite-model-maker nightly. @hakimus2k ! Please check in nightly version. will do some investigation in older version before putting my pointers infront of team for possible cherry picks.

Thank you!

**Comment by hakimus2k** [comment]
Dear @HripsimeS I got the same result with nightly version for pyhton 3.8 and 3.10 on Windows 10.
So now my problem is not the scann version, but PIP is unable to install it. 

I have updated VisualC++ and Installed WSL, ( however I have cygwin and worked fine to compilae th library portaudio), because my next try before desisting, will be to try to compile by hand.   
The last I´ve suffered so much with libraries, was in the 90´s when installing anythin in Solaris or Linux was masoquist exercise of persistence. 
It´s likely that after solving such problem, another will show up. 
By now is a matter of honor due the time I´ve lost.

Any light at the end of the tunnel?

**Comment by hakimus2k** [comment]
I just found a solution. After days trying to installs dependeces of the dependence of the dependece ...and before to desist of TFlite-model-maker, I tried a final thing, It worked in minutes... 

```
git clone https://github.com/tensorflow/examples
cd examples/tensorflow_examples/lite/model_maker/pip_package
pip install -e .
```
The result: 
```
>pip show tflite-model-maker
Name: tflite-model-maker
Version: 0.3.4
Summary: TFLite Model Maker: a model customization library for on-device applications.
Home-page: http://github.com/tensorflow/examples
Author: Google LLC
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\dev\anaconda3\envs\p39\lib\site-packages
Requires: absl-py, Cython, fire, flatbuffers, librosa, lxml, matplotlib, neural-structured-learning, numba, numpy, pillow, PyYAML, sentencepiece, six, tensorflow, tensorflow-addons, tensorflow-datasets, tensorflow-hub, tensorflow-model-optimization, tensorflowjs, tf-models-official, tflite-support, urllib3
Required-by:
```
And that´s it :)

**Comment by stojanni** [comment]
> I just found a solution. After days trying to installs dependeces of the dependence of the dependece ...and before to desist of TFlite-model-maker, I tried a final thing, It worked in minutes...
> 
> ```
> git clone https://github.com/tensorflow/examples
> cd examples/tensorflow_examples/lite/model_maker/pip_package
> pip install -e .
> ```
> 
> The result:
> 
> ```
> >pip show tflite-model-maker
> Name: tflite-model-maker
> Version: 0.3.4
> Summary: TFLite Model Maker: a model customization library for on-device applications.
> Home-page: http://github.com/tensorflow/examples
> Author: Google LLC
> Author-email: packages@tensorflow.org
> License: Apache 2.0
> Location: c:\dev\anaconda3\envs\p39\lib\site-packages
> Requires: absl-py, Cython, fire, flatbuffers, librosa, lxml, matplotlib, neural-structured-learning, numba, numpy, pillow, PyYAML, sentencepiece, six, tensorflow, tensorflow-addons, tensorflow-datasets, tensorflow-hub, tensorflow-model-optimization, tensorflowjs, tf-models-official, tflite-support, urllib3
> Required-by:
> ```
> 
> And that´s it :)

tried it and get numba=0.53 not found error, any ideas?
