### ISSUE TITLE
convert_variables_to_constants_v2 not supper fo embedding?

### ISSUE THREAD

**Issue by GuoGuiRong** [tensorflow/tensorflow#53569]
TensorFlow not supper frozen ConcreteFunction when I convert My deepFM model,
 It's because convert_variables_to_constants_v2 not supper enbedding, I want to know the fix of this issue please?
![image](https://user-images.githubusercontent.com/22836006/147644669-d550ed28-0715-495a-86b4-8b0b4b6d28c6.png)

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.4-gpu
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory:  16G

**Describe the current behavior**
TensorFlow not supper frozen ConcreteFunction when I convert My deepFM model,
 It's because convert_variables_to_constants_v2 not supper enbedding

**Describe the expected behavior**
Conver saved model to froze graph success

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by sushreebarsa** [comment]
@GuoGuiRong 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by GuoGuiRong** [comment]
> @GuoGuiRong In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), Thanks!

ok

**Comment by sushreebarsa** [comment]
@GuoGuiRong We see that you're using older version of `TF v2.3.4`,  could you please try to upgrade to latest stable TF version` 2.7.0` and let us know the outcome?Thanks

**Comment by GuoGuiRong** [comment]
I have fix it use Tensorflow 2.5.0 GPU, this is beasuce my model has some input that not used, A redundant input Cause it conver failed in TensorFlow2.3.0 GPU, I have remove this input and use Tensorflow 2.5.0 success.
So I close this issue, Thanks
