### ISSUE TITLE
GPU sync failed and CUDA_ERROR_ILLEGAL_ADDRESS error

### ISSUE THREAD

**Issue by Jeaninezpp** [tensorflow/tensorflow#53568]
**System information**
- Have I written custom code: **yes**
- OS Platform and Distribution: **ubuntu 20.04**
- Mobile device if the issue happens on mobile device: **No**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version: **Tensorflow-1.4.0**
- Python version: **Python 3.5.2**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **CUDA Version 8.0.61, cuDNN 7.0.5**
- GPU model and memory: **GeForce GTX 1080 Ti with 11G memory**

**Describe the current behavior**
The baseline model is implemented under TensorFlow 1.4.0, so I built my model based on this model. Then I made a docker and ran it in docker. When I train my model, it occasionally shows this error: 
`tensorflow.python.framework.errors_impl.InternalError: GPU sync failed`
and
`2017-11-08 12:24:52.838106: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x51f18f0: CUDA_ERROR_ILLEGAL_ADDRESS`

When using fewer training samples, it seems that there is no problem when training the model once (epoch=1). This problem usually occurs when I train the model 5 times (epoch=5).
When more training samples are used, even if the model is only trained once, this problem will occur more frequently.

I downloaded cudnn7.0.5 according to the [this](https://github.com/tensorflow/tensorflow/issues/14363), but it did not alleviate this problem.
I had tried to restart the docker but it didn't help.
The GPU memory is not exceeded. In the case of successful training, it only takes up 30% of the memory.

At the same time, I found the following error in the system log. (by `sudo journalctl -f`)
`Dec 29 15:02:52 zpp-lab kernel: NVRM: Xid (PCI:0000:17:00): 31, pid=1342831, Ch 00000012, intr 30000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_9 faulted @ 0x7f96_54002000. Fault is of type FAULT_PDE ACCESS_TYPE_ATOMIC
`

Then I run my code with cuda-memcheck, [here](https://www.dropbox.com/s/9zdegkd64kzmtgk/cuda_memcheck.txt?dl=0) is the error info.

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
[https://github.com/fakeppz/demo](https://github.com/fakeppz/demo)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@Jeaninezpp ,
We see that you are using tf version 1.4, 1.x is not actively supported, please update to latest stable v2.7 and let us know if you are using same issue.Please take a look at this link for tested build [configurations](https://www.tensorflow.org/install/source#gpu).Thanks
