### ISSUE TITLE
tensorflow/lite/schema/upgrade_schema.py has a docstring arg out-of-line

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/tensorflow#53566]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/87462bf/tensorflow/lite/schema/upgrade_schema.py#L234

### Clear description

The `(see :schema.fbs).` is an odd syntax, which my custom docstring parser picks up as an argument. What function does it have? - Can it be moved to the line above it?

```python
    def RemapOperatorType(operator_type):
      """Remap operator structs from old names to new names.
      Args:
        operator_type: String representing the builtin operator data type
          string.
        (see :schema.fbs).
      Raises:
        ValueError: When the model has consistency problems.
      Returns:
        Upgraded builtin operator data type as a string.
      """
```

### Parameters defined

No there is a parameter that is defined that doesn't exist, namely `(see :schema.fbs).`.

### Submit a pull request?

Yes I can send a PR

**Comment by tilakrayal** [comment]
@SamuelMarks ,
Please feel free to submit a PR for the requested change or share the link where requested change is to be made

**Comment by SamuelMarks** [comment]
Opened PR

**Comment by tilakrayal** [comment]
@SamuelMarks 
The related PR has been assigned for reviewing and once it is merged this issue will move to closed status.
