### ISSUE TITLE
 No such package '@png_archive//': Traceback (most recent call last):

### ISSUE THREAD

**Issue by Dragonchengllc** [tensorflow/tensorflow#53565]
### 1. System information
Installation Package Version：
CUDA 10.0
CUDNN 7.6
Bazel  0.2
msys  X64
tensorflow 1.13.1
### 2. Code

I get the following error when compiling TENSORFLOW
F:/tensorflow-1.13.1/source/tensorflow/core/platform/default/build_config/BUILD:188:1: no such package '@png_archive//': Traceback (most recent call last):
        File "F:/tensorflow-1.13.1/source/third_party/repo.bzl", line 106
                _apply_patch(ctx, ctx.attr.patch_file)
        File "F:/tensorflow-1.13.1/source/third_party/repo.bzl", line 73, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "F:/tensorflow-1.13.1/source/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "C:/users/cgh/_bazel_llc/guutvuc2/external/png_archive" "-i" "F:/tensorflow-1.13.1/source/third_party/png_fix_rpi.patch"':
Stdout:
Stderr: /usr/bin/bash: patch: 鏈壘鍒板懡浠? and referenced by '//tensorflow/core/platform/default/build_config:png'

Any other info / logs

ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 29.908s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (95 packages loaded, 4625 targets configured)
    Fetching @icu; fetching 7s
    Fetching @grpc; fetching
    Fetching @png_archive; fetching
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:

**Comment by mohantym** [comment]
Hi @Dragonchengllc ! 1.x versions are supported anymore. Please refer this[ link](https://www.tensorflow.org/install/source) to build Tensorflow from source. Attaching relevant[ thread ](https://github.com/tensorflow/tensorflow/issues/27778)for reference. Thank you!
