### ISSUE TITLE
AveragePooling1D wrongly accept stride parameter to be None

### ISSUE THREAD

**Issue by maybeLee** [tensorflow/tensorflow#53571]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.3/8
- GPU model and memory: N/A

**Describe the current behavior**
`tf.keras.layers.AveragePooling1D` can output normal value when setting `stride` parameter to `None` with no warning/exceptions. In contrast `tf.keras.layers.Conv1D` will raise an exception to forbit such usage.

**Describe the expected behavior**
This API should throw an exception or raise a warning instead of outputing a normal value.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): I haven't tried a solution yet and I am not familiar with your coding style to deal with such an issue.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
x = tf.keras.layers.Input((32,3))
layer = tf.keras.layers.AveragePooling1D(pool_size=3, strides=None)
y = layer(x)
model = tf.keras.Model(x,y)
model.predict(np.random.rand(10,32,3))
```
You may access the code here:
https://colab.research.google.com/drive/1u80B4LFEEctS5GOZj3GUd_G6u_3A9kcu?usp=sharing

**Comment by mohantym** [comment]
Hi @maybeLee ! According to this [document](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling2D#args), When you are declaring Strides as **None** in AveragePooling1D, It is taking **strides size equal to pooling_size** But in case of [Conv1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D#args) , Strides has be an integer or tuple/list of a single integer, specifying the stride length of the convolution.

**Comment by maybeLee** [comment]
Hi mohantym, thanks for your prompt reply. So this is the expected behavior. I will close the issue.
