### ISSUE TITLE
model.fit excess memory usage with GPU

### ISSUE THREAD

**Issue by Chaudry24** [tensorflow/tensorflow#53577]
I am running 4 scripts which should be equivalent in theory. However, two of those [which use GPU to train the model] are using 10 times more memory than their CPU counterparts. 

The scripts which are using acceptable levels of memory are scripts 1 and 3. The unacceptable levels are scripts 2 and 4. 

Here is the code:
script1: https://pastebin.com/2gRbjKmx
script2: https://pastebin.com/GK9iE2DC
script3: https://pastebin.com/cUniWZxj
script4: https://pastebin.com/BwkWbHjg

My python version is 3.9.7 and tensorflow version is 2.4.1.

The OS is: Red Hat Enterprise Linux
The Kernel is: Linux 3.10.0-1160.2.1.el7.x86_64
The architecture is: x86-64

The GPU is Nvidia either P100 or Nvidia V100.

**Comment by mohantym** [comment]
Hi @Chaudry24 ! I tried switching between CPU and GPU using tf.device() and checked the memory usage using memory_usage api. Memory usage in GPU was exceeding CPU memory usage  as you pointed out . Attaching [Gist ](https://colab.sandbox.google.com/gist/mohantym/e8a26e8b9928bd24c436c654ef8e8c4d/github_53577.ipynb#scrollTo=TLi1gNCx3H8v)for reference. 

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by Chaudry24** [comment]
Hi @mohantym ! Thank you for taking the time and responding with these useful links. Here is the [link](https://github.com/keras-team/keras/issues/15843) to the issue I opened up. Thanks again!
