### ISSUE TITLE
Request for RandomIllumination layer in keras

### ISSUE THREAD

**Issue by MohamedAliRashad** [tensorflow/tensorflow#53588]
Something like this already is possible with `ImageDataGenerator` but with corners in it (only applies brightness scale).
What is needed is a full keras layer that randomize illumination differences spatially across the image (or even a single scaling factor to the whole image).
i think more ideas can be added to something like this if it was implemented properly.

**Comment by tilakrayal** [comment]
@MohamedAliRashad ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
