### ISSUE TITLE
Please add `tf.random.stateless_shuffle`

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#53584]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
we only have `tf.random.shuffle` which is generally annoying to work with and bug-prune when reproducible results are needed

(same reasoning for all 'tf.random.stateless_*`)

**Will this change the current api? How?**A
only API addition

**Who will benefit with this feature?**
people that want to reproduce random function rexecution

**Any Other info.**
no, thank you

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this feature request?

**Comment by Saduf2019** [comment]
@amitport 
Please feel free to create a PR or share where this change has to be made.

**Comment by amitport** [comment]
@Saduf2019 
If I had the capacity to implement this I would've sent a PR already.

**Comment by sachinprasadhs** [comment]
Could you please look at the available stateless distribution [here](https://www.tensorflow.org/api_docs/python/tf/random) like `stateless_binomial`, `stateless_normal`, `stateless_uniform` etc and let us know if this is what you are looking for or you need something specific. Thanks!

**Comment by amitport** [comment]
@sachinprasadhs 

No. stateless_shuffle is not covered by the other functions as is

**Comment by sachinprasadhs** [comment]
There is already an implementation available on nightly to run ops deterministically which is [enable_op_determinism](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism) you can start using that in nightly version as of now and it will be available in future stable releases. Thanks!

**Comment by amitport** [comment]
non determinism does not replace all stateless ops AFAIKT.
I want do be able to supply shuffle with a specific seed and get the same result in every context....

**Comment by wangpengmit** [comment]
We are working on adding `stateless_shuffle`.

BTW there is a new op [`index_shuffle`](https://www.tensorflow.org/api_docs/python/tf/random/experimental/index_shuffle) which can be used to implement `stateless_shuffle` (though the native `stateless_shuffle` we are adding will probably be faster).

**Comment by amitport** [comment]
@wangpengmit I just want to point out, that I specifically implemented a 'select random K without replacement' op.
For which [`index_shuffle`](https://www.tensorflow.org/api_docs/python/tf/random/experimental/index_shuffle) seems like a better alternative than the `stateless_shuffle` :).

**Comment by mohantym** [comment]
Hi @amitport !
It seems they have added [tf.random.experimental.stateless_shuffle](https://www.tensorflow.org/api_docs/python/tf/random/experimental/stateless_shuffle)  feature now.

**Comment by amitport** [comment]
Looks great! Thanks!

This issue can be closed as far as I'm concerned.

**Comment by mohantym** [comment]
@amitport !
Thanks for the confirmation . Marking this as resolved then.
Thank you!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
