### ISSUE TITLE
tf.ragged.stack_dynamic_partitions silently output wrong result with negative `partitions`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53581]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: Cuda 11.4
- GPU model and memory: n/a

**Standalone code to reproduce the issue**
```
import tensorflow as tf
data=['a', 'b', 'c', 'd', 'e']
partitions=[3, -2, 2, -1, 2]
num_partitions=5
t1 = tf.ragged.stack_dynamic_partitions(data, partitions, num_partitions) # Succeed
print(t1)
t2 = tf.ragged.stack(tf.dynamic_partition(data, partitions, num_partitions)) # Raise InvalidArgumentError
print(t2)
```
Outputs
```
<tf.RaggedTensor [[], [], [b'b', b'd'], [b'c'], []]>
InvalidArgumentError: partitions[1] = -2 is not in [0, 5) [Op:DynamicPartition]
```

**Describe the current behavior**
For `tf.ragged.stack_dynamic_partitions`, values in `partitions` should be greater or equal to zero. (as the document points out)

**Describe the expected behavior**
In the document it says "if `num_partitions` is an int (not a Tensor), then `tf.ragged.stack_dynamic_partitions(data, partitions, num_partitions)` is equivalent to `tf.ragged.stack(tf.dynamic_partition(data, partitions, num_partitions))`". So similar to the latter case, an `InvalidArgumentError` is expected to be raised when calling `tf.ragged.stack_dynamic_partitions` with `partitions` containing negative values.

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky ! According to this [document](https://www.tensorflow.org/api_docs/python/tf/ragged/stack_dynamic_partitions#args) , Values in Partitions must be greater than or equal to zero, and less than num_partitions. partitions is not required to be sorted. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/69d7ecbc4924ce8b37c71356b4df2285/github_53581.ipynb) for reference.

**Comment by ArrowIntoTheSky** [comment]
Thank you @mohantym ! I checked your Gist, and indeed on CPU it is raising invalid argument error. However, if you enable GPU it is not raising any error.

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you  please look at this issue . This issue is replicating in GPU mode. Attaching gist in[ 2.6](https://colab.sandbox.google.com/gist/mohantym/1917c86e14f83915194adba8d4d7f034/github_53581.ipynb#scrollTo=cfSJsLFEB3Km) and [2.7 ](https://colab.sandbox.google.com/gist/mohantym/69d7ecbc4924ce8b37c71356b4df2285/github_53581.ipynb#scrollTo=fUA6f6FO_2oX)for reference.

**Comment by mohantym** [comment]
Hi @sachinprasadhs @ArrowIntoTheSky !
This issue is still replicating with [2.10.0](https://colab.sandbox.google.com/gist/mohantym/8475cf9a2151d2a81d74e1f0411f04f4/github_53581.ipynb#scrollTo=0z_dJ5YABSUv) as @ArrowIntoTheSky pointed out in this [comment](https://github.com/tensorflow/tensorflow/issues/53581#issuecomment-1003051252).

**Comment by JXRiver** [comment]
This should be fixed with the latest tf-nightly.

**Comment by sachinprasadhs** [comment]
Reference commit id for the fix is https://github.com/tensorflow/tensorflow/commit/492bd543db5d55080af3efc1bbadf651f184f44d, you can use tf-nightly to include this fix, until next release is available or till it makes to any of the upcoming patch release.
