### ISSUE TITLE
Inconsistent results of K.dot

### ISSUE THREAD

**Issue by davy868** [tensorflow/tensorflow#53585]
there are two numpy matrixs：
**first** with shape:[1,39],dtype=float32, 
 **second** with shape[39,2],dtype=float32

`
import tensorflow.keras.backend as K
`
`
K.dot(tf.constant(first),tf.constant(second[:,0:1]))
`
Out[5]: <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[**0.8299226**]], dtype=float32)>

``
K.dot(tf.constant(first),tf.constant(second[:,0:2]))
``
Out[6]: <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[**0.8301826**, 1.0395387]], dtype=float32)>

the two results diff 2.66e-4 which is big enough for me

**can anybody tell me why this happens and any solutions?** 

tf v2.4.0

values of the matrix:

first
Out[7]: 
array([[-7.2378081e-01,  1.6171148e+00, -1.4751177e+00, -1.1468199e+00,
        -9.4957459e-01, -1.1004009e+00, -6.0811418e-01,  1.3347808e+00,
        -5.6221259e-01, -2.8636627e-02, -1.3238943e+00,  1.3290122e+00,
         3.3704469e-01,  4.8254672e-01, -6.0419792e-01,  7.0332962e-01,
        -8.1343579e-01, -1.7627051e+00,  3.5882825e-01, -1.4614569e+00,
        -3.9931360e-01, -9.7357178e-01, -6.1273777e-01,  4.6369970e-01,
         9.3952209e-01,  5.2290356e-01, -6.9766754e-01,  4.8909006e-01,
        -2.4669762e-01,  1.1569391e+00,  8.5423976e-01, -1.2952095e-03,
        -3.4862864e-01, -2.7243546e-01,  8.0830842e-01, -3.0422598e-01,
         2.8226626e-01, -5.6840044e-02, -7.3323792e-01]], dtype=float32)

second[:,0:2]
Out[8]: 
array([[-0.09545885,  0.0301608 ],
       [ 0.10142329, -0.09098691],
       [-0.04838413,  0.15964064],
       [ 0.16257629, -0.1777806 ],
       [-0.131538  , -0.14655067],
       [-0.085496  , -0.13280763],
       [ 0.18278474, -0.11492068],
       [ 0.03820068,  0.00508413],
       [-0.00234684, -0.10233091],
       [ 0.12245703,  0.10799986],
       [ 0.01588374,  0.05467606],
       [-0.15388036,  0.14180547],
       [-0.0121727 , -0.08367829],
       [ 0.09906906,  0.09994766],
       [-0.07855757, -0.18606487],
       [-0.02123192,  0.07851872],
       [-0.1276356 , -0.12484328],
       [-0.17431177,  0.00072895],
       [-0.02924933, -0.01532622],
       [ 0.06264558, -0.19014324],
       [ 0.07497945, -0.0103462 ],
       [ 0.00148363,  0.12542334],
       [ 0.0202539 , -0.04290475],
       [ 0.06409332,  0.17675939],
       [ 0.07451543, -0.01164982],
       [ 0.14731088, -0.16865423],
       [-0.13444461, -0.14083615],
       [ 0.17176068, -0.09960409],
       [-0.12674293, -0.17646563],
       [ 0.13016194,  0.09005257],
       [-0.19060531, -0.06375018],
       [ 0.03746909,  0.00599393],
       [ 0.18026543,  0.18963405],
       [-0.11866984, -0.11520495],
       [ 0.09463558,  0.11655363],
       [ 0.05268271, -0.1161972 ],
       [-0.1774411 ,  0.18842372],
       [ 0.02491291,  0.12098533],
       [-0.11909473,  0.03792849]], dtype=float32)

**Comment by tilakrayal** [comment]
@davy868 ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Also please try to test the code in latest stable tf v2.7.It helps.Thanks!

**Comment by davy868** [comment]
![image](https://user-images.githubusercontent.com/42214343/147809387-996ffdc7-f14a-46b4-8c21-d81ea7cf52ff.png)

**Comment by tilakrayal** [comment]
@davy868 ,
I ran the code shared and face a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/534bf8de81ba1724d6a00f9f3179c9d1/untitled173.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.

**Comment by tilakrayal** [comment]
Can you please look at this link [1](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dot) and [2](https://keras.io/api/layers/merging_layers/dot/) for more information on tf.keras.layers.Dot.It  helps.Thanks
