### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method for @tf.function and when I use tfp.mcmc.NoUTurnSampler()

### ISSUE THREAD

**Issue by DamingoNdiwa** [tensorflow/tensorflow#53586]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur
- TensorFlow installed from (source or binary): using homebrew
- TensorFlow version (use command below): tf-nightly==2.9.0.dev20211224
- Tensorflow probability version: tensorflow-probability==0.13.0
- Python version: Python 3.9.9

**Describe the current behavior**
I am unable to use @tf.function with indexing, for instance, the code below gives

- Auscomp.Qobs is data
t_end = len(Auscomp.Qobs)
t_obs = np.linspace(start=0.,
                    stop= t_end,
                    num=int(t_end)).tolist()
Auscomp.Prec.values is observed data values.

@tf.function(jit_compile=True)
def p(t):
    pos = tf.raw_ops.Bucketize(input=t,boundaries=t_obs)
    precip_t = Auscomp.Prec.values[pos - 1:pos]

    return precip_t[0]

- call function

p(1.5) throws the error message 

TypeError: in user code:

    File "<ipython-input-3-f42dda5a54a8>", line 20, in p  *
        precip_t = Auscomp.Prec.values[pos - 1:pos]

    TypeError: slice indices must be integers or None or have an __index__ method

**Describe the expected behavior**
I expect to have scaler value returned. For instance, if I add 
tf.config.run_functions_eagerly(True)  at the top of the programme the function works.
But I also have functions that solve ODEs and do Bayesian inference with TensorFlow probability. So when I run a function tfp.mcmc.NoUTurnSampler() that calls an ODE that calls the above function, I get the  message below

WARNING:tensorflow:It looks like tf.function behavior was disabled, perhaps using tf.config.run_functions_eagerly. Vectorization primitives (e.g. tf.vectorized_map) require tf.function to work. These primitives will override the disable.

and later the error

File "<ipython-input-6-7453b3323d01>", line 27, in precip
        precip_t = Auscomp.Prec.values[pos - 1:pos]

    TypeError: slice indices must be integers or None or have an __index__ method

**Standalone code to reproduce the issue**

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

t_end = 21
t_obs = np.linspace(0.0, t_end, 20)

- data set with zeros and ones 
precip = np.zeros(t_end + 1)
t_precip = np.linspace(0, t_end + 1, num=t_end + 2).tolist()

precip[0::7] = 1.0

@tf.function
def p(t):
        pos = tf.raw_ops.Bucketize(input=t,boundaries=t_precip)
    
        precip_t = precip[pos - 1:pos]

        return precip_t[0]
- call function  
p(1.5)

**Comment by sushreebarsa** [comment]
@DamingoNdiwa 
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by DamingoNdiwa** [comment]
@sushreebarsa 
thank you, here is the link to a Google Colab that has comments and some data with explanations.
https://colab.research.google.com/drive/1DU7gsLW2UkUJGjE6L5erWVZW2vljtN6-?usp=sharing

**Comment by sushreebarsa** [comment]
@Saduf2019  Was able to reproduce the issue in TF v2.7.0 ,please find the gist [here](https://colab.sandbox.google.com/gist/sushreebarsa/d1bef46615f7b88391e3e9d5c0869c84/hbvode.ipynb) for reference.Thanks!

**Comment by Saduf2019** [comment]
@DamingoNdiwa 
Please refer to similar error issues and let us know:
[link](https://stackoverflow.com/questions/28272322/typeerror-slice-indices-must-be-integers-or-none-or-have-an-index-method/28272778), [link1](https://careerkarma.com/blog/python-typeerror-slice-indices-must-be-integers-or-none/), [link2](https://www.stechies.com/typeerror-slice-indices-must-integers-none-have-index-metho/)

**Comment by DamingoNdiwa** [comment]
@Saduf2019 Thanks, I have tried similar solutions. I think the problem is the autograph used by  @tf.function. I now use a different package for this.

**Comment by Saduf2019** [comment]
@DamingoNdiwa 
Please move this to closed status, as it is not an issue any more.

**Comment by DamingoNdiwa** [comment]
Yes, I will close it. I left thinking it could be resolved because only TensorFlow 2. Thank you.
