### ISSUE TITLE
PKIX path validation failed for giflib/giflib-5.2.1.tar.gz ( CertPathValidatorException )

### ISSUE THREAD

**Issue by sdp009** [tensorflow/tensorflow#53587]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?:  docker pull tensorflow/tensorflow:devel
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CUDA/cuDNN version: 
- GPU model and memory: 

**Describe the problem**

**Reproduction step:**
 bazel build //tensorflow/tools/graph_transforms:transform_graph

**ERROR:** tensorflow/tensorflow/core/platform/default/build_config/BUILD:172:11: //tensorflow/core/platform/default/build_config:gif depends on @gif//:gif in repository @gif which failed to fetch. no such package '@gif//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted: Analysis failed

**Logs:**

INFO: Found applicable config definition build:dynamic_kernels in file /local/mnt/workspace/sdks/tf_src/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/curl.haxx.se/download/curl-7.78.0.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Repository gif instantiated at:
  /local/mnt/workspace/sdks/tf_src/tensorflow/WORKSPACE:15:14: in <toplevel>
  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:1089:21: in workspace
  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:366:20: in _tf_repositories
  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:66:35: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: An error occurred during the fetch of repository 'gif':
   Traceback (most recent call last):
        File "/local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl", line 53, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
INFO: Repository icu instantiated at:
  /local/mnt/workspace/sdks/tf_src/tensorflow/WORKSPACE:15:14: in <toplevel>
  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:1082:28: in workspace
  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:70:8: in _initialize_third_party
  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/icu/workspace.bzl:6:20: in repo
  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:66:35: in <toplevel>
ERROR: /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/core/platform/default/build_config/BUILD:172:11: //tensorflow/core/platform/default/build_config:gif depends on @gif//:gif in repository @gif which failed to fetch. no such package '@gif//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted: Analysis failed
INFO: Elapsed time: 40.378s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (186 packages loaded, 8493 targets configured)

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@sdp009 
Apologies for the delayed response,is this still an issue

**Comment by sdp009** [comment]
@Saduf2019 , issue is still reproducible. I also tried with different machines. I think, something wrong with 'gif' repo keystore with importing SSL cert. I don't know much on this.

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
ERROR: An error occurred during the fetch of repository 'gif':
   Traceback (most recent call last):
        File "/local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl", line 53, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException

**Comment by sachinprasadhs** [comment]
Could you try the below and build again.
```
apt-get update 
apt-get install git
```

**Comment by Nithin061** [comment]
i Am also facing the same issue. Can someone help here
