### ISSUE TITLE
Tensor Issue. 1

### ISSUE THREAD

**Issue by RonSherfey** [tensorflow/tensorflow#53599]
https://github.com/tensorflow/tensorflow/blob/c256c071bb26e1e13b4666d1b3e229e110bc914a/tensorflow/python/ops/tensor_array_ops.py#L961-L1296

**Comment by tilakrayal** [comment]
@RonSherfey ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.
