### ISSUE TITLE
TF > 2.5 does not work properly for keras.fit for dictionary inputs

### ISSUE THREAD

**Issue by jostheim** [tensorflow/tensorflow#53590]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.2, 2.6.2, 2.7
- Python version: 3.9
- CUDA/cuDNN version: 11.3
- GPU model and memory: 1080 Ti

**Describe the current behavior**

If I use TF 2.5.2 with keras.fit and inputs that are dictionaries for my multi input model, my model will fit.  If I used TF 2.6.* or 2.7.* I get out of memory errors.  

**Describe the expected behavior**

TF should not run out of memory in one version and not run out of memory in another, this model is definitively fittable with my GPU memory.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

I did find a solution and that was to start using tf.dataset with from_generator being based on my input dictionaries instead of directly using dictionaries for my multi input model.  Why this would make any difference I do not know and this is the bug that should be addressed.

**Standalone code to reproduce the issue**

Don't have a standalone case, but this should be easily identifiable, there should be unit tests around all the different ways of passing input to keras.fit.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@jostheim 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by jostheim** [comment]
I won't be providing a code snippet, I am just reporting a bug, I found a work around so feel free to ignore the bug if you don't care.

**Comment by sushreebarsa** [comment]
@jostheim Without the reproducible code, it would be difficult for us to debug the issue. If you're unable to provide the code could you please post in [TF discussion Forum](https://discuss.tensorflow.org/) and move this issue to closed status ?  Thank you!

**Comment by jostheim** [comment]
Up to you, I explained the issue, you can write unit tests for it, pass in data to keras.fit as a dictionary of numpy arrays for a reasonably large model (67E6 parameters) and it goes OOM, use a tf.dataset instead and it doesn't go OOM.  I have thousands of lines of code in my model and any dataset is gigabytes, I can't give you a simple example..

**Comment by jostheim** [comment]
Oh and by the by if anyone needs to convert multi-input dictionary to a dataset so it won't OOM error, here is my code.  Hope it helps someone!


```
       features_output_sig = {}
        for i, (k, v) in enumerate(features.items()):
            features_output_sig[k] = tf.TensorSpec(list(v[0].shape), dtype=tf.float32)
        targets_output_sig = {}
        for i, (k, v) in enumerate(features.items()):
            targets_output_sig[k] = tf.TensorSpec(list(v[0].shape), dtype=tf.float32)

        def train_generator():
            size = list(features.values())[0].shape[0]
            for j in range(size):
                features_d = {}
                for k, v in features.items():
                    features_d[k] = v[j]
                targets_d = {}
                for k, v in targets.items():
                    targets_d[k] = v[j]
                yield features_d, targets_d

        train_dataset = tf.data.Dataset.from_generator(train_generator, output_signature=(features_output_sig, targets_output_sig))


```

**Comment by sushreebarsa** [comment]
@jostheim Thank you for the update! 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
