### ISSUE TITLE
Keras: How to use another model as a layer in current model which input is ragged tensor and  output is also ragged tensor with same shape

### ISSUE THREAD

**Issue by zwh14** [tensorflow/tensorflow#53594]
Suppose I have a base model take two inputs and output single value:

```
# define two input
input1 = keras.Input(shape=(100,), dtype=tf.int8)
input2 = keras.Input(shape=(20,), dtype=tf.int8)
# DNN for onehot feature
dense1 = Dense(32, activation='relu')(input1)
dense2 = Dense(4, activation='relu')(input2 )
# output 
output = Dense(1, activation='sigmoid')(Concatenate(axis=1)([dense1 , dense2 ]))
# define base model 
item_base_model = keras.Model(inputs=[input1, input2], outputs=output, name="base_model")
```

Then I have a model take (None,100) and (None, 20) array as two inputs:
```
# define input list
input1_list = keras.Input(shape=(None, 100],), dtype=tf.int8)
input2_list = keras.Input(shape=(None, 20,), dtype=tf.int16)
```

I want to ask that how I can call the based model for each input in the inpu1_list and input2_list and get their output as a tensor with shape (None,).  Finally, I will train the entire model

**Comment by tilakrayal** [comment]
@zwh14 ,
 In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.

**Comment by tilakrayal** [comment]
Also can you please take a look at link [1](https://stackoverflow.com/questions/47678108/keras-use-one-model-output-as-another-model-input) and [2](https://github.com/keras-team/keras/issues/3465) with the similar issue.It helps.Thanks!

**Comment by zwh14** [comment]
@tilakrayal

I am using the tf 2.5.2.
In fact that is almost all code. I first define the base model. Its inputs is with shape(100,) and (20,) and it output a value. 
Than I want to define another model, its inputs is with shape(None,100,) and (None, 20). I just want to iterate the ragged tensor with the base model to get a (None,) shape output. I think the output is also ragged tensor? I do not know how to implement

**Comment by zwh14** [comment]
This is the base model

```
# define item-base model
input_aspects_onehot = keras.Input(shape=(100,), dtype=tf.int8)
input_aspects_ordinal = keras.Input(shape=(20,), dtype=tf.int16)


# DNN for onehot feature
dense1_onehot_output = Dense(256, activation='relu')(input_aspects_onehot)
dense2_onehot_output = Dense(64, activation='relu')(dense1_onehot_output)

# Embedding and Max Pool Layer for ordinal feature
aspects_embedding = Embedding(input_dim=2000, 
                              output_dim=64, 
                              mask_zero=True)(input_aspects_ordinal)

aspects_embedding_maxpool = GlobalMaxPooling1D()(aspects_embedding)

# stacking the two dense2_onehot_output and aspects_embedding_maxpool
dense_stack_output = Dense(64, activation='relu')(Concatenate(axis=1)([dense2_onehot_output, aspects_embedding_maxpool]))

# output for one item
output = Dense(1)(dense_stack_output)

item_base_model = keras.Model(inputs=[input_aspects_onehot,input_aspects_ordinal], outputs=output, name="item_base_model")
item_base_model.summary()
```
This is another model which will call the base model

```
# define list model
input_aspects_onehot_list = keras.Input(shape=(None, 100,), dtype=tf.int8)
input_aspects_ordinal_list = keras.Input(shape=(None, 20,), dtype=tf.int16)

base_model_output_list = []
for i in range(len(input_aspects_onehot_list)):
    base_model_output_list.append(item_base_model(input_aspects_onehot_list[i], input_aspects_ordinal_list[i]))
output = tf.stack(base_model_output_list)

item_base_model = keras.Model(inputs=[input_aspects_onehot_list,input_aspects_ordinal_list], outputs=output, name="model")
```

**Comment by zwh14** [comment]
Obviously I can't do a for loop for keras Input.I'm just trying to express that logic

**Comment by tilakrayal** [comment]
@zwh14 ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
