### ISSUE TITLE
error LNK2001 when build on windows with --config=dynamic_kernels

### ISSUE THREAD

**Issue by maz-1** [tensorflow/tensorflow#53597]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10 19044.1415
- TensorFlow installed from: source
- TensorFlow version: master
- Python version: 3.9.7
- Installed using: conda
- Bazel version: 4.2.2
- GCC/Compiler version: msvc 19.29.30038.1
- CUDA/cuDNN version: cuda 11.1, cudnn 8.2.1
- GPU model and memory: GTX 1080TI 11G

**Describe the problem**

I'm trying to compile tensorflow with "--config=dynamic_kernels" so I can use custom op. What I did:
* Following https://www.tensorflow.org/install/source_windows?hl=zh-cn except using anaconda python
* Edit .bazelrc and replace "build:windows --config=monolithic" with "build:windows --config=dynamic_kernels"
* run "bazel build //tensorflow/tools/pip_package:build_pip_package --config=avx2_win"
When building goes into link stage I got a lot of  LNK2001 error.

**Any other info / logs**
[build-log.txt](https://github.com/tensorflow/tensorflow/files/7796223/build-log.txt)

**Comment by sachinprasadhs** [comment]
The document which you are following has some old versions, please follow [this](https://www.tensorflow.org/install/source_windows) document which has the steps with the latest version and let us know if the problem still persists. Thanks!

**Comment by maz-1** [comment]
> 

Ok, so the only difference i found is the step "Install Python and the TensorFlow package dependencies"
I followed the newest document and I got exactly same errors.
