### ISSUE TITLE
Add a way to see the shape of the Tensors (arrows) in Tensorboard.

### ISSUE THREAD

**Issue by cesarsalgado** [tensorflow/tensorflow#536]
I think it would be useful to add functionality to check the calculated shape (if available) of the Tensors in the graph visualization. Maybe we could click the arrows to open a window that showed info about the tensor shape (and maybe other info too). What are your thoughts about that?

**Comment by mrry** [comment]
That's a good idea, but it will require some thought because the graph visualizer doesn't current get information about the execution (other than the computed summaries). Assigning to danmane@, who's been tracking feature requests for new versions of TensorBoard.

**Comment by HamedMP** [comment]
I also had an idea for what the ultimate version of tensroboard can look like, that is putting aside the add_image/histogram/..._summary and let user click and each node of the graph and see what is exactly flowing in the tensors, if it images, vectors, ..., something like the debugger area of most of the ideas which let you know the variables info in the run time.

**Comment by cesarsalgado** [comment]
Does cc36921 solves this issue?

**Comment by dsmilkov** [comment]
Yes, exactly. I will update this issue and close it once the documentation is updated (the commit on under review). The doc talks about this new feature and show users how to use it.

Here is the short doc: To include tensor shapes in the `GraphDef` pass `sess.graph.as_graph_def(add_shapes=True)` to the `SummaryWriter` when
serializing the graph.

**Comment by dsmilkov** [comment]
Forgot to mention that the shapes shown in the graph visualizer are the statically inferred shapes from the python client. Most of the shapes are known in practice. However, ops whose output tensor's shape depends on some variable at run-time, will have unknown shape in the graph.

**Comment by cesarsalgado** [comment]
Thanks!

**Comment by dsmilkov** [comment]
[Here is](https://www.tensorflow.org/versions/master/how_tos/graph_viz/index.html#tensor-shape-information) part of the tutorial explaining how to add tensor shapes to the graph visualizer.

**Comment by dmoham1476** [comment]
I have tensorflow 1.5 and I tried passing this to the summary_writer on the nmt tutorial, 
graph_def=sess.graph.as_graph_def(add_shapes=True)
It says - passing as_graph_def to summarywriter is deprecated, use sess.graph instead. However, sess.graph does  not have add_shapes=True.

What is a good way to see what the tensors in the arrows represent. It is hard to dig through the code and figure the tensors and their shapes and map it to the corresponding graph
