### ISSUE TITLE
What can I use instead of "tf.contrib.layers.embed_sequence"

### ISSUE THREAD

**Issue by BuuDien** [tensorflow/tensorflow#53605]
I try to build a chatbot for studying purpose, but it seems like the lesson is quite out-dated, they used tensorflow v1 and there are some problems with that.

What can I use instead of "tf.contrib.layers.embed_sequence" since "contrib" is no longer available and I can't find anything in [tf_slim/layers](https://github.com/google-research/tf-slim/tree/master/tf_slim/layers) and [addons](https://github.com/tensorflow/addons), too.

**Comment by tilakrayal** [comment]
@BuuDien ,
Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/46666#issuecomment-775313197) from the issue and the SO [link](https://stackoverflow.com/questions/55518033/where-can-i-find-tensorflow-contrib-layers-for-tensorflow-2-0).It helps.Thanks
