### ISSUE TITLE
how to build iOS static library using bazel

### ISSUE THREAD

**Issue by superrunt19** [tensorflow/tensorflow#5360]
I'm working with tag `v0.11.0.rc2`.

Following the instructions here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/README.md I have successfully built tensorflow for iOS using the makefile approach.  However, I have wondered about the first line in the readme
>The recommended way to build TensorFlow from source is using the Bazel open-source build system

I can't find any targets in the bazel BUILD files that would build `libprotobuf-lite.a`, `libprotobuf.a`, and `libtensorflow-core.a` that the makefile approach builds.

Does anyone know how to build the static libs for iOS using Bazel?  Is there a reason/advantage to do so?

**Comment by aselle** [comment]
Sorry that is a general statement that doesn't apply to iOS. For iOS you currently need to use the makefile. Sorry for the confusion.

**Comment by cancan101** [comment]
Is it still the case that Make is the only way to build for iOS, or can bazel now be used? If no bazel, what is this: https://github.com/tensorflow/tensorflow/commit/78c9dec5a62e74389608c709027fb8eabdf2bef0 ?

**Comment by aselle** [comment]
@petewarden, I believe this still applies. Right?

**Comment by jakiechris** [comment]
i successfully built ios  file : tensorflow\contrib\makefile\gen\lib\libtensorflow-core.a

but don't know where the header files are...

any one knows where to find h files ?

here is my technical paths:
https://github.com/tensorflow/tensorflow/issues/11126
https://github.com/tensorflow/tensorflow/issues/11231
