### ISSUE TITLE
MaxPool2D crashes

### ISSUE THREAD

**Issue by lugalUrim** [tensorflow/tensorflow#53604]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: cuda 11.2
- GPU model and memory: n/a

**Standalone code to reproduce the issue**
```
import tensorflow as tf
kernel_size = [1,3]
strides = [2,2]
layer = tf.keras.layers.MaxPool2D(kernel_size,strides=strides)
input_tensor = tf.random.uniform([3, 1, 1, 64], dtype=tf.float32)
layer(input_tensor) 
# Aborted (core dumped)
```
This code would crash with GPU. 

**Describe the expected behavior**
With CPU the output of the `MaxPool2D` layer would be a tensor of shape `(3, 1, 0, 64)`. I think the output should be similar with GPU, or at least there should also be some error checking instead of crashing.

**Comment by atarax665** [comment]
Input tensor should be of shape [1, x, 3, y] at least as you have set the pool size as [1, 3]. I guess this is why its crashing.

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue ? It is replicating in GPU mode only. Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/43b459c155f4b16a69854f2a1b4ec800/github_53604.ipynb) for reference. Thanks!

**Comment by Saduf2019** [comment]
@lugalUrim 
I ran the code and made few changes on GPU, as per errors reported in keras team, please find the gist [here](https://colab.research.google.com/gist/Saduf2019/61e7a8c327dd820b9a20e4dff383e2e3/untitled653.ipynb), you may fix the error in this using this [link](https://github.com/nginyc/rafiki/issues/154),[link1](https://stackoverflow.com/questions/55195701/tensorflow-why-does-cudnn-fails-to-launch-cuda-error-launch-failed).

In case of any more keras related issues please create this in keras repo.
