### ISSUE TITLE
Android TensorFlow GPU Delegate

### ISSUE THREAD

**Issue by soiavaq** [tensorflow/tensorflow#53616]
I want to apply cartoon effect to picture in android (java/kotlin or c/c++) with tensorflow lite. (tflite model / dr, fp16, int8 quantization)

I found [this tutorial.](https://blog.tensorflow.org/2020/09/how-to-create-cartoonizer-with-tf-lite.html)

[This code](https://github.com/margaretmz/Cartoonizer-with-TFLite) is also based on it.

My demo app works on CPU with 4 threads but when I want to test it with GPU delegate gives an [error.](https://i.stack.imgur.com/4whGx.jpg)

I used several devices and the result was the same in all of them.

```
// Check if device supports GPU delegate

val compatList = CompatibilityList()

val isSupported = compatList.isDelegateSupportedOnThisDevice

// If device does not support, then it will be done on 4 CPU threads

val options = Model.Options.Builder().apply {

if(isSupported) setDevice(Model.Device.GPU)

else setNumThreads(4)

}.build()

val model = WhiteboxCartoonGanFp16.newInstance(this, options)

val process = model.process(picture)
                     
val cartoon = process.cartoonizedImageAsTensorImage

val bitmap = image.bitmap
                                    
model.close()
```

**Comment by sushreebarsa** [comment]
@soiavaq 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by miaout17** [comment]
+1 to what @sushreebarsa said -- It would be helpful to understand the used TFLite version etc. 

By looking at the error message, it seems that it's hitting [this](https://github.com/tensorflow/tensorflow/blob/90393c40b1623cfae7929987ab830d0995f9bea7/tensorflow/lite/delegates/gpu/common/object_reader.cc#L47) path, and it's probably a case that's not handled by GPU delegate yet. 
@impjdi do you have any insight?

**Comment by impjdi** [comment]
Sorry, absolutely no experience with Kotlin or its multithreading which OpenGL is very sensitive with.

**Comment by soiavaq** [comment]
When I change version (downgrade tensorflow-lite from 2.7.0 to 1.15) , this problem is solved but in speed it is no different with CPU, while GPU should be faster.
I tested other tflite models like MobileNet and they work.

**Comment by sushreebarsa** [comment]
@soiavaq Could you please  check if your GPU inference part is running in a different thread than the main app thread in the latest version ?Could you please refer to [this](https://github.com/tensorflow/tensorflow/issues/41839) similar issue and let us know if it helps? Please make sure you're using TF v2.4 or later as older versions are no longer supported.If you could provide the error  in text format rather than image ,then it would be more helpful to analyze the issue? Thanks!

**Comment by Raphaelzrf** [comment]
@soiava Have you already solved this problem?
