### ISSUE TITLE
Loading a Keras model which contains __ne__ or __eq__ operators fails

### ISSUE THREAD

**Issue by OmriSteiner** [tensorflow/tensorflow#53610]
I posted this on Keras first, but it didn't get any attention, so posting here as well.
https://github.com/keras-team/keras/issues/15832

**Comment by sushreebarsa** [comment]
@OmriSteiner Sorry for the late response in [keras-team/keras#15832](https://github.com/keras-team/keras/issues/15832) !
Please move this issue to close status as we will track the other ticket in keras-team/keras repo.  
We are addressing the Keras issues in `keras-team/keras repo`. To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
