### ISSUE TITLE
Problem with setting up CUDA or cuDNN

### ISSUE THREAD

**Issue by suchencjusz** [tensorflow/tensorflow#53611]
**System information**
- OS Platform and Distribution: Windows 10 21H2 19044.1415
- TensorFlow installed from: pip install (binary)
- TensorFlow version: 2.7.0 (keras too)
- Python version: 3.9.7
- Installed using virtualenv? pip? conda?: nope, pip
- CUDA/cuDNN version: cudnn-windows-x86_64-8.3.1.22 cuda 11.5 
- GPU model and memory: GTX 1050Ti 4GB

I get this error in terminal 
`
Could not load library cudnn_cnn_infer64_8.dll. Error code 126
Please make sure cudnn_cnn_infer64_8.dll is in your library path!
`

![installed cudnn .dll files](https://i.ibb.co/C7qgYB5/temp.jpg)

I also tried with v11.2 with modifiaction on system env. variable, did not help...

Also adding this lines of code did not helped
`
import os
os.add_dll_directory("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5/bin")
`

The problem shows on clear python env. and in jupyter notebook.

**Comment by mohantym** [comment]
Hi @suchencjusz! Can you please check this [thread](https://stackoverflow.com/questions/66355477/could-not-load-library-cudnn-ops-infer64-8-dll-error-code-126-please-make-sure) for answer? Thanks!

**Comment by suchencjusz** [comment]
@mohantym I checked your thread, did not worked.

**Comment by mohantym** [comment]
@suchencjusz ! Could you try these following steps and let us know ?                                                                                          
1. Please Uninstall Cuda 
2. Switch to Cuda 11.2 (presently 11.5 as mentioned in template) and Cudnn 8.1  
3. Try  again with a new environment  .
If it still displays same error then try copying the .dll files from Cuda download location. Ref [1](https://www.tensorflow.org/install/source#gpu) ,[ 2 ](https://stackoverflow.com/a/69935795/11530462) .Thanks!

**Comment by tushar-31093** [comment]
Yes this issue persists. Some of the devices it is not working at all.
