### ISSUE TITLE
Object of type 'path' has no field "realpath".

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5361]
i get the latest code, installed **bazel 0.3.2**. but still meet errors when run **./configure** for build from source.

root@scopephotos:/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow# ./configure 
/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow /home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: **5.1.3**
Please specify the location where cuDNN 5.1.3 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
**ERROR:** com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/third_party/gpus/cuda_configure.bzl", line 517
		_create_cuda_repository(repository_ctx)
	File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/third_party/gpus/cuda_configure.bzl", line 432, in _create_cuda_repository
		_cuda_toolkit_path(repository_ctx, cuda_version)
	File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/third_party/gpus/cuda_configure.bzl", line 148, in _cuda_toolkit_path
		str(repository_ctx.path(cuda_toolkit...)
	File "/home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/third_party/gpus/cuda_configure.bzl", line 148, in str
		repository_ctx.path(cuda_toolkit_path).realpath
**Object of type 'path' has no field "realpath".**

**Comment by aselle** [comment]
Please provide the information on the template. What operating system, compiler, etc. are you using?

**Comment by civilmanxx** [comment]
the latest source code. Ubuntu 16.04. Cuda 7.5, cudnn 5.1.3.

**Comment by aselle** [comment]
A few more things...
- What version of bazel?
- Did you try upgrading bazel?
- Did you try starting from a clean sandbox?

**Comment by civilmanxx** [comment]
I install bazel 0.3.2. my previous version is 0.3.1, as I see another post has the similar issue and is fixed by update to bazel 0.3.2. But it does not work for me. I use **git pull** to update the code. all the local code are up to date.

**Comment by civilmanxx** [comment]
I run the following cmd and the issues are fixed.

 sudo apt-get update && sudo apt-get install bazel

 sudo apt-get upgrade bazel
