### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS when enable unified memory in multi-GPUs training

### ISSUE THREAD

**Issue by firejq** [tensorflow/tensorflow#53626]
I perform data parallel training on nvidia v100 based on horovod+tensorflow. Since a single gpu cannot accommodate the size of my model, I am trying to use tensorflow's unified memory through `per_process_gpu_memory_fractio`.

When I use 4 gpus for training and enable unified memory, everything is fine, and the performance loss is acceptable.

But when I used 8 gpus for training and turned on unified memory, I encountered the following error:
```
E tensorflow/stream_executor/event.cc:34] error destroying CUDA event in context 0x7fd97d23d970: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
terminate called after throwing an instance of 'std::logic_error'
  what():  cudaEventSynchronize failed: an illegal memory access was encounteredterminate called after throwing an instance of 
```

- Tensorflow version: 1.13.1
- CUDA 10.0
- CentOS 7.2

I don’t know the reason for this error, any troubleshooting suggestions will be very much appreciated.

**Comment by mohantym** [comment]
Hi @firejq ! 
1.x versions of Tensorflow which is not supported any more. Could you please try in latest version 2.7 and let us know ?Attaching relevant threads . [1](https://developer.nvidia.com/blog/unified-memory-cuda-beginners/), [2](https://discuss.tensorflow.org/t/mult-gpus-training-with-unified-memory/6428).  Thanks!
