### ISSUE TITLE
model.build documentation absent on wensite

### ISSUE THREAD

**Issue by old-school-kid** [tensorflow/tensorflow#53625]
The build method for model class is not documented or/and is not present on the [page](https://www.tensorflow.org/api_docs/python/tf/keras/Model#methods_2). Can this be added?
Thank you!

**Comment by sushreebarsa** [comment]
@old-school-kid 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), to provide more information on this issue?Thanks!

**Comment by old-school-kid** [comment]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: [Tensorflow model methods](https://www.tensorflow.org/api_docs/python/tf/keras/Model#methods_2)

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/

## Description of issue (what needs changing): The documentation for `build` method is missing. 

### Clear description

For example, why should someone use this method? How is it useful? Basic method present in every model. Without `build` on wont be able to see the summary and cant see the network even.

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example? There is no example right now but the method is used to build custom models in the documentation.

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? No

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue?  No
See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by sachinprasadhs** [comment]
`build()` method is to be used for subclassed models, which do not know at instantiation time what their inputs look like.
 This method only exists for users who want to call `model.build()` in a standalone way (as a substitute for calling the 
model on real data to build it). It will never be called by the framework (and thus it will never throw unexpected errors in an unrelated workflow).
You can check the usage of build() in subclassed layer documentation [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer?version=nightly) and [here](https://www.tensorflow.org/guide/keras/custom_layers_and_models).
