### ISSUE TITLE
Missing comma in test results in unexpected string concatenation

### ISSUE THREAD

**Issue by code-review-doctor** [tensorflow/tensorflow#53636]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): NA
- Python version: NA
- Bazel version (if compiling from source): NA
- GPU model and memory: NA
- Exact command to reproduce: NA

**Describe the problem**.

Absent comma results in unwatned string concatenation on line 330:
https://github.com/tensorflow/tensorflow/blob/0d8705c82c64dfb39c49e346de1a66182e5eabd1/tensorflow/python/keras/engine/training_generator_test.py#L330-L336

So `'matmul'` gets appended with 'Yaks are also quite nice' resulting in `matmulYaks are also quite nice` being used in the test.

**Describe the current behavior**.

`'matmulYaks are also quite nice'` is used in the test

**Describe the expected behavior**.

`'matmul', 'Yaks are also quite nice'` is used in the test

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

Add the missing comma

**Standalone code to reproduce the issue**.

NA

**Source code / logs**.

NA

**Comment by sachinprasadhs** [comment]
Would you like to create a PR for the same

**Comment by sachinprasadhs** [comment]
Could you please create the PR in github.com/keras-team/keras repo as per the above linked PR.

**Comment by code-review-doctor** [comment]
this is now fixed upstream
