### ISSUE TITLE
Convert retrained data into .pb format for ios camera example?

### ISSUE THREAD

**Issue by QuantumTCode** [tensorflow/tensorflow#5363]
I retrained image data using the tutorial at ((https://www.tensorflow.org/versions/r0.9/how_tos/image_retraining/index.html)) I did all the steps until `bazel build tensorflow/examples/image_retraining:retrain`. I was wondering how to turn this image training data into a .pb file that I can use in the ios camera example.

Thank you for your help!

**Comment by QuantumTCode** [comment]
``

**Comment by aselle** [comment]
This question is better asked on StackOverflow which is centered around how to do things. GitHub issues is primarily for bugs or feature requests. Thank you!
