### ISSUE TITLE
Request for grouped convolutions on CPU

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorflow#53631]
**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Grouped convolutions are not currently supported on CPUs in graph mode. We get the following error when we try to do the same:
```
UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
	 [[node sequential_2/sequential/conv2d/BiasAdd
 (defined at /usr/local/lib/python3.7/dist-packages/keras/layers/convolutional.py:265)
]] [Op:__inference_predict_function_1730]
```
Till date, there have been numerous issues on TF's GitHub repo regarding this. Owing to that, I am requesting the team to look into this.

**Will this change the current api? How?**
`model.predict()` with a model having grouped convolutions will not result in an error on a CPU.

**Who will benefit with this feature?**
Many architectures today use grouped convolutions as they are known to be more efficient while maintaining the accuracy. Thus, I believe many TF developers will benefit from this addition.

**Comment by mohantym** [comment]
Hi @AdityaKane2001 ! 
Could you please post this feature request on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thank you!

**Comment by AdityaKane2001** [comment]
@mohantym

I believe this is a core TF issue and not a Keras one. This is because the aforementioned error is thrown in [tensorflow/core/kernels/conv_ops_fused_impl.h](https://github.com/tensorflow/tensorflow/blob/25d9dd7b1194de41a63e9ddaa68445e64b7f802a/tensorflow/core/kernels/conv_ops_fused_impl.h#L216-L218). As the error says the core library has not implemented this yet, and hence I have raised this issue here itself.

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this feature request?

**Comment by Saduf2019** [comment]
@AdityaKane2001 
Please feel free to raise a PR for the same.

**Comment by AdityaKane2001** [comment]
@Saduf2019 

Not really my piece of cake 😅 That's the reason I opened an issue and not a PR directly.

**Comment by AdityaKane2001** [comment]
@jvishnuvardhan 

Could you please take a look at this one? TIA

**Comment by AdityaKane2001** [comment]
@
