### ISSUE TITLE
Question on implicit transpose in HLO bitcast/copy/reshape instruction

### ISSUE THREAD

**Issue by donglinz** [tensorflow/tensorflow#53649]
HLO instructions like bitcast/copy/reshape often conduct implicit transpose. I am confusing on how the reshape/transpose performed exactly, as I am not aware of they are documented anywhere else including official operation semantics. 

Take tensor A[2,3]{1,0} as an example, suppose tensor A have element [[1,2,3], [4,5,6]] with memory layout [1,2,3,4,5,6], consider following two transposition performed by bitcast/copy/reshape:

1. %bitcast = f32[2,3]{0,1} bitcast(f32[2,3]{1, 0} %A)
we get tensor elements [[1,2,3], [4,5,6]] with memory layout [1,4,2,5,3,6] 
2. %bitcast = f32[3,2]{0,1} bitcast(f32[2,3]{1, 0} %A)
For this case both tensor shape and memory layout are permutes, I suppose technically tensor A first reshape to [3,2] (get [3,2]{1,0}), then permute memory layout to get the final result.
So the process would be [[1,2,3], [4,5,6]] [1,2,3,4,5,6]  --reshape--> [[1,2],[3,4],[5,6]] [1,2,3,4,5,6] --transpose--> [[1,2],[3,4],[5,6]] [1,3,5,2,4,6]

Am I understanding implicit transpose correctly?

Thanks a lot:)

**Comment by sushreebarsa** [comment]
@donglinz We see that there is another issue #53650 which we are tracking. Could you please confirm if it is  a duplicate ticket and close this one so that we can get you the right help in other issue ?Thank you!

**Comment by donglinz** [comment]
Hi @sushreebarsa, it not a duplicated ticket. Two issues are both targeting hlo bitcast instruction however the question are unique.

**Comment by sushreebarsa** [comment]
@donglinz   Thank you for the update!
Could you please refer to [bitcast](https://www.tensorflow.org/api_docs/python/tf/bitcast),[operation_semantics](https://www.tensorflow.org/xla/operation_semantics) and[ this thread ](https://stackoverflow.com/questions/50128777/tensorflow-concat-with-transpose-using-the-broadcast-semantic),please let us know if it helps?Thanks!
