### ISSUE TITLE
Conv2DTranspose have a non-deterministic behavior 

### ISSUE THREAD

**Issue by reuvenperetz** [tensorflow/tensorflow#53645]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 8.1
- GPU model and memory: GeForce GTX 1080 Ti

**Describe the current behavior**
It seems that Conv2DTranspose behaves in a non-deterministic way.

**Describe the expected behavior**
I would expect to get the exact same output when I run the same model with the same input.

**Standalone code to reproduce the issue**
#*****************************************
import numpy as np
from keras.layers import Conv2DTranspose, Input
from keras.models import Model

input_layer = Input(shape=(8, 8, 3))
output = Conv2DTranspose(3, 4)(input_layer)
model = Model(input_layer, output)
data = np.random.randn(1, 8, 8, 3)

for _ in range(10):
    output_sum = np.sum(model.predict(data))
    print(f'output_sum: {output_sum}')
#*****************************************

Output I get:
output_sum: 1.6755037307739258
output_sum: 1.675503134727478
output_sum: 1.675502896308899
output_sum: 1.6755034923553467
output_sum: 1.6755017042160034
output_sum: 1.675503134727478
output_sum: 1.6755036115646362
output_sum: 1.6755034923553467
output_sum: 1.6755030155181885
output_sum: 1.6755015850067139

**Comment by tilakrayal** [comment]
@reuvenperetz ,
I was able to run the code without any issues on TF v2.7. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/79dcd03c352cd86f2a7cc17cc170dc82/untitled179.ipynb).Also please create a virtual environment and test your code again. It helps. Thanks!

**Comment by kasyap1234** [comment]
I tried it with google colab and it worked perfectly .
