### ISSUE TITLE
tf.bincount outputs wrong results

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53651]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
v = tf.constant([[0, 1, 2],
       [3, 4, 5]], dtype=tf.int64)
res1 = tf.math.bincount(v,axis=-1,maxlength=0, binary_output=True)
res2 = tf.sparse.bincount(v,axis=-1,maxlength=0, binary_output=True)
print(res1)
print(res2)
```

**Current output**
```
tf.Tensor([], shape=(2, 0), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [1 3]
 [1 4]
 [1 5]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int64), dense_shape=tf.Tensor([2 6], shape=(2,), dtype=int64))
```

**Expected output**
For `tf.sparse.bincount`, the output should have length at most `maxlength`, in the above code `maxlength` is `0`, so the output should be an empty tensor.
(`tf.math.bincount` is just to show that the output for `tf.sparse.bincount` should be have _same length_ as `tf.math.bincount`. )

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky ,
tf.math.bincount:-Counts the number of occurrences of each value in an integer array.
tf.sparse.bincount:-Count the number of times an integer value appears in a tensor.
Please take a look at this link [1](https://www.tensorflow.org/api_docs/python/tf/math/bincount) and [2](https://www.tensorflow.org/api_docs/python/tf/sparse/bincount) which provides more information.It helps.Thanks!

**Comment by ArrowIntoTheSky** [comment]
Hi @tilakrayal ! Thanks for the comment and sorry about the confusion. I have edited the issue description.

For `tf.sparse.bincount`, the output should have **length at most `maxlength`**, in the above code `maxlength` is `0`, so the output should be an **empty tensor**.
(`tf.math.bincount` is just to show that the output for `tf.sparse.bincount` should be have **same length**(not same value) as `tf.math.bincount`. )

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/e0d0eea36762e1b9fbf3ef8a295b2b22/53651.ipynb).

**Comment by cantonios** [comment]
This is a simple edge-case bug.  Will be fixed soon.
