### ISSUE TITLE
tf.sparse.segment_sum doesn't support complex dtypes

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53655]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
data = tf.complex(tf.random.uniform([3, 4], dtype=tf.float64),tf.random.uniform([3, 4], dtype=tf.float64))
segment_ids = [0,0,1]
res = tf.math.segment_sum(data=data,segment_ids=segment_ids) # pass
res_sp = tf.sparse.segment_sum(data=data,indices=tf.constant([0, 1, 2]),segment_ids=segment_ids) # InvalidArgumentError
```

**Describe the current behavior**
`tf.sparse.segment_sum` cannot accept a tensor of type `complex128`. However, `tf.math.segment_sum` do support it. 
For the above code snippet, the error message is:
```
InvalidArgumentError: Value for attr 'T' of complex128 is not in the list of allowed values: float, double, int32, uint8, int16, int8, int64, bfloat16, uint16, half, uint32, uint64
	; NodeDef: {{node SparseSegmentSum}}; Op<name=SparseSegmentSum; signature=data:T, indices:Tidx, segment_ids:Tsegmentids -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UINT16, DT_HALF, DT_UINT32, DT_UINT64]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]; attr=Tsegmentids:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> [Op:SparseSegmentSum]
```

**Describe the expected behavior**
`tf.sparse.segment_sum` should also support complex dtypes. Actually I would expect the valid types of `data` of `tf.sparse.segment_sum`  to be the same as `tf.math.segment_sum`, since the document of `tf.sparse.segment_sum` does not have this information.

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue. Attaching Gist in [2.6](https://colab.sandbox.google.com/gist/mohantym/82bdcdd01364e838e17ba09bdc46fe35/github_53655.ipynb#scrollTo=bP0HkuagQpt8) ,2.7  and [nightly ](https://colab.sandbox.google.com/gist/mohantym/f118d8aac7af27e0a9a5e5d61f3a25c7/github_53655.ipynb#scrollTo=2-mrSko-tzOy)for reference. Thank you!

**Comment by yongtang** [comment]
Added PR #54357 for complex support of tf.sparse.segment_sum.

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky !
I am able to replicate this issue in 2.11 . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/8fa5b93f4c0e7fb76d2cf18b752d4793/-53655.ipynb#scrollTo=RycgtC8AKNgi) for reference. 
Thank you!

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky,
The **tf.sparse.segment_sum** performs efficient summation operations on sparse tensors, and the complex numbers introduce additional computational complexity that can decrease the performance of the function.

If you need to perform segment-wise summation on sparse tensors with complex values, As the temporary workaround you can try using custom TensorFlow operations or consider alternative approach like `converting the complex values to real or imaginary components and performing the summation separately`.
Thank you!
