### ISSUE TITLE
tf.sparse.softmax lack support for float16

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53657]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
logits = tf.random.uniform([16, 1, 10], dtype=tf.float16)
r1 = tf.nn.softmax(logits,axis=-1) # pass
logits_sp = tf.sparse.from_dense(logits)
r2 = tf.sparse.softmax(logits_sp) # InvalidArgumentError
```

**Describe the current behavior**
`tf.sparse.softmax` cannot accept a tensor of type `float16`. However, `tf.nn.softmax` do support `half`. 
For the above code snippet, the error message is:
```
InvalidArgumentError: Value for attr 'T' of half is not in the list of allowed values: float, double
	; NodeDef: {{node SparseSoftmax}}; Op<name=SparseSoftmax; signature=sp_indices:int64, sp_values:T, sp_shape:int64 -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]> [Op:SparseSoftmax]
```

**Describe the expected behavior**
According to the document for `tf.sparse.softmax`, it is equivalent to `tf.nn.softmax` (but for sparse tensors), so `tf.sparse.softmax` should also support `float16` inputs.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with `tf-nightly-2.11.0-dev20220829` . Please find the gist [here](https://colab.research.google.com/drive/1MYXLhHnH2NoX9ktS4FtAc-jnznNtPRQj?usp=sharing). Thank you!
