### ISSUE TITLE
Compiling tensorflow/core/kernels/bincount_op.cc failed: (Exit 1): clang failed: error executing command

### ISSUE THREAD

**Issue by SefaZeng** [tensorflow/tensorflow#53668]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.7
- Python version: 3.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): 10.1.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Try to build the libtensorflowlite.so with select-tf-ops. I add `"//tensorflow/lite/delegates/flex:delegate"` to tensorflow/lite/BUILD. Then the Compilation failed.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
1. git clone https://github.com/tensorflow/tensorflow
2. cd tensorflow && ./configure
3. vim tensorflow/lite/BUILD && add "//tensorflow/lite/delegates/flex:delegate" to the deps of tensorflowlite
4. bazel build -c opt --cxxopt=--std=c++11 --fat_apk_cpu=arm64-v8a --config=android_arm64 //tensorflow/lite:libtensorflowlite.so --verbose_failures
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Full log:

> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=146
> INFO: Reading rc options for 'build' from /data/offline/deps/tensorflow/.bazelrc:
>   Inherited 'common' options: --experimental_repo_remote_exec
> INFO: Reading rc options for 'build' from /data/offline/deps/tensorflow/.bazelrc:
>   'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
> INFO: Reading rc options for 'build' from /data/offline/deps/tensorflow/.tf_configure.bazelrc:
>   'build' options: --action_env PYTHON_BIN_PATH=/root/miniconda2/envs/py36/bin/python3 --action_env PYTHON_LIB_PATH=/root/miniconda2/envs/py36/lib/python3.6/site-packages --python_path=/root/miniconda2/envs/py36/bin/python3 --define=PREFIX=/data/offline/deps/prefix --action_env ANDROID_NDK_HOME=/data/offline/deps/android-ndk-r21e --action_env ANDROID_NDK_API_LEVEL=21 --action_env ANDROID_BUILD_TOOLS_VERSION=30.0.2 --action_env ANDROID_SDK_API_LEVEL=30 --action_env ANDROID_SDK_HOME=/opt/android-sdk
> INFO: Reading rc options for 'build' from /data/offline/deps/tensorflow/.bazelrc:
>   'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
> INFO: Found applicable config definition build:short_logs in file /data/offline/deps/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
> INFO: Found applicable config definition build:v2 in file /data/offline/deps/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> INFO: Found applicable config definition build:android_arm64 in file /data/offline/deps/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
> INFO: Found applicable config definition build:android in file /data/offline/deps/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --define=with_xla_support=false
> INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (76 packages loaded, 4130 targets configured).
> INFO: Found 1 target...
> ERROR: /data/offline/deps/tensorflow/tensorflow/core/kernels/BUILD:6848:11: Compiling tensorflow/core/kernels/bincount_op.cc failed: (Exit 1): clang failed: error executing command 
>   (cd /root/.cache/bazel/_bazel_root/c8bef3cfd9e610c81b071433025995b0/execroot/org_tensorflow && \
>   exec env - \
>     ANDROID_BUILD_TOOLS_VERSION=30.0.2 \
>     ANDROID_NDK_API_LEVEL=21 \
>     ANDROID_NDK_HOME=/data/offline/deps/android-ndk-r21e \
>     ANDROID_SDK_API_LEVEL=30 \
>     ANDROID_SDK_HOME=/opt/android-sdk \
>     LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64 \
>     PATH=/data/offline/deps/cmdline-tools/tools:/data/offline/deps/cmdline-tools/tools/bin:/data/offline/deps/cmdline-tools/platform-tools:/root/miniconda2/envs/py36/bin:/root/miniconda2/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda/bin:/root/.ft:/root/.local/bin:/usr/local/bin:/root/bin:/usr/local/git/bin \
>     PWD=/proc/self/cwd \
>     PYTHON_BIN_PATH=/root/miniconda2/envs/py36/bin/python3 \
>     PYTHON_LIB_PATH=/root/miniconda2/envs/py36/lib/python3.6/site-packages \
>     TF2_BEHAVIOR=1 \
>   external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android '-D__ANDROID_API__=21' -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig '-Werror=return-type' '-Werror=int-to-pointer-cast' '-Werror=pointer-to-int-cast' '-Werror=implicit-function-declaration' -O2 -g -DNDEBUG -MD -MF bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/bincount_op.pic.d '-frandom-seed=bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/bincount_op.pic.o' -fPIC '-DS_IREAD=S_IRUSR' '-DS_IWRITE=S_IWUSR' '-DS_IEXEC=S_IXUSR' -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' -DSUPPORT_SELECTIVE_REGISTRATION -iquote . -iquote bazel-out/arm64-v8a-opt/bin -iquote external/gif -iquote bazel-out/arm64-v8a-opt/bin/external/gif -iquote external/eigen_archive -iquote bazel-out/arm64-v8a-opt/bin/external/eigen_archive -iquote external/com_google_absl -iquote bazel-out/arm64-v8a-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/arm64-v8a-opt/bin/external/nsync -iquote external/libjpeg_turbo -iquote bazel-out/arm64-v8a-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf -iquote external/double_conversion -iquote bazel-out/arm64-v8a-opt/bin/external/double_conversion -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm64-v8a-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm64-v8a-opt/bin/external/farmhash_archive -iquote external/png -iquote bazel-out/arm64-v8a-opt/bin/external/png -iquote external/zlib -iquote bazel-out/arm64-v8a-opt/bin/external/zlib -iquote external/highwayhash -iquote bazel-out/arm64-v8a-opt/bin/external/highwayhash -iquote external/icu -iquote bazel-out/arm64-v8a-opt/bin/external/icu -iquote external/fft2d -iquote bazel-out/arm64-v8a-opt/bin/external/fft2d -iquote external/gemmlowp -iquote bazel-out/arm64-v8a-opt/bin/external/gemmlowp -isystem external/gif -isystem bazel-out/arm64-v8a-opt/bin/external/gif -isystem external/eigen_archive -isystem bazel-out/arm64-v8a-opt/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/arm64-v8a-opt/bin/external/nsync/public -isystem external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf/src -isystem external/farmhash_archive/src -isystem bazel-out/arm64-v8a-opt/bin/external/farmhash_archive/src -isystem external/png -isystem bazel-out/arm64-v8a-opt/bin/external/png -isystem external/zlib -isystem bazel-out/arm64-v8a-opt/bin/external/zlib -isystem external/icu/icu4c/source/common -isystem bazel-out/arm64-v8a-opt/bin/external/icu/icu4c/source/common -w '--std=c++11' '-std=c++14' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -DTF_LEAN_BINARY -Wno-narrowing -fomit-frame-pointer -O2 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/core/kernels/bincount_op.cc -o bazel-out/arm64-v8a-opt/bin/tensorflow/core/kernels/_objs/portable_tensorflow_kernels/bincount_op.pic.o)
> Execution platform: @local_execution_config_platform//:platform
> Target //tensorflow/lite:libtensorflowlite.so failed to build
> INFO: Elapsed time: 942.540s, Critical Path: 321.94s
> INFO: 1130 processes: 48 internal, 1082 local.
> FAILED: Build did NOT complete successfully
> 
>

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by SefaZeng** [comment]
Change "//tensorflow/lite/kernels:builtin_ops_all_linked", to "//tensorflow/lite/kernels:builtin_ops", solve this issue.
