### ISSUE TITLE
Does tensorflow support structure of nested sequence like Paddle? Like "each timestep of the input sequence is also a sequence"?

### ISSUE THREAD

**Issue by cactiball** [tensorflow/tensorflow#5366]
For example, 

X=[[x11, x12, x13], [x21, x22], [x31, x32, x33, x34]], Y=[y1, y2, y3]. 
This way the initial state of the sequence could be initialized to **0** vector.

Thanks

**Comment by aselle** [comment]
It's not really clear what you are asking. However, it looks somewhat like sparse ragged arrays. You might look at our sparse tensor format. Also, this question is more of a TensorFlow usage question, so please re-ask in StackOverflow. GitHub issues is primarily for bugs, feature requests, etc. If you find that nobody's suggestions on StackOverflow are reasonable, then you can come back and request a specific feature.
