### ISSUE TITLE
Resurrecting Swift bindings / how much of the core C++ API can run on iOS?

### ISSUE THREAD

**Issue by philipturner** [tensorflow/tensorflow#53662]
I'm directly addressing TensorFlow's admins and maintainers of the core C/C++ code with this issue.

Before starting out, I am not using TensorFlow for _inference_ on iOS. I am doing _training_, which is orders of magnitude more difficult to support. It has never been done on a high-level, feature-complete ML framework except for [DL4S](https://github.com/palle-k/dl4s) (MPSGraph and ArrayFire don't count). Using an iPhone or iPad for training may seem strange, but I have numerous reasons for doing so (leaving out those reasons for brevity).

The existing TensorFlow training API is only compatible with macOS, Linux, and Windows. I am concerned with the C API used internally by [Swift for TensorFlow](https://github.com/tensorflow/swift-apis). iOS can't run Python, which means it certainly can't run the TensorFlow in this repository. However, Swift for TensorFlow brings an opportunity to take Python out of the equation. C and C++ can run on iOS, and I assume a lot of the code is platform-agnostic. Has anyone ever succeeded in training TensorFlow models on an Android device?

> Side note: I know Swift for TensorFlow is "archived", and I'm [fixing that](https://github.com/philipturner/swift-colab) right now. In fact, the Metal backend is part of S4TF's resurrection. I have had [extensive conversations](https://github.com/tensorflow/swift-apis/issues/1185) with several members of the original S4TF team (6 so far) and I know about the obstacles I will face.

Apple released a PluggableDevice implementation of GPU acceleration for Macs. However, it's closed-source, missing several ops it could support, and shuts out low-end Intel Macs. I'm looking for universal training support just like [DL4S](https://github.com/palle-k/dl4s). Is there any chance that I could reuse the C TensorFlow API as a component of my Metal backend for iOS?

This would save time and make DirectML acceleration for Swift for TensorFlow easier. Also, there are several ops like Cholesky grad which aren't in Metal Performance Shaders or Accelerate. I don't have the slightest clue how to implement them in CPU code. I assume that TensorFlow's core C API contains CPU kernels for those obscure ops.

One more thing - if I could use PluggableDevice for my backend, it would be much more in line with TensorFlow and less likely that my S4TF branch would diverge from main and eventually die. I'm approaching this  with the objective of realistically resurrecting S4TF. Whether TensorFlow's owners can change their mind and officially support my work has a massive impact on its long-term viability. How can I contact the people who have authority over this?

> Another side note: Apple just responded to me about an issue with syntax coloring in Xcode. I spent three months waiting for them without hearing back, and it should not have taken that long. I fear that Google will treat me the same way (part of the reason I'm not reaching out through private email), but hopefully it's going to be different this time.

**Comment by philipturner** [comment]
After scanning the core C/C++ code, there’s no mention of iOS - outside of TensorFlow Lite (again, not my goal). However, iOS and macOS are very similar, and the same can be said for Linux and Android. Are there any fundamental barriers to bringing it to iOS using macOS?

For example, loading a specific dynamic library at runtime, JIT compiling CPU code, relying on the structure of the macOS file system in a way that deviates from generic Darwin.

If I do find out how to modify the macOS code to run on iOS, how much of a chance is there for TensorFlow to merge my additions into main? I expect you might also want something similar for Android to make it equal and consistent.

I would be okay with keeping Swift for TensorFlow exclusive to desktop platforms initially, as long as I could guarantee it’s possible to train on iOS in the future. There are other problems (Swift autodiff) that currently prevent deployment on iOS anyway, which won’t be resolved for several months.

**Comment by philipturner** [comment]
CC: @sachinprasadhs

**Comment by philipturner** [comment]
@rohan100jain the information in this issue should be helpful: https://github.com/tensorflow/swift-apis/issues/1190

**Comment by philipturner** [comment]
@saeta I think you're the person I should be talking to.

**Comment by saeta** [comment]
Thank you so much @philipturner for reaching out!

> If it was archived for some other more serious or not publicly disclosable reason, I imagine that my request will be very controversial and require a lot of discussion internally at Google. That's why I'm reaching out to you and building support in the community so that Google can't say no 😄

The decision to archive S4TF was based on (among many other things) private discussions between two companies. Suffice it to say, while no one wanted to shut down S4TF, it was (unfortunately) not reasonable to continue forward with the project as envisioned at Google. Sorry!

That said, I'd be _delighted_ for you to take over the project and move things forward in whatever way you envision (feel free to fork it!). There will likely be a number of choices you'll have to make. S4TF evolved from targeting a library of kernels (i.e. TF's kernel library) to targeting XLA. (The reasons for doing this are beyond the scope of this comment, but I'd be happy to share.) The problem with this approach (historically) on iOS has been that JIT compilation was forbidden (it seems that this might have changed in the last year or so); as a result, I don't know of anyone who has tried getting XLA to work on iOS. (Related to this is your autodiff strategy; I see @ProfFan has [already mentioned the associated caveats](https://github.com/tensorflow/swift-apis/issues/1185#issuecomment-985143540).) This affects what C APIs you need, and what portion of the Core TensorFlow codebase must be ported to work on iOS.

Although I don't want to dissuade you, I'd be remiss if I didn't mention that I believe you can do some forms of on-device training with TFLite (although this won't save you from having to author the model in Python).

**Comment by philipturner** [comment]
If I can't use PluggableDevice, I'm planning to rip out XLA on most platforms and replace it with an open backend for MPSGraph and DirectML. The reason I need TensorFlow/Google's support is for publicity and maintainability purposes. I need to preserve the public API and a fork is destined to die.

> The decision to archive S4TF was based on (among many other things) private discussions between two companies. Suffice it to say, while no one wanted to shut down S4TF, it was (unfortunately) not reasonable to continue forward with the project as envisioned at Google. Sorry!

If possible, could you tell what company made Google shut down S4TF? Was it Apple going for Python TensorFlow? Given how many people are dissatisfied by it shutting down, there needs to be an answer for why that decision happened.

---

Would it be acceptable if Google sponsored a genuine successor that reused 90% of the code base but changed its name to omit TensorFlow? I have a problem with caching TensorFlow binaries, as my GitHub account doesn't allow uploading files larger than 25 MB (x10 binaries are 40 MB). So, without how it was before, I have to stay on TensorFlow 2.4.0 for platforms it will be the backend for (Google Colab and CUDA), using the last one-off builds Google ever made of x10.

There also might be licensing issues with that approach because of the way I'm setting up the successor. Is it possible to transfer ownership of the repository to another entity or allow me to preserve the commit history on a new repository without the restrictions of it being a GitHub fork? At a minimum, could there be one final addition to the S4TF README citing my [Swift-Colab](https://github.com/philipturner/swift-colab) and successor as spin-off projects like PythonKit and AutoDiff?

**Comment by philipturner** [comment]
I anticipate that what I'm about to hear next will not be very pleasing. In advance:

I knew all along that Google probably wasn't going to support this. Nonetheless, I pushed it 100% down the rabbit hole to guarantee they wouldn't help me. Moving forward, my objective will be more difficult, but it should still be possible. If I find the right people, I should be able to acquire the resources I need to bring Swift for TensorFlow back to life.

**Comment by philipturner** [comment]
@saeta when I made this post asking for Google’s support, I didn’t realize the following:
- I can post files larger than 25 MB on GitHub, using binary downloads from releases.
- I can make my own releases on a fork.
- I can enable issues and discussions on a fork made from S4TF.

This knowledge effectively solves my problems. Still the open-source community needs an answer for why Google stopped working on S4TF.
