### ISSUE TITLE
`tf.sparse.split` crashes when axis is a tuple

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53660]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
data = tf.random.uniform([1, 32, 32], dtype=tf.float32)
axis = [1, 2]
x = tf.sparse.from_dense(data)
result = tf.sparse.split(x,3, axis=axis) # crash
```
Session crashes. `tf.sparse.split` failed to do proper checking for `axis`.

**Describe the expected behavior**
`tf.sparse.split` should raise `InvalidArgumentError` when `axis` is not a 0-D tensor, instead of crashing.

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky ! According to this [document ](https://www.tensorflow.org/api_docs/python/tf/sparse/split#args) , Axis should be a 0-D int32 Tensor. Attaching resolved [Gist ](https://colab.sandbox.google.com/gist/mohantym/fc51468cd3f63bb48750f3c91c1795a6/github_53660.ipynb)for reference. Thank you!

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue? It's replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/599ed1f5134314a960fff561fc369737/github_53660.ipynb) ,[2.6 ](https://colab.sandbox.google.com/gist/mohantym/98348f4572ffac7b91f30d94f930644d/github_53660.ipynb#scrollTo=qjuBqEkMup9X)and [nightly](https://colab.sandbox.google.com/gist/mohantym/fec4b007291137635e74b18b70423929/github_53660.ipynb#scrollTo=qjuBqEkMup9X) .Thank you!

**Comment by yongtang** [comment]
Added a PR #53695 for the fix.
