### ISSUE TITLE
Do we have any way to avoid memory copy in tf.convert_to_tensor ?

### ISSUE THREAD

**Issue by JansonZhu** [tensorflow/tensorflow#53665]
**System information**
- TensorFlow version (use command below): 2.4.1

**Describe the current behavior**

Code:

```python
@tf.function
def inference(model, image):
    return model(image)


def test_model():
    model = tf.keras.Sequential([tf.keras.layers.Conv2D(filters=3, kernel_size=3)])

    np_image = np.random.randn(256, 256, 256, 3)
    model(np_image)
    # passing a python object to tf.function is not a recommend way, so this is slow.
    inference(model, np_image)

    tf_image = tf.convert_to_tensor(np_image)
    inference(model, tf_image)

    total_time = 0
    for _ in range(10):
        np_image = np.random.randn(256, 256, 256, 3)
        start_time = time.time()
        model(np_image)
        total_time += time.time() - start_time
    print("inference by model: {0} s".format(total_time))

    total_time = 0
    for _ in range(10):
        np_image = np.random.randn(256, 256, 256, 3)
        start_time = time.time()
        inference(model, np_image)
        total_time += time.time() - start_time
    print("inference by np_image: {0} s".format(total_time))

    total_time = 0
    for _ in range(10):
        np_image = np.random.randn(256, 256, 256, 3)
        tf_image = tf.convert_to_tensor(np_image)
        start_time = time.time()
        inference(model, tf_image)
        total_time += time.time() - start_time
    print("inference by tf_image: {0} s".format(total_time))
```

The result:

```txt
inference by model: 2.4521803855895996 s
inference by np_image: 2.472818374633789 s
inference by tf_image: 0.007699012756347656 s, convert time: 2.4546449184417725 s
```

My question is:

1. What does  `tf.convert_to_tensor` do ? Does it copy cpu data from numpy to tf.Tensor and also copy it to GPU ?
2. How can I avoid memory copy when using tf.convert_to_tensor ? In my case I will not modify the input image at all, so it's safe for me to make a memory view for the numpy data to tf.Tensor.
I can restrict the numpy data to be continuous and C order if it is needed.

From official docs I can find that it's recommended to create data from tf.data.Dataset which is already a tf.Tensor. But in my case we cannot use tf.data.Dataset API because I want to use some data which is mutable when training.

The alternative is to produce tf.Tensor by multiprocessing and push it to main process for training, but it will dump and reload the tf.Tensor object when using multiprocessing.Queue.
And I cannot run `tf.queue.FIFOQueue` in multiprocessing. Is this a good way to sharing tensor between different processes? (For numpy, we can use memmap to share numpy data.)

**Describe the expected behavior**

My expected behavior is that the convert time is very small.

**Comment by sushreebarsa** [comment]
@JansonZhu Could you please have a look at the similar [issue1](https://stackoverflow.com/questions/47519802/does-tensorflow-convert-to-tensor-do-memory-copy),[issue2](https://stackoverflow.com/questions/50109996/whats-the-difference-between-tf-constant-and-tf-convert-to-tensor) and [issue3](https://stackoverflow.com/questions/67116476/memory-leak-for-custom-tensorflow-training-using-tf-function) ?Please let us know if it helps?Thanks!

**Comment by JansonZhu** [comment]
Sorry, they don't help in my case.
I think an alternative is to support `tf.convert_to_tensor` with a specific cuda_stream, so that we can convert my data to cuda tensor in another cuda stream in background.
Notes: `tf.convert_to_tensor` can only be called in training process because passing tensor between processes is expensive, so we call it in a python thread. For this reason, we should support it without blocking python GIL.
Or is there any other api that can achieve it ?
