### ISSUE TITLE
Higher validation and test loss and lower accuracy using tf.data.dataset with tfrecords than using numpy

### ISSUE THREAD

**Issue by marzdeveloper** [tensorflow/tensorflow#53672]
**System information**
- OS Platform and Distribution : Kaggle and Colab gpu/tpu
- TensorFlow version (use command below): 2.4 on Kaggle, 2.7 on Colab
- GPU model and memory:tesla p100, colab tpu, kaggle tpu

Hi, I'm training and testing an LSTM network using kaggle notebooks. 
To improve time performance I have converted my numpy dataset to TFRecords, but the results are very differents respects results obtained with numpy dataset. I noticed this behavior either on GPU and TPU on Kaggle and Google Colab. 
I want to specify that the hyperparametrs and the dataset order is the same with numpy method and td.data.
I repeated the tests on differents file of the dataset many times but each time the validation and test accuracy are lower  and validation and test loss are higher using tf.data rsepect to using numpy.

With tf.data:
![accuracy](https://user-images.githubusercontent.com/48318112/148437400-86932751-279e-4ae3-96de-2a9c7c3589e3.png)
![loss](https://user-images.githubusercontent.com/48318112/148437401-a0529b6b-71f7-4d56-8604-86914565cc2f.png)

With numpy dataset:
![accuracy](https://user-images.githubusercontent.com/48318112/148437518-2eb912f8-5f37-496a-a0e6-a393b9b64d2a.png)
![loss](https://user-images.githubusercontent.com/48318112/148437522-f79ecc38-6681-42df-91ab-57fb00c0afdc.png)

Execution with tf.data:
```
Epoch 1/18
11929/11929 [==============================] - 323s 26ms/step - loss: 0.1282 - binary_accuracy: 0.9558 - auc: 0.8314 - precision: 0.7457 - recall: 0.6855 - val_loss: 1.6054 - val_binary_accuracy: 0.6283 - val_auc: 0.6912 - val_precision: 0.9549 - val_recall: 0.0453
2022-01-06 15:14:59.141498: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 146116, Output num: 3
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1641482099.138121196","description":"Error received from peer ipv4:10.0.0.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 146116, Output num: 3","grpc_status":3}
Epoch 2/18
11929/11929 [==============================] - 303s 25ms/step - loss: 0.0450 - binary_accuracy: 0.9862 - auc: 0.8506 - precision: 0.8013 - recall: 0.7681 - val_loss: 1.4894 - val_binary_accuracy: 0.7084 - val_auc: 0.8023 - val_precision: 0.9523 - val_recall: 0.2626
Epoch 3/18
11929/11929 [==============================] - 307s 26ms/step - loss: 0.0294 - binary_accuracy: 0.9915 - auc: 0.8516 - precision: 0.8214 - recall: 0.8078 - val_loss: 1.4176 - val_binary_accuracy: 0.7219 - val_auc: 0.8154 - val_precision: 0.9737 - val_recall: 0.2922
Epoch 4/18
11929/11929 [==============================] - 308s 26ms/step - loss: 0.0186 - binary_accuracy: 0.9947 - auc: 0.8534 - precision: 0.8326 - recall: 0.8298 - val_loss: 1.2668 - val_binary_accuracy: 0.7506 - val_auc: 0.8195 - val_precision: 0.9890 - val_recall: 0.3619
Epoch 5/18
11929/11929 [==============================] - 306s 26ms/step - loss: 0.0142 - binary_accuracy: 0.9961 - auc: 0.8542 - precision: 0.8387 - recall: 0.8378 - val_loss: 1.2077 - val_binary_accuracy: 0.7710 - val_auc: 0.8313 - val_precision: 0.9954 - val_recall: 0.4125
Epoch 6/18
11929/11929 [==============================] - 304s 25ms/step - loss: 0.0126 - binary_accuracy: 0.9965 - auc: 0.8548 - precision: 0.8432 - recall: 0.8397 - val_loss: 1.1289 - val_binary_accuracy: 0.7836 - val_auc: 0.8471 - val_precision: 0.9974 - val_recall: 0.4442
Epoch 7/18
11929/11929 [==============================] - 303s 25ms/step - loss: 0.0094 - binary_accuracy: 0.9975 - auc: 0.8555 - precision: 0.8470 - recall: 0.8455 - val_loss: 0.9592 - val_binary_accuracy: 0.8196 - val_auc: 0.8885 - val_precision: 0.9983 - val_recall: 0.5365
Epoch 8/18
11929/11929 [==============================] - 304s 26ms/step - loss: 0.0085 - binary_accuracy: 0.9978 - auc: 0.8559 - precision: 0.8478 - recall: 0.8463 - val_loss: 0.7648 - val_binary_accuracy: 0.8320 - val_auc: 0.9281 - val_precision: 0.9983 - val_recall: 0.5686
Epoch 9/18
11929/11929 [==============================] - 305s 26ms/step - loss: 0.0070 - binary_accuracy: 0.9982 - auc: 0.8561 - precision: 0.8498 - recall: 0.8481 - val_loss: 0.6531 - val_binary_accuracy: 0.8376 - val_auc: 0.9435 - val_precision: 0.9986 - val_recall: 0.5828
Epoch 10/18
11929/11929 [==============================] - 304s 25ms/step - loss: 0.0062 - binary_accuracy: 0.9984 - auc: 0.8565 - precision: 0.8506 - recall: 0.8491 - val_loss: 0.6175 - val_binary_accuracy: 0.8421 - val_auc: 0.9462 - val_precision: 0.9987 - val_recall: 0.5943
Epoch 11/18
11929/11929 [==============================] - 307s 26ms/step - loss: 0.0048 - binary_accuracy: 0.9987 - auc: 0.8567 - precision: 0.8514 - recall: 0.8501 - val_loss: 0.5576 - val_binary_accuracy: 0.8626 - val_auc: 0.9529 - val_precision: 0.9990 - val_recall: 0.6470
Epoch 12/18
11929/11929 [==============================] - 309s 26ms/step - loss: 0.0044 - binary_accuracy: 0.9988 - auc: 0.8568 - precision: 0.8520 - recall: 0.8514 - val_loss: 0.4787 - val_binary_accuracy: 0.8744 - val_auc: 0.9641 - val_precision: 0.9992 - val_recall: 0.6773
Epoch 13/18
11929/11929 [==============================] - 308s 26ms/step - loss: 0.0040 - binary_accuracy: 0.9989 - auc: 0.8568 - precision: 0.8526 - recall: 0.8521 - val_loss: 0.4774 - val_binary_accuracy: 0.8818 - val_auc: 0.9635 - val_precision: 0.9991 - val_recall: 0.6965
Epoch 14/18
11929/11929 [==============================] - 306s 26ms/step - loss: 0.0036 - binary_accuracy: 0.9990 - auc: 0.8568 - precision: 0.8528 - recall: 0.8522 - val_loss: 0.4594 - val_binary_accuracy: 0.8837 - val_auc: 0.9663 - val_precision: 0.9992 - val_recall: 0.7011
Epoch 15/18
11929/11929 [==============================] - 307s 26ms/step - loss: 0.0035 - binary_accuracy: 0.9990 - auc: 0.8568 - precision: 0.8529 - recall: 0.8517 - val_loss: 0.4588 - val_binary_accuracy: 0.8946 - val_auc: 0.9615 - val_precision: 0.9992 - val_recall: 0.7294
Epoch 16/18
11929/11929 [==============================] - 305s 26ms/step - loss: 0.0031 - binary_accuracy: 0.9991 - auc: 0.8568 - precision: 0.8534 - recall: 0.8529 - val_loss: 0.3980 - val_binary_accuracy: 0.9048 - val_auc: 0.9642 - val_precision: 0.9994 - val_recall: 0.7553
Epoch 17/18
11929/11929 [==============================] - 304s 26ms/step - loss: 0.0030 - binary_accuracy: 0.9991 - auc: 0.8569 - precision: 0.8532 - recall: 0.8528 - val_loss: 0.3670 - val_binary_accuracy: 0.9098 - val_auc: 0.9685 - val_precision: 0.9993 - val_recall: 0.7683
Epoch 18/18
11929/11929 [==============================] - 306s 26ms/step - loss: 0.0028 - binary_accuracy: 0.9992 - auc: 0.8569 - precision: 0.8533 - recall: 0.8526 - val_loss: 0.3948 - val_binary_accuracy: 0.9091 - val_auc: 0.9655 - val_precision: 0.9992 - val_recall: 0.7667
3497/3497 [==============================] - 83s 23ms/step - loss: 0.4007 - binary_accuracy: 0.9079 - auc: 0.9650 - precision: 0.9993 - recall: 0.7645
2022-01-06 16:43:10.007313: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 2652130, Output num: 3
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1641487390.006754880","description":"Error received from peer ipv4:10.0.0.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 2652130, Output num: 3","grpc_status":3}
```
Only with Kaggle TPU i have the following error as you can see just after first epoch validation and during testing, but the training run correctly and the program don't crash:

```
W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 2652130, Output num: 3
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1641487390.006754880","description":"Error received from peer ipv4:10.0.0.2:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 2652130, Output num: 3","grpc_status":3}
```
This problem occour also without this error on Kaggle GPU and Colab, so this error is specific on platform TPU Kaggle and is not related with the problem.

In the following link you can find my code with tfrecord write and read and all the process to get the dataset from tfrecord, model creation, fitting and testing:
[link code](https://colab.research.google.com/drive/1goQZL3xRU2vkBos04PZkWL2o1qHv8qul?usp=sharing)

Seems like to with tf.data the training start with lower validation accuracy value and increase more slowly compared to numpy dataset, so with a lot of epochs maybe also with tf.data can reach numpy accuracy level, is this comportament normal using tf.data or not?

**Comment by sushreebarsa** [comment]
@marzdeveloper I tried to replicate this issue on colab using TF [v2.7.0](https://colab.research.google.com/gist/sushreebarsa/9dbe6bd35372f742d1085de59c632df3/tf.ipynb#scrollTo=kbOvr83M16wU) , [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/761f60c0874a16364fa3d5538cfd8658/tf.ipynb#scrollTo=kbOvr83M16wU) and faced a different error as `NameError: name 'GCS_DS_PATH' is not defined` ,could you please have a look at the attached gists ? Please let us know if I am missing something to reproduce this issue. Thank you!

**Comment by marzdeveloper** [comment]
@sushreebarsa Now i published a part of dataset, in the attached code now you can find the GCS_DS_PATH definition which contains tfrecord files. While in this [link ](https://drive.google.com/drive/folders/1EKCf4YH1fau5Zpr78dCGNH6VmT5FnY5v?usp=sharing) you can find the same part in numpy, before the tfrecord transformation. So if you want run with tfrecord dataset just run the code in "Main with TFRecords" section. To run with numpy dataset please run the code in "Main with Numpy" but first download the dataset in this comment and obviously change the value of "path" variable in the code. If you want check the validity of conversion from numpy to TFRecords please run the code in "From numpy to TFRecords" section. If you need anything else let me know. Thank you!

**Comment by mohantym** [comment]
Hi @marzdeveloper !
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by marzdeveloper** [comment]
Hi @mohantym !
Thank you, but shouldn't this be a tensorflow.data problem?

**Comment by mohantym** [comment]
@marzdeveloper !Sorry for the late response!  Model should provide same accuracy irrespective of Dataset type. It has been seen earlier that  accuracy ,loss and performance differs when you used numpy array instead of tensors. So I think it should be more appropriate for keras repo. Thank you!
