### ISSUE TITLE
error executing command crosstool_wrapper_driver_is_not_gcc

### ISSUE THREAD

**Issue by Geremia** [tensorflow/tensorflow#53680]
**System information**
- OS Platform and Distribution: Slackware64 Linux (current), kernel 5.15.12
- TensorFlow installed from: source
- TensorFlow version: 2.4.0
- Python version: 3.9
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 11.2.0
- CUDA/cuDNN version: 11.5.50, 8.3.1.22
- GPU model and memory: Nvidia Quadro RTX 4000, 8GB

**the problem**

     # bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden --define=no_tensorflow_py_deps=true --define=no_nccl_support=true //native_client:libdeepspeech.so --config=cuda

gives 

```
ERROR: ~/DeepSpeech/tensorflow/tensorflow/stream_executor/cuda/BUILD:469:11: C++ compilation of rule '//tensorflow/stream_executor/cuda:cupti_stub' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/stream_executor/cuda/_objs/cupti_stub/cupti_stub.pic.d ... (remaining 141 argument(s) skipped)
In file included from ./tensorflow/core/platform/status.h:28,
                 from ./tensorflow/core/platform/errors.h:22,
                 from ./tensorflow/core/platform/env.h:27,
                 from ./tensorflow/stream_executor/lib/env.h:20,
                 from tensorflow/stream_executor/cuda/cupti_stub.cc:19:
bazel-out/k8-opt/bin/tensorflow/core/protobuf/error_codes.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
   17 | #error This file was generated by an older version of protoc which is
      |  ^~~~~
bazel-out/k8-opt/bin/tensorflow/core/protobuf/error_codes.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
   18 | #error incompatible with your Protocol Buffer headers. Please
      |  ^~~~~
bazel-out/k8-opt/bin/tensorflow/core/protobuf/error_codes.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
   19 | #error regenerate this file with a newer version of protoc.
      |  ^~~~~
In file included from ./tensorflow/core/platform/status.h:28,
                 from ./tensorflow/core/platform/errors.h:22,
                 from ./tensorflow/core/platform/env.h:27,
                 from ./tensorflow/stream_executor/lib/env.h:20,
                 from tensorflow/stream_executor/cuda/cupti_stub.cc:19:
bazel-out/k8-opt/bin/tensorflow/core/protobuf/error_codes.pb.h:47:51: error: 'AuxillaryParseTableField' in namespace 'google::protobuf::internal' does not name a type; did you mean 'AuxiliaryParseTableField'?
   47 |   static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                   AuxiliaryParseTableField
Target //native_client:libdeepspeech.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.015s, Critical Path: 8.56s
INFO: 123 processes: 98 internal, 25 local.
FAILED: Build did NOT complete successfully
```

**Comment by Geremia** [comment]
This seems due to protobuf issue "[mac Protobuf 3.12 AuxillaryParseTableField wrong spelling #7616](https://github.com/protocolbuffers/protobuf/issues/7616)".

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@Geremia 
Could you please upgrade to the latest tf version and let us know if you still face this issue, also please verify the [test build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) for compatibility

**Comment by Geremia** [comment]
@Saduf2019 Unfortunately, I have to build 2.4.0 for compatibility with [DeepSpeech](https://deepspeech.readthedocs.io/en/r0.9/BUILDING.html).

**Comment by mohantym** [comment]
Hi @Geremia !

We are checking to see whether you still need help in this issue . The commands in above command seems to be depreciated now .
Could you provide a new command to replicate this issue in 2.11 version.

Thank you!
