### ISSUE TITLE
framework not found TensorFlowLite

### ISSUE THREAD

**Issue by bhesaniyakrunal** [tensorflow/tensorflow#53684]
ld: warning: directory not found for option '-F/Users/mymac/Library/Developer/Xcode/DerivedData/Background-Remover-arhautmfeyumxqcubarflnbxmgsv/Build/Products/Debug-iphonesimulator/TensorFlowLiteSwift'
**ld: framework not found TensorFlowLite**
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i was try to solve last 2 - 3 days please help me

**Comment by mohantym** [comment]
Hi @bhesaniyakrunal ! Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) as it would help expedite the issue?

**Comment by miaout17** [comment]
+1 to what @mohantym said. Specifically it's unclear how to reproduce the issue.
