### ISSUE TITLE
API generation makes inheritance relationship confusing after r2.6

### ISSUE THREAD

**Issue by Lifann** [tensorflow/tensorflow#53686]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.6.0-rc2-32-g919f693420e 2.6.0
- Python version: Python 3.6.8

**Describe the current behavior**
I'm trying to select different algorithms by different optimizer, and got following unexpected behavior:
```python
import tensorflow as tf
from tensorflow.python.keras.optimizer_v2 import adam
from tensorflow.python.keras.optimizer_v2 import optimizer_v2

opt = tf.keras.optimizers.Adam(1E-3)
cond = isinstance(opt, optimizer_v2.OptimizerV2) # It expects true.
```

Before r2.6, everything works fine. But after r2.6, it will get false instead. I noticed that there is an API-gen process when exporting the APIs. And I make other tests.

```python
opt = tf.keras.optimizers.Adam(1E-3)
cond = isinstance(opt, optimizer_v2.OptimizerV2) # 2.6: false, 2.5: true
cond = isinstance(opt, tf.keras.optimizers.Optimizer) # 2.6: true, 2.5: true

opt = adam.Adam(1E-3)
cond = isinstance(opt, optimizer_v2.OptimizerV2) # 2.6: true, 2.5: true
cond = isinstance(opt, tf.keras.optimizers.Optimizer) # 2.6: false, 2.5: true
```

It seems that the APIs have an independent type system after r2.6. It makes code hard to manage when we need to extend some functionalities.

**Comment by sushreebarsa** [comment]
@Lifann 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
