### ISSUE TITLE
Training time is varying between docker and without docker 

### ISSUE THREAD

**Issue by rameshkunasi** [tensorflow/tensorflow#53690]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04. 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.4/8.2
- GPU model and memory:A6000 & 48GB

**Describe the current behavior**
If I use docker image tensorflow/tensorflow:latest-gpu container for training Convolution based neural network it is taking less time compared to Tensorflow installed using pip install tensorflow-gpu==2.7. 

**Describe the expected behavior**
If we use docker image/ installed using pip also the training should not change much

I am using tf.distribute.MirroredStrategy() to use all GPU's. How to resolve this issue?

**Comment by sushreebarsa** [comment]
@rameshkunasi 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rameshkunasi** [comment]
Sorry... We are using in built database, We cannot give that data and code here

**Comment by sushreebarsa** [comment]
@rameshkunasi If you're unable to provide  a code snippet of the reported issue , then it would be difficult for us to reproduce this one from our end .Could you please post this issue in [TF discussion](https://discuss.tensorflow.org/) forum where there is a larger community to get you the right help? Thanks!
