### ISSUE TITLE
Support reading data from HDFS with Kerberos

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#5369]
Now TensorFlow and read/write data from HDFS cluster. But we have tested that it doesn't support HDFS with Kerberos. The log looks like this.

![screen shot 2016-11-03 at 15 25 37](https://cloud.githubusercontent.com/assets/2715000/19958692/3415c576-a1dc-11e6-906b-7e4d4af63574.png)

### Environment info

Operating System: CentOS 7.0
TensorFlow Version: 0.11.0rc1

Refer to https://github.com/tensorflow/tensorflow/issues/5316

**Comment by aselle** [comment]
@jhseu, can you comment on this issue?  Also, for future reference, posting textual errors logs is much more useful, because they get indexed, so people who see similar errors in the future can search for them.

**Comment by jhseu** [comment]
I'm not too familiar with Kerberos, so I don't plan on working on this anytime soon. Contributions are welcome:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/platform/hadoop

**Comment by llhe** [comment]
I'll provide a patch for kerberos-enabled HDFS.

**Comment by girving** [comment]
Looks like @llhe fixed this.

**Comment by Karocyt** [comment]
It works perfectly fine for tensorflow, thanks a lot !

Would it be possible to apply the same kind of patch to standalone tensorboard ? It was working like a charm with HDFS but it doesn't as soon as Kerberos is involved...
