### ISSUE TITLE
NNAPI/Hexagon Support Through CMAKE on RB5 Arm Linux Platform

### ISSUE THREAD

**Issue by mrawding** [tensorflow/tensorflow#53692]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu 18.04 Qualcomm Linaro Release
- Qualcomm RB5
- Source
- TensorFlow version: v2.6
- Python version: 3.6
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source):  
- GCC/Compiler version (if compiling from source): gcc 7.5
- CUDA/cuDNN version: n/a
- GPU model and memory: Adreno GPU 650

Hello, I am having trouble understanding the tutorials and getting delegate support for Tensorflow lite c++/c library on the Qualcomm RB5.

I have been using ```CMAKE / GCC``` installation natively on board.

I have the following flags enabled ```-DTFLITE_ENBLE_XNN_PACK -DTFLITE_-DTFLITE_ENABLE_GPU -DTFLITE_ENABLE_NNAPI```

And I am able to compile a working(ish) library and do inferencing. However the only delegate that works is the XNN_PACK delegate. The GPU delegate causes the program to fail when specifying it (maybe not linking correct adreno library to the inferencing code)...could use some help there)

But mostly I am concerned about building NNAPI and HEXAGON delegate support. The RB5 has hexagon libraries already installed and I will also install the libhexagon_nn_skel.so libraries.

There is no documentation using cmake to enable hexagon support in the TensorFlow lite library and I see no flags in the CMakeLists.txt.

I have downloaded the Hexagon SDK and will copy the android_ndk _rc19 workspace to somewhere on board and set the path. Will this enable NNAPI correctly? Because now it does not believe it skips that compilation because it cannot find the correct headers (not installed yet)

Basically I have the following questions:

1) Will moving the android_rc19_ndk to a directory on board the RB5 and setting ANDROID_NDK_HOME successfully compile the NNAPI delegate ?

2) How can I enable hexagon support with the CMake Installation of the TfLite ? All hexagon libraries are on board.

3) What are the correct library links to use to successfully enable a GPU delegate on the Adreno GPU? I see existing support documented on the tensorflow website for this.

4) If none of the three on board are viable - Would building with Bazel on board work? Or do we need to do a cross compilation, if so how?

Thank you for taking the time to read this. I really enjoy using tensorflow lite and I know the RB5 community would really enjoy a documented process to do this correctly and unlock all of it's potential.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by sachinprasadhs** [comment]
Can you have a look into [this](https://www.tensorflow.org/lite/performance/hexagon_delegate#hexagon_delegate_c_api) document on Hexagon delegate C API and also check these [FAQs](https://www.tensorflow.org/lite/performance/hexagon_delegate#faq) on Hexagon delegate. Let us know if there is anything missing which you are looking for. Thanks!

**Comment by St190706025** [comment]
How can ı run hexagon delegate on tensorflow that which version? I am working on object detection. But FPS is not enough for my homework. Can please help me?
