### ISSUE TITLE
TensorBoard doesn't work on IOS/IpadOS. Requires apple icons. 

### ISSUE THREAD

**Issue by NikitaGordia** [tensorflow/tensorflow#53696]
After starting the server it gives the following result:

W0107 19:43:36.780149 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.798506 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.832389 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.849392 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.900132 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.915132 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.948019 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.965894 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404

And in afterwards you can not access tensorboard on apple devices (tested on Iphone 8, iphone 11, ipad 2018). but on android/chome(macos) works great

**Comment by sushreebarsa** [comment]
@NikitaGordia 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!

**Comment by NikitaGordia** [comment]
no. it is clear

**Comment by sushreebarsa** [comment]
@NikitaGordia This issue is more related to TensorBoard ,could you please post this issue in [TensorBoard](https://github.com/tensorflow/tensorboard/issues) repo to get the right help?Thank you!

**Comment by NikitaGordia** [comment]
Yeah, thank you, I missed it. Just moved to the tensorboard repo
