### ISSUE TITLE
ValueError: Exception encountered when calling layer "transformer_decoder_3" (type TransformerDecoder).  Could not find matching concrete function to call loaded from the SavedModel

### ISSUE THREAD

**Issue by MrBuzzy4** [tensorflow/tensorflow#53699]
<em>I got this error, while trying to load my transformer model. </em>

Model:
>Layer (type)          ==         Output Shape    ==     Param #   ==  Connected to                     
>=============================================================================================>=====
> encoder_inputs (InputLayer)      ==  [(None, None)]  ==     0    ==       []                               
 >                                                                                                 
 >positional_embedding_6 (Positi    == (None, None, 256)==   645120  ==    ['encoder_inputs[0][0]']         
 >onalEmbedding)                                                                                   
  >                                                                                                
 >decoder_inputs (InputLayer)      ==  [(None, None)]  ==     0    ==       []                               
  >                                                                                                
 >transformer_encoder_3 (Transfo    == (None, None, 256) ==  3155456   ==  ['positional_embedding_6[0][0]'] 
 >rmerEncoder)                                                                                     
 >                                                                                                 
 >model_7 (Functional)      ==     (None, None, 2500) ==  6547140  ==   ['decoder_inputs[0][0]',         
  >                                                                                                                 'transformer_encoder_3[0][0]']  
   >                                                                                               
>==================================================================================================

Error:
>ValueError: Exception encountered when calling layer "transformer_decoder_3" (type TransformerDecoder).
>
>Could not find matching concrete function to call loaded from the SavedModel. Got:
 > Positional arguments (4 total):
   > * Tensor("inputs:0", shape=(None, None, 256), dtype=float32)
   > * Tensor("encoder_outputs:0", shape=(None, None, 256), dtype=float32)
   > * None
   > * False
  >Keyword arguments: {}
>
> Expected these arguments to match one of the following 2 option(s):
>
>Option 1:
 > Positional arguments (4 total):
  >  * TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs')
   > * TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='encoder_outputs')
    >* TensorSpec(shape=(None, None), dtype=tf.bool, name='mask')
    >* False
  >Keyword arguments: {}
>
>Option 2:
 > Positional arguments (4 total):
  >  * TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='inputs')
   > * TensorSpec(shape=(None, None, 256), dtype=tf.float32, name='encoder_outputs')
    >* TensorSpec(shape=(None, None), dtype=tf.bool, name='mask')
    >* True
 > Keyword arguments: {}
>
>Call arguments received:
 > • args=('tf.Tensor(shape=(None, None, 256), dtype=float32)',)
 > • kwargs={'encoder_outputs': 'tf.Tensor(shape=(None, None, 256), dtype=float32)', 'training': 'None'}

I also got this warning, while saving model.
>WARNING:absl:Found untraced functions such as embedding_12_layer_call_fn, embedding_12_layer_call_and_return_conditional_losses, embedding_13_layer_call_fn, embedding_13_layer_call_and_return_conditional_losses, multi_head_attention_9_layer_call_fn while saving (showing 5 of 150). These >functions will not be directly callable after loading.

**Important Notice**

GOOGLE COLAB
https://colab.research.google.com/drive/1vhJiMvCnxT7y4KhMv7wez_zBqwI-7yqu?usp=sharing

**Comment by tilakrayal** [comment]
@MrBuzzy4 ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by BernardoOlisan** [comment]
@MrBuzzy4 I'm facing with the same problem, did you solved it?
