### ISSUE TITLE
Will experimental_distribute_dataset or experimental_distribute_datasets_from_function distribute same data in more than one batch ?

### ISSUE THREAD

**Issue by kabilan6** [tensorflow/tensorflow#53693]
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.2
-   **Python version**: 3.8
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**: 
-   **Exact command to reproduce**:

### Describe the problem
am using tensorflow 2.2, Noticed same data being distributed in multiple batches/data shard . total batch count and no of records in each batch matched to expected count but the records present in each batch isn't unique.  Strategy - Multiworker mirror strategy

### Source code / logs
I won't be able to share the codes here. but am using multiworker mirror strategy with unbatch, batch and autoshard policy of data.

**Comment by tilakrayal** [comment]
@kabilan6 ,
We see that you are using tf version 2.2, which is not actively supported, please update to v2.7 and let us know if you are using same issue.

**Comment by kabilan6** [comment]
I tried upgrade to v2.7, but i'm getting this error
AttributeError: 'Tensor' object has no attribute '_keras_mask'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield                   
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 346, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 699, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

same code runs fine with v2.2

**Comment by tilakrayal** [comment]
@kabilan6 ,
Please take a look at this link [1](https://github.com/tensorflow/tensorflow/issues/42403#issuecomment-751622363) and [2](https://github.com/tensorflow/tensorflow/issues/36624) with the similar error.It helps.Thanks!
