### ISSUE TITLE
Select TF Ops build output a large library file.

### ISSUE THREAD

**Issue by SefaZeng** [tensorflow/tensorflow#53708]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.7
- Python version: 3.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): 10.1.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Try to add Select TF Ops to the libtensorflowlite.so and it outputs a large binary file about 180MB in linux gcc and 90+ MB in cross-compilation for android. Is there a way to reduce the size of library ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I follow the guide of [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/reduce_binary_size.md](url) to get a BUILD file and a shared library with Select TF Ops. But it seems the size of the library is almost the same as 

> Add the TensorFlow ops delegate library dependency to the build dependencies: tensorflow/lite/delegates/flex:delegate.
It's to large for mobile deploy and is there any ways to reduce it?

The BUILD file is:
```
load(       
    "//tensorflow/lite:build_def.bzl",
    "tflite_custom_cc_library",
    "tflite_cc_shared_object",
)        
load(       
    "@org_tensorflow//tensorflow/lite/delegates/flex:build_def.bzl",
        "tflite_flex_shared_library"
)        
         
tflite_flex_shared_library(
  name = "tensorflowlite_flex",
  models = [
      ":model.tflite",
  ],        
)        
         
tflite_custom_cc_library(
    name = "selectively_built_cc_lib",
    models = [ 
        ":model.tflite",
    ],   
)        
         
# Shared lib target for convenience, pulls in the core runtime and builtin ops.
# Note: This target is not yet finalized, and the exact set of exported (C/C++)
# APIs is subject to change. The output library name is platform dependent:
#   - Linux/Android: `libtensorflowlite.so`
#   - Mac: `libtensorflowlite.dylib`
#   - Windows: `tensorflowlite.dll`
tflite_cc_shared_object(
    name = "tensorflowlite",
    # Until we have more granular symbol export for the C++ API on Windows,
    # export all symbols.
    features = ["windows_export_all_symbols"],
    linkopts = select({
        "//tensorflow:macos": [
            "-Wl,-exported_symbols_list,$(location //tensorflow/lite:tflite_exported_symbols.lds)",
        ],
        "//tensorflow:windows": [], 
        "//conditions:default": [
            "-Wl,-z,defs",
            "-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)",
        ],
    }),  
    per_os_targets = True,
    deps = [
        ":selectively_built_cc_lib",
        "//tensorflow/lite:tflite_exported_symbols.lds",                                                                                          
        "//tensorflow/lite:tflite_version_script.lds",
    ],   
)
```
The build command:
`bazel build -c opt --cxxopt=--std=c++14 --config=monolithic --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/tmp:libtensorflowlite_flex.so`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@SefaZeng ,
Can you please provide the error log to debug the issue.It helps to analyse the issue.Thanks!

**Comment by SefaZeng** [comment]
> @SefaZeng , Can you please provide the error log to debug the issue.It helps to analyse the issue.Thanks!

Hi @tilakrayal , there is no such error log. I get a tflite shared library with select tf ops. And my model can load by this library. But I want to know is there any ways to reduce the library size as it's to large for mobile deployment. I followed the "reduce the size" guide but it did not reduce library size.

**Comment by mohantym** [comment]
Hi @SefaZeng ! Can you check this [comment](https://github.com/tensorflow/tensorflow/issues/55835#issuecomment-1118039625) on Selective builds? Thanks!

**Comment by FengMu1995** [comment]
@SefaZeng did you solve the probelm?
Can you share how do you use the libtensorflowlite_flex.so in your project. I build the project with cmake, but I don't know how to llink and use the lib.

**Comment by paazca** [comment]
I've run into the same issue.

`tflite_flex_shared_library` ignores my model and outputs the full Select TF Ops library, instead of building only the needed operators.

**Comment by CuriousSingularity** [comment]
Hi @paazca were you able to solve the problem? I am currently having the same difficulty even in latest 2.13 version. 
thank you.
