### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by gyurmey** [tensorflow/tensorflow#53706]
pardon me for being new veteran on this. i still cannot figure this error after i try to train the model, it end up with this error. after few search, have a clue that it might be Mac issue.

My mac is macOS Catalina and version 10.15.2.

Thank you in advance ^^

![Screen Shot 2022-01-09 at 10 24 30 PM](https://user-images.githubusercontent.com/15898245/148703921-5db43328-a512-4ba5-a343-ade0aaeaee86.png)

**Comment by sushreebarsa** [comment]
@gyurmey 
In order to reproduce the issue reported here, could you please provide the error in text format, complete code , the dataset , tensorflow version you are using?Thanks!

**Comment by gyurmey** [comment]
@sushreebarsa thanks for the reply ^^

error is Segmentation fault: 11 
tensorflow version is 2.7.0

**Comment by sushreebarsa** [comment]
@gyurmey 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
