### ISSUE TITLE
Conflict between two libraries of source-built and prebuilt (conda) TensorFlow

### ISSUE THREAD

**Issue by rangsimanketkaew** [tensorflow/tensorflow#53704]
Hi Folks,

I installed prebuilt TensorFlow (TF) 2.6 using conda and compiled the same version from the source using bazel. I am able to call/import TF in Python but when adding the built shared libraries to the lib env variable (`LD_LIBRARY_PATH`), I got the following error about a conflict between two TF libraries.

These codes work well:

```sh
Python 3.9.0 (default, Nov 15 2020, 14:28:56)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2022-01-09 16:31:59.785672: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-09 16:31:59.785714: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

But these codes yielded the error in question (suppose that shared libs are stored in `/usr/local/tensorflow/lib/`):

```
export LD_LIBRARY_PATH=/usr/local/tensorflow/lib/:$LD_LIBRARY_PATH

Python 3.9.0 (default, Nov 15 2020, 14:28:56)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: descriptor_table_tensorflow_2fcore_2fprotobuf_2fdata_5fservice_2eproto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 79, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: descriptor_table_tensorflow_2fcore_2fprotobuf_2fdata_5fservice_2eproto

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
>>>
```

**Comment by mohantym** [comment]
Hi @rangsimanketkaew ! The error is about configuring GPU support . You need to point the respective Cuda files after downloading them in your local machine. You can refer these thread to configure GPU support on your machine.Link [1](url) ,[2 ](https://www.analyticsvidhya.com/blog/2020/11/how-to-download-install-and-use-nvidia-gpu-for-tensorflow-on-windows/) Thank you!

**Comment by rangsimanketkaew** [comment]
> Hi @rangsimanketkaew ! The error is about configuring GPU support . You need to point the respective Cuda files after downloading them in your local machine. You can refer these thread to configure GPU support on your machine.Link [1](url) ,[2 ](https://www.analyticsvidhya.com/blog/2020/11/how-to-download-install-and-use-nvidia-gpu-for-tensorflow-on-windows/) Thank you!

IIUC, the error was at this line `ImportError: /home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: descriptor_table_tensorflow_2fcore_2fprotobuf_2fdata_5fservice_2eproto` which I think that the conflict is relevant to the protobuf, not GPU support.

**Comment by mohantym** [comment]
Ok @rangsimanketkaew ! First suggestion on LD_LIBRARY_PATH was upon this[ thread](https://www.tensorflow.org/install/gpu#linux_setup). For the this [error ](https://github.com/tensorflow/tensorflow/issues/53704#issuecomment-1009240177), You can try upgrading the protobuf version . Attaching relevant thread for  [Reference ](https://github.com/tensorflow/tensorflow/issues/12326#issuecomment-346314550). Please don't mix conda installation of Tensorflow with Build from source installation in one environment. Thank you.

**Comment by rangsimanketkaew** [comment]
Hi @mohantym Thanks for the suggestions. I've tried upgrading the protobuf to the newer version (4.x) but it didn't work.

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by sachinprasadhs** [comment]
Could you please try creating a new environment and try only with build from source and let us know if you face any error. Thanks!

**Comment by sachinprasadhs** [comment]
If your issue is resolved, could you please close this issue. Thanks!
