### ISSUE TITLE
Is tensorflow threadsafe in feedforward prediction of trained models.

### ISSUE THREAD

**Issue by jungle-cat** [tensorflow/tensorflow#5371]
#### Question:

I'ved trained a text classification model using tensorflow and also wrapped Java interface for feedward prediction. And I'm wondering if tensorflow is threadsafe in feedforward prediction. 

Thanks

**Comment by aselle** [comment]
This question is better addressed on StackOverflow. Also, your question is ill-posed. Thread safety is not a simple concept. It is more a question of is it thread-safe to use something in a particular way. For someone to answer this question, you need to describe the context in which you are going to be setting up your feedforward prediction infrastructure.
