### ISSUE TITLE
Option to check every write in TFRecordWriter.

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#5372]
Referencing this [post](http://stackoverflow.com/questions/40370866/tf-corrupted-record-while-training/40396754#40396754) on stackoverflow.

There may be situations when we write huge databases of images into a TFRecord (or at least a few TFRecords). It would be good if there's an option to check every write to prevent such cases of corrupted data happening during training.

@allenlavoie

**Comment by llhe** [comment]
@jkschin You mentioned you have run twice, so did you use the same TFRecord file or recreate it for each run?

If it's the first case, I guess you are using local disk. It might be just corruption in the IO path, like **broken disk**, bugs in IO controllers, non-ECC memory and bit rot etc. But this should be rare. Using checksum-ed auto recovery (by either duplication or EC code) file system like GFS, HDFS (or simply RAID) can avoid most of the problems. I think **check every write to prevent such cases of corrupted data happening** is not the responsibility of tensorflow.

If it's the second case, it may be a bug.

**Comment by jkschin** [comment]
@llhe, I could recreate the error. I used the same TFRecord file 4 times. I decided to recreate the TFRecord. It worked.

**Comment by jkschin** [comment]
@llhe the case of corrupted data is definitely something that happens locally. It's probably a black swan event. I'll close this as it's probably not wise to implement such a thing.

**Comment by llhe** [comment]
@jkschin @allenlavoie May be adding an option **Ignore corrupted record silently** in the reader is a reasonable feature request? Looks like many TF users use poor unstable storage but processing **big** data which data corruption is not that rare.
