### ISSUE TITLE
Inference time jumps for varying batch size

### ISSUE THREAD

**Issue by parneetk** [tensorflow/tensorflow#53725]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes [Link below]
- OS Platform and Distribution (Ubuntu 18.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version: Tested on 2.6, 2.4
- Python version: 3.6
- CUDA/cuDNN version: Tested on 1) CUDA 10.1+cudnn 7, 2) CUDA 11.1 + cudnn 8
- GPU model and memory: Tested on 1) Tesla P100, 16GB , 2) Quadro P4000, 8GB

**Current behavior**

When running classifier inference on GPU, if an input batch size is seen for the first time, the inference time is more than expected. In subsequent runs for the same input batch size, the inference time reduces. When the inference time jump is observed, the load shifts to CPU (GPU usage drops in nvidia-smi) while on subsequent inferences the load is on GPU.

Example 1: 

![figure1_tf_expt_1](https://user-images.githubusercontent.com/3059405/148972390-3c2f86bc-bc50-44f7-ab77-a2ce78012ed2.png)

For a random batch size, the inference time on `run 2` reduces because it is seen in `run 1`. In `run 3`, all the batch sizes are seen in `run 2` and their inference time reduces.

Example 2: 

![figure2_tf_expt_2](https://user-images.githubusercontent.com/3059405/148972415-0c4a74a5-9084-46c7-8b27-b757a257869b.png)

For 10 random batch sizes, the inference time in `run 2` reduces because all these batches are seen in `run 1`. In `run 3`, all the batch sizes are seen in `run 2` and their inference time reduces.

**Why is this relevant?**

Suppose we have a video sequence with varying number of objects every few frames (i.e., the batch size=number of objects varies every few frames). Every time there are total number of objects in a frame that have not been seen before, there is a jump in inference time. For example, if there are 10 objects in the first 30 frames and then there are 8 objects in the next frame, an inference time jump is observed for this frame. In a product with real time expectations, this can have system level implementations on other modules.

**Expected behavior**

Inference time jumps should not be observed with varying batch sizes as it can have system level implications. This behavior is not observed with PyTorch.
An easy solution is to run classifier inference with all batch sizes on dummy images during initialization. For example, we can run inference for batch sizes from 1 to 64 if maximum expected objects are 64. However, that's more of a hack. I am interested in understanding the reason behind this issue. Looks like it has something to do with memory allocation - but why is it dependent on batch size? Is there a better Tensorflow configuration or inference function or memory allocation that can help resolve it?

**Standalone code to reproduce the issue**

Jupyter notebook in Colab:
https://colab.research.google.com/drive/1fHy3HcrYBskMLy-nNn12bbwBI-QIxg1c?usp=sharing

This notebook uses model() for inference. Using model.predict(), gives similar results.

**To enable GPU in Colab, select GPU**

Runtime -> Change Runtime Type -> Hardware Accelerator -> Select GPU from drop down

**Comment by sushreebarsa** [comment]
@parneetk I tried to replicate this issue on colab using TF v2.7.0 , tf-nightly(2.9.0-dev20220111) and faced different error in 
 tf-nightly, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/13f317728b0d420611d8b4d8531b5201/expt_variable_batch_size.ipynb#scrollTo=trURuyQLMyNO) for reference. Please confirm the same.Thanks!

**Comment by parneetk** [comment]
@sushreebarsa I did not install tf-nightly and used default TF of colab environment (v2.7.0). Not sure why colab shows an error for you and not me. I verified again and it seems to run without any errors.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
