### ISSUE TITLE
How can I uninstall tensorflow built in the v-environment of ubuntu-20.04?

### ISSUE THREAD

**Issue by wuliJerry** [tensorflow/tensorflow#53724]
I have tried both "sudo pip uninstall tensorflow-2.7.0" and "sudo pip uninstall tensorflow" in both normal environment and the v-environment which I installed the tensorflow before, but they all just display "WARNING: Skipping tensorflow as it is not installed.".
I check the "pip list" in the v-environment to see whether the tensorflow still exist, but as the picture, it just right there,safe and sound.
So how can I deal with it to uninstall it? Thanks for your help in advance
<img width="364" alt="微信图片_20220111233045" src="https://user-images.githubusercontent.com/95178820/148972571-8e7f8b1f-7de1-4389-b983-7271125f5515.png">
<img width="479" alt="微信图片_20220111233050" src="https://user-images.githubusercontent.com/95178820/148972602-72f6fcb2-3976-4292-847a-80ae46456697.png">
.

**Comment by tilakrayal** [comment]
@wuliJerry ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/55366503/problems-cannot-installing-uninstalling-tensorflow) and the issue [1](https://github.com/tensorflow/tensorflow/issues/8785), [2](https://askubuntu.com/questions/764032/how-to-uninstall-tensorflow-completely) and [3](https://sparrow.dev/uninstall-tensorflow-troubleshooting/) with the similar error.It helps.Thanks!
