### ISSUE TITLE
Flatten return null with DenseNet121

### ISSUE THREAD

**Issue by bbday** [tensorflow/tensorflow#53731]
python 3.7.9 (windows 11 x64)
tensorflow-gpu 2.7.0

```
from tensorflow.python.keras.applications.densenet import DenseNet121
from tensorflow.keras.applications.resnet_v2 import ResNet50V2
from tensorflow.keras.layers import Dense, Flatten

input_shape = (110, 110, 3)
base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=input_shape)
#base_model = ResNet50V2(weights='imagenet', include_top=False, input_shape=input_shape)

x = base_model.output
x = Flatten()(x)

```

Error: _(if i use ResNet50V2 not happen)_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python37\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "...\Python37\site-packages\tensorflow\python\framework\constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Exception encountered when calling layer "flatten_1" (type Flatten).

Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

Call arguments received:
  • inputs=<KerasTensor: shape=(None, 3, 3, 1024) dtype=float32 (created by layer 'relu')>

**Comment by tilakrayal** [comment]
@bbday ,
Please take a look at this SO [link](https://stackoverflow.com/questions/44176982/how-does-the-flatten-layer-work-in-keras) and [issue](https://github.com/keras-team/keras/issues/12870) with the similar error.It helps.Thanks!
