### ISSUE TITLE
Padding batches with high ranks (>=6) doesn't work

### ISSUE THREAD

**Issue by DanBmh** [tensorflow/tensorflow#53735]
### System information

-   **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **TensorFlow installed from (source or binary)**: Nvidia docker (nvcr.io/nvidia/tensorflow:21.08-tf2-py3)
-   **TensorFlow version (use command below)**: 2.5 (default installation) / 2.7 (updated with pip), doesn't work for both
-   **Python version**: 3.8.10
-   **CUDA/cuDNN version**: 11.4

### Describe the problem
Padding batches with high ranks (>=6) doesn't work and raise an `tensorflow.python.framework.errors_impl.UnimplementedError: CopyElementToLargerSlice Unhandled rank: 6` error.

### Source code / logs
```python3
# Rank 5 is working
import tensorflow as tf
a = {"x": tf.ones([1, 1, 1, 1, 1])}
b = {"x": tf.ones([1, 1, 1, 1, 2])}
labels = [a, b]
ds = tf.data.Dataset.from_generator(lambda: iter(labels), output_types={"x": tf.float32})
ds = ds.padded_batch(2, padded_shapes={"x": [None, None, None, None, None]})
list(ds.take(1))
# [{'x': <tf.Tensor: shape=(2, 1, 1, 1, 1, 2), dtype=float32, 
#    numpy=array([[[[[[1., 0.]]]]], [[[[[1., 1.]]]]]], dtype=float32)>}]

# Rank 6 doesn't
import tensorflow as tf
a = {"x": tf.ones([1, 1, 1, 1, 1, 1])}
b = {"x": tf.ones([1, 1, 1, 1, 1, 2])}
labels = [a, b]
ds = tf.data.Dataset.from_generator(lambda: iter(labels), output_types={"x": tf.float32})
ds = ds.padded_batch(2, padded_shapes={"x": [None, None, None, None, None, None]})
list(ds.take(1))
# Throws below error
```

Full error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 800, in __next__
    return self._next_internal()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 783, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2845, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnimplementedError: CopyElementToLargerSlice Unhandled rank: 6 [Op:IteratorGetNext]
```

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.7,v2.5 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/a6414e3fa844c224f5de5a8f0e6a7d08/53735.ipynb).

**Comment by sachinprasadhs** [comment]
This is because only till Rank 5, case is handled, anything above that rank will throw the unimplemented error. 
Is there any specific need for Rank above 5 in general use case scenarios.

**Comment by DanBmh** [comment]
My usecase was 3d-action-recognition, with a shape of [persons, timesteps, x, y, z, joints]

The workaround was reshaping the tensor before padding (in this case [x,y,z]->[x*y*z]) and reshaping it back after batching.

**Comment by DanBmh** [comment]
I'm currently ok with the workaround. 

Is there so much logic behind the padding step? I didn't thought it was restricted to a maximal rank before.

**Comment by sachinprasadhs** [comment]
It's base implementation is in C++ and you can see the logic here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/batch_util.cc#L386-L395 which is having the defined cases for rank.
