### ISSUE TITLE
tf.assign_from_checkpoint_fn needs write_version argument to pass to tf.Saver

### ISSUE THREAD

**Issue by nmhkahn** [tensorflow/tensorflow#5373]
Hi,
according to [slim_walkthrough.ipython](https://github.com/tensorflow/models/blob/master/slim/slim_walkthough.ipynb), when we load from checkpoints we can use `assign_from_checkpoint_fn` function.

But (maybe i thought) inside of `slim.assign_from_checkpoint_fn`, it create `tf.Saver` but there is no `write_version` args. And in my case, I have some ckpt with saver V2 but default saver version is 1 and `slim.assign_from_checkpoint_fn` doesn't have any code about this version issue so I can't load model using this function.

Any clue or plan to handle this issue?
Thanks.

**Comment by aselle** [comment]
It looks like this request is to get write_version added as an argument to tf.assign. Could you take this on @concretevitamin or comment on what a better way to solve this problem might be. Thanks!

**Comment by concretevitamin** [comment]
@nmhkahn: if I understand you correctly, I think you 
1. Used the master branch to produce a V2 checkpoint.
2. Try to load it with some code (in this case, some contrib code) in an official release (or candidate).

This is not a supported use case.  If you do your second step also in master, it should work (I pushed out the default version switch this week).

**Comment by nmhkahn** [comment]
I see. thanks for comment!
