### ISSUE TITLE
Small mathematical typo at https://www.tensorflow.org/guide/basics

### ISSUE THREAD

**Issue by urrutiag** [tensorflow/tensorflow#53745]
## URL(s) with the issue:

https://www.tensorflow.org/guide/basics

### Clear description

Currently: 
At x = 1.0, y = f(x) = (1**2 + 3 - 5) = -2

Proposed:
At x = 1.0, y = f(x) = (1**2 + 2 - 5) = -2

### Submit a pull request?

Yes, I can submit a pull request if issue approved

**Comment by urrutiag** [comment]
will transfer issue to tensorflow/docs

**Comment by urrutiag** [comment]
Nevermind, just read 'To file a docs issue, use the issue tracker in the tensorflow/tensorflow repo.'

**Comment by tilakrayal** [comment]
@urrutiag ,
Please feel free to submit a PR for the requested change or share the link where requested change is to be made

**Comment by Cheril311** [comment]
have solved this issue and submitted a PR

**Comment by urrutiag** [comment]
Thanks @Cheril311! Appears fixed on the guide.
