### ISSUE TITLE
Problems with xla and dynamic LinearOperatorBlockDiag. Issues developing custom XLA op

### ISSUE THREAD

**Issue by pemoi1982jpm** [tensorflow/tensorflow#53746]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution:  Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): r2.7
- Python version: 3.6.10
- Bazel version (if compiling from source):  3.7.2
- GCC/Compiler version (if compiling from source): 7.3.1

**Describe the current behavior**
I have a 2D sparse square matrix, where the elements are organized in blocks around the diagonal, similar to [LinearOperatorBlockDiag](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorBlockDiag). 
At compilation time I know the total matrix size, but the size of each of its blocks its not known until execution time.
I need to multiply that matrix by a 1D vector to generate a 1D vector, and similar to [matvec](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorBlockDiag#matvec) method I would like to only compute the dense part of the matrix, i.e. block_0 x sub_vector_0, block_1 x sub_vector_1 ... block_n x sub_vector_n.
And I would like to have it working with XLA.

I have tried XLA with LinearOperatorBlockDiag, however it is not XLA compatible
I would like to create a custom XLA op, which could deal with the computation and offsets internally: 
it can receive as input a (NxN) matrix, a (N) vector and an array of M offsets (the size of each block), and generate the final (N) vector.
I cannot express it with the available [XLA ops](https://www.tensorflow.org/xla/operation_semantics): tried with xla::DynamicSlice + xla::Dot ,  but I do not know the size of the submatrices/subvectors, so I cannot pass the sizes to DynamicSlice.

I have created my own [Custom Call](https://www.tensorflow.org/xla/custom_call) but I am not sure how to expose it to TensorFlow. The documentation does not include how to compile the Custom Call, integrate, and how to expose it.
In any case I have register a XLA op within `tensorflow/compiler/tf2xla/kernels/mat_vec_op.cc`, compiled, but I cannot call my CustomCall (sitting in `tensorflow/compiler/xla/service/cpu/mycustomcall.cc`), it seems it was not exposed correctly, and it does not find it.

I would like to ask here:
1. Is it possible to implement that kind of op on TF-XLA?
2. If yes, can you please provide some guidance on how?
if it is with a CustomCall, can you please provide help on how to compile, expose and use? 
 

**Standalone code to reproduce the issue**
Python example of what I am trying to do:

`import tensorflow as tf`
`n_blocks = 4`

`@tf.function(jit_compile=True)`
`def myfunc(segment_ids, vector):`
`    value = tf.ones_like(segment_ids)`
`    size_blocks = tf.math.unsorted_segment_sum(value, segment_ids, num_segments=n_blocks)`
`    offsets = tf.concat([[0], tf.math.cumsum(size_blocks)], axis=-1)`
`    blocks_list = []`
`    for i in range(n_blocks):`
`        block = vector[offsets[i]:offsets[i+1]]`
`        block = tf.einsum('i,j -> ij', block, tf.transpose(block))`
`        blocks_list.append(tf.linalg.LinearOperatorFullMatrix(block))`
`    matrix = tf.linalg.LinearOperatorBlockDiag(blocks_list)`
`    return matrix.matvec(vector)`

`for i in range(3):`
`    segment_ids = tf.constant([0, 0, 1, 1, 2, 3])`
`    vector = tf.ones([6], dtype=tf.float64)`
`    print(myfunc(segment_ids, vector))`

**Comment by sushreebarsa** [comment]
@pemoi1982jpm 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by pemoi1982jpm** [comment]
Here you can find the gist:
[https://gist.github.com/pemoi1982jpm/382ef8c23622dcfd4c878cc403fe6c74](https://gist.github.com/pemoi1982jpm/382ef8c23622dcfd4c878cc403fe6c74)

Thanks

**Comment by sushreebarsa** [comment]
@pemoi1982jpm I tried to replicate the issue on colab using TF v2.7.0 , tf-nightly ,and faced a different error .Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/6d01dae2795d6afe02d24bff53ab0c3f/53746.ipynb) and confirm the same?Could you please refer to the [ tutorial](https://www.tensorflow.org/xla/tutorials/jit_compile) and similar [issue1](https://github.com/tensorflow/tensorflow/issues/14506), [issue2 ](https://github.com/tensorflow/tensorflow/issues/43687),let us know if it helps?Please refer to the [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) to see version compatibility.Thanks!

**Comment by pemoi1982jpm** [comment]
That error you faced it is the same I got, and the reason why I said: 
"I have tried XLA with LinearOperatorBlockDiag, however it is not XLA compatible"

Those issues you pointed do not seem to apply here. It is not a performance issue, and I am running everything on CPU.

The dynamic shapes of the blocks seem to be the issue.

I would like to ask here:
    Is it possible to implement that kind of op on TF-XLA?
    If yes, can you please provide some guidance on how?
    if it is with a CustomCall, can you please provide help on how to compile, expose and use?


Thank you

**Comment by pemoi1982jpm** [comment]
Any update on this?
Thank you

**Comment by MoisesHer** [comment]
Please, 
Any progress or update?

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
