### ISSUE TITLE
Convert tflite model with customerized QuantizeConfig for different layers.

### ISSUE THREAD

**Issue by JuanLei2019** [tensorflow/tensorflow#53749]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source):pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): tf 2.5

### 2. Code

import tensorflow as tf
from tensorflow import keras
import tensorflow_model_optimization as tfmot
import numpy as np
import tempfile
from tensorflow.keras import layers

###################################################
LastValueQuantizer = tfmot.quantization.keras.quantizers.LastValueQuantizer
MovingAverageQuantizer = tfmot.quantization.keras.quantizers.MovingAverageQuantizer

class DefaultConv2DQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    # Configure how to quantize weights.
    def get_weights_and_quantizers(self, layer):
        return [(layer.kernel, LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False))]

    # Configure how to quantize activations.
    def get_activations_and_quantizers(self, layer):
        return [(layer.activation, MovingAverageQuantizer(num_bits=16, symmetric=False, narrow_range=False, per_axis=False))]

    def set_quantize_weights(self, layer, quantize_weights):
        # Add this line for each item returned in `get_weights_and_quantizers`
        # , in the same order
        layer.kernel = quantize_weights[0]

    def set_quantize_activations(self, layer, quantize_activations):
        # Add this line for each item returned in `get_activations_and_quantizers`
        # , in the same order.
        layer.activation = quantize_activations[0]

    # Configure how to quantize outputs (may be equivalent to activations).
    def get_output_quantizers(self, layer):
        return []

    def get_config(self):
        return {}

def apply_quantization_to_conv2d(layer):
    if isinstance(layer, tf.keras.layers.Conv2D):
        return   tfmot.quantization.keras.quantize_annotate_layer(layer, DefaultConv2DQuantizeConfig())
    return layer

if __name__ == "__main__":
    quantize_annotate_layer = tfmot.quantization.keras.quantize_annotate_layer
    quantize_annotate_model = tfmot.quantization.keras.quantize_annotate_model
    quantize_scope = tfmot.quantization.keras.quantize_scope

    input = keras.Input(shape=(28,28,1))
    x1 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(input)
    x2 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x1)
    x3 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x2)

    model = keras.Model(input, x3)
    model = tf.keras.models.clone_model(model, clone_function=apply_quantization_to_conv2d)
    with tfmot.quantization.keras.quantize_scope({'DefaultConv2DQuantizeConfig': DefaultConv2DQuantizeConfig}):
        model = tfmot.quantization.keras.quantize_apply(model)

    q_aware_model = model
    converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    quantized_tflite_model = converter.convert()

    #save tflite file
    with open("testtf25.tflite", 'wb') as f:
        f.write(quantized_tflite_model)

    interpreter = tf.lite.Interpreter(model_content=quantized_tflite_model)
    interpreter.allocate_tensors()

### 3. Failure after conversion

We're trying to quantization-aware train a model. But we're not sure how to set the QuantizeConfig with activation 16bits, weights 8bits for different layers. We try to quantize the convoluational layers as the above code. The above code can produce a tflite model, but it outputs an RuntimeError. 

"
  interpreter.allocate_tensors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/conv.cc:353 bias->type != kTfLiteInt64 (INT32 != INT64)Node number 1 (CONV_2D) failed to prepare.
"

We're not sure how to set the QuantizeConfig of different keras layers. Could you give us some reference or examples to quantization-aware training a model with different kinds of layers: convoluational layer, MaxPooling2D() layer, etc.

**Comment by JuanLei2019** [comment]
@sushreebarsa Thanks for your response. We have tried the TF v2.7.0 and it outputs the same error. 
By the way, we change the  class " InputLayerQuantize" of  "default_8bit_transforms.py"  to make the output of "InputLayer" to int16 type. But we think it's not the reason which cause the above runtime error.

**Comment by JuanLei2019** [comment]
> @JuanLei2019 Could you please try to use latest TF v2.7.0 and let us know the outcome?Thanks!

@sushreebarsa Thanks for your response. We have tried the TF v2.7.0 and it outputs the same error.
By the way, we change the class " InputLayerQuantize" of "default_8bit_transforms.py" to make the output of "InputLayer" to int16 type. But we think it's not the reason which cause the above runtime error.

**Comment by JuanLei2019** [comment]
> @JuanLei2019 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

Running the below code will output the error. 
The code is: 

`import tensorflow as tf
from tensorflow import keras
import tensorflow_model_optimization as tfmot
import numpy as np
import tempfile
from tensorflow.keras import layers


LastValueQuantizer = tfmot.quantization.keras.quantizers.LastValueQuantizer
MovingAverageQuantizer = tfmot.quantization.keras.quantizers.MovingAverageQuantizer

class DefaultConv2DQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    def get_weights_and_quantizers(self, layer):
        return [(layer.kernel, LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False))]
    def get_activations_and_quantizers(self, layer):
        return [(layer.activation, MovingAverageQuantizer(num_bits=16, symmetric=False, narrow_range=False, per_axis=False))]
    def set_quantize_weights(self, layer, quantize_weights):
        layer.kernel = quantize_weights[0]
    def set_quantize_activations(self, layer, quantize_activations):
        layer.activation = quantize_activations[0]
    def get_output_quantizers(self, layer):
        return []
    def get_config(self):
        return {}

def apply_quantization_to_conv2d(layer):
    if isinstance(layer, tf.keras.layers.Conv2D):
        return   tfmot.quantization.keras.quantize_annotate_layer(layer, DefaultConv2DQuantizeConfig())
    return layer


if __name__ == "__main__":
    quantize_annotate_layer = tfmot.quantization.keras.quantize_annotate_layer
    quantize_annotate_model = tfmot.quantization.keras.quantize_annotate_model
    quantize_scope = tfmot.quantization.keras.quantize_scope

    input = keras.Input(shape=(28,28,1))
    x1 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(input)
    x2 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x1)
    x3 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x2)

    model = keras.Model(input, x3)

    model = tf.keras.models.clone_model(model, clone_function=apply_quantization_to_conv2d)
    with tfmot.quantization.keras.quantize_scope({'DefaultConv2DQuantizeConfig': DefaultConv2DQuantizeConfig}):
        model = tfmot.quantization.keras.quantize_apply(model)

    q_aware_model = model
    converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    quantized_tflite_model = converter.convert()

    #save tflite file
    with open("testtf25.tflite", 'wb') as f:
        f.write(quantized_tflite_model)

    interpreter = tf.lite.Interpreter(model_content=quantized_tflite_model)
    interpreter.allocate_tensors()

`

**Comment by JuanLei2019** [comment]
> @JuanLei2019 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!  

Running the below code will output the error. Thanks.

```python
import tensorflow as tf
from tensorflow import keras
import tensorflow_model_optimization as tfmot
import numpy as np
import tempfile
from tensorflow.keras import layers


LastValueQuantizer = tfmot.quantization.keras.quantizers.LastValueQuantizer
MovingAverageQuantizer = tfmot.quantization.keras.quantizers.MovingAverageQuantizer

class DefaultConv2DQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    def get_weights_and_quantizers(self, layer):
        return [(layer.kernel, LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False))]
    def get_activations_and_quantizers(self, layer):
        return [(layer.activation, MovingAverageQuantizer(num_bits=16, symmetric=False, narrow_range=False, per_axis=False))]
    def set_quantize_weights(self, layer, quantize_weights):
        layer.kernel = quantize_weights[0]
    def set_quantize_activations(self, layer, quantize_activations):
        layer.activation = quantize_activations[0]
    def get_output_quantizers(self, layer):
        return []
    def get_config(self):
        return {}

def apply_quantization_to_conv2d(layer):
    if isinstance(layer, tf.keras.layers.Conv2D):
        return   tfmot.quantization.keras.quantize_annotate_layer(layer, DefaultConv2DQuantizeConfig())
    return layer


if __name__ == "__main__":
    quantize_annotate_layer = tfmot.quantization.keras.quantize_annotate_layer
    quantize_annotate_model = tfmot.quantization.keras.quantize_annotate_model
    quantize_scope = tfmot.quantization.keras.quantize_scope

    input = keras.Input(shape=(28,28,1))
    x1 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(input)
    x2 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x1)
    x3 = keras.layers.Conv2D(filters=12, kernel_size=(3,3), activation='relu')(x2)

    model = keras.Model(input, x3)

    model = tf.keras.models.clone_model(model, clone_function=apply_quantization_to_conv2d)
    with tfmot.quantization.keras.quantize_scope({'DefaultConv2DQuantizeConfig': DefaultConv2DQuantizeConfig}):
        model = tfmot.quantization.keras.quantize_apply(model)

    q_aware_model = model
    converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    quantized_tflite_model = converter.convert()

    #save tflite file
    with open("testtf25.tflite", 'wb') as f:
        f.write(quantized_tflite_model)

    interpreter = tf.lite.Interpreter(model_content=quantized_tflite_model)
    interpreter.allocate_tensors()

```

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to replicate the issue on colab using TF [v2.7.0](https://colab.research.google.com/gist/sushreebarsa/994675facdb1d4d555a645168d112e5c/53749.ipynb#scrollTo=utwlQejrw3Qq) and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/b21d3cb2b642848974d675632fad238c/53749-nightly.ipynb),please find the attached gists for reference.Thanks!

**Comment by JuanLei2019** [comment]
> 
@sushreebarsa，@sachinprasadhs， hello,  sorry to interrupt，I do not know how to check the "attached gists for reference". I can not find any attached files. Could you paste the reference here? or could you give me some advice how to solve the errors? Thanks.

**Comment by JuanLei2019** [comment]
> @sachinprasadhs Was able to replicate the issue on colab using TF [v2.7.0](https://colab.research.google.com/gist/sushreebarsa/994675facdb1d4d555a645168d112e5c/53749.ipynb#scrollTo=utwlQejrw3Qq) and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/b21d3cb2b642848974d675632fad238c/53749-nightly.ipynb),please find the attached gists for reference.Thanks!

@sushreebarsa，@sachinprasadhs， hello, sorry to interrupt，I do not know how to check the "attached gists for reference". I can not find any attached files. Could you paste the reference here? or could you give me some advice how to solve the errors? Thanks.

**Comment by sachinprasadhs** [comment]
The gist for v2.7.0 is https://colab.research.google.com/gist/sushreebarsa/994675facdb1d4d555a645168d112e5c/53749.ipynb#scrollTo=utwlQejrw3Qq and for tf-nightly is https://colab.research.google.com/gist/sushreebarsa/b21d3cb2b642848974d675632fad238c/53749-nightly.ipynb, could you please verify the error message reproduced. Thanks!

**Comment by JuanLei2019** [comment]
> The gist for v2.7.0 is https://colab.research.google.com/gist/sushreebarsa/994675facdb1d4d555a645168d112e5c/53749.ipynb#scrollTo=utwlQejrw3Qq and for tf-nightly is https://colab.research.google.com/gist/sushreebarsa/b21d3cb2b642848974d675632fad238c/53749-nightly.ipynb, could you please verify the error message reproduced. Thanks!

Thanks for the reply. I checked the error message. The output error message is a little different. We change the class " InputLayerQuantize" of "default_8bit_transforms.py" to make the output of "InputLayer" to int16 type. The output error message is  "interpreter.allocate_tensors() 
File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/conv.cc:353 bias->type != kTfLiteInt64 (INT32 != INT64)Node number 1 (CONV_2D) failed to prepare." And the link error message is "RuntimeError: tensorflow/lite/kernels/conv.cc:357 output->type != input_type (INT16 != INT8)Node number 1 (CONV_2D) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.".  But they are occured at the same "conv.cc" file.

**Comment by JuanLei2019** [comment]
> The gist for v2.7.0 is https://colab.research.google.com/gist/sushreebarsa/994675facdb1d4d555a645168d112e5c/53749.ipynb#scrollTo=utwlQejrw3Qq and for tf-nightly is https://colab.research.google.com/gist/sushreebarsa/b21d3cb2b642848974d675632fad238c/53749-nightly.ipynb, could you please verify the error message reproduced. Thanks!

Hi, sorry to disturb you,  we have checked the error messages. And  could you give us some advice how to solve the errors?

**Comment by pjpratik** [comment]
I was able to reproduce this in TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/9b46a52223cd6faa7b19cb893a49b55b/53749.ipynb). Thank you.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
