### ISSUE TITLE
Configure requires user interaction in r0.11

### ISSUE THREAD

**Issue by andreas-eberle** [tensorflow/tensorflow#5374]
The ./configure in the r0.11 branch requires user interaction if there is more than one PYTHON_LIBRARY_PATH found by the `util/python/python_config.sh` script. In r0.10 it was possible to run a ./configure without user interaction. Furthermore, in the PR #5135 the script was changed to make it possible to directly specify the PYTHON_LIBRARY_PATH to prevent the need of user interaction.

I think this fix should also be merged into to the r0.11 branch to ensure tensorflow can be configured/build without user interaction (when there are multiple pythons installed).

**Comment by aselle** [comment]
Thanks for bringing this up. Were you offering to contribute a patch to fix this. It looks like #5135 was already merged. Do you have a pointer to the code in ./configure that has regressed?

**Comment by andreas-eberle** [comment]
#5135 was merged into master 12 days ago, while the `python_config.sh` file wasn't touched since September 20th in the r0.11 branch. That's why I think the change has never been merged to r0.11. Do you need a PR for this, or can you just merge/cherry pick the changes of #5135 and #5167? (#5167 is a small fix for #5135).

**Comment by aselle** [comment]
@gunan, are we open to merging this change into r0.11?

**Comment by gunan** [comment]
As long as the first python library path is valid, if you run 
`yes "" | ./configure` the script executes unattended, without any need for user interaction.
Therefore, I am not too much in the favor of merging this. @yifeif @martinwicke for their opinions.

@andreas-eberle would the suggested execution method work for you?

**Comment by martinwicke** [comment]
sgtm

**Comment by gunan** [comment]
As this has been the default behaviour all along, I will close this issue.
It is a nice to have feature, but we have prepared the 0.11 final packages, and this issue currently has a workaround known to work for most cases.
