### ISSUE TITLE
The custom op with nccl communication in MirroredStrategy cause hanging in the eager mode

### ISSUE THREAD

**Issue by gavin1332** [tensorflow/tensorflow#53748]
I write a custom op with nccl communication, and I run it under the `MirroredStrategy` in the eager mode. The expected behavior is to do nccl communication in such an op among all replicas.

As the nccl communication waits util it is aware of all peers, the custom op hangs before other op replicas run. However, the python GIL restrict other op replicas running parallelly, which cause the training step hanging in a deadlock ...

I need help to know whether my analysis above is correct or not about my unexpected hanging problem. And if it is correct, how can I fix it?

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6
- Python version: 3.9.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 11/cuDNN 8.1
- GPU model and memory: V100 with 32GB

**Comment by tilakrayal** [comment]
@gavin1332 ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by gavin1332** [comment]
As the code of my custom op is not open source, it is not easy to supply. Could we just have a discussion about whether it is possible to hang under my conidtion? If my analysis makes sense and it is not suggested to use nccl in custom op under the MirroredStrategy, I could change my implementation.

**Comment by tilakrayal** [comment]
@gavin1332 ,
If you are unable to provide the code, can you please post this question on TensorFlow [discussion Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by gavin1332** [comment]
close this issue for no response for a long time
