### ISSUE TITLE
movenet fp16 not executed by TFLITE NNAPI DELEGATE

### ISSUE THREAD

**Issue by suyash-narain** [tensorflow/tensorflow#53758]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): aarch64 Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.8
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I have issues while working with movenet tflite models on android 11 NNAPI 1.3
the movenet models used are sourced from tfhub:

https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/tflite/float16/4
https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/tflite/int8/4

the above two singlepose movenet lighting tflite models are float16 and INT8 respectively, and I was trying to perform benchmarking of the same using the prebuilt benchmark model for android_aarch64 sourced from tflite website (v 2.8):
https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model

When I run lite-model_movenet_singlepose_lightning_tflite_int8_4.tflite model on NNAPI using the following command:

> ./benchmark_model --graph=lite-model_movenet_singlepose_lightning_tflite_int8_4.tflite --use_nnapi=1 --nnapi_accelerator_name=nnapi-reference
STARTING!
Log parameter values verbosely: [0]
Graph: [lite-model_movenet_singlepose_lightning_tflite_int8_4.tflite]
Use NNAPI: [1]
NNAPI accelerator name: [nnapi-reference]
NNAPI accelerators available: [nnapi-reference]
Loaded model lite-model_movenet_singlepose_lightning_tflite_int8_4.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
NNAPI delegate created.
INFO: Replacing 141 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 15 partitions.
Explicitly applied NNAPI delegate, and the model graph will be partially executed by the delegate w/ 8 delegate kernels.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
The input model file size (MB): 2.89484
Initialized session in 59.758ms.

 the NNAPI delegate is created and the model is partially executed by NNAPI CPU.

whereas when I run float16 lite-model_movenet_singlepose_lightning_tflite_float16_4.tflite model as follows:

> $ ./benchmark_model --graph=lite-model_movenet_singlepose_lightning_tflite_float16_4.tflite --use_nnapi=1 --nnapi_accelerator_name=nnapi-reference
STARTING!
Log parameter values verbosely: [0]
Graph: [lite-model_movenet_singlepose_lightning_tflite_float16_4.tflite]
Use NNAPI: [1]
NNAPI accelerator name: [nnapi-reference]
NNAPI accelerators available: [nnapi-reference]
Loaded model lite-model_movenet_singlepose_lightning_tflite_float16_4.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
NNAPI delegate created.
Though NNAPI delegate is explicitly applied, the model graph will not be executed by the delegate.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 269 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 13 partitions.
The input model file size (MB): 4.75851
Initialized session in 109.192ms.

the float16 model is not at all executed by the NNAPI delegate even though I am explicitly applying NNAPI CPU

I face the same issue if i run this model https://tfhub.dev/sayakpaul/lite-model/mobilenetv2-coco/fp16/1?lite-format=tflite, i see the same message as before for fp16 models:

> Graph: [lite-model_mobilenetv2-coco_fp16_1.tflite]
Use NNAPI: [1]
NNAPI accelerator name: [nnapi-reference]
NNAPI accelerators available: [nnapi-reference]
Loaded model lite-model_mobilenetv2-coco_fp16_1.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
NNAPI delegate created.
Though NNAPI delegate is explicitly applied, the model graph will not be executed by the delegate.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Replacing 211 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 43 partitions.
The input model file size (MB): 4.2551
Initialized session in 133.522ms.

I even used the --disable_nnapi_cpu=0 argument, and yet still got the same result with nightly
y
is it the same for every fp16 model that it won't be supported on NNAPI?

**Describe the expected behavior**
the model should be executed by NNAPI CPU

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@suyash-narain 
Can you please confirm the tensorflow version you are using?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.Thanks!

**Comment by suyash-narain** [comment]
i was using the tf version 2.8-rc0 and tf nightly benchmark model for date 1/13/2022

since the issue occurred during benchmarking the models using tflite benchmark model
the command used for benchmarking was:

$chmod +x android_aarch64_benchmark_model
$./android_aarch64_benchmark_model --graph=lite-model_movenet_singlepose_lightning_tflite_float16_4.tflite --use_nnapi=1 --nnapi_accelerator_name=nnapi-reference

**Comment by suhrid-s** [comment]
Hi @sushreebarsa,

We faced the same issue when trying to emulate pose estimation on Android Studio for Movenet Thunder/Lightning fp16 on NNAPI using tflite nightly build.

To reproduce the error,
1)  Clone https://github.com/SuhridS/examples.git -b suhrids/update_pose_estimation
2) Open "https://github.com/SuhridS/examples/tree/suhrids/update_pose_estimation/lite/examples/pose_estimation/android" on Android Studio and build.
3) Create an AVD for Pixel 5, API 30 and run pose estimation app on it.

Observation:
| Model             | Type | CPU   | GPU             | NNAPI       |
|-------------------|------|-------|-----------------|-------------|
| Movenet Lightning | FP16 | Works | Works           | App crashes |
| Movenet Lightning | INT8 | Works | Works           | Works       |
| Movenet Thunder   | FP16 | Works | Works           | App crashes |
| Movenet Thunder   | INT8 | Works | Works           | Works       |
| Movenet Multipose | FP16 | Works | Fallback to CPU | Works       |
| Posenet           | FP16 | Works | Works           | Works       |

**Comment by haozha111** [comment]
@karimnosseir could you help take a look? thanks!

**Comment by miaowang14** [comment]
Thanks for reporting the issue. The fix has been submitted and you should be able to build benchmark_model and run the fp16 one. (There are still ops like GatherNd not supported by NNAPI delegate, causing the model being partitioned into several sub models though)

**Comment by madhavarora2002** [comment]
Hi, same issue as above.
probably the changes not been pushed to the master branch. Could you pls look into it!
