### ISSUE TITLE
why does tensorflow use multi threads to launch gpu kernels?

### ISSUE THREAD

**Issue by sleepwalker2017** [tensorflow/tensorflow#53759]
I noticed that when I launch kernel to the same GPU with multi threads, cudaLaunchKernel  api will get much slower. 
But seems it's the case in tensorflow. why not use a single thread to communicate with GPU?

Here is my test，when thread_num is larger, cuda api cost will be huge.
![image](https://user-images.githubusercontent.com/26128514/149446536-06d6117a-d348-4b0d-a2a8-8ebf81299c5a.png)

`#include <thread>
#include <vector>

using namespace std;

bool running = true;
const int thread_num = 20;
const int launch_num = 25;

__global__ void task_kernel(int x) {
    int ans = 1024;
    for(int i = 0; i < x; i++) {
        if(ans > 0) {
            ans *= (x + 2);
        }
    }
}

void task(int x) {
    while(running) {
        for(int i = 0; i < launch_num; i++) {
            task_kernel<<<1, 1>>>(x);
        }
        this_thread::sleep_for(1ms);
    }
}

void test() {
    vector<thread> threads;
    for(int i = 0; i < thread_num; i++) {
        thread t(task, i);
        threads.push_back(std::move(t));
    }
    this_thread::sleep_for(100ms);
    running = false;
    for(auto& t: threads) {
        t.join();
    }
}

int main() {
    cudaFree(0);
    test();
    return 0;
}`

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@sleepwalker2017 
We see that you have not filled the issue template without the important information like tf version and gpu card used, its hard to help you.
May be you have to fine tune your cuda configurations for TF.
This does not seem like a bug or feature request as this repo is for them, can you open this in discussion forum for further queries as there is a large community to guide there.

**Comment by sleepwalker2017** [comment]
> discussion forum

OK, I'll go to the forum for some more discuss. thank you.

**Comment by Saduf2019** [comment]
@sleepwalker2017 
Can you move this to closed status
