### ISSUE TITLE
Exploding gradient after network has converged

### ISSUE THREAD

**Issue by biplavc** [tensorflow/tensorflow#53756]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Implemented a custom distribution. It is in the jupyter notebook provided at the end.
- OS Platform and Distribution: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- TensorFlow installed from (source or binary): source
- TensorFlow version :  2.3.1
- Python version:  Python 3.8.5
- GCC/Compiler version : gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
- CUDA/cuDNN version:  CUDA Version: 11.0
- GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.142.00   Driver Version: 450.142.00   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM3...  Off  | 00000000:34:00.0 Off |                    0 |
| N/A   27C    P0    66W / 350W |   3358MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM3...  Off  | 00000000:36:00.0 Off |                    0 |
| N/A   26C    P0    50W / 350W |      7MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM3...  Off  | 00000000:39:00.0 Off |                    0 |
| N/A   31C    P0    49W / 350W |      7MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM3...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   64C    P0   273W / 350W |  25960MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM3...  Off  | 00000000:57:00.0 Off |                    0 |
| N/A   23C    P0    48W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM3...  Off  | 00000000:59:00.0 Off |                    0 |
| N/A   29C    P0    49W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM3...  Off  | 00000000:5C:00.0 Off |                    0 |
| N/A   26C    P0    49W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM3...  Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   28C    P0    48W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   8  Tesla V100-SXM3...  Off  | 00000000:B7:00.0 Off |                    0 |
| N/A   24C    P0    48W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   9  Tesla V100-SXM3...  Off  | 00000000:B9:00.0 Off |                    0 |
| N/A   25C    P0    49W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  10  Tesla V100-SXM3...  Off  | 00000000:BC:00.0 Off |                    0 |
| N/A   30C    P0    49W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  11  Tesla V100-SXM3...  Off  | 00000000:BE:00.0 Off |                    0 |
| N/A   30C    P0    46W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  12  Tesla V100-SXM3...  Off  | 00000000:E0:00.0 Off |                    0 |
| N/A   25C    P0    47W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  13  Tesla V100-SXM3...  Off  | 00000000:E2:00.0 Off |                    0 |
| N/A   25C    P0    47W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  14  Tesla V100-SXM3...  Off  | 00000000:E5:00.0 Off |                    0 |
| N/A   31C    P0    49W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|  15  Tesla V100-SXM3...  Off  | 00000000:E7:00.0 Off |                    0 |
| N/A   29C    P0    50W / 350W |      5MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Describe the current behavior**
The multinomial distribution has multiple variables where each variable takes a value that equals the probability of an unique action.
When the network converges, as some of the probabilities are very small, the resulting gradient becomes NaN.

**Describe the expected behavior**
It should provide the actual result instead of NaN.

**Standalone code to reproduce the issue**
[The jupyter notebook can produce the situation where the gradient becomes NaN](https://colab.research.google.com/drive/1IVb0s5Tt2BmibgKqLVojj3SoCi2TJctL?usp=sharing).

**Comment by mohantym** [comment]
Hi @biplavc ! I was getting a different error in [2.7](https://colab.sandbox.google.com/gist/mohantym/9f0e30116a7ec36e9fb99ebff946eee6/uniquemultonomialdist.ipynb#scrollTo=cb795b94) .

**Comment by prasenjit52282** [comment]
Hello @mohantym and @biplavc !

The error for TF2.7 is fixed in the jupyter notebook.

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by Saduf2019** [comment]
@prasenjit52282 
Could you please try on colab and let us know,please share the gist for us to help you.
