### ISSUE TITLE
Master build fails on s390x arch due to FloatList struct changes in tpu/c_api_conversions.cc

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#53754]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: Master
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 4.2.2- (@non-git)
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Recently, master builds on `s390x` arch is failing due to following error:
```
tensorflow/stream_executor/tpu/c_api_conversions.cc:175:66:   required from here
tensorflow/stream_executor/tpu/c_api_conversions.cc:164:15: error: cannot convert 'float*' to 'float_t* {aka double*}' in assignment
     dst->heap = new Dst[dst->size];
     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" build  --define=tensorflow_mkldnn_contraction_kernel=0 --define tflite_with_xnnpack=false //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
I believe the problem occurs at this line: https://github.com/tensorflow/tensorflow/blob/276e5c51c310983923b8078bcf6fcf78844c6211/tensorflow/stream_executor/tpu/c_api_decl.h#L197

I was able to successfully build by changing `float_t` occurrences in `FloatList` struct to `float`.  However, I am not sure if this change has a wider implication.

Any help appreciated.

Thanks.

**Comment by Saduf2019** [comment]
@rposts 
Could you please use a stable version, please use tf 2.6 or 2.7 and let us know if you still face any issues.

**Comment by rposts** [comment]
@Saduf2019 - problem happens on master branch as this is a new code introduced by this [commit](https://github.com/tensorflow/tensorflow/commit/dfd06f8cf01fb0a1cf12ca29f7798d16a692396a#diff-235daf4799407636e32920a062d4c08b50e10ef1c222df0c623c78c8cbc258ae) on Jan 4, 2022.

**Comment by Saduf2019** [comment]
@rposts 
Hence please use stable versions that are already tested, as its master branch would have updates to it and is not tested as yet.

**Comment by sbushmanov** [comment]
2 month since initial post and still not resolved

**Comment by SilverLuke** [comment]
Sorry for this necroposting, any solutions yet? 
I am using the r2.9 branch.
