### ISSUE TITLE
Constant folding fails when converting int8 transposed convolutions

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#53766]
When converting a model that used int8 quantization aware training conversion of transposed convolutions fails.

The converter isn't able to correctly constant fold the fake quantized weights and keeps an unnecessary `tfl.transpose` operation in the graph which leads to problems when executing the TFLite model. Note that this issue is independent of TensorFlow Model Optimization and can be reproduced using plain TensorFlow as well (see linked notebook).

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS / Ubuntu
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5, 2.6, 2.7, 2.8rc0 and 2.9.0-dev20220114

### 2. Code

A minimal reproduction of the issue is available in [this notebook](https://colab.research.google.com/drive/1bfI_Dx3zyoHkabJlHpNFnbDA9r9G5ffE?usp=sharing). Re-run the notebook to show `netron` visualisations showing the conversion problem.

**Comment by tilakrayal** [comment]
@lgeiger ,
Can you please confirm this issue is duplicate of issue #53767.if yes, Can you please close this issue, since it is already being tracked there? Thanks!

**Comment by lgeiger** [comment]
> Can you please confirm this issue is duplicate of issue #53767.

@tilakrayal I cannot confirm, this issue is not a duplicate of #53767.

#53767 talks about **per-channel quantization** which makes the converter crash/segfault (maybe this is even a security vulnerability?). Whereas this issue refers to **per-tensor quantization** which merely fails to properly constant fold the graph and therefore results in wrong output but does not crash the converter.

The problems might be related, but fundamentally they manifest themselves in two different issues.

**Comment by tilakrayal** [comment]
@Saduf2019  ,
I was able to reproduce the issue in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/039895e64be9e908165c62087c9986c0/quant_transposed_conv_2_5_0.ipynb),[v2.7](https://colab.research.google.com/gist/tilakrayal/21cd6a527e22819de2f26cc904b60034/quant_transposed_conv-2-7-0.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/17a4ebeb7b4d5aa1ec543e57bbc88530/quant_transposed_conv_nightly.ipynb).Please find the gist.

**Comment by lgeiger** [comment]
It seems like this has been fixed in 4a98e2761646811d829f26038f5954ff44cb0f38 which is great! I verified that [this works correctly with TF 2.10.0-rc0](https://colab.research.google.com/drive/1bfI_Dx3zyoHkabJlHpNFnbDA9r9G5ffE?usp=sharing#scrollTo=1RDYCUwP4oW1).
