### ISSUE TITLE
TFLite Converter segfaults when trying to convert per-channel quantized transposed convolutions

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#53767]
When converting transposed convolutions using per-channel weight quantization the converter segfaults and crashes the Python process. Per-channel quantization is supported by TFLite Transposed convolutions:
https://github.com/tensorflow/tensorflow/blob/f87be6c7de847017c48520649e3d771e5d6b81b6/tensorflow/lite/kernels/transpose_conv.cc#L371-L380
so the converter shouldn't segfault when trying to convert such a model.

It looks like this issue has been introduced in TensorFlow 2.6 since the same model code produced a valid TFLite file in TensorFlow 2.5. This issue might also be related to #53766, but in any case the converter should never segfault.

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS / Ubuntu
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.6, 2.7, 2.8rc0 and 2.9.0-dev20220114

### 2. Code

A minimal reproduction of the issue and a workaround is available in [this notebook](https://colab.research.google.com/drive/1IXri5HeDc9qTAtDOp-LqZyQTL8CcemGq?usp=sharing).

```python
import tensorflow as tf


class QuantConv2DTransposed(tf.keras.layers.Layer):
    def build(self, input_shape):
        self.kernel = self.add_weight("kernel", [3, 3, input_shape[-1], 24])

    def call(self, inputs):
        filters = tf.quantization.fake_quant_with_min_max_vars_per_channel(
            self.kernel, -3.0 * tf.ones([24]), 3.0 * tf.ones([24]), narrow_range=True
        )
        filters = tf.transpose(filters, (0, 1, 3, 2))
        return tf.nn.conv2d_transpose(inputs, filters, [*inputs.shape[:-1], 24], 1)


inp = tf.keras.Input(shape=(6, 8, 48), batch_size=1)
x = tf.quantization.fake_quant_with_min_max_vars(inp, -3.0, 3.0, narrow_range=True)
x = QuantConv2DTransposed()(x)
x = tf.quantization.fake_quant_with_min_max_vars(x, -3.0, 3.0, narrow_range=True)

model = tf.keras.Model(inp, x)

model.save("/tmp/testing")
converter = tf.lite.TFLiteConverter.from_saved_model("/tmp/testing")
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# terminated by signal SIGSEGV (Address boundary error)
tflite_model = converter.convert()
```

**Comment by sushreebarsa** [comment]
@Saduf2019  Was able to replicate the issue on colab using  TF v[2.6.0](https://colab.research.google.com/gist/sushreebarsa/3325c1d57489120e4a7af70701f4bae0/quant-conv-transposed-pre-channel.ipynb#scrollTo=Uwk4VEay4RRr), [2.7.0 ](https://colab.research.google.com/gist/sushreebarsa/d160e5366f330488d391b19ecdd2ba1e/53767.ipynb)and[ tf-nightly](https://colab.research.google.com/gist/sushreebarsa/8b314dfdc9b269823840e789b69eb756/quant-conv-transposed-pre-channel.ipynb#scrollTo=jNfg0zbs4N-g)(2.9.0-dev20220114),please find the attached gists.Thank you!

**Comment by lgeiger** [comment]
> Was able to replicate the issue on colab using TF v2.6.0, 2.7.0 and tf-nightly(2.9.0-dev20220114),please find the attached gists

@sushreebarsa  Thanks for confirming. Just for reference, your reproduction on TF 2.6.0 actually now fails due to an unrelated Keras version conflict. Changing the dependency from `v2.6.0` to `v2.6.2` will fix this and allow you to correctly reproduce the segfault mentioned in this issue.

**Comment by lgeiger** [comment]
This is still an issue in `2.9.0-dev20220318`. Are there any updates on this?
Being able to trigger a converter segfault seems to be quite problematic.

**Comment by lgeiger** [comment]
@JunyoungLim I retested the above example `2.10.0-dev20220427` and the converter still segfaults.

**Comment by lgeiger** [comment]
I retested the above example with `2.10.0` and the segfault seems to be fixed now, however conversion still fails with:
```
'tfl.transpose' op has mismatched quantized axes of input and output
```
See [here](https://colab.research.google.com/drive/1IXri5HeDc9qTAtDOp-LqZyQTL8CcemGq?usp=sharing).

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
