### ISSUE TITLE
JIT Compile too slow 

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#53774]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): master
- Python version: 3.7
- Bazel version (if compiling from source): 4.4.4
- GCC/Compiler version (if compiling from source): 7.3.1
- CUDA/cuDNN version: cuda 11
- GPU model and memory: yes 80GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![image](https://user-images.githubusercontent.com/33950866/149608623-f2e6ed39-b587-4015-afbd-954bc491ba06.png)
I run 1+1=2, TF cost 30mins...
It really compile 30 mins every times.

**Describe the expected behavior**
I don't want to wait 30mins ...

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
turn off ```TensorFlow was not built with CUDA kernel binaries compatible with compute capability 8.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

#@tf.function(experimental_compile=False,autograph=True)
#def zz_sm():
#  # I don't want to use xla .
#  input_a = tf.random.uniform([1024000], dtype=tf.int32, maxval=1024000)
#  uniq_a, uniq_idx = tf.unique(input_a)
#  uniq_a_shape = tf.shape(uniq_a)
#  #uniq_a_shape_print = tf.Print(uniq_a_shape, [uniq_a_shape], "zz:", 10, 10)
#  source_a = tf.gather(uniq_a, uniq_idx)
#  source_a = source_a + source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  source_a = source_a * source_a
#  return source_a
#
#source_a = zz_sm()
with tf.xla.experimental.jit_scope(compile_ops=False):
  input_a = tf.random.uniform([1024000], dtype=tf.int32, maxval=1024000)
  uniq_a, uniq_idx = tf.unique(input_a)
  uniq_a_shape = tf.shape(uniq_a)
  #uniq_a_shape_print = tf.Print(uniq_a_shape, [uniq_a_shape], "zz:", 10, 10)
  source_a = tf.gather(uniq_a, uniq_idx)
  source_a = source_a + source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a
  source_a = source_a * source_a

#  I want to use xla .
res_a_1 = source_a * source_a
res_a_2 = res_a_1 + res_a_1
res_a_3 = res_a_2 + res_a_2
res_a_4 = res_a_3 + res_a_3
res_a_5 = res_a_4 + res_a_4
res_a_6 = res_a_5 + res_a_5


session_config = tf.compat.v1.ConfigProto(allow_soft_placement=True,
                             log_device_placement=True)
#session_config.graph_options.rewrite_options.disable_meta_optimizer=True
session_config.graph_options.optimizer_options.global_jit_level = tf.compat.v1.OptimizerOptions.ON_1


with tf.compat.v1.Session(config = session_config) as sess:
    for i in range(16384) :
      _ = sess.run([res_a_6]);
      #print(res)
```

**Comment by mohantym** [comment]
Hi @zhaozheng09 ! Can you please refer this [thread](https://www.tensorflow.org/install/source) to build from using Bazel 3.7.2 ? [Reference](https://www.tensorflow.org/install/gpu#hardware_requirements). Thank you.
