### ISSUE TITLE
[TFLite] Code Snippet in official GPU Advances Guide Doc Get Crash.

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#53776]
Hi TensorFlowers,
The following codes in [official guide](https://tensorflow.google.cn/lite/performance/gpu_advanced#android_cc) seem to be crash until my [PR](https://github.com/tensorflow/tensorflow/pull/53734) applied, please take a check, thx.
```
// Set up interpreter.
auto model = FlatBufferModel::BuildFromFile(model_path);
if (!model) return false;
ops::builtin::BuiltinOpResolver op_resolver;
std::unique_ptr<Interpreter> interpreter;
InterpreterBuilder(*model, op_resolver)(&interpreter);

// NEW: Prepare GPU delegate.
auto* delegate = TfLiteGpuDelegateV2Create(/*default options=*/nullptr);
if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return false;

// Run inference.
WriteToInputTensor(interpreter->typed_input_tensor<float>(0));
if (interpreter->Invoke() != kTfLiteOk) return false;
ReadFromOutputTensor(interpreter->typed_output_tensor<float>(0));

// NEW: Clean up.
TfLiteGpuDelegateV2Delete(delegate);
```

**Comment by SunAriesCN** [comment]
@multiverse-tf Can you give me a hand?

**Comment by mohantym** [comment]
Hi @SunAriesCN !
Could you check the instructions from the [English document ](https://www.tensorflow.org/lite/performance/gpu#delegate_serialization)for now. 

 Feel free to update in Chinese document too.

Thank you!
