### ISSUE TITLE
A spelling mistake in gpu_delegate_serialization doc.

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#53775]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://tensorflow.google.cn/lite/performance/gpu_advanced#gpu_delegate_serialization

## Description of issue (what needs changing):
 "ThThis improvement is is achieved by exchanging disk space for time savings." -> "This improvement is is achieved by exchanging disk space for time savings."

**Comment by Saduf2019** [comment]
Moving this to closed status as this has bee fixed.
