### ISSUE TITLE
keras.layers.SimpleRNN/LSTM output NaN when setting "activation" to "exponential"

### ISSUE THREAD

**Issue by mazeltovlee** [tensorflow/tensorflow#53779]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.7.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`keras.layers.SimpleRNN` and `keras.layers.LSTM` output `NaN` when setting the `activation` parameter to `exponential` if the shape of input is larger than 3.

**Describe the expected behavior**
`keras.layers.SimpleRNN` and `keras.layer.LSTM` should not output `NaN` under this setting.

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
from tensorflow import keras
x = keras.layers.Input((6,3))
buggy_layer = keras.layers.SimpleRNN(50, activation="exponential")
y = buggy_layer(x)
model = keras.Model(x, y)
import numpy as np
input = np.random.rand(10,6,3)
res = model.predict(input)
model_path = "simple_rnn_exponential.h5"
model.save(model_path)
print(res)
```
You may also access the code here:
https://colab.research.google.com/drive/1mVBIPF79kiIYggZUUkvs1IEB1GdxeoJC?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
To help you identify this issue, I have tried several ways to construct the buggy layer.

Trial 1:
Use `linear` as the activation while adding an additional exponential activation after the SimpleRNN. In this way, the `res` will not output `NaN`
```
from tensorflow import keras
x = keras.layers.Input((6,3))
buggy_layer = keras.layers.SimpleRNN(50, activation="linear")
y = buggy_layer(x)
z = keras.activations.exponential(y)
model = keras.Model(x, z)
import numpy as np
input = np.random.rand(10,6,3)
res = model.predict(input)
print(res)
```

Trial 2:
I tried converting the generated model which will output `NaN` to PyTorch using ONNX, I find that: after converting to PyTorch, the output will contain `Inf` and `0` but no `NaN`. Please see this link for more details about this trial:
https://colab.research.google.com/drive/1mVBIPF79kiIYggZUUkvs1IEB1GdxeoJC?usp=sharing

**Comment by sushreebarsa** [comment]
@mazeltovlee 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by mazeltovlee** [comment]
Thanks for your response, I will pass this issue to keras
