### ISSUE TITLE
[TFLite] Optional Debug Tools can only support log in Desktop Computer

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#53777]
Hi TensorFlowers,
The `tflite::PrintInterpreterState(interpreter.get())` in [minimal.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/minimal.cc#L62) can only be used on computer system with desktop. Because it use `printf` style to output info in [optional_debug_tools.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/optional_debug_tools.cc#L278), not the `TFLITE_LOG` in [minimal_logging](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/minimal_logging.h) the better way supporting more systems. Besides, why not use something like `std::stringstream` to format info, that seems more general?

**Comment by pkgoogle** [comment]
Hi @SunAriesCN, please feel free to submit a PR for your suggested changes, we will review it. Thanks!
