### ISSUE TITLE
issue with building manylinux wheel

### ISSUE THREAD

**Issue by hsl89** [tensorflow/tensorflow#53772]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**

The system is the image build from [this dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.rbe.cuda11.4-cudnn8.2-ubuntu18.04-manylinux2010-multipython)

**Describe the problem**
When fixing the wheel built in the above environment into a manylinux wheel, auditwheel complains 
```
auditwheel: error: cannot repair "/tmp/tensorflow-2.8.0rc0-cp39-cp39-linux_x86_64.whl" to "manylinux2010_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Build commands:
```
cd <tensorflow source>
export TF_NEED_CUDA=1
export TF_CUDA_VERSION=11.4
export TF_CUDNN_VERSION=8

export LD_LIBRARY_PATH="/usr/local/cuda-${CUDA}/targets/x86_64-linux/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs:/usr/local/cuda-${CUDA}/lib64:/usr/local/cuda-${CUDA}/lib64"

export TF_CUDA_COMPUTE_CAPABILITIES=3.7,5.2,7.0,7.5,8.0
  
export TF_BUILD_FLAGS="--config=opt --config=v2 --config=cuda \
    --distinct_host_configuration=false \
    --action_env=TF_CUDA_VERSION --action_env=TF_CUDNN_VERSION \
    --action_env=LD_LIBRARY_PATH --action_env=TF_CUDA_COMPUTE_CAPABILITIES"

yes "" | python3.9 configure.py
bazel build --color=yes --curses=yes $TF_BUILD_FLAGS --verbose_failures \
 //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
before 2.6 there used to be a toolchain to build manylinux wheel 
```
https://github.com/tensorflow/tensorflow/blob/r2.6/third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda11.2/BUILD
```
since 2.7 this toolchain has been removed, I wonder how one should build manylinux wheels without those toolchains

**Comment by satishpasumarthi** [comment]
@mihaimaruseac Could you please provide some insight into this?

**Comment by mihaimaruseac** [comment]
The toolchains are now in tensorflow/toolchains repository. TF's `.bazelrc` and `workspaceN.bzl` files should point to the corresponding file

**Comment by hsl89** [comment]
Hi @mihaimaruseac , I think you are referring to this repo https://github.com/tensorflow/toolchains/tree/master 
but I don't really see nvcc toolchains for building cuda supported manylinux wheel. This file https://github.com/tensorflow/toolchains/blob/master/toolchains/BUILD seems to include a toolchain for building cpu manylinux wheel, but my guess is you need a different toolchain for building gpu wheel

**Comment by sachinprasadhs** [comment]
Hi, could you please refer this PR  https://github.com/tensorflow/build/pull/57 which is merged could address your issue.
Also, refer the comment [here](https://github.com/tensorflow/tensorflow/issues/34946#issuecomment-1130558321), which explains about the manylinux changes from 2.9.0 onwards. Thanks!
