### ISSUE TITLE
Conv 16x8 incorrect reference kernel usage

### ISSUE THREAD

**Issue by felix-johnny** [tensorflow/tensorflow#53784]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):NA
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):NA
- TensorFlow version (use command below):NA
- Python version:NA
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Introduced by PR: https://github.com/tensorflow/tensorflow/commit/0d8705c82c64dfb39c49e346de1a66182e5eabd1

Code in 16x8 conv.cc file expects input/kernel/output offsets to be present if 16x8 conv has a 32 bit bias. But the reference kernel that is invoked does not use offsets as that is the default behavior for 16x8 conv.

**Describe the expected behavior**
It is one of the two
1. Do not expect offsets for 16x8 conv in case of 32 bit bias. In which case the correction is in conv.cc else
2. Add offset handling in the reference kernel.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):no
- Briefly describe your candidate solution(if contributing):NA

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
NA
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by felix-johnny** [comment]
@dayeongl Please have a look..

**Comment by dayeongl** [comment]
Could you elaborate more on this?
"Code in 16x8 conv.cc file expects input/kernel/output offsets to be present if 16x8 conv has a 32 bit bias. But the reference kernel that is invoked does not use offsets as that is the default behavior for 16x8 conv.
"

**Comment by felix-johnny** [comment]
@dayeongl This is just from a code review. So, there aren't any error messages.

So, in conv.cc, 
https://github.com/tensorflow/tensorflow/blob/1a46edf47699a2a10b0e801a48afdc95f5660395/tensorflow/lite/kernels/conv.cc#L811 this line states that for a 16x8 case and with 32 bit bias there can be offsets and the reference kernel is invoked(reference_integer_ops::ConvPerChannel)

The reference implementation for 16x8 (https://github.com/tensorflow/tensorflow/blob/1a46edf47699a2a10b0e801a48afdc95f5660395/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h#L129) does not have a provision for handling offsets.

**Comment by Tessil** [comment]
Note that `has_non_zero_point` https://github.com/tensorflow/tensorflow/blob/1a46edf47699a2a10b0e801a48afdc95f5660395/tensorflow/lite/kernels/conv.cc#L797
should never be true as quantized int16 tensors should always have a null zero-point. 

It's also enforced by the 
https://github.com/tensorflow/tensorflow/blob/1a46edf47699a2a10b0e801a48afdc95f5660395/tensorflow/lite/kernels/conv.cc#L359
check in the Prepare method of the Conv2D operator.

**Comment by felix-johnny** [comment]
@dayeongl Could you confirm the intention with zero points and int16?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
