### ISSUE TITLE
`tf.scatter_nd` document refers to deprecated apis

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53783]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.7/api_docs/python/tf/scatter_nd

### Clear description
 Here is a paragraph describing the relationship between `tf.scatter_nd` and `tf.tensor_scatter_add`:

> This operation is similar to tf.tensor_scatter_add, except that the tensor is zero-initialized. Calling tf.scatter_nd(indices, values, shape) is identical to calling tf.tensor_scatter_add(tf.zeros(shape, values.dtype), indices, values).

However,  `tf.tensor_scatter_add` does not exist in TensorFlow 2.7, `tf.tensor_scatter_add` should be replaced with [`tf.tensor_scatter_nd_add`](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_add).

**Comment by Cheril311** [comment]
I can fix this

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky , @Cheril311 ,
Please feel free to submit a PR for the requested change or share the link where requested change is to be made.

**Comment by Cheril311** [comment]
@tilakrayal cannot find the source file for the mentioned issue, can you help me a bit?

**Comment by jvishnuvardhan** [comment]
@ArrowIntoTheSky Thanks for raising this issue. This was merged internally and will show up soon on the TF website. Thanks again.
