### ISSUE TITLE
BUG Fail to save model when tf.summary is used inside keras model

### ISSUE THREAD

**Issue by MaxwellLZH** [tensorflow/tensorflow#53791]
**System information**
- OS: Linux
- Python Version: 3.6.8
- Tensorflow version: Git version v2.6.0-rc2-32-g919f693420e  tf_version 2.6.0

**Describe the current behavior**
`tf.keras.Model.save` raises error when `tf.summary` is used inside of `call` function. A short script for reproducing the problem: 
```python
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

class Mymodel(tf.keras.Model):
    
    def __init__(self):
        super().__init__()
        self.l = tf.keras.models.Sequential([
            layers.Dense(64) for _ in range(3)
        ] + [layers.Dense(1)])
    
    def call(self, inputs, training=None):
        tf.summary.scalar(name='avg_1', data=tf.reduce_sum(inputs))
        return self.l(inputs)

m = Mymodel()
m.compile(loss='mse', optimizer='adam')
m.fit(np.random.randn(1000, 20), np.random.randn(1000), epochs=5)

m.save('/tmp', save_format='tf')
```
this raises the following error:
```
AssertionError: Tried to export a function which references untracked resource Tensor("72061:0", shape=(), dtype=resource). TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
Trackable Python objects referring to this tensor (from gc.get_referrers, limited to two hops)
```
everything works fine if I comment out the `tf.summary.scalar` line.

**Comment by MaxwellLZH** [comment]
Any update on this issue? It seem like a pretty obvious bug and can affect a lot of use cases.

**Comment by tilakrayal** [comment]
@MaxwellLZH ,
I was facing different error while trying to execute the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/50606e360b18554c654e35452ad0db36/untitled190.ipynb) and share the required dependencies.Thanks!

**Comment by kalosisz** [comment]
@tilakrayal you are missing the layers import. check it [here](https://colab.research.google.com/gist/kalosisz/bee99d0803270b8d1da5071074bbb2da/untitled190.ipynb)

It can save and load the model
