### ISSUE TITLE
C++ SetDefaultDevice does not appear to work properly

### ISSUE THREAD

**Issue by beniz** [tensorflow/tensorflow#5379]
I'm using a simple C++ session that works fine otherwise. Trying to use `tensorflow::graph::SetDefaultDevice` to pin on either CPU or GPU (per id) does not appear to work:

- without `SetDefaultDevice`:

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   Y Y   
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus i
d: 0000:02:00.0)  
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K40c, pci bus i
d: 0000:03:00.0) 
```
all goes well beyond this point.

- now trying to pin on `GPU0`:
```
tensorflow::graph::SetDefaultDevice("/gpu:0", &graph_def);
```
yields
```
E tensorflow/core/common_runtime/direct_session.cc:132] Invalid argument: Could not parse entry in 'visible_device_list': '/gpu:0'.  visible_device_list = /gpu:0
```
Same with `/cpu:0`, no surprise.

- looking at https://github.com/tensorflow/tensorflow/blob/f7ec99516ce0e0937e0b865e90aa02c748cd36c6/tensorflow/core/common_runtime/gpu/gpu_device.cc#L808 it seems the code is rather looking for an int ? Trying it out:

```
tensorflow::graph::SetDefaultDevice("0",&graph_def);
```
yields
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:02:00.0)
E tensorflow/core/common_runtime/gpu/process_state.cc:108] Invalid allocator type: 0
```

Am I doing something wrong or has something changed (maybe due to 3e8c4fd7403659ec32b9fec90a78831043aa0786 ?)

The tutorial at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/tutorials/example_trainer.cc#L104 still calls on `SetDefaultDevice` the way I tried to use it, this seems odd :)

**Comment by aselle** [comment]
Check that this error doesn't occur when you don't call SetDefaultDevice at all. @keveman, do you have any inight?

**Comment by vrv** [comment]
I'm going to go out on a limb and suggest that you are setting 'visible_device_list' incorrectly in your ConfigProto, and this has nothing to do with SetDefaultDevice.  SetDefaultDevice doesn't touch 'visible_device_list', and the documentation of 'visible_device_list' should clear up what the syntax is supposed to be.  Please comment if you disagree and I'll reopen!

**Comment by beniz** [comment]
@aselle hi, see the initial report, there's no error when no call is made to `SetDefaultDevice`.

@vrv hi, I can certify we are not touching anything within the `ConfigProto` in our code (it's heere actually https://github.com/beniz/deepdetect/blob/tf/src/tflib.cc#L199) besides the `set_allow_growth` option that is set to `true`. 
I believe I understand what `SetDefaultDevice` does and that `visible_device_list` is outside its scope but if you look at the initial report you can see the initial parsing error can be avoided by setting up the device to `0` instead of `/gpu:0` and that with the parsing code `strings::safe_strto32(gpu_id_str, &gpu_id)` looks suspicious to me.

Please let me know if I can run tests somehow to drive closer to the root of the problem here.

**Comment by vrv** [comment]
I just can't see a codepath that connects anything in the graph to "visible_device_list".  In fact, visible_device_list is *only* populated here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/gpu_device.cc#L525, which comes from the ConfigProto.

**Comment by kalluwa** [comment]
[ **Windows 10 x64** ] I have found a solution for using "setDefaultDevice" with no exception:

edit **tensorflow/tf_version_script.lds** to:

> this code is from another issue, but i cannot find it out now

```
tensorflow {
  global:
    *tensorflow*;
    *perftools*gputools*;
    *TF_*;
    *TFE_*;
    *nsync_*;
    *protobuf*;
  local:
    *;
};
```
then compile the source( r1.2 is tested ok)
you will get tensorflow.dll and lib, but if use these two file in your project you will encounter the exception.
 please use ***.obj** file instead of ~~tensorflow.dll/lib~~
Edit your **vcxproj** file (add a lot of Object Entries) just like:
```
<ItemGroup>
        <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\arena.obj" />
    <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\bitmap.obj" />
    <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\coding.obj" />
    <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\status.obj" />
    <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\stringpiece.obj" />
    <Object Include="E:\twd\build_from_source\buildgpu12_setdevice\tf_core_lib.dir\$(Configuration)\threadpool.obj" />
...
```
more details see [this link](https://pan.baidu.com/s/12OLFuQ4htdLbNQ-z57408g)

---
and the exception is gone.
but :
exe file is larger  (10MB - > 150MB)
no tensorflow.dll depends

**Comment by knighthappy** [comment]
my solution:
tensorflow1.8
c++

https://blog.csdn.net/cdknight_happy/article/details/81100554

**Comment by ttdd11** [comment]
@knighthappy were you able to resolve the SetDefaultDevice issue?
