### ISSUE TITLE
Use enable_op_determinism + Fixed seed + same hardware (partial DGX) still get different results in 2.8. 

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#53792]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.8rc0
- Python version: 3.8.12
- GPU model and memory:8*V100

After I use enable_op_determinism in TensorFlow 2.8, my model still gets random results (around 0.3 mIOU) after each run. Note that, I set PYTHONHASHEED to a fixed value before start python, and also set a fixed value as the random seed for TensorFlow and numpy etc.

I wonder why the result is still random in same hardware, since the UnimplementedError should be thrown if nondeterministic op is used.

**Comment by edwardyehuang** [comment]
@duncanriach

**Comment by sushreebarsa** [comment]
@edwardyehuang 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by duncanriach** [comment]
@edwardyehuang, this could be due to issue [53771](https://github.com/tensorflow/tensorflow/issues/53771). Does your model use convolution? Seconding @sushreebarsa's request for a reproducer.

**Comment by edwardyehuang** [comment]
> @edwardyehuang, this could be due to issue [53771](https://github.com/tensorflow/tensorflow/issues/53771). I assume that your model uses convolution. Seconding @sushreebarsa's request for a reproducer.

Thanks for your reply. I will try it. However, should I set TF_CUDNN_USE_FRONTEND = 1 before python start?

**Comment by edwardyehuang** [comment]
Not work, sorry. I ran the same model on two 4*v100 machine, with TF_CUDNN_USE_FRONTEND =1

**Comment by duncanriach** [comment]
@edwardyehuang, yes, running with `TF_CUDNN_USE_FRONTEND=1 ` would be the workaround for the base issue discussed in #53771; thanks for adding that to your process. It is possible, although it's very unlikely that you're running into the OOM issue discussed in #53771.

You mention that you're running on a 4*V100 machine. I assume that you're only running on one of the GPUs though. Is that correct?

**Comment by edwardyehuang** [comment]
> @edwardyehuang, yes, running with `TF_CUDNN_USE_FRONTEND=1 ` would be the workaround for the base issue discussed in #53771; thanks for adding that to your process. It is possible, although it's very unlikely, that you're running into the OOM issue discussed in #53771; I doubt it's that.
> 
> You mention that you're running on a 4*V100 machine. I assume that you're only running on one of the GPUs though. Is that correct?

Sorry I misunderstood it. I ran on 4*v100 or 8*v100 without OOM. However, after I set TF_CUDNN_USE_FRONTEND=1, my result still is different on each run.  Is there any other soruce can result nondeterminism?

Note that, I may not use the same v100 cards in each run.

**Comment by duncanriach** [comment]
My question is this: are you training on a single GPU or on a multi-GPU setup? If you're training using more than one GPU, what regime are you using to coordinate the work between the GPUs?

**Comment by edwardyehuang** [comment]
> regime are you using to coordinate the work

I am using multi-GPU setup with tf.distribute.MirroredStrategy()

I think the GPUs connection is simliar like DGX, since the GPU card name is "Tesla V100-SXM2...".

I may check futher information if you need

**Comment by edwardyehuang** [comment]
I will try a small setup, for both single and multi-gpu, on my own machine (2 * Titan RTX), to see if the problem is still existing.

**Comment by edwardyehuang** [comment]
> I will try a small setup, for both single and multi-gpu, on my own machine (2 * Titan RTX), to see if the problem is still existing.

In my own machine with multiple-gpu setup (2* Titan RTX), it can be repeated. I will try to figure out it cannot be repeated in my company machine (maybe different v100 cards each run?)

**Comment by duncanriach** [comment]
It's always good to narrow the issue down by discovering if it happens on a single GPU or not. If a single GPU is operating deterministically, then the problem would be related to the multi-GPU setup. If a single GPU does not operate deterministically, then you've narrowed the problem down, leading towards a smaller/simpler reproducer.

**Comment by edwardyehuang** [comment]
> It's always good to narrow the issue down by discovering if it happens on a single GPU or not. If a single GPU is operating deterministically, then the problem would be related to the multi-GPU setup. If a single GPU does not operate deterministically, then you've narrowed the problem down, leading towards a smaller/simpler reproducer.

Possible source of nondeterminism is located. 

When I used entire DGX (8 * v100), even not the same machine every time, the result can be repeated (deterministically).
When I only used partial of DGX (e.g. 4 * v100), the result is nondeterminism

@duncanriach

**Comment by sushreebarsa** [comment]
@edwardyehuang 
In order to expedite the trouble-shooting process, could you please provide a code snippet to reproduce the issue reported here. Please try with the latest tf-nightly and let us know the outcome? 
Thanks!

**Comment by edwardyehuang** [comment]
> @edwardyehuang In order to expedite the trouble-shooting process, could you please provide a code snippet to reproduce the issue reported here. Please try with the latest tf-nightly and let us know the outcome? Thanks!

Thanks for your reply. Please read previous replies and #53771 . 
What we diccussed in this issue and #53771  already slightly beyond tf-nightly. And a code snippet cannot reproduce the issue since this is caused by multi-gpus.

Regards

**Comment by duncanriach** [comment]
@edwardyehuang,

1. By discovering that there is nondeterminism with 4 GPUs but not with 8 GPUs, you have mostly ruled out the possibility that this is a within-GPU issue, and therefore you have mostly ruled out that your issue is related to #53771.
2. Ideally, you would run on a single GPU just to confirm that it is definitely not a within-GPU issue.
3. It may be possible that you are running into [this issue](https://github.com/NVIDIA/framework-determinism/issues/39), in the framework-determinism repo, which I have asked @yanniskar to move into the main TensorFlow repo. This reports a problem with `tf.data.experimental.sample_from_datasets` in the context of multi-GPU.
4. Regardless, it is theoretically possible to provide a code snippet to reproduce the issue, including the code you use to configure multi-GPU operation. As @sushreebarsa states, once you provide a simple-as-possible reproducer, it makes debugging possible on our side. Up until now, I've only been able to help you to isolate the problem into a smaller scope, through this remote-guidance process.

**Comment by edwardyehuang** [comment]
Close this issue for now, since I am very busy atm, and the current staus of determinism (8×v100) is enough for me to largely outperform prior art preformance deterministically.

I will reopen this issue afterwards, and will ack your hard working on determinism in my paper.

**Comment by duncanriach** [comment]
Thank you, @edwardyehuang.
