### ISSUE TITLE
'tensorflow/core/public/session.h' file not found

### ISSUE THREAD

**Issue by MircoT** [tensorflow/tensorflow#5380]
I didn't find anything about this problem. I'm creating the python package from the source with bazel, the commands used are the same of the official guide in the section [create pip package](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#create-the-pip-package-and-install).

The file *.whl* generated is working but doesn't have some include files that I use in a new op created in C++. The missing files are **session_options.h** and **session.h** which, however, are present in the official *.whl* of tensorflow that you can download (the binary package pre-compiled).

To add those files I had to insert some requirements in *tensorflow/core/BUILD*:

```
---
 tensorflow/core/BUILD | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/tensorflow/core/BUILD b/tensorflow/core/BUILD
index 79546cc..7d9e9a2 100644
--- a/tensorflow/core/BUILD
+++ b/tensorflow/core/BUILD
@@ -214,6 +214,9 @@ cc_library(
         "platform/strong_hash.h",
         "platform/thread_annotations.h",
         "platform/types.h",
+        "public/version.h",
+        "public/session.h",
+        "public/session_options.h",
     ],
     visibility = ["//visibility:public"],
     deps = [
@@ -299,6 +302,8 @@ tf_cuda_library(
         "framework/type_traits.h",
         "framework/types.h",
         "public/version.h",
+        "public/session.h",
+        "public/session_options.h",
         "util/bcast.h",
         "util/cuda_kernel_helper.h",
         "util/device_name_utils.h",
-- 
2.10.2
```

Is it normal or I missed some configuration during the building? I could not fix it without this additions.

### Environment info
Operating System: macOS Sierra (10.12.1)

Installed version of CUDA and cuDNN: NO CUDA

Source:

1. The commit hash: "eaa9dde98d95f843ad1d3d0f5956693991372e4a"
2. Bazel version:
```
Build label: 0.3.2-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Oct 8 08:02:20 2016 (1475913740)
Build timestamp: 1475913740
Build timestamp as int: 1475913740
```

### Example to test

If you try to import a graph as you can see in the [guide](https://www.tensorflow.org/versions/r0.11/api_docs/cc/index.html) you need to require the header: `#include "tensorflow/core/public/session.h"`.

### Logs or other output that would be helpful
```
... fatal error: 'tensorflow/core/public/session.h' file not found
#include "tensorflow/core/public/session.h"
         ^
1 error generated.
make: *** [...] Error 1
```

**Comment by vrv** [comment]
Will send a fix, thanks for the report!

**Comment by kalli8** [comment]
I'm getting this error, where is the fix?

**Comment by zhangbei07** [comment]
I'm getting this error, where is the fix?
