### ISSUE TITLE
Deprecation message for tf.compat.v1.batch_gather suggests invalid migration

### ISSUE THREAD

**Issue by dniku** [tensorflow/tensorflow#53806]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): `v2.7.0-0-gc256c071bb2 2.7.0`
- Python version: `3.7.12`

**Describe the current behavior**

Using `tf.compat.v1.batch_gather` triggers the following warning:

```python
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1096: batch_gather (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2017-10-25.
Instructions for updating:
`tf.batch_gather` is deprecated, please use `tf.gather` with `batch_dims=-1` instead.
```

This warning was last edited in [this commit](https://github.com/tensorflow/tensorflow/commit/50abb98b7db07adc78df883ffa7b6c6dd4273ffc).

However, the suggested migration from `tf.compat.v1.batch_gather(...)` to `tf.gather(..., batch_dims=-1)` is invalid — e.g., see [this Colab notebook](https://colab.research.google.com/gist/dniku/7510249f61b9b00881af6c0bcfdac7a3/tf_migrate_batch_gather_to_gather.ipynb) for an example. From the [implementation](https://github.com/tensorflow/tensorflow/blob/c256c071bb26e1e13b4666d1b3e229e110bc914a/tensorflow/python/ops/array_ops.py#L5166) of `batch_gather` it seems that the correct migration is from

```python
tf.compat.v1.batch_gather(data, indices)
```
to
```python
tf.gather(data, indices, batch_dims=tf.rank(indices) - 1)
```

**Describe the expected behavior**

The warning should be amended.

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf [v2.7](https://colab.research.google.com/gist/tilakrayal/7b6fddffae4c22cb2a86fa3d63728ada/tf_migrate_batch_gather_to_gather-2-7.ipynb), [v2.5](https://colab.research.google.com/gist/tilakrayal/917e6d99b4c31b4aaee98deba7202cc4/tf_migrate_batch_gather_to_gather2-5.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/da1a790730efaeaaf1a2ce1fddf8d246/tf_migrate_batch_gather_to_gather.ipynb).Please find the gist here.

**Comment by rthadur** [comment]
This should be fixed , I made the change internally.Thank you @dniku
