### ISSUE TITLE
Segmentation model C++ API's based inference output different from Python tensors

### ISSUE THREAD

**Issue by nullbyte91** [tensorflow/tensorflow#53802]
**System information**
- Have I written custom code:No
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):  Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.1-cudnn7
- GPU model and memory:

**Describe the current behavior**
We've trained a Segmentation model using Keras with Tensorflow backend. Now, We are trying to infer by using the TF C++ interface.
I used the below code snippet to convert the .h5 model to a .pb file.

```python
keras_model_path="keras_model.h5"
model = tf.keras.models.load_model(keras_model_path,  compile=False)
model.summary()
tf.saved_model.save(model, "~/tf2_cpp/")
```

Our python pipeline,
```python
model = tf.keras.models.load_model(keras_model_path,  compile=False)
img = cv2.imread("test.jpg")
resized_img = cv2.resize(img,(224, 224)).reshape([1, 224, 224,3]).astype(np.float32)
output = model.predict(resized_img) #7, 224, 244, 2
mask = tf.argmax(output[0], axis=3) #1, 244, 244
```
our C++ pipeline,
```c++
// Pre Processing
cv::Mat img = cv::imread("test.jpg")
cv::Size s(224,224);
cv::resize(img, img, s, cv::INTER_LINEAR);
tensorflow::Tensor input_tensor(tensorflow::DT_FLOAT, tensorflow::TensorShape({1, height, width, depth}));
float *p = input_tensor.flat<float>().data();
cv::Mat fakeMat(224, 224, CV_32FC3, p);
img.convertTo(fakeMat, CV_32FC3);

// Prediction
const string input_node = "serving_default_input_4:0";
// std::vector<std::pair<string, tensorflow::Tensor>> inputs_data  = {{input_node, input_tensor_mapped}};
std::vector<string> output_nodes = {{"StatefulPartitionedCall:3",
    "StatefulPartitionedCall:2", 
    "StatefulPartitionedCall:5", 
    "StatefulPartitionedCall:1",
    "StatefulPartitionedCall:4",             
    "StatefulPartitionedCall:0",
    "StatefulPartitionedCall:6"}};

std::vector<Tensor> predictions;

this->bundle.GetSession()->Run({{input_node, input_tensor}}, output_nodes, {}, &predictions);

//Post-processing
auto argOps = tensorflow::ops::ArgMax(transposeScope, predictions[1], 3);
std::vector<Tensor> temOutputs;
TF_CHECK_OK(sess.Run({argOps}, &temOutputs));
```

The tensor value is different when I compare the result between Python and C++. And, C++ argmax API returning zero for all the tensor as well.

**Describe the expected behavior**
The output expected to be same in both Python and C++. Maybe with some precision changes.

**Comment by tilakrayal** [comment]
@nullbyte91 ,
 In order to expedite the trouble-shooting process, could you please provide a complete code to reproduce the issue.Also
could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!

**Comment by sguelbol** [comment]
ArgMax doesnt work, I suppose it has a bug, it returns a list of zero for the tensor
