### ISSUE TITLE
undefined symbol: _ZN4llvm7APFloat15getAllOnesValueERKNS_12fltSemanticsEj Target //tensorflow:libtensorflow_cc.so

### ISSUE THREAD

**Issue by hujhcv** [tensorflow/tensorflow#53813]
**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from source
- TensorFlow version: 2.7.0
- Python version: 3.9.6
- Bazel version: 3.7.2
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: GTX3060

**Describe the problem**
Build tensorFlow 2.7.0 from source error:
ERROR: /root/Tensorflow/tensorflow-2.7.0/tensorflow/core/kernels/mlir_generated/BUILD:1146:23: Generating kernel '%{label}' failed (Exit 127): tf_to_kernel failed: error executing command bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel '--unroll_factors=4' '--tile_sizes=1024' '--max-supported-rank=5' '--arch=compute_86' ... (remaining 5 argument(s) skipped)
bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel: symbol lookup error: bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tools/kernel_gen/tf_to_kernel: undefined symbol: _ZN4llvm7APFloat15getAllOnesValueERKNS_12fltSemanticsEj
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17520.571s, Critical Path: 494.07s
INFO: 19740 processes: 6816 internal, 12924 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
set CUDA support Yes
bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so

**Any other info / logs**
the same error at TensorFlow 2.8

**Comment by tilakrayal** [comment]
@hujhcv ,
Can you please confirm if you are trying to install from these link [1](https://github.com/tensorflow/tensorflow/blob/master/README.md) and [2](https://www.tensorflow.org/install/lang_c).Thanks!

**Comment by hujhcv** [comment]
> @hujhcv , Can you please confirm if you are trying to install from these link [1](https://github.com/tensorflow/tensorflow/blob/master/README.md) and [2](https://www.tensorflow.org/install/lang_c).Thanks!

I use "pip install tensorflow" to install tensorflow. and try like this：import tensorflow as tf
error is as follows：

(py39) root@bsyai:~# python
Python 3.9.6 (default, Aug 18 2021, 19:38:01) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 79, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
>>> exit()

**Comment by hitbuyi** [comment]
> > [@hujhcv](https://github.com/hujhcv) , Can you please confirm if you are trying to install from these link [1](https://github.com/tensorflow/tensorflow/blob/master/README.md) and [2](https://www.tensorflow.org/install/lang_c).Thanks!
> 
> I use "pip install tensorflow" to install tensorflow. and try like this：import tensorflow as tf error is as follows：
> 
> (py39) root@bsyai:~# python Python 3.9.6 (default, Aug 18 2021, 19:38:01) [GCC 7.5.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import tensorflow as tf
> > > > Traceback (most recent call last):
> > > > File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in 
> > > > from tensorflow.python._pywrap_tensorflow_internal import *
> > > > ImportError: /opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/**init**.py", line 41, in from tensorflow.python.tools import module_util as _module_util File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/**init**.py", line 40, in from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 79, in raise ImportError( ImportError: Traceback (most recent call last): File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in from tensorflow.python._pywrap_tensorflow_internal import * ImportError: /opt/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
> 
> Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/errors for some common causes and solutions. If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
> 
> > > > exit()

some issue, have you solved it ?
