### ISSUE TITLE
`tf.norm` not accurate in Tensorflow 2.7.0

### ISSUE THREAD

**Issue by Janus-Shiau** [tensorflow/tensorflow#53816]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pypl
- TensorFlow version (use command below): v2.7.0
- Python version: 3.8.10
- Bazel version (if compiling from source): not required
- GCC/Compiler version (if compiling from source): not required
- CUDA/cuDNN version: 11.0 (from docker image of TF 2.7.0)
- GPU model and memory: 2080ti

**Describe the current behavior**

We are using `tf.norm` to make a vector be unit vector.

This is quite simple and we use the following code in TF 2.2.0.

```python
vec = np.array([4.6463e-03, -4.8086258e+01], dtype="float32")
amount = tf.norm(vec, ord=2, axis=-1)
```

The amount is `<tf.Tensor: shape=(), dtype=float32, numpy=48.086258>` in TF 2.2.0.
Thus the normalizing is correct and we get an unit vector by `vec / amount`.
But in TF 2.7.0, the amount will be `<tf.Tensor: shape=(), dtype=float32, numpy=48.086254>`, which is incorrect.

We also found that this situation only happened when the tensor is computed on GPU.
In other word, if we set `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`, we could get correct value in TF 2.7.

**Describe the expected behavior**

The norm value should be `<tf.Tensor: shape=(), dtype=float32, numpy=48.086258>` in both CPU or GPU.

**Comment by tilakrayal** [comment]
@Janus-Shiau ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

**Comment by Janus-Shiau** [comment]
I think using the code block above can reproduce the problem.
But I can also provide more if you need.

```python=3.8
import numpy as np
import tensorflow as tf

if not tf.__version__ == "2.7.0" or not tf.test.is_gpu_available():
    return

vec = np.array([4.6463e-03, -4.8086258e+01], dtype="float32")
amount = tf.norm(vec, ord=2, axis=-1)

print(amount)
``` 
In my case, this is enough to reproduce the issue.

**Comment by tilakrayal** [comment]
@Janus-Shiau ,
I was facing different error while trying to execute the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0c9110805d5e9ecb36ea12f907004de9/untitled196.ipynb).

**Comment by bersbersbers** [comment]
@tilakrayal delete the `if` and the `return` and you see the problem.

**Comment by Janus-Shiau** [comment]
Thank you @bersbersbers. Your example is quite clear!
The `if` statement is aim to make sure the TF version is correct and GPUs are utilized.

**Comment by bersbersbers** [comment]
This problem has two parts, offering two workarounds:

1. Part of the problem is that GPU TensorFlow is computing, by default, using `float32`, while CPU TensorFlow is doing `float64` computations (as do `numpy` and Python's `math` module):

   ```python
   import math
   import numpy as np
   import tensorflow as tf
   
   x = 99.0
   a = np.array(x)
   a32 = np.array(x, dtype=np.float32)
   a64 = np.array(x, dtype=np.float64)
   t = tf.constant(x)
   t32 = tf.constant(x, dtype=tf.float32)
   t64 = tf.constant(x, dtype=tf.float64)
   
   print(np.sqrt(a32))
   print(tf.sqrt(t).numpy())
   print(tf.sqrt(t32).numpy())
   
   print(math.sqrt(x))
   print(np.sqrt(a))
   print(np.sqrt(a64))
   print(tf.sqrt(t64).numpy())
   ```
   
   Output:
   ```
   9.949874
   9.949874
   9.949874
   9.9498743710662
   9.9498743710662
   9.9498743710662
   9.9498743710662
   ```
   
   You see that `a` behaves like `a64`, while `t` behaves like `t32`. You can avoid the problem using `float64`.

2. But this is not the whole story. Yes, it's similar for `tf.norm`:

   ```python
   import numpy as np
   import tensorflow as tf
   
   x = 48.086258
   a = np.array(x)
   a32 = np.array(x, dtype=np.float32)
   a64 = np.array(x, dtype=np.float64)
   t = tf.constant(x)
   t32 = tf.constant(x, dtype=tf.float32)
   t64 = tf.constant(x, dtype=tf.float64)
   
   print(tf.norm(t).numpy())
   print(tf.norm(t32).numpy())
   
   print(np.linalg.norm(a))
   print(np.linalg.norm(a32))
   print(np.linalg.norm(a64))
   print(tf.norm(t64).numpy())
   ```
   
   Output:
   ```
   48.086254
   48.086254
   48.086258
   48.086258
   48.086258
   48.086258
   ```
   
   But you also see that this time, `numpy` computes correctly in `float32`. Interestingly, the same is true in TF using the alternative code commented out here:
   
   https://github.com/tensorflow/tensorflow/blob/c256c071bb26e1e13b4666d1b3e229e110bc914a/tensorflow/python/ops/linalg_ops.py#L759-L763
   
   ```python
   import tensorflow as tf
   from tensorflow.python.ops import math_ops
   
   x = 48.086258
   t32 = tf.constant(x, dtype=tf.float32)
   
   print(math_ops.sqrt(math_ops.reduce_sum(t32 * math_ops.conj(t32))).numpy())
   print(math_ops.reduce_euclidean_norm(t32).numpy())
   ```
   
   Output:
   ```
   48.086254
   48.086258
   ```
   
   So another workaround is to use `math_ops.reduce_euclidean_norm`, and you can stick to your `float32` data type.

I guess the TF team should switch to `math_ops.reduce_euclidean_norm` according to the `TODO` comment.

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/f0607f8b519b7cd48e46fe9e958a2c41/53816_2-5.ipynb),[v2.7](https://colab.research.google.com/gist/tilakrayal/178449572d81bfd8f6a1949897832195/53816-2-7.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/d4edc7553898f01c0876a23bd72d4577/53816-nightly.ipynb).Please find the gist here.

**Comment by jvishnuvardhan** [comment]
@bersbersbers @Janus-Shiau Looks like this was resolved. Can you please check this [gist](https://colab.research.google.com/gist/jvishnuvardhan/1fa8750bc428f6dbc31bdae7b86ebb85/untitled1157.ipynb). Please let me know if i am missing anything. Thanks!

**Comment by jvishnuvardhan** [comment]
@bersbersbers @Janus-Shiau Disregard my last comment. I ran it on CPU which works well as you mentioned earlier. 
This is throwing wrong results on GPU. Thanks

**Comment by bersbersbers** [comment]
Excuse my ignorance, but it looks to me like https://github.com/tensorflow/tensorflow/commit/18937a7232d8c66559b44afb99da2743f907da5a exactly reverted https://github.com/tensorflow/tensorflow/commit/d5a0174ddd279c1dd8ee434aa05edea4e0afaaf0. Should this issue be re-opened?

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with `tf-nightly-2.11.0-dev20220829`. Please find the attached gist [here](https://colab.research.google.com/drive/1Sa0pnFYR2IlQzuUHOiT57yAJLfepy98b?usp=sharing). Thank you!

**Comment by cantonios** [comment]
@bersbersbers yes, it was reverted.

The issue is that the change to always use the `EuclideanNorm` op from within `tf.norm` breaks many workflows that rely on the existing `norm` function, since it introduces a new op that isn't supported on all devices.

The only workable solution is that if you *need* the higher accuracy, then use `tf.math.reduce_euclidean_norm` directly. 
 Internally, it uses a more stable way of computing the norm that less prone to overflow and precision issues.
