### ISSUE TITLE
tensorflow.datasets.load() throws an exception

### ISSUE THREAD

**Issue by vyepishov1** [tensorflow/tensorflow#53815]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: not a mobile device
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.8.0-rc0-28-g24a4b3b5e58 2.8.0-rc1
- Python version: 3.8
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.2 / 8.1.1.33
- GPU model and memory: NVIDIA GeForce 940MX 1629 MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After running the script

`import tensorflow as tf
import tensorflow_datasets as tfds

print(tf.__version__)
datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)`

I am getting the following output:

2.8.0-rc1
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Describe the expected behavior**
No exception is expected

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

`import tensorflow as tf
import tensorflow_datasets as tfds

print(tf.__version__)
datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @vyepishov1 ! There are import issues in 2.8.rc0 in Colab.  Attaching relevant threads link [1](https://github.com/tensorflow/tensorflow/issues/14885) ,[2](https://github.com/tensorflow/tensorflow/issues/17216)  though. Can you try building from sources with tested[ specification](https://www.tensorflow.org/install/source#gpu) ? Thank you!

**Comment by vyepishov1** [comment]
> Hi @vyepishov1 ! There are import issues in 2.8.rc0 in Colab. Attaching relevant threads link [1](https://github.com/tensorflow/tensorflow/issues/14885) ,[2](https://github.com/tensorflow/tensorflow/issues/17216) though. Can you try building from sources with tested[ specification](https://www.tensorflow.org/install/source#gpu) ? Thank you!

Hi @mohantym! Thank you for the advice. I managed to get working tensorflow 2.7.0 that was built with the GPU support, but my aim was to try the 2.8 version. Anyway, I think I have found the working solution by removing the --config=monolithic option from the bazel build. Also, I used gcc 7 instead of gcc 9 (not sure, if the latest had also the influence onto getting proper wheel).

**Comment by vyepishov1** [comment]
Can confirm that I could manage to build working tensorflow 2.8.0-rc1 with enabled CUDA and MKL support by removing the --config=monolithic options and using GCC 7 instead of GCC 9. Anyway, some work needs to be done with the 2.8.0 version to make it possible to use the --config=monolithic option as well.

**Comment by mohantym** [comment]
@vyepishov1 ! if you are looking to build with mkl support , you can put **--config=mkl** instead **--config=monolithic**. Attaching relevant [thread ](https://www.tensorflow.org/install/source#preconfigured_configurations)for reference. Thank you!
