### ISSUE TITLE
Installing TF without Google OAuthLib

### ISSUE THREAD

**Issue by x0734x** [tensorflow/tensorflow#53810]
**System information**
- OS Platform and Distribution: Docker deployment with RedHat 8 base image
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.7
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: virtualenv
- CUDA/cuDNN version: TBA (Will get info, but don't think it's relevant to issue)
- GPU model and memory: TBA (Will get info, but don't think it's relevant to issue)

**Problem**
Hi,

Where I work, we use Twistlock, a container security analysis tool, in our current workflow.

Twistlock reports this error with our current container:

`There is no support for PKCE implementation in the oauthlib client. Client-side PKCE for OAuth2 RFC 7636 is required for applications to have secure communication with the authorization server. OAuth 2.0 public clients utilizing the Authorization Code Grant are susceptible to the authorization code interception attack.`

We don't have the luxury to use another version of TF; we effectively need to use as close to the latest version as we can. That said, we need to be able to install TF but without this lib. Is this possible?

I should mention it seems this lib is needed to train models on Google Cloud (or so I read), but we don't need that functionality.

It would be helpful if this could be an optional feature instead of a required one. Currently, this is preventing us from deploying our container, as we can't deploy if this error yields.

I also apologize if this is improper use of this ticket (or ticketing system), I was asked to create one in the mean time, so the people managing Twistlock can make an exception if they can refer back to this ticket, but I also am seeking information about this issue we ran into.

Thanks for your time in advance.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Create docker container with Redhat 8 and Python 3.8.8, and startup container
2. create virtualenv
3. pip install tensorflow
4. Run Twistlock on container (I'm greatly simplifying this step because Twistlock is part of service that's not directly in our hands; we submit the container to a service that automatically runs Twistlock 3rd party for us.)

**Any other info / logs**

Twistlock:
`There is no support for PKCE implementation in the oauthlib client. Client-side PKCE for OAuth2 RFC 7636 is required for applications to have secure communication with the authorization server. OAuth 2.0 public clients utilizing the Authorization Code Grant are susceptible to the authorization code interception attack.`

**Comment by sushreebarsa** [comment]
@x0734x 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by x0734x** [comment]
I updated it a bit. Let me know if you need more info.

**Comment by x0734x** [comment]
I think there is a misunderstanding here... I'm not having trouble installing Tensorflow. I'm saying the installation of TF requires a library *that has a known security vulnerability* as described by Twistlock - a service we use to scan for vulnerabilities. So I'm asking is there a way to install TF without this Google OAuth lib? (Cause we don't need the library)

I don't see anywhere in the installation guides where this lib can be made option if installed from source either.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
