### ISSUE TITLE
How to add monolithic flag when compile tensorflow-lite with cmake tools

### ISSUE THREAD

**Issue by lantianguhong** [tensorflow/tensorflow#53817]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

OS Platform and Distribution: 
Linux centos 7.6
TensorFlow installed from source
TensorFlow version: 2.7.0
Python version: 3.9.6
Bazel version: 4.2.2
GCC/Compiler version (if compiling from source): 7.3.1

**Describe the problem**
![image](https://user-images.githubusercontent.com/5045116/150095111-da33a434-1e1b-4db8-884b-6f124862f6e0.png)
The article teaches how to add monolithic flag with bazel, but I know how to add options with cmake tools. Thank you!

**Comment by sushreebarsa** [comment]
@lantianguhong 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity. Please feel free to reopen this ticket when new information becomes available. Thanks!
