### ISSUE TITLE
bazel compile errors

### ISSUE THREAD

**Issue by lantianguhong** [tensorflow/tensorflow#53814]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

OS Platform and Distribution: 
Linux centos 7.6
TensorFlow installed from source
TensorFlow version: 2.7.0
Python version: 3.9.6
Bazel version: 4.2.2
GCC/Compiler version (if compiling from source): 7.3.1

**Describe the problem**
Hello, I want to get libtensorflowlite.so with bazel, but I met a problem.  The llvm tar file is wrong, it can't be exacted.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build -c opt --cxxopt=-std=c++11 --config=mkl --config=numa --config=monolithic //tensorflow/lite:libtensorflowlite.so

**Any other info / logs**
Following is the error logs:
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/2325f363010d3176e96579628cbb96b8fca003a1.tar.gz, https://github.com/llvm/llvm-project/archive/2325f363010d3176e96579628cbb96b8fca003a1.tar.gz] to /home/cjh/.cache/bazel/_bazel_cjh/904c1e9488234a0ff2cc21c6287b3e45/external/llvm-raw/temp9533793750467514112/2325f363010d3176e96579628cbb96b8fca003a1.tar.gz: Premature EOF
I try to extract the temp9533793750467514112/2325f363010d3176e96579628cbb96b8fca003a1.tar.gz file, then a same problem occurs. The downloading file is wrong.
[cjh tensorflow-master]$ tar -xf llvm-project-2325f363010d3176e96579628cbb96b8fca003a1.tar.gz
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by sushreebarsa** [comment]
@lantianguhong 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sushreebarsa** [comment]
@lantianguhong Could you please refer the [build from source ](https://www.tensorflow.org/install/source) and check the tested build configurations ?Please let us know if it helps?Thanks!
