### ISSUE TITLE
Documentation For The New Version of Histogram on TensorBoard

### ISSUE THREAD

**Issue by TaihuaLi** [tensorflow/tensorflow#5381]
Hello~

I'm trying to interpret the new version of the histogram and it looks like the x-axis represents the value/bin, y-axis represent the step/time, and **z-axis represents the density since it is a continuous number. In addition, the color represents the standard deviation??** 

Is my interpretation correct? If so, I can help putting up the documentation for the new histogram tab.

Thanks!

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by aselle** [comment]
Thanks @TalhuaLI. FYI, @danmane, I assume documentation contributions are welcome.

**Comment by danmane** [comment]
Yes, documentation contributions would be welcome. As you hypothesize, the axes are bin value, time in steps, and density. The color is actually just a function of which run it is from, and how far back in time it is.

I label the axes x for value, y for density, and z for time (since the oldest steps seem to recede backwards into the distance)

**Comment by TaihuaLi** [comment]
@danmane  Hi Daniel. Thank you for the clarification! I want to confirm one more thing before start writing the description. Is it accurate to state the density the "probability density"? Thanks!

**Comment by danmane** [comment]
It's a normalized density. I wouldn't describe it as a probability density,
although I think calling it one would be justifiable.

**Comment by TaihuaLi** [comment]
@danmane here is a draft for the new histogram tab:
The histogram dashboard visualizes the distribution of a variable across epochs. x-, y- and z-aixs represent variable value, epoch time and normalized density, respectively.

**Comment by drcrook1** [comment]
Did this get documented somewhere?  I'm trying to understand the tensorboard outputs in detail; a link at the end of this to where the updated docs are would be great. :D

**Comment by dandelionmane** [comment]
Take a look here. https://www.tensorflow.org/versions/master/get_started/tensorboard_histograms

Or in the README for the dashboard, seen here: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/histograms/README.md
