### ISSUE TITLE
File system scheme 's3' not implemented

### ISSUE THREAD

**Issue by ktsitsi** [tensorflow/tensorflow#53818]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below):  tensorflow==2.7.0
- TensorFlow-IO version: tensorflow-io==0.23.1
- Python version: Python 3.8.12
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
`tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented`

**Describe the expected behavior**
`Should be able to connect the s3 filesystem.`

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): NA
- Briefly describe your candidate solution(if contributing):
 Rollback to `tensorflow-io==0.17` and `tensorflow==2.4.4` seems to resolve issue

**Standalone code to reproduce the issue**
```
from tensorflow.python.lib.io import file_io
print(file_io.stat('s3://bucketname/path/'))
```

```
from tensorflow.io import gfile
print(gfile.exists(`s3://bucketname/path/`))

```

**Other info / logs**  Similar older issue [here- 40302](https://github.com/tensorflow/tensorflow/issues/40302)

**Comment by mihaimaruseac** [comment]
#51583
