### ISSUE TITLE
Descriptions of `tf.RaggedTensor`'s methods '__xx__' are unclear

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53828]
Documentation bug for: https://www.tensorflow.org/api_docs/python/tf/RaggedTensor?hl=en#__and__

### Usage examples are unmatched
`tf.RaggedTensor` has a number of class methods, for example, `__abs__`, `__add__`, ... The usage examples for these methods are unmatched. For instance, the example code for `__add__` does not contain any **ragged tensors**, instead the examples are all normal tensors (of type `tf.Tensor`). 

The example code is:
```
a = tf.constant([True])
b = tf.constant([False])
tf.math.logical_and(a, b)
```
That is not expected for a `tf.RaggedTensor.__add__()` method.

**Comment by sushreebarsa** [comment]
@ArrowIntoTheSky 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), and provide more details on this?
Thanks!

**Comment by ArrowIntoTheSky** [comment]
@sushreebarsa Sorry for the late response. I have updated the description of the issue to include more details. Can you please look into this?

**Comment by gadagashwini** [comment]
Added a PR [#55222](https://github.com/tensorflow/tensorflow/pull/55222) for the fix.

**Comment by gadagashwini** [comment]
@ArrowIntoTheSky,
A RaggedTensor is a subclass of Tensor. If the method is not redefined, the parent class method is used. Hence the examples given are in dense tensor. Thanks!

**Comment by mihaimaruseac** [comment]
Reopening as https://github.com/tensorflow/tensorflow/issues/53828#issuecomment-1101038091 is a comment on #55222 which could be edited to incorporate the comment and add proper ragged tensor description

**Comment by sachinprasadhs** [comment]
Fix provided here https://github.com/tensorflow/tensorflow/commit/d0356e76730aee601a91f342d32a9671a487230a contains the example of Ragged Tensors, it is reflecting in the document as well here https://www.tensorflow.org/api_docs/python/tf/RaggedTensor?hl=en&version=nightly#__abs__
