### ISSUE TITLE
ImportError: cannot import name 'StructureCoder' from 'tensorflow.python.saved_model.nested_structure_coder'

### ISSUE THREAD

**Issue by nhenscheid** [tensorflow/tensorflow#53827]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 Enterprise
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary via pip
- TensorFlow version: 2.7.0 (have tried with several versions, 2.6.0, 2.6.2, 2.8.0
- Python version: 3.8.8
- Installed using virtualenv? pip? conda?: yes, venv + pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Using jupyter notebook,  `import tensorflow as tf`  results in the following error: 

ImportError: cannot import name 'StructureCoder' from 'tensorflow.python.saved_model.nested_structure_coder' (C:\path\to\folder)

I've tried various iterations of uninstalling and re-installing tensorflow, restarting kernels, etc.   Same error. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`import tensorflow as tf`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@nhenscheid ,
Can you please try to install  the latest stable tf v2.7 and let us know if still it is issue.Also please check this [link](https://github.com/tensorflow/tensorflow/commit/6c67b530dc40cdaf66ddf5d8f5d05c9e3046766f) once.Thanks!
