### ISSUE TITLE
`tf.sparse.sparse_dense_matmul` lack support for mixed bfloat16 and float32

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#53829]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
a = tf.random.uniform([207, 768], dtype=tf.bfloat16)
b = tf.random.uniform([768, 3072], dtype=tf.float32)

c = tf.linalg.matmul(a,b)
print(c.shape) # (207, 3072)
a_sp = tf.sparse.from_dense(a)
b_sp = tf.sparse.from_dense(b)
c_sp = tf.sparse.sparse_dense_matmul(a_sp, b) # InvalidArgumentError
```

**Describe the current behavior**
`tf.sparse.sparse_dense_matmul` cannot accept a tensor of type `bfloat16` and a tensor of type `float32`. However, `tf.linalg.matmul` do support this. 
For the above code snippet, the error message is:
```
InvalidArgumentError: cannot compute SparseTensorDenseMatMul as input #3(zero-based) was expected to be a bfloat16 tensor but is a float tensor [Op:SparseTensorDenseMatMul]
```

**Describe the expected behavior**
According to the document for `tf.sparse.sparse_dense_matmul`, it is equivalent to `tf.linalg.matmul` (but for sparse tensors), so `tf.sparse.sparse_dense_matmul` should also support such mixed precision inputs.

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky ! As per [document](https://www.tensorflow.org/api_docs/python/tf/sparse/sparse_dense_matmul#args), a_sp and b should be of same dtype. Attaching resolved [gist](https://colab.sandbox.google.com/gist/mohantym/e5713e436ba00f6f30f345e7f28cb747/github_53829.ipynb) for reference. Thank you!
