### ISSUE TITLE
Post Training Quantization doesn't work for tf.divide and tf.negative in TF 2.7

### ISSUE THREAD

**Issue by elad-c** [tensorflow/tensorflow#53837]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installation: from pip
- TensorFlow library: 2.7.0 (and 2.6.2 for reference)

### 2. Code

```
import tensorflow as tf
import numpy as np
from pathlib import Path

run_negative = True
if run_negative:
    model_file = '/tmp/debug_layers/neg_model_' + tf.__version__.replace('.', '_')
else:
    model_file = '/tmp/debug_layers/divide_2inputs_model_' + tf.__version__.replace('.', '_')

_in = tf.keras.layers.Input((4, 4))
out = tf.negative(_in) if run_negative else tf.divide(tf.keras.layers.ReLU()(_in), _in)
m = tf.keras.models.Model(inputs=_in, outputs=out)

_input = np.random.normal(size=(1, 4, 4))
output = m(_input)


def representative_dataset():
    for _ in range(100):
        d = np.random.normal(size=_input.shape).astype(np.float32)
        yield [d]


converter = tf.lite.TFLiteConverter.from_keras_model(m)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
tflite_quant_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_quant_model)
interpreter.allocate_tensors()
for t in interpreter.get_tensor_details():
    print(t['name'])

# Path(model_file + '.tflite').write_bytes(tflite_quant_model)
# m.save(model_file + '.h5')

```

### 3. Failure after conversion
Conversion passes succesfuly.
In TF 2.7 the converted network isn't quantized, but in TF 2.6.2 the network is quantized correctly.

output for TF 2.6.2:
```
input_1
tfl.quantize
tfl.dequantize
Identity1
tfl.quantize1
Identity
```

output for TF 2.7.0:
```
serving_default_input_1:0
PartitionedCall:0
```

The output of TF 2.7 is missing the Quantize-Dequantize nodes

**Comment by tilakrayal** [comment]
@elad-c ,
I was facing different error while trying to execute the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5c564ad20442e852738e6334130d3539/untitled196.ipynb).

**Comment by elad-c** [comment]
I've removed the last 2 lines which cuased the exception. I used them to save the models to disk and later open them with netron. It should work now

**Comment by elad-c** [comment]
for example, here's a Tensorflow model:
![image](https://user-images.githubusercontent.com/78862769/150987102-356984f8-1fd6-4744-8b5f-8503b7d94c1c.png)

This is the output of the converter with TensorFlow 2.6.2:
![image](https://user-images.githubusercontent.com/78862769/150987397-c616f33d-ad9e-4e00-ba56-e655fec3a82a.png)

and this is the converter's output with TensorFlow 2.7.0:
![image](https://user-images.githubusercontent.com/78862769/150987539-b599ae94-076c-41fd-8c9a-54d1739ee8e6.png)

**Comment by tilakrayal** [comment]
@elad-c ,
I was able to execute the mentioned code in colab.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/5a47376c85dcde718d39da37c44c669e/untitled200.ipynb).Can you please provide the colab gist where you are facing issue.It helps to debug the issue.Thanks!

**Comment by elad-c** [comment]
Editted the code to print the difference in outputs. The difference matches the plots of the networks I added in the previous comment.

**Comment by tilakrayal** [comment]
@elad-c ,
With the updated code also i was not able to get the output which you are mentioned.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/04c382d1732fb640f665a0378f96cc37/untitled209.ipynb).

**Comment by eladc4** [comment]
Looks like you got exactly the output I got (for TF 2.7.0)
```
serving_default_input_1:0
PartitionedCall:0
```
When I changed the gist to install TF 2.6.3, I got:
```
input_1
tfl.quantize
tfl.dequantize
Identity1
tfl.quantize1
Identity
```

Note the TF 2.6.3 quantized the network (tfl.qantize, tfl.dequantize), and TF 2.7.0 did not. That is the bug I reported in this issue

**Comment by elad-c** [comment]
Looks like you got exactly the output I got (for TF 2.7.0)
```
serving_default_input_1:0
PartitionedCall:0
```

When I changed the gist to install TF 2.6.3, I got:
```
input_1
tfl.quantize
tfl.dequantize
Identity1
tfl.quantize1
Identity

```

Note the TF 2.6.3 quantized the network (tfl.qantize, tfl.dequantize), and TF 2.7.0 did not. That is the bug I reported in this issue

**Comment by tilakrayal** [comment]
@Saduf2019 ,
I was able to reproduce the issue in tf v2.7 and nightly, where in v2.5 the code executed as expected.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/cf4465c60aaffff832199da58b0e555b/53837.ipynb).

**Comment by mohantym** [comment]
Hi @elad-c !I am able to get an integer quantized model by setting the **converter.inference_input_type** and **converter.inference_ouput_type** to tf.uint8. Attaching [gist](converter.inference_input_type) and relevant [thread ](https://www.tensorflow.org/lite/performance/post_training_integer_quant)for reference. Thanks!
