### ISSUE TITLE
`AutoGraph could not transform <function <lambda> at ...> ... Please report this to the TensorFlow team.`

### ISSUE THREAD

**Issue by samuela** [tensorflow/tensorflow#53831]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): script to reproduce below
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 5.10.91, NixOS, 21.11 (Porcupine)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): nixpkgs
- TensorFlow version (use command below): 2.7.0
- Python version: 3.9.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
Consider the following quick script:
```py
import tensorflow as tf
import tensorflow_datasets as tfds

print(tf.__version__)
print(tfds.__version__)
ds = tfds.load("mnist", split="train", as_supervised=True)
# Normalize 0-255 pixel values to 0.0-1.0
ds = ds.map(lambda image, label:
            (tf.cast(image, tf.float32) / 255.0, tf.one_hot(label, depth=10)))
```
based off of the example in the tensorflow-datasets docs [here](https://www.tensorflow.org/datasets/performances).

Running this code, I get the following:
```
[nix-shell:~/dev/research/lottery]$ AUTOGRAPH_VERBOSITY=10 python mnist_basic.py 
2.7.0
4.4.0+nightly
WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7f63dfc5e310> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Constant constructor takes either 0 or 2 positional arguments
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7f63dfc5e310> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Constant constructor takes either 0 or 2 positional arguments
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

Here's my shell.nix to reproduce the exact same setup:
```nix
let
  # Last updated: 1/17/2022. Check for new commits at status.nixos.org.
  pkgs = import (fetchTarball ("https://github.com/NixOS/nixpkgs/archive/bc59ba15b64d0a0ee1d1764f18b4f3480d2c3e5a.tar.gz")) { };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    python3
    python3Packages.flax
    python3Packages.ipython
    python3Packages.jax
    (python3Packages.jaxlib.override { cudaSupport = true; })
    python3Packages.matplotlib
    python3Packages.tensorflow
    python3Packages.tensorflow-datasets
    python3Packages.tqdm
    python3Packages.wandb
    yapf
  ];
}
```
**Describe the expected behavior**
The example code to run as expected without any warnings.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): n/a

**Standalone code to reproduce the issue**
See above.

**Other info / logs** 
My entire setup should be reproducible from the shell.nix file above. I'm running on an m5.large EC2 instance (x86_64-linux).

**Comment by sushreebarsa** [comment]
@samuela I tried to replicate the issue on colab using TF v2.7.0 , tf-nightly(2.9.0-dev20220119) and didn't face the error reported in tf-nightly. This issue seems to be fixed in tf-nightly .Could you please have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/f0e232d8b61478b16f25342bf549d91e/53831.ipynb#scrollTo=sOwjnRpTtE9R) and confirm the same ?Thank you!
