### ISSUE TITLE
Using learning-rate decay schedule with Keras (transfer learning with RESNET) generates unsupported operand error 'ExponentialDecay'

### ISSUE THREAD

**Issue by castorgit** [tensorflow/tensorflow#53833]
** System information **

- custom code
- Ubuntu 20.4
- TF installed from binary
- TF / Keras 2.7.0
- Python 3.8.12
- no GPU

** Current Behavior **

Training a Network to classify images, The network is based on RESNET152V2 + some new layers. We train last 19 layers of RESNET + the new added layers
(data is XRAY dataset from Kaggle)
Using a learning-rate decay schedule, the training crashes with an error 'unsupported operand error'

TypeError: unsupported operand type(s) for *: 'ExponentialDecay' and 'int'

** Standalone code to reproduce the issue **

[link to notebook](https://github.com/castorgit/AI-course-2021/blob/main/Group_Project/ResNet152V%20error.ipynb)

**Comment by mohantym** [comment]
Hi @castorgit ! 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by castorgit** [comment]
Thanks I'll do!
