### ISSUE TITLE
XLA docs for `Map` are unclear and incomplete

### ISSUE THREAD

**Issue by joelberkeley** [tensorflow/tensorflow#53845]
## URL(s) with the issue:

https://www.tensorflow.org/xla/operation_semantics#map

### Clear description

No. The section
```
The mapped function is an arbitrary computation with the restriction that it has N inputs of scalar type T and a single output with type S. The output has the same dimensions as the operands except that the element type T is replaced with S.
```
is not clear. Does it mean the output of the mapped function or the output of `Map`? I think it means the latter but it's not worded like that.

### Correct links

Yes

### Parameters defined

No. It's not clear what `dimensions` is for, and the argument `static_operands` is missing, though it it possibly alluded to in the definition of `computation` (see mention of `M` indices)

### Returns defined

Yes

### Raises listed and defined

As much as any other function in these docs.

### Usage example

No. An example would be amazing, should the devs feel like adding one.

### Request visuals, if applicable

n/a

### Submit a pull request?

No.

**Comment by tilakrayal** [comment]
@joelberkeley ,
Please feel free to submit a PR for the requested change or share the link where requested change is to be made

**Comment by joelberkeley** [comment]
@tilakrayal the link is included. I can't submit a PR because the problem is a lack of knowledge

**Comment by sachinprasadhs** [comment]
The sentence `The output has the same dimensions as the operands except that the element type T is replaced with S.` refers to output of Map function. 
Will it be fine for you if the sentence is changed to `The output of Map has the same dimensions as the operands except that the element type T is replaced with S.`

**Comment by joelberkeley** [comment]
sounds good, thanks. There are a few other things missing in the `Map` docs. Would be great if they were fixed too

**Comment by sachinprasadhs** [comment]
Could you please mention the issues you find in the doc or the missing details in the doc. Thanks

**Comment by joelberkeley** [comment]
I've mentioned them in the ticket description

**Comment by joelberkeley** [comment]
see "Parameters defined"
