### ISSUE TITLE
Is there a direct way to add Flex delegate to options in Android Tensorflow Lite 2.5 on C API ?

### ISSUE THREAD

**Issue by fatihkiralioglu** [tensorflow/tensorflow#53849]
I'm trying to use tflite 2.5 and  a tflite model converted from tensorflow model and I need to use flex delegate  in android on a native level C api.

There is a method in c header lite\c\c_api.h

TFL_CAPI_EXPORT extern void TfLiteInterpreterOptionsAddDelegate(
    TfLiteInterpreterOptions* options, TfLiteDelegate* delegate);

But: there is no api for creating TfLiteDelegate object.

Is it possible to use this TfLiteInterpreterOptionsAddDelegate method or  is this method just a prank?

I need an api for creating flex TfLiteDelegate  object and If such a method exitsts, where is it?

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this query?

**Comment by haozha111** [comment]
@karimnosseir could you help take a look? Thanks!

**Comment by karimnosseir** [comment]
@fatihkiralioglu 
You can use TfLiteInterpreterOptionsAddDelegate for sure. How to get TfLiteDelegate ? TfLite delegates expose C API functions to create TfLiteDelegate instances
example, 
[GPU](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/delegate.h#L153) 
[XNNPACK](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h#L50)
[Hexagon](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_delegate.h#L96)

For Flex Delegate, you don't need to add it as long as you're using TFLite which already built with TF Select support - see [here](https://www.tensorflow.org/lite/guide/ops_select#android_aar) for android build that links Flex.
We apply it automatically underneath.

Let me know if you have more questions.

Thanks

**Comment by karimnosseir** [comment]
Closing. Please feel free to reopen if you have other questions/issues.

Thanks
