### ISSUE TITLE
Shape issues in tf.keras.metrics.SparseTopKCategoricalAccuracy with multiple dimensions (previously #36985)

### ISSUE THREAD

**Issue by dfossl** [tensorflow/tensorflow#53842]
Might not be a bug could be my application. But if that is the case I feel the documentation should be edited as from reading those functionality seems to be similar.

When I run this:
```
target = tf.constant([[1,1,2,0,0,0],[1,1,2,2,0,0]])
predict = tf.constant([[[0,1,0],
                       [0,1,0],
                       [0,0,1],
                       [0,1,0],
                       [1,0,0],
                       [1,0,0]],
                       [[0,1,0],
                        [0,1,0],
                        [0,0,1],
                        [0,0,1],
                        [0,1,0],
                        [0,1,1000]]], dtype=tf.float32)


print(tf.shape(target))
print(tf.shape(predict))

mask = tf.math.logical_not(tf.math.equal(target, 0))

mask = tf.cast(mask, dtype=tf.int64)


loss = tf.keras.losses.SparseCategoricalCrossentropy(
        from_logits=True)
loss(target, predict, sample_weight=mask)
```
```
tf.Tensor([2 6], shape=(2,), dtype=int32)
tf.Tensor([2 6 3], shape=(3,), dtype=int32)
<tf.Tensor: shape=(), dtype=float32, numpy=0.3216761>
```
Works as expected. But when I try it for TopKAccuracy I get this:
```
m = tf.keras.metrics.SparseTopKCategoricalAccuracy(k=1)
m.update_state(target, predict, sample_weight=mask)
m.result.numpy()
InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 6 [Op:Squeeze]
```

In the documentation, both of them have the same definitions for y_true, y_pred and sample_weight. So not sure why the applications seem different here.

This may be my misuse, but not clear regardless. Any help would be appreciated.

**Comment by sushreebarsa** [comment]
@dfossl 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by dfossl** [comment]
Sounds good!
