### ISSUE TITLE
Loading optimizer weights on on TPUs

### ISSUE THREAD

**Issue by ttdd11** [tensorflow/tensorflow#53844]
**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): GCP
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.5
Python version: 3
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

Running many training sessions on TPUs using GCP (typically v2-32). Instead of using module.fit in keras, we use optimizer.apply_gradients.  Basically, we would like to be able to stop and restart training sessions by loading model weights and optimizer weights. The optimizer weights are really important because we would like to tune.

In keras, there are options to save optimizer weights using np.save(PATH_TO_OPT, optimizer.get_weights())

On GPUs we can re-load them using:
            def _loads_opt_weights():
               opt_weights = np.load(PATH_TO_OPT, allow_pickle=True)
               grad_vars = model.trainable_weights
               zero_grads = [tf.zeros_like(w) for w in grad_vars]
               optimizer.apply_gradients(zip(zero_grads, grad_vars))
               optimizer.set_weights(opt_weights)
            strategy.run(_loads_opt_weights)

For each GPU, but on the TPUs this doesn't work. We get an error of:

NotImplementedError: TPUStrategy.run(fn, ...) does not support pure eager execution. please make sure the function passed into strategy.run is a tf.function or strategy.run is called inside a tf.function if eager behavior is enabled

Turning eager mode off using tf.compat.v1.disable_eager_execution(): 
Results in InaccessibleTensorError: Operation 'LogicalAnd_30' has been marked as not fetchable. Typically this happens when it is defined in another function or code block. Use return values,explicit Python locals or TensorFlow collections to access it. When calling optimizer.set_weights(..)

How do we get this to load on distributed TPUs?

Do you want to contribute a PR? (yes/no): no
Briefly describe your candidate solution(if contributing): N/A

Standalone code to reproduce the issue: See above

**Comment by mohantym** [comment]
Hi @ttdd11 ! As this error "NotImplementedError: TPUStrategy.run(fn, ...) does not support pure eager execution. please make sure the function passed into strategy.run is a tf.function or strategy.run is called inside a tf.function if eager behavior is enabled" suggests , Can you try again by including the function inside tf.function like this ? Please provide a sample stand alone code to proceed further . Thank you!

```
@tf.function
def _loads_opt_weights():
  opt_weights = np.load(PATH_TO_OPT, allow_pickle=True)
  grad_vars = model.trainable_weights
  zero_grads = [tf.zeros_like(w) for w in grad_vars]
  optimizer.apply_gradients(zip(zero_grads, grad_vars))
  optimizer.set_weights(opt_weights)
strategy.run(_loads_opt_weights)
```

**Comment by ttdd11** [comment]
@mohantym thanks for the quick reply. I should have made the original post a bit more comprehensive. 

Here is standalone code to reproduce this (you have to put in a valid tpu name or set tpu to false if using gpus):

import os
import tensorflow as tf
import numpy as np
import os.path as osp
import pickle
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model

#build model
X, y = np.random.rand(100, 50), np.random.randint(2, size=100)
x = Input((50,))
out = Dense(1, activation='sigmoid')(x)
model = Model(x, out)

#build setup an optimizer and save the state
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
opt_path = 'opt_wights.npy'
grad_vars = model.trainable_weights
zero_grads = [tf.zeros_like(w) for w in grad_vars]
optimizer.apply_gradients(zip(zero_grads, grad_vars))
np.save(opt_path, optimizer.get_weights())

#do the same thing with a load, but in strategy scope
#get the strategy
bTPU = True
tpu_name = 'tpu-name'
if bTPU:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_name)  # TPU detection
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.TPUStrategy(tpu)
else:    
    gpus = tf.config.experimental.list_logical_devices("GPU")
    if len(gpus) > 1:
        strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
    elif len(gpus) == 1:
        strategy = tf.distribute.get_strategy()
    else:
        strategy = tf.distribute.get_strategy()

with strategy.scope():
    #build the model and optimizer again
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
    X, y = np.random.rand(100, 50), np.random.randint(2, size=100)
    x = tf.keras.layers.Input((50,))
    out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.Model(x, out)
    @tf.function	
    def _model_weight_setting():
        opt_weights = np.load(opt_path, allow_pickle=True)
        grad_vars = model.trainable_weights
        zero_grads = [tf.zeros_like(w) for w in grad_vars]
        optimizer.apply_gradients(zip(zero_grads, grad_vars))
        optimizer.set_weights(opt_weights)
    strategy.run(_model_weight_setting)


We have tried your solutions mentioned above (setting the @tf.function), and unfortunately this does not work on GPUs or TPUs. Without using the @tf.function, this script works on GPUs but not on TPUs.

The error log for both is very similar and is as follows when calling set_weights on the optimizer:

2022-01-21 16:20:03.947418: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
2022-01-21 16:20:04.430294: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.120.42.42:8470, 1 -> 10.120.42.43:8470, 2 -> 10.120.42.44:8470, 3 -> 10.120.42.45:8470}
2022-01-21 16:20:04.430470: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:43503}
2022-01-21 16:20:04.452118: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.120.42.42:8470, 1 -> 10.120.42.43:8470, 2 -> 10.120.42.44:8470, 3 -> 10.120.42.45:8470}
2022-01-21 16:20:04.452298: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:43503}
2022-01-21 16:20:04.454347: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://localhost:43503
Traceback (most recent call last):
  File "test_opt.py", line 56, in <module>
    strategy.run(_model_weight_setting)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 402, in run
    return self.extended.tpu_run(fn, args, kwargs, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 1428, in tpu_run
    return func(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 764, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
RuntimeError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/tpu_strategy.py:1448 replicated_fn  *
        result[0] = fn(*replica_args, **replica_kwargs)
    test_opt.py:55 _model_weight_setting  *
        optimizer.set_weights(opt_weights)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/adam.py:161 set_weights  **
        super(Adam, self).set_weights(weights)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:1148 set_weights
        param_values = backend.batch_get_value(params)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:3746 batch_get_value
        raise RuntimeError('Cannot get value inside Tensorflow graph function.')

    RuntimeError: Cannot get value inside Tensorflow graph function.

**Comment by mohantym** [comment]
Hi @ttdd11 ! There was a syntax error in earlier answer. Have attached  updated [gist](https://colab.sandbox.google.com/gist/mohantym/0bab7c440905503bbeabc1bd8c0d1769/github_53844.ipynb) for reference. Thank you!

**Comment by ttdd11** [comment]
@mohantym thanks for the reply. I'm a bit confused though.

The change I see is that the strategy.run call was moved into the @tf.function. Was there a syntax error in what I sent? Do you need me to correct something so move this along? 

Is this run call even executed? So if you print optimizer.get_weights() at the end of modified code will it print the loaded weights?

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you look at this issue? Attaching gist in [2.6](https://colab.sandbox.google.com/gist/mohantym/0dab4bb65ba2b800f1a5fbc74c2aefc7/github_53844.ipynb#scrollTo=aMnmqhS_PY6-), [2.7](https://colab.sandbox.google.com/gist/mohantym/0bab7c440905503bbeabc1bd8c0d1769/github_53844.ipynb#scrollTo=aMnmqhS_PY6-) and [2.8.rc1](https://colab.sandbox.google.com/gist/mohantym/2bd6c423f1e04598e469a46720b6fd9e/github_53844.ipynb#scrollTo=I1XCsNqyPfvD) for reference. Thanks!

**Comment by ttdd11** [comment]
@Saduf2019 is there anything I can do/tests I can run to help with this? Currently all of our GCP experiments are on hold.

**Comment by ttdd11** [comment]
@mohantym @Saduf2019 any ideas? Is loading optimizer weights not currently supported on distributed TPU training? Is there a short term solution that would allow this to happen with some code changes?

**Comment by jvishnuvardhan** [comment]
@ttdd11 Can you please share a standalone code that we can use to reproduce the issue? I tried your code and it throws different error as shown in [this gist](https://colab.research.google.com/gist/jvishnuvardhan/463f703c8d38554c85176b2ac2d6b9cb/github_53844.ipynb). May be share a *.py file or colab file. Thanks!

**Comment by ttdd11** [comment]
@jvishnuvardhan I believe that timeout is occurring because the tpu of "tpu-name" doesn't exist with your system. If you use no parameters in the cluster resolver, ie.  tpu = tf.distribute.cluster_resolver.TPUClusterResolver() it won't time out on that line.

**Comment by ttdd11** [comment]
@jvishnuvardhan Is this enough information to take a look? Would you like anything else? If you take a look at the gists from @mohantym from 22 days ago they have the correct TPUClusterResolver.

**Comment by ttdd11** [comment]
@jvishnuvardhan @Saduf2019 I'm really looking for any method at this point to load the optimizer state on tpus. Is there a different model format that I can use instead? To me it seems like there must be a work around, otherwise no model tuning would be possible on TPUs.

**Comment by ttdd11** [comment]
@jvishnuvardhan @Saduf2019 here is a standalone file if that helps. Is there no workaround to this? 

[standaalone_load_opt_state.txt](https://github.com/tensorflow/tensorflow/files/8147647/standaalone_load_opt_state.txt)

In summary, we just want to re-start training where I was. Same model and optimizer state. For us this is important to tune models, but also restart a training session if the GCP times out. I hope this helps understand where we are coming from. Please let me know if I can help test anything.

**Comment by ttdd11** [comment]
@gadagashwini do you need anything from us in order to escalate this?

**Comment by fig666** [comment]
device and focus isnt being registered properly due to disruptive intergrating users on the ios operating system

**Comment by ttdd11** [comment]
@fig666 @gadagashwini I'm not sure if I follow the last point. 

My questions:
1.  Anything I can do to help here?
2. Are there any other solutions to this that would allow us to load optimizer and model weights via a different mechanism so we can tune some models? 
3. Is something that is being investigated in general?

**Comment by ttdd11** [comment]
@Saduf2019 @gadagashwini @jvishnuvardhan I'm unsure what other options we have here. We are coming up on three months and the assignee has not yet responded. It effectively means that we can't run GCP experiments.

**Comment by jszaday** [comment]
@ttdd11 I retooled your example code to run on the TPU with a few changes; if this is still an issue, I hope this helps! Please see below:

```python
import numpy as np
import tensorflow as tf

# build the initial model
x = tf.keras.layers.Input((50,))
out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(x, out)

# build setup an optimizer and save the state
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
opt_path = 'opt_wights.npy'
grad_vars = model.trainable_weights
zero_grads = [tf.zeros_like(w) for w in grad_vars]
optimizer.apply_gradients(zip(zero_grads, grad_vars))

opt_weights = optimizer.get_weights()
np.save(opt_path, [np.int32(opt_weights[0])] + opt_weights[1:])

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver('')
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.TPUStrategy(cluster_resolver)

# build the model and optimizer again
with strategy.scope():
  x = tf.keras.layers.Input((50,))
  out = tf.keras.layers.Dense(1, activation='sigmoid')(x)
  optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
  model = tf.keras.Model(x, out)
  model.compile(optimizer=optimizer)

# set up the weights for the model
with strategy.scope():
  grad_vars = model.trainable_weights
  zero_grads = [tf.zeros_like(w) for w in grad_vars]
  opt_weights = np.load(opt_path, allow_pickle=True)
  opt_weights = [tf.constant(w) for w in opt_weights]

@tf.function
def _model_weight_setting():
  optimizer.apply_gradients(zip(zero_grads, grad_vars))

# apply the gradients to the model
strategy.run(_model_weight_setting)

# update the weights of the model
with strategy.scope():
  optimizer.set_weights(opt_weights)
```

**Comment by ttdd11** [comment]
@jszaday thanks for the reply, sorry it took a little while to test this.

In practice, though it seems like it's loading (no crash, no exceptions), when I load the optimizer state with the code provided, the model loss get far worse quickly, than if the optimizer is not loaded at all. I'm not sure what is causing this, however this solution unfortunately does not seem to accomplish the goal.

**Comment by ttdd11** [comment]
@jszaday is there anything else I can do to test this? Our current challenging is that the state of the optimizer is important if we want to tune models, however without being able to load it, we end up re-training which is very time consuming and compute heavy. Any help would be greatly appreciated.

**Comment by jszaday** [comment]
Previously, you mentioned you tested this method on GPUs. Does the provided code also work on GPUs? If not, what are the key differences between your working GPU code and the provided code?

**Comment by ttdd11** [comment]
The testing I did was on GPUs for this particular test (where the loss diverged).

Perhaps I may have been incorrect in my description of "working" on GPUs. A better assessment is that it didn't throw an error. I didn't search too much past that because practically, we train these models on TPUs.

**Comment by jszaday** [comment]
One last question—typically, when we want to save/load the optimizer's state, we'd also save/load the rest of the model's state (e.g., its trainable variables). This procedure is outlined [here](https://www.tensorflow.org/guide/keras/save_and_serialize). Is it possible to save/load the entire model in your use-case?

**Comment by ttdd11** [comment]
@jszaday for sure, the model and the optimizer state are saved/loaded at the same time. Now the different I see in that example is that model.fit isn't being called, but creating gradients using tape.gradient and applying them using optimizer.apply_gradients. Is there a way for me to get the optimizer object from the model after its loaded?

**Comment by jszaday** [comment]
Hmm, in general, if one passes an optimizer object via `Model.compile`, it should be the optimizer that the model uses.

That's to say, in my code snippet above: `id(optimizer) == id(model.optimizer)`

**Comment by ttdd11** [comment]
Given that those optimizers are the same,  would it make sense to load the model via load_model then optimizer = model.optimizer and then use apply_gradients?

**Comment by jszaday** [comment]
That makes sense; you can try it.

**Comment by ttdd11** [comment]
@jszaday sorry just edited the comment, will circle back.

**Comment by ttdd11** [comment]
I have models saved as .h5 format, before I go down this road I'm assuming we need to use a model = model.load("path to model") and not model.load_weights, is this correct?

**Comment by jszaday** [comment]
Correct, like:

```
# Calling `save('my_model.h5')` creates a h5 file `my_model.h5`.
model.save("my_h5_model.h5")
# It can be used to reconstruct the model identically.
reconstructed_model = tf.keras.models.load_model("my_h5_model.h5")
```

**Comment by ttdd11** [comment]
@jszaday besides the loss not diverging, what would be a good way to test whether the model and state are being used? It is loading on GPUS.

**Comment by jszaday** [comment]
Unsure, `tf.print` and the like are incompatible with saved models, so one usually has to check the values of intermediate/output tensors by returning them. Did you end up finding out whether loading/saving the model improved your results?

**Comment by zout3** [comment]
I'm having a similar problem where I want to save the optimizer state. The "applying gradient" method and get_weights() and set_weights() worked fine under CPU but got into trouble in distributed computing under TPU.

I found a work around by still applying the gradient method. Soing do will raise an error, but afterwards the weights can be successfully set, so I use the try and except to handle the error. My codes look like this:

# First build model, fit model and save the weights
`with STRATEGY.scope():
    model = build_model()
    opt = tfa.optimizers.RectifiedAdam(0.01)
    opt = tfa.optimizers.Lookahead(opt)
    model.compile(opt, loss="mean_absolute_error")
model.fit(ds, epochs=1)
opt_wgts = model.optimizer.get_weights()
print(opt_wgts)
with open('opt_wgts.pickle', 'wb') as file:
    pickle.dump(opt_wgts, file)`

# Resume training and load the optimizer weights

`with open('opt_wgts.pickle', 'rb') as file:
    opt_wgts_new = pickle.load(file)
with STRATEGY.scope():
    model_new = build_model()
    opt = tfa.optimizers.RectifiedAdam(0.01)
    opt = tfa.optimizers.Lookahead(opt)
    model_new.compile(opt, loss="mean_absolute_error")

grad_vars = model_new.trainable_weights
@tf.function
def func(grad_vars):
    return [tf.zeros_like(w) for w in grad_vars]
zero_grads = STRATEGY.run(func, args=(grad_vars,))`

try:
    model_new.optimizer.apply_gradients(zip(zero_grads, grad_vars))  # this will raise an error but allows me to set weights
except:
    model_new.optimizer.set_weights(opt_wgts_new)

print(model_new.optimizer.get_weights())   # check the weights are the same as the saved ones
