### ISSUE TITLE
no interface provided to set 'max_num_snapshots' when profile memory

### ISSUE THREAD

**Issue by tomusfri** [tensorflow/tensorflow#53852]
When using the tensorflow profiler for memory footprint analysis, the profiler keeps up to 1000 snapshots. This default value limits us to more detailed memory analysis. I would like to know why this default value is set to 1000.

The relevant code is as follows：
https://github.com/tensorflow/tensorflow/blob/f0df570aa30f962f58aedf6d111e017c7345431b/tensorflow/core/profiler/convert/xplane_to_memory_profile.h#L30
https://github.com/tensorflow/tensorflow/blob/f0df570aa30f962f58aedf6d111e017c7345431b/tensorflow/core/profiler/convert/xplane_to_memory_profile.cc#L550

TF version：TF 2.7
How to reproduce: Strictly speaking, this is not a bug.

Looking forward to reply.

**Comment by mohantym** [comment]
Hi @tomusfri ! 
Could you please update the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!
