### ISSUE TITLE
Expose half_pixel_center or anti-aliasing parameter in the keras resizing layer.

### ISSUE THREAD

**Issue by bayesian-mind** [tensorflow/tensorflow#53856]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.6
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The feature that I am proposing is basically a fix for the current resizing keras layer which sets the `half_pixel_center` to true by default which causes problem on nnapi (android) based platforms and also on snapdragon based platforms. There are 2 possible solution to this problem - 

1. You expose the parameters `antialias` or `half_pixel_center` via the keras Resizing layer and let the user explicitly set either of the 2 properties. Better would be to expose `antialias` which can be defaulted to `None` or `True` since resizing is used mostly in later layers and not for downsampling it should be fine.
2.  Add an automated check within the resize base function to check if the half_pixel_center is actually needed. From my understanding when you are resizing just check if the (inputsize -1)/(outputsize-1) when downsampling or vice versa when upsampling, is fractional or int. If fractional set half_pixel_center to true else set it to false. 

**Will this change the current api? How?**
Yes this will change the current api by either exposing certain optional parameters or by adding an automated check.

**Who will benefit with this feature?**
Everyone running their NN on somekind of DSP.

**Any Other info.**

**Comment by sushreebarsa** [comment]
@bayesian-mind 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
