### ISSUE TITLE
normalization should be done using moving averages?

### ISSUE THREAD

**Issue by 1knueller** [tensorflow/tensorflow#53858]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/structured_data/time_series#normalize_the_data

## Description of issue (what needs changing):

Hello this is a small feature request. In the Time series tutorial at the normalization section in the 3rd paragraph there is a remark saying:
"and that this normalization should be done using moving averages."

I am very curious on how a moving average would be used here. 
Should  a "simple moving average" for the whole dataset be computed and then on that new "dataset-MA" just use the normalization technique that is described in the tutorial?

The feature I am requesting is something like a remark on how this would be done or maybe a pointer to different tutorial if one exists or some further references/research users could look into.

**Comment by sushreebarsa** [comment]
@t0b4cc0 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!

**Comment by t0b4cc0** [comment]
I created the issue with the relevant parts of that template.

**Comment by t0b4cc0** [comment]
did the tutorial just mean to use something like pandas.rolling function to create the data?

**Comment by sachinprasadhs** [comment]
The tutorial uses the simple average to normalize the data, the intention of the tutorial is to create a Time series forecasting using Tensorflow. 
If you feel any of the description is irrelevant/inappropriate feel free to create a PR. Thanks!
