### ISSUE TITLE
Node is not unique when frozen graph using convert_variables_to_constants_v2()

### ISSUE THREAD

**Issue by posEdgeOfLife** [tensorflow/tensorflow#53866]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Windows 10/11 and Ubutun 20
- TensorFlow installed from pip
- tf 2.5.0/2.7.0/2.9nightly
- Python 3.6.9/3.8
- NA
- NA:
- NA:

**Describe the current behavior**

From google/deeplab2/export_model.py, add the following line:
```
  signatures = module.__call__.get_concrete_function(module.get_input_spec())
  #following is the added code.
  frozen_func = convert_variables_to_constants_v2(signatures)
```
This issue also appears in tf2onnx tool which uses this convert_variables_to_constants_v2() call.

Full command to run the above script.
```
python export.py
--experiment_option_path
"./configs/cityscapes/axial_deeplab/max_deeplab_l_backbone_os16.textproto"
--checkpoint_path
"C:/develop/max_deeplab_l_backbone_os16_axial_deeplab_cityscapes_trainfine_saved_model/"
```

- Do you want to contribute a PR? (yes/no):
no. I have no profound knowledge in this conversion, and it may take too much time for me to look into it.

**Standalone code to reproduce the issue**
[export.py](https://github.com/google-research/deeplab2/blob/main/export_model.py).
Can get the save model from the following page, I used MaX-DeepLab-L-Backbone
https://github.com/google-research/deeplab2/blob/main/g3doc/projects/axial_deeplab.md

**Other info / logs**

> 
> 2022-01-21 17:28:22.472844: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
> 2022-01-21 17:28:22.473118: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> 2022-01-21 17:28:33.104143: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> I0121 17:28:33.102456 21356 deeplab.py:57] Synchronized Batchnorm is used.
> I0121 17:28:33.110966 21356 axial_resnet_instances.py:144] Axial-ResNet final config: {'num_blocks': [3, 6, 3, 3], 'backbone_layer_multiplier': 1.0, 'width_multiplier': 1.0, 'stem_width_multiplier': 1.0, 'output_stride': 16, 'classification_mode': True, 'backbone_type': 'wider_resnet', 'use_axial_beyond_stride': 16, 'backbone_use_transformer_beyond_stride': 0, 'extra_decoder_use_transformer_beyond_stride': 16, 'backbone_decoder_num_stacks': 1, 'backbone_decoder_blocks_per_stage': 1, 'extra_decoder_num_stacks': 1, 'extra_decoder_blocks_per_stage': 3, 'max_num_mask_slots': 128, 'num_mask_slots': 128, 'memory_channels': 512, 'base_transformer_expansion': 2.0, 'global_feed_forward_network_channels': 512, 'high_resolution_output_stride': 4, 'activation': 'relu', 'block_group_config': {'attention_bottleneck_expansion': 4, 'drop_path_keep_prob': 1.0, 'drop_path_beyond_stride': 4, 'drop_path_schedule': 'linear', 'positional_encoding_type': None, 'use_global_beyond_stride': 0, 'use_sac_beyond_stride': -1, 'use_squeeze_and_excite': False, 'conv_use_recompute_grad': False, 'axial_use_recompute_grad': True, 'recompute_within_stride': 0, 'transformer_use_recompute_grad': False, 'axial_layer_config': {'query_shape': (129, 129), 'key_expansion': 2, 'value_expansion': 4, 'memory_flange': (32, 32), 'double_global_attention': False, 'num_heads': 8, 'use_query_rpe_similarity': True, 'use_key_rpe_similarity': True, 'use_content_similarity': True, 'retrieve_value_rpe': True, 'retrieve_value_content': True, 'initialization_std_for_query_key_rpe': 1.0, 'initialization_std_for_value_rpe': 1.0, 'self_attention_activation': 'softmax'}, 'dual_path_transformer_layer_config': {'num_heads': 8, 'bottleneck_expansion': 2, 'key_expansion': 1, 'value_expansion': 2, 'feed_forward_network_channels': 2048, 'use_memory_self_attention': True, 'use_pixel2memory_feedback_attention': True, 'transformer_activation': 'softmax'}}, 'bn_layer': functools.partial(<class 'keras.layers.normalization.batch_normalization.SyncBatchNormalization'>, momentum=0.9900000095367432, epsilon=0.0010000000474974513), 'conv_kernel_weight_decay': 0.0}
> I0121 17:28:33.613099 21356 deeplab.py:96] Setting pooling size to (65, 129)
> I0121 17:28:36.232671 21356 api.py:446] Eval with scales ListWrapper([1.0])
> I0121 17:28:39.102459 21356 api.py:446] Eval scale 1.0; setting pooling size to [None, None]
> I0121 17:28:58.836912 21356 api.py:446] Eval with scales ListWrapper([1.0])
> I0121 17:28:58.883746 21356 api.py:446] Eval scale 1.0; setting pooling size to [None, None]
> 2022-01-21 17:40:38.838944: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
> 2022-01-21 17:40:38.847874: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
> 2022-01-21 17:40:38.883561: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> 2022-01-21 17:40:40.300834: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1137] Optimization results for grappler item: graph_to_optimize
>   function_optimizer: Graph size after: 4654 nodes (1206), 6100 edges (1886), time = 239.541ms.
>   function_optimizer: function_optimizer did nothing. time = 2.73ms.
> Traceback (most recent call last):
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\importer.py", line 497, in _import_graph_def_internal
>     graph._c_graph, serialized, options)  # pylint: disable=protected-access
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\absl\app.py", line 303, in run
>     _run_main(main, args)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\absl\app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "C:/develop/deeplab2/export_model.py", line 158, in main
>     frozen_func = convert_variables_to_constants_v2(signatures)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 1154, in convert_variables_to_constants_v2
>     converted_input_indices)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\convert_to_constants.py", line 1080, in _construct_concrete_function
>     new_output_names)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 650, in function_from_graph_def
>     wrapped_import = wrap_function(_imports_graph_def, [])
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 628, in wrap_function
>     collections={}),
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 87, in __call__
>     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 93, in wrapped
>     return fn(*args, **kwargs)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\eager\wrap_function.py", line 648, in _imports_graph_def
>     importer.import_graph_def(graph_def, name="")
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\util\deprecation.py", line 549, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\importer.py", line 405, in import_graph_def
>     producer_op_list=producer_op_list)
>   File "C:\Users\tfan\.conda\envs\XNNC\lib\site-packages\tensorflow\python\framework\importer.py", line 501, in _import_graph_def_internal
>     raise ValueError(str(e))
> ValueError: Node 'DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique

**Comment by sushreebarsa** [comment]
@posEdgeOfLife 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by posEdgeOfLife** [comment]
> 

hi, excuse me  for asking, i have already provided the code from deeplab2 and the code I added, but I don't have any snippet can run  independently.

**Comment by sushreebarsa** [comment]
@posEdgeOfLife Thank you for the update! 
Could you please try on the latest TF v2.7.0 ,tf-nightly and let us know the outcome? Thanks!

**Comment by posEdgeOfLife** [comment]
> @posEdgeOfLife Thank you for the update! Could you please try on the latest TF v2.7.0 ,tf-nightly and let us know the outcome? Thanks!

actually I just tested a code snippet that would run independently as long as you have the model downloaded.
 ```
 model = tf.keras.models.load_model(r"C:/develop/max_deeplab_l_backbone_os16_axial_deeplab_cityscapes_trainfine_saved_model/")
  # module = DeepLabModule(
  #     config, _FLAGS_CKPT_PATH.value, _FLAGS_MERGE_WITH_TF_OP.value)


  signatures = model.signatures['serving_default']
  frozen_func = convert_variables_to_constants_v2(signatures)
```

**Comment by posEdgeOfLife** [comment]
> @posEdgeOfLife Thank you for the update! Could you please try on the latest TF v2.7.0 ,tf-nightly and let us know the outcome? Thanks!

I think I tried 2.7 and there were some numpy errors related to [some numpy array ](https://github.com/tensorflow/models/issues/9706), which is the reason I downgraded to 2.5.0

**Comment by posEdgeOfLife** [comment]
> @posEdgeOfLife Thank you for the update! Could you please try on the latest TF v2.7.0 ,tf-nightly and let us know the outcome? Thanks!
ignore my previous msg.
tried with 2.7 and same error.
new error log on 2.7:

  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'StatefulPartitionedCall/DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "export_model.py", line 177, in <module>
    app.run(main)
  File "/home/tfan/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/tfan/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "export_model.py", line 158, in main
    frozen_func = convert_variables_to_constants_v2(signatures)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1083, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1008, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 650, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 621, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 87, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 93, in wrapped
    return fn(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 648, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 535, in new_func
    return func(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'StatefulPartitionedCall/DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique
```

**Comment by posEdgeOfLife** [comment]
tried it on 2.9 nightly which returns same error. Logs:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_model.py", line 177, in <module>
    app.run(main)
  File "/home/tfan/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/tfan/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "export_model.py", line 158, in main
    frozen_func = convert_variables_to_constants_v2(signatures)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1151, in convert_variables_to_constants_v2
    return _construct_concrete_function(func, output_graph_def,
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/convert_to_constants.py", line 1076, in _construct_concrete_function
    new_func = wrap_function.function_from_graph_def(output_graph_def,
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 655, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 619, in wrap_function
    func_graph.func_graph_from_py_func(
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1161, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 83, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 89, in wrapped
    return fn(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/eager/wrap_function.py", line 649, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 548, in new_func
    return func(*args, **kwargs)
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 403, in import_graph_def
    return _import_graph_def_internal(
  File "/home/tfan/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 504, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'StatefulPartitionedCall/DeepLab/max_deeplab_l_backbone/stage4/block2/attention/height_axis/query_rpe/Gather/axis' is not unique
tfan@PC-TFAN-DT:/mnt/c/develop/deeplab2$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.__version__)
2.9.0-dev20220121
```

**Comment by sushreebarsa** [comment]
@posEdgeOfLife Could you please post this issue in [models repo](https://github.com/tensorflow/models/issues) to get the right help there ?Thanks!
