### ISSUE TITLE
Installing tensorflow with pip

### ISSUE THREAD

**Issue by pure-rgb** [tensorflow/tensorflow#53869]
**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

When installing tensorflow on windows, after `pip install tensorflow`, it further needs to install Cuda and cudann and also needs to add their paths to windows environmental utility.  I'm not sure why we need to face this hassle whereas, in pytorch, we don't see such things. 

**Will this change the current api? How?** dunno. 

**Who will benefit from this feature?** all of the painful souls who use tensorflow

**Any Other info.**

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this feature request?

**Comment by aryannewyork** [comment]
Hey I want to contribute to this, can you please guide me through

**Comment by Suzan009** [comment]
@mihaimaruseac @sachinprasadhs any idea?

**Comment by gadagashwini** [comment]
@Suzan009,
Hi Thanks for reporting this issue.
Can you share commands/steps that you get after running  `pip install tensorflow`. 
Thanks!

**Comment by Suzan009** [comment]
Any update? Why it's always required for end-user to update path config manually for installing TensorFlow with GPU support? Can't it be made automatic, like in a torch?

**Comment by Suzan009** [comment]
Any updated? Is it even an issue or I will close it; no pressure?

**Comment by pure-rgb** [comment]
One of the tricky approach for the API maintainers is that, if a user open an issue and you know your limits, them keep silence for long time. As soon as the user lost interest or move forward with other solutions (pytorch), - close the issue. F*k it.

**Comment by mihaimaruseac** [comment]
Funny that you say this, when the issue has been under discussion in SIG Build since at least 2 months ago ([bit.ly/tf-sig-build-notes](http://bit.ly/tf-sig-build-notes))
