### ISSUE TITLE
Tensorflow Dataset: Image too large

### ISSUE THREAD

**Issue by riteshahlawat** [tensorflow/tensorflow#53865]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary):  **binary**
- TensorFlow version (use command below): **v2.7.0-rc1-69-gc256c071bb2 2.7.0**
- Python version: **3.8.9**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **11.2 / 8.1**
- GPU model and memory: **Tested on RTX 3080 10 GB & V100 16 GB**

**Describe the current behavior**

Hello, I am creating a TF Dataset from Gigapixel WSIs (whole slide images). The dimensions of them are 51968 x 37632 x 1 (grayscale) yielding a size of 1955659776. 

```python
WSI_SHAPE = (51968, 37632)
train_ds = keras.preprocessing.image_dataset_from_directory(wsi_dataset_path, validation_split=0.2, color_mode='grayscale',
                                                                labels=None, shuffle=True, subset='training', image_size=WSI_SHAPE,
                                                                batch_size=32, seed=42)

val_ds = keras.preprocessing.image_dataset_from_directory(wsi_dataset_path, validation_split=0.2, color_mode='grayscale',
                                                              labels=None, shuffle=True, subset='validation', image_size=WSI_SHAPE,
                                                              batch_size=32, seed=42)

for image in train_ds.take(1):
    print('Image input shape:', image.input_shape)
```

This gives an error:
```
2022-01-21 20:30:25.456609: E tensorflow/core/lib/jpeg/jpeg_mem.cc:183] Image too large: 1955659776
```

**Describe the expected behavior**

Expected behavior is for tensorflow to load in the large images into the Dataset.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): **No**
- Briefly describe your candidate solution(if contributing): **N/A**

**Other info / logs**

I looked into the location of this error: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/jpeg/jpeg_mem.cc#L182-L186
```cpp
if (total_size >= (1LL << 29)) {
  LOG(ERROR) << "Image too large: " << total_size;
  jpeg_destroy_decompress(&cinfo);
  return nullptr;
}
```

The size of my images (1955659776) is 3.6 times larger than the maximum size (536870912). I'm curious as to why it is this specifically this number as the maximum size since I have access to 256 GB of memory. For large images like this would I have to create the dataset manually instead of `image_dataset_from_directory`?

**Comment by sushreebarsa** [comment]
@riteshahlawat 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by riteshahlawat** [comment]
@sushreebarsa Filled!

**Comment by sushreebarsa** [comment]
@riteshahlawat 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by riteshahlawat** [comment]
> @riteshahlawat In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

I have already provided a code snippet that loads in a dataset of images with an extremely large resolution, uploading the dataset would be an issue but any high-resolution image over size 536870912 (width x height x channels) would work.

**Comment by sushreebarsa** [comment]
@riteshahlawat 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!
