### ISSUE TITLE
Generated debug info can not be read by TensorBoard under distributed training environment

### ISSUE THREAD

**Issue by pwrliang** [tensorflow/tensorflow#53870]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, a distributed training example
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Train on CentOS 7; Read the dump on Macbook M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Does not apply
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): v2.8.0-rc0-24-g671aa8d 2.8.0-rc0
- Python version: 3.8.3
- Bazel version (if compiling from source): bazel 4.2.2
- GCC/Compiler version (if compiling from source): GCC 9.3.0
- CUDA/cuDNN version: Does not apply
- GPU model and memory: Does not apply

**Describe the current behavior**

The dump files can not be read by TensorBoard under the distributed training environment

**Describe the expected behavior**

It can be read from TensorBoard.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
- Run the following code and generate the dump files:

```python
import tensorflow as tf
import tensorflow_datasets as tfds
import os
import json
import sys
import time
from absl import logging

num_epochs = 1
batch_size_per_replica = 64
learning_rate = 0.001

worker_idx = int(sys.argv[1])
num_workers = 2
os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["10.3.1.101:20000", "10.3.1.102:20000"]
    },
    'task': {'type': 'worker', 'index': worker_idx}
})

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'
os.environ['TF_CPP_MIN_VLOG_LEVEL'] = '3'

logging.set_verbosity(logging.DEBUG)

################ HERE ######################
tf.debugging.experimental.enable_dump_debug_info('/home/geng.161/my-tfdbg-dumps', tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1)
################ HERE ######################

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
batch_size = batch_size_per_replica * num_workers

def resize(image, label):
    image = tf.image.resize(image, [224, 224]) / 255.0
    return image, label

dataset = tfds.load("cats_vs_dogs", split=tfds.Split.TRAIN, as_supervised=True)
dataset = dataset.map(resize).shuffle(1024).batch(batch_size)

with strategy.scope():
    model = tf.keras.applications.MobileNetV2(weights=None, classes=2)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss=tf.keras.losses.sparse_categorical_crossentropy,
        metrics=[tf.keras.metrics.sparse_categorical_accuracy]
    )

begin = time.time()
model.fit(dataset, epochs=num_epochs)
end = time.time()
print("Train Time: %s" % (end - begin))
```

- Copy the dumps on my laptop, and use TensorFlow to read the dumps.
```bash
tensorboard --logdir ~/Downloads/my-tfdbg-dumps
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.8.0 at http://localhost:6006/ (Press CTRL+C to quit)
```

But I got nothing on the TensorBoard,
![image](https://user-images.githubusercontent.com/14839342/150647620-6b9923c6-d0c2-49d6-a507-925929a59f28.png)

I've posted this issue on the TensorBoard repo, but they think this is a bug stem from TensorFlow since the dumps can be read without the distributed strategy. They suggested that I should post an issue on the TensorFlow repo.

Refer: https://github.com/tensorflow/tensorboard/issues/5518

**Comment by sushreebarsa** [comment]
@pwrliang Could you please post this issue on [TensorBoard repo](https://github.com/tensorflow/tensorboard/issues) to get the right help there?Thanks!

**Comment by pwrliang** [comment]
> @pwrliang Could you please post this issue on [TensorBoard repo](https://github.com/tensorflow/tensorboard/issues) to get the right help there?Thanks!

@sushreebarsa Hi, I opened a issue on TensorBoard, they said this issue only happened when under the distributed training settings, so they suggested me open the issue  on TensorFlow repo. Please read my issue throughout, thanks

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
