### ISSUE TITLE
Bug report, easy 1 line fix.

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#539]
filename: tensorflow/python/framework/ops.py

def set_shapes_for_outputs(op):
  """Uses the registered shape functions to set the shapes for op's outputs."""
  try: 
    shape_func = _shape_registry.lookup(op.type)
  except LookupError:
    try: 
      shape_func = _default_shape_function_registry.lookup(op.type)
    except LookupError:
      raise RuntimeError("No shape function registered for standard op: %s"
                         % op.type)
  shapes = shape_func(op)
  if len(op.outputs) != len(shapes):
    raise RuntimeError(
        "Shape function for op %s returned %g shapes but expecting %g" %
        (op, len(op.outputs), len(shapes)))
  for output, s in zip(op.outputs, shapes):
    output.set_shape(s)

The call of "Shape function for op %s returned %g shapes but expecting %g" %" is reversed, should be (op, len(op.shapes), len(outputs)); (i swapped the shapes and outputs) ... took me awhile to debug an unrelated bug because i was getting the wrong debug message ;)

**Comment by reynoldscem** [comment]
Submit a pull request?
