### ISSUE TITLE
[tensorflow/examples] TensorFlow Lite Example for Android: Insecure protocols error during build

### ISSUE THREAD

**Issue by maximecharriere** [tensorflow/tensorflow#53907]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 Entreprise 21H1**
- Android Studio Version: **Android Studio Arctic Fox 2020.3.1 Patch 4**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Any android device**
- tensorflow/examples Repo Version: [**Commit eb925e4**](https://github.com/tensorflow/examples/tree/eb925e4)
- TensorFlow version: **tensorflow-lite:2.5.0**

**Describe the problem**
When I build any Android example, I get this error :
```
> Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'ossrh-snapshot(http://oss.sonatype.org/content/repositories/snapshots)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.3.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
```

We need to set `allowInsecureProtocol` to `true` in the build.gradle for the example to compile. 
```
maven {
    name 'ossrh-snapshot'
    url 'http://oss.sonatype.org/content/repositories/snapshots'
    allowInsecureProtocol = true
    }
```
This happens on this example and all other android examples: 
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android  

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Get the tensorflow/examples repo with  `git clone https://github.com/tensorflow/examples`  
1. Open `examples\lite\examples\object_detection\android` in Android Studio  
1. Run `Build > Rebuild Project`

**Comment by sachinprasadhs** [comment]
This error seems to be on the gradle side, in the above example when the insecure url is used from the `gradle` file with `http:// `this exception is thrown, as per the error suggestion,  you need to set `allowInsecureProtocol` to `true` to build. 
This won't be the issue when you build the example with secured url starting with `https:// `. Thanks!

**Comment by maximecharriere** [comment]
Do you want me to make a PR with https for each example?
