### ISSUE TITLE
iterating over `tf.Tensor` is not allowed

### ISSUE THREAD

**Issue by saylideshmukh** [tensorflow/tensorflow#53910]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I have a dictionary that I build by accessing only the channel dimensions of an output layer of a convolutional neural network (it has a shape (100,24,24,6) )
Therefore keys of this dictionary are tuples of tensor shape (6, ) . I want to map these keys to the input of the next layer using the tf.map_fn(). However, i am incapable of doing it because the keys of my dictionary are of type tensor and i cannot iterate over them .
Looking for some help. Thank you.

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by devnev39** [comment]
#53911

**Comment by devnev39** [comment]
Issue #53911

**Comment by sushreebarsa** [comment]
@saylideshmukh 
Can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!

**Comment by saylideshmukh** [comment]
@sushreebarsa  After training a particular cnn model if i observe the learned channel dimension values of the particular layer then most of them are similar , so i plan to make a custom layer which first just passes the output of one CNN layer to the next layer during the initial training, i can then observe the similar channel dimension values by accessing the values of the custom layer. After this i collect those similar values in a dictionary and now i want to freeze all the layers before the custom layer and pass only my compressed channel dimension values (values in the dictionary) and train only the layers preceding the custom layer of my model. This will save me some space. Since my previous layer had filter 6x6 , the dictionary has a tuple of 6 keys.The problem now i get is while mapping the dictionary keys. I have a tuple of tensors as my dictionary keys.I try to use the tf.map_fn() to map my dictionary keys(which are learned pixel values) to the inputs of the next layer . The problem i got first when i try to get the keys of the dictionary is tensors are unhashable then I made a tuple and then tried to get the keys (which are already a tuple of 6 tensors)in them , but now i get this error- 
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
