### ISSUE TITLE
iterating over `tf.Tensor` is not allowed

### ISSUE THREAD

**Issue by saylideshmukh** [tensorflow/tensorflow#53911]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.3
- Python version:3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a dictionary that I build by accessing only the channel dimensions of an output layer of a convolutional neural network (it has a shape (100,24,24,6) )
Therefore keys of this dictionary are tuples of tensor shape (6, ) . I want to map these keys to the input of the next layer using the tf.map_fn(). However, i am incapable of doing it because the keys of my dictionary are of type tensor and i cannot iterate over them .
Looking for some help. Thank you.
**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @saylideshmukh ! Could you please provide a standalone code to reproduce this issue?

**Comment by mohantym** [comment]
Hi @saylideshmukh ! Is this issue #53910 is duplicate to this feature request?

**Comment by saylideshmukh** [comment]
Yes

**Comment by saylideshmukh** [comment]
Hi @mohantym I realized that I can try to access the tf.Tensor objects by delaying my python function i.e. delaying the execution of the do_mapping function. Any idea regarding this?

**Comment by mohantym** [comment]
@saylideshmukh ! Could you provide the gist of solution you are working on and close the duplicate feature request #53910 ?

**Comment by saylideshmukh** [comment]
Hello @mohantym I have a built a custom layer and trained it by just passing the outputs of the previous layer to the custom layer and then recording these output values so that i can observe them . i use a dictionary for observing. I observed that most of the values in the channel dimension of output values are similar. So in my custom layer build i encode a dictionary (vmap)that have these enumerated similar values . Now i want to freeze all the previous layers to the custom layer and retrain my model by passing my encoded dictionary values (vmap) to the inputs of the preceding layer of the custom layer. For this purpose i need to map my enumerated values using tf.map_fn to the input channel dimension of the preceeding layer. The problem i am having is while trying to iterate over the keys of the dictionary(vmap), which are tuple of 6 tf.Tensor objects. I want to access this tf.Tensor objects of the key tuple. 
I have tried the eager execution and decorating my mapping function with tf.decorator so that i can iterate over these tf.Tensor objects . But the error i get is :TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:
"""
iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

Here is the gist of the custom layer Class : 


class valuemaplayer(keras.layers.Layer):
    def __init__(self,data_format = None,**kwargs):
        super(valuemaplayer,self).__init__(**kwargs)
        self._vmap = {}
        self._data = []
        self._compression = True
        self.data_format = conv_utils.normalize_data_format(data_format)
      

    def build(self, input_shape):
            pass

    def enable_compression(self):
        value = list(self.get_values())
        vmap = self._vmap
        cnt = 0
       
        for v0 in value:
            for v1 in v0:
                for v2 in v1:
                    for v3 in v2:
                        v = tuple(v3)
                        if v not in vmap:
                            vmap[v]=cnt
                            cnt+=1
        self._compression = True

    @tf.function
    def do_mapping(self,pixel):
        if self._compression :       #can i make this python free if cond?
            pixel = tuple(pixel)
        # to do convert pixel(of channel axis) from tensor to a tuple

        for en in range(len(pixel.shape)) :   #can i make this in tf.range of tf.while_loop cond?
            enumerated_value=self._vmap.get(pixel)
        return enumerated_value


    @tf.function
    def call(self, inputs, training=True):#use eager execution or decorate with @tf.function
        if self._compression:
                # input_shape = inputs.get_shape()
                # input_channel = self._get_input_channel(input_shape)
                # channel_axis = self._get_channel_axis()
            inputs = tuple(inputs[-1,-1,-1,:])


            # TODO check if channel axis gets mapped by tf.map_fn
            #resize inputs to 2 axis, 1 for each pixel and other channel , work on each pixel
            changed_inputs = tf.map_fn(self.do_mapping(pixel=self._vmap.keys()), elems=inputs,fn_output_signature=tf.TensorSpec)
        return changed_inputs
        # # else compression is disabled
        # # in case we're training, we do not want to observe values
        if not training:
            self._data.append(inputs)
        return inputs

        # get values of the output of value map layer
    def get_values(self):
        for d in self._data:
            try:
                d = d.numpy()
            except AttributeError:
                continue
        yield d
