### ISSUE TITLE
backporting setup.py relaxation of requirements to 2.7

### ISSUE THREAD

**Issue by casassg** [tensorflow/tensorflow#53939]
Hi folks wondering if it would be possible to backport https://github.com/tensorflow/tensorflow/commit/41e66148999080da5b2b80a59740a8f2a59f17da to 2.7 since that would make 2.7 way more flexible to install on environments.

**Comment by Saduf2019** [comment]
@casassg 
What issues are you facing with this version, that need to backport.

**Comment by casassg** [comment]
Mostly being unable to use typing-extensions severely limit my ability to use latest typing pep while also using tensorflow.

**Comment by sachinprasadhs** [comment]
I can see the changes from the above fix reflecting ion 2.7.4 patch release, you can check the file here https://github.com/tensorflow/tensorflow/blob/v2.7.4/tensorflow/tools/pip_package/setup.py and close the issue. Thanks!
