### ISSUE TITLE
TFRT saved_model_test registers type names in variant_op_registry multiple times

### ISSUE THREAD

**Issue by lzr-official** [tensorflow/tensorflow#53936]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9.9 (stretch)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: master
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
The target `//tensorflow/core/tfrt/saved_model/tests:saved_model_test` somehow caused multiple call to register actions in variant_op_registry.cc.

E.g. This line [`REGISTER_UNARY_VARIANT_DECODE_FUNCTION(Tensor, "tensorflow::Tensor");`](https://github.com/tensorflow/tensorflow/blob/ae9e5b2aa9cad5da4e614dfb40766c8e64bfc2d6/tensorflow/core/framework/tensor.cc#L71) is called two times and fail check:
> 2022-01-24 19:21:42.384846: F tensorflow/core/framework/variant_op_registry.cc:77] Check failed: existing == nullptr (0x6d2e2e0 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I did some preprocessing steps to get this test to run:
1. Set visibility to public for `//tensorflow/core/tfrt/callback:op_kernel_runner` (because build fails on visibility)
2. Add `"@com_google_absl//absl/flags:flag"` dependency to `//tensorflow/core/tfrt/saved_model:saved_model_testutil`; Add
    ```
    #include "absl/flags/declare.h"
    #include "absl/flags/flag.h"
    ```
    to `//tensorflow/core/tfrt/saved_model/saved_model_testutil.h`
 (Otherwise `ABSL_DECLARE_FLAG` is not defined)
3. Remove the `no_oss` tag in`//tensorflow/core/tfrt/saved_model/tests:saved_model_test` (Otherwise it won't run)

And then run
```
bazel test --config=tfrt tensorflow/core/tfrt/saved_model/tests:saved_model_test
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by qqfish** [comment]
Can you log a stack trace before [REGISTER_UNARY_VARIANT_DECODE_FUNCTION(Tensor, "tensorflow::Tensor");](https://github.com/tensorflow/tensorflow/blob/ae9e5b2aa9cad5da4e614dfb40766c8e64bfc2d6/tensorflow/core/framework/tensor.cc#L71)?  Then we may know why it is linked twice.

Bazel should be able to dedup automatically. However, if it is linked as an external library (e.g. tf_runtime is an external library to TensorFlow), then it is possible to have this issue.

**Comment by lzr-official** [comment]
Looking from the stack trace, the code is linked via two .so: `libtensorflow_Score_Sframework_Slibtensor.so` and `libtensorflow_framework.so.2`:

```
stack trace:
  /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/tfrt/saved_model/tests/../../../../../_solib_k8/libtensorflow_Score_Sframework_Slibtensor.so : ()+0x278de
  /lib64/ld-linux-x86-64.so.2 : ()+0xf79a
  /lib64/ld-linux-x86-64.so.2 : ()+0xf8ab
  /lib64/ld-linux-x86-64.so.2 : ()+0xc5a
2022-01-24 23:35:59.418926: E tensorflow/core/framework/variant_op_registry.cc:74] *** UnaryVariantOpRegistry::RegisterDecodeFn tensorflow::Tensor
stack trace:
  /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/tfrt/saved_model/tests/../../../../../_solib_k8/_U_S_Stensorflow_Score_Stfrt_Ssaved_Umodel_Stests_Csaved_Umodel_Utest___Utensorflow/libtensorflow_framework.so.2 : ()+0x777d0e
  /lib64/ld-linux-x86-64.so.2 : ()+0xf79a
  /lib64/ld-linux-x86-64.so.2 : ()+0xf8ab
  /lib64/ld-linux-x86-64.so.2 : ()+0xc5a
2022-01-24 23:35:59.423506: E tensorflow/core/framework/variant_op_registry.cc:74] *** UnaryVariantOpRegistry::RegisterDecodeFn tensorflow::Tensor
2022-01-24 23:35:59.424534: F tensorflow/core/framework/variant_op_registry.cc:77] Check failed: existing == nullptr (0x67d0400 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered
```

It seems to me like the two .so are coming from `//tensorflow/core:framework` and `//tensorflow/core/framework:tensor`, where the former contains the latter. Both are from within tensorflow but not tf_runtime. (not sure if I understood correctly)

I also observed another test ([xla_compiler_test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/xla_compiler_test.cc)) that also depend on `//tensorflow/core/framework:tensor`. `ldd` of the test binary shows that it only links `libtensorflow_framework.so.2` but not linking `libtensorflow_Score_Sframework_Slibtensor.so`.

**Comment by lzr-official** [comment]
Changing to `linkstatic=True` for this test would result in a build error:
```
ERROR: /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/external/llvm-project/llvm/BUILD.bazel:1909:16: Compiling llvm/lib/Target/ARM/Thumb2InstrInfo.cpp failed: (Exit 1): gcc failed: error executing command /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 73 argument(s) skipped)
during RTL pass: expand
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp: In function 'bool llvm::rewriteT2FrameIndex(llvm::MachineInstr&, unsigned int, llvm::Register, int&, const llvm::ARMBaseInstrInfo&, const llvm::TargetRegisterInfo*)':
external/llvm-project/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp:764:1: internal compiler error: in commit_one_edge_insertion, at cfgrtl.c:2021
 }
 ^
0x5d188d commit_one_edge_insertion(edge_def*)
        ../.././gcc/cfgrtl.c:2021
0x7f2f55 execute
        ../.././gcc/cfgexpand.c:6498

```

**Comment by lzr-official** [comment]
The issue might be that `//tensorflow/core/tfrt/saved_model/tests:saved_model_test` is a `tf_cc_test`, which links in shared object `tensorflow_framework` sources via [`tf_binary_additional_srcs`](https://github.com/tensorflow/tensorflow/blob/ee62dbd6d71243c0d7c79123f6b34d26cc048599/tensorflow/tensorflow.bzl#L558-L572).

We worked around in the following way:
1. Change `tf_cc_test` to `cc_test`;
2. Link the [dependencies](https://github.com/tensorflow/tensorflow/blob/ee62dbd6d71243c0d7c79123f6b34d26cc048599/tensorflow/BUILD#L951-L974) of `tensorflow_framework` shared object back into our `cc_test`
```
deps = original_deps + [
        "//tensorflow:tf_private_symbols.lds",
        "//tensorflow/c/experimental/filesystem:filesystem_interface",
        "//tensorflow/c/experimental/stream_executor:stream_executor",
        "//tensorflow/c:env",
        "//tensorflow/c:kernels",
        "//tensorflow/c:kernels_experimental",
        "//tensorflow/c:logging",
        "//tensorflow/c:ops",
        "//tensorflow/cc/saved_model:loader_lite_impl",
        "//tensorflow/cc/saved_model:metrics_impl",
        "//tensorflow/core/common_runtime:core_cpu_impl",
        "//tensorflow/core:framework_internal_impl",
        "//tensorflow/core/common_runtime/gpu:gpu_runtime_impl",
        "//tensorflow/core/common_runtime/pluggable_device:pluggable_device_runtime_impl",
        "//tensorflow/core/grappler/optimizers:custom_graph_optimizer_registry_impl",
        "//tensorflow/core:lib_internal_impl",
        "//tensorflow/core/profiler:profiler_impl",
        "//tensorflow/core/util:determinism",
        "//tensorflow/lite/kernels/shim:tf_kernel_shim",
        "//tensorflow/stream_executor:stream_executor_impl",
        "//tensorflow:tf_framework_version_script.lds",
    ] + tf_additional_binary_deps(),
```

The multiple registration issue is gone with these settings. (Some saved_model reading issue remain though)

**Comment by lzr-official** [comment]
Looks like the test fails because `tfrt.merge.chains` kernel is not open-sourced yet?

```
[ RUN      ] SavedModelTest.BasicV2
2022-01-26 05:35:55.123556: I tensorflow/core/tfrt/saved_model/saved_model.cc:418] TFRT reading v1 savedmodel: /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/tfrt/saved_model/tests/saved_model_test.runfiles/org_t
ensorflow/tensorflow/core/tfrt/saved_model/tests/toy_v2                                                                                                                                               
2022-01-26 05:35:55.123597: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/tfrt/saved_model/tests/saved_model_test.runfiles/org_tensorflow/tensor
flow/core/tfrt/saved_model/tests/toy_v2
2022-01-26 05:35:55.124004: I tensorflow/cc/saved_model/reader.cc:78] Reading meta graph with tags { serve }
2022-01-26 05:35:55.124057: I tensorflow/core/tfrt/saved_model/saved_model.cc:434] TFRT finished reading meta graph. Took 0 ms.
2022-01-26 05:35:55.124070: I tensorflow/core/tfrt/saved_model/saved_model.cc:485] TFRT loading v1 savedmodel: /data00/home/zhuoran.liu/.cache/bazel/_bazel_zhuoran.liu/c9b3369ae2db47e431aa7b0a87cbd540/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/core/tfrt/saved_model/tests/saved_model_test.runfiles/org_t
ensorflow/tensorflow/core/tfrt/saved_model/tests/toy_v2                                                                                                                                                           
2022-01-26 05:35:55.124082: I tensorflow/core/tfrt/saved_model/saved_model.cc:501] TFRT Savedmodel use TPU target NoTpu                                                                                                              
2022-01-26 05:35:55.125893: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-26 05:35:55.156251: I tensorflow/core/tfrt/saved_model/saved_model_import_input.cc:47] TFRT importing savedmodel signature: serving_default
2022-01-26 05:35:55.157061: W tensorflow/core/tfrt/utils/tfrt_graph_execution_state.cc:263] TFRT failed to optimize graph: INVALID_ARGUMENT: Meta Optimizer disabled
2022-01-26 05:35:55.158508: I tensorflow/core/tfrt/saved_model/saved_model_import_input.cc:47] TFRT importing savedmodel signature: StatefulPartitionedCall_2
2022-01-26 05:35:55.159069: W tensorflow/core/tfrt/utils/tfrt_graph_execution_state.cc:263] TFRT failed to optimize graph: INVALID_ARGUMENT: Meta Optimizer disabled
2022-01-26 05:35:55.160018: I tensorflow/core/tfrt/saved_model/saved_model_import_input.cc:47] TFRT importing savedmodel signature: NoOp
2022-01-26 05:35:55.160362: W tensorflow/core/tfrt/utils/tfrt_graph_execution_state.cc:263] TFRT failed to optimize graph: INVALID_ARGUMENT: Meta Optimizer disabled
2022-01-26 05:35:55.160779: I tensorflow/core/tfrt/saved_model/saved_model.cc:363] TFRT ImportSavedModel: Functionalization took 0 ms.                                                                        
2022-01-26 05:35:55.160796: I tensorflow/core/tfrt/saved_model/saved_model.cc:367] TFRT ImportSavedModel: Grappler took 0 ms.                                                                                                    
2022-01-26 05:35:55.161013: I tensorflow/core/tfrt/saved_model/saved_model.cc:535] TFRT finished importing savedmodel. Took 36 ms.                                                                                               
2022-01-26 05:35:55.171788: I tensorflow/core/tfrt/saved_model/saved_model.cc:558] TFRT finished compiling savedmodel. Took 10 ms.
2022-01-26 05:35:55.171831: E tensorflow/core/tfrt/runtime/runtime.cc:133] unknown kernel name 'tfrt.merge.chains'
2022-01-26 05:35:55.176632: E tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (tensorflow/core/tfrt/utils/utils.cc:117) bef_file failed to open BEF
*** Begin stack trace ***

        xla::status_macros::MakeErrorStream::Impl::GetStatus()
        tfrt::CreateBefFileFromBefBuffer(tensorflow::tfrt_stub::Runtime const&, std::vector<unsigned char, tfrt::internal::AlignedAllocator<unsigned char, 8ul> > const&)
        tensorflow::tfrt_stub::SavedModelImpl::LoadSavedModel(tensorflow::tfrt_stub::SavedModel::Options, absl::lts_20210324::string_view, tensorflow::MetaGraphDef, tensorflow::Status*)
        tensorflow::tfrt_stub::SavedModelImpl::LoadSavedModel(tensorflow::tfrt_stub::SavedModel::Options, absl::lts_20210324::string_view, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::alloc
ator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, tensorflow::Status*)
        tensorflow::tfrt_stub::TFRTSavedModelTest::TFRTSavedModelTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<tensorflow::tfrt_stub::Runtime, std::default_delete<tensorflow::tfrt_stub::Runtime> >)
        tensorflow::tfrt_stub::TFRTSavedModelTest::TFRTSavedModelTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)

        void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
        testing::Test::Run()
        testing::TestInfo::Run()
        testing::TestSuite::Run()
        testing::internal::UnitTestImpl::RunAllTests()
        bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
        testing::UnitTest::Run()
        main
        __libc_start_main

*** End stack trace ***
```

**Comment by lzr-official** [comment]
Turns out some kernel registrations are not always linked. Adding `*_alwayslink` targets of kernel registrations from `@tf_runtime` to `//tensorflow/core/tfrt/saved_model:saved_model` resolves the issue. E.g:
```
        "@tf_runtime//:basic_kernels_alwayslink",
        "@tf_runtime//:test_kernels_alwayslink",
        "@tf_runtime//:io_alwayslink",
        "@tf_runtime//:data_alwayslink",
```

**Comment by lzr-official** [comment]
Closing this issue since all blockers are worked-around. Thanks @qqfish and others for triaging!

**Comment by lzr-official** [comment]
I tried to compare the `TraceMe` of [TfrtModelRun](https://github.com/tensorflow/tensorflow/blob/eca06dbd5d190645d10686494ee222fafbb12094/tensorflow/core/tfrt/graph_executor/graph_executor.cc#L160) and [SessionRun](https://github.com/tensorflow/tensorflow/blob/eca06dbd5d190645d10686494ee222fafbb12094/tensorflow/core/common_runtime/direct_session.cc#L525), and find that for a `MatMul`-dominant model TFRT is much slower.
**TFRT:**
![image](https://user-images.githubusercontent.com/49047362/152891918-ca757f2c-b0cb-411c-ad30-f85da900a383.png)
**Session Run:**
![image](https://user-images.githubusercontent.com/49047362/152891976-24d44841-c8b1-430d-837c-f3169a639218.png)


I have two questions about this:
1. Are these two `TraceMe` comparable? If not, which section should be timed in order to compare the performance of TFRT and current runtime?
2. It looks like current runtime comes with breakdowns of smaller `TraceMe` into op-level (e.g. showing which op / function consumes what amount of time). Are there equivalents in TFRT? Is there some config I need to turn on to see them?
**TFRT:**
![image](https://user-images.githubusercontent.com/49047362/152892055-472b0b7f-37a0-430e-9000-bb7f75f61a2a.png)
(Only some fallback tensor conversion is shown)
![image](https://user-images.githubusercontent.com/49047362/152892471-5cb87679-9b43-48d0-8357-5e435c6dba3e.png)

**Session Run:**
![image](https://user-images.githubusercontent.com/49047362/152892133-4f7ff578-1b88-423f-865e-0bea69802e4d.png)

**Comment by qqfish** [comment]
The threading looks suspicious: in TFRT, looks like only one thread is using for computation.

**Comment by lzr-official** [comment]
Thanks @qqfish and @cky9301 ! After increasing number of threads and setting compile options as suggested, time cost of `TfrtModelRun` is almost on par with `SessionRun` (variating run to run with ~10% fluctuation).

One more question is: What is a general guideline for tuning `num_threads` and `num_blocking_threads` in
```cpp
tensorflow::tfrt_stub::Runtime::Create(
      tensorflow::tfrt_stub::WrapDefaultWorkQueue(
          tfrt::CreateMultiThreadedWorkQueue(num_threads, num_blocking_threads)));
```

**Comment by cky9301** [comment]
You can set "num_threads" to the number of CPU cores you want to utilize for executing ops. "num_blocking_threads" is roughly not used for CPU ops. "num_threads" here is the same as "inter_op_parallelism_threads" in SessionOptions. By default, IIRC, SessionRun() uses tensorflow::port::MaxParallelism(). You can also use this number.
