### ISSUE TITLE
Distributed training hangs

### ISSUE THREAD

**Issue by passerbyd** [tensorflow/tensorflow#5394]
As mentioned in #4651, during training with syncreplicasoptimizer, tensorflow must run into hanging(after thousands steps). This does not happen with simple network setup. 
Both workers and pses are still "alive", no errors/exceptions are reported. The saver thread keeps working.

Environment info
the cluster is set on 2 servers, one ps and one worker on each. And each worker works on 4 gpu cards.

Operating System:
Centos (customized)

Installed version of CUDA and cuDNN: 
CUDA 7.5
cnDNN 5.1

installed from source,  
build on branch r0.11, and r0.10

trace log after hanging
[ps0_pstack.txt](https://github.com/tensorflow/tensorflow/files/570595/ps0_pstack.txt)
[ps0_strace.txt](https://github.com/tensorflow/tensorflow/files/570597/ps0_strace.txt)
[ps1_pstack.txt](https://github.com/tensorflow/tensorflow/files/570598/ps1_pstack.txt)
[ps1_strace.txt](https://github.com/tensorflow/tensorflow/files/570602/ps1_strace.txt)
[worker0_pstack.txt](https://github.com/tensorflow/tensorflow/files/570601/worker0_pstack.txt)
[worker0_strace.txt](https://github.com/tensorflow/tensorflow/files/570600/worker0_strace.txt)
[worker1_pstack.txt](https://github.com/tensorflow/tensorflow/files/570596/worker1_pstack.txt)
[worker1_strace.txt](https://github.com/tensorflow/tensorflow/files/570599/worker1_strace.txt)

**Comment by passerbyd** [comment]
If you need the setup to reproduce this issue, please message me your email address.

**Comment by aselle** [comment]
I'm sorry, but I'm closing this for now for these reasons.
- Providing reproduction instructions was why #4651 was closed, and you still have not provided them. This type of problem cannot be solved by simple inspection of the stack trace (@mrry, you don't have any magical solution do you).
- Providing them for email removes visibility to your issue which is at odds with the idea of community support.
- CentOS is an unsupported platform. @jart's example of someone getting help was on an Ubuntu platform.

**Comment by aselle** [comment]
See #5394

**Comment by martinwicke** [comment]
From @mrry: Maybe the queue runner on the chief wasn't started, which is required for synchronous updates. No way to verify without the code.

**Comment by passerbyd** [comment]
The problem does not happen any more on current version of RDMA. Seems like an issue on GRPC.

**Comment by martinwicke** [comment]
Maybe it's an instance of the bug fixed by https://github.com/grpc/grpc/pull/12648? We should get an updated ref to gRPC soon, which might fix this.
