### ISSUE TITLE
tf.train.range_input_producer(epoch_size, shuffle=True) does not terminate

### ISSUE THREAD

**Issue by pltrdy** [tensorflow/tensorflow#5396]
Hey guys,

While working on language modeling using PTB dataset  [(as shown in TensorFlow tutorial)](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) I had an issue with `ptb_producer `[(see on StackOverflow)](http://stackoverflow.com/questions/40406469/tf-nn-embedding-lookup-does-nothing-blocking-the-execution-but-no-associated-cp).

Long story short, it turns out that `ptb_producer` never terminates.

To debug, I tried to 'manually' run `ptb_producer` with the code below.

```
import tensorflow as tf

learning_rate = 1.0
num_layers = 2
num_steps = 20
hidden_size = 2
epochs = 50
batch_size = 20
vocab_size = 10000

# Loading data
import tensorflow.models.rnn.ptb.reader as reader

ptb_data_path = '<path>/tensorflow/ptb_data/simple-examples/data/'
(train, valid, test, _) = reader.ptb_raw_data(ptb_data_path)

raw_data = train
name = None

# Exact content of PTBProducer
with tf.name_scope(name, "PTBProducer", [raw_data, batch_size, num_steps]):
    raw_data = tf.convert_to_tensor(raw_data, name="raw_data", dtype=tf.int32)

    data_len = tf.size(raw_data)
    batch_len = data_len // batch_size
    data = tf.reshape(raw_data[0 : batch_size * batch_len],
                      [batch_size, batch_len])

    epoch_size = (batch_len - 1) // num_steps
    assertion = tf.assert_positive(
        epoch_size,
        message="epoch_size == 0, decrease batch_size or num_steps")
    with tf.control_dependencies([assertion]):
        epoch_size = tf.identity(epoch_size, name="epoch_size")

    i = tf.train.range_input_producer(epoch_size, shuffle=False).dequeue()
    x = tf.slice(data, [0, i * num_steps], [batch_size, num_steps])
    y = tf.slice(data, [0, i * num_steps + 1], [batch_size, num_steps])
```

And then running to find out where thing is getting into troubles
`sess = tf.Session()` then `sess.run(epoch_size)` gives `2323`

Running `sess.run(tf.train.range_input_producer(epoch_size, shuffle=True).dequeue())` just waits (it does not terminate nor induce CPU load, i.e. same problem than when I run the whole code).

In fact, even `queue = tf.train.range_input_producer(epoch_size, shuffle=True)` (which can be intermediate step for previous syntax) does nothing. There is the problem line, still don't know why

I am not sure how this issue could be related to be, thus it might be a bug.

# Config Information
- `tf.__version__` = '0.11.0rc2'
- python 3.5.2
- Ubuntu 16.04

**Comment by aselle** [comment]
To be clear. Are you running the unmodified tutorial, or are you writing your own code and having problems? If it is the former, then it is a bug, and a github issue is appropriate. Otherwise, please wait for a response on stackoverflow.

**Comment by pltrdy** [comment]
My point here is that I am using [reader.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/reader.py) from a custom script (i.e. not [ptb_word_lm.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/ptb_word_lm.py) as suggested in the tuto). 

My issue in fact only concerns [reader.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/ptb/reader.py) since I'm having trouble using `tensorflow.models.rnn.ptb.ptb_word_lm.ptb_producer()`. My tensorflow is up to date with master. 

I think I may have missunderstood something. I would expect `inputs_ = sess.run(inputs)` to run correctly with following "model":

```
ptb_data_path = '<some_path>/ptb_data/simple-examples/data/'
(train, valid, test, _) = reader.ptb_raw_data(ptb_data_path)
c = ptb_word_lm.SmallConfig()
inputs, targets = reader.ptb_producer(train, c.batch_size, c.num_steps, name=None)
```

It instead "sleeps" (does not terminate, no (C/G)PU load

**Comment by girving** [comment]
You probably need to start queue runners.  Please see the documentation at

https://www.tensorflow.org/versions/r0.11/how_tos/threading_and_queues/index.html

**Comment by pltrdy** [comment]
I am still having trouble with this ptb_producer. My point now is just not to pass data on graph building (i.e. not in the PTBModel object creation) but on execution through placeholder.

Thus I modified PTBInput the following way:
```
class PTBInput(object):
  """The input data."""

  def __init__(self, config, data=None, name=None):
    self.data = data #tf.placeholder(tf.int32, shape=[None], name="data")
    datalen = tf.size(self.data)

    self.batch_size = batch_size = config.batch_size
    self.num_steps = num_steps = config.num_steps
    self.epoch_size = ((datalen // batch_size) - 1) // num_steps
    self.input_data, self.targets = reader.producer(
        self.data, batch_size, num_steps, name=name)
```
and I try to run:
```
from ptb_word_lm import PTBModel, SmallConfig
import reader

config = SmallConfig() 
data_path='./data'
train_data, valid_data, test_data, word_to_id = reader.ptb_raw_data(data_path)
with tf.Graph().as_default():
   initializer = tf.random_uniform_initializer(-config.init_scale,config.init_scale)
    with tf.name_scope("Train"):
        with tf.variable_scope("Model", reuse=False, initializer=initializer):
            m = Model(is_training=True, config=config)
    
    with tf.Session()  as session:
        m.assign_lr(session, 1.0)
        state = session.run(m.initial_state)
        vals = session.run([m.cost, m.final_state], feed_dict={m.initial_state: state, m.data: train_data})
```

Which should run one training epoch. 
This code is minimalistic but still does not work. As always, no CPU nor GPU load, just waiting...

The only difference is that 'data' is not an array anymore but a Tensorf (placeholder), don't see which this induces errors.

**Comment by girving** [comment]
Please read the documentation on queues I linked above.  You need to start queue runners.

**Comment by wangpeng138375** [comment]
If you just use code of `with tf.Session() as sess:,` you must open the thread explicitly with `threads = tf.train.start_queue_runners()`. But in ptb_word_lm.py, It uses the codes like this `sv = tf.train.Supervisor()  with sv.managed_session() as sess:`, the Supervisor() function contains something which starts the thread implicitly

**Comment by wangpeng138375** [comment]
I really confused ! 
 `  x = tf.slice(data, [0, i * num_steps], [batch_size, num_steps])
    y = tf.slice(data, [0, i * num_steps + 1], [batch_size, num_steps])`
Do x  and y use the same value of i ??????????????????????

**Comment by RudrakshTuwani** [comment]
For anyone else struggling with this, please read the documentation as mentioned by girving. For the lazy ones:

```
init = tf.global_variables_initializer()
sess.run(init)
threads = tf.train.start_queue_runners()
print(sess.run(name_of_output_tensor))
```

**Comment by Rojina99** [comment]
Can you help me understand this problem.I am also having the same problem, I am checking the function values with Interactive session as

def ptb_producer(raw_data, batch_size, num_steps, name=None):
  """Iterate on the raw PTB data.

  This chunks up raw_data into batches of examples and returns Tensors that
  are drawn from these batches.

  Args:
    raw_data: one of the raw data outputs from ptb_raw_data.
    batch_size: int, the batch size.
    num_steps: int, the number of unrolls.
    name: the name of this operation (optional).

  Returns:
    A pair of Tensors, each shaped [batch_size, num_steps]. The second element
    of the tuple is the same data time-shifted to the right by one.

  Raises:
    tf.errors.InvalidArgumentError: if batch_size or num_steps are too high.
  """
  session = tf.InteractiveSession()
  with tf.name_scope(name, "PTBProducer", [raw_data, batch_size, num_steps]):
    raw_data = tf.convert_to_tensor(raw_data, name="raw_data", dtype=tf.int32)
    data_len = tf.size(raw_data)
    print("Data Len", data_len.eval())
    batch_len = data_len // batch_size
    print("Batch Len", batch_len.eval())
    data = tf.reshape(raw_data[0 : batch_size * batch_len],
                      [batch_size, batch_len])
    print("Data", data.eval())
    a = tf.shape(data)
    print("Data Size", a.eval())
    epoch_size = (batch_len - 1) // num_steps
    print("Epoch_Size", epoch_size.eval())
    assertion = tf.assert_positive(
        epoch_size,
        message="epoch_size == 0, decrease batch_size or num_steps")
    with tf.control_dependencies([assertion]):
      epoch_size = tf.identity(epoch_size, name="epoch_size")
    # session.run(tf.global_variables_initializer())
    threads = tf.train.start_queue_runners()
    # session.run(threads)
    i = tf.train.range_input_producer(epoch_size, shuffle=False).dequeue()
    print("i", i.eval())
    x = tf.strided_slice(data, [0, i * num_steps],
                         [batch_size, (i + 1) * num_steps])
    print("x", x.eval())
    x.set_shape([batch_size, num_steps])
    print("x", x.eval())
    y = tf.strided_slice(data, [0, i * num_steps + 1],
                         [batch_size, (i + 1) * num_steps + 1])
    print("y", y.eval())
    y.set_shape([batch_size, num_steps])
    print("y", y.eval())
    return x, y

raw_data = ptb_raw_data("DataPath")
ptb_producer(raw_data[0], batch_size=25, num_steps=7)

But I could not get any output at print("i", i.eval()) and the process also kept running
