### ISSUE TITLE
Support cuda 7.5 and cudnn 7.0

### ISSUE THREAD

**Issue by amolchanov86** [tensorflow/tensorflow#54]
Please, add support of cuda 7.5 and cudnn 7.0. 
The best way would be to introduce it as configuration option. Right now, I have to correct everything manually, since only cuda 7.0 and cudnn 6.5 are supported

**Comment by zheng-xq** [comment]
There are two short-term options for now. 

1. Install Cuda 7.0 and Cudnn 6.5, in additional to your existing Cuda 7.5 and Cudnn 7.0 libraries. They are the officially supported versions. And it is okay to have multiple Cuda toolkits with different paths on your system. This is the recommended way.

2. Manually correct source code to pick up Cuda 7.5. We are discussing options to make it easier to configure in the future. However, given Cuda toolkits and libraries are not necessarily backward compatible, you may or may not hit subtle issues down the road.

**Comment by shenxudeu** [comment]
I have Cuda 7.0 and Cudnn 7.0 installed on my machine. This message pop up when I import tensor flow:

I tensorflow/stream_executor/dso_loader.cc:77] LD_LIBRARY_PATH: :/usr/local/cuda-7.0/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1062] Unable to load cuDNN DSO.

Does it mean it does NOT support Cudnn 7.0?

**Comment by zheng-xq** [comment]
At this moment, the officially supported CUDNN version is 6.5 V2. This may change soon.

You can download the previous version from NVIDIA website, and use it in the configure script. This is okay even if you have CUDNN 7.0 V3 installed in the system.

https://developer.nvidia.com/rdp/cudnn-archive

**Comment by shenxudeu** [comment]
Thanks! It helps. I got another problem when I tries to build from source
on another machine (Nvidia Dev Box, Ubuntu 14.04.1).

When I follow the Installation for linux from tensorflow offical site,
everything is fine until the last step:Train your first TensorFlow neural
net model.

When I execute the command, python
tensorflow/models/image/mnist/convolutional.py, An ImportError promps.

Traceback (most recent call last): File
"tensorflow/models/image/mnist/convolutional.py", line 13, in <module>
import tensorflow.python.platform File "tensorflow/tensorflow/__init__.py",
line 4, in <module> from tensorflow.python import * File
"tensorflow/tensorflow/python/__init__.py", line 13, in <module> from
tensorflow.core.framework.graph_pb2 import * ImportError: No module named
core.framework.graph_pb2


Would you shed some light on this?

Thanks,

Shen

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/20
