### ISSUE TITLE
Extract glimpse has no shape function

### ISSUE THREAD

**Issue by boyentenbi** [tensorflow/tensorflow#540]
I'm receiving this error when calling tf.image.extract_glimpse:

**No shape function registered for standard op: ExtractGlimpse**

Could someone confirm that this is a problem with the API itself? If so, how can I go about implementing a solution?

**Comment by bschreck** [comment]
I found this was a problem too, and hacked a solution together by registering a shape for it:

    ops.RegisterShape("ExtractGlimpse")
    def _ExtractGlimpseShape(op):
      """Shape function for ExtractGlimpse op."""
      input_shape = op.inputs[0].get_shape().with_rank(4)
      unused_size_shape = op.inputs[1].get_shape().merge_with(
          tensor_shape.vector(2))
      offsets_shape = op.inputs[2].get_shape().merge_with(
          input_shape[:1].concatenate([2]))
       offsets_shape = offsets_shape
       size_value = tf.ConstantValue(op.inputs[1])
      if size_value is not None:
        height = size_value[0]
        width = size_value[1]
      else:
        height = None
        width = None
      return [tf.TensorShape(
          [input_shape[0], height, width, input_shape[3]])]

**Comment by boyentenbi** [comment]
Thanks a lot; can I just run this once in my own code, or do I have to paste it into some of the tensorflow files?

**Comment by boyentenbi** [comment]
I've found an almost identical piece of code in /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/attentions_ops.py

It must be that the code isn't being called correctly; how did you fix this? Or in which file should the code be pasted?

**Comment by mrry** [comment]
Thanks for reporting this - there is a bug in the imports for this code. I'm working on a fix, and it should be available soon.
