### ISSUE TITLE
Some operations didn't work in tflite train procedure.

### ISSUE THREAD

**Issue by SpicyYeol** [tensorflow/tensorflow#54001]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- TensorFlow version (use command below): tensorflow 2.7.0
- Python version: python 3.9
- CUDA/cuDNN version: Cuda 11.2/ cudnn 8.2
- GPU model and memory: rtx A6000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
 I want to generate fully train able tflite model. I found mapped ops in ['tfl' Dialect](https://www.tensorflow.org/mlir/tfl_ops?hl=en). And then, I use these functions in my model.  All operation can convert to graph model use converter.convert(), but it dosen't work. Some operation can use in inference, but can't use in train without any error just stop.(ex. Avgpool2d). 

**Describe the expected behavior**

I have three questions in upper problem.

 First, Is this operation(avgpool) can't use in  tflite?

 Second, If first question is true, can i get trainable operation documentation in tflite?

 Third, When can i use fully trainable tflite model in mobile?

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

** custom source code
```
`import tensorflow as tf
import numpy as np

import h5py
import json

import os
os.environ["CUDA_VISIBLE_DEVICES"]="3"
print(tf.__version__)
print("here")


class Deepphys(tf.keras.Model):
    def __init__(self):
        super(Deepphys,self).__init__()
        self.a_1 = tf.keras.layers.ZeroPadding2D(1)
        self.a_2 = tf.keras.layers.Conv2D(filters=32,kernel_size=3,name='a_2')
        # self.a_3 = tf.keras.layers.BatchNormalization()

        self.a_4 = tf.keras.layers.ZeroPadding2D(1)
        self.a_5 = tf.keras.layers.Conv2D(filters=32, kernel_size=3,name='a_5')
        # self.a_6 = tf.keras.layers.BatchNormalization()

        self.a_7 = tf.keras.layers.AveragePooling2D(pool_size =2,strides=2)

        self.a_8 = tf.keras.layers.ZeroPadding2D(1)
        self.a_9 = tf.keras.layers.Conv2D(filters=64, kernel_size=3,name='a_7')
        # self.a_10 = tf.keras.layers.BatchNormalization()

        self.a_11 = tf.keras.layers.ZeroPadding2D(1)
        self.a_12 = tf.keras.layers.Conv2D(filters=64, kernel_size=3,name='a_12')
        # self.a_13 = tf.keras.layers.BatchNormalization()

        self.att_conv_1 = tf.keras.layers.Conv2D(filters=1,kernel_size=1,activation='sigmoid',name='att_1')
        self.att_conv_2 = tf.keras.layers.Conv2D(filters=1, kernel_size=1,activation='sigmoid',name='att_2')

        self.m_1 = tf.keras.layers.ZeroPadding2D(1)
        self.m_2 = tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='valid',name='m_2')
        # self.m_3 = tf.keras.layers.BatchNormalization()

        self.m_4 = tf.keras.layers.ZeroPadding2D(1)
        self.m_5 = tf.keras.layers.Conv2D(filters=32,kernel_size=3,name='m_5')
        # self.m_6 = tf.keras.layers.BatchNormalization()

        # self.m_7 = tf.keras.layers.AveragePooling2D(pool_size=2, strides=2)
        self.m_7 = tf.keras.layers.Conv2D(filters = 32, kernel_size=2, strides=2)


        self.m_8 = tf.keras.layers.ZeroPadding2D(1)
        self.m_9 = tf.keras.layers.Conv2D(filters=64,kernel_size=3,strides=1,name='m_9')
        # self.m_10 = tf.keras.layers.BatchNormalization()

        self.m_11 = tf.keras.layers.ZeroPadding2D(1)
        self.m_12 = tf.keras.layers.Conv2D(filters=64, kernel_size=3, strides=1,name='m_12')
        # self.m_13 = tf.keras.layers.BatchNormalization()

        # self.m_14 = tf.keras.layers.AveragePooling2D(pool_size=2,strides=2)
        self.m_14 = tf.keras.layers.Conv2D(filters=64, kernel_size=2, strides=2)

        self.f_1 = tf.keras.layers.Flatten()
        self.f_2 = tf.keras.layers.Dense(256)
        self.f_3 = tf.keras.layers.Dense(1)


    @tf.function(input_signature=[
        tf.TensorSpec([None,36,36,6], tf.float32),
    ])
    def call(self,inputs):
        _in = tf.split(inputs,2,axis=3)
        A = self.a_1(_in[1])
        A = self.a_2(A)
        # A = self.a_3(A)
        A = tf.keras.activations.tanh(A)

        A = self.a_4(A)
        A = self.a_5(A)
        # A = self.a_6(A)
        A = tf.keras.activations.tanh(A)

        M1 = self.att_conv_1(A)
        # M1 = tf.keras.activations.sigmoid(M1)
        # B,_,H,W = tf.shape(M1)
        norm = tf.abs(M1)
        norm = tf.math.reduce_sum(norm)
        norm = 2 * norm
        norm = tf.reshape(norm,[1,1,1,1])
        M1 = tf.divide(M1,norm)

        A = self.a_7(A)
        A = self.a_8(A)
        A = self.a_9(A)
        # A = self.a_10(A)
        A = tf.keras.activations.tanh(A)

        A = self.a_11(A)
        A = self.a_12(A)
        # A = self.a_13(A)
        A = tf.keras.activations.tanh(A)

        M2 = self.att_conv_2(A)
        # M2 = tf.keras.activations.sigmoid(M2)
        # B, _, H, W = tf.shape(M2)
        norm = tf.abs(M2)
        norm = tf.math.reduce_sum(norm)
        norm = 2 * norm
        norm = tf.reshape(norm, [1, 1, 1, 1])
        M2 = tf.divide(M2, norm)

        M = self.m_1(_in[0])
        M = self.m_2(M)
        # M = self.m_3(M)
        M = tf.keras.activations.tanh(M)

        M = self.m_4(M)
        M = self.m_5(M)
        # M = self.m_6(M)

        ones_1 = tf.ones([1,36,36,36])
        mat_1 = ones_1 @ M1 #tf.matmul(ones_1,M1)
        g1 = mat_1*M
        M = tf.keras.activations.tanh(g1)

        M = self.m_7(M)

        M = self.m_8(M)
        M = self.m_9(M)
        # M = self.m_10(M)
        M = tf.keras.activations.tanh(M)

        M = self.m_11(M)
        M = self.m_12(M)
        # M = self.m_13(M)

        ones_2 = tf.ones([1,18,18,18])
        mat_2 = ones_2 @ M
        g2 = mat_2 * M
        M = tf.keras.activations.tanh(g2)

        M = tf.keras.activations.tanh(M)

        M = self.m_14(M)

        F = self.f_1(M)
        F = self.f_2(F)
        F = self.f_3(F)

        return F

class Model(tf.Module):
    def __init__(self):
        self.model = Deepphys()
        self.model.compile(
            optimizer='adam',
            loss=tf.keras.losses.mean_squared_error)


    @tf.function(input_signature=[
        tf.TensorSpec([1, 36,36,6], tf.float32),
        tf.TensorSpec([1, ], tf.float32),
    ])
    def train(self, x, y):
        with tf.GradientTape() as tape:
            predictions = self.model(x)
            loss = self.model.loss(predictions, y)
        gradients = tape.gradient(loss, self.model.trainable_variables)
        self.model.optimizer.apply_gradients(
            zip(gradients, self.model.trainable_variables))
        result = {"loss":loss}
        return result

    @tf.function(input_signature=[
        tf.TensorSpec([None,36,36,6], tf.float32),
    ])
    def infer(self, x):

        output = self.model(x)
        return {
            "output" : output
        }

    @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
    def save(self, checkpoint_path):
        tensor_names = [weight.name for weight in self.model.weights]
        tensors_to_save = [weight.read_value() for weight in self.model.weights]
        tf.raw_ops.Save(
            filename=checkpoint_path, tensor_names=tensor_names,
            data=tensors_to_save, name='save')
        return {
            "checkpoint_path": checkpoint_path
        }

    @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
    def restore(self, checkpoint_path):
        restored_tensors = {}
        for var in self.model.weights:
            restored = tf.raw_ops.Restore(
                file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
                name='restore')
            var.assign(restored)
            restored_tensors[var.name] = restored
        return restored_tensors

with open('../../params.json') as f:
    jsonObject = json.load(f)
    params = jsonObject.get("params")
    model_params = jsonObject.get("model_params")
    save_root_path = params["save_root_path"]
    model_name = model_params["name"]
    dataset_name = params["dataset_name"]
    option="train"

hpy_file = h5py.File(save_root_path + model_name + "_" + dataset_name + "_" + option + ".hdf5", "r")
video_data = []
label_data = []
for key in hpy_file.keys():
     video_data.extend(hpy_file[key]['preprocessed_video'])
     label_data.extend(hpy_file[key]['preprocessed_label'])
hpy_file.close()

# train_loader = DataLoader(video_data,label_data,1)

# train_loader = DataLoader(video_data[:(int)(video_data.__len__()*0.8)],label_data[:(int)(label_data.__len__()*0.8)],1)
# valid_loader = DataLoader(video_data[(int)(video_data.__len__()*0.8):],label_data[(int)(label_data.__len__()*0.8):],1)
# test_loader = DataLoader(video_data,label_data,32)

NUM_EPOCHS = 10
BATCH_SIZE = 1
epochs = np.arange(1, NUM_EPOCHS + 1, 1)
losses = np.zeros([NUM_EPOCHS])
m = Model()
# m.model.build(input_shape=(1,36,36,6))
# m.model.summary()
video_data = np.asarray(video_data)
label_data = np.asarray(label_data)
train_ds = tf.data.Dataset.from_tensor_slices((video_data[:2],label_data[:2]))
train_ds = train_ds.batch(BATCH_SIZE)

# trian
for i in range(NUM_EPOCHS):
  for x,y in train_ds:
    # x = tf.reshape(x, [-1, 2, 36, 36, 3])
    x = tf.cast(x,tf.float32)
    # y = tf.cast(y,tf.float32)
    result = m.train(x, y)
  losses[i] = result['loss']
  if (i + 1) % 1 == 0:
      # print(result['loss'])
   print(f"Finished {i+1} epochs")
   print(f"  loss: {losses[i]:.3f}")

m.save('/tmp/trained_model')

SAVED_MODEL_DIR = "./tmp"

tf.saved_model.save(
    m,
    SAVED_MODEL_DIR,
    signatures={
        'train':
            m.train.get_concrete_function(),
        'infer':
            m.infer.get_concrete_function(),
        # 'save':
        #     m.save.get_concrete_function(),
        # 'restore':
        #     m.restore.get_concrete_function(),
    })

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
# converter = tf.lite.TFLiteConverter.from_concrete_functions()
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]

converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()
f = open('test.tflite','wb')
f.write(tflite_model)
f.close()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

infer = interpreter.get_signature_runner("infer")

for x, _ in train_ds:
    x = tf.cast(x, tf.float32)
    logits_original = m.infer(x=x)['output'][0]
    logits_lite = infer(x=x)['output'][0]

    # print(logits_original, logits_lite)

print("try")
train = interpreter.get_signature_runner("train")

# train_loader = DataLoader(video_data[:(int)(video_data.__len__()*0.8)],label_data[:(int)(label_data.__len__()*0.8)],1)
print("tried")
for i in range(NUM_EPOCHS):
  for x,y in train_ds:
    x = tf.cast(x,tf.float32)
    y = tf.cast(y,tf.float32)
    result = train(x=x,y=y)
    print(result)



# # EncoderBlock
            #
            # # ConvBlock1
            # tf.keras.layers.ZeroPadding3D(padding=(0,2,2),input_shape=(32,128,128,3)),
            # tf.keras.layers.Conv3D(filters=16,kernel_size=(1,5,5),strides=(1,1,1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # #MaxPool3d1r
            # # tf.keras.layers.MaxPool3D(pool_size=(1,2,2), strides=(1,2,2)),
            # tf.keras.layers.Conv3D(filters=16, kernel_size=(1, 2, 2), strides=(1, 2, 2)),
            # # #
            # # # ConvBlock2
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=32, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # # ConvBlock3
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            #
            # # # MaxPool3d2
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(2, 2, 2), strides=(2, 2, 2)),
            # # tf.keras.layers.MaxPool3D(pool_size=(2, 2, 2), strides=(2, 2, 2)),
            # #
            # # ConvBlock4
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # # ConvBlock5
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # #
            # # # MaxPool3d3
            # # tf.keras.layers.MaxPool3D(pool_size=(2, 2, 2), strides=(2, 2, 2)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(2, 2, 2), strides=(2, 2, 2)),
            # #
            # # # ConvBlock6
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # # ConvBlock7
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # #
            # # # MaxPool3d4
            # # tf.keras.layers.MaxPool3D(pool_size=(1, 2, 2), strides=(1, 2, 2)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(1, 2, 2), strides=(1, 2, 2)),
            # # #
            # # # ConvBlock8
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            # # ConvBlock9
            # tf.keras.layers.ZeroPadding3D(padding=(1, 1, 1)),
            # tf.keras.layers.Conv3D(filters=64, kernel_size=(3, 3, 3), strides=(1, 1, 1)),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ReLU(),
            #
            # # # #
            # # # # DecoderBlock
            # # # #
            # # DeConvBlock1
            # tf.keras.layers.Convolution3DTranspose(filters=64,kernel_size=(4,1,1),strides=(2,1,1),padding='same'),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ELU(),
            #
            # # DeConvBlock2
            # tf.keras.layers.Convolution3DTranspose(filters=64, kernel_size=(4, 1, 1), strides=(2, 1, 1),padding='same'),
            # tf.keras.layers.BatchNormalization(),
            # tf.keras.layers.ELU(),
            #
            # #
            # # AdaptivePooling
            # #
            # AdaptivePooling3D(tf.reduce_max,(32,1,1)),
            # # #
            # #Conv3D
            # #
            # # tf.keras.layers.Conv3D(filters=32,kernel_size=(8,8,1)),
            #
            # tf.keras.layers.Conv3D(1,kernel_size=(1,64,64),strides=(1,1,1),padding='same'),
            # tf.keras.layers.Reshape((-1,)),`


```

**Comment by sushreebarsa** [comment]
@SpicyYeol 
In order to expedite the trouble-shooting process, please provide a  code snippet to reproduce the issue reported here. Thanks!

**Comment by SpicyYeol** [comment]
I use the modified example code. I added print("train_finish) in train loop. but I can't see that.

`import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

IMG_SIZE = 28

class Model(tf.Module):

  def __init__(self):
    self.model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation="sigmoid",input_shape=(IMG_SIZE,IMG_SIZE,1)),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.AveragePooling2D(pool_size=2),
        tf.keras.layers.Flatten(name='flatten'),
        tf.keras.layers.Dense(128, activation='relu', name='dense_1'),
        tf.keras.layers.Dense(10, name='dense_2')
    ])

    self.model.compile(
        optimizer='sgd',
        loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True))

  # The `train` function takes a batch of input images and labels.
  @tf.function(input_signature=[
      tf.TensorSpec([None, IMG_SIZE, IMG_SIZE], tf.float32),
      tf.TensorSpec([None, 10], tf.float32),
  ])
  def train(self, x, y):
    with tf.GradientTape() as tape:
      prediction = self.model(x)
      loss = self.model.loss(y, prediction)
    gradients = tape.gradient(loss, self.model.trainable_variables)
    self.model.optimizer.apply_gradients(
        zip(gradients, self.model.trainable_variables))
    result = {"loss": loss}
    return result

  @tf.function(input_signature=[
      tf.TensorSpec([None, IMG_SIZE, IMG_SIZE], tf.float32),
  ])
  def infer(self, x):
    logits = self.model(x)
    probabilities = tf.nn.softmax(logits, axis=-1)
    return {
        "output": probabilities,
        "logits": logits
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def save(self, checkpoint_path):
    tensor_names = [weight.name for weight in self.model.weights]
    tensors_to_save = [weight.read_value() for weight in self.model.weights]
    tf.raw_ops.Save(
        filename=checkpoint_path, tensor_names=tensor_names,
        data=tensors_to_save, name='save')
    return {
        "checkpoint_path": checkpoint_path
    }

  @tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])
  def restore(self, checkpoint_path):
    restored_tensors = {}
    for var in self.model.weights:
      restored = tf.raw_ops.Restore(
          file_pattern=checkpoint_path, tensor_name=var.name, dt=var.dtype,
          name='restore')
      var.assign(restored)
      restored_tensors[var.name] = restored
    return restored_tensors

fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()


train_images = (train_images / 255.0).astype(np.float32)
test_images = (test_images / 255.0).astype(np.float32)

train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

NUM_EPOCHS = 10
BATCH_SIZE = 100
epochs = np.arange(1, NUM_EPOCHS + 1, 1)
losses = np.zeros([NUM_EPOCHS])
m = Model()

train_ds = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_ds = train_ds.batch(BATCH_SIZE)

for i in range(NUM_EPOCHS):
  for x,y in train_ds:
    result = m.train(x, y)

  losses[i] = result['loss']
  if (i + 1) % 10 == 0:
    print(f"Finished {i+1} epochs")
    print(f"  loss: {losses[i]:.3f}")

# Save the trained weights to a checkpoint.
m.save('/tmp/model.ckpt')


SAVED_MODEL_DIR = "saved_model"

tf.saved_model.save(
    m,
    SAVED_MODEL_DIR,
    signatures={
        'train':
            m.train.get_concrete_function(),
        'infer':
            m.infer.get_concrete_function(),
        'save':
            m.save.get_concrete_function(),
        'restore':
            m.restore.get_concrete_function(),
    })

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]
converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()

##
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
# converter = tf.lite.TFLiteConverter.from_concrete_functions()
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]

converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()
f = open('test2.tflite','wb')
f.write(tflite_model)
f.close()
##

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

infer = interpreter.get_signature_runner("infer")


logits_original = m.infer(x=train_images[:1])['logits'][0]
logits_lite = infer(x=train_images[:1])['logits'][0]

print(logits_original,logits_lite)

train_ds = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_ds = train_ds.batch(BATCH_SIZE)

# for i in range(NUM_EPOCHS):
#   for x,y in train_ds:
#     result = m.train(x, y)
#
#   losses[i] = result['loss']
#   if (i + 1) % 10 == 0:
#     print(f"Finished {i+1} epochs")
#     print(f"  loss: {losses[i]:.3f}")

train = interpreter.get_signature_runner("train")

# train_loader = DataLoader(video_data[:(int)(video_data.__len__()*0.8)],label_data[:(int)(label_data.__len__()*0.8)],1)

for i in range(NUM_EPOCHS):
  for x,y in train_ds:
    x = tf.cast(x,tf.float32)
    y = tf.cast(y,tf.float32)
    result = train(x=x,y=y)
    print("train_finish")
    print(result)
`

**Comment by sushreebarsa** [comment]
@jvishnuvardhan  Was able to reproduce this issue on colab using TF v2.7.0 and tf-nightly(2.9.0-dev20220130) ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/31415cc59d2dc304629d02f5fa46d5dd/54001.ipynb#scrollTo=L__q4B26ZeRO) for reference.
Thanks!

**Comment by SpicyYeol** [comment]
@sushreebarsa Thanks for the answer. I tested my code with tf-nightly(2.9.0) and I confirmed training. Thanks.
My final goal is  train a 3D conv model on mobile using tflite. however, It already doesn't work yet.
Any plans for support to 3d models in the near future?

**Comment by MeghnaNatraj** [comment]
@haozha111 Triaging training related questions.
