### ISSUE TITLE
VARIABLES Collection name is deprecated, please use GLOBAL_VARIABLES instead

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/tensorflow#5404]
I pulled the latest HEAD a few mins ago and ran my code.  I started to get the listed error:

**WARNING:tensorflow:VARIABLES Collection name is deprecated, please use GLOBAL_VARIABLES instead.**
**VARIABLES will be removed after 2017-03-02**

I didn't fully debug all the causes but seems like there is errors thrown when the following lines are hit:

> from tensorflow.contrib.session_bundle import exporter

if I remove that line, it seems to move to another line building the graph, not sure if it is a "get_variables()" operation or something.  I don't use VARIABLES anywhere in  my code.  Given the "saver" below causing a similar issue, it is possible my "histogram_summary" or "scalar_summary" ops may have triggered this as well while building the graph.

The same error is printed on each iteration of "save()" with the saver, this really messes up my logging to the screen:
> save_path = saverRun.save(session, saveto)

Seems like something within the Saver and possibly the "variables" might need updating.

**Comment by aselle** [comment]
Assigning @ilblackdragon  since this is your CL. It looks like tensorflow.contrib is still touching the old all_variables instead of the new global_variables. Is it possible we could do a more replacement of everything within the tensorflow repository?

**Comment by aselle** [comment]
@martinwicke, do we have a policy on updating contrib when we do deprecations? It is definitely less supported, of course.

**Comment by ilblackdragon** [comment]
All the tensorflow internal usages were updated on Friday (https://github.com/tensorflow/tensorflow/commit/4cbdead95f22de74bcbc72a68c9a38d465202db9, https://github.com/tensorflow/tensorflow/commit/cbd3cacfb73bbea912b9d01c2540187684f751a7). There is a code in flight for printing location where deprecated function was called from.

**Comment by martinwicke** [comment]
Note also that this is only a warning, your code should continue working as before. 

In general, code is contrib can and will change at will. We're trying to be nice about it, but sometimes it's not possible. Not that in this instance, nothing should have been broken.

**Comment by aselle** [comment]
Thanks Martin and @ilblackdragon  and @martinwicke for the quick response.
