### ISSUE TITLE
allocate temp tensor would be free before the end of the aysnc gpu kernel  execution 

### ISSUE THREAD

**Issue by MichoChan** [tensorflow/tensorflow#54059]
https://github.com/tensorflow/tensorflow/blob/a9e4e55bcfaa95c40b36ef9c85991e3534532b2c/tensorflow/core/kernels/gpu_device_array.h#L83

**Comment by sushreebarsa** [comment]
@MichoChan Could you please include more details on the issue?
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!
