### ISSUE TITLE
Building Tensorflow lite from source: cannot fix unresolved external symbols in Visual Studio project

### ISSUE THREAD

**Issue by 4scastro** [tensorflow/tensorflow#54066]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Tensorflow lite (source)
- TensorFlow version: 2.7.0
- GCC/Compiler version (if compiling from source): MSVC 19.26.28806.0

**Describe the problem**

Building Tensorflow lite from source appears to work, in so far as I get the static libraries. However, when I create a Visual Studio project I get several linker errors (unresolved externals - see end of issue for error messages) and whatever libs I try to link, I cannot seem to get anything to build. I have followed the instructions for building the minimal example CMake project and **this appears to work**. However, we need to be able to link tensorflow lite in our application code which isn't managed with CMake, so using CMake isn't an option for us.

In a nutshell: the build process appears to work, but I can't seem to get a Visual Studio project set up. More details below.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Used this link as a guide: https://www.tensorflow.org/lite/guide/build_cmake
2. Cloned the tensorflow repo
3. Created a directory called "mybuild" at the top level of the repo
4. Opened a command prompt in mybuild and ran: `cmake ../tensorflow_src/tensorflow/lite`
5. Then ran: `cmake --build . -j`
6. Created a visual studio project console application (see hello world program below)
7. Set up the include directory to point to the tensorflow repo
8. Added tensorflow-lite.lib to the linker input options
9. Added the path to the lib in the additional linker directories
10. Built in x64, and tried both Debug and Release* - both resulted in the same linker error.
11. As a desperate measure, included all the libs in the _deps/ folder in the linker input options - still the same linker error

*I wasn't totally clear whether the lib I'd built was for Debug or Release. The instructions say "It generates an optimized release binary by default", but then the built lib ends up in mybuild/Debug which was confusing. Is this a minor bug in the build or are the instructions wrong in saying this?

Hope this is clear enough and I've posted in the right place. Any more info I can provide let me know, thanks.

**Sample code**
```
#include <iostream>
#include <tensorflow/lite/c/c_api.h>

int main()
{
	std::cout << "Hello from TensorFlow C library version " << TfLiteVersion() << std::endl;
	return 0;
}
```

**Build from sample project**
```
1>------ Build started: Project: ConsoleApplication2, Configuration: Release x64 ------
1>ConsoleApplication2.cpp
1>ConsoleApplication2.obj : error LNK2001: unresolved external symbol __imp_TfLiteVersion
1>C:\Users\4Sight\source\repos\ConsoleApplication2\x64\Release\ConsoleApplication2.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "ConsoleApplication2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by sachinprasadhs** [comment]
It could be due to the wrong choice of application type, make sure at the start of the application you choose Console Application instead of windows application for Visual Studio.
Start the process again with option something like. File -> New -> Project -> Win32 Console Application.

**Comment by 4scastro** [comment]
Having checked the project properties I can confirm it is a console application. If I comment out the Tflite line/header and put in a standard cout statement the console app builds and runs fine.

**Comment by 4scastro** [comment]
Mystery solved - we were trying to use the C API as opposed to the C++ binding. I was able to build and link the example code provided here without any significant problems: https://stackoverflow.com/a/56868813/1618009
