### ISSUE TITLE
LSTM slow to calibrate with large observation period

### ISSUE THREAD

**Issue by Raa23** [tensorflow/tensorflow#54085]
I am reporting an issue in the calibration speed of LSTM models with large observation period even though none of my resource is saturated (CPU, GPU, RAM, SSD)

**System information**
- OS Platform and Distribution: Win11
- TensorFlow installed from: `pip install tensorflow`
- TensorFlow version: 2.7 / GPU
- Python version: 3.9
- CUDA/cuDNN version: cuDNN 8201 (installed via `pip install tensorflow`), CUDA 11.4
- GPU model and memory: Geforce GTX 3060 4 Go / RAM 32 Go / CPU AMD Ryzen 5 / SSD

**Describe the current behavior**
None of the machine resource is saturated following LSTM calibration
`print(tf.config.list_physical_devices("GPU"))` shows that the calibration runs on the GPU as expected.

**Describe the expected behavior**
Any of the machine resource should be saturated

**Standalone code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

print(tf.config.list_physical_devices("GPU"))

if __name__ == "__main__":

    epoch = 10
    batch_size = 2000
    number_output = 3
    number_features = 5
    backward = 992
    number_node = 40

    def train_gen():
        for i in range(1000):
            yield np.random.random((batch_size, backward, number_features)),\
                  np.random.random((batch_size, number_output))

    train_dataset = tf.data.Dataset.from_generator(train_gen, output_types=(tf.float64, tf.float64))
    train_dataset = train_dataset.prefetch(tf.data.AUTOTUNE)

    drop_ratio = 0.2
    model = Sequential([layers.Input(shape=(backward, number_features))])
    model.add(layers.LSTM(number_node, return_sequences=False))
    model.add(layers.Dropout(drop_ratio))
    model.add(layers.Dense(number_output, activation='sigmoid'))
    model.compile(optimizer='adam', loss='mse')
    model.summary()

    history = model.fit(train_dataset, epochs=epoch)
```

**Other info / logs**
![image](https://user-images.githubusercontent.com/25941523/151064911-8f1ba15f-16d5-4b63-ad9b-ffb19eb9302e.png)

**Comment by mohantym** [comment]
Hi @Raa23 ! I was getting a slow processing time but memory usage  was saturated at end of training . Attaching [gist ](https://colab.sandbox.google.com/gist/mohantym/fac4737d22825e038a35295f898ce084/github_54085.ipynb#scrollTo=VJyqD-tDYQAA) and screenshot for reference.
![image](https://user-images.githubusercontent.com/86464649/151492436-13ed810a-48ed-45f1-9759-d124de245a05.png)

**Comment by Raa23** [comment]
Hello, thank you for your feedback but I see in the screenshot that the RAM (system and GPU) is not saturated, though I don't understand the reference.
I have tested the gist and it has the same behavior as in my local machine: nothing is saturated and the process is slow.
Is there any reason why to expect RAM to be saturated as the dataset is not cached ?
Also, should I request assistance in the Forum instead ?
Thanks

**Comment by mohantym** [comment]
@Raa23 ! 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) or TF forum.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!
