### ISSUE TITLE
Tensorflow restore memory leak

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#54086]
**System information**

- OS Platform and Distribution: MacOS Monterey 12.1
- TensorFlow installed: from binary
- TensorFlow version: The issue could be reproduced by v2.6.0
- Python version: 3.8.3

**Describe the current behavior**
I notice that Tensorflow (TF) leaks memory when I restore TF models. Specifically if I iteratively load model checkpoint from disk with TF restore API, the memory usage keeps growing no matter what I do `tf.reset_default_graph()` or `tf.keras.backend.clear_session()` or both (But it seems `tf.reset_default_graph()` and `tf.keras.backend.clear_session()` slow down the memory leak speed rate).

** Standalone code to reproduce the issue **
The issue could be reproduced as below. Run `tf_save_model.py` to create and save a model in the folder `./test_model_repro/` with the model name `foo`. Then run `tf_restore_model.py` to load the model iteratively. You would see after each iteration calling `restore()`, even if `tf.reset_default_graph()` and `tf.keras.backend.clear_session()` are being called, the log shows the memory usage keeps increasing.

tf_save_model.py
```
from typing import Tuple

import tensorflow.compat.v1 as tf
from tensorflow.keras import models
from tensorflow.keras import layers

tf.disable_v2_behavior()


def create_model() -> Tuple[tf.Tensor, tf.Tensor]:
    """
    Create a model with Neural-Net: 1024 x 1024
    """
    graph = tf.get_default_graph()
    with graph.as_default():
        # The Neural Net Size: 200 -> 1024 x 1024 -> 6
        model = models.Sequential()
        input_shape, hidden_shape, output_shape = 200, 1024, 6
        model.add(
            layers.Dense(
                hidden_shape,
                activation='tanh',
                input_shape=(input_shape,),
                name="layer0"
            )
        )
        model.add(layers.Dense(hidden_shape, activation='tanh', name="layer1"))
        model.add(layers.Dense(output_shape, activation='relu', name="final_layer"))
        input_tensor = tf.placeholder(dtype=tf.float32, shape=[None, input_shape])
        output_tensor = model(input_tensor)
    return input_tensor, output_tensor


def save_model(sess: tf.Session, path: str) -> None:
    """
    Save the TF model according to the path.
    """
    saver = tf.train.Saver()
    sess.run(tf.global_variables_initializer())
    save_path = saver.save(sess, path)
    print(f"Saved the model in {save_path}")


def main() -> None:
    input_tensor, output_tensor = create_model()
    print(
        f"Create the model with Input tensor {input_tensor} "
        f"and output tensor {output_tensor}."
    )
    sess = tf.Session()
    sess.run(tf.global_variables_initializer())
    save_model(sess, "./test_model_repro/foo")


main()
```

tf.restore_model.py
```
import os
import psutil

import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()


def _get_memory_rss() -> float:
    """
    Get the RSS memory value in GB.
    """
    return psutil.Process(os.getpid()).memory_info().rss / 1024 ** 3


def restore(path: str) -> tf.train.Saver:
    """
    Restores the TF graph from the path and returns the saver.
    """
    sess = tf.Session()
    saver = tf.train.import_meta_graph(f"{path}.meta")
    saver.restore(sess, path)


def main() -> None:
    init_prev = _get_memory_rss()
    for _ in range(10000):
        restore("./test_model_repro/foo")
        mem_after = _get_memory_rss() - init_prev
        print(
            f"The memory increased after restoring the TF model: {mem_after}"
        )
        tf.reset_default_graph()
        tf.keras.backend.clear_session()


main()
```
The issue could be 100% repro-d by the above Python scripts.

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf [v2.5](https://colab.research.google.com/gist/tilakrayal/61cfb2bcb6db7f15b18f939c0d45ded5/54086-2-5.ipynb),[v2.7](https://colab.research.google.com/gist/tilakrayal/e3ad29fcde5cb4fe5ddc2f05769db298/54086-2-7.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/aea162370bef4cb9a9968756a9bd9f3f/54086-nightly.ipynb).Please find the gist here.

**Comment by sachinprasadhs** [comment]
Hi did you try the same in eager mode and is there any specific reason you are testing it by using `tf.disable_v2_behavior()`

**Comment by RuofanKong** [comment]
Hi @sachinprasadhs We use the v1-compatible one and don't use the eager mode, due to our product spec in the current phase.

**Comment by exx8** [comment]
PING, it also affects me.

**Comment by jiujiuxia** [comment]
555...have you solved the problem?

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
