### ISSUE TITLE
no attribute '_register_wrapper_optimizer_cls' in python 3.8.12

### ISSUE THREAD

**Issue by jiku100** [tensorflow/tensorflow#54087]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.7.0
- Python version: 3.8.12
- Installed using virtualenv? pip? conda?: conda virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2/8.1.0
- GPU model and memory: RTX 3090 / 24GB

**Describe the problem**
I installed tensorflow 2.7.0 using pip with python 3.8.12. It imported fine in ubuntu 18.04.
However, as a result of doing the same in ubuntu 20.04, the import was not performed with an error such as "AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'".
I tried the same method in python 3.9.7 version just in case, but this time it was imported.
Therefore, I wonder why python 3.8.12 version can be done in ubuntu 18.04, but not in ubuntu 20.04.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
environment.yaml file
```
name: tf27
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.8.12
  - pip
  - pip:
    - lxml>=4.6.1
    - cython>=0.29.13 
    - absl-py>-0.10.0
    - matplotlib>=3.0.3
    - numpy>=1.19.4
    - Pillow>=6.0.0
    - pycocotools>=2.0
    - PyYAML>=5.1
    - six>=1.15.0
    - tensorflow>=2.7.0
    - tensorflow-addons>=0.15
    - tensorflow-hub>=0.11
    - neural-structured-learning>=1.3.1
    - opencv-python
    - tqdm
```
Then try 
```
import tensorflow
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Full error log below.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeron/anaconda3/envs/tf27/lib/python3.8/site-packages/tensorflow/__init__.py", line 479, in <module>
    keras._load()
  File "/home/zeron/anaconda3/envs/tf27/lib/python3.8/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/zeron/anaconda3/envs/tf27/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/metrics.py", line 27, in <module>
    from keras import activations
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/layers/__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/engine/base_layer.py", line 41, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/zeron/.local/lib/python3.8/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 1180, in <module>
    mixed_precision._register_wrapper_optimizer_cls(optimizer_v2.OptimizerV2,
AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'

**Comment by sushreebarsa** [comment]
@jiku100 Could you please check if  your cpu model  support AVX instructions sets?See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
Also, please follow the instructions from [Tensorflow website](https://www.tensorflow.org/install/source).
Please let us know if it helps?
Thanks!

**Comment by tobiaspiechowiak** [comment]
Hi all, 
I have the exactly same error - with almost the same system specifications. 
I haven't found a solution yet but my strong hunch is that it has something to do that TF is trying to use the .local python version _/home/zeron/.local/_  and not the one specified in the environment. This verison might than exhibit a compatibility issue with Keras.... Just a guess ;-). Let me know what you think.
