### ISSUE TITLE
iOS app size increasing

### ISSUE THREAD

**Issue by PahlevanyanSamvel** [tensorflow/tensorflow#54083]
Hey dear TensorFlow team.
I am using  following lib on my iOS application  `pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['Metal','CoreML']`
Every time when I am trying to read .tflite, my app size is increasing.
I discovered and found some interesting think inside the app container AppData->tmp 
<img width="1215" alt="Screen Shot 2022-01-25 at 22 45 39" src="https://user-images.githubusercontent.com/34054539/151039294-2bd9033f-f13f-4f39-93e1-ddc5da661d31.png">

Why does it create a Core ML Compiled Model each time and not be deleted after being freed?
Please  help me , this is a really blocker 🙏

**Comment by sushreebarsa** [comment]
@PahlevanyanSamvel 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
