### ISSUE TITLE
TF_OperationOutputType returns values not contained in TF_DataType

### ISSUE THREAD

**Issue by juraj-bicikl** [tensorflow/tensorflow#5409]
For example, if TF_OperationOutputType is used on a Variable node of 
type Double, the function returns value 102, which corresponds to DT_DOUBLE_REF
in protobuf DataType enum (types.proto). However, value 102 is not defined in 
TF_DataType enum (c_api.h).

This inconsistency can be easily avoided by using integers instead of TF_DataType enum,
however it should be probably fixed at some point.

**Comment by aselle** [comment]
Could you please take this bug on @josh11b. Thanks!

**Comment by asimshankar** [comment]
@juraj-bicikl : Could you elaborate a bit on your use of `TF_OperationOutputType`? Specifically, I'm wondering whether your use of the C API needs to care about reference types.

@alextp is in the process of changing how variables are used without references (using the `DT_RESOURCE` type) and perhaps it makes sense for `TF_OperationOutputType` to always return the type (so `DT_DOUBLE` and not `DT_DOUBLE_REF`) so that the notion of references remains internal to the runtime.

**Comment by juraj-bicikl** [comment]
So far, I have been using TF_OperationOutputType in the context of building a tensorflow 
graph. The function is useful when the type of the next node in the graph has to match 
the type of one of the previous nodes. The function enables me to figure out the type 
that I have to assign to the new node. 

For example, when implementing Adam optimizer, I have to define
two new variables (per each variable over which we optimize the cost) to keep track
of the mean and variance of the gradient. To create those "Variable" nodes, I have to know
the type, and for that I use TF_OperationOutputType. 

I haven't yet encountered a situation where it was important to me to distinguish 
between DT_FLOAT and DT_FLOAT_REF, or DT_DOUBLE and DT_DOUBLE_REF. 
Currently I am not aware of the case where this could be useful.

**Comment by asimshankar** [comment]
Thanks. I'll ask around to see what folks think about hiding the reference type and having `TF_OperationOutputType` return the non-reference type always and circle back.

**Comment by martinwicke** [comment]
This issue is quite old and hasn't had recent activity. If it is still not working in the latest version of TensorFlow, and please create a new bug. Thank you.
