### ISSUE TITLE
TFLite SignatureRunner support for the C API

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#54091]
**System information**
- TensorFlow version (you are using): 2.7 / tf-nightly
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The current TFLite interpreter C API allows using TFLite in situations where a stable ABI is needed and the C++ API is not an option. For example, in cases where TFLite needs to be used in bigger projects that cannot use bazel to build and might use different toolchains or incompatible C++ compiler settings.

However, while the C++ API already has support for multiple signatures [through the use of SignatureRunner](https://www.tensorflow.org/lite/guide/signatures#c), the C API has not been updated accordingly. As such, the use of multiple signatures in TFLite models is not possible if ABI stability requirements prevent you from using the C++ API directly.

**Will this change the current api? How?**
New APIs that allow using signature runners would need to be added [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h), or in a separate header if appropriate.

**Who will benefit with this feature?**
Anyone who needs stable ABIs and wants to run TFLite models with multiple signatures.

**Any Other info.**
As mentioned [here](https://www.tensorflow.org/lite/guide/signatures#known_limitations) this feature is not available _yet_, suggesting it's planned. I'm opening this feature request so that it's easier to track its status, as well as any kind of information on when it might be implemented.

**Comment by tilakrayal** [comment]
@leandro-gracia-gil ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by leandro-gracia-gil** [comment]
> @leandro-gracia-gil , Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

The feature is basically bring support for signature runners (what you can do [here](https://www.tensorflow.org/lite/guide/signatures#c) in C++) to the C API. There should already internal be support for this, but it's simply not yet exposed in the C API.

The use cases are using TFLite models that have more than a single TF function in situations where ABI stability issues don't allow you using the C++ API.

For example, I've tried integrating TFLite with big projects using Unreal Engine in Windows where it is not in my power to do things like enabling exceptions or making some changes in toolchain settings that affects the whole project. If you try to build a TFLite C++ dll separately using bazel and run it from this bigger project you often get ABI-related issues and crashes. Depending on what you do you can also be missing required C++ symbols due to the dll export limit of 64k functions. Trying to build everything on bazel, or to build TFLite using the Unreal Engine build system are not feasible options.

On the other hand, using a smaller C API dll provides a stable C ABI that avoids these issues, and makes it easier to get things working by building TFLite separately in bazel. But my TFLite models have more than a single TF function, so I need C APIs to be able to use the signature runners that already exist in C++.

**Comment by pjpratik** [comment]
Hi @leandro-gracia-gil 

The `SignatureRunner` support  for the C API has been implemented with the commit https://github.com/tensorflow/tensorflow/commit/3a6a6465c45797bd573c118a535405da43ab03fa

https://github.com/tensorflow/tensorflow/blob/48421345a02db49011cd4536285e76535c5d67c2/tensorflow/lite/core/c/c_api_experimental.cc#L166-L172

Could you please confirm the same?

Thanks.

**Comment by leandro-gracia-gil** [comment]
Hi @pjpratik 

I haven't got the time to try the API myself, but this seems to be precisely what I was asking.
Thanks!

**Comment by pjpratik** [comment]
Hi @leandro-gracia-gil 

Thanks. Feel free to close the issue since it is resolved.

**Comment by Nenteru** [comment]
Hi, everybody! 
Can you tell me how to use this API? Which version (which tag) should I build? In which public dependencies will the implementation be located?

**Comment by Nenteru** [comment]
I downloaded and compiled the sources of TensorFlow Lite C API, along with 'c_api_experimental'.

Now I have a question, but how to use it? Is there a guide on this topic, I will be very grateful for your help!
