### ISSUE TITLE
tf.keras.metrics.get raise error for None

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54117]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
print(tf.keras.losses.get(None))
print(tf.keras.metrics.get(None)) # Fail
```
Outputs:
```
None
ValueError: Could not interpret metric identifier: None
```

**Expected output**
According to the document [tf.keras.metrics.get](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/get?hl=en), the `identifier` is "One of None or string name of a metric function/class or metric configuration dictionary or a metric function or a metric class instance". So do we expect the output to be `None` when `identifier` is `None` like `tf.keras.losses.get`?

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky ,
Please post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by Yashashree304** [comment]
There's a minor error in the source code. I am trying to fix it and created a new pr for the same.
