### ISSUE TITLE
Docker images for Tensorflow 2.6.2 are missing

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#54122]
TensorFlow 2.6.2 was released, but I cannot find docker images for TF 2.6.2 in docker hub.

https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=2.6.2

<img width="1262" alt="스크린샷 2022-01-27 오전 11 30 59" src="https://user-images.githubusercontent.com/8815362/151281339-8b1cad3d-fae3-4526-888e-a3536e151dc9.png">

**Comment by sachinprasadhs** [comment]
Since it is similar to `Tensorflow version 2.6.1`, the docker Images for version `2.6.2` are not included in docker hub. 
You can use the equivalent Images for `2.6.2` with `2.6.1`.

**Comment by jeongukjae** [comment]
@sachinprasadhs Thank you for the response!
