### ISSUE TITLE
tf.histogram_fixed_width_bins miss input check for `nbins`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54125]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
value_range = [0.0, 5.0]
new_values = [-1.0, 0.0, 1.5, 2.0, 5.0, 15]
indices = tf.histogram_fixed_width_bins(new_values, value_range, nbins=-5)
indices.numpy()
```
Outputs:
```
array([0, 0, 0, 0, 0, 0], dtype=int32)
```
**Expected output**
Expected nbins to be a positive interger, and raise an error if it's negative.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?  Attaching gist in [2.6](https://colab.sandbox.google.com/gist/mohantym/38dd66c557d5f77993144919b11f653b/github_54125.ipynb#scrollTo=fxuWOtXR_aPE) and [2.7](https://colab.sandbox.google.com/gist/mohantym/6942139dfd2218e14af74cccea8db259/github_54125.ipynb) , [2.8](https://colab.sandbox.google.com/gist/mohantym/17c5b2aa7cbf28f9b59de73a92ec858e/github_54125.ipynb#scrollTo=fxuWOtXR_aPE) for reference.
