### ISSUE TITLE
StudentT.cdf() bug

### ISSUE THREAD

**Issue by icouckuy** [tensorflow/tensorflow#5413]
With the TF0.11 rc2 (also with rc0) I get the following error while trying to evaluate the CDF of the StudentT distribution:
```
----> 1 a.cdf(5.0)

/home/ilm/.local/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/distribution.pyc in cdf(self, value, name)
    496         values of type `self.dtype`.
    497     """
--> 498     self._check_hasattr(self._cdf)
    499     with self._name_scope(name, values=[value]):
    500       value = ops.convert_to_tensor(value, name="value")

AttributeError: 'StudentT' object has no attribute '_cdf'

```
Is the CDF of StudentT supported? According to the docs it should:
https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.distributions.html#StudentT

MWE:
```
import tensorflow as tf
a = tf.contrib.distributions.StudentT(5.0, 0.0, 1.0)
a.cdf(5.0)
```

**Comment by aselle** [comment]
It's not implemented as of nightly.
``` 
>>> import tensorflow as tf
>>> a = tf.contrib.distributions.StudentT(5.0, 0.0, 1.0)
>>> a.cdf(5.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/python/ops/distribution.py", line 706, in cdf
    raise original_exception
NotImplementedError: cdf is not implemented
```
Contributions are welcome.  From @brianwa84's original checkin:
```
Adds Student's t distribution to tf.contrib.distributions
Leaving out the cdf for now, as it requires incomplete beta, not available in eigen at the moment.
```

**Comment by icouckuy** [comment]
Ok thanks, I was confused because the documentation says otherwise.

It seems Eigen now implements the (regularized) incomplete beta, both for cpu and gpu:
https://eigen.tuxfamily.org/dox-devel/group__CoeffwiseMathFunctions.html
https://bitbucket.org/eigen/eigen/pull-requests/190/add-ternaryfunctors-and-the-betainc/diff

Not sure if it is in stable Eigen yet, have to check.

**Comment by jvdillon** [comment]
On Mon, Nov 7, 2016 at 1:00 PM, icouckuy <notifications@github.com> wrote:

> Ok thanks, I was confused because the documentation says otherwise.
>

Hi there!  Sorry for the confusion and troubles!

We regard base class distribution as being somewhat like an abstract base
class which lists the properties a distribution *might* have.  In the
latest release (and indeed for some time now) a call to an unsupported
function should trigger NotImplementedError or an exception indicating
something along the lines of "cannot be implemented."


> It seems Eigen now implements the (regularized) incomplete beta, both for
> cpu and gpu:
> https://eigen.tuxfamily.org/dox-devel/group__CoeffwiseMathFunctions.html
> https://bitbucket.org/eigen/eigen/pull-requests/190/add-
> ternaryfunctors-and-the-betainc/diff
>
> Not sure if it is in stable Eigen yet, have to check.
>
I opened a bug to implement student's t cdf now that betainc is supported.
We should be able to get this in reasonably quickly.

**Comment by finbarrtimbers** [comment]
Has this been assigned to anyone? I want to start contributing to tensorflow and am looking for a bug to work on.

**Comment by brianwa84** [comment]
Go for it, instructions here:
https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

Brian Patton | Software Engineer | bjp@google.com | +1 (360) 903-9003

**Comment by finbarrtimbers** [comment]
Sounds good. On it.

**Comment by gunan** [comment]
Looks like this is just closed today.
