### ISSUE TITLE
TensorFLow Lite version for iOS through POD

### ISSUE THREAD

**Issue by mercksamir** [tensorflow/tensorflow#54133]
Hi folks,

Can anyone please let us know what is the latest TensorFlow lite version available for iOS through PODs. In the example, it is mentioned that the latest version for TensorFLow lite is 1.13.1. 

What is the latest TensorFlow lite version that we can use with TensorFlow version 2.6.0?

<img width="1340" alt="Screenshot 2022-01-27 at 10 52 12 AM" src="https://user-images.githubusercontent.com/98508996/151297127-95b22550-8b43-474a-835c-026cc22bd482.png">

**Comment by tilakrayal** [comment]
@mercksamir ,
Please take a look at this [link](https://www.tensorflow.org/lite/guide/build_ios) for the installation of TensorflowLite for iOS.It helps.Thanks!

**Comment by mercksamir** [comment]
@tilakrayal - Thanks but can you please confirm the latest version available for 'TensorFlow' lite POD for iOS? Not for ObjC and Swift POD.

**Comment by sachinprasadhs** [comment]
The file which you are referring to is old one and will be removed in future, for IOS examples you can check  https://www.tensorflow.org/lite/examples.
The Tensorflow Lite version you can use with TensorFlow 2.6 is  2.6. Thanks!
