### ISSUE TITLE
Warning Tensorflow: "Invalid GPU Compute Capability"

### ISSUE THREAD

**Issue by jcnew07** [tensorflow/tensorflow#54143]
Hi...i have  this warning Tensorflow: 

"Invalid GPU Compute Capability"

Att. 
Jcnew07

**Comment by mohantym** [comment]
Hi @jcnew07 ! Minimum Gpu compute capability is 3.5 . Attaching relevant [thread](https://www.tensorflow.org/install/gpu#hardware_requirements) for reference. Thank you!
