### ISSUE TITLE
how to run distributed version on mutiple CPUs but not GPUs. 

### ISSUE THREAD

**Issue by younfor** [tensorflow/tensorflow#5414]
when i run scripts like follows:
CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=192.168.1.100:2222 --worker_hosts=192.168.1.100:2224,192.168.1.100:2225 --job_name=ps --task_index=0

CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=192.168.1.100:2222 --worker_hosts=192.168.1.100:2224,192.168.1.100:2225 --job_name=worker --task_index=0

CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=192.168.1.100:2222 --worker_hosts=192.168.1.100:2224,192.168.1.100:2225 --job_name=worker --task_index=1 

terminal will not start , I am confused. when I change one of the CUDA_VISIBLE_DEVICES=''  to CUDA_VISIBLE_DEVICES=0,  it works .  But I need just CPUs without a GPU

**Comment by aselle** [comment]
Please resubmit your issue, filling in the required information from github template. In particular, provide any error messages and details about your environment.
