### ISSUE TITLE
tensorflow-cpu 2.7.0 missing from conda-forge

### ISSUE THREAD

**Issue by brsolomon-deloitte** [tensorflow/tensorflow#54154]
`tensorflow-cpu` 2.7.0 is [present on PyPI](https://pypi.org/project/tensorflow-cpu/) as of now but [missing from conda-forge](https://anaconda.org/conda-forge/tensorflow-cpu), where latest is 2.6.2.

**Comment by sachinprasadhs** [comment]
The Tensorflow releases made on `PyPI` is maintained by Tensorflow but the Tensorflow releases made on `conda-forge` is a community build releases. 
Usually these community builds are done by `TensorFlow Special Interest Groups (SIGs)` and these [community builds ](https://github.com/tensorflow/build#community-supported-tensorflow-builds)are not supported by Tensorflow.

You can see the overview and details about the Community supported Tensorflow builds and releases [here](https://github.com/tensorflow/community/blob/master/sigs/build/community-builds.md). Thanks!
