### ISSUE TITLE
TFLITE conversion Failed - Custom Model

### ISSUE THREAD

**Issue by raminmohammadi** [tensorflow/tensorflow#54155]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installation (pip package or built from source): Pip
- TensorFlow installation (pip package or built from source): tensorflow==2.8.0-rc0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
Reference [TensorFlow Lite Model Colab]: https://colab.research.google.com/drive/1crWPg__nYgt5IUFOA_OzgU0qgvgzmsZc?usp=sharing

### 3. Failure after conversion
conversion Fails when adding the "update_control_variate" function.

### 4. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

2022-01-27 11:53:08.600343: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:357] Ignored output_format.
2022-01-27 11:53:08.600385: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored drop_control_dependency.
2022-01-27 11:53:08.600602: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: saved_model
2022-01-27 11:53:08.647834: I tensorflow/cc/saved_model/reader.cc:78] Reading meta graph with tags { serve }
2022-01-27 11:53:08.647877: I tensorflow/cc/saved_model/reader.cc:119] Reading SavedModel debug info (if present) from: saved_model
2022-01-27 11:53:08.787707: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-01-27 11:53:09.230312: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: saved_model
2022-01-27 11:53:09.631676: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 1031073 microseconds.
2022-01-27 11:53:10.288551: E tensorflow/compiler/mlir/tensorflow/translate/tf_mlir_translate.cc:207] SavedModel V1 import failed: FAILED_PRECONDITION: Graph does not contain node: 

---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
/tmp/ipykernel_5933/617434638.py in <module>
     10 converter.experimental_new_converter = True
     11 converter.allow_custom_ops = True
---> 12 tflite_model = converter.convert()

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in convert(self)
   1712         Invalid quantization parameters.
   1713     """
-> 1714     return super(TFLiteConverterV2, self).convert()
   1715 
   1716 

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in wrapper(self, *args, **kwargs)
    801   def wrapper(self, *args, **kwargs):
    802     # pylint: disable=protected-access
--> 803     return self._convert_and_export_metrics(convert_func, *args, **kwargs)
    804     # pylint: enable=protected-access
    805 

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in _convert_and_export_metrics(self, convert_func, *args, **kwargs)
    787     self._save_conversion_params_metric()
    788     start_time = time.process_time()
--> 789     result = convert_func(self, *args, **kwargs)
    790     elapsed_time_ms = (time.process_time() - start_time) * 1000
    791     if result:

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in convert(self)
   1371     """
   1372     if self.experimental_lower_to_saved_model:
-> 1373       saved_model_convert_result = self._convert_as_saved_model()
   1374       if saved_model_convert_result:
   1375         return saved_model_convert_result

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in _convert_as_saved_model(self)
   1351       if self.saved_model_dir:
   1352         self._validate_inputs(graph_def, input_tensors)
-> 1353         return self._convert_from_saved_model(graph_def)
   1354     finally:
   1355       shutil.rmtree(temp_dir, True)

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/lite.py in _convert_from_saved_model(self, graph_def)
    965     converter_kwargs.update(quant_mode.converter_flags())
    966 
--> 967     result = _convert_saved_model(**converter_kwargs)
    968     return self._optimize_tflite_model(
    969         result, quant_mode, quant_io=self.experimental_new_quantizer)

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py in wrapper(*args, **kwargs)
    211         else:
    212           report_error_message(str(converter_error))
--> 213         raise converter_error from None  # Re-throws the exception.
    214       except Exception as error:
    215         report_error_message(str(error))

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py in wrapper(*args, **kwargs)
    204     def wrapper(*args, **kwargs):
    205       try:
--> 206         return func(*args, **kwargs)
    207       except ConverterError as converter_error:
    208         if converter_error.errors:

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/convert.py in convert_saved_model(**kwargs)
    787   model_flags = build_model_flags(**kwargs)
    788   conversion_flags = build_conversion_flags(**kwargs)
--> 789   data = convert(
    790       model_flags.SerializeToString(),
    791       conversion_flags.SerializeToString(),

~/anaconda3/envs/tf_2.8/lib/python3.9/site-packages/tensorflow/lite/python/convert.py in convert(model_flags_str, conversion_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    304       for error_data in _metrics_wrapper.retrieve_collected_errors():
    305         converter_error.append_error(error_data)
--> 306       raise converter_error
    307 
    308   return _run_deprecated_conversion_binary(

ConverterError: Graph does not contain node:

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue ? Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/0b6470da4eb662ffeb93cf0d52cfbae3/test_mode.ipynb#scrollTo=Nbvrn_9uaCSY) for reference.

**Comment by raminmohammadi** [comment]
Any updates on this one? Is this a bug or an error from my side?

**Comment by raminmohammadi** [comment]
Any update here? I really would appreciate it if you could provide some answers.

**Comment by MeghnaNatraj** [comment]
Hello @raminmohammadi, this will take a longer to debug, please give us a few days to take a look and get back to you.

**Comment by raminmohammadi** [comment]
Thanks

**Comment by raminmohammadi** [comment]
@MeghnaNatraj Any updates on this ticket?

**Comment by MeghnaNatraj** [comment]
@raminmohammadi could you update the gist and fix the errors on cell 8, 9 and 10?

**Cell 8**

```
signatures = [
  m.train.get_concrete_function(),
  m.infer.get_concrete_function(),
  m.save.get_concrete_function(),
  m.restore.get_concrete_function(),
  m.get_the_update.get_concrete_function(),
  m.update_control_variate.get_concrete_function()               
]
    
converter = tf.lite.TFLiteConverter.from_concrete_functions(signatures, m) 
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.
    tf.lite.Optimize.DEFAULT
]
converter.target_spec.supported_types = [tf.float32]
converter.experimental_enable_resource_variables = True
converter.experimental_new_converter = True
converter.allow_custom_ops = True
tflite_model = converter.convert()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-10-7df60c3cf334>](https://localhost:8080/#) in <module>()
     18 converter.experimental_new_converter = True
     19 converter.allow_custom_ops = True
---> 20 tflite_model = converter.convert()

6 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py](https://localhost:8080/#) in _freeze_concrete_function(self)
   1390 
   1391     if len(self._funcs) > 1:
-> 1392       raise ValueError("This converter can only convert a single "
   1393                        "ConcreteFunction. Converting multiple functions is "
   1394                        "under development.")

ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

**Cell 9**
```
SAVED_MODEL_DIR = "saved_model"

tf.saved_model.save(
    m,
    SAVED_MODEL_DIR,
    signatures={
        'train':
            m.train.get_concrete_function(),
        'infer':
            m.infer.get_concrete_function(),
        'save':
            m.save.get_concrete_function(),
        'restore':
            m.restore.get_concrete_function(),
        'get_the_update':
            m.get_the_update.get_concrete_function(),
        'update_control_variate':
            m.update_control_variate.get_concrete_function()
    })
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-b5016c469a88>](https://localhost:8080/#) in <module>()
     16             m.get_the_update.get_concrete_function(),
     17         'update_control_variate':
---> 18             m.update_control_variate.get_concrete_function()
     19     })
     20 

18 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/signature_serialization.py](https://localhost:8080/#) in _normalize_outputs(outputs, function_name, signature_key)
    217     if not isinstance(value, (ops.Tensor, composite_tensor.CompositeTensor)):
    218       raise ValueError(
--> 219           f"Got a non-Tensor value {value!r} for key {key!r} in the output of "
    220           f"the function {compat.as_str_any(function_name)} used to generate "
    221           f"the SavedModel signature {signature_key!r}. "

ValueError: in user code:


    ValueError: Got a non-Tensor value <tf.Operation 'PartitionedCall' type=PartitionedCall> for key 'output_0' in the output of the function __inference_update_control_variate_8606 used to generate the SavedModel signature 'update_control_variate'. Outputs for functions used as signatures must be a single Tensor, a sequence of Tensors, or a dictionary from string to Tensor.
```

**Cell 10**
```
# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.
    tf.lite.Optimize.DEFAULT
]
converter.target_spec.supported_types = [tf.float32]
converter.experimental_enable_resource_variables = True
converter.experimental_new_converter = True
converter.allow_custom_ops = True
tflite_model = converter.convert()
```
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-11-ca397ff95c32>](https://localhost:8080/#) in <module>()
      1 # Convert the model
----> 2 converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
      3 converter.target_spec.supported_ops = [
      4     tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
      5     tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.

4 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/loader_impl.py](https://localhost:8080/#) in parse_saved_model(export_dir)
    114   else:
    115     raise IOError(
--> 116         f"SavedModel file does not exist at: {export_dir}{os.path.sep}"
    117         f"{{{constants.SAVED_MODEL_FILENAME_PBTXT}|"
    118         f"{constants.SAVED_MODEL_FILENAME_PB}}}")

OSError: SavedModel file does not exist at: saved_model/{saved_model.pbtxt|saved_model.pb}
```

**Comment by raminmohammadi** [comment]
@MeghnaNatraj its updated now.

**Comment by raminmohammadi** [comment]
@MeghnaNatraj Can you look into this? I assume 3 months waiting period for a help is fair :)

**Comment by raminmohammadi** [comment]
@sachinprasadhs - Can you look into this?

**Comment by karimnosseir** [comment]
The failure is coming from importing the saved model.
Can you try running the model after saving.
Mainly
1) Save
2) Load
3) Run

The issue looks like it is coming from 'update_control_variate'

And verify that it load and run (Steps 2,3) for multiple signature.

**Comment by raminmohammadi** [comment]
@karimnosseir 
Please refer to this [Colab](https://colab.research.google.com/drive/1D46HsEnbgw2GvB4oq5ahhVRdAfH4Msu2?usp=sharing) I did follow your comments and once devloped a model without update_control_variate function and was able to convert it to tflite and after that i was able to test all the concrete functions within the model as you can see in the Notebook.

Then i added the update_control_variate function and tried to convert the model and that when I get the error that 
"ConverterError: Graph does not contain node"

**Comment by karimnosseir** [comment]
I meant in TF, so test in TF by loading the saved model in TF and then running it and make sure 'update_control_variate' works in TF then call the convert.

Thanks

**Comment by raminmohammadi** [comment]
I have tested the model in TF and it does work, I only have problem with conversion.

**Comment by karimnosseir** [comment]
The test in the colab is before saving. I don't see any tests similar to my request in the earlier comment.
Please update the colab to run in the sequence i mentioned above.

1) Save the model in Saved model format.
2) Load the saved model in TF.
3) Verify all the signatures saved in TF after loading from step 2.

Thanks

**Comment by raminmohammadi** [comment]
I did update the [colab](https://colab.research.google.com/drive/1rvqIo7Zgh1H-x6q98bfcz2xnVGbdB6Iu?usp=sharing) and have the following results within:

1. Trained the model without "update_control_variate" function and save it in Saved model format.
2. Load the model back and tested all the functions
3. saved the model in TFLITE and loaded back
4. Tested all the concrete functions
5. Trained the model with "update_control_variate" function and save it in Saved model format.
6. Load the model back and tested all the functions even the "update_control_variate" function
7. Tried to save the model to TFLITE and it produced "ConverterError: Graph does not contain node: "

**Comment by karimnosseir** [comment]
Thanks for the update. Will update the issue after we check the failure and reproduce code.

**Comment by raminmohammadi** [comment]
@karimnosseir! Any update on the above? Also, the ticket is labeled as stale!!

**Comment by raminmohammadi** [comment]
@karimnosseir - Just wanted to check in on the status of this ticket. Appreciate your understanding, this bug is currently a blocker for me.

**Comment by karimnosseir** [comment]
@raminmohammadi I had a deeper look, your last signature that fails are because 2 of the outputs are composite tensors - probably ragged tensors.

Is it possible to update your model to avoid using composite tensors.

**Comment by karimnosseir** [comment]
Below are the inputs and outputs of the signature

format is 
<name_as_in_signaturedef> <space> <tensor name> 
except when it is composite the proto in text format is printed.
```
signature inputs

labels update_control_variate_labels:0
x_case update_control_variate_x_case:0
x_chars update_control_variate_x_chars:0

signature outputs

output_9 StatefulPartitionedCall_5:17
output_4 StatefulPartitionedCall_5:10
output_1 StatefulPartitionedCall_5:3
output_7 StatefulPartitionedCall_5:15
output_12 StatefulPartitionedCall_5:6
output_5 composite tensor
type_spec 	 {
  type_spec_class: INDEXED_SLICES_SPEC
  type_state {
    tuple_value {
      values {
        tensor_shape_value {
          dim {
            size: -1
          }
          dim {
            size: 3
          }
        }
      }
      values {
        tensor_dtype_value: DT_FLOAT
      }
      values {
        tensor_dtype_value: DT_INT32
      }
      values {
        tensor_dtype_value: DT_INT32
      }
      values {
        tensor_shape_value {
          dim {
            size: -1
          }
        }
      }
    }
  }
  type_spec_class_name: "IndexedSlicesSpec"
  num_flat_components: 3
}
components {
  name: "StatefulPartitionedCall_5:11"
  dtype: DT_FLOAT
  tensor_shape {
    dim {
      size: -1
    }
    dim {
      size: 3
    }
  }
}
components {
  name: "StatefulPartitionedCall_5:12"
  dtype: DT_INT32
  tensor_shape {
    dim {
      size: -1
    }
  }
}
components {
  name: "StatefulPartitionedCall_5:13"
  dtype: DT_INT32
  tensor_shape {
    dim {
      size: 2
    }
  }
}

output_3 StatefulPartitionedCall_5:9
output_13 StatefulPartitionedCall_5:7
output_0 composite tensor
type_spec 	 {
  type_spec_class: INDEXED_SLICES_SPEC
  type_state {
    tuple_value {
      values {
        tensor_shape_value {
          dim {
            size: -1
          }
          dim {
            size: 156
          }
        }
      }
      values {
        tensor_dtype_value: DT_FLOAT
      }
      values {
        tensor_dtype_value: DT_INT32
      }
      values {
        tensor_dtype_value: DT_INT32
      }
      values {
        tensor_shape_value {
          dim {
            size: -1
          }
        }
      }
    }
  }
  type_spec_class_name: "IndexedSlicesSpec"
  num_flat_components: 3
}
components {
  name: "StatefulPartitionedCall_5:0"
  dtype: DT_FLOAT
  tensor_shape {
    dim {
      size: -1
    }
    dim {
      size: 156
    }
  }
}
components {
  name: "StatefulPartitionedCall_5:1"
  dtype: DT_INT32
  tensor_shape {
    dim {
      size: -1
    }
  }
}
components {
  name: "StatefulPartitionedCall_5:2"
  dtype: DT_INT32
  tensor_shape {
    dim {
      size: 2
    }
  }
}

output_2 StatefulPartitionedCall_5:8
output_8 StatefulPartitionedCall_5:16
output_11 StatefulPartitionedCall_5:5
output_10 StatefulPartitionedCall_5:4
output_6 StatefulPartitionedCall_5:14
```

**Comment by karimnosseir** [comment]
@joker-eph The model shared here fails during saved model to TF importing, looks like coming from a composite tensor.
Mehdi can you please have a look ?

Thanks

**Comment by raminmohammadi** [comment]
Can you elaborate how to avoid using composite tensors? the function is returning the gradients after one epoch of learning, so the composite tensor is being generated within the gradient tape module.

**Comment by raminmohammadi** [comment]
@joker-eph can you please look into this ticket! Tnx

**Comment by mohantym** [comment]
@raminmohammadi ! 
Sorry for the inconvenience. Error slightly changed  after removing tf.lite.optimize.default from converter.target_spec.supported_ops   . It is throwing multiple concrete functions is not supported now.   You have to experiment with concrete functions and converter flags a bit ( like removing  4 other signature and  changing leftover concrete functions declared, see the warnings for hint) . Will update from my side too.


Attached [gist](https://colab.sandbox.google.com/gist/mohantym/b1f7ff992de7510823951405e3b11df6/test_mode.ipynb#scrollTo=n8tQ-LwOIXSQ) for reference

Thank you!

**Comment by raminmohammadi** [comment]
@mohantym 
Thanks for the response! I did experiment with the concrete functions and the tf.lite.optimize.default flag. I am still able to convert the model if i remove m.update_control_variate.get_concrete_function() from the signatures and the error happens as soon as i add this function.

**Comment by mohantym** [comment]
Hi @raminmohammadi !
It seems to be resolving in 2.10 version . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/2c22a263b374cb8b988c3485ad06c43f/test_mode.ipynb#scrollTo=xCtyT2cJwUu3) for reference.
Could you let us know from your end.
Thank you!

**Comment by raminmohammadi** [comment]
@mohantym 
I just checked with TF=2.10 version and the issue still persist. See the [gist](https://colab.research.google.com/drive/1YvIH5FesoP-eMz0m__39aprevvg20CSR?usp=sharing)

In your example the signature was commented out:
`signatures = [
  m.train.get_concrete_function(),
  m.infer.get_concrete_function(),
  m.save.get_concrete_function(),
  m.restore.get_concrete_function(),
  m.get_the_update.get_concrete_function(),
  # m.update_control_variate.get_concrete_function() This signature is the one that causing the error
] `

thanks

**Comment by pjpratik** [comment]
I was able to replicate this issue on TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/f8926221271b44c9ebd5b40193d72e44/54155.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi @majiddadashi, can you please take a look? Thanks.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by raminmohammadi** [comment]
This issue is still ongoing, tested with the latest TF version and same error. 
https://colab.research.google.com/drive/1crWPg__nYgt5IUFOA_OzgU0qgvgzmsZc?usp=sharing#scrollTo=9j4MGqyKQEo4

**Comment by pkgoogle** [comment]
Reopening as requested.

**Comment by pkgoogle** [comment]
Hi @raminmohammadi, Tensorflow and Keras has change significantly from even the last 2.11 gist, can you try adjusting what you are doing here to the modern APIs and see if you can convert properly?

**Comment by raminmohammadi** [comment]
Just verified with Tensorflow 2.15 and the issue persists. https://colab.research.google.com/drive/1crWPg__nYgt5IUFOA_OzgU0qgvgzmsZc?usp=sharing#scrollTo=7k4QfC3cE6RQ

**Comment by pkgoogle** [comment]
Hi @raminmohammadi, we're wondering if you may be able to resolve your issue by using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), our PyTorch conversion library, you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

It seems you are working with an NLP model here. We actually have examples of converting and quantizing decoder-only LLMs here: https://github.com/google-ai-edge/ai-edge-torch/tree/main/ai_edge_torch/generative/examples.

If the conversion is successful, you can also try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repo. Thanks for your help.

**Comment by raminmohammadi** [comment]
@pkgoogle could you please clarify why to use a pytorch converter on tensorflow model?

**Comment by raminmohammadi** [comment]
@pkgoogle thanks i will give it a try.
