### ISSUE TITLE
UnsupportedWheel: tensorflow-0.11.0rc2-cp27-cp27mu-linux_x86_64.whl

### ISSUE THREAD

**Issue by lan2720** [tensorflow/tensorflow#5415]
Hi all,

I'm updating my tensorflow from r0.10 to r0.11 or the master, but after I run the cmd:
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```
I just got a `tensorflow-0.11.0rc2-cp27-cp27mu-linux_x86_64.whl` instead of `tensorflow-0.11.0rc2-py2-none-any.whl`. And this file always caused an `UnsupportedWheel` error when I run pip install. 

This is the pip.log:
```
------------------------------------------------------------
/usr/bin/pip run on Sat Nov  5 16:59:34 2016
tensorflow-0.11.0rc2-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: tensorflow-0.11.0rc2-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
```

Operating system: Ubuntu 14.04
Kernel release: 4.4.0-45-generic
Cuda toolkit: 8.0.44
cuDNN: 5.1.5
GPU: GTX 1080
bazel version: 0.4.0
gcc and g++: 4.8.5
python: 2.7.6

I wonder what  `cp27-cp27mu` means and why I can't get an supported .whl file?

**Comment by Lass3** [comment]
Same problem with the downloadable on page: https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html

Ubuntu 16.04, kernel 4.4.0-45, CUDA 8.0.44, gcc 5.4.0, python 2.7.12 : 
$ sudo -H pip install --upgrade tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl
tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
$

But "parallel" python 3.5 file works in my python3 setup:
$ sudo -H pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc2-cp35-cp35m-linux_x86_64.whl
...
Successfully installed numpy-1.11.2 protobuf-3.0.0 setuptools-28.8.0 tensorflow-0.11.0rc2
$

**Comment by caisq** [comment]
Renaming the wheel to `tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl` should address the problem.
Can you give it a try?

**Comment by girving** [comment]
@aselle What's with the tag fight?

**Comment by ahmedammar** [comment]
@caisq yup that fixes it for me

**Comment by aselle** [comment]
The tag fight was due to a bug in github that marked the "awaiting response" as coming from the original poster rather than the person that did it (me).

**Comment by caisq** [comment]
I'm closing this issue for now. For future reference:
There is a script that takes care of the pip wheel renaming automatically:

E.g.,
tensorflow/tools/ci_build/ci_build.sh CPU tensorflow/tools/ci_build/builds/pip.sh CPU
tensorflow/tools/ci_build/ci_build.sh GPU tensorflow/tools/ci_build/builds/pip.sh GPU

For more details see:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build
