### ISSUE TITLE
Why the parameter size of mobilenetv3 in 2.7.0 is different from nightly?

### ISSUE THREAD

**Issue by molvcan** [tensorflow/tensorflow#54163]
<em>
</em>
The number of parameters of MobileNetv3Small(alpha=1) in tf=2.7.0 is 1.5M, while it is 0.9M in tf-nightly. 

The same code was used to load the MobileNetV3Small model.

`
base_model =keras.applications.MobileNetV3Small(input_shape=(384, 512, 3),include_top=False,weights='imagenet',)
base_model.summary()
`

I saw that some layers were deleted in tf-nightly. Why is that?

![image](https://user-images.githubusercontent.com/41880345/151437092-63762b58-5bca-4ca7-9409-2146ed80631e.png)

**Comment by mohantym** [comment]
Hi @molvcan ! 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!
