### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: UnboundedIndexRangeEncode. number 3 (UnboundedIndexRangeEncode) failed to prepare. Node number 108 (WHILE) failed to invoke.

### ISSUE THREAD

**Issue by prmudgal** [tensorflow/tensorflow#54164]
**### 1. System information**

Linux
TF 2.7.0
### 2. Code

**Command used to run the converter or code if you’re using the Python API**

Converter:

  import argparse
  import io
  import os
  import sys
  import urllib
  from absl import app
  from absl.flags import argparse_flags
  import cv2
  import numpy as np
  import tensorflow.compat.v1 as tf
  
  #import tensorflow as tf
  from tensorflow.python import pywrap_tensorflow
  import tensorflow_compression as tfc  # pylint:disable=unused-import
  
  
  
  
  with tf.Session() as sess:
          saver = tf.train.import_meta_graph('/mnt/6t_hdd/Priyanka/hific-lo.metagraph')
          #saver.restore(sess, latest_checkpoint_path)
          inputs=None
          outputs=None
          signature='sender'
          request = urllib.request.urlopen('file:///mnt/6t_hdd/Priyanka/hific-lo.metagraph') # replace it with your local path and model
          try:
                  string = request.read()
          finally:
                  request.close()
  
          metagraph = tf.compat.v1.MetaGraphDef()
          loaded = metagraph.ParseFromString(string)
  
          wrapped_import = tf.compat.v1.wrap_function(lambda: tf.compat.v1.train.import_meta_graph('/mnt/6t_hdd/Priyanka/hific-lo.metagraph'), [])
          graph = wrapped_import.graph
          print("*************************************")
          inputs = metagraph.signature_def['sender'].inputs
          print(inputs)
          concrete_function =  metagraph.signature_def['sender']
          print("$$$$$$$$$$")
          inputs = [graph.as_graph_element(inputs[k].name) for k in sorted(inputs)]
          print(inputs)
          outputs = metagraph.signature_def[signature].outputs
          print(outputs)
          outputs = [graph.as_graph_element(outputs[k].name) for k in sorted(outputs)]
          print("*************************************")
          converter = tf.lite.TFLiteConverter.from_session(sess, inputs, outputs)
          converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
          converter.allow_custom_ops = True
          converter.optimizations = [tf.lite.Optimize.DEFAULT]
          tflite_model = converter.convert()
          open("/mnt/6t_hdd/Priyanka/converted_model_fp16.tflite", "wb").write(tflite_model) # replace the path with your local path

Here, i get the warning for custom ops as below - 
Custom ops: UnboundedIndexRangeDecode, UnboundedIndexRangeEncode
Details:
        tf.UnboundedIndexRangeDecode(tensor<*x!tf_type.string>, tensor<?x?x320xi32>, tensor<320x48xi32>, tensor<320xi32>, tensor<320xi32>) -> (tensor<?x?x320xi32>) : {debug_level = 0 : i64, device = "", overflow_width = 4 : i64, precision = 16 : i64}
        tf.UnboundedIndexRangeEncode(tensor<*xi32>, tensor<*xi32>, tensor<64x1481xi32>, tensor<64xi32>, tensor<64xi32>) -> (tensor<!tf_type.string>) : {debug_level = 0 : i64, device = "", overflow_width = 4 : i64, precision = 16 : i64}
        tf.UnboundedIndexRangeEncode(tensor<*xi32>, tensor<?x?x320xi32>, tensor<320x48xi32>, tensor<320xi32>, tensor<320xi32>) -> (tensor<!tf_type.string>) : {debug_level = 0 : i64, device = "", overflow_width = 4 : i64, precision = 16 : i64}
See instructions: https://www.tensorflow.org/lite/guide/ops_custom

Inference:

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="./model.tflite")
interpreter.allocate_tensors()
print("all ok")

# # Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# # Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# # The function `get_tensor()` returns a copy of the tensor data.
# # Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

*The output from the converter invocation*

Traceback (most recent call last):
  File "load_tflite.py", line 31, in <module>
    interpreter.invoke()
  File "/home/marlin/anaconda/envs/prune/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 923, in invoke
    self._interpreter.Invoke()
RuntimeError: Encountered unresolved custom op: UnboundedIndexRangeEncode.
See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 3 (UnboundedIndexRangeEncode) failed to prepare.
Node number 108 (WHILE) failed to invoke.

I'm wondering why the flex delegate couldn't prepare the UnboundedIndexRangeEncode function, even though I have the SELECT_TF_OPS flag enabled?

**Comment by tilakrayal** [comment]
@prmudgal ,
While executing the given code i was facing different error.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/ed5f93dbeace20ae3f146ca8f3819dc1/untitled203.ipynb).In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by prmudgal** [comment]
@tilakrayal 
the error is because of missing model. You can find the trained model [here ](https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-lo.metagraph)
Dataset - [Coco2014](https://cocodataset.org/#home)

Although the error is because of missing Custom op. Is it possible to add "UnboundedIndexRangeEncode" in custom op?

**Comment by tilakrayal** [comment]
@prmudgal ,
The code provided is fairly complex hence it would be difficult for us to pinpoint the issue. Could you please get the example down to the simplest possible repro? That will allow us to determine the source of the issue easily. Thanks!

**Comment by prmudgal** [comment]
Code is updated. Please see the it in original comment. Download the model from [here ](https://storage.googleapis.com/tensorflow_compression/metagraphs/hific-lo.metagraph).

**Comment by prmudgal** [comment]
I updated the code in colab, please see the gist [here](https://colab.research.google.com/gist/prmudgal/a8080494c3e554da70e55abc1acdc5e3/untitled203.ipynb)

**Comment by prmudgal** [comment]
Is there any update on this issue?

**Comment by tilakrayal** [comment]
@prmudgal ,
Looks like this is not a bug  related to Tensorflow end.Please take a look this issue [1](https://github.com/tensorflow/compression/issues/22) and [2](https://github.com/tensorflow/compression/issues/32) from the compression repo and try to post in respective repo from [here](https://github.com/tensorflow/compression/issues).It helps.Thanks

**Comment by prmudgal** [comment]
@tilakrayal Thanks for the suggestion. Tensorflow compression suggestion is to include it as custom op in TFLite. Please see [here](https://github.com/tensorflow/compression/issues/119#issuecomment-1029331406). It will be helpful if TFLite team can support to include this as custom op.

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I have tried in colab with TF version v2.5, v2.7 and nightly version and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/b88eb4cdbee6c90015cc76dc2415ee8f/54164.ipynb). Thanks!

**Comment by prmudgal** [comment]
Is there any update on this?

**Comment by prmudgal** [comment]
@sachinprasadhs following up on this issue.

**Comment by MeghnaNatraj** [comment]
Hello @prmudgal The TF version of the op can in included in the TFLite model if it's in the [TFLite Allowlist](https://www.tensorflow.org/lite/guide/op_select_allowlist). Refer to [this FAQ](https://www.tensorflow.org/lite/guide/faq#why_are_some_operations_not_implemented_in_tensorflow_lite). If not, you would have to create your own custom op or you can [request an op via a Github issue](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=comp%3Alite&template=40-tflite-op-request.md). Before you request a new op, check if there [existing issues](https://github.com/tensorflow/tensorflow/issues?q=label%3Acomp%3Alite+) with the same request and comment on it with your request details.
