### ISSUE TITLE
Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)

### ISSUE THREAD

**Issue by knkumar** [tensorflow/tensorflow#54172]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Monterey 12.1 on M1 Chip
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.5.4
- Python version: 3.6.12
- Installed using virtualenv? pip? conda?: Yes pipenv
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): Apple clang version 13.0.0 (clang-1300.0.29.30) aka 4.2.1
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**
Build fails with linker error - pointer not aligned at address
`tensorflow/tensorflow/python/BUILD:4936:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)`

```
ld: warning: cannot export hidden symbol unsigned int
std::__1::__sort5<std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, tensorflow::tfprof::CodeNode**>
(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> >
tensorflow::tfprof::TFMultiShow::SortNodes<tensorflow::tfprof::CodeNode>(std::__1::vector<tensorflow::tfprof::CodeNode*,
std::__1::allocator<tensorflow::tfprof::CodeNode*> > const&,
tensorflow::tfprof::Options const&)::'lambda'
(tensorflow::tfprof::CodeNode const*, tensorflow::tfprof::CodeNode
const*)&, tensorflow::tfprof::CodeNode) from
bazel-out/host/bin/tensorflow/core/profiler/internal/libtfprof_code.a
(tfprof_code.o)
```
The same error repeats for `tfprof_graph` and `tfprof_op`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow && git checkout tags/v1.5.4
./configure
bazel build //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Please see attachment**
[build_fail.txt](https://github.com/tensorflow/tensorflow/files/7960509/build_fail.txt)

**Comment by tilakrayal** [comment]
@knkumar ,
We see that you are using tf version 1.5, 1.x is not actively supported, please update to latest stable v2.7 and let us know if you are facing same issue.Also Please refer to similar issues #44751,#47782 and for installation please take a look at this [link](https://github.com/apple/tensorflow_macos). It helps.
