### ISSUE TITLE
AttributeError: 'float' object has no attribute 'dtype',  When executing tfp.optimizer.differential_evolution_one_step

### ISSUE THREAD

**Issue by Northerneye** [tensorflow/tensorflow#54187]
This error is shown whenever tf.optimizer.differential_evolution_one_step is called.

This error is due to line 125 in the tensorflow optimizer file differential_evolution.py, which is,
crossover_prob=0.9

In this line, the variable crossover_prob is given as a float whereas it is required to be a tensorflow variable later in the file on line 652, which is,
dtype=crossover_prob.dtype.base_dtype,

changing crossover_prob to a tf.Variable before line 652 will solve this problem.
Also, setting the default value of crossover_prob in line 125 from
crossover_prob=0.9, to
crossover_prob=tf.Variable(0.9)
will also solve this problem and allow for this function to run.

Thank you

**Comment by Cheril311** [comment]
Made a PR

**Comment by mohantym** [comment]
Hi @Northerneye ! Please post this issue in [Tensorflow probability](https://www.tensorflow.org/probability) repo too. Thank you!

**Comment by Cheril311** [comment]
@mohantym have already submitted a PR for the same should I update it or something as you assigned a label afterwards

**Comment by mohantym** [comment]
Hi @Cheril311 !  It is fine in pull request side.  Thank you!

**Comment by mohantym** [comment]
Hi @Northerneye ! Have you checked in 2.8/Nightly version yet? [Ref](https://github.com/tensorflow/probability/pull/1506#issuecomment-1026528109).

**Comment by Northerneye** [comment]
I had not but it seems that the problem must have already been fixed?

**Comment by mohantym** [comment]
Ok @Northerneye ! Please move the issue to closed status if it has been resolved in latest versions. Thanks!
