### ISSUE TITLE
NameError: Exception encountered when calling layer "lambda_1" (type Lambda).

### ISSUE THREAD

**Issue by izainpasha** [tensorflow/tensorflow#54198]
`if __name__ == "__main__":
    (x_train, y_train, groups_train), (x_test, y_test, groups_test) = load_data()
    
    model = load_model(os.path.join("/content/drive/MyDrive/models", "model.h5"))
    model.summary()

    print("training:")
    y_true, y_pred = y_train, np.argmax(model.predict(x_train, batch_size=1024, verbose=1), axis=-1)

    C = confusion_matrix(y_true, y_pred, labels=(1, 0))
    TP, TN, FP, FN = C[0, 0], C[1, 1], C[1, 0], C[0, 1]
    acc, sn, sp = 1. * (TP + TN) / (TP + TN + FP + FN), 1. * TP / (TP + FN), 1. * TN / (TN + FP)
    print("acc: {}, sn: {}, sp: {}".format(acc, sn, sp))

    print("testing:")
    y_true, y_pred = y_test, np.argmax(model.predict(x_test, batch_size=1024, verbose=1), axis=-1)

    C = confusion_matrix(y_true, y_pred, labels=(1, 0))
    TP, TN, FP, FN = C[0, 0], C[1, 1], C[1, 0], C[0, 1]
    acc, sn, sp = 1. * (TP + TN) / (TP + TN + FP + FN), 1. * TP / (TP + FN), 1. * TN / (TN + FP)
    print("acc: {}, sn: {}, sp: {}".format(acc, sn, sp))`
![image](https://user-images.githubusercontent.com/86849708/151673124-81fbe818-87c8-4285-b1db-e944da943eca.png)

**Comment by Cheril311** [comment]
@izainpasha can you please elaborate your issue?

**Comment by tilakrayal** [comment]
Looks like the error is due to providing wrong naming conventions.Thanks!

**Comment by izainpasha** [comment]
> @izainpasha , In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.Also please try to execute the code with full code by following indentation and naming conventions.It helps.Thanks!

import pickle

import numpy as np
import os
from keras.models import load_model
from scipy.interpolate import splev, splrep
from sklearn.metrics import confusion_matrix

base_dir = "dataset"

ir = 3
before = 2
after = 2

# normalize
scaler = lambda arr: (arr - np.min(arr)) / (np.max(arr) - np.min(arr))


def load_data():
    tm = np.arange(0, (before + 1 + after) * 60, step=1 / float(ir))

    with open(os.path.join(base_dir, "apnea-ecg.pkl"), 'rb') as f:
        apnea_ecg = pickle.load(f)

    x_train = []
    o_train, y_train = apnea_ecg["o_train"], apnea_ecg["y_train"]
    groups_train = apnea_ecg["groups_train"]
    for i in range(len(o_train)):
        (rri_tm, rri_signal), (ampl_tm, ampl_siganl) = o_train[i]
        rri_interp_signal = splev(tm, splrep(rri_tm, scaler(rri_signal), k=3), ext=1)
        ampl_interp_signal = splev(tm, splrep(ampl_tm, scaler(ampl_siganl), k=3), ext=1)
        x_train.append([rri_interp_signal, ampl_interp_signal])
    x_train = np.array(x_train, dtype="float32").transpose((0, 2, 1))
    y_train = np.array(y_train, dtype="float32")

    x_test = []
    o_test, y_test = apnea_ecg["o_test"], apnea_ecg["y_test"]
    groups_test = apnea_ecg["groups_test"]
    for i in range(len(o_test)):
        (rri_tm, rri_signal), (ampl_tm, ampl_siganl) = o_test[i]
        rri_interp_signal = splev(tm, splrep(rri_tm, scaler(rri_signal), k=3), ext=1)
        ampl_interp_signal = splev(tm, splrep(ampl_tm, scaler(ampl_siganl), k=3), ext=1)
        x_test.append([rri_interp_signal, ampl_interp_signal])
    x_test = np.array(x_test, dtype="float32").transpose((0, 2, 1))
    y_test = np.array(y_test, dtype="float32")

    return (x_train, y_train, groups_train), (x_test, y_test, groups_test)


if __name__ == "__main__":
    (x_train, y_train, groups_train), (x_test, y_test, groups_test) = load_data()

    model = load_model(os.path.join("./models", "model.final.h5"))
    model.summary()

    print("training:")
    y_true, y_pred = y_train, np.argmax(model.predict(x_train, batch_size=1024, verbose=1), axis=-1)

    C = confusion_matrix(y_true, y_pred, labels=(1, 0))
    TP, TN, FP, FN = C[0, 0], C[1, 1], C[1, 0], C[0, 1]
    acc, sn, sp = 1. * (TP + TN) / (TP + TN + FP + FN), 1. * TP / (TP + FN), 1. * TN / (TN + FP)
    print("acc: {}, sn: {}, sp: {}".format(acc, sn, sp))

    print("testing:")
    y_true, y_pred = y_test, np.argmax(model.predict(x_test, batch_size=1024, verbose=1), axis=-1)

    C = confusion_matrix(y_true, y_pred, labels=(1, 0))
    TP, TN, FP, FN = C[0, 0], C[1, 1], C[1, 0], C[0, 1]
    acc, sn, sp = 1. * (TP + TN) / (TP + TN + FP + FN), 1. * TP / (TP + FN), 1. * TN / (TN + FP)
    print("acc: {}, sn: {}, sp: {}".format(acc, sn, sp))

Here is the full Code snippet I've my trained model saved in drive and the Tensorflow is 1.15.2

**Comment by izainpasha** [comment]
> error is due to providing wrong naming

Can you please check where the issue is? Cause I've rewrite it several times and can't find where the naming issue

**Comment by izainpasha** [comment]
> @izainpasha can you please elaborate your issue?

I'm trying to load my model but it is showing nameerror of K that haven't been used in the whole code

**Comment by tilakrayal** [comment]
@izainpasha ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to latest stable v2.7 and let us know if you are facing same issue.

**Comment by RandomAnass** [comment]
I had the same problem while using a lambda layer. I suppose the saved model they are using has some custom lambda layer.

Here is a similar error, from a reproducible example:

```
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Lambda,Flatten

def dummy_padding(x, padding_size):
    return tf.pad(x, [[0, 0], [padding_size, padding_size], [padding_size, padding_size], [0, 0]], mode='SYMMETRIC')

def dummy_nn(n_hidden, kernel_size=28, padding_size=5):
    model = Sequential()
    model.add(Lambda(lambda x: dummy_padding(x, padding_size), input_shape=(28, 28, 1)))
    model.add(Flatten())
    model.add(Dense(10))
    return model

model_ = dummy_nn(500)

tf.keras.models.save_model(model_, 'model_.h5')
model_.summary()
```
Output:
```Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 lambda (Lambda)             (None, 38, 38, 1)         0         
                                                                 
 flatten (Flatten)           (None, 1444)              0         
                                                                 
 dense (Dense)               (None, 10)                14450     
                                                                 
=================================================================
Total params: 14,450
Trainable params: 14,450
Non-trainable params: 0
```


Then the model can be used
```
import tensorflow as tf
model2_ = tf.keras.models.load_model('model_.h5')
model2_.summary()
```

```
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 lambda (Lambda)             (None, 38, 38, 1)         0         
                                                                 
 flatten (Flatten)           (None, 1444)              0         
                                                                 
 dense (Dense)               (None, 10)                14450     
                                                                 
=================================================================
Total params: 14,450
Trainable params: 14,450
Non-trainable params: 0
```

Now to use the model later (outside, or after restarting the kernel), the code:
```
import tensorflow as tf
model2_ = tf.keras.models.load_model('model_.h5')
model2_.summary()`
raises this error:
```
```
NameError: Exception encountered when calling layer "lambda" (type Lambda).

name 'dummy_padding' is not defined

Call arguments received by layer "lambda" (type Lambda):
  • inputs=tf.Tensor(shape=(None, 28, 28, 1), dtype=float32)
  • mask=None
  • training=None`
```
A possible workaround is **defining the lamda function before loading the model**. 
```
import tensorflow as tf

def dummy_padding(x, padding_size):
    return tf.pad(x, [[0, 0], [padding_size, padding_size], [padding_size, padding_size], [0, 0]], mode='SYMMETRIC')

model2_ = tf.keras.models.load_model('model_.h5')
model2_.summary()
```

```
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 lambda (Lambda)             (None, 38, 38, 1)         0         
                                                                 
 flatten (Flatten)           (None, 1444)              0         
                                                                 
 dense (Dense)               (None, 10)                14450     
                                                                 
=================================================================
Total params: 14,450
Trainable params: 14,450
Non-trainable params: 0
_________________________________________________________________
```
An other reproducible example that raises the same error can be found here [keras-raises-an-exception-on-loading-a-lambda-layer](https://stackoverflow.com/questions/65883675/keras-raises-an-exception-on-loading-a-lambda-layer) @tilakrayal
