### ISSUE TITLE
TensorFlowLite CocoaPod v1.13.1 throwing error EXC_BAD_ACCESS on iOS 

### ISSUE THREAD

**Issue by mercksamir** [tensorflow/tensorflow#54195]
** System Information

- iOS App built using React Native v0.61.2 (iOS v15.2)
- Installed TensorFlowLite POD v1.13.1
- Getting this error while inputing tensor model to interpreter

int32_t lengthInputTensor = tflInterpreter->input_tensor(0)->dims->data[1];

<img width="837" alt="Screenshot 2022-01-29 at 12 44 34 PM" src="https://user-images.githubusercontent.com/98508996/151651883-c0ad5965-ed1b-489a-b050-d77fbb498ac1.png">

<img width="888" alt="Screenshot 2022-01-29 at 12 44 02 PM" src="https://user-images.githubusercontent.com/98508996/151651891-50d13594-aa52-4a46-883a-a0ddd5d53113.png">

**Comment by tilakrayal** [comment]
@mercksamir ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Also please try with latest stable v2.7 and let us know if you are facing same issue.Thanks!
