### ISSUE TITLE
Is there any way to decrease tensorflow lite invoke time on windows 10 ?  

### ISSUE THREAD

**Issue by sazzad15-1779** [tensorflow/tensorflow#54206]
**System information**
- windows 10, x64
- TensorFlow version: 2.7.0
- Python version: 3.9.5
- Bazel version : 3.7.2
- GCC/Compiler version : 11.2.0
- xnnpack : enable

I run a custom CNN tflite model on tensorflow lite using c++ where  i got invoke time 2.5 second and same tensorflow model version i run on python where i got 1.19 second . As i know c++ is more faster than python then what is the issue ?
Note : because of commercial reason i can't give the code snapshot.

**Comment by tilakrayal** [comment]
@sazzad15-1779 ,
This question is better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.
