### ISSUE TITLE
partially initialized module 'tensorflow' has no attribute 'Tensor' (most likely due to a circular import)

### ISSUE THREAD

**Issue by jpiedrafita** [tensorflow/tensorflow#54208]
**System information**
- Running code from: https://github.com/jpiedrafita/ai_number_read/blob/main/numbers.py
❯pyhton3 numbers.py

- OS Platform and Distribution: OSX 10.15.7

- TensorFlow installed from: pip install tensorflow
As described in other "has no attribute" issues I tried other tf versions using
pip install tensorflow==x.x.x --ignore-installed

- TensorFlow version (use command below):

❯ pip show tensorflow
Name: tensorflow
Version: 2.7.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, keras-preprocessing, libclang, numpy, opt-einsum, protobuf, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wheel, wrapt
Required-by:

❯ pip show tensorflow_datasets
Name: tensorflow-datasets
Version: 4.5.0
Summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
Home-page: https://github.com/tensorflow/datasets
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: absl-py, dill, numpy, promise, protobuf, requests, six, tensorflow-metadata, termcolor, tqdm
Required-by:

- Python version 3.9.6

**Describe the current behavior**
Console error: 
https://github.com/jpiedrafita/ai_number_read/blob/main/traceback.txt
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tensorflow_datasets/core/utils/type_utils.py", line 49, in <module>
    Tensor = Union[tf.Tensor, tf.SparseTensor, tf.RaggedTensor]
AttributeError: partially initialized module 'tensorflow' has no attribute 'Tensor' (most likely due to a circular import)

In my code ther isn't any Tensor reference that could make a circular import.

**Describe the expected behavior**
Simple console output similar to:
>Resultado: 0.974

**Standalone code to reproduce the issue**
https://github.com/jpiedrafita/ai_number_read/blob/main/numbers.py)

**Other info / logs**

**Comment by tilakrayal** [comment]
@jpiedrafita ,
Can you please confirm whether you have installed tensorflow from this [link](https://www.tensorflow.org/install).If not please try to follow the doc and let us know if you are facing same issue.Thanks!

**Comment by tilakrayal** [comment]
@jpiedrafita ,
I was facing different issue while executing the mentioned code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/70e4f71dd0752233472a87ab0b0a772f/untitled208.ipynb).
