### ISSUE TITLE
clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'

### ISSUE THREAD

**Issue by fushwLZU** [tensorflow/tensorflow#54219]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows11
- Bazel version (if compiling from source): 4.2.2

**Describe the problem**
    I want to build tensorflowLite from source, I use this command: `bazel build -c opt --fat_apk_cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite`,  and it occurs this error:

`ERROR: D:/desktop/ky/tensorflow-master/tensorflow/lite/kernels/internal/BUILD:838:11: Compiling tensorflow/lite/kernels/internal/mfcc.cc failed: (Exit 1): clang failed: error executing command
  cd C:/users/25486/_bazel_25486/v4xxzvgh/execroot/org_tensorflow
  SET ANDROID_BUILD_TOOLS_VERSION=30.0.3
    SET ANDROID_NDK_API_LEVEL=21
    SET ANDROID_NDK_HOME=D:/SoftWare/Andriod/ndk/21.4.7075529
    SET ANDROID_SDK_API_LEVEL=29
    SET ANDROID_SDK_HOME=D:/SoftWare/Andriod
    SET PATH=D:\SoftWare\Msys2\usr\bin;D:\SoftWare\Msys2\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\SoftWare\Python\Scripts\;D:\SoftWare\Python\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\SoftWare\Xshell\;D:\SoftWare\WinSCP\WinSCP\;D:\SoftWare\mingw64\bin;D:\SoftWare\Cmake\bin;D:\SoftWare\Ninja;D:\SoftWare\Andriod\platform-tools;D:\SoftWare\Git\Git\cmd;D:\SoftWare\Gradle\gradle-6.8.3\bin;D:\SoftWare\bazel;D:\SoftWare\Java\jdk1.8.0_202\bin;C:\Users\25486\AppData\Local\Microsoft\WindowsApps;D:\SoftWare\Bandizip\;D:\SoftWare\VSCode\Microsoft VS Code\bin;D:\SoftWare\mingw64\bin;D:\SoftWare\Java\jdk1.8.0_202\bin;
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/SoftWare/Python/python.exe
    SET PYTHON_LIB_PATH=D:/SoftWare/Python/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -D__ANDROID_API__=21 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.d -frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.o -fPIC -iquote . -iquote bazel-out/android-armeabi-v7a-opt/bin -iquote external/fft2d -iquote bazel-out/android-armeabi-v7a-opt/bin/external/fft2d /W0 /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /experimental:preprocessor /d2ReducedOptimizeHugeFunctions /std:c++14 -DFARMHASH_NO_CXX_STRING -mfpu=neon -O3 -ffunction-sections -fdata-sections -fno-exceptions --sysroot=external/androidndk/ndk/platforms/android-21/arch-arm -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/lite/kernels/internal/mfcc.cc -o bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.o
Execution platform: @local_execution_config_platform//:platform
clang: error: no such file or directory: '/W0'

clang: error: no such file or directory: '/D_USE_MATH_DEFINES'

clang: error: no such file or directory: '/experimental:preprocessor'

clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'

clang: error: no such file or directory: '/std:c++14'

Target //tensorflow/lite/java:tensorflow-lite failed to build
INFO: Elapsed time: 21.998s, Critical Path: 17.47s
INFO: 95 processes: 73 internal, 22 local.
FAILED: Build did NOT complete successfully`

I have installed visual studio 2019, but in the error info above, I gusess the reason may be it can't find the visual studio??  please help...

**Comment by sushreebarsa** [comment]
@fushwLZU 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by VV20192019** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows11
> * Bazel version (if compiling from source): 4.2.2
> 
> **Describe the problem** I want to build tensorflowLite from source, I use this command: `bazel build -c opt --fat_apk_cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite`, and it occurs this error:
> 
> `ERROR: D:/desktop/ky/tensorflow-master/tensorflow/lite/kernels/internal/BUILD:838:11: Compiling tensorflow/lite/kernels/internal/mfcc.cc failed: (Exit 1): clang failed: error executing command cd C:/users/25486/_bazel_25486/v4xxzvgh/execroot/org_tensorflow SET ANDROID_BUILD_TOOLS_VERSION=30.0.3 SET ANDROID_NDK_API_LEVEL=21 SET ANDROID_NDK_HOME=D:/SoftWare/Andriod/ndk/21.4.7075529 SET ANDROID_SDK_API_LEVEL=29 SET ANDROID_SDK_HOME=D:/SoftWare/Andriod SET PATH=D:\SoftWare\Msys2\usr\bin;D:\SoftWare\Msys2\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\SoftWare\Python\Scripts;D:\SoftWare\Python;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;D:\SoftWare\Xshell;D:\SoftWare\WinSCP\WinSCP;D:\SoftWare\mingw64\bin;D:\SoftWare\Cmake\bin;D:\SoftWare\Ninja;D:\SoftWare\Andriod\platform-tools;D:\SoftWare\Git\Git\cmd;D:\SoftWare\Gradle\gradle-6.8.3\bin;D:\SoftWare\bazel;D:\SoftWare\Java\jdk1.8.0_202\bin;C:\Users\25486\AppData\Local\Microsoft\WindowsApps;D:\SoftWare\Bandizip;D:\SoftWare\VSCode\Microsoft VS Code\bin;D:\SoftWare\mingw64\bin;D:\SoftWare\Java\jdk1.8.0_202\bin; SET PWD=/proc/self/cwd SET PYTHON_BIN_PATH=D:/SoftWare/Python/python.exe SET PYTHON_LIB_PATH=D:/SoftWare/Python/lib/site-packages SET RUNFILES_MANIFEST_ONLY=1 SET TF2_BEHAVIOR=1 external/androidndk/ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/clang -D__ANDROID_API__=21 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.d -frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.o -fPIC -iquote . -iquote bazel-out/android-armeabi-v7a-opt/bin -iquote external/fft2d -iquote bazel-out/android-armeabi-v7a-opt/bin/external/fft2d /W0 /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /experimental:preprocessor /d2ReducedOptimizeHugeFunctions /std:c++14 -DFARMHASH_NO_CXX_STRING -mfpu=neon -O3 -ffunction-sections -fdata-sections -fno-exceptions --sysroot=external/androidndk/ndk/platforms/android-21/arch-arm -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/lite/kernels/internal/mfcc.cc -o bazel-out/android-armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/mfcc.pic.o Execution platform: @local_execution_config_platform//:platform clang: error: no such file or directory: '/W0'
> 
> clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
> 
> clang: error: no such file or directory: '/experimental:preprocessor'
> 
> clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'
> 
> clang: error: no such file or directory: '/std:c++14'
> 
> Target //tensorflow/lite/java:tensorflow-lite failed to build INFO: Elapsed time: 21.998s, Critical Path: 17.47s INFO: 95 processes: 73 internal, 22 local. FAILED: Build did NOT complete successfully`
> 
> I have installed visual studio 2019, but in the error info above, I gusess the reason may be it can't find the visual studio?? please help...

hi,  
I have the same problem. Have you solved it? clang.exe: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'

**Comment by sushreebarsa** [comment]
@VV20192019 Could you please create a new issue with all the information as this ticket is closed and it would be difficult for us to track here.Thank you!
