### ISSUE TITLE
Tensorboard: This site can’t be reached localhost refused to connect.

### ISSUE THREAD

**Issue by faizan1234567** [tensorflow/tensorflow#54211]
Hey everyone! I am training my model, when I use !tensorborad logdir=runs, it shows a link( http://localhost:6006/). When I click on this link it shows this site cant be reached. I don't what's wrong? I tried some solutions suggested at this site. But nothing worked for me.

**Comment by faizan1234567** [comment]
I am using pytorch for training. And i am training it on google colab.

**Comment by unrealwill** [comment]
Hello, 

You probably need to open a ssh tunnel to route the 6006 port of the remote server to your localhost 6006 port :
https://stackoverflow.com/questions/37987839/how-can-i-run-tensorboard-on-a-remote-server

Alternatively there also exist a --bind_all option to tensorboard when the machine you are running is not the machine you use to consult, (but you will need to do some port forwarding, and it will be accessible to everyone, so it's mainly useful for local networks that you trust).

**Comment by tilakrayal** [comment]
@faizan1234567 ,
Please take a look at this link [1](https://github.com/tensorflow/tensorboard/issues/2481) and [2](https://stackoverflow.com/questions/40106949/unable-to-open-tensorboard-in-browser) with the similar error.It helps.Thanks!

**Comment by BrunoV21** [comment]
Deleting the contents of the .tensorboard-info folder solves the issue. One way to automate the process is doing that in python prior to launching a new TensorBoard instance:

`path_tensorboard_cache = 'C:\\Users\\GL504GS\\AppData\\Local\\Temp\\.tensorboard-info'

print("Files in Tensor Board cache directory -->", os.listdir(path_tensorboard_cache))

for file in os.listdir(path_tensorboard_cache):
    print(f'{file} sucessfully removed')
    os.remove(f'{path_tensorboard_cache}\\{file}')
        
%load_ext tensorboard
%tensorboard --logdir logs   `
