### ISSUE TITLE
Tensorflow Object detection AI

### ISSUE THREAD

**Issue by Annieliaquat** [tensorflow/tensorflow#54215]
0

I am using Tensorflow model zoo object detection. SSD MobileNet V2 FPNLite 320x320 is the model I am using to train my model. Everything goes well my model starts training but I receive some weird msgs. I don't why this msg is showing up.

I think half of my model is training on GPU and then it is switching to CPU but I am not sure.

Here are the msgs that are showing up.

2022-01-30 19:30:21.237816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9971 MB memory: -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6 INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',) I0130 19:30:21.241063 140126199379776 mirrored_strategy.py:376] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)

After this it is showing me the following msgs.

INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',). I0130 19:30:43.470607 140126199379776 cross_device_ops.py:619] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).

Here is my GPU information.

![image](https://user-images.githubusercontent.com/43025113/151710543-0dcf2f72-94ec-465f-bb08-f12dfa2815fb.png)

Please someone help me with this. I have been struggling for weeks.

**Comment by tilakrayal** [comment]
@Annieliaquat ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.

**Comment by dagresearch** [comment]
we have the same issues. I am trying to run an object detection model with TensorFlow.

**Comment by Annieliaquat** [comment]
So someone plz answer if there is any solution.

**Comment by Annieliaquat** [comment]
My error is solved now.. I wrote the folder's name wrong. My folder is models/workspace/my-ssd-mobnet and I wrote it as models/workspace/my_ssd_mobnet

**Comment by mohantym** [comment]
Hi @Annieliaquat ! It seems you are using distribution strategy for your code. Those warning are expected to be coming while running the code in [distribution computing](https://www.tensorflow.org/guide/distributed_training#:~:text=Overview-,tf.,code%20with%20minimal%20code%20changes.). Can you please provide a stand alone code to reproduce this issue?

**Comment by Annieliaquat** [comment]
> Hi @Annieliaquat ! It seems you are using distribution strategy for your code. Those warning are expected to be coming while running the code in [distribution computing](https://www.tensorflow.org/guide/distributed_training#:~:text=Overview-,tf.,code%20with%20minimal%20code%20changes.). Can you please provide a stand alone code to reproduce this issue?

Thank you so much the problem is solved now.

**Comment by Annieliaquat** [comment]
> @Annieliaquat , Glad the issue is resolved for you, please feel free to move this to closed status.

Can you also answer me that is Image Data generator is used in Tensorflow object detection API?

**Comment by Annieliaquat** [comment]
> Hi @Annieliaquat ! It seems you are using distribution strategy for your code. Those warning are expected to be coming while running the code in [distribution computing](https://www.tensorflow.org/guide/distributed_training#:~:text=Overview-,tf.,code%20with%20minimal%20code%20changes.). Can you please provide a stand alone code to reproduce this issue?

Can you also answer me that is Image Data generator is used in Tensorflow object detection API??

**Comment by tilakrayal** [comment]
@Annieliaquat ,
Please feel free to move this issue to closed status and please submit a new issue from [this link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
