### ISSUE TITLE
Issue with load_model and custom_object_scope

### ISSUE THREAD

**Issue by deepNeuralNick** [tensorflow/tensorflow#54224]
So as it seems like there is an issue with load_model for tensorflow 2.7.0, 
This was not happening for me on tensorflow 2.4.1 and everything was running smoothly.

Let's get to the topic. 

When i try to load my model instance i am getting an error the first time i try to load it i'll highlight my code here.
   ```
 with K.utils.custom_object_scope(
        {
            "r2": r2,
            "r2_keras": r2,
            "AttentionAugmentation2D": AttentionAugmentation2D,
            "Functional": tf.keras.models.Model,
        }
    ):
        with GzipFile(filename, "rb") as fs:
            estimator = pickle.load(fs)
            keras_model = pickle.load(fs)
            model_h5_instance = h5py.File(BytesIO(keras_model), "r")
            estimator.estimator = K.models.load_model(
                model_h5_instance, compile=False
            )
```
it is also noted that the instance that i am using for saving is obviously a tf.keras.models.Model() instance

so the first time this line `estimator.estimator = K.models.load_model(model_h5_instance, compile=False)`  runs i am getting this error:
`AttirbuteError: module 'keras.api._v2.keras.models' has no attribute "Functional"`
the second time i run this line it loads the model regularly.
also noting that i have already tried to pass the custom objects on load_model.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- CUDA/cuDNN version: 11.6
- GPU model and memory: GTX 1050 TI

**Comment by sushreebarsa** [comment]
@deepNeuralNick 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
