### ISSUE TITLE
Github still lists 2.6.2 as the release, but pip installs 2.7.0

### ISSUE THREAD

**Issue by surak** [tensorflow/tensorflow#54237]
What is the current version in such a case?

**Comment by sushreebarsa** [comment]
@surak 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!

**Comment by surak** [comment]
There is no proper template for issues on the repo itself. It is what is written here. The “releases” page shows 2.6.2. Pip downloads 2.7. What is the stable version?

**Comment by sushreebarsa** [comment]
@surak Thank  you for the quick response!
The latest stable TF version is 2.7.0 , please have a look on this [link](https://www.tensorflow.org/install/source#tested_build_configurations)  of tested build configuration for reference.
Thanks!

**Comment by surak** [comment]
Great - then, whoever administers github, please make a release. 

Have a look. Go to the main page, here: https://github.com/tensorflow/tensorflow
and check on the right side, at RELEASES:
![Screen Shot 2022-02-02 at 16 05 57](https://user-images.githubusercontent.com/878399/152180213-ca76c2ba-c2cd-441d-9dcf-4dd195b6d149.png)

**Comment by markub3327** [comment]
@surak @sushreebarsa

GitHub shows the latest uploaded version not the latest version of TF !!! 

The last uploaded version is TF 2.6.2 because security or critical updates were done on it. Please do not mix the last activity and the latest version.

Thanks.

**Comment by surak** [comment]
I know, Mark. But there’s no indication of what is the actual latest release anywhere written in a clear, unambiguous way.

**Comment by sushreebarsa** [comment]
@markub3327 Thank you for the response!
@surak Please have a look at https://github.com/tensorflow/tensorflow , where the latest released version of TF is `2.8.0 ` now.
It was showing TF 2.6.2 as latest due to some updates were done on it.
Thanks!

**Comment by markub3327** [comment]
@surak The latest tested version of TF is (here)[https://www.tensorflow.org/install/source#tested_build_configurations] like @sushreebarsa mentioned. GitHub Releases is only informative for developers and sysadmins may look at https://www.tensorflow.org/install pages.

Thanks.

**Comment by surak** [comment]
There is still no clear indication of what the current release is on the github page.

**Comment by sushreebarsa** [comment]
@surak **GitHub** shows the `latest uploaded version for the recent activity not the latest version of TF`. Please refer [official ](https://www.tensorflow.org/) site of TensorFlow where stable TF version is 2.8.0 .
Thanks!

**Comment by gadagashwini** [comment]
@surak 
Latest and stable Tensorflow version is 2.8.0. It is updated in Tensorflow githib release notes 
Take a look [here](https://github.com/tensorflow/tensorflow/releases)

**Comment by surak** [comment]
@gadagashwini thanks, but only shows the most recent version created. If an older version has a bug fix release issued, that one will come up on top.... And this is my beef here. The page the way you show seems correct now, it wasn't when I opened this issue - look at the comment above: https://github.com/tensorflow/tensorflow/issues/54237#issuecomment-1028034032

**Comment by surak** [comment]
Seems nobody cares, or get it so I will close it.

**Comment by mihaimaruseac** [comment]
This is the standard procedure for all other packages. It's not soemething that TF itself is at fault.
