### ISSUE TITLE
tf.data.Dataset.from_generator() does not work with tf.data.experimental.enable_debug_mode()

### ISSUE THREAD

**Issue by dniku** [tensorflow/tensorflow#54232]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): `v2.7.0-0-gc256c071bb2 2.7.0`
- Python version: 3.7.12

**Describe the current behavior**

`tf.data.Dataset.from_generator()` does not work when `tf.data.experimental.enable_debug_mode()` is called in advance.

```python
import tensorflow as tf

tf.data.experimental.enable_debug_mode()

def gen():
    yield from iter(range(10))

dataset = tf.data.Dataset.from_generator(gen, output_signature=tf.TensorSpec(shape=(), dtype=tf.int32))

for item in dataset:
    print(item)
```

Results in

```
  ...

  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 810, in get_iterator
    return self._iterators[iterator_id]

TypeError: unhashable type: 'numpy.ndarray'


	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
```

From a small investigation it seems that the "obvious" solution — changing https://github.com/tensorflow/tensorflow/blob/ffe6f62b7f8e57177c26ca3b38c0929d5f64b43f/tensorflow/python/data/ops/dataset_ops.py#L833 to

```python
return np.int64(ret)
```

does not fix the issue, even though `np.int64(0)` is hashable, while `np.array(0, dtype=np.int64)` is not.

Additionally, I tried a workaround and added to `_GeneratorState` the following method:

```python
@staticmethod
def _fix_iterator_id(iterator_id):
    assert isinstance(iterator_id, np.ndarray)
    assert iterator_id.ndim == 0
    assert iterator_id.dtype == np.int64
    return np.int64(iterator_id)
```

and added calls to it from `get_iterator()` and `iterator_completed()`. However, this triggered yet another issue: in `tf.python.ops.script_ops`, `FuncRegistry` started throwing an error `ValueError('callback pyfunc_63 is not found')`.

**Describe the expected behavior**

No crash.

**Standalone code to reproduce the issue**

https://colab.research.google.com/gist/dniku/80456bc9d30fbaaadca4a22469c2c1df/tf_dataset_from_generator_with_debug_mode_crash.ipynb

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.5, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/356927cf329e036cb4cb873ad5615437/54232.ipynb).

**Comment by sachinprasadhs** [comment]
@dniku , If you have identified the issue in the code and the probable fix, could you please raise a PR. Thanks!

**Comment by dniku** [comment]
I have not, and my small investigation only hints at what will _not_ resolve this issue.
