### ISSUE TITLE
Segmentation Fault After Canonicalization Pass

### ISSUE THREAD

**Issue by yaochengji** [tensorflow/tensorflow#54249]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10 (buster)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source. 
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):GCC 8.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Segment Fault.

**Describe the expected behavior**
Run canonicalization pass successfully.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): I have some findings but I can't solve it independently.
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
- First create the `reproduce.mlir` as below.
```
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 0 : i32}} {
  func @main(%arg0: tensor<1xf32>, %arg1: tensor<1xf32>) -> tensor<1xf32> {
    %0 = mhlo.constant dense<9.99999997E-7> : tensor<f32>
    %1 = mhlo.constant dense<0.000000e+00> : tensor<1xf32>
    %2 = shape.shape_of %1 : tensor<1xf32> -> tensor<1xindex>
    %3 = shape.shape_of %0 : tensor<f32> -> tensor<0xindex>
    %4 = shape.cstr_broadcastable %2, %3 : tensor<1xindex>, tensor<0xindex>
    %5 = shape.assuming %4 -> (tensor<1xi1>) {
      %8 = shape.const_shape [1] : tensor<1xindex>
      %9 = "mhlo.dynamic_broadcast_in_dim"(%1, %8) {broadcast_dimensions = dense<0> : tensor<1xi64>} : (tensor<1xf32>, tensor<1xindex>) -> tensor<1xf32>
      %10 = "mhlo.dynamic_broadcast_in_dim"(%0, %8) {broadcast_dimensions = dense<> : tensor<0xi64>} : (tensor<f32>, tensor<1xindex>) -> tensor<1xf32>
      %11 = "mhlo.compare"(%9, %10) {comparison_direction = "LT"} : (tensor<1xf32>, tensor<1xf32>) -> tensor<1xi1>
      shape.assuming_yield %11 : tensor<1xi1>
    }
    %6 = shape.const_witness true
    %7 = shape.assuming %6 -> (tensor<1xf32>) {
      %8 = "mhlo.select"(%5, %arg0, %arg1) : (tensor<1xi1>, tensor<1xf32>, tensor<1xf32>) -> tensor<1xf32>
      shape.assuming_yield %8 : tensor<1xf32>
    }
    return %7 : tensor<1xf32>
  }
}
```
- `bazel  build //tensorflow/compiler/mlir/hlo:mlir-hlo-opt`
- `./bazel-bin/tensorflow/compiler/mlir/hlo/mlir-hlo-opt -canonicalize reproduce.mlir`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
- backtrace: `readBits (rawData=0x0, bitPos=0, bitWidth=1)`
- If `mlir-hlo-opt` is built by CMake, the command could run successfully.
- If `mlir-hlo-opt` is built by Bazel with debug mode (`-c dbg`), the command could run successfully.
- The bug start to appear from tensorflow commit `51ab810dd80114a463d6703f`.

**Comment by sushreebarsa** [comment]
@yaochengji 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by yaochengji** [comment]
@sushreebarsa Thanks for your reply. This content is already from the `bug issue template`. It is a `mlir` and `bazel` related bug, I hope the additional infomation could help you find the right person to assign the issue to.

**Comment by akuegel** [comment]
Is this still happening? I just tried it, and for me it seems to work now.

**Comment by yaochengji** [comment]
> * ./bazel-bin/tensorflow/compiler/mlir/hlo/mlir-hlo-opt -canonicalize reproduce.mlir

@akuegel Thanks. But this bug still appears on my side. I'm using the latest commit `3362b358bbad2e6d`.

**Comment by akuegel** [comment]
My guess is that it depends on which compiler you use. Are you using gcc by any chance? And if yes, which version?

**Comment by yaochengji** [comment]
I'm using gcc 8.3.0.
```
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by yaochengji** [comment]
Thanks, @akuegel . I tried gcc-11 and it works.

**Comment by yaochengji** [comment]
@SuryanarayanaY it is closed, thanks.
