### ISSUE TITLE
 symbol not found in flat namespace '__ZN4mlir2TF6detail25ResourceAliasAnalysisInfo18kMaxResourceTypeIdE'

### ISSUE THREAD

**Issue by shenyufengt** [tensorflow/tensorflow#54242]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS monterey 12.0.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary):source
- TensorFlow version: r2.7
- Python version: python3.9
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source): bazel 3.7.2
- GCC/Compiler version (if compiling from source):  Apple clang version 13.0.0 (clang-1300.0.29.3)
- CUDA/cuDNN version: no enabled
- GPU model and memory:: no enabled(Just CPU model)

**Describe the problem**
when running the "import tensorflow as tf" , I got the exception below:
"Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 0x0006): symbol not found in flat namespace '__ZN4mlir2TF6detail25ResourceAliasAnalysisInfo18kMaxResourceTypeIdE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxx/PycharmProjects/pythonProject1/tensorflow/testdebug.py", line 1, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 79, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 0x0006): symbol not found in flat namespace '__ZN4mlir2TF6detail25ResourceAliasAnalysisInfo18kMaxResourceTypeIdE'

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

Process finished with exit code 1
"

**Provide the exact sequence of commands / steps that you executed before running into the problem**
 steps:
 
0) download source code and " git checkout r2.7"
1)  ./configure  (choose "N" for all of the questions)
2)  bazel build --config=dbg --strip=never -c dbg --copt='-g' --cxxopt='-g'   //tensorflow/tools/pip_package:build_pip_package
3) ./bazel-bin/tensorflow/tools/pip_package/build_pip_package pkt2/tensorflow_pkg
4) pip install /Users/xxxxx/ai/tf/tensorflow/pkt2/tensorflow_pkg/tensorflow-2.7.0-cp39-cp39-macosx_12_0_x86_64.whl --force-reinstall
5) try to run "import tensorflow as tf" and got the exception:"ImportError: dlopen(/usr/local/lib/python3.9/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 0x0006): symbol not found in flat namespace '__ZN4mlir2TF6detail25ResourceAliasAnalysisInfo18kMaxResourceTypeIdE'
"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by shenyufeng1234** [comment]
BTW, got the same exception if using the build command "bazel build --config=dbg --per_file_copt=+tensorflow/core/kernels/identity_op.*@-g //tensorflow/tools/pip_package:build_pip_package"

**Comment by shenyufeng1234** [comment]
Hi @sushreebarsa  , do you have any idea or can duplicate for this issue?

**Comment by shenyufeng1234** [comment]
The issue also happens at TF2.8 (all of the other configs and commands are the same as  TF2.8)

**Comment by chunduriv** [comment]
@shenyufeng1234,
Can you please take a look at [link1](https://github.com/tensorflow/tensorflow/issues/41682), [link2](https://stackoverflow.com/a/70305743/14290681) which discusses about the similar issue and let us know if it helps? Thanks!

**Comment by shenyufeng1234** [comment]
> link2

No,I already updated Xcode to the most recent.

**Comment by shenyufeng1234** [comment]
BTW,how to know the  python version used to compile the TF source code?

**Comment by shenyufeng1234** [comment]
force_flat_namespace option for Clang of macos (I don't know if it is helpful) ,however I cannot use it with commmand "bazel build", it is not supported:"ERROR: -force_flat_namespace :: Invalid options syntax: -force_flat_namespace".

**Comment by shenyufeng1234** [comment]
I found a big diff between r2.6 and r2 .7, the variable  "__ZN4mlir2TF6detail25ResourceAliasAnalysisInfo18kMaxResourceTypeIdE"  (static constexpr int64_t kMaxResourceTypeId  )doesn't exist in  r2.6, it is new from r2 .7 to master, maybe the new  variable  kMaxResourceTypeId cuased the issue at the macos.

**Comment by shenyufeng1234** [comment]
It seems TF needs to move the two variables  "static constexpr int64_t kMaxResourceTypeId = 9999;" and "static constexpr int64_t kUnknownResourceId = -1;" from resource_alias_analysis.h to resource_alias_analysis.cc ,otherwise it would cause the issue at mac os.

**Comment by shenyufeng1234** [comment]
BTW ,if I build with "bazel build --config=opt  //tensorflow/tools/pip_package:build_pip_package  " everything is ok,  however if I build with  enable any debug info , it would be failed with exception above.

**Comment by Kipsora** [comment]
I was trying to build with a different command but encountered the same issue. Adding the following one line fix this issue for me.

```diff
diff --git a/tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc b/tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc
index 5c366896349..40ef08483d5 100644
--- a/tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc
+++ b/tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc
@@ -262,6 +262,7 @@ bool IsResourceAllocatingOp(Operation* op) {
 }  // namespace
 
 constexpr int64_t ResourceAliasAnalysisInfo::kUnknownResourceId;
+constexpr int64_t ResourceAliasAnalysisInfo::kMaxResourceTypeId;
 
 void IncrementResourceTypeId(int64_t& resource_type_id) {
   if (resource_type_id == ResourceAliasAnalysisInfo::kMaxResourceTypeId) {

```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
