### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by faizan1234567** [tensorflow/tensorflow#54245]
Hey everyone. I am training resnet50v2 on my dataset, I have 18746 images in the training set and 4000+ images in the validation set. I am using a batch size of 32. The first time I tried to train my model with this batch size, it worked. When I try to train my model it gave me the following error this time.
![error](https://user-images.githubusercontent.com/61932757/152167745-4ce0449f-6530-41d7-b4c3-b1afd00d82e7.png)

I tried a lot, but nothing worked for me.

**Comment by Cheril311** [comment]
@faizan1234567 could you please tell your system and software specifications?

**Comment by faizan1234567** [comment]
I am using google colab

**Comment by Cheril311** [comment]
You can refer to this answer here: https://stackoverflow.com/questions/59394947/how-to-fix-resourceexhaustederror-oom-when-allocating-tensor/59395251 <br> This is basically because your colab gpu is running out of memory for your use case
