### ISSUE TITLE
Isn't tf.compat.v1.get_variable the default trainable variable?

### ISSUE THREAD

**Issue by Nafees-060** [tensorflow/tensorflow#54250]
I am implementing deep learning model using tensorflow keras where I need γ learnable parameter. For that I am utilizing

`gamma = tf.compat.v1.get_variable("gamma", [1], initializer=tf.constant_initializer(0.0))`

I read the [Official Documentation of tf.compat.v1.get_variable](https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_variable) but could not get the complete idea. In the official documentation it seems that by default this variable is non trainable. am I right? If yes then should I need to true this function in order to make trainable, like:
` gamma = tf.compat.v1.get_variable("gamma", [1], trainable=True, initializer=tf.constant_initializer(0.0))`

Could someone please clear it?

**Comment by mohantym** [comment]
Hi @Nafees-060 ! I agree with your point on getting trainable variables by enabling **trainable=True**.  Have attached a [thread ](https://www.programcreek.com/python/example/112642/tensorflow.compat.v1.get_variable)for comparing different use cases on tf.compat.v1.get_variable(). Thanks!

**Comment by Nafees-060** [comment]
> Hi @Nafees-060 ! I agree with your point on getting trainable variables by enabling **trainable=True**. Have attached a [thread ](https://www.programcreek.com/python/example/112642/tensorflow.compat.v1.get_variable)for comparing different use cases on tf.compat.v1.get_variable(). Thanks!

Okay, thanks. May I know the difference between `initializer=v.initial_value` and  `initializer=tf.constant_initializer(0.0)`

**Comment by Nafees-060** [comment]
> Hi @Nafees-060 ! I agree with your point on getting trainable variables by enabling **trainable=True**. Have attached a [thread ](https://www.programcreek.com/python/example/112642/tensorflow.compat.v1.get_variable)for comparing different use cases on tf.compat.v1.get_variable(). Thanks!

OOPs, I just tried trainable=True, and the number of trainable parameters remains the same as it was previously. Shouldn't the total number of parameters be increased by one additional learnable parameter?

**Comment by mohantym** [comment]
@Nafees-060 ! Number of trainable parameters will remain same but their value will vary once set trainable=True. Regarding this [query](https://github.com/tensorflow/tensorflow/issues/54250#issuecomment-1028719878) , Please visit [tf.constant.initializer ](https://www.tensorflow.org/api_docs/python/tf/constant_initializer)and [tf.variable](https://www.tensorflow.org/api_docs/python/tf/Variable#args) to get more details. Thank you!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
