### ISSUE TITLE
InvalidArgumentError:  Size 1 must be non-negative, not -13 	 [[{{node gradient_tape/mean_squared_error/sub-1-ReshapeNHWCToNCHW-LayoutOptimizer}}]] [Op:__inference_train_function_7208]

### ISSUE THREAD

**Issue by Salman-F** [tensorflow/tensorflow#54255]
I am trying to train my neuronal Network but get this error everytime and i dont know what it means.

I am using tenserfow 2.7.0 in google colab.
Here is my NN architecture (i am training a CNN to output two informations - steering and speed.
Is something wrong with the mean_squared_error? 
`class v2Model():
    def __init__(self):
        self.logdir = os.path.join(TRAIN_LOGS_PATH, datetime.datetime.now().strftime("run-V2_%d-%b-%Y__%H-%M-%S_%f"))
        self.epochs = 10
        self.batchSizeTrain = 100
        self.batchSizeVal = 25

    def createModel(self) -> None:
        inputs = Input(shape=(80, 320, 1))
        self.model = Rescaling(scale=1./127.5, offset=-1.)(inputs)
        self.model = Conv2D(filters=16, kernel_size=(5, 5), padding='VALID', activation='elu')(self.model)
        self.model = MaxPooling2D(pool_size=(2, 2), padding='VALID')(self.model)
        self.model = Conv2D(filters=32, kernel_size=(3, 3), padding='VALID', activation='elu')(self.model)
        self.model = MaxPooling2D(pool_size=(2, 2), padding='VALID')(self.model)
        self.model = Conv2D(filters=64, kernel_size=(3, 3), padding='VALID', activation='elu')(self.model)
        self.model = MaxPooling2D(pool_size=(2, 2), padding='VALID')(self.model)
        self.model = Dense(19456, use_bias=True)(self.model)
        self.model = Dropout(rate=0.2)(self.model)
        self.model = Dense(500, use_bias=True)(self.model)
        dropV2 = Dropout(rate=0.2)(self.model)

        headSteeringV2 = Dense(1, activation="linear", name="output_ster")(dropV2)
        headSpeedV2 = Dense(1, activation="linear", name="output_acc")(dropV2)

        self.model = Model(inputs=inputs, outputs=[headSteeringV2, headSpeedV2])
        #print(self.model.summary())
      
        lossMse = MeanSquaredError()
        optimizer = Adam()

        self.model.compile(optimizer=optimizer, loss="mean_squared_error", metrics=['accuracy'])
    
    def trainModel(self, x_train, y_train_ster, y_train_acc, x_val, y_val_ster, y_val_acc) -> None:

        tensorboardCallback = tf.keras.callbacks.TensorBoard(self.logdir, histogram_freq=1)
        earlyStopCallback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=1e-4, patience=2, mode='auto')
        # bei zittern 1e-2, 1e-3

        stepsPerEpoch = len(x_train) // self.batchSizeTrain
        stepsVal = len(x_val) // self.batchSizeVal

        self.history = self.model.fit(genData(x_train, {"output_ster":y_train_ster, "output_acc":y_train_acc}, self.batchSizeTrain, True, "v2"),
                                  steps_per_epoch=stepsPerEpoch,
                                  epochs=self.epochs ,
                                  validation_data=genData(x_val, {"output_ster": y_val_ster, "output_acc": y_val_acc}, self.batchSizeVal, False, "v2"),
                                  validation_steps=stepsVal,
                                  callbacks=[tensorboardCallback, earlyStopCallback])

    def uploadTraining(self):
      !tensorboard dev upload --logdir {self.logdir} \
        --name f"Training Results from CNN V2 at {datetime.datetime.now().strftime('%d-%b-%Y__%H-%M-%S')}" \
        --description "Accuracy and loss graphs" \
        --one_shot
    
    def saveModel(self):
      self.model.save("/content/drive/MyDrive/model-v2.h5")`

`
Full Error message.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-22-33a8561955b9>](https://localhost:8080/#) in <module>()
     74 v2CNN = v2Model()
     75 v2CNN.createModel()
---> 76 v2CNN.trainModel(x_train, y_train_ster, y_train_acc, x_val, y_val_ster, y_val_acc)
     77 v2CNN.uploadTraining()
     78 v2CNN.saveModel()

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57     ctx.ensure_initialized()
     58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:
     61     if name is not None:

InvalidArgumentError:  Size 1 must be non-negative, not -12
	 [[{{node gradient_tape/mean_squared_error_1/sub-1-ReshapeNHWCToNCHW-LayoutOptimizer}}]] [Op:__inference_train_function_5310]
`

**Comment by sushreebarsa** [comment]
@Salman-F  
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by Salman-F** [comment]
@sushreebarsa 
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): google colab pre installed
- TensorFlow version (use command below): 2.7.0
- Python version: 3.6.9
- Bazel version (if compiling from source): no idea
- GCC/Compiler version (if compiling from source): no idea
- CUDA/cuDNN version: google colab pre installed
- GPU model and memory: google colab switches sometimes

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
3. v2.7.0-0-gc256c071bb2 2.7.0

**Describe the current behavior**
I can't train my CNN because of an error i can't explain (or see where it is)

**Describe the expected behavior**
The training of my CNN should start and the epochs should work

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no idea
- Briefly describe your candidate solution(if contributing): no idea

**Standalone code to reproduce the issue**
Here is my notebook
https://gist.github.com/Salman-F/015a7658333e8afe8d6c80c7b8ce1d2a

**Other info / logs** 
Epoch 1/10
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-22-33a8561955b9>](https://localhost:8080/#) in <module>()
     74 v2CNN = v2Model()
     75 v2CNN.createModel()
---> 76 v2CNN.trainModel(x_train, y_train_ster, y_train_acc, x_val, y_val_ster, y_val_acc)
     77 v2CNN.uploadTraining()
     78 v2CNN.saveModel()

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57     ctx.ensure_initialized()
     58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:
     61     if name is not None:

InvalidArgumentError:  Size 1 must be non-negative, not -12
	 [[{{node gradient_tape/mean_squared_error_1/sub-1-ReshapeNHWCToNCHW-LayoutOptimizer}}]] [Op:__inference_train_function_5310]

**Comment by Salman-F** [comment]
Sorry for not filling it out immediately :)

**Comment by Salman-F** [comment]
> @Salman-F  
> 
> In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
> 
> Thanks!

Just made it

**Comment by sushreebarsa** [comment]
@Salman-F Thank you for the update!
I tried to run your code on colab using TF v2.7.0,2.8.0  and faced a different error .Could you please have a look at the [gist1](https://colab.research.google.com/gist/sushreebarsa/d5c3ca1517f7466c011b746dab8ab22d/trainingv2.ipynb#scrollTo=BThu9cCBrpIt),  [gist2](https://colab.research.google.com/gist/sushreebarsa/90752372d189019a6aabbe02281694d7/trainingv2.ipynb#scrollTo=dbSAFS9wp0gI) and confirm the same? Let me know if I'm missing something to replicate the issue.Thanks!

**Comment by Salman-F** [comment]
@sushreebarsa Hi, yes i think you are missing my data. I can try to give you some data that you have to load into your google colab enviorment. A problem may accur with the paths i decleared at the beginning. You have to change them to access the data (or if you put them in your google drive  and conect it to google colab it should be the same)
Download a few data samples here: https://nextcloud.dhbw-stuttgart.de/index.php/s/akmrSWTFA6zDiQm
Maybe you can also create some dummy data.
Please feel free to contact me, if you need more :)

**Comment by sushreebarsa** [comment]
@gadagashwini Was able to reproduce the issue on colab using TF v[2.7.0](https://colab.research.google.com/gist/sushreebarsa/1158d73576da91e6fc8d164de8172fc5/gist54255.ipynb) and [2.8.0](https://colab.research.google.com/gist/sushreebarsa/52ff328b88545cfecb6ca410c81408c2/gist54255.ipynb) ,please find the attached gists for reference.Thanks!

**Comment by gadagashwini** [comment]
@Salman-F, Looks like issue is with your input data shape
I tried to replicate your issue with minimal code. Below sample code works

```
import tensorflow as tf
import numpy as np
from tensorflow.keras import datasets
import tensorflow.keras as keras
from tensorflow.keras.layers import Conv2D, Flatten, Dropout, Dense, Rescaling
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.models import Model


X_train = np.random.random((235,65, 320, 1))
y_train = np.random.random((235, 65, 320, 1))

dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
train_data = dataset.shuffle(len(X_train)).batch(32)
train_data = train_data.prefetch(
        buffer_size=tf.data.experimental.AUTOTUNE)

input_shape = (65, 320, 1)
initializer = tf.keras.initializers.HeUniform()

model = tf.keras.Sequential(
[
    tf.keras.Input(shape=(65, 320, 1)),
    keras.layers.Rescaling(1./125,offset=1., input_shape=(65,320,1)),
    keras.layers.Conv2D(filters=16, kernel_size=(5,5), padding='same', activation='relu', kernel_initializer=initializer),
    keras.layers.Dense(20, use_bias=True),
    keras.layers.Dropout(rate=0.7),
    keras.layers.Dense(1, activation='linear')
])

model.summary()
lossMse = MeanSquaredError()
model.compile(optimizer='adam',
                loss=lossMse,
                metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5, verbose=1)
```

**Output**
```
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 rescaling (Rescaling)       (None, 65, 320, 1)        0         
                                                                 
 conv2d (Conv2D)             (None, 65, 320, 16)       416       
                                                                 
 dense (Dense)               (None, 65, 320, 20)       340       
                                                                 
 dropout (Dropout)           (None, 65, 320, 20)       0         
                                                                 
 dense_1 (Dense)             (None, 65, 320, 1)        21        
                                                                 
=================================================================
Total params: 777
Trainable params: 777
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
8/8 [==============================] - 6s 47ms/step - loss: 1.7397 - accuracy: 0.0000e+00
Epoch 2/5
8/8 [==============================] - 0s 25ms/step - loss: 0.7736 - accuracy: 0.0000e+00
Epoch 3/5
8/8 [==============================] - 0s 23ms/step - loss: 0.5147 - accuracy: 0.0000e+00
Epoch 4/5
8/8 [==============================] - 0s 22ms/step - loss: 0.4024 - accuracy: 0.0000e+00
Epoch 5/5
8/8 [==============================] - 0s 26ms/step - loss: 0.3066 - accuracy: 0.0000e+00
<keras.callbacks.History at 0x7f66000bcb90>
```
