### ISSUE TITLE
How to install llvm-project from local ? 

### ISSUE THREAD

**Issue by shenyufeng1234** [tensorflow/tensorflow#54257]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS monterey 12.0.1
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
TensorFlow installed from (source or binary):source
TensorFlow version: r2.7
Python version: python3.9
Installed using virtualenv? pip? conda?:pip
Bazel version (if compiling from source): bazel 3.7.2
GCC/Compiler version (if compiling from source): Apple clang version 13.0.0 (clang-1300.0.29.3)
CUDA/cuDNN version: no enabled
GPU model and memory:: no enabled(Just CPU model)

**Describe the problem**
When I run the command " bazel build --config=dbg --strip=never -c dbg --copt='-g' --cxxopt='-g' //tensorflow/tools/pip_package:build_pip_package", it would pull package from "https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz" ,maybe it is too large,  the bazel build  command always failed at this step, so how to install this package from local ? As I can download this package  to local successfully.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
	File "/Users/xxx/ai/tf/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /private/var/tmp/_bazel_shenyufeng/a4eaa5fcc3d32c786eb9bb79fa0163a2/external/llvm-raw/temp10925281720111290723/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Premature EOF
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/Users/xxxx/ai/tf/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /private/var/tmp/_bazel_shenyufeng/a4eaa5fcc3d32c786eb9bb79fa0163a2/external/llvm-raw/temp10925281720111290723/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Premature EOF
ERROR: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz, https://github.com/llvm/llvm-project/archive/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz] to /private/var/tmp/_bazel_shenyufeng/a4eaa5fcc3d32c786eb9bb79fa0163a2/external/llvm-raw/temp10925281720111290723/55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz: Premature EOF
INFO: Elapsed time: 1738.882s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tilakrayal** [comment]
@shenyufeng1234 ,
Can you please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/53503) with the similar error and it is fixed in the latest build.It helps.Thanks!

**Comment by shenyufeng1234** [comment]
> tilakrayal
The issue also happened at r2.8, which has the fix.so they are different issue. My question is is there is any way to install the llvm-project from local ? such as download it to local manually and install it from there .

**Comment by tilakrayal** [comment]
@shenyufeng1234 ,
Can you please take a look at this [link](https://llvm.org/docs/CMake.html) to install llvm-project.It helps.Thanks!

**Comment by qinhj** [comment]
> > tilakrayal
> > The issue also happened at r2.8, which has the fix.so they are different issue. My question is is there is any way to install the llvm-project from local ? such as download it to local manually and install it from there .

A solution to "download it to local manually and install it from there": add an additional attr(e.g. "local_files") to "_tf_http_archive" in third_party/repo.bzl, and call "ctx.extract" instead of "ctx.download_and_extract" in "_tf_http_archive_impl".

Below is a quick patch based on v2.12.1, which also should be compatible with other release versions:
[0001-patch-support-to-extract-local-dependencies-directly.patch](https://github.com/tensorflow/tensorflow/files/12924329/0001-patch-support-to-extract-local-dependencies-directly.patch)

Then, add the local file path for llvm
> \-\-\- a/third_party/llvm/workspace.bzl
> \+\+\+ b/third_party/llvm/workspace.bzl
> @@ -15,6 +15,9 @@ def repo(name):
>              "https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
>              "https://github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
>          ],
> \+       local_files = [
> \+            "/dl/llvm-10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz",
> \+        ],
>          build_file = "//third_party/llvm:llvm.BUILD",

Have a try!
