### ISSUE TITLE
GPU delegate for tflite not finding libOpenCL when deployed on linux

### ISSUE THREAD

**Issue by parnham** [tensorflow/tensorflow#54269]
**System information**
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow):* yes
- *OS Platform and Distribution (e.g., Linux Ubuntu 16.04):* Built on and deployed to Ubuntu 18.04 x86_64 
- *TensorFlow installed from (source or binary):* Package of tflite built from source, deployed as deb
- *TensorFlow version (use command below):* tflite v2.5.0 (2.6 was slower and we've not yet had time to assess 2.7)
- *Python version:* n/a
- *Bazel version (if compiling from source):* 4.2.1
- *GCC/Compiler version (if compiling from source):* 7.5.0-3ubuntu1~18.04
- *CUDA/cuDNN version:* n/a
- *GPU model and memory:* Deployed to systems with nvidia GTX 1070

**Describe the current behavior**
On a linux system the GPU delegate attempts to dynamically load libOpenCL but uses the "dev" name of the library. 
When deploying a solution on an Ubuntu system the filename for the installed OpenCL library from package "ocl-icd-libopencl1" is `libOpenCL.so.1`. The symlink `libOpenCL.so` would only be present via the "ocl-icd-opencl-dev" package which would usually be installed when building not deploying. 

**Describe the expected behavior**
When deployed it should load OpenCL from the library package and not the dev package.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/cl/opencl_wrapper.cc#L92

**Comment by yupinov** [comment]
213a786 fixes this. Alternatively, passing `auto options = TfLiteGpuDelegateOptionsV2Default();` also works around the crash.

**Comment by pjpratik** [comment]
Hi @parnham 

Th commit https://github.com/tensorflow/tensorflow/commit/6e58460909fdcb9b64e606eca9590014576f4caf which updates build rule to use opencl icd loader to run OpenCL tests under gLinux.

Can you please check in the latest version and confirm the same?

Thanks.

**Comment by parnham** [comment]
Hi @pjpratik, 

I'm afraid I can't check since we're unable to build the v2.13.0-rc2 GPU delegate under linux due to this change (I think) which causes a linker error:

https://github.com/tensorflow/tensorflow/commit/33722bc185e676c99f738790ef35db8479f2f7d4

```
+tflite *failed* | [918 / 919] [Prepa] Linking tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so
+tflite *failed* | ERROR: /code/tensorflow/tensorflow/lite/delegates/gpu/BUILD:132:10: Linking tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so-2.params
+tflite *failed* | /usr/bin/ld.gold: error: cannot find -lnativewindow
+tflite *failed* | /usr/bin/ld.gold: error: cannot find -lnativewindow
```
I'm not very familiar with Bazel and our build of the tflite libraries occurs in a container so it's not that easy for me to hack around with.

Kind regards,
Dan

**Comment by misterBart** [comment]
@parnham 
Thanks for your sed solution, because I experienced the same problem.

The simple program:
```
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/delegates/gpu/delegate.h"
#include <iostream>

using namespace std;
using namespace tflite;

int main() {
	// Set up interpreter.
	std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("test.tflite");
	if (!model) std::cout << "Model error\n";
	ops::builtin::BuiltinOpResolver op_resolver;
	std::unique_ptr<Interpreter> interpreter;
	InterpreterBuilder(*model, op_resolver)(&interpreter);

	//Prepare GPU delegate.
	auto* delegate = TfLiteGpuDelegateV2Create(/*default options=*/nullptr);
	if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) std::cout << "ModifyGraphWithDelegate error\n";

	std::cout << "Done\n";
	return EXIT_SUCCESS;
}
```

outputted before your fix:
```
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Can not open OpenCL library on this device - ./app: undefined symbol: clGetCommandBufferInfoKHR
ERROR: Falling back to OpenGL
ERROR: TfLiteGpuDelegate Init: OpenGL-based API disabled
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 70 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
ModifyGraphWithDelegate error
Done
```

And outputted after your fix:
```
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
Done
```

Tested on Ubuntu 23.04 with an Nvidia Geforece GT1030.
```
$ ls /usr/lib/x86_64-linux-gnu/libOpen*
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1      /usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0  /usr/lib/x86_64-linux-gnu/libOpenThreads.so
/usr/lib/x86_64-linux-gnu/libOpenGL.so        /usr/lib/x86_64-linux-gnu/libOpenThreads.so.21
/usr/lib/x86_64-linux-gnu/libOpenGL.so.0      /usr/lib/x86_64-linux-gnu/libOpenThreads.so.3.3.1
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
