### ISSUE TITLE
Why is inference time so slow when using tensorflow.compat.v1?

### ISSUE THREAD

**Issue by SinDongHwan** [tensorflow/tensorflow#54263]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source(pip install)
- TensorFlow version (use command below): TFv1(1.13.1 / 1.14.0 /1.15.4), TFv2(2.7.0)
- Python version: Python 3.6(TFv1), Python 3.7(TFv2)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.3 / cuDNN 8.2.1
- GPU model and memory: GTX 1080ti 11G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: 1.13.1 / 1.14.0 / 1.15.4
2. TF 2.0: 2.7.0

**Describe the current behavior**
Inference time is slow when loading and inferring models using tf.compat.v1.
I tested 4 cases about one model.
the model is one of tensorflow object detection model zoo and trained using own dataset(fine tuning). 

1 case) inference using TF 1.13.1 -> inference time : 0.05
2 case) inference using TF 1.14.0 -> inference time : 0.05
3 case) inference using TF 1.15.4 -> inference time : 0.27
4 case) inference using TF 2.7.0 -> inference time : 0.27

Looking at the above results, I think version of tf.compat.v1 is 1.15.4.
Can I change version of tf.compat.v1 from 1.15 -> 1.14?

Our company solution is using tensorflow 1.13 to load and infer models. And I am migrating to tf2 to support RTX 3000 series.

**Describe the expected behavior**

Expected result,
1 case) inference using TF 1.13.1 -> inference time : 0.05
2 case) inference using TF 1.14.0 -> inference time : 0.05
3 case) inference using TF 1.15.4 -> inference time : 0.05
4 case) inference using TF 2.7.0 -> inference time : 0.05

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@SinDongHwan ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by SinDongHwan** [comment]
@tilakrayal ,
I would like to send you the sample code and weight file by email.
Could you tell me your email?

**Comment by tilakrayal** [comment]
@SinDongHwan ,
Can you please attach the files here.We can download from the same.Thanks!

**Comment by tilakrayal** [comment]
@SinDongHwan ,
This issue is more suitable for TensorFlow Models repo. Please post it on Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thanks!

**Comment by SinDongHwan** [comment]
@tilakrayal 
Thank you. I also wrote this issue there.
