### ISSUE TITLE
Reduce axis produce wrong results in tf.function mode when there are duplicate dimensions

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#54265]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: running on CPU
- GPU model and memory: running on CPU

**Describe the current behavior**
The two API: tf.math.reduce_sum, tf.math.reduce_mean will have wrong output in tf.function when there are duplicate dimension in axis.

**Describe the expected behavior**
It should either raise an exception or clear the duplicate dimension.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import traceback
import tensorflow as tf
import numpy as np

input = np.array([[  79, -126,   95,   39,  -50,  -59,   -6,  -82,   95,  124,  -94,
        -126,  -45,   46,   33,  123, -126],
       [-108,   68,   91,   -5,   53,  122,  -56,  106, -107,  126,   64,
         -25, -118,  -17,  -59,  -99,   98],
       [ -25, -119,  -28,   44,   13,  -80,   30,  105,   42,  119,   79,
          38,   34,  -89,  -23, -110,    1],
       [ -44, -121,   -7,  -62,   -8,  120,   24,  110,  -68,  -22,  -67,
         -10, -118,   21,  -47,  -94,  108],
       [ 108,   82,  -14,   26,  120,  -11,   19,  -77,  -47,  -35,  109,
          -3,   67,   20,  -90,   42,   95],
       [-125,  -80,  -18,   72,  -90,   55,   39,   -2,  -81,   -6,  -84,
          18,   96, -100,   68,   73,  -57],
       [  67,   46,  -49,   47,  -11,  -66,  -14,  107,   43, -105,  -71,
        -108,   23,  -21,   77,  -63, -107],
       [-115,  -14,  -92,   68, -118,   73,   92,   27,  -21,  -99,  -99,
         124,   47,  -70,  -93,  122,   69],
       [ -96,  -47,  -23,   43,   12,   12,  -80,   65,   39, -110,    2,
          -4,  110,  -23,   94,   67,   39]], dtype=np.int8)
axis = np.array([0, 0], dtype=np.int32)

fun_list = [tf.math.reduce_sum, tf.math.reduce_mean]
fun = tf.math.reduce_sum

for fun in fun_list:
    try:
        output1 = fun(input, axis)
    except:
        print(traceback.format_exc())  # the eager mode will raise an execption

    @tf.function
    def fun_wrapper(x, y):
        return fun(x, y)

    output2 = fun_wrapper(input, axis)
    print(output2)  # the results of tf function is wrong
```
The tf function mode should either raise an Exception like the eager mode or clear the duplicate dimension and then do the execution.

**Comment by mohantym** [comment]
Hi @jiannanWang ! I was getting invalid argument error in above code which got resolved by disabling eager execution . Attaching resolved [gist ](https://colab.sandbox.google.com/gist/mohantym/08933c56ef3f271d6cd6bd3a26e6e15b/github_54265.ipynb#scrollTo=wI4TxI9ecfDH)for reference.

**Comment by jiannanWang** [comment]
Hi mohantym, thank you for your response! From my perspective, the results for disabling eager execution are wrong, while the invalid argument error is kind of expected. In the above example, when the axis is [0, 0], I would expect it to act like axis = [0] instead of axis = [0, 1]. 

Moreover, I found that in tf.function mode, as long as len(axis) = len(input_tensor.shape), tf.math.reduce_sum, tf.math.reduce_mean will ignore the actual value of the axis argument and reduce all dimensions of the input_tensor, which is a wrong assumption without checking duplicate dimensions in axis.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? It is replicating  in [2.7](https://colab.sandbox.google.com/gist/mohantym/1a40f4940de5e619cc7bf8b7a0b47923/github_54265.ipynb#scrollTo=wI4TxI9ecfDH), [2.8](https://colab.sandbox.google.com/gist/mohantym/7f0eebdbc6ae4b8a1764552a1452b0c7/github_54265.ipynb#scrollTo=t37fp5I8vsMf) and [nightly](https://colab.sandbox.google.com/gist/mohantym/44d2418969979eeea99152d35d0e65c0/github_54265.ipynb#scrollTo=t37fp5I8vsMf) in eager mode.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
