### ISSUE TITLE
tf.image.non_max_suppression produces wrong results in tf.function when the input is float16.

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#54264]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: running on CPU
- GPU model and memory: running on CPU

**Describe the current behavior**
tf.image.non_max_suppression will produce wrong results in tf.function when the input is float16.

**Describe the expected behavior**
The results should be equivalent to eager mode.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

argument = {'max_output_size': 3673497876354746723,
            'scores': np.array([61920., 31020., 2234., 41280., -25490.], dtype=np.float16),
            'boxes': np.array([[-40500., -59940., -106.3, 41800.],
                               [-37700., 37500., -53630., 49920.],
                               [-44900., -5356., 28080., 24940.],
                               [-44770., -18110., 28940., 7900.],
                               [-32380., 36200., -40640., 22850.]], dtype=np.float16)}

fun = tf.image.non_max_suppression

output1 = fun(**argument)
print(output1)  # the results of eager mode is correct

@tf.function
def fun_wrapper(arg):
    return fun(**arg)

output2 = fun_wrapper(argument) 
print(output2)  # the results of tf function is wrong
```

The results are:

tf.Tensor([0 3 1 2 4], shape=(5,), dtype=int32)
tf.Tensor([0], shape=(1,), dtype=int32)

**Comment by sushreebarsa** [comment]
@chunduriv Was able to replicate the issue on colab using TF v2.7.0 ,2.8.0 and tf-nightly, please find the attached gist [here](https://colab.research.google.com/gist/sushreebarsa/f2e8a8bf3f8d60f7f7255741315cfd52/untitled566.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Triage Notes: The maximum value that float16 can represent is `65504`. The values in this example are large enough that it is a reasonable guess that overflow is occurring. This appears to be a testing only case to find numeric bounds, the box coordinates do not look like either typical absolute pixel coordinates in an image or [0,1] normalized coordinates. Using `float32` avoids this bug. While the `NonMaxSuppressionV3` currently does not support `bfloat16`, using `bfloat16` instead of `float16` might solve this problem.
