### ISSUE TITLE
Option to avoid caching with bijectors.

### ISSUE THREAD

**Issue by alexhepburn** [tensorflow/tensorflow#54277]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.7.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The current behaviour for `tensorflow_probability.bijectors.Bijector` is to cache the input to be used if the inverse function is called. I would very much like a keyword being able to turn this caching off to ensure the inverse function of the bijector is always called. Whilst setting the property of `_is_injective` can accomplish this, you lose other features.

**Will this change the current api? How?**
Yes, a keyword in the definition of the Bijector class.

**Who will benefit with this feature?**
Anyone who wishes to have bijectors where the inverse function is always called rather than the input that's been cached.

**Any Other info.**

**Comment by tilakrayal** [comment]
@alexhepburn ,
This issue is more related to tensorflow/probability than tensorflow/tensorflow. Please post it on Tensorflow probability repo from [here](https://github.com/tensorflow/probability). Thanks!

**Comment by alexhepburn** [comment]
Thanks!

**Comment by tilakrayal** [comment]
@alexhepburn ,
Please feel free to move this issue to closed status as it is related to different repo.Thanks!
