### ISSUE TITLE
Build broken on AARCH64 by XNNPACK update

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#54273]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version:3.8.10
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

build_pip_package fails with

ERROR: /home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/external/XNNPACK/BUILD.bazel:9264:19: Compiling src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc failed: (Exit 1): gcc failed: error executing command 
  (cd /home/builder/.cache/bazel/_bazel_builder/9dc2dbd69dc3512cedb530e1521082e7/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib \
    PATH=/home/builder/.cache/bazelisk/downloads/bazelbuild/bazel-5.0.0-linux-arm64/bin:/home/builder/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
  /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/aarch64-opt/bin/external/XNNPACK/_objs/jit/1/1x8-aarch64-neonfma-cortex-a75.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/XNNPACK/_objs/jit/1/1x8-aarch64-neonfma-cortex-a75.pic.o' -fPIC '-DXNN_LOG_LEVEL=0' -DPTHREADPOOL_NO_DEPRECATED_API -iquoteexternal/XNNPACK -iquotebazel-out/aarch64-opt/bin/external/XNNPACK -iquoteexternal/FP16 -iquotebazel-out/aarch64-opt/bin/external/FP16 -iquoteexternal/clog -iquotebazel-out/aarch64-opt/bin/external/clog -iquoteexternal/pthreadpool -iquotebazel-out/aarch64-opt/bin/external/pthreadpool -iquoteexternal/FXdiv -iquotebazel-out/aarch64-opt/bin/external/FXdiv -iquoteexternal/cpuinfo -iquotebazel-out/aarch64-opt/bin/external/cpuinfo -Ibazel-out/aarch64-opt/bin/external/FP16/_virtual_includes/FP16 -Ibazel-out/aarch64-opt/bin/external/clog/_virtual_includes/clog -Ibazel-out/aarch64-opt/bin/external/pthreadpool/_virtual_includes/pthreadpool -Ibazel-out/aarch64-opt/bin/external/FXdiv/_virtual_includes/FXdiv -Ibazel-out/aarch64-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -isystem external/XNNPACK/include -isystem bazel-out/aarch64-opt/bin/external/XNNPACK/include -isystem external/XNNPACK/src -isystem bazel-out/aarch64-opt/bin/external/XNNPACK/src -isystem external/FP16/include -isystem bazel-out/aarch64-opt/bin/external/FP16/include -isystem external/pthreadpool/include -isystem bazel-out/aarch64-opt/bin/external/pthreadpool/include -isystem external/FXdiv/include -isystem bazel-out/aarch64-opt/bin/external/FXdiv/include -w -DAUTOLOAD_DYNAMIC_KERNELS '-std=c++14' -Iinclude -Isrc -O2 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc -o bazel-out/aarch64-opt/bin/external/XNNPACK/_objs/jit/1/1x8-aarch64-neonfma-cortex-a75.pic.o)
# Configuration: ce8f4d34c0d44ddff120a1f5ad2cdfaaab653410aefcb8fe64f7a37d66c62619
# Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc: In member function 'void xnnpack::aarch64::{anonymous}::Generator::generate(bool, size_t, size_t, size_t, float, float)':
external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc:48:39: error: 'numeric_limits' is not a member of 'std'
   48 |   const bool clamp_min = min != -std::numeric_limits<float>::infinity();
      |                                       ^~~~~~~~~~~~~~
external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc:48:54: error: expected primary-expression before 'float'
   48 |   const bool clamp_min = min != -std::numeric_limits<float>::infinity();
      |                                                      ^~~~~
external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc:49:39: error: 'numeric_limits' is not a member of 'std'
   49 |   const bool clamp_max = max != +std::numeric_limits<float>::infinity();
      |                                       ^~~~~~~~~~~~~~
external/XNNPACK/src/f32-igemm/1x8-aarch64-neonfma-cortex-a75.cc:49:54: error: expected primary-expression before 'float'
   49 |   const bool clamp_max = max != +std::numeric_limits<float>::infinity();
      |                                                      ^~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 387.892s, Critical Path: 129.24s
INFO: 2857 processes: 206 internal, 2651 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Seems to be caused by 
https://github.com/tensorflow/tensorflow/commit/b9f4c111ce9301240bd3d3b97449bc485ca52b15

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by mihaimaruseac** [comment]
CC @Maratyszcza

**Comment by ngzhian** [comment]
Will be fixed by https://github.com/google/XNNPACK/pull/2539
