### ISSUE TITLE
Getting incorrect value of lengthOutputTensor on iOS

### ISSUE THREAD

**Issue by mercksamir** [tensorflow/tensorflow#54270]
**System information**
- Using a stock example script provided in TensorFlow
- iOS
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9.10
- Bazel version (if compiling from source):3.7.2

**Current behavior**
I've used the stock example code snippet as mentioned below.

```
std::unique_ptr<tflite::FlatBufferModel> tflModel = nullptr;
tflite::ops::builtin::BuiltinOpResolver tflResolver;
std::unique_ptr<tflite::Interpreter> tflInterpreter;
tflModel = tflite::FlatBufferModel::BuildFromFile(pakgFilePath.c_str());
tflite::InterpreterBuilder(*tflModel, tflResolver)(&tflInterpreter);
tflInterpreter->AllocateTensors();

int32_t lengthInputTensor = tflInterpreter->input_tensor(0)->dims->data[1];
int32_t lengthOutputTensor = tflInterpreter->output_tensor(0)->dims->data[1];

tflInterpreter->Invoke();
```

The above code is executed on Android and iOS both but getting an incorrect value of **lengthOutputTensor** in iOS for the same file.

**Expected behavior**
The value of **lengthOutputTensor** on iOS should be the same as it's on Android for the same file.

Also, while going through the documentation, I've found below details. So is the above mentioned issue due to this work in progress for iOS?

<img width="1344" alt="Screenshot 2022-02-04 at 5 57 12 PM" src="https://user-images.githubusercontent.com/98508996/152529171-e67e17f3-9e2b-4a84-b564-e340d4386648.png">

**Comment by mercksamir** [comment]
Hi - Could anyone please let us know by when we can expect an update on this issue?

**Comment by sushreebarsa** [comment]
@mercksamir Sorry for the late response!
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mercksamir** [comment]
I've mentioned the code snippet in my initial comment though here you go.

```
std::unique_ptr<tflite::FlatBufferModel> tflModel = nullptr;
tflite::ops::builtin::BuiltinOpResolver tflResolver;
std::unique_ptr<tflite::Interpreter> tflInterpreter;
tflModel = tflite::FlatBufferModel::BuildFromFile(pakgFilePath.c_str());
tflite::InterpreterBuilder(*tflModel, tflResolver)(&tflInterpreter);
tflInterpreter->AllocateTensors();

int32_t lengthInputTensor = tflInterpreter->input_tensor(0)->dims->data[1];
int32_t lengthOutputTensor = tflInterpreter->output_tensor(0)->dims->data[1];

tflInterpreter->Invoke();
```

**Comment by mercksamir** [comment]
Could anyone at least just confirm whether it's an issue due to some work in progress for iOS or not?

**Comment by mercksamir** [comment]
Hi @jvishnuvardhan - Any update on this?

**Comment by mercksamir** [comment]
Could anyone please give an update in this issue?

**Comment by MeghnaNatraj** [comment]
Hello @mercksamir, does your model use metadata? Can you try to run run inference without metadata and let us know if you face the same issue? https://www.tensorflow.org/lite/guide/inference
