### ISSUE TITLE
tensorflow.contrib.layers.feature_column_ops with tf.placeholder tensors

### ISSUE THREAD

**Issue by pilipolio** [tensorflow/tensorflow#5427]
Following up on the TF.Learn tutorials demonstrating linear models with categorical variables (https://www.tensorflow.org/versions/r0.9/tutorials/linear/overview.html), I have tried to re-use the functions & abstractions from `tensorflow.contrib.layers.feature_column_ops` to hash, encode & cross my input categorical columns while still handling the rest of the computing in low-level TensorFlow.

However, when I pass a normal Tensor (or placeholder) as values of the `columns_to_tensors` parameters of `weighted_sum_from_feature_columns` (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/feature_column_ops.py#L460), it fails because of the `shape` parameter being not available.

Is there any way or plan to enable passing any Tensors other than SparseTensors to this function?

**Comment by aselle** [comment]
Please ask this question on StackOverflow as many users of TensorFlow contribute answers to those questions.. If you discover a concrete feature or bug in behavior, please repost here. Thanks!
