### ISSUE TITLE
Unintuitive error in learning rate type when saving then loading weights after further fitting

### ISSUE THREAD

**Issue by johanbluecreek** [tensorflow/tensorflow#54280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Ubuntu 20.04.3 LTS (or the colab-env)
- TensorFlow installed from (source or binary): binary (through pip) (or the colab-env)
- TensorFlow version: 2.7.0
- Python version: 3.8.10 (or the colab-env)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

The following procedure causes a fairly unintuitive `tensorflow.python.framework.errors_impl.InvalidArgumentError`:

1. Setup model
2. Compile model
3. Fit model with e.g. learning-rate scheduler callback (saving the history)
4. Save weights of model
5. Compile model using `learning_rate` from last epoch from previous fit (using saved history)
6. Fit model
7. Load the saved weights, which triggers `InvalidArgumentError `

see linked colab notebook for details.

What happens is that the type for the learning-rate changes when compiling the model the second time, causing a mismatch and the saved learning-rate fails to load. This appears unintuitive since both types for the learning-rate are apparently valid (can be used to perform a fit), but you cannot load if you accidentally changed the type.

**Describe the expected behavior**

Step 7. in the above should not produce an error.

**Standalone code to reproduce the issue**

This example code:

```python
import tensorflow as tf

X, y = tf.random.uniform((50,)), tf.random.uniform((50,))
X_val, y_val = tf.random.uniform((5,)), tf.random.uniform((5,))

lr_scheduler = tf.keras.callbacks.LearningRateScheduler(schedule=lambda epoch,lr: lr*0.995, verbose=1)

model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])

model.compile(optimizer=tf.keras.optimizers.SGD(), loss='mse')

history = model.fit(X, y, epochs=1, validation_data=(X_val,y_val), callbacks=[lr_scheduler])

model.save_weights('tmp_model')

model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=history.history['lr'][-1]*0.1),
    #optimizer=tf.keras.optimizers.SGD(learning_rate=float(history.history['lr'][-1]*0.1)), # work-around
    loss='mse'
)

model.fit(X, y, epochs=1, validation_data=(X_val,y_val), callbacks=[lr_scheduler])
model.load_weights('tmp_model')
```
outputs:
```
Epoch 00001: LearningRateScheduler setting learning rate to 0.00994999977760017.
2/2 [==============================] - 0s 126ms/step - loss: 0.6959 - val_loss: 0.9985 - lr: 0.0099

Epoch 00001: LearningRateScheduler setting learning rate to 0.0009900249862112105.
2/2 [==============================] - 0s 157ms/step - loss: 0.6430 - val_loss: 0.9910 - lr: 9.9002e-04
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-3d1de671fc08> in <module>()
     21 
     22 model.fit(X, y, epochs=1, validation_data=(X_val,y_val), callbacks=[lr_scheduler])
---> 23 model.load_weights(f'tmp_model')

1 frames
/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57     ctx.ensure_initialized()
     58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:
     61     if name is not None:

InvalidArgumentError: tensor_name = optimizer/learning_rate/.ATTRIBUTES/VARIABLE_VALUE; expected dtype double does not equal original dtype float [Op:RestoreV2]
```

notebook with code:

https://colab.research.google.com/drive/1FxwBUjUcw0U0FiL1LDGFbfCY7ocGQ8ij?usp=sharing

**Comment by mohantym** [comment]
Hi @johanbluecreek !  You have to save weights before loading weights. Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/209fb08281d158a0b9a42013c6b7a781/invalidargumenterror-bug.ipynb#scrollTo=gqh2NGrMfRld) and relevant [thread](https://keras.io/api/models/model_saving_apis/#saveweights-method) for reference.   Thanks!

**Comment by johanbluecreek** [comment]
> Hi @johanbluecreek ! You have to save weights before loading weights. Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/209fb08281d158a0b9a42013c6b7a781/invalidargumenterror-bug.ipynb#scrollTo=gqh2NGrMfRld) and relevant [thread](https://keras.io/api/models/model_saving_apis/#saveweights-method) for reference. Thanks!

The purpose was to load weights from before the second fit, not after.

Potential scenario is when doing fine-tuning after transfer learning: You set your downloadable model to `trainable=False`, and add and train your top layers, then set the layers of the whole model to `trainable=True`, what you then may want to do is to find an appropriate learning rate, which does not leave the already found minima too much. To do so you may want to load weights from after first fit, try one epoch with a new learning rate a few times before you find an appropriate one. Under such an approach, the error is triggered.

**Comment by mohantym** [comment]
Ok @johanbluecreek ! Thanks for the clarification . Please post this [Keras](https://github.com/keras-team/keras) repo too. Thanks!

**Comment by mohantym** [comment]
Ok @johanbluecreek ! Closing this issue here as it will be tracked in Keras repo. Thanks!
