### ISSUE TITLE
UnknownError: Failed to get convolution algorithm

### ISSUE THREAD

**Issue by Shanduur** [tensorflow/tensorflow#54283]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): *Linux Debian 10 @ GCP Vertex AI*
- TensorFlow installed from (source or binary): *Vertex AI Environment TensorFlow Enterprise 2.7 (Intel® MKL-DNN/MKL)*
- TensorFlow version (use command below): *TensorFlow Enterprise 2.7 (Intel® MKL-DNN/MKL)*
- Python version: *Python 3.7.12*
- Bazel version (if compiling from source): *N/A*
- GCC/Compiler version (if compiling from source): *N/A*
- CUDA/cuDNN version: *CUDA 11.2, cuDNN 8.3.0 (default from the Environment)*

- GPU model and memory: tested at both NVidia Tesla K80 and NVidia Tesla P3

**Describe the current behavior**

We get the following error (completely by random during training pipeline). Can appear during 1st batch or 200 batch of 1st epoch.

```
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[node spatio_ temporal _autoencoder/sequential/chong_tay_encoder/conv3d/Conv3D
(defined at /opt/conda/lib/python3.7/site-packages/keras/layers/convolutional.py:238)
11 [Op: inference predict function 4511]
```

**Describe the expected behavior**

Everything working?

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

To be honest, I have no idea... The issue is only visible on the Vertex AI, on Colab and our machines everything is okay... I am unable to share code, as we are using confidential datasets, that cannot be shared or easily reproduced.

**Other info / logs**

What we tried to do:
- remove `$HOME/.nv` folder
- reinstalled whole environment
- changed parameters of model to ensure that there is no memory shortage

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/8009147/tf_env.txt)

**Comment by mohantym** [comment]
Hi @Shanduur ! Could you  you try below options and let us know? Thanks!
1. Constrain memory growth . Add this code snippet at start of your solution. 
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  except RuntimeError as e:
    print(e)
```
2. Overwrite with this configuration CUDA 11.2 and CudaNN 8.1 (not 8.3) .[Reference](https://www.tensorflow.org/install/source#gpu)
