### ISSUE TITLE
TFlite model shows different output shape than TF for simple MLP

### ISSUE THREAD

**Issue by moberweger** [tensorflow/tensorflow#54287]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04**
- TensorFlow installation (pip package or built from source): **pip**
- TensorFlow library (version, if pip package or github SHA, if built from source): **v2.8.0-rc1-32-g3f878cff5b6 2.8.0**

### 2. Code
Standalone code to reproduce the issue can be found in the Colab gist [here](https://colab.research.google.com/gist/moberweger/aaadb484f3829dfab4e3e82b83212c02/untitled1.ipynb#scrollTo=clDg3HuITEJj)

### 3. Failure after conversion
The model conversion is successful, but the output shape of the generated model seems wrong. Note that the shape of the inference is correct, but the printed shapes are different.
There are two identical TF models exported (modelling an MLP as a conv and as a fully-connected layer). Both models have an output shape of `(None, 128, 2)` on the TF side.
The TFlite models show two different shapes (see `shape` and `shape_signature`) `[  1, 128,   2]` vs. `[1, 1, 2]`. Since the models are the same on the TF side, they should also match on the TFlite side.
The issue could be caused by some broadcasting/reshaping in the `Dense` layer (`tensordot`), since it looks like the second dimension is changed to "dynamic" after that layer.

**Comment by tilakrayal** [comment]
@moberweger ,
TensorFlow Lite is a lighter version of TensorFlow, which is specifically designed for the mobile platform and embedded devices. TFLite is intended to provide the ability to perform predictions on a trained model (load the model not to train the model). On the other hand TF is used to build (train) the model.

TFLite optimises the model using quantisation techniques which is dramatically reduces both the memory requirement and computational cost of using neural networks.Please take a look at this link [1](https://www.tensorflow.org/lite/api_docs/python/tf/lite/TFLiteConverter) and [2](https://www.tensorflow.org/lite/guide/inference).It helps.Thanks!

**Comment by moberweger** [comment]
Thanks @tilakrayal for getting back to me. I am aware of the objectives of TFlite. In my MWE, there is no quantization or other optimization involved in the model conversion and inference, but still I get the mismatch between the shapes, which can be confusing.

**Comment by tilakrayal** [comment]
@moberweger ,
Kindly open a tf discussion forum issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. Thanks!

**Comment by moberweger** [comment]
Thanks for your consideration @tilakrayal
