### ISSUE TITLE
How to make the ./configure find package in local place

### ISSUE THREAD

**Issue by GaofengCheng** [tensorflow/tensorflow#5428]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
My server cannot connect to the Internet, when I `./configure`, it will download package from Internet, of course this will fail. So I download the package manually.
E.G.
`ERROR: package contains errors: tensorflow/core/debug.
ERROR: error loading package 'tensorflow/core/debug': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /mnt/a/usr/75c879a7665c1f6bb168362b3b0eb86b/external/protobuf: Error downloading http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /mnt/a/usr/75c879a7665c1f6bb168362b3b0eb86b/external/protobuf/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: Failed to connect to http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz : github.com.`

I download the `protobuf-008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz` and move it under `/mnt/a/usr/75c879a7665c1f6bb168362b3b0eb86b/external/protobuf/`, but it still fails. It seems the `./configure` will ignore the local package

Anyway to solve this...? It's troubling to install tensorflow on the NFS without Internet.
### Environment info
Operating System:
Linux gs07 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Installed version of CUDA and cuDNN: cuda 8.0 cudnn 5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
-rw-r--r-- 1 root staff   558720 Nov  4 10:59 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root staff       16 Nov  4 10:59 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root staff       19 Nov  4 10:59 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root staff   415432 Nov  4 10:59 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root staff   775162 Nov  4 10:59 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root staff 79337624 Nov  4 11:10 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root staff 79337624 Nov  4 11:10 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root staff 79337624 Nov  4 11:10 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root staff 69756172 Nov  4 11:10 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by zafartahirov** [comment]
Might be similar to #587 and #5029

**Comment by zafartahirov** [comment]
Can you try installing the protobuf using `pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp27-none-linux_x86_64.whl`

**Comment by GaofengCheng** [comment]
I use ' pip install --upgrade protobuf-3.0.0-cp27-none-linux_x86_64.whl' but get:
```
Unpacking ./protobuf-3.0.0-cp27-none-linux_x86_64.whl
Downloading/unpacking six>=1.9 (from protobuf==3.0.0)
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement six>=1.9 (from protobuf==3.0.0)
Cleaning up...
No distributions at all found for six>=1.9 (from protobuf==3.0.0)
Storing debug log for failure in /home/chenggaofeng/.pip/pip.log
```
@zafartahirov  any idea?

**Comment by zafartahirov** [comment]
This is odd. Can you show the contents of the `pip.log`? I am using OS X Sierra, but `pip install` works fine, maybe it is only on Linux?

Here is my run sequence:
```bash
$> mkvirtualenv dev-test
(dev-test) $> wget https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp27-cp27m-macosx_10_11_x86_64.whl
protobuf-3.0.0-cp27-none- 100%[===================================>]   4.58M  2.33MB/s    in 2.0s
(dev-test) $> pip install --upgrade protobuf-3.0.0-cp27-cp27m-macosx_10_11_x86_64.whl
Processing ./protobuf-3.0.0-cp27-cp27m-macosx_10_11_x86_64.whl
Requirement already up-to-date: setuptools in /Users/zafar/.virtualenvs/dev-test/lib/python2.7/site-packages (from protobuf==3.0.0)
Collecting six>=1.9 (from protobuf==3.0.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, protobuf
Successfully installed protobuf-3.0.0 six-1.10.0
```

**Comment by AntonyM55** [comment]
how about edit /tensorflow/workspace.bzl
change url to your local place
for example chang
url = "http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz",
to 
url = "file:////mnt/a/usr/bzip2-1.0.6.tar.gz",

**Comment by GaofengCheng** [comment]
@zafartahirov I download the source code of mock six protobuf etc... and make it....

**Comment by GaofengCheng** [comment]
@zafartahirov  I do like this:
`sudo pip install --upgrade six-1.9.0-py2.py3-none-any.whl`
```
Unpacking ./six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six
Cleaning up...
```
It shows the six installation is successful.
but` pip show six`:
```
Name: six
Version: 1.8.0
Location: /usr/lib/python2.7/dist-packages
Requires:
``` 
any idea? :)

**Comment by zafartahirov** [comment]
@GaofengCheng What is your environment setup? Would it be possible to create a clean virtual environment and test it there? Also, can you provide the `pip list` and content of `pip.log`

I think this is a related by different issue -- because even after install, your pip is using a different version, my suspicion is that your `python` and `pip` are located in different locations. If you try using `virtualenv`, it might fix that.

**Comment by GaofengCheng** [comment]
@zafartahirov I find the way to install. First all the packages like six, mock update using `apt`, the python have default installed mock, six but the version is very low(at least in the debian jessie stable), OS will seem ignore the manually updating. Using the `apt`, installation of tensor(whl) is very easy.

**Comment by GaofengCheng** [comment]
@zafartahirov Any way, Thx for your help!

**Comment by GaofengCheng** [comment]
@AntonyM55 it seems change http url directly to local location doesn't work, any other idea?

**Comment by GaofengCheng** [comment]
@AntonyM55  I just miss the `file:///`..... thxs! but I have encountered another problem. There is a url direct  ed to fit:
```
  native.new_git_repository(
    name = "linenoise",
    commit = "c894b9e59f02203dbe4e2be657572cf88c4230c3",
    init_submodules = True,
    remote = "https://github.com/antirez/linenoise.git",
    build_file = str(Label("//:linenoise.BUILD")),
  )
```
I change` remote = "https://github.com/antirez/linenoise.git",` to remote = `"file:////nobackup/datapool/project/proa/chenggaofeng/kaldi_tens/dependences/linenoise",` 
but when I `./configure`,  it shows:
```
ERROR: /nobackup/datapool/project/proa/usr/kaldi_tens/tensorflow-master/tensorflow/tools/tfprof/BUILD:22:1: no such package '@linenoise//': Invalid Git repository URI: Invalid remote: origin and referenced by '//tensorflow/tools/tfprof:tfprof'.
ERROR: /nobackup/datapool/project/proa/usr/kaldi_tens/tensorflow-master/tensorflow/tools/tfprof/BUILD:22:1: no such package '@linenoise//': Invalid Git repository URI: Invalid remote: origin and referenced by '//tensorflow/tools/tfprof:tfprof'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

**Comment by mrtonnet** [comment]
Hello, GaofengCheng

Did you solve this problem? If so, could you explain how you solve this?

My situation is exactly same as you. My company's firewall blocks my server from the Internet connection.  So no Internet connection is available for my server. This caused tens of problems, but I solved all the error except this part. I'll restate my problem as follows. When I run
  $ ./configure
, the following command fails.
   $ bazel fetch //tensorflow/...

This bazel command is supposed to fetch all the packages in target tensorflow from the Internet. I also downloaded links manually with wget, but it seems something is wrong when I run the next command in the TensorFlow installation manual.

$ bazel build -c opt -config=cuda //tensorflow/cc:tutorials_example_trainer

I'd appreciate your feedback.
