### ISSUE TITLE
TFLite 2.8.0 iOS framework cplusplus build not c

### ISSUE THREAD

**Issue by deshan** [tensorflow/tensorflow#54289]
**System information**
- iOS framework generation
- build from source
- tflite 2.8.0

**How to build for iOS c++ not c?**

I have common tflite code for mac, win, android and iOS which was developed with c++. 

eg : 
```
#include "tensorflow/lite/model.h"
...
tflite::FlatBufferModel::BuildFromBuffer(.., ..);
```
But above does not compile with TFLite framework I built with following. My guess is it's only c not c++.
`bazel build --config=ios_fat -c opt tensorflow/lite/ios:TensorFlowLiteC_framework`

How to build tflite iOS framework for c++?

Thanks

**Comment by mohantym** [comment]
Hi @deshan! Could you check these two threads for answer ? Please check out r2.8 branch while checking out branches. Ref [1](https://github.com/tensorflow/tensorflow/issues/43955#issuecomment-859731256), [2](https://stackoverflow.com/questions/59468514/use-tf-lite-c-api-for-both-android-and-ios).  Thanks!

**Comment by deshan** [comment]
@mohantym with the help of Ref 1 I was able to do that.
Thank You
