### ISSUE TITLE
module 'tensorflow.compat.v2.__internal__' has no attribute 'monitoring'

### ISSUE THREAD

**Issue by dryginmo** [tensorflow/tensorflow#54286]
Hello,

when following the tensor flow tutorial (https://www.youtube.com/watch?v=tPYj3fFJGjk at 1:49:00) I get the following error:
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'monitoring'.
So far I have only found one hint online, suggesting to uninstall tensorflow and reinstall tensorflow-cpu, yet this did not solve the problem.
Can anyone come up with a working solutoin? Would you need more information?

Here my system specs:
- Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.4.1
- Numpy: 1.21.2
- Python version: 3.8.12
- IPython 7.29.0

**Comment by mohantym** [comment]
Hi @dryginmo ! Have you checked in [TF 2.8](https://colab.sandbox.google.com/gist/mohantym/493b1fa67490158457af1b281f826c59/core-learning-algorithms.ipynb#scrollTo=QdmENcK6TBrI) version yet?

**Comment by dryginmo** [comment]
Upgrading Tensorflow to 2.8.0 and Numpy to 1.22.2 solved the problem.
Thanks :)
