### ISSUE TITLE
TFLite model working in multi-processing but not multi-threading

### ISSUE THREAD

**Issue by rohanmishra21** [tensorflow/tensorflow#54282]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur (M1)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): binary (pip package)
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.12
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: M1 Chip

**Describe the current behavior**
Tensorflow lite model doesn't work when using multi-threading using `multiprocessing.dummy.Pool` in Python, while it does work in multi-processing.

**Describe the expected behavior**
Tensorflow Lite model should have worked in both.

**Standalone code to reproduce the issue**
(Sample TFLite model attached here: [model.tflite.zip](https://github.com/tensorflow/tensorflow/files/8008907/model.tflite.zip))

```
import math
import numpy as np
import os
import tensorflow as tf
import time

#use below one for multi-threading
from multiprocessing.dummy import Pool 

#use below one for multi-processing
#from multiprocessing import Pool 

from multiprocessing import cpu_count
from tqdm import tqdm

interpreter = None
input_index = None
output_index = None

def init_interpreter(model_path):
    global interpreter
    global input_index
    global output_index
    interpreter = tf.lite.Interpreter(model_path=model_path)
    input_index = interpreter.get_input_details()
    output_index = interpreter.get_output_details()
    interpreter.allocate_tensors()
    print('done init')

def get_prediction(img_name):
    img = np.random.randn(1, 256, 256, 3).astype(np.float32)
    interpreter.set_tensor(input_index[0]["index"], img)
    interpreter.invoke()
    pred = interpreter.tensor(output_index[0]["index"])()[0][0]
    return pred

def main():
    samples = list(range(100))
    model_path = 'model.tflite'
    with Pool(processes=2, initializer=init_interpreter, initargs=(model_path,)) as pool:
        preds = list(tqdm(pool.imap(get_prediction, samples)))

if __name__ == '__main__':
    main()

```

**Other info / logs**  It gives the following error when using TFLite model with multi-threading
```
RuntimeError: There is at least 1 reference to internal data
      in the interpreter in the form of a numpy array or slice. Be sure to
      only hold the function returned from tensor() if you are using raw
      data access.
```

The problem that we are working on is memory sensitive and requires many models to be loaded into the memory and thus, we can't use multi-processing as it leads to the same model being loaded as many times as the number of processes. Is there any way to use TFLite models in multi-threading? Any help would be much appreciated. Thanks!

**Comment by sushreebarsa** [comment]
@rohanmishra21 Could you please try with the latest TF v2.8.0 and refer this [link](https://www.tensorflow.org/lite/performance/best_practices) ?Please let us know if it helps.
Thank you!

**Comment by PandiRaja18** [comment]
I'm encountering the same issue when attempting to infer a TFLite model using C++ multithreading. If I load the model and allocate tensors to the interpreter for each inference, everything works fine. However, if I try to load and initialize the model just once (using the following code):
 `tflite::FlatBufferModel::BuildFromFile(model_path);
tflite::ops::builtin::BuiltinOpResolver resolver;
tflite::InterpreterBuilder builder(*this->model, resolver);`. 

and then attempt to run inferences with different input vectors in a multithreaded context, it either produces incorrect results or leads to a core dump. Does TFLite handle multi-threaded requests internally, or do I need to implement thread safety mechanisms myself,  such as using locks? And if I use locks every time I run an inference with different inputs, could that create a performance bottleneck?
