### ISSUE TITLE
Do you have plan to build with C++17 by default?

### ISSUE THREAD

**Issue by guizili0** [tensorflow/tensorflow#54294]
Hi,

I found TensorFlow has build option to build with C++17, but seems the release version binary did not use this one.
Do you have plan to build with C++17 in release binary?

**Comment by sushreebarsa** [comment]
@guizili0 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by guizili0** [comment]
**System information**
- OS Platform and Distribution : Linux Ubuntu 20.04
- Mobile device : NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.8
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Want to confirm the C++ standard of the release binary, if it is not C++17, do you have plan to use C++17? thanks.

**Comment by guizili0** [comment]
@sushreebarsa  Thanks.
How about the linux side? And from the compiler version how can I figure out the C++ standard? thanks.

**Comment by sushreebarsa** [comment]
@guizili0 GCC compiler 7.3.1. supports c++17.
While building Tensorflow from source you can mention gcc version as 7.3.1 in the **./configure**.Please check [this](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc) link for reference.Thanks!

**Comment by guizili0** [comment]
@sushreebarsa Thanks.
Yes, you are right, TF can configure C++17, so I try to know the [TF release binary](https://pypi.org/project/tensorflow/) C++ standard. thanks.

**Comment by mihaimaruseac** [comment]
Hi @guizili0 

I am currently working on enabling C++17 dialect in entirety of TF. While `.bazelrc` supports the `--config=c++1z` (and similar), this was experimental and only for some targets, not the pip package.

Currently I got the macos build to fully work in C++17, have 3 failing tests on Linux and some compile errors on Windows. If all goes well, by next TF release we should be on C++17

**Comment by guizili0** [comment]
@mihaimaruseac  Thanks for this information? Can you help to share how to check C++17 is enabled? Or do you have somewhere to get these information? I can check later. Thanks.

**Comment by mihaimaruseac** [comment]
I will announce on this issue and the [forum](https://discuss.tensorflow.org/latest) when the switch is done. Probably we'll also remove C++14 stuff from `.bazelrc`

**Comment by guizili0** [comment]
@mihaimaruseac  great thanks!

**Comment by mihaimaruseac** [comment]
Keeping open util the switch

**Comment by gadagashwini** [comment]
Hi @guizili0, By default, build TF in C++ 17 mode.
```
build:android --cxxopt=-std=c++17
build:android --host_cxxopt=-std=c++17
build:ios --cxxopt=-std=c++17
build:ios --host_cxxopt=-std=c++17
build:linux --cxxopt=-std=c++17
build:linux --host_cxxopt=-std=c++17
build:macos --cxxopt=-std=c++17
build:macos --host_cxxopt=-std=c++17
build:windows --cxxopt=/std:c++17
build:windows --host_cxxopt=/std:c++17
```
For more information refer this [link](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L334). Thank you!

**Comment by guizili0** [comment]
@gadagashwini thanks, is this from 2.10 release? Or just in TF master.

**Comment by mihaimaruseac** [comment]
Master and TF 2.10 will both support C++17 (that is, you can compile code in C++17 from both `master` and `r2.10` branches). I just forgot to close this issue when we landed the fix, my bad.
