### ISSUE TITLE
tflite with hexagon delegate get poor performance while running mobilenet_quant_v1_224.tflite on Snapdragon 845

### ISSUE THREAD

**Issue by peyer** [tensorflow/tensorflow#54298]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MeiZu 16th, Snapdragon 845
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch, commit hash : 851b83d0ef9659bb83b4f8c56708fb045fe276dc
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): ndk 20

After push all libhexagon_*.so to phone, I run benchmark_model with option "--use_hexagon=true --hexagon_profiling=true", then get results below
![image](https://user-images.githubusercontent.com/19945545/152995700-7ecb5c09-a39a-483e-bd54-6870c3fb471e.png)

It seem that symbol of remote_handle_control not found, and the performance just so poor which even almost reach 60ms

**Comment by sushreebarsa** [comment]
@peyer 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), and please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by peyer** [comment]
ok. As I have said, I just use master branch with newest commit 851b83d0ef9659bb83b4f8c56708fb045fe276dc

Below is my configure results
![image](https://user-images.githubusercontent.com/19945545/153165875-009dedd6-b7cb-4425-977d-fd6ac99d7325.png)

Then I just use bazel to compile tflie
![image](https://user-images.githubusercontent.com/19945545/153165999-d4b7f605-8903-47e7-be6e-b0d4adced30e.png)

After all, I push all libhexagon_*.so and mobilenet_quant_v1_224.tflite, benchmark_model, then got
![image](https://user-images.githubusercontent.com/19945545/153166688-d3a384dd-8f12-4378-a7c2-c39ec769f6a1.png)

I think it is just too simple to reproduce similar results as well as running on Snapdragon 845 device

**Comment by karimnosseir** [comment]
For the remote handle log message, it is harmless in your case.

As for the latency, i think you are mistaken. From the log you shared, the inference is taking 6358 us, which is 6.358 ms. not 60ms.
This looks working correctly to me.

**Comment by peyer** [comment]
@karimnosseir Sorry to brother you for my mistake. Another question, does tflite support SnapDragon with Hexagon backend?

**Comment by peyer** [comment]
@karimnosseir Sorry to brother you for my mistake. Another question, dose tflite support inference on SnaDragon 888 with Hexagon dsp backend ?

**Comment by karimnosseir** [comment]
@peyer np.
Sadly no, Snapdragon 888 doesn't leverage Hexagon NN API. They had a new APIs for executing on the DSP, and hexagon delegate doesn't work with it.
