### ISSUE TITLE
Suggested changes in tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb

### ISSUE THREAD

**Issue by raulsoutelo** [tensorflow/tensorflow#54300]
Hi,

I ran the notebook tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb and I encountered some issues that I believe it would good to change:

1) In cell 2, tensorflow is installed and in cell 3 a couple of packages are imported that would not be installed in a fresh environment: pandas and matplotlib. I believe it would be good to install these two together with tensorflow.

2) In cell 33, the size of the models is plotted in a table. I got 160 bytes for size_tf while the total size of the model folder for me is 107573. The following code does give me this number:

```
def get_dir_size(path='.'):
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_dir_size(entry.path)
    return total
size_tf = get_dir_size(MODEL_TF)
```

3) If we do not want to commit the models generated when running the examples, it may be good to add the following line to the .gitignore file?

```
tensorflow/lite/micro/examples/*/train/models
```

I can create a PR with these changes if they make sense. 

Thanks!

**Comment by tilakrayal** [comment]
@raulsoutelo , 
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced].
