### ISSUE TITLE
Linking of rule '//tensorflow/java:libtensorflow_jni.dylib' failed (Exit 1)

### ISSUE THREAD

**Issue by crane76** [tensorflow/tensorflow#54303]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.4
- Python version: 3.8.12(installed with brew, python@3.8)
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): How can I detect?
- CUDA/cuDNN version:
- GPU model and memory: Not using GPU, 16g memory

I'm using macbookpro m1.
I executed bazel like this.
`bazel build --config opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni //tensorflow/java:pom`

Error message was like this
`
ERROR: ~/tensorflow/tensorflow/java/BUILD:416:1: Linking of rule '//tensorflow/java:libtensorflow_jni.dylib' failed (Exit 1)
ld: warning: pointer not aligned at address 0x91C12B6 (_grpc_lb_v1_ClientStats_fields + 166 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C1225 (_grpc_lb_v1_ClientStats_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C1312 (_grpc_lb_v1_LoadBalanceRequest_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C12F5 (_grpc_lb_v1_LoadBalanceRequest_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C1372 (_grpc_lb_v1_InitialLoadBalanceResponse_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C13B5 (_grpc_lb_v1_ServerList_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C1412 (_grpc_lb_v1_LoadBalanceResponse_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C13F5 (_grpc_lb_v1_LoadBalanceResponse_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libgrpclb_proto.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x91C2886 (_grpc_gcp_AltsContext_fields + 166 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(altscontext.pb.o))
ld: warning: pointer not aligned at address 0x91C29AD (_grpc_gcp_StartClientHandshakeReq_fields + 253 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2973 (_grpc_gcp_StartClientHandshakeReq_fields + 195 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2956 (_grpc_gcp_StartClientHandshakeReq_fields + 166 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2939 (_grpc_gcp_StartClientHandshakeReq_fields + 137 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2A12 (_grpc_gcp_ServerHandshakeParameters_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2A72 (_grpc_gcp_StartServerHandshakeReq_HandshakeParametersEntry_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2B46 (_grpc_gcp_StartServerHandshakeReq_fields + 166 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2B29 (_grpc_gcp_StartServerHandshakeReq_fields + 137 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2AD2 (_grpc_gcp_StartServerHandshakeReq_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2BBF (_grpc_gcp_HandshakerReq_fields + 79 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2BA2 (_grpc_gcp_HandshakerReq_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2B85 (_grpc_gcp_HandshakerReq_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2CB3 (_grpc_gcp_HandshakerResult_fields + 195 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2C79 (_grpc_gcp_HandshakerResult_fields + 137 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2D2F (_grpc_gcp_HandshakerResp_fields + 79 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(handshaker.pb.o))
ld: warning: pointer not aligned at address 0x91C2DB2 (_grpc_gcp_RpcProtocolVersions_fields + 50 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(transport_security_common.pb.o))
ld: warning: pointer not aligned at address 0x91C2D95 (_grpc_gcp_RpcProtocolVersions_fields + 21 from bazel-out/darwin-opt/bin/external/grpc/libalts_proto.a(transport_security_common.pb.o))
ld: unaligned pointer(s) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 5379.928s, Critical Path: 327.92s
INFO: 11618 processes: 11618 local.
FAILED: Build did NOT complete successfully
`

I think `ld: unaligned pointer(s) for architecture x86_64` is the main problem.
How can I build tensorflow with jni?

Thanks.

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@crane76 We see that you are using older version of TF v2.1.4 , we recommend you to kindly upgrade to TF v2.4 or latest . Please have a look at [ this ](https://www.tensorflow.org/install/source#macos)link and also refer the tested build configurations. 
Please let us know if it helps? Thanks!

**Comment by crane76** [comment]
@sushreebarsa, I have an project that was developed with TF 2.1. So I wanted to use 2.1.
Is there no way to use TF 2.1 on M1 Mac?

I'll try TF 2.4 also.

Thanks.

**Comment by sushreebarsa** [comment]
@crane76 Older version is no longer actively supported ,please refer[ this ](https://github.com/tensorflow/tensorflow/issues/52915#issuecomment-961288304)comment.Could you please let us know if you have tried with the latest version?
Thanks!

**Comment by crane76** [comment]
@sushreebarsa  Thanks for reply.
Yes, I tried with 2.4, 2.7 and it was successful.
But, I have to verify the result was same between 2.1.x vs 2.4.x.
Thanaks.

**Comment by sushreebarsa** [comment]
@crane76 Thank you for the update!
Glad it is working fine for you.Please let us know if we can move this issue to closed status as if it is resolved for you ?
Thanks!
