### ISSUE TITLE
`tf.compat.v1.layers.AveragePooling3D` lack support for float64

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54318]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf

pool_size = [3,3,3]
strides = 2
padding = "valid"
x = tf.random.uniform([1, 11, 12, 10, 4], dtype=tf.float64)
print(tf.compat.v1.layers.AveragePooling3D(pool_size,strides,padding=padding,)(x))
```
throws 
```
NotFoundError: Exception encountered when calling layer "average_pooling3d" (type AveragePooling3D).

Could not find device for node: {{node AvgPool3D}} = AvgPool3D[T=DT_DOUBLE, data_format="NDHWC", ksize=[1, 3, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 2, 1]]
All kernels registered for op AvgPool3D:
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_FLOAT]
 [Op:AvgPool3D]
```

**Expected output**
`tf.compat.v1.layers.AveragePooling3D` should be able to accept a `float64` input.

**Comment by sushreebarsa** [comment]
@ArrowIntoTheSky` tf.compat.v1.layers.AveragePooling3D` API was designed for TensorFlow v1, please have a look at [this](https://www.tensorflow.org/api_docs/python/tf/compat/v1/layers/AveragePooling3D) link . TF v1.x is not actively supported so we recommend you to rewrite the code using native TF v2 API.Please refer this migration [guide](https://www.tensorflow.org/guide/migrate) to migrate rest of your code.Thanks!
