### ISSUE TITLE
`tf.math.asin` lack support for complex

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54317]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf

x = tf.complex(tf.random.uniform([4], dtype=tf.float64),tf.random.uniform([4], dtype=tf.float64))
print(tf.math.asin(x))
# Could not find device for node: {{node Asin}} = Asin[T=DT_COMPLEX128]
```

**Expected output**
According to the document [tf.math.asin](https://www.tensorflow.org/api_docs/python/tf/math/asin), it should be able to accept a complex input.

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e984b885c1efc3c9cc06b3659914c4da/54317.ipynb).

**Comment by yongtang** [comment]
Added a PR #54356 for the complex support of tf.math.asin.
