### ISSUE TITLE
TensorFlow Lite 2.8.0, benchmark_model build, error C2065: 'M_PI': undeclared identifier

### ISSUE THREAD

**Issue by Jukyy** [tensorflow/tensorflow#54323]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 21H1 19043.1526
- TensorFlow installed from (source or binary): None
- TensorFlow version: 2.8.0
- Python version: Python 3.7.6
- Installed using virtualenv? pip? conda?: None
- Bazel version (if compiling from source): None, using CMake version 3.19.2
- GCC/Compiler version (if compiling from source): Microsoft Visual Studio Professional 2019, Version 16.11.6
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**

During benchmark_model build I've received following error:
```
D:\Git_repos\tensorflow\tensorflow/core/lib/random/random_distributions_utils.h(83,27): error C2065: 'M_PI': undeclared identifier [D:\Git_repos\tensorflow\tensorflow\lite\build_win_2_8\tensorflow-lite.vcxpro
j]
D:\Git_repos\tensorflow\tensorflow/core/lib/random/random_distributions_utils.h(83,15): error C2737: 'v1': const object must be initialized [D:\Git_repos\tensorflow\tensorflow\lite\build_win_2_8\tensorflow-li
te.vcxproj]
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I've tried to build benchmark_model (tag v2.8.0) on Windows with following steps:
```
cd tensorflow\tensorflow\lite
mkdir build_win_2_8
cd build_win_2_8
cmake ..
cmake --build . -j -t benchmark_model --config Release
```

**Any other info / logs**

I've managed to fix this with following code change:

```patch
index f09b32f63d3..65c8d90b919 100644
--- a/tensorflow/core/lib/random/random_distributions_utils.h
+++ b/tensorflow/core/lib/random/random_distributions_utils.h
@@ -25,6 +25,10 @@ limitations under the License.
 namespace tensorflow {
 namespace random {

+#ifndef M_PI
+  #define M_PI 3.14159265358979323846
+#endif
+
 // Helper function to convert an 32-bit integer to a float between [0..1).
 PHILOX_DEVICE_INLINE float Uint32ToFloat(uint32_t x) {
   // IEEE754 floats are formatted as follows (MSB first):
```

Is this a correct way of solving this issue or am I missing something in the build process?

**Comment by Jukyy** [comment]
Are there any updates regarding this issue?

Just a heads up, I tried this on a different Windows machine which is running Visual Studio 2017 version 15.9.5 and I got the same error. On that machine I was able to fix this with a patch mentioned in the issue description.

It seams to me that this is an issue on a TensorFlow side because documentation doesn't specify any specific steps (link: https://www.tensorflow.org/lite/guide/build_cmake#step_6_build_tensorflow_lite_benchmark_tool_and_label_image_example_optional).

**Comment by Jukyy** [comment]
I tried building with Bazel (version 4.2.1), but now I get following error:

```
tensorflow/lite/nnapi/sl/SupportLibrary.cc(20): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```

For some reason Bazel tries to build with Linux header on Windows. This just raises more questions and we are diverging from an original issue at hand which is solving `error C2065: 'M_PI': undeclared identifier` on Windows platform.

The code at question was added in this commit https://github.com/tensorflow/tensorflow/commit/89428690d177fb2577359e682687f4022a89ec23 (this part of the source code wasn't used in previous TFLite builds). Also TFLite source code recognizes that some macros are not available on all platforms https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/lite/kernels/internal/constants.h#L19 

To me it this seems like an simple oversight where you didn't account for M_PI being missing on Windows platform. Simply adding this definition as I have shown in issue description should solve the problem because this is not the first time in TensorFlow source code where this fix was added (example: https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/lite/experimental/microfrontend/lib/window_util.c#L23).

**Comment by augustineam** [comment]
Using cmake I just added `/D_USE_MATH_DEFINES` to `CMAKE_CXX_FLAGS` and it built the C shared library without problems

```
> cmake -GNinja ..\tensorflow\tensorflow\lite\c -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /GR /EHsc /D_USE_MATH_DEFINES"
```

**Comment by Jukyy** [comment]
@augustineam I've generated cmake project like this
```
cmake .. -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /GR /EHsc /D_USE_MATH_DEFINES"
```
After that I've managed to build `benchmark_model` target successfully without resorting to a code changes.

That being said, what is the actual solution to this issue?
It should be one of the following:

1. Adding MI_PI definition as I suggested in an issue description
2. Adding those `CMAKE_CXX_FLAGS` to a TensorFlow Lite CMake
3. Adding those instruction to a CMake build documentation as an known issue for a Windows platform

**Comment by MeghnaNatraj** [comment]
@Jukyy The suggestion 1. has [already been added to the `random_distributions_utils.h` file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/random/random_distributions_utils.h#L25-L27). This is the preferred solution.
