### ISSUE TITLE
NotFoundError：dlopen(.../roi_pooling.so, 6): image not found

### ISSUE THREAD

**Issue by Anthony1011** [tensorflow/tensorflow#54326]
I try to run Faster_RCNN_TF from this source：
https://github.com/smallcorgi/Faster-RCNN_TF#installation-sufficient-for-the-demo
and I get this error can't solve.
--------------------------------------------------------------------------------
...line 60, in load_op_library 
lib_handle = py_tf.TF_LoadLibrary(library_filename)

tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/anthony/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so, 6): image not found

--------------------------------------------------------------------------------
Environment：
Run on the Mac m1  chip
macOS：11.6.1
Python：3.7.11
TensorFlow：2.0.0
TensorFlow install form anaconda
GPU model and memory：M1 GPU,16 GB RAM
Bazel version：N/A
CUDA/cuDNN：N/A 

--------------------------------------------------------------------------------
I have solved most of error so far but I can't find a solution for this error.
I would appreciate any ideas.

**Comment by tilakrayal** [comment]
@Anthony1011 ,
We see that you are using tf version 2.0 which is not actively supported, please update to tensorflow v2.7 and let us know if you are facing same issue.Also please take a look at this [link](https://github.com/tensorflow/tensorflow/issues/53309#issuecomment-986657957).Thanks!
