### ISSUE TITLE
Cant install TF2

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [tensorflow/tensorflow#54327]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version: any
- Python version: 3.7 (and same with 3.8)
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: i dont know this
- GPU model and memory: 64gb ram. No gpu i guess? (Because its VPS)

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow
pip3 install tensorflow
( Any of those 2 )
```bash
Same when trying install 2.3.1
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.3.1 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.3.1 (from -r requirements.txt (line 5))
```

**Error**
```bash
root@vm:~/bot/DolboNet# pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by sushreebarsa** [comment]
@MrMasrozYTLIVE We see that you are using older version of TF v2.3.1 and older versions are no longer supported. We recommend you to kindly upgrade to TF v2.4 or latest . Please have a look at [ this ](https://www.tensorflow.org/install/source#ubuntu)link and also refer the tested build [configurations](https://www.tensorflow.org/install/source#tested_build_configurations). 
Please let us know if it helps?Thanks!
