### ISSUE TITLE
tf.TensorArray as a FIFO ???

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#54336]
Hello,

  [here](https://github.com/keras-team/keras/issues/16015) I was pointed to use `tf.TensorArray` instead of `tf.Variable` or `tf.queue.FIFOQueue` for making FIFO contained in custom layer. Is it an effective way? Exist any alternative here?

If it's the most effective method how can I replace `self.queue.assign(tf.concat([self.queue[timesteps:, :], inputs], axis=0))` with methods of `tf.TensorArray`?

## Code
```python
class FIFOLayer(Layer):
    def __init__(self, window_size, **kwargs):
        super(FIFOLayer, self).__init__(**kwargs)

        self.window_size = window_size
        self.count = 0

    def build(self, input_shape):
        super(FIFOLayer, self).build(input_shape)

        self.queue = self.add_weight(
            name="queue",
            shape=(self.window_size, input_shape[-1]),
            initializer=tf.initializers.Constant(value=np.nan),
            trainable=False,
        )

    def call(self, inputs, training):
        timesteps = tf.shape(inputs)[0]

        # check if batch_size is more than queue capacity
        if timesteps > self.window_size:
            raise ValueError()

        # 1. append new state to queue
        self.queue.assign(tf.concat([self.queue[timesteps:, :], inputs], axis=0))
        self.count += timesteps

        # 2. feed-forward
        if self.count < self.window_size:
            # generate mask
            attention_mask = tf.cast(
                tf.math.reduce_all(
                    tf.math.logical_not(tf.math.is_nan(self.queue)), axis=-1
                ),
                dtype=tf.float32,
            )
            attention_mask = tf.matmul(
                attention_mask[..., tf.newaxis],
                attention_mask[..., tf.newaxis],
                transpose_b=True,
            )
            return self.queue[tf.newaxis, ...], attention_mask
        # !!! check overflow
        elif self.count > self.window_size:
            self.count = self.window_size

        return self.queue[tf.newaxis, ...], None

    @property
    def is_full(self):
        return self.count == self.window_size

    def clear(self):
        self.count = 0
        self.queue.assign(tf.fill(self.queue.shape, np.nan))


l = FIFOLayer(window_size=10)
for i in range(6):
    x = tf.random.normal((2, 12))
    y = l(x)
    print(y)

print(l.is_full, "\n\n")

l.clear()

print(l(x))
print(l.is_full, "\n\n")
```

Thanks a lot for your time.
Have a nice day.

**Comment by markub3327** [comment]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey 12.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: Python 3.9.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Apple M1

This question is about what is the best practice with TensorFlow.

1. Is the best practice using `tf.TensorArray` instead of `tf.Variable` or `tf.queue.FIFOQueue` for making FIFO contained in the custom layer (above is the example code).
2. If it's the most effective method how can I replace self.queue.assign(tf.concat([self.queue[timesteps:, :], inputs], axis=0)) with methods of tf.TensorArray?

Thanks a lot.
Have a nice day.

**Comment by markub3327** [comment]
Now I have an issue when I applied `tf.TensorArray` to `tf.data.dataset.map`.

```python
class FIFOLayer(tf.keras.layers.Layer):
    def __init__(self, window_size, **kwargs):
        super(FIFOLayer, self).__init__(**kwargs)

        self.window_size = window_size
        self.count = 0

    def build(self, input_shape):
        super(FIFOLayer, self).build(input_shape)
        self.features = input_shape[-1]

        self.queue_array = tf.TensorArray(dtype=tf.float32, size=self.window_size)
        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.fill((self.window_size, self.features), np.nan),
        )

    def call(self, inputs, training):
        timesteps = tf.shape(inputs)[0]
        tf.print(timesteps)

        # check if batch_size is more than queue capacity
        #if timesteps > self.window_size:
        #    raise ValueError()

        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.concat(
                [
                    self.queue_array.gather(tf.range(timesteps, self.window_size)),
                    inputs,
                ],
                axis=0,
            ),
        )
        queue_tensor = self.queue_array.stack()
        self.count += timesteps
        # 2. feed-forward
        if self.count < self.window_size:
            # generate mask
            attention_mask = tf.cast(
                tf.math.reduce_all(
                    tf.math.logical_not(tf.math.is_nan(queue_tensor)), axis=-1
                ),
                dtype=tf.float32,
            )
            attention_mask = tf.matmul(
                attention_mask[..., tf.newaxis],
                attention_mask[..., tf.newaxis],
                transpose_b=True,
            )
            return queue_tensor[tf.newaxis, ...], attention_mask
        # !!! check overflow
        elif self.count > self.window_size:
            self.count = self.window_size

        return queue_tensor[tf.newaxis, ...], None

    @property
    def is_full(self):
        return self.count == self.window_size

    def clear(self):
        self.count = 0
        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.fill((self.window_size, self.features), np.nan),
        )
```

```python
preprocessing_layer = FIFOLayer(
    window_size = 300,
)

PAMAP2_dataset = tf.data.Dataset.from_tensor_slices((
    np.random.normal(size=(64, 10)),
    np.ones((64,))
))
PAMAP2_dataset = PAMAP2_dataset.map(lambda x, y: (preprocessing_layer(x), y))

for features in PAMAP2_dataset.take(1):
    print(features)
```

**Comment by tilakrayal** [comment]
@markub3327 ,
Looks like code is incomplete. Request you to provide complete code to reproduce the issue in our environment. It helps us in localizing the issue faster.

**Comment by markub3327** [comment]
**Python:** Python 3.9.7
**Clang:** Clang 11.1.0 ] on darwin
**TF Version:** 2.7.0
**Platform:** Apple M1

## Code
```python
import tensorflow as tf
import numpy as np

class FIFOLayer(tf.keras.layers.Layer):
    def __init__(self, window_size, **kwargs):
        super(FIFOLayer, self).__init__(**kwargs)

        self.window_size = window_size
        self.count = 0

    def build(self, input_shape):
        super(FIFOLayer, self).build(input_shape)
        self.features = input_shape[-1]

        self.queue_array = tf.TensorArray(dtype=tf.float32, size=self.window_size)
        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.fill((self.window_size, self.features), np.nan),
        )

    def call(self, inputs, training):
        timesteps = tf.shape(inputs)[0]
        tf.print(timesteps)

        # check if batch_size is more than queue capacity
        #if timesteps > self.window_size:
        #    raise ValueError()

        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.concat(
                [
                    self.queue_array.gather(tf.range(timesteps, self.window_size)),
                    inputs,
                ],
                axis=0,
            ),
        )
        queue_tensor = self.queue_array.stack()
        self.count += timesteps
        # 2. feed-forward
        if self.count < self.window_size:
            # generate mask
            attention_mask = tf.cast(
                tf.math.reduce_all(
                    tf.math.logical_not(tf.math.is_nan(queue_tensor)), axis=-1
                ),
                dtype=tf.float32,
            )
            attention_mask = tf.matmul(
                attention_mask[..., tf.newaxis],
                attention_mask[..., tf.newaxis],
                transpose_b=True,
            )
            return queue_tensor[tf.newaxis, ...], attention_mask
        # !!! check overflow
        elif self.count > self.window_size:
            self.count = self.window_size

        return queue_tensor[tf.newaxis, ...], None

    @property
    def is_full(self):
        return self.count == self.window_size

    def clear(self):
        self.count = 0
        self.queue_array = self.queue_array.scatter(
            tf.range(self.window_size),
            tf.fill((self.window_size, self.features), np.nan),
        )

preprocessing_layer = FIFOLayer(
    window_size = 300,
)

dataset = tf.data.Dataset.from_tensor_slices((
    np.random.normal(size=(64, 10)),
    np.ones((64,))
))
dataset = dataset.map(lambda x, y: (preprocessing_layer(x), y))

for features in dataset.take(1):
    print(features)
```

## Result

> main* $ python3 x.py                                                                                                          [12:03:44]
> /Users/martin/miniforge3/lib/python3.9/site-packages/jax/_src/lib/__init__.py:32: UserWarning: JAX on Mac ARM machines is experimental and minimally tested. Please see https://github.com/google/jax/issues/5501 in the event of problems.
>   warnings.warn("JAX on Mac ARM machines is experimental and minimally tested. "
> Metal device set to: Apple M1
> 
> systemMemory: 16.00 GB
> maxCacheSize: 5.33 GB
> 
> Traceback (most recent call last):
>   File "/Users/martin/Documents/Projects/HAR-Transformer/x.py", line 81, in <module>
>     dataset = dataset.map(lambda x, y: (preprocessing_layer(x), y))
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2004, in map
>     return MapDataset(self, map_func, preserve_cardinality=True, name=name)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 5455, in __init__
>     self._map_func = StructuredFunctionWrapper(
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4533, in __init__
>     self._function = fn_factory()
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3244, in get_concrete_function
>     graph_function = self._get_concrete_function_garbage_collected(
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3210, in _get_concrete_function_garbage_collected
>     graph_function, _ = self._maybe_define_function(args, kwargs)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3557, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3392, in _create_graph_function
>     func_graph_module.func_graph_from_py_func(
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1143, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4510, in wrapped_fn
>     ret = wrapper_helper(*args)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4440, in wrapper_helper
>     ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
>   File "/Users/martin/miniforge3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 699, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:
> 
>     File "/Users/martin/Documents/Projects/HAR-Transformer/x.py", line 81, in None  *
>         lambda x, y: (preprocessing_layer(x), y)
>     File "/Users/martin/miniforge3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
>         raise e.with_traceback(filtered_tb) from None
> 
>     OperatorNotAllowedInGraphError: Exception encountered when calling layer "fifo_layer" (type FIFOLayer).
>     
>     in user code:
>     
>         File "/Users/martin/Documents/Projects/HAR-Transformer/x.py", line 29, in call  *
>             self.queue_array = self.queue_array.scatter(
>     
>         OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
>     
>     
>     Call arguments received:
>       • inputs=tf.Tensor(shape=(10,), dtype=float32)
>       • training=None

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3fde4ef8a063b8ce7749fa193d1ddb6c/54336.ipynb).

**Comment by gowthamkpr** [comment]
@markub3327 Please take a solution provided [here](https://stackoverflow.com/questions/71074606/tf-tensorarray-as-a-fifo). Please note that using tf.TensorArray as FIFO is very slow. Thanks!

**Comment by markub3327** [comment]
@gowthamkpr 

Thanks a lot for your time.
