### ISSUE TITLE
Inference overhead when resizing input image

### ISSUE THREAD

**Issue by BernardoGO** [tensorflow/tensorflow#54335]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): PIP Binary
- TensorFlow version (use command below): 2.6
- Python version: 3.7

**Describe the current behavior**
Inference time increases by a lot when changing input image resolution in a dynamic tensor shape model. 
This only happens if the input shape changes, consecutive runs for different images performs well as long as the input size is the same. Once it changes, even for lower resolutions (1024x768 -> 512x512), the inference time increases for the first inference and then goes back to normal for the next ones.

**Comment by mohantym** [comment]
Hi @BernardoGO ! Have you checked the performance in Python 3.7 /3.8 ? Please provide a simple stand alone code to reproduce the issue. Thanks!

**Comment by BernardoGO** [comment]
Hello @mohantym

Sorry, I mistyped python version. It's version 3.7.
As for the code, I've been trying Style Transfer from with provided weights: https://github.com/cryu854/FastStyle

The issue only happens at inference time

**Comment by mohantym** [comment]
Ok @BernardoGO ! Could you please provide exact code with  inference time code snippet?
