### ISSUE TITLE
ValueError: No gradients provided for any variable:

### ISSUE THREAD

**Issue by arjun-majumdar** [tensorflow/tensorflow#54341]
I am using TensorFlow 2.6.0 and Python 3.9. I am attempting to implement a Variational Autoencoder toy example using MNIST dataset with Convolutional Neural Network as encoder and decoder. You can refer to the complete Jupyter notebook [here](https://github.com/arjun-majumdar/Autoencoders_Experiments/blob/master/Testing-VAE_TF2.ipynb).

For some reason, on using GradientTape for training - in this case, computing the gradients with respect to the trainable parameters of the defined model, it keeps giving **ValueError: No gradients provided for any variable:** error message.

The exact lines of code are:

```
with tf.GradientTape() as tape:
    total_loss = compute_total_loss(
        data = X, reconstruction = X_recon,
        mu = mu, log_var = log_var,
        alpha = 1
    )
    
grads = tape.gradient(total_loss, model.trainable_weights)

type(grads), len(grads)
# (list, 16)


# No gradients are computed!
for x in grads:
    print(x)
'''
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
'''


optimizer.apply_gradients(zip(grads, model.trainable_weights))
"""
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_232/111942921.py in <module>
----> 1 optimizer.apply_gradients(zip(grads, model.trainable_weights))

~\anaconda3\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py in apply_gradients(self, grads_and_vars, name, experimental_aggregate_gradients)
    639       RuntimeError: If called in a cross-replica context.
    640     """
--> 641     grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    642     var_list = [v for (_, v) in grads_and_vars]
    643 

~\anaconda3\envs\tf-cpu\lib\site-packages\tensorflow\python\keras\optimizer_v2\utils.py in filter_empty_gradients(grads_and_vars)
     73 
     74   if not filtered:
---> 75     raise ValueError("No gradients provided for any variable: %s." %
     76                      ([v.name for _, v in grads_and_vars],))
     77   if vars_with_empty_grads:

ValueError: No gradients provided for any variable: ['vae_1/encoder_4/conv2d_8/kernel:0', 'vae_1/encoder_4/conv2d_8/bias:0', 'vae_1/encoder_4/conv2d_9/kernel:0', 'vae_1/encoder_4/conv2d_9/bias:0', 'vae_1/decoder_3/dense_9/kernel:0', 'vae_1/decoder_3/dense_9/bias:0', 'vae_1/decoder_3/conv2d_transpose_9/kernel:0', 'vae_1/decoder_3/conv2d_transpose_9/bias:0', 'vae_1/decoder_3/conv2d_transpose_10/kernel:0', 'vae_1/decoder_3/conv2d_transpose_10/bias:0', 'vae_1/decoder_3/conv2d_transpose_11/kernel:0', 'vae_1/decoder_3/conv2d_transpose_11/bias:0', 'vae_1/dense_10/kernel:0', 'vae_1/dense_10/bias:0', 'vae_1/dense_11/kernel:0', 'vae_1/dense_11/bias:0'].
"""

```

Is this a bug? Is it the case that tf.GradientTape() API is somehow not computing the gradients?

**Comment by mohantym** [comment]
Hi @arjun-majumdar ! I was facing some issues to run the complete code. This error generally occurs normally when loss function is not differentiable. Can you change the compute_total_loss like below and let us know? Thanks!
```
def compute_total_loss(data, reconstruction, mu, log_var, alpha = 1):
    recon_loss = compute_reconstruction_loss(data = data, reconstruction = reconstruction)
    kl_loss = compute_kl_divergence_loss(mu = mu, log_var = log_var)
    
    total_loss = (recon_loss * alpha) + kl_loss
    loss = total_loss**2
    return loss
```

**Comment by arjun-majumdar** [comment]
Hey @mohantym I am attaching the Jupyter notebook which I ran on Google Colab to help you troubleshoot it better.

I changed the loss function as suggested-

```
def compute_total_loss(data, reconstruction, mu, log_var, alpha = 1):
    recon_loss = compute_reconstruction_loss(data = data, reconstruction = reconstruction)
    kl_loss = compute_kl_divergence_loss(mu = mu, log_var = log_var)
    
    total_loss = (recon_loss * alpha) + kl_loss
    loss = total_loss**2
    
    # return total_loss
    return loss


# Make forward propagation using defined VAE model-
X_recon, mu, log_var = model(X)

X_recon.shape, X.shape
# (TensorShape([4, 28, 28, 1]), (4, 28, 28, 1))

mu.shape, log_var.shape
# (TensorShape([4, 3]), TensorShape([4, 3]))

with tf.GradientTape() as tape:
    loss = compute_total_loss(
    data = X, reconstruction = X_recon,
    mu = mu, log_var = log_var,
    alpha = 1
)

grads = tape.gradient(loss, model.trainable_weights)

type(grads), len(grads)
# (list, 20)

# But, this still raises the error as before-
optimizer.apply_gradients(zip(grads, model.trainable_weights))
```


> ValueError                                Traceback (most recent call last)
> 
> [<ipython-input-39-455ef87a6a2b>](https://localhost:8080/#) in <module>()
> ----> 1 optimizer.apply_gradients(zip(grads, model.trainable_weights))
> 
> 1 frames
> 
> [/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/utils.py](https://localhost:8080/#) in filter_empty_gradients(grads_and_vars)
>      71   if not filtered:
>      72     variable = ([v.name for _, v in grads_and_vars],)
> ---> 73     raise ValueError(f"No gradients provided for any variable: {variable}. "
>      74                      f"Provided `grads_and_vars` is {grads_and_vars}.")
>      75   if vars_with_empty_grads:
> 
> ValueError: No gradients provided for any variable: (['vae/encoder/conv2d/kernel:0', 'vae/encoder/conv2d/bias:0', 'vae/encoder/conv2d_1/kernel:0', 'vae/encoder/conv2d_1/bias:0', 'vae/encoder/dense/kernel:0', 'vae/encoder/dense/bias:0', 'vae/decoder/dense_1/kernel:0', 'vae/decoder/dense_1/bias:0', 'vae/decoder/dense_2/kernel:0', 'vae/decoder/dense_2/bias:0', 'vae/decoder/conv2d_transpose/kernel:0', 'vae/decoder/conv2d_transpose/bias:0', 'vae/decoder/conv2d_transpose_1/kernel:0', 'vae/decoder/conv2d_transpose_1/bias:0', 'vae/decoder/conv2d_transpose_2/kernel:0', 'vae/decoder/conv2d_transpose_2/bias:0', 'vae/dense_3/kernel:0', 'vae/dense_3/bias:0', 'vae/dense_4/kernel:0', 'vae/dense_4/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'vae/encoder/conv2d/kernel:0' shape=(3, 3, 1, 32)

**Comment by mohantym** [comment]
Hi @arjun-majumdar !  Could you please post this in[ Keras](https://github.com/keras-team/keras/issues) repo? Thanks!

**Comment by arjun-majumdar** [comment]
Solved issue

**Comment by worthy7** [comment]
@arjun-majumdar Tell us how
