### ISSUE TITLE
TFTRT and Ragged operations

### ISSUE THREAD

**Issue by rpytel1** [tensorflow/tensorflow#54348]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18 (using docker image from nvidia: [nvcr.io/nvidia/tensorflow:21.12-tf2-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow)
- TensorFlow installed from (source or binary): 2.6.2, but the problem persists on older versions too (all versions in 2021). Newer versions are not yet stable for tensorrt. 
- TensorFlow version (use command below): via docker image. 
- Python version: Python 3.8.10
- CUDA/cuDNN version: CUDA 11.5.0
- GPU model and memory: Tesla T4 16 GB, but also on GTX 1080 TI. 

**Describe the current behaviour**
When trying to optimize the model with ragged operations via TFTRT, optimization fails with a following error:
```
2022-02-09 14:56:57.575556: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at segment_reduction_ops_impl.h:422 : Invalid argument: data.shape = [48,256] does not start with segment_ids.shape = [168]
Traceback (most recent call last):
  File "optimize.py", line 41, in <module>
    converter.build(input_fn=my_input_fn)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1320, in build
    self._converted_func(*map(ops.convert_to_tensor, first_input))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1707, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/wrap_function.py", line 246, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1725, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1774, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  data.shape = [48,256] does not start with segment_ids.shape = [168]
	 [[node StatefulPartitionedCall/ragged_net/lambda/RaggedReduceMax/RaggedReduce_1/RaggedReduce_1/UnsortedSegmentMax (defined at optimize.py:25) ]] [Op:__inference_pruned_2056]
```
 After some investigation, I have found out that the problem is happening in ``row_splits_to_segment_ids``, invoked within RaggedReduceMax( actually under the hood it is invoked in ``_ragged_segment_aggregate()``,  invoked by ``ragged_reduce_aggregate`` which is invoked by ``reduce_max`` in ``tensorflow.python.ops.ragged.ragged_math_ops``). The problem is with correctly calculating ``row_lenghts`` which in most cases are done correctly (while training and first sweeps of optimization, but in the second part it produces wrong results). The current version is: 
```python
    row_lengths = splits[1:] - splits[:-1]
```
The proposed version is:
```python
    s = splits[::-1][1:][::-1]
    row_lengths = splits[1:] - s
```
Which essentially does the very same thing, but at least it does not result in the presented crash. On the other hand, it produces a soft crash (non-breaking one but indicating that no significant optimization was run):
```
2022-01-25 13:24:56.322210: E tensorflow/compiler/tf2tensorrt/utils/trt_logger.cc:40] DefaultLogger 3: [executionContext.cpp::enqueueInternal::328] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::enqueueInternal::328, condition: bindings[x] != nullptr
```

**Describe the expected behaviour**
I would like to get a model which is TFTRT optimized with smaller ``min_segment_size``.  My current workaround is to use a larger value for the parameter ``min_segment_size`` but this gives me a suboptimal solution in terms of performance.
  
**Standalone code to reproduce the issue and logs**
Gist with required code and logs: [https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24). 
Explanation of how to use gist:
- to train a model **without custom changes** in ``row_splits_to_segment_ids()``: use [train_round1.py](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24#file-train_round1-py)
- to train a model **with custom changes** in ``row_splits_to_segment_ids()``: use [train_round2.py](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24#file-train_round2-py)
- to optimize a trained model: use [optimize.py](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24#file-optimize-py)
- my logs for optimizing model trained with no custom changes: [log_after_optimize_for_round_1.txt](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24#file-log_after_optimize_for_round_1-txt)
- my logs for optimizing model trained with custom changes: [log_after_optmize_for_round_2.txt](https://gist.github.com/rpytel1/6f6d57f68a5e3d69922cd1ec43eb6a24#file-log_after_optmize_for_round_2-txt)

Due to a nightmare with configuring TensorRT in Google Colab, I provide only gists.

**Comment by tilakrayal** [comment]
@chunduriv ,
I have tried in colab with TF version 2.7 and nightly version and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/522ec71abfb70331e9d30d48887bd5b1/untitled221.ipynb). Thanks!

**Comment by rpytel1** [comment]
> @chunduriv , I have tried in colab with TF version 2.7 and nightly version and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/522ec71abfb70331e9d30d48887bd5b1/untitled221.ipynb). Thanks!

@tilakrayal this is due to the fact that ``tf-2.7`` and Colab is are not compiled with Cudnn (CUDA). For TFTRT you need CUDA. If. you want to check if the problem is solved in TF2.7 I would recommend using [docker image from Nvidia](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow/tags) with tag 22.01-tf2-py3. 
But as I said for this you need to check on a real machine, not a Colab.

**Comment by rpytel1** [comment]
Any update on the issue?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
