### ISSUE TITLE
How to select GPU device via NNAPI？

### ISSUE THREAD

**Issue by Hank880223** [tensorflow/tensorflow#54355]
How to choose gpu1 and gpu2 device if using embedded platform and two gpus deployed via tflite's nnapi？
e.g. Dual GPU for embedded platform NXP i.MX8 QuadMax

**Comment by tilakrayal** [comment]
@Hank880223 ,
Can you please take a look at this link [1](https://stackoverflow.com/questions/40069883/how-to-set-specific-gpu-in-tensorflow),  [2](https://www.tensorflow.org/guide/gpu), [3](https://www.tensorflow.org/lite/performance/nnapi) which delivers the required information.It helps.Thanks!
