### ISSUE TITLE
User defined op without input + control dependencies causes op execution error

### ISSUE THREAD

**Issue by skydoorkai** [tensorflow/tensorflow#5435]
1. Define a user-defined op without input, with 1 output:
REGISTER_OP("MyOp")
  .Output("output: T")
  .Attr(.....)

2. in python code:
op1 = my_op(attrs)

with tf.control_dependencies([op1]):
  op2 = otherOp

This runs OK, both op1 and op2 execute once:
sess.run(op2)

This is WRONG:
sess.run([op1, op2])
op1 will execute 2 times.

If adding an input for MyOp, op1 will execute only once as expected for 
 sess.run([op1, op2])

**Comment by girving** [comment]
@skydoorkai Please include complete code.  Your description so far is unlikely to be true, since a single call to run never runs ops multiple times.

**Comment by prb12** [comment]
Closing due to lack of response.
