### ISSUE TITLE
How to know whether TF is using cudnn?

### ISSUE THREAD

**Issue by QuantumLiu** [tensorflow/tensorflow#5436]
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
>>>

**Comment by burness** [comment]
"successfully opened cuda librray libcudnn.so locallly" says that your TF is using cudnn

**Comment by QuantumLiu** [comment]
thank you ！

**Comment by Jowizo** [comment]
When I import tensorflow as tf , it returns nothing! Does this mean it isn't using CuDnn?
