### ISSUE TITLE
convert .meta,and chkpoint to .pb gives error "maximum protobuf size of 2GB"

### ISSUE THREAD

**Issue by prmudgal** [tensorflow/tensorflow#54364]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 1.15
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

I am converting .meta and chkpoint file to protobuf type, but getting error-

Traceback (most recent call last):
  File "converttofrozen.py", line 28, in <module>
    pickle.dump(frozen_graph, frozen_graph_file)
  File "/home/marlin/anaconda/envs/hific-compress1/lib/python3.7/site-packages/google/protobuf/message.py", line 408, in __reduce__
    return type(self), (), self.__getstate__()
  File "/home/marlin/anaconda/envs/hific-compress1/lib/python3.7/site-packages/google/protobuf/message.py", line 393, in __getstate__
    return dict(serialized=self.SerializePartialToString())
ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 2237555411

I followed the suggestion [here ](https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb/45868106#45868106) for conversion.

The chkpt file size is bigger than 2 GB.
![image](https://user-images.githubusercontent.com/20053548/153773801-826d6bd9-d0d5-48ed-906d-829e2e5d013f.png)

Is there a way to get rid of the hard limit of 2GB in conversion?

**Comment by tilakrayal** [comment]
@prmudgal ,
Can you please take a look at this link [1](https://github.com/tensorflow/tensorflow/issues/47326) and [2](https://github.com/tensorflow/tensorflow/issues/45041) with the similar error.It helps.Thanks!
