### ISSUE TITLE
graph - AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Nagakiran1** [tensorflow/tensorflow#54363]
OS: windows
tenosrflow  '2.8.0' (usingas  import tensorflow._api.v2.compat.v1 as tf)

Hi 
I am not able to do update operations for tensorflow graph nodes (graph -> node -> node.node_def) [https://github.com/davidsandberg/facenet/issues/161](https://github.com/davidsandberg/facenet/issues/161) I have explored few repos, none of them seems to be working.

code 

```
model_path = '../deepmind-research/meshgraphnets/chk/flag_simple/chk/model.ckpt-29872'
sess = tf.Session()

saver = tf.train.import_meta_graph(model_path + ".meta")
saver.restore(sess, model_path)


init_op =  tf.global_variables_initializer()    
with tf.Session() as session:
    session.run(init_op)
    gd = sess.graph.as_graph_def()
    output_graph_def = graph_util.convert_variables_to_constants(sess, gd, output)
    graph_io.write_graph(graphdef_frozen, save_pb_dir, 'frozen_model1.pb', as_text=save_pb_as_text)
        


node = graph.get_operations()
print(node.node_def)
```
name: "Model/output_normalizer/Variable/Assign"
op: "AssignVariableOp"
input: "Model/output_normalizer/Variable"
input: "Model/output_normalizer/Variable/Initializer/initial_value"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "validate_shape"
  value {
    b: false
  }
}

```
node.node_def.op = 'VariableOp'
(runs without error but, not reflecting in node_def)
print(node.node_def)
```
name: "Model/output_normalizer/Variable/Assign"
op: "AssignVariableOp"
input: "Model/output_normalizer/Variable"
input: "Model/output_normalizer/Variable/Initializer/initial_value"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "validate_shape"
  value {
    b: false
  }
}
```
a = node.node_def
a.op = node.node_def.op[6:]
node.node_def = a

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [111], in <module>
      1 a = node.node_def
      2 a.op = node.node_def.op[6:]
----> 3 node.node_def = a

AttributeError: can't set attribute

```

Would you please show me some relevant resources to explore in this problem, I am exhausted from searching :-| 

Here I added link to frozen inference graph [https://github.com/Nagakiran1/data/blob/main/frozen_model.pb](url)

**Comment by mohantym** [comment]
Hi @Nagakiran1 ! Could you please share same  stand alone code as a colab gist with reference to below code snippet? 

```
a = node.node_def
a.op = node.node_def.op[6:]
node.node_def = a

```
