### ISSUE TITLE
Cannot install tensorflow_text in virtual environment of python 3.8 mac m1

### ISSUE THREAD

**Issue by sijia-w** [tensorflow/tensorflow#54369]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac M1
- TensorFlow version: 2.7.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv (see https://developer.apple.com/metal/tensorflow-plugin/)

**Describe the problem**
To use the [`xx_use_md` model](https://pypi.org/project/spacy-universal-sentence-encoder/0.2.1/), I started a virtualenv. 

I tried to load the model by 

```
import spacy_universal_sentence_encoder
nlp = spacy_universal_sentence_encoder.load_model('xx_use_md')
```

Then, I encountered the error:

```
FileNotFoundError: Op type not registered 'SentencepieceOp' in binary running on MacBook-Air. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.
```

Guided by the discussion here: https://github.com/tensorflow/tensorflow/issues/38597, I tried to install `tensorflow_text` in the virtualenv via pip3, but this raised another error:

```
ERROR: Could not find a version that satisfies the requirement tensorflow_text (from versions: none)
ERROR: No matching distribution found for tensorflow_text
```

Additionally, I tried to load the model by

```
import spacy
nlp = spacy.load('xx_use_md')
```

which raised the error

```
OSError: [E050] Can't find model 'xx_use_md'. It doesn't seem to be a Python package or a valid path to a data directory.
```

Then, I used the command `pip3 install https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/releases/download/xx_use_md-0.2.1/xx_use_md-0.2.1.tar.gz#xx_use_md-0.2.1` on https://pypi.org/project/spacy-universal-sentence-encoder/0.2.1/ . Another error happened:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.1.0 (from spacy-universal-sentence-encoder) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.1.0
```

It is impossible to use the 'xx_use_md' model by `import spacy` or `import spacy_universal_sentence_encoder` in the virtualenv. However, when I tried with the same code on Colab, similar errors occurred and were resolved by installing and importing `tensowflow_text`.

**Comment by mohantym** [comment]
Hi @sijia-w ! Please change your command  "pip install tensorflow_text"  to "pip install tensorflow-text" . You can import tensorflow -text with this command "import tensorflow_text as [tf_text](https://www.tensorflow.org/text)" after that. Thanks!

**Comment by sijia-w** [comment]
Hi @mohantym  Thanks a lot for your quick response! Unfortunately, still the same error.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/53718687/153870129-3489eb2e-26c4-4145-9291-3273db2b80f2.png">

**Comment by mohantym** [comment]
Hi @sijia-w ! Could you please post on [Tensorflow-text ](https://github.com/tensorflow/text/issues)repo ?Attaching relevant [thread ](https://github.com/tensorflow/text/issues/89#issuecomment-1015848485)for reference. Thanks!

**Comment by sijia-w** [comment]
Hi @mohantym, Sure! See https://github.com/tensorflow/text/issues/837.  Shall I close this issue?

**Comment by mohantym** [comment]
Ok @sijia-w ! Closing this issue here as it will be tracked in Tensorflow-text repo. Thanks!

**Comment by mohantym** [comment]
Hi @sijia-w !
Re-opening as requested.
Thank you!

**Comment by tilakrayal** [comment]
@sijia-w,
Have you got the chance to have a look at this PR https://github.com/tensorflow/text/pull/756 for the similar feature for Apple Silicon support. By installing tensorflow-macos 2.6.0 and tensorflow-metal 0.2.0, TF.Text can be compiled from source code(Currently Apple does not provide a preview version of tensorflow-macos and tf-nightly, so TF.Text can only build a stable version.). The PR was also merged.

Also the similar issue was already being tracked in the **tensorflow-text** repo for the same. https://github.com/tensorflow/text/issues/823. Thank you!

**Comment by luis-arellano** [comment]
I'm running into the same issue. I have a mac with M1.  
ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text
