### ISSUE TITLE
Document for tensorflow>=2.8 in wsl2 ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#54360]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/releases

### Clear description
Is there any document for ```get start in wsl2``` since I notice the section
```TensorFlow has been validated on Windows Subsystem for Linux 2 (aka WSL 2) for both GPUs and CPUs.``` ?

**Comment by mohantym** [comment]
Hi @DachuanZhao ! Can you check the build from source documentation for Linux for this issue?

**Comment by chunduriv** [comment]
@DachuanZhao,

Can you please check [this](https://github.com/tensorflow/build/tree/master/wsl2_gpu_guide) guide and let us know if it helps? Thanks!

**Comment by mihaimaruseac** [comment]
The WSL2 usage should be handled by Microsoft or other documentation. There is nothing special about TF for this.
