### ISSUE TITLE
tflite with CoreML delegate errors with mediapipe models

### ISSUE THREAD

**Issue by korkland** [tensorflow/tensorflow#54375]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: IPAD pro M1
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.8.0 C api
- Python version: 3.9
- Bazel version (if compiling from source): 4.1
- GCC/Compiler version (if compiling from source): apple clang
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the current behavior**
I've built a tflite 2.8.0 with coreML delegate to run mediapipe models on ipad M1,
for the build i edit the BUILD.apple according to one of the issues here, changing the coreml dependencies to the c api build:

`# bazel build -c opt --config=ios_fat //tensorflow/lite/ios:TensorFlowLiteC_framework

tflite_ios_framework(
    name = "TensorFlowLiteC_framework",
    hdrs = [
        ":builtin_ops.h",
        ":c_api.h",
        ":c_api_experimental.h",
        ":common.h",
        ":coreml_delegate.h",
        ":xnnpack_delegate.h",
        "//tensorflow/lite/c:c_api_types.h",
    ],
    allowlist_symbols_file = ":allowlist_TensorFlowLiteC.txt",
    bundle_name = "TensorFlowLiteC",
    minimum_os_version = TFL_MINIMUM_OS_VERSION,
    deps = [
        ":tensorflow_lite_c",
        "//tensorflow/lite/delegates/coreml:coreml_delegate",
    ],
)`

it faster than the XNNPACK delegate but i get the following errors:

`2022-02-14 18:13:53.989664+0200 Blackbox[17707:4340397] [espresso] [Espresso::ANERuntimeEngine::__forward_segment 0] evaluate[RealTime]WithModel returned 0; code=5 err=Error Domain=com.apple.appleneuralengine Code=5 "processRequest:model:qos:qIndex:modelStringID:options:error:: 0x2: Program Inference overflow" UserInfo={NSLocalizedDescription=processRequest:model:qos:qIndex:modelStringID:options:error:: 0x2: Program Inference overflow}

2022-02-14 18:13:53.989716+0200 Blackbox[17707:4340397] [espresso] [Espresso::overflow_error] /private/var/mobile/Containers/Data/Application/D959913C-E34A-44C9-8706-3FD4944AF1ED/tmp/B14B4C52-2C7C-4C96-A4CC-DECBF54971E5-17707-0000111529177368.mlmodelc/model.espresso.net:0`

Im using Xcode 13.1 
with XNNPACK everything is working perfect

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

tflite code:
`TfLiteModel* m_model{ nullptr };
TfLiteInterpreter* m_interpreter{ nullptr };
TfLiteDelegate* m_delegateXNNPACK{ nullptr };
TfLiteDelegate* m_delegateCoreML{ nullptr };

m_model = TfLiteModelCreateFromFile(modelFile.c_str());
if (m_model == nullptr)
	return false;

TfLiteInterpreterOptions* options = TfLiteInterpreterOptionsCreate();
TfLiteCoreMlDelegateOptions optionsCoreML;
optionsCoreML.enabled_devices = TfLiteCoreMlDelegateAllDevices;
m_delegateCoreML = TfLiteCoreMlDelegateCreate(&optionsCoreML);
TfLiteInterpreterOptionsAddDelegate(options, m_delegateCoreML);

if(!m_delegateCoreML)
{
	TfLiteXNNPackDelegateOptions optionsXNNPACK = TfLiteXNNPackDelegateOptionsDefault();
	m_delegateXNNPACK = TfLiteXNNPackDelegateCreate(&optionsXNNPACK);
	TfLiteInterpreterOptionsAddDelegate(options, m_delegateXNNPACK);
}

m_interpreter = (TfLiteInterpreter*)TfLiteInterpreterCreate(m_model, options);
if (m_interpreter == nullptr)
	return false;

// Allocate tensor buffers
if (TfLiteInterpreterAllocateTensors(m_interpreter) != kTfLiteOk)
	return false;

if (TfLiteInterpreterInvoke(m_interpreter) != kTfLiteOk)
	return false;	`

models:
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite
https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_landmark/pose_landmark_lite.tflite

init the model and interpreter yeilds:
`2022-02-14 19:51:21.711179+0200 Blackbox[17727:4362469] coreml_version must be 2 or 3. Setting to 3.
2022-02-14 19:51:21.722082+0200 Blackbox[17727:4362469] Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
2022-02-14 19:51:21.727229+0200 Blackbox[17727:4362469] CoreML delegate: 37 nodes delegated out of 291 nodes, with 33 partitions.
INFO: CoreML delegate: 37 nodes delegated out of 291 nodes, with 33 partitions.
2022-02-14 19:52:12.292307+0200 Blackbox[17727:4362469] coreml_version must be 2 or 3. Setting to 3.
2022-02-14 19:52:12.293704+0200 Blackbox[17727:4362469] CoreML delegate: 112 nodes delegated out of 283 nodes, with 6 partitions.
INFO: CoreML delegate: 112 nodes delegated out of 283 nodes, with 6 partitions.`

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by colinrgodsey** [comment]
any updates on this?

**Comment by yishuangP** [comment]
The error is from Espresso::ANERuntimeEngine and is happening at coreml level. Can you ask on https://developer.apple.com/forums/? Also Can you try a newer tflite version (2.11.0 for example)?

`2022-02-14 18:13:53.989664+0200 Blackbox[17707:4340397] [espresso] [Espresso::ANERuntimeEngine::__forward_segment 0] evaluate[RealTime]WithModel returned 0; code=5 err=Error Domain=com.apple.appleneuralengine Code=5 "processRequest:model:qos:qIndex:modelStringID:options:error:: 0x2: Program Inference overflow" UserInfo={NSLocalizedDescription=processRequest:model:qos:qIndex:modelStringID:options:error:: 0x2: Program Inference overflow}

2022-02-14 18:13:53.989716+0200 Blackbox[17707:4340397] [espresso] [Espresso::overflow_error] /private/var/mobile/Containers/Data/Application/D959913C-E34A-44C9-8706-3FD4944AF1ED/tmp/B14B4C52-2C7C-4C96-A4CC-DECBF54971E5-17707-0000111529177368.mlmodelc/model.espresso.net:0`
