### ISSUE TITLE
does tensorflow support cuda 11.3?

### ISSUE THREAD

**Issue by MinWang1997** [tensorflow/tensorflow#54384]
Hi,

I noticed that tensorflow support cuda 11.2 but you do not mention if tensorflow supports cuda 11.3.

When I use cuda 11.3 with tensorflow 2.4, it shows that 
`failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
`

For the details, please refer to[ this issue ](https://github.com/open-mmlab/mmdetection3d/issues/1233#issue-1133840656)

**Comment by sushreebarsa** [comment]
@MinWang1997 Could you please have a look at the [link](https://github.com/tensorflow/docs/blob/master/site/en/install/source.md#gpu) and try with the latest TF version with compatible configurations ?Please let us know if it helps?Thanks!

**Comment by MinWang1997** [comment]
Hi @sushreebarsa according the compatibility table, all the tensorflow doesnot support cuda11.3 since the latest supported version is cuda 11.2.

**Comment by ngam** [comment]
@MinWang1997 anything compiled with cuda=11.2 should work with anything cuda>=11.2, see more here : https://docs.nvidia.com/deploy/cuda-compatibility/#default-to-minor-version. I have recently used tensorflow 2.7 and tensorflow 2.8 with cudatoolkit 11.5 and 11.6 with no problems. Are you seeing any problems?

**Comment by dfrabu** [comment]
# Setup for Windows 10 (if you are hating anaconda and miniconda) 
# Avoid to buy GPU NVIDIA with CUDA < 5.0 ... GTX 9xx or higher.
# Install python.org version 3.10.5 (current data is now: 18/06/2022)
# GPU NVIDIA (Install CUDA-Toolkit 11.3)
# https://developer.nvidia.com/cuda-11-3-1-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_network
#
# PACOTES NECESSÁRIOS PRA IA (comandos de instalação)
#
#

python -m pip install --upgrade pip
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
pip install tensorflow-gpu
pip install pandas numpy numba sklearn
pip install pyqt6 pyqt5  # para criar interfaces gráficas instale o qt-designer

# create a script called check.py (It is the source code):

import sys
import pandas as pd
import sklearn as sk
import tensorflow as tf
import torch

print(f"Torch Version: {torch.__version__}")
print(f"Torch GPU: {torch.cuda.is_available()}")
print(f"Torch GPU Name: {torch.cuda.get_device_name()}")
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tf.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

# running python check.py you should receive a output like that:

Torch Version: 1.11.0+cu113
Torch GPU: True
Torch GPU Name: NVIDIA GeForce RTX 3060
Tensor Flow Version: 2.9.1
Keras Version: 2.9.0

Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Pandas 1.4.2
Scikit-Learn 1.1.1
GPU is available

# Even with old GPUs it should works:

Torch Version: 1.11.0+cu113
Torch GPU: True
Torch GPU Name: NVIDIA GeForce GTX 960
Tensor Flow Version: 2.9.1
Keras Version: 2.9.0

Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Pandas 1.4.2
Scikit-Learn 1.1.1
GPU is available


# If you gonna work with yoloV5 ... 
# please comment the following requirements.txt lines using # like that:
# torch>=1.7.0 e 
# torchvision>=0.8.1

# now run the default install to yolo:
pip install -r requirements.txt

**Comment by qhaas** [comment]
CUDA 11.8 is out and its mid October 2022, docs still show the latest supported cuda version is 11.2.
