### ISSUE TITLE
Building unit tests on non-GPU build is broken

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#54388]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.8.10
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Build errors out with

`ERROR: /home/builder/1/tensorflow_build/tensorflow-git/tensorflow/compiler/xla/service/gpu/BUILD:653:11: Compiling tensorflow/compiler/xla/service/gpu/triangular_solve_thunk.cc failed: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/service/gpu:gpu_executable':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/service/gpu/triangular_solve_thunk.cc':
  'tensorflow/compiler/xla/service/gpu/precompiled_kernels.h'
INFO: Elapsed time: 4632.439s, Critical Path: 957.38s
INFO: 40192 processes: 12988 internal, 27204 local.
FAILED: Build did NOT complete successfully
`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --remote_http_cache=""  --remote_cache_proxy="" --noremote_accept_cached --config=nonccl --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --verbose_failures -- //tensorflow/... -//tensorflow/python/integration_testing/... -//tensorflow/compiler/tf2tensorrt/... -//tensorflow/compiler/xrt/... -//tensorflow/core/tpu/... -//tensorflow/java/... -//tensorflow/go/... -//tensorflow/lite/... -//tensorflow/python/tools/... -//tensorflow/compiler/mlir/lite/tests:const-fold.mlir.test -//tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test -//tensorflow/python/eager:function_test -//tensorflow/python/kernel_tests/linalg:linear_operator_circulant_test -//tensorflow/python/kernel_tests/linalg:self_adjoint_eig_op_test

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The commit https://github.com/tensorflow/tensorflow/commit/3e3d3cb87d1f747928d26d832e9bbc231b201c43 is involved but that seems to have been partially addressing another problem, so not sure where the root cause is.

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by gadagashwini** [comment]
@elfringham 
Can you clear the cache before running Bazel build command

Try to wipe out bazel cache using
`rm -rf ~/.cache/bazel  `
Or
`bazel clean --expunge`.

Please let us know if that helps!

**Comment by elfringham** [comment]
No, that does not help at all.

**Comment by gadagashwini** [comment]
@elfringham,
Looks like its more of Bazel issue. Please check similar issue [#13135](https://github.com/bazelbuild/bazel/issues/13135)

**Comment by elfringham** [comment]
@gadagashwini I disagree. Cleaning the cache is no help. That issue does not seem to relate in any way.

**Comment by elfringham** [comment]
It looks like this was resolved by https://github.com/tensorflow/tensorflow/commit/31acf21fda3d6a443afd58c594ec6b9ba09cf23f
