### ISSUE TITLE
BlazePose model support in iOS sample

### ISSUE THREAD

**Issue by pratimash** [tensorflow/tensorflow#54389]
Hi Team, I was checking https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/ios example it supports
Posenet, Movenet Lightning, Movenet Thunder models. I just wanted to know, Is it possible to add googles BlazePose model  support ? If yes how can I do that ?

Thank you

**Comment by tilakrayal** [comment]
@pratimash ,
Please take a look at this link [1](https://ai.googleblog.com/2020/08/on-device-real-time-body-pose-tracking.html) [2](https://google.github.io/mediapipe/solutions/pose#personpose-detection-model-blazepose-detector) and [3](https://blog.tensorflow.org/2021/05/high-fidelity-pose-tracking-with-mediapipe-blazepose-and-tfjs.html) which delivers the approach towards BlazePose.It helps.Thanks!
