### ISSUE TITLE
README.md useless

### ISSUE THREAD

**Issue by zmajew** [tensorflow/tensorflow#54383]
This is the most time and nerve-consuming library in the whole dev eco!!! To install it you have to spend hours and hours, just because you assume that all of us have prior knowledge that you have.

**Comment by tilakrayal** [comment]
@zmajew ,
TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.Can you please try to follow and install from this [link](https://www.tensorflow.org/install).Thanks!

**Comment by mihaimaruseac** [comment]
No template filled. Rant issues are not productive, they just waste the time of everyone.
