### ISSUE TITLE
tf.function with jit_compile runs on CPU when there is GPU

### ISSUE THREAD

**Issue by charlielam0615** [tensorflow/tensorflow#54386]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
pip install
- TensorFlow version (use command below):
v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: Python 3.9.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 (ptxas cherrypicked from CUDA 11.3)
- GPU model and memory: RTX A6000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`@tf.function(jit_compile=True)` runs on both CPU and GPU, and mostly CPU
**Describe the expected behavior**
Should mainly use GPU

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

@tf.function(jit_compile=True)
def func(a, b):
    for i in tf.range(100):
        c = a + b
        a = b
        b = c 
    return c
concrete_fn = func.get_concrete_function(
    tf.TensorSpec(shape=[3], dtype=tf.float32, name='a'),
    tf.TensorSpec(shape=[3], dtype=tf.float32, name='b')
    )
a = tf.random.normal([3])
b = tf.random.normal([3])
tf.profiler.experimental.start('profile_results_simple')
for step in range(300):
    with tf.profiler.experimental.Trace("Train", step_num=step, _r=1):
        concrete_fn(a, b)
tf.profiler.experimental.stop()
```

![Screen Shot 2022-02-15 at 5 30 14 PM](https://user-images.githubusercontent.com/20623744/154033461-2cb94471-666d-4fba-87f0-aac898e2d08e.png)

The full tensorboard file can be downloaded from [here](https://drive.google.com/file/d/1IYNdjCkko4u2ktaxRe1vdjbqCMjrkgtg/view?usp=sharing).

Above is a short code snippt to reproduce the problem. In my actual project, this problem is more severe. I can see the GPU usage drops to 0% and stays there for a few seconds before rise to ~70% again and this pattern repeats for every step. This GPU drop cannot be explained by disk IO because I am working on a toy example and input is some randomly generated tensors.

Moreover, adding `with tf.device('/gpu:0'):` doesn't solve this issue.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@charlielam0615 ,
While executing the provided code i haven't found any issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/e35a9f5983135d4cbb7ba29525bb6fc1/untitled228.ipynb) and provide complete code to debug.Thanks!

**Comment by charlielam0615** [comment]
> @charlielam0615 ,
> While executing the provided code i haven't found any issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/e35a9f5983135d4cbb7ba29525bb6fc1/untitled228.ipynb) and provide complete code to debug.Thanks!

Running this gist will create profile files inside the `profile_results_simple` folder. Visualizing this profile using tensorboard shows exactly the same issue. Below is the screenshot where you can see lots of ops happened in CPU instead of GPU.

![Screen Shot 2022-02-16 at 4 53 10 PM](https://user-images.githubusercontent.com/20623744/154229250-11ee340e-f3a8-45e5-9602-4ffabd070d8d.png)

I further tested this code with 
CUDA 11.2, RTX A6000, TF 2.7.0
CUDA 11.2, RTX A6000, TF 2.6.0
CUDA 11.2, Tesla V100, TF 2.6.0

This problem persists.

Setting `jit_compile=False` to get rid of XLA would resolve this issue (ops run only on GPU) but loses JIT benefits.

**Comment by tilakrayal** [comment]
@charlielam0615 ,
The code provided is not complete hence it would be difficult for us to pinpoint the issue in the tensorboard. Please share complete stand alone code to replicate the issue or a colab gist with the error reported.?

**Comment by charlielam0615** [comment]
I don't understand. The code is complete and it is a somewhat minimum stand alone code to replicate this issue. Am I missing something?

If I have to break this down into steps...

Step 1. Run the notebook in the [gist](https://colab.research.google.com/gist/tilakrayal/e35a9f5983135d4cbb7ba29525bb6fc1/untitled228.ipynb) (which you provide)
Step 2. Click 'Files' on the left panel, and in the file panel right-click and choose "refresh", you should see a directory named "profile_results_simple"
Step 3. Create a new cell, and compress "profile_results_simple" into a zip file in order to download it by running `!zip -r profile_results_simple.zip profile_results_simple`
Step 4. Download "profile_results_simple.zip", uncompress it, visualize it using tensorboard, and voila.

**Comment by mohantym** [comment]
Hi @charlielam0615 ! I used tf.debugging.set_log_device_placement(True) to see device usage in [Colab](https://colab.sandbox.google.com/gist/mohantym/9ca0a2807d64f33cf11feec023f672e2/untitled228.ipynb#scrollTo=GT0_l7GOz5hx) with 2.8. It was using GPU in entire operation.  Can you try in TF 2.8/nightly and let us know?

**Comment by charlielam0615** [comment]
> Hi @charlielam0615 ! I used **tf.debugging.set_log_device_placement(True)** to see device usage in [Colab](https://colab.sandbox.google.com/gist/mohantym/9ca0a2807d64f33cf11feec023f672e2/untitled228.ipynb#scrollTo=GT0_l7GOz5hx) with 2.8. It was using GPU in entire operation. Can you try in TF 2.8/nightly and let us know?

Interesting. I am confused then. Why does the profiler show lots of ops running on CPU when visualized in tensorboard? There seems to be some contradiction in results given by `tf.debugging.set_log_device_placement(True)` and tensorflow profiler.

**Comment by mohantym** [comment]
Hi @gadagashwini ! Could you please look at this issue ? It is replicating in [2.7](https://colab.research.google.com/gist/mohantym/b8e01d36c61ae847c3fd40d90868605a/untitled228.ipynb#scrollTo=CumlNBz0QYXy), [2.8](https://colab.research.google.com/gist/mohantym/9ca0a2807d64f33cf11feec023f672e2/untitled228.ipynb#scrollTo=a3BsA6yhQbwG) and [nightly](https://colab.research.google.com/gist/mohantym/b8e01d36c61ae847c3fd40d90868605a/untitled228.ipynb#scrollTo=CumlNBz0QYXy). Thanks

**Comment by sachinprasadhs** [comment]
In the Gist [here](https://colab.sandbox.google.com/gist/mohantym/9ca0a2807d64f33cf11feec023f672e2/untitled228.ipynb#scrollTo=GT0_l7GOz5hx) it shows all the Ops are running in GPU and tensorboard also shows device used as GPU. Could you please point out in tensorboard for the ops running in CPU. Thanks!

**Comment by charlielam0615** [comment]
Hi @sachinprasadhs! If you select "Tools→Trace Viewer", the tensorboard shows almost every op runs both on GPU **and** host CPU, which is very confusing. I verified this on the gist you provided.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
