### ISSUE TITLE
TensorBoard could not refresh automatically when use HDFS path as logdir?

### ISSUE THREAD

**Issue by wangyang0918** [tensorflow/tensorflow#5438]
Environment
https://github.com/tensorflow/ecosystem/blob/master/docker/Dockerfile.hdfs

I use the following command to start a tensorflow job. It works well. However, the tensor board could not refresh automatically unless restart the tensor board server.

<pre><code>
python mnist.py --data_dir=hdfs://hdpalt/user/danrtsey.wy/mnist-data --train_dir=hdfs://hdpalt/user/danrtsey.wy/.slider/checkpoints/test1
</code></pre>
<pre><code>
tensorboard --logdir=hdfs://hdpalt/user/danrtsey.wy/.slider/checkpoints/test1
</code></pre>

BTW, i find the file size of event file on HDFS does not update. Although, the content has changed. Is this the reason?
<pre><code>
$hadoop fs -ls hdfs://hdpalt/user/danrtsey.wy/.slider/checkpoints/test1/events.out.tfevents.1478500140.8e103b0b7135
-rw-r--r--   3 yarn danrtsey.wy         40 2016-11-07 14:29 hdfs://hdpalt/user/danrtsey.wy/.slider/checkpoints/test1/events.out.tfevents.1478500140.8e103b0b7135
</code></pre>
<pre><code>
$hadoop fs -cat hdfs://hdpalt/user/danrtsey.wy/.slider/checkpoints/test1/events.out.tfevents.1478500140.8e103b0b7135 | wc -l
9312
</code></pre>

**Comment by aselle** [comment]
@jhseu, @danmane, any ideas won why this might be?

**Comment by spaceplane** [comment]
when a HDFS file writing, its length listed from Namenode will not be updated until a block completed or the file created with SyncFlag.UPDATE_LENGTH, but the new data flushed can be read to the new reader.

**Comment by renchunde** [comment]
When a HDFS file writing, its length listed/got from Namenode will not be updated until the block completed or the file created with SyncFlag.UPDATE_LENGTH, but the new data flushed from OutputStream will be available to read for new reader only.

**Comment by jhseu** [comment]
Fixed internally and will show up during the next commit sync within a day or so.

We now reopen the inputstream upon reaching EOF as suggested by @renchunde.

**Comment by jhseu** [comment]
Also note that the file size still doesn't update when listing the directory, but the new contents are available for reading and show up on tensorboard.

**Comment by wangyang0918** [comment]
Thanks a lot for your attention to this issue. I will help to confirm after the next commit sync.
