### ISSUE TITLE
WARNING: 404 Not Found

### ISSUE THREAD

**Issue by yIllusionSky** [tensorflow/tensorflow#54393]
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/vcpkg/downloads/tools/msys2/16665682389be3a4/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/vcpkg/downloads/tools/msys2/16665682389be3a4/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=D:/vcpkg/downloads/tools/msys2/16665682389be3a4/mingw64/lib/python3.8/site-packages --python_path=D:/vcpkg/downloads/tools/msys2/16665682389be3a4/mingw64/bin/python3.exe --define=with_xla_support=false --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\vcpkg\buildtrees\tensorflow-cc\x64-windows-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/64c92c8013b557087351c91b5423b6046d10f206.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/43d6991c2a4cc2ac374e68c029634f2b59ffdfdf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/WORKSPACE:23:14: in <toplevel>
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/workspace0.bzl:108:34: in workspace
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Repository local_config_cc instantiated at:
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/WORKSPACE:23:14: in <toplevel>
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/workspace0.bzl:106:24: in workspace
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/repositories.bzl:28:17: in rules_cc_toolchains
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/cc_configure.bzl:180:16: in cc_configure
Repository rule cc_autoconf defined at:
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/cc_configure.bzl:143:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/cc_configure.bzl", line 120, column 36, in cc_autoconf_impl
		configure_windows_toolchain(repository_ctx)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 694, column 31, in configure_windows_toolchain
		msvc_vars = _get_msvc_vars(repository_ctx, paths)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 535, column 28, in _get_msvc_vars
		env = setup_vc_env_vars(repository_ctx, vc_path)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 318, column 24, in setup_vc_env_vars
		_check_env_vars(env_map, cmd, expected = envvars)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 324, column 32, in _check_env_vars
		auto_configure_fail(
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Setting up VC environment variables failed, WINDOWSSDKDIR is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64  -vcvars_ver=14.29.30133
ERROR: Error fetching repository: Traceback (most recent call last):
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/cc_configure.bzl", line 120, column 36, in cc_autoconf_impl
		configure_windows_toolchain(repository_ctx)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 694, column 31, in configure_windows_toolchain
		msvc_vars = _get_msvc_vars(repository_ctx, paths)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 535, column 28, in _get_msvc_vars
		env = setup_vc_env_vars(repository_ctx, vc_path)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 318, column 24, in setup_vc_env_vars
		_check_env_vars(env_map, cmd, expected = envvars)
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/windows_cc_configure.bzl", line 324, column 32, in _check_env_vars
		auto_configure_fail(
	File "D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/rules_cc/cc/private/toolchain/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Setting up VC environment variables failed, WINDOWSSDKDIR is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64  -vcvars_ver=14.29.30133
INFO: Repository rules_proto instantiated at:
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/WORKSPACE:23:14: in <toplevel>
  D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/workspace0.bzl:120:20: in workspace
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/com_google_protobuf/protobuf_deps.bzl:42:21: in protobuf_deps
Repository rule http_archive defined at:
  D:/vcpkg/buildtrees/tensorflow-cc/.bzl/hwfhzki5/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: D:/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg/tensorflow/cc/BUILD:125:11: //tensorflow/cc:gradient_checker depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//': 
Auto-Configuration Error: Setting up VC environment variables failed, WINDOWSSDKDIR is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\VCVARSALL.BAT" amd64  -vcvars_ver=14.29.30133
ERROR: Analysis of target '//tensorflow:install_headers' failed; build aborted: Analysis failed
INFO: Elapsed time: 120.017s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (60 packages loaded, 167 targets configured)
FAILED: Build did NOT complete successfully (60 packages loaded, 167 targets configured)

**Comment by tilakrayal** [comment]
@yIllusionSky ,
Can you please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/43979) with the similar error.It helps.
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

**Comment by yIllusionSky** [comment]
> @yIllusionSky ， 你能用类似的错误看看这个 [问题 ](https://github.com/tensorflow/tensorflow/issues/43979)有帮助。 为了加快故障排除过程，您能否提供以下信息 操作系统平台和发行版（例如，Linux Ubuntu 16.04）： 移动设备（例如 iPhone 8、Pixel 2、Samsung Galaxy）如果问题发生在移动设备上： TensorFlow 安装自（源代码或二进制文件）： TensorFlow 版本： 蟒蛇版本： 使用 virtualenv 安装？ 点子？ 康达？： Bazel 版本（如果从源代码编译）： GCC/编译器版本（如果从源代码编译）： CUDA / cuDNN 版本： GPU型号和内存：

It seems to have been installed successfully again. Thank you. It's all right
