### ISSUE TITLE
The model size after Lite conversion is much larger than the original Tensorflow model

### ISSUE THREAD

**Issue by sonnykurniawan** [tensorflow/tensorflow#54405]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip install
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.8.0

### 2. Code
```
import tensorflow as tf
import tensorflow_text as text
converter = tf.lite.TFLiteConverter.from_saved_model(
    saved_model_dir='chatter_engine',
    signature_keys=['serving_default']
)  # path to the SavedModel directory
print('after load')
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.target_spec.supported_types = [tf.float16]

print('before conversion')
tflite_model = converter.convert()
print('after conversion')

# Save the model.
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
print('after write')

```

```
- Tensorflow model : https://drive.google.com/drive/folders/1WrNca1DQ9xpbH00JAVQKE8PsxFzB60qj?usp=sharing
- Tensorflow lite model: https://drive.google.com/file/d/1nqpkM3ShOTit37BHZ1A5DYEDCjaaac6J/view?usp=sharing
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong: the converted model size is more than 400 MB where the original model is only 4 MB

**Comment by mohantym** [comment]
Hi @chunduriv! Could you please look at this issue? It is replicating in 2.7 ,[2.8 ](https://colab.sandbox.google.com/gist/mohantym/0e54856c2c952ab3d5c9763384fc6131/github_54405.ipynb#scrollTo=iQvBGhKm-p7v)and nightly. Size of  tflite file came 400 mb after conversion as mentioned in template.

**Comment by cstamatopoulos** [comment]
I am also having the same issue.
I have a custom TF model that is about 16Mb
Sizes after conversion are

TF Lite Dynamic Range file size is 73.5 Mb
TF Lite Int with float fallback file size is 267.7 Mb
TF lite Full integer quantization file size is 271.2 Mb

Here is a colab that showcases the problem
TensorFlow 2.8
https://colab.research.google.com/drive/1uYZOrPJWbSGfhf-DYEgMtCVmy5xLBE5G?usp=sharing
TensorFlow 2.7.1
https://colab.research.google.com/drive/15kzXMSF2olfzNskYN99WKq7DarUy-3tj?usp=sharing

Note that integer quantization fails in 2.7.1 and for all model generated they have an incorrect input size of 1x1x1x3 but I will open a separate issue for that.

**Comment by karimnosseir** [comment]
Please see my reply on similar question [here](https://github.com/tensorflow/tensorflow/issues/54659)

**Comment by karimnosseir** [comment]
Closing please reopen if you have questions.

Thanks

**Comment by bgr2rgb** [comment]
@cstamatopoulos Did you manage to solve it after all? Having similar problem with model size exploding from 14M to 2GB after quantization
