### ISSUE TITLE
Help! Didnt change anything in code and was working fine but today tensorflow gives me a bug.

### ISSUE THREAD

**Issue by RitoRitoni** [tensorflow/tensorflow#54404]
Hi guys, till yesterday i was running without a problem my GAN in colab pro + and today i stopped it and tried to begin it again and i am taking an error  "NotImplementedError: Cannot convert a symbolic Tensor (frame/Size:0) to a numpy array." I literally didnt change a single thing and i am doing this process the last month without a problem. Does anyone know what is happening?

**Comment by sushreebarsa** [comment]
@RitoRitoni 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by polxo00** [comment]
Hi, I have the same issue since Tuesday. Have you solved it? or do you know what has happened?
Thanks!

**Comment by sushreebarsa** [comment]
@RitoRitoni 
In order to reproduce the issue reported here, could you please  fill the [template](https://github.com/tensorflow/tensorflow/issues/new/choose)  and provide the complete code  , tensorflow version you are using? Thanks!
