### ISSUE TITLE
```tf.GradientTape``` returns None gradient in fitting RNN

### ISSUE THREAD

**Issue by DagonArises** [tensorflow/tensorflow#54417]
Define h_t as the hidden states of SimpleRNN layer at step t. h_0 the initial hidden states. In a model with an embedding layer and SimpleRNN layer, I would like to compute the partial derivative dh_t/dh_0 for each step t. 

The structure of my model:
```
# For each h_t, compute gradient:
batch_size = 100; input_length = 1403
inp= Input(batch_shape= (batch_size, input_length), name= 'input') 
emb_out= Embedding(input_dim, output_dim, input_length= input_length, 
                         weights= [Emat], trainable= False, name= 'embedding')(inp)
rnn= SimpleRNN(200, return_sequences= True, return_state= False, stateful= True, name= 'simpleRNN')

h0 = tf.convert_to_tensor(np.random.uniform(size= (batch_size, 200)).astype(np.float32))
rnn_allstates= rnn(emb_out, initial_state=h0) 
model_rnn = Model(inputs=inp, outputs= rnn_allstates, name= 'model_rnn')
model_rnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

ds = tf.data.Dataset.from_tensor_slices((xtr_pad[:100], ytr[:100])).batch(100)
embedding_layer = model_rnn.layers[1]
rnn_layer = model_rnn.layers[2]

grads_allsteps= []
for b, (x_batch_train, y_batch_train) in enumerate(ds):
    for t in range(input_length):
        with tf.GradientTape() as tape:
            tape.watch(h0)
            et = embedding_layer(x_batch_train)
            states = rnn_layer(et, initial_state= h0)   # (100, 1403, 200)
            ht = states[:,t,:]  # (100, 200)

        grad_t= tape.gradient(ht, h0)  # (100, 200)
        print('Computed gradient dht/dh0 at step ', t+1, 'in batch', b+1)
        grads_allsteps.append(grad_t)
``` 
At each step t, h_t has shape (100,200), h_0 has shape (100,200). However ```tape.gradient(ht, h0)``` returns None for every t. Below is the result of the first step:
```
for t in range(1):
    with tf.GradientTape() as tape:
        tape.watch(h0)
        et = embedding_layer(x_batch_train)
        #tape.watch(et)
        states = rnn_layer(et, initial_state= h0)   # (100, 1403, 200)
        ht = states[:,t,:] 
        print(ht)
        print(h0)
    grad_t = tape.gradient(ht, h0)
    tf.print(grad_t)

>>
# h_t:
tf.Tensor(
[[ 0.25634336  0.5259362   0.60045886 ... -0.4978792   0.62755316
   0.09803997]
 [ 0.58387524  0.26037565  0.5646103  ...  0.31233114  0.4853201
   0.10877549]
 [ 0.17190906  0.68681747 -0.32054633 ... -0.6139967   0.48944488
   0.06301598]
 ...
 [ 0.1985917  -0.11821499 -0.47709295 ... -0.05718012  0.16089934
   0.20585683]
 [ 0.73872745  0.503326    0.25224414 ... -0.5771631   0.03748894
   0.09212588]
 [-0.6597108  -0.43926442 -0.23546427 ...  0.26760277  0.28221437
  -0.4039318 ]], shape=(100, 200), dtype=float32)

# h_0:
tf.Tensor(
[[0.51580787 0.51664346 0.70773274 ... 0.45973232 0.7760376  0.48297063]
 [0.61048764 0.26038417 0.60392565 ... 0.7426153  0.15507504 0.57494944]
 [0.11859739 0.33591187 0.68375146 ... 0.59409297 0.5302879  0.28876984]
 ...
 [0.12401487 0.39376178 0.9850304  ... 0.21582918 0.9592233  0.5257605 ]
 [0.9401199  0.2157638  0.6445949  ... 0.36316434 0.5799403  0.3749675 ]
 [0.37230062 0.18162128 0.0739954  ... 0.21624395 0.66291    0.7807376 ]], shape=(100, 200), dtype=float32)

# dh_t/dh_0:
None
```
I have successfully used GradientTape watch the inputs e_t to the RNN layer, and computed the gradients dh_t/de_t, but this does not really provide much information about the quality of model fitting. I would like to base the gradient on a quantity only at the start of the sequence.

There seems to be some difficulty for Gradient tape to watch this fixed-time quantity h_0, and perform gradient computation for dh_t/dh_0. Is there a way I can obtain this gradient shaped (100,200)? Thanks in advance for any help.

**Comment by sushreebarsa** [comment]
@DagonArises 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by DagonArises** [comment]
@sushreebarsa I have filled in what I can find out. Please let me know if you need anything else. Thanks in advance for helping me with the GradientTape operation.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur 11.3.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): v2.6.1-9-gc2363d6d025 2.6.2
- Python version:  Python 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 2.3 GHz Quad-Core Intel Core i7; 32 GB 3733 MHz LPDDR4X

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Please refer to the code below for details.
```tape.gradient(states, h0)``` returns a gradient of shape (100, 200). However I would like to obtain the gradient to contain the step index. After I added a loop over the steps, at each step t, ht has shape (100,200), h0 has shape (100,200). However ```tape.gradient(ht, h0)``` returns dh_t/dh_0 but it is None type.

**Describe the expected behavior**
I am expecting ```tape.gradient(ht, h0)``` to return me a gradient object shaped (100,200), instead of None. 
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
# For each h_t, compute gradient:
batch_size = 100; input_length = 1403
inp= Input(batch_shape= (batch_size, input_length), name= 'input') 
emb_out= Embedding(input_dim, output_dim, input_length= input_length, 
                         weights= [Emat], trainable= False, name= 'embedding')(inp)
rnn= SimpleRNN(200, return_sequences= True, return_state= False, stateful= True, name= 'simpleRNN')

h0 = tf.convert_to_tensor(np.random.uniform(size= (batch_size, 200)).astype(np.float32))
rnn_allstates= rnn(emb_out, initial_state=h0) 
model_rnn = Model(inputs=inp, outputs= rnn_allstates, name= 'model_rnn')
model_rnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

ds = tf.data.Dataset.from_tensor_slices((xtr_pad[:100], ytr[:100])).batch(100)
embedding_layer = model_rnn.layers[1]
rnn_layer = model_rnn.layers[2]

grads_allsteps= []
for b, (x_batch_train, y_batch_train) in enumerate(ds):
    for t in range(input_length):
        with tf.GradientTape() as tape:
            tape.watch(h0)
            et = embedding_layer(x_batch_train)
            states = rnn_layer(et, initial_state= h0)   # (100, 1403, 200)
            ht = states[:,t,:]  # (100, 200)

        grad_t= tape.gradient(ht, h0)  # (100, 200)
        print('Computed gradient dht/dh0 at step ', t+1, 'in batch', b+1)
        grads_allsteps.append(grad_t)
```

First step as a test case:
```
for t in range(1):
    with tf.GradientTape() as tape:
        tape.watch(h0)
        et = embedding_layer(x_batch_train)
        #tape.watch(et)
        states = rnn_layer(et, initial_state= h0)   # (100, 1403, 200)
        ht = states[:,t,:] 
        print(ht)
        print(h0)
    grad_t = tape.gradient(ht, h0)
    tf.print(grad_t)

>>
# h_t:
tf.Tensor(
[[ 0.25634336  0.5259362   0.60045886 ... -0.4978792   0.62755316
   0.09803997]
 [ 0.58387524  0.26037565  0.5646103  ...  0.31233114  0.4853201
   0.10877549]
 [ 0.17190906  0.68681747 -0.32054633 ... -0.6139967   0.48944488
   0.06301598]
 ...
 [ 0.1985917  -0.11821499 -0.47709295 ... -0.05718012  0.16089934
   0.20585683]
 [ 0.73872745  0.503326    0.25224414 ... -0.5771631   0.03748894
   0.09212588]
 [-0.6597108  -0.43926442 -0.23546427 ...  0.26760277  0.28221437
  -0.4039318 ]], shape=(100, 200), dtype=float32)

# h_0:
tf.Tensor(
[[0.51580787 0.51664346 0.70773274 ... 0.45973232 0.7760376  0.48297063]
 [0.61048764 0.26038417 0.60392565 ... 0.7426153  0.15507504 0.57494944]
 [0.11859739 0.33591187 0.68375146 ... 0.59409297 0.5302879  0.28876984]
 ...
 [0.12401487 0.39376178 0.9850304  ... 0.21582918 0.9592233  0.5257605 ]
 [0.9401199  0.2157638  0.6445949  ... 0.36316434 0.5799403  0.3749675 ]
 [0.37230062 0.18162128 0.0739954  ... 0.21624395 0.66291    0.7807376 ]], shape=(100, 200), dtype=float32)

# dh_t/dh_0:
None
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by DagonArises** [comment]
@sushreebarsa  Hi I have updated with a simple test case, and found something interesting: the first-step gradient is computed and looks fine. But the rest are Nones even when I set persistent = True.

**Comment by DagonArises** [comment]
@sushreebarsa 
Have you looked up the content in ```grads_allsteps```? I have run your code and got the same output as before, did you find different outputs?
```
[<tf.Tensor: shape=(100, 200), dtype=float32, numpy=
 array([[-1.1518437 ,  0.09250898,  0.63095075, ...,  1.0590861 ,
         -1.1120602 ,  1.8342849 ],
        [-1.2972618 ,  0.07211287,  0.7869835 , ...,  1.1403981 ,
         -0.976047  ,  1.7088349 ],
        [-1.318328  ,  0.20531593,  0.89947236, ...,  0.97652054,
         -0.8525504 ,  1.6919007 ],
        ...,
        [-1.1943431 ,  0.18806057,  0.7745916 , ...,  1.2284715 ,
         -0.78275585,  1.8919656 ],
        [-1.112908  ,  0.22119978,  0.8069727 , ...,  0.9464315 ,
         -1.2341805 ,  1.6773576 ],
        [-1.2471178 ,  0.34073132,  0.60667646, ...,  0.8718521 ,
         -1.0613108 ,  1.4353436 ]], dtype=float32)>, None, None, None, None]
```

Anyways I have found a way around it: simply ```tf.gradients(ht, h0)``` will consistently compute the gradients. Seems that Tape really needs the source to be the 'real input' to NN. Probably h0 is not a typical source.

**Comment by sushreebarsa** [comment]
@DagonArises Thank you for the update!
@chunduriv I was able to replicate the issue on colab using TF [v2.8.0](https://colab.research.google.com/gist/sushreebarsa/633bfbe5a5a4c867f487c4729c98eefa/54417.ipynb#scrollTo=hZuT2KJz-bYy) and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/e648d2fb4e48ee6a38e1f7d86ec2dbad/54417.ipynb#scrollTo=VNtcMcCwPjhd)(2.9.0.dev20220224) , please find the attached gists for reference.Thanks!

**Comment by gowthamkpr** [comment]
@DagonArises Linking this solution [here](https://stackoverflow.com/questions/71153292/tf2-0-gradient-tape-returns-none-gradient-in-rnn-model) as it would be helpful for the community. Please close this issue as it has been resolved. Thanks!
