### ISSUE TITLE
`tf.boolean_mask` lack checking for bool arguments

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54412]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
tensor = [0,1,2,3]
mask = tf.random.uniform([4], dtype=tf.float64)
tf.boolean_mask(tensor, mask) 
# Outputs: <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>
```

**Describe the current behavior**
`tf.boolean_mask` has an argument `mask` which should be a `bool` tensor. However, it does not perform any validity checking and can accept a `float64` value. 

**Describe the expected behavior**
`tf.boolean_mask` should check the dtype of input tensor `mask`.

For example, `tf.math.reduce_any` would check the first argument and throw an `InvalidArgumentError` for non-boolean inputs.
```
import tensorflow as tf
input_tensor = tf.random.uniform([4], dtype=tf.float64)
tf.math.reduce_any(input_tensor) # InvalidArgumentError: cannot compute Any as input #0(zero-based) was expected to be a bool tensor but is a double tensor [Op:Any]
```

**Comment by yongtang** [comment]
Added a PR #54412 for the fix.

**Comment by chunduriv** [comment]
@ArrowIntoTheSky, The issue will move to closed status once the https://github.com/tensorflow/tensorflow/pull/54432 is merged. Thanks!
