### ISSUE TITLE
`tf.math.cumsum` lack checking for bool arguments

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54410]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = [0.5, 1.0, 2.0, 4.0]
axis = 0
exclusive = -1
reverse = -1
res_1 = tf.math.cumsum(x, axis=axis, exclusive=exclusive, reverse=reverse)
print(res_1) # tf.Tensor([7. 6. 4. 0.], shape=(4,), dtype=float32)
res_2 = tf.raw_ops.Cumsum(x=x, axis=axis, exclusive=exclusive, reverse=reverse)
print(res_2) # TypeError: Expected bool for argument 'exclusive' not -1.
```

**Describe the current behavior**
`tf.math.cumsum` has an argument `exclusive` which should be a `bool`. However, it does not perform any validity checking and can accept a non-bool value like `-1`.  `tf.raw_ops.Cumsum` (another API which does the same job) can detect this error and raise an `TypeError`.

**Describe the expected behavior**
`tf.math.cumsum` should check the type of input values for `exclusive` and `reverse`.

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.7,v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e28662bd282cf264ba33fb906a21105d/54410.ipynb).

**Comment by jvishnuvardhan** [comment]
@ArrowIntoTheSky Agree with you that this is a bug we need to fix. Thanks for raising it.
I am working on to fix the issue. Thanks!

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky ! This issue is not replicating any more in [2.8](https://colab.sandbox.google.com/gist/mohantym/597924703d660bae5b66a43b92036f5e/untitled370.ipynb#scrollTo=T2-hlunyu4qa) version. Can we move this to closed status now? Thanks!
