### ISSUE TITLE
`tf.compat.as_bytes` does not check the encoding string

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54413]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
bytes_or_text = "hello"
encoding = "valid"
t1 = tf.compat.as_text(bytes_or_text, encoding=encoding)
print(t1) # hello
t2 = tf.compat.as_bytes(bytes_or_text,encoding=encoding)
# LookupError: unknown encoding: valid
```

**Describe the current behavior**
`"valid"` is not valid value for `encoding`, as we can see that `tf.compat.as_bytes` would throw an `LoopupError`. However, `tf.compat.as_text` does not perform any validity checking and can accept it and even give an output.

**Describe the expected behavior**
`tf.compat.as_text` should check the validity of `encoding`.

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky ,
Please find the difference between tf.compat.as_text and tf.compat.as_bytes.
tf.compat.as_text:Converts any string-like python input types to unicode.
tf.compat.as_bytes:Converts bytearray, bytes, or unicode python input types to bytes

**Comment by ArrowIntoTheSky** [comment]
@tilakrayal 
Yes, they are different APIs. I just use `tf.compat.as_bytes` to show the correct error handling of a **wrong** encoding string. It is obvious that `encoding` cannot be `valid` or `hi` as in the following example:
```
import tensorflow as tf
bytes_or_text = "hello"
encoding = "hi"
t1 = tf.compat.as_text(bytes_or_text, encoding=encoding) # This pass! But it should not.
```

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/00dfd63ad2db6914065b7d00893cfc41/54413.ipynb).

**Comment by yongtang** [comment]
Added a PR #54503 for the fix.
