### ISSUE TITLE
`tf.histogram_fixed_width_bins` lack checking for `nbins`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54415]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
nbins = -16
value_range = [0.0, 5.0]
new_values = [-1.0, 0.0, 1.5, 2.0, 5.0, 15]
indices = tf.histogram_fixed_width_bins(new_values, value_range, nbins=nbins)
indices.numpy()
```
Outputs:
```
array([0, 0, 0, 0, 0, 0], dtype=int32)
```

**Describe the current behavior**
`tf.histogram_fixed_width_bins` has an argument `nbins` which should be a **positive** integer. However, it does not perform any validity checking and can accept a **negative** value like `-16`.  `tf.histogram_fixed_width` (another API with similar functionality) can detect this error and raise an `InvalidArgumentError`:
```
import tensorflow as tf
nbins = -16
value_range = [0.0, 5.0]
new_values = [-1.0, 0.0, 1.5, 2.0, 5.0, 15]
indices = tf.histogram_fixed_width(new_values, value_range, nbins=nbins)
indices.numpy()
# InvalidArgumentError: nbins should be a positive number, but got '-16' [Op:HistogramFixedWidth]
```

**Describe the expected behavior**
`tf.histogram_fixed_width_bins` should have better input checking.

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky ! It is throwing invalid argument error in 2.8 as expected . Attaching gist in 2.7 and 2.8  for reference. Thanks!

**Comment by yongtang** [comment]
Added a PR #54429 for the fix.
