### ISSUE TITLE
`tf.math.atan` lack support for `complex64`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54411]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.complex(tf.random.uniform([8, 8], dtype=tf.float32),tf.random.uniform([8, 8], dtype=tf.float32))
print(x.dtype) # <dtype: 'complex64'>
tf.math.atan(x)
```

**Describe the current behavior**
`tf.math.atan` cannot accept a tensor of type `complex64`. However, according to the [document](https://www.tensorflow.org/api_docs/python/tf/math/atan?hl=en) it should support `complex64` and `complex128`.
For the above code snippet, the error message is:
```
NotFoundError: Could not find device for node: {{node Atan}} = Atan[T=DT_COMPLEX64]
All kernels registered for op Atan:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
 [Op:Atan]
```

**Comment by rthadur** [comment]
Related PR has been merged here are the [changes](https://github.com/tensorflow/tensorflow/commit/64af5cd59743d8d595ec4d3654e25ffb11e6ef0d) . Thank you for raising the issue.
