### ISSUE TITLE
tflite inference on single image confidence scores.

### ISSUE THREAD

**Issue by abaqusstudent** [tensorflow/tensorflow#54420]
I am fairly new to tensorflow and I have a tflite model which needs inference on a single image (ie no datasets).  When I run the inference on the quantised model, I out output confidence scores in the range of [0,255] as uint8.

However, when I do the inference on batch I get scores in the [0,1] float range.

I am a bit puzzled why this is. For example, if you see this post: https://thinkmobile.dev/testing-tensorflow-lite-image-classification-model/ you can see that the model results are in the 0-1 range, but, if you do it over a single image like so: https://towardsdev.com/custom-image-classification-model-using-tensorflow-lite-model-maker-68ee4514cd45 the results are in [0-255] int range.

Bit perplexed as to why this is.

**Comment by tilakrayal** [comment]
@abaqusstudent ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.
