### ISSUE TITLE
einsum with ellipses "..." (indefinite number of axes)

### ISSUE THREAD

**Issue by isabeaups** [tensorflow/tensorflow#5443]
Thank you very much for providing the (numpy) einsum feature in tensorflow, that is really great. The documentation for einsum says to look at the numpy documentation as it provides the same api. It is not exactly the same, one difference is the possibility of using "..." in numpy which seems not to be implemented in tensorflow. This would definitely be a nice feature to have in tensorflow also since that way one could build various function/transformations in tensorflow which are not dependent on the number of axis the tensor has (i.e. the specific use case). 

Here is the error I encountered when trying to do that:
`d = tf.einsum("i...,ij->j...",c,b)`

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-12-d7c0123ec21a> in <module>()
> ----> 1 d = tf.einsum("i...,ij->j...",c,b)
> 
> //anaconda/envs/chaos/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py in einsum(axes, *inputs)
>     100   match = re.match('([a-z,]+)->([a-z]+)', axes)
>     101   assert match, \
> --> 102     "Indices have incorrect format: %s" % axes
>     103 
>     104   inputs = list(inputs)
> 
> AssertionError: Indices have incorrect format: i...,ij->j...

**Comment by isabeaups** [comment]
@nikhilmishra000 I believe you implemented it? Maybe you know of a work around in the meantime?

**Comment by aselle** [comment]
einsum is known to be not fully implemented (see #4722). We welcome continued contributions to improve it (as it was a contribution in of itself). Thanks for bringing this up.

**Comment by nikhilmishra000** [comment]
@isabeaups, see the following from the docstring about the current implementation:
```
Like `numpy.einsum`, but does not support:
* Ellipses (subscripts like `ij...,jk...->ik...`)
* Subscripts where an axis appears more than once for a single input (e.g. `ijj,jk->ik`).
```
It shouldn't be too hard to add some of this functionality, if you wanted to take a stab at it :D

**Comment by isabeaups** [comment]
Thanks @nikhilmishra000. I don't really know C++, but I might take a look at it.

**Comment by isabeaups** [comment]
@nikhilmishra000 I just looked at the code and it is in python so that is good. If you could maybe explain to me the code (once the indices and axes are defined, I get that from the code, how do you contract them) then I would be happy to add this functionality to it.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity, but please let me know if I'm mistaken. Thanks!

**Comment by sushreebarsa** [comment]
@isabeaups Is this still an issue ?
Could you please have a look at this [thread](https://stackoverflow.com/questions/55549264/ultimate-flexibility-with-einsum-ellipses) and refer to this [link](https://www.tensorflow.org/api_docs/python/tf/einsum) ,please let us know if it helps?
Thanks!

**Comment by isabeaups** [comment]
@sushreebarsa  Thanks. I don't know if this is still an issue, I have not used TF for years now since I moved to PyTorch

**Comment by tilakrayal** [comment]
@isabeaups,
Einsum allows defining Tensors by defining their element-wise computation. This computation is defined by the equation, a shorthand form based on Einstein summation.
**tf.Einsum** -- Tensor contraction over specified indices and outer product.

Could you please take a look at the code below.


```
import tensorflow as tf
print(tf.__version__)
m0 = tf.random.normal(shape=[2, 3])
m1 = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij,jk->ik', m0, m1)
# output[i,k] = sum_j m0[i,j] * m1[j, k]
print(e.shape)
```

Output:
```
2.8.2
(2, 5)
```
```
import tensorflow as tf
print(tf.__version__)
s = tf.random.normal(shape=[11, 7, 5, 3])
t = tf.random.normal(shape=[11, 7, 3, 2])
e =  tf.einsum('...ij,...jk->...ik', s, t)
print(e.shape)
```
output:

```
2.8.2
(11, 7, 5, 2)
```
