### ISSUE TITLE
libXNNPACK.so: internal symbol `xnn_f16_ibilinear_ukernel__neonfp16arith_c8' isn't defined

### ISSUE THREAD

**Issue by fengyuentau** [tensorflow/tensorflow#54437]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 56e2e916929746cd6c415c2a402a46349bffa7e0 (commit id)
- Python version: N/A
- Installed using virtualenv? pip? conda?:  N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

I was trying to build TFLite with XNNPACK delegate natively on [an ARM-based board](https://www.khadas.com/vim3) using CMake. Previously I successfully built TFLite as static library, but when I tried to link it to my program, many errors of undefined references related to `ruy` happened. So I turned to compile TFLite as shared library instead, but got the following error:
```
[ 21%] Linking CXX shared library libXNNPACK.so
/usr/bin/ld: CMakeFiles/XNNPACK.dir/src/init.c.o: in function `init':
init.c:(.text+0x139c): undefined reference to `xnn_f16_ibilinear_ukernel__neonfp16arith_c8'
/usr/bin/ld: init.c:(.text+0x13a0): undefined reference to `xnn_f16_ibilinear_ukernel__neonfp16arith_c8'
/usr/bin/ld: libXNNPACK.so: internal symbol `xnn_f16_ibilinear_ukernel__neonfp16arith_c8' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/xnnpack-build/CMakeFiles/XNNPACK.dir/build.make:6532: _deps/xnnpack-build/libXNNPACK.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:5486: _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
cmake -B tflite-build -DBUILD_SHARED_LIBS=ON tensorflow/tensorflow/lite
cmake --build tflite-build -j 4
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by fengyuentau** [comment]
@mohantym Thanks for the reply, but TFLite is compiled natively on ARM in my case.

**Comment by mjp9527** [comment]
> Hi @fengyuentau ! Can you check below command after declaring [ARM 64 SDK tool chain](https://www.tensorflow.org/lite/guide/build_cmake#cross-compilation) in path and removing -DBUILD_SHARED_LIBS=ON flag ? Thanks!
> 
> `cmake -DCMAKE_TOOLCHAIN_FILE=<CMakeToolchainFileLoc> ../tensorflow/lite/`

I met the same problem and I can compile static library successfully, but failed with "-DBUILD_SHARED_LIBS=ON" on Android64.  "error: undefined reference to `xnn_f16_ibilinear_ukernel__neonfp16arith_c8'"

**Comment by fengyuentau** [comment]
@mjp9527 Did you have undefined reference related to `ruy` when linking TFLite static library to your programe?

**Comment by mjp9527** [comment]
> @mjp9527 Did you have undefined reference related to `ruy` when linking TFLite static library to your programe?

@fengyuentau ......I was wrong,  this error appeared again when linking TFLite static library.
![image](https://user-images.githubusercontent.com/54735487/154673663-238ab5bc-a780-47b4-97e2-f5f68b0d43e9.png)

**Comment by Maratyszcza** [comment]
This was fixed in XNNPACK in google/XNNPACK@ba7e4bf72936ad7dcb750707eb519cd9c56bc1c9, and the latest revision of TensorFlow shouldn't have this issue.

**Comment by fengyuentau** [comment]
@Maratyszcza Let me check which version of XNNPACK is using when I compiled TLite.

**Comment by fengyuentau** [comment]
@Maratyszcza The last compilation I tried was 3 days ago, but somehow CMake scripts downloaded XNNPACK at https://github.com/google/XNNPACK/commit/d605aa76904aa1c5ea98bb7a0a4bafc4886b8a0a, which was 6 days ago (The fix you mention was 5 days ago). Do you know how to force using latest of XNNPACK?

**Comment by fengyuentau** [comment]
I wonder if `pip install tflite-runtime` comes with XNNPACK delegate for aarch64, which can be a workaround for now.

**Comment by Maratyszcza** [comment]
XNNPACK revision used in the build is specified [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/modules/xnnpack.cmake#L26). You'd probably need to remove all configuration artifacts and reconfigure TFLite after updating this line.

**Comment by fengyuentau** [comment]
@Maratyszcza Thanks for your information! I pulled the latest Tensorflow which has a newer XNNPACK with the patch you mentioned previously. It can finish compilation without errors.
