### ISSUE TITLE
error with functools32

### ISSUE THREAD

**Issue by lhy2749** [tensorflow/tensorflow#54439]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.15
- Python version:3.6.4
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.3.0
- CUDA/cuDNN version:none
- GPU model and memory:cpu-only

**Describe the problem**
I compiled the file `tensorflow-1.15.5-cp36-cp36m-linux_x86_64.whl` by using the tensorflw@r1.15, when i use `pip install tensorflow-1.15.5-cp36-cp36m-linux_x86_64.whl`,  there is a problem:

Downloading functools32-3.2.3-2.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/envs/tf_test/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zi7j89fx/functools32_fe3235542fe548578e556e08b3efc74b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zi7j89fx/functools32_fe3235542fe548578e556e08b3efc74b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-oymtginn
         cwd: /tmp/pip-install-zi7j89fx/functools32_fe3235542fe548578e556e08b3efc74b/
    Complete output (1 lines):
    This backport is for Python 2.7 only.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@lhy2749 ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to latest stable version 2.8 and let us know if you are facing same issue.
