### ISSUE TITLE
Can't install Tensorflow 2.x.x on Jetson boards with pip

### ISSUE THREAD

**Issue by LITDataScience** [tensorflow/tensorflow#54446]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetson - Jp 4.6
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.x.x
- Python version: 3.6/3.8
- Installed using virtualenv? pip? conda?: Pip/virtualenv
- CUDA/cuDNN version: 11.3
- GPU model and memory: Jetson AGX/ 32GB

**Describe the problem**
Cannot install Tensorflow on Jetson boards with ease of pip.

pip install tensorflow

**Comment by mohantym** [comment]
Hi @LITDataScience ! Did you try in a virtual environment after installing dependencies as this [thread](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html) suggests? Thanks!

**Comment by sampathweb** [comment]
@LITDataScience - As suggested by @mohantym , please use the Nvidia Link to install TF on Jetson (https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html).  Nvidia has built a wheel file to work specifically for Jetson.  So please use that wheel file link in the docs to install in Jetson.  ARM builds can't be installed with `pip install tensorflow`.
