### ISSUE TITLE
Save and load a model with PReLU activation results in error

### ISSUE THREAD

**Issue by trungnt13** [tensorflow/tensorflow#54445]
There is very specific scenarios when PReLU activation failed during `tf.keras.models.load`

- Create and save the model via keras.Model.save
- Load the model, make modifications to the Layer that including the PReLU activation
- Save the modified Model and load it again, PReLU layer failed during `build` when initializing the `alpha` parameters

Note: this issue disappear when I subclassing the `PReLU` that is replacing all `PReLU` with `ParamReLU`
or specify the `share_axes` argument also solve the problem

```python
class ParamReLU(PReLU):
    ...
```

---

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**, **Windows 10**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.6.0, 2.6.1, 2.7.0, 2.8.0**; **v2.8.0-rc1-32-g3f878cff5b6 2.8.0**
- Python version: **3.7.10**
- CUDA/cuDNN version: **11.2/8.10**
- GPU model and memory: **RTX 3080 / 10GB**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): **no**
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, Input, PReLU

x = Input((1, 1, 1))
y = Conv2D(8, 1)(x)
y = PReLU()(y)
y = Conv2D(40, 1)(y)
model = Model(x, y)

model.save('/tmp/model_abc')
model_new = tf.keras.models.load_model('/tmp/model_abc')
layer1 = model_new.get_layer('conv2d')
layer2 = model_new.get_layer('p_re_lu')
layer3 = model_new.get_layer('conv2d_1')

# === prune the last filter of layer1
cfg = layer1.get_config()
cfg['filters'] = 7
layer1_copy = layer1.__class__.from_config(cfg)
layer1_copy.build((None, 1, 1, 1))
layer1_copy.set_weights([layer1.kernel.numpy()[..., :7],
                         layer1.bias.numpy()[:7]])
y = layer1_copy(model_new.inputs[0])

# remove the last alpha of PReLU
layer2_copy = layer2.__class__.from_config(layer2.get_config())
layer2_copy.build(y.shape)
layer2_copy.set_weights([layer2.alpha.numpy()[..., :7]])
y = layer2_copy(y)

# remove 1 input filter layer3
cfg = layer3.get_config()
layer3_copy = layer3.__class__.from_config(cfg)
layer3_copy.build(y.shape)
layer3_copy.set_weights([layer3.kernel.numpy()[..., :7, :],
                         layer3.bias.numpy()])
y = layer3_copy(y)
model_prune = Model(model_new.inputs, y)

# everything OK here
print(model_prune.summary())

# === error happening here when we save and load the model again
model_prune.save('/tmp/model_abc_prune')
model_prune_new = tf.keras.models.load_model('/tmp/model_abc_prune')
```

**Other info / logs** 
```
Traceback (most recent call last):
  File "...", line 44, in <module>
    model_prune_new = tf.keras.models.load_model('/tmp/model_abc_prune')
  File "/home/trung/miniconda3/envs/denoise/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/trung/miniconda3/envs/denoise/lib/python3.7/site-packages/keras/initializers/initializers_v2.py", line 145, in __call__
    return tf.zeros(shape, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

**Comment by chunduriv** [comment]
@trungnt13,

This issue is related to Keras. Please post this on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more please check [here](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999). Thanks!

**Comment by trungnt13** [comment]
Thanks, I have reposted the issue to Keras here
https://github.com/keras-team/keras/issues/16116
