### ISSUE TITLE
AttributeError:  module 'tensorflow.contrib.learn.python.learn.datasets.base' has no attribute 'load_csv'

### ISSUE THREAD

**Issue by fansongfs** [tensorflow/tensorflow#5444]
I had install tensorflow in ubuntu with Anaconda install. I try to run neural network sample but get 
AttributeError:  module 'tensorflow.contrib.learn.python.learn.datasets.base' has no attribute 'load_csv' error.
Any clue?

Thanks,

**Comment by aselle** [comment]
I apologize, but it is impossible to help you when you do not provide detailed information about what you are running and what you are running it on. Please provide the info requested on the new git hub issue template and create a new issue.  Include exactly what commands you are running to reproduce your problem. Thanks.

**Comment by gueshD** [comment]
I was trying to run a code "import tensorflow as tf
import numpy as np

training_set = tf.contrib.learn.datasets.base.load_csv(filename="train.csv", target_dtype=np.int)

test_set =     tf.contrib.learn.datasets.base.load_csv(filename="test.csv",  target_dtype=np.int)

classifier = tf.contrib.learn.DNNClassifier(hidden_units=[12, 12, 12], n_classes=2)

# note: to set L1 or L2 regularization (for overfitting), learning rate, etc.
#       then use DNNClassifier options described in:
# https://www.tensorflow.org/versions/r0.9/api_docs/python/contrib.learn.html#DNNClassifier

classifier.fit(x=training_set.data, y=training_set.target, steps=500)

accuracy = classifier.evaluate(x=test_set.data, y=test_set.target)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy))

no_and_yes_samples = np.array(
        [[4,1,1,3,2,1,3,1,1], [3,7,7,4,4,9,4,8,1]], dtype=np.int)
y = classifier.predict(no_and_yes_samples)
print ('Predictions: {}'.format(str(y)))" which is publicly available on github and I get an error of type"AttributeError: module 'tensorflow.contrib.learn.python.learn.datasets.base' has no attribute 'load_csv'"

**Comment by 952599993** [comment]
Dear fansongfs,

How is it going? I also met a similar problem. Would you please show your solutions?

Best regards.
