### ISSUE TITLE
"ValueError: Setting hub.KerasLayer.trainable = True is unsupported when loading from the TF1 Hub format." when running Object Detection with TensorFlow Lite Model Maker tutorial on Windows 10. Tutorial ran well on Mac book

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tensorflow#54440]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.8.0
- Python version:3.9.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA GeForce MX150  16GB Ram

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Encountered 

    ValueError: Setting hub.KerasLayer.trainable = True is unsupported when loading from the TF1 Hub format.

When running below tutorial for training custom model for object detection using Tensorflow Lite Model Maker

https://www.tensorflow.org/lite/tutorials/model_maker_object_detection

**Describe the expected behavior**

custom model to be trained.

Similar set up is working in Mac book. Please advise on how to get the custom model training working on Windows 10 machine.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

On Windows 10 machine, download the Anaconda installer. Follow default settings to install Anaconda

Open Anaconda prompt and create environment test by

conda create -name test python=3.9

activate environment by

(base) C:\Users\dev>conda activate test

(test) C:\Users\dev>

Install tflite-model-maker by 

(test) C:\Users\dev>pip install tflite-model-maker

after installation completed, enter python prompt

(test) C:\Users\dev>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

execute the instructions adapted from 

https://www.tensorflow.org/lite/tutorials/model_maker_object_detection

(test) C:\Users\dev>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import os
>>> from tflite_model_maker.config import QuantizationConfig
>>> from tflite_model_maker.config import ExportFormat
>>> from tflite_model_maker import model_spec
>>> from tflite_model_maker import object_detector
>>> import tensorflow as tf
>>> assert tf.__version__.startswith('2')
>>> spec = model_spec.get('efficientdet_lite0')
2022-02-18 12:41:00.098002: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-18 12:41:01.311912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1342 MB memory:  -> device: 0, name: NVIDIA GeForce MX150, pci bus id: 0000:01:00.0, compute capability: 6.1
>>> train_data, validation_data, test_data = object_detector.DataLoader.from_csv('C:/Users/dev/Documents/achiever/tensorFlow/sub_salads.csv')
INFO:tensorflow:Cache will be stored in C:\Users\dev\AppData\Local\Temp\tmpafosi8_7 with prefix filename train_47472d894c199311b64931ed1b6dae18. Cache_prefix is C:\Users\dev\AppData\Local\Temp\tmpafosi8_7\train_47472d894c199311b64931ed1b6dae18
INFO:tensorflow:Cache will be stored in C:\Users\dev\AppData\Local\Temp\tmpv_nxxrzt with prefix filename val_47472d894c199311b64931ed1b6dae18. Cache_prefix is C:\Users\dev\AppData\Local\Temp\tmpv_nxxrzt\val_47472d894c199311b64931ed1b6dae18
INFO:tensorflow:Cache will be stored in C:\Users\dev\AppData\Local\Temp\tmpdfguu885 with prefix filename test_47472d894c199311b64931ed1b6dae18. Cache_prefix is C:\Users\dev\AppData\Local\Temp\tmpdfguu885\test_47472d894c199311b64931ed1b6dae18
INFO:tensorflow:On image 0
INFO:tensorflow:On image 0
INFO:tensorflow:On image 0
>>> model = object_detector.create(train_data, model_spec=spec, batch_size=8, train_whole_model=True, validation_data=validation_data)
INFO:tensorflow:Retraining the models...
WARNING:tensorflow:The size of the validation_data (3) is smaller than batch_size (8). Ignore the validation_data.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\object_detector.py", line 260, in create
    object_detector.train(train_data, validation_data, epochs, batch_size)
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\object_detector.py", line 123, in train
    return self.model_spec.train(self.model, train_ds, steps_per_epoch,
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_examples\lite\model_maker\core\task\model_spec\object_detector_spec.py", line 264, in train
    train.setup_model(model, config)
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_examples\lite\model_maker\third_party\efficientdet\keras\train.py", line 113, in setup_model
    model.build((None, *config.image_size, 3))
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\keras\engine\training.py", line 440, in build
    self.call(x, **kwargs)
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_examples\lite\model_maker\third_party\efficientdet\keras\train_lib.py", line 885, in call
    cls_outputs, box_outputs = self.base_model(inputs, training=training)
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: Exception encountered when calling layer "keras_layer" (type KerasLayer).

in user code:

    File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_hub\keras_layer.py", line 213, in call  *
        self._check_trainability()
    File "C:\Users\dev\anaconda3\envs\test\lib\site-packages\tensorflow_hub\keras_layer.py", line 272, in _check_trainability  *
        raise ValueError(

    ValueError: Setting hub.KerasLayer.trainable = True is unsupported when loading from the TF1 Hub format.

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 320, 320, 3), dtype=float32)
  • training=False

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Related to issue:

https://github.com/tensorflow/hub/issues/841

I have since uninstall Python 3.8.6, Anaconda3 and reinstalled Anaconda3. I tried running the above in Anaconda environment with python 3.9 installed. However, the error persisted.

I repeat the same setup on my Mac book and it worked. Thus, this looks to be a Windows 10 specific issue.

attached is Anaconda exported environment from windows:

[winEnv.yml.txt](https://github.com/tensorflow/tensorflow/files/8094267/winEnv.yml.txt)

and the working Anaconda exported environment from Mac Book

[mac.yml.txt](https://github.com/tensorflow/tensorflow/files/8094270/mac.yml.txt)

**Comment by chunduriv** [comment]
@FlyWong,
In order to expedite the trouble-shooting process, please provide above mentioned custom model and dataset to reproduce the issue. Thanks!

**Comment by FlyWong** [comment]
Hi Chunduriv, I got the issue just by following this tutorial. So you can use the code and dataset to reproduce the issue.
https://www.tensorflow.org/lite/tutorials/model_maker_object_detection
