### ISSUE TITLE
Unrecognized term used by the documentation of the class "tensorflow.compat.v1.variable_scope".

### ISSUE THREAD

**Issue by A1795066711** [tensorflow/tensorflow#54449]
The paragraph following:

                      "A note about using variable scopes in multi-threaded environment: Variable
                        scopes are thread local, so one thread will not see another thread's current
                        scope. Also, when using `default_name`, unique scopes names are also generated
                        only on a per thread basis. If the same name was used within a different
                        thread, that doesn't prevent a new thread from creating the same scope.
                        However, the underlying variable store is shared across threads (within the
                        same graph). As such, if another thread tries to create a new variable with
                        the same name as a variable created by a previous thread, it will fail unless
                        reuse is True."

which is found in both the documentation (https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope) and the source code (https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/python/ops/variable_scope.py#L2144-L2579).

My question(s):

For the last sentence of this paragraph, what is the point it talks about? 
It seems to talk about a condition when two threads cause an error since one tries to have a variable of the same name as the other, previous one, although I am not sure what is the mentioned 'underlying variable store' referring to.
But after some tests, I haven't found the condition yet, while it is always the case that each thread has a variable scope separated from others.
Does anyone have learned about the documented condition or the term 'underlying variable store'?

Additional Information:

Here are codes used for two tests, all run without an error found. (With Python 3.7.12, Tensorflow 1.15.0 as the environment)

1. Test One

```
      import tensorflow as tf
      
      def F():
        T = tf.get_variable( 'Mark' , [1,2] )
        print( T.name )
      
      import threading
      t1 = threading.Thread( target=F , args=() )
      t2 = threading.Thread( target=F , args=() )
      
      t1.start()
      t2.start()
      t1.join()
      t2.join()
```

2. Test Two
```
      import tensorflow as tf
      
      def F(s):
        with tf.variable_scope(s,reuse=tf.AUTO_REUSE) as scope:
          T = tf.get_variable( 'Mark' , [1,2] )
          print( T.name )
      
      import threading
      with tf.variable_scope('s',reuse=tf.AUTO_REUSE):
        s = tf.get_variable_scope()
        T = tf.get_variable( 'Mark' , [1,2] )
        t1 = threading.Thread( target=F , args=(s,) )
        t2 = threading.Thread( target=F , args=(s,) )
      
      t1.start()
      t2.start()
      t1.join()
      t2.join()
```

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/e6f1b3a32474af619a01b566b44fc6cf/github_54449.ipynb#scrollTo=xpjbF1-rnslQ),[2.8](https://colab.sandbox.google.com/gist/mohantym/18ea6783dcfc9ea6eacfd692c0ffdaf8/github_54449.ipynb) and [nightly](https://colab.sandbox.google.com/gist/mohantym/ab736270a9a85dde8f9a36297ab3d45a/github_54449.ipynb#scrollTo=-bXGE65_e5EB)

**Comment by sachinprasadhs** [comment]
Variable store is nothing but the thread local store for the current variable scope and scope counts.
variable store will be maintained on a thread level so that it will not create any problem during multithread environments.

In your code when you change the `reuse=None`( which is equivalent to reuse = False) instead of `reuse=tf.AUTO_REUSE`, you will get the expected error outcome, if you want your variable store's scope to be shared to other threads  then you can use `reuse = True`.

Below is the code with reuse=None which does not allow variable scope to be shared to other thread.

```
%tensorflow_version 1.x
import tensorflow as tf

def F(s):
  with tf.variable_scope(s,reuse=None) as scope:
    T = tf.get_variable( 'Mark' , [1,2] )
    print( T.name )

import threading
with tf.variable_scope('s',reuse=None):
  s = tf.get_variable_scope()
  T = tf.get_variable( 'Mark' , [1,2] )
  t1 = threading.Thread( target=F , args=(s,) )
  t2 = threading.Thread( target=F , args=(s,) )

t1.start()
t2.start()
t1.join()
t2.join()
```

**Comment by A1795066711** [comment]
@sachinprasadhs 

Thank you very much for your answer!

For your answer, I have two more questions if you'd like to have a look at.

(1) Is the variable store mentioned in your answer the variable '_var_store' (should be initialized [here](https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/variable_scope.py#L1994)) or the variable '_var_scope_store' (should be initialized [here](https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/variable_scope.py#L1995)) inside the object of the class _pure_variable_scope (should be defined [here](https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/variable_scope.py#L1942)) which could be found after the scope (variable_scope(should be defined [here](https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/variable_scope.py#L2144))) containing, or ready to initialize it, is entered?

(2) Is the mechanism of deciding to reuse a variable in a variable scope or not, is only based on the value of the REUSE set to the scope as well as the existence and the content of such store?

**Comment by sachinprasadhs** [comment]
`_var_scope_store` is a thread local store for the current variable scope and scope counts, see [here](https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/variable_scope.py#L1431).
In multithread environment by default the variable scope mechanism will be in thread local, when the reuse option is set to `True`, then you can create the variable with the same name as the another thread.
