### ISSUE TITLE
StringLookup fails as first layer in a Sequential model in TF 2.8.0

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#54459]
**System information**

<details>

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04 (Google Colab)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary (preinstalled on Google Colab)**
- TensorFlow version (use command below): **v2.8.0-0-g3f878cff5b6 2.8.0**
- Python version: **3.7.12**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

</details>

**Describe the current behavior**

Using a `tf.keras.layers.StringLookup` layer as the first layer in a `Sequential` model raises an exception when calling the model: `UnimplementedError: Exception encountered when calling layer "sequential" (type Sequential). Cast string to int64 is not supported [Op:Cast]` (see full stacktrace below).

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

cat = ["Paris", "Singapore", "Auckland"]
str_lookup_layer = tf.keras.layers.StringLookup()
str_lookup_layer.adapt(cat)
lookup_and_embed = tf.keras.Sequential([
    str_lookup_layer,
    tf.keras.layers.Embedding(input_dim=str_lookup_layer.vocabulary_size(),
                              output_dim=2)
])
lookup_and_embed(tf.constant([["Paris"], ["Singapore"], ["Auckland"]]))  # ERROR!
```

This code is available in this [gist](https://colab.research.google.com/gist/ageron/4ba943dac246ade26699b7fe8fa38fae/tensorflow-issue-54459.ipynb).

**Describe the expected behavior**
This should work like it did in TensorFlow 2.7.1, I believe it's a regression. It should output something like this:

```
<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.02887753, -0.01268407],
       [ 0.04601531, -0.02668235],
       [ 0.03409723, -0.03205377]], dtype=float32)>
```

**Other info / logs**

Instead, it raises this exception. Full stacktrace:

<details>

```stacktrace
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
[<ipython-input-2-ee4b4b94a15e>](https://localhost:8080/#) in <module>()
      7                               output_dim=2)
      8 ])
----> 9 lookup_and_embed(tf.constant([["Paris"], ["Singapore"], ["Auckland"]]))

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

UnimplementedError: Exception encountered when calling layer "sequential" (type Sequential).

Cast string to int64 is not supported [Op:Cast]

Call arguments received:
  • inputs=tf.Tensor(shape=(3, 1), dtype=string)
  • training=None
  • mask=None
```

</details>

**Comment by mohantym** [comment]
Hi @ageron !
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by ageron** [comment]
Oh right, will do, thanks.
