### ISSUE TITLE
tf.gather doesn't run on GPU for DT_INT32

### ISSUE THREAD

**Issue by chhwang** [tensorflow/tensorflow#5445]
As I know, `tf.gather` should be able to operate on a GPU device according to this issue: #2502

I installed the latest version of `r0.11` branch (commit hash written below) and ran the following code:
```python
    import tensorflow as tf
    x = tf.constant([1,2,3,4,5])
    idx = tf.constant([0,1,2,3,4])
    with tf.device('/gpu:0'):
        y = tf.gather(x, idx)
    sess = tf.Session()
    print(sess.run(y))
```

and it returned the following error message:

    tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'Gather': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
         [[Node: Gather = Gather[Tindices=DT_INT32, Tparams=DT_INT32, validate_indices=true, _device="/device:GPU:0"](Const, Const_1)]]

If I change `'/gpu:0'` into `'/cpu:0'`, it works well. Can you give me any hint on this?

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: CUDA 8.0 and cuDNN 5.1.5

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
7197421df430a51383fba7c4e7ff9a3fd7795535
2. The output of `bazel version`
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

**Comment by MInner** [comment]
try 

```
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True))
```

Not sure why, but hard placement does not always seem to work for me too, but `soft_placement` always works.

**Comment by chhwang** [comment]
@MInner Thank you for your comment, but I don't want to use soft placement. I want it actually runs on GPU.

**Comment by vrv** [comment]
A hint is that the error message is telling you what datatypes are being requested but are not registered for GPU.  In particular, the kernel it is looking for is Gather with datatypes DT_INT32, which are not currently registered on GPU (only float).  

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_functor_gpu.cu.cc registers gather for some types (https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/framework/register_types.h#L163), but not DT_INT32.  You could try registering the kernel for DT_INT32 if you really wanted.

**Comment by chhwang** [comment]
@vrv Thank you very much! Let me close this issue because my problem is solved.
Nevertheless, I think it would be better to make the API document clear about currently supported types and devices...
