### ISSUE TITLE
Tensorflow import error, undefined symbol

### ISSUE THREAD

**Issue by bunbun205** [tensorflow/tensorflow#54469]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Arch
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Arch community repository
- TensorFlow version: 2.8.0
- Python version: 3.10
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 11.1.0
- CUDA/cuDNN version: 11.5
- GPU model and memory: Nvidia GTX GeForce 1050ti 4GB

**Describe the problem**
import tensorflow leads to the following import error:

```
>>> import tensorflw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflw'
>>> import tensorflow
Traceback (most recent call last):
  File "/home/beany/.local/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 60, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/beany/.local/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/beany/.local/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/beany/.local/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/beany/.local/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 75, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/beany/.local/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 60, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/beany/.local/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb


Failed to load the native TensorFlow runtime.

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

>>> import tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by chunduriv** [comment]
@bunbun205,

For `Tensorflow 2.8`, can you please try `CUDA` and `cuDNN` versions as shown below 

![image](https://user-images.githubusercontent.com/74177924/154927657-6e9d354d-8363-45a0-b4e8-63f282e89b21.png)

Thanks!

**Comment by phillip9077** [comment]
> @bunbun205,
> 
> For `Tensorflow 2.8`, can you please try `CUDA` and `cuDNN` versions as shown below
> 
> ![image](https://user-images.githubusercontent.com/74177924/154927657-6e9d354d-8363-45a0-b4e8-63f282e89b21.png)
> 
> For more details, please refer tested build configurations [here](https://github.com/tensorflow/docs/blob/cbaa96238c823b39e4433c843823895cef903343/site/en/install/source.md#gpu).Thanks!

How do you "try" this?
