### ISSUE TITLE
RNN with nested inputs

### ISSUE THREAD

**Issue by claCase** [tensorflow/tensorflow#54464]
I would like to implement a recurrent GAT model which takes two inputs of shape: [(batch_size, time, N, F), [batch_size,  time, N, N)].  The hidden size should have shape (batch_size, N, hidden_feature).  I've structured the class as follows:
```python
class NestedCell(keras.layers.Layer):
    def __init__(self, nodes, features, channels, attention_heads, **kwargs):
        self.tot_nodes = nodes
        self.nodes_features = features
        self.hidden_size = channels * attention_heads
        self.state_size = [tf.TensorShape([self.tot_nodes, self.hidden_size])]
        self.output_size = [tf.TensorShape([self.tot_nodes, self.tot_nodes]),
                            tf.TensorShape([self.tot_nodes, self.hidden_size])]
        super(NestedCell, self).__init__(**kwargs)
```
The problem is that when I feed a list of two inputs:
```python
N = 10
f = 5
cell = NestedCell(N, f, 10,10)
i1 = tf.keras.Input((None, N, f))
i2 = tf.keras.Input((None, N, N))
rnn = tf.keras.layers.RNN(cell)
o = rnn([i1, i2])
```
I get the error that the initial state is not compatible with the cell.state_size:
```
ValueError: An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=ListWrapper([InputSpec(shape=(None, None, 10, 10), ndim=4)]); however `cell.state_size` is [TensorShape([10, 100])]
```
How should I structure the class to accept such input shape?

**Comment by chunduriv** [comment]
@claCase,

This issue is related to Keras. Please post this on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more please check [here](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999). Thanks!

**Comment by chunduriv** [comment]
@claCase, Can you please close this issue, since it is tracked https://github.com/keras-team/keras/issues/16103. Thanks!
