### ISSUE TITLE
`in` operation in TF takes incredibly long time

### ISSUE THREAD

**Issue by charlielam0615** [tensorflow/tensorflow#54461]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.9.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.2
- GPU model and memory: RTX A6000

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`in` operation in tensors took an unreasonably amount of time

**Describe the expected behavior**
should be very fast to execute

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
import numpy as np
import time

a = tf.range(256)
start = time.time()
res = tf.constant([i in a for i in range(256)])
print("Using tf: took", time.time()-start, "seconds.")

a_ = a.numpy()
start = time.time()
res = tf.constant([i in a_ for i in range(256)])
print("Using numpy: took", time.time()-start, "seconds.")
```

In my own machine, this gives
```
Using tf: took 3.605224847793579 seconds.
Using numpy: took 0.0006427764892578125 seconds
```

Well, it's pretty obvious something is wrong when using `in` operations with tensors.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Cheril311** [comment]
@charlielam0615 can you please check the type of the variable res and tell here?

**Comment by charlielam0615** [comment]
`print(res.dtype)` gives `<dtype: 'bool'>`

**Comment by chunduriv** [comment]
I am able to reproduce the issue in `TF2.8` and `tf-nightly(2.9.0-dev20220228)`. Please find the [gist](https://colab.research.google.com/gist/chunduriv/5068c1273eed5f1297ce7dea1f168bbb/54461.ipynb) here for reference.Thanks!
