### ISSUE TITLE
Bus error in quantized network on Android

### ISSUE THREAD

**Issue by JosiahKane** [tensorflow/tensorflow#5446]
We have a tensorflow image processing network, which executes fine on osX, iOS and Android. Now that quantization has been pulled into core, we wanted to use it to optimize our install size on phones.

When we run the quantization process there are as expected small differences in the output on the Mac, but nothing that seems unreasonable. Further, when the quantized network is run on iOS it gives a warning that zero is outside the quantization range and it has to revert to a slow version to handle convolution padding. However it runs fine and the numbers are plausible.

On Android, however, and running with precisely the same code that worked perfectly with the unquantized version, it completely breaks. On one phone it gives outputs on the order of 1000 where we expect values on the order of 1. On another, probably the more reasonable, phone it just dies following a bus error. This has been true on the latest commits sampled over the last several days.

If it's relevant, the network was converted from a caffe predecessor using this tool: https://github.com/ethereon/caffe-tensorflow
Regrettably I'm unable to upload the source code or network in question.

**Comment by aselle** [comment]
@petewarden, do you have any thoughts on this or who can diagnose this?

**Comment by petewarden** [comment]
I just hit a similar "Bus error" problem with another model, so I'll take on debugging this.

**Comment by maciekcc** [comment]
Hi there, I'm helping Pete with this bug. As a quick solution you can disable the new codepath, call:

tensorflow::meta::SetEnabled(false);

this will revert to Eigen.

**Comment by maciekcc** [comment]
Or even better try building with: TENSORFLOW_DISABLE_META defined

**Comment by aselle** [comment]
@petewarden, @maciekcc, was there any resolution on this bug? Is it still reproducible and relevant?

**Comment by maciekcc** [comment]
IIRC this bug has been fixed in: https://github.com/tensorflow/tensorflow/commit/38aec869681e0ac964e33bf44aef57016c5960c5
