### ISSUE TITLE
An op outside of the function building code is being passed a "Graph" tensor

### ISSUE THREAD

**Issue by pnuzyf** [tensorflow/tensorflow#54465]
I am using tf 2.3.0, and did not explicitly  set the eager mode。

I defined a memory network layer, and call it from another layer。 It succeeded during the training step. However, I got the following error during the evaluation step。

Traceback (most recent call last):
  File "/Users/fabriszhou/PycharmProjects/tf-model/test/msmt/test_memory.py", line 94, in <module>
    mymodel = model.get_train_model()
  File "/Users/fabriszhou/PycharmProjects/tf-model/models/msmt.py", line 374, in get_train_model
    long_cluster = self.memory.predict_process([query_emb, long_emb, isActive_vals])  # 拿到长期的兴趣表征
  File "/Users/fabriszhou/PycharmProjects/tf-model/pkgs/tf/extend_layers.py", line 2499, in predict_process
    read_attention = compute_cosine_similarity(read_query, self.key_memory, temperature=self.temperature)
  File "/Users/fabriszhou/PycharmProjects/tf-model/pkgs/tf/extend_layers.py", line 2322, in compute_cosine_similarity
    normed_memory = tf.nn.l2_normalize(memory, axis=1)  # [n_memory, dim]
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py", line 666, in l2_normalize_v2
    square_sum = math_ops.reduce_sum(math_ops.square(x), axis, keepdims=True)
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10309, in square
    x, name=name, ctx=_ctx)
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10347, in square_eager_fallback
    ctx=ctx, name=name)
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: add:0

Here is my source code。

def compute_cosine_similarity(query, memory, temperature=0.1):
    """
    Compute cosine similarity between query and memory.

    Args:
        query: (batch_size, embedding_dim)
        memory: (n_memory, embedding_dim)
        temperature: hyper-parameter to control the final probabilities of softmax.

    Returns:
        Attention in the shape of (batch_size, n_memory)
    """

    normed_query = tf.nn.l2_normalize(query, axis=1)  # [batch, dim]
    query = tf.expand_dims(normed_query, axis=1)  # [batch, 1, dim]

    normed_memory = tf.nn.l2_normalize(memory, axis=1)  # [n_memory, dim]
    memory = tf.expand_dims(normed_memory, axis=0)  # [1, n_memory, dim]

    similarity = tf.reduce_sum(tf.multiply(query, memory), axis=2)  # [batch, n_memory]
    similarity = tf.nn.softmax(similarity / temperature, axis=1)  # [batch, n_memory]

    return similarity

class MemoryLayer(tf.keras.layers.Layer):
    def __init__(self, controller_layers, controller_hidden_act='relu', controller_output_act=None, n_clusters=100, key_dims=8, long_dims=8, short_dims=8, temperature=0.1, alpha=0.1, is_short=False, name="memory_layer", **kwargs):
        super(MemoryLayer, self).__init__(name=name, trainable=True, **kwargs)
        self.controller_layers = controller_layers
        self.controller_hidden_act = controller_hidden_act
        self.controller_output_act = controller_output_act
        self.n_clusters = n_clusters
        self.key_dims = key_dims
        self.long_dims = long_dims
        self.short_dims = short_dims
        self.temperature = temperature
        self.alpha = alpha
        self.is_short = is_short

        self.key_memory = tf.compat.v1.get_variable(
            f"{self.name}_key_memory",
            shape=[self.n_clusters, self.key_dims],
            initializer=tf.compat.v1.glorot_normal_initializer())
        # self.key_memory = self.add_weight(f"{self.name}_key_memory",
        #                       shape=(self.n_clusters, self.key_dims),
        #                       initializer=tf.keras.initializers.GlorotNormal(),
        #                       trainable=False)

        #
        # self.long_memory = self.add_weight(f"{self.name}_long_memory",
        #                       shape=(self.n_clusters, self.long_dims),
        #                       initializer=tf.keras.initializers.GlorotNormal(),
        #                       trainable=False)

        self.long_memory = tf.compat.v1.get_variable(
            f"{self.name}_long_memory",
            shape=[self.n_clusters, self.key_dims],
            initializer=tf.compat.v1.glorot_normal_initializer())

        if is_short:
            self.short_memory =  self.add_weight(f"{self.name}_short_memory",
                              shape=(self.n_clusters, self.long_dims),
                              initializer=tf.keras.initializers.GlorotNormal(),
                              trainable=False)

            self.short_erase_layer = DNNLayer([self.short_dims], 'sigmoid',
                                             name=f"{self.name}_short_erase_layer")  # short earse layer
            self.short_add_layer = DNNLayer([self.short_dims], 'tanh', name=f"{self.name}_short_add_layer")  #short add layer

        self.write_controller = DNNLayer(controller_layers, controller_hidden_act, controller_output_act) #write controller

        self.read_controller = DNNLayer(controller_layers, controller_hidden_act, controller_output_act) #read controller

        self.key_erase_layer = DNNLayer([self.key_dims], 'sigmoid', name=f"{self.name}_key_erase_layer") #key erase layer
        self.key_add_layer = DNNLayer([self.key_dims], 'tanh', name=f"{self.name}_key_add_layer") #key add layer

        self.long_erase_layer = DNNLayer([self.long_dims], 'sigmoid', name=f"{self.name}_long_erase_layer")  #long erase layer
        self.long_add_layer = DNNLayer([self.long_dims], 'tanh', name=f"{self.name}_long_add_layer")  # long add layer

        # self.read_sim_layer = SimLayer()
        # self.write_sim_layer = SimLayer()

    @tf.function
    def call(self, inputs, training=None, **kwargs):
        attr_emb = inputs[0]  # [batch_size, attr_emb]
        long_emb = inputs[1] #[batch, long_dims] embedding
        isActive = inputs[2]  # [batch_size, 1]

        active_status = tf.cast(tf.transpose(isActive, perm=[1,0]), dtype='float32')

        # denominator = tf.math.count_nonzero(isActive) 

        #＞0才更新
        if training:
            #write memory
            #[batch_size, key_dims]
            write_query = self.write_controller(attr_emb) 

            write_query_add = tf.reduce_mean(write_query, axis=0, keepdims=True)

            #[batch, n_clusters]
            # write_attention = compute_cosine_similarity(write_query, self.key_memory, temperature=self.temperature)

            # write_attention = self.write_sim_layer([write_query, self.key_memory], temperature=self.temperature)
            #
            # #[1, n_clusters]
            # write_memory_attention = tf.matmul(active_status, write_attention) / tf.cast(1024, dtype=tf.float32)
            # write_memory_attention = tf.matmul(active_status, write_attention) / tf.cast(1024, dtype=tf.float32)

            #[n_clusters, 1]
            # write_memory_attention = tf.transpose(write_memory_attention, perm=[1, 0])

            #write key memory
            # key_erase_vector = self.key_erase_layer(write_query) #[batch, key_dims]
            # key_erase_vector = tf.matmul(active_status, key_erase_vector) / tf.cast(denominator, dtype=tf.float32) #[1,key_dims]
            #
            # key_add_vector = tf.reduce_mean(self.key_add_layer(write_query), axis=0, keepdims=True)#[batch, key_dims]
            # key_add_vector = tf.matmul(active_status, key_add_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,key_dims]

            self.key_memory = self.key_memory \
                               + write_query_add

            # * (1. - self.alpha * tf.matmul(write_memory_attention, key_erase_vector)) \

            #write long_memory
            # long_erase_vector = self.long_erase_layer(long_emb)  # [batch, long_dims]
            # long_erase_vector = tf.matmul(active_status, long_erase_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,long_dims]
            #
            # long_add_vector = self.long_add_layer(long_emb)  # [batch, long_dims]
            # long_add_vector = tf.matmul(active_status, long_add_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,key_dims]

            self.long_memory = self.long_memory
                              # * (1. - self.alpha * tf.matmul(write_memory_attention, long_erase_vector)) \
                              # + self.alpha * tf.matmul(write_memory_attention, long_add_vector)

        #read memory
        #[batch, key_dims]
        read_query = self.read_controller(tf.stop_gradient(attr_emb))

         #[batch, n_clusters]
        read_attention = compute_cosine_similarity(read_query, self.key_memory, temperature=self.temperature)

        # read_attention = self.read_sim_layer([read_query, self.key_memory], temperature=self.temperature)

        long_cluster_emb = tf.matmul(read_attention, self.long_memory) #[batch, long_dims] 长期兴趣表征

        return long_cluster_emb

    def predict_process(self, inputs):
        read_query = self.read_controller(inputs[0])
        # read_attention = self.read_sim_layer([read_query, self.key_memory], temperature=self.temperature)
        read_attention = compute_cosine_similarity(read_query, self.key_memory, temperature=self.temperature)

        long_cluster_emb = tf.matmul(read_attention, self.long_memory)  # [batch, long_dims] 长期兴趣表征

        return long_cluster_emb

    def get_config(self):
        config = super(MemoryLayer, self).get_config()
        config.update({
            'controller_layers': self.controller_layers,
            'controller_hidden_act': self.controller_hidden_act,
            'controller_output_act': self.controller_output_act,
            'n_clusters': self.n_clusters,
            'key_dims': self.key_dims,
            'long_dims': self.long_dims,
            'short_dims': self.short_dims,
            'temperature': self.temperature,
            'alpha': self.alpha,
            'is_short': self.is_short,
            'name': self.name
        })
        return config

    @classmethod
    def from_config(cls, config):
        return cls(**config)

**Comment by mohantym** [comment]
Hi @pnuzyf ! Could you provide the standalone code as Colab gist ?

**Comment by pnuzyf** [comment]
> 

thanks for  your prompt response. since we change a lot for the input layer and embedding layer, I should provide all the source code. Is that ok?

**Comment by mohantym** [comment]
Ok @pnuzyf ! Please share as Colab gist with source code. Thanks!

**Comment by pnuzyf** [comment]
you can clone the source code from https://github.com/pnuzyf/tf-model.git, the test code locates in test/msmt/test_memory.py if I set "tf.compat.v1.disable_eager_execution()", anthor error comes up.

**Comment by pnuzyf** [comment]
hello, could you run the test code?

**Comment by mohantym** [comment]
Hi! @pnuzyf ! I was getting import error at line mentioned at "pkgs" . Could you please attach a requirement.txt file in your source code to install all dependencies?

**Comment by pnuzyf** [comment]
really？ could you show me the error？ I think there is nothing special dependency, just follow the hint when you run the code.

**Comment by pnuzyf** [comment]
in test_memory.py, you should change the argument of custom_layer_file_path， and  the correponding config_file, export_path, pack_path and data_path etc.

model = MsMtModel(input, num_scenarios, moe_num_experts, moe_expert_layers, ordered_task_names, layer_number, ple_dict, tower_dict, task_output_act,
                     tower_dependencies_dict={},
                     custom_layer_file_path="/Users/fabriszhou/PycharmProjects/tf-model/test/msmt/custom/custom_layers.py", is_parallel=False, short_cut=True,
                     cut_tower=cut_tower_dict, is_memory=True, controller_layers=controller_layers, controller_output_act=controller_output_act, key_dims=key_dims,
                     long_dims=long_dims,
                     name='msmt')

**Comment by mohantym** [comment]
Hi @pnuzyf ! Could you please look at these relevant threads for answer? Link [1](https://github.com/tensorflow/tensorflow/issues/32889#issuecomment-880245700) , [2.](https://colab.sandbox.google.com/gist/mohantym/2cedb7497a1c768d986a1d194c8843be/github_54465.ipynb#scrollTo=9RvlhcTdFdII) .

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) for further assistance.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by pnuzyf** [comment]
I have posted the issue to keras repo.will anybody take over this issue?

**Comment by pnuzyf** [comment]
> Hi @pnuzyf ! Could you please look at these relevant threads for answer? Link [1](https://github.com/tensorflow/tensorflow/issues/32889#issuecomment-880245700) , [2.](https://colab.sandbox.google.com/gist/mohantym/2cedb7497a1c768d986a1d194c8843be/github_54465.ipynb#scrollTo=9RvlhcTdFdII) .
> 
> Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) for further assistance. To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 . Thanks!

hello, could you test it with some IDE? such as pycharm?

**Comment by mohantym** [comment]
@pnuzyf !  It will be tracked there in Keras repo. But please post a simple stand alone code there. As debugging a entire source code is a tedious job. I will check in IDE and update you in mean while . Closing this issue for now. Thank you!

**Comment by mohantym** [comment]
Closing this issue for now. Thank you!

**Comment by pnuzyf** [comment]
> @pnuzyf ! It will be tracked there in Keras repo. But please post a simple stand alone code there. As debugging a entire source code is a tedious job. I will check in IDE and update you in mean while . Thank you!

When I added MemoryLayer to Msmt， I got the above error, without MemoryLayer, it's ok.
