### ISSUE TITLE
What operations are supported in tf.lite.OpsSet.TFLITE_BUILTINS_INT8

### ISSUE THREAD

**Issue by mrtpk123** [tensorflow/tensorflow#54476]
To convert a Keras model to tflite format using post-training quantization, we use `tf.lite.OpsSet.TFLITE_BUILTINS_INT8`. Is there any list of operations that are supported when this flag is set?

**Comment by mohantym** [comment]
Hi @mrtpk123 ! Can you check this [link](https://www.tensorflow.org/lite/guide/ops_compatibility) for answer?

**Comment by mrtpk123** [comment]
HI @mohantym, Thank you for your response. The [link has the list of all operators](https://www.tensorflow.org/mlir/tfl_ops) that are supported by TFlite. I want to know when operations are supported when we use `tf.lite.OpsSet.TFLITE_BUILTINS_INT8` flag.

Here is the context:
I have a `tf.transpose` in the model and when this model is converted to tflite using `tf.lite.OpsSet.TFLITE_BUILTINS_INT8`  I get an error - `'tf.Transpose' op is neither a custom op nor a flex op`. But, [transpose is a supported](https://www.tensorflow.org/mlir/tfl_ops#tfltranspose_mlirtfltransposeop) operation. When I add in `tf.lite.OpsSet.SELECT_TF_OPS`, I get the model converted to TFlite but it has dequantize and quantize operations before and after transpose layer (which is not expected). Moreover the tf.transpose is converted as `flextranspose`.

![image](https://user-images.githubusercontent.com/76564442/155113899-f32931b6-0312-4c35-b432-51899df161c3.png)

**Comment by mohantym** [comment]
@mrtpk123 ! Can you please share a simple stand alone code which help us expedite the issue?

**Comment by mrtpk123** [comment]
Yep. Below is the code:

```
import tensorflow as tf
import numpy as np
import pathlib

# model
inputs = tf.keras.Input(shape=(384, 544, 20))
x = tf.keras.layers.Reshape(target_shape= [384, 544, 5, 2, 2])(inputs)
x = tf.keras.layers.Lambda(lambda x : tf.transpose(x, perm=[0, 1, 2, 4, 5, 3]))(x)
x = tf.keras.layers.Reshape(target_shape= [384, 544, 20])(x)
x = tf.nn.depth_to_space(x, block_size=2)
model = tf.keras.Model(inputs=inputs, outputs=x, name="model")
path_tf_model = "./test.h5"
model.save(path_tf_model)
model.summary()

# convert
len_dataset = 2
def representative_data_gen():
    for idx in range(0, len_dataset): # 384, 544, 20
        input_value1 = np.random.rand(1, 384, 544, 20).astype(np.float32) * 255
        input_value1 = input_value1.astype(np.int) - 128
        input_value1 = input_value1.astype(np.float32)    
        yield [input_value1]

model = tf.keras.models.load_model(path_tf_model)
converter = tf.lite.TFLiteConverter.from_keras_model(model) 

converter.optimizations = [tf.lite.Optimize.DEFAULT]
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

converter.representative_dataset = representative_data_gen

tflite_model_quant = converter.convert()

tflite_models_dir = pathlib.Path("./")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

tflite_model_quant_file = tflite_models_dir/"test.tflite"
tflite_model_quant_file.write_bytes(tflite_model_quant)

```

![image](https://user-images.githubusercontent.com/76564442/155125609-8c8609fa-3477-44da-ae92-e57064bbfa51.png)
[models_transform_test.zip](https://github.com/tensorflow/tensorflow/files/8116293/models_transform_test.zip)

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? Attaching gist in [2.7](https://colab.sandbox.google.com/gist/mohantym/d4493e523bd7d0d1e32927fbbb6fcee6/github_54476.ipynb#scrollTo=GRICClPvrAU-), [2.8](https://colab.sandbox.google.com/gist/mohantym/8f32b9689c59e24333ca8c09b63b9b3a/github_54476.ipynb#scrollTo=pf9KClzehTs4) and [nightly](https://colab.sandbox.google.com/gist/mohantym/173ce2d0fdf404491678554c33fd9c48/github_54476.ipynb#scrollTo=pf9KClzehTs4)(2.9.0dev) for reference.

**Comment by mrtpk123** [comment]
From https://github.com/tensorflow/tensorflow/issues/53702, can I deduce that inputs with greater than four dimensions are not natively supported for Transpose operation?

**Comment by sachinprasadhs** [comment]
All the OPS in TFLite is not having support for `int8`, you can use the flag  for OPS which supports TFLite quint8 in their input and output [here](https://www.tensorflow.org/mlir/tfl_ops).
To avoid error, like you have tried you can mention like below 
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS]`
Which would apply `TFLITE_BUILTINS_INT8` if OP is supported, else it will apply `SELECT_TF_OPS`
