### ISSUE TITLE
Error message of `tf.nn.gelu` with `uint16` input is misleading 

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54475]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
features = tf.zeros([3, 4], dtype=tf.uint16)
tf.nn.gelu(features)
```
Throws `TypeError`
```
TypeError: Cannot convert 0.5 to EagerTensor of dtype uint16
```
**Describe the current behavior**
The current message is misleading, as it seems to be some computation error. If `tf.nn.gelu` does not accept `uint16` inputs, the message should be a standard message like
```
Value for attr 'T' of uint16 is not in the list of allowed values:
```
Similar to `tf.nn.crelu`:
```
import tensorflow as tf
features = tf.zeros([3, 4], dtype=tf.uint16)
tf.nn.crelu(features)
# InvalidArgumentError: Value for attr 'T' of uint16 is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64, complex64, complex128; NodeDef: {{node Neg}}; Op<name=Neg; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]> [Op:Neg]
```

**Describe the expected behavior**
`tf.nn.gelu` should have better error message in this case.

**Comment by rthadur** [comment]
Thank you for reporting , will update the code soon.
