### ISSUE TITLE
XLA tf.bincount support

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#54479]
**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): only if we have a clear path and a reviewer on how to contribute this
**Describe the feature and the current behavior/state.**
`tf.bincount` isn't supported by XLA
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Speedup functions/loops that rely on `tf.bincount`
**Any Other info.**
How to reproduce it:
```python
import tensorflow as tf
@tf.function(jit_compile=True)
def compiled_bincount(values):
  return tf.math.bincount(values)

values = tf.constant([1,1,2,3,2,4,4,5])
print(compiled_bincount(values)) #[0 2 2 1 2 1]
```

```python
InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_compiled_bincount_296[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: Bincount (No registered 'Bincount' OpKernel for XLA_CPU_JIT devices compatible with node {{node bincount/Bincount}}){{node bincount/Bincount}}
The op is created at: 
```

Without this we had problems to compile intermediate Ms Coco recall function in keras-cv:
https://github.com/keras-team/keras-cv/issues/141#issuecomment-1043692891

Extra: 
Please also note that the CPU/GPU TF2XLA supported ops tables are probably outdated (2018):
https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247

/cc @joker-eph @LukeWood

**Comment by LukeWood** [comment]
Thanks for opening this.  This would be really helpful for the KerasCV project.

**Comment by cheshire** [comment]
@bhack is this still relevant? 

1) If you are willing to write a TF2XLA kernel, I could help with review.

2) As a shorter-term solution, what do you think about using light outside compilation to achieve this, similarly to https://github.com/tensorflow/tensorflow/commit/1edb91b1cb4390189d77e15e491df035f4016fd2 ? In that solution, HLO will directly call into a TF kernel (which precludes fusing the TF kernel, but other optimizations remain viable).

**Comment by bhack** [comment]
What is the most similar thing to 1. for `tf.bincount` in our portfolio:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/tf2xla/kernels

**Comment by cheshire** [comment]
Kernels for tf.where and tf.unique.

**Comment by bhack** [comment]
Ok i.e. where is the test for [tf.unique](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/kernels/unique_op.cc)?

**Comment by bhack** [comment]
Is it in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/def_function_xla_jit_test.py?

Another question, is this going to be still valid when the mlir bridge will be enabled (as I see specific tests for this case) or will need need to write something totally different (just to understand if this effort will eventually have a minimal longevity).

**Comment by cheshire** [comment]
Yes , it will be valid, mlir bridge can call tf2xla kernels.

**Comment by bhack** [comment]
Is the test I've pointed correct?

In the end what Is the scope of TF2XLA kernel? Is it Is a c++ implementation that need to use 
only [XLA Op semantics](https://www.tensorflow.org/xla/operation_semantics)? Any other constrain?

**Comment by bhack** [comment]
Just another info I see that iterating the development over this TF2XLA kernels is quite slow also on a GCP instance with a modern CPU. 
E.g. with every single edit in `unique_op.cc`:

```bazel test  -k tensorflow/python/eager:def_function_xla_jit_test  --flaky_test_attempts=1  --test_filter=*testUniqueCompilability*```

```Elapsed time: 48.398s, Critical Path: 40.65s```

**Comment by bhack** [comment]
@cheshire 
In the meant time I would try at least to prepare/merge a good test coverage with a dummy kernel. 
We can discuss on the test early draft at https://github.com/tensorflow/tensorflow/pull/56276

**Comment by bhack** [comment]
As @LukeWood didn't share any additional code/perf gist but we have merged yesterday the `bincount` XLA kernel in TF I've tried  again to `jit_compile` the Mscoco `MAP` `update` function with `tf-nightly`:
https://github.com/keras-team/keras-cv/blob/master/keras_cv/metrics/coco/mean_average_precision.py#L148-L293

Running `pytest keras_cv/metrics/coco/mean_average_precision_test.py` we have:

```python
FAILED keras_cv/metrics/coco/mean_average_precision_test.py::COCOMeanAveragePrecisionTest::test_bounding_box_counting - tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 to node `while_1/while/while/bincount/Bincount` with op Bincount must be a compile-time constant.
FAILED keras_cv/metrics/coco/mean_average_precision_test.py::COCOMeanAveragePrecisionTest::test_counting_with_missing_class_present_in_data - tensorflow.python.framework.errors_impl.UnimplementedError: Dynamic reshape is not implemented.
FAILED keras_cv/metrics/coco/mean_average_precision_test.py::COCOMeanAveragePrecisionTest::test_mixed_dtypes - tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 to node `while_1/while/while/bincount/Bincount` with op Bincount must be a compile-time constant.
FAILED keras_cv/metrics/coco/mean_average_precision_test.py::COCOMeanAveragePrecisionTest::test_runs_inside_model - tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:
FAILED keras_cv/metrics/coco/mean_average_precision_test.py::COCOMeanAveragePrecisionTest::test_runs_with_confidence_over_1 - tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_update_state_5982[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] 
```

As for two test the error output is truncated we have:

```python
2022-07-09 13:53:06.869179: W tensorflow/core/framework/op_kernel.cc:1777] OP_REQUIRES failed at bincount_op.cc:49 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.
2022-07-09 13:53:06.869839: W tensorflow/core/framework/op_kernel.cc:1777] OP_REQUIRES failed at while_op.cc:351 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.
         [[{{function_node while_1_while_while_body_494}}{{node while_1/while/while/bincount_1/Bincount}}]]
2022-07-09 13:53:06.870151: W tensorflow/core/framework/op_kernel.cc:1777] OP_REQUIRES failed at while_op.cc:351 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.
         [[{{function_node while_1_while_while_body_494}}{{node while_1/while/while/bincount_1/Bincount}}]]
         [[while_1/while/while_tfg_inlined_while_1/while_tfg_inlined_while_1_1_1]]
2022-07-09 13:53:06.870502: W tensorflow/core/framework/op_kernel.cc:1777] OP_REQUIRES failed at while_op.cc:351 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.
         [[{{function_node while_1_while_while_body_494}}{{node while_1/while/while/bincount_1/Bincount}}]]
         [[while_1/while/while_tfg_inlined_while_1/while_tfg_inlined_while_1_1_1]]
         [[while_1/while_tfg_inlined_while_1_1]]
2022-07-09 13:53:06.877054: W tensorflow/core/framework/op_kernel.cc:1777] OP_REQUIRES failed at xla_ops.cc:296 : UNIMPLEMENTED: Dynamic reshape is not implemented.
        while evaluating input 1 of Bincount operator as a compile-time constant.
         [[{{function_node while_1_while_while_body_494}}{{node while_1/while/while/bincount_1/Bincount}}]]
         [[while_1/while/while_tfg_inlined_while_1/while_tfg_inlined_while_1_1_1]]
         [[while_1/while_tfg_inlined_while_1_1]]
         [[while_1]]
```

And for the last one.
```python
XLA_CPU_JIT: RaggedTensorToTensor (No registered 'RaggedTensorToTensor' OpKernel for XLA_CPU_JIT devices compatible with node {{node RaggedToTensor/RaggedTensorToTensor}}){{node RaggedToTensor/RaggedTensorToTensor}}
```

@cheshire Let me know if we could do something else here to cover these issues or I will close this as we have now the Bincount TF2XLA kernel in master.

**Comment by cheshire** [comment]
Ragged tensor is not supported in XLA, so it might not be feasible now?

**Comment by bhack** [comment]
> Ragged tensor is not supported in XLA, so it might not be feasible now?

We know this but If you check this is just one test case.

What do you think about the other issues ?

**Comment by bhack** [comment]
Some of these  `Dynamic reshape is not implemented` are:

https://github.com/tensorflow/tensorflow/blob/262777e9f9304c7df6b694934af819c820954ef5/tensorflow/compiler/xla/literal.cc#L963-L965

**Comment by bhack** [comment]
As XLA support it is finally merged, please follow-up Keras-cv use case (excluding Raggedtensor input that is not supported in XLA) at:
https://github.com/tensorflow/tensorflow/issues/56769
