### ISSUE TITLE
Web Page problem

### ISSUE THREAD

**Issue by FedePeralta** [tensorflow/tensorflow#54478]
When trying to access some pages of tensorflow it downloads an xml instead of showing the webpage
![image](https://user-images.githubusercontent.com/19721178/155134500-416d0005-29e5-404f-bc8b-0bfb6358a2ab.png)

**Comment by aliencaocao** [comment]
Many pages especially keras related pages all have this issue. Changing browsers does not work.

**Comment by sushreebarsa** [comment]
@FedePeralta  @aliencaocao We are able to reproduce the issue . We will resolve this soon.Thank you!

**Comment by sushreebarsa** [comment]
@FedePeralta This should be fixed now.Could you please confirm the same?Thanks!
