### ISSUE TITLE
TF1.15 configuartion with CUDA 11.4 and cuDNN 8

### ISSUE THREAD

**Issue by Wolpes11** [tensorflow/tensorflow#54471]
<em>Hi everybody, I am wondering if it's possible to use TF1.15 with CUDA 11.4 and cuDNN 8. The problem that I have is that the migration of the code to TF2 is painful and I have no root privileges on this machine to modify the CUDA drivers.</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from pip: version 1.15
- Python version: python 3.7.12 in virtaulenv
- CUDA/cuDNN version: CUDA 11.4 and cuDNN 8
- GPU model and memory: NVIDIA A100-SMX-80GB

When I run my script TF looks for libraries of CUDA 10 and cuDNN 7, such as libcudart.10.so, libcublas.10.so, etc...

Thank you!

**Comment by tilakrayal** [comment]
@Wolpes11 ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to latest stable  v2.7 or v2.8 from [here](https://www.tensorflow.org/install) and let us know if you are facing same issue.Also please take a look at this [link](https://www.tensorflow.org/install/source#linux) for tested build configurations.It helps.Thanks!

**Comment by Wolpes11** [comment]
Thank you for your prompt reply.
I know that tf 1.15 is no longer supported but with version 2.x my code doesn't work and it takes too much to convert the code (and I'm not sure I can obtain the same results).
According to this [link](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-10.html#rel_21-10) there should be a way to configure tf 1.15 with the latest CUDA libraries, even if I can't figure out how.

**Comment by chunduriv** [comment]
@Wolpes11,

We have tested in Google Colab with `TF1.15` and CUDA `11.1` and it is working as expected. Please can you install build from source using `bazel`. 

Make sure your branch is - `git checkout TF r1.15` and on `./configure` mention the CUDA version as `11.4` and set the appropriate CUDA and cuDNN path.

Please refer this [guide](https://www.tensorflow.org/install/source).Thanks!
