### ISSUE TITLE
`parallel_iterations` in `tf.map_fn` has no effect

### ISSUE THREAD

**Issue by charlielam0615** [tensorflow/tensorflow#54470]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: Python 3.9.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.2
- GPU model and memory: RTX A6000, CPU: Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`parallel_iterations` in `tf.map_fn` has no effect
**Describe the expected behavior**
setting higher values in `parallel_iterations` should improve running speed
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): on
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf
import time
import numpy as np

def some_fn(x):
    return tf.math.exp(x)

@tf.function
def map_fn_test(samples):
    some_fn_vals = tf.map_fn(some_fn, samples, parallel_iterations=1)
    return some_fn_vals

samples = tf.constant(np.linspace(0,10,100000))
start_time = time.time()
values = map_fn_test(samples)
print("--- %s seconds ---" % (time.time() - start_time))
```

Changing `parallel_iterations` to any other number gives approximately the same amount of time. It looks like there ain't any parallelism happening.

This bug was also reported [here](https://github.com/tensorflow/tensorflow/issues/34716#issuecomment-560936125) and also [here](https://github.com/tensorflow/tensorflow/issues/24774) but remain stalled.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @charlielam0615 ! As this [document ](https://www.tensorflow.org/api_docs/python/tf/map_fn#args)suggests the number of iterations allowed to run in parallel default value is 10 in graph mode and is set to 1 in eager mode . I set values for parallel_operations accordingly and was getting different results. Attaching[ gist](https://colab.sandbox.google.com/gist/mohantym/d12855919bb832049bf64fb1457def39/github_54470.ipynb#scrollTo=C0uqpVUVmKrl) for reference

**Comment by charlielam0615** [comment]
Hi @mohantym, as per the outputs of your gist, with the `parallel_iterations` increasing from 10 to 20, the code doesn't run significantly faster (if not slower). It makes one wonder if there is indeed parallelization happening behind the scene.
```
--- 0.029703855514526367 seconds ---
--- 0.02797532081604004 seconds ---
--- 0.02787494659423828 seconds ---
--- 0.02804279327392578 seconds ---
--- 0.027938365936279297 seconds ---
--- 0.02780890464782715 seconds ---
--- 0.08853292465209961 seconds ---
--- 0.05671095848083496 seconds ---
--- 0.026008129119873047 seconds ---
--- 0.027454853057861328 seconds ---
```

**Comment by mohantym** [comment]
Hi @gadagashwini ! Could you look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/6160d5ad155e8f455c39dbf237a2e745/github_54470.ipynb#scrollTo=3m9IAJirnvZZ), [2.8](https://colab.sandbox.google.com/gist/mohantym/d12855919bb832049bf64fb1457def39/github_54470.ipynb#scrollTo=3m9IAJirnvZZ) and [nightly.](https://colab.sandbox.google.com/gist/mohantym/b82990e604cbd135c685019a92391a40/github_54470.ipynb#scrollTo=3m9IAJirnvZZ)

**Comment by gadagashwini** [comment]
@charlielam0615,
I tried your code on Eager execution and tf.function mode with parallel_iterations, Looks like there is difference in execution  time.

**Graph mode: parallel execution**
```
import tensorflow as tf
import time
import numpy as np

def some_fn(x):
    return tf.math.exp(x)

@tf.function
def map_fn_test(samples,iterations):
    some_fn_vals = tf.map_fn(some_fn, samples, parallel_iterations=iterations)
    return some_fn_vals

samples = tf.constant(np.linspace(0,10,100000))

for iterations in range(1,5):
 start_time = time.time()
 values = map_fn_test(samples,iterations)
 print("--- %s seconds ---" % (time.time() - start_time))

--- 40.14726758003235 seconds ---
--- 38.71791315078735 seconds ---
--- 34.22684836387634 seconds ---
--- 34.73827767372131 seconds ---
```

**Eager mode: Sequential Execution**
```
import tensorflow as tf
import time
import numpy as np

def some_fn(x):
    return tf.math.exp(x)

def map_fn_test(samples,iterations):
    some_fn_vals = tf.map_fn(some_fn, samples, parallel_iterations=iterations)
    return some_fn_vals

samples = tf.constant(np.linspace(0,10,100000))

for iterations in range(1,5):
 start_time = time.time()
 values = map_fn_test(samples,iterations)
 print("--- %s seconds ---" % (time.time() - start_time))

--- 124.02748465538025 seconds ---
--- 93.25651001930237 seconds ---
--- 93.3725266456604 seconds ---
--- 92.41289329528809 seconds ---
```

**Comment by charlielam0615** [comment]
Hi @gadagashwini, I do not observe speed improvement with higher `parallel_iterations` settings on my own machine (TF2.8, RTX A6000, CUDA 11.2).

(Using your code)
**Graph mode: parallel execution**
```
--- 21.58019709587097 seconds ---
--- 21.391409873962402 seconds ---
--- 21.302981853485107 seconds ---
--- 21.093496322631836 seconds ---
```
**Eager mode: Sequential Execution**
```
--- 52.483237504959106 seconds ---
WARNING:tensorflow:Setting parallel_iterations > 1 has no effect when executing eagerly. Consider calling map_fn with tf.function to execute fn in parallel.
--- 53.701409578323364 seconds ---
--- 55.06963491439819 seconds ---
--- 50.95377826690674 seconds ---
```
While in Eager mode, there is indeed time difference, but as far as the warning tells, these time differences should not be attributed to `parallel_iterations` as parallel_iterations>1 settings virtually has no effect.

Also, I suspect the time difference you see in **Graph mode** is not due to different `parallel_iteration` settings, as parallelism should give performance boost in this situation approximately linear in the number of threads. I think the time could be explained if some overhead is calculated in the first iteration. Changing `for iterations in range(1,5):` to `for iterations in [1,1,2,3,4]:` confirms this conjecture (see [this notebook](https://colab.research.google.com/drive/1LjerXUgeOw5Z6rNQqUKqu73sqa1Df72I?usp=sharing))
```
--- 52.46350336074829 seconds --- # parallel_iteration = 1
--- 50.104897022247314 seconds --- # parallel_iteration = 1
--- 51.024954319000244 seconds --- # parallel_iteration = 2
--- 51.20623803138733 seconds --- # parallel_iteration = 3
--- 51.01601719856262 seconds --- # parallel_iteration = 4
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
