### ISSUE TITLE
invalid conversion from 'cudnnDropoutStruct*' to 'int' [-fpermissive]     

### ISSUE THREAD

**Issue by puneet336** [tensorflow/tensorflow#5447]
Hi all,
I am trying to compile tensorflow-0.11 + bazel 0.3.2 on RHEL 6 with cuda 7.0 + cudnn 7.5.5.0 + gcc 4.9.
The compilation command is :
EXTRA_BAZEL_ARGS="--jobs 10" bazel build -c opt --config=cuda --jobs 10 //tensorflow/tools/pip_package:build_pip_package 

Compilation of rule '//tensorflow/stream_executor:stream_executor' fails with cuda specific message.

I have latest version of compilers at non standard path , hence i had modified some variables in CROSSTOOL.tpl + third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl. I am attaching **compilation error logs**, **CROSSTOOL.tpl** and **third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl** for your reference.

Though i am able to compile cpu-only version of tensorflow successfully. 
Please let me know if any information is needed from my side.
Eagerly awaiting your replies.

[crosstool_wrapper_driver_is_not_gcc.tpl.txt](https://github.com/tensorflow/tensorflow/files/575209/crosstool_wrapper_driver_is_not_gcc.tpl.txt)
[CROSSTOOL.tpl.txt](https://github.com/tensorflow/tensorflow/files/575211/CROSSTOOL.tpl.txt)
[tensorflow_build2.log.txt](https://github.com/tensorflow/tensorflow/files/575210/tensorflow_build2.log.txt)

**Comment by puneet336** [comment]
Hi,
I retried compilation of tensorflow 0.11 with cuda -7.0 & cudnn 7.0
i got:
tensorflow/stream_executor/cuda/cuda_dnn.cc:154:39: error: '::cudnnBatchNormalizationBackward' has not been declared
     typedef std::add_pointer<decltype(::__name)>::type FuncPoint
Detailed error log is attached herewith.
It seems that the cuda 7 & cudnn 7/7.5 are incompatible with tensorflow-0.11
If this is the case , could you please recommend a newer "suitable" version for the version of cuda i have currently(7.0).



[tensorflow_build3.log.txt](https://github.com/tensorflow/tensorflow/files/575585/tensorflow_build3.log.txt)

**Comment by aselle** [comment]
@gunan, do we now require at least Cuda 7.5?

**Comment by gunan** [comment]
I thought no, but it now certainly looks like it. Not sure who to check
with if the bump was intentional though.

On Nov 7, 2016 11:06 AM, "Andrew Selle" <notifications@github.com> wrote:

> <https://github.com/gunan>

> @gunan <https://github.com/gunan>, do we now require at least Cuda 7.5?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/5447#issuecomment-258930171>,
or mute the thread

**Comment by puneet336** [comment]
Thank you all for the help,
tried cuda-7 + cudnn 7.5 -> build failed (version incompatibility)
I tried cuda-7 + cudnn 7.0.3.0  --> build failed
I tried cuda-7 + cudnn 7.0.4.0  --> build was success!
I checked the cudnn.h file for 7.0.3.0 , it didn't had the declaration of "cudnnBatchNormalizationBackward", whereas 7.0.4.0 's cudnn.h had the definition. This issue could be closed now.

**Comment by gunan** [comment]
We should update our documentation to reflect this.
Sorry for the inconvenience.

however, in your documentation, what do you mean by cudnn 7?
I think there was a typo, the latest cudnn version out is cudnn 5.xx

**Comment by puneet336** [comment]
Hi,
My apologies for delayed reply. 7.0.4 was indeed a typo.
in cudnn.h 
#define CUDNN_MAJOR      4
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 7
so CUDNN_MAJOR .  CUDNN_MINOR . CUDNN_PATCHLEVEL-> 4.0.7 (  7.0.4 )

**Comment by gunan** [comment]
Problem might be the cudnn version.
We upgraded all our test machines to use cuda 8.0 and cudnn 5.0 and 5.1.
Anything older we are not testing anymore.
