### ISSUE TITLE
SavedModel way slower than h5 in loading

### ISSUE THREAD

**Issue by SergioG-M** [tensorflow/tensorflow#54477]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.7
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 7.3
- CUDA/cuDNN version: 11.2/8.1
- GPU model and memory: T4

I have found some issues about this, but I didn't find any solution/explanation about it. Loading a SavedModel is way slower than loading the same model in h5df. Is there any way to speed this up? I find hard to justiy the use SavedModel (even if it is the preferred formar) if it takes 4x-5x longer to load in my code.

![image](https://user-images.githubusercontent.com/61322372/155090488-110b9206-7b85-4b95-8df1-586bf17de3d5.png)

**Comment by sushreebarsa** [comment]
@SergioG-M 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
