### ISSUE TITLE
Building tensorflowlite.so for aarch_64 failed 

### ISSUE THREAD

**Issue by mohamedgamal7** [tensorflow/tensorflow#54473]
**System information**
- OS Platform and Distribution (Windows 10):
- Mobile device ( for RPI4) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source (cloned the repo)
- TensorFlow version: latest
- Python version: 3.7.9
- Installed using virtualenv? pip? conda?: none
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): g++
- CUDA/cuDNN version: 
- GPU model and memory: gtx 1060 6gb

**Describe the problem**
I followed this tutorial for cross compilation of aarch64 
https://www.tensorflow.org/lite/guide/build_arm
1- cloned tensorflow repo 
2- ran `bazel build --config=elinux_aarch64 -c opt //tensorflow/lite:libtensorflowlite.so`

**Any other info / logs**
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/Mohamed_Gamal/AppData/Local/Microsoft/WindowsApps/python.exe
INFO: Reading rc options for 'build' from c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=//tensorflow/tools/toolchains/java:tf_java_toolchain --host_java_toolchain=//tensorflow/tools/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_aarch64 in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --config=elinux --cpu=aarch64 --distinct_host_configuration=true
INFO: Found applicable config definition build:elinux in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:windows in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\mohamed_gamal\downloads\tensorflow_src\.bazelrc: --define framework_shared_object=false
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/9df1c45bd751eeff53f6811501e015c7eba4b536.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository local_config_embedded_arm instantiated at:
  C:/users/mohamed_gamal/downloads/tensorflow_src/WORKSPACE:15:14: in <toplevel>
  C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/workspace2.bzl:868:19: in workspace
  C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/workspace2.bzl:118:34: in _tf_toolchains
Repository rule arm_linux_toolchain_configure defined at:
  C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/tools/toolchains/embedded/arm-linux/arm_linux_toolchain_configure.bzl:34:48: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_embedded_arm':
   Traceback (most recent call last):
        File "C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/tools/toolchains/embedded/arm-linux/arm_linux_toolchain_configure.bzl", line 23, column 9, in _arm_linux_toolchain_configure_impl
                _tpl(repository_ctx, "cc_config.bzl", {
        File "C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/tools/toolchains/embedded/arm-linux/arm_linux_toolchain_configure.bzl", line 6, column 28, in _tpl
                repository_ctx.template(
Error in template: Unable to load package for //tensorflow/tools/toolchains/embedded/arm-linux:cc_config.bzl.tpl: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/tools/toolchains/embedded/arm-linux
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/users/mohamed_gamal/downloads/tensorflow_src/WORKSPACE:23:14: in <toplevel>
  C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/workspace0.bzl:110:34: in workspace
  C:/users/mohamed_gamal/_bazel_mohamed_gamal/wmmhak3q/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  C:/users/mohamed_gamal/_bazel_mohamed_gamal/wmmhak3q/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/lite/BUILD:1158:24: //tensorflow/lite:libtensorflowlite.so depends on @local_config_embedded_arm//:toolchain in repository @local_config_embedded_arm which failed to fetch. no such package '@local_config_embedded_arm//': Unable to load package for //tensorflow/tools/toolchains/embedded/arm-linux:cc_config.bzl.tpl: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - C:/users/mohamed_gamal/downloads/tensorflow_src/tensorflow/tools/toolchains/embedded/arm-linux
ERROR: Analysis of target '//tensorflow/lite:libtensorflowlite.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.724s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by mohantym** [comment]
Hi @mohamedgamal7 ! Could you try with Bazel 4.2.2/5.0.0 after installing [llvm package](https://github.com/tensorflow/tensorflow/issues/54257#issuecomment-1033387603) locally ?
