### ISSUE TITLE
cant open pages

### ISSUE THREAD

**Issue by reemaljaber** [tensorflow/tensorflow#54480]
the website downloads  pages instead of opening them

**Comment by mpettinger** [comment]
I'm having the exact same issue on different browsers and machines.

**Comment by jvishnuvardhan** [comment]
We can reproduce the issue. We will resolve it soon. Thanks @reemaljaber @mpettinger

**Comment by MarkDaoust** [comment]
Yes. We are looking into this. Will fix ASAP.

**Comment by MarkDaoust** [comment]
This should be fixed now.

**Comment by reemaljaber** [comment]
it works thank you

**Comment by mpettinger** [comment]
Excellent work!
