### ISSUE TITLE
TFLite with Hexagon delegate produces wrong results for a particular model

### ISSUE THREAD

**Issue by AB5247** [tensorflow/tensorflow#54481]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 (host), Android 11 (target device)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: device with Snapdragon 660
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): 8.4.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
For a custom model I am trying to use, when I enable the Hexagon delegate, the output contains incorrect values. The Hexagon delegate seems to work fine with other models I have tried.

**Describe the expected behavior**
I expect the Hexagon delegate to produce the same results as CPU.

**Standalone code to reproduce the issue**
The difference between CPU and Hexagon delegate can be observed with your [Inference Diff tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff#inference-diff-tool):
```
INFO: TfLiteHexagonDelegate delegate: 270 nodes delegated out of 270 nodes with 1 partitions.
INFO: Replacing 270 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 1 partitions.
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:77 Test interpreter has been initialized.
native : lite/tools/evaluation/stages/tflite_inference_stage.cc:128 
native : lite/tools/evaluation/stages/inference_profiler_stage.cc:91 Reference interpreter (1 thread on CPU) has been initialized.
Num evaluation runs: 50
Reference run latency: avg=863334(us), std_dev=25697(us)
Test run latency: avg=93164.5(us), std_dev=675(us)
OutputDiff[0]: avg_error=86.0362, std_dev=0.0619768
OutputDiff[1]: avg_error=48.6195, std_dev=0.168915
OutputDiff[2]: avg_error=52.9178, std_dev=0.252582
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Model used: [test_model.zip](https://github.com/tensorflow/tensorflow/files/8118439/test_model.zip)

**Comment by sushreebarsa** [comment]
@AB5247 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by AB5247** [comment]
@sushreebarsa As I mentioned in my initial comment, the issue can easily be reproduced with the Inference Diff tool from this repository.

**Comment by AB5247** [comment]
Hi, are there any updates? Has anyone been able to take a look at this issue?

**Comment by AB5247** [comment]
@sushreebarsa @jvishnuvardhan @karimnosseir Can anyone provide an update on the status of this issue or if someone will be able to take a look at it soon? Thank you.

**Comment by AB5247** [comment]
@jvishnuvardhan Sorry, but this is not related to anything reported before and answered by @karimnosseir. TFlite with the Hexagon delegate is simply giving completely wrong results for the model I am working with, someone from your team will have to look at it and tell me what is going on. https://github.com/tensorflow/tensorflow/issues/36804 was a similar problem  and it was a bug that you eventually fixed.

**Comment by karimnosseir** [comment]
Sorry for the late reply as i was out of office and came back today. Will check it and update the issue.

Thanks

**Comment by AB5247** [comment]
@karimnosseir Any updates on this? Thanks.

**Comment by AB5247** [comment]
@jvishnuvardhan @sushreebarsa Sorry to bother you again, but can this be assigned to someone else if @karimnosseir is not able to take a look? It has been almost 2 months since I opened this issue and no one has told me yet if you can even reproduce the same bug I experience. Thanks.

**Comment by karimnosseir** [comment]
Hi @AB5247 
Sorry for the late update, we didn't ignore you. I was sick for some time.

Thanks for reporting

I can reproduce the issue, and found a bug related to relu layer and sent a fix for it.
There is another issue related to depthwise conv when stride h/w > 1 and shape has ?x5x5x? don't have a fix but will be disabling this until fix is ready - sending a change to it too..

Will update the issue here when changes are in.

Thanks

**Comment by AB5247** [comment]
Thanks @karimnosseir, glad you found the bugs. Please, keep me updated about the fixes. Thanks.

**Comment by jm4453** [comment]
Hi @karimnosseir , are there any updates for this issue? Is a fix going to go in soon?

Thanks,
John.

**Comment by karimnosseir** [comment]
The reshape fix is merged. The depthwise conv is not yet.
Sorry for the delay

Thanks

**Comment by MM2932** [comment]
Thanks @karimnosseir ! Do you have any update on the depthwise conv defect?

Thanks,
Massimo.

**Comment by sirakiin** [comment]
Hi @MM2932 ,

The depthwise conv issue is identified and it's a defect in Hexagon's depthwiseSupernode implementation. Unfortunately we can not modify hexagon nn lib. I'm trying to provide a workaround so we can avoid disabling it, but it requires some refactoring on the hexagon delegate code base. Will update in the thread next week.

**Comment by MM2932** [comment]
Hi @sirakiin , thanks for your update. Really appreciated! Talk to you next week then.

Have a good weekend!
Massimo.

**Comment by MM2932** [comment]
Hi @sirakiin ! Any new update you could share?

Thanks!
Massimo.

**Comment by karimnosseir** [comment]
@MM2932 The change in review and will be merged soon.

Thanks for your patience.

**Comment by sirakiin** [comment]
Hi @MM2932 

Could you help validate if the pushed change [5d18974](https://github.com/tensorflow/tensorflow/commit/5d189740ed607fbaf5b3f61009887b5ea9b89ca5) fixes the issue? 

Thanks!

**Comment by MM2932** [comment]
Hi @sirakiin , thanks! We'll test the change and let you know soon.

Thanks again!
Massimo.

**Comment by sirakiin** [comment]
Hi @AB5247 

What's the device you are trying to run on? Also could you try different devices with the inference diff?

Thanks.

**Comment by MM2932** [comment]
Hi @sirakiin !

Do you think you guys can run the change on a SnapDragon660 based device or something similar to reproduce our environment?

Thanks!
Massimo.

**Comment by MM2932** [comment]
Hi @sirakiin ,

Thanks! Please keep us updated about the progress.

Thanks again,
Massimo.

**Comment by MM2932** [comment]
Hi @sirakiin ,

Any recent update you could share with us on this issue?

Thanks!
Massimo.

**Comment by Janus-Shiau** [comment]
I use TF 2.7 for training and deploy to Proto Buffer. After that, I try to convert them with different TF version.
So far, some models still have wrong value on Hexagon, but fine on CPU.

### Convert with TF 2.2
I can reproduce this bug using TFLite converter in Tensorflow 2.4.0 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.1.
But using converter in Tensorflow 2.2.0 get correct result on both CPU and Hexagon.

### Troubleshooting
In our case, some building block, e.g. the residual-like conv. building block, may cause ***standalone ReLU*** operator in TFLite.
When this kind of operators occurs in graph, the results on CPU and Hexagon are usually different.

For example, this kind of building block result in wrong value in Hexagon.

![image](https://user-images.githubusercontent.com/22385182/186613415-2962a641-ed92-4130-bd75-1217672024ee.png)

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
