### ISSUE TITLE
Can't find tensorflow version on python 3.10.2

### ISSUE THREAD

**Issue by Lumijek** [tensorflow/tensorflow#54489]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS Monerey Version 12.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version:
2.8
- Python version:
3.10.2
- Installed using virtualenv? pip? conda?:
pip version 22.0.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I changed from python 3.8 to 3.10 as I saw from the official website that tensorflow 2.8 was supported by python 3.10 however it couldn't find a version that satisfied requirements.
**Provide the exact sequence of commands / steps that you executed before running into the problem**
![imageedit_3_9779348486](https://user-images.githubusercontent.com/52308419/155244353-63d4c411-f866-4ef4-addc-baaab14b4420.jpg)
I tried:
"python3 -m pip install tensorflow" and when that didn't work "python3 -m pip install tensorflow==2.8" but that didn't work either.

**Comment by sampathweb** [comment]
Can you clarify if you are on Mac M1 or Mac Intel machine?  You can get this information from Apple -> About this Mac and check the "Processor" listed there.

**Comment by Lumijek** [comment]
Oh I am on Mac M1. Guess I didn't look at the hardware requirements.

**Comment by burglarhobbit** [comment]
How did you solve this? I am stuck at the same issue

**Comment by OscarLundin** [comment]
Same,
