### ISSUE TITLE
ConnectionError when downloading deep_weeds dataset

### ISSUE THREAD

**Issue by nikitamaia** [tensorflow/tensorflow#54487]
I'm unable to use the [deep_weeds dataset](https://www.tensorflow.org/datasets/catalog/deep_weeds) from TensorFlow Datasets. Seems like this has happened in the past [#44053](https://github.com/tensorflow/tensorflow/issues/44053)

```
import tensorflow as tf
import tensorflow_datasets as tfds

data, info = tfds.load(name='deep_weeds')
```

Results in `ConnectionError`

[See gist here](https://colab.research.google.com/gist/nikitamaia/fdd8654acd6d6d889585f60895f158f5/untitled4.ipynb)

**Comment by sushreebarsa** [comment]
@jvishnuvardhan I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5e6b7b164edad2158a86cbe1e7a1a0de/untitled4.ipynb#scrollTo=6oW7j3XvIXTG) for reference.Thanks!

**Comment by jvishnuvardhan** [comment]
@Conchylicultor Can you please take a look at this issue? Thanks!

**Comment by nikitamaia** [comment]
I think we can close this now. It has been fixed in tfds-nightly, [see gist.](https://colab.research.google.com/gist/nikitamaia/f4ec07d2606d76f4f7bfd0104a2e0cb5/untitled5.ipynb)

**Comment by jvishnuvardhan** [comment]
Thanks @nikitamaia
