### ISSUE TITLE
[TFLite] memory cost is much higher when enable xnnpack delegate

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#54496]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OPPO Find X3Pro

Dear
I build TFLite benchmark_model from source code, based on commitID: 965c39fdf304a80eacd6cdca43241956084301c3 (CommitDate: Mon Feb 21 15:37:46 2022 -0800)

build command: 
```
bazel build -c opt --config=android_arm64 --define tflite_with_xnnpack=true --define tflite_with_xnnpack_qs8=true --define tflite_with_xnnpack_qu8=true tensorflow/lite/tools/benchmark:benchmark_model
```

then I run benchmark_model on my Android Phone, I test with model  https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_quant_and_labels.zip

when disable xnnpack, the memory cost is 8.8MB, see below:
build command: 
```
OP:/data/local/tmp # ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=4 --use_xnnpack=false
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [mobilenet_v1_1.0_224_quant.tflite]
#threads used for CPU inference: [4]
Use xnnpack: [0]
Loaded model mobilenet_v1_1.0_224_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
The input model file size (MB): 4.27635
Initialized session in 1.004ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=43 first=22701 curr=10983 min=10906 max=22701 avg=11638.5 std=1768

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=91 first=11004 curr=10970 min=10864 max=11745 avg=11008.7 std=105

Inference timings in us: Init: 1004, First inference: 22701, Warmup (avg): 11638.5, Inference (avg): 11008.7
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=3.32422 overall=8.83984
```

When enable xnnpack, the memory cost is 13.8MB, see below:
```
OP:/data/local/tmp # ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=4 --use_xnnpack=true
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [mobilenet_v1_1.0_224_quant.tflite]
#threads used for CPU inference: [4]
Use xnnpack: [1]
Loaded model mobilenet_v1_1.0_224_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Replacing 28 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 4 partitions.
Explicitly applied XNNPACK delegate, and the model graph will be partially executed by the delegate w/ 2 delegate kernels.
The input model file size (MB): 4.27635
Initialized session in 14.79ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=66 first=13307 curr=7452 min=7431 max=13307 avg=7638.41 std=719

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=133 first=7588 curr=7541 min=7445 max=8710 avg=7556.99 std=159

Inference timings in us: Init: 14790, First inference: 13307, Warmup (avg): 7638.41, Inference (avg): 7556.99
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=11.2891 overall=13.8906
```

Could you please help check this ?

**Comment by multiverse-tf** [comment]
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OPPO Find X3Pro
> 
> Dear I build TFLite benchmark_model from source code, based on commitID: [965c39f](https://github.com/tensorflow/tensorflow/commit/965c39fdf304a80eacd6cdca43241956084301c3) (CommitDate: Mon Feb 21 15:37:46 2022 -0800)
> 
> build command:
> 
> ```
> bazel build -c opt --config=android_arm64 --define tflite_with_xnnpack=true --define tflite_with_xnnpack_qs8=true --define tflite_with_xnnpack_qu8=true tensorflow/lite/tools/benchmark:benchmark_model
> ```
> 
> then I run benchmark_model on my Android Phone, I test with model https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_quant_and_labels.zip
> 
> when disable xnnpack, the memory cost is 8.8MB, see below: build command:
> 
> ```
> OP:/data/local/tmp # ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=4 --use_xnnpack=false
> STARTING!
> Log parameter values verbosely: [0]
> Num threads: [4]
> Graph: [mobilenet_v1_1.0_224_quant.tflite]
> #threads used for CPU inference: [4]
> Use xnnpack: [0]
> Loaded model mobilenet_v1_1.0_224_quant.tflite
> INFO: Initialized TensorFlow Lite runtime.
> The input model file size (MB): 4.27635
> Initialized session in 1.004ms.
> Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
> count=43 first=22701 curr=10983 min=10906 max=22701 avg=11638.5 std=1768
> 
> Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
> count=91 first=11004 curr=10970 min=10864 max=11745 avg=11008.7 std=105
> 
> Inference timings in us: Init: 1004, First inference: 22701, Warmup (avg): 11638.5, Inference (avg): 11008.7
> Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
> Memory footprint delta from the start of the tool (MB): init=3.32422 overall=8.83984
> ```
> 
> When enable xnnpack, the memory cost is 13.8MB, see below:
> 
> ```
> OP:/data/local/tmp # ./benchmark_model --graph=mobilenet_v1_1.0_224_quant.tflite --num_threads=4 --use_xnnpack=true
> STARTING!
> Log parameter values verbosely: [0]
> Num threads: [4]
> Graph: [mobilenet_v1_1.0_224_quant.tflite]
> #threads used for CPU inference: [4]
> Use xnnpack: [1]
> Loaded model mobilenet_v1_1.0_224_quant.tflite
> INFO: Initialized TensorFlow Lite runtime.
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> XNNPACK delegate created.
> INFO: Replacing 28 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 4 partitions.
> Explicitly applied XNNPACK delegate, and the model graph will be partially executed by the delegate w/ 2 delegate kernels.
> The input model file size (MB): 4.27635
> Initialized session in 14.79ms.
> Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
> count=66 first=13307 curr=7452 min=7431 max=13307 avg=7638.41 std=719
> 
> Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
> count=133 first=7588 curr=7541 min=7445 max=8710 avg=7556.99 std=159
> 
> Inference timings in us: Init: 14790, First inference: 13307, Warmup (avg): 7638.41, Inference (avg): 7556.99
> Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
> Memory footprint delta from the start of the tool (MB): init=11.2891 overall=13.8906
> ```
> 
> Could you please help check this ?

Thx for reporting this! This is not surprising to us when we turned on XNNPACK by default, especially when the model is small and the relative memory footprint increase is quite large. We intentionally made a trade-off between memory consumption increase and performance gains across a wide range of platforms. 

Note we provide multiple options to disable using XNNPACK-by-default if the memory consumption increase doesn't fit your use cases. One could use any one of the following options:
1. Add --define=tflite_with_xnnpack=false when compiling the code using Bazel.
2. In C++ code, use [BuiltinOpResolverWithoutDefaultDelegates](https://github.com/tensorflow/tensorflow/blob/6f824c625ac538d6aebe198a73147e916230df85/tensorflow/lite/kernels/register.h#L39) when resolving Tensorflow Lite ops.
3. In Python code, use [BUILTIN_WITHOUT_DEFAULT_DELEGATES](https://github.com/tensorflow/tensorflow/blob/6f824c625ac538d6aebe198a73147e916230df85/tensorflow/lite/python/interpreter.py#L338) when creating the Interpreter.
