### ISSUE TITLE
capture_tpu_profile on Cloud TPU VM

### ISSUE THREAD

**Issue by bduclaux** [tensorflow/tensorflow#54495]
Hello

It seems that capture_tpu_profile only works for legacy TPU devices, but not for Cloud TPU VM.

I was wondering if and when we can expect to have support for Cloud TPU VM. 
At the moment, its is impossible to monitor Jax/Flax TPU workloads, as tensorboard instrumentation does not exhibit the right metrics (eg % utilization of TPU Matrix Units).

Other related thread for legacy TPU devices: https://stackoverflow.com/questions/52427141/check-tpu-workload-utilization

Thanks!

**Comment by gowthamkpr** [comment]
@bduclaux Unfortunately `capture_tpu_profile` doesn't work with TPU VM.
Please take a look at this [explanation](https://stackoverflow.com/questions/70783509/google-cloud-tpu-capture-tpu-profile-no-trace-event-is-collected-after-n-attem). Thanks!
