### ISSUE TITLE
Build failing from tensorflow r2.7

### ISSUE THREAD

**Issue by JueonPark** [tensorflow/tensorflow#54498]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **centos 7**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **source** 
- TensorFlow version: **r2.7**
- Python version: **3.6.13**
- Installed using virtualenv? pip? conda?: **conda**
- Bazel version (if compiling from source): **3.7.2**
- GCC/Compiler version (if compiling from source): **8.3.0**
- CUDA/cuDNN version: **CUDA 10.1.243, cuDNN 7.6.4**
- GPU model and memory: **RTX 2080 * 4, 67 GB (not sure)**

**Describe the problem**
Build keep failing with branch r2.7.
The build emits ` error: incomplete type is not allowed` message, yet I have not faced this issue before, nor from issues to best of my knowledge.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have done configuration with `./configure`, selecting the options described above.
After that, I used the following instrcution to build TensorFlow.
``` bash
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```
The build ended with the following error, and I found that there was no similar issue with this error.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
``` text
WARNING: Output base '/home/jueonpark/.cache/bazel/_bazel_jueonpark/39636ca59c1e25526db6a6ad2e035e5e' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=209
INFO: Reading rc options for 'build' from /home/jueonpark/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/jueonpark/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /home/jueonpark/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/jueonpark/anaconda3/envs/timeloop/bin/python3 --action_env PYTHON_LIB_PATH=/home/jueonpark/anaconda3/envs/timeloop/lib/python3.6/site-packages --python_path=/home/jueonpark/anaconda3/envs/timeloop/bin/python3 --action_env TF_CUDA_PATHS=/home/jueonpark/cuda --action_env CUDA_TOOLKIT_PATH=/home/jueonpark/cuda-10.1 --action_env CUDNN_INSTALL_PATH=/home/jueonpark/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.0 --action_env LD_LIBRARY_PATH=/home/jueonpark/cuda/extras/CUPTI/lib64:/home/jueonpark/cuda/lib64:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64:/home/jueonpark/cuda/extras/CUPTI/lib64:/home/jueonpark/cuda/lib64 --action_env GCC_HOST_COMPILER_PATH=/opt/ohpc/pub/compiler/gcc/8.3.0/bin/gcc --config=cuda
INFO: Reading rc options for 'build' from /home/jueonpark/tensorflow/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/jueonpark/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/jueonpark/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /home/jueonpark/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file /home/jueonpark/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:linux in file /home/jueonpark/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/jueonpark/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/jueonpark/tensorflow/tensorflow/core/kernels/image/BUILD:308:18: C++ compilation of rule '//tensorflow/core/kernels/image:resize_nearest_neighbor_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 216 argument(s) skipped)
external/com_google_absl/absl/types/internal/span.h(38): error: incomplete type is not allowed
          detected during instantiation of "absl::lts_20210324::span_internal::GetDataImpl" based on template argument <tensorflow::TensorShapeProto>
./tensorflow/core/framework/tensor_shape.h(376): here

1 error detected in the compilation of "/tmp/tmpxft_0000b538_00000000-7_resize_nearest_neighbor_op_gpu.cu.compute_70.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/jueonpark/tensorflow/tensorflow/lite/toco/python/BUILD:92:10 C++ compilation of rule '//tensorflow/core/kernels/image:resize_nearest_neighbor_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 216 argument(s) skipped)
INFO: Elapsed time: 37.049s, Critical Path: 22.44s
INFO: 123 processes: 64 internal, 59 local.
FAILED: Build did NOT complete successfully
```

**Comment by sampathweb** [comment]
Also, please note that TF 2.7 only supports Python 3.7-3.9.  So if you are using Python 3.6, I would suggest you use TF 2.6 or upgrade your python env.  Python 3.6 EOL was Dec'2021 (https://endoflife.date/python)

**Comment by JueonPark** [comment]
@sampathweb I tried with Python 3.9.7, yet it fails with the same error.
@mohantym I'll try with the tested configuration and let you know.

**Comment by sampathweb** [comment]
@JueonPark - If you are going to use the suggested configuration, would `pip install tensorflow` not serve your needs?

**Comment by sampathweb** [comment]
CUDA version. needs to be 11.2+, from your config it looks like its 10.1.  So, please see if you can upgrade your local CUDA version to 11.x.  11.2 builds should be compatible with anything 11.x

**Comment by JueonPark** [comment]
The problem was CUDA's version. TF was successfully installed with CUDA version 11.2. Thank you for the help, @mohantym and @sampathweb !!!

**Comment by llv22** [comment]
@JueonPark Hi guy, I'm enabling tensorflow 2.8 on mac 10.13.6 with cuda 10.1, cudnn7.3.6 and meeting with the same issue. After investigating with code logic, I figured out the root cause:

you check the implementation of absl::lts_20210324::span_internal::GetDataImpl in https://github.com/abseil/abseil-cpp/blob/1ae9b71c474628d60eb251a3f62967fe64151bb2/absl/types/internal/span.h#L38, you will find 

```c++
template <typename C>
constexpr auto GetDataImpl(C& c, char) noexcept  // NOLINT(runtime/references)
    -> decltype(c.data()) {
  return c.data();
}
```

this function is used to call typename with remember function data(). with keywords decltype and constexpr auto, the compiler could delegate the instantiation phase for type compatibility check-up, saying whether such type has data() function.

However, the trick lies during the instantiation phase. That is if and only if the typename could be found with detailed declaration, otherwise it will fail.

OK, back to the instantiation phase of our case:

```bash
ERROR: /home/jueonpark/tensorflow/tensorflow/core/kernels/image/BUILD:308:18: C++ compilation of rule '//tensorflow/core/kernels/image:resize_nearest_neighbor_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 216 argument(s) skipped)
external/com_google_absl/absl/types/internal/span.h(38): error: incomplete type is not allowed
          detected during instantiation of "absl::lts_20210324::span_internal::GetDataImpl" based on template argument <tensorflow::TensorShapeProto>
./tensorflow/core/framework/tensor_shape.h(376): here
```
check the implementation of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_shape.h#L375
```c++
  static Status BuildTensorShape(const TensorShapeProto& proto,
                                 TensorShape* out) {
    return BuildTensorShapeBase(proto, out);
  }
```
how does TensorShapeProto generate? it is a sort of proto file (protobuf protocol declaration) which will be converted to pb.h file together with its default implementation based on protobuf protocol.

But there is no declaration in resize_nearest_neighbor_op_gpu.cu.cc to let compile understand its detailed type. 
so like https://github.com/tensorflow/tensorflow/blob/6b7b98fa154d57260337e5e5f929f8907f4b23f1/tensorflow/lite/kernels/shim/tf_tensor_view_test.cc, 
just include 

#include "tensorflow/core/framework/tensor_shape.pb.h" 

to your resize_nearest_neighbor_op_gpu.cu.cc
this issue will be settled down.

PS: Regarding why cuda 11.0+ doesn't have such pain, I guess during compilation resize_nearest_neighbor_op_gpu.cu.pic.d may insert tensor_shape.pb.h in advance, so the class type is ready to use during compilation.

Enjoy your hack anyway. ^-^

**Comment by njzjz** [comment]
I got the same issue when building TensorFlow 2.9 with CUDA 10.1, among a lot of `.cu.cc` files. Finally, I decided to use CUDA 10.2 instead, and the errors disappeared. It's still quite confusing why 10.2 doesn't have this issue.

**Comment by llv22** [comment]
@njzjz actually nvcc has one option [--pre-include file,... (-include)](https://docs.nvidia.com/cuda/archive/10.1/cuda-compiler-driver-nvcc/index.html#file-and-path-specifications-pre-include), so it shouldn't be a big deal to include proto header files. Actually bazel already generates tensorflow/core/framework/tensor_shape.pb.h and include in *.d file, even under cuda 10.1.
Need to check how bazel do compile after hacking successfully for 2.8 and 2.9 on cuda 10.1 macOS
