### ISSUE TITLE
keras layer GRU tflite conversion wrong model

### ISSUE THREAD

**Issue by jimch3n** [tensorflow/tensorflow#54492]
### System information

-   **TensorFlow version (use command below)**:v2.8.0
-   **Python version**: python 3.8

### Describe the problem
To conversion lite model with in GRU model you can found here for example
https://github.com/ARM-software/ML-zoo/blob/master/models/noise_suppression/RNNoise/tflite_int8/rnnoise_INT8.tflite

I found that GRU kernel process r\*wr+i\*wi+bias convert to  tflite is wrong, it's convert to 
two fc ops and ADD  (r\*wr+bias) + (i\*wi+bias) and each biases are the same, so the result bias will be double added.
LSTM has no such problem, it only convert without bias, and add single bias later.

### Source code / logs
N/A

**Comment by sushreebarsa** [comment]
@jimch3n 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
