### ISSUE TITLE
How to Edit the c++ files in TensorFlow？

### ISSUE THREAD

**Issue by Leemy9612** [tensorflow/tensorflow#54497]
I need to change the c++ files in tensorflow, but if I got it by using pip, there has no c++ file in the directory. So how can I edit these files? Or can I just pull tensorflow from github? I tried the command `pip install git+https://github.com/tensorflow/tensorflow.git` , it failed.

**Comment by sushreebarsa** [comment]
@Leemy9612 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
