### ISSUE TITLE
Tensorflow features

### ISSUE THREAD

**Issue by Sukhjitghuman** [tensorflow/tensorflow#545]
If there any difference between Tensorflow installed on Linux machine and Windows machine in terms of features.
If yes, can anyone please list down the features available for both the machine versions.

**Comment by mrry** [comment]
Currently, TensorFlow does not support Windows (except in a Linux docker container), and this is dependent on our build system (Bazel) adding Windows support. You can track issue #17 to see what progress has been made on this front.
