### ISSUE TITLE
AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'EqualGraphDefWrapper'

### ISSUE THREAD

**Issue by Christinele14** [tensorflow/tensorflow#54509]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): The code is from a conda module which is not continually developed.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WSL Ubuntu 20.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from: conda package 
- TensorFlow version (use command below): 2.4.1
- TensorFlow-GPU: 2.4.1
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.6.5
- GPU model and memory: NVIDIA-SMI 510.00 (4GB)

** Description:
This code is developed in Python 3.6 and TF1. Now I want to upgrade it to run in Python 3.7 and TF2. I followed the instructions to migrate TF1 to TF2 (https://www.tensorflow.org/guide/migrate/migrate_tf2) and fix almost all errors except this AttributeError. I am wondering how to fix it or do we have similar functions to compare graphs in TF2. Thank you. 

**Code:
@pytest.mark.parametrize('conv_patch', (2, 5, 10), ids=lambda x: 'c=%s' % x)
@pytest.mark.parametrize('pool_patch', (2, 3), ids=lambda x: 'p=%s' % x)
def test_convolve3D(conv_patch, pool_patch):
    from tfbio.net import hidden_conv3D, convolve3D

    out_chnls = [8, 16]

    g1 = tf.Graph()
    with g1.as_default():
        x = tf.compat.v1.placeholder(tf.float32, shape=(None, 21, 21, 21, 19))
        h11 = hidden_conv3D(x, out_chnls[0], conv_patch=conv_patch,
                            pool_patch=pool_patch, name='conv0')
        h12 = hidden_conv3D(h11, out_chnls[1], conv_patch=conv_patch,
                            pool_patch=pool_patch, name='conv1')
    def1 = g1.as_graph_def().SerializeToString()

    g2 = tf.Graph()
    with g2.as_default():
        x = tf.compat.v1.placeholder(tf.float32, shape=(None, 21, 21, 21, 19))
        h2 = convolve3D(x, out_chnls, conv_patch=conv_patch,
                        pool_patch=pool_patch)
    def2 = g2.as_graph_def().SerializeToString()

    # graphs should be identical
    assert not pywrap_tensorflow.EqualGraphDefWrapper(def1, def2)

**Describe the current behavior**
FAILED net_test.py::test_convolve3D[p=2-c=2] - AttributeError: module 'tensorflow.python.pywrap_tensorflow' has no attribute 'EqualGraphDefWrapper'

**Describe the expected behavior**
Pass the pytest

**Comment by gadagashwini** [comment]
@Christinele14,
 Equivalent  of `EqualGraphDefWrapper` in Tensorflow 2.x is 

```
from tensorflow.python.client import pywrap_tf_session
 diff = pywrap_tf_session.EqualGraphDefWrapper(actual.SerializeToString(),
                                                expected.SerializeToString())
```

**Comment by Christinele14** [comment]
> @Christinele14, Equivalent of `EqualGraphDefWrapper` in Tensorflow 2.x is
> 
> ```
> from tensorflow.python.client import pywrap_tf_session
>  diff = pywrap_tf_session.EqualGraphDefWrapper(actual.SerializeToString(),
>                                                 expected.SerializeToString())
> ```

Thank you so much! It solved my problem. I will close my issue here.
