### ISSUE TITLE
tf.argmax() function and documentation inconsistent with numpy.argmax() implementation

### ISSUE THREAD

**Issue by anyaconda** [tensorflow/tensorflow#54506]
--Issue. 
`tensorflow` documentation and implementation of `argmax()`  threw me off.  
`tensorflow` starts with the same definition as `numpy` when it comes to the  'axis' parameter.

#src: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
numpy.argmax(a, **axis=None**, out=None, *, keepdims=<no value>)

#src: https://www.tensorflow.org/api_docs/python/tf/math/argmax
tf.math.argmax( input, **axis=None**, output_type=tf.dtypes.int64, name=None)
However, the documentation down the page shows that `axis` really defaults to 0.
<html>
<body>

axis | An integer, the axis to reduce across. Default to 0.
-- | --

</body>
</html>

The code results differ between `numpy` and `tensorflow`.

--Proposition
If this is a feature and not a bug in `tensorflow`, let's have a consistent documentation.  If it should behave like `numpy`, let's correct the code and by default return a scalar.  (or let me know if this has been already addressed in a later version). 

--Reproducible code samples:

a) with `numpy`
A = np.array([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8], 
                 [14, 45, 23, 5, 27]])
print(np.argmax(A, 0))
print(np.argmax(A, 1))
print(np.argmax(A, None))

Returns:
[2 2 0 2 2]
[2 2 1]
11

b) with `tensorflow`
B = tf.constant([[2, 20, 30, 3, 6], 
                 [3, 11, 16, 1, 8], 
                 [14, 45, 23, 5, 27]])
print(tf.math.argmax(B, 0))
print(tf.math.argmax(B, 1))
print(tf.math.argmax(B, None))

Returns:
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)

**Comment by Cheril311** [comment]
@anyaconda I believe the case when axis is None is missing, will fix this

**Comment by sushreebarsa** [comment]
@anyaconda 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by jvishnuvardhan** [comment]
@anyaconda I think this is intended behavior. 

In case of numpy, it clearly mentions that if `axis` arg is not provided, then by default, it will be flattened and find `argmax`.

```
axis : int, optional
    By default, the index is into the flattened array, otherwise
along the specified axis.
```

In case of TF, if `axis` parameter is not provided, then by default, it sets axis=0

` axis: An integer, the axis to reduce across. Default to 0.`

Please let me know if I miss anything. Thanks!

**Comment by sushreebarsa** [comment]
@anyaconda Could you please update as per the above [comment](https://github.com/tensorflow/tensorflow/issues/54506#issuecomment-1055121497https://github.com/tensorflow/tensorflow/issues/54506#issuecomment-1055121497)? Thanks!

**Comment by anyaconda** [comment]
@[jvishnuvardhan](https://github.com/jvishnuvardhan)
thank you for the explanation.  i will try to remember that the behavior is intended to be different between `numpy` and `tensorflow`.  i wish it was consistent - imho `numpy` is a standard for many developers and data scientists.

**Comment by rohan100jain** [comment]
Does tf.experimental.numpy.argmax work?

**Comment by Cheril311** [comment]
@rohan100jain tf.experimental.numpy.argmax works
