### ISSUE TITLE
"std::string is no longer a scalar type, use tensorflow::tstring"

### ISSUE THREAD

**Issue by Thomnt2306** [tensorflow/tensorflow#54511]
I use python 3.9 and have successfully built tensorflow 2.7 on Windows, But when I build my own code with tensorflow, I get the error as below, please help, thanks!
![image](https://user-images.githubusercontent.com/49086407/155453100-f6558009-306d-4aa7-a0b6-e2f6644717f9.png)

**Comment by tilakrayal** [comment]
@Thomnt2306 ,
Can you please take a look at this [link](https://github.com/tensorflow/tensorflow/issues/43150) with the similar error.It helps.Thanks!

**Comment by Thomnt2306** [comment]
> @Thomnt2306 , Can you please take a look at this [link](https://github.com/tensorflow/tensorflow/issues/43150) with the similar error.It helps.Thanks!

hi, I followed your instructions and it didn't solve the error, do you have any other solution?

**Comment by tilakrayal** [comment]
@Thomnt2306 ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.
