### ISSUE TITLE
SavedModel guide shows raw Jupyter code instead of HTML

### ISSUE THREAD

**Issue by nss-ysasaki** [tensorflow/tensorflow#54512]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/guide/saved_model

### Clear description

The above URL shows raw Jupyter notebook code, instead of HTML (as in other pages in the documentation)

### Correct links

-

### Parameters defined

-

### Returns defined

-

### Raises listed and defined

-

### Usage example

-

### Request visuals, if applicable

-

### Submit a pull request?

-

**Comment by sushreebarsa** [comment]
@nss-ysasaki This should be fixed now.Could you please check ,and confirm the same ?Thanks!

![5hwkKZaXrcySvZA](https://user-images.githubusercontent.com/84765720/155476991-43acca82-2b00-4396-a83f-b0961f3c7442.png)

**Comment by nss-ysasaki** [comment]
Looks good now!

**Comment by sushreebarsa** [comment]
@nss-ysasaki Thank you for raising this issue.
Glad it is working fine now.Thanks!

**Comment by sushreebarsa** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
