### ISSUE TITLE
failed: (Exit 2): cl.exe failed: error executing command，Bazel=5.0.0, tf=2.8.0,MSVC2019

### ISSUE THREAD

**Issue by Leemy9612** [tensorflow/tensorflow#54516]
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: F:/tensorflow/tensorflow/core/framework/BUILD:1400:31 Middleman _middlemen/_S_Stensorflow_Score_Sframework_Cattr_Uvalue_Uproto_Utext-BazelCppSemantics_build_arch_x64_windows-opt failed: (Exit 2): cl.exe failed: error executing command
  cd /d C:/users/manyuan/_bazel_manyuan/2qttxlm7/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/JetBrain/python/python.exe
    SET PYTHON_LIB_PATH=D:/JetBrain/python/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\manyuan\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\manyuan\AppData\Local\Temp
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/tensorflow/core/platform/windows/_objs/platform_port/port.obj.params
# Configuration: 93a4c43a10f53f2edc71827668aaf369d1f071b1a7a163cf0701c8d4b7b35e12
# Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 17.366s, Critical Path: 8.04s
INFO: 65 processes: 26 internal, 39 local.
FAILED: Build did NOT complete successfully

**Comment by Leemy9612** [comment]
I've tried change the version of bazel , but it not works.

**Comment by Leemy9612** [comment]
My python version is 3.10 , and the blow is all my configure.


F:\tensorflow>python ./configure.py
You have bazel 5.0.0 installed.
Please specify the location of python. [Default is D:\JetBrain\python\python.exe]:


Found possible Python library paths:
  D:\JetBrain\python\lib\site-packages
Please input the desired Python library path to use.  Default is [D:\JetBrain\python\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.

F:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
Starting local Bazel server and connecting to it...

**Comment by Leemy9612** [comment]
After the configuration, I execute the command `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Comment by sushreebarsa** [comment]
@Leemy9612 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by Leemy9612** [comment]
I already finish the template ....#54578

**Comment by sushreebarsa** [comment]
@Leemy9612 Thank you for the update! 
We can see that you have raised another ticket as per the above [comment](https://github.com/tensorflow/tensorflow/issues/54516#issuecomment-1050750670) .So,closing this issue as we will track the other ticket.Thanks!
