### ISSUE TITLE
Links to some of the guides are broken

### ISSUE THREAD

**Issue by ganesh-vgp** [tensorflow/tensorflow#54513]
Links to [guide/basics](https://www.tensorflow.org/guide/basics), [guide/autodiff](https://www.tensorflow.org/guide/autodiff), [guide/basic_training_loops](https://www.tensorflow.org/guide/basic_training_loops), [guide/keras/functional](https://www.tensorflow.org/guide/keras/functional), [guide/keras/train_and_evaluate](https://www.tensorflow.org/guide/keras/train_and_evaluate), [guide/keras/rnn](https://www.tensorflow.org/guide/keras/rnn), [guide/keras/transfer_learning](https://www.tensorflow.org/guide/keras/transfer_learning), [guide/advanced_autodiff](https://www.tensorflow.org/guide/advanced_autodiff), [guide/tf_numpy](https://www.tensorflow.org/guide/tf_numpy), [guide/data](https://www.tensorflow.org/guide/data), [guide/data_performance](https://www.tensorflow.org/guide/data_performance) and [guide/saved_model](https://www.tensorflow.org/guide/saved_model) are broken. They are responding with .ipynb files.

Please look into it.

**Comment by mohantym** [comment]
Hi @ganesh-vgp ! There is a ongoing maintenance on the website.Team has been already informed about it.  Thank you!

**Comment by mohantym** [comment]
@ganesh-vgp ! Can you please try the above links again?

**Comment by ganesh-vgp** [comment]
Now the links are working fine. Thanks!

**Comment by mohantym** [comment]
Ok @ganesh-vgp ! Closing this issue as it has been resolved now. Thanks!
