### ISSUE TITLE
tensorflow/core/util/event.proto: File not found while building with custom C++ project

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#5453]
I'm building tensorflow inside a C++ project and link with it using bazel build script. I'm using the master version of tensorflow and here a the BUILD file 

```
cc_library(
    name = "tf-net",
    hdrs = ["model.h"],
    srcs = [
        "model.cc",
    ],
    linkopts = ["-lm"],
    deps = [
        "@org_tensorflow//tensorflow/core:core_cpu",
        "@org_tensorflow//tensorflow/core:lib",
        "@org_tensorflow//tensorflow/core:tensorflow"
    ],
	visibility=["//visibility:public"]
)
```

This worked for previous version of tensorflow but now I get 
```
tensorflow/core/util/event.proto: File not found.
tensorflow/core/debug/debug_service.proto: Import "tensorflow/core/util/event.proto" was not found or had errors.
tensorflow/core/debug/debug_service.proto:38:25: "Event" is not defined.
```

It seems that it tries to compile the proto file debug_service.proto but can't find the needed dependencies.

**Comment by sherrym** [comment]
Could you please add dependency to @org_tensorflow//tensorflow/core:protos_all?

We have probably moved thing around.

Sherry

**Comment by JosiahKane** [comment]
I have the same problem in a similar situation (though without the assurance that it used to work).
Adding the dependency on protos_all does not resolve it. (It can't find protos_all and suggests protos_all_cc but that doesn't help either) 

After a little digging, I note that in the file
tensorflow/core/debug/BUILD
there is a line (85) which currently reads
":debug_service_proto_cc",  # TODO(cais): Confirm safe.

It seems that this line, and the whole debug_service_proto changeset, have been added, reverted, and unreverted over the last couple of months, and simply commenting out that line allows my build to complete. 

I do not fully appreciate what that code does and am not suggesting this as a fix, (although for jrabary it might suffice as a workaround, infering that they are like me not using Cuda) but it may be useful for working out what a fix would look like.

**Comment by girving** [comment]
@caisq Can you comment based on the "Confirm safe" TODO?

**Comment by JosiahKane** [comment]
In my project the problem has disappeared with the newest head (having restored the line I mentioned commenting out) 
I don't know whether @jrabary has the same experience.

**Comment by caisq** [comment]
@girving The "Confirm safe" TODO is now obsolete and will be removed on the next successful push from internal. @jrabary, does the problem persist if you use use the latest master HEAD?

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
