### ISSUE TITLE
Bug in `tf.math.acos`: `string` input is not supported

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54545]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/math/acos?hl=en

### Parameters defined
Doc says `x` must be one of the following types: bfloat16, half, ..., **string**, but obviously the input to `tf.math.acos` cannot be a `string` Tensor.

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!
