### ISSUE TITLE
dist_test local k8s cluster setup is broken, use kubernetes/minikube

### ISSUE THREAD

**Issue by r2d4** [tensorflow/tensorflow#5462]
**Feature Request/Documentation Request**

local k8s cluster dist_test broken, use [kubernetes/minikube](https://github.com/kubernetes/minikube) instead

As of commit 21a7ae05e04f4f060938db08015cb47896970dd1, the dockerfile for setting up a local cluster for dist_test is broken.  This dockerfile imports start_local_k8s_service.sh and other scripts that were deleted with this merge.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/local/Dockerfile#L18
```
$ docker build .
...
Step 9 : ADD start_local_k8s_cluster.sh /var/k8s/start_local_k8s_cluster.sh
lstat start_local_k8s_cluster.sh: no such file or directory
...
```

Instead of this dockerfile, this local cluster setup should be switched over to Minikube, the officially supported method for non-k8s-development local clusters.

http://kubernetes.io/docs/getting-started-guides/minikube/

As a maintainer for minikube, I would happily create a PR with instructions and a tutorial on how to run dist_test locally.  If this sounds good to you, please assign this issue to me.

**Comment by r2d4** [comment]
cc @elibixby @dlorenc

**Comment by girving** [comment]
@mrry Can you comment?

**Comment by mrry** [comment]
My guess is this should be "contributions welcome", although we should check with @caisq, who created the test in the first place.

**Comment by elibixby** [comment]
This is definitely the way to go long term IMO. I'm wondering if it would be worth having a separate repo to store all the third-party (including k8s) tooling around running distributed TF. Useful configs, etc.

**Comment by mrry** [comment]
@elibixby Perhaps https://github.com/tensorflow/ecosystem would be the right place? There's already [some k8s content](https://github.com/tensorflow/ecosystem/tree/master/kubernetes) in that repo.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
