### ISSUE TITLE
Where is  "from tensorflow.python.keras.layers.normalization import LayerNormalization" in ther repository

### ISSUE THREAD

**Issue by Mather10** [tensorflow/tensorflow#54637]
It seems that tensorflow/python/keras/layers/__init__.py does not have a line "from tensorflow.python.keras.layers.normalization import LayerNormalization", but why the error

```
tensorflow/python/keras/layers/__init__.py](https://localhost:8080/#) in <module>()
    144 
    145 # Normalization layers.
--> 146 from tensorflow.python.keras.layers.normalization import LayerNormalization
    147 from tensorflow.python.keras.layers.normalization_v2 import SyncBatchNormalization
    148 

ImportError: cannot import name 'LayerNormalization' from 'tensorflow.python.keras.layers.normalization'
```

occur? Thanks.

**Comment by mohantym** [comment]
Hi @Mather10 !
Could you please update the template too as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by sampathweb** [comment]
@Mather10 - You may want to use 
```
from tensorflow.keras.layers import LayerNormalization
```
