### ISSUE TITLE
expand support for image file types (primarily TIFF)

### ISSUE THREAD

**Issue by wihobbs** [tensorflow/tensorflow#54648]
This issue requests support for TIFF images when using TensorFlow for image processing research.

**System information**
- TensorFlow version (you are using): 2.8.0 available via Colab: Python 3 Google Compute Engine backend (GPU)
- Are you willing to contribute it (Yes/No): I'm willing to help but looking for high-level suggestions on how to implement this. Feel free to assign me with a mentor.

**Describe the feature and the current behavior/state.**
Currently, TensorFlow only supports a limited number of image filetypes. This should be expanded for both convenience and data uses of users who require other image filetypes.

**Will this change the current api? How?**
Maybe? The current image decoder would have to be updated to read TIFF filetypes. ~No commands would have to change.~ A `tf.io.decode_jpeg(sample_image)` equivalent would have to be added.

**Who will benefit with this feature?**
This feature would benefit domain science users who rely on TIFF image types for microscopy images, among other uses.

**Any Other info.**
Traceback on Error if running TIFF image filetype is shown below. Even if I change the filetype to JPEG, if the image was originally TIFF I get this error.

```python
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-4-940ee08e0488>](https://localhost:8080/#) in <module>()
      2 
      3 
----> 4 sample_image = tf.io.decode_jpeg(sample_image)
      5 print(sample_image.shape)

2 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required. [Op:DecodeJpeg]
```

**Comment by wihobbs** [comment]
Also referencing https://github.com/tensorflow/tensorflow/issues/13583 since it's relevant to this issue.

**Comment by tilakrayal** [comment]
@wihobbs ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!

**Comment by wihobbs** [comment]
```python
sample_image = tf.io.read_file(str('/content/drive/MyDrive/1737/1737-01.tif'))


sample_image = tf.io.decode_jpeg(sample_image)
print(sample_image.shape)
```

There is no `decode_tiff` or equivalent AFAIK and the error message from this is displayed in the original issue.

**Comment by yongtang** [comment]
@wihobbs tensorflow-io package consists of decode_tiff:
https://www.tensorflow.org/io/api_docs/python/tfio/experimental/image/decode_tiff

**Comment by chunduriv** [comment]
@wihobbs,

Yes, you can use [decode_tiff](https://www.tensorflow.org/io/api_docs/python/tfio/experimental/image/decode_tiff). Please find the [gist](https://colab.research.google.com/gist/chunduriv/b811176f7e2d9f6fe4a9031d125c2b72/54648.ipynb) here for reference.

```
import tensorflow as tf
import tensorflow_io as tfio

sample_image = tf.io.read_file(str('/content/at3_1m4_01.tif'))

sample_image= tfio.experimental.image.decode_tiff(
    sample_image, index=0, name=None
)
print(sample_image.shape)

Output:
(480, 640, 4)
```
Thanks!

**Comment by wihobbs** [comment]
I saw the `decode_tiff` function as part of the `tfio` library. Can this be incorporated into the main TensorFlow repo? This would prevent Google Colab users from having to install additional libraries for their codes.

**Comment by yongtang** [comment]
@wihobbs As tensorflow main repo is getting too big (and take a long time to complie), the plan has been to only keep minimal format types to tensorflow repo and keep other formats in tensorflow-io.

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
