### ISSUE TITLE
Autograph 

### ISSUE THREAD

**Issue by Idanzinner** [tensorflow/tensorflow#54654]
AutoGraph could not transform <function TFDS.<locals>.select_from at 0x7fb3dc34d050> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Comment by sushreebarsa** [comment]
@Idanzinner 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sushreebarsa** [comment]
@Idanzinner Please refer to the similar [issue 1](https://stackoverflow.com/questions/65813263/how-to-suppress-warningtensorflowautograph-could-not-transform-bound-method), [issue2](https://stackoverflow.com/questions/62931610/warningtensorflowautograph-could-not-transform-function-format-example-at) and let us know if it helps?Thanks!
