### ISSUE TITLE
BERT guide in tensorflow.org works differently(not converging)

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#54655]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/

https://www.tensorflow.org/text/tutorials/classify_text_with_bert

## Description of issue (what needs changing):

not converging

### Clear description

For example, why should someone use this method? How is it useful?

works differentlly

### Correct links

https://www.tensorflow.org/text/tutorials/classify_text_with_bert

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

yes

### Returns defined

Are return values defined?

yes

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

N/A

### Usage example

Is there a usage example?

![image](https://user-images.githubusercontent.com/4515120/155879988-294e8af7-9022-4187-b748-5f72a8bc5c7f.png)

![image](https://user-images.githubusercontent.com/4515120/155880012-ffac1736-032e-4f79-aa37-2f3c0ae38308.png)

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by alanpurple** [comment]
windows 11 x64
cuda 11.6/ cudnn 8.3.2

tensorflow 2.8.0

**Comment by chunduriv** [comment]
@alanpurple,

I am able to run the tutorial and the model converge properly. Please refer the [gist](https://colab.research.google.com/gist/chunduriv/7330d14a3be2eaffaff0aace28e7039a/54655.ipynb) for reference.

![image](https://user-images.githubusercontent.com/74177924/155974637-9ca08a86-623c-41da-be50-0a2624e0fe18.png)

Can you please elaborate about your issue? Thanks!

**Comment by alanpurple** [comment]
@chunduriv 

It's very strange I have another PC which has Windows 11, Intel i5 9600k and RTX2060, but works same as guide

but my main pc which has Windows11, AMD Ryzen 5900x and RTX3090 works differently as above

both has CUDA 11.6 and cudnn 8.3.2  ( also tested cuda 11.5 and 11.4 )

**Comment by alanpurple** [comment]
@chunduriv 

sorry, my bad.... I forgot "trainable=True"

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
