### ISSUE TITLE
TFLite conversion works in TF 2.8 / fails in 2.7.1, both produce large file sizes and incorrect input size of 1x1x1x3

### ISSUE THREAD

**Issue by cstamatopoulos** [tensorflow/tensorflow#54659]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip install 
- TensorFlow library (version, if pip package or github SHA, if built from source): test 2.7.1 and 2.8

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

TensorFlow 2.8
https://colab.research.google.com/drive/1uYZOrPJWbSGfhf-DYEgMtCVmy5xLBE5G?usp=sharing
TensorFlow 2.7.1
https://colab.research.google.com/drive/15kzXMSF2olfzNskYN99WKq7DarUy-3tj?usp=sharing

### 3. Failure after conversion

Used ssd_resnet101_v1_fpn_640x640_coco17_tpu-8 from model zoo to train a custom model since SSD models are supported in TF lite conversion. Exported the model using 'exporter_main_v2.py' from model zoo repo and the saved model was 16 Mb.

All TFLite models incorrectly have an input size of 1x1x1x3

TF 2.8 converts all 3 different quantizations tested (see relevant colab)
TF Lite Dynamic Range file size is 73.5 Mb
TF Lite Int with float fallback file size is 267.7 Mb
TF lite Full integer quantization file size is 271.2 Mb

TF 2.7.1 integer quantization fails with
Failed to quantize: <unknown>:0: error: loc("Postprocessor/Slice;Postprocessor/Slice"): 'tfl.slice' op quantization parameters violate the same scale constraint: !quant.uniform<i8:f32, 2.5953195290639997E-4:-128> vs. !quant.uniform<i8:f32, 0.0011857558274641633:-128>

### 5. (optional) Any other info / logs

For the large file size generation I have also commented over at #54405 as well but I created new issue for the incorrect input size and failure of conversion for 2.7.1

I also tried using the 'export_tflite_graph_tf2.py' (not sure if that is what I should be using) to export my saved model which seems to correctly generate the input signature of 1,640,640,3 though I am not sure about the generated tflite yet but the converted tflite files are still 70 Mb.

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to reproduce the issue on colab using TF v[2.7.1](https://colab.research.google.com/gist/sushreebarsa/af58b398f4910d5f3e66ed30831a8a13/tflite-conversion-with-tf-2-7-1.ipynb) and [2.8.0](https://colab.research.google.com/gist/sushreebarsa/f43a4b1e926a200bd38066d55ab57e6d/tflite-conversion.ipynb) .Please find the attached gists.Thanks!

**Comment by cstamatopoulos** [comment]
I also have a colab that allows one to easily test the conversion of the models available in the model zoo
https://colab.research.google.com/drive/1nHWL9MaZ-em6gfKC8fBP4RnS9nQq4ZyP#scrollTo=aLZGB8dsH1iD

It allows you to quickly change the model name in the forms of tar.gz that are over at the model zoo along with the image input size and test that output of the conversion. Similar issue with the large file size can be seen there as well.

The 'export_tflite_graph_tf2.py' is used to export the graph as that seems to be the correct way to do it which also fixed the input signature as already mentioned.

**Comment by karimnosseir** [comment]
@cstamatopoulos I used the colab in your latest comment.
1) I don't see the shape issue, can you explain how i can find it ?

2) For the large files, i think you are missing few things:
 
 a) saved_model.pb stores the actual graph, but it doesn't store the variables or assets. Variables are stored in variables directory in the checkpoint format. 
 TFLite have everything in the .tflite file, which means the variables values (either frozen or initialized as variables) are present inside the TFLite file.
 
  b) TFLite converter optimizes the graph for inference latency, this means that in many cases if an op value can be inferred during conversion we will do this and fold the results as constant tensors in the graph to be used by dependent layers. This means that the amount of data in the file can be bigger than TF equivalent.
  
  Let me know if you have any questions.

Thanks

**Comment by cstamatopoulos** [comment]
@karimnosseir The latest colab uses a different command to export the saved model.
Namely "export_tflite_graph_tf2.py" vs "exporter_main_v2.py" from the model zoo.
Documentation is a bit unclear as the documentation for tf lite says that all that is needed a saved model and there are various posts about setting the fixed size and re-saving the model as I show below which does not work.
"export_tflite_graph_tf2.py" seems to do the trick

If you notice in the first 2 colabs you will see that 
`'shape': array([1, 1, 1, 3]` 
even though I am saving the model as advised with an input size
`model = tf.saved_model.load(tfmodel_path)
        model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 640, 640, 3])
        tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])`

I can provide the same input data to tf lite model maker and I get a model for efficientdet_lite3 that is around 12Mb.
Maybe that is not fair comparison as as you say the size of the model variables is what matters.
I was initially using TF 2.7.1 that was generating files that were 270 Mb.
Then I tested 2.8 and it was 70 Mb so it made me skeptical.

**Comment by karimnosseir** [comment]
I see them now, thanks.

So this is working as expected. Let me explain the output to you
```
{'name': 'serving_default_input_tensor:0', 'index': 0, 'shape': array([1, 1, 1, 3], dtype=int32), 'shape_signature': array([ 1, -1, -1,  3], dtype=int32)
```

There are 2 parts that have shape, shape and shape_signature
- shape: Is the default shape of the tensor, IOW if you just decided to load the model and run this is the shape of the tensor.
So what is shape_signature then
- shape_signature: Is similar to shape but instead might have some dimensions labeled with -1, these dimensions are the dimensions that are dynamic and can be resized.

That means that the model you are converting has shape [1, None, None, 3] and TFLite honor this and you can resize the 'None' dimensions at runtime.

Hope it is more clear now.

Thanks

**Comment by sachinprasadhs** [comment]
Hi, Could you please refer the above comment which should clarify your confusion.
In addition to that could you please refer the document here https://www.tensorflow.org/lite/guide/signatures which explains the **Signatures in Tensorflow Lite** for `Inputs`, `Outputs` and `Signature Key`.
