### ISSUE TITLE
Please remove invalid hyperlinks.

### ISSUE THREAD

**Issue by praksharma** [tensorflow/tensorflow#54660]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/guide/migrate/upgrade

## Description of issue (what needs changing):
There is a link but the domain is for sell.

### Clear description
In the very end.
Check out [tf2up.ml](http://tf2up.ml/) for a convenient tool to upgrade Jupyter notebooks and Python files in a GitHub repository.
This link is not working anymore.

### Correct links
https://github.com/lc0/tf2up

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by mohantym** [comment]
Thanks @praksharma for reporting the issue. made a PR[ #2040](https://github.com/tensorflow/docs/pull/2040) to address this issue.

**Comment by mohantym** [comment]
@praksharma ! Closing this issue as above PR has been merged now. Thanks!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
