### ISSUE TITLE
After finetuning a BERT model max_position_embeddings=128, my saved model is not reflecting the smaller sequence length

### ISSUE THREAD

**Issue by SohaK** [tensorflow/tensorflow#54687]
I used to fine-tune BERT with tf1 with original BERT code, now that I am using tf-models-official, although I change max_position_embedding, my saved model file doesn't change. Previously when I limit max_seq_length and saved model with the associated signature (with the same max_seq_length) my saved model would be smaller. Here in tf-models-official I don't need to explicitly pass a signature, so the only place that l put limitation is in max_position_embedding. The problem is my saved model is bigger than I expected.

**Comment by mohantym** [comment]
Hi @SohaK ! 
Could you please update the template too as it helps us analyse the [issue](https://github.com/tensorflow/tensorflow/issues/new/choose) [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced].Thanks!

**Comment by SohaK** [comment]
TF version: 2.7

I am almost following https://www.tensorflow.org/text/tutorials/fine_tune_bert but with my own BERT model and data

bert_config: {'hidden_size': 512,
 'hidden_act': 'gelu',
 'initializer_range': 0.02,
 'vocab_size': 47644,
 'hidden_dropout_prob': 0.1,
 'num_attention_heads': 8,
 'type_vocab_size': 2,
 'max_position_embeddings': 128,
 'num_hidden_layers': 12,
 'intermediate_size': 2048,
 'attention_probs_dropout_prob': 0.1,
 'max_seq_length': 128}


with tf.saved_model.save(reloaded, export_dir=export_dir) I get the variables and pb files the variable file are 753 MB, but I expected to be 251 MB (based on older versions on TF1), the saved_model.pb is 4.65 MB while on TF1 I used to get 764kB.
with bert_classifier.save(export_dir, include_optimizer=False), I get the variables with the size I expect, and I get two pb files: saved_model.pb and keras_metadata.pb the saved_model.pb is 3.99 MB.

Do these different saved models affect the runtime behavior and speed?

**Comment by SohaK** [comment]
Also
bert_classifier = tf.saved_model.load(import_dir)
bert_classifier.summary()
on both way of saving gives me

'_UserObject' object has no attribute 'summary'

**Comment by gadagashwini** [comment]
@SohaK, When i tried to save the Fine_tune_bert model with same configuration as you mentioned, it has only one .pb file `saved_model.pb`. Size of the model ~3.4MB. 

Use keras load model to load your model.
```
from tensorflow import keras

new_model = keras.models.load_model("save_model_keras")
new_model.summary()
```

**Comment by SohaK** [comment]
@gadagashwini I also need to be able to reload a bert classifier_model checkpoint to retrain further, but when I do:

bert_classifier, bert_encoder = bert.bert_models.classifier_model(bert_config, num_labels=2)
checkpoint = tf.train.Checkpoint(model=bert_classifier)
checkpoint.read(os.path.join(path +'/model00000001.ckpt/variables/', 'variables')).assert_existing_objects_matched()

I get this error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-19-6fad2876f6ee> in <module>
      1 checkpoint = tf.train.Checkpoint(model=bert_classifier)
      2 checkpoint.read(
----> 3     os.path.join(efs_path +"AF2022/model00000001.ckpt/variables/", 'variables')).assert_existing_objects_matched()

~/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py in assert_existing_objects_matched(self)
    845       num_variables_to_show = min(10, num_unused_python_objects)
    846       raise AssertionError(
--> 847           f"Found {num_unused_python_objects} Python objects that were "
    848           "not bound to checkpointed values, likely due to changes in the "
    849           f"Python program. Showing {num_variables_to_show} of "

AssertionError: Found 201 Python objects that were not bound to checkpointed values, likely due to changes in the Python program. Showing 10 of 201 unmatched objects: [<tf.Variable 'transformer/layer_5/output/kernel:0' shape=(2048, 512) dtype=float32, numpy=...

**Comment by gadagashwini** [comment]
@SohaK, Could you share complete code to reproduce the issue. Thanks!

**Comment by SohaK** [comment]
@gadagashwini  This is the complete code:

!pip install tensorflow==2.8
!pip install -U tensorflow-text==2.8
!pip install tf-models-official==2.7


import os
import json

import numpy as np
import tensorflow as tf

from official.nlp import bert
from official import nlp

# Load the required submodules
import official.nlp.optimization
import official.nlp.bert.run_classifier


efs_path = # a path
data_path =  efs_path + # a path

gs_folder_bert = efs_path + # a path
tf.io.gfile.listdir(gs_folder_bert)

bert_config_file = os.path.join(gs_folder_bert, "bert_config.json")
config_dict = json.loads(tf.io.gfile.GFile(bert_config_file).read())

bert_config = bert.configs.BertConfig.from_dict(config_dict)

bert_classifier, bert_encoder = bert.bert_models.classifier_model(
    bert_config, num_labels=2)

train_data_output_path="./AF_NQ_train.tf_record"
eval_data_output_path="./AF_NQ_eval.tf_record"

max_seq_length = 128
batch_size = 32
eval_batch_size = 32

training_dataset = bert.run_classifier.get_dataset_fn(
    train_data_output_path,
    max_seq_length,
    batch_size,
    is_training=True)()

evaluation_dataset = bert.run_classifier.get_dataset_fn(
    eval_data_output_path,
    max_seq_length,
    eval_batch_size,
    is_training=False)()



# Set up epochs and steps
epochs = 1
batch_size = 32
eval_batch_size = 32

TRAIN_SIZE = # a number
train_data_size = TRAIN_SIZE
steps_per_epoch = int(train_data_size / batch_size)
num_train_steps = steps_per_epoch * epochs
warmup_steps = int(epochs * train_data_size * 0.1 / batch_size)

# creates an optimizer with learning rate schedule
optimizer = nlp.optimization.create_optimizer(
    2e-5, num_train_steps=num_train_steps, num_warmup_steps=warmup_steps)



checkpoint = tf.keras.callbacks.ModelCheckpoint('model{epoch:08d}_test.ckpt', save_freq=steps_per_epoch, save_format="tf") 
log = tf.keras.callbacks.TensorBoard(log_dir='./logs',update_freq=10)
metrics = [tf.keras.metrics.SparseCategoricalAccuracy('accuracy', dtype=tf.float32)]
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

bert_classifier.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=metrics)

bert_classifier.fit(
      training_dataset,
      validation_data=evaluation_dataset,
      batch_size=32,
      steps_per_epoch=steps_per_epoch,
      epochs=epochs,
      callbacks=[checkpoint, log])



export_dir='./AF_128_NQ_3'
tf.saved_model.save(bert_classifier, export_dir=export_dir)

import_dir="./AF_128_NQ_3"
bert_classifier = tf.keras.models.load_model(import_dir)


---------------------------------------------------------------------------------------------------------------------------------
WARNING:absl:Found untraced functions such as dropout_5_layer_call_fn, dropout_5_layer_call_and_return_conditional_losses, logits_layer_call_fn, logits_layer_call_and_return_conditional_losses, self_attention_layer_call_fn while saving (showing 5 of 364). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: ./AF_128_NQ_3/assets
INFO:tensorflow:Assets written to: ./AF_128_NQ_3/assets
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1252/896310302.py in <module>
      3 
      4 import_dir="./AF_128_NQ_3"
----> 5 bert_classifier = tf.keras.models.load_model(import_dir)

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    627     self._self_setattr_tracking = False  # pylint: disable=protected-access
    628     try:
--> 629       result = method(self, *args, **kwargs)
    630     finally:
    631       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'

**Comment by gadagashwini** [comment]
@SohaK, Thanks for providing code to reproduce. Could you please provide the required documents like Json and dataset file. Thanks!

**Comment by gadagashwini** [comment]
@SohaK,
When i tried to save the [Fine_tune_bert model](https://www.tensorflow.org/text/tutorials/fine_tune_bert) with same configuration as you mentioned, it has only one .pb file saved_model.pb. Size of the model ~3.3MB.
If you are customising the model and training it again. Make sure you have the same size data set. Thanks!
