### ISSUE TITLE
Any plans for TF to support FP16&INT8?

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#5468]
nVidia releases P100, P4, and P40 GPUs, and it also releases TensorRT for inference to support FP16 and INT8. Any plans for TensorFlow?

**Comment by sherrym** [comment]
Benoit, could you please comment? Thanks.

**Comment by Randl** [comment]
Any update on this?

**Comment by yaroslavvb** [comment]
dup of https://github.com/tensorflow/tensorflow/issues/4589

**Comment by Randl** [comment]
@yaroslavvb AFAIK, there is no full support of even non-native INT8 operations, and https://github.com/tensorflow/tensorflow/issues/4589 talks only about FP16

**Comment by tfboyd** [comment]
I am tracking #4589 and will provide updates until FP16 is in decent shape.  With out Volta it is hard to test real performance but that will happen soon.
