### ISSUE TITLE
tf.saved_model.save is very slow if a tf.function contains an onnx model

### ISSUE THREAD

**Issue by wkema** [tensorflow/tensorflow#54681]
I can successfully convert a pretrained Pytorch model into the onnx format and export to a Tensorflow proto file. I can load this file in Tensorflow, add some preprocessing/postprocessing steps and pack them into a `tf.function`. Everything works fine. Now it is very slow if I want to use `tf.saved_model.save` to save this new tf.function.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 4.19
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.11
- CUDA/cuDNN version: 11.3
- GPU model and memory: 2 NV TESLA K80 GPUs, 2x12GB 

**Describe the current behavior**
It took 500+ sec to save a simple resnet18, 7000+ sec to save a resnet34, and more than 40 hours to save a resnet50 in the following toy example.
Not sure why this process is so slow or I did something wrong.

**Describe the expected behavior**
Hopefully it could be faster.

**Standalone code to reproduce the issue**
```python
import torch
from torchvision.models import resnet18
import torch.onnx

import tensorflow as tf

import onnx
from onnx_tf.backend import prepare

# load a pytorch model
torch_model = resnet18(pretrained=True, progress=False)
# save to onnx
save_dst = './torch_resnet18.onnx'
x = torch.rand(1, 3, 224, 224)
torch.onnx.export(
    torch_model, 
    x, 
    save_dst, 
    verbose=True,
    opset_version=12,
    export_params=True, 
    input_names = ['input'], 
    output_names = ['output'], 
    dynamic_axes={'input' : {0 : 'batch_size'}, 'output' : {0 : 'batch_size'}},
    )
# load and save to tf graph
onnx_model = onnx.load(save_dst)
tf_model = prepare(onnx_model)
tf_model.export_graph('tf_resnet18')
#%% modify
class TestModule(tf.Module):
    def __init__(self):
        super().__init__()
        self.t_model = tf.saved_model.load('tf_resnet18')
        self.f = self.t_model.signatures['serving_default']

    @tf.function(input_signature=[
        tf.TensorSpec(shape=[None, 256, 256, 3], dtype=tf.float32),
    ])
    def __call__(self, x):
        x = tf.image.resize(x, (224, 224))
        x = tf.transpose(x, [0, 3, 1, 2])
        return self.f(x)

m = TestModule()
x = tf.random.uniform((1, 256, 256, 3))
y = m(x)
print(y)
# it works fine above
tf.saved_model.save(m, 'tf_new')
# the last line takes a lot of time...
```
**Note**
It seems the program spent a lot of time on:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L1959
which leads to a lower level implementation:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L1084

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d68d8deabfc0a345bffdff3f52a8de37/54681.ipynb) for reference.Thanks!

**Comment by piEsposito** [comment]
Same problem here.

**Comment by piEsposito** [comment]
Never mind. In my specific case I just had to remove some if-elses form the Torch nn and make some operations more straighforward. Saving it in 3 seconds now.

**Comment by tilakrayal** [comment]
@wkema,
I tried to execute the mentioned code on the latest tensorflow v2.16.1 and observed the time taken to save the model using **tf.saved_model.save()** is very minimal & as intended. and also the code was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8284c499de4a6ee852e6fb183c5f9890/untitled1800.ipynb). Thank you!

**Comment by wkema** [comment]
Thank you! It has been 2 years and the gist looks good to me. I will close this issue :)
