### ISSUE TITLE
Tensorflow MaxPool doesn't accept float64

### ISSUE THREAD

**Issue by ketabdarhamed** [tensorflow/tensorflow#547]
I am using Tensorflow to train a CNN. I am currently basing my calculations on Float32 which is kind of default at the time of initialising variables.

I guessed that by using float64as my dtype I can get more accurate results so I changed the initilization of my varibales as follows:

`w1 = tf.Variable(tf.random_normal([5, 5, 3, 64], stddev=0.1, dtype=tf.float64))`
But I get following error in the maxpooloperation: I chacked the maxpooldocumentation and it accept value type as follow: `value: A 4-D Tensor with shape [batch, height, width, channels] and type float32, float64, qint8, quint8, qint32.`

But I get the following error. Is this a bug or I'm doing something wrong?

`Input 'input' of 'MaxPool' Op has type float64 that does not match expected type of float32.`

Full trace:

``` python
Traceback (most recent call last):
  File "/Users/hamedketabdar/LearningTensorFlow/CIFAR-Khodam/convolutional_network_batch_2d2c_clean_64f.py", line 213, in <module>
    pred = conv_net(x, weights, biases, keep_prob)
  File "/Users/hamedketabdar/LearningTensorFlow/CIFAR-Khodam/convolutional_network_batch_2d2c_clean_64f.py", line 153, in conv_net
    conv1 = max_pool(conv1, k=2) # Normally K=2
  File "/Users/hamedketabdar/LearningTensorFlow/CIFAR-Khodam/convolutional_network_batch_2d2c_clean_64f.py", line 135, in max_pool
    return tf.nn.max_pool(img, ksize=[1, k, k, 1], strides=[1, k, k, 1], padding='SAME')
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 235, in max_pool
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 449, in _max_pool
    strides=strides, padding=padding, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 430, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'input' of 'MaxPool' Op has type float64 that does not match expected type of float32.
```

stackoverflow link: http://stackoverflow.com/questions/34354126/tensorflow-maxpool-doesnt-accept-float64

**Comment by mrry** [comment]
It looks like the docs are wrong, in this case - the [registration](https://github.com/tensorflow/tensorflow/blob/a0f880c3432462f99c1ba046f0c4193675e7013f/tensorflow/core/ops/nn_ops.cc#L318) for the MaxPool op actually only accepts single-precision floats.

**Comment by ketabdarhamed** [comment]
Thanks, don't you think using float64 can enhance the overall performance? if yes, why not adding support for float64?

**Comment by mrry** [comment]
The current implementation is pretty specialized to `float32`, so it wouldn't be completely trivial to switch it over. However, we'd be glad to take contributions on this if it would be useful.

**Comment by girving** [comment]
Hmm, tried briefly to do this, but hit the lack of `atomicAdd` on GPU for double.

**Comment by siddharth-agrawal** [comment]
Stumbled upon some more errors in the documentation for AvgPool3D and MaxPool3D. Documentation says that these ops can be used with many tensor types, as can be seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/tf.nn.avg_pool3d.md) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/tf.nn.max_pool3d.md). But they are registered only for float32 as can be seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/pooling_ops_3d.cc#L124). Will send out a PR soon.

**Comment by girving** [comment]
@siddharth-agrawal: That would be awesome!  You'll likely need atomic add for doubles, but it's available now in `util/cuda_kernel_helper.h` as `CudaAtomicAdd`.

**Comment by siddharth-agrawal** [comment]
Oops. I think I didn't express myself right. I meant PR for the documentation errors. However, I found this while digging for the solution to this issue. So hopefully the PR you meant will come soon too. :)

**Comment by girving** [comment]
@siddharth-agrawal: If the documentation change requires changing the list of dtypes passed to `REGISTER_OP`, you'll break the backwards compatibility tests when doing so (those tests don't notice the lack of kernels).  If the double kernels are coming soon, it may be better to wait.  However, it's also possible (likely?) that I'm misunderstanding the changes, so please tell me if the previous makes no sense.

**Comment by siddharth-agrawal** [comment]
@girving I was thinking of modifying the first two files I mentioned in my first comment on the thread and `api_docs/python/nn.md`. Do you mean the list passed in `core/ops/ops.pbtxt`? Is that used for registering the op? Also, could you tell me where the backward compatibility tests are? (sorry, newbie here)

**Comment by girving** [comment]
`api_docs/python/nn.md` is autogenerated from code: you can't modify it directly.  Specifically, it's autogenerated from `core/ops/nn_ops.cc`, `python/ops/nn.py`, and `python/ops/nn_ops.py`.

**Comment by siddharth-agrawal** [comment]
Alright. I was looking at [this commit](https://github.com/tensorflow/tensorflow/commit/aa7c2472a70a26f4e57508b788eb9791abdbaee1), guess things have changed.

**Comment by girving** [comment]
@siddharth-agrawal: They're autogenerated but also checked in.  That commit also changed the code from which it was autogenerated (scroll down).

**Comment by siddharth-agrawal** [comment]
@girving I ran into a problem while trying to solve this, let me know if the following makes sense.

To register `MaxPoolingGradOp` on the GPU for float64 we need to have `template class DnnPoolingGradOp<double>` in `kernels/pooling_ops_common.cc` as `MaxPoolingGradOp`'s `Compute()` uses it. But adding this gives a build error with the following message:
`error: no matching function for call to 'perftools::gputools::Stream::ThenPoolForward(perftools::gputools::dnn::PoolingDescriptor&, perftools::gputools::dnn::BatchDescriptor&, perftools::gputools::DeviceMemory<double>&, perftools::gputools::dnn::BatchDescriptor&, perftools::gputools::DeviceMemory<double>*)'`

This feels like a dead end to me, as cudnn has come into the picture. Is there a way around this?

**Comment by girving** [comment]
It's surmountable, but I don't think we can accept pull requests that change the necessary code at the moment due to silly code organizational reasons.  @zheng-xq: I am I right that stream executor changes are difficult to accept from outside?

**Comment by siddharth-agrawal** [comment]
Ah, okay. I will find something else to work on. Thanks for all the help.

**Comment by girving** [comment]
Here are the ops that are missing double versions.  I believe the only difficult ones to add are the max pool ops, as described in #547.  Most of them are very neural net specific, which is probably why they haven't been generalized yet: neural net specific applications rarely need double precision.  We'd be happy to accept PRs though!

    AdjustContrastv2
    AllCandidateSampler
    AudioSummary
    CTCBeamSearchDecoder
    CTCGreedyDecoder
    CTCLoss
    ComputeAccidentalHits
    DrawBoundingBoxes
    EditDistance
    ExtractGlimpse
    FixedUnigramCandidateSampler
    HSVToRGB
    ImageSummary
    InTopK
    LRN
    LRNGrad
    LearnedUnigramCandidateSampler
    LogUniformCandidateSampler
    MaxPool
    MaxPoolGrad
    MaxPoolGradWithArgmax
    MaxPoolWithArgmax
    NegTrain
    RGBToHSV
    SampleDistortedBoundingBox
    SparseMatMul
    StringToNumber
    TensorArrayConcat
    TensorArrayGrad
    TensorArrayPack
    TensorArrayRead
    TensorArraySize
    TensorArraySplit
    TensorArrayUnpack
    TensorArrayWrite
    ThreadUnsafeUnigramCandidateSampler
    UniformCandidateSampler

**Comment by girving** [comment]
Automatically closing due to lack of recent activity.

**Comment by bela127** [comment]
what happen to this issue? it is still not fixed as fare as i can see

**Comment by I-Thompson** [comment]
I use tensorflow for quantum physics calculations that involve much matrix arithmetic.
And float64 makes a huge difference to accuracy. With float32, fitting data stops too often at false minima.

And now I discover that DTensorAllGather cannot do float64.
(Strangely?) the first missinig float64 support I have met in 2 years now of tf.

I really do want full float64 support

**Comment by I-Thompson** [comment]
Many parts of tf not working with DTensor yet.

tf.linalg.solve is my show-stopper at the moment.
As  is the failure of dtensor.relayout to distribute complex64. It does float32 and float64, but not yet complex of any kind. This is done by DTensorAllScatter.

**Comment by I-Thompson** [comment]
I admit that a full generalization tf.MatrixSolve to DTensors distributed in arbitrary dimension will be rather difficult.

I only request that, in the meantime, we allow distributed tensor only in the **batch** dimensions that are not in the matrices themselves.  Even that would  extremely useful!!
