### ISSUE TITLE
Cannot import graph_def for 8-bit Quantized cnn model

### ISSUE THREAD

**Issue by ResByte** [tensorflow/tensorflow#5470]
Following steps I did:
1. Train a CNN model on MNIST using tensorflow tutorials(Deep MNIST for Experts)(CONV+CONV+FC). Saved this model as binary protobuf(.pb).
2. Using 8-bit Quantization api, converted previously saved model to 8-bit model as binary proto(.pb). 
3. Read 8-bit binary-proto to tensorflow, by first creating graph_def and importing graph def to tf.Session()
```python
with sess.as_default() :
   with tf.Graph().as_default():
       graph_def = tf.GraphDef()
             with open(input_file_name, 'rb') as f:
                 proto_b = f.read()
                 graph_def.ParseFromString(proto_b)	
                 _ = tf.import_graph_def(graph_def, name="")
``` 

However, this gives error on tf.import_graph_def as
`ValueError: graph_def is invalid at node u'concat_eightbit_reshape_concat/values_0': Input tensor 'concat/values_0:0' Cannot convert a tensor of type int32 to an input of type float32.`

### Environment info
Operating System: Ubuntu 16.04 + tensorflow 0.11.0rc2

Installed version of CUDA and cuDNN: No

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp27-none-linux_x86_64.whl

### What other attempted solutions have you tried?
1. I am able to correctly import quantized graph def for pre-trained inception model(.pb).
2. When I define Multi-layer perceptron model for MNIST, it can import quantized graph_def. 
3. All the quantization headers are imported correctly as
``` python
from tensorflow.contrib.quantization import load_quantized_ops_so
from tensorflow.contrib.quantization.kernels import load_quantized_kernels_so
load_quantized_ops_so.Load()
load_quantized_kernels_so.Load()
```

**Comment by sherrym** [comment]
Which 8-bit Quantization API is this? Could you please send me a link? Sounds like it didn't change the data type when performing the conversion.

**Comment by ResByte** [comment]
I followed this [How-to](https://www.tensorflow.org/versions/r0.11/how_tos/quantization/index.html).

**Comment by sherrym** [comment]
Andrew, could you please take a look? Thanks.

Sherry

**Comment by sherrym** [comment]
Added @cwhipkey as well.

**Comment by cwhipkey** [comment]
Can you share the file that you pass to quantize_graph ?

@petewarden as well

**Comment by ResByte** [comment]
This is binary proto before quantization. 
[tf_mnist_cnn_graph.pb.zip](https://github.com/tensorflow/tensorflow/files/585009/tf_mnist_cnn_graph.pb.zip)

Thanks.

**Comment by cwhipkey** [comment]
@petewarden

Thanks for the info.  Yes, the problem is that it is choosing to quantize a
Concat node, but can't actually quantize its inputs.  I have a fix I will
push out.

**Comment by ResByte** [comment]
@cwhipkey 
Thank you, Please share the info after the fix.

**Comment by cwhipkey** [comment]
This change was pushed as this commit:
https://github.com/tensorflow/tensorflow/commit/662533b85c66f198b779bea147397e1441f3e482
