### ISSUE TITLE
Linking process takes forever

### ISSUE THREAD

**Issue by gmernov** [tensorflow/tensorflow#54714]
**System information**
- OS Platform and Distribution: Ubuntu18.04 (x86_64)
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tensorflow.git
- TensorFlow version: latest
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source): bazel-5.0.0-linux-arm64
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: 8.2.1.32-1+cuda10.2
- CPU model and memory: CPU:       32 core Intel Xeon E5-2667 v2 (-MT-MCP-) speed: 3292 MHz (max) / 40GB RAM

I'm trying to cross-compile Tensorflow for my NVIDIA Jetson Nano device, from a source code, on an Intel platform server machine. Got by the git clone. It seems like compilation process is finished, or the part of is finished, but the linking process stuck. It gives a tiny load on 1 of 32 cpu threads, but it already took almost a day, but nothing happens. Linking.... Also i checked, IO load, it's minimal. Is it ok, and it takes so much time, or i do something wrong ?

> 
![image](https://user-images.githubusercontent.com/4686690/156057119-5578e436-e2e3-4dd4-abbd-d9fe58465562.png)

![image](https://user-images.githubusercontent.com/4686690/156057201-384425a1-032c-4692-a719-f33192d97f24.png)

![image](https://user-images.githubusercontent.com/4686690/156057731-d5c55dc8-30cd-4306-b56e-98abbf1c1f37.png)

**Comment by tilakrayal** [comment]
@gmernov ,
Can you please try installing TensorFlow v2.8 with GCC 7.3.1 and Bazel 4.2.1 as suggested in tested build configurations [here](https://www.tensorflow.org/install/source#cpu) and check if you are facing the same error. Thanks!

**Comment by gmernov** [comment]
Actually i tried multiple version of Bazel. But only 5.0 did the trick. All other versions gave me an error. I can try to get a log of building with Bazel 4.2.1 if you want it to.

**Comment by gmernov** [comment]
> @gmernov , Can you please try installing TensorFlow v2.8 with GCC 7.3.1 and Bazel 4.2.1 as suggested in tested build configurations [here](https://www.tensorflow.org/install/source#cpu) and check if you are facing the same error. Thanks!

Actually i tried multiple version of Bazel. But only 5.0 did the trick. All other versions gave me an error. I can try to get a log of building with Bazel 4.2.1 if you want it to.

**Comment by gmernov** [comment]
I also tried to build with 4.2.2
It segfaulted in the start of. Before the actuall compilation process started. Somewhere after bazel started and Download of something was initiaed:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000005513a5d80c, pid=99, tid=339
#
# JRE version: OpenJDK Runtime Environment (Zulu11.37+48-CA) (11.0.6+9) (build 11.0.6+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM (11.0.6+9-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-aarch64)
# Problematic frame:
# J 7167 c2 net.starlark.java.eval.Eval.eval(Lnet/starlark/java/eval/StarlarkThread$Frame;Lnet/starlark/java/syntax/Expression;)Ljava/lang/Object; (316 bytes) @ 0x0000005513a5d80c [0x0000005513a5d740+0x00000000000000cc]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /tmp/tensorflow-master/core.99)
#
# An error report file with more information is saved as:
# /tmp/tensorflow-master/hs_err_pid99.log
Compiled method (c2)  512027 7167       4       net.starlark.java.eval.Eval::eval (316 bytes)
 total in heap  [0x0000005513a5c790,0x0000005513a68aa0] = 49936
 relocation     [0x0000005513a5c908,0x0000005513a5d708] = 3584
 main code      [0x0000005513a5d740,0x0000005513a63b40] = 25600
 stub code      [0x0000005513a63b40,0x0000005513a65140] = 5632
 oops           [0x0000005513a65140,0x0000005513a65180] = 64
 metadata       [0x0000005513a65180,0x0000005513a654f0] = 880
 scopes data    [0x0000005513a654f0,0x0000005513a671a0] = 7344
 scopes pcs     [0x0000005513a671a0,0x0000005513a68240] = 4256
 dependencies   [0x0000005513a68240,0x0000005513a68250] = 16
 handler table  [0x0000005513a68250,0x0000005513a68928] = 1752
 nul chk table  [0x0000005513a68928,0x0000005513a68aa0] = 376
Could not load hsdis-aarch64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#

**Comment by gmernov** [comment]
As for now, it doesn't want to build even with 5.0.0 bazel.
![image](https://user-images.githubusercontent.com/4686690/157863092-ef7832a0-e462-4687-80aa-fa4fed9581de.png)

/root/.cache/bazel/_bazel_root/2b5c4e51f9e1005b4128ae187b9d110f/server/jvm.out  - has nothing in

**Comment by gmernov** [comment]
Tensorflow 2.7.1, bazel 4.2.2 the same thing: I also tried to install clang6.0 and clang10.0, but clang compilation provides an errors.

![image](https://user-images.githubusercontent.com/4686690/158339107-d719f6b8-e9b7-46b6-a1c7-99f5156881cc.png)

**Comment by gmernov** [comment]
It's not possible to share the complete error log because of: if i compile tensor using GCC, it gives me no error. Simply endless linking... i have to stop the compilation process using CTRL+C(3 times). My ./configure 

```
root@UBUNTU-SRV:/tmp/tensorflow-2.7.1# ./configure
You have bazel 4.2.2 installed.
Please specify the location of python. [Default is /usr/bin/python3]:


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.8/dist-packages
  /usr/local/lib/python3.8/site-packages/cv2/python-3.8
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Found CUDA 10.2 in:
    /usr/local/cuda-10.2/targets/aarch64-linux/lib
    /usr/local/cuda-10.2/targets/aarch64-linux/include
Found cuDNN 8 in:
    /usr/lib/aarch64-linux-gnu
    /usr/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]:


Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```
Also the build command looks like: 

`bazel build --progress_report_interval=30 --show_loading_progress --show_progress --local_ram_resources=1500 --local_cpu_resources=32 -j 32 --verbose_failures=true --config=cuda //tensorflow/tools/pip_package:build_pip_package
`

Actually i started with 2.8.0 and bazel 5.0.0 versions. and a build string:

`bazel build  --config=cuda //tensorflow/tools/pip_package:build_pip_package
`

**Comment by gmernov** [comment]
Anything you can advice ?

**Comment by gadagashwini** [comment]
@gmernov,
As per the Tensorflow [Tested build configuration](https://www.tensorflow.org/install/source#gpu), Tensorflow v2.8 supports CUDA 11.2 and cuDNN 8.1.  Linking to specific CUDA version is taking long time. Upgrade CUDA version and try. Thanks!

**Comment by gmernov** [comment]
I think it's not possible to upgrade CUDA version, because of i'm using latest Jetson JetPack. And it has it's certain version in. But i tried to build TF 2.7.3 using bazel =<3.99.0. The situation changed. Now it doesn't wait to the end to start linking process, but it does it on the run. Compiling,linking,compiling,linking. But it "hangs" somewhere in the middle of as well as TF 2.8.0 does.
So, still no go...

**Comment by gmernov** [comment]
Can i ask you to help me to compile python3.8 module for aarch64 architechture with GPU CUDA support, if you can help me with ?

**Comment by gadagashwini** [comment]
@gmernov,
You can use binary package with GPU support
`pip install tensorflow-aarch64`

**Comment by gmernov** [comment]
> Linking large binaries is supposed to take a lot of time. Please also watch memory usage, in case it uses swap (which results in even more slowdown).

Yes, but the linking doesn't want to end. It produces no load. I don't think that it's gonna end while it does no load... I'm using 32 cores, and 40GB or RAM

**Comment by gmernov** [comment]
> @gmernov, You can use binary package with GPU support `pip install tensorflow-aarch64`

This build has a very dated version. I need something like 2.4-2.8 version for aarch64 with GPU CUDA support

**Comment by gmernov** [comment]
Trying to build TF 2.4.1 using bazel 3.1.0(built from sources as well). The same crap. hangs on linking... But now, i've enabled debug messages by --subcommands.

![image](https://user-images.githubusercontent.com/4686690/161059874-ace48eb3-1abb-4923-bb28-1f741215b43c.png)

That's the system monitor, to see the "load" on the system: 

![image](https://user-images.githubusercontent.com/4686690/161059957-73f8e6e3-0786-47cf-9071-9f136750bf4b.png)

**Comment by gmernov** [comment]
Maybe it's not related exactly  for Tensorflow, but for linker. IDK. But i suffer this for multiple versions of tensorflow code.

**Comment by gadagashwini** [comment]
@gmernov,
Latest release 
`pip install tensorflow-aarch64==2.8.0`

**Comment by gmernov** [comment]
> @gmernov, Latest release `pip install tensorflow-aarch64==2.8.0`

Does this version support CUDA ? I'm trying to build a version from sources because of i need tensorflow GPU support.

**Comment by gadagashwini** [comment]
@gmernov,
`tensorflow-aarch64==2.8.0` it does support GPU.
