### ISSUE TITLE
LLVM component error.

### ISSUE THREAD

**Issue by DublikuntMux** [tensorflow/tensorflow#54749]
**System information**

OS Platform : Windows 11
TensorFlow version: 2.8
Python version: 3.9.9
Bazel version : 421
GPU model and memory: GTX1650
CUDA/CUdnn: 11.5/8.3.1

**Describe the problem**
Problem when build from source. LLVM component.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=156
INFO: Reading rc options for 'build' from c:\users\dubli\downloads\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=E:/Python3/python.exe
INFO: Reading rc options for 'build' from c:\users\dubli\downloads\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library
INFO: Reading rc options for 'build' from c:\users\dubli\downloads\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=E:/Python3/python.exe --action_env PYTHON_LIB_PATH=E:/Python3/lib/site-packages --python_path=E:/Python3/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5 --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.5 --config=cuda --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from c:\users\dubli\downloads\tensorflow\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file c:\users\dubli\downloads\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\dubli\downloads\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file c:\users\dubli\downloads\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file c:\users\dubli\downloads\tensorflow\.tf_configure.bazelrc: --copt=/arch:FMA3 --host_copt=/arch:FMA3
INFO: Found applicable config definition build:windows in file c:\users\dubli\downloads\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\dubli\downloads\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Repository llvm-project instantiated at:
  C:/users/dubli/downloads/tensorflow/WORKSPACE:15:14: in <toplevel>
  C:/users/dubli/downloads/tensorflow/tensorflow/workspace2.bzl:888:21: in workspace
  C:/users/dubli/downloads/tensorflow/tensorflow/workspace2.bzl:526:15: in _tf_repositories
  C:/users/dubli/downloads/tensorflow/third_party/llvm/setup.bzl:22:19: in llvm_setup
Repository rule llvm_configure defined at:
  C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/configure.bzl:83:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm-project':
   Traceback (most recent call last):
        File "C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'E:/Python3/python.exe C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw --overlay C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] ╩ышхэЄ эх юсырфрхЄ ЄЁхсєхь√ьш яЁртрьш: 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-project\\.bazelignore'

ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/configure.bzl", line 73, column 25, in _llvm_configure_impl
                _overlay_directories(repository_ctx)
        File "C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/configure.bzl", line 62, column 13, in _overlay_directories
                fail(("Failed to execute overlay script: '{cmd}'\n" +
Error in fail: Failed to execute overlay script: 'E:/Python3/python.exe C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw --overlay C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] ╩ышхэЄ эх юсырфрхЄ ЄЁхсєхь√ьш яЁртрьш: 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-project\\.bazelignore'

ERROR: C:/users/dubli/downloads/tensorflow/tensorflow/tools/pip_package/BUILD:273:10: //tensorflow/tools/pip_package:build_pip_package depends on //tensorflow/compiler/mlir/tensorflow:gen_mlir_passthrough_op_py in repository @ which failed to fetch. no such package '@llvm-project//mlir': Failed to execute overlay script: 'E:/Python3/python.exe C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/overlay_directories.py --src C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw --overlay C:/users/dubli/_bazel_dubli/mnmgdhl7/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

stderr:
Traceback (most recent call last):
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 92, in <module>
    main(parse_arguments())
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 80, in main
    _symlink_abs(os.path.join(args.overlay, relpath),
  File "C:\users\dubli\_bazel_dubli\mnmgdhl7\external\llvm-raw\utils\bazel\overlay_directories.py", line 64, in _symlink_abs
    os.symlink(os.path.abspath(from_path), os.path.abspath(to_path))
OSError: [WinError 1314] ╩ышхэЄ эх юсырфрхЄ ЄЁхсєхь√ьш яЁртрьш: 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-raw\\utils\\bazel\\llvm-project-overlay\\.bazelignore' -> 'C:\\users\\dubli\\_bazel_dubli\\mnmgdhl7\\external\\llvm-project\\.bazelignore'

ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.208s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: tensorflow/compiler/mlir/tensorflow

**Comment by patlevin** [comment]
Try to [Activate Developer Mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) - this did the trick for me.

The error occurs if Windows couldn't create a symbolic link. The `mklink`-command requires administrator privileges for some reason unless dev mode is enabled.

**Comment by gadagashwini** [comment]
@DublikuntMux, This issue seems to be Bazel version problem. Latest Tensorflow version supports Bazel version 5.0.0. Thanks!

**Comment by DublikuntMux** [comment]
> Try to [Activate Developer Mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) - this did the trick for me.
> 
> The error occurs if Windows couldn't create a symbolic link. The `mklink`-command requires administrator privileges for some reason unless dev mode is enabled.

Thank you, you were right. The problem was solved as soon as I turned on developer mode.

**Comment by DublikuntMux** [comment]
> @DublikuntMux, This issue seems to be Bazel version problem. Latest Tensorflow version supports Bazel version 5.0.0. Thanks!

_TF_MAX_BAZEL_VERSION = '4.99.0'
The settings do not allow you to use any more than this version.
