### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'reduce_sum'

### ISSUE THREAD

**Issue by CL500Coupe** [tensorflow/tensorflow#54748]
Hi while running 

python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

To verify my Tensorflow installation I get AttributeError;

AttributeError: module 'tensorflow' has no attribute 'reduce_sum'

tensorflow version: Version: 2.5.0

**Comment by Ahmed-M0hamed** [comment]
you could try tf.math.reduce_sum()
