### ISSUE TITLE
Segmentation Fault (core dumped) Issue

### ISSUE THREAD

**Issue by peter-jp** [tensorflow/tensorflow#54747]
**System information**
- I have written custom code
- OS Platform and Distribution: CentOS Linux release 7.7.1908 (AltArch), Power9 PC with 4 GPU nodes, 1 login node and 1 compute node and it has little endian architecture
- TensorFlow installed from (source or binary): https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
- TensorFlow version (use command below): 2.1.3 (tensorflow-gpu)
- Python version:3.6.13
- Bazel version (if compiling from source):
-  python compiler version: GCC 7.3.0
- CUDA/cuDNN version:10.2
- GPU model and memory: NVIDIA Tesla V100, Total memory: 379140608 kB =379.140608 GB (in one of the node)

I use Supercomputer at our organization for training. I am facing the Segmentation Fault (core dumped) Issue, when I attempt to train a CNN model. The model gets trained for a smaller number of Epochs. Eg if epochs=50 the model runs fine and outputs the trained model file (using callbacks in model.fit). But when epochs are increased, to 75 then segmentation fault occurs at 54th epoch for the same dataset. I ran .py file by submitting it as a job through slurm script. Dataset size is 80,000*5600, around 9GB.

**Code**
```
import os
import os.path
import sys

import h5py
import numpy as np
import tensorflow as tf
from tensorflow import keras

def load_file(database_file, load_data=False):
    in_file  = h5py.File(database_file, "r")
    X_train = np.array(in_file['training/data'],dtype=np.int8)
    Y_train = np.array(in_file['training/label'])
    X_test = np.array(in_file['testing/data'], dtype=np.int8)
    Y_test = np.array(in_file['testing/label'])
    if load_data == False:
        return (X_train, Y_train), (X_test, Y_test)
    else:
        return (X_train, Y_train), (X_test, Y_test), (in_file['train/data'], in_file['test/data'])

database = "/home/..../dataset.h5"
trained_model = "/home..../trained_epoch_test.h5"
  
(X_train, Y_train), (X_test, Y_test) = load_file(database_file)

X_train_scaled = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test_scaled = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

y_train_categorical = keras.utils.to_categorical(Y_train, num_classes=256)
y_test_categorical    = keras.utils.to_categorical(Y_test, num_classes=256)

batch_size = 300 
epochs = 100
   
classes=256
input_shape = (5600,1)     
img_input = keras.layers.Input(shape=input_shape)

x = keras.layers.Conv1D(64, 11, activation='relu', padding='same', name='block1_conv1')(img_input)
x = keras.layers.AveragePooling1D(2, strides=2, name='block1_pool')(x)

x = keras.layers.Conv1D(128, 11, activation='relu', padding='same', name='block2_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block2_pool')(x)

x = keras.layers.Conv1D(256, 11, activation='relu', padding='same', name='block3_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block3_pool')(x)

x = keras.layers.Conv1D(512, 11, activation='relu', padding='same', name='block4_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block4_pool')(x)

x = keras.layers.Conv1D(512, 11, activation='relu', padding='same', name='block5_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block5_pool')(x)

x = keras.layers.Flatten(name='flatten')(x)
x = keras.layers.Dense(4096, activation='relu', name='fc1')(x)
x = keras.layers.Dense(4096, activation='relu', name='fc2')(x)
x = keras.layers.Dense(classes, activation='softmax', name='predictions')(x)
  
model = keras.models.Model(img_input, x, name='cnn_best')
optimizer = keras.optimizers.RMSprop(lr=0.00001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
save_model = keras.callbacks.ModelCheckpoint(trained_model)
callbacks=[save_model]
    
model.fit(x=X_train_scaled, y=y_train_categorical, batch_size=batch_size, verbose = 1, epochs=epochs, callbacks=callbacks)
```
**Following is the logs generated after enabling fault handler() function:**
![fault handler](https://user-images.githubusercontent.com/70361953/156146446-230da029-000b-4c0f-9911-90ff9c51276e.png)

**Slurm Script used to submit the job**
#!/bin/bash
#SBATCH --partition=GPU_three
#SBATCH --nodelist=Node_03
#SBATCH --output=output
python3 train.py

**Comment by mohantym** [comment]
Hi @peter-jp! Thanks for reporting this issue. You can reduce reduce the batch size to 30 or 60  and input size to (100,1) to see the difference. You can also use [tf.device](https://www.tensorflow.org/guide/gpu) to force run the entire process in GPU mode. 

Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) for further assistance.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!

**Comment by peter-jp** [comment]
I can reduce the batch size but cannot reduce the input size (as it must be equal to the number of columns in the dataset). 
In IBM conda, the latest version available for Tensorflow-gpu is 2.1.3, no other versions like TF 2.8 is available for ppcle64 arch.
I will use tf.device and will update the result.

**Comment by mohantym** [comment]
@peter-jp ! Did it get resolved in GPU mode in 2.8 version?

**Comment by peter-jp** [comment]
There is no TF2.8 version for PPCLE64 architecture. I use the following channel for installing packages

conda config --prepend channels \
https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue?

**Comment by peter-jp** [comment]
yes sure

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by peter-jp** [comment]
@mohantym I tried with 30 as batch size for 400 epochs but it also resulted in segmentation fault at 130th epoch.

Following is the result of enabling fault handler



Current thread 0x0000200000044cd0 (most recent call first):
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/h5py/_hl/files.py", line 443 in close
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 120 in save_model_to_hdf5
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 112 in save_model
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1011 in save
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 1040 in _save_model
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 992 in on_epoch_end
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 302 in on_epoch_end
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 771 in on_epoch
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/contextlib.py", line 88 in __exit__
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 397 in fit
  File "/home/peter/.conda/envs/peter_env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819 in fit
  File "/home/peter/analysis/for_Training_gpu.py", line 100 in <module>
/var/spool/slurm/d/job03321/slurm_script: line 8:  3921 Segmentation fault      (core dumped) python3 ~/analysis/for_Training_gpu.py

**Comment by sachinprasadhs** [comment]
Hi, Could you please refer this comment and post the issue in Keras repo for faster resolution. Thanks!

> Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues
> 
> Please post this issue on keras-team/keras repo. To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!
