### ISSUE TITLE
Tensorflow Lite iOS framework- info.plist file missing

### ISSUE THREAD

**Issue by dtomarepo** [tensorflow/tensorflow#54750]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Iphone 13 mini
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7r
- Python version: 3.9.5
- Installed using virtualenv? pip? conda?: venv
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): compilation is fine.
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Problem description**
Building an iOS framework does not generate info.plist which is needed when the library is used as an embed framework. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure -> use iOS
bazel build --config=ios_arm64 -c opt //tensorflow/lite/ios:dvdnr_framework

**Any other info / logs**
the framework generates fine, but info.plist should be included in the framework.

**Comment by dtomarepo** [comment]
nvm.

**Comment by mohantym** [comment]
Hi @nvm! Did it get resolved?
