### ISSUE TITLE
Inconsistent behaviour between CPU and GPU using TFLite model on iOS

### ISSUE THREAD

**Issue by witsemp** [tensorflow/tensorflow#54751]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  iOS 14.7.1 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 11 Pro
- TensorFlow installed from (source or binary): binary using cocoapods
- TensorFlow version (use command below): 2.6.0
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Apple A13 GPU

**Describe the current behavior**
I'm running a TFLite [object detection model](https://github.com/google/mediapipe/blob/master/mediapipe/modules/objectron/object_detection_3d_sneakers_1stage.tflite) with 2 main outputs and an auxiliary output that provides a segmentation map. The model is used in iOS application via Swift TFLite API where I'm using a Metal Delegate to utilise the GPU. While running on GPU, I'm constantly receiving a tensor of zeros from the auxiliary output. On CPU however, I'm getting non-zero values (which is a desired behaviour). Switching between GPU and CPU does not effect the two main outputs. I tried manipulating different options of the MetalDelegate, but to no success.  Can you point me towards reasons for such behaviour and any possible solutions? 

**Describe the expected behavior**
Receiving non-zero values from the segmentation output, consistent with CPU performance, while running on GPU. 

**Other info / logs**
Below I'm posting a snippet from method responsible for configuration of an Interpreter. `InferenceConfig.accelerate` is a boolean flag - if true, the model runs on GPU.
```
if InferenceConfig.accelerate {
    var options = MetalDelegate.Options()

    options.isPrecisionLossAllowed = false
    options.isQuantizationEnabled = false
    options.waitType = .active
    let gpuDelegate = MetalDelegate(options: options)

    interpreter = try Interpreter(
        modelPath: InferenceConfig.modelPath!,
        delegates: [gpuDelegate]
    )
} else {
    var interpreterOptions = Interpreter.Options()
    interpreterOptions.isXNNPackEnabled = true

    interpreter = try Interpreter(
        modelPath: InferenceConfig.modelPath!,
        options: interpreterOptions
    )
}
```

**Comment by witsemp** [comment]
I came across [this issue](https://github.com/tensorflow/tensorflow/issues/27240) which seems very closely related to the problem I described. The solution mentioned there implies changing the graph by introducing an addition operator with a very small constant value to remove the intermediate tensor problem. My question here is: is there a way to modify the graph in existing TFLite model? I don't have the access to TF model that I could change and convert to TFLite again.

**Comment by pjpratik** [comment]
Hi @witsemp 

You can modify tflite model by converting it to json format using `flatc` which requires downloading [schema.fbs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs) 

`flatc -t schema.fbs  -- xyz.tflite` which gives editable json file then

convert it back to new tflite model by
`flatc -b schema.fbs  xyz_edite.json`

Thanks.
