### ISSUE TITLE
model.save fails with ValueError __inference_conv2d_transpose_layer_call_fn_4530 when Conv2DTranspose is quantization aware

### ISSUE THREAD

**Issue by ypsilon-elle** [tensorflow/tensorflow#54753]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):  pip install
- TensorFlow version: 
        tf=2.7.0, tensorflow_model_optimization=0.7.1
	tf=2.8.0, tensorflow_model_optimization=0.7.1
	tf-nightly=2.9.0dev20211222, tensorflow_model_optimization=0.7.1
- Python version: 3.7.12

**Describe the current behavior**
We save a quantization-aware keras-model in a .pb model format using `model.save()`. This operation fails with `ValueError: __inference_conv2d_transpose_layer_call_fn_4530` when our model contains a `Conv2DTranspose` layer. 
- The error is reproducible when we quantize the entire model using `tfmot.quantization.keras.quantize_model()`
- The error is also reproducible when we annotate layers using `tf.keras.models.clone_model()` apply quantization using `tfmot.quantization.keras.quantize_apply()`. Our current workaround is to not annotate `Conv2DTranspose` but this prevents us from having a fully quantization-aware model. 
 - The error is reproducible in  tf2.7.0, tf2.8.0 and tf-nightly

Saving the same model as .h5 works (unfortunately this workaround this is not suitable for us because our technical requirement is that we save a .pb-model)

**Describe the expected behavior**
`model.save()` saves a QAT  model with a  Conv2DTranspose layer in a .pb-format successfully. 

**Standalone code to reproduce the issue**
Here are collabs to reproduce the issue using a very simple model with a Conv2DTranspose layer and two ways to make a model quantization aware mentioned above:
     - [ Collab with tf2.7.0](https://colab.research.google.com/drive/1BHQeFMd0Pc8qtfjY3FBBZ2rM1m2tqs23?usp=sharing)
     - [ Collab with tf2.8.0](https://colab.research.google.com/drive/1zTzM9nJnY0NagzAcnZSlUgKW-vTUsL4F?usp=sharing)

	
**Other info / logs** 
Similar issue [#868](https://github.com/tensorflow/model-optimization/issues/868 )

```
Traceback
ValueError                                Traceback (most recent call last)
<ipython-input-7-dc1f93a93afb> in <module>()
      2 annotated_model = tf.keras.models.clone_model(base_model, clone_function=apply_quantization)
      3 q_aware_model = tfmot.quantization.keras.quantize_apply(annotated_model)
----> 4 q_aware_model.save('D:/output_folder/q_aware_model') # save keras model as .pb, fails

1 frames
/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/save.py in map_resources(self)
    402           if capture_constant_value is None:
    403             raise ValueError(
--> 404                 f"Unable to save function {concrete_function.name} because it "
    405                 f"captures graph tensor {capture} from a parent function which "
    406                 "cannot be converted to a constant with `tf.get_static_value`.")

ValueError: Unable to save function b'__inference_conv2d_transpose_layer_call_fn_4530' because it captures graph tensor 
Tensor("model/quant_conv2d_transpose/transpose_1:0", shape=(3, 3, 16, 16), dtype=float32) from a parent function which 
cannot be converted to a constant with `tf.get_static_value`.
```

**Comment by GoogleForce** [comment]
**f**

**Comment by pat749** [comment]
I followed this guide and it worked for me: https://www.tensorflow.org/guide/saved_model#exporting_custom_models

In other words, the below code should work. That said, I do agree that an explicit example for exporting a sub-classed keras model with a custom training loop is missing on the tf page.

import tensorflow as tf


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    @tf.function(input_signature=[tf.TensorSpec([2, 3], tf.float32)])
    def call(self, x, training=True, mask=None):
        return self.d(x)


model = Model()
model(tf.random.normal((2, 3)))

tf.saved_model.save(model, '/tmp/serving_path')

**Comment by sushreebarsa** [comment]
@ypsilon-elle 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by ypsilon-elle** [comment]
Hey @sushreebarsa, thank you for your suggestion. I have reposted this issue to [keras-team/keras](https://github.com/keras-team/keras/issues): [#16152](https://github.com/keras-team/keras/issues/16152)
