### ISSUE TITLE
Square root symbol Sqrt not displayed correctly

### ISSUE THREAD

**Issue by ScholliYT** [tensorflow/tensorflow#54763]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/sqrt
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/rsqrt

## Description of the issue (what needs changing):
The square root symbol is not displayed in the rendered HTML documentation. Although, the source code includes the appropriate code `\sqrt{x}`. One would expect a square symbol around the x in the following image:

![image](https://user-images.githubusercontent.com/12571895/156189226-cc3865fe-cc0e-416d-a3d7-1086c776fdff.png)

- https://github.com/tensorflow/tensorflow/blob/e88293b0d59a237af1e2a299048b783f5331b7fb/tensorflow/core/api_def/base_api/api_def_Rsqrt.pbtxt#L5
- https://github.com/tensorflow/tensorflow/blob/e88293b0d59a237af1e2a299048b783f5331b7fb/tensorflow/core/api_def/base_api/api_def_Sqrt.pbtxt#L5

### Clear description

The missing square symbol is confusing for someone reading the documentation.

### Fix

One could change every occurrence of the sqrt symbol to `x^{1/2}`. However, this is not a good solution and we should rather fix the display issue itself.

**Comment by pat749** [comment]
yes i also saw in documentation but we can change it by y=1/sqrt{x}=1/(x^2) ,by this we can correct it

**Comment by chunduriv** [comment]
@ScholliYT ,

Thanks for reporting. Created CL's to fix above issues.

**Comment by aflah02** [comment]
@chunduriv is this still issue still open? As I don't see a pull request for the same

**Comment by chunduriv** [comment]
@ScholliYT,

This issue fixed now. Please refer updated api_docs for [sqrt](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/sqrt) and [rsqrt](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/rsqrt). Thanks!

**Comment by ScholliYT** [comment]
@chunduriv looks good to me 👍

**Comment by chunduriv** [comment]
@ScholliYT,

Please feel free to close the issue. Thanks!

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
