### ISSUE TITLE
ImportError: No module named tensorflow - Can't install Tensorflow

### ISSUE THREAD

**Issue by paralaxwombat** [tensorflow/tensorflow#5478]
I am trying to install tensorflow on mac and it's giving me this error.

ImportError: No module named tensorflow

Here is what I have done in the terminal

`sudo easy_install pip 

sudo easy_install --upgrade six
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py3-none-any.whl
sudo -H pip3 install --upgrade $TF_BINARY_URL`

After that I try to run python and tensorflow to check my installation. It doesn't work. I have spent 3 hours on the problem.

Here is another post about it. http://stackoverflow.com/questions/40472144/importerror-no-module-named-tensorflow-cant-install-tensorflow?noredirect=1#comment68200554_40472144

**Comment by aselle** [comment]
Please consider these things:
- What OS? We support El Capitan right now. Sierra hopefully soon.
- Try a newer version than 0.9 which is quite old, perhaps 0.11rc2
- Are there any errors on the pip install?
- What version of python. Perhaps try the python 2 version if you have that as well. Show exactly what version of python you are actually running and what it spits out. For example...
```
$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
>>> 

```
I understand it is frustrating to spend 3 hours having trouble, but it is hard for us to help you when you do not provide detailed information. Thanks.

**Comment by LeongKH** [comment]
Hi @aselle ,

I am having the same error too.
I am using EI Capitan 10.11.2

Here is what i did in my installation:
```
$ sudo easy_install pip
$ sudo easy_install --upgrade six
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py2-none-any.whl
$ sudo pip install --upgrade $TF_BINARY_URL

```
Here is my tensor flow information:
```
$ pip show tensorflow
Name: tensorflow
Version: 0.9.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: protobuf, numpy, wheel, six
```

Following is my python version:
```
$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensor flow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensor flow
>>>
```

**Comment by prb12** [comment]
Closing.

**Comment by rezafarhadi** [comment]
I had the same issue with mac os.. this fixed the problem:
install brew
brew install python
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py2-none-any.whl
sudo pip install --upgrade $TF_BINARY_URL

**Comment by UkiDLucas** [comment]
If you use brew:
- brew install python - installs 2.7
- brew install python3 - installs 3.6
in any case, you are not running optimal version for TensorFlow 3.5

When running:
 $ sudo  pip3 install --ignore-installed --upgrade $TF_BINARY_URL

it looks like it installs everything 100%
$ conda list
...
tensorflow-gpu            0.12.1                    <pip>
...

but when running $ jupyter notebook
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

So something is not working between Python (conda, pip) environment and Jupyter.

**Comment by lingfengchencn** [comment]
i had the same issue. and here is why it happen and how i fixed it in my issue:
env: anaconda (python 3.6)+mac ,
first ,i used :
$ pip3 install tensorflow 
$ python
Python 3.6.0 |Anaconda 4.3.0 (x86_64)| (default, Dec 23 2016, 13:19:00) 

>>> import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

and then 
$pip install tensorflow
$python
Python 3.6.0 |Anaconda 4.3.0 (x86_64)| (default, Dec 23 2016, 13:19:00) 
>>>  import tensorflow as tf
>>>

**Comment by gsanjeevkumar** [comment]
@LeongKH thanks this works for me!

**Comment by saramelvin** [comment]
importing tensorflow using python3 instead of python 2.7 worked for me.

**Comment by KiselevMaxim** [comment]
> pip3 install tensorflow
> ...
> pip install tensorflow

thank you, it is works for me

**Comment by johndpope** [comment]
some computer scientist lady recommended miniconda - and I haven't looked back.
Forget using pip/pip3 / use conda + conda environments. I can't recommend it more.
https://gist.github.com/johndpope/187b0dd996d16152ace2f842d43e3990

**Comment by andyhappy1** [comment]
@UkiDLucas  Thanks very much.  That fixed it for me.  I believe it's that you need iPython to make Python 2.7 work with Anaconda.  

This fixed it for me:
$source activate tensorflow
$ sudo pip install ipykernel
$ python -m ipykernel install --user --name tensorflow --display-name "conda env tensorflow"

**Comment by armotodo** [comment]
chunchuria
umbrella

**Comment by armotodo** [comment]
a si
como 
no
me
inco

**Comment by Afrogeek254** [comment]
Hi i have the same issue when trying to run tensorflow in my windows 10 
when I run pip show cmd this is what is displayed 
C:\>pip show tensorflow
Name: tensorflow
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: c:\program files\python36\lib\site-packages
Requires: six, wheel, tensorflow-tensorboard, numpy, protobuf

when prompt my python shell and try to import tensorflow 


it gives me this error 
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

kindly assist

**Comment by renying** [comment]
i had the same issue.
i installed two version of python 2.7 and 3.5
tensorflow installs in python2.7

my default python version is 3.5 
so if I type: python
Python 3.5.3 (default, Dec  7 2017, 09:41:57) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'


but if I type: python2.7
Python 2.7.5 (default, Aug  4 2017, 00:39:18) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf

It`s OK 


so check your python version.
It will help

**Comment by emelendez89** [comment]
@Afrogeek254 I also stumbled on this problem, also fixed it by changing python version. (Win10 x64)
Funny thing is that the first version I tried is the one "supported" by TF as said in [the documentation](https://www.tensorflow.org/install/install_windows#installing_with_native_pip) (used the link in the page for 3.6.x 64 which was 3.6.2).
Didn't want to find a workaround, and ended up installing 3.5.2 (also linked in the installation docs)

**Comment by hollykunge** [comment]
卧槽 解决了 很给力！

**Comment by nickkong** [comment]
わあ、解決し、すごい

**Comment by devinhee** [comment]
I create a virtual environment, when I run some codes ,give the same Error. And I reinstall tensorflow , but it doesn't work

**Comment by cww97** [comment]
I have another stituation, I have succssfully installed tensorflow on my mac, and a function which uses tensorflow's model can run by its own. However, when I import this fuction in Django, the first line is 'import tensorflow as tf', error: ModuleNotFoundError: No module named 'tensorflow'.. wtf

**Comment by devinhee** [comment]
In a new environment, maybe you need reinstall it. If it doesn't work , try to change the way installing.
At first, I used pip installing, got the error. then I changed to use conda installing, the error gone.

发自坚果 Pro

Weiwen Chen <notifications@github.com> 于 2018年6月15日 下午7:31写道：


I have another stituation, I have succssfully installed tensorflow on my mac, and a function which uses tensorflow's model can run by its own. However, when I import this fuction in Django, the first line is 'import tensorflow as tf', error: ModuleNotFoundError: No module named 'tensorflow'.. wtf

―

**Comment by FatemehAsgarinejad** [comment]
Although it's a long time after this question is asked since I was searching so much for the same problem and couldn't find the extant solutions helpful, I write what fixed my trouble for anyone with the same issue:
The point is, Jupyter should be installed in your virtual environment, otherwise, meaning, after activating the tensorflow environment, run the following in the command prompt (in virtual environment):
- conda install jupyter
- jupyter notebook

and then the jupyter norebook will pop up
