### ISSUE TITLE
theano.clone feature

### ISSUE THREAD

**Issue by 4SkyNet** [tensorflow/tensorflow#5479]
Are there some plans to do extension like a **theano.clone** ?

[Description from a original API:](http://deeplearning.net/software/theano/library/#theano.clone)

`theano.clone(output, replace=None, strict=True, share_inputs=True)`

Function that allows replacing subgraphs of a computational graph.
It returns a copy of the initial subgraph with the corresponding substitutions.

**Parameters:**

- **output** (Theano Variables (or Theano expressions)) – Theano expression that represents the computational graph.

- **replace** (dict) – Dictionary describing which subgraphs should be replaced by what.

- **share_inputs** (bool) – If True, use the same inputs (and shared variables) as the original graph. If False, clone them. Note that cloned shared variables still use the same underlying storage, so they will always have the same value.

It would be great if we can do similar things in **tensorflow** with easy.

**Comment by aselle** [comment]
Closing since this seems to be fixed with pull request #557.
