### ISSUE TITLE
How to output .pb file directly instead of .ckpt checkpoint files during training

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5481]
Now during training session, the output files are all .ckpt  which are very large. Is there any api can output .pb file directly during training. In fact, .ckpt file is not so useful for us, we only care about the final output.

**Comment by sherrym** [comment]
Hi @civilmanxx,

We do not have plans to support outputting .pb files directly. If you are worried about too many checkpoint files taking up space, you can limit the max_to_keep to 1.

Sherry
