### ISSUE TITLE
cmake error: when build libtensorflow-lite.a for arm64.

### ISSUE THREAD

**Issue by FdyCN** [tensorflow/tensorflow#54822]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur 11.6.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest version 2.8.0 [master branch]
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
git clone latest master source, and use this CLI command in /tensorflow/lite dir:
`cmake ../ -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
        -DTFLITE_ENABLE_GPU=ON  \
        -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=21 -DABSL_PROPAGATE_CXX_STD=ON
`

it's OK to build static library libtensorflow-lite.a 
BUT, when i include "c_api.h" and related header(e.g: c_api_types.h) and link libtensorflow-lite.a in my project.
it comes compiling err.
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

cmake err log: (so many same style errs. seems like absl lib is not linked in libtensorflow-lite.a？？)
`/TFLite/TF_master/tensorflow/tensorflow/lite/delegates/gpu/common/model_builder_helper.cc:129:  undefined reference to absl::lts_20211102::OutOfRangeError(absl::lts_20211102::string_view)
/TFLite/TF_master/tensorflow/tensorflow/lite/delegates/gpu/common/model_builder_helper.cc:150: undefined reference to absl::lts_20211102::UnavailableError(absl::lts_20211102::string_view)
`

and then i add this code in /tensorflow/lite/CMakeList.txt:

`
find_package(absl REQUIRED)
if(absl_FOUND)
  message("absl found!")
endif()
`
BUT there is no "absl found!" log. so there is no absl lib found??? but it's really confused...

**Comment by sachinprasadhs** [comment]
Could you try with the 2.8.0 stable branch and let us know if you face the same error. Thanks!
