### ISSUE TITLE
TensorFlow crashing on IBM POWER; request debug advice

### ISSUE THREAD

**Issue by hartb** [tensorflow/tensorflow#5482]
We're seeing various crashes while running TensorFlow on IBM POWER systems with Ubuntu 16.04. We'd welcome any debugging advice or comments, especially about debug features or about reducing the size/complexity of TF to simplify debug.

Problem isolation information:

- Occurs with any of TF 0.9, 0.10, and recent master (e.g. 2cbb9b52 of Oct 26th)

- Occurs while training inception model on ILSVRC 2012 dataset. Model is from: https://github.com/tensorflow/models.git  inception/

- Independent of CUDA / GPU; occurs even if we compile with:
    TF_NEED_CUDA=0
    TF_NEED_GCP=0
    TF_NEED_HDFS=0

- Occurs after varying run times. Appears to occur sooner with higher thread counts. Very possibly a race of some sort.

- Does not occur with Ubuntu 15.10's GLIBC 2.21 (or earlier) but does occur with Ubuntu 16.04's GLIBC 2.23 (or later). So appears to be a problem in (or at least exposed by) GLIBC 2.22 or 2.23.

- TF runs (mostly) clean under valgrind --tool=memcheck. (There are some complaints about bad behavior by python at startup, but then silence. We see similar complaints running other python apps.)

To try to simplify analysis, we're:

- Building without CUDA, GCP, HDFS support

- Limiting threading by forcing tensorflow/core/platform/posix/port.cc NumSchedulableCPUs() to return a small value

- Forcing gcc to perform extra stack checking (updating tf_copts in tensorflow/tensorflow.bzl to include "-fstack-protector-all")

Nature of the crash:

The crash is usually a segfault, and often because a pointer was damaged while it was sitting on the stack.

The damage is quite consistent. Under linux on POWER, pointers to stack and heap will generally have the form 0x00003nnn nnnnnnnn. The damage always seems to be that the high half-word is changed from 0x0000 to 0x0001 (so looks like a short/half is set or incremented).

Occasionally the damaged pointer started life as NULL, and so we end up with a dereference of 0x0001000000000000.

In one case the pointer that was damaged was the stack pointer (r1), which would not normally be itself stored and retrieved from the stack. So maybe in that damage occurred:
a) while the thread was inactive and r1 sitting in a context save area,
b) in some odd case where r1 was saved on the stack, e.g. setjmp() / longjmp().

That suggests the crashing thread may not be the thread that's causing the damage.

I didn't find any obvious matches on stackoverflow (no crash reports with "stack smashing" or "power"). I did see (unresolved) issue #3174 from July, but can't be sure that's related.

**Comment by sherrym** [comment]
A contributor from IBM is currently working on it. We have a PR at the moment.

https://github.com/tensorflow/tensorflow/pull/5450

Maybe you can contact @namrata-ibm for more information.

Sherry

**Comment by hartb** [comment]
Thank you, Sherry.  I'll ping @namrata-ibm, but I guess that other work is unrelated to what we're seeing.  s390 and POWER are separate CPU architectures. It looks like their PR is aimed (at least in part) at adding big-endian support, but our linux on POWER target is little-endian.

**Comment by namrata-ibm** [comment]
@sherrym , Our PR is related to adding Big endian support as @hartb has mentioned. This issue is different.

**Comment by vrv** [comment]
I'd suggest trying to just run a bunch of our different C++ tests in various directories (e.g., tests in framework/, or graph/, or platform/) repeatedly.  We probably won't have very good insight without a way to reproduce it on our side.

**Comment by hartb** [comment]
Thank you, @vrv. The problem is easily reproducible on our systems, but there's so much going on the full TF run that the cause of the damaged stack isn't obvious.

We'll try the component-level tests as you suggest. 

If there are any other debug suggestions, or if anything comes to mind as a bit of code that would be touching sparsely-packed shorts/halves, we'd much appreciate it.  Thank you!

**Comment by hartb** [comment]
Just wanted to give an update on this.  The root cause appears to be a problem in the libpthread code used by Ubuntu 16.04 on POWER. More information is available at:

https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1641241
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1640518
https://sourceware.org/bugzilla/show_bug.cgi?id=20822

The problem is independent of TF version. It's specific to POWER systems, so shouldn't appear on x86. And won't appear on Ubuntu systems prior to 16.04. IBM folks are working to get a fix into GLIBC/libpthread and then will work with Canonical to get a fix published for Ubuntu.

Thank you all for the suggestions!  Closing the issue.
