### ISSUE TITLE
tf.contrib.learn Quickstart tutorial code doesn't run, no attribute 'load_csv'

### ISSUE THREAD

**Issue by fbriggs** [tensorflow/tensorflow#5483]
I am trying to run the sample code in the tutorial here (I named the source file 'tf_iris.py'):
https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html#tf-contrib-learn-quickstart

It gives the following error:

```
  File "tf_iris.py", line 13, in <module>
    training_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TRAINING,
AttributeError: 'module' object has no attribute 'load_csv'
```

I installed TF on OS X using virtualenv, following instructions here:
https://www.tensorflow.org/versions/master/get_started/os_setup.html#virtualenv-installation

The version of TF installed is OS X / Python 2.7 / CPU, i.e.:
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc1-py2-none-any.whl

**Comment by fbriggs** [comment]
This seems to be related:
https://github.com/tensorflow/tensorflow/pull/4864/files

I tried changing the lines that call load_csv as follows, and it fixed the error (although now there are a bunch of other warnings):

```
training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
  filename=IRIS_TRAINING, target_dtype=np.int, features_dtype=np.float32)
test_set = tf.contrib.learn.datasets.base.load_csv_with_header(
  filename=IRIS_TEST, target_dtype=np.int, features_dtype=np.float32)
```

**Comment by martinwicke** [comment]
Your fix is correct -- can you send a PR? The PR you referenced never signed a CLA and unfortunately we cannot accept the change.

**Comment by martinwicke** [comment]
This has been fixed at head.
