### ISSUE TITLE
IndexError: tuple index out of range in tf.Model.fit()

### ISSUE THREAD

**Issue by jormajo** [tensorflow/tensorflow#54835]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **I am using a tutorial script, adapted for a custom dataset** (Tutorial: Training and evaluation with the built-in methods)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows11 Home (10.0.22000 Build 22000)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **n.a**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v1.12.1-71979-ge2609918a1c 2.9.0-dev20220301**
- Python version: **Python 3.10.2**
- Bazel version (if compiling from source): **n.a.**
- GCC/Compiler version (if compiling from source): **n.a.**
- CUDA/cuDNN version: **n.a.**
- GPU model and memory: **n.a.**

**Describe the current behavior**
tf.model.fit() does not show any output and eventually generates an error:

**Traceback (most recent call last):
  File "g:\My Drive\Personal\Spider\Datasets\ModelEGame.py", line 92, in <module>
    history = model.fit(
  File "C:\Users\jordi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\jordi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tensorflow\python\framework\tensor_shape.py", line 908, in __getitem__
    return self._dims[key]
IndexError: tuple index out of range**

**Describe the expected behavior**
The model should get trained with the data provided.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.python.ops.numpy_ops import np_config

# Create a dictionary describing the features.
observ = {
        'data' : tf.io.FixedLenFeature([104], tf.int64),
        'label' : tf.io.FixedLenFeature([], tf.int64) }

# Parse the input tf.train.Example proto using the dictionary above.
def _map_function_1(example_proto):
  return tf.io.parse_single_example(example_proto, observ)

def split_data_label(sample):
    return sample['data'].astype('int16'), sample['label'].astype('int16')

# Import End game data
def load_data() :
    dataset = tf.data.TFRecordDataset('EndGsh.tfrecords')
    parsed_dataset = dataset.map(_map_function_1)
    parsed_and_split_datased = parsed_dataset.map(split_data_label)

    DATASET_SIZE = 10000 # 2836995
    train_size = int(0.7 * DATASET_SIZE)
    val_size = int(0.10 * DATASET_SIZE)
    test_size = int(0.20 * DATASET_SIZE)

    parsed_and_split_datased = parsed_and_split_datased.shuffle(DATASET_SIZE)

    train_dataset = parsed_and_split_datased.take(train_size)
    tAv_dataset = parsed_and_split_datased.skip(train_size)
    val_dataset = tAv_dataset.take(val_size)
    test_dataset = tAv_dataset.skip(val_size)

    return train_dataset, test_dataset, val_dataset

# Define model
np_config.enable_numpy_behavior()

model = keras.Sequential()
model.add(keras.Input(shape=(104,)))
model.add(layers.Dense(64, activation="relu", name="end_game_in"))
model.add(layers.Dense(32, activation="relu", name="end_game_h1"))
model.add(layers.Dense(16, activation="relu", name="end_game_h2"))
model.add(layers.Dense(1, activation="relu", name="end_game_out"))
model.summary()

train_dataset , test_dataset, val_dataset = load_data()

model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer
    # Loss function to minimize
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

print("Fit model on training data")
x_train =[]
y_train = []
count = 0
for it in train_dataset :
    x , y = it
    x_train.append(x.astype("float32"))
    y_train.append(y.astype("float32"))
    count += 1
    if count % 5000 == 0:
        print("Train: ", count)

x_val =[]
y_val = []
count = 0
for it in val_dataset :
    x , y = it
    x_val.append(x.astype("float32"))
    y_val.append(y.astype("float32"))
    count += 1
    if count % 5000 == 0:
        print("Val: ", count)

history = model.fit(
    x_train,
    y_train,
    batch_size=64,
    epochs=5,
    verbose=2,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
    validation_data=(x_val, y_val),
)

# rest of script happens after the error
history.history

# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")

x_test =[]
y_test = []
count = 0
for it in val_dataset :
    x , y = it
    x_test.append(x.astype("float32"))
    y_test.append(y.astype("float32"))
    count += 1
    if count % 5000 == 0:
        print("Test: ", count)

results = model.evaluate(x_test, y_test, batch_size=128)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using predict
print("Generate predictions for 3 samples")
predictions = model.predict(x_test[:3])
print("predictions shape:", predictions.shape)
```

Any data set of x_train.shape() = (104,) y_train.shape() = () produces the same behavior. Script provided uses 10,000 examples, but lower and higher numbers produce same result.

**Other info / logs**

I have tested it in a different computer and got a similar (yet different) error:

**Traceback (most recent call last):
  File "C:\Users\jordi\Google Drive\Personal\Spider\Datasets\modelegame.py", line 92, in <module>
    history = model.fit(
  File "C:\Users\jordi\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\jordi\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\framework\tensor_shape.py", line 902, in __getitem__
    return self._dims[key].value
IndexError: list index out of range**

**Comment by mohantym** [comment]
Hi @jormajo ! You seem to be using a older version (1.x ) version of Tensorflow. But  **y_train.shape() = ()** might be the issue here (as it is  trying to index from a invalid shape).

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!
