### ISSUE TITLE
Not able to cluster Conv1DTranspose layer

### ISSUE THREAD

**Issue by rameshkunasi** [tensorflow/tensorflow#54832]
Hi, 

I am using this code for clustering the conv1d layers.

```
`# Create a base model
base_model = setup_model()
base_model.load_weights(pretrained_weights)


def apply_clustering_to_dense(layer):
  if isinstance(layer, tf.keras.layers.Conv1D):
    return cluster_weights(layer, **clustering_params)
  return layer

clustered_model = tf.keras.models.clone_model(
    base_model,
    clone_function=apply_clustering_to_dense,
)`
```

I am getting below error. Is Conv1DTranspose clustering is possible or not? Can anyone suggest how to solve this.
 
**`Please initialize `Cluster` with a supported layer. Layers should either be a `ClusterableLayer` instance, or should be supported by the ClusteringRegistry. You passed: <class 'keras.layers.convolutional.Conv1DTranspose'>`**

--------------------------------------------------------------------------------------
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` : v2.6.0-rc2-32-g919f693420e 2.6.0

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@rameshkunasi 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by rameshkunasi** [comment]
@sushreebarsa - Updated in the template format

**Comment by rameshkunasi** [comment]
Code snippet to reproduce the issue.

```
import tensorflow as tf
import tensorflow_model_optimization as tfmot

cluster_weights = tfmot.clustering.keras.cluster_weights
CentroidInitialization = tfmot.clustering.keras.CentroidInitialization

time_dat = tf.keras.layers.Input(batch_shape=(1, 16000))
x1 = tf.keras.layers.Conv1D(10, 256, 64, padding = "valid",use_bias=False)(tf.expand_dims(time_dat, axis=-1))
x2 = tf.keras.layers.Conv1DTranspose(1, 256, 64, padding = "valid",use_bias=False)(x1)
model = tf.keras.models.Model(inputs=time_dat, outputs=[x2])

clustering_params = {
  'number_of_clusters': 50,
  'cluster_centroids_init': CentroidInitialization.LINEAR
}

def apply_clustering_to_dense(layer):
  if isinstance(layer, tf.keras.layers.Conv1D):
    return cluster_weights(layer, **clustering_params)
  return layer

clustered_model = tf.keras.models.clone_model(
    model,
    clone_function=apply_clustering_to_dense,
)
```

**Comment by sushreebarsa** [comment]
@rameshkunasi Sorry for the late response!
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by rameshkunasi** [comment]
@sushreebarsa , Can you please add this as a serious issue?

**Comment by sushreebarsa** [comment]
@rameshkunasi Could you please move this issue to close status as we are tracking the other ticket in keras-team/keras repo?
Thanks!
