### ISSUE TITLE
`tf.linalg.tensor_diag_part` lack input dimension checking

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54848]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
input = 6.0
tf.linalg.tensor_diag_part(input) # pass, but it should fail instead
```

**Describe the current behavior**
[`tf.linalg.tensor_diag_part`](https://www.tensorflow.org/api_docs/python/tf/linalg/tensor_diag_part) should accept `input` with rank `2k`, and at least dim 2. It should throw an error in the example code where the shape in `[]`.

**Comment by Cheril311** [comment]
will fix this

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with `tf-nightly-2.11.0-dev20220901` .Please find the gist [here](https://colab.research.google.com/drive/1nRndgGcBgS12FhJsU0xrNwrQQewoHAIp?usp=sharing)

**Comment by cantonios** [comment]
@Cheril311 do you want to retry your PR to fix this?

**Comment by oawxkw** [comment]
I also observed the following API aliases have the same behavior that accepts the `input` with the shape of `[]` without throwing any Exception.

- `tf.linalg.tensor_diag_part`, `tf.compat.v1.linalg.tensor_diag_part`, `tf.compat.v1.diag_part`

This behavior still exists in tensorflow nightly (2.15.0-dev20230907), and users should be cautious when using them on both CPU and GPU.

**Comment by cantonios** [comment]
This works as intended.  The rank need not by >=2.  For a constant tensor it returns the constant, with k=0.
