### ISSUE TITLE
`tf.ragged.row_splits_to_segment_ids` lack input validation

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54849]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
splits = [-16, 4, 2, 5, 5, 7]
result = tf.ragged.row_splits_to_segment_ids(splits) # pass, but it should throw ValueError as splits starts with -16
print(result) 
```

**Describe the current behavior**
[`tf.ragged.row_splits_to_segment_ids`](https://www.tensorflow.org/api_docs/python/tf/ragged/row_splits_to_segment_ids?hl=en) should check `splits` starts with `0`, and throw `ValueError` if invalid.

**Comment by mohantym** [comment]
Thanks @ArrowIntoTheSky ! Added a PR #54920 to address this issue.

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue?

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with `tf-nightly-2.11.0-dev20220901` . Please find the gist [here](https://colab.research.google.com/drive/1GywmoM9kNn7NwIJfqDxHx4BzDN1-dI8T?usp=sharing). Thank you!

**Comment by oawxkw** [comment]
I also observed the following API aliases have the same behavior that accepts the `splits` not started from 0 without throwing any Exception.

- `tf.ragged.row_splits_to_segment_ids`, `tf.compat.v1.ragged.row_splits_to_segment_ids`

This behavior still exists in tensorflow nightly (2.15.0-dev20230907), and users should be cautious when using them on both CPU and GPU.

**Comment by tilakrayal** [comment]
@ArrowIntoTheSky,
I tried to execute the code on tensorflow v2.17 and observed that the code was executed with the output "Tensor("RaggedSplitsToSegmentIds/Repeat/boolean_mask/GatherV2:0", shape=(None,), dtype=int64)" Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7abf69831309e023adb307f86683ede1/untitled.ipynb). Thank you!
