### ISSUE TITLE
Possible bug when instantiating multi RNN cell in PTB LSTM model

### ISSUE THREAD

**Issue by glarchev** [tensorflow/tensorflow#5485]
Note sure whether this is a bug, since TensorFlow API is unclear on this. Would like someone more familiar with TensorFlow to investigate.

The possible bug is in file tensorflow/models/rnn/ptb/ptb_word_lm.py on line 115. The line reads:

cell = tf.nn.rnn_cell.MultiRNNCell([lstm_cell] * config.num_layers, state_is_tuple=True)

According to the API reference, the constructor for MultiRNNCell is:

tf.nn.rnn_cell.MultiRNNCell.__init__(cells, state_is_tuple=True)

where 

cells: list of RNNCells that will be composed in this order.

The following notation:

[lstm_cell] * config.num_layers 

will create a list of size config.num_layers, where each element in the list is a reference to the same object lstm_cell. This potentially means that if we modify one layer of "cell", we will also be modifying all the other layers. Is this what we want?

**Comment by ebrevdo** [comment]
__init__ is the Python constructor. I'm confused by your question.

**Comment by ebrevdo** [comment]
Ah I see.  Yes in this case we want the same cell for each layer.  Reach layer will nevertheless receive it's own parameters, because parameters are not tied to the layer object.
