### ISSUE TITLE
`tf.experimental.numpy.floor_divide` is inconsistent with numpy version when divide by zero

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54856]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
print(np.floor_divide(0,0)) # Outputs 0
print(tf.experimental.numpy.floor_divide(0,0 )) # InvalidArgumentError: Integer division by zero [Op:FloorDiv]
```

**Describe the current behavior**
[`tf.experimental.numpy.floor_divide`](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/floor_divide)  is TF's version of [numpy.floor_div](https://numpy.org/doc/stable/reference/generated/numpy.floor_divide.html?highlight=floor_div#numpy.floor_divide), and users would expect them to have the same behavior. In the special case of divide by zero, `numpy.floor_div` would throw `RuntimeWarning` but still give `0` as output, but `tf.experimental.numpy.floor_divide` would throw an error. 

**Describe the expected behavior**
Expect  `tf.experimental.numpy.floor_divide`  to output `0`, consistent with `numpy.floor_divide`

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/d0fe070770a41fe3f114a1304f705dab/github_54856.ipynb#scrollTo=FNeG5wKCenf6), [2.8](https://colab.sandbox.google.com/gist/mohantym/07d3d19b45c1ceb4bb30a08216c32bdd/github_54856.ipynb#scrollTo=FNeG5wKCenf6) and [nightly](https://colab.sandbox.google.com/gist/mohantym/01ff188588ad69d85ae5b7b668d2ba6c/github_54856.ipynb#scrollTo=FNeG5wKCenf6)(2.9.0dev).

**Comment by rthadur** [comment]
I am not able to reproduce the same if i run as below 

```
import tensorflow as tf
print(tf.__version__)
import numpy as np
print(tf.experimental.numpy.floor_divide(0,0 )) # InvalidArgumentError: Integer division by zero [Op:FloorDiv]
```

can you please check

**Comment by ArrowIntoTheSky** [comment]
Hi @rthadur , if I run the code in your comment, I can reproduce the issue (it throws InvalidArgumentError). Could you please provide which version of TF are you using, and what is the output you get?

**Comment by chunduriv** [comment]
@ArrowIntoTheSky,

This is an intended behavior and the same can also be seen in all cases mentioned below

Using `math` module

```
import math
math.floor(0/0)
```

output:

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-1-054651c01b6b>](https://localhost:8080/#) in <module>()
      1 import math
      2 
----> 3 math.floor(0/0)

ZeroDivisionError: division by zero
```

Using Python

`print('Floor value for 0/0:',0//0)  
`
Output:
```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-4-9fb0c9205c59>](https://localhost:8080/#) in <module>()
----> 1 print('Floor value for 0/0:',0//0)

ZeroDivisionError: integer division or modulo by zero
```

Using `tf.math.floordiv`

```
x=0
y=0
tf.math.floordiv( x, y, name=None)
```
Output:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-e18cb5fc9e77> in <module>()
      3 y=0
      4 tf.math.floordiv(
----> 5     x, y, name=None
      6 )

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

InvalidArgumentError: Integer division by zero [Op:FloorDiv]
```
