### ISSUE TITLE
`tf.raw_ops.RGBToHSV` lack support for bfloat16

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54855]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
images = tf.random.uniform([1, 1, 3], dtype=tf.bfloat16)
tf.raw_ops.RGBToHSV(images=images)
```
throws error:
```
NotFoundError: Could not find device for node: {{node RGBToHSV}} = RGBToHSV[T=DT_BFLOAT16]
All kernels registered for op RGBToHSV:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
 [Op:RGBToHSV]
```
**Describe the current behavior**
[`tf.raw_ops.RGBToHSV`](https://www.tensorflow.org/api_docs/python/tf/raw_ops/RGBToHSV) should support half, bfloat16, float32, float64 according to the document.

**Comment by sushreebarsa** [comment]
@chunduriv Was able to replicate the issue on colab using TF v2.8.0 and tf-nightly(2.9.0.dev20220303), please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/edac82db0255229e1a8a06989716e6d9/54855.ipynb#scrollTo=BxmihNCvCOid).Thanks!

**Comment by yongtang** [comment]
Added a PR #54972 for the fix.
