### ISSUE TITLE
`tf.ragged.segment_ids_to_row_splits` lack check for `out_type`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54851]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
segment_ids = [0,0,0,2,2,3,4,4,4]
res=tf.ragged.segment_ids_to_row_splits(segment_ids, out_type=1) # pass
print(res)
```

**Describe the current behavior**
[`tf.ragged.segment_ids_to_row_splits`](https://www.tensorflow.org/api_docs/python/tf/ragged/segment_ids_to_row_splits?hl=en) should check `out_type` is a valid DType. In the example code, `out_typt` is `1`, so it should raise an error instead of silently pass.

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/becdc149d8a4b7976fb2a19920100e56/54851.ipynb).

**Comment by chunduriv** [comment]
@ArrowIntoTheSky ,

According to [this](https://www.tensorflow.org/api_docs/python/tf/ragged/segment_ids_to_row_splits?hl=en#args), The `dtype` for the return value defaults to `segment_ids.dtype`, or `tf.int64` if `segment_ids` does not have a `dtype`. Thanks!

**Comment by Cheril311** [comment]
@yongtang can you look into this as this should have been solved in https://github.com/tensorflow/tensorflow/pull/54441 however the issue is being reproduced. If not I can add the necessary python validations

**Comment by yongtang** [comment]
The `out_type` relies on `tf.dtypes.as_dtype` for dtype validation. In case of integer, out_type will inteperete the integer as enum of the dtype (`enum 1 == float32`), so a float32 is taken:
https://www.tensorflow.org/api_docs/python/tf/dtypes/as_dtype

Overall, passing `1` is working as expected in this case.

**Comment by ArrowIntoTheSky** [comment]
Thanks @yongtang ! I didn't know that before!
I will close this issue.
