### ISSUE TITLE
Update Cmake minimum requirement to v3.5

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#5487]
As it seems to have appeared an [issue with Cmake 3.3](https://github.com/tensorflow/tensorflow/issues/17#issuecomment-258649999) and the minimum known working Cmake version apparently is 3.5 [(see here)](https://github.com/tensorflow/tensorflow/pull/5071#issuecomment-255490169). Should the minimum requirement be updated on [CmakeLists](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/CMakeLists.txt#L2) to 3.5 and the [readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md#pre-requisites) for minimum 3.5 up to 3.6?
If those changes look relevant and are the ones to be made I could update them and submit a PR.

**Comment by sherrym** [comment]
Sure please submit a PR.

Thanks,
Sherry
