### ISSUE TITLE
Unable to find valid certification path

### ISSUE THREAD

**Issue by taegeonum** [tensorflow/tensorflow#54899]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: source build
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

~/tensorflow$ ./configure
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /home/user/miniconda3/envs/tf-2.5/bin/python3]: /home/user/miniconda3/envs/tf-2.5/bin/python3]^H

Invalid python path: /home/user/miniconda3/envs/tf-2.5/bin/python3 cannot be found.
Please specify the location of python. [Default is /home/user/miniconda3/envs/tf-2.5/bin/python3]: /home/user/miniconda3/envs/tf-2.5/bin/python3

Found possible Python library paths:
  /home/user/miniconda3/envs/tf-2.5/lib/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/home/user/miniconda3/envs/tf-2.5/lib/python3.7/site-packages]
/home/user/miniconda3/envs/tf-2.5/lib/python3.7/site-packages
Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

$ bazel build  --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=252
INFO: Reading rc options for 'build' from /home/user/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/user/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/user/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/user/miniconda3/envs/tf-2.5/bin/python3 --action_env PYTHON_LIB_PATH=/home/user/miniconda3/envs/tf-2.5/lib/python3.7/site-packages --python_path=/home/user/miniconda3/envs/tf-2.5/bin/python3
INFO: Found applicable config definition build:short_logs in file /home/user/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/user/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:opt in file /home/user/tensorflow/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:linux in file /home/user/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/user/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository io_bazel_rules_closure instantiated at:
  /home/user/tensorflow/WORKSPACE:11:14: in <toplevel>
  /home/user/tensorflow/tensorflow/workspace3.bzl:6:17: in workspace
Repository rule http_archive defined at:
  /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_closure':
   Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz, https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_bazel_rules_closure/temp13563286205250891784/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@io_bazel_rules_closure//closure': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz, https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_bazel_rules_closure/temp13563286205250891784/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Elapsed time: 28.763s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by mohantym** [comment]
Hi @taegeonum ! Can you try following steps s?

Step-1: bazel clean --expunge ( it will clean previous builds and cache)
Step-2: Uninstall and Reinstall JDK latest version.
Step-3: Try again  Bazel build with 3.7.2  or 4.2.2 for 2.5 or Bazel 4.2.2 (with   with branch 2.8).

Attaching relevant threads for reference. [1](https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ),[ 2](https://github.com/tensorflow/tensorflow/issues/7497#issuecomment-355743662).

**Comment by taegeonum** [comment]
@mohantym Thanks for the reply! I will share the result after trying the steps.

**Comment by taegeonum** [comment]
Hmm, I reinstalled my jdk (jdk 11) but got the following error 
```
  /home/user/tensorflow/third_party/repo.bzl:65:35: in <toplevel>
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/upb/temp5565003095748082168/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
INFO: Elapsed time: 19.725s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
The error message is different from the previous one, but also has the same exception (unable to find valid certification path). 
Perhaps is this because of firewall? but I'm using proxy and `wget https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz` is successful. 

The attatched reference explains registering certifcate in java toolchain, but I don't have `sudo` permission so cannot execute the keytool command that requires `sudo` permission.

**Comment by gadagashwini** [comment]
@taegeonum, Add these lines in Tensorflow WORKSPACE file

```
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2020-02-14
    ],
)
```

**Comment by taegeonum** [comment]
@gadagashwini I got the following error
```
ERROR: /home/user/tensorflow/WORKSPACE:25:1: name 'http_archive' is not defined
ERROR: error loading package 'external': Package 'external' contains errors
```

**Comment by gadagashwini** [comment]
@taegeonum, 
Try 

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2020-02-14
    ],
)
```

**Comment by taegeonum** [comment]
@gadagashwini I added the code in WORKSPACE, but still got this error:
```
  /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz failed: class javax.net.ssl.SSLHandshakeException
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provi
der.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_closure':
   Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz, h
ttps://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_bazel_rules_closure/temp1303
3208819056549827/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@io_bazel_rules_closure//closure': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee047
1b67a40403df940149.tar.gz, https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_
bazel_rules_closure/temp13033208819056549827/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification pa
th to requested target
```

**Comment by gadagashwini** [comment]
@taegeonum, You need to do `HTTPS SSL certificate` setup on your browser. Follow the workaround mention [#9619030](https://stackoverflow.com/a/12524960/14290244). Thanks!

**Comment by taegeonum** [comment]
@gadagashwini I added the certificate to java keystore as suggested in the link, but still got PKIX error. I also got no such package error `ERROR: no such package '@io_bazel_rules_closure//closure`  
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
WARNING: Download from https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gzfailed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_closure':
   Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz, https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_bazel_rules_closure/temp5120340009819662576/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@io_bazel_rules_closure//closure': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz, https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz] to /home/user/.cache/bazel/_bazel_taegeon.um/f9f5c94ad789d21bcfdb930889866229/external/io_bazel_rules_closure/temp5120340009819662576/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz: PKIX path building failed
```

**Comment by taegeonum** [comment]
@gadagashwini I also added github.com cert to java keystore, but still got the same error. Is there any way 
 to changing `https` to `http`?

**Comment by taegeonum** [comment]
Or is there a workaround for downloading all dependencies in my local machine, and using the downloaded files during bazel build?

**Comment by taegeonum** [comment]
I resolved this issue by changing my proxy server. Thanks for your help
