### ISSUE TITLE
MirroredStrategy with custom model throws AttributeError: 'NoneTensorSpec' object has no attribute 'rank'

### ISSUE THREAD

**Issue by Bidski** [tensorflow/tensorflow#54900]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: 3.10.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.6/8.3
- GPU model and memory: GTX1080Ti 11GB

**Describe the current behavior**
When training a custom model with `keras.fit` and `MirroredStrategy` an `AttributeError` is thrown. Without the `MirroredStrategy` training proceeds without error. I also notice that the console output does not mention something like `INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)` even though the strategy reports having 3 replicas in sync

Code snippet
```
    ### ----- create datasets
    
    strategy = tf.distribute.MirroredStrategy()
    print("Number of devices: {}".format(strategy.num_replicas_in_sync))

    # with strategy.scope():
        model = MyModel()

        # Setup the optimiser with the learning rate schedule
        lr_schedule = CosineDecayWithWarmup(
            initial_learning_rate=args.lr,
            decay_steps=args.num_epochs,
            warmup_steps=args.warmup_steps,
            warmup_learning_rate=args.warmup_lr,
            hold_base_rate_steps=args.hold_base_rate_steps,
        )
        optimiser = tf.keras.optimizers.Adam(learning_rate=lr_schedule)

        # Compile the model
        model.compile(optimizer=optimiser, loss=MyLoss())

    # Build the model and print a summary
    model.build(input_shape=(args.batch_size, image_shape[0], image_shape[1], 3))
    model.summary()

    history = model.fit(
        training_dataset,
        epochs=args.num_epochs,
        validation_data=validation_dataset,
        callbacks=callbacks,
    )
```

Console output
```
2022-03-03 14:30:59.481815: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-03 14:31:00.853869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8972 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1
2022-03-03 14:31:00.854710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 10405 MB memory:  -> device: 1, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1
2022-03-03 14:31:00.855231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 10405 MB memory:  -> device: 2, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:43:00.0, compute capability: 6.1
Number of devices: 3

#### ----- MODEL SUMMARY ----

Traceback (most recent call last):
  File "$HOME/network/train.py", line 279, in <module>
    main()
  File "$HOME/network/train.py", line 242, in main
    history = model.fit(
  File "$HOME/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "$HOME/.local/lib/python3.10/site-packages/tensorflow/python/data/experimental/ops/distribute.py", line 513, in get_static_batch_dim
    if output_shape.rank is None:
AttributeError: 'NoneTensorSpec' object has no attribute 'rank'
```

**Describe the expected behavior**
Network trains with the `MirroredStrategy` with no error.

**Comment by tilakrayal** [comment]
@Bidski ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

**Comment by Bidski** [comment]
Unfortunately a reproducible example is going to be difficult to provide in the short term. I suspect that [this commit](https://github.com/tensorflow/tensorflow/commit/5a8ef901f4f0b50f798feb5429ed4b962a8153a2) might resolve the problem but I don't currently have the time to build tensorflow from scratch to test this theory. Are there any pre-built python wheels (or similar) that contain this commit yet?

Is there any way for me to construct my `tf.data.Dataset` such that this function will work? I am already calling `.batch()` on my dataset.

**Comment by tilakrayal** [comment]
@Bidski ,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide the code.Thanks!

**Comment by Bidski** [comment]
@tilakrayal the code is closed source so I cant provide that and constructing a MWE that show-cases the problem is difficult since I dont know where the problem lies. Are you able to provide any insight at all into what might be going on so that I may try and create a MWE for you?

I tried building tensorflow from source (from current master) to see if the commit I referenced solved the problem and it didnt seem to help.

**Comment by Bidski** [comment]
Ok, I have figured out the problem. I was returning a tuple `(x, y, None)` (being `x`, `y`, `sample_weights`) from my `tf.data.Dataset`. This resulted in the `sample_weights` having a `NoneTensorSpec` which `compute_batch_size()` was not happy about. 

Changing my `tf.data.Dataset` to return just `(x, y)` fixes the problem

**Comment by tilakrayal** [comment]
@Bidski ,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide the code.Thanks!

**Comment by Bidski** [comment]
@tilakrayal please re-read my last comment. I have now solved the problem and I have described what I needed to do in order to fix the problem that I was experiencing.

**Comment by tilakrayal** [comment]
@Bidski ,
Glad the issue got resolved.Could you please feel free to move this issue to closed status.Thanks!
