### ISSUE TITLE
problem with the eager execution

### ISSUE THREAD

**Issue by hapicatto** [tensorflow/tensorflow#54916]
I retrain the resnet152v2 from keras to calassify my own set of image. I did so using a data generator that looks like this:
```
class My_Custom_Generator(Sq):

    def __init__(self, image_filenames, labels, batch_size):
        self.image_filenames = image_filenames
        self.labels = labels
        self.batch_size = batch_size

    def __len__(self):
        return (np.ceil(len(self.image_filenames) / float(self.batch_size))).astype(int)

    def __getitem__(self, idx):
        batch_x = self.image_filenames[idx * self.batch_size: (idx + 1) * self.batch_size]
        batch_y = self.labels[idx * self.batch_size: (idx + 1) * self.batch_size]
        return np.array([
            resize(imread('E:\\data\\allFrames\\' + str(file_name)), (559, 331))
            for file_name in batch_x]) / 255.0, np.array(batch_y)
```
for training the model the code looks like this:
```
 baseModel = EfficientNetB2(weights=None, include_top=False,
                               input_tensor=Input(shape=(559, 331, 3)))
    # construct the head of the model that will be placed on top of the
    # the base model
    headModel = baseModel.output
    headModel = AveragePooling2D(pool_size=(7, 7))(headModel)
    headModel = Flatten(name="flatten")(headModel)
    headModel = Dense(512, activation="relu")(headModel)
    headModel = Dropout(0.5)(headModel)
    headModel = Dense(5, activation="softmax")(headModel)
    # place the head FC model on top of the base model (this will become
    # the actual model we will train)
    model = Model(inputs=baseModel.input, outputs=headModel)
    # loop over all layers in the base model and freeze them so they will
    # *not* be updated during the training process
    for layer in baseModel.layers:
        layer.trainable = False
opt = SGD(learning_rate=0.005, momentum=0.9, decay=1e-4 / 50)
    model.compile(loss="categorical_crossentropy", optimizer=opt,
                  metrics=["accuracy"])
    model.summary()
    NAME = 'resnet152-559x331-{}'.format(int(time.time()))
    tboard_log_dir = os.path.join("C:\\Users\\dsyr\\PycharmProjects\\VideoProcessingProject\\tmp\\checkpoint", NAME)
    model_checkpoint_callback = ModelCheckpoint(
        filepath=tboard_log_dir,
        save_weights_only=False,
        monitor='val_accuracy',
        mode='max',
        save_freq=1000,
        save_best_only=False)
    print("[INFO] training model...")
    model.fit(my_training_batch_generator,
                  steps_per_epoch=int(621108 // batch_size),
                  epochs=50,
                  verbose=1,
                  validation_data=my_validation_batch_generator,
                  validation_steps=int(155277 // batch_size),
                  callbacks=[model_checkpoint_callback])
```
till there there was no problem, I've a couple of thousand images to validate and produce the output. The issue is that I've not been able to get the same prediction with and without the batch generator. 
when I do model.predict(img, verbose=0, use_multiprocessing=True, workers=4)
where img is a numpy array that is the same as generated by the batch I get this:

> 
> in user code:
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\engine\training.py", line 1801, in predict_function  *
>         return step_function(self, iterator)
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\engine\training.py", line 1790, in step_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\engine\training.py", line 1783, in run_step  **
>         outputs = model.predict_step(data)
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\engine\training.py", line 1751, in predict_step
>         return self(x, training=False)
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
>         raise e.with_traceback(filtered_tb) from None
>     File "C:\Users\dsyr\anaconda3\envs\intel\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
>         raise ValueError(f'Input {input_index} of layer "{layer_name}" is '
> 
>     ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 559, 331, 3), found shape=(None, 331, 559, 3)

the exact same error happens if I run the prediction (or training) with the comand "disable_eager_execution()"
it is to say with eager execution eneable batch processing can be done, with the picture in the format I wanted (559, 331, 3) if eager execution is disabled I cant. I've tried even transposing the picture but the result is widly different than the real forecast done in the batch. 
 
I'm using intel-tensorflow 2.8.0 and intel python 3.9.7 on a windows computer without GPU

**Comment by tilakrayal** [comment]
@hapicatto ,
Can you please take a look at this SO link [1](https://stackoverflow.com/questions/70067588/valueerror-input-0-of-layer-sequential-is-incompatible-with-the-layer-expect) and [2](https://stackoverflow.com/questions/67047026/valueerror-input-0-is-incompatible-with-layer-model-expected-shape-none-1499) with the similar error.It helps.Thanks!

**Comment by hapicatto** [comment]
Hello, thanks for your response. I've looked at those before and I'm not declaring the batch size in the network architecture. 
In fact I can feed the network without the data generator but the image has to be transposed. if you notice, the dimensions are flipped in the response.  
I can provide access to a colab notebook so you can check code.

**Comment by hapicatto** [comment]
Link to the colab code: https://colab.research.google.com/drive/1GdzxZn9LjE4JdzW1n0qGmubsTFpDuTTo?usp=sharing
Link to the data and model file: https://drive.google.com/drive/folders/1ZInGRY0FB25LaFcE9vCG1vgqqaGBS2nW?usp=sharing

**Comment by hapicatto** [comment]
@tilakrayal could you check what I mentioned? the entrances to SO that you referenced were not useful. I don't think the bug label was removed correctly
thanks

**Comment by tilakrayal** [comment]
@hapicatto ,
Sorry for the delay response.
Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
