### ISSUE TITLE
TF_CPP_MIN_VLOG_LEVEL and TF_CPP_MIN_LOG_LEVEL do not output log info in TF 2.8.0/2.9

### ISSUE THREAD

**Issue by hshazly** [tensorflow/tensorflow#54925]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20
- TensorFlow installed from (source or binary): Yes
- TensorFlow version (use command below): v2.8.0-2-ge994fb9c3ad and 2.9 (master branch)
- Python version: 3.8.10
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Setting TF_CPP_MIN_LOG_LEVEL and TF_CPP_MIN_VLOG_LEVEL does not work with the latest release 2.8.0 and 2.9 of the master branch (both built from source) -- Nor exporting an envvar before launching the TF script, nor using the os module in the code (tried setting it before and after the tensorflow module import).

For source build, I followed the steps mentioned in the [official guide](https://www.tensorflow.org/install/source
), using the build command: 
`bazel build //tensorflow/tools/pip_package:build_pip_package` 

Both builds are CPU only without CUDA nor ROCm support. 

**Describe the expected behavior**
As discussed in #31870, setting TF_CPP_MIN_LOG_LEVEL=0 and/or TF_CPP_MIN_VLOG_LEVEL=2 should show logging/debugging information regarding the C++ implementation inner operations, memory allocations, etc. 

**Standalone code to reproduce the issue**
```
import os 

#os.environ['TF_CPP_MIN_VLOG_LEVEL'] = "2"

import tensorflow as tf

os.environ['TF_CPP_MIN_VLOG_LEVEL'] = "2"

a = tf.Variable(tf.zeros(shape=(2)), name="a")

print(a)

```

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/769d205b6f4760f538659d358714c4c7/github_54925_2-8.ipynb#scrollTo=zQ0fZ5mhPixF), [2.8](https://colab.sandbox.google.com/gist/mohantym/42528c8349ad1091584bc16f3495cce2/github_54925_2-8.ipynb#scrollTo=8sTRdFNUPQ4M) and[ nightly.](https://colab.sandbox.google.com/gist/mohantym/95db88ce1b0737980d98fe80111069bc/github_54925_2-8.ipynb#scrollTo=8sTRdFNUPQ4M)

**Comment by hshazly** [comment]
Update: I just read in the RELEASE.md file that the TF_CPP_MIN_VLOG_LEVEL environment variable has been renamed to TF_CPP_MAX_VLOG_LEVEL. I tried it and it worked only when `os.environ['TF_CPP_MAX_VLOG_LEVEL'] = "3"` is set before importing the tensorflow module. Closing.

**Comment by luweizheng** [comment]
I am using jax and xla, I tried with `TF_CPP_MAX_VLOG_LEVEL=3 python jax.py` but I can not get logs less than 3. Is there some switch that I have to turn on?
