### ISSUE TITLE
TensorBoard giving all black events and distributions

### ISSUE THREAD

**Issue by CeliaPhoebe** [tensorflow/tensorflow#5493]
Each time after typing "tensorboard --logdir=logs"
only "Starting TensorBoard 29 on port 6006" is shown
so I need to type "http://0.0.0.0:6006" myself.
Then the graph of neural network and histograms are well displayed, 
but events and distributions are all black, like this:

![capture d ecran 2016-11-09 a 11 59 42](https://cloud.githubusercontent.com/assets/18445114/20136246/08436326-a674-11e6-90d8-8d34c6a455ce.png)

Mac OS enivrement, python version 2.7.
I'm sure that the code is good because someone else runs it correctly on his Mac.
What should be the problem?

**Comment by jiny2001** [comment]
Hi, 
What browser do you use? It also happens on my safari and Firefox but chrome looks OK.
I also want it fixed since I need to open chrome every time...

**Comment by CeliaPhoebe** [comment]
@jiny2001 Good point ! I never think about the browser! Thanks! I always use Safari. So the Google tools work best with Google accessories... lol

**Comment by smistad** [comment]
I have the same problem with Firefox and Ubuntu

**Comment by fengsky401** [comment]
@smistad use chrome, it wil be solved

**Comment by attiladoor** [comment]
I had problems on Ubuntu (even 2 devices), and Firefox, and Firefox on Android, but chrome helped. Thanks, great idea. (psi: even on built in Chinese android browser works fine).
