### ISSUE TITLE
Modifying the convolution operation

### ISSUE THREAD

**Issue by sahiliitm** [tensorflow/tensorflow#5495]
Hi,

I wanted to test a modification to the convolutional operation. Which files should I change in the source code to implement and test my modifications? I have seen some [low level .cc code](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/kernels/conv_grad_ops.cc) which seems to implement convolutions. However, I'm not sure about exactly which files I should modify to implement my modification. 

Also is there a cleaner way (as in, a high-level pythonic way) to  test modifications to the convolutional operation without losing out on the speed of Tensorflow?

Thanks!

**Comment by sherrym** [comment]
Hi @sahiliitm ,

I'd start here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/conv_ops.cc.

You can verify your changes by running

bazel test -c opt //tensorflow/python/kernel_tests:conv_ops_test

Sherry

**Comment by aselle** [comment]
For future reference, this question is more appropriately asked on StackOverflow. thanks!

**Comment by mthcom** [comment]
@aselle Could you provide a link to the stackoverflow page you mentioned?
