### ISSUE TITLE
Per thread allocation of MKL primitives

### ISSUE THREAD

**Issue by milpuz01** [tensorflow/tensorflow#54979]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
From source using Docker container script from here: https://github.com/ARM-software/Tool-Solutions/tree/master/docker/tensorflow-aarch64 and container available here: https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse
- TensorFlow version (use command below):
v2.8.0-0-g3f878cff5b6 2.8.0
- Python version:
3.8.10
- Bazel version (if compiling from source):
4.2.2
- GCC/Compiler version (if compiling from source):
10.3.0
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**

We have noticed when running a simple example (https://github.com/ARM-software/Tool-Solutions/blob/master/docker/tensorflow-aarch64/examples/py-api/detect_objects.py) on AArch64 using this container: https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse, with the command line:

`python detect_objects.py -m ./ssd_resnet34.yml -i https://raw.githubusercontent.com/zhreshold/mxnet-ssd/master/data/demo/street.jpg --inter_threads 64 -r 100`

that amount of resident memory grows to ~50GiB. The TF (MKL) build in the container uses oneDNN and Compute Library as backend. When setting TF `inter_op_parallelism_threads` to 1 (via the `--inter_threads` switch in the script) the amount of resident memory is ~2GiB.

We have also noticed that on x86, when running the same script using TF (MKL) build with oneDNN backend, memory grows from 900MiB, when then number of inter parallel threads is 1, to around 1.4GiB when it set to 64. The more significant increase observed on AArch64 is due to additional memory per operation required by Compute Library.

**Describe the expected behavior**

The size of allocated memory should not increase due to change in number of inter parallel threads.

**Standalone code to reproduce the issue**

Run the command line referenced above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

We have tracked the issue down to the per-thread caching here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/mkl_util.h#L1860. For some models when using inter parallelism > 1 it seems that TF starts cloning working threads and each of these thread has its own cache; so it is not aware of same primitives created in other threads.

For this particular model we counted there are about 50 convolution operations. When setting inter parallelism to 64 the number of convolution operations allocated is `64*50`, where `63*50` are simply duplicated. By making this cache global and shared among these multiple threads we have noticed that resident memory doesn’t grow with increased number of threads and it stays flat to ~2GiB on AArch64 when setting inter parallelism to be 64.

**Comment by milpuz01** [comment]
Filing issue as discussed with @penpornk

**Comment by milpuz01** [comment]
Hi @chunduriv, @jvishnuvardhan (cc: @agramesh1 as he helped us earlier with oneDNN-TF integration), another data point that might be useful is that on AArch64 with oneDNN reference build (without using Compute Library) we are also seeing increase in memory consumption growing from ~1.9GiB when using 2 `inter-threads` to ~7.7GiB when using 32 `inter-threads`. 

As noted above this memory bloat doesn't happen if we use single global LRU cache. What we are not sure about with this approach is whether between creation of `MklPrimitive` via  `MklPrimitiveFactory` (e.g. creating `MklConvFwdPrimitive` inside of `MklConvFwdPrimitiveFactory`) and its execution there is anything that is not thread safe that will make two or more threads if using same primitive to get in corrupt state.

**Comment by agramesh1** [comment]
@milpuz01 yes, oneDNN does in some cases uses scratch buffers and stores them in primitives and this could lead to memory bloat.  We are fixing it now so scratch buffer memory is allocated locally when needed.  Here is a PR for fixing it for the matmul primitive https://github.com/tensorflow/tensorflow/pull/54381   We will have PRs in a few days for other primitives.  That should fix the issue.  Also having a global cache may not be thread safe as you mentioned.

CCing @penpornk

**Comment by penpornk** [comment]
@milpuz01 Thank you for creating the issue! 

> For this particular model we counted there are about 50 convolution operations. When setting inter parallelism to 64 the number of convolution operations allocated is 64*50, where 63*50 are simply duplicated. 

What is your `intra_threads` setting? I'm guessing it's also 64? `inter_threads` controls the number of concurrent ops TF can execute at a time, and `intra_threads` controls the number of worker threads (in a separate pool) which all executing ops share. So we expect at most `inter_threads` + `intra_threads` threads running at a time in vanilla TF.

IIUC, the `inter_threads * intra_threads` (50 * 64) threads here is because TF-oneDNN aarch64 backend is still using separate OpenMP/pthread thread pools from TF. So instead of sharing TF's global intra threads thread pool with other vanilla TF ops, each of the 50 oneDNN convolution ops has its own thread pool of size 64, creating 50*64 more threads. We should be able to avoid this threading explosion when the aarch64 backend switches to Eigen thread pool. (We should fix this over-subscription regardless of this per-thread memory issue.)

I think this is because TF-oneDNN aarch64 backend still uses OpenMP/pthread and doesn't take 

> another data point that might be useful is that on AArch64 with oneDNN reference build (without using Compute Library) we are also seeing increase in memory consumption growing from ~1.9GiB when using 2 inter-threads to ~7.7GiB when using 32 inter-threads.

IIRC the reference build is still using separate OpenMP thread pools, so it has the same threading explosion problem.

> oneDNN does in some cases uses scratch buffers and allocates them during primitive creation and this could lead to memory bloat. We are fixing it now so scratch buffer memory is allocated locally when needed. Here is a PR for fixing it for the matmul primitive https://github.com/tensorflow/tensorflow/pull/54381 We will have PRs in a few days for other primitives. That should fix the issue. Also having a global cache may not be thread safe as you mentioned.

Thank you for the quick answer and the PR! I'm looking at it now and will ask more questions there.

**Comment by milpuz01** [comment]
Hi @penpornk,

Thank you very much for your reply.

> What is your intra_threads setting? I'm guessing it's also 64?

For this particular example number of `intra_threads` was set to 64. 

This thread explosion we have also noticed on x86. If we run the same test example in Intel optimised TF docker (available from here: https://hub.docker.com/r/intel/intel-optimized-tensorflow) then total number of threads created by TF when `inter_threads` is 64 and `intra_threads` is 16 is 4177. We have noticed that number of additional threads that is created when changing `inter_threads` both in x86 and AArch64 is function of `OMP_NUM_THREADS`. If `base` is base number of threads when `inter_threads` and `intra_threads`  are 1 then total number of created threads when `inter_threads`  and `intra_threads` are > 1 will be `base + inter_threads*OMP_NUM_THREADS +intra_threads`. This tread explosion we see for this particular model (MLCommons SSD-ResNet34), but for example do not see when using MLCommons ResNet-50 (both run in single stream mode). 

From the stack that we were able to obtain it seems these threads are created by TF's session executors (DirectionSession::CreateExecutors) and are independent to number of oneDNN primitives created (for SSD-ResNet34 model there are 117 primitives in total: 51 convolutions, 65 reorders and 1 pooling as reported by `DNNL_VERBOSE`).

I hope this helps to clarify the issue.

**Comment by tilakrayal** [comment]
@milpuz01,
Have you got the chance to check the respective PR's raised for the same issue that was already merged. Also https://github.com/tensorflow/tensorflow/pull/55925 pull request was raised to use global cache for MKL primitives instead of cache per TensorFlow inter-thread.
https://github.com/tensorflow/tensorflow/pull/55968

Thank you!
