### ISSUE TITLE
gradient tape with rank 0 tensors causes integer division or modulo by zero

### ISSUE THREAD

**Issue by mikegashler** [tensorflow/tensorflow#54984]
**System information**
- Have I written custom code? Yes
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: binary (via apt-get)
- TensorFlow version: 2.3.1
- Python version: 3.8.10
- GPU model: GeForce GTX 1050 Ti Mobile

**Describe the current behavior**
The simple repro below throws the following exception:
```
Traceback (most recent call last):
  File "bug.py", line 16, in <module>
    grads = tape.gradient(loss, model.trainable_variables)
  File "/home/mike/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 1067, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "/home/mike/.local/lib/python3.8/site-packages/tensorflow/python/eager/imperative_grad.py", line 71, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "/home/mike/.local/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/home/mike/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_grad.py", line 228, in _ConcatGradV2
    return _ConcatGradHelper(
  File "/home/mike/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_grad.py", line 118, in _ConcatGradHelper
    concat_dim._numpy().item(0) % input_values[0]._rank())  # pylint: disable=protected-access
ZeroDivisionError: integer division or modulo by zero

```
**Describe the expected behavior**
It should either compute a gradient (or throw a meaningful exception if that is not possible).

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? No

**Standalone code to reproduce the issue**
```
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self) -> None:
        super().__init__()
        self.layer = tf.keras.layers.Dense(1)

    def call(self, inputs: tf.Tensor) -> tf.Tensor:
        return self.layer(inputs)

model = MyModel()
x = tf.zeros((1, 1))
with tf.GradientTape() as tape:
    theta = model(x)[0,0]
    loss = tf.concat([tf.math.cos(theta), tf.math.sin(theta)], axis=0)
grads = tape.gradient(loss, model.trainable_variables)

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @mikegashler ! Could you check this resolved [gist](https://colab.sandbox.google.com/gist/mohantym/f1510dcc3622066522aeb9c5f76df6da/github_54984.ipynb)? Thanks!

**Comment by mikegashler** [comment]
Yes, this works around the problem in my simplified repro. And I see that the relevant difference is that you removed "[0,0]" from the code. I found that changing it to "[0]" also seems to work around the problem.

Unfortunately, I'm having trouble fixing my larger project because I don't understand what specific condition triggers this problem. Is it inappropriate to index a tensor all the way down to a scalar inside of gradient tape? I tried auditing each variable in model.trainable_variables to make sure there are no scalars, but the problem still persists. Is it possible to articulate what I did wrong?

**Comment by mohantym** [comment]
Hi @mikegashler ! I have used [0,0] to instantiate the MyModel class in this line.
`model = MyModel([0,0])` then model(x) instead of `theta = model(x)[0,0]`
Attaching relevant thread for reference.[ 1](https://www.tensorflow.org/guide/keras/custom_layers_and_models), [2](https://colab.sandbox.google.com/github/tensorflow/docs/blob/snapshot-keras/site/en/guide/keras/custom_layers_and_models.ipynb). Thank you!

**Comment by mikegashler** [comment]
Yes, I can follow the recommended structure better. Sorry. I have fixed my code to do that. But this is not relevant to the bug.

This example does not throw any exceptions:
```
from typing import Union, List, Mapping, Any
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self, hidden_units:List[int]):
        super(MyModel, self).__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [tf.keras.layers.Dense(u) for u in hidden_units]

    def call(self, inputs:tf.Tensor) -> tf.Tensor:
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self) -> Mapping[str,Any]:
        return {"hidden_units": self.hidden_units}

    @classmethod
    def from_config(cls, config:Mapping[str,Any]) -> 'MyModel':
        return cls(**config)

model = MyModel([3,2])
model.from_config(model.get_config())
x = tf.zeros((1, 1))
print(x)
with tf.GradientTape() as tape:
    theta = model(x)[0]
    loss = tf.concat([tf.math.cos(theta), tf.math.sin(theta)], axis=0)
grads = tape.gradient(loss, model.trainable_variables)

```
But this example does throw an exception:
```
from typing import Union, List, Mapping, Any
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self, hidden_units:List[int]):
        super(MyModel, self).__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [tf.keras.layers.Dense(u) for u in hidden_units]

    def call(self, inputs:tf.Tensor) -> tf.Tensor:
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self) -> Mapping[str,Any]:
        return {"hidden_units": self.hidden_units}

    @classmethod
    def from_config(cls, config:Mapping[str,Any]) -> 'MyModel':
        return cls(**config)

model = MyModel([3,2])
model.from_config(model.get_config())
x = tf.zeros((1, 1))
print(x)
with tf.GradientTape() as tape:
    theta = model(x)[0,0]
    loss = tf.concat([tf.math.cos(theta), tf.math.sin(theta)], axis=0)
grads = tape.gradient(loss, model.trainable_variables)
```
The only difference is the first (working) example uses "model(x)[0]" and the second (broken) example uses "model(x)[0,0]".

My question is, why does the second (broken) example throw an exception that says "ZeroDivisionError: integer division or modulo by zero"? I did not do an integer division or modulo. I only indexed an element in a tensor.

**Comment by mohantym** [comment]
Hi @Aswini! Could you please look at this issue ? Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/cdcbc43129515e13b0b5c9cf3f354711/github_54984.ipynb#scrollTo=_qVbZcXqav6k) for reference.

**Comment by gadagashwini** [comment]
@mikegashler, 
Loss calculation was concatenating a bunch of scalars together, by changing them from scalars to rank 1 tensors with keep_dims, the error no longer occurs.

```
import tensorflow as tf

class MyModel(tf.keras.Model):
    def __init__(self) -> None:
        super().__init__()
        self.layer = tf.keras.layers.Dense(1)

    def call(self, inputs: tf.Tensor) -> tf.Tensor:
        return self.layer(inputs)

model = MyModel()
x = tf.zeros((1, 1))
with tf.GradientTape() as tape:
    theta = model(x)[0,0]
    loss = tf.math.reduce_mean([tf.math.cos(theta), tf.math.sin(theta)], axis=0,keepdims=True).   #keepdims args will result in scalar output
grads = tape.gradient(loss, model.trainable_variables)
```
Since `tf.concat()` doesn’t have keepdims argument, replace it with `tf.math.reduce_mean().` Thanks!

**Comment by mikegashler** [comment]
Yes, that fixes it. Thanks so much!

(I still don't understand why concatenating scalars inside gradient tape is bad behavior. I hope you'll improve the error message to reflect the problem, but I suppose that's up to you.)
