### ISSUE TITLE
Change HTTP source locations away from Sourceforge

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#5498]
### Problem

There are a bunch of sources downloaded over HTTP during the build process that depend on Sourceforge (libjpeg, giflib, boost, etc.). Unfortunately, Sourceforge presents a download delay at download initiation time, often suffers timeouts, and the download speeds are really slow. This significantly impacts build times.

### Solution

The sources could migrate to a subproject under the TensorFlow Github org, or to another Github repo that could host them, or to a CDN. Whatever the solution may be, this could help prevent timeouts and significantly improve the build speeds.

Note: I could issue a PR but the question is what location for these sources the TensorFlow team would find acceptable as an alternative to SourceForge.

**Comment by drpngx** [comment]
@gunan already changed a bunch of them away from sourceforge. Which ones are you thinking of?

**Comment by gunan** [comment]
https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE
If you are building from source at head, there are no more sourceforge links remaining.
If you are referring to old release branches, I think it's OK to leave them.

Is there anything we are missing?

**Comment by mkolod** [comment]
@drpngx @gunan Ah ok, that must be a very recent development, I was working off of a quite recent but not totally up to date fork. Sorry for a false alarm.
