### ISSUE TITLE
TensorFlow API Versions Hyperlink for 2.7 points to 2.8

### ISSUE THREAD

**Issue by KilnOfTheSecondFlame** [tensorflow/tensorflow#54991]
## URL(s) with the issue:

https://www.tensorflow.org/versions

## Description of issue (what needs changing):
The link to version r2.7 points to `https://www.tensorflow.org/api_docs/python/tf` but should point point to `https://www.tensorflow.org/versions/r2.7/api_docs/python/tf`.

**Comment by sachinprasadhs** [comment]
Thanks for the PR, I have submitted the fix internally which should reflect the updated changes.

**Comment by sachinprasadhs** [comment]
Hi, You can see the changes in the document now. You can close this issue. Thanks!

**Comment by KilnOfTheSecondFlame** [comment]
I verified the changes in the page, all works as expected, thanks @sachinprasadhs =)
