### ISSUE TITLE
TensorFlow Developer Certificate error sign in on pycharm 

### ISSUE THREAD

**Issue by callmekofi** [tensorflow/tensorflow#55027]
I am able to successfully sign in to the Certification Assistant. However, I keep getting this error on pycharm "An error occurred while trying to sign in: Connection reset". I don't know why it happened
![Screenshot 2022-03-05 at 2 43 15 PM](https://user-images.githubusercontent.com/39478293/156871893-b6fcf86b-266a-48a2-9cd6-d568ddb150a1.png)
.

**Comment by mohantym** [comment]
Hi @callmekofi ! Did you try again after disabling your antivirus/VPN or whitelisting the IP address linked with Tensorflow exam ? Can you also confirm that you are on Pycharm version  2021.3?

**Comment by callmekofi** [comment]
I am using pycharm version 2021.3 on apple macbook. I turned off my vpn once i sign in my google account but the result is the same.

**Comment by mohantym** [comment]
Hi @callmekofi ! 

1. Please uninstall then reinstall the Tensorflow certification plugin  and accept policies wherever needed. 

2. Please check from different devices aside macbook( There are performance issue in Mac OS .You can refer https://developer.apple.com/metal/tensorflow-plugin/ for installation in Mac) .

Please post on Tensorflow [Forum](https://discuss.tensorflow.org/) for further assistance ? Thank you!

**Comment by DormouseLi** [comment]
I meet the same problem. I successfully login via the opened browser, but the Pycharm occurs the Time out Error. I have sent the mail the tensorflow-certificate-support@google.com, but still get no reply. My test only left 3 days,.Please help me.
