### ISSUE TITLE
the update ordering in 

### ISSUE THREAD

**Issue by tomandjake** [tensorflow/tensorflow#55023]
**System information**
-  tf_v5    tf.image.NonMaxSupressionWithScore

**Describe the current behavior**
I think there is a little bug in the implementation of *non_max_suppression_op.cc* in the  function *DoNonMaxSuppressionOp*
![image](https://user-images.githubusercontent.com/31850863/156863445-27c3d631-d426-4e9d-89f6-d281ce597503.png)
I has tried to change it as 
![image](https://user-images.githubusercontent.com/31850863/156863575-a06b6771-90ee-47de-9f91-d90b2c1b2458.png)
In some extreme cases, I find they have different results because the value of a\*b\*c\*d != d\*c\*b\*a in numerical meaning and I think my change of the order is the normal order of the NMS algorithm proposed.

**Describe the expected behavior**
Just change the sequence as I showed above.

**Comment by tomandjake** [comment]
a*b*c*d != d*c*b*a 
in numerical meaning.

**Comment by sushreebarsa** [comment]
@tomandjake 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by tomandjake** [comment]
Sorry I has already wirite things according to that template and I do not think this "little and understandable bug" need other information such as My environment and etc. I am not convenient to check those information.

**Comment by sushreebarsa** [comment]
@tomandjake 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
