### ISSUE TITLE
How to make pipeline parallelism in Tensorflow runtime with custom CUDA steam

### ISSUE THREAD

**Issue by Lifann** [tensorflow/tensorflow#55030]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.7
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 7.3.1
- CUDA/cuDNN version: cuda-11.0, cudnn-8.2
- GPU model and memory: A100, 40GB HBM.

# Description
I'm trying to run a recommender-system for advertisement application with TensorFlow, on A100 X 16, and run a sparse embedding_lookup on a model-parallized embedding layer (embedding layer is splitted to 16 partitions on each GPU, and every worker send the lookup indices to others, and gather the lookup  results to local).

One problem is: I'm trying to split a whole batch input into several mini-batches, and let the k-th mini-batch be parallized to the (k+1)-th mini-batch, with a stage step bebind, to overlap the element-wise computations between mini-batches. But I haven't found a method to implement the idea, since the TensorFlow runtime run an op in graph when its upstream ops are finished.

Another problem is in an AsyncOpKernel, I found that a cudaStream created by cudaStreamCreate(), not d.stream(), is not synchronizable to the host code:
```c++
cudaStreamCreate(&custom_stream);
... ...
CUDACHECK(cudaStreamSynchronize(custom_stream));  // Block the custom stream.
CUDACHECK(cudaStreamSynchronize(d.stream()));  // stream from the context->eigen_device<GPUDevice>(), I found it somehow not working (will not wait the custom_stream finished). I'm really confused about it.

```

I struggled with it for several weeks, I will be really appreciated if someone could answer the issue (X0X) !

**Comment by MoFHeka** [comment]
@chunduriv Any latest progress?
