### ISSUE TITLE
Mulitple inputs not parsing properly with dictionary

### ISSUE THREAD

**Issue by tjaqu787** [tensorflow/tensorflow#55037]
I'm getting an error with multiple inputs 
something like this

`    
    customer = Input(shape=(1,), name="customer_id")  # 1-length sequence of ints
    age = Input(shape=(1,), name="age")  # 1-length sequence of ints
    other_customer_input = Input(shape=(None,7), name="customer_info")# 7-length sequence of ints
    other_customer_input = layers.Dense(7,kernel_regularizer='l1')(other_customer_input)
    cust_embedding = layers.Embedding(num_of_cx, 256)(customer)
    dem_embedding = layers.Embedding(num_of_age, 16)(age)

    x = layers.concatenate(axis=2,inputs=[customer_embedding,postal_code_embedding,other_customer_input])
    x = layers.Dense(450,kernel_regularizer='l1')(x)

    pref = layers.Dense(619, name="pref",kernel_regularizer='l1')(x)

    model = tf.keras.Model(
        inputs=[age, customer, other_customer_input],
        outputs=[pref]
    )

    x = layers.concatenate(axis=2,inputs=[customer_embedding,postal_code_embedding,other_customer_input])
    x = layers.Dense(450,kernel_regularizer='l1')(x)
    model.compile()

    X= {"customer_id": data['customer_id'], "age": data['age'], "customer_info": data[cols]}
    Y={"pref": data[cols])}

    pref_model.fit(X,Y,
        epochs=2,
        batch_size=64)
`
This is the full error message 

It's not accepting a dictionary as an input

INFO:tensorflow:Allowlisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x7fb010938940>: DoNotConvert rule for keras
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x7faf82c8cd30>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, ({'customer_id': <tf.Tensor 'args_2:0' shape=(1362281, 1) dtype=int64>, 'age': <tf.Tensor 'args_1:0' shape=(1362281, 1) dtype=float32>, 'customer_info': <tf.Tensor 'args_3:0' shape=(1362281, 7) dtype=float64>}, {'pref': <tf.Tensor 'args_4:0' shape=(1362281, 619) dtype=int64>}))
    kwargs: {}

INFO:tensorflow:Allowlisted: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x7faf82c8cd30>: DoNotConvert rule for keras
Epoch 1/2
INFO:tensorflow:Converted call: <function Model.make_train_function.<locals>.train_function at 0x7faf82c8cdc0>
    args: (<tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x7faf82c9ef40>,)
    kwargs: {}

INFO:tensorflow:Cache hit for <function Model.make_train_function.<locals>.train_function at 0x7faf82c8cdc0> subkey ConversionOptions[{}]: <tensorflow.python.autograph.pyct.transpiler._PythonFnFactory object at 0x7fb0133f89a0>
INFO:tensorflow:Error transforming entity <function Model.make_train_function.<locals>.train_function at 0x7faf82c8cdc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 427, in converted_call
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 269, in _convert_actual
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 282, in transform
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 490, in transform_function
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/pyct/transpiler.py", line 201, in instantiate
ValueError: closure mismatch, requested ('self', 'step_function'), but source function had ()
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x7faf82c8cdc0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Converted call: <function Model.make_train_function.<locals>.step_function.<locals>.run_step at 0x7faf82c8c790>
    args: (({'customer_id': <tf.Tensor 'IteratorGetNext:1' shape=(None, 1) dtype=int64>, 'age': <tf.Tensor 'IteratorGetNext:0' shape=(None, 1) dtype=float32>, 'customer_info': <tf.Tensor 'IteratorGetNext:2' shape=(None, 7) dtype=float64>}, {'pref': <tf.Tensor 'IteratorGetNext:3' shape=(None, 619) dtype=int64>}),)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function Model.make_train_function.<locals>.step_function.<locals>.run_step at 0x7faf82c8c790>: DoNotConvert rule for keras

**Comment by mohantym** [comment]
Hi @tjaqu787 ! Could you please share the above code as a Colab gist? Thanks!
