### ISSUE TITLE
TFLite Python:  interpreter._get_tensor_details(index) can't read tensor with sparsity

### ISSUE THREAD

**Issue by zk-talentech** [tensorflow/tensorflow#55040]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.0
- Bazel version (if compiling from source):  5.0.0
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

In the Python code below, load the [Mediapipe pose_detection tflie model](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite), and try to get details of tensor index 15. The program crashes during `interpreter._get_tensor_details(15)`, and the `print(details)` never executes.

```
import tensorflow as tf

interpreter = tf.lite.Interpreter("pose_detection.tflite")
details = interpreter._get_tensor_details(15)
print(details)
```

I analysed it and found the call stack is
`interpreter._get_tensor_details(index)` ->
`_interpreter.TensorSparsityParameters()` ->
`InterpreterWrapper::TensorSparsityParameters()` ->
`PyDictFromSparsityParam()` ->
`PyArrayFromIntVector()`

tensorflow\lite\python\interpreter.py
```
  def _get_tensor_details(self, tensor_index):
  ...
    tensor_sparsity_params = self._interpreter.TensorSparsityParameters(
        tensor_index)
```

tensorflow\lite\python\interpreter_wrapper\interpreter_wrapper.cc
```
PyObject* InterpreterWrapper::TensorSparsityParameters(int i) const {
  TFLITE_PY_ENSURE_VALID_INTERPRETER();
  TFLITE_PY_TENSOR_BOUNDS_CHECK(i);
  const TfLiteTensor* tensor = interpreter_->tensor(i);
  if (tensor->sparsity == nullptr) {
    return PyDict_New();
  }

  return PyDictFromSparsityParam(*tensor->sparsity);
}


PyObject* PyDictFromSparsityParam(const TfLiteSparsity& param) {
  PyObject* result = PyDict_New();
  PyDict_SetItemString(result, "traversal_order",
                       PyArrayFromIntVector(param.traversal_order->data,
                                            param.traversal_order->size));
  PyDict_SetItemString(
      result, "block_map",
      PyArrayFromIntVector(param.block_map->data, param.block_map->size));
...
}

PyObject* PyArrayFromIntVector(const int* data, npy_intp size) {
  void* pydata = malloc(size * sizeof(int));
  memcpy(pydata, data, size * sizeof(int));
  PyObject* obj = PyArray_SimpleNewFromData(1, &size, NPY_INT32, pydata);
  PyArray_ENABLEFLAGS(reinterpret_cast<PyArrayObject*>(obj), NPY_ARRAY_OWNDATA);
  return obj;
}
```

In the tensor index 15 of pose_detection.tflite, `tensor->sparsity` is not null, but `tensor->sparsity->traversal_order->data` is null.
So the `memcpy()` in `PyArrayFromIntVector()` crashed with null pointer exception.

Could you check why pose_detection.tflite can be inferred normally in Mediapipe, but can't be read by `interpreter._get_tensor_details(index)`?
Thanks.

**Comment by mohantym** [comment]
I could replicate this issue in 2.8 . Used two different pose net models  (one from [Tensorflow site ](https://storage.googleapis.com/download.tensorflow.org/models/tflite/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite)and another from [mediapipe](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite)) . I saw there is a difference coming from gist and  with Netron view. Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/e87ceacd1d468ad6bc9a04890b0354e4/git_55040.ipynb) for reference. Thanks!

**Comment by pjpratik** [comment]
Hi @zk-talentech 

I was checking if the issue still persists. Seems like mediapipe `tflite` model is unavailabe at [pose detection](https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/).

The `interpreter._get_tensor_details()` require tensor index as well the sub graph index. If the model has only one subgraph, try

`interpreter._get_tensor_details(15,0)`

that should give the tensor details at the index 15. Indexing beyond sub graph indices might lead to the program crash.

I have tested with [Movenet multipose](https://tfhub.dev/google/lite-model/movenet/multipose/lightning/tflite/float16/1) tflite model available in tf hub and was able to get the tesnor details at an index. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/5f13c0060ebd54436118926ffbca5a56/55040.ipynb).

Thanks.
