### ISSUE TITLE
Android arm64-v8a (armv8) native libs build error

### ISSUE THREAD

**Issue by kevinmost** [tensorflow/tensorflow#5504]
Hello,

I am encountering an error trying to build Tensorflow for arm64-v8a. *All other architectures build successfully*.

Operating system: OS X 10.11
Tensorflow repo commit: v0.11.0rc2 (tagged release)

From the Tensorflow repository root directory, I run:

```
bazel build -c opt //tensorflow/examples/android:tensorflow_native_libs \
--crosstool_top=//external:android/crosstool \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--verbose_failures \
--cpu=arm64-v8a
```

The error emitted is:

```ERROR: /Users/kevin/work/mobile-sdk/android/sdk/tensorflow/tensorflow/examples/android/BUILD:14:1: Linking of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed: aarch64-linux-android-gcc failed: error executing command
  (cd /private/var/tmp/_bazel_kevin/47b9700ecb360f2f1d6606e4f92873e1/execroot/tensorflow && \
  exec env - \
  external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc -shared -o bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/examples/android/libtensorflow_demo.so -Wl,-whole-archive bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/imageutils_jni.o bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/rgb2yuv.o bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/yuv2rgb.o bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/contrib/android/libandroid_tensorflow_inference_jni.lo bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/core/libandroid_tensorflow_lib.lo bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/core/libandroid_tensorflow_lib_lite.lo bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/tensorflow/core/libprotos_all_cc.a bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/external/protobuf/libprotobuf.a bazel-out/aarch64-linux-android-4.9-gnu-libstdcpp-opt/bin/external/protobuf/libprotobuf_lite.a -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libsupc++.a -landroid -ljnigraphics -llog -lm -z defs -s '-Wl,--icf=all' -Wl,--version-script tensorflow/contrib/android/jni/version_script.lds -lz -static-libgcc -no-canonical-prefixes '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: unrecognized option '--icf=all'
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: use the --help option for usage information
```

As stated, I have built several other architectures successfully with this method (changing the `cpu` flag to `armeabi-v7a`, `x86`, `x86_64` all build successfully).

Thanks for any help! Let me know if I can provide any more info.

**Comment by andrewharp** [comment]
If you remove `"-Wl,--icf=all",  # Identical Code Folding` from the linkopts of libtensorflow_demo.so, does it build successfully?

**Comment by kevinmost** [comment]
@andrewharp Yes, that works. I commented out that line in `tensorflow/examples/android/BUILD` and it builds successfully. 

Is there any reason why that option fails only on arm64, and if it's not easily-fixed, is there a way to make it so that that option is only used on non-arm64 architectures? I'm building Tensorflow for arm, arm64, x86, and x64 for a project I'm working on, and it'd be nice not to have to edit between builds so I can automate the process.

Alternatively, can the option be omitted for all architectures? I'm not entirely sure what the ramifications of doing that would be.

Thanks!

**Comment by andrewharp** [comment]
@kevinmost 
I don't think we need the config setting for the demo, so I'll remove it to make things simpler.

In general, though, you can use the various if_android*() methods defined in tensorflow.bzl to customize your srcs/deps/flags appropriately for different target platforms.

**Comment by andrewharp** [comment]
`-Wl,--icf=all` was removed from libtensorflow_demo.so in https://github.com/tensorflow/tensorflow/commit/1a08f5e79266a2e83106ab7f9e17c3787da57703#diff-06b90d704990e9b4f5adadb18c837b64, so this should no longer be an issue.
