### ISSUE TITLE
Error during Inference of LSTM Tflite model

### ISSUE THREAD

**Issue by MTawfik93** [tensorflow/tensorflow#55065]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster
- TensorFlow library (version, if pip package or github SHA, if built from source): tflite-runtime 2.7 compiled using pip 
- Device: Raspberry pi 4 32 bit armv7l

### 2. Issue

I did create a custom LSTM model using the below architecture

```
def My_LSTM(X_train, y_train, X_test, y_test):
    model = Sequential()
    model.add(Masking(mask_value= -27/255 , input_shape=(None, 600)))
    model.add(LSTM(32, return_sequences=True))
    model.add(LSTM(32, return_sequences=False))
    model.add(Dropout(0.5))
    model.add(Dense(16,activation='tanh'))
    model.add(Dropout(0.5))
    model.add(Dense(4,activation='softmax'))

    model.compile(loss = 'sparse_categorical_crossentropy', optimizer= Adam(learning_rate = 1e-3, decay = 1e-6),metrics = ['accuracy'])

    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, min_lr=1e-9)
    stop = EarlyStopping(monitor='val_accuracy', patience=20, verbose=1, mode='auto', baseline=None, restore_best_weights=True)

    
    model.fit(X_train, y_train, epochs=40, batch_size= 128, validation_data=(X_test, y_test), callbacks=[reduce_lr, stop], verbose =1)
    
    
    return model
```

and then I did convert it to tflite extension using the following converter, which successfully converted the model.

```
def Create_tflite_Model(ModelName, savePath):
    
    keras_model = tf.keras.models.load_model(ModelName, compile = False)
    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.experimental_new_converter=True
    converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS]
    tflite_model = converter.convert()
    tflite_model_dir = pathlib.Path(savePath)
    tflite_model_file = tflite_model_dir/"My_model.tflite"
    tflite_model_file.write_bytes(tflite_model)
    
    return tflite_model
```

I did make inference using ``` tf.lite.Interpreter ``` in Tensorflow 2.7 on my PC and was working fine. But when I migrate to my Raspberrypi 4 with armv7l 32bit and try to make inference using ```tflite-runtime 2.7``` using the following code: 

```
Super_Interpreter = tf.lite.Interpreter(model_path='My_model.tflite')
Super_Interpreter.get_signature_list()
Super = Super_Interpreter.get_signature_runner('serving_default')
Result = Super(masking_input = "File to Classify")
object = np.argmax(Result.get('dense_1'))
print(Classes[object])
```

It returns this error: 

```
RuntimeError: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_selectNode number 14 (FlexTensorListReserve) failed to prepare.
```

I also tried using tflite-runtime 2.5 which returns this error:
``` Unsupported data type 14 in tensor  ``` 

In addition, I tried using the tensorflow 2.4 library on armv7l, which is the last version that can be installed on this system and tried making the same inference but I still get this error:
``` Unsupported data type 14 in tensor  ``` 

Is there any solution for this issue?

**Comment by sushreebarsa** [comment]
@MTawfik93 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment]
@MTawfik93,
Use tflite_runtime 2.6 or higher. There shouldn't be any additional step to run the the delegate. Take a look at the guide to use Select TF ops is in https://www.tensorflow.org/lite/guide/ops_select#run_inference. Similar issue [#40157](https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-956002355). Thanks!

**Comment by MTawfik93** [comment]
> @MTawfik93, Use tflite_runtime 2.6 or higher. There shouldn't be any additional step to run the delegate. Take a look at the guide to use Select TF ops is in https://www.tensorflow.org/lite/guide/ops_select#run_inference. Similar issue [#40157](https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-956002355). Thanks!

I did try doing this but unfortunately still having the same error. I did solve it by upgrading the hardware to arch64 and installing a tensorflow 2.7 for Arm and using ```tf.lite.Interpreter``` function, but never succeeded in running the ```tflite_runtime``` using the LSTM tflite model, always running into the same error that I mentioned earlier.

**Comment by pjpratik** [comment]
@MTawfik93 The code seems to be working on TF 2.11 and tflite_runtime==2.11. Could you please check the  gist [here](https://colab.research.google.com/gist/pjpratik/88a544702f3e834c4be2627ced3633d8/55065.ipynb) and let us know if it helps. Thank you.
