### ISSUE TITLE
Cannot find documentation on how to use FILE autosharding

### ISSUE THREAD

**Issue by hunse** [tensorflow/tensorflow#55072]
## URL(s) with the issue:

https://tensorflow.google.cn/guide/distributed_training?hl=en

### Clear description

I would like to use the FILE autoshard policy for my distributed training. However, I cannot find any examples in the documentation of how to do this. I am using the Librispeech dataset, which is split across many audio files. I have created a `tf.data.Dataset` that is the list of the file names (as strings), but when I try to use it, I get errors of the form ``AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy``. There are a number of Github issues discussing this problem, and I think the fact that there are no concrete examples of using FILE sharding is a contributor to this. (The other contributor is many people using Tensor-based datasets rather than file-based ones, and this is what was addressed in the discussion of those Github issues, not how to actually make a file-based dataset suitable for sharding.)

The fact that this warning even comes up in the examples on the "Distributed Training" page again highlights the fact that this warning is something users will see regularly. The warning itself tells users how to turn it off (good, though some including myself have had problems actually getting it to turn off), but nowhere have I seen anything pointing to how to actually get FILE sharding working.

### Usage example

No, there is no usage example, which is the core problem here I believe. I would be happy to contribute one, except I cannot get this working myself, hence the request for an example.

**Comment by gadagashwini** [comment]
@hunse, Try `tf.data.experimental.DistributeOptions()`, which has AutoShardPolicy and represents options for distributed data processing. For more information refer [link](https://www.tensorflow.org/api_docs/python/tf/data/experimental/DistributeOptions). Thanks!

**Comment by hunse** [comment]
Hi @gadagashwini. That documentation is about changing the AutoShardPolicy, which is not what I want to do. The default of AUTO attempts FILE-based sharding, and falls back on DATA-based sharding if that doesn't work. What I want to know is, why isn't FILE-based sharding working for my dataset? Obviously, that's an in-depth question that depends on the specifics of my dataset. However, what I am requesting is a general example of using FILE-based sharding with a dataset. How does one set up a `tf.data.Dataset` so that FILE-based sharding will work? This seems like a common use-case, and an example would be very useful addition to the documentation.

**Comment by gadagashwini** [comment]
@hunse, `tf.data.Dataset` has class called shard, which creates a Dataset that includes only `1/num_shards` of this dataset.
Take a look at this [info](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#important_caveats_2). Thanks!

**Comment by hunse** [comment]
@gadagashwini If I want to use `tf.data.Dataset.shard` to manually shard my data for multiple GPUs, how do I then provide those different shards to the different GPUs? Can I do this with `tf.keras.Model.fit`, or do I need to write a custom training loop? There's a basic example of a custom training loop [here](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy), but it's still not clear to me how I would modify that example to use the shards. Furthermore, it would be nice to be able to use `tf.keras.Model.fit`, since that's what I'm currently using for single-GPU training, and moving away from that is both more work and more potential for mistakes on my part.

There's also some information [here](https://www.tensorflow.org/tutorials/distribute/input), but that example also uses auto-sharding, not manual sharding. Again, this emphasizes the need for an example of using a `tf.data.Dataset` with FILE-based autosharding.

I feel like you're getting away from the point, though. There's obviously a use-case for FILE-based autosharding, since otherwise it wouldn't be part of TensorFlow. Somebody wrote it, and there must be some way to use it. How? I really think that this warrants an example, especially since you're not able to point me towards a piece of documentation that details how to write a dataset suitable for FILE-based autosharding.

**Comment by sachinprasadhs** [comment]
Hi, You can follow [this](https://www.tensorflow.org/tutorials/distribute/input) tutorial for distribution strategies which shows the details and usage of `AutoShardPolicy`. 
 Also, you can refer [this](https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy) document for type of options to use in `AutoShardPolicy`.

**Comment by aaudiber** [comment]
Hi @hunse. The example in https://www.tensorflow.org/tutorials/distribute/input#sharding demonstrates how to set the sharding policy:

```python
dataset = tf.data.Dataset.from_tensors(([1.],[1.])).repeat(64).batch(16)
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.FILE
dataset = dataset.with_options(options)
```

This will "just work" as long as the dataset begins with a list of files. If the dataset doesn't begin with a list of files, you'll see an error along the lines of `Found an unshardable source dataset: name: "foo"`. What unshardable source dataset are you seeing?
