### ISSUE TITLE
nvcc warning: option '--relaxed-constexpr' has been deprecated

### ISSUE THREAD

**Issue by Samurais** [tensorflow/tensorflow#5507]
# Description

Build with CUDNn 5, CUDA 8.0, tensorflow 0.11.0 rc1.

```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

Get a lot ```Too many warnings: nvcc warning option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.```

![image](https://cloud.githubusercontent.com/assets/3538629/20159915/ae552718-a71e-11e6-9f94-043d7f382e17.png)

In the console, this happens a lot, any way to turn it off?

**Comment by benbarsdell** [comment]
This was fixed and then reverted; not sure why (perhaps to support CUDA 7.0?).

https://github.com/tensorflow/tensorflow/pull/5256

**Comment by aselle** [comment]
@gunan, do you have any thoughts about this?

**Comment by vrv** [comment]
Yes, we still need to support CUDA 7.0 for a bit longer.  I'm hoping we can drop support for 7.0 soon though.

**Comment by gunan** [comment]
Yes, I made the change, but it broke all our cuda 7 builds.
Once we can drop our cuda7 builds, we will roll forward with the fix.
For now, we cannot really do anything about this.
