### ISSUE TITLE
Lock contention in thread pool for CPU-based tensor operations

### ISSUE THREAD

**Issue by jeremybarnes** [tensorflow/tensorflow#551]
Running the December 15 Inception model, with either serial or parallel inference steps, is showing serious lock contention on the thread pool lock, with about 50% of the CPU being spent in futex operations:

<img width="1296" alt="jeremy_khan____projects_mldb" src="https://cloud.githubusercontent.com/assets/112556/11910933/8f720e80-a5d3-11e5-9a03-33ad7985fe3f.png">

As an experiment, replacing the mutex with a basic spinlock reduces latency by around 35% (whilst obviously increasing CPU usage due to all of the CPUs constantly spinning even with nothing to do).  Obviously a pure spinlock is not a viable solution, but it shows that there is some scope for improvement.

This leads to three related questions:

1.  Would it be possible to allow the platform to provide its own thread pool implementation or factory?  The ThreadPool methods are virtual, so it would be possible to make it pluggable, except that the class is directly created wherever used.  In our case we have a separate thread pool that has a broadly compatible interface and we'd like to share with TensorFlow.
2.  Would it make sense to reduce the granularity of the Eigen tensor operation multithreading?
3.  If not, is there any interest in a lock free thread pool implementation?  Or is this something that somebody is already working on?

**Comment by benoitsteiner** [comment]
We are aware of the fact that there are cases where we shard the processing of the Eigen tensors too much, and plan to address this in the future. In the meantime, I'd be very happy to replace the current implementation of the ThreadPool class with a lock free implementation if you can contribute one. It would help speed things up quite a bit.

**Comment by vincentvanhoucke** [comment]
As of change `ab02c5`, we consider the CPU scaling issue generally resolved, so I'm going to close this bug. Please file new issues with benchmarks and steps to reproduce if you still see any performance issues.
