### ISSUE TITLE
Support pad_sequences in Autograph

### ISSUE THREAD

**Issue by victorconan** [tensorflow/tensorflow#55118]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.8.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The following works in eager:
```
def pad_function(x):
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(x,padding='post')
    return padded_inputs

pad_function([tf.constant([[1, 2, 3], [1, 2, 3]]), tf.constant([[1, 2, 3]])])

>> output:
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [0, 0, 0]]], dtype=int32)
```
However, when having the @tf.function decorator, it does not work:
```
@tf.function
def pad_function(x):
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(x,padding='post')
    return padded_inputs

>> output:

ValueError: `sequences` must be a list of iterables. Found non-iterable: Tensor("x:0", shape=(2, 3), dtype=int32)
```

If you have any other workarounds, please let me know. Much appreciated! Thanks!
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Everyone who uses tensor padding
**Any Other info.**

**Comment by sushreebarsa** [comment]
@victorconan I tried to replicate the provided code on colab using TF v2.8.0 and didn't face the error as reported.Could you please have a look at  the [gist](https://colab.research.google.com/gist/sushreebarsa/0c0e28958acd29fbd418206b9a5d3919/55118.ipynb) and let us know if we are missing something to reproduce the issue?Thanks!

**Comment by victorconan** [comment]
> gist

Hi, can you run it again? it clearly threw the same error if you run the @tf.function decorated one.

**Comment by sushreebarsa** [comment]
@victorconan Thank you for the response. 
I was able to reproduce this issue. 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by victorconan** [comment]
> @victorconan Thank you for the response. I was able to reproduce this issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thanks!

Do you believe this is a Keras issue? Keras guys believed this is a tensorflow issue...

**Comment by victorconan** [comment]
> @victorconan Thank you for the response. I was able to reproduce this issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thanks!

Do you believe this is a Keras issue? Keras guys believed this is a tensorflow issue...

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
