### ISSUE TITLE
Instantiating a `tf.keras.applications` Model Nullifies Augmentation Layers

### ISSUE THREAD

**Issue by beneyal** [tensorflow/tensorflow#55113]
Hi! 👋 

I'm having a very weird problem which I couldn't find in the Issues tab, so I hope I'm not duplicating anything.

First, I'm using TensorFlow v2.8.0 on Google Colab (Python v3.7.12).

When creating an augmentation layer, be it a single layer, or a `tf.keras.Sequential` collection of them, they work as expected.
However, right after instantiating a model from `tf.keras.applications` (I've seen it happen with EfficientNetB0 and ResNet152V2), the augmentation layers become a no-op. This behavior does not occur with TensorFlow v2.7.0 on Colab.

A Colab notebook showing this behavior can be found here: https://colab.research.google.com/drive/14K2-OgcPjkHRk2aeOMnW1CnaThow6Fia?usp=sharing

Thank you for your time and patience,
Ben

**Comment by chunduriv** [comment]
@beneyal, Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by beneyal** [comment]
Thank you, will do 🙂

**Comment by chunduriv** [comment]
@beneyal,

Can you please close this issue, since it is tracked [there](https://github.com/keras-team/keras/issues/16189). Thanks!
