### ISSUE TITLE
I cannot start my tensorflow certificate exam due to error

### ISSUE THREAD

**Issue by deeplearner2022** [tensorflow/tensorflow#55128]
So i purchased the tensorflow exam and tried to start it, however for some wierd reason i cannot start the exam. the error in the screenshot keeps coming at every try
![Uploading Screen Shot 2022-03-08 at 3.17.40 AM.png…]()

Does anyone know the solution to this

**Comment by chunduriv** [comment]
@deeplearner2022,

I am not able to access attached screenshot. Please can you share once again. Thanks!

**Comment by deeplearner2022** [comment]
<img width="896" alt="Screen Shot 2022-03-08 at 3 17 40 AM" src="https://user-images.githubusercontent.com/101177094/157224841-163bd9b6-bf4c-4486-9dd3-9c9b22468147.png">
@chunduriv @tilakrayal here it is

**Comment by deeplearner2022** [comment]
<img width="998" alt="Screen Shot 2022-03-08 at 3 45 19 PM" src="https://user-images.githubusercontent.com/101177094/157261868-d952c82c-30fd-46ce-ac66-9486b28d82e8.png">
Just to add, This is what it shows on the Trueability website, yet the plugin doesnt work

**Comment by deeplearner2022** [comment]
I tried, its still the same error

**Comment by chunduriv** [comment]
@deeplearner2022,

Thanks for reaching out.
For general support and questions regarding the Google Tensorflow Developer Certification, please contact tensorflow-certificate-support@google.com. Thanks!

**Comment by Kyrpel** [comment]
Have you tried to uninstall  the plugin and re-install it?

**Comment by deeplearner2022** [comment]
Thanks for your response. Yes I did that and still I keep getting the same
error message

**Comment by chunduriv** [comment]
@deeplearner2022,

As suggested please refer this [link](https://github.com/tensorflow/tensorflow/issues/55128#issuecomment-1062547263) and also this is not a feature or bug for Tensorflow. Please feel free to close this issue. Thanks!
