### ISSUE TITLE
please publish TensorFlowLiteObjC 2.8

### ISSUE THREAD

**Issue by v7lin** [tensorflow/tensorflow#55137]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
Android 2.8
iOS 2.7
- Are you willing to contribute it (Yes/No):
NO

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by sushreebarsa** [comment]
@v7lin 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your feature and please specify the use cases for this feature. Thanks!
