### ISSUE TITLE
Unit test build failure - fatal error: mlir/Parser.h: No such file or directory

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#55133]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Unit test build fails with

# Execution platform: @local_execution_config_platform//:platform
tensorflow/core/function/runtime_client_test.cc:25:10: fatal error: mlir/Parser.h: No such file or directory
   25 | #include "mlir/Parser.h"  // from @llvm-project
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --config=nonccl --verbose_failures --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --jobs=75 -- //tensorflow/... -//tensorflow/compiler/tf2tensorrt/... -//tensorflow/compiler/xrt/... -//tensorflow/core/tpu/... -//tensorflow/go/... -//tensorflow/java/... -//tensorflow/python/integration_testing/... -//tensorflow/tools/toolchains/... -//tensorflow/lite/... -//tensorflow/python/tools/... -//tensorflow/compiler/mlir/lite/tests:const-fold.mlir.test -//tensorflow/compiler/mlir/lite/tests:prepare-tf.mlir.test -//tensorflow/python/data/experimental/kernel_tests/service:fault_tolerance_test -//tensorflow/python/eager:function_test -//tensorflow/python/kernel_tests/linalg:self_adjoint_eig_op_test

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Header file was moved by https://github.com/llvm/llvm-project/commit/9eaff42360f4430e2baba28dd8d119137caae486

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by mohantym** [comment]
@elfringham !Thanks for the PR #55134 . This issue will be closed once PR is merged.

**Comment by elfringham** [comment]
Made moot by https://github.com/tensorflow/tensorflow/commit/214d2ed3ff4228e92f246873d3ff535bdb7de35a
