### ISSUE TITLE
AttributeError: 'module' object has no attribute 'global_variables_initializer'

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#5514]
when I was trying a multi gpu training using `python cifar10_multi_gpu_train.py --num_gpus=2`, I got an error:
```
usr@linux:~/tensorflow_source/tensorflow/tensorflow/models/image/cifar10$ python cifar10_multi_gpu_train.py --num_gpus=2
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Traceback (most recent call last):
  File "cifar10_multi_gpu_train.py", line 280, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "cifar10_multi_gpu_train.py", line 276, in main
    train()
  File "cifar10_multi_gpu_train.py", line 229, in train
    init = tf.global_variables_initializer()
AttributeError: 'module' object has no attribute 'global_variables_initializer'
```
Seemingly there's no `global_variables_initializer` of tf or in other module?

**Comment by schmiflo** [comment]
This was introduced lately. Consider upgrading tf or use `tf.intialize_all_variables` .

**Comment by zakizhou** [comment]
@schmiflo thanks, I will try it

**Comment by liusida** [comment]
@schmiflo you mean `tf.initialize_all_variables`
there is a typo.

**Comment by zakizhou** [comment]
@liusida I changed `global_variables_initializer` into `initialize_all_variables`, and it did work, I haven't updated my tf to the latest version, maybe it has already had `global_variables_initializer`

**Comment by yangliuy** [comment]
It works! Thank you!
 I changed global_variables_initializer into initialize_all_variables.

**Comment by liusida** [comment]
@zakizhou yes, i think you are right.

https://github.com/tensorflow/tensorflow/blob/20c3d37ecc9bef0e106002b9d01914efd548e66b/tensorflow/python/ops/variables.py#L1170

```
@deprecated("2017-03-02", "Use `tf.global_variables_initializer` instead.")
def initialize_all_variables():
  """See `tf.global_variables_initializer`."""
  return global_variables_initializer()
```

This change was made just 12 days ago

https://github.com/tensorflow/tensorflow/commit/4cbdead95f22de74bcbc72a68c9a38d465202db9#diff-ae1a8f7b66539f000615a4ab7e4b2151

**Comment by insikk** [comment]
@schmiflo Thankyou for your solution. However I got error by just blindly copy and paste the code. There is type in `tf.intialize_all_variables`. It should be `tf.initialize_all_variables`.  Could you fix it to prevent confusion?

**Comment by Binay2011** [comment]
I found that TensorFlow v0.12 accepts the global_variables_initializer command

**Comment by solomatov** [comment]
It would be nice if you update your tutorial here https://www.tensorflow.org/tutorials/mnist/beginners/ to use the new method.

**Comment by Binay2011** [comment]
I'm no expert by any means but I will try to do that over the next weekend. Hopefully I won't mess anything up :)
Binay 

    On Monday, January 9, 2017 7:05 PM, Konstantin Solomatov <notifications@github.com> wrote:
 

 It would be nice if you update your tutorial here https://www.tensorflow.org/tutorials/mnist/beginners/ to use the new method.—

**Comment by aertoria** [comment]
For folks that needs a complete answer: user the code below as is:
`sess.run(tf.initialize_all_variables())`

**Comment by shuuchen** [comment]
I upgraded tensorflow but global_variables_initializer() still cannot work.

**Comment by anabeatrizzz** [comment]
> @liusida I changed `global_variables_initializer` into `initialize_all_variables`, and it did work, I haven't updated my tf to the latest version, maybe it has already had `global_variables_initializer`

Hello, how can I update tf to the last version in Kaggle? `tf.initialize_all_variables` didn't work for me...

**Comment by EricBuist** [comment]
I'm having the same issue, nothing works.
>>> init = tf.global_variables_initializer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'
>>> init = tf.initialize_all_variables()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'initialize_all_variables'
I installed Tensorflow using pip and got 2.2.0.

**Comment by TanihiraDev** [comment]
@EricBuist if u are using tensorflow version 2.x u can try this:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by mohamedScikitLearn** [comment]
**I solved this by using tf.compat.v1.global_variables_initializer()**

**Comment by 1986Mohammad1986** [comment]
best answer:)))
