### ISSUE TITLE
Build of tests //tensorflow/core/transforms/... fails

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#55148]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.8.12
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 10.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Attempting to build //tensorflow/core/transforms/... fails with many undefined references

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --config=nonccl --verbose_failures --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --jobs=75 -- //tensorflow/core/transforms/...

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /tmp/workspace/tensorflow-git/tensorflow/core/transforms/BUILD:92:20: Linking tensorflow/core/transforms/tfg-transforms-opt failed: (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/db210f68f81d95ddcca9ae96b16ed72c/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64 \
    PATH=/tmp/workspace/venv-cp38-cp38/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/tmp/workspace/venv-cp38-cp38/bin/python3 \
    PYTHON_LIB_PATH=/tmp/workspace/venv-cp38-cp38/lib/python3.8/site-packages \
    TF2_BEHAVIOR=1 \
  /opt/rh/devtoolset-10/root/usr/bin/gcc @bazel-out/aarch64-opt/bin/tensorflow/core/transforms/tfg-transforms-opt-2.params)
# Configuration: adf76bbb856b8d7e1075d9fa81311a63f070542e9be48c5b759e905be0f8e507
# Execution platform: @local_execution_config_platform//:platform
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::~FactOp(): error: undefined reference to 'tensorflow::OpKernel::~OpKernel()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::~FactOp(): error: undefined reference to 'tensorflow::OpKernel::~OpKernel()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function register_kernel_1::{lambda(tensorflow::KernelDef const*)#1}::operator()(tensorflow::KernelDef const) const::{lambda(register_kernel_1::OpKernelConstruction*)#1}::_FUN(register_kernel_1::{lambda(tensorflow::KernelDef const*)#1}): error: undefined reference to 'tensorflow::OpKernel::OpKernel(tensorflow::OpKernelConstruction*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::OpKernelContext::allocate_output(int, tensorflow::TensorShape const&, tensorflow::Tensor**)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::Tensor::CheckIsAlignedAndSingleElement() const'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::TensorShapeRep::DestructorOutOfLine()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::CheckNotInComputeAsync(tensorflow::OpKernelContext*, char const*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function FactOp::Compute(tensorflow::OpKernelContext*): error: undefined reference to 'tensorflow::OpKernelContext::CtxFailureWithWarning(char const*, int, tensorflow::Status const&)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::OpDefBuilder::OpDefBuilder(std::string)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::OpDefBuilder::Output(std::string)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::shape_inference::UnknownShape(tensorflow::shape_inference::InferenceContext*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::shape_inference::UnknownShape(tensorflow::shape_inference::InferenceContext*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::OpDefBuilder::SetShapeFn(std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)>)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::register_op::OpDefBuilderWrapper::operator()()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::OpDef::~OpDef()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::KernelDefBuilder::KernelDefBuilder(char const*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::DEVICE_CPU'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::DEVICE_CPU'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::KernelDefBuilder::Device(char const*)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::KernelDefBuilder::Build()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'vtable for tensorflow::kernel_factory::OpKernelRegistrar::PtrOpKernelFactory'
/opt/rh/devtoolset-10/root/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'vtable for tensorflow::kernel_factory::OpKernelRegistrar::PtrOpKernelFactory'
/opt/rh/devtoolset-10/root/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::kernel_factory::OpKernelRegistrar::InitInternal(tensorflow::KernelDef const*, absl::lts_20211102::string_view, std::unique_ptr<tensorflow::kernel_factory::OpKernelFactory, std::default_delete<tensorflow::kernel_factory::OpKernelFactory> >)'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:function __static_initialization_and_destruction_0(int, int) [clone .constprop.0]: error: undefined reference to 'tensorflow::KernelDefBuilder::~KernelDefBuilder()'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:typeinfo for FactOp: error: undefined reference to 'typeinfo for tensorflow::OpKernel'
bazel-out/aarch64-opt/bin/tensorflow/core/user_ops/_objs/user_ops_op_lib/fact.o:fact.cc:vtable for FactOp: error: undefined reference to 'tensorflow::OpKernel::TraceString(tensorflow::OpKernelContext const&, bool) const'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op19::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::UnchangedShape(tensorflow::shape_inference::InferenceContext*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op10::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::ConcatShape(tensorflow::shape_inference::InferenceContext*, int)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function tensorflow::shape_inference::ScalarShape(tensorflow::shape_inference::InferenceContext*): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::Scalar()'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op57::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::Vector(tensorflow::shape_inference::DimensionOrConstant)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op57::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::WithRank(tensorflow::shape_inference::ShapeHandle, long, tensorflow::shape_inference::ShapeHandle*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op59::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::Vector(tensorflow::shape_inference::DimensionOrConstant)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function tensorflow::(anonymous namespace)::ScatterNdTensorShape(tensorflow::shape_inference::InferenceContext*): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::WithRankAtLeast(tensorflow::shape_inference::ShapeHandle, long, tensorflow::shape_inference::ShapeHandle*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function tensorflow::(anonymous namespace)::ScatterNdTensorShape(tensorflow::shape_inference::InferenceContext*): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::WithRankAtLeast(tensorflow::shape_inference::ShapeHandle, long, tensorflow::shape_inference::ShapeHandle*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function tensorflow::(anonymous namespace)::ScatterNdTensorShape(tensorflow::shape_inference::InferenceContext*): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::WithRankAtLeast(tensorflow::shape_inference::ShapeHandle, long, tensorflow::shape_inference::ShapeHandle*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function tensorflow::(anonymous namespace)::ScatterNdTensorShape(tensorflow::shape_inference::InferenceContext*): error: undefined reference to 'tensorflow::shape_inference::ScatterNdShapeHelper(tensorflow::shape_inference::InferenceContext*, tensorflow::shape_inference::ShapeHandle, tensorflow::shape_inference::ShapeHandle, tensorflow::shape_inference::ShapeHandle)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op118::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::UnchangedShape(tensorflow::shape_inference::InferenceContext*)'
bazel-out/aarch64-opt/bin/tensorflow/core/ops/_objs/array_ops_op_lib/array_ops.o:array_ops.cc:function std::_Function_handler<tensorflow::Status (tensorflow::shape_inference::InferenceContext*), tensorflow::register_op118::{lambda(tensorflow::shape_inference::InferenceContext*)#1}>::_M_invoke(std::_Any_data const&, tensorflow::shape_inference::InferenceContext*&&): error: undefined reference to 'tensorflow::shape_inference::InferenceContext::WithRank(tensorflow::shape_inference::ShapeHandle, long, tensorflow::shape_inference::ShapeHandle*)'

and much more....

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by cfRod** [comment]
Tagging @penpornk

**Comment by elfringham** [comment]
This can be avoided by using "--build_tests_only" on the command line.
