### ISSUE TITLE
tf.distribute.MultiWorkerMirroredStrategy() not getting initialized(RuntimeError: Collective ops must be configured at program startup)

### ISSUE THREAD

**Issue by ranvirdesai** [tensorflow/tensorflow#55178]
I am running a training job on vertex AI. 
Versions:
TF = 2.7
python = 3.8

The model runs fine for mirrored strategy where we have only one node with multiple gpu attached to it.

For MultiWorkerMirroredStrategy I am using
chief - n1 32 with 4V100 gpu - count 1(default)
worker n1 32 with 4V100 gpu - count 1

When I am trying to run the code using multiple nodes using MultiWorkerMirroredStrategy, It is giving following error

RuntimeError: Collective ops must be configured at program startup

I found some suggestions to put the strategy at the program beginning  but that also didn't help.
Vertex AI is setting the TF_CONFIG correctly.
But it is not able to instantiate the MultiWorkerMirroredStrategy

The stack trace

 mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()"
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 348, in new_func"

workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 253, in __init__"
" super(_CollectiveAllReduceStrategyExperimental,"
workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 186, in __init__"
workerpool0-0
" CollectiveAllReduceExtended("
workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 330, in __init__"
workerpool0-0
" self._initialize_strategy(self._cluster_resolver)"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 342, in _initialize_strategy"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" self._initialize_multi_worker(cluster_resolver)"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 463, in _initialize_multi_worker"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" context.context().configure_collective_ops("
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" File "/opt/conda/envs/py38/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 817, in configure_collective_ops"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
" raise RuntimeError("Collective ops must be configured at program startup")"
Error
2022-03-09 09:57:09.622 IST
workerpool0-0
"RuntimeError: Collective ops must be configured at program startup"

**Comment by andre-bauer** [comment]
Can you put a breakpoint before this line `mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()` and check if any gpu memory is allocated already by TF? if so you accidentally created a tf.Var or Tensor which you are not allowed to before creating MultiWorkerMirroredStrategy

**Comment by ranvirdesai** [comment]
Instantiating the strategy is first line of code, I don't think there are any tensors created before.

**Comment by chunduriv** [comment]
@ranvirdesai, 

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ranvirdesai** [comment]
@andre-bauer Thanks for the reply, any other issue you could think of....

**Comment by ranvirdesai** [comment]
@chunduriv 
Its just this code raises error while initializing strategy.

if __name__=="__main__":
    mirrored_strategy = tf.distribute.MultiWorkerMirroredStrategy()

**Comment by andre-bauer** [comment]
This is not the first line of code... Did you check the GPU memory at this line? 

you could have 
```
def do_something(var_name=tf.constant(0)):
   pass
```
somewhere above main and it would already fail

**Comment by chunduriv** [comment]
@ranvirdesai,

Could you please refer to the [comment](https://github.com/tensorflow/tensorflow/issues/55178#issuecomment-1063131241) and let us know ?Thanks!

**Comment by ranvirdesai** [comment]
@chunduriv @andre-bauer 
Thanks for the response.

I tried running vertex ai custom job using suggested method.
I initialized strategy right after importing tf, it did not give error but training was also not done.
training was for only one epoch and takes 2min in my local, but I think it went in never ending loop on vertex ai.

**Comment by sachinprasadhs** [comment]
Make sure you have the proper configuration, follow [this](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration) document for reference. Thanks!

**Comment by ranvirdesai** [comment]
@chunduriv @andre-bauer 
The comment helped.
I rearranged imports and it worked

**Comment by sachinprasadhs** [comment]
@ranvirdesai , If your issue is resolved, could you please close this issue. Thanks!

**Comment by surajitkundu-dazn** [comment]
I have a similar problem , I am trying to distribute the load accross multiple nodes , if I initiate the Strategy first then it's not using the TF_CONFIG so as a result it's using only one GPU, but if I initiate the config first then getting error "Collective ops must be configured at program startup"
