### ISSUE TITLE
Don't support avgpooling op on Windows ?

### ISSUE THREAD

**Issue by apollo-time** [tensorflow/tensorflow#5517]
## Environment info
Operating System: Windows 10, 64bit, Visual Studio 2015

## Issue
I try compile tensorflow label image sample on windows 10 64bit with Visual Studio 2015.
I got error 'AvgPool' op kernel not found message while loading tensorflow_inception_graph.pb graph.
I check tf_core_kernels.cmake and found follow line.

```
if(WIN32)
  file(GLOB_RECURSE tf_core_kernels_windows_exclude_srcs
      # not working on windows yet
      "${tensorflow_source_dir}/tensorflow/core/kernels/depthwise_conv_op.cc"  # Cannot find symbol: tensorflow::LaunchConv2DOp<struct Eigen::ThreadPoolDevice, double>::launch(...).
      "${tensorflow_source_dir}/tensorflow/core/kernels/fact_op.cc"
      "${tensorflow_source_dir}/tensorflow/core/kernels/meta_support.*"
      "${tensorflow_source_dir}/tensorflow/core/kernels/*quantiz*.h"
      "${tensorflow_source_dir}/tensorflow/core/kernels/*quantiz*.cc"
      "${tensorflow_source_dir}/tensorflow/core/kernels/svd*.cc"
      "${tensorflow_source_dir}/tensorflow/core/kernels/avgpooling_op.*"
  )
  list(REMOVE_ITEM tf_core_kernels_srcs ${tf_core_kernels_windows_exclude_srcs})
endif(WIN32)
```

Is this mean don't support above ops on windows?
How can I running graph that using these ops?

**Comment by mrry** [comment]
At least in the initial version, `avgpooling_op.cc` did not compile with MSVC. I'm not at a computer right now, but could you try commenting out the line 

```
      "${tensorflow_source_dir}/tensorflow/core/kernels/avgpooling_op.*"
```

from the `tf_core_kernels_windows_exclude_srcs` definition you pasted above, and report the error (if any)?

**Comment by apollo-time** [comment]
I had try the add avgpooling_op.cc into tf_core_kernels project manually and build it.
But I got the last error
`
1>------ Build started: Project: tf_core_kernels, Configuration: Debug x64 ------

...

1>tf_core_kernels.dir\Debug\tf_core_kernels.lib : fatal error LNK1248: image size (1017EA054) exceeds maximum allowable size (FFFFFFFF)
`
How can I build it?

**Comment by mrry** [comment]
The best bet is to build it in the`Release` or `RelWithDebInfo` configurations, which are the only two we support. (`Debug` has some compatibility issues with the behavior of STL iterators in MSVC... and apparently some image-size problems too!)

I've just sent out PR #5532, which adds the CPU version of `avgpooling_op.cc` to the Windows build, and the tests are passing.
