### ISSUE TITLE
[TfLite] C++ tflite::InterpreterBuilder is missing in version r1.12

### ISSUE THREAD

**Issue by BILLXZY1215** [tensorflow/tensorflow#55179]
Hi, I'm using the tflite library from version [r1.12](https://github.com/tensorflow/tensorflow/tree/r1.12/tensorflow/contrib/lite). However, I followed the guide in [official doc](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter):

```
// Create model from file. Note that the model instance must outlive the
// interpreter instance.
auto model = [tflite::FlatBufferModel::BuildFromFile](https://tensorflow.google.cn/lite/api_docs/cc/class/tflite/flat-buffer-model#classtflite_1_1_flat_buffer_model_1aa38cad2bc62ae19a647c64f10226862b)(...);
if (model == nullptr) {
  // Return error.
}
// Create an [Interpreter](https://tensorflow.google.cn/lite/api_docs/cc/class/tflite/interpreter#classtflite_1_1_interpreter) with an [InterpreterBuilder](https://tensorflow.google.cn/lite/api_docs/cc/class/tflite/interpreter-builder#classtflite_1_1_interpreter_builder).
std::unique_ptr interpreter;
tflite::ops::builtin::BuiltinOpResolver resolver;
if (InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk) {
  // Return failure.
}
if (interpreter->AllocateTensors() != kTfLiteOk) {
  // Return failure.
}
```

It seems that the `interpreterBuilder.h` file is missing in the r1.12 version. In this case, what should I do to create an interpreter with a specified model in r1.12? Thanks.

**Comment by sushreebarsa** [comment]
@BILLXZY1215 We could see you are using tflite under contrib directory which is not actively supported, and `contrib` is `depreciated`. We recommend you to kindly  use the latest version.Thanks!

**Comment by BILLXZY1215** [comment]
Okay, I see, thanks!

**Comment by sushreebarsa** [comment]
@BILLXZY1215 Could you please move this issue to closed  status if it is resolved for you?
Thanks!

**Comment by sushreebarsa** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
