### ISSUE TITLE
Silent reset_states() error in custom model

### ISSUE THREAD

**Issue by mattiasu96** [tensorflow/tensorflow#55174]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Monterey 12.1
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.8
- Python version: 3.9

**Describe the current behavior**
I am developing a custom model by inheriting from the `tf.keras.Model` class, in particular I am developing a custom LSTM residual network. Following the documentation and code, if calling `model.reset_states()` on a stateless layer should trigger an exception present in the layer class (in my case LSTM). 

However, such call is obscured by a conditional statement that prevents the raising of such exception in any case (at least the one I was trying). So basically model.reset_states() runs silently without errors and without resetting the states. 

This is the function present inside tf.keras.Model class. The conditional statement prevents the condition from layer.reset_states() to be raised. By manually forcing the evaluation  of `layer.reset_states()` inside a debugger, the exception is correctly raised.

```
  def reset_states(self):
    for layer in self.layers:
      if hasattr(layer, 'reset_states') and getattr(layer, 'stateful', False):
        layer.reset_states()

```

**Describe the expected behavior**
Raise the exception and make explicit whether reset_states() is called on layers that are not stateful

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**

```
class ResNetModel(Model):
    def __init__(self, num_inputs, **kwargs):
        """
        The class initialiser should call the base class initialiser, passing any keyword
        arguments along. It should also create the layers of the network according to the
        above specification.
        """
        super(ResNetModel, self).__init__(**kwargs)
        self.lstm_1 = tf.keras.layers.LSTM(units=32, input_shape=(None, num_inputs), return_sequences=True, stateful = False)
        self.dense = tf.keras.layers.Dense(units=1, activation=None)

    def call(self, inputs, training=False):
        """
        This method should contain the code for calling the layer according to the above
        specification, using the layer objects set up in the initialiser.
        """
        x = self.lstm_1(inputs)
        y = self.dense(x)
        return y + inputs

model = ResNetModel(1)
model.reset_states() # does not raise any errors
```

**Comment by chunduriv** [comment]
@mattiasu96, Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999. Thanks!

**Comment by mattiasu96** [comment]
Oh sorry, should I copy the issue to Keras then?

**Comment by chunduriv** [comment]
@mattiasu96,

Yes, please post your issue here https://github.com/keras-team/keras/issues. Thanks!

**Comment by mattiasu96** [comment]
Dona!
