### ISSUE TITLE
tensorflow core while do stdthread create

### ISSUE THREAD

**Issue by goddie1** [tensorflow/tensorflow#55186]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (yes):
- OS Platform and Distribution (e.g., Linux Red Hat 4.8.5-16) (GCC) ):
- Mobile device (no) if the issue happens on mobile device:
- TensorFlow installed from (source):
- TensorFlow version (use command below):1.15.0
- Python version:no
- Bazel version (3.1.0):
- GCC/Compiler version (5.4.0):
- CUDA/cuDNN version:no
- GPU model and memory:no

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
while I load savedmodel,tensorflow core dump,the detail gdb info at below.

**Describe the expected behavior**
load saved model success
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs**
core dump stack info:
#0  0x0000000000000000 in ?? ()
#1  0x00007f201fbfbaf3 in __gthread_create (__args=<optimized out>, __func=0x7f201fbfb990 <std::execute_native_thread_routine(void*)>, __threadid=0x2ab77d8)
    at /usr/gcc-5.4.0/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:662
#2  std::thread::_M_start_thread (this=0x2ab77d8, __b=...) at ../../../../../libstdc++-v3/src/c++11/thread.cc:149
#3  0x00007f2016dc92c1 in std::thread::thread<std::function<void ()>&>(std::function<void ()>&) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#4  0x00007f2016dc8027 in tensorflow::(anonymous namespace)::StdThread::StdThread(tensorflow::ThreadOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#5  0x00007f2016dc83d6 in tensorflow::(anonymous namespace)::PosixEnv::StartThread(tensorflow::ThreadOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#6  0x00007f2016db46b5 in tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#7  0x00007f2016db517b in Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::ThreadPoolTempl(int, bool, tensorflow::thread::EigenEnvironment) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#8  0x00007f2016db1c9c in tensorflow::thread::ThreadPool::ThreadPool(tensorflow::Env*, tensorflow::ThreadOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, Eigen::Allocator*) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#9  0x00007f2016850084 in tensorflow::LocalDevice::EigenThreadPoolInfo::EigenThreadPoolInfo(tensorflow::SessionOptions const&, int, tensorflow::Allocator*)
    () from /.../bazel-bin/src/lib/lib_common/xxx.so
#10 0x00007f201684f9f9 in tensorflow::LocalDevice::LocalDevice(tensorflow::SessionOptions const&, tensorflow::DeviceAttributes const&) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#11 0x00007f20168ca7d1 in tensorflow::ThreadPoolDevice::ThreadPoolDevice(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::gtl::IntType<tensorflow::Bytes_tag_, long long>, tensorflow::DeviceLocality const&, tensorflow::Allocator*)
    () from /.../bazel-bin/src/lib/lib_common/xxx.so
#12 0x00007f20168cbcb6 in absl::memory_internal::MakeUniqueResult<tensorflow::ThreadPoolDevice>::scalar absl::make_unique<tensorflow::ThreadPoolDevice, tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, tensorflow::gtl::IntType<tensorflow::Bytes_tag_---Type <return> to continue, or q <return> to quit---
, long long>, tensorflow::DeviceLocality, tensorflow::Allocator*>(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, tensorflow::gtl::IntType<tensorflow::Bytes_tag_, long long>&&, tensorflow::DeviceLocality&&, tensorflow::Allocator*&&) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#13 0x00007f20168cb92a in tensorflow::ThreadPoolDeviceFactory::CreateDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::unique_ptr<tensorflow::Device, std::default_delete<tensorflow::Device> >, std::allocator<std::unique_ptr<tensorflow::Device, std::default_delete<tensorflow::Device> > > >*) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#14 0x00007f20167f3272 in tensorflow::DeviceFactory::AddDevices(tensorflow::SessionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::unique_ptr<tensorflow::Device, std::default_delete<tensorflow::Device> >, std::allocator<std::unique_ptr<tensorflow::Device, std::default_delete<tensorflow::Device> > > >*) () from /.../bazel-bin/src/lib/lib_common/xxx.so
#15 0x00007f2015eb4a5d in tensorflow::DirectSessionFactory::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#16 0x00007f20168aa054 in tensorflow::NewSession(tensorflow::SessionOptions const&, tensorflow::Session**) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#17 0x00007f200f324559 in tensorflow::(anonymous namespace)::LoadMetaGraphIntoSession(tensorflow::MetaGraphDef const&, tensorflow::SessionOptions const&, std::unique_ptr<tensorflow::Session, std::default_delete<tensorflow::Session> >*) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#18 0x00007f200f32617a in tensorflow::(anonymous namespace)::LoadSavedModelInternal(tensorflow::SessionOptions const&, tensorflow::RunOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, tensorflow::SavedModelBundle*) () from /.../bazel-bin/src/lib/lib_common/xxx.so
#19 0x00007f200f3268e1 in tensorflow::LoadSavedModel(tensorflow::SessionOptions const&, tensorflow::RunOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, tensorflow::SavedModelBundle*) () from /.../bazel-bin/src/lib/lib_common/xxx.so
#20 0x00007f200f10a683 in fg_framework::TFGraphModel::LoadFromSavedModelBundle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >---Type <return> to continue, or q <return> to quit---
 const&, fg_framework::LocalModelBundle*) () from /.../bazel-bin/src/lib/lib_common/xxx.so
#21 0x00007f200f10ac77 in fg_framework::TFGraphModel::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /.../bazel-bin/src/lib/lib_common/xxx.so
#22 0x00007f200f1077ad in fg_framework::FeatureGenerator::InitFgConfig(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /.../bazel-bin/src/lib/lib_common/xxx.so

**Comment by sushreebarsa** [comment]
@goddie1 
We see that you are using old version of tensorflow 1,x(1.15)  which is not actively supported, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions.Thanks!

**Comment by goddie1** [comment]
ok,I will try  new version.

**Comment by sushreebarsa** [comment]
@goddie1 Could you please move this issue to closed status if it is resolved for you ?Thanks!
