### ISSUE TITLE
Will 64-bit support ever be added to the TPU driver API?

### ISSUE THREAD

**Issue by WillFarris** [tensorflow/tensorflow#55187]
Hi, this is my first GitHub issue so please let me know if this is an innapropriate place to ask this question.

When I try to create an array of type `float64` in JAX I get the following message:

`RuntimeError: INVALID_ARGUMENT: 64-bit data types are not yet supported on the TPU driver API. Convert inputs to float32/int32_t before using.`

which from what I can tell is from the file `tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc` in the Tensorflow repo, which I assume is part of the TPU driver API code. The verbiage here suggests this support may one day be added to the TPU driver API, so I'd like to know if this is something that's planned to be added in the future. If it is planned, is there an ETA on when this feature may be available?

For a university project I'm trying to implement a Mersenne prime number search program which runs on the TPU. These calculations are very sensitive to precision errors, and we've found that although we may be able to use the TPU to improve performance over existing GPU-based programs, the precision of `bfloat16` or even `float32` are too low for the calculations we're trying to run.

**Comment by mohantym** [comment]
Hi @WillFarris ! Can you please share a simple stand alone code to replicate this issue?

**Comment by WillFarris** [comment]
@mohantym sure thing, running the code below in a Google Colab notebook with the TPU runtime selected should produce the error:
```
import jax
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
jax.config.update("jax_enable_x64", True)
x = jax.numpy.array([1, 2, 3, 4], dtype=jax.numpy.float64) # Should throw an error on Colab
```


The error message:
```
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-1-a3700b59f8b9>](https://localhost:8080/#) in <module>()
      3 jax.tools.colab_tpu.setup_tpu()
      4 jax.config.update("jax_enable_x64", True)
----> 5 x = jax.numpy.array([1, 2, 3, 4], dtype=jax.numpy.float64) # Should throw an error on Colab

10 frames

[/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in _device_put_array(x, device)
    671   if x.dtype is dtypes.float0:
    672     x = np.zeros(x.shape, dtype=np.dtype(bool))
--> 673   return (backend.buffer_from_pyval(x, device),)
    674 
    675 def _device_put_scalar(x, device):

RuntimeError: INVALID_ARGUMENT: 64-bit data types are not yet supported on the TPU driver API. Convert inputs to float32/int32_t before using.
```

**Comment by mohantym** [comment]
@WillFarris ! I think this issue will suit more in [Jax repo ](https://github.com/google/jax/issues).

**Comment by WillFarris** [comment]
Sure thing, thanks! Should I go ahead and close this issue then?

**Comment by mohantym** [comment]
Ok @WillFarris . Moving this to closed status. Thanks!

**Comment by WillFarris** [comment]
It appears the answer is no, this feature is not planned. See the issue below for details.

https://github.com/google/jax/issues/9862
