### ISSUE TITLE
Op type not registered 'SqrtGrad'

### ISSUE THREAD

**Issue by leslietso** [tensorflow/tensorflow#5518]
I am unable to create the Tensorflow graph from an imported model on Android using JNI. When attempting to load the file with `tensorflow::Status s = session->Create(graph_def);`, I receive the error, `Not found: Op type not registered 'SqrtGrad'`.

I checked `jni-build/jni/include/tensorflow/python/ops/math_ops.py` and `SqrtGrad` does exist. As running the model on Python does not return this error, could this be a problem when I generated my protobuf file with `tf.train.write_graph(sess.graph_def, 'location', 'trained_model.pb', as_text=False)`?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/3619
https://github.com/tensorflow/tensorflow/issues/3533

### Environment info
Operating System:
Mac OS 10.12
Android Cyanogenmod 12
Tensorflow 0.10.0 on Jupyter

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
This section of code is from [TensorFlowAndroidMNIST](https://github.com/miyosuda/TensorFlowAndroidMNIST/tree/master/jni-build/jni)

[trained_model.pb.zip](https://github.com/tensorflow/tensorflow/files/583485/trained_model.pb.zip)
```
static std::unique_ptr<tensorflow::Session> session;

static bool g_compute_graph_initialized = false;
using namespace tensorflow;

JNIEXPORT jfloat JNICALL
TENSORFLOW_METHOD(init)(JNIEnv* env, jobject thiz, jobject java_asset_manager, jstring model) {

	const char* const model_cstr = env->GetStringUTFChars(model, NULL);

	tensorflow::SessionOptions options;
	tensorflow::ConfigProto& config = options.config;

	session.reset(tensorflow::NewSession(options));

	tensorflow::GraphDef graph_def;
	AAssetManager* const asset_manager = AAssetManager_fromJava(env, java_asset_manager);

	ReadFileToProto(asset_manager, model_cstr, &graph_def);
	tensorflow::Status s = session->Create(graph_def);

	if (!s.ok()) {
		LOG(ERROR) << "Could not create Tensorflow Graph: " << s;
		return -1;
	}
}
```

### What other attempted solutions have you tried?
I have tried adding `tensorflow/contrib/*`to `tf_op_files.txt` and `"//tensorflow/contrib/all_files"` to the tensorflow/BUILD file.

**Comment by sherrym** [comment]
Hi @leslietso ,

By default we only have inference ops on Android, however there's a way that you can add training ops. @petewarden will address this for you.

Sherry

**Comment by petewarden** [comment]
Hi @leslietso,

If you're using Bazel, you should add cwise_op_sqrt.cc to the srcs list of :android_extended_ops_group_2:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L2490

If you're using the makefile, add this line to tensorflow/contrib/makefile/tf_op_files.txt:
tensorflow/core/kernels/cwise_op_sqrt.cc

The reason that this isn't present by default is that most applications don't do training on mobile devices, and removing the implementations of those ops shrinks the binary size. If you're not running training, you might want to run some tools like optimize_for_inference to strip out training ops. I've attached some draft documentation on that process.
[deploying.txt](https://github.com/tensorflow/tensorflow/files/584688/deploying.txt)

**Comment by leslietso** [comment]
Thank you for the reply. You are right in saying I do not need to train in Android so I want to strip the training ops with `optimize_for_inference`. 

To do so, I want to use the freeze graph method mentioned in the "deploying.txt" file you posted. From my understanding I need to run /.configure first. However, when doing so, I keep getting the error `Can't open tensorflow/core/platform/default/build_config.bzl: No such file or directory.` which is strange since the file does exist in that location. I have tried redownloading tensorflow but no go.

**Comment by leslietso** [comment]
You are correct in saying that I do not want to train on my Android device. 

In order to run `optimize_for_inference`, I wanted to first run `freeze_graph` mentioned in the "deploying.txt" file you posted. However, I get the error `UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 331: invalid start byte` when attempting to run the bash script:

```
#!/bin/bash
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=/Users/leslie/Downloads/trained_model.pb \
--input_checkpoint=/Users/leslie/Downloads/Y6_1478303913_Leslie \
--output_graph=/tmp/frozen_graph.pb --output_node_names=Y_GroundTruth
```

Could this be a problem in the way I created my graph and checkpoint? I created the input_graph via ` tf.train.write_graph(sess.graph_def, location, 'trained_model.pb', as_text=False)` and the checkpoint is created via `saver.save(sess, chkpointpath)`. Answers from StackOverflow say that the python script has non-ascii characters and that I should just simply strip them from the python script but I do not think that is such a great idea.

**Comment by leslietso** [comment]
Just wanted to say that it was a problem with how the protobuf file was generated (the variables in the protobuf file were not correctly initiated).

However, I am not getting the error `Invalid argument: NodeDef mentions attr 'Tshape' not in Op<name=Reshape; signature=tensor:T, shape:int32 -> output:T; attr=T:type>; NodeDef: Y_GroundTruth = Reshape[T=DT_FLOAT, Tshape=DT_INT32](LOut_Add, Y_GroundTruth/shape)` when attempting to load the file on Android. 

People with similar problems have mentioned that upgrading to Tensorflow 0.9.0rc0 fixed their problems. However, I am already using the most current Tensorflow build in my `jni-build`.

**Comment by aselle** [comment]
Closing due to lack of recent activity. Since this issue is quite old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thanks.
