### ISSUE TITLE
Fail to convert trained model to TensorFlow Lite (integer only and unsigned integer)

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#55198]
### 1. System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installation: pip package
- TensorFlow library: 2.4.0
- tensorflow-model-optimization: 0.7.1.

### 2. Code
(int8 conversion)
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT] # require representative dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8 
converter.inference_output_type = tf.int8 

converter.representative_dataset = representative_data_gen
tflite_int8_model = converter.convert()
```

(uint8 conversion)
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.uint8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_uint8_model = converter.convert()
```

I'm trying to apply post-training quantization to the trained model, the model is built and trained through TensorFlow2 functional API. However, for conversion of integer only, the converter generates the error message: `Model output is not dquntized.` when executing converter.convert(); for conversion of unsigned integer, the converter generates the error message: `the inference_input_type and inference_output_type must be tf.float32.` if I assigned `converter.target_spec.supported_ops = [tf.uint8]`, `converter.inference_input_type = tf.uint8`, and `converter.inference_output_type = tf.uint8`.
![keras_to_int8_error](https://user-images.githubusercontent.com/8951991/157827139-3259fa6a-8a63-4b89-acb6-55efa0b98e92.png)

![keras_to_uint8_error](https://user-images.githubusercontent.com/8951991/157827152-aa8e4b0c-7425-455d-96af-dbdc9f3d378e.png)

Are there settings required to convert the trained model to int8 and uint8 precision?

Best Regards,
Rahn

**Comment by tilakrayal** [comment]
@Rahn80643 ,
In order to expedite the trouble-shooting process, could you please provide a complete code and also please try to test your the code in latest tensorflow version 2.8 and let us know if you are facing same issue.Thanks!
