### ISSUE TITLE
XLA support for ImageProjectiveTransformV3

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#55194]
**System information**
- TensorFlow version (you are using):
master
- Are you willing to contribute it (Yes/No):
I don't know, only if I have a clear contribution path

**Describe the feature and the current behavior/state.**
XLA support for `ImageProjectiveTransformV3` 
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Performance on image preprocessing
**Any Other info.**

```python
import tensorflow as tf
import numpy as np
@tf.function(jit_compile=True)
def transform():
    inp = np.arange(15).reshape((1, 5, 3, 1)).astype(np.float32)
    transform_matrix = np.asarray([[1., 0., 0., 0., 1., -1., 0., 0.]])
    output_shape = tf.shape(inp)[1:3]
    tf.raw_ops.ImageProjectiveTransformV3(
        images=inp,
        output_shape=output_shape,
        fill_value=0.0,
        transforms=transform_matrix,
        fill_mode="constant",
        interpolation="bilinear")

transform()
```

```
 on XLA_CPU_JIT: ImageProjectiveTransformV3 (No registered 'ImageProjectiveTransformV3' OpKernel for XLA_CPU_JIT devices compatible with node {{node ImageProjectiveTransformV3}}){{node ImageProjectiveTransformV3}}
```

Extra:
Please also note that the CPU/GPU TF2XLA supported ops tables are probably outdated (2018):
https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/51715e77586dd8ed5b886e12ad983713/55194.ipynb).

**Comment by wangpengmit** [comment]
Assigning to @smit-hinsu for triage.

**Comment by smit-hinsu** [comment]
We don't have a plan to support ImageProjectiveTransform at the moment so for now the best option will be to put this op outside of the XLA cluster.

**Comment by bhack** [comment]
Ok but It Is quite recurrent in image augmentation  layers

**Comment by bhack** [comment]
Also, I don't know if you could expose some steps for a contributor to add support to this op trought a PR.

**Comment by bhack** [comment]
See also https://github.com/keras-team/keras/issues/16219#issuecomment-1071827074
