### ISSUE TITLE
supported Image formats (.PNG) for custom object detection training

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#55197]
Hey guys,

After reading through the topics a bit, it was mentioned that certain image formats are not supported, but that wrappers have been written by individual users.

These were then added to the code in the tensorflow/core/..... etc. folder structure.

How does TensorFlow behave with an individual training with .PNG images? Would I also have to use one of these wrappers and if so, it is not exactly clear to me where this has to be inserted.

Thank you very much, I am grateful for any tips.

**Comment by Petros626** [comment]
Hey @mohantym 

thank you for your quick response!

I don't have any code for it myself, but I have read in various topics that different picture format decoders have been gradually added.

I have to relate the question to my application. I want to know if API's Object Detection supports a format other than .jpg, because in the Python scripts to create the TFRecord files .jpg is used.

**Comment by sachinprasadhs** [comment]
Apologies for the delayed response.
You can use .PNG format in your custom object detection training.
For preprocessing pipeline you can read the .PNG file using [tf.io.read_file](https://www.tensorflow.org/api_docs/python/tf/io/read_file).
Also, refer [this](https://www.tensorflow.org/guide/data#parsing_tfexample_protocol_buffer_messages) example where PNG file is used in `tf.data` pipeline. Thanks!

**Comment by Petros626** [comment]
Hello,

i think you can use this if you use TensorFlow via an IDE, but the Object Detection API has ready made scripts to provide training on the computer (hard coded)

**Comment by sachinprasadhs** [comment]
You can refer [this](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md) document from the models repo for object detection where it mentions about the use of Jpeg or PNG as your inout data.

**Comment by Petros626** [comment]
Yes I've read this one, but I'm using this script to generate my TFRecord files. 
It uses jpg Images. (https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10/blob/master/generate_tfrecord.py). So I think I must change line 62, 66, 67 and 80 ?

**Comment by sachinprasadhs** [comment]
Yes, basically you need to change the pipeline to adapt PNG input files instead of JPG files.

**Comment by Petros626** [comment]
> Yes, basically you need to change the pipeline to adapt PNG input files instead of JPG files.

that's the way.

**Comment by sachinprasadhs** [comment]
You can close the issue if your issue is addressed. Thanks!

**Comment by Petros626** [comment]
> Can anyone please let me know the changes that should be made in generate_tfrecord.py file if input image is in PNG fomat?

Hey read above and you will find the solution. I didn't change the script because now I'm creating first my Dataset. In the future I'll post on my site the new script for `png` images.

**Comment by vm533** [comment]
Hey @Petros626.. thank you for your reply. I tried with few changes as mentioned like changing in line 62, 66, 67 and 80 but still i couldnt figure it out.

**Comment by Petros626** [comment]
The specified lines could be a guess I thought different in the past, maybe today I would only take a look a the function `tf.io`. But just ask chatgpt, if you can't figure out on yourself.
