### ISSUE TITLE
Got this warning while using @tf.function on tensorflow_probability.

### ISSUE THREAD

**Issue by HimGautam** [tensorflow/tensorflow#55190]
I am trying to train a reinforcment learning agent on BipedalWalker. To Speed things up I used @tf.function wrapper on my gradient calculations and then I got this warning.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04LTS
- Device: Lenovo Legion Y540
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): v2.4
- TensorFlow-Probability: v0.12.2
- Python version: v3.9
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: Nvidia Geforce Gtx 1650 4GB

**Describe the current behavior**

```
WARNING:tensorflow:AutoGraph could not transform <bound method A3CAgent.act of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f20540f1940>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <bound method A3CAgent.act of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f20540f1940>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:From /home/himanshu/anaconda3/envs/myenv/lib/python3.9/site-packages/tensorflow_probability/python/distributions/distribution.py:298: calling MultivariateNormalDiag.__init__ (from tensorflow_probability.python.distributions.mvn_diag) with scale_identity_multiplier is deprecated and will be removed after 2020-01-01.
Instructions for updating:
`scale_identity_multiplier` is deprecated; please combine it with `scale_diag` directly instead.
WARNING:tensorflow:From /home/himanshu/anaconda3/envs/myenv/lib/python3.9/site-packages/tensorflow/python/ops/linalg/linear_operator_diag.py:167: calling LinearOperator.__init__ (from tensorflow.python.ops.linalg.linear_operator) with graph_parents is deprecated and will be removed in a future version.
Instructions for updating:
Do not pass `graph_parents`.  They will  no longer be used.
```

**Describe the expected behavior**
   Tensorflow should not give these warnings.

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): None

**Standalone code to reproduce the issue**
  Link to the jupyter notebook can be found [here](https://drive.google.com/file/d/1OzDI00TQ1U1g63UR7HxuKhEzAQ3nMwug/view?usp=sharing).

**Comment by HimGautam** [comment]
No, v2.8 is not supported by CUDA 10.1. So that's why I have not checked it.

**Comment by mohantym** [comment]
Can you switch to Cuda 11.2 and CudNN 8.1 for TF 2.8 and let us know whether the issue still persists.

**Comment by HimGautam** [comment]
I tried but my machine when I install these versions of cuda and cudnn, tensorflow is not able to access gpu on my system.

**Comment by gadagashwini** [comment]
@HimGautam,
There are the Deprecation Warnings, which we can suppress using one of the below code snippets 

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
```
OR

```
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf
```

**Comment by HimGautam** [comment]
Ok got it, I think when I will update to higher versions of tensorflow then these warning will go away automatically. Thanks for the assist.
