### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by GodsNightmare** [tensorflow/tensorflow#55208]
https://github.com/isaacs/node-heatmap/blob/master/example/web/index.html

**Comment by tilakrayal** [comment]
@GodsNightmare ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by mihaimaruseac** [comment]
spam
