### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'

### ISSUE THREAD

**Issue by shubhambagwari** [tensorflow/tensorflow#55202]
I trained the model and saved it, now I am trying to load but unable to do. I have seen in previous post as well, but reference links are not working.

**Code**

```
`#load model

with tf.io.gfile.GFile(args.model, "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())

# with tf.Graph().as_default() as graph:
generated_image_1, generated_image_2, generated_image_3, = tf.graph_util.import_graph_def(
        graph_def, 
        input_map={'input_image' : input_tensor, 'short_edge_1' : short_edge_1, 'short_edge_2' : short_edge_2, 'short_edge_3' : short_edge_3}, 
        return_elements=['style_subnet/conv-block/resize_conv_1/output:0', 'enhance_subnet/resize_conv_1/output:0', 'refine_subnet/resize_conv_1/output:0'],  
        producer_op_list=None
    )`
```

**Error:**

```
`Traceback (most recent call last):
  File "stylize.py", line 97, in <module>
    main()
  File "stylize.py", line 57, in main
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message with type 'tensorflow.GraphDef'`
```

Note: I am using,
python = 3.7.6
Tensorflow-gpu=1.15
tensorboard=1.15.0
protobuf =3.19.4

**Comment by tilakrayal** [comment]
@shubhambagwari ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to 2.x and let us know if you are facing same issue.

**Comment by shubhambagwari** [comment]
@tilakrayal I updated tensorflow version to 2.7, still not resolved.
  File "stylize.py", line 107, in <module>
    main()
  File "stylize.py", line 52, in main
    graph = load_graph(args.model)
  File "stylize.py", line 15, in load_graph
    graph_def.ParseFromString(f.read())
  File "C:\Users\shubham\env\lib\site-packages\google\protobuf\message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\shubham\env\lib\site-packages\google\protobuf\internal\python_message.py", line 1145, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\shubham\env\lib\site-packages\google\protobuf\internal\python_message.py", line 1198, in InternalParse
    (data, new_pos) = decoder._DecodeUnknownField(
  File "C:\Users\shubham\env\lib\site-packages\google\protobuf\internal\decoder.py", line 993, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

**Comment by tilakrayal** [comment]
@shubhambagwari ,
In order to expedite the trouble-shooting process, could you please provide a complete code snippet  you are using.

**Comment by tilakrayal** [comment]
Can you please take a look at this [SO link](https://stackoverflow.com/questions/65142116/using-tensorflow-google-protobuf-message-decodeerror-wrong-wire-type-in-tag) with the similar error.It helps.Thanks!

**Comment by shubhambagwari** [comment]
Can you mail me subbu.bagwari@gmail.com, I can share gcolab sheet

**Comment by tilakrayal** [comment]
@shubhambagwari ,
Can you please provide the code and the dependencies here or in colab gist.Thanks!
