### ISSUE TITLE
Build fails to make use of bazelisk, if available.

### ISSUE THREAD

**Issue by Gelesh** [tensorflow/tensorflow#55218]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WINDOWS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  https://github.com/tensorflow/tensorflow.git
- TensorFlow version: r2.
- Python version: 3.10
- Installed using virtualenv? pip? conda?: GIT
- Bazel version (if compiling from source): 5.0
- GCC/Compiler version (if compiling from source): 11.2
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the problem**

When using the [build from source](https://www.tensorflow.org/install/source_windows) https://www.tensorflow.org/install/source_windows , Even when 'bazelisk' is installed, the install run fails from config.py stating 
'Cannot find bazel. Please install bazel.',

This could easly be fixed, like

```
  if bazel_executable is None:
    bazel_executable = which('bazelisk')
    print('bazel_executable not found, instead using bazelisk @ ',bazel_executable)
    if bazel_executable is None:
        print('Cannot find bazel. Please install bazel.')
        sys.exit(1)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Remove from path variable /Un Install bazel.
Install bazelisk.

execute ./config  or python config.py

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
**Error**: 'Cannot find bazel. Please install bazel.'

**Comment by tilakrayal** [comment]
@Gelesh ,
Can you please confirm whether you followed this step mentioned [here](https://www.tensorflow.org/install/source_windows#build_the_pip_package) which try to install the bazel?

**Comment by Gelesh** [comment]
@gadagashwini , Please feel free to reach out, if in case the problem statement requires any clarification. One way to replicate the issue is, to un-install Bazel, and install Bazelisk .
Bazelisk details are [here](https://github.com/bazelbuild/bazelisk#about-bazelisk). This would be critical because [Bazel has moved](https://docs.bazel.build/versions/main/install-bazelisk.html)

**Comment by mihaimaruseac** [comment]
We are using bazelisk in our CI, symlinked to bazel as per instructions.

**Comment by Gelesh** [comment]
Bazelisk symlinked to bazel  , is a work around. @mihaimaruseac , could we have it somehow fixed,

**Comment by mihaimaruseac** [comment]
#55272 should fix this?

**Comment by Gelesh** [comment]
https://github.com/tensorflow/tensorflow/pull/55272 should fix this !!
