### ISSUE TITLE
Example code of tfd.Independent seems to be incorrect.

### ISSUE THREAD

**Issue by matthewlujp** [tensorflow/tensorflow#55212]
## URL(s) with the issue:
https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Independent

## Description of issue (what needs changing):
The example code provided seems to be incorrect.
In my understanding ind.batch_shape should be [2] and even_shape should be [3].

```
# Make independent distribution from a 2-batch bivariate Normal.
  ind = tfd.Independent(
      distribution=tfd.MultivariateNormalDiag(
          loc=[[-1., 1], [1, -1]],
          scale_identity_multiplier=[1., 0.5]),
      reinterpreted_batch_ndims=1)

# All batch dims have been 'absorbed' into event dims.
ind.batch_shape  # ==> []
ind.event_shape  # ==> [2, 2]
```

**Comment by tilakrayal** [comment]
@matthewlujp ,
This issue is more related to tensorflow propability(tfp).Can you please post the issue in tensorflow/probability repo from [here](https://github.com/tensorflow/probability/issues) to resolve the issue.Thanks!
