### ISSUE TITLE
Model.compute_loss documentation section is not correct. compute_loss function is not called

### ISSUE THREAD

**Issue by snarb** [tensorflow/tensorflow#55216]
Hello,

[Model.compute_loss documentation section is not correct]( https://www.tensorflow.org/api_docs/python/tf/keras/Model)

compute_loss function is not called for some reason.

```
import tensorflow as tf


class MyModel(tf.keras.Model):

  def __init__(self, *args, **kwargs):
    super(MyModel, self).__init__(*args, **kwargs)
    self.loss_tracker = tf.keras.metrics.Mean(name='loss')

  def compute_loss(self, x, y, y_pred, sample_weight):
    tf.print("compute_loss is called:")
    loss = tf.reduce_mean(tf.math.squared_difference(y_pred, y))
    loss += tf.add_n(self.losses)
    self.loss_tracker.update_state(loss)
    return loss

  def reset_metrics(self):
    self.loss_tracker.reset_states()

  @property
  def metrics(self):
    return [self.loss_tracker]

tensors = tf.random.uniform((10, 10)), tf.random.uniform((10,))
dataset = tf.data.Dataset.from_tensor_slices(tensors).repeat().batch(1)

inputs = tf.keras.layers.Input(shape=(10,), name='my_input')
outputs = tf.keras.layers.Dense(10)(inputs)
model = MyModel(inputs, outputs)
model.add_loss(tf.reduce_sum(outputs))

optimizer = tf.keras.optimizers.SGD()
model.compile(optimizer, loss='mse', steps_per_execution=10)
model.fit(dataset, epochs=2, steps_per_epoch=10)
print('My custom loss: ', model.loss_tracker.result().numpy())
```

'compute_loss is called:' is not printed.  Checked on tensorflow 2.6.2

**Comment by sushreebarsa** [comment]
@snarb I tried to replicate the code on  colab using `TF 2.8.0` ,and didn't face any error reported . Could you please have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/b1cc373d83195ad065dbfd601e7f0544/55216.ipynb) and let us know if it helps?Thanks!

**Comment by snarb** [comment]
@sushreebarsa  Hi. I have checked. The mentioned problem exists on 2.6 and 2.7, but not on 2.8. Thank you!

**Comment by sushreebarsa** [comment]
@snarb Thank you for the update!
Could you please move this issue to closed status as it is resolved for you?
Thanks!

**Comment by snarb** [comment]
@sushreebarsa  yes.  Resolved for me. Thanks

**Comment by sushreebarsa** [comment]
@snarb Closing this issue as it is fixed in latest version of TensorFlow.  Thanks!
