### ISSUE TITLE
`tf.experimental.numpy.stack` should check out-of-bound `axis` 

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#55217]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
x = tf.random.uniform([5])
print(tf.experimental.numpy.stack(x, axis=-2)) # Outputs a shape [5] tensor
```

**Describe the current behavior**
In the above example, the input is a rank-1 tensor, so `axis` cannot be -2. `tf.experimental.numpy.stack` did not check the argument `axis`.

Expect it to throw an error like `tf.stack`:
```

import tensorflow as tf
x = tf.random.uniform([5])
tf.stack(x, axis=-1) # Pass
tf.stack(x, axis=-2) # ValueError: Argument `axis` = -2 not in range [-1, 1)
```

**Comment by mohantym** [comment]
Hi @ArrowIntoTheSky !
I am able to replicate this issue in 2.11 . Attached  [gist](https://colab.sandbox.google.com/gist/mohantym/f8df98b39364928b5cd88d3d91c42c3a/git_55217_2-11.ipynb) for reference.
Thank you!

**Comment by tilakrayal** [comment]
Hi,

I tried to execute the mentioned code on tf--nightly and observed the code was executed with the expected error than the out-of-bound axis. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/992cbc2e38d797437e165300951d4595/untitled2193.ipynb).
