### ISSUE TITLE
list_ops.empty_tensor_list() crashed when element_shape is a two dimensional tensor

### ISSUE THREAD

**Issue by DLFrameworkBug** [tensorflow/tensorflow#55214]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.6.0, 2.7.0
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory:

**Describe the current behavior**
When running test cases for list_ops.empty_tensor_list(), the program crashed for core dump if I used 2-d tensor in the attribute of element_shape. The normal case is using 1-d tensor like [1], but getting crashed when using [[1]].

**Describe the expected behavior**
Since users might misuse some parameters, the program would show ValueError related to incorrect shape information.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import list_ops
from tensorflow.python.platform import test

class TensorsTest(test.TestCase):

    def test_is_tensor_array(self):
        # this case will pass if using [1] in element_shape
        return list_ops.empty_tensor_list(element_shape=constant_op.constant([[1]], dtype=dtypes.int32),
                                          element_dtype=dtypes.int32) 

if (__name__ == '__main__'):
    test.main()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Here is a snapshot of the error log.
```
[ RUN      ] TensorsTest.test_is_tensor_array
2022-03-14 04:44:22.682042: F tensorflow/core/framework/tensor_shape.cc:46] Check failed: NDIMS == dims() (1 vs. 2)Asking for tensor of 1 dimensions from a tensor of 2 dimensions
Fatal Python error: Aborted

Current thread 0x00007ff0c7b02180 (most recent call first):
  File "/root/anaconda3/envs/tf2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/gen_list_ops.py", line 49 in empty_tensor_list
  File "/root/anaconda3/envs/tf2.5.0/lib/python3.7/site-packages/tensorflow/python/ops/list_ops.py", line 62 in empty_tensor_list
  File "test_bug/bug2.py", line 11 in test_is_tensor_array
  File "/root/anaconda3/envs/tf2.5.0/lib/python3.7/unittest/case.py", line 628 in run
  File "/root/anaconda3/envs/tf2.5.0/lib/python3.7/unittest/case.py", line 676 in __call__
  File "/root/anaconda3/envs/tf2.5.0/lib/python3.7/unittest/suite.py", line 122 in run
......

*** End stack trace ***
Aborted (core dumped)
```

**Comment by gadagashwini** [comment]
I could able to reproduce the issue on [Tf v2.8](https://colab.research.google.com/drive/1jF68bkWlClZXHyQoHNcFZ3UBKy_YfDJs?usp=sharing). Thanks!

**Comment by sachinprasadhs** [comment]
@JXRiver , I updated the link with Github Gist.

**Comment by mohantym** [comment]
Hi @DLFrameworkBug !
Getting a crash in [2.9](https://colab.sandbox.google.com/gist/mohantym/a0bc4b0b68da02308fe7d2bbf2ada816/-55214.ipynb#scrollTo=Qv24ISeUd2lZ) and invalidArgument error in[ nightly](https://colab.sandbox.google.com/gist/mohantym/a838d11722ab24baef1a7919695cc4ab/-55214.ipynb#scrollTo=wexsxyrRfVa4).
Thank you!

**Comment by sachinprasadhs** [comment]
Now, the session is not crashing with the nightly version,  it now throws an error saying 
`Shape must be at most rank 1 but is rank 2 [Op:EmptyTensorList]`
Please find the attached gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/2d2a368fa4198dfec545c3e6f391ae04/-55214.ipynb#scrollTo=07SAmXTqY3FS) and close the issue. Thanks!

**Comment by DLFrameworkBug** [comment]
@sachinprasadhs  Is there any link to the  commit or pull request related to the patch with my issue?
