### ISSUE TITLE
support vscode devcontiners for development

### ISSUE THREAD

**Issue by sampath017** [tensorflow/tensorflow#55213]
**System information**
- TensorFlow version (you are using): latest
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
support for vscode devcontainers is required for good dependency management and overall good support for modern development

**Comment by sushreebarsa** [comment]
@sampath017 
Can you please elaborate about your feature and please specify the use cases for this feature. Thanks!

**Comment by sampath017** [comment]
i found the preconfigured development docker images on tensorflow website, so they can we used as vscode devcontainers.
