### ISSUE TITLE
Failed to use evaluation function from TF, TypeError: tf__loss() after loading a saved model

### ISSUE THREAD

**Issue by algoteam5** [tensorflow/tensorflow#55220]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **from pip**
- TensorFlow version (use command below): 2.8
- Python version: 3.10.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory:   A100-PCI 40GB *4

**Describe the current behavior**
```
# Save and load using High-level API
siamese.save('test_model')
a = tf.keras.models.load_model("test_model", custom_objects={'contrastive_loss': loss})

## Evaluate the model
results = a.evaluate([x_test_1, x_test_2], labels_test)
print("test loss, test acc:", results)
```
After saving my trained model (assigned as `siamese`), I loaded the saved model that I just had saved (assigned as `a`) . When I perform evaluate on the loaded model (load `a`). I face this error:

`TypeError: tf__loss() takes from 0 to 1 positional arguments but 2 were given
`
**Describe the expected behavior**
When I tried evaluating with `siamese` model, it worked fine. But if I saved it, loaded it I got the above error, 

Here is my loss function:
```

def loss(margin=1):
    def contrastive_loss(y_true, y_pred):
        square_pred = tf.math.square(y_pred)
        margin_square = tf.math.square(tf.math.maximum(margin - (y_pred), 0))
        return tf.math.reduce_mean(
            (1 - y_true) * square_pred + (y_true) * margin_square
        )
    return contrastive_loss
```

**Comment by algoteam5** [comment]
@sushreebarsa Please download this folder named `test_load_model` and then run docker as follow
`docker build -t harry/sm-tf-testload:latest . && docker run --name harry_tf_testload --rm --shm-size 8G -it --gpus all harry/sm-tf-testload:latest`
Finally, please run `pyrthon testload.py` inside docker container to reproduce the error
`https://drive.google.com/drive/folders/1g7E92X2xwa7yqyIIPqe87tugz-OPy7LY?usp=sharing
`

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly ,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/320fde521ea662be6a31e0c9d98ebc5b/gist55220.ipynb) for reference.Thanks!

**Comment by gadagashwini** [comment]
@algoteam5,
Seems like issue is with custom loss function. 
Since evaluate method takes x_test and y_test
`results = a.evaluate([x_test_1, x_test_2], labels_test)`
Change this to 
`results = a.evaluate([x_test_1,x_test_2])`

**Comment by algoteam5** [comment]
Without the `labels_test`, your code could fix the error but there were no loss and accuracy values.
```
1779/1779 [==============================] - 2s 1ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
[0.0, 0.0]
```

**Comment by gadagashwini** [comment]
@algoteam5, 
`results = a.evaluate(x, y)`.


x | Input data. It could be:A Numpy array (or array-like), or a list of arrays (in case the model has multiple inputs).A TensorFlow tensor, or a list of tensors (in case the model has multiple inputs).A dict mapping input names to the corresponding array/tensors, if the model has named inputs.A tf.data dataset. Should return a tuple of either (inputs, targets) or (inputs, targets, sample_weights).
-- | --



y | Target data. Like the input data x, it could be either Numpy array(s) or TensorFlow tensor(s). It should be consistent with x (you cannot have Numpy inputs and tensor targets, or inversely). If x is a dataset, generator or keras.utils.Sequence instance, y should not be specified (since targets will be obtained from the iterator/dataset).
-- | --

**Comment by algoteam5** [comment]
I dont get this. Have you tried it yourself? `results = a.evaluate(x, y)` will produce the error as in the title. Tensorflow team should work on this problem to resovle it.

**Comment by sachinprasadhs** [comment]
Apologies for the delayed response, have you tried to save the model through `tf.keras.models.save_model()`, also it looks like you are saving a model from Tensorflow version before to 2.5. Is it possible for you to save and load in the latest version, else please check if you're able to see the `keras_metadata.pb` in the saved model directory. Thanks!
