### ISSUE TITLE
MutexLock should not segfault given a non-mutex

### ISSUE THREAD

**Issue by kanghj** [tensorflow/tensorflow#55234]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.8.0
- Python version:3.7.12
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
Given the following code:
```
import numpy as np
import tensorflow as tf

tf.raw_ops.MutexLock(mutex=np.shape(a=4))
```
This currently crashes the colab notebook. On a different machine, it leads to a segfault.

**Describe the expected behavior**

Tensorflow should throw an exception rejecting the invalid argument.  Tensorflow should reject the `mutex` argument since it's not a mutex resource (`A Tensor of type resource`, based on https://www.tensorflow.org/api_docs/python/tf/raw_ops/MutexLock)

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1cwMDIYX9pruA1eG22eYykAxlbhDayjT8?usp=sharing

```
import numpy as np
import tensorflow as tf

tf.raw_ops.MutexLock(mutex=np.shape(a=4))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/1698f2822d4c658961418a0dd5b52f2d/55234.ipynb)  for reference.Thanks!

**Comment by wangpengmit** [comment]
@kanghj Thanks for the finding! We'll fix the dtype sanity check for `MutexLock`.

**Comment by gowthamkpr** [comment]
@kanghj This has been fixed in the latest version of tf-nightly. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/e8863d0b888966f41e807d2b091a6b76/untitled369.ipynb). Please close the issue as it has been resolved. Thanks!
