### ISSUE TITLE
C-API Binaries for 32-bit for x86 instruction set

### ISSUE THREAD

**Issue by CometManAtGitHub** [tensorflow/tensorflow#55257]
**System information**
- TensorFlow version (you are using): 2.7.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Tensorflow provides Windows binaries for the C-API for 64-bit processprs for instruction set x86 (= x64), see:
https://www.tensorflow.org/install/lang_c#supported_platforms

It would be great to support this for 32-bit also.

**Who will benefit with this feature?**
Projects requiring to build in 32-bit and 64-bit OS.

**Comment by gadagashwini** [comment]
@CometManAtGitHub,

We no longer build 64bit TF. The code assumes 64 bits in several places, so building from source might still lead into errors.

**Comment by gadagashwini** [comment]
Closing as stale. Please reopen if you'd like to work on this further.

**Comment by gadagashwini** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/54687)
[No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/54687)
