### ISSUE TITLE
[RNN] Max and min for dynamic tensors should be recorded during calibration: Failed for tensor arg1 Empty min/max for tensor arg1

### ISSUE THREAD

**Issue by schmiph2** [tensorflow/tensorflow#55267]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.8.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

[Colab Link
](https://colab.research.google.com/drive/1FMUCqyB48x88mEwhIJA1KM1SKA1SDWwb?usp=sharing
)

```
import tensorflow as tf

# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the input image so that each pixel value is between 0 to 1.
train_images = train_images / 255.0
test_images = test_images / 255.0

# Define the model architecture
model = tf.keras.Sequential([
  tf.keras.layers.InputLayer(input_shape=(28, 28)),
  tf.keras.layers.GRU(5,return_sequences=True),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(10)
])

# Train the digit classification model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit(
  train_images,
  train_labels,
  epochs=1,
  validation_data=(test_images, test_labels)
)

# Wrap it into function (like in https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb )
run_model = tf.function(lambda x: model(x))
BATCH_SIZE = 1
concrete_func = run_model.get_concrete_function(
    tf.TensorSpec([BATCH_SIZE, model.input.shape[1], model.input.shape[2]], model.inputs[0].dtype))

MODEL_DIR = "keras_model"
model.save(MODEL_DIR, save_format="tf", signatures=concrete_func)

# Convert it using integer quantization with int16 activations
converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
converter.inference_input_type = tf.int16
converter.inference_output_type = tf.int16

mnist_train, _ = tf.keras.datasets.mnist.load_data()
images = tf.cast(mnist_train[0], tf.float32) / 255.0
mnist_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)
def representative_data_gen():
  for input_value in mnist_ds.take(10):
    # Model has only one input so each data point has one element.
    yield [input_value]
converter.representative_dataset = representative_data_gen

tflite_16x8_model = converter.convert()
```
Output:
`RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor arg1
Empty min/max for tensor arg1`

I'm trying to quantize this model using 8 bit for weights and 16 bit for activations. Code works perfectly if full 8 bit quantization (including activations) is used or if the GRU layer is removed. So the experimental 8x16 bit quantization seems to fail for GRUs.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
flatbuffers downgraded to version 1.12, got error otherwise (same as in https://github.com/tensorflow/tensorflow/issues/51590#issuecomment-912614740 ).

**Comment by tilakrayal** [comment]
@schmiph2 ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/64968250/how-to-solve-runtime-error-empty-min-max-for-tensor-cast-while-doing-post-train) and the [issue](https://github.com/tensorflow/tensorflow/issues/39718) with the similar error.It helps.Thanks!

**Comment by schmiph2** [comment]
Unfortunately, these links didn't help me. The problem is really just with the [16x8 quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8) of the GRU layer. If I remove the GRU layer, I can use the 16x8 quantization. Furthermore, when I switch to 8x8 quantization, everything works fine (including the GRU layer).

If you want to test it yourself without the GRU layer, please comment out the line `tf.keras.layers.GRU(5,return_sequences=True)` in the [colab notebook](https://colab.research.google.com/drive/1FMUCqyB48x88mEwhIJA1KM1SKA1SDWwb?usp=sharing).

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? It is replicating in  [2.8](https://colab.sandbox.google.com/gist/mohantym/0dc1a1da6c14d21d7106845e79ad3b00/gru_post_training_integer_quant_16x8.ipynb#scrollTo=BzYaZhHk8ZAR) but throwing different error in [2.7](https://colab.sandbox.google.com/gist/mohantym/fe9acca2be0a5de06d1ebcf63f3f148b/gru_post_training_integer_quant_16x8.ipynb#scrollTo=BzYaZhHk8ZAR), [nightly](https://colab.sandbox.google.com/gist/mohantym/87f59acdd3648a353692946e745c993d/gru_post_training_integer_quant_16x8.ipynb#scrollTo=hWSAjQWagIHl) .

**Comment by pjpratik** [comment]
The issue still exists with TF 2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/38fc80633f2afac5efdb16130d3246e9/55267.ipynb). Thank you.

**Comment by LXP-Never** [comment]
I also encountered this problem. From tensorflow 2.8 to 2.11, this problem still exists. Does the official plan to make any fixes?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
