### ISSUE TITLE
List of TF ops that tf.vectorized_map supports

### ISSUE THREAD

**Issue by pure-rgb** [tensorflow/tensorflow#55260]
Where can I get this information? 

Which tf operation is a vectorized operation? and which one is not?

**Comment by sushreebarsa** [comment]
@Suzan009 
Please refer this [link ](https://www.tensorflow.org/api_docs/python/tf/vectorized_map) and let us know if ir helps?This is not a bug or feature request,for any further queries please post this issue in TF discussion [forum](https://discuss.tensorflow.org/) as there is a larger community to help.Thanks!

**Comment by bhack** [comment]
It seems that [is not available](https://github.com/keras-team/keras-cv/pull/146#issuecomment-1063495630) so it Is a valid feature request.

Also, If you are looking instead for XLA supported ops, Markdowns tables are not updated by years as you can find in the related ticket https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247

/cc @wangpengmit @rohan100jain

**Comment by wangpengmit** [comment]
The solution should be similar to https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247, an auto-gen tool that dumps `tf.vectorized_map`'s internal registration table to a markdown file.

**Comment by bhack** [comment]
> The solution should be similar to https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247, an auto-gen tool that dumps `tf.vectorized_map`'s internal registration table to a markdown file.

Yes but we also need to find an internal orchestration owner cause orchestration It is not opensoruce/visibile to the community

**Comment by Suzan009** [comment]
update?

**Comment by Suzan009** [comment]
Is there any pages listed down the vectorized operation list

**Comment by wangpengmit** [comment]
CCing @ishark .

**Comment by bhack** [comment]
> The solution should be similar to https://github.com/tensorflow/tensorflow/issues/14798#issuecomment-1047796247, an auto-gen tool that dumps tf.vectorized_map's internal registration table to a markdown file.

For that one I have now a PR
https://github.com/tensorflow/tensorflow/pull/56510
