### ISSUE TITLE
Hexagon delegate doesn`t work on Android devices, cannot be loaded library UnsatisfiedLinkError (CMake)

### ISSUE THREAD

**Issue by YevhenServetnykSD** [tensorflow/tensorflow#55269]
**System information**
- OS Platform and Distribution: build with ubuntu:18.04(docker image)
-  Samsung S7 tab (SM-T875, Android12, Snapdragon 865), Samsung S21 (SM-G9910, Snapdragon 888, Android 12), Vivotek FT9392-EHTV-0 (Smart Camera, Qualcomm SOC, Custom Android OS API 27 - Azena OS)
- TensorFlow version: 2.5.0
- Python version: 3.6
- Installed using bazel build
- Bazel version: bazel-3.7.2
- Compiler version: clang(ndk;18.1.5063045)
- CUDA/cuDNN version: not used
- GPU model and memory:  not used

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
TF build with this command:
```
    bazel --output_base=. build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so && \
    bazel --output_base=. build -c opt --config=android_arm64 tensorflow/lite/delegates/hexagon:hexagon_delegate && \
    bazel --output_base=. build -c opt --config=android_arm64  tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so
```
Linkage: 
CMake:
```
target_link_libraries(TFLite INTERFACE "/opt/tflite/lib/libtensorflowlite.so" "/opt/tflite/lib/libhexagon_delegate.so" "/opt/tflite/lib/libhexagon_interface.so" log)
```
CppCode (based on https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/utils.cc#L132):
```
tflite::Interpreter::TfLiteDelegatePtr CreateHexagonDelegate(
 const TfLiteHexagonDelegateOptions* options,
 const std::string& library_directory_path) {
	if (library_directory_path.empty()) {
		TfLiteHexagonInit();
	} else {
		TfLiteHexagonInitWithPath(library_directory_path.c_str());
	}

	TfLiteDelegate* delegate = TfLiteHexagonDelegateCreate(options);
	if (!delegate) {
		TfLiteHexagonTearDown();
		return CreateNullDelegate();
	}
	return tflite::Interpreter::TfLiteDelegatePtr(delegate, [](TfLiteDelegate* delegate) {
		TfLiteHexagonDelegateDelete(delegate);
		TfLiteHexagonTearDown();
	});
}

tflite::Interpreter::TfLiteDelegatePtr CreateDelegate() {
        // path from tablet
	std::string library_directory_path = "/system/vendor/lib/rfsa/adsp";
	TfLiteHexagonDelegateOptions options = {0};
	bool profiling = true;
	options.print_graph_profile = profiling;
	return CreateHexagonDelegate(&options, library_directory_path);
}
```

Aar contains: libhexagon_interface.so; libhexagon_delegate.so; libtensorflowlite.so; libhexagon_nn_skel(_v66/_v65/).so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
Failed to load library
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libadsprpc.so" not found: needed by /data/app/~~61iiTanIn8XaBlzk1Msb3g==/com.brainbuilder-fKAm_DWPORj_MBhTzkwZqQ==/base.apk!/lib/arm64-v8a/libhexagon_interface.so in namespace classloader-namespace
```

**Comment by karimnosseir** [comment]
I am wondering if this is related to open sourcing the hexagon interface code, where some refactoring caused an issue here.

Few suggestions / questions:

1) Do you get the same issue when you run evaluation tool, benchmark tool using adb ?
2) Do you face same issue when running on older versions ?
3) Do you face same issue when using the precompiled aar ?

Thanks
