### ISSUE TITLE
model.fit error, I need to adjust my code for a 5 categories instead of two.

### ISSUE THREAD

**Issue by youssefelnaggar** [tensorflow/tensorflow#55270]
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D

X = pickle.load(open("X.pickle","rb"))
y = pickle.load(open("y.pickle","rb"))

X = X/255.0

model = Sequential()

model.add(  Conv2D(64,  (3,3), input_shape = X.shape[1:]  ))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,  (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation("relu"))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss="categorical_crossentropy",
              optimizer="adam",
              metrics=['accuracy'])

model.fit(X, [y], batch_size=32, epochs=30, validation_split=0.1)

**Comment by youssefelnaggar** [comment]
ValueError                                Traceback (most recent call last)
[<ipython-input-138-bed1b8040615>](https://localhost:8080/#) in <module>()
     32               metrics=['accuracy'])
     33 
---> 34 model.fit(X, [y], batch_size=32, epochs=30, validation_split=0.1)
     35 

1 frames
[/usr/local/lib/python3.7/dist-packages/keras/engine/data_adapter.py](https://localhost:8080/#) in train_validation_split(arrays, validation_split)
   1478     raise ValueError(
   1479         "`validation_split` is only supported for Tensors or NumPy "
-> 1480         "arrays, found following types in the input: {}".format(unsplitable))
   1481 
   1482   if all(t is None for t in flat_arrays):

ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class...

**Comment by tri008** [comment]
Change y to a numpy array
y=np.array(y)

**Comment by youssefelnaggar** [comment]
thank you so much\

**Comment by chunduriv** [comment]
@youssefelnaggar,

Could you please confirm if this issue is resolved for you? Thanks!

**Comment by youssefelnaggar** [comment]
Yes. Thank you !

**Comment by chunduriv** [comment]
@youssefelnaggar,

Please feel free to close the issue. Thanks!
