### ISSUE TITLE
tf.function condition with tensor

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#55278]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
colab
- TensorFlow version (use command below):
default colab
- Python version:
default colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```python 
@tf.function
def test():
  b = tf.math.maximum(0,1)
  if 0 < b <= 2:
   b = b+1
  return b
test().numpy()
```
```python
OperatorNotAllowedInGraphError: in user code:

    File "<ipython-input-80-cfa5312e70c9>", line 4, in test  *
        if 0 < b <= 2:

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```

**Describe the expected behavior**
I suppose that it will give `2` as with this little modified version:

```python
@tf.function
def test():
  b = tf.math.maximum(0,1)
  if 0 < b and b <= 2:
   b = b+1
  return b
test().numpy()
```
```python
2
```
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
With some hints
- Briefly describe your candidate solution(if contributing):
I need some pointer

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Just to share more debugging info for the failing and working case:

```python
INFO:tensorflow:Source code of <function test at 0x7f06040d5160>:

@tf.function
def test():
  b = tf.math.maximum(0,1)
  if 0 < b and b <= 2:
   b = b+1
  return b


INFO:tensorflow:Transformed <function test at 0x7f06040d5160>:

# coding=utf-8
def tf__test():
    with ag__.FunctionScope('test', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        b = ag__.converted_call(ag__.ld(tf).math.maximum, (0, 1), None, fscope)

        def get_state():
            return (b,)

        def set_state(vars_):
            nonlocal b
            (b,) = vars_

        def if_body():
            nonlocal b
            b = ag__.ld(b) + 1

        def else_body():
            nonlocal b
            pass
        ag__.if_stmt(ag__.and_(lambda : 0 < ag__.ld(b), lambda : ag__.ld(b) <= 2), if_body, else_body, get_state, set_state, ('b',), 1)
        try:
            do_return = True
            retval_ = ag__.ld(b)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)
```
```python
INFO:tensorflow:Source code of <function test at 0x7ff34af56160>:

@tf.function
def test():
  b = tf.math.maximum(0,1)
  if 0 < b <= 2:
   b = b+1
  return b


INFO:tensorflow:Transformed <function test at 0x7ff34af56160>:

# coding=utf-8
def tf__test():
    with ag__.FunctionScope('test', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        b = ag__.converted_call(ag__.ld(tf).math.maximum, (0, 1), None, fscope)

        def get_state():
            return (b,)

        def set_state(vars_):
            nonlocal b
            (b,) = vars_

        def if_body():
            nonlocal b
            b = ag__.ld(b) + 1

        def else_body():
            nonlocal b
            pass
        ag__.if_stmt(0 < ag__.ld(b) <= 2, if_body, else_body, get_state, set_state, ('b',), 1)
        try:
            do_return = True
            retval_ = ag__.ld(b)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)
```

**Comment by bhack** [comment]
The 2nd autograph is valid so I think that there is some kind of false positive:
```python
from tensorflow.python.autograph.impl import api
ag__ = api._TRANSPILER.get_extra_locals()['ag__']  # pylint:disable=protected-access
def tf__test():
    with ag__.FunctionScope('test', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        b = ag__.converted_call(ag__.ld(tf).math.maximum, (0, 1), None, fscope)

        def get_state():
            return (b,)

        def set_state(vars_):
            nonlocal b
            (b,) = vars_

        def if_body():
            nonlocal b
            b = ag__.ld(b) + 1

        def else_body():
            nonlocal b
            pass
        ag__.if_stmt(0 < ag__.ld(b) <= 2, if_body, else_body, get_state, set_state, ('b',), 1)
        try:
            do_return = True
            retval_ = ag__.ld(b)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)

print(tf__test().numpy())
```
```python
2
```

**Comment by bhack** [comment]
The second form seems to pass with:
`@tf.function(experimental_autograph_options=tf.autograph.experimental.Feature.EQUALITY_OPERATORS)`

/cc @mdanatg

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/blob/87462bfac761435a46641ff2f10ad0b6e5414a4b/tensorflow/python/autograph/converters/logical_expressions.py#L89-L90

**Comment by mdanatg** [comment]
Odd, I thought we had enabled that feature by default. But I think if was left off as Tensor implemented its own `__eq__` , `__lt__`, etc. This use case indicates that we should turn it on anyway.

**Comment by bhack** [comment]
> Odd, I thought we had enabled that feature by default. But I think if was left off as Tensor implemented its own `__eq__` , `__lt__`, etc. This use case indicates that we should turn it on anyway.

Is https://github.com/tensorflow/tensorflow/issues/55278#issuecomment-1073058951 running fine cause we are in eager mode?

**Comment by mdanatg** [comment]
Yes. When evaluating `a < b < c` Python calls something in the lines of `(a < b).__bool__()`, which only works in eager mode.

**Comment by mdanatg** [comment]
Yep, Python has uses a bit of magic in this case. I find is easiest to explain by crafting a class with overloaded operators and running it:

```
class C():

  def __init__(self, name):
    self.name = name

  def __lt__(self, other):
    print('__lt__: ', self.name, '<', other.name)
    return C('result of ' + self.name + ' < ' + other.name)
  
  def __bool__(self):
    print('__bool__: ', self.name)
    return True

  def __repr__(self):
    return self.name

a = C('a')
b = C('b')
c = C('c')

print(a < b < c)
```

BTW, the `max` case could be a feature requerst for autograph to replace `tf.maximum` - we do that for a few builtins like `len`, and it's a fairly straightforward change: http://google3/third_party/tensorflow/python/autograph/operators/py_builtins.py;l=630;rcl=408616219

**Comment by bhack** [comment]
> Yep, Python has uses a bit of magic in this case. I find is easiest to explain by crafting a class with overloaded operators and running it:

It is still hard for an avg developer to understand that we probably want to collect this case as a new `Autograph` ticket. 
Do you think that we could improve the string:
`OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

>  http://google3/third_party/tensorflow/python/autograph/operators/py_builtins.py;l=630;rcl=408616219

Sorry, I don't have access to the internal system.

**Comment by bhack** [comment]
P.s. I would like to make a PR for both the cases but I will go for sure to abuse the CI with a blackbox impl as I've described in https://github.com/tensorflow/tensorflow/pull/55192#issue-1165231429.
And in this case it will require for sure  more CI cycles so this will go to slowdown the PR too much without locally executing tests.

**Comment by mdanatg** [comment]
Oops, edited.

Yes, improving the error message makes sense too; one challenge is that it comes from outside of autograph, and can be triggered from other places as well.

**Comment by bhack** [comment]
@mdanatg Let me know how I could help you. If required I could spent/invest again many computing hours to rebuild TF with a fresh commit. I still think it will be faster for you with your build infra but if you don't have free slots give me some pointers I would try to rebuild "again" TF. 

I see 3 activities here:
- Default enable `tf.autograph.experimental.Feature.EQUALITY_OPERATORS`
- Extend buitlin ops for `tmin` and `max` + test.
- Improve `OperatorNotAllowedInGraphError: using a tf.Tensoras a Pythonbool is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

**Comment by mdanatg** [comment]
It's definitely easier for me to test, though I'm not sure when I'll have the bandwidth. For very simple changes, I think it'd be ok to rely on the CI instead of building locally. BTW, I think basic building is a bit more practical on linux nowadays - especially if you use the [docker container](https://www.tensorflow.org/install/source#cpu-only); you don't need to build the whole pip package, just `bazel test` the unit test straight after `./configure`.

For now, how about we keep this issue for the first bullet, and file separate ones for the other two bullets?

**Comment by bhack** [comment]
As we are not going to care/solve these build topics quite soon I need to invest many hours to rebuild again TF.

 For the fist point do you have a specific pointer for the tests I need to run/pass? Is `bazel test tensorflow/python/autograph/operator` enough?

As just `bazel test tensorflow/python/autograph/operator` already requires  more then 27k targets if the bazel estimation is correct:

`INFO: Analyzed target //tensorflow/python/autograph/operators:operators (372 packages loaded, 27441 targets configured).`

**Comment by mdanatg** [comment]
> As we are not going to care/solve these build topics quite soon I need to invest many hours to rebuild again TF.

I admit it's frustrating :( Most PRs rely on the internal build system, making it hard to get traction to improve the external one.

> For the fist point do you have a specific pointer for the tests I need to run/pass? Is bazel test tensorflow/python/autograph/operator enough?

I'd say, just `tensorflow/python/autograph/operators:py_builtins_test` and `tensorflow/python/autograph/converterd:logical_expressions_test` (especially if you add a test in there). The main idea is to test that the code builds and runs, and let the CI catch any other corner cases.

> As just bazel test tensorflow/python/autograph/operator already requires more then 27k targets if the bazel estimation is correct:

Looks about right, though IIRC it can grow up to 50k. It practically builds the whole TF, it's just that you'll run far fewer tests.

**Comment by bhack** [comment]
> I admit it's frustrating :( Most PRs rely on the internal build system, making it hard to get traction to improve the external one.

It Is one of the "chicken or the egg" problem for community growing.

I will ping you when the compilation is done.
