### ISSUE TITLE
Event file summary metric type changed, breaking the example in summary_iterator.py

### ISSUE THREAD

**Issue by timatim** [tensorflow/tensorflow#55276]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

[Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/summary/summary_iterator.py#L45)

### Clear description
```
  for e in tf.compat.v1.train.summary_iterator(path to events file):
      for v in e.summary.value:
          if v.tag == 'loss':
              print(v.simple_value)
```
Some version between TF 2.3 and TF 2.8, it seems the behavior of logging metrics in TB event files changed. Before, values were logged as `simple_value` in the proto. Now, it is logged as a tensor that requires additional parsing with `tf.make_ndarray()` for example. As a result, this example in the documentation here no longer works. I'm not sure if the change to metrics writing was intentional (wasn't able to find release notes on that) but we should update the documentation here to a working one.

TF 2.3 gist: https://colab.research.google.com/gist/timatim/067edda865dc9c0899bda0befd97930c/beginner.ipynb
```
v.simple_value
```
TF 2.8 gist: https://colab.research.google.com/gist/timatim/2828cf9aa67e77d20baa22fc9935a684/beginner.ipynb
```
tf.make_ndarray(v.tensor)
```

**Comment by chunduriv** [comment]
@timatim,

Thanks for reporting. Created CL to fix above issue.

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
