### ISSUE TITLE
Build from Source Instructions for Tensorflow C++ on Linux

### ISSUE THREAD

**Issue by amehrish** [tensorflow/tensorflow#55279]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/cc
https://blog.devgenius.io/standalone-c-build-tensorflow-opencv-6dc9d8a1412d

## Description of issue (what needs changing):
Please could you provide clear instructions for building Tensorflow C++ 2.x (2.4 and above) on Linux and potentially how to use the built library in a project with all its dependencies such as Eigen, protobuf and abseil? 

### Clear description
The documentation says that Tensorflow provides a stable C++ API but no build and usage (compiling and linking with CMake) appear to exist in documentation. I have spent a lot of time  dredging  for relevant information in articles and stackoverflow and realised that most of it is outdated becasue bazel-genfiles  folder doesnt exist and has been replaced quite possibly with bin folder, and there is no contrib file as well anymore which allowed easy building of dependencies. 

It would be of great help if the Tensorflow Developers could demonstrate through a simple example for VS Code (it has become a standard) in Ubuntu, how to compile and link the library using CMake and ideally a descriptive example where a developer gets the idea of the capability of C++ API? It would be very useful if you could please make it clear what is possible with C++ API and what is not. For instance if C++ API also allows building the graph or just accepts the .pb file or how much of this example can be done in C++ API for instance as a cross reference: https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras ? 

Is it possible to do everything in C++ and not use Python at all ? 

Why should someone use this method? How is it useful?
Tensorflow documentation should be the one stop shop for all official information about tensorflow especially associated with building, compiling and linking the library where the API is available, There is information on C API but not C++. Tensorflow is written in C++ (I believe) so it is not unfair to request the developers to help guide the users, how to use the C++ API well. Not sure why this hasn't already been done. If this information exists somewhere, I would very much appreciate if you could please make it more obvious. Python is popular but C++ is also useful in production performant environments. You all are doing a great job developing and building this library and I can only be grateful for that. I am very much hoping that you would help me and many other developers. Thanks very much.

**Comment by gadagashwini** [comment]
@amehrish,

Build Tensorflow C++ from source using

`bazel build -c dbg --config=opt //tensorflow:tensorflow_cc.dll`

**Comment by amehrish** [comment]
Is there any official documentation that shows how to use the C++ API through examples like it has been the case with Python API?

**Comment by amehrish** [comment]
I have managed to build the build link C++ API on Linux and can build a graph etc. One example that shows, how to use the C++ API from start to finish will go a long way. Thank you

**Comment by amehrish** [comment]
Some example that used to be there earlier for C++ have been removed

**Comment by dangerginger** [comment]
I was just searching for the answer to this, and it seems that there is still no official documentation for building the C++ library nor simple examples, as @amehrish pointed out. I would also appreciate this and I am sure there are many other C++ developers who would welcome such instructions.
