### ISSUE TITLE
The code says that it failed to save and then never ran properly again. basically i upload a picture and then it shows the right prediction but the second picture it run into error but if i start with second photo as my first inout then it show the correct prediction 

### ISSUE THREAD

**Issue by youssefelnaggar** [tensorflow/tensorflow#55289]
from google.colab import files
uploaded = files.upload()

new_image = plt.imread('20220316_134951.jpg')
img = plt.imshow(new_image)

from skimage.transform import resize
resized_image = resize(new_image, (IMG_SIZE,IMG_SIZE,3))
img = plt.imshow(resized_image)

predictions = model.predict(np.array([resized_image]))

predictions

list_index = [0,1,2,3,4]
x = predictions

for i in range(5):
  for j in range(5):
    if x[0][list_index[i]] > x[0][list_index[j]]:
      temp = list_index[i]
      list_index[i] = list_index[j]
      list_index[j] = temp

for i in range(3):
  print(CATEGORIES[list_index[i]], ':', predictions[0][list_index[i]] *100, '%')

print(CATEGORIES[list_index[0]])

**Comment by tilakrayal** [comment]
@youssefelnaggar ,
 In order to expedite the trouble-shooting process, could you please provide  code dependencies and the TensorFlow version you are using.Also could you please create a virtual environment and test your code again. It helps. Thanks!
