### ISSUE TITLE
The tensorflow training freezes for no reason

### ISSUE THREAD

**Issue by pengzhangzhi** [tensorflow/tensorflow#55283]
I run a deep learning training code written in tensorflow and it seems stuck at the following code:
```python
history = model.fit(X_train_all, Y_train_all,
                        epochs=nb_epoch,
                        batch_size=batch_size,
                        validation_data=(X_test, Y_test),
                        # callbacks=[early_stopping, model_checkpoint],
                        # callbacks=[model_checkpoint, lr_callback],
                        callbacks=[model_checkpoint],
                        verbose=0)
```
I tried to look closely and found it actually stuck at 
```python
# coding=utf-8
def outer_factory():

    def inner_factory(ag__):

        def tf__rmse(y_true, y_pred):
            with ag__.FunctionScope('rmse', 'fscope', ag__.STD) as fscope:
                do_return = False
                retval_ = ag__.UndefinedReturnValue()
                try:
                    do_return = True
                    retval_ = (ag__.converted_call(ag__.ld(mean_squared_error), (ag__.ld(y_true), ag__.ld(y_pred)), None, fscope) ** 0.5)
                except:
                    do_return = False
                    raise
                return fscope.ret(retval_, do_return)
        return tf__rmse
    return inner_factory
```
The outputs:
```bash
training model...
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "
2022-03-18 07:54:21.572669: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-03-18 07:54:21.589590: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2300020000 Hz
2022-03-18 07:54:21.624242: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2022-03-18 07:54:23.469658: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-03-18 07:54:23.863409: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "
```
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): `pip3 install tensorflow ==2.4.1`
- TensorFlow version (use command below): tensorflow                    2.4.1
- Python version: Python 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA Version: 11.6 
- GPU model and memory: Tesla V100-SXM2...

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by pengzhangzhi** [comment]
I also run other tensorflow codes, they all work well. I guess if it is the problem of the model achitecture?

**Comment by tilakrayal** [comment]
@pengzhangzhi ,
Can you please update to latest tensorflow version v2.8  fron this [link](https://www.tensorflow.org/install/source#gpu) and test your code.It helps.Thanks!
