### ISSUE TITLE
TFX Starter Tutorial Typo

### ISSUE THREAD

**Issue by LukasS91** [tensorflow/tensorflow#55282]
Hello,

there is a typo in the TFX [starter tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple#run_the_pipeline).

LocalDagRunner provides fast iterations for **developemnt** and debugging. TFX also supports other orchestrators including Kubeflow Pipelines and Apache Airflow which are suitable for production use cases.

**Comment by mohantym** [comment]
Hi @LukasS91 !  Could you please post this on [TFX ](https://github.com/tensorflow/tfx)github repo? Thanks!

**Comment by chunduriv** [comment]
@LukasS91, 

Thanks for reporting. Created [PR](https://github.com/tensorflow/tfx/pull/4773) to fix this issue. Thanks!

**Comment by rthadur** [comment]
Changes have been fixed and merged in this PR https://github.com/tensorflow/tfx/pull/4891 , will be closing this issue. Thank you
