### ISSUE TITLE
self._interpreter.AllocateTensors() returns with error : +1: Node number 189 (ADD) failed to prepare.

### ISSUE THREAD

**Issue by MadhuriPatil1694** [tensorflow/tensorflow#55284]
After converting model to tflite successfully getting error at interpreter.AllocateTensors() 
### 1. System information
tensorflow 2.6
onnx 1.9
python 3.6

#### code to invoke the TFLite Converter Python API and the errors.
converter = tf.lite.TFLiteConverter.from_saved_model('/model.pb')
 converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
    ]
    
  tflite_model = converter.convert()
  tflite_model_path = 'test_net_.tflite'
    # Save the model
  with open(tflite_model_path, 'wb') as f:
        f.write(tflite_model)
interpreter = tf.lite.Interpreter(model_path="test_net_.tflite")
interpreter.allocate_tensors()

error logs:
INFO: Created TensorFlow Lite delegate for select TF ops.
2022-03-18 12:56:44.148260: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-18 12:56:44.149833: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
INFO: TfLiteFlexDelegate delegate: 11 nodes delegated out of 1402 nodes with 3 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 0 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 0 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 0 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 0 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 8 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 14 nodes with 1 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 8 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 2 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 14 nodes with 0 partitions.

Traceback (most recent call last):
  
  File "/home/usr/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 423, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Given shapes, [1, 63, 95, 256] and [1, 64, 96, 256], are not broadcastable.Node number 189 (ADD) failed to prepare.

**Comment by chunduriv** [comment]
@MadhuriPatil1694,

In order to expedite the trouble-shooting process, please provide a complete code snippet  and `model.pb` to reproduce the issue reported here. Thanks!

**Comment by MadhuriPatil1694** [comment]
> @MadhuriPatil1694,
> 
> In order to expedite the trouble-shooting process, please provide a complete code snippet and `model.pb` to reproduce the issue reported here. Thanks!

tensorflow model and the converted tflite model is at path https://drive.google.com/drive/folders/1BAGSERjLu5Qgrp47rXGJF8ByfLv9K33v?usp=sharing

**Comment by chunduriv** [comment]
i was able to replicate the issue using TF2.8. Please find the gist [here](https://colab.sandbox.google.com/gist/mohantym/c9888d6e3d0a1a45e8390d72d6236464/github_55284.ipynb) for reference.

**Comment by MeghnaNatraj** [comment]
@MadhuriPatil1694 could you check if the inputs provided has the right shape? Refer to https://github.com/tensorflow/tensorflow/issues/49216

**Comment by MadhuriPatil1694** [comment]
Yes while exporting the model I provided correct input shape

**Comment by Shishir-Suman** [comment]
Anyone found a fix for this? Facing similar issue

**Comment by sushreebarsa** [comment]
@Shishir-Suman Please open a new ticket with all the relevant information regarding the issue you are facing?
Thank you!
