### ISSUE TITLE
Plugin implementation of AssignVarOp

### ISSUE THREAD

**Issue by slai-nick** [tensorflow/tensorflow#55295]
I am struggling a lot to understand how plugins (pluggable device) should implement `AssignVarOp`.

I created a [post](https://discuss.tensorflow.org/t/how-does-assignvarop-work/8335/3) on the discussion forum but it seems like no one is able to answer pluggable device questions.

I am trying to run a `Conv2D` on a separate device (only dummy for now) using the pluggable device interface.
I implemented the `Conv2D` kernel, and when running tensorflow asked for an implementation of `AssignVarOp`.
So I started implementing `AssignVarOp`, it has two input tensors (variable and value), variable is a tensor of type `TF_RESOURCE`.
I imagine I should modify the data of the resource tensor, but what does it contain?
After further research, it looks like `VarHandleOp` is the kernel responsible for the creation of the variable (and it's resource). 
So I wrote a kernel for `VarHandleOp`. Checking the parameters at runtime, they are all uninitialized at the first call (`shared_name` is a default value, `shape` unitialized, etc).
So I am left with two choices:
- Either I would update the variable attributes later (doesn't seem possible as the C api doesn't provide any function for modifying an input tensor dimensions)
- Either I should store all dimensions, etc in the resource tensor data in the form of a `ResourceHandle`. Is this `Resourcehandle` type arbitrarily defined by the user?

I have been following this basic [tutorial](https://github.com/jzhoulon/community/blob/plugin_tutorial/rfcs/20200624-pluggable-device-for-tensorflow/tutorial.md) for writing tensorflow plugins, but the logic for variable handling is missing and it seems like a necessary step for plugins.

**I will be really thankful if the tensorflow team (or anyone) could help me understand the mechanism of variable handling for plugins.**

**Thank you.**

**Comment by gadagashwini** [comment]
@slai-nick,
[This post](https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html), introduces the [PluggableDevice](https://github.com/tensorflow/community/blob/master/rfcs/20200624-pluggable-device-for-tensorflow.md) architecture which offers a plugin mechanism for registering devices with TensorFlow without the need to make changes in TensorFlow code. Thanks!

**Comment by artlesenson373** [comment]
With AssignVarOp, the OpKernelContext has two inputs, but expect no output.
The first input is the variable, the second input is the value.
This is analogous to me as a C++ function with a signature like AssignVarOp(TF_Tensor &variable, TF_Tensor value) ( [this](https://thepinterestvideodownloader.com/) is not meant to represent the C++ implementation in tensorflow, just an analogy where I expose the concept of an input being a reference that will get modified using the second input which contains the value).

The value input is a well formed tensor, with well defined dimensions and data, however the variable doesn’t seem well defined (no dimensions, etc).
There is no functions to modify a tensor object in the C API, nor to (re)set an input tensor.
Therefore, it is unclear to me how to assign the value to the variable just by accessing those two tensors.
