### ISSUE TITLE
org.tensorflow:tensorflow-lite-support:0.3.1 has missing files

### ISSUE THREAD

**Issue by IoanaKitsune** [tensorflow/tensorflow#55298]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When trying to deploy a TFLite model in Android Studio, I received the error ClassNotFound: about org.tensorflow.lite.support.common.SupportPreconditions.
**Describe the expected behavior**
No error.
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
modelPath = "local_path_of_model"
AudioClassifier model = AudioClassifier.createFromFile(requireContext(), modelPath);
TensorAudio tensor = model.createInputTensorAudio();
AudioRecord record = model.createAudioRecord();

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
When I downgraded to org.tensorflow:tensorflow-lite-support:0.3.0, I didn't receive the error anymore.

**Comment by tilakrayal** [comment]
@IoanaKitsune ,
Can you please refer this link which helps to upgrade [TFLite Support 0.3.1](https://github.com/tensorflow/tflite-support/releases/tag/v0.3.1). Thanks!

**Comment by Agono0** [comment]
I face the same error and i figure out the problem.
Actually the problem is `SupportPreconditions.java` is in `/org/tensorflow/lite/support/common/internal/SupportPreconditions.java` not in `/org/tensorflow/lite/support/common/SupportPreconditions.java`
With lastest version of `tensorflow-lite-support:0.3.1`
And this cause a problem with `implementation 'org.tensorflow:tensorflow-lite-task-audio:0.3.0'`
And here's the full stacktrace:
```Java
java.lang. NoClassDefFoundError: Failed resolution
of:Lorg/tensorflow/lite/support/common/SupportPreconditions;
at
org.tensorflow.lite.task.audio.classifier.AudioClassifier.createAudioRecord (AudioClassifier.java:473)
at com.test.noplv.MainActivity.onCreate (MainActivity.java:45)
at android.app.Activity.performCreate(Activity.java:7335)
at
android.app.Activity.performCreate (Activity.java:7326)
at
android.app.Instrumentation.callActivityOnCreate(Inst rumentation.java:1275) at
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3119)

at
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3282)
at
android.app.servertransaction.LaunchActivityItem.exec ute (LaunchActivityItem.java:78)
at
android.app.servertransaction.TransactionExecutor.exe cuteCallbacks (TransactionExecutor.java:108) at
android.app.servertransaction.Transaction Executor.exe cute(TransactionExecutor.java:68)
at
android.app.Activity Thread$H.handleMessage (ActivityTh read.java:1970)
at
android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop (Looper.java:214) 
at
android.app.ActivityThread.main(ActivityThread.java: 7156) at java.lang.reflect.Method.invoke (Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
```
I hope you understand me
Thanks in advance.

**Comment by IoanaKitsune** [comment]
Oh, I see, thank you so much. I temporarily downgraded and it worked, but I
think your solution helps a lot!

**Comment by tilakrayal** [comment]
@IoanaKitsune ,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status

**Comment by Agono0** [comment]
Properly not solved for me any help.
I describe the issue . But I didn't solve it

**Comment by Agono0** [comment]
I must modify the library files or what?
Then if yes.
how l can move `SupportPreconditions.java` then?

**Comment by mehranali-dev** [comment]
> I face the same error and i figure out the problem. Actually the problem is `SupportPreconditions.java` is in `/org/tensorflow/lite/support/common/internal/SupportPreconditions.java` not in `/org/tensorflow/lite/support/common/SupportPreconditions.java` With lastest version of `tensorflow-lite-support:0.3.1` And this cause a problem with `implementation 'org.tensorflow:tensorflow-lite-task-audio:0.3.0'` And here's the full stacktrace:
> 
> java.lang. NoClassDefFoundError: Failed resolution
> of:Lorg/tensorflow/lite/support/common/SupportPreconditions;
> at
> org.tensorflow.lite.task.audio.classifier.AudioClassifier.createAudioRecord (AudioClassifier.java:473)
> at com.test.noplv.MainActivity.onCreate (MainActivity.java:45)
> at android.app.Activity.performCreate(Activity.java:7335)
> at
> android.app.Activity.performCreate (Activity.java:7326)
> at
> android.app.Instrumentation.callActivityOnCreate(Inst rumentation.java:1275) at
> android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3119)
> 
> at
> android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3282)
> at
> android.app.servertransaction.LaunchActivityItem.exec ute (LaunchActivityItem.java:78)
> at
> android.app.servertransaction.TransactionExecutor.exe cuteCallbacks (TransactionExecutor.java:108) at
> android.app.servertransaction.Transaction Executor.exe cute(TransactionExecutor.java:68)
> at
> android.app.Activity Thread$H.handleMessage (ActivityTh read.java:1970)
> at
> android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop (Looper.java:214) 
> at
> android.app.ActivityThread.main(ActivityThread.java: 7156) at java.lang.reflect.Method.invoke (Native Method)
> at
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> I hope you understand me Thanks in advance.

How to solve this? i am facing this same issue.
