### ISSUE TITLE
Missing information on headers providing symbols

### ISSUE THREAD

**Issue by BenBE** [tensorflow/tensorflow#55291]
While scrolling through the API documentation I was missing the information on which headers (for C/C++) the TF (and TFLite) APIs want me to include. As I'm using [IWYU](https://github.com/include-what-you-use/include-what-you-use) it would be nice if the documentation could provide clear guidance on which headers of the API are regarded as internal implementation details and which headers are meant for use by foreign code.

Questions that should be answered by the documentation are (e.g.):
* Is there a central (set of) header(s) to include? If so which?
* Are there certain headers meant for inclusion to group several related includes?
* What headers are not typically meant for use by foreign code?

**Comment by mohantym** [comment]
Hi @BenBE ! Are you looking for the header files in these links? [C header files](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/c) , [Lite header files.](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite). Thank you!

**Comment by BenBE** [comment]
Hi @mohantym.

I'm looking at the TFLite C++ API right now for the project I'm working on. So let's look for example at [the TFLite C++ API](https://www.tensorflow.org/lite/api_docs/cc): When looking at the various symbols/types/functions there is a rough description of what things are doing. If I then follow up to look e.g. at the `tflite::InterpreterBuilder` at [here](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter-builder) I basically see:

> **tflite::InterpreterBuilder** `#include <interpreter_builder.h>`
> 
> Build an interpreter capable of interpreting model.

![image](https://user-images.githubusercontent.com/111196/159364082-d857fb7d-c6d1-42d4-92fc-914ba3cffdcc.png)

While the header file here seems to be included in this case, it's quite easy to miss, and a better layout would probably be:

> **tflite::InterpreterBuilder**
> `#include <interpreter_builder.h>`
> 
> Build an interpreter capable of interpreting model.

or 

> `#include <interpreter_builder.h>`
> **tflite::InterpreterBuilder**
> 
> Build an interpreter capable of interpreting model.

I.e. force the header line to start on a fresh line.

Where the header specs get confusing is with [`tflite::OpResolver`](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/op-resolver#classtflite_1_1_op_resolver) which describes two types on that page: `tflite::OpResolver` and `tflite::TfLiteDelegatePtrVector`. For the latter it's not evident that the include from above still holds. Also `tflite::TfLiteDelegatePtrVector` is not listed in the overall overview page (like probably others too).

So while for the top-level classes there seems to be a hint, it's not exactly intuitive or readily visible. For some other types (aliases?) it's not obvious whether they just inherit the header from the page they are documented/mentioned on.

---

The second part of my issue boils down to a question of whether `#include "tensorflow/lite/kernels/register.h"` is intended public API or if another header should be used instead. In particular which headers are intended public API (I guess `#include "tensorflow/lite/interpreter_builder.h"` is) and which headers should be treated as private implementation details? Unfortunately given both the code and the docs I couldn't quite figure out which of the various headers (in the directories you linked above) should be used as public API and which ones you should avoid (like things in `"internal/*"` and `"kernels/*"` probably? It would be nice if the documentation could be extended to include some information on this. Or if a central header (like `opencv2/opencv.hpp`) could be added, that lists all header files belonging to the public part of the API.

I hope this answer sheds some more light on the information that would be nice to see added to/clarified in the docs.

**Comment by wickson2** [comment]
I'm working on a C project implementing some generic containers and am having this weird issue when compiling. Here is some sample code that also replicates the error.
foo.h
void fooprint(void);
foo.c
 #include "foo.h"
 #include <stdio>
 void fooprint(void){
    printf("bar");
    return;
 }
main.c
#include "foo.h"
int main(void){
    fooprint();
    return 0;
}
I compile by typing
gcc main.c -o main
and this is what terminal outputs
Undefined symbols:
"_fooprint", referenced from:
  _main in ccfMXGzj.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
I'm compiling [it ](https://exams.com.pk/)on an OSX system but have also tried compiling on a red hat machine with the same effect.
The solution is probably painfully obvious but I have had multiple friends I'm working with look at this and they couldnt see the problem. I've googled around a lot but most symbol error issues are usually pertaining to objective C.

**Comment by BenBE** [comment]
@wickson2 Please use markup to format your post to include code formatting. Also I fear you question is unrelated to the issue this thread discusses.

Short form: `foo.c` defines `fooprint`, declared in `foo.h` for export. `main.c` references this function via its declaration in the included `foo.h`, but does not contain a definition of that function. When compiling your code with `gcc main.c -o main` you compile (and link) `main.c`, but not `foo.c`, thus your code references a function it knows exists (from it's declaration), but does not have the definition of what that function does. Either use `gcc main.c foo.c -o main` (not recommended, but does the job) OR better:
```console
$ gcc -o main.o -c main.c
$ gcc -o foo.o -c foo.c
$ gcc -o main main.o foo.o
```

Note the additional `-c` for compile for the first two commands and it's absence in the last one to trigger linking.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
