### ISSUE TITLE
`tf.experimental.numpy.array` should have the same behavior as `numpy.array`, but currently crashes

### ISSUE THREAD

**Issue by kanghj** [tensorflow/tensorflow#55292]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.12
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Currently, the following code snippet below leads to a crash due to the incorrect value of `ndmin`.
```
a = tf.constant(value=1)
b = tf.constant(value=1000)
tf.experimental.numpy.array(val=a,ndmin=b)
```

**Describe the expected behavior**

It should not crash.
It should have the  same behavior as numpy.array given the same inputs (in which ndmin is validated):
`ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)`

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
The following colab demonstrates the issue:
https://colab.research.google.com/drive/1Voz0WB5TCt3s5pQ2etIU3HFBZqN-YVFc?usp=sharing

**Comment by tilakrayal** [comment]
@kanghj ,
I have tried in colab with v 2.8 version and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/39587d8c4222dbbb35d876cb316973be/untitled255.ipynb). Also please find the errorlog of the crashed colab which stated as below.
`Check failed: ndims_byte() < MaxDimensions() (unsigned char value 254 vs. 254)Too many dimensions in tensor`

**Comment by kanghj** [comment]
Thanks for checking. 

Yes, indeed it crashes. The expected behavior is that`tf.experimental.numpy.array` should throw an exception (same as numpy.array), and not crash.

**Comment by tilakrayal** [comment]
@chunduriv ,
I have tried in colab with tf v2.8, v2.7, nightly and noticed that session is being crashed. Please, find the gist [here](https://colab.research.google.com/gist/tilakrayal/a0505cddfd9e7663e5c56e945b74b912/55292.ipynb). Thanks!
