### ISSUE TITLE
how to change tensorflow version if build from source?

### ISSUE THREAD

**Issue by WingsOfPanda** [tensorflow/tensorflow#55297]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 lts
- TensorFlow installed from (source or binary): source
- TensorFlow version: master
- Python version: 3.10.2
- Bazel version (if compiling from source): 5.0.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.2/8.1
- GPU model and memory: RTX 3090

**Describe the problem**

I am trying to build tensorflow from source. Everything works good and I successfully build it based on master branch. 

After I get the `.whl` package, I installed it and checked the version number. I get the following output:

```
Python 3.9.5 (default, Jun 18 2021, 13:37:06)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'2.9.0'
>>>
```

I get the version number as `'2.9.0'`. it makes sense as I build based on master branch and the current release is `2.8.0`. However, I wish to customize the version number, for example, as `2.9.0--xxx` so that I know what features I added into this build. I thought there should be a setup file or something I can change but I cannot find it. Any ideas? Thx!

**Comment by mohantym** [comment]
Hi @WingsOfPanda ! Once you cloned Tensorflow repo and entered into tensoflow folder through cd command , you can use `git checkout branch_name ` # r2.2, r2.3,r2.8 etc to select a release branch. Attaching relevant[ thread](https://www.tensorflow.org/install/source#download_the_tensorflow_source_code) for reference. Thanks!

**Comment by freedomtan** [comment]
@WingsOfPanda please refer to how the master bump the version number from 2.8.0 to 2.9.0
2719182f888c16b44dba504c2f2d2240ddc9396d

**Comment by gzygmontson13** [comment]
You can do as suggested beforehand and search for available version [in](https://inloggengids.com/) tesorflow site but you can't access versions older than available there. So if you want an earlier version: go to https://github.com/tensorflow/tensorflow. search for the version you want under branches
How to Upgrade or Downgrade TensorFlow
Python 3.6-3.9 installed and configured (check the Python version before starting). TensorFlow 2 installed. ...
The command shows information about the package, including the version. ...
Make sure to select a version compatible with your Python release. ...
How to Downgrade TensorFlow.

**Comment by mihaimaruseac** [comment]
You just need to clone the corresponding branch. For example, for TF 2.8, you need to clone `r2.8` and build from that branch.
