### ISSUE TITLE
`tf.recompute_grad` completely broken inside graph loop with big tensors

### ISSUE THREAD

**Issue by TruePikachu** [tensorflow/tensorflow#55304]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, provided.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 21H1
- TensorFlow installed from: `pip`
- TensorFlow version (use command below): `v2.8.0-rc1-32-g3f878cff5b6 2.8.0`
- Python version: 3.7.8

**Describe the current behavior**
Use of the `tf.recompute_grad` decorator inside a graph-based loop (versus Python-based with Eager) results in invalid-argument `TypeError`s. Editing the TensorFlow source to realign the arguments then results in other errors (e.g. invoking graph-mode attributes on tensors in Eager mode).

**Describe the expected behavior**
No differences (beyond what `tf.recompute_grad` is advertised to do) from when `tf.recompute_grad` is removed.

**Standalone code to reproduce the issue**
```py
import tensorflow as tf
import tensorflow.keras.layers as layers

model = tf.keras.Sequential([
    layers.Conv2D(8, kernel_size=(5, 5), padding='same', input_shape=(24, 24, 3)),
    layers.MaxPooling2D(pool_size=(24, 24), padding='valid'),
    layers.Flatten(),
    layers.Dense(3),
])

@tf.function
def run_episode(
        model: tf.keras.Model,
        max_steps: int):
    
    outs = tf.TensorArray(tf.float32, size=0, dynamic_size=True)
    for t in tf.range(max_steps):
        ins = tf.random.uniform((16, 24, 24, 3))
        out = tf.recompute_grad(model)(ins)
        outs = outs.write(t, out)
            
    return outs.stack()

with tf.GradientTape() as tape:
    lp = run_episode(model, max_steps=500)
    sigma = tf.reduce_sum(lp)
g = tape.gradient(sigma, model.trainable_variables)
```

```
[...]
TypeError: Exception encountered when calling layer "conv2d_2" (type Conv2D).

Expected float32 passed to parameter 'filter' of op 'Conv2D', got <tf.Variable 'conv2d_2/kernel:0' shape=(5, 5, 3, 8) dtype=float32> of type 'ResourceVariable' instead. Error: Expected resource passed to parameter 'resource' of op 'ReadVariableOp', got <tf.Tensor: shape=(), dtype=resource, value=<Resource Tensor>> of type 'EagerTensor' instead. Error: _capture_helper() takes 3 positional arguments but 4 were given

Call arguments received:
  • inputs=tf.Tensor(shape=(16, 24, 24, 3), dtype=float32)
```

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c35a6c318840c96bfbf530f6b795a6cb/55304.ipynb).Thanks!

**Comment by tilakrayal** [comment]
@TruePikachu,
I tried to execute the mentioned code on tensorflow v 2.15 and it was executed without any issue/error which was happening on tensorflow 2.8 and older versions. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c62e721710f0de98ac9a83965b4ba8ed/untitled1801.ipynb). Thank you!
