### ISSUE TITLE
Installation Issue - OSError: [Errno 2] No such file or directory: ...\\BufferizableOpInterface.cpp.inc

### ISSUE THREAD

**Issue by ahmad-alkadri** [tensorflow/tensorflow#55300]
**System information**
- OS Platform and Distribution: Windows 11 Professional 
- TensorFlow installed from: binary (`pip install tensorflow`)
- TensorFlow version: 2.8.0
- Python version: 3.10.3
- Installed using virtualenv: `pip`
- CUDA/cuDNN version: 11.6
- GPU model and memory: NVIDIA RTX A2000 / RAM 32 GB

Trying to install tensorflow on my PC (system described above) and found an issue as follows at the end of `pip install tensorflow`:

```
Installing collected packages: tensorflow
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\%PathToRepo%\\tfenv\\Lib\\site-packages\\tensorflow\\include\\external\\llvm-project\\mlir\\_virtual_includes\\BufferizableOpInterfaceIncGen\\mlir\\Dialect\\Linalg\\ComprehensiveBufferize\\BufferizableOpInterface.cpp.inc'
```

`tfenv` is the name of the virtual environment I've created using the command `python -m venv --system-site-packages tfenv`.
I've installed the pre-requisite (Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019) from this [link](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads). I'm guessing the error is somehow related to the MS Visual C++ or the virtual environment, but I'm not sure how.

Could you help me please? Thank you in advance.

**Comment by k-styles** [comment]
Similar to #46934

**Comment by mohantym** [comment]
Hi @ahmad-alkadri ! Can you check this [thread](https://stackoverflow.com/a/66754914/11530462) and let us know the results?

**Comment by ahmad-alkadri** [comment]
> Hi @ahmad-alkadri ! Can you check this [thread](https://stackoverflow.com/a/66754914/11530462) as workaround and let us know the results? Thank you!

Alright the installation succeeded! You're right the problem is the character limit on the path. Deactivating this limit on Windows is the solution. Thanks again!

**Comment by weeklynote** [comment]
已收到，我会尽快回复你！
                     ——刘劲字
