### ISSUE TITLE
Node: 'model/conv1d/Conv1D' DNN library is not found.

### ISSUE THREAD

**Issue by caliari-italo** [tensorflow/tensorflow#55309]
**System information**
- OS: Linux Ubuntu 20.04:
- TensorFlow installed from pip
- TensorFlow version: v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: Python 3.8.10
- CUDA/cuDNN version: NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6   
- GPU model : [GeForce GTX 1650] 

Hello, everyone.
I'm trying to run a  convolutional neural network on tensorflow but I'm receiving the current error:

> 2022-03-21 10:40:20.665473: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:20.687599: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:20.687804: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.544819: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2022-03-21 10:40:22.545204: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.545428: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.545579: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.815601: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.815824: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.815975: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2022-03-21 10:40:22.816100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2607 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
> Epoch 1/999999
> 2022-03-21 10:40:23.481069: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
> 2022-03-21 10:40:23.481615: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
> Traceback (most recent call last):
>   File "CNN_regression.py", line 367, in <module>
>     results = pd.concat([results,main(mode)], ignore_index=True)
>   File "CNN_regression.py", line 124, in main
>     history = model.fit(X_train, Y_train,
>   File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "/home/italocaliari/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
>     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:
> 
> Detected at node 'model/conv1d/Conv1D' defined at (most recent call last):
>     File "CNN_regression.py", line 367, in <module>
>       results = pd.concat([results,main(mode)], ignore_index=True)
>     File "CNN_regression.py", line 124, in main
>       history = model.fit(X_train, Y_train,
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>       return fn(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1384, in fit
>       tmp_logs = self.train_function(iterator)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1021, in train_function
>       return step_function(self, iterator)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1010, in step_function
>       outputs = model.distribute_strategy.run(run_step, args=(data,))
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step
>       outputs = model.train_step(data)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/training.py", line 859, in train_step
>       y_pred = self(x, training=True)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>       return fn(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
>       outputs = call_fn(inputs, *args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>       return fn(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/functional.py", line 451, in call
>       return self._run_internal_graph(
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/functional.py", line 589, in _run_internal_graph
>       outputs = node.layer(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
>       return fn(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1096, in __call__
>       outputs = call_fn(inputs, *args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 92, in error_handler
>       return fn(*args, **kwargs)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/layers/convolutional.py", line 248, in call
>       outputs = self.convolution_op(inputs, self.kernel)
>     File "/home/italocaliari/.local/lib/python3.8/site-packages/keras/layers/convolutional.py", line 233, in convolution_op
>       return tf.nn.convolution(
> Node: 'model/conv1d/Conv1D'
> DNN library is not found.
> 	 [[{{node model/conv1d/Conv1D}}]] [Op:__inference_train_function_660]

I'm running the exact same code with another computer with a Nvidia MX110 and is working just fine. I think this might be a configuration/installation issue related to:

>  "Loaded runtime CuDNN library: 8.0.4 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration." 

I could not find any solution to this problem.

Thank you all in advance.

**Comment by mohantym** [comment]
Hi @caliari-italo ! Could you switch to Cuda 11.2 and CuDNN 8.1 and let us know the results ? Thanks. Attaching [tested configuration](https://www.tensorflow.org/install/source#gpu) for reference. Thanks!

**Comment by mohantym** [comment]
Ok. Please use 2.8.0 stable version with Cuda 11.2 and CudNN 8.1 . Are you loading Pytorch and Tensorflow simultaneously as this[ thread ](https://forums.developer.nvidia.com/t/loaded-runtime-cudnn-incompatible-with-version-used-to-compile-source/180462)suggests? Could you provide a simple stand alone code to reproduce this issue too?

**Comment by caliari-italo** [comment]
I ended up using the TensorFlow Docker image and it worked just fine.

**Comment by mohantym** [comment]
@caliari-italo ! Shall we move this issue to closed status then?
