### ISSUE TITLE
I am getting the same errors with version 2.8.0 and python 3.9.

### ISSUE THREAD

**Issue by caligoig** [tensorflow/tensorflow#55308]
I am getting the same errors with version 2.8.0 and python 3.9.
I need to use class_weight cause of my data is heavily imbalanced. 
If I run without the class_weight, no errors.
Is there solutions or workarounds for this issue?
Thanks

When using a list for class_weight, I got:
```
  File "/opt/local/stow/Python-3.7.1/lib/python3.7/site-packages/keras/engine/data_adapter.py", line 1416, in _make_class_weight_map_fn
    class_ids = list(sorted(class_weight.keys()))
AttributeError: 'list' object has no attribute 'keys'
```
When using a dictionary for class_weight, I got:
```
  File "/opt/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

indices[24] = 18 is not in [0, 10)
         [[{{node GatherV2}}]]
         [[IteratorGetNext]] [Op:__inference_train_function_43205]
```
These errors occur even when I give all classes a weight 1.

However, when I do not use class_weight in model.fit(), the training for my model just works fine.

So it looks like I just cannot use class_weight in training. But my classes are highly imbalanced; not using class weights would train a useless model.

I would really appreciate any solution or workaround for this issue.

Thank you very much!

_Originally posted by @lauraht in https://github.com/tensorflow/tensorflow/issues/40070#issuecomment-1066037695_

**Comment by lauraht** [comment]
Hello!
I saw this issue was closed; is there a solution or workaround for this issue?
If so, could you please also share the solution or workaround here? I would greatly appreciate it!
Thank you so much!

**Comment by caligoig** [comment]
Sorry, I posted by mistake as new issue, thats why I closed it.
It is related to issues/40070 and added there as comment.
