### ISSUE TITLE
How to allow GPU memory growth under TF slim?

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5530]
Under TF library, we can set how GPU memory is used by creating a config as below and then assign to a session.

**config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)**

However, I can't find any such config to let **TF slim** library to set memory usage mode. Directly put such config to **slim.learning.train()** method?

**Comment by civilmanxx** [comment]
I just tried, at least this **train()** method does not accept **config** as parameter.

**Comment by zseymour** [comment]
The parameter is `session_config`.

See here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py#L595

**Comment by civilmanxx** [comment]
yes, the code below works. Thanks!

**session_config = tf.ConfigProto()
session_config.gpu_options.allow_growth = True
session = tf.Session(session_config=session_config)**

**Comment by tzattack** [comment]
to make it clear, the right code in tf.slim to allow memory grow is:
```
session_config = tf.ConfigProto()
session_config.gpu_options.allow_growth = True
slim.learning.train(..., session_config=session_config)
```
