### ISSUE TITLE
`tf.strings.unsorted_segment_join` crashes unexpectedly when `num_segments` is negative

### ISSUE THREAD

**Issue by kanghj** [tensorflow/tensorflow#55305]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.8.0
- Python version: 3.7.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Given the following code snippet:
```
import tensorflow as tf

try:
  tf.strings.unsorted_segment_join(inputs=['123'],segment_ids=[0],num_segments=-1)
except Exception:
  print('an exception should be thrown, but unsorted_segment_join crashes')

print('Not reached')
```
the call to `tf.strings.unsorted_segment_join`  causes a crash.

**Describe the expected behavior**

Since `num_segments` is negative, an exception should be thrown (perhaps an `InvalidArgumentError` or `ValueError`. The code should not crash.

**Standalone code to reproduce the issue**

The code snippet above should reproduce the issue. 

The following colab notebook (running the notebook should crash the session) demonstrates the issue: https://colab.research.google.com/drive/1zoYVGQXY9MlYgbtW4N3lC51yC8wQh5J2?usp=sharing

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? It is replicating[ 2.7](https://colab.sandbox.google.com/gist/mohantym/250cc06f9006f7f406e88a64a3d97988/unexpected-crash-on-unsorted_segment_join-due-to-invalid-value-of-num_segments.ipynb#scrollTo=fwNys377gUGZ), [2.8 ](https://colab.sandbox.google.com/gist/mohantym/d226528fd7dca6e208a7c9b3ebbc18c4/unexpected-crash-on-unsorted_segment_join-due-to-invalid-value-of-num_segments.ipynb#scrollTo=fwNys377gUGZ)and [nightly](https://colab.sandbox.google.com/gist/mohantym/3a38571d2f553145bb038109198167f5/unexpected-crash-on-unsorted_segment_join-due-to-invalid-value-of-num_segments.ipynb#scrollTo=_f0oULUsaDZd).
