### ISSUE TITLE
can it possible improve the tf serving performance

### ISSUE THREAD

**Issue by liumilan** [tensorflow/tensorflow#55311]
Now I train a recommend nn model offline ,and then predict it by tf serving on cpu online machine. There are 8 cores i just applied, and found it cost slow when predict it. More than 0.4% it costs 100ms when predict. The batch size request is 50. There are 167 one hot features and 3 full-connected layers.And the usage of cpu is also slow, it is only 20% usage.
How can i analyze the bottleneck of serving ,and can it possible to reduce the time cost ratio by adjust some parameters?

i have tried many ways followed this links https://www.tensorflow.org/tfx/serving/performance ,but it hardly worked.
Tf serving can't support many sparse features so well?

**Comment by tilakrayal** [comment]
@liumilan ,
This issue is more suitable for TensorFlow tfx repo. Please post it on Tensorflow/tfx repo from [here](https://github.com/tensorflow/tfx/issues). Thanks!

**Comment by liumilan** [comment]
ok,link as below 
https://github.com/tensorflow/tfx/issues/4759

**Comment by fig666** [comment]
give tf time adjusting to language input for the module response duration and input a specific time with notifications to alert tf who is working on malware prevention issues.

**Comment by tilakrayal** [comment]
@liumilan ,
Can you please close this issue, since it is already being tracked there? Thanks!
