### ISSUE TITLE
AttributeError: 'arguments' object has no attribute 'posonlyargs'

### ISSUE THREAD

**Issue by dannybarash7** [tensorflow/tensorflow#55325]
summary: while running locally the efficient net tutorial, the logs showed and error and asked to report to the tf team.
"AttributeError: 'arguments' object has no attribute 'posonlyargs'
WARNING:tensorflow:AutoGraph could not transform <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'"

**System information**
- Code is an official example of how to run efficientnet:(https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md) 
- OS Platform Linux Ubuntu 20.04, Lenovo T14, no gpu.
- TensorFlow installed from binary.
- TensorFlow version v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0.
- Python version 3.8

log:

`tpu/models/official/detection/main.py -model=retinanet --model_dir=/home/dannyb/Documents/Research/copy_paste/model_output --mode=train --eval_after_training=True --use_tpu=False "--params_override={ train: { checkpoint: { path: gs://cloud-tpu-checkpoints/retinanet/resnet50-checkpoint-2018-02-07/model.ckpt-112603, prefix: resnet50/ }, train_file_pattern: /home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco }, eval: { val_json_file: /home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco/raw-data/annotations/image_info_test-dev2017.json, eval_file_pattern: /home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco } }"
Connected to pydev debugger (build 213.7172.26)
2022-03-22 13:26:39.711187: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-03-22 13:26:39.711228: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dannybarash-t14-gen-1): /proc/driver/nvidia/version does not exist
I0322 13:26:39.726564 140697653870976 main.py:114] Model Parameters: {'anchor': {'anchor_size': 4.0,
            'aspect_ratios': [1.0, 2.0, 0.5],
            'num_scales': 3},
 'architecture': {'backbone': 'resnet',
                  'max_level': 7,
                  'min_level': 3,
                  'multilevel_features': 'fpn',
                  'num_classes': 91,
                  'output_flat_fpn_features': False,
                  'parser': 'retinanet_parser',
                  'pre_parser': None,
                  'space_to_depth_block_size': 1,
                  'use_bfloat16': False},
 'batch_norm_activation': {'activation': 'relu',
                           'batch_norm_epsilon': 0.0001,
                           'batch_norm_momentum': 0.997,
                           'batch_norm_trainable': True,
                           'use_sync_bn': False},
 'dropblock': {'dropblock_keep_prob': None, 'dropblock_size': None},
 'enable_summary': False,
 'eval': {'eval_batch_size': 8,
          'eval_dataset_type': 'tfrecord',
          'eval_file_pattern': '/home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco',
          'eval_samples': None,
          'eval_timeout': None,
          'min_eval_interval': 180,
          'num_steps_per_eval': 1000,
          'per_category_metrics': False,
          'skip_eval_loss': False,
          'suffix': '',
          'type': 'box',
          'use_json_file': True,
          'val_json_file': '/home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco/raw-data/annotations/image_info_test-dev2017.json'},
 'fpn': {'fpn_feat_dims': 256,
         'use_batch_norm': True,
         'use_separable_conv': False},
 'isolate_session_state': False,
 'model_dir': '/home/dannyb/Documents/Research/copy_paste/model_output',
 'nasfpn': {'activation': None,
            'block_fn': 'conv',
            'fpn_feat_dims': 256,
            'init_drop_connect_rate': None,
            'num_repeats': 5,
            'use_separable_conv': False,
            'use_sum_for_combination': False},
 'platform': {'eval_master': None,
              'gcp_project': None,
              'tpu': None,
              'tpu_zone': None},
 'postprocess': {'apply_nms': True,
                 'apply_sigmoid': True,
                 'max_total_size': 100,
                 'nms_iou_threshold': 0.5,
                 'nms_version': 'v1',
                 'pre_nms_num_boxes': 5000,
                 'score_threshold': 0.05,
                 'use_batched_nms': False},
 'predict': {'predict_batch_size': 8},
 'resnet': {'init_drop_connect_rate': None, 'resnet_depth': 50},
 'retinanet_head': {'anchors_per_location': None,
                    'num_convs': 4,
                    'num_filters': 256,
                    'use_batch_norm': True,
                    'use_separable_conv': False},
 'retinanet_loss': {'box_loss_weight': 50,
                    'focal_loss_alpha': 0.25,
                    'focal_loss_gamma': 1.5,
                    'huber_loss_delta': 0.1,
                    'normalizer_momentum': 0.0},
 'retinanet_parser': {'aug_policy': '',
                      'aug_rand_hflip': True,
                      'aug_scale_max': 1.0,
                      'aug_scale_min': 1.0,
                      'match_threshold': 0.5,
                      'max_num_instances': 100,
                      'output_size': [640, 640],
                      'regenerate_source_id': False,
                      'skip_crowd_during_training': True,
                      'unmatched_threshold': 0.5},
 'spinenet': {'init_drop_connect_rate': None,
              'model_id': '49',
              'use_native_resize_op': False},
 'spinenet_mbconv': {'init_drop_connect_rate': None,
                     'model_id': '49',
                     'se_ratio': 0.2,
                     'use_native_resize_op': False},
 'tpu_job_name': None,
 'train': {'checkpoint': {'path': 'gs://cloud-tpu-checkpoints/retinanet/resnet50-checkpoint-2018-02-07/model.ckpt-112603',
                          'prefix': 'resnet50/',
                          'skip_variables_regex': ''},
           'frozen_variable_prefix': None,
           'gradient_clip_norm': 0.0,
           'input_partition_dims': None,
           'iterations_per_loop': 100,
           'l2_weight_decay': 0.0001,
           'learning_rate': {'init_learning_rate': 0.08,
                             'learning_rate_levels': [0.008, 0.0008],
                             'learning_rate_steps': [15000, 20000],
                             'type': 'step',
                             'warmup_learning_rate': 0.0067,
                             'warmup_steps': 500},
           'num_cores_per_replica': None,
           'num_shards': 8,
           'optimizer': {'momentum': 0.9, 'type': 'momentum'},
           'pre_parser_dataset': {'dataset_type': 'tfrecord',
                                  'file_pattern': ''},
           'regularization_variable_regex': '.*(kernel|weight):0$',
           'space_to_depth_block_size': 1,
           'total_steps': 22500,
           'train_batch_size': 64,
           'train_dataset_type': 'tfrecord',
           'train_file_pattern': '/home/dannyb/Documents/Research/copy_paste/cocoapi/PythonAPI/data/coco',
           'transpose_input': True},
 'type': 'retinanet',
 'use_tpu': False}
INFO:tensorflow:gpu devices: []
I0322 13:26:39.727839 140697653870976 tpu_executor.py:134] gpu devices: []
2022-03-22 13:26:39.728716: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
W0322 13:26:39.730379 140697653870976 cross_device_ops.py:1386] There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
I0322 13:26:39.737167 140697653870976 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
INFO:tensorflow:Number of devices: 1
I0322 13:26:39.737861 140697653870976 tpu_executor.py:137] Number of devices: 1
INFO:tensorflow:Initializing RunConfig with distribution strategies.
I0322 13:26:39.827292 140697653870976 run_config.py:582] Initializing RunConfig with distribution strategies.
INFO:tensorflow:Not using Distribute Coordinator.
I0322 13:26:39.827548 140697653870976 estimator_training.py:163] Not using Distribute Coordinator.
INFO:tensorflow:Using config: {'_model_dir': '/home/dannyb/Documents/Research/copy_paste/model_output', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7ff6509af290>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
I0322 13:26:39.831076 140697653870976 estimator.py:202] Using config: {'_model_dir': '/home/dannyb/Documents/Research/copy_paste/model_output', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': <tensorflow.python.distribute.mirrored_strategy.MirroredStrategyV1 object at 0x7ff6509af290>, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_distribute_coordinator_mode': None}
WARNING:tensorflow:From /home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py:1244: StrategyBase.configure (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
use `update_config_proto` instead.
W0322 13:26:39.871531 140697653870976 deprecation.py:343] From /home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py:1244: StrategyBase.configure (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
use `update_config_proto` instead.
WARNING:tensorflow:From /home/dannyb/Documents/Research/copy_paste/tpu/models/official/detection/dataloader/input_reader.py:48: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
W0322 13:26:39.898388 140697653870976 deprecation.py:343] From /home/dannyb/Documents/Research/copy_paste/tpu/models/official/detection/dataloader/input_reader.py:48: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
INFO:tensorflow:Converted call: <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=string>,)
    kwargs: {}
I0322 13:26:39.902364 140697653870976 ag_logging.py:136] Converted call: <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=string>,)
    kwargs: {}
INFO:tensorflow:Not allowed: <method-wrapper '__call__' of function object at 0x7ff6443d2e60>: default rule
I0322 13:26:39.903000 140697653870976 ag_logging.py:136] Not allowed: <method-wrapper '__call__' of function object at 0x7ff6443d2e60>: default rule
INFO:tensorflow:Not allowed: <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>: default rule
I0322 13:26:39.903301 140697653870976 ag_logging.py:136] Not allowed: <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>: default rule
INFO:tensorflow:<function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60> is not cached for subkey ConversionOptions[{}]
I0322 13:26:39.903635 140697653870976 ag_logging.py:136] <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Source code of <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>:
lambda file_name: dataset_cls(file_name).prefetch(1),
I0322 13:26:39.912487 140697653870976 ag_logging.py:136] Source code of <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>:
lambda file_name: dataset_cls(file_name).prefetch(1),
INFO:tensorflow:Error transforming entity <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>
Traceback (most recent call last):
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 427, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 269, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 359, in transform_function
    result = self.transform_ast(node, context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 237, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 225, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 700, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 441, in visit
    result = super(Base, self).visit(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 605, in visit_Lambda
    node = self._visit_arg_annotations(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 546, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 551, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'
I0322 13:26:39.914238 140697653870976 ag_logging.py:136] Error transforming entity <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60>
Traceback (most recent call last):
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 427, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 269, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 282, in transform
    return self.transform_function(obj, user_context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 466, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 359, in transform_function
    result = self.transform_ast(node, context)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 237, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 225, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 700, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 441, in visit
    result = super(Base, self).visit(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 605, in visit_Lambda
    node = self._visit_arg_annotations(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 546, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/home/dannyb/miniconda/envs/copypaste/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 551, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'
WARNING:tensorflow:AutoGraph could not transform <function _create_pre_batch_dataset_fn.<locals>.get_dataset.<locals>.<lambda> at 0x7ff6443d2e60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
`

**Comment by tilakrayal** [comment]
@dannybarash7 ,
Can you please take a look at this link [1](https://github.com/tensorflow/tensorflow/issues/53879) and [2](https://github.com/tensorflow/tensorflow/issues/48239) with the similar error.It helps.Thanks!
