### ISSUE TITLE
`tf.image.non_max_suppression_padded` pads indices with a valid index value (0)

### ISSUE THREAD

**Issue by NatanBagrov** [tensorflow/tensorflow#55323]
`tf.image.non_max_suppression` returns a vector of surviving indices of dynamic shape.
To hold static shapes, you use `tf.image.non_max_suppression_padded` which returns a vector of surviving indices (and a scalar indicates the amount).

This vector however, is padded with zeros, to match the input shape (dimension 0).
Since [0] is a valid index in the input, I find it weird and confusing -- does the first zero encountered in the surviving indices is a survivor or just a padding?
For instance, I cannot use `>=0` since that will take all indices, and I cannot use `>0` since it will skip index 0 in case it does survive
```python
return tf.where(tf.expand_dims(indices, axis=1) >= 0, x, tf.zeros_like(x))
```

I understand that this is solvable using the second returned value which indicates the amount of survivors, but I wish the vector itself would be sufficient.

A current workaround is prepending a dummy box with confidence=0 just to make sure that valid indices start from [1].

CoreML handles this issue by padding -1s -- which makes more sense, I guess that might be helpful here as well.

TF 2.8.0

**Comment by tilakrayal** [comment]
@NatanBagrov ,
 In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

**Comment by NatanBagrov** [comment]
Hi @tilakrayal and @fig666, please see the following example code, together with output.
```python
boxes = tf.constant([
        [1., 2., 3., 4.],
        [10., 20., 30., 40.],
        [1., 2., 3., 4.],
    ])
scores = tf.constant([0.6, 0.8, 0.2])
assert len(boxes) == len(scores)

indices, num_survivors = tf.image.non_max_suppression_padded(boxes, scores,
                                                             max_output_size=len(boxes),
                                                             pad_to_max_output_size=True)
print('INDICES:', indices)
print('SURVIVORS:', num_survivors)
```

We expect boxes [1] and [0] to survive, because both with `score>0.5` and there is no overlap between them. When looking at the output, we see this:
```python
INDICES: tf.Tensor([1 0 0], shape=(3,), dtype=int32)
SURVIVORS: tf.Tensor(2, shape=(), dtype=int32)
```
It is not possible to understand from `indices` whether box [0] survived or it is just a padding. Only when looking at `num_survivors` you see that there are 2 survivors.

I can try to PR a fix if you'd like.

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.8, 2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/9e6dd3f8456e63e0245292ec3ad11c8b/55323.ipynb).

**Comment by sachinprasadhs** [comment]
Could you please create a PR and link to this issue. Thanks!
