### ISSUE TITLE
[Accuracy] round issue on tf.nn.conv2d, it does not return the same results for a kernel depth size < 8 vs kernel depth size > 16

### ISSUE THREAD

**Issue by qmller** [tensorflow/tensorflow#55326]
**System information**
- OS Platform and Distribution: Ubuntu 18.04 ($uname -a)
`Linux *** 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- TensorFlow installed from : pypi.org
- TensorFlow version: tested on 2.4.1, 2.6.0, 2.6.2, 2.8.0
  - tf.version.VERSION: "2.6.2"
  - tf.version.GIT_VERSION: 'v2.6.1-9-gc2363d6d025'
  - tf.version.COMPILER_VERSION: '7.3.1 20180303'
- Python version: 3.6.9, 3.8.0, 3.9.11

- CUDA/cuDNN version: no CUDA
- GPU model and memory: no GPU

**Describe the current behavior**
Comparing a 2d-convolution with kernel depth =16 with two 2d-convolution with kernel depth = 8 then concatenated would provide strictly the same results. However, it is not the case. Trace is:
```
>> test with kernel depth = 32 pass
>> test with kernel depth =  8 pass
Traceback (most recent call last):
  File "/***/test_conv2d/tf_conv2d_d8d8_vs_d16.py", line 76, in <module>
    _test(d)
  File "/***/test_conv2d/tf_conv2d_d8d8_vs_d16.py", line 71, in _test
    numpy.testing.assert_allclose(out_1, out_2)
  File "/***/.local/share/virtualenvs/python-3.9-venv/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/***/.local/share/virtualenvs/python-3.9-venv/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2044522 / 4194304 (48.7%)
Max absolute difference: 1.7881393e-07
Max relative difference: 0.10666173
 x: array([[[[ 0.283143,  0.117474,  0.101533, ...,  0.302509, -0.060525,
          -0.123441],
         [ 0.044446, -0.08746 ,  0.078083, ...,  0.173368,  0.143438,...
 y: array([[[[ 0.283143,  0.117474,  0.101533, ...,  0.302509, -0.060525,
          -0.123441],
         [ 0.044446, -0.08746 ,  0.078083, ...,  0.173368,  0.143438,...

Process finished with exit code 1
```

**Describe the expected behavior**
It appears that:
- for a depth size of 8 vs 4-4, results are strictly the same
- for a depth size of 16 vs 8-8, results are not strictly the same (round issue?)
- for a depth size of 32 vs 16-16, results are strictly the same

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): ...
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
tf_conv2d_d8d8_vs_d16.py
```python
import numpy
import tensorflow as tf


class Model_1conv2d(tf.Module):
    def __init__(self, kernel):
        super().__init__()
        self.conv2d_weigths = tf.constant(kernel)

    @tf.function(input_signature=[
        tf.TensorSpec(shape=(1, 512, 512, 3), dtype=tf.float32, name='input')])
    def f(self, input_1):
        conv2d = tf.nn.conv2d(
            input_1,
            self.conv2d_weigths,
            data_format="NHWC",
            padding="SAME",
            dilations=[1, 1],
            strides=[1, 1, 1, 1],
            name="conv2d")
        return conv2d

class Model_2conv2d(tf.Module):
    def __init__(self, k1, k2):
        super().__init__()
        self.conv2d_weigths_1 = tf.constant(k1)
        self.conv2d_weigths_2 = tf.constant(k2)

    @tf.function(input_signature=[
        tf.TensorSpec(shape=(1, 512, 512, 3), dtype=tf.float32, name='input_1_input')
    ])
    def f(self, input_1):
        conv2d_1 = tf.nn.conv2d(
            input_1,
            self.conv2d_weigths_1,
            data_format="NHWC",
            padding="SAME",
            dilations=[1, 1],
            strides=[1, 1, 1, 1],
            name="conv2d1")
        conv2d_2 = tf.nn.conv2d(
            input_1,
            self.conv2d_weigths_2,
            data_format="NHWC",
            padding="SAME",
            dilations=[1, 1],
            strides=[1, 1, 1, 1],
            name="conv2d2")
        concat = tf.concat([
            conv2d_1,
            conv2d_2,],
            axis=3,
            name="output")
        return concat


def _test(depth):

    kernel = (numpy.random.uniform(
        low=-0.05,
        high=0.05,
        size=[3, 3, 3, depth])).astype(dtype=numpy.float16).astype(dtype=numpy.float32)

    x = 2 * numpy.random.rand(1, 512, 512, 3).astype(dtype=numpy.float32)
    input_1_feed = numpy.where(x > 1, x - 0.5, x - 1.5).astype(dtype=numpy.float32)

    model_1 = Model_1conv2d(kernel)
    model_2 = Model_2conv2d(kernel[:, :, :, :(depth // 2)], kernel[:, :, :, (depth // 2):])

    out_1 = model_1.f(input_1_feed,).numpy()
    out_2 = model_2.f(input_1_feed,).numpy()

    numpy.testing.assert_allclose(out_1, out_2)


if __name__ == '__main__':
    for d in [32, 8, 16]:
        _test(d)
        print('>> test with kernel depth = %2s pass' % d)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@qmller ,
Can you please take a look at this SO link [1](https://stackoverflow.com/questions/40205497/why-conv2d-in-tensorflow-gives-an-output-has-the-same-shape-as-input), [2](https://stackoverflow.com/questions/34619177/what-does-tf-nn-conv2d-do-in-tensorflow) and the [link](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d) which delivers the required information.It helps.Thanks!

**Comment by qmller** [comment]
Hi,
I took a look at the links you shared me. However, it does not answer to my request.
Link SO 1 is talking about : why the output dimension does not change if I change the depth of my kernel filter in a conv2d.
Link SO 2 is talking about :  conv2d implementation explanation

And nothing in the help documentation explains why the results are very similar (but different) for 2 x conv2d-concatenated with a kernel filter depth of 8 and a conv2d with a kernel filter depth of 16 (my origin question).

Thanks by adavance for your support and explanation,
Q.

**Comment by qmller** [comment]
ping @tilakrayal

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c50b65c12977f1eabb7dd48ef387954a/55326.ipynb).

**Comment by cantonios** [comment]
We sometimes take different code paths depending on the size of the inputs, so it's not guaranteed you'll get bit-exact results.  For example, the order of additions may change, and the compiler may introduce fused multiply-add instructions, leading to slightly different numerical values.

For input values on the order of magnitude 2.0, and kernel values on the order of magnitude 0.05 (which seems to be the case here), the result of a 3x3x3 convolution will have an error per element distributed ~ N(0, 2.5e-8).  The errors you're seeing seem to be in line with this.  Changing the types to `float64`, the error should be ~ N(0, 4.7e-17).
