### ISSUE TITLE
Cannot predict or serialize model that performs tf.image.resize after decoding image bytearray.

### ISSUE THREAD

**Issue by piEsposito** [tensorflow/tensorflow#55334]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 (Google Colab)
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.12

**Describe the current behavior**
When creating a model that receives a bytearray of an image, decodes it, resizes it and feeds it to the model, it won't serialize nor work with the `predict` method, we can only use `__call__`. 

**Describe the expected behavior**
The model would interpolate the tensor for the size inputed, serialize and save it.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Colab link: https://colab.research.google.com/drive/11VDEMesHjflnG7YytMI-KC9CgbA7hRYa

```python
from PIL import Image

import tensorflow as tf
import numpy as np


class MyModel(tf.keras.models.Model):
    def __init__(self):
        super().__init__()
        self.model = tf.keras.applications.ResNet101(
          include_top=True,
          weights="imagenet",
          input_tensor=None,
          input_shape=None,
          pooling=None,
          classes=1000,
      )

    def call(self, x):
        x = self.preprocess(x)
        return self.model(x)

    def preprocess(self, x):
        x = tf.map_fn(
            self.decode_bytes,
            x,
            dtype=tf.float32
        )
        x = tf.image.resize(x, (224, 224))

        return x

    def decode_bytes(self, x):
        return tf.io.decode_image(x, channels=3, dtype=tf.float32)


def create_input_tensor():
    fname = "/tmp/image.png"

    mock_input = np.random.random((330, 330, 3)).astype(np.float32)
    mock_image = Image.fromarray(mock_input, "RGB")
    mock_image.save(fname)
    b = tf.io.read_file(fname)
    return tf.expand_dims(b, axis=0)


model = MyModel()
in_tensor = create_input_tensor()

model.predict(in_tensor)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/deprecation.py:616: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-efcc1d4139ed>](https://localhost:8080/#) in <module>()
----> 1 model.predict(in_tensor)

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py](https://localhost:8080/#) in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1751, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "my_model" (type MyModel).
    
    in user code:
    
        File "<ipython-input-4-f4258c3336bd>", line 17, in call  *
            x = self.preprocess(x)
        File "<ipython-input-4-f4258c3336bd>", line 26, in preprocess  *
            x = tf.image.resize(x, (224, 224))
    
        ValueError: 'images' contains no shape.
    
    
    Call arguments received:
      • x=tf.Tensor(shape=(None,), dtype=string)
```

**EDIT 1: workaround**

Colab link: https://colab.research.google.com/drive/1_VF5TWbehTECy-33TjdzqQyoOvSOF0bZ?usp=sharing

It seems that a workaround is to save the model with the resize operation but receiving the tensor (not a tf.string tensor with the bytearray), then load it, wrap it into a model that receives the bytearray then save it again. 

When the operation is already serialized and loaded into a model it seems to do no harm. 

Anyway, this is hacky and despite we can make it work like that it is not ideal.

**Comment by piEsposito** [comment]
**EDIT 1: workaround**

Colab link: https://colab.research.google.com/drive/1_VF5TWbehTECy-33TjdzqQyoOvSOF0bZ?usp=sharing

It seems that a workaround is to save the model with the resize operation but receiving the tensor (not a tf.string tensor with the bytearray), then load it, wrap it into a model that receives the bytearray then save it again. 

When the operation is already serialized and loaded into a model it seems to do no harm. 

Anyway, this is hacky and despite we can make it work like that it is not ideal.

**Comment by bhack** [comment]
@piEsposito This is a very well old know issue and `decode_image`, `decode_jpg` and `decode_gif` are "unfied" you need to use `expand_animations = False`.
As you can see, the thread is active since 2017 https://github.com/tensorflow/tensorflow/issues/9356#issuecomment-298469582

**Comment by piEsposito** [comment]
@bhack thanks, that worked!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
