### ISSUE TITLE
Error while creating apk in TensorFlow Android Camera Demo

### ISSUE THREAD

**Issue by Luckygirlllll** [tensorflow/tensorflow#5534]
I followed  instruction for TensorFlow Android Camera Demo, I changed the path for NDK and SDK in WORKSPACE and now when I'm trying to build APK, using command:

`$ bazel build //tensorflow/examples/android:tensorflow_demo`

I got such errors:

![screen shot 2016-11-10 at 8 00 20 am](https://cloud.githubusercontent.com/assets/10096433/20200940/18a39390-a7bd-11e6-939a-7a0f9132be11.png)

If I'm trying to build APK in Android Studio I get such Errors:

```
`Error:/private/var/tmp/_bazel_Iryna/c541cf0f6f349cf0d7c8d3692096116a/external/protobuf/BUILD:73:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_Iryna/c541cf0f6f349cf0d7c8d3692096116a/bazel-sandbox/a0350092-17a0-44fc-a63c-6321732c52f4-2/sandbox.sb /bin/false -MD -MF ... (remaining 27 argument(s) skipped).`
Error:Execution failed for task ':buildNative'.
> Process 'command '/usr/local/bin/bazel'' finished with non-zero exit value 1
```

My question in [StackOverflow.](http://stackoverflow.com/questions/40520927/error-while-trying-to-build-apk-of-tensorflow-android-camera-demo)

**Comment by drpngx** [comment]
What is the bazel version, tensorflow version, OS?

**Comment by andrewharp** [comment]
@Luckygirlllll 
Can you verify that the entries have also been uncommented, the paths are correct, and the specified API levels have been installed?

**Comment by Luckygirlllll** [comment]
tensorflow==0.11.0, Bazel: build label: 0.4.0-homebrew,  Mac OS 10.11.6

**Comment by Luckygirlllll** [comment]
@andrewharp 

You are right, I changed path in WORKSPACE, but didn't uncomment it, now I uncommented it:
![screen shot 2016-11-11 at 4 31 55 am](https://cloud.githubusercontent.com/assets/10096433/20202498/357bd102-a7c8-11e6-9b5e-9b9b1a1bb20a.png)

 and get ERRORS: 

![screen shot 2016-11-11 at 4 34 27 am](https://cloud.githubusercontent.com/assets/10096433/20202502/3db8a700-a7c8-11e6-8afa-f0fe04bc5711.png)

**Comment by andrewharp** [comment]
It looks like you have "smart" quotes around the SDK path, which could be causing problems.

**Comment by Luckygirlllll** [comment]
@andrewharp which kind of quotes should I use there?

**Comment by andrewharp** [comment]
The regular ascii kind you have elsewhere :)

Some text editors, especially on Mac, will "helpfully" replace straight quotes ("") with the curly unicode ones: (“”). Can lead to some pretty devious issues... you might try and find the setting that caused this so it doesn't happen again.

https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html

**Comment by Luckygirlllll** [comment]
@andrewharp 

That was a tricky one! I changed quotes,  now command 

`$ bazel build //tensorflow/examples/android:tensorflow_demo`

works without errors. 

It finished, but I didn't see installed app in my phone. Or it generate apk file in some directory in the  laptop? and then I manually should install it? 

![screen shot 2016-11-11 at 6 14 27 am](https://cloud.githubusercontent.com/assets/10096433/20204278/0c2b8dc4-a7d7-11e6-9902-9895fc69eb11.png)

**Comment by drpngx** [comment]
Woohoo! It looks like, from the output, is that you have a choice of two apks to install:
`bazel-bin/tensorflow/examples/android/tensorflow_demo_unsigned.apk` or the signed one. To install it on your phone, if memory serves, you need to upload it `adb install bazel-bin/tensorflow/examples/android/tensorflow_demo_unsigned.apk`.

**Comment by Luckygirlllll** [comment]
Command not found, if I use command:

`adb install bazel-bin/tensorflow/examples/android/tensorflow_demo_unsigned.apk`

![Uploading Screen Shot 2016-11-11 at 6.34.01 AM.png…]()

**Comment by drpngx** [comment]
It's somewhere in the android sdk, `/Users/Iryna/Library/Android/sdk/`. There may be a binary directory.

You can use `find /Users/Iryna/Library/Android/sdk -type f -name adb` to locate it.

**Comment by Luckygirlllll** [comment]
Okay, found it, now I got:

`Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]`

**Comment by drpngx** [comment]
OK, try the signed one maybe?

Are you in developer mode? On the phone, you should find "About" "version", and click something like 10 times on the version to enable the developer mode.

**Comment by Luckygirlllll** [comment]
Yeah, I'm in developer mode. I tried signed apk, it installed app on my phone. But when I open the app, it crashes immideately.

**Comment by drpngx** [comment]
What does `adb logcat` say?

**Comment by Luckygirlllll** [comment]
ClassifierActivity Exception.
 java.io.FileNotFoundException: imagenet_comp_graph_label_strings.txt 

![screen shot 2016-11-11 at 7 30 31 am](https://cloud.githubusercontent.com/assets/10096433/20205367/da651dbe-a7e0-11e6-80a0-20d45cde980a.png)

**Comment by drpngx** [comment]
If you `unzip -v bazel-bin/tensorflow/examples/android/tensorflow_demo.apk`, do you see the file somewhere there?

**Comment by Luckygirlllll** [comment]
No

![screen shot 2016-11-11 at 7 47 53 am](https://cloud.githubusercontent.com/assets/10096433/20205653/3cdb8986-a7e3-11e6-9ef8-4529a778839c.png)

**Comment by drpngx** [comment]
OK, I'm not sure where it's supposed to come from. Maybe it's from the assets and bazel failed to fetch them.

Can you look at `tensorflow/examples/android/assets`? Is it there?

If you download the inception file:
```
$ curl -L https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip -o /tmp/inception5h.zip
$ unzip -v /tmp/inception5h.zip
```
Is it there?

**Comment by Luckygirlllll** [comment]
There is no directory assets in android directory: 

![screen shot 2016-11-11 at 8 17 01 am](https://cloud.githubusercontent.com/assets/10096433/20206279/e0b3021a-a7e7-11e6-9bbe-7143eeffe65b.png)

If I'm doing this: 

```
$ curl -L https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip -o /tmp/inception5h.zip
$ unzip -v /tmp/inception5h.zip
```

Yeah, in this zip exists file: imagenet_comp_graph_label_strings.txt

**Comment by Luckygirlllll** [comment]
Where should I put this file (imagenet_comp_graph_label_strings.txt) in the project in order not to get Error?

**Comment by drpngx** [comment]
It should have been fetched outomatically. 
Try
```
unzip /tmp/inception5h.zip -d tensorflow/examples/android/assets/
```

Then rebuild, the apk, `unzip -v` to make sure it's there. Then `adb install -r` to re-install on your phone.

**Comment by Luckygirlllll** [comment]
Okay,  so I did it, installed app once again, but still have the same error. 

![screen shot 2016-11-11 at 8 42 46 am](https://cloud.githubusercontent.com/assets/10096433/20206729/1c273fac-a7eb-11e6-91a8-edd4d6c2a713.png)

**Comment by andrewharp** [comment]
@Luckygirlllll You need to rebuild the APK after putting the files in the assets dir.

Also, if you git pull you should be able to get the updated version that auto-fetches the assets so you can skip the manual step altogether.

**Comment by Luckygirlllll** [comment]
@andrewharp Okay, and how to rebuild it? 

If I'm using `bazel build //tensorflow/examples/android:tensorflow_demo`, then I get errors 

![screen shot 2016-11-11 at 8 51 11 am](https://cloud.githubusercontent.com/assets/10096433/20206889/40846f36-a7ec-11e6-8146-2a4e93f59971.png)

**Comment by andrewharp** [comment]
Delete the .DS_store file it's complaining about -- that's an OSX artifact that doesn't need to be there.

**Comment by Luckygirlllll** [comment]
@andrewharp @drpngx Bingo! Finally it works! Thanks a lot!

**Comment by drpngx** [comment]
Woohoo!

**Comment by riyasinha** [comment]
Hi I am trying to build the demo project on my linux pc and am getting this error. I opened the project after from the examples folder from the tensor flow library. 

ERROR: /home/riya/.cache/bazel/_bazel_riya/e4d251743a4c03f32e2f3f7357bd97d7/external/bazel_tools/tools/android/BUILD:288:1: Executing genrule @bazel_tools//tools/android:no_android_sdk_repository_error failed (Exit 1)
This build requires an Android SDK. Please add the android_sdk_repository rule to your WORKSPACE.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 84.049s, Critical Path: 0.35s
FAILED: Build did NOT complete successfully

In my Android project I am getting the same error as this : 
Error:Execution failed for task ':buildNativeBazel'.
> A problem occurred starting process 'command '/usr/local/bin/bazel''

**Comment by njamortel** [comment]
I follow what @Luckygirlllll did, but I still unable to install the apk . help please . 

__Nico-MBP:tensorflow nicomortel$ adb install -r bazel-bin/tensorflow/examples/android/tensorflow_demo.apk
bazel-bin/tensorflow/examples/android/tenso...shed. 51.5 MB/s (175398653 bytes in 3.245s)
        pkg: /data/local/tmp/tensorflow_demo.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]__

**Comment by njamortel** [comment]
what this conflict means?

_CONFLICT: asset:tensorflow_inception_graph.pb is provided with ambiguous priority from:
        tensorflow/examples/android/assets/tensorflow_inception_graph.pb
        external/inception_v1/tensorflow_inception_graph.pb

CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
        external/speech_commands/WORKSPACE
        external/mobile_ssd/WORKSPACE

CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
        external/mobile_ssd/WORKSPACE
        external/inception_v1/WORKSPACE

CONFLICT: asset:WORKSPACE is provided with ambiguous priority from:
        external/stylize/WORKSPACE
        external/speech_commands/WORKSPACE_
