### ISSUE TITLE
Autovectorization fail with tf.vectorized_map and range

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#55340]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
Nightly
- Python version:
Colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
def outer_product(a):
  for i in tf.range(10):
    pass
  return tf.tensordot(a, a, 0)

@tf.function
def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

```
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```
**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Just to expose a few reformulations it seems that we have some side effect with `tf.vectorized_map` in an autovectorizzation region.

This is working correctly instead:
```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
def outer_product(a):
  for i in range(10):
    pass
  return tf.tensordot(a, a, 0)

@tf.function
def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

This is failing
```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
def outer_product(a):
  for i in range(tf.constant(10)):
    pass
  return tf.tensordot(a, a, 0)

@tf.function
def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

```python
    TypeError: 'Tensor' object cannot be interpreted as an integer
```

This is failing:

```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
def outer_product(a):
  for i in tf.range(tf.constant(10)):
    pass
  return tf.tensordot(a, a, 0)

@tf.function
def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```
```python
    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
````

Moving Autovectorizzation to execlute `tf.vectorized_map`:

This is working
```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
@tf.function
def outer_product(a):
  for i in tf.range(tf.constant(10)):
    pass
  return tf.tensordot(a, a, 0)

def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

This is working:
```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
@tf.function
def outer_product(a):
  for i in range(tf.constant(10)):
    pass
  return tf.tensordot(a, a, 0)

def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

This is working:

```python
import tensorflow as tf
tf.autograph.set_verbosity(10)
@tf.function
def outer_product(a):
  for i in range(10):
    pass
  return tf.tensordot(a, a, 0)

def vectorized(a):
  return tf.vectorized_map(outer_product, a)  

batch_size = 100
a = tf.ones((batch_size, 32, 32))
c = vectorized(a)
assert c.shape == (batch_size, 32, 32, 32, 32)
```

/cc @mdanatg

**Comment by bhack** [comment]
P.s. just a note the `tf.vectorized_map` example was derived from official example in docstring:

https://www.tensorflow.org/api_docs/python/tf/vectorized_map#examples

**Comment by sushreebarsa** [comment]
@bhack Can we close this issue, since associated PR got merged. Thanks!
