### ISSUE TITLE
How to convert Keras LSTM model into tf.nn.rnn_cell.LSTMCell model

### ISSUE THREAD

**Issue by Ironbrotherstyle** [tensorflow/tensorflow#55345]
I have trained a LSTM model on pytorch, and converted it into Keras lstm model with `set_weights` method. The performance looks almost the same. However, I need to convert the model into lstm model with older tensorflow version (V1.xx), by using `tf.nn.rnn_cell.LSTMCell` method. What confused me was that I did not find any method that can load lstm weights from numpy like arrays. The only method I find is loading saved checkpoints, but not suitable for me.
Any suggestion for me? Thanks.

**Comment by chunduriv** [comment]
@Ironbrotherstyle,

This is not a bug or feature request, for any queries you may open this issue in tf discussion [forum](https://discuss.tensorflow.org/) as there is a larger community there. Thanks!
