### ISSUE TITLE
@tensorflow/tfjs: Unable to load model

### ISSUE THREAD

**Issue by mcmanussean** [tensorflow/tensorflow#55357]
Using Webpack to build a node app with @tensorflow/tfjs included, when using tf.loadLayersModel() the following error is received:

```
webpack:///./node_modules/@tensorflow/tfjs-core/dist/platforms/platform_node.js?:59
        return systemFetch(path, requestInits);
               ^

TypeError: systemFetch is not a function
```

When looking into the node_module, it does appear that this is a bug in the tensorflowjs core code. This happens when trying to load a model via an http request or a direct file (since this is a node application)

**Comment by sushreebarsa** [comment]
@mcmanussean Could you please post this issue in [tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues) repo to get the right help there?
Thanks!

**Comment by sushreebarsa** [comment]
@mcmanussean  Could you please confirm if you have posted this issue in tfjs repo and please refer to [this](https://github.com/tensorflow/tfjs/issues/3883) thread with similar error?
Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity.Please feel free to reopen the issue if you still have a concern. Thanks!
