### ISSUE TITLE
I am trying to build tensorflow from source code and error happed

### ISSUE THREAD

**Issue by lixinyutfd** [tensorflow/tensorflow#5536]
after :bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
Things happend like this:

WARNING: /home/lixinyu/tensorflow/tensorflow/tensorflow.bzl:477:26: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/lixinyu/tensorflow/tensorflow/tensorflow.bzl:490:24: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/lixinyu/.cache/bazel/_bazel_lixinyu/824013fbb9b22e08d948a2226491e595/external/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/lixinyu/.cache/bazel/_bazel_lixinyu/824013fbb9b22e08d948a2226491e595/external/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
ERROR: /home/lixinyu/tensorflow/tensorflow/python/BUILD:1044:1: in cc_library rule //tensorflow/python:tf_session_helper: non-test target '//tensorflow/python:tf_session_helper' depends on testonly target '//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 0.209s

I googled this but there is not a trustworthy answer to my issue

**Comment by sono-bfio** [comment]
Running to the same thing error:
ERROR: /home/ubuntu/tensorflow/tensorflow/python/BUILD:1728:1: in cc_library rule //tensorflow/python:tf_session_helper: non-test target '//tensorflow/python:tf_session_helper' depends on testonly target '//tensorflow/python:construction_fails_op' and doesn't have testonly attribute set.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 2.693s

Ubuntu 14.04
Using: tf 11 (tagged commit)
Bazel Info
```
bazel version
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254
```

**Comment by sono-bfio** [comment]
FYI - I just pulled master down and was able to build.

**Comment by aselle** [comment]
@lixinyutfd  we can't really help you if you don't specify what operating system and version you are trying to build. Thanks @sono-bfio.

**Comment by lixinyutfd** [comment]
@aselle I am using ubantu 14.04 and 0-11-0 version.

**Comment by gunan** [comment]
@sono-bfio @lixinyutfd which bazel version are you using?
I think this can be caused by a bazel update.
There has been a non backwards compatible change in bazel.
Could you try with bazel 0.3.2 ?

**Comment by lixinyutfd** [comment]
@gunan  I am using 0.40 for bazel.

**Comment by gunan** [comment]
Then I am pretty certain it is with the bazel version.
Could you try with bazel 0.3.2?

**Comment by lixinyutfd** [comment]
I did successfully just now .
What I did is just pull the new master of tensorflow and it worked.
I dont think this is caused by bazel @gunan 
Athough there are lots of info and warning during compiling. Is such warning normal ones or shows something wrong?

**Comment by gunan** [comment]
@lixinyutfd It is caused by an update in bazel.
They used to not care about "testonly" attributes in BUILD files.
With 0.4, they now do. Due to them not caring about testonly attributes before, our code evolved in such a way that we imported our test helper libraries into our pip package, which is obviously not test only.
On master, we did make the fixes and removed most testonly libs from pip package, so it builds successfully with the latest bazel version. In older releases, we did not make that fix, so they do not build with bazel 0.4.

The compilation warnings are expected. INFO and WARNING messages are mostly benign.

**Comment by sono-bfio** [comment]
Will try with bazel 0.3.2 and let you know how it goes.

**Comment by jcarloseugenio** [comment]
Hi everyone,
I am looking for some help regarding the same error message. I haven't found the way to downgrade bazel to the version 0.3.2,  I am doing :
root@tensorflow:~# sudo apt-get install bazel=0.3.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '0.3.2' for 'bazel' was not found

Below is my system configuration:

Tensorflow version:
>>> tf.__version__
'1.0.0'

ARNING: /root/.cache/bazel/_bazel_root/ff219f214582e62419b9171e5b5ba9a0/external/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /root/.cache/bazel/_bazel_root/ff219f214582e62419b9171e5b5ba9a0/external/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/local/lib/python2.7/dist-packages

Ubuntu version:
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial


Bazel version:
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 18:47:11 2016 (1481136431)
Build timestamp: 1481136431
Build timestamp as int: 1481136431

Thanks

**Comment by gunan** [comment]
I realized I might be looking at the wrong error message above.
If you are trying to build 1.0 branch, any bazel version above 0.4.2 should work.
If you are trying to build an old branch, you can download an old version of bazel and install manually using the packages found here:
https://github.com/bazelbuild/bazel/releases
