### ISSUE TITLE
benchmark_model: Could not create Hexagon delegate: platform may not support delegate or required libraries are missing

### ISSUE THREAD

**Issue by tonysung** [tensorflow/tensorflow#55364]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung S21
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly

**Describe the current behavior**
* Follow instructions in https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary and https://www.tensorflow.org/lite/performance/hexagon_delegate to run TFLite `benchmark_model` with `use_hexagon=true`.
* `adb push` contents of these to `/data/local/tmp`:
  * [android_aarch64_benchmark_model](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model)
  * [libhexagon_interface.so ](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_libhexagon_interface.so)
  * [hexagon_nn_skel v1.20.0.1](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.1.run)
  * [mobilenet_v2_1.0_224_quant](https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224_quant.tgz)
* Verify with `adb shell ls /data/local/tmp`: 
  ```
  android_aarch64_benchmark_model
  libhexagon_interface.so
  libhexagon_nn_skel.so
  libhexagon_nn_skel_v65.so
  libhexagon_nn_skel_v66.so
  mobilenet_v2_1.0_224.tflite
  mobilenet_v2_1.0_224_quant.tflite
  ```
* Run `adb shell /data/local/tmp/android_aarch64_benchmark_model --graph=/data/local/tmp/mobilenet_v2_1.0_224_quant.tflite --use_hexagon=true --hexagon_lib_path=/data/local/tmp`
* Hexagon delegate fail to create:
  ```
  STARTING!
  Log parameter values verbosely: [0]
  Graph: [/data/local/tmp/mobilenet_v2_1.0_224_quant.tflite]
  Use Hexagon: [1]
  Hexagon lib path: [/data/local/tmp]
  Loaded model /data/local/tmp/mobilenet_v2_1.0_224_quant.tflite
  INFO: Initialized TensorFlow Lite runtime.
  WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
  INFO: Hexagon Delegate is not supported.
  
  loaded libcdsprpc.so
  Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
  The input model file size (MB): 3.57776
  Initialized session in 51.739ms.
  Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
  count=66 first=23605 curr=6778 min=6765 max=23605 avg=7583.89 std=2197
  
  Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
  count=82 first=6870 curr=850063 min=6765 max=850063 avg=17097.5 std=92551
  
  Inference timings in us: Init: 51739, First inference: 23605, Warmup (avg): 7583.89, Inference (avg): 17097.5
  Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
  Memory footprint delta from the start of the tool (MB): init=4.73828 overall=8.75
  ``` 

**Describe the expected behavior**

`benchmark_model` runs with hexagon delegate enabled.

**Comment by mohantym** [comment]
Hi @tonysung ! I see you have pushed **multiple versions of libhexagon_nn_skel.so** . Can you let us know the results with only one libhexagon_nn_skel.so ? Thanks!

**Comment by tonysung** [comment]
Tried keeping only each one of `libhexagon_nn_skel.so`, `libhexagon_nn_skel_v65.so`, `libhexagon_nn_skel_v66.so`, both with their names unchanged, and with them all renamed to `libhexagon_nn_skel.so` (total 6 combinations). Same result:

```
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.

loaded libcdsprpc.so
Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
```

**Comment by freedomtan** [comment]
as you can see from the [hexagon delegate page](https://www.tensorflow.org/lite/performance/hexagon_delegate), Samsung S21 (supposedly Snapdragon 888, which has Hexagon 780) is not supported.

**Comment by sachinprasadhs** [comment]
Could you please follow the steps mentioned [here](https://github.com/tensorflow/tensorflow/issues/45014#issuecomment-731474874) and let us know if this helps to solve your problem. Thanks!

**Comment by tonysung** [comment]
Hi @sachinprasadhs If this has anything to do with the `nativeLibraryDir` as mentioned [here](https://github.com/tensorflow/tensorflow/issues/45014#issuecomment-731474874), then I'm afraid it is a bug in `benchmark_model`, because it should load the library NOT from `nativeLibraryDir` but from the path specified in `--hexagon_lib_path`:

```
$ adb shell /data/local/tmp/android_aarch64_benchmark_model --help
...
--hexagon_lib_path=/data/local/tmp string optional The library path for the underlying Hexagon libraries.
...
```

And here's the original command when this bug is reproduced:

```
adb shell /data/local/tmp/android_aarch64_benchmark_model \
--graph=/data/local/tmp/mobilenet_v2_1.0_224_quant.tflite \
--use_hexagon=true \
--hexagon_lib_path=/data/local/tmp
```

And the content of `/data/local/tmp`:

```
$ adb shell ls /data/local/tmp:
android_aarch64_benchmark_model
libhexagon_interface.so
libhexagon_nn_skel.so
```

**Comment by freedomtan** [comment]
> I believe that's not the cause, as the page said, "Currently the following Hexagon architecture are supported, **including but not limited to** ..."

Please check https://github.com/tensorflow/tensorflow/issues/47246.

**Comment by tonysung** [comment]
I tried the same on both Samsung Galaxy S8 (Snapdragon 835) and Google Pixel 3 (Snapdragon 845), and both failed.

Both listed to be supported according to https://www.tensorflow.org/lite/performance/hexagon_delegate

The error message is a bit different though.

Samsung Galaxy S21:

> WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.

Samsung Galaxy S8 & Google Pixel 3:

> ERROR: Failed to load libhexagon_interface.so, Error: dlopen failed: library "libhexagon_interface.so" not found

```
adb shell ls -l /data/local/tmp/android-benchmark-tools/aarch64
total 16776
-rwxrw-rw- 1 shell shell 6707096 2022-04-01 16:01 benchmark_model
-rwxrw-rw- 1 shell shell 6727576 2022-04-01 16:09 benchmark_model_performance_options
-rwxrw-rw- 1 shell shell  249008 2022-04-01 16:01 libhexagon_interface.so
-rwxrwxrwx 1 shell shell 1148720 2022-04-12 22:31 libhexagon_nn_skel.so
-rwxrwxrwx 1 shell shell 1165168 2022-04-12 22:31 libhexagon_nn_skel_v65.so
-rwxrwxrwx 1 shell shell 1161072 2022-04-12 22:31 libhexagon_nn_skel_v66.so
```

Full error log:

```
STARTING!
Log parameter values verbosely: [0]
Graph: [/data/local/tmp/android-benchmark-tools/tflite/mobilenet_v2_1.0_224_quant.tflite]
Use Hexagon: [1]
Hexagon lib path: [/data/local/tmp/android-benchmark-tools/aarch64]
Loaded model /data/local/tmp/android-benchmark-tools/tflite/mobilenet_v2_1.0_224_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
ERROR: Failed to load libhexagon_interface.so, Error: dlopen failed: library "libhexagon_interface.so" not found
INFO: Hexagon Delegate is not supported.

Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
The input model file size (MB): 3.57776
Initialized session in 2.229ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=15 first=38031 curr=34185 min=34119 max=38031 avg=34471.7 std=954

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=34574 curr=34198 min=34125 max=35839 avg=34541.4 std=450

Inference timings in us: Init: 2229, First inference: 38031, Warmup (avg): 34471.7, Inference (avg): 34541.4
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=1.24219 overall=6.80078
```

**Comment by karimnosseir** [comment]
@tonysung as [freedomtan](https://github.com/freedomtan) mentioned new chipset doesn't use the Hexagon NN, so we can't support it currently.

For the other supported use cases of Samsung S8
You will need to make libhexagon_interface.so in the LD library path so it can be loaded
Example
```
LD_LIBRARY_PATH=/data/local/tmp/android-benchmark-tools:${LD_LIBRARY_PATH}
```

See example [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/builders/tests/run_tests.sh#L45) when it is done for testing.
For benchmark tool we set [rpath](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/BUILD#L37) to /data/lcoal/tmp/ by default to ease running. See [instructions](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)

**Comment by karimnosseir** [comment]
One more thing for pixel phones DSP access is disabled so it will not work.
If you have the Pixel phone rooted you can run these commands first
```
adb root
adb shell setenforce 0
```

**Comment by karimnosseir** [comment]
Documentation updated.

Thanks a lot

**Comment by aseok** [comment]
@tonysung would you please provide the complete instruction to make dsp run? there's no android-benchmark-tools in tmp directory!
