### ISSUE TITLE
Failed to build libtensorflow (v2.8.0 + bazel 4.2.1) from source on Apple M1 

### ISSUE THREAD

**Issue by lnshi** [tensorflow/tensorflow#55369]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
`Apple M1`

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
`Source: v2.8.0 branch`

- TensorFlow version:
- Python version:
`3.9.9`

- Installed using virtualenv? pip? conda?
- Bazel version (if compiling from source):
`4.2.1`

- GCC/Compiler version (if compiling from source):
```
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
```
bazel build --jobs 10 --config opt --cpu=darwin_arm64 --host_cpu=darwin_arm64 //tensorflow/tools/lib_package:libtensorflow

ERROR: /private/var/tmp/_bazel_leonard/dbb496db86443ebdf640b47e39125a9a/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_arm64'
ERROR: Analysis of target '//tensorflow/tools/lib_package:libtensorflow' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 131.509s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (126 packages loaded, 2996 targets configured)
    Fetching @icu; fetching 6s
    Fetching ...6db86443ebdf640b47e39125a9a/external/icu; Extracting /private/var/tmp/_bazel_leonard/dbb496db86443ebdf640b47e39125a9a/external/icu/temp15584703296969244655/release-69-1.zip
    Fetching @com_google_absl; Restarting.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
./configure

bazel build --jobs 10 --config opt --cpu=darwin_arm64 --host_cpu=darwin_arm64 //tensorflow/tools/lib_package:libtensorflow
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@lnshi,
Make sure you have installed Xcode app correctly from app store.

Try workaround mention on similar issue thread [#13514](https://github.com/bazelbuild/bazel/issues/13514#issuecomment-847917936)

**Comment by lnshi** [comment]
@gadagashwini thanks for the prompt reply.

Actually what is the difference between the below two commands:
```
bazel build --jobs=10 --compilation_mode=opt --copt=-march=native //tensorflow/tools/lib_package:libtensorflow
```

and
```
bazel build --jobs 10 --config opt --cpu=darwin_arm64 --host_cpu=darwin_arm64 //tensorflow/tools/lib_package:libtensorflow
```

The first one all is ok, but the latter one i run into this reported issue.

**Comment by gadagashwini** [comment]
@lnshi,
`bazel build --jobs=10 --compilation_mode=opt --copt=-march=native //tensorflow/tools/lib_package:libtensorflow`

`--copt `or `--compilation_mode opt` is for passing args to to the compiler. This flag is for Bazel to build with optimization settings enabled with no debug information. 

`bazel build --jobs 10 --config opt --cpu=darwin_arm64 --host_cpu=darwin_arm64 //tensorflow/tools/lib_package:libtensorflow`

`--config opt` is for selecting a configuration. You can have a .bazelrc which defines default options. Some of them are not always active, but some only if you activate them by the --config=configname command line option. There are some [preconfigured build configs](https://www.tensorflow.org/install/source#preconfigured_configurations) available that can be added to the bazel build command, for example `--config=dbg,` `--config=mkl`. 

Here you are configuring with `darwin_arm64`, you can configure this with bazel build as mentioned [here](https://github.com/bazelbuild/bazel/issues/13514#issuecomment-847917936)

**Comment by gadagashwini** [comment]
@lnshi, Seems like issue is with Bazel.
Build Tensorflow with Bazel version 4.2.2 or 5.0.0.
