### ISSUE TITLE
Wrong definition of arg fixed_length in api_docs/python/tf/raw_ops/DecodePaddedRaw

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#55372]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/raw_ops/DecodePaddedRaw

## Description of issue (what needs changing):

Wrong type decription of `fixed_length` .

### Clear description

`fixed_length` should be a positive int, but the doc has following description:
````
A Tensor of type int32. Length in bytes for each element of the decoded output. Must be a multiple of the size of the output type.
````

### Parameters defined

`fixed_length` should be a positive int.

### Submit a pull request?

no

**Comment by sushreebarsa** [comment]
@shijy16 
Could you please mention the exact changes that are needed for the documentation and please specify some use cases ?Thanks!

**Comment by shijy16** [comment]
@sushreebarsa 
The  argument `fixed_length`  is defined as a Tensor in the doc:
````
A Tensor of type int32. Length in bytes for each element of the decoded output. Must be a multiple of the size of the output type.
````
According to the execute result  of following code, `fixed_length` should be a positive int:

````python
 import tensorflow as tf
 
input_bytes = ['123', '1234', '12345']
fixed_length = [3, 3, 3]
out_type = tf.int8
print(tf.raw_ops.DecodePaddedRaw(input_bytes=input_bytes, fixed_length=fixed_length, out_type=out_type))
````
Execute Result:
````
python test.py
2022-03-29 08:52:53.152603: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-29 08:52:56.352918: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14635 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:2f:00.0, compute capability: 7.0
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(tf.raw_ops.DecodePaddedRaw(input_bytes=input_bytes, fixed_length=fixed_length, out_type=out_type))
  File "/home/sjy/.conda/envs/tf_nightly/lib/python3.8/site-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper
    return f(**kwargs)
  File "/home/sjy/.conda/envs/tf_nightly/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 343, in decode_padded_raw
    return decode_padded_raw_eager_fallback(
  File "/home/sjy/.conda/envs/tf_nightly/lib/python3.8/site-packages/tensorflow/python/ops/gen_parsing_ops.py", line 379, in decode_padded_raw_eager_fallback
    _result = _execute.execute(b"DecodePaddedRaw", 1, inputs=_inputs_flat,
  File "/home/sjy/.conda/envs/tf_nightly/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__DecodePaddedRaw_device_/job:localhost/replica:0/task:0/device:CPU:0}} k must be scalar, got shape [3] [Op:DecodePaddedRaw]
````
Obviously, the argument `fixed_length` should be a scalar instead of a Tensor. After some research on the source code of DecodePaddedRawOp, I think it should be defined as:
````
A positive int. Length in bytes for each element of the decoded output. Must be a multiple of the size of the output type.
````

**Comment by Yashashree304** [comment]
@shijy16 in the code you sent above you tried to pass a list for fixed_length however the documentation mentions to pass a tensor of type int32. The following code works.

`import tensorflow as tf
 
input_bytes = ['123', '1234', '12345']
fixed_length = tf.constant(3)
out_type = tf.int8
print(tf.raw_ops.DecodePaddedRaw(input_bytes=input_bytes, fixed_length=fixed_length, `out_type=out_type))`

**Comment by shijy16** [comment]
@Yashashree304  You are right, thank you.
I thought a tensor was meant to be a multi-dimensional arrays. After reading the definition of tensor, I just realize it can be a scalar. And in the definition of `DecaodePaddedRaw`, it is a scalar obviously.
Sorry for bothering. XD

**Comment by sushreebarsa** [comment]
@Yashashree304 Thank you for your response!
@shijy16  The description in the [documentation](https://www.tensorflow.org/api_docs/python/tf/raw_ops/DecodePaddedRaw) for `fixed_length` is correct as it says to pass a tensor of type int32 and the example you have shared is passing a list for fixed_length.
Could you please move this issue to closed status if it is resolved for you?
Thanks!

**Comment by shijy16** [comment]
OK, I'll close this issue.
Thank you all!
