### ISSUE TITLE
tf.load_op_library doesn't load .so file and throws file not found error although the file exists

### ISSUE THREAD

**Issue by nirnayr** [tensorflow/tensorflow#55375]
```
**System information**
== check python ===================================================
python version: 3.7.7
python branch: 
python build version: ('default', 'Jan 13 2021 07:47:31')
python compiler version: GCC 7.5.0
python implementation: CPython


== check os platform ===============================================
os: Linux
os kernel version: 69-18.04.1-Ubuntu SMP Wed Feb 9 15:36:54 UTC 2022
os release version: 5.4.0-1066-aws
os platform: Linux-5.4.0-1066-aws-x86_64-with-debian-buster-sid
linux distribution: ('debian', 'buster/sid', '')
linux os distribution: ('debian', 'buster/sid', '')
architecture: ('64bit', '')
machine: x86_64


== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                            1.21.5
protobuf                         3.14.0
tensorflow                       2.8.0
tensorflow-estimator             1.14.0
tensorflow-hub                   0.11.0
tensorflow-io-gcs-filesystem     0.24.0
wsproto                          1.0.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.8.0
tf.version.GIT_VERSION = v2.8.0-rc1-32-g3f878cff5b6
tf.version.COMPILER_VERSION = 7.3.1 20180303
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary):binary

== env ==========================================================
LD_LIBRARY_PATH /usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib:/opt/amazon/efa/lib:/usr/local/mpi/lib:/opt/amazon/openmpi/lib:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib:/opt/amazon/efa/lib:/usr/local/mpi/lib:/opt/amazon/openmpi/lib:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.


== cuda libs  ===================================================
/usr/local/cuda-9.0/lib64/libcudart_static.a
/usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
/usr/local/cuda-9.0/doc/man/man7/libcudart.7
/usr/local/cuda-9.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so.10.2.89
/usr/local/cuda-10.2/doc/man/man7/libcudart.7
/usr/local/cuda-10.2/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.243
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart_static.a
/usr/local/cuda-10.1/doc/man/man7/libcudart.7
/usr/local/cuda-10.1/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.2/lib64/libcudart_static.a
/usr/local/cuda-9.2/lib64/libcudart.so.9.2.148
/usr/local/cuda-9.2/doc/man/man7/libcudart.7
/usr/local/cuda-9.2/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
/usr/local/cuda-10.0/lib64/libcudart_static.a
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.8.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/ubuntu/venvpipe1v1/lib/python3.7/site-packages
Required-by: spacy-universal-sentence-encoder

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 7, 'final', 0)

== bazel version  ===============================================
```
**Describe the current behavior**

When the code below is executed
```
print(config.COREF_KERNELS_SO_FILE_PATH.is_file())
coref_op_library = tf.load_op_library(str(config.COREF_KERNELS_SO_FILE_PATH))
```
The first line prints `True` which means that the file exists. But the second line throws the following error.

`
 File "/home/ubuntu/venvpipe1v1/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory
`

**Describe the expected behavior**

The .so file should load

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**

```
import tensorflow as tf
coref_op_library = tf.load_op_librarypath to .so file')

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
2022-03-24 17:39:30.761737: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-24 17:39:30.761779: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

**Comment by tilakrayal** [comment]
@nirnayr ,
Can you please take a look at this [issue1](https://github.com/tensorflow/tensorflow/issues/30488), [2](https://github.com/tensorflow/tensorflow/issues/45930) and also TensorFlow release is compatible with a certain version, for more information please take a look at the tested build [configurations](https://www.tensorflow.org/install/source#gpu).

**Comment by nirnayroy** [comment]
Tried linking libtensorflow_framework.so and libtensorflow_framework.so.2 using ln as suggested by [https://stackoverflow.com/questions/56888781/tensorflow-notfounderror-libtensorflow-framework-so-cannot-open-shared-file-or?noredirect=1&lq=1](https://www.stackoverflow.com/)

I have tried appending LD_LIBRARY_PATH with the libtensorflow_framework.so file as suggested by this thread [https://github.com/tensorflow/tensorflow/issues/30488](https://www.stackoverflow.com/)

I have tried downgrading to tensorflow 1.14, with Python 3.7. As that was the latest compatible according to [https://www.tensorflow.org/install/source#gpu](https://www.stackoverflow.com/)

**Comment by nirnayr** [comment]
Tried linking libtensorflow_framework.so and libtensorflow_framework.so.2 using ln as suggested by [https://stackoverflow.com/questions/56888781/tensorflow-notfounderror-libtensorflow-framework-so-cannot-open-shared-file-or?noredirect=1&lq=1](https://www.stackoverflow.com/)

I have tried appending LD_LIBRARY_PATH with the libtensorflow_framework.so file as suggested by this thread [https://github.com/tensorflow/tensorflow/issues/30488](https://www.stackoverflow.com/)

I have tried downgrading to tensorflow 1.14, with Python 3.7. As that was the latest compatible according to [https://www.tensorflow.org/install/source#gpu](https://www.stackoverflow.com/)

**Comment by gadagashwini** [comment]
@nirnayr, 
`tf.sysconfig.get_link_flags()`. returns ```
['-L/usr/local/lib/python3.7/dist-packages/tensorflow',
 '-l:libtensorflow_framework.so.2'] ```

 Here, `library directory` is  `-L` and `library` is `-l`. Now replace the `-L` and `-l`  with `library_dirs` and `libraries `arguments to your Extension object in `setup.py`.

Finally, set your `LD_LIBRARY_PATH` environment variable to point to the directory with the `libtensorflow_framework.so` library is located.
