### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by klorinczi** [tensorflow/tensorflow#55377]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source 
- TensorFlow version: v2.4.4
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source): 3.1.0 (bazel-3.1.0-linux-x86_64)
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**

I installed moodlemlbackend v3.0.2 (I use Moodle v3.9).
`pip3 install moodlemlbackend==3.0.2`

Now I try to meet the requirements:
https://github.com/moodlehq/moodle-mlbackend-python/blob/3.0.2/requirements.txt
Requires:
tensorflow>=2.4.2,<2.5
numpy>=1.19.2,<1.20

I had to recompile tensorflow v2.4.4 with noavx option.
Used options: -march=nehalem -msse4.1 -msse4.2 -mpclmul -mpopcnt -maes -mno-avx -mno-avx2

`pip3 install /git/tensorflow/tensorflow_output/tensorflow-2.4.4-cp37-cp37m-linux_x86_64.whl`

Also installed the required numpy v1.19.5:
`pip3 install numpy==1.19.5`

Now I get the following error:

```
python3 -c 'import tensorflow'
# RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
# RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
# ImportError: numpy.core._multiarray_umath failed to import
# ImportError: numpy.core.umath failed to import
# 2022-03-25 17:43:52.642579: F tensorflow/python/lib/core/bfloat16.cc:714] Check failed: PyBfloat16_Type.tp_base != nullptr
# Aborted
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@klorinczi,

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

This looks like numpy version 1.19.5 and TensorFlow 2.4 not playing well together. 

Use `numpy ~= 1.19.2`

**Comment by klorinczi** [comment]
It seems, the problem was with sudo.
I have different module versions installed with sudo and with user install.

With sudo:
```
sudo pip3 list | grep -e tensorflow -e numpy
numpy                        1.21.5
tensorflow-estimator         2.4.0
tensorflow-io-gcs-filesystem 0.24.0
```

With user installed (without sudo):
```
pip3 list | grep -e tensorflow -e numpy
numpy                        1.19.5
tensorflow                   2.4.4
tensorflow-estimator         2.4.0
tensorflow-io-gcs-filesystem 0.24.0
```

Because I compiled with sudo:
`date && sudo bazel build --disk_cache ./cache //tensorflow/tools/pip_package:build_pip_package && date`

I compile again without sudo and works fine:
`date && bazel build --disk_cache ./cache //tensorflow/tools/pip_package:build_pip_package && date`

No error executing:
`python3 -c 'import tensorflow'`

```
python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
2022-03-28 11:32:37.148566: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.Tensor(-1334.6855, shape=(), dtype=float32)

```

**Comment by gadagashwini** [comment]
@klorinczi,
Glad that its resolved. 
Seems like this is not related to sudo. Its regarding the numpy version configured with sudo and pip3 binary package. 
Closing as issue is resolved. Please feel free to reopen if still faces an error. Thanks!

**Comment by klorinczi** [comment]
Solution to error: "RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd"

moodlemlbackend v3.0.2 is not compatible with Moodle v3.9.x.
Moodle v3.9.x requires moodlemlbackend v2.6.5
Also as described on:
https://docs.moodle.org/39/en/Analytics_settings#Versions
`sudo -H python3 -m pip3 install "moodlemlbackend==2.6.5"`

Solution steps:
```
# uninstall in case we have had version installed with sudo
sudo pip3 uninstall moodlemlbackend
sudo pip3 uninstall tensorflow
sudo pip3 uninstall numpy

# install for current user
pip3 install moodlemlbackend==2.6.5

# uninstall tensorflow with avx requirement
pip3 uninstall tensorflow

# install my compiled tensorflow v2.4.4 without avx support 
# used options: -march=nehalem -msse4.1 -msse4.2 -mpclmul -mpopcnt -maes -mno-avx -mno-avx2)
pip3 install /git/tensorflow/tensorflow_output/tensorflow-2.4.4-cp37-cp37m-linux_x86_64.whl

python3 -c 'import tensorflow'
# Empty, so import was successful

# install with sudo -H 
sudo -H pip3 install moodlemlbackend==2.6.5

# uninstall original tensorflow 
sudo -H pip3 uninstall tensorflow

# install my compiled tensorflow v2.4.4 without avx support 
# used options: -march=nehalem -msse4.1 -msse4.2 -mpclmul -mpopcnt -maes -mno-avx -mno-avx2)
sudo -H pip3 install /git/tensorflow/tensorflow_output/tensorflow-2.4.4-cp37-cp37m-linux_x86_64.whl

sudo -H python3 -c 'import tensorflow'
# SUCCESS
```
