### ISSUE TITLE
TensorflowLite Undefined symbol: _TfLiteTensorCopy

### ISSUE THREAD

**Issue by luckysmg** [tensorflow/tensorflow#55389]
**System information**
Xcode13.3, complie app for arm64 iPhone

The step I following is here:
https://www.tensorflow.org/lite/guide/ops_select#ios

Demo code is here:
[iOSDemo 2.zip](https://github.com/tensorflow/tensorflow/files/8356734/iOSDemo.2.zip)

**Step to reproduce issue**
1. Download the zip,and `cd` to the project root folder
2. Run `pod update` 
3. Compile project.
4. Get the error and compile failed.

<img width="352" alt="QQ20220327-110056@2x" src="https://user-images.githubusercontent.com/49340347/160264810-524cfabc-5cfd-48bd-a93c-9ff9966374a6.png">

**Comment by mohantym** [comment]
Hi @luckysmg ! Have you force loaded the Select TF ops to your app after the "pod install" step?

**Comment by luckysmg** [comment]
Yes

**Comment by luckysmg** [comment]
emm，When I change it to the lastest version
```
 pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
  pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
```
It raise these error..
<img width="1105" alt="QQ20220328-164724@2x" src="https://user-images.githubusercontent.com/49340347/160361317-939261b8-df0e-47a7-9e42-b3cff5d49c04.png">
.

**Comment by mohantym** [comment]
@luckysmg ! Good to hear that.  Can you let us know the results with the[ same approach ](https://github.com/tensorflow/tensorflow/issues/55389#issuecomment-1080367899)with a new app ?

**Comment by luckysmg** [comment]
Here is demo code.
[iOSDemo 2.zip](https://github.com/tensorflow/tensorflow/files/8356734/iOSDemo.2.zip)

**Comment by tomacco** [comment]
Any updates on this? We are facing the same issue.
