### ISSUE TITLE
Compiling error when adding -c dbg parameter

### ISSUE THREAD

**Issue by alephman** [tensorflow/tensorflow#5538]
I try to compile tensorflow in Docker machine:
./configure   // all options is default
bazel build -c dbg --local_resources 1500,1,1 --verbose_failures  tensorflow/tools/pip_package:build_pip_package --ignore_unsupported_sandboxing

bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

the output is here:

Fri Nov 11 04:23:09 UTC 2016 : === Using tmpdir: /tmp/tmp.EhXibedOJY
/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles /tensorflow
/tensorflow
/tmp/tmp.EhXibedOJY /tensorflow
Fri Nov 11 04:23:15 UTC 2016 : === Building wheel
Traceback (most recent call last):
  File "setup.py", line 201, in <module>
    keywords='tensorflow tensor machine learning',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 241, in run
    wheel_name = archive_wheelfile(pseudoinstall_root, archive_root)
  File "/usr/local/lib/python2.7/dist-packages/wheel/archive.py", line 22, in archive_wheelfile
    return make_wheelfile_inner(base_name)
  File "/usr/local/lib/python2.7/dist-packages/wheel/archive.py", line 72, in make_wheelfile_inner
    writefile(path, date_time)
  File "/usr/local/lib/python2.7/dist-packages/wheel/archive.py", line 61, in writefile
    zip.writestr(zinfo, fp.read())
  File "/usr/lib/python2.7/zipfile.py", line 1222, in writestr
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1106, in _writecheck
    raise LargeZipFile("Filesize would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions

**Comment by girving** [comment]
@alephman This looks like a bug in pip, not tensorflow

@martinwicke Do you know any workarounds?  Is this something we can fix on our end?

**Comment by martinwicke** [comment]
It looks like it's somehow trying to build a truly huge zip file. I have never seen this before, but I'm not building debug pip packages -- can you do some sanity checks to see how big it would be?

**Comment by alephman** [comment]
yeah, the whole folder in /tmp has more than 5G size.   
BTW,  I try to re-compile the tensorflow, but always failed due to downloading dependences errors. Any ways to work around this?

**Comment by girving** [comment]
@alephman I don't think we can fix this on our end, since it's a bug in pip.  I would suggest building and running in place without going through pip.

**Comment by Mistobaan** [comment]
Just got this error too. I always did this steps and I wasn't getting it before

**Comment by martinwicke** [comment]
Can you try building with --spawn_strategy=sandboxed? I just fixed the sandboxed build, and that should cut down on the size of the data in the folder used for building the package.

**Comment by conqer** [comment]
Still getting this issue when compiled with 'dbg' option. Any workaround?

**Comment by martinwicke** [comment]
@conqer This sounds like it would be a great PR for wheel.

**Comment by zuowang** [comment]
solved by modifying /usr/lib/python2.7/site-packages/wheel/archive.py:46
```diff
    # XXX support bz2, xz when available
    zip = zipfile.ZipFile(open(zip_filename, "wb+"), "w",
-                         compression=zipfile.ZIP_DEFLATED)
+                         compression=zipfile.ZIP_DEFLATED, allowZip64=True)

    score = {'WHEEL': 1, 'METADATA': 2, 'RECORD': 3}
    deferred = []

    def writefile(path, date_time):
        st = os.stat(path)
        if date_time is None:
            mtime = time.gmtime(st.st_mtime)
            date_time = mtime[0:6]
        zinfo = zipfile.ZipInfo(path, date_time)
        zinfo.external_attr = st.st_mode << 16
        zinfo.compress_type = zipfile.ZIP_DEFLATED
-       with open(path, 'rb') as fp:
-            zip.writestr(zinfo, fp.read())
+       zip.write(path, arcname=zinfo.filename, compress_type=zipfile.ZIP_DEFLATED)
        log.info("adding '%s'" % path)
```
