### ISSUE TITLE
Calling `model.compile()` multiple times leads to memory leak

### ISSUE THREAD

**Issue by maghsk** [tensorflow/tensorflow#55398]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04, macOS 12.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): `pip install tensorflow==2.8.0`
- TensorFlow version (use command below): 2.8.0
- Python version: 3.9.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: - 
- GPU model and memory:- 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

[Stackoverflow](https://stackoverflow.com/posts/71633201/timeline)

I have tried resetting the state of the optimizer by re-compiling the model. Then I found that it could lead to a memory leak.

reproducible code attached.

**Describe the expected behavior**

Since there are no active variables that could reach the old generated model graph. The old graph in RAM should be freed.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): -

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np
import objgraph

m = tf.keras.models.Sequential([tf.keras.layers.InputLayer(input_shape=(20,)), tf.keras.layers.Dense(10),tf.keras.layers.Dense(10),tf.keras.layers.Dense(10),tf.keras.layers.Dense(10)])
objgraph.show_growth()

for i in range(100):
    tf.keras.backend.clear_session()
    m.compile('adam', loss='mse')
    data = np.arange(32*20).reshape(32, 20)
    labels = np.zeros(32)
    results = m.fit(data, labels, epochs=10)
    objgraph.show_growth()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
@maghsk .
Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by tilakrayal** [comment]
@maghsk ,
please feel free to move this issue to closed status, so that we can track the issue there. Thanks!
