### ISSUE TITLE
TFLite Failed to Allocate Tensor

### ISSUE THREAD

**Issue by ZikeiWong** [tensorflow/tensorflow#55399]
### 2. Code
I have an exported Frozen Graph .pb file, and converted it to tflite using
```
graph_def_file = "model.pb"
input_arrays = ["Placeholder"]
input_shape = {"Placeholder": [1024, 2048, 3]}
output_arrays = ["final_output"]
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file, input_arrays, output_arrays, input_shape)

tflite_model = converter.convert()
with open("my_model.tflite", "wb") as f:
        f.write(tflite_model)
```
And I could not restore my model with
```
interpreter = tf.lite.Interpreter(model_path="my_model.tflite")
interpreter.resize_tensor_input(0, [1024, 2048, 3], strict=True)
interpreter.allocate_tensors()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-3cfaee7dc51c> in <module>
      1 interpreter = tf.lite.Interpreter(model_path=model_path)
      2 interpreter.resize_tensor_input(0, [1024, 2048, 3], strict=True)
----> 3 interpreter.allocate_tensors()

~/.local/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    512   def allocate_tensors(self):
    513     self._ensure_safe()
--> 514     return self._interpreter.AllocateTensors()
    515 
    516   def _safe_to_run(self):

RuntimeError: tensorflow/lite/kernels/conv.cc:349 input->dims->data[3] != filter->dims->data[3] (65 != 64)Node number 11 (CONV_2D) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.
```

However, I can successfully reload my .pb file frozen graph by using
```
with tf.gfile.GFile('my_model.pb', "rb") as pb:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(pb.read())
with tf.Graph().as_default() as graph:
    tf.import_graph_def(
            graph_def,
            name="", 
            )
```
and also successfully generated result by

```
node_in = graph.get_tensor_by_name('Placeholder:0') 
node_out = graph.get_tensor_by_name('final_output:0') 

with tf.Session(graph=graph) as sess:  # Session()
    # sess.run(tf.global_variables_initializer()) 
    feed_dict = {node_in: input_img}  
    pred = sess.run(node_out, feed_dict) 
    print(pred)
    sess.close()
```

I've checked the node 11 of the .tflite file in Netron, but everything seemed fine.
![node 11](https://user-images.githubusercontent.com/42362331/160350576-92c32abb-2ccc-4ee5-9003-a6ec3538dd78.png)
What could be the problem? 

The file attached is my .pb frozen graph
 [model.zip](https://github.com/tensorflow/tensorflow/files/8359810/model.zip)

**Comment by mohantym** [comment]
Hi @ZikeiWong ! Could you check this [migration document](https://tensorflow.google.cn/guide/migrate/tflite) on converting frozen graphs to Tflite ?

**Comment by ZikeiWong** [comment]
Hi @mohantym! Thank you so much for your reply.

Yeah, I am sorry that I forgot to put my coverting code up there, and I've updated it.

I've tried to convert from frozen graph to tflite with:
```
graph_def_file = "model.pb"
input_arrays = ["Placeholder"]
input_shape = {"Placeholder": [1024, 2048, 3]}
output_arrays = ["final_output"]
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    graph_def_file, input_arrays, output_arrays, input_shape)

tflite_model = converter.convert()
with open("my_model.tflite", "wb") as f:
        f.write(tflite_model)
```

I've also tried to convert my frozen graph to SavedModel first using
```
from tensorflow.python.saved_model import signature_constants
from tensorflow.python.saved_model import tag_constants

export_dir = './convert_model/saved'
graph_pb = './convert_model/model.pb'

builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

with tf.gfile.GFile(graph_pb, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

sigs = {}

with tf.Session(graph=tf.Graph()) as sess:
    # name="" is important to ensure we don't get spurious prefixing
    tf.import_graph_def(graph_def, name="")
    g = tf.get_default_graph()
    inp = g.get_tensor_by_name("Placeholder:0")
    out = g.get_tensor_by_name("final_output:0")

    sigs[signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY] = \
        tf.saved_model.signature_def_utils.predict_signature_def(
            {"in": inp}, {"out": out})

    builder.add_meta_graph_and_variables(sess,
                                         [tag_constants.SERVING],
                                         signature_def_map=sigs)

builder.save()
```
and then convert the SavedModel to tflite with
```
converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(
    './convert_model/saved')
tflite_model = converter.convert()
open("./convert_model/icnet_savedmodel.tflite", "wb").write(tflite_model)
```
but ```interpreter.allocate_tensors()``` still gives me the same debugging information ```untimeError: tensorflow/lite/kernels/conv.cc:349 input->dims->data[3] != filter->dims->data[3] (65 != 64)Node number 11 (CONV_2D) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.``` 


I suppose it's the problem of the .pb file of the frozen graph, but it could still be used to restore session and give inference.

This is how I saved my frozen graph .pb file:
```
saver = tf.train.Saver()
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    tf.train.write_graph(sess.graph_def, './convert_model', 'model.pb') 
    saver.save(sess, "convert_model/model.ckpt") 

constant_graph = graph_util.convert_variables_to_constants(net.sess, 
                                                           net.sess.graph_def,
                                                           ['final_output'])

with tf.gfile.FastGFile('./convert_model/model.pb', mode='wb') as f:
        f.write(constant_graph.SerializeToString())
```

**Comment by mohantym** [comment]
Hi Sachin! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/b6d40ef800f27a5853c515fbf9104629/github_55399.ipynb#scrollTo=HBHgb24w3V3l) ,[ 2.8](https://colab.sandbox.google.com/gist/mohantym/69634a06b55281b56cb5f105e6152ab8/github_55399.ipynb#scrollTo=-DZ4o0WaCDIZ) and[ nightly](https://colab.sandbox.google.com/gist/mohantym/48c3236fb6c45083d7ebc6fb56de68df/github_55399.ipynb#scrollTo=sGje8x42Frfn).

**Comment by ZikeiWong** [comment]
Hi, thank you for your responses. I wonder if anyone could help me with the issuse?

**Comment by ZikeiWong** [comment]
Hi,  thank you again for your previous responses. I am still waiting for any response.

**Comment by pjpratik** [comment]
The issue still persists with TF 2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/7f9e69288f789a94bec84467ce96166e/55399.ipynb). Thank you.

**Comment by pjpratik** [comment]
Hi @ZikeiWong 

The issue seems to be resolved with latest nightly version.

Could you please check this [gist](https://colab.sandbox.google.com/gist/pjpratik/5c3e16a273ba3ecf49efada05f1e8a7d/55399.ipynb) and confirm the same?

Thanks.
