### ISSUE TITLE
tanh(float(7~8)) = 1.0000001 in XLA

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#55390]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux or mac 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 2.8 or 1.15
- Python version: 3.9 or 2.7
- Bazel version (if compiling from source): bazel release 5.0.0-pre.20211011.2
- GCC/Compiler version (if compiling from source): Apple clang version 13.0.0 (clang-1300.0.29.3) 
- CUDA/cuDNN version: no
- GPU model and memory: no 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
    zsh: command not found: v1.12.1-68911-gea661077441

**Describe the current behavior**
The return value of tanh function is  1.0000001, but tanh can not return more than 1.

**Describe the expected behavior**
The return value of tanh function is 1 or less than 1.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):
There is a description in the xla comment that the xla implementation of the tanh function is copied from eigen3.(tensorflow/compiler/xla/service/llvm_ir/math_ops.h:25), but I compare the implementation of the tanh function within xla and eigen3, they not have same implementation .so I copy the implementation of tanh function from eigen3 to tensorflow ....

**Standalone code to reproduce the issue**
```
import os
os.environ['TF_XLA_FLAGS'] = '--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit --tf_xla_min_cluster_size=0'

import tensorflow as tf

tf.compat.v1.disable_eager_execution()

#with tf.compat.v1.device('gpu'):
ctr_y = tf.compat.v1.random.uniform([1], minval=8, maxval=9, dtype=tf.compat.v1.float32)
ctr_pred_ori = tf.compat.v1.tanh(ctr_y)


session_config = tf.compat.v1.ConfigProto(allow_soft_placement=True, log_device_placement=True)
session_config.graph_options.rewrite_options.disable_meta_optimizer=True
with tf.compat.v1.Session(config=session_config) as sess:
  while  True:
    ret = sess.run([ctr_pred_ori])[0]
    if ret > 1.0:
      print(ret);
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
 212 [array([0.99999964], dtype=float32)]
13702 [array([0.99999976], dtype=float32)]
 621 [array([0.9999997], dtype=float32)]
17916 [array([0.9999998], dtype=float32)]
21312 [array([0.99999994], dtype=float32)]
48624 [array([0.9999999], dtype=float32)]
8097 [array([1.0000001], dtype=float32)]
   5 [array([1.0000002], dtype=float32)]
42322 [array([1.], dtype=float32)]
```
tanh return 1.0000001 8097 times

**Comment by sushreebarsa** [comment]
@chunduriv  I was able to reproduce this issue on colab using TF v2.8.0 and tf-nightly,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/917d52c54aec646ed8c22a90bd8c4ac3/55390.ipynb).Thanks!

**Comment by zhaozheng09** [comment]
Please add TF_XLA_FLAGS="--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit --tf_xla_min_cluster_size=0", because there is only 1 node in my example xla cluster, 1 node does not meet the tf_xla_min_cluster_size(default:4) condition
![image](https://user-images.githubusercontent.com/33950866/160961857-bcf84532-eb56-4bbc-9f30-37e449a52af5.png)

**Comment by sachinprasadhs** [comment]
@zhaozheng09 , Could you please provide the test case as requested in the PR created by you. Thanks!
