### ISSUE TITLE
Sticky  "No OpKernel was registered to support Op 'Conv2D' with these attrs."

### ISSUE THREAD

**Issue by ssegvic** [tensorflow/tensorflow#5539]
There are two issues here:

1: tf.nn.conv2d does not support float64 tensors on CPU although the documentation states it should
2: after the first occurrence of the situation above, tf.nn.conv2d keeps crashing with the same error even when we provide float32 tensors.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/4929

### Environment info
Operating System: Linux

Installed version of CUDA and cuDNN: None

If installed from binary pip package, provide:
1. A link to the pip package you installed:
-> https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
(not 100% sure though)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
-> 0.11.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
# issue 1: this never works although the documentation states that it should
import tensorflow as tf
import numpy as np

input = tf.constant(np.zeros([1,5,5,1]))
filter = tf.constant(np.zeros([3,3,1,1]))
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
tf.Session().run(op)

# issue 2: 
# - this works if executed *before* the part above
# - this does not work if exectuted *after* the part above
import tensorflow as tf
import numpy as np

input2 = tf.constant(np.zeros([1,5,5,1]), dtype=np.float32)
filter2 = tf.constant(np.zeros([3,3,1,1]), dtype=np.float32)
op2 = tf.nn.conv2d(input2, filter2, strides=[1, 1, 1, 1], padding='VALID')
tf.Session().run(op2)
```

**Comment by sherrym** [comment]
Our doc is incorrect in this case: we currently don't support 64-bit conv2d. We will have the doc updated shortly. Thanks.

We do have plans to support 64-bit in the near future.

**Comment by girving** [comment]
@sherrym Is a near term doc update likely?
