### ISSUE TITLE
Does the released Inception-v3 model only support forward pass with batch_size=1?

### ISSUE THREAD

**Issue by ffmpbgrnn** [tensorflow/tensorflow#554]
Hi all,
I am new to TF. I am playing with Inception-v3 model and I found that I can only pass `batch_size=1` to the model. Here is my test code:
```python
import tensorflow.python.platform
import tensorflow as tf
from tensorflow.python.platform import gfile
import numpy as np


with tf.device("/cpu:0"):
    with gfile.FastGFile('/tmp/imagenet/classify_image_graph_def.pb', 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        _ = tf.import_graph_def(graph_def, name='')

with tf.Session() as sess:

    array = np.random.rand(1, 299, 299, 3)
    image_data = tf.convert_to_tensor(array, dtype=tf.float32).eval()

    test_tensor = sess.graph.get_tensor_by_name('Mul:0')
    print(test_tensor.get_shape())
    softmax_tensor = sess.graph.get_tensor_by_name('softmax:0')
    predictions = sess.run(softmax_tensor,
                          {'Mul:0': image_data})
```
If I change `array = np.random.rand(1, 299, 299, 3)` with `batch_size=2`, then TF would complain about the size mismatch.

Am I doing something wrong? Any pointer would be of great help.

**Comment by sherrym** [comment]
The classify_image_graph_def.pb is built explicitly to support a batch size of 1, and cannot support other batch sizes. But nice effort.

Sherry

**Comment by dmitryfisko** [comment]
Does exist easy way to remove this limitation?

**Comment by martinwicke** [comment]
In an already built graph, no. Sorry.

**Comment by dmitryfisko** [comment]
Those, because graph already built, it is impossible to cut out a part of saved graph and connect it with a new in "inference" stage?

**Comment by martinwicke** [comment]
That would be a major headache. It's probably possible, but I wouldn't
recommend it. If any of the variables have to change shape for the
different batch size, your checkpoints become useless or you have to
manually add resize or reshape ops.

**Comment by sangramkapre** [comment]
I also want to try Inception-V3 model to make a forward pass on images and extract features from intermediate layers. From where can I get the TensorFlow meta-graph file (i.e. classify_image_graph_def.pb)?

**Comment by D-X-Y** [comment]
@sangramkapre http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
You could see https://github.com/tensorflow/models/blob/master/tutorials/image/imagenet/classify_image.py

**Comment by ideaRunner** [comment]
Hi @dmitryfisko, Have you find a way to solve this problem？ Hmm, batch size =1 cost too much unnecessary time.
@martinwicke Will the batch inference version of this pb model be released?

**Comment by martinwicke** [comment]
We will not release a new version of this old graph. I would check out tfhub.dev for various alternatives.
