### ISSUE TITLE
TensorBoard Dev doesn't update upon delete operation

### ISSUE THREAD

**Issue by de-gozaru** [tensorflow/tensorflow#55407]
Hi,

I'm using TensorBoard dev to log my training metrics. My TensorBoard version is `2.8.0`.

I log my data using the command
```
tensorboard dev upload --logdir=my/dir/of/logs
```

However, I noticed that once a version is created, and is apparent on TensorBoard dev, even if I delete it locally, it still exist on the online version. This behavior doesn't happen with local TensorBoard.

Is this behavior expected? is there a way to correct this?

Thank you in advance.

**Comment by sushreebarsa** [comment]
@de-gozaru Could you please post this issue on Tensorboard [repo](https://github.com/tensorflow/tensorboard/issues) to get the right help there?
Thanks!

**Comment by sushreebarsa** [comment]
@de-gozaru Thank you for the quick response!
Please move this issue to closed status if you have posted this issue in that repo?
Thanks!
