### ISSUE TITLE
ValueError: Python inputs incompatible with input_signature

### ISSUE THREAD

**Issue by harshayelchuri** [tensorflow/tensorflow#55403]
I'm working with this On-Device Training with TensorFlow Lite
https://www.tensorflow.org/lite/examples/on_device_training/overview#setup

However, I customized the model. But, after customization, the following error is coming
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[ 9.       17.229916]
 [15.       10.601508]
 [15.       10.517618]
 [ 7.       26.893026]
 [15.       10.572687]
 [ 7.       27.393883]
 [15.        9.859101]
 [14.       11.724992]
 [12.       13.421819]
 [ 7.       28.229916]], shape=(10, 2), dtype=float32),
    tf.Tensor([1. 1. 1. 0. 1. 0. 1. 1. 1. 0.], shape=(10,), dtype=float32))
  input_signature: (
    TensorSpec(shape=(10, 2), dtype=tf.float32, name=None),
    TensorSpec(shape=(10, 1), dtype=tf.float32, name=None)).

Please find the code here
https://colab.research.google.com/drive/1jLM8BWuB7VRDMJHxKUDAIBR17MHqYSKk?usp=sharing

**Comment by mohantym** [comment]
Hi @harshayelchuri ! I think you have already resolved the issue by changing these lines. 
`TensorSpec(shape=(10, 2), dtype=tf.float32, name=None) ,TensorSpec(shape=(10, 1), dtype=tf.float32, name=None)`
to
`TensorSpec(shape=(None, 2), dtype=tf.float32, name=None), TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)`

**Comment by harshayelchuri** [comment]
Yes I resolved the issue, But the final code is this:
 @tf.function(input_signature=[tf.TensorSpec([None, 2], tf.float64),tf.TensorSpec([None], tf.float64)])

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
