### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: StridedSlice.

### ISSUE THREAD

**Issue by whoisltd** [tensorflow/tensorflow#55419]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 21.10
- TensorFlow installation: pip
- TensorFlow library: 2.8.0

### 2. Code
        original = img
        height = self.input_details[0]['shape'][1]
        width = self.input_details[0]['shape'][2]
        img = cv2.resize(img, (width, height), interpolation=cv2.INTER_AREA)
        img = np.expand_dims(img, axis=0)

        # Normalize input data
        input_mean = 127.5
        input_std = 127.5
        input_data = np.uint8((np.float32(img) - input_mean) / input_std)
        self.interpreter.set_tensor(self.input_details[0]['index'], input_data)

        self.interpreter.invoke()

Code Im using to convert model:

          converter = tf.lite.TFLiteConverter.from_saved_model('./saved_model')
          converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
          converter.allow_custom_ops=True
          converter.experimental_new_converter =True
          tflite_model = converter.convert()

### 3. Failure after conversion
Model converting finished with no error, but the converted model couldn't run through the interpreter.

### 4. Error traceback
       Traceback (most recent call last):
        File "/home/whoisltd/detect/serve_model.py", line 32, in <module>
          print(predict(image))
        File "/home/whoisltd/detect/serve_model.py", line 21, in predict
          result = model.predict(img)
        File "/home/whoisltd/detect/src/merged_model.py", line 88, in predict
          self.detect_text(cropped_image)
        File "/home/whoisltd/detect/src/merged_model.py", line 49, in detect_text
          detection_boxes, detection_classes, _ = self.text_detection_model.predict(image)
        File "/home/whoisltd/detect/src/detector/detector.py", line 46, in predict
          self.interpreter.invoke()
        File "/home/whoisltd/detect/det/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 916, in invoke
          self._interpreter.Invoke()
      RuntimeError: Encountered unresolved custom op: StridedSlice.
      See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 11 (StridedSlice) failed to prepare.Node number 0 (WHILE) failed to invoke.
      double free or corruption (!prev)
      Aborted (core dumped)

**Comment by mohantym** [comment]
Hi @whoisltd ! Can you add the below line before converter.convert() to allow custom ops in Tflite conversion and let us know the result? Attaching relevant thread for reference . [1](https://github.com/tensorflow/tensorflow/issues/45321#issuecomment-737049073) , [2](https://stackoverflow.com/a/59801545/11530462). Thanks!
```
converter.experimental_new_converter =True
or converter.allow_custom_ops=True 
```

**Comment by whoisltd** [comment]
> Hi @whoisltd ! Could you please share a complete stand alone code to replicate this issue?

what do you mean?

**Comment by mohantym** [comment]
@whoisltd ! The conversion process looks fine to me.I was skeptical about the inference part actually  and needed either a sample model or the lite model for investigation. Below line in the stack trace is curious to me. 

`  double free or corruption (!prev)`

Attaching relevant thread for reference. [1](https://stackoverflow.com/questions/50342405/error-in-python-double-free-or-corruption-prev-0x00005634ba7d3e80) , [2](https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-498542543). Thanks!

**Comment by whoisltd** [comment]
@mohantym 
I was fix `double free or corruption (!prev)` follow [this](https://github.com/tensorflow/tensorflow/issues/6968#issuecomment-380319691) comment. 
But i still have runtime error:
```
RuntimeError: Encountered unresolved custom op: StridedSlice.
See instructions: https://www.tensorflow.org/lite/guide/ops_customNode number 11 (StridedSlice) failed to prepare.Node number 0 (WHILE) failed to invoke.
```

**Comment by mohantym** [comment]
@sachinprasadhs ! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/2d5f401614bd971ef46d86f55cfcdecd/github_55419.ipynb#scrollTo=uHGXHgtNsGPN) ,[2.8](https://colab.sandbox.google.com/gist/mohantym/77e671c5950af663a844cda4cbf697b5/github_55419.ipynb#scrollTo=Kl6t5SPZpXXS) and [nightly](https://colab.sandbox.google.com/gist/mohantym/2d5dbe212edd4f1a4ad640368092a2dc/github_55419.ipynb#scrollTo=uHGXHgtNsGPN)

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/e1529a4ee4f1f94dda19b4b6f10671df/55419.ipynb). Thank you.

**Comment by pjpratik** [comment]
Hi @whoisltd 

The right way to add select ops is 
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
Please find the resolved [gist](https://colab.sandbox.google.com/gist/pjpratik/f2d783fd4242b7842868c5f160594a7e/55419.ipynb) with correct syntax and random data.

Thanks.

**Comment by whoisltd** [comment]
I have tested and it works. Thanks to TensorFlow team for still support

**Comment by pjpratik** [comment]
Hi @whoisltd 

Glad it works.

Please feel free to close the issue since it is resolved.

Thanks.
