### ISSUE TITLE
Parameter init_epoch can not be identified when calling model.train()

### ISSUE THREAD

**Issue by v3551G** [tensorflow/tensorflow#55422]
Hi,
    I am trying to implement incremental training (when the model trained is stopped due to other reasons, I can retrain the model from the latest checkpoint). There, I used the parameter 'init_epoch' when calling model.train(). However, parameter 'init_epoch' can not be identified in Tensorflow2.4.0.
   I want to know which version of Tensorflow support parameter 'init_epoch'?

![scr](https://user-images.githubusercontent.com/12910533/160596038-09c582fa-334f-4426-bb5a-8d014398e617.png)

**Comment by sushreebarsa** [comment]
@v3551G In order to expedite the trouble-shooting process,could you please provide the code and share the error in  text format  instead of the screenshot which will help  us to analyze the issue?Thanks!

**Comment by v3551G** [comment]
Thank you. The parameter is misspelled, and the correct parameter should be 'initial_epoch'

**Comment by sushreebarsa** [comment]
@v3551G Currently the BackupAndRestore callback only supports eager mode. In graph mode, consider using  Save/Restore Model as mentioned [here](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras), and by providing initial_epoch in [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit).
We recommend you to use TF v2.4 or later versions as older versions are not actively supported.
Please let us know if it helps?
Thanks!
