### ISSUE TITLE
`pfor`/`tf.vectorize_map`: Improve feedback/hints messages when it `fallback_to_while_loop`

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#55425]
**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):
Probably if I can talk with a codeowner of this namepace

**Describe the feature and the current behavior/state.**
As we are adding [a root cause message](https://github.com/tensorflow/tensorflow/pull/55192) on the cause we are going internally to rely on `fallback_to_while_loop`  it would be nice to have a more clear feedback  string to the user on what kind of action is required (e.g. refactoring his function, open a new ticket with a code gist on TF github, etc..).

See more at https://github.com/tensorflow/tensorflow/pull/55192#issuecomment-1081306349 /cc @wangpengmit 

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Developers that partially fail to fully `tf.vectorize_map` their functions
**Any Other info.**

**Comment by gadagashwini** [comment]
@bhack, Can we close this issue, since associated PR got merged. Thanks!

**Comment by bhack** [comment]
@gadagashwini This is something else and it has no associated PR. 
Please check the mentioned @wangpengmit's comment at https://github.com/tensorflow/tensorflow/pull/55192#issuecomment-1081306349
