### ISSUE TITLE
model is loaded as Loader._recreate_base_user_object.<locals>._UserObject

### ISSUE THREAD

**Issue by darrahts** [tensorflow/tensorflow#55438]
python == 3.8
tensorflow (gpu) == 'v2.8.0-rc1-32-g3f878cff5b6'
keras == 2.8
windows 10

I am saving the model as both an h5 and keras format with

```
model.save('model.h5')
model.save(model_location)
type(model)   
```
```
keras.engine.functional.Functional
```

Then, I am loading the model with 

```
model = keras.models.load_model(model_location)
# or 
model = tf.saved_model.load(model_location) # results in the same
type(model)
```

```<class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>```

There is something up with the loading process that results in the following error when calling `model.predict(X)` 

```AttributeError: '_UserObject' object has no attribute 'predict'```

```
tf.saved_model.contains_saved_model(model_location)

true
```
However, loading the same model saved as an h5 file 
```
model = keras.models.load_model('model.h5')
type(model)
```
```
keras.engine.functional.Functional
```
works. 

Thanks in advance!

**Comment by tilakrayal** [comment]
@darrahts ,
Model.save() will save  keras type model. tf.keras.models.load_model will load it back as keras model. 

tf.saved_model.save will save  generic model. tf.saved_model.load will load it back either type, as generic _UserObject model.
Also can you please look at this [comment](https://github.com/tensorflow/models/issues/8990#issuecomment-1069733488) from the issue with the similar error.Thanks

**Comment by darrahts** [comment]
@tilakrayal,

Thanks for the comment. The point of this is, why is `keras.models.load_model` not returning the model? It is returning the same thing as `tf.saved_model.load`.

**Comment by tilakrayal** [comment]
@darrahts ,
In order to reproduce the issue reported here, could you please provide the complete code you are using. Thanks!

**Comment by gowthamkpr** [comment]
@darrahts This issue doesn't exist on my Linux machine. **Please try with the latest version of tensorflow gpu on windows** and let me know if the issue still persists . Thanks!

**Comment by NEGU93** [comment]
I am having this issue using tensorflow 2.8.0

```Python
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import Model
from tensorflow import saved_model
from pathlib import Path
from numpy.random import rand

inputs = Input(shape=(200,))
x = Dense(64, activation="relu")(inputs)
outputs = Dense(1, activation="sigmoid")(x)

model = Model(inputs=inputs, outputs=outputs, name="DummyTF")
model.compile()

data = rand(1, 200).tolist()
model.predict(data)

path = str(Path(__file__).parent.resolve() / "ai_model" / "models" / "dummy_tf")

model.save(path)

model_loaded = saved_model.load(path)
model_loaded.predict(data)
```

Error message:

```
Traceback (most recent call last):
  File "creating_dummy_tf_model.py", line 22, in <module>
    model_loaded.predict(data)
AttributeError: '_UserObject' object has no attribute 'predict'
```

**Comment by NEGU93** [comment]
Ok, I solved it using [`tf.keras.models.load_model`](https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model) as suggested [here](https://stackoverflow.com/a/70524143/5931672). 

However, was the error I got the expected behavior?
