### ISSUE TITLE
TF 2.8.0 NNApi createInterpreter fails on Android API 32 devices

### ISSUE THREAD

**Issue by elevenfive** [tensorflow/tensorflow#55436]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes (sample project linked below)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Android API 32 - Pixel 6

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Any device running Android API 32 (such as Pixel 6)

- TensorFlow installed from (source or binary):
Binary

- TensorFlow version (use command below):
2.8.0

- GPU model and memory:
Mali-G78 MP20, N/A (Shared memory)

**Describe the current behavior**

Instrumented test in sample project succeeds on API <= 31, fails on API == 32

**Describe the expected behavior**

Instrumented test in sample project succeeds on all Android API levels

- Do you want to contribute a PR? (yes/no): No, I don't know the fix.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

`./gradlew connectedAndroidTest`

https://github.com/elevenfive/TensorFlowApplication

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
NNApi test threw exception
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: NN API returned error ANEURALNETWORKS_OP_FAILED at line 4483 while completing NNAPI compilation.
    
    Node number 7 (TfLiteNnapiDelegate) failed to prepare.
    Restored original execution plan after delegate application failure.
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:93)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
        at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:226)
```

**Comment by mohantym** [comment]
Hi @elevenfive ! Sorry for the late response. The above app is running fine in an emulator with Pixel 5 and API 32 with latest android studio version.  Can you confirm your android studio version too?                                                    ![AndroidStudioAPI32](https://user-images.githubusercontent.com/86464649/161043609-728d4e00-7831-4003-a667-651a9640e870.png)

**Comment by mohantym** [comment]
@elevenfive! I could run the instrumental test after commenting out **options.setUseNnapiCpu(true)** in Pixel XL with API 32 in Android  studio BumbleBee  without any exception. I would like to hear from @sachinprasadhs too. Thanks!

**Comment by elevenfive** [comment]
> @elevenfive! I could run the instrumental test after commenting out **options.setUseNnapiCpu(true)** in Pixel XL with API 32 in latest Android studio version( BumbleBee) without any exception. I would like to hear from @sachinprasadhs too. Thanks!
> 
> [NNAPI_55436](https://user-images.githubusercontent.com/86464649/161215324-bfe09f09-7f55-43f1-b530-2a4c313f8aad.png)

Are you sure you ran the test there and not the "app" configuration?  You should use that little green play button next to the test method name.  You should see the unit test results as pass/fail at the bottom.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
