### ISSUE TITLE
MobileNetV3 reloading weights from version 2.8 gives error but not 2.7

### ISSUE THREAD

**Issue by PhillipMaire** [tensorflow/tensorflow#55432]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no 
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.7 and 2.8
- Python version: 3

**current behavior** is it give an error when loading weights in V2.8 but not in 2.7. tested models include 
ResNetV2 = works!
MobileNetV3Large = ERROR
MobileNetV3Small = ERROR
inceptionnetV3 = works!

it give the following error for MobileNetV3Large 
`ValueError: Layer count mismatch when loading weights from file. Model expected 110 layers, found 111 saved layers.`

**expected behavior** is to load the weights 

- Do you want to contribute a PR? (yes/no): no, 

**Standalone code to reproduce the issue**
here is a [Colab notebook](https://colab.research.google.com/drive/1RdRdW2GtLl_XrRkRgA78R170r9hZh-of?usp=sharing) that shows the issue, it downloads my weight file and everything but just in case [here is a link](https://www.dropbox.com/s/9pkhkvij53paz5m/0022_cp.hdf5?dl=0) to my weights.

**Other info / logs** 
when I originally created and trained my model and when rebuilding my model I get the following warning
`WARNING:tensorflow:`input_shape` is undefined or non-square, or `rows` is not 224. Weights for input shape (224, 224) will be loaded as the default.`

because I use image size of [96, 96, 3] and not [224, 224] as the warning mentioned above. the model worked great so I didn't worry about it, maybe this is related to the issue? 

Thanks for your hard work and I hope this helps other community members!

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8 and [nightly](https://colab.research.google.com/gist/tilakrayal/cb4fb69f9096a4a2260acae5fd5fb9e7/nigtlytf_issues_fails_to_load_mobilenet_weights_in_2_8_but_not_2_7.ipynb), whereas in [v2.7](https://colab.research.google.com/gist/tilakrayal/182544e20eeb1d103f8d2cea85bdd781/tf_issues_fails_to_load_mobilenet_weights_in_2_8_but_not_2_7.ipynb) i was able to execute without facing any issue.Please find the gist.

**Comment by PhillipMaire** [comment]
I'm a little confused, are you just confirming my results? Because I get the same results.

**Comment by chunduriv** [comment]
@PhillipMaire,

>note 2.8 name load _v2 while 2.7 does not. 

Yes

>can I force it to download from the 2.7 version? I can test if this solves the issue!

If you can force it to `weights_mobilenet_v3_large_224_1.0_float_no_top.h5`, it is working. Thanks!

**Comment by PhillipMaire** [comment]
ok great! I am not sure how to force it to use the original no top weights file though. how would I go about doing this? will this be in a new release? I am trying to collect data for a publication so I'm in a bit of a hurry :sweat: thank you

**Comment by PhillipMaire** [comment]
any mobility on this issue? I saw the commit failed some tests, can anyone elaborate on why changing the mobile net weights file to what it was in 2.7 causes failures?

**Comment by chunduriv** [comment]
@PhillipMaire,

Sorry for late response. As we modified the architecture in TF 2.8, it is not possible to make it backward compatible. Hence the old weights is not going to work with new model.

As a workaround you can try to use TF2.7 else you need to train your model using TF2.8. Thanks!

**Comment by PhillipMaire** [comment]
can you elaborate on how this is possible? mobilenet V3 (or any static base model) architecture should be the exact same no matter what version of TF/keras is being used right? I am very confused because by definition if a model has a different number of layers it can not be the same model (even if it behaves identically in every other way). Can you point to a reference as to why the following function `applications.MobileNetV3Large(input_shape=[96, 96, 3], weights='imagenet', include_top=False)` should generate a model with 109 layer in TF V 2.7 but 108 layers in TF 2.8, surely this is a mistake of some kind, right?

**Comment by PhillipMaire** [comment]
I am using colab for my project and they have TF 2.8 GPU installed and I can not get a working V2.7 GPU working on colab. Is it unreasonable to ask for a working TF 2.7 version mobilenet model function perhaps like `applications._MobileNetV3Large()` or something? or are there too many dependancies and changes so that wont work?

**Comment by chunduriv** [comment]
@PhillipMaire,

Currently on colab it defaults to `TF2.8` , to work with TF 2.7, please can you try as below

`!pip install tensorflow==2.7`

Please find the working [gist](https://colab.research.google.com/gist/chunduriv/6d6ebde57741d8467a86374d0270c87e/55432.ipynb) using `TF2.7 GPU` for reference. Thanks!
