### ISSUE TITLE
Constant folding doesn't remove control edges

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#5543]
I believe that when constant folding takes place, and a section of a graph is replaced by a constant, that only the data output edge of the replaced node is removed.  

I believe that I can see that a graph of nodes ending up in a Div (part of the gradient generation bit) is replaced by a Const.  The output of the Div goes to a Mul, and this is changed to the new const correctly.

However, there is a control output from the Div going to a Const (not sure why, but it is).  This is not changed to the Div replacement.  Consequently the dead node pruning doesn't remove the original Div.  

Here is some trace:

During the constant folding:

Graph Before #nodes 67 #edges 109
Graph Constant graph #nodes 32 #edges 42
Constant foldable 32 : 67

Replacing {name:'gradients/Mean_grad/truediv' id:28 op device:{/job:localhost/replica:0/task:0/device:ipu:0} def:{gradients/Mean_grad/truediv = Div[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:ipu:0"](gradients/Mean_grad/Tile, gradients/Mean_grad/Cast)}} :: 0 with a constant
Replacing edge to gradients/Square_grad/mul_1:0

During the post constant folding pruning:

PruneForReverseReachability: gradients/Square_grad/mul_1 <- gradients/Mean_grad/truediv/_0__cf__1
PruneForReverseReachability: gradients/Square_grad/mul/x <- gradients/Mean_grad/truediv

After the pruning:

Graph ConstFolding #nodes 68 #edges 110

When the graph is passed to the device, it contains:

Node: gradients/Square_grad/mul/x = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 2>, _device="/job:localhost/replica:0/task:0/device:ipu:0"](^gradients/Mean_grad/truediv)

**Comment by DavidNorman** [comment]
Example:
```
import tensorflow as tf

# Creates a graph.
a = tf.placeholder(tf.float32, [2,2])
b = tf.placeholder(tf.float32, [2,2])
c = tf.constant([[2.0,2.0],[2.0,2.0]])
d = tf.constant([[2.0,2.0],[2.0,2.0]])
e = tf.add(c, d)
with tf.control_dependencies([e]):
  f = tf.mul(a, a)
  g = tf.mul(b, e)
  o = tf.add(f, g)

sess = tf.Session()

fd = {
  a: [[1.0,2.0],[3.0,4.0]],
  b: [[1.0,0.0],[0.0,1.0]],
}

sess.run(o, feed_dict=fd)
```

During constant folding this leads to:
```
Graph Before #nodes 11 #edges 16
|| 
|| () -> () {
||   n2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_16__recv_Placeholder_0", tensor_type=float]()
||   n3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_17__recv_Placeholder_1_0", tensor_type=float]()
||   n4 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 2 2 2...>]()
||   n5 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 2 2 2...>]()
||   n6 = Add[T=float](n4, n5)
||   n7 = Mul[T=float](n2, n2) @ n6
||   n8 = Mul[T=float](n3, n6)
||   n9 = Add[T=float](n7, n8)
||   n10 = _Send[T=float, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device_incarnation=1, tensor_name="edge_5_Add_1"](n9)
|| }
|| 


Graph After #nodes 12 #edges 17
|| 
|| () -> () {
||   n11 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 4 4 4...>]()
||   n2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_16__recv_Placeholder_0", tensor_type=float]()
||   n3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_17__recv_Placeholder_1_0", tensor_type=float]()
||   n4 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 2 2 2...>]()
||   n5 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 2 2 2...>]()
||   n8 = Mul[T=float](n3, n11)
||   n6 = Add[T=float](n4, n5)
||   n7 = Mul[T=float](n2, n2) @ n6
||   n9 = Add[T=float](n7, n8)
||   n10 = _Send[T=float, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device_incarnation=1, tensor_name="edge_5_Add_1"](n9)
|| }
|| 
```

You can see that there is a constant replacing the Add, but that the Add remains, because it is referred to by the control edge.

I think that the output should be:

```
Graph After #nodes 12 #edges 17
|| 
|| () -> () {
||   n11 = Const[dtype=float, value=Tensor<type: float shape: [2,2] values: 4 4 4...>]()
||   n2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_16__recv_Placeholder_0", tensor_type=float]()
||   n3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_17__recv_Placeholder_1_0", tensor_type=float]()
||   n8 = Mul[T=float](n3, n11)
||   n7 = Mul[T=float](n2, n2) @ n11
||   n9 = Add[T=float](n7, n8)
||   n10 = _Send[T=float, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device_incarnation=1, tensor_name="edge_5_Add_1"](n9)
|| }
|| 
```

**Comment by DavidNorman** [comment]
One more example.  This is the 'getting_started.py' that is in the TF documentation.  I have modified it so that it uses placeholders, rather than allowing the X and Y data to be constants.

```
Graph Before #nodes 67 #edges 109
|| 
|| () -> () {
||   n2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_110__recv_Placeholder_1_0", tensor_type=float]()
||   n3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_109__recv_Placeholder_0", tensor_type=float]()
||   n4 = Variable[container="", dtype=float, shape=[1], shared_name=""]()
||   n7 = Variable[container="", dtype=float, shape=[1], shared_name=""]()
||   n11 = Const[dtype=int32, value=Tensor<type: int32 shape: [0] values: >]()
||   n12 = Const[dtype=float, value=Tensor<type: float shape: [] values: 1>]()
||   n14 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n16 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n18 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n19 = Const[dtype=int32, value=Tensor<type: int32 shape: [0] values: >]()
||   n20 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 0>]()
||   n22 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 0>]()
||   n24 = Const[dtype=int32, value=Tensor<type: int32 shape: [] values: 1>]()
||   n32 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n33 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n42 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n43 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n54 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n55 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n63 = Const[dtype=float, value=Tensor<type: float shape: [] values: 0.5>]()
||   n5 = Identity[T=float, _class=["loc:@Variable"]](n4)
||   n8 = Identity[T=float, _class=["loc:@Variable_1"]](n7)
||   n13 = Fill[T=float](n11, n12)
||   n21 = Prod[T=int32, Tidx=int32, keep_dims=false](n18, n20)
||   n23 = Prod[T=int32, Tidx=int32, keep_dims=false](n19, n22)
||   n34 = BroadcastGradientArgs[T=int32](n32, n33)
||   n44 = BroadcastGradientArgs[T=int32](n42, n43)
||   n56 = BroadcastGradientArgs[T=int32](n54, n55)
||   n6 = Mul[T=float](n5, n3)
||   n15 = Reshape[T=float, Tshape=int32](n13, n14)
||   n25 = Maximum[T=int32](n23, n24)
||   n9 = Add[T=float](n6, n8)
||   n17 = Tile[T=float, Tmultiples=int32](n15, n16)
||   n26 = Div[T=int32](n21, n25)
||   n10 = Sub[T=float](n9, n2)
||   n27 = Cast[DstT=float, SrcT=int32](n26)
||   n28 = Div[T=float](n17, n27)
||   n29 = Const[dtype=float, value=Tensor<type: float shape: [] values: 2>]() @ n28
||   n30 = Mul[T=float](n29, n10)
||   n31 = Mul[T=float](n28, n30)
||   n35 = Sum[T=float, Tidx=int32, keep_dims=false](n31, n34)
||   n37 = Sum[T=float, Tidx=int32, keep_dims=false](n31, n34:1)
||   n36 = Reshape[T=float, Tshape=int32](n35, n32)
||   n38 = Neg[T=float](n37)
||   n39 = Reshape[T=float, Tshape=int32](n38, n33)
||   n40 = NoOp() @ n36, n39
||   n41 = Identity[T=float, _class=["loc:@gradients/sub_grad/Reshape"]](n36) @ n40
||   n45 = Sum[T=float, Tidx=int32, keep_dims=false](n41, n44)
||   n47 = Sum[T=float, Tidx=int32, keep_dims=false](n41, n44:1)
||   n46 = Reshape[T=float, Tshape=int32](n45, n42)
||   n48 = Reshape[T=float, Tshape=int32](n47, n43)
||   n49 = NoOp() @ n46, n48
||   n50 = Identity[T=float, _class=["loc:@gradients/add_grad/Reshape"]](n46) @ n49
||   n53 = Identity[T=float, _class=["loc:@gradients/add_grad/Reshape_1"]](n48) @ n49
||   n51 = Mul[T=float](n50, n3)
||   n52 = Mul[T=float](n5, n50)
||   n65 = ApplyGradientDescent[T=float, _class=["loc:@Variable_1"], use_locking=false](n7, n63, n53)
||   n57 = Sum[T=float, Tidx=int32, keep_dims=false](n51, n56)
||   n59 = Sum[T=float, Tidx=int32, keep_dims=false](n52, n56:1)
||   n58 = Reshape[T=float, Tshape=int32](n57, n54)
||   n60 = Reshape[T=float, Tshape=int32](n59, n55)
||   n61 = NoOp() @ n58, n60
||   n62 = Identity[T=float, _class=["loc:@gradients/mul_grad/Reshape"]](n58) @ n61
||   n64 = ApplyGradientDescent[T=float, _class=["loc:@Variable"], use_locking=false](n4, n63, n62)
||   n66 = NoOp() @ n64, n65
|| }
|| 


Replacing {name:'gradients/Mean_grad/truediv' id:28 op device:{/job:localhost/replica:0/task:0/device:ipu:0} def:{gradients/Mean_grad/truediv = Div[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:ipu:0"](gradients/Mean_grad/Tile, gradients/Mean_grad/Cast)}} :: 0 with a constant

Graph After #nodes 68 #edges 110
|| 
|| () -> () {
||   n67 = Const[dtype=float, value=Tensor<type: float shape: [100] values: 0.01 0.01 0.01...>]()
||   n2 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_110__recv_Placeholder_1_0", tensor_type=float]()
||   n3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:ipu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_109__recv_Placeholder_0", tensor_type=float]()
||   n4 = Variable[container="", dtype=float, shape=[1], shared_name=""]()
||   n7 = Variable[container="", dtype=float, shape=[1], shared_name=""]()
||   n11 = Const[dtype=int32, value=Tensor<type: int32 shape: [0] values: >]()
||   n12 = Const[dtype=float, value=Tensor<type: float shape: [] values: 1>]()
||   n14 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n16 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n18 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n19 = Const[dtype=int32, value=Tensor<type: int32 shape: [0] values: >]()
||   n20 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 0>]()
||   n22 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 0>]()
||   n24 = Const[dtype=int32, value=Tensor<type: int32 shape: [] values: 1>]()
||   n32 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n33 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n42 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n43 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n54 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 1>]()
||   n55 = Const[dtype=int32, value=Tensor<type: int32 shape: [1] values: 100>]()
||   n63 = Const[dtype=float, value=Tensor<type: float shape: [] values: 0.5>]()
||   n5 = Identity[T=float, _class=["loc:@Variable"]](n4)
||   n8 = Identity[T=float, _class=["loc:@Variable_1"]](n7)
||   n13 = Fill[T=float](n11, n12)
||   n21 = Prod[T=int32, Tidx=int32, keep_dims=false](n18, n20)
||   n23 = Prod[T=int32, Tidx=int32, keep_dims=false](n19, n22)
||   n34 = BroadcastGradientArgs[T=int32](n32, n33)
||   n44 = BroadcastGradientArgs[T=int32](n42, n43)
||   n56 = BroadcastGradientArgs[T=int32](n54, n55)
||   n6 = Mul[T=float](n5, n3)
||   n15 = Reshape[T=float, Tshape=int32](n13, n14)
||   n25 = Maximum[T=int32](n23, n24)
||   n9 = Add[T=float](n6, n8)
||   n17 = Tile[T=float, Tmultiples=int32](n15, n16)
||   n26 = Div[T=int32](n21, n25)
||   n10 = Sub[T=float](n9, n2)
||   n27 = Cast[DstT=float, SrcT=int32](n26)
||   n28 = Div[T=float](n17, n27)
||   n29 = Const[dtype=float, value=Tensor<type: float shape: [] values: 2>]() @ n28
||   n30 = Mul[T=float](n29, n10)
||   n31 = Mul[T=float](n67, n30)
||   n35 = Sum[T=float, Tidx=int32, keep_dims=false](n31, n34)
||   n37 = Sum[T=float, Tidx=int32, keep_dims=false](n31, n34:1)
||   n36 = Reshape[T=float, Tshape=int32](n35, n32)
||   n38 = Neg[T=float](n37)
||   n39 = Reshape[T=float, Tshape=int32](n38, n33)
||   n40 = NoOp() @ n36, n39
||   n41 = Identity[T=float, _class=["loc:@gradients/sub_grad/Reshape"]](n36) @ n40
||   n45 = Sum[T=float, Tidx=int32, keep_dims=false](n41, n44)
||   n47 = Sum[T=float, Tidx=int32, keep_dims=false](n41, n44:1)
||   n46 = Reshape[T=float, Tshape=int32](n45, n42)
||   n48 = Reshape[T=float, Tshape=int32](n47, n43)
||   n49 = NoOp() @ n46, n48
||   n50 = Identity[T=float, _class=["loc:@gradients/add_grad/Reshape"]](n46) @ n49
||   n53 = Identity[T=float, _class=["loc:@gradients/add_grad/Reshape_1"]](n48) @ n49
||   n51 = Mul[T=float](n50, n3)
||   n52 = Mul[T=float](n5, n50)
||   n65 = ApplyGradientDescent[T=float, _class=["loc:@Variable_1"], use_locking=false](n7, n63, n53)
||   n57 = Sum[T=float, Tidx=int32, keep_dims=false](n51, n56)
||   n59 = Sum[T=float, Tidx=int32, keep_dims=false](n52, n56:1)
||   n58 = Reshape[T=float, Tshape=int32](n57, n54)
||   n60 = Reshape[T=float, Tshape=int32](n59, n55)
||   n61 = NoOp() @ n58, n60
||   n62 = Identity[T=float, _class=["loc:@gradients/mul_grad/Reshape"]](n58) @ n61
||   n64 = ApplyGradientDescent[T=float, _class=["loc:@Variable"], use_locking=false](n4, n63, n62)
||   n66 = NoOp() @ n64, n65
|| }
|| 

```

Node n29, which has a control dependency on n28 is the problem.  n28 was the Div which was replaced.

**Comment by sherrym** [comment]
@keveman would you please comment? Thanks.

**Comment by DavidNorman** [comment]
I should point out that if I bind the nodes to the CPU, then the results are the same.

(these examples are for my own device back end)

**Comment by DavidNorman** [comment]
It seems that constant_folding.cc, ReplaceTensorWithConstant, assumes that the node that will be replaced will have multiple outputs, and only replaces those edges that are fed by the one replaced output. 

BroadcastGradientArgs is a good example.  It really needs to be replaced by 2 constants, and the code, as it stands, works well for that.

Perhaps it is worth considering what it means to have a node that only has a control output assigned to it?  Is this valid?  If not, then the control output should be eliminated, then then the dead code pruning algorithm will kill off that node and it's upstream nodes.

I've not played with the control flow (loops, conditionals), so I don't know if nodes with only control outputs are useful.   I would expect that loops and conditonals are done with Boolean edges, not control edges.  If this is the case, then I think that adding the control edge removal thing is the correct thing to do.

**Comment by DavidNorman** [comment]
I am also wondering what is the rationale behind the memory constraints in the ReplaceTensorWithConstant:

```
  // 1) If the destination tensor is not an int32 tensor, and has HOST_MEMORY
  // constraint, do not replace it.
  // 2) If the destination tensor is an int32 tensor, but has DEVICE_MEMORY
  // constraint, do not replace it.
```

Why would you want to keep nodes that perform arithmetic on a device unnecessarily?  I can imagine that you might consider that it is important to do floating point arithmetic on the target platform because of differences in rounding (although on a neural network I would hope that the result would work around that).

In the case of integers, I can't decide why constant folding would always take place. Could you describe why it would be limited to HOST_MEMORY only?

**Comment by DavidNorman** [comment]
Here is a diff for trying out 'remove control outputs from nodes that have only a control output after constant folding' change:

[diff.txt](https://github.com/tensorflow/tensorflow/files/589083/diff.txt)

**Comment by keveman** [comment]
Sorry for the late response. Constant folding is conservative (perhaps overly) in what it replaces. In your case, since the original node had an outgoing control dependence, it didn't get replaced. Note that the analysis to decide whether that is safe to do is somewhat non-trivial. We have to determine whether that node is control dependent on a stateful node. We chose to let it be conservative. If you have a real example where the performance is poor because of this conservativeness, I'll be happy to take a look.

**Comment by DavidNorman** [comment]
I see the problem.  My case isn't really a performance issue, per se. I am trying to implement a device on TF for our new hardware.  The extra nodes of integer math are getting in the way of the initial bring-up.

If there are stateful nodes in the graph, then why does the constant tree finder consider them acceptable to be within the constant tree?  Isn't the constant that is generated (there is one generated) is not valid after the 1st run through the graph?  In which case, the constant should not replace that section of the graph at all?

**Comment by DavidNorman** [comment]
I realize i failed to write sensible language in that last message.

What I intended to say is that replacing a stateful node with a constant doesn't seem right.  If the stateful node changes state, then the constant is invalid. Either the stateful node should not be included in the constant sub-graph, or the constant sub-graph should be re-evaluated whenever the stateful node changes, in which case there doesn't seem to be a lot of point in having it.

**Comment by DavidNorman** [comment]
Hi,

In fact, I'm pretty certain that the following code taken from constant_folding.cc will prevent the constant sub-graph from containing any stateful nodes.  In which case, it should be ok to apply the control edge removal.

```
bool IsConstantFoldable(const FunctionLibraryDefinition* flib_def,
                        const Node* n,
                        std::function<bool(const Node*)> consider) {
  if (n->op_def().is_stateful()) {
    return false;
  }
```

**Comment by keveman** [comment]
Started looking at this. Will have a fix soon.

**Comment by DavidNorman** [comment]
Now that my own device is an XLA device, I am no longer concerned about this.   

However this is still a problem as far as I can see.  unless the dead code removal is removing nodes that only have a control output.

**Comment by wickson2** [comment]
The code below is my best effort to avoid constant-folding (at all costs). It doesn't work. I end up with constant 100011111 in the instruction stream.

llc -O0 code.ll -print-after-all reveals that the folding happens at Expand ISel Pseudo-instructions pass.
; ModuleID = '0'
target triple = "x86_64-unknown-linux-gnu"

define  i64 @"0"() {
BlockEntry0:
  %cell = alloca i64, align 8
  store volatile i64 0, i64* %cell, align 8
  %volatile_zero3 = load volatile i64, i64* %cell, align 8
  %base = add i64 %volatile_zero3, 100000000
  %volatile_zero4 = load volatile i64, i64* %cell, align 8
  %opaque_offset = add i64 %volatile_zero4, 11111
  %casted_base = inttoptr i64 %base to i8*
  %gep = getelementptr i8, i8* %casted_base, i64 %opaque_offset
  %as_ptr = bitcast i8* %gep to i64*
  %loaded = load i64, i64* %as_ptr, align 4
  %as_function = inttoptr i64 %loaded to i64 (i64)*
  %ret_val = tail call i64 %as_function(i64 0)
  ret i64 %ret_val
}
attributes #0 = { nounwind }
I realize that my problem can be solved by adding some intrinsic which [at]([https://www.cheekywinx.com.au/](https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.cheekywinx.com.au%2F%3Ffbclid%3DIwAR0qx10-H1MJYoe8WGLghgf8n83icrwB5nqtYrU7xZjXwYb1Ar6B6iVHS7s&h=AT11JQk-JsK4Li2yfDhDyf1M0zH7t08cko2DPusnQsKXAwSb3eXUrZ25K53aoBj9wvAZiYuPdn-RqPCeIfjgY42c2oEmmzh497_lgTJ477r0hCxrhjzJcRstcOHDrMhXrv4m) ) codegen level would unfold to simple movabs reg, imm64. But I'd like to have a temporary solution for the time being.
