### ISSUE TITLE
How about exporting `Tensor::FromProto` to Python API?

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/tensorflow#55447]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.8
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

If we have to convert TensorProto message in Python env, we can't directly convert it.
We have to 

1. construct a new tensor with protobuf message field
2. serialize message to string and parse it using `tf.io.parse_tensor`
3. or some other way

**Will this change the current api? How?**

Yes. Maybe we can add the `tf.from_tensor_proto` like `tf.make_tensor_proto`.

**Who will benefit with this feature?**

The people who frequently handle protobuf messages.
For example, I handle TensorProto messages directly when I predict some examples with TensorFlow Serving using gRPC.

**Any Other info.**

[`Tensor::FromProto` docs link](https://www.tensorflow.org/api_docs/cc/class/tensorflow/tensor#fromproto)

**Comment by jeongukjae** [comment]
@rainwoodman Oh, I didn't know about that function. Thank you!

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
