### ISSUE TITLE
Checkpoint variable names are assigned "variables/0/..." etc if keras model has more than two nested layers/models

### ISSUE THREAD

**Issue by canbakiskan** [tensorflow/tensorflow#55446]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0 (gpu)
- Python version: 3.10.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.5/8.3.1
- GPU model and memory: 1080 Ti 12GB

**Describe the current behavior**

When a keras model has more than two nested layers/models the names of saved variables of inner layers get assigned incremental values like `variables/{0,1,2...}/.ATTRIBUTES/VARIABLE_VALUE` instead of `inner/layer/kernel/.ATTRIBUTES/VARIABLE_VALUE` for example. This does not happen in nested `tf.Module`s.

**Describe the expected behavior**

To be honest I would expect both tensorflow and keras to respect the actual names of variables in `.name` attribute when saving to a checkpoint, like with TF1.x scopes; rather than this mess of `module_name/module_name/kernel/.ATTRIBUTES/VARIABLE_VALUE`. But if we have to accept the `.ATTRIBUTES/VARIABLE_VALUE` business, the variable names should still follow the nested module names rather than `variables/0/` etc.

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

The issue is caused when the `TrackableReference` chain to a variable is shorter through `variables/{index}` (2 jumps) than it is with `inner/layer/kernel` (3 jumps or more) during the breadth first traversal implemented here: https://github.com/tensorflow/tensorflow/blob/38976aedc4e9d9149bfe75f485be0dd833e9eec7/tensorflow/python/training/tracking/graph_view.py#L246

**Solution**

Add
```
elif any([path_element.name in ["variables", "trainable_variables", "non_trainable_variables"] for path_element in node_paths[dependency]]):
    node_paths[dependency] = node_paths[current_trackable] + (base.TrackableReference(name, dependency),)
```
after https://github.com/tensorflow/tensorflow/blob/38976aedc4e9d9149bfe75f485be0dd833e9eec7/tensorflow/python/training/tracking/graph_view.py#L260

**Standalone code to reproduce the issue**

```
import tensorflow as tf

class inner_block(tf.keras.layers.Layer):
    def __init__(self):
        super().__init__(name="inner")
        self.layer = tf.keras.layers.Dense(2, name="inner_dense") # kernel of this will save as "variables/0/.ATTRIBUTES/VARIABLE_VALUE"
        self.var = tf.Variable([1.0, 2.0], name="inner_var") # this will save as expected "inner_m/var/.ATTRIBUTES/VARIABLE_VALUE"

    def call(self, x):
        return self.layer(x) + self.var

class model(tf.keras.Model):
    def __init__(self):
        super().__init__(name="outer")
        self.inner_m = inner_block()
        self.dense = tf.keras.layers.Dense(2, name="outer_dense") # kernel of this will save as expected "dense/kernel/.ATTRIBUTES/VARIABLE_VALUE"

    def call(self, x):
        x = self.inner_m(x)
        x = self.dense(x)
        return x

m = model()
m.build((None, 3))
m(tf.random.normal((1, 3)))

m.save("model")  # or tf.saved_model.save(m, "model")
tf.train.list_variables(
    "model/variables/variables"
)  # this lists 'variables/0/...' 'variables/1/...' along with the expected names
```

**Comment by sushreebarsa** [comment]
@canbakiskan I tried to replicate the issue on colab using TF v2.8.0(gpu) and faced a warning message.Could you please find the [gist](https://colab.research.google.com/gist/sushreebarsa/3d2cc435f86e6e4a598c0e01b554c89e/55446.ipynb)  and confirm the same?
Thanks!

**Comment by canbakiskan** [comment]
Ok, when I used `save_traces=False` to turn those off in `m.save()` it does save with the proper names. I guess that was the issue. Is it saved like that intentionally when `save_traces=True`?

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate this issue onn colab using TF v2.8.0, tf-nightly,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2402f679bf715cdfad81b49a90c6bef5/gist55446.ipynb#scrollTo=lOjG2SGMpT3E) for reference.Thanks!
