### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: PyFunc.Node number 559 (PyFunc) failed to prepare.

### ISSUE THREAD

**Issue by MiracleMiranda07** [tensorflow/tensorflow#55445]
System information

Windows
TF 2.5.0

Command used to run the converter or code if you’re using the Python API
Converter:

**keras_model = model.keras_model
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.allow_custom_ops = True
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()**

Inference:

 **# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

interpreter.resize_tensor_input(input_details[0]['index'], layer_image.shape)
interpreter.allocate_tensors()

input_data_1 = np.array(layer_image, dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data_1)

interpreter.invoke()**

The output from the Inference:
**RuntimeError: Encountered unresolved custom op: PyFunc.Node number 559 (PyFunc) failed to prepare.**

Im pretty new to tensorflow. Im facing an issue in tflite model inference.I have used a **tf.numpy_function** in my keras layer for inference part, the inference is perfectly working in keras. But when converted to tflite, the pinvoke is giving me the above error

**Comment by mohantym** [comment]
Hi @MiracleMiranda07 ! Can you please share a link to the model file too?

**Comment by Mayur28** [comment]
Hi, is there any solution to this problem as I am experiencing the same issue?
Thanks

**Comment by mohantym** [comment]
Hi @Mayur28 ! 
To resolve custom ops issues , you need to register them in lite/kernels and put` converter.allow_custom_ops = True` during conversion. Attached relevant [thread](https://www.tensorflow.org/lite/guide/ops_custom) for reference.

Please create a new issue for further assistance. 

Thank you!
