### ISSUE TITLE
lack of up-to-date files after upgrading to tensorflow 0.11

### ISSUE THREAD

**Issue by kopxiong** [tensorflow/tensorflow#5544]
I just upgraded tensorflow to 0.11 by using `conda install -c conda-forge tensorflow` , but still lack of files in `anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/examples/tutorials`, such as `mnist_softmax.py`. The current files I have in this folder are:
```
__init__.py 
__init__.pyc
input_data.py
input_data.pyc
mnist.py
mnist.pyc
```

**Comment by sherrym** [comment]
Hi @kopxiong ,

0.11 was built a month ago. If you would like the latest greatest of everything, please install nightly.

Sherry

**Comment by kopxiong** [comment]
One stupid question: anyone can give a hint how to install tensorflow nightly? Because I am using python 2.7 in Anaconda environment, does Anaconda is not a good choice for tensorflow? Thanks a lot!

**Comment by girving** [comment]
@martinwicke Should a page about the tensorflow nightly builds show up on the first page of https://www.google.com/search?sclient=psy-ab&espv=2&biw=1440&bih=801&btnG=Search&q=tensorflow+nightly&oq=&gs_l=&pbx=1#q=tensorflow+nightly+builds?

**Comment by martinwicke** [comment]
Ideally, but since we're completely replacing our website, SEO is not
useful at this point.

**Comment by zuoxingdong** [comment]
@girving @sherrym 

I've uninstalled tensorflow and build it from nightly binaries, it is now `0.11.0` version, but still doesn't contain other examples except for mnist tutorials. 

```
/tensorflow
----/examples
--------/__pycache__
--------/tutortials
------------/mnist
------------/__pycache__
------------/__init__.py
--------/__init__.py
```

**Comment by martinwicke** [comment]
That's the only example that named in the pip_package/BUILD file. I have no objection to including other things from the examples/ folder.
