### ISSUE TITLE
Keras cant load model with tf.where when dtype is float64

### ISSUE THREAD

**Issue by VihGrimm** [tensorflow/tensorflow#55454]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8 (also encountered on 2.4)
- Python version: 3.7.5
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
Loading a model that utilizes `tf.where` to replace a variable with some constant fails when all involved tensors are `float64` tensors.

Possibly connected to [this issue](https://github.com/tensorflow/tensorflow/issues/47161).

**Describe the expected behavior**
The model loads successfuly.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras

dtype = 'float64'

some_input = keras.Input(shape=(1), dtype=dtype)
some_value = keras.layers.Dense(4, activation="relu", dtype=dtype)(some_input)
some_value = keras.layers.Dense(2, dtype=dtype)(some_value)

other_value = tf.constant([0.1], dtype=dtype)

mask = tf.equal([0, 1], 1)
replaced_value = tf.where(mask, x=other_value, y=some_value)

model = tf.keras.Model(inputs=[some_input], outputs=[replaced_value])
model.save('my_test_model')

loaded_model = tf.keras.models.load_model('my_test_model')
```

However, the model can be loaded properly when the arguments in the call to `tf.where` are switched, like this `tf.where(mask, x=some_value, y=other_value)`

Setting `tf.keras.backend.set_floatx('float64')` does not prevent the error from occuring.

See this [Colab notebook](https://colab.research.google.com/drive/1mii4nbvHUJHaqbG60bEm88-ttdB7AltJ).

**Other info / logs**
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-11-a4651214ca80>](https://localhost:8080/#) in <module>()
----> 1 loaded_model = tf.keras.models.load_model('my_test_model')

[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py](https://localhost:8080/#) in _apply_op_helper(op_type_name, name, **keywords)
    545 
    546             raise TypeError(
--> 547                 f"{prefix} type "
    548                 f"{dtypes.as_dtype(attrs[input_arg.type_attr]).name} of "
    549                 f"argument '{inferred_from[input_arg.type_attr]}'.")

TypeError: Exception encountered when calling layer "tf.where_3" (type TFOpLambda).

Input 'e' of 'SelectV2' Op has type float64 that does not match type float32 of argument 't'.

Call arguments received:
  • condition=['tf.Tensor(shape=(), dtype=bool)', 'tf.Tensor(shape=(), dtype=bool)']
  • x=['0.1']
  • y=tf.Tensor(shape=(None, 2), dtype=float64)
  • name=None
```

**Comment by tilakrayal** [comment]
@VihGrimm ,
`tf.keras.backend.set_floatx` supports only for Keras and it doesn't have any effect on Tensorflow. Also I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/26033) where a similar feature has been proposed and it is still open and [comment](https://github.com/tensorflow/tensorflow/issues/35141#issuecomment-902165565) from the google developer. 

Please try to use tf.constant which resulting tensor values are cast to the requested dtype.
**`tf.constant([values], dtype=tf.float64)`**.Thanks!

**Comment by VihGrimm** [comment]
@tilakrayal 

> Please try to use tf.constant which resulting tensor values are cast to the requested dtype. **`tf.constant([values], dtype=tf.float64)`**.Thanks!

`tf.constant([values], dtype='float64')` and `tf.constant([values], dtype=tf.float64)` seem to yield to the same result.
In particular the described behaviour does not change when setting dtype to `tf.float64` as opposed to `'float64'`.

>  Also I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/26033) where a similar feature has been proposed and it is still open and [comment](https://github.com/tensorflow/tensorflow/issues/35141#issuecomment-902165565) from the google developer.

Thank you for pointing out that issue and especially the comment.
The ongoing feature request to set tensorflow dtypes globally would probably solve the problem.
The dtype parameter for `tf.where` would definitely solve it.

**Comment by tilakrayal** [comment]
@VihGrimm ,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.Thanks!

**Comment by VihGrimm** [comment]
@tilakrayal 
For me, the problem is solved with the workaround.
However, it feels unsatisfactory to call the whole thing resolved, since the error still exists when loading models that use `tf.where`. And I would describe it as unexpected behavior.
Since a fix is not foreseeable for now: maybe it would be good to point out this behavior in the docs so that others don`t face the same problem?
