### ISSUE TITLE
Possibly platform related tflite conversion issue

### ISSUE THREAD

**Issue by enaskopelja** [tensorflow/tensorflow#55461]
#### (1) With issues in:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `macOS Monterey 12.2.1 (m1)`
- TensorFlow installation (pip package or built from source):  following https://developer.apple.com/metal/tensorflow-plugin/
- TensorFlow library (version, if pip package or github SHA, if built from source): 
```
tensorflow-deps==2.8.0
tensorflow-graphics==2021.12.3
tensorflow-macos==2.8.0
tensorflow-metal==0.4.0  
```

#### (2) Without issues in:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Arch Linux x86_64 (5.16.16-arch1-1)`
- TensorFlow installation (pip package or built from source):  `pip`
- TensorFlow library (version, if pip package or github SHA, if built from source): `2.8.0`

### 2. Code
Written to match [this example](https://www.tensorflow.org/graphics/api_docs/python/tfg/math/optimizer/levenberg_marquardt/minimize#examplesl) as much as possible.

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
from tensorflow_graphics.math.optimizer import levenberg_marquardt


def convert_to_tflite(
    model_path: str,
) -> bytes:
    converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS,  # enable TensorFlow ops.
    ]

    tflite_model = converter.convert()
    assert isinstance(tflite_model, bytes)

    return tflite_model


def tflite_inference(
    inputs: list[tf.Tensor],
    tflite_model: bytes,
) -> list:
    # create interpreter
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

    # set inputs
    input_details = interpreter.get_input_details()
    for input_tensor, input_placeholder in zip(inputs, input_details):
        interpreter.set_tensor(input_placeholder["index"], input_tensor)

    # invoke interpreter
    interpreter.invoke()

    # return outputs
    output_details = interpreter.get_output_details()
    return [interpreter.get_tensor(output["index"]) for output in output_details]


def create_lmo_model():
    def f1(x, y):
        return x + y

    def f2(x, y):
        return x * y

    class LMO(tf.keras.layers.Layer):
        def call(self, inputs):
            _, (r1, r2) = levenberg_marquardt.minimize(
                residuals=(f1, f2),
                variables=inputs,
                max_iterations=10,
            )
            return [r1, r2]

    input_x = tf.keras.Input(
        shape=(1, 2),
    )
    input_y = tf.keras.Input(
        shape=(3, 1),
    )
    output = LMO()([input_x, input_y])

    return tf.keras.Model(
        inputs=[input_x, input_y],
        outputs=output,
    )


def main():
    tf.random.set_seed(5)
    x = tf.random.uniform((1, 1, 2))
    y = tf.random.uniform((1, 3, 1))
    inputs = [x, y]

    model = create_lmo_model()
    print(model(inputs))

    tf.saved_model.save(
        model,
        "lmo_model",
    )

    tflite_model = convert_to_tflite("lmo_model")
    print(
        tflite_inference(
            tflite_model=tflite_model,
            inputs=inputs,
        )
    )


if __name__ == "__main__":
    main()
```

### 3. Failure after conversion
On platform 1 tflite interpreter fails to invoke with error:
```bash
RuntimeError: Input matrix is not invertible.
	 (while executing 'MatrixTriangularSolve' via Eager)Node number 15 (TfLiteFlexDelegate) failed to invoke.Node number 104 (IF) failed to invoke.Node number 10 (WHILE) failed to invoke.
```
On platform 2 everything works as expected.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you look at this issue? I modified the original code run in colab environment  . The issue is surfacing in 2nd inference (not in 1st inference). Attaching gist in [2.7](https://colab.sandbox.google.com/gist/mohantym/9a726f539a17b8b28d20d1377422f13e/git_55461.ipynb#scrollTo=Zxg4aODy_cjj), [2.8](https://colab.sandbox.google.com/gist/mohantym/301325009d7dce8b62dd6de966ecce7d/git_55461.ipynb#scrollTo=lxQY9XhqwTcb) and [nightly](https://colab.sandbox.google.com/gist/mohantym/8bdfdc3e8368fd4d448a0c2aa56768c3/git_55461.ipynb#scrollTo=Zxg4aODy_cjj). Thanks!

**Comment by pkgoogle** [comment]
Hi @enaskopelja ,

I was able to resolve the issue by changing the order of inputs: [gist](https://colab.research.google.com/gist/pkgoogle/60ac96606cb20e50052e45d539ac16cc/git_55461.ipynb)
However this is not a guaranteed solution as the input ordering is not guaranteed either way after conversion and creating the interpreter, one can resolve this more generally by using input signatures and using names for your inputs. Please review the following documentation on how to add signatures: https://www.tensorflow.org/lite/guide/signatures

Once you have signatures for the model you can inspect the converted model's signature and map your inputs to the named inputs.

Let us know if you are satisfied with this solution.
