### ISSUE TITLE
undefined symbol when linking tf code with custom op

### ISSUE THREAD

**Issue by pranavladkat** [tensorflow/tensorflow#55466]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): AmazonLinux2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): installed through pip
- TensorFlow version: 2.8
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: Nvidia V100

**Describe the problem**

Hi,

I'm writing a custom op and I'd like to reuse an existing tf function `tensorflow::functor::DenseUpdate<>` for updating `tf.Variable`. I am able to compile my custom op successfully but I get the following error at runtime when I try to load my op in python:

```
undefined symbol: _ZN10tensorflow7functor11DenseUpdateIN5Eigen9GpuDeviceEdLNS_15DenseUpdateTypeE2EEclERKS3_NS2_9TensorMapINS2_6TensorIdLi1ELi1ElEELi16ENS2_11MakePointerEEENS8_INS9_IKdLi1ELi1ElEELi16ESB_EE
```

I am able to find this symbol in `_pywrap_tensorflow_internal.so` library which gets loaded when I import tensorflow.
```
$ nm -gD /home/ec2-user/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so | grep _ZN10tensorflow7functor11DenseUpdateIN5Eigen9GpuDevice
_ZN10tensorflow7functor11DenseUpdateIN5Eigen9GpuDeviceEdLNS_15DenseUpdateTypeE2EEclERKS3_NS2_9TensorMapINS2_6TensorIdLi1ELi1ElEELi16ENS2_11MakePointerEEENS8_INS9_IKdLi1ELi1ElEELi16ESB_EE
```

Can someone help point out what could be an issue here?

Thanks

**Comment by pranavladkat** [comment]
I believe this issue is somewhat related to https://github.com/tensorflow/tensorflow/issues/25513. I don't see any solution there as well.

**Comment by pranavladkat** [comment]
Alright, I think I found the root cause of this issue. It turns out that tensorflow uses `RTLD_LOCAL` when reading this shared file [[code]](https://github.com/tensorflow/tensorflow/blob/9758c05524a05b1c6f54d23513520b14f35c5878/tensorflow/python/pywrap_tensorflow.py#L52). If I change the `RTLD_LOCAL` flag to `RTLD_GLOBAL` my custom op is able to find the undefined symbols. I'm not sure why the original intent was to load these symbols with this flag. Can someone clarify that? If it can be changed to global, it will resolve similar issues which are still open.

I can also get around this issue by changing `dlopen` flags prior to importing tensorflow:
```
import sys
import os
old_flags = sys.getdlopenflags()
sys.setdlopenflags(old_flags | os.RTLD_GLOBAL | os.RTLD_LAZY)
import tensorflow as tf
```

**Comment by gadagashwini** [comment]
@pranavladkat, 
Hi Thanks for reporting this issue.
Could you tell us the GCC version that you are using. Thanks!

**Comment by gadagashwini** [comment]
@pranavladkat, 
Hi Thanks for reporting this issue.
Could you tell us the GCC version that you are using. Thanks!

**Comment by pranavladkat** [comment]
Hi, thanks for the response. I'm using GCC 9.3.0.

Thanks

**Comment by gadagashwini** [comment]
@pranavladkat, 
Hi Thanks for the information. 
Looks like issue with Tensorflow build. Can you try the workaround mention here [#48064](https://github.com/tensorflow/tensorflow/issues/48064#issuecomment-811554566). Delete `/root/.cache/bazel` to force it to rebuild from scratch. Thanks!

**Comment by Jiaao-Bai** [comment]
i'm seeing the same issue too, what can i do if i build op only using gcc 9.3? Delete /root/.cache/bazel is not ok

**Comment by 372046933** [comment]
Temporary solution https://github.com/tensorflow/tensorflow/issues/27899#issuecomment-907362692

**Comment by gadagashwini** [comment]
@Jiaao-Bai,
Could you open new issue by providing all the required information asked in [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&template=tensorflow_issue_template.yaml). Thanks!
