### ISSUE TITLE
difference Between the output of conv1d with same input and weights for tf2.3 and tf2.6

### ISSUE THREAD

**Issue by zhazl** [tensorflow/tensorflow#55471]
Hello, I had met a problem just like the title. The inputs and weights  are same, use difference tf's version 2.3 and 2.6, I got difference outputs. Is this caused by precision
![clipboard_image_1648902447965](https://user-images.githubusercontent.com/20295041/161383301-524ba7bc-e9ef-4ac3-a5aa-a69566420557.png)
![clipboard_image_1648902397799](https://user-images.githubusercontent.com/20295041/161383307-36ef8a79-fd5a-446f-bf6c-874107116a7a.png)
?

**Comment by tilakrayal** [comment]
@zhazl ,
In order to expedite the trouble-shooting process, could you please provide a complete code you are using.

**Comment by zhazl** [comment]
![image](https://user-images.githubusercontent.com/20295041/161932162-e873634b-49a0-4971-bc75-e8b874d704f5.png)
Thanks for response. The code I used as follows. Inputs x  and weights are all same, but I got diffenrent results.

**Comment by zhazl** [comment]
> @zhazl , In order to expedite the trouble-shooting process, I request you, please provide a complete code you are using.Thanks!,

I wonder the method to realize Conv1d between the version of tf about how to process value in type of float32.  Is tf2.6 internally implemented based on the double type?

**Comment by tilakrayal** [comment]
@zhazl ,
I request you can you please provide the code in reproducible format or provide the colab gist.It helps to debug the issue.Thanks!

**Comment by gowthamkpr** [comment]
@zhazl You are right. The results are slightly different due to different degrees of precision.

**Comment by zhazl** [comment]
@gowthamkpr I wonder the detail of the process leads to the degree's difference. Is there any detailed code ?

**Comment by gowthamkpr** [comment]
@zhazl Tried with the latest versions of tensorflow aka (2.7 and 2.8) and this issue doesn't persist. Look at my [gists]([url]([url]([url]([url](url))))) here for tensorflow [2.7](https://colab.research.google.com/gist/gowthamkpr/164005c68a52c075b5d704a1ef2362f9/untitled323.ipynb) and [2.8](https://colab.research.google.com/gist/gowthamkpr/28a2ff3c0394c999ac7bba70f1e2e990/untitled.ipynb).

Please try latest version of tensorflow and check if your issue still persists. Thanks!

**Comment by tilakrayal** [comment]
@zhazl ,
As suggested above request you to please try in latest version of tensorflow 2.8 and check if your issue still persists. Thanks!

**Comment by zhazl** [comment]
@tilakrayal @gowthamkpr Ok, thanks for your solution. It's ok. Thanks again!

**Comment by tilakrayal** [comment]
@zhazl ,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status
