### ISSUE TITLE
Build TF 2.3 with GPU minus AVX

### ISSUE THREAD

**Issue by nafeesmahbub** [tensorflow/tensorflow#55479]
How to custom build TF 2.3 in centos 8 with GPU and without avx as my hardware not support AVX.

**Comment by chunduriv** [comment]
@nafeesmahbub,

 Could you please try [TensorFlow Dockerfile for centos 8](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/onednn/centos-8.Dockerfile). Thanks!
