### ISSUE TITLE
Adding a parameter to teh tf.image.extract_patches function to change the value of added border pixels due to the padding

### ISSUE THREAD

**Issue by mehran66** [tensorflow/tensorflow#55484]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.8
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Using tf.image.extract_patches with "same" padding leads to zeros on the image border. Zero is a default value and cannot be changed by the user. This means that the mask data for image segmentation should always have zero as the background class, otherwise it does mess up after patching. It is best to add this default value as a parameter so the user can change it if needed.

**Will this change the current api? How?**
Adding a parameter to teh tf.image.extract_patches function to change the value of added border pixels due to the padding

**Who will benefit with this feature?**
Anyone using this function for patching data for image segmentation

**Any Other info.**

**Comment by tilakrayal** [comment]
@mehran66 ,
Can you please elaborate about your feature. Also,I request you to please specify the Use Cases for this feature. Thanks!

**Comment by mehran66** [comment]
The tf.image.extract_patches function is used to patchify large images into smaller images. When Padding is set "same", some extra pixels are generated in the border of some images with value of zero. If someone use this tool to patchify images and masks (in semantic segmentation), then zero pixels are added to the masks. If the zero is specific class in the mask, these added zero pixels on the boder can result in inacurate training. Adding a parameter for the default value of padding into the function can solve this issue.

**Comment by mohantym** [comment]
Hi @mehran66 !
Could you share a reproducible code too.
Thank you!
