### ISSUE TITLE
Which version of CUDA does tensorflow2.8.0 correspond to? I can't find it on the website.

### ISSUE THREAD

**Issue by OBLPlife** [tensorflow/tensorflow#55482]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tilakrayal** [comment]
Hello @OBLPlife ,
Every TensorFlow release is compatible with a certain version.I request you, please take a look at the tested build [configurations](https://www.tensorflow.org/install/source#gpu).In this case, can you please try installing TensorFlow v2.8 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Thanks!

**Comment by OBLPlife** [comment]
> Hello @OBLPlife ,
> Every TensorFlow release is compatible with a certain version.I request you, please take a look at the tested build [configurations](https://www.tensorflow.org/install/source#gpu).In this case, can you please try installing TensorFlow v2.8 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Thanks!
> 

OK，thanks for help

**Comment by tilakrayal** [comment]
@OBLPlife ,
Could you please confirm if the issue is resolved. if yes,can you please feel free to move this issue to closed status.Thanks!
