### ISSUE TITLE
Memory Leak in Example/Tutorial Documentation

### ISSUE THREAD

**Issue by tokotchd** [tensorflow/tensorflow#55486]
## URL(s) with the issue:
https://www.tensorflow.org/tensorboard/image_summaries#logging_arbitrary_image_data

## Description of issue (what needs changing):
Listed example needs to be corrected as to avoid memory leaks.

### Clear description
It appears that the example is creating `tf.image.decode_png`  and `tf.expand_dims` layers within `plot_to_image` which is being repeatedly called by a `tf.keras.callbacks.LambdaCallback`.  These layers are filling VRAM or system RAM, depending on whether or not the example is running on GPU or not.

**Comment by sushreebarsa** [comment]
@tokotchd 
Could you please share more details on the issue and provide some use cases on this ?
I was able to run the example tutorial  successfully on colab using TF v2.8.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/210475c9617c4cd9a90fa76fdcbd8464/image_summaries.ipynb) for reference.Thanks!
