### ISSUE TITLE
https://www.tensorflow.org/tutorials/generative/autoencoder

### ISSUE THREAD

**Issue by koushik1234** [tensorflow/tensorflow#55487]
On define convolution encoder: encoded_imgs = autoencoder.encoder(x_test).numpy()

Here the input data is supposed to be " x_test_noisy"

**Comment by tilakrayal** [comment]
Hello @koushik1234 ,
This issue will move to closed status once the PR is merged.Thanks!

**Comment by 8bitmp3** [comment]
Thank you so much @koushik1234 @tilakrayal Let's discuss this in a similar earlier issue https://github.com/tensorflow/tensorflow/issues/53357 and PR https://github.com/tensorflow/docs/pull/1986 (approved). Feel free to reopen! 🙏
