### ISSUE TITLE
How to convert XLA HLO debug code to executable ?

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#55483]
Background : We use TF1.15 to training model, and I'm so sorry we can not upgrade TF to 2.8, because we add some new function for custom tensorflow.
Question: I have a big model, and I want to increase training speed by using xla, but I meet a CUDA_ERROR_ILLEGAL_ADDRESS when I use xla, so I want to know how to solve this question. 
now I have some infomations:
1. I got error xla_cluster name.
2. I got all inputs of error xla_cluster.
3. I got all XLA HLO codes by ```export XLA_FLAGS="--xla_dump_to=./xla"```
For eaier debug, For easier debugging, I want a method that converts the IR code into an executable.
Debugging xla is very, very difficult, please help.

other infos:
cluster_728 have 30 ops. 
The problem will not be repeated when I narrow down the cluster.
The problem will not recur when I shrink the batch_size again.
debug-file about cluster_728: [module_0023.tar.gz](https://github.com/tensorflow/tensorflow/files/8410698/module_0023.tar.gz)

![image](https://user-images.githubusercontent.com/33950866/161570318-b613eca7-6a1e-49da-b223-3b744258f5e6.png)

**Comment by zhaozheng09** [comment]
cluster_728 have 30 ops. 
![image](https://user-images.githubusercontent.com/33950866/161570318-b613eca7-6a1e-49da-b223-3b744258f5e6.png)

**Comment by zhaozheng09** [comment]
comp:xla

**Comment by sushreebarsa** [comment]
@zhaozheng09 We see that you are using TF v1.15 which is not actively supported ,so could you please post this issue in TF [forum](https://discuss.tensorflow.org/) where there is a larger community to get you the right help?Thank you!
