### ISSUE TITLE
is there tensorflow-gpu available for cuda 11.4？

### ISSUE THREAD

**Issue by colaaaaaa** [tensorflow/tensorflow#55492]
<em>I was wandering whether there is a available tensorflow-gpu version for cuda 11.4， when i install the latest version 2.8.0，when i import the tensorflow，i got this

："W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib:/usr/local/cuda/lib:
2022-04-05 11:20:15.733394: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.",  

i see the version attached to cuda latest is 11.2，but i have no authority to downgrad the cuda version, thanks for your attention!</em>

**System information**
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.8.0
- Python version:3.8.0
- Installed using virtualenv? pip? conda?:conda
- CUDA/cuDNN version:11.4

**Comment by tilakrayal** [comment]
@colaaaaaa ,
Every TensorFlow release is compatible with a certain version, for more information can you please take a look at the tested build [configurations](https://www.tensorflow.org/install/source_windows#gpu).In this case, can you please try installing TensorFlow v2.8 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Thanks!

**Comment by reedwm** [comment]
TensorFlow is built and tested with CUDA 11.2, but it also works with CUDA 11.4.

I see you have `/usr/local/cuda/lib` in your `LD_LIBRARY_PATH`, but I don't think CUDA has a directory called `lib`. Try adding `/usr/local/cuda/lib64` to your `LD_LIBRARY_PATH`.

**Comment by colaaaaaa** [comment]
> TensorFlow is built and tested with CUDA 11.2, but it also works with CUDA 11.4.
> 
> I see you have `/usr/local/cuda/lib` in your `LD_LIBRARY_PATH`, but I don't think CUDA has a directory called `lib`. Try adding `/usr/local/cuda/lib64` to your `LD_LIBRARY_PATH`.
Thanks for your advice☺☺☺, but i have checked that the machine has made a soft link form lib to "lib64", so the path is "lib", so this wouldnt work, and i finally reinstalled tensorflow 2.4.0 by install cudatoolkit 11.0  and cudnn 8.1.1.33 without sudo permission 😴😴😴

**Comment by colaaaaaa** [comment]
> @colaaaaaa , Every TensorFlow release is compatible with a certain version, for more information can you please take a look at the tested build [configurations](https://www.tensorflow.org/install/source_windows#gpu).In this case, can you please try installing TensorFlow v2.8 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Thanks!

i looked it before and found that the newst cuda version supported is 11.4， and i finally reinstalled tensorflow 2.4.0 by install cudatoolkit 11.0 and cudnn 8.1.1.33 without sudo permission . and thanks for you kind and quick response!!!😁😁😁

**Comment by colaaaaaa** [comment]
> > @colaaaaaa , Every TensorFlow release is compatible with a certain version, for more information can you please take a look at the tested build [configurations](https://www.tensorflow.org/install/source_windows#gpu).In this case, can you please try installing TensorFlow v2.8 with CUDA 11.2 and cuDNN 8.1 and check if you are facing the same error. Thanks!
> 
> i looked it before and found that the newst cuda version supported is 11.4， and i finally reinstalled tensorflow 2.4.0 by install cudatoolkit 11.0 and cudnn 8.1.1.33 without sudo permission . and thanks for you kind and quick response!!!😁😁😁

and still the cuda version is 11.4, so tf 

> > TensorFlow is built and tested with CUDA 11.2, but it also works with CUDA 11.4.
> > I see you have `/usr/local/cuda/lib` in your `LD_LIBRARY_PATH`, but I don't think CUDA has a directory called `lib`. Try adding `/usr/local/cuda/lib64` to your `LD_LIBRARY_PATH`.
> > Thanks for your advice☺☺☺, but i have checked that the machine has made a soft link form lib to "lib64", so the path is "lib", so this wouldnt work, and i finally reinstalled tensorflow 2.4.0 by install cudatoolkit 11.0  and cudnn 8.1.1.33 without sudo permission 😴😴😴



> > TensorFlow is built and tested with CUDA 11.2, but it also works with CUDA 11.4.
> > I see you have `/usr/local/cuda/lib` in your `LD_LIBRARY_PATH`, but I don't think CUDA has a directory called `lib`. Try adding `/usr/local/cuda/lib64` to your `LD_LIBRARY_PATH`.
> > Thanks for your advice☺☺☺, but i have checked that the machine has made a soft link form lib to "lib64", so the path is "lib", so this wouldnt work, and i finally reinstalled tensorflow 2.4.0 by install cudatoolkit 11.0  and cudnn 8.1.1.33 without sudo permission 😴😴😴

and still the cuda version is 11.4, so tf truly worked with cuda 11.4~

**Comment by tilakrayal** [comment]
@colaaaaaa ,
Glad the issue is resolved for you, please feel free to move this to closed status.Thanks!
