### ISSUE TITLE
TfLiteGpuDelegateV2Create() causes segmentation fault with tflite-gpu2.8 on native side in Android

### ISSUE THREAD

**Issue by lakshya-4gp** [tensorflow/tensorflow#55495]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Android 10, API 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Galaxy S9
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Qualcomm Adreno 630

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
1. On Native side.
`auto* delegate = TfLiteGpuDelegateV2Create(/*default options=*/nullptr);`
results in following error with tensorflow-lite 2.8
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 23129 (com.example.gpu), pid 23129 (com.example.gpu)`

2. In Java.
GPU delegation works fine with tensorflow-lite 2.8, following code works well.
`GpuDelegate.Options delegateOptions = compatList.getBestOptionsForThisDevice();
delegate = new GpuDelegate(delegateOptions);
options.addDelegate(delegate);`

**Describe the expected behavior**
No segmentation fault in 1.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): Not at the moment
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
I downloaded the tflite-2.8 and tflite-gpu-2.8 from the maven repository(https://search.maven.org/) and added them to a new C++ Android project.
And in the default native-lib.cpp added the above code, which throws the error.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @lakshya-IIT4gp ! Did you get a chance to check this [thread ](https://stackoverflow.com/a/65992488/11530462)on using Bazel and Cmaklist.txt for using tflite in react native environment?

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by impjdi** [comment]
Can you attach the model?

**Comment by lakshya-IIT4gp** [comment]
Please find here, https://tfhub.dev/tensorflow/lite-model/efficientdet/lite4/detection/metadata/2. Although, the error is unrelated to any model as its in TfLiteGpuDelegateV2Create(), which still gives error even if no model is initialized.

**Comment by impjdi** [comment]
Wow, this model has ginormous intermediate tensors.  Take 1x320x320x144 as an example; that's ~60MB (= 1x320x320x144x sizeof(float)) and that's only ONE intermediate tensor in your deep neural net.  (I wonder who came up with this and claimed that this is a mobile model :P)  I wouldn't be surprised if things blow up, however, this doesn't explain that things work fine on Java and fail on C++, as the Java version only wraps the C++ code in JNI.  Are you instantiating more than one interpreter?  Any C++ code?

**Comment by lakshya-IIT4gp** [comment]
No, I'm not instantiating even 1 interpreter. I only added single line `auto* delegate = TfLiteGpuDelegateV2Create(/*default options=*/nullptr);` in a default native application, and it gives resulted in error. Please note that I downloaded the libs , tflite-2.8 and tflite-gpu-2.8, from the maven repository(https://search.maven.org/). Could there be difference.

**Comment by nhatuan84** [comment]
I am facing the same issue with 2.8.

**Comment by impjdi** [comment]
Uh, I'm not familiar with the Maven repository.  When I go to search.maven.org, I only get 3 search results and neither libs are there =/

**Comment by nhatuan84** [comment]
> Wow, this model has ginormous intermediate tensors. Take 1x320x320x144 as an example; that's ~60MB (= 1x320x320x144x sizeof(float)) and that's only ONE intermediate tensor in your deep neural net. (I wonder who came up with this and claimed that this is a mobile model :P) I wouldn't be surprised if things blow up, however, this doesn't explain that things work fine on Java and fail on C++, as the Java version only wraps the C++ code in JNI. Are you instantiating more than one interpreter? Any C++ code?

Another issue, I am using TFLite C++, the output of Tensorflow TFLite Python is different with TFLite C++. I am using this example:
https://www.tensorflow.org/lite/examples/style_transfer/overview

**Comment by yupinov** [comment]
https://github.com/tensorflow/tensorflow/commit/213a786c057b516b477de157fb984de04cd4ab51 fixes this. Alternatively, passing auto options = TfLiteGpuDelegateOptionsV2Default(); also works around the crash.

**Comment by zhuker** [comment]
> @lakshya-4gp , there is tensorflow-lite 2.9 available on Maven, as per the above comment, could you please try in the latest stable version and let us know if that works for you. Thanks!

same thing happens to me with 2.9.0

**Comment by lakshya-4gp** [comment]
Any updates on this, as per @zhuker it seems to be still an issue

**Comment by impjdi** [comment]
With v2.9.0,

```
#include <iostream>

#include "third_party/tensorflow/lite/delegates/gpu/delegate.h"

int main() {
  auto* delegate = TfLiteGpuDelegateV2Create(nullptr);
  if (delegate) {
    std::cout << "^_^" << std::endl;
  } else {
    std::cout << "-_-" << std::endl;
  }
  TfLiteGpuDelegateV2Delete(delegate);
  return 0;
}
```

and

```
$ bazel build --config android_arm64 -c opt :hello_world
$ adb push bazel-bin/hello_world /data/local/tmp
$ adb shell /data/local/tmp/hello_world
```

I get

```
^_^
INFO: Created TensorFlow Lite delegate for GPU.
```

Maybe the segfault is coming from somewhere else?

**Comment by infil00p** [comment]
I'm still getting the issue on 2.10 when I use the precompiled libraries provided in the AAR on Gradle.

**Comment by zhusonger** [comment]
I'm facing the issue on 2.12, it's ok run on HUAWEI P20, but crash on One OnePlus 11.

Code:
`
const TfLiteGpuDelegateOptionsV2 options = {
            .is_precision_loss_allowed = 1, // FP16
            .inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER,
            .inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY,
            .inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
            .inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
    };
    TfLiteDelegate* delegate = TfLiteGpuDelegateV2Create(&options);
    TfLiteInterpreterOptionsAddDelegate(p->options, delegate);
`

Log:
`I/tflite  (32341): Created TensorFlow Lite delegate for GPU.
I/tflite  (32341): Initialized TensorFlow Lite runtime.
E/tflite  (32341): Following operations are not supported by GPU delegate:
E/tflite  (32341): GATHER: Operation is not supported.
E/tflite  (32341): 107 operations will run on the GPU, and the remaining 3 operations will run on the CPU.
I/tflite  (32341): Replacing 107 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions for the whole graph.
E/tflite  (32341): Can not open OpenCL library on this device - undefined symbol: clGetCommandBufferInfoKHR
E/tflite  (32341): Falling back to OpenGL
E/tflite  (32341): TfLiteGpuDelegate Init: Batch size mismatch, expected 1 but got 16800
I/tflite  (32341): Created 0 GPU delegate kernels.
E/tflite  (32341): TfLiteGpuDelegate Prepare: delegate is not initialized
E/tflite  (32341): Node number 110 (TfLiteGpuDelegateV2) failed to prepare.
E/tflite  (32341): Restored original execution plan after delegate application failure.
F/libc    (32341): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 8051 (DartWorker), pid 32341 (com.hexin.aigc)`

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
