### ISSUE TITLE
Unit test //tensorflow/core/kernels:conv_ops_benchmark_test_cpu fails to build on non-mkl build

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#55496]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: git HEAD
- Python version: 3.8.12
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 5.1.0
- GCC/Compiler version (if compiling from source): 10.2.1
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Build of unit test //tensorflow/core/kernels:conv_ops_benchmark_test_cpu fails with 

ERROR: /tmp/workspace/tensorflow-git/tensorflow/core/kernels/BUILD:1836:16: Compiling tensorflow/core/kernels/conv_ops_benchmark_test.cc failed: undeclared inclusion(s) in rule '//tensorflow/core/kernels:conv_ops_benchmark_test_cpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/conv_ops_benchmark_test.cc':
  'tensorflow/core/graph/mkl_graph_util.h'
Target //tensorflow/core/kernels:conv_ops_benchmark_test_cpu failed to build
INFO: Elapsed time: 50.018s, Critical Path: 46.01s
INFO: 314 processes: 74 internal, 240 local.
FAILED: Build did NOT complete successfully
//tensorflow/core/kernels:conv_ops_benchmark_test_cpu           FAILED TO BUILD

FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel test --test_timeout=300,500,-1,-1 --flaky_test_attempts=3 --test_output=all --cache_test_results=no --config=nonccl --verbose_failures --build_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --test_tag_filters=-no_oss,-oss_serial,-gpu,-tpu,-benchmark-test,-v1only,-no_aarch64,-requires-gpu --jobs=75 --build_tests_only -- //tensorflow/core/kernels:conv_ops_benchmark_test_cpu

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Introduced by https://github.com/tensorflow/tensorflow/commit/3a0c3b215c969ea5f1a9d59f11b4c628b8c4b22f

**Comment by elfringham** [comment]
@cfRod @nSircombe

**Comment by penpornk** [comment]
Could you please help check if this has been fixed by https://github.com/tensorflow/tensorflow/commit/3fb057af1b930e30cd8f42fd91f722354eaba0e0? Thank you!

**Comment by elfringham** [comment]
Yes, now fixed, thanks.
