### ISSUE TITLE
Build TF wheel in another project which depends on TF

### ISSUE THREAD

**Issue by 372046933** [tensorflow/tensorflow#55505]
**System information**
- OS Platform and Distribution: (Linux Ubuntu 20.04)
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.8.0
- Python version: 3.8.0
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): gcc version 9.4.0
- CUDA/cuDNN version: CUDA 11.2/ cuDNN 8
- GPU model and memory: V100

**Describe the problem**
I have a bazel project which depends on `org_tensorflow`.  My project's `.bazelrc` is copied from TF project
In my project, I can successfully build TF `build_pip_package` target by:
```bash
bazel build --config=native_arch_linux --config=cuda @org_tensorflow//tensorflow/tools/pip_package:build_pip_package
```
However, the following error occurs when generating the wheel
```
./bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

Wed Apr 6 10:41:47 CST 2022 : === Preparing sources in dir: /tmp/tmp.C0MooMsKIF
Could not find bazel-bin.  Did you run from the root of the build tree?
```
The prompt is very intuitive. I also checked `./bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package`
The script assumes that TF is not an external dependency.
 In this situation. How can I generate the TF wheel?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```bash
bazel build --config=native_arch_linux --config=cuda @org_tensorflow//tensorflow/tools/pip_package:build_pip_package
```
```bash
./bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

**Comment by tilakrayal** [comment]
Hello @372046933 ,

It seems there is no symlink for bazel-bin being created.The idea is to create the **`bazel-bin`** symlink is that the TensorFlow **`build_pip_package`** script expects to exist.

Can you try manually creating it and copying all files from **`users/XXXXXXXXXXXXXXXXXX/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/tools/pip_package/build_pip_package.exe`** into **`\tmp\tensorflow\bazel-bin`**

If that doesn't work, can you please try building on a different directory, not **`C:\tmp`**. Most of times **`tmp`** is mismanaged.

If possible, move your workspace to a filesystem that supports symlinks and re-run **`bazel build`** there.

**Comment by 372046933** [comment]
@tilakrayal  Thanks. The reason for no `bazel-bin` is that I am building TF as an external dependency. By the way, I'm building on Linux. `C:\tmp` does not exist.

**Comment by 372046933** [comment]
The key output of `bazel build --config=native_arch_linux --config=cuda @org_tensorflow//tensorflow/tools/pip_package:build_pip_package`:
```
INFO: Found 1 target...
Target @org_tensorflow//tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 211.970s, Critical Path: 98.34s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

**Comment by tilakrayal** [comment]
@372046933 ,
Could you please confirm if the installation issue is resolved? Thanks!

**Comment by 372046933** [comment]
@tilakrayal No, it's not resolved. Cannot execute 
```
./bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

**Comment by gadagashwini** [comment]
@372046933,
Bazel wasn't able to create the symlinks for bazel-bin, try workaround `bazel build --symlink_prefix=/ `when you run Bazel. This will tell Bazel to not create the symlink so it will hopefully work. Thanks!

**Comment by 372046933** [comment]
@gadagashwini  Added `--symlink_prefix=/` to `bazel build`. But nothing changed. My build command is
```bash
bazel build --config=native_arch_linux --config=cuda  --symlink_prefix=/ @org_tensorflow//tensorflow/tools/pip_package:build_pip_package
```
By the way, did you notice that I am building TF as an external dependency. i.e. `@org_tensorflow//tensorflow/tools/pip_package:build_pip_package`  not `//tensorflow/tools/pip_package:build_pip_package`

**Comment by gadagashwini** [comment]
@372046933,
Can you try the workaround mention on similar thread [#21461](https://github.com/tensorflow/tensorflow/issues/21461#issuecomment-430449910).Let us know if that helps. Thanks!

**Comment by gadagashwini** [comment]
@372046933, Once you build the Tensorflow wheel. you need to install the wheel package with pip. 

```
bazel build [--config=option] //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

pip install /tmp/tensorflow_pkg/tensorflow-version-tags.whl
```

**Comment by 372046933** [comment]
@gadagashwini . Yes, here is what I executed:
```
./bazel-bin/external/org_tensorflow/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```
The following error occurred 
```
Wed Apr 6 10:41:47 CST 2022 : === Preparing sources in dir: /tmp/tmp.C0MooMsKIF
Could not find bazel-bin.  Did you run from the root of the build tree?
```

**Comment by mihaimaruseac** [comment]
Do you have a minimal example of your repo and how are you referring to TF's wheel?

You'll need a bazel `genrule` that would depend on the `build_pip_package` target and then builds the wheel. Use this as the base rule in your repo

**Comment by mihaimaruseac** [comment]
If you are building a target from an external repo you have to use `@` syntax.

I think this is more and more becoming an issue for Bazel, not TF. There's no breakage that can be root caused to TF itself.

**Comment by 372046933** [comment]
Did we come to a conclusion that it's not possible to build TF wheel in an external repo currently?

**Comment by mihaimaruseac** [comment]
No, it is possible to build it. See recommendation in https://github.com/tensorflow/tensorflow/issues/55505#issuecomment-1112731813

**Comment by 372046933** [comment]
Could you give an example? Found that `genrule` does not have `deps` attribute. I did not know how to  depend on `build_pip_package` and then build a wheel

**Comment by mihaimaruseac** [comment]
Yes, `genrule` does not have `deps` but has `tools` which is the list of deps needed to run the genrule.

Try something like

```
genrule(
    name = "tf_wheel",
    outs = ["tensorflow.whl"],
    cmd = "$(location build_pip_package) >$@",
    tools = ["@org_tensorflow//tensorflow/tools/pip_package:build_pip_package"],
)
```

**Comment by 372046933** [comment]
Seems that `@org_tensorflow//tensorflow/tools/pip_package:build_pip_package` is not visible from external project. 

```
ERROR: /xxx/yyy/BUILD:330:8: in genrule rule //:tf_wheel: target '@org_tensorflow//tensorflow/tools/pip_package:build_pip_package' is not visible from target '//:tf_wheel'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//:tf_wheel' failed; build aborted: Analysis of target '//:tf_wheel' failed
```

**Comment by mihaimaruseac** [comment]
Will send a patch to make it visible

**Comment by mihaimaruseac** [comment]
Can you try now, after syncing to the above commit?

**Comment by 372046933** [comment]
Copy `genrule` from  the above comment. https://github.com/tensorflow/tensorflow/issues/55505#issuecomment-1114333283
Build results in the following error.
```
ERROR: /xxx/yyy/BUILD:330:8: in cmd attribute of genrule rule //:tf_wheel: label '//:build_pip_package' in $(location) expression is not a declared prerequisite of this rule
ERROR: /xxx/yyy/BUILD:330:8: Analysis of target '//:tf_wheel' failed
ERROR: Analysis of target '//:tf_wheel' failed; build aborted: 
```

**Comment by mihaimaruseac** [comment]
You shouldn't have `//:build_pip_package` anywhere in your code.

**Comment by 372046933** [comment]
My workspace does not have `build_pip_package` target. 
`genrule`:
```
genrule(
    name = "tf_wheel",
    outs = ["tensorflow.whl"],
    cmd = "$(location build_pip_package) >$@",
    tools = ["@org_tensorflow//tensorflow/tools/pip_package:build_pip_package"],
)
```
Build command:
```
bazel build --config=native_arch_linux --config=cuda :tf_wheel
```

I didn't understand the following error message
```
ERROR: /xxx/yyy/BUILD:330:8: in cmd attribute of genrule rule //:tf_wheel: label '//:build_pip_package' in $(location) expression is not a declared prerequisite of this rule
```

**Comment by mihaimaruseac** [comment]
I think this might be a Bazel bug, not TF. So, maybe try to simplify all of this and open a bug on Bazel repo, as they might have much more context.

Or, let's step a step back. Why do you want to build the wheel from within Bazel?

**Comment by 372046933** [comment]
> Why do you want to build the wheel from within Bazel?

Did you mean build the wheel within TF? Because I did build the wheel with bazel. When it comes to why I build TF wheel outside of TF repository, because my project directly depends on `org_tensorflow`. If TF wheel can be build inside my project. It's more convenient.

**Comment by mihaimaruseac** [comment]
Unassigning since as of this week I no longer work within TF.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
