### ISSUE TITLE
RFE tensorflow-aarch64==2.6.0 build ?

### ISSUE THREAD

**Issue by torehl** [tensorflow/tensorflow#55513]
**System information**
 TensorFlow version (you are using):  2.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Brainchip Akida AKD1000 SNN neuromorphic MetaTF SDK support 2.6.0 on x86_64. They claim support for aarch64, but when creating a virtualenv it fails on aarch64 due to lacking tensorflow-aarc64==2.6.0 build.

**Will this change the current api? How?**

NA

**Who will benefit with this feature?**

Customer of Brainchip Akida who run on Arm64 platforms.

**Any Other info.**

https://doc.brainchipinc.com/installation.html

**Comment by gadagashwini** [comment]
@torehl, Can you try the instructions mentioned [here](https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel). While building you fetch Git branch 2.6 and build the Tensorflow. Thanks!
