### ISSUE TITLE
Inconsistent behavior for variables_collections and outputs_collections parameters (contrib/layers)

### ISSUE THREAD

**Issue by vonclites** [tensorflow/tensorflow#5551]
Using layers from contrib,
- The outputs_collections parameter accepts either a string or list of strings.
- The variables_collections parameter requires a list of strings.

Granted, the documentation does specify this
```
variables_collections: optional list of collections for all the variables or
      a dictionay containing a different list of collection per variable.
outputs_collections: collection to add the outputs.
```
But I don't think it's very obvious.  Furthermore, is it really necessary to have these two parameters behave differently?

The variables_collections parameter is passed to the model_variable function()
Currently, the model_variable() function performs this before creating the variable:
```
  collections = list(collections or [])
  collections += [ops.GraphKeys.VARIABLES, ops.GraphKeys.MODEL_VARIABLES]
```
So, if
```
# variables_collections = 'kernels'
collections
['k', 'e', 'r', 'n', 'e', 'l', 's']
```

Whereas, for outputs_collections it uses the utils.collect_named_outputs() function, wherein
```
# variables_collections = 'kernels'
names = (names,) if isinstance(names, six.string_types) else set(names)
names
('kernels',)
```

Perhaps the behavior of these two parameters should be unified?

**Comment by martinwicke** [comment]
This is a bug. Thanks for reporting.

**Comment by martinwicke** [comment]
The outputs_collections behavior is clearly the correct one. Both arguments should accept the same types of input, that is, either strings or set types.

**Comment by martinwicke** [comment]
We chose not to include the collections arguments when we ported the layers to core. 

When using the core layers: If you need access to the variables, use the scope. If you want to add the activations to a collection, do that using the returned tensor.

I'm closing this, since the contrib layers are being deprecated in favor of those in core.

**Comment by Robomate** [comment]
the bug still exists in tf.contrib.layers.batch_norm(variables_collections=['vars'], outputs_collections='vars2'). If you do just variables_collections='vars' it will return an empty list. Annoying if you do not know this thread.

**Comment by vonclites** [comment]
Pretty sure it's not just batch_norm.
