### ISSUE TITLE
Tensorflow for M1 mac

### ISSUE THREAD

**Issue by akshatmanohar21** [tensorflow/tensorflow#55519]
I have a macbook air m1. I am trying to use tensorflow (for darkflow) in my mac. I need to get tensorflow 1.13.2 but brew and conda always installs the latest version. Now it gives me error ' tensorflow.contrib' not found as it was removed in 1.14. 

I am importing this: 'from darkflow.net.build import TFNet'

Could someone please explain what commands to replace for the new version.

**Comment by chunduriv** [comment]
@akshatmanohar21,

You can follow below commands below to install Tensorflow=1.13.2

```
brew install python3
python3 -m vent tf
source tf/bin/activate
python3 -m pip install -U pip
pip install tensorflow==1.13.2
```
