### ISSUE TITLE
I would like to ask how to save the personalization model during training on device

### ISSUE THREAD

**Issue by YourPeer** [tensorflow/tensorflow#55527]
I would like to ask how to save the personalization model during training on device. If this personalization model can be used for transmission, it may be possible to implement federated learning for user privacy and security, and I would like to ask if this feature is supported or will be supported soon.

**Comment by tilakrayal** [comment]
@YourPeer ,
 In order to expedite the trouble-shooting process, I request you to please provide a minimal code snippet and the TensorFlow version you are using.Thanks!
