### ISSUE TITLE
tflite gpu_delegate "undefined symbol: glFenceSync"

### ISSUE THREAD

**Issue by BenjaminWegener** [tensorflow/tensorflow#55522]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04 arm64
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.8.0
- Python version: 3.10
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Mali G72

**Describe the current behavior**
i compiled tflite from source to test the gpu / gl delegate in python with
`bazel build -s -c opt --copt "-DEGL_NO_X11" --copt="-DMESA_EGL_NO_X11_HEADERS" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so`

tflite inference and training works without loading the delegate, uses xnnpack delegate for cpu

if loading the gpu delegate, i get following error:
OSError: /home/linux/Documents/libtensorflowlite_gpu_delegate.so: undefined symbol: glFenceSync
**UPDATE: the loading takes places via following code:
`delegate = tf.lite.experimental.load_delegate('./libtensorflowlite_gpu_delegate.so')`
the error is exactly following:
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_24874/1769046455.py in <module>
----> 1 delegate = tf.lite.experimental.load_delegate('./libtensorflowlite_gpu_delegate.so')
      2 model = tf.lite.Interpreter(model_content=tflite_model, experimental_delegates=[delegate])
      3 
      4 model.allocate_tensors()
      5 infer = generator_lite.get_signature_runner("infer")

~/.local/lib/python3.10/site-packages/tensorflow/lite/python/interpreter.py in load_delegate(library, options)
    173   """
    174   try:
--> 175     delegate = Delegate(library, options)
    176   except ValueError as e:
    177     raise ValueError('Failed to load delegate from {}\n{}'.format(

~/.local/lib/python3.10/site-packages/tensorflow/lite/python/interpreter.py in __init__(self, library, options)
     81                          'due to missing immediate reference counting.')
     82 
---> 83     self._library = ctypes.pydll.LoadLibrary(library)
     84     self._library.tflite_plugin_create_delegate.argtypes = [
     85         ctypes.POINTER(ctypes.c_char_p),

/usr/lib/python3.10/ctypes/__init__.py in LoadLibrary(self, name)
    450 
    451     def LoadLibrary(self, name):
--> 452         return self._dlltype(name)
    453 
    454     __class_getitem__ = classmethod(_types.GenericAlias)

/usr/lib/python3.10/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

`OSError: ./libtensorflowlite_gpu_delegate.so: undefined symbol: glFenceSync`
--> This is on Ubuntu 22.04 arm64
--> on Ubuntu 22.04 x64 the Error is:
`OSError: ./libtensorflowlite_gpu_delegate.so: undefined symbol: glDeleteBuffers` 
**

**Describe the expected behavior**
should work with gpu delegate?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by BenjaminWegener** [comment]
https://github.com/tensorflow/tensorflow/issues/45953

**Comment by mohantym** [comment]
Hi @BenjaminWegener ! 
Sorry for the late response.  I see the issue is happening when you are loading libtensorflowlite_gpu_delegate.so (built using bazel in linux system).  Can you try below steps and let us know ?
1. Install opengl dependencies in terminal 
```
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
sudo apt-get install mesa-utilsglxinfo | grep -i opengl

```
3. Rebuild the gpu_delegate file  (Removed .so as you are not doing inference in C++ ,added monolthic as your are on pc )
4. 
`bazel build  --config=monolithic -c opt --copt "-DEGL_NO_X11" --copt="-DMESA_EGL_NO_X11_HEADERS" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate`

5. put the full path of library containing libtensorflowlite_gpu_delegate.so in this line

`delegate = tf.lite.experimental.load_delegate('./libtensorflowlite_gpu_delegate)`

Attaching relevant[ thread](https://review.mlplatform.org/plugins/gitiles/ml/armnn/+/86723e67a940ed9f288c3cb59c120b9a10a1d590/delegate/IntegrateDelegateIntoPython.md) for reference. Thanks!

**Comment by BenjaminWegener** [comment]
Thanks for your response, that thread you attached looks promising.
leaving the ".so" from the command line yields following:
`INFO: Found applicable config definition build:dynamic_kernels in file /home/linux/Documents/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: Skipping 'tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate': no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate': target 'libtensorflowlite_gpu_delegate' not declared in package 'tensorflow/lite/delegates/gpu' (did you mean 'libtensorflowlite_gpu_delegate.so'?) defined by /home/linux/Documents/tensorflow/tensorflow/lite/delegates/gpu/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate': target 'libtensorflowlite_gpu_delegate' not declared in package 'tensorflow/lite/delegates/gpu' (did you mean 'libtensorflowlite_gpu_delegate.so'?) defined by /home/linux/Documents/tensorflow/tensorflow/lite/delegates/gpu/BUILD
INFO: Elapsed time: 0.370s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
`

**Comment by BenjaminWegener** [comment]
step 3 produces the output mentioned in https://github.com/tensorflow/tensorflow/issues/55522#issuecomment-1091672405

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by impjdi** [comment]
I don't think you can drop ".so".  You need to build "tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so" AFAIK

**Comment by BenjaminWegener** [comment]
@impjdi @sachinprasadhs @mohantym i built it again from 2.9 sources and even tested with tflite_runtime from pipy, same result. `undefined symbol: glFenceSync`
I guess there are two possibilities:
-missing library during build (android doesnt need gles libs for example)
-some error in the load_delegate function

I will dive deeper into it, during the weekend.

**Comment by impjdi** [comment]
Sorry, I'm not too familiar with lib.so setup; I only use statically linked binaries.  In fact, I never got dynamically linked libraries to work with Bazel; I remember I gave up after a couple weeks of trying.

`undefined symbol: glFenceSync` is a linker error, so linking is failing due to not finding EGL / GLES libraries.

**Comment by BenjaminWegener** [comment]
@impjdi thanks for the tip in the right direction. i managed to build it and load it up in python using tflite_runtime. the needed patches were
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/9721986c8289c3fce9642526ef7bb799ade5466e
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/b1fcd1b51c039fca0408eccf49cea77d3bbee2c5

there is a build.sh for arm64 debian, there you can see the build options.
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/blob/tflite_gpu_python/build_gpudelegate_debianArm64.sh
i have to test it tomorrow, reporting back soon, so i am closing this due to the fact the problem is resolved.

**Comment by BenjaminWegener** [comment]
https://github.com/tensorflow/tensorflow/issues/22
