### ISSUE TITLE
[docs] python3 bytes -> string in example in README

### ISSUE THREAD

**Issue by dgoerger** [tensorflow/tensorflow#5552]
The current README.md indicates the following "first TensorFlow program":

```
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> sess.run(hello)
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> sess.run(a+b)
42
>>>
```

This works fine under python2, but handling of strings has [changed slightly in python3](http://stackoverflow.com/a/6269785). Suggested improvement to the example program for compatibility with both python2 and python3 (we need to [convert bytes to string](http://stackoverflow.com/a/606199)):

```
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> sess.run(hello).decode("utf-8")
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> sess.run(a+b)
42
```

Tested from the [wheel build](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#virtualenv-installation) of 0.11.0 (final), [converted to RPM](https://copr.fedorainfracloud.org/coprs/dgoerger/yale-zoo/package/python-tensorflow/), on Fedora 24/25.

Thanks!

**Comment by sherrym** [comment]
@dgoerger would you like to send a PR? Thanks.

**Comment by girving** [comment]
@dgoerger What is the error message you see with the current version?

**Comment by dgoerger** [comment]
Hmm. Further testing suggests this may be more serious than I'd thought. Type inconsistency, not just documentation.

```
$ python3
>>> type('Hello, TensorFlow!')
<class 'str'>
>>> type(tf.constant('Hello, TensorFlow!'))
<class 'tensorflow.python.framework.ops.Tensor'>
>>> type(tf.Session().run(tf.constant('Hello, TensorFlow!')))
<class 'bytes'>
```

According to [the docs](https://www.tensorflow.org/versions/master/api_docs/python/client.html#Session.run), input type Tensor outputs via numpy ndarray, which appears not to output type string. Reformatting Session.run(Tensor) when output type is bytes, to new output type string, might give the intended behaviour here. Compare non-ASCII:

```
$ python3
>>> import tensorflow, sys
>>> type('¿Cómo se ve?')
<class 'str'>
>>> type(tensorflow.constant('¿Cómo se ve?'))
<class 'tensorflow.python.framework.ops.Tensor'>
>>> type(tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')))
<class 'bytes'>
>>> type(tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')).decode(sys.getdefaultencoding()))
<class 'str'>
>>> tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?'))
b'\xc2\xbfC\xc3\xb3mo se ve?'
>>> tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')).decode(sys.getdefaultencoding())
'¿Cómo se ve?'
```

... and of course the same doesn't work on python2:

```
$ python2
>>> import tensorflow, sys
>>> type('¿Cómo se ve?')
<type 'str'>
>>> type(tensorflow.constant('¿Cómo se ve?'))
<class 'tensorflow.python.framework.ops.Tensor'>
>>> type(tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')))
<type 'str'>
>>> type(tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')).decode(sys.getdefaultencoding()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
>>> # yikes, python2 default encoding is ascii
>>> type(tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')).decode('utf-8'))
<type 'unicode'>
>>> tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?'))
'\xc2\xbfC\xc3\xb3mo se ve?'
>>> tensorflow.Session().run(tensorflow.constant('¿Cómo se ve?')).decode('utf-8')
u'\xbfC\xf3mo se ve?'
```

So I guess fixing this discrepancy will require evaluating what type object should be output by tensorflow.Session().run(Tensor(string)). On the other hand, is it possible non-ASCII doesn't work at all under the current Session.run() python2 implementation? The python2 output seems non-ideal, but maybe I'm missing a common trick.

**Comment by girving** [comment]
TensorFlow converts `str` to `bytes` in most places, including `sess.run`, and this is unlikely to change.  The user is free to convert back, but unfortunately it's too large a change to add a unicode dtype to the core.  Closing as won't fix for now.

**Comment by erwa** [comment]
For the record, it's useful to use

```
from tensorflow.python.util import compat

compat.as_bytes(...)
compat.as_text(...)
```

to do the conversions between bytes and string when needed.
