### ISSUE TITLE
Bullet Points missing

### ISSUE THREAD

**Issue by devendra-rgb** [tensorflow/tensorflow#55532]
![image](https://user-images.githubusercontent.com/63838746/162250635-d3786b74-37f7-417d-855b-7c5647b7f4f1.png)

**Comment by devendra-rgb** [comment]
the bullets points are visible only if the sentence has any special character

**Comment by sushreebarsa** [comment]
@devendra-rgb 
In order to expedite the trouble-shooting process here,could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by devendra-rgb** [comment]
Hey sushreebarsa the isse is that the in markup language the points are written but they are not showing in preview if we are appending any special characters to the sentence it is working 

this is the normal one 
![image](https://user-images.githubusercontent.com/63838746/162252398-6ba0d69d-e9c8-4666-9c2e-068bbb513a34.png)
![image](https://user-images.githubusercontent.com/63838746/162252458-f5c0dfff-f921-40a7-83b9-2267ebc6ab10.png)

after adding space it is like this 

![image](https://user-images.githubusercontent.com/63838746/162252667-9ca74204-a0a7-4980-bafb-b66f5e28c8a4.png)


![image](https://user-images.githubusercontent.com/63838746/162252710-2f1f80d1-3165-4e6d-9d56-9acfc04fad29.png)

**Comment by mihaimaruseac** [comment]
These are just placeholders, have no significance in the rich text editor
