### ISSUE TITLE
Test fail on r2.8: core:__tensorflow_core_lib_math_math_util_test   

### ISSUE THREAD

**Issue by awf** [tensorflow/tensorflow#55530]
EDIT: PR fixing this issue is https://github.com/tensorflow/tensorflow/pull/55730

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.8.0-2-ge994fb9c3ad 2.8.0
- Python version: 3.8.3
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

test fails

**Describe the expected behavior**

test passes

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

[EDIT: Removed incorrect hypothesis]

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
$ git checkout r2.8
$ bazel  --host_jvm_args=-Xmx32g test --jobs=12  --config=dbg --verbose_failures -k //tensorflow/core:__tensorflow_core_lib_math_math_util_test   
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

[test.log](https://github.com/tensorflow/tensorflow/files/8443281/t.log)

**Comment by awf** [comment]
Update: 
test still fails on commit `55645ca964508507890529a71591f51a344a6356` April 9

test passes with ``--config=opt``

**Comment by sushreebarsa** [comment]
@awf
Please let us know if this issue is resolved for you in a recent commit ?Thanks!

**Comment by awf** [comment]
Note I'm happy to submit a PR, but there are a few options, as listed above, so seeking guidance on which one to implement.

**Comment by awf** [comment]
PR fixing this issue is #55730
