### ISSUE TITLE
Adding Select Tf Ops to Cmake

### ISSUE THREAD

**Issue by CaptainDario** [tensorflow/tensorflow#55536]
**System information**
- TensorFlow version (you are using): any
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.** 
Currently one has to decide between using Select TF ops with bazel or GPU support with CMake.
It would be nice if either bazel has an option to support GPU on any OpenCL system or CMake can build with TF Ops.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everybody who wants to use GPU acceleration and TF Ops.

**Comment by noahgould** [comment]
Hello, wanted to comment that I have a use case where we want to compile tflite with CMake and use the flex delegate. This would be great if support could be added.

**Comment by mohantym** [comment]
Hi @CaptainDario !
Could you build the select ops library using bazel and link it in target_link_libraries.
#Bazel command to build tensorflowlite_flex library

`bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex
`#Sample CMake snippet

```
add_executable(minimal minimal.cpp)
target_link_libraries(minimal tensorflowlite tensorflowlite_flex)
```
[Reference](https://github.com/tensorflow/tensorflow/issues/57822#issuecomment-1257127667)

Thank you!

**Comment by mohantym** [comment]
@CaptainDario !
The above approach did not work in ubuntu ( but works in macos) as per this[ thread](https://github.com/tensorflow/tensorflow/issues/57822#issuecomment-1259494826). 
Keep this feature request open until it is resolved.
Thank you!

**Comment by aflaischer** [comment]
Hi,

I encounter the same issue and I think I found a way to make it work on Linux.
In order to force the link  of tensorflowlite_flex with ld you can use the --no-as-needed option:

```
file(GLOB ${PROJECT_NAME}_EXE_SRC
    src/*.cpp
)

set(TENSORFLOW_SOURCE_DIR "/tensorflow_src" CACHE PATH
  "Directory that contains the TensorFlow project"
)

find_library(TF_LIB tensorflowlite HINTS "${TENSORFLOW_SOURCE_DIR}/bazel-bin/tensorflow/lite/")
find_library(TF_LIB_FLEX tensorflowlite_flex HINTS "${TENSORFLOW_SOURCE_DIR}/bazel-bin/tensorflow/lite/delegates/flex/")

include_directories(
    "${TENSORFLOW_SOURCE_DIR}/"
    "${TENSORFLOW_SOURCE_DIR}/bazel-bin/external/flatbuffers/src/_virtual_includes/flatbuffers/"
)

add_executable(testmodel ${${PROJECT_NAME}_EXE_SRC})
target_link_libraries(testmodel
-Wl,--no-as-needed # Need --no-as-needed to link tensorflowlite_flex
${TF_LIB}
${TF_LIB_FLEX}
)
```

Now the tensorflowlite_flex lib is correctly linked to my bin:
```
root@070699d2a87e:/tmp/tflite_minimal/build# ldd testmodel 
	linux-vdso.so.1 (0x00007ffe2ddc4000)
	libtensorflowlite.so => /tensorflow_src/bazel-bin/tensorflow/lite/libtensorflowlite.so (0x00007f59c0e19000)
	libtensorflowlite_flex.so => /tensorflow_src/bazel-bin/tensorflow/lite/delegates/flex/libtensorflowlite_flex.so (0x00007f59b3de4000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f59b3bfb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f59b3aac000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f59b3a91000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f59b389f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f59b3897000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f59b3874000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f59c137c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f59b386a000)
```

@mohantym maybe it could help you

**Comment by nyadla-sys** [comment]
I have build tensorflowlite_flex lib as below using bazel command:
**bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex**
Followed as you mentioned above and it worked for me.!
diff --git a/tensorflow/lite/examples/minimal/CMakeLists.txt b/tensorflow/lite/examples/minimal/CMakeLists.txt
index 7f8301162bb..1dd8ae05089 100644
--- a/tensorflow/lite/examples/minimal/CMakeLists.txt
+++ b/tensorflow/lite/examples/minimal/CMakeLists.txt
@@ -35,10 +35,14 @@ add_subdirectory(
   EXCLUDE_FROM_ALL
 )
 
+find_library(TF_LIB_FLEX tensorflowlite_flex HINTS "${TENSORFLOW_SOURCE_DIR}/bazel-bin/tensorflow/lite/delegates/flex/")
+
 set(CMAKE_CXX_STANDARD 17)
 add_executable(minimal
   minimal.cc
 )
 target_link_libraries(minimal
+  -Wl,--no-as-needed # Need --no-as-needed to link tensorflowlite_flex
   tensorflow-lite
+  ${TF_LIB_FLEX}
 )

**Comment by mohantym** [comment]
Hi @aflaischer @nyadla-sys !
Thanks for confirming the same and providing your inputs. It would be great to have a PR from your side  to update the CMake documentation to support flex delegate feature.

@CaptainDario !
Could you confirm from your side too. 
Thank you!

**Comment by CaptainDario** [comment]
@mohantym somehow I did not notice your ping. I am still interested in this.
I do not fully understand how the mentioned solution is supposed to work.
Could you give me step-by-step instructions? One cannot just build using CMake?
Something like this is not possible, right?

```bash
cmake --build . -j -t select_ops
```
