### ISSUE TITLE
TensorFlow Dataset has not correct shape

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#55546]
Hi,
   I think the issue here is from the dataset, which doesn't populate the shape info for the sequence dim.

  It is becouse print(dataset) gives me:
`<ZipDataset element_spec=(TensorSpec(shape=(None, None, 25, 81), dtype=tf.float64, name=None), TensorSpec(shape=(None, None, 25, 1), dtype=tf.float64, name=None))> `.

The model knows from the dataset object only the last two axis, but I need to it knows the last 3 axis. 
The shape must be defined for example: `shape=(None, 7, 25, 81)` or `shape=(None, 7, 25, 1)`.

Thanks. 

## System information
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.3 / Debian 5.10.70-1 (2021-09-30)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0 / 2.9.0-dev20220329
- Python version: Python 3.9.7 / Python 3.9.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): Clang 11.1.0 / GCC 10.2.1
- CUDA/cuDNN version: No
- GPU model and memory: Apple M1, 16GB / No

## Code
```python
from tensorflow.keras.layers import Dense, Dropout, Layer, Input
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.models import Model

import tensorflow as tf
import numpy as np

class PositionalEmbedding(Layer):
    def __init__(self, units, dropout_rate, **kwargs):
        super(PositionalEmbedding, self).__init__(**kwargs)

        self.units = units

        self.projection = Dense(units, kernel_initializer=TruncatedNormal(stddev=0.02))
        self.dropout = Dropout(rate=dropout_rate)

    def build(self, input_shape):
        super(PositionalEmbedding, self).build(input_shape)

        print(input_shape, '\n')
        self.position = self.add_weight(
            name="position",
            shape=(1, input_shape[1], input_shape[2], self.units),
            initializer=TruncatedNormal(stddev=0.02),
            trainable=True,
        )

    def call(self, inputs, training):
        x = self.projection(inputs)
        x += self.position

        return self.dropout(x, training=training)

class Transformer(Model):
    def __init__(
        self,
        embed_dim,
        dropout_rate,
        **kwargs
    ):
        super(Transformer, self).__init__(**kwargs)

        # Input
        self.pos_embs = PositionalEmbedding(embed_dim, dropout_rate)

    def compile(self, optimizer, loss):
        super(Transformer, self).compile()
        self.optimizer = optimizer
        self.loss = loss

    def call(self, inputs, training):
        inputs, targets = inputs
        
        return self.pos_embs(inputs, training=training)

    def train_step(self, inputs):
        inputs, targets = inputs

        print(inputs.shape)
        print(targets.shape, '\n')

        targets_inputs = targets[:, :-1]
        targets_real = targets[:, 1:]

        with tf.GradientTape() as tape:
            y_pred = self([inputs, targets_inputs], training=True)
            loss = self.loss(targets_real, y_pred)

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        return {
            "loss": loss,
        }

def load_dataset(batch_size, window_size):
  x_all = np.ones((1000, 25, 81)) #np.load('./dataset/X_all.npy')
  y_all = np.ones((1000, 25, 1)) #np.load('./dataset/y_all.npy')

  inputs_dataset = tf.keras.preprocessing.timeseries_dataset_from_array(
      x_all, None, sequence_length=window_size, sequence_stride=(window_size // 2), batch_size=batch_size)
  targets_dataset = tf.keras.preprocessing.timeseries_dataset_from_array(
      y_all, None, sequence_length=window_size, sequence_stride=(window_size // 2), batch_size=batch_size)

  return inputs_dataset, targets_dataset



# load dataset
inputs_dataset, targets_dataset = load_dataset(
      batch_size=64,
      window_size=7,
)
dataset = tf.data.Dataset.zip((inputs_dataset, targets_dataset))

for batch in dataset:
    inputs, targets = batch
    print(inputs.shape)
    print(targets.shape, '\n')
    break

sample_transformer = Transformer(
    embed_dim=256, dropout_rate=0.1,
)

sample_transformer.compile(
      loss=tf.keras.losses.mean_squared_error,
      optimizer=tf.keras.optimizers.Adam(),
)

# Train model
sample_transformer.fit(
      dataset,
      epochs=10
)
```

**Comment by tilakrayal** [comment]
Hello @markub3327 ,
I tried to execute the given code snippet, I am facing different error stating. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/773ef1a7f6105767925cd885691e4c21/untitled296.ipynb).

**Comment by markub3327** [comment]
@tilakrayal 

It's the same error as I saw. 
```shell
ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "<ipython-input-1-75c76593a629>", line 66, in train_step
        y_pred = self([inputs, targets_inputs], training=True)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "transformer" (type Transformer).
    
    in user code:
    
        File "<ipython-input-1-75c76593a629>", line 54, in call  *
            return self.pos_embs(inputs, training=training)
        File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "<ipython-input-1-75c76593a629>", line 25, in build
            trainable=True,
    
        ValueError: Can't convert Python sequence with mixed types to Tensor.
    
    
    Call arguments received:
      • inputs=['tf.Tensor(shape=(None, None, 25, 81), dtype=float32)', 'tf.Tensor(shape=(None, None, 25, 1), dtype=float32)']
      • training=True
```

The problem is with `print(dataset)` that gives me:
  ` <ZipDataset element_spec=(TensorSpec(shape=(None, None, 25, 81), dtype=tf.float64, name=None), TensorSpec(shape=(None, None, 25, 1), dtype=tf.float64, name=None))>`

And I need to propagate the last 3 dims from Dataset to model during build process.
More info about this you found here: https://github.com/keras-team/keras/issues/16315

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/b448144440cb53b755f6c58d7ddc6e1c/16315.ipynb).

**Comment by aaudiber** [comment]
It looks like `tf.keras.preprocessing.timeseries_dataset_from_array` builds the sequences in such a way that their length can't be inferred automatically. If the second dimension is guaranteed to be equal to the sequence length, you can use [ensure_shape](https://www.tensorflow.org/api_docs/python/tf/ensure_shape) to communicate the knowledge to the shape inference system:

```python
targets_dataset = tf.keras.preprocessing.timeseries_dataset_from_array(
      y_all, None, sequence_length=window_size, sequence_stride=(window_size // 2), batch_size=batch_size)
# Set the shape for the elements of the dataset.
targets_dataset = targets_dataset.map(lambda x: tf.ensure_shape(x, <expected shape>)
```

@fchollet would it make sense for `timeseries_dataset_from_array` to call `ensure_shape` for the elements produced by `timeseries_dataset_from_array`?

**Comment by markub3327** [comment]
@fchollet Is it a true solution? Can I rely this solution?

I need it know with academical precision.

Thanks.

**Comment by gowthamkpr** [comment]
@markub3327 Can you please create an issue in [Keras repo](https://github.com/keras-team/keras/issues/new/choose) as all the Keras issues are tracked separately in keras repo. Thanks!

**Comment by markub3327** [comment]
@gowthamkpr 

In Keras this issue exists, it's [here](https://github.com/keras-team/keras/issues/16315). Please re-open it.

Thanks.

**Comment by gowthamkpr** [comment]
@markub3327  I reopened the issue. Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
