### ISSUE TITLE
GPU-enabled Mac build of TensorFlow version 0.11.0rc2-py2 was compiled against cuDNN v5.1

### ISSUE THREAD

**Issue by dtrebbien** [tensorflow/tensorflow#5555]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
This is a regression of issue #3826.

### Environment info
Operating System: macOS Sierra Version 10.12.1 (16B2555)

Installed version of CUDA and cuDNN: cuda_8.0.47_mac, cudnn-8.0-osx-x64-v5.1 (I explain why I am using cuDNN v5.1 rather than cuDNN v5 below.)
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
lrwxr-xr-x  1 root  admin     13 Nov 11 17:13 /usr/local/cuda/lib/libcuda.1.dylib -> libcuda.dylib
-rwxr-xr-x@ 1 root  wheel  13504 Sep 26 17:59 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x@ 1 root  wheel     45 Sep 26 18:00 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root  wheel     50 Sep 26 18:00 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x@ 1 root  wheel     46 Sep 26 18:00 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x@ 1 root  wheel     49 Sep 26 18:00 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
lrwxr-xr-x  1 root  admin     47 Nov 11 17:29 /usr/local/cuda/lib/libcudnn.5.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  admin     45 Nov 11 17:29 /usr/local/cuda/lib/libcudnn.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.dylib
lrwxr-xr-x  1 root  admin     48 Nov 11 17:29 /usr/local/cuda/lib/libcudnn_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: `export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0rc2-py2-none-any.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.dylib locally
0.11.0rc2
```

If installed from source: Not Applicable

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
1. Set up TensorFlow according to the instructions at  
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#prepare_environment_for_mac_os_x

    In particular, the page says to install cuDNN v5 from the cuDNN Download page.
2. Test the installation by running:

        cuda-memcheck python -m tensorflow.models.image.mnist.convolutional

    You should see:

    > E tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

### What other attempted solutions have you tried?
Uninstalling cuDNN v5 and installing cuDNN v5.1 (labeled "cuDNN v5.1 (August 10, 2016), for CUDA 8.0" on the cuDNN Download page) fixes the issue.

As before in issue #3826, the installation instructions should be corrected to specify that cuDNN v5.1 needs to be installed.

**Comment by gunan** [comment]
cc @yifeif 

Will update the docs,
Which documentation have you been using specificly?

**Comment by dtrebbien** [comment]
I was following:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#prepare_environment_for_mac_os_x

The master version of these docs appear to be the same:
https://www.tensorflow.org/versions/master/get_started/os_setup.html#prepare_environment_for_mac_os_x

**Comment by gunan** [comment]
@yifeif, did we update the documentation about this one?

**Comment by yifeif** [comment]
Updated the instruction at #6407. Should be up on the website tomorrow.
