### ISSUE TITLE
Tensorflow ERROR - Testing a linear regression model using TensorFlow

### ISSUE THREAD

**Issue by NathFarinha237** [tensorflow/tensorflow#55564]
I'm trying to resolve an error in tensoflow but I can't understand what the error is. I can't understand what the type [('resource', 'u1')] is and what that means.
I am studying the book Mastering OpenCV 4 with Python by the author Alberto Fernandez Villan, but the code is outdated, I have already updated everything according to version 2.8 of tensorflow, but now this error appears. can you help me? Here is the complete code and the error.

numpy version: 1.22.3
tensorflow version: 2.8.0

-------------------------------------------------------------------------------------

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
tf.compat.v1.disable_eager_execution()

# Number of points:
N = 50

# Make random numbers predictable:
np.random.seed(101)
tf.compat.v1.set_random_seed(101)

# Generate random data composed by 50 (N = 50) points:
x = np.linspace(0, N, N) #float64
y = 3 * np.linspace(0, N, N) + np.random.uniform(-10, 10, N) #float64

# Number of points to predict:
M = 3

# Define 'M' more points to get the predictions using the trained model:
new_x = np.linspace(N + 1, N + 10, M) #float64

# Restore the model.
# First step when loading a model is to load the graph from '.meta':
tf.compat.v1.reset_default_graph()
imported_meta = tf.compat.v1.train.import_meta_graph("linear_regression.meta")

# The second step when loading a model is to load the values of the variables:
# Note that values only exist within a session
with tf.compat.v1.Session() as sess:
    imported_meta.restore(sess, './linear_regression')
    # Run the model to get the values of the variables W, b and new prediction values:
    W_estimated = sess.run('W:0')
    b_estimated = sess.run('b:0')
    new_predictions = sess.run(['y_model:0'], {'X:0': new_x}) #[array([153.04472, 166.54755, 180.05037], dtype=float32)]
    print(W_estimated.dtype)
    print(b_estimated.dtype)

# Reshape for proper visualization:
new_predictions = np.reshape(new_predictions, (M, -1)) #float32

# Calculate the predictions:
predictions = W_estimated * x + b_estimated

# Create the dimensions of the figure and set title:
fig = plt.figure(figsize=(12, 5))
plt.suptitle("Linear regression using TensorFlow", fontsize=14, fontweight='bold')
fig.patch.set_facecolor('silver')

# Plot training data:
plt.subplot(1, 3, 1)
plt.plot(x, y, 'ro', label='Original data')
plt.xlabel('x')
plt.ylabel('y')
plt.title("Training Data")
plt.legend()

# Plot results:
plt.subplot(1, 3, 2)
plt.plot(x, y, 'ro', label='Original data')
plt.plot(x, predictions, label='Fitted line')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Linear Regression Result')
plt.legend()

# Plot new predicted data:
plt.subplot(1, 3, 3)
plt.plot(x, y, 'ro', label='Original data')
plt.plot(x, predictions, label='Fitted line')
plt.plot(new_x, new_predictions, 'bo', label='New predicted data')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Predicting new points')
plt.legend()

# Show the Figure:
plt.show()

---------------------------------------------------------------------------------
ERROR: line 51, in <module>predictions = W_estimated * x + b_estimated
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype([('resource', 'u1')]), dtype('float64')) -> None

**Comment by NathFarinha237** [comment]
Updated training code that works.
Required for the test code that shows an error to work.
----------------------------------------------------------------------------------
# Training a linear regression model using TensorFlow
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

tf.compat.v1.disable_eager_execution() # sugestão encontrada na internet para evitar erro

# Path to the folder that we want to save the logs for Tensorboard:
logs_path = "./logs"
# Number of points:
N = 50

# Make random numbers predictable:
np.random.seed(101)
tf.compat.v1.set_random_seed(101)

# Generate random data composed by 50 (N = 50) points:
x = np.linspace(0, N, N)
y = 3 * np.linspace(0, N, N) + np.random.uniform(-10, 10, N)

# You can check the shape of the created training data:
print(x.shape)
print(y.shape)

# Create the placeholders in order to feed our training examples into the optimizer while training:
X = tf.compat.v1.placeholder("float", name='X')
Y = tf.compat.v1.placeholder("float", name='Y')

# Declare two trainable TensorFlow Variables for the Weights and Bias
# We are going to initialize them randomly. Another way can be to set '0.0':
W = tf.Variable(np.random.randn(), name="W")
b = tf.Variable(np.random.randn(), name="b")

# Define the hyperparameters of the model:
learning_rate = 0.01
training_epochs = 1000

# This will be used to show results after every 25 epochs:
disp_step = 100

# Construct a linear model:
y_model = tf.add(tf.multiply(X, W), b, name="y_model")

# Define cost function, in this case, the Mean squared error
# (Note that other cost functions can be defined)
cost = tf.reduce_sum(tf.pow(y_model - Y, 2)) / (2 * N)

# Create the gradient descent optimizer that is going to minimize the cost function modifying the
# values of the variables W and b:
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initialize all variables:
init = tf.compat.v1.global_variables_initializer()

# Create a Saver object:
saver = tf.compat.v1.train.Saver()

# Start the training procedure inside a TensorFlow Session:
with tf.compat.v1.Session() as sess:
    # Run the initializer:
    sess.run(init)

    # Uncomment if you want to see the created graph
    # summary_writer = tf.summary.FileWriter(logs_path, sess.graph)

    # Iterate over all defined epochs:
    for epoch in range(training_epochs):

        # Feed each training data point into the optimizer:
        for (_x, _y) in zip(x, y):
            sess.run(optimizer, feed_dict={X: _x, Y: _y})

        # Display the results every 'display_step' epochs:
        if (epoch + 1) % disp_step == 0:
            # Calculate the actual cost, W and b:
            c = sess.run(cost, feed_dict={X: x, Y: y})
            w_est = sess.run(W)
            b_est = sess.run(b)
            print("epoch {}: cost = {} W = {}  b = {}".format(epoch + 1, c, w_est, b_est))

    # Save the final model
    saver.save(sess, './linear_regression')

    # Storing necessary values to be used outside the session
    training_cost = sess.run(cost, feed_dict={X: x, Y: y})
    weight = sess.run(W)
    bias = sess.run(b)

print("Training finished!")

# Calculate the predictions:
predictions = weight * x + bias

# Create the dimensions of the figure and set title:
fig = plt.figure(figsize=(8, 5))
plt.suptitle("Linear regression using TensorFlow", fontsize=14, fontweight='bold')
fig.patch.set_facecolor('silver')

# Plot training data:
plt.subplot(1, 2, 1)
plt.plot(x, y, 'ro', label='Original data')
plt.xlabel('x')
plt.ylabel('y')
plt.title("Training Data")

# Plot results:
plt.subplot(1, 2, 2)
plt.plot(x, y, 'ro', label='Original data')
plt.plot(x, predictions, label='Fitted line')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Linear Regression Result')
plt.legend()

# Show the Figure:
plt.show()

**Comment by tilakrayal** [comment]
Hello @NathFarinha237 ,
On running the given code snippet, I am facing an error stating `OSError: File does not exist. Received: {filename}`. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/fb61ab0f893d14efb33aa26335ed11ea/untitled297.ipynb).
