### ISSUE TITLE
Build failed: undeclared inclusion(s) in rule '@llvm-project//mlir:GPUTransforms'

### ISSUE THREAD

**Issue by ayaka14732** [tensorflow/tensorflow#55563]
**System information**

- Have I written custom code: No
- OS Platform and Distribution: Ubuntu 20.04.4 LTS x86_64
- TensorFlow version: Latest commit [`55645ca`](https://github.com/tensorflow/tensorflow/commit/55645ca964508507890529a71591f51a344a6356)
- Python version: 3.10.4
- Bazel version (if compiling from source): 5.1.1
- GCC/Compiler version (if compiling from source): 9.4.0
- CUDA/cuDNN version: No CUDA
- GPU model and memory: No GPU

I am trying to build Tensorflow with TPU support on a Cloud TPU VM.

I have successfully built [v2.8.0](https://github.com/tensorflow/tensorflow/tree/v2.8.0) before, but now it shows an error:

```
$ bazel build --config=tpu //tensorflow/tools/pip_package:build_pip_package
...
ERROR: /home/ayaka/.cache/bazel/_bazel_ayaka/daa247f909e330d435159750c8dca57c/external/llvm-project/mlir/BUILD.bazel:3385:11: Compiling mlir/lib/Dialect/GPU/Transforms/SerializeToCubin.cpp failed: undeclared inclusion(s) in rule '@llvm-project//mlir:GPUTransforms':
this rule is missing dependency declarations for the following files included by 'mlir/lib/Dialect/GPU/Transforms/SerializeToCubin.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/mlir/_virtual_includes/GPUBaseIncGen/mlir/Dialect/GPU/GPUOpsDialect.h.inc'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 269.070s, Critical Path: 131.50s
INFO: 3174 processes: 247 internal, 2927 local.
FAILED: Build did NOT complete successfully
```

I am willing to provide more information on this issue.

**Comment by leiteg** [comment]
I am experiencing a similar problem.

```
ERROR: /home/leite/.cache/bazel/_bazel_leite/cc29ca840c1f2e86437824f86564e745/external/llvm-project/mlir/BUILD.bazel:2992:11: Compiling mlir/lib/Support/ToolUtilities.cpp failed: undeclared inclusion(s) in rule '@llvm-project//mlir:Support':
this rule is missing dependency declarations for the following files included by 'mlir/lib/Support/ToolUtilities.cpp':
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/config.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt-exec-50AE0418/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**System information**

- Have I written custom code: No
- OS Platform and Distribution: Arch Linux x86_64 (rolling release)
- TensorFlow version: master branch @ [c44d14f2194](https://github.com/tensorflow/tensorflow/tree/c44d14f2194cf4c4b4060fd4141194ee62792ca8)
- Python version: 3.10.4
- Bazel version (if compiling from source): 5.1.1
- GCC/Compiler version (if compiling from source): Clang 13.0.1
- Compiling without GPU support

**Comment by qodfathr** [comment]
I am seeing same, compiling with GPU support.

**Comment by gadagashwini** [comment]
@ayaka14732, Looks like Bazel version, can you try with Bazel 5.0.0 Version. Thanks!

**Comment by ayaka14732** [comment]
> @ayaka14732, Looks like Bazel version, can you try with Bazel 5.0.0 Version. Thanks!

I manually changed `.bazelversion` to 5.0.0 and build with Bazel 5.0.0, but there are even more build errors.

**Comment by ZYHowell** [comment]
I met the same error, but it is automatically fixed after I clean up the bazel cache.

**Comment by ayaka14732** [comment]
@ZYHowell Thanks! This also works for me.

@gadagashwini Is this a Bazel bug or a Tensorflow bug?

**Comment by gadagashwini** [comment]
@ayaka14732,
Can you try to clear the bazel cache before building Tensorflow
`bazel clean --expunge`

**Comment by ayaka14732** [comment]
As I replied before, I tried to clean the cache and it works for me.

**Comment by gadagashwini** [comment]
@ayaka14732,
Glad that its resolved. Can we close this issue. Thanks!

**Comment by agostini01** [comment]
Hi, I had a similar issue but `bazel clean --expunge` did not fix my problem. Instead I had to use the workaround below

I had my env variables set CC=/usr/bin/clang CXX=/usr/bin/clang++
But bazel (v5.1.1) and tensorflow (93b2ef6e27c63f48f7bab67a630ee226b78e74c6) have some issues when compiling the with clang: https://github.com/bazelbuild/bazel/issues/15359
To fix this issue I cleared my CC and CXX env variables and compiled tensorflow with gcc9

**Comment by samuela** [comment]
This bug also impacts the bazel build of jaxlib on x86_64-darwin with clang (https://github.com/NixOS/nixpkgs/pull/183051#issuecomment-1226635146).

**Comment by lockmatrix** [comment]
add `--spawn_strategy=sandboxed` solved this problem for me

**Comment by ngocson2vn** [comment]
> Hi, I had a similar issue but `bazel clean --expunge` did not fix my problem. Instead I had to use the workaround below
> 
> I had my env variables set CC=/usr/bin/clang CXX=/usr/bin/clang++ But bazel (v5.1.1) and tensorflow ([93b2ef6](https://github.com/tensorflow/tensorflow/commit/93b2ef6e27c63f48f7bab67a630ee226b78e74c6)) have some issues when compiling the with clang: [bazelbuild/bazel#15359](https://github.com/bazelbuild/bazel/issues/15359) To fix this issue I cleared my CC and CXX env variables and compiled tensorflow with gcc9

I encountered the same issue as yours and I also resolved it with gcc10:
```Bash
gcc --version
gcc (GCC) 10.1.0
```

Bazel command:
```Bash
CC=gcc bazel build //examples:lower_lmhlo_ops ...
```
