### ISSUE TITLE
Question: how to implement tf.gather with some other tf ops ?

### ISSUE THREAD

**Issue by wwdok** [tensorflow/tensorflow#55560]
I am trying to implement tf.gather with some simple and common tf ops, because tf.gather is not supported in the ncnn deployment framework currently, for now I can only think of implementing it with numpy:
```
import tensorflow as tf 

indices = [3, 5, 2]

params = tf.constant([[[11, 12, 13], 
                    [14, 15, 16], 
                    [17, 18, 19],
                    [21, 22, 23],
                    [24, 25, 26], 
                    [27, 28, 29]],
                    [[31, 32, 33],
                    [34, 35, 36],
                    [37, 38, 39],
                    [41, 42, 43],
                    [44, 45, 46],
                    [47, 48, 49]]])
print("==>> params.shape: ", params.shape)
res = tf.gather(indices = indices, params = params, axis=1)
print("==>> res: ", res)
print("==>> res.shape: ", res.shape)

def gather(params, indices):
    """ equivalent to tf.gather(axis=1)"""
    output_shape = [params.shape[0], len(indices), params.shape[2]]
    params = params.numpy()
    output_tensor = params[:,indices,:]
    return tf.constant(output_tensor,dtype=tf.float32)

res2 = gather(params,indices)
print("==>> res2: ", res2)
print("==>> res2.shape: ", res2.shape)
``` 
If I don't convert the type of tensor to numpy by `params = params.numpy()`, it will reports error:
```
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got [3, 5, 2]
```
So how to implement tf.gather with some other tf ops and  without numpy, thanks in advance !

**Comment by wwdok** [comment]
I know there is an approach that is convert both params and indices to numpy type:
```
params = params.numpy()
indices = indices.numpy()
...
indices = indices.reshape((num_samples, m)).transpose().tolist()
output = params[indices]
```
But if is there an approach to implement it by tensorflow without tf.gather_nd ?

**Comment by wwdok** [comment]
or please tell me where is the (c++?)source code of tf.gather, thanks !

**Comment by wwdok** [comment]
or please tell me where is the minimal c++ implementation code of tf.gather, thanks !

**Comment by sushreebarsa** [comment]
@wwdok Could you please have a look at this[ link](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/gather) to get more details on Gather and let us know if it helps?Thanks!

**Comment by wwdok** [comment]
@sushreebarsa I'd rather know the code-level implementation than the superficial documentation. I notice the [gather_op.cc](https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/gather_op.cc) and [gather_functor.cc](https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/gather_functor.cc), are they the low-level implementation of tf.gather ?

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to reproduce this issue on colab using TF v2.7.0 , 2.8.0 and tf-nightly ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/428c2abe68f22930951688e3af851e39/55560.ipynb).Thanks!

**Comment by gadagashwini** [comment]
@wwdok,
Hi, Are you looking for https://github.com/tensorflow/tensorflow/blob/aa64f94acc83889d5e165d14f2e5c1dbe71bef3b/tensorflow/python/ops/array_ops.py#L5066

**Comment by MorphSeur** [comment]
I got the same issue.
Any help please!!
