### ISSUE TITLE
training input shape changed after v2.7.0

### ISSUE THREAD

**Issue by wiyr** [tensorflow/tensorflow#55573]
https://github.com/tensorflow/tensorflow/blob/92a6bb06549e74a8bd8cdb8e28552496e5520007/tensorflow/python/keras/engine/training.py#L798

There is a expand operation for 1d input data, but this op is missed in v2.7.0. I'd like to know why and how can i keep compatibility

**Comment by sushreebarsa** [comment]
@wiyr 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by wiyr** [comment]
This is keras issue. I will close it and opend in keras repo. Thanks
