### ISSUE TITLE
TFLite InterpreterBuilder Segmentation fault 11 on MacOS 11.6

### ISSUE THREAD

**Issue by HedgeHao** [tensorflow/tensorflow#55576]
I use C++ to load tflite model. Same code works fine on Linux & Android. But when running on MacOS it gives Segmentation fault 11  error.

I am using tensorflow 2.8.0. 

```C++
#include <tensorflow/lite/kernels/register.h>

std::unique_ptr<tflite::FlatBufferModel> model;
std::unique_ptr<tflite::Interpreter> interpreter;

int main() {
  model = tflite::FlatBufferModel::BuildFromFile"model.tflite");
  tflite::ops::builtin::BuiltinOpResolver resolver;
  tflite::InterpreterBuilder(*model, resolver)(&interpreter); // -> Segmentation fault 11 here
  return 0;
}
```

**Comment by mohantym** [comment]
Hi @HedgeHao ! Can you check this code and let us know the output?
```
// Create model from file. Note that the model instance must outlive the
// interpreter instance.
auto model = [tflite::FlatBufferModel::BuildFromFile](...);
if (model == nullptr) {
  // Return error.
}
// Create an [Interpreter]
std::unique_ptr interpreter;
tflite::ops::builtin::BuiltinOpResolver resolver;
if (InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk) {
  // Return failure.
}
if (interpreter->AllocateTensors() != kTfLiteOk) {
  // Return failure.
}
```

**Comment by HedgeHao** [comment]
@mohantym Not working, either. Still Segmentation fault: 11 in `InterpreterBuilder`.

> Hi @HedgeHao ! Could you check this code snippet and let us know the output? Thanks!
> 
> ```
> #include <tensorflow/lite/kernels/register.h>
> using namespace tflite;
> std::unique_ptr<tflite::FlatBufferModel> model;
> std::unique_ptr<tflite::Interpreter> interpreter;
> 
> int main() {
>   auto model = tflite::FlatBufferModel::BuildFromFile("model.tflite"); // saw a missing open bracket in original code
>   if (model == nullptr) {
>   // Return error if model is empty
> }
> tflite::ops::builtin::BuiltinOpResolver resolver;
> if (InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk) {
>   // Return failure.
> }
> if (interpreter->AllocateTensors() != kTfLiteOk) {
>   // Return failure.
> }
>   return 0;
> }
> ```

**Comment by HedgeHao** [comment]
Anyone?

**Comment by sachinprasadhs** [comment]
Hi, Did you try it in the nightly version and did you find the same behavior. 
Could you also let us know your Mac's processor. Thanks!

**Comment by HedgeHao** [comment]
I built tensorflowlite shared library following this [tutorial] (https://www.tensorflow.org/lite/guide/build_cmake) with version 2.8.0. I use Mac Air 2014 , Big Sur 11.6, Intel Core i5.

**Comment by HedgeHao** [comment]
Problem is not resolve

**Comment by HedgeHao** [comment]
@terryheo I use debug build but the debugger stuck at InterpreterBuilder(). I can't step into tflite function to debug. 

Can anyone provide the sample code and prebuilt dylib that can work. I've been stuck on this very beginning sample for a month..

**Comment by pkgoogle** [comment]
Hi @HedgeHao,

Can you provide the "model.tflite" file so that we can attempt to replicate this?

Thanks!
