### ISSUE TITLE
Unwanted log messages and crash/force termination

### ISSUE THREAD

**Issue by prabalakanti** [tensorflow/tensorflow#55575]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 8.5
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: Binary
-   **TensorFlow version (use command below)**: 2.5.3
-   **Python version**: 3.8.8
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: CUDA 11.2.2
-   **GPU model and memory**:  P100

### Describe the problem
While running a model training using `.fit` function using a tf.data.Dataset we observe a lot of prints of the statement `Cleanup called...`. Example:
```
Cleanup called...
Cleanup called...
Cleanup called...
Cleanup called...
Cleanup called...
Cleanup called...
Cleanup called...
```
Followed by Python code termination with an error code:
`Aborted (core dumped) python run.py`

This problem occurs with TF 2.5.3. The same code runs perfectly with TF 2.5.2.
Even though the Python interpreter errors out with the core dumped message, actual model training works fine and the model also gets saved.

We use the function `tf.io.decode_image` in the tf.data pipeline which seems to be causing these prints.

**Comment by tilakrayal** [comment]
@prabalakanti ,
In order to expedite the trouble-shooting process, I request you, could you please provide a complete code you are using.

Also there is a high possibility that this was fixed with stable TF versions. Perhaps you can try to test your code in latest stable tf version 2.8 for your case. Thanks!

**Comment by prabalakanti** [comment]
@tilakrayal Unfortunately it is not possible for me to share the complete code. Based on our analysis the log message is coming from: https://github.com/tensorflow/tensorflow/blob/959e9b2a0c06df945f9fb66bd367af8832ca0d28/tensorflow/core/kernels/image/decode_image_op.cc#L337

This seems to have been removed in the latest TF version 2.8: https://github.com/tensorflow/tensorflow/commit/09dab4f0e0f3785c3b764b64b476831e529bb139

An upgrade to TF 2.8 is not immediately feasible for us as we have to update the code for TF2.5 to TF2.8 upgrade.

Is there any alternative way to fix this in TF2.5.3 by some flag/param to skip these log messages?

**Comment by prabalakanti** [comment]
Code snippets from the tf.data pipeline:

```python
def get_images_dataset(data_dir, num_labels, prefix="train"):
    tfrecord_files = tf.data.Dataset.list_files(
        os.path.join(data_dir, f"{prefix}-*.tfrecord"))

    raw_dataset = tf.data.TFRecordDataset(tfrecord_files)

    features = {
        "image/height": tf.io.FixedLenFeature([], tf.int64),
        "image/width": tf.io.FixedLenFeature([], tf.int64),
        "image/encoded": tf.io.FixedLenFeature([], tf.string),
        "image/labels": tf.io.FixedLenFeature([num_labels], tf.int64)
    }

    def _parse_example(example):
        parsed_tensors = tf.io.parse_single_example(example, features)
        image = tf.io.decode_image(
            parsed_tensors["image/encoded"], channels=3, expand_animations=False)
        image.set_shape([None, None, 3])
        label_vector = parsed_tensors["image/labels"]
        return image, label_vector

    dataset = raw_dataset.map(
        _parse_example, num_parallel_calls=tf.data.experimental.AUTOTUNE)

    return dataset
```

Additionally we run these functions on top of the created dataset:
```
dataset = dataset.cache()
dataset = dataset.shuffle(buffer_size=num_images)
dataset = dataset.repeat()
dataset = dataset.batch(batch_size)
dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
```

Training is run using the `model.fit` function of tf.keras:
```
model.fit(
            train_ds,
            steps_per_epoch=steps_per_epoch,
            epochs=epochs,
            validation_data=valid_ds,
            validation_steps=validation_steps,
            callbacks=cbks,
            verbose=1,
        )
```

**Comment by tilakrayal** [comment]
@prabalakanti ,
On running the given code snippet, I am facing an error stating `NameError: name 'dataset' is not defined`'. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/71a906fec4b5da800f380b34a07be7bb/untitled305.ipynb) and provide the complete code to reproduce the issue.Thanks!

**Comment by jerryIsHere** [comment]
This happened in version 2.6.3 `tfds.load('cifar100',split=['train', 'test'],as_supervised=True)`

**Comment by prabalakanti** [comment]
> @prabalakanti , On running the given code snippet, I am facing an error stating `NameError: name 'dataset' is not defined`'. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/71a906fec4b5da800f380b34a07be7bb/untitled305.ipynb) and provide the complete code to reproduce the issue.
> 
> There is a high possibility that this was fixed with stable TF versions. Perhaps you can try to test your code in latest stable tf version 2.8 for your case. Thanks!Thanks!

Unfortunately I won't be able to give the entire working code snippet to reproduce this issue. We will try to run the same code with TF 2.8 and check if the issue occurs.

**Comment by jerryIsHere** [comment]
I tried `!pip install -U -q tensorflow==2.8.0` on kaggle, it worked
For version 2.6.3, I tried tricks that I found on stackoverflow, they don't work on kaggle.
 (`sys.stderr` and `from contextlib import redirect_stderr`)
