### ISSUE TITLE
building tensorflow with docker image fails

### ISSUE THREAD

**Issue by N1uY** [tensorflow/tensorflow#55571]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04(in docker)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version: master branch
- Python version:3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):5.1.0
- GCC/Compiler version (if compiling from source):gcc9.4.0
- CUDA/cuDNN version:cuda11.2 cudnn8
- GPU model and memory:RTX3090

**Describe the problem**
i follow the instruction in the tensorflow document to build the source with docker.I pulled the devel-gpu image and and try to build source in the container. i found using the command in the document i went to the directory  "tensorflow",but it cant pull as it is not a git repo, go to the directory “tensorflow_src" it can work but i can not checkout branch like r2.7,so i build the master branch with default configuration and i got the error.Really confused me. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
/root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/external/nsync/BUILD:467:11: Compiling platform/c++11/src/nsync_panic.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 \
    LD_LIBRARY_PATH=/usr/local/cuda-11.0/targets/x86_64-linux/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64/stubs:/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.2/lib64 \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.1.0-linux-x86_64/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=8.6 \
    TF_CUDA_VERSION=11.2 \
    TF_CUDNN_VERSION=8 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/nsync/_objs/nsync_cpp/nsync_panic.d '-frandom-seed=bazel-out/k8-opt/bin/external/nsync/_objs/nsync_cpp/nsync_panic.o' -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DAUTOLOAD_DYNAMIC_KERNELS -Wno-sign-compare '-std=c++14' -x c++ '-std=c++11' -I./external/nsync//platform/c++11.futex -DNSYNC_ATOMIC_CPP11 -DNSYNC_USE_CPP11_TIMEPOINT -I./external/nsync//platform/c++11 -I./external/nsync//platform/gcc -I./external/nsync//platform/x86_64 -I./external/nsync//public -I./external/nsync//internal -I./external/nsync//platform/posix '-D_POSIX_C_SOURCE=200809L' -pthread -c external/nsync/platform/c++11/src/nsync_panic.cc -o bazel-out/k8-opt/bin/external/nsync/_objs/nsync_cpp/nsync_panic.o)
# Configuration: c750dc19fc82070b294558f14293082aaaae479c4ce153dc94857ec7a3f60c5d
# Execution platform: @local_execution_config_platform//:platform
In file included from /usr/include/c++/9/mutex:44,
                 from ./external/nsync//platform/c++11.futex/../c++11/platform.h:29,
                 from ./external/nsync//platform/c++11.futex/platform.h:22,
                 from ./external/nsync//internal/headers.h:19,
                 from external/nsync/platform/c++11/src/nsync_panic.cc:15:
/usr/include/c++/9/bits/unique_lock.h: In instantiation of ‘void std::unique_lock<_Mutex>::lock() [with _Mutex = std::mutex]’:
./external/nsync//platform/c++11.futex/../c++11/platform.h:99:14:   required from here
/usr/include/c++/9/bits/unique_lock.h:136:35: internal compiler error: Segmentation fault
  136 |    __throw_system_error(int(errc::operation_not_permitted));

**Comment by tilakrayal** [comment]
Hello @N1uY ,
Every TensorFlow release is compatible with a certain version, for more information requesting you to please take a look at the tested build [configurations](https://www.tensorflow.org/install/source#gpu)(GCC 7.3.1 ,CUDA 11.2 and CuDNN 8.1) after following one of these commands `"bazel clean --expunge" or "bazel clean --expunge_async"`.

Also I request you please check this relevant thread [1](https://github.com/tensorflow/tensorflow/issues/54498) and [2](https://github.com/tensorflow/tensorflow/issues/53118) for reference. Thanks!

**Comment by N1uY** [comment]
@tilakrayal ,thanks for you response! I have checked the relevant thread you mentioned, it seems that uncompatible cuda or cudnn version can be the cause. After running the bazel clean command, I rebuild the TensorFlow with(cuda 11.2 and Cudnn8.1 and GCC7.5.0 (so difficult to install 7.3.1 on ubuntu 20)).Unfortunately, it failed again.

**Comment by N1uY** [comment]
@tilakrayal it still fails....can you give some advice?
`/home/ubuntu/.cache/bazel/_bazel_ubuntu/13d17b8c3a469e3b21b32031a169192f/external/llvm-project/llvm/BUILD.bazel:1881:16: C++ compilation of rule '@llvm-project//llvm:NVPTXCodeGen' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/13d17b8c3a469e3b21b32031a169192f/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-7 \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64: \
    PATH=/home/ubuntu/bl/software/anaconda3/envs/buildTF/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/home/GaoJH/login_network/node-v14.15.4-linux-x64/bin:/home/ubuntu/bl/software/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/bl/software/java/jdk1.7.0_80/bin:/home/ubuntu/bl/software/java/jdk1.7.0_80/jre/bin:/home/ubuntu/bl/software/java/neo4j-community-2.1.8/bin:/home/ubuntu/bl/software/java/jdk1.7.0_80/bin:/bin:/sbin:/bin:/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/bl/software/java/jdk1.7.0_80/bin:/home/ubuntu/bl/software/java/jdk1.7.0_80/jre/bin:/home/ubuntu/bl/software/java/neo4j-community-2.1.8/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/ubuntu/bl/software/anaconda3/envs/buildTF/bin/python3 \
    PYTHON_LIB_PATH=/home/ubuntu/bl/software/anaconda3/envs/buildTF/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=8.6 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/NVPTXCodeGen/NVPTXAsmPrinter.d '-frandom-seed=bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/NVPTXCodeGen/NVPTXAsmPrinter.o' '-DLLVM_ON_UNIX=1' '-DHAVE_BACKTRACE=1' '-DBACKTRACE_HEADER=<execinfo.h>' '-DLTDL_SHLIB_EXT=".so"' '-DLLVM_PLUGIN_EXT=".so"' '-DLLVM_ENABLE_THREADS=1' '-DHAVE_SYSEXITS_H=1' '-DHAVE_UNISTD_H=1' '-DHAVE_STRERROR_R=1' '-DHAVE_LIBPTHREAD=1' '-DHAVE_PTHREAD_GETNAME_NP=1' '-DHAVE_PTHREAD_SETNAME_NP=1' '-DHAVE_PTHREAD_GETSPECIFIC=1' '-DHAVE_REGISTER_FRAME=1' '-DHAVE_DEREGISTER_FRAME=1' -D_GNU_SOURCE '-DHAVE_LINK_H=1' '-DHAVE_LSEEK64=1' '-DHAVE_MALLINFO=1' '-DHAVE_POSIX_FALLOCATE=1' '-DHAVE_SBRK=1' '-DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1' '-DLLVM_NATIVE_ARCH="X86"' '-DLLVM_NATIVE_ASMPARSER=LLVMInitializeX86AsmParser' '-DLLVM_NATIVE_ASMPRINTER=LLVMInitializeX86AsmPrinter' '-DLLVM_NATIVE_DISASSEMBLER=LLVMInitializeX86Disassembler' '-DLLVM_NATIVE_TARGET=LLVMInitializeX86Target' '-DLLVM_NATIVE_TARGETINFO=LLVMInitializeX86TargetInfo' '-DLLVM_NATIVE_TARGETMC=LLVMInitializeX86TargetMC' '-DLLVM_NATIVE_TARGETMCA=LLVMInitializeX86TargetMCA' '-DLLVM_HOST_TRIPLE="x86_64-unknown-linux-gnu"' '-DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-unknown-linux-gnu"' -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -iquote external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -iquote external/llvm_terminfo -iquote bazel-out/k8-opt/bin/external/llvm_terminfo -iquote external/llvm_zlib -iquote bazel-out/k8-opt/bin/external/llvm_zlib -Ibazel-out/k8-opt/bin/external/llvm-project/llvm/_virtual_includes/NVPTXCodeGen -Ibazel-out/k8-opt/bin/external/llvm-project/llvm/_virtual_includes/InstCombineTableGen -Ibazel-out/k8-opt/bin/external/llvm-project/llvm/_virtual_includes/NVPTXCommonTableGen -Ibazel-out/k8-opt/bin/external/llvm-project/llvm/_virtual_includes/NVPTXInfo -Ibazel-out/k8-opt/bin/external/llvm-project/llvm/_virtual_includes/NVPTXUtilsAndDesc -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include -isystem external/llvm-project/llvm/lib/Target/NVPTX -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/lib/Target/NVPTX -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DAUTOLOAD_DYNAMIC_KERNELS '-std=c++14' -c external/llvm-project/llvm/lib/Target/NVPTX/NVPTXAsmPrinter.cpp -o bazel-out/k8-opt/bin/external/llvm-project/llvm/_objs/NVPTXCodeGen/NVPTXAsmPrinter.o)
Execution platform: @local_execution_config_platform//:platform
In file included from /usr/include/c++/7/memory:65:0,
                 from external/llvm-project/llvm/include/llvm/ADT/Optional.h:24,
                 from external/llvm-project/llvm/include/llvm/ADT/STLExtras.h:19,
                 from external/llvm-project/llvm/include/llvm/IR/PassManager.h:41,
                 from external/llvm-project/llvm/lib/Target/NVPTX/NVPTX.h:17,
                 from external/llvm-project/llvm/lib/Target/NVPTX/NVPTXAsmPrinter.h:17,
                 from external/llvm-project/llvm/lib/Target/NVPTX/NVPTXAsmPrinter.cpp:14:
/usr/include/c++/7/bits/stl_uninitialized.h: In instantiation of ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = std::pair<const void*, llvm::Pass*>*; _ForwardIterator = std::pair<const void*, llvm::Pass*>*; _Allocator = std::allocator<std::pair<const void*, llvm::Pass*> >]’:
/usr/include/c++/7/bits/vector.tcc:426:6:   required from ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {const std::pair<const void*, llvm::Pass*>&}; _Tp = std::pair<const void*, llvm::Pass*>; _Alloc = std::allocator<std::pair<const void*, llvm::Pass*> >; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<std::pair<const void*, llvm::Pass*>*, std::vector<std::pair<const void*, llvm::Pass*> > >; typename std::_Vector_base<_Tp, _Alloc>::pointer = std::pair<const void*, llvm::Pass*>*]’
/usr/include/c++/7/bits/stl_vector.h:948:21:   required from ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::pair<const void*, llvm::Pass*>; _Alloc = std::allocator<std::pair<const void*, llvm::Pass*> >; std::vector<_Tp, _Alloc>::value_type = std::pair<const void*, llvm::Pass*>]’
external/llvm-project/llvm/include/llvm/PassAnalysisSupport.h:183:32:   required from here
/usr/include/c++/7/bits/stl_uninitialized.h:313:5: internal compiler error: Segmentation fault
     }
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

**Comment by gadagashwini** [comment]
Hello @N1uY,
Required `CUDA version 11.2+`, from your config it looks like its 11.0. So, please see if you can upgrade your local CUDA version to 11.x. 11.2 builds should be compatible with anything 11.x. If you have multiple CUDA versions, I suggest you to delete rest of them. Thanks!

**Comment by N1uY** [comment]
@gadagashwini Sorry to reply so late.I have uninstalled all cuda and reinstall 11.2 and cudnn ,there is still something wrong.I really thank you all for your help.
