### ISSUE TITLE
Android- No implementation found.

### ISSUE THREAD

**Issue by ahmadbajwa8282** [tensorflow/tensorflow#55584]
Hello everyone. I'm using tensorflow for background removal of an object. Every thing is working great but I'm keep getting this exception on the first time of model load. once the model is loaded it did not occurred.

**Stack Trace:**
No implementation found for long org.tensorflow.contrib.android.RunStats.allocate() (tried Java_org_tensorflow_contrib_android_RunStats_allocate and Java_org_tensorflow_contrib_android_RunStats_allocate__)
I/TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
I/TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)

**Code:**

   private var sTFInterface: TensorFlowInferenceInterface? = null
   sTFInterface = TensorFlowInferenceInterface(context.assets, MODEL_FILE)

**Dependencies:**
    implementation 'org.tensorflow:tensorflow-lite:2.8.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.8.0'

**Comment by mohantym** [comment]
Hi @ahmadbajwa8282 ! Contrib has depreciated in 2.x version and not supported any more. Please select the suitable lite version in build.gradle according to your Tensorflow version. Thanks!

**Comment by ahmadbajwa8282** [comment]
@mohantym  but according to the repo the latest version is 2.8.0.

**Comment by mohantym** [comment]
@ahmadbajwa8282 ! I traced this "TensorFlowInferenceInterface" keyword in stack trace to [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/android) which says that it is depreciated and  use TFlite instead. Could you share the link to that repo though?

**Comment by ahmadbajwa8282** [comment]
@mohantym Ok thanks for your help.

**Comment by ahmadbajwa8282** [comment]
@mohantym Can you explain or share an exmaple how to use TFlite?

**Comment by mohantym** [comment]
@ahmadbajwa8282 ! You can get a TFlite model from model from model using TFliteConverter . Attaching [sample notebook](https://colab.research.google.com/github/frogermcs/TFLite-Tester/blob/master/notebooks/Testing_TFLite_model.ipynb) and [guide ](https://www.tensorflow.org/lite/convert)for reference. Thanks!

**Comment by ahmadbajwa8282** [comment]
@mohantym thanks for the help. I have implemented Interpreter for reading model lets see the result how it works.
