### ISSUE TITLE
how reduce  tensorflow-lite-select-tf-ops.aar size ？

### ISSUE THREAD

**Issue by thomaszheng** [tensorflow/tensorflow#55583]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04.4 LTS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.7.0
- Python version:3.8.10 
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source):3.7.2
- GCC/Compiler version (if compiling from source):  9.4.0
- CUDA/cuDNN version:N
- GPU model and memory:

**Describe the problem**

I follow the guide [reduce_binary_size](https://www.tensorflow.org/lite/guide/reduce_binary_size#selectively_build_tensorflow_lite_with_docker)  and execute this commands: [model.tflite](https://drive.google.com/file/d/1f-BDEojrEgx0lPmaI8_x44sKOJl-1mOv/view?usp=sharing)

```
bash tensorflow/lite/tools/build_aar.sh  --input_models=/host_dir/model.tflite --target_archs=arm64-v8a,armeabi-v7a
```

and get the tensorflow-lite-select-tf-ops.aar 6.5M

```
6507898 Apr 12 03:31 tensorflow-lite-select-tf-ops.aar*
```

but its size is still too big，can i further reduce it size ? only build cpu or build without Delegate?

**Any other info / logs**

Intermediate file in tmp :`ops_list.txt`

```
["AddN","BiasAddGrad","BroadcastGradientArgs","Cast","ConcatOffset","EmptyTensorList","ReluGrad","Restore","Save","ShapeN","SigmoidGrad","StridedSliceGrad","TensorListElementShape","TensorListFromTensor","TensorListGetItem","TensorListLength","TensorListPopBack","TensorListPushBack","TensorListReserve","TensorListSetItem","TensorListStack","UnsortedSegmentSum","ZerosLike"]
```

**Comment by mohantym** [comment]
Ok @thomaszheng ! Can you put this line during lite conversion for [optimum size](https://www.tensorflow.org/api_docs/python/tf/lite/Optimize) and let us know after rebuilding the aar files from it.?

```
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE
converter.convert()
```

**Comment by thomaszheng** [comment]
ok @mohantym !
I used this conversion  command before (tf version 2.8.0)：
```
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```

model.tflite size is 4M
now i use:
```
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_DIR)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
```
model_n.tflite size is 8.6M

then, reduce binary size arr:

```
bash tensorflow/lite/tools/build_aar.sh  --input_models=/host_dir/model_n.tflite --target_archs=arm64-v8a,armeabi-v7a
```

```
1273647 Apr 12 08:53 tensorflow-lite.aar*
6926947 Apr 12 09:17 tensorflow-lite-select-tf-ops.aar*
```

from the results, it seems that there is no decrease

**Comment by mohantym** [comment]
@sachinprasadhs ! Could you please look at this issue?

**Comment by thomaszheng** [comment]
@miaout17 hi，Is there any other way please ？

**Comment by mohantym** [comment]
Hi @thomaszheng !  
Have you checked this document to [reduce binary size](https://www.tensorflow.org/lite/guide/reduce_binary_size) using two tflite models with different configurations. You can create multiple TFLite models using Dynamic range/ Float 16 or Int 16 quantization and use the Bash command with specific targets to get a lighter model. Other options can be [model optimization](https://www.tensorflow.org/model_optimization/guide/pruning/) which might render TFlite model  in KBs.

Thank you!

**Comment by thomaszheng** [comment]
@mohantym i have used quantization to get a lighter model,and it also reduce tflite model size from 8M to 4M,and I will try again. and now i think the size of  tensorflow-lite.aar*(1.2M)  and tensorflow-lite-select-tf-ops.aar*(6.5M) is too big. 

My model is implemented with reference to this tutorial [model_personalization](https://github.com/tensorflow/examples/tree/master/lite/examples/model_personalization), it will train on android device.

and I implement the same function using [MNN](https://github.com/alibaba/MNN),and it size of lib so 3.27M (arm64-v8a) and  1.79M (armabi-v7a).

**Comment by mohantym** [comment]
@thomaszheng ! 
Were you able to reduce the file size further ? Feel free to re-open this issue if you are still looking for further assistance.
Thank you!

**Comment by thomaszheng** [comment]
yes, i want to use tflite if the file size no too big
