### ISSUE TITLE
ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 219566, 6), found shape=(None, 6)

### ISSUE THREAD

**Issue by donskoyaleksander** [tensorflow/tensorflow#55588]
Guys, do you have any idea how to solve this problem (LSTM, Keras, Tensorflow)? 
---------------------------------------------------------------------------
I looked through the similar topics but suggested solutions do not work for me. The code is pretty simple:

import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn
import keras_tuner as kt

from tensorflow import keras
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

df_training_data = pd.read_csv (r'G:\Research\Oils\REQUESTS\US_data\ProdAbo_AllHeaders_csv.csv')

x_total = df_training_data.loc[:,['Lat_X1','Lon_X2','Month_X3',
                                  'Well_length_X5','Density_X7','Month_from_start_X8']]

y_total = df_training_data.loc[:,'Liquids_Y1']

scaler = MinMaxScaler()
x_total = scaler.fit_transform(x_total)

x_total = np.array(x_total).astype(np.float32)
y_total = np.array(y_total).astype(np.float32)

x_train, x_test, y_train, y_test = train_test_split(x_total, y_total, test_size = 0.3, random_state = 0)

num_rows, num_cols = x_train.shape

x_train = tf.reshape(x_train, [num_rows, num_cols])
y_train = tf.reshape(y_train, [num_rows, 1])

batch_size = 100
num_epochs = 5

model = tf.keras.models.Sequential([tf.keras.layers.LSTM(num_cols, 
                                                         input_shape=(num_rows,num_cols), 
                                                         activation = tf.nn.tanh,
                                                         return_sequences=True),        
                                    tf.keras.layers.LSTM(10, activation = tf.nn.tanh),
                                    tf.keras.layers.Dense(1, activation = tf.nn.relu)]) 

model.compile(optimizer='adam', loss='mse', metrics=[tf.keras.metrics.RootMeanSquaredError()])

model.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(x_test, y_test))

And here we are:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-37ddda0f53d6> in <module>
      3 num_epochs = 5
      4 
----> 5 model.fit(x_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(x_test, y_test))
      6 
      7 #model.fit(train_data, epochs=num_epochs, batch_size=batch_size, validation_data=test_data)

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 219566, 6), found shape=(None, 6)

**Comment by donskoyaleksander** [comment]
Problem resolved:

**x_train = np.reshape(x_train, (x_train.shape[0],1,x_train.shape[1]))
x_test = np.reshape(x_test, (x_test.shape[0],1,x_test.shape[1]))**

model = tf.keras.models.Sequential([tf.keras.layers.LSTM(num_cols, 
                                                         **input_shape=(1,num_cols),** 
                                                         activation = tf.nn.tanh,
                                                         return_sequences=True),        
                                    tf.keras.layers.LSTM(10, activation = tf.nn.tanh), 
                                    tf.keras.layers.Dense(1, activation = tf.nn.relu)])

**Comment by varundeepakgudhe** [comment]
x_train = np.reshape(x_train, (x_train.shape[0],1,x_train.shape[1]))
x_test = np.reshape(x_test, (x_test.shape[0],1,x_test.shape[1]))
If I try this methods its giving this error
Must pass 2-d input. shape=(53656, 1, 54)

**Comment by varundeepakgudhe** [comment]
Is there any alternate way to solve expected =____ ;found=___ error?
