### ISSUE TITLE
how to define representative_data_gen function when model has two inputs?

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#55586]
https://www.tensorflow.org/lite/performance/post_training_integer_quant:

def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(train_images).batch(1).take(100):
    # Model has only one input so each data point has one element.
    yield [input_value]
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
tflite_model_quant = converter.convert()

My question is, how to modify the code listed above, when model has two or more inputs?

**Comment by mohantym** [comment]
Hi @njuhang ! You have to add the other input in the yield line of the representative Dataset. Please use the [input signature](https://www.tensorflow.org/lite/guide/signatures) to keep the inputs in order . Attaching relevant[ thread](https://github.com/tensorflow/tensorflow/issues/46732) for reference. Thanks!

**Comment by njuhang** [comment]
yes, I solve the problem

**Comment by mohantym** [comment]
@njuhang ! Thanks for confirmation . Moving this issue to closed status then.
