### ISSUE TITLE
on xcode,  not found for architecture arm64 caused

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tensorflow#55585]
I added on my podfile 
pod 'TensorFlowLiteObjc' 

then install, 
build then cause error on xcode. 

what may be the problem? 
I'm using m1 mac 

```
ld: warning: Could not find or use auto-linked framework 'TFLTensorFlowLite'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TFLInterpreter", referenced from:
      objc-class-ref in SmartVisionVehicle.o
ld: symbol(s) not found for architecture arm64
```

**Comment by mohantym** [comment]
Hi @kotran88 ! Could you please share all the steps ? Attaching relevant [thread](https://stackoverflow.com/a/54651151) for reference. Thanks!
