### ISSUE TITLE
macOS wheel URLs are incorrect

### ISSUE THREAD

**Issue by samuela** [tensorflow/tensorflow#55581]
## URL(s) with the issue:

https://www.tensorflow.org/install/pip

## Description of issue (what needs changing):

The Mac wheels that the docs page purport to exist do not, in fact, exist:
```
NoSuchKeyThe specified key does not exist.No such object: tensorflow/mac/cpu/tensorflow-2.8.0-cp39-cp39-macosx_10_11_x86_64.whl
```

Where are these wheels actually located?

### Submit a pull request?

I would submit a PR, but I am not aware of what the correct URLs are. The storage bucket does not have any index as far as I could tell.

**Comment by chunduriv** [comment]
@samuela,

Thank you for reporting.

**Comment by samuela** [comment]
@chunduriv what are the correct URLs for those wheels?

**Comment by chunduriv** [comment]
@samuela,

I have submitted the fix internally which should reflect the updated changes.

Please refer correct path for macOS

Python 3.7 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.8.0-cp37-cp37m-macosx_10_14_x86_64.whl
Python 3.8 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.8.0-cp38-cp38-macosx_10_14_x86_64.whl
Python 3.9 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.8.0-cp39-cp39-macosx_10_14_x86_64.whl
Python 3.10 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.8.0-cp310-cp310-macosx_10_14_x86_64.whl

Thanks!

**Comment by samuela** [comment]
Thanks @chunduriv! What is the correct path for linux, python 3.10, CPU only?

**Comment by chunduriv** [comment]
@samuela,

We have submitted fix internally for `Linux Python 3.10 CPU only` wheel. Thanks!

**Comment by samuela** [comment]
@chunduriv Thanks!

Is there a technical reason that the linux/python 3.10/CPU-only wheel does not exist?

**Comment by samuela** [comment]
not stale

**Comment by chunduriv** [comment]
@samuela,

Sorry for the late response. `TF2.8` binaries were uploaded to the wrong bucket. 

`TF2.8.1` is released. Could you try to use 2.8.1 wheel https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.8.1-cp310-cp310-manylinux2010_x86_64.whl

Thank you.
