### ISSUE TITLE
In tensorflow 2.8.0 multi input / multi output keras model not working

### ISSUE THREAD

**Issue by shinel94** [tensorflow/tensorflow#55598]
**System information**
- tensorflow 2.8.0
- python 3.8.12
- Windows 10 Home 21H2 (19044.1586)
- CPU : AMD Ryzen 9 3900XT 12-Core Processor 3.80 GHz
- RAM : 64.0GB
- GPU : NVIDIA GeForce GRX 1660 SUPER
- NVIDIA-SMI 496.13 / Driver Version: 496.13 / CUDA Version: 11.5 / cuDNN version 8302
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
```import numpy as np
import tensorflow as tf
i1 = tf.keras.layers.Input(shape=(10, 1))
i2 = tf.keras.layers.Input(shape=(20, 1))
i3 = tf.keras.layers.Input(shape=(40, 10))
h1 = tf.keras.layers.Conv1D(32, 10, name='o1')(i1)
h2 = tf.keras.layers.Conv1D(32, 20, name='o2')(i2)
h3 = tf.keras.layers.Conv1D(32, 40, name='o3')(i3)
m = tf.keras.Model(inputs=[i1,i2,i3], outputs=[h1,h2,h3])
def loss(y_true,y_pred):
    return tf.losses.mean_absolute_error(y_true, y_pred) + tf.losses.mean_squared_error(y_true, y_pred)
m.compile(optimizer='adam', loss={'o1': 'mse', 'o2':"mae", 'o3': loss})
m.fit([np.random.normal(size=(10,10,1)), np.random.normal(size=(10,20,1)), np.random.normal(size=(10,40,10))], [np.random.normal(size=(10,1,32)),np.random.normal(size=(10,1,32)),np.random.normal(size=(10,1,32))])
m.predict([np.random.normal(size=(10,10,1)), np.random.normal(size=(10,20,1)), np.random.normal(size=(10,40,10))])
```
- OUTPUT : 
```2022-04-13 09:27:20.307913: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-13 09:27:20.725606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3995 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 SUPER, pci bus id: 0000:26:00.0, compute capability: 7.5
2022-04-13 09:27:22.135084: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8302

Process finished with exit code -1073740791 (0xC0000409)
```

**Describe the expected behavior**
In Previous version tensorflow, work done same code, but in later 2.7.1 occur, error and can't running same code

- Do you want to contribute a PR? (yes/no): may be can't
- Briefly describe your candidate solution(if contributing):

**Comment by chunduriv** [comment]
@shinel94,

I am successfully able to run using Colab `TF2.8`. Please find [the](https://colab.research.google.com/gist/chunduriv/474bba9885746fbea4b4643f68b877d2/55598.ipynb) gist for reference.

>CUDA Version: 11.5 / cuDNN version 8302

Could you please try with `CUDA 11.2` and `cuDNN 8.1` for `TF2.8`. Please refer tested build configuration [here](https://www.tensorflow.org/install/source_windows#gpu).Thanks!
