### ISSUE TITLE
right after install TensorFlowLiteObjC , by pod install, cause error in Xcode

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tensorflow#55599]
my Podfile is 

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MyApp
  pod 'TensorFlowLiteObjC'

end
```

right after install pod file by commanding 
arch -x86_64 pod install

then build keep failed saying 

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I did many things that on web says...delete pods file...clean .... I did almost everything but no worth it. 
it just happened when install pod. 

m1 Mac

**Comment by mohantym** [comment]
Hi @kotran88 ! Is this issue duplicate to #55585 ?
