### ISSUE TITLE
ImportError: cannot import name 'deepmac_meta_arch' from 'object_detection.meta_architectures'

### ISSUE THREAD

**Issue by santhoshnumberone** [tensorflow/tensorflow#55591]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Google colab
- TensorFlow installed from (source or binary): Google colab (default)
- TensorFlow version: 1.15.2
- Python version: 3.7.13
- Installed using virtualenv? pip? conda?: Google Colab (no env)
- Bazel version (if compiling from source): Google colab (default)
- GCC/Compiler version (if compiling from source): Google colab (default)
- CUDA/cuDNN version: Google colab (default)
- GPU model and memory: Google colab (default)

**Describe the problem**
Trying to train custom object detector referring blog [Custom object detection in the browser using TensorFlow.js](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Ran these blocks one after other inside Google colab
```
from google.colab import drive
drive.mount('/content/drive/')
```

```
%cd /content/drive/MyDrive/Tensorflow/models/research/
!protoc object_detection/protos/*.proto --python_out=.
# Install TensorFlow Object Detection API.
!cp object_detection/packages/tf2/setup.py .
```

```
!pip install tensorflow-object-detection-api
```

```
%tensorflow_version 1.x
```

```
%cd /content/drive/MyDrive/Tensorflow/models/research/slim/
```

```
%%bash
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

python setup.py build
python setup.py install
```

```
!python /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py
```

Error in this block
```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/model_builder_tf2_test.py", line 27, in <module>
    from object_detection.meta_architectures import deepmac_meta_arch
ImportError: cannot import name 'deepmac_meta_arch' from 'object_detection.meta_architectures' (/usr/local/lib/python3.7/dist-packages/object_detection/meta_architectures/__init__.py)
```

**Comment by chunduriv** [comment]
Since you are using `TF1.x`, 

1. Can you try to install `TF1.x` Object Detection API instead of `TF2.x` Object Detection API as shown below

`cp object_detection/packages/tf1/setup.py 
`

2. Can you try to change `model_builder_tf2_test.py` to `model_builder_tf1_test.py` as shown below

`!python /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/model_builder_tf1_test.py
`

Or simple workaround is try to use `%tensorflow_version 2.x` instead of `%tensorflow_version 1.x`. Thanks!

**Comment by santhoshnumberone** [comment]
> Since you are using `TF1.x`,
> 
> 1. Can you try to install `TF1.x` Object Detection API instead of `TF2.x` Object Detection API as shown below
> 
> `cp object_detection/packages/tf1/setup.py `
> 
> 2. Can you try to change `model_builder_tf2_test.py` to `model_builder_tf1_test.py` as shown below
> 
> `!python /content/drive/MyDrive/Tensorflow/models/research/object_detection/builders/model_builder_tf1_test.py `
> 
> Or simple workaround is try to use `%tensorflow_version 2.x` instead of `%tensorflow_version 1.x`.
> 
> For more details please refer [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1.md). Thanks!

Thank you it started working

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by ingenious-hans** [comment]
For those using Tensorflow 2.2 or above, Manually Downloading the missing files from [https://github.com/tensorflow/models/tree/master/research/object_detection/meta_architectures](https://github.com/tensorflow/models/tree/master/research/object_detection/meta_architectures) can fix it
