### ISSUE TITLE
Cant't make quantization for op that tflite doesn't support

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#55605]
I will use tf.raw_ops.CropAndResize as an example.

This is how I define the op:
with tf.compat.v1.Session() as sess:
    inputs  = tf.raw_ops.Placeholder(dtype = tf.float32, shape = [1,18,18,8], name = "input")
    boxes = tf.raw_ops.Placeholder(dtype = tf.float32, shape = [1,64,4], name = "boxes")
    zeros = [0,0,0,0]
    zeros = zeros + zeros + zeros + zeros
    zeros = zeros + zeros + zeros + zeros
    crop_size = [18, 18]
    out = tf.raw_ops.CropAndResize(image=inputs, boxes= boxes, box_ind=zeros, crop_size=crop_size)
graph = tf.compat.v1.get_default_graph()
graph_def = graph.as_graph_def()
output_graph_def = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['output'])
with tf.io.gfile.GFile(save_name, 'wb') as f:
    f.write(graph_def.SerializeToString())

This is part of code I convert the .pb to .tflite and make quantization:
model = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(graph_def_file = pb_name, input_arrays=["input","boxes"],output_arrays=["CropAndResize"])
model.optimizations = [tf.lite.Optimize.DEFAULT]
model.representative_dataset = representative_dataset
model.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
model.inference_input_type = tf.uint8  # or tf.uint8
model.inference_output_type = tf.uint8  # or tf.uint8
model.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
model.allow_custom_ops = True
tflite_model = model.convert()
with open(tflite_name, 'wb') as f:
    f.write(tflite_model)

I have some questions during this process:
1. Can I use SaveModel to save this single layer model?
2. I don't know why I failed to quantize this model. But I could convert it from .pb to .tflite without quantization successfully. What's more, I can quantize a similar single conv layer model successfully, with similar way above.

**Comment by mohantym** [comment]
Hi @njuhang ! Could you please share the Complete code as Colab gist? I was getting value error in [above code](https://colab.sandbox.google.com/drive/1tL0SlyHl-SMFc_gz9mQX6V5K9KMhIzRo?resourcekey=0-U8aaOyiUddMu_gpJTWBlhQ#scrollTo=rFaRvhLPEUW0).  Yes! It is possible to get a single layer model by using v2 apis and [tf.keras.Model](https://www.tensorflow.org/api_docs/python/tf/keras/Model) . Thanks!

**Comment by njuhang** [comment]
I have update the code here:
https://colab.research.google.com/gist/njuhang/a9e8fe57a0d3e677093d5b84073b7d7c/github_55605.ipynb#scrollTo=rFaRvhLPEUW0

I am sorry for not explaining my 1st question explicitly. The point is not single layer model, but model with layer defined in raw_op or other package rather than keras.layer. For example, tf.raw_ops.CropAndResize. I wonder if I can save them with SaveModel method.

**Comment by mohantym** [comment]
Hi @njuhang ! I am going through this issue now . I was suggesting to create a class and use **tf.raw_ops.CropAndResize(image=inputs, boxes= boxes, box_ind=zeros, crop_size=crop_size) function** under a [tf.function](https://www.tensorflow.org/api_docs/python/tf/function) to call it as concrete function later. You can then tf.saved_model method to save the model and tf.lite.TFLiteConverter.get_concrete_function to load in the converter. Thank you!

**Comment by njuhang** [comment]
Thanks, I got to know how to convert by concrete function. 
But what about the question2? I still have no idea how to quantize this op.

**Comment by mohantym** [comment]
@njuhang ! tf.raw_ops.CropAndResize is already in supported [select ops](https://www.tensorflow.org/lite/guide/op_select_allowlist) list . Can you only go with this [select ops](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model) syntax (remove custom_ops = true and integer quantization) after loading interpreter from concrete function and let us know the difference? You can also visualize your Tflite model using [netron app ](https://netron.app/)for confirmation . Thanks!

**Comment by njuhang** [comment]
Sorry for long time no reply. I'll take a try and respond to you soon.

**Comment by njuhang** [comment]
I got an error after I remove converter.allow_custom_ops = True:
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select.
So I think this line of code is compulsory for tflite model convert. 
Now  the point is, I can convert it successfully when I remove these lines:

model.optimizations = [tf.lite.Optimize.DEFAULT]
model.representative_dataset = representative_dataset
model.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
model.inference_input_type = tf.uint8 # or tf.uint8
model.inference_output_type = tf.uint8 # or tf.uint8
model.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

That is to say, no quantization for convert.

Thanks.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? Thanks!

**Comment by mohantym** [comment]
Hi @njuhang !
I was able to get a tflite model in [2.10](https://colab.research.google.com/gist/mohantym/6a5f95299c412465f31b66d00b28ff1e/github_55605.ipynb#scrollTo=g7cwVSaZp74x) , but input and output dtype is int32. 
will that be fine ?
Thank you!
