### ISSUE TITLE
C++ Using TensorflowLiteC in iOS with Flex delegate TensorflowLiteCSelectTfOps

### ISSUE THREAD

**Issue by fatihkiralioglu** [tensorflow/tensorflow#55602]
I try to make inference with flex delegate supported tflite model in iOS using C++ language.

following the instructions in:
https://www.tensorflow.org/lite/guide/ops_select

I have installed the following pods:

   pod 'TensorFlowLiteC', '~> 2.5.0'

   pod 'TensorFlowLiteSelectTfOps', '~> 2.5.0'

and I have also added linker flag:

-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps

But during inference I observe:

 **Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.**

is TensorFlowLiteSelectTfOps  not suitable for C++? or what am I doing wrong here?

Thanks

**Comment by mohantym** [comment]
Hi @fatihkiralioglu ! Could you please make below changes in the Pod file and let us know the results? Thanks!
```
pod 'TensorFlowLiteSwift'                        # or 'TensorFlowLiteObjC' 
pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
```

**Comment by mohantym** [comment]
@fatihkiralioglu !Not fully confident on that. Please try once with current published pods if it does not work switch to Bazel method. You can refer to this [document](https://www.tensorflow.org/lite/guide/ops_select#cc) for Flex ops. Thanks!
