### ISSUE TITLE
tensorflow 2.8 neural network model training cannot be run as multiprocess even though the training data is created by keras.utils.Sequence 

### ISSUE THREAD

**Issue by umusa** [tensorflow/tensorflow#55609]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu (18.04.6)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pip install tensorflow==2.8.0
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I am trying to train a neural network model built by tf2.8 ans keras 2.8.
I would like to train the model with **"multiprocess".** to improve the training performance.
The following url shows that only keras.utils.Sequence is supported for multiprocess.
https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit

" "use_multiprocessing"  Boolean. **Used for generator or [keras.utils.Sequence](https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence) input only**. If True, use process-based threading. If unspecified, use_multiprocessing will default to False. Note that because this implementation relies on multiprocessing, you should not pass non-picklable arguments to the generator as they can't be passed easily to children processes."

**My code (tf2.8):** 

------------------------------
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import Sequence

class MyDataGenerator(Sequence):
    def __init__(self, train_file_paths, batch_size, train_data_size, epoch ):

        self.file_paths = train_file_paths
        self.batch_size = batch_size
        self.index_and_filename = defaultdict(str)
        self.cur_file_index = 0
        self.total_file_nums = 0
        self.num_parallel_calls = -1
        self.set_files_indices()
        self.on_epoch_end()
       
    def __len__(self):
        return 100
   
    def __getitem__(self, index):
        cur_train_file_path = self.index_and_filename[self.cur_file_index]
        features_and_labels = self.__data_create(cur_train_file_path)
        self.cur_file_index += 1
        features, labels = next(iter(features_and_labels))
        return features, labels
   
    def  on_epoch_end(self):
        self.cur_file_index = 0
        self.total_file_nums = 0
        
    def  set_files_indices(self):
        for a_file in self.file_paths:
            self.index_and_filename[self.total_file_nums] = a_file
            self.total_file_nums += 1
        
    def data_generation(self, file_path):
       
        def process_sample(input_dataset):
            features = tf.io.parse_single_example(input_dataset, [some feature names])
            labels = tf.io.parse_single_example(input_dataset, LABEL_NAME)[LABEL_NAME]
            return (features, labels)
       
        file_paths_ds = tf.data.Dataset.from_tensors(file_path)
       
        all_features_dataset = file_paths_ds.interleave(lambda x: tf.data.TFRecordDataset(x,  compression_type='GZIP'),
                                        cycle_length=10, num_parallel_calls=-1, deterministic=False)
        
        all_features_dataset = all_features_dataset.map(lambda x: process_sample(x),
                                                num_parallel_calls=-1,
                                                deterministic=False)
       
        all_features_dataset = all_features_dataset.shuffle(100)
        all_features_dataset = all_features_dataset.batch(self.batch_size, drop_remainder=True)
        all_features_dataset = all_features_dataset.cache()
        return all_features_dataset

train_data_generator = MyDataGenerator(train_data_path, 2, 10000, 2)
test_data_generator = MyDataGenerator(train_data_path, 2, 1000, 2)

model.fit(train_data_generator,
          epochs=2
          steps_per_epoch = 100,
          validation_data=test_data_generator,
          validation_steps=10,
          **workers=1,
          use_multiprocessing=False**)

```

If I run model.fit as:

```
model.fit(train_data_generator,
          epochs=2,
          steps_per_epoch = 100 ,
          validation_data=test_data_generator,
          validation_steps=10),
          workers=1,
          use_multiprocessing=False)
```

I got error: 

```
InvalidArgumentError: ValueError: Could not find callback with key=pyfunc_44 in the registry.
    Traceback (most recent call last):

   File "lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 259, in __call__
    raise ValueError(f"Could not find callback with key={token} in the "

    ValueError: Could not find callback with key=pyfunc_44 in the registry.

	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
```

------------------
If I run model.fit as:

 ```
model.fit(train_data_generator,
          epochs=2,
          steps_per_epoch = 100 ,
          validation_data=test_data_generator,
          validation_steps=10),
          workers=2,
          use_multiprocessing=True)
```

The whole training process is frozen and made no progress and no errors popped.
It seems that there is a deadlock ? 
I have also tried tf2.9, got the same error. 
Could anybody let me know what I did wrong ? 
I missed something ? 

thanks

**Describe the expected behavior**

The 

    model.fit(train_data_generator,
          epochs=2,
          steps_per_epoch = 100 ,
          validation_data=test_data_generator,
          validation_steps=10),
          workers=2,
          use_multiprocessing=True)

should not be frozen and all CPU cores should be busy in working on data loading and model training. 

And, if run it by single-process, 

```
model.fit(train_data_generator,
          epochs=2,
          steps_per_epoch = 100 ,
          validation_data=test_data_generator,
          validation_steps=10),
          workers=1,
          use_multiprocessing=False)
```
it should also works well. No errors.

**Comment by tilakrayal** [comment]
Hello @umusa,
On running the given code snippet, I am facing an different error.Can you please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2316d92952b12ccfb40bf15e4a282e2c/untitled300.ipynb) and requesting to provide the complete code to debug the issue.Thanks!

**Comment by umusa** [comment]
@tilakrayal , this code needs to access some data files, which are not available to access here. Can you please check the logic to confirm that I do not do anything wrong. thanks

**Comment by tilakrayal** [comment]
@umusa ,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a complete code and the dependencies you are using.Thanks!
