### ISSUE TITLE
request for feature gather and matmul

### ISSUE THREAD

**Issue by Bayes-Song** [tensorflow/tensorflow#55600]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.7.1
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
This function can realize that the corresponding weight is taken from the matrix B according to the index given by the matrix C and then multiplied by the matrix A.
A: [batch, h]
B: [num, h, d]
C: [batch, ]
out: [batch, d]
batch >> num
```python
for i, j in enumerate(C):
   out[i] = matmul(A[i], B[j])
```
Currently this function can be implemented by tf.gather then tf.matmul. However, it will waste a lot of gpu memory due to the need to define an intermediate variable W.
```python
W = tf.gather(B, C)
out = tf.matmul(A, W)
```
It can also be implemented by one hot matmul. However the time complexity of the calculation will be very high.
```python
tmp = tf.one_hot(C, depth=num)
out = tf.enisum('bh,bn,nhd->bd', A, tmp, B)
```
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
This function can be applied to the moe model to achieve the assignment of experts strictly according to the probability of the router. Avoids the limitations of the expert capacity currently required. 
**Any Other info.**
No

**Comment by cantonios** [comment]
To make sure I'm on the same page: you want to add a new op that does the combined gather+matmul?  So this *will* modify the API (i.e. it will extend it by introducing a `tf.gather_and_matmul(...)` op).

Any new op will need to be implemented for all backends (CPU/GPU/XLA).  You will also need to demonstrate the savings are worth the extra code complexity/maintenance burden.

Feel free to submit a PR, and we can take a look.

**Comment by Bayes-Song** [comment]
Sorry I didn't correctly understand the meaning of the question "Will this change the current api? How?". Yes, this will modify the API by adding an extra op tf.gather_and_matmul.
Below I will introduce the improvement that this op can bring in combination with some technical details in the switch transformer. Switch Transformer is a kind of sparsely activated model. 
In normal model
```python
output = FFN(input)
```
In sparsely activated model, there will be multiple FFN as multiple experts and a router to determine the assignment of experts
```python
assign_prob = router(input)
assign_index = argmax(assign_prob, axis=-1)
output = [FFNs[k](input[i]) for i, k in enumerate(assign_index)]
```
Through the above sparse activation operation, a large number of parameters are added (the FFN parameter are expanded by num_experts) while only a small amount of computation is added (only the router which is a dense layer). 
However, due to the limitation of tensorflow dynamic graph, the input shape of each expert should be the same. The actual implementation is shown below
![image](https://user-images.githubusercontent.com/16948304/164589552-ad27fbcb-3a96-46e9-88c1-ee80122746d6.png)
![image](https://user-images.githubusercontent.com/16948304/164589577-1f960b75-6db8-48bd-a8a0-7e5890b09e64.png)
https://arxiv.org/pdf/2101.03961.pdf
There will be two problems here. The first is that some samples will not pass through any experts, and the second is that they cannot be assigned strictly according to the maximum probability.
In most cases, the FFN will be the combination of multiple dense layer. So this problem can be solved by the above gather_and_matmul op. 
```python
assign_prob = router(input)
assign_index = argmax(assign_prob, axis=-1)
output = tf.gather_and_matmul(FFN_weight, input, assign_index)
```
It is theoretically possible to simulate gather_and_matmul by existing operations gather or one hot matmul. 
```python
assign_prob = router(input)
assign_index = argmax(assign_prob, axis=-1)
assigned_weight = tf.gather(FFN_weight, assign_index)
output = tf.matmul(input, assigned_weight)
```
However, the shape of FFN_weight will be [num_experts, h1, h2] (num_experts 16/32/64), but the shape of the intermediate variable assigned_weight will be [batch, seq_length, h1, h2]. batch * seq_length (eg. 64 * 128) is far more than num_experts. This intermediate variable will waste a lot of memory and cause oom. 
```python
assign_prob = router(input)
assign_index = argmax(assign_prob, axis=-1)
assign_index_onehot = tf.one_hot(assign_index, depth=num_experts)
out = tf.enisum('blh,bln,nhd->bld', input, assign_index_onehot, FFN_weight)
```
The second avoids defining an intermediate variable, but the computational complexity is very high. 
The actual computational complexity required is batch*seq_length*h*d. However the computational complexity of the second is batch*seq_length*h*d*num_experts. 
In my experiments this will be three to four times slower (num_experts=8).

**Comment by cantonios** [comment]
Will something like this work:
```
@tf.function
def gather_and_matmul(a, b, c):
  return tf.map_fn(lambda i: tf.matmul(a[:,:], b[i,:,:]), c, fn_output_signature=a.dtype)
```

We don't normally add merged ops like this to the API.  If it's an efficiency issue, we often instead rely on graph optimization passes that can fuse ops and eliminate intermediaries.  The issue with modifying the API is that it adds a lot of maintenance burden, and needs to be supported on all platforms/backends - so the change needs to be strongly justified.

**Comment by Bayes-Song** [comment]
> 

Thanks for your reply, I will try your proposed solution as soon as possible.

**Comment by Bayes-Song** [comment]
> Will something like this work:
> 
> ```
> @tf.function
> def gather_and_matmul(a, b, c):
>   return tf.map_fn(lambda i: tf.matmul(a[:,:], b[i,:,:]), c, fn_output_signature=a.dtype)
> ```
> 
> We don't normally add merged ops like this to the API. If it's an efficiency issue, we often instead rely on graph optimization passes that can fuse ops and eliminate intermediaries. The issue with modifying the API is that it adds a lot of maintenance burden, and needs to be supported on all platforms/backends - so the change needs to be strongly justified.

Thanks for your suggestion, I will try your proposed solution as soon as possible

**Comment by gogettp11** [comment]
Hello, I am new to contributing TensorFlow. Shouldn't this issue be marked as closed?

**Comment by cantonios** [comment]
Potentially.  The user hasn't responded back to report that it works for them.
