### ISSUE TITLE
[Memory Issue]: Dst tensor is not initialized

### ISSUE THREAD

**Issue by IchiruTake** [tensorflow/tensorflow#55614]
Summary: I believe this issue is fired by Memory Issue with GPU on Tensorflow 2.8 and Tensorflow-GPU 2.8.

Configuration:
- Python 3.8.12
- GPU: NVIDIA Quadro P1000 Notebook 4Gb (InUse: ~ 3Gb)
- RAM: 16 Gb
- OS: Windows 10 Pro
Config 1: Tensorflow: 2.8 - Tensorflow-GPU: 2.8 - TF-Addons: 0.16.1 - Keras: 2.8
Config 2: Tensorflow: 2.5.x - Tensorflow-GPU: 2.5.x - TF-Addons: 0.15

Description: The following model was just a super-cheap model using only Dense, Add, and Concatenation with only 8M+ parameters, but the warning warns me about memory overflow and stop my training on PyCharm

Total behaviour: 
(Batch Size: 256)
- I have been training this model (8M+) and two heavier versions (48M+, and 55M+) on Tensorflow 2.3.x and 2.5.x but Tensorflow did not raise to me either warning and error and the model still worked fine. The model received four input with `dtype='uint8'`, totally 14930 features per vector using 256 batch size with Adam optimizer.
- But since I upgraded my Tensorflow to 2.8, this issue arised on both models, even I have pruned my model to 8M+ parameters with 13674 features per vector only (same dtype=uint8). 
- In the same code, I always used `from tensorflow.keras import ...` for both versions: 2.5- and 2.8

The memory log is displayed in PyCharm 2021.3.3
[memory_p07-15.pdf](https://github.com/tensorflow/tensorflow/files/8485684/memory_p07-15.pdf)

Behaviour Prediction: I believed this is raised in version 2.6 due to the introduction of API shifting. Please check on that. Also, the PyCharm could not track the code + autocompletion when Tensorflow >= 2.6 (It worked only with Tensorflow 2.3 - 2.5*).
* I did not try installing previous version of Tensorflow

**Comment by sushreebarsa** [comment]
@IchiruTake 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
