### ISSUE TITLE
[XLA] Different JIT compile behavior from TF2.7

### ISSUE THREAD

**Issue by wenscarl** [tensorflow/tensorflow#55610]
For the customized code below, I have seen such a error at runtime when xla is turned on. This does NOT appear in TF2.7.
`2022-04-13 19:49:36.873241: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at xla_ops.cc:436 : INVALID_ARGUMENT: Fail to proof the equality of two dimensions at compile time: %multiply.144 = s32[] multiply(s32[] %constant.142, s32[] %add.1), metadata={op_type="Reshape" op_name="Reshape_3"} vs %add = s32[] add(s32[] %reduce.109, s32[] %constant.17)`

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Ubuntu 20.04.4 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version:2.8.0
- Python version: 3.8
- GCC/Compiler version (if compiling from source): gcc 10
- CUDA/cuDNN version: 11.6
- GPU model and memory: V100, 32G

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np
display_id_counter = tf.Variable(0, trainable=False, dtype=tf.float64)

@tf.function
def evaluation_step(x, y, predictions):
    dummy_loss = 0.9
    predictions = tf.reshape(predictions, [-1])
    predictions = tf.cast(predictions, tf.float64)
    display_ids = x
    display_ids = tf.reshape(display_ids, [-1])
    labels = tf.reshape(y, [-1])
    sorted_ids = tf.argsort(display_ids)
    display_ids = tf.gather(display_ids, indices=sorted_ids)
    predictions = tf.gather(predictions, indices=sorted_ids)
    labels = tf.gather(labels, indices=sorted_ids)
    _, display_ids_idx, display_ids_ads_count = tf.unique_with_counts(
        display_ids, out_idx=tf.int64)
    pad_length = 30 - tf.reduce_max(display_ids_ads_count)
    preds = tf.RaggedTensor.from_value_rowids(
        predictions, display_ids_idx).to_tensor()
    labels = tf.RaggedTensor.from_value_rowids(
        labels, display_ids_idx).to_tensor()
    labels_mask = tf.math.reduce_max(labels, 1)
    preds_masked = tf.boolean_mask(preds, labels_mask)
    labels_masked = tf.boolean_mask(labels, labels_mask)
    labels_masked = tf.argmax(labels_masked, axis=1, output_type=tf.int32)
    labels_masked = tf.reshape(labels_masked, [-1, 1])

    preds_masked = tf.pad(preds_masked, [(0, 0), (0, pad_length)])
    _, predictions_idx = tf.math.top_k(preds_masked, 12)
    indices = tf.math.equal(predictions_idx, labels_masked)

    shape = tf.cast(tf.shape(indices)[0], tf.float64)
    display_id_counter.assign_add(shape)

DIM = 102400
tf.config.optimizer.set_jit(True)
for step in range(200):
    pre = np.random.random((DIM, 1))
    y_tmp = np.zeros((DIM, 1), dtype=float)

    num_ones = np.random.randint(1, DIM+1, 1)
    id_one = np.random.randint(0, DIM, num_ones)
    for i in id_one:
        y_tmp[i][0] = 1.
    x_tmp = np.random.randint(0, DIM, (DIM, 1), dtype=np.int64)
    evaluation_step(x_tmp, y_tmp, pre)
```

Tracked down to commit [ac4575](https://github.com/tensorflow/tensorflow/commit/ac457560364f18f24ae506d978f2ab5f04aa501b).

**Comment by jurahul** [comment]
@cheshire can you triage to check where this error is coming from?

**Comment by cheshire** [comment]
Right, what has changed is that `tf.where` became compilable in autoclustering, and then the compiler tries at compile time to prove equality of dimensions from two dynamic outputs and fails.

Do you need a general solution, or a workaround? Switching this line (https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/xla/service/gpu/gpu_compiler.cc;l=440?q=padder%20f:gpu_compiler) to `kIgnore`  would solve the issue by ignoring the check.

We can also give you a flag to switch those without modifying TF. Or do you need a general solution which always works?

**Comment by wenscarl** [comment]
Thanks @cheshire. Making `tf.where` XLA compilable in autoclustering may results into a perf regression. Say in a training loop, XLA will trigger compilation multiple times every time seeing a data with different size.  See the snapshot from profiler.
![recompile](https://user-images.githubusercontent.com/25590028/163456405-41e50e98-69b6-4d07-9410-9867cd067fd2.PNG)
 Reverting this commit resolve this.  I would prefer to have a switch flag to turn it off.

**Comment by cheshire** [comment]
@wenscarl OK it might make sense to not compile tf.where in autoclustering environment altogether then. I can make this change.

> Say in a training loop, XLA will trigger compilation multiple times every time seeing a data with different size

Do you have a repro I could try? XLA compiles up to the upper bound of the `tf.where` output, not to the concrete bound seen at runtime, so it seems bizarre it would recompile.

**Comment by cheshire** [comment]
@wenscarl Actually do you want to send a patch disabling tf.where autoclustering?

**Comment by wenscarl** [comment]
@cheshire 
> Do you have a repro I could try?
I don't have a lite repro. The regression is observed from [wideanddeep](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Recommendation/WideAndDeep) model. With this commit, XLA compiled 3 times as indicated by the above snapshot. Turning off, only 1 XLA jit compile as shown below.
![image](https://user-images.githubusercontent.com/25590028/163497115-a399d02c-76a6-4862-9d63-197ed97c7e51.png). The recompilation may not be directly caused by tf.where autoclustering, but turning-off is a WAR.

**Comment by wenscarl** [comment]
For the sample code above, the compile time for cluster_1 which include tf.where, is about 10sec while for other clusters on ms level. Recompilation couldn't be reproduced by the sample code, but once happen, it would stall the cpu for 10 sec long.

**Comment by wenscarl** [comment]
@cheshire 
> Actually do you want to send a patch disabling tf.where autoclustering?
Yes. `tf_xla_ops_to_cluster` serves a similar purpose but not quite the granularity we want.  I would like to propose a `tf_xla_ops_cluster_blacklist` under `TF_XLA_FLAG` which takes comma separated op names like where or unique. Does that sound good?

**Comment by cheshire** [comment]
Thanks! We already have a struct for enabling/disabling such ops, in
compilability_check_util. Re-adding tf.where there and disabling it by
default for autoclustering could make sense.

**Comment by mohitrajpal1** [comment]
This is also causing an issue for me. Do you have a pointer in TF code where I can hack together an addition to not compile tf.where?

**Comment by wenscarl** [comment]
A PR is opened [here](https://github.com/tensorflow/tensorflow/pull/55808).

**Comment by wenscarl** [comment]
PR merged. Closing.
