### ISSUE TITLE
tf.io.encode png doesn't work when trying to write array to png

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tensorflow#55615]
Please see here.  https://colab.research.google.com/drive/1ayBIErWSDAZGJ6B_CjeqraJyMAzEWSyv?usp=sharing

I am trying to write a tensor to a png. As seen here, when I take the encoded bytes and write it a file using python, it doesn't work. Trying opening the image it gets corrupted 
When I use tf.io.write_file it works. I also tried taking a png and using tf.io_decode_png and than tf.io.encoding_png and the image string bytes differ from the original png. I am using tensorflow serving and using this png result through the rest api, where I don't have access to tf.io.wrte_file so I was wondering what encode_png does differently, than traditional png encodings.

**Comment by tilakrayal** [comment]
Hello @rohanmuplara ,
The error log stating that `write() takes exactly one argument (0 given)` which will be in bytes, not in str type.I request you please try to execute the code by providing the expected input.Thanks!

**Comment by rohanmuplara** [comment]
@tilakrayal please try again. I was just playing around in colab and forgot to return it to proper state. I apologize for that. The error is one I was describing above.

**Comment by rohanmuplara** [comment]
@tilakrayal sorry for repining but I haven't been able to get it to work for any other image formats. I have also tried other formats here and they are still not working. I have added this https://colab.research.google.com/drive/13Y4ET8jAHZDq7qwUYgg8nuBkxqniUqGu#scrollTo=kTeKBHg-kcaG.

**Comment by tilakrayal** [comment]
@rohanmuplara ,
On running the given code snippet, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory`. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/61f8e2745d17296e957284e7d4a73adf/55615.ipynb).

**Comment by rohanmuplara** [comment]
You have to upload a sample image for that cell because it reads it locally. Wasn't sure how it was supposed to work otherwise.  https://user-images.githubusercontent.com/47044724/163808624-2f435116-f8cd-4cb2-9be0-116c16fe56fe.png

**Comment by rohanmuplara** [comment]
@tilakrayal I have gotten rid of having to upload a sample image to make it easier. I also added a video https://www.loom.com/share/4b32b330a0e742cab2ea3a1a9af11b22 here. I am also happy to jump on google meet or whatever is required

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf [v2.7](https://colab.research.google.com/gist/tilakrayal/cf1fe8ad48178485690bb9f9553f04c6/55615_2_7.ipynb), [v2.8](https://colab.research.google.com/gist/tilakrayal/1e8292cafef6c3312b5756750d9a615f/55615-2-8.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/ce2f4f1b6d881c5504ef2866eeb2b6a1/55615_nightly.ipynb).Please find the attached gist.

**Comment by cantonios** [comment]
The returned value from `tf.io.encode_png` is a `Tensor` of type `string`, where the string value is the image bytes.

Trying to write this directly to a file in python attempts to write the `Tensor` object itself, which is a container and pointer to the underlying data.  It does not write the string contents.  Using `tf.io.write_file` will write the underlying input `Tensor` contents to the file, which is why it works.

To write the contents without `tf.io.write_file`, you need to extract the string contents and write that directly.
```
with open("/content/result_python_write.png", "wb") as f:
  f.write(b.numpy())  # Get the string contents
```
