### ISSUE TITLE
Android - abort crash.

### ISSUE THREAD

**Issue by ahmadbajwa8282** [tensorflow/tensorflow#55618]
I'm having this crash on android 10.

**Dependencies**

implementation 'org.tensorflow:tensorflow-lite:2.8.0'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.8.0'

Stack Trace:

abort

pid: 0, tid: 0 >>> com.humbbles.imagenes <<<

backtrace:
  #00  pc 000000000005ec46  /apex/com.android.runtime/lib/bionic/libc.so (abort+166)
  #00  pc 000000000003606d  /system/lib/libc++.so (abort_message+88)
  #00  pc 00000000000361e9  /system/lib/libc++.so (demangling_terminate_handler()+160)
  #00  pc 0000000000044ecb  /system/lib/libc++.so (std::__terminate(void (*)())+2)
  #00  pc 00000000000446cf  /system/lib/libc++.so (__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)+12)
  #00  pc 0000000000044631  /system/lib/libc++.so (__cxa_throw+72)
  #00  pc 000000000007fe5f  /system/lib/libc++.so (std::__1::__throw_system_error(int, char const*)+86)
  #00  pc 000000000000e645  /system/lib/libEGL.so (android::egl_cache_t::setBlob(void const*, long, void const*, long)+228)
  #00  pc 000000000000e4fd  /system/lib/libEGL.so (android::setBlob(void const*, long, void const*, long)+20)
  #00  pc 0000000000141aa8  /vendor/lib/egl/libGLES_mali.so
  #00  pc 0000000000141ddc  /vendor/lib/egl/libGLES_mali.so
  #00  pc 00000000003cabe8  /vendor/lib/egl/libGLES_mali.so
  #00  pc 0000000002bfc13b  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfbe99  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfbd59  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfc91d  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfc511  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfc1e1  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002bfb1a1  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b50861  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b51477  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b51203  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b51095  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b5100d  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002b606c1  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 00000000020ca769  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 00000000020c88c7  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000001796063  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002061309  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 000000000206109d  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002060e01  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 0000000002060d1f  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 00000000020df89d  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 00000000020df0b7  /data/app/com.google.android.trichromelibrary_469209830-OMAU-ijYS8rmP_RtBvJXIg==/base.apk!libmonochrome.so (offset 0x664000)
  #00  pc 00000000000a6077  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #00  pc 0000000000060131  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

**Comment by mohantym** [comment]
Hi @ahmadbajwa8282 ! Could you please fill the template to help expedite the issue? Thanks!
